pociar	pociàsimo	V;IPFV;SBJV;PL;1;PST
arivar	arivasi	V;IPFV;SBJV;SG;2;PST
fondar	fonda	V;IMP;PL;3;LGSPEC1
strabucar	strabucava	V;IPFV;IND;PL;3;PST
apostrofar	apostrofa	V;IND;PL;3;PRS
partir	partise	V;IND;PL;3;PRS
daquar	daquémo	V;SBJV;PL;1;PRS;LGSPEC1
sbrisiar	sbrisiava	V;IPFV;IND;PL;3;PST
semenar	semeni	V;SBJV;SG;2;PRS
invidiar	invidiar	V;NFIN
łavorar	łavora	V;IMP;PL;3;LGSPEC1
arar	ara	V;IMP;SG;3;LGSPEC1
pociar	pocie	V;IMP;SG;3;LGSPEC2
spoliar	spolia	V;SBJV;SG;1;PRS;LGSPEC2
sarare	sarase	V;IPFV;SBJV;SG;3;PST
spoliar	spoliase	V;IPFV;SBJV;SG;3;PST
cargar	cargone	V;SBJV;PL;1;PRS;LGSPEC2
dettar	dettòn	V;IND;PL;1;PRS;LGSPEC2
sfrixar	sfrixarémo	V;IND;PL;1;FUT
conzsar	conzsa	V;SBJV;PL;3;PRS;LGSPEC2
tardigar	tardighé	V;IND;PL;2;PRS
aderir	aderì	V;IMP;PL;2
rancurar	rancurasi	V;IPFV;SBJV;SG;2;PST
cantar	canta	V;IMP;PL;3;LGSPEC1
covèrzar	covèrzarisi	V;COND;PL;2
rivar	riva	V;IMP;SG;3;LGSPEC1
desbrojar	desbrojava	V;IPFV;IND;PL;3;PST
roxegar	roxegarìa	V;COND;SG;3
noar	noasi	V;IPFV;SBJV;SG;2;PST
colpir	colpisa	V;SBJV;PL;3;PRS
crédar	créda	V;SBJV;SG;3;PRS
ałestir	ałestise	V;IPFV;SBJV;PL;3;PST
pestar	pesta	V;SBJV;SG;3;PRS;LGSPEC2
sugerir	sugerirìa	V;COND;PL;3
pontar	pontarà	V;IND;PL;3;FUT
spiegar	spiegarìa	V;COND;PL;3
caminar	caminarè	V;IND;PL;2;FUT
copar	copi	V;IND;SG;2;PRS;LGSPEC1
amar	amavi	V;IPFV;IND;PL;2;PST
arivar	ariva	V;IMP;SG;3;LGSPEC1
tacar	tacarà	V;IND;SG;3;FUT
realisar	realisava	V;IPFV;IND;SG;1;PST
sgnaolar	sgnaolase	V;IPFV;SBJV;PL;3;PST
arivar	arivavi	V;IPFV;IND;PL;2;PST
vałer	vała	V;SBJV;PL;3;PRS
petar	petasi	V;IPFV;SBJV;PL;2;PST
doparar	doparasi	V;IPFV;SBJV;SG;2;PST
obligar	obligava	V;IPFV;IND;SG;1;PST
postar	posta	V;SBJV;SG;3;PRS;LGSPEC2
stropar	stroparìsimo	V;COND;PL;1
sujerir	sujerisi	V;IMP;SG;2
dettar	dettarò	V;IND;SG;1;FUT
desbrojar	desbrojava	V;IPFV;IND;SG;1;PST
intrigar	intrigarisi	V;COND;SG;2
slatar	slatava	V;IPFV;IND;SG;1;PST
bałar	bałé	V;IND;PL;2;PRS
supiàr	supia	V;SBJV;SG;1;PRS;LGSPEC2
arivar	arivé	V;IND;PL;2;PRS
visuałixar	visuałixémo	V;IND;PL;1;PRS;LGSPEC1
finansiar	finansiarà	V;IND;PL;3;FUT
ametar	ameto	V;IND;SG;1;PRS
arivar	arivava	V;IPFV;IND;PL;3;PST
sachegiar	sachegiarisi	V;COND;PL;2
conbatar	conbatisi	V;IPFV;SBJV;PL;2;PST
carołar	carołé	V;IND;PL;2;PRS
costar	costòn	V;IND;PL;1;PRS;LGSPEC2
intrigar	intrigase	V;IPFV;SBJV;SG;3;PST
morir	moririsi	V;COND;PL;2
tastar	taste	V;IMP;PL;3;LGSPEC2
bójar	bójarìsimo	V;COND;PL;1
visuałixar	visuałixe	V;IMP;PL;3;LGSPEC2
sbregar	sbrega	V;SBJV;SG;3;PRS;LGSPEC2
arestar	arestarè	V;IND;PL;2;FUT
gòder	gòdì	V;IND;PL;2;PRS
asistar	asistarè	V;IND;SG;2;FUT
segar	segarìa	V;COND;SG;3
intivar	intive	V;IMP;PL;3;LGSPEC2
cuèrzar	cuèrza	V;IMP;SG;3
gòder	gòdése	V;IPFV;SBJV;PL;3;PST
ciapar	ciapòn	V;IND;PL;1;PRS;LGSPEC2
gòder	gòdo	V;IND;SG;1;PRS
svejar	svejavi	V;IPFV;IND;SG;2;PST
parlar	parlarémo	V;IND;PL;1;FUT
morsegar	morsegava	V;IPFV;IND;PL;3;PST
partir	partirìa	V;COND;SG;1
macar	machi	V;IND;SG;2;PRS
bałar	bałasi	V;IPFV;SBJV;PL;2;PST
descargar	descargarisi	V;COND;SG;2
tacar	tacarisi	V;COND;PL;2
pensar	pensarémo	V;IND;PL;1;FUT
intivar	intivarìa	V;COND;PL;3
insegnar	insegnase	V;IPFV;SBJV;SG;1;PST
bałar	bałasi	V;IPFV;SBJV;SG;2;PST
nàsar	nàso	V;IND;SG;1;PRS
fondar	fondarà	V;IND;PL;3;FUT
colpir	colpirìa	V;COND;SG;3
castrar	castrémo	V;IND;PL;1;PRS;LGSPEC1
suar	suarìa	V;COND;SG;3
strabucar	strabuchi	V;SBJV;SG;2;PRS
tamixar	tamixé	V;IMP;PL;2
macar	macarà	V;IND;SG;3;FUT
obligar	obligava	V;IPFV;IND;SG;3;PST
supiàr	supiava	V;IPFV;IND;SG;3;PST
rìdar	rìdarìa	V;COND;SG;3
bruscar	brusché	V;IND;PL;2;PRS
parlar	parlar	V;NFIN
bruscar	bruscarè	V;IND;SG;2;FUT
sgnaolar	sgnaolémo	V;SBJV;PL;1;PRS;LGSPEC1
rivar	rivava	V;IPFV;IND;SG;1;PST
influensar	influensarìa	V;COND;SG;1
baxar	baxo	V;IND;SG;1;PRS
scrivar	scrivarè	V;IND;SG;2;FUT
spiar	spiavi	V;IPFV;IND;PL;2;PST
finansiar	finansie	V;SBJV;PL;3;PRS;LGSPEC1
stropar	stropavi	V;IPFV;IND;SG;2;PST
siełier	siełiémo	V;IND;PL;1;PRS
pestar	pestasi	V;IPFV;SBJV;SG;2;PST
traversar	traversa	V;IND;SG;3;PRS
dettar	dettarémo	V;IND;PL;1;FUT
parlar	parlé	V;IND;PL;2;PRS
entrar	entrone	V;SBJV;PL;1;PRS;LGSPEC2
tardigar	tardigarìa	V;COND;PL;3
spojar	spoje	V;SBJV;SG;3;PRS;LGSPEC1
deventar	deventémo	V;SBJV;PL;1;PRS;LGSPEC1
rìdar	rìde	V;IND;SG;3;PRS
voxar	voxarìsimo	V;COND;PL;1
visuałixar	visuałixasi	V;IPFV;SBJV;SG;2;PST
sbrisiar	sbrisiàsimo	V;IPFV;SBJV;PL;1;PST
amar	amémo	V;IND;PL;1;PRS;LGSPEC1
daquar	daque	V;SBJV;SG;1;PRS;LGSPEC1
apostrofar	apostrofa	V;IMP;SG;3;LGSPEC1
intorcołar	intorcołé	V;SBJV;PL;2;PRS
voltar	volti	V;SBJV;SG;2;PRS
sachegiar	sachegie	V;IMP;SG;3;LGSPEC2
realisar	realisarisi	V;COND;PL;2
roversar	roversémo	V;SBJV;PL;1;PRS;LGSPEC1
pensar	pensa	V;IND;SG;3;PRS
ascrivar	ascrivivi	V;IPFV;IND;PL;2;PST
cantar	cantòn	V;IND;PL;1;PRS;LGSPEC2
exagerar	exageri	V;IND;SG;2;PRS
prodùr	produxarìsimo	V;COND;PL;1
destacar	destacar	V;NFIN
udar	udarà	V;IND;PL;3;FUT
bójar	bójisi	V;IPFV;SBJV;SG;2;PST
strénxar	strénxéa	V;IPFV;IND;SG;1;PST
sałudar	sałudava	V;IPFV;IND;SG;3;PST
tremar	tremarisi	V;COND;SG;2
vołer	vołarè	V;IND;SG;2;FUT
sotomesar	sotomesésimo	V;IPFV;SBJV;PL;1;PST
uxar	uxa	V;IND;PL;3;PRS
somejar	somejavi	V;IPFV;IND;SG;2;PST
sfrixar	sfrixémo	V;IMP;PL;1
łimar	łimarè	V;IND;PL;2;FUT
supiàr	supia	V;IND;SG;3;PRS
daquar	daquarè	V;IND;SG;2;FUT
postar	posta	V;SBJV;PL;3;PRS;LGSPEC2
domandar	domandarisi	V;COND;SG;2
temer	temi	V;SBJV;SG;2;PRS
crédar	crédéa	V;IPFV;IND;SG;3;PST
ofrir	ofrirìa	V;COND;PL;3
vìnsar	vìnsa	V;IMP;PL;3
fondar	fondo	V;IND;SG;1;PRS
tremar	trema	V;IND;SG;3;PRS
realisar	realisa	V;IND;SG;3;PRS
savariare	savariarìa	V;COND;SG;3
slargar	slargar	V;NFIN
stuxar	stuxa	V;IMP;PL;3;LGSPEC1
finansiar	finansiarè	V;IND;PL;2;FUT
uxar	uxava	V;IPFV;IND;SG;3;PST
magnar	magnar	V;NFIN
dettar	dette	V;IMP;SG;3;LGSPEC2
sbregar	sbrega	V;IMP;SG;2
stropar	stropo	V;IND;SG;1;PRS
pestar	peste	V;SBJV;SG;3;PRS;LGSPEC1
spiar	spiarè	V;IND;SG;2;FUT
sperar	spera	V;IND;PL;3;PRS
scóndar	scóndì	V;SBJV;PL;2;PRS
colpir	colpisi	V;IND;SG;2;PRS
daquar	daqué	V;SBJV;PL;2;PRS
vernixar	vernixasi	V;IPFV;SBJV;SG;2;PST
bójar	bójarìa	V;COND;SG;1
sałudar	sałudone	V;SBJV;PL;1;PRS;LGSPEC2
comerçar	comerça	V;SBJV;SG;1;PRS;LGSPEC2
sarar	sarar	V;NFIN
partir	partirìsimo	V;COND;PL;1
sgrafar	sgrafé	V;SBJV;PL;2;PRS
visuałixar	visuałixarisi	V;COND;PL;2
vernixar	vernixava	V;IPFV;IND;SG;3;PST
verxar	verxasi	V;IPFV;SBJV;PL;2;PST
segar	sega	V;SBJV;SG;3;PRS;LGSPEC2
tardigar	tardigase	V;IPFV;SBJV;SG;1;PST
tardigar	tardigasi	V;IPFV;SBJV;PL;2;PST
influensar	influenso	V;IND;SG;1;PRS
strénxar	strénxése	V;IPFV;SBJV;PL;3;PST
ciapar	ciapé	V;IND;PL;2;PRS
dettar	detté	V;IMP;PL;2
èser	geri	V;IPFV;IND;PL;2;PST;LGSPEC1
crédar	créde	V;IND;PL;3;PRS
conbatar	conbato	V;IND;SG;1;PRS
stupar	stupé	V;IND;PL;2;PRS
scuminsiar	scuminsie	V;SBJV;SG;1;PRS;LGSPEC1
restar	restòn	V;IND;PL;1;PRS;LGSPEC2
scuminsiar	scuminsiavi	V;IPFV;IND;PL;2;PST
afitar	afite	V;IMP;SG;3;LGSPEC2
spoliar	spoliava	V;IPFV;IND;SG;1;PST
inaugurar	inaugurarìa	V;COND;SG;3
noar	noase	V;IPFV;SBJV;PL;3;PST
tacar	taca	V;SBJV;SG;1;PRS;LGSPEC2
afitar	afitase	V;IPFV;SBJV;PL;3;PST
roversar	roversarisi	V;COND;PL;2
stranuar	stranuasi	V;IPFV;SBJV;SG;2;PST
acreditar	acrediti	V;IND;SG;2;PRS
smorsar	smorsa	V;IMP;SG;3;LGSPEC1
savariare	savaria	V;SBJV;SG;1;PRS;LGSPEC2
insegnar	insegnarémo	V;IND;PL;1;FUT
arivar	ariva	V;IND;PL;3;PRS
arar	ararémo	V;IND;PL;1;FUT
inaugurar	inauguré	V;IMP;PL;2
pensar	pense	V;IMP;PL;3;LGSPEC2
gòder	gòdivi	V;IPFV;IND;SG;2;PST
finansiar	finansii	V;SBJV;SG;2;PRS
dettar	dettarè	V;IND;SG;2;FUT
magnar	magnava	V;IPFV;IND;SG;1;PST
sunar	sunavi	V;IPFV;IND;SG;2;PST
sugerir	sugerirìa	V;COND;SG;3
spiar	spia	V;IMP;SG;2
ciapar	ciape	V;SBJV;SG;1;PRS;LGSPEC1
sgrafar	sgrafasi	V;IPFV;SBJV;SG;2;PST
macar	macarà	V;IND;PL;3;FUT
maurar	maurava	V;IPFV;IND;SG;1;PST
verxar	verxarìa	V;COND;PL;3
verxar	verxa	V;IND;PL;3;PRS
tamixar	tamixase	V;IPFV;SBJV;PL;3;PST
bójar	bójarémo	V;IND;PL;1;FUT
arivar	arivi	V;SBJV;SG;2;PRS
smorsar	smorsé	V;IND;PL;2;PRS
verxar	verxavi	V;IPFV;IND;PL;2;PST
prodùr	produxa	V;SBJV;PL;3;PRS
taxer	taxer	V;NFIN
colpir	colpirà	V;IND;SG;3;FUT
pociar	pociasi	V;IPFV;SBJV;SG;2;PST
noar	noa	V;IND;PL;3;PRS
realisar	realisa	V;SBJV;SG;3;PRS;LGSPEC2
arestar	aresté	V;SBJV;PL;2;PRS
realisar	realisarìsimo	V;COND;PL;1
cantar	cantàsimo	V;IPFV;SBJV;PL;1;PST
invidar	invidarémo	V;IND;PL;1;FUT
verxar	verxe	V;IMP;SG;3;LGSPEC2
bałar	bałe	V;SBJV;PL;3;PRS;LGSPEC1
tardigar	tardigava	V;IPFV;IND;SG;1;PST
insegnar	insegna	V;SBJV;SG;3;PRS;LGSPEC2
amar	amarà	V;IND;PL;3;FUT
crédar	crédése	V;IPFV;SBJV;SG;3;PST
invełenar	invełenarò	V;IND;SG;1;FUT
ascrivar	ascrivarà	V;IND;PL;3;FUT
çentrałizar	çentrałizarè	V;IND;PL;2;FUT
descovèrzar	descovèrzarò	V;IND;SG;1;FUT
apostrofar	apostrofarìa	V;COND;PL;3
sbregar	sbregarémo	V;IND;PL;1;FUT
rancurar	rancura	V;IND;PL;3;PRS
spojar	spojàvimo	V;IPFV;IND;PL;1;PST
cargar	carghe	V;SBJV;PL;3;PRS;LGSPEC1
pisar	pisa	V;SBJV;SG;3;PRS;LGSPEC2
stranuar	stranui	V;SBJV;SG;2;PRS
costar	coste	V;IMP;SG;3;LGSPEC2
voltar	voltava	V;IPFV;IND;PL;3;PST
desbrojar	desbrojarìa	V;COND;SG;3
cavar	cavava	V;IPFV;IND;SG;3;PST
spoliar	spoliarisi	V;COND;SG;2
jutar	jutavi	V;IPFV;IND;PL;2;PST
sperar	sperava	V;IPFV;IND;SG;1;PST
taxer	taxa	V;SBJV;SG;1;PRS
sarar	sare	V;IMP;SG;3;LGSPEC2
svejar	svejase	V;IPFV;SBJV;PL;3;PST
ocupar	ocuparìa	V;COND;SG;1
sunar	sunàsimo	V;IPFV;SBJV;PL;1;PST
cuèrzar	cuèrze	V;IND;PL;3;PRS
pasar	pasava	V;IPFV;IND;SG;3;PST
spojar	spoji	V;SBJV;SG;2;PRS
netar	netarìa	V;COND;SG;1
desmentegar	desmentegava	V;IPFV;IND;SG;3;PST
dettar	dettarisi	V;COND;PL;2
taxer	taxa	V;IMP;PL;3
sgnacar	sgnaca	V;IND;PL;3;PRS
maurar	mauravi	V;IPFV;IND;PL;2;PST
bruscar	bruscase	V;IPFV;SBJV;PL;3;PST
cavar	cavava	V;IPFV;IND;SG;1;PST
sguaratar	sguaratase	V;IPFV;SBJV;SG;1;PST
cantar	cantone	V;SBJV;PL;1;PRS;LGSPEC2
sachegiar	sachegiémo	V;SBJV;PL;1;PRS;LGSPEC1
sachegiar	sachegiase	V;IPFV;SBJV;PL;3;PST
petar	pete	V;SBJV;PL;3;PRS;LGSPEC1
spaxemar	spaxemarisi	V;COND;SG;2
sfrutar	sfrutase	V;IPFV;SBJV;PL;3;PST
sguaratar	sguarate	V;SBJV;SG;1;PRS;LGSPEC1
sguaratar	sguaratarémo	V;IND;PL;1;FUT
realisar	realisasi	V;IPFV;SBJV;PL;2;PST
maurar	maurava	V;IPFV;IND;SG;3;PST
fondar	fondasi	V;IPFV;SBJV;PL;2;PST
topar	tope	V;SBJV;SG;3;PRS;LGSPEC1
cargar	cargarìa	V;COND;SG;1
spacar	spachi	V;IND;SG;2;PRS
colpir	colpì	V;IMP;PL;2
sunar	suna	V;IMP;SG;2
descovèrzar	descovèrzarìa	V;COND;PL;3
stranuar	stranuarè	V;IND;PL;2;FUT
vałer	vałisi	V;IPFV;SBJV;SG;2;PST
vìnsar	vìnsarè	V;IND;PL;2;FUT
stranuar	stranuarémo	V;IND;PL;1;FUT
petar	pete	V;IMP;PL;3;LGSPEC2
vołer	vołì	V;IND;PL;2;PRS
invidar	invidé	V;SBJV;PL;2;PRS
doparar	dopare	V;IMP;SG;3;LGSPEC2
rìdar	rìdarìsimo	V;COND;PL;1
smorsar	smorsarisi	V;COND;PL;2
carołar	carołàvimo	V;IPFV;IND;PL;1;PST
petar	petarisi	V;COND;SG;2
restar	restase	V;IPFV;SBJV;SG;3;PST
destacar	destaco	V;IND;SG;1;PRS
supiàr	supie	V;SBJV;SG;3;PRS;LGSPEC1
verxar	verxé	V;SBJV;PL;2;PRS
smorsar	smorsa	V;IND;PL;3;PRS
spetar	speti	V;IND;SG;2;PRS
amar	amarisi	V;COND;PL;2
sugerir	sugeririsi	V;COND;SG;2
pónxar	pónxéa	V;IPFV;IND;SG;3;PST
invojar	invojàsimo	V;IPFV;SBJV;PL;1;PST
tastar	tasta	V;IMP;SG;3;LGSPEC1
vernixar	vernixarà	V;IND;PL;3;FUT
morsegar	morsegarìa	V;COND;PL;3
magnar	magnàsimo	V;IPFV;SBJV;PL;1;PST
morsegar	morseghi	V;SBJV;SG;2;PRS
pónxar	pónxarè	V;IND;SG;2;FUT
voxar	voxa	V;IMP;PL;3;LGSPEC1
sałudar	sałuda	V;IND;SG;3;PRS
covèrzar	covèrzése	V;IPFV;SBJV;PL;3;PST
baxar	baxarà	V;IND;PL;3;FUT
cołegar	cołeghe	V;SBJV;SG;3;PRS;LGSPEC1
spostar	spostase	V;IPFV;SBJV;PL;3;PST
pónxar	pónxarò	V;IND;SG;1;FUT
taxer	taxì	V;IND;PL;2;PRS
pontar	pontava	V;IPFV;IND;SG;1;PST
invełenar	invełenasi	V;IPFV;SBJV;PL;2;PST
tociar	tocia	V;IMP;SG;3;LGSPEC1
desbrojar	desbrojé	V;IMP;PL;2
cavar	cavase	V;IPFV;SBJV;PL;3;PST
vèrzar	vèrzarìa	V;COND;SG;3
invidar	invide	V;IMP;PL;3;LGSPEC2
netar	nete	V;IMP;SG;3;LGSPEC2
arestar	areste	V;IMP;PL;3;LGSPEC2
desbrojar	desbrojémo	V;IMP;PL;1
descargar	descargasi	V;IPFV;SBJV;SG;2;PST
stropar	stropa	V;SBJV;SG;1;PRS;LGSPEC2
fondar	fondavi	V;IPFV;IND;PL;2;PST
vołer	vułivi	V;IND;SG;2;PRS;LGSPEC3
sguaratar	sguaratarà	V;IND;PL;3;FUT
apostrofar	apostrofa	V;SBJV;SG;3;PRS;LGSPEC2
tardigar	tardigarè	V;IND;PL;2;FUT
parlar	parla	V;IND;SG;3;PRS
caminar	caminavi	V;IPFV;IND;SG;2;PST
costar	costa	V;IMP;SG;2
insegnar	insegné	V;IND;PL;2;PRS
copar	copavi	V;IPFV;IND;PL;2;PST
pisar	pise	V;IMP;PL;3;LGSPEC2
cuxir	cuxisi	V;IPFV;SBJV;SG;2;PST
afitar	afitarò	V;IND;SG;1;FUT
rivar	rivar	V;NFIN
sgrafar	sgrafi	V;IND;SG;2;PRS
ałestir	ałestisa	V;SBJV;SG;1;PRS
ofrir	ofrisi	V;IMP;SG;2
destacar	destacarìa	V;COND;SG;3
inventar	inventémo	V;IMP;PL;1
urtar	urta	V;SBJV;PL;3;PRS;LGSPEC2
acreditar	acreditarà	V;IND;PL;3;FUT
stupar	stuparà	V;IND;PL;3;FUT
apartegnir	apartegnise	V;IPFV;SBJV;SG;3;PST
maurar	maura	V;IND;PL;3;PRS
vołer	vołarìsimo	V;COND;PL;1
vestir	vestìvimo	V;IPFV;IND;PL;1;PST
siełier	siełier	V;NFIN
cołegar	cołega	V;IND;PL;3;PRS
svejar	svejémo	V;SBJV;PL;1;PRS;LGSPEC1
descargar	descarghe	V;IMP;SG;3;LGSPEC2
segar	segarìsimo	V;COND;PL;1
magnar	magna	V;SBJV;PL;3;PRS;LGSPEC2
pociar	pociarìa	V;COND;SG;1
ałestir	ałestìvimo	V;IPFV;IND;PL;1;PST
pèrdar	pèrdi	V;IND;SG;2;PRS
pisar	pisa	V;SBJV;PL;3;PRS;LGSPEC2
scuminsiar	scuminsiarà	V;IND;PL;3;FUT
tardigar	tardigarìa	V;COND;SG;1
influensar	influensarisi	V;COND;PL;2
noar	noavi	V;IPFV;IND;PL;2;PST
descovèrzar	descovèrza	V;SBJV;SG;3;PRS
desbrojar	desbrojarè	V;IND;PL;2;FUT
bruscar	bruscarisi	V;COND;PL;2
afitar	afitarisi	V;COND;PL;2
segar	seghé	V;IMP;PL;2
somejar	somejarìa	V;COND;PL;3
slargar	slargàvimo	V;IPFV;IND;PL;1;PST
macar	maca	V;IND;PL;3;PRS
scóndar	scónda	V;IMP;PL;3
topar	toparisi	V;COND;SG;2
spostar	sposta	V;IND;PL;3;PRS
cargar	cargòn	V;IND;PL;1;PRS;LGSPEC2
desmentegar	desmenteghémo	V;IMP;PL;1
vìnsar	vìnsì	V;IND;PL;2;PRS
spaxemar	spaxemé	V;SBJV;PL;2;PRS
asistar	asisti	V;IND;SG;2;PRS
voltar	volta	V;SBJV;SG;1;PRS;LGSPEC2
stuxar	stuxavi	V;IPFV;IND;PL;2;PST
portar	porte	V;IMP;SG;3;LGSPEC2
rostir	rostise	V;IPFV;SBJV;SG;3;PST
cunar	cuné	V;SBJV;PL;2;PRS
caminar	camina	V;SBJV;PL;3;PRS;LGSPEC2
arestar	areste	V;SBJV;SG;1;PRS;LGSPEC1
ałestir	ałestì	V;IMP;PL;2
parer	para	V;IMP;SG;3
strigar	striga	V;IND;SG;3;PRS
magnar	magnarè	V;IND;PL;2;FUT
caminar	camine	V;IMP;SG;3;LGSPEC2
siełier	siełiarò	V;IND;SG;1;FUT
pasar	pasé	V;SBJV;PL;2;PRS
vołer	vołarìa	V;COND;SG;1
sguaratar	sguaratàvimo	V;IPFV;IND;PL;1;PST
spiar	spione	V;SBJV;PL;1;PRS;LGSPEC2
spetar	spetavi	V;IPFV;IND;PL;2;PST
spoliar	spoliasi	V;IPFV;SBJV;SG;2;PST
colpir	colpise	V;IND;PL;3;PRS
descovèrzar	descovèrza	V;SBJV;PL;3;PRS
spiegar	spiega	V;IMP;SG;2
sguaratar	sguaratavi	V;IPFV;IND;PL;2;PST
obligar	obligarìa	V;COND;SG;1
pontar	ponta	V;IMP;SG;2
vałer	vałémo	V;IMP;PL;1
segar	segar	V;NFIN
pociar	pocia	V;IMP;PL;3;LGSPEC1
postar	postarìa	V;COND;SG;3
mołar	mołarìa	V;COND;PL;3
somejar	somejàvimo	V;IPFV;IND;PL;1;PST
asistar	asistéa	V;IPFV;IND;SG;3;PST
ascrivar	ascrive	V;IND;SG;3;PRS
spaxemar	spaxemàvimo	V;IPFV;IND;PL;1;PST
sachegiar	sachegii	V;IND;SG;2;PRS
ciapar	ciaparìa	V;COND;SG;1
tremar	tremarè	V;IND;SG;2;FUT
sugerir	sugerisi	V;SBJV;SG;2;PRS
urtar	urtar	V;NFIN
sotomesar	sotomesése	V;IPFV;SBJV;SG;3;PST
svejar	sveje	V;IMP;SG;3;LGSPEC2
crédar	crédarà	V;IND;SG;3;FUT
cunar	cuno	V;IND;SG;1;PRS
łimar	łimarémo	V;IND;PL;1;FUT
verxar	verxe	V;IMP;PL;3;LGSPEC2
realisar	realiso	V;IND;SG;1;PRS
sgnacar	sgnacase	V;IPFV;SBJV;SG;1;PST
udar	udarà	V;IND;SG;3;FUT
invełenar	invełené	V;IMP;PL;2
afitar	afitarè	V;IND;PL;2;FUT
justar	justarìa	V;COND;PL;3
intivar	intivarìa	V;COND;SG;3
doparar	dopararìa	V;COND;SG;1
slatar	slatòn	V;IND;PL;1;PRS;LGSPEC2
voxar	voxe	V;SBJV;PL;3;PRS;LGSPEC1
èser	fuse	V;IPFV;SBJV;SG;3;PST
tamixar	tamixe	V;SBJV;PL;3;PRS;LGSPEC1
ciamar	ciama	V;IMP;PL;3;LGSPEC1
suar	suémo	V;IMP;PL;1
pensar	pensarìsimo	V;COND;PL;1
pèrdar	pèrdo	V;IND;SG;1;PRS
entrar	entrarìsimo	V;COND;PL;1
èser	xe	V;IND;PL;3;PRS;LGSPEC1
desbrojar	desbroja	V;SBJV;SG;1;PRS;LGSPEC2
udar	udase	V;IPFV;SBJV;SG;1;PST
voxar	voxavi	V;IPFV;IND;PL;2;PST
spojar	spoja	V;SBJV;SG;1;PRS;LGSPEC2
ametar	ameta	V;IMP;SG;3
sgnacar	sgnacava	V;IPFV;IND;PL;3;PST
uxar	uxe	V;IMP;SG;3;LGSPEC2
afitar	afitémo	V;IMP;PL;1
conosar	conosarisi	V;COND;SG;2
entrar	entri	V;SBJV;SG;2;PRS
cunar	cuné	V;IMP;PL;2
udar	uda	V;SBJV;SG;1;PRS;LGSPEC2
arestar	arestase	V;IPFV;SBJV;PL;3;PST
prodùr	produxer	V;NFIN
cosołar	cosołone	V;SBJV;PL;1;PRS;LGSPEC2
prodùr	produxivi	V;IPFV;IND;SG;2;PST
netar	neta	V;IND;PL;3;PRS
inaugurar	inaugure	V;IMP;SG;3;LGSPEC2
spoliar	spoliasi	V;IPFV;SBJV;PL;2;PST
vestir	vestise	V;IPFV;SBJV;SG;3;PST
traversar	traversa	V;IND;PL;3;PRS
portar	portémo	V;IND;PL;1;PRS;LGSPEC1
slargar	slargava	V;IPFV;IND;SG;1;PST
rancurar	rancurarè	V;IND;SG;2;FUT
taconar	taconarisi	V;COND;SG;2
pontar	pontémo	V;SBJV;PL;1;PRS;LGSPEC1
domandar	domandarìa	V;COND;PL;3
domandar	domandava	V;IPFV;IND;SG;1;PST
cantar	cantava	V;IPFV;IND;PL;3;PST
incroxar	incroxarémo	V;IND;PL;1;FUT
sotomesar	sotomesa	V;SBJV;SG;1;PRS
bruscar	brusche	V;SBJV;PL;3;PRS;LGSPEC1
ciapar	ciaparémo	V;IND;PL;1;FUT
spojar	spojarà	V;IND;SG;3;FUT
sperar	sperémo	V;IND;PL;1;PRS;LGSPEC1
descovèrzar	descovèrzarìa	V;COND;SG;3
rìdar	rìdarà	V;IND;PL;3;FUT
roxegar	roxega	V;IND;PL;3;PRS
magnar	magnasi	V;IPFV;SBJV;PL;2;PST
bruscar	bruscàsimo	V;IPFV;SBJV;PL;1;PST
èser	jèrimo	V;IPFV;IND;PL;1;PST;LGSPEC3
magnar	magnase	V;IPFV;SBJV;SG;1;PST
vołer	vołi	V;SBJV;SG;2;PRS
roxegar	roxegarò	V;IND;SG;1;FUT
tacar	tacase	V;IPFV;SBJV;PL;3;PST
portar	portàvimo	V;IPFV;IND;PL;1;PST
restar	restava	V;IPFV;IND;PL;3;PST
robar	robase	V;IPFV;SBJV;SG;1;PST
topar	toparè	V;IND;SG;2;FUT
cołegar	cołeghémo	V;IMP;PL;1
invidar	invide	V;IMP;SG;3;LGSPEC2
suar	suàvimo	V;IPFV;IND;PL;1;PST
stanpar	stanpase	V;IPFV;SBJV;PL;3;PST
spostar	spostasi	V;IPFV;SBJV;PL;2;PST
tamixar	tamixarìsimo	V;COND;PL;1
obligar	obliga	V;SBJV;SG;1;PRS;LGSPEC2
vansar	vanso	V;IND;SG;1;PRS
realisar	realisémo	V;IND;PL;1;PRS;LGSPEC1
realisar	realisavi	V;IPFV;IND;PL;2;PST
daquar	daquavi	V;IPFV;IND;PL;2;PST
spiegar	spiegàvimo	V;IPFV;IND;PL;1;PST
costumar	costumava	V;IPFV;IND;PL;3;PST
fondar	fondone	V;SBJV;PL;1;PRS;LGSPEC2
spesegar	spesegarà	V;IND;PL;3;FUT
costumar	costumase	V;IPFV;SBJV;SG;3;PST
invojar	invoja	V;IND;SG;3;PRS
udar	uda	V;IMP;SG;3;LGSPEC1
exagerar	exagerarè	V;IND;SG;2;FUT
ascrivar	ascrivémo	V;IMP;PL;1
roxegar	roxegarè	V;IND;PL;2;FUT
spesegar	speseghé	V;SBJV;PL;2;PRS
traversar	traversarìa	V;COND;PL;3
uxar	uxasi	V;IPFV;SBJV;PL;2;PST
carołar	caroła	V;IND;PL;3;PRS
traversar	traversava	V;IPFV;IND;PL;3;PST
acreditar	acreditone	V;SBJV;PL;1;PRS;LGSPEC2
crédar	crédarè	V;IND;PL;2;FUT
pasar	pasavi	V;IPFV;IND;SG;2;PST
parlar	parlàsimo	V;IPFV;SBJV;PL;1;PST
sbrisiar	sbrisiarà	V;IND;PL;3;FUT
copar	coparè	V;IND;PL;2;FUT
cołegar	cołegar	V;NFIN
sbregar	sbreghe	V;SBJV;SG;3;PRS;LGSPEC1
cantar	cantarà	V;IND;PL;3;FUT
temer	temisi	V;IPFV;SBJV;PL;2;PST
jutar	jute	V;SBJV;SG;1;PRS;LGSPEC1
invidar	invidàvimo	V;IPFV;IND;PL;1;PST
remenar	remena	V;SBJV;PL;3;PRS;LGSPEC2
pestar	pesté	V;IND;PL;2;PRS
stranuar	stranuarè	V;IND;SG;2;FUT
ofrir	ofrisi	V;IPFV;SBJV;PL;2;PST
bójar	bója	V;SBJV;PL;3;PRS
tremar	tremarìa	V;COND;SG;3
spojar	spojarìsimo	V;COND;PL;1
çentrałizar	çentrałizémo	V;IND;PL;1;PRS;LGSPEC1
magnar	magno	V;IND;SG;1;PRS
saltar	salti	V;IND;SG;2;PRS
partir	partirò	V;IND;SG;1;FUT
costumar	costumarisi	V;COND;SG;2
gòder	gòdi	V;IND;SG;2;PRS
spoliar	spoliarìa	V;COND;PL;3
sguaratar	sguaratasi	V;IPFV;SBJV;SG;2;PST
tamixar	tamixarà	V;IND;PL;3;FUT
oxar	oxa	V;SBJV;SG;3;PRS;LGSPEC2
tociar	tocie	V;SBJV;SG;3;PRS;LGSPEC1
siełier	siełiése	V;IPFV;SBJV;PL;3;PST
bałar	bałòn	V;IND;PL;1;PRS;LGSPEC2
descargar	descargasi	V;IPFV;SBJV;PL;2;PST
verxar	verxi	V;IND;SG;2;PRS
èser	sémo	V;SBJV;PL;1;PRS
morsegar	morsega	V;IMP;PL;3;LGSPEC1
baxar	baxasi	V;IPFV;SBJV;SG;2;PST
segar	sega	V;IMP;SG;3;LGSPEC1
scrivar	scriva	V;SBJV;SG;3;PRS
vèrzar	vèrzi	V;IMP;SG;2
spacar	spacarìa	V;COND;PL;3
smorsar	smorsarìa	V;COND;PL;3
deventar	devente	V;SBJV;SG;3;PRS;LGSPEC1
apostrofar	apostrofavi	V;IPFV;IND;PL;2;PST
aderir	aderirà	V;IND;PL;3;FUT
partir	partise	V;IND;SG;3;PRS
justar	justé	V;SBJV;PL;2;PRS
postar	postòn	V;IND;PL;1;PRS;LGSPEC2
noar	noe	V;IMP;SG;3;LGSPEC2
visuałixar	visuałixi	V;IND;SG;2;PRS
magnar	magne	V;IMP;SG;3;LGSPEC2
spacar	spaca	V;IMP;SG;2
doparar	dopararà	V;IND;SG;3;FUT
amar	amo	V;IND;SG;1;PRS
pasar	pase	V;IMP;SG;3;LGSPEC2
parlar	parlavi	V;IPFV;IND;PL;2;PST
baxar	baxase	V;IPFV;SBJV;PL;3;PST
maurar	maura	V;IMP;SG;3;LGSPEC1
baxar	baxarìa	V;COND;SG;1
arivar	arivarémo	V;IND;PL;1;FUT
pèrdar	pèrdémo	V;SBJV;PL;1;PRS
pociar	pociarisi	V;COND;SG;2
maurar	maurarìa	V;COND;PL;3
invojar	invojarò	V;IND;SG;1;FUT
visuałixar	visuałixémo	V;SBJV;PL;1;PRS;LGSPEC1
bałar	bałava	V;IPFV;IND;PL;3;PST
spesegar	spesegar	V;NFIN
bójar	bójì	V;IMP;PL;2
spojar	spojase	V;IPFV;SBJV;SG;3;PST
insegnar	insegnòn	V;IND;PL;1;PRS;LGSPEC2
finansiar	finansié	V;IMP;PL;2
parlar	parlasi	V;IPFV;SBJV;PL;2;PST
invojar	invojémo	V;SBJV;PL;1;PRS;LGSPEC1
morir	morisa	V;SBJV;PL;3;PRS
influensar	influensase	V;IPFV;SBJV;SG;3;PST
partir	partirisi	V;COND;PL;2
pónxar	pónxa	V;IMP;SG;3
tociar	tociémo	V;SBJV;PL;1;PRS;LGSPEC1
segar	segone	V;SBJV;PL;1;PRS;LGSPEC2
cunar	cunàvimo	V;IPFV;IND;PL;1;PST
vansar	vansarìa	V;COND;SG;1
rostir	rostivi	V;IPFV;IND;PL;2;PST
voxar	voxé	V;IND;PL;2;PRS
aderir	aderirò	V;IND;SG;1;FUT
ciamar	ciama	V;IMP;SG;2
stranuar	stranue	V;SBJV;SG;3;PRS;LGSPEC1
udar	udarìa	V;COND;SG;3
jutar	juti	V;SBJV;SG;2;PRS
incroxar	incroxé	V;IND;PL;2;PRS
rostir	rostisa	V;SBJV;SG;3;PRS
tetar	teta	V;IND;PL;3;PRS
finansiar	finansiarò	V;IND;SG;1;FUT
remenar	remenavi	V;IPFV;IND;PL;2;PST
vernixar	vernixa	V;IMP;SG;2
mołar	mołémo	V;SBJV;PL;1;PRS;LGSPEC1
spacar	spacase	V;IPFV;SBJV;SG;3;PST
parlar	parla	V;SBJV;PL;3;PRS;LGSPEC2
supiàr	supione	V;SBJV;PL;1;PRS;LGSPEC2
inventar	inventa	V;IND;PL;3;PRS
asistar	asisto	V;IND;SG;1;PRS
conbatar	conbati	V;SBJV;SG;2;PRS
entrar	entra	V;IMP;SG;3;LGSPEC1
spiegar	spiegarà	V;IND;PL;3;FUT
sarare	sararìa	V;COND;SG;3
cavar	cavarà	V;IND;PL;3;FUT
siełier	siełiarà	V;IND;PL;3;FUT
inventar	inventarè	V;IND;SG;2;FUT
stropar	strope	V;SBJV;SG;1;PRS;LGSPEC1
descovèrzar	descovèrzarà	V;IND;PL;3;FUT
somejar	somejarà	V;IND;PL;3;FUT
sbrisiar	sbrisia	V;IMP;SG;2
covèrzar	covèrzése	V;IPFV;SBJV;SG;1;PST
traversar	traversàvimo	V;IPFV;IND;PL;1;PST
pasar	pasarè	V;IND;SG;2;FUT
inaugurar	inaugura	V;SBJV;PL;3;PRS;LGSPEC2
costruir	costruirè	V;IND;SG;2;FUT
traversar	traversone	V;SBJV;PL;1;PRS;LGSPEC2
pociar	pocia	V;IMP;SG;3;LGSPEC1
spiegar	spiegava	V;IPFV;IND;SG;3;PST
pasar	pasarémo	V;IND;PL;1;FUT
ametar	ametisi	V;IPFV;SBJV;PL;2;PST
suar	suémo	V;SBJV;PL;1;PRS;LGSPEC1
traversar	traversarisi	V;COND;PL;2
rancurar	rancura	V;IND;SG;3;PRS
saltar	salta	V;IND;PL;3;PRS
vernixar	vernixarè	V;IND;SG;2;FUT
roversar	roversase	V;IPFV;SBJV;PL;3;PST
traversar	traverse	V;SBJV;SG;3;PRS;LGSPEC1
influensar	influensasi	V;IPFV;SBJV;SG;2;PST
èser	sì	V;IND;PL;2;PRS
sujerir	sujerì	V;SBJV;PL;2;PRS
costar	costa	V;IND;PL;3;PRS
carołar	carołémo	V;IND;PL;1;PRS;LGSPEC1
destacar	destaca	V;SBJV;SG;1;PRS;LGSPEC2
spojar	spoje	V;IMP;PL;3;LGSPEC2
tardigar	tardighe	V;SBJV;PL;3;PRS;LGSPEC1
sachegiar	sachegiémo	V;IND;PL;1;PRS;LGSPEC1
costumar	costumase	V;IPFV;SBJV;SG;1;PST
pisar	piso	V;IND;SG;1;PRS
afitar	afité	V;IMP;PL;2
afitar	afitarisi	V;COND;SG;2
conzsar	conzsi	V;SBJV;SG;2;PRS
spetar	spetarè	V;IND;PL;2;FUT
acreditar	acreditarè	V;IND;SG;2;FUT
sbregar	sbregavi	V;IPFV;IND;SG;2;PST
ałestir	ałestirìa	V;COND;SG;3
çentrałizar	çentrałizarìa	V;COND;SG;1
vansar	vansa	V;IND;SG;3;PRS
urtar	urtava	V;IPFV;IND;PL;3;PST
bruscar	brusca	V;IMP;SG;2
restar	restava	V;IPFV;IND;SG;1;PST
sfrutar	sfrutarisi	V;COND;PL;2
tociar	tocio	V;IND;SG;1;PRS
ałestir	ałestì	V;IND;PL;2;PRS
urtar	urté	V;SBJV;PL;2;PRS
doparar	doparase	V;IPFV;SBJV;SG;1;PST
roversar	roversarémo	V;IND;PL;1;FUT
visuałixar	visuałixavi	V;IPFV;IND;SG;2;PST
smorsar	smorsarémo	V;IND;PL;1;FUT
somejar	somejava	V;IPFV;IND;SG;3;PST
rancurar	rancure	V;SBJV;SG;1;PRS;LGSPEC1
finansiar	finansiase	V;IPFV;SBJV;SG;1;PST
scriver	scriva	V;SBJV;SG;3;PRS
slatar	slata	V;IMP;PL;3;LGSPEC1
portar	porto	V;IND;SG;1;PRS
rìdar	rìdémo	V;IMP;PL;1
sbregar	sbregavi	V;IPFV;IND;PL;2;PST
pestar	pesta	V;IMP;SG;3;LGSPEC1
intorcołar	intorcołarò	V;IND;SG;1;FUT
afitar	afite	V;SBJV;SG;3;PRS;LGSPEC1
tastar	tastarìa	V;COND;SG;1
oxar	oxavi	V;IPFV;IND;SG;2;PST
vernixar	vernixarò	V;IND;SG;1;FUT
stropar	stroparìa	V;COND;SG;3
cantar	canta	V;IMP;SG;3;LGSPEC1
dettar	dettavi	V;IPFV;IND;SG;2;PST
spiegar	spiegàsimo	V;IPFV;SBJV;PL;1;PST
postar	postàvimo	V;IPFV;IND;PL;1;PST
invidiar	invidiémo	V;IND;PL;1;PRS;LGSPEC1
svejar	svejé	V;IMP;PL;2
invojar	invojava	V;IPFV;IND;PL;3;PST
spesegar	spesegasi	V;IPFV;SBJV;PL;2;PST
carołar	caroła	V;SBJV;SG;1;PRS;LGSPEC2
sgnaolar	sgnaolàvimo	V;IPFV;IND;PL;1;PST
nàsar	nàsarisi	V;COND;PL;2
invidiar	invidiase	V;IPFV;SBJV;PL;3;PST
rivar	rivasi	V;IPFV;SBJV;PL;2;PST
sunar	suné	V;IMP;PL;2
spiegar	spiegarò	V;IND;SG;1;FUT
invojar	invojase	V;IPFV;SBJV;PL;3;PST
spaxemar	spaxemé	V;IMP;PL;2
uxar	uxasi	V;IPFV;SBJV;SG;2;PST
destacar	destacàsimo	V;IPFV;SBJV;PL;1;PST
cołegar	cołeghe	V;SBJV;SG;1;PRS;LGSPEC1
acreditar	acreditava	V;IPFV;IND;SG;3;PST
noar	noémo	V;IMP;PL;1
vìnsar	vìnsarisi	V;COND;SG;2
ocupar	ocuparà	V;IND;PL;3;FUT
spaxemar	spaxemarò	V;IND;SG;1;FUT
tremar	tremarè	V;IND;PL;2;FUT
saltar	saltasi	V;IPFV;SBJV;SG;2;PST
exagerar	exagerase	V;IPFV;SBJV;SG;1;PST
destacar	destache	V;IMP;SG;3;LGSPEC2
vołer	voła	V;SBJV;SG;1;PRS
suar	sue	V;SBJV;SG;3;PRS;LGSPEC1
justar	juste	V;SBJV;SG;1;PRS;LGSPEC1
pasar	pasémo	V;IND;PL;1;PRS;LGSPEC1
obligar	oblighi	V;SBJV;SG;2;PRS
ciamar	ciamasi	V;IPFV;SBJV;PL;2;PST
arar	are	V;SBJV;SG;3;PRS;LGSPEC1
sarare	sara	V;IND;SG;3;PRS
sałudar	sałuda	V;IMP;SG;3;LGSPEC1
pónxar	pónxarà	V;IND;PL;3;FUT
incroxar	incroxa	V;IMP;SG;2
roversar	roversa	V;IMP;SG;3;LGSPEC1
stranuar	stranua	V;SBJV;SG;1;PRS;LGSPEC2
tastar	tasta	V;IMP;PL;3;LGSPEC1
stranuar	stranuase	V;IPFV;SBJV;SG;3;PST
cavar	cavase	V;IPFV;SBJV;SG;3;PST
stanpar	stanpémo	V;IMP;PL;1
pisar	pisarè	V;IND;PL;2;FUT
scriver	scrivi	V;IMP;SG;2
oxar	oxi	V;SBJV;SG;2;PRS
finansiar	finansiasi	V;IPFV;SBJV;PL;2;PST
sunar	suna	V;SBJV;SG;1;PRS;LGSPEC2
pensar	pensase	V;IPFV;SBJV;PL;3;PST
cantar	cantasi	V;IPFV;SBJV;SG;2;PST
svejar	svejòn	V;IND;PL;1;PRS;LGSPEC2
petar	peté	V;SBJV;PL;2;PRS
vìnsar	vìnsémo	V;IND;PL;1;PRS
sałudar	sałuda	V;IND;PL;3;PRS
strigar	strighémo	V;SBJV;PL;1;PRS;LGSPEC1
sgrafar	sgrafarìa	V;COND;PL;3
vèrzar	vèrzarémo	V;IND;PL;1;FUT
scriver	scrivése	V;IPFV;SBJV;SG;1;PST
tacar	tacasi	V;IPFV;SBJV;SG;2;PST
justar	justasi	V;IPFV;SBJV;SG;2;PST
cołegar	cołega	V;IND;SG;3;PRS
siełier	siełiéa	V;IPFV;IND;PL;3;PST
scrivar	scrivése	V;IPFV;SBJV;SG;3;PST
costruir	costruiso	V;IND;SG;1;PRS
supiàr	supie	V;IMP;PL;3;LGSPEC2
daquar	daquar	V;NFIN
traversar	traverse	V;IMP;PL;3;LGSPEC2
sugerir	sugerìa	V;IPFV;IND;PL;3;PST
sguaratar	sguaratar	V;NFIN
pisar	pisarémo	V;IND;PL;1;FUT
robar	robémo	V;IND;PL;1;PRS;LGSPEC1
stropar	stroparè	V;IND;SG;2;FUT
sunar	sunasi	V;IPFV;SBJV;PL;2;PST
pontar	pontone	V;SBJV;PL;1;PRS;LGSPEC2
colpir	colpirè	V;IND;PL;2;FUT
spostar	spostavi	V;IPFV;IND;SG;2;PST
parer	parivi	V;IPFV;IND;SG;2;PST
invidar	invidarò	V;IND;SG;1;FUT
remenar	remenarisi	V;COND;PL;2
spesegar	spesegarìa	V;COND;SG;1
pasar	pasarìa	V;COND;SG;3
stanpar	stanpa	V;IMP;SG;3;LGSPEC1
topar	topémo	V;IMP;PL;1
çentrałizar	çentrałiza	V;SBJV;PL;3;PRS;LGSPEC2
maurar	maurarò	V;IND;SG;1;FUT
ciapar	ciape	V;SBJV;SG;3;PRS;LGSPEC1
urtar	urtàsimo	V;IPFV;SBJV;PL;1;PST
somejar	somejase	V;IPFV;SBJV;SG;3;PST
fondar	fonde	V;SBJV;PL;3;PRS;LGSPEC1
sotomesar	sotomesévimo	V;IPFV;IND;PL;1;PST
tetar	teto	V;IND;SG;1;PRS
spetar	spetarémo	V;IND;PL;1;FUT
sałudar	sałuda	V;SBJV;PL;3;PRS;LGSPEC2
postar	postarìa	V;COND;PL;3
slatar	slate	V;IMP;SG;3;LGSPEC2
tamixar	tamixé	V;IND;PL;2;PRS
noar	noé	V;IMP;PL;2
castrar	castràvimo	V;IPFV;IND;PL;1;PST
vìnsar	vìnsar	V;NFIN
pensar	penso	V;IND;SG;1;PRS
copar	copasi	V;IPFV;SBJV;PL;2;PST
spesegar	spesega	V;IND;SG;3;PRS
pisar	pisarà	V;IND;PL;3;FUT
taxer	taxarìa	V;COND;SG;3
morsegar	morsegarémo	V;IND;PL;1;FUT
vèrzar	vèrzarìsimo	V;COND;PL;1
copar	cope	V;IMP;SG;3;LGSPEC2
temer	teméa	V;IPFV;IND;SG;1;PST
apostrofar	apostrofe	V;IMP;PL;3;LGSPEC2
sałudar	sałudé	V;IMP;PL;2
èser	jeri	V;IPFV;IND;SG;2;PST;LGSPEC3
acreditar	acreditase	V;IPFV;SBJV;SG;1;PST
ofrir	ofrìa	V;IPFV;IND;PL;3;PST
invełenar	invełenémo	V;IMP;PL;1
afitar	afita	V;IND;SG;3;PRS
sgnaolar	sgnaolarìa	V;COND;PL;3
oxar	oxé	V;SBJV;PL;2;PRS
asistar	asistémo	V;SBJV;PL;1;PRS
strigar	striga	V;IND;PL;3;PRS
sfrixar	sfrixo	V;IND;SG;1;PRS
bałar	bałi	V;SBJV;SG;2;PRS
ofrir	ofrisa	V;SBJV;SG;3;PRS
invełenar	invełenava	V;IPFV;IND;PL;3;PST
tacar	tacasi	V;IPFV;SBJV;PL;2;PST
tremar	tremé	V;IND;PL;2;PRS
descovèrzar	descovèrzévimo	V;IPFV;IND;PL;1;PST
strabucar	strabucarisi	V;COND;PL;2
mołar	mołarisi	V;COND;SG;2
taconar	taconavi	V;IPFV;IND;PL;2;PST
sgnaolar	sgnaolava	V;IPFV;IND;SG;1;PST
vernixar	vernixarisi	V;COND;SG;2
pociar	pociarìa	V;COND;SG;3
cosołar	cosołavi	V;IPFV;IND;PL;2;PST
sałudar	sałudarémo	V;IND;PL;1;FUT
apostrofar	apostrofi	V;SBJV;SG;2;PRS
sgrafar	sgrafa	V;IND;SG;3;PRS
strénxar	strénxarò	V;IND;SG;1;FUT
çentrałizar	çentrałizàvimo	V;IPFV;IND;PL;1;PST
intorcołar	intorcołarisi	V;COND;SG;2
strigar	strigavi	V;IPFV;IND;PL;2;PST
inventar	inventa	V;IND;SG;3;PRS
incroxar	incroxar	V;NFIN
entrar	entrarè	V;IND;SG;2;FUT
entrar	entravi	V;IPFV;IND;PL;2;PST
rostir	rostise	V;IND;PL;3;PRS
tamixar	tamixe	V;IMP;PL;3;LGSPEC2
apostrofar	apostrofa	V;IND;SG;3;PRS
doparar	doparé	V;IND;PL;2;PRS
ciocar	ciocase	V;IPFV;SBJV;PL;3;PST
semenar	semenarè	V;IND;SG;2;FUT
invojar	invoje	V;SBJV;PL;3;PRS;LGSPEC1
nàsar	nàsarémo	V;IND;PL;1;FUT
prodùr	produxarà	V;IND;PL;3;FUT
taconar	tacona	V;SBJV;SG;1;PRS;LGSPEC2
sgnaolar	sgnaolòn	V;IND;PL;1;PRS;LGSPEC2
invełenar	invełenarìa	V;COND;SG;1
amar	amarà	V;IND;SG;3;FUT
pisar	pise	V;IMP;SG;3;LGSPEC2
invojar	invoja	V;IMP;SG;3;LGSPEC1
łavorar	łavorarìsimo	V;COND;PL;1
sbrisiar	sbrisiarè	V;IND;SG;2;FUT
crédar	crédivi	V;IPFV;IND;SG;2;PST
acreditar	acreditémo	V;SBJV;PL;1;PRS;LGSPEC1
crédar	crédarìa	V;COND;SG;3
tardigar	tardigarisi	V;COND;PL;2
vestir	vestirémo	V;IND;PL;1;FUT
incroxar	incroxàvimo	V;IPFV;IND;PL;1;PST
descargar	descarga	V;SBJV;SG;1;PRS;LGSPEC2
arestar	arestàvimo	V;IPFV;IND;PL;1;PST
spiegar	spiegasi	V;IPFV;SBJV;PL;2;PST
morsegar	morsegarisi	V;COND;SG;2
stranuar	stranuarìsimo	V;COND;PL;1
stanpar	stanpòn	V;IND;PL;1;PRS;LGSPEC2
parer	pararìa	V;COND;SG;1
ofrir	ofrisa	V;IMP;PL;3
comerçar	comerçasi	V;IPFV;SBJV;SG;2;PST
pociar	pociava	V;IPFV;IND;PL;3;PST
scuminsiar	scuminsiarà	V;IND;SG;3;FUT
entrar	entrarisi	V;COND;SG;2
rìdar	rìdivi	V;IPFV;IND;PL;2;PST
obligar	obligarà	V;IND;PL;3;FUT
covèrzar	covèrzése	V;IPFV;SBJV;SG;3;PST
sgrafar	sgrafarò	V;IND;SG;1;FUT
tamixar	tamixase	V;IPFV;SBJV;SG;1;PST
scrivar	scrivi	V;SBJV;SG;2;PRS
cargar	carga	V;IND;SG;3;PRS
ascrivar	ascrivi	V;SBJV;SG;2;PRS
arestar	arestarò	V;IND;SG;1;FUT
domandar	domanda	V;IMP;PL;3;LGSPEC1
entrar	entra	V;SBJV;SG;1;PRS;LGSPEC2
macar	macase	V;IPFV;SBJV;SG;3;PST
parer	parése	V;IPFV;SBJV;PL;3;PST
baxar	baxasi	V;IPFV;SBJV;PL;2;PST
bałar	bałarìa	V;COND;SG;3
pociar	pociasi	V;IPFV;SBJV;PL;2;PST
cunar	cuna	V;SBJV;PL;3;PRS;LGSPEC2
doparar	doparémo	V;SBJV;PL;1;PRS;LGSPEC1
scóndar	scóndéa	V;IPFV;IND;SG;1;PST
rivar	rivarìa	V;COND;SG;1
voxar	voxé	V;IMP;PL;2
costar	coste	V;IMP;PL;3;LGSPEC2
slatar	slatase	V;IPFV;SBJV;PL;3;PST
sfrutar	sfrutarà	V;IND;SG;3;FUT
justar	justàvimo	V;IPFV;IND;PL;1;PST
ofrir	ofrisi	V;IPFV;SBJV;SG;2;PST
taconar	taconarìa	V;COND;SG;1
cuèrzar	cuèrzése	V;IPFV;SBJV;PL;3;PST
influensar	influensava	V;IPFV;IND;PL;3;PST
vèrzar	vèrzì	V;SBJV;PL;2;PRS
temer	temivi	V;IPFV;IND;PL;2;PST
intrigar	intrighe	V;IMP;PL;3;LGSPEC2
vestir	vestir	V;NFIN
comerçar	comerçe	V;SBJV;SG;3;PRS;LGSPEC1
desmentegar	desmentegarà	V;IND;SG;3;FUT
castrar	castrase	V;IPFV;SBJV;SG;3;PST
morir	morirà	V;IND;SG;3;FUT
spesegar	spesegòn	V;IND;PL;1;PRS;LGSPEC2
stupar	stupa	V;SBJV;SG;3;PRS;LGSPEC2
scriver	scriva	V;SBJV;PL;3;PRS
scuminsiar	scuminsiase	V;IPFV;SBJV;SG;3;PST
sperar	sperarisi	V;COND;PL;2
savariare	savariase	V;IPFV;SBJV;SG;1;PST
cołegar	cołegarè	V;IND;PL;2;FUT
descovèrzar	descovèrza	V;IMP;PL;3
somejar	someja	V;SBJV;SG;3;PRS;LGSPEC2
sbregar	sbregòn	V;IND;PL;1;PRS;LGSPEC2
baxar	baxémo	V;IMP;PL;1
copar	copa	V;SBJV;PL;3;PRS;LGSPEC2
influensar	influensa	V;IMP;SG;3;LGSPEC1
pociar	pocia	V;IMP;SG;2
invidar	invidémo	V;SBJV;PL;1;PRS;LGSPEC1
spostar	spostavi	V;IPFV;IND;PL;2;PST
domandar	domanda	V;IMP;SG;2
spojar	spojasi	V;IPFV;SBJV;SG;2;PST
ocupar	ocuparisi	V;COND;SG;2
bójar	bójarà	V;IND;PL;3;FUT
descargar	descarga	V;SBJV;PL;3;PRS;LGSPEC2
ofrir	ofririsi	V;COND;SG;2
deventar	deventarà	V;IND;PL;3;FUT
vałer	vałarìa	V;COND;SG;1
pensar	pensa	V;IND;PL;3;PRS
covèrzar	covèrzì	V;IMP;PL;2
vìnsar	vìnsi	V;IND;SG;2;PRS
sotomesar	sotomesivi	V;IPFV;IND;PL;2;PST
uxar	uxa	V;IND;SG;3;PRS
rivar	rivava	V;IPFV;IND;SG;3;PST
savariare	savarie	V;SBJV;SG;1;PRS;LGSPEC1
robar	robone	V;SBJV;PL;1;PRS;LGSPEC2
restar	restarìa	V;COND;PL;3
insegnar	insegnémo	V;IMP;PL;1
stranuar	stranuone	V;SBJV;PL;1;PRS;LGSPEC2
dettar	detta	V;IND;PL;3;PRS
vansar	vansase	V;IPFV;SBJV;SG;1;PST
spaxemar	spaxemarè	V;IND;SG;2;FUT
scóndar	scóndarò	V;IND;SG;1;FUT
insegnar	insegnarà	V;IND;SG;3;FUT
stuxar	stuxarisi	V;COND;PL;2
vìnsar	vìnsi	V;IMP;SG;2
pociar	pociavi	V;IPFV;IND;SG;2;PST
semenar	semenase	V;IPFV;SBJV;SG;3;PST
destacar	destacavi	V;IPFV;IND;SG;2;PST
spostar	sposto	V;IND;SG;1;PRS
voltar	voltarà	V;IND;PL;3;FUT
semenar	semenarisi	V;COND;PL;2
sgnacar	sgnaca	V;IMP;PL;3;LGSPEC1
sgrafar	sgrafémo	V;IMP;PL;1
pensar	pensémo	V;SBJV;PL;1;PRS;LGSPEC1
tremar	treme	V;SBJV;PL;3;PRS;LGSPEC1
incroxar	incroxasi	V;IPFV;SBJV;PL;2;PST
costar	costasi	V;IPFV;SBJV;SG;2;PST
scriver	scrive	V;IND;SG;3;PRS
uxar	uxa	V;IMP;PL;3;LGSPEC1
postar	posta	V;IND;SG;3;PRS
somejar	someja	V;IND;PL;3;PRS
spojar	spojarémo	V;IND;PL;1;FUT
cunar	cunase	V;IPFV;SBJV;SG;1;PST
córar	córarìa	V;COND;PL;3
divìdar	divìdarà	V;IND;PL;3;FUT
bazxotar	bazxota	V;IND;SG;3;PRS
vangar	vangase	V;IPFV;SBJV;SG;1;PST
tugar	tugarìsimo	V;COND;PL;1
provar	prove	V;IMP;PL;3;LGSPEC2
sluxegar	sluxeghémo	V;IND;PL;1;PRS;LGSPEC1
raprexentar	raprexentarisi	V;COND;PL;2
spełar	speła	V;IND;SG;3;PRS
curar	curé	V;IMP;PL;2
asaltar	asalta	V;SBJV;PL;3;PRS;LGSPEC2
raprexentar	raprexentar	V;NFIN
łibarar	łibarava	V;IPFV;IND;SG;3;PST
divìdar	divìde	V;IND;SG;3;PRS
spełar	speła	V;IMP;SG;3;LGSPEC1
bacajar	bacajarà	V;IND;PL;3;FUT
divìdar	divìdisi	V;IPFV;SBJV;SG;2;PST
córar	córar	V;NFIN
sostituir	sostituise	V;IPFV;SBJV;SG;1;PST
menar	menémo	V;SBJV;PL;1;PRS;LGSPEC1
desidar	desidava	V;IPFV;IND;SG;1;PST
inpizar	inpizarisi	V;COND;SG;2
modifegar	modifegarà	V;IND;PL;3;FUT
bojir	bojimo	V;IMP;PL;1
viajar	viajarè	V;IND;SG;2;FUT
begar	begava	V;IPFV;IND;PL;3;PST
pexar	pexe	V;SBJV;SG;3;PRS;LGSPEC1
pareciar	pareciar	V;NFIN
misiar	misia	V;SBJV;SG;3;PRS;LGSPEC2
begar	bega	V;SBJV;SG;1;PRS;LGSPEC2
viajar	viaje	V;SBJV;PL;3;PRS;LGSPEC1
ricordar	ricordasi	V;IPFV;SBJV;PL;2;PST
mantegner	mantegner	V;NFIN
strapegar	strapegarò	V;IND;SG;1;FUT
busnar	busnar	V;NFIN
modifegar	modifega	V;SBJV;PL;3;PRS;LGSPEC2
criar	cria	V;SBJV;SG;1;PRS;LGSPEC2
spełar	speła	V;SBJV;SG;3;PRS;LGSPEC2
calcołar	calcołavi	V;IPFV;IND;PL;2;PST
danar	danarisi	V;COND;PL;2
canbiar	canbia	V;SBJV;SG;3;PRS;LGSPEC2
afermar	afermi	V;IND;SG;2;PRS
bazxotar	bazxote	V;SBJV;PL;3;PRS;LGSPEC1
proclamar	proclamasi	V;IPFV;SBJV;PL;2;PST
conpiłar	conpiłarìsimo	V;COND;PL;1
sbrajar	sbraja	V;IND;SG;3;PRS
sgropar	sgrope	V;SBJV;PL;3;PRS;LGSPEC1
aver	avisi	V;IPFV;SBJV;SG;2;PST
aspetar	aspete	V;IMP;SG;3;LGSPEC2
carezxar	carezxarémo	V;IND;PL;1;FUT
vantar	vantémo	V;SBJV;PL;1;PRS;LGSPEC1
pareciar	pareciase	V;IPFV;SBJV;SG;1;PST
sostituir	sostituimo	V;IMP;PL;1
tocar	tocàvimo	V;IPFV;IND;PL;1;PST
stisar	stisa	V;SBJV;SG;1;PRS;LGSPEC2
sciocar	sciocarìsimo	V;COND;PL;1
védar	véda	V;SBJV;PL;3;PRS
catar	cata	V;IMP;PL;3;LGSPEC1
tornar	tornase	V;IPFV;SBJV;PL;3;PST
sfondrar	sfondravi	V;IPFV;IND;SG;2;PST
soranomenar	soranomenarà	V;IND;PL;3;FUT
intosegar	intoseghe	V;IMP;SG;3;LGSPEC2
votar	votase	V;IPFV;SBJV;SG;1;PST
sponciar	sponciarisi	V;COND;PL;2
becar	becase	V;IPFV;SBJV;SG;1;PST
concepir	concepisa	V;SBJV;SG;3;PRS
nominar	nomine	V;SBJV;PL;3;PRS;LGSPEC1
maciar	macie	V;SBJV;SG;3;PRS;LGSPEC1
sparagnar	sparagno	V;IND;SG;1;PRS
bazxotar	bazxoté	V;IND;PL;2;PRS
conpletar	conpletarà	V;IND;PL;3;FUT
svodar	svodarà	V;IND;PL;3;FUT
bévar	bévarè	V;IND;PL;2;FUT
riciamar	riciamé	V;IMP;PL;2
viajar	viaja	V;IND;SG;3;PRS
rodołar	rodołarà	V;IND;SG;3;FUT
mancar	mancarà	V;IND;PL;3;FUT
provar	provarìa	V;COND;PL;3
bojir	bojise	V;IPFV;SBJV;PL;3;PST
spoxar	spoxe	V;SBJV;PL;3;PRS;LGSPEC1
piànxar	piànxése	V;IPFV;SBJV;SG;3;PST
scoltar	scolta	V;SBJV;SG;1;PRS;LGSPEC2
proclamar	proclamavi	V;IPFV;IND;SG;2;PST
cascar	caschémo	V;SBJV;PL;1;PRS;LGSPEC1
łegałixar	łegałixi	V;IND;SG;2;PRS
bagnar	bagnavi	V;IPFV;IND;PL;2;PST
sparagnar	sparagna	V;SBJV;PL;3;PRS;LGSPEC2
slongar	slonga	V;SBJV;PL;3;PRS;LGSPEC2
studiar	studié	V;SBJV;PL;2;PRS
scorlar	scorle	V;IND;PL;3;PRS
limitar	limito	V;IND;SG;1;PRS
rumar	rumarìa	V;COND;SG;1
sentar	sentì	V;IND;PL;2;PRS
bearar	beararìa	V;COND;SG;3
ciuciar	ciuciarè	V;IND;PL;2;FUT
star	sta	V;IMP;PL;3;LGSPEC1
sgropar	sgropa	V;IMP;PL;3;LGSPEC1
desmontar	desmontase	V;IPFV;SBJV;SG;3;PST
bazxotar	bazxoto	V;IND;SG;1;PRS
spełar	spełàsimo	V;IPFV;SBJV;PL;1;PST
carezxar	carezxe	V;IMP;PL;3;LGSPEC2
canbiar	canbiarè	V;IND;PL;2;FUT
dormir	dormise	V;IPFV;SBJV;PL;3;PST
tegner	tegna	V;SBJV;SG;1;PRS
abitar	abitavi	V;IPFV;IND;PL;2;PST
danar	danémo	V;SBJV;PL;1;PRS;LGSPEC1
slùxar	slùxava	V;IPFV;IND;PL;3;PST
łustrar	łustrava	V;IPFV;IND;SG;3;PST
svodar	svodarémo	V;IND;PL;1;FUT
bociar	bociarìa	V;COND;PL;3
begar	begavi	V;IPFV;IND;PL;2;PST
rodołar	rodoła	V;IMP;SG;3;LGSPEC1
nominar	nominémo	V;IMP;PL;1
catar	catarà	V;IND;PL;3;FUT
trincar	trincarè	V;IND;SG;2;FUT
piànxar	piànxi	V;IND;SG;2;PRS
trar	travi	V;IPFV;IND;PL;2;PST
pełar	pełé	V;SBJV;PL;2;PRS
sluxegar	sluxeghe	V;SBJV;PL;3;PRS;LGSPEC1
anoverar	anoverase	V;IPFV;SBJV;SG;1;PST
xontar	xonta	V;IMP;SG;3;LGSPEC1
piànxar	piànxarìa	V;COND;SG;1
dormir	dormisi	V;IPFV;SBJV;PL;2;PST
asaltar	asaltase	V;IPFV;SBJV;PL;3;PST
rasar	rasasi	V;IPFV;SBJV;SG;2;PST
desidar	desidarìa	V;COND;SG;3
zontar	zontarò	V;IND;SG;1;FUT
picar	picava	V;IPFV;IND;SG;3;PST
sajar	sajémo	V;IND;PL;1;PRS;LGSPEC1
inverinar	inverinarémo	V;IND;PL;1;FUT
strapegar	strapegava	V;IPFV;IND;SG;1;PST
sciocar	sciocarè	V;IND;SG;2;FUT
desligar	desligarìa	V;COND;SG;1
bévar	bévémo	V;IMP;PL;1
sentar	sente	V;IND;PL;3;PRS
controłar	controłàsimo	V;IPFV;SBJV;PL;1;PST
desligar	deslighémo	V;SBJV;PL;1;PRS;LGSPEC1
soranomenar	soranomena	V;IND;SG;3;PRS
svodar	svodone	V;SBJV;PL;1;PRS;LGSPEC2
invernixar	invernixémo	V;IMP;PL;1
desgozar	desgozarè	V;IND;PL;2;FUT
carezsar	carezsàsimo	V;IPFV;SBJV;PL;1;PST
arfiar	arfiarà	V;IND;PL;3;FUT
aprovar	aprovarisi	V;COND;PL;2
sofegar	sofegarìa	V;COND;SG;1
rumegar	rumegava	V;IPFV;IND;PL;3;PST
pexar	pexe	V;IMP;PL;3;LGSPEC2
métar	métarò	V;IND;SG;1;FUT
fracar	fraca	V;IND;PL;3;PRS
strupiar	strupie	V;SBJV;PL;3;PRS;LGSPEC1
inverinar	inveriné	V;IMP;PL;2
slongar	slongarìa	V;COND;SG;3
brustołar	brustołémo	V;SBJV;PL;1;PRS;LGSPEC1
łustrar	łustra	V;SBJV;PL;3;PRS;LGSPEC2
bévar	bévarìsimo	V;COND;PL;1
sciocar	sciochémo	V;IND;PL;1;PRS;LGSPEC1
alzsar	alzse	V;IMP;PL;3;LGSPEC2
springar	springar	V;NFIN
limitar	limita	V;SBJV;SG;1;PRS;LGSPEC2
łegałixar	łegałixe	V;IMP;SG;3;LGSPEC2
sluxegar	sluxeghe	V;SBJV;SG;1;PRS;LGSPEC1
tajar	taja	V;IND;SG;3;PRS
aterar	atera	V;IMP;SG;3;LGSPEC1
brustołar	brustołarisi	V;COND;SG;2
trincar	trinchémo	V;IND;PL;1;PRS;LGSPEC1
atribuir	atribuirisi	V;COND;PL;2
raprexentar	raprexente	V;SBJV;SG;1;PRS;LGSPEC1
prodùxer	produxì	V;SBJV;PL;2;PRS
aver	gavaria	V;COND;PL;3;LGSPEC3
augurar	augure	V;IMP;SG;3;LGSPEC2
slùxar	slùxa	V;SBJV;SG;3;PRS;LGSPEC2
vogar	voghe	V;IMP;SG;3;LGSPEC2
confrontar	confronta	V;IND;SG;3;PRS
sgropar	sgropòn	V;IND;PL;1;PRS;LGSPEC2
arfiar	arfiàvimo	V;IPFV;IND;PL;1;PST
bagnar	bagnase	V;IPFV;SBJV;SG;3;PST
batizxar	batizxa	V;SBJV;SG;1;PRS;LGSPEC2
ponciar	ponciar	V;NFIN
stuar	stuar	V;NFIN
vardar	vardarà	V;IND;SG;3;FUT
salvar	salvava	V;IPFV;IND;PL;3;PST
canbiar	canbiarà	V;IND;PL;3;FUT
intosegar	intosegarìa	V;COND;SG;1
bevarar	bevara	V;IND;PL;3;PRS
łibarar	łibare	V;SBJV;SG;3;PRS;LGSPEC1
busnar	busna	V;IMP;SG;2
springar	springhé	V;SBJV;PL;2;PRS
sbuxar	sbuxa	V;SBJV;SG;1;PRS;LGSPEC2
tornar	tornarè	V;IND;PL;2;FUT
menar	menarè	V;IND;PL;2;FUT
strupiar	strupiarìa	V;COND;SG;3
schincar	schinca	V;IMP;PL;3;LGSPEC1
rumar	ruma	V;IND;PL;3;PRS
ciacołar	ciacołarìa	V;COND;PL;3
łegałixar	łegałixarè	V;IND;SG;2;FUT
studiar	studia	V;SBJV;SG;3;PRS;LGSPEC2
catar	catarìa	V;COND;SG;3
abitar	abitàsimo	V;IPFV;SBJV;PL;1;PST
pareciar	parecia	V;IND;PL;3;PRS
anbir	anbirìa	V;COND;PL;3
remar	remémo	V;IND;PL;1;PRS;LGSPEC1
ricordar	ricordavi	V;IPFV;IND;SG;2;PST
sfondrar	sfondré	V;IND;PL;2;PRS
tirar	tira	V;IMP;SG;3;LGSPEC1
riciamar	riciami	V;SBJV;SG;2;PRS
danar	danavi	V;IPFV;IND;SG;2;PST
criar	criémo	V;SBJV;PL;1;PRS;LGSPEC1
criar	crie	V;IMP;SG;3;LGSPEC2
desidar	deside	V;SBJV;PL;3;PRS;LGSPEC1
picar	pica	V;SBJV;PL;3;PRS;LGSPEC2
augurar	augura	V;IMP;SG;2
vogar	vogarè	V;IND;PL;2;FUT
desmontar	desmontase	V;IPFV;SBJV;PL;3;PST
butar	buté	V;SBJV;PL;2;PRS
piantar	pianta	V;IND;PL;3;PRS
rodołar	rodołasi	V;IPFV;SBJV;SG;2;PST
mandar	mandarisi	V;COND;PL;2
ónxar	ónxivi	V;IPFV;IND;PL;2;PST
maciar	maciàvimo	V;IPFV;IND;PL;1;PST
desidar	desidarè	V;IND;PL;2;FUT
bearar	beara	V;IMP;SG;3;LGSPEC1
inpizar	inpizarisi	V;COND;PL;2
pełar	pełi	V;IND;SG;2;PRS
móvar	móvése	V;IPFV;SBJV;SG;1;PST
slùxar	slùxi	V;SBJV;SG;2;PRS
sugar	suga	V;SBJV;SG;3;PRS;LGSPEC2
dormir	dormise	V;IPFV;SBJV;SG;1;PST
mantegner	mantegni	V;IMP;SG;2
brustołar	brustołava	V;IPFV;IND;SG;3;PST
sfexar	sfexàsimo	V;IPFV;SBJV;PL;1;PST
concepir	concepirà	V;IND;SG;3;FUT
sonar	sonase	V;IPFV;SBJV;SG;3;PST
sostituir	sostituise	V;IND;PL;3;PRS
conpiłar	conpiła	V;IND;PL;3;PRS
capir	capirisi	V;COND;PL;2
butar	butàsimo	V;IPFV;SBJV;PL;1;PST
riciamar	riciamarìa	V;COND;PL;3
desgatejar	desgatejémo	V;IND;PL;1;PRS;LGSPEC1
ónxar	ónxarìa	V;COND;PL;3
desgatejar	desgateje	V;IMP;PL;3;LGSPEC2
łibarar	łibara	V;IMP;SG;2
misiar	misié	V;SBJV;PL;2;PRS
modifegar	modifegarémo	V;IND;PL;1;FUT
mancar	mancase	V;IPFV;SBJV;SG;3;PST
invadar	invadése	V;IPFV;SBJV;PL;3;PST
tugar	tugavi	V;IPFV;IND;PL;2;PST
sbiansar	sbiansémo	V;IMP;PL;1
capir	capise	V;IPFV;SBJV;PL;3;PST
conpletar	conpletarìsimo	V;COND;PL;1
sbiansar	sbiansàsimo	V;IPFV;SBJV;PL;1;PST
meritar	meritava	V;IPFV;IND;PL;3;PST
calcołar	calcołé	V;SBJV;PL;2;PRS
desmontar	desmontarè	V;IND;PL;2;FUT
unir	unise	V;IND;PL;3;PRS
pełar	pełarè	V;IND;SG;2;FUT
acetar	acetase	V;IPFV;SBJV;SG;1;PST
pełar	pełarisi	V;COND;SG;2
tocar	tocasi	V;IPFV;SBJV;SG;2;PST
intosegar	intosegàvimo	V;IPFV;IND;PL;1;PST
łibarar	łibarar	V;NFIN
brazsar	brazsé	V;IND;PL;2;PRS
viajar	viajémo	V;SBJV;PL;1;PRS;LGSPEC1
sponciar	sponciavi	V;IPFV;IND;SG;2;PST
gestir	gestisi	V;SBJV;SG;2;PRS
sentar	senta	V;IMP;SG;3
scorlar	scorlì	V;IMP;PL;2
abitar	abitarà	V;IND;PL;3;FUT
oler	olèđe	V;IPFV;IND;PL;2;PST
ponciar	poncie	V;SBJV;SG;1;PRS;LGSPEC1
łigar	łigava	V;IPFV;IND;PL;3;PST
curar	cura	V;IND;PL;3;PRS
sparagnar	sparagna	V;SBJV;SG;1;PRS;LGSPEC2
ciuciar	ciuciarìa	V;COND;SG;3
desligar	deslighémo	V;IND;PL;1;PRS;LGSPEC1
slùxar	slùxo	V;IND;SG;1;PRS
limitar	limitava	V;IPFV;IND;SG;3;PST
curar	curone	V;SBJV;PL;1;PRS;LGSPEC2
desgozar	desgozémo	V;IMP;PL;1
sparagnar	sparagnémo	V;IND;PL;1;PRS;LGSPEC1
criar	criasi	V;IPFV;SBJV;SG;2;PST
spuar	spua	V;IND;PL;3;PRS
begar	begar	V;NFIN
cascar	cascarìsimo	V;COND;PL;1
ponciar	ponciarisi	V;COND;PL;2
łegałixar	łegałixe	V;IMP;PL;3;LGSPEC2
spoxar	spoxa	V;SBJV;SG;1;PRS;LGSPEC2
sparagnar	sparagne	V;SBJV;SG;1;PRS;LGSPEC1
raprexentar	raprexentémo	V;IMP;PL;1
busnar	busnarè	V;IND;SG;2;FUT
mandar	mandava	V;IPFV;IND;SG;3;PST
schincar	schincòn	V;IND;PL;1;PRS;LGSPEC2
slisegar	sliseghémo	V;SBJV;PL;1;PRS;LGSPEC1
slùxar	slùxé	V;IND;PL;2;PRS
supiar	supia	V;IMP;PL;3;LGSPEC1
aver	avéa	V;IPFV;IND;SG;3;PST;LGSPEC1
intosegar	intoseghi	V;SBJV;SG;2;PRS
comandar	comandasi	V;IPFV;SBJV;PL;2;PST
proclamar	proclami	V;IND;SG;2;PRS
menar	menase	V;IPFV;SBJV;SG;3;PST
rodołar	rodołava	V;IPFV;IND;SG;3;PST
vixitar	vixitòn	V;IND;PL;1;PRS;LGSPEC2
aspetar	aspetarisi	V;COND;SG;2
sentar	sentésimo	V;IPFV;SBJV;PL;1;PST
confrontar	confrontarò	V;IND;SG;1;FUT
zontar	zontava	V;IPFV;IND;SG;3;PST
servir	servimo	V;SBJV;PL;1;PRS
tirar	tirarìsimo	V;COND;PL;1
proclamar	proclamarìsimo	V;COND;PL;1
trar	tra	V;SBJV;SG;3;PRS;LGSPEC2
sbrajar	sbrajase	V;IPFV;SBJV;PL;3;PST
carezsar	carezsarìsimo	V;COND;PL;1
spełar	speła	V;SBJV;PL;3;PRS;LGSPEC2
oler	olerisi	V;COND;SG;2
bruxar	bruxe	V;SBJV;PL;3;PRS;LGSPEC1
łigar	łigarémo	V;IND;PL;1;FUT
dir	dése	V;IPFV;SBJV;SG;3;PST
bruxar	bruxone	V;SBJV;PL;1;PRS;LGSPEC2
ciuciar	ciuciasi	V;IPFV;SBJV;SG;2;PST
slùxar	slùxarìa	V;COND;SG;1
łustrar	łustre	V;IMP;SG;3;LGSPEC2
atribuir	atribuise	V;IND;PL;3;PRS
limitar	limite	V;IMP;PL;3;LGSPEC2
serar	sere	V;SBJV;SG;3;PRS;LGSPEC1
pareciar	pareciase	V;IPFV;SBJV;PL;3;PST
cascar	cascasi	V;IPFV;SBJV;SG;2;PST
serar	serarìsimo	V;COND;PL;1
rasar	rase	V;IMP;SG;3;LGSPEC2
véndar	véndarè	V;IND;SG;2;FUT
bruxar	bruxarà	V;IND;PL;3;FUT
strapegar	strapegàvimo	V;IPFV;IND;PL;1;PST
misiar	misii	V;IND;SG;2;PRS
anbir	anbì	V;SBJV;PL;2;PRS
schincar	schincarìa	V;COND;SG;1
controłar	controłe	V;SBJV;SG;3;PRS;LGSPEC1
smagrir	smagrir	V;NFIN
canbiar	canbie	V;SBJV;PL;3;PRS;LGSPEC1
zontar	zonte	V;SBJV;PL;3;PRS;LGSPEC1
gestir	gestìvimo	V;IPFV;IND;PL;1;PST
gestir	gestisi	V;IPFV;SBJV;SG;2;PST
łustrar	łustra	V;IMP;SG;2
aprovar	aprovava	V;IPFV;IND;PL;3;PST
łigar	łighe	V;IMP;SG;3;LGSPEC2
controłar	controła	V;IND;PL;3;PRS
begar	begone	V;SBJV;PL;1;PRS;LGSPEC2
springar	springa	V;IMP;PL;3;LGSPEC1
studiar	studiarè	V;IND;SG;2;FUT
convìnzsar	convìnzsa	V;SBJV;SG;1;PRS
vixitar	vixitémo	V;SBJV;PL;1;PRS;LGSPEC1
comandar	comandémo	V;SBJV;PL;1;PRS;LGSPEC1
aver	avì	V;IND;PL;2;PRS
smagrir	smagrirìa	V;COND;PL;3
curar	curarè	V;IND;SG;2;FUT
sorar	sora	V;SBJV;PL;3;PRS;LGSPEC2
stuar	stua	V;IMP;SG;3;LGSPEC1
testimoniar	testimoniasi	V;IPFV;SBJV;SG;2;PST
vangar	vanghémo	V;IND;PL;1;PRS;LGSPEC1
acumular	acumula	V;IMP;SG;3;LGSPEC1
xontar	xonta	V;IND;PL;3;PRS
sentar	sentarìa	V;COND;PL;3
abitar	abitémo	V;IMP;PL;1
strapegar	strapeghe	V;SBJV;PL;3;PRS;LGSPEC1
bàtar	bàtése	V;IPFV;SBJV;PL;3;PST
springar	springarìa	V;COND;SG;3
menar	mena	V;SBJV;PL;3;PRS;LGSPEC2
cascar	cascarò	V;IND;SG;1;FUT
stisar	stise	V;SBJV;SG;1;PRS;LGSPEC1
védar	védéa	V;IPFV;IND;PL;3;PST
spoxar	spoxé	V;SBJV;PL;2;PRS
conpiłar	conpiłava	V;IPFV;IND;SG;3;PST
gestir	gestisa	V;SBJV;SG;1;PRS
sugar	sughé	V;IMP;PL;2
cascar	casca	V;IMP;SG;3;LGSPEC1
meritar	merite	V;SBJV;SG;3;PRS;LGSPEC1
inverinar	inverinémo	V;SBJV;PL;1;PRS;LGSPEC1
insìstar	insìstarìa	V;COND;SG;1
schincar	schincava	V;IPFV;IND;SG;3;PST
modifegar	modifegarisi	V;COND;PL;2
ciuciar	ciuciase	V;IPFV;SBJV;PL;3;PST
slùxar	slùxarò	V;IND;SG;1;FUT
métar	métarà	V;IND;SG;3;FUT
tajar	tajar	V;NFIN
bearar	beararìsimo	V;COND;PL;1
sentar	senta	V;SBJV;SG;3;PRS
insìstar	insìstése	V;IPFV;SBJV;PL;3;PST
asumar	asuméa	V;IPFV;IND;PL;3;PST
bearar	beare	V;IMP;SG;3;LGSPEC2
móvar	móvarémo	V;IND;PL;1;FUT
acetar	acetarisi	V;COND;SG;2
acetar	aceti	V;IND;SG;2;PRS
łegałixar	łegałixava	V;IPFV;IND;PL;3;PST
scorlar	scorla	V;IMP;SG;3
controłar	controła	V;SBJV;PL;3;PRS;LGSPEC2
bacajar	bacaja	V;IMP;SG;3;LGSPEC1
rasar	rasa	V;IMP;PL;3;LGSPEC1
becar	becavi	V;IPFV;IND;PL;2;PST
łustrar	łustrarè	V;IND;PL;2;FUT
xontar	xontàsimo	V;IPFV;SBJV;PL;1;PST
sgropar	sgropase	V;IPFV;SBJV;SG;1;PST
bearar	beare	V;SBJV;PL;3;PRS;LGSPEC1
vixitar	vixité	V;SBJV;PL;2;PRS
studiar	studie	V;SBJV;SG;1;PRS;LGSPEC1
mandar	mandémo	V;SBJV;PL;1;PRS;LGSPEC1
strapegar	strapeghé	V;SBJV;PL;2;PRS
raxónxer	raxónxivi	V;IPFV;IND;PL;2;PST
tugar	tugàvimo	V;IPFV;IND;PL;1;PST
védar	védarà	V;IND;SG;3;FUT
busnar	busno	V;IND;SG;1;PRS
sfexar	sfexa	V;SBJV;SG;1;PRS;LGSPEC2
stuar	stua	V;SBJV;SG;1;PRS;LGSPEC2
usir	usir	V;NFIN
inpizar	inpiza	V;SBJV;SG;1;PRS;LGSPEC2
brazsar	brazsarisi	V;COND;PL;2
busnar	busné	V;IND;PL;2;PRS
sbrajar	sbrajarè	V;IND;SG;2;FUT
sajar	sajarìa	V;COND;PL;3
dir	divi	V;IPFV;IND;SG;2;PST;LGSPEC1
sbuxar	sbuxarà	V;IND;PL;3;FUT
sparagnar	sparagnémo	V;IMP;PL;1
comandar	comande	V;SBJV;SG;1;PRS;LGSPEC1
sciocar	sciochi	V;IND;SG;2;PRS
sponciar	sponcia	V;IMP;PL;3;LGSPEC1
canbiar	canbié	V;SBJV;PL;2;PRS
riciamar	riciamo	V;IND;SG;1;PRS
concepir	concepìa	V;IPFV;IND;SG;1;PST
scoltar	scoltar	V;NFIN
tegner	tegnì	V;IND;PL;2;PRS
smagrir	smagrirà	V;IND;SG;3;FUT
viajar	viajase	V;IPFV;SBJV;SG;1;PST
star	ste	V;IMP;PL;3;LGSPEC2
pełar	pełe	V;IMP;SG;3;LGSPEC2
sbuxar	sbuxa	V;IMP;PL;3;LGSPEC1
serar	serarà	V;IND;SG;3;FUT
slongar	slonghémo	V;IND;PL;1;PRS;LGSPEC1
vixitar	vixitava	V;IPFV;IND;PL;3;PST
zontar	zontasi	V;IPFV;SBJV;PL;2;PST
xontar	xontar	V;NFIN
fracar	frachémo	V;SBJV;PL;1;PRS;LGSPEC1
acetar	acetava	V;IPFV;IND;PL;3;PST
picar	picarè	V;IND;SG;2;FUT
łegałixar	łegałixarisi	V;COND;PL;2
stuar	stue	V;IMP;PL;3;LGSPEC2
rasar	rasémo	V;IMP;PL;1
limitar	limita	V;IMP;SG;2
finir	finirìsimo	V;COND;PL;1
remar	remémo	V;SBJV;PL;1;PRS;LGSPEC1
usir	usise	V;IPFV;SBJV;PL;3;PST
smagrir	smagrìvimo	V;IPFV;IND;PL;1;PST
schincar	schincar	V;NFIN
łibarar	łibararà	V;IND;SG;3;FUT
łibarar	łibare	V;SBJV;SG;1;PRS;LGSPEC1
pareciar	pareciarìsimo	V;COND;PL;1
trincar	trinco	V;IND;SG;1;PRS
sugar	sughe	V;SBJV;SG;1;PRS;LGSPEC1
sgropar	sgropémo	V;SBJV;PL;1;PRS;LGSPEC1
bagnar	bagna	V;IND;PL;3;PRS
tegner	tegnémo	V;IND;PL;1;PRS
łegałixar	łegałixa	V;IND;SG;3;PRS
piantar	piante	V;SBJV;SG;3;PRS;LGSPEC1
tugar	tughé	V;IND;PL;2;PRS
cascar	cascarà	V;IND;PL;3;FUT
tegner	tegna	V;SBJV;SG;3;PRS
afermar	afermase	V;IPFV;SBJV;SG;3;PST
picar	picarò	V;IND;SG;1;FUT
anoverar	anoveravi	V;IPFV;IND;SG;2;PST
bojir	bojìvimo	V;IPFV;IND;PL;1;PST
desmontar	desmontàsimo	V;IPFV;SBJV;PL;1;PST
misiar	misiasi	V;IPFV;SBJV;SG;2;PST
sugar	sugarìa	V;COND;SG;1
sonar	sonavi	V;IPFV;IND;PL;2;PST
conpiłar	conpiłé	V;SBJV;PL;2;PRS
sonar	sonava	V;IPFV;IND;SG;3;PST
rodołar	rodołé	V;SBJV;PL;2;PRS
trar	tré	V;SBJV;PL;2;PRS
móvar	móva	V;IMP;SG;3
tegner	tegno	V;IND;SG;1;PRS
pexar	pexarisi	V;COND;PL;2
carezsar	carezsarà	V;IND;PL;3;FUT
desidar	desidase	V;IPFV;SBJV;SG;1;PST
cascar	casché	V;IND;PL;2;PRS
usir	usirè	V;IND;SG;2;FUT
desmontar	desmontarisi	V;COND;PL;2
catar	catémo	V;IND;PL;1;PRS;LGSPEC1
łevar	łeva	V;IMP;PL;3;LGSPEC1
strapegar	strapegarà	V;IND;PL;3;FUT
afermar	afermar	V;NFIN
sluxegar	sluxegarémo	V;IND;PL;1;FUT
rumegar	rumegarè	V;IND;PL;2;FUT
xontar	xontarisi	V;COND;PL;2
salvar	salvo	V;IND;SG;1;PRS
ricordar	ricordasi	V;IPFV;SBJV;SG;2;PST
sofegar	sofeghémo	V;IMP;PL;1
butar	bute	V;SBJV;SG;3;PRS;LGSPEC1
brustołar	brustołarìa	V;COND;SG;1
menar	mene	V;SBJV;SG;3;PRS;LGSPEC1
spoxar	spoxémo	V;SBJV;PL;1;PRS;LGSPEC1
soranomenar	soranomene	V;IMP;SG;3;LGSPEC2
copiar	copie	V;IMP;PL;3;LGSPEC2
vangar	vangasi	V;IPFV;SBJV;SG;2;PST
łustrar	łustràsimo	V;IPFV;SBJV;PL;1;PST
mandar	mandi	V;SBJV;SG;2;PRS
xontar	xontase	V;IPFV;SBJV;SG;3;PST
star	sta	V;SBJV;SG;1;PRS;LGSPEC2
łustrar	łustrarìa	V;COND;SG;3
brazsar	brazsarìa	V;COND;SG;1
cascar	cascarìa	V;COND;SG;1
łevar	łevava	V;IPFV;IND;PL;3;PST
maciar	maciar	V;NFIN
rodołar	rodołé	V;IND;PL;2;PRS
zontar	zontava	V;IPFV;IND;PL;3;PST
védar	védarò	V;IND;SG;1;FUT
sostituir	sostituisa	V;SBJV;SG;3;PRS
fracar	fracarémo	V;IND;PL;1;FUT
conpletar	conpleta	V;IMP;SG;2
abitar	abitòn	V;IND;PL;1;PRS;LGSPEC2
strupiar	strupiavi	V;IPFV;IND;PL;2;PST
butar	butarisi	V;COND;SG;2
xontar	xontasi	V;IPFV;SBJV;PL;2;PST
meritar	merité	V;SBJV;PL;2;PRS
aver	avémo	V;IMP;PL;1
rasar	rasava	V;IPFV;IND;PL;3;PST
sonar	sona	V;SBJV;SG;1;PRS;LGSPEC2
dir	dése	V;IPFV;SBJV;SG;1;PST
sfondrar	sfondrarò	V;IND;SG;1;FUT
vangar	vangàvimo	V;IPFV;IND;PL;1;PST
batexemar	batexema	V;IND;SG;3;PRS
stuar	stuarìa	V;COND;PL;3
bearar	bearava	V;IPFV;IND;SG;1;PST
sugar	sugasi	V;IPFV;SBJV;PL;2;PST
finir	finisa	V;SBJV;SG;3;PRS
invadar	invadarémo	V;IND;PL;1;FUT
canbiar	canbiase	V;IPFV;SBJV;PL;3;PST
nominar	nominarìa	V;COND;SG;1
raprexentar	raprexentarè	V;IND;SG;2;FUT
tajar	tajasi	V;IPFV;SBJV;SG;2;PST
vogar	vogarò	V;IND;SG;1;FUT
brazsar	brazsa	V;IMP;PL;3;LGSPEC1
usir	usirìa	V;COND;PL;3
carezxar	carezxòn	V;IND;PL;1;PRS;LGSPEC2
springar	springa	V;IMP;SG;2
usir	usirìa	V;COND;SG;3
carezxar	carezxarìsimo	V;COND;PL;1
remar	remasi	V;IPFV;SBJV;PL;2;PST
vixitar	vixitarìa	V;COND;PL;3
limitar	limitasi	V;IPFV;SBJV;PL;2;PST
sfexar	sfexe	V;SBJV;SG;1;PRS;LGSPEC1
concepir	concepir	V;NFIN
bearar	beararè	V;IND;PL;2;FUT
bruxar	bruxa	V;IND;PL;3;PRS
ofendar	ofendarà	V;IND;PL;3;FUT
arfiar	arfia	V;SBJV;SG;1;PRS;LGSPEC2
acumular	acumularè	V;IND;SG;2;FUT
brazsar	brazsòn	V;IND;PL;1;PRS;LGSPEC2
copiar	copiémo	V;IMP;PL;1
scorlar	scorlivi	V;IPFV;IND;PL;2;PST
sugar	sughi	V;IND;SG;2;PRS
trincar	trinca	V;IMP;SG;2
raxónxer	raxónxi	V;IND;SG;2;PRS
dir	da	V;SBJV;SG;3;PRS
acetar	acetavi	V;IPFV;IND;PL;2;PST
strapegar	strapegavi	V;IPFV;IND;SG;2;PST
mancar	manco	V;IND;SG;1;PRS
córar	córa	V;IMP;PL;3
pexar	pexa	V;IMP;PL;3;LGSPEC1
tajar	taje	V;SBJV;SG;1;PRS;LGSPEC1
abitar	abita	V;IMP;SG;2
spoxar	spoxarè	V;IND;PL;2;FUT
starnudar	starnudasi	V;IPFV;SBJV;PL;2;PST
ónxar	ónxa	V;SBJV;PL;3;PRS
inverinar	inverina	V;IMP;PL;3;LGSPEC1
comandar	comanda	V;SBJV;SG;3;PRS;LGSPEC2
prodùxer	produxémo	V;IMP;PL;1
brustołar	brustołasi	V;IPFV;SBJV;PL;2;PST
trar	trase	V;IPFV;SBJV;SG;1;PST
aterar	atere	V;IMP;SG;3;LGSPEC2
votar	votar	V;NFIN
sentir	sentirà	V;IND;PL;3;FUT
votar	votarè	V;IND;SG;2;FUT
bévar	bévo	V;IND;SG;1;PRS
inpizar	inpizémo	V;IMP;PL;1
aterar	atera	V;IMP;PL;3;LGSPEC1
piànxar	piànxéa	V;IPFV;IND;SG;1;PST
prodùxer	produxì	V;IMP;PL;2
busnar	busne	V;SBJV;SG;1;PRS;LGSPEC1
scoltar	scoltava	V;IPFV;IND;SG;1;PST
batexemar	batexemava	V;IPFV;IND;SG;3;PST
ponciar	ponciòn	V;IND;PL;1;PRS;LGSPEC2
nominar	nominarè	V;IND;PL;2;FUT
provar	provone	V;SBJV;PL;1;PRS;LGSPEC2
nominar	nominé	V;SBJV;PL;2;PRS
stuar	stuase	V;IPFV;SBJV;SG;1;PST
starnudar	starnuda	V;IND;PL;3;PRS
védar	vidi	V;SBJV;SG;2;PRS
comandar	comandi	V;SBJV;SG;2;PRS
conpiłar	conpiłase	V;IPFV;SBJV;SG;3;PST
pexar	pexar	V;NFIN
sfexar	sfexa	V;IND;PL;3;PRS
carezsar	carezsémo	V;SBJV;PL;1;PRS;LGSPEC1
desidar	desidàvimo	V;IPFV;IND;PL;1;PST
córar	córo	V;IND;SG;1;PRS
bagnar	bagnòn	V;IND;PL;1;PRS;LGSPEC2
servir	servirisi	V;COND;PL;2
canbiar	canbiarà	V;IND;SG;3;FUT
comandar	comande	V;IMP;PL;3;LGSPEC2
sluxegar	sluxegarisi	V;COND;SG;2
asumar	asumo	V;IND;SG;1;PRS
tornar	tornar	V;NFIN
confrontar	confronta	V;SBJV;PL;3;PRS;LGSPEC2
abitar	abitarìa	V;COND;PL;3
provar	provòn	V;IND;PL;1;PRS;LGSPEC2
criar	cria	V;IND;PL;3;PRS
brustołar	brustoła	V;IMP;SG;3;LGSPEC1
bojir	bojise	V;IND;PL;3;PRS
anbir	anbirè	V;IND;PL;2;FUT
intosegar	intosego	V;IND;SG;1;PRS
sbiansar	sbiansasi	V;IPFV;SBJV;SG;2;PST
picar	pichi	V;SBJV;SG;2;PRS
limitar	limita	V;IMP;SG;3;LGSPEC1
sbrajar	sbrajone	V;SBJV;PL;1;PRS;LGSPEC2
bearar	bearase	V;IPFV;SBJV;PL;3;PST
viajar	viajavi	V;IPFV;IND;PL;2;PST
testimoniar	testimoniar	V;NFIN
acetar	acetarémo	V;IND;PL;1;FUT
capir	capirisi	V;COND;SG;2
sponciar	sponciòn	V;IND;PL;1;PRS;LGSPEC2
pexar	pexase	V;IPFV;SBJV;SG;1;PST
ricordar	ricordase	V;IPFV;SBJV;SG;3;PST
desgatejar	desgatejarìa	V;COND;SG;3
catar	catavi	V;IPFV;IND;SG;2;PST
sofegar	sofega	V;SBJV;SG;3;PRS;LGSPEC2
finir	finirisi	V;COND;SG;2
sciocar	sciocar	V;NFIN
insìstar	insìstarà	V;IND;SG;3;FUT
ponciar	poncié	V;IMP;PL;2
aver	avarisi	V;COND;SG;2
afermar	afermarìa	V;COND;PL;3
mandar	mandémo	V;IMP;PL;1
acumular	acumula	V;SBJV;PL;3;PRS;LGSPEC2
convìnzsar	convìnzsa	V;IMP;SG;3
ribelar	ribelémo	V;IND;PL;1;PRS;LGSPEC1
bevarar	bevarar	V;NFIN
vangar	vanghe	V;IMP;PL;3;LGSPEC2
acetar	acetarè	V;IND;SG;2;FUT
asumar	asuma	V;SBJV;PL;3;PRS
mancar	mancarémo	V;IND;PL;1;FUT
maciar	maciarò	V;IND;SG;1;FUT
raprexentar	raprexenta	V;SBJV;SG;1;PRS;LGSPEC2
móvar	móvéa	V;IPFV;IND;PL;3;PST
sostituir	sostituimo	V;IND;PL;1;PRS
aver	avésimo	V;IPFV;SBJV;PL;1;PST
danar	danar	V;NFIN
divìdar	divìdarè	V;IND;SG;2;FUT
spełar	speła	V;IND;PL;3;PRS
stisar	stisarè	V;IND;SG;2;FUT
ponciar	ponciava	V;IPFV;IND;SG;3;PST
inverinar	inverina	V;SBJV;PL;3;PRS;LGSPEC2
confrontar	confrontava	V;IPFV;IND;PL;3;PST
vogar	vogavi	V;IPFV;IND;SG;2;PST
canbiar	canbiava	V;IPFV;IND;SG;1;PST
strapegar	strapegarìsimo	V;COND;PL;1
limitar	limitavi	V;IPFV;IND;SG;2;PST
desidar	desidarìsimo	V;COND;PL;1
pexar	pexa	V;IND;PL;3;PRS
sugar	suga	V;SBJV;PL;3;PRS;LGSPEC2
asumar	asumarè	V;IND;SG;2;FUT
spoxar	spoxa	V;IMP;SG;3;LGSPEC1
sfexar	sfexarìa	V;COND;PL;3
begar	beghe	V;IMP;SG;3;LGSPEC2
mandar	mande	V;SBJV;PL;3;PRS;LGSPEC1
schincar	schinchémo	V;SBJV;PL;1;PRS;LGSPEC1
carezsar	carezsarémo	V;IND;PL;1;FUT
finir	finirò	V;IND;SG;1;FUT
alzsar	alzsa	V;IMP;PL;3;LGSPEC1
asaltar	asaltarè	V;IND;PL;2;FUT
łevar	łeve	V;IMP;SG;3;LGSPEC2
bàtar	bàtì	V;IND;PL;2;PRS
carezxar	carezxava	V;IPFV;IND;SG;1;PST
tegner	tegnévimo	V;IPFV;IND;PL;1;PST
sugar	sugava	V;IPFV;IND;SG;1;PST
intosegar	intoseghe	V;SBJV;SG;3;PRS;LGSPEC1
slùxar	slùxarà	V;IND;SG;3;FUT
vixitar	vixitàsimo	V;IPFV;SBJV;PL;1;PST
busnar	busnava	V;IPFV;IND;PL;3;PST
ofendar	ofendéa	V;IPFV;IND;SG;3;PST
aterar	atera	V;SBJV;SG;1;PRS;LGSPEC2
batizxar	batizxi	V;IND;SG;2;PRS
arfiar	arfiàsimo	V;IPFV;SBJV;PL;1;PST
trar	trémo	V;IND;PL;1;PRS;LGSPEC1
curar	curarò	V;IND;SG;1;FUT
rasar	raso	V;IND;SG;1;PRS
rumar	rumone	V;SBJV;PL;1;PRS;LGSPEC2
sbuxar	sbuxava	V;IPFV;IND;SG;1;PST
spoxar	spoxarà	V;IND;PL;3;FUT
modifegar	modifega	V;SBJV;SG;1;PRS;LGSPEC2
limitar	limitarò	V;IND;SG;1;FUT
ponciar	ponciasi	V;IPFV;SBJV;PL;2;PST
bacajar	bacajase	V;IPFV;SBJV;SG;3;PST
véndar	véndar	V;NFIN
slùxar	slùxòn	V;IND;PL;1;PRS;LGSPEC2
starnudar	starnudi	V;IND;SG;2;PRS
slisegar	slisegone	V;SBJV;PL;1;PRS;LGSPEC2
fracar	fraca	V;SBJV;PL;3;PRS;LGSPEC2
vardar	vardémo	V;SBJV;PL;1;PRS;LGSPEC1
tornar	tornarìa	V;COND;SG;3
strupiar	strupiàvimo	V;IPFV;IND;PL;1;PST
votar	votase	V;IPFV;SBJV;SG;3;PST
dir	darìa	V;COND;PL;3
serar	seravi	V;IPFV;IND;PL;2;PST
aprovar	aprove	V;SBJV;SG;3;PRS;LGSPEC1
stisar	stisavi	V;IPFV;IND;PL;2;PST
slongar	slongava	V;IPFV;IND;SG;3;PST
piantar	piantava	V;IPFV;IND;PL;3;PST
supiar	supiémo	V;IND;PL;1;PRS;LGSPEC1
strapegar	strapegava	V;IPFV;IND;SG;3;PST
catar	catarémo	V;IND;PL;1;FUT
scoltar	scolta	V;IND;PL;3;PRS
alzsar	alzsémo	V;SBJV;PL;1;PRS;LGSPEC1
bojir	bojirìa	V;COND;PL;3
aprovar	aprova	V;IMP;PL;3;LGSPEC1
svodar	svodarè	V;IND;PL;2;FUT
móvar	móvì	V;IND;PL;2;PRS
inpizar	inpizé	V;IND;PL;2;PRS
ponciar	poncie	V;SBJV;SG;3;PRS;LGSPEC1
mantegner	mantegnése	V;IPFV;SBJV;PL;3;PST
acetar	acetone	V;SBJV;PL;1;PRS;LGSPEC2
córar	curi	V;SBJV;SG;2;PRS
desidar	desida	V;IMP;SG;3;LGSPEC1
studiar	studiava	V;IPFV;IND;PL;3;PST
desgatejar	desgatejarè	V;IND;PL;2;FUT
ciacołar	ciacołe	V;SBJV;PL;3;PRS;LGSPEC1
aver	avése	V;IPFV;SBJV;SG;1;PST
misiar	misia	V;IND;PL;3;PRS
supiar	supiase	V;IPFV;SBJV;SG;1;PST
trar	trarisi	V;COND;SG;2
ribelar	ribele	V;IMP;SG;3;LGSPEC2
véndar	véndisi	V;IPFV;SBJV;SG;2;PST
inpizar	inpizarè	V;IND;PL;2;FUT
carezsar	carezsase	V;IPFV;SBJV;SG;1;PST
salvar	salvémo	V;IND;PL;1;PRS;LGSPEC1
fracar	fraché	V;SBJV;PL;2;PRS
bojir	bojisi	V;IND;SG;2;PRS
brazsar	brazsarémo	V;IND;PL;1;FUT
schincar	schincava	V;IPFV;IND;PL;3;PST
aspetar	aspetarè	V;IND;PL;2;FUT
spełar	spełémo	V;IND;PL;1;PRS;LGSPEC1
sciocar	sciocàsimo	V;IPFV;SBJV;PL;1;PST
svodar	svodarìa	V;COND;SG;3
raprexentar	raprexento	V;IND;SG;1;PRS
bruxar	bruxa	V;SBJV;SG;3;PRS;LGSPEC2
viajar	viajo	V;IND;SG;1;PRS
sciocar	sciocarà	V;IND;PL;3;FUT
córar	córarìa	V;COND;SG;1
misiar	misiémo	V;SBJV;PL;1;PRS;LGSPEC1
strupiar	strupiase	V;IPFV;SBJV;SG;1;PST
piantar	piantase	V;IPFV;SBJV;PL;3;PST
stuar	stua	V;SBJV;PL;3;PRS;LGSPEC2
misiar	misiàsimo	V;IPFV;SBJV;PL;1;PST
rumar	rumé	V;SBJV;PL;2;PRS
trar	trasi	V;IPFV;SBJV;SG;2;PST
proclamar	proclame	V;IMP;SG;3;LGSPEC2
testimoniar	testimonia	V;SBJV;SG;1;PRS;LGSPEC2
viajar	viajé	V;SBJV;PL;2;PRS
nominar	nominasi	V;IPFV;SBJV;SG;2;PST
sfondrar	sfondrarémo	V;IND;PL;1;FUT
criar	criarà	V;IND;SG;3;FUT
aver	avéa	V;IPFV;IND;SG;1;PST;LGSPEC1
danar	dani	V;IND;SG;2;PRS
métar	métésimo	V;IPFV;SBJV;PL;1;PST
atribuir	atribuivi	V;IPFV;IND;SG;2;PST
tugar	tugarìa	V;COND;SG;3
mandar	mandarìa	V;COND;SG;1
ribelar	ribelone	V;SBJV;PL;1;PRS;LGSPEC2
sentir	sentisi	V;IPFV;SBJV;SG;2;PST
soranomenar	soranomenarìa	V;COND;PL;3
abitar	abitone	V;SBJV;PL;1;PRS;LGSPEC2
calcołar	calcołase	V;IPFV;SBJV;SG;1;PST
bevarar	bevare	V;SBJV;SG;3;PRS;LGSPEC1
becar	beca	V;IMP;SG;2
łustrar	łustré	V;IND;PL;2;PRS
smagrir	smagrirìsimo	V;COND;PL;1
ciacołar	ciacoła	V;SBJV;PL;3;PRS;LGSPEC2
scorlar	scorlì	V;SBJV;PL;2;PRS
butar	buti	V;SBJV;SG;2;PRS
abitar	abitarìa	V;COND;SG;1
acumular	acumulase	V;IPFV;SBJV;PL;3;PST
comandar	comandarò	V;IND;SG;1;FUT
intosegar	intosegòn	V;IND;PL;1;PRS;LGSPEC2
strapegar	strapega	V;SBJV;PL;3;PRS;LGSPEC2
dir	do	V;IND;SG;1;PRS
trincar	trinchémo	V;IMP;PL;1
oler	olea	V;IPFV;IND;PL;3;PST
meritar	meritone	V;SBJV;PL;1;PRS;LGSPEC2
acetar	aceta	V;IND;SG;3;PRS
scorlar	scorli	V;IMP;SG;2
aver	ò	V;IND;SG;1;PRS;LGSPEC2
intosegar	intosegarémo	V;IND;PL;1;FUT
inverinar	inverinasi	V;IPFV;SBJV;SG;2;PST
rumar	rumarè	V;IND;SG;2;FUT
divìdar	divìdarémo	V;IND;PL;1;FUT
sparagnar	sparagne	V;SBJV;PL;3;PRS;LGSPEC1
strapegar	strapeghe	V;SBJV;SG;1;PRS;LGSPEC1
inpizar	inpizarìa	V;COND;SG;1
gestir	gestirisi	V;COND;SG;2
rodołar	rodołavi	V;IPFV;IND;SG;2;PST
slùxar	slùxa	V;IMP;SG;3;LGSPEC1
ribelar	ribelava	V;IPFV;IND;SG;1;PST
sfondrar	sfondrarà	V;IND;PL;3;FUT
sorar	sorase	V;IPFV;SBJV;SG;1;PST
bagnar	bagnarè	V;IND;PL;2;FUT
concepir	concepise	V;IND;SG;3;PRS
bevarar	bevari	V;SBJV;SG;2;PRS
desgatejar	desgatejo	V;IND;SG;1;PRS
ónxar	ónxémo	V;IND;PL;1;PRS
aver	avarè	V;IND;SG;2;FUT
nominar	nominarà	V;IND;SG;3;FUT
ónxar	ónxémo	V;SBJV;PL;1;PRS
strapegar	strapegone	V;SBJV;PL;1;PRS;LGSPEC2
butar	butavi	V;IPFV;IND;PL;2;PST
ciuciar	ciuciava	V;IPFV;IND;SG;1;PST
ponciar	ponciarè	V;IND;SG;2;FUT
servir	servì	V;SBJV;PL;2;PRS
inpizar	inpiza	V;IMP;PL;3;LGSPEC1
atribuir	atribuimo	V;IMP;PL;1
vangar	vangase	V;IPFV;SBJV;PL;3;PST
piantar	piantavi	V;IPFV;IND;PL;2;PST
rumar	rumarà	V;IND;SG;3;FUT
convìnzsar	convìnzsarisi	V;COND;SG;2;LGSPEC1
tirar	tira	V;IMP;SG;2
piànxar	piànxarìa	V;COND;SG;3
starnudar	starnudavi	V;IPFV;IND;PL;2;PST
asaltar	asalta	V;IND;SG;3;PRS
supiar	supiarìa	V;COND;SG;3
convìnzsar	convìnzsarò	V;IND;SG;1;FUT
picar	picase	V;IPFV;SBJV;SG;3;PST
ciuciar	ciucié	V;SBJV;PL;2;PRS
copiar	copiasi	V;IPFV;SBJV;PL;2;PST
trar	tre	V;IMP;SG;3;LGSPEC2
vogar	voghé	V;IND;PL;2;PRS
mandar	mandone	V;SBJV;PL;1;PRS;LGSPEC2
insìstar	insìstésimo	V;IPFV;SBJV;PL;1;PST
sugar	sugarisi	V;COND;PL;2
confrontar	confronti	V;IND;SG;2;PRS;LGSPEC1
ónxar	ónxar	V;NFIN
batizxar	batizxarà	V;IND;SG;3;FUT
inverinar	inverinémo	V;IMP;PL;1
łustrar	łustrase	V;IPFV;SBJV;SG;1;PST
anbir	anbimo	V;IND;PL;1;PRS
bojir	bojì	V;SBJV;PL;2;PRS
bàtar	bàtéa	V;IPFV;IND;SG;1;PST
sponciar	sponcie	V;SBJV;PL;3;PRS;LGSPEC1
rumegar	rumeghi	V;SBJV;SG;2;PRS
bacajar	bacajé	V;SBJV;PL;2;PRS
alzsar	alzse	V;IMP;SG;3;LGSPEC2
strupiar	strupiòn	V;IND;PL;1;PRS;LGSPEC2
métar	métisi	V;IPFV;SBJV;SG;2;PST
salvar	salva	V;IND;SG;3;PRS
rasar	rasavi	V;IPFV;IND;SG;2;PST
soranomenar	soranomena	V;SBJV;SG;3;PRS;LGSPEC2
alzsar	alzsasi	V;IPFV;SBJV;SG;2;PST
védar	védarisi	V;COND;SG;2
intosegar	intoseghémo	V;IND;PL;1;PRS;LGSPEC1
mantegner	mantegna	V;IMP;SG;3
copiar	copiavi	V;IPFV;IND;SG;2;PST
usir	usì	V;IND;PL;2;PRS
desidar	desidava	V;IPFV;IND;SG;3;PST
desgozar	desgoza	V;IND;PL;3;PRS
vangar	vanga	V;SBJV;SG;3;PRS;LGSPEC2
sparagnar	sparagnarò	V;IND;SG;1;FUT
desidar	desida	V;SBJV;SG;1;PRS;LGSPEC2
vìvar	vìvéa	V;IPFV;IND;SG;1;PST
atribuir	atribuisa	V;SBJV;PL;3;PRS
véndar	véndarò	V;IND;SG;1;FUT
confrontar	confronta	V;IMP;SG;3;LGSPEC1
conpletar	conpleta	V;IMP;SG;3;LGSPEC1
métar	métarìa	V;COND;PL;3
łevar	łevo	V;IND;SG;1;PRS
dir	darìsimo	V;COND;PL;1
slongar	slongarìa	V;COND;PL;3
vangar	vangarìsimo	V;COND;PL;1
salvar	salvòn	V;IND;PL;1;PRS;LGSPEC2
concepir	concepise	V;IPFV;SBJV;SG;1;PST
rasar	rasàvimo	V;IPFV;IND;PL;1;PST
busnar	busnavi	V;IPFV;IND;SG;2;PST
védar	védar	V;NFIN
abitar	abitarè	V;IND;SG;2;FUT
alzsar	alzsava	V;IPFV;IND;SG;1;PST
ciuciar	ciucie	V;SBJV;SG;3;PRS;LGSPEC1
sponciar	sponcie	V;IMP;PL;3;LGSPEC2
meritar	merité	V;IMP;PL;2
métar	méta	V;SBJV;SG;3;PRS
rumar	rumi	V;IND;SG;2;PRS
sluxegar	sluxegava	V;IPFV;IND;PL;3;PST
carezxar	carezxase	V;IPFV;SBJV;SG;1;PST
sciocar	scioché	V;SBJV;PL;2;PRS
tirar	tire	V;SBJV;PL;3;PRS;LGSPEC1
usir	usìvimo	V;IPFV;IND;PL;1;PST
spoxar	spoxòn	V;IND;PL;1;PRS;LGSPEC2
sentir	sentirò	V;IND;SG;1;FUT
vogar	voghémo	V;SBJV;PL;1;PRS;LGSPEC1
proclamar	proclamone	V;SBJV;PL;1;PRS;LGSPEC2
véndar	véndémo	V;IND;PL;1;PRS
arfiar	arfiarìa	V;COND;SG;3
aspetar	aspetar	V;NFIN
tirar	tiràvimo	V;IPFV;IND;PL;1;PST
carezxar	carezxe	V;SBJV;PL;3;PRS;LGSPEC1
desgozar	desgozarò	V;IND;SG;1;FUT
slongar	slonga	V;IMP;SG;2
slùxar	slùxémo	V;IND;PL;1;PRS;LGSPEC1
canbiar	canbie	V;IMP;SG;3;LGSPEC2
aprovar	aprove	V;SBJV;SG;1;PRS;LGSPEC1
fracar	fracàvimo	V;IPFV;IND;PL;1;PST
augurar	auguré	V;IMP;PL;2
mandar	mandarè	V;IND;PL;2;FUT
tocar	tochi	V;IND;SG;2;PRS
łustrar	łustrémo	V;IND;PL;1;PRS;LGSPEC1
fracar	frache	V;IMP;PL;3;LGSPEC2
testimoniar	testimoniarè	V;IND;PL;2;FUT
pexar	pexava	V;IPFV;IND;SG;3;PST
anoverar	anovera	V;SBJV;SG;1;PRS;LGSPEC2
votar	votòn	V;IND;PL;1;PRS;LGSPEC2
ponciar	poncione	V;SBJV;PL;1;PRS;LGSPEC2
desgozar	desgozase	V;IPFV;SBJV;SG;1;PST
sciocar	sciocasi	V;IPFV;SBJV;PL;2;PST
testimoniar	testimonié	V;IMP;PL;2
ribelar	ribelarìa	V;COND;SG;3
łegałixar	łegałixarémo	V;IND;PL;1;FUT
limitar	limita	V;SBJV;PL;3;PRS;LGSPEC2
ribelar	ribele	V;SBJV;SG;3;PRS;LGSPEC1
oler	ope	V;SBJV;PL;3;PRS
tugar	tuga	V;SBJV;SG;1;PRS;LGSPEC2
bearar	bearase	V;IPFV;SBJV;SG;3;PST
convìnzsar	convìnzséa	V;IPFV;IND;SG;1;PST
mancar	mancavi	V;IPFV;IND;SG;2;PST
rodołar	rodołar	V;NFIN
tornar	torné	V;IMP;PL;2
tirar	tiròn	V;IND;PL;1;PRS;LGSPEC2
desgatejar	desgatejé	V;IMP;PL;2
ponciar	ponciarémo	V;IND;PL;1;FUT
studiar	studiòn	V;IND;PL;1;PRS;LGSPEC2
piànxar	piànxarisi	V;COND;PL;2
canbiar	canbiàvimo	V;IPFV;IND;PL;1;PST
proclamar	proclamòn	V;IND;PL;1;PRS;LGSPEC2
pełar	pełémo	V;SBJV;PL;1;PRS;LGSPEC1
atribuir	atribuirò	V;IND;SG;1;FUT
anbir	anbìvimo	V;IPFV;IND;PL;1;PST
controłar	controłase	V;IPFV;SBJV;PL;3;PST
calcołar	calcołarìa	V;COND;SG;1
asumar	asumémo	V;IMP;PL;1
bàtar	bàtéa	V;IPFV;IND;PL;3;PST
prodùxer	produxéa	V;IPFV;IND;SG;1;PST
slùxar	slùxone	V;SBJV;PL;1;PRS;LGSPEC2
asaltar	asalta	V;SBJV;SG;1;PRS;LGSPEC2
picar	picava	V;IPFV;IND;SG;1;PST
desgatejar	desgatejasi	V;IPFV;SBJV;SG;2;PST
desidar	desidavi	V;IPFV;IND;PL;2;PST
conpletar	conpletase	V;IPFV;SBJV;SG;3;PST
picar	pica	V;IND;SG;3;PRS
sorar	sorone	V;SBJV;PL;1;PRS;LGSPEC2
bruxar	bruxa	V;IMP;SG;2
łustrar	łustra	V;IMP;SG;3;LGSPEC1
sparagnar	sparagna	V;IMP;PL;3;LGSPEC1
calcołar	calcoła	V;IND;PL;3;PRS
bruxar	bruxarò	V;IND;SG;1;FUT
sentir	sentìa	V;IPFV;IND;PL;3;PST
trincar	trincarémo	V;IND;PL;1;FUT
meritar	meriti	V;IND;SG;2;PRS
sentar	sentémo	V;SBJV;PL;1;PRS
inverinar	inverinase	V;IPFV;SBJV;SG;3;PST
sbiansar	sbiansavi	V;IPFV;IND;SG;2;PST
stuar	stuémo	V;SBJV;PL;1;PRS;LGSPEC1
pareciar	pareciémo	V;IMP;PL;1
sbiansar	sbiansé	V;IMP;PL;2
anoverar	anoverava	V;IPFV;IND;SG;1;PST
ribelar	ribelarà	V;IND;PL;3;FUT
vogar	vogàvimo	V;IPFV;IND;PL;1;PST
sonar	sonarè	V;IND;PL;2;FUT
tornar	tornone	V;SBJV;PL;1;PRS;LGSPEC2
bruxar	bruxé	V;IND;PL;2;PRS
capir	capise	V;IPFV;SBJV;SG;3;PST
tornar	tornase	V;IPFV;SBJV;SG;1;PST
calcołar	calcoła	V;IMP;PL;3;LGSPEC1
dir	darè	V;IND;SG;2;FUT
asaltar	asaltase	V;IPFV;SBJV;SG;3;PST
cascar	cascava	V;IPFV;IND;SG;1;PST
asaltar	asaltarè	V;IND;SG;2;FUT
sentar	senti	V;SBJV;SG;2;PRS
véndar	vénde	V;IND;PL;3;PRS
sonar	sonase	V;IPFV;SBJV;PL;3;PST
desligar	desliga	V;IND;PL;3;PRS
acumular	acumulòn	V;IND;PL;1;PRS;LGSPEC2
piantar	pianta	V;IMP;SG;3;LGSPEC1
spoxar	spoxava	V;IPFV;IND;SG;1;PST
łevar	łeva	V;IND;PL;3;PRS
acumular	acumulé	V;IMP;PL;2
vixitar	vixitarà	V;IND;SG;3;FUT
tugar	tugarìa	V;COND;SG;1
acetar	aceté	V;IND;PL;2;PRS
conpletar	conpletàsimo	V;IPFV;SBJV;PL;1;PST
bociar	bociarìa	V;COND;SG;3
vixitar	vixitasi	V;IPFV;SBJV;PL;2;PST
curar	curé	V;IND;PL;2;PRS
