brusler	brusle	V;SBJV;SG;1;PRS
estrangler	estrangleriez	V;COND;PL;2;LGSPEC1
voller	vollent	V;SBJV;PL;3;PRS
recorder	recordoit	V;IPFV;IND;SG;3;PST;LGSPEC1
tramper	tramperiez	V;COND;PL;2;LGSPEC1
rejecter	rejecter	V;NFIN
tyrer	tyriez	V;IPFV;IND;PL;2;PST;LGSPEC1
estudier	estudioyent	V;IPFV;IND;PL;3;PST;LGSPEC2
mocquer	mocquera	V;IND;SG;3;FUT
desplacer	desplaçois	V;IPFV;IND;SG;1;PST;LGSPEC1
ruyner	ruynez	V;IND;PL;2;PRS
vuider	vuiderions	V;COND;PL;1;LGSPEC1
despouiller	despouilleroys	V;COND;SG;1;LGSPEC2
confesser	confesseroys	V;COND;SG;2;LGSPEC2
descourager	descouragerions	V;COND;PL;1;LGSPEC1
desmonter	desmontions	V;IPFV;IND;PL;1;PST;LGSPEC1
esplucher	esplucheroit	V;COND;SG;3;LGSPEC1
armoier	armoiez	V;IND;PL;2;PRS
enpoisonner	enpoisonneryez	V;COND;PL;2;LGSPEC2
courouchier	courouchoient	V;IPFV;IND;PL;3;PST;LGSPEC1
renfler	renfleroys	V;COND;SG;2;LGSPEC2
tournoyer	tournoyeroyt	V;COND;SG;3;LGSPEC2
geller	gelleryons	V;COND;PL;1;LGSPEC2
appuier	appuiois	V;IPFV;IND;SG;1;PST;LGSPEC1
eriger	erigeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
assister	assister	V;NFIN
expuyser	expuysoys	V;IPFV;IND;SG;1;PST;LGSPEC2
chanter	chanteryez	V;COND;PL;2;LGSPEC2
praesenter	praesentez	V;IND;PL;2;PRS
retirer	retirons	V;SBJV;PL;1;PRS
celer	celeryez	V;COND;PL;2;LGSPEC2
retirer	retirassent	V;IPFV;SBJV;PL;3;PST
lyer	lyes	V;SBJV;SG;2;PRS
empenser	empensa	V;PFV;IND;SG;3;PST
espier	espierent	V;PFV;IND;PL;3;PST
empieger	empiegeryez	V;COND;PL;2;LGSPEC2
renger	rengent	V;IND;PL;3;PRS
protester	proteste	V;IND;SG;1;PRS
posseder	possederas	V;IND;SG;2;FUT
demesler	demesles	V;IND;SG;2;PRS
affier	affier	V;NFIN
desrober	desrobez	V;IMP;PL;2
assieger	assiegiez	V;IPFV;IND;PL;2;PST;LGSPEC1
rejecter	rejecteroit	V;COND;SG;3;LGSPEC1
rejecter	rejectons	V;IND;PL;1;PRS
herrier	herriez	V;IMP;PL;2
temprer	tempreroient	V;COND;PL;3;LGSPEC1
armoier	armoiez	V;SBJV;PL;2;PRS
espier	espieriez	V;COND;PL;2;LGSPEC1
escarter	escartoys	V;IPFV;IND;SG;2;PST;LGSPEC2
geller	gelleroyent	V;COND;PL;3;LGSPEC2
appareiller	appareillez	V;IMP;PL;2
devourer	devoureryez	V;COND;PL;2;LGSPEC2
preceder	precede	V;SBJV;SG;1;PRS
denunchier	denunchient	V;IND;PL;3;PRS
bancqueter	bancqueteroys	V;COND;SG;2;LGSPEC2
combiner	combineroient	V;COND;PL;3;LGSPEC1
preceder	precedez	V;SBJV;PL;2;PRS
melancholier	melancholieroit	V;COND;SG;3;LGSPEC1
posseder	possederent	V;PFV;IND;PL;3;PST
monstrer	monstreroys	V;COND;SG;1;LGSPEC2
esplucher	esplucheriez	V;COND;PL;2;LGSPEC1
saluer	saluerions	V;COND;PL;1;LGSPEC1
nommer	nomme	V;IND;SG;1;PRS
participer	participent	V;IND;PL;3;PRS
approuchier	approuchierions	V;COND;PL;1;LGSPEC1
persuader	persuaderent	V;PFV;IND;PL;3;PST
esparpiller	esparpilleroit	V;COND;SG;3;LGSPEC1
entrempescher	s'entrempescherent	V;PFV;IND;PL;3;PST
enferrer	enferrerois	V;COND;SG;2;LGSPEC1
songer	songeroient	V;COND;PL;3;LGSPEC1
enconcher	enconchez	V;SBJV;PL;2;PRS
edifier	edifiassiez	V;IPFV;SBJV;PL;2;PST
deifier	deifiez	V;IMP;PL;2
tumber	tumberai	V;IND;SG;1;FUT;LGSPEC1
esvertuer	esvertue	V;SBJV;SG;3;PRS
estinceller	estincellastes	V;PFV;IND;PL;2;PST
resigner	resignerons	V;IND;PL;1;FUT
jecter	jecterent	V;PFV;IND;PL;3;PST
entrempescher	entrempeschyons	V;IPFV;IND;PL;1;PST;LGSPEC2
esplucher	espluchasmes	V;PFV;IND;PL;1;PST
evaporer	evaporeroient	V;COND;PL;3;LGSPEC1
inviter	inviteroys	V;COND;SG;2;LGSPEC2
remonstrer	remonstre	V;SBJV;SG;3;PRS
entrempescher	vousentrempescheriez	V;COND;PL;2;LGSPEC1
quitter	quittyons	V;IPFV;IND;PL;1;PST;LGSPEC2
escrier	escrioit	V;IPFV;IND;SG;3;PST;LGSPEC1
mehaignier	mehaignent	V;IND;PL;3;PRS
delivrer	delivrent	V;SBJV;PL;3;PRS
esveigler	esveigloient	V;IPFV;IND;PL;3;PST;LGSPEC1
quereler	querelerons	V;IND;PL;1;FUT
affermer	affermeryons	V;COND;PL;1;LGSPEC2
esgaler	esgalastes	V;PFV;IND;PL;2;PST
oublyer	oublyassent	V;IPFV;SBJV;PL;3;PST
r'asseurer	r'asseureras	V;IND;SG;2;FUT
desplacer	desplacer	V;NFIN
desployer	desployoys	V;IPFV;IND;SG;2;PST;LGSPEC2
escapper	escappez	V;IND;PL;2;PRS
toucher	touches	V;IND;SG;2;PRS
garder	garderons	V;IND;PL;1;FUT
estrangler	estrangleroient	V;COND;PL;3;LGSPEC1
donner	donnassions	V;IPFV;SBJV;PL;1;PST
renouveller	renouvellasses	V;IPFV;SBJV;SG;2;PST
descourager	descourageriez	V;COND;PL;2;LGSPEC1
quereler	querelyez	V;IPFV;IND;PL;2;PST;LGSPEC2
detester	detestassiez	V;IPFV;SBJV;PL;2;PST
solliciter	solliciterez	V;IND;PL;2;FUT
estrangler	estrangler	V;NFIN
empirer	empirions	V;IPFV;IND;PL;1;PST;LGSPEC1
quitter	quitterons	V;IND;PL;1;FUT
esparpiller	esparpilloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
transporter	transporta	V;PFV;IND;SG;1;PST
asseurer	asseureryez	V;COND;PL;2;LGSPEC2
operer	operes	V;SBJV;SG;2;PRS
lyer	lye	V;SBJV;SG;3;PRS
empenser	empensoient	V;IPFV;IND;PL;3;PST;LGSPEC1
desplacer	desplacerions	V;COND;PL;1;LGSPEC1
voller	volle	V;IND;SG;1;PRS
exstirper	exstirpyez	V;IPFV;IND;PL;2;PST;LGSPEC2
ymaginer	ymaginerez	V;IND;PL;2;FUT
assieger	assiegerois	V;COND;SG;2;LGSPEC1
temprer	temprions	V;IPFV;IND;PL;1;PST;LGSPEC1
flechir	fleschissent	V;SBJV;PL;3;PRS
approuchier	approuchierois	V;COND;SG;2;LGSPEC1
redoubter	redoubteroient	V;COND;PL;3;LGSPEC1
escarter	escartoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
encontrer	encontras	V;PFV;IND;SG;2;PST
enhorter	enhortera	V;IND;SG;3;FUT
espier	espierions	V;COND;PL;1;LGSPEC1
proclamer	proclamons	V;IMP;PL;1
rejecter	rejectas	V;PFV;IND;SG;2;PST
mulcter	mulcterions	V;COND;PL;1;LGSPEC1
tocquer	tocqueroyt	V;COND;SG;3;LGSPEC2
esgarer	esgarerions	V;COND;PL;1;LGSPEC1
inviter	invitoit	V;IPFV;IND;SG;3;PST;LGSPEC1
presumer	presumerons	V;IND;PL;1;FUT
quereler	querelera	V;IND;SG;3;FUT
esmerveillier	esmerveillieroys	V;COND;SG;1;LGSPEC2
fascher	fascherent	V;PFV;IND;PL;3;PST
conquester	conquestiez	V;IPFV;IND;PL;2;PST;LGSPEC1
allaicter	allaicteray	V;IND;SG;1;FUT;LGSPEC2
pecher	pecheroys	V;COND;SG;1;LGSPEC2
detester	detestois	V;IPFV;IND;SG;1;PST;LGSPEC1
excuser	excusera	V;IND;SG;3;FUT
fumer	fumasses	V;IPFV;SBJV;SG;2;PST
ralier	ralias	V;PFV;IND;SG;2;PST
entrefrapper	s'entrefrapperont	V;IND;PL;3;FUT
retirer	retiryons	V;IPFV;IND;PL;1;PST;LGSPEC2
soumectre	soumenctent	V;SBJV;PL;3;PRS
soubhaitter	soubhaittent	V;IND;PL;3;PRS
occurrer	occurrions	V;IPFV;IND;PL;1;PST;LGSPEC1
occuper	occupent	V;IND;PL;3;PRS
renger	rengeriez	V;COND;PL;2;LGSPEC1
rouller	roullons	V;IMP;PL;1
quester	questons	V;SBJV;PL;1;PRS
assister	assista	V;PFV;IND;SG;1;PST
blasphemer	blasphemast	V;IPFV;SBJV;SG;3;PST
arrester	arresteroient	V;COND;PL;3;LGSPEC1
leicher	leicherois	V;COND;SG;2;LGSPEC1
armoier	armoiera	V;IND;SG;3;FUT
celer	celerons	V;IND;PL;1;FUT
renger	rengerois	V;COND;SG;2;LGSPEC1
suffocquer	suffocquent	V;IND;PL;3;PRS
essayer	essayeront	V;IND;PL;3;FUT
prier	prie	V;SBJV;SG;3;PRS
occurrer	occurroys	V;IPFV;IND;SG;2;PST;LGSPEC2
regorger	regorgeoys	V;IPFV;IND;SG;1;PST;LGSPEC2
affier	affieryons	V;COND;PL;1;LGSPEC2
adviser	advise	V;IMP;SG;2
estimer	estimoys	V;IPFV;IND;SG;2;PST;LGSPEC2
provocquer	provocquerions	V;COND;PL;1;LGSPEC1
preceder	precederois	V;COND;SG;1;LGSPEC1
abandonner	abandonnoient	V;IPFV;IND;PL;3;PST;LGSPEC1
mectre	mets	V;IND;SG;1;PRS
seiourner	seiourne	V;SBJV;SG;3;PRS
accorder	accorderois	V;COND;SG;2;LGSPEC1
cabasser	cabasses	V;IND;SG;2;PRS
iouer	iouassiez	V;IPFV;SBJV;PL;2;PST
tyrer	tyrasses	V;IPFV;SBJV;SG;2;PST
presumer	presume	V;IND;SG;3;PRS
empenser	empenseryons	V;COND;PL;1;LGSPEC2
effreer	effreerons	V;IND;PL;1;FUT
evaporer	evaporeroit	V;COND;SG;3;LGSPEC1
escarter	escartasses	V;IPFV;SBJV;SG;2;PST
quereler	querelerois	V;COND;SG;1;LGSPEC1
embausmer	embausmeront	V;IND;PL;3;FUT
mehaignier	mehaignois	V;IPFV;IND;SG;2;PST;LGSPEC1
ralier	ralieryez	V;COND;PL;2;LGSPEC2
declairer	declaira	V;PFV;IND;SG;1;PST
enyvrer	enyvreroyent	V;COND;PL;3;LGSPEC2
empieger	empiegeront	V;IND;PL;3;FUT
empenser	empenseroys	V;COND;SG;2;LGSPEC2
blasphemer	blasphemiez	V;IPFV;IND;PL;2;PST;LGSPEC1
acoustrer	acoustreray	V;IND;SG;1;FUT;LGSPEC2
desrouter	desrouteroys	V;COND;SG;2;LGSPEC2
affier	affiiez	V;IPFV;IND;PL;2;PST;LGSPEC1
regratier	regratioit	V;IPFV;IND;SG;3;PST;LGSPEC1
redoubter	redoubte	V;IND;SG;1;PRS
desplacer	desplaçoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
finer	finois	V;IPFV;IND;SG;1;PST;LGSPEC1
reietter	reietterent	V;PFV;IND;PL;3;PST
ruyner	ruynerois	V;COND;SG;2;LGSPEC1
nommer	nomme	V;SBJV;SG;3;PRS
esclairer	esclairasses	V;IPFV;SBJV;SG;2;PST
desver	desvyez	V;IPFV;IND;PL;2;PST;LGSPEC2
condescendre	condescendissoiz	V;IPFV;SBJV;PL;2;PST;LGSPEC1
repraesenter	repraesenterois	V;COND;SG;1;LGSPEC1
esquacher	esquachent	V;SBJV;PL;3;PRS
coniurer	coniurera	V;IND;SG;3;FUT
cercher	cercheroyt	V;COND;SG;3;LGSPEC2
quitter	quitterez	V;IND;PL;2;FUT
encontrer	encontrera	V;IND;SG;3;FUT
desheriter	desheriter	V;NFIN
fumer	fumes	V;IND;SG;2;PRS
leicher	leichent	V;IND;PL;3;PRS
monstrer	monstrions	V;IPFV;IND;PL;1;PST;LGSPEC1
accuser	accuseray	V;IND;SG;1;FUT;LGSPEC2
regratier	regratias	V;PFV;IND;SG;2;PST
enyvrer	enyvrerez	V;IND;PL;2;FUT
soumectre	soumectroye	V;IND;SG;1;FUT;LGSPEC2
mulcter	mulctasmes	V;PFV;IND;PL;1;PST
tumber	tumberoyent	V;COND;PL;3;LGSPEC2
regorger	regorge	V;IND;SG;1;PRS
evaporer	evaporons	V;IND;PL;1;PRS
embausmer	embausmions	V;IPFV;IND;PL;1;PST;LGSPEC1
affier	affions	V;IMP;PL;1
appareiller	appareilles	V;IND;SG;2;PRS
essayer	essaye	V;IND;SG;1;PRS
fouragier	fourageastes	V;PFV;IND;PL;2;PST
praesenter	praesentions	V;IPFV;IND;PL;1;PST;LGSPEC1
doubter	doubtoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
tumber	tumberont	V;IND;PL;3;FUT
tyrer	tyras	V;PFV;IND;SG;2;PST
demesler	demeslez	V;SBJV;PL;2;PRS
tocquer	tocquast	V;IPFV;SBJV;SG;3;PST
iniurier	iniurieras	V;IND;SG;2;FUT
leicher	leichoient	V;IPFV;IND;PL;3;PST;LGSPEC1
escarter	escarteras	V;IND;SG;2;FUT
r'asseurer	r'asseurerent	V;PFV;IND;PL;3;PST
desguiser	desguiseroyent	V;COND;PL;3;LGSPEC2
esclairer	esclairerons	V;IND;PL;1;FUT
renouveller	renouvella	V;PFV;IND;SG;1;PST
celer	celasses	V;IPFV;SBJV;SG;2;PST
demesler	demeslasse	V;IPFV;SBJV;SG;1;PST
pecher	pechyez	V;IPFV;IND;PL;2;PST;LGSPEC2
operer	opere	V;IMP;SG;2
iecter	iecteroit	V;COND;SG;3;LGSPEC1
iniurier	iniuriast	V;IPFV;SBJV;SG;3;PST
approuchier	approuchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
descourager	descouragea	V;PFV;IND;SG;1;PST
renger	rengez	V;IND;PL;2;PRS
honnourer	honnoureroyent	V;COND;PL;3;LGSPEC2
soucyer	soucyyez	V;IPFV;IND;PL;2;PST;LGSPEC2
regorger	regorgea	V;PFV;IND;SG;1;PST
esgarer	esgarerons	V;IND;PL;1;FUT
penetrer	penetras	V;PFV;IND;SG;2;PST
regretter	regretteray	V;IND;SG;1;FUT;LGSPEC2
charger	chargeasse	V;IPFV;SBJV;SG;1;PST
pausmer	pausmoys	V;IPFV;IND;SG;1;PST;LGSPEC2
occurrer	occurrez	V;IND;PL;2;PRS
escapper	escapperoit	V;COND;SG;3;LGSPEC1
esgaler	esgalassions	V;IPFV;SBJV;PL;1;PST
dilater	dilateroys	V;COND;SG;2;LGSPEC2
apuyer	apuyez	V;IND;PL;2;PRS
empirer	empiryez	V;IPFV;IND;PL;2;PST;LGSPEC2
eslancer	eslanciez	V;IPFV;IND;PL;2;PST;LGSPEC1
eschauffer	eschauffes	V;IND;SG;2;PRS
eschauffer	eschauffassions	V;IPFV;SBJV;PL;1;PST
protester	protestois	V;IPFV;IND;SG;2;PST;LGSPEC1
accuser	accusoys	V;IPFV;IND;SG;1;PST;LGSPEC2
affier	affiions	V;IPFV;IND;PL;1;PST;LGSPEC1
iniurier	iniurier	V;NFIN
apuyer	apuyent	V;SBJV;PL;3;PRS
encontrer	encontreroys	V;COND;SG;1;LGSPEC2
chercher	chercherons	V;IND;PL;1;FUT
trembler	trembleryons	V;COND;PL;1;LGSPEC2
demonstrer	demonstreroit	V;COND;SG;3;LGSPEC1
escouiller	escouillast	V;IPFV;SBJV;SG;3;PST
ployer	ployez	V;IND;PL;2;PRS
denunchier	denunchieryez	V;COND;PL;2;LGSPEC2
entrempescher	entrempeschez vous	V;IMP;PL;2
uriner	urineroient	V;COND;PL;3;LGSPEC1
uriner	urine	V;IND;SG;3;PRS
desmonter	desmonter	V;NFIN
honnourer	honnoureroyt	V;COND;SG;3;LGSPEC2
aguyser	aguysions	V;IPFV;IND;PL;1;PST;LGSPEC1
quereler	querelons	V;IND;PL;1;PRS
quitter	quitteroyent	V;COND;PL;3;LGSPEC2
asseurer	asseurasses	V;IPFV;SBJV;SG;2;PST
saluer	saluer	V;NFIN
penser	pensois	V;IPFV;IND;SG;1;PST;LGSPEC1
depescher	depeschassent	V;IPFV;SBJV;PL;3;PST
empieger	empiegea	V;PFV;IND;SG;3;PST
mectre	mectons	V;IND;PL;1;PRS
enferrer	enferreriez	V;COND;PL;2;LGSPEC1
esveigler	esveiglons	V;IND;PL;1;PRS
eslancer	eslançoys	V;IPFV;IND;SG;2;PST;LGSPEC2
ottroyer	ottroyeray	V;IND;SG;1;FUT;LGSPEC2
soubhaitter	soubhaitteroys	V;COND;SG;2;LGSPEC2
mettre	mets	V;IND;SG;2;PRS
abayer	abayes	V;IND;SG;2;PRS
esmerveillier	esmerveilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
gaigner	gaignyez	V;IPFV;IND;PL;2;PST;LGSPEC2
garder	gardez	V;IND;PL;2;PRS
despencer	despençasse	V;IPFV;SBJV;SG;1;PST
mascher	masche	V;IND;SG;1;PRS
renouveller	renouvellons	V;IMP;PL;1
condescendre	condescendent	V;SBJV;PL;3;PRS
provocquer	provocquons	V;IMP;PL;1
acquiter	acquiteroyent	V;COND;PL;3;LGSPEC2
avanchier	avanchiez	V;SBJV;PL;2;PRS
preceder	precederas	V;IND;SG;2;FUT
retirer	retireroient	V;COND;PL;3;LGSPEC1
allaicter	allaictons	V;IMP;PL;1
charger	chargeroient	V;COND;PL;3;LGSPEC1
soulaiger	soulaigent	V;SBJV;PL;3;PRS
presumer	presumasses	V;IPFV;SBJV;SG;2;PST
mucer	muceroys	V;COND;SG;2;LGSPEC2
fumer	fumerois	V;COND;SG;2;LGSPEC1
poiser	poiseroys	V;COND;SG;2;LGSPEC2
temprer	tempreriez	V;COND;PL;2;LGSPEC1
courouchier	courouchoit	V;IPFV;IND;SG;3;PST;LGSPEC1
deslacer	delacez	V;SBJV;PL;2;PRS
eschauffer	eschaufferoys	V;COND;SG;2;LGSPEC2
soucyer	soucyas	V;PFV;IND;SG;2;PST
encontrer	encontriez	V;IPFV;IND;PL;2;PST;LGSPEC1
desirer	desirois	V;IPFV;IND;SG;1;PST;LGSPEC1
executer	executeriez	V;COND;PL;2;LGSPEC1
bancqueter	bancquetasse	V;IPFV;SBJV;SG;1;PST
desirer	desiras	V;PFV;IND;SG;2;PST
esplucher	espluchez	V;IMP;PL;2
regratier	regratiez	V;IMP;PL;2
rouller	roullez	V;IND;PL;2;PRS
mocquer	mocquerois	V;COND;SG;1;LGSPEC1
bayser	bayser	V;NFIN
ruyner	ruyner	V;NFIN
conquester	conquestassions	V;IPFV;SBJV;PL;1;PST
leicher	leicherez	V;IND;PL;2;FUT
estouffer	estoufferyons	V;COND;PL;1;LGSPEC2
contreroller	contrerollasse	V;IPFV;SBJV;SG;1;PST
demesler	demesle	V;IMP;SG;2
jecter	jecteroit	V;COND;SG;3;LGSPEC1
combiner	combineroyt	V;COND;SG;3;LGSPEC2
executer	executerent	V;PFV;IND;PL;3;PST
consyderer	consyderassions	V;IPFV;SBJV;PL;1;PST
creancer	creanceroys	V;COND;SG;2;LGSPEC2
embler	embleriez	V;COND;PL;2;LGSPEC1
jecter	jectassent	V;IPFV;SBJV;PL;3;PST
cesser	cessons	V;IND;PL;1;PRS
entrefaire	entreferoyent	V;COND;PL;3;LGSPEC2
jecter	jectyez	V;IPFV;IND;PL;2;PST;LGSPEC2
courroucer	courrouçons	V;IPFV;IND;PL;1;PST;LGSPEC2
subiuger	subiugeassent	V;IPFV;SBJV;PL;3;PST
compter	compter	V;NFIN
geller	gelloys	V;IPFV;IND;SG;1;PST;LGSPEC2
soupper	soupperoyt	V;COND;SG;3;LGSPEC2
songer	songez	V;SBJV;PL;2;PRS
marcher	marcheroys	V;COND;SG;2;LGSPEC2
entrempescher	s'entrempeschent	V;SBJV;PL;3;PRS
eschauffer	eschauffons	V;IND;PL;1;PRS
approuchier	approuchois	V;IPFV;IND;SG;1;PST;LGSPEC1
affamer	affamerions	V;COND;PL;1;LGSPEC1
appareiller	appareillerent	V;PFV;IND;PL;3;PST
marcher	marcheroyent	V;COND;PL;3;LGSPEC2
poiser	poiseroys	V;COND;SG;1;LGSPEC2
tournoyer	tournoyeroit	V;COND;SG;3;LGSPEC1
rouller	roulle	V;IND;SG;1;PRS
temprer	temproys	V;IPFV;IND;SG;2;PST;LGSPEC2
enchargier	enchargieroit	V;COND;SG;3;LGSPEC1
desplacer	desplaceryez	V;COND;PL;2;LGSPEC2
trancher	trancheroys	V;COND;SG;1;LGSPEC2
deshonnourer	deshonnourasses	V;IPFV;SBJV;SG;2;PST
apatir	apatit	V;IND;SG;3;PRS
resider	reside	V;IMP;SG;2
desrouter	desrouterions	V;COND;PL;1;LGSPEC1
appareiller	appareilleroit	V;COND;SG;3;LGSPEC1
nombrer	nombrer	V;NFIN
regratier	regratioys	V;IPFV;IND;SG;2;PST;LGSPEC2
desconseiller	desconseillas	V;PFV;IND;SG;2;PST
cesser	cesserois	V;COND;SG;1;LGSPEC1
armoier	armoie	V;IND;SG;1;PRS
eschever	eschevent	V;IND;PL;3;PRS
veigler	veiglerions	V;COND;PL;1;LGSPEC1
desrouter	desroutassiez	V;IPFV;SBJV;PL;2;PST
jecter	jectois	V;IPFV;IND;SG;2;PST;LGSPEC1
chercher	cherche	V;SBJV;SG;1;PRS
redoubter	redoubteryons	V;COND;PL;1;LGSPEC2
vuider	vuideroys	V;COND;SG;1;LGSPEC2
soubhaitter	soubhaitteront	V;IND;PL;3;FUT
regorger	regorgeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
escouiller	escouillerai	V;IND;SG;1;FUT;LGSPEC1
raenchonner	raenchonne	V;IMP;SG;2
mulcter	mulctent	V;IND;PL;3;PRS
desmonter	desmonte	V;SBJV;SG;3;PRS
bancqueter	bancquetoys	V;IPFV;IND;SG;1;PST;LGSPEC2
desployer	desployeront	V;IND;PL;3;FUT
tyrer	tyreray	V;IND;SG;1;FUT;LGSPEC2
recorder	recordas	V;PFV;IND;SG;2;PST
ruyner	ruynons	V;IND;PL;1;PRS
eviter	evitons	V;SBJV;PL;1;PRS
bancqueter	bancquetez	V;SBJV;PL;2;PRS
ordonner	ordonnerons	V;IND;PL;1;FUT
r'asseurer	r'asseurasmes	V;PFV;IND;PL;1;PST
delivrer	delivreroient	V;COND;PL;3;LGSPEC1
asseurer	asseurerois	V;COND;SG;2;LGSPEC1
denunchier	denunchie	V;SBJV;SG;3;PRS
disner	disneroit	V;COND;SG;3;LGSPEC1
esguiser	esguiserions	V;COND;PL;1;LGSPEC1
fluir	fluis	V;IND;SG;1;PRS
mehaignier	mehaignoient	V;IPFV;IND;PL;3;PST;LGSPEC1
chercher	cherchast	V;IPFV;SBJV;SG;3;PST
occurrer	occurrerois	V;COND;SG;2;LGSPEC1
arrester	arrestasses	V;IPFV;SBJV;SG;2;PST
voller	volle	V;SBJV;SG;3;PRS
estouffer	estoufferai	V;IND;SG;1;FUT;LGSPEC1
tumber	tumberoient	V;COND;PL;3;LGSPEC1
poiser	poiseroyent	V;COND;PL;3;LGSPEC2
r'asseurer	r'asseurois	V;IPFV;IND;SG;1;PST;LGSPEC1
appareiller	appareilleroys	V;COND;SG;2;LGSPEC2
escouiller	escouilla	V;PFV;IND;SG;1;PST
esperer	esperasse	V;IPFV;SBJV;SG;1;PST
assieger	assiegeons	V;SBJV;PL;1;PRS
quester	questeriez	V;COND;PL;2;LGSPEC1
expuyser	expuysez	V;IND;PL;2;PRS
renouveller	renouvellois	V;IPFV;IND;SG;2;PST;LGSPEC1
enconvenencier	enconvenençoit	V;IPFV;IND;SG;3;PST;LGSPEC1
remonstrer	remonstrasses	V;IPFV;SBJV;SG;2;PST
iniurier	iniuries	V;SBJV;SG;2;PRS
denunchier	denunchierois	V;COND;SG;1;LGSPEC1
disner	disnois	V;IPFV;IND;SG;1;PST;LGSPEC1
occuper	occuperions	V;COND;PL;1;LGSPEC1
esventer	esventeryez	V;COND;PL;2;LGSPEC2
embausmer	embausmiez	V;IPFV;IND;PL;2;PST;LGSPEC1
nombrer	nombrassent	V;IPFV;SBJV;PL;3;PST
fluir	fluissiez	V;IPFV;SBJV;PL;2;PST
essilier	essiloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
soingner	soingnasses	V;IPFV;SBJV;SG;2;PST
mulcter	mulctastes	V;PFV;IND;PL;2;PST
alterer	altera	V;PFV;IND;SG;1;PST
presumer	presumons	V;SBJV;PL;1;PRS
protester	protestons	V;IND;PL;1;PRS
excuser	excuser	V;NFIN
assister	assisteryons	V;COND;PL;1;LGSPEC2
escarter	escarteroient	V;COND;PL;3;LGSPEC1
desrober	desroberez	V;IND;PL;2;FUT
affier	affierai	V;IND;SG;1;FUT;LGSPEC1
ruyner	ruynoient	V;IPFV;IND;PL;3;PST;LGSPEC1
retirer	retireryez	V;COND;PL;2;LGSPEC2
accuser	accuse	V;IMP;SG;2
coniurer	coniurasse	V;IPFV;SBJV;SG;1;PST
confesser	confessions	V;IPFV;IND;PL;1;PST;LGSPEC1
escapper	escapperoyt	V;COND;SG;3;LGSPEC2
enyvrer	enyvrons	V;IND;PL;1;PRS
herrier	herrierent	V;PFV;IND;PL;3;PST
translater	translata	V;PFV;IND;SG;1;PST
iniurier	iniurierois	V;COND;SG;2;LGSPEC1
allaicter	allaicteroyent	V;COND;PL;3;LGSPEC2
nommer	nommeray	V;IND;SG;1;FUT;LGSPEC2
fromenter	fromente	V;IND;SG;1;PRS
essilier	essiloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
accuser	accuserons	V;IND;PL;1;FUT
monstrer	monstrer	V;NFIN
rouller	roulleroit	V;COND;SG;3;LGSPEC1
consyderer	consydereroyt	V;COND;SG;3;LGSPEC2
bayser	baysera	V;IND;SG;3;FUT
translater	translate	V;SBJV;SG;1;PRS
solliciter	sollicite	V;IND;SG;3;PRS
desbarater	desbaratoys	V;IPFV;IND;SG;2;PST;LGSPEC2
mercyer	mercye	V;IND;SG;3;PRS
quester	questas	V;PFV;IND;SG;2;PST
iouer	ioueroient	V;COND;PL;3;LGSPEC1
lyer	lyoys	V;IPFV;IND;SG;1;PST;LGSPEC2
iolyer	iolyez	V;IND;PL;2;PRS
empescher	empeschoys	V;IPFV;IND;SG;2;PST;LGSPEC2
lyer	lyez	V;IMP;PL;2
chercher	cherchassiez	V;IPFV;SBJV;PL;2;PST
translater	translate	V;IND;SG;3;PRS
pecher	pechas	V;PFV;IND;SG;2;PST
courouchier	courouchieryez	V;COND;PL;2;LGSPEC2
devourer	devourasse	V;IPFV;SBJV;SG;1;PST
embausmer	embausmas	V;PFV;IND;SG;2;PST
entrehurter	nous entrehurtasmes	V;PFV;IND;PL;1;PST
inquieter	inquieteryez	V;COND;PL;2;LGSPEC2
seiourner	seiournasmes	V;PFV;IND;PL;1;PST
armoier	armoiois	V;IPFV;IND;SG;1;PST;LGSPEC1
poiser	poisons	V;IMP;PL;1
obliger	obligeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
honnourer	honnourerez	V;IND;PL;2;FUT
conquester	conquesteroient	V;COND;PL;3;LGSPEC1
acquiter	acquiteriez	V;COND;PL;2;LGSPEC1
arrester	arrestas	V;PFV;IND;SG;2;PST
doubter	doubterez	V;IND;PL;2;FUT
desadvouer	desadvoua	V;PFV;IND;SG;1;PST
fomenter	fomentois	V;IPFV;IND;SG;1;PST;LGSPEC1
mocquer	mocqua	V;PFV;IND;SG;3;PST
monstrer	monstroit	V;IPFV;IND;SG;3;PST;LGSPEC1
subiuger	subiugera	V;IND;SG;3;FUT
marcher	marchons	V;IMP;PL;1
esplucher	espluchast	V;IPFV;SBJV;SG;3;PST
celer	cela	V;PFV;IND;SG;3;PST
desconseiller	desconseilla	V;PFV;IND;SG;3;PST
ordonner	ordonnyez	V;IPFV;IND;PL;2;PST;LGSPEC2
dilater	dilatoys	V;IPFV;IND;SG;2;PST;LGSPEC2
entredemander	nous entredemandons	V;SBJV;PL;1;PRS
tournoyer	tournoyeryez	V;COND;PL;2;LGSPEC2
affamer	affamerent	V;PFV;IND;PL;3;PST
effreer	effreoys	V;IPFV;IND;SG;1;PST;LGSPEC2
esventer	esventerois	V;COND;SG;2;LGSPEC1
iolyer	iolyerai	V;IND;SG;1;FUT;LGSPEC1
desguiser	desguisa	V;PFV;IND;SG;3;PST
esprouver	esprouvera	V;IND;SG;3;FUT
desheriter	desheritions	V;IPFV;IND;PL;1;PST;LGSPEC1
mercyer	mercyes	V;SBJV;SG;2;PRS
desployer	desployerois	V;COND;SG;2;LGSPEC1
fromenter	fromentiez	V;IPFV;IND;PL;2;PST;LGSPEC1
contreroller	contrerolleras	V;IND;SG;2;FUT
pryer	pryasse	V;IPFV;SBJV;SG;1;PST
praesenter	praesenterois	V;COND;SG;2;LGSPEC1
adiouster	adioustes	V;IND;SG;2;PRS
aymer	aymer	V;NFIN
desyrer	desyroient	V;IPFV;IND;PL;3;PST;LGSPEC1
huer	huerez	V;IND;PL;2;FUT
estimer	estima	V;PFV;IND;SG;1;PST
eschauffer	eschauffoient	V;IPFV;IND;PL;3;PST;LGSPEC1
enconcher	enconcheras	V;IND;SG;2;FUT
operer	operoient	V;IPFV;IND;PL;3;PST;LGSPEC1
praesenter	praesentent	V;IND;PL;3;PRS
trembler	tremblions	V;IPFV;IND;PL;1;PST;LGSPEC1
desancrer	desancreriez	V;COND;PL;2;LGSPEC1
prattiquer	prattiqueryez	V;COND;PL;2;LGSPEC2
doubter	doubtas	V;PFV;IND;SG;2;PST
declairer	declairons	V;IND;PL;1;PRS
estudier	estudia	V;PFV;IND;SG;3;PST
esgarer	esgareras	V;IND;SG;2;FUT
fromenter	fromentasse	V;IPFV;SBJV;SG;1;PST
marcher	marcheryons	V;COND;PL;1;LGSPEC2
uriner	urinas	V;PFV;IND;SG;2;PST
veigler	veiglent	V;SBJV;PL;3;PRS
effreer	effreez	V;IMP;PL;2
trembler	trembleroys	V;COND;SG;1;LGSPEC2
contreroller	contrerollassions	V;IPFV;SBJV;PL;1;PST
recorder	recorderont	V;IND;PL;3;FUT
demesler	demeslerent	V;PFV;IND;PL;3;PST
desregler	desreglent	V;SBJV;PL;3;PRS
seiourner	seiournoient	V;IPFV;IND;PL;3;PST;LGSPEC1
temprer	temproient	V;IPFV;IND;PL;3;PST;LGSPEC1
escumer	escumiez	V;IPFV;IND;PL;2;PST;LGSPEC1
aracher	arachassions	V;IPFV;SBJV;PL;1;PST
penetrer	penetrent	V;SBJV;PL;3;PRS
embausmer	embausment	V;SBJV;PL;3;PRS
esclairer	esclairoient	V;IPFV;IND;PL;3;PST;LGSPEC1
songer	songeassiez	V;IPFV;SBJV;PL;2;PST
pryer	prye	V;SBJV;SG;1;PRS
iouer	ioue	V;SBJV;SG;1;PRS
separer	separasmes	V;PFV;IND;PL;1;PST
ralier	ralieray	V;IND;SG;1;FUT;LGSPEC2
desinfecter	desinfectois	V;IPFV;IND;SG;1;PST;LGSPEC1
finer	finassiez	V;IPFV;SBJV;PL;2;PST
effreer	effreiez	V;IPFV;IND;PL;2;PST;LGSPEC1
desbarater	desbaratois	V;IPFV;IND;SG;1;PST;LGSPEC1
nombrer	nombrions	V;IPFV;IND;PL;1;PST;LGSPEC1
adviser	advisasse	V;IPFV;SBJV;SG;1;PST
pryer	pryent	V;SBJV;PL;3;PRS
logier	logeasse	V;IPFV;SBJV;SG;1;PST
depescher	depesche	V;IND;SG;3;PRS
combiner	combinasmes	V;PFV;IND;PL;1;PST
esprouver	esprouverions	V;COND;PL;1;LGSPEC1
celer	celes	V;SBJV;SG;2;PRS
estinceller	estincellassent	V;IPFV;SBJV;PL;3;PST
desadvouer	desadvouyez	V;IPFV;IND;PL;2;PST;LGSPEC2
soucyer	soucyer	V;NFIN
desgorger	desgorgeons	V;IMP;PL;1
resigner	resignois	V;IPFV;IND;SG;2;PST;LGSPEC1
brusler	bruslera	V;IND;SG;3;FUT
tramper	trampoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
fumer	fumez	V;SBJV;PL;2;PRS
arroier	arroiez	V;IMP;PL;2
escrier	escriassiez	V;IPFV;SBJV;PL;2;PST
affier	affiera	V;IND;SG;3;FUT
ruyner	ruyneray	V;IND;SG;1;FUT;LGSPEC2
desrober	desrobons	V;IMP;PL;1
nombrer	nombrez	V;IND;PL;2;PRS
fromenter	fromenteras	V;IND;SG;2;FUT
pausmer	pausma	V;PFV;IND;SG;3;PST
songer	songiez	V;IPFV;IND;PL;2;PST;LGSPEC1
donner	donnassent	V;IPFV;SBJV;PL;3;PST
posseder	possedes	V;IND;SG;2;PRS
aymer	aymez	V;SBJV;PL;2;PRS
fluir	fluirois	V;COND;SG;1;LGSPEC1
delaisser	delaissoys	V;IPFV;IND;SG;2;PST;LGSPEC2
enconvenencier	enconvenençois	V;IPFV;IND;SG;1;PST;LGSPEC1
escarter	escarter	V;NFIN
redoubter	redoubtes	V;IND;SG;2;PRS
doubter	doubtions	V;IPFV;IND;PL;1;PST;LGSPEC1
combiner	combiner	V;NFIN
executer	executions	V;IPFV;IND;PL;1;PST;LGSPEC1
fluir	fluiroit	V;COND;SG;3;LGSPEC1
plaider	plaidoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
enyvrer	enyvrasses	V;IPFV;SBJV;SG;2;PST
combiner	combinoit	V;IPFV;IND;SG;3;PST;LGSPEC1
toucher	touchasses	V;IPFV;SBJV;SG;2;PST
pausmer	pausmyez	V;IPFV;IND;PL;2;PST;LGSPEC2
ottroyer	ottroyasses	V;IPFV;SBJV;SG;2;PST
escouiller	escouilloys	V;IPFV;IND;SG;2;PST;LGSPEC2
huer	huerons	V;IND;PL;1;FUT
demesler	demeslastes	V;PFV;IND;PL;2;PST
desprisonner	desprisonneroys	V;COND;SG;2;LGSPEC2
commencer	commença	V;PFV;IND;SG;3;PST
aracher	arachasses	V;IPFV;SBJV;SG;2;PST
abandonner	abandonnerois	V;COND;SG;1;LGSPEC1
donner	donnons	V;IMP;PL;1
accorder	accordoys	V;IPFV;IND;SG;1;PST;LGSPEC2
empirer	empira	V;PFV;IND;SG;3;PST
ordonner	ordonnoys	V;IPFV;IND;SG;1;PST;LGSPEC2
inquieter	inquietoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
deifier	deifiois	V;IPFV;IND;SG;1;PST;LGSPEC1
desadvouer	desadvoue	V;SBJV;SG;3;PRS
desprisonner	desprisonne	V;SBJV;SG;1;PRS
courouchier	courouchassiez	V;IPFV;SBJV;PL;2;PST
excuser	excuseront	V;IND;PL;3;FUT
assieger	assiegerez	V;IND;PL;2;FUT
nombrer	nombrois	V;IPFV;IND;SG;1;PST;LGSPEC1
quitter	quittoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
acoustrer	acoustres	V;SBJV;SG;2;PRS
despouiller	despouilleryez	V;COND;PL;2;LGSPEC2
desployer	desploye	V;SBJV;SG;1;PRS
esplucher	espluchois	V;IPFV;IND;SG;1;PST;LGSPEC1
cabasser	cabassois	V;IPFV;IND;SG;2;PST;LGSPEC1
entrefrapper	entrefrappons nous	V;IMP;PL;1
tocquer	tocquerez	V;IND;PL;2;FUT
embler	embloient	V;IPFV;IND;PL;3;PST;LGSPEC1
enorter	enorteroyt	V;COND;SG;3;LGSPEC2
empescher	empescheroit	V;COND;SG;3;LGSPEC1
esperer	esperoys	V;IPFV;IND;SG;2;PST;LGSPEC2
recuperer	recupera	V;PFV;IND;SG;1;PST
reverer	reveroys	V;IPFV;IND;SG;1;PST;LGSPEC2
ordonner	ordonnerois	V;COND;SG;1;LGSPEC1
reverer	reveres	V;SBJV;SG;2;PRS
veigler	veigleras	V;IND;SG;2;FUT
arroier	arroierons	V;IND;PL;1;FUT
estimer	estimeryez	V;COND;PL;2;LGSPEC2
tocquer	tocquons	V;IMP;PL;1
atourner	atournent	V;SBJV;PL;3;PRS
monstrer	monstrez	V;SBJV;PL;2;PRS
descouchier	descouchieryez	V;COND;PL;2;LGSPEC2
aracher	aracherois	V;COND;SG;1;LGSPEC1
estouffer	estouffois	V;IPFV;IND;SG;1;PST;LGSPEC1
descouchier	descouches	V;IND;SG;2;PRS
creancer	creanceroys	V;COND;SG;1;LGSPEC2
ralier	ralions	V;SBJV;PL;1;PRS
desfaire	desfaisoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
desconseiller	desconseille	V;IND;SG;1;PRS
estudier	estudieryons	V;COND;PL;1;LGSPEC2
compter	compteroient	V;COND;PL;3;LGSPEC1
marcher	marcha	V;PFV;IND;SG;3;PST
provocquer	provocquerai	V;IND;SG;1;FUT;LGSPEC1
pausmer	pausmons	V;IND;PL;1;PRS
operer	operez	V;IMP;PL;2
combiner	combineront	V;IND;PL;3;FUT
logier	logeassions	V;IPFV;SBJV;PL;1;PST
descourager	descourageroyt	V;COND;SG;3;LGSPEC2
embausmer	embausmast	V;IPFV;SBJV;SG;3;PST
charger	chargeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
tyrer	tyre	V;IND;SG;1;PRS
baster	bastois	V;IPFV;IND;SG;1;PST;LGSPEC1
trembler	trembloys	V;IPFV;IND;SG;2;PST;LGSPEC2
desirer	desiroient	V;IPFV;IND;PL;3;PST;LGSPEC1
picquer	picqua	V;PFV;IND;SG;3;PST
desfaire	desfisse	V;IPFV;SBJV;SG;1;PST
desirer	desireroient	V;COND;PL;3;LGSPEC1
charger	chargerent	V;PFV;IND;PL;3;PST
tremper	trempas	V;PFV;IND;SG;2;PST
enpoisonner	enpoisonne	V;SBJV;SG;1;PRS
tumber	tumboys	V;IPFV;IND;SG;1;PST;LGSPEC2
separer	separeryez	V;COND;PL;2;LGSPEC2
alterer	altere	V;SBJV;SG;3;PRS
renger	rengiez	V;IPFV;IND;PL;2;PST;LGSPEC1
enpoisonner	enpoisonnent	V;IND;PL;3;PRS
ployer	ployerez	V;IND;PL;2;FUT
fouragier	fouragiera	V;IND;SG;3;FUT
fortiffier	fortiffiiez	V;IPFV;IND;PL;2;PST;LGSPEC1
herrier	herrierois	V;COND;SG;1;LGSPEC1
desgorger	desgorgerois	V;COND;SG;1;LGSPEC1
esparpiller	esparpillyons	V;IPFV;IND;PL;1;PST;LGSPEC2
bayser	bayseroient	V;COND;PL;3;LGSPEC1
mercyer	mercye	V;SBJV;SG;1;PRS
saluer	saluera	V;IND;SG;3;FUT
enconcher	enconchons	V;IND;PL;1;PRS
renouveller	renouvellas	V;PFV;IND;SG;2;PST
estudier	estudie	V;IMP;SG;2
desver	desveriez	V;COND;PL;2;LGSPEC1
regretter	regrettent	V;IND;PL;3;PRS
desprisonner	desprisonneras	V;IND;SG;2;FUT
lyer	lyasses	V;IPFV;SBJV;SG;2;PST
reietter	reiettes	V;IND;SG;2;PRS
enpoisonner	enpoisonnez	V;IMP;PL;2
retirer	retireront	V;IND;PL;3;FUT
temprer	tempres	V;SBJV;SG;2;PRS
aracher	arachent	V;IND;PL;3;PRS
garder	garde	V;IMP;SG;2
desheriter	desheritoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
affamer	affameryez	V;COND;PL;2;LGSPEC2
eschauffer	eschauffe	V;SBJV;SG;1;PRS
esveigler	esveiglez	V;SBJV;PL;2;PRS
denunchier	denunchioient	V;IPFV;IND;PL;3;PST;LGSPEC1
esmerveillier	esmerveillent	V;SBJV;PL;3;PRS
celer	celas	V;PFV;IND;SG;2;PST
enconcher	enconchoit	V;IPFV;IND;SG;3;PST;LGSPEC1
resider	residoys	V;IPFV;IND;SG;2;PST;LGSPEC2
cesser	cessas	V;PFV;IND;SG;2;PST
resver	resvasse	V;IPFV;SBJV;SG;1;PST
eslancer	eslança	V;PFV;IND;SG;1;PST
melancholier	melancholieray	V;IND;SG;1;FUT;LGSPEC2
exstirper	exstirperons	V;IND;PL;1;FUT
esprouver	esprouvons	V;SBJV;PL;1;PRS
condescendre	condescendeie	V;IPFV;IND;SG;1;PST;LGSPEC2
enconcher	enconchassiez	V;IPFV;SBJV;PL;2;PST
recuperer	recupererois	V;COND;SG;1;LGSPEC1
accepter	accepteroys	V;COND;SG;1;LGSPEC2
desconseiller	desconseille	V;SBJV;SG;1;PRS
tournoyer	tournoyons	V;IND;PL;1;PRS
avanchier	avanches	V;SBJV;SG;2;PRS
effreer	effreoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
soumectre	soumectrons	V;IND;PL;1;FUT
penetrer	penetrerois	V;COND;SG;2;LGSPEC1
escumer	escumoys	V;IPFV;IND;SG;1;PST;LGSPEC2
demesler	demesleroyt	V;COND;SG;3;LGSPEC2
ottroyer	ottroyast	V;IPFV;SBJV;SG;3;PST
eslancer	eslances	V;SBJV;SG;2;PRS
praesenter	praesentoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
compter	comptassent	V;IPFV;SBJV;PL;3;PST
entredemander	nous entredemandons	V;IND;PL;1;PRS
aerer	aere	V;SBJV;SG;1;PRS
accepter	acceptassiez	V;IPFV;SBJV;PL;2;PST
desirer	desirassiez	V;IPFV;SBJV;PL;2;PST
approuchier	approuche	V;IMP;SG;2
eschauffer	eschauffons	V;SBJV;PL;1;PRS
mucer	muçasse	V;IPFV;SBJV;SG;1;PST
regratier	regratiassent	V;IPFV;SBJV;PL;3;PST
retourner	retournas	V;PFV;IND;SG;2;PST
appareiller	appareillois	V;IPFV;IND;SG;1;PST;LGSPEC1
bayser	bayses	V;IND;SG;2;PRS
enconvenencier	enconvenencyez	V;IPFV;IND;PL;2;PST;LGSPEC2
lyer	lyons	V;IMP;PL;1
chercher	cherchas	V;PFV;IND;SG;2;PST
fortiffier	fortiffieroyt	V;COND;SG;3;LGSPEC2
accepter	acceptassions	V;IPFV;SBJV;PL;1;PST
gouverner	gouvernez	V;SBJV;PL;2;PRS
desrober	desrobassions	V;IPFV;SBJV;PL;1;PST
regretter	regrettions	V;IPFV;IND;PL;1;PST;LGSPEC1
mocquer	mocquassiez	V;IPFV;SBJV;PL;2;PST
avanchier	avanchasmes	V;PFV;IND;PL;1;PST
esguiser	esguiseriez	V;COND;PL;2;LGSPEC1
fluir	fluistes	V;PFV;IND;PL;2;PST
consyderer	consydere	V;SBJV;SG;1;PRS
accepter	accepteroit	V;COND;SG;3;LGSPEC1
desrouter	desrouteront	V;IND;PL;3;FUT
deifier	deifie	V;IND;SG;1;PRS
commencer	commençoys	V;IPFV;IND;SG;1;PST;LGSPEC2
demonstrer	demonstrasse	V;IPFV;SBJV;SG;1;PST
offencer	offenças	V;PFV;IND;SG;2;PST
asseurer	asseurera	V;IND;SG;3;FUT
atourner	atourneroyent	V;COND;PL;3;LGSPEC2
esmerveillier	esmerveillieroyent	V;COND;PL;3;LGSPEC2
entrempescher	entrempescheryons	V;COND;PL;1;LGSPEC2
resigner	resigniez	V;IPFV;IND;PL;2;PST;LGSPEC1
detester	detesteryez	V;COND;PL;2;LGSPEC2
executer	executent	V;IND;PL;3;PRS
fumer	fumez	V;IMP;PL;2
esgaler	esgalons	V;SBJV;PL;1;PRS
subiuger	subiugeoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
empenser	empensiez	V;IPFV;IND;PL;2;PST;LGSPEC1
r'asseurer	r'asseurerois	V;COND;SG;2;LGSPEC1
proclamer	proclament	V;SBJV;PL;3;PRS
prier	prierai	V;IND;SG;1;FUT;LGSPEC1
renfler	renfloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
assister	assistes	V;IND;SG;2;PRS
mocquer	mocquoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
repraesenter	repraesentez	V;SBJV;PL;2;PRS
pryer	pryoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
mehaignier	mehaignions	V;IMP;PL;1
avanchier	avancha	V;PFV;IND;SG;3;PST
confesser	confesseroyt	V;COND;SG;3;LGSPEC2
cesser	cessent	V;SBJV;PL;3;PRS
fascher	faschassions	V;IPFV;SBJV;PL;1;PST
desheriter	desheriteryons	V;COND;PL;1;LGSPEC2
temprer	tempriez	V;IPFV;IND;PL;2;PST;LGSPEC1
desployer	desployasses	V;IPFV;SBJV;SG;2;PST
enferrer	enferra	V;PFV;IND;SG;1;PST
arrester	arresteryons	V;COND;PL;1;LGSPEC2
entreruyner	nous entreruynasmes	V;PFV;IND;PL;1;PST
quitter	quitteroys	V;COND;SG;1;LGSPEC2
apuyer	apuyerois	V;COND;SG;1;LGSPEC1
deslacer	deslacer	V;NFIN
enconcher	enconcher	V;NFIN
conquester	conquesteriez	V;COND;PL;2;LGSPEC1
entrefaire	entrefaisoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
atourner	atournerai	V;IND;SG;1;FUT;LGSPEC1
alterer	altereroit	V;COND;SG;3;LGSPEC1
accorder	accorderoys	V;COND;SG;2;LGSPEC2
regratier	regratieriez	V;COND;PL;2;LGSPEC1
escarter	escarterent	V;PFV;IND;PL;3;PST
poiser	poisois	V;IPFV;IND;SG;2;PST;LGSPEC1
charger	chargeryons	V;COND;PL;1;LGSPEC2
desrouter	desrouterons	V;IND;PL;1;FUT
presenter	presentons	V;SBJV;PL;1;PRS
getter	gettez	V;IMP;PL;2
desirer	desire	V;IND;SG;1;PRS
enorter	enorteroyent	V;COND;PL;3;LGSPEC2
esvertuer	esvertuyez	V;IPFV;IND;PL;2;PST;LGSPEC2
retourner	retournasse	V;IPFV;SBJV;SG;1;PST
reverer	reverez	V;IMP;PL;2
tramper	trampes	V;SBJV;SG;2;PRS
pausmer	pausme	V;SBJV;SG;1;PRS
mulcter	mulcte	V;IND;SG;3;PRS
devourer	devourois	V;IPFV;IND;SG;1;PST;LGSPEC1
fouragier	fourage	V;SBJV;SG;3;PRS
courroucer	courrouceryons	V;COND;PL;1;LGSPEC2
pecher	pechent	V;SBJV;PL;3;PRS
donner	donnerons	V;IND;PL;1;FUT
adviser	adviserons	V;IND;PL;1;FUT
resider	resideroyt	V;COND;SG;3;LGSPEC2
estimer	estima	V;PFV;IND;SG;3;PST
estacher	estache	V;IND;SG;1;PRS
escouiller	escouillasmes	V;PFV;IND;PL;1;PST
ruyner	ruyne	V;SBJV;SG;3;PRS
remonstrer	remonstrera	V;IND;SG;3;FUT
excuser	excuse	V;IND;SG;3;PRS
quereler	querela	V;PFV;IND;SG;1;PST
voller	vollerois	V;COND;SG;1;LGSPEC1
r'asseurer	r'asseuryez	V;IPFV;IND;PL;2;PST;LGSPEC2
gouverner	gouvernerent	V;PFV;IND;PL;3;PST
diviner	divineroys	V;COND;SG;1;LGSPEC2
esperonner	esperonnoient	V;IPFV;IND;PL;3;PST;LGSPEC1
eviter	evitoient	V;IPFV;IND;PL;3;PST;LGSPEC1
declairer	declairois	V;IPFV;IND;SG;1;PST;LGSPEC1
raenchonner	raenchonnons	V;IMP;PL;1
trancher	tranche	V;IND;SG;1;PRS
adiouster	adioustasse	V;IPFV;SBJV;SG;1;PST
protester	protesterai	V;IND;SG;1;FUT;LGSPEC1
descourager	descourageons	V;IND;PL;1;PRS
combiner	combinerent	V;PFV;IND;PL;3;PST
regorger	regorgeoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
dilater	dilateryons	V;COND;PL;1;LGSPEC2
ralier	raliyons	V;IPFV;IND;PL;1;PST;LGSPEC2
descourager	descourageryons	V;COND;PL;1;LGSPEC2
contreroller	contrerollyez	V;IPFV;IND;PL;2;PST;LGSPEC2
subiuger	subiugeroys	V;COND;SG;1;LGSPEC2
ymaginer	ymaginerai	V;IND;SG;1;FUT;LGSPEC1
presumer	presumyez	V;IPFV;IND;PL;2;PST;LGSPEC2
saluer	salue	V;IMP;SG;2
tournoyer	tournoyent	V;IND;PL;3;PRS
enyvrer	enyvreriez	V;COND;PL;2;LGSPEC1
regorger	regorgeroit	V;COND;SG;3;LGSPEC1
fascher	faschasmes	V;PFV;IND;PL;1;PST
approuchier	approuchieriez	V;COND;PL;2;LGSPEC1
jecter	jectoys	V;IPFV;IND;SG;2;PST;LGSPEC2
descourager	descourages	V;IND;SG;2;PRS
eslancer	eslancerent	V;PFV;IND;PL;3;PST
affermer	affermoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
confesser	confesseryons	V;COND;PL;1;LGSPEC2
cabasser	cabasseroient	V;COND;PL;3;LGSPEC1
acquiter	acquita	V;PFV;IND;SG;1;PST
esclairer	esclaireroient	V;COND;PL;3;LGSPEC1
avanchier	avanchieroys	V;COND;SG;2;LGSPEC2
mehaignier	mehaigne	V;IMP;SG;2
consyderer	consyderassent	V;IPFV;SBJV;PL;3;PST
retyrer	retyres	V;SBJV;SG;2;PRS
repraesenter	repraesentasses	V;IPFV;SBJV;SG;2;PST
ymaginer	ymaginons	V;IND;PL;1;PRS
reietter	reietteray	V;IND;SG;1;FUT;LGSPEC2
abandonner	abandonnons	V;IND;PL;1;PRS
quereler	quereloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
tocquer	tocque	V;SBJV;SG;1;PRS
desprisonner	desprisonnasmes	V;PFV;IND;PL;1;PST
regorger	regorgeois	V;IPFV;IND;SG;1;PST;LGSPEC1
desgorger	desgorgeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
eschauffer	eschaufferyez	V;COND;PL;2;LGSPEC2
cabasser	cabasserois	V;COND;SG;2;LGSPEC1
expuyser	expuysassent	V;IPFV;SBJV;PL;3;PST
desployer	desployois	V;IPFV;IND;SG;1;PST;LGSPEC1
demonstrer	demonstrent	V;SBJV;PL;3;PRS
prier	priera	V;IND;SG;3;FUT
regretter	regrette	V;SBJV;SG;1;PRS
desirer	desirons	V;IMP;PL;1
aterminer	atermineroit	V;COND;SG;3;LGSPEC1
consyderer	consyderons	V;SBJV;PL;1;PRS
fomenter	fomentassent	V;IPFV;SBJV;PL;3;PST
desmonter	desmonte	V;IND;SG;3;PRS
commencer	commençoient	V;IPFV;IND;PL;3;PST;LGSPEC1
getter	gettent	V;IND;PL;3;PRS
charger	chargeois	V;IPFV;IND;SG;2;PST;LGSPEC1
regratier	regratiyez	V;IPFV;IND;PL;2;PST;LGSPEC2
saluer	salue	V;IND;SG;3;PRS
oublyer	oublyast	V;IPFV;SBJV;SG;3;PST
deshonnourer	deshonnoura	V;PFV;IND;SG;1;PST
tramper	trampa	V;PFV;IND;SG;1;PST
desbaucher	desbauchons	V;IND;PL;1;PRS
arrester	arresteryez	V;COND;PL;2;LGSPEC2
quitter	quittyez	V;IPFV;IND;PL;2;PST;LGSPEC2
iecter	iectoit	V;IPFV;IND;SG;3;PST;LGSPEC1
atacher	atachent	V;SBJV;PL;3;PRS
charger	chargeois	V;IPFV;IND;SG;1;PST;LGSPEC1
affier	affions	V;IND;PL;1;PRS
prier	prioys	V;IPFV;IND;SG;1;PST;LGSPEC2
enhorter	enhortons	V;IND;PL;1;PRS
recuperer	recupereroit	V;COND;SG;3;LGSPEC1
demonstrer	demonstrast	V;IPFV;SBJV;SG;3;PST
entrefaire	entreferoient	V;COND;PL;3;LGSPEC1
retirer	retire	V;IND;SG;1;PRS
encontrer	encontrerions	V;COND;PL;1;LGSPEC1
rouller	roulloient	V;IPFV;IND;PL;3;PST;LGSPEC1
desrober	desrobois	V;IPFV;IND;SG;2;PST;LGSPEC1
prier	prie	V;IND;SG;1;PRS
enferrer	enferreryez	V;COND;PL;2;LGSPEC2
esgaler	esgala	V;PFV;IND;SG;3;PST
esveigler	esveigle	V;IMP;SG;2
flechir	fleschirent	V;PFV;IND;PL;3;PST
praesenter	praesenteroyent	V;COND;PL;3;LGSPEC2
esventer	esventerai	V;IND;SG;1;FUT;LGSPEC1
recuperer	recuperassent	V;IPFV;SBJV;PL;3;PST
esquacher	esquachyez	V;IPFV;IND;PL;2;PST;LGSPEC2
encontrer	encontra	V;PFV;IND;SG;3;PST
desheriter	desherityez	V;IPFV;IND;PL;2;PST;LGSPEC2
desregler	desreglastes	V;PFV;IND;PL;2;PST
desplacer	desplacyez	V;IPFV;IND;PL;2;PST;LGSPEC2
assieger	assiegez	V;IND;PL;2;PRS
desyrer	desyrons	V;IND;PL;1;PRS
exstirper	exstirpiez	V;IPFV;IND;PL;2;PST;LGSPEC1
resigner	resignoys	V;IPFV;IND;SG;2;PST;LGSPEC2
arroier	arroiois	V;IPFV;IND;SG;1;PST;LGSPEC1
songer	songyons	V;IPFV;IND;PL;1;PST;LGSPEC2
enpoisonner	enpoisonneras	V;IND;SG;2;FUT
consyderer	consydereroys	V;COND;SG;2;LGSPEC2
iecter	iectoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
mulcter	mulcte	V;SBJV;SG;1;PRS
offencer	offençast	V;IPFV;SBJV;SG;3;PST
condescendre	condescendons	V;SBJV;PL;1;PRS
aguyser	aguyses	V;SBJV;SG;2;PRS
offencer	offencent	V;IND;PL;3;PRS
r'asseurer	r'asseuroient	V;IPFV;IND;PL;3;PST;LGSPEC1
fouller	foulle	V;SBJV;SG;1;PRS
occuper	occupe	V;IND;SG;1;PRS
repraesenter	repraesentassions	V;IPFV;SBJV;PL;1;PST
quester	questoys	V;IPFV;IND;SG;1;PST;LGSPEC2
gaimenter	gaimentoys	V;IPFV;IND;SG;1;PST;LGSPEC2
proclamer	proclamassiez	V;IPFV;SBJV;PL;2;PST
contreroller	contrerolleroys	V;COND;SG;1;LGSPEC2
tocquer	tocquoys	V;IPFV;IND;SG;1;PST;LGSPEC2
aguyser	aguyseroys	V;COND;SG;2;LGSPEC2
pausmer	pausmoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
entredemander	vous entredemandez	V;SBJV;PL;2;PRS
ralier	raliera	V;IND;SG;3;FUT
pausmer	pausmez	V;SBJV;PL;2;PRS
translater	translatoit	V;IPFV;IND;SG;3;PST;LGSPEC1
iolyer	iolyer	V;NFIN
baster	bastons	V;SBJV;PL;1;PRS
chanter	chanterois	V;COND;SG;2;LGSPEC1
presumer	presumasse	V;IPFV;SBJV;SG;1;PST
effreer	effreassions	V;IPFV;SBJV;PL;1;PST
marcher	marchasmes	V;PFV;IND;PL;1;PST
empieger	empiegeassent	V;IPFV;SBJV;PL;3;PST
provocquer	provocquerois	V;COND;SG;2;LGSPEC1
esperonner	esperonneroient	V;COND;PL;3;LGSPEC1
preceder	precederoyent	V;COND;PL;3;LGSPEC2
penser	pense	V;IND;SG;1;PRS
esmerveillier	esmerveilliez	V;IND;PL;2;PRS
cercher	cercheroys	V;COND;SG;1;LGSPEC2
estimer	estimasmes	V;PFV;IND;PL;1;PST
mettre	mettriez	V;COND;PL;2
essilier	essiliez	V;IND;PL;2;PRS
detester	detesteroys	V;COND;SG;1;LGSPEC2
enorter	enorteroys	V;COND;SG;2;LGSPEC2
estouffer	estouffons	V;IND;PL;1;PRS
entrefraper	entrefraperyons	V;COND;PL;1;LGSPEC2
esvanter	esvantassiez	V;IPFV;SBJV;PL;2;PST
esparpiller	esparpillasse	V;IPFV;SBJV;SG;1;PST
garder	garderay	V;IND;SG;1;FUT;LGSPEC2
approuchier	approuches	V;SBJV;SG;2;PRS
pausmer	pausmassent	V;IPFV;SBJV;PL;3;PST
mercyer	mercyeras	V;IND;SG;2;FUT
prier	prie	V;IND;SG;3;PRS
tocquer	tocquasmes	V;PFV;IND;PL;1;PST
combiner	combine	V;IMP;SG;2
cesser	cessez	V;IND;PL;2;PRS
mercyer	mercyois	V;IPFV;IND;SG;2;PST;LGSPEC1
soubhaitter	soubhaitte	V;IND;SG;1;PRS
cesser	cessastes	V;PFV;IND;PL;2;PST
estinceller	estincellent	V;IND;PL;3;PRS
separer	separera	V;IND;SG;3;FUT
raenchonner	raenchonnoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
esvanter	esvantassent	V;IPFV;SBJV;PL;3;PST
baster	bastes	V;SBJV;SG;2;PRS
appareiller	appareillerois	V;COND;SG;1;LGSPEC1
essilier	essilasses	V;IPFV;SBJV;SG;2;PST
coniurer	coniuroys	V;IPFV;IND;SG;2;PST;LGSPEC2
enhorter	enhortent	V;SBJV;PL;3;PRS
presumer	presumez	V;IMP;PL;2
adviser	adviserois	V;COND;SG;1;LGSPEC1
renfler	renflyons	V;IPFV;IND;PL;1;PST;LGSPEC2
enterrer	enterroit	V;IPFV;IND;SG;3;PST;LGSPEC1
mensongier	mensongierons	V;IND;PL;1;FUT
lascher	lascherez	V;IND;PL;2;FUT
faucer	fauceriez	V;COND;PL;2;LGSPEC1
desrisier	desrisieroit	V;COND;SG;3;LGSPEC1
marier	mariois	V;IPFV;IND;SG;2;PST;LGSPEC1
cauterizer	cauterizerez	V;IND;PL;2;FUT
finir	finis	V;PFV;IND;SG;1;PST
adapter	adaptez	V;IMP;PL;2
fortifier	fortifies	V;IND;SG;2;PRS
remerquer	remerquyons	V;IPFV;IND;PL;1;PST;LGSPEC2
ietter	ietteras	V;IND;SG;2;FUT
reguarder	reguarderai	V;IND;SG;1;FUT;LGSPEC1
mensongier	mensongent	V;IND;PL;3;PRS
entituler	entituler	V;NFIN
sembler	semble	V;IND;SG;3;PRS
rappeller	rappellasmes	V;PFV;IND;PL;1;PST
desister	desiste	V;IND;SG;1;PRS
abboyer	abboyez	V;SBJV;PL;2;PRS
traitter	traitter	V;NFIN
estonner	estonneriez	V;COND;PL;2;LGSPEC1
espouser	espousez	V;IMP;PL;2
desloger	deslogiez	V;IPFV;IND;PL;2;PST;LGSPEC1
escryer	escryes	V;SBJV;SG;2;PRS
rappeller	rappelle	V;SBJV;SG;3;PRS
ieusner	ieusnera	V;IND;SG;3;FUT
derver	dervassent	V;IPFV;SBJV;PL;3;PST
traicter	tractassions	V;IPFV;SBJV;PL;1;PST
minorer	minoryons	V;IPFV;IND;PL;1;PST;LGSPEC2
buchier	buchieroyent	V;COND;PL;3;LGSPEC2
payer	payasse	V;IPFV;SBJV;SG;1;PST
transgloutir	transgloutisse	V;SBJV;SG;3;PRS
employer	employast	V;IPFV;SBJV;SG;3;PST
blesser	blesse	V;IMP;SG;2
monter	monte	V;IND;SG;1;PRS
caper	capons	V;SBJV;PL;1;PRS
accompaigner	accompaignois	V;IPFV;IND;SG;1;PST;LGSPEC1
ieusner	ieusnons	V;IND;PL;1;PRS
mortifier	mortifierez	V;IND;PL;2;FUT
reserver	reserverions	V;COND;PL;1;LGSPEC1
menasser	menassons	V;SBJV;PL;1;PRS
rebarber	rebarberoys	V;COND;SG;2;LGSPEC2
desnouer	desnoueras	V;IND;SG;2;FUT
traicter	tracteront	V;IND;PL;3;FUT
alonger	alongez	V;SBJV;PL;2;PRS
alonger	alongeassent	V;IPFV;SBJV;PL;3;PST
effronter	effronterent	V;PFV;IND;PL;3;PST
enchasser	enchassastes	V;PFV;IND;PL;2;PST
loger	logeroys	V;COND;SG;1;LGSPEC2
travailler	travaillerai	V;IND;SG;1;FUT;LGSPEC1
arriver	arrivent	V;IND;PL;3;PRS
communicquer	communicquerent	V;PFV;IND;PL;3;PST
pocher	pochez	V;SBJV;PL;2;PRS
viser	vises	V;IND;SG;2;PRS
porter	portoit	V;IPFV;IND;SG;3;PST;LGSPEC1
resister	resistoient	V;IPFV;IND;PL;3;PST;LGSPEC1
ronfler	ronfleroys	V;COND;SG;2;LGSPEC2
renommer	renommeroys	V;COND;SG;1;LGSPEC2
luitter	luittastes	V;PFV;IND;PL;2;PST
traittier	traittieroyt	V;COND;SG;3;LGSPEC2
tesmoigner	tesmoignastes	V;PFV;IND;PL;2;PST
debaracer	debaraceriez	V;COND;PL;2;LGSPEC1
expeller	expelleroit	V;COND;SG;3;LGSPEC1
abhorrer	abhorres	V;SBJV;SG;2;PRS
renommer	renommeryez	V;COND;PL;2;LGSPEC2
aloser	alose	V;SBJV;SG;1;PRS
fiancer	fiançassent	V;IPFV;SBJV;PL;3;PST
humilier	humilieront	V;IND;PL;3;FUT
rincer	rincerai	V;IND;SG;1;FUT;LGSPEC1
finir	finissons	V;IND;PL;1;PRS
flotter	flotteryez	V;COND;PL;2;LGSPEC2
encliner	enclinas	V;PFV;IND;SG;2;PST
rappeller	rappella	V;PFV;IND;SG;3;PST
esternuer	esternuez	V;IMP;PL;2
espoventer	espoventa	V;PFV;IND;SG;3;PST
moderer	moderes	V;IND;SG;2;PRS
fraper	frapyons	V;IPFV;IND;PL;1;PST;LGSPEC2
deslyer	deslyassiez	V;IPFV;SBJV;PL;2;PST
dampner	dampneryons	V;COND;PL;1;LGSPEC2
gouster	gousta	V;PFV;IND;SG;3;PST
surnommer	surnommeryez	V;COND;PL;2;LGSPEC2
subiecter	subiecte	V;IND;SG;1;PRS
cointoier	cointoierai	V;IND;SG;1;FUT;LGSPEC1
sçavoir	sçavoient	V;IPFV;IND;PL;3;PST;LGSPEC2
houssepillier	houssepillieroient	V;COND;PL;3;LGSPEC1
haster	hasteroit	V;COND;SG;3;LGSPEC1
accomplir	accomplirent	V;PFV;IND;PL;3;PST
aler	vas	V;IND;SG;2;PRS
saulver	saulveryez	V;COND;PL;2;LGSPEC2
avaller	avallerent	V;PFV;IND;PL;3;PST
baptiser	baptisas	V;PFV;IND;SG;2;PST
desloger	desloge	V;IND;SG;3;PRS
mortifier	mortifient	V;IND;PL;3;PRS
parler	parle	V;SBJV;SG;3;PRS
destabler	destableroient	V;COND;PL;3;LGSPEC1
couster	cousterai	V;IND;SG;1;FUT;LGSPEC1
presupposer	presupposas	V;PFV;IND;SG;2;PST
trouver	trouvois	V;IPFV;IND;SG;2;PST;LGSPEC1
riffler	rifflons	V;IMP;PL;1
pacquer	pacqueras	V;IND;SG;2;FUT
praeparer	praeparast	V;IPFV;SBJV;SG;3;PST
estoffer	estoffa	V;PFV;IND;SG;3;PST
enseignier	enseignerent	V;PFV;IND;PL;3;PST
transgloutir	transgloutissoit	V;IPFV;IND;SG;3;PST;LGSPEC1
practicquer	practicque	V;IND;SG;3;PRS
foetter	foetterez	V;IND;PL;2;FUT
iurer	iuriez	V;IPFV;IND;PL;2;PST;LGSPEC1
baptizer	baptizons	V;SBJV;PL;1;PRS
courrouchier	courrouchierois	V;COND;SG;2;LGSPEC1
trouver	trouverez	V;IND;PL;2;FUT
advancer	advancer	V;NFIN
effronter	effronteront	V;IND;PL;3;FUT
deslyer	deslyez	V;SBJV;PL;2;PRS
desploier	desploie	V;SBJV;SG;3;PRS
emprunter	empruntasses	V;IPFV;SBJV;SG;2;PST
vengier	vengyons	V;IPFV;IND;PL;1;PST;LGSPEC2
enfelonner	enfelonne	V;SBJV;SG;3;PRS
tesmoigner	tesmoignasse	V;IPFV;SBJV;SG;1;PST
aorner	aornas	V;PFV;IND;SG;2;PST
estoffer	estofferez	V;IND;PL;2;FUT
frapper	frappes	V;IND;SG;2;PRS
blesser	blessons	V;IMP;PL;1
flatter	flattoient	V;IPFV;IND;PL;3;PST;LGSPEC1
peser	pesasmes	V;PFV;IND;PL;1;PST
abhorrer	abhorreriez	V;COND;PL;2;LGSPEC1
demander	demanderent	V;PFV;IND;PL;3;PST
houssepillier	houssepillyons	V;IPFV;IND;PL;1;PST;LGSPEC2
interpreter	interpreteront	V;IND;PL;3;FUT
effronter	effronteroys	V;COND;SG;2;LGSPEC2
demander	demandez	V;IND;PL;2;PRS
seeller	seellassions	V;IPFV;SBJV;PL;1;PST
espoventer	espoventerois	V;COND;SG;2;LGSPEC1
tesmoigner	tesmoignerent	V;PFV;IND;PL;3;PST
visiter	visitons	V;SBJV;PL;1;PRS
infourmer	infourmes	V;IND;SG;2;PRS
tabuster	tabustoient	V;IPFV;IND;PL;3;PST;LGSPEC1
habiter	habiteroyent	V;COND;PL;3;LGSPEC2
debaracer	debaraceront	V;IND;PL;3;FUT
menasser	menassastes	V;PFV;IND;PL;2;PST
iurer	iurasmes	V;PFV;IND;PL;1;PST
estre	estois	V;IPFV;IND;SG;1;PST;LGSPEC1
couster	cousterois	V;COND;SG;2;LGSPEC1
exposer	exposeray	V;IND;SG;1;FUT;LGSPEC2
celebrer	celebreryons	V;COND;PL;1;LGSPEC2
deliberer	deliberions	V;IPFV;IND;PL;1;PST;LGSPEC1
pourchasser	pourchassez	V;SBJV;PL;2;PRS
acoustumer	acoustumoys	V;IPFV;IND;SG;2;PST;LGSPEC2
contribuer	contribuastes	V;PFV;IND;PL;2;PST
esternuer	esternueriez	V;COND;PL;2;LGSPEC1
picquier	picquieroit	V;COND;SG;3;LGSPEC1
advancer	advancyez	V;IPFV;IND;PL;2;PST;LGSPEC2
enfelonner	enfelonnast	V;IPFV;SBJV;SG;3;PST
engroisser	engroisserons	V;IND;PL;1;FUT
expeller	expellez	V;IMP;PL;2
deslyer	deslyoit	V;IPFV;IND;SG;3;PST;LGSPEC1
emerger	emergeras	V;IND;SG;2;FUT
faucer	fauceray	V;IND;SG;1;FUT;LGSPEC2
guarder	guarderyons	V;COND;PL;1;LGSPEC2
rappeller	rappellez	V;IMP;PL;2
revencher	revencheront	V;IND;PL;3;FUT
chocquer	chocquons	V;SBJV;PL;1;PRS
despossesser	despossesses	V;IND;SG;2;PRS
reguarder	reguardassiez	V;IPFV;SBJV;PL;2;PST
abiurer	abiurassent	V;IPFV;SBJV;PL;3;PST
encommencer	encommençast	V;IPFV;SBJV;SG;3;PST
moustrer	moustrent	V;IND;PL;3;PRS
deslyer	deslyent	V;IND;PL;3;PRS
celebrer	celebre	V;IND;SG;3;PRS
quiter	quiteroys	V;COND;SG;1;LGSPEC2
baptiser	baptisa	V;PFV;IND;SG;3;PST
luitter	luitte	V;IMP;SG;2
eslever	esleverois	V;COND;SG;1;LGSPEC1
gouster	goustassent	V;IPFV;SBJV;PL;3;PST
chocquer	chocqueras	V;IND;SG;2;FUT
approuvender	approuvenda	V;PFV;IND;SG;1;PST
achever	achevasmes	V;PFV;IND;PL;1;PST
gaspiller	gaspillez	V;IMP;PL;2
desnouer	desnouast	V;IPFV;SBJV;SG;3;PST
racointer	racointes	V;SBJV;SG;2;PRS
cointoier	cointoiasmes	V;PFV;IND;PL;1;PST
empoizonner	empoizonnez	V;SBJV;PL;2;PRS
gaber	gaberoyt	V;COND;SG;3;LGSPEC2
traittier	traittoys	V;IPFV;IND;SG;1;PST;LGSPEC2
entredesirer	s'entredesireroient	V;COND;PL;3;LGSPEC1
deliberer	deliberez	V;SBJV;PL;2;PRS
esveiller	esveillons	V;SBJV;PL;1;PRS
traitter	traittoient	V;IPFV;IND;PL;3;PST;LGSPEC1
nouer	nouerai	V;IND;SG;1;FUT;LGSPEC1
rebarber	rebarboyt	V;IPFV;IND;SG;3;PST;LGSPEC2
habiter	habitent	V;IND;PL;3;PRS
desister	desisteriez	V;COND;PL;2;LGSPEC1
contribuer	contribuoit	V;IPFV;IND;SG;3;PST;LGSPEC1
reiecter	reiecteriez	V;COND;PL;2;LGSPEC1
ayder	aydons	V;IND;PL;1;PRS
supposer	supposoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
conseiller	conseillois	V;IPFV;IND;SG;1;PST;LGSPEC1
conseiller	conseillez	V;IND;PL;2;PRS
gaster	gasteriez	V;COND;PL;2;LGSPEC1
toquer	toquoys	V;IPFV;IND;SG;1;PST;LGSPEC2
communicquer	communicqueryez	V;COND;PL;2;LGSPEC2
frapper	frappe	V;IMP;SG;2
effectuer	effectuons	V;SBJV;PL;1;PRS
noter	noteroys	V;COND;SG;2;LGSPEC2
lever	leviez	V;IPFV;IND;PL;2;PST;LGSPEC1
engendrer	engendrerent	V;PFV;IND;PL;3;PST
deschevaucher	deschevauchions	V;IPFV;IND;PL;1;PST;LGSPEC1
escryer	escrye	V;SBJV;SG;1;PRS
humilier	humiliasse	V;IPFV;SBJV;SG;1;PST
remercyer	remercyera	V;IND;SG;3;FUT
habiter	habitastes	V;PFV;IND;PL;2;PST
racointer	racointasse	V;IPFV;SBJV;SG;1;PST
empoizonner	empoizonneroyt	V;COND;SG;3;LGSPEC2
mortifier	mortifioient	V;IPFV;IND;PL;3;PST;LGSPEC1
baptiser	baptises	V;SBJV;SG;2;PRS
enseignier	enseigneroys	V;COND;SG;1;LGSPEC2
deliberer	deliberent	V;SBJV;PL;3;PRS
destabler	destablons	V;IMP;PL;1
buchier	buchieroys	V;COND;SG;2;LGSPEC2
fortifier	fortifieras	V;IND;SG;2;FUT
proffiter	proffiteront	V;IND;PL;3;FUT
effronter	effronta	V;PFV;IND;SG;3;PST
alimenter	alimentez	V;IND;PL;2;PRS
aler	alas	V;PFV;IND;SG;2;PST
trouver	trouve	V;IND;SG;3;PRS
gangler	gangle	V;IND;SG;3;PRS
parler	parleroyent	V;COND;PL;3;LGSPEC2
enchasser	enchasseroit	V;COND;SG;3;LGSPEC1
haittier	haittois	V;IPFV;IND;SG;2;PST;LGSPEC1
recommander	recommanderyez	V;COND;PL;2;LGSPEC2
deschainer	deschainiez	V;IPFV;IND;PL;2;PST;LGSPEC1
estre	estoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
proffiter	proffite	V;IMP;SG;2
praeparer	praeparez	V;IMP;PL;2
sceller	scelle	V;IMP;SG;2
saulver	saulveroyt	V;COND;SG;3;LGSPEC2
meriter	meritent	V;SBJV;PL;3;PRS
rotter	rotter	V;NFIN
arrengier	arrengions	V;IND;PL;1;PRS
hucher	huchyez	V;IPFV;IND;PL;2;PST;LGSPEC2
espargner	espargnois	V;IPFV;IND;SG;1;PST;LGSPEC1
proffiter	proffitions	V;IPFV;IND;PL;1;PST;LGSPEC1
aller	yroie	V;IND;SG;1;FUT;LGSPEC2
nouer	nouasses	V;IPFV;SBJV;SG;2;PST
approuvender	approuvende	V;IND;SG;3;PRS
reculler	recullerent	V;PFV;IND;PL;3;PST
haster	hastasses	V;IPFV;SBJV;SG;2;PST
remercyer	remercyeryez	V;COND;PL;2;LGSPEC2
achapter	achapta	V;PFV;IND;SG;3;PST
aloser	alosez	V;IMP;PL;2
aboscher	aboschast	V;IPFV;SBJV;SG;3;PST
quiter	quite	V;SBJV;SG;1;PRS
viser	visyons	V;IPFV;IND;PL;1;PST;LGSPEC2
resumer	resumions	V;IPFV;IND;PL;1;PST;LGSPEC1
accomplir	accomplissoys	V;IPFV;IND;SG;1;PST;LGSPEC2
galoper	galopast	V;IPFV;SBJV;SG;3;PST
cointoier	cointoiassent	V;IPFV;SBJV;PL;3;PST
viser	viseras	V;IND;SG;2;FUT
desmettre	desmettra	V;IND;SG;3;FUT
merveiller	merveillions	V;IPFV;IND;PL;1;PST;LGSPEC1
ozer	ozer	V;NFIN
pourforcer	pourforces	V;SBJV;SG;2;PRS
passer	passois	V;IPFV;IND;SG;1;PST;LGSPEC1
tomber	tomberez	V;IND;PL;2;FUT
esveiller	esveilleryez	V;COND;PL;2;LGSPEC2
gaster	gasterent	V;PFV;IND;PL;3;PST
peser	pesons	V;IMP;PL;1
esgratigner	esgratignoient	V;IPFV;IND;PL;3;PST;LGSPEC1
baptiser	baptisent	V;SBJV;PL;3;PRS
fraper	frapent	V;IND;PL;3;PRS
eschieller	escielloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
estonner	estonnyez	V;IPFV;IND;PL;2;PST;LGSPEC2
pourchasser	pourchassent	V;IND;PL;3;PRS
prosperer	prospere	V;IMP;SG;2
tromper	tromperoyent	V;COND;PL;3;LGSPEC2
regarder	regardoys	V;IPFV;IND;SG;1;PST;LGSPEC2
rincer	rinçons	V;SBJV;PL;1;PRS
flatter	flatte	V;IND;SG;1;PRS
avoir	eussions	V;IPFV;SBJV;PL;1;PST
tabuster	tabustasse	V;IPFV;SBJV;SG;1;PST
proffiter	proffityons	V;IPFV;IND;PL;1;PST;LGSPEC2
acoustumer	acoustumerez	V;IND;PL;2;FUT
aloser	alosoys	V;IPFV;IND;SG;2;PST;LGSPEC2
gaber	gabasmes	V;PFV;IND;PL;1;PST
serainer	serainerai	V;IND;SG;1;FUT;LGSPEC1
heurter	heurteroys	V;COND;SG;2;LGSPEC2
finir	finiroys	V;COND;SG;2;LGSPEC2
houssepillier	houssepillierons	V;IND;PL;1;FUT
piller	pilleroys	V;COND;SG;1;LGSPEC2
racompter	racompteroyent	V;COND;PL;3;LGSPEC2
avoir	avons	V;IND;PL;1;PRS
estirer	estirerois	V;COND;SG;2;LGSPEC1
abiurer	abiurerez	V;IND;PL;2;FUT
mouscher	mouschez	V;IND;PL;2;PRS
gaspiller	gaspillera	V;IND;SG;3;FUT
gaster	gasteroys	V;COND;SG;2;LGSPEC2
gangler	ganglyons	V;IPFV;IND;PL;1;PST;LGSPEC2
destacher	destachez	V;SBJV;PL;2;PRS
esbaucher	esbaucher	V;NFIN
mesler	meslons	V;IND;PL;1;PRS
nettoyer	nettoyer	V;NFIN
engroisser	engroissera	V;IND;SG;3;FUT
tesmoigner	tesmoigneryons	V;COND;PL;1;LGSPEC2
macter	mactois	V;IPFV;IND;SG;1;PST;LGSPEC1
rouiller	rouillerai	V;IND;SG;1;FUT;LGSPEC1
representer	representerai	V;IND;SG;1;FUT;LGSPEC1
escorner	escornerai	V;IND;SG;1;FUT;LGSPEC1
estirer	estire	V;SBJV;SG;1;PRS
baisler	baisleroyent	V;COND;PL;3;LGSPEC2
fraper	frapa	V;PFV;IND;SG;1;PST
prosperer	prosperez	V;IND;PL;2;PRS
prosperer	prosperions	V;IPFV;IND;PL;1;PST;LGSPEC1
enterrer	enterras	V;PFV;IND;SG;2;PST
arriver	arriverois	V;COND;SG;2;LGSPEC1
traicter	tracta	V;PFV;IND;SG;3;PST
fraper	frapiez	V;IPFV;IND;PL;2;PST;LGSPEC1
engroisser	engroisseryons	V;COND;PL;1;LGSPEC2
esguarer	esguarerions	V;COND;PL;1;LGSPEC1
lascher	lascheront	V;IND;PL;3;FUT
rappeller	rappellent	V;IND;PL;3;PRS
enseignier	enseignasmes	V;PFV;IND;PL;1;PST
presupposer	presuppose	V;IMP;SG;2
interpreter	interpretas	V;PFV;IND;SG;2;PST
redrechier	redrechois	V;IPFV;IND;SG;1;PST;LGSPEC1
visiter	visiteroit	V;COND;SG;3;LGSPEC1
entredonner	vous entredonnerez	V;IND;PL;2;FUT
oultrager	oultragent	V;IND;PL;3;PRS
encliner	enclineroient	V;COND;PL;3;LGSPEC1
porter	portasses	V;IPFV;SBJV;SG;2;PST
prosperer	prospereroyent	V;COND;PL;3;LGSPEC2
preferer	prefereroit	V;COND;SG;3;LGSPEC1
effronter	effrontons	V;SBJV;PL;1;PRS
coucher	couchast	V;IPFV;SBJV;SG;3;PST
espouser	espousons	V;SBJV;PL;1;PRS
effronter	effrontons	V;IND;PL;1;PRS
encommencer	encommençoys	V;IPFV;IND;SG;1;PST;LGSPEC2
guarder	guarderoit	V;COND;SG;3;LGSPEC1
deschainer	deschainent	V;SBJV;PL;3;PRS
pourforcer	pourforcerions	V;COND;PL;1;LGSPEC1
deliberer	delibere	V;IND;SG;1;PRS
mesler	mesleray	V;IND;SG;1;FUT;LGSPEC2
abboyer	abboyeras	V;IND;SG;2;FUT
gaspiller	gaspilleroyt	V;COND;SG;3;LGSPEC2
engendrer	engendreras	V;IND;SG;2;FUT
heiler	heileront	V;IND;PL;3;FUT
deschirer	deschirions	V;IPFV;IND;PL;1;PST;LGSPEC1
esguarer	esguare	V;IND;SG;3;PRS
piller	pilleroys	V;COND;SG;2;LGSPEC2
pourchasser	pourchasserons	V;IND;PL;1;FUT
fraper	frapons	V;SBJV;PL;1;PRS
ieuner	ieunas	V;PFV;IND;SG;2;PST
invader	invaderions	V;COND;PL;1;LGSPEC1
estoffer	estoffois	V;IPFV;IND;SG;2;PST;LGSPEC1
reiecter	reiecteryons	V;COND;PL;1;LGSPEC2
payer	payast	V;IPFV;SBJV;SG;3;PST
exposer	exposassions	V;IPFV;SBJV;PL;1;PST
mesler	meslasses	V;IPFV;SBJV;SG;2;PST
estonner	estonne	V;SBJV;SG;1;PRS
employer	employeroyt	V;COND;SG;3;LGSPEC2
rouiller	rouilloit	V;IPFV;IND;SG;3;PST;LGSPEC1
subiecter	subiecterai	V;IND;SG;1;FUT;LGSPEC1
surnommer	surnommerai	V;IND;SG;1;FUT;LGSPEC1
lever	leveryez	V;COND;PL;2;LGSPEC2
foetter	foetteroyent	V;COND;PL;3;LGSPEC2
despossesser	despossessassiez	V;IPFV;SBJV;PL;2;PST
nettoyer	nettoyoys	V;IPFV;IND;SG;2;PST;LGSPEC2
estirer	estirera	V;IND;SG;3;FUT
lescher	leschoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
acoustumer	acoustumer	V;NFIN
tuer	tueray	V;IND;SG;1;FUT;LGSPEC2
expeller	expelleroys	V;COND;SG;2;LGSPEC2
infourmer	infourmerions	V;COND;PL;1;LGSPEC1
arriver	arriverez	V;IND;PL;2;FUT
enfelonner	enfelonne	V;SBJV;SG;1;PRS
desploier	desploias	V;PFV;IND;SG;2;PST
tuer	tueroient	V;COND;PL;3;LGSPEC1
cerchier	cerche	V;IND;SG;1;PRS
rincer	rinças	V;PFV;IND;SG;2;PST
desrobber	desrobba	V;PFV;IND;SG;1;PST
destacher	destachasmes	V;PFV;IND;PL;1;PST
lascher	laschoit	V;IPFV;IND;SG;3;PST;LGSPEC1
tabuster	tabusteryez	V;COND;PL;2;LGSPEC2
debaracer	debaraçoient	V;IPFV;IND;PL;3;PST;LGSPEC1
preparer	prepara	V;PFV;IND;SG;3;PST
desarmer	desarmeroit	V;COND;SG;3;LGSPEC1
redrechier	redrechastes	V;PFV;IND;PL;2;PST
celebrer	celebre	V;IMP;SG;2
abboyer	abboyerois	V;COND;SG;1;LGSPEC1
abboyer	abboyeront	V;IND;PL;3;FUT
demander	demanderois	V;COND;SG;1;LGSPEC1
hacher	hachoys	V;IPFV;IND;SG;2;PST;LGSPEC2
mesler	mesloys	V;IPFV;IND;SG;1;PST;LGSPEC2
croniquier	croniquiasses	V;IPFV;SBJV;SG;2;PST
destacher	destacheroyent	V;COND;PL;3;LGSPEC2
tomber	tomberoyt	V;COND;SG;3;LGSPEC2
pasturer	pasturons	V;SBJV;PL;1;PRS
racompter	racomptasse	V;IPFV;SBJV;SG;1;PST
dancer	danceryez	V;COND;PL;2;LGSPEC2
emboucher	emboucheroient	V;COND;PL;3;LGSPEC1
adapter	adapteryons	V;COND;PL;1;LGSPEC2
effectuer	effectuez	V;IMP;PL;2
esloigner	esloigneryons	V;COND;PL;1;LGSPEC2
tromper	trompent	V;IND;PL;3;PRS
veiller	veilleroient	V;COND;PL;3;LGSPEC1
derver	derveroys	V;COND;SG;2;LGSPEC2
estre	soient	V;SBJV;PL;3;PRS;LGSPEC2
vengier	vengeast	V;IPFV;SBJV;SG;3;PST
arrengier	arrengions	V;SBJV;PL;1;PRS
escorcher	escorchez	V;IMP;PL;2
quiter	quitiez	V;IPFV;IND;PL;2;PST;LGSPEC1
eslever	esleveroys	V;COND;SG;1;LGSPEC2
aller	irions	V;COND;PL;1;LGSPEC1
resumer	resumons	V;SBJV;PL;1;PRS
peser	peseront	V;IND;PL;3;FUT
amadouer	amadoueroient	V;COND;PL;3;LGSPEC1
remercyer	remercyyons	V;IPFV;IND;PL;1;PST;LGSPEC2
escorner	escornent	V;IND;PL;3;PRS
avoyr	eust	V;IPFV;SBJV;SG;3;PST
esternuer	esternuer	V;NFIN
menasser	menassez	V;IMP;PL;2
sceller	scellera	V;IND;SG;3;FUT
rebarber	rebarbast	V;IPFV;SBJV;SG;3;PST
caper	capoys	V;IPFV;IND;SG;2;PST;LGSPEC2
viser	visons	V;IND;PL;1;PRS
resumer	resumois	V;IPFV;IND;SG;1;PST;LGSPEC1
ronfler	ronfle	V;SBJV;SG;1;PRS
ayder	aydiez	V;IPFV;IND;PL;2;PST;LGSPEC1
visiter	visites	V;IND;SG;2;PRS
pourchasser	pourchassoys	V;IPFV;IND;SG;1;PST;LGSPEC2
peser	pese	V;IND;SG;3;PRS
peser	pesastes	V;PFV;IND;PL;2;PST
hebergier	hebergea	V;PFV;IND;SG;3;PST
engroisser	engroisseryez	V;COND;PL;2;LGSPEC2
emprunter	emprunterent	V;PFV;IND;PL;3;PST
sçavoir	sçauray	V;IND;SG;1;FUT;LGSPEC1
mesler	mesleroys	V;COND;SG;1;LGSPEC2
tabuster	tabusteroys	V;COND;SG;1;LGSPEC2
praeparer	praeparassions	V;IPFV;SBJV;PL;1;PST
subiecter	subiecte	V;IND;SG;3;PRS
faucer	fauçasmes	V;PFV;IND;PL;1;PST
emerger	emerges	V;SBJV;SG;2;PRS
conseiller	conseillas	V;PFV;IND;SG;2;PST
cointoier	cointoiassiez	V;IPFV;SBJV;PL;2;PST
pourpenser	pourpense	V;IND;SG;1;PRS
foetter	foetteroit	V;COND;SG;3;LGSPEC1
visiter	visiterez	V;IND;PL;2;FUT
nouer	noue	V;SBJV;SG;1;PRS
demourer	demoureroyt	V;COND;SG;3;LGSPEC2
amer	amera	V;IND;SG;3;FUT
interpreter	interpretons	V;IND;PL;1;PRS
desarmer	desarment	V;IND;PL;3;PRS
supposer	supposeroyent	V;COND;PL;3;LGSPEC2
preter	pretois	V;IPFV;IND;SG;2;PST;LGSPEC1
fraper	frapez	V;SBJV;PL;2;PRS
importuner	importunassiez	V;IPFV;SBJV;PL;2;PST
surnommer	surnommez	V;IMP;PL;2
humilier	humilias	V;PFV;IND;SG;2;PST
achapter	achaptoys	V;IPFV;IND;SG;1;PST;LGSPEC2
accompaigner	accompaignoient	V;IPFV;IND;PL;3;PST;LGSPEC1
flotter	flotterent	V;PFV;IND;PL;3;PST
proffiter	proffiteras	V;IND;SG;2;FUT
mescler	mescleroys	V;COND;SG;2;LGSPEC2
habiter	habiteras	V;IND;SG;2;FUT
recouvrer	recouvreroit	V;COND;SG;3;LGSPEC1
tourmenter	tourmentyons	V;IPFV;IND;PL;1;PST;LGSPEC2
loger	logeras	V;IND;SG;2;FUT
macter	mactes	V;IND;SG;2;PRS
contribuer	contribues	V;SBJV;SG;2;PRS
manouvrer	manouvrerois	V;COND;SG;1;LGSPEC1
bransler	branslerons	V;IND;PL;1;FUT
expeller	expellassions	V;IPFV;SBJV;PL;1;PST
pourforcer	pourforçoient	V;IPFV;IND;PL;3;PST;LGSPEC1
tourmenter	tourmentasses	V;IPFV;SBJV;SG;2;PST
desnouer	desnouassions	V;IPFV;SBJV;PL;1;PST
tourner	tournent	V;SBJV;PL;3;PRS
finir	finissent	V;IND;PL;3;PRS
impugner	impugnes	V;IND;SG;2;PRS
baisler	baislerai	V;IND;SG;1;FUT;LGSPEC1
singler	singlons	V;SBJV;PL;1;PRS
travailler	travailler	V;NFIN
macter	mactassent	V;IPFV;SBJV;PL;3;PST
desarmer	desarmeroient	V;COND;PL;3;LGSPEC1
estiquier	estiquieray	V;IND;SG;1;FUT;LGSPEC2
pourchasser	pourchassent	V;SBJV;PL;3;PRS
passer	passeroient	V;COND;PL;3;LGSPEC1
estoffer	estofferai	V;IND;SG;1;FUT;LGSPEC1
engroisser	engroissois	V;IPFV;IND;SG;1;PST;LGSPEC1
ozer	ozons	V;SBJV;PL;1;PRS
oster	ostez	V;SBJV;PL;2;PRS
achever	acheves	V;SBJV;SG;2;PRS
tromper	tromperiez	V;COND;PL;2;LGSPEC1
peser	pesons	V;SBJV;PL;1;PRS
aquitter	aquittastes	V;PFV;IND;PL;2;PST
desarmer	desarmions	V;IPFV;IND;PL;1;PST;LGSPEC1
hacher	hacheroit	V;COND;SG;3;LGSPEC1
eslever	esleves	V;SBJV;SG;2;PRS
subiecter	subiecteroient	V;COND;PL;3;LGSPEC1
reguarder	reguarderont	V;IND;PL;3;FUT
emprunter	empruntoit	V;IPFV;IND;SG;3;PST;LGSPEC1
intoxiquer	intoxiquastes	V;PFV;IND;PL;2;PST
representer	representassent	V;IPFV;SBJV;PL;3;PST
ozer	ozent	V;SBJV;PL;3;PRS
hacher	hachoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
deschevaucher	deschevaucheroit	V;COND;SG;3;LGSPEC1
racointer	racointassiez	V;IPFV;SBJV;PL;2;PST
sçavoir	sceurent	V;PFV;IND;PL;3;PST
rotter	rottes	V;IND;SG;2;PRS
escryer	escryyons	V;IPFV;IND;PL;1;PST;LGSPEC2
deschirer	deschireryez	V;COND;PL;2;LGSPEC2
proffiter	proffitasses	V;IPFV;SBJV;SG;2;PST
racointer	racointerai	V;IND;SG;1;FUT;LGSPEC1
subiuguier	subiugue	V;IND;SG;3;PRS
eslever	esleveroyt	V;COND;SG;3;LGSPEC2
praesider	praesidassiez	V;IPFV;SBJV;PL;2;PST
monter	montons	V;IMP;PL;1
besoinger	besoigneray	V;IND;SG;1;FUT;LGSPEC2
flotter	flotter	V;NFIN
houssepillier	houssepillasmes	V;PFV;IND;PL;1;PST
saulter	saultas	V;PFV;IND;SG;2;PST
racompter	racompte	V;IND;SG;3;PRS
laisser	laissyons	V;IPFV;IND;PL;1;PST;LGSPEC2
frapper	frapperiez	V;COND;PL;2;LGSPEC1
estre	fus	V;PFV;IND;SG;2;PST
buchier	buchieront	V;IND;PL;3;FUT
deliberer	deliberyons	V;IPFV;IND;PL;1;PST;LGSPEC2
derver	derve	V;IND;SG;1;PRS
rotter	rottasse	V;IPFV;SBJV;SG;1;PST
esbaucher	esbauchent	V;SBJV;PL;3;PRS
despuceller	despucelleray	V;IND;SG;1;FUT;LGSPEC2
revencher	revenchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
lescher	leschez	V;SBJV;PL;2;PRS
tabuster	tabustions	V;IPFV;IND;PL;1;PST;LGSPEC1
desmeler	desmela	V;PFV;IND;SG;1;PST
escorner	escornez	V;IMP;PL;2
desmeler	desmelons	V;IMP;PL;1
flotter	flottez	V;IMP;PL;2
vengier	vengieroyent	V;COND;PL;3;LGSPEC2
aquitter	aquittasses	V;IPFV;SBJV;SG;2;PST
achapter	achapteront	V;IND;PL;3;FUT
louer	loues	V;SBJV;SG;2;PRS
ronfler	ronflois	V;IPFV;IND;SG;1;PST;LGSPEC1
esgratigner	esgratigner	V;NFIN
accoustumer	accoustumasmes	V;PFV;IND;PL;1;PST
loger	logeoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
destourner	destournerai	V;IND;SG;1;FUT;LGSPEC1
gaster	gastoys	V;IPFV;IND;SG;1;PST;LGSPEC2
aler	aliez	V;IPFV;IND;PL;2;PST
escryer	escrye	V;IND;SG;3;PRS
gaster	gaster	V;NFIN
preferer	preferons	V;IND;PL;1;PRS
contribuer	contribuasses	V;IPFV;SBJV;SG;2;PST
abiurer	abiureroys	V;COND;SG;2;LGSPEC2
pourforcer	pourforçassions	V;IPFV;SBJV;PL;1;PST
accomplir	accomplit	V;PFV;IND;SG;3;PST
considerer	consideres	V;IND;SG;2;PRS
praesider	praesiderois	V;COND;SG;1;LGSPEC1
aller	irons	V;IND;PL;1;FUT;LGSPEC1
guarder	guarderont	V;IND;PL;3;FUT
houssepillier	houssepille	V;IMP;SG;2
entituler	entitule	V;IND;SG;1;PRS
cointoier	cointoions	V;IND;PL;1;PRS
encharger	enchargerons	V;IND;PL;1;FUT
fiancer	fiançois	V;IPFV;IND;SG;1;PST;LGSPEC1
eschapper	eschapperai	V;IND;SG;1;FUT;LGSPEC1
iurer	iurerons	V;IND;PL;1;FUT
traicter	tractast	V;IPFV;SBJV;SG;3;PST
abiurer	abiurons	V;IND;PL;1;PRS
parler	parlastes	V;PFV;IND;PL;2;PST
escorner	escorneroient	V;COND;PL;3;LGSPEC1
rouiller	rouillions	V;IPFV;IND;PL;1;PST;LGSPEC1
coucher	coucheroys	V;COND;SG;2;LGSPEC2
escouter	escouterons	V;IND;PL;1;FUT
gaster	gastons	V;SBJV;PL;1;PRS
dampner	dampne	V;IND;SG;3;PRS
pourforcer	pourforça	V;PFV;IND;SG;1;PST
baptizer	baptize	V;SBJV;SG;1;PRS
supposer	supposes	V;SBJV;SG;2;PRS
proffiter	proffitassiez	V;IPFV;SBJV;PL;2;PST
encommencer	encommenceriez	V;COND;PL;2;LGSPEC1
laisser	laissez	V;IND;PL;2;PRS
praesider	praesideroient	V;COND;PL;3;LGSPEC1
explorer	explorassiez	V;IPFV;SBJV;PL;2;PST
mesler	meslerois	V;COND;SG;2;LGSPEC1
tomber	tombast	V;IPFV;SBJV;SG;3;PST
travailler	travaillois	V;IPFV;IND;SG;1;PST;LGSPEC1
reguarder	reguardons	V;SBJV;PL;1;PRS
remerquer	remerquions	V;IPFV;IND;PL;1;PST;LGSPEC1
effectuer	effectueray	V;IND;SG;1;FUT;LGSPEC2
baptizer	baptizeront	V;IND;PL;3;FUT
espouser	espouserent	V;PFV;IND;PL;3;PST
reculler	reculla	V;PFV;IND;SG;1;PST
gaster	gasta	V;PFV;IND;SG;1;PST
desborder	desbordez	V;IND;PL;2;PRS
macter	mactoit	V;IPFV;IND;SG;3;PST;LGSPEC1
derver	derveroient	V;COND;PL;3;LGSPEC1
pasturer	pastureroyt	V;COND;SG;3;LGSPEC2
auser	ause	V;IND;SG;1;PRS
laidenger	laidengez	V;SBJV;PL;2;PRS
detranchier	detranchieront	V;IND;PL;3;FUT
endommaiger	endommaigeront	V;IND;PL;3;FUT
prester	prestyons	V;IPFV;IND;PL;1;PST;LGSPEC2
robber	robboyent	V;IPFV;IND;PL;3;PST;LGSPEC2
traveillier	traveillieroient	V;COND;PL;3;LGSPEC1
proteger	protegyez	V;IPFV;IND;PL;2;PST;LGSPEC2
flotter	flotte	V;IMP;SG;2
ieuner	ieunerent	V;PFV;IND;PL;3;PST
pourforcer	pourforce	V;IND;SG;1;PRS
rebarber	rebarbe	V;IND;SG;1;PRS
estirer	estireroient	V;COND;PL;3;LGSPEC1
alonger	alongeryons	V;COND;PL;1;LGSPEC2
dampner	dampnerent	V;PFV;IND;PL;3;PST
deffier	deffiassent	V;IPFV;SBJV;PL;3;PST
prosperer	prospererez	V;IND;PL;2;FUT
meriter	merite	V;IND;SG;1;PRS
possesser	possesseroient	V;COND;PL;3;LGSPEC1
deslyer	deslyeroyt	V;COND;SG;3;LGSPEC2
achever	achevois	V;IPFV;IND;SG;2;PST;LGSPEC1
mortifier	mortifies	V;SBJV;SG;2;PRS
importuner	importuneroys	V;COND;SG;1;LGSPEC2
endommaiger	endommaigeois	V;IPFV;IND;SG;2;PST;LGSPEC1
desieuner	desieunerions	V;COND;PL;1;LGSPEC1
coucher	coucher	V;NFIN
communicquer	communicquoys	V;IPFV;IND;SG;1;PST;LGSPEC2
gaber	gaberoys	V;COND;SG;1;LGSPEC2
pacquer	pacquois	V;IPFV;IND;SG;1;PST;LGSPEC1
hostoier	hostoiassions	V;IPFV;SBJV;PL;1;PST
estiquier	estiquent	V;IND;PL;3;PRS
aboscher	aboschez	V;IMP;PL;2
possesser	possessas	V;PFV;IND;SG;2;PST
traicter	tracterions	V;COND;PL;1;LGSPEC1
redrechier	redrechieriez	V;COND;PL;2;LGSPEC1
negotier	negotiast	V;IPFV;SBJV;SG;3;PST
employer	employassions	V;IPFV;SBJV;PL;1;PST
avaller	avalloys	V;IPFV;IND;SG;2;PST;LGSPEC2
deliberer	delibere	V;SBJV;SG;1;PRS
engroisser	engroissois	V;IPFV;IND;SG;2;PST;LGSPEC1
oster	ostasses	V;IPFV;SBJV;SG;2;PST
moustrer	moustrasse	V;IPFV;SBJV;SG;1;PST
confermer	confermerez	V;IND;PL;2;FUT
saulter	saulteroys	V;COND;SG;2;LGSPEC2
remercyer	remercyast	V;IPFV;SBJV;SG;3;PST
conseiller	conseilloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
baisler	baisloys	V;IPFV;IND;SG;1;PST;LGSPEC2
auser	ausa	V;PFV;IND;SG;1;PST
desnouer	desnouerois	V;COND;SG;1;LGSPEC1
souspirer	souspirent	V;IND;PL;3;PRS
achapter	achaptes	V;IND;SG;2;PRS
faire	faisois	V;IPFV;IND;SG;2;PST;LGSPEC1
moderer	moderast	V;IPFV;SBJV;SG;3;PST
possesser	possessasses	V;IPFV;SBJV;SG;2;PST
remerquer	remerquerent	V;PFV;IND;PL;3;PST
desarmer	desarmastes	V;PFV;IND;PL;2;PST
proffiter	proffiteroys	V;COND;SG;1;LGSPEC2
guerpir	guerpissons	V;IND;PL;1;PRS
hucher	hucherois	V;COND;SG;1;LGSPEC1
superseder	supersedast	V;IPFV;SBJV;SG;3;PST
besoinger	besoignons	V;IMP;PL;1
auser	ause	V;IND;SG;3;PRS
tuer	tuez	V;IMP;PL;2
toquer	toquerois	V;COND;SG;1;LGSPEC1
estonner	estonnerons	V;IND;PL;1;FUT
possesser	possessions	V;IPFV;IND;PL;1;PST;LGSPEC1
resumer	resume	V;IND;SG;1;PRS
desieuner	desieunassent	V;IPFV;SBJV;PL;3;PST
raporter	raporteroyent	V;COND;PL;3;LGSPEC2
prosperer	prospereroys	V;COND;SG;2;LGSPEC2
cointoier	cointoient	V;SBJV;PL;3;PRS
aquitter	aquitteras	V;IND;SG;2;FUT
veiller	veille	V;IND;SG;3;PRS
oultrager	oultragent	V;SBJV;PL;3;PRS
superseder	supersederois	V;COND;SG;1;LGSPEC1
saulver	saulveroit	V;COND;SG;3;LGSPEC1
considerer	considererons	V;IND;PL;1;FUT
buchier	buchois	V;IPFV;IND;SG;1;PST;LGSPEC1
engendrer	engendroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
ronfler	ronfla	V;PFV;IND;SG;3;PST
hebergier	hebergieryez	V;COND;PL;2;LGSPEC2
macter	mactas	V;PFV;IND;SG;2;PST
aboscher	aboschassent	V;IPFV;SBJV;PL;3;PST
oster	ostyez	V;IPFV;IND;PL;2;PST;LGSPEC2
tourmenter	tourmente	V;SBJV;SG;1;PRS
chevauchier	chevauchierois	V;COND;SG;1;LGSPEC1
confermer	confermassiez	V;IPFV;SBJV;PL;2;PST
tomber	tomberiez	V;COND;PL;2;LGSPEC1
atempter	atemptas	V;PFV;IND;SG;2;PST
raporter	raporte	V;SBJV;SG;1;PRS
gaspiller	gaspilleront	V;IND;PL;3;FUT
loger	logea	V;PFV;IND;SG;1;PST
meriter	meritez	V;IND;PL;2;PRS
navrer	navrez	V;SBJV;PL;2;PRS
esveiller	esveilleroit	V;COND;SG;3;LGSPEC1
hacher	hachoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
interpreter	interpreteryez	V;COND;PL;2;LGSPEC2
ayder	aydasmes	V;PFV;IND;PL;1;PST
payer	payoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
haster	hastassent	V;IPFV;SBJV;PL;3;PST
heiler	heilons	V;IND;PL;1;PRS
quiter	quiteroyent	V;COND;PL;3;LGSPEC2
courrouchier	courrouchieroys	V;COND;SG;2;LGSPEC2
serainer	serainent	V;IND;PL;3;PRS
bobeliner	bobelineroit	V;COND;SG;3;LGSPEC1
achapter	achapteroys	V;COND;SG;2;LGSPEC2
auser	auseroys	V;COND;SG;1;LGSPEC2
alonger	alongea	V;PFV;IND;SG;3;PST
interpreter	interpreteroyt	V;COND;SG;3;LGSPEC2
tomber	tomberoys	V;COND;SG;2;LGSPEC2
engendrer	engendres	V;IND;SG;2;PRS
reigler	reigloit	V;IPFV;IND;SG;3;PST;LGSPEC1
effronter	effronte	V;SBJV;SG;3;PRS
alimenter	alimente	V;IMP;SG;2
macter	mactois	V;IPFV;IND;SG;2;PST;LGSPEC1
cuyder	cuydez	V;IND;PL;2;PRS
desister	desisteroient	V;COND;PL;3;LGSPEC1
superseder	supersederont	V;IND;PL;3;FUT
encliner	enclinerent	V;PFV;IND;PL;3;PST
recouvrer	recouvroit	V;IPFV;IND;SG;3;PST;LGSPEC1
flatter	flattoys	V;IPFV;IND;SG;1;PST;LGSPEC2
merveiller	merveillyons	V;IPFV;IND;PL;1;PST;LGSPEC2
moustrer	moustrastes	V;PFV;IND;PL;2;PST
gaspiller	gaspillerent	V;PFV;IND;PL;3;PST
remercyer	remercyerai	V;IND;SG;1;FUT;LGSPEC1
enfelonner	enfelonnoit	V;IPFV;IND;SG;3;PST;LGSPEC1
pourchasser	pourchassera	V;IND;SG;3;FUT
buchier	buchoys	V;IPFV;IND;SG;2;PST;LGSPEC2
dampner	dampneroys	V;COND;SG;2;LGSPEC2
practicquer	practicquerois	V;COND;SG;2;LGSPEC1
intoxiquer	intoxiqueryons	V;COND;PL;1;LGSPEC2
loger	logeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
plier	pliez	V;SBJV;PL;2;PRS
porter	portassent	V;IPFV;SBJV;PL;3;PST
mesler	mesleront	V;IND;PL;3;FUT
tourner	tournerois	V;COND;SG;1;LGSPEC1
monter	monte	V;SBJV;SG;3;PRS
subiecter	subiectasmes	V;PFV;IND;PL;1;PST
alonger	alongez	V;IND;PL;2;PRS
remerquer	remerquerois	V;COND;SG;1;LGSPEC1
riffler	riffleroient	V;COND;PL;3;LGSPEC1
espargner	espargnons	V;IMP;PL;1
emerger	emergeroys	V;COND;SG;2;LGSPEC2
pasturer	pasturerent	V;PFV;IND;PL;3;PST
preparer	preparoit	V;IPFV;IND;SG;3;PST;LGSPEC1
descharger	descharge	V;SBJV;SG;3;PRS
reiecter	reiectasse	V;IPFV;SBJV;SG;1;PST
gaber	gaberiez	V;COND;PL;2;LGSPEC1
racompter	racompteray	V;IND;SG;1;FUT;LGSPEC2
singler	singleroyt	V;COND;SG;3;LGSPEC2
preter	pretasses	V;IPFV;SBJV;SG;2;PST
enterrer	enterrerons	V;IND;PL;1;FUT
courrouchier	courrouchions	V;IPFV;IND;PL;1;PST;LGSPEC1
fraper	frapoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
grapper	grappes	V;IND;SG;2;PRS
sembler	semblyons	V;IPFV;IND;PL;1;PST;LGSPEC2
gangler	gangle	V;IMP;SG;2
empoizonner	empoizonnois	V;IPFV;IND;SG;2;PST;LGSPEC1
cuyder	cuyderois	V;COND;SG;1;LGSPEC1
proffiter	proffitons	V;IND;PL;1;PRS
noter	notoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
chocquer	chocquerai	V;IND;SG;1;FUT;LGSPEC1
pasturer	pastureray	V;IND;SG;1;FUT;LGSPEC2
quiter	quitast	V;IPFV;SBJV;SG;3;PST
estirer	estirastes	V;PFV;IND;PL;2;PST
desploier	desploies	V;SBJV;SG;2;PRS
sembler	semblerois	V;COND;SG;1;LGSPEC1
esveiller	esveilloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
moustrer	moustre	V;IND;SG;3;PRS
renommer	renommastes	V;PFV;IND;PL;2;PST
mouscher	mouscheroient	V;COND;PL;3;LGSPEC1
fraper	frapons	V;IND;PL;1;PRS
accomplir	accomplissoit	V;IPFV;IND;SG;3;PST;LGSPEC1
entituler	entituloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
possesser	possesse	V;IND;SG;3;PRS
pasturer	pastureras	V;IND;SG;2;FUT
reserver	reserve	V;IND;SG;1;PRS
reguarder	reguardez	V;IMP;PL;2
mesler	meslas	V;PFV;IND;SG;2;PST
expeller	expelloit	V;IPFV;IND;SG;3;PST;LGSPEC1
desborder	desborde	V;IND;SG;1;PRS
explicquer	explicqueras	V;IND;SG;2;FUT
traveillier	traveillent	V;SBJV;PL;3;PRS
lever	leve	V;IMP;SG;2
ayder	aydes	V;SBJV;SG;2;PRS
vengier	venge	V;IND;SG;3;PRS
desieuner	desieuneroys	V;COND;SG;1;LGSPEC2
tuer	tuas	V;PFV;IND;SG;2;PST
enterrer	enterrassions	V;IPFV;SBJV;PL;1;PST
emboucher	embouchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
loger	logeons	V;SBJV;PL;1;PRS
desborder	desborderez	V;IND;PL;2;FUT
macter	mactons	V;SBJV;PL;1;PRS
preferer	prefera	V;PFV;IND;SG;1;PST
picquier	picquieryez	V;COND;PL;2;LGSPEC2
iurer	iure	V;SBJV;SG;1;PRS
gouster	goustyez	V;IPFV;IND;PL;2;PST;LGSPEC2
derver	dervas	V;PFV;IND;SG;2;PST
oultrager	oultrageriez	V;COND;PL;2;LGSPEC1
preferer	prefereryons	V;COND;PL;1;LGSPEC2
bransler	branslasse	V;IPFV;SBJV;SG;1;PST
oultrager	oultrageois	V;IPFV;IND;SG;1;PST;LGSPEC1
expeller	expelle	V;IND;SG;1;PRS
deschevaucher	deschevauchez	V;SBJV;PL;2;PRS
entituler	entitulassions	V;IPFV;SBJV;PL;1;PST
entredesirer	nous entredesirasmes	V;PFV;IND;PL;1;PST
mescler	mesclois	V;IPFV;IND;SG;1;PST;LGSPEC1
passer	passer	V;NFIN
supposer	supposeroys	V;COND;SG;1;LGSPEC2
representer	representeras	V;IND;SG;2;FUT
derver	derve	V;IND;SG;3;PRS
bransler	bransleras	V;IND;SG;2;FUT
pourforcer	pourforcer	V;NFIN
enterrer	enterrerez	V;IND;PL;2;FUT
avaller	avallassions	V;IPFV;SBJV;PL;1;PST
heiler	heilerai	V;IND;SG;1;FUT;LGSPEC1
achapter	achaptez	V;IMP;PL;2
impugner	impugneryons	V;COND;PL;1;LGSPEC2
avoyr	aiez	V;IMP;PL;2;LGSPEC2
confermer	confermeroys	V;COND;SG;1;LGSPEC2
arriver	arriveroyent	V;COND;PL;3;LGSPEC2
ieusner	ieusnoys	V;IPFV;IND;SG;1;PST;LGSPEC2
hacher	hacheryons	V;COND;PL;1;LGSPEC2
confermer	conferme	V;IND;SG;3;PRS
foetter	foettyez	V;IPFV;IND;PL;2;PST;LGSPEC2
trousser	troussions	V;IPFV;IND;PL;1;PST;LGSPEC1
sceller	scelles	V;IND;SG;2;PRS
adapter	adapterez	V;IND;PL;2;FUT
pacquer	pacquez	V;IMP;PL;2
pourpenser	pourpensyons	V;IPFV;IND;PL;1;PST;LGSPEC2
estiquier	estiquassions	V;IPFV;SBJV;PL;1;PST
espoventer	espoventions	V;IPFV;IND;PL;1;PST;LGSPEC1
derver	derveriez	V;COND;PL;2;LGSPEC1
piller	pillassent	V;IPFV;SBJV;PL;3;PST
entituler	entituleras	V;IND;SG;2;FUT
tabuster	tabusteriez	V;COND;PL;2;LGSPEC1
reculler	recullent	V;IND;PL;3;PRS
fortifier	fortifiassiez	V;IPFV;SBJV;PL;2;PST
frapper	frapperoit	V;COND;SG;3;LGSPEC1
dampner	dampnois	V;IPFV;IND;SG;1;PST;LGSPEC1
desborder	desbordent	V;SBJV;PL;3;PRS
seeller	seellions	V;IPFV;IND;PL;1;PST;LGSPEC1
flatter	flattassions	V;IPFV;SBJV;PL;1;PST
houer	houerons	V;IND;PL;1;FUT
effectuer	effectuyez	V;IPFV;IND;PL;2;PST;LGSPEC2
ieusner	ieusna	V;PFV;IND;SG;3;PST
transgloutir	transgloutissoient	V;IPFV;IND;PL;3;PST;LGSPEC1
vengier	vengeassent	V;IPFV;SBJV;PL;3;PST
derver	dervons	V;SBJV;PL;1;PRS
gaster	gasteray	V;IND;SG;1;FUT;LGSPEC2
couster	couster	V;NFIN
entredesirer	vous entredesirassiez	V;IPFV;SBJV;PL;2;PST
courrouchier	courrouchastes	V;PFV;IND;PL;2;PST
courrouchier	courrouchierez	V;IND;PL;2;FUT
destacher	destachoys	V;IPFV;IND;SG;1;PST;LGSPEC2
proffiter	proffitera	V;IND;SG;3;FUT
esloigner	esloignerions	V;COND;PL;1;LGSPEC1
recouvrer	recouvrent	V;SBJV;PL;3;PRS
espargner	espargnes	V;IND;SG;2;PRS
merveiller	merveiller	V;NFIN
debaracer	debaracez	V;IMP;PL;2
aorner	aorne	V;SBJV;SG;1;PRS
hucher	huches	V;IND;SG;2;PRS
galoper	galopassions	V;IPFV;SBJV;PL;1;PST
desmettre	desmettiez	V;SBJV;PL;2;PRS
aquitter	aquittons	V;IMP;PL;1
aller	allastes	V;PFV;IND;PL;2;PST
gangler	ganglasses	V;IPFV;SBJV;SG;2;PST
espoventer	espoventes	V;IND;SG;2;PRS
estoffer	estofferiez	V;COND;PL;2;LGSPEC1
entituler	entitules	V;SBJV;SG;2;PRS
alimenter	alimenteriez	V;COND;PL;2;LGSPEC1
sembler	sembloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
dancer	dança	V;PFV;IND;SG;3;PST
esloigner	esloignasmes	V;PFV;IND;PL;1;PST
eschapper	eschappas	V;PFV;IND;SG;2;PST
importuner	importune	V;IND;SG;3;PRS
endommaiger	endommaigeray	V;IND;SG;1;FUT;LGSPEC2
estonner	estonnerois	V;COND;SG;1;LGSPEC1
proffiter	proffite	V;IND;SG;1;PRS
ozer	ozois	V;IPFV;IND;SG;2;PST;LGSPEC1
galoper	galopasses	V;IPFV;SBJV;SG;2;PST
blesser	blessasmes	V;PFV;IND;PL;1;PST
escryer	escryeroient	V;COND;PL;3;LGSPEC1
baptizer	baptizerois	V;COND;SG;2;LGSPEC1
baptizer	baptizasses	V;IPFV;SBJV;SG;2;PST
approuvender	approuvendast	V;IPFV;SBJV;SG;3;PST
emprunter	empruntasmes	V;PFV;IND;PL;1;PST
pocher	poche	V;IMP;SG;2
abiurer	abiurassiez	V;IPFV;SBJV;PL;2;PST
entredonner	nous entredonnons	V;SBJV;PL;1;PRS
enfelonner	enfelonneroys	V;COND;SG;2;LGSPEC2
manger	mangeras	V;IND;SG;2;FUT
sembler	semblast	V;IPFV;SBJV;SG;3;PST
chocquer	chocqueray	V;IND;SG;1;FUT;LGSPEC2
hacher	hacherons	V;IND;PL;1;FUT
espoventer	espoventez	V;SBJV;PL;2;PRS
reguarder	reguarderoyt	V;COND;SG;3;LGSPEC2
mortifier	mortifiassions	V;IPFV;SBJV;PL;1;PST
cerchier	cerches	V;IND;SG;2;PRS
desnouer	desnouyez	V;IPFV;IND;PL;2;PST;LGSPEC2
visiter	visitoys	V;IPFV;IND;SG;2;PST;LGSPEC2
rebarber	rebarberyez	V;COND;PL;2;LGSPEC2
reserver	reserve	V;SBJV;SG;1;PRS
pourforcer	pourforçast	V;IPFV;SBJV;SG;3;PST
praeparer	praeparera	V;IND;SG;3;FUT
esternuer	esternuerions	V;COND;PL;1;LGSPEC1
estre	estoit	V;IPFV;IND;SG;3;PST;LGSPEC1
toquer	toqueryons	V;COND;PL;1;LGSPEC2
flotter	flottons	V;IMP;PL;1
aorner	aorne	V;IND;SG;3;PRS
ietter	iettent	V;IND;PL;3;PRS
deffier	deffiions	V;IPFV;IND;PL;1;PST;LGSPEC1
superseder	supersedyons	V;IPFV;IND;PL;1;PST;LGSPEC2
contribuer	contribuassiez	V;IPFV;SBJV;PL;2;PST
desrobber	desrobbons	V;SBJV;PL;1;PRS
courrouchier	courrouches	V;IND;SG;2;PRS
desieuner	desieunez	V;IND;PL;2;PRS
bobeliner	bobelinerent	V;PFV;IND;PL;3;PST
abboyer	abboyeroys	V;COND;SG;1;LGSPEC2
effronter	effrontes	V;IND;SG;2;PRS
manger	mangeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
arriver	arrive	V;IMP;SG;2
toquer	toquent	V;IND;PL;3;PRS
importuner	importuner	V;NFIN
tromper	trompast	V;IPFV;SBJV;SG;3;PST
traitter	traitterez	V;IND;PL;2;FUT
considerer	consideroient	V;IPFV;IND;PL;3;PST;LGSPEC1
desmeler	desmelez	V;IND;PL;2;PRS
manouvrer	manouvrez	V;IND;PL;2;PRS
confermer	confermastes	V;PFV;IND;PL;2;PST
pocher	pocheroit	V;COND;SG;3;LGSPEC1
noter	noteroyt	V;COND;SG;3;LGSPEC2
houer	houerois	V;COND;SG;2;LGSPEC1
bobeliner	bobelinastes	V;PFV;IND;PL;2;PST
traveillier	traveillierent	V;PFV;IND;PL;3;PST
buchier	bucha	V;PFV;IND;SG;1;PST
desploier	desploia	V;PFV;IND;SG;3;PST
sceller	scellyez	V;IPFV;IND;PL;2;PST;LGSPEC2
destabler	destableryons	V;COND;PL;1;LGSPEC2
oultrager	oultrageryez	V;COND;PL;2;LGSPEC2
cointoier	cointoiez	V;SBJV;PL;2;PRS
reserver	reserveroys	V;COND;SG;2;LGSPEC2
cointoier	cointoie	V;IND;SG;1;PRS
adapter	adapterois	V;COND;SG;1;LGSPEC1
esbaucher	esbauches	V;IND;SG;2;PRS
cacher	cachasses	V;IPFV;SBJV;SG;2;PST
desborder	desbordyons	V;IPFV;IND;PL;1;PST;LGSPEC2
auser	ausasses	V;IPFV;SBJV;SG;2;PST
payer	payez	V;SBJV;PL;2;PRS
destourner	destournassions	V;IPFV;SBJV;PL;1;PST
mortifier	mortifier	V;NFIN
esloigner	esloigneroit	V;COND;SG;3;LGSPEC1
emboucher	embouchoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
couster	coustast	V;IPFV;SBJV;SG;3;PST
employer	employent	V;IND;PL;3;PRS
merveiller	merveillez	V;IND;PL;2;PRS
porter	porteryez	V;COND;PL;2;LGSPEC2
foetter	foettas	V;PFV;IND;SG;2;PST
conseiller	conseilloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
haster	hasterois	V;COND;SG;1;LGSPEC1
prester	prestoys	V;IPFV;IND;SG;1;PST;LGSPEC2
aloser	alosez	V;IND;PL;2;PRS
interpreter	interpreter	V;NFIN
recouvrer	recouvrerois	V;COND;SG;2;LGSPEC1
accompaigner	accompaigniez	V;IPFV;IND;PL;2;PST;LGSPEC1
mouscher	mouschoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
recouvrer	recouvrer	V;NFIN
desmettre	desmettions	V;IPFV;IND;PL;1;PST
alimenter	alimenteroys	V;COND;SG;2;LGSPEC2
traveillier	traveilles	V;SBJV;SG;2;PRS
exposer	exposeryons	V;COND;PL;1;LGSPEC2
saulver	saulve	V;IMP;SG;2
preferer	preferasses	V;IPFV;SBJV;SG;2;PST
souspirer	souspireroys	V;COND;SG;1;LGSPEC2
haittier	haittent	V;SBJV;PL;3;PRS
pocher	pocheroyent	V;COND;PL;3;LGSPEC2
escouter	escoutasmes	V;PFV;IND;PL;1;PST
gangler	ganglez	V;IND;PL;2;PRS
iurer	iurassiez	V;IPFV;SBJV;PL;2;PST
navrer	navrerez	V;IND;PL;2;FUT
desister	desisteroys	V;COND;SG;1;LGSPEC2
fiancer	fianceroys	V;COND;SG;1;LGSPEC2
habiter	habiteriez	V;COND;PL;2;LGSPEC1
deliberer	delibererois	V;COND;SG;2;LGSPEC1
cerchier	cerchierois	V;COND;SG;2;LGSPEC1
peser	peserions	V;COND;PL;1;LGSPEC1
haittier	haittieray	V;IND;SG;1;FUT;LGSPEC2
espoventer	espoventerons	V;IND;PL;1;FUT
baisler	baisle	V;SBJV;SG;1;PRS
deschevaucher	deschevaucheroient	V;COND;PL;3;LGSPEC1
iurer	iurez	V;SBJV;PL;2;PRS
resumer	resumerai	V;IND;SG;1;FUT;LGSPEC1
employer	employez	V;IND;PL;2;PRS
effronter	effronteryez	V;COND;PL;2;LGSPEC2
preparer	prepare	V;SBJV;SG;3;PRS
esternuer	esternuerez	V;IND;PL;2;FUT
avoyr	aurons	V;IND;PL;1;FUT
contribuer	contribuoient	V;IPFV;IND;PL;3;PST;LGSPEC1
robber	robberez	V;IND;PL;2;FUT
accomplir	accomplis	V;PFV;IND;SG;2;PST
renommer	renommes	V;SBJV;SG;2;PRS
proffiter	proffitons	V;IMP;PL;1
achever	acheveront	V;IND;PL;3;FUT
tesmoigner	tesmoigne	V;IMP;SG;2
