учитель	учителензонды	N;HUM;DAT;PL;PSS3S;LGSPEC1
пьеса	пьесадонза	N;ABL;SG;PSS3S;LGSPEC1
потенциал	потенциалонь	N;GEN;SG;LGSPEC1
надзор	надзоронь	N;GEN;SG;LGSPEC1
синдемс	синдевсть	V;PL;3;PST;TR;PASS
тапоркс	тапорксне	N;NOM;DEF;PL
мастор	масторстонга	N;IN+ABL;SG;LGSPEC_AMP
ванондомс	ванондат	V;SG;2;TR
прважамс	прважавихть	V;PL;3;TR;PASS;LGSPEC1
кяжи	кяжиян	ADJ;SG;1
вера	верась	N;NOM;DEF;SG;LGSPEC1
поремс	порендеви	V;SG;3;TR;PASS
ранения	ранениянзон	N;GEN;PL;PSS3S;LGSPEC1
грамотнай	грамотнайста	ADJ;IN+ABL;SG;LGSPEC1
подвиг	подвигть	N;GEN;DEF;SG;LGSPEC1
фотография	фотография	N;NOM;SG;LGSPEC1
лефкс	лефкс	N;HUM;NOM;SG
пинге	пингтот	N;ABL;SG;PSS2S
варя	варясь	N;NOM;DEF;SG
азорава	азоравасна	N;HUM;NOM;SG;PSS3P
ковол	коволхне	N;NOM;DEF;PL
инвалид	инвалиттненди	N;HUM;DAT;DEF;PL;LGSPEC1
шары	шарысь	N;NOM;DEF;SG
студия	студиять	N;GEN;DEF;SG;LGSPEC1
сргоземс	сргозьфтеволь	V;SG;3;RMT;CAUS;PASS
райцентра	райцентратнень	N;GEN;PL;PSS2S;LGSPEC1
токарь	токарти	N;HUM;DAT;DEF;SG;LGSPEC1
поремс	порьф	V.PTCP;PST;TR
шаштомс	шаштсть	V;AC3;IMP;PL;2;INTR
пяшкодемс	пяшкотькшнян	V;SG;1;TR
удомс	удомс	V;NFIN;TR
репетиция	репетицияда	N;ABL;SG;LGSPEC1
зерновой	зерновой	ADJ;LGSPEC1
диск	дисконц	N;GEN;SG;PSS3S;LGSPEC1
филолог	филолог	N;HUM;NOM;SG;LGSPEC1
благодарность	благодарностть	N;NOM;PL;LGSPEC1
туста	тустста	ADJ;IN+ABL;SG
приёмнай	приемнаезонза	ADJ;IN+ALL;SG;PSS3S;LGSPEC1
студия	студиясонк	N;IN+ESS;SG;PSS1P;LGSPEC1
садик	садикнень	N;GEN;DEF;PL;LGSPEC1
севернай	севернайста	ADJ;IN+ABL;SG;LGSPEC1
касомс	касонды	V;SG;3;INTR
нярьхкамаз	нярьхкамаснень	N;GEN;PL;PSS1S
положения	положениянц	N;GEN;SG;PSS3S;LGSPEC1
очка	очкт	N;NOM;PL;LGSPEC1
кемокстамс	кемокстафтольхть	V;PL;3;RMT;CAUS
летькомомс	летькомф	V.PTCP;PST;INTR
атяпине	атяпинесь	N;HUM;NOM;DEF;SG
советник	советниконь	N;HUM;GEN;SG;LGSPEC1
тонадомс	тонаткшнемс	V;NFIN;INTR
перга	пергаста	N;IN+ABL;SG;LGSPEC1
компост	компостть	N;GEN;DEF;SG;LGSPEC1
гордость	гордостец	N;NOM;SG;PSS3S;LGSPEC1
юкстамс	юкстафтольхть	V.PTCP;NOM;PL;3;PST;TR
потяфты	потяфты	N;HUM;NOM;SG
руз	рузан	N;HUM;SG;1;LGSPEC1
кенеремс	кенерьфнень	V.PTCP;GEN;PL;PSS1S;PST;TR
рецепт	рецептонь	N;GEN;SG;LGSPEC1
туфтал	туфталда	N;ABL;SG
указания	указаниянзон	N;GEN;PL;PSS3S;LGSPEC1
ушеткс	ушетксс	N;IN+ALL;SG
уй	уель	N;SG;3;PST
петрушка	петрушкань	N;GEN;SG;LGSPEC1
святой	святойхнень	ADJ;GEN;PL;PSS1S;LGSPEC1
кальдяв	кальдяфненьге	N;GEN;PL;LGSPEC_AMP;PSS1S
час	час	N;NOM;SG;LGSPEC1
кооператив	кооперативкс	N;TRANS;SG;LGSPEC1
аймак	аймакснон	N;GEN;SG;PSS3P
литературовед	литературоветт	N;HUM;NOM;PL;LGSPEC1
забота	заботантень	N;GEN;SG;PSS2P;LGSPEC1
питания	питаниятнень	N;GEN;DEF;PL;LGSPEC1
яфодемс	яфодезь	V;AC3;PL;3;TR
эвондамс	эвондафтсть	V;AC3;IMP;PL;2;CAUS
васта	вастозост	N;IN+ALL;SG;PSS3P
промысла	промыслатнень	N;GEN;DEF;PL;LGSPEC1
крхкалгодомс	крхкалгофтсыне	V;AC3P;SG;3;CAUS
заседания	заседанияда	N;ABL;SG;LGSPEC1
ётамс	етафтсайть	V;AC3P;SG;2;CAUS
пионер	пионерсь	N;HUM;NOM;DEF;SG;LGSPEC1
судья	судьятне	N;HUM;NOM;DEF;PL;LGSPEC1
секретарь	секретаренди	N;HUM;DAT;SG;LGSPEC1
уровень	уроветтненди	N;DAT;DEF;PL;LGSPEC1
блог	блоксь	N;NOM;DEF;SG;LGSPEC1
дивандамс	дивандакшнян	V;SG;1;INTR;LGSPEC1
пов	пофтада	N;PL;2
арт-салон	арт-салонца	N;IN+ESS;SG;LGSPEC1
гастямс	гастяф	V.PTCP;PST;TR
нолдамс	нолдатама	V;PL;1;TR
комиссия	комиссияса	N;IN+ESS;SG;LGSPEC1
лем	лемонкса	N;CAUSV;SG
тонадомс	тонафтоволь	V;SG;3;RMT;CAUS;PASS
ансамбль	ансамбленьке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
республика	республиказонк	N;IN+ALL;SG;PSS1P;LGSPEC1
пря	пряста	N;IN+ABL;SG
перьф	перьфсь	N;NOM;DEF;SG
номинация	номинацияда	N;ABL;SG;LGSPEC1
процесс	процессть	N;GEN;DEF;SG;LGSPEC1
козяши	козяшиста	N;IN+ABL;SG
курькстомс	курькста	V;NEG;INTR
сахар	сахар	N;NOM;SG;LGSPEC1
няфтемс	няфтьф	V.PTCP;PST;TR
тумс	тусть	V;AC3;PL;2;INTR
дуган	дуганонзон	N;HUM;GEN;PL;PSS3S
лизинг	лизинг	N;NOM;SG;LGSPEC1
сярядемс	сярятьфонза	V.PTCP;NOM;PL;PSS3S;PST;INTR
канкс	канксонцка	N;GEN;SG;LGSPEC_AMP;PSS3S
пяяремс	пяярихть	V;PL;3;INTR
кемокстамс	кемокставсть	V;AC3;IMP;PL;2;TR;PASS
зарплата	зарплатань	N;GEN;SG;LGSPEC1
няемс	няине	V;AC3;SG;1;TR
содамс	содафонцты	V.PTCP;DAT;SG;PSS3S;PST;TR
возямс	возясть	V;AC3;PL;2;INTR;LGSPEC1
сяське	сяськть	N;HUM;GEN;DEF;SG
исповедь	исповедсь	N;NOM;DEF;SG;LGSPEC1
гармоният	гармонияса	N;IN+ESS;SG;LGSPEC1
юбилей	юбилейда	N;ABL;SG;LGSPEC1
кержи	кержи	ADJ
союзник	союзниконзон	N;HUM;GEN;PL;PSS3S;LGSPEC1
модернизация	модернизациясна	N;NOM;SG;PSS3P;LGSPEC1
репертуар	репертуароц	N;NOM;SG;PSS3S;LGSPEC1
тренер	тренеронтень	N;HUM;GEN;SG;PSS2P;LGSPEC1
содамс	содафсь	V.PTCP;NOM;DEF;SG;PST;TR
цемент	цемент	N;NOM;SG;LGSPEC1
мяндемс	мянтьфт	V.PTCP;NOM;PL;PST;TR
мумс	мусть	V;PL;3;PST;TR
сиволь	сиволенди	N;DAT;SG
открытия	открытиятнень	N;GEN;PL;PSS2S;LGSPEC1
рекомендация	рекомендациятненди	N;DAT;PL;PSS2S;LGSPEC1
музыковед	музыковеттне	N;HUM;NOM;DEF;PL;LGSPEC1
шавомс	шавса	V;AC3S;SG;1;TR
поздравления	поздравлениятнень	N;GEN;PL;PSS2S;LGSPEC1
азомс	азондоманьке	V;AC1;SG;LGSPEC_AMP;3;TR
работа	работаса	N;IN+ESS;SG;LGSPEC1
касомс	касфтыне	V;AC3;SG;1;CAUS
судендамс	судендать	V;SG;2;PST;TR;LGSPEC1
слава	славац	N;NOM;SG;PSS3S;LGSPEC1
корреспонденция	корреспонденциянзон	N;GEN;PL;PSS3S;LGSPEC1
сосуд	сосуттнень	N;GEN;PL;PSS2S;LGSPEC1
политсовет	политсоветть	N;GEN;DEF;SG;LGSPEC1
пандомс	пандсак	V;AC3S;SG;2;TR
лядыкс	лядыкс	ADJ
площадка	площадкась	N;NOM;DEF;SG;LGSPEC1
кадомс	кадоль	V;SG;3;RMT;TR
водопровод	водопроводса	N;IN+ESS;SG;LGSPEC1
мор	моронза	N;NOM;PL;PSS3S
форма	форматненди	N;DAT;DEF;PL;LGSPEC1
сод	содан	N;SG;1
метра	метрат	N;NOM;PL;LGSPEC1
ресурс	ресурсонь	N;GEN;SG;LGSPEC1
район	районцьке	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
потамс	потамс	V;NFIN;INTR
ведь	ведьсот	N;IN+ESS;SG;PSS2S
озамс	озафнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
поликлиника	поликлиникаса	N;IN+ESS;SG;LGSPEC1
пакш	пакшнень	N;GEN;PL;PSS1S
комсомол	комсомолть	N;GEN;DEF;SG;LGSPEC1
пракста	пракстатне	N;NOM;PL;PSS2S
предприниматель	предпринимателян	N;HUM;SG;1;LGSPEC1
тяштемс	тяштьфоль	V.PTCP;SG;3;PST;TR
вешемс	вешить	V;AC3;SG;2;TR
пондамс	пондаф	V.PTCP;PST;TR
шарфтомс	шарфтан	V;SG;1;TR
пялемс	пялесть	V;PL;3;PST;TR
старт	стартонь	N;GEN;SG;LGSPEC1
пялеве	пялевес	N;IN+ALL;SG
пона	понатнень	N;GEN;PL;PSS2S
финно-угровед	финно-угроведонь	N;HUM;GEN;SG;LGSPEC1
кеворемс	кеворсь	V;SG;3;PST;INTR
заказ	заказонь	N;GEN;SG;LGSPEC1
локсти	локсти	N;HUM;NOM;SG
переработка	переработкаса	N;IN+ESS;SG;LGSPEC1
сирень	сиретнень	N;GEN;PL;PSS1S;LGSPEC1
венгра	венгратне	N;HUM;NOM;PL;PSS2S;LGSPEC1
корхтамс	корхтав	V;NEG;TR;PASS
кукуруза	кукурузась	N;NOM;DEF;SG;LGSPEC1
шуфта	шуфттнень	N;GEN;DEF;PL
кячказ	кячкаст	N;NOM;PL
щамс	щатядязь	V;AC2;PL;1;TR
офис	офисозонза	N;IN+ALL;SG;PSS3S;LGSPEC1
аттракцион	аттракциоттне	N;NOM;PL;PSS2S;LGSPEC1
штамс	штасть	V;AC3;IMP;PL;2;TR
ёрдамс	ёрдафт	V.PTCP;NOM;PL;PST;TR
материал	материалозти	N;DAT;SG;PSS1S;LGSPEC1
мумс	мумс	V;NFIN;TR
судендамс	судендафсь	V.PTCP;NOM;DEF;SG;PST;TR;LGSPEC1
горелка	горелкатнень	N;GEN;PL;PSS2S;LGSPEC1
уезд	уезттненди	N;DAT;DEF;PL;LGSPEC1
тренировандамс	тренировандай	V;SG;3;TR;LGSPEC1
ЖКХ	жкх-нь	N;GEN;SG;LGSPEC1
старец	старецти	N;HUM;DAT;DEF;SG;LGSPEC1
признак	признакнень	N;GEN;DEF;PL;LGSPEC1
сяськомс	сяськихть	V;PL;3;TR
шукштору	шукштору	N;NOM;SG
пруд	прудсь	N;NOM;DEF;SG;LGSPEC1
кафедра	кафедраста	N;IN+ABL;SG;LGSPEC1
угол	уголфтома	N;PRIV;SG;LGSPEC1
приметамс	приметаме	V;PL;1;PST;TR;LGSPEC1
варя	варятнень	N;GEN;PL;PSS2S
пшкядемс	пшкядихть	V;PL;3;TR
пуня	пуняда	N;ABL;SG
марамс	марат	V;SG;2;TR
вельхкс	вельхксське	N;NOM;DEF;SG;LGSPEC_AMP
кундамс	кундаль	V;SG;3;RMT;TR
экскурсовод	экскурсовоттненди	N;HUM;DAT;DEF;PL;LGSPEC1
вельхтямс	вельхтяк	V;IMP;SG;2;TR
химик	химик	N;HUM;NOM;SG;LGSPEC1
сеель	сееленьке	N;HUM;NOM;SG;PSS1P
структура	структурасонза	N;IN+ESS;SG;PSS3S;LGSPEC1
тяемс	тяфтанга	V;SG;LGSPEC_AMP;1;CAUS
кузнець	кузнецне	N;HUM;NOM;PL;PSS1S;LGSPEC1
тише	тишети	N;DAT;DEF;SG
сргоземс	сргозьфтсь	V;SG;3;PST;CAUS
боец	боецт	N;HUM;NOM;PL;LGSPEC1
лажадомс	лажаткшнесь	V;SG;3;PST;INTR
запас	запас	N;NOM;SG;LGSPEC1
друг	друг	N;HUM;NOM;SG;LGSPEC1
прважамс	прважак	V;AC3;IMP;SG;2;TR;LGSPEC1
сборнай	сборнаень	N;GEN;SG;LGSPEC1
нерва	нерва	N;NOM;SG;LGSPEC1
паёк	паек	N;NOM;SG;LGSPEC1
шукштору	шукшторукст	N;TRANS;SG;PSS2S
инфраструктура	инфраструктурань	N;GEN;SG;LGSPEC1
фамилия	фамилияда	N;ABL;SG;LGSPEC1
повомс	повонды	V;SG;3;INTR
устав	уставти	N;DAT;DEF;SG;LGSPEC1
социолог	социолокнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
таргай	таргайть	N;HUM;GEN;DEF;SG
лем	лемсь	N;NOM;DEF;SG
видеоролик	видеороликста	N;IN+ABL;SG;LGSPEC1
инвестиция	инвестицияда	N;ABL;SG;LGSPEC1
сотрудник	сотрудниконц	N;HUM;GEN;SG;PSS3S;LGSPEC1
политрук	политрукнень	N;HUM;GEN;DEF;PL;LGSPEC1
ётамс	етафтфста	V.PTCP;IN+ABL;SG;PST;CAUS
секс	сексеть	N;GEN;DEF;SG;LGSPEC1
производственнай	производственнай	ADJ;LGSPEC1
пинге	пингти	N;DAT;DEF;SG
итог	итокненди	N;DAT;DEF;PL;LGSPEC1
тёждялгодомс	тёждялготкшнихть	V;PL;3;INTR
лямбе	лямбоснон	N;GEN;SG;PSS3P
редактор	редактороньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
одёжат	одёжатнень	N;GEN;DEF;PL;LGSPEC1
приём	приёпне	N;NOM;PL;PSS1S;LGSPEC1
телетайп	телетайпсь	N;NOM;DEF;SG;LGSPEC1
возможность	возможностеньконь	N;GEN;SG;PSS1P;LGSPEC1
член	членти	N;DAT;DEF;SG;LGSPEC1
потма	потмова	N;PROL;SG
ответ	ответтне	N;NOM;PL;PSS2S;LGSPEC1
потя	потят	N;NOM;PL
сргоземс	сргозькшнян	V;SG;1;INTR
раздел	разделсь	N;NOM;DEF;SG;LGSPEC1
покой	покойсна	N;NOM;SG;PSS3P;LGSPEC1
критик	критиксь	N;HUM;NOM;DEF;SG;LGSPEC1
усадьба	усадьбатнень	N;GEN;DEF;PL;LGSPEC1
лавра	лаврась	N;NOM;DEF;SG;LGSPEC1
ёжуши	ёжушинц	N;GEN;SG;PSS3S
пизел	пизелхт	N;NOM;PL
площадь	площаттнень	N;GEN;PL;PSS2S;LGSPEC1
сборник	сборниксост	N;IN+ESS;SG;PSS3P;LGSPEC1
пуромкс	пуромксонза	N;NOM;PL;PSS3S
марш	маршть	N;GEN;DEF;SG
функция	функцияснон	N;GEN;SG;PSS3P;LGSPEC1
весялгодомс	весялгодсть	V;PL;3;PST;INTR;LGSPEC1
тяштемс	тяштьса	V;AC3S;SG;1;TR
полка	полкста	N;IN+ABL;SG;LGSPEC1
лисемс	лиселень	V;SG;1;RMT;INTR
депо	депоть	N;GEN;DEF;SG;LGSPEC1
книга	книганьке	N;NOM;SG;PSS1P;LGSPEC1
духт	духнень	N;GEN;DEF;PL;LGSPEC1
результат	результаттненди	N;DAT;DEF;PL;LGSPEC1
лук	лука	N;PROL;SG;LGSPEC1
батальон	батальону	N;AT+ALL;SG;LGSPEC1
араламс	аралафт	V;NEG;CAUS
шовамс	шовасть	V;AC3;PL;2;TR
тапоркс	тапоркст	N;NOM;PL
психолог	психологокс	N;HUM;TRANS;SG;LGSPEC1
ушедомс	ушеткшнесть	V;AC3;IMP;PL;2;TR
столовай	столовай	N;NOM;SG;LGSPEC1
касомс	касоме	V;PL;1;PST;INTR
афсатыкс	афсатыксоньконь	N;GEN;SG;PSS1P
зарплата	зарплатазе	N;NOM;SG;PSS1S;LGSPEC1
спорт	спортти	N;DAT;DEF;SG;LGSPEC1
кочкамс	кочкальхть	V;PL;3;RMT;TR
юбиляр	юбиляр	N;HUM;NOM;SG;LGSPEC1
ушедомс	ушеды	V;SG;3;TR
тон	тонат	N;SG;2;LGSPEC1
замечания	замечаниятнень	N;GEN;PL;PSS2S;LGSPEC1
пов	поволь	N;SG;3;PST
боец	боецненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
цильф	цильфне	N;NOM;PL;PSS1S
душ	душть	N;GEN;DEF;SG;LGSPEC1
робот	роботтненди	N;DAT;DEF;PL;LGSPEC1
приоритет	приоритеттне	N;NOM;DEF;PL;LGSPEC1
мора	морозост	N;IN+ALL;SG;PSS3P
почф	почфонь	N;GEN;SG
солистка	солистканц	N;HUM;GEN;SG;PSS3S;LGSPEC1
профессионал	профессионалхненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
государства	государстваса	N;IN+ESS;SG;LGSPEC1
обеспечендамс	обеспечендамс	V;NFIN;TR;LGSPEC1
активность	активностьснон	N;GEN;SG;PSS3P;LGSPEC1
кенеремс	кенерьфнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
тише	тишеть	N;GEN;DEF;SG
экран	экранцта	N;IN+ABL;SG;LGSPEC1
мадомс	мадольхть	V;PL;3;RMT;INTR
эльбядемс	эльбядсть	V;AC3;PL;2;INTR
заявления	заявленияда	N;ABL;SG;LGSPEC1
ушедомс	ушедса	V;AC3S;SG;1;TR
принцип	принципс	N;IN+ALL;SG;LGSPEC1
мора	моронц	N;GEN;SG;PSS3S
кавалер	кавалер	N;HUM;NOM;SG;LGSPEC1
согласнай	согласнайхне	ADJ;NOM;PL;PSS1S;LGSPEC1
организация	организацияв	N;AT+ALL;SG;LGSPEC1
учреждения	учрежденияста	N;IN+ABL;SG;LGSPEC1
антибиотик	антибиотик	N;NOM;SG;LGSPEC1
философ	философнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
лувомс	лувса	V;AC3S;SG;1;TR
мала	малакс	ADJ;TRANS;SG
совещания	совещаниясь	N;NOM;DEF;SG;LGSPEC1
среда	среда	N;NOM;SG;LGSPEC1
бславамс	бславафолень	V.PTCP;SG;1;PST;TR;LGSPEC1
вольер	вольерхнень	N;GEN;PL;PSS1S;LGSPEC1
фрукта	фруктада	N;ABL;SG;LGSPEC1
гражданин	гражданиттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
категория	категорияснон	N;GEN;SG;PSS3P;LGSPEC1
судьба	судьбанц	N;GEN;SG;PSS3S;LGSPEC1
потенциал	потенциал	N;NOM;SG;LGSPEC1
шарфтомс	шарфтомс	V;NFIN;TR
котф	котфонди	N;DAT;SG
сайт	сайтоньконь	N;GEN;SG;PSS1P;LGSPEC1
инжи	инжида	N;HUM;ABL;SG
ляцемс	ляцендельхть	V;PL;3;RMT;TR
рецепт	рецептс	N;IN+ALL;SG;LGSPEC1
книга	книгатнень	N;GEN;DEF;PL;LGSPEC1
рацион	рационти	N;DAT;DEF;SG;LGSPEC1
содамс	содафснон	V.PTCP;GEN;SG;PSS3P;PST;TR
седь	седьге	N;PROL;SG
стенд	стенттненди	N;DAT;DEF;PL;LGSPEC1
ульця	ульцяванк	N;PROL;SG;PSS1P;LGSPEC1
свадьба	свадьбастонза	N;IN+ABL;SG;PSS3S;LGSPEC1
инвалид	инвалидоньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
вуз	вузда	N;ABL;SG;LGSPEC1
кемокстамс	кемокстафты	V;SG;3;CAUS
государственность	государственности	N;AT+ALL;SG;LGSPEC1
сялондомс	сялондыхть	V;PL;3;INTR
варжамс	варжак	V;AC3;IMP;SG;2;TR
форум	форумть	N;GEN;DEF;SG;LGSPEC1
информация	информациятнень	N;GEN;PL;PSS2S;LGSPEC1
лазкс	лазкснень	N;GEN;PL;PSS1S
жалоба	жалобаснон	N;GEN;SG;PSS3P;LGSPEC1
офис	офис	N;NOM;SG;LGSPEC1
киза	кизостост	N;IN+ABL;SG;PSS3P
тюри	тюрихть	N;HUM;GEN;DEF;SG
кодваста	кодвастса	N;IN+ESS;SG
мор	морозост	N;IN+ALL;SG;PSS3P
маладомс	маладонь	V;SG;1;PST;INTR
розь	розтненди	N;DAT;DEF;PL
пря	пряти	N;DAT;DEF;SG
пакш	пакшсь	N;NOM;DEF;SG
кенеремс	кенерькшнек	V;IMP;SG;2;INTR
судендамс	судендай	V;SG;3;TR;LGSPEC1
нола	ноладонга	ADJ;ABL;SG;LGSPEC_AMP
авария	авариятне	N;NOM;PL;PSS2S;LGSPEC1
значения	значениянь	N;GEN;SG;LGSPEC1
минута	минутатне	N;NOM;PL;PSS2S;LGSPEC1
кума	кумават	N;HUM;PROL;SG;PSS2S;LGSPEC1
пе	пекс	N;TRANS;SG
самогон	самогон	N;NOM;SG;LGSPEC1
полномочия	полномочиятне	N;NOM;DEF;PL;LGSPEC1
тумс	туф	V.PTCP;PST;INTR
мазыши	мазышиц	N;NOM;SG;PSS3S
пейзаж	пейзажсь	N;NOM;DEF;SG;LGSPEC1
усадьба	усадьбань	N;GEN;SG;LGSPEC1
воляши	воляшинцты	N;DAT;SG;PSS3S;LGSPEC1
озамс	озафтфоль	V.PTCP;SG;3;PST;CAUS
экспедиция	экспедициясь	N;NOM;DEF;SG;LGSPEC1
апрякамс	апрякакшнезе	V;AC3S;SG;3;TR;LGSPEC1
кельгомс	кельгови	V;SG;3;TR;PASS
орден	ордеттне	N;NOM;DEF;PL;LGSPEC1
кяше	кяшеть	N;GEN;DEF;SG
линия	линиянь	N;GEN;SG;LGSPEC1
чаша	чашась	N;NOM;DEF;SG;LGSPEC1
сиредемс	сиредихть	V;PL;3;INTR
азкс	азкста	N;ABL;SG
кели	келидонга	ADJ;ABL;SG;LGSPEC_AMP
работа	работадот	N;ABL;SG;PSS2S;LGSPEC1
унок	унок	N;HUM;NOM;SG;LGSPEC1
страна	странанди	N;DAT;SG;LGSPEC1
шина	шинатне	N;NOM;DEF;PL;LGSPEC1
хозяйства	хозяйстваса	N;IN+ESS;SG;LGSPEC1
комната	комнатаста	N;IN+ABL;SG;LGSPEC1
редактор	редактороц	N;HUM;NOM;SG;PSS3S;LGSPEC1
корянь	коряттне	N;NOM;PL;PSS2S;LGSPEC1
танад	танадс	N;IN+ALL;SG
кядь	кядь	N;NOM;SG
потя	потяса	N;IN+ESS;SG
потма	потмосонк	N;IN+ESS;SG;PSS1P
подкормка	подкормкаса	N;IN+ESS;SG;LGSPEC1
промоз	промозсна	N;NOM;SG;PSS3P
сянгяря	сянгярят	ADJ;NOM;PL
мигрант	мигранттнень	N;HUM;GEN;DEF;PL;LGSPEC1
железа	железань	N;GEN;SG;LGSPEC1
журнал	журнал	N;NOM;SG;LGSPEC1
МВД	мвд-са	N;IN+ESS;SG;LGSPEC1
мощность	мощностень	N;GEN;SG;LGSPEC1
еврей	еврейхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
портной	портноель	N;HUM;SG;3;PST;LGSPEC1
квартира	квартират	N;NOM;PL;LGSPEC1
воляши	воляшити	N;DAT;DEF;SG;LGSPEC1
эцемс	эцекшне	V;NEG;TR
государственность	государственностьснон	N;GEN;SG;PSS3P;LGSPEC1
моль	молелеть	N;HUM;SG;2;PST;LGSPEC1
аделамс	аделасть	V;PL;3;PST;TR
шарфтомс	шарфтфоль	V.PTCP;SG;3;PST;TR
ляды	лядыкс	ADJ;TRANS;SG
азомс	азфснон	V.PTCP;GEN;SG;PSS3P;PST;TR
эвфемизма	эвфемизматнень	N;GEN;PL;PSS2S;LGSPEC1
пиндолгодомс	пиндолгофтсы	V;AC3S;SG;3;CAUS
тошна	тошна	N;NOM;SG;LGSPEC1
ши	шит	N;NOM;PL
лефкс	лефкснень	N;HUM;GEN;DEF;PL
старец	старецне	N;HUM;NOM;DEF;PL;LGSPEC1
вакс	вакссонт	N;IN+ESS;SG;PSS2P
кячказ	кячказнень	N;GEN;PL;PSS1S
мярьгомс	мярьголь	V;SG;3;RMT;TR
баярава	баяраватне	N;HUM;NOM;DEF;PL;LGSPEC1
тапарямс	тапарякшнесь	V;SG;3;PST;TR
полоса	полосатненди	N;DAT;PL;PSS2S;LGSPEC1
материал	материалонц	N;GEN;SG;PSS3S;LGSPEC1
шоколад	шоколадса	N;IN+ESS;SG;LGSPEC1
бславамс	бславанзе	V;AC2S;SG;3;TR;LGSPEC1
лям	лямсь	N;NOM;DEF;SG
щамс	щафтозе	V;AC3S;SG;3;CAUS
простиндамс	простиндамак	V;AC1;IMP;SG;2;TR;LGSPEC1
переработка	переработкань	N;GEN;SG;LGSPEC1
кизефкс	кизефкснень	N;GEN;PL;PSS1S
кизефкс	кизефксонц	N;GEN;SG;PSS3S
миле	миле	N;NOM;SG
ацам	ацамат	N;SG;2
тев	тевсонга	N;IN+ESS;SG;LGSPEC_AMP
отношения	отношениясна	N;NOM;SG;PSS3P;LGSPEC1
сочельник	сочельник	N;NOM;SG;LGSPEC1
поздравления	поздравленияньконь	N;GEN;SG;PSS1P;LGSPEC1
сяськомс	сяськондевольхть	V;PL;3;RMT;TR;PASS
поляна	полянав	N;AT+ALL;SG;LGSPEC1
ава	авацень	N;HUM;GEN;SG;PSS2S
метра	метрась	N;NOM;DEF;SG;LGSPEC1
нешке	нешкненди	N;DAT;PL;PSS1S
венемомс	венемф	V.PTCP;PST;INTR
сельмоведь	сельмоведензон	N;GEN;PL;PSS3S
ласькомс	ласьки	V;SG;3;INTR
западнай	западнай	ADJ;LGSPEC1
итог	итогсна	N;NOM;SG;PSS3P;LGSPEC1
мода	модав	N;AT+ALL;SG;LGSPEC1
строчка	строчкань	N;GEN;SG;LGSPEC1
вешендема	вешендемаса	N;IN+ESS;SG
республика	республикантень	N;GEN;SG;PSS2P;LGSPEC1
нешке	нешконьке	N;GEN;SG;LGSPEC_AMP
подростка	подростка	N;HUM;NOM;SG;LGSPEC1
пчкамс	пчкафта	V;NEG;CAUS
шкаф	шкафсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
каталог	каталогу	N;AT+ALL;SG;LGSPEC1
ковол	коволста	N;IN+ABL;SG
пяште	пяштень	N;GEN;SG
автозавод	автозаводста	N;IN+ABL;SG;LGSPEC1
исследования	исследованиять	N;GEN;DEF;SG;LGSPEC1
пеель	пеелец	N;HUM;NOM;SG;PSS3S
организация	организацияса	N;IN+ESS;SG;LGSPEC1
наречия	наречият	N;NOM;PL;LGSPEC1
радива	радива	N;NOM;SG;LGSPEC1
лиемс	лиендень	V;SG;1;PST;INTR
бункер	бункерть	N;GEN;DEF;SG;LGSPEC1
правила	правилац	N;NOM;SG;PSS3S;LGSPEC1
канал	каналонзон	N;GEN;PL;PSS3S;LGSPEC1
инекуй	инекуйхнень	N;HUM;GEN;PL;PSS1S
пичефкс	пичефксоньконь	N;GEN;SG;PSS1P
прибавамс	прибавась	V;SG;3;PST;TR;LGSPEC1
солдат	солдатське	N;HUM;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
сянгяря	сянгяряти	ADJ;DAT;DEF;SG
содамс	содафтыне	V;AC3;SG;1;CAUS
опыт	опытт	N;NOM;PL;LGSPEC1
ресурс	ресурст	N;NOM;PL;LGSPEC1
обуця	обуцясон	N;IN+ESS;SG;PSS1S;LGSPEC1
епархия	епархиясь	N;NOM;DEF;SG;LGSPEC1
содамс	содафтсть	V;AC3;PL;2;CAUS
олимпиада	олимпиадась	N;NOM;DEF;SG;LGSPEC1
армия	армиятне	N;NOM;PL;PSS2S;LGSPEC1
регистрация	регистрациянц	N;GEN;SG;PSS3S;LGSPEC1
гальця	гальцят	N;NOM;PL;LGSPEC1
потямс	потяйне	V;AC3;SG;1;TR
срадомс	срадсь	V;SG;3;PST;INTR
член	членть	N;GEN;DEF;SG;LGSPEC1
бригада	бригада	N;NOM;SG;LGSPEC1
поздравления	поздравленияса	N;IN+ESS;SG;LGSPEC1
парамс	параса	V;AC3S;SG;1;INTR
корхтамс	корхтаса	V;AC3S;SG;1;TR
пациент	пациенттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
инжи	инжидонза	N;HUM;ABL;SG;PSS3S
нанотехнология	нанотехнологиятне	N;NOM;PL;PSS2S;LGSPEC1
ляды	лядысь	ADJ;NOM;DEF;SG
армян	армян	N;HUM;NOM;SG;LGSPEC1
качества	качестваснон	N;GEN;SG;PSS3P;LGSPEC1
агитбригада	агитбригадась	N;NOM;DEF;SG;LGSPEC1
отвечамс	отвечак	V;IMP;SG;2;TR;LGSPEC1
тумс	тушендсь	V;SG;3;PST;INTR
сеель	сеельхне	N;HUM;NOM;PL;PSS1S
фонд	фондонц	N;GEN;SG;PSS3S;LGSPEC1
сяськомс	сяськи	V;SG;3;TR
мумс	мун	V;SG;1;TR
пачфнема	пачфнемаснон	N;GEN;SG;PSS3P
собор	соборхнень	N;GEN;DEF;PL;LGSPEC1
давол	давол	N;NOM;SG
содамс	содафонтень	V.PTCP;GEN;SG;PSS2P;PST;TR
шиньф	шиньфсна	N;NOM;SG;PSS3P
пар	пархт	N;NOM;PL
музыкант	музыкантокс	N;HUM;TRANS;SG;LGSPEC1
сеель	сеельхнень	N;HUM;GEN;DEF;PL
радиостанция	радиостанциясь	N;NOM;DEF;SG;LGSPEC1
погода	погодаста	N;IN+ABL;SG;LGSPEC1
филолог	филолокненди	N;HUM;DAT;DEF;PL;LGSPEC1
рецензия	рецензиянзон	N;GEN;PL;PSS3S;LGSPEC1
футбол	футболонь	N;GEN;SG;LGSPEC1
руз	рузкска	N;HUM;TRANS;SG;LGSPEC_AMP;LGSPEC1
мазыши	мазышиньке	N;GEN;SG;LGSPEC_AMP
кяшемс	кяшендемс	V;NFIN;TR
пяшкодемс	пяшкотькшнихть	V;PL;3;TR
машты	маштыкс	ADJ;TRANS;SG
цинковай	цинковайхть	ADJ;NOM;PL;LGSPEC1
пужемс	пужфтсы	V;AC3S;SG;3;CAUS
образования	образованиятне	N;NOM;DEF;PL;LGSPEC1
маршрут	маршруттнень	N;GEN;DEF;PL;LGSPEC1
шкайава	шкайавась	N;HUM;NOM;DEF;SG
координатор	координаторхт	N;HUM;NOM;PL;LGSPEC1
продавщица	продавщицать	N;HUM;GEN;DEF;SG;LGSPEC1
пуд	путкс	N;TRANS;SG;LGSPEC1
пси	псиснон	ADJ;GEN;SG;PSS3P
работа	работадон	N;ABL;SG;PSS1S;LGSPEC1
канкс	канксть	N;GEN;DEF;SG
механизатор	механизаторть	N;HUM;GEN;DEF;SG;LGSPEC1
ункс	унксоньке	N;NOM;SG;PSS1P
федерация	федерацияц	N;NOM;SG;PSS3S;LGSPEC1
период	период	N;NOM;SG;LGSPEC1
банк	банка	N;PROL;SG;LGSPEC1
сапоня	сапонятне	N;NOM;PL;PSS2S
дежурства	дежурствать	N;GEN;DEF;SG;LGSPEC1
наречия	наречиятнень	N;GEN;DEF;PL;LGSPEC1
оркестра	оркестрац	N;NOM;SG;PSS3S;LGSPEC1
календамс	календакшнеса	V;AC3S;SG;1;TR;LGSPEC1
заводь	завоттнень	N;GEN;DEF;PL;LGSPEC1
лядыкс	лядыксне	N;NOM;PL;PSS1S
рейс	рейст	N;NOM;PL;LGSPEC1
тёс	тесонь	N;GEN;SG;LGSPEC1
рассказ	расскаснень	N;GEN;PL;PSS1S;LGSPEC1
куля	кулятнень	N;GEN;PL;PSS2S
праздник	праздникстост	N;IN+ABL;SG;PSS3P;LGSPEC1
подростка	подросткатнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
пайге	пайгсь	N;NOM;DEF;SG
сфера	сфератненди	N;DAT;PL;PSS2S;LGSPEC1
ЕГЭ	егэ	N;NOM;SG;LGSPEC1
заря	зарякс	N;TRANS;SG;LGSPEC1
касомс	касфтови	V;SG;3;CAUS;PASS
дата	дататненди	N;DAT;PL;PSS2S;LGSPEC1
пуромкс	пуромксоц	N;NOM;SG;PSS3S
ава	аваньконди	N;HUM;DAT;SG;PSS1P
летопись	летописнень	N;GEN;PL;PSS1S;LGSPEC1
усадьба	усадьбаснон	N;GEN;SG;PSS3P;LGSPEC1
служамс	служамань	V;AC1;SG;3;INTR;LGSPEC1
руководитель	руководительхне	N;HUM;NOM;DEF;PL;LGSPEC1
магия	магияса	N;IN+ESS;SG;LGSPEC1
призывник	призывникт	N;HUM;NOM;PL;LGSPEC1
потямс	потясть	V;AC3;PL;2;TR
зверь	зверьда	N;HUM;ABL;SG;LGSPEC1
прважамс	прважак	V;IMP;SG;2;TR;LGSPEC1
элемент	элементса	N;IN+ESS;SG;LGSPEC1
оператор	операторти	N;HUM;DAT;DEF;SG;LGSPEC1
труба	трубаса	N;IN+ESS;SG;LGSPEC1
гимназия	гимназияньке	N;NOM;SG;PSS1P;LGSPEC1
прибавамс	прибавамс	V;NFIN;TR;LGSPEC1
корхтамс	корхтазень	V;AC3P;SG;3;TR
тялькфтамс	тялькфтав	V;NEG;TR;PASS
лувомс	лувсамак	V;AC1;SG;2;TR
хоровод	хоровоттнень	N;GEN;PL;PSS2S;LGSPEC1
подписчик	подписчикнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
наставник	наставникнень	N;HUM;GEN;DEF;PL;LGSPEC1
кристалл	кристаллса	N;IN+ESS;SG;LGSPEC1
оркестра	оркестраса	N;IN+ESS;SG;LGSPEC1
лисемс	лисьфонь	V.PTCP;GEN;SG;PST;INTR
мярьгомс	мярьгондев	V;NEG;TR;PASS
мудрай	мудрайста	ADJ;IN+ABL;SG;LGSPEC1
озондомс	озонды	V;SG;3;INTR
страховандамс	страховандамс	V;NFIN;TR;LGSPEC1
драма	драмась	N;NOM;DEF;SG;LGSPEC1
кулак	кулак	N;NOM;SG;LGSPEC1
принцесса	принцесса	N;HUM;NOM;SG;LGSPEC1
паломс	палфне	V.PTCP;NOM;DEF;PL;PST;INTR
имож	имож	N;NOM;SG
ранения	ранениянь	N;GEN;SG;LGSPEC1
элемент	элементтнень	N;GEN;PL;PSS2S;LGSPEC1
республика	республиказень	N;GEN;SG;PSS1S;LGSPEC1
велямс	веляфтость	V;AC3;PL;2;CAUS
чуваш	чувашт	N;HUM;NOM;PL
сивомс	сивфть	V.PTCP;GEN;DEF;SG;PST;TR
капа	капань	N;GEN;SG
пионер	пионерхт	N;HUM;NOM;PL;LGSPEC1
киремс	кирьфтама	V.PTCP;PL;1;PST;INTR
пача	пачанень	N;GEN;PL;PSS1S
прогноз	прогнозть	N;GEN;DEF;SG;LGSPEC1
пеже	пежетка	N;NOM;PL;LGSPEC_AMP
сёрма	серманьке	N;GEN;SG;LGSPEC_AMP
пионер	пионеронь	N;HUM;GEN;SG;LGSPEC1
кяль	кялят	N;SG;2
сргоземс	сргозьфтьф	V.PTCP;PST;CAUS
крня	крняста	N;IN+ABL;SG
лиемс	лиеви	V;SG;3;INTR;PASS
васта	вастоцка	N;NOM;SG;LGSPEC_AMP;PSS3S
сюролда	сюролданза	N;NOM;PL;PSS3S
советник	советниксь	N;HUM;NOM;DEF;SG;LGSPEC1
касомс	касфтоме	V;PL;1;PST;CAUS
кирдемс	кирдель	V;SG;3;RMT;TR
маршрут	маршрут	N;NOM;SG;LGSPEC1
университет	университетти	N;DAT;DEF;SG;LGSPEC1
батальон	батальоттненди	N;DAT;PL;PSS2S;LGSPEC1
свалка	свалкав	N;AT+ALL;SG;LGSPEC1
озамс	озатама	V;PL;1;INTR
пьеса	пьесатнень	N;GEN;DEF;PL;LGSPEC1
реформа	реформа	N;NOM;SG;LGSPEC1
котф	котфта	N;ABL;SG
эряй	эряйти	N;HUM;DAT;DEF;SG
ляцемс	ляцеськ	V;AC3;PL;1;TR
сакал	сакалу	N;AT+ALL;SG
аля	алязти	N;HUM;DAT;SG;PSS1S
кельме	кельмоти	ADJ;DAT;DEF;SG
вятемс	вятьк	V;AC3;IMP;SG;2;TR
ризф	ризфоц	N;NOM;SG;PSS3S
тумс	тувода	V;IMP;PL;2;INTR;PASS
укроп	укроп	N;NOM;SG;LGSPEC1
ваннай	ваннайста	N;IN+ABL;SG;LGSPEC1
судьба	судьбацень	N;GEN;SG;PSS2S;LGSPEC1
животноводства	животноводства	N;NOM;SG;LGSPEC1
ума	умастонза	N;IN+ABL;SG;PSS3S
куфтолкс	куфтолкссь	N;NOM;DEF;SG
приоритет	приоритеттнень	N;GEN;DEF;PL;LGSPEC1
лоток	лотокста	N;IN+ABL;SG;LGSPEC1
толмар	толмарть	N;GEN;DEF;SG
пеняцяй	пеняцяйхть	N;HUM;NOM;PL
эзне	эзнетненди	N;DAT;DEF;PL
ярхцамбяль	ярхцамбялезост	N;IN+ALL;SG;PSS3P
няфтемс	няфти	V;SG;3;TR
паломс	палан	V;SG;1;INTR
юго-запад	юго-западть	N;GEN;DEF;SG;LGSPEC1
коня	коняс	N;IN+ALL;SG
модернизация	модернизация	N;NOM;SG;LGSPEC1
азомс	азфстон	V.PTCP;IN+ABL;SG;PSS1S;PST;TR
пильге	пильгс	N;IN+ALL;SG
эвондамс	эвондакшнемс	V;NFIN;INTR
мифология	мифологиятнень	N;GEN;DEF;PL;LGSPEC1
комната	комнатав	N;AT+ALL;SG;LGSPEC1
робот	роботтне	N;NOM;DEF;PL;LGSPEC1
корпус	корпуссонза	N;IN+ESS;SG;PSS3S;LGSPEC1
святой	святойхненди	ADJ;DAT;PL;PSS1S;LGSPEC1
начкомс	начконда	V;NEG;INTR
публикация	публикацияда	N;ABL;SG;LGSPEC1
морамс	мораль	V;SG;3;RMT;TR
пси	псить	ADJ;GEN;DEF;SG
самогон	самогононь	N;GEN;SG;LGSPEC1
обед	обед	N;NOM;SG;LGSPEC1
сирень	сиретнень	N;GEN;DEF;PL;LGSPEC1
черепаха	черепахатне	N;HUM;NOM;DEF;PL;LGSPEC1
газета	газетаснон	N;GEN;SG;PSS3P;LGSPEC1
пуромкс	пуромкссонза	N;IN+ESS;SG;PSS3S
эцемс	эцесак	V;AC3S;SG;2;TR
кяжиямс	кяжиять	V;SG;2;PST;INTR
крхтамс	крхтамс	V;NFIN;TR
кядь	кядень	N;GEN;SG
газета	газетазти	N;DAT;SG;PSS1S;LGSPEC1
шаба	шабазти	N;HUM;DAT;SG;PSS1S
диалект	диалектсь	N;NOM;DEF;SG;LGSPEC1
шиньф	шиньфть	N;GEN;DEF;SG
форум	форумозонк	N;IN+ALL;SG;PSS1P;LGSPEC1
презентация	презентациятне	N;NOM;DEF;PL;LGSPEC1
препарат	препараттнень	N;GEN;DEF;PL;LGSPEC1
месячник	месячниконь	N;GEN;SG;LGSPEC1
пункт	пунктснон	N;GEN;SG;PSS3P;LGSPEC1
личинка	личинкатнень	N;GEN;PL;PSS2S;LGSPEC1
стада	стадань	N;GEN;SG;LGSPEC1
вер	вероц	N;NOM;SG;PSS3S
вешфкс	вешфксненди	N;DAT;PL;PSS1S
опера	операц	N;NOM;SG;PSS3S;LGSPEC1
ассоциация	ассоциацияньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
часовня	часовняц	N;NOM;SG;PSS3S;LGSPEC1
сярятькстомс	сярятькстольхть	V;PL;3;RMT;INTR
тярде	тярдензон	N;GEN;PL;PSS3S
крахмал	крахмалть	N;GEN;DEF;SG;LGSPEC1
щамс	щава	V;NEG;TR;PASS
критик	критик	N;HUM;NOM;SG;LGSPEC1
разработка	разработкатне	N;NOM;DEF;PL;LGSPEC1
тише	тишетнень	N;GEN;DEF;PL
эвондамс	эвондайхть	V;PL;3;INTR
плот	плотонь	N;GEN;SG;LGSPEC1
бурят	бурятне	N;HUM;NOM;PL;PSS1S;LGSPEC1
азомс	азондовсть	V;AC3;PL;2;TR;PASS
конкурсантка	конкурсанткась	N;HUM;NOM;DEF;SG;LGSPEC1
прдамс	прдайне	V;AC3;SG;1;TR
сивомс	сивомс	V;NFIN;TR
шукштору	шукшторуса	N;IN+ESS;SG
лагерь	лагерьса	N;IN+ESS;SG;LGSPEC1
курендамс	курендакшнихть	V;PL;3;TR;LGSPEC1
репертуар	репертуарстонт	N;IN+ABL;SG;PSS2P;LGSPEC1
заявления	заявленияти	N;DAT;DEF;SG;LGSPEC1
подростка	подросткакс	N;HUM;TRANS;SG;LGSPEC1
нумол	нумолхнень	N;HUM;GEN;DEF;PL
васта	васттне	N;NOM;DEF;PL
уча	учакс	N;HUM;TRANS;SG
труд	трудсост	N;IN+ESS;SG;PSS3P;LGSPEC1
объект	объекттне	N;NOM;PL;PSS2S;LGSPEC1
щамс	щафтомс	V;NFIN;CAUS
растения	растениянь	N;GEN;SG;LGSPEC1
универсиада	универсиада	N;NOM;SG;LGSPEC1
прважамс	прважафтолеме	V;PL;1;RMT;CAUS;LGSPEC1
пешкодомс	пешкодсть	V;AC3;PL;2;INTR
тур	турхт	N;NOM;PL;LGSPEC1
сташендомс	сташендовсть	V;AC3;IMP;PL;2;TR;PASS
поздравляндамс	поздравляндасть	V;AC3;PL;2;TR;LGSPEC1
ярхцамбяль	ярхцамбялензон	N;GEN;PL;PSS3S
куцемс	куцевонь	V;SG;1;PST;INTR;PASS
мода	моданьке	N;GEN;SG;LGSPEC_AMP
задача	задачась	N;NOM;DEF;SG;LGSPEC1
значения	значенияс	N;IN+ALL;SG;LGSPEC1
академик	академик	N;HUM;NOM;SG;LGSPEC1
рангомс	рангса	V;AC3S;SG;1;INTR
азорава	азораванцты	N;HUM;DAT;SG;PSS3S
пеель	пеель	N
атказамс	атказайхть	V;PL;3;INTR;LGSPEC1
юр	юроньке	N;GEN;SG;LGSPEC_AMP
зоотехник	зоотехникть	N;HUM;GEN;DEF;SG;LGSPEC1
крандаз	крандасне	N;NOM;DEF;PL
васта	вастсь	N;NOM;DEF;SG
конкурс	конкурст	N;NOM;PL;LGSPEC1
события	событиятне	N;NOM;PL;PSS2S;LGSPEC1
толь	толти	N;DAT;DEF;SG;LGSPEC1
содамс	содафнень	V.PTCP;GEN;PL;PSS1S;PST;TR
эксплуатация	эксплуатацияста	N;IN+ABL;SG;LGSPEC1
возможность	возможносттне	N;NOM;PL;PSS2S;LGSPEC1
лажнамс	лажнамань	V;AC1;SG;3;INTR
дотация	дотациять	N;GEN;DEF;SG;LGSPEC1
райцентра	райцентраса	N;IN+ESS;SG;LGSPEC1
айгор	айгорть	N;HUM;GEN;DEF;SG
лешамс	лешафты	V;SG;3;CAUS
кооператив	кооператифненди	N;DAT;PL;PSS1S;LGSPEC1
афсатыкс	афсатыкстка	N;NOM;PL;LGSPEC_AMP
лавка	лавкаса	N;IN+ESS;SG;LGSPEC1
кувалгодомс	кувалгофтомс	V;NFIN;CAUS
штамс	шталь	V;SG;3;RMT;TR
священник	священникненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
дивандамс	дивандафтсь	V;SG;3;PST;CAUS;LGSPEC1
тёс	тёсста	N;IN+ABL;SG;LGSPEC1
ярхцамс	ярхцан	V;SG;1;TR
уемс	уйфне	V.PTCP;NOM;PL;PSS1S;PST;INTR
конкурсантка	конкурсантканьконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
лазкс	лазксонц	N;GEN;SG;PSS3S
кай	каят	N;SG;2
средства	средствада	N;ABL;SG;LGSPEC1
декан	деканоль	N;HUM;SG;3;PST;LGSPEC1
мемориал	мемориалхне	N;NOM;DEF;PL;LGSPEC1
декан	деканонди	N;HUM;DAT;SG;LGSPEC1
оклад	окладоц	N;NOM;SG;PSS3S;LGSPEC1
предания	преданиять	N;GEN;DEF;SG;LGSPEC1
сокоргодомс	сокоргодат	V;SG;2;INTR
санатория	санаторияса	N;IN+ESS;SG;LGSPEC1
колхоз	колхозфтомонга	N;PRIV;SG;LGSPEC_AMP;LGSPEC1
куя	куясь	ADJ;NOM;DEF;SG
сяськомс	сяськсь	V;SG;3;PST;TR
паломс	палатка	V;SG;LGSPEC_AMP;2;INTR
труд	трудонтень	N;GEN;SG;PSS2P;LGSPEC1
мода	модадост	N;ABL;SG;PSS3P
кучемс	кучте	V;AC2;SG;1;TR
шаба	шабаце	N;HUM;NOM;SG;PSS2S
орта	ортанзон	N;GEN;PL;PSS3S;LGSPEC1
форма	формава	N;PROL;SG;LGSPEC1
алакша	алакшеть	N;GEN;DEF;SG
врач	врачненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
щам	щамоцка	N;NOM;SG;LGSPEC_AMP;PSS3S
кяжиямс	кяжия	V;NEG;INTR
штраф	штраф	N;NOM;SG;LGSPEC1
типография	типографиятка	N;NOM;PL;LGSPEC_AMP;LGSPEC1
нужа	нужатне	N;NOM;PL;PSS2S;LGSPEC1
пуворемс	пуворса	V;AC3S;SG;1;INTR
ваймоси	ваймосихне	N;HUM;NOM;PL;PSS1S
сайт	сайтоньке	N;NOM;SG;PSS1P;LGSPEC1
угол	уголсь	N;NOM;DEF;SG;LGSPEC1
менталитет	менталитетоньке	N;NOM;SG;PSS1P;LGSPEC1
правила	правилафтома	N;PRIV;SG;LGSPEC1
водопровод	водопровод	N;NOM;SG;LGSPEC1
фотография	фотографиянц	N;GEN;SG;PSS3S;LGSPEC1
аделамс	аделасть	V;AC3;IMP;PL;2;TR
веле	велефтома	N;PRIV;SG
альбом	альбомонь	N;GEN;SG;LGSPEC1
давления	давленияснон	N;GEN;SG;PSS3P;LGSPEC1
вакс	ваксозон	N;IN+ALL;SG;PSS1S
портрет	портретонзон	N;GEN;PL;PSS3S;LGSPEC1
лажадомс	лажадонь	V;SG;1;PST;INTR
микрорайон	микрорайононь	N;GEN;SG;LGSPEC1
шавомс	шавоме	V;PL;1;PST;TR
козякодомс	козякодыхть	V;PL;3;INTR
кавалер	кавалерхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
араламс	аралайхть	V;PL;3;TR
скалвай	скалвайсь	N;NOM;DEF;SG
проза	прозась	N;NOM;DEF;SG;LGSPEC1
модамарь	модамарьхнень	N;GEN;PL;PSS1S
билет	билет	N;NOM;SG;LGSPEC1
азор	азорхнень	N;HUM;GEN;PL;PSS1S
подвал	подвалу	N;AT+ALL;SG;LGSPEC1
продовольственнай	продовольственнайхть	ADJ;NOM;PL;LGSPEC1
туткоткс	туткоткс	ADJ
эвондамс	эвондань	V;SG;1;PST;INTR
душман	душматтненди	N;DAT;DEF;PL;LGSPEC1
цель	целенди	N;DAT;SG;LGSPEC1
кши	кшитне	N;NOM;PL;PSS2S
атяпине	атяпинеть	N;HUM;GEN;DEF;SG
армия	армияньконь	N;GEN;SG;PSS1P;LGSPEC1
трудендамс	трудендалеме	V;PL;1;RMT;INTR;LGSPEC1
баярава	баяравань	N;HUM;GEN;SG;LGSPEC1
звонямс	звонясть	V;AC3;PL;2;INTR;LGSPEC1
поздравляндамс	поздравляндафоль	V.PTCP;SG;3;PST;TR;LGSPEC1
отряд	отрядонь	N;GEN;SG;LGSPEC1
бешенства	бешенствать	N;GEN;DEF;SG;LGSPEC1
озамс	озада	V;IMP;PL;2;INTR
плманжань	плманжанень	ADJ;GEN;SG
дистанция	дистанциясь	N;NOM;DEF;SG;LGSPEC1
психолог	психолог	N;HUM;NOM;SG;LGSPEC1
площадка	площадкав	N;AT+ALL;SG;LGSPEC1
киза	кизонза	N;NOM;PL;PSS3S
муворгодомс	муворгофтомань	V;AC1;SG;3;CAUS
приметамс	приметада	V;IMP;PL;2;TR;LGSPEC1
налхкомс	налхкозевсть	V;AC3;IMP;PL;2;TR
экипаж	экипажень	N;GEN;SG;LGSPEC1
расчёт	расчет	N;NOM;SG;LGSPEC1
стопка	стопкасонт	N;IN+ESS;SG;PSS2P;LGSPEC1
значения	значениянц	N;GEN;SG;PSS3S;LGSPEC1
книга	книганц	N;GEN;SG;PSS3S;LGSPEC1
шаракодомс	шаракоды	V;SG;3;INTR
растения	растениятнень	N;GEN;PL;PSS2S;LGSPEC1
объединения	объединениянь	N;GEN;SG;LGSPEC1
ош	ошнень	N;GEN;DEF;PL
пчкамс	пчкафтовсть	V;PL;3;PST;CAUS;PASS
цятордомс	цятордсть	V;AC3;PL;2;INTR
орден	орден	N;NOM;SG;LGSPEC1
пеель	пеель	N;NOM;SG
коммуникация	коммуникациянди	N;DAT;SG;LGSPEC1
пирьф	пирьфнень	N;GEN;PL;PSS1S
предприятия	предприятиянь	N;GEN;SG;LGSPEC1
пинге	пингфтома	N;PRIV;SG
тюремщик	тюремщикокс	N;HUM;TRANS;SG;LGSPEC1
резерва	резерванзон	N;GEN;PL;PSS3S;LGSPEC1
режиссёр	режиссерхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
устав	уставда	N;ABL;SG;LGSPEC1
путнямс	путнят	V;SG;2;INTR
доля	долятнень	N;GEN;DEF;PL;LGSPEC1
коняфкс	коняфкс	N;NOM;SG
разработка	разработкафтома	N;PRIV;SG;LGSPEC1
уемс	уендсть	V;PL;3;PST;INTR
государства	государстваньконди	N;DAT;SG;PSS1P;LGSPEC1
акварель	акварель	N;NOM;SG;LGSPEC1
сюлека	сюлекань	N;GEN;SG
медицина	медицинать	N;GEN;DEF;SG;LGSPEC1
президент	президенттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
кевонзамс	кевонзасть	V;PL;3;PST;INTR
занятия	занятияньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
шоряфкс	шоряфкста	N;ABL;SG
юкстамс	юкстасайть	V;AC3P;SG;2;TR
дистанция	дистанцияса	N;IN+ESS;SG;LGSPEC1
участница	участницасна	N;HUM;NOM;SG;PSS3P;LGSPEC1
пяле	пялетьке	N;NOM;PL;LGSPEC_AMP
эряфкшу	эряфкшуфт	ADJ;NOM;PL
офта	офтт	N;HUM;NOM;PL
округ	округа	N;PROL;SG;LGSPEC1
психолог	психологонди	N;HUM;DAT;SG;LGSPEC1
труд	трудонзон	N;GEN;PL;PSS3S;LGSPEC1
ансамбль	ансамбльхне	N;NOM;PL;PSS1S;LGSPEC1
кальдявгодомс	кальдявгофтсы	V;AC3S;SG;3;CAUS
оця	оцяньконь	N;HUM;GEN;SG;PSS1P
номинация	номинация	N;NOM;SG;LGSPEC1
шаба	шабаста	N;HUM;IN+ABL;SG
пине	пинедонза	N;HUM;ABL;SG;PSS3S
аборт	абортонь	N;GEN;SG;LGSPEC1
свадьба	свадьбаснонды	N;DAT;SG;PSS3P;LGSPEC1
хозяйства	хозяйстваснонды	N;DAT;SG;PSS3P;LGSPEC1
пшкядемс	пшкядят	V;SG;2;TR
экипаж	экипажть	N;GEN;DEF;SG;LGSPEC1
сапоня	сапонят	N;NOM;PL
шовонь	шовоньц	N;IN+ALL;SG
семинар	семинархне	N;NOM;DEF;PL;LGSPEC1
садик	садикти	N;DAT;DEF;SG;LGSPEC1
пяшкодемс	пяшкодевсь	V;SG;3;PST;TR;PASS
артистка	артистканте	N;HUM;NOM;SG;PSS2P;LGSPEC1
почердамс	почердань	V;SG;1;PST;TR
шар	шароль	N;SG;3;PST;LGSPEC1
брат	браттненди	N;HUM;DAT;DEF;PL;LGSPEC1
семья	семьязонза	N;IN+ALL;SG;PSS3S;LGSPEC1
лихтемс	лихтеви	V;SG;3;TR;PASS
гайфтемс	гайфтезь	V;AC3;PL;3;TR
обязанность	обязанностьтост	N;ABL;SG;PSS3P;LGSPEC1
материал	материалхненди	N;DAT;DEF;PL;LGSPEC1
велямс	веляф	V.PTCP;PST;INTR
нормаль	нормальхнень	N;GEN;DEF;PL
сиве	сивот	N;NOM;PL
мастер	мастероньке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
иностранец	иностранецне	N;HUM;NOM;PL;PSS1S;LGSPEC1
пялькс	пялькснень	N;GEN;PL;PSS1S
румын	румыттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
трилогия	трилогиянкса	N;CAUSV;SG;LGSPEC1
юмай	юмайхнень	N;GEN;PL;PSS1S
лямбе	лямбонь	N;GEN;SG
журнал	журналхнень	N;GEN;DEF;PL;LGSPEC1
просветитель	просветителенза	N;HUM;NOM;PL;PSS3S;LGSPEC1
содамоши	содамошис	N;IN+ALL;SG
сюлека	сюлека	N;NOM;SG
князь	княснень	N;HUM;GEN;PL;PSS1S;LGSPEC1
эряфкшу	эряфкшусь	ADJ;NOM;DEF;SG
кластер	кластерхне	N;NOM;PL;PSS1S;LGSPEC1
губор	губорсь	N;NOM;DEF;SG
аля	аляце	N;HUM;NOM;SG;PSS2S
колхозник	колхозниксь	N;HUM;NOM;DEF;SG;LGSPEC1
резина	резина	N;NOM;SG;LGSPEC1
князь	князень	N;HUM;GEN;SG;LGSPEC1
юрнамс	юрнась	V;SG;3;PST;INTR
ушеткс	ушеткссна	N;NOM;SG;PSS3P
модель	моделензон	N;GEN;PL;PSS3S;LGSPEC1
художница	художницась	N;HUM;NOM;DEF;SG;LGSPEC1
шуму	шуму	N;HUM;NOM;SG
репортаж	репорташнень	N;GEN;DEF;PL;LGSPEC1
лиемс	ливсть	V;PL;3;PST;INTR;PASS
носок	носокне	N;NOM;PL;PSS1S;LGSPEC1
тише	тишефтома	N;PRIV;SG
кемай	кемайда	ADJ;ABL;SG
спасибамс	спасибань	V;SG;1;PST;TR;LGSPEC1
полга	полкстост	N;IN+ABL;SG;PSS3P
вирь	виреньке	N;NOM;SG;PSS1P
знамя	знамяц	N;NOM;SG;PSS3S;LGSPEC1
плод	плоттне	N;NOM;DEF;PL;LGSPEC1
кампания	кампаниятне	N;NOM;PL;PSS2S;LGSPEC1
приёмнай	приемнайса	ADJ;IN+ESS;SG;LGSPEC1
удаламс	удалафть	V.PTCP;GEN;DEF;SG;PST;INTR;LGSPEC1
биатлонист	биатлонистоньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
копордамс	копордасть	V;PL;3;PST;TR
слава	слава	N;NOM;SG;LGSPEC1
куя	куя	N;NOM;SG
парикмахерскяй	парикмахерскяйхнень	N;GEN;PL;PSS1S;LGSPEC1
газовик	газовикть	N;HUM;GEN;DEF;SG;LGSPEC1
мордва	мордвада	N;HUM;ABL;SG;LGSPEC1
ётка	етксонза	N;IN+ESS;SG;PSS3S
ринит	ринитта	N;ABL;SG;LGSPEC1
права	праваса	N;IN+ESS;SG;LGSPEC1
патриот	патриотсь	N;HUM;NOM;DEF;SG;LGSPEC1
таз	тазса	N;IN+ESS;SG
переселенец	переселенецненди	N;HUM;DAT;DEF;PL;LGSPEC1
ацергодомс	ацергофтф	V.PTCP;PST;CAUS
медицина	медицинати	N;DAT;DEF;SG;LGSPEC1
газовик	газовик	N;HUM;NOM;SG;LGSPEC1
толмар	толмаронь	N;GEN;SG
согласия	согласияти	N;DAT;DEF;SG;LGSPEC1
приметамс	приметамань	V;AC1;SG;3;TR;LGSPEC1
тёкш	тёкшезонза	N;IN+ALL;SG;PSS3S
потма	потмоть	N;GEN;DEF;SG
шарфтомс	шарфттама	V;PL;1;TR
испытания	испытаниясь	N;NOM;DEF;SG;LGSPEC1
од	одсь	ADJ;NOM;DEF;SG
филиал	филиалоц	N;NOM;SG;PSS3S;LGSPEC1
магнитофон	магнитофон	N;NOM;SG;LGSPEC1
труба	трубань	N;GEN;SG;LGSPEC1
фонд	фонд	N;NOM;SG;LGSPEC1
анамс	анаф	V.PTCP;PST;TR
воляши	воляшить	N;GEN;DEF;SG;LGSPEC1
тумс	туфнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
пере	перель	N;SG;3;PST
очка	очкасна	N;NOM;SG;PSS3P;LGSPEC1
тест	тесттне	N;NOM;PL;PSS2S;LGSPEC1
тротуар	тротуархт	N;NOM;PL;LGSPEC1
ядохимикат	ядохимикаттнень	N;GEN;PL;PSS2S;LGSPEC1
мариец	мариецнень	N;HUM;GEN;DEF;PL;LGSPEC1
ватага	ватакне	N;NOM;PL;PSS1S;LGSPEC1
киза	кизоль	N;SG;3;PST
летопись	летопись	N;NOM;SG;LGSPEC1
сапонь	сапонь	N;NOM;SG
кучемс	кучса	V;AC3S;SG;1;TR
веле	веленьконди	N;DAT;SG;PSS1P
коня	конясонза	N;IN+ESS;SG;PSS3S
рамка	рамканзон	N;GEN;PL;PSS3S;LGSPEC1
июнь	июнень	N;GEN;SG;LGSPEC1
департамент	департамент	N;NOM;SG;LGSPEC1
пачфтемс	пачфтине	V;AC3;SG;1;TR
памятник	памятникста	N;IN+ABL;SG;LGSPEC1
банк	банконь	N;GEN;SG;LGSPEC1
почердамс	почердафт	V;NEG;CAUS
школа	школаснонды	N;DAT;SG;PSS3P;LGSPEC1
республика	республиканцты	N;DAT;SG;PSS3S;LGSPEC1
ружья	ружьят	N;NOM;PL;LGSPEC1
валвеляфкс	валвеляфксне	N;NOM;DEF;PL
макса	макса	N;NOM;SG
капитан	капитанть	N;HUM;GEN;DEF;SG;LGSPEC1
предприниматель	предпринимательхне	N;HUM;NOM;DEF;PL;LGSPEC1
запас	запасса	N;IN+ESS;SG;LGSPEC1
статья	статьяцень	N;GEN;SG;PSS2S;LGSPEC1
муниципалитет	муниципалитет	N;NOM;SG;LGSPEC1
ваномс	ванови	V;SG;3;TR;PASS
скутер	скутерсь	N;NOM;DEF;SG;LGSPEC1
радиатор	радиаторть	N;GEN;DEF;SG;LGSPEC1
учебник	учебник	N;NOM;SG;LGSPEC1
сиволю	сиволюфт	ADJ;NOM;PL
печатламс	печатлафоль	V.PTCP;SG;3;PST;TR;LGSPEC1
шкамс	шкафти	V;SG;3;CAUS
концерн	концерттнень	N;GEN;DEF;PL;LGSPEC1
спартакиада	спартакиадасост	N;IN+ESS;SG;PSS3P;LGSPEC1
прьхчещандамс	прьхчещандафтомс	V;NFIN;CAUS;LGSPEC1
сюла	сюлотне	N;NOM;DEF;PL
унжа	унжатнень	N;HUM;GEN;PL;PSS2S
ширь	ширетне	N;NOM;PL;PSS2S
школьник	школьник	N;HUM;NOM;SG;LGSPEC1
отзыв	отзывонзон	N;GEN;PL;PSS3S;LGSPEC1
радня	радняне	N;HUM;NOM;PL;PSS1S;LGSPEC1
идьфтома	идьфтома	ADJ
карга	каркта	N;HUM;ABL;SG
фольклорист	фольклорист	N;HUM;NOM;SG;LGSPEC1
пандоз	пандоз	N;NOM;SG
сувамс	сувафтовсь	V;SG;3;PST;CAUS;PASS
шапамомс	шапами	V;SG;3;INTR
решения	решениянц	N;GEN;SG;PSS3S;LGSPEC1
толкавамс	толкавакшнезе	V;AC3S;SG;3;TR;LGSPEC1
мани	манись	ADJ;NOM;DEF;SG
проект	проектоц	N;NOM;SG;PSS3S;LGSPEC1
мазоптомс	мазоптфт	V.PTCP;NOM;PL;PST;TR
кев	кефнень	N;GEN;PL;PSS1S
суском	суском	N;NOM;SG
шорсемс	шорсезе	V;AC3S;SG;3;INTR
пиле	пилезонк	N;IN+ALL;SG;PSS1P
лувома	лувоматне	N;NOM;DEF;PL
кувалма	кувалмотне	N;NOM;PL;PSS2S
поражения	поражения	N;NOM;SG;LGSPEC1
таран	тараттне	N;NOM;PL;PSS2S;LGSPEC1
пристань	пристанькс	N;TRANS;SG;LGSPEC1
ила	илать	N;GEN;DEF;SG
ванф	ванфне	N;NOM;PL;PSS1S
руль	рульхнень	N;GEN;DEF;PL;LGSPEC1
диспансер	диспансерти	N;DAT;DEF;SG;LGSPEC1
отвёртка	отвертка	N;NOM;SG;LGSPEC1
пенсия	пенсиять	N;GEN;DEF;SG;LGSPEC1
шукшторукс	шукшторуксонь	N;GEN;SG
свежай	свежайхне	ADJ;NOM;PL;PSS1S;LGSPEC1
колай	колаят	N;SG;2
тргадомс	тргаткшнихть	V;PL;3;INTR
сюла	сюлонц	N;GEN;SG;PSS3S
бактерия	бактерия	N;NOM;SG;LGSPEC1
президиум	президиумозонза	N;IN+ALL;SG;PSS3S;LGSPEC1
наказамс	наказа	V;NEG;TR;LGSPEC1
бюро	бюроти	N;DAT;DEF;SG;LGSPEC1
люкамс	люкай	V;SG;3;INTR
шпана	шпанать	N;HUM;GEN;DEF;SG;LGSPEC1
распределения	распределенияса	N;IN+ESS;SG;LGSPEC1
каникула	каникулатненди	N;DAT;DEF;PL;LGSPEC1
обжамс	обжакшне	V;NEG;TR;LGSPEC1
кенярдемс	кенярдсть	V;AC3;PL;2;INTR
пример	примерсонк	N;IN+ESS;SG;PSS1P;LGSPEC1
поколения	поколениятненди	N;DAT;DEF;PL;LGSPEC1
пиломатериал	пиломатериалхнень	N;GEN;DEF;PL;LGSPEC1
монет	монетат	N;SG;2;LGSPEC1
скромнай	скромнайхть	ADJ;NOM;PL;LGSPEC1
мебель	мебельсь	N;NOM;DEF;SG;LGSPEC1
круг	кругоц	N;NOM;SG;PSS3S;LGSPEC1
самбо	самбо	N;NOM;SG;LGSPEC1
таргамс	таргафт	V;NEG;CAUS
амбразура	амбразураснон	N;GEN;SG;PSS3P;LGSPEC1
кой	койхне	N;NOM;PL;PSS1S
карша	каршезон	N;IN+ALL;SG;PSS1S
концлагерь	концлагерень	N;GEN;SG;LGSPEC1
ангел	ангелхненди	N;DAT;DEF;PL;LGSPEC1
документ	документтне	N;NOM;PL;PSS2S;LGSPEC1
большевик	большевикокс	N;HUM;TRANS;SG;LGSPEC1
заезд	заезтта	N;ABL;SG;LGSPEC1
юморист	юмористтне	N;HUM;NOM;DEF;PL;LGSPEC1
документ	документт	N;NOM;PL;LGSPEC1
белорус	белорусть	N;HUM;GEN;DEF;SG;LGSPEC1
ётай	ётайти	N;HUM;DAT;DEF;SG
шире	ширенц	N;GEN;SG;PSS3S
действия	действиятнень	N;GEN;PL;PSS2S;LGSPEC1
явомс	яволь	V;SG;3;RMT;TR
кит	китненди	N;HUM;DAT;DEF;PL;LGSPEC1
мази	мази	ADJ
мастерица	мастерицатнень	N;HUM;GEN;DEF;PL;LGSPEC1
призёр	призероль	N;HUM;SG;3;PST;LGSPEC1
стирь	стирель	N;HUM;SG;3;PST
сускомс	сускф	V.PTCP;PST;TR
щебёнка	щебенкань	N;GEN;SG;LGSPEC1
киномеханик	киномеханиксь	N;HUM;NOM;DEF;SG;LGSPEC1
тиемс	тифти	V;SG;3;CAUS
кошардомс	кошардомс	V;NFIN;TR
падёж	падешнень	N;GEN;DEF;PL;LGSPEC1
антрополог	антрополокне	N;HUM;NOM;DEF;PL;LGSPEC1
наказамс	наказакшневсть	V;AC3;PL;2;CAUS;LGSPEC1
учебник	учебникокс	N;TRANS;SG;LGSPEC1
тундра	тундрась	N;NOM;DEF;SG;LGSPEC1
радиоканал	радиоканалсь	N;NOM;DEF;SG;LGSPEC1
оброк	оброкне	N;NOM;DEF;PL;LGSPEC1
сире	сиретне	ADJ;NOM;DEF;PL
мрдамс	мрдамс	V;NFIN;INTR
кялемс	кялезень	V;AC3P;SG;3;INTR
норма	норманди	N;DAT;SG;LGSPEC1
колдун	колдуттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
кон	конть	N;GEN;DEF;SG;LGSPEC1
хутор	хуторхт	N;NOM;PL;LGSPEC1
взвод	взводонь	N;GEN;SG;LGSPEC1
прогрессивка	прогрессивка	N;NOM;SG;LGSPEC1
калмамс	калмафтольхть	V;PL;3;RMT;CAUS
мазоптомс	мазоптомс	V;NFIN;TR
сокамс	сокафть	V.PTCP;GEN;DEF;SG;PST;TR
проблема	проблемати	N;DAT;DEF;SG;LGSPEC1
чеснок	чеснокти	N;DAT;DEF;SG;LGSPEC1
пуромомс	пуромфнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
конвоир	конвоирть	N;HUM;GEN;DEF;SG;LGSPEC1
асу	асувонц	N;GEN;SG;PSS3S
документ	документтка	N;NOM;PL;LGSPEC_AMP;LGSPEC1
патриотизма	патриотизма	N;NOM;SG;LGSPEC1
седи	седиснон	N;GEN;SG;PSS3P
вес	весть	N;GEN;DEF;SG;LGSPEC1
аспирант	аспирантсь	N;HUM;NOM;DEF;SG;LGSPEC1
кардамс	кардатядязь	V;AC2;PL;3;TR
ляй	ляезонза	N;IN+ALL;SG;PSS3S
симпозиум	симпозиупнень	N;GEN;DEF;PL;LGSPEC1
раштамс	раштасть	V;AC3;IMP;PL;2;TR
куфтол	куфтолхт	N;NOM;PL
пяляскодомс	пяляскоткшни	V;SG;3;INTR
сур	сурть	N;GEN;DEF;SG
колдун	колдункс	N;HUM;TRANS;SG;LGSPEC1
топ	топть	N;GEN;DEF;SG
оцязор	оцязороньке	N;HUM;GEN;SG;LGSPEC_AMP
регион	регион	N;NOM;SG;LGSPEC1
пейзиволь	пейзивольхненди	N;DAT;PL;PSS1S
медсестра	медсестрать	N;HUM;GEN;DEF;SG;LGSPEC1
рамамс	рамаль	V;SG;3;RMT;TR
суском	сускопнень	N;GEN;DEF;PL
лотка	лоткалень	N;SG;1;PST
гармонист	гармонисттненди	N;HUM;DAT;DEF;PL;LGSPEC1
машиностроитель	машиностроительхнень	N;HUM;GEN;DEF;PL;LGSPEC1
колдун	колдуттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
источник	источник	N;NOM;SG;LGSPEC1
ювадемс	ювадсть	V;PL;3;PST;TR
тошкамс	тошкайхть	V;PL;3;TR
животнай	животнайть	N;HUM;GEN;DEF;SG;LGSPEC1
смекамс	смекафт	V;NEG;CAUS;LGSPEC1
магистра	магистрхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
программнай	программнай	ADJ;LGSPEC1
лицей	лицейть	N;NOM;PL;LGSPEC1
поэма	поэмань	N;GEN;SG;LGSPEC1
раса	расав	N;AT+ALL;SG;LGSPEC1
подразделения	подразделениякс	N;TRANS;SG;LGSPEC1
трактор	тракторонза	N;HUM;NOM;PL;PSS3S;LGSPEC1
закон	закононц	N;GEN;SG;PSS3S;LGSPEC1
колена	коленати	N;DAT;DEF;SG;LGSPEC1
сёра	сёросна	N;NOM;SG;PSS3P
комамс	команды	V;SG;3;INTR
драмтеатра	драмтеатра	N;NOM;SG;LGSPEC1
оцязор	оцязоронте	N;HUM;NOM;SG;PSS2P
жест	жесттнень	N;GEN;DEF;PL;LGSPEC1
ковёр	коверхненди	N;DAT;DEF;PL;LGSPEC1
кяскав	кяскавста	N;IN+ABL;SG
пародист	пародистт	N;HUM;NOM;PL;LGSPEC1
сель	сельге	N;NOM;SG;LGSPEC_AMP
степень	степенец	N;NOM;SG;PSS3S;LGSPEC1
антихрист	антихристть	N;GEN;DEF;SG;LGSPEC1
виздемс	виздихть	V;PL;3;TR
пакся	паксясонза	N;IN+ESS;SG;PSS3S
экономическяй	экономическяйста	ADJ;IN+ABL;SG;LGSPEC1
арьсемс	арьсезевода	V;IMP;PL;2;TR
казак	казак	N;HUM;NOM;SG;LGSPEC1
казямгодомс	казямгофтомс	V;NFIN;CAUS
каникулат	каникуласна	N;NOM;SG;PSS3P;LGSPEC1
свежай	свежайхть	ADJ;NOM;PL;LGSPEC1
водендамс	водендак	V;IMP;SG;2;TR;LGSPEC1
тиши	тиши	ADJ
шама	шамасост	N;IN+ESS;SG;PSS3P
жених	женихсь	N;NOM;DEF;SG;LGSPEC1
шире	ширетнень	N;GEN;PL;PSS2S
воспитандамс	воспитандай	V;SG;3;TR;LGSPEC1
венгерка	венгеркась	N;HUM;NOM;DEF;SG;LGSPEC1
рота	ротанц	N;GEN;SG;PSS3S;LGSPEC1
доска	доскаста	N;IN+ABL;SG;LGSPEC1
актуальнай	актуальнайхть	ADJ;NOM;PL;LGSPEC1
вайме	ваймозе	N;NOM;SG;PSS1S
кенкш	кенкшка	N;NOM;SG;LGSPEC_AMP
масторонь	мастороньке	ADJ;LGSPEC_AMP
ориентир	ориентирхнень	N;GEN;PL;PSS1S;LGSPEC1
самс	саф	V.PTCP;PST;INTR
ловонь	ловонь	ADJ
ал	алста	N;IN+ABL;SG
граница	границать	N;GEN;DEF;SG;LGSPEC1
тонафни	тонафниень	N;HUM;GEN;SG
президиум	президиумонц	N;GEN;SG;PSS3S;LGSPEC1
калдаз	калдазста	N;IN+ABL;SG
штангист	штангистсь	N;HUM;NOM;DEF;SG;LGSPEC1
белок	белок	N;NOM;SG;LGSPEC1
ми	митька	N;GEN;DEF;SG;LGSPEC_AMP
сообщества	сообществань	N;GEN;SG;LGSPEC1
повфтамс	повфтась	V;SG;3;PST;TR
байдек	байдек	N;NOM;SG
хлопчатобумажнай	хлопчатобумажнайхть	ADJ;NOM;PL;LGSPEC1
воспаления	воспаления	N;NOM;SG;LGSPEC1
ужамс	ужат	V;SG;2;INTR
сувенир	сувенироньке	N;NOM;SG;PSS1P;LGSPEC1
тополень	тополень	ADJ;LGSPEC1
кум	кумсь	N;HUM;NOM;DEF;SG;LGSPEC1
экспортнай	экспортнай	ADJ;LGSPEC1
лаймоньзи	лаймоньзинь	N;HUM;GEN;SG
виздемс	виздсть	V;AC3;PL;2;TR
венец	венецсь	N;NOM;DEF;SG;LGSPEC1
субсидия	субсидияда	N;ABL;SG;LGSPEC1
ацамс	ацави	V;SG;3;TR;PASS
ген	геттнень	N;GEN;DEF;PL;LGSPEC1
няевикс	няевикс	ADJ
ведущай	ведущайхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
шовордамс	шовордазе	V;AC3S;SG;3;TR
барак	баракнень	N;GEN;DEF;PL;LGSPEC1
пиченал	пиченалсь	N;NOM;DEF;SG
параллель	параллельхне	N;NOM;DEF;PL;LGSPEC1
бебамс	бебан	V;SG;1;TR
урядамс	урядась	V;SG;3;PST;TR;LGSPEC1
вииямс	вииясь	V;SG;3;PST;INTR
сукс	сукснень	N;HUM;GEN;PL;PSS1S
кагод	каготтне	N;NOM;DEF;PL
сура	суроньконь	N;GEN;SG;PSS1P
сельме	сельмос	N;IN+ALL;SG
ряд	рядсь	N;NOM;DEF;SG;LGSPEC1
оптика	оптикати	N;DAT;DEF;SG;LGSPEC1
церемония	церемонияда	N;ABL;SG;LGSPEC1
кочкяря	кочкяряса	N;IN+ESS;SG
товар	товаронц	N;GEN;SG;PSS3S;LGSPEC1
собес	собесу	N;AT+ALL;SG;LGSPEC1
занямс	заняфненди	V.PTCP;DAT;PL;PSS1S;PST;TR;LGSPEC1
праведнай	праведнай	ADJ;LGSPEC1
ветеран	ветераттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
ноляви	нолявихнень	ADJ;GEN;DEF;PL
кулемс	кулендярятанза	V;AC2;COND;SG;3;TR
тройка	тройка	N;NOM;SG;LGSPEC1
воспоминания	воспоминания	N;NOM;SG;LGSPEC1
посаблямс	посабляда	V;IMP;PL;2;INTR;LGSPEC1
ков	ковда	N;ABL;SG
представительства	представительствац	N;NOM;SG;PSS3S;LGSPEC1
медалист	медалисттнень	N;HUM;GEN;DEF;PL;LGSPEC1
или	илиста	N;IN+ABL;SG
байдек	байдекса	N;IN+ESS;SG
пиди	пидикс	ADJ;TRANS;SG
автомобилестроения	автомобилестроенияти	N;DAT;DEF;SG;LGSPEC1
обзор	обзорхт	N;NOM;PL;LGSPEC1
шачемс	шачендсть	V;AC3;IMP;PL;2;INTR
водка	водкати	N;DAT;DEF;SG;LGSPEC1
юром	юропненди	N;DAT;PL;PSS1S
субэтнос	субэтноссь	N;NOM;DEF;SG;LGSPEC1
ферма	фермац	N;NOM;SG;PSS3S;LGSPEC1
сатомс	сатоть	V;SG;2;PST;TR
мяште	мяштезень	N;GEN;SG;PSS1S
сталь	сталь	N;LGSPEC1
тонафнемань	тонафнемань	ADJ
загс	загста	N;ABL;SG;LGSPEC1
выступандамс	выступандакшнихть	V;PL;3;INTR;LGSPEC1
сувамс	сувафтольхть	V.PTCP;NOM;PL;3;PST;INTR
козя	козянь	ADJ;GEN;SG
шире	ширесна	N;NOM;SG;PSS3P
машиностроитель	машиностроительхненди	N;HUM;DAT;DEF;PL;LGSPEC1
продукция	продукцияньконди	N;DAT;SG;PSS1P;LGSPEC1
косьфтамс	косьфтави	V;SG;3;TR;PASS
шнамс	шнафоль	V.PTCP;SG;3;PST;TR
калгамс	калгась	V;SG;3;PST;TR
стирь	стирьхнень	N;HUM;GEN;DEF;PL
тетрадь	тетрадьс	N;IN+ALL;SG;LGSPEC1
вальмя	вальмятненди	N;DAT;PL;PSS2S
тенька	тенькафтома	N;PRIV;SG
менеджмент	менеджментсь	N;NOM;DEF;SG;LGSPEC1
котлета	котлетатнень	N;GEN;PL;PSS2S;LGSPEC1
сявомс	сявфт	V;NEG;CAUS
кулу	кулуфнень	N;GEN;PL;PSS1S
тормоз	тормозсна	N;NOM;SG;PSS3P;LGSPEC1
фигура	фигуратнень	N;GEN;PL;PSS2S;LGSPEC1
вайме	ваймотнень	N;GEN;DEF;PL
ЦИК	цик-са	N;IN+ESS;SG;LGSPEC1
педемс	педельхть	V;PL;3;RMT;INTR
лоткамс	лоткафта	V.PTCP;ABL;SG;PST;INTR
частт	частть	N;GEN;DEF;SG;LGSPEC1
постановления	постановлениянц	N;GEN;SG;PSS3S;LGSPEC1
корабль	корабльса	N;IN+ESS;SG;LGSPEC1
астролог	астролокне	N;HUM;NOM;PL;PSS1S;LGSPEC1
элякодомс	элякоды	V;SG;3;INTR
кирпиць	кирпицьста	N;IN+ABL;SG;LGSPEC1
отчёт	отчетсь	N;NOM;DEF;SG;LGSPEC1
пуромомс	пуромфне	V.PTCP;NOM;DEF;PL;PST;INTR
эшендемс	эшентьфтесть	V;PL;3;PST;CAUS
революция	революциятненди	N;DAT;DEF;PL;LGSPEC1
учемс	учемс	V;NFIN;TR
поэт	поэтоньконди	N;HUM;DAT;SG;PSS1P;LGSPEC1
сяряди	сярядида	ADJ;ABL;SG
миллиардер	миллиардерхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
фигурист	фигуристонза	N;HUM;NOM;PL;PSS3S;LGSPEC1
медень	медень	ADJ
бюллетень	бюллетенти	N;DAT;DEF;SG;LGSPEC1
толу	толусь	ADJ;NOM;DEF;SG
перямс	перяфса	V.PTCP;IN+ESS;SG;PST;TR
педемс	петьфтольхть	V;PL;3;RMT;CAUS
реагирования	реагированиянь	N;GEN;SG;LGSPEC1
ванна	ваннатне	N;NOM;PL;PSS2S;LGSPEC1
салмокс	салмокссь	N;NOM;DEF;SG
рамай	рамайхнень	N;HUM;GEN;PL;PSS1S
пятница	пятница	N;NOM;SG;LGSPEC1
путёвка	путевкас	N;IN+ALL;SG;LGSPEC1
дефиле	дефилесь	N;NOM;DEF;SG;LGSPEC1
мрдамс	мрдаф	V.PTCP;PST;INTR
аськолдамс	аськолдат	V;SG;2;INTR
слега	слегатнень	N;GEN;DEF;PL;LGSPEC1
роштува	роштуванди	N;DAT;SG;LGSPEC1
история	историяньке	N;NOM;SG;PSS1P;LGSPEC1
печатламс	печатлакшнемазь	V;AC1;PL;3;TR;LGSPEC1
шумбраши	шумбрашинкса	N;CAUSV;SG
каванямс	каваняфоль	V.PTCP;SG;3;PST;TR
валондомс	валондомс	V;NFIN;INTR
аздомс	азфнень	V.PTCP;GEN;DEF;PL;PST;INTR
амолдамс	амолдасть	V;PL;3;PST;TR
вика	викать	N;GEN;DEF;SG
сюрприз	сюрприст	N;NOM;PL;LGSPEC1
пою	поюста	N;IN+ABL;SG
ртутнай	ртутнай	ADJ;LGSPEC1
муводемс	муводсь	V;SG;3;PST;TR
фея	феякс	N;TRANS;SG;LGSPEC1
токамс	токафтозень	V;AC3P;SG;3;CAUS
этаж	эташт	N;NOM;PL;LGSPEC1
кайгомс	кайгонды	V;SG;3;INTR
викторина	викторинатнень	N;GEN;DEF;PL;LGSPEC1
пиле	пилеса	N;IN+ESS;SG
гулядондамс	гулядондасть	V;AC3;IMP;PL;2;INTR;LGSPEC1
панжа	панжельхть	N;PL;3;PST
венептемс	венептьк	V;AC3;IMP;SG;2;TR
уша	ушень	N;GEN;SG
юромомс	юромга	V;LGSPEC_AMP;NEG;INTR
наказамс	наказавихть	V;PL;3;TR;PASS;LGSPEC1
шнамс	шнакшнедязь	V;AC2S;PL;3;TR
пизелкс	пизелкснень	N;GEN;DEF;PL
смысла	смысла	N;NOM;SG;LGSPEC1
аердомс	аерфтозень	V;AC3P;SG;3;CAUS
стирьксши	стирьксшицень	N;GEN;SG;PSS2S
стая	стаяса	N;IN+ESS;SG;LGSPEC1
стихотворения	стихотворениятнень	N;GEN;DEF;PL;LGSPEC1
кельмофтевомс	кельмофтевсть	V;AC3;PL;2;INTR
наркодиспансер	наркодиспансеру	N;AT+ALL;SG;LGSPEC1
кркштадемс	кркштади	V;SG;3;TR
куд	кудозти	N;DAT;SG;PSS1S
ОРВИ	орви-тнень	N;GEN;PL;PSS2S;LGSPEC1
марь	марьхне	N;NOM;PL;PSS1S
шулкфтомс	шулкфтыхть	V;PL;3;TR
пример	примерса	N;IN+ESS;SG;LGSPEC1
фоторепортаж	фоторепортажень	N;GEN;SG;LGSPEC1
поселения	поселениятнень	N;GEN;PL;PSS2S;LGSPEC1
кредит	кредиттне	N;NOM;PL;PSS2S;LGSPEC1
тюжалгодомс	тюжалгодсть	V;AC3;PL;2;INTR
коммунизма	коммунизма	N;NOM;SG;LGSPEC1
тердемс	тертьфта	V.PTCP;ABL;SG;PST;TR
разряд	разрядса	N;IN+ESS;SG;LGSPEC1
лядемс	ляденде	V;NEG;INTR
шинь	шинень	ADJ;GEN;SG
учемс	учеме	V;PL;1;PST;TR
политика	политикац	N;NOM;SG;PSS3S;LGSPEC1
позиция	позициятнень	N;GEN;DEF;PL;LGSPEC1
класс	класснон	N;GEN;SG;PSS3P;LGSPEC1
факультет	факультеттне	N;NOM;PL;PSS2S;LGSPEC1
писатель	писателеньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
смелши	смелшинцты	N;DAT;SG;PSS3S;LGSPEC1
катер	катер	N;NOM;SG;LGSPEC1
училища	училищаньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
лоткамс	лоткафтыне	V;AC3;SG;1;CAUS
декларация	декларацият	N;NOM;PL;LGSPEC1
кятькс	кятькснень	N;GEN;PL;PSS1S
типонь	типонь	N;LGSPEC1
эрямс	эрявсть	V;AC3;PL;2;INTR;PASS
кев	кевонц	N;GEN;SG;PSS3S
бюджетник	бюджетникнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
колонна	колоннат	N;NOM;PL;LGSPEC1
государственнай	государственнайсь	ADJ;NOM;DEF;SG;LGSPEC1
федеральнай	федеральнайста	ADJ;IN+ABL;SG;LGSPEC1
фантазия	фантазиянц	N;GEN;SG;PSS3S;LGSPEC1
учения	учениясна	N;NOM;SG;PSS3P;LGSPEC1
журналист	журналистта	N;HUM;ABL;SG;LGSPEC1
носка	носкань	N;GEN;SG;LGSPEC1
маштомаши	маштомошизень	N;GEN;SG;PSS1S
автобус	автобуста	N;ABL;SG;LGSPEC1
валхтомс	валхты	V;SG;3;TR
рота	ротась	N;NOM;DEF;SG;LGSPEC1
наряд	нарядоньконь	N;GEN;SG;PSS1P;LGSPEC1
гайнямс	гайнякшнесть	V;AC3;PL;2;INTR
сустав	сустав	N;NOM;SG;LGSPEC1
арьсемс	арьсезевсь	V;SG;3;PST;TR
толгав	толгав	ADJ
эряскодомс	эряскофтомс	V;NFIN;CAUS
ваномс	ванфонц	V.PTCP;GEN;SG;PSS3S;PST;TR
маластонь	маластонне	ADJ;NOM;DEF;PL
част	часткат	N;PROL;SG;PSS2S;LGSPEC1
сатирическяй	сатирическяй	ADJ;LGSPEC1
пример	примерсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
калькулятор	калькуляторонтень	N;GEN;SG;PSS2P;LGSPEC1
ланга	ланкста	N;IN+ABL;SG
поведения	поведения	N;NOM;SG;LGSPEC1
фронтовик	фронтовикненди	N;HUM;DAT;DEF;PL;LGSPEC1
деятельность	деятельностень	N;GEN;SG;LGSPEC1
суском	сускомть	N;GEN;DEF;SG
казямгодомс	казямгодсть	V;PL;3;PST;INTR
сувамс	сувафтов	V;NEG;CAUS;PASS
мрдамс	мрдафтови	V;SG;3;CAUS;PASS
обязательства	обязательства	N;NOM;SG;LGSPEC1
инспекция	инспекцияв	N;AT+ALL;SG;LGSPEC1
парикмахер	парикмахерсь	N;HUM;NOM;DEF;SG;LGSPEC1
этап	этап	N;NOM;SG;LGSPEC1
буква	букватнень	N;GEN;DEF;PL;LGSPEC1
юрхта	юрхтонц	N;GEN;SG;PSS3S
советскяй	советскяйть	ADJ;GEN;DEF;SG;LGSPEC1
шама	шамаса	N;IN+ESS;SG
сатомшка	сатомшка	ADJ
субъект	субъектонзон	N;GEN;PL;PSS3S;LGSPEC1
шаман	шаманцка	N;HUM;IN+ALL;SG;LGSPEC_AMP;LGSPEC1
шум	шумда	N;ABL;SG;LGSPEC1
музыка	музыкаса	N;IN+ESS;SG;LGSPEC1
мокшаля	мокшалятне	N;HUM;NOM;DEF;PL
автор	авторсь	N;HUM;NOM;DEF;SG;LGSPEC1
пилот	пилотка	N;HUM;PROL;SG;LGSPEC1
сталма	сталмонзон	N;GEN;PL;PSS3S
премьер-министр	премьер-министрти	N;HUM;DAT;DEF;SG;LGSPEC1
заместитель	заместитель	N;HUM;LGSPEC1
фракция	фракциятне	N;NOM;PL;PSS2S;LGSPEC1
недяля	недялятне	N;NOM;PL;PSS2S;LGSPEC1
цебярь	цебярьдонза	ADJ;ABL;SG;PSS3S
панно	паннот	N;NOM;PL;LGSPEC1
работник	работникне	N;HUM;NOM;DEF;PL;LGSPEC1
гонорар	гонорархнень	N;GEN;DEF;PL;LGSPEC1
врьгятемс	врьгятсть	V;AC3;IMP;PL;2;INTR
якорь	якорьхнень	N;GEN;DEF;PL;LGSPEC1
мирде	мирдентенди	N;HUM;DAT;SG;PSS2P
противник	противникокс	N;HUM;TRANS;SG;LGSPEC1
сатфкс	сатфксс	N;IN+ALL;SG
промышленность	промышленности	N;AT+ALL;SG;LGSPEC1
гармошка	гармошкань	N;GEN;SG;LGSPEC1
вес	вести	N;DAT;DEF;SG;LGSPEC1
оптика	оптикать	N;GEN;DEF;SG;LGSPEC1
инженер	инженерсь	N;HUM;NOM;DEF;SG;LGSPEC1
верондамс	верондаманьке	V;AC1;SG;LGSPEC_AMP;3;TR;LGSPEC1
карел	карелонь	N;HUM;GEN;SG;LGSPEC1
модамарень	модамареньке	ADJ;LGSPEC_AMP
пожар	пожаронь	N;GEN;SG;LGSPEC1
лядомс	ляткшнетяма	V;PL;1;INTR
инфекция	инфекциятне	N;NOM;DEF;PL;LGSPEC1
сёлгомс	сёлгондови	V;SG;3;TR;PASS
рубрика	рубриканьконь	N;GEN;SG;PSS1P;LGSPEC1
шава	шава	N;NOM;SG
шовордамс	шовордасть	V;PL;3;PST;TR
близорукость	близорукостть	N;NOM;PL;LGSPEC1
воявамс	воявасть	V;AC3;IMP;PL;2;INTR;LGSPEC1
мочало	мочалов	N;AT+ALL;SG;LGSPEC1
видеоконференция	видеоконференцияса	N;IN+ESS;SG;LGSPEC1
агитация	агитациясь	N;NOM;DEF;SG;LGSPEC1
эждемс	эждеда	V;IMP;PL;2;TR
роман	романце	N;NOM;SG;PSS2S;LGSPEC1
шокши	шокши	N;HUM;NOM;SG
шокшемс	шокшсазь	V;AC3;PL;3;TR
панар	панаронди	N;DAT;SG
животнай	животнайсь	N;HUM;NOM;DEF;SG;LGSPEC1
модярямс	модяряфт	V;NEG;CAUS
стамс	стан	V;SG;1;TR
уполномоченнай	уполномоченнай	N;HUM;LGSPEC1
бомж	бомжсь	N;HUM;NOM;DEF;SG;LGSPEC1
тёрка	теркань	N;GEN;SG;LGSPEC1
соламс	солафтость	V;AC3;PL;2;CAUS
салмокс	салмокска	N;NOM;SG;LGSPEC_AMP
тяшти	тяштити	N;HUM;DAT;DEF;SG
эрявиксши	эрявиксшинц	N;GEN;SG;PSS3S
лига	лигать	N;GEN;DEF;SG;LGSPEC1
адрес	адресть	N;GEN;DEF;SG;LGSPEC1
практика	практикань	N;GEN;SG;LGSPEC1
советскяй	советскяйть	ADJ;NOM;PL;LGSPEC1
шине	шиненц	N;GEN;SG;PSS3S
композитор	композитороньке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
стахановец	стахановец	N;HUM;NOM;SG;LGSPEC1
рукава	рукава	N;NOM;SG;LGSPEC1
подряднай	подряднай	ADJ;LGSPEC1
эй	эйти	N;DAT;DEF;SG
край	краень	N;GEN;SG;LGSPEC1
урма	урмаське	N;NOM;DEF;SG;LGSPEC_AMP
панжа	панжень	N;GEN;SG
сиземс	сизесть	V;AC3;PL;2;INTR
издания	изданиянди	N;DAT;SG;LGSPEC1
каменоломня	каменоломнятнень	N;GEN;PL;PSS2S;LGSPEC1
доярка	дояркати	N;HUM;DAT;DEF;SG;LGSPEC1
пяряка	пярякать	N;GEN;DEF;SG;LGSPEC1
авиатор	авиаторхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
рыжай	рыжайхне	ADJ;NOM;PL;PSS1S;LGSPEC1
мирнай	мирнайхнень	ADJ;GEN;PL;PSS1S;LGSPEC1
госпиталь	госпитальда	N;ABL;SG;LGSPEC1
гвардеец	гвардеец	N;HUM;NOM;SG;LGSPEC1
катушка	катушка	N;NOM;SG;LGSPEC1
дневник	дневникстон	N;IN+ABL;SG;PSS1S;LGSPEC1
фосфорнай	фосфорнай	ADJ;LGSPEC1
опекун	опекуттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
потяв	потяв	ADJ
фронтон	фронтонц	N;NOM;SG;PSS3S;LGSPEC1
сятяв	сятяван	ADJ;SG;1
люцерна	люцернать	N;GEN;DEF;SG;LGSPEC1
ён	ён	ADJ
сведения	сведенияда	N;ABL;SG;LGSPEC1
ряд	ряттнень	N;GEN;DEF;PL;LGSPEC1
кичкордомс	кичкордсть	V;AC3;PL;2;TR
главарь	главарь	N;HUM;NOM;SG;LGSPEC1
пурхцозамс	пурхцозафненди	V.PTCP;DAT;PL;PSS1S;PST;INTR
требования	требованиятне	N;NOM;DEF;PL;LGSPEC1
ускомс	усконь	V;SG;1;PST;TR
якамс	якалеме	V;PL;1;RMT;INTR
урожай	урожаеньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
палма	палмань	N;GEN;SG
валгомс	валголь	V;SG;3;RMT;INTR
синод	синодса	N;IN+ESS;SG;LGSPEC1
ламолгодомс	ламолгофтсы	V;AC3S;SG;3;CAUS
грипп	грипп	N;NOM;SG;LGSPEC1
инзамс	инза	V;NEG;TR
безопасность	безопасностть	N;GEN;DEF;SG;LGSPEC1
общества	обществанц	N;GEN;SG;PSS3S;LGSPEC1
паваз	павазу	N;AT+ALL;SG
сведения	сведеният	N;NOM;PL;LGSPEC1
шра	шрастост	N;IN+ABL;SG;PSS3P
стирь	стирьге	N;HUM;PROL;SG
коридор	коридорхненди	N;DAT;DEF;PL;LGSPEC1
арзя	арзятненди	N;DAT;DEF;PL
госуниверситет	госуниверситетсь	N;NOM;DEF;SG;LGSPEC1
творчества	творчества	N;NOM;SG;LGSPEC1
учёнай	ученайда	N;HUM;ABL;SG;LGSPEC1
оцязор	оцязорхнень	N;HUM;GEN;PL;PSS1S
электроника	электроника	N;NOM;SG;LGSPEC1
сура	суронзон	N;GEN;PL;PSS3S
толга	толгат	N;NOM;PL
паваз	павазга	N;NOM;SG;LGSPEC_AMP
цинга	цинга	N;NOM;SG;LGSPEC1
шаромс	шарфнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
рута	рута	N;NOM;SG;LGSPEC1
оливка	оливкатне	N;NOM;DEF;PL;LGSPEC1
век	векозон	N;IN+ALL;SG;PSS1S;LGSPEC1
ритма	ритматне	N;NOM;PL;PSS2S;LGSPEC1
госэкзамен	госэкзаменоньке	N;NOM;SG;PSS1P;LGSPEC1
статуэтка	статуэтка	N;NOM;SG;LGSPEC1
критика	критикт	N;NOM;PL;LGSPEC1
лувкс	лувксоньке	N;NOM;SG;PSS1P
стабильность	стабильности	N;AT+ALL;SG;LGSPEC1
тюк	тюкть	N;GEN;DEF;SG;LGSPEC1
актив	актифненди	N;DAT;DEF;PL;LGSPEC1
капста	капстада	N;ABL;SG;LGSPEC1
эрямс	эряфське	V.PTCP;NOM;DEF;SG;LGSPEC_AMP;PST;INTR
пяльхкя	пяльхкянтень	N;GEN;SG;PSS2P
специальность	специальностьса	N;IN+ESS;SG;LGSPEC1
тешендамс	тешендасть	V;AC3;IMP;PL;2;TR;LGSPEC1
ащемс	ащекшнесть	V;AC3;IMP;PL;2;INTR
азербайджан	азербайджанць	N;HUM;NOM;DEF;SG;LGSPEC1
пелемс	пелендемс	V;NFIN;INTR
кастрюля	кастрюляса	N;IN+ESS;SG;LGSPEC1
ремонт	ремонтть	N;GEN;DEF;SG;LGSPEC1
экскурсия	экскурсияньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
строитель	строительхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
груз	грусть	N;GEN;DEF;SG;LGSPEC1
явомс	явса	V;AC3S;SG;1;TR
куйгор	куйгорхнень	N;GEN;DEF;PL
эффект	эффект	N;NOM;SG;LGSPEC1
винань	винань	ADJ;LGSPEC1
сятяв	сятяфнень	ADJ;GEN;PL;PSS1S
строительства	строительстваснон	N;GEN;SG;PSS3P;LGSPEC1
кенярдемс	кенярделеде	V;PL;2;RMT;INTR
биатлон	биатлонць	N;NOM;DEF;SG;LGSPEC1
валомс	валонда	V;NEG;TR
алгебраическяй	алгебраическяй	ADJ;LGSPEC1
крёсналя	кресналять	N;HUM;GEN;DEF;SG;LGSPEC1
премьер-лига	премьер-лигать	N;GEN;DEF;SG;LGSPEC1
голосовандамс	голосовандамс	V;NFIN;INTR;LGSPEC1
маштомс	маштан	V;SG;1;TR
фам	фамса	N;IN+ESS;SG
ходок	ходококс	N;HUM;TRANS;SG;LGSPEC1
пичемарень	пичемарень	ADJ
ялгакстомс	ялгакстсь	V;SG;3;PST;INTR
сяземс	сяземе	V;PL;1;PST;TR
нежедемс	нежедеме	V;PL;1;PST;INTR
погон	поготтне	N;NOM;DEF;PL;LGSPEC1
тракт	трактонь	N;GEN;SG;LGSPEC1
актив	активти	N;DAT;DEF;SG;LGSPEC1
казне	казненза	N;NOM;PL;PSS3S
тядя	тядяньке	N;HUM;NOM;SG;PSS1P
делянка	делянкаста	N;IN+ABL;SG;LGSPEC1
пляма	пляманьке	N;NOM;SG;PSS1P
регистратура	регистратурав	N;AT+ALL;SG;LGSPEC1
поэт	поэтоньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
фелуцен	фелуцен	N;NOM;SG;LGSPEC1
перямс	перясть	V;AC3;PL;2;TR
пайка	пайкт	N;NOM;PL;LGSPEC1
церькав	церькафне	N;NOM;PL;PSS1S;LGSPEC1
тиемс	тифонцты	V.PTCP;DAT;SG;PSS3S;PST;TR
колокольня	колокольнясь	N;NOM;DEF;SG;LGSPEC1
вии	вии	ADJ
легкоатлет	легкоатлетоньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
калма	калмотне	N;NOM;DEF;PL
каркс	каркснень	N;GEN;PL;PSS1S
физиотерапевтическяй	физиотерапевтическяй	ADJ;LGSPEC1
абонгодомс	абонгодсть	V;AC3;IMP;PL;2;INTR
санитарка	санитарка	N;HUM;NOM;SG;LGSPEC1
понятия	понятияснон	N;GEN;SG;PSS3P;LGSPEC1
шобда	шобдать	ADJ;GEN;DEF;SG
эрямс	эряфстот	V.PTCP;IN+ABL;SG;PSS2S;PST;INTR
инзамс	инзамс	V;NFIN;TR
станция	станциятне	N;NOM;PL;PSS2S;LGSPEC1
покодемс	покоди	V;SG;3;TR
чемпионат	чемпионаттнень	N;GEN;PL;PSS2S;LGSPEC1
секретариат	секретариатонц	N;GEN;SG;PSS3S;LGSPEC1
сторожевой	сторожевой	ADJ;LGSPEC1
делегация	делегацияц	N;NOM;SG;PSS3S;LGSPEC1
баня	баняс	N;IN+ALL;SG;LGSPEC1
виздемс	виздсь	V;SG;3;PST;TR
атлетика	атлетикав	N;AT+ALL;SG;LGSPEC1
лочамс	лочасть	V;AC3;IMP;PL;2;TR
исполнитель	исполнительхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
ведень	ведень	ADJ
народность	народностть	N;GEN;DEF;SG;LGSPEC1
кулома	куломаснонды	N;DAT;SG;PSS3P
калма	калмотненди	N;DAT;PL;PSS2S
общества	обществав	N;AT+ALL;SG;LGSPEC1
алгат	алгань	N;GEN;SG
посольства	посольствась	N;NOM;DEF;SG;LGSPEC1
аспект	аспект	N;NOM;SG;LGSPEC1
влияния	влиянияц	N;NOM;SG;PSS3S;LGSPEC1
успения	успениянц	N;GEN;SG;PSS3S;LGSPEC1
спецоперация	спецоперациятнень	N;GEN;DEF;PL;LGSPEC1
получамс	получась	V;SG;3;PST;INTR;LGSPEC1
летьке	летькти	N;DAT;DEF;SG
четверть	четвертть	N;NOM;PL;LGSPEC1
розьбря	розьбрятнень	N;GEN;PL;PSS2S
сире	сиреть	ADJ;GEN;DEF;SG
пакся	паксява	N;PROL;SG
толга	толгасна	N;NOM;SG;PSS3P
вкладчик	вкладчикне	N;HUM;NOM;DEF;PL;LGSPEC1
наблюдения	наблюдениятне	N;NOM;PL;PSS2S;LGSPEC1
лайме	лаймоть	N;GEN;DEF;SG
самоуправления	самоуправления	N;NOM;SG;LGSPEC1
субсидия	субсидиятне	N;NOM;DEF;PL;LGSPEC1
ваномс	ванфтовсть	V;AC3;IMP;PL;2;CAUS;PASS
чемпион	чемпиоттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
вселеннай	вселеннайть	N;NOM;PL;LGSPEC1
седень	седень	ADJ
кргамс	кргась	V;SG;3;PST;TR
седи	седизонт	N;IN+ALL;SG;PSS2P
рдаскодомс	рдаскофта	V;NEG;CAUS
жир	жирхне	N;NOM;PL;PSS1S;LGSPEC1
свет	светонкса	N;CAUSV;SG;LGSPEC1
формула	формулатнень	N;GEN;PL;PSS2S;LGSPEC1
полезнай	полезнайда	ADJ;ABL;SG;LGSPEC1
гениальнай	гениальнайхть	ADJ;NOM;PL;LGSPEC1
ведун	ведутт	N;HUM;NOM;PL;LGSPEC1
регби	регбиса	N;IN+ESS;SG;LGSPEC1
цокольнай	цокольнай	ADJ;LGSPEC1
стихотворения	стихотворения	N;NOM;SG;LGSPEC1
сувамс	сувамазь	V;AC1;PL;3;INTR
ринг	рингс	N;IN+ALL;SG;LGSPEC1
отдел	отделхнень	N;GEN;PL;PSS1S;LGSPEC1
снимандамс	снимандать	V;SG;2;PST;TR;LGSPEC1
эрьхтемс	эрьхтемайть	V;AC1;SG;2;TR
сыр	сырське	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
азондомс	азондан	V;SG;1;TR
тапамс	тапа	V;NEG;TR
приз	призснон	N;GEN;SG;PSS3P;LGSPEC1
седи	седисонт	N;IN+ESS;SG;PSS2P
иждивенец	иждивенецсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
декабрист	декабристть	N;HUM;GEN;DEF;SG;LGSPEC1
шума	шумоце	N;NOM;SG;PSS2S
водопад	водопаттне	N;NOM;PL;PSS2S;LGSPEC1
воявай	воявай	N;HUM;LGSPEC1
мялямс	мяляфттядязь	V;AC2;PL;3;CAUS
сяваремс	сяварсть	V;PL;3;PST;INTR
полафткс	полафтксть	N;GEN;DEF;SG
католик	католикт	N;HUM;NOM;PL;LGSPEC1
васьфтемс	васьфтян	V;SG;1;TR
трос	тросонь	N;GEN;SG;LGSPEC1
словарь	словарьхненди	N;DAT;DEF;PL;LGSPEC1
шави	шавихнень	N;HUM;GEN;DEF;PL
копорь	копорь	N;NOM;SG
холодильник	холодильникнень	N;GEN;PL;PSS1S;LGSPEC1
драматург	драматургонь	N;HUM;GEN;SG;LGSPEC1
дискотека	дискотека	N;NOM;SG;LGSPEC1
топ	топти	N;DAT;DEF;SG
учительскяй	учительскяи	N;AT+ALL;SG;LGSPEC1
эрямс	эряфсост	V.PTCP;IN+ESS;SG;PSS3P;PST;INTR
варвар	варвархнень	N;HUM;GEN;DEF;PL;LGSPEC1
пианист	пианистоньке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
прамс	прават	V;SG;2;INTR;PASS
асу	асути	N;DAT;DEF;SG
перяфкс	перяфкссь	N;NOM;DEF;SG
выступандамс	выступандакшнень	V;SG;1;PST;INTR;LGSPEC1
самс	сашендыть	V;AC3;SG;2;INTR
черта	чертать	N;GEN;DEF;SG;LGSPEC1
педколледж	педколледжень	N;GEN;SG;LGSPEC1
представления	представлениять	N;GEN;DEF;SG;LGSPEC1
петьфтамс	петьфтамс	V;NFIN;TR
бра	брадонза	N;ABL;SG;PSS3S;LGSPEC1
сява	сявац	N;HUM;NOM;SG;PSS3S
радня	раднядонга	N;HUM;ABL;SG;LGSPEC_AMP;PSS1S;LGSPEC1
лядомс	лядоза	V;OPT;SG;3;INTR
энциклопедия	энциклопедияса	N;IN+ESS;SG;LGSPEC1
госпремия	госпремияса	N;IN+ESS;SG;LGSPEC1
ям	ямть	N;GEN;DEF;SG
ремесленник	ремесленникне	N;HUM;NOM;DEF;PL;LGSPEC1
лаборатория	лабораторияц	N;NOM;SG;PSS3S;LGSPEC1
значок	значокса	N;IN+ESS;SG;LGSPEC1
си	силь	N;HUM;SG;3;PST
окоп	окопонзон	N;GEN;PL;PSS3S;LGSPEC1
лафту	лафтувоц	N;NOM;SG;PSS3S
лашма	лашма	N;NOM;SG
полафткс	полафткснень	N;GEN;DEF;PL
век	века	N;PROL;SG;LGSPEC1
завод	заводсь	N;NOM;DEF;SG;LGSPEC1
потяй	потяйхнень	N;HUM;GEN;PL;PSS1S
сезон	сезонца	N;IN+ESS;SG;LGSPEC1
адрес	адресонц	N;GEN;SG;PSS3S;LGSPEC1
камфара	камфара	N;NOM;SG;LGSPEC1
питне	питнетне	N;NOM;PL;PSS2S
ведомства	ведомстваснон	N;GEN;SG;PSS3P;LGSPEC1
баня	банява	N;PROL;SG;LGSPEC1
каникула	каникулатненди	N;DAT;PL;PSS2S;LGSPEC1
статья	статьят	N;NOM;PL;LGSPEC1
пальма	пальмань	N;GEN;SG;LGSPEC1
пример	примерхт	N;NOM;PL;LGSPEC1
лазомс	лазондов	V;NEG;TR;PASS
самс	сать	V;SG;2;PST;INTR
шачемс	шачфтса	V;AC3S;SG;1;CAUS
пример	примерхнень	N;GEN;PL;PSS1S;LGSPEC1
тепловоз	тепловозса	N;IN+ESS;SG;LGSPEC1
скомня	скомнятнень	N;GEN;DEF;PL;LGSPEC1
крёз	крезоньконь	N;GEN;SG;PSS1P;LGSPEC1
губка	губка	N;NOM;SG;LGSPEC1
пресса	прессань	N;GEN;SG;LGSPEC1
концерн	концертозост	N;IN+ALL;SG;PSS3P;LGSPEC1
зерносушилка	зерносушилкада	N;ABL;SG;LGSPEC1
урядамс	урядай	V;SG;3;TR;LGSPEC1
этаж	эташнень	N;GEN;DEF;PL;LGSPEC1
гармония	гармониясь	N;NOM;DEF;SG;LGSPEC1
куда	кудань	N;HUM;GEN;SG
уштомбяль	уштомбяльса	N;IN+ESS;SG
лядемс	лятьфть	V.PTCP;GEN;DEF;SG;PST;TR
серьгядемс	серьгядсть	V;AC3;PL;2;TR
эжемс	эжсть	V;AC3;IMP;PL;2;INTR
шобдалгодомс	шобдалготкшнихть	V;PL;3;INTR
шумордамс	шумордасть	V;AC3;PL;2;TR
шарьхкодемс	шарьхкодить	V;AC3;SG;2;TR
наука	наукатне	N;NOM;PL;PSS2S;LGSPEC1
пзьгонал	пзьгоналхнень	N;GEN;PL;PSS1S
остановка	остановкатнень	N;GEN;PL;PSS2S;LGSPEC1
использования	использования	N;NOM;SG;LGSPEC1
урок	уроконзонды	N;DAT;PL;PSS3S;LGSPEC1
лексика	лексикасна	N;NOM;SG;PSS3P;LGSPEC1
суд	суд	N;NOM;SG
цятка	цятксь	N;NOM;DEF;SG
дисциплина	дисциплинатненди	N;DAT;DEF;PL;LGSPEC1
арамс	арасть	V;PL;3;PST;TR
броненосец	броненосец	N;HUM;NOM;SG;LGSPEC1
фестиваль	фестивальс	N;IN+ALL;SG;LGSPEC1
поэма	поэмасна	N;NOM;SG;PSS3P;LGSPEC1
автобус	автобуст	N;NOM;PL;LGSPEC1
сатомс	сатфтозе	V;AC3S;SG;3;CAUS
сельме	сельме	N;NOM;SG
марь	марьсь	N;NOM;DEF;SG
комамс	комафта	V;NEG;CAUS
ила	иласот	N;IN+ESS;SG;PSS2S
средняй	средняйста	ADJ;IN+ABL;SG;LGSPEC1
путомс	путфан	V.PTCP;SG;1;PST;TR
каштордомс	кашторды	V;SG;3;INTR
лишме	лишмоцень	N;HUM;GEN;SG;PSS2S;LGSPEC1
ужяльди	ужяльди	N;HUM;NOM;SG
тядя	тядянди	N;HUM;DAT;SG
шама	шамати	N;DAT;DEF;SG
клуб	клубснон	N;GEN;SG;PSS3P;LGSPEC1
шинель	шинель	N;LGSPEC1
бомбардировщик	бомбардировщикса	N;IN+ESS;SG;LGSPEC1
валенця	валенцятне	N;NOM;DEF;PL;LGSPEC1
нувамс	нувафта	V;NEG;CAUS
лыжня	лыжня	N;NOM;SG;LGSPEC1
мирде	мирдекс	N;HUM;TRANS;SG
доклад	докладснон	N;GEN;SG;PSS3P;LGSPEC1
демократия	демократия	N;NOM;SG;LGSPEC1
делегация	делегацият	N;NOM;PL;LGSPEC1
гайги	гайгихть	ADJ;GEN;DEF;SG
причастия	причастиянь	N;GEN;SG;LGSPEC1
илядомс	илядат	V;SG;2;INTR
урядай	урядайсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
ве	веста	N;IN+ABL;SG
обжамс	обжазень	V;AC3P;SG;3;TR;LGSPEC1
алимент	алиментонь	N;GEN;SG;LGSPEC1
спорямс	спорянь	V;SG;1;PST;INTR;LGSPEC1
вешка	вешкас	N;IN+ALL;SG;LGSPEC1
козяля	козялятнень	N;HUM;GEN;PL;PSS2S
валхтомс	валхтфтольхть	V;PL;3;RMT;CAUS
шуваня	шуваняста	ADJ;IN+ABL;SG
сордише	сордишеське	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
инзедемс	инзедеда	V;IMP;PL;2;TR
вакцина	вакцинась	N;NOM;DEF;SG;LGSPEC1
телевизор	телевизорхнень	N;GEN;DEF;PL;LGSPEC1
танец	танецса	N;IN+ESS;SG;LGSPEC1
мимс	мифтольхть	V;PL;3;RMT;CAUS
кяскав	кяскавса	N;IN+ESS;SG
пей	пейнтень	N;GEN;SG;PSS2P
эрьгодемс	эрьгодят	V;SG;2;INTR
доскань	доскань	ADJ;LGSPEC1
течения	течениятнень	N;GEN;PL;PSS2S;LGSPEC1
курсовой	курсовоенди	N;DAT;SG;LGSPEC1
запись	записенцты	N;DAT;SG;PSS3S;LGSPEC1
пчкяй	пчкяй	ADJ
турист	туристтненьге	N;HUM;GEN;PL;LGSPEC_AMP;PSS2S;LGSPEC1
лемех	лемехне	N;NOM;PL;PSS1S
каземс	казедязь	V;AC2S;PL;3;TR
мяль	мялезон	N;IN+ALL;SG;PSS1S
кагод	каготтненди	N;DAT;PL;PSS2S
апрель	апрельть	N;GEN;DEF;SG;LGSPEC1
поступамс	поступафтозень	V;AC3P;SG;3;CAUS;LGSPEC1
дискуссия	дискуссиять	N;GEN;DEF;SG;LGSPEC1
храм	храмста	N;IN+ABL;SG;LGSPEC1
каряз	карязти	N;DAT;DEF;SG
мишенди	мишендихне	N;HUM;NOM;PL;PSS1S
сускомс	сускфта	V.PTCP;ABL;SG;PST;TR
физика	физикаса	N;IN+ESS;SG;LGSPEC1
одкстоптомс	одкстоптф	V.PTCP;PST;TR
руця	руцяса	N;IN+ESS;SG
комментарий	комментарийхть	N;NOM;PL;LGSPEC1
панно	паннось	N;NOM;DEF;SG;LGSPEC1
кальций	кальций	N;NOM;SG;LGSPEC1
кулемс	кулендевсть	V;AC3;IMP;PL;2;TR;PASS
сявомс	сявфолень	V.PTCP;SG;1;PST;TR
колонка	колонкати	N;DAT;DEF;SG;LGSPEC1
юмамс	юмасть	V;PL;3;PST;INTR
общепит	общепитонь	N;GEN;SG;LGSPEC1
пенсия	пенсият	N;NOM;PL;LGSPEC1
шоворемс	шоворькшнесть	V;AC3;PL;2;INTR
тонафни	тонафнихтьке	N;HUM;GEN;DEF;SG;LGSPEC_AMP
симомс	симса	V;AC3S;SG;1;TR
завод	заводоньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
мазоптомс	мазоптозь	V;AC3;PL;3;TR
тиемс	тисайть	V;AC3P;SG;2;TR
трва	трват	N;NOM;PL
шумбраши	шумбрашиньке	N;NOM;SG;PSS1P
сязем	сяземс	N;IN+ALL;SG
ранендамс	ранендакшневсь	V;SG;3;PST;CAUS;LGSPEC1
бисер	бисерса	N;IN+ESS;SG;LGSPEC1
предложения	предложения	N;NOM;SG;LGSPEC1
опекун	опекуттненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
одкстоптома	одкстоптомат	N;NOM;PL
уголок	уголок	N;NOM;SG;LGSPEC1
рукава	рукаватнень	N;GEN;DEF;PL;LGSPEC1
преподаватель	преподавательхненьге	N;HUM;GEN;PL;LGSPEC_AMP;PSS1S;LGSPEC1
призыв	призывть	N;GEN;DEF;SG;LGSPEC1
трагедия	трагедияньке	N;NOM;SG;PSS1P;LGSPEC1
сатфкс	сатфкснень	N;GEN;PL;PSS1S
лакамс	лакафта	V;NEG;CAUS
баня	баня	N;NOM;SG;LGSPEC1
глухой	глухой	ADJ;LGSPEC1
двигатель	двигательхть	N;NOM;PL;LGSPEC1
или	илиень	N;GEN;SG
волна	волна	N;NOM;SG;LGSPEC1
эжемс	эжеме	V;PL;1;PST;INTR
якамс	якаль	V;SG;3;RMT;INTR
технология	технологиятнень	N;GEN;DEF;PL;LGSPEC1
фильма	фильмаса	N;IN+ESS;SG;LGSPEC1
танка	танканцты	N;DAT;SG;PSS3S;LGSPEC1
жесть	жест	N;LGSPEC1
ёфкс	ефксоньке	N;GEN;SG;LGSPEC_AMP
маслянай	маслянай	ADJ;LGSPEC1
каладомс	калафтозь	V;AC3;PL;3;CAUS
сиреши	сирешить	N;GEN;DEF;SG
национальность	национальностти	N;DAT;DEF;SG;LGSPEC1
оптика	оптикась	N;NOM;DEF;SG;LGSPEC1
щака	щакась	N;HUM;NOM;DEF;SG
ганець	ганецне	N;NOM;PL;PSS1S
урожай	урожаенди	N;DAT;SG;LGSPEC1
нонат	нонат	N;NOM;SG
съезд	съездонцты	N;DAT;SG;PSS3S;LGSPEC1
болота	болотань	N;GEN;SG;LGSPEC1
салыямс	салыяфтфста	V.PTCP;IN+ABL;SG;PST;CAUS
шире	ширензонды	N;DAT;PL;PSS3S
националист	националистокс	N;HUM;TRANS;SG;LGSPEC1
сяськома	сяськомат	N;NOM;PL
самс	савсь	V;SG;3;PST;INTR;PASS
комитет	комитеттненди	N;DAT;DEF;PL;LGSPEC1
клин	клину	N;AT+ALL;SG;LGSPEC1
сцена	сценанди	N;DAT;SG;LGSPEC1
стимул	стимулхт	N;NOM;PL;LGSPEC1
цинк	цинкта	N;ABL;SG;LGSPEC1
реорганизация	реорганизациясь	N;NOM;DEF;SG;LGSPEC1
лиана	лиана	N;NOM;SG;LGSPEC1
комсомолец	комсомолецт	N;HUM;NOM;PL;LGSPEC1
коммерческяй	коммерческяй	ADJ;LGSPEC1
шашлык	шашлыконди	N;DAT;SG;LGSPEC1
обвинительнай	обвинительнай	ADJ;LGSPEC1
роща	рощаса	N;IN+ESS;SG;LGSPEC1
продукция	продукцияньке	N;NOM;SG;PSS1P;LGSPEC1
каркс	карксне	N;NOM;DEF;PL
согласовандамс	согласовандазь	V;AC3;PL;3;TR;LGSPEC1
суд	суттненди	N;DAT;PL;PSS2S
преступник	преступникне	N;HUM;NOM;DEF;PL;LGSPEC1
салмокс	салмоксть	N;GEN;DEF;SG
технолог	технолокт	N;HUM;NOM;PL;LGSPEC1
плантация	плантацияньке	N;NOM;SG;PSS1P;LGSPEC1
куртка	куртканц	N;GEN;SG;PSS3S;LGSPEC1
радий	радий	N;NOM;SG;LGSPEC1
сандор	сандорть	N;GEN;DEF;SG
цитата	цитатать	N;GEN;DEF;SG;LGSPEC1
эзрай	эзрайста	ADJ;IN+ABL;SG
шурьхкяпря	шурьхкяпрят	N;NOM;PL
фейерверк	фейерверкне	N;NOM;PL;PSS1S;LGSPEC1
саламс	салафоль	V.PTCP;SG;3;PST;TR
люпштама	люпштамат	N;NOM;PL
первомай	первомайть	N;GEN;DEF;SG;LGSPEC1
подстрочник	подстрочникть	N;GEN;DEF;SG;LGSPEC1
печатник	печатникнень	N;HUM;GEN;DEF;PL;LGSPEC1
мрдамс	мрдафтк	V;AC3;IMP;SG;2;CAUS
урмаськодомс	урмаськододе	V;PL;2;PST;INTR
стихотворения	стихотворенияне	N;NOM;PL;PSS1S;LGSPEC1
урень	уретненди	N;HUM;DAT;DEF;PL
ашуши	ашушис	N;IN+ALL;SG
шабра	шабразень	N;HUM;GEN;SG;PSS1S
эпидемия	эпидемиятнень	N;GEN;PL;PSS2S;LGSPEC1
орёл	орел	N;HUM;NOM;SG;LGSPEC1
гектар	гектарть	N;GEN;DEF;SG;LGSPEC1
вяшкомс	вяшкондемс	V;NFIN;INTR
лакамс	лакай	V;SG;3;INTR
кельмомс	кельмофтемс	V;NFIN;CAUS
затмения	затмениять	N;GEN;DEF;SG;LGSPEC1
парендамс	парендакшнесть	V;PL;3;PST;TR;LGSPEC1
васькамс	васькафтоводе	V;PL;2;PST;CAUS;PASS
январь	январть	N;GEN;DEF;SG;LGSPEC1
эрямс	эряфснонды	V.PTCP;DAT;SG;PSS3P;PST;INTR
аппарат	аппаратсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
сцена	сценатне	N;NOM;PL;PSS2S;LGSPEC1
движения	движениятненди	N;DAT;DEF;PL;LGSPEC1
зажигалка	зажигалкась	N;NOM;DEF;SG;LGSPEC1
урожамс	урожайть	V;AC3;SG;2;INTR
вайгялю	вайгялюфт	ADJ;NOM;PL
культ	культснонды	N;DAT;SG;PSS3P;LGSPEC1
цебярь	цебярелеть	ADJ;SG;2;PST
гать	гатьнень	N;GEN;DEF;PL;LGSPEC1
терпения	терпенияц	N;NOM;SG;PSS3S;LGSPEC1
шама	шамацень	N;GEN;SG;PSS2S
коцькарга	коцькаргаснон	N;GEN;SG;PSS3P;LGSPEC1
курсовой	курсовой	N;NOM;SG;LGSPEC1
шума	шумонза	N;NOM;PL;PSS3S
чемпионка	чемпионка	N;HUM;NOM;SG;LGSPEC1
касса	кассати	N;DAT;DEF;SG;LGSPEC1
акция	акция	N;NOM;SG;LGSPEC1
верондамс	верондакшнесь	V;SG;3;PST;TR;LGSPEC1
артист	артистоньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
получамс	получакшнесть	V;PL;3;PST;INTR;LGSPEC1
шоссе	шоссети	N;DAT;DEF;SG;LGSPEC1
катания	катанияса	N;IN+ESS;SG;LGSPEC1
ОАО	оао-са	N;IN+ESS;SG;LGSPEC1
наксадомс	наксаткшнесть	V;PL;3;PST;INTR
питни	питнити	ADJ;DAT;DEF;SG
кайгомс	кайгондсть	V;AC3;IMP;PL;2;INTR
эряскодомс	эряскодат	V;SG;2;INTR
видептемс	видептесть	V;AC3;IMP;PL;2;TR
лазф	лазфнень	N;GEN;DEF;PL
производитель	производителеньконди	N;HUM;DAT;SG;PSS1P;LGSPEC1
мяль	мяльсон	N;IN+ESS;SG;PSS1S
эрямс	эряфоньконди	V.PTCP;DAT;SG;PSS1P;PST;INTR
кялемс	кяли	V;SG;3;INTR
буфет	буфету	N;AT+ALL;SG;LGSPEC1
грамма	граммань	N;GEN;SG;LGSPEC1
жувата	жуватац	N;HUM;NOM;SG;PSS3S
явомс	явондяряй	V;COND;SG;3;TR
кумбарав	кумбарафнень	N;GEN;DEF;PL
сюрьхцем	сюрьхцепт	N;NOM;PL
энергия	энергиясь	N;NOM;DEF;SG;LGSPEC1
шотнамс	шотнаса	V;AC3S;SG;1;TR
варма	вармада	N;ABL;SG
политика	политиканц	N;GEN;SG;PSS3S;LGSPEC1
парикмахер	парикмахерхне	N;HUM;NOM;DEF;PL;LGSPEC1
миниатюра	миниатюрать	N;GEN;DEF;SG;LGSPEC1
сбор	сборсь	N;NOM;DEF;SG;LGSPEC1
проект	проектта	N;ABL;SG;LGSPEC1
учебник	учебникснон	N;GEN;SG;PSS3P;LGSPEC1
музей	музеезонк	N;IN+ALL;SG;PSS1P;LGSPEC1
сюла	сюлонь	N;GEN;SG
цопай	цопай	N;HUM;NOM;SG
телефон	телефонца	N;IN+ESS;SG;LGSPEC1
тетрадь	тетраднень	N;GEN;DEF;PL;LGSPEC1
путомс	путфтсть	V;AC3;IMP;PL;2;CAUS
рамамс	раматама	V;PL;1;TR
собственность	собственностекс	N;TRANS;SG;LGSPEC1
петем	петемска	N;IN+ALL;SG;LGSPEC_AMP
рой	ройса	N;IN+ESS;SG;LGSPEC1
финно-угроведения	финно-угроведения	N;NOM;SG;LGSPEC1
вернай	вернайхть	ADJ;NOM;PL;LGSPEC1
автор	авторонди	N;HUM;DAT;SG;LGSPEC1
рамамс	рамават	V;SG;2;TR;PASS
обжамс	обжафста	V.PTCP;IN+ABL;SG;PST;TR;LGSPEC1
вокал	вокалонь	N;GEN;SG;LGSPEC1
шама	шаманьке	N;GEN;SG;LGSPEC_AMP
саламс	салать	V;SG;2;PST;TR
кит	китне	N;HUM;NOM;DEF;PL;LGSPEC1
