шождалгадомс	шождалгавтовлизе	V;AC3S;SBJV;SG;3;CAUS
прявкс	прявксонтень	N;IN+ALL;DEF;SG
апаро	апарос	ADJ;IN+ALL
лакамс	лакавтынзе	V;AC3P;SG;3;PST;CAUS
ведьвелявкс	ведьвелявкс	N;NOM;SG
эрявомс	эрявиньгак	V;SG;LGSPEC_AMP;1;PST
кепстямс	кепсти	V;SG;3
керявкс	керявксось	N;NOM;DEF;SG
виензамс	виензыть	V;SG;2;PST
валдомтомс	валдомтыть	V;SG;2;PST
икеле	икелель	N;SG;3;PST
стардомс	стардыдизь	V;AC2S;PL;3;PST
коллектив	коллективентень	N;IN+ALL;DEF;SG;LGSPEC1
оя	оятненень	N;HUM;IN+ALL;DEF;PL
репештя	репештясь	N;NOM;DEF;SG
куземс	кузеват	V;SG;2;PASS
чопавтомс	чопавтомс	V;NFIN
лецтямс	лецтинек	V;AC3;PL;1;PST
кече	кечестэ	N;IN+ABL;SG
теема	теемаст	N;NOM;SG;PSS3P
лем	лемсэнть	N;IN+ESS;DEF;SG
синдтремс	синтреде	V;IMP;PL;2
каямс	каят	V;AC3P;IMP;SG;2
бодя	бодямгак	N;HUM;NOM;SG;LGSPEC_AMP;PSS1S
яволявкс	яволявкссонок	N;IN+ESS;SG;PSS1P
бедной	бедноен	ADJ;NOM;SG;PSS1S;LGSPEC1
заочной	заочноентень	ADJ;DAT;DEF;SG;LGSPEC1
ботинка	ботинкам	N;NOM;SG;PSS1S;LGSPEC1
генштаб	генштабонтень	N;DAT;DEF;SG;LGSPEC1
пачалксе	пачалксес	N;IN+ALL;SG
миллион	миллиондо	N;ABL;SG;LGSPEC1
эрявомс	эрявкшнынь	V;AC3P;SG;1;PST
кардаз	кардазнэк	N;COM
директор	директор	N;NOM;SG;LGSPEC1
туемс	туиньгак	V;AC3P;SG;LGSPEC_AMP;1;PST
каямс	каи	V;SG;3
аштемс	аштинек	V;AC3;PL;1;PST
таштавкс	таштавкс	N;NOM;SG
лисьма	лисьматнень	N;GEN;DEF;PL
янгамс	янгимизь	V;AC1P;PST
чавола	чаволась	ADJ;NOM;DEF;SG
пачтямс	пачтилизь	V;AC3;PL;3;RMT
книга	книган	N;NOM;PL;PSS1S;LGSPEC1
масторава	масторавантень	N;DAT;DEF;SG
вадрялгадомс	вадрялгавтовлизе	V;AC3S;SBJV;SG;3;CAUS
саевкс	саевкссэ	N;IN+ESS;SG
пештямс	пештямс	V;NFIN
пандомс	пандыть	V;SG;2;PST
велосипед	велосипедэськак	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
журнал	журналонок	N;NOM;SG;PSS1P;LGSPEC1
отпуск	отпускозо	N;NOM;SG;PSS3S;LGSPEC1
кувалмо	кувалмот	N;NOM;SG;PSS2S
лецтнемс	лецтне	V;NEG
футбол	футболонть	N;GEN;DEF;SG;LGSPEC1
каямс	каясынь	V;AC3P;SG;1
буе	буензэ	N;NOM;PL;PSS3S
технолог	технолог	N;HUM;NOM;SG;LGSPEC1
навамс	нававтыдизь	V;AC2S;PL;3;PST;CAUS
стамс	ставтынек	V;AC3;PL;1;PST;CAUS
музей	музейде	N;ABL;SG;LGSPEC1
пот	потмоват	N;PROL;SG;PSS2S
потамс	потазевинь	V;AC3P;SG;1;PST
участник	участникень	N;HUM;GEN;LGSPEC1
спортсменка	спортсменканть	N;HUM;GEN;DEF;SG;LGSPEC1
таза	тазас	ADJ;IN+ALL
нерьгемс	нерьгинек	V;AC3;PL;1;PST
музыка	музыкаст	N;NOM;SG;PSS3P;LGSPEC1
кши	кшикс	N;TRANS;SG
тейтерень	тейтерентень	ADJ;DAT
роль	роль	N;NOM;SG;LGSPEC1
стакачи	стакачидензэ	N;ABL;PL;PSS3S
капшемс	капшилинь	V;AC3P;SG;1;RMT
ачарькодема	ачарькодемась	N;NOM;DEF;SG
рязанской	рязанской	ADJ;LGSPEC1
гайгемс	гайгинь	V;SG;1;PST
каштмолемс	каштмолезеви	V;SG;3
лецтямс	лецтяса	V;AC3S;SG;1
панар	панардо	N;ABL;SG
озавтнемс	озавтнетядызь	V;AC2P
ластямс	ластясь	V;SG;3;PST
кенярдомс	кенярдовтост	V;OPT;PL;3;CAUS
кадомс	кады	V;SG;3
врадомс	врадыть	V;PL;3
ёнкс	ёнксозост	N;IN+ALL;SG;PSS3P
духовной	духовнойтнень	ADJ;GEN;DEF;PL;LGSPEC1
сэняжа	сэняжанть	ADJ;GEN;DEF;SG
контора	конторанть	N;GEN;DEF;SG;LGSPEC1
сайнемс	сайнинь	V;AC3P;SG;1;PST
чивалдо	чивалдонть	N;GEN;DEF;SG
чавомс	чавоткак	V;AC3P;IMP;SG;LGSPEC_AMP;2
капшамс	капшавт	V;AC3P;IMP;SG;2;PASS
негатив	негатив	N;NOM;SG;LGSPEC1
тематика	тематикадо	N;ABL;SG;LGSPEC1
мелявкс	мелявкссонзо	N;IN+ESS;PL;PSS3S
галстук	галстукось	N;NOM;DEF;SG;LGSPEC1
пензамс	пензась	V;SG;3;PST
авечкема	авечкемась	N;NOM;DEF;SG
начко	начктано	ADJ;PL;1
территория	территорияст	N;NOM;SG;PSS3P;LGSPEC1
гала	галат	N;HUM;NOM;PL
покшолгадомс	покшолгадт	V;IMP;SG;2
сталмо	сталмозояк	N;NOM;SG;LGSPEC_AMP;PSS3S
пандомс	пандызе	V;AC3S;SG;3;PST
явомс	явовкшнось	V;SG;3;PST;PASS
пазава	пазававтомо	N;PRIV;SG
мелявкс	мелявкскак	N;NOM;SG;LGSPEC_AMP
президиум	президиумонтень	N;DAT;DEF;SG;LGSPEC1
сявордомс	сявордово	V;NEG;PASS
митинг	митингентень	N;DAT;DEF;SG;LGSPEC1
цецяв	цецяв	ADJ;NOM;SG
човорямс	човорявкшность	V;PL;3;PST;PASS
ваз	вазонтень	N;DAT;DEF;SG;LGSPEC1
синагога	синагогастонть	N;IN+ABL;DEF;SG;LGSPEC1
кундамс	кундындерясынек	V;AC3;COND;PL;1
прамс	правтан	V;AC2S;SG;1;PASS
сасамс	сасан	V;SG;1
улем	улемга	N;PROL;SG
кочкомс	кочктано	V;PL;1
гайгемс	гайгевельть	V;SBJV;PL;3
баба	бабанок	N;HUM;NOM;SG;PSS1P;LGSPEC1
корпус	корпустнэнь	N;GEN;DEF;PL;LGSPEC1
стявтнемс	стявтневить	V;SG;2;PST;PASS
тердемс	тердемскак	V;NFIN;LGSPEC_AMP
пря	прявтомо	N;PRIV;SG
здравоохранения	здравоохранениясонть	N;IN+ESS;DEF;SG;LGSPEC1
чавомс	чавитькак	V;SG;LGSPEC_AMP;2;PST
сэняжа	сэняжа	ADJ;NOM;SG
тетьксемс	тетьксизе	V;AC3S;SG;3;PST
эшкемс	эшкевкшнесь	V;SG;3;PST;PASS
квартет	квартетэнть	N;GEN;DEF;SG;LGSPEC1
грек	гректненень	N;HUM;IN+ALL;DEF;PL;LGSPEC1
сельмукшт	сельмукштнэнь	N;GEN;DEF;PL
каста	кастантень	N;DAT;DEF;SG;LGSPEC1
пшкадемс	пшкадильть	V;PL;3;RMT
крёст	крёстонтень	N;IN+ALL;DEF;SG;LGSPEC1
нолдамс	нолдавтокшнозь	V.PTCP;PST;CAUS
куншкакуро	куншкакурокс	N;TRANS;SG
кортамс	кортави	V;SG;3;PASS
кевердемс	кевердевиль	V;SG;3;RMT;PASS
нардамс	нардаван	V;SG;1;PASS
вельтямс	вельтяк	V;AC3S;IMP;SG;2
лексемс	лексить	V;PL;3
сырнень	сырненть	ADJ;NOM;PL
эске	эскетнень	N;GEN;DEF;PL
ваткамс	ваткат	V;SG;2
чачо	чачонтькак	N;GEN;DEF;SG;LGSPEC_AMP
чангодемс	чангодть	V;IMP;SG;2
лайшемс	лайшинь	V;SG;1;PST
кочкомс	кочкилинек	V;PL;1;RMT
вадря	вадряяк	ADJ;NOM;SG;LGSPEC_AMP
кинозал	кинозалсонть	N;IN+ESS;DEF;SG;LGSPEC1
кастомс	кастовлизе	V;AC3S;SBJV;SG;3
пот	потмозояк	N;IN+ALL;SG;LGSPEC_AMP
кем	кемензэ	N;NOM;PL;PSS3S
нурсемс	нурсек	V;AC3S;IMP;SG;2
кевкстямс	кевкститькак	V;PL;LGSPEC_AMP;3
лем	лемтнеде	N;ABL;DEF;PL
кедьге	кедьгес	N;IN+ALL;SG
чийнемс	чийнемс	V;NFIN
кевкстямс	кевкститькак	V;SG;LGSPEC_AMP;2;PST
нешке	нешкень	N;NOM;SG;PSS1S
вариант	вариантсонть	N;IN+ESS;DEF;SG;LGSPEC1
масторланго	масторлангсо	N;IN+ESS;SG
куншкакуро	куншкакуро	N;NOM;SG
потамс	потавтыть	V;SG;2;PST;CAUS
бюст	бюсттнэнь	N;GEN;DEF;PL;LGSPEC1
кадомс	кадовинек	V;AC3;PL;1;PST;PASS
миема	миемаст	N;NOM;SG;PSS3P
киртямс	киртимизь	V;AC1P;PST
сюдомс	сюдо	V;NEG
сочинения	сочиненият	N;NOM;SG;PSS2S;LGSPEC1
сюва	сювавтомо	N;PRIV;SG
кирьгапарь	кирьгапарьга	N;PROL;SG
консультант	консультанттнэ	N;HUM;NOM;DEF;PL;LGSPEC1
певеремс	певерсь	V;SG;3;PST
фото	фототнень	N;GEN;DEF;PL;LGSPEC1
шовинизма	шовинизмань	N;GEN;LGSPEC1
пря	прязонзо	N;IN+ALL;PL;PSS3S
паламс	палыть	V;PL;3
теште	теште	N;NOM;SG
ашо	ашот	ADJ;NOM;SG;PSS2S
пецемс	пецек	V;IMP;SG;2
невтемс	невтевель	V;SBJV;SG;3
ютнемс	ютнесызь	V;AC3;PL;3
задача	задачатненьгак	N;GEN;DEF;PL;LGSPEC_AMP;LGSPEC1
аштемс	аштят	V;SG;2
институт	институтто	N;ABL;SG;LGSPEC1
пандомс	пандомскак	V;NFIN;LGSPEC_AMP
айгор	айгоргак	N;HUM;NOM;SG;LGSPEC_AMP
превспутома	превспутомат	N;NOM;PL
яволявтомс	яволявтозельть	V.PTCP;PL;3;PST
сюконямс	сюконяволь	V;SBJV;SG;3
лемдямс	лемдидизь	V;AC2P;PST
гайгемс	гайгек	V;AC3S;IMP;SG;2
чачомс	чачови	V;SG;3;PASS
раськемастор	раськемасторсо	N;IN+ESS;SG
святой	святой	ADJ;SG;LGSPEC1
томбаланго	томбалангонтень	N;IN+ALL;DEF;SG
сёлт	сёлтканть	N;PROL;DEF;SG
онкстамс	онкстась	V;SG;3;PST
оев	оевть	ADJ;NOM;PL
газета	газетаст	N;NOM;SG;PSS3P;LGSPEC1
индекс	индексэнть	N;GEN;DEF;SG;LGSPEC1
шукшторов	шукшторов	N;NOM;SG
муевкс	муевксэзэ	N;NOM;SG;PSS3S
анокстамс	анокстыть	V;AC3P;SG;2;PST
сырне	сырнень	N;GEN
невтевкс	невтевкстнэяк	N;NOM;DEF;PL;LGSPEC_AMP
куземс	кузевить	V;SG;2;PST;PASS
булдордомс	булдордыть	V;SG;2;PST
лембелгадомс	лембелгадо	V;NEG
тошначи	тошначизэ	N;NOM;SG;PSS3S;LGSPEC1
азортомо	азортомот	ADJ;NOM;SG;PSS2S
нувсемс	нувсить	V;SG;2;PST
певеремс	певерть	V;AC3P;IMP;SG;2
урок	урокось	N;NOM;DEF;SG;LGSPEC1
венч	венчезэ	N;NOM;SG;PSS3S
сиведемс	сиведезтнестэ	V.PTCP;IN+ABL;DEF;PL;PST
нупаль	нупальтненень	N;DAT;DEF;PL
мифология	мифологиятненень	N;IN+ALL;DEF;PL;LGSPEC1
рузава	рузаваль	N;HUM;SG;3;PST;LGSPEC1
аштемс	аштиндерят	V;COND;SG;2
кастомс	кастт	V;AC3P;IMP;SG;2
сёрмадомс	сёрмадозтнень	V.PTCP;GEN;DEF;PL;PST
реформа	реформатнень	N;GEN;DEF;PL;LGSPEC1
сюлмамс	сюлмавтан	V;AC2S;SG;1;PASS
щупамс	щупасть	V;PL;3;PST;LGSPEC1
пештямс	пештятадызь	V;AC2S;PL;3
тантейгадомс	тантейгадыть	V;SG;2;PST
варчнемс	варчнить	V;AC3P;SG;2;PST
кемекстамс	кемекставинь	V;AC3P;SG;1;PST;PASS
фото	фотост	N;NOM;SG;PSS3P;LGSPEC1
вачкодемс	вачкодевинек	V;PL;1;PST;PASS
толковамс	толковинзе	V;AC3P;SG;3;PST;LGSPEC1
сея	сеянзо	N;HUM;NOM;PL;PSS3S
изнямс	изня	V;NEG
синдтремс	синтринк	V;AC3;PL;2;PST
бюст	бюстонзо	N;NOM;PL;PSS3S;LGSPEC1
комоля	комоля	N;NOM;SG
урендямс	урендить	V;PL;3
лакамс	лакавтат	V;SG;2;CAUS
ильтямс	ильтитькак	V;PL;LGSPEC_AMP;3
потямс	потявлинек	V;AC3;SBJV;PL;1
сёрмадкс	сёрмадксонтень	N;IN+ALL;DEF;SG
капшамс	капшавтымизь	V;AC1P;PST;CAUS
ванськадомс	ванськадт	V;IMP;SG;2
коршамс	коршак	V;AC3S;IMP;SG;2
ульма	ульмань	N;GEN
васькамс	васькавт	V;NEG;CAUS
эшкемс	эшкевемс	V;NFIN;PASS
этнос	этносось	N;NOM;DEF;SG;LGSPEC1
фонарь	фонарть	N;NOM;PL;LGSPEC1
стих	стихтнестэяк	N;IN+ABL;DEF;PL;LGSPEC_AMP;LGSPEC1
шумбралгадомс	шумбралгавтсынек	V;AC3;PL;1;CAUS
туемс	тусак	V;AC3S;SG;2
яровой	яровой	ADJ;LGSPEC1
куда	кудатано	N;HUM;PL;1
розорямс	розорякшны	V;SG;3;LGSPEC1
робота	роботасонть	N;IN+ESS;DEF;SG;LGSPEC1
вишка	вишкат	ADJ;SG;PSS2S
троицкой	троицкой	ADJ;NOM;SG;LGSPEC1
балл	баллт	N;NOM;PL;LGSPEC1
кадомс	кадозь	V.PTCP;PST
станция	станциясо	N;IN+ESS;SG;LGSPEC1
шлямс	шлявсь	V;SG;3;PST;PASS
справочной	справочной	ADJ;NOM;SG;LGSPEC1
панар	панартнэ	N;NOM;DEF;PL
андомс	андылимизь	V;AC1S;PL;2;RMT
сюлмамс	сюлминзе	V;AC3P;SG;3;PST
коськемс	коськезель	V.PTCP;SG;3;PST
моряк	морякось	N;HUM;NOM;DEF;SG;LGSPEC1
паця	пацязо	N;IN+ALL;SG
сюкорка	сюкоркат	N;NOM;SG;PSS2S
питней	питнеесь	ADJ;NOM;DEF;SG
симпозиум	симпозиумось	N;NOM;DEF;SG;LGSPEC1
делегация	делегациядонть	N;HUM;ABL;DEF;SG;LGSPEC1
ладямс	ладятадызь	V;AC2P;LGSPEC1
хоккеист	хоккеист	N;HUM;NOM;SG;LGSPEC1
корпус	корпусонтень	N;DAT;DEF;SG;LGSPEC1
дова	довазояк	N;HUM;IN+ALL;SG;LGSPEC_AMP;LGSPEC1
моряк	морякт	N;HUM;NOM;PL;LGSPEC1
большевик	большевикентень	N;HUM;DAT;DEF;SG;LGSPEC1
мар	маронтень	N;DAT;DEF;SG
путовкс	путовксонк	N;NOM;SG;PSS2P
каванявкс	каванявксонтень	N;IN+ALL;DEF;SG
кевердемс	кевердиде	V;PL;2;PST
чачтомс	чачтымик	V;AC1S;SG;2;PST
стардомс	стардовлидизь	V;AC2P;SBJV
заседания	заседаният	N;NOM;PL;LGSPEC1
ёртомс	ёртозенть	V.PTCP;GEN;DEF;SG;PST
юкснемс	юкснезь	V.PTCP;PST
дива	дивасть	N;GEN;DEF;SG;LGSPEC1
ракша	ракша	N;HUM;NOM;SG
музей	музейденть	N;ABL;DEF;SG;LGSPEC1
човордамс	човордыть	V;SG;2;PST
поза	позанть	N;GEN;DEF;SG
содамс	содавитькак	V;AC3P;SG;LGSPEC_AMP;2;PST;PASS
кайсемс	кайсевить	V;AC3P;SG;2;PST;PASS
кортамс	кортаваткак	V;SG;LGSPEC_AMP;2;PASS
вельмемс	вельмевтевить	V;PL;3;CAUS;PASS
казначейства	казначействань	N;GEN;LGSPEC1
вадря	вадрятнестэ	ADJ;IN+ABL;DEF;PL
коллекция	коллекциясонзо	N;IN+ESS;PL;PSS3S;LGSPEC1
паламс	палазь	V.PTCP;NOM;SG;PST
нарамс	нарыть	V;PL;3
лакамс	лакавтодо	V;IMP;PL;2;CAUS
стувтомс	стувтыдизь	V;AC2S;PL;1;PST
мордвин	мордвин	N;HUM;NOM;SG;LGSPEC1
пакся	паксядо	N;ABL;SG
тематика	тематикантень	N;DAT;DEF;SG;LGSPEC1
цюлка	цюлкасто	N;IN+ABL;SG;LGSPEC1
кадомс	кадовкшнынек	V;PL;1;PST;PASS
приказчик	приказчик	N;HUM;NOM;SG;LGSPEC1
сэдь	сэденть	N;GEN;DEF;SG
чамомс	чамсь	V;SG;3;PST
иневенч	иневенчсэнзэ	N;IN+ESS;PL;PSS3S
тарго	таргосонть	N;IN+ESS;DEF;SG
газет	газетэнтень	N;IN+ALL;DEF;SG;LGSPEC1
звания	званият	N;NOM;SG;PSS2S;LGSPEC1
канаскадомс	канаскавтызь	V;AC3;PL;3;PST;CAUS
ландямс	ландяви	V;SG;3;PASS
терявтомс	терявттано	V;PL;1
ванмопарго	ванмопаргосто	N;IN+ABL;SG
содамс	содавттадызь	V;AC2P;CAUS
терявтомс	терявтодо	V;IMP;PL;2
якамс	якавтомс	V;NFIN;CAUS
ванськадомс	ванськавтса	V;AC3S;SG;1;CAUS
полавтнемс	полавтневить	V;SG;2;PST;PASS
удомс	удовттадызь	V;AC2P;CAUS
коллектив	коллективтнеде	N;ABL;DEF;PL;LGSPEC1
животноводства	животноводствасо	N;IN+ESS;SG;LGSPEC1
касса	кассасо	N;IN+ESS;SG;LGSPEC1
территория	территорияс	N;IN+ALL;LGSPEC1
пштичи	пштичись	N;NOM;DEF;SG
кши	кшинтень	N;DAT;DEF;SG
кундамс	кундавлинь	V;AC3P;SBJV;SG;1
чеядавкс	чеядавкст	N;NOM;PL
вешнемс	вешнедеяк	V;IMP;PL;LGSPEC_AMP;2
панемс	паневтизе	V;AC3S;SG;3;PST;CAUS
чамдомс	чамдыть	V;SG;2;PST
пиже	пижеть	ADJ;SG;PSS2S
эрявиксчи	эрявиксчинтень	N;DAT;DEF;SG
строитель	строительтненень	N;HUM;DAT;DEF;PL;LGSPEC1
кочкомс	кочкизе	V;AC3S;SG;3;PST
гражданин	гражданинтнэ	N;HUM;NOM;DEF;PL;LGSPEC1
волонтёр	волонтёртнэнень	N;HUM;DAT;DEF;PL;LGSPEC1
пирявт	пирявттано	N;PL;1
вановт	вановтост	N;NOM;SG;PSS3P
пежеть	пежетензэяк	N;NOM;PL;LGSPEC_AMP;PSS3S
метра	метрасто	N;IN+ABL;SG;LGSPEC1
паломс	палт	V;AC3P;IMP;SG;2
урожай	урожаест	N;NOM;SG;PSS3P;LGSPEC1
каля	калянь	N;GEN
кадомс	кадовтан	V;AC2S;SG;1;PASS
благоустройства	благоустройствас	N;IN+ALL;LGSPEC1
источник	источниктнесэ	N;IN+ESS;DEF;PL;LGSPEC1
панжомс	панжовлизе	V;AC3S;SBJV;SG;3
час	часозонзо	N;IN+ALL;PL;PSS3S;LGSPEC1
лия	лиясто	ADJ;IN+ABL;SG
айгор	айгорошка	N;HUM;COMPV;SG
азор	азоронк	N;HUM;NOM;SG;PSS2P
видьмекс	видьмексэкс	N;TRANS;SG
храм	храмсо	N;IN+ESS;SG;LGSPEC1
каштанчи	каштанчисэ	N;IN+ESS;SG
явомс	явовтыксэлить	V;OPT;SG;2;CAUS
мелькужо	мелькужов	N;AT+ALL;SG
кенкш	кенкшенк	N;NOM;SG;PSS2P
модарька	модарькаткак	N;HUM;NOM;PL;LGSPEC_AMP
область	областесь	N;NOM;DEF;SG;LGSPEC1
нумолонь	нумолонь	ADJ;SG
стройка	стройкасонть	N;IN+ESS;DEF;SG;LGSPEC1
нарьгамс	нарьгизе	V;AC3S;SG;3;PST
ваднемс	вадневть	V;IMP;SG;2;PASS
повамс	повавлизе	V;AC3S;SBJV;SG;3
порнемс	порневть	V;AC3P;IMP;SG;2;PASS
печтемс	печтяткак	V;SG;LGSPEC_AMP;2
невтемс	невтинек	V;PL;1;PST
ливти	ливтитькак	ADJ;SG;LGSPEC_AMP;PSS2S
эйкакшчи	эйкакшчинть	N;GEN;DEF;SG
инепаз	инепазонтень	N;IN+ALL;DEF;SG
ношкалгадомс	ношкалгадыть	V;PL;3
мешамс	меши	V;SG;3
вешнемс	вешнезь	V.PTCP;PST
алтавкс	алтавксонзо	N;NOM;PL;PSS3S
васькамс	васькавтан	V;SG;1;CAUS
вирев	виревгак	ADJ;NOM;SG;LGSPEC_AMP
манчемс	манчестькак	V;PL;LGSPEC_AMP;3;PST
сялгомс	сялгимизь	V;AC1P;PST
тренировка	тренировкан	N;NOM;PL;PSS1S;LGSPEC1
керькс	керькстнэнь	N;GEN;DEF;PL
иллюстрация	иллюстрацият	N;NOM;PL;LGSPEC1
ёжо	ёжомгак	N;NOM;SG;LGSPEC_AMP;PSS1S
максомс	максовозо	V;OPT;SG;3;PASS
робота	роботат	N;NOM;PL;LGSPEC1
консерватория	консерваториянь	N;GEN;LGSPEC1
зал	залсто	N;IN+ABL;SG;LGSPEC1
специалист	специалисттэнь	N;HUM;ABL;SG;PSS1S;LGSPEC1
оев	оев	ADJ;NOM;SG
сёрма	сёрмадот	N;ABL;SG;PSS2S
нардамс	нардасызь	V;AC3;PL;3
простямс	простинь	V;AC3P;SG;1;PST;LGSPEC1
лачо	лачо	N;NOM;SG
хозяйства	хозяйстватнень	N;GEN;DEF;PL;LGSPEC1
лисьма	лисьмазо	N;NOM;SG;PSS3S
обслуживания	обслуживанияс	N;IN+ALL;SG;LGSPEC1
ахолямс	ахолязевсь	V;SG;3;PST
кусля	куслянть	N;GEN;DEF;SG;LGSPEC1
стакалгадомс	стакалгадынь	V;SG;1;PST
колхоз	колхозоськак	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
орожиямс	орожият	V;SG;2;LGSPEC1
пинень	пиненть	ADJ;NOM;PL
бюджет	бюджетстэ	N;IN+ABL;SG;LGSPEC1
лоткамс	лоткавтокшнызь	V;AC3;PL;3;PST;CAUS
митинг	митингентень	N;IN+ALL;DEF;SG;LGSPEC1
полавтнемс	полавтнекшне	V;NEG
куншка	куншказонзо	N;IN+ALL;PL;PSS3S
айгор	айгоронзо	N;HUM;NOM;PL;PSS3S
сырьгамс	сырьгавтынзе	V;AC3P;SG;3;PST;CAUS
чокшнэ	чокшнэс	N;IN+ALL;SG
больниця	больницядонть	N;ABL;DEF;SG;LGSPEC1
прогимназия	прогимназиясо	N;IN+ESS;SG;LGSPEC1
нузялдомс	нузялдтано	V;PL;1
цёра	цёран	N;HUM;NOM;PL;PSS1S
зверь	зверенть	N;HUM;GEN;DEF;SG;LGSPEC1
седей	седейстэнть	N;IN+ABL;DEF;SG
куломс	куловлизь	V;AC3;SBJV;PL;3
сабля	сабля	N;NOM;SG;LGSPEC1
кооператив	кооперативенть	N;GEN;DEF;SG;LGSPEC1
пей	пеем	N;NOM;SG;PSS1S
полуфинал	полуфиналонтень	N;DAT;DEF;SG;LGSPEC1
пря	прядо	N;ABL;SG
кажо	кажост	N;NOM;SG;PSS3P
лепштнемс	лепштнить	V;AC3P;SG;2;PST
варчнемс	варчнят	V;SG;2
коморо	коморот	N;NOM;SG;PSS2S
явомс	явовтыть	V;AC3P;SG;2;PST;CAUS
тарка	таркаль	N;SG;3;PST
невтемс	невтинь	V;SG;1;PST
кородомс	кородовить	V;PL;3;PASS
лакамс	лаказем	V.PTCP;NOM;SG;PSS1S;PST
малавикс	малавиксэть	ADJ;SG;PSS2S
алтарь	алтаренек	N;NOM;SG;PSS1P;LGSPEC1
вечкемань	вечкемантень	ADJ;DAT
ящик	ящикесь	N;NOM;DEF;SG;LGSPEC1
азор	азорозо	N;HUM;NOM;SG;PSS3S
общежития	общежитиява	N;PROL;SG;LGSPEC1
верень	веренть	ADJ;NOM;PL
кабинет	кабинет	N;NOM;SG;LGSPEC1
семия	семиява	N;PROL;SG;LGSPEC1
ручка	ручка	N;NOM;SG;LGSPEC1
край	крайганть	N;PROL;DEF;SG;LGSPEC1
выступления	выступлениянк	N;NOM;SG;PSS2P;LGSPEC1
сюдомс	сюдозь	V.PTCP;NOM;SG;PST
арфа	арфа	N;NOM;SG;LGSPEC1
чачо	чачозо	N;IN+ALL;SG
комиссия	комиссият	N;NOM;SG;PSS2S;LGSPEC1
ёмамс	ёмавтанзат	V;AC2S;SG;3;PASS
паламс	палымик	V;AC1S;SG;2;PST
пандов	пандовольть	ADJ;PL;3;PST
шлямс	шлязьгак	V.PTCP;LGSPEC_AMP;PST
таштамс	таштакшнынек	V;PL;1;PST
каладо	каладо	ADJ;NOM;SG
кирьгапаця	кирьгапацят	N;NOM;PL
нурька	нурькадо	ADJ;ABL;SG
кельмемс	кельмеськак	V;SG;LGSPEC_AMP;3;PST
ёр	ёрошканть	N;HUM;COMPV;DEF;SG
фронтовик	фронтовикекс	N;HUM;TRANS;SG;LGSPEC1
ванськадомс	ванськавтовиль	V;SG;3;RMT;CAUS;PASS
валпелькс	валпелькс	N;NOM;SG
редямс	редимим	V;AC1S;SG;3;PST
бачка	бачкатненень	N;HUM;DAT;DEF;PL
сёрма	сёрматадо	N;PL;2
валаня	валаня	ADJ;NOM;SG
ожо	ожотнень	ADJ;GEN;DEF;PL
велямс	велиль	V;SG;3;RMT
алкуксчи	алкуксчинь	N;NOM;SG;PSS1S
жанра	жанратнесэ	N;IN+ESS;DEF;PL;LGSPEC1
вакномс	вакномс	V;NFIN
пекстамс	пекстазель	V.PTCP;SG;3;PST
терявтомс	терявтынек	V;PL;1;PST
ульмамс	ульминек	V;PL;1;PST
робочей	робочеесь	N;HUM;NOM;DEF;SG;LGSPEC1
верепе	верепева	N;PROL;SG
лезэ	лезэзэяк	N;NOM;SG;LGSPEC_AMP;PSS3S
сюлмамс	сюлмазель	V.PTCP;SG;3;PST
казна	казнантень	N;DAT;DEF;SG;LGSPEC1
решётка	решёткат	N;NOM;SG;PSS2S;LGSPEC1
баран	барансонть	N;HUM;IN+ESS;DEF;SG;LGSPEC1
тарькс	тарькстнэнень	ADJ;DAT;DEF;PL
мир	мирдэнть	N;ABL;DEF;SG;LGSPEC1
уштомс	уштовт	V;AC3P;IMP;SG;2;PASS
ладямс	ладить	V;SG;2;PST;LGSPEC1
содавиксчи	содавиксчинь	N;GEN
нузякс	нузяксом	ADJ;SG;PSS1S
типография	типографиянь	N;GEN;LGSPEC1
эй	эйстэнзэ	N;IN+ABL;PL;PSS3S
сельмеведь	сельмеведекс	N;TRANS;SG
оля	оляв	N;AT+ALL;SG;LGSPEC1
панжадо	панжадо	ADJ;NOM;SG
эйде	эйдекс	N;HUM;TRANS;SG
вардо	вардотнень	N;HUM;GEN;DEF;PL
покшолма	покшолмадост	N;ABL;SG;PSS3P
шерже	шержень	N;NOM;SG;PSS1S
седейризкс	седейризксэсь	N;NOM;DEF;SG
торамо	торамосо	N;IN+ESS;SG
оска	оскасо	N;IN+ESS;SG
киртямс	киртявт	V;NEG;CAUS
прописка	прописказо	N;NOM;SG;PSS3S;LGSPEC1
престол	престолонзо	N;NOM;PL;PSS3S;LGSPEC1
плато	плато	N;NOM;SG;LGSPEC1
мадемс	мадсть	V;PL;3;PST
минерал	минералтнэ	N;NOM;DEF;PL;LGSPEC1
видьмекс	видьмекстэ	N;ABL;SG
отношения	отношенияст	N;NOM;SG;PSS3P;LGSPEC1
кирваземс	кирвазьсы	V;AC3S;SG;3
кевензамс	кевензавтынзе	V;AC3P;SG;3;PST;CAUS
мар	маронок	N;NOM;SG;PSS1P
матка	маткат	N;NOM;PL;LGSPEC1
кочксемс	кочксесть	V;PL;3;PST
каталог	каталогс	N;IN+ALL;SG;LGSPEC1
завет	заветэсь	N;NOM;DEF;SG;LGSPEC1
девиз	девизэкс	N;TRANS;SG;LGSPEC1
жанра	жанратнестэ	N;IN+ABL;DEF;PL;LGSPEC1
стамс	стакшныльть	V;PL;3;RMT
анамаз	анамаз	N;NOM;SG
нолгов	нолговось	ADJ;NOM;DEF;SG
салмуксонь	салмуксонь	ADJ;NOM;SG
филфак	филфаков	N;AT+ALL;SG;LGSPEC1
тея	теят	ADJ;NOM;PL
содамс	содасамизьгак	V;AC1S;PL;LGSPEC_AMP;2
поцемс	поцилизь	V;AC3;PL;3;RMT
ванськадомс	ванськавтыть	V;SG;2;PST;CAUS
тус	тустот	N;ABL;SG;PSS2S
рангстамс	рангстызе	V;AC3S;SG;3;PST
народ	народнэнь	N;DAT;LGSPEC1
тарка	таркатнесэяк	N;IN+ESS;DEF;PL;LGSPEC_AMP
одирьва	одирьват	N;HUM;NOM;SG;PSS2S
лепштнемс	лепштни	V;SG;3
бука	буканень	N;HUM;DAT
кедьчельке	кедьчельксэст	N;IN+ESS;SG;PSS3P
авардемс	авардемс	V;NFIN
свет	светканть	N;PROL;DEF;SG;LGSPEC1
комбайна	комбайнат	N;NOM;SG;PSS2S;LGSPEC1
философия	философиянтень	N;DAT;DEF;SG;LGSPEC1
экспозиция	экспозициязо	N;IN+ALL;SG;LGSPEC1
винтовка	винтовкатнеяк	N;NOM;DEF;PL;LGSPEC_AMP;LGSPEC1
манчемс	манчекшниль	V;SG;3;RMT
стувтнемс	стувтнетядызь	V;AC2P
пеедькшнемс	пеедькшнезьгак	V.PTCP;LGSPEC_AMP;PST
каямс	каясынек	V;AC3;PL;1
нарьгамс	нарьгить	V;PL;3
сайнемс	сайнилизь	V;AC3;PL;3;RMT
понгонемс	понгонян	V;SG;1
ош	ошканк	N;PROL;SG;PSS2P
кенде	кендев	N;AT+ALL;SG
справна	справна	ADJ;SG
фермер	фермертнэ	N;HUM;NOM;DEF;PL;LGSPEC1
ботинка	ботинканень	N;DAT;LGSPEC1
ёртомс	ёртындеряса	V;AC3S;COND;SG;1
дикарь	дикарев	N;HUM;AT+ALL;SG;LGSPEC1
расход	расходтнэ	N;NOM;DEF;PL;LGSPEC1
потямс	потязь	V.PTCP;PST
шлямс	шлян	V;SG;1
берёк	берёконтень	N;IN+ALL;DEF;SG;LGSPEC1
экономист	экономист	N;HUM;NOM;SG;LGSPEC1
нупаль	нупальга	N;PROL;SG
оя	оя	N;HUM;NOM;SG
карма	кармангак	N;NOM;PL;LGSPEC_AMP;PSS1S;LGSPEC1
простямс	простясамизь	V;AC1S;PL;2;LGSPEC1
паролгадомс	паролгавтызь	V;AC3;PL;3;PST;CAUS
пряспутомка	пряспутомкатнеяк	N;NOM;DEF;PL;LGSPEC_AMP
капшамс	капшазеват	V;SG;2
пряудем	пряудемест	N;NOM;SG;PSS3P
велямс	велят	V;AC3P;IMP;SG;2
кирдимастор	кирдимасторонтень	N;IN+ALL;DEF;SG
сасамс	сасыксэлинек	V;OPT;PL;1
культура	культурасто	N;IN+ABL;SG;LGSPEC1
эрьбамс	эрьбат	V;AC3P;IMP;SG;2
азор	азортнэньгак	N;HUM;GEN;DEF;PL;LGSPEC_AMP
памятник	памятникентень	N;IN+ALL;DEF;SG;LGSPEC1
жойнемс	жойневтсть	V;PL;3;PST;CAUS
лоткамс	лоткавтымизь	V;AC1S;PL;2;PST;CAUS
палата	палатантень	N;DAT;DEF;SG;LGSPEC1
законодательства	законодательства	N;NOM;SG;LGSPEC1
слог	слогсо	N;IN+ESS;SG;LGSPEC1
жанра	жанрасояк	N;IN+ESS;SG;LGSPEC_AMP;LGSPEC1
сыявкс	сыявкс	N;NOM;SG
ёжовчи	ёжовчисэ	N;IN+ESS;SG
прамс	правтсак	V;AC3S;SG;2;CAUS
тапарямс	тапарить	V;SG;2;PST
кснав	кснавонтень	N;DAT;DEF;SG
сан	санстонзо	N;IN+ABL;PL;PSS3S
лад	ладан	N;SG;1;LGSPEC1
тарго	таргось	N;NOM;DEF;SG
билет	билетнэнь	N;DAT;LGSPEC1
организма	организманть	N;GEN;DEF;SG;LGSPEC1
диплом	дипломонть	N;GEN;DEF;SG;LGSPEC1
заповедь	заповедесь	N;NOM;DEF;SG;LGSPEC1
кока	кокасо	N;HUM;IN+ESS;SG
рузонь	рузонть	ADJ;NOM;PL
теле	телень	N;GEN
кортамс	кортыть	V;SG;2;PST
посол	посолтнэ	N;HUM;NOM;DEF;PL;LGSPEC1
кенярксчи	кенярксчи	N;NOM;SG
пештямс	пештявсть	V;PL;3;PST;PASS
падеж	падеж	N;NOM;SG;LGSPEC1
экспонат	экспонатсо	N;IN+ESS;SG;LGSPEC1
мелькужо	мелькужонь	N;GEN
сивой	сивоест	ADJ;NOM;SG;PSS3P;LGSPEC1
кшинь	кшинь	ADJ;SG
урок	урокнень	N;DAT;LGSPEC1
лемдямс	лемдявлия	V;AC3S;SBJV;SG;1
лоткамс	лоткавтытькак	V;PL;LGSPEC_AMP;3;CAUS
вельтямс	вельтятадызь	V;AC2P
куломс	куловлинек	V;AC3;SBJV;PL;1
витькстамс	витькстан	V;SG;1
юр	юронть	N;GEN;DEF;SG
кой	койтнедеяк	N;ABL;DEF;PL;LGSPEC_AMP
пилявкс	пилявкстнэ	N;NOM;DEF;PL;LGSPEC1
кирвазтемс	кирвазтьсынзе	V;AC3P;SG;3
чевге	чевгекс	N;TRANS;SG
покшкавтнемс	покшкавтне	V;NEG
меельце	меельцесь	ADJ;NOM;DEF;SG
инечи	инечинень	N;DAT
лецтямс	лецтявитькак	V;PL;LGSPEC_AMP;3;PASS
ванськадомс	ванськавтозтяно	V.PTCP;PL;1;PST;CAUS
файл	файлтнэсэ	N;IN+ESS;DEF;PL;LGSPEC1
ёкстамс	ёкстык	V;AC3S;SG;2;PST
содыдей	содыдеекс	N;HUM;TRANS;SG
квартира	квартирам	N;NOM;SG;PSS1S;LGSPEC1
пря	прязо	N;IN+ALL;SG
пандопря	пандопрятнева	N;PROL;DEF;PL
вата	ватазо	N;NOM;SG;PSS3S;LGSPEC1
энергетик	энергетикенть	N;HUM;GEN;DEF;SG;LGSPEC1
род	родов	N;AT+ALL;SG;LGSPEC1
данной	данноест	ADJ;NOM;SG;PSS3P;LGSPEC1
пачтямс	пачтить	V;PL;3
патриотической	патриотической	ADJ;NOM;SG;LGSPEC1
потямс	потямс	V;NFIN
менстямс	менстякшнызь	V;AC3;PL;3;PST
роль	рольтнестэ	N;IN+ABL;DEF;PL;LGSPEC1
прявтвитниця	прявтвитницянь	N;HUM;GEN
пси	псизэ	ADJ;NOM;SG;PSS3S
якстердемс	якстердить	V;AC3P;SG;2;PST
сееремс	сееревть	V;IMP;SG;2;PASS
система	системань	N;GEN;LGSPEC1
манямс	манявкшныньгак	V;SG;LGSPEC_AMP;1;PST;PASS
башкачи	башкачитнень	N;GEN;DEF;PL
шлямс	шлясамизь	V;AC1P
пинге	пингедем	N;ABL;SG;PSS1S
немой	немойть	N;HUM;NOM;PL;LGSPEC1
превчи	превчинь	N;GEN
паломс	палытинь	V;AC2S;SG;1;PST
татар	татартнэяк	N;HUM;NOM;DEF;PL;LGSPEC_AMP
ярмак	ярмакось	N;NOM;DEF;SG
ни	нитне	N;HUM;NOM;DEF;PL
задания	заданиятнень	N;GEN;DEF;PL;LGSPEC1
чевтечи	чевтечисэть	N;IN+ESS;SG;PSS2S
роштува	роштувань	N;GEN;LGSPEC1
касса	кассанть	N;GEN;DEF;SG;LGSPEC1
судо	судост	N;NOM;SG;PSS3P
лайшемс	лайшитинь	V;AC2S;SG;1;PST
агрофирма	агрофирмантень	N;IN+ALL;DEF;SG;LGSPEC1
ладямс	ладякшнызе	V;AC3S;SG;3;PST;LGSPEC1
апаро	апарост	ADJ;SG;PSS3P
коня	конязо	N;IN+ALL;SG
ограниченной	ограниченной	ADJ;NOM;SG;LGSPEC1
рама	рамась	N;NOM;DEF;SG;LGSPEC1
керьксамс	керьксак	V;AC3S;IMP;SG;2
розорямс	розорясамизь	V;AC1P;LGSPEC1
яксяргонь	яксяргонень	ADJ;GEN
экшелямс	экшелинек	V;PL;1;PST
порнемс	порнинь	V;AC3P;SG;1;PST
рамсемс	рамсинек	V;PL;1;PST
прамс	празтнень	V.PTCP;GEN;DEF;PL;PST
вариант	вариантонзо	N;NOM;PL;PSS3S;LGSPEC1
толковамс	толковадо	V;IMP;PL;2;LGSPEC1
рамамс	рамилизь	V;AC3;PL;3;RMT
валморозей	валморозееньтень	N;HUM;DAT;DEF;SG
кромождомс	кроможды	V;SG;3
кунсоломс	кунсолындерясынзе	V;AC3P;COND;SG;3
хозяйства	хозяйстватне	N;NOM;DEF;PL;LGSPEC1
ильведькс	ильведькстнэс	N;IN+ALL;DEF;PL
ине	ине	ADJ;NOM;SG
чентямс	чентят	V;AC3P;IMP;SG;2
иневенч	иневенчентень	N;IN+ALL;DEF;SG
ривезень	ривезень	ADJ;SG
слог	слогт	N;NOM;PL;LGSPEC1
работник	работникень	N;HUM;GEN;LGSPEC1
жертва	жертватьнеде	N;HUM;ABL;DEF;PL;LGSPEC1
ревень	ревенть	N;NOM;PL;LGSPEC1
лисьма	лисьмась	N;NOM;DEF;SG
потолок	потолоксто	N;IN+ABL;SG;LGSPEC1
коммунизма	коммунизмасот	N;IN+ESS;SG;PSS2S;LGSPEC1
талакадомс	талакавтызе	V;AC3S;SG;3;PST;CAUS
чирьке	чирьке	N;NOM;SG
садик	садикенть	N;GEN;DEF;SG;LGSPEC1
якшамо	якшамо	N;NOM;SG
алыямс	алыян	V;SG;1
лоштямс	лоштявсь	V;SG;3;PST;PASS
представитель	представителекс	N;HUM;TRANS;SG;LGSPEC1
чапамо	чапамонь	ADJ;GEN
пандопря	пандопрят	N;NOM;PL
бюст	бюстонтень	N;IN+ALL;DEF;SG;LGSPEC1
чачомс	чачовольть	V;SBJV;PL;3
пупсемс	пупсесызь	V;AC3;PL;3
ливкс	ливксэнтень	N;IN+ALL;DEF;SG
робочей	робочейтне	N;HUM;NOM;DEF;PL;LGSPEC1
простямс	простизь	V;AC3;PL;3;PST;LGSPEC1
редямс	редясынзе	V;AC3P;SG;3
воспитательной	воспитательной	ADJ;NOM;SG;LGSPEC1
кирвазтнемс	кирвазтнить	V;SG;2;PST
невтемс	невтевезь	V.PTCP;PST;PASS
кель	келеськак	N;NOM;DEF;SG;LGSPEC_AMP
кой	койдензэ	N;ABL;PL;PSS3S
койме	коймензэ	N;NOM;PL;PSS3S
права	права	N;NOM;SG;LGSPEC1
синдемс	синдизе	V;AC3S;SG;3;PST
киртямс	киртявсть	V;PL;3;PST;PASS
алтыма	алтыматнестэ	N;IN+ABL;DEF;PL
нардамс	нардазь	V.PTCP;NOM;SG;PST
тешкстамс	тешкстымизь	V;AC1S;PL;3;PST
нилемс	нилевть	V;IMP;SG;2;PASS
ятонь	ятонть	ADJ;NOM;PL
розорямс	розорясы	V;AC3S;SG;3;LGSPEC1
ладямс	ладякшнымизь	V;AC1S;PL;3;PST;LGSPEC1
седей	седеезэ	N;NOM;SG;PSS3S
шумбралгадомс	шумбралгадсть	V;PL;3;PST
чавомс	чавозть	V.PTCP;NOM;PL;PST
доктор	докторонь	N;HUM;GEN;LGSPEC1
сеть	сеть	N;NOM;SG;LGSPEC1
изнямс	изнясамизь	V;AC1P
фотоаппарат	фотоаппаратозо	N;NOM;SG;PSS3S;LGSPEC1
превтеме	превтеметяно	ADJ;PL;1
коня	коняст	N;NOM;SG;PSS3P
кандомс	кандовлить	V;AC3P;SBJV;SG;2
сайнемс	сайнинек	V;AC3;PL;1;PST
меельце	меельцес	ADJ;IN+ALL;SG
производства	производстватнень	N;GEN;DEF;PL;LGSPEC1
кши	кшинень	N;DAT
невтемс	невтитькак	V;SG;LGSPEC_AMP;2;PST
эрявомс	эрявинь	V;AC3P;SG;1;PST
лейтенант	лейтенантось	N;HUM;NOM;DEF;SG;LGSPEC1
пурксемс	пурксить	V;PL;3
сёлт	сёлтось	N;NOM;DEF;SG
судо	судозояк	N;NOM;SG;LGSPEC_AMP;PSS3S
мельспрамо	мельспрамосонзо	N;IN+ESS;PL;PSS3S
прамс	правтыя	V;AC3S;SG;1;PST;CAUS
шукшторов	шукшторовсонть	N;IN+ESS;DEF;SG
виевчи	виевчинь	N;GEN
лотксемс	лоткси	V;SG;3
атявт	атявтот	N;HUM;NOM;SG;PSS2S
сельмекерь	сельмекерень	N;GEN
экшелямс	экшелинь	V;AC3P;SG;1;PST
смусть	смустезэ	N;NOM;SG;PSS3S
содамс	содасамизь	V;AC1S;PL;2
образ	образонтень	N;IN+ALL;DEF;SG;LGSPEC1
туемс	туевтизе	V;AC3S;SG;3;PST;CAUS
рамсемс	рамсинь	V;SG;1;PST
эскельдямс	эскельдинек	V;PL;1;PST
тов	товось	N;NOM;DEF;SG
пштилгадомс	пштилгавт	V;NEG;CAUS
ёрок	ёрокост	ADJ;SG;PSS3P
юрт	юртот	N;NOM;SG;PSS2S
сюжет	сюжетэкс	N;TRANS;SG;LGSPEC1
содамочи	содамочинтень	N;IN+ALL;DEF;SG
стувтнемс	стувтневи	V;SG;3;PASS
лакамс	лакить	V;PL;3
клюшка	клюшкасо	N;IN+ESS;SG;LGSPEC1
мероприятия	мероприятиякс	N;TRANS;SG;LGSPEC1
пазава	пазаватнестэ	N;IN+ABL;DEF;PL
гайгемс	гайгевтевить	V;SG;2;PST;CAUS;PASS
нурька	нурька	ADJ;NOM;SG
апаро	апаротне	N;NOM;DEF;PL
кургопотмо	кургопотмонок	N;NOM;SG;PSS1P
явшемс	явшинек	V;PL;1;PST
сельхозпредприятия	сельхозпредприятиянь	N;GEN;LGSPEC1
чатьмонемс	чатьмонть	V;IMP;SG;2
трибуна	трибунанть	N;GEN;DEF;SG;LGSPEC1
кухнянь	кухнянь	ADJ;LGSPEC1
ёр	ёрат	N;HUM;SG;2
ботамс	ботамс	V;NFIN
этнография	этнографиядо	N;ABL;SG;LGSPEC1
кирвазтемс	кирвазтизеяк	V;AC3S;SG;LGSPEC_AMP;3;PST
вельмемс	вельмить	V;AC3P;SG;2;PST
мелявкс	мелявкссост	N;IN+ESS;SG;PSS3P
ёнкс	ёнксканзо	N;PROL;PL;PSS3S
амолямс	амолямс	V;NFIN
ладямс	ладяви	V;SG;3;PASS;LGSPEC1
мор	морозонзо	N;IN+ALL;PL;PSS3S
кудолем	кудолемстэ	N;IN+ABL;SG
репертуар	репертуаронь	N;GEN;LGSPEC1
производства	производствантень	N;IN+ALL;DEF;SG;LGSPEC1
шлямс	шлякшнызе	V;AC3S;SG;3;PST
тешкстамс	тешкставить	V;PL;3;PASS
представитель	представителест	N;HUM;NOM;SG;PSS3P;LGSPEC1
валдомтомс	валдомтсть	V;PL;3;PST
веженсь	веженсь	ADJ;SG
анокстамс	анокстынек	V;AC3;PL;1;PST
фрукта	фруктань	N;GEN;LGSPEC1
комамс	комак	V;IMP;SG;2
старой	старой	ADJ;LGSPEC1
аволдамс	аволдаяк	V;LGSPEC_AMP;NEG
потамс	потан	V;SG;1
кувалгадомс	кувалгавтсак	V;AC3S;SG;2;CAUS
режнемс	режнезь	V.PTCP;PST
боцька	боцькат	N;NOM;PL;LGSPEC1
тапарямс	тапарявить	V;SG;2;PST;PASS
издания	изданиянок	N;NOM;SG;PSS1P;LGSPEC1
туемс	туилизь	V;AC3;PL;3;RMT
салов	салов	ADJ
содамс	содавтыть	V;AC3P;SG;2;PST;CAUS
кадра	кадрась	N;NOM;DEF;SG;LGSPEC1
ятонь	ятонь	ADJ;NOM;SG
кой	коеськак	N;NOM;DEF;SG;LGSPEC_AMP
сессия	сессиянтень	N;IN+ALL;DEF;SG;LGSPEC1
нужа	нужа	N;NOM;SG;LGSPEC1
юго-запад	юго-запад	N;NOM;SG;LGSPEC1
тулевкс	тулевкст	N;HUM;NOM;PL
кондямо	кондямолинь	ADJ;SG;1;PST
автор	автортнэненьгак	N;HUM;IN+ALL;DEF;PL;LGSPEC_AMP;LGSPEC1
лавшо	лавшольгак	ADJ;SG;LGSPEC_AMP;3;PST
кавшаня	кавшаня	ADJ
вариант	вариантозо	N;IN+ALL;SG;LGSPEC1
издательства	издательствась	N;NOM;DEF;SG;LGSPEC1
дорномс	дорныть	V;AC3P;SG;2;PST
самовар	самовардо	N;ABL;SG;LGSPEC1
пштилгадомс	пштилгавты	V;SG;3;CAUS
пачтямс	пачтизь	V;AC3;PL;3;PST
кардаз	кардазсто	N;IN+ABL;SG
инязор	инязорнэнь	N;HUM;DAT
седейстокиця	седейстокиця	ADJ;NOM;SG
содамс	содасыть	V;AC3P;SG;2
коцтонь	коцтонь	ADJ;SG
лув	лувдонть	N;ABL;DEF;SG
саам	саам	N;HUM;NOM;SG;LGSPEC1
меельце	меельцеденть	ADJ;ABL;DEF;SG
видио	видиль	N;SG;3;PST;LGSPEC1
пекстамс	пекстылинь	V;SG;1;RMT
шуба	шубань	N;GEN;LGSPEC1
сельгемс	сельгинзе	V;AC3P;SG;3;PST
кардамс	кардакшно	V;NEG
сардо	сардотне	N;NOM;DEF;PL
штердемс	штердильть	V;PL;3;RMT
шумбрачи	шумбрачитькак	N;NOM;SG;LGSPEC_AMP;PSS2S
стакачи	стакачинек	N;COM
пединститут	пединститутсонть	N;IN+ESS;DEF;SG;LGSPEC1
виемс	виевтемс	V;NFIN;CAUS
визделгадомс	визделгадсь	V;SG;3;PST
юткошка	юткошканзо	N;NOM;PL;PSS3S
проект	проектт	N;NOM;PL;LGSPEC1
песок	песок	N;NOM;SG;LGSPEC1
икеле	икельгат	N;PROL;SG;PSS2S
простямс	простявить	V;AC3P;SG;2;PST;PASS;LGSPEC1
панемс	паньсынь	V;AC3P;SG;1
кудря	кудрятненень	N;DAT;DEF;PL
оршнемс	оршнеде	V;IMP;PL;2
задача	задачанть	N;GEN;DEF;SG;LGSPEC1
вельтямс	вельтявтызе	V;AC3S;SG;3;PST;CAUS
сёрмадомс	сёрмадовлик	V;AC3S;SBJV;SG;2
пакся	паксятненень	N;DAT;DEF;PL
комбайна	комбайнанок	N;NOM;SG;PSS1P;LGSPEC1
координация	координациясост	N;IN+ESS;SG;PSS3P;LGSPEC1
мелькужо	мелькужотнева	N;PROL;DEF;PL
оска	оска	N;NOM;SG
шлямс	шляса	V;AC3S;SG;1
фермер	фермерэсь	N;HUM;NOM;DEF;SG;LGSPEC1
простямс	простязь	V.PTCP;PST;LGSPEC1
демократ	демократокс	N;HUM;TRANS;SG;LGSPEC1
чапомс	чапан	V;SG;1
мендямс	мендяк	V;AC3S;IMP;SG;2
ладямс	ладидизь	V;AC2S;PL;3;PST;LGSPEC1
невтнемс	невтневсть	V;PL;3;PST;PASS
яволявтомс	яволявтокшнымизь	V;AC1P;PST
лисьмапря	лисьмапрят	N;NOM;PL
нурямс	нурить	V;SG;2;PST
вельтямс	вельтявт	V;IMP;SG;2;PASS
циледемс	циледсь	V;SG;3;PST
кадомс	кадомизь	V;AC1P;IMP;2
стиль	стилезэ	N;IN+ALL;SG;LGSPEC1
карво	карвотне	N;HUM;NOM;DEF;PL
мунямс	муниль	V;SG;3;RMT
шатамс	шатавтово	V;NEG;CAUS;PASS;LGSPEC1
вельтямс	вельтявить	V;AC3P;SG;2;PST;PASS
пси	псить	ADJ;SG;PSS2S
рестамс	рестан	V;SG;1
чачо	чачом	N;NOM;SG;PSS1S
народ	народонок	N;NOM;SG;PSS1P;LGSPEC1
ёжовне	ёжовнеть	ADJ;SG;PSS2S
производства	производстванть	N;GEN;DEF;SG;LGSPEC1
пекстамс	пекставт	V;AC3P;IMP;SG;2;PASS
кевкстемс	кевкстьсыть	V;AC3P;SG;2
кевкстнемс	кевкстнеть	V;AC3P;IMP;SG;2
баксорямс	баксорясь	V;SG;3;PST
крандаз	крандазтомо	N;PRIV;SG
рестамс	реста	V;NEG
андомс	андовлитинь	V;AC2S;SBJV;SG;1
тов	товт	N;NOM;PL
распоряжения	распоряжениянть	N;GEN;DEF;SG;LGSPEC1
панемс	паневть	V;IMP;SG;2;PASS
отрадной	отраднойсэ	ADJ;IN+ESS;SG;LGSPEC1
кастомс	касттано	V;PL;1
пецька	пецькакс	N;TRANS;SG;LGSPEC1
эрявомс	эрявомс	V;NFIN
покштя	покштядонзо	N;HUM;ABL;PL;PSS3S
поэтесса	поэтессантень	N;HUM;DAT;DEF;SG;LGSPEC1
казне	казнеде	N;ABL;SG
сеземс	сези	V;SG;3
чиремтемс	чиремтезь	V.PTCP;NOM;SG;PST
максомс	максовлить	V;AC3P;SBJV;SG;2
масторланго	масторлангсот	N;IN+ESS;SG;PSS2S
нуема	нуемантень	N;DAT;DEF;SG
славянской	славянскойстэ	ADJ;IN+ABL;SG;LGSPEC1
сырьгамс	сырьгамс	V;NFIN
мифология	мифологиясто	N;IN+ABL;SG;LGSPEC1
чевкс	чевксстэ	N;IN+ABL;SG
оршамопель	оршамопелест	N;NOM;SG;PSS3P
ачарькодема	ачарькодемаст	N;NOM;SG;PSS3P
чугун	чугунсто	N;IN+ABL;SG
лецтнемс	лецтнить	V;SG;2;PST
панемс	панимизь	V;AC1S;PL;3;PST
ёвкстомс	ёвкстыть	V;SG;2;PST
район	районсо	N;IN+ESS;SG;LGSPEC1
фотоальбом	фотоальбомост	N;NOM;SG;PSS3P;LGSPEC1
спорткомплекс	спорткомплекссэ	N;IN+ESS;SG;LGSPEC1
уське	уськень	N;NOM;SG;PSS1S
декларация	декларациянть	N;GEN;DEF;SG;LGSPEC1
валяямс	валяят	V;AC3P;IMP;SG;2;LGSPEC1
видемс	видильть	V;PL;3;RMT
зыйть	зыйтень	N;GEN
рамсемс	рамсекшнесь	V;SG;3;PST
лисьмапря	лисьмапрястот	N;IN+ABL;SG;PSS2S
совершенной	совершенной	ADJ;NOM;SG;LGSPEC1
лайме	лайметнева	N;PROL;DEF;PL
лемдямс	лемдявлинек	V;SBJV;PL;1
фотоальбом	фотоальбом	N;NOM;SG;LGSPEC1
кунсоломс	кунсоловлить	V;AC3P;SBJV;SG;2
православия	православиясь	N;NOM;DEF;SG;LGSPEC1
ракша	ракшантень	N;HUM;IN+ALL;DEF;SG
пазонь	пазонь	ADJ;NOM;SG
оймсемс	оймсевить	V;AC3P;SG;2;PST;PASS
анокстамс	анокставильть	V;PL;3;RMT;PASS
явшемс	явшинь	V;SG;1;PST
куншкакуро	куншкакуросто	N;IN+ABL;SG
дневник	дневникеть	N;NOM;SG;PSS2S;LGSPEC1
сатомс	сатовольгак	V;SBJV;SG;LGSPEC_AMP;3
очередь	очередть	N;NOM;PL;LGSPEC1
сеель	сеельть	N;HUM;NOM;PL
выставка	выставкас	N;IN+ALL;LGSPEC1
акция	акциятне	N;NOM;DEF;PL;LGSPEC1
наряжамс	наряжинь	V;AC3P;SG;1;PST;LGSPEC1
стявтнемс	стявтнемс	V;NFIN
сюкунямс	сюкунить	V;SG;2;PST
кардаз	кардазсонк	N;IN+ESS;SG;PSS2P
пензамс	пензы	V;SG;3
невтемс	невтик	V;AC3S;SG;2;PST
вагон	вагонга	N;PROL;SG;LGSPEC1
ни	нитнененьгак	N;HUM;DAT;DEF;PL;LGSPEC_AMP
кильдемань	кильдеманть	ADJ;NOM;PL
сельмеведь	сельмеведьсэ	N;IN+ESS;SG
цянав	цянавтне	N;HUM;NOM;DEF;PL
духовка	духовкам	N;NOM;SG;PSS1S;LGSPEC1
события	событиянь	N;GEN;LGSPEC1
талика	таликат	N;NOM;PL
нузякс	нузяксокс	ADJ;TRANS;SG
агрофирма	агрофирмантень	N;DAT;DEF;SG;LGSPEC1
печкас	печкастнене	N;HUM;DAT;DEF;PL
газета	газетазо	N;IN+ALL;SG;LGSPEC1
ашо	ашо	ADJ;SG
кунсоломс	кунсоловияк	V;SG;LGSPEC_AMP;3;PASS
спортсмен	спортсментнэде	N;HUM;ABL;DEF;PL;LGSPEC1
покшолгадомс	покшолгавтынзе	V;AC3P;SG;3;PST;CAUS
вачкамс	вачкилизь	V;AC3;PL;3;RMT
салсемс	салсильгак	V;SG;LGSPEC_AMP;3;RMT
ловсос	ловсост	ADJ;NOM;PL
котьмамс	котьмить	V;AC3P;SG;2;PST
повестка	повесткасонть	N;IN+ESS;DEF;SG;LGSPEC1
вечка	вечкан	N;HUM;NOM;SG;PSS1S
майдан	майдан	N;NOM;SG;LGSPEC1
состояния	состояниязо	N;NOM;SG;PSS3S;LGSPEC1
миниатюра	миниатюратне	N;NOM;DEF;PL;LGSPEC1
людской	людской	ADJ;NOM;SG;LGSPEC1
явшемс	явшат	V;SG;2
стих	стихсэнть	N;IN+ESS;DEF;SG;LGSPEC1
авария	авария	N;NOM;SG;LGSPEC1
редямс	редясь	V;SG;3;PST
футбол	футбол	N;NOM;SG;LGSPEC1
викшневкс	викшневксэнзэ	N;NOM;PL;PSS3S
заседания	заседаниянтень	N;DAT;DEF;SG;LGSPEC1
паровоз	паровозонь	N;GEN;LGSPEC1
актёр	актёроль	N;HUM;SG;3;PST;LGSPEC1
кадомс	кадовкшныть	V;AC3P;SG;2;PST;PASS
фольклорист	фольклористэнтень	N;HUM;DAT;DEF;SG;LGSPEC1
тарка	таркасо	N;IN+ESS;SG
анок	анококс	ADJ;TRANS;SG
хозяйка	хозяйказо	N;HUM;IN+ALL;SG;LGSPEC1
родня	роднят	N;HUM;NOM;SG;PSS2S;LGSPEC1
культура	культурасост	N;IN+ESS;SG;PSS3P;LGSPEC1
мендямс	мендязь	V.PTCP;PST
седейоймамо	седейоймамос	N;IN+ALL
путкотезь	путкотезь	ADJ;NOM;SG
яжамс	яжаса	V;AC3S;SG;1
приложения	приложениянть	N;GEN;DEF;SG;LGSPEC1
соракадомс	соракадыть	V;SG;2;PST
чудикерькс	чудикерьксс	N;IN+ALL;SG
рисьме	рисьмес	N;IN+ALL;SG
пе	пензэ	N;NOM;PL;PSS3S
патят-сазорт	патят-сазортнэнь	N;HUM;DAT
ютамс	ютавтовськак	V;SG;LGSPEC_AMP;3;PST;CAUS;PASS
каток	катоктнеде	N;ABL;DEF;PL;LGSPEC1
ёндол	ёндолось	N;NOM;DEF;SG
межа	межавтомо	N;PRIV;SG;LGSPEC1
аймельгадомс	аймельгадозь	V.PTCP;NOM;SG;PST
кашамс	кашить	V;AC3P;SG;2;PST
начальник	начальниктне	N;HUM;NOM;DEF;PL;LGSPEC1
совамс	совавттадызь	V;AC2P;CAUS
онкологической	онкологической	ADJ;NOM;SG;LGSPEC1
арамс	арат	V;SG;2
мелодика	мелодикат	N;NOM;SG;PSS2S;LGSPEC1
ономастика	ономастикантень	N;IN+ALL;DEF;SG;LGSPEC1
луганаронь	луганаронть	ADJ;NOM;PL;LGSPEC1
драма	драмат	N;NOM;PL;LGSPEC1
историк	историктненень	N;HUM;IN+ALL;DEF;PL;LGSPEC1
чумондомс	чумондытькак	V;AC3P;SG;LGSPEC_AMP;2;PST
сюжетной	сюжетной	ADJ;NOM;SG;LGSPEC1
асатома	асатомаст	N;NOM;SG;PSS3P
школа	школатнеяк	N;NOM;DEF;PL;LGSPEC_AMP;LGSPEC1
вызов	вызовось	N;NOM;DEF;SG;LGSPEC1
нурдо	нурдост	N;NOM;SG;PSS3P
заметка	заметкась	N;NOM;DEF;SG;LGSPEC1
атаман	атамантнэ	N;HUM;NOM;DEF;PL;LGSPEC1
сывель	сывельгак	N;NOM;SG;LGSPEC_AMP
эрьгедемс	эрьгедезь	V.PTCP;PST
икелень	икелень	ADJ;SG
русинава	русинава	N;HUM;NOM;SG;LGSPEC1
лыкамс	лыказеве	V;NEG
цикловой	цикловой	ADJ;NOM;SG;LGSPEC1
секретарь	секретарть	N;HUM;NOM;PL;LGSPEC1
дивамс	дивавтымизь	V;AC1S;PL;3;PST;CAUS;LGSPEC1
кеверемс	кеверькшнить	V;AC3P;SG;2;PST
ютамс	ютавтымизь	V;AC1P;PST;CAUS
марямс	марявсь	V;SG;3;PST;PASS
эрьба	эрьба	N;NOM;SG;LGSPEC1
пидемс	пидесы	V;AC3S;SG;3
валдо	валдо	ADJ
пиле	пилентень	N;DAT;DEF;SG
кикс	киксэнть	N;GEN;DEF;SG
пантеон	пантеононть	N;GEN;DEF;SG;LGSPEC1
кедьчелькс	кедьчельксэст	N;NOM;SG;PSS3P
функция	функциясь	N;NOM;DEF;SG;LGSPEC1
куля	кулянь	N;GEN
идем	идемстэяк	ADJ;IN+ABL;SG;LGSPEC_AMP
пурнамс	пурнавлинь	V;SBJV;SG;1
яшма	яшмань	N;GEN;LGSPEC1
атямарь	атямартне	N;NOM;DEF;PL
цёрынька	цёрынькакс	N;HUM;TRANS;SG
арамс	аразнень	V.PTCP;DAT;PST
чемпион	чемпионат	N;HUM;SG;2;LGSPEC1
сэпей	сэпей	ADJ
совамс	совавтсть	V;PL;3;PST;CAUS
пурдтнемс	пурдтнесызь	V;AC3;PL;3
карсемапель	карсемапелень	N;GEN
правила	правилатнеяк	N;NOM;DEF;PL;LGSPEC_AMP;LGSPEC1
фразеология	фразеологиянь	N;GEN;LGSPEC1
явома	явомань	N;GEN
важо	важотнестэ	N;IN+ABL;DEF;PL
самс	саяк	V;LGSPEC_AMP;NEG
кадномс	каднымизь	V;AC1S;PL;3;PST
кармамс	карминдерян	V;COND;SG;1
курго	кургстояк	N;IN+ABL;SG;LGSPEC_AMP
номенклатура	номенклатуранть	N;GEN;DEF;SG;LGSPEC1
озкс	озксонтькак	N;GEN;DEF;SG;LGSPEC_AMP
киштемс	киштевтядызь	V;AC2P;PASS
ловномс	ловносы	V;AC3S;SG;3
левштапо	левштапосояк	N;IN+ESS;SG;LGSPEC_AMP
карелава	карелава	N;HUM;NOM;SG
чарькодемс	чарькодевитькак	V;AC3P;SG;LGSPEC_AMP;2;PST;PASS
разведка	разведкасо	N;IN+ESS;SG;LGSPEC1
эрсемс	эрсилинек	V;AC3;PL;1;RMT
каторга	каторгав	N;AT+ALL;SG;LGSPEC1
стямс	стявтыть	V;AC3P;SG;2;PST;CAUS
пожар	пожаронть	N;GEN;DEF;SG;LGSPEC1
стомавт	стомавт	ADJ;SG
керямс	керявлия	V;AC3S;SBJV;SG;1
кулялопа	кулялопат	N;NOM;SG;PSS2S
перинатальной	перинатальной	ADJ;SG;LGSPEC1
учомс	учосамизь	V;AC1P
видео	видео	N;NOM;SG;LGSPEC1
церемония	церемонияс	N;IN+ALL;LGSPEC1
полда	полданзо	N;NOM;PL;PSS3S
коник	коникеть	N;NOM;SG;PSS2S
гайнемс	гайневтян	V;SG;1;CAUS
шанжав	шанжавс	N;HUM;IN+ALL;SG
варштамс	варштасынек	V;AC3;PL;1
лиснемс	лисневить	V;PL;3;PASS
манкурт	манкуртнэнь	N;HUM;DAT;LGSPEC1
злыдардемс	злыдардить	V;SG;2;PST;LGSPEC1
кевпандо	кевпандокс	N;TRANS;SG
сад	садов	N;AT+ALL;SG;LGSPEC1
кантнемс	кантнить	V;SG;2;PST
пача	пачат	N;HUM;NOM;SG;PSS2S
герой	героесткак	N;HUM;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
старшина	старшинакс	N;HUM;TRANS;SG;LGSPEC1
литава	литава	N;NOM;SG
каштом	каштомось	N;NOM;DEF;SG
ютко	юткозонок	N;IN+ALL;SG;PSS1P
кочкамс	кочкасы	V;AC3S;SG;3
неке	некеть	ADJ;SG;PSS2S
арамс	аравтындерясынек	V;AC3;COND;PL;1;CAUS
венстямс	венстявить	V;AC3P;SG;2;PST;PASS
фура	фура	N;NOM;SG;LGSPEC1
реве	ревень	N;HUM;GEN
кочкамс	кочкимик	V;AC1S;SG;2;PST
оянь	оянтень	ADJ;DAT
потмо	потмсо	ADJ;IN+ESS;SG
чемпионат	чемпионатов	N;AT+ALL;SG;LGSPEC1
сияждомс	сияждсь	V;SG;3;PST
ресторан	ресторантнэсэ	N;IN+ESS;DEF;PL;LGSPEC1
саемс	савтадо	V;PL;2;PASS
эмблема	эмблеманть	N;GEN;DEF;SG;LGSPEC1
стройплощадка	стройплощадкасо	N;IN+ESS;SG;LGSPEC1
кортавкс	кортавксонок	N;NOM;SG;PSS1P
улемс	ульнекшны	V;SG;3
бульон	бульон	N;NOM;SG;LGSPEC1
радовамс	радовить	V;AC3P;SG;2;PST;LGSPEC1
валдомомс	валдомт	V;IMP;SG;2
цеця	цецясонть	N;IN+ESS;DEF;SG
стадия	стадия	N;NOM;SG;LGSPEC1
маней	манейденть	ADJ;ABL;DEF;SG
васолкс	васолксот	N;NOM;SG;PSS2S
произведения	произведениятнень	N;GEN;DEF;PL;LGSPEC1
микрорайон	микрорайонс	N;IN+ALL;SG;LGSPEC1
чумондомс	чумондстькак	V;PL;LGSPEC_AMP;3;PST
ювномс	ювныть	V;SG;2;PST
ингелькс	ингелькс	N;NOM;SG
ликшань	ликшань	ADJ
ядамс	ядав	V;NEG;PASS
неямс	неизеяк	V;AC3S;SG;LGSPEC_AMP;3;PST
витнемс	витневить	V;AC3P;SG;2;PST;PASS
вера	веразонк	N;IN+ALL;SG;PSS2P;LGSPEC1
обидямс	обидия	V;AC3S;SG;1;PST;LGSPEC1
кирдивий	кирдивийтненень	N;DAT;DEF;PL
ютамс	ютавттано	V;PL;1;CAUS
гастроль	гастрольтнеде	N;ABL;DEF;PL;LGSPEC1
декан	деканонь	N;HUM;GEN;LGSPEC1
эскадрилья	эскадрильят	N;NOM;PL;LGSPEC1
тапавт	тапавт	ADJ;SG
идеолог	идеологтне	N;HUM;NOM;DEF;PL;LGSPEC1
ченькс	ченькстэ	N;ABL;SG
каникула	каникулатнестэяк	N;IN+ABL;DEF;PL;LGSPEC_AMP;LGSPEC1
руз	рузонтень	ADJ;DAT;DEF;SG
ськамочи	ськамочи	N;NOM;SG
токамс	токак	V;IMP;SG;2
торама	тораманть	N;GEN;DEF;SG
упражнения	упражнениятнень	N;GEN;DEF;PL;LGSPEC1
рукава	рукават	N;NOM;PL;LGSPEC1
кежиямс	кежиявтокшнось	V;SG;3;PST;CAUS
субъект	субъект	N;NOM;SG;LGSPEC1
действия	действиятнень	N;GEN;DEF;PL;LGSPEC1
кандидат	кандидатонтень	N;HUM;DAT;DEF;SG;LGSPEC1
сёрмадомакель	сёрмадомакель	N;NOM;SG
кантнемс	кантнесь	V;SG;3;PST
спонсор	спонсордо	N;HUM;ABL;SG;LGSPEC1
баранонь	баранонь	ADJ;SG;LGSPEC1
пелькс	пелькска	ADJ;PROL;SG
гимнастической	гимнастической	ADJ;NOM;SG;LGSPEC1
яндава	яндавасонть	N;IN+ESS;DEF;SG
исследования	исследованиякс	N;TRANS;SG;LGSPEC1
тардемс	тардят	V;SG;2
тейтерьксэнь	тейтерьксэнь	ADJ;NOM;SG
меремс	меряткак	V;SG;LGSPEC_AMP;2
столекш	столекшсэ	N;IN+ESS;SG;LGSPEC1
кильдемс	кильдть	V;AC3P;IMP;SG;2
граница	границат	N;NOM;PL;LGSPEC1
шешкемс	шешкат	V;SG;2
десант	десантонть	N;GEN;DEF;SG;LGSPEC1
шинель	шинельстэнть	N;IN+ABL;DEF;SG;LGSPEC1
вастамс	вастыть	V;AC3P;SG;2;PST
надворной	надворной	ADJ;LGSPEC1
вальмань	вальмань	ADJ;NOM;SG
няшной	няшной	ADJ;LGSPEC1
медень	медентень	ADJ;DAT
сий	сийтне	N;HUM;NOM;DEF;PL
орфография	орфографиянть	N;GEN;DEF;SG;LGSPEC1
потмовий	потмовийсэ	N;IN+ESS;SG
ченярдомс	ченярдо	V;NEG
ютавтнемс	ютавтнить	V;SG;2;PST
нарде	нардевтеме	ADJ;PRIV;SG
дельтаплан	дельтаплан	N;NOM;SG;LGSPEC1
токшемс	токшимизь	V;AC1P;PST
маштыкс	маштыкссэ	N;IN+ESS;SG
оймамс	оймави	V;SG;3;PASS
калгамс	калгазь	V.PTCP;PST
ливамс	ливан	V;SG;1
ал	алдост	N;ABL;SG;PSS3P
ваномс	ванкшнови	V;SG;3;PASS
цийнемс	цийнить	V;PL;3
нармунь	нармунесь	N;HUM;NOM;DEF;SG
доклад	докладозо	N;NOM;SG;PSS3S;LGSPEC1
революционной	революционной	ADJ;NOM;SG;LGSPEC1
кабала	кабаластонть	N;IN+ABL;DEF;SG;LGSPEC1
чачи	чачиде	ADJ;ABL;SG
ума	уматнень	N;GEN;DEF;PL
усксемс	усксик	V;AC3S;SG;2;PST
трилогия	трилогиязо	N;IN+ALL;SG;LGSPEC1
зэрнемс	зэрнезевсть	V;PL;3;PST
менстемс	менстьсамизь	V;AC1P
пурнамс	пурнавлинзеяк	V;AC3P;SBJV;SG;LGSPEC_AMP;3
акт	актонь	N;GEN;LGSPEC1
меремс	меринек	V;PL;1;PST
ударения	ударение	N;NOM;SG;LGSPEC1
кажварч	кажварч	N;HUM;NOM;SG
уемс	уйкшнэсть	V;PL;3;PST
училища	училищасто	N;IN+ABL;SG;LGSPEC1
каникула	каникулат	N;NOM;SG;PSS2S;LGSPEC1
список	списокс	N;IN+ALL;SG;LGSPEC1
сумма	сумманть	N;GEN;DEF;SG;LGSPEC1
келя	келясь	N;NOM;DEF;SG
агрегат	агрегатось	N;NOM;DEF;SG;LGSPEC1
маштомс	маштсть	V;PL;3;PST
кедьёнкс	кедьёнксонть	N;GEN;DEF;SG
халява	халяват	N;NOM;SG;PSS2S;LGSPEC1
право	правось	N;NOM;DEF;SG;LGSPEC1
майор	майоран	N;HUM;SG;1;LGSPEC1
калмоланго	калмолангонь	N;GEN
морамс	морылинек	V;PL;1;RMT
кош	кош	N;NOM;SG
костямс	костятан	V;AC2S;SG;1
сектор	сектортнэсэ	N;IN+ESS;DEF;PL;LGSPEC1
кинемс	кинят	V;SG;2
тюремс	тюртяно	V;PL;1
педямс	педявозь	V.PTCP;PST;PASS
индустриальной	индустриальной	ADJ;NOM;SG;LGSPEC1
сокамс	сокить	V;PL;3
лутамс	луты	V;SG;3
пстиемс	пстиесынек	V;AC3;PL;1
онгомс	онгозевсть	V;PL;3;PST
пелькс	пелькссэнь	N;IN+ESS;SG;PSS1S
шлагбаум	шлагбаум	N;NOM;SG;LGSPEC1
гостиница	гостиницакс	N;TRANS;SG;LGSPEC1
сервер	серверс	N;IN+ALL;SG;LGSPEC1
маштомс	маштовлинь	V;AC3P;SBJV;SG;1
войска	войскасо	N;IN+ESS;SG;LGSPEC1
подгольцовой	подгольцовой	ADJ;SG;LGSPEC1
ледовитой	ледовитой	ADJ;SG;LGSPEC1
тонавтомакудо	тонавтомакудотнень	N;GEN;DEF;PL
каркс	карксокс	N;TRANS;SG
аграрий	аграриесь	N;HUM;NOM;DEF;SG;LGSPEC1
чарамс	чарат	V;AC3P;IMP;SG;2
традиционной	традиционноеть	ADJ;SG;PSS2S;LGSPEC1
кепсемс	кепсесак	V;AC3S;SG;2
артиллерия	артиллериянь	N;GEN;LGSPEC1
колобок	колобоконь	N;GEN;LGSPEC1
рангомс	рангомс	V;NFIN
междометия	междометият	N;NOM;SG;PSS2S;LGSPEC1
сезон	сезоност	N;NOM;SG;PSS3P;LGSPEC1
калмамс	калмизе	V;AC3S;SG;3;PST
националистка	националистка	N;HUM;NOM;SG;LGSPEC1
сэскемс	сэски	V;SG;3
тешкстнемс	тешкстневсь	V;SG;3;PST;PASS
срадомс	сравтсы	V;AC3S;SG;3;CAUS
перкуссия	перкуссия	N;NOM;SG;LGSPEC1
указ	указат	N;SG;2;LGSPEC1
кучомс	кучсамизь	V;AC1S;PL;3
чинев	чинев	ADJ;SG
суравка	суравка	N;NOM;SG
таргсемс	таргсесызь	V;AC3;PL;3
луговской	луговской	ADJ;NOM;SG;LGSPEC1
венстемс	венстинек	V;AC3;PL;1;PST
чарькодемс	чаркодевимизь	V;AC1S;PL;3;PST;PASS
прянь	прянь	ADJ;SG
ловатя	ловатят	N;NOM;PL
раськевтеме	раськевтеме	ADJ;SG
коридор	коридорга	N;PROL;SG;LGSPEC1
солдат	солдатт	N;HUM;NOM;PL;LGSPEC1
прищепка	прищепка	N;NOM;SG;LGSPEC1
украинец	украинецтано	N;HUM;PL;1;LGSPEC1
мозг	мозгонь	N;GEN;LGSPEC1
маласо	маласось	ADJ;NOM;DEF;SG
исследователь	исследователекс	N;HUM;TRANS;SG;LGSPEC1
оймамс	оймить	V;PL;3
сайт	сайтян	N;SG;1;LGSPEC1
тарад	тарадсто	N;IN+ABL;SG
ава	аваст	N;HUM;NOM;SG;PSS3P
миемс	миевлизе	V;AC3S;SBJV;SG;3
пурнамс	пурнавлинек	V;AC3;SBJV;PL;1
кедь	кедемгак	N;NOM;SG;LGSPEC_AMP;PSS1S
лыкамс	лыкить	V;SG;2;PST
политика	политиканть	N;GEN;DEF;SG;LGSPEC1
пине	пинесь	N;HUM;NOM;DEF;SG
очко	очков	N;AT+ALL;SG;LGSPEC1
коник	коникс	N;IN+ALL;SG
ютамс	ютасынзе	V;AC3P;SG;3
мастерок	мастероктне	N;NOM;DEF;PL;LGSPEC1
фотолув	фотолувсо	N;IN+ESS;SG
тонадомс	тонадт	V;IMP;SG;2
оймамс	оймавтан	V;AC2S;SG;1;PASS
рубин	рубин	N;NOM;SG;LGSPEC1
валпе	валпетнесэ	N;IN+ESS;DEF;PL
ансамбля	ансамблясто	N;IN+ABL;SG;LGSPEC1
совамс	совавтокшнызе	V;AC3S;SG;3;PST;CAUS
кучнемс	кучнесызь	V;AC3;PL;3
образовательной	образовательной	ADJ;NOM;SG;LGSPEC1
верькс	верькссэ	N;IN+ESS;SG
эрямопинге	эрямопингеде	N;ABL;SG
ал	алган	N;PROL;SG;PSS1S
топавтомс	топавтсынк	V;AC3;PL;2
якстере	якстеретнень	ADJ;GEN;DEF;PL
ловомс	ловильть	V;PL;3;RMT
брага	брагань	N;GEN;LGSPEC1
менстемс	менстеве	V;NEG;PASS
валямс	валявсть	V;PL;3;PST;PASS;LGSPEC1
вастамс	вастасамизь	V;AC1P
ветьке	ветькень	N;HUM;GEN
пачкодемс	пачкодемс-как	V;NFIN;LGSPEC_AMP
молемс	молевить	V;PL;3;PASS
келемтемс	келемтеви	V;SG;3;PASS
истувтомс	истувтыть	V;SG;2;PST
сэрей	сэреень	ADJ;GEN
лапша	лапшасто	N;IN+ABL;SG;LGSPEC1
каземс	казекшнизь	V;AC3;PL;3;PST
пупстнемс	пупстнить	V;SG;2;PST
станица	станицась	N;NOM;DEF;SG;LGSPEC1
руз	рузтнэненьгак	ADJ;IN+ALL;DEF;PL;LGSPEC_AMP
экология	экологиянть	N;GEN;DEF;SG;LGSPEC1
симемапель	симемапельтне	N;NOM;DEF;PL
функциональной	функциональной	ADJ;SG;LGSPEC1
сообщения	сообщениятне	N;NOM;DEF;PL;LGSPEC1
келямс	келить	V;PL;3
понгомс	понгильть	V;PL;3;RMT
пицемс	пицевсь	V;SG;3;PST;PASS
оптической	оптической	ADJ;NOM;SG;LGSPEC1
пиштяка	пиштякантень	ADJ;IN+ALL;DEF;SG
торговой	торговоесь	ADJ;NOM;DEF;SG;LGSPEC1
неямс	неить	V;SG;2;PST
учомс	учотанзат	V;AC2S;SG;3
тонгомс	тонгить	V;PL;3
эрямопинге	эрямопингентень	N;DAT;DEF;SG
совамс	совамс	V;NFIN
дательной	дательной	ADJ;LGSPEC1
канал	каналдонть	N;ABL;DEF;SG;LGSPEC1
образования	образованиянтень	N;IN+ALL;DEF;SG;LGSPEC1
гимназия	гимназиянть	N;GEN;DEF;SG;LGSPEC1
кескав	кескавонок	N;NOM;SG;PSS1P
кучомс	кучовить	V;AC3P;SG;2;PST;PASS
неемс	неезь-гак	V.PTCP;LGSPEC_AMP;PST
картинка	картинкасо	N;IN+ESS;SG;LGSPEC1
ве	веть	N;NOM;PL
пачкодемс	пачкодть	V;AC3P;IMP;SG;2
сыреждемс	сыреждезь	V.PTCP;NOM;SG;PST
гимнастической	гимнастической	ADJ;SG;LGSPEC1
вастомс	вастозь	V.PTCP;NOM;SG;PST
диван	диванонть	N;GEN;DEF;SG;LGSPEC1
стан	станонтень	N;IN+ALL;DEF;SG;LGSPEC1
лембе	лембенк	ADJ;SG;PSS2P
ожоков	ожоков	N;NOM;SG
сера	серань	N;GEN;LGSPEC1
логической	логической	ADJ;SG;LGSPEC1
восстания	восстаният	N;NOM;PL;LGSPEC1
модамарь	модамарьстэ	N;IN+ABL;SG
конёвпанкс	конёвпанкс	N;NOM;SG
замечания	замечаният	N;NOM;PL;LGSPEC1
адыг	адыгтнень	N;HUM;GEN;DEF;PL;LGSPEC1
милиция	милицияс	N;IN+ALL;LGSPEC1
печтямс	печтязь	V.PTCP;PST
учомс	учидизь	V;AC2S;PL;3;PST
гайнемс	гайневттядо	V;PL;2;CAUS
медярво	медярво	N;NOM;SG
лоподемс	лоподян	V;SG;1
поладомс	полавттан	V;AC2S;SG;1;CAUS
эцемс	эцезь	V.PTCP;PST
светодиодной	светодиодной	ADJ;LGSPEC1
монумент	монументэсь	N;NOM;DEF;SG;LGSPEC1
веле	велетнестэ	N;IN+ABL;DEF;PL
кучомс	кучовлить	V;SBJV;SG;2
сюро	сюросояк	N;IN+ESS;SG;LGSPEC_AMP
профессионал	профессионалтнэнень	N;HUM;DAT;DEF;PL;LGSPEC1
лемрисьме	лемрисьме	N;NOM;SG
томбамс	томбазь	V.PTCP;NOM;SG;PST
цярахман	цярахмандо	N;ABL;SG
кумажа	кумажазонзо	N;IN+ALL;PL;PSS3S
бандит	бандитэсь	N;HUM;NOM;DEF;SG;LGSPEC1
инфраструктура	инфраструктурасонть	N;IN+ESS;DEF;SG;LGSPEC1
пулт	пулттнэнь	N;GEN;DEF;PL
сёксь	сёкснень	N;DAT
аксиома	аксиома	N;NOM;SG;LGSPEC1
раське	раськенеккак	N;NOM;SG;LGSPEC_AMP;PSS1P
кенкшкундамо	кенкшкундамонтень	N;IN+ALL;DEF;SG
аффиксоид	аффиксоид	N;NOM;SG;LGSPEC1
таргсемс	таргсинь	V;SG;1;PST
предприятия	предприятиясо	N;IN+ESS;SG;LGSPEC1
сёрмадстомс	сёрмадстсамизь	V;AC1P
рудазыямс	рудазыявтыльть	V;PL;3;RMT;CAUS
диктор	дикторось	N;HUM;NOM;DEF;SG;LGSPEC1
гастроль	гастролев	N;AT+ALL;SG;LGSPEC1
витнемс	витнить	V;SG;2;PST
сэпе	сэпензэ	N;NOM;PL;PSS3S
садовой	садовой	ADJ;LGSPEC1
кундсемс	кундсизь	V;AC3;PL;3;PST
согласямс	согласить	V;AC3P;SG;2;PST;LGSPEC1
христианства	христианствантень	N;IN+ALL;DEF;SG;LGSPEC1
компонент	компонентнэнь	N;DAT;LGSPEC1
виднемс	видневить	V;AC3P;SG;2;PST;PASS
сусконь	сусконесь	ADJ;NOM;DEF;SG
корреспондент	корреспондентэсь	N;HUM;NOM;DEF;SG;LGSPEC1
ад	адонть	N;GEN;DEF;SG;LGSPEC1
якшавтомс	якшавты	V;SG;3
воспитатель	воспитатель	N;HUM;NOM;SG;LGSPEC1
попечительской	попечительской	ADJ;LGSPEC1
сюпавчи	сюпавчива	N;PROL;SG
носка	носкат	N;NOM;SG;PSS2S;LGSPEC1
территориальной	территориальной	ADJ;LGSPEC1
звонок	звоноктне	N;NOM;DEF;PL;LGSPEC1
комсомолец	комсомолецнэнь	N;HUM;DAT;LGSPEC1
апельсин	апельсинэсь	N;NOM;DEF;SG;LGSPEC1
нусмакалемс	нусмакале	V;NEG
ведь	ведьшка	N;COMPV;SG
учнемс	учнесть	V;PL;3;PST
токшемс	токшинзе	V;AC3P;SG;3;PST
максазей	максазейть	N;HUM;NOM;PL
совамс	совавты	V;SG;3;CAUS
меря	мерянгак	N;HUM;NOM;PL;LGSPEC_AMP;PSS1S;LGSPEC1
куло	куло	N;NOM;SG
путомс	путымизь	V;AC1S;PL;3;PST
поладомс	полавтык	V;AC3S;SG;2;PST;CAUS
торо	торотне	N;NOM;DEF;PL
поназ	поназонзо	N;NOM;PL;PSS3S
кириллица	кириллицанть	N;GEN;DEF;SG;LGSPEC1
форма	формасост	N;IN+ESS;SG;PSS3P;LGSPEC1
варштнемс	варштнеяк	V;LGSPEC_AMP;NEG
нагрузка	нагрузкатнень	N;GEN;DEF;PL;LGSPEC1
каштомо	каштомосонть	N;IN+ESS;DEF;SG
власть	властензэ	N;NOM;PL;PSS3S;LGSPEC1
саемс	саевлимизь	V;AC1P;SBJV
пандя	пандянь	N;GEN
ледстямс	ледстявтсть	V;PL;3;PST;CAUS
сводной	сводной	ADJ;SG;LGSPEC1
шукш	шукш	N;NOM;SG
вайгель	вайгельстэ	N;IN+ABL;SG
лакавтнемс	лакавтни	V;SG;3
турбина	турбина	N;NOM;SG;LGSPEC1
сыргоземс	сыргозтядо	V;PL;2
оймамс	оймавтынь	V;SG;1;PST;CAUS
саемс	саилить	V;SG;2;RMT
совамс	совавтызе	V;AC3S;SG;3;PST;CAUS
вернисаж	вернисажсо	N;IN+ESS;SG;LGSPEC1
инфекционист	инфекционистэнь	N;HUM;GEN;LGSPEC1
пувамс	пувильть	V;PL;3;RMT
универсальной	универсальной	ADJ;NOM;SG;LGSPEC1
човонь	човонькс	N;TRANS;SG
почко	почкостонть	N;IN+ABL;DEF;SG
папироса	папироса	N;NOM;SG;LGSPEC1
касомс	кассть	V;PL;3;PST
потмовий	потмовиесь	N;NOM;DEF;SG
презентационной	презентационной	ADJ;NOM;SG;LGSPEC1
ладсемс	ладсесы	V;AC3S;SG;3;LGSPEC1
эле	элезэнзэ	N;IN+ALL;PL;PSS3S
вечкемс	вечктянгак	V;AC2S;SG;LGSPEC_AMP;1
роботамс	роботынек	V;PL;1;PST;LGSPEC1
цитнемс	цитнесть	V;PL;3;PST
строчка	строчкас	N;IN+ALL;LGSPEC1
ушодомс	ушодт	V;IMP;SG;2
омбоцеде	омбоцеде	ADJ
праздник	праздниктнень	N;GEN;DEF;PL;LGSPEC1
меште	мештентень	N;IN+ALL;DEF;SG
бренд	брендэнтень	N;DAT;DEF;SG;LGSPEC1
предприятия	предприятияванть	N;PROL;DEF;SG;LGSPEC1
причастия	причастия	N;NOM;SG;LGSPEC1
пеедемс	пеедьтядызь	V;AC2S;PL;3
кудо	кудось	N;NOM;DEF;SG
варштамс	варштак	V;IMP;SG;2
пейдемс	пейдяткак	V;SG;LGSPEC_AMP;2
саемс	савтсак	V;AC3S;SG;2;CAUS
мельчкамс	мельчкамс	V;NFIN
цилига	цилигат	N;NOM;PL
чарамс	чаравтсь	V;SG;3;PST;CAUS
ёвтамс	ёвтазть	V.PTCP;NOM;PL;PST
оймамс	оймить	V;SG;2;PST
артиллерия	артиллериянть	N;GEN;DEF;SG;LGSPEC1
касомс	касовтыль	V;SG;3;RMT;CAUS
копия	копият	N;NOM;PL;LGSPEC1
лиця	лицянть	N;GEN;DEF;SG;LGSPEC1
повстанец	повстанец	N;HUM;NOM;SG;LGSPEC1
неевкс	неевкст	N;NOM;PL
гайнемс	гайневсь	V;SG;3;PST;PASS
пряка	прякаст	N;NOM;SG;PSS3P
справедливость	справедливостенть	N;GEN;DEF;SG;LGSPEC1
верблюд	верблюдт	N;HUM;NOM;PL;LGSPEC1
уставамс	уставак	V;IMP;SG;2
кемемс	кемекшнинь	V;SG;1;PST
мерка	меркан	N;NOM;PL;PSS1S;LGSPEC1
торама	торамадонть	N;ABL;DEF;SG
верце	верцетненень	ADJ;DAT;DEF;PL
марчонь	марчонь	ADJ;NOM;SG
сэрнявт	сэрнявтось	N;NOM;DEF;SG
киланго	килангованть	N;PROL;DEF;SG
аудиокассета	аудиокассета	N;NOM;SG;LGSPEC1
мурнемс	мурневить	V;AC3P;SG;2;PST;PASS
шкинемс	шкиневть	V;IMP;SG;2;PASS
кодамс	кодасыть	V;AC3P;SG;2
госпиталь	госпитальсэ	N;IN+ESS;SG;LGSPEC1
разъезд	разъездс	N;IN+ALL;SG;LGSPEC1
фраза	фразасонть	N;IN+ESS;DEF;SG;LGSPEC1
ванстомс	ванстсы	V;AC3S;SG;3
округ	округонтень	N;IN+ALL;DEF;SG;LGSPEC1
сёлгомс	сёлговить	V;AC3P;SG;2;PST;PASS
козяйка	козяйкаст	N;HUM;NOM;SG;PSS3P;LGSPEC1
настоятель	настоятельтненень	N;HUM;IN+ALL;DEF;PL;LGSPEC1
эрямоки	эрямокисэ	N;IN+ESS;SG
капельница	капельницат	N;NOM;PL;LGSPEC1
пурдамс	пурдыть	V;PL;3
пильге	пильгень	N;GEN
лекция	лекцият	N;NOM;SG;PSS2S;LGSPEC1
варштавкс	варштавкссто	N;IN+ABL;SG
инязоро	инязоротьне	N;HUM;NOM;DEF;PL
фильтрационной	фильтрационной	ADJ;LGSPEC1
физкультурной	физкультурной	ADJ;SG;LGSPEC1
певтеме	певтемель	ADJ;SG;3;PST
уло	улонзо	N;NOM;PL;PSS3S
кармамс	карматан	V;AC2S;SG;1
оператор	оператортнэнь	N;HUM;GEN;DEF;PL;LGSPEC1
лезэпарго	лезэпаргонть	N;GEN;DEF;SG
конструктор	конструкторт	N;HUM;NOM;PL;LGSPEC1
сывель	сывельде	N;ABL;SG
скирдамс	скирдат	V;AC3P;IMP;SG;2
ёвтамс	ёвтылинь	V;SG;1;RMT
лепе	лепень	N;GEN
покордамс	покордатадызь	V;AC2S;PL;1
цярахман	цярахманонть	N;GEN;DEF;SG
телевидения	телевидениясонть	N;IN+ESS;DEF;SG;LGSPEC1
пиштемс	пиштевтинь	V;AC3P;SG;1;PST;CAUS
озамс	озавтынек	V;AC3;PL;1;PST;CAUS
поэма	поэмастонть	N;IN+ABL;DEF;SG;LGSPEC1
тейтерь	тейтересь	N;HUM;NOM;DEF;SG
интернет	интернетть	N;NOM;PL;LGSPEC1
тонавтнемс	тонавтни	V;SG;3
молемс	молемскак	V;NFIN;LGSPEC_AMP
воспитания	воспитаниянть	N;GEN;DEF;SG;LGSPEC1
шкипаз	шкипазонтень	N;DAT;DEF;SG
ведьбря	ведьбрятнес	N;IN+ALL;DEF;PL
гравитация	гравитациянть	N;GEN;DEF;SG;LGSPEC1
брусок	брусокт	N;NOM;PL;LGSPEC1
арсемс	арсекшнеяк	V;LGSPEC_AMP;NEG
чиемс	чиянгак	V;SG;LGSPEC_AMP;1
саемс	саилить	V;AC3P;SG;2;RMT
неемс	невтевлинек	V;AC3;SBJV;PL;1;CAUS
очередной	очередной	ADJ;LGSPEC1
школа	школасо	N;IN+ESS;SG;LGSPEC1
ритм	ритм	N;NOM;SG;LGSPEC1
видеооператор	видеооператор	N;HUM;NOM;SG;LGSPEC1
видео	видеоськак	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
киска	кискантеньгак	N;HUM;IN+ALL;DEF;SG;LGSPEC_AMP
пистолет	пистолетэнзэ	N;NOM;PL;PSS3S;LGSPEC1
ватракш	ватракштнень	N;HUM;GEN;DEF;PL
марямс	марявкшнок	V;AC3S;IMP;SG;2;PASS
ватага	ватага	N;HUM;NOM;SG;LGSPEC1
самс	сакшнок	V;AC3S;IMP;SG;2
давления	давлениясь	N;NOM;DEF;SG;LGSPEC1
калда	калда	N;NOM;SG
планшетной	планшетной	ADJ;SG;LGSPEC1
морамс	моразевиль	V;SG;3;RMT
викинг	викингекс	N;HUM;TRANS;SG;LGSPEC1
чугунонь	чугунонь	ADJ;SG
копачамс	копачавкшнось	V;SG;3;PST;PASS
техногенной	техногенной	ADJ;LGSPEC1
каторга	каторгава	N;PROL;SG;LGSPEC1
педямс	педязь	V.PTCP;PST
строй	стройсэть	N;IN+ESS;SG;PSS2S;LGSPEC1
киска	кискантень	N;HUM;DAT;DEF;SG
канал	каналтнэнь	N;GEN;DEF;PL;LGSPEC1
пластмасса	пластмассань	N;GEN;LGSPEC1
ливтямс	ливтитькак	V;AC3P;SG;LGSPEC_AMP;2;PST
репродуктивной	репродуктивной	ADJ;LGSPEC1
тутмадемс	тутмадемс	V;NFIN
диалект	диалектэст	N;NOM;SG;PSS3P;LGSPEC1
тонавтолма	тонавтолмасо	N;IN+ESS;SG
берянь	беряньсэ	ADJ;IN+ESS;SG
сокамс	сокиль	V;SG;3;RMT
приёмной	приёмноенть	ADJ;GEN;DEF;SG;LGSPEC1
сэредемка	сэредемкат	N;NOM;SG;PSS2S
афонской	афонской	ADJ;LGSPEC1
улема	улемадонть	N;ABL;DEF;SG
учомс	учотадызь	V;AC2S;PL;3
меремс	мериль	V;SG;3;RMT
чавача	чавачас	N;HUM;IN+ALL
ума	умань	N;GEN
кота	котась	N;NOM;DEF;SG
педямс	педявтызь	V;AC3;PL;3;PST;CAUS
лията	лиятатне	ADJ;NOM;DEF;PL
коридор	коридорганть	N;PROL;DEF;SG;LGSPEC1
враг	врагокс	N;HUM;TRANS;SG;LGSPEC1
мазылгадомс	мазылгадт	V;IMP;SG;2
вор	ворон	N;HUM;NOM;SG;PSS1S;LGSPEC1
биология	биологиянь	N;GEN;LGSPEC1
нулгодемс	нулгодевтсь	V;SG;3;PST;CAUS
коклаць	коклаць	N;NOM;SG
обеспечения	обеспеченият	N;NOM;SG;PSS2S;LGSPEC1
тукшномс	тукшныть	V;AC3P;SG;2;PST
тувор	тувор	N;NOM;SG
ве	веденть	N;ABL;DEF;SG
сельведь	сельведьс	N;IN+ALL;SG
поцердемс	поцердить	V;SG;2;PST
сульть	сультень	N;GEN
болота	болотасо	N;IN+ESS;SG;LGSPEC1
физкультурник	физкультурникень	N;HUM;GEN;LGSPEC1
модной	модной	ADJ;NOM;SG;LGSPEC1
тонавтнемс	тонавтнеть	V;AC3P;IMP;SG;2
кудо	кудон	N;NOM;PL;PSS1S
пидемс	пидезесь	V.PTCP;NOM;DEF;SG;PST
пеле	пелентень	N;IN+ALL;DEF;SG
позакши	позакшитнень	N;GEN;DEF;PL
пачколемс	пачколинек	V;AC3;PL;1;PST
авиде	авиде	ADJ;SG
кудопотмар	кудопотмаров	N;AT+ALL;SG
скал	скалтнэнень	N;HUM;IN+ALL;DEF;PL
разнарядка	разнарядканзо	N;NOM;PL;PSS3S;LGSPEC1
кельваря	кельварясо	N;IN+ESS;SG
пещера	пещерав	N;AT+ALL;SG;LGSPEC1
оламс	олакшно	V;NEG
шнамс	шнавт	V;IMP;SG;2;PASS
эстононь	эстононь	ADJ;NOM;SG
аразь	араздензэ	N;ABL;PL;PSS3S
варака	варакат	N;HUM;NOM;SG;PSS2S
менеджер	менеджертнэде	N;HUM;ABL;DEF;PL;LGSPEC1
ламо	ламолинек	N;PL;1;PST
аздамс	аздат	V;AC3P;IMP;SG;2
азбука	азбукантькак	N;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
брак	брактне	N;NOM;DEF;PL;LGSPEC1
кашкамс	кашказь	V.PTCP;PST
синтремс	синтревить	V;AC3P;SG;2;PST;PASS
кальдердемс	кальдердить	V;AC3P;SG;2;PST
плаштя	плаштятнень	N;GEN;DEF;PL
кирвамс	кирвазевть	V;AC3P;IMP;SG;2
вейсэндявкс	вейсэндявкстонть	N;ABL;DEF;SG
шина	шинат	N;NOM;SG;PSS2S;LGSPEC1
дух	духсо	N;IN+ESS;SG;LGSPEC1
преступной	преступной	ADJ;NOM;SG;LGSPEC1
ислам	исламонтень	N;IN+ALL;DEF;SG
авждамс	авждамс	V;NFIN
зэхель	зэхелесь	N;NOM;DEF;SG
кошт	коштто	N;ABL;SG
лихой	лихой	ADJ;LGSPEC1
марсемс	марсекшнить	V;AC3P;SG;2;PST
налкстамс	налкставить	V;PL;3;PASS
нравственность	нравственностень	N;GEN;LGSPEC1
кочкодык	кочкодыкентень	N;HUM;IN+ALL;DEF;SG
платия	платият	N;NOM;PL;LGSPEC1
козкстамс	козксты	V;SG;3
пувтамс	пувтыдизь	V;AC2P;PST
чудожов	чудожов	N;NOM;SG
турва	турвастонзо	N;IN+ABL;PL;PSS3S
ледемс	ледевть	V;IMP;SG;2;PASS
кирдивий	кирдивиеськак	N;NOM;DEF;SG;LGSPEC_AMP
келе	келень	N;GEN
курка	куркасткак	N;HUM;NOM;SG;LGSPEC_AMP;PSS3P
беларус	беларустне	N;HUM;NOM;DEF;PL;LGSPEC1
тандадомс	тандадокшнось	V;SG;3;PST
ледстнемс	ледстник	V;AC3S;SG;2;PST
мельёжо	мельёжозо	N;IN+ALL;SG
куко	куко	N;HUM;NOM;SG
макснемс	макснинек	V;PL;1;PST
шабра	шабра	N;HUM;NOM;SG
судостроительной	судостроительной	ADJ;SG;LGSPEC1
радиокомпания	радиокомпаниятненень	N;IN+ALL;DEF;PL;LGSPEC1
инстаграм	инстаграмт	N;NOM;PL;LGSPEC1
кан	кантне	N;NOM;DEF;PL
энциклопедия	энциклопедият	N;NOM;PL;LGSPEC1
конямс	конязь	V.PTCP;NOM;SG;PST
баляга	балягатнеяк	N;NOM;DEF;PL;LGSPEC_AMP
обсуждения	обсужденияс	N;IN+ALL;LGSPEC1
лавгамс	лавги	V;SG;3
пеедемс	пеедькшниль	V;SG;3;RMT
кир	кир	ADJ
правительства	правительствасонть	N;IN+ESS;DEF;SG;LGSPEC1
чумондомс	чумондтадызь	V;AC2P
порьмепель	порьмепельть	N;NOM;PL
пенгедемс	пенгедезь	V.PTCP;PST
вера	веразо	N;NOM;SG;PSS3S;LGSPEC1
оршамс	оршакшность	V;PL;3;PST
пстидемс	пстидинзе	V;AC3P;SG;3;PST
топода-сэнь	топода-сэнь	ADJ;SG
эффективной	эффективной	ADJ;LGSPEC1
пляж	пляжт	N;NOM;PL;LGSPEC1
найманонь	найманонь	ADJ
лей	лейтненьгак	N;GEN;DEF;PL;LGSPEC_AMP
ёзамс	ёза	V;NEG
принцесса	принцессанть	N;HUM;GEN;DEF;SG;LGSPEC1
нартнемс	нардтнить	V;PL;3
самс	савсь	V;SG;3;PST;PASS
котьма	котьмат	N;HUM;NOM;PL
доцент	доцент	N;HUM;NOM;SG;LGSPEC1
срадомс	сравтыть	V;SG;2;PST;CAUS
бугульминской	бугульминской	ADJ;LGSPEC1
сокамс	сокавтынек	V;AC3;PL;1;PST;CAUS
короб	короб	N;NOM;SG;LGSPEC1
связист	связисттнэ	N;HUM;NOM;DEF;PL;LGSPEC1
пелямс	пелить	V;SG;2;PST
аварийной	аварийной	ADJ;SG;LGSPEC1
печкемс	печкезель	V.PTCP;SG;3;PST
чачтнемс	чачтнить	V;PL;3
ушодомс	ушодыя	V;AC3S;SG;1;PST
мештетешкс	мештетешкс	N;NOM;SG
докладной	докладной	N;NOM;SG;LGSPEC1
кузнемс	кузне	V;NEG
симемс	симить	V;SG;2;PST
сятко	сятконень	N;DAT
саемс	саия	V;AC3S;SG;1;PST
реп	репость	N;GEN;DEF;SG;LGSPEC1
раське	раськеньгак	N;NOM;SG;LGSPEC_AMP;PSS1S
нупонев	нупонев	ADJ;NOM;SG
живой	живоесь	ADJ;NOM;DEF;SG;LGSPEC1
седеень	седеенть	ADJ;NOM;PL
одра	одратьненень	N;IN+ALL;DEF;PL
тапамс	тапат	V;AC3P;IMP;SG;2
толбандя	толбандякс	N;TRANS;SG
заведения	заведеният	N;NOM;PL;LGSPEC1
менель	менелеськак	N;NOM;DEF;SG;LGSPEC_AMP
агглюнативной	агглюнативной	ADJ;LGSPEC1
нусманячи	нусманячинь	N;GEN
лейчире	лейчирень	N;GEN
тетя	тетястонзо	N;HUM;IN+ABL;PL;PSS3S
ютко	юткова	N;PROL;SG
люкша	люкша	N;HUM;NOM;SG
тулодомс	тулодомс	V;NFIN
крепость	крепостьсэ	N;IN+ESS;SG;LGSPEC1
пурдавкс	пурдавксонть	N;GEN;DEF;SG
ризкс	ризксэнтень	N;DAT;DEF;SG
латякарь	латякарть	ADJ;NOM;PL
ёзамс	ёзазь	V.PTCP;PST
ки	кикс	N;TRANS;SG
роботамс	роботыть	V;SG;2;PST;LGSPEC1
ён	ёнонть	N;GEN;DEF;SG
атякш	атякшонть	N;HUM;GEN;DEF;SG
боевой	боевой	ADJ;SG;LGSPEC1
чимадема	чимадема	N;NOM;SG
теемс	теевельгак	V;SBJV;SG;LGSPEC_AMP;3
спорямс	спорить	V;PL;3;LGSPEC1
морамс	морангак	V;SG;LGSPEC_AMP;1
вадрячи	вадрячисэнзэ	N;IN+ESS;PL;PSS3S
технопарк	технопарконть	N;GEN;DEF;SG;LGSPEC1
левой	левой	ADJ;NOM;SG;LGSPEC1
эзь	эзимик	V;AC1S;SG;2;NEG;PST
пособия	пособиясь	N;NOM;DEF;SG;LGSPEC1
терроризма	терроризманть	N;GEN;DEF;SG;LGSPEC1
ой	оевгак	N;AT+ALL;SG;LGSPEC_AMP
коламс	кола	V;NEG
сад	садокс	N;TRANS;SG;LGSPEC1
театрализованной	театрализованной	ADJ;NOM;SG;LGSPEC1
шляпа	шляпань	N;GEN;LGSPEC1
кучомс	кучсызь	V;AC3;PL;3
стямс	стявтовильть	V;PL;3;RMT;CAUS;PASS
марлянь	марлянь	ADJ;LGSPEC1
симемс	сименк	V;AC1S;IMP;PL;2
чавномс	чавнозь	V.PTCP;NOM;SG;PST
эрмитаж	эрмитажонтень	N;DAT;DEF;SG;LGSPEC1
печтямс	печтявсь	V;SG;3;PST;PASS
шта	штадот	N;ABL;SG;PSS2S
кантнемс	кантнидизь	V;AC2S;PL;3;PST
верь	верьга	N;PROL;SG
ванномс	ваннозельть	V.PTCP;PL;3;PST
готической	готической	ADJ;NOM;SG;LGSPEC1
обушка	обушка	N;NOM;SG;LGSPEC1
член	членов	N;AT+ALL;SG;LGSPEC1
варштавкс	варштавкс	N;NOM;SG
арсемс	арсестькак	V;PL;LGSPEC_AMP;3;PST
паниця	паницят	ADJ;NOM;PL
кор	корсо	N;IN+ESS;SG
озамс	озавкшнынь	V;AC3P;SG;1;PST;PASS
бухгалтер	бухгалтерэнек	N;HUM;NOM;SG;PSS1P;LGSPEC1
покш	покшоноккак	ADJ;NOM;SG;LGSPEC_AMP;PSS1P
токамс	токасть	V;PL;3;PST
райгазета	райгазетатне	N;NOM;DEF;PL;LGSPEC1
отделения	отделениясонть	N;IN+ESS;DEF;SG;LGSPEC1
сур	сурксом	N;TRANS;SG;PSS1S
шашки	шашки	N;NOM;SG;LGSPEC1
кашамс	кашить	V;PL;3
топавтомс	топавтовить	V;AC3P;SG;2;PST;PASS
меелькст	меелькст	N;NOM;SG
тайга	тайгасо	N;IN+ESS;SG;LGSPEC1
кедьсёрмадовкс	кедьсёрмадовкссонть	N;IN+ESS;DEF;SG
парламентарий	парламентариентень	N;HUM;DAT;DEF;SG;LGSPEC1
тешкстнемс	тешкстнилинек	V;PL;1;RMT
каладомс	калавттадызь	V;AC2S;PL;1;CAUS
поладомс	поладсынзе	V;AC3P;SG;3
ушоёнксонь	ушоёнксонть	ADJ;NOM;PL
стомавт	стомавт	ADJ
лампа	лампат	N;NOM;SG;PSS2S;LGSPEC1
жальне	жальне	N;NOM;SG;LGSPEC1
кильдемс	кильдиндерятан	V;AC2S;COND;SG;1
арамс	ара	V;NEG
каванямс	каваняводо	V;IMP;PL;2;PASS
актив	актив	N;NOM;SG;LGSPEC1
тусто	тусто	ADJ;NOM;SG
цыганава	цыганават	N;HUM;NOM;SG;PSS2S;LGSPEC1
неемс	неевлинк	V;AC3;SBJV;PL;2
веле	велесэнзэяк	N;IN+ESS;PL;LGSPEC_AMP;PSS3S
библиотека	библиотеказонк	N;IN+ALL;SG;PSS2P;LGSPEC1
поп	попоньтькак	N;HUM;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
маштомс	маштоват	V;SG;2;PASS
киштемс	киштевтсь	V;SG;3;PST;CAUS
саемс	саиль	V;SG;3;RMT
кирнемс	кирневезь	V.PTCP;NOM;SG;PST;PASS
хронологической	хронологической	ADJ;NOM;SG;LGSPEC1
якут	якут	N;HUM;NOM;SG;LGSPEC1
кол	колан	ADJ;SG;1
унжа	унжатнеде	N;HUM;ABL;DEF;PL
кепсемс	кепсемс	V;NFIN
конституционной	конституционной	ADJ;NOM;SG;LGSPEC1
шнамс	шныть	V;PL;3
понгомс	понгинь	V;SG;1;PST
постройка	постройкатне	N;NOM;DEF;PL;LGSPEC1
пильгалкс	пильгалксозо	N;IN+ALL;SG
тевлем	тевлем	N;NOM;SG
эскелькс	эскелькстнэсэ	N;IN+ESS;DEF;PL
венчамс	венчинь	V;SG;1;PST;LGSPEC1
явномс	явнылизь	V;AC3;PL;3;RMT
няшной	няшной	ADJ;SG;LGSPEC1
тамаша	тамашантькак	N;GEN;DEF;SG;LGSPEC_AMP
пеель	пеельтне	N;NOM;DEF;PL
ракамс	ракамс	V;NFIN
баскетбол	баскетболонтень	N;IN+ALL;DEF;SG;LGSPEC1
лездамс	лездынь	V;AC3P;SG;1;PST
эрямопинге	эрямопингедест	N;ABL;SG;PSS3P
ой	ойтнень	N;GEN;DEF;PL
дивамс	дивавттадо	V;PL;2;CAUS;LGSPEC1
коробка	коробканзо	N;NOM;PL;PSS3S;LGSPEC1
навозонь	навозонть	ADJ;NOM;PL;LGSPEC1
дига	дигась	N;HUM;NOM;DEF;SG
плестяямс	плестяи	V;SG;3;LGSPEC1
валрисьме	валрисьмензэ	N;NOM;PL;PSS3S
кутмордамс	кутмордыя	V;AC3S;SG;1;PST
собеседования	собеседованиянть	N;GEN;DEF;SG;LGSPEC1
гепард	гепард	N;HUM;NOM;SG;LGSPEC1
перець	перецьсэ	N;IN+ESS;SG;LGSPEC1
труба	трубасо	N;IN+ESS;SG;LGSPEC1
апрель	апрелесь	N;NOM;DEF;SG;LGSPEC1
виздемс	виздевлинек	V;AC3;SBJV;PL;1
шумбра	шумбра	ADJ;NOM;SG
ал	алтнэньгак	N;GEN;DEF;PL;LGSPEC_AMP
лём	лёмтнень	N;GEN;DEF;PL
трус	трус	N;NOM;SG;LGSPEC1
топавтомс	топавтовозо	V;OPT;SG;3;PASS
чиемс	чиеват	V;SG;2;PASS
понкст	понксосткак	N;NOM;SG;LGSPEC_AMP;PSS3P
кучнемс	кучнинек	V;AC3;PL;1;PST
чинев	чиневть	ADJ;NOM;PL
эрьгедемс	эрьгедсь	V;SG;3;PST
нурьгамомс	нурьгамо	V;NEG
кемевикс	кемевикс	ADJ
варштамс	варштазевинь	V;SG;1;PST
наждак	наждаксо	N;IN+ESS;SG;LGSPEC1
болота	болотась	N;NOM;DEF;SG;LGSPEC1
пельнемс	пельнеть	V;AC3P;IMP;SG;2
сляника	сляникат	N;NOM;PL;LGSPEC1
чиемс	чиимизь	V;AC1S;PL;3;PST
полавтомс	полавтовсь	V;SG;3;PST;PASS
орма	ормасткак	N;NOM;SG;LGSPEC_AMP;PSS3P
нартнемс	нардтнизь	V;AC3;PL;3;PST
ветямс	ветинек	V;AC3;PL;1;PST
муськемс	муськить	V;PL;3
кумажа	кумажаст	N;NOM;SG;PSS3P
витемс	витезель	V.PTCP;SG;3;PST
сад	садтнэнь	N;GEN;DEF;PL;LGSPEC1
лагерь	лагерденть	N;ABL;DEF;SG;LGSPEC1
талаень	талаень	ADJ;NOM;SG
печкемс	печкевсть	V;PL;3;PST;PASS
демагогия	демагогиясь	N;NOM;DEF;SG;LGSPEC1
операция	операциятнень	N;GEN;DEF;PL;LGSPEC1
пристань	пристаньгак	N;NOM;SG;LGSPEC_AMP;LGSPEC1
сюпавчи	сюпавчитнень	N;GEN;DEF;PL
кренч	кренчень	N;HUM;GEN
аэрявикс	аэрявикс	ADJ
салдырькс	салдырьксэс	N;IN+ALL;SG
налксемс	налксевинь	V;SG;1;PST;PASS
кильдтнемс	кильдтнизь	V;AC3;PL;3;PST
символической	символической	ADJ;SG;LGSPEC1
межа	межасо	N;IN+ESS;SG;LGSPEC1
чарькодемс	чарькодилинь	V;SG;1;RMT
эрикс	эрикстнэнь	ADJ;GEN;DEF;PL
ремшамс	ремшазь	V.PTCP;NOM;SG;PST
мель	мельсэнек	N;IN+ESS;SG;PSS1P
фамилия	фамилиянзо	N;NOM;PL;PSS3S;LGSPEC1
палсемс	палсинь	V;SG;1;PST
героиня	героинятне	N;HUM;NOM;DEF;PL;LGSPEC1
лездамс	лездакшныть	V;PL;3
ваномс	ванкшнотано	V;PL;1
кодамс	кодан	V;SG;1
хирург	хирург	N;HUM;NOM;SG;LGSPEC1
ютамс	ютавттадо	V;PL;2;CAUS
епархия	епархиятнесэ	N;IN+ESS;DEF;PL;LGSPEC1
глобальной	глобальной	ADJ;NOM;SG;LGSPEC1
яшма	яшмат	N;NOM;PL;LGSPEC1
форма	формантень	N;IN+ALL;DEF;SG;LGSPEC1
суверенной	суверенной	ADJ;NOM;SG;LGSPEC1
ютко	юткошкаст	N;COMPV;SG;PSS3P
эпоха	эпохатненень	N;DAT;DEF;PL;LGSPEC1
притча	притчась	N;NOM;DEF;SG;LGSPEC1
тюремс	тюрят	V;SG;2
менеджер	менеджер	N;HUM;NOM;SG;LGSPEC1
чавума	чавумат	N;NOM;SG;PSS2S
лагерь	лагертнева	N;PROL;DEF;PL;LGSPEC1
удем	удемензэ	N;NOM;PL;PSS3S
карсемапель	карсемапелест	N;NOM;SG;PSS3P
морфология	морфологиянтень	N;DAT;DEF;SG;LGSPEC1
вачодо	вачодот	ADJ;SG;PSS2S
олго	олгонзо	N;NOM;PL;PSS3S
границя	границянок	N;NOM;SG;PSS1P;LGSPEC1
чивалгомань	чивалгомань	ADJ
кошт	коштозояк	N;NOM;SG;LGSPEC_AMP;PSS3S
технопарк	технопарконь	N;GEN;LGSPEC1
ранг	рангонь	N;GEN;LGSPEC1
отрасля	отраслятненень	N;DAT;DEF;PL;LGSPEC1
единоросс	единоросстнэнь	N;HUM;GEN;DEF;PL;LGSPEC1
вачкотемс	вачкотьсазо	V;AC3S;SG;3
тейнемс	тейнилинь	V;AC3P;SG;1;RMT
симемс	симекшнесь	V;SG;3;PST
путомс	путылизь	V;AC3;PL;3;RMT
академия	академиянтень	N;IN+ALL;DEF;SG;LGSPEC1
левштапо	левштапонть	N;GEN;DEF;SG
кавонзамс	кавонзазь	V.PTCP;NOM;SG;PST
пильге	пильгстэнзэ	N;IN+ABL;PL;PSS3S
тапардамо	тапардамонь	ADJ;GEN
формула	формуласо	N;IN+ESS;SG;LGSPEC1
мукоро	мукоронзо	N;NOM;PL;PSS3S
сторож	сторожось	N;HUM;NOM;DEF;SG;LGSPEC1
судямс	судямс	V;NFIN;LGSPEC1
совет	советтнэсэ	N;IN+ESS;DEF;PL;LGSPEC1
куро	куросонк	N;IN+ESS;SG;PSS2P
алфавит	алфавитсэ	N;IN+ESS;SG;LGSPEC1
валдочи	валдочи	N;NOM;SG
отход	отходов	N;AT+ALL;SG;LGSPEC1
машина	машинасто	N;IN+ABL;SG;LGSPEC1
кармамс	кармавтоволь	V;SBJV;SG;3;CAUS
варчамс	варчасынек	V;AC3;PL;1
поисковой	поисковой	ADJ;SG;LGSPEC1
школа	школавгак	N;AT+ALL;SG;LGSPEC_AMP;LGSPEC1
медь	медесь	N;NOM;DEF;SG
авидечи	авидечинь	N;NOM;SG;PSS1S
авань	авантень	ADJ;DAT
неемс	некшныльть	V;PL;3;RMT
муемс	муевиде	V;PL;2;PST;PASS
транспорт	транспортонтень	N;IN+ALL;DEF;SG;LGSPEC1
волна	волнась	N;NOM;DEF;SG;LGSPEC1
субвенция	субвенцият	N;NOM;SG;PSS2S;LGSPEC1
ила	иласто	N;IN+ABL;SG
фельдшер	фельдшерэнтькак	N;HUM;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
асодавикс	асодавиксэкс	ADJ;TRANS;SG
вайгель	вайгелеськак	N;NOM;DEF;SG;LGSPEC_AMP
пувтамс	пувтымизь	V;AC1P;PST
вашо	вашонзо	N;HUM;NOM;PL;PSS3S
совамс	совавтымим	V;AC1S;SG;3;PST;CAUS
утердемс	утерьдемс	V;NFIN
лисемс	лисевинь	V;AC3P;SG;1;PST;PASS
заведения	заведениятненень	N;IN+ALL;DEF;PL;LGSPEC1
суркст	суркст	N;NOM;SG
прогресс	прогрессэкс	N;TRANS;SG;LGSPEC1
томбалькс	томбалькс	N;NOM;SG
менель	менельтнень	N;GEN;DEF;PL
доход	доходт	N;NOM;PL;LGSPEC1
курсант	курсантось	N;HUM;NOM;DEF;SG;LGSPEC1
приказной	приказной	ADJ;LGSPEC1
оршавт	оршавтост	N;NOM;SG;PSS3P
мандо	мандосонть	N;IN+ESS;DEF;SG
ютамс	ютавтсынь	V;AC3P;SG;1;CAUS
океан	океантнэнь	N;GEN;DEF;PL;LGSPEC1
тенденция	тенденцият	N;NOM;SG;PSS2S;LGSPEC1
ядерной	ядерной	ADJ;SG;LGSPEC1
сезнемс	сезнесыть	V;AC3P;SG;2
дательной	дательной	ADJ;SG;LGSPEC1
молевкс	молевкс	N;NOM;SG
лавшочи	лавшочисэяк	N;IN+ESS;SG;LGSPEC_AMP
лазомс	лазызе	V;AC3S;SG;3;PST
ёвтнемс	ёвтневлинь	V;SBJV;SG;1
онгомс	онго	V;NEG
вастамс	вастыльть	V;PL;3;RMT
подход	подход	N;NOM;SG;LGSPEC1
аволямс	аволяк	V;IMP;SG;2
толпандя	толпандясост	N;IN+ESS;SG;PSS3P
конверт	конвертэнтень	N;IN+ALL;DEF;SG;LGSPEC1
ваномс	ванкшнат	V;SG;2
куло	кулостькак	N;GEN;DEF;SG;LGSPEC_AMP
санитар	санитартнэнь	N;HUM;GEN;DEF;PL;LGSPEC1
виськстэме	виськстэмесь	ADJ;NOM;DEF;SG
ёрамс	ёравт	V;AC3P;IMP;SG;2;PASS
наркоман	наркоманось	N;HUM;NOM;DEF;SG;LGSPEC1
варения	варениядо	N;ABL;SG;LGSPEC1
кепсемс	кепси	V;SG;3
историк	историктнень	N;HUM;GEN;DEF;PL;LGSPEC1
толбандя	толбандятне	N;NOM;DEF;PL
ведьчика	ведьчика	N;HUM;NOM;SG
дуцямс	дуци	V;SG;3
частота	частота	N;NOM;SG;LGSPEC1
декан	деканоль	N;HUM;SG;3;PST;LGSPEC1
талномс	талномс	V;NFIN
парсей	парсейганть	N;PROL;DEF;SG
варштавкс	варштавксткак	N;NOM;PL;LGSPEC_AMP
пицемс	пицизь	V;AC3;PL;3;PST
тол	толонь	N;GEN
шумбра	шумбратненень	ADJ;IN+ALL;DEF;PL
целковой	целковоень	N;GEN;LGSPEC1
