lunsj	lunsjen	N;DEF;SG
søke	søkt	V.PTCP;PST
data	data	N;NDEF;PL
grasiøs	grasiøse	ADJ;DEF;SG+PL
reparere	reparerer	V;PRS
eik	eikene	N;DEF;PL
dørnøkkel	dørnøkkelen	N;DEF;SG
stivelse	stivelsen	N;DEF;SG
flyselskap	flyselskapene	N;DEF;PL
helle	heller	V;PRS
kjøkkenredskap	kjøkkenredskapen	N;DEF;SG
stele	stelene	N;DEF;PL
soveværelse	soveværelsene	N;DEF;PL
vevtjener	vevtjenere	N;NDEF;PL
glemme	glemte	V;PST
håndhilse	håndhilste	V;PST
flagg	flagget	N;DEF;SG
legemiddel	legemidla	N;DEF;PL
økonomi	økonomiene	N;DEF;PL
irlender	irlenderen	N;DEF;SG
kreasjon	kreasjonen	N;DEF;SG
fyrtårn	fyrtårnet	N;DEF;SG
repertoar	repertoar	N;NDEF;PL
satellitt	satellitter	N;NDEF;PL
centimeter	centimeter	N;NDEF;PL
muslim	muslimen	N;DEF;SG
forsvinne	forsvinner	V;PRS
vatn	vatnet	N;DEF;SG
kino	kinoer	N;NDEF;PL
farge	fargende	V.PTCP;PRS
formell	formelt	ADJ;NEUT;SG
maksimum	maksimumet	N;DEF;SG
mål	mål	N;NDEF;PL
drømme	drøm	V;IMP
solist	solister	N;NDEF;PL
luftfartøy	luftfartøyer	N;NDEF;PL
millionær	millionærer	N;NDEF;PL
henge	henger	V;PRS
navle	navlene	N;DEF;PL
låne	lånende	V.PTCP;PRS
fordeling	fordelingene	N;DEF;PL
aldring	aldringer	N;NDEF;PL
rektangel	rektangler	N;NDEF;PL
lufthavn	lufthavnen	N;DEF;SG
banke	bankende	V;PRS
komme	kommer	V;PRS
sage	saget	V.PTCP;PST
strekning	strekningen	N;DEF;SG
tilnærming	tilnærminga	N;DEF;SG
sporvogn	sporvogner	N;NDEF;PL
desertere	deserterer	V;PRS
katte	katter	N;NDEF;PL
fiske	fisket	V;PST
pigment	pigmenter	N;NDEF;PL
kopp	koppene	N;DEF;PL
søvn	søvne	N;DAT
morter	morteren	N;DEF;SG
potensiell	potensielle	ADJ;DEF;SG+PL
posthum	posthumt	ADJ;NEUT;SG
vare	varen	N;DEF;SG
regjere	regjert	V.PTCP;PST
skrog	skrog	N;NDEF;PL
rapportere	rapportert	V.PTCP;PST
masseprodusere	masseproduserer	V;PRS
morter	mortere	N;NDEF;PL
tall	tallet	N;DEF;SG
kvalross	kvalrossen	N;DEF;SG
hopp	hoppet	N;DEF;SG
tykkelse	tykkelsene	N;DEF;PL
rykte	rykter	N;NDEF;PL
virkelig	virkelige	ADJ;DEF;SG+PL
masse	massene	N;DEF;PL
leveranse	leveransene	N;DEF;PL
standardisere	standardiser	V;IMP
brisling	brislingen	N;DEF;SG
mamma	mammaene	N;DEF;PL
rommelig	rommelig	ADJ;NEUT;SG
bro	broa	N;DEF;SG
skrivemaskin	skrivemaskinen	N;DEF;SG
utdanne	utdannet	V;PST
krigføring	krigføringene	N;DEF;PL
tempo	tempi	N;NDEF;PL
brøling	brølingen	N;DEF;SG
tortur	torturene	N;DEF;PL
uke	uker	N;NDEF;PL
kloster	klosteret	N;DEF;SG
etymolog	etymologene	N;DEF;PL
oversette	oversett	V;IMP
teaterstykke	teaterstykkene	N;DEF;PL
aspekt	aspekt	N;NDEF;PL
ungarsk	ungarsken	N;DEF;SG
sverd	sverda	N;DEF;PL
snøplog	snøploger	N;NDEF;PL
bygdelag	bygdelaga	N;DEF;PL
helle	hellene	N;DEF;PL
tygge	tyggende	V.PTCP;PRS
svarttrost	svarttrosten	N;DEF;SG
busserull	busserullene	N;DEF;PL
lekter	lektere	N;NDEF;PL
akseptere	akseptert	V.PTCP;PST
ønske	ønsker	V;PRS
buss	bussen	N;DEF;SG
åkle	åkleet	N;DEF;SG
apparat	apparater	N;NDEF;PL
forkjølelse	forkjølelsene	N;DEF;PL
grønn	grønne	ADJ;DEF;SG+PL
påhengsmotor	påhengsmotorer	N;NDEF;PL
snill	snilt	ADJ;NEUT;SG
arkitektur	arkitekturene	N;DEF;PL
sikkerhet	sikkerheter	N;NDEF;PL
iskrem	iskremene	N;DEF;PL
galoppere	galopper	V;IMP
brems	bremsen	N;DEF;SG
anemometer	anemometer	N;NDEF;PL
lesepult	lesepultene	N;DEF;PL
redskap	redskap	N;NDEF;PL
dokument	dokumentene	N;DEF;PL
kyrillisk	kyrilliske	ADJ;DEF;SG+PL
håndveske	håndvesken	N;DEF;SG
privatlærer	privatlærerne	N;DEF;PL
produsere	produsert	V.PTCP;PST
øye	øyne	N;NDEF;PL
komorer	komorere	N;NDEF;PL
oppfinne	oppfinner	V;PRS
støyttann	støyttannen	N;DEF;SG
veidekke	veidekket	N;DEF;SG
soverom	soveromma	N;DEF;PL
topografi	topografier	N;NDEF;PL
andrespråk	andrespråka	N;DEF;PL
kineser	kineserne	N;DEF;PL
venezuelaner	venezuelanerne	N;DEF;PL
klatre	klatra	V;PST
styre	styrt	V.PTCP;PST
putevar	putevara	N;DEF;PL
arbeidsuke	arbeidsuken	N;DEF;SG
skorpion	skorpionen	N;DEF;SG
maksimum	maksima	N;NDEF;PL
pære	pærer	N;NDEF;PL
løs	løseste	ADJ;SPRL;DEF
lukke	lukka	V;PST
kaffer	kafferen	N;DEF;SG
hestesko	hesteskoene	N;DEF;PL
forlag	forlaga	N;DEF;PL
lærebok	læreboken	N;DEF;SG
panne	pannen	N;DEF;SG
beskatte	beskatt	V;IMP
tolkning	tolkningen	N;DEF;SG
trommis	trommiser	N;NDEF;PL
skyte	skjøt	V;PST
gymnas	gymnaset	N;DEF;SG
virksom	virksomme	ADJ;DEF;SG+PL
hytte	hytter	N;NDEF;PL
forvrenge	forvreng	V;IMP
meningsløs	meningsløse	ADJ;DEF;SG+PL
kjøkkenhåndkle	kjøkkenhåndklær	N;NDEF;PL
rekkefølge	rekkefølgen	N;DEF;SG
a	aen	N;DEF;SG
telefonsentral	telefonsentralen	N;DEF;SG
reptil	reptil	N;NDEF;PL
nicaraguaner	nicaraguaneren	N;DEF;SG
lokomotiv	lokomotiver	N;NDEF;PL
republikansk	republikansk	ADJ;NEUT;SG
demokrat	demokrater	N;NDEF;PL
lufttett	lufttett	ADJ;NEUT;SG
kapitel	kapitela	N;DEF;PL
jackpot	jackpoten	N;DEF;SG
skjære	skåret	V.PTCP;PST
komponist	komponisten	N;DEF;SG
dråpe	dråpene	N;DEF;PL
comeback	comebacket	N;DEF;SG
hjerne	hjernene	N;DEF;PL
kritt	kritt	N;NDEF;PL
teskei	teskeier	N;NDEF;PL
vinterlig	vinterlige	ADJ;DEF;SG+PL
grave	gravende	V.PTCP;PRS
tusendel	tusendelene	N;DEF;PL
BH	BH-en	N;DEF;SG
element	element	N;NDEF;PL
ben	benene	N;DEF;PL
inntektsskatt	inntektsskatter	N;NDEF;PL
tegning	tegningen	N;DEF;SG
hore	horen	N;DEF;SG
himmelseng	himmelsengen	N;DEF;SG
vokalist	vokalister	N;NDEF;PL
svakhet	svakheter	N;NDEF;PL
lyspære	lyspæra	N;DEF;SG
kjempe	kjempen	N;DEF;SG
skjære	skjærene	N;DEF;PL
prise	priser	V;PRS
sprengstoff	sprengstoffet	N;DEF;SG
arkaisere	arkaiser	V;IMP
gnu	gnuene	N;DEF;PL
suge	suger	V;PRS
helikopter	helikopter	N;NDEF;PL
væske	væsker	N;NDEF;PL
foto	fotoene	N;DEF;PL
endelse	endelsene	N;DEF;PL
gudinne	gudinnene	N;DEF;PL
hete	het	V;PST
kokebok	kokeboka	N;DEF;SG
fryse	frøys	V;PST
jamaikaner	jamaikanere	N;NDEF;PL
blyant	blyantene	N;DEF;PL
utnevnelse	utnevnelsen	N;DEF;SG
begrenset	begrensete	ADJ;DEF;SG+PL
magedanser	magedansere	N;NDEF;PL
be	bedende	V.PTCP;PRS
domene	domener	N;NDEF;PL
troll	troll	N;NDEF;PL
afghaner	afghaneren	N;DEF;SG
oversette	oversatte	V;PST
frukt	frukta	N;DEF;SG
flyte	fløyt	V;PST
sprengstoff	sprengstoff	N;NDEF;PL
fe	feen	N;DEF;SG
abkhaser	abkhasere	N;NDEF;PL
bøk	bøken	N;DEF;SG
smie	smien	N;DEF;SG
hylle	hylla	V;PST
kvadratisk	kvadratiske	ADJ;DEF;SG+PL
tømmerstokk	tømmerstokken	N;DEF;SG
baby	babyer	N;NDEF;PL
lommetyv	lommetyven	N;DEF;SG
tung	tyngste	ADJ;SPRL;DEF
jamaicaner	jamaicaneren	N;DEF;SG
manøver	manøvrer	N;NDEF;PL
tykkelse	tykkelser	N;NDEF;PL
bore	bor	V;IMP
møte	møter	V;PRS
internatskole	internatskoler	N;NDEF;PL
støtte	støttene	N;DEF;PL
skjulested	skjulesteder	N;NDEF;PL
fyrverkeri	fyrverkeriet	N;DEF;SG
drap	drapa	N;DEF;PL
pike	piken	N;DEF;SG
sagbruk	sagbrukene	N;DEF;PL
forvarsel	forvarsler	N;NDEF;PL
djiboutier	djiboutierne	N;DEF;PL
lommetyv	lommetyvene	N;DEF;PL
diktatur	diktatura	N;DEF;PL
interesse	interessen	N;DEF;SG
tute	tutet	V;PST
bøffel	bøflene	N;DEF;PL
sivil	sivile	ADJ;DEF;SG+PL
ugift	ugifte	ADJ;DEF;SG+PL
klima	klima	N;NDEF;PL
skål	skålen	N;DEF;SG
uvanlig	uvanlig	ADJ;NEUT;SG
kvalifisere	kvalifisert	V.PTCP;PST
mannskap	mannskaper	N;NDEF;PL
skje	skje	V;IMP
arm	armt	ADJ;NEUT;SG
fortelle	forteller	V;PRS
klesvask	klesvasker	N;NDEF;PL
fly	fløy	V;PST
natt	natta	N;DEF;SG
vare	varer	N;NDEF;PL
pandemi	pandemier	N;NDEF;PL
begynne	begynn	V;IMP
får	får	N;NDEF;PL
øve	øvet	V;PST
treenighet	treenigheta	N;DEF;SG
system	systemet	N;DEF;SG
mors	morsene	N;DEF;PL
klon	kloner	N;NDEF;PL
debutere	debutert	V.PTCP;PST
helhet	helheta	N;DEF;SG
aseksuell	aseksuelle	ADJ;DEF;SG+PL
munning	munningen	N;DEF;SG
øye	øyene	N;DEF;PL
kapitel	kapiteler	N;NDEF;PL
eksistere	eksisterende	V.PTCP;PRS
chilener	chilenere	N;NDEF;PL
samle	samler	V;PRS
programmeringsspråk	programmeringsspråkene	N;DEF;PL
klo	klørne	N;DEF;PL
tyv	tyven	N;DEF;SG
svane	svanen	N;DEF;SG
samarbeid	samarbeidet	N;DEF;SG
rike	riker	N;NDEF;PL
hylle	hylla	V.PTCP;PST
landkrabbe	landkrabben	N;DEF;SG
forbrenningsmotor	forbrenningsmotorene	N;DEF;PL
hytte	hyttene	N;DEF;PL
alge	algene	N;DEF;PL
savanne	savannen	N;DEF;SG
formue	formuer	N;NDEF;PL
brasilianer	brasilianere	N;NDEF;PL
krystall	krystallet	N;DEF;SG
gudelig	gudelige	ADJ;DEF;SG+PL
rund	runde	ADJ;DEF;SG+PL
reklame	reklamen	N;DEF;SG
fortsette	fortsett	V;IMP
tyngdekraft	tyngdekreftene	N;DEF;PL
mulig	mulige	ADJ;DEF;SG+PL
rulett	rulettene	N;DEF;PL
flyte	fløt	V;PST
butikk	butikker	N;NDEF;PL
sy	sydde	V;PST
skade	skada	V;PST
irlender	irlenderne	N;DEF;PL
begrense	begrensa	V;PST
vie	vigde	V;PST
mykne	mykna	V;PST
eksponere	eksponer	V;IMP
frykt	frykten	N;DEF;SG
myke	myka	V.PTCP;PST
utstillingsvindu	utstillingsvindu	N;NDEF;PL
fontene	fontenene	N;DEF;PL
badeby	badebyen	N;DEF;SG
kilde	kilden	N;DEF;SG
vipp	vipper	N;NDEF;PL
grensesnitt	grensesnitt	N;NDEF;PL
skjermskudd	skjermskuddene	N;DEF;PL
slips	slipsa	N;DEF;PL
regulering	reguleringer	N;NDEF;PL
sierraleoner	sierraleonere	N;NDEF;PL
påfugl	påfuglen	N;DEF;SG
gaffel	gaffelen	N;DEF;SG
zoomlinse	zoomlinsen	N;DEF;SG
toåring	toåringen	N;DEF;SG
alder	aldrene	N;DEF;PL
rosin	rosinen	N;DEF;SG
struktur	strukturen	N;DEF;SG
tak	tak	N;NDEF;PL
cupfinale	cupfinaler	N;NDEF;PL
forlag	forlagene	N;DEF;PL
østerriker	østerrikere	N;NDEF;PL
tru	trua	N;DEF;SG
snøbyge	snøbygen	N;DEF;SG
vitenskap	vitenskapene	N;DEF;PL
be	ba	V;PST
baug	baugen	N;DEF;SG
terrorist	terroristene	N;DEF;PL
ugress	ugressa	N;DEF;PL
ordbok	ordbøker	N;NDEF;PL
bygning	bygningene	N;DEF;PL
kult	kulter	N;NDEF;PL
år	året	N;DEF;SG
ordbok	ordbøkene	N;DEF;PL
sangfugl	sangfuglene	N;DEF;PL
desimal	desimaler	N;NDEF;PL
vitamin	vitamin	N;NDEF;PL
standard	standarden	N;DEF;SG
forenkle	forenkle	V;IMP
tale	taler	N;NDEF;PL
stoff	stoffet	N;DEF;SG
ending	endingen	N;DEF;SG
behov	behov	N;NDEF;PL
forsvinne	forsvinnende	V.PTCP;PRS
forventning	forventninga	N;DEF;SG
hul	hult	ADJ;NEUT;SG
forvrenge	forvrengte	V;PST
råolje	råoljer	N;NDEF;PL
besøk	besøk	N;NDEF;PL
fornavn	fornavna	N;DEF;PL
kosedyr	kosedyret	N;DEF;SG
forsvare	forsvarer	V;PRS
identitet	identiteter	N;NDEF;PL
århundre	århundret	N;DEF;SG
utbredt	utbredt	ADJ;NEUT;SG
gudshus	gudshuset	N;DEF;SG
ren	reneste	ADJ;SPRL;DEF
undulat	undulatene	N;DEF;PL
modifikasjon	modifikasjoner	N;NDEF;PL
desimal	desimalene	N;DEF;PL
brøk	brøken	N;DEF;SG
resymé	resymea	N;DEF;PL
natt	natten	N;DEF;SG
forsvar	forsvar	N;NDEF;PL
jungel	jungler	N;NDEF;PL
prosent	prosenten	N;DEF;SG
emirat	emirata	N;DEF;PL
vert	verten	N;DEF;SG
synd	synda	N;DEF;SG
lyst	lysten	N;DEF;SG
påskeegg	påskeegget	N;DEF;SG
fellesnevner	fellesnevneren	N;DEF;SG
safari	safarier	N;NDEF;PL
dråpe	dråpen	N;DEF;SG
undervannsbåt	undervannsbåten	N;DEF;SG
stim	stimene	N;DEF;PL
sveise	sveisa	V.PTCP;PST
bremse	bremsa	V;PST
skade	skader	V;PRS
uregistrert	uregistrerte	ADJ;DEF;SG+PL
skatt	skatten	N;DEF;SG
metall	metalla	N;DEF;PL
folkevogn	folkevogna	N;DEF;SG
bokholder	bokholdere	N;NDEF;PL
husholdning	husholdningen	N;DEF;SG
stim	stimen	N;DEF;SG
diameter	diameterne	N;DEF;PL
seismologisk	seismologisk	ADJ;NEUT;SG
understreke	understreket	V;PST
kattedyr	kattedyret	N;DEF;SG
profesjonell	profesjonelt	ADJ;NEUT;SG
bambusrør	bambusrøret	N;DEF;SG
turner	turnerne	N;DEF;PL
papir	papira	N;DEF;PL
mirakel	mirakel	N;NDEF;PL
fregatt	fregattene	N;DEF;PL
usbeker	usbekerne	N;DEF;PL
dame	damen	N;DEF;SG
retning	retninga	N;DEF;SG
bøye	bøya	N;DEF;SG
bestyrer	bestyreren	N;DEF;SG
fryser	fryserne	N;DEF;PL
miniskjørt	miniskjørtene	N;DEF;PL
øyelokk	øyelokket	N;DEF;SG
fartsgrense	fartsgrensene	N;DEF;PL
togoleser	togoleseren	N;DEF;SG
forklare	forklar	V;IMP
konsultere	konsulterende	V.PTCP;PRS
skape	skapte	V;PST
kne	knær	N;NDEF;PL
forskjellig	forskjellige	ADJ;DEF;SG+PL
spiker	spikeren	N;DEF;SG
sykkelsti	sykkelstier	N;NDEF;PL
jerv	jerver	N;NDEF;PL
sporvogn	sporvognen	N;DEF;SG
sen	senere	ADJ;CMPR
krigsskip	krigsskipene	N;DEF;PL
arbeide	arbeidende	V.PTCP;PRS
lastebilsjåfør	lastebilsjåfører	N;NDEF;PL
gymnas	gymnasa	N;DEF;PL
tilnærming	tilnærmingene	N;DEF;PL
avholde	avholder	V;PRS
veranda	verandaene	N;DEF;PL
lei	leia	N;DEF;SG
kult	kulten	N;DEF;SG
nysgjerrig	nysgjerrig	ADJ;NEUT;SG
tømmerstokk	tømmerstokkene	N;DEF;PL
kraftig	kraftige	ADJ;DEF;SG+PL
anonym	anonymt	ADJ;NEUT;SG
ting	ting	N;NDEF;PL
leddgikt	leddgikta	N;DEF;SG
gyldig	gyldig	ADJ;NEUT;SG
sandal	sandalen	N;DEF;SG
mikrobiolog	mikrobiologen	N;DEF;SG
synke	synkende	V.PTCP;PRS
pandemi	pandemiene	N;DEF;PL
uskadelig	uskadelige	ADJ;DEF;SG+PL
bedring	bedringa	N;DEF;SG
kapittel	kapitlet	N;DEF;SG
majoritet	majoriteten	N;DEF;SG
portugiser	portugisere	N;NDEF;PL
sikkerhet	sikkerheta	N;DEF;SG
uklar	uklare	ADJ;DEF;SG+PL
nese	nesa	N;DEF;SG
spesifikasjon	spesifikasjoner	N;NDEF;PL
utfordre	utfordret	V;PST
hvite	hviten	N;DEF;SG
fyr	fyrer	N;NDEF;PL
multiplum	multiplaene	N;DEF;PL
åring	åringene	N;DEF;PL
endestasjon	endestasjonen	N;DEF;SG
forenkle	forenkla	V;PST
sofa	sofaene	N;DEF;PL
influensa	influensaer	N;NDEF;PL
ettermiddag	ettermiddagene	N;DEF;PL
fortelle	fortalte	V;PST
flaske	flaska	N;DEF;SG
apparat	apparat	N;NDEF;PL
kongelig	kongelig	ADJ;NEUT;SG
strøm	strømmene	N;DEF;PL
sykle	sykler	V;PRS
fornye	fornyet	V;PST
bøye	bøyet	V;PST
handelsskip	handelsskip	N;NDEF;PL
krampe	krampene	N;DEF;PL
fotnote	fotnoter	N;NDEF;PL
slovakisk	slovakisk	ADJ;NEUT;SG
identifisere	identifisert	V.PTCP;PST
vikingtid	vikingtida	N;DEF;SG
molekyl	molekyla	N;DEF;PL
statsborger	statsborgeren	N;DEF;SG
programmere	programmerte	V;PST
karikaturtegner	karikaturtegneren	N;DEF;SG
karbohydrat	karbohydrat	N;NDEF;PL
spedbarn	spedbarnene	N;DEF;PL
øks	øksene	N;DEF;PL
krokus	krokuser	N;NDEF;PL
sukkerfri	sukkerfritt	ADJ;NEUT;SG
skade	skad	V;IMP
heissjakt	heissjakten	N;DEF;SG
flerfarget	flerfarget	ADJ;NEUT;SG
sangfugl	sangfugler	N;NDEF;PL
økotype	økotypene	N;DEF;PL
måke	måket	V;PST
veskenapper	veskenappere	N;NDEF;PL
mase	maset	V;PST
akseptere	aksepterte	V;PST
brille	brilla	N;DEF;SG
høyskole	høyskolen	N;DEF;SG
julepresang	julepresangene	N;DEF;PL
hertug	hertugene	N;DEF;PL
skyte	skyter	V;PRS
seilskip	seilskipa	N;DEF;PL
papuaner	papuanerne	N;DEF;PL
kjøkken	kjøkkena	N;DEF;PL
apostrof	apostrofen	N;DEF;SG
støt	støtet	N;DEF;SG
påskeegg	påskeeggene	N;DEF;PL
mase	maste	V;PST
banke	banker	N;NDEF;PL
nedgang	nedganger	N;NDEF;PL
varelager	varelager	N;NDEF;PL
spiss	spissen	N;DEF;SG
motvekt	motvekter	N;NDEF;PL
få	få	V;IMP
festival	festivalen	N;DEF;SG
mamma	mammaen	N;DEF;SG
fantom	fantoma	N;DEF;PL
kokebok	kokebøkene	N;DEF;PL
soverom	soverommet	N;DEF;SG
etablere	etablerer	V;PRS
skotsk	skotske	ADJ;DEF;SG+PL
tommel	tomlene	N;DEF;PL
hvithåret	hvithårete	ADJ;DEF;SG+PL
trøblet	trøblete	ADJ;DEF;SG+PL
elg	elgen	N;DEF;SG
parodi	parodier	N;NDEF;PL
tute	tut	V;IMP
colombianer	colombianerne	N;DEF;PL
sekk	sekken	N;DEF;SG
dvergbjerk	dvergbjerkene	N;DEF;PL
sigøyner	sigøynerne	N;DEF;PL
salomoner	salomoneren	N;DEF;SG
mentor	mentorene	N;DEF;PL
tsjekkisk	tsjekkisken	N;DEF;SG
campingvogn	campingvognene	N;DEF;PL
sy	sy	V;IMP
utgang	utgangene	N;DEF;PL
øye	øyet	N;DEF;SG
fantastisk	fantastisk	ADJ;NEUT;SG
middel	middel	N;NDEF;PL
blekemiddel	blekemidlene	N;DEF;PL
betale	betaler	V;PRS
stim	stimer	N;NDEF;PL
nyre	nyret	N;DEF;SG
blyant	blyanter	N;NDEF;PL
løvinne	løvinna	N;DEF;SG
turnpike	turnpikene	N;DEF;PL
tøff	tøffest	ADJ;SPRL;NDEF
fil	filer	N;NDEF;PL
abstrakt	abstraktene	N;DEF;PL
superleder	superledere	N;NDEF;PL
laste	last	V;IMP
ær	ærene	N;DEF;PL
skje	skjedde	V;PST
desertør	desertørene	N;DEF;PL
bane	banene	N;DEF;PL
spiselig	spiselig	ADJ;NEUT;SG
fisker	fiskerne	N;DEF;PL
grunnlag	grunnlag	N;NDEF;PL
anarki	anarkier	N;NDEF;PL
vanskeliggjøre	vanskeliggjorde	V;PST
passasjer	passasjerer	N;NDEF;PL
tegnspråk	tegnspråkene	N;DEF;PL
resymé	resyméer	N;NDEF;PL
multiplikasjon	multiplikasjonene	N;DEF;PL
rykte	rykta	N;DEF;PL
prislapp	prislapper	N;NDEF;PL
måke	måket	V.PTCP;PST
fare	farende	V.PTCP;PRS
renne	rent	V.PTCP;PST
fjær	fjæra	N;DEF;SG
forteller	fortellerne	N;DEF;PL
krokus	krokusen	N;DEF;SG
tam	tamt	ADJ;NEUT;SG
bevege	bevegde	V;PST
spørsmål	spørsmåla	N;DEF;PL
åpen	åpne	ADJ;DEF;SG+PL
motiv	motivene	N;DEF;PL
antiguaner	antiguanerne	N;DEF;PL
dress	dresser	N;NDEF;PL
kvalifisere	kvalifiserte	V;PST
orientere	orienterer	V;PRS
håndtere	håndterer	V;PRS
tast	tasten	N;DEF;SG
fly	flyr	V;PRS
jekk	jekkene	N;DEF;PL
utstillingsvindu	utstillingsvindua	N;DEF;PL
målløs	målløse	ADJ;DEF;PL
punktum	punktumet	N;DEF;SG
lås	låset	N;DEF;SG
forbindelse	forbindelsene	N;DEF;PL
robbe	robbet	V;PST
syltetøy	syltetøyer	N;NDEF;PL
treenighet	treenigheten	N;DEF;SG
forlove	forlov	V;IMP
oversetter	oversettere	N;NDEF;PL
kanadisk	kanadiske	ADJ;DEF;SG+PL
fremføre	fremført	V.PTCP;PST
forlag	forlag	N;NDEF;PL
forlengelse	forlengelser	N;NDEF;PL
ghanesisk	ghanesisk	ADJ;NEUT;SG
skoggrense	skoggrensa	N;DEF;SG
forretning	forretningen	N;DEF;SG
diameter	diametere	N;NDEF;PL
årstid	årstiden	N;DEF;SG
utdannelse	utdannelsene	N;DEF;PL
sluse	slusa	N;DEF;SG
fremføre	fremførte	V;PST
sentrifugalkraft	sentrifugalkraften	N;DEF;SG
nordmann	nordmannen	N;DEF;SG
isbryter	isbryteren	N;DEF;SG
substantiv	substantiv	N;NDEF;PL
kinesisk	kinesisken	N;DEF;SG
bukett	buketten	N;DEF;SG
vie	via	V.PTCP;PST
simulere	simulerende	V.PTCP;PRS
rygg	ryggene	N;DEF;PL
kreere	kreerende	V.PTCP;PRS
kreere	kreert	V.PTCP;PST
istapp	istapper	N;NDEF;PL
koselig	koselig	ADJ;NEUT;SG
fet	fetere	ADJ;CMPR
deltagelse	deltagelsen	N;DEF;SG
fornyelse	fornyelsene	N;DEF;PL
triumfere	triumferer	V;PRS
behov	behova	N;DEF;PL
bred	bredt	ADJ;NEUT;SG
ordgyteri	ordgyteria	N;DEF;PL
spiss	spisst	ADJ;NEUT;SG
jungel	jungelen	N;DEF;SG
mørkhåret	mørkhårete	ADJ;DEF;SG+PL
trene	trent	V.PTCP;PST
stor	større	ADJ;CMPR
sosiolog	sosiologer	N;NDEF;PL
fare	farene	N;DEF;PL
øyelokk	øyelokka	N;DEF;PL
gjenbruke	gjenbruk	V;IMP
offentlig	offentlige	ADJ;DEF;SG+PL
åk	åkene	N;DEF;PL
snøras	snørasa	N;DEF;SG
harddisk	harddisken	N;DEF;SG
nyre	nyra	N;DEF;PL
tørket	tørket	ADJ;NEUT;SG
dørklokke	dørklokka	N;DEF;SG
dame	damer	N;NDEF;PL
ønske	ønskt	V.PTCP;PST
kampanje	kampanjen	N;DEF;SG
harpe	harpene	N;DEF;PL
ornitolog	ornitologen	N;DEF;SG
tut	tuter	N;NDEF;PL
kjempe	kjemp	V;IMP
gevær	geværet	N;DEF;SG
foajé	foajéen	N;DEF;SG
utland	utlandet	N;DEF;SG
øyenbryn	øyenbryna	N;DEF;PL
kjennskap	kjennskaper	N;NDEF;PL
segregere	segregert	V.PTCP;PST
følge	følgende	V.PTCP;PRS
maje	majen	N;DEF;SG
resepsjonist	resepsjonister	N;NDEF;PL
fjellside	fjellsiden	N;DEF;SG
forbinde	forbinder	V;PRS
kvalifisere	kvalifiserer	V;PRS
bakke	bakkene	N;DEF;PL
apal	apaler	N;NDEF;PL
nordlig	nordligste	ADJ;SPRL;DEF
kondensasjon	kondensasjonen	N;DEF;SG
utgift	utgifta	N;DEF;SG
verdsette	verdsetter	V;PRS
premiere	premierer	N;NDEF;PL
standardisere	standardisert	V.PTCP;PST
kongoleser	kongoleseren	N;DEF;SG
emirat	emiratene	N;DEF;PL
skrunøkkel	skrunøklene	N;DEF;PL
detonere	detoner	V;IMP
langbue	langbuer	N;NDEF;PL
moldover	moldoverne	N;DEF;PL
hengekøye	hengekøya	N;DEF;SG
trofé	trofeene	N;DEF;PL
stige	stig	V;IMP
ren	rene	ADJ;DEF;SG+PL
bambus	bambusen	N;DEF;SG
kongle	konglen	N;DEF;SG
skinke	skinkene	N;DEF;PL
klatre	klatret	V;PST
ambulanse	ambulansen	N;DEF;SG
humpet	humpet	ADJ;NEUT;SG
knallsyre	knallsyren	N;DEF;SG
klo	kloen	N;DEF;SG
hette	hetten	N;DEF;SG
fettsyre	fettsyra	N;DEF;SG
lei	leier	N;NDEF;PL
starte	startet	V;PST
flyfoto	flyfotoet	N;DEF;SG
kateter	katetra	N;DEF;PL
nåløye	nåløyne	N;NDEF;PL
arvelig	arvelig	ADJ;NEUT;SG
bukse	buksen	N;DEF;SG
kontur	konturene	N;DEF;PL
penis	penisen	N;DEF;SG
kuwaiter	kuwaitere	N;NDEF;PL
arkaisere	arkaiserte	V;PST
regnboge	regnbogene	N;DEF;PL
kald	kaldeste	ADJ;SPRL;DEF
kjede	kjeda	N;DEF;PL
rop	ropa	N;DEF;PL
organisasjon	organisasjoner	N;NDEF;PL
gribb	gribben	N;DEF;SG
terapi	terapiene	N;DEF;PL
hemmelighetsfull	hemmelighetsfulle	ADJ;DEF;SG+PL
hestesko	hesteskoen	N;DEF;SG
modellfly	modellfly	N;NDEF;PL
ravn	ravnen	N;DEF;SG
visum	visumene	N;DEF;PL
levested	levestedet	N;DEF;SG
ministerium	ministerier	N;NDEF;PL
modell	modellene	N;DEF;PL
bibliotekar	bibliotekaren	N;DEF;SG
zambisk	zambisk	ADJ;NEUT;SG
destruksjon	destruksjoner	N;NDEF;PL
varelager	varelagre	N;NDEF;PL
administrasjon	administrasjoner	N;NDEF;PL
krokodille	krokodillen	N;DEF;SG
skiløper	skiløperen	N;DEF;SG
tisse	tiss	V;IMP
zoomlinse	zoomlinser	N;NDEF;PL
tommel	tommelen	N;DEF;SG
tilbakedanning	tilbakedanninga	N;DEF;SG
sitteplass	sitteplassene	N;DEF;PL
folkestyre	folkestyret	N;DEF;SG
sete	seter	N;NDEF;PL
rosin	rosina	N;DEF;SG
betaling	betalingene	N;DEF;PL
motehus	motehuset	N;DEF;SG
gravemaskin	gravemaskinene	N;DEF;PL
hockeykølle	hockeykøllene	N;DEF;PL
nasjonalsang	nasjonalsangen	N;DEF;SG
utnyttelse	utnyttelsen	N;DEF;SG
batteridrevet	batteridrevet	ADJ;NEUT;SG
høste	høst	V;IMP
skadelig	skadelig	ADJ;NEUT;SG
molekyl	molekyl	N;NDEF;PL
undervannsbåt	undervannsbåtene	N;DEF;PL
brøling	brølinga	N;DEF;SG
bombe	bomb	V;IMP
teori	teoriene	N;DEF;PL
handelsskip	handelsskipene	N;DEF;PL
skilt	skilta	N;DEF;PL
turkis	turkist	ADJ;NEUT;SG
bank	bankene	N;DEF;PL
beholde	beholdt	V;PST
estlender	estlenderen	N;DEF;SG
asiat	asiater	N;NDEF;PL
rulletrapp	rulletrappa	N;DEF;SG
nevne	nevnte	V;PST
øve	øvet	V.PTCP;PST
maskinvare	maskinvara	N;DEF;SG
samle	samle	V;IMP
ubegrenset	ubegrenset	ADJ;NEUT;SG
tavle	tavlen	N;DEF;SG
tusendel	tusendeler	N;NDEF;PL
svart	svart	ADJ;NEUT;SG
stolt	stolte	ADJ;DEF;SG+PL
kvartett	kvartetter	N;NDEF;PL
lam	lam	N;NDEF;PL
flystripe	flystripene	N;DEF;PL
sende	sendende	V.PTCP;PRS
føll	føll	N;NDEF;PL
soverom	soverom	N;NDEF;PL
pingvin	pingvinene	N;DEF;PL
hyggelig	hyggelige	ADJ;DEF;SG+PL
individ	individet	N;DEF;SG
foto	fotoet	N;DEF;SG
være	væra	V;PST
telefonsentral	telefonsentraler	N;NDEF;PL
heise	heist	V.PTCP;PST
fanatiker	fanatikeren	N;DEF;SG
kull	kullene	N;DEF;PL
løfte	løftet	N;DEF;SG
eksistere	eksister	V;IMP
kalender	kalendrer	N;NDEF;PL
kinesisk	kinesisk	ADJ;NEUT;SG
undervurdering	undervurderingene	N;DEF;PL
korall	korallene	N;DEF;PL
kjøre	kjørte	V;PST
gardin	gardina	N;DEF;PL
karantene	karantenene	N;DEF;PL
stor	størst	ADJ;SPRL;NDEF
iraker	irakeren	N;DEF;SG
jordbruk	jordbruk	N;NDEF;PL
medisinsk	medisinsk	ADJ;NEUT;SG
hvite	hviter	N;NDEF;PL
maursluker	maurslukeren	N;DEF;SG
veranda	verandaen	N;DEF;SG
galoppbane	galoppbanene	N;DEF;PL
potteplante	potteplanta	N;DEF;SG
gen	genene	N;DEF;PL
sviske	svisker	N;NDEF;PL
maursluker	maurslukerne	N;DEF;PL
særegen	særegent	ADJ;NEUT;SG
kartlegge	kartleggende	V.PTCP;PRS
eksperimentere	eksperimentert	V.PTCP;PST
konsentrert	konsentrerte	ADJ;DEF;SG+PL
bambusrør	bambusrøra	N;DEF;PL
nøytron	nøytrona	N;DEF;PL
baksete	bakseter	N;NDEF;PL
pisse	pissa	V.PTCP;PST
dieselmotor	dieselmotoren	N;DEF;SG
puré	puréen	N;DEF;SG
økonomisere	økonomiserte	V;PST
øyelokk	øyelokkene	N;DEF;PL
foto	fotoa	N;DEF;PL
datavirus	datavirus	N;NDEF;PL
kjøkken	kjøkkenene	N;DEF;PL
åpning	åpninga	N;DEF;SG
inntrykk	inntrykket	N;DEF;SG
bokstav	bokstaver	N;NDEF;PL
idé	ideene	N;DEF;PL
næringsstoff	næringsstoffa	N;DEF;PL
retning	retningen	N;DEF;SG
identitet	identiteten	N;DEF;SG
fjord	fjordene	N;DEF;PL
utdanning	utdanninger	N;NDEF;PL
sørafrikaner	sørafrikanere	N;NDEF;PL
beundre	beundret	V;PST
åsside	åssiden	N;DEF;SG
bein	beinet	N;DEF;SG
wienerpølse	wienerpølser	N;NDEF;PL
bombe	bombene	N;DEF;PL
finne opp	finn opp	V;IMP
minutt	minutt	N;NDEF;PL
stjert	stjerter	N;NDEF;PL
gård	gårdene	N;DEF;PL
slips	slipsene	N;DEF;PL
ønskeliste	ønskelistene	N;DEF;PL
vendepunkt	vendepunktet	N;DEF;SG
fuktighetskrem	fuktighetskremen	N;DEF;SG
pælerot	pælerøtter	N;NDEF;PL
ikon	ikonene	N;DEF;PL
sort	sorte	ADJ;DEF;SG+PL
lok	loka	N;DEF;PL
ferge	fergen	N;DEF;SG
hummer	hummere	N;NDEF;PL
resultat	resultatene	N;DEF;PL
sen	seneste	ADJ;SPRL;DEF
hær	hærer	N;NDEF;PL
våkne	våkna	V;PST
grunnlag	grunnlagene	N;DEF;PL
sklie	skliene	N;DEF;PL
arbeidstager	arbeidstagere	N;NDEF;PL
alfabet	alfabeter	N;NDEF;PL
svane	svaner	N;NDEF;PL
nøkkel	nøkkelen	N;DEF;SG
tempo	tempoet	N;DEF;SG
sanktvinsenter	sanktvinsenterne	N;DEF;PL
arbeidsuke	arbeidsukene	N;DEF;PL
kråke	kråka	N;DEF;SG
forpliktelse	forpliktelsene	N;DEF;PL
myte	myten	N;DEF;SG
krysse	krysset	V;PST
såpe	såpen	N;DEF;SG
rotbløyte	rotbløyter	N;NDEF;PL
dansk	danske	ADJ;DEF;SG+PL
lei	leien	N;DEF;SG
kontur	konturer	N;NDEF;PL
mosambiker	mosambikere	N;NDEF;PL
kølle	køllen	N;DEF;SG
kongedømme	kongedømmer	N;NDEF;PL
terrorisere	terroriserer	V;PRS
apparat	apparata	N;DEF;PL
eksponering	eksponeringen	N;DEF;SG
frakt	frakta	N;DEF;SG
forfriske	forfriska	V;PST
bruke	bruker	V;PRS
restaurant	restauranten	N;DEF;SG
kamel	kamelen	N;DEF;SG
sitteplass	sitteplassen	N;DEF;SG
system	systemene	N;DEF;PL
dreie	dreiende	V.PTCP;PRS
objektiv	objektiv	N;NDEF;PL
musikalsk	musikalske	ADJ;DEF;SG+PL
bambus	bambusene	N;DEF;PL
bore	bora	V;PST
frihet	friheta	N;DEF;PL
pinsevenn	pinsevenner	N;NDEF;PL
sandstrand	sandstranda	N;DEF;SG
gnager	gnageren	N;DEF;SG
polakk	polakker	N;NDEF;PL
håndtrykk	håndtrykk	N;NDEF;PL
australier	australierne	N;DEF;PL
sørafrikaner	sørafrikaneren	N;DEF;SG
allé	alleen	N;DEF;SG
park	parken	N;DEF;SG
tiger	tigrene	N;DEF;PL
meteorolog	meteorologene	N;DEF;PL
intervju	intervjuene	N;DEF;PL
selvisk	selvisk	ADJ;NEUT;SG
skoleveske	skoleveska	N;DEF;SG
eksempel	eksempel	N;NDEF;PL
brødrister	brødristeren	N;DEF;SG
utdanne	utdann	V;IMP
billett	billettene	N;DEF;PL
amfiteater	amfiteater	N;NDEF;PL
bilbelte	bilbeltet	N;DEF;SG
tablett	tabletten	N;DEF;SG
mindretall	mindretallene	N;DEF;PL
esel	eslene	N;DEF;PL
sabotasje	sabotasjer	N;NDEF;PL
bred	bredest	ADJ;SPRL;NDEF
sangerinne	sangerinna	N;DEF;SG
snøball	snøballene	N;DEF;PL
drittsekk	drittsekken	N;DEF;SG
salami	salamier	N;NDEF;PL
rike	rika	N;DEF;PL
vannhund	vannhundene	N;DEF;PL
krystall	krystalla	N;DEF;PL
bulevard	bulevardene	N;DEF;PL
togoleser	togoleserne	N;DEF;PL
oversetter	oversetterne	N;DEF;PL
mykne	mykner	V;PRS
håndflate	håndflater	N;NDEF;PL
kran	kranen	N;DEF;SG
handlevogn	handlevogner	N;NDEF;PL
tommelfinger	tommelfingrer	N;NDEF;PL
fyrverkeri	fyrverkerier	N;NDEF;PL
gass	gassene	N;DEF;PL
tilbehør	tilbehør	N;NDEF;PL
forsinkelse	forsinkelser	N;NDEF;PL
tiger	tigere	N;NDEF;PL
oppvaskmiddel	oppvaskmidlene	N;DEF;PL
trofé	troféen	N;DEF;SG
sebra	sebraene	N;DEF;PL
kjøttmeis	kjøttmeisen	N;DEF;SG
jekk	jekken	N;DEF;SG
føde	fødte	V;PST
glorifisere	glorifisert	V.PTCP;PST
klatre	klatrer	V;PRS
forurensning	forurensninga	N;DEF;SG
angripe	angrip	V;IMP
postboks	postbokser	N;NDEF;PL
trio	trioen	N;DEF;SG
gelé	geléen	N;DEF;SG
grimase	grimasene	N;DEF;PL
synonymordbok	synonymordboken	N;DEF;SG
hyene	hyenene	N;DEF;PL
julepresang	julepresangen	N;DEF;SG
eggeplomme	eggeplommen	N;DEF;SG
koreansk	koreanske	ADJ;DEF;SG+PL
ytringsfrihet	ytringsfrihetene	N;DEF;PL
lår	lår	N;NDEF;PL
åsyn	åsyna	N;DEF;PL
rullebane	rullebanene	N;DEF;PL
folkemord	folkemordene	N;DEF;PL
alkan	alkaner	N;NDEF;PL
skjære	skjærer	N;NDEF;PL
luftskip	luftskip	N;NDEF;PL
konstitusjon	konstitusjonen	N;DEF;SG
selger	selgerne	N;DEF;PL
sirkelsag	sirkelsager	N;NDEF;PL
diplomati	diplomatiene	N;DEF;PL
newager	newageren	N;DEF;SG
grønlender	grønlenderen	N;DEF;SG
forsage	forsager	V;PRS
dobbelthake	dobbelthaken	N;DEF;SG
stær	stærene	N;DEF;PL
mikronesier	mikronesierne	N;DEF;PL
monark	monarker	N;NDEF;PL
kopp	kopper	N;NDEF;PL
topografisk	topografisk	ADJ;NEUT;SG
stadium	stadiene	N;DEF;PL
alkoholmisbruk	alkoholmisbruken	N;DEF;SG
død og maktesløs	dødt og maktesløst	ADJ;NEUT;SG
beundre	beundrer	V;PRS
liste	lister	V;PRS
luftfoto	luftfotoa	N;DEF;PL
be	be	V;IMP
latterlig	latterlig	ADJ;NEUT;SG
arbeide	arbeida	V.PTCP;PST
mors	mors	N;NDEF;PL
ordfører	ordførerne	N;DEF;PL
kai	kaier	N;NDEF;PL
virus	viruset	N;DEF;SG
platespiller	platespillere	N;NDEF;PL
synagoge	synagogene	N;DEF;PL
negl	neglene	N;DEF;PL
kubikkmeter	kubikkmeterne	N;DEF;PL
attraksjon	attraksjonen	N;DEF;SG
kjøkkenredskap	kjøkkenredskaper	N;NDEF;PL
forgiftning	forgiftninga	N;DEF;SG
strand	strendene	N;DEF;PL
strøm	strømmen	N;DEF;SG
tvinge	tvinger	V;PRS
maleri	maleria	N;DEF;PL
prest	prestene	N;DEF;PL
inndele	inndel	V;IMP
analog	analogt	ADJ;NEUT;SG
gammeldags	gammeldagse	ADJ;DEF;SG+PL
baksete	baksetene	N;DEF;PL
kreasjon	kreasjoner	N;NDEF;PL
fjellklatrer	fjellklatrere	N;NDEF;PL
flykropp	flykroppen	N;DEF;SG
tilsetningsstoff	tilsetningsstoff	N;NDEF;PL
iskrem	iskremen	N;DEF;SG
bidronning	bidronningene	N;DEF;PL
endelig	endelig	ADJ;NEUT;SG
omdirigere	omdiriger	V;IMP
urenhet	urenhetene	N;DEF;PL
stenge	stengte	V;PST
mikroskop	mikroskopet	N;DEF;SG
havfrue	havfrua	N;DEF;SG
entomolog	entomologen	N;DEF;SG
sikring	sikringa	N;DEF;SG
katt	katten	N;DEF;SG
ekkolodd	ekkolodda	N;DEF;PL
papegøye	papegøyene	N;DEF;PL
slå	slående	V.PTCP;PRS
korsett	korsettene	N;DEF;PL
gyngehest	gyngehester	N;NDEF;PL
løype	løyper	N;NDEF;PL
leke	leken	N;DEF;SG
melk	melka	N;DEF;SG
kupong	kupongen	N;DEF;SG
fønikisk	fønikiske	ADJ;DEF;SG+PL
hode	hoder	N;NDEF;PL
notisbok	notisboken	N;DEF;SG
boksåpner	boksåpneren	N;DEF;SG
debut	debutene	N;DEF;PL
ambassadør	ambassadørene	N;DEF;PL
skjønnhet	skjønnhetene	N;DEF;PL
prøve	prøva	N;DEF;SG
langtidsvarsel	langtidsvarslet	N;DEF;SG
briste	brister	V;PRS
insekt	insekta	N;DEF;PL
doktrine	doktrinen	N;DEF;SG
drypp	dryppet	N;DEF;SG
lang	lengste	ADJ;SPRL;DEF
skøyte	skøytene	N;DEF;PL
løsne	løsn	V;IMP
rull	rullene	N;DEF;PL
nederlender	nederlenderen	N;DEF;SG
uassistert	uassistert	ADJ;NEUT;SG
tåre	tårene	N;DEF;PL
svigermor	svigermora	N;DEF;SG
vertsmaskin	vertsmaskinen	N;DEF;SG
sommer	sommerne	N;DEF;PL
periode	perioder	N;NDEF;PL
golfkølle	golfkøller	N;NDEF;PL
vestlig	vestlige	ADJ;DEF;SG+PL
drosje	drosjene	N;DEF;PL
sperre	sperr	V;IMP
leite	leitte	V;PST
konspirasjonsteori	konspirasjonsteoriene	N;DEF;PL
oppleve	opplever	V;PRS
gjøre	gjør	V;PRS
trenge	treng	V;IMP
tidsskrift	tidsskrift	N;NDEF;PL
underjordisk	underjordiske	ADJ;DEF;SG+PL
avdrag	avdrag	N;NDEF;PL
kritikk	kritikker	N;NDEF;PL
metanol	metanolen	N;DEF;SG
rå	råa	N;DEF;SG
spir	spirer	N;NDEF;PL
ferskvann	ferskvannene	N;DEF;PL
tur	turen	N;DEF;SG
annen	anna	ADJ;FEM
samling	samlinger	N;NDEF;PL
vits	vitsene	N;DEF;PL
heire	heiren	N;DEF;SG
pattedyr	pattedyra	N;DEF;PL
gladiator	gladiatoren	N;DEF;SG
balltre	balltreet	N;DEF;SG
parasitt	parasitten	N;DEF;SG
kappverder	kappverderen	N;DEF;SG
program	programmer	N;NDEF;PL
arbeidsgiver	arbeidsgivere	N;NDEF;PL
publikasjon	publikasjonen	N;DEF;SG
meteor	meteorer	N;NDEF;PL
inflasjon	inflasjonene	N;DEF;PL
kildekode	kildekoden	N;DEF;SG
dødelig	dødelige	ADJ;DEF;SG+PL
søndag	søndagen	N;DEF;SG
pinnsvin	pinnsvina	N;DEF;PL
rød	røde	ADJ;DEF;SG+PL
støvel	støvelen	N;DEF;SG
plass	plassene	N;DEF;PL
edel	edle	ADJ;DEF;SG+PL
sosialisme	sosialismen	N;DEF;SG
sal	saler	N;NDEF;PL
etasje	etasjer	N;NDEF;PL
gå	gående	V.PTCP;PRS
valp	valper	N;NDEF;PL
hand	hendene	N;DEF;PL
vegetabilsk	vegetabilske	ADJ;DEF;SG+PL
regne	regnet	V;PST
romtemperatur	romtemperaturene	N;DEF;PL
elskerinne	elskerinna	N;DEF;SG
lengsel	lengselen	N;DEF;SG
elektriker	elektrikeren	N;DEF;SG
ekvator	ekvatorer	N;NDEF;PL
sonde	sonden	N;DEF;SG
moden	modne	ADJ;DEF;SG+PL
servitør	servitøren	N;DEF;SG
reservoar	reservoarene	N;DEF;PL
skarp	skarpeste	ADJ;SPRL;DEF
bety	betød	V;PST
grenadier	grenadieren	N;DEF;SG
språkforsker	språkforskeren	N;DEF;SG
frigjort	frigjorte	ADJ;DEF;SG+PL
finner	finneren	N;DEF;SG
lete	lette	V;PST
finne sted	fant sted	V;PST
tiår	tiår	N;NDEF;PL
hjort	hjorten	N;DEF;SG
mørk	mørke	ADJ;DEF;SG+PL
avgjørelse	avgjørelsen	N;DEF;SG
tante	tanten	N;DEF;SG
giver	giveren	N;DEF;SG
ål	ålen	N;DEF;SG
antyde	antyda	V;PST
ateistisk	ateistiske	ADJ;DEF;SG+PL
varemerke	varemerker	N;NDEF;PL
subtraksjon	subtraksjonen	N;DEF;SG
spire	spira	N;DEF;SG
tilskuer	tilskuere	N;NDEF;PL
høne	hønene	N;DEF;PL
sentrum	sentraene	N;DEF;PL
hoppe	hoppen	N;DEF;SG
skarv	skarven	N;DEF;SG
subtrahere	subtraherte	V;PST
gift	gift	ADJ;NEUT;SG
salmebok	salmebøker	N;NDEF;PL
adressat	adressaten	N;DEF;SG
signatur	signaturer	N;NDEF;PL
minne	minnet	N;DEF;SG
ubevæpnet	ubevæpnete	ADJ;DEF;SG+PL
beherske	behersket	V;PST
holdning	holdningen	N;DEF;SG
pessimist	pessimister	N;NDEF;PL
aggressiv	aggressive	ADJ;DEF;SG+PL
spanjol	spanjolene	N;DEF;PL
forsinke	forsinker	V;PRS
garanti	garantiene	N;DEF;PL
tysker	tyskeren	N;DEF;SG
pinnsvin	pinnsvinet	N;DEF;SG
nepaler	nepalerne	N;DEF;PL
karikatur	karikaturen	N;DEF;SG
vitenskapelig	vitenskapelige	ADJ;DEF;SG
ambisjon	ambisjoner	N;NDEF;PL
byge	bygen	N;DEF;SG
bratt	brattest	ADJ;SPRL;NDEF
kabinett	kabinettene	N;DEF;PL
reprodusere	reproduserende	V.PTCP;PRS
synge	synger	V;PRS
kontakte	kontakta	V;PST
stenge	stengt	V.PTCP;PST
vakt	vakter	N;NDEF;PL
gummistøvel	gummistøvler	N;NDEF;PL
utsette	utsett	V;IMP
innhøste	innhøsta	V;PST
zimbabwer	zimbabwerne	N;DEF;PL
matforgiftning	matforgiftningene	N;DEF;PL
fjern	fjernest	ADJ;SPRL;NDEF
heire	heirene	N;DEF;PL
kjemi	kjemien	N;DEF;SG
franskmann	franskmenn	N;NDEF;PL
tennplugg	tennpluggen	N;DEF;SG
pilegrim	pilegrimer	N;NDEF;PL
sirkus	sirkuser	N;NDEF;PL
invasjon	invasjoner	N;NDEF;PL
oppheve	opphevende	V.PTCP;PRS
sump	sumpene	N;DEF;PL
alvorlig	alvorlig	ADJ;NEUT;SG
papegøye	papegøyer	N;NDEF;PL
tilhører	tilhørerne	N;DEF;PL
motstander	motstanderen	N;DEF;SG
fotografi	fotografier	N;NDEF;PL
mangel	manglene	N;DEF;PL
andel	andeler	N;NDEF;PL
ansvarlig	ansvarlig	ADJ;NEUT;SG
leie	leid	V.PTCP;PST
investering	investeringer	N;NDEF;PL
luxembourger	luxembourgere	N;NDEF;PL
innføring	innføringer	N;NDEF;PL
milliliter	milliliteren	N;DEF;SG
brukergrensesnitt	brukergrensesnittet	N;DEF;SG
elde	eldet	V;PST
befolkning	befolkninger	N;NDEF;PL
dreiemoment	dreiemomenta	N;DEF;PL
bord	borda	N;DEF;PL
utopisk	utopisk	ADJ;NEUT;SG
tilby	tilbudt	V.PTCP;PST
historie	historier	N;NDEF;PL
fanatisk	fanatiske	ADJ;DEF;SG+PL
arkitekt	arkitektene	N;DEF;PL
pulverisere	pulveriser	V;IMP
skygge	skyggene	N;DEF;PL
milliliter	milliliter	N;NDEF;PL
larve	larvene	N;DEF;PL
sikt	sikter	N;NDEF;PL
røve	røvd	V.PTCP;PST
bleik	bleikest	ADJ;SPRL;NDEF
hjelper	hjelperen	N;DEF;SG
nederlandsk	nederlandsk	ADJ;NEUT;SG
statsoverhode	statsoverhodet	N;DEF;SG
motvirke	motvirk	V;IMP
ventil	ventilen	N;DEF;SG
komparativ	komparativene	N;DEF;PL
kobberrør	kobberrøra	N;DEF;PL
hoppe	hoppene	N;DEF;PL
pronomen	pronomener	N;NDEF;PL
angstbiteri	angstbiteriene	N;DEF;PL
ordklasse	ordklassen	N;DEF;SG
protestant	protestantene	N;DEF;PL
sudaner	sudanerne	N;DEF;PL
sverm	svermen	N;DEF;SG
moralsk	moralsk	ADJ;NEUT;SG
folie	foliene	N;DEF;PL
maksimal	maksimalt	ADJ;NEUT;SG
karboksylsyre	karboksylsyrene	N;DEF;PL
mørk	mørkeste	ADJ;SPRL;DEF
tysk	tysk	ADJ;NEUT;SG
dagsorden	dagsordenen	N;DEF;SG
bærbar	bærbart	ADJ;NEUT
jordbær	jordbæret	N;DEF;SG
farlig	farligste	ADJ;SPRL;DEF
tempel	templene	N;DEF;PL
fuktighet	fuktigheta	N;DEF;SG
akilleshæl	akilleshælen	N;DEF;SG
pass	passet	N;DEF;SG
skohorn	skohornene	N;DEF;PL
aprikos	aprikosene	N;DEF;PL
rose	rosen	N;DEF;SG
fotballspiller	fotballspillerne	N;DEF;PL
leketøy	leketøyer	N;NDEF;PL
villdyr	villdyret	N;DEF;SG
newzealandsk	newzealandske	ADJ;DEF;SG+PL
adjektiv	adjektiv	N;NDEF;PL
regime	regimet	N;DEF;SG
dataprogram	dataprogrammet	N;DEF;SG
jomfru	jomfruene	N;DEF;PL
avarisk	avariske	ADJ;DEF;SG+PL
relevans	relevansen	N;DEF;SG
temperatur	temperaturer	N;NDEF;PL
abakus	abakusene	N;DEF;PL
perle	perler	N;NDEF;PL
jevndøgn	jevndøgna	N;DEF;PL
bryst	brystet	N;DEF;SG
valp	valpene	N;DEF;PL
trafikklys	trafikklysa	N;DEF;PL
trommehinne	trommehinnen	N;DEF;SG
kakerlakk	kakerlakkene	N;DEF;PL
konnotasjon	konnotasjoner	N;NDEF;PL
singel	singelene	N;DEF;PL
tempel	tempelet	N;DEF;SG
gutt	gutten	N;DEF;SG
strekkode	strekkodene	N;DEF;PL
finale	finaler	N;NDEF;PL
anklage	anklagde	V;PST
skjermutklipp	skjermutklippet	N;DEF;SG
amfetamin	amfetaminer	N;NDEF;PL
løype	løyp	V;IMP
boks	boksene	N;DEF;PL
pandemisk	pandemisk	ADJ;NEUT;SG
påskelilje	påskeliljer	N;NDEF;PL
anneks	anneksene	N;DEF;PL
kvadrat	kvadrat	N;NDEF;PL
plasma	plasma	N;NDEF;PL
hysteri	hysteriet	N;DEF;SG
islamsk	islamsk	ADJ;NEUT;SG
bøtte	bøttene	N;DEF;PL
symbol	symbolene	N;DEF;PL
omslag	omslaget	N;DEF;SG
samleie	samleia	N;DEF;PL
bordell	bordellene	N;DEF;PL
ny	nytt	ADJ;NEUT;SG
dryppe	dryppende	V.PTCP;PRS
utsolgt	utsolgt	ADJ;NEUT;SG
varemerke	varemerket	N;DEF;SG
overstige	oversteget	V.PTCP;PST
kontaktlinse	kontaktlinsen	N;DEF;SG
juvel	juvelen	N;DEF;SG
portugisisk	portugisisk	ADJ;NEUT;SG
nivå	nivå	N;NDEF;PL
zimbabwer	zimbabwere	N;NDEF;PL
brunsttid	brunsttider	N;NDEF;PL
frimerke	frimerkene	N;DEF;PL
punkt	punkter	N;NDEF;PL
tann	tennene	N;DEF;PL
pasient	pasientene	N;DEF;PL
steinbrudd	steinbrudd	N;NDEF;PL
stål	stålet	N;DEF;SG
rekke	rekkene	N;DEF;PL
selleri	selleriene	N;DEF;PL
skulder	skulderen	N;DEF;SG
sjøfugl	sjøfuglene	N;DEF;PL
presang	presangen	N;DEF;SG
folie	folier	N;NDEF;PL
fokusere	fokuser	V;IMP
fungere	fungerer	V;PRS
nøkkelhull	nøkkelhullet	N;DEF;SG
kryss	kryssene	N;DEF;PL
jødisk	jødiske	ADJ;DEF;SG+PL
senegaleser	senegaleserne	N;DEF;PL
banansplitt	banansplitter	N;NDEF;PL
under	undre	N;NDEF;SG
bordduk	borddukene	N;DEF;PL
luktfri	luktfritt	ADJ;NEUT;SG
branndør	branndørene	N;DEF;PL
snøbrett	snøbretter	N;NDEF;PL
kleshenger	kleshengere	N;NDEF;PL
fastnøkkel	fastnøklene	N;DEF;PL
pris	priser	N;NDEF;PL
koordinasjon	koordinasjoner	N;NDEF;PL
bahamaner	bahamanerne	N;DEF;PL
ambassade	ambassaden	N;DEF;SG
høns	hønsene	N;DEF;PL
pattedyr	pattedyrene	N;DEF;PL
bøtte	bøtter	N;NDEF;PL
ekvilibrium	ekvilibrium	N;NDEF;PL
amøbe	amøbene	N;DEF;PL
mur	muren	N;DEF;SG
lyn	lynet	N;DEF;SG
nål	nåler	N;NDEF;PL
syn	syne	V;GEN
annen	andre	ADJ;DEF
fall	fallet	N;DEF;SG
skygge	skyggen	N;DEF;SG
offiser	offiseren	N;DEF;SG
modifisere	modifiser	V;IMP
ressurs	ressursen	N;DEF;SG
aluminium	aluminiumen	N;DEF;SG
mongol	mongoler	N;NDEF;PL
faste	fastet	V;PST
ryggsekk	ryggsekker	N;NDEF;PL
encellet	encellede	ADJ;DEF;SG+PL
vinglass	vinglass	N;NDEF;PL
atavisme	atavismer	N;NDEF;PL
lang	lange	ADJ;DEF;SG+PL
skinne	skinnen	N;DEF;SG
skinn	skinnet	N;DEF;SG
amerikanisere	amerikanisert	V.PTCP;PST
forene	forente	V;PST
tabell	tabellene	N;DEF;PL
labyrint	labyrinten	N;DEF;SG
verdensmesterskap	verdensmesterskap	N;NDEF;PL
yoghurt	yoghurten	N;DEF;SG
fattigdom	fattigdommen	N;DEF;SG
sikksakkbevegelse	sikksakkbevegelsen	N;DEF;SG
timeglass	timeglassene	N;DEF;PL
bordell	bordella	N;DEF;PL
langtidsvarsel	langtidsvarsler	N;NDEF;PL
undervise	underviser	V;PRS
helvete	helvetes	N;GEN
beskjære	beskar	V;PST
flaskeåpner	flaskeåpneren	N;DEF;SG
rep	repa	N;DEF;PL
ark	arkene	N;DEF;PL
løype	løypte	V;PST
krav	krava	N;DEF;PL
flytur	flyturer	N;NDEF;PL
dekke	dekket	V;PST
bruneier	bruneiere	N;NDEF;PL
glassverk	glassverk	N;NDEF;PL
objekt	objekter	N;NDEF;PL
hode	hoda	N;DEF;PL
ekko	ekko	N;NDEF;PL
gate	gaten	N;DEF;SG
nær	nære	ADJ;DEF;SG+PL
sabbat	sabbaten	N;DEF;SG
vann	vannet	N;DEF;SG
blåbær	blåbæra	N;DEF;PL
eksemplarisk	eksemplarisk	ADJ;CMPR
trinidader	trinidaderen	N;DEF;SG
koordinere	koordinerte	V;PST
beskjære	beskåret	V.PTCP;PST
kanal	kanalene	N;DEF;PL
fjell	fjellet	N;DEF;SG
byfornyelse	byfornyelsen	N;DEF;SG
suvenir	suvenirene	N;DEF;PL
reagere	reagerer	V;PRS
evakuere	evakuerte	V;PST
treverk	treverker	N;NDEF;PL
oppslagsverk	oppslagsverkene	N;DEF;PL
varme	varma	V;PST
lamme	lammer	V;PRS
inkontinent	inkontinente	ADJ;DEF;SG+PL
sone	soner	N;NDEF;PL
svak	svake	ADJ;DEF;SG+PL
vakuum	vakuumet	N;DEF;SG
lys	lysa	N;DEF;PL
rettighet	rettighetene	N;DEF;PL
garderobe	garderobene	N;DEF;PL
dødfødt	dødfødte	ADJ;DEF;SG+PL
kylling	kyllinger	N;NDEF;PL
komma	kommaene	N;DEF;PL
måler	målerne	N;DEF;PL
fakkel	fakkelen	N;DEF;SG
sentralafrikaner	sentralafrikanere	N;NDEF;PL
avdrag	avdragene	N;DEF;PL
sortere	sortert	V.PTCP;PST
ofre	ofrer	V;PRS
lande	land	V;IMP
kattunge	kattungen	N;DEF;SG
alkohol	alkoholer	N;NDEF;PL
viktig	viktige	ADJ;DEF;SG+PL
malawier	malawieren	N;DEF;SG
skudd	skuddene	N;DEF;PL
medisin	medisinen	N;DEF;SG
regne	regnte	V;PST
knapphull	knapphulla	N;DEF;PL
allmenn	allmenne	ADJ;DEF;SG+PL
finne	finner	N;NDEF;PL
danske	dansker	N;NDEF;PL
anklage	anklaget	V;PST
laboratorium	laboratoriet	N;DEF;SG
vakker	vakkert	ADJ;NEUT;SG
vise	vist	V.PTCP;PST
atrofi	atrofier	N;NDEF;PL
sterk	sterkeste	ADJ;SPRL;DEF
kylling	kyllingen	N;DEF;SG
vinter	vintrene	N;DEF;PL
ven	venere	ADJ;CMPR
vollgrav	vollgravene	N;DEF;PL
oversjøisk	oversjøisk	ADJ;NEUT;SG
rabarbra	rabarbraene	N;DEF;PL
abort	abortene	N;DEF;PL
tapet	tapet	N;NDEF;PL
gjel	gjelene	N;DEF;PL
ivorianer	ivorianeren	N;DEF;SG
månedlig	månedlig	ADJ;NEUT;SG
knute	knutene	N;DEF;PL
trontale	trontaler	N;NDEF;PL
romsonde	romsonder	N;NDEF;PL
sukkerroe	sukkerroer	N;NDEF;PL
kongefamilie	kongefamiliene	N;DEF;PL
steikepanne	steikepanna	N;DEF;SG
skandinav	skandinavene	N;DEF;PL
verb	verber	N;NDEF;PL
samling	samlinga	N;DEF;SG
trille	trillene	N;DEF;PL
kenyaner	kenyanere	N;NDEF;PL
husdyr	husdyret	N;DEF;SG
sjakt	sjakter	N;NDEF;PL
blodgiver	blodgiverne	N;DEF;PL
basere	basert	V.PTCP;PST
akselerasjon	akselerasjonene	N;DEF;PL
sider	sidrene	N;DEF;PL
innhøste	innhøstet	V;PST
forbruker	forbrukeren	N;DEF;SG
massakre	massakrer	N;NDEF;PL
mistanke	mistanker	N;NDEF;PL
restaurering	restaureringer	N;NDEF;PL
tjeneste	tjenester	N;NDEF;PL
ligning	ligningen	N;DEF;SG
perfekt	perfekt	ADJ;NEUT;SG
forbedre	forbedrer	V;PRS
mobil	mobile	ADJ;DEF;SG+PL
forstad	forsteder	N;NDEF;PL
varsler	varslerne	N;DEF;PL
stasjonsvogn	stasjonsvognen	N;DEF;SG
ballkjole	ballkjoler	N;NDEF;PL
stjernetegn	stjernetegn	N;NDEF;PL
øl	ølet	N;DEF;SG
barnebarn	barnebarnet	N;DEF;SG
pilot	pilotene	N;DEF;PL
fordel	fordelene	N;DEF;PL
sardin	sardinene	N;DEF;PL
tosk	tosker	N;NDEF;PL
tysker	tyskere	N;NDEF;PL
hamre	hamra	V;PST
overstige	overstig	V;IMP
sovepose	soveposer	N;NDEF;PL
tsjader	tsjaderne	N;DEF;PL
gaboner	gaboneren	N;DEF;SG
gyngehest	gyngehestene	N;DEF;PL
løvetann	løvetannen	N;DEF;SG
drivstoff	drivstoff	N;NDEF;PL
jernmalm	jernmalmer	N;NDEF;PL
sabbat	sabbater	N;NDEF;PL
kostarikaner	kostarikaneren	N;DEF;SG
dopplereffekt	dopplereffekten	N;DEF;SG
tusenbein	tusenbeinene	N;DEF;PL
nedgradere	nedgraderende	V.PTCP;PRS
sjørøveri	sjørøveri	N;NDEF;PL
passere	passerer	V;PRS
telle	tellet	V.PTCP;PST
kraftverk	kraftverker	N;NDEF;PL
gulv	gulvene	N;DEF;PL
hauk	hauken	N;DEF;SG
regnvann	regnvannet	N;DEF;SG
bord	bordene	N;DEF;PL
seismologi	seismologien	N;DEF;SG
ordinere	ordinerte	V;PST
fald	falden	N;DEF;SG
venteliste	ventelister	N;NDEF;PL
forsinke	forsinkende	V.PTCP;PRS
korn	korna	N;DEF;SG
baderom	baderommet	N;DEF;SG
biskop	biskopen	N;DEF;SG
hensynsløs	hensynsløse	ADJ;DEF;SG+PL
flamsk	flamsk	ADJ;NEUT;SG
innføre	innført	V.PTCP;PST
plan	planene	N;DEF;PL
karriere	karrierer	N;NDEF;PL
spy	spydd	V.PTCP;PST
gjenkjenne	gjenkjente	V;PST
fakkel	fakler	N;NDEF;PL
reservoar	reservoarer	N;NDEF;PL
dikt	dikt	N;NDEF;PL
kvadratmeter	kvadratmeteren	N;DEF;SG
etterkommer	etterkommere	N;NDEF;PL
iraner	iranerne	N;DEF;PL
gulv	gulv	N;NDEF;PL
håndjern	håndjernene	N;DEF;PL
trompet	trompeter	N;NDEF;PL
falsk	falske	ADJ;DEF;SG+PL
frostvæske	frostvæsker	N;NDEF;PL
trakassering	trakasseringen	N;DEF;SG
spekter	spektrene	N;DEF;PL
sperrebånd	sperrebåndene	N;DEF;PL
hestekastanje	hestekastanjene	N;DEF;PL
skandinavisk	skandinaviske	ADJ;DEF;SG+PL
elskerinne	elskerinner	N;NDEF;PL
bombefly	bombeflyet	N;DEF;SG
innflytelsesrik	innflytelsesrikt	ADJ;NEUT;SG
mynt	myntene	N;DEF;PL
uløselig	uløselige	ADJ;DEF;SG+PL
dekke	dekte	V;PST
fjernsyn	fjernsynet	N;DEF;SG
alternativ	alternativene	N;DEF;PL
nøkkelhull	nøkkelhulla	N;DEF;PL
høyteknologisk	høyteknologisk	ADJ;NEUT;SG
foss	fossene	N;DEF;PL
kontrollere	kontrollerende	V.PTCP;PRS
firedoble	firedobla	V;PST
fjell	fjell	N;NDEF;PL
kokepunkt	kokepunkter	N;NDEF;PL
monolog	monologer	N;NDEF;PL
leikeplass	leikeplasser	N;NDEF;PL
etterligne	etterligna	V;PST
synge	sunget	V.PTCP;PST
sekund	sekunda	N;DEF;PL
ensfarget	ensfarget	ADJ;NEUT;SG
kork	korker	N;NDEF;PL
sykesøster	sykesøsterer	N;NDEF;PL
breddegrad	breddegrader	N;NDEF;PL
magnetisme	magnetismen	N;DEF;SG
skolisse	skolissene	N;DEF;PL
nervøs	nervøst	ADJ;NEUT;SG
talg	talgen	N;DEF;SG
sammenheng	sammenhengene	N;DEF;PL
mobil	mobiler	N;NDEF;PL
tidssone	tidssonene	N;DEF;PL
årsak	årsaken	N;DEF;SG
innkast	innkast	N;NDEF;PL
tapet	tapetet	N;DEF;SG
lilje	liljer	N;NDEF;PL
messing	messingen	N;DEF;SG
bakside	baksidene	N;DEF;PL
fall	fallene	N;DEF;PL
kjærlighetshistorie	kjærlighetshistoria	N;DEF;SG
sykkelsete	sykkelseta	N;DEF;PL
falle	faller	V;PRS
damp	dampene	N;DEF;PL
sanktkitter	sanktkittere	N;NDEF;PL
besøke	besøker	V;PRS
hvit	hvitt	ADJ;NEUT;SG
trekant	trekantene	N;DEF;PL
vokse	voksa	V;PST
gangren	gangrenen	N;DEF;SG
mineral	mineralet	N;DEF;SG
tyveri	tyveriet	N;DEF;SG
utgave	utgaven	N;DEF;SG
villdyr	villdyra	N;DEF;PL
negasjon	negasjoner	N;NDEF;PL
entreprenør	entreprenøren	N;DEF;SG
kaptein	kapteinene	N;DEF;PL
tørste	tørsta	V;PST
ugle	ugla	N;DEF;SG
breddegrad	breddegraden	N;DEF;SG
hestekastanje	hestekastanjer	N;NDEF;PL
antall	antallet	N;DEF;SG
blindeskrift	blindeskrifta	N;DEF;SG
ulykkelig	ulykkelige	ADJ;DEF;SG+PL
gissel	gisselen	N;DEF;SG
klippe	klippen	N;DEF;SG
sjørøver	sjørøveren	N;DEF;SG
kollega	kollegene	N;DEF;PL
nymfe	nymfene	N;DEF;PL
forbedre	forbedr	V;IMP
vanlig	vanligst	ADJ;SPRL;NDEF
europeisk	europeisk	ADJ;NEUT;SG
fasan	fasanen	N;DEF;SG
adresse	adressene	N;DEF;PL
sesong	sesongen	N;DEF;SG
argentiner	argentinere	N;NDEF;PL
golfbane	golfbaner	N;NDEF;PL
vennskap	vennskapa	N;DEF;PL
fredelig	fredeligst	ADJ;SPRL;NDEF
kommentar	kommentaren	N;DEF;SG
reagensrør	reagensrørene	N;DEF;PL
sosial	sosial	ADJ;CMPR
motorkjøretøy	motorkjøretøyet	N;DEF;SG
sjakal	sjakalen	N;DEF;SG
sommersolverv	sommersolvervet	N;DEF;SG
garasje	garasjer	N;NDEF;PL
elfenbeinstårn	elfenbeinstårna	N;DEF;PL
publikasjon	publikasjoner	N;NDEF;PL
allergi	allergien	N;DEF;SG
fjern	fjerne	ADJ;DEF;SG+PL
telefonnummer	telefonnummeret	N;DEF;SG
svømmebasseng	svømmebassenga	N;DEF;PL
bevisst	bevisst	ADJ;NEUT;SG
avsnitt	avsnittet	N;DEF;SG
snøfall	snøfall	N;NDEF;PL
entreprenør	entreprenørene	N;DEF;PL
nær	nært	ADJ;NEUT;SG
boble	boblende	V.PTCP;PRS
halv	halve	ADJ;DEF;SG+PL
sammenligne	sammenlignet	V;PST
velge	valgt	V.PTCP;PST
notatbok	notatbøker	N;NDEF;PL
or	orer	N;NDEF;PL
dybde	dybden	N;DEF;SG
erstatte	erstatter	V;PRS
tidssone	tidssoner	N;NDEF;PL
syn	syn	N;NDEF;PL
bestå	bestående	V.PTCP;PRS
amøbe	amøben	N;DEF;SG
etterforske	etterforsket	V;PST
monument	monumenta	N;DEF;PL
ultrafiolett	ultrafiolett	ADJ;NEUT;SG
implantat	implantatet	N;DEF;SG
opprettholde	oppretthold	V;IMP
bregne	bregna	N;DEF;SG
angstbiteri	angstbiterier	N;NDEF;PL
albue	albuene	N;DEF;PL
utstede	utsteder	V;PRS
syntetisere	syntetiserende	V.PTCP;PRS
male	mol	V;PST
garderobe	garderoben	N;DEF;SG
kusine	kusiner	N;NDEF;PL
programvare	programvarer	N;NDEF;PL
banansplitt	banansplitten	N;DEF;SG
vannkoker	vannkokeren	N;DEF;SG
rand	rand	N;NDEF;PL
sanger	sangerne	N;DEF;PL
grunnmur	grunnmuren	N;DEF;SG
snø	snødd	V.PTCP;PST
frigjøring	frigjøringer	N;NDEF;PL
tyggegummi	tyggegummiene	N;DEF;PL
reportasje	reportasjen	N;DEF;SG
snøleopard	snøleoparden	N;DEF;SG
krem	kremene	N;DEF;PL
bære	bær	V;IMP
larve	larver	N;NDEF;PL
bleike	bleiket	V;PST
hus	hus	N;NDEF;PL
stedfortreder	stedfortredere	N;NDEF;PL
subtraksjon	subtraksjonene	N;DEF;PL
forstillelse	forstillelsene	N;DEF;PL
skarlagen	skarlagenene	N;DEF;PL
ponni	ponniene	N;DEF;PL
entreprenør	entreprenører	N;NDEF;PL
tusjpenn	tusjpenner	N;NDEF;PL
skarv	skarver	N;NDEF;PL
los	losene	N;DEF;PL
spre	spredte	V;PST
fersk	ferskeste	ADJ;SPRL;DEF
luftbåren	luftbårne	ADJ;DEF;SG+PL
valutakurs	valutakurser	N;NDEF;PL
fugleskremsel	fugleskremsla	N;DEF;PL
implantat	implantater	N;NDEF;PL
sår	sår	N;NDEF;PL
ornitologisk	ornitologisk	ADJ;NEUT;SG
piktogram	piktogram	N;NDEF;PL
sirup	sirupene	N;DEF;PL
skrujern	skrujern	N;NDEF;PL
kiosk	kiosker	N;NDEF;PL
vadefugl	vadefuglen	N;DEF;SG
konklusjon	konklusjonen	N;DEF;SG
heldig	heldig	ADJ;NEUT;SG
bryllup	bryllupet	N;DEF;SG
handelsflåte	handelsflåtene	N;DEF;PL
debatt	debattene	N;DEF;PL
gjennomgå	gjennomgående	V.PTCP;PRS
vante	vantene	N;DEF;PL
regne	regna	V;PST
forum	forumene	N;DEF;PL
majestetisk	majestetiske	ADJ;DEF;SG+PL
tap	tapa	N;DEF;PL
rattstamme	rattstammen	N;DEF;SG
fløte	fløtt	V.PTCP;PST
innføring	innføringene	N;DEF;PL
viskøs	viskøse	ADJ;DEF;SG+PL
menstruasjonssyklus	menstruasjonssyklusene	N;DEF;PL
blindeskrift	blindeskriften	N;DEF;SG
plattform	plattformer	N;NDEF;PL
kokepunkt	kokepunktene	N;DEF;PL
vise	vis	V;IMP
determinativ	determinativet	N;DEF;SG
ekvilibrium	ekvilibriuma	N;DEF;PL
skriftspråk	skriftspråket	N;DEF;SG
kjønn	kjønnene	N;DEF;PL
bille	billen	N;DEF;SG
frysepunkt	frysepunktet	N;DEF;SG
portrett	portrettene	N;DEF;PL
innskrift	innskriftene	N;DEF;PL
lamme	lam	V;IMP
renovere	renoverte	V;PST
marje	marjer	N;NDEF;PL
håndfull	håndfullen	N;DEF;SG
oppheve	opphevde	V;PST
rand	render	N;NDEF;PL
omklassifisere	omklassifisert	V.PTCP;PST
sirkulasjon	sirkulasjonene	N;DEF;PL
mørk	mørkest	ADJ;SPRL;NDEF
tilsette	tilsett	V;IMP
avansere	avanserer	V;PRS
bygge	bygger	V;PRS
søsken	søskenet	N;DEF;SG
søtlig	søtlig	ADJ;NEUT;SG
korn	korn	N;NDEF;PL
leite	leitet	V.PTCP;PST
skrivebord	skriveborda	N;DEF;PL
vante	vanten	N;DEF;SG
syndebukk	syndebukker	N;NDEF;PL
filmstjerne	filmstjerna	N;DEF;SG
snømåke	snømåka	N;DEF;SG
stasjon	stasjonen	N;DEF;SG
plast	plasten	N;DEF;SG
vaskemaskin	vaskemaskinene	N;DEF;PL
vokal	vokalen	N;DEF;SG
andreplass	andreplassen	N;DEF;SG
bestefar	bestefedrene	N;DEF;PL
stedfortreder	stedfortrederne	N;DEF;PL
tvist	tvisten	N;DEF;SG
armenier	armeniere	N;NDEF;PL
kristadelfianer	kristadelfianeren	N;DEF;SG
eksplosjon	eksplosjonene	N;DEF;PL
løft	løfta	N;DEF;PL
spontanabort	spontanaborten	N;DEF;SG
luxemburger	luxemburgeren	N;DEF;SG
skruppelløs	skruppelløse	ADJ;DEF;SG+PL
ekko	ekkoet	N;DEF;SG
historiker	historikerne	N;DEF;PL
sperre	sperrer	V;PRS
aborigin	aboriginen	N;DEF;SG
elfenbeinstårn	elfenbeinstårnene	N;DEF;PL
syre	syra	N;DEF;SG
kirkegjenger	kirkegjengeren	N;DEF;SG
korn	kornene	N;DEF;SG
naboland	nabolanda	N;DEF;PL
støpe	støpt	V.PTCP;PST
dirigent	dirigentene	N;DEF;PL
likvidere	likviderte	V;PST
brødskive	brødskivene	N;DEF;PL
basalt	basalter	N;NDEF;PL
vokse	vokser	V;PRS
epletre	epletrærne	N;DEF;PL
transvestitt	transvestitten	N;DEF;SG
haug	hauger	N;NDEF;PL
silikon	silikona	N;DEF;PL
grue	gruer	N;NDEF;PL
gutt	guttene	N;DEF;PL
kronisk	kroniske	ADJ;DEF;SG+PL
ufarget	ufargede	ADJ;DEF;SG+PL
kynisme	kynismen	N;DEF;SG
sist	sist	ADJ;NEUT;SG
maori	maorier	N;NDEF;PL
surinamer	surinameren	N;DEF;SG
utemmet	utemmede	ADJ;DEF;SG+PL
skinne	skein	V;PST
anstøtelighet	anstøtelighetene	N;DEF;PL
apostel	apostelen	N;DEF;SG
henrettelse	henrettelser	N;NDEF;PL
kjølig	kjølig	ADJ;NEUT;SG
overhode	overhodet	N;DEF;SG
grunnleggelse	grunnleggelser	N;NDEF;PL
gitar	gitarene	N;DEF;PL
klosset	klossete	ADJ;DEF;SG+PL
morse	mors	V;IMP
kjøleskap	kjøleskap	N;NDEF;PL
snakk	snakken	N;DEF;SG
slektskap	slektskapen	N;DEF;SG
tuberkulose	tuberkulosen	N;DEF;SG
gjel	gjela	N;DEF;PL
kentaur	kentaurer	N;NDEF;PL
gråaktig	gråaktig	ADJ;NEUT;SG
tibetaner	tibetaneren	N;DEF;SG
røntgenbilde	røntgenbildene	N;DEF;PL
yoghurt	yoghurtene	N;DEF;PL
under	undret	N;DEF;SG
kniv	knivene	N;DEF;PL
fornektelse	fornektelser	N;NDEF;PL
vulkan	vulkanene	N;DEF;PL
rask	raskeste	ADJ;SPRL;DEF
marje	marjen	N;DEF;SG
hastighet	hastigheter	N;NDEF;PL
pil	pila	N;DEF;SG
terapeutisk	terapeutisk	ADJ;NEUT;SG
amfibium	amfibiet	N;DEF;SG
skriver	skriverne	N;DEF;PL
spesialitet	spesialiteter	N;NDEF;PL
container	containere	N;NDEF;PL
snø	snør	V;PRS
befri	befri	V;IMP
stekepanne	stekepanna	N;DEF;SG
vokse	voks	V;IMP
forsøk	forsøkene	N;DEF;PL
hydrokarbon	hydrokarbonene	N;DEF;PL
marked	markeder	N;NDEF;PL
avsnitt	avsnittene	N;DEF;PL
hendig	hendig	ADJ;NEUT;SG
steke	stekte	V;PST
nymfomani	nymfomanien	N;DEF;SG
purre	purrene	N;DEF;PL
sjonglør	sjongløren	N;DEF;SG
mekaniker	mekanikerne	N;DEF;PL
insekt	insekt	N;NDEF;PL
ha	ha	V;IMP
felt	felt	N;NDEF;PL
sirkulasjon	sirkulasjonen	N;DEF;SG
stasjonær	stasjonært	ADJ;NEUT;SG
spørsmålstegn	spørsmålstegnene	N;DEF;PL
sabotere	saboter	V;IMP
diskusjon	diskusjoner	N;NDEF;PL
radiobil	radiobilen	N;DEF;SG
brenne	brant	V;PST
upopulær	upopulære	ADJ;DEF;SG+PL
teller	tellerne	N;DEF;PL
obo	oboer	N;NDEF;PL
misteltein	mistelteiner	N;NDEF;PL
pulverisere	pulveriserende	V.PTCP;PRS
systematisk	systematisk	ADJ;NEUT;SG
selvmord	selvmordene	N;DEF;PL
brukergrensesnitt	brukergrensesnittene	N;DEF;PL
fjernkontroll	fjernkontroller	N;NDEF;PL
snegl	snegler	N;NDEF;PL
snøvær	snøværet	N;DEF
teater	teater	N;NDEF;PL
røveri	røveri	N;NDEF;PL
vannseng	vannsengen	N;DEF;SG
fokusere	fokusert	V.PTCP;PST
hank	hanka	N;DEF;SG
mester	mesteren	N;DEF;SG
omdirigere	omdirigert	V.PTCP;PST
male	malt	V.PTCP;PST
USA-amerikaner	USA-amerikaneren	N;DEF;SG
keiser	keisere	N;NDEF;PL
etterligne	etterlign	V;IMP
roman	romanene	N;DEF;PL
mordvåpen	mordvåpen	N;NDEF;PL
hele	helet	V;PST
banan	bananer	N;NDEF;PL
bumerang	bumeranger	N;NDEF;PL
danske	dansken	N;DEF;SG
reprodusere	reproduserer	V;PRS
eksosrør	eksosrøret	N;DEF;SG
overbefolkning	overbefolkningen	N;DEF;SG
renslig	renslige	ADJ;DEF;SG+PL
debatt	debatter	N;NDEF;PL
kommersiell	kommersielt	ADJ;NEUT;SG
røveri	røveriene	N;DEF;PL
triumf	triumfer	N;NDEF;PL
felt	felta	N;DEF;PL
nigerianer	nigerianere	N;NDEF;PL
dong	dongene	N;DEF;PL
teller	telleren	N;DEF;SG
smil	smil	N;NDEF;PL
slaveri	slaveriet	N;DEF;SG
endring	endringen	N;DEF;SG
stadion	stadion	N;NDEF;PL
skate	skaten	N;DEF;SG
referanse	referanser	N;NDEF;PL
lekeplass	lekeplassene	N;DEF;PL
sand	sanden	N;DEF;SG
kalkstein	kalksteiner	N;NDEF;PL
ekskone	ekskonene	N;DEF;PL
uforandret	uforandret	ADJ;NEUT;SG
fobi	fobier	N;NDEF;PL
ensemble	ensemblene	N;DEF;PL
tusj	tusjer	N;NDEF;PL
bulldoser	bulldoseren	N;DEF;SG
værelse	værelsene	N;DEF;PL
kambodsjansk	kambodsjanske	ADJ;DEF;SG+PL
historie	historia	N;DEF;SG
temme	temmende	V.PTCP;PRS
leirdue	leirdua	N;DEF;SG
sylinder	sylindere	N;NDEF;PL
skarp	skarpe	ADJ;DEF;SG+PL
hvalp	hvalpene	N;DEF;PL
spent	spente	ADJ;DEF;SG+PL
avrunde	avrund	V;IMP
bit	biter	N;NDEF;PL
None	stås	V;PRS;PASS
traktor	traktoren	N;DEF;SG
fargestoff	fargestoffene	N;DEF;PL
sink	sinket	N;DEF;SG
langrenn	langrennene	N;DEF;PL
ampulle	ampullene	N;DEF;PL
sogn	sognet	N;DEF;SG
trekantet	trekantete	ADJ;DEF;SG+PL
ambassadør	ambassadøren	N;DEF;SG
svastika	svastikaen	N;DEF;SG
bikkje	bikkjen	N;DEF;SG
beherske	behersker	V;PRS
bursdagskake	bursdagskakene	N;DEF;PL
befolkning	befolkningen	N;DEF;SG
ekvilibrium	ekvilibriumet	N;DEF;SG
rokke	rokken	N;DEF;SG
drage	dragene	N;DEF;PL
anestesi	anestesier	N;NDEF;PL
appelsintre	appelsintrærne	N;DEF;PL
skinn	skinnene	N;DEF;PL
dugnad	dugnadene	N;DEF;PL
bordell	bordell	N;NDEF;PL
boble	bobler	V;PRS
likevekt	likevekter	N;NDEF;PL
benytte	benytta	V;PST
ideologi	ideologien	N;DEF;SG
tilby	tilbyr	V;PRS
objekt	objekta	N;DEF;PL
legering	legeringen	N;DEF;SG
fødselsdag	fødselsdagen	N;DEF;SG
ekko	ekkoene	N;DEF;PL
lommebok	lommeboka	N;DEF;SG
fyrstedømme	fyrstedømmene	N;DEF;PL
flyplass	flyplasser	N;NDEF;PL
mening	meningen	N;DEF;SG
metafor	metaforen	N;DEF;SG
uinteressant	uinteressant	ADJ;NEUT;SG
motorkjøretøy	motorkjøretøyer	N;NDEF;PL
biolog	biologene	N;DEF;PL
blokk	blokkene	N;DEF;PL
T-bane	T-banene	N;DEF;PL
dreiebenk	dreiebenken	N;DEF;SG
ljå	ljåene	N;DEF;PL
råd	rådene	N;DEF;PL
knapphull	knapphuller	N;NDEF;PL
tann	tanna	N;DEF;SG
tannbørste	tannbørster	N;NDEF;PL
åre	årene	N;DEF;PL
kastanje	kastanjen	N;DEF;SG
katolsk	katolske	ADJ;DEF;SG+PL
høgskole	høgskolen	N;DEF;SG
boggi	boggier	N;NDEF;PL
sammensetning	sammensetninger	N;NDEF;PL
møller	møllere	N;NDEF;PL
blanding	blandingen	N;DEF;SG
undervurdere	undervurdert	V.PTCP;PST
spørsmålstegn	spørsmålstegna	N;DEF;PL
kambodsjaner	kambodsjanere	N;NDEF;PL
ost	oster	N;NDEF;PL
by	bydde	V;PST
fabrikant	fabrikantene	N;DEF;PL
orkan	orkaner	N;NDEF;PL
krypdyr	krypdyret	N;DEF;SG
sikring	sikringen	N;DEF;SG
sonde	sonder	N;NDEF;PL
reagensrør	reagensrør	N;NDEF;PL
hue	hua	N;DEF;PL
pass	passene	N;DEF;PL
blomsterbed	blomsterbed	N;NDEF;PL
massør	massører	N;NDEF;PL
emalje	emaljer	N;NDEF;PL
omklassifisere	omklassifiser	V;IMP
russer	russerne	N;DEF;PL
inspirere	inspirerer	V;PRS
massasje	massasjene	N;DEF;PL
dominikaner	dominikaneren	N;DEF;SG
vendbar	vendbare	ADJ;DEF;SG+PL
størrelse	størrelsen	N;DEF;SG
utstille	utstilt	V.PTCP;PST
flaggermus	flaggermusen	N;DEF;SG
kjerne	kjernen	N;DEF;SG
syre	syren	N;DEF;SG
gave	gavene	N;DEF;PL
henrette	henrettet	V;PST
vis	vise	ADJ;DEF;SG+PL
sykkelsete	sykkelsetene	N;DEF;PL
relativitet	relativiteten	N;DEF;SG
vakt	vakten	N;DEF;SG
programmering	programmeringer	N;NDEF;PL
fjernkontroll	fjernkontrollen	N;DEF;SG
kassett	kassettene	N;DEF;PL
kjøkkenbenk	kjøkkenbenkene	N;DEF;PL
skinne	skint	V.PTCP;PST
hue	huen	N;DEF;SG
kalkstein	kalksteinene	N;DEF;PL
kirkegjenger	kirkegjengere	N;NDEF;PL
turnering	turneringa	N;DEF;SG
skikkelig	skikkelig	ADJ;NEUT;SG
spontanabort	spontanaborter	N;NDEF;PL
boksåpner	boksåpnerne	N;DEF;PL
voks	vokset	N;DEF;SG
krakk	krakkene	N;DEF;PL
fødselsdato	fødselsdatoene	N;DEF;PL
løype	løypen	N;DEF;SG
belte	beltene	N;DEF;PL
bjørkefink	bjørkefinkene	N;DEF;PL
paraguayaner	paraguayanerne	N;DEF;PL
diagnose	diagnosene	N;DEF;PL
