हृदय	हृदयेन	ADJ;INS;MASC;SG
प्रतीक	प्रतीकम्	ADJ;ACC;MASC;SG
प्राच्य	प्राच्ये	ADJ;NOM;NEUT;DU
रुधिर	रुधिरा	ADJ;DAT;NEUT;SG
कथा	कथे	N;ACC;DU
अङ्गना	अङ्गनायाः	N;ABL;SG
अङ्गुलि	अङ्गुल्योः	N;LOC;DU
प्रतीक	प्रतीके	ADJ;LOC;MASC;SG
कृमि	कृमेः	N;ABL;SG
विद्या	विद्याः	N;VOC;PL
वैवाहिक	वैवाहिक्या	ADJ;INS;FEM;SG
स्वप्न	स्वप्नः	N;NOM;SG
जुगुप्सु	जुगुप्सुनः	ADJ;ABL;NEUT;SG
युद्ध	युद्ध	ADJ;VOC;NEUT;SG
सरस्वती	सरस्वत्यौ	N;VOC;DU
मन्दर	मन्दरा	ADJ;NOM;FEM;SG
मन्दर	मन्दराम्	ADJ;ACC;FEM;SG
पृष्ठ	पृष्ठानि	N;VOC;PL
द्वादशाह	द्वादशाहानि	ADJ;VOC;NEUT;PL
कर्मन्	कर्म्णः	N;ABL;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसायै	ADJ;DAT;FEM;SG
सर्व	सर्वानि	ADJ;ACC;NEUT;PL
सकर्मक	सकर्मक	ADJ;VOC;MASC;SG
जम्भ	जम्भयोः	N;LOC;DU
अजाति	अजात्याः	N;ABL;SG
स्वप्न	स्वप्नेषु	N;LOC;PL
अकर्मक	अकर्मकाणि	ADJ;NOM;NEUT;PL
सकर्मक	सकर्मकाभिः	ADJ;INS;FEM;PL
लोह	लोहे	ADJ;LOC;MASC;SG
छाया	छाये	N;VOC;DU
प्रतीक	प्रतीकान्	ADJ;ACC;MASC;PL
तडाग	तडागस्य	N;GEN;SG
खिलकाण्ड	खिलकाण्डे	N;ACC;DU
चीन	चीनः	N;NOM;SG
सुवर्ण	सुवर्णाभ्याम्	ADJ;ABL;MASC;DU
ब्रह्मविद्या	ब्रह्मविद्यासु	N;LOC;PL
जुष्ट	जुष्टानाम्	ADJ;GEN;NEUT;PL
सुम्न	सुम्नयोः	ADJ;GEN;NEUT;DU
अग्निहोत्र	अग्निहोत्रे	ADJ;VOC;FEM;SG
पार्ष्णि	पार्ष्णौ	N;LOC;SG
ब्रह्मोद्य	ब्रह्मोद्याभ्याम्	ADJ;ABL;NEUT;DU
तित्तिर	तित्तिराः	N;NOM;PL
पर्वसंग्रह	पर्वसंग्रहेन	N;INS;SG
काम्बोज	काम्बोजैः	N;INS;PL
सखि	सखीनाम्	N;GEN;PL
तनूज	तनूजे	ADJ;VOC;FEM;SG
गुरु	गुरोः	N;GEN;SG
जनन	जननयोः	N;GEN;DU
व्याकरण	व्याकरणाभ्याम्	N;ABL;DU
पारग	पारगे	ADJ;ACC;NEUT;DU
नक्त	नक्तयोः	N;LOC;DU
हृदय	हृदयानाम्	ADJ;GEN;FEM;PL
सिद्धार्थ	सिद्धार्थाम्	ADJ;ACC;FEM;SG
अकूपार	अकूपारे	ADJ;ACC;NEUT;DU
नलद	नलदाभ्याम्	ADJ;ABL;FEM;DU
ब्राह्मण	ब्राह्मणायाः	ADJ;GEN;FEM;SG
अन्ताराष्ट्रिय	अन्ताराष्ट्रिय	ADJ;VOC;MASC;SG
कृपाण	कृपाणौ	N;ACC;DU
अङ्गुली	अङ्गुल्याः	N;GEN;SG
गोपुर	गोपुरम्	N;NOM;SG
गिरि	गिरयः	N;NOM;PL
कल्ल	कल्लम्	ADJ;NOM;NEUT;SG
फेन	फेनेषु	N;LOC;PL
उदन्या	उदन्यायाः	N;GEN;SG
सिद्धार्थ	सिद्धार्थाभिः	ADJ;INS;FEM;PL
चक्रवाक	चक्रवाकयोः	N;GEN;DU
सुम्न	सुम्ने	ADJ;ACC;FEM;DU
ऋण	ऋणौ	ADJ;VOC;MASC;DU
व्यञ्जन	व्यञ्जनस्य	ADJ;GEN;NEUT;SG
पलित	पलिक्नीभ्याम्	N;ABL;DU
विधवा	विधवाभिः	N;INS;PL
राशिचक्र	राशिचक्राभ्याम्	N;ABL;DU
तित्तिरि	तित्तिर्याः	N;ABL;SG
अनस्	अनः	N;NOM;SG
वैवाहिक	वैवाहिक्यः	ADJ;NOM;FEM;PL
प्रपाठक	प्रपाठकयोः	N;LOC;DU
आशु	आशुभ्याम्	ADJ;ABL;MASC;DU
यवनिका	यवनिके	N;ACC;DU
आथर्वण	आथर्वण्यः	ADJ;NOM;FEM;PL
अकूपार	अकूपारे	ADJ;LOC;MASC;SG
अक्षरा	अक्षरे	N;VOC;DU
निष्क	निष्कान्	N;ACC;PL
सवन	सवनाः	ADJ;NOM;PL
राजि	राजिभ्याम्	N;ABL;DU
शारद	शारदयोः	ADJ;GEN;NEUT;DU
तरु	तरोः	ADJ;GEN;SG
आप्त्य	आप्त्यैः	ADJ;INS;NEUT;PL
अथर्वाङ्गिरस	अथर्वाङ्गिरसाभ्यः	ADJ;DAT;FEM;PL
दारु	दारूणाम्	N;GEN;PL
रोच	रोचाभ्याम्	ADJ;DAT;DU
बालातप	बालातपाभ्याम्	N;DAT;DU
नवोदित	नवोदितस्य	ADJ;GEN;MASC;SG
प्रतीक	प्रतीकानि	ADJ;ACC;NEUT;PL
तरु	तरू	ADJ;NOM;DU
मह	महायै	ADJ;DAT;FEM;SG
तटाक	तटाकानाम्	N;GEN;PL
पर्वत	पर्वताभ्याम्	N;ABL;DU
पुण्डरीक	पुण्डरीके	N;VOC;DU
हिम	हिमेभ्यः	ADJ;ABL;NEUT;PL
वसुधा	वसुधानाम्	N;GEN;PL
तुच्छ	तुच्छे	ADJ;LOC;NEUT;SG
सर्म	सर्मः	N;NOM;SG
आशु	आशुना	ADJ;INS;MASC;SG
प्रान्त	प्रान्ताः	ADJ;NOM;MASC;PL
साधु	साधुषु	ADJ;LOC;NEUT;PL
आथर्वण	आथर्वणौ	ADJ;VOC;MASC;DU
चन्दन	चन्दनम्	N;ACC;SG
बाधा	बाधासु	N;LOC;PL
वसु	वस्वीभ्याम्	ADJ;ABL;DU
उदन्या	उदन्याभ्याम्	N;INS;DU
पुर	पुरम्	ADJ;ACC;NEUT;SG
मन्दार	मन्दाराभ्याम्	N;DAT;DU
नारी	नारीः	N;ACC;PL
नवोदय	नवोदयम्	ADJ;NOM;NEUT;SG
मधुर	मधुरा	ADJ;DAT;NEUT;SG
रुधिर	रुधिरेभ्यः	ADJ;ABL;MASC;PL
वली	वलीभ्यः	N;ABL;PL
सपिण्ड	सपिण्डाभ्याम्	N;ABL;DU
जङ्गल	जङ्गलाय	ADJ;DAT;MASC;SG
लघु	लघोः	ADJ;ABL;SG
वसति	वसती	ADJ;NOM;FEM;DU
मद	मदस्य	N;GEN;SG
कर्मकाण्ड	कर्मकाण्डेभ्यः	N;DAT;PL
पृथु	प्र्थ्व्याः	ADJ;GEN;SG
नेपथ्य	नेपथ्याः	N;NOM;PL
अकन्या	अकन्याः	N;ACC;PL
शत्रु	शत्रुणा	N;INS;SG
सकर्मक	सकर्मकान्	ADJ;ACC;MASC;PL
अकूपार	अकूपारयोः	ADJ;LOC;FEM;DU
काव्य	काव्यः	ADJ;NOM;MASC;SG
महाभारत	महाभारतानि	N;ACC;PL
विधान	विधानाभ्याम्	ADJ;ABL;NEUT;DU
उत्सव	उत्सवौ	N;NOM;DU
गृह	गृहे	N;VOC;DU
दण्ड	दण्डानाम्	N;GEN;PL
खिल	खिलम्	ADJ;ACC;FEM;SG
चातुर्मास्य	चातुर्मास्ययोः	ADJ;LOC;NEUT;DU
सवन	सवानि	N;VOC;PL
साधार	साधारात्	ADJ;ABL;NEUT;SG
क्षेत्र	क्षेत्रेषु	N;LOC;PL
अङ्ग	अङ्गौ	N;ACC;DU
भोजन	भोजनाभ्याम्	ADJ;ABL;NEUT;DU
ह्रस्व	ह्रस्वे	ADJ;NOM;NEUT;DU
मुण्ड	मुण्डे	ADJ;NOM;FEM;DU
अश्व	अश्व	N;VOC;SG
सह	सहात्	ADJ;ABL;NEUT;SG
लोह	लोहायाम्	ADJ;LOC;FEM;SG
हेलि	हेली	N;NOM;DU
प्रसिद्धि	प्रसिद्ध्योः	N;LOC;DU
पार्वती	पार्वत्यौ	N;VOC;DU
कृपाण	कृपाणान्	N;ACC;PL
अक्ष	अक्षैः	N;INS;PL
साहाय्य	साहाय्यानि	N;VOC;PL
अकूपार	अकूपारा	ADJ;NOM;FEM;SG
मार्जार	मार्जारौ	N;NOM;DU
पुष्कर	पुष्करे	N;NOM;DU
आशु	आशुभिः	ADJ;INS;MASC;PL
व्यञ्जन	व्यञ्जनाभ्याम्	ADJ;ABL;NEUT;DU
नक्ति	नक्ती	N;VOC;DU
अंह्रि	अंह्रयः	N;VOC;PL
अनुवाक	अनुवाकः	N;NOM;SG
नृप	नृपस्य	N;GEN;SG
प्रतीक	प्रतीकयोः	ADJ;GEN;MASC;DU
भोजन	भोजन्यौ	ADJ;ACC;FEM;DU
वचन	वचनेभ्यः	ADJ;ABL;NEUT;PL
रुद्राक्ष	रुद्राक्षे	N;LOC;SG
नीति	नीतिभ्याम्	N;DAT;DU
मह	महानि	ADJ;VOC;NEUT;PL
पृथु	पृथुभ्यः	ADJ;DAT;PL
प्रधान	प्रधानाभ्याम्	ADJ;DAT;FEM;DU
अक्षरा	अक्षराम्	N;ACC;SG
आप्त्य	आप्त्यौ	ADJ;VOC;MASC;DU
आप्त्य	आप्त्यान्	ADJ;ACC;MASC;PL
धूम	धूमाः	N;VOC;PL
वैश्वानर	वैश्वानराभ्याम्	ADJ;DAT;NEUT;DU
वसति	वसते	ADJ;VOC;MASC;SG
राशि	राशौ	N;LOC;SG
पति	पती	N;ACC;DU
कुटुम्बक	कुटुम्बकानि	N;ACC;PL
प्रतिष्ठा	प्रतिष्ठयोः	N;GEN;DU
मनुष्य	मनुष्यायाः	ADJ;GEN;FEM;SG
यजमान	यजमाने	ADJ;NOM;NEUT;DU
हिम	हिमम्	ADJ;ACC;NEUT;SG
ग्रीवा	ग्रीवायै	N;DAT;SG
कुक्षि	कुक्षिभ्याम्	N;INS;DU
यजमान	यजमानयोः	ADJ;LOC;NEUT;DU
ह्रस्व	ह्रस्वाः	ADJ;NOM;MASC;PL
अबुध्न	अबुध्नाः	ADJ;NOM;FEM;PL
आहार	आहारौ	ADJ;NOM;MASC;DU
शत्रु	शत्रवः	N;VOC;PL
पार्ष्णि	पार्ष्णिः	N;NOM;SG
सकर्मक	सकर्मकम्	ADJ;ACC;MASC;SG
कर्कट	कर्कटानाम्	N;GEN;PL
साहाय्य	साहाय्याभ्याम्	N;INS;DU
अकृता	अकृताभ्यः	N;ABL;PL
प्रसन्न	प्रसन्नाः	N;VOC;PL
अदृष्ट	अदृष्टाभिः	ADJ;INS;FEM;PL
सत्य	सत्यस्य	N;GEN;SG
जुष्ट	जुष्टाभ्याम्	ADJ;ABL;FEM;DU
लघु	लघुनोः	N;LOC;DU
अक्का	अक्के	N;VOC;SG
अपस्मार	अपस्मारस्य	N;GEN;SG
सुराकार	सुराकारस्य	N;GEN;SG
स्वतन्त्र	स्वतन्त्राभ्याम्	ADJ;INS;NEUT;DU
प्रतिज्ञा	प्रतिज्ञे	N;ACC;DU
दीर्घ	दीर्घाभ्याम्	ADJ;DAT;NEUT;DU
सह	सहाभ्याम्	ADJ;ABL;MASC;DU
कल्ल	कल्लाभ्याम्	ADJ;DAT;MASC;DU
तायु	तायुना	N;INS;SG
क्षिति	क्षित्याः	N;ABL;SG
प्रान्त	प्रान्ते	ADJ;LOC;MASC;SG
मेध	मेधौ	N;NOM;DU
शश	शश	N;VOC;SG
पुष्कर	पुष्करे	N;ACC;DU
सूकर	सूकराणाम्	N;GEN;PL
वसति	वसतिनोः	ADJ;LOC;NEUT;DU
कुशीलव	कुशीलवान्	N;ACC;PL
मृत	मृताः	ADJ;NOM;MASC;PL
चक्रवाल	चक्रवालात्	N;ABL;SG
क्षौरी	क्षौरि	N;VOC;SG
अग्निष्टोम	अग्निष्टोमः	N;NOM;SG
चक्रवाल	चक्रवालयोः	N;GEN;DU
अस्थि	अस्थिभ्यः	N;ABL;PL
बिडाली	बिडाल्याः	N;GEN;SG
चन्द्र	चन्द्रौ	ADJ;NOM;MASC;DU
राम	रामाणाम्	ADJ;GEN;MASC;PL
नवोदय	नवोदयेषु	ADJ;LOC;NEUT;PL
जम्भ	जम्भौ	N;ACC;DU
विभक्ति	विभक्तीनाम्	N;GEN;PL
पुष्प	पुष्पाणि	N;VOC;PL
खिलकाण्ड	खिलकाण्डाभ्याम्	N;INS;DU
दर्पण	दर्पणे	N;LOC;SG
वैतान	वैतानम्	ADJ;ACC;NEUT;SG
नृप	नृपाभ्याम्	N;ABL;DU
घृण	घृणे	N;LOC;SG
अहर्गण	अहर्गणम्	N;ACC;SG
तन्वी	तन्वी	N;NOM;SG
मूषक	मूषकस्य	N;GEN;SG
छुरी	छुरीभ्यः	N;DAT;PL
तृष्णा	तृष्णा	N;NOM;SG
तरु	तरौ	N;LOC;SG
तद्धित	तद्धिते	N;VOC;DU
काव्य	काव्यायाः	ADJ;ABL;FEM;SG
श्वसुर	श्वसुरेभ्यः	N;DAT;PL
नक्ति	नक्तीनाम्	N;GEN;PL
भोजन	भोजनैः	ADJ;INS;MASC;PL
जुष्ट	जुष्टम्	ADJ;ACC;MASC;SG
वैश्य	वैश्याभ्याम्	ADJ;DAT;MASC;DU
शिव	शिवाभ्याम्	ADJ;ABL;MASC;DU
जुगुप्सु	जुगुप्सू	ADJ;NOM;MASC;DU
अग्निष्टोम	अग्निष्टोमाः	N;VOC;PL
लिङ्गशरीर	लिङ्गशरीरयोः	N;GEN;DU
साधु	साध्व्यौ	ADJ;VOC;FEM;DU
जुगुप्सु	जुगुप्सोः	ADJ;GEN;MASC;SG
स्वतन्त्र	स्वतन्त्रयोः	ADJ;LOC;FEM;DU
सृगाल	सृगालाभ्याम्	N;DAT;DU
प्रसन्न	प्रसन्नेभ्यः	N;DAT;PL
दीर्घ	दीर्घाभिः	ADJ;INS;FEM;PL
अक्ष	अक्षाः	N;VOC;PL
मास	मासेन	N;INS;SG
मन्दर	मन्दरस्य	ADJ;GEN;NEUT;SG
सहस्र	सहस्रा	ADJ;DAT;MASC;SG
ब्राह्मण	ब्राह्मणाभ्याम्	ADJ;DAT;MASC;DU
मृग	मृगौ	N;NOM;DU
तद्धित	तद्धिताभ्याम्	N;DAT;DU
तन्तु	तन्त्वोः	N;LOC;DU
शारद	शारदयोः	ADJ;GEN;MASC;DU
श्वसुर	श्वसुरान्	N;ACC;PL
शिव	शिवयोः	ADJ;LOC;FEM;DU
चीन	चीनेभ्यः	N;ABL;PL
रोटी	रोटीम्	N;ACC;SG
स्वतन्त्र	स्वतन्त्राः	ADJ;NOM;MASC;PL
विदूषक	विदूषकाभ्याम्	ADJ;ABL;FEM;DU
सवन	सवनायाः	ADJ;GEN;SG
ग्रीवा	ग्रीवयोः	N;LOC;DU
धर्म	धर्मान्	N;ACC;PL
लोह	लोहैः	ADJ;INS;NEUT;PL
विभाग	विभागे	N;LOC;SG
आलु	आलुभिः	N;INS;PL
अपस्मार	अपस्मारेभ्यः	N;DAT;PL
ऊर्णा	ऊर्णाभ्याम्	N;INS;DU
स्तन	स्तनयोः	N;GEN;DU
मित्र	मित्रौ	N;ACC;DU
शून्य	शून्यानि	N;ACC;PL
रुद्राक्ष	रुद्राक्षाभ्याम्	N;ABL;DU
राग	रागाः	N;NOM;PL
अङ्गना	अङ्गने	N;VOC;DU
मेघ	मेघेषु	N;LOC;PL
विद्या	विद्यायै	N;DAT;SG
अगस्ति	अगस्तिभ्याम्	N;INS;DU
विधान	विधान्योः	ADJ;LOC;FEM;DU
वज्र	वज्राणि	ADJ;ACC;FEM;PL
नाश	नाशाभ्याम्	N;DAT;DU
अदृष्ट	अदृष्टानाम्	ADJ;GEN;NEUT;PL
रात्रि	रात्रिभ्याम्	N;INS;DU
विद्या	विद्याभिः	N;INS;PL
वज्र	वज्रैः	ADJ;INS;MASC;PL
राम	रामौ	ADJ;ACC;MASC;DU
स्वप्न	स्वप्ने	N;LOC;SG
मान	मानौ	N;VOC;DU
सह	सहाभिः	ADJ;INS;FEM;PL
गर्जन	गर्जनेषु	N;LOC;PL
दुन्दुभि	दुन्दुभियः	N;NOM;PL
व्यञ्जन	व्यञ्जनेन	ADJ;INS;MASC;SG
साध्य	साध्येभ्यः	ADJ;DAT;NEUT;PL
वराह	वराहाभ्याम्	N;INS;DU
दृष्टि	दृष्ट्योः	N;GEN;DU
वैवाहिक	वैवाहिक्याः	ADJ;ABL;FEM;SG
उत्सव	उत्सवौ	N;ACC;DU
सवन	सवाभ्याम्	N;ABL;DU
तृष्णा	तृष्णायाः	N;GEN;SG
जुगुप्सु	जुगुप्सुनी	ADJ;ACC;NEUT;DU
शारद	शारदेषु	ADJ;LOC;NEUT;PL
प्रान्त	प्रान्तयोः	ADJ;GEN;MASC;DU
भक्ति	भक्तिभिः	N;INS;PL
ईर्म	ईर्मम्	N;ACC;SG
हति	हत्योः	N;LOC;DU
जुगुप्सु	जुगुप्सो	ADJ;VOC;FEM;SG
अभिनय	अभिनयेण	N;INS;SG
वैश्वानर	वैश्वानरम्	ADJ;NOM;NEUT;SG
तद्धित	तद्धितात्	N;ABL;SG
वैवाहिक	वैवाहिकाभ्याम्	ADJ;ABL;MASC;DU
ह्रस्व	ह्रस्वयोः	ADJ;LOC;NEUT;DU
ऋण	ऋणाभ्याम्	ADJ;INS;NEUT;DU
प्रपाठक	प्रपाठकाः	N;VOC;PL
प्रतिष्ठा	प्रतिष्ठाभ्याम्	N;INS;DU
स्तन	स्तनाभ्याम्	N;DAT;DU
अग्निहोत्र	अग्निहोत्राभिः	ADJ;INS;FEM;PL
द्वादशाह	द्वादशाहाभ्याम्	ADJ;ABL;FEM;DU
ब्रह्मोद्य	ब्रह्मोद्यात्	ADJ;ABL;NEUT;SG
ऋण	ऋणस्य	ADJ;GEN;MASC;SG
काव्य	काव्यौ	ADJ;NOM;MASC;DU
भट्ट	भट्टाः	ADJ;VOC;MASC;PL
अंशक	अंशिकयोः	ADJ;LOC;FEM;DU
अपस्मार	अपस्मारौ	N;VOC;DU
दर्पण	दर्पणाभ्याम्	N;INS;DU
अहर्गण	अहर्गणेषु	N;LOC;PL
नवोदित	नवोदितम्	ADJ;NOM;NEUT;SG
पिप्पलि	पिप्पलिभ्याम्	N;ABL;DU
वसति	वसतौ	ADJ;LOC;MASC;SG
ब्राह्मण	ब्राह्मणाभ्याम्	ADJ;INS;FEM;DU
औषध	औषधाभ्याम्	N;DAT;DU
जम्भ	जम्भस्य	N;GEN;SG
पाल	पाले	N;VOC;DU
शाखा	शाखाः	N;VOC;PL
मिथुन	मिथुने	ADJ;LOC;MASC;SG
पुरी	पुरीभिः	N;INS;PL
केतक	केतकौ	N;ACC;DU
सर्व	सर्वाभ्याम्	ADJ;ABL;FEM;DU
वैश्य	वैश्याभ्याम्	ADJ;DAT;NEUT;DU
छल्ली	छल्ल्यौ	N;NOM;DU
वैवाहिक	वैवाहिकाय	ADJ;DAT;MASC;SG
मुण्ड	मुण्डौ	ADJ;VOC;MASC;DU
मेघ	मेघान्	N;ACC;PL
वैबोधिक	वैबोधिकानाम्	N;GEN;PL
आप्त्य	आप्त्यानाम्	ADJ;GEN;NEUT;PL
कर्कट	कर्कटाभ्याम्	N;ABL;DU
पूर्णिमा	पूर्णिमाः	N;VOC;PL
विदूषक	विदूषके	ADJ;ACC;FEM;DU
काम	कामयोः	N;LOC;DU
दिन	दिनानाम्	N;GEN;PL
साति	सत्यै	N;DAT;SG
कृमि	कृमीः	N;ACC;PL
काव्य	काव्ये	ADJ;VOC;FEM;SG
काम्बोज	काम्बोजाभ्याम्	N;ABL;DU
वैवाहिक	वैवाहिकीभ्याम्	ADJ;INS;FEM;DU
भूतयज्ञ	भूतयज्ञाभ्याम्	N;ABL;DU
ब्रह्मोद्य	ब्रह्मोद्यायै	ADJ;DAT;FEM;SG
प्रतिष्ठा	प्रतिष्ठया	N;INS;SG
हिम	हिमाभ्यः	ADJ;DAT;FEM;PL
व्याकरण	व्याकरणम्	N;ACC;SG
पृथु	पृथुम्	ADJ;ACC;SG
श्वश्रू	श्वश्रूभ्यः	N;ABL;PL
छाया	छाये	N;VOC;SG
पोत	पोतौ	N;NOM;DU
पृष्ठ	पृष्ठेन	N;INS;SG
संसार	संसारः	N;NOM;SG
आथर्वण	आथर्वणेन	ADJ;INS;NEUT;SG
अर्भ	अर्भे	ADJ;NOM;FEM;DU
वैश्य	वैश्यानि	ADJ;NOM;NEUT;PL
ध्यान	ध्यानानि	N;ACC;PL
अरण्य	अरण्यम्	N;NOM;SG
अर्भ	अर्भाभ्यः	ADJ;ABL;FEM;PL
वसुधा	वसुधायाः	N;GEN;SG
आशु	आशुभिः	ADJ;INS;FEM;PL
राशिचक्र	राशिचक्रैः	N;INS;PL
पस्त्य	पस्त्यानाम्	N;GEN;PL
उदन्या	उदन्यायाम्	N;LOC;SG
द्वादशाह	द्वादशाहे	ADJ;NOM;NEUT;DU
ब्राह्मण	ब्राह्मणाणाम्	ADJ;GEN;FEM;PL
नवोदय	नवोदयैः	ADJ;INS;MASC;PL
मेध	मेधयोः	N;LOC;DU
स्मृति	स्मृतिम्	N;ACC;SG
अन्ताराष्ट्रिय	अन्ताराष्ट्रियाम्	ADJ;ACC;FEM;SG
ईर्म	ईर्मात्	N;ABL;SG
अगुरु	अगुरु	N;ACC;SG
तरंग	तरंगाय	N;DAT;SG
भूतयज्ञ	भूतयज्ञेषु	N;LOC;PL
घृणा	घृणे	N;VOC;SG
नृप	नृपयोः	N;LOC;DU
जुगुप्सु	जुगुप्सवः	ADJ;VOC;FEM;PL
महाकवि	महाकविः	N;NOM;SG
मन्दर	मन्दराभ्याम्	ADJ;DAT;FEM;DU
ग्रह	ग्रहैः	N;INS;PL
असुर	असुरेभ्यः	N;ABL;PL
तरु	तरुनी	ADJ;ACC;DU
विशेष	विशेषेषु	ADJ;LOC;MASC;PL
अर्भ	अर्भायै	ADJ;DAT;FEM;SG
वैतान	वैतानाभ्याम्	ADJ;DAT;MASC;DU
वैबोधिक	वैबोधिकाभ्याम्	N;ABL;DU
वज्र	वज्रे	ADJ;NOM;FEM;DU
व्रीहि	व्रीहिभिः	N;INS;PL
नर	नरः	N;NOM;SG
अभिनय	अभिनयाः	N;VOC;PL
प्राच्य	प्राच्येषु	ADJ;LOC;NEUT;PL
अकूपार	अकूपाराय	ADJ;DAT;MASC;SG
सर्प	सर्प्यः	ADJ;NOM;FEM;PL
नृप	नृपेभ्यः	N;DAT;PL
गति	गतीनाम्	N;GEN;PL
उत्तमपुरुष	उत्तमपुरुषाय	N;DAT;SG
धर्म	धर्मौ	N;VOC;DU
भोजन	भोजनीषु	ADJ;LOC;FEM;PL
नेपथ्य	नेपथ्यान्	N;ACC;PL
ब्राह्म	ब्राह्माणि	ADJ;NOM;NEUT;PL
नाटिका	नाटिकयोः	N;LOC;DU
चन्द्र	चन्द्रस्य	ADJ;GEN;MASC;SG
अंस	अंसौ	N;VOC;DU
तन्वी	तन्व्योः	N;GEN;DU
रुचि	रुचीनाम्	N;GEN;PL
आस्य	आस्येभ्यः	N;DAT;PL
भट्ट	भट्टाः	ADJ;NOM;MASC;PL
चुम्बन	चुम्बनस्य	N;GEN;SG
साध्य	साध्ययोः	ADJ;LOC;NEUT;DU
तडाग	तडागानाम्	N;GEN;PL
अर्थ	अर्थानाम्	N;GEN;PL
ग्रीवा	ग्रीवाभ्यः	N;ABL;PL
प्रस्ताव	प्रस्तावेभ्यः	N;ABL;PL
दुन्दुभि	दुन्दुभिीनाम्	N;GEN;PL
देवयान	देवयानायै	ADJ;DAT;FEM;SG
चन्द्र	चन्द्राणि	ADJ;VOC;NEUT;PL
रोच	रोचानि	ADJ;ACC;PL
लघु	लघू	ADJ;VOC;DU
एकोद्दिष्ट	एकोद्दिष्टानि	N;ACC;PL
शिश्न	शिश्ने	N;LOC;SG
अकर्मक	अकर्मकाः	ADJ;NOM;MASC;PL
साध्य	साध्यम्	ADJ;NOM;NEUT;SG
मनुष्य	मनुष्ये	ADJ;ACC;FEM;DU
गुरु	गुरू	N;NOM;DU
साधार	साधारयोः	ADJ;GEN;NEUT;DU
कवि	कवी	ADJ;ACC;MASC;DU
अश्व	अश्वात्	N;ABL;SG
शङ्ख	शङ्खेन	N;INS;SG
यान	यानयोः	N;GEN;DU
उत्तमपुरुष	उत्तमपुरुषाभ्याम्	N;DAT;DU
श्रम	श्रमौ	N;ACC;DU
दीर्घ	दीर्घाः	ADJ;NOM;MASC;PL
बालातप	बालातपेन	N;INS;SG
आशु	आशुः	ADJ;NOM;FEM;SG
वाद	वादाभ्याम्	ADJ;DAT;FEM;DU
एकोद्दिष्ट	एकोद्दिष्टेभ्यः	N;ABL;PL
खिल	खिलेन	ADJ;INS;FEM;SG
चरण	चरणौ	N;NOM;DU
चन्द्र	चन्द्राम्	ADJ;ACC;FEM;SG
तद्	तेषु	N;LOC;PL
दन्त	दन्तौ	N;NOM;DU
दन्त	दन्तेषु	N;LOC;PL
उद्गातृ	उद्गातृभ्याम्	N;INS;DU
वृषभ	वृषभ	ADJ;VOC;MASC;SG
वैश्य	वैश्येन	ADJ;INS;MASC;SG
कल्ल	कल्लैः	ADJ;INS;MASC;PL
बिडाली	बिडालीम्	N;ACC;SG
घोर	घोरया	ADJ;INS;FEM;SG
चक्रवाल	चक्रवालौ	N;VOC;DU
अग्निष्टोम	अग्निष्टोमेन	N;INS;SG
मृग	मृगम्	N;ACC;SG
मुण्ड	मुण्डौ	ADJ;NOM;MASC;DU
स्वयंवर	स्वयंवराभ्याम्	ADJ;ABL;MASC;DU
ब्रह्मोद्य	ब्रह्मोद्ययोः	ADJ;LOC;NEUT;DU
मुण्ड	मुण्डासु	ADJ;LOC;FEM;PL
पारग	पारगे	ADJ;ACC;FEM;DU
तरु	तरुभिः	ADJ;INS;PL
ज्योतिष	ज्योतिषे	N;NOM;DU
चातुर्मास्य	चातुर्मास्यैः	ADJ;INS;MASC;PL
तृष्णा	तृष्णे	N;NOM;DU
व्यञ्जन	व्यञ्जनस्य	ADJ;GEN;MASC;SG
द्वार	द्वारेभ्यः	N;DAT;PL
आज्ञा	आज्ञाः	N;VOC;PL
भव	भवः	N;NOM;SG
वनिता	वनिताभ्याम्	N;ABL;DU
अग्न्याधान	अग्न्याधानयोः	N;LOC;DU
जुगुप्सु	जुगुप्सोः	ADJ;ABL;MASC;SG
वृक	वृकयोः	N;LOC;DU
ऋण	ऋणयोः	ADJ;LOC;FEM;DU
विधवा	विधवयोः	N;GEN;DU
ब्राह्म	ब्राह्मयोः	ADJ;LOC;NEUT;DU
इन्दु	इन्दुभ्याम्	N;INS;DU
घोर	घोराभ्याम्	ADJ;DAT;FEM;DU
भट्ट	भट्टाभ्याम्	ADJ;ABL;NEUT;DU
क्षिति	क्षित्यै	N;DAT;SG
आहार	आहारे	ADJ;VOC;NEUT;DU
मन्दार	मन्दाराः	N;VOC;PL
आहार	आहारीभ्याम्	ADJ;DAT;FEM;DU
वैयाकरण	वैयाकरणान्	ADJ;ACC;MASC;PL
प्रसिद्धि	प्रसिद्धीनाम्	N;GEN;PL
ह्रस्व	ह्रस्वाभिः	ADJ;INS;FEM;PL
वाण	वाणेभ्यः	N;ABL;PL
पट	पट	N;VOC;SG
सत्य	सत्येन	N;INS;SG
वचन	वचनेभ्यः	ADJ;DAT;MASC;PL
कुक्षि	कुक्षिम्	N;ACC;SG
छात्र	छात्राय	N;DAT;SG
सिद्धार्थ	सिद्धार्थान्	ADJ;ACC;MASC;PL
नर	नरयोः	N;GEN;DU
अकूपार	अकूपाराः	ADJ;VOC;FEM;PL
ग्रह	ग्रहेन	N;INS;SG
अकर्मक	अकर्मकेषु	ADJ;LOC;MASC;PL
नवोदय	नवोदये	ADJ;ACC;FEM;DU
शब्द	शब्दौ	N;ACC;DU
श्रोणि	श्रोणिम्	N;ACC;SG
पलित	पलितानाम्	ADJ;GEN;PL
वानर	वानरयोः	ADJ;GEN;MASC;DU
शून्य	शून्येन	N;INS;SG
बोधि	बोधे	ADJ;VOC;MASC;SG
वैवाहिक	वैवाहिक	ADJ;VOC;NEUT;SG
सिद्धार्थ	सिद्धार्था	ADJ;DAT;NEUT;SG
बुद्धि	बुद्धयः	N;NOM;PL
सकर्मक	सकर्मकयोः	ADJ;LOC;MASC;DU
तनू	तनु	N;VOC;SG
उदन्या	उदन्याभ्याम्	N;ABL;DU
वज्र	वज्राः	ADJ;NOM;MASC;PL
अभिनय	अभिनयाभ्याम्	N;INS;DU
पर्वसंग्रह	पर्वसंग्रहस्य	N;GEN;SG
अङ्गार	अङ्गारेभ्यः	N;DAT;PL
अजाति	अजाती	N;VOC;DU
गभस्ति	गभस्ते	ADJ;VOC;MASC;SG
अश्वा	अशवया	N;INS;SG
अंस	अंसानाम्	N;GEN;PL
सवन	सवनेन	ADJ;INS;SG
अपस्मार	अपस्माराय	N;DAT;SG
नाश	नाशाय	N;DAT;SG
अन्ति	अन्तिः	N;NOM;SG
स्वयंवर	स्वयंवरयोः	ADJ;LOC;NEUT;DU
तुच्छ	तुच्छस्य	ADJ;GEN;MASC;SG
यजमान	यजमानाभ्याम्	ADJ;INS;MASC;DU
वानर	वानरेषु	ADJ;LOC;NEUT;PL
अन्ताराष्ट्रिय	अन्ताराष्ट्रियायाम्	ADJ;LOC;FEM;SG
मार्जार	मार्जारौ	N;ACC;DU
दन्त	दन्तान्	N;ACC;PL
प्रसिद्धि	प्रसिद्धी	N;ACC;DU
अकृता	अकृताभ्याम्	N;DAT;DU
मन्दर	मन्दरैः	ADJ;INS;MASC;PL
प्रस्ताव	प्रस्तावात्	N;ABL;SG
अक्षरा	अक्षराः	N;ACC;PL
सुम्न	सुम्ने	ADJ;VOC;NEUT;DU
अङ्गुलि	अङ्गुलयः	N;NOM;PL
अकर्मक	अकर्मकेण	ADJ;INS;MASC;SG
अदृष्ट	अदृष्ट	ADJ;VOC;MASC;SG
वैवाहिक	वैवाहिकाभ्याम्	ADJ;INS;MASC;DU
वैडूर्य	वैडूर्याभ्याम्	N;DAT;DU
क्ष	क्षाभ्याम्	N;ABL;DU
पारग	पारगाभ्याम्	ADJ;INS;NEUT;DU
पलाल	पलालाभ्याम्	N;INS;DU
शश	शशयोः	N;GEN;DU
विधान	विधानीभ्याम्	ADJ;ABL;FEM;DU
दीर्घ	दीर्घाभ्याम्	ADJ;DAT;FEM;DU
पट	पटयोः	N;LOC;DU
दिन	दिन	N;VOC;SG
दिन	दिनानि	N;NOM;PL
नवोदित	नवोदितायै	ADJ;DAT;FEM;SG
नाभि	नाभ्याः	N;ABL;SG
वैश्वानर	वैश्वानरम्	ADJ;ACC;MASC;SG
सुवर्ण	सुवर्णाय	ADJ;DAT;MASC;SG
कृमि	कृमिम्	N;ACC;SG
काव्य	काव्ययोः	ADJ;LOC;FEM;DU
तनूज	तनूजाभ्याम्	ADJ;INS;FEM;DU
तोयकण	तोयकणाभ्याम्	N;DAT;DU
वैश्य	वैश्यायाः	ADJ;GEN;FEM;SG
अनस्	अनोभिः	N;INS;PL
वसति	वसतिः	ADJ;NOM;FEM;SG
आथर्वण	आथर्वणयोः	ADJ;LOC;MASC;DU
गभस्ति	गभस्ती	ADJ;VOC;FEM;DU
मान	मानेषु	N;LOC;PL
विभक्ति	विभक्तिभ्यः	N;ABL;PL
पार्वती	पार्वतीभ्यः	N;DAT;PL
मिथुन	मिथुनयोः	ADJ;LOC;MASC;DU
भवन	भवने	N;ACC;DU
चरण	चरण	N;VOC;SG
सत्य	सत्येभ्यः	N;ABL;PL
रुचि	रुच्योः	N;LOC;DU
अग्निहोत्र	अग्निहोत्रेण	ADJ;INS;MASC;SG
यवनिका	यवनिके	N;VOC;DU
साध्य	साध्याः	ADJ;NOM;FEM;PL
सुम्न	सुम्ना	ADJ;NOM;FEM;SG
विजय	विजयौ	N;NOM;DU
साधु	साधु	ADJ;NOM;NEUT;SG
आशु	आशुषु	ADJ;LOC;NEUT;PL
जनन	जनने	N;VOC;DU
मिथुन	मिथुनौ	ADJ;VOC;MASC;DU
ऊर्णा	ऊर्णाभ्याम्	N;DAT;DU
उदय	उदयैः	N;INS;PL
सवन	सवा	N;DAT;SG
स्वप्न	स्वप्नस्य	N;GEN;SG
बाधा	बाधा	N;NOM;SG
अर्भ	अर्भ	ADJ;VOC;NEUT;SG
धी	धीनाम्	N;GEN;PL
अन्ताराष्ट्रिय	अन्ताराष्ट्रियाः	ADJ;ACC;FEM;PL
अहर्गण	अहर्गणानाम्	N;GEN;PL
भक्ति	भक्तिभ्याम्	N;ABL;DU
ईषा	ईषायाः	N;ABL;SG
अङ्गार	अङ्गारौ	N;VOC;DU
विधान	विधानम्	ADJ;ACC;MASC;SG
वैदर्भ	वैदर्भीभ्यः	ADJ;ABL;FEM;PL
गभस्ति	गभस्तिः	ADJ;NOM;FEM;SG
ब्राह्मण	ब्राह्मणाभ्याम्	ADJ;DAT;NEUT;DU
समाधि	समाधी	N;NOM;DU
दीर्घ	दीर्घात्	ADJ;ABL;NEUT;SG
मेघ	मेघौ	N;ACC;DU
शिल्पशाला	शिल्पशालायै	N;DAT;SG
नक्षत्र	नक्षतरैः	N;INS;PL
लोह	लोहानाम्	ADJ;GEN;NEUT;PL
वनिता	वनिते	N;VOC;DU
अंशक	अंशिकायाः	ADJ;ABL;FEM;SG
दुर्बल	दुर्बलयोः	N;LOC;DU
ग्रीवा	ग्रीवाः	N;NOM;PL
वैश्य	वैश्यानाम्	ADJ;GEN;FEM;PL
मार्ग	मार्गौ	N;VOC;DU
असुर	असुरः	N;NOM;SG
तनू	तन्वोः	N;LOC;DU
महिला	महिलायै	N;DAT;SG
विधवा	विधवे	N;VOC;DU
पुरुष	पुरुषाभ्याम्	N;INS;DU
असुर	असुरेण	N;INS;SG
कनक	कनकयोः	N;LOC;DU
चक्रवात	चक्रवातानाम्	N;GEN;PL
अंशक	अंशकम्	ADJ;ACC;MASC;SG
सुराकार	सुराकारा	N;DAT;SG
अमृत	अमृतात्	N;ABL;SG
स्वयंवर	स्वयंवरासु	ADJ;LOC;FEM;PL
पार्वती	पार्वत्योः	N;GEN;DU
प्रधान	प्रधाने	ADJ;NOM;NEUT;DU
साधार	साधारायै	ADJ;DAT;FEM;SG
अनुवाक	अनुवाकाः	N;NOM;PL
रुचि	रुचौ	N;LOC;SG
स्वयंवर	स्वयंवरायाः	ADJ;GEN;FEM;SG
साहाय्य	साहाय्ये	N;VOC;DU
चन्द्र	चन्द्रः	ADJ;NOM;MASC;SG
शश	शशः	N;NOM;SG
भक्ति	भक्त्योः	N;LOC;DU
मन्दर	मन्दराणाम्	ADJ;GEN;FEM;PL
रोच	रोस्य	N;GEN;SG
रुधिर	रुधिरायाम्	ADJ;LOC;FEM;SG
कुटुम्बक	कुटुम्बकैः	N;INS;PL
यव	यवाभ्याम्	N;DAT;DU
नक्षत्र	नक्षतरा	N;DAT;SG
वसति	वसतिनी	ADJ;VOC;NEUT;DU
परमाणु	परमाणवे	N;DAT;SG
आलु	आलूनाम्	N;GEN;PL
धातृ	धातृभ्यः	N;DAT;PL
मित्र	मित्रेषु	N;LOC;PL
व्यञ्जन	व्यञ्जने	ADJ;NOM;NEUT;DU
ब्रह्मोद्य	ब्रह्मोद्याभ्यः	ADJ;ABL;FEM;PL
ब्राह्मण	ब्राह्मणेभ्यः	ADJ;DAT;MASC;PL
पार्वती	पार्वतीषु	N;LOC;PL
वाद	वादया	ADJ;INS;FEM;SG
शारद	शारदस्य	ADJ;GEN;MASC;SG
शस्ति	शस्त्याः	N;ABL;SG
विशेष	विशेषयोः	ADJ;GEN;MASC;DU
कुज	कुजः	N;NOM;SG
धेनु	धेनोः	N;GEN;SG
नेपथ्य	नेपथ्यानि	N;ACC;PL
कृत्ति	कृत्त्या	N;INS;SG
सुवर्ण	सुवर्णे	ADJ;NOM;NEUT;DU
परमाणु	परमाणो	N;VOC;SG
प्रहार	प्रहारैः	N;INS;PL
शब्दकोश	शब्दकोशाः	N;NOM;PL
राम	रामाभ्याम्	ADJ;INS;FEM;DU
जा	जाः	N;NOM;PL
धातु	धातू	N;ACC;DU
आज्ञा	आज्ञाः	N;ACC;PL
भूतयज्ञ	भूतयज्ञाः	N;NOM;PL
खण्ड	खण्डेभ्यः	N;ABL;PL
बोधि	बोधीनाम्	ADJ;GEN;MASC;PL
उद्यान	उद्यानम्	N;ACC;SG
जुष्ट	जुष्टानाम्	ADJ;GEN;MASC;PL
अभ्र	अभ्रेभ्यः	N;DAT;PL
चन्द्रबिन्दु	चन्द्रबिन्दुः	N;NOM;SG
हिम	हिमाः	ADJ;NOM;MASC;PL
तन्तु	तन्तवः	N;VOC;PL
मिथुन	मिथुनायाम्	ADJ;LOC;FEM;SG
अकर्मक	अकर्मके	ADJ;ACC;FEM;DU
खिल	खिलेषु	ADJ;LOC;FEM;PL
वैश्वानर	वैश्वानरीणाम्	ADJ;GEN;FEM;PL
मनुष्ययज्ञ	मनुष्ययज्ञाः	N;NOM;PL
मृत	मृतानाम्	ADJ;GEN;FEM;PL
नलद	नलदानि	ADJ;ACC;FEM;PL
साहाय्य	साहाय्यम्	N;NOM;SG
चक्रवाल	चक्रवाल	N;VOC;SG
दातृ	दात्रा	N;INS;SG
ब्राह्मण	ब्राह्मणेभ्यः	ADJ;ABL;MASC;PL
नक्त	नक्तेषु	N;LOC;PL
अगस्ति	अगस्तिभिः	N;INS;PL
उपरूपक	उपरूपकानाम्	N;GEN;PL
चुम्बन	चुम्बन	N;VOC;SG
पुष्कर	पुष्करे	N;VOC;DU
उदय	उदयाभ्याम्	N;ABL;DU
प्रजापति	प्रजापत्योः	N;GEN;DU
उरण	उरणात्	N;ABL;SG
औषध	औषधाभ्याम्	N;INS;DU
मृत	मृतानि	ADJ;VOC;NEUT;PL
तनू	तनूः	N;NOM;SG
बुद्धि	बुद्धिभ्याम्	N;DAT;DU
पलित	पलिक्न्याः	N;GEN;SG
यवनिका	यवनिकाभ्याम्	N;DAT;DU
तोयकण	तोयकणौ	N;NOM;DU
काव्य	काव्याभ्याम्	ADJ;DAT;FEM;DU
देवयान	देवयाने	ADJ;NOM;NEUT;DU
राशिचक्र	राशिचक्रे	N;ACC;DU
स्वतन्त्र	स्वतन्त्र	ADJ;VOC;MASC;SG
कुञ्चिका	कुञ्चिकाम्	N;ACC;SG
कुल	कुलेषु	N;LOC;PL
अङ्ग	अङ्गाभ्याम्	N;DAT;DU
भुज	भुजाभ्याम्	N;ABL;DU
आशु	आशू	ADJ;ACC;MASC;DU
गति	गत्यै	N;DAT;SG
प्रतीक	प्रतीकयोः	ADJ;LOC;MASC;DU
गभस्ति	गभस्तिभ्याम्	ADJ;ABL;FEM;DU
प्राण	प्राणाभ्याम्	N;INS;DU
लक्ष्मी	लक्ष्मीणाम्	N;GEN;PL
पुण्डरीक	पुण्डरीकाः	N;NOM;PL
प्रतिष्ठा	प्रतिष्ठानाम्	N;GEN;PL
नरक	नरक	N;VOC;SG
अभिनय	अभिनयात्	N;ABL;SG
अमल	अमले	ADJ;LOC;NEUT;SG
सिद्धार्थ	सिद्धार्थेभ्यः	ADJ;ABL;MASC;PL
अनुक्रमणिका	अनुक्रमणिकाभ्यः	N;DAT;PL
वैश्वानर	वैश्वानरैः	ADJ;INS;MASC;PL
ब्राह्म	ब्राह्म्योः	ADJ;LOC;FEM;DU
साधन	साधनौ	ADJ;VOC;DU
काव्य	काव्ययोः	ADJ;LOC;NEUT;DU
धातृ	धातॄन्	N;ACC;PL
वृषभ	वृषभासु	ADJ;LOC;FEM;PL
ब्रह्मविद्या	ब्रह्मविद्यानाम्	N;GEN;PL
बोधि	बोधी	ADJ;ACC;FEM;DU
मेध	मेधान्	N;ACC;PL
कन्या	कन्ये	N;VOC;DU
विचार	विचारम्	N;ACC;SG
सवन	सवनाः	ADJ;ACC;PL
शारद	शारदाः	ADJ;VOC;MASC;PL
रोच	रोचौ	ADJ;VOC;DU
मेध	मेधानाम्	N;GEN;PL
तपस्	तपसाम्	N;GEN;PL
वैदर्भ	वैदर्भ्योः	ADJ;GEN;FEM;DU
रात्रि	रात्रिभ्याम्	N;ABL;DU
भोजन	भोजनम्	ADJ;ACC;MASC;SG
पार्ष्णि	पार्ष्णिभ्याम्	N;ABL;DU
अमल	अमलाभ्याम्	ADJ;INS;NEUT;DU
ग्रीष्म	ग्रीष्मानाम्	N;GEN;PL
प्रसाद	प्रसादौ	N;VOC;DU
पार्वती	पार्वति	N;VOC;SG
आहार	आहार्योः	ADJ;GEN;FEM;DU
वैयाकरण	वैयाकरणयोः	ADJ;LOC;FEM;DU
हृदय	हृदययोः	ADJ;LOC;FEM;DU
शारद	शारदाभ्याम्	ADJ;DAT;MASC;DU
ऊर्णा	ऊर्णाम्	N;ACC;SG
तटाक	तटाकैः	N;INS;PL
मधुर	मधुरम्	ADJ;NOM;NEUT;SG
चीन	चीनाय	N;DAT;SG
पृथु	पृथुभिः	N;INS;PL
तद्धित	तद्धितान्	N;ACC;PL
चन्दन	चन्दनाभ्याम्	N;ABL;DU
राम	रामाम्	ADJ;ACC;FEM;SG
अर्भ	अर्भाभ्याम्	ADJ;DAT;NEUT;DU
स्वयंवर	स्वयंवरौ	ADJ;ACC;MASC;DU
सर्प	सर्प्याम्	ADJ;LOC;FEM;SG
स्वतन्त्र	स्वतन्त्राभ्याम्	ADJ;DAT;NEUT;DU
दम्पति	दम्पती	N;NOM;DU
वैवाहिक	वैवाहिकाभ्याम्	ADJ;DAT;NEUT;DU
दुःस्वप्न	दुःस्वप्नयोः	N;GEN;DU
वसति	वसतेः	ADJ;GEN;MASC;SG
प्रवेशक	प्रवेशकेन	N;INS;SG
बोधि	बोधिम्	ADJ;ACC;FEM;SG
मिथुन	मिथुनाः	ADJ;NOM;FEM;PL
यव	यवाभ्याम्	N;ABL;DU
नक्ति	नक्ते	N;VOC;SG
वैवाहिक	वैवाहिक्योः	ADJ;LOC;FEM;DU
सिद्धार्थ	सिद्धार्थाः	ADJ;ACC;FEM;PL
लक्ष्मी	लक्ष्मी	N;NOM;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसेभ्यः	ADJ;ABL;NEUT;PL
मिथुन	मिथुनस्य	ADJ;GEN;MASC;SG
व्यञ्जन	व्यञ्जनात्	ADJ;ABL;NEUT;SG
द्वादशाह	द्वादशाहयोः	ADJ;LOC;FEM;DU
वसु	वसुना	ADJ;INS;SG
जुष्ट	जुष्टौ	ADJ;NOM;MASC;DU
पट	पटस्य	N;GEN;SG
ऋद्धि	ऋद्धये	N;DAT;SG
घोर	घोरायाम्	ADJ;LOC;FEM;SG
वसु	वसुनि	N;LOC;SG
भट्ट	भट्टाः	ADJ;NOM;FEM;PL
पारग	पारगे	ADJ;NOM;FEM;DU
मह	महे	ADJ;ACC;FEM;DU
मृग	मृगेन	N;INS;SG
आहार	आहाराणि	ADJ;NOM;NEUT;PL
अकाल	अकालयोः	N;GEN;DU
वैश्वानर	वैश्वानरीभ्याम्	ADJ;INS;FEM;DU
बोधि	बोधीन्	ADJ;ACC;MASC;PL
युद्ध	युद्धात्	ADJ;ABL;NEUT;SG
वानर	वानरीभ्यः	ADJ;ABL;FEM;PL
लोचन	लोचनेषु	N;LOC;PL
अक्षरा	अक्षरा	N;NOM;SG
बिल	बिलाभ्याम्	N;DAT;DU
साधु	साधुनः	ADJ;GEN;NEUT;SG
मृत	मृतेषु	ADJ;LOC;NEUT;PL
लोह	लोहैः	ADJ;INS;MASC;PL
नर	नरौ	N;ACC;DU
शारद	शारदम्	ADJ;ACC;NEUT;SG
लघु	लघ्व्या	ADJ;INS;SG
ब्राह्म	ब्राह्म्यौ	ADJ;NOM;FEM;DU
दुःस्वप्न	दुःस्वप्नेभ्यः	N;DAT;PL
नर	नरेभ्यः	N;ABL;PL
रात्रि	रात्रीणाम्	N;GEN;PL
अकूपार	अकूपारस्य	ADJ;GEN;NEUT;SG
मन्त्र	मन्त्र	N;VOC;SG
पुरुष	पुरुषाः	N;VOC;PL
मुण्ड	मुण्डानाम्	ADJ;GEN;MASC;PL
जुष्ट	जुष्टात्	ADJ;ABL;NEUT;SG
अनस्	अनसाम्	N;GEN;PL
दर्पण	दर्पणाभ्याम्	N;DAT;DU
काव्य	काव्यानि	ADJ;ACC;NEUT;PL
आथर्वण	आथर्वणाः	ADJ;NOM;MASC;PL
अग्निहोत्र	अग्निहोत्राभ्याम्	ADJ;INS;FEM;DU
सकर्मक	सकर्मके	ADJ;ACC;FEM;DU
वैदर्भ	वैदर्भीः	ADJ;ACC;FEM;PL
साधु	साधुभिः	ADJ;INS;NEUT;PL
राशि	राशे	N;VOC;SG
पृथु	प्र्थ्व्यौ	ADJ;NOM;DU
स्वतन्त्र	स्वतन्त्रानि	ADJ;NOM;NEUT;PL
तनू	तन्वः	N;NOM;PL
आथर्वण	आथर्वणाय	ADJ;DAT;MASC;SG
प्रतीक	प्रतीक	ADJ;VOC;NEUT;SG
भट्ट	भट्टाभ्याम्	ADJ;ABL;FEM;DU
ऊर्णा	ऊर्णे	N;ACC;DU
मृत	मृतयोः	ADJ;LOC;FEM;DU
सुम्न	सुम्नैः	ADJ;INS;NEUT;PL
आस्य	आस्य	N;VOC;SG
हिम	हिमात्	ADJ;ABL;MASC;SG
अमल	अमले	ADJ;NOM;FEM;DU
विधान	विधाने	ADJ;LOC;MASC;SG
रोच	रोौ	N;NOM;DU
अन्ताराष्ट्रिय	अन्ताराष्ट्रिये	ADJ;NOM;FEM;DU
कम्बल	कम्बलौ	N;NOM;DU
कर्कट	कर्कटेभ्यः	N;ABL;PL
स्वयंवर	स्वयंवराभ्यः	ADJ;DAT;FEM;PL
स्वतन्त्र	स्वतन्त्रासु	ADJ;LOC;FEM;PL
छाया	छाये	N;ACC;DU
राहु	राहुम्	N;ACC;SG
लिङ्गशरीर	लिङ्गशरीराभ्याम्	N;INS;DU
प्राच्य	प्राच्यायाः	ADJ;GEN;FEM;SG
पूर्णिमा	पूर्णिमायाः	N;GEN;SG
सरस्वती	सरस्वतीभ्याम्	N;DAT;DU
मह	महेभ्यः	ADJ;ABL;NEUT;PL
पुरोडाश	पुरोडाशौ	N;NOM;DU
अग्न्याधान	अग्न्याधानानाम्	N;GEN;PL
अग्निहोत्र	अग्निहोत्रा	ADJ;NOM;FEM;SG
पलित	पलितेभ्यः	ADJ;DAT;PL
कवि	कव्योः	ADJ;GEN;MASC;DU
अवतार	अवताराणाम्	N;GEN;PL
शृकाल	शृकालाः	N;VOC;PL
मनुष्य	मनुष्याणि	ADJ;NOM;NEUT;PL
निष्क	निष्क	N;VOC;SG
मेध	मेधाः	N;NOM;PL
दर्पण	दर्पणानाम्	N;GEN;PL
वर्ण	वर्णान्	N;ACC;PL
वसति	वसतयः	ADJ;NOM;MASC;PL
एध	एधौ	N;VOC;DU
मोह	मोहे	N;LOC;SG
वैडूर्य	वैडूर्येन	N;INS;SG
वसु	वसवे	ADJ;DAT;SG
ब्राह्मण	ब्राह्मणाभिः	ADJ;INS;FEM;PL
शान्ति	शान्तिः	N;NOM;SG
रात्रि	रात्र्या	N;INS;SG
वैश्वानर	वैश्वानराभ्याम्	ADJ;INS;NEUT;DU
जुष्ट	जुष्टाभिः	ADJ;INS;FEM;PL
प्रान्त	प्रान्तानाम्	ADJ;GEN;MASC;PL
वैवाहिक	वैवाहिकानि	ADJ;ACC;NEUT;PL
अकाल	अकाल	N;VOC;SG
साधु	साध्वोः	ADJ;LOC;MASC;DU
इन्दु	इन्दून्	N;ACC;PL
कर्मकाण्ड	कर्मकाण्डस्य	N;GEN;SG
सवन	सवानि	N;NOM;PL
देवयान	देवयान	ADJ;VOC;NEUT;SG
चीन	चीने	N;NOM;DU
तनूज	तनूजानाम्	ADJ;GEN;MASC;PL
तुच्छ	तुच्छे	ADJ;VOC;NEUT;DU
वैयाकरण	वैयाकरणस्य	ADJ;GEN;MASC;SG
आथर्वण	आथर्वणयोः	ADJ;LOC;NEUT;DU
सर्म	सर्मस्य	N;GEN;SG
गति	गत्याः	N;ABL;SG
तायु	तायुभ्यः	N;DAT;PL
मेघ	मेघयोः	N;LOC;DU
सहस्र	सहस्रीषु	ADJ;LOC;NEUT;PL
गभस्ति	गभस्तीनि	ADJ;NOM;NEUT;PL
सुम्न	सुम्नानाम्	ADJ;GEN;MASC;PL
जाया	जाया	N;NOM;SG
द्वार	द्वारम्	N;ACC;SG
जुगुप्सु	जुगुप्सुभ्याम्	ADJ;ABL;NEUT;DU
अङ्गार	अङ्गाराभ्याम्	N;INS;DU
स्वतन्त्र	स्वतन्त्रम्	ADJ;ACC;MASC;SG
यजमान	यजमानयोः	ADJ;GEN;FEM;DU
क्षिति	क्षिते	N;VOC;SG
अक्ष	अक्षाभ्याम्	N;ABL;DU
प्रतीक	प्रतीकौ	ADJ;NOM;MASC;DU
सुवर्ण	सुवर्णम्	ADJ;ACC;MASC;SG
भूतयज्ञ	भूतयज्ञात्	N;ABL;SG
अकूपार	अकूपारात्	ADJ;ABL;MASC;SG
अगाध	अगाधाभ्याम्	N;DAT;DU
चन्द्र	चन्द्रे	ADJ;LOC;NEUT;SG
ग्ना	ग्नयोः	N;LOC;DU
मनुष्य	मनुष्य	ADJ;VOC;MASC;SG
ऋद्धि	ऋद्धीनाम्	N;GEN;PL
उद्यान	उद्याने	N;LOC;SG
बाधा	बाधायाः	N;ABL;SG
केतु	केतुना	N;INS;SG
प्रधान	प्रधानायाः	ADJ;ABL;FEM;SG
राम	रामयोः	ADJ;LOC;MASC;DU
वाद	वादाभ्याम्	ADJ;DAT;MASC;DU
चातुर्मास्य	चातुर्मास्ययोः	ADJ;LOC;MASC;DU
अक्का	अक्काभ्यः	N;ABL;PL
वसु	वस्वै	ADJ;DAT;SG
सर्व	सर्वात्	ADJ;ABL;MASC;SG
सर्व	सर्व	ADJ;VOC;MASC;SG
हिमालय	हिमालयात्	N;ABL;SG
सहस्र	सहस्रे	ADJ;LOC;FEM;SG
वैयाकरण	वैयाकरणानि	ADJ;VOC;NEUT;PL
वैतान	वैताने	ADJ;LOC;MASC;SG
अदृष्ट	अदृष्टयोः	ADJ;GEN;FEM;DU
पाद	पादान्	N;ACC;PL
विजय	विजयः	N;NOM;SG
सिद्धार्थ	सिद्धार्थात्	ADJ;ABL;NEUT;SG
पुर	पुराभ्याम्	ADJ;INS;FEM;DU
सर्व	सर्वयोः	ADJ;LOC;FEM;DU
वैश्वानर	वैश्वानर्यौ	ADJ;NOM;FEM;DU
स्वर	स्वरेण	N;INS;SG
अर्भ	अर्भयोः	ADJ;LOC;FEM;DU
क्रोश	क्रोशानि	N;NOM;PL
प्रहार	प्रहारे	N;LOC;SG
क्रिया	क्रियासु	N;LOC;PL
फेन	फेनस्य	N;GEN;SG
ब्राह्मण	ब्राह्मण	ADJ;VOC;MASC;SG
जुगुप्सु	जुगुप्सूनाम्	ADJ;GEN;MASC;PL
ब्राह्म	ब्राह्म्यै	ADJ;DAT;FEM;SG
व्याकरण	व्याकरणयोः	N;GEN;DU
वचन	वचनम्	ADJ;ACC;NEUT;SG
खिल	खिले	ADJ;NOM;FEM;DU
मद	मदात्	N;ABL;SG
अगस्ति	अगस्ते	N;VOC;SG
चक्रवाक	चक्रवाकाभ्याम्	N;ABL;DU
तायु	तायुभिः	N;INS;PL
ऋण	ऋणाभिः	ADJ;INS;FEM;PL
बोधि	बोधिभ्यः	ADJ;ABL;FEM;PL
ऋद्धि	ऋद्धी	N;NOM;DU
हृदय	हृदये	ADJ;LOC;NEUT;SG
प्रतिष्ठा	प्रतिष्ठाः	N;ACC;PL
ईर्म	ईर्मैः	N;INS;PL
विचार	विचारयोः	N;LOC;DU
सुम्न	सुम्नाभ्याम्	ADJ;DAT;FEM;DU
जुष्ट	जुष्टाभ्याम्	ADJ;INS;FEM;DU
जङ्गल	जङ्गलाभ्याम्	ADJ;ABL;MASC;DU
वसति	वसतिनी	ADJ;ACC;NEUT;DU
हृदय	हृदयाः	ADJ;NOM;MASC;PL
ब्रह्मोद्य	ब्रह्मोद्यया	ADJ;INS;FEM;SG
सर्प	सर्पैः	ADJ;INS;MASC;PL
प्रतीक	प्रतीकैः	ADJ;INS;NEUT;PL
भोजन	भोजनीभ्यः	ADJ;DAT;FEM;PL
पति	पत्योः	N;GEN;DU
हृदय	हृदयाभ्याम्	ADJ;DAT;NEUT;DU
अन्ताराष्ट्रिय	अन्ताराष्ट्रियाः	ADJ;NOM;FEM;PL
आसन	आसनाभ्याम्	N;INS;DU
गभस्ति	गभस्तिना	ADJ;INS;MASC;SG
तुच्छ	तुच्छाय	ADJ;DAT;MASC;SG
भक्ति	भक्तीः	N;ACC;PL
रात्रि	रात्रिः	N;NOM;SG
प्राच्य	प्राच्याभ्याम्	ADJ;DAT;MASC;DU
आहार	आहारीषु	ADJ;LOC;FEM;PL
तुच्छ	तुच्छयोः	ADJ;GEN;MASC;DU
छुरी	छुरीभ्याम्	N;DAT;DU
लोह	लोहे	ADJ;ACC;NEUT;DU
श्वश्रू	श्वश्र्वा	N;INS;SG
वधू	वध्वै	N;DAT;SG
पोत	पोतेन	N;INS;SG
अर्भ	अर्भैः	ADJ;INS;NEUT;PL
नवोदय	नवोदये	ADJ;VOC;NEUT;DU
विधवा	विधवे	N;ACC;DU
सूत्र	सूत्राणि	N;NOM;PL
वृषभ	वृषभैः	ADJ;INS;MASC;PL
वराह	वराहौ	N;VOC;DU
अमल	अमलानाम्	ADJ;GEN;FEM;PL
द्वादशाह	द्वादशाहस्य	ADJ;GEN;MASC;SG
अकन्या	अकन्यायाः	N;GEN;SG
पलित	पलितौ	ADJ;ACC;DU
ऊर्णा	ऊर्णाभिः	N;INS;PL
उच्च	उच्चम्	ADJ;ACC;NEUT;SG
पुराण	पुराणाभ्याम्	N;INS;DU
सत्त्र	सत्त्र	N;VOC;SG
आर्य	आर्ये	ADJ;ACC;NEUT;DU
सिन्धु	सिन्धवः	N;VOC;PL
मध्यम	मध्यमाभ्यः	ADJ;ABL;FEM;PL
द्युम्न	द्युम्नानाम्	N;GEN;PL
सिंह	सिंहाय	N;DAT;SG
उपाख्यान	उपाख्यानाभ्याम्	N;DAT;DU
मध्यम	मध्यमाः	ADJ;NOM;FEM;PL
पवमान	पवमानाभ्याम्	ADJ;DAT;FEM;DU
अंशु	अंशवे	N;DAT;SG
सत्त्र	सत्त्रम्	N;ACC;SG
चतुरङ्ग	चतुरङग	ADJ;VOC;NEUT;SG
शलभ	शलभाभ्याम्	N;INS;DU
दुग्ध	दुग्धायाः	ADJ;ABL;FEM;SG
ओषधि	ओषधिषु	N;LOC;PL
भूमि	भूमिभिः	N;INS;PL
जनि	जन्या	N;INS;SG
पुरु	पुरुणः	ADJ;GEN;NEUT;SG
ज्या	ज्याम्	N;ACC;SG
घटना	घटनाभ्याम्	N;DAT;DU
गुण	गुणेषु	N;LOC;PL
तर्पण	तर्पणे	ADJ;NOM;NEUT;DU
विद्याचण	विद्याचणः	ADJ;NOM;MASC;SG
सृष्टि	सृष्टये	N;DAT;SG
अंहु	अंहुभ्याम्	ADJ;ABL;FEM;DU
आर्ष	आर्षी	ADJ;NOM;FEM;SG
अचित्ति	अचित्तिभिः	N;INS;PL
संस्कृत	संस्कृतानि	ADJ;ACC;NEUT;PL
सहित	सहितायाः	ADJ;ABL;FEM;SG
कुमार	कुमारैः	N;INS;PL
श्रामणेर	श्रामणेरैः	N;INS;PL
विष	विषौ	ADJ;VOC;MASC;DU
राज्य	राज्ये	ADJ;VOC;NEUT;DU
अमित्र	अमित्रे	ADJ;NOM;NEUT;DU
कनीन	कनीने	ADJ;NOM;FEM;DU
अचित्ति	अचित्त्याः	N;GEN;SG
उखा	उखे	N;VOC;DU
सांख्य	सांख्यानि	ADJ;ACC;NEUT;PL
कपि	कप्याः	ADJ;GEN;FEM;SG
इन्द्र	इन्द्राय	N;DAT;SG
जीवित	जीवितम्	ADJ;NOM;NEUT;SG
बह्वृच	बह्वृच्याम्	N;LOC;SG
मण्डल	मण्डले	ADJ;NOM;NEUT;DU
संगीत	संगीताः	ADJ;VOC;MASC;PL
गाथा	गाथयोः	N;LOC;DU
सांख्य	सांख्यानि	ADJ;NOM;NEUT;PL
सूक्त	सूक्तेन	ADJ;INS;NEUT;SG
ब्रह्मवेद	ब्रह्मवेदस्य	N;GEN;SG
संहिता	संहिताभ्याम्	N;DAT;DU
वृत्त	वृत्ताम्	ADJ;ACC;FEM;SG
सोम	सोमैः	ADJ;INS;NEUT;PL
व्याहृति	व्याहृतये	N;DAT;SG
शोभा	शोभासु	N;LOC;PL
पुरोहित	पुरोहितौ	ADJ;VOC;MASC;DU
संगीत	संगीताभ्याम्	ADJ;ABL;FEM;DU
जीवित	जीविताः	ADJ;NOM;FEM;PL
कितव	कितवस्य	N;GEN;SG
अपभ्रंश	अपभ्रंशाभ्याम्	N;DAT;DU
श्रमण	श्रमण्याम्	ADJ;LOC;SG
ज्ञानकाण्ड	ज्ञानकाण्डेन	N;INS;SG
अनुवाद	अनुवादयोः	N;LOC;DU
अरुण	अरुणान्	N;ACC;PL
अर्जुन	अर्जुनम्	N;NOM;SG
ऋषि	ऋषिषु	N;LOC;PL
माला	मालायै	N;DAT;SG
परा	पराभ्यः	N;DAT;PL
ऊर्ध्व	ऊर्ध्वेन	ADJ;INS;MASC;SG
तर्पण	तर्पणेभ्यः	ADJ;DAT;NEUT;PL
ऋत	ऋते	N;VOC;DU
गर्भ	गर्भाभ्याम्	N;INS;DU
दृढ	दृढैः	N;INS;PL
जनि	जनिभिः	N;INS;PL
अगुण	अगुणः	N;NOM;SG
देश	देशम्	N;ACC;SG
अक्षता	अक्षते	N;NOM;DU
चतुरङ्ग	चतुरङगे	ADJ;VOC;FEM;SG
नाचिकेत	नाचिकेत्यः	ADJ;NOM;FEM;PL
जामित्र	जामित्रे	N;NOM;DU
बाल	बालौ	N;VOC;DU
अर्थवाद	अर्थवादैः	N;INS;PL
विपक्ष	विपक्षाः	ADJ;ACC;FEM;PL
चाप	चापाभ्याम्	N;ABL;DU
दुर्जन	दुर्जनायाः	ADJ;ABL;FEM;SG
गविष्टि	गविष्टेः	N;GEN;SG
आश्रम	आश्रमाभ्याम्	N;INS;DU
प्राणायाम	प्राणायामाभ्याम्	N;DAT;DU
अपत्यता	अपत्यताभ्यः	N;DAT;PL
केन्द्र	केन्द्रेभ्यः	N;DAT;PL
सृष्टि	सृष्ट्योः	N;LOC;DU
सामयाचारिक	सामयाचारिका	ADJ;DAT;NEUT;SG
क्षत्रिय	क्षत्रियासु	ADJ;LOC;FEM;PL
अक्षता	अक्षतया	N;INS;SG
मल	मलेभ्यः	ADJ;ABL;MASC;PL
क्षत्रिय	क्षत्रिये	ADJ;LOC;MASC;SG
तर्पण	तर्पणि	ADJ;VOC;FEM;SG
संगीत	संगीताभ्यः	ADJ;ABL;FEM;PL
सूक्त	सूक्तायै	ADJ;DAT;FEM;SG
नेत्र	नेत्राय	N;DAT;SG
रूपक	रूपकेभ्यः	ADJ;ABL;MASC;PL
सामयाचारिक	सामयाचारिकम्	ADJ;NOM;NEUT;SG
श्रवण	श्रवणेन	N;INS;SG
आवास	आवासेषु	N;LOC;PL
अभिधान	अभिधानेभ्यः	N;ABL;PL
सिद्ध	सिद्धाः	ADJ;VOC;MASC;PL
मति	मते	N;VOC;SG
ऋष्व	ऋष्वाभ्याम्	ADJ;INS;MASC;DU
घूक	घूकौ	N;VOC;DU
परिणय	परिणयेषु	N;LOC;PL
विशाल	विशालीनाम्	ADJ;GEN;PL
काण्ड	काण्डौ	N;NOM;DU
हेतु	हेतुषु	N;LOC;PL
बल	बलासु	ADJ;LOC;FEM;PL
विष्णु	विषणधेन्वाः	N;GEN;SG
पार्वण	पार्वणाभ्याम्	ADJ;DAT;NEUT;DU
श्यामा	श्यामाभ्यः	N;DAT;PL
आवसथ्य	आवसथ्येभ्यः	ADJ;DAT;NEUT;PL
वृत्त	वृत्तायाः	ADJ;GEN;FEM;SG
असि	असौ	N;LOC;SG
कितव	कितवे	N;LOC;SG
पुरोहित	पुरोहितेन	ADJ;INS;NEUT;SG
प्रार्थना	प्रार्थनयोः	N;LOC;DU
उदन्	उदभ्याम्	N;ABL;DU
अधिकार	अधिकारान्	N;ACC;PL
पर्जन्य	पर्जन्यम्	N;ACC;SG
गाथ	गाथाः	N;NOM;PL
सत्त्र	सत्त्रानि	N;NOM;PL
ब्रह्म	ब्रह्मौ	N;VOC;DU
स्वर्ग	स्वर्गाभिः	ADJ;INS;FEM;PL
प्राणायाम	प्राणायामौ	N;NOM;DU
शरीर	शरीरयोः	N;LOC;DU
अध्याय	अध्याययोः	N;GEN;DU
उद्गूर्ण	उद्गूर्णेषु	ADJ;LOC;MASC;PL
धूर्त	धूर्त	ADJ;VOC;MASC;SG
मत्त	मत्तयोः	N;GEN;DU
व्याघ्र	व्याघ्रेभ्यः	N;DAT;PL
सांख्य	सांख्या	ADJ;NOM;FEM;SG
निपात	निपातान्	N;ACC;PL
सिंह	सिंहैः	N;INS;PL
आर्ष	आर्षात्	ADJ;ABL;NEUT;SG
प्रमन्थ	प्रमन्थम्	N;ACC;SG
देवयज्ञ	देवयज्ञे	N;LOC;SG
क्षत्रिय	क्षत्रियम्	ADJ;ACC;MASC;SG
नारायण	नारायणि	ADJ;VOC;FEM;SG
नान्दी	नान्दीभ्याम्	N;ABL;DU
देवयज्ञ	देवयज्ञ	N;VOC;SG
स्वेद	स्वेदे	ADJ;ACC;NEUT;DU
श्रवण	श्रवणयोः	N;LOC;DU
ग्राम	ग्रामेषु	N;LOC;PL
उपरम	उपरमाभ्याम्	N;INS;DU
अक्षय	अक्षयेन	ADJ;INS;NEUT;SG
राज	राजान्	N;ACC;PL
अनार्य	अनार्याः	ADJ;VOC;MASC;PL
राज	राजयोः	N;GEN;DU
कितव	कितवः	N;NOM;SG
इतिहास	इतिहासेभ्यः	N;ABL;PL
द्राक्षा	द्राक्षाभिः	N;INS;PL
काण्ड	काण्डेभ्यः	N;ABL;PL
मानव	मानवौ	N;VOC;DU
भेषज	भेषज्याः	ADJ;GEN;FEM;SG
स्थान	स्थाना	N;DAT;SG
भिक्षु	भिक्षौ	N;LOC;SG
बहुव्रीहि	बहुव्रीहिभ्याम्	ADJ;INS;MASC;DU
पण्डित	पण्डिताभ्याम्	ADJ;ABL;FEM;DU
कालचक्र	कालचक्राभ्याम्	N;ABL;DU
मनस्	मनसी	N;VOC;DU
घोषक	घोषकाय	N;DAT;SG
परिजन	परिजनेभ्यः	N;DAT;PL
उदात्त	उदात्ते	ADJ;VOC;FEM;DU
इन्द्र	इन्द्रेभ्यः	N;DAT;PL
पण्डित	पण्डिताभ्याम्	ADJ;INS;NEUT;DU
रयि	रयिभ्याम्	ADJ;DAT;FEM;DU
कालचक्र	कालचक्रानि	N;VOC;PL
विपक्ष	विपक्षेभ्यः	ADJ;DAT;MASC;PL
गञ्जा	गञ्जाभ्यः	N;ABL;PL
संगीत	संगीत	ADJ;VOC;MASC;SG
योनि	योनिभिः	N;INS;PL
अगार	अगारस्य	N;GEN;SG
ऋष्व	ऋष्वेण	ADJ;INS;NEUT;SG
इन्द्र	इन्द्रौ	N;NOM;DU
आचार	आचारः	N;NOM;SG
पुलस्ति	पुलस्तिभ्याम्	ADJ;INS;MASC;DU
कनीन	कनीनान्	ADJ;ACC;MASC;PL
ईशान	ईशानाः	ADJ;VOC;MASC;PL
भारतवर्ष	भारतवर्षानि	N;NOM;PL
गौड	गौडेभ्यः	ADJ;DAT;NEUT;PL
गज	गजेभ्यः	N;DAT;PL
द्रु	द्रुभ्यः	N;DAT;PL
मण्डल	मण्डलानि	ADJ;NOM;NEUT;PL
उक्थ	उक्थौ	N;NOM;DU
उच्च	उच्चानि	ADJ;ACC;NEUT;PL
बल	बलौ	ADJ;NOM;MASC;DU
उखा	उखाभ्याम्	N;INS;DU
वादक	वादकाः	N;NOM;PL
अरुण	अरुणौ	N;NOM;DU
अन	अनस्य	N;GEN;SG
ऋत	ऋतेभ्यः	N;ABL;PL
विरा	विराः	N;NOM;PL
प्लुषि	प्लुषिभ्याम्	N;INS;DU
सुजित	सुजितम्	N;NOM;SG
देश	देशाः	N;NOM;PL
संगीत	संगीते	ADJ;VOC;NEUT;DU
संगीतशाला	संगीतशाला	N;NOM;SG
अमित्र	अमित्रम्	ADJ;ACC;MASC;SG
कल	कलस्य	ADJ;GEN;MASC;SG
कृष्ण	कृष्णे	ADJ;VOC;FEM;DU
द्रु	द्रुणे	N;DAT;SG
कर्पर	कर्परौ	N;ACC;DU
माला	मालायाः	N;GEN;SG
अजिर	अजिरेभ्यः	ADJ;DAT;MASC;PL
सहित	सहिताभ्याम्	ADJ;ABL;MASC;DU
आम्र	आम्रेभ्यः	N;DAT;PL
आर्ष	आर्ष्यौ	ADJ;NOM;FEM;DU
गञ्जा	गञ्जाः	N;NOM;PL
संगीत	संगीतम्	ADJ;NOM;NEUT;SG
मण्डल	मण्डलानाम्	ADJ;GEN;NEUT;PL
कल	कलायाः	ADJ;GEN;FEM;SG
वृत्त	वृत्तेन	ADJ;INS;NEUT;SG
जिह्वा	जिह्वाम्	N;ACC;SG
अंश	अंशयोः	N;LOC;DU
स्थान	स्थाने	N;NOM;DU
दुर्ग	दुर्गेषु	N;LOC;PL
तर्पण	तर्पण्योः	ADJ;LOC;FEM;DU
यातु	यातु	N;NOM;SG
देवयज्ञ	देवयज्ञाभ्याम्	N;ABL;DU
कल	कलैः	ADJ;INS;MASC;PL
प्रताप	प्रतापाणाम्	N;GEN;PL
मन्यु	मन्य्वोः	N;GEN;DU
संधि	संधिभ्याम्	ADJ;INS;FEM;DU
बाला	बालाभ्याम्	N;INS;DU
राज्ञी	राज्ञ्यः	N;VOC;PL
आद	आदाभ्याम्	N;ABL;DU
मृदु	मृदुनी	N;ACC;DU
शारि	शारौ	N;LOC;SG
अनुवाद	अनुवादात्	N;ABL;SG
निपात	निपाताः	N;VOC;PL
यक्ष	यक्षे	N;NOM;DU
पान	पानयोः	N;GEN;DU
दृढ	दृढे	N;VOC;DU
तर्क	तर्के	N;VOC;DU
नामकरण	नामकरणे	N;NOM;DU
आचार	आचाराः	N;VOC;PL
ज्ञानकाण्ड	ज्ञानकाण्डानि	N;VOC;PL
शलभ	शलभेन	N;INS;SG
भारत	भारताभ्याम्	ADJ;INS;NEUT;DU
अरित्र	अरित्रौ	ADJ;VOC;MASC;DU
कण्ठ	कण्ठेषु	N;LOC;PL
घोषक	घोषकाः	N;NOM;PL
मनु	मनून्	ADJ;ACC;MASC;PL
स्वरित	स्वरितौ	ADJ;VOC;MASC;DU
घोष	घोषस्य	N;GEN;SG
नारायण	नारायणम्	ADJ;NOM;NEUT;SG
वरुण	वरुणौ	N;VOC;DU
देवदासी	देवदासीषु	N;LOC;PL
संगीत	संगीतानि	ADJ;ACC;NEUT;PL
पराजय	पराजयौ	N;VOC;DU
इच्छा	इच्छाभ्याम्	N;INS;DU
अविद्या	अविद्ययोः	N;LOC;DU
तृण	तृणयोः	N;LOC;DU
पूर	पूराः	ADJ;VOC;FEM;PL
उक्थ	उक्थानि	N;ACC;PL
संधि	संधीनि	ADJ;VOC;NEUT;PL
सुन्दर	सुन्दरेषु	N;LOC;PL
नाचिकेत	नाचिकेति	ADJ;VOC;FEM;SG
चित्र	चित्रेषु	N;LOC;PL
तर्पण	तर्पणानि	ADJ;NOM;NEUT;PL
दुर्जन	दुर्जनाभ्याम्	ADJ;DAT;NEUT;DU
नड	नडौ	N;VOC;DU
लम्बक	लम्बकौ	N;NOM;DU
भग	भगौ	N;VOC;DU
अकृत्य	अकृत्यात्	N;ABL;SG
मत्स्य	मत्स्यस्य	N;GEN;SG
वृष	वृषाभ्याम्	N;INS;DU
कल्य	कल्याः	ADJ;ACC;FEM;PL
कल	कल	ADJ;VOC;MASC;SG
स्वर्ग	स्वर्गाभ्याम्	ADJ;INS;NEUT;DU
प्रयत्न	प्रयत्नयोः	N;LOC;DU
आति	आतिभ्यः	N;DAT;PL
पुलस्ति	पुलस्तिना	ADJ;INS;MASC;SG
कर्म	कर्मे	N;ACC;DU
व्याघ्र	व्याघ्रे	N;LOC;SG
मूल्य	मूल्येभ्यः	ADJ;ABL;MASC;PL
पुलस्ति	पुलस्ति	ADJ;NOM;NEUT;SG
संदेश	संदेशयोः	N;LOC;DU
आवसथ्य	आवसथ्याभ्याम्	ADJ;INS;NEUT;DU
वाणिज	वाणिजैः	N;INS;PL
भ्राता	भ्रातायाः	N;ABL;SG
उल्ब	उल्ब	N;VOC;SG
मणि	मण्योः	N;LOC;DU
अरित्र	अरित्राभ्याम्	ADJ;ABL;FEM;DU
अकृत्य	अकृत्ये	N;VOC;DU
अक्षय	अक्षयया	ADJ;INS;FEM;SG
चषक	चषकौ	N;NOM;DU
प्रारम्भ	प्रारम्भस्य	N;GEN;SG
वर्षा	वर्षे	N;VOC;DU
स्वश्व	स्वश्व	ADJ;VOC;MASC;SG
श्वन्	शुनोः	N;LOC;DU
असि	अस्योः	N;LOC;DU
सांख्य	सांख्यैः	ADJ;INS;NEUT;PL
अक्तु	अक्तुभ्याम्	N;ABL;DU
परिणाम	परिणामाः	N;VOC;PL
उद्गीथ	उद्गीथेषु	N;LOC;PL
पठन	पठन	N;VOC;SG
सांख्य	सांख्यम्	ADJ;ACC;NEUT;SG
हेतु	हेतून्	N;ACC;PL
चुम्ब	चुम्बयोः	N;LOC;DU
नाथ	नाथ	ADJ;VOC;MASC;SG
मति	मती	N;NOM;DU
मल	मलाभ्याम्	ADJ;ABL;MASC;DU
कर्पर	कर्परयोः	N;LOC;DU
विष्कम्भ	विष्कम्भौ	N;ACC;DU
मृदु	मृदवः	ADJ;VOC;PL
जन	जनौ	ADJ;NOM;MASC;DU
नारायण	नारायण्यौ	ADJ;NOM;FEM;DU
अकृत्य	अकृत्याभ्याम्	N;ABL;DU
गूथ	गूथैः	N;INS;PL
भारतवर्ष	भारतवर्षस्य	N;GEN;SG
पुरु	पुरुभ्यः	ADJ;DAT;MASC;PL
अनार्य	अनार्यैः	ADJ;INS;MASC;PL
आर्य	आर्याणि	ADJ;VOC;NEUT;PL
कनीन	कनीनाभ्याम्	ADJ;ABL;FEM;DU
मुद्रा	मुद्रयोः	N;LOC;DU
ओषधि	ओषध्योः	N;GEN;DU
परिजन	परिजनाय	N;DAT;SG
वाहन	वाहने	N;NOM;DU
पवमान	पवमानायाः	ADJ;GEN;FEM;SG
चकोर	चकोरेभ्यः	N;ABL;PL
अग्नि	अग्निम्	N;ACC;SG
तीर	तीराभ्याम्	N;DAT;DU
धूर्त	धूर्ता	ADJ;NOM;FEM;SG
साधकत्व	साधकत्व	N;VOC;SG
घोषणा	घोषणाभ्यः	N;ABL;PL
क्षत्र	क्षत्र	N;VOC;SG
निपात	निपाताः	N;NOM;PL
अन्त	अन्ताभ्याम्	N;INS;DU
उक्ति	उक्त्या	N;INS;SG
कपि	कपीनि	ADJ;ACC;NEUT;PL
पान	पानेन	N;INS;SG
सूक्त	सूक्तान्	ADJ;ACC;MASC;PL
श्रमण	श्रमणाभ्यः	ADJ;ABL;PL
वृत्र	वृत्रैः	N;INS;PL
तर्का	तर्कयोः	N;GEN;DU
मण्डल	मण्डलेभ्यः	ADJ;ABL;MASC;PL
विष्कम्भ	विष्कम्भ	N;VOC;SG
जानु	जानुनी	N;VOC;DU
ऊर्ध्व	ऊर्ध्वाभ्यः	ADJ;ABL;FEM;PL
नाटक	नाटकौ	ADJ;NOM;MASC;DU
वाट	वाटाभ्याम्	N;ABL;DU
पवमान	पवमानेभ्यः	ADJ;DAT;MASC;PL
राज्य	राज्याभ्याम्	ADJ;INS;MASC;DU
विपक्ष	विपक्षायाः	ADJ;ABL;FEM;SG
किशोर	किशोराः	N;NOM;PL
वर्षा	वर्षे	N;NOM;DU
जन	जनीभ्यः	ADJ;DAT;FEM;PL
आवास	आवासैः	N;INS;PL
आख्या	आख्याः	N;NOM;PL
मणि	मणिभिः	N;INS;PL
स्तृ	स्तृषु	N;LOC;PL
ऊर्ध्व	ऊर्ध्वे	ADJ;LOC;NEUT;SG
दुर्जन	दुर्जनाः	ADJ;NOM;FEM;PL
उद्गूर्ण	उद्गूर्णयोः	ADJ;LOC;MASC;DU
अनुदात्त	अनुदात्तासु	ADJ;LOC;FEM;PL
पुरु	पूर्वी	ADJ;NOM;FEM;SG
दिति	दितिभ्यः	N;ABL;PL
जाङ्गल	जाङ्गलाभ्याम्	ADJ;ABL;NEUT;DU
मध्यम	मध्यमयोः	ADJ;LOC;FEM;DU
प्रतिबुद्ध	प्रतिबद्धानाम्	ADJ;GEN;NEUT;PL
विद्याचण	विद्याचणायाम्	ADJ;LOC;FEM;SG
शय्या	शय्याभिः	N;INS;PL
स्नातक	स्नातके	N;LOC;SG
कृष्ण	कृष्णेभ्यः	ADJ;DAT;MASC;PL
राजकुमार	राजकुमारः	N;NOM;SG
कृष्ण	कृष्णाभ्याम्	ADJ;ABL;FEM;DU
नारायण	नारायणात्	ADJ;ABL;MASC;SG
पार्वण	पार्वणीभ्याम्	ADJ;DAT;FEM;DU
कालचक्र	कालचक्रानाम्	N;GEN;PL
स्वागम	स्वागमौ	N;VOC;DU
सहित	सहिताभ्याम्	ADJ;INS;MASC;DU
भण्टाकी	भण्टाकीभिः	N;INS;PL
बुध्न	बुध्नाभ्याम्	ADJ;ABL;FEM;DU
सुजित	सुजितानि	N;ACC;PL
अनुराग	अनुरागे	N;LOC;SG
अगार	अगारेभ्यः	N;ABL;PL
संस्कार	संस्कारयोः	N;LOC;DU
रयि	रयि	ADJ;ACC;NEUT;SG
स्वर्ग	स्वर्ग	ADJ;VOC;NEUT;SG
संगीतशाला	संगीतशालाः	N;NOM;PL
चित्र	चित्रयोः	N;LOC;DU
गौड	गौडी	ADJ;NOM;FEM;SG
दृढ	दृढानाम्	N;GEN;PL
दुग्ध	दुग्धाभ्याम्	ADJ;DAT;FEM;DU
उच्च	उच्चे	ADJ;NOM;FEM;DU
विपक्ष	विपक्षयोः	ADJ;GEN;MASC;DU
चिन्तन	चिन्तनानाम्	N;GEN;PL
तर्क	तर्के	N;NOM;DU
रासभी	रासभीभिः	N;INS;PL
वरुण	वरुणेन	N;INS;SG
तर्क	तर्केभ्यः	N;ABL;PL
बुध्न	बुध्नैः	ADJ;INS;MASC;PL
दुर्जन	दुर्जनया	ADJ;INS;FEM;SG
सुन्दर	सुन्दरीभिः	ADJ;INS;PL
ऊर्ध्व	ऊर्ध्वस्य	ADJ;GEN;NEUT;SG
पुरंधि	पुरंधौ	ADJ;LOC;NEUT;SG
दास	दासौ	N;NOM;DU
परिवार	परिवारौ	N;VOC;DU
धूर्त	धूर्ते	ADJ;LOC;MASC;SG
बाल	बालयोः	N;LOC;DU
निष्ठा	निष्ठया	N;INS;SG
भारत	भारताः	ADJ;NOM;MASC;PL
स्वर्ग	स्वर्गाय	ADJ;DAT;MASC;SG
बाल	बाल	N;VOC;SG
प्रथम	प्रथमाभ्याम्	ADJ;INS;FEM;DU
कल	कलयोः	ADJ;LOC;MASC;DU
वर्ष	वर्षम्	ADJ;NOM;NEUT;SG
गो	गोषु	N;LOC;PL
संस्कृत	संस्कृत	ADJ;VOC;MASC;SG
भेषज	भेषज्यः	ADJ;VOC;FEM;PL
पत्नी	पत्न्यौ	N;ACC;DU
ऋषि	ऋषयः	N;VOC;PL
संधि	संधिभ्याम्	ADJ;INS;MASC;DU
शरीर	शरीरात्	N;ABL;SG
उद्र	उद्रात्	N;ABL;SG
पण्डित	पण्डितेन	ADJ;INS;NEUT;SG
चकोर	चकोरानाम्	N;GEN;PL
गूथ	गूथाः	N;VOC;PL
वशगा	वशगाभ्याम्	N;ABL;DU
जय	जयम्	N;ACC;SG
विष्णु	विषणोः	N;ABL;SG
सिद्ध	सिद्धे	ADJ;ACC;FEM;DU
सिंह	सिंहस्य	N;GEN;SG
शुक	शुकयोः	N;LOC;DU
पूर	पूराभ्याम्	ADJ;DAT;FEM;DU
कण्ठ	कण्ठे	N;LOC;SG
प्राणायाम	प्राणायामाः	N;NOM;PL
स्नेह	स्नेहस्य	N;GEN;SG
कृष्ण	कृष्णात्	ADJ;ABL;MASC;SG
जाङ्गल	जाङ्गलासु	ADJ;LOC;FEM;PL
होतृ	होतुः	N;GEN;SG
साम्य	साम्ये	N;NOM;DU
मनु	मनू	ADJ;VOC;FEM;DU
ऊर्ध्व	ऊर्ध्वाभ्याम्	ADJ;INS;FEM;DU
अङ्क	अङ्काभ्याम्	N;DAT;DU
अंहु	अंहुः	ADJ;NOM;FEM;SG
चतुरङ्ग	चतुरङगे	ADJ;LOC;MASC;SG
उद्र	उद्रौ	N;VOC;DU
साहित्य	साहित्येन	N;INS;SG
राज्य	राज्येषु	ADJ;LOC;MASC;PL
वाट	वाट	N;VOC;SG
अन	अनाः	N;VOC;PL
निर्णय	निर्णययोः	N;GEN;DU
जनि	जनयः	N;NOM;PL
विपक्ष	विपक्षाणाम्	ADJ;GEN;NEUT;PL
राज्ञी	राज्ञ्यौ	N;NOM;DU
पवमान	पवमानौ	ADJ;ACC;MASC;DU
दिग्नाग	दिग्नागाय	N;DAT;SG
मूल्य	मूल्ये	ADJ;LOC;MASC;SG
प्लुषि	प्लुषिभ्याम्	N;ABL;DU
मल	मलेन	ADJ;INS;NEUT;SG
पवमान	पवमानाय	ADJ;DAT;MASC;SG
पर्जन्य	पर्जन्येभ्यः	N;ABL;PL
अन्त	अन्ताः	N;VOC;PL
अकृत	अकृतयोः	N;LOC;DU
उक्त	उक्तेन	ADJ;INS;MASC;SG
स्वपू	स्वपूम्	N;ACC;SG
दुर्जन	दुर्जनाभ्याम्	ADJ;ABL;FEM;DU
बल	बले	ADJ;VOC;FEM;DU
स्तृ	स्तुः	N;ABL;SG
भण्डाकी	भण्डाक्यः	N;NOM;PL
मति	मत्याः	N;GEN;SG
स्नातक	स्नातकानाम्	N;GEN;PL
स्वस्ति	स्वस्तिभ्याम्	N;INS;DU
मषि	मषिषु	N;LOC;PL
जाङ्गल	जाङ्गलैः	ADJ;INS;NEUT;PL
कपि	कपेः	ADJ;GEN;MASC;SG
क्षत्रिय	क्षत्रिययोः	ADJ;LOC;FEM;DU
सृष्टि	सृष्टिभ्याम्	N;DAT;DU
पुत्र	पुत्रेण	N;INS;SG
केश	केशयोः	N;GEN;DU
संधि	संधी	ADJ;ACC;MASC;DU
विष	विषान्	ADJ;ACC;MASC;PL
मठ	मठेभ्यः	N;DAT;PL
पाठ	पाठयोः	N;GEN;DU
रयि	रयि	ADJ;VOC;NEUT;SG
स्वरित	स्वरिताभिः	ADJ;INS;FEM;PL
मुख	मुखस्य	N;GEN;SG
अविक	अविकैः	N;INS;PL
गर्भ	गर्भाभ्याम्	N;ABL;DU
भूर्ज	भूर्जानाम्	N;GEN;PL
महाकाव्य	महाकाव्यानि	N;ACC;PL
पुराण	पुराणाः	ADJ;NOM;PL
परिणाम	परिणामेभ्यः	N;ABL;PL
श्रामणेर	श्रामणेरानाम्	N;GEN;PL
कर्पर	कर्परात्	N;ABL;SG
ईशान	ईशाने	ADJ;ACC;NEUT;DU
परिवार	परिवाराभ्याम्	N;INS;DU
वर्षा	वर्षायाः	N;GEN;SG
पुलस्ति	पुलस्तयः	ADJ;VOC;MASC;PL
रासभी	रासभ्याः	N;GEN;SG
अङ्गुरि	अङ्गुरिभ्यः	N;DAT;PL
प्रथम	प्रथमस्य	ADJ;GEN;MASC;SG
स्वेद	स्वेदैः	ADJ;INS;NEUT;PL
वैतथ्य	वैतथ्ये	ADJ;LOC;NEUT;SG
गोविन्द	गोविन्देभ्यः	N;DAT;PL
मत्स्य	मत्स्येषु	N;LOC;PL
रूपक	रूपकौ	ADJ;VOC;MASC;DU
कल	कलाभ्याम्	ADJ;ABL;NEUT;DU
पितृयाण	पितृयाणे	ADJ;LOC;MASC;SG
बहुव्रीहि	बहुव्रीहिम्	ADJ;ACC;MASC;SG
गोपाल	गोपालयोः	N;GEN;DU
अमृता	अमृते	N;VOC;SG
मृगतृष्णा	मृगतृष्णयोः	N;GEN;DU
गोविन्द	गोविन्दयोः	N;LOC;DU
तप	तपा	ADJ;NOM;FEM;SG
दोष	दोषान्	N;ACC;PL
जुहू	जुह्वः	N;VOC;PL
मध्यम	मध्यमाभ्याम्	ADJ;DAT;NEUT;DU
ऋत	ऋतस्य	N;GEN;SG
गुप्त	गुप्तानि	ADJ;ACC;NEUT;PL
बह्वृच	बह्वृच्यै	N;DAT;SG
नभ्य	नभ्य	N;VOC;SG
रसा	रसा	N;NOM;SG
प्रजा	प्रजायाम्	N;LOC;SG
गौड	गौडाभ्याम्	ADJ;INS;NEUT;DU
आद	आदात्	N;ABL;SG
मुख	मुखम्	N;ACC;SG
अक्तु	अक्तुना	N;INS;SG
महाकाव्य	महाकाव्याभ्याम्	N;ABL;DU
मधु	मधु	N;VOC;SG
मध्यम	मध्यमाभिः	ADJ;INS;FEM;PL
पठन	पठने	N;NOM;DU
प्रयत्न	प्रयत्नाय	N;DAT;SG
कारागार	कारागाराभ्याम्	N;ABL;DU
दीपिका	दीपिकाभ्यः	N;DAT;PL
चण्डाल	चण्डालाभ्याम्	N;DAT;DU
उद्गीथ	उद्गीथात्	N;ABL;SG
रसा	रसायाम्	N;LOC;SG
रसा	रसाः	N;VOC;PL
तप	तपे	ADJ;VOC;NEUT;DU
सोम	सोमाभिः	ADJ;INS;FEM;PL
अमित्र	अमित्रायाः	ADJ;ABL;FEM;SG
देवर	देवरौ	N;NOM;DU
अविक	अविकात्	N;ABL;SG
स्वर्ग	स्वर्गानि	ADJ;VOC;NEUT;PL
बल	बले	ADJ;ACC;FEM;DU
आखु	आक्ह्वाम्	N;LOC;SG
अङ्घ्रि	अङ्घ्रयः	N;NOM;PL
कपि	कपी	ADJ;NOM;MASC;DU
गौड	गौड्योः	ADJ;LOC;FEM;DU
दुग्ध	दुग्धयोः	ADJ;GEN;MASC;DU
पितृयाण	पितृयाणया	ADJ;INS;FEM;SG
उक्ति	उक्तीनाम्	N;GEN;PL
सर्पिणी	सर्पिणीभिः	N;INS;PL
सृष्टि	सृष्टयः	N;NOM;PL
प्रशस्ति	प्रशस्त्यै	N;DAT;SG
शारि	शारिभ्याम्	N;DAT;DU
मध्यम	मध्यमे	ADJ;ACC;NEUT;DU
साधारण	साधारणी	ADJ;NOM;SG
ध्वनि	ध्वन्योः	N;LOC;DU
अपरा	अपराभ्याम्	N;INS;DU
अविक	अविकाभ्याम्	N;DAT;DU
वृत्त	वृत्तैः	ADJ;INS;NEUT;PL
अरि	अरी	N;VOC;DU
स्वागम	स्वागमाः	N;VOC;PL
आकाश	आकाशेभ्यः	N;DAT;PL
अनुस्वार	अनुस्वाराय	N;DAT;SG
साहित्य	साहित्याभ्याम्	N;ABL;DU
भेषज	भेषजे	ADJ;LOC;NEUT;SG
नामन्	नामभ्यः	N;DAT;PL
ब्रह्म	ब्रह्माः	N;VOC;PL
अनार्य	अनार्याः	ADJ;NOM;FEM;PL
गाथ	गाथम्	N;ACC;SG
गञ्जा	गञ्जा	N;NOM;SG
वाहन	वाहनाभ्याम्	N;INS;DU
आम्र	आम्रात्	N;ABL;SG
मधु	मधुनी	N;ACC;DU
पवमान	पवमानम्	ADJ;NOM;NEUT;SG
नप्तृ	नप्तुः	N;ABL;SG
प्रथम	प्रथमयोः	ADJ;GEN;FEM;DU
इन्द्र	इन्द्र	N;VOC;SG
अक्षता	अक्षताभ्याम्	N;INS;DU
सुख	सुखे	ADJ;LOC;NEUT;SG
परा	पराभ्याम्	N;DAT;DU
वसन्त	वसन्तेभ्यः	N;DAT;PL
आवसथ्य	आवसथ्याभ्याम्	ADJ;INS;MASC;DU
अनुराग	अनुरागाभ्याम्	N;ABL;DU
अक्तु	अक्तून्	N;ACC;PL
पक्ष	पक्षेभ्यः	N;DAT;PL
केश	केशाभ्याम्	N;ABL;DU
पुरोहित	पुरोहितेभ्यः	ADJ;ABL;MASC;PL
परिवार	परिवाराः	N;NOM;PL
स्वस्ति	स्वस्तिनोः	N;LOC;DU
उद्गीथ	उद्गीथान्	N;ACC;PL
कपि	कपिभिः	ADJ;INS;MASC;PL
मल	मले	ADJ;ACC;NEUT;DU
बुध्न	बुध्नयोः	ADJ;LOC;FEM;DU
सुख	सुखाभिः	ADJ;INS;FEM;PL
सिंहल	सिंहलः	N;NOM;SG
ऋष्व	ऋष्वे	ADJ;LOC;MASC;SG
नड	नडाभ्याम्	N;INS;DU
श्याम	श्यामासु	ADJ;LOC;FEM;PL
भग	भगे	N;LOC;SG
आधार	आधाराय	N;DAT;SG
तर्का	तर्कायाम्	N;LOC;SG
द्रुम	द्रुमाः	N;VOC;PL
तप	तपाः	ADJ;VOC;FEM;PL
अविक	अविकाभ्याम्	N;INS;DU
चषक	चषकात्	N;ABL;SG
सर्पिणी	सर्पिण्यौ	N;NOM;DU
जानु	जानुनः	N;GEN;SG
तृण	तृणे	N;NOM;DU
प्रशस्ति	प्रशस्तिभ्यः	N;ABL;PL
उच्च	उच्च	ADJ;VOC;NEUT;SG
पण्यशाला	पण्यशालाभ्याम्	N;INS;DU
परिणाम	परिणामम्	N;ACC;SG
कालचक्र	कालचक्रात्	N;ABL;SG
अहि	अहे	N;VOC;SG
चकोर	चकोरौ	N;ACC;DU
रसभ	रसभेभ्यः	N;DAT;PL
पुराण	पुराणेषु	N;LOC;PL
कल्य	कल्या	ADJ;NOM;FEM;SG
सुख	सुखाभ्याम्	ADJ;DAT;NEUT;DU
स्वर्ग	स्वर्गम्	ADJ;NOM;NEUT;SG
व्याघ्र	व्याघ्राभ्याम्	N;ABL;DU
उच्च	उच्चम्	ADJ;NOM;NEUT;SG
कुटुम्ब	कुटुम्बे	N;ACC;DU
मनु	मनवः	ADJ;VOC;MASC;PL
भेषज	भेषजेन	ADJ;INS;NEUT;SG
सहित	सहिते	ADJ;LOC;MASC;SG
ऋष्व	ऋष्वाभ्याम्	ADJ;DAT;MASC;DU
विष	विषे	ADJ;LOC;MASC;SG
गोपाल	गोपाले	N;LOC;SG
अघ्न्या	अघ्न्ये	N;NOM;DU
कृष्ण	कृष्ण	ADJ;VOC;MASC;SG
गौड	गौडाः	ADJ;VOC;MASC;PL
अग	अगाः	N;VOC;PL
वाणिज	वाणिजाः	N;NOM;PL
अनुदात्त	अनुदात्ताम्	ADJ;ACC;FEM;SG
अबला	अबलाः	N;NOM;PL
पुराण	पुराणाभ्याम्	ADJ;ABL;DU
घोटक	घोटकौ	N;ACC;DU
रूपक	रूपकेभ्यः	ADJ;DAT;NEUT;PL
संदेश	संदेशैः	N;INS;PL
जानु	जानु	N;VOC;SG
स्वेद	स्वेदाभ्याम्	ADJ;DAT;FEM;DU
ग्रन्थ	ग्रन्थ	N;VOC;SG
शय्या	शय्यायाम्	N;LOC;SG
अनार्य	अनार्यात्	ADJ;ABL;NEUT;SG
प्राणायाम	प्राणायामौ	N;VOC;DU
वाहन	वाहनाभ्याम्	N;DAT;DU
अभाव	अभावे	N;LOC;SG
पुराण	पुराणेन	ADJ;INS;SG
व्रत	व्रतानि	N;ACC;PL
चूर्ण	चूर्णाभ्यः	ADJ;DAT;FEM;PL
देवदासी	देवदास्यः	N;VOC;PL
गरुड	गरुडान्	N;ACC;PL
मध्यम	मध्यमे	ADJ;VOC;FEM;SG
बाल	बालेन	N;INS;SG
निघण्टु	निघण्टुभ्याम्	N;DAT;DU
अग्नि	अग्निभिः	N;INS;PL
वाणिज	वाणिजाः	N;VOC;PL
पिप्पल	पिप्पलाभ्याम्	N;ABL;DU
संस्कार	संस्काराभ्याम्	N;INS;DU
अग	अगौ	N;ACC;DU
कल्य	कल्ये	ADJ;NOM;NEUT;DU
पाप	पापा	ADJ;DAT;SG
गौड	गौड्याम्	ADJ;LOC;FEM;SG
मुक्ति	मुक्तौ	N;LOC;SG
प्रार्थना	प्रार्थने	N;VOC;DU
सुन्दर	सुन्दरौ	N;ACC;DU
घोषक	घोषकाभ्याम्	N;INS;DU
आदिकाव्य	आदिकाव्याभ्याम्	N;ABL;DU
भण्टाकी	भण्टाक्याम्	N;LOC;SG
प्रशस्ति	प्रशस्तिम्	N;ACC;SG
संस्कृत	संस्कृताभ्याम्	ADJ;DAT;NEUT;DU
गाथ	गाथाभ्याम्	N;ABL;DU
पिप्पल	पिप्पलैः	N;INS;PL
कल्य	कल्यात्	ADJ;ABL;NEUT;SG
उक्त	उक्ते	ADJ;VOC;NEUT;DU
मनु	मनूनि	ADJ;NOM;NEUT;PL
पुरु	पूर्व्योः	ADJ;LOC;FEM;DU
व्याघ्र	व्याघ्रस्य	N;GEN;SG
स्वस्ति	स्वस्तिम्	N;ACC;SG
पुराण	पुराणे	ADJ;NOM;DU
कल्य	कल्याभ्याम्	ADJ;ABL;MASC;DU
जय	जयाभ्याम्	N;ABL;DU
योनि	योनिम्	N;ACC;SG
जन	जनीभ्याम्	ADJ;INS;FEM;DU
विश्पति	विश्पतीन्	N;ACC;PL
आश्रम	आश्रमैः	N;INS;PL
तर्कु	तर्कुभ्याम्	N;DAT;DU
कनीन	कनीनासु	ADJ;LOC;FEM;PL
हल	हले	N;LOC;SG
माया	मायायाम्	N;LOC;SG
ब्रह्मवेद	ब्रह्मवेदान्	N;ACC;PL
धूर्त	धूर्ताः	ADJ;VOC;FEM;PL
उदन्	उद	N;VOC;SG
भूर्ज	भूर्जौ	N;NOM;DU
अपरा	अपरासु	N;LOC;PL
मन्यु	मन्युना	N;INS;SG
निघण्टु	निघण्टुभ्याम्	N;INS;DU
विद्यापति	विद्यापतिना	N;INS;SG
दुग्ध	दुग्धेभ्यः	ADJ;ABL;MASC;PL
गुप्त	गुप्तयोः	ADJ;LOC;FEM;DU
चित्र	चित्रेभ्यः	N;ABL;PL
तल्प	तल्पः	N;NOM;SG
कल्य	कल्यानि	ADJ;NOM;NEUT;PL
बल	बलेभ्यः	ADJ;ABL;MASC;PL
अनुस्वार	अनुस्वारौ	N;VOC;DU
विद्याधरी	विद्याधर्योः	N;LOC;DU
विशाल	विशाल्यौ	ADJ;NOM;DU
संगीत	संगीताः	ADJ;VOC;FEM;PL
सूक्त	सूक्तेभ्यः	ADJ;ABL;MASC;PL
घटना	घटनाभ्यः	N;DAT;PL
जीवित	जीवितैः	ADJ;INS;NEUT;PL
न्यग्रोध	न्यग्रोधौ	N;ACC;DU
आर्य	आर्ययोः	ADJ;LOC;FEM;DU
नयन	नयनैः	N;INS;PL
स्वपू	स्वपूभ्यः	N;DAT;PL
शारि	शारेः	N;ABL;SG
गर्भ	गर्भौ	N;ACC;DU
पराजय	पराजयम्	N;ACC;SG
श्रमण	श्रमण्यः	ADJ;NOM;PL
गुप्त	गुप्तयोः	ADJ;GEN;NEUT;DU
क्षत्रिय	क्षत्रियेण	ADJ;INS;NEUT;SG
माया	मायाः	N;ACC;PL
कल	कलैः	ADJ;INS;NEUT;PL
चिन्तन	चिन्तनेन	N;INS;SG
स्वेद	स्वेदा	ADJ;DAT;NEUT;SG
कल	कलयोः	ADJ;LOC;FEM;DU
अक्तु	अक्तू	N;NOM;DU
आश्रम	आश्रमान्	N;ACC;PL
चतुरङ्ग	चतुरङगान्	ADJ;ACC;MASC;PL
रयि	रयेः	ADJ;GEN;FEM;SG
अग	अगात्	N;ABL;SG
दिग्नाग	दिग्नागाभ्याम्	N;ABL;DU
नाटक	नाटक	ADJ;VOC;NEUT;SG
पाप	पापौ	ADJ;NOM;DU
उच्च	उच्चाम्	ADJ;ACC;FEM;SG
स्वसृ	स्वसुः	N;GEN;SG
द्रुम	द्रुमेण	N;INS;SG
भ्रमर	भ्रमरौ	N;NOM;DU
वृष	वृषाः	N;NOM;PL
अभाव	अभावात्	N;ABL;SG
पाप	पापीभ्याम्	N;INS;DU
श्रामणेर	श्रामणेरेन	N;INS;SG
श्रवण	श्रवणाय	N;DAT;SG
कनीन	कनीनाभ्याम्	ADJ;ABL;MASC;DU
देश	देशेन	N;INS;SG
अक्षय	अक्षयम्	ADJ;ACC;NEUT;SG
चूर्ण	चूर्णे	ADJ;NOM;FEM;DU
वंश	वंशम्	N;NOM;SG
तीर	तीरौ	N;VOC;DU
वर्तनी	वर्तन्योः	N;LOC;DU
देवी	देव्याम्	N;LOC;SG
नाचिकेत	नाचिकेत्योः	ADJ;GEN;FEM;DU
अपभ्रंश	अपभ्रंशेभ्यः	N;DAT;PL
उक्त	उक्तायाः	ADJ;GEN;FEM;SG
भेषज	भेषजा	ADJ;DAT;NEUT;SG
पुराण	पुराण्याम्	ADJ;LOC;SG
निर्णय	निर्णयान्	N;ACC;PL
ग्राम	ग्राम	N;VOC;SG
प्रार्थना	प्रार्थनया	N;INS;SG
आति	आत्याः	N;ABL;SG
कारागार	कारागारेभ्यः	N;ABL;PL
मल	मलेभ्यः	ADJ;DAT;NEUT;PL
उदात्त	उदात्तेभ्यः	ADJ;DAT;MASC;PL
स्वरित	स्वरिते	ADJ;LOC;MASC;SG
अक्षय	अक्षयाभ्याम्	ADJ;ABL;NEUT;DU
ज्ञानकाण्ड	ज्ञानकाण्डम्	N;NOM;SG
गविष्टि	गविष्ट्यै	N;DAT;SG
स्नेह	स्नेहम्	N;ACC;SG
कर्म	कर्मे	N;NOM;DU
फल	फलाभ्याम्	N;INS;DU
प्रमन्थ	प्रमन्थाय	N;DAT;SG
पार्वण	पार्वणे	ADJ;NOM;NEUT;DU
अनुवाद	अनुवादम्	N;ACC;SG
बल	बला	ADJ;NOM;FEM;SG
विद्याचण	विद्याचणायै	ADJ;DAT;FEM;SG
घोष	घोषाभ्याम्	N;DAT;DU
दर्शपूर्णमास	दर्शपूर्णमासौ	N;ACC;DU
राज्य	राज्ययोः	ADJ;LOC;NEUT;DU
वारि	वारिणोः	N;LOC;DU
मल	मल	ADJ;VOC;NEUT;SG
अक्षि	अक्षीणी	N;ACC;PL
ध्वनि	ध्वने	N;VOC;SG
क्षत्रिय	क्षत्रियौ	ADJ;NOM;MASC;DU
समुद्र	समुद्रात्	N;ABL;SG
विद्यापति	विद्यापत्योः	N;LOC;DU
जीवित	जीवितयोः	ADJ;LOC;FEM;DU
साधारण	साधारणीम्	ADJ;ACC;SG
कल	कलात्	ADJ;ABL;NEUT;SG
मृगतृष्णा	मृगतृष्णे	N;VOC;DU
तंतुवाय	तंतुवायाः	N;VOC;PL
तंतुवाय	तंतुवायेषु	N;LOC;PL
क्षत्र	क्षत्रम्	N;ACC;SG
मरु	मरुभ्याम्	N;DAT;DU
पितृयज्ञ	पितृयज्ञाभ्याम्	N;ABL;DU
अमित्र	अमित्रे	ADJ;VOC;NEUT;DU
क्षत्र	क्षत्राभ्याम्	N;DAT;DU
आर्ष	आर्षेभ्यः	ADJ;DAT;NEUT;PL
हेतु	हेतुभ्यः	N;DAT;PL
पाप	पापम्	ADJ;NOM;SG
गञ्जा	गञ्जासु	N;LOC;PL
ओषधि	ओषध्या	N;INS;SG
कल्य	कल्येभ्यः	ADJ;ABL;NEUT;PL
उक्थ	उक्थाभ्याम्	N;INS;DU
क्षत्रिय	क्षत्रियेषु	ADJ;LOC;MASC;PL
भारत	भारतीम्	ADJ;ACC;FEM;SG
दर्शपूर्णमास	दर्शपूर्णमासेभ्यः	N;ABL;PL
निष्ठा	निष्ठाभिः	N;INS;PL
सत्त्र	सत्त्रानि	N;VOC;PL
अभय	अभयेभ्यः	N;DAT;PL
बह्वृच	बह्वृच्या	N;INS;SG
क्षत्रिय	क्षत्रियः	ADJ;NOM;MASC;SG
मनु	मनुभ्याम्	ADJ;ABL;FEM;DU
प्रहसन	प्रहसनम्	N;ACC;SG
अमित्र	अमित्राम्	ADJ;ACC;FEM;SG
अकृत्य	अकृत्याभ्याम्	N;DAT;DU
ज्या	ज्यायै	N;DAT;SG
ब्रह्म	ब्रह्मेण	N;INS;SG
शलभ	शलभे	N;LOC;SG
अन्त	अन्तः	N;NOM;SG
आवसथ्य	आवसथ्या	ADJ;NOM;FEM;SG
दक्षिण	दक्षिणेभ्यः	ADJ;DAT;NEUT;PL
दुर्जन	दुर्जनानि	ADJ;ACC;NEUT;PL
गौड	गौडात्	ADJ;ABL;MASC;SG
नारायण	नारायणाभ्याम्	ADJ;ABL;MASC;DU
अगार	अगारैः	N;INS;PL
आवसथ्य	आवसथ्येषु	ADJ;LOC;NEUT;PL
रूपक	रूपकायै	ADJ;DAT;FEM;SG
देवी	देवीभ्याम्	N;INS;DU
मध्यम	मध्यमाभ्याम्	ADJ;INS;NEUT;DU
अश्रि	अश्रिभ्याम्	N;DAT;DU
बह्वृच	बह्वृचेभ्यः	ADJ;ABL;PL
गिरिका	गिरिके	N;VOC;DU
मुद्रा	मुद्रे	N;VOC;DU
विहार	विहारेभ्यः	N;DAT;PL
मध्यम	मध्यमयोः	ADJ;GEN;FEM;DU
संगीत	संगीतानाम्	ADJ;GEN;FEM;PL
उदात्त	उदात्ते	ADJ;NOM;NEUT;DU
विद्याचण	विद्याचण	ADJ;VOC;NEUT;SG
घोष	घोषेभ्यः	N;DAT;PL
चाप	चापाभ्याम्	N;DAT;DU
माया	मायानाम्	N;GEN;PL
प्रताप	प्रतापे	N;LOC;SG
आदिकाव्य	आदिकाव्ये	N;NOM;DU
कर्पर	कर्परस्य	N;GEN;SG
सहित	सहिते	ADJ;NOM;NEUT;DU
साधारण	साधारणाः	ADJ;ACC;PL
बहुव्रीहि	बहुव्रीह्योः	ADJ;GEN;FEM;DU
शारि	शारिभ्याम्	N;INS;DU
मृगतृष्णा	मृगतृष्णाभ्यः	N;ABL;PL
धूर्त	धूर्ताः	ADJ;VOC;MASC;PL
चिन्तन	चिन्तना	N;DAT;SG
उदन्	उदनी	N;NOM;DU
नाथ	नाथानि	ADJ;VOC;MASC;PL
कल	कले	ADJ;VOC;FEM;DU
पवमान	पवमाने	ADJ;VOC;FEM;SG
वृत्र	वृत्रम्	N;ACC;SG
मृध	मृधौ	N;ACC;DU
शरीर	शरीराभ्याम्	N;DAT;DU
आवास	आवासानाम्	N;GEN;PL
भेषज	भेषज्याम्	ADJ;LOC;FEM;SG
रूपक	रूपकैः	ADJ;INS;MASC;PL
राज्ञी	राज्ञ्योः	N;GEN;DU
रूपक	रूपकैः	ADJ;INS;NEUT;PL
पुलस्ति	पुलस्ती	ADJ;NOM;MASC;DU
पूर	पूराणि	ADJ;NOM;NEUT;PL
इतिहास	इतिहासानाम्	N;GEN;PL
विपक्ष	विपक्षे	ADJ;LOC;NEUT;SG
नप्तृ	नप्तृषु	N;LOC;PL
चूर्ण	चूर्णयोः	ADJ;LOC;NEUT;DU
प्रथम	प्रथमयोः	ADJ;GEN;MASC;DU
पार्वण	पार्वण्यै	ADJ;DAT;FEM;SG
व्याघ्र	व्याघ्राभ्याम्	N;DAT;DU
मलिक	मलिकैः	N;INS;PL
पेशी	पेशीभ्याम्	N;ABL;DU
क्षत्र	क्षत्रयोः	N;GEN;DU
कपि	कपि	ADJ;VOC;FEM;SG
अंश	अंशस्य	N;GEN;SG
गुण	गुणाः	N;VOC;PL
अक्तु	अक्तोः	N;ABL;SG
मधु	मधुभ्याम्	N;DAT;DU
विराम	विरामौ	N;ACC;DU
जीवन्मुक्ति	जिवन्मुक्तौ	N;LOC;SG
संहिता	संहिताभिः	N;INS;PL
ईशान	ईशानेभ्यः	ADJ;DAT;NEUT;PL
पुलस्ति	पुलस्तिषु	ADJ;LOC;FEM;PL
जाङ्गल	जाङ्गलौ	ADJ;ACC;MASC;DU
पुरोहित	पुरोहितायाम्	ADJ;LOC;FEM;SG
पुरंधि	पुरंधिभ्याम्	ADJ;INS;FEM;DU
श्रवण	श्रवणानाम्	N;GEN;PL
विरा	विराः	N;VOC;PL
मषि	मषिम्	N;ACC;SG
यक्ष	यक्षे	N;ACC;DU
देवदासी	देवदासीभ्याम्	N;INS;DU
कर्पर	कर्परैः	N;INS;PL
पृदाकु	पृदाकू	N;ACC;DU
यक्ष	यक्षानि	N;VOC;PL
मठ	मठात्	N;ABL;SG
नामकरण	नामकरणैः	N;INS;PL
निष्ठा	निष्ठे	N;VOC;DU
देव	देवाभ्याम्	N;INS;DU
रसभ	रसभेभ्यः	N;ABL;PL
उद्गूर्ण	उद्गूर्णाभ्याम्	ADJ;DAT;FEM;DU
स्वस्ति	स्वस्ती	N;VOC;DU
मनस्	मनसोः	N;GEN;DU
मुरली	मुरल्याम्	N;LOC;SG
ध्वनि	ध्वनिभ्यः	N;ABL;PL
होतृ	होतृभ्यः	N;ABL;PL
अजिर	अजिराणाम्	ADJ;GEN;NEUT;PL
सिंहपुर	सिंहपुराभ्याम्	N;ABL;DU
कपि	कप्यौ	ADJ;VOC;FEM;DU
कृष्ण	कृष्णैः	ADJ;INS;NEUT;PL
मृदु	मृद्व्याम्	ADJ;LOC;SG
कल्य	कल्ययोः	ADJ;GEN;FEM;DU
जय	जयैः	N;INS;PL
पुरोहित	पुरोहिताः	ADJ;NOM;MASC;PL
विशाल	विशालः	ADJ;NOM;SG
उक्त	उक्तेषु	ADJ;LOC;NEUT;PL
जाङ्गल	जाङ्गलस्य	ADJ;GEN;MASC;SG
काण्ड	काण्डान्	N;ACC;PL
अद्वैत	अद्वैतानाम्	ADJ;GEN;NEUT;PL
स्नातक	स्नातकौ	N;NOM;DU
दृढ	दृढे	N;ACC;DU
पण्डित	पण्डिताः	ADJ;VOC;FEM;PL
साधारण	साधारणीभ्यः	ADJ;ABL;PL
प्रथम	प्रथमाभ्यः	ADJ;ABL;FEM;PL
अभाव	अभावैः	N;INS;PL
कपि	कपीषु	ADJ;LOC;FEM;PL
पर्कटी	पर्कट्या	N;INS;SG
ध्वनि	ध्वनयः	N;NOM;PL
प्राणायाम	प्राणायामेन	N;INS;SG
तर्का	तर्के	N;VOC;DU
पार्वण	पार्वणानाम्	ADJ;GEN;MASC;PL
पुरु	पुरुणः	ADJ;ABL;NEUT;SG
किशोर	किशोरेभ्यः	N;DAT;PL
गौड	गौडेषु	ADJ;LOC;NEUT;PL
स्वश्व	स्वश्वाभ्याम्	ADJ;INS;NEUT;DU
पुराण	पुराणि	ADJ;VOC;SG
अकर्मन्	अकर्मभ्यः	N;ABL;PL
सिद्ध	सिद्धानाम्	ADJ;GEN;NEUT;PL
दर्शपूर्णमास	दर्शपूर्णमासेभ्यः	N;DAT;PL
गौड	गौडेभ्यः	ADJ;DAT;MASC;PL
भ्रमर	भ्रमराभ्याम्	N;ABL;DU
पृदाकु	पृदाकुः	N;NOM;SG
आति	आती	N;ACC;DU
यातु	यातू	N;ACC;DU
अन्त	अन्तानाम्	N;GEN;PL
सत्त्र	सत्त्रानि	N;ACC;PL
पण्डित	पण्डिते	ADJ;LOC;NEUT;SG
भ्राता	भ्राता	N;NOM;SG
पितृयज्ञ	पितृयज्ञः	N;NOM;SG
नाटक	नाटकेभ्यः	ADJ;DAT;MASC;PL
मूल्य	मूल्यानि	ADJ;VOC;NEUT;PL
विष्णु	विषणूः	N;ACC;PL
पुत्र	पुत्र	N;VOC;SG
सुजित	सुजिते	N;LOC;SG
कर्पर	कर्परौ	N;VOC;DU
देवभाषा	देवभाषाभ्यः	N;DAT;PL
अन्त	अन्तौ	N;NOM;DU
पठन	पठनम्	N;NOM;SG
विपक्ष	विपक्षासु	ADJ;LOC;FEM;PL
विष्कम्भ	विष्कम्भानाम्	N;GEN;PL
श्रमण	श्रमणीः	ADJ;ACC;PL
पण्डित	पण्डिताम्	ADJ;ACC;FEM;SG
उखा	उखानाम्	N;GEN;PL
दुर्जन	दुर्जनाम्	ADJ;ACC;FEM;SG
भारतवर्ष	भारतवर्षे	N;LOC;SG
परिमाण	परिमाणे	N;NOM;DU
पर्जन्य	पर्जन्ययोः	N;LOC;DU
भर्ग	भर्गे	N;LOC;SG
अन्त	अन्तेभ्यः	N;ABL;PL
क्षति	क्षत्याः	N;GEN;SG
रूपक	रूपकाः	ADJ;NOM;MASC;PL
बहुव्रीहि	बहुव्रीहीनि	ADJ;VOC;NEUT;PL
काण्ड	काण्डौ	N;VOC;DU
श्याम	श्यामायै	ADJ;DAT;FEM;SG
अमृता	अमृताः	N;NOM;PL
अमित्र	अमित्राः	ADJ;VOC;FEM;PL
राज्ञी	राज्ञीः	N;ACC;PL
आखु	आक्ह्वोः	N;LOC;DU
मल	मलयोः	ADJ;LOC;FEM;DU
आखु	आक्हो	N;VOC;SG
वृत्र	वृत्राः	N;NOM;PL
बह्वृच	बह्वृचानि	ADJ;VOC;PL
अमित्र	अमित्रात्	ADJ;ABL;NEUT;SG
जाति	जातिः	N;NOM;SG
परिणय	परिणयानाम्	N;GEN;PL
गुण	गुणाभ्याम्	N;DAT;DU
द्वेष	द्वेषेषु	N;LOC;PL
दुग्ध	दुग्धयोः	ADJ;GEN;NEUT;DU
कितव	कितवात्	N;ABL;SG
धूर्त	धूर्तः	ADJ;NOM;MASC;SG
तप	तपया	ADJ;INS;FEM;SG
वाणिज	वाणिजयोः	N;LOC;DU
पुरु	पूर्वीभ्याम्	ADJ;DAT;FEM;DU
पुराण	पुराणैः	ADJ;INS;PL
मरु	मरुषु	N;LOC;PL
