көҙгө	көҙгөнән	ADJ;ABL;SG
кендек	кендектәргә	N;DAT;PL
талап	талаптарҙы	N;ACC;DEF;PL
йәшәйеш	йәшәйеште	N;ACC;DEF;SG
эйәр	эйәрләрҙе	N;ACC;DEF;PL
адрес	адреста	N;LOC;SG
ҡоҙғон	ҡоҙғондарҙың	N;GEN;DEF;PL
йүнәлеш	йүнәлештәргә	N;DAT;PL
бесән	бесәндең	N;GEN;DEF;SG
аҡбур	аҡбур	N;DAT;SG
ҡулаҡса	ҡулаҡсаларҙан	N;ABL;PL
таң	таңдың	N;GEN;DEF;SG
миҫал	миҫалды	N;ACC;DEF;SG
бөҙрә	бөҙрәләрҙе	N;ACC;DEF;PL
ҡылым	ҡылымды	N;ACC;DEF;SG
айғыр	айғырҙарҙан	N;ABL;PL
мейе	мейелә	N;LOC;SG
кендек	кендектә	N;LOC;SG
тәжрибә	тәжрибә	N;GEN;DEF;PL
күргәҙмә	күргәҙмәне	N;ACC;DEF;SG
йоҙроҡ	йоҙроҡтарҙың	N;GEN;DEF;PL
сөй	сөйҙәрҙең	N;GEN;DEF;PL
һырға	һырғанан	N;ABL;SG
дәүләт	дәүләттәргә	N;DAT;PL
һандуғас	һандуғаста	N;LOC;SG
ғибәҙәтхана	ғибәҙәтхананы	N;ACC;DEF;SG
гәүһәр	гәүһәр	N;NOM;SG
тантана	тантаналарҙа	N;LOC;PL
мөгөҙ	мөгөҙҙө	N;ACC;DEF;SG
дарыухана	дарыуханаға	N;DAT;SG
ярымутрау	ярымутрауҙарға	N;DAT;PL
шарт	шарттарҙа	N;LOC;PL
әхирәт	әхирәттәр	N;NOM;PL
ғөрөф-ғәҙәт	ғөрөф-ғәҙәттәрҙән	N;ABL;PL
фил	фил	N;GEN;DEF;PL
төрткө	төрткөнән	N;ABL;SG
фәлсәфә	фәлсәфәләр	N;NOM;PL
һыйыр	һыйырға	N;DAT;SG
тамашасы	тамашасыларға	N;DAT;PL
баҡсасы	баҡсасыларҙың	N;GEN;DEF;PL
бүләк	бүләктәрҙән	N;ABL;PL
тәҡдим	тәҡдим	N;ACC;DEF;SG
тәгәрмәс	тәгәрмәстең	N;GEN;DEF;SG
ауыҙ	ауыҙ	N;NOM;SG
үҫмер	үҫмерҙең	N;GEN;DEF;SG
бесәй	бесәйҙе	N;ACC;DEF;SG
буйҙаҡ	буйҙаҡтарҙан	N;ABL;PL
бөҙрә	бөҙрәләрҙән	N;ABL;PL
кәүҙә	кәүҙәләрҙең	N;GEN;DEF;PL
энә	энәне	N;ACC;DEF;SG
сәғәт	сәғәттәрҙең	N;GEN;DEF;PL
ярымутрау	ярымутрауҙа	N;LOC;SG
йәрминкә	йәрминкә	N;ACC;DEF;SG
атай	атайҙарҙа	N;LOC;PL
тәсбих	тәсбих	N;NOM;PL
күргәҙмә	күргәҙмәнән	N;ABL;SG
һандуғас	һандуғасҡа	N;DAT;SG
иғтибар	иғтибар	N;NOM;SG
сифат	сифатта	N;LOC;SG
поезд	поездтың	N;GEN;DEF;SG
пәрҙә	пәрҙәләр	N;NOM;PL
күбәләк	күбәләк	N;NOM;SG
милли көрәш	милли көрәштә	N;LOC;SG
әшнә	әшнәнән	N;ABL;SG
бишек	бишектәрҙең	N;GEN;DEF;PL
көҙгө	көҙгөләрҙе	ADJ;ACC;DEF;PL
һөҙөмтә	һөҙөмтә	N;ABL;SG
хоҡуҡ	хоҡуҡ	N;GEN;DEF;SG
кисә	кисә	N;ACC;DEF;PL
һауыт-һаба	һауыт-һабалар	N;NOM;PL
тубыҡ	тубыҡтың	N;GEN;DEF;SG
тиҫтә	тиҫтә	N;NOM;SG
тәҡдир	тәҡдир	N;ACC;DEF;PL
ғибәҙәтхана	ғибәҙәтханаларҙан	N;ABL;PL
һал	һал	N;NOM;SG
йәйғор	йәйғорҙа	N;LOC;SG
ғәҙәт	ғәҙәттәргә	N;DAT;PL
йәшен	йәшендәр	N;NOM;PL
татыулыҡ	татыулыҡтың	N;GEN;DEF;SG
эт	эткә	N;DAT;SG
журнал	журналдар	N;NOM;PL
хәреф	хәрефтәрҙе	N;ACC;DEF;PL
аҙаш	аҙаштан	N;ABL;SG
көрәш	көрәш	N;NOM;SG
миләүшә	миләүшәгә	N;DAT;SG
ҡыуаҡ	ҡыуаҡты	N;ACC;DEF;SG
мәйет	мәйеткә	N;DAT;SG
таң	таңдарҙың	N;GEN;DEF;PL
йәйғор	йәйғорға	N;DAT;SG
кафыр	кафырҙарға	N;DAT;PL
ҡабырға	ҡабырға	N;NOM;PL
өлгө	өлгө	N;NOM;SG
эҙ	эҙ	N;LOC;SG
киле	киленең	N;GEN;DEF;SG
ҡул	ҡул	N;NOM;PL
көсөк	көсөктәр	N;NOM;PL
миҙгел	миҙгелдәрҙән	N;ABL;PL
сара	сараның	N;GEN;DEF;SG
тамыр	тамыр	N;NOM;SG
сиркәү	сиркәүҙәр	ADJ;NOM;PL
туй	туй	N;ACC;DEF;PL
Буға	Буғаны	N;ACC;DEF;SG
һаҙағай	һаҙағайҙың	N;GEN;DEF;SG
әтәс	әтәстә	N;LOC;SG
каса	каса	N;NOM;SG
бәшмәк	бәшмәктәрҙән	N;ABL;PL
алмағас	алмағасҡа	N;DAT;SG
дин	дин	N;LOC;PL
өлкә	өлкәнән	N;ABL;SG
ҡар	ҡарҙарҙы	N;ACC;DEF;PL
кафыр	кафырҙа	N;LOC;SG
тырнаҡ	тырнаҡтан	N;ABL;SG
ирлән	ирләндәрҙең	N;GEN;DEF;PL
татыулыҡ	татыулыҡтарҙы	N;ACC;DEF;PL
йәйғор	йәйғорҙарҙы	N;ACC;DEF;PL
рәссам	рәссамдан	N;ABL;SG
батмус	батмус	N;LOC;PL
энә	энәлә	N;LOC;SG
ҡайыш	ҡайыш	N;NOM;SG
баҡсасы	баҡсасының	N;GEN;DEF;SG
шаршау	шаршауҙа	N;LOC;SG
һандыҡ	һандыҡ	N;NOM;SG
керпек	керпектәр	N;NOM;PL
урта	урталарҙан	N;ABL;PL
сәйнүк	сәйнүк	N;NOM;PL
йома	йома	N;NOM;SG
айғыр	айғыр	N;NOM;SG
һауыт	һауытта	N;LOC;SG
көрәш	көрәштәрҙән	N;ABL;PL
былбыл	былбылға	N;DAT;SG
упҡын	упҡында	N;LOC;SG
кафыр	кафырға	N;DAT;SG
буранка	буранка	N;NOM;SG
ужым	ужым	N;NOM;SG
ахырызаман	ахырызаманларҙа	N;LOC;PL
тырнаҡ	тырнаҡтар	N;NOM;PL
ҙурлыҡ	ҙурлыҡтарҙың	N;GEN;DEF;PL
әйбер	әйберләргә	N;DAT;PL
тышау	тышауҙарҙы	N;ACC;DEF;PL
әңгәмә	әңгәмә	N;LOC;SG
арпа	арпаның	N;GEN;DEF;SG
балға	балғаға	N;DAT;SG
таҡырбаш	таҡырбаштың	N;GEN;DEF;SG
бысаҡ	бысаҡтарҙың	N;GEN;DEF;PL
майҙансыҡ	майҙансыҡтарҙың	N;GEN;DEF;PL
буш ваҡыт	буш ваҡытты	N;ACC;DEF;SG
торлаҡ	торлаҡтан	N;ABL;SG
бесәй	бесәй	N;NOM;SG
һуғыш	һуғыштан	N;ABL;SG
тамға	тамғаларҙа	N;LOC;PL
буйҙаҡ	буйҙаҡты	ADJ;ACC;DEF;SG
заман	замандарҙы	N;ACC;DEF;PL
шаһит	шаһит	N;LOC;PL
еҫ	еҫте	N;ACC;DEF;SG
күстәнәс	күстәнәстең	N;GEN;DEF;SG
тире	тирегә	N;DAT;SG
тупраҡ	тупраҡҡа	N;DAT;SG
йүкә	йүкәнең	N;GEN;DEF;SG
аждаһа	аждаһаны	N;ACC;DEF;SG
тәгәрмәс	тәгәрмәстәрҙе	N;ACC;DEF;PL
итәк	итәктән	N;ABL;SG
тамсы	тамсы	N;NOM;SG
ҡылым	ҡылымдың	N;GEN;DEF;SG
һәнәк	һәнәк	N;NOM;SG
дилбегә	дилбегәләрҙең	N;GEN;DEF;PL
ҡош-ҡорт	ҡош-ҡорттан	N;ABL;SG
сүл	сүл	N;ABL;SG
тауыш	тауыштан	N;ABL;SG
өҙәңге	өҙәңгенең	N;GEN;DEF;SG
туй	туй	N;GEN;DEF;SG
кеҫә	кеҫәләрҙе	N;ACC;DEF;PL
беләҙек	беләҙектәр	N;NOM;PL
тауыш	тауыштарҙан	N;ABL;PL
дауыл	дауылдарҙы	N;ACC;DEF;PL
йөкмәтке	йөкмәткенең	N;GEN;DEF;SG
баҡсасы	баҡсасыла	N;LOC;SG
ялан	яландар	N;NOM;PL
миләш	миләштәрҙе	N;ACC;DEF;PL
һөңгө	һөңгөлә	N;LOC;SG
елкән	елкәндәрҙә	N;LOC;PL
хәйер	хәйерҙәрҙән	N;ABL;PL
мунса	мунсала	N;LOC;SG
гөл	гөлләргә	N;DAT;PL
һейҙек	һейҙектән	N;ABL;SG
бөрсә	бөрсәләрҙән	N;ABL;PL
дуҫлыҡ	дуҫлыҡтан	N;ABL;SG
һәүәҫкәр	һәүәҫкәрҙәрҙә	N;LOC;PL
ришүәтсе	ришүәтсенең	N;GEN;DEF;SG
ҡарғыш	ҡарғышты	N;ACC;DEF;SG
йәкшәмбе	йәкшәмбене	N;ACC;DEF;SG
ялыу	ялыуҙы	N;ACC;DEF;SG
сеймал	сеймалдан	N;ABL;SG
ғибәҙәт	ғибәҙәттәрҙән	N;ABL;PL
яуап	яуапҡа	N;DAT;SG
үҫемлек	үҫемлектең	N;GEN;DEF;SG
уҡытыусы	уҡытыусыларҙың	N;GEN;DEF;PL
ҡанат	ҡанаттарҙы	N;ACC;DEF;PL
йәшен	йәшен	N;NOM;SG
сусҡа	сусҡа	N;NOM;SG
он	ондо	N;ACC;DEF;SG
сәбәп	сәбәптәрҙе	N;ACC;DEF;PL
йоҙроҡ	йоҙроҡтарға	N;DAT;PL
дәүләт	дәүләтте	N;ACC;DEF;SG
теркәүес	теркәүестәрҙә	N;LOC;PL
шишәмбе	шишәмбеләрҙә	N;LOC;PL
шағир	шағирҙың	N;GEN;DEF;SG
төп	төптә	N;LOC;SG
башҡала	башҡалалар	N;NOM;PL
ужым	ужымдың	N;GEN;DEF;SG
урта	урталарҙы	N;ACC;DEF;PL
ҡарлуғас	ҡарлуғастарҙа	N;LOC;PL
сәңгелдәк	сәңгелдәкте	N;ACC;DEF;SG
һыҙыҡ	һыҙыҡтан	N;ABL;SG
йөн	йөндә	N;LOC;SG
йылҡы	йылҡынан	N;ABL;SG
аҙаш	аҙашты	ADJ;ACC;DEF;SG
тантана	тантаналарҙы	N;ACC;DEF;PL
упҡын	упҡындарҙа	N;LOC;PL
халыҡ	халыҡтың	N;GEN;DEF;SG
тәжрибә	тәжрибә	N;ACC;DEF;PL
килеш	килештәрҙе	N;ACC;DEF;PL
таҡта	таҡтала	N;LOC;SG
сифат	сифат	N;NOM;SG
ҡәләмфер	ҡәләмферҙән	N;ABL;SG
ҡылым	ҡылым	N;NOM;SG
аҡҡош	аҡҡоштарға	N;DAT;PL
яуаплылыҡ	яуаплылыҡ	N;NOM;SG
хәйер	хәйер	N;NOM;SG
баҙар	баҙар	N;NOM;SG
даирә	даирәләрҙең	N;GEN;DEF;PL
тәҙрә	тәҙрәләрҙең	N;GEN;DEF;PL
йүгән	йүгәнгә	N;DAT;SG
башватҡыс	башватҡысты	N;ACC;DEF;SG
редакция	редакцияларҙан	N;ABL;PL
бойондороҡһоҙлоҡ	бойондороҡһоҙлоҡтарҙа	N;LOC;PL
һум	һум	N;ACC;DEF;SG
тол	толдарға	N;DAT;PL
белешмә	белешмәнән	N;ABL;SG
тараф	тарафтарҙың	N;GEN;DEF;PL
уғры	уғрыларҙың	N;GEN;DEF;PL
игеҙәк	игеҙәктәргә	N;DAT;PL
буйҙаҡ	буйҙаҡта	ADJ;LOC;SG
тау	тауҙарҙың	N;GEN;DEF;PL
ялан	яландарҙы	N;ACC;DEF;PL
кейеҙ	кейеҙгә	N;DAT;SG
маңлай	маңлайҙы	N;ACC;DEF;SG
йүкә	йүкәләрҙе	N;ACC;DEF;PL
сиркәү	сиркәүҙә	ADJ;LOC;SG
алҡа	алҡаларға	N;DAT;PL
ожмах	ожмахтарға	N;DAT;PL
урынбаҫар	урынбаҫарҙы	N;ACC;DEF;SG
баҫым	баҫымда	N;LOC;SG
ураҡ	ураҡтарҙы	N;ACC;DEF;PL
мөйөш	мөйөштә	N;LOC;SG
баш мәҡәлә	баш мәҡәләнән	N;ABL;SG
ҡатын	ҡатында	N;LOC;SG
өмөт	өмөттөң	N;GEN;DEF;SG
ҡатын	ҡатынға	N;DAT;SG
мәйет	мәйеттәрҙе	N;ACC;DEF;PL
бәхет	бәхеттән	N;ABL;SG
бурыс	бурыстарҙан	N;ABL;PL
тамыр	тамырҙарҙан	N;ABL;PL
кейем	кейемдәрҙең	N;GEN;DEF;PL
бура	бураны	N;ACC;DEF;SG
һәйкәл	һәйкәл	N;NOM;SG
иҙән	иҙәндәрҙе	N;ACC;DEF;PL
кәзә	кәзәнән	N;ABL;SG
емтек	емтеккә	N;DAT;SG
ҡауырһын	ҡауырһындан	N;ABL;SG
өлгө	өлгөнө	N;ACC;DEF;SG
нәшриәт	нәшриәттәрҙән	N;ABL;PL
төрткө	төрткө	N;NOM;SG
борос	боросто	N;ACC;DEF;SG
нур	нур	N;ABL;SG
гөл	гөлгә	N;DAT;SG
мөхәббәт	мөхәббәт	N;NOM;SG
һаҡал	һаҡалдарҙан	N;ABL;PL
йүтәл	йүтәлдә	N;LOC;SG
сер	серҙәрҙең	N;GEN;DEF;PL
ауыл	ауылдарҙың	ADJ;GEN;DEF;PL
кейеҙ	кейеҙҙе	N;ACC;DEF;SG
әхирәт	әхирәттә	N;LOC;SG
йүнәлеш	йүнәлештә	N;LOC;SG
гәүһәр	гәүһәрҙәргә	N;DAT;PL
дөйә	дөйәләргә	N;DAT;PL
әҙәбиәт	әҙәбиәткә	N;DAT;SG
ҡылыс	ҡылыстарға	N;DAT;PL
сәйнүк	сәйнүк	N;DAT;PL
терегөмөш	терегөмөштөң	N;GEN;DEF;SG
фәрештә	фәрештәләрҙә	N;LOC;PL
бәлә	бәләнән	N;ABL;SG
белешмә	белешмәләрҙә	N;LOC;PL
һәйкәл	һәйкәлдәрҙән	N;ABL;PL
мунса	мунсанан	N;ABL;SG
һуған	һуғандан	N;ABL;SG
ауырыу	ауырыуҙан	N;ABL;SG
ҡыпсыуыр	ҡыпсыуыр	N;NOM;SG
батыр	батырҙарға	N;DAT;PL
үпкә	үпкә	N;NOM;PL
һарай	һарайлар	N;NOM;PL
хөрәфәт	хөрәфәткә	N;DAT;SG
егет	егет	N;NOM;SG
әжәл	әжәлдәр	N;NOM;PL
ярғанат	ярғанаттарҙа	N;LOC;PL
Уҡсы	Уҡсылар	N;NOM;PL
орсоҡ	орсоҡтар	N;NOM;PL
мейес	мейестән	N;ABL;SG
рәхмәт	рәхмәттә	N;LOC;SG
туфан	туфанды	N;ACC;DEF;SG
шәл	шәлдәрҙә	N;LOC;PL
һарай	һарай	N;NOM;SG
дәрес	дәрестең	N;GEN;DEF;SG
төп	төптәрҙән	N;ABL;PL
яҙ	яҙ	N;NOM;SG
һөйкәлеш	һөйкәлештән	N;ABL;SG
шырпы	шырпы	N;NOM;SG
шәреҡ	шәреҡкә	N;DAT;SG
ирекмән	ирекмәнгә	N;DAT;SG
ярҙамсы	ярҙамсыны	N;ACC;DEF;SG
юлдаш	юлдашта	N;LOC;SG
саған	сағандарға	N;DAT;PL
сәйнүк	сәйнүк	N;GEN;DEF;SG
ярҙамсы	ярҙамсы	N;NOM;SG
еләк	еләк	N;NOM;SG
һөйәк	һөйәк	N;NOM;SG
айыу	айыуҙы	N;ACC;DEF;SG
теркәүес	теркәүестә	N;LOC;SG
ваҡыт	ваҡытта	N;LOC;SG
имсәк	имсәктәрҙән	N;ABL;PL
миҫал	миҫалға	N;DAT;SG
тирмәнсе	тирмәнсенән	N;ABL;SG
уйын	уйындарға	N;DAT;PL
суйын	суйында	N;LOC;SG
һүҙ	һүҙ	N;ACC;DEF;SG
йәй	йәйҙең	N;GEN;DEF;SG
ай	айҙан	N;ABL;SG
тоҡсай	тоҡсайға	N;DAT;SG
фән	фәнде	N;ACC;DEF;SG
сифат	сифаттарға	N;DAT;PL
һаҡал	һаҡалдан	N;ABL;SG
ташбаҡа	ташбаҡаны	N;ACC;DEF;SG
еләк	еләктең	N;GEN;DEF;SG
салғы	салғыларҙа	N;LOC;PL
урам	урамды	N;ACC;DEF;SG
бәхет	бәхеттәрҙең	N;GEN;DEF;PL
көй	көйҙәрҙән	N;ABL;PL
хыял	хыялдарҙа	N;LOC;PL
ахырызаман	ахырызаманла	N;LOC;SG
мейес	мейесте	N;ACC;DEF;SG
көрәк	көрәктәрҙән	N;ABL;PL
һыйыр	һыйырҙарҙан	N;ABL;PL
баш	баштар	N;NOM;PL
урта быуат	урта быуаттың	ADJ;GEN;DEF;SG
ҡорос	ҡоростан	N;ABL;SG
уйын	уйындарҙа	N;LOC;PL
урта	урталарҙың	N;GEN;DEF;PL
бөрсә	бөрсәне	N;ACC;DEF;SG
ҡала	ҡалаларға	N;DAT;PL
светофор	светофорҙарға	N;DAT;PL
даға	дағаларҙың	N;GEN;DEF;PL
йоҙроҡ	йоҙроҡтан	N;ABL;SG
ваҡиға	ваҡиғаға	N;DAT;SG
шәреҡ	шәреҡтә	N;LOC;SG
ҡоро ер	ҡоро ерҙән	N;ABL;SG
мәйет	мәйеттең	N;GEN;DEF;SG
күгәрсен	күгәрсендәрҙең	N;GEN;DEF;PL
абруй	абруй	N;ACC;DEF;PL
таҡырбаш	таҡырбаштарҙы	N;ACC;DEF;PL
ҡанат	ҡанатты	N;ACC;DEF;SG
ашъяулыҡ	ашъяулыҡтар	N;NOM;PL
форсат	форсатты	N;ACC;DEF;SG
тиҫтә	тиҫтәнең	N;GEN;DEF;SG
йәһәннәм	йәһәннәмдәрҙе	N;ACC;DEF;PL
игәү	игәүҙәргә	N;DAT;PL
келәм	келәмдәрҙе	N;ACC;DEF;PL
бейәләй	бейәләйҙәрҙең	N;GEN;DEF;PL
ҡолон	ҡолондарҙа	N;LOC;PL
ҡайнатма	ҡайнатмаларҙың	N;GEN;DEF;PL
игеҙәк	игеҙәктә	N;LOC;SG
гүр	гүр	N;ABL;PL
аҙна	аҙналар	N;NOM;PL
мөйөш	мөйөштөң	N;GEN;DEF;SG
Ылаҡ	Ылаҡтың	N;GEN;DEF;SG
энә	энәләрҙән	N;ABL;PL
ҡоҙғон	ҡоҙғондан	N;ABL;SG
нур	нур	N;ACC;DEF;SG
тауыш	тауыштарға	N;DAT;PL
ең	еңдең	N;GEN;DEF;SG
яҫмыҡ	яҫмыҡтың	N;GEN;DEF;SG
кәбеҫтә	кәбеҫтәлә	N;LOC;SG
ысынбарлыҡ	ысынбарлыҡта	N;LOC;SG
өй	өйҙәр	N;NOM;PL
энә	энәләргә	N;DAT;PL
үрнәк	үрнәктән	N;ABL;SG
редакция	редакция	N;NOM;SG
таҡта	таҡталарға	N;DAT;PL
ҡайнатма	ҡайнатмаларҙы	N;ACC;DEF;PL
ҡайыш	ҡайыштарға	N;DAT;PL
һөйкәлеш	һөйкәлештәрҙән	N;ABL;PL
дарыу	дарыуҙарҙың	ADJ;GEN;DEF;PL
терһәк	терһәктәр	N;NOM;PL
ғасыр	ғасырҙа	N;LOC;SG
исемлек	исемлектәрҙе	N;ACC;DEF;PL
сәбәп	сәбәпте	N;ACC;DEF;SG
сәтләүек	сәтләүекте	N;ACC;DEF;SG
таяҡ	таяҡта	N;LOC;SG
елкән	елкәнде	N;ACC;DEF;SG
селдә	селдә	N;NOM;SG
рәҡәғәт	рәҡәғәтте	N;ACC;DEF;SG
аҡҡош	аҡҡошто	N;ACC;DEF;SG
ағза	ағзала	N;LOC;SG
керпек	керпектәрҙе	N;ACC;DEF;PL
торлаҡ	торлаҡты	N;ACC;DEF;SG
үҙаң	үҙаңдан	N;ABL;SG
татыулыҡ	татыулыҡтан	N;ABL;SG
сепрәк	сепрәктә	N;LOC;SG
ашъяулыҡ	ашъяулыҡҡа	N;DAT;SG
һүҙ	һүҙ	N;GEN;DEF;PL
тәһәрәт	тәһәрәттәрҙә	N;LOC;PL
бала	балаларҙы	N;ACC;DEF;PL
хәбәрсе	хәбәрсене	N;ACC;DEF;SG
йүкә	йүкәгә	N;DAT;SG
хикәйә	хикәйәнең	N;GEN;DEF;SG
дарыу	дарыуҙа	N;LOC;SG
һандуғас	һандуғастарҙың	N;GEN;DEF;PL
тоҙ	тоҙға	N;DAT;SG
тәнәфес	тәнәфестәрҙән	N;ABL;PL
уҡыусы	уҡыусыларға	N;DAT;PL
мосолман	мосолмандың	N;GEN;DEF;SG
дауам	дауамды	N;ACC;DEF;SG
ирекмән	ирекмәндәрҙең	N;GEN;DEF;PL
сүл	сүл	N;ABL;PL
теш	тештәрҙең	N;GEN;DEF;PL
тәғлимәт	тәғлимәттәрҙә	N;LOC;PL
он	ондар	N;NOM;PL
хаҡ	хаҡтарҙы	N;ACC;DEF;PL
ҡәбер	ҡәберҙәрҙән	N;ABL;PL
самолёт	самолёттың	N;GEN;DEF;SG
миҫал	миҫалдарҙың	N;GEN;DEF;PL
ай	айҙа	N;LOC;SG
әжәл	әжәлдән	N;ABL;SG
тартма	тартмаларҙа	N;LOC;PL
ҡатнашыусы	ҡатнашыусыға	N;DAT;SG
помидор	помидорҙың	N;GEN;DEF;SG
ҡыуаҡ	ҡыуаҡтарҙан	N;ABL;PL
һунарсы	һунарсының	N;GEN;DEF;SG
йылъяҙма	йылъяҙманан	N;ABL;SG
мәрйен	мәрйендәрҙә	N;LOC;PL
ең	еңдә	N;LOC;SG
ҡашығаяҡ	ҡашығаяҡтарҙы	N;ACC;DEF;PL
даға	дағалар	N;NOM;PL
артылыш	артылыштарҙа	N;LOC;PL
бурыс	бурыстарҙа	N;LOC;PL
төрмә	төрмә	N;NOM;PL
йәнһүрәт	йәнһүрәттәргә	N;DAT;PL
сөй	сөйҙәрҙән	N;ABL;PL
ҡыпсыуыр	ҡыпсыуырҙар	N;NOM;PL
икмәк	икмәк	N;NOM;SG
рәхмәт	рәхмәттәрҙе	N;ACC;DEF;PL
ташбаҡа	ташбаҡа	N;NOM;SG
ихтилал	ихтилалдарҙың	N;GEN;DEF;PL
өлкә	өлкәләрҙә	N;LOC;PL
оя	оянан	N;ABL;SG
дуҫ	дуҫ	N;DAT;PL
ут	ут	N;NOM;SG
таяҡ	таяҡтарҙың	N;GEN;DEF;PL
ынйы	ынйыларға	N;DAT;PL
төлкө	төлкөгә	N;DAT;SG
ҡулаҡса	ҡулаҡсаларҙың	N;GEN;DEF;PL
йыуаса	йыуаса	N;NOM;SG
таң	таңдан	N;ABL;SG
ир	ир	N;DAT;PL
дин	дин	N;ACC;DEF;SG
тамсы	тамсыларҙан	N;ABL;PL
кәүҙә	кәүҙәнән	N;ABL;SG
ондатра	ондатралар	N;NOM;PL
исемлек	исемлектән	N;ABL;SG
йәтим	йәтим	N;LOC;PL
дәүләт	дәүләттәрҙең	N;GEN;DEF;PL
ҡулъяҙма	ҡулъяҙмаларҙы	N;ACC;DEF;PL
әрем	әрем	N;NOM;SG
башҡала	башҡалаларҙа	N;LOC;PL
тумыртҡа	тумыртҡаны	N;ACC;DEF;SG
аҡса	аҡсаларға	N;DAT;PL
бей	бейҙәргә	N;DAT;PL
яҡ	яҡта	N;LOC;SG
өҙәңге	өҙәңгеләргә	N;DAT;PL
мөхәрририәт	мөхәрририәттән	N;ABL;SG
әжәл	әжәлдәрҙән	N;ABL;PL
еҙ	еҙгә	N;DAT;SG
болан	болан	N;NOM;SG
алмағас	алмағастың	N;GEN;DEF;SG
барабан	барабандың	N;GEN;DEF;SG
йәшелсә	йәшелсәнең	N;GEN;DEF;SG
ҡулъяҙма	ҡулъяҙмаларға	ADJ;DAT;PL
мөгөҙ	мөгөҙҙәрҙән	N;ABL;PL
тәҡдим	тәҡдим	N;ABL;SG
урта быуат	урта быуатта	N;LOC;SG
түтәл	түтәл	N;NOM;SG
ҡала	ҡалаларҙың	N;GEN;DEF;PL
кишер	кишерҙә	N;LOC;SG
мосолман	мосолмандарға	ADJ;DAT;PL
маймыл	маймылдарҙы	N;ACC;DEF;PL
нәркәс	нәркәстең	N;GEN;DEF;SG
ялыу	ялыуҙарҙы	N;ACC;DEF;PL
барабансы	барабансы	N;NOM;SG
тире	тиреләрҙе	N;ACC;DEF;PL
урта быуат	урта быуаттан	N;ABL;SG
уғры	уғрыларҙа	N;LOC;PL
тулҡын	тулҡын	N;NOM;SG
аҡса	аҡса	N;NOM;SG
мосолман	мосолмандарҙан	N;ABL;PL
ямғыр	ямғырҙан	N;ABL;SG
гүр	гүр	N;LOC;SG
туп	туп	N;NOM;SG
ришүәтсе	ришүәтселәрҙең	N;GEN;DEF;PL
хәбәрсе	хәбәрсенең	N;GEN;DEF;SG
яңылыҡ	яңылыҡтарҙы	N;ACC;DEF;PL
ымлыҡ	ымлыҡтарға	N;DAT;PL
өҙәңге	өҙәңгегә	N;DAT;SG
игеҙәк	игеҙәккә	N;DAT;SG
бесәй	бесәйҙәр	N;NOM;PL
имән	имәндән	N;ABL;SG
торош	тороштан	N;ABL;SG
бәндә	бәндәдән	N;ABL;SG
күләгә	күләгәнең	N;GEN;DEF;SG
һуғыш	һуғыштарҙы	N;ACC;DEF;PL
йыртҡыс	йыртҡысты	N;ACC;DEF;SG
өмөт	өмөттәргә	N;DAT;PL
нигеҙ	нигеҙҙәр	N;NOM;PL
туғай	туғайҙың	N;GEN;DEF;SG
тәгәрмәс	тәгәрмәстәрҙә	N;LOC;PL
көрәк	көрәктәрҙә	N;LOC;PL
китап	китаптарҙа	N;LOC;PL
утрау	утрауҙарға	N;DAT;PL
яҙ	яҙҙы	N;ACC;DEF;SG
ҡағыҙ	ҡағыҙҙарға	N;DAT;PL
мал	малда	N;LOC;SG
берәмек	берәмектәргә	N;DAT;PL
бура	бураларҙан	N;ABL;PL
ҡорбан	ҡорбандарҙан	N;ABL;PL
ҡарағай	ҡарағайҙар	N;NOM;PL
киндер	киндергә	N;DAT;SG
уңыш	уңыштың	N;GEN;DEF;SG
поезд	поезд	N;NOM;SG
ҡумта	ҡумтаның	N;GEN;DEF;SG
йәй	йәйҙәр	N;NOM;PL
ялҡаулыҡ	ялҡаулыҡтарҙың	N;GEN;DEF;PL
имән	имәндәрҙә	N;LOC;PL
урта	уртаға	ADJ;DAT;SG
мунса	мунсаны	N;ACC;DEF;SG
машина	машинанан	N;ABL;SG
йомран	йомранға	N;DAT;SG
ҡунаҡхана	ҡунаҡханалар	N;NOM;PL
былбыл	былбыл	N;NOM;SG
емтек	емтек	N;NOM;SG
сирек	сиректәрҙең	N;GEN;DEF;PL
кишер	кишергә	N;DAT;SG
көрәк	көрәктән	N;ABL;SG
ымлыҡ	ымлыҡтарҙа	N;LOC;PL
фәрештә	фәрештәне	N;ACC;DEF;SG
уҡытыусы	уҡытыусынан	N;ABL;SG
етәксе	етәкселәрҙе	N;ACC;DEF;PL
бөрө	бөрөлә	N;LOC;SG
дәүләт	дәүләткә	N;DAT;SG
ҡолон	ҡолондарға	N;DAT;PL
балаҡ	балаҡтар	N;NOM;PL
мендәр	мендәрҙән	N;ABL;SG
дала	далала	N;LOC;SG
шырау	шырауҙың	N;GEN;DEF;SG
ахырызаман	ахырызаманның	N;GEN;DEF;SG
сер	серҙә	N;LOC;SG
бысаҡ	бысаҡтарҙа	N;LOC;PL
ғашиҡ	ғашиҡта	N;LOC;SG
һум	һум	N;LOC;PL
буранка	буранкаға	N;DAT;SG
ҡойроҡ	ҡойроҡтар	N;NOM;PL
ваҡ-төйәк	ваҡ-төйәк	N;NOM;SG
яҙ	яҙҙарҙың	N;GEN;DEF;PL
һурпа	һурпала	N;LOC;SG
ҡауҙы	ҡауҙы	N;NOM;SG
ҡояш	ҡояшта	N;LOC;SG
киндер	киндерҙең	N;GEN;DEF;SG
ауыл	ауылдан	N;ABL;SG
урта	урталарҙа	N;LOC;PL
осҡон	осҡондарҙа	N;LOC;PL
тәхет	тәхеткә	N;DAT;SG
фекер	фекергә	N;DAT;SG
сауап	сауапта	N;LOC;SG
сәтләүек	сәтләүектәргә	N;DAT;PL
ришүәтсе	ришүәтсе	N;NOM;SG
ташбаҡа	ташбаҡаларға	N;DAT;PL
мышы	мышылар	N;NOM;PL
кишер	кишерҙән	N;ABL;SG
рәхмәт	рәхмәт	N;NOM;SG
терпе	терпеләрҙең	N;GEN;DEF;PL
шарт	шартҡа	N;DAT;SG
тәхет	тәхеттәр	N;NOM;PL
сифат	сифаттан	N;ABL;SG
йондоҙнамә	йондоҙнамә	N;DAT;SG
кәрт	кәрттәрҙе	N;ACC;DEF;PL
мөгөҙ	мөгөҙҙәр	N;NOM;PL
хөкүмәт	хөкүмәттәргә	N;DAT;PL
йыртҡыс ҡош	йыртҡыс ҡоштоң	N;GEN;DEF;SG
йыртҡыс ҡош	йыртҡыс ҡоштарға	N;DAT;PL
турғай	турғайҙарға	N;DAT;PL
рәт	рәткә	N;DAT;SG
ауыл	ауылдарҙа	N;LOC;PL
быҙау	быҙауҙарға	N;DAT;PL
ҡыш	ҡышты	N;ACC;DEF;SG
кеҫә	кеҫәне	N;ACC;DEF;SG
ир-ат	ир-аттарға	N;DAT;PL
балаҫ	балаҫҡа	N;DAT;SG
рәхмәт	рәхмәткә	N;DAT;SG
ҡутаҡ	ҡутаҡтан	N;ABL;SG
таҡырбаш	таҡырбаштарҙа	N;LOC;PL
нәшриәт	нәшриәттең	N;GEN;DEF;SG
суйын	суйынға	N;DAT;SG
алма	алмаларға	N;DAT;PL
тирмәнсе	тирмәнселәр	N;NOM;PL
рәт	рәтте	N;ACC;DEF;SG
аҡбур	аҡбур	N;LOC;PL
кафыр	кафырҙы	N;ACC;DEF;SG
әжәл	әжәлдәргә	N;DAT;PL
ашъяулыҡ	ашъяулыҡтарға	N;DAT;PL
телмәр	телмәрҙең	N;GEN;DEF;SG
ҡыш	ҡыштарҙа	N;LOC;PL
ҡымыҙ	ҡымыҙға	N;DAT;SG
көйәнтә	көйәнтәләрҙе	N;ACC;DEF;PL
шишәмбе	шишәмбегә	N;DAT;SG
шиғыр	шиғыр	N;NOM;SG
дуҫлыҡ	дуҫлыҡтарҙың	N;GEN;DEF;PL
боҙбармаҡ	боҙбармаҡтарҙа	N;LOC;PL
тупраҡ	тупраҡтан	N;ABL;SG
кесаҙна	кесаҙналарҙан	N;ABL;PL
бишек	бишектәрҙә	N;LOC;PL
кәрт	кәрттәргә	N;DAT;PL
шыршы	шыршыларҙан	N;ABL;PL
даирә	даирәнең	N;GEN;DEF;SG
көндәлек	көндәлекте	N;ACC;DEF;SG
маңдай	маңдайҙы	N;ACC;DEF;SG
таяҡ	таяҡҡа	N;DAT;SG
тумыртҡа	тумыртҡаларҙа	N;LOC;PL
табут	табут	N;DAT;PL
йомағара	йомағараны	N;ACC;DEF;SG
шәреҡ	шәреҡкә	ADJ;DAT;SG
ураҡ һәм сүкеш	ураҡ һәм сүкеш	N;NOM;SG
буйҙаҡ	буйҙаҡтар	ADJ;NOM;PL
хужабикә	хужабикәләрҙә	N;LOC;PL
берәмек	берәмектәрҙә	N;LOC;PL
бал	балдан	N;ABL;SG
тантана	тантананың	N;GEN;DEF;SG
баҡса	баҡсаларҙа	N;LOC;PL
дала	даланы	N;ACC;DEF;SG
селдә	селдәләрҙә	N;LOC;PL
хужабикә	хужабикәләрҙән	N;ABL;PL
сыйырсыҡ	сыйырсыҡ	N;NOM;SG
йәнһүрәт	йәнһүрәткә	N;DAT;SG
исемлек	исемлектәрҙә	N;LOC;PL
сепрәк	сепрәктәрҙе	N;ACC;DEF;PL
хат	хаттың	N;GEN;DEF;SG
ҡатын	ҡатын	N;NOM;SG
рөхсәт	рөхсәттәрҙә	N;LOC;PL
бей	бейҙән	N;ABL;SG
рөхсәт	рөхсәттән	N;ABL;SG
туй	туй	N;ACC;DEF;SG
ожмах	ожмахтарҙа	N;LOC;PL
дарыу	дарыуға	N;DAT;SG
юйғыс	юйғыстарҙан	N;ABL;PL
яҙ	яҙҙарҙы	N;ACC;DEF;PL
иҫ	иҫ	N;ACC;DEF;PL
кеҫә	кеҫәләр	N;NOM;PL
осҡон	осҡондарҙың	N;GEN;DEF;PL
рәҡәғәт	рәҡәғәттә	N;LOC;SG
майҙансыҡ	майҙансыҡтарға	N;DAT;PL
ялыу	ялыуҙарҙан	N;ABL;PL
кейем	кейемдән	N;ABL;SG
яҡты	яҡтыла	N;LOC;SG
буҫтау	буҫтауҙарҙы	N;ACC;DEF;PL
тымау	тымауға	N;DAT;SG
машина	машиналарҙан	N;ABL;PL
ер тетрәү	ер тетрәү	N;NOM;SG
йырсы	йырсының	N;GEN;DEF;SG
төшөнсә	төшөнсәнең	N;GEN;DEF;SG
сыбыҡ	сыбыҡта	N;LOC;SG
көҙгө	көҙгөлә	N;LOC;SG
ҡалып	ҡалыптарҙы	N;ACC;DEF;PL
аҙаш	аҙашта	N;LOC;SG
яулыҡ	яулыҡҡа	N;DAT;SG
йомағара	йомағараларҙы	N;ACC;DEF;PL
йәй	йәйҙән	N;ABL;SG
ҡәбер	ҡәберҙә	N;LOC;SG
имән	имәндең	N;GEN;DEF;SG
шишмә	шишмәләрҙе	N;ACC;DEF;PL
таң	таңдарҙы	N;ACC;DEF;PL
сара	сараларҙа	N;LOC;PL
һәйкәл	һәйкәлдәрҙең	N;GEN;DEF;PL
дөгө	дөгөнө	N;ACC;DEF;SG
төлкө	төлкөләрҙең	N;GEN;DEF;PL
ҡарлуғас	ҡарлуғас	N;NOM;SG
китап	китаптың	N;GEN;DEF;SG
аҡман-тоҡман	аҡман-тоҡмандар	N;NOM;PL
һауынсы	һауынсыларҙың	N;GEN;DEF;PL
хаким	хакимда	N;LOC;SG
күт	күт	N;LOC;SG
егәр	егәрҙәрҙең	N;GEN;DEF;PL
башватҡыс	башватҡыста	N;LOC;SG
самауыр	самауырҙарҙың	N;GEN;DEF;PL
йәһәннәм	йәһәннәмдәрҙә	N;LOC;PL
ҡарама	ҡарамаларҙың	N;GEN;DEF;PL
бысҡы	бысҡы	N;NOM;PL
терпе	терпеләрҙә	N;LOC;PL
бил	бил	N;NOM;SG
буҫаға	буҫағаларҙан	N;ABL;PL
мосолман	мосолманға	N;DAT;SG
таҫтамал	таҫтамалда	N;LOC;SG
миҙгел	миҙгелдән	N;ABL;SG
мунса	мунсаларға	N;DAT;PL
мосолман	мосолмандар	ADJ;NOM;PL
ишәк	ишәктәрҙән	N;ABL;PL
маймыл	маймылда	N;LOC;SG
күргәҙмә	күргәҙмәләр	ADJ;NOM;PL
ғәмәл	ғәмәлдәрҙән	N;ABL;PL
фатиха	фатиханан	N;ABL;SG
сәйхана	сәйхананан	N;ABL;SG
үрнәк	үрнәктең	N;GEN;DEF;SG
ҡунаҡхана	ҡунаҡханаларҙан	N;ABL;PL
хужабикә	хужабикәлә	N;LOC;SG
мәсьәлә	мәсьәләләрҙең	N;GEN;DEF;PL
аҡҡош	аҡҡоштарҙы	N;ACC;DEF;PL
сәскә	сәскә	N;NOM;SG
һыҙыҡ	һыҙыҡтарҙа	N;LOC;PL
редакция	редакцияға	N;DAT;SG
мал	малдың	N;GEN;DEF;SG
йәшен	йәшендәрҙән	N;ABL;PL
сауап	сауапҡа	N;DAT;SG
бәрҙе	бәрҙелә	N;LOC;SG
морон	морондар	N;NOM;PL
туп	туп	N;GEN;DEF;PL
тирмәнсе	тирмәнсегә	N;DAT;SG
көй	көйҙөң	N;GEN;DEF;SG
ағыу	ағыуҙы	N;ACC;DEF;SG
ғәйбәт	ғәйбәттең	N;GEN;DEF;SG
яҡты	яҡтыны	ADJ;ACC;DEF;SG
һаҙ	һаҙға	N;DAT;SG
уңыш	уңыштар	N;NOM;PL
ҡасҡын	ҡасҡындарҙың	N;GEN;DEF;PL
ҡараңғы	ҡараңғының	N;GEN;DEF;SG
маймыл	маймылдар	N;NOM;PL
мөгөҙ	мөгөҙгә	N;DAT;SG
фил	фил	N;ACC;DEF;PL
йәтим	йәтим	N;GEN;DEF;PL
сифат	сифаттарҙа	N;LOC;PL
икмәк	икмәктең	N;GEN;DEF;SG
әжәл	әжәлдәрҙә	N;LOC;PL
йоҙаҡ	йоҙаҡ	N;NOM;SG
һөҙөмтә	һөҙөмтә	N;DAT;PL
үпкә	үпкә	N;ABL;PL
бүлмә	бүлмәләр	N;NOM;PL
баҙар	баҙарҙарҙы	N;ACC;DEF;PL
абруй	абруй	N;GEN;DEF;PL
кисә	кисә	N;GEN;DEF;PL
ҡыуаҡ	ҡыуаҡта	N;LOC;SG
бәлә	бәләләргә	N;DAT;PL
ташлама	ташламалар	N;NOM;PL
ҡырмыҫҡа	ҡырмыҫҡаның	N;GEN;DEF;SG
мейе	мейеләрҙә	N;LOC;PL
боҙбармаҡ	боҙбармаҡтан	N;ABL;SG
дөгө	дөгөлә	N;LOC;SG
урынбаҫар	урынбаҫарҙар	N;NOM;PL
төрмә	төрмә	N;ABL;PL
мейес	мейескә	N;DAT;SG
аяҡ	аяҡта	N;LOC;SG
тәҡдир	тәҡдир	N;DAT;SG
аҡсарлаҡ	аҡсарлаҡтарҙы	N;ACC;DEF;PL
тәре	тәреләрҙе	N;ACC;DEF;PL
ҡоҙғон	ҡоҙғонға	N;DAT;SG
сепрәк	сепрәк	N;NOM;SG
күләүек	күләүектәрҙән	N;ABL;PL
мосолман	мосолмандың	ADJ;GEN;DEF;SG
урын	урынға	N;DAT;SG
ҡояш	ҡояштың	N;GEN;DEF;SG
төп	төптө	N;ACC;DEF;SG
болот	болоттарҙы	N;ACC;DEF;PL
утҡойроҡ	утҡойроҡтарҙы	N;ACC;DEF;PL
өмөт	өмөттәрҙә	N;LOC;PL
быуат	быуаттарҙың	N;GEN;DEF;PL
Һыуғояр	Һыуғоярҙың	N;GEN;DEF;SG
тауыҡ	тауыҡтың	N;GEN;DEF;SG
һыҙат	һыҙатта	N;LOC;SG
ғөрөф-ғәҙәт	ғөрөф-ғәҙәт	N;NOM;SG
селдә	селдәнең	N;GEN;DEF;SG
мәней	мәнейгә	N;DAT;SG
һәүәҫкәр	һәүәҫкәрҙе	N;ACC;DEF;SG
етәксе	етәкселә	N;LOC;SG
яҙма	яҙма	ADJ;NOM;SG
ҡолаҡ	ҡолаҡтар	N;NOM;PL
фәлсәфә	фәлсәфәнең	N;GEN;DEF;SG
поезд	поездтарҙа	N;LOC;PL
танау	танаутан	N;ABL;SG
эшсе	эшсенән	N;ABL;SG
ауырыу	ауырыуҙы	N;ACC;DEF;SG
торош	торошҡа	N;DAT;SG
әшнә	әшнәнең	N;GEN;DEF;SG
бөрө	бөрөләрҙең	N;GEN;DEF;PL
бишек	бишектәрҙе	N;ACC;DEF;PL
хәйер	хәйерҙәр	N;NOM;PL
күләм	күләмдәрҙе	N;ACC;DEF;PL
баҫма	баҫма	N;NOM;SG
быҙау	быҙауҙарҙың	N;GEN;DEF;PL
селлә	селләне	N;ACC;DEF;SG
ысынбарлыҡ	ысынбарлыҡтарҙың	N;GEN;DEF;PL
бөйөр	бөйөргә	N;DAT;SG
зыярат	зыяратты	N;ACC;DEF;SG
йәһүд	йәһүд	ADJ;NOM;PL
һупайҙы	һупайҙыны	N;ACC;DEF;SG
сусҡа	сусҡаларға	N;DAT;PL
хәреф	хәрефтәрҙең	N;GEN;DEF;PL
йәкшәмбе	йәкшәмбе	N;NOM;SG
бейеүсе	бейеүселәрҙе	N;ACC;DEF;PL
тары	тарыны	N;ACC;DEF;SG
ауыл	ауылдарҙан	N;ABL;PL
ҡомартҡы	ҡомартҡыларҙа	N;LOC;PL
бойҙай	бойҙайҙа	N;LOC;SG
шишәмбе	шишәмбеләрҙе	N;ACC;DEF;PL
йомортҡа	йомортҡаның	N;GEN;DEF;SG
ишәк	ишәктә	N;LOC;SG
һауыт	һауыттар	N;NOM;PL
сәйхана	сәйхананың	N;GEN;DEF;SG
рәҡәғәт	рәҡәғәттәргә	N;DAT;PL
эт	эттәр	N;NOM;PL
фирғәүен	фирғәүенде	N;ACC;DEF;SG
һөйәк	һөйәктең	N;GEN;DEF;SG
Ҡыҙ	Ҡыҙҙан	N;ABL;SG
утрау	утрауҙа	N;LOC;SG
тәсбих	тәсбих	N;LOC;PL
таҡтаташ	таҡтаташ	N;NOM;SG
минут	минут	N;ABL;PL
күгәүен	күгәүендең	N;GEN;DEF;SG
миндек	миндектәргә	N;DAT;PL
шалҡан	шалҡанда	N;LOC;SG
аҙым	аҙымда	N;LOC;SG
ҡарағат	ҡарағатҡа	N;DAT;SG
дарыу	дарыуҙың	N;GEN;DEF;SG
адрес	адрестарҙа	N;LOC;PL
йөн	йөндөң	N;GEN;DEF;SG
ишек	ишектәрҙә	N;LOC;PL
ҡатнашыусы	ҡатнашыусыларҙың	N;GEN;DEF;PL
бағана	бағаналар	N;NOM;PL
һорау	һорауҙы	ADJ;ACC;DEF;SG
һөйләм	һөйләмдәр	N;NOM;PL
балға	балғала	N;LOC;SG
таҫма	таҫма	N;DAT;PL
үҫмер	үҫмерҙәр	N;NOM;PL
шама	шама	N;DAT;SG
дуҫ	дуҫ	N;NOM;PL
форсат	форсат	N;NOM;SG
бүләк	бүләкте	N;ACC;DEF;SG
ялыу	ялыуҙың	N;GEN;DEF;SG
урам	урамдарҙың	N;GEN;DEF;PL
сүл	сүл	N;GEN;DEF;SG
һыу	һыуҙарҙы	N;ACC;DEF;PL
ондатра	ондатра	N;NOM;SG
миҫал	миҫалдың	N;GEN;DEF;SG
ҡайыш	ҡайыштарҙа	N;LOC;PL
бөрсә	бөрсәлә	N;LOC;SG
шаршау	шаршауҙарҙа	N;LOC;PL
йомаҡ	йомаҡтарҙан	N;ABL;PL
ир-ат	ир-аттан	N;ABL;SG
һал	һалды	N;ACC;DEF;SG
нигеҙ	нигеҙҙәрҙе	N;ACC;DEF;PL
ҡатын	ҡатындарҙың	N;GEN;DEF;PL
тоҡсай	тоҡсайҙар	N;NOM;PL
маймыл	маймылға	N;DAT;SG
әсәй	әсәйҙәрҙең	N;GEN;DEF;PL
ойоштороусы	ойоштороусы	N;NOM;SG
сер	серҙән	N;ABL;SG
ярғанат	ярғанаттарҙан	N;ABL;PL
ҡауырһын	ҡауырһынға	N;DAT;SG
таҫтамал	таҫтамалдың	N;GEN;DEF;SG
шиғриәт	шиғриәтте	N;ACC;DEF;SG
юйғыс	юйғыстарҙы	N;ACC;DEF;PL
аҡса	аҡсаларҙан	N;ABL;PL
тәғлимәт	тәғлимәттәргә	N;DAT;PL
пәрҙә	пәрҙәләрҙең	N;GEN;DEF;PL
ҡайсы	ҡайсынан	N;ABL;SG
бөҙрә	бөҙрәләрҙе	ADJ;ACC;DEF;PL
ишек	ишек	N;NOM;SG
ишек	ишектең	N;GEN;DEF;SG
алҡа	алҡалар	N;NOM;PL
тармаҡ	тармаҡтың	N;GEN;DEF;SG
яҙма	яҙмаларҙан	N;ABL;PL
имән	имәнде	N;ACC;DEF;SG
сәғәт	сәғәттәргә	N;DAT;PL
ҡаҙаныш	ҡаҙаныштың	N;GEN;DEF;SG
баҡсасы	баҡсасылар	N;NOM;PL
ҡайсы	ҡайсыла	N;LOC;SG
күлдәк	күлдәктәр	N;NOM;PL
һупайҙы	һупайҙыларҙа	N;LOC;PL
фәлсәфә	фәлсәфәләрҙең	N;GEN;DEF;PL
Ҡәғбә	Ҡәғбәне	N;ACC;DEF;SG
ҡолон	ҡолондарҙың	N;GEN;DEF;PL
имән	имәндәрҙән	N;ABL;PL
остаз	остаздарҙы	N;ACC;DEF;PL
шәкерт	шәкерттәрҙең	N;GEN;DEF;PL
алҡыш	алҡыштың	N;GEN;DEF;SG
фекер	фекерҙә	N;LOC;SG
орлоҡ	орлоҡтар	N;NOM;PL
урта быуат	урта быуат	ADJ;NOM;SG
талап	талаптарҙан	N;ABL;PL
сара	сараға	N;DAT;SG
йөкмәтке	йөкмәткеләрҙең	N;GEN;DEF;PL
һүҙ	һүҙ	N;NOM;PL
түтәл	түтәлдәрҙе	N;ACC;DEF;PL
эшсе	эшселәр	N;NOM;PL
сыбыҡ	сыбыҡтарҙа	N;LOC;PL
рәссам	рәссамдарҙы	N;ACC;DEF;PL
тәнәфес	тәнәфестең	N;GEN;DEF;SG
тубыҡ	тубыҡта	N;LOC;SG
арҡан	арҡандарға	N;DAT;PL
ҡорос	ҡороста	N;LOC;SG
терһәк	терһәкте	N;ACC;DEF;SG
ғасыр	ғасырға	N;DAT;SG
юлдаш	юлдаштарҙың	N;GEN;DEF;PL
килеш	килеште	N;ACC;DEF;SG
шаһит	шаһит	N;GEN;DEF;PL
башаҡ	башаҡтарҙың	N;GEN;DEF;PL
һауа	һауаны	N;ACC;DEF;SG
ришүәтсе	ришүәтселәрҙән	N;ABL;PL
көс	көстө	N;ACC;DEF;SG
сәбәп	сәбәптәргә	N;DAT;PL
тәгәрмәс	тәгәрмәстәр	N;NOM;PL
машина	машинаны	N;ACC;DEF;SG
ыуылдырыҡ	ыуылдырыҡта	N;LOC;SG
бүлмә	бүлмәләрҙең	N;GEN;DEF;PL
һандыҡ	һандыҡтарҙы	N;ACC;DEF;PL
зыян	зыяндарҙы	N;ACC;DEF;PL
ҡыпһыуыр	ҡыпһыуырҙы	N;ACC;DEF;SG
үҫемлек	үҫемлектә	N;LOC;SG
бөҙрә	бөҙрәнең	N;GEN;DEF;SG
иҫ	иҫ	N;NOM;PL
шәм	шәмдең	N;GEN;DEF;SG
арҡа	арҡала	N;LOC;SG
әңгәмә	әңгәмә	N;DAT;SG
торлаҡ	торлаҡтар	N;NOM;PL
йомаҡ	йомаҡтар	N;NOM;PL
табут	табут	N;LOC;PL
йоҙроҡ	йоҙроҡтар	N;NOM;PL
рөхсәт	рөхсәттең	N;GEN;DEF;SG
алмас	алмастарҙың	N;GEN;DEF;PL
бәйләүес	бәйләүестәр	N;NOM;PL
кесерткән	кесерткәнгә	N;DAT;SG
бөҙрә	бөҙрәләргә	ADJ;DAT;PL
урта быуат	урта быуаттарҙа	ADJ;LOC;PL
һайыҫҡан	һайыҫҡан	N;NOM;SG
һуған	һуғанда	N;LOC;SG
тәһәрәт	тәһәрәттәрҙең	N;GEN;DEF;PL
тауыҡ	тауыҡта	N;LOC;SG
йомаҡ	йомаҡтарҙа	N;LOC;PL
ҡайнатма	ҡайнатмаларҙан	N;ABL;PL
йома	йомаға	N;DAT;SG
ҡултамға	ҡултамғалар	N;NOM;PL
һөйләм	һөйләмдең	N;GEN;DEF;SG
йәһәннәм	йәһәннәмдәрҙән	N;ABL;PL
дуҫлыҡ	дуҫлыҡтарға	N;DAT;PL
өлгө	өлгөлә	N;LOC;SG
яҡ	яҡты	N;ACC;DEF;SG
һауыт	һауыттарға	N;DAT;PL
айыу	айыуҙарҙа	N;LOC;PL
дилбегә	дилбегәгә	N;DAT;SG
кейем	кейемдәрҙән	N;ABL;PL
ойошма	ойошмаларҙа	N;LOC;PL
шишә	шишәгә	N;DAT;SG
шәреҡ	шәреҡ	ADJ;NOM;SG
егәр	егәрҙе	N;ACC;DEF;SG
себен	себенгә	N;DAT;SG
гөл	гөллә	N;LOC;SG
секунд	секунд	N;ABL;SG
игәү	игәүҙәрҙең	N;GEN;DEF;PL
бармаҡ	бармаҡҡа	N;DAT;SG
ағза	ағзаларҙың	N;GEN;DEF;PL
борос	борос	N;NOM;SG
упҡын	упҡындарҙың	N;GEN;DEF;PL
кафыр	кафырҙан	N;ABL;SG
игәү	игәүҙе	N;ACC;DEF;SG
тәсбих	тәсбих	N;ABL;PL
ҡыпсыуыр	ҡыпсыуырҙан	N;ABL;SG
майҙансыҡ	майҙансыҡтар	N;NOM;PL
сәүкә	сәүкәнән	N;ABL;SG
һорау	һорауҙарҙың	N;GEN;DEF;PL
утрау	утрауҙарҙың	N;GEN;DEF;PL
мырҙа	мырҙала	N;LOC;SG
ҙурлыҡ	ҙурлыҡ	N;NOM;SG
буйҙаҡ	буйҙаҡтарҙа	ADJ;LOC;PL
ҡалып	ҡалыптан	N;ABL;SG
милләтсе	милләтсене	N;ACC;DEF;SG
тормош	тормоштан	N;ABL;SG
мөрйә	мөрйәләр	N;NOM;PL
тел	телдә	N;LOC;SG
урта быуат	урта быуаттар	ADJ;NOM;PL
иләү	иләүҙәрҙә	N;LOC;PL
килмешәк	килмешәктәрҙең	N;GEN;DEF;PL
ташҡын	ташҡынға	N;DAT;SG
әүлиә	әүлиәләрҙең	N;GEN;DEF;PL
тыҡрыҡ	тыҡрыҡ	N;NOM;SG
эш	эш	N;DAT;SG
опто	оптоларға	N;DAT;PL
мөхәррир	мөхәррир	N;ACC;DEF;SG
китапхана	китапханаларға	N;DAT;PL
башҡорт	башҡортто	ADJ;ACC;DEF;SG
һарымһаҡ	һарымһаҡҡа	N;DAT;SG
ҡарға	ҡарғанан	N;ABL;SG
ташҡын	ташҡынды	N;ACC;DEF;SG
өҫтәл	өҫтәлдәрҙе	N;ACC;DEF;PL
борғаҡ	борғаҡтарҙы	N;ACC;DEF;PL
һеләгәй	һеләгәйҙе	N;ACC;DEF;SG
алтын	алтындан	N;ABL;SG
аҙыҡ-түлек	аҙыҡ-түлектәрҙән	N;ABL;PL
һылыу	һылыуҙарҙа	ADJ;LOC;PL
кәмә	кәмә	N;NOM;SG
ришүәт	ришүәттәргә	N;DAT;PL
дуңғыҙ	дуңғыҙҙар	N;NOM;PL
милләт	милләттәргә	N;DAT;PL
муйын	муйындарға	N;DAT;PL
саҡрым	саҡрымға	N;DAT;SG
этморон	этморонға	N;DAT;SG
йәннәт	йәннәттә	N;LOC;SG
тирмә	тирмәләрҙе	N;ACC;DEF;PL
гөбөргәйел	гөбөргәйелдәрҙе	N;ACC;DEF;PL
тәртип	тәртип	N;ABL;PL
һөлөк	һөлөктән	N;ABL;SG
алтын	алтынға	N;DAT;SG
ғүмер	ғүмерҙең	N;GEN;DEF;SG
буран	буранға	N;DAT;SG
муйыл	муйылда	N;LOC;SG
бүре	бүреләр	N;NOM;PL
үҙәк	үҙәктәрҙә	N;LOC;PL
ҡоролоҡ	ҡоролоҡтар	N;NOM;PL
тишек	тишектәрҙең	N;GEN;DEF;PL
япраҡ	япраҡты	N;ACC;DEF;SG
нәтижә	нәтижәләрҙә	N;LOC;PL
үрҙәк	үрҙәктә	N;LOC;SG
тәңре	тәңре	N;NOM;SG
майҙан	майҙан	N;NOM;SG
офоҡ	офоҡта	N;LOC;SG
байрам	байрамдан	N;ABL;SG
Балыҡ	Балыҡ	N;NOM;SG
тишек	тишектәрҙең	ADJ;GEN;DEF;PL
һинд	һиндтан	ADJ;ABL;SG
тотҡа	тотҡа	N;ABL;PL
майҙан	майҙандарҙан	N;ABL;PL
еңгә	еңгә	N;ACC;DEF;SG
төйөн	төйөндәрҙә	N;LOC;PL
йондоҙ	йондоҙ	N;NOM;SG
мәғәнә	мәғәнәләрҙең	N;GEN;DEF;PL
бүре	бүреләргә	N;DAT;PL
тубырсыҡ	тубырсыҡты	N;ACC;DEF;SG
борғаҡ	борғаҡтар	N;NOM;PL
шаҡмаҡ	шаҡмаҡтарҙың	N;GEN;DEF;PL
баҫҡыс	баҫҡыс	N;NOM;SG
мәңгелек	мәңгелеккә	ADJ;DAT;SG
таш	таштарҙан	N;ABL;PL
һөт	һөттөң	N;GEN;DEF;SG
ришүәт	ришүәттәрҙе	N;ACC;DEF;PL
бата	баталарҙың	N;GEN;DEF;PL
тубырсыҡ	тубырсыҡтарҙан	N;ABL;PL
шифа	шифаларҙы	N;ACC;DEF;PL
өҫтәл	өҫтәлдә	N;LOC;SG
эшҡыуарлыҡ	эшҡыуарлыҡтарҙың	N;GEN;DEF;PL
саҡрым	саҡрымдың	N;GEN;DEF;SG
бүре	бүренең	N;GEN;DEF;SG
йылан	йыландарҙың	N;GEN;DEF;PL
тейен	тейендең	N;GEN;DEF;SG
муйын	муйында	N;LOC;SG
ҡаҙ	ҡаҙға	N;DAT;SG
балан	баландарҙы	N;ACC;DEF;PL
әлифба	әлифбаны	N;ACC;DEF;SG
ҡоҙоҡ	ҡоҙоҡтарҙың	N;GEN;DEF;PL
мәрмәр	мәрмәргә	N;DAT;SG
үтек	үтеккә	N;DAT;SG
төҫ	төҫтәрҙе	N;ACC;DEF;PL
нәтижә	нәтижәләрҙе	N;ACC;DEF;PL
сумаҙан	сумаҙандарҙа	N;LOC;PL
Яңы йыл	Яңы йылдың	N;GEN;DEF;SG
ҡаш	ҡаштарҙан	N;ABL;PL
башҡорт	башҡорттарға	N;DAT;PL
тәүтормош	тәүтормоштарҙы	ADJ;ACC;DEF;PL
буран	бурандарҙан	N;ABL;PL
мәрмәр	мәрмәрҙәргә	N;DAT;PL
үрт	үрт	N;DAT;SG
саҡрым	саҡрымдар	N;NOM;PL
муйын	муйындарҙа	N;LOC;PL
өйрәк	өйрәктәр	N;NOM;PL
килмешәк	килмешәктәргә	N;DAT;PL
көл	көлдәрҙән	N;ABL;PL
ҡыяр	ҡыярҙарҙа	N;LOC;PL
төйөн	төйөндәрҙең	N;GEN;DEF;PL
киләсәк заман	киләсәк заманда	N;LOC;SG
балан	баландың	N;GEN;DEF;SG
кеше	кешене	N;ACC;DEF;SG
еңгә	еңгә	N;LOC;PL
файҙа	файҙаға	N;DAT;SG
өлөш	өлөштәр	N;NOM;PL
иләү	иләүҙәрҙән	N;ABL;PL
әфәнде	әфәнделәрҙә	N;LOC;PL
әҙәм	әҙәм	N;NOM;SG
селән	селәндә	N;LOC;SG
ағай	ағайҙа	N;LOC;SG
ҡуян	ҡуяндан	N;ABL;SG
тамуҡ	тамуҡ	N;ACC;DEF;SG
ҡоротҡос	ҡоротҡоста	N;LOC;SG
хәләл ефет	хәләл ефеттәрҙе	N;ACC;DEF;PL
уҡ	уҡ	N;NOM;PL
ришүәт	ришүәткә	N;DAT;SG
теләк	теләк	N;NOM;SG
саңғы	саңғыла	N;LOC;SG
ҡәләм	ҡәләмде	N;ACC;DEF;SG
күпер	күперҙәрҙә	N;LOC;PL
юл	юл	N;GEN;DEF;SG
олон	олонда	N;LOC;SG
кәңәш	кәңәштә	N;LOC;SG
кеше	кешеләр	N;NOM;PL
тут	тут	N;DAT;SG
өйрәк	өйрәккә	N;DAT;SG
олон	олон	N;NOM;SG
осраҡ	осраҡтарҙың	N;GEN;DEF;PL
ҡалҡан	ҡалҡандарҙа	N;LOC;PL
тәртип	тәртип	N;LOC;SG
елен	елендәргә	N;DAT;PL
хоҙай	хоҙайҙан	N;ABL;SG
йылға	йылға	N;NOM;SG
арыҫлан	арыҫланға	N;DAT;SG
тәржемә	тәржемәләрҙе	N;ACC;DEF;PL
байрам	байрамдарҙан	N;ABL;PL
алтын	алтынға	ADJ;DAT;SG
ҡыңғырау	ҡыңғырауҙарҙан	N;ABL;PL
тейен	тейендәргә	N;DAT;PL
бала саҡ	бала саҡтан	N;ABL;SG
һылыу	һылыуҙар	ADJ;NOM;PL
сәнәғәт	сәнәғәттең	N;GEN;DEF;SG
аҡыл	аҡыл	N;NOM;SG
толом	толомдарға	N;DAT;PL
шарап	шарап	N;NOM;SG
хәләл ефет	хәләл ефет	N;NOM;SG
дуңғыҙ	дуңғыҙҙа	N;LOC;SG
бейә	бейәләрҙән	N;ABL;PL
гөбөргәйел	гөбөргәйелдәрҙә	N;LOC;PL
буран	бурандарҙың	N;GEN;DEF;PL
шәжәрә	шәжәрәгә	N;DAT;SG
ҡусты	ҡустылар	N;NOM;PL
арыҫлан	арыҫланда	N;LOC;SG
етем	етемдәрҙең	N;GEN;DEF;PL
бәхәс	бәхәстә	N;LOC;SG
сәркәтип	сәркәтип	N;NOM;SG
иләү	иләүҙәр	N;NOM;PL
шарап	шараптарҙа	N;LOC;PL
һинд	һиндтарҙан	N;ABL;PL
туҡыма	туҡыманың	N;GEN;DEF;SG
иҡтисад	иҡтисадҡа	N;DAT;SG
һеләгәй	һеләгәйҙә	N;LOC;SG
аҙыҡ-түлек	аҙыҡ-түлек	N;NOM;SG
бата	бата	N;NOM;SG
ауһаҡ	ауһаҡ	N;NOM;SG
уҡ	уҡ	N;ACC;DEF;SG
ус	ус	N;ACC;DEF;SG
гөбөргәйел	гөбөргәйелдә	N;LOC;SG
ел	елдәрҙе	N;ACC;DEF;PL
күҙлек	күҙлектәргә	N;DAT;PL
вазифа	вазифаларҙың	N;GEN;DEF;PL
ниәт	ниәт	N;NOM;SG
олон	олондарҙан	N;ABL;PL
мышар	мышарҙарҙан	N;ABL;PL
ҡунаҡ	ҡунаҡҡа	N;DAT;SG
ҡуян	ҡуяндарҙан	N;ABL;PL
ҡарсыҡ	ҡарсыҡтарҙа	N;LOC;PL
тишек	тишектә	N;LOC;SG
уҡ	уҡ	N;DAT;PL
ҡотоҡ	ҡотоҡтарҙа	N;LOC;PL
үҙәк	үҙәктә	ADJ;LOC;SG
эсәк	эсәк	N;NOM;SG
арыҫлан	арыҫландан	N;ABL;SG
уҡ	уҡ	N;DAT;SG
кәңәш	кәңәштәрҙә	N;LOC;PL
ус	ус	N;ABL;PL
батша	батшала	N;LOC;SG
саҡрым	саҡрымда	N;LOC;SG
бырау	бырауҙың	N;GEN;DEF;SG
эш	эш	N;GEN;DEF;SG
үрҙәк	үрҙәктәрҙе	N;ACC;DEF;PL
тәржемә	тәржемәләр	N;NOM;PL
килмешәк	килмешәкте	N;ACC;DEF;SG
һылыу	һылыуҙарҙың	N;GEN;DEF;PL
сумаҙан	сумаҙандарға	N;DAT;PL
баҫыу	баҫыуҙарҙан	N;ABL;PL
шарап	шараптың	N;GEN;DEF;SG
бабай	бабайҙарға	N;DAT;PL
ҡуян	ҡуяндарға	N;DAT;PL
муйыл	муйылдарға	N;DAT;PL
миҙал	миҙалдарҙың	N;GEN;DEF;PL
һинд	һиндтың	N;GEN;DEF;SG
ҡағиҙә	ҡағиҙәләр	N;NOM;PL
ыласын	ыласындың	N;GEN;DEF;SG
мәғәнә	мәғәнәләрҙе	N;ACC;DEF;PL
доға	доғаларҙың	N;GEN;DEF;PL
ҡунаҡ	ҡунаҡ	N;NOM;SG
ҡоротҡос	ҡоротҡос	N;NOM;SG
опто	оптоға	N;DAT;SG
Ҡыҫала	Ҡыҫала	N;NOM;SG
сыр	сырҙан	N;ABL;SG
бейә	бейәләрҙең	N;GEN;DEF;PL
ҡом	ҡомда	N;LOC;SG
сик	сик	N;GEN;DEF;SG
таж	таждар	N;NOM;PL
бәпембә	бәпембәләрҙең	N;GEN;DEF;PL
һинд	һиндтарҙың	N;GEN;DEF;PL
сәй	сәй	N;NOM;SG
бәрәкәт	бәрәкәттән	N;ABL;SG
һылыу	һылыуҙа	ADJ;LOC;SG
ҡотоҡ	ҡотоҡто	N;ACC;DEF;SG
үтек	үтектән	N;ABL;SG
бәхәс	бәхәстән	N;ABL;SG
балыҡсы	балыҡсыларға	N;DAT;PL
балан	баландан	N;ABL;SG
ҡармаҡ	ҡармаҡта	N;LOC;SG
ғүмер	ғүмер	N;NOM;SG
бәрәкәт	бәрәкәттә	N;LOC;SG
ҡаҙ	ҡаҙҙы	N;ACC;DEF;SG
рәүеш	рәүештәр	N;NOM;PL
шәмбе	шәмбеләр	N;NOM;PL
саңғы	саңғы	N;DAT;SG
ғәйеп	ғәйептәрҙең	N;GEN;DEF;PL
етем	етемдән	N;ABL;SG
көл	көлдәргә	N;DAT;PL
шоңҡар	шоңҡарҙарҙан	N;ABL;PL
кеше	кешенән	N;ABL;SG
хәләл ефет	хәләл ефетте	N;ACC;DEF;SG
өйрәк	өйрәктәрҙә	N;LOC;PL
ҡурсаҡ	ҡурсаҡтан	N;ABL;SG
эшләпә	эшләпәгә	N;DAT;SG
әҙәм	әҙәмдә	N;LOC;SG
тәржемә	тәржемәләрҙә	N;LOC;PL
мәңгелек	мәңгелектә	ADJ;LOC;SG
хеҙмәт	хеҙмәткә	N;DAT;SG
үҙәк	үҙәктәрҙе	N;ACC;DEF;PL
өҫтәл	өҫтәл	N;NOM;SG
ҡунаҡ	ҡунаҡтың	N;GEN;DEF;SG
намаҙ	намаҙҙы	N;ACC;DEF;SG
ҡол	ҡолдарҙың	N;GEN;DEF;PL
рәүеш	рәүештәрҙә	N;LOC;PL
норма	нормала	N;LOC;SG
орҙоҡ	орҙоҡларға	N;DAT;PL
тәртип	тәртип	N;LOC;PL
тотҡа	тотҡа	N;GEN;DEF;SG
биҙәк	биҙәккә	N;DAT;SG
былау	былауҙарҙан	N;ABL;PL
мәҫәл	мәҫәлде	N;ACC;DEF;SG
әлифба	әлифбаларҙан	N;ABL;PL
эшләпә	эшләпәләрҙә	N;LOC;PL
сәнәғәт	сәнәғәттәрҙә	N;LOC;PL
һоло	һолоно	N;ACC;DEF;SG
тишек	тишекте	ADJ;ACC;DEF;SG
көл	көлдәр	N;NOM;PL
мөғжизә	мөғжизәгә	N;DAT;SG
үтек	үтектең	N;GEN;DEF;SG
мәңгелек	мәңгелектәрҙән	ADJ;ABL;PL
гәрәбә	гәрәбәгә	N;DAT;SG
иптәш	иптәшкә	N;DAT;SG
Балыҡ	Балыҡтарҙы	N;ACC;DEF;PL
ус	ус	N;LOC;PL
сумаҙан	сумаҙандар	N;NOM;PL
теләк	теләктә	N;LOC;SG
башҡорт	башҡорттарға	ADJ;DAT;PL
етем	етем	N;NOM;SG
иптәш	иптәштәр	N;NOM;PL
балыҡ	балыҡ	N;NOM;SG
һуҡыр сысҡан	һуҡыр сысҡандарҙың	N;GEN;DEF;PL
хайуан	хайуандар	N;NOM;PL
үт	үт	N;DAT;SG
ҡош	ҡошто	N;ACC;DEF;SG
ҡаш	ҡаштан	N;ABL;SG
китапхана	китапханаларҙа	N;LOC;PL
ҡуян	ҡуяндарҙың	N;GEN;DEF;PL
ирен	иренгә	N;DAT;SG
гәзит	гәзит	N;DAT;PL
сәнәғәт	сәнәғәттәр	N;NOM;PL
кәйеф	кәйефтәрҙе	N;ACC;DEF;PL
хеҙмәт	хеҙмәттәрҙең	N;GEN;DEF;PL
инша	иншаның	N;GEN;DEF;SG
намыҫ	намыҫта	N;LOC;SG
хәҙерге заман	хәҙерге замандан	N;ABL;SG
тишек	тишектәрҙе	N;ACC;DEF;PL
быяла	быяланан	N;ABL;SG
бабай	бабайҙы	N;ACC;DEF;SG
намыҫ	намыҫтың	N;GEN;DEF;SG
ауһаҡ	ауһаҡтарға	N;DAT;PL
ағай	ағайҙарҙан	N;ABL;PL
бәпембә	бәпембәне	N;ACC;DEF;SG
ҡағиҙә	ҡағиҙәне	N;ACC;DEF;SG
ниәт	ниәттәрҙең	N;GEN;DEF;PL
балта	балталар	N;NOM;PL
исем	исемдән	N;ABL;SG
бауыр	бауырҙы	N;ACC;DEF;SG
бала-саға	бала-саға	N;NOM;SG
аҙналыҡ	аҙналыҡтан	ADJ;ABL;SG
гәзит	гәзит	N;ACC;DEF;SG
тәүтормош	тәүтормошҡа	ADJ;DAT;SG
гәрәбә	гәрәбәләрҙә	N;LOC;PL
мәжүси	мәжүси	ADJ;NOM;SG
кәштә	кәштәләргә	N;DAT;PL
ватан	ватанға	N;DAT;SG
выждан	выжданды	N;ACC;DEF;SG
уҡ	уҡ	N;ABL;SG
ҡунаҡ	ҡунаҡтарҙан	N;ABL;PL
байтал	байталдарға	N;DAT;PL
норма	нормаларҙан	N;ABL;PL
хәтер	хәтергә	N;DAT;SG
сыр	сыр	N;NOM;SG
батша	батшаларҙан	N;ABL;PL
ауһаҡ	ауһаҡтан	N;ABL;SG
ирен	ирендәргә	N;DAT;PL
юрған	юрғанда	N;LOC;SG
кеше	кешеләрҙең	N;GEN;DEF;PL
сәнғәт	сәнғәттәргә	N;DAT;PL
файҙа	файҙалар	N;NOM;PL
ҡорот	ҡороттан	N;ABL;SG
саҡрым	саҡрымдан	N;ABL;SG
баҫыу	баҫыуҙа	N;LOC;SG
балыҡсы	балыҡсыға	N;DAT;SG
үрт	үрт	N;ABL;SG
мажара	мажараға	N;DAT;SG
этморон	этморондан	N;ABL;SG
тиҫбе	тиҫбенән	N;ABL;SG
ниәт	ниәттәрҙе	N;ACC;DEF;PL
кәңәш	кәңәштәр	N;NOM;PL
ағай	ағайҙарҙы	N;ACC;DEF;PL
ҡол	ҡолдарҙы	N;ACC;DEF;PL
Игеҙәктәр	Игеҙәктәрҙә	N;LOC;SG
аш	аштарҙа	N;LOC;PL
ағай	ағайҙың	N;GEN;DEF;SG
өсмөйөш	өсмөйөштөң	N;GEN;DEF;SG
гәзит	гәзит	N;DAT;SG
бәрәкәт	бәрәкәт	N;NOM;SG
үҫенте	үҫентеләр	N;NOM;PL
таҡмаҡ	таҡмаҡтарҙы	N;ACC;DEF;PL
тир	тир	N;DAT;SG
йыһан	йыһандың	N;GEN;DEF;SG
юрған	юрғандарҙа	N;LOC;PL
маҡсат	маҡсаттарҙан	N;ABL;PL
балта	балтаның	N;GEN;DEF;SG
сөгөлдөр	сөгөлдөрҙән	N;ABL;SG
балан	баландарҙа	N;LOC;PL
аҙналыҡ	аҙналыҡтарҙа	ADJ;LOC;PL
иләү	иләүҙәрҙе	N;ACC;DEF;PL
шаҡмаҡ	шаҡмаҡтар	N;NOM;PL
өҫтәл	өҫтәлгә	N;DAT;SG
һуҡмаҡ	һуҡмаҡҡа	N;DAT;SG
күбек	күбектәрҙе	N;ACC;DEF;PL
сик	сик	N;ABL;SG
һуҡыр сысҡан	һуҡыр сысҡандарҙан	N;ABL;PL
иләү	иләүҙә	N;LOC;SG
һөт	һөт	N;NOM;SG
ел	елдәргә	N;DAT;PL
диңгеҙ	диңгеҙҙәргә	N;DAT;PL
инша	иншаларҙы	N;ACC;DEF;PL
тыҡрыҡ	тыҡрыҡтарҙа	N;LOC;PL
байрам	байрамдарға	N;DAT;PL
шәриғәт	шәриғәт	N;NOM;SG
балыҡ	балыҡты	N;ACC;DEF;SG
ниәт	ниәттәргә	N;DAT;PL
төйөн	төйөнгә	N;DAT;SG
төкөрөк	төкөрөктөң	N;GEN;DEF;SG
ҡоҙоҡ	ҡоҙоҡта	N;LOC;SG
иптәш	иптәштәрҙән	N;ABL;PL
киләсәк заман	киләсәк замандың	N;GEN;DEF;SG
ижад	ижадтарҙа	N;LOC;PL
иләү	иләүҙән	N;ABL;SG
яра	яра	N;NOM;SG
ижад	ижадтар	N;NOM;PL
һағыҙ	һағыҙҙан	N;ABL;SG
мәҫәл	мәҫәлдәрҙә	N;LOC;PL
аҡыл	аҡылдарҙың	N;GEN;DEF;PL
йылға	йылғаларҙың	N;GEN;DEF;PL
һылыу	һылыуҙарҙы	ADJ;ACC;DEF;PL
етем	етемдә	N;LOC;SG
ел	елдәрҙә	N;LOC;PL
ҡотоҡ	ҡотоҡтарға	N;DAT;PL
ҡулъяулыҡ	ҡулъяулыҡта	N;LOC;SG
мәжүси	мәжүсиҙәрҙең	N;GEN;DEF;PL
баҫҡыс	баҫҡыстың	N;GEN;DEF;SG
ат	атты	N;ACC;DEF;SG
төҫ	төҫтән	N;ABL;SG
арыҫлан	арыҫландарҙың	N;GEN;DEF;PL
аҡыл	аҡылдарҙа	N;LOC;PL
мәжүси	мәжүсиҙәр	ADJ;NOM;PL
ҡусты	ҡустыға	N;DAT;SG
ботаҡ	ботаҡты	N;ACC;DEF;SG
шәриғәт	шәриғәткә	N;DAT;SG
һылыу	һылыуға	N;DAT;SG
күренеш	күренештәрҙән	N;ABL;PL
ҡан	ҡан	N;NOM;SG
осраҡ	осраҡты	N;ACC;DEF;SG
тәүтормош	тәүтормоштоң	ADJ;GEN;DEF;SG
әлифба	әлифбалар	N;NOM;PL
үксә	үксәнән	N;ABL;SG
ҡыяр	ҡыярҙа	N;LOC;SG
ҡоҙоҡ	ҡоҙоҡ	N;NOM;SG
балта	балталарҙың	N;GEN;DEF;PL
үрҙәк	үрҙәктәргә	N;DAT;PL
ҡоҙоҡ	ҡоҙоҡтарға	N;DAT;PL
һағыҙ	һағыҙҙың	N;GEN;DEF;SG
мәҫәл	мәҫәлгә	N;DAT;SG
хәләл ефет	хәләл ефеттәргә	N;DAT;PL
ҡалҡан	ҡалҡандарҙы	N;ACC;DEF;PL
нәфрәт	нәфрәттән	N;ABL;SG
эш	эш	N;ACC;DEF;PL
мәҫәл	мәҫәлдәргә	N;DAT;PL
шифа	шифаларҙың	N;GEN;DEF;PL
байрам	байрамды	N;ACC;DEF;SG
торна	торналарҙа	N;LOC;PL
юрған	юрғандарға	N;DAT;PL
эсәк	эсәктәрҙә	N;LOC;PL
яра	яраларға	N;DAT;PL
Ҡыҫала	Ҡыҫалаға	N;DAT;SG
үҙәк	үҙәктә	N;LOC;SG
ағай	ағайҙы	N;ACC;DEF;SG
инша	иншаларҙа	N;LOC;PL
йылға	йылғаларға	N;DAT;PL
таҡмаҡ	таҡмаҡтарҙа	N;LOC;PL
эсәк	эсәктәргә	N;DAT;PL
буран	буранды	N;ACC;DEF;SG
еңгә	еңгә	N;DAT;PL
кеше	кешеләрҙә	N;LOC;PL
тишек	тишектәрҙе	ADJ;ACC;DEF;PL
елен	елендә	N;LOC;SG
яҙмыш	яҙмыш	N;NOM;SG
елен	елендәрҙе	N;ACC;DEF;PL
шарап	шараптарҙың	N;GEN;DEF;PL
мәҫәл	мәҫәлдәр	N;NOM;PL
Ҡыҫала	Ҡыҫалалар	N;NOM;PL
миҙал	миҙалға	N;DAT;SG
хоҙай	хоҙай	N;NOM;SG
шифа	шифаның	N;GEN;DEF;SG
үҙәк	үҙәктәрҙе	ADJ;ACC;DEF;PL
ыласын	ыласында	N;LOC;SG
саҡрым	саҡрымдарға	N;DAT;PL
һунар	һунарға	N;DAT;SG
килмешәк	килмешәк	N;NOM;SG
батырлыҡ	батырлыҡтарҙың	N;GEN;DEF;PL
күренеш	күренештәрҙең	N;GEN;DEF;PL
бутҡа	бутҡаны	N;ACC;DEF;SG
намаҙ	намаҙҙарҙың	N;GEN;DEF;PL
сыр	сырҙарҙы	N;ACC;DEF;PL
гәзит	гәзит	N;NOM;SG
ирен	ирендәрҙең	N;GEN;DEF;PL
нисбәт	нисбәттең	N;GEN;DEF;SG
кер	кер	N;NOM;SG
кәңәш	кәңәштәрҙән	N;ABL;PL
ҡармаҡ	ҡармаҡ	N;NOM;SG
аҙналыҡ	аҙналыҡтарҙан	ADJ;ABL;PL
тирмә	тирмәнең	N;GEN;DEF;SG
мәҫәл	мәҫәлдәрҙән	N;ABL;PL
ус	ус	N;GEN;DEF;SG
шәжәрә	шәжәрәнән	N;ABL;SG
ҫупайҙы	ҫупайҙыларға	N;DAT;PL
тишек	тишек	N;NOM;SG
дуңғыҙ	дуңғыҙҙы	N;ACC;DEF;SG
мәрмәр	мәрмәр	N;NOM;SG
ҡуян	ҡуяндарҙа	N;LOC;PL
алйырҙан	алйырҙандарҙың	N;GEN;DEF;PL
йылан	йылан	N;NOM;SG
хәтер	хәтер	N;NOM;SG
тирәк	тирәктәрҙең	N;GEN;DEF;PL
сыр	сырҙарға	N;DAT;PL
бырау	бырауҙарҙа	N;LOC;PL
балан	баландарға	N;DAT;PL
иҡтисад	иҡтисадты	N;ACC;DEF;SG
маҡсат	маҡсат	N;NOM;SG
мылтыҡ	мылтыҡҡа	N;DAT;SG
мәҫәл	мәҫәлдә	N;LOC;SG
кесе йома	кесе йома	N;NOM;SG
сәркәтип	сәркәтип	N;LOC;SG
арыҫлан	арыҫландар	N;NOM;PL
тишек	тишеккә	N;DAT;SG
борғаҡ	борғаҡ	N;NOM;SG
доға	доғаға	N;DAT;SG
ҡош	ҡоштарҙа	N;LOC;PL
тыуған көн	тыуған көндө	N;ACC;DEF;SG
бала-саға	бала-сағаны	N;ACC;DEF;SG
дуңғыҙ	дуңғыҙҙарҙа	N;LOC;PL
аҙналыҡ	аҙналыҡтарҙың	N;GEN;DEF;PL
мәғәнә	мәғәнәнән	N;ABL;SG
тин	тин	N;GEN;DEF;PL
гонаһ	гонаһтар	N;NOM;PL
файҙа	файҙаларҙың	N;GEN;DEF;PL
шәжәрә	шәжәрәләр	N;NOM;PL
китапхана	китапханаларҙы	N;ACC;DEF;PL
батша	батшаларға	N;DAT;PL
гонаһ	гонаһта	N;LOC;SG
һинд	һиндты	ADJ;ACC;DEF;SG
атама	атамала	N;LOC;SG
селән	селәндең	N;GEN;DEF;SG
сәркәтип	сәркәтип	N;DAT;SG
тиҫбе	тиҫбеләрҙең	N;GEN;DEF;PL
көл	көл	N;NOM;SG
сәнәғәт	сәнәғәт	N;NOM;SG
таш	таштың	N;GEN;DEF;SG
бырау	бырауҙарҙан	N;ABL;PL
ҡол	ҡолдар	N;NOM;PL
таҡмаҡ	таҡмаҡтың	N;GEN;DEF;SG
шәмбе	шәмбе	N;NOM;SG
Игеҙәктәр	Игеҙәктәргә	N;DAT;SG
ҡош	ҡоштарҙы	N;ACC;DEF;PL
хәләл ефет	хәләл ефеттәрҙең	N;GEN;DEF;PL
тишек	тишектең	ADJ;GEN;DEF;SG
бейә	бейә	N;NOM;SG
сик	сик	N;DAT;SG
үҫенте	үҫентеләрҙең	N;GEN;DEF;PL
төн	төндәрҙә	N;LOC;PL
исем	исемдәрҙән	N;ABL;PL
байтал	байталдарҙан	N;ABL;PL
әҙәм	әҙәмде	N;ACC;DEF;SG
тиҫбе	тиҫбеләрҙе	N;ACC;DEF;PL
шифа	шифаға	N;DAT;SG
сәркәтип	сәркәтип	N;GEN;DEF;SG
тәңре	тәңренән	N;ABL;SG
йылға	йылғаның	N;GEN;DEF;SG
аҙыҡ	аҙыҡтың	N;GEN;DEF;SG
Ҡыҫала	Ҡыҫаланы	N;ACC;DEF;SG
ҡыҙыҡ	ҡыҙыҡ	ADJ;NOM;SG
муйын	муйындарҙың	N;GEN;DEF;PL
шәрәлек	шәрәлеккә	N;DAT;SG
үрт	үрт	N;NOM;SG
һөлөк	һөлөктө	N;ACC;DEF;SG
гонаһ	гонаһтарҙың	N;GEN;DEF;PL
алйырҙан	алйырҙан	N;NOM;SG
китапхана	китапхананың	N;GEN;DEF;SG
һинд	һиндты	N;ACC;DEF;SG
һеләгәй	һеләгәйҙең	N;GEN;DEF;SG
ғәйеп	ғәйептең	N;GEN;DEF;SG
сәй	сәйгә	N;DAT;SG
гонаһ	гонаһҡа	N;DAT;SG
һинд	һиндтарҙан	ADJ;ABL;PL
былау	былауҙарҙы	N;ACC;DEF;PL
мәжүси	мәжүсиҙең	ADJ;GEN;DEF;SG
гонаһ	гонаһтарҙан	N;ABL;PL
бутҡа	бутҡаларҙан	N;ABL;PL
ҡом	ҡомдоң	N;GEN;DEF;SG
һуҡмаҡ	һуҡмаҡтан	N;ABL;SG
тыҡрыҡ	тыҡрыҡтарға	N;DAT;PL
ҡайын	ҡайында	N;LOC;SG
мәрмәр	мәрмәрҙә	N;LOC;SG
мәктәп	мәктәптәрҙән	N;ABL;PL
нисбәт	нисбәттәрҙә	N;LOC;PL
тәүтормош	тәүтормоштарҙы	N;ACC;DEF;PL
ҡыяр	ҡыярҙың	N;GEN;DEF;SG
аҙыҡ-түлек	аҙыҡ-түлектәрҙең	N;GEN;DEF;PL
үҙәк	үҙәктәр	N;NOM;PL
мәрмәр	мәрмәрҙәрҙең	N;GEN;DEF;PL
шоңҡар	шоңҡарҙарҙың	N;GEN;DEF;PL
тәржемә	тәржемәлә	N;LOC;SG
кәйеф	кәйефтәрҙән	N;ABL;PL
ҡаш	ҡашта	N;LOC;SG
кисеү	кисеүҙәрҙең	N;GEN;DEF;PL
һалам	һаламдан	N;ABL;SG
риүәйәт	риүәйәттән	N;ABL;SG
былау	былауҙың	N;GEN;DEF;SG
олон	олонға	N;DAT;SG
орҙоҡ	орҙоҡларҙан	N;ABL;PL
тин	тин	N;NOM;PL
оро	ороларҙы	N;ACC;DEF;PL
диңгеҙ	диңгеҙҙәр	N;NOM;PL
Игеҙәктәр	Игеҙәктәр	N;NOM;SG
үрҙәк	үрҙәкте	N;ACC;DEF;SG
ат	аттарҙан	N;ABL;PL
балан	баланға	N;DAT;SG
еңгә	еңгә	N;ACC;DEF;PL
кеше	кеше	N;NOM;SG
төҫ	төҫ	N;NOM;SG
яҙмыш	яҙмышта	N;LOC;SG
мәңгелек	мәңгелекте	N;ACC;DEF;SG
шифа	шифаларҙа	N;LOC;PL
баҫыу	баҫыуҙы	N;ACC;DEF;SG
ауһаҡ	ауһаҡтарҙа	N;LOC;PL
Науруз	Науруз	N;NOM;SG
быяла	быяла	N;NOM;SG
быяла	быялаларҙың	N;GEN;DEF;PL
бырау	бырауҙар	N;NOM;PL
балыҡ	балыҡтарҙан	N;ABL;PL
бала-саға	бала-сағаның	N;GEN;DEF;SG
хәләл ефет	хәләл ефеттәр	N;NOM;PL
соҡор	соҡорҙарҙан	N;ABL;PL
аҙыҡ-түлек	аҙыҡ-түлектәрҙә	N;LOC;PL
кәмә	кәмәләрҙең	N;GEN;DEF;PL
һылыу	һылыуҙарға	ADJ;DAT;PL
нәтижә	нәтижәлә	N;LOC;SG
үҙәк	үҙәктәрҙең	N;GEN;DEF;PL
гәзит	гәзит	N;NOM;PL
мәңгелек	мәңгелек	N;NOM;SG
үҫенте	үҫентене	N;ACC;DEF;SG
майҙан	майҙандар	N;NOM;PL
һемәк	һемәктең	N;GEN;DEF;SG
ер	ерҙәрҙең	N;GEN;DEF;PL
шаҡмаҡ	шаҡмаҡтарға	N;DAT;PL
ҡотоҡ	ҡотоҡтоң	N;GEN;DEF;SG
толом	толомдар	N;NOM;PL
һуҡмаҡ	һуҡмаҡтарҙың	N;GEN;DEF;PL
бала-саға	бала-сағала	N;LOC;SG
выждан	выждандан	N;ABL;SG
мылтыҡ	мылтыҡтың	N;GEN;DEF;SG
мәктәп	мәктәптәргә	N;DAT;PL
тишек	тишектәргә	N;DAT;PL
эшҡыуарлыҡ	эшҡыуарлыҡтар	N;NOM;PL
эшҡыуарлыҡ	эшҡыуарлыҡтарҙа	N;LOC;PL
һинд	һиндҡа	ADJ;DAT;SG
күҙлек	күҙлекте	N;ACC;DEF;SG
ҡуян	ҡуяндарҙы	N;ACC;DEF;PL
ришүәт	ришүәт	N;NOM;SG
күҙлек	күҙлектәрҙең	N;GEN;DEF;PL
ел	елдең	N;GEN;DEF;SG
төн	төн	N;NOM;SG
өсмөйөш	өсмөйөштән	N;ABL;SG
һинд	һиндтың	ADJ;GEN;DEF;SG
күбек	күбектәргә	N;DAT;PL
ирен	ирендәрҙә	N;LOC;PL
күпер	күпергә	N;DAT;SG
ватан	ватанда	N;LOC;SG
ҡорот	ҡоротҡа	N;DAT;SG
төбәк	төбәктәрҙең	N;GEN;DEF;PL
ярҙам	ярҙамда	N;LOC;SG
сәнәғәт	сәнәғәттә	N;LOC;SG
ыласын	ыласындан	N;ABL;SG
таж	тажда	N;LOC;SG
тиҫбе	тиҫбелә	N;LOC;SG
норма	норманың	N;GEN;DEF;SG
тыҡрыҡ	тыҡрыҡты	N;ACC;DEF;SG
китапхана	китапханалар	N;NOM;PL
үҙәк	үҙәктәр	ADJ;NOM;PL
һинд	һиндта	ADJ;LOC;SG
әҙәм	әҙәмдәр	N;NOM;PL
өҫтәл	өҫтәлде	N;ACC;DEF;SG
шәмбе	шәмбелә	N;LOC;SG
төҫ	төҫтө	N;ACC;DEF;SG
тин	тин	N;GEN;DEF;SG
ҫупайҙы	ҫупайҙы	N;NOM;SG
маңҡа	маңҡа	N;NOM;SG
көл	көлдән	N;ABL;SG
шәжәрә	шәжәрә	N;NOM;SG
селән	селән	N;NOM;SG
гөбөргәйел	гөбөргәйелдәргә	N;DAT;PL
күҙлек	күҙлектәрҙә	N;LOC;PL
ташҡын	ташҡындарҙа	N;LOC;PL
асҡыс	асҡыстың	N;GEN;DEF;SG
шәмбе	шәмбеләрҙә	N;LOC;PL
теләк	теләктән	N;ABL;SG
нәтижә	нәтижәне	N;ACC;DEF;SG
тәбиғәт	тәбиғәт	N;NOM;SG
мөғжизә	мөғжизәләрҙән	N;ABL;PL
төкөрөк	төкөрөктән	N;ABL;SG
осраҡ	осраҡта	N;LOC;SG
ҡом	ҡомдо	N;ACC;DEF;SG
ҡоролоҡ	ҡоролоҡҡа	N;DAT;SG
арыҫлан	арыҫландарҙан	N;ABL;PL
ыласын	ыласындарҙан	N;ABL;PL
кер	керҙән	N;ABL;SG
инша	иншаларҙың	N;GEN;DEF;PL
бәхәс	бәхәстең	N;GEN;DEF;SG
ат	аттар	N;NOM;PL
былау	былауҙа	N;LOC;SG
йәннәт	йәннәттәр	N;NOM;PL
алтын	алтындың	ADJ;GEN;DEF;SG
ҡарсыҡ	ҡарсыҡтан	N;ABL;SG
хәл	хәлде	N;ACC;DEF;SG
сәркәтип	сәркәтип	N;LOC;PL
Ҡыҫала	Ҡыҫалаларҙың	N;GEN;DEF;PL
доға	доғаны	N;ACC;DEF;SG
ҡунаҡ	ҡунаҡта	N;LOC;SG
араҡы	араҡыла	N;LOC;SG
ҡәләм	ҡәләмдәрҙең	N;GEN;DEF;PL
тубырсыҡ	тубырсыҡтарҙың	N;GEN;DEF;PL
ҡунаҡ	ҡунаҡтарҙы	N;ACC;DEF;PL
шаршамбы	шаршамбыларҙан	N;ABL;PL
толом	толом	N;NOM;SG
баҫҡыс	баҫҡысҡа	N;DAT;SG
бәхәс	бәхәстәрҙең	N;GEN;DEF;PL
милләт	милләттең	N;GEN;DEF;SG
мылтыҡ	мылтыҡтар	N;NOM;PL
дуңғыҙ	дуңғыҙҙарҙы	N;ACC;DEF;PL
байтал	байталдарҙың	N;GEN;DEF;PL
өҫтәл	өҫтәлдәрҙә	N;LOC;PL
төтөн	төтөндә	N;LOC;SG
ата-әсә	ата-әсәлә	N;LOC;SG
туҡыма	туҡымаларҙан	N;ABL;PL
тирәк	тирәктә	N;LOC;SG
үҫенте	үҫентелә	N;LOC;SG
рәүеш	рәүеште	N;ACC;DEF;SG
етем	етемде	N;ACC;DEF;SG
алтын	алтындан	ADJ;ABL;SG
хәл	хәлдәрҙе	N;ACC;DEF;PL
тин	тин	N;ACC;DEF;PL
йондоҙ	йондоҙҙар	N;NOM;PL
ярҙам	ярҙамға	N;DAT;SG
байтал	байталдар	N;NOM;PL
тамуҡ	тамуҡ	N;LOC;SG
үтек	үтектәрҙе	N;ACC;DEF;PL
кесе йома	кесе йомаларҙы	N;ACC;DEF;PL
бутҡа	бутҡаға	N;DAT;SG
һемәк	һемәктәрҙә	N;LOC;PL
диңгеҙ	диңгеҙ	N;NOM;SG
муйыл	муйылдан	N;ABL;SG
йылан	йыландарға	N;DAT;PL
рәүеш	рәүештәргә	N;DAT;PL
ватан	ватандың	N;GEN;DEF;SG
селән	селәндәр	N;NOM;PL
Яңы йыл	Яңы йылды	N;ACC;DEF;SG
бүре	бүреләрҙең	N;GEN;DEF;PL
балыҡсы	балыҡсылар	N;NOM;PL
аҡыл	аҡылдарҙан	N;ABL;PL
аҙналыҡ	аҙналыҡты	N;ACC;DEF;SG
шаҡмаҡ	шаҡмаҡтан	N;ABL;SG
нисбәт	нисбәттән	N;ABL;SG
өҫтәл	өҫтәлдәрҙән	N;ABL;PL
ҡаҙ	ҡаҙҙарҙың	N;GEN;DEF;PL
әфәнде	әфәндегә	N;DAT;SG
саҡрым	саҡрымдарҙан	N;ABL;PL
торна	торналарҙан	N;ABL;PL
ҡарға	ҡарғалар	N;NOM;PL
гонаһ	гонаһтан	N;ABL;SG
бәхәс	бәхәсте	N;ACC;DEF;SG
ҡарға	ҡарға	N;NOM;SG
йондоҙ	йондоҙҙа	N;LOC;SG
сәсән	сәсәнде	N;ACC;DEF;SG
төн	төндөң	N;GEN;DEF;SG
инша	иншалар	N;NOM;PL
эшҡыуарлыҡ	эшҡыуарлыҡҡа	N;DAT;SG
гәрәбә	гәрәбәлә	N;LOC;SG
ғүмер	ғүмерҙәргә	N;DAT;PL
бата	баталар	N;NOM;PL
ришүәт	ришүәттәрҙән	N;ABL;PL
ҡарға	ҡарғаның	N;GEN;DEF;SG
ил	ил	N;NOM;PL
мылтыҡ	мылтыҡтарҙан	N;ABL;PL
тимерсыбыҡ	тимерсыбыҡтарҙың	N;GEN;DEF;PL
доға	доғаларҙа	N;LOC;PL
шаҡмаҡ	шаҡмаҡты	N;ACC;DEF;SG
аш	ашта	N;LOC;SG
гәрәбә	гәрәбәләрҙән	N;ABL;PL
балыҡ	балыҡтың	N;GEN;DEF;SG
тәңре	тәңрегә	N;DAT;SG
үҙәк	үҙәкте	N;ACC;DEF;SG
аҙыҡ-түлек	аҙыҡ-түлектән	N;ABL;SG
диңгеҙ	диңгеҙҙән	N;ABL;SG
ҡыҙыҡ	ҡыҙыҡты	ADJ;ACC;DEF;SG
Ҡуҙы	Ҡуҙыға	N;DAT;SG
әлифба	әлифбаларҙа	N;LOC;PL
төн	төндәр	N;NOM;PL
үтек	үтектәр	N;NOM;PL
ел	ел	N;NOM;SG
өлөш	өлөштәрҙең	N;GEN;DEF;PL
ҡыҙыҡ	ҡыҙыҡтың	ADJ;GEN;DEF;SG
сәнғәт	сәнғәттәрҙе	N;ACC;DEF;PL
тыуған көн	тыуған көндәрҙән	N;ABL;PL
шифахана	шифаханала	N;LOC;SG
таш	таштарҙың	N;GEN;DEF;PL
шәмбе	шәмбеләрҙе	N;ACC;DEF;PL
таж	таж	N;NOM;SG
мәжүси	мәжүсиҙәрҙе	ADJ;ACC;DEF;PL
ғаилә	ғаиләләр	N;NOM;PL
торна	торналарҙы	N;ACC;DEF;PL
ҡыяр	ҡыярҙы	N;ACC;DEF;SG
оро	оро	N;NOM;SG
бәрәкәт	бәрәкәткә	N;DAT;SG
ирен	ирендә	N;LOC;SG
ҡотоҡ	ҡотоҡтарҙан	N;ABL;PL
һылыу	һылыуҙың	N;GEN;DEF;SG
шифа	шифаларға	N;DAT;PL
Яңы йыл	Яңы йылдан	N;ABL;SG
донъя	донъялар	N;NOM;PL
мәжүсилек	мәжүсилекте	N;ACC;DEF;SG
хайуан	хайуандың	N;GEN;DEF;SG
тейен	тейендәр	N;NOM;PL
мөғжизә	мөғжизәләр	N;NOM;PL
мәжүси	мәжүсиҙәрҙә	ADJ;LOC;PL
тиҫбе	тиҫбегә	N;DAT;SG
милләт	милләт	N;NOM;SG
сәркәтип	сәркәтип	N;GEN;DEF;PL
шарап	шарапты	N;ACC;DEF;SG
эсәк	эсәкте	N;ACC;DEF;SG
шифа	шифанан	N;ABL;SG
ус	ус	N;GEN;DEF;PL
тәртип	тәртип	N;GEN;DEF;PL
хеҙмәт	хеҙмәттәргә	N;DAT;PL
сумаҙан	сумаҙандарҙан	N;ABL;PL
кәшәнә	кәшәнәләрҙән	N;ABL;PL
саңғы	саңғынан	N;ABL;SG
һөргөн	һөргөндөң	N;GEN;DEF;SG
эсәк	эсәктә	N;LOC;SG
кәйеф	кәйеф	N;NOM;SG
һинд	һиндтарға	N;DAT;PL
ҡыңғырау	ҡыңғырауҙы	N;ACC;DEF;SG
иблис	иблис	N;ACC;DEF;SG
донъя	донъяны	N;ACC;DEF;SG
ҡол	ҡолдо	N;ACC;DEF;SG
кәйеф	кәйефкә	N;DAT;SG
рәүеш	рәүештә	N;LOC;SG
Үлсәү	Үлсәүҙең	N;GEN;DEF;SG
төбәк	төбәктәрҙән	N;ABL;PL
тырма	тырманы	N;ACC;DEF;SG
мәҡәлә	мәҡәләләрҙе	N;ACC;DEF;PL
осраҡ	осраҡтарҙан	N;ABL;PL
шоңҡар	шоңҡар	N;NOM;SG
еңгә	еңгә	N;GEN;DEF;PL
тырма	тырманан	N;ABL;SG
һөт	һөткә	N;DAT;SG
оро	ороларҙан	N;ABL;PL
таш	таштарға	N;DAT;PL
тотҡа	тотҡа	N;NOM;SG
ус	ус	N;DAT;SG
йондоҙ	йондоҙҙарҙа	N;LOC;PL
йылға	йылғаларҙан	N;ABL;PL
ҡаш	ҡаштың	N;GEN;DEF;SG
балта	балталарҙа	N;LOC;PL
ботаҡ	ботаҡтарҙы	N;ACC;DEF;PL
тәртип	тәртип	N;NOM;PL
мышар	мышарҙарҙы	N;ACC;DEF;PL
төйөн	төйөндәрҙе	N;ACC;DEF;PL
төҫ	төҫтә	N;LOC;SG
бүре	бүрене	N;ACC;DEF;SG
тамуҡ	тамуҡ	N;GEN;DEF;PL
тәңре	тәңренең	N;GEN;DEF;SG
кәшәнә	кәшәнәләрҙең	N;GEN;DEF;PL
ҫупайҙы	ҫупайҙылар	N;NOM;PL
әлифба	әлифбаларҙың	N;GEN;DEF;PL
таж	тажды	N;ACC;DEF;SG
һылыу	һылыуҙы	N;ACC;DEF;SG
ирен	иренде	N;ACC;DEF;SG
китапхана	китапханаға	N;DAT;SG
доға	доғалар	N;NOM;PL
асҡыс	асҡыста	N;LOC;SG
сәркәтип	сәркәтип	N;ACC;DEF;SG
эшләпә	эшләпәнең	N;GEN;DEF;SG
күҙлек	күҙлектән	N;ABL;SG
риүәйәт	риүәйәттәр	N;NOM;PL
нәфрәт	нәфрәттә	N;LOC;SG
офоҡ	офоҡтарҙан	N;ABL;PL
аҡыл	аҡылдан	N;ABL;SG
ыласын	ыласындарҙың	N;GEN;DEF;PL
хайуан	хайуанды	N;ACC;DEF;SG
үксә	үксәгә	N;DAT;SG
оро	ороно	N;ACC;DEF;SG
толом	толомдарҙа	N;LOC;PL
күпер	күперҙәрҙән	N;ABL;PL
хәл	хәлдәр	N;NOM;PL
шоңҡар	шоңҡарҙар	N;NOM;PL
ҫупайҙы	ҫупайҙыны	N;ACC;DEF;SG
күбек	күбектәрҙең	N;GEN;DEF;PL
гәрәбә	гәрәбә	N;NOM;SG
осраҡ	осраҡтарҙы	N;ACC;DEF;PL
арыҫлан	арыҫландарға	N;DAT;PL
шаршамбы	шаршамбыларҙы	N;ACC;DEF;PL
ҡайын	ҡайындарға	N;DAT;PL
намаҙ	намаҙ	N;NOM;SG
хайуан	хайуанға	N;DAT;SG
кәштә	кәштә	N;NOM;SG
тир	тир	N;ACC;DEF;SG
төн	төнгә	N;DAT;SG
гөлйемеш	гөлйемеш	N;NOM;SG
өсмөйөш	өсмөйөш	N;NOM;SG
ижек	ижек	N;NOM;SG
ил	ил	N;ACC;DEF;SG
таш	ташты	N;ACC;DEF;SG
көл	көлдөң	N;GEN;DEF;SG
шифахана	шифахананан	N;ABL;SG
сейә	сейәне	N;ACC;DEF;SG
япраҡ	япраҡ	N;NOM;SG
ҡағиҙә	ҡағиҙәләрҙә	N;LOC;PL
ижек	ижеккә	N;DAT;SG
аҡыл	аҡылды	N;ACC;DEF;SG
тәңре	тәңреләр	N;NOM;PL
муйын	муйындар	N;NOM;PL
исем	исемдең	N;GEN;DEF;SG
бәпембә	бәпембәгә	N;DAT;SG
соҡор	соҡорҙарҙы	N;ACC;DEF;PL
былау	былау	N;NOM;SG
хәбәр	хәбәрҙәрҙән	N;ABL;PL
йыһан	йыһанға	N;DAT;SG
эшләпә	эшләпәләрҙе	N;ACC;DEF;PL
тыуған көн	тыуған көндән	N;ABL;SG
күбек	күбек	N;NOM;SG
батша	батшаны	N;ACC;DEF;SG
ғәйеп	ғәйептәрҙә	N;LOC;PL
әлифба	әлифбаға	N;DAT;SG
оро	оронан	N;ABL;SG
Балыҡ	Балыҡҡа	N;DAT;SG
бүре	бүрелә	N;LOC;SG
сәй	сәйҙә	N;LOC;SG
ғаилә	ғаиләләрҙе	N;ACC;DEF;PL
Ҡуҙы	Ҡуҙыны	N;ACC;DEF;SG
япраҡ	япраҡтарҙа	N;LOC;PL
ҡулъяулыҡ	ҡулъяулыҡтарға	N;DAT;PL
сик	сик	N;LOC;PL
мәжүсилек	мәжүсилеккә	N;DAT;SG
тишек	тишектәрҙән	N;ABL;PL
тут	тут	N;ABL;SG
араҡы	араҡы	N;NOM;SG
башҡорт	башҡорттарҙа	N;LOC;PL
мәктәп	мәктәпте	N;ACC;DEF;SG
бабай	бабайҙарҙа	N;LOC;PL
маҡсат	маҡсаттан	N;ABL;SG
ҡурсаҡ	ҡурсаҡтарға	N;DAT;PL
иҡтисад	иҡтисадта	N;LOC;SG
эшләпә	эшләпәләргә	N;DAT;PL
эшҡыуарлыҡ	эшҡыуарлыҡта	N;LOC;SG
вазифа	вазифаларҙы	N;ACC;DEF;PL
мөғжизә	мөғжизәлә	N;LOC;SG
ат	аттарға	N;DAT;PL
толом	толомдо	N;ACC;DEF;SG
мажара	мажара	N;NOM;SG
тирәк	тирәктәрҙән	N;ABL;PL
шарап	шараптарға	N;DAT;PL
опто	опто	N;NOM;SG
балан	баланды	N;ACC;DEF;SG
күренеш	күренештәр	N;NOM;PL
һылыу	һылыуҙа	N;LOC;SG
асҡыс	асҡысты	N;ACC;DEF;SG
доға	доғаның	N;GEN;DEF;SG
ҡаҙ	ҡаҙҙарға	N;DAT;PL
вазифа	вазифалар	N;NOM;PL
әфәнде	әфәнделәрҙе	N;ACC;DEF;PL
сик	сик	N;GEN;DEF;PL
шоңҡар	шоңҡарҙан	N;ABL;SG
буран	бурандан	N;ABL;SG
ер	ер	N;NOM;SG
аҙналыҡ	аҙналыҡтарға	ADJ;DAT;PL
баҫыу	баҫыуҙар	N;NOM;PL
сәркәтип	сәркәтип	N;NOM;PL
төтөн	төтөнгә	N;DAT;SG
әлифба	әлифбала	N;LOC;SG
иләү	иләүҙәрҙең	N;GEN;DEF;PL
ҫупайҙы	ҫупайҙыларҙан	N;ABL;PL
донъя	донъя	N;NOM;SG
юл	юл	N;ACC;DEF;SG
офоҡ	офоҡтарҙа	N;LOC;PL
борғаҡ	борғаҡтарға	N;DAT;PL
алтын	алтын	N;NOM;SG
атама	атаманы	N;ACC;DEF;SG
Науруз	Науруз	N;LOC;SG
кәшәнә	кәшәнәләрҙә	N;LOC;PL
хәбәр	хәбәрҙе	N;ACC;DEF;SG
йылан	йыланды	N;ACC;DEF;SG
бутҡа	бутҡаның	N;GEN;DEF;SG
һуҡыр сысҡан	һуҡыр сысҡандан	N;ABL;SG
бутҡа	бутҡа	N;NOM;SG
етем	етемдәргә	N;DAT;PL
быяла	быялаларҙа	N;LOC;PL
Ҡуҙы	Ҡуҙыларға	N;DAT;PL
әлифба	әлифбанан	N;ABL;SG
һөлөк	һөлөктәрҙән	N;ABL;PL
муйын	муйындарҙан	N;ABL;PL
миҙал	миҙалдар	N;NOM;PL
юрған	юрғанға	N;DAT;SG
төҫ	төҫкә	N;DAT;SG
ғәйеп	ғәйептән	N;ABL;SG
ҡойо	ҡойоно	N;ACC;DEF;SG
төбәк	төбәкте	N;ACC;DEF;SG
файҙа	файҙаларҙан	N;ABL;PL
хеҙмәт	хеҙмәттән	N;ABL;SG
нәтижә	нәтижәгә	N;DAT;SG
ҡыяр	ҡыярҙар	N;NOM;PL
өҫтәл	өҫтәлдәрҙең	N;GEN;DEF;PL
офоҡ	офоҡтоң	N;GEN;DEF;SG
үтек	үтектәрҙән	N;ABL;PL
мәжүси	мәжүсиҙәргә	N;DAT;PL
кәмә	кәмәләрҙән	N;ABL;PL
япраҡ	япраҡҡа	N;DAT;SG
ҡуян	ҡуяндың	N;GEN;DEF;SG
ҡотоҡ	ҡотоҡтар	N;NOM;PL
мәңгелек	мәңгелектәрҙә	ADJ;LOC;PL
һунар	һунарҙан	N;ABL;SG
яра	яраны	N;ACC;DEF;SG
байтал	байтал	N;NOM;SG
бейә	бейәгә	N;DAT;SG
маҡсат	маҡсаттарҙа	N;LOC;PL
донъя	донъяға	N;DAT;SG
балта	балталарға	N;DAT;PL
байрам	байрамдарҙың	N;GEN;DEF;PL
исем	исемдәргә	N;DAT;PL
йылға	йылғаларҙы	N;ACC;DEF;PL
кәмә	кәмәләрҙә	N;LOC;PL
үксә	үксәне	N;ACC;DEF;SG
етем	етемдәрҙе	N;ACC;DEF;PL
ижек	ижектәргә	N;DAT;PL
ғаилә	ғаилә	N;NOM;SG
тәүтормош	тәүтормоштарға	ADJ;DAT;PL
ҡоролоҡ	ҡоролоҡ	N;NOM;SG
Науруз	Науруз	N;DAT;SG
выждан	выжданға	N;DAT;SG
буран	бурандың	N;GEN;DEF;SG
алйырҙан	алйырҙандарҙа	N;LOC;PL
ғаилә	ғаиләгә	N;DAT;SG
диңгеҙ	диңгеҙҙәрҙең	N;GEN;DEF;PL
