ieusner	ieusneroyt	V;COND;SG;3;LGSPEC2
raenchonner	raenchonneray	V;IND;SG;1;FUT;LGSPEC2
enterrer	enterreroit	V;COND;SG;3;LGSPEC1
enhorter	enhorteriez	V;COND;PL;2;LGSPEC1
r'asseurer	r'asseurasse	V;IPFV;SBJV;SG;1;PST
desnouer	desnouyons	V;IPFV;IND;PL;1;PST;LGSPEC2
obliger	obligerions	V;COND;PL;1;LGSPEC1
contreroller	contrerolloys	V;IPFV;IND;SG;2;PST;LGSPEC2
nettoyer	nettoyons	V;IMP;PL;1
finir	finirez	V;IND;PL;2;FUT
destourner	destournes	V;SBJV;SG;2;PRS
rotter	rottons	V;SBJV;PL;1;PRS
desconseiller	desconseille	V;IND;SG;1;PRS
entrefraper	s'entrefraperent	V;PFV;IND;PL;3;PST
iniurier	iniurieroient	V;COND;PL;3;LGSPEC1
confesser	confessa	V;PFV;IND;SG;1;PST
cerchier	cerchieras	V;IND;SG;2;FUT
esveiller	esveillast	V;IPFV;SBJV;SG;3;PST
traveillier	traveillierai	V;IND;SG;1;FUT;LGSPEC1
faire	faces	V;SBJV;SG;2;PRS
fraper	frapyez	V;IPFV;IND;PL;2;PST;LGSPEC2
desieuner	desieunassions	V;IPFV;SBJV;PL;1;PST
detester	detestoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
traicter	tracterent	V;PFV;IND;PL;3;PST
preparer	prepares	V;SBJV;SG;2;PRS
aquitter	aquittois	V;IPFV;IND;SG;2;PST;LGSPEC1
ruyner	ruyneroyt	V;COND;SG;3;LGSPEC2
invader	invaderoyent	V;COND;PL;3;LGSPEC2
avoyr	avais	V;IPFV;IND;SG;2;PST
recorder	recordons	V;SBJV;PL;1;PRS
tabuster	tabusterent	V;PFV;IND;PL;3;PST
rappeller	rappelloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
verifier	verifieroyent	V;COND;PL;3;LGSPEC2
esternuer	esternue	V;IND;SG;3;PRS
advouer	advouyons	V;IPFV;IND;PL;1;PST;LGSPEC2
gouverner	gouvernerions	V;COND;PL;1;LGSPEC1
contreroller	contrerollerons	V;IND;PL;1;FUT
empescher	empescherez	V;IND;PL;2;FUT
engroisser	engroisseryons	V;COND;PL;1;LGSPEC2
inviter	inviteroit	V;COND;SG;3;LGSPEC1
enfelonner	enfelonne	V;IND;SG;3;PRS
deschainer	deschainerions	V;COND;PL;1;LGSPEC1
herrier	herriassions	V;IPFV;SBJV;PL;1;PST
delaisser	delaissast	V;IPFV;SBJV;SG;3;PST
effectuer	effectuions	V;IPFV;IND;PL;1;PST;LGSPEC1
arrester	arrestera	V;IND;SG;3;FUT
cerchier	cerchions	V;IMP;PL;1
fomenter	fomentons	V;IMP;PL;1
ralier	ralioient	V;IPFV;IND;PL;3;PST;LGSPEC1
esplucher	espluchez	V;SBJV;PL;2;PRS
exposer	exposastes	V;PFV;IND;PL;2;PST
reverer	reverons	V;SBJV;PL;1;PRS
effreer	effreons	V;IMP;PL;1
tourner	tournez	V;IMP;PL;2
lascher	laschera	V;IND;SG;3;FUT
auser	ausasses	V;IPFV;SBJV;SG;2;PST
ployer	ployiez	V;IPFV;IND;PL;2;PST;LGSPEC1
empirer	empiryez	V;IPFV;IND;PL;2;PST;LGSPEC2
bayser	baysent	V;IND;PL;3;PRS
desheriter	desheriterois	V;COND;SG;1;LGSPEC1
gaigner	gaignent	V;IND;PL;3;PRS
seeller	seellasmes	V;PFV;IND;PL;1;PST
raenchonner	raenchonneryons	V;COND;PL;1;LGSPEC2
fascher	fascherons	V;IND;PL;1;FUT
baptizer	baptizez	V;IND;PL;2;PRS
enchasser	enchassons	V;IND;PL;1;PRS
reserver	reservez	V;IMP;PL;2
emboucher	embouchez	V;IMP;PL;2
lyer	lyerent	V;PFV;IND;PL;3;PST
bancqueter	bancquete	V;IMP;SG;2
desadvouer	desadvouerions	V;COND;PL;1;LGSPEC1
esparpiller	esparpillerois	V;COND;SG;1;LGSPEC1
poiser	poisyons	V;IPFV;IND;PL;1;PST;LGSPEC2
enchargier	enchargiez	V;IPFV;IND;PL;2;PST;LGSPEC1
retirer	retiroys	V;IPFV;IND;SG;2;PST;LGSPEC2
desyrer	desyroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
iniurier	iniurioyent	V;IPFV;IND;PL;3;PST;LGSPEC2
gouverner	gouvernois	V;IPFV;IND;SG;2;PST;LGSPEC1
posseder	possederoys	V;COND;SG;1;LGSPEC2
raenchonner	raenchonna	V;PFV;IND;SG;1;PST
deschainer	deschainoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
entrefrapper	vousentrefrappiez	V;IPFV;IND;PL;2;PST;LGSPEC1
affermer	affermer	V;NFIN
trembler	tremblions	V;IPFV;IND;PL;1;PST;LGSPEC1
solliciter	sollicitons	V;IND;PL;1;PRS
espouser	espouseroient	V;COND;PL;3;LGSPEC1
guarder	guardasse	V;IPFV;SBJV;SG;1;PST
couster	coustasse	V;IPFV;SBJV;SG;1;PST
reguarder	reguarde	V;IND;SG;3;PRS
empenser	empenseroient	V;COND;PL;3;LGSPEC1
suffocquer	suffocque	V;SBJV;SG;1;PRS
effreer	effreoys	V;IPFV;IND;SG;1;PST;LGSPEC2
rappeller	rappellera	V;IND;SG;3;FUT
enconvenencier	enconvenençoys	V;IPFV;IND;SG;1;PST;LGSPEC2
engroisser	engroissasmes	V;PFV;IND;PL;1;PST
cerchier	cerchieront	V;IND;PL;3;FUT
evaporer	evaporerai	V;IND;SG;1;FUT;LGSPEC1
reietter	reiettiez	V;IPFV;IND;PL;2;PST;LGSPEC1
estourdir	estourdirons	V;IND;PL;1;FUT
escarter	escarte	V;IND;SG;3;PRS
bobeliner	bobelinoient	V;IPFV;IND;PL;3;PST;LGSPEC1
soulaiger	soulaigent	V;IND;PL;3;PRS
fortiffier	fortiffions	V;IND;PL;1;PRS
prester	presteroys	V;COND;SG;1;LGSPEC2
hostoier	hostoioyt	V;IPFV;IND;SG;3;PST;LGSPEC2
gouster	gousta	V;PFV;IND;SG;3;PST
poiser	poiseryons	V;COND;PL;1;LGSPEC2
herrier	herria	V;PFV;IND;SG;1;PST
enseignier	enseignez	V;IMP;PL;2
reguarder	reguardast	V;IPFV;SBJV;SG;3;PST
desver	desvons	V;IMP;PL;1
haster	hastois	V;IPFV;IND;SG;1;PST;LGSPEC1
chevauchier	chevauchoys	V;IPFV;IND;SG;1;PST;LGSPEC2
penetrer	penetrassiez	V;IPFV;SBJV;PL;2;PST
fascher	faschasses	V;IPFV;SBJV;SG;2;PST
temprer	temprasses	V;IPFV;SBJV;SG;2;PST
ieusner	ieusnoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
houssepillier	houssepilliez	V;IND;PL;2;PRS
retirer	retirerai	V;IND;SG;1;FUT;LGSPEC1
aquitter	aquitte	V;SBJV;SG;3;PRS
subiuguier	subiuguieryez	V;COND;PL;2;LGSPEC2
traittier	traittions	V;IPFV;IND;PL;1;PST;LGSPEC1
navrer	navra	V;PFV;IND;SG;1;PST
eschapper	eschappois	V;IPFV;IND;SG;2;PST;LGSPEC1
invader	invadez	V;SBJV;PL;2;PRS
evaporer	evapore	V;SBJV;SG;1;PRS
contreroller	contrerolle	V;SBJV;SG;1;PRS
courrouchier	courrouchoient	V;IPFV;IND;PL;3;PST;LGSPEC1
gaspiller	gaspillastes	V;PFV;IND;PL;2;PST
reguarder	reguardyons	V;IPFV;IND;PL;1;PST;LGSPEC2
asseurer	asseure	V;IMP;SG;2
esbaucher	esbauchastes	V;PFV;IND;PL;2;PST
affamer	affamerois	V;COND;SG;1;LGSPEC1
esquacher	esquachent	V;IND;PL;3;PRS
diviner	divinions	V;IPFV;IND;PL;1;PST;LGSPEC1
debaracer	debaraçons	V;IPFV;IND;PL;1;PST;LGSPEC2
bobeliner	bobelinez	V;IMP;PL;2
desmettre	desmettriez	V;COND;PL;2
deffier	deffierois	V;COND;SG;1;LGSPEC1
haittier	haittent	V;IND;PL;3;PRS
frapper	frappent	V;SBJV;PL;3;PRS
veigler	veigleryons	V;COND;PL;1;LGSPEC2
aracher	arachent	V;SBJV;PL;3;PRS
courrouchier	courrouche	V;IMP;SG;2
esplucher	espluche	V;IND;SG;1;PRS
engroisser	engroissoys	V;IPFV;IND;SG;1;PST;LGSPEC2
traicter	tractast	V;IPFV;SBJV;SG;3;PST
esplucher	espluchera	V;IND;SG;3;FUT
temprer	tempreroient	V;COND;PL;3;LGSPEC1
descouchier	descouchassent	V;IPFV;SBJV;PL;3;PST
desbaucher	desbauche	V;SBJV;SG;3;PRS
fraper	fraperyons	V;COND;PL;1;LGSPEC2
resister	resista	V;PFV;IND;SG;1;PST
meriter	meritoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
esparpiller	esparpillassent	V;IPFV;SBJV;PL;3;PST
esplucher	esplucha	V;PFV;IND;SG;3;PST
emerger	emergeryons	V;COND;PL;1;LGSPEC2
finir	finissions	V;IPFV;IND;PL;1;PST
blasphemer	blasphemeryons	V;COND;PL;1;LGSPEC2
desver	desve	V;SBJV;SG;3;PRS
esveiller	esveillons	V;IMP;PL;1
piller	pilleroyt	V;COND;SG;3;LGSPEC2
empieger	empiege	V;IND;SG;3;PRS
detester	detestas	V;PFV;IND;SG;2;PST
desarmer	desarmeroient	V;COND;PL;3;LGSPEC1
preferer	prefera	V;PFV;IND;SG;3;PST
essayer	essayois	V;IPFV;IND;SG;2;PST;LGSPEC1
hebergier	hebergions	V;IND;PL;1;PRS
effectuer	effectueroys	V;COND;SG;1;LGSPEC2
enchargier	enchargierez	V;IND;PL;2;FUT
enchasser	enchassiez	V;IPFV;IND;PL;2;PST;LGSPEC1
esgaler	esgalois	V;IPFV;IND;SG;1;PST;LGSPEC1
praesider	praesidions	V;IPFV;IND;PL;1;PST;LGSPEC1
entredemander	nousentredemanderions	V;COND;PL;1;LGSPEC1
poiser	poisons	V;SBJV;PL;1;PRS
rotter	rottez	V;SBJV;PL;2;PRS
occurrer	occurroient	V;IPFV;IND;PL;3;PST;LGSPEC1
souspirer	souspiryons	V;IPFV;IND;PL;1;PST;LGSPEC2
enconvenencier	enconvenence	V;IND;SG;3;PRS
debaracer	debaraças	V;PFV;IND;SG;2;PST
iecter	iectoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
desinfecter	desinfecteriez	V;COND;PL;2;LGSPEC1
invader	invadois	V;IPFV;IND;SG;1;PST;LGSPEC1
destourner	destournassent	V;IPFV;SBJV;PL;3;PST
impugner	impugne	V;IND;SG;3;PRS
supposer	supposoient	V;IPFV;IND;PL;3;PST;LGSPEC1
faire	faciez	V;SBJV;PL;2;PRS
escarter	escartasmes	V;PFV;IND;PL;1;PST
appeller	appellons	V;IND;PL;1;PRS
deschainer	deschainez	V;SBJV;PL;2;PRS
esmerveillier	esmerveilles	V;SBJV;SG;2;PRS
bayser	bayseroient	V;COND;PL;3;LGSPEC1
aguyser	aguysast	V;IPFV;SBJV;SG;3;PST
escapper	escapperai	V;IND;SG;1;FUT;LGSPEC1
pisser	pissas	V;PFV;IND;SG;2;PST
estudier	estudiois	V;IPFV;IND;SG;2;PST;LGSPEC1
soupper	souppyez	V;IPFV;IND;PL;2;PST;LGSPEC2
enterrer	enterrent	V;IND;PL;3;PRS
esperer	esperoit	V;IPFV;IND;SG;3;PST;LGSPEC1
enconcher	enconcheray	V;IND;SG;1;FUT;LGSPEC2
auser	ausassions	V;IPFV;SBJV;PL;1;PST
emerger	emergeroyent	V;COND;PL;3;LGSPEC2
deschainer	deschainiez	V;IPFV;IND;PL;2;PST;LGSPEC1
demesler	demeslyons	V;IPFV;IND;PL;1;PST;LGSPEC2
hebergier	hebergeastes	V;PFV;IND;PL;2;PST
denunchier	denunchiyez	V;IPFV;IND;PL;2;PST;LGSPEC2
abhorrer	abhorrez	V;SBJV;PL;2;PRS
enterrer	enterre	V;IMP;SG;2
translater	translates	V;IND;SG;2;PRS
prier	prierai	V;IND;SG;1;FUT;LGSPEC1
solliciter	sollicitoit	V;IPFV;IND;SG;3;PST;LGSPEC1
eschapper	eschappyons	V;IPFV;IND;PL;1;PST;LGSPEC2
haster	hasterai	V;IND;SG;1;FUT;LGSPEC1
essilier	essilieront	V;IND;PL;3;FUT
esveiller	esveillez	V;IMP;PL;2
seeller	seelloit	V;IPFV;IND;SG;3;PST;LGSPEC1
ployer	ployes	V;SBJV;SG;2;PRS
fascher	fascheray	V;IND;SG;1;FUT;LGSPEC2
confesser	confessiez	V;IPFV;IND;PL;2;PST;LGSPEC1
emboucher	embouchez	V;IND;PL;2;PRS
penetrer	penetrez	V;SBJV;PL;2;PRS
entrefrapper	vous entrefrappez	V;SBJV;PL;2;PRS
abhorrer	abhorreryons	V;COND;PL;1;LGSPEC2
verifier	verifiez	V;IMP;PL;2
esplucher	espluchoys	V;IPFV;IND;SG;2;PST;LGSPEC2
tyrer	tyroit	V;IPFV;IND;SG;3;PST;LGSPEC1
estouffer	estouffer	V;NFIN
supposer	supposasmes	V;PFV;IND;PL;1;PST
invader	invadasmes	V;PFV;IND;PL;1;PST
soupper	souppyons	V;IPFV;IND;PL;1;PST;LGSPEC2
abayer	abayoit	V;IPFV;IND;SG;3;PST;LGSPEC1
moderer	moderasse	V;IPFV;SBJV;SG;1;PST
debaracer	debaraceras	V;IND;SG;2;FUT
hebergier	hebergiez	V;IPFV;IND;PL;2;PST;LGSPEC1
eschapper	eschapperas	V;IND;SG;2;FUT
fascher	faschons	V;IMP;PL;1
finir	finiroys	V;COND;SG;1;LGSPEC2
desister	desisteroyt	V;COND;SG;3;LGSPEC2
ieusner	ieusneryons	V;COND;PL;1;LGSPEC2
cerchier	cerchierois	V;COND;SG;2;LGSPEC1
manger	mangeons	V;IMP;PL;1
accuser	accuseryez	V;COND;PL;2;LGSPEC2
oublyer	oublyeryez	V;COND;PL;2;LGSPEC2
remercyer	remercyastes	V;PFV;IND;PL;2;PST
couster	coustassiez	V;IPFV;SBJV;PL;2;PST
demesler	demeslast	V;IPFV;SBJV;SG;3;PST
picquer	picque	V;IMP;SG;2
solliciter	solliciterons	V;IND;PL;1;FUT
adviser	advisoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
pourchasser	pourchasseriez	V;COND;PL;2;LGSPEC1
faire	feroit	V;COND;SG;3;LGSPEC1
retirer	retirons	V;SBJV;PL;1;PRS
saulter	saultons	V;SBJV;PL;1;PRS
invader	invaderez	V;IND;PL;2;FUT
oublyer	oublyeroit	V;COND;SG;3;LGSPEC1
esplucher	espluchions	V;IPFV;IND;PL;1;PST;LGSPEC1
desver	desvons	V;IND;PL;1;PRS
accointer	accointe	V;IND;SG;1;PRS
despencer	despencions	V;IPFV;IND;PL;1;PST;LGSPEC1
mettre	mettroys	V;COND;SG;1;LGSPEC2
communicquer	communicqueray	V;IND;SG;1;FUT;LGSPEC2
sçavoir	sçavez	V;IND;PL;2;PRS
executer	executeroys	V;COND;SG;2;LGSPEC2
essayer	essayons	V;SBJV;PL;1;PRS
mesler	meslassions	V;IPFV;SBJV;PL;1;PST
ralier	ralieroyent	V;COND;PL;3;LGSPEC2
participer	participe	V;SBJV;SG;1;PRS
mettre	mettrois	V;COND;SG;2;LGSPEC1
enseignier	enseignes	V;IND;SG;2;PRS
aracher	arachons	V;IND;PL;1;PRS
subiuguier	subiuguierois	V;COND;SG;2;LGSPEC1
encontrer	encontra	V;PFV;IND;SG;1;PST
enterrer	enterrer	V;NFIN
emprunter	emprunteroyt	V;COND;SG;3;LGSPEC2
diviner	divine	V;IMP;SG;2
enchasser	enchassent	V;IND;PL;3;PRS
esvertuer	esvertuent	V;SBJV;PL;3;PRS
occurrer	occurrois	V;IPFV;IND;SG;1;PST;LGSPEC1
enferrer	enferreryez	V;COND;PL;2;LGSPEC2
despencer	despençoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
lascher	laschoys	V;IPFV;IND;SG;2;PST;LGSPEC2
finir	finirent	V;PFV;IND;PL;3;PST
entrefraper	nousentrefraperions	V;COND;PL;1;LGSPEC1
emboucher	embouchons	V;SBJV;PL;1;PRS
reserver	reservassent	V;IPFV;SBJV;PL;3;PST
piller	pilla	V;PFV;IND;SG;1;PST
souspirer	souspireras	V;IND;SG;2;FUT
haster	hastoys	V;IPFV;IND;SG;1;PST;LGSPEC2
entredemander	s'entredemandoient	V;IPFV;IND;PL;3;PST;LGSPEC1
escumer	escumas	V;PFV;IND;SG;2;PST
superseder	supersede	V;IND;SG;1;PRS
empescher	empescheras	V;IND;SG;2;FUT
desrober	desroberoys	V;COND;SG;1;LGSPEC2
seeller	seelles	V;IND;SG;2;PRS
supposer	supposes	V;IND;SG;2;PRS
aracher	arachiez	V;IPFV;IND;PL;2;PST;LGSPEC1
gaspiller	gaspilleroient	V;COND;PL;3;LGSPEC1
depescher	depeschassent	V;IPFV;SBJV;PL;3;PST
affamer	affamoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
fascher	faschas	V;PFV;IND;SG;2;PST
approuchier	approuchieroyt	V;COND;SG;3;LGSPEC2
desconseiller	desconseilloys	V;IPFV;IND;SG;2;PST;LGSPEC2
enfelonner	enfelonnassions	V;IPFV;SBJV;PL;1;PST
blasphemer	blasphemoient	V;IPFV;IND;PL;3;PST;LGSPEC1
cauterizer	cauterizois	V;IPFV;IND;SG;1;PST;LGSPEC1
communicquer	communicqueroys	V;COND;SG;2;LGSPEC2
escorner	escornes	V;SBJV;SG;2;PRS
loger	loge	V;IND;SG;1;PRS
deslacer	deslacer	V;NFIN
abayer	abayyons	V;IPFV;IND;PL;1;PST;LGSPEC2
enconvenencier	enconvenenças	V;PFV;IND;SG;2;PST
traveillier	traveillieriez	V;COND;PL;2;LGSPEC1
pourchasser	pourchassoys	V;IPFV;IND;SG;2;PST;LGSPEC2
desplacer	desplace	V;IMP;SG;2
plier	pliois	V;IPFV;IND;SG;2;PST;LGSPEC1
pourchasser	pourchassa	V;PFV;IND;SG;3;PST
reietter	reiettyons	V;IPFV;IND;PL;1;PST;LGSPEC2
herrier	herrieroient	V;COND;PL;3;LGSPEC1
oultrager	oultrageois	V;IPFV;IND;SG;1;PST;LGSPEC1
deffier	deffiez	V;SBJV;PL;2;PRS
entredemander	vousentredemanderiez	V;COND;PL;2;LGSPEC1
melancholier	melancholiastes	V;PFV;IND;PL;2;PST
marier	marieront	V;IND;PL;3;FUT
esquacher	esquacherions	V;COND;PL;1;LGSPEC1
participer	participiez	V;IPFV;IND;PL;2;PST;LGSPEC1
mectre	mectra	V;IND;SG;3;FUT
estonner	estonnerez	V;IND;PL;2;FUT
estacher	estachent	V;SBJV;PL;3;PRS
enferrer	enferre	V;SBJV;SG;1;PRS
enseignier	enseignasmes	V;PFV;IND;PL;1;PST
derver	dervassent	V;IPFV;SBJV;PL;3;PST
executer	executions	V;IPFV;IND;PL;1;PST;LGSPEC1
enfelonner	enfelonna	V;PFV;IND;SG;3;PST
repraesenter	repraesenteroys	V;COND;SG;2;LGSPEC2
cauterizer	cauteriziez	V;IPFV;IND;PL;2;PST;LGSPEC1
resider	resident	V;IND;PL;3;PRS
baptizer	baptizons	V;SBJV;PL;1;PRS
ployer	ployons	V;IND;PL;1;PRS
considerer	considereray	V;IND;SG;1;FUT;LGSPEC2
estudier	estudie	V;IMP;SG;2
desinfecter	desinfecte	V;SBJV;SG;1;PRS
nombrer	nombreras	V;IND;SG;2;FUT
descouchier	descouchieroys	V;COND;SG;2;LGSPEC2
iecter	iecteroys	V;COND;SG;1;LGSPEC2
loger	logeois	V;IPFV;IND;SG;2;PST;LGSPEC1
aler	yrons	V;IND;PL;1;FUT;LGSPEC2
enorter	enortois	V;IPFV;IND;SG;2;PST;LGSPEC1
toucher	touchera	V;IND;SG;3;FUT
renouveller	renouvellastes	V;PFV;IND;PL;2;PST
affermer	afferment	V;SBJV;PL;3;PRS
moustrer	moustrasmes	V;PFV;IND;PL;1;PST
enterrer	enterryons	V;IPFV;IND;PL;1;PST;LGSPEC2
adapter	adapte	V;IND;SG;1;PRS
visiter	visitoit	V;IPFV;IND;SG;3;PST;LGSPEC1
loger	logyez	V;IPFV;IND;PL;2;PST;LGSPEC2
esmerveillier	esmerveilliez	V;IND;PL;2;PRS
jecter	jecta	V;PFV;IND;SG;3;PST
mercyer	mercyoys	V;IPFV;IND;SG;1;PST;LGSPEC2
fomenter	fomentasse	V;IPFV;SBJV;SG;1;PST
lurrer	lurrerions	V;COND;PL;1;LGSPEC1
excuser	excuserois	V;COND;SG;2;LGSPEC1
manger	mange	V;IND;SG;1;PRS
estourdir	estourdiroys	V;COND;SG;1;LGSPEC2
communicquer	communicquiez	V;IPFV;IND;PL;2;PST;LGSPEC1
affermer	affermerons	V;IND;PL;1;FUT
estinceller	estincelleroyt	V;COND;SG;3;LGSPEC2
lascher	laschoit	V;IPFV;IND;SG;3;PST;LGSPEC1
iniurier	iniurierions	V;COND;PL;1;LGSPEC1
prosperer	prospereroys	V;COND;SG;1;LGSPEC2
soupper	soupperons	V;IND;PL;1;FUT
croniquier	croniquieroient	V;COND;PL;3;LGSPEC1
reietter	reietteriez	V;COND;PL;2;LGSPEC1
mercyer	mercyions	V;IPFV;IND;PL;1;PST;LGSPEC1
aracher	arachassent	V;IPFV;SBJV;PL;3;PST
resister	resistoys	V;IPFV;IND;SG;1;PST;LGSPEC2
atourner	atournerions	V;COND;PL;1;LGSPEC1
tourmenter	tourmentoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
mesler	meslerai	V;IND;SG;1;FUT;LGSPEC1
subiuguier	subiuguieras	V;IND;SG;2;FUT
estudier	estudiyez	V;IPFV;IND;PL;2;PST;LGSPEC2
abhorrer	abhorrastes	V;PFV;IND;PL;2;PST
entreruyner	vous entreruynerez	V;IND;PL;2;FUT
escorner	escornerois	V;COND;SG;2;LGSPEC1
communicquer	communicqueryez	V;COND;PL;2;LGSPEC2
desrober	desroberont	V;IND;PL;3;FUT
doubter	doubtons	V;IND;PL;1;PRS
commencer	commençons	V;IMP;PL;1
eriger	erige	V;SBJV;SG;3;PRS
enhorter	enhorte	V;IND;SG;3;PRS
ymaginer	ymagineroys	V;COND;SG;2;LGSPEC2
loger	logeroys	V;COND;SG;1;LGSPEC2
fromenter	fromentasmes	V;PFV;IND;PL;1;PST
empescher	empeschera	V;IND;SG;3;FUT
excuser	excuseront	V;IND;PL;3;FUT
blasphemer	blasphemera	V;IND;SG;3;FUT
enferrer	enferre	V;IND;SG;3;PRS
entredemander	entredemandez vous	V;IMP;PL;2
avoir	ayons	V;IMP;PL;1;LGSPEC1
debaracer	debaracions	V;IPFV;IND;PL;1;PST;LGSPEC1
desconseiller	desconseillois	V;IPFV;IND;SG;1;PST;LGSPEC1
oultrager	oultrageast	V;IPFV;SBJV;SG;3;PST
esgaler	esgaleroyent	V;COND;PL;3;LGSPEC2
baptiser	baptisent	V;SBJV;PL;3;PRS
mercyer	mercyasmes	V;PFV;IND;PL;1;PST
enconcher	enconcherois	V;COND;SG;2;LGSPEC1
atourner	atournyons	V;IPFV;IND;PL;1;PST;LGSPEC2
inquieter	inquietasse	V;IPFV;SBJV;SG;1;PST
esvertuer	esvertuasse	V;IPFV;SBJV;SG;1;PST
rotter	rotteryons	V;COND;PL;1;LGSPEC2
reverer	reveroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
nombrer	nombra	V;PFV;IND;SG;3;PST
destabler	destablons	V;IND;PL;1;PRS
prosperer	prospereroyent	V;COND;PL;3;LGSPEC2
despouiller	despouillyez	V;IPFV;IND;PL;2;PST;LGSPEC2
translater	translaterois	V;COND;SG;2;LGSPEC1
rappeller	rappellasmes	V;PFV;IND;PL;1;PST
contribuer	contribueroys	V;COND;SG;2;LGSPEC2
esternuer	esternua	V;PFV;IND;SG;1;PST
desbaucher	desbaucheriez	V;COND;PL;2;LGSPEC1
descouchier	descouchiez	V;IMP;PL;2
esternuer	esternuerons	V;IND;PL;1;FUT
tourner	tourneryons	V;COND;PL;1;LGSPEC2
deschainer	deschainas	V;PFV;IND;SG;2;PST
explicquer	explicquastes	V;PFV;IND;PL;2;PST
fluir	fluissent	V;IPFV;SBJV;PL;3;PST
engroisser	engroisserai	V;IND;SG;1;FUT;LGSPEC1
eslever	esleva	V;PFV;IND;SG;3;PST
estirer	estirast	V;IPFV;SBJV;SG;3;PST
lascher	laschassiez	V;IPFV;SBJV;PL;2;PST
gaigner	gaignerois	V;COND;SG;2;LGSPEC1
entrefrapper	entrefrapperoyent	V;COND;PL;3;LGSPEC2
r'asseurer	r'asseurons	V;SBJV;PL;1;PRS
desmettre	desmis	V;PFV;IND;SG;2;PST
contreroller	contrerolleroys	V;COND;SG;1;LGSPEC2
cerchier	cerchieroys	V;COND;SG;1;LGSPEC2
adiouster	adiousteroit	V;COND;SG;3;LGSPEC1
gaster	gaste	V;SBJV;SG;3;PRS
esvertuer	esvertuiez	V;IPFV;IND;PL;2;PST;LGSPEC1
iouer	iouerois	V;COND;SG;1;LGSPEC1
nombrer	nombroient	V;IPFV;IND;PL;3;PST;LGSPEC1
contrepoiser	contrepoisassent	V;IPFV;SBJV;PL;3;PST
affermer	affermeront	V;IND;PL;3;FUT
desieuner	desieuneront	V;IND;PL;3;FUT
guarder	guarderoient	V;COND;PL;3;LGSPEC1
enconvenencier	enconvenençois	V;IPFV;IND;SG;2;PST;LGSPEC1
faucer	faucez	V;IMP;PL;2
remercyer	remercyions	V;IPFV;IND;PL;1;PST;LGSPEC1
r'asseurer	r'asseurassent	V;IPFV;SBJV;PL;3;PST
auser	ausez	V;IMP;PL;2
voller	volles	V;IND;SG;2;PRS
jecter	jectasses	V;IPFV;SBJV;SG;2;PST
estiquier	estiquassent	V;IPFV;SBJV;PL;3;PST
recorder	recordez	V;SBJV;PL;2;PRS
lyer	lyez	V;SBJV;PL;2;PRS
veigler	veigleroit	V;COND;SG;3;LGSPEC1
accorder	accordons	V;IND;PL;1;PRS
proffiter	proffiteroyt	V;COND;SG;3;LGSPEC2
fomenter	fomentes	V;IND;SG;2;PRS
escumer	escumoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
esquacher	esquacherois	V;COND;SG;2;LGSPEC1
empescher	empeschoient	V;IPFV;IND;PL;3;PST;LGSPEC1
heurter	heurtasses	V;IPFV;SBJV;SG;2;PST
preceder	precedastes	V;PFV;IND;PL;2;PST
esventer	esventassiez	V;IPFV;SBJV;PL;2;PST
veigler	veigleroys	V;COND;SG;1;LGSPEC2
esventer	esventast	V;IPFV;SBJV;SG;3;PST
destabler	destablerai	V;IND;SG;1;FUT;LGSPEC1
deslacer	delace	V;IND;SG;3;PRS
nombrer	nombreryez	V;COND;PL;2;LGSPEC2
traicter	tracterons	V;IND;PL;1;FUT
faucer	fauceroit	V;COND;SG;3;LGSPEC1
communicquer	communicque	V;SBJV;SG;1;PRS
toucher	touchasmes	V;PFV;IND;PL;1;PST
importuner	importunasmes	V;PFV;IND;PL;1;PST
depescher	depeschyons	V;IPFV;IND;PL;1;PST;LGSPEC2
affamer	affamoys	V;IPFV;IND;SG;2;PST;LGSPEC2
posseder	possedez	V;IND;PL;2;PRS
enconvenencier	enconvenencieront	V;IND;PL;3;FUT
souspirer	souspire	V;IND;SG;1;PRS
eriger	erigeassent	V;IPFV;SBJV;PL;3;PST
haittier	haittyons	V;IPFV;IND;PL;1;PST;LGSPEC2
gouverner	gouvernastes	V;PFV;IND;PL;2;PST
repraesenter	repraesentoys	V;IPFV;IND;SG;1;PST;LGSPEC2
resister	resistons	V;IND;PL;1;PRS
souspirer	souspirons	V;IND;PL;1;PRS
engroisser	engroissois	V;IPFV;IND;SG;2;PST;LGSPEC1
plier	pliasse	V;IPFV;SBJV;SG;1;PST
subiecter	subiecte	V;IMP;SG;2
derver	derviez	V;IPFV;IND;PL;2;PST;LGSPEC1
desinfecter	desinfecte	V;SBJV;SG;3;PRS
rappeller	rappelloit	V;IPFV;IND;SG;3;PST;LGSPEC1
suffocquer	suffocqueroys	V;COND;SG;1;LGSPEC2
entredemander	nous entredemanderons	V;IND;PL;1;FUT
mucer	muces	V;IND;SG;2;PRS
aracher	arachassions	V;IPFV;SBJV;PL;1;PST
embausmer	embausma	V;PFV;IND;SG;1;PST
gaigner	gaignastes	V;PFV;IND;PL;2;PST
desyrer	desyroys	V;IPFV;IND;SG;1;PST;LGSPEC2
brusler	brusler	V;NFIN
voller	volle	V;SBJV;SG;3;PRS
inviter	invitast	V;IPFV;SBJV;SG;3;PST
ymaginer	ymagineroit	V;COND;SG;3;LGSPEC1
voller	volleray	V;IND;SG;1;FUT;LGSPEC2
voller	vollassiez	V;IPFV;SBJV;PL;2;PST
penetrer	penetreroient	V;COND;PL;3;LGSPEC1
abayer	abayerois	V;COND;SG;1;LGSPEC1
desnouer	desnoue	V;IND;SG;1;PRS
sçavoir	sceusses	V;IPFV;SBJV;SG;2;PST
posseder	posseda	V;PFV;IND;SG;3;PST
fascher	faschions	V;IPFV;IND;PL;1;PST;LGSPEC1
confesser	confesses	V;IND;SG;2;PRS
veiller	veillons	V;SBJV;PL;1;PRS
penetrer	penetrerons	V;IND;PL;1;FUT
desister	desisteront	V;IND;PL;3;FUT
desadvouer	desadvoueriez	V;COND;PL;2;LGSPEC1
pourchasser	pourchassasmes	V;PFV;IND;PL;1;PST
regarder	regardoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
estoffer	estofferay	V;IND;SG;1;FUT;LGSPEC2
reverer	revere	V;IMP;SG;2
oublyer	oublyyons	V;IPFV;IND;PL;1;PST;LGSPEC2
auser	ausast	V;IPFV;SBJV;SG;3;PST
bobeliner	bobelinassent	V;IPFV;SBJV;PL;3;PST
gaspiller	gaspillerez	V;IND;PL;2;FUT
rappeller	rappellyons	V;IPFV;IND;PL;1;PST;LGSPEC2
occurrer	occurre	V;IND;SG;1;PRS
participer	participoys	V;IPFV;IND;SG;2;PST;LGSPEC2
adapter	adaptyons	V;IPFV;IND;PL;1;PST;LGSPEC2
aracher	arachez	V;SBJV;PL;2;PRS
preceder	precedons	V;IND;PL;1;PRS
destourner	destournas	V;PFV;IND;SG;2;PST
cerchier	cerchierons	V;IND;PL;1;FUT
passer	passastes	V;PFV;IND;PL;2;PST
navrer	navrassiez	V;IPFV;SBJV;PL;2;PST
desmettre	desmet	V;IND;SG;3;PRS
resider	resida	V;PFV;IND;SG;3;PST
participer	participe	V;IND;SG;3;PRS
desnouer	desnouoit	V;IPFV;IND;SG;3;PST;LGSPEC1
desadvouer	desadvoueroyt	V;COND;SG;3;LGSPEC2
prier	prioyt	V;IPFV;IND;SG;3;PST;LGSPEC2
rappeller	rappelleront	V;IND;PL;3;FUT
asseurer	asseuroient	V;IPFV;IND;PL;3;PST;LGSPEC1
iniurier	iniurierai	V;IND;SG;1;FUT;LGSPEC1
pourmener	pourmeneryons	V;COND;PL;1;LGSPEC2
subiecter	subiecteriez	V;COND;PL;2;LGSPEC1
importuner	importuneront	V;IND;PL;3;FUT
enconcher	enconche	V;IND;SG;3;PRS
moderer	modereront	V;IND;PL;3;FUT
advouer	advouast	V;IPFV;SBJV;SG;3;PST
deschainer	deschaine	V;SBJV;SG;3;PRS
eschapper	eschappast	V;IPFV;SBJV;SG;3;PST
sçavoir	sçavoyent	V;IPFV;IND;PL;3;PST;LGSPEC1
rotter	rottassiez	V;IPFV;SBJV;PL;2;PST
souspirer	souspireroys	V;COND;SG;1;LGSPEC2
fomenter	fomentoit	V;IPFV;IND;SG;3;PST;LGSPEC1
desyrer	desyrent	V;SBJV;PL;3;PRS
haittier	haittier	V;NFIN
destourner	destourna	V;PFV;IND;SG;1;PST
rejecter	rejecte	V;IMP;SG;2
rincer	rincerions	V;COND;PL;1;LGSPEC1
empieger	empiegeasse	V;IPFV;SBJV;SG;1;PST
frapper	frappoient	V;IPFV;IND;PL;3;PST;LGSPEC1
enchasser	enchassois	V;IPFV;IND;SG;1;PST;LGSPEC1
rebarber	rebarboys	V;IPFV;IND;SG;2;PST;LGSPEC2
retirer	retiroit	V;IPFV;IND;SG;3;PST;LGSPEC1
gaigner	gaignez	V;IND;PL;2;PRS
chevauchier	chevauchieras	V;IND;SG;2;FUT
frapper	frappois	V;IPFV;IND;SG;1;PST;LGSPEC1
rejecter	rejectons	V;IMP;PL;1
resider	residerai	V;IND;SG;1;FUT;LGSPEC1
croniquier	croniquieryons	V;COND;PL;1;LGSPEC2
cerchier	cerchieroys	V;COND;SG;2;LGSPEC2
suffocquer	suffocqueriez	V;COND;PL;2;LGSPEC1
apatir	apatissons	V;IMP;PL;1
explorer	explorons	V;IMP;PL;1
empenser	empenserent	V;PFV;IND;PL;3;PST
visiter	visiteryez	V;COND;PL;2;LGSPEC2
veiller	veille	V;IMP;SG;2
desmettre	desmettroyent	V;COND;PL;3;LGSPEC2
recorder	recordast	V;IPFV;SBJV;SG;3;PST
esperer	esperassent	V;IPFV;SBJV;PL;3;PST
esbaucher	esbaucheryons	V;COND;PL;1;LGSPEC2
lurrer	lurreroient	V;COND;PL;3;LGSPEC1
desyrer	desyrois	V;IPFV;IND;SG;1;PST;LGSPEC1
getter	gettassions	V;IPFV;SBJV;PL;1;PST
empirer	empiroit	V;IPFV;IND;SG;3;PST;LGSPEC1
manger	mangeoys	V;IPFV;IND;SG;1;PST;LGSPEC2
arrester	arrestassions	V;IPFV;SBJV;PL;1;PST
desrober	desroboient	V;IPFV;IND;PL;3;PST;LGSPEC1
aler	yroie	V;IND;SG;1;FUT;LGSPEC2
cabasser	cabassois	V;IPFV;IND;SG;1;PST;LGSPEC1
nettoyer	nettoyeriez	V;COND;PL;2;LGSPEC1
occurrer	occurra	V;PFV;IND;SG;1;PST
encontrer	encontroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
deffier	deffions	V;IND;PL;1;PRS
enferrer	enferreroyent	V;COND;PL;3;LGSPEC2
fraper	frapes	V;IND;SG;2;PRS
faucer	fauçons	V;IND;PL;1;PRS
desister	desistes	V;IND;SG;2;PRS
enferrer	enferrassent	V;IPFV;SBJV;PL;3;PST
aler	alons	V;IND;PL;1;PRS
gaigner	gaignast	V;IPFV;SBJV;SG;3;PST
prier	prier	V;NFIN
estre	soyez	V;SBJV;PL;2;PRS
detranchier	detranchierent	V;PFV;IND;PL;3;PST
praeparer	praepara	V;PFV;IND;SG;3;PST
saulter	saultastes	V;PFV;IND;PL;2;PST
resister	resista	V;PFV;IND;SG;3;PST
honnourer	honnourerez	V;IND;PL;2;FUT
bransler	branslons	V;IMP;PL;1
piller	pillerons	V;IND;PL;1;FUT
escapper	escappoys	V;IPFV;IND;SG;1;PST;LGSPEC2
aracher	aracha	V;PFV;IND;SG;3;PST
arrester	arresterez	V;IND;PL;2;FUT
posseder	possederoient	V;COND;PL;3;LGSPEC1
prier	priassent	V;IPFV;SBJV;PL;3;PST
cabasser	cabassons	V;SBJV;PL;1;PRS
escorner	escornons	V;IMP;PL;1
rejecter	rejectent	V;IND;PL;3;PRS
rejecter	rejectoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
moderer	moderiez	V;IPFV;IND;PL;2;PST;LGSPEC1
esquacher	esquachast	V;IPFV;SBJV;SG;3;PST
bancqueter	bancqueteroys	V;COND;SG;2;LGSPEC2
asseurer	asseureriez	V;COND;PL;2;LGSPEC1
detester	detestassent	V;IPFV;SBJV;PL;3;PST
desbaucher	desbauche	V;IMP;SG;2
mesler	mesleroys	V;COND;SG;2;LGSPEC2
emprunter	emprunterent	V;PFV;IND;PL;3;PST
desrober	desroberoyt	V;COND;SG;3;LGSPEC2
penetrer	penetrasse	V;IPFV;SBJV;SG;1;PST
desheriter	desheriteray	V;IND;SG;1;FUT;LGSPEC2
exposer	exposa	V;PFV;IND;SG;3;PST
saulter	saulteroyt	V;COND;SG;3;LGSPEC2
destabler	destabloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
blasphemer	blasphemasmes	V;PFV;IND;PL;1;PST
subiecter	subiecte	V;IND;SG;1;PRS
manger	mangea	V;PFV;IND;SG;3;PST
achapter	achaptoit	V;IPFV;IND;SG;3;PST;LGSPEC1
merveiller	merveille	V;SBJV;SG;3;PRS
estre	soient	V;SBJV;PL;3;PRS;LGSPEC2
esgaler	esgalast	V;IPFV;SBJV;SG;3;PST
deschainer	deschainons	V;IND;PL;1;PRS
bancqueter	bancqueterent	V;PFV;IND;PL;3;PST
aler	irez	V;IND;PL;2;FUT;LGSPEC1
arrester	arrestons	V;SBJV;PL;1;PRS
heurter	heurtois	V;IPFV;IND;SG;2;PST;LGSPEC1
deslacer	delaçons	V;SBJV;PL;1;PRS
contrepoiser	contrepoisasses	V;IPFV;SBJV;SG;2;PST
traittier	traittieroys	V;COND;SG;1;LGSPEC2
penetrer	penetreroyt	V;COND;SG;3;LGSPEC2
oultrager	oultragiez	V;IPFV;IND;PL;2;PST;LGSPEC1
finir	finira	V;IND;SG;3;FUT
mettre	mettiez	V;SBJV;PL;2;PRS
manger	mangeray	V;IND;SG;1;FUT;LGSPEC2
brusler	brusle	V;SBJV;SG;3;PRS
prosperer	prospererent	V;PFV;IND;PL;3;PST
affamer	affamons	V;IMP;PL;1
gaigner	gaignons	V;IND;PL;1;PRS
estouffer	estouffez	V;SBJV;PL;2;PRS
esternuer	esternuons	V;IND;PL;1;PRS
esplucher	esplucheroient	V;COND;PL;3;LGSPEC1
esternuer	esternuois	V;IPFV;IND;SG;1;PST;LGSPEC1
desister	desistasmes	V;PFV;IND;PL;1;PST
espouser	espousyons	V;IPFV;IND;PL;1;PST;LGSPEC2
faucer	fauçois	V;IPFV;IND;SG;2;PST;LGSPEC1
bransler	bransleroys	V;COND;SG;1;LGSPEC2
adviser	advisa	V;PFV;IND;SG;3;PST
hebergier	hebergyons	V;IPFV;IND;PL;1;PST;LGSPEC2
piller	pilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
emboucher	embouchasse	V;IPFV;SBJV;SG;1;PST
bransler	branslas	V;PFV;IND;SG;2;PST
tourmenter	tourmentes	V;IND;SG;2;PRS
trembler	tremblas	V;PFV;IND;SG;2;PST
inviter	invitons	V;SBJV;PL;1;PRS
repraesenter	repraesentons	V;SBJV;PL;1;PRS
fluir	fluit	V;PFV;IND;SG;3;PST
praesider	praesideras	V;IND;SG;2;FUT
auser	ause	V;SBJV;SG;1;PRS
esvertuer	esvertuerions	V;COND;PL;1;LGSPEC1
despouiller	despouillons	V;IND;PL;1;PRS
enconcher	enconchoys	V;IPFV;IND;SG;1;PST;LGSPEC2
enchasser	enchasserons	V;IND;PL;1;FUT
navrer	navrerai	V;IND;SG;1;FUT;LGSPEC1
estouffer	estouffoit	V;IPFV;IND;SG;3;PST;LGSPEC1
enconvenencier	enconvenencierez	V;IND;PL;2;FUT
emerger	emergeoient	V;IPFV;IND;PL;3;PST;LGSPEC1
plaider	plaidasse	V;IPFV;SBJV;SG;1;PST
desnouer	desnouastes	V;PFV;IND;PL;2;PST
faire	feroye	V;IND;SG;1;FUT;LGSPEC2
jecter	jectassent	V;IPFV;SBJV;PL;3;PST
entrefrapper	entrefrappons nous	V;IMP;PL;1
esbaucher	esbaucheryez	V;COND;PL;2;LGSPEC2
considerer	considerera	V;IND;SG;3;FUT
prosperer	prosperoit	V;IPFV;IND;SG;3;PST;LGSPEC1
arroier	arroieroys	V;COND;SG;1;LGSPEC2
soupper	souppasses	V;IPFV;SBJV;SG;2;PST
escumer	escumasses	V;IPFV;SBJV;SG;2;PST
pourchasser	pourchasseroys	V;COND;SG;2;LGSPEC2
esveiller	esveillassions	V;IPFV;SBJV;PL;1;PST
cabasser	cabasseroit	V;COND;SG;3;LGSPEC1
aler	yroit	V;COND;SG;3;LGSPEC2
heurter	heurtoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
estinceller	estincelleroient	V;COND;PL;3;LGSPEC1
remercyer	remercyeryez	V;COND;PL;2;LGSPEC2
essayer	essayasses	V;IPFV;SBJV;SG;2;PST
empenser	empensassent	V;IPFV;SBJV;PL;3;PST
manouvrer	manouvreryons	V;COND;PL;1;LGSPEC2
esgaler	esgalez	V;IMP;PL;2
mucer	muçassions	V;IPFV;SBJV;PL;1;PST
detranchier	detranchions	V;IPFV;IND;PL;1;PST;LGSPEC1
considerer	considererez	V;IND;PL;2;FUT
entreruyner	nousentreruynions	V;IPFV;IND;PL;1;PST;LGSPEC1
preferer	prefereriez	V;COND;PL;2;LGSPEC1
aler	alions	V;SBJV;PL;1;PRS
celebrer	celebrerions	V;COND;PL;1;LGSPEC1
estrangler	estranglas	V;PFV;IND;SG;2;PST
gaspiller	gaspilloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
trembler	tremblons	V;IND;PL;1;PRS
brusler	bruslyons	V;IPFV;IND;PL;1;PST;LGSPEC2
ralier	ralioys	V;IPFV;IND;SG;1;PST;LGSPEC2
doubter	doubte	V;SBJV;SG;3;PRS
espargner	espargnast	V;IPFV;SBJV;SG;3;PST
aquitter	aquittez	V;IND;PL;2;PRS
adapter	adapteroit	V;COND;SG;3;LGSPEC1
resigner	resignasses	V;IPFV;SBJV;SG;2;PST
desconseiller	desconseillons	V;IND;PL;1;PRS
esperer	espererons	V;IND;PL;1;FUT
prier	priasse	V;IPFV;SBJV;SG;1;PST
retirer	retireray	V;IND;SG;1;FUT;LGSPEC2
lascher	laschiez	V;IPFV;IND;PL;2;PST;LGSPEC1
toucher	touche	V;IMP;SG;2
dampner	dampnyons	V;IPFV;IND;PL;1;PST;LGSPEC2
empescher	empeschyons	V;IPFV;IND;PL;1;PST;LGSPEC2
ralier	ralient	V;SBJV;PL;3;PRS
adiouster	adiousta	V;PFV;IND;SG;1;PST
saulter	saulteras	V;IND;SG;2;FUT
estourdir	estourdis	V;IND;SG;1;PRS
tyrer	tyrerions	V;COND;PL;1;LGSPEC1
tourner	tournoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
rappeller	rappelle	V;SBJV;SG;3;PRS
expuyser	expuyse	V;IND;SG;1;PRS
commencer	commencions	V;IPFV;IND;PL;1;PST;LGSPEC1
esmerveillier	esmerveillassiez	V;IPFV;SBJV;PL;2;PST
exposer	exposeras	V;IND;SG;2;FUT
retirer	retires	V;SBJV;SG;2;PRS
honnourer	honnouroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
dampner	dampnons	V;IMP;PL;1
guarder	guarder	V;NFIN
desplacer	desplaceryez	V;COND;PL;2;LGSPEC2
reietter	reiette	V;IMP;SG;2
rappeller	rappelliez	V;IPFV;IND;PL;2;PST;LGSPEC1
escrier	escriez	V;SBJV;PL;2;PRS
hebergier	heberge	V;IMP;SG;2
rincer	rinçois	V;IPFV;IND;SG;2;PST;LGSPEC1
escumer	escumassions	V;IPFV;SBJV;PL;1;PST
couster	coustassent	V;IPFV;SBJV;PL;3;PST
desister	desisterions	V;COND;PL;1;LGSPEC1
honnourer	honnoureroyent	V;COND;PL;3;LGSPEC2
arroier	arroient	V;SBJV;PL;3;PRS
mucer	mucyez	V;IPFV;IND;PL;2;PST;LGSPEC2
emprunter	empruntons	V;IMP;PL;1
temprer	tempre	V;SBJV;SG;3;PRS
esvertuer	esvertuez	V;SBJV;PL;2;PRS
pourchasser	pourchassois	V;IPFV;IND;SG;1;PST;LGSPEC1
deffier	deffiez	V;IMP;PL;2
remercyer	remercyerent	V;PFV;IND;PL;3;PST
ayder	ayderai	V;IND;SG;1;FUT;LGSPEC1
nombrer	nombrent	V;IND;PL;3;PRS
espouser	espousassent	V;IPFV;SBJV;PL;3;PST
estonner	estonneront	V;IND;PL;3;FUT
fluir	fluirois	V;COND;SG;1;LGSPEC1
eriger	erige	V;IND;SG;3;PRS
verifier	verifiyons	V;IPFV;IND;PL;1;PST;LGSPEC2
demesler	demeslasse	V;IPFV;SBJV;SG;1;PST
appeller	appellasse	V;IPFV;SBJV;SG;1;PST
asseurer	asseurent	V;SBJV;PL;3;PRS
empescher	empeschez	V;IND;PL;2;PRS
espargner	espargne	V;IND;SG;1;PRS
lascher	lascherois	V;COND;SG;1;LGSPEC1
desmonter	desmonteroys	V;COND;SG;2;LGSPEC2
gouverner	gouvernent	V;SBJV;PL;3;PRS
effreer	effreera	V;IND;SG;3;FUT
ymaginer	ymagineroyt	V;COND;SG;3;LGSPEC2
plier	plierois	V;COND;SG;1;LGSPEC1
importuner	importuna	V;PFV;IND;SG;3;PST
confesser	confesse	V;SBJV;SG;3;PRS
desver	desvassent	V;IPFV;SBJV;PL;3;PST
brusler	brusle	V;IND;SG;1;PRS
affermer	affermerions	V;COND;PL;1;LGSPEC1
dampner	dampnerez	V;IND;PL;2;FUT
resigner	resignez	V;IMP;PL;2
reverer	revereryons	V;COND;PL;1;LGSPEC2
marier	marierions	V;COND;PL;1;LGSPEC1
advouer	advoue	V;IND;SG;1;PRS
ieusner	ieusnons	V;IMP;PL;1
deschainer	deschainerez	V;IND;PL;2;FUT
subiecter	subiecteryons	V;COND;PL;1;LGSPEC2
guarder	guardez	V;IND;PL;2;PRS
loger	logeras	V;IND;SG;2;FUT
bancqueter	bancquete	V;SBJV;SG;3;PRS
esveiller	esveillerai	V;IND;SG;1;FUT;LGSPEC1
rotter	rotteroys	V;COND;SG;2;LGSPEC2
lascher	laschyons	V;IPFV;IND;PL;1;PST;LGSPEC2
affamer	affamerions	V;COND;PL;1;LGSPEC1
ieusner	ieusnassiez	V;IPFV;SBJV;PL;2;PST
frapper	frapperai	V;IND;SG;1;FUT;LGSPEC1
desrober	desrobent	V;SBJV;PL;3;PRS
iecter	iectas	V;PFV;IND;SG;2;PST
prier	prieront	V;IND;PL;3;FUT
cerchier	cerchas	V;PFV;IND;SG;2;PST
translater	translations	V;IPFV;IND;PL;1;PST;LGSPEC1
ayder	aydassent	V;IPFV;SBJV;PL;3;PST
superseder	supersediez	V;IPFV;IND;PL;2;PST;LGSPEC1
esquacher	esquachasses	V;IPFV;SBJV;SG;2;PST
desrober	desrobe	V;SBJV;SG;1;PRS
desadvouer	desadvouassent	V;IPFV;SBJV;PL;3;PST
iniurier	iniurions	V;IND;PL;1;PRS
explicquer	explicquoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
ietter	iettyez	V;IPFV;IND;PL;2;PST;LGSPEC2
preter	preteroyent	V;COND;PL;3;LGSPEC2
contregarder	contregardassiez	V;IPFV;SBJV;PL;2;PST
bransler	branslasmes	V;PFV;IND;PL;1;PST
solliciter	solliciteriez	V;COND;PL;2;LGSPEC1
executer	executerois	V;COND;SG;2;LGSPEC1
gaigner	gaigneroys	V;COND;SG;1;LGSPEC2
aracher	arache	V;SBJV;SG;3;PRS
frapper	frappez	V;IND;PL;2;PRS
invader	invadoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
escrier	escrient	V;IND;PL;3;PRS
exposer	exposassent	V;IPFV;SBJV;PL;3;PST
entrefraper	s'entrefrapassent	V;IPFV;SBJV;PL;3;PST
demesler	demeslez	V;SBJV;PL;2;PRS
recorder	recordes	V;SBJV;SG;2;PRS
dampner	dampneroys	V;COND;SG;1;LGSPEC2
detester	deteste	V;IND;SG;1;PRS
engroisser	engroisses	V;SBJV;SG;2;PRS
reguarder	reguardyez	V;IPFV;IND;PL;2;PST;LGSPEC2
desnouer	desnouerez	V;IND;PL;2;FUT
enchargier	enchargieroyent	V;COND;PL;3;LGSPEC2
r'asseurer	r'asseurent	V;SBJV;PL;3;PRS
estouffer	estouffast	V;IPFV;SBJV;SG;3;PST
espargner	espargnez	V;SBJV;PL;2;PRS
hostoier	hostoieroys	V;COND;SG;2;LGSPEC2
arroier	arroions	V;SBJV;PL;1;PRS
superseder	supersedez	V;SBJV;PL;2;PRS
lascher	lascheryez	V;COND;PL;2;LGSPEC2
estinceller	estincelleroys	V;COND;SG;1;LGSPEC2
r'asseurer	r'asseurons	V;IMP;PL;1
obliger	obligerons	V;IND;PL;1;FUT
accorder	accorderoyt	V;COND;SG;3;LGSPEC2
adviser	advisent	V;IND;PL;3;PRS
deslacer	delaçoit	V;IPFV;IND;SG;3;PST;LGSPEC1
essilier	essilieryez	V;COND;PL;2;LGSPEC2
auser	ausasmes	V;PFV;IND;PL;1;PST
encontrer	encontrois	V;IPFV;IND;SG;1;PST;LGSPEC1
invader	invadoit	V;IPFV;IND;SG;3;PST;LGSPEC1
macter	mactasse	V;IPFV;SBJV;SG;1;PST
ymaginer	ymaginoient	V;IPFV;IND;PL;3;PST;LGSPEC1
verifier	verifiez	V;SBJV;PL;2;PRS
nombrer	nombroit	V;IPFV;IND;SG;3;PST;LGSPEC1
avoyr	avons	V;IND;PL;1;PRS
empescher	empesche	V;SBJV;SG;1;PRS
enfelonner	enfelonnoient	V;IPFV;IND;PL;3;PST;LGSPEC1
desplacer	desplacions	V;IPFV;IND;PL;1;PST;LGSPEC1
contreroller	contrerollasmes	V;PFV;IND;PL;1;PST
debaracer	debaracerai	V;IND;SG;1;FUT;LGSPEC1
desieuner	desieuneryez	V;COND;PL;2;LGSPEC2
avoyr	auront	V;IND;PL;3;FUT
diviner	divinerions	V;COND;PL;1;LGSPEC1
ietter	iettoit	V;IPFV;IND;SG;3;PST;LGSPEC1
cerchier	cerchassent	V;IPFV;SBJV;PL;3;PST
louer	loueroyt	V;COND;SG;3;LGSPEC2
despouiller	despouillerois	V;COND;SG;2;LGSPEC1
effectuer	effectuons	V;IMP;PL;1
commencer	commenceriez	V;COND;PL;2;LGSPEC1
esventer	esventiez	V;IPFV;IND;PL;2;PST;LGSPEC1
praeparer	praeparent	V;IND;PL;3;PRS
esgaler	esgaloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
iniurier	iniuriez	V;IND;PL;2;PRS
superseder	supersederez	V;IND;PL;2;FUT
advouer	advoua	V;PFV;IND;SG;3;PST
enchargier	enchargierons	V;IND;PL;1;FUT
iecter	iectoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
soupper	souppastes	V;PFV;IND;PL;2;PST
enchargier	enchargeois	V;IPFV;IND;SG;2;PST;LGSPEC1
recorder	recordoys	V;IPFV;IND;SG;2;PST;LGSPEC2
cauterizer	cauteriza	V;PFV;IND;SG;1;PST
tromper	trompe	V;IND;SG;1;PRS
praeparer	praepara	V;PFV;IND;SG;1;PST
bransler	branslerai	V;IND;SG;1;FUT;LGSPEC1
desbaucher	desbauchons	V;IND;PL;1;PRS
nettoyer	nettoyerois	V;COND;SG;2;LGSPEC1
ieusner	ieusnas	V;PFV;IND;SG;2;PST
tourmenter	tourmentasmes	V;PFV;IND;PL;1;PST
aracher	aracherions	V;COND;PL;1;LGSPEC1
ployer	ployent	V;SBJV;PL;3;PRS
fomenter	fomentez	V;IMP;PL;2
mettre	mettroyent	V;COND;PL;3;LGSPEC2
voller	volle	V;IND;SG;3;PRS
rouiller	rouillerois	V;COND;SG;2;LGSPEC1
reverer	revereront	V;IND;PL;3;FUT
desnouer	desnoueray	V;IND;SG;1;FUT;LGSPEC2
rouiller	rouillois	V;IPFV;IND;SG;1;PST;LGSPEC1
r'asseurer	r'asseura	V;PFV;IND;SG;3;PST
baptizer	baptizast	V;IPFV;SBJV;SG;3;PST
emprunter	emprunteray	V;IND;SG;1;FUT;LGSPEC2
enorter	enorteryez	V;COND;PL;2;LGSPEC2
fraper	frapoient	V;IPFV;IND;PL;3;PST;LGSPEC1
tourner	tourneroyt	V;COND;SG;3;LGSPEC2
trembler	tremblerois	V;COND;SG;2;LGSPEC1
moustrer	moustroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
occurrer	occurreroit	V;COND;SG;3;LGSPEC1
enfelonner	enfelonnes	V;IND;SG;2;PRS
mucer	muceryons	V;COND;PL;1;LGSPEC2
iniurier	iniurieront	V;IND;PL;3;FUT
depescher	depeschez	V;IMP;PL;2
emboucher	emboucheroyt	V;COND;SG;3;LGSPEC2
desmonter	desmonteroit	V;COND;SG;3;LGSPEC1
hebergier	heberge	V;SBJV;SG;1;PRS
tourmenter	tourmentas	V;PFV;IND;SG;2;PST
accuser	accusassent	V;IPFV;SBJV;PL;3;PST
rincer	rinçastes	V;PFV;IND;PL;2;PST
cauterizer	cauterizeroys	V;COND;SG;2;LGSPEC2
jecter	jectons	V;IMP;PL;1
recorder	recorderiez	V;COND;PL;2;LGSPEC1
despencer	despencerions	V;COND;PL;1;LGSPEC1
communicquer	communicquyons	V;IPFV;IND;PL;1;PST;LGSPEC2
asseurer	asseureroys	V;COND;SG;1;LGSPEC2
descouchier	descouchierai	V;IND;SG;1;FUT;LGSPEC1
enconcher	enconche	V;IND;SG;1;PRS
advouer	advouent	V;IND;PL;3;PRS
remercyer	remercye	V;IND;SG;1;PRS
asseurer	asseurasse	V;IPFV;SBJV;SG;1;PST
evaporer	evaporasses	V;IPFV;SBJV;SG;2;PST
veigler	veigla	V;PFV;IND;SG;1;PST
empenser	empensoit	V;IPFV;IND;SG;3;PST;LGSPEC1
estonner	estonnasse	V;IPFV;SBJV;SG;1;PST
trouver	trouvions	V;IPFV;IND;PL;1;PST;LGSPEC1
blasphemer	blasphemoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
gouverner	gouvernasse	V;IPFV;SBJV;SG;1;PST
visiter	visitoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
entrefraper	s'entrefrapent	V;IND;PL;3;PRS
desbaucher	desbaucherons	V;IND;PL;1;FUT
desadvouer	desadvouoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
reguarder	reguardoys	V;IPFV;IND;SG;1;PST;LGSPEC2
iniurier	iniuries	V;IND;SG;2;PRS
detester	detestera	V;IND;SG;3;FUT
renouveller	renouveller	V;NFIN
honnourer	honnourasse	V;IPFV;SBJV;SG;1;PST
couster	cousterent	V;PFV;IND;PL;3;PST
despencer	despencez	V;IND;PL;2;PRS
espargner	espargneroit	V;COND;SG;3;LGSPEC1
croniquier	croniquie	V;SBJV;SG;3;PRS
desnouer	desnouiez	V;IPFV;IND;PL;2;PST;LGSPEC1
tourner	tourneryez	V;COND;PL;2;LGSPEC2
aracher	arachast	V;IPFV;SBJV;SG;3;PST
veiller	veilleras	V;IND;SG;2;FUT
evaporer	evapore	V;IMP;SG;2
explicquer	explicquent	V;IND;PL;3;PRS
escumer	escumeriez	V;COND;PL;2;LGSPEC1
estrangler	estrangleryez	V;COND;PL;2;LGSPEC2
apatir	apatissoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
mectre	misse	V;IPFV;SBJV;SG;1;PST
recorder	recorder	V;NFIN
temprer	tempreroyent	V;COND;PL;3;LGSPEC2
estudier	estudie	V;IND;SG;3;PRS
tourmenter	tourmenteront	V;IND;PL;3;FUT
fomenter	fomentasmes	V;PFV;IND;PL;1;PST
preferer	preferassiez	V;IPFV;SBJV;PL;2;PST
esbaucher	esbauchasmes	V;PFV;IND;PL;1;PST
celebrer	celebrassiez	V;IPFV;SBJV;PL;2;PST
sçavoir	sçaurays	V;COND;SG;2;LGSPEC1
desinfecter	desinfectasse	V;IPFV;SBJV;SG;1;PST
occurrer	occurrerois	V;COND;SG;1;LGSPEC1
enhorter	enhortas	V;PFV;IND;SG;2;PST
communicquer	communicqueroyent	V;COND;PL;3;LGSPEC2
espargner	espargnyons	V;IPFV;IND;PL;1;PST;LGSPEC2
ymaginer	ymaginons	V;IMP;PL;1
posseder	possedons	V;IND;PL;1;PRS
eriger	eriger	V;NFIN
eslever	eslevas	V;PFV;IND;SG;2;PST
piller	pillez	V;IND;PL;2;PRS
louer	louer	V;NFIN
esternuer	esternueroyt	V;COND;SG;3;LGSPEC2
escapper	escapperez	V;IND;PL;2;FUT
enchargier	enchargions	V;SBJV;PL;1;PRS
desbaucher	desbauchons	V;SBJV;PL;1;PRS
deffier	deffiasmes	V;PFV;IND;PL;1;PST
merveiller	merveilleryez	V;COND;PL;2;LGSPEC2
inviter	invites	V;SBJV;SG;2;PRS
reguarder	reguardasses	V;IPFV;SBJV;SG;2;PST
estiquier	estiquieriez	V;COND;PL;2;LGSPEC1
estre	estois	V;IPFV;IND;SG;2;PST;LGSPEC1
esperer	espere	V;IND;SG;1;PRS
soupper	souppe	V;IMP;SG;2
baptiser	baptisez	V;SBJV;PL;2;PRS
debaracer	debaracent	V;IND;PL;3;PRS
enfelonner	enfelonnent	V;SBJV;PL;3;PRS
desyrer	desyrerois	V;COND;SG;2;LGSPEC1
marier	mariasse	V;IPFV;SBJV;SG;1;PST
debaracer	debaraçons	V;IMP;PL;1
mehaignier	mehaigne	V;SBJV;SG;3;PRS
resver	resvent	V;IND;PL;3;PRS
conquester	conquestent	V;SBJV;PL;3;PRS
desancrer	desancre	V;SBJV;SG;3;PRS
esvanter	esvantas	V;PFV;IND;SG;2;PST
rouller	roulloient	V;IPFV;IND;PL;3;PST;LGSPEC1
combiner	combiniez	V;IPFV;IND;PL;2;PST;LGSPEC1
ieuner	ieuneryons	V;COND;PL;1;LGSPEC2
mescler	mescle	V;SBJV;SG;1;PRS
eschever	escheverions	V;COND;PL;1;LGSPEC1
separer	separe	V;IMP;SG;2
advancer	advancerent	V;PFV;IND;PL;3;PST
subiuger	subiuges	V;SBJV;SG;2;PRS
entredonner	s'entredonneront	V;IND;PL;3;FUT
hucher	hucha	V;PFV;IND;SG;3;PST
amer	ame	V;SBJV;SG;1;PRS
arrengier	arrengeoient	V;IPFV;IND;PL;3;PST;LGSPEC1
desfaire	desferoyent	V;COND;PL;3;LGSPEC2
guerpir	guerpis	V;IND;SG;2;PRS
buchier	buchassiez	V;IPFV;SBJV;PL;2;PST
robber	robberoyt	V;COND;SG;3;LGSPEC2
mulcter	mulcteroyent	V;COND;PL;3;LGSPEC2
infourmer	infourment	V;IND;PL;3;PRS
lescher	lescheroys	V;COND;SG;1;LGSPEC2
endommaiger	endommaigera	V;IND;SG;3;FUT
atacher	atacheroit	V;COND;SG;3;LGSPEC1
desregler	desregleryez	V;COND;PL;2;LGSPEC2
habiter	habiterois	V;COND;SG;1;LGSPEC1
consyderer	consydere	V;SBJV;SG;3;PRS
ottroyer	ottroyoit	V;IPFV;IND;SG;3;PST;LGSPEC1
monstrer	monstreroyt	V;COND;SG;3;LGSPEC2
espoventer	espoventez	V;IMP;PL;2
conquester	conquestas	V;PFV;IND;SG;2;PST
eschever	eschevera	V;IND;SG;3;FUT
cercher	cercherai	V;IND;SG;1;FUT;LGSPEC1
desploier	desploions	V;SBJV;PL;1;PRS
trancher	trancheroient	V;COND;PL;3;LGSPEC1
luitter	luittez	V;SBJV;PL;2;PRS
presenter	presenta	V;PFV;IND;SG;3;PST
cointoier	cointoiera	V;IND;SG;3;FUT
deshonnourer	deshonnourerions	V;COND;PL;1;LGSPEC1
cercher	cercheryons	V;COND;PL;1;LGSPEC2
transporter	transportent	V;IND;PL;3;PRS
devourer	devouroit	V;IPFV;IND;SG;3;PST;LGSPEC1
humilier	humilions	V;SBJV;PL;1;PRS
appareiller	appareillons	V;IMP;PL;1
aorner	aorneroyent	V;COND;PL;3;LGSPEC2
possesser	possessast	V;IPFV;SBJV;SG;3;PST
gaimenter	gaimentyons	V;IPFV;IND;PL;1;PST;LGSPEC2
descourager	descourageoit	V;IPFV;IND;SG;3;PST;LGSPEC1
nouer	nouent	V;IND;PL;3;PRS
tocquer	tocquez	V;SBJV;PL;2;PRS
desgorger	desgorgerez	V;IND;PL;2;FUT
edifier	edifiiez	V;IPFV;IND;PL;2;PST;LGSPEC1
riffler	riffle	V;IMP;SG;2
employer	employyez	V;IPFV;IND;PL;2;PST;LGSPEC2
laidenger	laidengeasse	V;IPFV;SBJV;SG;1;PST
descourager	descouragerions	V;COND;PL;1;LGSPEC1
desfaire	desfacions	V;SBJV;PL;1;PRS
eslancer	eslançast	V;IPFV;SBJV;SG;3;PST
enpoisonner	enpoisonne	V;IMP;SG;2
combiner	combines	V;SBJV;SG;2;PRS
revencher	revenchions	V;IPFV;IND;PL;1;PST;LGSPEC1
cesser	cessons	V;IMP;PL;1
chanter	chantera	V;IND;SG;3;FUT
entrempescher	s'entrempeschoient	V;IPFV;IND;PL;3;PST;LGSPEC1
soubhaitter	soubhaitter	V;NFIN
chanter	chantes	V;IND;SG;2;PRS
flechir	fleschisse	V;SBJV;SG;3;PRS
accoustumer	accoustumeriez	V;COND;PL;2;LGSPEC1
pryer	pryons	V;IMP;PL;1
fortifier	fortifient	V;IND;PL;3;PRS
offencer	offenceryez	V;COND;PL;2;LGSPEC2
remonstrer	remonstrer	V;NFIN
remonstrer	remonstres	V;SBJV;SG;2;PRS
mensongier	mensongieroyent	V;COND;PL;3;LGSPEC2
persuader	persuadassent	V;IPFV;SBJV;PL;3;PST
redoubter	redoubtez	V;IMP;PL;2
payer	payast	V;IPFV;SBJV;SG;3;PST
desbarater	desbaraterons	V;IND;PL;1;FUT
finer	finerez	V;IND;PL;2;FUT
abandonner	abandonnerai	V;IND;SG;1;FUT;LGSPEC1
destacher	destachons	V;IND;PL;1;PRS
chercher	chercheryez	V;COND;PL;2;LGSPEC2
charger	chargeassions	V;IPFV;SBJV;PL;1;PST
apuyer	apuyoient	V;IPFV;IND;PL;3;PST;LGSPEC1
practicquer	practicquerons	V;IND;PL;1;FUT
lever	leverez	V;IND;PL;2;FUT
confermer	conferme	V;IND;SG;1;PRS
desploier	desploiastes	V;PFV;IND;PL;2;PST
desancrer	desancroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
pocher	pochois	V;IPFV;IND;SG;2;PST;LGSPEC1
occuper	occupe	V;SBJV;SG;3;PRS
soucyer	soucyeroyent	V;COND;PL;3;LGSPEC2
pourpenser	pourpensastes	V;PFV;IND;PL;2;PST
surnommer	surnomme	V;IMP;SG;2
mortifier	mortifiassent	V;IPFV;SBJV;PL;3;PST
entredonner	s'entredonnassent	V;IPFV;SBJV;PL;3;PST
persuader	persuadas	V;PFV;IND;SG;2;PST
acoustumer	acoustumoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
grapper	grappa	V;PFV;IND;SG;3;PST
chocquer	chocqueroys	V;COND;SG;1;LGSPEC2
cuyder	cuydez	V;SBJV;PL;2;PRS
transgloutir	transgloutirois	V;COND;SG;2;LGSPEC1
sceller	scellons	V;IND;PL;1;PRS
esgratigner	esgratigneras	V;IND;SG;2;FUT
condescendre	condescendistes	V;PFV;IND;PL;2;PST
finer	finent	V;SBJV;PL;3;PRS
uriner	urineray	V;IND;SG;1;FUT;LGSPEC2
chanter	chantent	V;IND;PL;3;PRS
flechir	fleschissez	V;IMP;PL;2
subiuger	subiugeront	V;IND;PL;3;FUT
demander	demande	V;SBJV;SG;3;PRS
chanter	chantas	V;PFV;IND;SG;2;PST
deifier	deifierois	V;COND;SG;1;LGSPEC1
occuper	occuperoys	V;COND;SG;1;LGSPEC2
escouter	escoutera	V;IND;SG;3;FUT
resver	resveroit	V;COND;SG;3;LGSPEC1
racointer	racointerois	V;COND;SG;1;LGSPEC1
interpreter	interpretasse	V;IPFV;SBJV;SG;1;PST
mortifier	mortifiions	V;IPFV;IND;PL;1;PST;LGSPEC1
apuyer	apuyeront	V;IND;PL;3;FUT
enyvrer	enyvreroyt	V;COND;SG;3;LGSPEC2
soucyer	soucyerez	V;IND;PL;2;FUT
intoxiquer	intoxique	V;IND;SG;1;PRS
negotier	negotiez	V;IMP;PL;2
embler	embles	V;SBJV;SG;2;PRS
occuper	occupons	V;SBJV;PL;1;PRS
entrefaire	entreferoient	V;COND;PL;3;LGSPEC1
tumber	tumboyt	V;IPFV;IND;SG;3;PST;LGSPEC2
desancrer	desancreray	V;IND;SG;1;FUT;LGSPEC2
tramper	tramperyez	V;COND;PL;2;LGSPEC2
saluer	saluez	V;SBJV;PL;2;PRS
reiecter	reiecter	V;NFIN
assieger	assiegeroys	V;COND;SG;2;LGSPEC2
espier	espiez	V;SBJV;PL;2;PRS
deshonnourer	deshonnoureroit	V;COND;SG;3;LGSPEC1
viser	viseroys	V;COND;SG;1;LGSPEC2
regretter	regrette	V;IND;SG;3;PRS
creancer	creance	V;IND;SG;1;PRS
ieuner	ieunez	V;IND;PL;2;PRS
disner	disnyez	V;IPFV;IND;PL;2;PST;LGSPEC2
desirer	desirez	V;IND;PL;2;PRS
quester	questyons	V;IPFV;IND;PL;1;PST;LGSPEC2
esmayer	esmayasses	V;IPFV;SBJV;SG;2;PST
ronfler	ronfleriez	V;COND;PL;2;LGSPEC1
infourmer	infourmoient	V;IPFV;IND;PL;3;PST;LGSPEC1
acquiter	acquitoient	V;IPFV;IND;PL;3;PST;LGSPEC1
reculler	recullent	V;IND;PL;3;PRS
espoventer	espoventeroys	V;COND;SG;2;LGSPEC2
toquer	toqueroit	V;COND;SG;3;LGSPEC1
uriner	urinoit	V;IPFV;IND;SG;3;PST;LGSPEC1
besoinger	besoignoys	V;IPFV;IND;SG;2;PST;LGSPEC2
coniecturer	coniecture	V;IND;SG;1;PRS
tirer	tirons	V;IND;PL;1;PRS
praesenter	praesentoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
heiler	heilyons	V;IPFV;IND;PL;1;PST;LGSPEC2
transgloutir	transgloutissiez	V;IPFV;SBJV;PL;2;PST
chocquer	chocquerois	V;COND;SG;2;LGSPEC1
revencher	revencheroient	V;COND;PL;3;LGSPEC1
destacher	destacheryons	V;COND;PL;1;LGSPEC2
descourager	descourageons	V;IMP;PL;1
alimenter	alimentoys	V;IPFV;IND;SG;1;PST;LGSPEC2
pecher	pecha	V;PFV;IND;SG;3;PST
despossesser	despossesses	V;IND;SG;2;PRS
presumer	presumeroyent	V;COND;PL;3;LGSPEC2
tuer	tuez	V;SBJV;PL;2;PRS
desployer	desployeryons	V;COND;PL;1;LGSPEC2
desrisier	desrisierent	V;PFV;IND;PL;3;PST
desbarater	desbaratera	V;IND;SG;3;FUT
separer	separez	V;IND;PL;2;PRS
chercher	cherche	V;IND;SG;3;PRS
luitter	luittastes	V;PFV;IND;PL;2;PST
caper	capera	V;IND;SG;3;FUT
sembler	sembla	V;PFV;IND;SG;3;PST
compter	comptons	V;IMP;PL;1
guerpir	guerpissons	V;IND;PL;1;PRS
demander	demandes	V;IND;SG;2;PRS
renfler	renflois	V;IPFV;IND;SG;2;PST;LGSPEC1
besoinger	besoigneray	V;IND;SG;1;FUT;LGSPEC2
surnommer	surnommasmes	V;PFV;IND;PL;1;PST
parler	parlast	V;IPFV;SBJV;SG;3;PST
quereler	querele	V;IND;SG;3;PRS
laisser	laissoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
amadouer	amadouera	V;IND;SG;3;FUT
luitter	luitteroit	V;COND;SG;3;LGSPEC1
pryer	pryassent	V;IPFV;SBJV;PL;3;PST
esloigner	esloignyez	V;IPFV;IND;PL;2;PST;LGSPEC2
encliner	enclinerons	V;IND;PL;1;FUT
deshonnourer	deshonnouroient	V;IPFV;IND;PL;3;PST;LGSPEC1
pecher	pechoit	V;IPFV;IND;SG;3;PST;LGSPEC1
desploier	desploiassiez	V;IPFV;SBJV;PL;2;PST
desancrer	desancrast	V;IPFV;SBJV;SG;3;PST
abandonner	abandonneront	V;IND;PL;3;FUT
redoubter	redoubterai	V;IND;SG;1;FUT;LGSPEC1
fortifier	fortifiera	V;IND;SG;3;FUT
saluer	salueroient	V;COND;PL;3;LGSPEC1
presumer	presumeras	V;IND;SG;2;FUT
presupposer	presuppose	V;IND;SG;1;PRS
approuvender	approuvenderoit	V;COND;SG;3;LGSPEC1
descharger	deschargeront	V;IND;PL;3;FUT
mensongier	mensongeasmes	V;PFV;IND;PL;1;PST
abandonner	abandonneriez	V;COND;PL;2;LGSPEC1
engendrer	engendrons	V;IMP;PL;1
declairer	declaireriez	V;COND;PL;2;LGSPEC1
desrobber	desrobbions	V;IPFV;IND;PL;1;PST;LGSPEC1
quereler	querelerent	V;PFV;IND;PL;3;PST
intoxiquer	intoxiqueray	V;IND;SG;1;FUT;LGSPEC2
expeller	expellons	V;IND;PL;1;PRS
desmeler	desmelerent	V;PFV;IND;PL;3;PST
coucher	couchez	V;SBJV;PL;2;PRS
dilater	dilatasmes	V;PFV;IND;PL;1;PST
desloger	deslogez	V;IMP;PL;2
habiter	habitois	V;IPFV;IND;SG;2;PST;LGSPEC1
seiourner	seiourne	V;IND;SG;1;PRS
remonstrer	remonstreroyt	V;COND;SG;3;LGSPEC2
engendrer	engendrassent	V;IPFV;SBJV;PL;3;PST
amer	amassions	V;IPFV;SBJV;PL;1;PST
mulcter	mulcteray	V;IND;SG;1;FUT;LGSPEC2
viser	visera	V;IND;SG;3;FUT
appareiller	appareilleroit	V;COND;SG;3;LGSPEC1
mouscher	mouschois	V;IPFV;IND;SG;2;PST;LGSPEC1
mescler	mesclons	V;IMP;PL;1
recouvrer	recouvrent	V;SBJV;PL;3;PRS
tournoyer	tournoya	V;PFV;IND;SG;1;PST
payer	payeront	V;IND;PL;3;FUT
mocquer	mocqueryons	V;COND;PL;1;LGSPEC2
vuider	vuidois	V;IPFV;IND;SG;2;PST;LGSPEC1
quester	questast	V;IPFV;SBJV;SG;3;PST
peser	peserons	V;IND;PL;1;FUT
delivrer	delivreriez	V;COND;PL;2;LGSPEC1
reigler	reiglasse	V;IPFV;SBJV;SG;1;PST
esclairer	esclairois	V;IPFV;IND;SG;1;PST;LGSPEC1
esgarer	esgaroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
esveigler	esveigloit	V;IPFV;IND;SG;3;PST;LGSPEC1
desborder	desborderois	V;COND;SG;1;LGSPEC1
galoper	galoperent	V;PFV;IND;PL;3;PST
habiter	habiteront	V;IND;PL;3;FUT
proteger	protegerois	V;COND;SG;1;LGSPEC1
laidenger	laidengeoient	V;IPFV;IND;PL;3;PST;LGSPEC1
mehaignier	mehaigne	V;IND;SG;3;PRS
desprisonner	desprisonneroyt	V;COND;SG;3;LGSPEC2
vengier	vengieryons	V;COND;PL;1;LGSPEC2
apuyer	apuyeras	V;IND;SG;2;FUT
atacher	atacherons	V;IND;PL;1;FUT
protester	protestent	V;IND;PL;3;PRS
reigler	reigle	V;IND;SG;3;PRS
porter	porteryons	V;COND;PL;1;LGSPEC2
coniurer	coniure	V;IMP;SG;2
tumber	tumboys	V;IPFV;IND;SG;1;PST;LGSPEC2
desployer	desployons	V;IND;PL;1;PRS
hucher	huche	V;IND;SG;1;PRS
aller	yras	V;IND;SG;2;FUT;LGSPEC2
compter	comptoys	V;IPFV;IND;SG;1;PST;LGSPEC2
disner	disnons	V;SBJV;PL;1;PRS
alterer	altereroyt	V;COND;SG;3;LGSPEC2
eschieller	escielloient	V;IPFV;IND;PL;3;PST;LGSPEC1
charger	chargez	V;SBJV;PL;2;PRS
proclamer	proclamerez	V;IND;PL;2;FUT
entrempescher	entrempescheryez	V;COND;PL;2;LGSPEC2
trancher	tranchoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
alimenter	alimentasses	V;IPFV;SBJV;SG;2;PST
accomplir	accomplissoient	V;IPFV;IND;PL;3;PST;LGSPEC1
iurer	iurasses	V;IPFV;SBJV;SG;2;PST
sembler	semblons	V;IMP;PL;1
iurer	iureroys	V;COND;SG;1;LGSPEC2
esgarer	esgaroys	V;IPFV;IND;SG;1;PST;LGSPEC2
achever	achevyons	V;IPFV;IND;PL;1;PST;LGSPEC2
fouragier	fourageoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
armoier	armoiera	V;IND;SG;3;FUT
disner	disnerois	V;COND;SG;1;LGSPEC1
esguiser	esguises	V;IND;SG;2;PRS
huer	huions	V;IPFV;IND;PL;1;PST;LGSPEC1
appareiller	appareilloit	V;IPFV;IND;SG;3;PST;LGSPEC1
leicher	leichoient	V;IPFV;IND;PL;3;PST;LGSPEC1
escorcher	escorchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
desloger	deslogeasse	V;IPFV;SBJV;SG;1;PST
galoper	galoperas	V;IND;SG;2;FUT
pecher	pecheryons	V;COND;PL;1;LGSPEC2
tuer	tuois	V;IPFV;IND;SG;1;PST;LGSPEC1
noter	note	V;SBJV;SG;3;PRS
finer	fine	V;IND;SG;1;PRS
atempter	atempteroit	V;COND;SG;3;LGSPEC1
aerer	aerois	V;IPFV;IND;SG;1;PST;LGSPEC1
ottroyer	ottroyeront	V;IND;PL;3;FUT
entrencontrer	s'entrencontroient	V;IPFV;IND;PL;3;PST;LGSPEC1
reiecter	reiecteras	V;IND;SG;2;FUT
respirer	respirez	V;SBJV;PL;2;PRS
accepter	acceptoient	V;IPFV;IND;PL;3;PST;LGSPEC1
ottroyer	ottroyons	V;IMP;PL;1
saluer	saluassent	V;IPFV;SBJV;PL;3;PST
retourner	retournent	V;IND;PL;3;PRS
transgloutir	transgloutissiez	V;SBJV;PL;2;PRS
transgloutir	transgloutisse	V;SBJV;SG;1;PRS
robber	robbois	V;IPFV;IND;SG;2;PST;LGSPEC1
viser	viserions	V;COND;PL;1;LGSPEC1
abandonner	abandonne	V;SBJV;SG;3;PRS
condescendre	condescendriiens	V;COND;PL;1;LGSPEC1
alimenter	alimenteroyt	V;COND;SG;3;LGSPEC2
caper	capois	V;IPFV;IND;SG;2;PST;LGSPEC1
tuer	tuasmes	V;PFV;IND;PL;1;PST
penser	penseroyent	V;COND;PL;3;LGSPEC2
arriver	arrivons	V;IND;PL;1;PRS
cointoier	cointoiez	V;IMP;PL;2
esgarer	esgarast	V;IPFV;SBJV;SG;3;PST
esclairer	esclaire	V;IND;SG;3;PRS
iurer	iurent	V;IND;PL;3;PRS
gaber	gaberoyt	V;COND;SG;3;LGSPEC2
buchier	buchasses	V;IPFV;SBJV;SG;2;PST
marcher	marchions	V;IPFV;IND;PL;1;PST;LGSPEC1
endommaiger	endommaigez	V;SBJV;PL;2;PRS
viser	vise	V;SBJV;SG;3;PRS
eschever	escheverai	V;IND;SG;1;FUT;LGSPEC1
uriner	urineroit	V;COND;SG;3;LGSPEC1
finer	finoient	V;IPFV;IND;PL;3;PST;LGSPEC1
engendrer	engendrerois	V;COND;SG;2;LGSPEC1
toquer	toquons	V;SBJV;PL;1;PRS
espoventer	espoventons	V;SBJV;PL;1;PRS
esgarer	esgarons	V;IMP;PL;1
entrempescher	entrempeschons nous	V;IMP;PL;1
entredesirer	vousentredesiriez	V;IPFV;IND;PL;2;PST;LGSPEC1
perser	persent	V;SBJV;PL;3;PRS
assister	assistent	V;SBJV;PL;3;PRS
blesser	blesseroyt	V;COND;SG;3;LGSPEC2
quiter	quitons	V;SBJV;PL;1;PRS
quiter	quitasse	V;IPFV;SBJV;SG;1;PST
pecher	pechyez	V;IPFV;IND;PL;2;PST;LGSPEC2
desguiser	desguisera	V;IND;SG;3;FUT
destacher	destachiez	V;IPFV;IND;PL;2;PST;LGSPEC1
infourmer	infourmassions	V;IPFV;SBJV;PL;1;PST
porter	porterai	V;IND;SG;1;FUT;LGSPEC1
desancrer	desancrez	V;IND;PL;2;PRS
empoizonner	empoizonnes	V;SBJV;SG;2;PRS
baster	basterent	V;PFV;IND;PL;3;PST
tirer	tirent	V;SBJV;PL;3;PRS
esclairer	esclairerois	V;COND;SG;2;LGSPEC1
reculler	reculle	V;SBJV;SG;1;PRS
armoier	armoias	V;PFV;IND;SG;2;PST
gaber	gabe	V;SBJV;SG;3;PRS
recommander	recommanderoit	V;COND;SG;3;LGSPEC1
marcher	marcherions	V;COND;PL;1;LGSPEC1
huer	huons	V;IND;PL;1;PRS
aller	iroit	V;COND;SG;3;LGSPEC1
laisser	laisserez	V;IND;PL;2;FUT
fouragier	fouragieroit	V;COND;SG;3;LGSPEC1
alimenter	alimentoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
perser	perserez	V;IND;PL;2;FUT
perser	persyons	V;IPFV;IND;PL;1;PST;LGSPEC2
courroucer	courrouciez	V;IPFV;IND;PL;2;PST;LGSPEC1
blesser	blessent	V;IND;PL;3;PRS
desrisier	desrises	V;SBJV;SG;2;PRS
baiser	baisoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
baster	bastez	V;IMP;PL;2
uriner	urinerons	V;IND;PL;1;FUT
galoper	galoperay	V;IND;SG;1;FUT;LGSPEC2
pacquer	pacquyez	V;IPFV;IND;PL;2;PST;LGSPEC2
singler	singlyons	V;IPFV;IND;PL;1;PST;LGSPEC2
tuer	tua	V;PFV;IND;SG;3;PST
representer	representeray	V;IND;SG;1;FUT;LGSPEC2
representer	representes	V;SBJV;SG;2;PRS
fortifier	fortifierent	V;PFV;IND;PL;3;PST
racompter	racompteray	V;IND;SG;1;FUT;LGSPEC2
despossesser	despossessons	V;SBJV;PL;1;PRS
remerquer	remerquoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
songer	songeasse	V;IPFV;SBJV;SG;1;PST
soumectre	soumectoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
redoubter	redoubtoys	V;IPFV;IND;SG;2;PST;LGSPEC2
amer	amassiez	V;IPFV;SBJV;PL;2;PST
chercher	cherche	V;SBJV;SG;3;PRS
iurer	iurez	V;SBJV;PL;2;PRS
confermer	confermeriez	V;COND;PL;2;LGSPEC1
fiancer	fiançois	V;IPFV;IND;SG;2;PST;LGSPEC1
monter	montons	V;SBJV;PL;1;PRS
escouiller	escouillas	V;PFV;IND;SG;2;PST
employer	employassent	V;IPFV;SBJV;PL;3;PST
combiner	combinasmes	V;PFV;IND;PL;1;PST
mescler	mescloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
possesser	possessois	V;IPFV;IND;SG;2;PST;LGSPEC1
fumer	fument	V;IND;PL;3;PRS
geller	gelloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
espoventer	espoventiez	V;IPFV;IND;PL;2;PST;LGSPEC1
desprisonner	desprisonna	V;PFV;IND;SG;3;PST
reiecter	reiectent	V;IND;PL;3;PRS
acquiter	acquiteroys	V;COND;SG;2;LGSPEC2
besoinger	besoignions	V;IPFV;IND;PL;1;PST;LGSPEC1
acquiter	acquiteront	V;IND;PL;3;FUT
fiancer	fiance	V;SBJV;SG;1;PRS
exstirper	exstirperyons	V;COND;PL;1;LGSPEC2
acoustrer	acoustrasse	V;IPFV;SBJV;SG;1;PST
foetter	foetteray	V;IND;SG;1;FUT;LGSPEC2
arriver	arrivois	V;IPFV;IND;SG;2;PST;LGSPEC1
assister	assista	V;PFV;IND;SG;3;PST
trancher	tranchyez	V;IPFV;IND;PL;2;PST;LGSPEC2
tuer	tuerois	V;COND;SG;2;LGSPEC1
picquier	picquassions	V;IPFV;SBJV;PL;1;PST
armoier	armoierions	V;COND;PL;1;LGSPEC1
engendrer	engendrions	V;IPFV;IND;PL;1;PST;LGSPEC1
accepter	acceptassiez	V;IPFV;SBJV;PL;2;PST
alonger	alongeons	V;SBJV;PL;1;PRS
recuperer	recuperas	V;PFV;IND;SG;2;PST
traitter	traittes	V;IND;SG;2;PRS
descourager	descourageoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
racointer	racointes	V;SBJV;SG;2;PRS
escouiller	escouilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
resver	resvassent	V;IPFV;SBJV;PL;3;PST
fouragier	fourageoient	V;IPFV;IND;PL;3;PST;LGSPEC1
courouchier	courouchions	V;IMP;PL;1
interpreter	interpreter	V;NFIN
entituler	entitule	V;IND;SG;3;PRS
porter	porteroyent	V;COND;PL;3;LGSPEC2
laidenger	laidengerent	V;PFV;IND;PL;3;PST
descourager	descourageasmes	V;PFV;IND;PL;1;PST
serainer	serainoys	V;IPFV;IND;SG;1;PST;LGSPEC2
porter	portoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
despossesser	despossessasse	V;IPFV;SBJV;SG;1;PST
persuader	persuadoit	V;IPFV;IND;SG;3;PST;LGSPEC1
tirer	tirassent	V;IPFV;SBJV;PL;3;PST
geller	gelloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
presumer	presumassent	V;IPFV;SBJV;PL;3;PST
fumer	fumes	V;SBJV;SG;2;PRS
acoustumer	acoustumeroyt	V;COND;SG;3;LGSPEC2
singler	singloys	V;IPFV;IND;SG;2;PST;LGSPEC2
creancer	creançasses	V;IPFV;SBJV;SG;2;PST
empoizonner	empoizonnyons	V;IPFV;IND;PL;1;PST;LGSPEC2
grapper	grapperyez	V;COND;PL;2;LGSPEC2
enpoisonner	enpoisonnois	V;IPFV;IND;SG;1;PST;LGSPEC1
alterer	altereroit	V;COND;SG;3;LGSPEC1
toquer	toquois	V;IPFV;IND;SG;2;PST;LGSPEC1
acoustumer	acoustumerai	V;IND;SG;1;FUT;LGSPEC1
galoper	galopa	V;PFV;IND;SG;3;PST
toquer	toquerons	V;IND;PL;1;FUT
vuider	vuideroys	V;COND;SG;1;LGSPEC2
mescler	mesclerois	V;COND;SG;1;LGSPEC1
combiner	combinerent	V;PFV;IND;PL;3;PST
tournoyer	tournoyassions	V;IPFV;SBJV;PL;1;PST
condescendre	condescendroiz	V;IND;PL;2;FUT;LGSPEC1
protester	protestoys	V;IPFV;IND;SG;1;PST;LGSPEC2
arrengier	arrengions	V;IPFV;IND;PL;1;PST;LGSPEC1
respirer	respirassions	V;IPFV;SBJV;PL;1;PST
cuyder	cuyde	V;SBJV;SG;3;PRS
sceller	scellent	V;SBJV;PL;3;PRS
mescler	mesclez	V;IND;PL;2;PRS
iurer	iuras	V;PFV;IND;SG;2;PST
payer	payoys	V;IPFV;IND;SG;1;PST;LGSPEC2
remonstrer	remonstres	V;IND;SG;2;PRS
atacher	atachastes	V;PFV;IND;PL;2;PST
respirer	respireriez	V;COND;PL;2;LGSPEC1
infourmer	infourmastes	V;PFV;IND;PL;2;PST
regretter	regrettez	V;IMP;PL;2
desprisonner	desprisonnoys	V;IPFV;IND;SG;1;PST;LGSPEC2
atempter	atemptoit	V;IPFV;IND;SG;3;PST;LGSPEC1
mortifier	mortifias	V;PFV;IND;SG;2;PST
desirer	desiryez	V;IPFV;IND;PL;2;PST;LGSPEC2
deshonnourer	deshonnourez	V;IMP;PL;2
charger	chargiez	V;IPFV;IND;PL;2;PST;LGSPEC1
pourpenser	pourpensoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
baiser	baiseriez	V;COND;PL;2;LGSPEC1
transporter	transportoys	V;IPFV;IND;SG;2;PST;LGSPEC2
flotter	flottent	V;IND;PL;3;PRS
demander	demanderay	V;IND;SG;1;FUT;LGSPEC2
enyvrer	enyvreroit	V;COND;SG;3;LGSPEC1
enyvrer	enyvrassions	V;IPFV;SBJV;PL;1;PST
gaber	gabons	V;SBJV;PL;1;PRS
accomplir	accomplissois	V;IPFV;IND;SG;2;PST;LGSPEC1
desregler	desreglassent	V;IPFV;SBJV;PL;3;PST
esveigler	esveigloient	V;IPFV;IND;PL;3;PST;LGSPEC1
fouragier	fouragieroient	V;COND;PL;3;LGSPEC1
coucher	couchastes	V;PFV;IND;PL;2;PST
renommer	renommassiez	V;IPFV;SBJV;PL;2;PST
coucher	coucherois	V;COND;SG;2;LGSPEC1
negotier	negotieray	V;IND;SG;1;FUT;LGSPEC2
amadouer	amadouent	V;SBJV;PL;3;PRS
garder	gardasses	V;IPFV;SBJV;SG;2;PST
trancher	tranchasses	V;IPFV;SBJV;SG;2;PST
tumber	tumbassions	V;IPFV;SBJV;PL;1;PST
abboyer	abboyent	V;IND;PL;3;PRS
arriver	arrivastes	V;PFV;IND;PL;2;PST
respirer	respireroit	V;COND;SG;3;LGSPEC1
baiser	baisyez	V;IPFV;IND;PL;2;PST;LGSPEC2
tirer	tiroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
accompaigner	accompaignasse	V;IPFV;SBJV;SG;1;PST
demonstrer	demonstrerois	V;COND;SG;2;LGSPEC1
picquier	picquierons	V;IND;PL;1;FUT
intoxiquer	intoxiquastes	V;PFV;IND;PL;2;PST
aymer	aymes	V;IND;SG;2;PRS
desploier	desploient	V;IND;PL;3;PRS
aboscher	aboschyons	V;IPFV;IND;PL;1;PST;LGSPEC2
recouvrer	recouvrois	V;IPFV;IND;SG;2;PST;LGSPEC1
eschieller	escielle	V;IND;SG;1;PRS
acoustrer	acoustreriez	V;COND;PL;2;LGSPEC1
mortifier	mortifieront	V;IND;PL;3;FUT
racointer	racointeriez	V;COND;PL;2;LGSPEC1
desprisonner	desprisonnas	V;PFV;IND;SG;2;PST
transporter	transportiez	V;IPFV;IND;PL;2;PST;LGSPEC1
descharger	deschargeassions	V;IPFV;SBJV;PL;1;PST
grapper	grappes	V;IND;SG;2;PRS
embler	embleriez	V;COND;PL;2;LGSPEC1
creancer	creancerois	V;COND;SG;2;LGSPEC1
monter	monteroyt	V;COND;SG;3;LGSPEC2
escouiller	escouillent	V;IND;PL;3;PRS
desgorger	desgorgeois	V;IPFV;IND;SG;2;PST;LGSPEC1
accompaigner	accompaignez	V;IND;PL;2;PRS
tirer	tirerions	V;COND;PL;1;LGSPEC1
peser	pese	V;SBJV;SG;3;PRS
avaller	avalleroys	V;COND;SG;1;LGSPEC2
acoustrer	acoustres	V;IND;SG;2;PRS
accepter	acceptasses	V;IPFV;SBJV;SG;2;PST
chocquer	chocquent	V;IND;PL;3;PRS
avaller	avalle	V;SBJV;SG;3;PRS
minorer	minorasse	V;IPFV;SBJV;SG;1;PST
entredesirer	s'entredesireront	V;IND;PL;3;FUT
menasser	menasserois	V;COND;SG;2;LGSPEC1
riffler	rifflera	V;IND;SG;3;FUT
desfaire	desfissiez	V;IPFV;SBJV;PL;2;PST
desrisier	desrisoient	V;IPFV;IND;PL;3;PST;LGSPEC1
deifier	deifie	V;SBJV;SG;1;PRS
caper	caperez	V;IND;PL;2;FUT
laidenger	laidengeons	V;SBJV;PL;1;PRS
esveigler	esveigloys	V;IPFV;IND;SG;2;PST;LGSPEC2
tramper	tramperoyt	V;COND;SG;3;LGSPEC2
representer	representerois	V;COND;SG;2;LGSPEC1
interpreter	interpretons	V;IMP;PL;1
descourager	descourageastes	V;PFV;IND;PL;2;PST
saulver	saulvez	V;IMP;PL;2
representer	representoys	V;IPFV;IND;SG;1;PST;LGSPEC2
reculler	reculles	V;IND;SG;2;PRS
seiourner	seiourner	V;NFIN
tumber	tumbe	V;SBJV;SG;1;PRS
surnommer	surnommeriez	V;COND;PL;2;LGSPEC1
mescler	mescla	V;PFV;IND;SG;3;PST
desancrer	desancryons	V;IPFV;IND;PL;1;PST;LGSPEC2
approuvender	approuvende	V;SBJV;SG;3;PRS
reigler	reigleryons	V;COND;PL;1;LGSPEC2
expeller	expelleroys	V;COND;SG;1;LGSPEC2
conquester	conquestois	V;IPFV;IND;SG;2;PST;LGSPEC1
declairer	declaireroyt	V;COND;SG;3;LGSPEC2
descharger	descharge	V;IND;SG;3;PRS
dilater	dilatoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
provocquer	provocquera	V;IND;SG;3;FUT
provocquer	provocqueryons	V;COND;PL;1;LGSPEC2
caper	caperions	V;COND;PL;1;LGSPEC1
tesmoigner	tesmoignoit	V;IPFV;IND;SG;3;PST;LGSPEC1
pourpenser	pourpenseroyt	V;COND;SG;3;LGSPEC2
flatter	flatte	V;SBJV;SG;1;PRS
esgarer	esgareryons	V;COND;PL;1;LGSPEC2
raporter	raportent	V;IND;PL;3;PRS
recuperer	recuperent	V;SBJV;PL;3;PRS
desploier	desploiasse	V;IPFV;SBJV;SG;1;PST
pecher	pecheroyt	V;COND;SG;3;LGSPEC2
achever	acheveroyt	V;COND;SG;3;LGSPEC2
atacher	atacheroient	V;COND;PL;3;LGSPEC1
presumer	presumas	V;PFV;IND;SG;2;PST
encharger	enchargerois	V;COND;SG;2;LGSPEC1
courouchier	courouchier	V;NFIN
viser	visois	V;IPFV;IND;SG;2;PST;LGSPEC1
avaller	avalleras	V;IND;SG;2;FUT
humilier	humilie	V;SBJV;SG;3;PRS
nommer	nommeryons	V;COND;PL;1;LGSPEC2
consyderer	consydererai	V;IND;SG;1;FUT;LGSPEC1
menasser	menassois	V;IPFV;IND;SG;2;PST;LGSPEC1
separer	separyons	V;IPFV;IND;PL;1;PST;LGSPEC2
achever	achevois	V;IPFV;IND;SG;2;PST;LGSPEC1
blesser	blesse	V;IMP;SG;2
grapper	grapperoyt	V;COND;SG;3;LGSPEC2
flatter	flattois	V;IPFV;IND;SG;2;PST;LGSPEC1
raporter	raportoient	V;IPFV;IND;PL;3;PST;LGSPEC1
negotier	negotia	V;PFV;IND;SG;3;PST
toquer	toquera	V;IND;SG;3;FUT
pocher	poches	V;IND;SG;2;PRS
appareiller	appareillassions	V;IPFV;SBJV;PL;1;PST
dilater	dilaterois	V;COND;SG;1;LGSPEC1
coniecturer	coniecturyons	V;IPFV;IND;PL;1;PST;LGSPEC2
esloigner	esloignerois	V;COND;SG;1;LGSPEC1
accompaigner	accompaigneriez	V;COND;PL;2;LGSPEC1
esmayer	esmayois	V;IPFV;IND;SG;1;PST;LGSPEC1
flotter	flottez	V;IND;PL;2;PRS
monstrer	monstre	V;IMP;SG;2
sceller	scella	V;PFV;IND;SG;3;PST
foetter	foettons	V;IMP;PL;1
flotter	flottions	V;IPFV;IND;PL;1;PST;LGSPEC1
disner	disnez	V;IMP;PL;2
coniurer	coniurera	V;IND;SG;3;FUT
prattiquer	prattiques	V;IND;SG;2;PRS
finer	fineroyt	V;COND;SG;3;LGSPEC2
logier	logeois	V;IPFV;IND;SG;1;PST;LGSPEC1
desloger	desloge	V;IMP;SG;2
estimer	estimeras	V;IND;SG;2;FUT
abandonner	abandonnera	V;IND;SG;3;FUT
quiter	quitez	V;IMP;PL;2
redoubter	redoubteroyt	V;COND;SG;3;LGSPEC2
robber	robbions	V;IPFV;IND;PL;1;PST;LGSPEC1
descourager	descourageois	V;IPFV;IND;SG;2;PST;LGSPEC1
esguarer	esguarer	V;NFIN
affier	affions	V;IMP;PL;1
buchier	buchierai	V;IND;SG;1;FUT;LGSPEC1
pocher	poche	V;SBJV;SG;1;PRS
deschirer	deschirez	V;IND;PL;2;PRS
coniecturer	coniecturas	V;PFV;IND;SG;2;PST
demander	demandasses	V;IPFV;SBJV;SG;2;PST
pourforcer	pourforçons	V;IPFV;IND;PL;1;PST;LGSPEC2
trousser	troussoit	V;IPFV;IND;SG;3;PST;LGSPEC1
dancer	dancez	V;SBJV;PL;2;PRS
destacher	destaches	V;SBJV;SG;2;PRS
devourer	devoure	V;IND;SG;3;PRS
separer	separois	V;IPFV;IND;SG;2;PST;LGSPEC1
demander	demandoient	V;IPFV;IND;PL;3;PST;LGSPEC1
encharger	encharge	V;SBJV;SG;3;PRS
monstrer	monstreras	V;IND;SG;2;FUT
tremper	trempasse	V;IPFV;SBJV;SG;1;PST
eschever	eschever	V;NFIN
desirer	desirons	V;IMP;PL;1
donner	donnoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
avaller	avalleryons	V;COND;PL;1;LGSPEC2
deschirer	deschiroys	V;IPFV;IND;SG;1;PST;LGSPEC2
creancer	creances	V;IND;SG;2;PRS
demonstrer	demonstres	V;IND;SG;2;PRS
desfaire	desfaisoient	V;IPFV;IND;PL;3;PST;LGSPEC1
possesser	possesserois	V;COND;SG;1;LGSPEC1
marcher	marcheront	V;IND;PL;3;FUT
charger	chargea	V;PFV;IND;SG;3;PST
songer	songes	V;IND;SG;2;PRS
escouter	escouterez	V;IND;PL;2;FUT
songer	songeroys	V;COND;SG;2;LGSPEC2
entredesirer	nous entredesirerons	V;IND;PL;1;FUT
demourer	demourasmes	V;PFV;IND;PL;1;PST
nouer	nouerois	V;COND;SG;2;LGSPEC1
declairer	declairez	V;IND;PL;2;PRS
acquiter	acquitoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
presupposer	presupposois	V;IPFV;IND;SG;1;PST;LGSPEC1
entrencontrer	entrencontreryons	V;COND;PL;1;LGSPEC2
devourer	devourez	V;IND;PL;2;PRS
combiner	combinassions	V;IPFV;SBJV;PL;1;PST
soucyer	soucyoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
allaicter	allaicterez	V;IND;PL;2;FUT
pryer	pryasse	V;IPFV;SBJV;SG;1;PST
iurer	iureront	V;IND;PL;3;FUT
raporter	raportyons	V;IPFV;IND;PL;1;PST;LGSPEC2
recuperer	recuperoit	V;IPFV;IND;SG;3;PST;LGSPEC1
accompaigner	accompaigne	V;IND;SG;1;PRS
gaimenter	gaimentoys	V;IPFV;IND;SG;2;PST;LGSPEC2
amadouer	amadouons	V;SBJV;PL;1;PRS
oster	oste	V;IND;SG;3;PRS
revencher	revencheroit	V;COND;SG;3;LGSPEC1
eschever	escheveront	V;IND;PL;3;FUT
desrisier	desrisoys	V;IPFV;IND;SG;2;PST;LGSPEC2
devourer	devoura	V;PFV;IND;SG;3;PST
desbarater	desbaratasse	V;IPFV;SBJV;SG;1;PST
expeller	expelleras	V;IND;SG;2;FUT
trancher	tranchois	V;IPFV;IND;SG;2;PST;LGSPEC1
seiourner	seiournerois	V;COND;SG;1;LGSPEC1
aterminer	atermine	V;SBJV;SG;3;PRS
pryer	pryois	V;IPFV;IND;SG;2;PST;LGSPEC1
assieger	assiegyez	V;IPFV;IND;PL;2;PST;LGSPEC2
quester	questerions	V;COND;PL;1;LGSPEC1
descharger	deschargeroyt	V;COND;SG;3;LGSPEC2
donner	donnyons	V;IPFV;IND;PL;1;PST;LGSPEC2
cointoier	cointoieriez	V;COND;PL;2;LGSPEC1
abboyer	abboyoit	V;IPFV;IND;SG;3;PST;LGSPEC1
possesser	possessa	V;PFV;IND;SG;3;PST
employer	employoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
encharger	enchargeryons	V;COND;PL;1;LGSPEC2
embler	emble	V;SBJV;SG;3;PRS
aerer	aereriez	V;COND;PL;2;LGSPEC1
aboscher	abosches	V;IND;SG;2;PRS
engendrer	engendroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
aterminer	aterminerois	V;COND;SG;1;LGSPEC1
pryer	pryoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
accompaigner	accompaignoys	V;IPFV;IND;SG;1;PST;LGSPEC2
esguiser	esguisassent	V;IPFV;SBJV;PL;3;PST
revencher	revencheryez	V;COND;PL;2;LGSPEC2
regretter	regrettent	V;SBJV;PL;3;PRS
desborder	desbordassent	V;IPFV;SBJV;PL;3;PST
transgloutir	transgloutissoient	V;IPFV;IND;PL;3;PST;LGSPEC1
nouer	nouoient	V;IPFV;IND;PL;3;PST;LGSPEC1
gaimenter	gaimentez	V;IND;PL;2;PRS
habiter	habiterez	V;IND;PL;2;FUT
amer	amoient	V;IPFV;IND;PL;3;PST;LGSPEC1
descharger	descharger	V;NFIN
besoinger	besoignast	V;IPFV;SBJV;SG;3;PST
proclamer	proclamois	V;IPFV;IND;SG;2;PST;LGSPEC1
donner	donnez	V;IMP;PL;2
mortifier	mortifieriez	V;COND;PL;2;LGSPEC1
desgorger	desgorgea	V;PFV;IND;SG;1;PST
esclairer	esclaira	V;PFV;IND;SG;3;PST
advancer	advancera	V;IND;SG;3;FUT
ozer	ozeront	V;IND;PL;3;FUT
disner	disneroyt	V;COND;SG;3;LGSPEC2
humilier	humilie	V;IMP;SG;2
embler	embleryez	V;COND;PL;2;LGSPEC2
sceller	sceller	V;NFIN
pasturer	pastures	V;IND;SG;2;PRS
dancer	danceroys	V;COND;SG;1;LGSPEC2
eschieller	escielloys	V;IPFV;IND;SG;2;PST;LGSPEC2
desployer	desployera	V;IND;SG;3;FUT
entredonner	entredonneryons	V;COND;PL;1;LGSPEC2
finer	finent	V;IND;PL;3;PRS
viser	visas	V;PFV;IND;SG;2;PST
esvanter	esvantasmes	V;PFV;IND;PL;1;PST
sembler	sembleroient	V;COND;PL;3;LGSPEC1
compter	comptoys	V;IPFV;IND;SG;2;PST;LGSPEC2
nouer	noueroit	V;COND;SG;3;LGSPEC1
reigler	reigleriez	V;COND;PL;2;LGSPEC1
parler	parlasses	V;IPFV;SBJV;SG;2;PST
estimer	estime	V;SBJV;SG;3;PRS
saulver	saulvoys	V;IPFV;IND;SG;2;PST;LGSPEC2
reiecter	reiectassent	V;IPFV;SBJV;PL;3;PST
desloger	deslogeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
garder	gardent	V;IND;PL;3;PRS
serainer	seraineroyt	V;COND;SG;3;LGSPEC2
abandonner	abandonnes	V;SBJV;SG;2;PRS
descharger	deschargeoient	V;IPFV;IND;PL;3;PST;LGSPEC1
pocher	pocheryez	V;COND;PL;2;LGSPEC2
recouvrer	recouvrassions	V;IPFV;SBJV;PL;1;PST
oster	ostasses	V;IPFV;SBJV;SG;2;PST
fouragier	fourageoys	V;IPFV;IND;SG;2;PST;LGSPEC2
cercher	cercherent	V;PFV;IND;PL;3;PST
buchier	buchierois	V;COND;SG;1;LGSPEC1
guider	guide	V;IND;SG;3;PRS
persuader	persuaderions	V;COND;PL;1;LGSPEC1
serainer	serainez	V;IND;PL;2;PRS
allaicter	allaicteroyent	V;COND;PL;3;LGSPEC2
luitter	luittoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
tournoyer	tournoyes	V;IND;SG;2;PRS
devourer	devourerons	V;IND;PL;1;FUT
menasser	menassez	V;IND;PL;2;PRS
engendrer	engendrent	V;IND;PL;3;PRS
fouller	foullasmes	V;PFV;IND;PL;1;PST
demander	demandes	V;SBJV;SG;2;PRS
remerquer	remerquons	V;SBJV;PL;1;PRS
quiter	quitois	V;IPFV;IND;SG;2;PST;LGSPEC1
accomplir	accomplist	V;IPFV;SBJV;SG;3;PST
baisler	baisloit	V;IPFV;IND;SG;3;PST;LGSPEC1
quester	questasses	V;IPFV;SBJV;SG;2;PST
despuceller	despuceller	V;NFIN
desbarater	desbarate	V;IND;SG;1;PRS
desployer	desployeryez	V;COND;PL;2;LGSPEC2
iolyer	iolyois	V;IPFV;IND;SG;1;PST;LGSPEC1
praesenter	praesentast	V;IPFV;SBJV;SG;3;PST
foetter	foetteriez	V;COND;PL;2;LGSPEC1
endommaiger	endommaigeoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
mocquer	mocqueront	V;IND;PL;3;FUT
disner	disneroyent	V;COND;PL;3;LGSPEC2
buchier	buchois	V;IPFV;IND;SG;1;PST;LGSPEC1
cacher	cacheray	V;IND;SG;1;FUT;LGSPEC2
desfaire	desferas	V;IND;SG;2;FUT
provocquer	provocqueroit	V;COND;SG;3;LGSPEC1
consyderer	consydererois	V;COND;SG;2;LGSPEC1
accoustumer	accoustumeront	V;IND;PL;3;FUT
racompter	racomptoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
arrengier	arrengieroyent	V;COND;PL;3;LGSPEC2
ottroyer	ottroyoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
disner	disnez	V;SBJV;PL;2;PRS
assieger	assiegeoys	V;IPFV;IND;SG;1;PST;LGSPEC2
luitter	luittoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
tesmoigner	tesmoignassiez	V;IPFV;SBJV;PL;2;PST
atempter	atempteras	V;IND;SG;2;FUT
exstirper	exstirpast	V;IPFV;SBJV;SG;3;PST
provocquer	provocquez	V;IND;PL;2;PRS
pausmer	pausmeryez	V;COND;PL;2;LGSPEC2
operer	operes	V;SBJV;SG;2;PRS
armoier	armoient	V;IND;PL;3;PRS
vuider	vuidasmes	V;PFV;IND;PL;1;PST
ordonner	ordonnons	V;IND;PL;1;PRS
garder	garderois	V;COND;SG;2;LGSPEC1
affier	affie	V;IND;SG;1;PRS
cryer	cryasse	V;IPFV;SBJV;SG;1;PST
pourpenser	pourpenserez	V;IND;PL;2;FUT
quiter	quiter	V;NFIN
consyderer	consyderions	V;IPFV;IND;PL;1;PST;LGSPEC1
sembler	semblassent	V;IPFV;SBJV;PL;3;PST
reigler	reigle	V;SBJV;SG;1;PRS
desbarater	desbarations	V;IPFV;IND;PL;1;PST;LGSPEC1
galoper	galoper	V;NFIN
soubhaitter	soubhaitta	V;PFV;IND;SG;3;PST
pausmer	pausmons	V;IMP;PL;1
proteger	proteges	V;SBJV;SG;2;PRS
praesenter	praesentes	V;IND;SG;2;PRS
seiourner	seiournerois	V;COND;SG;2;LGSPEC1
presumer	presumois	V;IPFV;IND;SG;1;PST;LGSPEC1
coniurer	coniurons	V;IMP;PL;1
remonstrer	remonstrons	V;IND;PL;1;PRS
effronter	effrontasse	V;IPFV;SBJV;SG;1;PST
coniurer	coniureroys	V;COND;SG;1;LGSPEC2
saulver	saulve	V;IND;SG;3;PRS
pourpenser	pourpensons	V;IMP;PL;1
deifier	deifieryez	V;COND;PL;2;LGSPEC2
demonstrer	demonstreroit	V;COND;SG;3;LGSPEC1
escouiller	escouilloys	V;IPFV;IND;SG;1;PST;LGSPEC2
geller	gellerois	V;COND;SG;1;LGSPEC1
cesser	cessions	V;IPFV;IND;PL;1;PST;LGSPEC1
subiuger	subiuge	V;SBJV;SG;1;PRS
traitter	traittyons	V;IPFV;IND;PL;1;PST;LGSPEC2
singler	singlas	V;PFV;IND;SG;2;PST
cuyder	cuyda	V;PFV;IND;SG;1;PST
entrer	entrerent	V;PFV;IND;PL;3;PST
entrehurter	s'entrehurteroient	V;COND;PL;3;LGSPEC1
deshonnourer	deshonnoureroient	V;COND;PL;3;LGSPEC1
gaimenter	gaimentez	V;IMP;PL;2
flechir	fleschissent	V;IPFV;SBJV;PL;3;PST
nouer	nouez	V;IMP;PL;2
quereler	querelassions	V;IPFV;SBJV;PL;1;PST
saluer	saluerent	V;PFV;IND;PL;3;PST
redoubter	redoubtoient	V;IPFV;IND;PL;3;PST;LGSPEC1
employer	employasses	V;IPFV;SBJV;SG;2;PST
recuperer	recuperasses	V;IPFV;SBJV;SG;2;PST
abiurer	abiurois	V;IPFV;IND;SG;2;PST;LGSPEC1
cryer	cryoient	V;IPFV;IND;PL;3;PST;LGSPEC1
aboscher	aboscheray	V;IND;SG;1;FUT;LGSPEC2
entrencontrer	entrencontroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
enyvrer	enyvryez	V;IPFV;IND;PL;2;PST;LGSPEC2
recouvrer	recouvroit	V;IPFV;IND;SG;3;PST;LGSPEC1
encommencer	encommenceryez	V;COND;PL;2;LGSPEC2
regretter	regrettoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
picquier	picquastes	V;PFV;IND;PL;2;PST
mulcter	mulcterois	V;COND;SG;1;LGSPEC1
trousser	troussasses	V;IPFV;SBJV;SG;2;PST
enpoisonner	enpoisonnoys	V;IPFV;IND;SG;1;PST;LGSPEC2
resver	resvoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
empoizonner	empoizonner	V;NFIN
assieger	assiegeastes	V;PFV;IND;PL;2;PST
marcher	marchoys	V;IPFV;IND;SG;2;PST;LGSPEC2
prattiquer	prattiqueroyent	V;COND;PL;3;LGSPEC2
fouragier	fourageassiez	V;IPFV;SBJV;PL;2;PST
approuvender	approuvenderions	V;COND;PL;1;LGSPEC1
entituler	entitulent	V;IND;PL;3;PRS
remerquer	remerques	V;SBJV;SG;2;PRS
assieger	assieger	V;NFIN
negotier	negotiois	V;IPFV;IND;SG;1;PST;LGSPEC1
praesenter	praesenteroyt	V;COND;SG;3;LGSPEC2
esguarer	esguarera	V;IND;SG;3;FUT
acquiter	acquiterai	V;IND;SG;1;FUT;LGSPEC1
alimenter	alimentyez	V;IPFV;IND;PL;2;PST;LGSPEC2
assister	assistez	V;IND;PL;2;PRS
disner	disnois	V;IPFV;IND;SG;1;PST;LGSPEC1
enpoisonner	enpoisonnez	V;IMP;PL;2
alonger	alongeassiez	V;IPFV;SBJV;PL;2;PST
combiner	combineray	V;IND;SG;1;FUT;LGSPEC2
monstrer	monstre	V;IND;SG;1;PRS
raporter	raportera	V;IND;SG;3;FUT
eschauffer	eschaufferyez	V;COND;PL;2;LGSPEC2
esvanter	esvantyez	V;IPFV;IND;PL;2;PST;LGSPEC2
chocquer	chocquoient	V;IPFV;IND;PL;3;PST;LGSPEC1
achever	acheverois	V;COND;SG;1;LGSPEC1
fouragier	fourageasses	V;IPFV;SBJV;SG;2;PST
charger	chargeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
aloser	aloseriez	V;COND;PL;2;LGSPEC1
esloigner	esloignoit	V;IPFV;IND;SG;3;PST;LGSPEC1
esmayer	esmayer	V;NFIN
aymer	aymoient	V;IPFV;IND;PL;3;PST;LGSPEC1
flechir	fleschissoient	V;IPFV;IND;PL;3;PST;LGSPEC1
raporter	raportez	V;IND;PL;2;PRS
racompter	racomptassiez	V;IPFV;SBJV;PL;2;PST
remerquer	remerqueroit	V;COND;SG;3;LGSPEC1
accoustumer	accoustume	V;SBJV;SG;3;PRS
sembler	semble	V;SBJV;SG;3;PRS
soubhaitter	soubhaittez	V;IND;PL;2;PRS
garder	garderont	V;IND;PL;3;FUT
entrer	entreras	V;IND;SG;2;FUT
tournoyer	tournoyoys	V;IPFV;IND;SG;1;PST;LGSPEC2
accoustumer	accoustumerois	V;COND;SG;2;LGSPEC1
chocquer	chocques	V;IND;SG;2;PRS
parler	parle	V;SBJV;SG;1;PRS
flechir	fleschismes	V;PFV;IND;PL;1;PST
empoizonner	empoizonna	V;PFV;IND;SG;1;PST
operer	operoys	V;IPFV;IND;SG;1;PST;LGSPEC2
fortifier	fortifierez	V;IND;PL;2;FUT
esgarer	esgariez	V;IPFV;IND;PL;2;PST;LGSPEC1
pasturer	pastura	V;PFV;IND;SG;3;PST
abiurer	abiuroient	V;IPFV;IND;PL;3;PST;LGSPEC1
alimenter	alimenterai	V;IND;SG;1;FUT;LGSPEC1
lescher	lescherions	V;COND;PL;1;LGSPEC1
esprouver	esprouviez	V;IPFV;IND;PL;2;PST;LGSPEC1
recuperer	recupererions	V;COND;PL;1;LGSPEC1
redoubter	redoubteryez	V;COND;PL;2;LGSPEC2
provocquer	provocquois	V;IPFV;IND;SG;1;PST;LGSPEC1
tumber	tumberons	V;IND;PL;1;FUT
monstrer	monstroient	V;IPFV;IND;PL;3;PST;LGSPEC1
ozer	ozes	V;IND;SG;2;PRS
edifier	edifient	V;SBJV;PL;3;PRS
esmayer	esmayoys	V;IPFV;IND;SG;2;PST;LGSPEC2
aterminer	aterminasse	V;IPFV;SBJV;SG;1;PST
resver	resves	V;SBJV;SG;2;PRS
desgorger	desgorgeras	V;IND;SG;2;FUT
vengier	vengions	V;IPFV;IND;PL;1;PST;LGSPEC1
abboyer	abboye	V;SBJV;SG;1;PRS
transporter	transportasse	V;IPFV;SBJV;SG;1;PST
uriner	urinerois	V;COND;SG;2;LGSPEC1
perser	persoient	V;IPFV;IND;PL;3;PST;LGSPEC1
logier	logeasmes	V;PFV;IND;PL;1;PST
quester	questerai	V;IND;SG;1;FUT;LGSPEC1
transporter	transportes	V;IND;SG;2;PRS
pryer	pryez	V;SBJV;PL;2;PRS
ottroyer	ottroyez	V;IMP;PL;2
hucher	huchons	V;IMP;PL;1
advancer	advanceroyent	V;COND;PL;3;LGSPEC2
effronter	effrontassions	V;IPFV;SBJV;PL;1;PST
gangler	ganglerent	V;PFV;IND;PL;3;PST
encharger	enchargyons	V;IPFV;IND;PL;1;PST;LGSPEC2
huer	huerons	V;IND;PL;1;FUT
saulver	saulvois	V;IPFV;IND;SG;2;PST;LGSPEC1
arrengier	arrengieroys	V;COND;SG;1;LGSPEC2
demourer	demourasses	V;IPFV;SBJV;SG;2;PST
practicquer	practicque	V;IMP;SG;2
deifier	deifieroit	V;COND;SG;3;LGSPEC1
aorner	aornerons	V;IND;PL;1;FUT
peser	peseriez	V;COND;PL;2;LGSPEC1
racompter	racompte	V;IND;SG;3;PRS
tocquer	tocquasses	V;IPFV;SBJV;SG;2;PST
saluer	saluoit	V;IPFV;IND;SG;3;PST;LGSPEC1
remerquer	remerquoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
negotier	negotioit	V;IPFV;IND;SG;3;PST;LGSPEC1
sceller	scellerent	V;PFV;IND;PL;3;PST
tirer	tirer	V;NFIN
geller	gelleroys	V;COND;SG;2;LGSPEC2
recuperer	recupereront	V;IND;PL;3;FUT
heiler	heileriez	V;COND;PL;2;LGSPEC1
soucyer	soucyez	V;IMP;PL;2
acoustumer	acoustumerions	V;COND;PL;1;LGSPEC1
aerer	aerez	V;IMP;PL;2
mortifier	mortifieroient	V;COND;PL;3;LGSPEC1
redrechier	redreche	V;IND;SG;1;PRS
tournoyer	tournoyeroys	V;COND;SG;2;LGSPEC2
recouvrer	recouvroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
interpreter	interpretons	V;SBJV;PL;1;PRS
lescher	leschassions	V;IPFV;SBJV;PL;1;PST
desployer	desploye	V;IMP;SG;2
estimer	estimez	V;SBJV;PL;2;PRS
eslancer	eslanceriez	V;COND;PL;2;LGSPEC1
assieger	assiegiez	V;IPFV;IND;PL;2;PST;LGSPEC1
fouragier	fouragyez	V;IPFV;IND;PL;2;PST;LGSPEC2
proteger	protegeast	V;IPFV;SBJV;SG;3;PST
desborder	desborda	V;PFV;IND;SG;1;PST
effronter	effrontast	V;IPFV;SBJV;SG;3;PST
gaimenter	gaimentyez	V;IPFV;IND;PL;2;PST;LGSPEC2
monstrer	monstra	V;PFV;IND;SG;1;PST
quiter	quitasmes	V;PFV;IND;PL;1;PST
atempter	atemptons	V;SBJV;PL;1;PRS
luitter	luitteriez	V;COND;PL;2;LGSPEC1
desguiser	desguisois	V;IPFV;IND;SG;2;PST;LGSPEC1
gangler	ganglerai	V;IND;SG;1;FUT;LGSPEC1
besoinger	besoigneryons	V;COND;PL;1;LGSPEC2
pourforcer	pourforceray	V;IND;SG;1;FUT;LGSPEC2
sembler	semblasses	V;IPFV;SBJV;SG;2;PST
perser	perseryez	V;COND;PL;2;LGSPEC2
deslyer	deslyer	V;NFIN
respirer	respireras	V;IND;SG;2;FUT
toquer	toquent	V;SBJV;PL;3;PRS
advancer	advançassiez	V;IPFV;SBJV;PL;2;PST
deifier	deifia	V;PFV;IND;SG;1;PST
reculler	reculloys	V;IPFV;IND;SG;1;PST;LGSPEC2
alimenter	alimente	V;SBJV;SG;3;PRS
retourner	retournasse	V;IPFV;SBJV;SG;1;PST
hucher	hucheroyt	V;COND;SG;3;LGSPEC2
eslancer	eslançons	V;IND;PL;1;PRS
entrehurter	nous entrehurtons	V;SBJV;PL;1;PRS
devourer	devoureras	V;IND;SG;2;FUT
robber	robber	V;NFIN
courouchier	courouchieras	V;IND;SG;2;FUT
pecher	pechez	V;IMP;PL;2
avanchier	avanchions	V;IMP;PL;1
quereler	querelois	V;IPFV;IND;SG;2;PST;LGSPEC1
laisser	laisseroient	V;COND;PL;3;LGSPEC1
escouter	escoutassiez	V;IPFV;SBJV;PL;2;PST
presumer	presumes	V;SBJV;SG;2;PRS
presupposer	presupposeriez	V;COND;PL;2;LGSPEC1
desgorger	desgorgeas	V;PFV;IND;SG;2;PST
huer	huiez	V;IPFV;IND;PL;2;PST;LGSPEC1
deschirer	deschirez	V;SBJV;PL;2;PRS
deslyer	deslyeroyt	V;COND;SG;3;LGSPEC2
laisser	laisseryez	V;COND;PL;2;LGSPEC2
demonstrer	demonstra	V;PFV;IND;SG;1;PST
porter	portas	V;PFV;IND;SG;2;PST
leicher	leicha	V;PFV;IND;SG;3;PST
robber	robbassent	V;IPFV;SBJV;PL;3;PST
conquester	conquesterions	V;COND;PL;1;LGSPEC1
heiler	heiles	V;IND;SG;2;PRS
desprisonner	desprisonnerois	V;COND;SG;1;LGSPEC1
assister	assisteroys	V;COND;SG;1;LGSPEC2
achever	acheveroys	V;COND;SG;2;LGSPEC2
avanchier	avanchent	V;IND;PL;3;PRS
encliner	enclinastes	V;PFV;IND;PL;2;PST
cryer	cryassiez	V;IPFV;SBJV;PL;2;PST
soubhaitter	soubhaitterions	V;COND;PL;1;LGSPEC1
trancher	tranchasmes	V;PFV;IND;PL;1;PST
edifier	edifie	V;SBJV;SG;1;PRS
desirer	desiroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
trancher	tranchent	V;IND;PL;3;PRS
deslyer	deslyent	V;SBJV;PL;3;PRS
cointoier	cointoieroys	V;COND;SG;1;LGSPEC2
approuvender	approuvendassent	V;IPFV;SBJV;PL;3;PST
traitter	traittasse	V;IPFV;SBJV;SG;1;PST
accomplir	accomplis	V;IMP;SG;2
finer	fina	V;PFV;IND;SG;3;PST
delivrer	delivrez	V;IMP;PL;2
retyrer	retyres	V;IND;SG;2;PRS
respirer	respirez	V;IND;PL;2;PRS
mocquer	mocque	V;IMP;SG;2
renommer	renommeriez	V;COND;PL;2;LGSPEC1
combiner	combina	V;PFV;IND;SG;1;PST
trousser	trousseryons	V;COND;PL;1;LGSPEC2
