aorner	aornoys	V;IPFV;IND;SG;1;PST;LGSPEC2
empirer	empirons	V;IMP;PL;1
aller	aille	V;SBJV;SG;1;PRS
aboscher	aboschyez	V;IPFV;IND;PL;2;PST;LGSPEC2
mesler	mesliez	V;IPFV;IND;PL;2;PST;LGSPEC1
esplucher	espluche	V;IND;SG;3;PRS
inquieter	inquietasmes	V;PFV;IND;PL;1;PST
saulver	saulves	V;SBJV;SG;2;PRS
proclamer	proclameront	V;IND;PL;3;FUT
aler	aloit	V;IPFV;IND;SG;3;PST
infourmer	infourmerai	V;IND;SG;1;FUT;LGSPEC1
destourner	destourne	V;SBJV;SG;1;PRS
poiser	poiseroit	V;COND;SG;3;LGSPEC1
dancer	dancions	V;IPFV;IND;PL;1;PST;LGSPEC1
escapper	escapperoys	V;COND;SG;1;LGSPEC2
toquer	toquasses	V;IPFV;SBJV;SG;2;PST
emerger	emergeryons	V;COND;PL;1;LGSPEC2
tyrer	tyrassent	V;IPFV;SBJV;PL;3;PST
preparer	preparastes	V;PFV;IND;PL;2;PST
proclamer	proclamast	V;IPFV;SBJV;SG;3;PST
delivrer	delivreroys	V;COND;SG;1;LGSPEC2
entrehurter	nous entrehurtasmes	V;PFV;IND;PL;1;PST
haittier	haittasse	V;IPFV;SBJV;SG;1;PST
practicquer	practicqueroient	V;COND;PL;3;LGSPEC1
apuyer	apuyerois	V;COND;SG;1;LGSPEC1
inquieter	inquietions	V;IPFV;IND;PL;1;PST;LGSPEC1
appeller	appellasmes	V;PFV;IND;PL;1;PST
desyrer	desyreroyent	V;COND;PL;3;LGSPEC2
haster	hasteroit	V;COND;SG;3;LGSPEC1
aler	alastes	V;PFV;IND;PL;2;PST
achever	acheveront	V;IND;PL;3;FUT
bancqueter	bancqueterez	V;IND;PL;2;FUT
enchargier	enchargierions	V;COND;PL;1;LGSPEC1
desancrer	desancreryons	V;COND;PL;1;LGSPEC2
transporter	transportions	V;IPFV;IND;PL;1;PST;LGSPEC1
macter	macterois	V;COND;SG;2;LGSPEC1
despossesser	despossesserons	V;IND;PL;1;FUT
mesler	mesle	V;SBJV;SG;1;PRS
oster	ostoient	V;IPFV;IND;PL;3;PST;LGSPEC1
praesenter	praesentiez	V;IPFV;IND;PL;2;PST;LGSPEC1
flechir	fleschissiez	V;SBJV;PL;2;PRS
soulaiger	soulaigeront	V;IND;PL;3;FUT
mectre	mectois	V;IPFV;IND;SG;2;PST;LGSPEC1
entrer	entrois	V;IPFV;IND;SG;2;PST;LGSPEC1
inquieter	inquietoys	V;IPFV;IND;SG;1;PST;LGSPEC2
resider	residerent	V;PFV;IND;PL;3;PST
rejecter	rejectasse	V;IPFV;SBJV;SG;1;PST
desplacer	desplacerez	V;IND;PL;2;FUT
esperonner	esperonnons	V;IMP;PL;1
cercher	cercherois	V;COND;SG;1;LGSPEC1
rejecter	rejecterai	V;IND;SG;1;FUT;LGSPEC1
desyrer	desyrez	V;SBJV;PL;2;PRS
contribuer	contribuastes	V;PFV;IND;PL;2;PST
reigler	reigloit	V;IPFV;IND;SG;3;PST;LGSPEC1
esveiller	esveillez	V;SBJV;PL;2;PRS
representer	representas	V;PFV;IND;SG;2;PST
visiter	visite	V;SBJV;SG;3;PRS
creancer	creancez	V;IMP;PL;2
destourner	destournes	V;IND;SG;2;PRS
traitter	traittois	V;IPFV;IND;SG;1;PST;LGSPEC1
gaster	gasteroyent	V;COND;PL;3;LGSPEC2
conseiller	conseillastes	V;PFV;IND;PL;2;PST
lescher	lescheroyent	V;COND;PL;3;LGSPEC2
lever	levoient	V;IPFV;IND;PL;3;PST;LGSPEC1
destabler	destablons	V;IND;PL;1;PRS
regarder	regarderyons	V;COND;PL;1;LGSPEC2
tomber	tombons	V;SBJV;PL;1;PRS
traitter	traittoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
esperonner	esperonnoit	V;IPFV;IND;SG;3;PST;LGSPEC1
baster	bastons	V;IND;PL;1;PRS
haittier	haittieroys	V;COND;SG;2;LGSPEC2
desrisier	desrisierent	V;PFV;IND;PL;3;PST
lescher	lesche	V;IMP;SG;2
entrer	entryons	V;IPFV;IND;PL;1;PST;LGSPEC2
entrer	entre	V;SBJV;SG;1;PRS
conseiller	conseilleroys	V;COND;SG;2;LGSPEC2
descharger	deschargerois	V;COND;SG;1;LGSPEC1
desrobber	desrobberoyt	V;COND;SG;3;LGSPEC2
employer	employerions	V;COND;PL;1;LGSPEC1
macter	macterai	V;IND;SG;1;FUT;LGSPEC1
descourager	descouragyez	V;IPFV;IND;PL;2;PST;LGSPEC2
considerer	considererai	V;IND;SG;1;FUT;LGSPEC1
aguyser	aguysas	V;PFV;IND;SG;2;PST
gaigner	gaignas	V;PFV;IND;SG;2;PST
detranchier	detranchions	V;IPFV;IND;PL;1;PST;LGSPEC1
emerger	emergiez	V;IPFV;IND;PL;2;PST;LGSPEC1
debaracer	debaracerons	V;IND;PL;1;FUT
considerer	considerent	V;IND;PL;3;PRS
praesenter	praesenteroit	V;COND;SG;3;LGSPEC1
acoustrer	acoustreroys	V;COND;SG;2;LGSPEC2
debaracer	debaracerois	V;COND;SG;1;LGSPEC1
occuper	occupe	V;IND;SG;3;PRS
representer	representeray	V;IND;SG;1;FUT;LGSPEC2
acoustumer	acoustumeroys	V;COND;SG;1;LGSPEC2
considerer	considera	V;PFV;IND;SG;1;PST
desconseiller	desconseillastes	V;PFV;IND;PL;2;PST
couster	cousteroit	V;COND;SG;3;LGSPEC1
approuvender	approuvenderois	V;COND;SG;1;LGSPEC1
cuyder	cuyderoient	V;COND;PL;3;LGSPEC1
despossesser	despossessois	V;IPFV;IND;SG;2;PST;LGSPEC1
rouiller	rouilla	V;PFV;IND;SG;1;PST
chocquer	chocquassent	V;IPFV;SBJV;PL;3;PST
coniurer	coniuroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
cuyder	cuyderyez	V;COND;PL;2;LGSPEC2
haittier	haittiez	V;IPFV;IND;PL;2;PST;LGSPEC1
practicquer	practicque	V;IND;SG;1;PRS
tournoyer	tournoyerois	V;COND;SG;1;LGSPEC1
macter	macte	V;IND;SG;1;PRS
destabler	destableroit	V;COND;SG;3;LGSPEC1
aboscher	aboschas	V;PFV;IND;SG;2;PST
encommencer	encommençasmes	V;PFV;IND;PL;1;PST
enferrer	enferrastes	V;PFV;IND;PL;2;PST
tomber	tombasmes	V;PFV;IND;PL;1;PST
finir	finis	V;IND;SG;2;PRS
reietter	reiettassiez	V;IPFV;SBJV;PL;2;PST
soulaiger	soulaigerez	V;IND;PL;2;FUT
desrobber	desrobbe	V;IND;SG;1;PRS
raporter	raportions	V;IPFV;IND;PL;1;PST;LGSPEC1
despossesser	despossessast	V;IPFV;SBJV;SG;3;PST
renouveller	renouvelloient	V;IPFV;IND;PL;3;PST;LGSPEC1
desyrer	desyrons	V;SBJV;PL;1;PRS
quiter	quiterois	V;COND;SG;1;LGSPEC1
ordonner	ordonnasmes	V;PFV;IND;PL;1;PST
espouser	espousa	V;PFV;IND;SG;3;PST
descharger	deschargeastes	V;PFV;IND;PL;2;PST
employer	employassions	V;IPFV;SBJV;PL;1;PST
fumer	fuma	V;PFV;IND;SG;1;PST
celebrer	celebrerions	V;COND;PL;1;LGSPEC1
reigler	reigliez	V;IPFV;IND;PL;2;PST;LGSPEC1
oster	osteroyt	V;COND;SG;3;LGSPEC2
renouveller	renouvelleryez	V;COND;PL;2;LGSPEC2
despossesser	despossesseroys	V;COND;SG;1;LGSPEC2
desplacer	desplaçast	V;IPFV;SBJV;SG;3;PST
visiter	visite	V;IND;SG;3;PRS
aboscher	abosche	V;IND;SG;1;PRS
emerger	emerge	V;IMP;SG;2
denunchier	denunchieras	V;IND;SG;2;FUT
deslyer	deslyyons	V;IPFV;IND;PL;1;PST;LGSPEC2
aller	allas	V;PFV;IND;SG;2;PST
ordonner	ordonneront	V;IND;PL;3;FUT
arrester	arrestoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
despossesser	despossesseroient	V;COND;PL;3;LGSPEC1
racointer	racointasmes	V;PFV;IND;PL;1;PST
debaracer	debarace	V;IMP;SG;2
oster	osteryons	V;COND;PL;1;LGSPEC2
gaster	gasterions	V;COND;PL;1;LGSPEC1
bancqueter	bancqueteryons	V;COND;PL;1;LGSPEC2
escapper	escappions	V;IPFV;IND;PL;1;PST;LGSPEC1
aller	vont	V;IND;PL;3;PRS
denunchier	denunchierois	V;COND;SG;2;LGSPEC1
gaigner	gaignez	V;IMP;PL;2
descharger	deschargea	V;PFV;IND;SG;1;PST
destabler	destabla	V;PFV;IND;SG;3;PST
fumer	fumez	V;IMP;PL;2
guerpir	guerpissons	V;IND;PL;1;PRS
lever	leveryons	V;COND;PL;1;LGSPEC2
renouveller	renouvellons	V;SBJV;PL;1;PRS
employer	employasse	V;IPFV;SBJV;SG;1;PST
lescher	leschons	V;IND;PL;1;PRS
entrempescher	vous entrempeschez	V;SBJV;PL;2;PRS
flechir	fleschissions	V;IPFV;SBJV;PL;1;PST
racointer	racointeras	V;IND;SG;2;FUT
couster	coustyons	V;IPFV;IND;PL;1;PST;LGSPEC2
desieuner	desieuneroys	V;COND;SG;2;LGSPEC2
gaigner	gaignerions	V;COND;PL;1;LGSPEC1
descharger	deschargeroys	V;COND;SG;1;LGSPEC2
esplucher	espluchyez	V;IPFV;IND;PL;2;PST;LGSPEC2
delivrer	delivreroys	V;COND;SG;2;LGSPEC2
meriter	merita	V;PFV;IND;SG;3;PST
conseiller	conseillasmes	V;PFV;IND;PL;1;PST
cacher	cacherois	V;COND;SG;1;LGSPEC1
visiter	visiterai	V;IND;SG;1;FUT;LGSPEC1
subiuguier	subiuguiez	V;IMP;PL;2
occuper	occuperyez	V;COND;PL;2;LGSPEC2
considerer	considereriez	V;COND;PL;2;LGSPEC1
soulaiger	soulaigeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
haster	haste	V;IND;SG;3;PRS
chocquer	chocques	V;SBJV;SG;2;PRS
eschever	escheva	V;PFV;IND;SG;1;PST
contribuer	contribueront	V;IND;PL;3;FUT
conseiller	conseillez	V;IMP;PL;2
cercher	cercheryez	V;COND;PL;2;LGSPEC2
uriner	urinast	V;IPFV;SBJV;SG;3;PST
aorner	aornerent	V;PFV;IND;PL;3;PST
saulver	saulvois	V;IPFV;IND;SG;1;PST;LGSPEC1
guerpir	guerpiront	V;IND;PL;3;FUT
porter	portons	V;IND;PL;1;PRS
cacher	cachassiez	V;IPFV;SBJV;PL;2;PST
minorer	minore	V;IND;SG;1;PRS
entrefraper	s'entrefrapent	V;SBJV;PL;3;PRS
encommencer	encommençoys	V;IPFV;IND;SG;2;PST;LGSPEC2
desancrer	desancre	V;IMP;SG;2
chocquer	chocqueras	V;IND;SG;2;FUT
enferrer	enferreras	V;IND;SG;2;FUT
gaigner	gaigneront	V;IND;PL;3;FUT
desregler	desregloys	V;IPFV;IND;SG;2;PST;LGSPEC2
dancer	dance	V;SBJV;SG;1;PRS
desplacer	desplaceras	V;IND;SG;2;FUT
porter	porterois	V;COND;SG;1;LGSPEC1
traitter	traitteriez	V;COND;PL;2;LGSPEC1
reietter	reiettons	V;IMP;PL;1
praesenter	praesentons	V;IND;PL;1;PRS
fluir	fluissent	V;IPFV;SBJV;PL;3;PST
visiter	visita	V;PFV;IND;SG;3;PST
descourager	descourageoys	V;IPFV;IND;SG;1;PST;LGSPEC2
desrisier	desrisieryez	V;COND;PL;2;LGSPEC2
effreer	effreons	V;IMP;PL;1
recommander	recommandent	V;SBJV;PL;3;PRS
denunchier	denunchieroys	V;COND;SG;1;LGSPEC2
desmeler	desmeles	V;SBJV;SG;2;PRS
flechir	fleschisse	V;SBJV;SG;3;PRS
praesenter	praesentes	V;IND;SG;2;PRS
tournoyer	tournoyes	V;IND;SG;2;PRS
acoustrer	acoustre	V;SBJV;SG;1;PRS
inquieter	inquietassiez	V;IPFV;SBJV;PL;2;PST
approuvender	approuvendyez	V;IPFV;IND;PL;2;PST;LGSPEC2
traitter	traittes	V;IND;SG;2;PRS
esperer	espereryez	V;COND;PL;2;LGSPEC2
bobeliner	bobelinerez	V;IND;PL;2;FUT
emerger	emergeroys	V;COND;SG;1;LGSPEC2
macter	mactent	V;SBJV;PL;3;PRS
abhorrer	abhorrois	V;IPFV;IND;SG;1;PST;LGSPEC1
desconseiller	desconseilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
infourmer	infourmeront	V;IND;PL;3;FUT
considerer	considerent	V;SBJV;PL;3;PRS
soupper	souppe	V;SBJV;SG;3;PRS
considerer	considerois	V;IPFV;IND;SG;2;PST;LGSPEC1
delivrer	delivreront	V;IND;PL;3;FUT
rouiller	rouilleroys	V;COND;SG;1;LGSPEC2
delivrer	delivras	V;PFV;IND;SG;2;PST
fluir	fluiroient	V;COND;PL;3;LGSPEC1
representer	representyons	V;IPFV;IND;PL;1;PST;LGSPEC2
reigler	reiglons	V;IND;PL;1;PRS
minorer	minoras	V;PFV;IND;SG;2;PST
enferrer	enferrasse	V;IPFV;SBJV;SG;1;PST
deslyer	deslyez	V;IND;PL;2;PRS
mesler	meslassions	V;IPFV;SBJV;PL;1;PST
cacher	cacheront	V;IND;PL;3;FUT
guerpir	guerpissons	V;IMP;PL;1
desancrer	desancrois	V;IPFV;IND;SG;2;PST;LGSPEC1
porter	porter	V;NFIN
dancer	dancerons	V;IND;PL;1;FUT
mortifier	mortifieray	V;IND;SG;1;FUT;LGSPEC2
entrehurter	nousentrehurterions	V;COND;PL;1;LGSPEC1
lescher	leschera	V;IND;SG;3;FUT
desborder	desborderas	V;IND;SG;2;FUT
deschirer	deschirez	V;SBJV;PL;2;PRS
meriter	meriteryez	V;COND;PL;2;LGSPEC2
oster	ostions	V;IPFV;IND;PL;1;PST;LGSPEC1
reietter	reiettons	V;IND;PL;1;PRS
desplacer	desplaciez	V;IPFV;IND;PL;2;PST;LGSPEC1
courrouchier	courrouchast	V;IPFV;SBJV;SG;3;PST
faucer	fauçons	V;SBJV;PL;1;PRS
desrobber	desrobbois	V;IPFV;IND;SG;2;PST;LGSPEC1
reietter	reiettera	V;IND;SG;3;FUT
porter	portez	V;IND;PL;2;PRS
acoustrer	acoustrerions	V;COND;PL;1;LGSPEC1
exposer	expose	V;IMP;SG;2
desancrer	desancra	V;PFV;IND;SG;1;PST
desplacer	desplaçoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
descharger	deschargiez	V;IPFV;IND;PL;2;PST;LGSPEC1
haster	hasteroient	V;COND;PL;3;LGSPEC1
apuyer	apuyerai	V;IND;SG;1;FUT;LGSPEC1
merveiller	merveille	V;SBJV;SG;1;PRS
iniurier	iniuria	V;PFV;IND;SG;1;PST
gaigner	gaignoient	V;IPFV;IND;PL;3;PST;LGSPEC1
esperonner	esperonnoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
escapper	escappast	V;IPFV;SBJV;SG;3;PST
payer	payeriez	V;COND;PL;2;LGSPEC1
emerger	emerger	V;NFIN
enchargier	enchargieroys	V;COND;SG;2;LGSPEC2
renger	rengeasmes	V;PFV;IND;PL;1;PST
entrehurter	s'entrehurteroient	V;COND;PL;3;LGSPEC1
aerer	aera	V;PFV;IND;SG;3;PST
payer	payyez	V;IPFV;IND;PL;2;PST;LGSPEC2
regratier	regratiez	V;SBJV;PL;2;PRS
descharger	deschargerez	V;IND;PL;2;FUT
esperer	esperastes	V;PFV;IND;PL;2;PST
tournoyer	tournoyasses	V;IPFV;SBJV;SG;2;PST
finir	finisse	V;IPFV;SBJV;SG;1;PST
apuyer	apuyerois	V;COND;SG;2;LGSPEC1
descourager	descouragez	V;IMP;PL;2
sembler	sembleras	V;IND;SG;2;FUT
desplacer	desplaças	V;PFV;IND;SG;2;PST
detranchier	detranchions	V;IMP;PL;1
desyrer	desyrerez	V;IND;PL;2;FUT
traitter	traittassent	V;IPFV;SBJV;PL;3;PST
jecter	jectons	V;IND;PL;1;PRS
acoustrer	acoustrer	V;NFIN
accoustumer	accoustumerent	V;PFV;IND;PL;3;PST
aller	allassiez	V;IPFV;SBJV;PL;2;PST
macter	mactons	V;SBJV;PL;1;PRS
parler	parleroys	V;COND;SG;1;LGSPEC2
tomber	tombas	V;PFV;IND;SG;2;PST
saulver	saulveroys	V;COND;SG;2;LGSPEC2
ordonner	ordonner	V;NFIN
enchargier	enchargieront	V;IND;PL;3;FUT
encommencer	encommençoit	V;IPFV;IND;SG;3;PST;LGSPEC1
adviser	advisez	V;SBJV;PL;2;PRS
escapper	escappera	V;IND;SG;3;FUT
regratier	regratient	V;SBJV;PL;3;PRS
desrober	desroberoit	V;COND;SG;3;LGSPEC1
deslyer	deslyez	V;IMP;PL;2
resider	residera	V;IND;SG;3;FUT
descharger	descharge	V;SBJV;SG;1;PRS
destabler	destableroyt	V;COND;SG;3;LGSPEC2
haittier	haitta	V;PFV;IND;SG;3;PST
minorer	minorerai	V;IND;SG;1;FUT;LGSPEC1
acoustrer	acoustrez	V;IMP;PL;2
entrempescher	vousentrempeschiez	V;IPFV;IND;PL;2;PST;LGSPEC1
bancqueter	bancqueteroyt	V;COND;SG;3;LGSPEC2
desconseiller	desconseilloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
lescher	lescherai	V;IND;SG;1;FUT;LGSPEC1
mectre	mectroient	V;COND;PL;3;LGSPEC1
mortifier	mortifiasmes	V;PFV;IND;PL;1;PST
encommencer	encommenceroys	V;COND;SG;1;LGSPEC2
achever	achevas	V;PFV;IND;SG;2;PST
desmeler	desmeles	V;IND;SG;2;PRS
gaster	gastastes	V;PFV;IND;PL;2;PST
approuvender	approuvendiez	V;IPFV;IND;PL;2;PST;LGSPEC1
cuyder	cuyderay	V;IND;SG;1;FUT;LGSPEC2
aler	alois	V;IPFV;IND;SG;2;PST
coniurer	coniurerions	V;COND;PL;1;LGSPEC1
achever	achevez	V;SBJV;PL;2;PRS
humilier	humilions	V;IMP;PL;1
soulaiger	soulaigeras	V;IND;SG;2;FUT
aller	ailles	V;SBJV;SG;2;PRS
saulver	saulvera	V;IND;SG;3;FUT
nommer	nommoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
coniurer	coniuras	V;PFV;IND;SG;2;PST
inquieter	inquietoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
gaster	gastions	V;IPFV;IND;PL;1;PST;LGSPEC1
delivrer	delivrons	V;SBJV;PL;1;PRS
ayder	aydes	V;IND;SG;2;PRS
aler	irons	V;IND;PL;1;FUT;LGSPEC1
reigler	reigle	V;IND;SG;1;PRS
coniurer	coniuroys	V;IPFV;IND;SG;2;PST;LGSPEC2
practicquer	practicqueryez	V;COND;PL;2;LGSPEC2
delaisser	delaissasse	V;IPFV;SBJV;SG;1;PST
mensongier	mensongeas	V;PFV;IND;SG;2;PST
reigler	reigleront	V;IND;PL;3;FUT
achever	achevassent	V;IPFV;SBJV;PL;3;PST
bancqueter	bancquete	V;IMP;SG;2
haittier	haittyons	V;IPFV;IND;PL;1;PST;LGSPEC2
cacher	cacheroyent	V;COND;PL;3;LGSPEC2
uriner	urinoys	V;IPFV;IND;SG;1;PST;LGSPEC2
abhorrer	abhorroyt	V;IPFV;IND;SG;3;PST;LGSPEC2
entrer	entrasses	V;IPFV;SBJV;SG;2;PST
resider	resideriez	V;COND;PL;2;LGSPEC1
soupper	soupperoient	V;COND;PL;3;LGSPEC1
mortifier	mortifierai	V;IND;SG;1;FUT;LGSPEC1
tournoyer	tournoyeroient	V;COND;PL;3;LGSPEC1
acoustrer	acoustrons	V;SBJV;PL;1;PRS
courrouchier	courrouchierez	V;IND;PL;2;FUT
soupper	soupperois	V;COND;SG;2;LGSPEC1
mesler	meslasse	V;IPFV;SBJV;SG;1;PST
baster	basterois	V;COND;SG;1;LGSPEC1
esperer	espereryons	V;COND;PL;1;LGSPEC2
mesler	mesle	V;IND;SG;3;PRS
transporter	transporteryons	V;COND;PL;1;LGSPEC2
inquieter	inquieteriez	V;COND;PL;2;LGSPEC1
conseiller	conseilla	V;PFV;IND;SG;3;PST
aller	allois	V;IPFV;IND;SG;2;PST
oster	ostera	V;IND;SG;3;FUT
parler	parlois	V;IPFV;IND;SG;1;PST;LGSPEC1
esperer	espererois	V;COND;SG;1;LGSPEC1
desrisier	desrisierois	V;COND;SG;1;LGSPEC1
jecter	jecterez	V;IND;PL;2;FUT
prosperer	prospera	V;PFV;IND;SG;3;PST
preparer	prepareray	V;IND;SG;1;FUT;LGSPEC2
recommander	recommanderoyent	V;COND;PL;3;LGSPEC2
appeller	appelles	V;IND;SG;2;PRS
deschirer	deschire	V;IMP;SG;2
aler	vont	V;IND;PL;3;PRS
lever	leve	V;IMP;SG;2
porter	porte	V;SBJV;SG;1;PRS
flechir	fleschis	V;PFV;IND;SG;1;PST
fumer	fumeras	V;IND;SG;2;FUT
deschirer	deschireriez	V;COND;PL;2;LGSPEC1
oster	ostons	V;SBJV;PL;1;PRS
renouveller	renouvellasmes	V;PFV;IND;PL;1;PST
entrefrapper	vous entrefrappez	V;SBJV;PL;2;PRS
poiser	poisoys	V;IPFV;IND;SG;2;PST;LGSPEC2
proclamer	proclamoys	V;IPFV;IND;SG;1;PST;LGSPEC2
tournoyer	tournoyerai	V;IND;SG;1;FUT;LGSPEC1
proclamer	proclamois	V;IPFV;IND;SG;1;PST;LGSPEC1
mocquer	mocquyez	V;IPFV;IND;PL;2;PST;LGSPEC2
espargner	espargneriez	V;COND;PL;2;LGSPEC1
despossesser	despossessez	V;IMP;PL;2
courrouchier	courrouchierois	V;COND;SG;1;LGSPEC1
deschirer	deschireroit	V;COND;SG;3;LGSPEC1
practicquer	practicqueroyent	V;COND;PL;3;LGSPEC2
coniurer	coniure	V;SBJV;SG;3;PRS
subiuguier	subiuguast	V;IPFV;SBJV;SG;3;PST
rejecter	rejectoient	V;IPFV;IND;PL;3;PST;LGSPEC1
merveiller	merveilleront	V;IND;PL;3;FUT
transporter	transportent	V;SBJV;PL;3;PRS
esperonner	esperonneras	V;IND;SG;2;FUT
desrobber	desrobberai	V;IND;SG;1;FUT;LGSPEC1
entrer	entrerai	V;IND;SG;1;FUT;LGSPEC1
poiser	poisent	V;IND;PL;3;PRS
preparer	prepareroient	V;COND;PL;3;LGSPEC1
employer	employeroys	V;COND;SG;1;LGSPEC2
delivrer	delivroys	V;IPFV;IND;SG;2;PST;LGSPEC2
debaracer	debaracent	V;SBJV;PL;3;PRS
cacher	cacherois	V;COND;SG;2;LGSPEC1
recommander	recommandes	V;SBJV;SG;2;PRS
empirer	empirions	V;IPFV;IND;PL;1;PST;LGSPEC1
entrencontrer	vous entrencontrez	V;SBJV;PL;2;PRS
exposer	exposa	V;PFV;IND;SG;1;PST
saulver	saulvyez	V;IPFV;IND;PL;2;PST;LGSPEC2
deschirer	deschirez	V;IND;PL;2;PRS
desmeler	desmelois	V;IPFV;IND;SG;1;PST;LGSPEC1
desrisier	desrisassions	V;IPFV;SBJV;PL;1;PST
r'asseurer	r'asseures	V;IND;SG;2;PRS
entrehurter	entrehurtez vous	V;IMP;PL;2
bobeliner	bobelines	V;IND;SG;2;PRS
desrisier	desrisieroient	V;COND;PL;3;LGSPEC1
parler	parlent	V;IND;PL;3;PRS
aller	allasmes	V;PFV;IND;PL;1;PST
merveiller	merveillassent	V;IPFV;SBJV;PL;3;PST
iniurier	iniurioit	V;IPFV;IND;SG;3;PST;LGSPEC1
iniurier	iniuriassiez	V;IPFV;SBJV;PL;2;PST
rejecter	rejecta	V;PFV;IND;SG;3;PST
acoustrer	acoustre	V;SBJV;SG;3;PRS
encommencer	encommençons	V;IND;PL;1;PRS
delivrer	delivreras	V;IND;SG;2;FUT
prosperer	prospereray	V;IND;SG;1;FUT;LGSPEC2
celebrer	celebrons	V;IND;PL;1;PRS
delivrer	delivrerois	V;COND;SG;2;LGSPEC1
jecter	jecteroys	V;COND;SG;1;LGSPEC2
desplacer	desplaçassent	V;IPFV;SBJV;PL;3;PST
soupper	souppez	V;IND;PL;2;PRS
contribuer	contribuerois	V;COND;SG;2;LGSPEC1
racointer	racointyons	V;IPFV;IND;PL;1;PST;LGSPEC2
bobeliner	bobelinast	V;IPFV;SBJV;SG;3;PST
detranchier	detranchieroyent	V;COND;PL;3;LGSPEC2
descourager	descourageroient	V;COND;PL;3;LGSPEC1
ordonner	ordonnoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
delivrer	delivreroit	V;COND;SG;3;LGSPEC1
despossesser	despossesseryez	V;COND;PL;2;LGSPEC2
lescher	leschasses	V;IPFV;SBJV;SG;2;PST
entrefrapper	vous entrefrapperez	V;IND;PL;2;FUT
delaisser	delaisses	V;SBJV;SG;2;PRS
finir	finissoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
desplacer	desplaces	V;SBJV;SG;2;PRS
occuper	occuperez	V;IND;PL;2;FUT
desconseiller	desconseillerois	V;COND;SG;1;LGSPEC1
gaigner	gaigne	V;IMP;SG;2
guerpir	guerpiroient	V;COND;PL;3;LGSPEC1
parler	parlons	V;IMP;PL;1
eschever	eschevas	V;PFV;IND;SG;2;PST
flechir	fleschismes	V;PFV;IND;PL;1;PST
tomber	tombiez	V;IPFV;IND;PL;2;PST;LGSPEC1
minorer	minoroit	V;IPFV;IND;SG;3;PST;LGSPEC1
apatir	apatist	V;IPFV;SBJV;SG;3;PST
houssepillier	houssepille	V;IMP;SG;2
rouiller	rouillez	V;IMP;PL;2
coniurer	coniurasse	V;IPFV;SBJV;SG;1;PST
quiter	quita	V;PFV;IND;SG;3;PST
gaigner	gaignoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
desancrer	desancrerions	V;COND;PL;1;LGSPEC1
baster	bastois	V;IPFV;IND;SG;2;PST;LGSPEC1
aguyser	aguysiez	V;IPFV;IND;PL;2;PST;LGSPEC1
proclamer	proclama	V;PFV;IND;SG;1;PST
guerpir	guerpissois	V;IPFV;IND;SG;2;PST;LGSPEC1
arrester	arresta	V;PFV;IND;SG;1;PST
desplacer	desplaçons	V;IMP;PL;1
iniurier	iniuriois	V;IPFV;IND;SG;1;PST;LGSPEC1
sembler	sembleront	V;IND;PL;3;FUT
espouser	espousyons	V;IPFV;IND;PL;1;PST;LGSPEC2
quiter	quite	V;IND;SG;3;PRS
cercher	cerchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
saulter	saultasse	V;IPFV;SBJV;SG;1;PST
descourager	descourageast	V;IPFV;SBJV;SG;3;PST
espouser	espousoys	V;IPFV;IND;SG;1;PST;LGSPEC2
lever	leva	V;PFV;IND;SG;1;PST
baster	bastiez	V;IPFV;IND;PL;2;PST;LGSPEC1
mectre	mectroyt	V;COND;SG;3;LGSPEC2
sembler	sembloient	V;IPFV;IND;PL;3;PST;LGSPEC1
eschever	eschevast	V;IPFV;SBJV;SG;3;PST
tyrer	tyreroyent	V;COND;PL;3;LGSPEC2
entrehurter	entrehurtyez	V;IPFV;IND;PL;2;PST;LGSPEC2
exposer	exposasmes	V;PFV;IND;PL;1;PST
dancer	danceroys	V;COND;SG;1;LGSPEC2
eschever	escheveryez	V;COND;PL;2;LGSPEC2
tyrer	tyreray	V;IND;SG;1;FUT;LGSPEC2
espouser	espouse	V;IND;SG;1;PRS
cercher	cerchoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
raporter	raportoient	V;IPFV;IND;PL;3;PST;LGSPEC1
mocquer	mocquoys	V;IPFV;IND;SG;2;PST;LGSPEC2
empirer	empireroys	V;COND;SG;1;LGSPEC2
esveiller	esveillerons	V;IND;PL;1;FUT
aller	yroie	V;IND;SG;1;FUT;LGSPEC2
rejecter	rejecteront	V;IND;PL;3;FUT
conseiller	conseillez	V;SBJV;PL;2;PRS
toquer	toquer	V;NFIN
gaster	gasteroit	V;COND;SG;3;LGSPEC1
empirer	empireryons	V;COND;PL;1;LGSPEC2
rouiller	rouilloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
chocquer	chocquent	V;IND;PL;3;PRS
mensongier	mensongent	V;IND;PL;3;PRS
ordonner	ordonnassions	V;IPFV;SBJV;PL;1;PST
acoustumer	acoustume	V;IND;SG;1;PRS
humilier	humiliyez	V;IPFV;IND;PL;2;PST;LGSPEC2
esperer	esperer	V;NFIN
delaisser	delaissoys	V;IPFV;IND;SG;2;PST;LGSPEC2
arrester	arrestoit	V;IPFV;IND;SG;3;PST;LGSPEC1
rouiller	rouille	V;IND;SG;3;PRS
mortifier	mortifieroyent	V;COND;PL;3;LGSPEC2
creancer	creanceroyent	V;COND;PL;3;LGSPEC2
reietter	reiettasse	V;IPFV;SBJV;SG;1;PST
soupper	souppera	V;IND;SG;3;FUT
coniurer	coniureroient	V;COND;PL;3;LGSPEC1
couster	coustois	V;IPFV;IND;SG;1;PST;LGSPEC1
entrer	entrerois	V;COND;SG;1;LGSPEC1
aller	yroient	V;COND;PL;3;LGSPEC2
deschirer	deschireray	V;IND;SG;1;FUT;LGSPEC2
emerger	emergions	V;IPFV;IND;PL;1;PST;LGSPEC1
tournoyer	tournoyeriez	V;COND;PL;2;LGSPEC1
fumer	fumes	V;SBJV;SG;2;PRS
emerger	emergeroit	V;COND;SG;3;LGSPEC1
piller	pilloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
achever	achevons	V;SBJV;PL;1;PRS
debaracer	debaraceroyt	V;COND;SG;3;LGSPEC2
saulter	saulterons	V;IND;PL;1;FUT
debaracer	debaraçons	V;IPFV;IND;PL;1;PST;LGSPEC2
r'asseurer	r'asseurerez	V;IND;PL;2;FUT
descourager	descouragerions	V;COND;PL;1;LGSPEC1
flechir	fleschirois	V;COND;SG;2;LGSPEC1
uriner	urines	V;IND;SG;2;PRS
uriner	urinez	V;IMP;PL;2
cacher	cacherent	V;PFV;IND;PL;3;PST
approuvender	approuvenderont	V;IND;PL;3;FUT
poiser	poisoit	V;IPFV;IND;SG;3;PST;LGSPEC1
gaster	gaste	V;IMP;SG;2
entrencontrer	nous entrencontrassions	V;IPFV;SBJV;PL;1;PST
guerpir	guerpisse	V;SBJV;SG;3;PRS
visiter	visitois	V;IPFV;IND;SG;1;PST;LGSPEC1
approuvender	approuvenderoys	V;COND;SG;2;LGSPEC2
rouiller	rouillerons	V;IND;PL;1;FUT
mortifier	mortifies	V;SBJV;SG;2;PRS
visiter	visitions	V;IPFV;IND;PL;1;PST;LGSPEC1
desregler	desregleriez	V;COND;PL;2;LGSPEC1
reigler	reiglent	V;IND;PL;3;PRS
effreer	effreeriez	V;COND;PL;2;LGSPEC1
enferrer	enferrasmes	V;PFV;IND;PL;1;PST
courrouchier	courrouchieryons	V;COND;PL;1;LGSPEC2
arrester	arresteray	V;IND;SG;1;FUT;LGSPEC2
occuper	occuperai	V;IND;SG;1;FUT;LGSPEC1
bobeliner	bobelinons	V;IMP;PL;1
oster	osteront	V;IND;PL;3;FUT
enchargier	enchargieroyt	V;COND;SG;3;LGSPEC2
practicquer	practicquois	V;IPFV;IND;SG;1;PST;LGSPEC1
dancer	danceroys	V;COND;SG;2;LGSPEC2
desyrer	desyreryez	V;COND;PL;2;LGSPEC2
empirer	empirerons	V;IND;PL;1;FUT
occuper	occupent	V;IND;PL;3;PRS
tyrer	tyre	V;IND;SG;3;PRS
representer	representeryons	V;COND;PL;1;LGSPEC2
courrouchier	courrouchoient	V;IPFV;IND;PL;3;PST;LGSPEC1
saulver	saulvoient	V;IPFV;IND;PL;3;PST;LGSPEC1
gaster	gastiez	V;IPFV;IND;PL;2;PST;LGSPEC1
apuyer	apuyois	V;IPFV;IND;SG;1;PST;LGSPEC1
appeller	appelleroyt	V;COND;SG;3;LGSPEC2
desrobber	desrobberont	V;IND;PL;3;FUT
esveiller	esveillez	V;IND;PL;2;PRS
quiter	quites	V;IND;SG;2;PRS
nommer	nommerois	V;COND;SG;2;LGSPEC1
apatir	apatissent	V;IND;PL;3;PRS
destabler	destabloyent	V;IPFV;IND;PL;3;PST;LGSPEC2
ordonner	ordonniez	V;IPFV;IND;PL;2;PST;LGSPEC1
haittier	haitta	V;PFV;IND;SG;1;PST
entrehurter	vous entrehurtassiez	V;IPFV;SBJV;PL;2;PST
acoustumer	acoustumeroient	V;COND;PL;3;LGSPEC1
raporter	raportoys	V;IPFV;IND;SG;1;PST;LGSPEC2
aboscher	aboscherois	V;COND;SG;1;LGSPEC1
mensongier	mensongea	V;PFV;IND;SG;1;PST
prosperer	prospere	V;IMP;SG;2
piller	pilloient	V;IPFV;IND;PL;3;PST;LGSPEC1
deschirer	deschirassent	V;IPFV;SBJV;PL;3;PST
renouveller	renouvella	V;PFV;IND;SG;1;PST
renommer	renommeroient	V;COND;PL;3;LGSPEC1
faucer	fauces	V;SBJV;SG;2;PRS
aguyser	aguysions	V;IPFV;IND;PL;1;PST;LGSPEC1
acoustrer	acoustres	V;IND;SG;2;PRS
achever	achevoit	V;IPFV;IND;SG;3;PST;LGSPEC1
parler	parleras	V;IND;SG;2;FUT
contribuer	contribuoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
aerer	aereront	V;IND;PL;3;FUT
regarder	regardons	V;IND;PL;1;PRS
esveiller	esveillera	V;IND;SG;3;FUT
toquer	toquoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
occuper	occuperoyent	V;COND;PL;3;LGSPEC2
apatir	apatirions	V;COND;PL;1
despossesser	despossessera	V;IND;SG;3;FUT
despossesser	despossessassions	V;IPFV;SBJV;PL;1;PST
descourager	descourageroyent	V;COND;PL;3;LGSPEC2
repraesenter	repraesentez	V;IMP;PL;2
haster	hastasses	V;IPFV;SBJV;SG;2;PST
aller	yront	V;IND;PL;3;FUT;LGSPEC2
emerger	emergeroyent	V;COND;PL;3;LGSPEC2
ayder	aydons	V;SBJV;PL;1;PRS
esperer	espereriez	V;COND;PL;2;LGSPEC1
coniurer	coniurassent	V;IPFV;SBJV;PL;3;PST
emerger	emerge	V;SBJV;SG;1;PRS
piller	pilleroyt	V;COND;SG;3;LGSPEC2
esveiller	esveilloient	V;IPFV;IND;PL;3;PST;LGSPEC1
guerpir	guerpiroyent	V;COND;PL;3;LGSPEC2
faucer	fauce	V;SBJV;SG;3;PRS
renger	rengeryez	V;COND;PL;2;LGSPEC2
macter	macteryez	V;COND;PL;2;LGSPEC2
entrer	entreryons	V;COND;PL;1;LGSPEC2
r'asseurer	r'asseureray	V;IND;SG;1;FUT;LGSPEC2
espargner	espargnerions	V;COND;PL;1;LGSPEC1
baster	bastoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
courrouchier	courrouchieroys	V;COND;SG;2;LGSPEC2
tournoyer	tournoyerez	V;IND;PL;2;FUT
dancer	danceroit	V;COND;SG;3;LGSPEC1
fumer	fument	V;SBJV;PL;3;PRS
resider	resider	V;NFIN
infourmer	infourmeroyent	V;COND;PL;3;LGSPEC2
racointer	racointoys	V;IPFV;IND;SG;1;PST;LGSPEC2
detranchier	detranchyons	V;IPFV;IND;PL;1;PST;LGSPEC2
porter	porteras	V;IND;SG;2;FUT
contribuer	contribuyez	V;IPFV;IND;PL;2;PST;LGSPEC2
renommer	renommes	V;SBJV;SG;2;PRS
enchargier	enchargeassiez	V;IPFV;SBJV;PL;2;PST
desyrer	desyre	V;IMP;SG;2
effreer	effreerai	V;IND;SG;1;FUT;LGSPEC1
iniurier	iniurieryez	V;COND;PL;2;LGSPEC2
arrester	arrestons	V;IMP;PL;1
quiter	quitons	V;IMP;PL;1
repraesenter	repraesenteront	V;IND;PL;3;FUT
saulter	saulteroyent	V;COND;PL;3;LGSPEC2
humilier	humilioyent	V;IPFV;IND;PL;3;PST;LGSPEC2
huer	huassions	V;IPFV;SBJV;PL;1;PST
rejecter	rejectasses	V;IPFV;SBJV;SG;2;PST
celebrer	celebre	V;SBJV;SG;1;PRS
rouiller	rouilleroys	V;COND;SG;2;LGSPEC2
haster	hasterois	V;COND;SG;2;LGSPEC1
mesler	mesleroys	V;COND;SG;2;LGSPEC2
entrer	entryez	V;IPFV;IND;PL;2;PST;LGSPEC2
bancqueter	bancqueteront	V;IND;PL;3;FUT
payer	payons	V;IND;PL;1;PRS
denunchier	denunchiyez	V;IPFV;IND;PL;2;PST;LGSPEC2
iniurier	iniuriasses	V;IPFV;SBJV;SG;2;PST
humilier	humilierai	V;IND;SG;1;FUT;LGSPEC1
sembler	sembleroys	V;COND;SG;1;LGSPEC2
desrober	desrobe	V;IND;SG;3;PRS
esveiller	esveiller	V;NFIN
creancer	creancerois	V;COND;SG;2;LGSPEC1
practicquer	practicquasses	V;IPFV;SBJV;SG;2;PST
piller	pilleray	V;IND;SG;1;FUT;LGSPEC2
eschever	escheveriez	V;COND;PL;2;LGSPEC1
entrencontrer	s'entrencontrent	V;IND;PL;3;PRS
houssepillier	houssepille	V;IND;SG;3;PRS
raporter	raporteray	V;IND;SG;1;FUT;LGSPEC2
enferrer	enferreroyent	V;COND;PL;3;LGSPEC2
entrencontrer	vousentrencontreriez	V;COND;PL;2;LGSPEC1
visiter	visitast	V;IPFV;SBJV;SG;3;PST
effreer	effreasses	V;IPFV;SBJV;SG;2;PST
arrester	arrestez	V;IND;PL;2;PRS
detranchier	detranchois	V;IPFV;IND;SG;2;PST;LGSPEC1
deschirer	deschirerions	V;COND;PL;1;LGSPEC1
esperer	espereroyt	V;COND;SG;3;LGSPEC2
poiser	poiserois	V;COND;SG;1;LGSPEC1
iniurier	iniuriois	V;IPFV;IND;SG;2;PST;LGSPEC1
destabler	destableryons	V;COND;PL;1;LGSPEC2
appeller	appelleroys	V;COND;SG;1;LGSPEC2
rouiller	rouillons	V;IND;PL;1;PRS
preparer	prepareroyt	V;COND;SG;3;LGSPEC2
aguyser	aguyseroit	V;COND;SG;3;LGSPEC1
cercher	cerches	V;IND;SG;2;PRS
inquieter	inquieta	V;PFV;IND;SG;3;PST
minorer	minorerois	V;COND;SG;1;LGSPEC1
humilier	humilieroient	V;COND;PL;3;LGSPEC1
tyrer	tyre	V;IMP;SG;2
baster	bastes	V;SBJV;SG;2;PRS
rejecter	rejectoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
eschever	eschevyez	V;IPFV;IND;PL;2;PST;LGSPEC2
enferrer	enferroys	V;IPFV;IND;SG;1;PST;LGSPEC2
aguyser	aguyseroys	V;COND;SG;1;LGSPEC2
courrouchier	courrouchiera	V;IND;SG;3;FUT
soulaiger	soulaigions	V;IPFV;IND;PL;1;PST;LGSPEC1
preparer	preparons	V;SBJV;PL;1;PRS
entrehurter	nous entrehurtons	V;IND;PL;1;PRS
desmeler	desmelez	V;SBJV;PL;2;PRS
bobeliner	bobelines	V;SBJV;SG;2;PRS
desieuner	desieunent	V;SBJV;PL;3;PRS
bobeliner	bobelineriez	V;COND;PL;2;LGSPEC1
emerger	emergeryez	V;COND;PL;2;LGSPEC2
empirer	empireriez	V;COND;PL;2;LGSPEC1
ordonner	ordonnez	V;IND;PL;2;PRS
chocquer	chocqueroyt	V;COND;SG;3;LGSPEC2
coniurer	coniureroit	V;COND;SG;3;LGSPEC1
poiser	poisoient	V;IPFV;IND;PL;3;PST;LGSPEC1
poiser	poisera	V;IND;SG;3;FUT
entrehurter	entrehurteroyent	V;COND;PL;3;LGSPEC2
escapper	escapperyons	V;COND;PL;1;LGSPEC2
mectre	mectras	V;IND;SG;2;FUT
occuper	occuperoyt	V;COND;SG;3;LGSPEC2
considerer	considereras	V;IND;SG;2;FUT
approuvender	approuvendoient	V;IPFV;IND;PL;3;PST;LGSPEC1
espouser	espousas	V;PFV;IND;SG;2;PST
desrober	desrober	V;NFIN
cacher	cachasse	V;IPFV;SBJV;SG;1;PST
gaigner	gaignoys	V;IPFV;IND;SG;2;PST;LGSPEC2
fluir	fluissoys	V;IPFV;IND;SG;1;PST;LGSPEC2
renger	rengent	V;IND;PL;3;PRS
courrouchier	courrouchoys	V;IPFV;IND;SG;2;PST;LGSPEC2
porter	portois	V;IPFV;IND;SG;2;PST;LGSPEC1
delaisser	delaisse	V;IMP;SG;2
baster	bastyez	V;IPFV;IND;PL;2;PST;LGSPEC2
resider	residez	V;SBJV;PL;2;PRS
mensongier	mensongyez	V;IPFV;IND;PL;2;PST;LGSPEC2
aorner	aorne	V;IND;SG;3;PRS
meriter	meritasses	V;IPFV;SBJV;SG;2;PST
jecter	jectez	V;SBJV;PL;2;PRS
minorer	minorerois	V;COND;SG;2;LGSPEC1
apatir	apatissiez	V;SBJV;PL;2;PRS
rejecter	rejectoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
aboscher	aboscherons	V;IND;PL;1;FUT
minorer	minore	V;SBJV;SG;1;PRS
renger	rengeassent	V;IPFV;SBJV;PL;3;PST
arrester	arrestent	V;IND;PL;3;PRS
ayder	ayderoys	V;COND;SG;2;LGSPEC2
saulter	saultes	V;IND;SG;2;PRS
gaster	gastyons	V;IPFV;IND;PL;1;PST;LGSPEC2
raporter	raporteriez	V;COND;PL;2;LGSPEC1
accoustumer	accoustumes	V;SBJV;SG;2;PRS
contribuer	contribuasses	V;IPFV;SBJV;SG;2;PST
visiter	visitasses	V;IPFV;SBJV;SG;2;PST
regarder	regarde	V;IMP;SG;2
desrober	desroberons	V;IND;PL;1;FUT
denunchier	denunchieroys	V;COND;SG;2;LGSPEC2
quiter	quiterois	V;COND;SG;2;LGSPEC1
ayder	ayderai	V;IND;SG;1;FUT;LGSPEC1
regratier	regratieroient	V;COND;PL;3;LGSPEC1
esplucher	espluches	V;SBJV;SG;2;PRS
iniurier	iniurie	V;IND;SG;1;PRS
oster	osteray	V;IND;SG;1;FUT;LGSPEC2
coniurer	coniure	V;SBJV;SG;1;PRS
tomber	tomberoyt	V;COND;SG;3;LGSPEC2
meriter	meritent	V;SBJV;PL;3;PRS
aboscher	aboschasses	V;IPFV;SBJV;SG;2;PST
renouveller	renouvellent	V;SBJV;PL;3;PRS
creancer	creançassiez	V;IPFV;SBJV;PL;2;PST
bancqueter	bancquetons	V;IMP;PL;1
reietter	reietteront	V;IND;PL;3;FUT
denunchier	denunchient	V;IND;PL;3;PRS
effreer	effreoys	V;IPFV;IND;SG;2;PST;LGSPEC2
desancrer	desancre	V;SBJV;SG;3;PRS
nommer	nommoys	V;IPFV;IND;SG;1;PST;LGSPEC2
considerer	consideryons	V;IPFV;IND;PL;1;PST;LGSPEC2
debaracer	debaracer	V;NFIN
soulaiger	soulaigerois	V;COND;SG;1;LGSPEC1
rouiller	rouilleroit	V;COND;SG;3;LGSPEC1
oster	ostassions	V;IPFV;SBJV;PL;1;PST
flechir	fleschissent	V;SBJV;PL;3;PRS
lescher	lesche	V;SBJV;SG;1;PRS
macter	mactez	V;SBJV;PL;2;PRS
deschirer	deschirerent	V;PFV;IND;PL;3;PST
aorner	aorniez	V;IPFV;IND;PL;2;PST;LGSPEC1
parler	parlois	V;IPFV;IND;SG;2;PST;LGSPEC1
subiuguier	subiuguierez	V;IND;PL;2;FUT
ruyner	ruyneryez	V;COND;PL;2;LGSPEC2
travailler	travaillassiez	V;IPFV;SBJV;PL;2;PST
arrester	arrestasmes	V;PFV;IND;PL;1;PST
travailler	travaillerez	V;IND;PL;2;FUT
apuyer	apuyasse	V;IPFV;SBJV;SG;1;PST
tomber	tomberiez	V;COND;PL;2;LGSPEC1
tournoyer	tournoyez	V;IND;PL;2;PRS
mectre	mectez	V;IND;PL;2;PRS
courrouchier	courrouchoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
accoustumer	accoustumons	V;IMP;PL;1
entrefrapper	entrefrappyez	V;IPFV;IND;PL;2;PST;LGSPEC2
infourmer	infourment	V;IND;PL;3;PRS
recommander	recommanderons	V;IND;PL;1;FUT
entrefrapper	vous entrefrappastes	V;PFV;IND;PL;2;PST
despossesser	despossessons	V;IND;PL;1;PRS
lescher	lescheryez	V;COND;PL;2;LGSPEC2
enferrer	enferreriez	V;COND;PL;2;LGSPEC1
lever	levent	V;IND;PL;3;PRS
nommer	nommoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
aler	alast	V;IPFV;SBJV;SG;3;PST
fluir	fluissions	V;IPFV;SBJV;PL;1;PST
occuper	occuperay	V;IND;SG;1;FUT;LGSPEC2
despossesser	despossesser	V;NFIN
aerer	aerast	V;IPFV;SBJV;SG;3;PST
transporter	transportoys	V;IPFV;IND;SG;1;PST;LGSPEC2
proclamer	proclamoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
bobeliner	bobelineront	V;IND;PL;3;FUT
guerpir	guerpisse	V;IPFV;SBJV;SG;1;PST
repraesenter	repraesenteroys	V;COND;SG;1;LGSPEC2
preparer	preparasse	V;IPFV;SBJV;SG;1;PST
despossesser	despossessoit	V;IPFV;IND;SG;3;PST;LGSPEC1
aboscher	aboscheryez	V;COND;PL;2;LGSPEC2
creancer	creanceryez	V;COND;PL;2;LGSPEC2
infourmer	infourmast	V;IPFV;SBJV;SG;3;PST
deschirer	deschirons	V;IND;PL;1;PRS
merveiller	merveilleroyt	V;COND;SG;3;LGSPEC2
ordonner	ordonnoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
houssepillier	houssepillieras	V;IND;SG;2;FUT
accoustumer	accoustumoient	V;IPFV;IND;PL;3;PST;LGSPEC1
soulaiger	soulaigeons	V;SBJV;PL;1;PRS
considerer	considereroit	V;COND;SG;3;LGSPEC1
soupper	soupperyons	V;COND;PL;1;LGSPEC2
contribuer	contribuyons	V;IPFV;IND;PL;1;PST;LGSPEC2
finir	finis	V;IND;SG;1;PRS
sembler	sembleroyent	V;COND;PL;3;LGSPEC2
employer	employassent	V;IPFV;SBJV;PL;3;PST
cuyder	cuyda	V;PFV;IND;SG;1;PST
oster	ostoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
praesenter	praesente	V;SBJV;SG;3;PRS
cercher	cercha	V;PFV;IND;SG;3;PST
preparer	preparois	V;IPFV;IND;SG;1;PST;LGSPEC1
arrester	arrester	V;NFIN
creancer	creancent	V;IND;PL;3;PRS
raporter	raportyez	V;IPFV;IND;PL;2;PST;LGSPEC2
huer	huoient	V;IPFV;IND;PL;3;PST;LGSPEC1
aboscher	aboscherions	V;COND;PL;1;LGSPEC1
poiser	poiserions	V;COND;PL;1;LGSPEC1
prosperer	prosperons	V;IMP;PL;1
entrer	entrez	V;SBJV;PL;2;PRS
mesler	meslois	V;IPFV;IND;SG;2;PST;LGSPEC1
transporter	transporterons	V;IND;PL;1;FUT
accoustumer	accoustumois	V;IPFV;IND;SG;1;PST;LGSPEC1
baster	bastez	V;IMP;PL;2
representer	representassent	V;IPFV;SBJV;PL;3;PST
aguyser	aguyseront	V;IND;PL;3;FUT
celebrer	celebrerai	V;IND;SG;1;FUT;LGSPEC1
saulver	saulveriez	V;COND;PL;2;LGSPEC1
nommer	nommiez	V;IPFV;IND;PL;2;PST;LGSPEC1
macter	mactasmes	V;PFV;IND;PL;1;PST
iniurier	iniuriez	V;IMP;PL;2
conseiller	conseilleryez	V;COND;PL;2;LGSPEC2
emerger	emergyons	V;IPFV;IND;PL;1;PST;LGSPEC2
desrobber	desrobboys	V;IPFV;IND;SG;2;PST;LGSPEC2
macter	mactera	V;IND;SG;3;FUT
huer	hueroient	V;COND;PL;3;LGSPEC1
mensongier	mensongeastes	V;PFV;IND;PL;2;PST
merveiller	merveillions	V;IPFV;IND;PL;1;PST;LGSPEC1
effreer	effreeroys	V;COND;SG;1;LGSPEC2
traitter	traitteroys	V;COND;SG;1;LGSPEC2
dancer	dançassiez	V;IPFV;SBJV;PL;2;PST
uriner	urinyez	V;IPFV;IND;PL;2;PST;LGSPEC2
entrer	entrent	V;SBJV;PL;3;PRS
enferrer	enferrez	V;SBJV;PL;2;PRS
mensongier	mensongeassiez	V;IPFV;SBJV;PL;2;PST
gaster	gaste	V;SBJV;SG;3;PRS
deschirer	deschiriez	V;IPFV;IND;PL;2;PST;LGSPEC1
desrisier	desrises	V;SBJV;SG;2;PRS
raporter	raportez	V;IND;PL;2;PRS
deslyer	deslyerent	V;PFV;IND;PL;3;PST
bancqueter	bancquetez	V;SBJV;PL;2;PRS
cercher	cercheroys	V;COND;SG;2;LGSPEC2
mectre	mections	V;IPFV;IND;PL;1;PST
saulver	saulverez	V;IND;PL;2;FUT
desyrer	desyrastes	V;PFV;IND;PL;2;PST
couster	cousteroyt	V;COND;SG;3;LGSPEC2
ordonner	ordonne	V;IMP;SG;2
considerer	considere	V;IND;SG;1;PRS
aler	irions	V;COND;PL;1;LGSPEC1
encommencer	encommença	V;PFV;IND;SG;1;PST
regratier	regratiassent	V;IPFV;SBJV;PL;3;PST
payer	payasse	V;IPFV;SBJV;SG;1;PST
representer	representerions	V;COND;PL;1;LGSPEC1
denunchier	denunchies	V;SBJV;SG;2;PRS
desborder	desbordyons	V;IPFV;IND;PL;1;PST;LGSPEC2
abhorrer	abhorreryons	V;COND;PL;1;LGSPEC2
deslyer	deslyons	V;SBJV;PL;1;PRS
aorner	aornyez	V;IPFV;IND;PL;2;PST;LGSPEC2
couster	coustoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
renommer	renomme	V;IND;SG;1;PRS
deschirer	deschire	V;IND;SG;1;PRS
racointer	racointast	V;IPFV;SBJV;SG;3;PST
minorer	minorasse	V;IPFV;SBJV;SG;1;PST
desmeler	desmelassions	V;IPFV;SBJV;PL;1;PST
ayder	aydassent	V;IPFV;SBJV;PL;3;PST
mocquer	mocqueray	V;IND;SG;1;FUT;LGSPEC2
aerer	aera	V;PFV;IND;SG;1;PST
rouiller	rouillassiez	V;IPFV;SBJV;PL;2;PST
detranchier	detranchas	V;PFV;IND;SG;2;PST
escapper	escapperai	V;IND;SG;1;FUT;LGSPEC1
deslyer	deslyeroyt	V;COND;SG;3;LGSPEC2
ordonner	ordonnons	V;IMP;PL;1
mectre	mectroys	V;COND;SG;1;LGSPEC2
subiuguier	subiuguiez	V;IPFV;IND;PL;2;PST;LGSPEC1
desborder	desborda	V;PFV;IND;SG;1;PST
aorner	aorneras	V;IND;SG;2;FUT
aboscher	aboscherois	V;COND;SG;2;LGSPEC1
emerger	emergeroient	V;COND;PL;3;LGSPEC1
fluir	fluira	V;IND;SG;3;FUT
soulaiger	soulaigyez	V;IPFV;IND;PL;2;PST;LGSPEC2
subiuguier	subiuguyons	V;IPFV;IND;PL;1;PST;LGSPEC2
jecter	jecteriez	V;COND;PL;2;LGSPEC1
destourner	destournerois	V;COND;SG;2;LGSPEC1
destabler	destablassent	V;IPFV;SBJV;PL;3;PST
traitter	traittions	V;IPFV;IND;PL;1;PST;LGSPEC1
apuyer	apuyoys	V;IPFV;IND;SG;2;PST;LGSPEC2
bobeliner	bobeline	V;SBJV;SG;3;PRS
desmeler	desmelerons	V;IND;PL;1;FUT
adviser	advisoys	V;IPFV;IND;SG;2;PST;LGSPEC2
apuyer	apuyerent	V;PFV;IND;PL;3;PST
desrisier	desrise	V;IND;SG;1;PRS
aboscher	aboschasse	V;IPFV;SBJV;SG;1;PST
detranchier	detranchiez	V;SBJV;PL;2;PRS
ayder	ayderiez	V;COND;PL;2;LGSPEC1
jecter	jectera	V;IND;SG;3;FUT
conseiller	conseilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
effreer	effreoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
espouser	espouserions	V;COND;PL;1;LGSPEC1
employer	employeryons	V;COND;PL;1;LGSPEC2
regratier	regratie	V;IND;SG;3;PRS
soupper	souppe	V;IND;SG;1;PRS
acoustrer	acoustrera	V;IND;SG;3;FUT
entredemander	entredemandons nous	V;IMP;PL;1
repraesenter	repraesenterez	V;IND;PL;2;FUT
desregler	desregles	V;IND;SG;2;PRS
arrester	arrestastes	V;PFV;IND;PL;2;PST
desancrer	desancroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
merveiller	merveillas	V;PFV;IND;SG;2;PST
recommander	recommandois	V;IPFV;IND;SG;1;PST;LGSPEC1
celebrer	celebrois	V;IPFV;IND;SG;2;PST;LGSPEC1
aerer	aereroys	V;COND;SG;1;LGSPEC2
cercher	cercheront	V;IND;PL;3;FUT
visiter	visiterons	V;IND;PL;1;FUT
regarder	regardes	V;IND;SG;2;PRS
cercher	cercheroient	V;COND;PL;3;LGSPEC1
destourner	destournoient	V;IPFV;IND;PL;3;PST;LGSPEC1
finir	finissoient	V;IPFV;IND;PL;3;PST;LGSPEC1
delivrer	delivrons	V;IMP;PL;1
aller	aller	V;NFIN
debaracer	debaraçassent	V;IPFV;SBJV;PL;3;PST
meriter	meritasse	V;IPFV;SBJV;SG;1;PST
houssepillier	houssepillast	V;IPFV;SBJV;SG;3;PST
encommencer	encommencerent	V;PFV;IND;PL;3;PST
desmeler	desmelyez	V;IPFV;IND;PL;2;PST;LGSPEC2
mensongier	mensongieriez	V;COND;PL;2;LGSPEC1
reigler	reiglent	V;SBJV;PL;3;PRS
jecter	jecteryons	V;COND;PL;1;LGSPEC2
renger	renge	V;IND;SG;1;PRS
creancer	creançoys	V;IPFV;IND;SG;2;PST;LGSPEC2
practicquer	practicquez	V;SBJV;PL;2;PRS
porter	porteroient	V;COND;PL;3;LGSPEC1
regarder	regarderyez	V;COND;PL;2;LGSPEC2
haittier	haitte	V;IMP;SG;2
delaisser	delaissoit	V;IPFV;IND;SG;3;PST;LGSPEC1
aboscher	aboscheroyent	V;COND;PL;3;LGSPEC2
deslyer	deslyiez	V;IPFV;IND;PL;2;PST;LGSPEC1
visiter	visitois	V;IPFV;IND;SG;2;PST;LGSPEC1
aller	allois	V;IPFV;IND;SG;1;PST
nommer	nommerent	V;PFV;IND;PL;3;PST
desregler	desreglasse	V;IPFV;SBJV;SG;1;PST
descharger	deschargea	V;PFV;IND;SG;3;PST
esperer	espererai	V;IND;SG;1;FUT;LGSPEC1
fumer	fumerois	V;COND;SG;2;LGSPEC1
mensongier	mensongeasmes	V;PFV;IND;PL;1;PST
saulver	saulverois	V;COND;SG;2;LGSPEC1
apuyer	apuyeroyent	V;COND;PL;3;LGSPEC2
visiter	visitoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
chocquer	chocquons	V;SBJV;PL;1;PRS
debaracer	debaraceroit	V;COND;SG;3;LGSPEC1
exposer	exposer	V;NFIN
rejecter	rejecteroyent	V;COND;PL;3;LGSPEC2
adviser	advisoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
desmeler	desmele	V;SBJV;SG;1;PRS
descharger	deschargeons	V;IND;PL;1;PRS
aller	allasses	V;IPFV;SBJV;SG;2;PST
repraesenter	repraesenteroyent	V;COND;PL;3;LGSPEC2
flechir	fleschirent	V;PFV;IND;PL;3;PST
entrempescher	entrempescher	V;NFIN
rouiller	rouilleront	V;IND;PL;3;FUT
desieuner	desieunerois	V;COND;SG;1;LGSPEC1
nommer	nommes	V;IND;SG;2;PRS
recommander	recommandoit	V;IPFV;IND;SG;3;PST;LGSPEC1
porter	portasse	V;IPFV;SBJV;SG;1;PST
esveiller	esveillasmes	V;PFV;IND;PL;1;PST
resider	residoit	V;IPFV;IND;SG;3;PST;LGSPEC1
haster	hastassiez	V;IPFV;SBJV;PL;2;PST
entrefrapper	vousentrefrapperiez	V;COND;PL;2;LGSPEC1
debaracer	debaracions	V;IPFV;IND;PL;1;PST;LGSPEC1
achever	acheveroyent	V;COND;PL;3;LGSPEC2
considerer	considereroyent	V;COND;PL;3;LGSPEC2
cuyder	cuyderions	V;COND;PL;1;LGSPEC1
preparer	prepareroit	V;COND;SG;3;LGSPEC1
poiser	poisoys	V;IPFV;IND;SG;1;PST;LGSPEC2
adviser	advisez	V;IND;PL;2;PRS
recommander	recommandassiez	V;IPFV;SBJV;PL;2;PST
contribuer	contribuons	V;IMP;PL;1
desrobber	desrobba	V;PFV;IND;SG;1;PST
gaigner	gaignes	V;IND;SG;2;PRS
occuper	occupyons	V;IPFV;IND;PL;1;PST;LGSPEC2
meriter	merite	V;SBJV;SG;3;PRS
travailler	travailler	V;NFIN
creancer	creançons	V;SBJV;PL;1;PRS
travailler	travailleriez	V;COND;PL;2;LGSPEC1
delaisser	delaisse	V;SBJV;SG;1;PRS
effreer	effreez	V;SBJV;PL;2;PRS
baptiser	baptisassions	V;IPFV;SBJV;PL;1;PST
embler	emblons	V;IMP;PL;1
desirer	desirassions	V;IPFV;SBJV;PL;1;PST
iurer	iura	V;PFV;IND;SG;1;PST
desadvouer	desadvouasmes	V;PFV;IND;PL;1;PST
soumectre	soumectroys	V;COND;SG;2;LGSPEC2
executer	executastes	V;PFV;IND;PL;2;PST
desnouer	desnoua	V;PFV;IND;SG;1;PST
esmerveillier	esmerveillast	V;IPFV;SBJV;SG;3;PST
desbarater	desbaratez	V;IND;PL;2;PRS
menasser	menassoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
estiquier	estiquieroient	V;COND;PL;3;LGSPEC1
gaber	gabasses	V;IPFV;SBJV;SG;2;PST
tirer	tires	V;IND;SG;2;PRS
estudier	estudierai	V;IND;SG;1;FUT;LGSPEC1
advancer	advance	V;SBJV;SG;1;PRS
desarmer	desarmes	V;SBJV;SG;2;PRS
empieger	empiegeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
iouer	iouoys	V;IPFV;IND;SG;2;PST;LGSPEC2
picquier	picquoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
ronfler	ronflerons	V;IND;PL;1;FUT
alonger	alongeoit	V;IPFV;IND;SG;3;PST;LGSPEC1
guider	guides	V;IND;SG;2;PRS
desfaire	desfit	V;PFV;IND;SG;3;PST
loger	loge	V;IND;SG;1;PRS
veigler	veigles	V;SBJV;SG;2;PRS
eschieller	esciellerez	V;IND;PL;2;FUT
garder	garderent	V;PFV;IND;PL;3;PST
deffier	deffieryons	V;COND;PL;1;LGSPEC2
emprunter	empruntions	V;IPFV;IND;PL;1;PST;LGSPEC1
endommaiger	endommaigerent	V;PFV;IND;PL;3;PST
redrechier	redrechierai	V;IND;SG;1;FUT;LGSPEC1
allaicter	allaictast	V;IPFV;SBJV;SG;3;PST
enseignier	enseigneroit	V;COND;SG;3;LGSPEC1
escrier	escriassent	V;IPFV;SBJV;PL;3;PST
enterrer	enterryez	V;IPFV;IND;PL;2;PST;LGSPEC2
desployer	desployeriez	V;COND;PL;2;LGSPEC1
mulcter	mulctyons	V;IPFV;IND;PL;1;PST;LGSPEC2
alonger	alongeasses	V;IPFV;SBJV;SG;2;PST
frapper	frappas	V;PFV;IND;SG;2;PST
respirer	respireroyt	V;COND;SG;3;LGSPEC2
chercher	cherchastes	V;PFV;IND;PL;2;PST
fiancer	fianceroys	V;COND;SG;2;LGSPEC2
pausmer	pausmeray	V;IND;SG;1;FUT;LGSPEC2
recuperer	recuperes	V;SBJV;SG;2;PRS
proteger	protegeast	V;IPFV;SBJV;SG;3;PST
heiler	heiles	V;SBJV;SG;2;PRS
gouster	gousteroient	V;COND;PL;3;LGSPEC1
adiouster	adiousteras	V;IND;SG;2;FUT
baisler	baisler	V;NFIN
esmerveillier	esmerveillions	V;IND;PL;1;PRS
alterer	altera	V;PFV;IND;SG;3;PST
ietter	iettassiez	V;IPFV;SBJV;PL;2;PST
ronfler	ronflassiez	V;IPFV;SBJV;PL;2;PST
enconcher	enconchyez	V;IPFV;IND;PL;2;PST;LGSPEC2
enseignier	enseigne	V;IND;SG;1;PRS
esgaler	esgale	V;SBJV;SG;3;PRS
plaider	plaidassent	V;IPFV;SBJV;PL;3;PST
desployer	desployasmes	V;PFV;IND;PL;1;PST
deifier	deifient	V;SBJV;PL;3;PRS
redrechier	redrechions	V;IPFV;IND;PL;1;PST;LGSPEC1
viser	visasse	V;IPFV;SBJV;SG;1;PST
demourer	demourastes	V;PFV;IND;PL;2;PST
bransler	branslerois	V;COND;SG;2;LGSPEC1
pourmener	pourmenez	V;SBJV;PL;2;PRS
soucyer	soucyerions	V;COND;PL;1;LGSPEC1
preferer	preferois	V;IPFV;IND;SG;2;PST;LGSPEC1
importuner	importunez	V;IND;PL;2;PRS
demourer	demoureryez	V;COND;PL;2;LGSPEC2
garder	gardoys	V;IPFV;IND;SG;2;PST;LGSPEC2
chevauchier	chevauche	V;IMP;SG;2
tumber	tumberoyt	V;COND;SG;3;LGSPEC2
occurrer	occurreroit	V;COND;SG;3;LGSPEC1
mulcter	mulcte	V;IND;SG;3;PRS
prattiquer	prattiqueroyt	V;COND;SG;3;LGSPEC2
doubter	doubterons	V;IND;PL;1;FUT
accompaigner	accompaigneras	V;IND;SG;2;FUT
esmayer	esmayons	V;IMP;PL;1
pourforcer	pourforcent	V;SBJV;PL;3;PRS
provocquer	provocquerent	V;PFV;IND;PL;3;PST
allaicter	allaicter	V;NFIN
ronfler	ronfles	V;IND;SG;2;PRS
mascher	maschons	V;IMP;PL;1
explorer	explorassions	V;IPFV;SBJV;PL;1;PST
edifier	edifiez	V;SBJV;PL;2;PRS
aloser	alosastes	V;PFV;IND;PL;2;PST
despouiller	despouillerois	V;COND;SG;2;LGSPEC1
revencher	revenchez	V;IMP;PL;2
esmerveillier	esmerveilliez	V;IPFV;IND;PL;2;PST;LGSPEC1
effronter	effrontez	V;IMP;PL;2
trancher	trancheryez	V;COND;PL;2;LGSPEC2
plier	plieroit	V;COND;SG;3;LGSPEC1
desadvouer	desadvouois	V;IPFV;IND;SG;1;PST;LGSPEC1
expuyser	expuysassent	V;IPFV;SBJV;PL;3;PST
suffocquer	suffocquez	V;SBJV;PL;2;PRS
redrechier	redrechassent	V;IPFV;SBJV;PL;3;PST
embausmer	embausmoit	V;IPFV;IND;SG;3;PST;LGSPEC1
luitter	luitterions	V;COND;PL;1;LGSPEC1
regretter	regretteroys	V;COND;SG;2;LGSPEC2
perser	persons	V;SBJV;PL;1;PRS
escryer	escryons	V;SBJV;PL;1;PRS
achapter	achapte	V;SBJV;SG;1;PRS
contrepoiser	contrepoiseray	V;IND;SG;1;FUT;LGSPEC2
fortifier	fortifie	V;SBJV;SG;1;PRS
emboucher	emboucherons	V;IND;PL;1;FUT
essayer	essayent	V;SBJV;PL;3;PRS
avanchier	avanchieryons	V;COND;PL;1;LGSPEC2
blasphemer	blasphemez	V;SBJV;PL;2;PRS
desver	desves	V;IND;SG;2;PRS
preceder	precedassions	V;IPFV;SBJV;PL;1;PST
evaporer	evaporent	V;IND;PL;3;PRS
descouchier	descouche	V;SBJV;SG;1;PRS
mucer	muçoys	V;IPFV;IND;SG;1;PST;LGSPEC2
enconcher	enconchent	V;SBJV;PL;3;PRS
robber	robbois	V;IPFV;IND;SG;2;PST;LGSPEC1
besoinger	besoigne	V;IMP;SG;2
resigner	resigneroys	V;COND;SG;2;LGSPEC2
encharger	enchargeasmes	V;PFV;IND;PL;1;PST
fromenter	fromentasmes	V;PFV;IND;PL;1;PST
esgaler	esgales	V;IND;SG;2;PRS
embausmer	embausmeront	V;IND;PL;3;FUT
saluer	saluoit	V;IPFV;IND;SG;3;PST;LGSPEC1
foetter	foettyez	V;IPFV;IND;PL;2;PST;LGSPEC2
iecter	iecterois	V;COND;SG;1;LGSPEC1
penetrer	penetrez	V;IMP;PL;2
engendrer	engendrois	V;IPFV;IND;SG;1;PST;LGSPEC1
importuner	importune	V;SBJV;SG;3;PRS
regorger	regorgyons	V;IPFV;IND;PL;1;PST;LGSPEC2
remercyer	remercyerons	V;IND;PL;1;FUT
ottroyer	ottroyerons	V;IND;PL;1;FUT
rincer	rinçassiez	V;IPFV;SBJV;PL;2;PST
oublyer	oublyeront	V;IND;PL;3;FUT
pacquer	pacquoient	V;IPFV;IND;PL;3;PST;LGSPEC1
desguiser	desguiseroyent	V;COND;PL;3;LGSPEC2
reverer	reveroys	V;IPFV;IND;SG;1;PST;LGSPEC2
chanter	chanteroys	V;COND;SG;2;LGSPEC2
cointoier	cointoiions	V;IPFV;IND;PL;1;PST;LGSPEC1
gouverner	gouvernoys	V;IPFV;IND;SG;1;PST;LGSPEC2
depescher	depeschast	V;IPFV;SBJV;SG;3;PST
oublyer	oublyiez	V;IPFV;IND;PL;2;PST;LGSPEC1
evaporer	evaporyons	V;IPFV;IND;PL;1;PST;LGSPEC2
obliger	obligeasses	V;IPFV;SBJV;SG;2;PST
esbaucher	esbaucherions	V;COND;PL;1;LGSPEC1
enyvrer	enyvra	V;PFV;IND;SG;3;PST
pourpenser	pourpensas	V;PFV;IND;SG;2;PST
pourmener	pourmenerois	V;COND;SG;2;LGSPEC1
escumer	escumoit	V;IPFV;IND;SG;3;PST;LGSPEC1
fascher	faschera	V;IND;SG;3;FUT
seiourner	seiournyons	V;IPFV;IND;PL;1;PST;LGSPEC2
encliner	enclinez	V;SBJV;PL;2;PRS
fascher	fascheroyt	V;COND;SG;3;LGSPEC2
ietter	iettoient	V;IPFV;IND;PL;3;PST;LGSPEC1
herrier	herrierois	V;COND;SG;2;LGSPEC1
finer	fina	V;PFV;IND;SG;1;PST
esgratigner	esgratignerez	V;IND;PL;2;FUT
seiourner	seiournerai	V;IND;SG;1;FUT;LGSPEC1
desnouer	desnoue	V;IND;SG;3;PRS
baiser	baisons	V;IMP;PL;1
deifier	deifiois	V;IPFV;IND;SG;2;PST;LGSPEC1
reguarder	reguarda	V;PFV;IND;SG;3;PST
abayer	abayerai	V;IND;SG;1;FUT;LGSPEC1
praeparer	praeparez	V;IMP;PL;2
dilater	dilaterois	V;COND;SG;1;LGSPEC1
escouiller	escouilleray	V;IND;SG;1;FUT;LGSPEC2
retyrer	retyreroyent	V;COND;PL;3;LGSPEC2
peser	peseryons	V;COND;PL;1;LGSPEC2
coniecturer	coniectureroient	V;COND;PL;3;LGSPEC1
leicher	leichastes	V;PFV;IND;PL;2;PST
descouchier	descouchoys	V;IPFV;IND;SG;2;PST;LGSPEC2
alonger	alongeriez	V;COND;PL;2;LGSPEC1
escrier	escrie	V;IMP;SG;2
contrepoiser	contrepoiserions	V;COND;PL;1;LGSPEC1
veigler	veigleriez	V;COND;PL;2;LGSPEC1
quester	questerent	V;PFV;IND;PL;3;PST
prattiquer	prattiqua	V;PFV;IND;SG;3;PST
demonstrer	demonstrast	V;IPFV;SBJV;SG;3;PST
brusler	brusleroys	V;COND;SG;1;LGSPEC2
baisler	baisleroit	V;COND;SG;3;LGSPEC1
resumer	resumoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
despuceller	despucellent	V;IND;PL;3;PRS
avoir	auroyent	V;COND;PL;3;LGSPEC2
singler	singleroys	V;COND;SG;2;LGSPEC2
recorder	recordoient	V;IPFV;IND;PL;3;PST;LGSPEC1
presenter	presenteroit	V;COND;SG;3;LGSPEC1
rebarber	rebarbasse	V;IPFV;SBJV;SG;1;PST
devourer	devourasses	V;IPFV;SBJV;SG;2;PST
exstirper	exstirperoys	V;COND;SG;2;LGSPEC2
regorger	regorgeas	V;PFV;IND;SG;2;PST
renfler	renflerois	V;COND;SG;1;LGSPEC1
eschauffer	eschaufferois	V;COND;SG;1;LGSPEC1
buchier	buchoient	V;IPFV;IND;PL;3;PST;LGSPEC1
amer	amois	V;IPFV;IND;SG;2;PST;LGSPEC1
estinceller	estincellerez	V;IND;PL;2;FUT
appuier	appuieryez	V;COND;PL;2;LGSPEC2
lurrer	lurreroient	V;COND;PL;3;LGSPEC1
regorger	regorgeassiez	V;IPFV;SBJV;PL;2;PST
blasphemer	blasphemer	V;NFIN
esguiser	esguisons	V;IMP;PL;1
disner	disnerent	V;PFV;IND;PL;3;PST
recuperer	recuperions	V;IPFV;IND;PL;1;PST;LGSPEC1
condescendre	condescendoie	V;IPFV;IND;SG;1;PST;LGSPEC1
separer	separez	V;SBJV;PL;2;PRS
blasphemer	blasphemasse	V;IPFV;SBJV;SG;1;PST
gaimenter	gaimentions	V;IPFV;IND;PL;1;PST;LGSPEC1
tromper	trompastes	V;PFV;IND;PL;2;PST
encliner	enclinerons	V;IND;PL;1;FUT
houer	houerai	V;IND;SG;1;FUT;LGSPEC1
esmayer	esmaye	V;IMP;SG;2
redoubter	redoubtons	V;IMP;PL;1
trouver	trouveras	V;IND;SG;2;FUT
proteger	protegez	V;SBJV;PL;2;PRS
desrouter	desroutes	V;IND;SG;2;PRS
vengier	vengeasmes	V;PFV;IND;PL;1;PST
traveillier	traveillieroyt	V;COND;SG;3;LGSPEC2
empieger	empiegeroys	V;COND;SG;1;LGSPEC2
fortifier	fortifierois	V;COND;SG;2;LGSPEC1
estoffer	estoffoys	V;IPFV;IND;SG;1;PST;LGSPEC2
enorter	enortoys	V;IPFV;IND;SG;1;PST;LGSPEC2
pourforcer	pourforce	V;IMP;SG;2
cerchier	cerchoient	V;IPFV;IND;PL;3;PST;LGSPEC1
deschainer	deschaines	V;SBJV;SG;2;PRS
desfaire	desferas	V;IND;SG;2;FUT
conquester	conquestassiez	V;IPFV;SBJV;PL;2;PST
desmonter	desmonteryons	V;COND;PL;1;LGSPEC2
resver	resvassions	V;IPFV;SBJV;PL;1;PST
confesser	confessez	V;IND;PL;2;PRS
transgloutir	transgloutisse	V;SBJV;SG;1;PRS
fromenter	fromentez	V;IND;PL;2;PRS
tremper	trempasses	V;IPFV;SBJV;SG;2;PST
contregarder	contregardoient	V;IPFV;IND;PL;3;PST;LGSPEC1
marier	marie	V;IND;SG;3;PRS
ralier	raliastes	V;PFV;IND;PL;2;PST
abiurer	abiureras	V;IND;SG;2;FUT
flotter	flotteras	V;IND;SG;2;FUT
estre	serions	V;COND;PL;1
commencer	commence	V;IND;SG;1;PRS
flotter	flottassent	V;IPFV;SBJV;PL;3;PST
remercyer	remercye	V;SBJV;SG;3;PRS
effectuer	effectuons	V;IND;PL;1;PRS
deslacer	delacez	V;IND;PL;2;PRS
doubter	doubtoys	V;IPFV;IND;SG;2;PST;LGSPEC2
invader	invadoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
baiser	baiser	V;NFIN
laisser	laisserai	V;IND;SG;1;FUT;LGSPEC1
explorer	exploreras	V;IND;SG;2;FUT
appareiller	appareillons	V;SBJV;PL;1;PRS
quereler	querelez	V;IND;PL;2;PRS
soumectre	soumectoient	V;IPFV;IND;PL;3;PST;LGSPEC1
encontrer	encontrerez	V;IND;PL;2;FUT
fascher	faschasmes	V;PFV;IND;PL;1;PST
tromper	trompoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
esgaler	esgalois	V;IPFV;IND;SG;1;PST;LGSPEC1
esternuer	esternuerions	V;COND;PL;1;LGSPEC1
estudier	estudieroyt	V;COND;SG;3;LGSPEC2
reiecter	reiecterions	V;COND;PL;1;LGSPEC1
songer	songe	V;SBJV;SG;1;PRS
nouer	nouoit	V;IPFV;IND;SG;3;PST;LGSPEC1
redrechier	redrechent	V;IND;PL;3;PRS
soubhaitter	soubhaitte	V;SBJV;SG;1;PRS
despencer	despencent	V;SBJV;PL;3;PRS
contrepoiser	contrepoiserez	V;IND;PL;2;FUT
baptizer	baptizions	V;IPFV;IND;PL;1;PST;LGSPEC1
derver	derveray	V;IND;SG;1;FUT;LGSPEC2
escrier	escrioient	V;IPFV;IND;PL;3;PST;LGSPEC1
essilier	essilierons	V;IND;PL;1;FUT
picquier	picquoys	V;IPFV;IND;SG;2;PST;LGSPEC2
consyderer	consydererons	V;IND;PL;1;FUT
passer	passerez	V;IND;PL;2;FUT
esgarer	esgarez	V;IMP;PL;2
rotter	rottassent	V;IPFV;SBJV;PL;3;PST
remerquer	remerquons	V;IND;PL;1;PRS
estoffer	estofferez	V;IND;PL;2;FUT
escarter	escartions	V;IPFV;IND;PL;1;PST;LGSPEC1
fiancer	fiancera	V;IND;SG;3;FUT
amadouer	amadoueroient	V;COND;PL;3;LGSPEC1
sçavoir	sçaurayent	V;COND;PL;3;LGSPEC1
passer	passasses	V;IPFV;SBJV;SG;2;PST
enhorter	enhortent	V;IND;PL;3;PRS
ozer	ozes	V;IND;SG;2;PRS
ronfler	ronfloys	V;IPFV;IND;SG;1;PST;LGSPEC2
presupposer	presupposast	V;IPFV;SBJV;SG;3;PST
estonner	estonnerions	V;COND;PL;1;LGSPEC1
effronter	effronteroient	V;COND;PL;3;LGSPEC1
obliger	obligeoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
emboucher	emboucherai	V;IND;SG;1;FUT;LGSPEC1
soingner	soingneroit	V;COND;SG;3;LGSPEC1
faire	feras	V;IND;SG;2;FUT
veiller	veilloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
recouvrer	recouvreryons	V;COND;PL;1;LGSPEC2
honnourer	honnouras	V;PFV;IND;SG;2;PST
inviter	inviteray	V;IND;SG;1;FUT;LGSPEC2
chercher	cherchasses	V;IPFV;SBJV;SG;2;PST
courroucer	courrouçoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
fraper	frapois	V;IPFV;IND;SG;2;PST;LGSPEC1
passer	passions	V;IPFV;IND;PL;1;PST;LGSPEC1
deschainer	deschainas	V;PFV;IND;SG;2;PST
esguiser	esguisassions	V;IPFV;SBJV;PL;1;PST
advouer	advouoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
toucher	touche	V;SBJV;SG;3;PRS
traveillier	traveilliez	V;SBJV;PL;2;PRS
soubhaitter	soubhaitteras	V;IND;SG;2;FUT
explicquer	explicquez	V;IMP;PL;2
cerchier	cercha	V;PFV;IND;SG;1;PST
raenchonner	raenchonnoys	V;IPFV;IND;SG;2;PST;LGSPEC2
suffocquer	suffocqueront	V;IND;PL;3;FUT
presupposer	presupposez	V;IND;PL;2;PRS
esventer	esventerions	V;COND;PL;1;LGSPEC1
veigler	veigleray	V;IND;SG;1;FUT;LGSPEC2
proteger	protegerois	V;COND;SG;2;LGSPEC1
iecter	iecterent	V;PFV;IND;PL;3;PST
encontrer	encontrerons	V;IND;PL;1;FUT
advouer	advouoys	V;IPFV;IND;SG;2;PST;LGSPEC2
regretter	regrettoit	V;IPFV;IND;SG;3;PST;LGSPEC1
eslancer	eslanciez	V;IPFV;IND;PL;2;PST;LGSPEC1
accorder	accorderiez	V;COND;PL;2;LGSPEC1
aymer	aymassent	V;IPFV;SBJV;PL;3;PST
laisser	laissasse	V;IPFV;SBJV;SG;1;PST
gaber	gaberay	V;IND;SG;1;FUT;LGSPEC2
operer	operez	V;SBJV;PL;2;PRS
accompaigner	accompaigneroys	V;COND;SG;1;LGSPEC2
viser	viserions	V;COND;PL;1;LGSPEC1
pasturer	pasturoit	V;IPFV;IND;SG;3;PST;LGSPEC1
desgorger	desgorgeroys	V;COND;SG;1;LGSPEC2
enhorter	enhortois	V;IPFV;IND;SG;2;PST;LGSPEC1
encliner	enclinassent	V;IPFV;SBJV;PL;3;PST
rappeller	rappellez	V;IMP;PL;2
reiecter	reiecteras	V;IND;SG;2;FUT
nettoyer	nettoye	V;SBJV;SG;3;PRS
atourner	atournassions	V;IPFV;SBJV;PL;1;PST
donner	donnassent	V;IPFV;SBJV;PL;3;PST
desmettre	desmettoys	V;IPFV;IND;SG;1;PST;LGSPEC2
deschevaucher	deschevauches	V;IND;SG;2;PRS
nombrer	nombrez	V;IND;PL;2;PRS
houer	houera	V;IND;SG;3;FUT
aquitter	aquittasse	V;IPFV;SBJV;SG;1;PST
souspirer	souspire	V;SBJV;SG;1;PRS
souspirer	souspireroyent	V;COND;PL;3;LGSPEC2
moustrer	moustre	V;IND;SG;1;PRS
souspirer	souspirassent	V;IPFV;SBJV;PL;3;PST
effronter	effrontera	V;IND;SG;3;FUT
reverer	revereroyt	V;COND;SG;3;LGSPEC2
trousser	troussent	V;SBJV;PL;3;PRS
alterer	alterer	V;NFIN
quereler	querelerois	V;COND;SG;2;LGSPEC1
revencher	revencheryez	V;COND;PL;2;LGSPEC2
reverer	reverassions	V;IPFV;SBJV;PL;1;PST
recorder	recorderiez	V;COND;PL;2;LGSPEC1
desloger	deslogeasses	V;IPFV;SBJV;SG;2;PST
gouster	gousterent	V;PFV;IND;PL;3;PST
mehaignier	mehaignoys	V;IPFV;IND;SG;1;PST;LGSPEC2
desheriter	desheriteras	V;IND;SG;2;FUT
serainer	seraineroyt	V;COND;SG;3;LGSPEC2
esvanter	esvantez	V;IND;PL;2;PRS
fouragier	fouragent	V;SBJV;PL;3;PRS
posseder	possederai	V;IND;SG;1;FUT;LGSPEC1
avoir	aurions	V;COND;PL;1
esquacher	esquachoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
ietter	iettons	V;SBJV;PL;1;PRS
desver	desvastes	V;PFV;IND;PL;2;PST
veigler	veigleroyent	V;COND;PL;3;LGSPEC2
nombrer	nombra	V;PFV;IND;SG;1;PST
soubhaitter	soubhaitterez	V;IND;PL;2;FUT
courouchier	courouche	V;IND;SG;1;PRS
gouster	gouster	V;NFIN
preceder	precede	V;SBJV;SG;1;PRS
desrouter	desroutiez	V;IPFV;IND;PL;2;PST;LGSPEC1
embler	emblerois	V;COND;SG;1;LGSPEC1
estimer	estimeryez	V;COND;PL;2;LGSPEC2
croniquier	croniquioys	V;IPFV;IND;SG;1;PST;LGSPEC2
eslancer	eslance	V;IMP;SG;2
gaimenter	gaimente	V;SBJV;SG;3;PRS
avanchier	avanchieroit	V;COND;SG;3;LGSPEC1
encliner	enclinent	V;IND;PL;3;PRS
ymaginer	ymaginasse	V;IPFV;SBJV;SG;1;PST
caper	capes	V;SBJV;SG;2;PRS
penser	pensois	V;IPFV;IND;SG;2;PST;LGSPEC1
pryer	pryassions	V;IPFV;SBJV;PL;1;PST
celer	celoient	V;IPFV;IND;PL;3;PST;LGSPEC1
lyer	lye	V;IND;SG;3;PRS
fouller	foulla	V;PFV;IND;SG;3;PST
translater	translateront	V;IND;PL;3;FUT
demourer	demourerent	V;PFV;IND;PL;3;PST
soubhaitter	soubhaittent	V;IND;PL;3;PRS
caper	capassent	V;IPFV;SBJV;PL;3;PST
esbaucher	esbauchyez	V;IPFV;IND;PL;2;PST;LGSPEC2
traveillier	traveillierai	V;IND;SG;1;FUT;LGSPEC1
esmayer	esmayyons	V;IPFV;IND;PL;1;PST;LGSPEC2
gaspiller	gaspilloit	V;IPFV;IND;SG;3;PST;LGSPEC1
baptizer	baptizasmes	V;PFV;IND;PL;1;PST
preter	pretes	V;SBJV;SG;2;PRS
pacquer	pacque	V;IND;SG;1;PRS
oublyer	oublyassiez	V;IPFV;SBJV;PL;2;PST
leicher	leicheront	V;IND;PL;3;FUT
atacher	atacha	V;PFV;IND;SG;3;PST
alonger	alongeons	V;IND;PL;1;PRS
eslever	esleva	V;PFV;IND;SG;1;PST
explicquer	explicquassiez	V;IPFV;SBJV;PL;2;PST
trembler	trembliez	V;IPFV;IND;PL;2;PST;LGSPEC1
remercyer	remercyions	V;IPFV;IND;PL;1;PST;LGSPEC1
garder	gardoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
manger	mange	V;IND;SG;3;PRS
entreruyner	vous entreruynez	V;SBJV;PL;2;PRS
presenter	presentez	V;IMP;PL;2
amadouer	amadoueryez	V;COND;PL;2;LGSPEC2
deschevaucher	deschevauchera	V;IND;SG;3;FUT
accompaigner	accompaignera	V;IND;SG;3;FUT
aterminer	atermine	V;IND;SG;1;PRS
moustrer	moustreryez	V;COND;PL;2;LGSPEC2
quester	questons	V;IND;PL;1;PRS
amadouer	amadoueront	V;IND;PL;3;FUT
tourmenter	tourmentassions	V;IPFV;SBJV;PL;1;PST
trousser	trousserons	V;IND;PL;1;FUT
commencer	commences	V;IND;SG;2;PRS
chercher	chercheront	V;IND;PL;3;FUT
baisler	baislent	V;IND;PL;3;PRS
appuier	appuioys	V;IPFV;IND;SG;1;PST;LGSPEC2
leicher	leiches	V;IND;SG;2;PRS
preferer	preferassiez	V;IPFV;SBJV;PL;2;PST
quester	questyez	V;IPFV;IND;PL;2;PST;LGSPEC2
tromper	trompons	V;SBJV;PL;1;PRS
esmerveillier	esmerveillasse	V;IPFV;SBJV;SG;1;PST
rouller	roulleroys	V;COND;SG;2;LGSPEC2
deifier	deifie	V;SBJV;SG;1;PRS
entituler	entitule	V;IMP;SG;2
esmayer	esmayions	V;IPFV;IND;PL;1;PST;LGSPEC1
picquer	picqueras	V;IND;SG;2;FUT
esternuer	esternuoys	V;IPFV;IND;SG;2;PST;LGSPEC2
arrengier	arrengeast	V;IPFV;SBJV;SG;3;PST
contregarder	contregarder	V;NFIN
tuer	tuoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
toucher	touchassiez	V;IPFV;SBJV;PL;2;PST
baptiser	baptiseroient	V;COND;PL;3;LGSPEC1
achapter	achaptoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
estourdir	estourdissions	V;SBJV;PL;1;PRS
grapper	grappoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
moustrer	moustrer	V;NFIN
leicher	leichiez	V;IPFV;IND;PL;2;PST;LGSPEC1
eschieller	esciellastes	V;PFV;IND;PL;2;PST
gouster	gousterois	V;COND;SG;2;LGSPEC1
cerchier	cerchiez	V;IPFV;IND;PL;2;PST;LGSPEC1
aloser	aloserai	V;IND;SG;1;FUT;LGSPEC1
accepter	accepter	V;NFIN
penetrer	penetrois	V;IPFV;IND;SG;1;PST;LGSPEC1
perser	perser	V;NFIN
tourmenter	tourmenteroyt	V;COND;SG;3;LGSPEC2
rotter	rottas	V;PFV;IND;SG;2;PST
interpreter	interpretoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
tocquer	tocquasses	V;IPFV;SBJV;SG;2;PST
retourner	retournons	V;SBJV;PL;1;PRS
desnouer	desnouons	V;SBJV;PL;1;PRS
renfler	renfloient	V;IPFV;IND;PL;3;PST;LGSPEC1
enterrer	enterreras	V;IND;SG;2;FUT
desheriter	desheritez	V;IND;PL;2;PRS
engroisser	engroisseroys	V;COND;SG;1;LGSPEC2
eschieller	escielle	V;IND;SG;1;PRS
empieger	empiegeras	V;IND;SG;2;FUT
heurter	heurtions	V;IPFV;IND;PL;1;PST;LGSPEC1
suffocquer	suffocqueryez	V;COND;PL;2;LGSPEC2
recuperer	recuperez	V;IND;PL;2;PRS
tocquer	tocqueryez	V;COND;PL;2;LGSPEC2
embausmer	embausmoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
armoier	armoioient	V;IPFV;IND;PL;3;PST;LGSPEC1
adapter	adaptassiez	V;IPFV;SBJV;PL;2;PST
toucher	toucheroys	V;COND;SG;2;LGSPEC2
blasphemer	blasphemois	V;IPFV;IND;SG;1;PST;LGSPEC1
mescler	mesclera	V;IND;SG;3;FUT
eslancer	eslança	V;PFV;IND;SG;1;PST
laisser	laissiez	V;IPFV;IND;PL;2;PST;LGSPEC1
deshonnourer	deshonnoure	V;IND;SG;1;PRS
manouvrer	manouvrastes	V;PFV;IND;PL;2;PST
amer	amoys	V;IPFV;IND;SG;2;PST;LGSPEC2
superseder	supersederoit	V;COND;SG;3;LGSPEC1
presumer	presumons	V;IND;PL;1;PRS
essilier	essilions	V;IMP;PL;1
esgratigner	esgratigneroit	V;COND;SG;3;LGSPEC1
ieuner	ieunyez	V;IPFV;IND;PL;2;PST;LGSPEC2
aquitter	aquittez	V;IND;PL;2;PRS
encharger	encharges	V;IND;SG;2;PRS
voller	volleras	V;IND;SG;2;FUT
offencer	offenças	V;PFV;IND;SG;2;PST
espier	espieryons	V;COND;PL;1;LGSPEC2
chevauchier	chevauchierois	V;COND;SG;2;LGSPEC1
luitter	luittez	V;IMP;PL;2
pourmener	pourmeniez	V;IPFV;IND;PL;2;PST;LGSPEC1
mucer	muçoit	V;IPFV;IND;SG;3;PST;LGSPEC1
superseder	supersedassions	V;IPFV;SBJV;PL;1;PST
manger	mangeassions	V;IPFV;SBJV;PL;1;PST
trouver	trouvassions	V;IPFV;SBJV;PL;1;PST
empieger	empiegent	V;SBJV;PL;3;PRS
eviter	evitastes	V;PFV;IND;PL;2;PST
esvanter	esvantoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
revencher	revencherions	V;COND;PL;1;LGSPEC1
separer	separa	V;PFV;IND;SG;3;PST
essilier	essilierent	V;PFV;IND;PL;3;PST
deschevaucher	deschevaucha	V;PFV;IND;SG;1;PST
cointoier	cointoiassiez	V;IPFV;SBJV;PL;2;PST
alterer	alterez	V;SBJV;PL;2;PRS
declairer	declairois	V;IPFV;IND;SG;2;PST;LGSPEC1
garder	gardez	V;IND;PL;2;PRS
detester	detesteryez	V;COND;PL;2;LGSPEC2
allaicter	allaictera	V;IND;SG;3;FUT
reiecter	reiectast	V;IPFV;SBJV;SG;3;PST
verifier	verifiassions	V;IPFV;SBJV;PL;1;PST
baiser	baiseroyent	V;COND;PL;3;LGSPEC2
finer	fines	V;SBJV;SG;2;PRS
courouchier	courouchieroient	V;COND;PL;3;LGSPEC1
reiecter	reiectons	V;IMP;PL;1
esvertuer	esvertue	V;SBJV;SG;1;PRS
traicter	tracteront	V;IND;PL;3;FUT
depescher	depescheras	V;IND;SG;2;FUT
negotier	negotiera	V;IND;SG;3;FUT
enfelonner	enfelonnions	V;IPFV;IND;PL;1;PST;LGSPEC1
proffiter	proffitassiez	V;IPFV;SBJV;PL;2;PST
chercher	chercheroyent	V;COND;PL;3;LGSPEC2
retirer	retirerions	V;COND;PL;1;LGSPEC1
reverer	revereroys	V;COND;SG;1;LGSPEC2
essilier	essiles	V;SBJV;SG;2;PRS
appareiller	appareilleroyent	V;COND;PL;3;LGSPEC2
nouer	noues	V;SBJV;SG;2;PRS
frapper	frappois	V;IPFV;IND;SG;2;PST;LGSPEC1
baiser	baisa	V;PFV;IND;SG;3;PST
temprer	tempres	V;SBJV;SG;2;PRS
eschapper	eschappassiez	V;IPFV;SBJV;PL;2;PST
vengier	vengions	V;IND;PL;1;PRS
accomplir	accomplissoit	V;IPFV;IND;SG;3;PST;LGSPEC1
desheriter	desherityons	V;IPFV;IND;PL;1;PST;LGSPEC2
auser	ausez	V;IND;PL;2;PRS
habiter	habitoient	V;IPFV;IND;PL;3;PST;LGSPEC1
houer	houeryez	V;COND;PL;2;LGSPEC2
melancholier	melancholioyt	V;IPFV;IND;SG;3;PST;LGSPEC2
navrer	navrera	V;IND;SG;3;FUT
fortifier	fortifias	V;PFV;IND;SG;2;PST
verifier	verifiyons	V;IPFV;IND;PL;1;PST;LGSPEC2
esgarer	esgareroys	V;COND;SG;1;LGSPEC2
mulcter	mulctast	V;IPFV;SBJV;SG;3;PST
recouvrer	recouvriez	V;IPFV;IND;PL;2;PST;LGSPEC1
accepter	acceptyons	V;IPFV;IND;PL;1;PST;LGSPEC2
trouver	trouvons	V;IND;PL;1;PRS
rotter	rottoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
nettoyer	nettoyoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
lascher	laschast	V;IPFV;SBJV;SG;3;PST
plier	plient	V;IND;PL;3;PRS
avoyr	eusmes	V;PFV;IND;PL;1;PST
gouster	gousteroys	V;COND;SG;2;LGSPEC2
explicquer	explicquassions	V;IPFV;SBJV;PL;1;PST
tramper	trampoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
encharger	enchargera	V;IND;SG;3;FUT
arriver	arrive	V;IND;SG;3;PRS
plier	pliasmes	V;PFV;IND;PL;1;PST
abboyer	abboyerez	V;IND;PL;2;FUT
adiouster	adioustassions	V;IPFV;SBJV;PL;1;PST
revencher	revenchent	V;SBJV;PL;3;PRS
inviter	invitoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
rebarber	rebarbent	V;IND;PL;3;PRS
flatter	flatte	V;IMP;SG;2
deslacer	delaceroit	V;COND;SG;3;LGSPEC1
contregarder	contregarderent	V;PFV;IND;PL;3;PST
mucer	muceroit	V;COND;SG;3;LGSPEC1
aloser	alosasses	V;IPFV;SBJV;SG;2;PST
suffocquer	suffocquoient	V;IPFV;IND;PL;3;PST;LGSPEC1
escryer	escryas	V;PFV;IND;SG;2;PST
endommaiger	endommaigeast	V;IPFV;SBJV;SG;3;PST
accuser	accusez	V;IND;PL;2;PRS
singler	singleroyt	V;COND;SG;3;LGSPEC2
resumer	resumeryez	V;COND;PL;2;LGSPEC2
aracher	arache	V;IND;SG;3;PRS
trousser	troussassiez	V;IPFV;SBJV;PL;2;PST
nettoyer	nettoyasses	V;IPFV;SBJV;SG;2;PST
esveigler	esveigla	V;PFV;IND;SG;1;PST
houer	houas	V;PFV;IND;SG;2;PST
enconcher	enconche	V;SBJV;SG;1;PRS
recuperer	recuperons	V;IND;PL;1;PRS
condescendre	condescendreit	V;COND;SG;3;LGSPEC2
veigler	veiglassiez	V;IPFV;SBJV;PL;2;PST
abiurer	abiurerois	V;COND;SG;1;LGSPEC1
demourer	demourassent	V;IPFV;SBJV;PL;3;PST
luitter	luittoys	V;IPFV;IND;SG;1;PST;LGSPEC2
laidenger	laidengeoys	V;IPFV;IND;SG;1;PST;LGSPEC2
gouster	goustois	V;IPFV;IND;SG;2;PST;LGSPEC1
disner	disneroit	V;COND;SG;3;LGSPEC1
entituler	entituleray	V;IND;SG;1;FUT;LGSPEC2
entreruyner	entreruynons nous	V;IMP;PL;1
amadouer	amadouez	V;IMP;PL;2
regorger	regorgeoys	V;IPFV;IND;SG;2;PST;LGSPEC2
confermer	confermiez	V;IPFV;IND;PL;2;PST;LGSPEC1
espier	espierois	V;COND;SG;1;LGSPEC1
ozer	oze	V;SBJV;SG;1;PRS
saluer	saluasse	V;IPFV;SBJV;SG;1;PST
allaicter	allaictes	V;IND;SG;2;PRS
retyrer	retyroys	V;IPFV;IND;SG;2;PST;LGSPEC2
accepter	acceptoys	V;IPFV;IND;SG;1;PST;LGSPEC2
chanter	chanta	V;PFV;IND;SG;1;PST
superseder	supersederiez	V;COND;PL;2;LGSPEC1
iecter	iectois	V;IPFV;IND;SG;2;PST;LGSPEC1
toucher	touchons	V;IND;PL;1;PRS
empescher	empeschiez	V;IPFV;IND;PL;2;PST;LGSPEC1
inviter	invita	V;PFV;IND;SG;1;PST
accorder	accordyons	V;IPFV;IND;PL;1;PST;LGSPEC2
adiouster	adioustera	V;IND;SG;3;FUT
tumber	tumbasse	V;IPFV;SBJV;SG;1;PST
deshonnourer	deshonnourerent	V;PFV;IND;PL;3;PST
verifier	verifierez	V;IND;PL;2;FUT
oublyer	oublyassent	V;IPFV;SBJV;PL;3;PST
enterrer	enterrons	V;SBJV;PL;1;PRS
consyderer	consydereroient	V;COND;PL;3;LGSPEC1
mulcter	mulctastes	V;PFV;IND;PL;2;PST
accomplir	accomplismes	V;PFV;IND;PL;1;PST
arrengier	arrengieroyt	V;COND;SG;3;LGSPEC2
respirer	respirons	V;SBJV;PL;1;PRS
espoventer	espoventastes	V;PFV;IND;PL;2;PST
escrier	escrierez	V;IND;PL;2;FUT
louer	louasmes	V;PFV;IND;PL;1;PST
coniecturer	coniecturassions	V;IPFV;SBJV;PL;1;PST
bransler	bransloys	V;IPFV;IND;SG;1;PST;LGSPEC2
pecher	pechons	V;IND;PL;1;PRS
gaimenter	gaimentasmes	V;PFV;IND;PL;1;PST
tramper	trampe	V;IND;SG;1;PRS
grapper	grappons	V;SBJV;PL;1;PRS
eviter	evitasmes	V;PFV;IND;PL;1;PST
eschauffer	eschauffassiez	V;IPFV;SBJV;PL;2;PST
aracher	arachiez	V;IPFV;IND;PL;2;PST;LGSPEC1
reverer	reveriez	V;IPFV;IND;PL;2;PST;LGSPEC1
estourdir	estourdirions	V;COND;PL;1
nombrer	nombriez	V;IPFV;IND;PL;2;PST;LGSPEC1
negotier	negotie	V;IND;SG;1;PRS
escorner	escorne	V;IMP;SG;2
ottroyer	ottroyes	V;SBJV;SG;2;PRS
robber	robbe	V;IND;SG;3;PRS
preferer	prefereroys	V;COND;SG;1;LGSPEC2
acquiter	acquiteroit	V;COND;SG;3;LGSPEC1
blasphemer	blasphemoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
amadouer	amadouerons	V;IND;PL;1;FUT
souspirer	souspireray	V;IND;SG;1;FUT;LGSPEC2
amadouer	amadouassiez	V;IPFV;SBJV;PL;2;PST
pasturer	pastureroyt	V;COND;SG;3;LGSPEC2
mescler	mescle	V;IND;SG;3;PRS
manger	mangerez	V;IND;PL;2;FUT
gouverner	gouvernez	V;SBJV;PL;2;PRS
heurter	heurteront	V;IND;PL;3;FUT
moustrer	moustreras	V;IND;SG;2;FUT
atacher	atachez	V;IMP;PL;2
occurrer	occurra	V;PFV;IND;SG;3;PST
escouter	escoutastes	V;PFV;IND;PL;2;PST
cesser	cessassions	V;IPFV;SBJV;PL;1;PST
eslancer	eslançoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
supposer	supposeroys	V;COND;SG;2;LGSPEC2
courroucer	courroucent	V;IND;PL;3;PRS
estre	estes	V;IND;PL;2;PRS
provocquer	provocqua	V;PFV;IND;SG;3;PST
saluer	salue	V;IND;SG;1;PRS
esmerveillier	esmerveillieroys	V;COND;SG;2;LGSPEC2
tremper	trempez	V;IMP;PL;2
blesser	blessasses	V;IPFV;SBJV;SG;2;PST
excuser	excuse	V;IMP;SG;2
eviter	eviteriez	V;COND;PL;2;LGSPEC1
eschieller	esciella	V;PFV;IND;SG;1;PST
diviner	divineront	V;IND;PL;3;FUT
toucher	touchoys	V;IPFV;IND;SG;1;PST;LGSPEC2
traicter	tracteras	V;IND;SG;2;FUT
invader	invade	V;IND;SG;1;PRS
diviner	divinoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
enseignier	enseignas	V;PFV;IND;SG;2;PST
solliciter	sollicitoient	V;IPFV;IND;PL;3;PST;LGSPEC1
avanchier	avanches	V;SBJV;SG;2;PRS
eschieller	esciellerions	V;COND;PL;1;LGSPEC1
abboyer	abboyoys	V;IPFV;IND;SG;2;PST;LGSPEC2
traicter	tractasses	V;IPFV;SBJV;SG;2;PST
seeller	seellent	V;SBJV;PL;3;PRS
voller	vollasmes	V;PFV;IND;PL;1;PST
aymer	aymastes	V;PFV;IND;PL;2;PST
reverer	reverassiez	V;IPFV;SBJV;PL;2;PST
offencer	offençons	V;IMP;PL;1
presupposer	presupposassiez	V;IPFV;SBJV;PL;2;PST
impugner	impugnoys	V;IPFV;IND;SG;1;PST;LGSPEC2
esvertuer	esvertuerent	V;PFV;IND;PL;3;PST
desmonter	desmontas	V;PFV;IND;SG;2;PST
effectuer	effectuerions	V;COND;PL;1;LGSPEC1
transgloutir	transgloutirions	V;COND;PL;1
regretter	regrettez	V;SBJV;PL;2;PRS
expuyser	expuysons	V;SBJV;PL;1;PRS
contrepoiser	contrepoisasmes	V;PFV;IND;PL;1;PST
enhorter	enhortez	V;IMP;PL;2
occurrer	occurrons	V;SBJV;PL;1;PRS
remonstrer	remonstreryez	V;COND;PL;2;LGSPEC2
condescendre	condescendisse	V;IPFV;SBJV;SG;1;PST
amer	amons	V;IND;PL;1;PRS
separer	separe	V;SBJV;SG;1;PRS
singler	singleras	V;IND;SG;2;FUT
esventer	esventast	V;IPFV;SBJV;SG;3;PST
excuser	excuseroient	V;COND;PL;3;LGSPEC1
fouller	foullois	V;IPFV;IND;SG;1;PST;LGSPEC1
plier	plierois	V;COND;SG;1;LGSPEC1
proteger	proteges	V;SBJV;SG;2;PRS
hacher	hachasses	V;IPFV;SBJV;SG;2;PST
donner	donnassiez	V;IPFV;SBJV;PL;2;PST
lurrer	lurrerois	V;COND;SG;2;LGSPEC1
confesser	confessiez	V;IPFV;IND;PL;2;PST;LGSPEC1
acquiter	acquite	V;SBJV;SG;3;PRS
resister	resistiez	V;IPFV;IND;PL;2;PST;LGSPEC1
marier	marierons	V;IND;PL;1;FUT
mehaignier	mehaignes	V;SBJV;SG;2;PRS
renfler	renfleryons	V;COND;PL;1;LGSPEC2
cryer	crye	V;IMP;SG;2
gangler	ganglez	V;IND;PL;2;PRS
declairer	declairoys	V;IPFV;IND;SG;2;PST;LGSPEC2
charger	chargerent	V;PFV;IND;PL;3;PST
trouver	trouvassent	V;IPFV;SBJV;PL;3;PST
alonger	alongeast	V;IPFV;SBJV;SG;3;PST
revencher	revenches	V;SBJV;SG;2;PRS
espier	espiasmes	V;PFV;IND;PL;1;PST
ronfler	ronflassions	V;IPFV;SBJV;PL;1;PST
encharger	enchargerez	V;IND;PL;2;FUT
affier	affient	V;SBJV;PL;3;PRS
manouvrer	manouvres	V;IND;SG;2;PRS
redrechier	redreches	V;SBJV;SG;2;PRS
pasturer	pasturerois	V;COND;SG;1;LGSPEC1
temprer	tempryez	V;IPFV;IND;PL;2;PST;LGSPEC2
monstrer	monstreroient	V;COND;PL;3;LGSPEC1
desgorger	desgorgea	V;PFV;IND;SG;1;PST
esclairer	esclairerons	V;IND;PL;1;FUT
fortifier	fortifiasse	V;IPFV;SBJV;SG;1;PST
abayer	abayerois	V;COND;SG;1;LGSPEC1
menasser	menasses	V;SBJV;SG;2;PRS
allaicter	allaicte	V;IND;SG;3;PRS
prester	prestoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
esmerveillier	esmerveillas	V;PFV;IND;SG;2;PST
accointer	accointoient	V;IPFV;IND;PL;3;PST;LGSPEC1
gouster	gousterai	V;IND;SG;1;FUT;LGSPEC1
subiecter	subiecteroient	V;COND;PL;3;LGSPEC1
desnouer	desnouerois	V;COND;SG;1;LGSPEC1
estrangler	estranglerons	V;IND;PL;1;FUT
suffocquer	suffocquasse	V;IPFV;SBJV;SG;1;PST
cerchier	cerchieroys	V;COND;SG;2;LGSPEC2
esprouver	esprouvons	V;SBJV;PL;1;PRS
desarmer	desarment	V;SBJV;PL;3;PRS
despencer	despençois	V;IPFV;IND;SG;1;PST;LGSPEC1
marier	marioient	V;IPFV;IND;PL;3;PST;LGSPEC1
provocquer	provocques	V;IND;SG;2;PRS
endommaiger	endommaigeroyent	V;COND;PL;3;LGSPEC2
baptiser	baptisez	V;IMP;PL;2
amadouer	amadouast	V;IPFV;SBJV;SG;3;PST
veigler	veigle	V;SBJV;SG;3;PRS
desploier	desploieroyt	V;COND;SG;3;LGSPEC2
accepter	acceptez	V;SBJV;PL;2;PRS
chanter	chanterois	V;COND;SG;2;LGSPEC1
rebarber	rebarberas	V;IND;SG;2;FUT
contreroller	contrerolles	V;IND;SG;2;PRS
confesser	confesserois	V;COND;SG;1;LGSPEC1
pryer	pryons	V;SBJV;PL;1;PRS
invader	invadyez	V;IPFV;IND;PL;2;PST;LGSPEC2
avanchier	avanchierois	V;COND;SG;1;LGSPEC1
geller	gellerez	V;IND;PL;2;FUT
alterer	alterons	V;IMP;PL;1
achapter	achapteroient	V;COND;PL;3;LGSPEC1
resumer	resumerai	V;IND;SG;1;FUT;LGSPEC1
pisser	pisserois	V;COND;SG;2;LGSPEC1
ployer	ployasses	V;IPFV;SBJV;SG;2;PST
conquester	conquestasses	V;IPFV;SBJV;SG;2;PST
desrouter	desroute	V;SBJV;SG;3;PRS
prier	prierois	V;COND;SG;1;LGSPEC1
esguarer	esguareras	V;IND;SG;2;FUT
veiller	veilleroys	V;COND;SG;2;LGSPEC2
dampner	dampnerez	V;IND;PL;2;FUT
empenser	empenseroyent	V;COND;PL;3;LGSPEC2
aloser	alose	V;SBJV;SG;1;PRS
affamer	affamassent	V;IPFV;SBJV;PL;3;PST
explicquer	explicquas	V;PFV;IND;SG;2;PST
superseder	supersedastes	V;PFV;IND;PL;2;PST
trembler	tremble	V;SBJV;SG;1;PRS
expuyser	expuysent	V;IND;PL;3;PRS
buchier	buchassiez	V;IPFV;SBJV;PL;2;PST
prier	priois	V;IPFV;IND;SG;2;PST;LGSPEC1
reserver	reserverons	V;IND;PL;1;FUT
assieger	assiegerois	V;COND;SG;2;LGSPEC1
habiter	habiteront	V;IND;PL;3;FUT
pourpenser	pourpenseras	V;IND;SG;2;FUT
aquitter	aquittions	V;IPFV;IND;PL;1;PST;LGSPEC1
resister	resisterois	V;COND;SG;2;LGSPEC1
amer	amerent	V;PFV;IND;PL;3;PST
aracher	arachoit	V;IPFV;IND;SG;3;PST;LGSPEC1
fiancer	fianceroient	V;COND;PL;3;LGSPEC1
resver	resve	V;IND;SG;3;PRS
explorer	exploroyent	V;IPFV;IND;PL;3;PST;LGSPEC2
cesser	cesserois	V;COND;SG;2;LGSPEC1
trancher	trancherez	V;IND;PL;2;FUT
gouverner	gouvernassions	V;IPFV;SBJV;PL;1;PST
rappeller	rappellas	V;PFV;IND;SG;2;PST
arrengier	arrenges	V;SBJV;SG;2;PRS
escumer	escumerois	V;COND;SG;2;LGSPEC1
mulcter	mulcteroyent	V;COND;PL;3;LGSPEC2
desrouter	desrouteroyent	V;COND;PL;3;LGSPEC2
oultrager	oultrages	V;IND;SG;2;PRS
quitter	quittons	V;IND;PL;1;PRS
logier	logieroys	V;COND;SG;2;LGSPEC2
desguiser	desguiseroys	V;COND;SG;2;LGSPEC2
pourmener	pourmeneroyent	V;COND;PL;3;LGSPEC2
quester	questerions	V;COND;PL;1;LGSPEC1
emprunter	emprunterions	V;COND;PL;1;LGSPEC1
esmerveillier	esmerveilloys	V;IPFV;IND;SG;1;PST;LGSPEC2
solliciter	solliciteriez	V;COND;PL;2;LGSPEC1
confesser	confessast	V;IPFV;SBJV;SG;3;PST
approuchier	approuchastes	V;PFV;IND;PL;2;PST
desmettre	desmis	V;PFV;IND;SG;2;PST
frapper	frapperoient	V;COND;PL;3;LGSPEC1
donner	donnez	V;IMP;PL;2
supposer	supposerai	V;IND;SG;1;FUT;LGSPEC1
essayer	essayoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
contreroller	contrerolloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
impugner	impugneroient	V;COND;PL;3;LGSPEC1
tumber	tumbasmes	V;PFV;IND;PL;1;PST
translater	translateroys	V;COND;SG;2;LGSPEC2
excuser	excusoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
esveigler	esveigleroient	V;COND;PL;3;LGSPEC1
fomenter	fomentyons	V;IPFV;IND;PL;1;PST;LGSPEC2
voller	vollent	V;SBJV;PL;3;PRS
amer	ameryons	V;COND;PL;1;LGSPEC2
tuer	tueroys	V;COND;SG;2;LGSPEC2
confermer	conferment	V;SBJV;PL;3;PRS
ozer	ozeroit	V;COND;SG;3;LGSPEC1
manger	mangeastes	V;PFV;IND;PL;2;PST
honnourer	honnoureroys	V;COND;SG;1;LGSPEC2
baptizer	baptizeroit	V;COND;SG;3;LGSPEC1
heurter	heurtent	V;IND;PL;3;PRS
despouiller	despouillerent	V;PFV;IND;PL;3;PST
pryer	pryyez	V;IPFV;IND;PL;2;PST;LGSPEC2
enpoisonner	enpoisonnassiez	V;IPFV;SBJV;PL;2;PST
besoinger	besoigneront	V;IND;PL;3;FUT
baiser	baisyons	V;IPFV;IND;PL;1;PST;LGSPEC2
oultrager	oultragent	V;SBJV;PL;3;PRS
gaspiller	gaspillez	V;IND;PL;2;PRS
consyderer	consydera	V;PFV;IND;SG;3;PST
besoinger	besoignes	V;IND;SG;2;PRS
esgaler	esgalasses	V;IPFV;SBJV;SG;2;PST
effronter	effrontoys	V;IPFV;IND;SG;2;PST;LGSPEC2
armoier	armoia	V;PFV;IND;SG;1;PST
estoffer	estofferoyt	V;COND;SG;3;LGSPEC2
combiner	combinoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
cabasser	cabassoient	V;IPFV;IND;PL;3;PST;LGSPEC1
occurrer	occurryez	V;IPFV;IND;PL;2;PST;LGSPEC2
prier	prieryez	V;COND;PL;2;LGSPEC2
possesser	possessoys	V;IPFV;IND;SG;1;PST;LGSPEC2
gangler	ganglas	V;PFV;IND;SG;2;PST
praeparer	praeparoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
hebergier	hebergieront	V;IND;PL;3;FUT
escorner	escorneroyt	V;COND;SG;3;LGSPEC2
tabuster	tabustois	V;IPFV;IND;SG;1;PST;LGSPEC1
lurrer	lurrerez	V;IND;PL;2;FUT
eschieller	esciellent	V;IND;PL;3;PRS
estimer	estimoit	V;IPFV;IND;SG;3;PST;LGSPEC1
descouchier	descouchierois	V;COND;SG;2;LGSPEC1
desloger	deslogez	V;IND;PL;2;PRS
executer	executa	V;PFV;IND;SG;3;PST
garder	gardast	V;IPFV;SBJV;SG;3;PST
cerchier	cerchieryons	V;COND;PL;1;LGSPEC2
hacher	hacheryons	V;COND;PL;1;LGSPEC2
tremper	tremperoyent	V;COND;PL;3;LGSPEC2
empescher	empescheroient	V;COND;PL;3;LGSPEC1
tremper	trempera	V;IND;SG;3;FUT
accointer	accointons	V;IMP;PL;1
laisser	laisseryons	V;COND;PL;1;LGSPEC2
mulcter	mulcterois	V;COND;SG;2;LGSPEC1
cesser	cessons	V;IMP;PL;1
getter	gettasse	V;IPFV;SBJV;SG;1;PST
explicquer	explicquasse	V;IPFV;SBJV;SG;1;PST
lurrer	lurrerions	V;COND;PL;1;LGSPEC1
desployer	desployasses	V;IPFV;SBJV;SG;2;PST
herrier	herriez	V;SBJV;PL;2;PRS
singler	singlons	V;SBJV;PL;1;PRS
pasturer	pasture	V;SBJV;SG;3;PRS
soingner	soingnerent	V;PFV;IND;PL;3;PST
eviter	eviterions	V;COND;PL;1;LGSPEC1
songer	songeons	V;IMP;PL;1
pacquer	pacquoyent	V;IPFV;IND;PL;3;PST;LGSPEC2
achapter	achaptassiez	V;IPFV;SBJV;PL;2;PST
gaspiller	gaspillas	V;PFV;IND;SG;2;PST
proteger	protegyez	V;IPFV;IND;PL;2;PST;LGSPEC2
fascher	fasche	V;IND;SG;3;PRS
celer	celez	V;IND;PL;2;PRS
derver	dervyez	V;IPFV;IND;PL;2;PST;LGSPEC2
avanchier	avanchiez	V;IPFV;IND;PL;2;PST;LGSPEC1
subiuger	subiugions	V;IPFV;IND;PL;1;PST;LGSPEC1
enconvenencier	enconvenencieroient	V;COND;PL;3;LGSPEC1
trembler	trembleroys	V;COND;SG;2;LGSPEC2
rebarber	rebarberoys	V;COND;SG;2;LGSPEC2
deschevaucher	deschevauchoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
geller	gellons	V;SBJV;PL;1;PRS
subiecter	subiectez	V;SBJV;PL;2;PRS
fortiffier	fortiffiois	V;IPFV;IND;SG;1;PST;LGSPEC1
frapper	frapperois	V;COND;SG;1;LGSPEC1
exstirper	exstirperez	V;IND;PL;2;FUT
heurter	heurtes	V;SBJV;SG;2;PRS
ieuner	ieunent	V;SBJV;PL;3;PRS
trembler	tremblerez	V;IND;PL;2;FUT
atempter	atempteras	V;IND;SG;2;FUT
fortiffier	fortiffies	V;IND;SG;2;PRS
supposer	supposent	V;IND;PL;3;PRS
plaider	plaiderois	V;COND;SG;1;LGSPEC1
estoffer	estoffons	V;IND;PL;1;PRS
fiancer	fiançois	V;IPFV;IND;SG;1;PST;LGSPEC1
aquitter	aquitterois	V;COND;SG;1;LGSPEC1
diviner	divinons	V;SBJV;PL;1;PRS
abandonner	abandonnoient	V;IPFV;IND;PL;3;PST;LGSPEC1
remonstrer	remonstre	V;SBJV;SG;1;PRS
subiuger	subiugeois	V;IPFV;IND;SG;1;PST;LGSPEC1
remerquer	remerquer	V;NFIN
accompaigner	accompaigne	V;SBJV;SG;1;PRS
allaicter	allaictassent	V;IPFV;SBJV;PL;3;PST
vengier	vengyons	V;IPFV;IND;PL;1;PST;LGSPEC2
superseder	supersederons	V;IND;PL;1;FUT
combiner	combines	V;IND;SG;2;PRS
contrepoiser	contrepoises	V;SBJV;SG;2;PRS
baptizer	baptizerois	V;COND;SG;2;LGSPEC1
esgarer	esgares	V;IND;SG;2;PRS
avoir	avez	V;IND;PL;2;PRS
confermer	confermassiez	V;IPFV;SBJV;PL;2;PST
veigler	veigleroit	V;COND;SG;3;LGSPEC1
descouchier	descouchastes	V;PFV;IND;PL;2;PST
fortifier	fortifiyez	V;IPFV;IND;PL;2;PST;LGSPEC2
expuyser	expuyser	V;NFIN
offencer	offencent	V;IND;PL;3;PRS
consyderer	consyderons	V;SBJV;PL;1;PRS
soubhaitter	soubhaittons	V;IMP;PL;1
despouiller	despouillent	V;SBJV;PL;3;PRS
combiner	combinyons	V;IPFV;IND;PL;1;PST;LGSPEC2
pourforcer	pourforça	V;PFV;IND;SG;3;PST
demesler	demesloyt	V;IPFV;IND;SG;3;PST;LGSPEC2
tourmenter	tourmenterions	V;COND;PL;1;LGSPEC1
foetter	foettions	V;IPFV;IND;PL;1;PST;LGSPEC1
abayer	abayions	V;IPFV;IND;PL;1;PST;LGSPEC1
dilater	dilatoys	V;IPFV;IND;SG;1;PST;LGSPEC2
penetrer	penetrerions	V;COND;PL;1;LGSPEC1
escouter	escoutassiez	V;IPFV;SBJV;PL;2;PST
seeller	seellassiez	V;IPFV;SBJV;PL;2;PST
estourdir	estourdiras	V;IND;SG;2;FUT
blesser	blesse	V;SBJV;SG;3;PRS
iouer	ioueront	V;IND;PL;3;FUT
esloigner	esloignera	V;IND;SG;3;FUT
toucher	touchons	V;IMP;PL;1
ozer	ozons	V;IND;PL;1;PRS
esmayer	esmaya	V;PFV;IND;SG;1;PST
marier	mariois	V;IPFV;IND;SG;2;PST;LGSPEC1
chercher	cherchez	V;IMP;PL;2
estre	seriez	V;COND;PL;2
tumber	tumba	V;PFV;IND;SG;1;PST
pecher	pecha	V;PFV;IND;SG;1;PST
engroisser	engroissoys	V;IPFV;IND;SG;2;PST;LGSPEC2
coniecturer	coniecturerai	V;IND;SG;1;FUT;LGSPEC1
recorder	recordasses	V;IPFV;SBJV;SG;2;PST
inviter	inviterez	V;IND;PL;2;FUT
vuider	vuideroit	V;COND;SG;3;LGSPEC1
perser	perserois	V;COND;SG;1;LGSPEC1
adiouster	adioustastes	V;PFV;IND;PL;2;PST
enconvenencier	enconvenençois	V;IPFV;IND;SG;1;PST;LGSPEC1
habiter	habitasmes	V;PFV;IND;PL;1;PST
pourpenser	pourpensa	V;PFV;IND;SG;3;PST
buchier	buchiez	V;IND;PL;2;PRS
donner	donnoys	V;IPFV;IND;SG;2;PST;LGSPEC2
penser	penseroys	V;COND;SG;1;LGSPEC2
enpoisonner	enpoisonneryez	V;COND;PL;2;LGSPEC2
mercyer	mercyoient	V;IPFV;IND;PL;3;PST;LGSPEC1
enpoisonner	enpoisonnoyt	V;IPFV;IND;SG;3;PST;LGSPEC2
buchier	buchieray	V;IND;SG;1;FUT;LGSPEC2
abiurer	abiuroys	V;IPFV;IND;SG;2;PST;LGSPEC2
trouver	trouveroyt	V;COND;SG;3;LGSPEC2
subiuger	subiugeons	V;IND;PL;1;PRS
quitter	quitteray	V;IND;SG;1;FUT;LGSPEC2
provocquer	provocquer	V;NFIN
estre	fusses	V;IPFV;SBJV;SG;2;PST
intoxiquer	intoxiquons	V;SBJV;PL;1;PRS
esguiser	esguisyons	V;IPFV;IND;PL;1;PST;LGSPEC2
esvertuer	esvertuast	V;IPFV;SBJV;SG;3;PST
mescler	mesclassiez	V;IPFV;SBJV;PL;2;PST
eriger	erigeriez	V;COND;PL;2;LGSPEC1
importuner	importunerai	V;IND;SG;1;FUT;LGSPEC1
grapper	grappiez	V;IPFV;IND;PL;2;PST;LGSPEC1
endommaiger	endommaigeryez	V;COND;PL;2;LGSPEC2
desployer	desployes	V;SBJV;SG;2;PRS
hacher	hachoit	V;IPFV;IND;SG;3;PST;LGSPEC1
demonstrer	demonstre	V;SBJV;SG;1;PRS
negotier	negoties	V;IND;SG;2;PRS
appareiller	appareilla	V;PFV;IND;SG;3;PST
donner	donneroit	V;COND;SG;3;LGSPEC1
hostoier	hostoions	V;SBJV;PL;1;PRS
desprisonner	desprisonnons	V;SBJV;PL;1;PRS
demander	demanda	V;PFV;IND;SG;1;PST
prattiquer	prattiqueryons	V;COND;PL;1;LGSPEC2
escumer	escume	V;SBJV;SG;3;PRS
tromper	tromperent	V;PFV;IND;PL;3;PST
estacher	estachas	V;PFV;IND;SG;2;PST
ymaginer	ymaginoys	V;IPFV;IND;SG;1;PST;LGSPEC2
trembler	tremblyons	V;IPFV;IND;PL;1;PST;LGSPEC2
pisser	pissasses	V;IPFV;SBJV;SG;2;PST
enconvenencier	enconvenence	V;IMP;SG;2
mercyer	mercyerions	V;COND;PL;1;LGSPEC1
superseder	supersedasses	V;IPFV;SBJV;SG;2;PST
tesmoigner	tesmoigne	V;SBJV;SG;3;PRS
assister	assisteroyt	V;COND;SG;3;LGSPEC2
monstrer	monstrons	V;SBJV;PL;1;PRS
entrefaire	entreferont	V;IND;PL;3;FUT
songer	songeasse	V;IPFV;SBJV;SG;1;PST
