nødvendighed	nødvendighed	N;NOM;INDF;SG
komponist	komponister	N;NOM;INDF;PL
reparere	reparerer	V;IND;PRS;ACT
ærme	ærmets	N;NOM;DEF;SG
pattedyr	pattedyr	N;NOM;INDF;PL
metallurg	metallurgs	N;GEN;INDF;SG
gondol	gondolen	N;NOM;DEF;SG
hånd	håndens	N;NOM;DEF;SG
sennep	senneppers	N;GEN;INDF;PL
kolos	kolossens	N;NOM;DEF;SG
resistor	resistorer	N;NOM;INDF;PL
vandringsmand	vandringsmands	N;GEN;INDF;SG
udgift	udgifterne	N;NOM;DEF;PL
menu	menuer	N;NOM;INDF;PL
navneord	navneords	N;GEN;INDF;SG
hare	harernes	N;NOM;DEF;PL
proscenium	prosceniets	N;NOM;DEF;SG
trækharmonika	trækharmonikaerne	N;NOM;DEF;PL
lejlighed	lejlighedens	N;NOM;DEF;SG
fodboldspiller	fodboldspiller	N;NOM;INDF;SG
brændstof	brændstoffer	N;NOM;INDF;PL
sejr	sejr	N;NOM;INDF;SG
professionshøjskole	professionshøjskoles	N;GEN;INDF;SG
reservere	reservere	V;NFIN;ACT
republik	republikkerne	N;NOM;DEF;PL
desavouere	desavouerende	V.PTCP;PRS;ACT
påmindelse	påmindelsernes	N;NOM;DEF;PL
tøsedreng	tøsedrengens	N;NOM;DEF;SG
e-mail	e-mails	N;GEN;INDF;PL
faster	fasters	N;GEN;INDF;SG
kraveben	kraveben	N;NOM;INDF;SG
debat	debatternes	N;NOM;DEF;PL
ven	venner	N;NOM;INDF;PL
brugerdiskussionsside	brugerdiskussionssider	N;NOM;INDF;PL
sennep	senneppen	N;NOM;DEF;SG
harekilling	harekillingens	N;NOM;DEF;SG
ørn	ørn	N;NOM;INDF;SG
føderation	føderationers	N;GEN;INDF;PL
apropos	aproposer	N;NOM;INDF;PL
babylift	babyliftens	N;NOM;DEF;SG
marked	markeder	N;NOM;INDF;PL
analfabet	analfabeter	N;NOM;INDF;PL
sortering	sorteringen	N;NOM;DEF;SG
ludder	ludder	N;NOM;INDF;SG
solsort	solsorts	N;GEN;INDF;SG
mandfolk	mandfolk	N;NOM;INDF;SG
videnskabsmand	videnskabsmænds	N;GEN;INDF;PL
hustru	hustruerne	N;NOM;DEF;PL
smiley	smileyernes	N;NOM;DEF;PL
trubadour	trubadour	N;NOM;INDF;SG
malle	maller	N;NOM;INDF;PL
kategori	kategorierne	N;NOM;DEF;PL
fatamorgana	fatamorganaets	N;NOM;DEF;SG
stør	størs	N;GEN;INDF;SG
riste	ristedes	V;IND;PST;PASS
begravelse	begravelse	N;NOM;INDF;SG
vasal	vasallernes	N;NOM;DEF;PL
klassifikationsalgoritme	klassifikationsalgoritmer	N;NOM;INDF;PL
babybio	babybioernes	N;NOM;DEF;PL
ridt	ridt	N;NOM;INDF;SG
mareridt	mareridtene	N;NOM;DEF;PL
affaldskurv	affaldskurv	N;NOM;INDF;SG
ran	rans	N;GEN;INDF;PL
e-mail-adresse	e-mail-adressen	N;NOM;DEF;SG
hældning	hældning	N;NOM;INDF;SG
kommentar	kommentarerne	N;NOM;DEF;PL
slikkepot	slikkepots	N;GEN;INDF;SG
dyst	dyst	N;NOM;INDF;SG
urinal	urinalernes	N;NOM;DEF;PL
stedord	stedordet	N;NOM;DEF;SG
seng	seng	N;NOM;INDF;SG
harekilling	harekillingernes	N;NOM;DEF;PL
landskab	landskabets	N;NOM;DEF;SG
affaldsbeholder	affaldsbeholders	N;GEN;INDF;SG
chokoladekage	chokoladekagens	N;NOM;DEF;SG
tandlæge	tandlægerne	N;NOM;DEF;PL
kedel	kedlernes	N;NOM;DEF;PL
fjende	fjendens	N;NOM;DEF;SG
fest	festens	N;NOM;DEF;SG
politiker	politikernes	N;NOM;DEF;PL
liechtensteiner	liechtensteinerens	N;NOM;DEF;SG
radiobil	radiobiler	N;NOM;INDF;PL
palimpsest	palimpsestens	N;NOM;DEF;SG
græsenke	græsenkes	N;GEN;INDF;SG
hældning	hældnings	N;GEN;INDF;SG
æbleskive	æbleskive	N;NOM;INDF;SG
trug	truget	N;NOM;DEF;SG
tomat	tomater	N;NOM;INDF;PL
agnostiker	agnostiker	N;NOM;INDF;SG
tortur	torturens	N;NOM;DEF;SG
spark	sparkets	N;NOM;DEF;SG
navneord	navneordene	N;NOM;DEF;PL
vene	venes	N;GEN;INDF;SG
puffer	pufferene	N;NOM;DEF;PL
intelligensniveau	intelligensniveauer	N;NOM;INDF;PL
taxa	taxaers	N;GEN;INDF;PL
dusin	dusinene	N;NOM;DEF;PL
malke	malk	V;IMP;ACT
mængdedifferens	mængdedifferens	N;NOM;INDF;SG
mexicaner	mexicanere	N;NOM;INDF;PL
vandmand	vandmændenes	N;NOM;DEF;PL
sæbeopera	sæbeoperaers	N;GEN;INDF;PL
debut	debutens	N;NOM;DEF;SG
ror	ror	N;NOM;INDF;SG
blodtype	blodtypens	N;NOM;DEF;SG
cigaretpakke	cigaretpakkens	N;NOM;DEF;SG
suppe	supper	N;NOM;INDF;PL
abonnement	abonnementers	N;GEN;INDF;PL
oldemor	oldemors	N;GEN;INDF;SG
brystvorte	brystvorten	N;NOM;DEF;SG
kar	kar	N;NOM;INDF;SG
stad	stadens	N;NOM;DEF;SG
vaskebræt	vaskebrætters	N;GEN;INDF;PL
revisor	revisorerne	N;NOM;DEF;PL
sennep	sennep	N;NOM;INDF;SG
trækharmonika	trækharmonikaer	N;NOM;INDF;PL
mynde	myndes	N;GEN;INDF;SG
vielsesring	vielsesringes	N;GEN;INDF;PL
forbrydelse	forbrydelsernes	N;NOM;DEF;PL
slutning	slutninger	N;NOM;INDF;PL
erobre	erobres	V;IND;PRS;PASS
maskine	maskines	N;GEN;INDF;SG
abkhaser	abkhaser	N;NOM;INDF;SG
globus	globussen	N;NOM;DEF;SG
gamache	gamachernes	N;NOM;DEF;PL
desavouere	desavouerede	V;IND;PST;ACT
veranda	verandaens	N;NOM;DEF;SG
korrigere	korrigerende	V.PTCP;PRS;ACT
græsslåmaskine	græsslåmaskinens	N;NOM;DEF;SG
lillebror	lillebrorens	N;NOM;DEF;SG
guddom	guddommene	N;NOM;DEF;PL
tekniker	teknikerens	N;NOM;DEF;SG
urmager	urmagerens	N;NOM;DEF;SG
kvadrat	kvadratet	N;NOM;DEF;SG
vaffel	vaflenvaffelen	N;NOM;DEF;SG
rollemodel	rollemodellernes	N;NOM;DEF;PL
vindruekerneolie	vindruekerneolies	N;GEN;INDF;SG
araber	araber	N;NOM;INDF;SG
gamache	gamacher	N;NOM;INDF;PL
intelligenskvotient	intelligenskvotienterne	N;NOM;DEF;PL
kardinaltal	kardinaltal	N;NOM;INDF;PL
gemytlighed	gemytlighederne	N;NOM;DEF;PL
resistor	resistor	N;NOM;INDF;SG
terræn	terrænernes	N;NOM;DEF;PL
skjorte	skjortens	N;NOM;DEF;SG
broderskab	broderskaber	N;NOM;INDF;PL
pulver	pulver	N;NOM;INDF;SG
taxa	taxaer	N;NOM;INDF;PL
purere	purere	V;NFIN;ACT
ør	øren	N;NOM;DEF;SG
e-mail	e-mail	N;NOM;INDF;PL
olding	oldingen	N;NOM;DEF;SG
nonne	nonnerne	N;NOM;DEF;PL
nederdel	nederdelene	N;NOM;DEF;PL
hjord	hjorderne	N;NOM;DEF;PL
kønsord	kønsord	N;NOM;INDF;PL
akvarel	akvarel	N;NOM;INDF;SG
ven	ven	N;NOM;INDF;SG
trimester	trimesters	N;GEN;INDF;SG
tatovere	tatover	V;IMP;ACT
kanelsnegl	kanelsneglens	N;NOM;DEF;SG
alkoholiker	alkoholikerne	N;NOM;DEF;PL
signere	signerede	V;IND;PST;ACT
symbol	symboler	N;NOM;INDF;PL
radiobil	radiobils	N;GEN;INDF;SG
resistor	resistorernes	N;NOM;DEF;PL
klient	klienten	N;NOM;DEF;SG
ændringsforslag	ændringsforslags	N;GEN;INDF;SG
gravhøj	gravhøjes	N;GEN;INDF;PL
skizofreni	skizofrenien	N;NOM;DEF;SG
indflyvning	indflyvningers	N;GEN;INDF;PL
integrere	integrer	V;IMP;ACT
opgave	opgavernes	N;NOM;DEF;PL
bov	boves	N;GEN;INDF;PL
frisør	frisørens	N;NOM;DEF;SG
vejr	vejr	N;NOM;INDF;SG
seraf	serafers	N;GEN;INDF;PL
antenne	antennerne	N;NOM;DEF;PL
trumf	trumfens	N;NOM;DEF;SG
læsehest	læsehestenes	N;NOM;DEF;PL
skede	skede	N;NOM;INDF;SG
olie	oliers	N;GEN;INDF;PL
kontinent	kontinents	N;GEN;INDF;SG
sild	silds	N;GEN;INDF;SG
fedt	fedter	N;NOM;INDF;PL
hvil	hvilenes	N;NOM;DEF;PL
natklub	natklubberne	N;NOM;DEF;PL
reparere	repareres	V;IND;PRS;PASS
gudshus	gudshuses	N;GEN;INDF;PL
gnier	gniernes	N;NOM;DEF;PL
bæ	bæer	N;NOM;INDF;PL
integrere	integrerede	V;IND;PST;ACT
erobre	erobret	V.PTCP;PST;PASS
korkeg	korkegs	N;GEN;INDF;SG
ara	aras	N;GEN;INDF;SG
tyver	tyver	N;NOM;INDF;SG
dyne	dyner	N;NOM;INDF;PL
måltid	måltids	N;GEN;INDF;SG
skumring	skumringer	N;NOM;INDF;PL
drue	drue	N;NOM;INDF;SG
kedel	kedlers	N;GEN;INDF;PL
urinal	urinalerne	N;NOM;DEF;PL
pirat	piratens	N;NOM;DEF;SG
erobre	erobrende	V.PTCP;PRS;ACT
malle	mallers	N;GEN;INDF;PL
mønster	mønsters	N;GEN;INDF;SG
sultanat	sultanat	N;NOM;INDF;SG
strofe	strofen	N;NOM;DEF;SG
udråbsord	udråbsords	N;GEN;INDF;SG
tendens	tendensens	N;NOM;DEF;SG
lime	lime	N;NOM;INDF;SG
punktum	punktummets	N;NOM;DEF;SG
trommesæt	trommesættet	N;NOM;DEF;SG
sal	sals	N;GEN;INDF;SG
gondol	gondolens	N;NOM;DEF;SG
suspensorium	suspensoriers	N;GEN;INDF;PL
oldemor	oldemorens	N;NOM;DEF;SG
putte	puttes	N;GEN;INDF;SG
medie	medierne	N;NOM;DEF;PL
grunde	grundedes	V;IND;PST;PASS
smaragd	smaragders	N;GEN;INDF;PL
gedde	gedderne	N;NOM;DEF;PL
imitere	imiterede	V;IND;PST;ACT
rygte	rygter	N;NOM;INDF;PL
marked	markederne	N;NOM;DEF;PL
atomkraft	atomkraft	N;NOM;INDF;SG
frikadelle	frikadeller	N;NOM;INDF;PL
potentat	potentaterne	N;NOM;DEF;PL
palindrom	palindromet	N;NOM;DEF;SG
kobberrør	kobberrør	N;NOM;INDF;SG
abort	abort	N;NOM;INDF;SG
vinter	vintre	N;NOM;INDF;PL
sag	sagen	N;NOM;DEF;SG
babyvræl	babyvrælenes	N;NOM;DEF;PL
asteroide	asteroidernes	N;NOM;DEF;PL
operahus	operahuse	N;NOM;INDF;PL
myre	myrer	N;NOM;INDF;PL
viser	viseren	N;NOM;DEF;SG
ungarer	ungarere	N;NOM;INDF;PL
republik	republikkernes	N;NOM;DEF;PL
kokkepige	kokkepigen	N;NOM;DEF;SG
huskarl	huskarl	N;NOM;INDF;SG
urmager	urmager	N;NOM;INDF;SG
vadested	vadestedet	N;NOM;DEF;SG
lejlighed	lejligheden	N;NOM;DEF;SG
impuls	impulsens	N;NOM;DEF;SG
kilometer	kilometer	N;NOM;INDF;SG
niveau	niveauer	N;NOM;INDF;PL
esplanade	esplanaderne	N;NOM;DEF;PL
trækharmonika	trækharmonikaers	N;GEN;INDF;PL
skotte	skottens	N;NOM;DEF;SG
klapperslange	klapperslangernes	N;NOM;DEF;PL
rig	rig	N;NOM;INDF;SG
vinliste	vinlisten	N;NOM;DEF;SG
parentes	parentesens	N;NOM;DEF;SG
brøk	brøkers	N;GEN;INDF;PL
færing	færinger	N;NOM;INDF;PL
chateau	chateauets	N;NOM;DEF;SG
hjord	hjorden	N;NOM;DEF;SG
pels	pels'	N;GEN;INDF;SG
værktøj	værktøj	N;NOM;INDF;SG
loppetjans	loppetjansers	N;GEN;INDF;PL
golfkølle	golfkøllen	N;NOM;DEF;SG
kernekraft	kernekrafter	N;NOM;INDF;PL
frimærke	frimærkes	N;GEN;INDF;SG
parentes	parenteserne	N;NOM;DEF;PL
guitarist	guitarist	N;NOM;INDF;SG
kaktus	kaktusserne	N;NOM;DEF;PL
anarki	anarkierne	N;NOM;DEF;PL
glansbillede	glansbillederne	N;NOM;DEF;PL
musikproducer	musikproduceres	N;GEN;INDF;PL
anæstesi	anæstesiernes	N;NOM;DEF;PL
svækling	svæklingens	N;NOM;DEF;SG
sommerfugl	sommerfugls	N;GEN;INDF;SG
udfordring	udfordringens	N;NOM;DEF;SG
rotte	rotte	N;NOM;INDF;SG
biord	biordets	N;NOM;DEF;SG
verbum	verbets	N;NOM;DEF;SG
lår	lårets	N;NOM;DEF;SG
køretøj	køretøj	N;NOM;INDF;SG
palisade	palisade	N;NOM;INDF;SG
rabat	rabatternes	N;NOM;DEF;PL
indhøste	indhøstende	V.PTCP;PRS;ACT
thiuf	thiufænæ	N;NOM;DEF;PL
hvepsetalje	hvepsetaljer	N;NOM;INDF;PL
halskæde	halskæderne	N;NOM;DEF;PL
skandale	skandaler	N;NOM;INDF;PL
grankogle	grankoglers	N;GEN;INDF;PL
argumentere	argumenteres	V;IND;PRS;PASS
trækfugl	trækfugles	N;GEN;INDF;PL
muskel	musklen	N;NOM;DEF;SG
onkel	onkel	N;NOM;INDF;SG
majsolie	majsolie	N;NOM;INDF;SG
komiker	komikerens	N;NOM;DEF;SG
mellemnavn	mellemnavnenes	N;NOM;DEF;PL
taxa	taxaerne	N;NOM;DEF;PL
abort	aborterne	N;NOM;DEF;PL
boykot	boykots	N;GEN;INDF;SG
fjært	fjærten	N;NOM;DEF;SG
kno	knoens	N;NOM;DEF;SG
purere	purerede	V;IND;PST;ACT
mobning	mobningen	N;NOM;DEF;SG
strygejern	strygejerns	N;GEN;INDF;SG
skræl	skrællerne	N;NOM;DEF;PL
sætning	sætnings	N;GEN;INDF;SG
musikproducer	musikproducernes	N;NOM;DEF;PL
bestie	bestierne	N;NOM;DEF;PL
suffiks	suffiksers	N;GEN;INDF;PL
diskutere	diskuteret	V.PTCP;PST;PASS
klan	klaner	N;NOM;INDF;PL
produkt	produkt	N;NOM;INDF;SG
badmintonspiller	badmintonspilleren	N;NOM;DEF;SG
cellekerne	cellekernes	N;GEN;INDF;SG
gilde	gildernes	N;NOM;DEF;PL
annektering	annekteringen	N;NOM;DEF;SG
pote	poterne	N;NOM;DEF;PL
brugerdiskussionsside	brugerdiskussionssiden	N;NOM;DEF;SG
motorcyklist	motorcyklists	N;GEN;INDF;SG
dun	dun	N;NOM;INDF;PL
topograf	topograf	N;NOM;INDF;SG
ørken	ørkenersørkners	N;GEN;INDF;PL
polemik	polemikkers	N;GEN;INDF;PL
vækkeur	vækkeures	N;GEN;INDF;PL
kardinaltal	kardinaltallenes	N;NOM;DEF;PL
kalkun	kalkunerne	N;NOM;DEF;PL
rabat	rabatters	N;GEN;INDF;PL
akademiker	akademikernes	N;NOM;DEF;PL
bølgelængde	bølgelængdens	N;NOM;DEF;SG
konklusion	konklusionens	N;NOM;DEF;SG
rektor	rektorerne	N;NOM;DEF;PL
frænde	frændes	N;GEN;INDF;SG
alfahan	alfahan	N;NOM;INDF;SG
bagsæde	bagsædes	N;GEN;INDF;SG
kranse	kranses	V;IND;PRS;PASS
produkt	produktet	N;NOM;DEF;SG
juveler	juvelerer	N;NOM;INDF;PL
alligator	alligatorer	N;NOM;INDF;PL
gravhøj	gravhøjens	N;NOM;DEF;SG
kanin	kanins	N;GEN;INDF;SG
muslim	muslimers	N;GEN;INDF;PL
tankskib	tankskib	N;NOM;INDF;SG
wc	wc'et	N;NOM;DEF;SG
midtnormal	midtnormal	N;NOM;INDF;SG
kæledyr	kæledyrene	N;NOM;DEF;PL
slurk	slurkenes	N;NOM;DEF;PL
boysenbær	boysenbærs	N;GEN;INDF;PL
bestie	bestiers	N;GEN;INDF;PL
værktøj	værktøjernes	N;NOM;DEF;PL
lejlighed	lejligheds	N;GEN;INDF;SG
møbel	møbel	N;NOM;INDF;SG
blodtype	blodtype	N;NOM;INDF;SG
pastel	pastel	N;NOM;INDF;SG
diagonal	diagonalen	N;NOM;DEF;SG
golfkølle	golfkøller	N;NOM;INDF;PL
walkie-talkie	walkie-talkie	N;NOM;INDF;SG
løve	løver	N;NOM;INDF;PL
hydrolog	hydrologers	N;GEN;INDF;PL
nationalsang	nationalsangen	N;NOM;DEF;SG
harmonika	harmonika	N;NOM;INDF;SG
musikartikel	musikartikler	N;NOM;INDF;PL
rov	rovet	N;NOM;DEF;SG
riffel	rifler	N;NOM;INDF;PL
bilist	bilistens	N;NOM;DEF;SG
armbåndsur	armbåndsur	N;NOM;INDF;SG
konklusion	konklusionerne	N;NOM;DEF;PL
nødudgang	nødudgange	N;NOM;INDF;PL
operahus	operahusets	N;NOM;DEF;SG
ordklasse	ordklasses	N;GEN;INDF;SG
kar	karret	N;NOM;DEF;SG
vinliste	vinlisterne	N;NOM;DEF;PL
smiley	smileyens	N;NOM;DEF;SG
renovere	renoveres	V;IND;PRS;PASS
sadel	sadlers	N;GEN;INDF;PL
brøk	brøkerne	N;NOM;DEF;PL
drømmekage	drømmekager	N;NOM;INDF;PL
vulkan	vulkans	N;GEN;INDF;SG
repræsentation	repræsentations	N;GEN;INDF;SG
libaneser	libaneserne	N;NOM;DEF;PL
kolonialforretning	kolonialforretningernes	N;NOM;DEF;PL
ovn	ovnes	N;GEN;INDF;PL
golfspiller	golfspilleren	N;NOM;DEF;SG
suppe	suppe	N;NOM;INDF;SG
kommune	kommunernes	N;NOM;DEF;PL
papegøje	papegøje	N;NOM;INDF;SG
affaldsbeholder	affaldsbeholdernes	N;NOM;DEF;PL
biord	biordenes	N;NOM;DEF;PL
ordre	ordrernes	N;NOM;DEF;PL
blodkredsløb	blodkredsløbets	N;NOM;DEF;SG
brosten	brostenens	N;NOM;DEF;SG
sild	sild	N;NOM;INDF;SG
rombe	rombernes	N;NOM;DEF;PL
aborre	aborrers	N;GEN;INDF;PL
metafor	metaforernes	N;NOM;DEF;PL
hypnotisør	hypnotisørens	N;NOM;DEF;SG
greve	greverne	N;NOM;DEF;PL
TV-program	TV-programmets	N;NOM;DEF;SG
monark	monarkerne	N;NOM;DEF;PL
jag	jaget	N;NOM;DEF;SG
ridt	ridtene	N;NOM;DEF;PL
babysæl	babysæler	N;NOM;INDF;PL
kalksten	kalkstenene	N;NOM;DEF;PL
søjle	søjlernes	N;NOM;DEF;PL
loppetjans	loppetjans'	N;GEN;INDF;SG
sovs	sovsenes	N;NOM;DEF;PL
klapperslange	klapperslangers	N;GEN;INDF;PL
element	elementet	N;NOM;DEF;SG
ræv	rævens	N;NOM;DEF;SG
skulder	skuldres	N;GEN;INDF;PL
græsslåmaskine	græsslåmaskines	N;GEN;INDF;SG
gåsepotentil	gåsepotentillers	N;GEN;INDF;PL
tebrev	tebreves	N;GEN;INDF;PL
drys	drysset	N;NOM;DEF;SG
telt	telte	N;NOM;INDF;PL
skulptør	skulptørerne	N;NOM;DEF;PL
krokodilletåre	krokodilletårernes	N;NOM;DEF;PL
ør	ørers	N;GEN;INDF;PL
kvadratmeter	kvadratmeternes	N;NOM;DEF;PL
kammer	kamres	N;GEN;INDF;PL
remulade	remuladens	N;NOM;DEF;SG
forbrydelse	forbrydelsers	N;GEN;INDF;PL
masse	massernes	N;NOM;DEF;PL
spermatozo	spermatozoen	N;NOM;DEF;SG
ananas	ananassenes	N;NOM;DEF;PL
lyske	lyskernes	N;NOM;DEF;PL
geled	geleddet	N;NOM;DEF;SG
vaskeklud	vaskekludene	N;NOM;DEF;PL
motivation	motivationens	N;NOM;DEF;SG
supermagt	supermagten	N;NOM;DEF;SG
palimpsest	palimpsester	N;NOM;INDF;PL
kanelsnegl	kanelsneglene	N;NOM;DEF;PL
knurhår	knurhåret	N;NOM;DEF;SG
pirat	pirat	N;NOM;INDF;SG
imitere	imiter	V;IMP;ACT
hvalp	hvalpe	N;NOM;INDF;PL
grotte	grotterne	N;NOM;DEF;PL
betydning	betydninger	N;NOM;INDF;PL
journalist	journalistens	N;NOM;DEF;SG
løvinde	løvindernes	N;NOM;DEF;PL
koncertina	koncertinas	N;GEN;INDF;SG
ordre	ordrens	N;NOM;DEF;SG
fjært	fjærtene	N;NOM;DEF;PL
stræde	strædes	N;GEN;INDF;SG
bil	bilens	N;NOM;DEF;SG
skuffelse	skuffelses	N;GEN;INDF;SG
hundesnor	hundesnorenes	N;NOM;DEF;PL
ædelsten	ædelstenene	N;NOM;DEF;PL
stikprøve	stikprøvernes	N;NOM;DEF;PL
myndighedsrepræsentant	myndighedsrepræsentant	N;NOM;INDF;SG
ed	edernes	N;NOM;DEF;PL
karakteristik	karakteristikkerne	N;NOM;DEF;PL
ytringsfrihed	ytringsfrihederne	N;NOM;DEF;PL
nitrat	nitrater	N;NOM;INDF;PL
åre	åren	N;NOM;DEF;SG
rombe	romberne	N;NOM;DEF;PL
stedord	stedordene	N;NOM;DEF;PL
vod	voddene	N;NOM;DEF;PL
smoking	smokingen	N;NOM;DEF;SG
hældning	hældningers	N;GEN;INDF;PL
pattedyr	pattedyr	N;NOM;INDF;SG
renovere	renovere	V;NFIN;ACT
navn	navn	N;NOM;INDF;SG
modulation	modulation	N;NOM;INDF;SG
urinale	urinalernes	N;NOM;DEF;PL
start	start	N;NOM;INDF;SG
stedord	stedord	N;NOM;INDF;PL
nederdel	nederdels	N;GEN;INDF;SG
fødsel	fødslers	N;GEN;INDF;PL
spøgelse	spøgelses	N;GEN;INDF;SG
sæl	sæl	N;NOM;INDF;SG
ed	eder	N;NOM;INDF;PL
chokoladekage	chokoladekage	N;NOM;INDF;SG
reje	rejen	N;NOM;DEF;SG
samleje	samlejerne	N;NOM;DEF;PL
mexicaner	mexicanernes	N;NOM;DEF;PL
kasse	kassens	N;NOM;DEF;SG
opfostre	opfostrende	V.PTCP;PRS;ACT
mobning	mobningernes	N;NOM;DEF;PL
muffe	muffernes	N;NOM;DEF;PL
navle	navle	N;NOM;INDF;SG
sektor	sektoren	N;NOM;DEF;SG
kardinaltal	kardinaltal	N;NOM;INDF;SG
buste	busternes	N;NOM;DEF;PL
løb	løbs	N;GEN;INDF;PL
niveau	niveauets	N;NOM;DEF;SG
golfbane	golfbanernes	N;NOM;DEF;PL
canadier	canadier	N;NOM;INDF;SG
intelligentsia	intelligentsiaens	N;NOM;DEF;SG
bogorm	bogormene	N;NOM;DEF;PL
journalist	journalist	N;NOM;INDF;SG
time	timerne	N;NOM;DEF;PL
julelys	julelys'	N;GEN;INDF;PL
gravhøj	gravhøje	N;NOM;INDF;PL
nytår	nytårenes	N;NOM;DEF;PL
dandere	danderede	V;IND;PST;ACT
TV-program	TV-programmerne	N;NOM;DEF;PL
lime	lime	N;NOM;INDF;PL
søster	søster	N;NOM;INDF;SG
kulstofkredsløb	kulstofkredsløbet	N;NOM;DEF;SG
pincet	pincets	N;GEN;INDF;SG
ærme	ærme	N;NOM;INDF;SG
pibe	piben	N;NOM;DEF;SG
ged	gedernes	N;NOM;DEF;PL
småbarn	småbørn	N;NOM;INDF;PL
troubadour	troubadourens	N;NOM;DEF;SG
esplanade	esplanaden	N;NOM;DEF;SG
ærkeengel	ærkeenglene	N;NOM;DEF;PL
ærme	ærmer	N;NOM;INDF;PL
svend	svenden	N;NOM;DEF;SG
stør	størenes	N;NOM;DEF;PL
fest	fests	N;GEN;INDF;SG
database	databasers	N;GEN;INDF;PL
element	element	N;NOM;INDF;SG
besked	beskedernes	N;NOM;DEF;PL
sofavælger	sofavælgere	N;NOM;INDF;PL
vindruekerneolie	vindruekerneoliens	N;NOM;DEF;SG
intelligenstestning	intelligenstestninger	N;NOM;INDF;PL
fremmedord	fremmedordenes	N;NOM;DEF;PL
omvej	omvejens	N;NOM;DEF;SG
papegøje	papegøjers	N;GEN;INDF;PL
broccoli	broccolis	N;GEN;INDF;SG
kokosnød	kokosnøddens	N;NOM;DEF;SG
overvågningsliste	overvågningslisters	N;GEN;INDF;PL
kasserolle	kasserolles	N;GEN;INDF;SG
troubadour	troubadourernes	N;NOM;DEF;PL
kvadratmeter	kvadratmeterne	N;NOM;DEF;PL
egern	egernet	N;NOM;DEF;SG
bæ	bæers	N;GEN;INDF;PL
føn	føns	N;GEN;INDF;SG
greve	greven	N;NOM;DEF;SG
klaviatur	klaviaturs	N;GEN;INDF;SG
rosin	rosinen	N;NOM;DEF;SG
antenne	antennernes	N;NOM;DEF;PL
abonnement	abonnementets	N;NOM;DEF;SG
verbum	verbum	N;NOM;INDF;SG
solbær	solbærrets	N;NOM;DEF;SG
statue	statuers	N;GEN;INDF;PL
konfiskere	konfisker	V;IMP;ACT
alkan	alkaner	N;NOM;INDF;PL
babyboom	babybooms	N;GEN;INDF;SG
hovedpulsåre	hovedpulsårer	N;NOM;INDF;PL
tæppe	tæpper	N;NOM;INDF;PL
skuffelse	skuffelsens	N;NOM;DEF;SG
solsort	solsorters	N;GEN;INDF;PL
laste	lastet	V.PTCP;PST;PASS
afgrøde	afgrødes	N;GEN;INDF;SG
ræv	ræve	N;NOM;INDF;PL
istap	istapper	N;NOM;INDF;PL
æbleskive	æbleskivernes	N;NOM;DEF;PL
tante	tantens	N;NOM;DEF;SG
solsort	solsorter	N;NOM;INDF;PL
wc	wc'ernes	N;NOM;DEF;PL
buste	bustes	N;GEN;INDF;SG
udgang	udgangen	N;NOM;DEF;SG
troubadur	troubadurerne	N;NOM;DEF;PL
bordlampe	bordlamper	N;NOM;INDF;PL
lagen	lagen	N;NOM;INDF;SG
symbol	symbolets	N;NOM;DEF;SG
operahus	operahus	N;NOM;INDF;SG
fugl	fuglenes	N;NOM;DEF;PL
horkarl	horkarles	N;GEN;INDF;PL
størrelse	størrelsens	N;NOM;DEF;SG
verballed	verballeddene	N;NOM;DEF;PL
debat	debatter	N;NOM;INDF;PL
mellemnavn	mellemnavnes	N;GEN;INDF;PL
trubadur	trubaduren	N;NOM;DEF;SG
syl	sylene	N;NOM;DEF;PL
gnom	gnomers	N;GEN;INDF;PL
fremmedord	fremmedords	N;GEN;INDF;SG
spøgelse	spøgelsernes	N;NOM;DEF;PL
mp3-afspiller	mp3-afspillernes	N;NOM;DEF;PL
babyboom	babyboomets	N;NOM;DEF;SG
onkel	onklernes	N;NOM;DEF;PL
salte	saltende	V.PTCP;PRS;ACT
eddike	eddiker	N;NOM;INDF;PL
overskæg	overskæg	N;NOM;INDF;SG
strømstyrke	strømstyrkes	N;GEN;INDF;SG
marked	markedernes	N;NOM;DEF;PL
las	lasers	N;GEN;INDF;PL
brillant	brillants	N;GEN;INDF;SG
flynder	flynderens	N;NOM;DEF;SG
pegefinger	pegefingrenes	N;NOM;DEF;PL
abyssinier	abyssiniere	N;NOM;INDF;PL
påmindelse	påmindelse	N;NOM;INDF;SG
avokado	avokadoer	N;NOM;INDF;PL
anæstesi	anæstesi	N;NOM;INDF;SG
kælenavn	kælenavnet	N;NOM;DEF;SG
massefylde	massefylders	N;GEN;INDF;PL
århusianer	århusianere	N;NOM;INDF;PL
ståsted	ståsteds	N;GEN;INDF;SG
datid	datiderne	N;NOM;DEF;PL
effekt	effektens	N;NOM;DEF;SG
søster	søsteren	N;NOM;DEF;SG
polemik	polemikken	N;NOM;DEF;SG
vinter	vintrene	N;NOM;DEF;PL
trappe	trappens	N;NOM;DEF;SG
ara	araens	N;NOM;DEF;SG
cirkelafsnit	cirkelafsnits	N;GEN;INDF;SG
kaffebønne	kaffebønners	N;GEN;INDF;PL
remulade	remuladernes	N;NOM;DEF;PL
kommunist	kommunist	N;NOM;INDF;SG
håndboldspiller	håndboldspillerenes	N;NOM;DEF;PL
etymologi	etymologiernes	N;NOM;DEF;PL
søndag	søndagene	N;NOM;DEF;PL
vandbakkelse	vandbakkelses	N;GEN;INDF;SG
reagensglas	reagensglas'	N;GEN;INDF;PL
kaffebønne	kaffebønnernes	N;NOM;DEF;PL
ytringsfrihed	ytringsfriheds	N;GEN;INDF;SG
rosin	rosinens	N;NOM;DEF;SG
putte	putte	N;NOM;INDF;SG
tøsedreng	tøsedrengenes	N;NOM;DEF;PL
annektering	annekteringers	N;GEN;INDF;PL
kolos	kolos'	N;GEN;INDF;SG
verballed	verballed	N;NOM;INDF;PL
univers	universers	N;GEN;INDF;PL
høst	høst	N;NOM;INDF;SG
gab	gab	N;NOM;INDF;PL
karisma	karismaers	N;GEN;INDF;PL
kobberrør	kobberrørenes	N;NOM;DEF;PL
skuespil	skuespillenes	N;NOM;DEF;PL
musikvideo	musikvideoer	N;NOM;INDF;PL
intimidere	intimiderer	V;IND;PRS;ACT
hyæne	hyænernes	N;NOM;DEF;PL
børnesygdom	børnesygdommes	N;GEN;INDF;PL
narkoman	narkomanen	N;NOM;DEF;SG
globus	globus	N;NOM;INDF;SG
mannequin	mannequinens	N;NOM;DEF;SG
interjektion	interjektionernes	N;NOM;DEF;PL
terrasse	terrassers	N;GEN;INDF;PL
syl	sylen	N;NOM;DEF;SG
strømstyrke	strømstyrker	N;NOM;INDF;PL
andrik	andrikkerne	N;NOM;DEF;PL
tolvfingertarm	tolvfingertarmens	N;NOM;DEF;SG
skuffelse	skuffelsers	N;GEN;INDF;PL
læsehest	læsehestene	N;NOM;DEF;PL
reje	rejens	N;NOM;DEF;SG
hornhinde	hornhinders	N;GEN;INDF;PL
lime	limenes	N;NOM;DEF;PL
mafia	mafiaen	N;NOM;DEF;SG
olivenolie	olivenolies	N;GEN;INDF;SG
kno	kno	N;NOM;INDF;SG
pulver	pulveret	N;NOM;DEF;SG
lund	lundenes	N;NOM;DEF;PL
eskadrille	eskadrillen	N;NOM;DEF;SG
kryds	krydsene	N;NOM;DEF;PL
kolibri	kolibriens	N;NOM;DEF;SG
assimilere	assimilerede	V;IND;PST;ACT
palimpsest	palimpsest	N;NOM;INDF;SG
knæ	knæs	N;GEN;INDF;SG
skåning	skåningens	N;NOM;DEF;SG
yndling	yndlinges	N;GEN;INDF;PL
babyble	babybleer	N;NOM;INDF;PL
komponist	komponisternes	N;NOM;DEF;PL
skede	skeden	N;NOM;DEF;SG
smed	smeds	N;GEN;INDF;SG
gamache	gamaches	N;GEN;INDF;SG
art	art	N;NOM;INDF;SG
bæ	bæen	N;NOM;DEF;SG
mareridt	mareridts	N;GEN;INDF;SG
betaling	betalingers	N;GEN;INDF;PL
karakal	karakalens	N;NOM;DEF;SG
pålæg	pålægs	N;GEN;INDF;PL
kuffert	kufferters	N;GEN;INDF;PL
børnesygdom	børnesygdommen	N;NOM;DEF;SG
flange	flangers	N;GEN;INDF;PL
udgift	udgifter	N;NOM;INDF;PL
jubilæum	jubilæer	N;NOM;INDF;PL
kasse	kasse	N;NOM;INDF;SG
tenor	tenorerne	N;NOM;DEF;PL
ambolt	ambolts	N;GEN;INDF;SG
skulptur	skulpturens	N;NOM;DEF;SG
nyre	nyrens	N;NOM;DEF;SG
svensker	svenskerne	N;NOM;DEF;PL
rollemodel	rollemodellen	N;NOM;DEF;SG
kanapé	kanapé	N;NOM;INDF;SG
mage	mager	N;NOM;INDF;PL
glimt	glimt	N;NOM;INDF;SG
klovn	klovns	N;GEN;INDF;SG
hind	hinder	N;NOM;INDF;PL
bondegård	bondegårdenes	N;NOM;DEF;PL
horkarl	horkarlene	N;NOM;DEF;PL
effekt	effekterne	N;NOM;DEF;PL
skumring	skumrings	N;GEN;INDF;SG
vejr	vejrenes	N;NOM;DEF;PL
røn	røns	N;GEN;INDF;SG
trækharmonika	trækharmonikaernes	N;NOM;DEF;PL
grotte	grotter	N;NOM;INDF;PL
aktivitet	aktiviteters	N;GEN;INDF;PL
halvmåne	halvmånens	N;NOM;DEF;SG
system	systemerne	N;NOM;DEF;PL
gamer	gameres	N;GEN;INDF;PL
ludder	ludders	N;GEN;INDF;SG
cigaretetui	cigaretetuiernes	N;NOM;DEF;PL
babylonier	babylonieres	N;GEN;INDF;PL
parentes	parenteser	N;NOM;INDF;PL
bestie	bestier	N;NOM;INDF;PL
værktøj	værktøjets	N;NOM;DEF;SG
ambra	ambras	N;GEN;INDF;SG
solbær	solbær	N;NOM;INDF;PL
kategori	kategoris	N;GEN;INDF;SG
statue	statues	N;GEN;INDF;SG
ananas	ananas'	N;GEN;INDF;PL
narkoman	narkomans	N;GEN;INDF;SG
mundharpe	mundharperne	N;NOM;DEF;PL
ophavsgruppe	ophavsgruppe	N;NOM;INDF;SG
konference	konferencers	N;GEN;INDF;PL
venlighed	venlighed	N;NOM;INDF;SG
bibel	bibler	N;NOM;INDF;PL
drys	dryssene	N;NOM;DEF;PL
globe	globers	N;GEN;INDF;PL
karakal	karakalerne	N;NOM;DEF;PL
rombe	rombes	N;GEN;INDF;SG
fedt	fedternes	N;NOM;DEF;PL
helgen	helgener	N;NOM;INDF;PL
kiste	kisternes	N;NOM;DEF;PL
gilde	gilde	N;NOM;INDF;SG
fremtid	fremtiderne	N;NOM;DEF;PL
tendens	tendens	N;NOM;INDF;SG
sofa	sofaerne	N;NOM;DEF;PL
anarki	anarkiers	N;GEN;INDF;PL
beholder	beholderen	N;NOM;DEF;SG
albino	albinoer	N;NOM;INDF;PL
ludder	ludderens	N;NOM;DEF;SG
kødspiser	kødspiseres	N;GEN;INDF;PL
pengeseddel	pengesedler	N;NOM;INDF;PL
kriterium	kriteriet	N;NOM;DEF;SG
knarr	knarrens	N;NOM;DEF;SG
kaskelothval	kaskelothval	N;NOM;INDF;SG
øreflip	øreflippen	N;NOM;DEF;SG
sulfat	sulfaterne	N;NOM;DEF;PL
busk	buskes	N;GEN;INDF;PL
mobning	mobningers	N;GEN;INDF;PL
repræsentation	repræsentationens	N;NOM;DEF;SG
kontaktperson	kontaktpersonerne	N;NOM;DEF;PL
englænder	englænderen	N;NOM;DEF;SG
benzinstation	benzinstationers	N;GEN;INDF;PL
knurhår	knurhår	N;NOM;INDF;SG
papegøje	papegøjes	N;GEN;INDF;SG
lokomotiv	lokomotiv	N;NOM;INDF;SG
mafia	mafiaerne	N;NOM;DEF;PL
proscenium	prosceniernes	N;NOM;DEF;PL
horrorfilm	horrorfilmen	N;NOM;DEF;SG
affaldsbeholder	affaldsbeholderens	N;NOM;DEF;SG
suspensorium	suspensorierne	N;NOM;DEF;PL
måltid	måltider	N;NOM;INDF;PL
golfspiller	golfspilleres	N;GEN;INDF;PL
musikartikel	musikartiklens	N;NOM;DEF;SG
postkort	postkortene	N;NOM;DEF;PL
overmængde	overmængdes	N;GEN;INDF;SG
græsenke	græsenker	N;NOM;INDF;PL
straffespark	straffesparkets	N;NOM;DEF;SG
armhule	armhulerne	N;NOM;DEF;PL
mariehøne	mariehønens	N;NOM;DEF;SG
kryds	kryds'	N;GEN;INDF;SG
skulptur	skulpturen	N;NOM;DEF;SG
engel	englenengelen	N;NOM;DEF;SG
skizofreni	skizofreniens	N;NOM;DEF;SG
burgerbar	burgerbarers	N;GEN;INDF;PL
vams	vamsenes	N;NOM;DEF;PL
agern	agern	N;NOM;INDF;PL
dag	dag	N;NOM;INDF;SG
produkt	produkts	N;GEN;INDF;SG
purere	purer	V;IMP;ACT
punktum	punktum	N;NOM;INDF;SG
brønd	brøndene	N;NOM;DEF;PL
mysli	myslien	N;NOM;DEF;SG
skjorte	skjorternes	N;NOM;DEF;PL
ørn	ørnen	N;NOM;DEF;SG
mexicaner	mexicanerens	N;NOM;DEF;SG
malm	malmene	N;NOM;DEF;PL
mellemnavn	mellemnavnet	N;NOM;DEF;SG
kontaktperson	kontaktpersoners	N;GEN;INDF;PL
tomme	tommes	N;GEN;INDF;SG
drømmekage	drømmekagerne	N;NOM;DEF;PL
motivation	motivationernes	N;NOM;DEF;PL
klaviatur	klaviatur	N;NOM;INDF;SG
skåning	skåninger	N;NOM;INDF;PL
hyppighed	hyppigheders	N;GEN;INDF;PL
rende	renders	N;GEN;INDF;PL
pip	pip	N;NOM;INDF;PL
snabel	snablers	N;GEN;INDF;PL
besked	beskeds	N;GEN;INDF;SG
babybio	babybioer	N;NOM;INDF;PL
ubåd	ubådenes	N;NOM;DEF;PL
ordinere	ordinerer	V;IND;PRS;ACT
myndighedsrepræsentant	myndighedsrepræsentantens	N;NOM;DEF;SG
bølgelængde	bølgelængde	N;NOM;INDF;SG
mønt	mønterne	N;NOM;DEF;PL
navle	navler	N;NOM;INDF;PL
spædbarn	spædbarnet	N;NOM;DEF;SG
riffel	riffel	N;NOM;INDF;SG
substans	substanser	N;NOM;INDF;PL
gilding	gildingen	N;NOM;DEF;SG
svend	svendenes	N;NOM;DEF;PL
fyrtårn	fyrtårne	N;NOM;INDF;PL
antenne	antenne	N;NOM;INDF;SG
metamorfose	metamorfose	N;NOM;INDF;SG
republik	republikker	N;NOM;INDF;PL
semiotiker	semiotiker	N;NOM;INDF;SG
majsolie	majsolies	N;GEN;INDF;SG
forelæsning	forelæsningernes	N;NOM;DEF;PL
massefylde	massefylden	N;NOM;DEF;SG
japaner	japaneres	N;GEN;INDF;PL
butterfly	butterflys	N;GEN;INDF;SG
androide	androiden	N;NOM;DEF;SG
intimidere	intimiderende	V.PTCP;PRS;ACT
antydning	antydninger	N;NOM;INDF;PL
majsolie	majsolier	N;NOM;INDF;PL
vandmand	vandmanden	N;NOM;DEF;SG
realist	realister	N;NOM;INDF;PL
autodidakt	autodidakten	N;NOM;DEF;SG
kor	korenes	N;NOM;DEF;PL
bogklub	bogklubs	N;GEN;INDF;SG
frimurer	frimureres	N;GEN;INDF;PL
kraveben	kravebens	N;GEN;INDF;SG
andrik	andrikkernes	N;NOM;DEF;PL
alkoholiker	alkoholikerens	N;NOM;DEF;SG
kolos	kolosser	N;NOM;INDF;PL
ambassade	ambassader	N;NOM;INDF;PL
hovedpulsåre	hovedpulsåre	N;NOM;INDF;SG
engel	engel	N;NOM;INDF;SG
ubåd	ubåde	N;NOM;INDF;PL
ræv	rævenes	N;NOM;DEF;PL
eskadrille	eskadrilles	N;GEN;INDF;SG
kammer	kamrene	N;NOM;DEF;PL
wc	wc'ets	N;NOM;DEF;SG
elev	elevers	N;GEN;INDF;PL
måge	måges	N;GEN;INDF;SG
modalverbum	modalverbernes	N;NOM;DEF;PL
ændringsforslag	ændringsforslagets	N;NOM;DEF;SG
spørgsmålstegn	spørgsmålstegns	N;GEN;INDF;SG
ophavsgruppe	ophavsgruppers	N;GEN;INDF;PL
vaskeklud	vaskekludenes	N;NOM;DEF;PL
flaskehals	flaskehalsenes	N;NOM;DEF;PL
palisade	palisades	N;GEN;INDF;SG
muffe	muffen	N;NOM;DEF;SG
prise	prises	N;GEN;INDF;SG
husbrand	husbrandene	N;NOM;DEF;PL
stad	stæderne	N;NOM;DEF;PL
database	databasernes	N;NOM;DEF;PL
krog	kroges	N;GEN;INDF;PL
babylonier	babyloniere	N;NOM;INDF;PL
alfahan	alfahans	N;GEN;INDF;SG
dag	dagen	N;NOM;DEF;SG
suspensorium	suspensoriernes	N;NOM;DEF;PL
sværd	sværdene	N;NOM;DEF;PL
ressource	ressourcers	N;GEN;INDF;PL
koncert	koncert	N;NOM;INDF;SG
padde	padderne	N;NOM;DEF;PL
bæskubber	bæskubberens	N;NOM;DEF;SG
cykeldæk	cykeldækket	N;NOM;DEF;SG
røgelse	røgelser	N;NOM;INDF;PL
fest	festerne	N;NOM;DEF;PL
manifest	manifesters	N;GEN;INDF;PL
eksempel	eksemplets	N;NOM;DEF;SG
atmosfære	atmosfærerne	N;NOM;DEF;PL
kranse	kranse	V;NFIN;ACT
kendeord	kendeords	N;GEN;INDF;PL
seraf	serafen	N;NOM;DEF;SG
plage	plagen	N;NOM;DEF;SG
gemytlighed	gemytlighedernes	N;NOM;DEF;PL
frøken	frøkenen	N;NOM;DEF;SG
vinkelhalveringslinje	vinkelhalveringslinjer	N;NOM;INDF;PL
læbe	læbers	N;GEN;INDF;PL
univers	universer	N;NOM;INDF;PL
gnom	gnomernes	N;NOM;DEF;PL
hyæne	hyænes	N;GEN;INDF;SG
udmatning	udmatningers	N;GEN;INDF;PL
middelhav	middelhavets	N;NOM;DEF;SG
honning	honnings	N;GEN;INDF;SG
pengepung	pengepungene	N;NOM;DEF;PL
urinrør	urinrørenes	N;NOM;DEF;PL
indtaste	indtastede	V;IND;PST;ACT
genotype	genotypernes	N;NOM;DEF;PL
blodplade	blodplade	N;NOM;INDF;SG
interjektion	interjektions	N;GEN;INDF;SG
færing	færings	N;GEN;INDF;SG
rom	rommernesrom'ernes	N;NOM;DEF;PL
søjle	søjles	N;GEN;INDF;SG
overskæg	overskægs	N;GEN;INDF;PL
mannequin	mannequin	N;NOM;INDF;SG
furie	furies	N;GEN;INDF;SG
slikkepot	slikkepotten	N;NOM;DEF;SG
massør	massørers	N;GEN;INDF;PL
faldgrube	faldgruberne	N;NOM;DEF;PL
efternavn	efternavns	N;GEN;INDF;SG
dekagram	dekagrams	N;GEN;INDF;PL
brunette	brunette	N;NOM;INDF;SG
nytår	nytårs	N;GEN;INDF;PL
kølsvin	kølsvins	N;GEN;INDF;PL
omvej	omvej	N;NOM;INDF;SG
vandhund	vandhunds	N;GEN;INDF;SG
klovn	klovnens	N;NOM;DEF;SG
piccolo	piccoloers	N;GEN;INDF;PL
glimt	glimts	N;GEN;INDF;SG
straffespark	straffesparks	N;GEN;INDF;SG
faster	fastres	N;GEN;INDF;PL
tillægsord	tillægsords	N;GEN;INDF;SG
bil	bilen	N;NOM;DEF;SG
strategi	strategier	N;NOM;INDF;PL
glansbillede	glansbilleders	N;GEN;INDF;PL
globe	globernes	N;NOM;DEF;PL
bolværk	bolværkets	N;NOM;DEF;SG
bikube	bikubers	N;GEN;INDF;PL
rig	riggenes	N;NOM;DEF;PL
kryddernellike	kryddernellike	N;NOM;INDF;SG
forkortning	forkortninger	N;NOM;INDF;PL
fiskeolie	fiskeolierne	N;NOM;DEF;PL
karikartutegning	karikartutegningen	N;NOM;DEF;SG
babylift	babylifterne	N;NOM;DEF;PL
grundlovsdag	grundlovsdags	N;GEN;INDF;SG
aktivitet	aktivitets	N;GEN;INDF;SG
stør	støres	N;GEN;INDF;PL
yndling	yndlingenes	N;NOM;DEF;PL
olie	olier	N;NOM;INDF;PL
akkusativ	akkusativer	N;NOM;INDF;PL
bro	broers	N;GEN;INDF;PL
mønster	mønstrene	N;NOM;DEF;PL
ed	ed	N;NOM;INDF;SG
kustode	kustodens	N;NOM;DEF;SG
korrigere	korrigere	V;NFIN;ACT
bugspytkirtel	bugspytkirtel	N;NOM;INDF;SG
bæskubber	bæskubbers	N;GEN;INDF;SG
penneven	penneven	N;NOM;INDF;SG
sprog	sprog	N;NOM;INDF;SG
rende	rende	N;NOM;INDF;SG
spækhugger	spækhuggerens	N;NOM;DEF;SG
zarina	zarinaerne	N;NOM;DEF;PL
værelse	værelses	N;GEN;INDF;SG
bambus	bambus	N;NOM;INDF;SG
e-mail	e-mail	N;NOM;INDF;SG
brosten	brosten	N;NOM;INDF;PL
ørred	ørreders	N;GEN;INDF;PL
musikvideo	musikvideoens	N;NOM;DEF;SG
tjørn	tjørne	N;NOM;INDF;PL
spækhugger	spækhugger	N;NOM;INDF;SG
forsømthed	forsømtheds	N;GEN;INDF;SG
sekant	sekantens	N;NOM;DEF;SG
nøgleroman	nøgleromaner	N;NOM;INDF;PL
cellekerne	cellekernens	N;NOM;DEF;SG
bajer	bajernes	N;NOM;DEF;PL
galdeblære	galdeblæres	N;GEN;INDF;SG
autopsi	autopsien	N;NOM;DEF;SG
græsenke	græsenkerne	N;NOM;DEF;PL
kommentar	kommentars	N;GEN;INDF;SG
psykologi	psykologien	N;NOM;DEF;SG
strømpe	strømpens	N;NOM;DEF;SG
tilstand	tilstande	N;NOM;INDF;PL
ørken	ørkenernesørknernes	N;NOM;DEF;PL
skede	skederne	N;NOM;DEF;PL
klimaforandring	klimaforandringers	N;GEN;INDF;PL
rov	rovs	N;GEN;INDF;SG
lænestol	lænestols	N;GEN;INDF;SG
brosten	brostenene	N;NOM;DEF;PL
piberenser	piberensers	N;GEN;INDF;SG
istap	istapperne	N;NOM;DEF;PL
tibetaner	tibetaners	N;GEN;INDF;SG
fosfolipid	fosfolipidets	N;NOM;DEF;SG
geometri	geometri	N;NOM;INDF;SG
ærkeengel	ærkeengel	N;NOM;INDF;SG
golfbane	golfbaners	N;GEN;INDF;PL
annektering	annekteringerne	N;NOM;DEF;PL
erobre	erobrer	V;IND;PRS;ACT
jurist	juristen	N;NOM;DEF;SG
tolk	tolks	N;GEN;INDF;SG
lillebror	lillebror	N;NOM;INDF;SG
kuffert	kuffertens	N;NOM;DEF;SG
rom	rommernerom'erne	N;NOM;DEF;PL
andrik	andrik	N;NOM;INDF;SG
organdonor	organdonors	N;GEN;INDF;SG
fælled	fælleds	N;GEN;INDF;SG
skulder	skulder	N;NOM;INDF;SG
sekant	sekanten	N;NOM;DEF;SG
D-mark	D-marken	N;NOM;DEF;SG
perfektionist	perfektionists	N;GEN;INDF;SG
ovn	ovn	N;NOM;INDF;SG
halvbror	halvbror	N;NOM;INDF;SG
komponist	komponisters	N;GEN;INDF;PL
metamorfose	metamorfosernes	N;NOM;DEF;PL
zucchini	zucchinier	N;NOM;INDF;PL
abbed	abbeds	N;GEN;INDF;SG
broccoli	broccoliens	N;NOM;DEF;SG
verballed	verballeds	N;GEN;INDF;SG
ludder	ludderne	N;NOM;DEF;PL
kolibri	kolibris	N;GEN;INDF;SG
laks	laks	N;NOM;INDF;SG
bro	broens	N;NOM;DEF;SG
orgie	orgies	N;GEN;INDF;SG
sultan	sultanens	N;NOM;DEF;SG
trampolin	trampolins	N;GEN;INDF;SG
strømpe	strømpes	N;GEN;INDF;SG
papir	papir	N;NOM;INDF;SG
efternavn	efternavnes	N;GEN;INDF;PL
akvarel	akvareller	N;NOM;INDF;PL
pulver	pulvernes	N;NOM;DEF;PL
urin	urins	N;GEN;INDF;SG
begravelse	begravelser	N;NOM;INDF;PL
blodplade	blodpladen	N;NOM;DEF;SG
chateau	chateaus	N;GEN;INDF;SG
mafiafamilie	mafiafamilien	N;NOM;DEF;SG
bolværk	bolværk	N;NOM;INDF;SG
bryn	brynenes	N;NOM;DEF;PL
hjerne	hjernes	N;GEN;INDF;SG
afstand	afstandene	N;NOM;DEF;PL
tændstikæske	tændstikæske	N;NOM;INDF;SG
julekort	julekortenes	N;NOM;DEF;PL
fejl	fejlen	N;NOM;DEF;SG
pyrrhussejr	pyrrhussejrs	N;GEN;INDF;SG
fasan	fasan	N;NOM;INDF;SG
lus	lus'	N;GEN;INDF;SG
ravn	ravnenes	N;NOM;DEF;PL
lab	labben	N;NOM;DEF;SG
avis	avisers	N;GEN;INDF;PL
symfoni	symfonien	N;NOM;DEF;SG
solopgang	solopganges	N;GEN;INDF;PL
kloakdyr	kloakdyrs	N;GEN;INDF;SG
begyndelse	begyndelserne	N;NOM;DEF;PL
weekend	weekenden	N;NOM;DEF;SG
harpun	harpunernes	N;NOM;DEF;PL
tempo	tempoers	N;GEN;INDF;PL
novelle	novellerne	N;NOM;DEF;PL
projekt	projekter	N;NOM;INDF;PL
græs	græs	N;NOM;INDF;SG
sorg	sorgernes	N;NOM;DEF;PL
deisme	deismens	N;NOM;DEF;SG
skib	skibenes	N;NOM;DEF;PL
slagsmål	slagsmåls	N;GEN;INDF;SG
bagdør	bagdørenes	N;NOM;DEF;PL
finte	finternes	N;NOM;DEF;PL
teori	teoriens	N;NOM;DEF;SG
horn	hornenes	N;NOM;DEF;PL
pinlighed	pinligheders	N;GEN;INDF;PL
magre	magres	V;IND;PRS;PASS
kvalitet	kvaliteter	N;NOM;INDF;PL
illusion	illusionernes	N;NOM;DEF;PL
drink	drink	N;NOM;INDF;SG
øjelåg	øjelågene	N;NOM;DEF;PL
pund	punds	N;GEN;INDF;SG
armlægning	armlægning	N;NOM;INDF;SG
visent	visent	N;NOM;INDF;SG
farvestof	farvestoffernes	N;NOM;DEF;PL
gummi	gummis	N;GEN;INDF;SG
charmere	charmer	V;IMP;ACT
vatpind	vatpinds	N;GEN;INDF;SG
palmeolie	palmeoliernes	N;NOM;DEF;PL
konspirationsteori	konspirationsteorien	N;NOM;DEF;SG
intelligensalder	intelligensalder	N;NOM;INDF;SG
interesse	interessens	N;NOM;DEF;SG
buffer	bufferens	N;NOM;DEF;SG
vippe	vippens	N;NOM;DEF;SG
præsident	præsidenternes	N;NOM;DEF;PL
rødlos	rødlossernes	N;NOM;DEF;PL
afart	afartens	N;NOM;DEF;SG
pølse	pølser	N;NOM;INDF;PL
tagetage	tage	N;NOM;INDF;SG
vable	vablerne	N;NOM;DEF;PL
klap-sammen-mad	klap-sammen-madder	N;NOM;INDF;PL
voldtægtsmand	voldtægtsmændene	N;NOM;DEF;PL
krave	kravers	N;GEN;INDF;PL
cigaretmærke	cigaretmærke	N;NOM;INDF;SG
negl	negls	N;GEN;INDF;SG
onsdag	onsdagens	N;NOM;DEF;SG
cigaretskod	cigaretskoddene	N;NOM;DEF;PL
relativ	relativs	N;GEN;INDF;SG
etiopier	etiopierne	N;NOM;DEF;PL
intelligenstest	intelligenstests	N;GEN;INDF;SG
bred	bred	N;NOM;INDF;SG
missekat	missekattes	N;GEN;INDF;PL
primtal	primtals	N;GEN;INDF;SG
øjenvippe	øjenvippe	N;NOM;INDF;SG
kast	kast	N;NOM;INDF;PL
nevø	nevøer	N;NOM;INDF;PL
meteorit	meteoritter	N;NOM;INDF;PL
kolli	kolli	N;NOM;INDF;SG
pølse	pølses	N;GEN;INDF;SG
pig	piggens	N;NOM;DEF;SG
smøre	smørers	N;GEN;INDF;PL
flue	fluen	N;NOM;DEF;SG
rejsebureau	rejsebureauernes	N;NOM;DEF;PL
endestation	endestationen	N;NOM;DEF;SG
fjernsyn	fjernsyn	N;NOM;INDF;SG
djævel	djævlenes	N;NOM;DEF;PL
strø	strøs	N;GEN;INDF;SG
polyeder	polyeders	N;GEN;INDF;SG
teori	teoriers	N;GEN;INDF;PL
ordsprog	ordsprogenes	N;NOM;DEF;PL
gemmested	gemmesteders	N;GEN;INDF;PL
væg	væggenes	N;NOM;DEF;PL
adgangskode	adgangskoders	N;GEN;INDF;PL
link	links	N;GEN;INDF;SG
kande	kanderne	N;NOM;DEF;PL
kubikmeter	kubikmeters	N;GEN;INDF;PL
differenskvotient	differenskvotients	N;GEN;INDF;SG
krave	kravernes	N;NOM;DEF;PL
partikel	partikler	N;NOM;INDF;PL
englærke	englærke	N;NOM;INDF;SG
postbud	postbude	N;NOM;INDF;PL
sål	såls	N;GEN;INDF;SG
svans	svansen	N;NOM;DEF;SG
romani	romanierne	N;NOM;DEF;PL
marsvin	marsvins	N;GEN;INDF;PL
garder	garders	N;GEN;INDF;SG
sav	saves	N;GEN;INDF;PL
tragedie	tragediers	N;GEN;INDF;PL
ventilere	ventilerende	V.PTCP;PRS;ACT
eskimolog	eskimologen	N;NOM;DEF;SG
korps	korpset	N;NOM;DEF;SG
slot	slot	N;NOM;INDF;SG
fotograf	fotograferne	N;NOM;DEF;PL
årti	årtiet	N;NOM;DEF;SG
bål	bålet	N;NOM;DEF;SG
efterår	efterårs	N;GEN;INDF;PL
pynt	pynts	N;GEN;INDF;SG
bregne	bregners	N;GEN;INDF;PL
lakaj	lakajers	N;GEN;INDF;PL
panere	panere	V;NFIN;ACT
radio	radioens	N;NOM;DEF;SG
pantebrev	pantebreves	N;GEN;INDF;PL
drøn	drønet	N;NOM;DEF;SG
komodovaran	komodovaranens	N;NOM;DEF;SG
hø	høs	N;GEN;INDF;PL
tidspunkt	tidspunktets	N;NOM;DEF;SG
nudel	nudlers	N;GEN;INDF;PL
overraskelse	overraskelser	N;NOM;INDF;PL
penalhus	penalhuse	N;NOM;INDF;PL
metropol	metropolens	N;NOM;DEF;SG
kriger	krigers	N;GEN;INDF;SG
suggerere	suggererer	V;IND;PRS;ACT
pornograf	pornografers	N;GEN;INDF;PL
modulere	moduleret	V.PTCP;PST;PASS
kongerige	kongeriger	N;NOM;INDF;PL
avis	avis	N;NOM;INDF;SG
rosmarin	rosmarinens	N;NOM;DEF;SG
løjtnant	løjtnants	N;GEN;INDF;SG
væggelus	væggelus'	N;GEN;INDF;PL
neg	negs	N;GEN;INDF;SG
dyrskue	dyrskuers	N;GEN;INDF;PL
synd	synders	N;GEN;INDF;PL
ildflue	ildfluerne	N;NOM;DEF;PL
lyn	lyn	N;NOM;INDF;SG
afasi	afasi	N;NOM;INDF;SG
tændstikmand	tændstikmandens	N;NOM;DEF;SG
vindmølle	vindmøllerne	N;NOM;DEF;PL
intelligenstest	intelligenstest	N;NOM;INDF;PL
beryl	beryllen	N;NOM;DEF;SG
barrikade	barrikadens	N;NOM;DEF;SG
miljø	miljøerne	N;NOM;DEF;PL
teori	teorier	N;NOM;INDF;PL
sportsserie	sportsserier	N;NOM;INDF;PL
subjekt	subjekterne	N;NOM;DEF;PL
perser	persere	N;NOM;INDF;PL
tagetage	tage	N;NOM;DEF;PL
pave	paverne	N;NOM;DEF;PL
vindmølle	vindmølles	N;GEN;INDF;SG
mulat	mulat	N;NOM;INDF;SG
participium	participier	N;NOM;INDF;PL
tronarving	tronarvingen	N;NOM;DEF;SG
torden	tordenernes	N;NOM;DEF;PL
ekspedient	ekspedienterne	N;NOM;DEF;PL
kronprins	kronprins'	N;GEN;INDF;SG
stål	stålene	N;NOM;DEF;PL
styr	styr	N;NOM;INDF;PL
fjord	fjordes	N;GEN;INDF;PL
kardiogram	kardiogram	N;NOM;INDF;SG
konservatorie	konservatoriet	N;NOM;DEF;SG
aboriginer	aboriginerne	N;NOM;DEF;PL
kejser	kejserne	N;NOM;DEF;PL
juble	jublet	V.PTCP;PST;PASS
hårbørste	hårbørste	N;NOM;INDF;SG
fordanskning	fordanskningerne	N;NOM;DEF;PL
dige	diget	N;NOM;DEF;SG
tusind	tusindernes	N;NOM;DEF;PL
musket	muskets	N;GEN;INDF;SG
bratsch	bratsch	N;NOM;INDF;SG
kulturchok	kulturchokket	N;NOM;DEF;SG
udstyre	udstyrer	V;IND;PRS;ACT
juble	jublende	V.PTCP;PRS;ACT
pave	pavens	N;NOM;DEF;SG
kvotient	kvotients	N;GEN;INDF;SG
tilladelse	tilladelser	N;NOM;INDF;PL
fjols	fjolserne	N;NOM;DEF;PL
paryk	paryks	N;GEN;INDF;SG
studium	studiets	N;NOM;DEF;SG
vakuum	vakuum	N;NOM;INDF;SG
nominativ	nominativen	N;NOM;DEF;SG
akilleshæl	akilleshæl	N;NOM;INDF;SG
gyngestol	gyngestolenes	N;NOM;DEF;PL
pinje	pinjernes	N;NOM;DEF;PL
taste	tastede	V;IND;PST;ACT
lån	lån	N;NOM;INDF;PL
spor	spors	N;GEN;INDF;SG
mavesaft	mavesaften	N;NOM;DEF;SG
tændstikæske	tændstikæskerne	N;NOM;DEF;PL
omelet	omeletterne	N;NOM;DEF;PL
atgejr	atgejr	N;NOM;INDF;SG
pagaj	pagajers	N;GEN;INDF;PL
kejserrige	kejserriget	N;NOM;DEF;SG
parodi	parodis	N;GEN;INDF;SG
slot	slotte	N;NOM;INDF;PL
lystre	lystret	V.PTCP;PST;PASS
studium	studier	N;NOM;INDF;PL
falk	falks	N;GEN;INDF;SG
loppe	loppe	N;NOM;INDF;SG
skæbne	skæbnen	N;NOM;DEF;SG
appelsinskræl	appelsinskrællen	N;NOM;DEF;SG
fædreland	fædrelandenes	N;NOM;DEF;PL
grundlag	grundlaget	N;NOM;DEF;SG
klapvogn	klapvognenes	N;NOM;DEF;PL
fodspor	fodspors	N;GEN;INDF;SG
recirkulation	recirkulationers	N;GEN;INDF;PL
astronaut	astronauter	N;NOM;INDF;PL
barnløshed	barnløshed	N;NOM;INDF;SG
terapi	terapiernes	N;NOM;DEF;PL
pentagram	pentagram	N;NOM;INDF;SG
dige	digerne	N;NOM;DEF;PL
katastrofe	katastrofer	N;NOM;INDF;PL
fornemmelse	fornemmelsens	N;NOM;DEF;SG
grindehval	grindehvale	N;NOM;INDF;PL
mandarin	mandarinerne	N;NOM;DEF;PL
bersærk	bersærker	N;NOM;INDF;PL
bror	brors	N;GEN;INDF;SG
data	datas	N;GEN;INDF;PL
snebold	snebold	N;NOM;INDF;SG
pupil	pupillerne	N;NOM;DEF;PL
forkortelse	forkortelses	N;GEN;INDF;SG
parabolantenne	parabolantenners	N;GEN;INDF;PL
stængel	stænglers	N;GEN;INDF;PL
låg	lågets	N;NOM;DEF;SG
nukleon	nukleonen	N;NOM;DEF;SG
argument	argumenter	N;NOM;INDF;PL
superorganisme	superorganismer	N;NOM;INDF;PL
morgenfrue	morgenfruerne	N;NOM;DEF;PL
gnist	gnistens	N;NOM;DEF;SG
lokum	lokums	N;GEN;INDF;SG
stormfugl	stormfugl	N;NOM;INDF;SG
nytårsaften	nytårsaftener	N;NOM;INDF;PL
trafikprop	trafikpropper	N;NOM;INDF;PL
gnist	gnisters	N;GEN;INDF;PL
økologi	økologien	N;NOM;DEF;SG
neksøbo	neksøboen	N;NOM;DEF;SG
deviere	devierede	V;IND;PST;ACT
valravn	valravne	N;NOM;INDF;PL
encyklopædi	encyklopædien	N;NOM;DEF;SG
bronze	bronze	N;NOM;INDF;SG
fårehund	fårehunde	N;NOM;INDF;PL
lue	luers	N;GEN;INDF;PL
kusse	kussen	N;NOM;DEF;SG
etymolog	etymologen	N;NOM;DEF;SG
kondom	kondomet	N;NOM;DEF;SG
semifinale	semifinalernes	N;NOM;DEF;PL
konkurrence	konkurrencen	N;NOM;DEF;SG
sadist	sadisters	N;GEN;INDF;PL
afpresning	afpresningerne	N;NOM;DEF;PL
kjole	kjoles	N;GEN;INDF;SG
beryl	beryllers	N;GEN;INDF;PL
grænse	grænser	N;NOM;INDF;PL
annihilere	annihileret	V.PTCP;PST;PASS
næse	næses	N;GEN;INDF;SG
ansøger	ansøgers	N;GEN;INDF;SG
ultralyd	ultralyde	N;NOM;INDF;PL
ryg	rygs	N;GEN;INDF;SG
zar	zarers	N;GEN;INDF;PL
bred	breds	N;GEN;INDF;SG
plæneklipper	plæneklippers	N;GEN;INDF;SG
matros	matrosens	N;NOM;DEF;SG
horde	horde	N;NOM;INDF;SG
tepose	teposer	N;NOM;INDF;PL
palmeolie	palmeolierne	N;NOM;DEF;PL
jærv	jærv	N;NOM;INDF;SG
tomrum	tomrum	N;NOM;INDF;SG
maksime	maksime	N;NOM;INDF;SG
måbe	måb	V;IMP;ACT
solsikkeolie	solsikkeoliers	N;GEN;INDF;PL
morgenfrue	morgenfrue	N;NOM;INDF;SG
kamel	kamelernes	N;NOM;DEF;PL
pyjamas	pyjamassens	N;NOM;DEF;SG
bankkonto	bankkontoer	N;NOM;INDF;PL
diskotek	diskoteker	N;NOM;INDF;PL
husbond	husbonden	N;NOM;DEF;SG
halvvokal	halvvokal	N;NOM;INDF;SG
gummi	gummier	N;NOM;INDF;PL
rær	rærenes	N;NOM;DEF;PL
trillebør	trillebørs	N;GEN;INDF;SG
tyttebær	tyttebærs	N;GEN;INDF;SG
mø	møernes	N;NOM;DEF;PL
vindrue	vindrue	N;NOM;INDF;SG
brand	brands	N;GEN;INDF;SG
rævegrav	rævegravene	N;NOM;DEF;PL
lønforhøjelse	lønforhøjelsers	N;GEN;INDF;PL
russer	russerens	N;NOM;DEF;SG
taste	taster	V;IND;PRS;ACT
kasseapparat	kasseapparater	N;NOM;INDF;PL
foderbræt	foderbrættets	N;NOM;DEF;SG
flagermus	flagermus'	N;GEN;INDF;SG
positiv	positiv	N;NOM;INDF;SG
dufte	duft	V;IMP;ACT
tyv	tyvenes	N;NOM;DEF;PL
hest	heste	N;NOM;INDF;PL
anonymisere	anonymiseredes	V;IND;PST;PASS
skuffe	skuffers	N;GEN;INDF;PL
fejl	fejlens	N;NOM;DEF;SG
akkordeon	akkordeon	N;NOM;INDF;SG
slutspurt	slutspurtens	N;NOM;DEF;SG
brækjern	brækjernets	N;NOM;DEF;SG
klitoris	klitorissen	N;NOM;DEF;SG
guldfisk	guldfiskene	N;NOM;DEF;PL
ballade	balladernes	N;NOM;DEF;PL
barbar	barbarernes	N;NOM;DEF;PL
album	albummers	N;GEN;INDF;PL
svulme	svulmet	V.PTCP;PST;PASS
hingst	hingst	N;NOM;INDF;SG
romani	romanien	N;NOM;DEF;SG
pilot	piloterne	N;NOM;DEF;PL
hasselnød	hasselnøds	N;GEN;INDF;SG
tatovering	tatoveringernes	N;NOM;DEF;PL
fraktur	frakturers	N;GEN;INDF;PL
faktum	faktaenes	N;NOM;DEF;PL
distance	distances	N;GEN;INDF;SG
dørklokke	dørklokkers	N;GEN;INDF;PL
spatel	spatel	N;NOM;INDF;SG
kladde	kladderne	N;NOM;DEF;PL
musikkonservatorie	musikkonservatoriet	N;NOM;DEF;SG
tese	tesers	N;GEN;INDF;PL
annihilere	annihilerede	V;IND;PST;ACT
rovfugl	rovfugl	N;NOM;INDF;SG
kælling	kællingers	N;GEN;INDF;PL
madras	madrassers	N;GEN;INDF;PL
raritet	rariteterne	N;NOM;DEF;PL
hæl	hæl	N;NOM;INDF;SG
kejsersnit	kejsersnittenes	N;NOM;DEF;PL
kriger	krigeren	N;NOM;DEF;SG
maksime	maksimen	N;NOM;DEF;SG
nutid	nutidernes	N;NOM;DEF;PL
kongerige	kongeriges	N;GEN;INDF;SG
bænk	bænk	N;NOM;INDF;SG
spytkirtel	spytkirtel	N;NOM;INDF;SG
mynte	mynters	N;GEN;INDF;PL
karpe	karpes	N;GEN;INDF;SG
skiløber	skiløberes	N;GEN;INDF;PL
campingvogn	campingvognene	N;NOM;DEF;PL
strande	strandedes	V;IND;PST;PASS
indadvendthed	indadvendtheders	N;GEN;INDF;PL
hjort	hjorts	N;GEN;INDF;SG
juicer	juicere	N;NOM;INDF;PL
ordspil	ordspils	N;GEN;INDF;SG
computerspilkarakter	computerspilkarakterernes	N;NOM;DEF;PL
navnebroder	navnebrødrenes	N;NOM;DEF;PL
fajance	fajancens	N;NOM;DEF;SG
ærinde	ærinders	N;GEN;INDF;PL
len	lens	N;GEN;INDF;PL
café au lait	café au laiterne	N;NOM;DEF;PL
pilot	piloternes	N;NOM;DEF;PL
beskyldning	beskyldningerne	N;NOM;DEF;PL
filter	filtret	N;NOM;DEF;SG
handler	handlerne	N;NOM;DEF;PL
puddel	pudlernes	N;NOM;DEF;PL
mule	muler	N;NOM;INDF;PL
botanik	botanikken	N;NOM;DEF;SG
entrecote	entrecoters	N;GEN;INDF;PL
intranet	intranet	N;NOM;INDF;PL
barrikade	barrikaders	N;GEN;INDF;PL
kondom	kondomets	N;NOM;DEF;SG
paraply	paraply	N;NOM;INDF;SG
motorcykel	motorcyklers	N;GEN;INDF;PL
tyv	tyve	N;NOM;INDF;PL
skurk	skurkene	N;NOM;DEF;PL
båd	båden	N;NOM;DEF;SG
allike	alliker	N;NOM;INDF;PL
mode	mode	N;NOM;INDF;SG
orne	ornes	N;GEN;INDF;SG
solopgang	solopgangen	N;NOM;DEF;SG
skidt	skidtet	N;NOM;DEF;SG
penis	penisser	N;NOM;INDF;PL
emblem	emblemet	N;NOM;DEF;SG
hviderusser	hviderussers	N;GEN;INDF;SG
måbe	måbedes	V;IND;PST;PASS
plakat	plakaters	N;GEN;INDF;PL
cigaretmærke	cigaretmærkets	N;NOM;DEF;SG
farmaceut	farmaceutens	N;NOM;DEF;SG
brandert	branderters	N;GEN;INDF;PL
sæbe	sæbe	N;NOM;INDF;SG
eventyr	eventyr	N;NOM;INDF;PL
snedker	snedkernes	N;NOM;DEF;PL
berømmelse	berømmelse	N;NOM;INDF;SG
babylem	babylems	N;GEN;INDF;SG
offer	ofre	N;NOM;INDF;PL
asterisk	asterisker	N;NOM;INDF;PL
forglemmigej	forglemmigejen	N;NOM;DEF;SG
autofokus	autofokusserne	N;NOM;DEF;PL
måbe	måber	V;IND;PRS;ACT
meteorit	meteoritters	N;GEN;INDF;PL
viking	vikingen	N;NOM;DEF;SG
styr	styrene	N;NOM;DEF;PL
samfundsstøtte	samfundsstøttes	N;GEN;INDF;SG
synonymordbog	synonymordbogs	N;GEN;INDF;SG
heltal	heltal	N;NOM;INDF;SG
løsen	løsens	N;GEN;INDF;SG
atom	atomet	N;NOM;DEF;SG
forklare	forklaret	V.PTCP;PST;PASS
moderkage	moderkagerne	N;NOM;DEF;PL
trillebør	trillebørene	N;NOM;DEF;PL
rekvirere	rekvirerede	V;IND;PST;ACT
solvind	solvinden	N;NOM;DEF;SG
bål	bål	N;NOM;INDF;PL
kommissær	kommissærernes	N;NOM;DEF;PL
lagune	lagunen	N;NOM;DEF;SG
hundestejle	hundestejlens	N;NOM;DEF;SG
ultralyd	ultralydenes	N;NOM;DEF;PL
underlag	underlags	N;GEN;INDF;PL
hæl	hælen	N;NOM;DEF;SG
stegepande	stegepanderne	N;NOM;DEF;PL
skænk	skænkes	N;GEN;INDF;PL
kildekode	kildekodernes	N;NOM;DEF;PL
mikrobølge	mikrobølgen	N;NOM;DEF;SG
asterisk	asteriskers	N;GEN;INDF;PL
krystallisere	krystalliseret	V.PTCP;PST;PASS
differenskvotient	differenskvotienterne	N;NOM;DEF;PL
harve	harven	N;NOM;DEF;SG
pornograf	pornograf	N;NOM;INDF;SG
kilogram	kilograms	N;GEN;INDF;SG
torn	torn	N;NOM;INDF;SG
frygte	frygtedes	V;IND;PST;PASS
manuskript	manuskripterne	N;NOM;DEF;PL
smørelse	smørelsen	N;NOM;DEF;SG
strø	strøernes	N;NOM;DEF;PL
skomager	skomagere	N;NOM;INDF;PL
spørgsmål	spørgsmålets	N;NOM;DEF;SG
cigaretrør	cigaretrørenes	N;NOM;DEF;PL
ishockeyspiller	ishockeyspillere	N;NOM;INDF;PL
julegave	julegave	N;NOM;INDF;SG
sandhed	sandheders	N;GEN;INDF;PL
ombudsmand	ombudsmænds	N;GEN;INDF;PL
facade	facades	N;GEN;INDF;SG
flyttebil	flyttebilernes	N;NOM;DEF;PL
krokodille	krokodiller	N;NOM;INDF;PL
tragt	tragts	N;GEN;INDF;SG
skuffe	skufferne	N;NOM;DEF;PL
storesøster	storesøstres	N;GEN;INDF;PL
kølle	køllernes	N;NOM;DEF;PL
tæller	tællerenes	N;NOM;DEF;PL
delfin	delfinernes	N;NOM;DEF;PL
flåde	flåder	N;NOM;INDF;PL
græs	græs'	N;GEN;INDF;SG
kjove	kjovernes	N;NOM;DEF;PL
port	ports	N;GEN;INDF;SG
næs	næs'	N;GEN;INDF;PL
sædcelle	sædcellen	N;NOM;DEF;SG
turban	turbanen	N;NOM;DEF;SG
arbejdsgiver	arbejdsgiverne	N;NOM;DEF;PL
ballade	balladers	N;GEN;INDF;PL
boring	boringens	N;NOM;DEF;SG
dufte	duftet	V.PTCP;PST;PASS
gebyr	gebyret	N;NOM;DEF;SG
kors	korsets	N;NOM;DEF;SG
bæk	bæks	N;GEN;INDF;SG
konspirationsteori	konspirationsteoriens	N;NOM;DEF;SG
øge	øg	V;IMP;ACT
tand	tændernes	N;NOM;DEF;PL
ordkløver	ordkløvernes	N;NOM;DEF;PL
sandsæk	sandsækkes	N;GEN;INDF;PL
hofteben	hoftebenets	N;NOM;DEF;SG
flakon	flakonen	N;NOM;DEF;SG
køleskab	køleskabets	N;NOM;DEF;SG
konsekvens	konsekvensernes	N;NOM;DEF;PL
søgeresultat	søgeresultater	N;NOM;INDF;PL
egennavn	egennavne	N;NOM;INDF;PL
amfibium	amfibierne	N;NOM;DEF;PL
vandregræshoppe	vandregræshopperne	N;NOM;DEF;PL
etape	etaper	N;NOM;INDF;PL
måde	mådes	N;GEN;INDF;SG
trafikprop	trafikproppernes	N;NOM;DEF;PL
knogle	knogle	N;NOM;INDF;SG
skræddermester	skræddermesters	N;GEN;INDF;SG
bonderøv	bonderøvs	N;GEN;INDF;SG
blokere	blokerer	V;IND;PRS;ACT
loddekolbe	loddekolbe	N;NOM;INDF;SG
hat	hatten	N;NOM;DEF;SG
cytoplasma	cytoplasmaerne	N;NOM;DEF;PL
katakombe	katakombes	N;GEN;INDF;SG
abrikostræ	abrikostræer	N;NOM;INDF;PL
pendant	pendanternes	N;NOM;DEF;PL
tærskel	tærsklerne	N;NOM;DEF;PL
bånd	båndet	N;NOM;DEF;SG
snor	snors	N;GEN;INDF;SG
tyrker	tyrkeres	N;GEN;INDF;PL
vietnameser	vietnameseren	N;NOM;DEF;SG
jordsvin	jordsvin	N;NOM;INDF;PL
strikkepind	strikkepindene	N;NOM;DEF;PL
ståltråd	ståltrådenes	N;NOM;DEF;PL
kapers	kapersen	N;NOM;DEF;SG
galge	galger	N;NOM;INDF;PL
afprøvning	afprøvningers	N;GEN;INDF;PL
drøne	drøner	V;IND;PRS;ACT
fader	faderens	N;NOM;DEF;SG
bamse	bamses	N;GEN;INDF;SG
rær	rær	N;NOM;INDF;PL
si	siers	N;GEN;INDF;PL
bæst	bæsternes	N;NOM;DEF;PL
aubergine	auberginerne	N;NOM;DEF;PL
bænk	bænkens	N;NOM;DEF;SG
hjort	hjortes	N;GEN;INDF;PL
børnehave	børnehave	N;NOM;INDF;SG
spisebord	spisebordenes	N;NOM;DEF;PL
barnebarn	børne	N;GEN;INDF;PL
kontakt	kontakternes	N;NOM;DEF;PL
kopi	kopiernes	N;NOM;DEF;PL
kontaktlinse	kontaktlinsens	N;NOM;DEF;SG
film	filmene	N;NOM;DEF;PL
parlament	parlamentets	N;NOM;DEF;SG
karotin	karotinet	N;NOM;DEF;SG
tilladelse	tilladelsen	N;NOM;DEF;SG
virolog	virologen	N;NOM;DEF;SG
despoti	despoti	N;NOM;INDF;SG
affaldsstof	affaldsstoffers	N;GEN;INDF;PL
fødselshyppighed	fødselshyppigheds	N;GEN;INDF;SG
lærer	lærerne	N;NOM;DEF;PL
sandstorm	sandstorms	N;GEN;INDF;SG
fremlejer	fremlejeres	N;GEN;INDF;PL
dehydrere	dehydrer	V;IMP;ACT
immigration	immigrationerne	N;NOM;DEF;PL
nektarin	nektarinens	N;NOM;DEF;SG
paryk	parykkerne	N;NOM;DEF;PL
fæstning	fæstningens	N;NOM;DEF;SG
adamsæble	adamsæbler	N;NOM;INDF;PL
spidsborger	spidsborgeren	N;NOM;DEF;SG
bølgefunktion	bølgefunktionens	N;NOM;DEF;SG
kildekode	kildekoden	N;NOM;DEF;SG
grønsag	grønsag	N;NOM;INDF;SG
samfund	samfund	N;NOM;INDF;PL
nominativ	nominativ	N;NOM;INDF;SG
fange	fangens	N;NOM;DEF;SG
svoger	svogre	N;NOM;INDF;PL
længde	længder	N;NOM;INDF;PL
bagmand	bagmands	N;GEN;INDF;SG
bedstemor	bedstemoren	N;NOM;DEF;SG
madras	madrassens	N;NOM;DEF;SG
bold	boldene	N;NOM;DEF;PL
middag	middagen	N;NOM;DEF;SG
pinlighedsfornemmelse	pinlighedsfornemmelser	N;NOM;INDF;PL
fårehund	fårehundene	N;NOM;DEF;PL
bulgarer	bulgarers	N;GEN;INDF;SG
mandebøde	mandebøder	N;NOM;INDF;PL
tragt	tragtenes	N;NOM;DEF;PL
trafikprop	trafikprop	N;NOM;INDF;SG
nyttevirkning	nyttevirkningens	N;NOM;DEF;SG
kunstnernavn	kunstnernavnes	N;GEN;INDF;PL
tilladelse	tilladelsernes	N;NOM;DEF;PL
taske	taske	N;NOM;INDF;SG
malstrøm	malstrømme	N;NOM;INDF;PL
omelet	omelets	N;GEN;INDF;SG
mikrobølge	mikrobølgens	N;NOM;DEF;SG
byttehandel	byttehandels	N;GEN;INDF;SG
lydkort	lydkort	N;NOM;INDF;PL
kærte	kærternes	N;NOM;DEF;PL
guitar	guitarerne	N;NOM;DEF;PL
jordemoder	jordemoders	N;GEN;INDF;SG
svin	svins	N;GEN;INDF;PL
klassifikation	klassifikations	N;GEN;INDF;SG
ændring	ændring	N;NOM;INDF;SG
majonæse	majonæser	N;NOM;INDF;PL
øge	øget	V.PTCP;PST;PASS
tryne	tryne	N;NOM;INDF;SG
knor	knorens	N;NOM;DEF;SG
lastbil	lastbilers	N;GEN;INDF;PL
sandstorm	sandstormene	N;NOM;DEF;PL
addere	adderede	V;IND;PST;ACT
sikring	sikringens	N;NOM;DEF;SG
aflyd	aflyden	N;NOM;DEF;SG
gene	gene	N;NOM;INDF;SG
halvsøster	halvsøster	N;NOM;INDF;SG
lab	labbens	N;NOM;DEF;SG
flyvemaskine	flyvemaskinernes	N;NOM;DEF;PL
avis	aviserne	N;NOM;DEF;PL
syerske	syerskes	N;GEN;INDF;SG
bopæl	bopæles	N;GEN;INDF;PL
epitet	epitet	N;NOM;INDF;SG
sydvest	sydvestes	N;GEN;INDF;PL
trold	troldens	N;NOM;DEF;SG
epitet	epiteternes	N;NOM;DEF;PL
ændre	ændre	V;NFIN;ACT
fylking	fylkingerne	N;NOM;DEF;PL
oversvømmelse	oversvømmelsers	N;GEN;INDF;PL
vinge	vingen	N;NOM;DEF;SG
salatfad	salatfadet	N;NOM;DEF;SG
citron	citrons	N;GEN;INDF;SG
politimester	politimestrene	N;NOM;DEF;PL
klassifikation	klassifikationerne	N;NOM;DEF;PL
definitionsmængde	definitionsmængder	N;NOM;INDF;PL
forårsrulle	forårsrulle	N;NOM;INDF;SG
centralnervesystem	centralnervesystemernes	N;NOM;DEF;PL
brynje	brynjerne	N;NOM;DEF;PL
aminosyre	aminosyrers	N;GEN;INDF;PL
kompagnon	kompagnoners	N;GEN;INDF;PL
jordnøddeolie	jordnøddeolie	N;NOM;INDF;SG
tornado	tornados	N;GEN;INDF;SG
håb	håbs	N;GEN;INDF;SG
marsvin	marsvinet	N;NOM;DEF;SG
trekant	trekantens	N;NOM;DEF;SG
provins	provinser	N;NOM;INDF;PL
hall	haller	N;NOM;INDF;PL
højdespring	højdespringenes	N;NOM;DEF;PL
filigran	filigrannets	N;NOM;DEF;SG
sandkasse	sandkasser	N;NOM;INDF;PL
abdicere	abdicerende	V.PTCP;PRS;ACT
pokerfjæs	pokerfjæs'	N;GEN;INDF;PL
introduktion	introduktions	N;GEN;INDF;SG
mø	møens	N;NOM;DEF;SG
cylinder	cylinderen	N;NOM;DEF;SG
kerne	kerne	N;NOM;INDF;SG
bibliofil	bibliofilerne	N;NOM;DEF;PL
fjols	fjolset	N;NOM;DEF;SG
transformator	transformatoren	N;NOM;DEF;SG
teater	teatre	N;NOM;INDF;PL
dansker	danskers	N;GEN;INDF;SG
kylling	kyllinger	N;NOM;INDF;PL
skov	skovene	N;NOM;DEF;PL
skurk	skurks	N;GEN;INDF;SG
skuldertræk	skuldertrækkets	N;NOM;DEF;SG
jyde	jyders	N;GEN;INDF;PL
kasket	kasket	N;NOM;INDF;SG
orne	ornerne	N;NOM;DEF;PL
guvernørpost	guvernørpost	N;NOM;INDF;SG
kopimaskine	kopimaskinen	N;NOM;DEF;SG
pomfrit	pomfritters	N;GEN;INDF;PL
filter	filtrene	N;NOM;DEF;PL
bussemand	bussemænd	N;NOM;INDF;PL
handikaptoilet	handikaptoilet	N;NOM;INDF;SG
rosmarin	rosmariner	N;NOM;INDF;PL
arrangere	arrangeret	V.PTCP;PST;PASS
syerske	syerskers	N;GEN;INDF;PL
polygon	polygoner	N;NOM;INDF;PL
lykønske	lykønske	V;NFIN;ACT
neg	negets	N;NOM;DEF;SG
atgejr	atgejrerne	N;NOM;DEF;PL
barnløshed	barnløsheden	N;NOM;DEF;SG
sværm	sværmens	N;NOM;DEF;SG
albumin	albumins	N;GEN;INDF;SG
immigration	immigrationernes	N;NOM;DEF;PL
galop	galopper	N;NOM;INDF;PL
kardinalitet	kardinaliteterne	N;NOM;DEF;PL
løg	løgs	N;GEN;INDF;SG
wc-rulle	wc-ruller	N;NOM;INDF;PL
brise	brise	N;NOM;INDF;SG
asiat	asiatens	N;NOM;DEF;SG
fejl	fejls	N;GEN;INDF;SG
galskab	galskaben	N;NOM;DEF;SG
brækjern	brækjern	N;NOM;INDF;SG
myriade	myriadernes	N;NOM;DEF;PL
bibliofil	bibliofils	N;GEN;INDF;SG
sangsvane	sangsvanernes	N;NOM;DEF;PL
karl	karls	N;GEN;INDF;SG
fremlejer	fremlejerne	N;NOM;DEF;PL
marmelade	marmeladernes	N;NOM;DEF;PL
våbenhvile	våbenhvile	N;NOM;INDF;SG
kontakt	kontakters	N;GEN;INDF;PL
højdespring	højdespringets	N;NOM;DEF;SG
hypotese	hypotesers	N;GEN;INDF;PL
havfrue	havfruens	N;NOM;DEF;SG
midnat	midnætternes	N;NOM;DEF;PL
sløjfe	sløjfers	N;GEN;INDF;PL
rugemor	rugemødrene	N;NOM;DEF;PL
montere	montere	V;NFIN;ACT
ændring	ændrings	N;GEN;INDF;SG
kerne	kernen	N;NOM;DEF;SG
folkedragt	folkedragt	N;NOM;INDF;SG
femkant	femkanten	N;NOM;DEF;SG
terapi	terapier	N;NOM;INDF;PL
fagforening	fagforeningen	N;NOM;DEF;SG
udstyre	udstyre	V;NFIN;ACT
svigerinde	svigerinde	N;NOM;INDF;SG
matrone	matroner	N;NOM;INDF;PL
golfbold	golfbolde	N;NOM;INDF;PL
dryp	dryppenes	N;NOM;DEF;PL
storebror	storebrorenes	N;NOM;DEF;PL
melodigrandprix	melodigrandprixerne	N;NOM;DEF;PL
næs	næssene	N;NOM;DEF;PL
industrialisering	industrialiserings	N;GEN;INDF;SG
løjtnant	løjtnant	N;NOM;INDF;SG
kælling	kællingerne	N;NOM;DEF;PL
makron	makrons	N;GEN;INDF;SG
cyklus	cyklussen	N;NOM;DEF;SG
individ	individ	N;NOM;INDF;SG
avis	avisernes	N;NOM;DEF;PL
magre	magre	V;NFIN;ACT
kuld	kuldenes	N;NOM;DEF;PL
islænding	islændinges	N;GEN;INDF;PL
mulat	mulats	N;GEN;INDF;SG
landkrabbe	landkrabbers	N;GEN;INDF;PL
mord	mordet	N;NOM;DEF;SG
hormon	hormonerne	N;NOM;DEF;PL
kronprinsesse	kronprinsesses	N;GEN;INDF;SG
lomme	lommens	N;NOM;DEF;SG
komikerduo	komikerduo	N;NOM;INDF;SG
etiopier	etiopiere	N;NOM;INDF;PL
password	passwords	N;GEN;INDF;PL
vandrør	vandrør	N;NOM;INDF;SG
tyveri	tyveriet	N;NOM;DEF;SG
konsul	konsuler	N;NOM;INDF;PL
definitionsmængde	definitionsmængdernes	N;NOM;DEF;PL
tændstik	tændstikken	N;NOM;DEF;SG
Wikipediabrugerside	Wikipediabrugerside	N;NOM;INDF;SG
federation	federationerne	N;NOM;DEF;PL
penis	penissens	N;NOM;DEF;SG
salme	salmernes	N;NOM;DEF;PL
mangel	manglerne	N;NOM;DEF;PL
sædcelle	sædceller	N;NOM;INDF;PL
opdagelse	opdagelsers	N;GEN;INDF;PL
handler	handler	N;NOM;INDF;SG
veninde	veninden	N;NOM;DEF;SG
beryl	beryllerne	N;NOM;DEF;PL
majonæse	majonæse	N;NOM;INDF;SG
ildslukker	ildslukkerene	N;NOM;DEF;PL
farmand	farmand	N;NOM;INDF;SG
sikkerhed	sikkerheders	N;GEN;INDF;PL
bom	bommene	N;NOM;DEF;PL
tone	toners	N;GEN;INDF;PL
gærdesmutte	gærdesmuttens	N;NOM;DEF;SG
polygon	polygons	N;GEN;INDF;SG
stofmisbrug	stofmisbrug	N;NOM;INDF;PL
lås	låse	N;NOM;INDF;PL
hyl	hylenes	N;NOM;DEF;PL
monopol	monopol	N;NOM;INDF;SG
forsørger	forsørgere	N;NOM;INDF;PL
pagaj	pagajerne	N;NOM;DEF;PL
eksemplar	eksemplar	N;NOM;INDF;SG
stang	stangs	N;GEN;INDF;SG
bønne	bønners	N;GEN;INDF;PL
badeværelse	badeværelserne	N;NOM;DEF;PL
tidsforlængelse	tidsforlængelser	N;NOM;INDF;PL
valg	valget	N;NOM;DEF;SG
vandrehistorie	vandrehistoriens	N;NOM;DEF;SG
væske	væske	N;NOM;INDF;SG
rosévin	rosévinens	N;NOM;DEF;SG
strubehoved	strubehoved	N;NOM;INDF;SG
konkurrence	konkurrencerne	N;NOM;DEF;PL
nomade	nomades	N;GEN;INDF;SG
eventyrer	eventyreren	N;NOM;DEF;SG
klitoris	klitorissernes	N;NOM;DEF;PL
midnat	midnats	N;GEN;INDF;SG
gebyr	gebyrs	N;GEN;INDF;SG
hjærte	hjærte	N;NOM;INDF;SG
menneske	mennesker	N;NOM;INDF;PL
trespring	tresprings	N;GEN;INDF;PL
fingerspids	fingerspidsernes	N;NOM;DEF;PL
kubikmeter	kubikmeter	N;NOM;INDF;SG
appelsinskræl	appelsinskræls	N;GEN;INDF;SG
afasi	afasiernes	N;NOM;DEF;PL
øjenlåg	øjenlågs	N;GEN;INDF;PL
jordnøddeolie	jordnøddeoliernes	N;NOM;DEF;PL
dadel	dadlernes	N;NOM;DEF;PL
nektarin	nektarins	N;GEN;INDF;SG
planteæder	planteæder	N;NOM;INDF;SG
kriger	kriger	N;NOM;INDF;SG
pyrrhussejr	pyrrhussejrenes	N;NOM;DEF;PL
ildsjæl	ildsjælenes	N;NOM;DEF;PL
pind	pind	N;NOM;INDF;SG
hviderusser	hviderussernes	N;NOM;DEF;PL
mølle	møller	N;NOM;INDF;PL
moratorium	moratorium	N;NOM;INDF;SG
ekstranet	ekstranets	N;GEN;INDF;PL
kule	kulens	N;NOM;DEF;SG
kup	kuppet	N;NOM;DEF;SG
eger	egerens	N;NOM;DEF;SG
stegepande	stegepandernes	N;NOM;DEF;PL
mule	mule	N;NOM;INDF;SG
krokodille	krokodillerne	N;NOM;DEF;PL
spisebord	spisebordets	N;NOM;DEF;SG
information	informationerne	N;NOM;DEF;PL
frokost	frokostens	N;NOM;DEF;SG
resistivitet	resistiviteterne	N;NOM;DEF;PL
rekvirere	rekvirerer	V;IND;PRS;ACT
morgenmenneske	morgenmennesker	N;NOM;INDF;PL
julekort	julekortene	N;NOM;DEF;PL
knald	knaldet	N;NOM;DEF;SG
spidsmus	spidsmusens	N;NOM;DEF;SG
ulykke	ulykkes	N;GEN;INDF;SG
historie	historien	N;NOM;DEF;SG
resistivitet	resistiviteters	N;GEN;INDF;PL
samfundsstøtte	samfundsstøtterne	N;NOM;DEF;PL
følelse	følelse	N;NOM;INDF;SG
næsehorn	næsehorns	N;GEN;INDF;PL
golfbold	golfboldens	N;NOM;DEF;SG
konstruktion	konstruktionernes	N;NOM;DEF;PL
hjærte	hjærtets	N;NOM;DEF;SG
halvø	halvø	N;NOM;INDF;SG
konsulat	konsulaters	N;GEN;INDF;PL
pennalhus	pennalhuse	N;NOM;INDF;PL
kuldegysning	kuldegysningers	N;GEN;INDF;PL
ordenstal	ordenstal	N;NOM;INDF;PL
asparges	asparges'	N;GEN;INDF;SG
birkes	birkeset	N;NOM;DEF;SG
udvikler	udvikleren	N;NOM;DEF;SG
langfinger	langfingrenes	N;NOM;DEF;PL
rygsæk	rygsække	N;NOM;INDF;PL
stød	stødet	N;NOM;DEF;SG
kast	kast	N;NOM;INDF;SG
anledning	anledninger	N;NOM;INDF;PL
fædreland	fædreland	N;NOM;INDF;SG
slagsmål	slagsmålenes	N;NOM;DEF;PL
østers	østersene	N;NOM;DEF;PL
lighed	ligheder	N;NOM;INDF;PL
hvede	hvede	N;NOM;INDF;SG
sammenskrivning	sammenskrivnings	N;GEN;INDF;SG
sten	stenen	N;NOM;DEF;SG
øldåse	øldåsen	N;NOM;DEF;SG
satse	satsedes	V;IND;PST;PASS
birkes	birkesene	N;NOM;DEF;PL
antonym	antonymernes	N;NOM;DEF;PL
farmand	farmanden	N;NOM;DEF;SG
ventilere	ventileret	V.PTCP;PST;PASS
oprør	oprørets	N;NOM;DEF;SG
brandbil	brandbil	N;NOM;INDF;SG
konserveringsmiddel	konserveringsmidlernes	N;NOM;DEF;PL
biologi	biologis	N;GEN;INDF;SG
affaldscontainer	affaldscontainer	N;NOM;INDF;SG
fløjt	fløjts	N;GEN;INDF;PL
enhjørning	enhjørningens	N;NOM;DEF;SG
surhedsregulator	surhedsregulatorernes	N;NOM;DEF;PL
trold	trold	N;NOM;INDF;SG
uge	ugernes	N;NOM;DEF;PL
aristokrat	aristokraters	N;GEN;INDF;PL
eksempelsætning	eksempelsætnings	N;GEN;INDF;SG
gyngehest	gyngehesten	N;NOM;DEF;SG
sojaolie	sojaoliers	N;GEN;INDF;PL
måne	månerne	N;NOM;DEF;PL
skråning	skråningernes	N;NOM;DEF;PL
kontakt	kontakt	N;NOM;INDF;SG
marsvin	marsvin	N;NOM;INDF;SG
spilkarakter	spilkarakter	N;NOM;INDF;SG
asparges	aspargesene	N;NOM;DEF;PL
galskab	galskabs	N;GEN;INDF;SG
tysker	tyskeres	N;GEN;INDF;PL
blok	blokkens	N;NOM;DEF;SG
pædagogik	pædagogik	N;NOM;INDF;SG
link	linkenes	N;NOM;DEF;PL
jæger	jægers	N;GEN;INDF;SG
parodi	parodier	N;NOM;INDF;PL
stinkdyr	stinkdyrenes	N;NOM;DEF;PL
synonymordbog	synonymordbøger	N;NOM;INDF;PL
hårbørste	hårbørsters	N;GEN;INDF;PL
aristokrat	aristokrat	N;NOM;INDF;SG
fjæs	fjæsets	N;NOM;DEF;SG
aboriginer	aborigineres	N;GEN;INDF;PL
chimpanse	chimpansens	N;NOM;DEF;SG
majonæse	majonæsers	N;GEN;INDF;PL
filet	fileternes	N;NOM;DEF;PL
kondolere	kondoleret	V.PTCP;PST;PASS
sørøver	sørøvers	N;GEN;INDF;SG
tømme	tømmen	N;NOM;DEF;SG
bombardement	bombardementernes	N;NOM;DEF;PL
rovfugl	rovfuglenes	N;NOM;DEF;PL
kvantificere	kvantificerende	V.PTCP;PRS;ACT
tyveri	tyveriernes	N;NOM;DEF;PL
forårsrulle	forårsruller	N;NOM;INDF;PL
tærte	tærters	N;GEN;INDF;PL
plombe	plomber	N;NOM;INDF;PL
hvidløg	hvidløgenes	N;NOM;DEF;PL
helikopter	helikopteres	N;GEN;INDF;PL
skjald	skjaldens	N;NOM;DEF;SG
kommutere	kommuteres	V;IND;PRS;PASS
påskeæg	påskeæg	N;NOM;INDF;SG
småkage	småkages	N;GEN;INDF;SG
fond	fondens	N;NOM;DEF;SG
valravn	valravnens	N;NOM;DEF;SG
kastanje	kastanjes	N;GEN;INDF;SG
pølse	pølserne	N;NOM;DEF;PL
rappenskralde	rappenskralderne	N;NOM;DEF;PL
møl	møl	N;NOM;INDF;PL
dråbe	dråber	N;NOM;INDF;PL
neuron	neuronerne	N;NOM;DEF;PL
mallemuk	mallemukkerne	N;NOM;DEF;PL
avance	avance	N;NOM;INDF;SG
argument	arguments	N;GEN;INDF;SG
kæderyger	kæderygerne	N;NOM;DEF;PL
afsnit	afsnits	N;GEN;INDF;SG
kusk	kuskes	N;GEN;INDF;PL
lunte	lunte	N;NOM;INDF;SG
guldur	gulduret	N;NOM;DEF;SG
langfredag	langfredagen	N;NOM;DEF;SG
smeltevarme	smeltevarmers	N;GEN;INDF;PL
håndjern	håndjern	N;NOM;INDF;PL
mekaniker	mekanikers	N;GEN;INDF;SG
komodovaran	komodovaranen	N;NOM;DEF;SG
visdomstand	visdomstænder	N;NOM;INDF;PL
rejecocktail	rejecocktails	N;GEN;INDF;PL
nattergal	nattergal	N;NOM;INDF;SG
grøft	grøfts	N;GEN;INDF;SG
lærerinde	lærerinden	N;NOM;DEF;SG
tidsmaskine	tidsmaskiner	N;NOM;INDF;PL
rytter	rytter	N;NOM;INDF;SG
intelligensalder	intelligensaldres	N;GEN;INDF;PL
kæp	kæppen	N;NOM;DEF;SG
musikkonservatorium	musikkonservatoriumer	N;NOM;INDF;PL
violinist	violinisters	N;GEN;INDF;PL
ultimatum	ultimatums	N;GEN;INDF;SG
bersærk	bersærkens	N;NOM;DEF;SG
sydafrikaner	sydafrikanerne	N;NOM;DEF;PL
lipid	lipids	N;GEN;INDF;SG
ytring	ytringer	N;NOM;INDF;PL
skiløber	skiløberen	N;NOM;DEF;SG
babysitter	babysitter	N;NOM;INDF;SG
café au lait	café au laiternes	N;NOM;DEF;PL
hovedserie	hovedseries	N;GEN;INDF;SG
finanslov	finanslovs	N;GEN;INDF;SG
rappenskralde	rappenskralders	N;GEN;INDF;PL
avance	avancens	N;NOM;DEF;SG
pinlighedsfornemmelse	pinlighedsfornemmelse	N;NOM;INDF;SG
juvel	juvel	N;NOM;INDF;SG
computerspilkarakter	computerspilkarakterer	N;NOM;INDF;PL
droge	drogens	N;NOM;DEF;SG
rejecocktail	rejecocktails	N;GEN;INDF;SG
politimester	politimestres	N;GEN;INDF;PL
tur	turs	N;GEN;INDF;SG
dørmåtte	dørmåtter	N;NOM;INDF;PL
syndrom	syndromer	N;NOM;INDF;PL
præsident	præsidentens	N;NOM;DEF;SG
fluesmækker	fluesmækkers	N;GEN;INDF;SG
hvedebrød	hvedebrødene	N;NOM;DEF;PL
fonetik	fonetikker	N;NOM;INDF;PL
bombardement	bombardementers	N;GEN;INDF;PL
antibiotikum	antibiotikum	N;NOM;INDF;SG
jyde	jydes	N;GEN;INDF;SG
kommissær	kommissærerne	N;NOM;DEF;PL
ændring	ændringens	N;NOM;DEF;SG
gerningssted	gerningsstedet	N;NOM;DEF;SG
mare	maren	N;NOM;DEF;SG
lomme	lommen	N;NOM;DEF;SG
albatros	albatrossens	N;NOM;DEF;SG
ingeniør	ingeniørerne	N;NOM;DEF;PL
kontaktlinse	kontaktlinsen	N;NOM;DEF;SG
sikkerhedsvagt	sikkerhedsvagten	N;NOM;DEF;SG
julekort	julekortets	N;NOM;DEF;SG
jordnød	jordnødderne	N;NOM;DEF;PL
oprør	oprøret	N;NOM;DEF;SG
salut	salutternes	N;NOM;DEF;PL
ukrainer	ukrainernes	N;NOM;DEF;PL
præsident	præsidenten	N;NOM;DEF;SG
bussemand	bussemands	N;GEN;INDF;SG
fregne	fregners	N;GEN;INDF;PL
ironi	ironis	N;GEN;INDF;SG
armlægning	armlægningerne	N;NOM;DEF;PL
stådreng	stådrengs	N;GEN;INDF;SG
julekort	julekorts	N;GEN;INDF;PL
kænguru	kænguruernes	N;NOM;DEF;PL
kram	kram	N;NOM;INDF;PL
hæle	hælende	V.PTCP;PRS;ACT
kuldegysning	kuldegysninger	N;NOM;INDF;PL
hov	hoves	N;GEN;INDF;PL
pyrrhussejr	pyrrhussejren	N;NOM;DEF;SG
påfugl	påfugle	N;NOM;INDF;PL
pølse	pølsers	N;GEN;INDF;PL
bøjning	bøjningers	N;GEN;INDF;PL
Wikipediabrugerside	Wikipediabrugersiders	N;GEN;INDF;PL
synliggørelse	synliggørelsers	N;GEN;INDF;PL
fløjte	fløjtens	N;NOM;DEF;SG
hjort	hjortenes	N;NOM;DEF;PL
bagmand	bagmanden	N;NOM;DEF;SG
giraf	girafs	N;GEN;INDF;SG
skoletaske	skoletaskes	N;GEN;INDF;SG
ultralyd	ultralyds	N;GEN;INDF;SG
standart	standarts	N;GEN;INDF;SG
rygsæk	rygsækkes	N;GEN;INDF;PL
ildflue	ildfluer	N;NOM;INDF;PL
bavian	bavianerne	N;NOM;DEF;PL
princip	principper	N;NOM;INDF;PL
talemåde	talemåderne	N;NOM;DEF;PL
akkordeon	akkordeonernes	N;NOM;DEF;PL
uddannelse	uddannelsers	N;GEN;INDF;PL
giro	giro	N;NOM;INDF;SG
græker	grækers	N;GEN;INDF;SG
syllogisme	syllogismen	N;NOM;DEF;SG
vandmelon	vandmeloner	N;NOM;INDF;PL
telefonboks	telefonbokses	N;GEN;INDF;PL
dogme	dogmes	N;GEN;INDF;SG
rune	runens	N;NOM;DEF;SG
fjernsyn	fjernsynet	N;NOM;DEF;SG
romani	romaniernes	N;NOM;DEF;PL
guitar	guitar	N;NOM;INDF;SG
børnehave	børnehaver	N;NOM;INDF;PL
bavian	bavian	N;NOM;INDF;SG
gennembrud	gennembruds	N;GEN;INDF;SG
flygel	flygelets	N;NOM;DEF;SG
anonymisere	anonymiseres	V;IND;PRS;PASS
hvidløg	hvidløg	N;NOM;INDF;PL
mellemniveau	mellemniveauet	N;NOM;DEF;SG
finte	fintens	N;NOM;DEF;SG
affaldscontainer	affaldscontaineren	N;NOM;DEF;SG
svanesang	svanesange	N;NOM;INDF;PL
æblesaft	æblesaft	N;NOM;INDF;SG
tidsforlængelse	tidsforlængelsernes	N;NOM;DEF;PL
arne	arne	N;NOM;INDF;SG
kynisme	kynismens	N;NOM;DEF;SG
bighornfår	bighornfåret	N;NOM;DEF;SG
topolog	topologens	N;NOM;DEF;SG
aubergine	auberginens	N;NOM;DEF;SG
flåde	flådernes	N;NOM;DEF;PL
legeplads	legepladsens	N;NOM;DEF;SG
matrone	matrones	N;GEN;INDF;SG
sygdom	sygdommen	N;NOM;DEF;SG
amager	amageres	N;GEN;INDF;PL
syerske	syersken	N;NOM;DEF;SG
