maskinskrivare	maskinskrivares	N;GEN;INDF;PL
svartskalle	svartskallen	N;NOM;DEF;SG
snickra	snickras	V;IND;PRS;PASS
tyngdlöshet	tyngdlösheten	N;NOM;DEF;SG
livselixir	livselixir	N;NOM;INDF;SG
arbetsmarknad	arbetsmarknadernas	N;GEN;DEF;PL
antilop	antilopens	N;GEN;DEF;SG
skärp	skärps	N;GEN;INDF;SG
kondoleans	kondoleansernas	N;GEN;DEF;PL
plita	plitades	V;IND;PST;PASS
veterinärmedicin	veterinärmedicinens	N;GEN;DEF;SG
presentation	presentationerna	N;NOM;DEF;PL
biträdd	biträtt	ADJ;INDF;NEUT;SG
flegma	flegman	N;NOM;DEF;SG
pakt	pakts	N;GEN;INDF;SG
bogsera	bogserade	V;IND;PST;ACT
posta	postade	V;IND;PST;ACT
sparka	sparkades	V;IND;PST;PASS
tanzanier	tanzanier	N;NOM;INDF;PL
koltrast	koltrasts	N;GEN;INDF;SG
vindrutetorkare	vindrutetorkares	N;GEN;INDF;PL
rockring	rockringarnas	N;GEN;DEF;PL
transportera	transporterats	V.CVB;PASS
applicera	applicera	V;IMP
pys	pys	N;NOM;INDF;SG
verktygslist	verktygslisters	N;GEN;INDF;PL
fängelsestraff	fängelsestraffets	N;GEN;DEF;SG
pansarstyrka	pansarstyrkornas	N;GEN;DEF;PL
lutfisk	lutfisken	N;NOM;DEF;SG
föregå	föregås	V;NFIN;PASS
brandstation	brandstationers	N;GEN;INDF;PL
farthinder	farthinders	N;GEN;INDF;SG
drabba	drabbat	V.CVB;ACT
mög	mögets	N;GEN;DEF;SG
stuga	stugas	N;GEN;INDF;SG
personlighet	personligheters	N;GEN;INDF;PL
avrätta	avrättad	V.PTCP;PST
bakgrundsstrålning	bakgrundsstrålnings	N;GEN;INDF;SG
rödbeta	rödbetas	N;GEN;INDF;SG
eftersträvad	eftersträvade	ADJ;INDF;PL
attraktiv	attraktive	ADJ;DEF;MASC;SG
klet	klets	N;GEN;INDF;SG
rövknulla	rövknullas	V;NFIN;PASS
hänga	häng	V;IMP
mörka	mörka	V;NFIN;ACT
fixera	fixerade	V;IND;PST;ACT
oviktig	oviktigt	ADJ;INDF;NEUT;SG
fåordig	fåordiga	ADJ;DEF
beskuren	beskuren	ADJ;INDF;MASC+FEM;SG
styver	styvrarna	N;NOM;DEF;PL
kid	kid	N;NOM;INDF;SG
fjärrkontroll	fjärrkontrollerna	N;NOM;DEF;PL
värmebehandla	värmebehandlas	V;NFIN;PASS
personlighet	personligheterna	N;NOM;DEF;PL
börjad	började	ADJ;INDF;PL
samspela	samspelade	V;IND;PST;ACT
reservera	reserverar	V;IND;PRS;ACT
volt	volters	N;GEN;INDF;PL
skotska	skotskans	N;GEN;DEF;SG
parkeringsplats	parkeringsplatsen	N;NOM;DEF;SG
valfläsk	valfläsket	N;NOM;DEF;SG
lödkolv	lödkolv	N;NOM;INDF;SG
automatlåda	automatlådornas	N;GEN;DEF;PL
ansvarsområde	ansvarsområdes	N;GEN;INDF;SG
butikskedja	butikskedjans	N;GEN;DEF;SG
bisonoxe	bisonoxars	N;GEN;INDF;PL
besvika	besvika	V;NFIN;ACT
lampskärm	lampskärms	N;GEN;INDF;SG
pingla	pinglat	V.CVB;ACT
splittra	splittrade	V;IND;PST;ACT
motvilja	motviljan	N;NOM;DEF;SG
X-kromosom	X-kromosoms	N;GEN;INDF;SG
drabba	drabbar	V;IND;PRS;ACT
vittnesbörd	vittnesbördet	N;NOM;DEF;SG
blanka	blanka	V;IMP
spakblock	spakblock	N;NOM;INDF;PL
sjukvårdare	sjukvårdares	N;GEN;INDF;SG
ögla	ögla	N;NOM;INDF;SG
kamera	kameras	N;GEN;INDF;SG
vandringstrast	vandringstrastarnas	N;GEN;DEF;PL
service	servicens	N;GEN;DEF;SG
lokomobil	lokomobilen	N;NOM;DEF;SG
amper	amprare	ADJ;COMPV;INDF;PL
bågminut	bågminuts	N;GEN;INDF;SG
socialminister	socialministern	N;NOM;DEF;SG
hyrbil	hyrbilarna	N;NOM;DEF;PL
konsultera	konsulteras	V;NFIN;PASS
återlämna	återlämnar	V;IND;PRS;ACT
byråintendent	byråintendenterna	N;NOM;DEF;PL
putsa	putsa	V;NFIN;ACT
ambassadsekreterare	ambassadsekreteraren	N;NOM;DEF;SG
egyptier	egyptierns	N;GEN;DEF;SG
huvudsak	huvudsakers	N;GEN;INDF;PL
underlig	underligaste	ADJ;SPRL;DEF
veckoberedning	veckoberedning	N;NOM;INDF;SG
mellanfolklig	mellanfolkliga	ADJ;INDF;PL
kontrollfråga	kontrollfrågor	N;NOM;INDF;PL
sekretariat	sekretariats	N;GEN;INDF;SG
brant	brantast	ADJ;SPRL;INDF;PL
fantisera	fantiseras	V;IND;PRS;PASS
andradel	andradelarnas	N;GEN;DEF;PL
vattenpass	vattenpass	N;GEN;INDF;SG
huvudsak	huvudsaker	N;NOM;INDF;PL
förnyare	förnyarens	N;GEN;DEF;SG
cabriolet	cabriolet	N;NOM;INDF;SG
missfall	missfallens	N;GEN;DEF;PL
golfklubb	golfklubbens	N;GEN;DEF;SG
dvärg	dvärgar	N;NOM;INDF;PL
finansiera	finansierande	V.PTCP;PRS
bakgrundsstrålning	bakgrundsstrålningens	N;GEN;DEF;SG
autokrati	autokratins	N;GEN;DEF;SG
acklimatisera	acklimatisera	V;IMP
skatta	skattad	V.PTCP;PST
uttal	uttalets	N;GEN;DEF;SG
arkeologi	arkeologins	N;GEN;DEF;SG
stjärtfena	stjärtfenans	N;GEN;DEF;SG
förhandsgranska	förhandsgranskade	V;IND;PST;ACT
aria	ariorna	N;NOM;DEF;PL
loppmarknad	loppmarknadens	N;GEN;DEF;SG
biträdd	biträdd	ADJ;INDF;MASC+FEM;SG
partikelverb	partikelverben	N;NOM;DEF;PL
homogen	homogen	ADJ;INDF;MASC+FEM;SG
sandal	sandalernas	N;GEN;DEF;PL
arrestera	arresteras	V;IND;PRS;PASS
cykelpump	cykelpumpar	N;NOM;INDF;PL
tittare	tittaren	N;NOM;DEF;SG
mörkna	mörknat	V.CVB;ACT
björntjänst	björntjänst	N;NOM;INDF;SG
korta	kortande	V.PTCP;PRS
W-boson	W-bosons	N;GEN;INDF;SG
delegerad	delegerad	ADJ;INDF;MASC+FEM;SG
vindrutetorkare	vindrutetorkarnas	N;GEN;DEF;PL
glasblock	glasblocks	N;GEN;INDF;SG
uppgradera	uppgraderar	V;IND;PRS;ACT
omfördela	omfördela	V;IMP
avgrund	avgrunder	N;NOM;INDF;PL
volt	volterna	N;NOM;DEF;PL
skåda	skåda	V;NFIN;ACT
plita	plitats	V.CVB;PASS
finansiera	finansierade	V;IND;PST;ACT
klorsyrlighet	klorsyrligheten	N;NOM;DEF;SG
barmhärtig	barmhärtiga	ADJ;INDF;PL
skotte	skotten	N;NOM;DEF;SG
applåd	applåd	N;NOM;INDF;SG
sjögräs	sjögräsets	N;GEN;DEF;SG
kreatur	kreaturs	N;GEN;INDF;SG
motvilja	motvilja	N;NOM;INDF;SG
klot	klotets	N;GEN;DEF;SG
americium	americiumet	N;NOM;DEF;SG
insinuera	insinuerar	V;IND;PRS;ACT
tittare	tittare	N;NOM;INDF;SG
tyngdlöshet	tyngdlöshetens	N;GEN;DEF;SG
pratsam	pratsamma	ADJ;INDF;PL
automatsäkring	automatsäkrings	N;GEN;INDF;SG
spridd	spridda	ADJ;INDF;PL
reflektera	reflekteras	V;IND;PRS;PASS
kossa	kossan	N;NOM;DEF;SG
folka	folkornas	N;GEN;DEF;PL
köttberg	köttberg	N;NOM;INDF;SG
smycka	smycka	V;NFIN;ACT
2-öring	2-öringarna	N;NOM;DEF;PL
obetalbar	obetalbara	ADJ;DEF
jama	jama	V;NFIN;ACT
korta	kortas	V;IND;PRS;PASS
tjetjenska	tjetjenskan	N;NOM;DEF;SG
vacker	vackrast	ADJ;SPRL;INDF;MASC+FEM;SG
försiktig	försiktigare	ADJ;COMPV;DEF
fänghål	fänghålets	N;GEN;DEF;SG
bordlägga	bordläggas	V;NFIN;PASS
mila	mila	N;NOM;INDF;SG
onödig	onödigt	ADJ;INDF;NEUT;SG
tredjeland	tredjeland	N;NOM;INDF;SG
tidsålder	tidsåldrar	N;NOM;INDF;PL
cykelpump	cykelpumparna	N;NOM;DEF;PL
adla	adlande	V.PTCP;PRS
fikon	fikonen	N;NOM;DEF;PL
butikskedja	butikskedjors	N;GEN;INDF;PL
halvsyster	halvsyster	N;NOM;INDF;SG
norrman	norrmännens	N;GEN;DEF;PL
kokosnöt	kokosnöt	N;NOM;INDF;SG
wienerbröd	wienerbröd	N;NOM;INDF;SG
boning	bonings	N;GEN;INDF;SG
toalettpapper	toalettpapperet	N;NOM;DEF;SG
amulett	amuletterna	N;NOM;DEF;PL
älg	älgar	N;NOM;INDF;PL
skärm	skärmarna	N;NOM;DEF;PL
tittare	tittarnas	N;GEN;DEF;PL
oxidationstal	oxidationstalet	N;NOM;DEF;SG
rörlig	rörligast	ADJ;SPRL;INDF;MASC+FEM;SG
livselixir	livselixiret	N;NOM;DEF;SG
assimilerad	assimilerade	ADJ;INDF;PL
kreatur	kreaturet	N;NOM;DEF;SG
solstråle	solstrålarna	N;NOM;DEF;PL
avlägsen	avlägsnare	ADJ;COMPV;INDF;PL
stjärtfena	stjärtfenan	N;NOM;DEF;SG
cab	cab	N;NOM;INDF;SG
beslutsmässig	beslutsmässiga	ADJ;INDF;PL
pagod	pagods	N;GEN;INDF;SG
skank	skanks	N;GEN;INDF;SG
poängtera	poängteras	V;NFIN;PASS
förhandla	förhandla	V;NFIN;ACT
spett	spetts	N;GEN;INDF;SG
borrstativ	borrstativ	N;NOM;INDF;SG
nödrim	nödrimmets	N;GEN;DEF;SG
undervattensbåt	undervattensbåts	N;GEN;INDF;SG
förvåning	förvåningen	N;NOM;DEF;SG
kampanil	kampanilerna	N;NOM;DEF;PL
byråintendent	byråintendent	N;NOM;INDF;SG
penning	penningars	N;GEN;INDF;PL
Riemannyta	Riemannytans	N;GEN;DEF;SG
artondedel	artondedels	N;GEN;INDF;SG
grotta	grottors	N;GEN;INDF;PL
bokmärke	bokmärkenas	N;GEN;DEF;PL
avdragsschack	avdragsschackars	N;GEN;INDF;PL
farthinder	farthinder	N;NOM;INDF;PL
obduktion	obduktionernas	N;GEN;DEF;PL
yrkesutbildning	yrkesutbildning	N;NOM;INDF;SG
fjärrkontroll	fjärrkontrollens	N;GEN;DEF;SG
strukturera	strukturerades	V;IND;PST;PASS
brunbjörn	brunbjörnarnas	N;GEN;DEF;PL
föra in	förts in	V.CVB;PASS
accis	accis	N;GEN;INDF;SG
bannad	bannade	ADJ;DEF
försegla	förseglas	V;NFIN;PASS
örtagård	örtagårdens	N;GEN;DEF;SG
finländare	finländare	N;NOM;INDF;PL
basker	basker	N;NOM;INDF;SG
rannsaka	rannsakas	V;NFIN;PASS
tillförlitlig	tillförlitlig	ADJ;INDF;MASC+FEM;SG
tydlig	tydligare	ADJ;COMPV;DEF
monism	monismens	N;GEN;DEF;SG
gratulera	gratulera	V;IMP
addend	addendens	N;GEN;DEF;SG
smycka	smyckad	V.PTCP;PST
finländare	finländarna	N;NOM;DEF;PL
kräma	krämade	V;IND;PST;ACT
fjällvråk	fjällvråken	N;NOM;DEF;SG
begynnelsebokstav	begynnelsebokstav	N;NOM;INDF;SG
självmordsbombare	självmordsbombares	N;GEN;INDF;PL
vattenmassa	vattenmassornas	N;GEN;DEF;PL
utbrista	utbrast	V;IND;PST;ACT
landare	landare	N;NOM;INDF;SG
tvättbräda	tvättbrädor	N;NOM;INDF;PL
etablerad	etablerade	ADJ;INDF;PL
ambassadsekreterare	ambassadsekreterares	N;GEN;INDF;PL
isbjörn	isbjörnars	N;GEN;INDF;PL
ambitiös	ambitiösare	ADJ;COMPV;INDF;PL
fågelart	fågelarternas	N;GEN;DEF;PL
ungerska	ungerskas	N;GEN;INDF;SG
justera	justerade	V;IND;PST;ACT
konselj	konselj	N;NOM;INDF;SG
forma	formande	V.PTCP;PRS
spektakulär	spektakulära	ADJ;DEF
syntetisera	syntetiserar	V;IND;PRS;ACT
ha råd	ha råd	V;NFIN;ACT
vitrin	vitrinernas	N;GEN;DEF;PL
undkomma	undkom	V;IND;PST;ACT
glutamin	glutamins	N;GEN;INDF;SG
motvilja	motviljas	N;GEN;INDF;SG
arbetslöshetskassa	arbetslöshetskassorna	N;NOM;DEF;PL
clownfisk	clownfiskarna	N;NOM;DEF;PL
politisk	politiske	ADJ;DEF;MASC;SG
ekumenik	ekumeniken	N;NOM;DEF;SG
gotlänning	gotlänningar	N;NOM;INDF;PL
transformator	transformatorer	N;NOM;INDF;PL
rot	rots	N;GEN;INDF;SG
ansvarsområde	ansvarsområden	N;NOM;INDF;PL
byråsekreterare	byråsekreterarna	N;NOM;DEF;PL
spektakulär	spektakulär	ADJ;INDF;MASC+FEM;SG
ambitiös	ambitiösare	ADJ;COMPV;DEF
pornografi	pornografins	N;GEN;DEF;SG
utegångsförbud	utegångsförbudens	N;GEN;DEF;PL
ordna	ordnar	V;IND;PRS;ACT
resultera	resulterade	V;IND;PST;ACT
djurpark	djurparker	N;NOM;INDF;PL
mutkolv	mutkolvarna	N;NOM;DEF;PL
våningssäng	våningssängarna	N;NOM;DEF;PL
reaktiv	reaktivt	ADJ;INDF;NEUT;SG
ungerska	ungerskors	N;GEN;INDF;PL
teologi	teologis	N;GEN;INDF;SG
rättstavning	rättstavningen	N;NOM;DEF;SG
inventarium	inventarium	N;NOM;INDF;SG
forma	format	V.CVB;ACT
bokmärke	bokmärkets	N;GEN;DEF;SG
avkoda	avkodat	V.CVB;ACT
förakt	föraktet	N;NOM;DEF;SG
pariserhjul	pariserhjulens	N;GEN;DEF;PL
messa	messat	V.CVB;ACT
vacker	vackrare	ADJ;COMPV;INDF;NEUT;SG
plita	plita	V;IMP
landmassa	landmassan	N;NOM;DEF;SG
entré	entréers	N;GEN;INDF;PL
maskinskrivare	maskinskrivarnas	N;GEN;DEF;PL
polygami	polygamis	N;GEN;INDF;SG
hurts	hurtsars	N;GEN;INDF;PL
missfall	missfall	N;NOM;INDF;PL
omnämna	omnämns	V;IND;PRS;PASS
fakultet	fakulteternas	N;GEN;DEF;PL
fly	flytts	V.CVB;PASS
handelskompani	handelskompaniernas	N;GEN;DEF;PL
grundsats	grundsats	N;GEN;INDF;SG
vindhål	vindhål	N;NOM;INDF;SG
besitta	besitts	V;IND;PRS;PASS
cricketlag	cricketlaget	N;NOM;DEF;SG
skånk	skånkarna	N;NOM;DEF;PL
vattenplaning	vattenplaningens	N;GEN;DEF;SG
bluffa	bluffa	V;IMP
försälja	försälja	V;NFIN;ACT
bög	bögens	N;GEN;DEF;SG
skiftlås	skiftlås	N;NOM;INDF;SG
myriad	myriaden	N;NOM;DEF;SG
fjärrkontroll	fjärrkontrollernas	N;GEN;DEF;PL
realisering	realiseringens	N;GEN;DEF;SG
övergångsbestämmelse	övergångsbestämmelse	N;NOM;INDF;SG
ministerråd	ministerråd	N;NOM;INDF;SG
svårbegriplig	svårbegripligt	ADJ;INDF;NEUT;SG
sinnebild	sinnebilders	N;GEN;INDF;PL
extrapolation	extrapolationens	N;GEN;DEF;SG
anpassning	anpassningen	N;NOM;DEF;SG
konstituant	konstituants	N;GEN;INDF;SG
lögnare	lögnarens	N;GEN;DEF;SG
månadstidning	månadstidningarna	N;NOM;DEF;PL
kinesa	kinesats	V.CVB;PASS
sia	sia	V;IMP
sultan	sultanerna	N;NOM;DEF;PL
haverera	haverera	V;IMP
webbsida	webbsidornas	N;GEN;DEF;PL
domkapitel	domkapitel	N;NOM;INDF;PL
uppskatta	uppskattats	V.CVB;PASS
kontrastera	kontrasterande	V.PTCP;PRS
mål	målet	N;NOM;DEF;SG
överlåta	överlåtande	V.PTCP;PRS
rölleka	röllekans	N;GEN;DEF;SG
duktig	duktigaste	ADJ;SPRL;DEF;MASC;SG
värmeljus	värmeljus	N;GEN;INDF;SG
rutschkana	rutschkanors	N;GEN;INDF;PL
segla	seglade	V;IND;PST;ACT
försälja	försålde	V;IND;PST;ACT
byggd	byggd	ADJ;INDF;MASC+FEM;SG
musikinstrument	musikinstrument	N;NOM;INDF;SG
gnaga	gnagde	V;IND;PST;ACT
gratulation	gratulationen	N;NOM;DEF;SG
villig	villiga	ADJ;DEF
wienerbröd	wienerbrödets	N;GEN;DEF;SG
rötmånad	rötmånad	N;NOM;INDF;SG
wienerbröd	wienerbröds	N;GEN;INDF;PL
kunskapsutveckling	kunskapsutveckling	N;NOM;INDF;SG
förlag	förlagens	N;GEN;DEF;PL
legitim	legitima	ADJ;INDF;PL
kassako	kassakors	N;GEN;INDF;PL
pärluggla	pärlugglas	N;GEN;INDF;SG
biträda	biträdas	V;NFIN;PASS
fotbollslag	fotbollslaget	N;NOM;DEF;SG
långsam	långsammaste	ADJ;SPRL;DEF
stjärtfena	stjärtfenorna	N;NOM;DEF;PL
betygsätta	betygsättas	V;NFIN;PASS
tillväxa	tillväxa	V;NFIN;ACT
docera	docerande	V.PTCP;PRS
bottenkvark	bottenkvarkar	N;NOM;INDF;PL
konvergent	konvergent	ADJ;INDF;NEUT;SG
ihålig	ihåliga	ADJ;INDF;PL
kamera	kameran	N;NOM;DEF;SG
hamster	hamsterns	N;GEN;DEF;SG
mörkna	mörknade	V;IND;PST;ACT
föregå	föregicks	V;IND;PST;PASS
diskretisera	diskretisera	V;NFIN;ACT
tjock	tjocke	ADJ;DEF;MASC;SG
övergångsbestämmelse	övergångsbestämmelserna	N;NOM;DEF;PL
sikta	siktade	V;IND;PST;ACT
besvika	besviken	V.PTCP;PST
chasidism	chasidismens	N;GEN;DEF;SG
psykologi	psykologin	N;NOM;DEF;SG
kronoassistent	kronoassistent	N;NOM;INDF;SG
störämne	störämnens	N;GEN;INDF;PL
lukta	luktade	V;IND;PST;ACT
opium	opiums	N;GEN;INDF;SG
parameter	parametrars	N;GEN;INDF;PL
petard	petardens	N;GEN;DEF;SG
självmordsbombare	självmordsbombarnas	N;GEN;DEF;PL
tillämplig	tillämplige	ADJ;DEF;MASC;SG
förfining	förfinings	N;GEN;INDF;SG
duktig	duktigare	ADJ;COMPV;INDF;NEUT;SG
värma	värmdes	V;IND;PST;PASS
köttberg	köttbergens	N;GEN;DEF;PL
assisterad	assisterad	ADJ;INDF;MASC+FEM;SG
styver	styvrarnas	N;GEN;DEF;PL
svenne	svenne	N;NOM;INDF;SG
partikelverb	partikelverbet	N;NOM;DEF;SG
tjugoförstadel	tjugoförstadelar	N;NOM;INDF;PL
brytare	brytaren	N;NOM;DEF;SG
farthinder	farthindren	N;NOM;DEF;PL
bogsera	bogsera	V;IMP
mätt	mätta	ADJ;INDF;PL
arrestera	arresterades	V;IND;PST;PASS
matt	mattaste	ADJ;SPRL;DEF;MASC;SG
slå in	slå in	V;NFIN;ACT
precisera	preciseras	V;NFIN;PASS
droppa	droppar	V;IND;PRS;ACT
posta	postades	V;IND;PST;PASS
klassklyfta	klassklyftornas	N;GEN;DEF;PL
strömming	strömmingar	N;NOM;INDF;PL
inkludera	inkludera	V;IMP
stark	starkare	ADJ;COMPV;INDF;PL
fotbollsliga	fotbollsligan	N;NOM;DEF;SG
maskinskrivare	maskinskrivarens	N;GEN;DEF;SG
saftig	saftige	ADJ;DEF;MASC;SG
genteknik	gentekniken	N;NOM;DEF;SG
lärosäte	lärosätenas	N;GEN;DEF;PL
översikt	översikter	N;NOM;INDF;PL
ståltråd	ståltrådars	N;GEN;INDF;PL
mc	mc:n	N;NOM;DEF;SG
koll	koll	N;NOM;INDF;SG
ödla	ödlans	N;GEN;DEF;SG
mystik	mystikens	N;GEN;DEF;SG
diabild	diabilders	N;GEN;INDF;PL
lös	lösast	ADJ;SPRL;INDF;NEUT;SG
individualisera	individualiserade	V;IND;PST;ACT
fläta	flätas	N;GEN;INDF;SG
frisksport	frisksport	N;NOM;INDF;SG
mätt	mättare	ADJ;COMPV;INDF;PL
domkapitel	domkapitels	N;GEN;INDF;SG
putsa	putsades	V;IND;PST;PASS
silvermynt	silvermynt	N;NOM;INDF;PL
delbetänkande	delbetänkande	N;NOM;INDF;SG
sia	sias	V;NFIN;PASS
livvakt	livvakten	N;NOM;DEF;SG
lyrisk	lyrisk	ADJ;INDF;MASC+FEM;SG
informera	informeras	V;NFIN;PASS
betydlig	betydlig	ADJ;INDF;MASC+FEM;SG
einsteinium	einsteiniums	N;GEN;INDF;SG
rosévin	rosévin	N;NOM;INDF;SG
attraktiv	attraktiva	ADJ;DEF
mussla	musslans	N;GEN;DEF;SG
rattlina	rattlinans	N;GEN;DEF;SG
disponera	disponera	V;NFIN;ACT
anlägg	anläggs	N;GEN;INDF;SG
klorsyrlighet	klorsyrlighetens	N;GEN;DEF;SG
pokal	pokalens	N;GEN;DEF;SG
köpman	köpman	N;NOM;INDF;SG
Laplaceoperator	Laplaceoperatorerna	N;NOM;DEF;PL
tunnel	tunnelns	N;GEN;DEF;SG
editera	editerande	V.PTCP;PRS
omfördela	omfördela	V;NFIN;ACT
helig	helige	ADJ;DEF;MASC;SG
postkolonial	postkoloniale	ADJ;DEF;MASC;SG
pakt	pakter	N;NOM;INDF;PL
rannsaka	rannsakar	V;IND;PRS;ACT
betala	betalas	V;IND;PRS;PASS
utarmningsområde	utarmningsområdets	N;GEN;DEF;SG
adertondel	adertondelars	N;GEN;INDF;PL
veckoberedning	veckoberedningarna	N;NOM;DEF;PL
mussla	mussla	N;NOM;INDF;SG
journalfilm	journalfilmens	N;GEN;DEF;SG
interferera	interferera	V;NFIN;ACT
förhandsgranska	förhandsgranskar	V;IND;PRS;ACT
förortsbana	förortsbanornas	N;GEN;DEF;PL
norrman	norrmannen	N;NOM;DEF;SG
styrutrustning	styrutrustningars	N;GEN;INDF;PL
förmögenhet	förmögenheten	N;NOM;DEF;SG
vittnesbörd	vittnesbörd	N;NOM;INDF;PL
ungerska	ungerska	N;NOM;INDF;SG
exakt	exaktast	ADJ;SPRL;INDF;MASC+FEM;SG
individualisera	individualisera	V;IMP
svartna	svartna	V;IMP
hallon	hallons	N;GEN;INDF;PL
absolutistisk	absolutistisk	ADJ;INDF;MASC+FEM;SG
einsteinium	einsteinium	N;NOM;INDF;SG
pingla	pinglas	V;IND;PRS;PASS
obduktion	obduktioners	N;GEN;INDF;PL
pyramid	pyramider	N;NOM;INDF;PL
älg	älgens	N;GEN;DEF;SG
entrecôte	entrecôternas	N;GEN;DEF;PL
tennislag	tennislagets	N;GEN;DEF;SG
fågelskrämma	fågelskrämma	N;NOM;INDF;SG
praseodym	praseodymet	N;NOM;DEF;SG
sjöröveri	sjöröveris	N;GEN;INDF;SG
knop	knops	N;GEN;INDF;SG
transportera	transporteras	V;NFIN;PASS
klorera	klorerad	V.PTCP;PST
tydlig	tydliga	ADJ;DEF
curling	curling	N;NOM;INDF;SG
accelererad	accelererad	ADJ;INDF;MASC+FEM;SG
lös	lösaste	ADJ;SPRL;DEF
dödssiffra	dödssiffrans	N;GEN;DEF;SG
exponent	exponenterna	N;NOM;DEF;PL
släplina	släplinornas	N;GEN;DEF;PL
applåd	applåden	N;NOM;DEF;SG
steglits	steglitsers	N;GEN;INDF;PL
rannsaka	rannsakat	V.CVB;ACT
tönt	tönts	N;GEN;INDF;SG
kil	kil	N;NOM;INDF;SG
affrikata	affrikators	N;GEN;INDF;PL
aioli	aiolin	N;NOM;DEF;SG
isskrapa	isskrapa	N;NOM;INDF;SG
riksbanksdirektör	riksbanksdirektörens	N;GEN;DEF;SG
apotek	apotekens	N;GEN;DEF;PL
strömförstärkning	strömförstärkning	N;NOM;INDF;SG
förortsbana	förortsbana	N;NOM;INDF;SG
femtiondel	femtiondelens	N;GEN;DEF;SG
okinawianska	okinawianskans	N;GEN;DEF;SG
klet	kletet	N;NOM;DEF;SG
fantisera	fantiseras	V;NFIN;PASS
sparka	sparkat	V.CVB;ACT
prenumeration	prenumerationen	N;NOM;DEF;SG
flygföretag	flygföretags	N;GEN;INDF;SG
dalta	daltar	V;IND;PRS;ACT
kisa	kisande	V.PTCP;PRS
deldokument	deldokumentens	N;GEN;DEF;PL
klotter	klotter	N;NOM;INDF;SG
avkoda	avkodades	V;IND;PST;PASS
sladdbarn	sladdbarn	N;NOM;INDF;PL
vänsterpolitik	vänsterpolitikens	N;GEN;DEF;SG
lånord	lånords	N;GEN;INDF;SG
pingla	pinglar	V;IND;PRS;ACT
färgblind	färgblint	ADJ;INDF;NEUT;SG
pressekreterare	pressekreterares	N;GEN;INDF;PL
värma	värmt	V.CVB;ACT
avtjäna	avtjänande	V.PTCP;PRS
hångla	hånglade	V;IND;PST;ACT
vittnesbörd	vittnesbörd	N;NOM;INDF;SG
vittnesbörd	vittnesbördens	N;GEN;DEF;PL
dona	dona	V;NFIN;ACT
övningsfält	övningsfält	N;NOM;INDF;SG
blanka	blankat	V.CVB;ACT
byråsekreterare	byråsekreterarnas	N;GEN;DEF;PL
obduktion	obduktionens	N;GEN;DEF;SG
fågelskrämma	fågelskrämmornas	N;GEN;DEF;PL
tangentbord	tangentbordet	N;NOM;DEF;SG
fornnordiska	fornnordiskans	N;GEN;DEF;SG
neutral	neutralare	ADJ;COMPV;INDF;MASC+FEM;SG
fotbollsliga	fotbollsligans	N;GEN;DEF;SG
svimma	svimmar	V;IND;PRS;ACT
skiss	skiss	N;GEN;INDF;SG
adla	adlad	V.PTCP;PST
skotte	skottar	N;NOM;INDF;PL
personlig	personligaste	ADJ;SPRL;DEF;MASC;SG
licentiatexamen	licentiatexamen	N;NOM;DEF;SG
sjundedel	sjundedels	N;GEN;INDF;SG
obduktion	obduktionerna	N;NOM;DEF;PL
generera	genererades	V;IND;PST;PASS
drabba	drabbas	V;NFIN;PASS
ambitiös	ambitiösaste	ADJ;SPRL;DEF;MASC;SG
betydlig	betydligt	ADJ;INDF;NEUT;SG
pelikan	pelikanen	N;NOM;DEF;SG
cykelhandlare	cykelhandlarna	N;NOM;DEF;PL
pippa	pippat	V.CVB;ACT
näringsliv	näringslivs	N;NOM;INDF;SG
huvudsak	huvudsakerna	N;NOM;DEF;PL
beskuren	beskuret	ADJ;INDF;NEUT;SG
hänga	hängts	V.CVB;PASS
godsägare	godsägarnas	N;GEN;DEF;PL
barm	barm	N;NOM;INDF;SG
dammsky	dammskyarnas	N;GEN;DEF;PL
handtag	handtag	N;NOM;INDF;SG
direktion	direktioners	N;GEN;INDF;PL
lösdriverska	lösdriverskornas	N;GEN;DEF;PL
segla	seglat	V.CVB;ACT
gå som katten kring het gröt	gången	V.PTCP;PST
rikspolischef	rikspolischefers	N;GEN;INDF;PL
raggare	raggare	N;NOM;INDF;PL
humla	humlas	N;GEN;INDF;SG
baksmälla	baksmällan	N;NOM;DEF;SG
vacker	vackre	ADJ;DEF;MASC;SG
tittare	tittarna	N;NOM;DEF;PL
tidsanda	tidsanda	N;NOM;INDF;SG
ministerråd	ministerråds	N;GEN;INDF;PL
exekverad	exekverad	ADJ;INDF;MASC+FEM;SG
handtag	handtags	N;GEN;INDF;SG
domkraft	domkraften	N;NOM;DEF;SG
bakgrundsstrålning	bakgrundsstrålning	N;NOM;INDF;SG
utgiven	utgivna	ADJ;INDF;PL
dränera	dränerats	V.CVB;PASS
cricketlag	cricketlagets	N;GEN;DEF;SG
droppa	droppas	V;NFIN;PASS
övningsköra	övningskör	V;IMP
bisonoxe	bisonoxarnas	N;GEN;DEF;PL
sabbatsår	sabbatsårs	N;GEN;INDF;PL
burka	burkas	N;GEN;INDF;SG
arkeologi	arkeologis	N;GEN;INDF;SG
kuk	kukars	N;GEN;INDF;PL
svartskalle	svartskalles	N;GEN;INDF;SG
strukturera	struktureras	V;NFIN;PASS
neutral	neutrala	ADJ;INDF;PL
brigadgeneral	brigadgeneralers	N;GEN;INDF;PL
blöja	blöjors	N;GEN;INDF;PL
överanstränga	överansträngd	V.PTCP;PST
invänta	inväntande	V.PTCP;PRS
aioli	aiolins	N;GEN;DEF;SG
ombryta	ombrytande	V.PTCP;PRS
disponera	disponera	V;IMP
messa	messats	V.CVB;PASS
neutralisera	neutraliserar	V;IND;PRS;ACT
sav	saven	N;NOM;DEF;SG
bostadskredit	bostadskrediter	N;NOM;INDF;PL
brutta	bruttornas	N;GEN;DEF;PL
maska	maskas	N;GEN;INDF;SG
anglicism	anglicismerna	N;NOM;DEF;PL
riksbanksdirektör	riksbanksdirektörs	N;GEN;INDF;SG
börja	börjats	V.CVB;PASS
ifrågasätta	ifrågasatt	V.CVB;ACT
hallon	hallonets	N;GEN;DEF;SG
rövknulla	rövknullar	V;IND;PRS;ACT
rölleka	röllekor	N;NOM;INDF;PL
monism	monisms	N;GEN;INDF;SG
ballong	ballongers	N;GEN;INDF;PL
altare	altaret	N;NOM;DEF;SG
riksbanksdirektör	riksbanksdirektörers	N;GEN;INDF;PL
automatsäkring	automatsäkringen	N;NOM;DEF;SG
sabbatsår	sabbatsåret	N;NOM;DEF;SG
human	humana	ADJ;DEF
oxidationstal	oxidationstal	N;NOM;INDF;SG
husband	husbandets	N;GEN;DEF;SG
skatta	skattar	V;IND;PRS;ACT
deklarerad	deklarerade	ADJ;INDF;PL
rättstavning	rättstavning	N;NOM;INDF;SG
vira	virats	V.CVB;PASS
diarium	diarier	N;NOM;INDF;PL
kokosnöt	kokosnöts	N;GEN;INDF;SG
finländsk	finländske	ADJ;DEF;MASC;SG
kungarike	kungarike	N;NOM;INDF;SG
bleckblåsinstrument	bleckblåsinstrument	N;NOM;INDF;SG
utropstecken	utropstecknens	N;GEN;DEF;PL
snickra	snickrades	V;IND;PST;PASS
sitta	sitter	V;IND;PRS;ACT
mogen	mogna	ADJ;INDF;PL
harpist	harpists	N;GEN;INDF;SG
deldokument	deldokuments	N;GEN;INDF;SG
tamil	tamil	N;NOM;INDF;SG
fågelvinge	fågelvingar	N;NOM;INDF;PL
elektron	elektroner	N;NOM;INDF;PL
matt	mattare	ADJ;COMPV;INDF;PL
avtalad	avtalat	ADJ;INDF;NEUT;SG
devalvera	devalverat	V.CVB;ACT
föregå	föregången	V.PTCP;PST
blodsocker	blodsockret	N;NOM;DEF;SG
diskretisera	diskretiserat	V.CVB;ACT
styver	styver	N;NOM;INDF;SG
avannonserad	avannonserade	ADJ;DEF;MASC;SG
samhällsvetenskap	samhällsvetenskaper	N;NOM;INDF;PL
delegerad	delegerade	ADJ;DEF;MASC;SG
avsluta	avslutande	V.PTCP;PRS
gångart	gångarten	N;NOM;DEF;SG
knyst	knysts	N;GEN;INDF;SG
blöt	blöta	ADJ;INDF;PL
utropstecken	utropsteckens	N;GEN;INDF;PL
armera	armerats	V.CVB;PASS
2-öring	2-öringar	N;NOM;INDF;PL
dragspel	dragspels	N;GEN;INDF;PL
musikinstrument	musikinstrument	N;NOM;INDF;PL
parkeringshus	parkeringshus	N;NOM;INDF;PL
japan	japanens	N;GEN;DEF;SG
nagellack	nagellacker	N;NOM;INDF;PL
uppskatta	uppskattas	V;NFIN;PASS
solstråle	solstråle	N;NOM;INDF;SG
ducka	duckar	V;IND;PRS;ACT
reservera	reservera	V;IMP
gångart	gångarternas	N;GEN;DEF;PL
amulett	amulettens	N;GEN;DEF;SG
acetat	acetaternas	N;GEN;DEF;PL
praseodym	praseodyms	N;GEN;INDF;SG
mumla	mumlar	V;IND;PRS;ACT
gå som katten kring het gröt	gående	V.PTCP;PRS
regeringsrättssekreterare	regeringsrättssekreterares	N;GEN;INDF;SG
justera	justera	V;NFIN;ACT
gök	göks	N;GEN;INDF;SG
kub	kubernas	N;GEN;DEF;PL
lönnmörda	lönnmördar	V;IND;PRS;ACT
kvark	kvarken	N;NOM;DEF;SG
ändamål	ändamål	N;NOM;INDF;SG
pupill	pupillers	N;GEN;INDF;PL
hallon	hallonen	N;NOM;DEF;PL
tuggummi	tuggummit	N;NOM;DEF;SG
mussla	musslors	N;GEN;INDF;PL
silvermynt	silvermynts	N;GEN;INDF;PL
skiftlås	skiftlås	N;GEN;INDF;PL
begynnelsebokstav	begynnelsebokstavens	N;GEN;DEF;SG
istapp	istapparnas	N;GEN;DEF;PL
drabba	drabbade	V;IND;PST;ACT
akter	aktern	N;NOM;DEF;SG
istapp	istappar	N;NOM;INDF;PL
tvättbräda	tvättbrädorna	N;NOM;DEF;PL
runsvenska	runsvenskas	N;GEN;INDF;SG
kalender	kalenders	N;GEN;INDF;SG
fodra	fodrade	V;IND;PST;ACT
pakt	pakterna	N;NOM;DEF;PL
blek	bleka	ADJ;DEF
tunnbrödsrulle	tunnbrödsrullarna	N;NOM;DEF;PL
prisjägare	prisjägare	N;NOM;INDF;PL
jämna	jämnats	V.CVB;PASS
skevsymmetrisk	skevsymmetriske	ADJ;DEF;MASC;SG
finländsk	finländsk	ADJ;INDF;MASC+FEM;SG
bedömningsgrund	bedömningsgrundernas	N;GEN;DEF;PL
duktig	duktigare	ADJ;COMPV;INDF;PL
lönnmörda	lönnmördade	V;IND;PST;ACT
sandstrand	sandstrand	N;NOM;INDF;SG
elektron	elektrons	N;GEN;INDF;SG
cirkelargument	cirkelarguments	N;GEN;INDF;PL
symmetriaxel	symmetriaxel	N;NOM;INDF;SG
acklimatisera	acklimatiserade	V;IND;PST;ACT
dödssiffra	dödssiffran	N;NOM;DEF;SG
tidsålder	tidsåldrarna	N;NOM;DEF;PL
telega	telegors	N;GEN;INDF;PL
prakt	prakts	N;GEN;INDF;SG
generera	genererad	V.PTCP;PST
kalender	kalendrar	N;NOM;INDF;PL
petard	petards	N;GEN;INDF;SG
forma	forma	V;IMP
hierarki	hierarki	N;NOM;INDF;SG
myriad	myriader	N;NOM;INDF;PL
opinionssiffra	opinionssiffrors	N;GEN;INDF;PL
landmassa	landmassa	N;NOM;INDF;SG
bemöta	bemötts	V.CVB;PASS
vandringstrast	vandringstrast	N;NOM;INDF;SG
byråintendent	byråintendenter	N;NOM;INDF;PL
brandgul	brandgule	ADJ;DEF;MASC;SG
tuggummi	tuggummin	N;NOM;INDF;PL
pungdjur	pungdjurens	N;GEN;DEF;PL
utvandrare	utvandrares	N;GEN;INDF;PL
trovärdig	trovärdiga	ADJ;INDF;PL
pupill	pupiller	N;NOM;INDF;PL
adresseringsstruktur	adresseringsstrukturs	N;GEN;INDF;SG
innebära	inneburit	V.CVB;ACT
landsman	landsman	N;NOM;INDF;SG
imitera	imiterade	V;IND;PST;ACT
hajmal	hajmals	N;GEN;INDF;SG
valkrets	valkrets	N;GEN;INDF;SG
krypton	krypton	N;NOM;INDF;SG
dån	dånet	N;NOM;DEF;SG
kontextuell	kontextuella	ADJ;INDF;PL
hänga	hängande	V.PTCP;PRS
fredspris	fredsprisets	N;GEN;DEF;SG
brunbjörn	brunbjörnarna	N;NOM;DEF;PL
adjungera	adjungeras	V;NFIN;PASS
tidsålder	tidsålders	N;GEN;INDF;SG
släplina	släplinas	N;GEN;INDF;SG
rikspolischef	rikspolischef	N;NOM;INDF;SG
väte	vätes	N;GEN;INDF;SG
verktygslåda	verktygslådas	N;GEN;INDF;SG
tolva	tolvans	N;GEN;DEF;SG
dragtvång	dragtvångs	N;GEN;INDF;SG
rörlig	rörligare	ADJ;COMPV;DEF
gnaga	gnagts	V.CVB;PASS
vobba	vobba	V;NFIN;ACT
borttagning	borttagningen	N;NOM;DEF;SG
laptop	laptopen	N;NOM;DEF;SG
gränsflod	gränsflodens	N;GEN;DEF;SG
utegångsförbud	utegångsförbuds	N;GEN;INDF;SG
extern	externa	ADJ;INDF;PL
maska	maskor	N;NOM;INDF;PL
maning	maningens	N;GEN;DEF;SG
anglicism	anglicismen	N;NOM;DEF;SG
entrecôte	entrecôterna	N;NOM;DEF;PL
rensning	rensningarnas	N;GEN;DEF;PL
behörighet	behörigheterna	N;NOM;DEF;PL
otvivelaktig	otvivelaktiga	ADJ;DEF
brytare	brytare	N;NOM;INDF;SG
stark	stark	ADJ;INDF;MASC+FEM;SG
tveka	tvekar	V;IND;PRS;ACT
justitiedepartement	justitiedepartementens	N;GEN;DEF;PL
kunskapsutveckling	kunskapsutvecklingens	N;GEN;DEF;SG
ballong	ballongerna	N;NOM;DEF;PL
blöja	blöjas	N;GEN;INDF;SG
kassako	kassakos	N;GEN;INDF;SG
kolumn	kolumners	N;GEN;INDF;PL
injektiv	injektiva	ADJ;DEF
kartritare	kartritares	N;GEN;INDF;PL
belägga	belagt	V.CVB;ACT
ljuda	ljuda	V;NFIN;ACT
kungaslott	kungaslottet	N;NOM;DEF;SG
adla	adla	V;NFIN;ACT
personlig	personliga	ADJ;INDF;PL
vattenpass	vattenpass	N;NOM;INDF;SG
veckoberedning	veckoberedningarnas	N;GEN;DEF;PL
verktygslist	verktygslistens	N;GEN;DEF;SG
avtjäna	avtjänas	V;IND;PRS;PASS
talformat	talformatens	N;GEN;DEF;PL
tjock	tjock	ADJ;INDF;MASC+FEM;SG
istapp	istapparna	N;NOM;DEF;PL
fänghål	fänghål	N;NOM;INDF;SG
långvägare	långvägarna	N;NOM;DEF;PL
skatta	skattande	V.PTCP;PRS
celldelning	celldelningars	N;GEN;INDF;PL
utvärdering	utvärderings	N;GEN;INDF;SG
obetalbar	obetalbara	ADJ;INDF;PL
ärlighet	ärlighets	N;GEN;INDF;SG
spingare	spingares	N;GEN;INDF;SG
motorväg	motorvägens	N;GEN;DEF;SG
reflektera	reflekterad	V.PTCP;PST
husrannsakan	husrannsakan	N;NOM;INDF;SG
kemist	kemisten	N;NOM;DEF;SG
pys	pysar	N;NOM;INDF;PL
ordklass	ordklassers	N;GEN;INDF;PL
solbränna	solbrännas	N;GEN;INDF;SG
tredjedel	tredjedelarna	N;NOM;DEF;PL
övergångsbestämmelse	övergångsbestämmelses	N;GEN;INDF;SG
klok	klokaste	ADJ;SPRL;DEF;MASC;SG
basketkorg	basketkorgen	N;NOM;DEF;SG
sömnapné	sömnapnéns	N;GEN;DEF;SG
drabba	drabbades	V;IND;PST;PASS
domkapitel	domkapitlens	N;GEN;DEF;PL
programmera	programmeras	V;NFIN;PASS
kreatur	kreaturs	N;GEN;INDF;PL
jordbruksdepartement	jordbruksdepartements	N;GEN;INDF;PL
sandal	sandalerna	N;NOM;DEF;PL
valkrets	valkretsen	N;NOM;DEF;SG
addend	addenden	N;NOM;DEF;SG
rötmånad	rötmånaderna	N;NOM;DEF;PL
fängelsestraff	fängelsestraffs	N;GEN;INDF;SG
bemöta	bemötas	V;NFIN;PASS
rikspolischef	rikspolischefernas	N;GEN;DEF;PL
vattenpass	vattenpassens	N;GEN;DEF;PL
nagellack	nagellack	N;NOM;INDF;SG
fredsverk	fredsverkens	N;GEN;DEF;PL
omfördela	omfördelad	V.PTCP;PST
myndig	myndiga	ADJ;DEF;MASC;SG
övergå	övergåtts	V.CVB;PASS
klot	klot	N;NOM;INDF;SG
fredspris	fredspris	N;GEN;INDF;PL
fänghål	fänghåls	N;GEN;INDF;SG
telega	telegans	N;GEN;DEF;SG
opponera	opponera	V;IMP
rannsaka	rannsakas	V;IND;PRS;PASS
tvättbräda	tvättbrädas	N;GEN;INDF;SG
långsam	långsam	ADJ;INDF;MASC+FEM;SG
rättstavningskontroll	rättstavningskontroll	N;NOM;INDF;SG
jaka	jaka	V;NFIN;ACT
mätt	mätte	ADJ;DEF;MASC;SG
briserad	briserade	ADJ;DEF;MASC;SG
personlighet	personlighets	N;GEN;INDF;SG
drönare	drönares	N;GEN;INDF;PL
transformator	transformators	N;GEN;INDF;SG
socialminister	socialminister	N;NOM;INDF;SG
molekyl	molekyl	N;NOM;INDF;SG
dvärg	dvärgarnas	N;GEN;DEF;PL
brylling	bryllingar	N;NOM;INDF;PL
modernisera	moderniseras	V;NFIN;PASS
ändra	ändrad	V.PTCP;PST
avhandlad	avhandlade	ADJ;DEF
editera	editerat	V.CVB;ACT
kanslichef	kanslicheferna	N;NOM;DEF;PL
mänska	mänskan	N;NOM;DEF;SG
reglera	reglerande	V.PTCP;PRS
havremjöl	havremjöls	N;GEN;INDF;PL
barkad	barkade	ADJ;DEF
vindrutetorkare	vindrutetorkarna	N;NOM;DEF;PL
kandidera	kandiderat	V.CVB;ACT
beaktandeled	beaktandeleds	N;GEN;INDF;SG
försvarsminister	försvarsminister	N;NOM;INDF;SG
prenumeration	prenumeration	N;NOM;INDF;SG
smycka	smyckats	V.CVB;PASS
könshår	könshårets	N;GEN;DEF;SG
lös	lösast	ADJ;SPRL;INDF;PL
landmassa	landmassor	N;NOM;INDF;PL
säd	säds	N;GEN;INDF;SG
accelererad	accelererat	ADJ;INDF;NEUT;SG
humla	humla	N;NOM;INDF;SG
rimlig	rimligaste	ADJ;SPRL;DEF;MASC;SG
farthinder	farthindret	N;NOM;DEF;SG
vräka	vräks	V;IND;PRS;PASS
vegetarian	vegetarianers	N;GEN;INDF;PL
magnetism	magnetisms	N;GEN;INDF;SG
parameter	parameters	N;GEN;INDF;SG
snökedja	snökedjornas	N;GEN;DEF;PL
ballong	ballong	N;NOM;INDF;SG
fly	flytt	V.CVB;ACT
säkerhetsbälte	säkerhetsbältets	N;GEN;DEF;SG
ansedd	ansedd	ADJ;INDF;MASC+FEM;SG
verktygslåda	verktygslådorna	N;NOM;DEF;PL
bekräftad	bekräftade	ADJ;DEF
valkrets	valkretsarnas	N;GEN;DEF;PL
paketcykel	paketcykel	N;NOM;INDF;SG
hypotes	hypoteser	N;NOM;INDF;PL
förtiga	förtigas	V;NFIN;PASS
avlösning	avlösningarnas	N;GEN;DEF;PL
predika	predikat	V.CVB;ACT
förneka	förneka	V;NFIN;ACT
meck	meck	N;NOM;INDF;SG
docera	docerar	V;IND;PRS;ACT
drönare	drönarens	N;GEN;DEF;SG
adventssöndag	adventssöndagars	N;GEN;INDF;PL
starta	startas	V;NFIN;PASS
stark	starkt	ADJ;INDF;NEUT;SG
medlem	medlemmars	N;GEN;INDF;PL
apotek	apotekets	N;GEN;DEF;SG
behörighet	behörighetens	N;GEN;DEF;SG
vuxen	vuxen	ADJ;INDF;MASC+FEM;SG
bogsera	bogserad	V.PTCP;PST
servitör	servitörer	N;NOM;INDF;PL
reglera	reglera	V;NFIN;ACT
korsning	korsning	N;NOM;INDF;SG
våningssäng	våningssängars	N;GEN;INDF;PL
förspel	förspels	N;GEN;INDF;PL
obetalbar	obetalbar	ADJ;INDF;MASC+FEM;SG
lättmetall	lättmetaller	N;NOM;INDF;PL
applicera	appliceras	V;IND;PRS;PASS
snickra	snickrar	V;IND;PRS;ACT
fasett	fasetternas	N;GEN;DEF;PL
hamna	hamna	V;IMP
avkodare	avkodarna	N;NOM;DEF;PL
rimlig	rimligare	ADJ;COMPV;INDF;PL
utvecklingsfond	utvecklingsfondernas	N;GEN;DEF;PL
svarv	svarvens	N;GEN;DEF;SG
petard	petardernas	N;GEN;DEF;PL
amper	amprare	ADJ;COMPV;DEF
blåhake	blåhakarna	N;NOM;DEF;PL
betydlig	betydliga	ADJ;INDF;PL
mogen	mognare	ADJ;COMPV;INDF;MASC+FEM;SG
vattenkran	vattenkrans	N;GEN;INDF;SG
vira	virades	V;IND;PST;PASS
övningsköra	övningskörande	V.PTCP;PRS
amortera	amortera	V;NFIN;ACT
prägla	präglas	V;NFIN;PASS
duo	duos	N;GEN;INDF;SG
putsa	putsad	V.PTCP;PST
bensinstation	bensinstations	N;GEN;INDF;SG
kid	kidets	N;GEN;DEF;SG
steglits	steglits	N;NOM;INDF;SG
ödla	ödlors	N;GEN;INDF;PL
cent	centen	N;NOM;DEF;SG
mutkolv	mutkolvar	N;NOM;INDF;PL
husa	husans	N;GEN;DEF;SG
neutral	neutralt	ADJ;INDF;NEUT;SG
alkalimetall	alkalimetallerna	N;NOM;DEF;PL
cedilj	cediljerna	N;NOM;DEF;PL
vräka	vräkts	V.CVB;PASS
tass	tass	N;NOM;INDF;SG
luftmassa	luftmassornas	N;GEN;DEF;PL
gruppteori	gruppteorin	N;NOM;DEF;SG
vräka	vräkt	V.PTCP;PST
gångart	gångarter	N;NOM;INDF;PL
peppar	peppar	N;NOM;INDF;SG
sojamjölk	sojamjölkens	N;GEN;DEF;SG
ljuda	ljuden	V.PTCP;PST
leja	lejs	V;IND;PRS;PASS
harpist	harpisterna	N;NOM;DEF;PL
fräsning	fräsningen	N;NOM;DEF;SG
tveka	tvekande	V.PTCP;PRS
svarv	svarv	N;NOM;INDF;SG
kid	kiden	N;NOM;DEF;PL
erkännande	erkännandet	N;NOM;DEF;SG
utbildningsdepartement	utbildningsdepartements	N;GEN;INDF;PL
uttal	uttal	N;NOM;INDF;PL
babylonisk	babyloniska	ADJ;DEF
adjungera	adjungera	V;IMP
adlad	adlade	ADJ;INDF;PL
automorfism	automorfismens	N;GEN;DEF;SG
tydlig	tydliga	ADJ;INDF;PL
surra	surrat	V.CVB;ACT
otvivelaktig	otvivelaktigt	ADJ;INDF;NEUT;SG
kaffebuske	kaffebuskens	N;GEN;DEF;SG
omnämna	omnämnts	V.CVB;PASS
myggnät	myggnätet	N;NOM;DEF;SG
tjejbacill	tjejbacillernas	N;GEN;DEF;PL
emancipation	emancipation	N;NOM;INDF;SG
assisterad	assisterade	ADJ;INDF;PL
amper	ampra	ADJ;DEF
personlig	personligare	ADJ;COMPV;INDF;PL
messa	messas	V;NFIN;PASS
tidsålder	tidsåldrarnas	N;GEN;DEF;PL
avgas	avgasernas	N;GEN;DEF;PL
tönt	tönt	N;NOM;INDF;SG
countrymusik	countrymusik	N;NOM;INDF;SG
tydlig	tydligaste	ADJ;SPRL;DEF
solstråle	solstrålars	N;GEN;INDF;PL
röta	rötor	N;NOM;INDF;PL
finansiera	finansierats	V.CVB;PASS
ihålig	ihålig	ADJ;INDF;MASC+FEM;SG
biträda	biträdde	V;IND;PST;ACT
kräma	krämat	V.CVB;ACT
smörjning	smörjning	N;NOM;INDF;SG
återgivning	återgivningars	N;GEN;INDF;PL
vänsterextrem	vänsterextrema	ADJ;INDF;PL
löna	lönats	V.CVB;PASS
kokosnöt	kokosnötterna	N;NOM;DEF;PL
mumla	mumlande	V.PTCP;PRS
tidsanda	tidsandan	N;NOM;DEF;SG
cirkulationsplats	cirkulationsplatserna	N;NOM;DEF;PL
styvsyskon	styvsyskonens	N;GEN;DEF;PL
ogudaktig	ogudaktiga	ADJ;DEF
längdgrad	längdgraden	N;NOM;DEF;SG
näbb	näbbar	N;NOM;INDF;PL
längdgrad	längdgraders	N;GEN;INDF;PL
bensinstation	bensinstationers	N;GEN;INDF;PL
vinylskiva	vinylskivor	N;NOM;INDF;PL
styvsyskon	styvsyskonet	N;NOM;DEF;SG
stympning	stympningars	N;GEN;INDF;PL
returnera	returnerat	V.CVB;ACT
inspektor	inspektor	N;NOM;INDF;SG
tanzanier	tanzanierna	N;NOM;DEF;PL
köttberg	köttbergets	N;GEN;DEF;SG
fixera	fixerad	V.PTCP;PST
dörrklocka	dörrklockorna	N;NOM;DEF;PL
släkte	släktena	N;NOM;DEF;PL
institutionell	institutionella	ADJ;DEF
självmordsbombare	självmordsbombare	N;NOM;INDF;SG
dalta	daltad	V.PTCP;PST
anpassning	anpassnings	N;GEN;INDF;SG
ansedd	ansedde	ADJ;DEF;MASC;SG
gelé	geléns	N;GEN;DEF;SG
vacker	vacker	ADJ;INDF;MASC+FEM;SG
filtrera	filtrera	V;NFIN;ACT
innehållsförteckning	innehållsförteckningars	N;GEN;INDF;PL
oreda	oredas	N;GEN;INDF;SG
egga	eggade	V;IND;PST;ACT
bojkotta	bojkottats	V.CVB;PASS
lämna	lämnades	V;IND;PST;PASS
accent	accents	N;GEN;INDF;SG
bedöma	bedömd	V.PTCP;PST
rejäl	rejäl	ADJ;INDF;MASC+FEM;SG
återförening	återföreningars	N;GEN;INDF;PL
chiffer	chiffer	N;NOM;INDF;SG
konservera	konservera	V;IMP
arresterad	arresterade	ADJ;DEF;MASC;SG
kroppsvätska	kroppsvätskan	N;NOM;DEF;SG
grapefrukt	grapefrukt	N;NOM;INDF;SG
karaktäristik	karaktäristikens	N;GEN;DEF;SG
cyklamen	cyklamens	N;GEN;INDF;SG
tveksamhet	tveksamheten	N;NOM;DEF;SG
fundera	funderats	V.CVB;PASS
bogserad	bogserad	ADJ;INDF;MASC+FEM;SG
abstinensbesvär	abstinensbesvär	N;NOM;INDF;PL
trettondedel	trettondedelens	N;GEN;DEF;SG
barrikadera	barrikaderar	V;IND;PRS;ACT
rubba	rubbats	V.CVB;PASS
tarm	tarmars	N;GEN;INDF;PL
väteklorid	vätekloriden	N;NOM;DEF;SG
ellips	ellipserna	N;NOM;DEF;PL
tjänstgöring	tjänstgöringars	N;GEN;INDF;PL
återuppbygga	återuppbyggd	V.PTCP;PST
meteorologisk	meteorologiska	ADJ;DEF
svenskspråkig	svenskspråkige	ADJ;DEF;MASC;SG
bokföra	bokfördes	V;IND;PST;PASS
arbetsmiljö	arbetsmiljöns	N;GEN;DEF;SG
kamelia	kameliornas	N;GEN;DEF;PL
växeltunga	växeltunga	N;NOM;INDF;SG
lilltå	lilltås	N;GEN;INDF;SG
grävare	grävare	N;NOM;INDF;SG
positron	positron	N;NOM;INDF;SG
referera	refererats	V.CVB;PASS
sponsra	sponsrat	V.CVB;ACT
cyanamid	cyanamiders	N;GEN;INDF;PL
kungadöme	kungadömet	N;NOM;DEF;SG
höjning	höjning	N;NOM;INDF;SG
kaktus	kaktusars	N;GEN;INDF;PL
guss	guss	N;NOM;INDF;SG
mörda	mördar	V;IND;PRS;ACT
invända	invänd	V.PTCP;PST
underhålla	underhåll	V;IMP
begrundad	begrundade	ADJ;DEF;MASC;SG
ryggsäck	ryggsäcks	N;GEN;INDF;SG
repetition	repetitioner	N;NOM;INDF;PL
ansiktsuttryck	ansiktsuttryckens	N;GEN;DEF;PL
uppvaknande	uppvaknandes	N;GEN;INDF;SG
ställ	ställs	N;GEN;INDF;SG
boson	bosonerna	N;NOM;DEF;PL
leddjur	leddjurs	N;GEN;INDF;SG
jämställdhetsminister	jämställdhetsministrar	N;NOM;INDF;PL
optik	optikens	N;GEN;DEF;SG
dyrka	dyrkad	V.PTCP;PST
errata	erratans	N;GEN;DEF;SG
harkla	harklade	V;IND;PST;ACT
spisa	spisar	V;IND;PRS;ACT
bor	bors	N;GEN;INDF;SG
tvekan	tvekans	N;GEN;DEF;SG
skjutglad	skjutglada	ADJ;INDF;PL
huv	huv	N;NOM;INDF;SG
klorpentafluorid	klorpentafluorid	N;NOM;INDF;SG
bokad	bokade	ADJ;DEF
sidoklass	sidoklassernas	N;GEN;DEF;PL
publicera	publicerande	V.PTCP;PRS
koppargruva	koppargruvornas	N;GEN;DEF;PL
likformig	likformige	ADJ;DEF;MASC;SG
radiator	radiators	N;GEN;INDF;SG
duscha	duschande	V.PTCP;PRS
tjollra	tjollra	V;NFIN;ACT
dårad	dårade	ADJ;DEF
hårddisk	hårddisk	N;NOM;INDF;SG
mugglare	mugglaren	N;NOM;DEF;SG
vapenstillestånd	vapenstillestånden	N;NOM;DEF;PL
jämställa	jämställas	V;NFIN;PASS
slapp	slappe	ADJ;DEF;MASC;SG
akryl	akryls	N;GEN;INDF;SG
ledamot	ledamoten	N;NOM;DEF;SG
tillåta	tillät	V;IND;PST;ACT
integrerad krets	integrerade kretsens	N;GEN;DEF;SG
värderad	värderat	ADJ;INDF;NEUT;SG
besöka	besöker	V;IND;PRS;ACT
kurslitteratur	kurslitteraturens	N;GEN;DEF;SG
skalärprodukt	skalärprodukter	N;NOM;INDF;PL
kyl	kyl	N;NOM;INDF;SG
trafikera	trafikerad	V.PTCP;PST
prälle	prällen	N;NOM;DEF;SG
styvmoder	styvmoderns	N;GEN;DEF;SG
paramagnetism	paramagnetismens	N;GEN;DEF;SG
visualisera	visualiserande	V.PTCP;PRS
prisbasbelopp	prisbasbelopps	N;GEN;INDF;SG
maximera	maximerade	V;IND;PST;ACT
soluppgång	soluppgångars	N;GEN;INDF;PL
uppvakta	uppvaktats	V.CVB;PASS
angelägen	angelägna	ADJ;DEF
kvastfening	kvastfeningarna	N;NOM;DEF;PL
uppförande	uppförande	N;NOM;INDF;SG
direktiv	direktivs	N;GEN;INDF;SG
kyrkbänk	kyrkbänkens	N;GEN;DEF;SG
underavdelning	underavdelningens	N;GEN;DEF;SG
trasdocka	trasdockors	N;GEN;INDF;PL
apelsin	apelsinerna	N;NOM;DEF;PL
kanta	kantat	V.CVB;ACT
absid	absid	N;NOM;INDF;SG
karbinhake	karbinhakens	N;GEN;DEF;SG
smeknamn	smeknamn	N;NOM;INDF;SG
mikro	mikrons	N;GEN;DEF;SG
katedral	katedrals	N;GEN;INDF;SG
spöregn	spöregnets	N;GEN;DEF;SG
administrera	administrera	V;IMP
kulturmyndighet	kulturmyndigheter	N;NOM;INDF;PL
silvergruva	silvergruvors	N;GEN;INDF;PL
främja	främjades	V;IND;PST;PASS
uppenbara	uppenbarats	V.CVB;PASS
poem	poemets	N;GEN;DEF;SG
data	datornas	N;GEN;DEF;PL
egyptologi	egyptologis	N;GEN;INDF;SG
dränerad	dränerade	ADJ;INDF;PL
feg	fegaste	ADJ;SPRL;DEF
världssamfund	världssamfund	N;NOM;INDF;SG
knega	knegas	V;NFIN;PASS
centralism	centralism	N;NOM;INDF;SG
alder	als	ADJ;SPRL;INDF;NEUT;SG
arbetstagare	arbetstagarnas	N;GEN;DEF;PL
fången	fången	ADJ;INDF;MASC+FEM;SG
dömd	dömde	ADJ;DEF;MASC;SG
byråassistent	byråassistenter	N;NOM;INDF;PL
hamstra	hamstrats	V.CVB;PASS
kusk	kuskarnas	N;GEN;DEF;PL
genomgång	genomgångens	N;GEN;DEF;SG
betvivlad	betvivlade	ADJ;DEF
rik	rikast	ADJ;SPRL;INDF;NEUT;SG
gynna	gynnar	V;IND;PRS;ACT
handgranat	handgranatens	N;GEN;DEF;SG
meningslös	meningslösast	ADJ;SPRL;INDF;MASC+FEM;SG
täcke	täcken	N;NOM;INDF;PL
bakad	bakade	ADJ;DEF;MASC;SG
celebritet	celebriteten	N;NOM;DEF;SG
slåss	slåss	V;NFIN;ACT
orgasm	orgasmerna	N;NOM;DEF;PL
monsun	monsunerna	N;NOM;DEF;PL
nominativ	nominativ	N;NOM;INDF;SG
kommunstyrelse	kommunstyrelsernas	N;GEN;DEF;PL
uppräkningsordning	uppräkningsordningars	N;GEN;INDF;PL
preludium	preludiernas	N;GEN;DEF;PL
sann	sannare	ADJ;COMPV;INDF;MASC+FEM;SG
biobränsle	biobränslet	N;NOM;DEF;SG
haj	hajen	N;NOM;DEF;SG
grå	gråare	ADJ;COMPV;INDF;PL
sorti	sortierna	N;NOM;DEF;PL
dividera	dividerar	V;IND;PRS;ACT
argumentation	argumentationers	N;GEN;INDF;PL
förtrycka	förtrycks	V;IND;PRS;PASS
uppenbara	uppenbarar	V;IND;PRS;ACT
blus	blusarna	N;NOM;DEF;PL
angelägenhet	angelägenhets	N;GEN;INDF;SG
förleda	förledd	V.PTCP;PST
ekonomi	ekonomin	N;NOM;DEF;SG
örhänge	örhänge	N;NOM;INDF;SG
passera	passera	V;NFIN;ACT
värma upp	värmas upp	V;NFIN;PASS
uttagning	uttagning	N;NOM;INDF;SG
åkning	åknings	N;GEN;INDF;SG
planera	planerade	V;IND;PST;ACT
otålig	otåligare	ADJ;COMPV;INDF;PL
tålamod	tålamodets	N;GEN;DEF;SG
samlingsdokument	samlingsdokument	N;NOM;INDF;PL
höstack	höstacks	N;GEN;INDF;SG
bedriven	bedrivna	ADJ;DEF
mys	mys	N;NOM;INDF;SG
brännoffer	brännoffrens	N;GEN;DEF;PL
anakronistisk	anakronistiska	ADJ;DEF
idyll	idyllens	N;GEN;DEF;SG
dominera	dominera	V;NFIN;ACT
driven	drivna	ADJ;INDF;PL
landsarkiv	landsarkivs	N;GEN;INDF;SG
vansinnig	vansinnigast	ADJ;SPRL;INDF;MASC+FEM;SG
kommentera	kommenterar	V;IND;PRS;ACT
täkt	täkterna	N;NOM;DEF;PL
armbandsur	armbandsurets	N;GEN;DEF;SG
infrastrukturminister	infrastrukturministrar	N;NOM;INDF;PL
fäst	fäste	ADJ;DEF;MASC;SG
avvisa	avvisar	V;IND;PRS;ACT
styvmoderlig	styvmoderligt	ADJ;INDF;NEUT;SG
underlägg	underlägg	N;NOM;INDF;SG
diskotek	diskotekens	N;GEN;DEF;PL
nobel	nobla	ADJ;DEF
mungipa	mungipornas	N;GEN;DEF;PL
abborre	abborrars	N;GEN;INDF;PL
bred	brett	ADJ;INDF;NEUT;SG
kantarell	kantarellernas	N;GEN;DEF;PL
cumulusmoln	cumulusmolnet	N;NOM;DEF;SG
avledning	avledningarna	N;NOM;DEF;PL
tånagel	tånaglarna	N;NOM;DEF;PL
rikshemvärnschef	rikshemvärnschefen	N;NOM;DEF;SG
cypriot	cyprioternas	N;GEN;DEF;PL
underrubrik	underrubrikens	N;GEN;DEF;SG
realskola	realskolors	N;GEN;INDF;PL
ekosystem	ekosystems	N;GEN;INDF;PL
sona	sonats	V.CVB;PASS
antyda	antydas	V;NFIN;PASS
förena	förenande	V.PTCP;PRS
konstmuseum	konstmuseer	N;NOM;INDF;PL
gena	gena	V;NFIN;ACT
sjukförsäkring	sjukförsäkringens	N;GEN;DEF;SG
bluffare	bluffares	N;GEN;INDF;SG
armveck	armveck	N;NOM;INDF;SG
utföra	utförts	V.CVB;PASS
namne	namnen	N;NOM;DEF;SG
akta	aktande	V.PTCP;PRS
kommunistisk	kommunistiska	ADJ;INDF;PL
ratificera	ratificerande	V.PTCP;PRS
skådeplats	skådeplats	N;GEN;INDF;SG
slavsändare	slavsändares	N;GEN;INDF;PL
tandvård	tandvårds	N;GEN;INDF;SG
kraftnät	kraftnät	N;NOM;INDF;SG
cirkumflex	cirkumflex	N;NOM;INDF;SG
sköterska	sköterskor	N;NOM;INDF;PL
navigera	navigeras	V;NFIN;PASS
anus	anuset	N;NOM;DEF;SG
absolutist	absolutist	N;NOM;INDF;SG
sed	seden	N;NOM;DEF;SG
blänka	blänkte	V;IND;PST;ACT
stämpelur	stämpelur	N;NOM;INDF;PL
sabba	sabbande	V.PTCP;PRS
leksak	leksak	N;NOM;INDF;SG
chatta	chattat	V.CVB;ACT
förnya	förnya	V;NFIN;ACT
gurkskiva	gurkskivors	N;GEN;INDF;PL
algeriska	algeriskor	N;NOM;INDF;PL
läglig	läglige	ADJ;DEF;MASC;SG
hägring	hägringarna	N;NOM;DEF;PL
salva	salva	N;NOM;INDF;SG
besvara	besvara	V;NFIN;ACT
extremist	extremists	N;GEN;INDF;SG
fakturera	fakturerar	V;IND;PRS;ACT
gula	gulans	N;GEN;DEF;SG
oskadlig	oskadlig	ADJ;INDF;MASC+FEM;SG
infiltrera	infiltrerat	V.CVB;ACT
ställa ut	ställtut	V.CVB;ACT
övertala	övertalade	V;IND;PST;ACT
fjäder	fjäderns	N;GEN;DEF;SG
bildstod	bildstoden	N;NOM;DEF;SG
ägiljett	ägiljett	N;NOM;INDF;SG
stock	stockens	N;GEN;DEF;SG
asgarva	asgarvade	V;IND;PST;ACT
kvartsfinal	kvartsfinalen	N;NOM;DEF;SG
nittondel	nittondelarnas	N;GEN;DEF;PL
lagrådsremiss	lagrådsremisserna	N;NOM;DEF;PL
räkenskapsår	räkenskapsårets	N;GEN;DEF;SG
kapitalisera	kapitaliserad	V.PTCP;PST
massaker	massakrernas	N;GEN;DEF;PL
stridsmedel	stridsmedels	N;GEN;INDF;PL
tveksamhet	tveksamheters	N;GEN;INDF;PL
ena	enats	V.CVB;PASS
medellågtyska	medellågtyskan	N;NOM;DEF;SG
rötmånadshistoria	rötmånadshistorierna	N;NOM;DEF;PL
hyperventilera	hyperventilerat	V.CVB;ACT
anrätta	anrättade	V;IND;PST;ACT
radbrytning	radbrytningar	N;NOM;INDF;PL
världsproblem	världsproblemet	N;NOM;DEF;SG
trend	trendens	N;GEN;DEF;SG
atombombning	atombombningars	N;GEN;INDF;PL
smocka	smockans	N;GEN;DEF;SG
anordna	anordnar	V;IND;PRS;ACT
exemplifiera	exemplifierande	V.PTCP;PRS
insexnyckel	insexnycklarnas	N;GEN;DEF;PL
utbildningsplan	utbildningsplanens	N;GEN;DEF;SG
roller	roller	N;NOM;INDF;SG
ljuga	ljug	V;IMP
brödrost	brödrostarnas	N;GEN;DEF;PL
ballongpelare	ballongpelares	N;GEN;INDF;PL
brevvän	brevvänners	N;GEN;INDF;PL
oboist	oboists	N;GEN;INDF;SG
sekundant	sekundanten	N;NOM;DEF;SG
introducera	introducerades	V;IND;PST;PASS
popularisera	populariserat	V.CVB;ACT
plasttallrik	plasttallrik	N;NOM;INDF;SG
provisorisk	provisoriska	ADJ;INDF;PL
adressat	adressater	N;NOM;INDF;PL
målad	målade	ADJ;DEF
konundrum	konundrumet	N;NOM;DEF;SG
galax	galax	N;GEN;INDF;SG
anblick	anblick	N;NOM;INDF;SG
wiccan	wiccanen	N;NOM;DEF;SG
tjugosjundedel	tjugosjundedelar	N;NOM;INDF;PL
bytta	byttan	N;NOM;DEF;SG
upphöra	upphörd	V.PTCP;PST
trettondedel	trettondedel	N;NOM;INDF;SG
bulevard	bulevard	N;NOM;INDF;SG
sexuell	sexuella	ADJ;INDF;PL
acceleration	accelerationerna	N;NOM;DEF;PL
rätts- och expeditionschef	rätts- och expeditionschefs	N;GEN;INDF;SG
daglig	dagligt	ADJ;INDF;NEUT;SG
devis	deviser	N;NOM;INDF;PL
uttala	uttalas	V;IND;PRS;PASS
stapla	stapla	V;NFIN;ACT
exponentiell	exponentiellt	ADJ;INDF;NEUT;SG
finlandssvenska	finlandssvenskan	N;NOM;DEF;SG
rationalisera	rationalisera	V;NFIN;ACT
riksgäldskontor	riksgäldskontorens	N;GEN;DEF;PL
utgå	utgående	V.PTCP;PRS
kommendör	kommendörernas	N;GEN;DEF;PL
bekymrad	bekymrade	ADJ;DEF;MASC;SG
machnoist	machnoistens	N;GEN;DEF;SG
kackig	kackigt	ADJ;INDF;NEUT;SG
servitris	servitris	N;GEN;INDF;SG
planetbana	planetbanor	N;NOM;INDF;PL
ofarlig	ofarliga	ADJ;INDF;PL
storleksordning	storleksordningar	N;NOM;INDF;PL
insatsstyrka	insatsstyrkans	N;GEN;DEF;SG
fattig	fattigast	ADJ;SPRL;INDF;MASC+FEM;SG
annullera	annullerades	V;IND;PST;PASS
deportera	deporterar	V;IND;PRS;ACT
åskådare	åskådaren	N;NOM;DEF;SG
sommelier	sommelierer	N;NOM;INDF;PL
translation	translationer	N;NOM;INDF;PL
promenera	promenerades	V;IND;PST;PASS
kategorisera	kategoriserande	V.PTCP;PRS
skämma bort	skäms	V;IND;PRS;PASS
termistor	termistor	N;NOM;INDF;SG
tryckeri	tryckeriernas	N;GEN;DEF;PL
allegori	allegoris	N;GEN;INDF;SG
jäsa	jäst	V.CVB;ACT
dagtinga	dagtingar	V;IND;PRS;ACT
avskeda	avskedat	V.CVB;ACT
summera	summerade	V;IND;PST;ACT
inäga	inäga	N;NOM;INDF;SG
rycka	ryckt	V.PTCP;PST
inferno	infernos	N;GEN;INDF;SG
cession	cessionerna	N;NOM;DEF;PL
skomakeri	skomakeri	N;NOM;INDF;SG
departementsråd	departementsråd	N;NOM;INDF;SG
specialistsjuksköterska	specialistsjuksköterskornas	N;GEN;DEF;PL
egenmäktigt förfarande	egenmäktigt förfarandes	N;GEN;INDF;SG
bevaka	bevakad	V.PTCP;PST
kvarleva	kvarlevas	N;GEN;INDF;SG
nattklubb	nattklubbarnas	N;GEN;DEF;PL
serb	serberna	N;NOM;DEF;PL
begå	begående	V.PTCP;PRS
fruktansvärd	fruktansvärda	ADJ;INDF;PL
förlaga	förlagan	N;NOM;DEF;SG
utrikesminister	utrikesministrar	N;NOM;INDF;PL
slumpvis	slumpvise	ADJ;DEF;MASC;SG
slovenska	slovenskans	N;GEN;DEF;SG
fallera	fallera	V;NFIN;ACT
cotangent	cotangenters	N;GEN;INDF;PL
beröra	berörd	V.PTCP;PST
stod	stoden	N;NOM;DEF;SG
kolla	kolla	V;NFIN;ACT
filformat	filformatets	N;GEN;DEF;SG
avskeda	avskeda	V;IMP
smycke	smyckens	N;GEN;INDF;PL
konserv	konserven	N;NOM;DEF;SG
förpliktelse	förpliktelserna	N;NOM;DEF;PL
solnedgång	solnedgången	N;NOM;DEF;SG
stanna	stanna	V;IMP
stamma	stammade	V;IND;PST;ACT
jordreform	jordreformernas	N;GEN;DEF;PL
häger	hägrarna	N;NOM;DEF;PL
aldehyd	aldehydernas	N;GEN;DEF;PL
bygdemålsfärgad	bygdemålsfärgat	ADJ;INDF;NEUT;SG
adressera	adresserar	V;IND;PRS;ACT
lustig	lustig	ADJ;INDF;MASC+FEM;SG
armerad	armerad	ADJ;INDF;MASC+FEM;SG
optisk	optiske	ADJ;DEF;MASC;SG
ond	ondaste	ADJ;SPRL;DEF
bröstkota	bröstkotor	N;NOM;INDF;PL
oemotståndlig	oemotståndlige	ADJ;DEF;MASC;SG
subtil	subtilt	ADJ;INDF;NEUT;SG
terrorisera	terrorisera	V;IMP
gödsel	gödsel	N;NOM;INDF;SG
graviditet	graviditets	N;GEN;INDF;SG
berömd	berömda	ADJ;INDF;PL
semifinal	semifinalers	N;GEN;INDF;PL
annex	annexet	N;NOM;DEF;SG
vårting	vårtings	N;GEN;INDF;PL
definiera	definierande	V.PTCP;PRS
vårta	vårtas	N;GEN;INDF;SG
fikus	fikusens	N;GEN;DEF;SG
röstsiffra	röstsiffrornas	N;GEN;DEF;PL
avstånd	avstånd	N;NOM;INDF;SG
ackommoderad	ackommoderade	ADJ;DEF;MASC;SG
femtiöring	femtiöringarnas	N;GEN;DEF;PL
nukleär	nukleäre	ADJ;DEF;MASC;SG
ödmjuk	ödmjuke	ADJ;DEF;MASC;SG
sabba	sabba	V;NFIN;ACT
döskalle	döskallars	N;GEN;INDF;PL
fransyska	fransyskan	N;NOM;DEF;SG
världsmästerskap	världsmästerskaps	N;GEN;INDF;SG
symbolisk	symboliska	ADJ;INDF;PL
produktionsdelningsavtal	produktionsdelningsavtalets	N;GEN;DEF;SG
törstig	törstiga	ADJ;INDF;PL
ödmjuk	ödmjuka	ADJ;DEF
kemisk	kemiske	ADJ;DEF;MASC;SG
finlandssvenska	finlandssvenska	N;NOM;INDF;SG
mens	mensens	N;GEN;DEF;SG
jos	jos	N;NOM;INDF;SG
kläcka	kläcktes	V;IND;PST;PASS
automatiserad	automatiserat	ADJ;INDF;NEUT;SG
gnistra	gnistrande	V.PTCP;PRS
kartläggning	kartläggningarna	N;NOM;DEF;PL
exemplifiera	exemplifieras	V;NFIN;PASS
trötta	tröttas	V;IND;PRS;PASS
påbyggnadslinje	påbyggnadslinjen	N;NOM;DEF;SG
bryn	bryn	N;NOM;INDF;PL
nervös	nervös	ADJ;INDF;MASC+FEM;SG
österrikiska	österrikiskor	N;NOM;INDF;PL
köl	kölarna	N;NOM;DEF;PL
knoge	knogar	N;NOM;INDF;PL
oskiljaktig	oskiljaktiga	ADJ;DEF
dödlighet	dödlighets	N;GEN;INDF;SG
publicering	publiceringen	N;NOM;DEF;SG
hjälppräst	hjälpprästers	N;GEN;INDF;PL
baltisk	baltiska	ADJ;INDF;PL
underrätta	underrätta	V;NFIN;ACT
sväva	sväva	V;IMP
þriþi	þriþia	ADJ;SPRL;INDF;NEUT;SG
passera	passerats	V.CVB;PASS
användarnamn	användarnamnens	N;GEN;DEF;PL
teism	teismen	N;NOM;DEF;SG
hyrd	hyrd	ADJ;INDF;MASC+FEM;SG
adressbok	adressboks	N;GEN;INDF;SG
bäcken	bäckenet	N;NOM;DEF;SG
glad	gladast	ADJ;SPRL;INDF;NEUT;SG
panteism	panteismens	N;GEN;DEF;SG
järnmalm	järnmalms	N;GEN;INDF;SG
intervenera	intervenerande	V.PTCP;PRS
gränd	gränderna	N;NOM;DEF;PL
bifoga	bifoga	V;NFIN;ACT
anpassa	anpassande	V.PTCP;PRS
regionkommitté	regionkommittéerna	N;NOM;DEF;PL
paja	pajats	V.CVB;PASS
neutron	neutroner	N;NOM;INDF;PL
formulera	formuleras	V;NFIN;PASS
schweiziska	schweiziskorna	N;NOM;DEF;PL
gråna	gråna	V;IMP
kombinatorik	kombinatorikens	N;GEN;DEF;SG
mellanrum	mellanrum	N;NOM;INDF;PL
lärarinna	lärarinnorna	N;NOM;DEF;PL
nätbedrägeri	nätbedrägeris	N;GEN;INDF;SG
överskugga	överskugga	V;NFIN;ACT
anmäla	anmäla	V;NFIN;ACT
värnpliktskongress	värnpliktskongressernas	N;GEN;DEF;PL
saxofon	saxofonen	N;NOM;DEF;SG
utveckla	utvecklad	V.PTCP;PST
pudel	pudelns	N;GEN;DEF;SG
epifyt	epifytens	N;GEN;DEF;SG
ogynnsam	ogynnsamt	ADJ;INDF;NEUT;SG
oordning	oordningens	N;GEN;DEF;SG
antända	antänt	V.CVB;ACT
brolägga	brolagt	V.CVB;ACT
misshandla	misshandlande	V.PTCP;PRS
kryssruta	kryssrutor	N;NOM;INDF;PL
mineral	minerals	N;GEN;INDF;SG
företagsledning	företagsledningarnas	N;GEN;DEF;PL
dockad	dockad	ADJ;INDF;MASC+FEM;SG
rama in	ramar in	V;IND;PRS;ACT
trollkona	trollkonorna	N;NOM;DEF;PL
adeqvat	adeqvata	ADJ;DEF
sympatisör	sympatisören	N;NOM;DEF;SG
ekonom	ekonomen	N;NOM;DEF;SG
tjeckiska	tjeckiskornas	N;GEN;DEF;PL
slippa	slapp	V;IND;PST;ACT
norna	nornors	N;GEN;INDF;PL
perfektparticip	perfektparticips	N;GEN;INDF;SG
doja	dojans	N;GEN;DEF;SG
stressa	stressats	V.CVB;PASS
cirkumflex	cirkumflexer	N;NOM;INDF;PL
vävnad	vävnadens	N;GEN;DEF;SG
stormsvala	stormsvalornas	N;GEN;DEF;PL
abort	aborten	N;NOM;DEF;SG
jordskalv	jordskalven	N;NOM;DEF;PL
simulera	simulerande	V.PTCP;PRS
talande	talande	N;NOM;INDF;SG
viss	vissaste	ADJ;SPRL;DEF
världshistoria	världshistoriens	N;GEN;DEF;SG
saxofon	saxofons	N;GEN;INDF;SG
middag	middagars	N;GEN;INDF;PL
blodgivare	blodgivare	N;NOM;INDF;SG
brotsch	brotschar	N;NOM;INDF;PL
lus	lusens	N;GEN;DEF;SG
investeringsbank	investeringsbanken	N;NOM;DEF;SG
tokig	tokigast	ADJ;SPRL;INDF;NEUT;SG
hamnskiftare	hamnskiftarnas	N;GEN;DEF;PL
ornitologi	ornitologi	N;NOM;INDF;SG
asterisk	asteriskens	N;GEN;DEF;SG
skör	skörare	ADJ;COMPV;INDF;NEUT;SG
orörlig	orörliga	ADJ;DEF
burgen	burgen	ADJ;INDF;MASC+FEM;SG
böjlig	böjlig	ADJ;INDF;MASC+FEM;SG
förhöra	förhörs	V;IND;PRS;PASS
skämtsam	skämtsamma	ADJ;INDF;PL
värna	värnande	V.PTCP;PRS
förefalla	förefall	V;IMP
julgran	julgrans	N;GEN;INDF;SG
häxa	häxorna	N;NOM;DEF;PL
lie	liars	N;GEN;INDF;PL
förbinda	förbunden	V.PTCP;PST
attrahera	attrahera	V;IMP
uppstå	uppstod	V;IND;PST;ACT
evangelium	evangeliet	N;NOM;DEF;SG
pricka av	avprickad	V.PTCP;PST
päronjuice	päronjuicers	N;GEN;INDF;PL
huvudägare	huvudägarnas	N;GEN;DEF;PL
flöjtist	flöjtists	N;GEN;INDF;SG
anus	anusets	N;GEN;DEF;SG
fyllo	fyllot	N;NOM;DEF;SG
utgiftstak	utgiftstaks	N;GEN;INDF;PL
barka	barkande	V.PTCP;PRS
chipspåse	chipspåsarna	N;NOM;DEF;PL
elchock	elchockernas	N;GEN;DEF;PL
turistfälla	turistfällas	N;GEN;INDF;SG
exotisk	exotiska	ADJ;INDF;PL
plommonträd	plommonträds	N;GEN;INDF;PL
diskriminera	diskriminera	V;IMP
pandeiro	pandeiro	N;NOM;INDF;SG
telefonnummer	telefonnummer	N;NOM;INDF;PL
karusell	karusellernas	N;GEN;DEF;PL
förlora	förlorat	V.CVB;ACT
diskursanalys	diskursanalys	N;GEN;INDF;SG
italiensk	italienskt	ADJ;INDF;NEUT;SG
knarka	knarkats	V.CVB;PASS
hitlista	hitlistorna	N;NOM;DEF;PL
kommunfullmäktige	kommunfullmäktige	N;NOM;DEF;SG
angripa	angrep	V;IND;PST;ACT
indoktrinera	indoktrineras	V;NFIN;PASS
entlediga	entlediga	V;NFIN;ACT
struts	strutsarna	N;NOM;DEF;PL
mellansvep	mellansvepet	N;NOM;DEF;SG
irländska	irländska	N;NOM;INDF;SG
deportera	deportera	V;NFIN;ACT
kommitté	kommittéerna	N;NOM;DEF;PL
forta	forta	V;IMP
slöjd	slöjderna	N;NOM;DEF;PL
textram	textramar	N;NOM;INDF;PL
trettiondel	trettiondelar	N;NOM;INDF;PL
språngbräda	språngbrädan	N;NOM;DEF;SG
fraktion	fraktionen	N;NOM;DEF;SG
Higgsboson	Higgsboson	N;NOM;INDF;SG
gosedjur	gosedjur	N;NOM;INDF;PL
jagare	jagare	N;NOM;INDF;PL
kammarrättspresident	kammarrättspresidenterna	N;NOM;DEF;PL
dödsdom	dödsdoms	N;GEN;INDF;SG
dödskalle	dödskallen	N;NOM;DEF;SG
ficklampa	ficklampornas	N;GEN;DEF;PL
show	show	N;NOM;INDF;SG
byta	bytande	V.PTCP;PRS
kungsörn	kungsörnens	N;GEN;DEF;SG
asyl	asylerna	N;NOM;DEF;PL
koppla	koppla	V;IMP
yttrandefrihetsgrundlag	yttrandefrihetsgrundlags	N;GEN;INDF;SG
begonia	begoniornas	N;GEN;DEF;PL
diffunderad	diffunderade	ADJ;DEF
skörlevnad	skörlevnad	N;NOM;INDF;SG
tiga	teg	V;IND;PST;ACT
skymta	skymtar	V;IND;PRS;ACT
grannsämja	grannsämjan	N;NOM;DEF;SG
diskriminera	diskriminerar	V;IND;PRS;ACT
svartsjuk	svartsjukare	ADJ;COMPV;INDF;NEUT;SG
dokumentera	dokumenteras	V;NFIN;PASS
förverkliga	förverkliga	V;NFIN;ACT
symbolisera	symboliserade	V;IND;PST;ACT
nyttig	nyttigare	ADJ;COMPV;INDF;MASC+FEM;SG
arrende	arrendens	N;GEN;INDF;PL
musknapp	musknapps	N;GEN;INDF;SG
säga	sagt	V.CVB;ACT
världsmakt	världsmakts	N;GEN;INDF;SG
hårdskiva	hårdskivans	N;GEN;DEF;SG
ramlag	ramlagarna	N;NOM;DEF;PL
anhängare	anhängares	N;GEN;INDF;PL
inspirerande	inspirerande	ADJ;DEF;MASC;SG
fastna	fastnade	V;IND;PST;ACT
följa	följa	V;NFIN;ACT
avfalla	avfallande	V.PTCP;PRS
styrsystem	styrsystem	N;NOM;INDF;SG
obetydlig	obetydligare	ADJ;COMPV;INDF;MASC;SG
kartlägga	kartläggas	V;NFIN;PASS
inkast	inkast	N;NOM;INDF;SG
sköljmedel	sköljmedlet	N;NOM;DEF;SG
likna	liknas	V;IND;PRS;PASS
fjätter	fjätter	N;NOM;INDF;SG
terapeutisk	terapeutiske	ADJ;DEF;MASC;SG
banda	bandat	V.CVB;ACT
differens	differens	N;NOM;INDF;SG
kungöra	kungöra	V;NFIN;ACT
bistå	bistå	V;NFIN;ACT
grävling	grävlingar	N;NOM;INDF;PL
qvot	qvoter	N;NOM;INDF;PL
dyrka	dyrka	V;NFIN;ACT
kvalitetssäkring	kvalitetssäkring	N;NOM;INDF;SG
dräng	dräng	N;NOM;INDF;SG
tankesmedja	tankesmedjor	N;NOM;INDF;PL
notera	noterad	V.PTCP;PST
undantag	undantags	N;GEN;INDF;PL
standardisering	standardisering	N;NOM;INDF;SG
ysta	ystas	V;IND;PRS;PASS
ställföreträdare	ställföreträdarens	N;GEN;DEF;SG
reformator	reformatorers	N;GEN;INDF;PL
dräpa	dräp	V;IMP
fulhack	fulhack	N;NOM;INDF;SG
kaviar	kaviaren	N;NOM;DEF;SG
initiativ	initiativens	N;GEN;DEF;PL
kvick	kvickt	ADJ;INDF;NEUT;SG
dieselmotor	dieselmotors	N;GEN;INDF;SG
huvudkälla	huvudkälla	N;NOM;INDF;SG
diplomati	diplomati	N;NOM;INDF;SG
kulturskapare	kulturskaparen	N;NOM;DEF;SG
acceptera	accepterats	V.CVB;PASS
miffo	miffo	N;NOM;INDF;SG
förnuftig	förnuftigt	ADJ;INDF;NEUT;SG
blunda	blunda	V;NFIN;ACT
långtradarchaufför	långtradarchaufför	N;NOM;INDF;SG
förvara	förvaras	V;IND;PRS;PASS
sucka	suckat	V.CVB;ACT
bländare	bländares	N;GEN;INDF;PL
häxa	häxan	N;NOM;DEF;SG
överdriva	överdriver	V;IND;PRS;ACT
realskola	realskola	N;NOM;INDF;SG
farlig	farliga	ADJ;DEF
sirap	sirapens	N;GEN;DEF;SG
foster	fostrens	N;GEN;DEF;PL
marsvin	marsvins	N;GEN;INDF;SG
ryggkota	ryggkotorna	N;NOM;DEF;PL
viceamiral	viceamiralers	N;GEN;INDF;PL
rotationsyta	rotationsytas	N;GEN;INDF;SG
frisinnad	frisinnade	ADJ;DEF;MASC;SG
dogmatisk	dogmatiska	ADJ;INDF;PL
utbyte	utbytena	N;NOM;DEF;PL
oändlig	oändligast	ADJ;SPRL;INDF;NEUT;SG
bryggkaffe	bryggkaffe	N;NOM;INDF;SG
otrolig	otroliga	ADJ;INDF;PL
australier	australier	N;NOM;INDF;SG
uppräkna	uppräknat	V.CVB;ACT
sjukna	sjukna	V;IMP
respektera	respekterar	V;IND;PRS;ACT
självuppfyllande profetia	självuppfyllande profetia	N;NOM;INDF;SG
odödlig	odödliga	ADJ;INDF;PL
vulgär	vulgäre	ADJ;DEF;MASC;SG
fruktträd	fruktträds	N;GEN;INDF;SG
resurs	resursen	N;NOM;DEF;SG
träffa	träffades	V;IND;PST;PASS
webbläsare	webbläsarnas	N;GEN;DEF;PL
coda	codan	N;NOM;DEF;SG
tillämpa	tillämpar	V;IND;PRS;ACT
reassurera	reassurera	V;NFIN;ACT
skicklig	skickligare	ADJ;COMPV;INDF;MASC+FEM;SG
blåneger	blånegrers	N;GEN;INDF;PL
dogmatiker	dogmatikerns	N;GEN;DEF;SG
hypotenusa	hypotenusa	N;NOM;INDF;SG
såpa	såpas	N;GEN;INDF;SG
like	liken	N;NOM;DEF;SG
formgivare	formgivarna	N;NOM;DEF;PL
stortå	stortåns	N;GEN;DEF;SG
inrikta	inriktas	V;IND;PRS;PASS
kisel	kisel	N;NOM;INDF;SG
infektera	infektera	V;IMP
mårka	mårkor	N;NOM;INDF;PL
späda	spädas	V;NFIN;PASS
överblicka	överblickande	V.PTCP;PRS
slå sig i slang	slå sig i slang	V;NFIN;ACT
kaliumsorbat	kaliumsorbat	N;NOM;INDF;SG
förstärka	förstärkt	V.CVB;ACT
logikelement	logikelementen	N;NOM;DEF;PL
valberedare	valberedare	N;NOM;INDF;SG
identifierad	identifierade	ADJ;INDF;PL
lämna	lämnats	V.CVB;PASS
utbjuda	utbjudits	V.CVB;PASS
segelfartyg	segelfartyg	N;NOM;INDF;PL
ackuschörska	ackuschörskornas	N;GEN;DEF;PL
associativitet	associativitetens	N;GEN;DEF;SG
keltisk	keltiske	ADJ;DEF;MASC;SG
tips	tipsets	N;GEN;DEF;SG
nagel	naglars	N;NOM;INDF;PL
vävstol	vävstolarnas	N;GEN;DEF;PL
placering	placeringarnas	N;GEN;DEF;PL
fräckhet	fräckheterna	N;NOM;DEF;PL
chanson	chansonens	N;GEN;DEF;SG
passare	passaren	N;NOM;DEF;SG
emulerad	emulerade	ADJ;INDF;PL
blodtryck	blodtrycks	N;GEN;INDF;SG
produktionsordbok	produktionsordboken	N;NOM;DEF;SG
arvedel	arvedel	N;NOM;INDF;SG
blockera	blockerats	V.CVB;PASS
korrigera	korrigerades	V;IND;PST;PASS
kontinuerlig	kontinuerlig	ADJ;INDF;MASC+FEM;SG
plocka	plockar	V;IND;PRS;ACT
inrätta	inrätta	V;NFIN;ACT
fattning	fattnings	N;GEN;INDF;SG
statschef	statschef	N;NOM;INDF;SG
fredsforskning	fredsforskningens	N;GEN;DEF;SG
påstå	påstås	V;IND;PRS;PASS
skrika	skrikits	V.CVB;PASS
neurotoxikologi	neurotoxikologi	N;NOM;INDF;SG
högskoleenhet	högskoleenheterna	N;NOM;DEF;PL
torr	torr	ADJ;INDF;MASC+FEM;SG
förslagen	förslagna	ADJ;DEF
klasskamrat	klasskamrater	N;NOM;INDF;PL
upptid	upptidens	N;GEN;DEF;SG
föreningsfrihet	föreningsfrihet	N;NOM;INDF;SG
skjutmått	skjutmåtts	N;GEN;INDF;PL
styvfamilj	styvfamiljens	N;GEN;DEF;SG
blatte	blatten	N;NOM;DEF;SG
kyrkbänk	kyrkbänkar	N;NOM;INDF;PL
sarkasm	sarkasmer	N;NOM;INDF;PL
hörn	hörns	N;GEN;INDF;PL
applådera	applåderande	V.PTCP;PRS
avhandla	avhandlat	V.CVB;ACT
fyllo	fyllon	N;NOM;INDF;PL
nödutgång	nödutgångar	N;NOM;INDF;PL
testare	testare	N;NOM;INDF;PL
antenn	antenners	N;GEN;INDF;PL
magsmärta	magsmärtan	N;NOM;DEF;SG
raljera	raljerar	V;IND;PRS;ACT
ändrad	ändrade	ADJ;INDF;PL
gudmor	gudmor	N;NOM;INDF;SG
personregister	personregisters	N;GEN;INDF;PL
kvadrat	kvadrats	N;GEN;INDF;SG
tjugondel	tjugondelarnas	N;GEN;DEF;PL
skolbildning	skolbildningarna	N;NOM;DEF;PL
överantvarda	överantvarda	V;NFIN;ACT
mobiltelefon	mobiltelefonens	N;GEN;DEF;SG
hamstring	hamstring	N;NOM;INDF;SG
inmatningsfält	inmatningsfälts	N;GEN;INDF;PL
underordna	underordnad	V.PTCP;PST
motett	motetters	N;GEN;INDF;PL
turban	turbans	N;GEN;INDF;SG
missförhållande	missförhållandens	N;GEN;INDF;PL
döva	dövade	V;IND;PST;ACT
bordslampa	bordslampornas	N;GEN;DEF;PL
skämtare	skämtarnas	N;GEN;DEF;PL
kritisera	kritiserar	V;IND;PRS;ACT
dass	dass	N;NOM;INDF;SG
tonsill	tonsiller	N;NOM;INDF;PL
kudde	kuddes	N;GEN;INDF;SG
hölja	höljts	V.CVB;PASS
diss	dissarnas	N;GEN;DEF;PL
stare	stare	N;NOM;INDF;SG
diskriminera	diskriminerad	V.PTCP;PST
trombocyt	trombocytens	N;GEN;DEF;SG
dödlig	dödligaste	ADJ;SPRL;DEF;MASC;SG
insatsstyrka	insatsstyrkan	N;NOM;DEF;SG
exkludera	exkluderas	V;NFIN;PASS
konkurrera	konkurrerat	V.CVB;ACT
nåldyna	nåldynor	N;NOM;INDF;PL
försäga	försäga	V;NFIN;ACT
dadel	dadlarna	N;NOM;DEF;PL
högskolestyrelse	högskolestyrelsen	N;NOM;DEF;SG
viska	viskades	V;IND;PST;PASS
vrida	vrida	V;NFIN;ACT
ringfinger	ringfingers	N;GEN;INDF;SG
rådande	rådande	ADJ;INDF;NEUT;SG
datakällvy	datakällvy	N;NOM;INDF;SG
ackurat	ackurat	ADJ;INDF;MASC+FEM;SG
tibetan	tibetaner	N;NOM;INDF;PL
kommentera	kommenterats	V.CVB;PASS
epifyt	epifyten	N;NOM;DEF;SG
extremism	extremismens	N;GEN;DEF;SG
diagnos	diagnosen	N;NOM;DEF;SG
adlig	adligt	ADJ;INDF;NEUT;SG
leverera	levereras	V;NFIN;PASS
fackla	fackla	N;NOM;INDF;SG
rättshaverist	rättshaveristers	N;GEN;INDF;PL
stampa	stampande	V.PTCP;PRS
vattenmelon	vattenmelonens	N;GEN;DEF;SG
curlingförälder	curlingföräldern	N;NOM;DEF;SG
ämnessakkunnig	ämnessakkunnig	N;NOM;INDF;SG
hasp	hasparnas	N;GEN;DEF;PL
statsminister	statsministrar	N;NOM;INDF;PL
anklagad	anklagad	ADJ;INDF;MASC+FEM;SG
snöre	snöre	N;NOM;INDF;SG
pilspets	pilspetsens	N;GEN;DEF;SG
förstärkare	förstärkarna	N;NOM;DEF;PL
webbsajt	webbsajt	N;NOM;INDF;SG
snabbmeny	snabbmenyernas	N;GEN;DEF;PL
häva	hävd	V.PTCP;PST
negrinna	negrinnors	N;GEN;INDF;PL
kejsardöme	kejsardömens	N;GEN;INDF;PL
trubbig	trubbige	ADJ;DEF;MASC;SG
bojkottad	bojkottad	ADJ;INDF;MASC+FEM;SG
meningsmotståndare	meningsmotståndare	N;NOM;INDF;PL
åtfärd	åtfärdens	N;GEN;DEF;SG
inflyta	influten	V.PTCP;PST
reol	reols	N;GEN;INDF;SG
qvadratisk	qvadratisk	ADJ;INDF;MASC+FEM;SG
killa	killar	V;IND;PRS;ACT
bordsalt	bordsaltets	N;GEN;DEF;SG
spinnrock	spinnrock	N;NOM;INDF;SG
porträttera	porträttera	V;NFIN;ACT
gummi	gummits	N;GEN;DEF;SG
rökruta	rökrutor	N;NOM;INDF;PL
natriumbenzoat	natriumbenzoat	N;NOM;INDF;SG
skruvdragare	skruvdragare	N;NOM;INDF;PL
järnvägsspår	järnvägsspårets	N;GEN;DEF;SG
vidskepelse	vidskepelsernas	N;GEN;DEF;PL
konfigurera	konfigurerade	V;IND;PST;ACT
atombomb	atombomben	N;NOM;DEF;SG
statuslist	statuslister	N;NOM;INDF;PL
rörande	rörande	ADJ;INDF;MASC+FEM;SG
bakväg	bakvägens	N;GEN;DEF;SG
premie	premier	N;NOM;INDF;PL
borrad	borrat	ADJ;INDF;NEUT;SG
pekare	pekare	N;NOM;INDF;SG
stop	stopen	N;NOM;DEF;PL
arrogans	arrogansens	N;GEN;DEF;SG
citrongräs	citrongräs	N;GEN;INDF;PL
arsle	arslena	N;NOM;DEF;PL
mö	mö	N;NOM;INDF;SG
opinionsbildare	opinionsbildares	N;GEN;INDF;SG
hundskatt	hundskatts	N;GEN;INDF;SG
halva	halvor	N;NOM;INDF;PL
läkemedelsförmån	läkemedelsförmåners	N;GEN;INDF;PL
eskalera	eskaleras	V;IND;PRS;PASS
förarbete	förarbetena	N;NOM;DEF;PL
försvarsstyrka	försvarsstyrkor	N;NOM;INDF;PL
tona	tonade	V;IND;PST;ACT
samlingsdokument	samlingsdokumentens	N;GEN;DEF;PL
ateism	ateism	N;NOM;INDF;SG
presenning	presenningens	N;GEN;DEF;SG
kvartsfinalist	kvartsfinalists	N;GEN;INDF;SG
meteorolog	meteorologers	N;GEN;INDF;PL
slangord	slangord	N;NOM;INDF;PL
ytterlig	ytterligt	ADJ;INDF;NEUT;SG
exemplifierad	exemplifierat	ADJ;INDF;NEUT;SG
calypso	calypsornas	N;GEN;DEF;PL
påverka	påverka	V;IMP
kraftmaskin	kraftmaskin	N;NOM;INDF;SG
eskalera	eskalerande	V.PTCP;PRS
kortlek	kortlekens	N;GEN;DEF;SG
ikosaeder	ikosaedrar	N;NOM;INDF;PL
koksalt	koksalt	N;NOM;INDF;SG
landstingsdirektör	landstingsdirektörerna	N;NOM;DEF;PL
valpa	valpande	V.PTCP;PRS
kalabalik	kalabalikens	N;GEN;DEF;SG
övningsbil	övningsbilen	N;NOM;DEF;SG
tröttna	tröttnade	V;IND;PST;ACT
sociologisk	sociologiska	ADJ;DEF
järnvägsförvaltning	järnvägsförvaltningens	N;GEN;DEF;SG
mineral	mineralet	N;NOM;DEF;SG
fakultetsnämnd	fakultetsnämndernas	N;GEN;DEF;PL
beduin	beduin	N;NOM;INDF;SG
nicka	nickas	V;NFIN;PASS
kopplad	kopplade	ADJ;DEF
attackerad	attackerade	ADJ;DEF;MASC;SG
objektlist	objektlisters	N;GEN;INDF;PL
vanka	vankas	V;IND;PRS;PASS
modersmål	modersmål	N;NOM;INDF;PL
snatta	snatta	V;NFIN;ACT
falsk	falskare	ADJ;COMPV;INDF;NEUT;SG
vålla	vållar	V;IND;PRS;ACT
förebygga	förebyggts	V.CVB;PASS
efterfrågan	efterfrågans	N;GEN;DEF;SG
getost	getostarna	N;NOM;DEF;PL
folksaga	folksagas	N;GEN;INDF;SG
yr	yrast	ADJ;SPRL;INDF;NEUT;SG
läroanstalt	läroanstaltens	N;GEN;DEF;SG
pilt	pilten	N;NOM;DEF;SG
sötsak	sötsak	N;NOM;INDF;SG
planering	planeringen	N;NOM;DEF;SG
omnämnd	omnämnde	ADJ;DEF;MASC;SG
befinna	befinn	V;IMP
tråddragare	tråddragarna	N;NOM;DEF;PL
hovrättsråd	hovrättsråden	N;NOM;DEF;PL
struts	strutsars	N;GEN;INDF;PL
direkt	direktare	ADJ;COMPV;INDF;NEUT;SG
multiplikation	multiplikationen	N;NOM;DEF;SG
lösning	lösningen	N;NOM;DEF;SG
återuppbygga	återuppbyggts	V.CVB;PASS
logiker	logikern	N;NOM;DEF;SG
våglängd	våglängdens	N;GEN;DEF;SG
expandera	expanderas	V;NFIN;PASS
dräpa	dräpas	V;NFIN;PASS
avrättad	avrättad	ADJ;INDF;MASC+FEM;SG
bepröva	beprövat	V.CVB;ACT
krokna	kroknande	V.PTCP;PRS
rötmånadshistoria	rötmånadshistoria	N;NOM;INDF;SG
tacknämlig	tacknämlige	ADJ;DEF;MASC;SG
kroatiska	kroatiskors	N;GEN;INDF;PL
leucin	leucinets	N;GEN;DEF;SG
inspirera	inspireras	V;IND;PRS;PASS
förankra	förankrats	V.CVB;PASS
lugna	lugna	V;NFIN;ACT
skitig	skitige	ADJ;DEF;MASC;SG
nådegåva	nådegåvors	N;GEN;INDF;PL
identifiera	identifieras	V;IND;PRS;PASS
körtelfeber	körtelfeber	N;NOM;INDF;SG
ångpanna	ångpannornas	N;GEN;DEF;PL
penetrera	penetrerade	V;IND;PST;ACT
bang	bangens	N;GEN;DEF;SG
kulturråd	kulturrådet	N;NOM;DEF;SG
exponera	exponerande	V.PTCP;PRS
tatuerare	tatuerares	N;GEN;INDF;SG
automat	automaterna	N;NOM;DEF;PL
samfund	samfundet	N;NOM;DEF;SG
kolon	kolon	N;NOM;INDF;PL
äggviteämne	äggviteämnet	N;NOM;DEF;SG
specialisera	specialiseras	V;NFIN;PASS
flitig	flitigast	ADJ;SPRL;INDF;PL
sonson	sonsons	N;GEN;INDF;SG
bakluckeloppis	bakluckeloppis	N;GEN;INDF;SG
publikation	publikationens	N;GEN;DEF;SG
grävskopa	grävskopans	N;GEN;DEF;SG
överföra	överförde	V;IND;PST;ACT
serin	serin	N;NOM;INDF;SG
förhandsgranskning	förhandsgranskningars	N;GEN;INDF;PL
potentiell	potentiell	ADJ;INDF;MASC+FEM;SG
slagverkare	slagverkarna	N;NOM;DEF;PL
dodekaeder	dodekaeder	N;NOM;INDF;SG
trycka	tryckt	V.CVB;ACT
bestämmelse	bestämmelses	N;GEN;INDF;SG
dramatisk	dramatisk	ADJ;INDF;MASC+FEM;SG
diagram	diagrams	N;GEN;INDF;SG
kulturverksamhet	kulturverksamhets	N;GEN;INDF;SG
rättsskola	rättsskola	N;NOM;INDF;SG
anvisad	anvisade	ADJ;INDF;PL
binaritet	binariteterna	N;NOM;DEF;PL
mast	masts	N;GEN;INDF;SG
chebeck	chebecken	N;NOM;DEF;SG
agnosticism	agnosticism	N;NOM;INDF;SG
intressera	intresserats	V.CVB;PASS
socialförsäkringsutskott	socialförsäkringsutskotts	N;GEN;INDF;SG
mager	magert	ADJ;INDF;NEUT;SG
deriverad	deriverade	ADJ;DEF;MASC;SG
sekundvisare	sekundvisares	N;GEN;INDF;SG
borrad	borrade	ADJ;DEF;MASC;SG
yacht	yachts	N;GEN;INDF;SG
vishet	visheters	N;GEN;INDF;PL
minimum	minimums	N;GEN;INDF;PL
magnet	magneters	N;GEN;INDF;PL
tordön	tordönarna	N;NOM;DEF;PL
stapel	staplar	N;NOM;INDF;PL
ägd	ägd	ADJ;INDF;MASC+FEM;SG
morsa	morsorna	N;NOM;DEF;PL
äten	äten	ADJ;INDF;MASC+FEM;SG
tangentkombination	tangentkombinations	N;GEN;INDF;SG
nav	navens	N;GEN;DEF;PL
rigga	riggats	V.CVB;PASS
föranleda	föranledas	V;NFIN;PASS
kompromettera	komprometterande	V.PTCP;PRS
ficklampa	ficklampa	N;NOM;INDF;SG
tilltalsnamn	tilltalsnamns	N;GEN;INDF;PL
cotangent	cotangent	N;NOM;INDF;SG
tröskel	tröskels	N;GEN;INDF;SG
placering	placeringen	N;NOM;DEF;SG
kraftverk	kraftverks	N;GEN;INDF;SG
omfattning	omfattningens	N;GEN;DEF;SG
detekterad	detekterade	ADJ;DEF
trygg	tryggt	ADJ;INDF;NEUT;SG
byrådirektör	byrådirektörens	N;GEN;DEF;SG
legering	legerings	N;GEN;INDF;SG
måltavla	måltavlan	N;NOM;DEF;SG
hanblomma	hanblommornas	N;GEN;DEF;PL
kraftig	kraftigast	ADJ;SPRL;INDF;NEUT;SG
faktura	fakturornas	N;GEN;DEF;PL
oboe	oboens	N;GEN;DEF;SG
underskrift	underskriften	N;NOM;DEF;SG
århundrade	århundradet	N;NOM;DEF;SG
kondensera	kondenseras	V;IND;PRS;PASS
reell	reella	ADJ;DEF
fana	fanan	N;NOM;DEF;SG
motivering	motiveringarnas	N;GEN;DEF;PL
sedvänja	sedvänjorna	N;NOM;DEF;PL
knopp	knoppen	N;NOM;DEF;SG
polisbyrå	polisbyråerna	N;NOM;DEF;PL
förgäta	förgätits	V.CVB;PASS
kommissionär	kommissionär	N;NOM;INDF;SG
locka	lockas	V;NFIN;PASS
synagoga	synagoga	N;NOM;INDF;SG
öm	ömma	ADJ;INDF;PL
kika	kikade	V;IND;PST;ACT
diskutera	diskuterades	V;IND;PST;PASS
läroverk	läroverket	N;NOM;DEF;SG
flöjtist	flöjtistens	N;GEN;DEF;SG
dold	dolde	ADJ;DEF;MASC;SG
beaktad	beaktade	ADJ;INDF;PL
fyra av	fyrats av	V.CVB;PASS
elektrifiera	elektrifierande	V.PTCP;PRS
germanska	germanska	N;NOM;INDF;SG
utbildningsutskott	utbildningsutskotten	N;NOM;DEF;PL
övertala	övertalande	V.PTCP;PRS
hopa	hopats	V.CVB;PASS
tandvärk	tandvärken	N;NOM;DEF;SG
klassisk	klassiskt	ADJ;INDF;NEUT;SG
papegoja	papegojans	N;GEN;DEF;SG
färöiska	färöiskans	N;GEN;DEF;SG
uv	uvs	N;GEN;INDF;SG
plöja	plöjts	V.CVB;PASS
affärsman	affärsman	N;NOM;INDF;SG
hantering	hanteringens	N;GEN;DEF;SG
crescendo	crescendots	N;GEN;DEF;SG
älskad	älskade	ADJ;DEF;MASC;SG
bokstöd	bokstöd	N;NOM;INDF;SG
svår	svårare	ADJ;COMPV;DEF
mack	macken	N;NOM;DEF;SG
recitera	reciteras	V;IND;PRS;PASS
