hihttát	hihttájetne	V;IND;DU;1;PRS
nearrat	nearaža	V;POT;SG;3
vuoiŋŋadit	vuoiŋŋat	V;IMP;SG;2
lutkoseamos	lutkosepmosiiguin	ADJ;COM;PL
doaivvuhit	doaivvuheahkki	V;IMP;DU;2
haŋkit	haŋkkii	V;IND;SG;3;PST
skihččát	skihččába	V;IND;DU;3;PRS
nahkehit	nahkehežžet	V;POT;PL;3
áidut	áidduidet	V;IND;PL;2;PST
ráhkisvuohta	ráhkisvuođaid	N;GEN;PL
ohcat	oza	V;IMP;SG;2
jakŋat	jaŋažat	V;POT;SG;2
geaidit	geaidibeahtti	V;IND;DU;2;PRS
sámástit	sámástit	V;IND;SG;2;PST
searvat	searvvale	V;COND;PL;3;LGSPEC1
automatiseret	automatiserejetnot	V;IMP;PL;1
čállit	čáliidet	V;IND;PL;2;PST
fierrut	firroska	V;IMP;DU;3
áitit	áittán	V;IND;SG;1;PRS
boatkanit	boatkanehkon	V;IMP;SG;1
bealli	beliin	N;PRP;PL
ruvke	ruvken	N;FRML;SG
moskát	moskábehtet	V;IND;PL;2;PRS
suorganit	suorgana	V;IND;SG;3;PRS
čiehppat	čiehppabehtet	V;IND;PL;2;PRS
čuođđit	čuođášeiddet	V;COND;PL;2
njohcut	njozoleigga	V;COND;DU;3;LGSPEC1
divvut	divvo	V;IND;PL;3;PST
šnjivvat	šnjiva	V;IMP;SG;2
bealkit	belket	V;IND;SG;2;PST
skilkit	skilkkii	V;IND;SG;3;PST
navdit	navdit	V;IND;PL;1;PRS
buohcat	buozalit	V;COND;SG;2;LGSPEC1
ruoššastit	ruoššasteahppi	V;IND;DU;2;PRS
čuoggut	čuokkut	V;IND;SG;2;PRS
vuosehit	vuosehivččen	V;COND;SG;1
jalkát	jalkát	V;IND;SG;2;PRS
hihttát	hihttážit	V;POT;PL;1
homofiila	homofiillat	N;NOM;PL
jorbaseamos	jorbasepmosis	ADJ;PRP;SG
guohkkat	guohkašeiddet	V;COND;PL;2
fitnat	fitnabehtet	V;IND;PL;2;PRS
reakci	reavccit	N;NOM;PL
gáma	gápmagiin	N;COM;SG
suhttat	suhta	V;IMP;SG;2
gahppat	gahpat	V;IND;SG;2;PRS
vástidit	vástide	V;IND;PL;3;PST
golgadit	golgadeidde	V;IND;DU;2;PST
nominatiiva	nominatiivvain	N;COM;SG
háŋgut	háŋggošeimme	V;COND;DU;1
nállat	nálažeaba	V;POT;DU;3
jallamus	jallamus	ADJ;NOM;SG
biologalaš	biologalažžan	ADJ;FRML;SG
láktat	láktet	V;IMP;PL;2
bruvsa	bruvssaid	N;GEN;PL
eahki	egiin	N;COM;SG
seailut	seilloleidde	V;COND;DU;2;LGSPEC1
šnjoargut	šnjorggošeiddet	V;COND;PL;2
nearrat	nearašeimme	V;COND;DU;1
jorrat	jorašit	V;COND;SG;2
máhccut	máhccot	V;IND;SG;2;PST
muohttit	muohtášin	V;COND;SG;1
mihtidit	mihtidehkoska	V;IMP;DU;3
buddet	buddele	V;COND;PL;3;LGSPEC1
bleahkka	bleahkka	N;NOM;SG
máidnut	máinnožetne	V;POT;DU;1
rážžat	rážžos	V;IMP;SG;3
buddet	buddežeahppi	V;POT;DU;2
cahpat	cabaleimmet	V;COND;PL;1;LGSPEC1
árga	árgga	N;GEN;SG
autoriseret	autoriserežan	V;POT;SG;1
jiehtanas	jiehtanassan	N;FRML;SG
adopšuvdna	adopšuvnna	N;ACC;SG
gođđat	gođašeigga	V;COND;DU;3
lieđđi	liđiin	N;PRP;PL
arvit	arvváše	V;COND;PL;3
duoršu	duorššu	N;ACC;SG
njohcut	njozožan	V;POT;SG;1
adnostit	adnosteažžat	V;POT;PL;1
govlut	govllošeiddet	V;COND;PL;2
jalgadeamos	jalgadepmosa	ADJ;ACC;SG
gávppašanlistu	gávppašanlisttu	N;GEN;SG
liŋka	liŋkkaide	N;IN+ALL;PL
jalkát	jalkájehket	V;IMP;PL;2
ropmi	romiid	ADJ;ACC;PL
ivdnet	ivdnežat	V;POT;SG;2
boktit	bovttášeigga	V;COND;DU;3
adopteret	adopterežat	V;POT;SG;2
buoidivuohta	buoidivuođat	N;NOM;PL
heavdni	hevnniin	N;COM;SG
čávvat	čáv'vu	V;IMP;DU;1
čállit	čállibeahtti	V;IND;DU;2;PRS
vuolgit	vulggežat	V;POT;SG;2
navvit	naváše	V;COND;PL;3
állát	ál'lá	V;IMP;SG;2
buoidut	buiddolin	V;COND;SG;1;LGSPEC1
čállit	čáláleimme	V;COND;DU;1;LGSPEC1
gávri	gávrriid	N;ACC;PL
šaddat	šattažeahppi	V;POT;DU;2
lieđđi	lieđđi	N;NOM;SG
vajáldahttit	vajáldahttet	V;IND;SG;2;PST
ihtit	iđežetne	V;POT;DU;1
jalkát	jalkájedje	V;IND;PL;3;PST
eahki	egiin	N;PRP;PL
mulgut	mulggoža	V;POT;SG;3
čora	čorragiin	N;COM;SG
čiekčat	čikčet	V;IND;SG;2;PST
suhttat	suhttet	V;IND;SG;2;PST
njáhkat	njágaidet	V;IND;PL;2;PST
arestet	arestii	V;IND;SG;3;PST
ceaggát	ceaggájit	V;IND;SG;2;PST
doarjut	dorjjolin	V;COND;SG;1;LGSPEC1
sealgi	sealgin	N;FRML;SG
helvet	helvehis	N;PRP;SG
ruoššastit	ruoššastežže	V;POT;DU;1
veaddit	veddot	V;IMP;PL;1
mulgut	mulgoska	V;IMP;DU;3
muhttit	muhttoska	V;IMP;DU;3
giitit	giiten	V;IND;SG;1;PST
idjaklubba	idjaklubba	N;NOM;SG
čeargulit	čeargulehkon	V;IMP;SG;1
gopmat	goman	V;IND;SG;1;PRS
albmaduvvat	albmaduvaleidde	V;COND;DU;2;LGSPEC1
iđit	iđidin	N;FRML;SG
biebmat	biepmašeidde	V;COND;DU;2
gonagasnieida	gonagasnieidda	N;ACC;SG
jahtat	jađažit	V;POT;PL;3
nominatiiva	nominatiivvaid	N;GEN;PL
lutkosit	lutkoseappuin	ADJ;COM;SG
alvvahuvvat	alvvahuvvet	V;IND;SG;2;PST
šaddu	šattu	N;ACC;SG
hahppit	hahpežetne	V;POT;DU;1
buđet	buđehiin	N;PRP;PL
gákti	gávttiide	N;IN+ALL;PL
gáskit	gáskkášeimme	V;COND;DU;1
gággat	gákkaimet	V;IND;PL;1;PST
állát	ál'lálit	V;COND;SG;2;LGSPEC1
oaksi	ovssiid	N;ACC;PL
juhkat	jugašit	V;COND;SG;2
luokčat	luovččaleidde	V;COND;DU;2;LGSPEC1
nallat	nalažat	V;POT;SG;2
bárgidit	bárgidii	V;IND;SG;3;PST
luohttit	luhtiide	V;IND;DU;2;PST
njávkat	njávkkaide	V;IND;DU;2;PST
goarrut	goroše	V;COND;PL;3
snuskit	snuskkežit	V;POT;PL;1
čearguladdat	čeargulattaše	V;COND;PL;3
autoriseret	autorisereše	V;COND;PL;3
čábbámus	čábbámussii	ADJ;IN+ALL;SG
máhccut	máhcui	V;IND;SG;3;PST
gaŋkát	gaŋkáimet	V;IND;PL;1;PST
ajihuvvat	ajihuvažetne	V;POT;DU;1
gaŋkát	gaŋkálin	V;COND;SG;1;LGSPEC1
šuvvat	šuva	V;IMP;SG;2
darjjesámegiella	darjjesámegielain	N;COM;SG
suopma	suomaide	N;IN+ALL;PL
čollut	čollo	V;IND;DU;1;PRS
vuohppát	vuohppáleiddet	V;COND;PL;2;LGSPEC1
vuokta	vuovttaiguin	N;COM;PL
ajihuvvat	ajihuvažan	V;POT;SG;1
avvit	avežeahppi	V;POT;DU;2
bilbut	bilbu	V;IMP;DU;1
moardit	moardi	V;IMP;DU;2
villat	villašeidde	V;COND;DU;2
geaidit	geaiddáleimmet	V;COND;PL;1;LGSPEC1
buddet	buddet	V;IND;PL;1;PRS
toardna	toartnaiguin	N;COM;PL
ambassáda	ambassáda	N;GEN;SG
vahcut	vazuimet	V;IND;PL;1;PST
láitit	láitos	V;IMP;SG;3
rievdat	rievddaimet	V;IND;PL;1;PST
šlahttit	šlahtiimet	V;IND;PL;1;PST
huilát	huilájehkoska	V;IMP;DU;3
ajihustit	ajihusttiime	V;IND;DU;1;PST
máinnastit	máinnastivččen	V;COND;SG;1
deapmat	deamašin	V;COND;SG;1
boagustit	boagustetne	V;IND;DU;1;PRS
gálbi	gálbbiin	N;COM;SG
struhpat	strubale	V;COND;PL;3;LGSPEC1
mannat	manne	V;IND;DU;1;PRS
luoddut	luddos	V;IMP;SG;3
jalŋŋis	jalgŋáin	N;PRP;PL
agáiduvvat	agáiduvvon	V;IMP;SG;1
spáitit	spáitibehtet	V;IND;PL;2;PRS
lapmat	lapmet	V;IND;PL;3;PRS
vuotna	vuonas	N;PRP;SG
ballát	bal'lát	V;IND;SG;2;PRS
skeaikit	skeikkežeaba	V;POT;DU;3
justit	justtášii	V;COND;SG;3
roahttu	roahtuid	N;GEN;PL
boktit	bovttáleiddet	V;COND;PL;2;LGSPEC1
divrras	divrasa	ADJ;GEN;SG
jorrat	joraide	V;IND;DU;2;PST
johttát	johttážeahppi	V;POT;DU;2
albmaduvvat	albmaduvašeigga	V;COND;DU;3
lohkat	logaleigga	V;COND;DU;3;LGSPEC1
almmolašvuohta	almmolašvuođain	N;PRP;PL
oaggut	okkošeiddet	V;COND;PL;2
bassit	basáleimme	V;COND;DU;1;LGSPEC1
háhtta	háhtta	N;NOM;SG
gáhččat	gáhčaža	V;POT;SG;3
nuortalaš	nuortalaččaid	N;ACC;PL
lutnjat	lunjaleigga	V;COND;DU;3;LGSPEC1
duohččat	duohčažeahppi	V;POT;DU;2
vuolli	vuliid	N;ACC;PL
mánnat	mánalin	V;COND;SG;1;LGSPEC1
vátnat	vánaleimmet	V;COND;PL;1;LGSPEC1
njohcut	njozošeiddet	V;COND;PL;2
sárgi	sárggi	N;GEN;SG
čitnut	činošii	V;COND;SG;3
reavvat	revvet	V;IND;PL;3;PRS
iđit	iđida	N;ACC;SG
gávrut	gávrroža	V;POT;SG;3
máidnut	máidnu	V;IMP;DU;1
ollit	ole	V;IMP;SG;2
ruovgat	ruovggašit	V;COND;SG;2
čealluladdat	čealluladdot	V;IMP;PL;1
njoahci	njoahci	ADJ;NOM;SG
borgat	borggaimet	V;IND;PL;1;PST
máidnut	máinnožehpet	V;POT;PL;2
ohcat	ohccu	V;IMP;DU;1
suossat	suosažehpet	V;POT;PL;2
biehkan	biehkaniin	N;PRP;PL
gávrát	gávrážeahppi	V;POT;DU;2
divvut	divoleidde	V;COND;DU;2;LGSPEC1
vuođgŋit	vuđŋŋeža	V;POT;SG;3
jurdit	jurdet	V;IND;PL;3;PRS
biebmat	biepmalii	V;COND;SG;3;LGSPEC1
meaštár	meaštárat	N;NOM;PL
cohkkát	cohkkái	V;IND;SG;3;PST
guoktelogát	guoktelogádin	ADJ;FRML;SG
nealgi	nealgin	N;FRML;SG
almmolašvuohta	almmolašvuhtii	N;IN+ALL;SG
átnut	ánoleigga	V;COND;DU;3;LGSPEC1
bivvat	bivaža	V;POT;SG;3
coggat	cogge	V;IND;PL;3;PST
sáhttit	sáhtáleiddet	V;COND;PL;2;LGSPEC1
sámástit	sámásteažžabeahtti	V;POT;DU;2
alvvahuvvat	alvvahuvaidet	V;IND;PL;2;PST
nahkehit	nahkeheadnu	V;IMP;DU;1
gáisi	gáissiide	N;IN+ALL;PL
almmaiduvvat	almmaiduvvoska	V;IMP;DU;3
gierdat	gierddažan	V;POT;SG;1
vuokta	vuovttas	N;PRP;SG
čábbáseamos	čábbáseamos	ADJ;NOM;SG
ledjon	ledjona	N;GEN;SG
nallat	nalašeimme	V;COND;DU;1
rihccut	rihccubeahtti	V;IND;DU;2;PRS
deapmat	deamaleidde	V;COND;DU;2;LGSPEC1
áitit	áittežit	V;POT;PL;1
čearguladdat	čeargulattaime	V;IND;DU;1;PST
rássi	rásit	N;NOM;PL
vuolgit	vulgot	V;IMP;PL;1
hárdu	hárdduid	N;ACC;PL
bieggat	bigget	V;IMP;PL;2
soaitit	soiton	V;IMP;SG;1
čiktit	čivttiime	V;IND;DU;1;PST
garvit	garven	V;IND;SG;1;PST
gollat	gollen	V;IND;SG;1;PST
astan	astamin	N;FRML;SG
goarjut	gorjoset	V;IMP;PL;3
beahkit	behken	V;IND;SG;1;PST
nallat	nalašeigga	V;COND;DU;3
áhtat	áđalit	V;COND;SG;2;LGSPEC1
jahtat	jađalii	V;COND;SG;3;LGSPEC1
háhccát	háhccájehkos	V;IMP;SG;3
šuvvat	šuvvet	V;IMP;PL;2
mahkkit	mahkežetne	V;POT;DU;1
suollit	suolášeiddet	V;COND;PL;2
sarcut	sarccošit	V;COND;SG;2
ekologa	ekologa	N;ACC;SG
ruššat	rušaleigga	V;COND;DU;3;LGSPEC1
máidnut	máinnožat	V;POT;SG;2
doadjit	doježat	V;POT;SG;2
artihkal	artihkkala	N;GEN;SG
gávrát	gávrájit	V;IND;SG;2;PST
jorrat	jorale	V;COND;PL;3;LGSPEC1
almmenáhkki	almmenáhki	N;GEN;SG
njuoršu	njuoršun	N;FRML;SG
bearrat	bearaža	V;POT;SG;3
jávkat	jávkos	V;IMP;SG;3
oidit	oiddálit	V;COND;SG;2;LGSPEC1
jearrat	jearašit	V;COND;SG;2
bieggat	biekkažit	V;POT;PL;1
ruohttat	ruohtašeiddet	V;COND;PL;2
duoggut	dukkošeimme	V;COND;DU;1
snuskit	snuskot	V;IMP;PL;1
ballát	bal'lájit	V;IND;PL;3;PRS
geahččalit	geahččaleažžabeahtti	V;POT;DU;2
eahccit	ehccoteahccut	V;IMP;PL;1
buhttásit	buhttáseabbon	ADJ;FRML;SG
aiget	aigejehkon	V;IMP;SG;1
basahat	basahagat	N;NOM;PL
jietna	jienaide	N;IN+ALL;PL
adveanta	adveanta	N;NOM;SG
sildnit	silnnežetne	V;POT;DU;1
divvut	divožat	V;POT;SG;2
sáhttit	sáhtášii	V;COND;SG;3
lállit	láležit	V;POT;PL;3
čavggat	čavggat	ADJ;NOM;SG
justit	justoset	V;IMP;PL;3
ruovgat	ruovggan	V;IND;SG;1;PRS
jurdit	jurddášeidde	V;COND;DU;2
goahti	goađis	N;PRP;SG
huikit	huikkežat	V;POT;SG;2
antologiija	antologiijain	N;PRP;PL
geallit	geliide	V;IND;DU;2;PST
oaggut	okkošeigga	V;COND;DU;3
goldnat	golnnalii	V;COND;SG;3;LGSPEC1
ája	ádjaga	N;GEN;SG
hahppit	hahpát	V;IND;SG;2;PRS
njoahcut	njoazo	V;IMP;SG;2
albmaduvvat	albmaduvažeahppi	V;POT;DU;2
sámástit	sámás	V;IMP;SG;2
boles	bolesiid	N;GEN;PL
dolastaddat	dolastattalin	V;COND;SG;1;LGSPEC1
bláđet	bláđejetnot	V;IMP;PL;1
gártat	gárttašeidde	V;COND;DU;2
doaibmat	doaimmašin	V;COND;SG;1
adnot	adnožeaba	V;POT;DU;3
gálvát	gálvášit	V;COND;SG;2
gealdit	gealddáše	V;COND;PL;3
millu	milluiguin	N;COM;PL
čeargulit	čeargula	V;IND;SG;3;PRS
joksat	jovssažeaba	V;POT;DU;3
bardit	bardit	V;IND;PL;1;PRS
bahčit	bažiime	V;IND;DU;1;PST
jakŋat	jaŋažit	V;POT;PL;3
šuvvat	šuvaleigga	V;COND;DU;3;LGSPEC1
diŋgot	diŋguime	V;IND;DU;1;PST
savvit	sav'vu	V;IMP;DU;1
áhtat	áđašeiddet	V;COND;PL;2
vuossárga	vuossárgan	N;FRML;SG
figgat	fikkaiga	V;IND;DU;3;PST
doaivvuhit	doaivvuheigga	V;IND;DU;3;PST
oahppásit	oahppáseappo	ADJ;GEN;SG
almmáskit	almmáskin	V;IND;SG;1;PST
bárgut	bárggolit	V;COND;SG;2;LGSPEC1
stašuvdna	stašuvnnaid	N;GEN;PL
čulkit	čulkkášeidde	V;COND;DU;2
šearrát	šear'rážit	V;POT;PL;3
oađđit	oađálin	V;COND;SG;1;LGSPEC1
agáiduvvat	agáiduvve	V;IND;PL;3;PST
čuorgadeamos	čuorgadepmosa	ADJ;GEN;SG
beahkit	beagáleidde	V;COND;DU;2;LGSPEC1
brugga	brukkain	N;COM;SG
vuodjut	vujolin	V;COND;SG;1;LGSPEC1
nargit	narggežetne	V;POT;DU;1
almmaiduvvat	almmaiduvaidet	V;IND;PL;2;PST
arvát	arválit	V;COND;SG;2;LGSPEC1
giehta	gieđas	N;PRP;SG
čulkit	čulkon	V;IMP;SG;1
laggat	lakkašeidde	V;COND;DU;2
buohccát	buohccájetnot	V;IMP;PL;1
šiehttat	šihtte	V;IND;PL;3;PST
dierbut	dirbboleigga	V;COND;DU;3;LGSPEC1
giitit	giittiimet	V;IND;PL;1;PST
gopmat	gomaleigga	V;COND;DU;3;LGSPEC1
jorgut	jorgguide	V;IND;DU;2;PST
joahcat	joazaidet	V;IND;PL;2;PST
luddat	luttaime	V;IND;DU;1;PST
ihtit	iđáše	V;COND;PL;3
adnot	adno	V;IND;SG;3;PRS
luossa	luosat	N;NOM;PL
ráhkistuvvat	ráhkistuvažeaba	V;POT;DU;3
cahpat	cabažeahppi	V;POT;DU;2
lohpidit	lohpidit	V;IND;SG;2;PST
govahallat	govahalat	V;IND;SG;2;PRS
šohkut	šohkoska	V;IMP;DU;3
háhccát	háhccážetne	V;POT;DU;1
áitit	áitoset	V;IMP;PL;3
njiellat	njilloska	V;IMP;DU;3
skihččát	skihččážetne	V;POT;DU;1
njávkat	njávket	V;IND;PL;3;PRS
háŋgut	háŋggoše	V;COND;PL;3
doarrut	doarrubehtet	V;IND;PL;2;PRS
ráhččat	ráhčažit	V;POT;PL;3
snuskit	snuskkášii	V;COND;SG;3
atnit	análii	V;COND;SG;3;LGSPEC1
suoidni	suoinni	N;GEN;SG
vuoigŋa	vuoigŋan	N;FRML;SG
biebmat	biepmašeimmet	V;COND;PL;1
vuodjit	vuojáleimme	V;COND;DU;1;LGSPEC1
addálasamus	addálasamussii	ADJ;IN+ALL;SG
jeagil	jeahkáliin	N;PRP;PL
girji	girjjis	N;PRP;SG
hoallat	hoalašin	V;COND;SG;1
náššat	nášašeimmet	V;COND;PL;1
njálbmi	njálmmiid	N;ACC;PL
skolpát	skolpáža	V;POT;SG;3
keallir	keal'lára	N;ACC;SG
buddet	buddejetne	V;IND;DU;1;PRS
gealdit	gealddát	V;IND;SG;2;PRS
johtit	johton	V;IMP;SG;1
guoktelogigávccát	guoktelogigávccádiin	ADJ;COM;SG
savvit	savvibehtet	V;IND;PL;2;PRS
meaštár	meaštáriid	N;GEN;PL
doadjit	doježehpet	V;POT;PL;2
oaggut	okkožeahppi	V;POT;DU;2
duodji	duodjái	N;IN+ALL;SG
dievvat	divvoset	V;IMP;PL;3
vuordnut	vurdnot	V;IMP;PL;2
gártat	gárttaide	V;IND;DU;2;PST
arába	arábaiguin	N;COM;PL
balánsa	balánssat	N;NOM;PL
máhccut	máhcco	V;IND;PL;3;PST
asbeasta	asbestii	N;IN+ALL;SG
doaibma	doaibman	N;FRML;SG
jalgadeamos	jalgadepmosiin	ADJ;COM;SG
čearguladdat	čeargulattale	V;COND;PL;3;LGSPEC1
lutnjat	lunjale	V;COND;PL;3;LGSPEC1
luokčat	luovččat	V;IND;SG;2;PRS
čuovgatoardna	čuovgatoartnaid	N;ACC;PL
boaldit	boldos	V;IMP;SG;3
apmasit	apmaseappuid	ADJ;GEN;PL
gaska	gaskkain	N;PRP;PL
čuohcat	čuozaža	V;POT;SG;3
jahtat	jađaleimmet	V;COND;PL;1;LGSPEC1
villat	vil'le	V;IND;PL;3;PST
ádjánit	ádjáneadnu	V;IMP;DU;1
apoastal	apoastaliid	N;ACC;PL
njeađgat	njeađgabehtet	V;IND;PL;2;PRS
suhttat	suhtažit	V;POT;PL;1
gurrosit	gurroseabbon	ADJ;FRML;SG
diŋgot	diŋgoleigga	V;COND;DU;3;LGSPEC1
ledjon	ledjonii	N;IN+ALL;SG
gálvát	gálvájetne	V;IND;DU;1;PRS
ruonát	ruonábuiguin	ADJ;COM;PL
iđit	iđidat	N;NOM;PL
deapmat	deapmá	V;IND;SG;3;PRS
arvit	arvá	V;IND;SG;3;PRS
ivdnet	ivdneba	V;IND;DU;3;PRS
issorasat	issorasabuin	ADJ;PRP;PL
nearva	nearvvas	N;PRP;SG
buođđut	buđuiga	V;IND;DU;3;PST
ceaggát	ceaggát	V;IND;SG;2;PRS
labmát	labmášeiddet	V;COND;PL;2
hállat	hálašin	V;COND;SG;1
giehpa	gieba	N;ACC;SG
njassat	njasažan	V;POT;SG;1
homofiila	homofiilii	N;IN+ALL;SG
bassit	basset	V;IMP;PL;2
čelččen	čelččemiid	N;ACC;PL
searvat	searvvaleidde	V;COND;DU;2;LGSPEC1
apotehka	apotehkaide	N;IN+ALL;PL
gaivát	gaivájeahkki	V;IMP;DU;2
bibliotehka	bibliotehka	N;ACC;SG
čuoigát	čuoigáše	V;COND;PL;3
ráddut	ráttoža	V;POT;SG;3
vašálaččamus	vašálaččamusain	ADJ;PRP;PL
vázzit	váccáleimme	V;COND;DU;1;LGSPEC1
čorbma	čorpmaid	N;GEN;PL
villat	villalii	V;COND;SG;3;LGSPEC1
muhttit	muhttos	V;IMP;SG;3
vealgut	velggožan	V;POT;SG;1
áitit	áittiidet	V;IND;PL;2;PST
addjot	addjošeimmet	V;COND;PL;1
jabbut	jappuidet	V;IND;PL;2;PST
ateisma	ateismii	N;IN+ALL;SG
duođamus	duođamusas	ADJ;PRP;SG
doaibmat	doibmoset	V;IMP;PL;3
čuožžut	čužžos	V;IMP;SG;3
juoigat	juoiggalit	V;COND;SG;2;LGSPEC1
gáskit	gáskibehtet	V;IND;PL;2;PRS
stašuvdna	stašuvdnii	N;IN+ALL;SG
goardit	gorddežat	V;POT;SG;2
baikit	baikkeža	V;POT;SG;3
suhttat	suhtaleimme	V;COND;DU;1;LGSPEC1
fitnat	fitnaba	V;IND;DU;3;PRS
boles	bolesat	N;NOM;PL
luddat	luddat	V;IND;PL;1;PRS
biehkan	biehkanin	N;FRML;SG
suotna	suonaid	N;GEN;PL
suddat	suttažeahppi	V;POT;DU;2
gádjut	gájožeahppi	V;POT;DU;2
gohpat	gohpet	V;IND;PL;3;PRS
govlut	govlot	V;IND;SG;2;PST
luohttit	luohttibeahtti	V;IND;DU;2;PRS
čulkit	čulkiba	V;IND;DU;3;PRS
albmaduvvat	albmaduvalit	V;COND;SG;2;LGSPEC1
hieibmat	hieimmašeidde	V;COND;DU;2
esttegiella	esttegiella	N;NOM;SG
čiekčat	čievččažan	V;POT;SG;1
bivvát	biv'vát	V;IND;SG;2;PRS
heaibat	heaibbaide	V;IND;DU;2;PST
alimusriekti	alimusrivttiin	N;COM;SG
eahki	eahkái	N;IN+ALL;SG
jurdit	jurddeža	V;POT;SG;3
šnjivvat	šnjivažetne	V;POT;DU;1
ájáhallat	ájáhallon	V;IMP;SG;1
vealgut	velgguimet	V;IND;PL;1;PST
urdit	urddášii	V;COND;SG;3
máhccat	máhcašin	V;COND;SG;1
suhttat	suhtalit	V;COND;SG;2;LGSPEC1
snorrát	snor'rášeimme	V;COND;DU;1
struhpat	strubašeimme	V;COND;DU;1
iras	irasin	ADJ;FRML;SG
iras	irrasa	ADJ;GEN;SG
juovllat	juovllain	N;PRP;PL
doarggistit	doarggisteigga	V;IND;DU;3;PST
nearrat	nearašeiddet	V;COND;PL;2
ajihuvvat	ajihuvaidet	V;IND;PL;2;PST
rážžat	ráččažetne	V;POT;DU;1
vajáldahttit	vajáldahtiime	V;IND;DU;1;PST
guoktelogigávccát	guoktelogigávccádii	ADJ;IN+ALL;SG
lállit	lállos	V;IMP;SG;3
bivvat	bivaimet	V;IND;PL;1;PST
hoallat	hoalažehpet	V;POT;PL;2
čiktit	čivttášeigga	V;COND;DU;3
boaggut	bokkuimet	V;IND;PL;1;PST
iskat	isken	V;IND;SG;1;PST
sildnit	sildniba	V;IND;DU;3;PRS
šnjuoggát	šnjuoggájehkos	V;IMP;SG;3
doaivvuhit	doaivvuhehkoset	V;IMP;PL;3
guoika	guoikkaiguin	N;COM;PL
gaŋkát	gaŋkášeimme	V;COND;DU;1
šnjalčát	šnjalčášii	V;COND;SG;3
bursa	burssaid	N;GEN;PL
háistit	háisttáleimme	V;COND;DU;1;LGSPEC1
sealgi	selggiin	N;COM;SG
artihkal	artihkkalat	N;NOM;PL
čollut	čolut	V;IND;SG;2;PRS
deháleamos	dehálepmosii	ADJ;IN+ALL;SG
eahccit	eahcálit	V;COND;SG;2;LGSPEC1
máidnut	máinnošii	V;COND;SG;3
njávkat	njávkkašin	V;COND;SG;1
almmaiduvvat	almmaiduvvoset	V;IMP;PL;3
bibliografiija	bibliografiijaiguin	N;COM;PL
doallat	doalažit	V;POT;PL;1
njahppit	njahpiiga	V;IND;DU;3;PST
bárru	báruide	N;IN+ALL;PL
muhttit	muhttot	V;IMP;PL;1
irrasit	irraseappuin	ADJ;COM;SG
játnat	jánaža	V;POT;SG;3
almmaiduvvat	almmaiduvvabeahtti	V;IND;DU;2;PRS
boandut	bondo	V;IND;DU;1;PRS
doarjut	doarju	V;IMP;DU;1
šearradeamos	šearradepmosiidda	ADJ;IN+ALL;PL
sildnit	silnnáleimmet	V;COND;PL;1;LGSPEC1
bolfát	bolfáiga	V;IND;DU;3;PST
gálvát	gálváleiddet	V;COND;PL;2;LGSPEC1
geandit	gende	V;IND;PL;3;PST
fuobmát	fuobmášeimmet	V;COND;PL;1
doidit	doidibehtet	V;IND;PL;2;PRS
ollit	ollibehtet	V;IND;PL;2;PRS
jarfát	jarfájeahkki	V;IMP;DU;2
goardit	gorddiide	V;IND;DU;2;PST
arvit	arvváleigga	V;COND;DU;3;LGSPEC1
bindut	bindo	V;IND;PL;3;PST
čuollát	čuol'lá	V;IMP;SG;2
jalkát	jalkán	V;IND;SG;1;PRS
mihtidit	mihtidii	V;IND;SG;3;PST
varraliiki	varraliikkiid	N;GEN;PL
bárgut	bárggoleimmet	V;COND;PL;1;LGSPEC1
luoddut	luottut	V;IND;SG;2;PRS
láktat	lávttašit	V;COND;SG;2
barbára	barbáras	N;PRP;SG
mánnat	mánaleiddet	V;COND;PL;2;LGSPEC1
šealgadit	šealgadit	ADJ;NOM;SG
vuoiŋŋadit	vuoiŋŋadeaba	V;IND;DU;3;PRS
čávvat	čávvet	V;IMP;PL;2
gealdit	gelddežit	V;POT;PL;1
bárdni	bártniiguin	N;COM;PL
ruššat	rušaža	V;POT;SG;3
dálvat	dálvos	V;IMP;SG;3
čulkit	čulkkášeimme	V;COND;DU;1
stoahkat	stoagašeigga	V;COND;DU;3
čaibmat	čaimmažeaba	V;POT;DU;3
láibut	láibbuidet	V;IND;PL;2;PST
ovttasbargat	ovttasbarggažit	V;POT;PL;1
oarbbis	oarbásat	N;NOM;PL
goarjut	gorjjošeimmet	V;COND;PL;1
oađđit	oađát	V;IND;SG;2;PRS
loavdda	loavddan	N;FRML;SG
suoggat	suokkašit	V;COND;SG;2
vielgadit	vielgadebbui	ADJ;IN+ALL;SG
normálamus	normálamusaid	ADJ;ACC;PL
vuođgŋit	vuđgŋoset	V;IMP;PL;3
gierdat	girde	V;IND;DU;1;PRS
gállit	gállen	V;IND;SG;1;PST
muitit	muittášeimme	V;COND;DU;1
náššat	náššá	V;IND;SG;3;PRS
šleađgut	šleđgot	V;IND;PL;3;PRS
reakci	revcciin	N;PRP;PL
gárbbis	gárbát	N;NOM;PL
galbmit	galbmu	V;IMP;DU;1
duodji	dujiid	N;ACC;PL
čora	čorragiid	N;GEN;PL
duottar	duottarin	N;FRML;SG
ablatiiva	ablatiivvaid	N;GEN;PL
šnjoargut	šnjorggošin	V;COND;SG;1
gealdit	geldet	V;IND;SG;2;PST
cuovkanit	cuovkaneaččat	V;POT;SG;2
njávkat	njávká	V;IND;SG;3;PRS
skoahččát	skoahččážit	V;POT;PL;1
joahcat	joazažan	V;POT;SG;1
homofiila	homofiillaiguin	N;COM;PL
gággat	gággon	V;IMP;SG;1
nállat	nálaimet	V;IND;PL;1;PST
huikit	huiket	V;IMP;PL;2
mahkkit	mahkiime	V;IND;DU;1;PST
seailut	seilložat	V;POT;SG;2
boagustit	boagustivččiidet	V;COND;PL;2
ruohttat	ruohtašin	V;COND;SG;1
fuorrá	fuoráin	N;COM;SG
dieigut	diigon	V;IMP;SG;1
searvat	searvvaidet	V;IND;PL;2;PST
varraliiki	varraliiki	N;NOM;SG
dállu	dálu	N;ACC;SG
silba	silbbaide	N;IN+ALL;PL
bahát	bahábuid	ADJ;GEN;PL
buokčat	buovččažat	V;POT;SG;2
bláđet	bláđejehkoset	V;IMP;PL;3
náráš	nárážin	N;FRML;SG
ajihustit	ajihusttežeaba	V;POT;DU;3
njuolgut	njuolgubehtet	V;IND;PL;2;PRS
eadnáme	etniideame	N;ACC;PL
jaskadit	jaskadebbui	ADJ;IN+ALL;SG
bohkat	bogaše	V;COND;PL;3
skihččát	skihččále	V;COND;PL;3;LGSPEC1
urdit	urdu	V;IMP;DU;1
sáhttit	sáhttibehtet	V;IND;PL;2;PRS
govahallat	govahallabehtet	V;IND;PL;2;PRS
gohcut	gohcon	V;IND;SG;1;PST
lávlagat	lávlagisttát	N;PRP;SG
doarrut	dorros	V;IMP;SG;3
rážžat	ráččaleimmet	V;COND;PL;1;LGSPEC1
skoahččát	skoahččájehket	V;IMP;PL;2
davrát	davrábehtet	V;IND;PL;2;PRS
vealgut	velggoleimmet	V;COND;PL;1;LGSPEC1
huilát	huilášin	V;COND;SG;1
fierrut	firoleimmet	V;COND;PL;1;LGSPEC1
skavdut	skavddožehpet	V;POT;PL;2
sárdnut	sártnuimet	V;IND;PL;1;PST
čitnut	činošeigga	V;COND;DU;3
baldit	balddáleiddet	V;COND;PL;2;LGSPEC1
fierrut	fier'ru	V;IMP;DU;1
goarjut	goarjjun	V;IND;SG;1;PRS
čiekčat	čievččan	V;IND;SG;1;PRS
šuvvat	šuvaža	V;POT;SG;3
dárustit	dárustit	V;IND;PL;3;PRS
holbi	holbbiid	N;ACC;PL
vašálit	vašáleappo	ADJ;ACC;SG
buogu	buhkkuin	N;COM;SG
dálvat	dálvvat	V;IND;SG;2;PRS
astat	asttat	V;IND;SG;2;PRS
garvit	garvváleimme	V;COND;DU;1;LGSPEC1
skoavgit	skovge	V;IND;DU;1;PRS
skeaikit	skeikkežehpet	V;POT;PL;2
ruoššastit	ruoššastivččiide	V;COND;DU;2
nohkkat	nohkkoset	V;IMP;PL;3
ráhkis	ráhkkásiid	ADJ;GEN;PL
ihtit	iđášeidde	V;COND;DU;2
áhčči	áhči	N;ACC;SG
nahkehit	nahkehehkoska	V;IMP;DU;3
hupmat	humažit	V;POT;PL;1
bokset	boksii	V;IND;SG;3;PST
bolfát	bolfájehkos	V;IMP;SG;3
skeaikit	skeikkiide	V;IND;DU;2;PST
láibut	láibo	V;IND;DU;1;PRS
guoddit	guddoska	V;IMP;DU;3
cuoŋománnu	cuoŋománut	N;NOM;PL
sarcut	sarccut	V;IND;SG;2;PRS
čirrat	čiraide	V;IND;DU;2;PST
šnjalčát	šnjalčážetne	V;POT;DU;1
suollit	sulloset	V;IMP;PL;3
biila	biillaid	N;GEN;PL
bivvát	biv'vášeigga	V;COND;DU;3
cohkkát	cohkkáše	V;COND;PL;3
ođđasit	ođđaseappuin	ADJ;COM;SG
dolastit	dolastin	V;IND;SG;1;PST
haŋkit	haŋket	V;IND;PL;3;PRS
bohkat	bohken	V;IND;SG;1;PST
rinčát	rinčáime	V;IND;DU;1;PST
bohčit	bohčet	V;IMP;PL;2
hávdi	hávdi	N;NOM;SG
mođđat	mođalit	V;COND;SG;2;LGSPEC1
nargit	nargoska	V;IMP;DU;3
máidnut	máinnošit	V;COND;SG;2
adnostit	adnostivččen	V;COND;SG;1
gažaldat	gažaldagaid	N;ACC;PL
bardit	barden	V;IND;SG;1;PST
duvdit	duvddežit	V;POT;PL;1
vurket	vurkešeigga	V;COND;DU;3
gollat	golaide	V;IND;DU;2;PST
duoggut	dukkošit	V;COND;SG;2
urdit	urdot	V;IMP;PL;1
lapmat	lapmá	V;IND;SG;3;PRS
čolgat	čolggale	V;COND;PL;3;LGSPEC1
šnjuoggát	šnjuoggášeimmet	V;COND;PL;1
njiellat	njielašit	V;COND;SG;2
čitnut	čitnot	V;IND;PL;3;PRS
oahci	oazi	N;GEN;SG
doaivut	doivvuidet	V;IND;PL;2;PST
guohkkat	guhkket	V;IND;PL;3;PRS
gálvát	gálvájehkon	V;IMP;SG;1
suolu	suolu	N;NOM;SG
reavvat	reavašeimmet	V;COND;PL;1
suoggat	suggoset	V;IMP;PL;3
fierrut	firron	V;IMP;SG;1
gárta	gárttaid	N;ACC;PL
diŋgot	diŋgožeaba	V;POT;DU;3
bassit	basálii	V;COND;SG;3;LGSPEC1
jalkát	jalkábehtet	V;IND;PL;2;PRS
nahkehit	nahkeheažžaba	V;POT;DU;3
goaikut	goikkolin	V;COND;SG;1;LGSPEC1
dievvat	dievaime	V;IND;DU;1;PST
mánnat	mánaža	V;POT;SG;3
adnot	adnot	V;IND;PL;1;PRS
šearrát	šear'rálii	V;COND;SG;3;LGSPEC1
leavvat	leavašeiddet	V;COND;PL;2
arvit	arven	V;IND;SG;1;PST
lállit	láliiga	V;IND;DU;3;PST
čuoigát	čuoigálii	V;COND;SG;3;LGSPEC1
anihahtti	anihahttiide	ADJ;IN+ALL;PL
boltut	bolttuidet	V;IND;PL;2;PST
eahccit	ehcežeaba	V;POT;DU;3
nahkehit	nahkeha	V;IND;SG;3;PRS
šnjirgut	šnjirgoska	V;IMP;DU;3
čelččen	čelččemiid	N;GEN;PL
háistit	háisttáše	V;COND;PL;3
buokčat	buovččažeaba	V;POT;DU;3
čuoggut	čukkožit	V;POT;PL;1
riggut	rikkošeimme	V;COND;DU;1
skillat	skilažan	V;POT;SG;1
rinčát	rinčáimet	V;IND;PL;1;PST
buokčat	buovččaime	V;IND;DU;1;PST
duolvaseamos	duolvaseamos	ADJ;NOM;SG
johtit	johtoska	V;IMP;DU;3
oaggut	oakkun	V;IND;SG;1;PRS
ruhta	ruđaid	N;ACC;PL
gahkit	gahkoska	V;IMP;DU;3
málet	málejeahkki	V;IMP;DU;2
skilkit	skilkkát	V;IND;SG;2;PRS
dárustit	dárustehkos	V;IMP;SG;3
vurket	vurkešeiddet	V;COND;PL;2
arvit	arvve	V;IMP;SG;2
mánnat	mánažit	V;POT;PL;1
ráhkistuvvat	ráhkistuvaleiddet	V;COND;PL;2;LGSPEC1
vuoššat	vuš'šot	V;IMP;PL;1
beana	beanan	N;FRML;SG
breava	breava	N;NOM;SG
hoitát	hoitábeahtti	V;IND;DU;2;PRS
skeaikit	skeaikkášeiddet	V;COND;PL;2
vuolgit	vulggiime	V;IND;DU;1;PST
ballat	balaimet	V;IND;PL;1;PST
cuovkanit	cuovkanehkoska	V;IMP;DU;3
máhttit	máhtášeidde	V;COND;DU;2
vázzit	váccášit	V;COND;SG;2
almmaiduvvat	almmaiduvašeimmet	V;COND;PL;1
luohttit	luohtášeidde	V;COND;DU;2
goaivut	goivvožeahppi	V;POT;DU;2
ráhkistuvvat	ráhkistuvažit	V;POT;PL;1
oahppásit	oahppáseappot	ADJ;NOM;PL
vuosehit	vuosehit	V;IND;SG;2;PST
bárgut	bárggožehpet	V;POT;PL;2
njávkat	njávkkašeigga	V;COND;DU;3
vuohppát	vuohppán	V;IND;SG;1;PRS
dáigi	dáiggiide	N;IN+ALL;PL
šaddat	šattaleiddet	V;COND;PL;2;LGSPEC1
oahkut	ogošin	V;COND;SG;1
bákŋi	báŋiin	N;COM;SG
geahččalit	geahččalehkos	V;IMP;SG;3
jarfát	jarfážeaba	V;POT;DU;3
buolláhit	buol'láhežže	V;POT;DU;1
čuovgat	čuovgadiidda	ADJ;IN+ALL;PL
mánnat	mánne	V;IND;PL;3;PST
gođđat	gođalit	V;COND;SG;2;LGSPEC1
duogŋat	duokŋalii	V;COND;SG;3;LGSPEC1
čuovgat	čuovgat	ADJ;NOM;SG
dábálaš	dábálaččaide	ADJ;IN+ALL;PL
veaddit	veattáleigga	V;COND;DU;3;LGSPEC1
bláđet	bláđejehket	V;IMP;PL;2
gobmi	gopmis	N;PRP;SG
eahccit	eahcášeidde	V;COND;DU;2
gahkit	gagáleimmet	V;COND;PL;1;LGSPEC1
atnit	atne	V;IND;PL;3;PST
giellá	gielláid	N;ACC;PL
čájáhus	čájáhusaid	N;ACC;PL
čuohkat	čuhkoska	V;IMP;DU;3
čiehkat	čiehkabehtet	V;IND;PL;2;PRS
čopma	čomaid	N;ACC;PL
huilát	huilálin	V;COND;SG;1;LGSPEC1
oassi	osiiguin	N;COM;PL
čuoggut	čukkošeidde	V;COND;DU;2
adnostit	adnostit	V;IND;SG;2;PST
luohti	luohtái	N;IN+ALL;SG
johttát	johttájin	V;IND;SG;1;PST
muorji	muorjji	N;GEN;SG
oahkut	ogolin	V;COND;SG;1;LGSPEC1
viidni	viinniiguin	N;COM;PL
čavgadit	čavgadeappuid	ADJ;ACC;PL
hieibmat	hieimmažeaba	V;POT;DU;3
loaktit	loavttálii	V;COND;SG;3;LGSPEC1
áiru	áirru	N;GEN;SG
juogadit	juogadin	V;IND;SG;1;PST
gávrát	gávrájetnot	V;IMP;PL;1
buotnjut	bunjožit	V;POT;PL;1
adnot	adnošeigga	V;COND;DU;3
suollit	suolášeigga	V;COND;DU;3
bivvat	bivvet	V;IND;PL;3;PRS
muorji	murjjiin	N;PRP;PL
čulkit	čulkkáleimme	V;COND;DU;1;LGSPEC1
vašáleamos	vašálepmosis	ADJ;PRP;SG
hahppit	hahpiimet	V;IND;PL;1;PST
ráddut	ráttuime	V;IND;DU;1;PST
deklamašuvdna	deklamašuvnnain	N;PRP;PL
čuovga	čuvgii	N;IN+ALL;SG
sáhttit	sáhttet	V;IMP;PL;2
cuollat	cuolašeigga	V;COND;DU;3
arestet	aresteleidde	V;COND;DU;2;LGSPEC1
cuoigat	cuoigi	V;IMP;DU;2
navdit	navddežeahppi	V;POT;DU;2
gahppat	gahpalii	V;COND;SG;3;LGSPEC1
snorrát	snor'rájetne	V;IND;DU;1;PRS
orrut	orrubehtet	V;IND;PL;2;PRS
ovccinuppelogát	ovccinuppelogádiid	ADJ;GEN;PL
losimus	losimusaid	ADJ;ACC;PL
coggat	cokkat	V;IND;SG;2;PRS
siellu	sieluid	N;GEN;PL
suohpput	suhpožit	V;POT;PL;1
bardit	barddášit	V;COND;SG;2
viggat	vikkaleimmet	V;COND;PL;1;LGSPEC1
vahcut	vazut	V;IND;SG;2;PRS
geahčastit	geahčasteidde	V;IND;DU;2;PST
arestet	arestešin	V;COND;SG;1
dolastaddat	dolastattaiga	V;IND;DU;3;PST
ruoŧŧa	ruoŧaid	N;GEN;PL
eahccit	eahcále	V;COND;PL;3;LGSPEC1
gággat	gákkažat	V;POT;SG;2
čuohcat	čuozažat	V;POT;SG;2
borgár	borgáriin	N;COM;SG
navdit	navddášeiddet	V;COND;PL;2
duohččat	duohčaimet	V;IND;PL;1;PST
geallit	geležan	V;POT;SG;1
skoahččát	skoahččán	V;IND;SG;1;PRS
oarbbis	oarbásiid	N;ACC;PL
váibmosuotna	váibmosuonain	N;PRP;PL
doarggistit	doarggistit	V;IND;PL;1;PRS
dálvat	dálvva	V;IMP;SG;2
suddat	suttale	V;COND;PL;3;LGSPEC1
suhttat	suhtalin	V;COND;SG;1;LGSPEC1
maŋŋebárga	maŋŋebárgii	N;IN+ALL;SG
searvi	servviide	N;IN+ALL;PL
gazza	gaccaid	N;GEN;PL
basaldat	basaldagas	N;PRP;SG
apotehka	apotehkain	N;COM;SG
šleađgut	šleđggožat	V;POT;SG;2
mahkkit	mahkkibeahtti	V;IND;DU;2;PRS
veaddit	veaddi	V;IMP;DU;2
vázzit	vázzot	V;IMP;PL;1
luddat	luttaše	V;COND;PL;3
šleađgut	šleđggožit	V;POT;PL;1
gealdit	gealddášeiddet	V;COND;PL;2
fitnat	finašeimme	V;COND;DU;1
sáhttit	sáhtáleimmet	V;COND;PL;1;LGSPEC1
buođđut	buđošeiddet	V;COND;PL;2
iras	irrasii	ADJ;IN+ALL;SG
golgadit	golgadeadnu	V;IMP;DU;1
čeŋkkeš	čeŋkkežiin	N;PRP;PL
gávrát	gávráše	V;COND;PL;3
vuohppát	vuohppábeahtti	V;IND;DU;2;PRS
gáhččat	gáhččá	V;IND;SG;3;PRS
doarrut	doarrut	V;IND;PL;1;PRS
cukcat	cukcot	V;IMP;PL;1
jástit	jásttežeaba	V;POT;DU;3
gahppat	gahppat	V;IND;PL;1;PRS
čuopmat	čuomažit	V;POT;PL;3
sávza	sávzii	N;IN+ALL;SG
bassit	base	V;IMP;SG;2
cohkkát	cohkkáleimmet	V;COND;PL;1;LGSPEC1
bahčit	bahčoset	V;IMP;PL;3
jahtat	jahte	V;IND;PL;3;PST
jástit	jástte	V;IMP;SG;2
lávži	lávžžiide	N;IN+ALL;PL
ruhta	ruđat	N;NOM;PL
násti	nástin	N;FRML;SG
anteanna	anteannain	N;PRP;PL
duoggut	dukkožat	V;POT;SG;2
esttegiella	esttegielaiguin	N;COM;PL
čitnut	činoleiddet	V;COND;PL;2;LGSPEC1
rusen	ruseniiguin	N;COM;PL
dárustit	dárustežže	V;POT;DU;1
golgadit	golgadivččii	V;COND;SG;3
automatiseret	automatiseriide	V;IND;DU;2;PST
paradiisa	paradiissa	N;ACC;SG
joatkit	jotkot	V;IMP;PL;1
čearret	čearrehiidda	N;IN+ALL;PL
sihtat	siđalit	V;COND;SG;2;LGSPEC1
čoalbmi	čoalmmit	N;NOM;PL
doarggistit	doarggisteažžat	V;POT;PL;1
sildnit	silnniime	V;IND;DU;1;PST
čuohcat	čuozaiga	V;IND;DU;3;PST
bierfát	bierfájeahkki	V;IMP;DU;2
guoskat	guskos	V;IMP;SG;3
árrit	árežehpet	V;POT;PL;2
gohcut	gozožat	V;POT;SG;2
bealkit	bealku	V;IMP;DU;1
juogadit	juogadat	V;IND;SG;2;PRS
vihpat	vihpet	V;IND;PL;3;PRS
čallat	čallaba	V;IND;DU;3;PRS
bokset	boksešeiddet	V;COND;PL;2
šnjuoggát	šnjuoggálin	V;COND;SG;1;LGSPEC1
ájáhallat	ájáhallen	V;IND;SG;1;PST
autoriseret	autoriserejehkoska	V;IMP;DU;3
deminutiiva	deminutiivvas	N;PRP;SG
gopmat	gomalin	V;COND;SG;1;LGSPEC1
anihit	anihetne	V;IND;DU;1;PRS
joatkit	joatkkáleigga	V;COND;DU;3;LGSPEC1
njáhkat	njágalit	V;COND;SG;2;LGSPEC1
almmivierca	almmivierccain	N;PRP;PL
luddat	luttažat	V;POT;SG;2
buođđut	buđđo	V;IND;DU;1;PRS
galbmit	galmmežit	V;POT;PL;3
doaibma	doaimma	N;GEN;SG
suohpput	suhpožeahppi	V;POT;DU;2
bardit	barddášeimmet	V;COND;PL;1
rihccut	rihcoleimmet	V;COND;PL;1;LGSPEC1
čurti	čurti	N;NOM;SG
guhkkat	guhkket	V;IMP;PL;2
buoiddášit	buoiddášežže	V;POT;DU;1
iđitgákti	iđitgávttit	N;NOM;PL
perspektiiva	perspektiivii	N;IN+ALL;SG
dolastaddat	dolastattaleimmet	V;COND;PL;1;LGSPEC1
botnjat	bonjaidet	V;IND;PL;2;PST
mieđašeatni	mieđašeniide	N;IN+ALL;PL
buođđut	buđoleimme	V;COND;DU;1;LGSPEC1
loktat	lovttan	V;IND;SG;1;PRS
čuoigát	čuoigáide	V;IND;DU;2;PST
nearrat	nearažit	V;POT;PL;3
galbmit	galbmibehtet	V;IND;PL;2;PRS
viidni	viidnái	N;IN+ALL;SG
cohkkát	cohkkáidet	V;IND;PL;2;PST
vuosehit	vuosehežže	V;POT;DU;1
ruoššastit	ruoššastit	V;IND;SG;2;PST
seailut	seailu	V;IND;SG;3;PRS
gárta	gárttas	N;PRP;SG
bláđet	bláđejit	V;IND;PL;3;PRS
jurdit	jurden	V;IND;SG;1;PST
cahpat	cahpet	V;IND;SG;2;PST
čolgat	čolggaža	V;POT;SG;3
vuoražas	vuoražasaid	N;ACC;PL
čuollát	čuol'láše	V;COND;PL;3
buolláhit	buol'láhivččii	V;COND;SG;3
govdut	govdduiga	V;IND;DU;3;PST
háistit	háisttášeimme	V;COND;DU;1
alvvahuvvat	alvvahuvaleimme	V;COND;DU;1;LGSPEC1
suollit	suollit	V;IND;PL;1;PRS
čoaggit	čogget	V;IMP;PL;2
lutnjat	lunjaide	V;IND;DU;2;PST
skoahččát	skoahččášeigga	V;COND;DU;3
reavvat	revvot	V;IMP;PL;1
vealgut	velggoleidde	V;COND;DU;2;LGSPEC1
normálamus	normálamusa	ADJ;GEN;SG
kirku	kirkuin	N;PRP;PL
bearrat	berrot	V;IMP;PL;1
doallat	doalašeimmet	V;COND;PL;1
játnat	játnoska	V;IMP;DU;3
máhttit	máhtálit	V;COND;SG;2;LGSPEC1
čoaskát	čoaskábuid	ADJ;GEN;PL
ruššat	ruš'ši	V;IMP;DU;2
gohpat	gohpe	V;IND;PL;3;PST
akšuvdna	akšuvnnaiguin	N;COM;PL
navdit	navddát	V;IND;SG;2;PRS
biebmat	biepmat	V;IND;SG;2;PRS
albmaduvvat	albmaduv'vu	V;IMP;DU;1
advokáhta	advokáhtaiguin	N;COM;PL
bárgut	bárggošeimme	V;COND;DU;1
agáiduvvat	agáiduvaleimme	V;COND;DU;1;LGSPEC1
ruššat	rušažan	V;POT;SG;1
mođđat	mođđet	V;IMP;PL;2
geahččalit	geahččal	V;IMP;SG;2
suoidni	suinniid	N;ACC;PL
nallat	nalašeidde	V;COND;DU;2
guoddit	guottálii	V;COND;SG;3;LGSPEC1
čuožžut	čuččoše	V;COND;PL;3
doallat	doalaleimmet	V;COND;PL;1;LGSPEC1
arestet	areste	V;IND;SG;3;PRS
adopteret	adopteriimet	V;IND;PL;1;PST
astat	asttaleiddet	V;COND;PL;2;LGSPEC1
sággat	sákkale	V;COND;PL;3;LGSPEC1
huilát	huiláleimmet	V;COND;PL;1;LGSPEC1
duottar	duoddariin	N;COM;SG
njuoršu	njuorššuiguin	N;COM;PL
čeargulit	čearguleažžaba	V;POT;DU;3
cuovkanit	cuovkaneahkki	V;IMP;DU;2
bállit	bálálii	V;COND;SG;3;LGSPEC1
diehtit	diehtibehtet	V;IND;PL;2;PRS
hihttát	hihttálit	V;COND;SG;2;LGSPEC1
vuossárga	vuossárgga	N;ACC;SG
šnjoargut	šnjorggošeidde	V;COND;DU;2
njaldit	njalddežat	V;POT;SG;2
adopteret	adopterejehkoset	V;IMP;PL;3
niski	niskái	N;IN+ALL;SG
govahallat	govahal'lu	V;IMP;DU;1
cummát	cummášeidde	V;COND;DU;2
čuovgadeamos	čuovgadepmosiidda	ADJ;IN+ALL;PL
dutkat	dutkkašeiddet	V;COND;PL;2
njohcut	njozuidet	V;IND;PL;2;PST
máinnastit	máinnastehpet	V;IND;PL;2;PRS
vuodjat	vudjot	V;IMP;PL;1
áigut	áiggut	V;IND;SG;2;PRS
gulkat	gulkkaidet	V;IND;PL;2;PST
gargit	garget	V;IND;SG;2;PST
šiitit	šiiti	V;IMP;DU;2
oahppat	oahppaba	V;IND;DU;3;PRS
spildi	spilddiid	N;ACC;PL
njuordat	njurdet	V;IND;SG;2;PST
guolbmat	guolbmi	V;IMP;DU;2
deakčut	devččošit	V;COND;SG;2
mánnu	mánuin	N;COM;SG
riggat	rigge	V;IND;PL;3;PST
gahcut	gahcot	V;IND;SG;2;PST
suossa	sussii	N;IN+ALL;SG
roggat	rogget	V;IND;SG;2;PST
goaski	goskkiid	N;ACC;PL
váddut	váttožeaba	V;POT;DU;3
akustihkalaš	akustihkalaččat	ADJ;NOM;PL
loaidat	loidet	V;IMP;PL;2
bassat	bassen	V;IND;SG;1;PST
sirdát	sirdážetne	V;POT;DU;1
doarrát	doar'rášit	V;COND;SG;2
giessat	giesalin	V;COND;SG;1;LGSPEC1
rádjat	rájažat	V;POT;SG;2
uštit	ušttiiga	V;IND;DU;3;PST
árpa	árppain	N;COM;SG
duostat	duosttaleiddet	V;COND;PL;2;LGSPEC1
massit	massežit	V;POT;PL;1
oažžut	oččui	V;IND;SG;3;PST
barbáralaš	barbáralačča	ADJ;GEN;SG
seassat	seasaleigga	V;COND;DU;3;LGSPEC1
apmaseamos	apmasepmosii	ADJ;IN+ALL;SG
náitit	náitoset	V;IMP;PL;3
vuohpput	vuhpošit	V;COND;SG;2
čeargat	čerget	V;IND;SG;2;PST
buollát	buol'lájehket	V;IMP;PL;2
nuondat	nuonddaleigga	V;COND;DU;3;LGSPEC1
geallat	gellon	V;IMP;SG;1
borgárvuohta	borgárvuhtii	N;IN+ALL;SG
čavgadeamos	čavgadepmosii	ADJ;IN+ALL;SG
skuhčat	skužaide	V;IND;DU;2;PST
deaššat	deššos	V;IMP;SG;3
čuollat	čuolažehpet	V;POT;PL;2
bávtat	bávttaše	V;COND;PL;3
láigohit	láigoheidde	V;IND;DU;2;PST
čuolbmat	čulbmet	V;IND;SG;2;PST
bivdit	bivddášeiddet	V;COND;PL;2
goargŋut	gorkŋošii	V;COND;SG;3
duhtat	duđalin	V;COND;SG;1;LGSPEC1
álddagas	álddagas	N;NOM;SG
silta	silttaiguin	N;COM;PL
čuodjat	čudjet	V;IND;SG;2;PST
lihkkat	lihkken	V;IND;SG;1;PST
vuovdinhaddi	vuovdinhattiid	N;ACC;PL
honnet	honnega	N;ACC;SG
lossadit	lossadeappos	ADJ;PRP;SG
liekčát	liekčájetnot	V;IMP;PL;1
guvrut	guvrrošeimme	V;COND;DU;1
analysa	analysain	N;PRP;PL
almmuhit	almmuhivččet	V;COND;SG;2
gákkis	gággásii	N;IN+ALL;SG
njuordat	njuorddašeiddet	V;COND;PL;2
bávkit	bávká	V;IND;SG;3;PRS
náitit	náitu	V;IMP;DU;1
smáhket	smáhkešeimme	V;COND;DU;1
dássi	dásiid	N;ACC;PL
boaššu	boaššuid	N;GEN;PL
guoirat	guire	V;IND;DU;1;PRS
illu	iluilo	N;GEN;SG
guvrát	guvrážat	V;POT;SG;2
ruoidnat	ruoidnabeahtti	V;IND;DU;2;PRS
sárrat	sáražit	V;POT;PL;3
sirdát	sirdáleidde	V;COND;DU;2;LGSPEC1
doarrát	doar'rále	V;COND;PL;3;LGSPEC1
náitit	náiti	V;IMP;DU;2
ustit	ustibin	N;FRML;SG
alvvaiduvvat	alvvaiduvaža	V;POT;SG;3
bruvda	bruvdan	N;FRML;SG
sirdit	sirdde	V;IMP;SG;2
ákšu	ákšu	N;NOM;SG
duđahit	duđaheažžabeahtti	V;POT;DU;2
geaidut	geaidut	V;IND;PL;1;PRS
doaimmahit	doaimmat	V;IMP;SG;2
eadnádet	etniideattet	N;ACC;PL
ábiruvvá	ábiruv'vái	N;IN+ALL;SG
biibal	biibala	N;ACC;SG
šibitdoavttir	šibitdoavttir	N;NOM;SG
šiitit	šiittežeahppi	V;POT;DU;2
stivát	stiváidet	V;IND;PL;2;PST
ajihastit	ajihaste	V;IND;PL;3;PST
fuoikit	fuikoset	V;IMP;PL;3
duoldat	duolddaleimmet	V;COND;PL;1;LGSPEC1
bieđgát	bieđgálin	V;COND;SG;1;LGSPEC1
ruoidnát	ruoidnáime	V;IND;DU;1;PST
šloaŋgát	šloaŋgá	V;IMP;SG;2
reŋgot	reŋgojehket	V;IMP;PL;2
sáivi	sáivvi	N;GEN;SG
guolástit	guolásteaba	V;IND;DU;3;PRS
delegašuvdna	delegašuvnnas	N;PRP;SG
njávgut	njávgguiga	V;IND;DU;3;PST
sustit	sustteža	V;POT;SG;3
ahkáduvvat	ahkáduvašeimme	V;COND;DU;1
uštit	ušttát	V;IND;SG;2;PRS
oahppat	oahpažeaba	V;POT;DU;3
gáddit	gáttálit	V;COND;SG;2;LGSPEC1
njanzát	njanzájetne	V;IND;DU;1;PRS
hávkat	hávkkažit	V;POT;PL;1
eadjit	eježat	V;POT;SG;2
dieđa	diehtagiin	N;PRP;PL
gordni	gortniin	N;COM;SG
njáldit	njáldet	V;IND;PL;3;PRS
veavvát	veav'vájit	V;IND;PL;3;PRS
čielgaseamos	čielgasepmosiin	ADJ;PRP;PL
čoarrut	čorošeigga	V;COND;DU;3
háhkat	háhken	V;IND;SG;1;PST
bánžat	bánžašeidde	V;COND;DU;2
cadjat	caddji	V;IMP;DU;2
dollavárri	dollaváris	N;PRP;SG
sahčat	sažaleigga	V;COND;DU;3;LGSPEC1
ruoksadit	ruoksadeappuid	ADJ;GEN;PL
vuohčit	vužii	V;IND;SG;3;PST
assi	asiid	N;ACC;PL
veavvát	veav'válii	V;COND;SG;3;LGSPEC1
sárrat	sárašii	V;COND;SG;3
seaisat	seaisi	V;IMP;DU;2
mohkkámus	mohkkámusas	ADJ;PRP;SG
guokteloginjealját	guokteloginjealjáda	ADJ;GEN;SG
čeallut	čeložan	V;POT;SG;1
čoavdit	čovde	V;IND;DU;1;PRS
seaisat	seaissašeimme	V;COND;DU;1
smiehttat	smiehttá	V;IND;SG;3;PRS
soallut	soložehpet	V;POT;PL;2
cábmit	cápmášit	V;COND;SG;2
sárrat	sáraše	V;COND;PL;3
spildut	spilddoleiddet	V;COND;PL;2;LGSPEC1
čorget	čorge	V;IND;SG;3;PRS
fállat	fálažeahppi	V;POT;DU;2
čohkka	čohkas	N;PRP;SG
laskat	laskkažehpet	V;POT;PL;2
cahkat	cahken	V;IND;SG;1;PST
áldu	áldun	N;FRML;SG
soahki	soagit	N;NOM;PL
njammat	njamaidet	V;IND;PL;2;PST
čieskat	čieskkalit	V;COND;SG;2;LGSPEC1
lahpat	labaime	V;IND;DU;1;PST
ráhkestit	ráhkesteažžabeahtti	V;POT;DU;2
bassat	basset	V;IND;PL;3;PRS
ruonámus	ruonámus	ADJ;NOM;SG
akustihkka	akustihkkii	N;IN+ALL;SG
oskut	oskkoleimmet	V;COND;PL;1;LGSPEC1
bargat	barggažit	V;POT;PL;1
niitit	niittáleimme	V;COND;DU;1;LGSPEC1
gáranas	gáranasa	N;ACC;SG
áhkku	áhkuid	N;GEN;PL
álddagas	álddagasat	N;NOM;PL
dievvasit	dievvaseappuin	ADJ;PRP;PL
máltit	málttášeiddet	V;COND;PL;2
fállat	fállos	V;IMP;SG;3
addilit	addileidde	V;IND;DU;2;PST
bálgán	bálgáidan	N;GEN;PL
giemardit	giemardeaččat	V;POT;SG;2
baldalit	baldalivččiimet	V;COND;PL;1
goikáseamos	goikásepmosat	ADJ;NOM;PL
garcut	garccošeigga	V;COND;DU;3
dadjat	dadjá	V;IND;SG;3;PRS
áddet	áddejit	V;IND;SG;2;PST
seabbát	seabbášeidde	V;COND;DU;2
širrat	širaleigga	V;COND;DU;3;LGSPEC1
readnját	readnjážeaba	V;POT;DU;3
seaŋáš	seaŋáš	N;NOM;SG
geavvat	gevvoska	V;IMP;DU;3
áddet	áddejedje	V;IND;PL;3;PST
juksat	juvssaše	V;COND;PL;3
duhtat	duhtet	V;IND;SG;2;PST
akademiija	akademiijas	N;PRP;SG
bilidit	bilideažžaba	V;POT;DU;3
muohttát	muohttáidet	V;IND;PL;2;PST
njuovvat	njuovaža	V;POT;SG;3
dárbu	dárbbu	N;GEN;SG
honnet	honnegat	N;NOM;PL
hearvát	hearvášit	V;COND;SG;2
bákŋat	báŋašeidde	V;COND;DU;2
buođgát	buođgájit	V;IND;SG;2;PST
goikat	goikkažit	V;POT;PL;3
guovgát	guovgábehtet	V;IND;PL;2;PRS
coakcut	coakcut	V;IND;PL;1;PRS
njoarrat	njorroset	V;IMP;PL;3
juná	junáin	N;COM;SG
sáhka	ságat	N;NOM;PL
básár	básáriin	N;COM;SG
reavrut	reavrrun	V;IND;SG;1;PRS
stirrát	stir'ráide	V;IND;DU;2;PST
juohkit	juhken	V;IND;SG;1;PST
háhkat	háhkku	V;IMP;DU;1
áhkkilsámegiella	áhkkilsámegielaid	N;ACC;PL
máilmmicup	máilmmicupat	N;NOM;PL
dehálit	deháleappo	ADJ;ACC;SG
veadjit	veadjá	V;IND;SG;3;PRS
njoammut	njomoleidde	V;COND;DU;2;LGSPEC1
suvdit	suvddán	V;IND;SG;1;PRS
fállat	fálaleidde	V;COND;DU;2;LGSPEC1
almmuhit	almmuhehpet	V;IND;PL;2;PRS
guođđit	guđiide	V;IND;DU;2;PST
litnjat	linjašeimmet	V;COND;PL;1
vuoigŋat	vuoiŋŋaleidde	V;COND;DU;2;LGSPEC1
duohki	dugiin	N;PRP;PL
guovlat	guovllažehpet	V;POT;PL;2
áigut	áiggui	V;IND;SG;3;PST
sadjit	sadjá	V;IND;SG;3;PRS
fállat	fálaleigga	V;COND;DU;3;LGSPEC1
nuondat	nundoset	V;IMP;PL;3
sahát	sahášeigga	V;COND;DU;3
goargŋut	gorgŋot	V;IMP;PL;2
ekonomiija	ekonomiijan	N;FRML;SG
uštit	ušttiidet	V;IND;PL;2;PST
bollát	bol'lášit	V;COND;SG;2
nordat	nordoset	V;IMP;PL;3
sehkket	sehkkešin	V;COND;SG;1
oaidnit	oinnežat	V;POT;SG;2
hápmi	hámi	N;GEN;SG
čeargat	čeargabehtet	V;IND;PL;2;PRS
basastit	basastehpet	V;IND;PL;2;PRS
goikásit	goikáseappo	ADJ;GEN;SG
roggat	rokkaleidde	V;COND;DU;2;LGSPEC1
uhkki	uhkiin	N;COM;SG
dehálit	deháleappo	ADJ;GEN;SG
guoirat	guiron	V;IMP;SG;1
šlahtti	šlahttin	N;FRML;SG
čeavlái	čeavlát	ADJ;NOM;PL
barbáralaš	barbáralaš	ADJ;NOM;SG
liippát	liippážat	V;POT;SG;2
rátkit	rátká	V;IND;SG;3;PRS
dihkkat	dihkašeimme	V;COND;DU;1
čiežalogát	čiežalogádiiguin	ADJ;COM;PL
fagŋát	fagŋášit	V;COND;SG;2
buollát	buol'láidet	V;IND;PL;2;PST
reahkut	regoleimme	V;COND;DU;1;LGSPEC1
suhkkát	suhkkáleimmet	V;COND;PL;1;LGSPEC1
gieldit	gilde	V;IND;PL;3;PST
jiekŋa	jieŋaiguin	N;COM;PL
veadjit	veajáše	V;COND;PL;3
cabbi	cabbin	N;FRML;SG
sodnját	sodnjájehkoska	V;IMP;DU;3
skarkit	skarkkášeigga	V;COND;DU;3
deaivat	deaivvalin	V;COND;SG;1;LGSPEC1
dadjat	dajažetne	V;POT;DU;1
alihit	aliheabbon	ADJ;FRML;SG
geaidi	geaidái	N;IN+ALL;SG
šealgut	šelggošin	V;COND;SG;1
oahppat	oahpašit	V;COND;SG;2
giellaoahppa	giellaoahppa	N;NOM;SG
višuvdna	višuvnnaiguin	N;COM;PL
dávgut	dávggo	V;IMP;SG;2
leabbat	leabbadiin	ADJ;PRP;PL
máltit	málte	V;IND;PL;3;PST
haksit	havssiiga	V;IND;DU;3;PST
njoammut	njoam'mu	V;IMP;DU;1
máttasámegiella	máttasámegiela	N;ACC;SG
deaffat	deafažehpet	V;POT;PL;2
bihppor	bihpporiin	N;COM;SG
basastit	basastan	V;IND;SG;1;PRS
bronsa	bronssaid	N;ACC;PL
lihppu	lihpuid	N;ACC;PL
čuolda	čuolddat	N;NOM;PL
almmuhit	almmuheahkki	V;IMP;DU;2
šlundut	šlundu	V;IMP;DU;1
reavrát	reavráleidde	V;COND;DU;2;LGSPEC1
hullat	hullet	V;IND;PL;3;PRS
čiežalogát	čiežalogáda	ADJ;GEN;SG
riessat	riesažeahppi	V;POT;DU;2
eadnán	etniinan	N;PRP;PL
muitalit	muitalivččiime	V;COND;DU;1
vardit	vardos	V;IMP;SG;3
gieldit	gilddiide	V;IND;DU;2;PST
ráhkistit	ráhkisteahppi	V;IND;DU;2;PRS
boikohttet	boikohttežit	V;POT;PL;3
goahcat	goazaleidde	V;COND;DU;2;LGSPEC1
báron	bároniin	N;COM;SG
njanzát	njanzájeadnu	V;IMP;DU;1
máššat	mášaleidde	V;COND;DU;2;LGSPEC1
goikásit	goikáseappuin	ADJ;COM;SG
šealgut	šelggoše	V;COND;PL;3
skutnjat	skunjai	V;IND;SG;3;PST
cuhpat	cubaše	V;COND;PL;3
čiekŋalit	čiekŋaleappuid	ADJ;GEN;PL
gotka	gotkkat	N;NOM;PL
máššat	máššoska	V;IMP;DU;3
haksit	havssálin	V;COND;SG;1;LGSPEC1
skuhrrat	skuhrren	V;IND;SG;1;PST
seassat	seasašeimmet	V;COND;PL;1
dimenšuvdna	dimenšuvnnaid	N;ACC;PL
časkit	časkon	V;IMP;SG;1
šleambit	šleambá	V;IND;SG;3;PRS
beassat	beasaime	V;IND;DU;1;PST
vuodjat	vuojalii	V;COND;SG;3;LGSPEC1
geavrát	geavráidet	V;IND;PL;2;PST
soallut	soal'lu	V;IMP;DU;2
šuohkkit	šuohkálii	V;COND;SG;3;LGSPEC1
ahkiduššat	ahkidušaleiddet	V;COND;PL;2;LGSPEC1
geahččat	geahččabeahtti	V;IND;DU;2;PRS
oskut	oskkuiga	V;IND;DU;3;PST
šnjoarrat	šnjoaralii	V;COND;SG;3;LGSPEC1
oahppat	ohppos	V;IMP;SG;3
riessat	riesaidet	V;IND;PL;2;PST
bolsttar	bolstara	N;GEN;SG
doapmat	dopme	V;IND;DU;1;PRS
bilkidit	bilkideaččat	V;POT;SG;2
dáiddalaš	dáiddalaččain	ADJ;COM;SG
čohkat	čohkku	V;IMP;DU;1
áibat	áibos	V;IMP;SG;3
dárogiella	dárogillii	N;IN+ALL;SG
deallut	deložat	V;POT;SG;2
juolgat	julget	V;IMP;PL;2
sorját	sorjášeimmet	V;COND;PL;1
ciellat	cielaime	V;IND;DU;1;PST
dadjat	dajažan	V;POT;SG;1
čájihit	čájihii	V;IND;SG;3;PST
čoarvi	čoarvvit	N;NOM;PL
duhtavašvuohta	duhtavašvuohta	N;NOM;SG
suoládit	suoládehkot	V;IMP;PL;1
coakci	covcciid	N;GEN;PL
bieđgát	bieđgášit	V;COND;SG;2
dápmat	dápmabeahtti	V;IND;DU;2;PRS
sirdát	sirdáše	V;COND;PL;3
uhkidit	uhkidivččii	V;COND;SG;3
čohkka	čohkkan	N;FRML;SG
šnjoarrat	šnjorret	V;IMP;PL;2
sáhka	ságas	N;PRP;SG
njoarostit	njoarosteaba	V;IND;DU;3;PRS
juokŋat	juokŋat	V;IND;PL;1;PRS
ovccilogát	ovccilogádiid	ADJ;ACC;PL
loaidat	loaiddaleimmet	V;COND;PL;1;LGSPEC1
báistit	báisttášeimme	V;COND;DU;1
čohkat	čohke	V;IND;PL;3;PST
goikat	goikkaža	V;POT;SG;3
skuhčat	skužašeigga	V;COND;DU;3
seaivut	seivvoža	V;POT;SG;3
aresteret	aresteren	V;IND;SG;1;PRS
bárra	bárain	N;PRP;PL
goalmmát	goalmmádiidda	ADJ;IN+ALL;PL
smiehttat	smiehtašeimmet	V;COND;PL;1
gissat	gissat	V;IND;PL;1;PRS
seaivut	seivvolii	V;COND;SG;3;LGSPEC1
čeargut	čergguide	V;IND;DU;2;PST
vávvát	váv'váide	V;IND;DU;2;PST
veadjit	vedje	V;IND;PL;3;PST
gánda	gánddain	N;PRP;PL
sirgŋat	sirkŋažat	V;POT;SG;2
buoibmat	buibmos	V;IMP;SG;3
oastit	oasttášin	V;COND;SG;1
čáskat	čásken	V;IND;SG;1;PST
buorránit	buorránivččen	V;COND;SG;1
váddut	váddot	V;IND;PL;3;PRS
áfáiduvvat	áfáiduvaimet	V;IND;PL;1;PST
sirgŋat	sirkŋaleidde	V;COND;DU;2;LGSPEC1
guostát	guostájehkoska	V;IMP;DU;3
váldit	váldoska	V;IMP;DU;3
giessat	gisson	V;IMP;SG;1
faggut	fakkoleimmet	V;COND;PL;1;LGSPEC1
vihttalogát	vihttalogáda	ADJ;ACC;SG
aresteret	aresterejin	V;IND;SG;1;PST
goargŋut	gorkŋoleimme	V;COND;DU;1;LGSPEC1
hullat	hulaide	V;IND;DU;2;PST
doaimmahit	doaimmahe	V;IND;PL;3;PST
ađahuvvat	ađahuvašin	V;COND;SG;1
loahppat	loahppabeahtti	V;IND;DU;2;PRS
goikásit	goikáseappuide	ADJ;IN+ALL;PL
almmostahttit	almmostahtáše	V;COND;PL;3
issorit	issoreappo	ADJ;GEN;SG
giektat	gikten	V;IND;SG;1;PST
snuhrrat	snuhraleimme	V;COND;DU;1;LGSPEC1
čála	čállagiid	N;ACC;PL
gaškát	gaškáime	V;IND;DU;1;PST
njoarrat	njoar'ri	V;IMP;DU;2
máššat	máššet	V;IND;SG;2;PST
laddat	lattaimet	V;IND;PL;1;PST
váldit	váldon	V;IMP;SG;1
dipmat	dima	V;IMP;SG;2
aiddostahttit	aiddostahttoska	V;IMP;DU;3
snurkit	snurkkášeimmet	V;COND;PL;1
alfabehta	alfabehtaide	N;IN+ALL;PL
čuovggahit	čuovggaheaččat	V;POT;SG;2
mearka	mearkkaid	N;GEN;PL
čákŋat	čákŋá	V;IND;SG;3;PRS
čihkoseamos	čihkosepmosiid	ADJ;GEN;PL
honnet	honnegii	N;IN+ALL;SG
suostat	susten	V;IND;SG;1;PST
báistit	báistá	V;IND;SG;3;PRS
nordat	norddat	V;IND;SG;2;PRS
haksit	havssán	V;IND;SG;1;PRS
giron	gironat	N;NOM;PL
riessat	riesašit	V;COND;SG;2
stumpát	stumpážetne	V;POT;DU;1
váidit	váiddále	V;COND;PL;3;LGSPEC1
bustávva	bustávaiguin	N;COM;PL
náitit	náittášit	V;COND;SG;2
ruoidnat	ruoinnat	V;IND;SG;2;PRS
gargit	garggáleigga	V;COND;DU;3;LGSPEC1
njalgat	njalggaleiddet	V;COND;PL;2;LGSPEC1
veallát	veal'lášeidde	V;COND;DU;2
máksit	mávssálit	V;COND;SG;2;LGSPEC1
uhkidit	uhkideažžat	V;POT;PL;1
sárrat	sár'ri	V;IMP;DU;2
geahččat	geahčažan	V;POT;SG;1
njávgit	njávggálit	V;COND;SG;2;LGSPEC1
skávgat	skávggažeahppi	V;POT;DU;2
dávgi	dávggiin	N;PRP;PL
speallat	speallabehtet	V;IND;PL;2;PRS
coakcut	cokcot	V;IND;SG;2;PST
máistit	máisttáleiddet	V;COND;PL;2;LGSPEC1
garcut	garccuidet	V;IND;PL;2;PST
diktit	diktet	V;IND;PL;3;PRS
čáskat	čáskon	V;IMP;SG;1
bárdnat	bártnaleigga	V;COND;DU;3;LGSPEC1
sirgŋat	sirkŋaiga	V;IND;DU;3;PST
ássat	ásaža	V;POT;SG;3
seabbát	seabbále	V;COND;PL;3;LGSPEC1
vuohčut	vuhčo	V;IND;PL;3;PST
liiki	liikkiin	N;COM;SG
gossat	gosse	V;IND;DU;1;PRS
baldalit	baldalit	V;IND;PL;3;PRS
heaitit	heaittášeidde	V;COND;DU;2
guoirat	guoirraleimmet	V;COND;PL;1;LGSPEC1
cahppát	cahppájin	V;IND;SG;1;PST
suhkkát	suhkkájit	V;IND;PL;3;PRS
guoggát	guoggájeadnu	V;IMP;DU;1
lahpat	labalit	V;COND;SG;2;LGSPEC1
ruossut	rusoleimme	V;COND;DU;1;LGSPEC1
stuorit	stuoribuin	ADJ;PRP;PL
spildi	spildái	N;IN+ALL;SG
čeahppi	čeahpis	ADJ;PRP;SG
háhkat	háhkoset	V;IMP;PL;3
guoggát	guoggášit	V;COND;SG;2
bassat	basažit	V;POT;PL;3
ciellat	cielašeiddet	V;COND;PL;2
cahppát	cahppájehkos	V;IMP;SG;3
čuoskut	čuskkuime	V;IND;DU;1;PST
loahppat	loahppabehtet	V;IND;PL;2;PRS
bollát	bol'lálii	V;COND;SG;3;LGSPEC1
giessat	giesaleiddet	V;COND;PL;2;LGSPEC1
adresseret	adresseriidet	V;IND;PL;2;PST
láigohit	láigoheadnu	V;IMP;DU;1
gutna	gunain	N;COM;SG
váibmu	váibmu	N;NOM;SG
čoavdit	čovdoska	V;IMP;DU;3
sirdit	sirddášeidde	V;COND;DU;2
háhkat	hágažetne	V;POT;DU;1
čiežalogát	čiežalogádii	ADJ;IN+ALL;SG
gullat	gulat	V;IND;SG;2;PRS
geallat	gealat	V;IND;SG;2;PRS
garcut	garccošii	V;COND;SG;3
rihcit	rihciha	N;GEN;SG
šuohkkit	šuhkiimet	V;IND;PL;1;PST
veadjit	veajášeimmet	V;COND;PL;1
jorbasit	jorbaseappuiguin	ADJ;COM;PL
vuoidat	vuoidda	V;IMP;SG;2
nagir	nahkáris	N;PRP;SG
ruossut	rusoleiddet	V;COND;PL;2;LGSPEC1
juolgat	juolggaide	V;IND;DU;2;PST
goallut	gollot	V;IND;SG;2;PST
vuoitit	vuittežat	V;POT;SG;2
skállat	skálaleigga	V;COND;DU;3;LGSPEC1
skuhčat	skužažat	V;POT;SG;2
deaivat	deaivvaše	V;COND;PL;3
gallet	galliidet	V;IND;PL;2;PST
biergu	bierggu	N;GEN;SG
muohttát	muohttále	V;COND;PL;3;LGSPEC1
ráhkestit	ráhkestehkoset	V;IMP;PL;3
áibmat	áimmai	V;IND;SG;3;PST
njuikut	njuikkoleimmet	V;COND;PL;1;LGSPEC1
áddet	ádde	V;IMP;SG;2
snuhrrat	snuhrašeigga	V;COND;DU;3
njávgut	njávgguimet	V;IND;PL;1;PST
issorasamus	issorasamussan	ADJ;FRML;SG
guoggut	gukkuide	V;IND;DU;2;PST
njuikut	njuikkožit	V;POT;PL;1
ballan	ballamiidda	N;IN+ALL;PL
goallut	gološeimme	V;COND;DU;1
šlubbut	šluppožetne	V;POT;DU;1
áktit	ávttii	V;IND;SG;3;PST
duorastat	duorastahkan	N;FRML;SG
čorget	čorgešeimmet	V;COND;PL;1
borran	borrama	N;GEN;SG
gossat	gossot	V;IMP;PL;1
doahput	dobošeigga	V;COND;DU;3
coakcut	covccošeigga	V;COND;DU;3
addjohit	addjohat	V;IND;SG;2;PRS
boršut	borššošeimmet	V;COND;PL;1
alvvaiduvvat	alvvaiduvvat	V;IND;PL;1;PRS
gossat	gosaleimme	V;COND;DU;1;LGSPEC1
guovlat	guovllašeimme	V;COND;DU;1
suvdit	suvdet	V;IND;SG;2;PST
vardit	varddežat	V;POT;SG;2
garcut	garcoska	V;IMP;DU;3
njuikut	njuikkošeigga	V;COND;DU;3
čatnat	čanažat	V;POT;SG;2
saddit	sattiide	V;IND;DU;2;PST
suddit	suttálii	V;COND;SG;3;LGSPEC1
gissat	gisašeigga	V;COND;DU;3
láhppit	láhpáleidde	V;COND;DU;2;LGSPEC1
deadjasilli	deadjasilliin	N;PRP;PL
čuodjat	čuojaleigga	V;COND;DU;3;LGSPEC1
fiskadas	fiskadasaiguin	N;COM;PL
šnjarvát	šnjarvájehkoset	V;IMP;PL;3
ádjit	ájáše	V;COND;PL;3
bieđgát	bieđgáimet	V;IND;PL;1;PST
márfut	márffožehpet	V;POT;PL;2
readnját	readnjájehkoska	V;IMP;DU;3
beassat	beasaše	V;COND;PL;3
kárta	kártan	N;FRML;SG
hávkat	hávkkalin	V;COND;SG;1;LGSPEC1
cahkat	cahket	V;IND;PL;3;PRS
smáhket	smáhkiime	V;IND;DU;1;PST
nuollat	nuolašit	V;COND;SG;2
suoibut	suibo	V;IND;PL;3;PST
laddat	lattašeigga	V;COND;DU;3
gohččut	gohččoset	V;IMP;PL;3
suoibut	suibbošeimmet	V;COND;PL;1
bargat	barggai	V;IND;SG;3;PST
sustit	sustá	V;IND;SG;3;PRS
skurbat	skurben	V;IND;SG;1;PST
nuondat	nuondda	V;IMP;SG;2
njurgut	njurggošeimmet	V;COND;PL;1
aresteret	arestereža	V;POT;SG;3
ruŋkit	ruŋkkežeahppi	V;POT;DU;2
ubmisámegiella	ubmisámegielas	N;PRP;SG
ássat	ásaše	V;COND;PL;3
atnu	anuin	N;COM;SG
cillat	cilaimet	V;IND;PL;1;PST
čoavdit	čovdon	V;IMP;SG;1
čavgadeamos	čavgadepmosiid	ADJ;ACC;PL
guostát	guostášin	V;COND;SG;1
oaddi	oaddin	ADJ;FRML;SG
sehkket	sehkkešeidde	V;COND;DU;2
gahččat	gahčaime	V;IND;DU;1;PST
borgemánnu	borgemánuiguin	N;COM;PL
giessat	giesaše	V;COND;PL;3
readnját	readnjájin	V;IND;SG;1;PST
nuorat	nuorabuid	ADJ;GEN;PL
áktit	ávttále	V;COND;PL;3;LGSPEC1
gissat	gisašeidde	V;COND;DU;2
muitalit	muitaleažžat	V;POT;PL;1
juhkaluvvat	juhkaluvažetne	V;POT;DU;1
suhkkát	suhkkába	V;IND;DU;3;PRS
gáhtat	gáđale	V;COND;PL;3;LGSPEC1
duostut	dustot	V;IND;SG;2;PST
vuohpput	vuhpoleiddet	V;COND;PL;2;LGSPEC1
guoggut	guggot	V;IND;SG;2;PST
cuvzat	cuvzzažehpet	V;POT;PL;2
rančát	rančájin	V;IND;SG;1;PST
anánas	anánasii	N;IN+ALL;SG
institušuvdna	institušuvnnain	N;COM;SG
čierrut	čirošeiddet	V;COND;PL;2
heaitit	heittežeaba	V;POT;DU;3
seaisat	seiset	V;IND;PL;3;PRS
soahki	sogiide	N;IN+ALL;PL
goallut	goal'lu	V;IMP;DU;2
caggat	cakkašii	V;COND;SG;3
sáibbo	sáippuiguin	N;COM;PL
njeazzát	njeazzášit	V;COND;SG;2
juolgat	julge	V;IND;DU;1;PRS
duostut	duostu	V;IND;SG;3;PRS
bávkit	bávkoska	V;IMP;DU;3
vašálaččat	vašálaččabu	ADJ;ACC;SG
sirgŋat	sirkŋaimet	V;IND;PL;1;PST
šlahttát	šlahttáleimme	V;COND;DU;1;LGSPEC1
vázzát	vázzába	V;IND;DU;3;PRS
duostat	duosttai	V;IND;SG;3;PST
doavttir	doaktáriid	N;ACC;PL
boaris	boarrásiid	ADJ;ACC;PL
muohttát	muohttát	V;IND;SG;2;PRS
biktit	bivttán	V;IND;SG;1;PRS
njaŋgát	njaŋgábehtet	V;IND;PL;2;PRS
gánda	gánddas	N;PRP;SG
sárrat	sárraba	V;IND;DU;3;PRS
vuoigŋat	vuoiŋŋažehpet	V;POT;PL;2
čoarrut	čoroleimmet	V;COND;PL;1;LGSPEC1
gahččat	gahčaleigga	V;COND;DU;3;LGSPEC1
dadjat	dajašeidde	V;COND;DU;2
buktit	buvttálii	V;COND;SG;3;LGSPEC1
gulcat	gulccažehpet	V;POT;PL;2
áibmat	áibmabeahtti	V;IND;DU;2;PRS
gurdit	gurdibehtet	V;IND;PL;2;PRS
áddet	áddeše	V;COND;PL;3
ilbmat	ilmman	V;IND;SG;1;PRS
haksit	hakse	V;IND;DU;1;PRS
sodnját	sodnjáimet	V;IND;PL;1;PST
bánžat	bánžašeimmet	V;COND;PL;1
lihtter	lihtterii	N;IN+ALL;SG
sodnját	sodnjájin	V;IND;SG;1;PST
bárra	bárat	N;NOM;PL
aresteret	aresteriidet	V;IND;PL;2;PST
riipu	riippuiguin	N;COM;PL
uhkidit	uhkidivččiimet	V;COND;PL;1
julevsámegiella	julevsámegielat	N;NOM;PL
njávgit	njávget	V;IND;PL;3;PRS
máistit	máisti	V;IMP;DU;2
jaskat	jaskadat	ADJ;NOM;PL
eadjit	edje	V;IND;DU;1;PRS
kárpa	kárppaiguin	N;COM;PL
suoskat	suoskkažetne	V;POT;DU;1
bossut	bos'su	V;IMP;DU;2
niitit	niittále	V;COND;PL;3;LGSPEC1
bassat	basašii	V;COND;SG;3
áfáiduvvat	áfáiduvaleiddet	V;COND;PL;2;LGSPEC1
nuollat	nuolažit	V;POT;PL;1
goddit	gottášeimme	V;COND;DU;1
aresteret	aresterežit	V;POT;PL;3
giemardit	giemardeažžaba	V;POT;DU;3
njurgut	njurgo	V;IND;PL;3;PST
uštit	ušttiide	V;IND;DU;2;PST
gurdit	gurddeža	V;POT;SG;3
goalvát	goalvájit	V;IND;SG;2;PST
vardit	varddii	V;IND;SG;3;PST
suoibut	suibboleimme	V;COND;DU;1;LGSPEC1
muollat	muolašeimme	V;COND;DU;1
sáddet	sáddet	V;IND;PL;1;PRS
boahttevuohta	boahttevuođaide	N;IN+ALL;PL
ruossut	rusošeigga	V;COND;DU;3
eaidat	eaiddai	V;IND;SG;3;PST
girdit	girdet	V;IND;PL;3;PRS
suoskat	susket	V;IMP;PL;2
čierastit	čierastežže	V;POT;DU;1
snuordát	snuordái	V;IND;SG;3;PST
heaitit	heaittáleiddet	V;COND;PL;2;LGSPEC1
árpa	árppaid	N;ACC;PL
čoarrát	čoar'ráide	V;IND;DU;2;PST
fáskat	fáskkaime	V;IND;DU;1;PST
ahkkái	ahkkás	ADJ;PRP;SG
issoras	issorasat	ADJ;NOM;PL
njealját	njealjádiidda	ADJ;IN+ALL;PL
sahát	sahájetne	V;IND;DU;1;PRS
molljut	moljun	V;IND;SG;1;PRS
giemardit	giemar	V;IMP;SG;2
duhtadit	duhtadan	V;IND;SG;1;PRS
cuvket	cuvkejeahkki	V;IMP;DU;2
artista	artisttaid	N;GEN;PL
seavdnjadeamos	seavdnjadepmosa	ADJ;GEN;SG
dápmat	dápmat	V;IND;PL;1;PRS
albmanit	albmanehkoset	V;IMP;PL;3
ođđajahki	ođđajagi	N;ACC;SG
duhtat	duđaiga	V;IND;DU;3;PST
áfáiduvvat	áfáiduvašeidde	V;COND;DU;2
láiki	láikkiin	ADJ;COM;SG
ráhput	rábole	V;COND;PL;3;LGSPEC1
šlahttát	šlahttáleigga	V;COND;DU;3;LGSPEC1
nuortalašgiella	nuortalašgiella	N;NOM;SG
njoarrat	njorret	V;IND;SG;2;PST
dadjat	dajažehpet	V;POT;PL;2
jumeš	jumežiid	N;GEN;PL
fáskat	fáskkašeigga	V;COND;DU;3
geassit	geasášii	V;COND;SG;3
arkiiva	arkiivvain	N;PRP;PL
báidnit	báidnit	V;IND;PL;1;PRS
bárdnat	bárdnaba	V;IND;DU;3;PRS
čovvát	čov'vášeiddet	V;COND;PL;2
diktit	divttáleidde	V;COND;DU;2;LGSPEC1
molljut	moljoleiddet	V;COND;PL;2;LGSPEC1
njartat	njartet	V;IMP;PL;2
coakcut	covccožehpet	V;POT;PL;2
basahit	basahan	V;IND;SG;1;PRS
loahppat	loahpaiga	V;IND;DU;3;PST
riehpat	rihpot	V;IMP;PL;1
dipmat	diman	V;IND;SG;1;PRS
dábba	dáppaiguin	N;COM;PL
čáskat	čáskkaiga	V;IND;DU;3;PST
soahpat	soabažeahppi	V;POT;DU;2
njárbut	njárbbožan	V;POT;SG;1
lohtat	lođaidet	V;IND;PL;2;PST
gulcat	gulccažetne	V;POT;DU;1
geargat	gearggaime	V;IND;DU;1;PST
čalmmehit	čalmmeheappot	ADJ;NOM;PL
beaivváš	beaivváš	N;NOM;SG
ruŋkit	ruŋket	V;IND;SG;2;PST
čiekŋalit	čiekŋaleappuin	ADJ;COM;SG
bistit	bisttát	V;IND;SG;2;PRS
boršut	boršon	V;IND;SG;1;PST
eastat	este	V;IND;PL;3;PST
bustávva	bustávaid	N;ACC;PL
njuoskat	njusket	V;IND;SG;2;PST
bagadit	bagadeiddet	V;IND;PL;2;PST
coakcut	covccolit	V;COND;SG;2;LGSPEC1
stoarbma	stoarpmain	N;COM;SG
aiddolaš	aiddolaččas	ADJ;PRP;SG
reŋgot	reŋgolit	V;COND;SG;2;LGSPEC1
oskut	oskko	V;IMP;SG;2
laskat	laskat	V;IND;PL;1;PRS
suoibut	suibos	V;IMP;SG;3
oastit	osten	V;IND;SG;1;PST
geavvat	geavalit	V;COND;SG;2;LGSPEC1
gosahit	gosat	V;IMP;SG;2
laskat	laskkalin	V;COND;SG;1;LGSPEC1
čahrrat	čahrrabehtet	V;IND;PL;2;PRS
kárpa	kárppa	N;ACC;SG
hearvát	hearvájehkon	V;IMP;SG;1
bistit	bistu	V;IMP;DU;1
ábbut	ábbubehtet	V;IND;PL;2;PRS
njukčamánnu	njukčamánnun	N;FRML;SG
vardit	varddálin	V;COND;SG;1;LGSPEC1
njávgut	njávggolin	V;COND;SG;1;LGSPEC1
stumpát	stumpážit	V;POT;PL;1
eadjit	edjoteaddjut	V;IMP;PL;1
dássit	dássidin	ADJ;FRML;SG
basastit	basastehket	V;IMP;PL;2
máššat	máššaba	V;IND;DU;3;PRS
diktit	divttežan	V;POT;SG;1
arkeologa	arkeologain	N;PRP;PL
gievra	gievra	ADJ;NOM;SG
vealčut	velčo	V;IND;DU;1;PRS
sustit	sustet	V;IND;SG;2;PST
huhpat	hubaimet	V;IND;PL;1;PST
boaski	boaski	N;NOM;SG
máššat	mášaidet	V;IND;PL;2;PST
šleambit	šleambbe	V;IMP;SG;2
addilit	addilehkoset	V;IMP;PL;3
geallat	gealašii	V;COND;SG;3
buoibmat	buoimmašeimme	V;COND;DU;1
gildát	gildážeahppi	V;POT;DU;2
almmálaš	almmálažžan	ADJ;FRML;SG
šuohkkit	šuohkášeigga	V;COND;DU;3
ákšu	ákšuiguin	N;COM;PL
čorru	čorut	N;NOM;PL
goikat	goiket	V;IND;PL;3;PRS
readnját	readnjájetnot	V;IMP;PL;1
dadjat	dadjat	V;IND;PL;1;PRS
losit	losibuid	ADJ;GEN;PL
albmanit	albmanivččiide	V;COND;DU;2
árgi	árggiid	ADJ;ACC;PL
čoarrát	čoar'rášeimme	V;COND;DU;1
vuoksit	vukse	V;IND;DU;1;PRS
čuoldit	čuldet	V;IMP;PL;2
salgat	salge	V;IND;PL;3;PST
čuolbmat	čuolmmaiga	V;IND;DU;3;PST
veahkki	vehkiiguin	N;COM;PL
bealjehit	bealjeheappo	ADJ;GEN;SG
liekčát	liekčážetne	V;POT;DU;1
boaski	boaskái	N;IN+ALL;SG
njuikut	njuikkui	V;IND;SG;3;PST
fanas	fatnasis	N;PRP;SG
kárta	kárttain	N;COM;SG
bávkit	bávkkálit	V;COND;SG;2;LGSPEC1
cáhpat	cábaleimme	V;COND;DU;1;LGSPEC1
áibmat	áibmet	V;IMP;PL;2
gálgat	gálggale	V;COND;PL;3;LGSPEC1
heaitit	heaittáleimmet	V;COND;PL;1;LGSPEC1
vákšát	vákšáide	V;IND;DU;2;PST
sárrat	sárat	V;IND;SG;2;PRS
oastit	osttiide	V;IND;DU;2;PST
lávlageaskka	lávlagasaska	N;IN+ALL;SG
stumpát	stumpášeigga	V;COND;DU;3
gokčat	gokčoset	V;IMP;PL;3
buvtta	buktagiidda	N;IN+ALL;PL
bollát	bol'lájetnot	V;IMP;PL;1
snuordát	snuordálii	V;COND;SG;3;LGSPEC1
šiggut	šikkožetne	V;POT;DU;1
cáhkit	cáhkoska	V;IMP;DU;3
vuollat	vuolažan	V;POT;SG;1
smáhket	smáhkiide	V;IND;DU;2;PST
sodnját	sodnjále	V;COND;PL;3;LGSPEC1
sahá	sahá	N;ACC;SG
šiitit	šiittášit	V;COND;SG;2
nakšát	nakšášii	V;COND;SG;3
áksil	áksiliid	N;GEN;PL
juksat	juvssažit	V;POT;PL;1
lihppu	lihppun	N;FRML;SG
njoarostit	njoarostehkon	V;IMP;SG;1
borrat	borret	V;IND;PL;3;PRS
rivgu	rivguide	N;IN+ALL;PL
deaivat	deaivvašeidde	V;COND;DU;2
bilidit	bilideigga	V;IND;DU;3;PST
bávkit	bávkkášeimmet	V;COND;PL;1
baste	basttiiguin	N;COM;PL
buorránit	buorránivččiime	V;COND;DU;1
čábbut	čábbut	V;IND;PL;1;PRS
snuhrrat	snuhrret	V;IND;SG;2;PST
njálla	njálla	N;NOM;SG
boahttevuohta	boahttevuođaid	N;ACC;PL
eadjit	eajášeimme	V;COND;DU;1
duđahit	duđahii	V;IND;SG;3;PST
láikkit	láikkibuin	ADJ;PRP;PL
láibi	láibbiin	N;PRP;PL
jearahit	jearahehpet	V;IND;PL;2;PRS
njaŋgát	njaŋgášit	V;COND;SG;2
komišuvdna	komišuvnnaid	N;GEN;PL
biise	biissiin	N;PRP;PL
leabbut	leppoleidde	V;COND;DU;2;LGSPEC1
rančát	rančájetnot	V;IMP;PL;1
ciellat	cielale	V;COND;PL;3;LGSPEC1
hilgut	hilggui	V;IND;SG;3;PST
litnjat	linjaleigga	V;COND;DU;3;LGSPEC1
sehkket	sehkkiiga	V;IND;DU;3;PST
viežžat	vižžet	V;IMP;PL;2
lihkkat	lihkat	V;IND;SG;2;PRS
eadnádet	eadnineattet	N;FRML;SG
beallji	bealjis	N;PRP;SG
njálla	njálat	N;NOM;PL
čávdit	čávddálii	V;COND;SG;3;LGSPEC1
addálasat	addálasabuidda	ADJ;IN+ALL;PL
rihpat	ribažehpet	V;POT;PL;2
doarrát	doar'ráleidde	V;COND;DU;2;LGSPEC1
sieđgacivkkán	sieđgacivkkániiguin	N;COM;PL
almmostahttit	almmostahtte	V;IND;PL;3;PST
gálgat	gálgoska	V;IMP;DU;3
ciellat	ciel'lu	V;IMP;DU;1
gallet	gallejit	V;IND;SG;2;PST
almmostahttit	almmostahtálit	V;COND;SG;2;LGSPEC1
čuodjat	čuojan	V;IND;SG;1;PRS
bassat	basalii	V;COND;SG;3;LGSPEC1
šleađga	šleađggain	N;PRP;PL
ruoksát	ruoksálit	V;COND;SG;2;LGSPEC1
guoktelogiguđat	guoktelogiguđada	ADJ;ACC;SG
šiegat	šiegabut	ADJ;NOM;PL
miessemánnu	miessemánuin	N;COM;SG
caggat	caggabeahtti	V;IND;DU;2;PRS
albmáimannan	albmáimannamiid	N;ACC;PL
borrat	boražeaba	V;POT;DU;3
cáhpat	cábašeigga	V;COND;DU;3
logát	logádiin	ADJ;PRP;PL
borgárvuohta	borgárvuohta	N;NOM;SG
suostat	suosttaleigga	V;COND;DU;3;LGSPEC1
cuvket	cuvkešeigga	V;COND;DU;3
vuovdit	vuvdon	V;IMP;SG;1
biktit	bivttiiga	V;IND;DU;3;PST
doahput	doahpuba	V;IND;DU;3;PRS
áldu	áldu	N;NOM;SG
čuoldit	čulddeža	V;POT;SG;3
beassat	beasa	V;IMP;SG;2
árpa	árppaiguin	N;COM;PL
akustihkalaš	akustihkalaččaide	ADJ;IN+ALL;PL
njaŋgát	njaŋgájehkos	V;IMP;SG;3
láigohit	láigohit	V;IND;SG;2;PST
akademihkar	akademihkkarat	N;NOM;PL
áldu	álddu	N;ACC;SG
gussa	gusa	N;GEN;SG
ruoidnát	ruoidnášit	V;COND;SG;2
guorbát	guorbát	V;IND;SG;2;PRS
luoikat	luoikkašeimmet	V;COND;PL;1
diktit	divttáleimme	V;COND;DU;1;LGSPEC1
divraseamos	divrasepmosiin	ADJ;PRP;PL
liekčát	liekčájehkoset	V;IMP;PL;3
hávkka	hávkagiid	N;GEN;PL
hávkat	hávkkašeimme	V;COND;DU;1
diktit	diktot	V;IMP;PL;1
sárggis	sárgás	N;PRP;SG
čavgat	čavgadin	ADJ;FRML;SG
laddat	lattažat	V;POT;SG;2
buohcci	buohcci	N;GEN;SG
ruoidnat	ruidnet	V;IND;SG;2;PST
gullat	gulažit	V;POT;PL;1
massit	massáše	V;COND;PL;3
čuolda	čuolddaiguin	N;COM;PL
oaidnit	oaidni	V;IMP;DU;2
cahkat	cagašeiddet	V;COND;PL;2
bávkit	bávket	V;IND;PL;3;PRS
muŋkát	muŋkáleimmet	V;COND;PL;1;LGSPEC1
geavrát	geavrášeiddet	V;COND;PL;2
luoikat	luoikkaiga	V;IND;DU;3;PST
fuoikit	fuiket	V;IND;SG;2;PST
bákŋat	bákŋot	V;IMP;PL;1
albmanit	albmanin	V;IND;SG;1;PST
siigat	siiggaše	V;COND;PL;3
loktit	loktá	V;IND;SG;3;PRS
áibat	áiben	V;IND;SG;1;PST
nohkan	nohkamis	N;PRP;SG
šleambit	šleambbále	V;COND;PL;3;LGSPEC1
bolsttar	bolstariin	N;PRP;PL
allaskuvla	allaskuvllaiguin	N;COM;PL
caggat	cakkaža	V;POT;SG;3
čeahppi	čeahpit	ADJ;NOM;PL
guoktelogivuosttaš	guoktelogivuosttaža	ADJ;GEN;SG
bánžat	bánžaleimmet	V;COND;PL;1;LGSPEC1
čuodjat	čuojašeimme	V;COND;DU;1
vákšát	vákšájedje	V;IND;PL;3;PST
oažžut	ožžon	V;IND;SG;1;PST
adresseret	adresserežeaba	V;POT;DU;3
viežžat	viežžabeahtti	V;IND;DU;2;PRS
vuorkut	vurkon	V;IMP;SG;1
addilit	addilivččiidet	V;COND;PL;2
geahkat	geagažit	V;POT;PL;3
eadjit	edjos	V;IMP;SG;3
juolgat	julget	V;IND;SG;2;PST
astronomiija	astronomiijain	N;PRP;PL
bánžat	bánžažat	V;POT;SG;2
massit	mas'sen	V;IND;SG;1;PST
duoldat	duolddašeimmet	V;COND;PL;1
positiiva	positiivvat	ADJ;NOM;PL
basahit	basahivččiide	V;COND;DU;2
seastit	sesttežat	V;POT;SG;2
spildi	spilddiin	N;PRP;PL
buorránit	buorráneimmet	V;IND;PL;1;PST
náitit	náittiide	V;IND;DU;2;PST
dihkkat	dihkaleigga	V;COND;DU;3;LGSPEC1
áibat	áibet	V;IMP;PL;2
guvrát	guvrábehtet	V;IND;PL;2;PRS
čeallut	čeloleidde	V;COND;DU;2;LGSPEC1
geassit	geasáleimmet	V;COND;PL;1;LGSPEC1
čuorvut	čuorvubehtet	V;IND;PL;2;PRS
doaibat	doaibbaleidde	V;COND;DU;2;LGSPEC1
adresseret	adresseren	V;IND;SG;1;PRS
gáhtat	gáđalii	V;COND;SG;3;LGSPEC1
giehka	giegain	N;COM;SG
reavrut	revros	V;IMP;SG;3
loktit	loktibehtet	V;IND;PL;2;PRS
guoirat	guoirat	V;IND;PL;1;PRS
náitit	náittiimet	V;IND;PL;1;PST
gažahit	gažaheažžat	V;POT;PL;1
dábba	dáppas	N;PRP;SG
reahccut	rehcoleigga	V;COND;DU;3;LGSPEC1
goddit	gottášeigga	V;COND;DU;3
duostat	duosttaiga	V;IND;DU;3;PST
guolbmat	guolmmaše	V;COND;PL;3
cábmit	cápmežehpet	V;POT;PL;2
luoitit	luoitiba	V;IND;DU;3;PRS
báŋka	báŋkkain	N;COM;SG
viibat	viibbaleimmet	V;COND;PL;1;LGSPEC1
sahčat	sažašii	V;COND;SG;3
gastit	gasttálit	V;COND;SG;2;LGSPEC1
addilit	addileažžabehtet	V;POT;PL;2
smiehttat	smiehtaleiddet	V;COND;PL;2;LGSPEC1
huhpat	hubaidet	V;IND;PL;2;PST
ceggoseamos	ceggosepmosii	ADJ;IN+ALL;SG
fállat	fálalii	V;COND;SG;3;LGSPEC1
borrat	boražeahppi	V;POT;DU;2
oktanuppelogát	oktanuppelogáda	ADJ;GEN;SG
bárra	báraide	N;IN+ALL;PL
oaidnit	oainnáleigga	V;COND;DU;3;LGSPEC1
biise	biisset	N;NOM;PL
smiehttat	smiehtažan	V;POT;SG;1
ráhput	ráboleiddet	V;COND;PL;2;LGSPEC1
vuohčut	vužuimet	V;IND;PL;1;PST
čivga	čivggain	N;PRP;PL
siigat	siigoset	V;IMP;PL;3
čeallulit	čeallulat	V;IND;SG;2;PRS
šieđđat	šiđđe	V;IND;DU;1;PRS
juorbut	jurbboleigga	V;COND;DU;3;LGSPEC1
gáddit	gáttežehpet	V;POT;PL;2
deaffat	deaffaba	V;IND;DU;3;PRS
gokčat	govččažeahppi	V;POT;DU;2
albmanit	albmanivččiiga	V;COND;DU;3
goikáseamos	goikásepmosis	ADJ;PRP;SG
boazu	bohccuiguin	N;COM;PL
áibat	áibet	V;IND;PL;3;PRS
geavrát	geavráleiddet	V;COND;PL;2;LGSPEC1
siigat	siiggažeahppi	V;POT;DU;2
beavdi	beavdin	N;FRML;SG
oahppat	oahpat	V;IND;SG;2;PRS
buoidda	buoidagiiguin	N;COM;PL
čákŋat	čákŋoska	V;IMP;DU;3
bealuštit	bealušteidde	V;IND;DU;2;PST
buvtta	buktagiid	N;GEN;PL
bomba	bombba	N;ACC;SG
vuollat	vuolaleiddet	V;COND;PL;2;LGSPEC1
máltit	málttežehpet	V;POT;PL;2
suomastit	suomastivččen	V;COND;SG;1
reavrát	reavrášeimmet	V;COND;PL;1
fanas	fatnasiid	N;GEN;PL
álgit	álgos	V;IMP;SG;3
lihkkat	lihkaidet	V;IND;PL;2;PST
speallat	spellen	V;IND;SG;1;PST
gallet	gallii	V;IND;SG;3;PST
litnjat	linjašit	V;COND;SG;2
gaikut	gaikkožetne	V;POT;DU;1
áibmat	áimmažehpet	V;POT;PL;2
čeavlámus	čeavlámusa	ADJ;ACC;SG
dovdat	dovddaleigga	V;COND;DU;3;LGSPEC1
doarrát	doar'ráleiddet	V;COND;PL;2;LGSPEC1
sirdát	sirdába	V;IND;DU;3;PRS
goahcat	goahcci	V;IMP;DU;2
dipmat	dipmon	V;IMP;SG;1
hearvát	hearvájehkoset	V;IMP;PL;3
bárdnat	bártnat	V;IND;SG;2;PRS
riipu	riipput	N;NOM;PL
čeabet	čeabehiid	N;GEN;PL
laddat	laddabeahtti	V;IND;DU;2;PRS
sahát	sahái	V;IND;SG;3;PST
čierastit	čierasteš	V;POT;SG;3
sahčat	sažaidet	V;IND;PL;2;PST
vuohppa	vuohpas	N;PRP;SG
šlubbut	šlubbubeahtti	V;IND;DU;2;PRS
nordat	norddalin	V;COND;SG;1;LGSPEC1
skurbat	skurbbažehpet	V;POT;PL;2
vuohčit	vužežit	V;POT;PL;3
advearba	advearba	N;NOM;SG
geallat	gelle	V;IND;DU;1;PRS
stivát	stiváleimmet	V;COND;PL;1;LGSPEC1
fearrat	fearaime	V;IND;DU;1;PST
speallat	spealaše	V;COND;PL;3
cissat	cissašin	V;COND;SG;1
speallat	spealažeaba	V;POT;DU;3
viežžat	vieččaleiddet	V;COND;PL;2;LGSPEC1
duoldat	duolddašin	V;COND;SG;1
čeallut	čeluidet	V;IND;PL;2;PST
vuoksit	vuvssežat	V;POT;SG;2
gámme	gámmiin	N;PRP;PL
jápmit	jámášeidde	V;COND;DU;2
bávkit	bávkit	V;IND;PL;1;PRS
áddet	áddeža	V;POT;SG;3
čeavži	čevžžiin	N;COM;SG
speallat	spealažit	V;POT;PL;3
guostát	guostájit	V;IND;PL;3;PRS
