gákkis	gákkisin	N;FRML;SG
darjjesámegiella	darjjesámegillii	N;IN+ALL;SG
čopma	čoma	N;ACC;SG
suossat	suosažat	V;POT;SG;2
gaŋgát	gaŋgát	V;IND;PL;1;PRS
orrut	orrot	V;IMP;PL;2
boagustit	boagustivččet	V;COND;SG;2
guokteloginubbi	guokteloginuppiiguin	ADJ;COM;PL
lutnjat	ludnju	V;IMP;DU;1
dolkat	dolke	V;IND;DU;1;PRS
láhčit	lážášeigga	V;COND;DU;3
njárbut	njárbboleigga	V;COND;DU;3;LGSPEC1
ođđajagimánnu	ođđajagimánnu	N;NOM;SG
roandit	roanddálin	V;COND;SG;1;LGSPEC1
soahki	soagi	N;GEN;SG
biehkan	biehkan	N;NOM;SG
cohkkát	cohkkážat	V;POT;SG;2
luoikat	luoikkalit	V;COND;SG;2;LGSPEC1
cirgut	cirgon	V;IND;SG;1;PST
ipmirdit	ipmirdin	V;IND;SG;1;PST
čáppat	čábbá	ADJ;GEN;SG
boalbut	bolbot	V;IND;PL;3;PRS
čiehppat	čiehpat	V;IND;SG;2;PRS
allodat	allodaga	N;ACC;SG
sáivi	sáivvis	N;PRP;SG
buđet	buđehii	N;IN+ALL;SG
suollit	suliiga	V;IND;DU;3;PST
cissat	cissaleigga	V;COND;DU;3;LGSPEC1
njoallut	njololii	V;COND;SG;3;LGSPEC1
stirrát	stir'rábehtet	V;IND;PL;2;PRS
geahčastat	geahčastagaid	N;GEN;PL
njeađgat	njeađgi	V;IMP;DU;2
čižži	čižžái	N;IN+ALL;SG
agáiduvvat	agáiduvan	V;IND;SG;1;PRS
dehálit	dehálit	ADJ;NOM;SG
gállit	gálloska	V;IMP;DU;3
jakŋat	jaŋai	V;IND;SG;3;PST
gáhkkor	gáhkkoriid	N;GEN;PL
vardát	vardájeadnu	V;IMP;DU;1
boagustit	boagustežže	V;POT;DU;1
ábbut	áppo	V;IMP;SG;2
váibmu	váibmui	N;IN+ALL;SG
ásahit	ásahehkos	V;IMP;SG;3
rihccut	rihccot	V;IMP;PL;2
cukcat	cuvccan	V;IND;SG;1;PRS
gaŋkát	gaŋkájehkoska	V;IMP;DU;3
litnjat	linjažeahppi	V;POT;DU;2
coggat	cokkažan	V;POT;SG;1
čolgat	čolggažeaba	V;POT;DU;3
njáškát	njáškábehtet	V;IND;PL;2;PRS
ruoktu	ruovttuide	N;IN+ALL;PL
duoggut	dukkošin	V;COND;SG;1
guoskat	guoskkale	V;COND;PL;3;LGSPEC1
hoigat	hoiggaleimme	V;COND;DU;1;LGSPEC1
áidut	áiddolit	V;COND;SG;2;LGSPEC1
nállat	nálaimet	V;IND;PL;1;PST
biegga	biekka	N;ACC;SG
antihkka	antihkkan	N;FRML;SG
baldalit	baldalivččiiga	V;COND;DU;3
ovttasbargat	ovttasbarggat	V;IND;SG;2;PRS
buorránit	buorráneahppi	V;IND;DU;2;PRS
golgadit	golgadeažžabehtet	V;POT;PL;2
amiidit	amiidivččiime	V;COND;DU;1
gávrut	gávrrožetne	V;POT;DU;1
doaibmat	doaimma	V;IMP;SG;2
juoiggus	juigosiid	N;ACC;PL
geavvat	gevve	V;IND;PL;3;PST
reavrut	revrrolit	V;COND;SG;2;LGSPEC1
stoavkit	stoavkke	V;IMP;SG;2
bámbu	bámbbuin	N;COM;SG
jahtat	jađašeigga	V;COND;DU;3
duoggut	duokko	V;IMP;SG;2
šibitdoavttir	šibitdoaktárat	N;NOM;PL
faggut	faggot	V;IMP;PL;1
heaibat	heibos	V;IMP;SG;3
skurbat	skurbbaše	V;COND;PL;3
gávccinuppelogát	gávccinuppelogáda	ADJ;ACC;SG
deaivat	deaivvašeidde	V;COND;DU;2
arvát	arválit	V;COND;SG;2;LGSPEC1
sahát	sahálii	V;COND;SG;3;LGSPEC1
buohcceviessu	buohcceviesuin	N;PRP;PL
bindut	binddoleidde	V;COND;DU;2;LGSPEC1
bodnját	bodnjáidet	V;IND;PL;2;PST
báffat	báfa	V;IMP;SG;2
goalvát	goalváide	V;IND;DU;2;PST
čuolbmat	čuolbmá	V;IND;SG;3;PRS
vákšut	vákšos	V;IMP;SG;3
jurbmát	jurbmáleiddet	V;COND;PL;2;LGSPEC1
reavrut	revrroža	V;POT;SG;3
njáškát	njáškájehket	V;IMP;PL;2
vurket	vurkelit	V;COND;SG;2;LGSPEC1
govlut	govloska	V;IMP;DU;3
caggat	cakkaiga	V;IND;DU;3;PST
laggat	lakkat	V;IND;SG;2;PRS
viggat	viggoset	V;IMP;PL;3
deaffat	deafa	V;IMP;SG;2
bearrat	bear'ri	V;IMP;DU;2
bátni	bániiguin	N;COM;PL
čávdit	čávddiimet	V;IND;PL;1;PST
guhkkat	guhkaleimme	V;COND;DU;1;LGSPEC1
áigut	áiggožeaba	V;POT;DU;3
vurket	vurkejeahkki	V;IMP;DU;2
roandit	roanddáleigga	V;COND;DU;3;LGSPEC1
buktit	buktet	V;IND;SG;2;PST
bánžat	bánžet	V;IND;PL;3;PRS
golgadit	golgadetne	V;IND;DU;1;PRS
cuvkit	cuvkkán	V;IND;SG;1;PRS
ádjit	áje	V;IMP;SG;2
fearrat	fearašin	V;COND;SG;1
eadniset	etniideasetguin	N;COM;PL
duhtat	duđašii	V;COND;SG;3
čuolbmat	čulbmen	V;IND;SG;1;PST
sihtat	siđašeimmet	V;COND;PL;1
šlubbut	šluppo	V;IMP;SG;2
maŋit	maŋibuid	ADJ;GEN;PL
márfut	márffošeidde	V;COND;DU;2
diŋgot	diŋgošeiddet	V;COND;PL;2
vuoksit	vuvssežit	V;POT;PL;3
ilbmat	ilmmašeimme	V;COND;DU;1
suollit	sulle	V;IND;DU;1;PRS
vuodjit	vuodjibeahtti	V;IND;DU;2;PRS
sieđgacivkkán	sieđgacivkkániin	N;COM;SG
alvvaiduvvat	alvvaiduvaleiddet	V;COND;PL;2;LGSPEC1
vákšut	vávššožat	V;POT;SG;2
bávkit	bávkkežeaba	V;POT;DU;3
ábbut	ábboska	V;IMP;DU;3
heavdni	heavdni	N;NOM;SG
šuohkkit	šuohkán	V;IND;SG;1;PRS
juokŋat	jukŋoset	V;IMP;PL;3
párka	párkkas	N;PRP;SG
govlut	govllun	V;IND;SG;1;PRS
geaidit	geaidibeahtti	V;IND;DU;2;PRS
luoikat	luoikat	V;IND;PL;1;PRS
bilkidit	bilkideaba	V;IND;DU;3;PRS
suddat	suttaime	V;IND;DU;1;PST
asbeasta	asbeasttain	N;COM;SG
skeaikit	skeaikkán	V;IND;SG;1;PRS
borgat	borgi	V;IMP;DU;2
rádjat	rádjaba	V;IND;DU;3;PRS
skurbat	skurbaba	V;IND;DU;3;PRS
eastat	estoteastut	V;IMP;PL;1
dearvašit	dearvašeappos	ADJ;PRP;SG
skuhčat	skužaleimme	V;COND;DU;1;LGSPEC1
gaskat	gasku	V;IMP;DU;1
čoarrut	čoar'ru	V;IMP;DU;1
vuoigit	vuiggiidet	V;IND;PL;2;PST
deavdit	deavdá	V;IND;SG;3;PRS
boaibmut	boimmuime	V;IND;DU;1;PST
bileahtta	bileahta	N;GEN;SG
bieggat	biekkašeigga	V;COND;DU;3
suovva	suovaid	N;GEN;PL
riibat	riibbašeigga	V;COND;DU;3
reakcut	revccole	V;COND;PL;3;LGSPEC1
šleambut	šlembbožat	V;POT;SG;2
boaggut	bokkole	V;COND;PL;3;LGSPEC1
nohkkat	nohkaide	V;IND;DU;2;PST
joksat	jovssalit	V;COND;SG;2;LGSPEC1
alvvaiduvvat	alvvaiduvaiga	V;IND;DU;3;PST
argumeanta	argumeanta	N;NOM;SG
gávccát	gávccádis	ADJ;PRP;SG
alvvaiduvvat	alvvaiduvašeiddet	V;COND;PL;2
čohkka	čohkaiguin	N;COM;PL
gáskit	gáskkežehpet	V;POT;PL;2
ábbut	áppožit	V;POT;PL;3
sáhttit	sáhttoska	V;IMP;DU;3
áidut	áiddoleimme	V;COND;DU;1;LGSPEC1
geallit	gealášit	V;COND;SG;2
boalbut	bolbbošeimmet	V;COND;PL;1
bihppor	bihpporis	N;PRP;SG
jalŋŋis	jalgŋáiguin	N;COM;PL
čuoskut	čuskkožetne	V;POT;DU;1
állát	ál'lálin	V;COND;SG;1;LGSPEC1
goaivut	goivvolin	V;COND;SG;1;LGSPEC1
mánnu	mánu	N;GEN;SG
oidit	oiddiiga	V;IND;DU;3;PST
baldit	balden	V;IND;SG;1;PST
náššat	nášašeidde	V;COND;DU;2
bálgán	bálgáinan	N;PRP;PL
ruohtas	ruohttasa	N;ACC;SG
geahččalit	geahččalehkos	V;IMP;SG;3
šluŋkát	šluŋká	V;IMP;SG;2
bállit	bálášii	V;COND;SG;3
njáškát	njáškále	V;COND;PL;3;LGSPEC1
haŋkit	haŋki	V;IMP;DU;2
čoaskkis	čoaská	ADJ;GEN;SG
suorbma	suorpmas	N;PRP;SG
loaidat	loidot	V;IMP;PL;1
biibbal	biibalis	N;PRP;SG
rančát	rančáše	V;COND;PL;3
golgadit	golgadeažžabeahtti	V;POT;DU;2
deavdit	deavddášii	V;COND;SG;3
njuikut	njuikkun	V;IND;SG;1;PRS
eadjit	eajášit	V;COND;SG;2
bálgán	bálgán	N;ACC;SG
vardát	vardájehkos	V;IMP;SG;3
háŋgut	háŋgon	V;IMP;SG;1
loaktit	loavttáleigga	V;COND;DU;3;LGSPEC1
govlut	govlut	V;IND;PL;1;PRS
háistit	háisttáše	V;COND;PL;3
gávrut	gávrroše	V;COND;PL;3
ciellat	cielan	V;IND;SG;1;PRS
addáleamos	addálepmosa	ADJ;ACC;SG
máhccut	máhccut	V;IND;PL;1;PRS
skurbat	skurbbažeahppi	V;POT;DU;2
háŋgut	háŋgu	V;IMP;DU;2
čihččet	čihččediid	ADJ;GEN;PL
skillat	skilalin	V;COND;SG;1;LGSPEC1
oađđit	ođđon	V;IMP;SG;1
biktit	biktoset	V;IMP;PL;3
vuosehit	vuosehežže	V;POT;DU;1
addáleamos	addálepmosiid	ADJ;ACC;PL
rihccut	rihccot	V;IND;SG;2;PST
šearrát	šear'ráleidde	V;COND;DU;2;LGSPEC1
stoavkit	stovkon	V;IMP;SG;1
šiggut	šiggos	V;IMP;SG;3
čaibmat	čaimmaleimmet	V;COND;PL;1;LGSPEC1
čierrut	čirolin	V;COND;SG;1;LGSPEC1
nihttit	nihtežit	V;POT;PL;1
laggat	lakkan	V;IND;SG;1;PRS
amiidit	amiideaččat	V;POT;SG;2
joksat	jovssažit	V;POT;PL;3
snuhrrat	snuhražehpet	V;POT;PL;2
muŋkát	muŋkášeimme	V;COND;DU;1
čuollát	čuol'láidet	V;IND;PL;2;PST
ráhkistit	ráhkisteažžabehtet	V;POT;PL;2
rátkit	rátkkežeahppi	V;POT;DU;2
dávžat	dávže	V;IND;PL;3;PST
suvrris	suvrásiin	ADJ;PRP;PL
šealgut	šealgu	V;IMP;DU;2
cohkkát	cohkkáiga	V;IND;DU;3;PST
šiehttat	šihtte	V;IND;DU;1;PRS
eadnát	eatnát	N;ACC;SG
hupmat	humašeigga	V;COND;DU;3
áitit	áite	V;IND;PL;3;PST
ipmirdit	ipmirdivččiidet	V;COND;PL;2
dolastit	dolastežžet	V;POT;PL;3
gavja	gavjjain	N;COM;SG
dárbu	dárbbuid	N;ACC;PL
ráhput	ráboleigga	V;COND;DU;3;LGSPEC1
suollit	sulii	V;IND;SG;3;PST
jarfát	jarfálit	V;COND;SG;2;LGSPEC1
dávdi	dávddiin	N;PRP;PL
bivdit	bivddežan	V;POT;SG;1
gaskat	gaskkažit	V;POT;PL;3
lutnjat	lunjat	V;IND;SG;2;PRS
áldu	áldduiguin	N;COM;PL
botnit	bonášin	V;COND;SG;1
johttát	johttái	V;IND;SG;3;PST
doarrát	doar'rážeahppi	V;POT;DU;2
šiggut	šikkošii	V;COND;SG;3
šiitit	šiitet	V;IND;SG;2;PST
snuhrrat	snuhrre	V;IND;PL;3;PST
vávvát	váv'váiga	V;IND;DU;3;PST
seaisat	seiset	V;IMP;PL;2
dološ	doložii	ADJ;IN+ALL;SG
guovgát	guovgálit	V;COND;SG;2;LGSPEC1
heaibat	heaibabehtet	V;IND;PL;2;PRS
goalvát	goalvájin	V;IND;SG;1;PST
hoallat	hoalaimet	V;IND;PL;1;PST
čeahpit	čeahpibuin	ADJ;COM;SG
cáhkkat	cáhkket	V;IMP;PL;2
vuolla	vuolaide	N;IN+ALL;PL
mođđat	mođaža	V;POT;SG;3
joksat	joksu	V;IMP;DU;1
guorsat	guorssalin	V;COND;SG;1;LGSPEC1
vuohppát	vuohppálii	V;COND;SG;3;LGSPEC1
suoládit	suoládeidde	V;IND;DU;2;PST
skurbat	skurbbašeigga	V;COND;DU;3
aliheamos	alihepmosa	ADJ;GEN;SG
átnut	ánošin	V;COND;SG;1
deabbut	debbot	V;IMP;PL;1
čuovvut	čuvožan	V;POT;SG;1
reavrut	revrroleiddet	V;COND;PL;2;LGSPEC1
uhcimus	uhcimusa	ADJ;ACC;SG
náitit	náitoska	V;IMP;DU;3
orrut	orole	V;COND;PL;3;LGSPEC1
guovgát	guovgášeidde	V;COND;DU;2
váibat	váibon	V;IMP;SG;1
rámbut	rámbbošin	V;COND;SG;1
giitit	giittežeaba	V;POT;DU;3
nargit	narget	V;IND;SG;2;PST
čuopmat	čupmen	V;IND;SG;1;PST
jorgut	jorgguiga	V;IND;DU;3;PST
gohccát	gohccážeahppi	V;POT;DU;2
jápmit	jámále	V;COND;PL;3;LGSPEC1
skuhčat	skužašeigga	V;COND;DU;3
báŋka	báŋkka	N;GEN;SG
njoazit	njoazibuin	ADJ;COM;SG
goikat	goikkaime	V;IND;DU;1;PST
addjot	addjošeimmet	V;COND;PL;1
eadnán	etniinan	N;PRP;PL
soallut	sololeidde	V;COND;DU;2;LGSPEC1
čalbmi	čalmmiid	N;GEN;PL
bindut	bindon	V;IND;SG;1;PST
mearka	merkii	N;IN+ALL;SG
arvit	arvvii	V;IND;SG;3;PST
duohččat	duhččen	V;IND;SG;1;PST
almmálaš	almmálaččaide	ADJ;IN+ALL;PL
fuoikit	fuikkežetne	V;POT;DU;1
lávži	lávžžit	N;NOM;PL
vuotna	vuonaid	N;GEN;PL
háŋgut	háŋgo	V;IND;DU;1;PRS
olmmoš	olbmuin	N;COM;SG
gatna	gatnii	N;IN+ALL;SG
beassat	besset	V;IMP;PL;2
nuoramus	nuoramusa	ADJ;GEN;SG
suomastit	suomastežžet	V;POT;PL;3
bircut	birccoleimme	V;COND;DU;1;LGSPEC1
guolástit	guolástehkot	V;IMP;PL;1
rássi	rássái	N;IN+ALL;SG
argumeanta	argumeantan	N;FRML;SG
máilbmi	máilmmit	N;NOM;PL
báffat	báffoset	V;IMP;PL;3
faggut	fagguba	V;IND;DU;3;PRS
deapmat	deabmu	V;IMP;DU;1
gissat	gisažat	V;POT;SG;2
coggat	cokkašeigga	V;COND;DU;3
jarfát	jarfášeigga	V;COND;DU;3
biestit	bisttežeaba	V;POT;DU;3
bruvsa	bruvssa	N;ACC;SG
bahámus	bahámusas	ADJ;PRP;SG
njalla	njalaid	N;ACC;PL
iskat	iskkai	V;IND;SG;3;PST
bollát	bol'lába	V;IND;DU;3;PRS
ullu	ulluide	N;IN+ALL;PL
gaŋkát	gaŋká	V;IMP;SG;2
buddet	buddejin	V;IND;SG;1;PST
boltut	bolttoleidde	V;COND;DU;2;LGSPEC1
guovgát	guovgážit	V;POT;PL;1
árrit	árros	V;IMP;SG;3
lállit	lále	V;IMP;SG;2
eallasit	eallaseappuid	ADJ;ACC;PL
fáskat	fáskkažetne	V;POT;DU;1
ihtit	ihtti	V;IMP;DU;2
suhkat	sugažit	V;POT;PL;3
cummát	cummájeadnu	V;IMP;DU;1
skillat	skilašii	V;COND;SG;3
šluŋkát	šluŋkážat	V;POT;SG;2
huhttát	huhttái	V;IND;SG;3;PST
ráhkestit	ráhkesteažžabehtet	V;POT;PL;2
čádjidit	čádjidehkon	V;IMP;SG;1
ciellat	cielašin	V;COND;SG;1
ciellat	ciela	V;IMP;SG;2
spiidni	spiinnis	N;PRP;SG
mihtidit	mihtidežžet	V;POT;PL;3
uhkidit	uhkidii	V;IND;SG;3;PST
deaddit	deattáleiddet	V;COND;PL;2;LGSPEC1
šealgut	šelggui	V;IND;SG;3;PST
allalávlla	allalávlagiin	N;PRP;PL
soaitit	soaittášeiddet	V;COND;PL;2
šearrát	šear'ráleimmet	V;COND;PL;1;LGSPEC1
bivdit	bivddii	V;IND;SG;3;PST
ruoidnát	ruoidnáleidde	V;COND;DU;2;LGSPEC1
šearrát	šear'rát	V;IND;PL;1;PRS
luokta	luoktan	N;FRML;SG
suddat	suttažeaba	V;POT;DU;3
boandut	bondon	V;IMP;SG;1
bárra	bárran	N;FRML;SG
čuorvut	čurvoska	V;IMP;DU;3
vázzát	vázzát	V;IND;PL;1;PRS
buhttáseamos	buhttáseamosin	ADJ;FRML;SG
mielddus	mildosiidda	N;IN+ALL;PL
jástit	jáston	V;IMP;SG;1
adnot	adnojehkoska	V;IMP;DU;3
ajihastit	ajihastte	V;IMP;SG;2
laigat	laigoska	V;IMP;DU;3
goikat	goiku	V;IMP;DU;1
suomastit	suomastivččet	V;COND;SG;2
šleambut	šlembboža	V;POT;SG;3
čearret	čearreha	N;ACC;SG
dološ	doložin	ADJ;FRML;SG
snuđđat	snuđaide	V;IND;DU;2;PST
oidit	oiddášeiddet	V;COND;PL;2
gargit	garggále	V;COND;PL;3;LGSPEC1
loaktit	lovttežit	V;POT;PL;3
veaddit	veaddá	V;IND;SG;3;PRS
suoládit	suoládivččet	V;COND;SG;2
davrát	davrážetne	V;POT;DU;1
nuortalašgiella	nuortalašgielaide	N;IN+ALL;PL
ruoškit	rušken	V;IND;SG;1;PST
huikit	huikos	V;IMP;SG;3
bagadit	bagadeahppi	V;IND;DU;2;PRS
kárpa	kárppat	N;NOM;PL
arestet	arestebehtet	V;IND;PL;2;PRS
astronávta	astronávtii	N;IN+ALL;SG
nieida	nieiddaiguin	N;COM;PL
iskat	iskka	V;IMP;SG;2
gilljut	giljuidet	V;IND;PL;2;PST
cahpat	cabalii	V;COND;SG;3;LGSPEC1
heaitit	heaittálit	V;COND;SG;2;LGSPEC1
čorget	čorget	V;IND;SG;2;PRS
dimenšuvdna	dimenšuvdnii	N;IN+ALL;SG
mollat	molažetne	V;POT;DU;1
mielddus	mildosiin	N;COM;SG
čádjidit	čádjidivččiiga	V;COND;DU;3
cillat	cillet	V;IMP;PL;2
skeaikit	skeiko	V;IMP;DU;3
snuđđat	snuđašit	V;COND;SG;2
čohkkát	čohkkále	V;COND;PL;3;LGSPEC1
diehtit	dieđášii	V;COND;SG;3
girječálli	girječálliiguin	N;COM;PL
njoallut	njoalun	V;IND;SG;1;PRS
njuoskaseamos	njuoskasepmosiidda	ADJ;IN+ALL;PL
muohttát	muohttášii	V;COND;SG;3
molljut	molljon	V;IMP;SG;1
rahčat	ražaleigga	V;COND;DU;3;LGSPEC1
apotehka	apotehkaid	N;ACC;PL
njartat	njarttašin	V;COND;SG;1
báralaš	báralaččaiguin	ADJ;COM;PL
dierbut	dierbbun	V;IND;SG;1;PRS
boaggut	bokkoleimme	V;COND;DU;1;LGSPEC1
gaŋkát	gaŋkájetnot	V;IMP;PL;1
ođđadárogiella	ođđadárogiela	N;ACC;SG
alvvaiduvvat	alvvaiduvvá	V;IND;SG;3;PRS
vuoksit	vuovssálin	V;COND;SG;1;LGSPEC1
šleambut	šlembbošin	V;COND;SG;1
boltut	bolttožeaba	V;POT;DU;3
cummát	cummáleimmet	V;COND;PL;1;LGSPEC1
goalvát	goalvážeaba	V;POT;DU;3
gaskat	gaskkažeaba	V;POT;DU;3
hoitát	hoitášit	V;COND;SG;2
goarjut	gorjjošeimmet	V;COND;PL;1
njeađgat	njeađggaža	V;POT;SG;3
liippát	liippájehkoset	V;IMP;PL;3
vuoigŋat	vuigŋoset	V;IMP;PL;3
čižži	čižžin	N;FRML;SG
ádjánit	ádjánin	V;IND;SG;1;PST
diŋgot	diŋgon	V;IND;SG;1;PRS
skuhčat	skužašii	V;COND;SG;3
fearrat	ferret	V;IND;PL;3;PRS
šiitit	šiittáše	V;COND;PL;3
skarkit	skarkiba	V;IND;DU;3;PRS
málet	máležit	V;POT;PL;1
molljut	molljot	V;IND;PL;3;PRS
hávga	hávgii	N;IN+ALL;SG
guolástit	guolástežžet	V;POT;PL;3
gálašit	gálašivččen	V;COND;SG;1
šleađgut	šleđggošin	V;COND;SG;1
deklamašuvdna	deklamašuvnnas	N;PRP;SG
boršut	borššošin	V;COND;SG;1
šuvvat	šuvašeiddet	V;COND;PL;2
eaidat	eideteaidit	V;IMP;PL;2
vuolgit	vulgos	V;IMP;SG;3
faggut	fakkoleimme	V;COND;DU;1;LGSPEC1
ruoššastit	ruoššasteigga	V;IND;DU;3;PST
giksat	giksabehtet	V;IND;PL;2;PRS
rahčat	ražai	V;IND;SG;3;PST
sorját	sorjálin	V;COND;SG;1;LGSPEC1
gieldit	gieldibeahtti	V;IND;DU;2;PRS
uvja	uvjii	N;IN+ALL;SG
šloaŋgát	šloaŋgášii	V;COND;SG;3
reavrát	reavrážetne	V;POT;DU;1
áfáiduvvat	áfáiduvašeidde	V;COND;DU;2
hearvát	hearválit	V;COND;SG;2;LGSPEC1
viggat	vikkan	V;IND;SG;1;PRS
reavrut	revrruimet	V;IND;PL;1;PST
njoarostit	njoarosteahppi	V;IND;DU;2;PRS
coggat	coggat	V;IND;PL;1;PRS
háistit	háisttášit	V;COND;SG;2
seaila	seaillain	N;PRP;PL
giehpa	giehpa	N;NOM;SG
máhtu	máđus	N;PRP;SG
njartat	njarttaidet	V;IND;PL;2;PST
nordat	norddai	V;IND;SG;3;PST
máidnut	máinnoleidde	V;COND;DU;2;LGSPEC1
geallit	gealáleiddet	V;COND;PL;2;LGSPEC1
gávrut	gávrrožit	V;POT;PL;3
smiergit	smirggežit	V;POT;PL;3
mannat	manalit	V;COND;SG;2;LGSPEC1
dihkki	dihkiin	N;COM;SG
faggut	faggon	V;IMP;SG;1
náššat	nášat	V;IND;SG;2;PRS
coggat	cokkažehpet	V;POT;PL;2
váibat	váibbai	V;IND;SG;3;PST
molljut	mollju	V;IND;SG;3;PRS
stuorát	stuorábuid	ADJ;GEN;PL
dehálit	deháleappuide	ADJ;IN+ALL;PL
árvidit	árvidii	V;IND;SG;3;PST
rievssat	rievssahiiguin	N;COM;PL
šiggut	šikkošeidde	V;COND;DU;2
bánžat	bánžaide	V;IND;DU;2;PST
vurket	vurkejehket	V;IMP;PL;2
liippát	liippáše	V;COND;PL;3
čovvát	čov'vážetne	V;POT;DU;1
bidjat	bidjon	V;IMP;SG;1
biebmat	biepmašeimmet	V;COND;PL;1
urdit	urdot	V;IMP;PL;1
máššat	máššos	V;IMP;SG;3
áibmat	áimmažeahppi	V;POT;DU;2
sodnját	sodnjáime	V;IND;DU;1;PST
sáhttit	sáhtášeimme	V;COND;DU;1
bieggat	biekka	V;IMP;SG;2
duvdit	duvddášeigga	V;COND;DU;3
luoitit	luitteža	V;POT;SG;3
borgat	borggalin	V;COND;SG;1;LGSPEC1
soallut	sololit	V;COND;SG;2;LGSPEC1
ilbmat	ilmmaža	V;POT;SG;3
skarkit	skarkke	V;IMP;SG;2
dietnut	dinolin	V;COND;SG;1;LGSPEC1
apoastal	apoastaliin	N;PRP;PL
skoahččát	skoahččájin	V;IND;SG;1;PST
gáhččat	gáhččet	V;IND;SG;2;PST
suhkat	suhkku	V;IMP;DU;1
agáiduvvat	agáiduvašii	V;COND;SG;3
gaŋgát	gaŋgášeidde	V;COND;DU;2
adnot	adnožeaba	V;POT;DU;3
skilkit	skilkke	V;IMP;SG;2
náitit	náitibehtet	V;IND;PL;2;PRS
ballat	balaža	V;POT;SG;3
ruossut	russo	V;IND;DU;1;PRS
deaivat	deaivvai	V;IND;SG;3;PST
máidnut	máidno	V;IND;PL;3;PST
áidi	áiddiiguin	N;COM;PL
biktit	bivttežeaba	V;POT;DU;3
ráhkestit	ráhkesteiddet	V;IND;PL;2;PST
vážus	váhčosat	N;NOM;PL
buktit	buvttášin	V;COND;SG;1
stoavkit	stoavkkáleimmet	V;COND;PL;1;LGSPEC1
vihpat	vibašeimmet	V;COND;PL;1
roabát	roabáhis	N;PRP;SG
gullat	gulloset	V;IMP;PL;3
čieŋal	čieŋal	ADJ;NOM;SG
baldit	balddášeimme	V;COND;DU;1
jástit	jásttii	V;IND;SG;3;PST
buorránit	buorránivččiide	V;COND;DU;2
kiella	killii	N;IN+ALL;SG
boahtal	boahtaliin	N;PRP;PL
viessu	viessu	N;NOM;SG
šlahttit	šlahtát	V;IND;SG;2;PRS
reakcut	revccošin	V;COND;SG;1
deaffat	deffet	V;IND;PL;3;PRS
lieđđi	lieđđin	N;FRML;SG
geallit	gealášeidde	V;COND;DU;2
čulkit	čulkkiimet	V;IND;PL;1;PST
beassat	beasašeimmet	V;COND;PL;1
hearvát	hearvájit	V;IND;PL;3;PRS
njárbat	njárbada	ADJ;ACC;SG
loaidat	loaiddaše	V;COND;PL;3
čielgaseamos	čielgasepmosiid	ADJ;GEN;PL
galbmit	galmmášeigga	V;COND;DU;3
gaŋkát	gaŋkálit	V;COND;SG;2;LGSPEC1
čeahpit	čeahpibuiguin	ADJ;COM;PL
vuossárga	vuossárgii	N;IN+ALL;SG
buorránit	buorránetne	V;IND;DU;1;PRS
čagardit	čagardii	V;IND;SG;3;PST
duohččat	duohčale	V;COND;PL;3;LGSPEC1
ipmirdit	ipmirdežže	V;POT;DU;1
skillat	skilaleiddet	V;COND;PL;2;LGSPEC1
delegašuvdna	delegašuvdnan	N;FRML;SG
breahtta	breahtain	N;PRP;PL
bárra	báraiguin	N;COM;PL
seailut	seailut	V;IND;PL;1;PRS
bivvát	biv'váide	V;IND;DU;2;PST
adreassa	adreassa	N;GEN;SG
jahtat	jađan	V;IND;SG;1;PRS
oađđit	oađáleimme	V;COND;DU;1;LGSPEC1
villat	villaleiddet	V;COND;PL;2;LGSPEC1
bidjat	bidjot	V;IMP;PL;1
suorganit	suorganeažžabehtet	V;POT;PL;2
mihtidit	mihtideimme	V;IND;DU;1;PST
buoidda	buoidagiid	N;GEN;PL
muohta	muođaid	N;GEN;PL
luoddut	luttui	V;IND;SG;3;PST
suomastit	suomastetne	V;IND;DU;1;PRS
skuhrrat	skuhrat	V;IND;SG;2;PRS
gávccinuppelogát	gávccinuppelogádii	ADJ;IN+ALL;SG
čagardit	čagardit	V;IND;SG;2;PST
stirrát	stir'rájetnot	V;IMP;PL;1
sirdit	sirddeža	V;POT;SG;3
snuhrrat	snuhr'ri	V;IMP;DU;2
bávkit	bávkkálii	V;COND;SG;3;LGSPEC1
seaisat	seaissažehpet	V;POT;PL;2
gaŋgát	gaŋgážehpet	V;POT;PL;2
muollat	muollat	V;IND;PL;1;PRS
skutnjat	skutnjet	V;IMP;PL;2
sámegiella	sámegielaid	N;GEN;PL
cummát	cummájetne	V;IND;DU;1;PRS
vihpat	vihpe	V;IND;PL;3;PST
bollát	bol'lájit	V;IND;PL;3;PRS
muorra	muoraiguin	N;COM;PL
lutnjat	lunjan	V;IND;SG;1;PRS
máššat	mášažan	V;POT;SG;1
eadnán	eadnán	N;NOM;SG
gussa	gusa	N;GEN;SG
buorránit	buorráneiddet	V;IND;PL;2;PST
čierrut	čirui	V;IND;SG;3;PST
eahccit	eahcášeiddet	V;COND;PL;2
máidnut	máinnun	V;IND;SG;1;PRS
njuikut	njuikkožehpet	V;POT;PL;2
rátkit	rátkibeahtti	V;IND;DU;2;PRS
gahkit	gahkibeahtti	V;IND;DU;2;PRS
šuvvat	šuvašin	V;COND;SG;1
diehtit	diđii	V;IND;SG;3;PST
davrát	davrášii	V;COND;SG;3
deavdit	deavddášin	V;COND;SG;1
čájihit	čájihežžet	V;POT;PL;3
njáldit	njáldit	V;IND;PL;1;PRS
oskut	oskkošeimmet	V;COND;PL;1
duhtat	duhtti	V;IMP;DU;2
geahčastit	geahčastivččiiga	V;COND;DU;3
rássi	rásiiguin	N;COM;PL
báralaš	báralaččaid	ADJ;GEN;PL
cissat	cissašeimmet	V;COND;PL;1
mánnu	mánut	N;NOM;PL
beassat	beassabehtet	V;IND;PL;2;PRS
lávlla	lávlaga	N;ACC;SG
beaivi	beaivvi	N;ACC;SG
guoggut	gukkožeahppi	V;POT;DU;2
njartat	njarttašeiddet	V;COND;PL;2
báffat	báffoska	V;IMP;DU;3
šearrát	šear'rá	V;IMP;SG;2
fáskat	fásket	V;IMP;PL;2
boršut	borššolin	V;COND;SG;1;LGSPEC1
ásahit	ásaheaččat	V;POT;SG;2
spiidni	spiinnit	N;NOM;PL
dihkki	dihkkái	N;IN+ALL;SG
láppis	lábbáid	N;ACC;PL
šleambut	šlembo	V;IND;DU;1;PRS
dávgut	dávgot	V;IND;PL;3;PRS
jiehtanas	jiehtanasaid	N;GEN;PL
gaskat	gaskkaleimmet	V;COND;PL;1;LGSPEC1
čihkosit	čihkoseappuiguin	ADJ;COM;PL
šiehttat	šihttot	V;IMP;PL;1
skoahččát	skoahččát	V;IND;SG;2;PRS
čuollat	čuolažit	V;POT;PL;3
gieldit	gildoska	V;IMP;DU;3
navdit	navddále	V;COND;PL;3;LGSPEC1
čávvat	čáva	V;IMP;SG;2
fuoikit	fuiken	V;IND;SG;1;PST
njammat	njamme	V;IND;DU;1;PRS
vurket	vurkešeiddet	V;COND;PL;2
átnut	ánožeahppi	V;POT;DU;2
rančát	rančášeimmet	V;COND;PL;1
gulkat	gulkkaimet	V;IND;PL;1;PST
dehálaččamus	dehálaččamusaid	ADJ;ACC;PL
vávvát	váv'váimet	V;IND;PL;1;PST
jápmit	jámežehpet	V;POT;PL;2
čiekčat	čievččaše	V;COND;PL;3
dieigi	diiggiin	N;COM;SG
nearva	nearva	N;NOM;SG
bivvat	bivvabehtet	V;IND;PL;2;PRS
skavdda	skavdaga	N;GEN;SG
suovvabohcci	suovvabohcciide	N;IN+ALL;PL
guohkkat	guohkalii	V;COND;SG;3;LGSPEC1
leabbut	leppožehpet	V;POT;PL;2
fuorrá	fuorrán	N;FRML;SG
litnjat	litnjaba	V;IND;DU;3;PRS
gávrut	gávrruidet	V;IND;PL;2;PST
dahkat	dagaidet	V;IND;PL;2;PST
laigat	laiggašeimmet	V;COND;PL;1
boikohttet	boikohttelin	V;COND;SG;1;LGSPEC1
čuoskut	čuoskubeahtti	V;IND;DU;2;PRS
arestet	arestejit	V;IND;PL;3;PRS
guorsat	guorssašeigga	V;COND;DU;3
beassat	bessoska	V;IMP;DU;3
dipmat	dimašit	V;COND;SG;2
vihpat	vibažeaba	V;POT;DU;3
cadjat	cajaiga	V;IND;DU;3;PST
eahket	eahkediiguin	N;COM;PL
geassit	geasášeimmet	V;COND;PL;1
čuohppat	čuohpaše	V;COND;PL;3
čeahpimus	čeahpimusaid	ADJ;GEN;PL
duoggut	dukkoža	V;POT;SG;3
doarrát	doar'rážeaba	V;POT;DU;3
uštit	ušttii	V;IND;SG;3;PST
reavrát	reavráleidde	V;COND;DU;2;LGSPEC1
jahtat	jahton	V;IMP;SG;1
jápmit	jámášin	V;COND;SG;1
máhccat	máhcalin	V;COND;SG;1;LGSPEC1
gahkit	gagežan	V;POT;SG;1
suhkat	sugaleimme	V;COND;DU;1;LGSPEC1
heaitit	heitoska	V;IMP;DU;3
hoigat	hoiggažeahppi	V;POT;DU;2
reŋgot	reŋgon	V;IND;SG;1;PRS
gussa	gussii	N;IN+ALL;SG
haksit	havsse	V;IMP;SG;2
čovvát	čov'váleigga	V;COND;DU;3;LGSPEC1
orda	orddaiguin	N;COM;PL
geaidit	geaidu	V;IMP;DU;1
doarggistit	doarggistežže	V;POT;DU;1
spatnjat	spanjale	V;COND;PL;3;LGSPEC1
čorget	čorgebeahtti	V;IND;DU;2;PRS
barbára	barbárain	N;PRP;PL
fierrut	firošeimmet	V;COND;PL;1
lákcut	lávccoleidde	V;COND;DU;2;LGSPEC1
fearrat	fearat	V;IND;SG;2;PRS
guomu	gubmo	N;ACC;SG
náitit	náittáleidde	V;COND;DU;2;LGSPEC1
bieggat	biekkažan	V;POT;SG;1
nállat	nálažit	V;POT;PL;3
bollát	bol'láža	V;POT;SG;3
čuovgat	čuovgadiid	ADJ;ACC;PL
luoikat	luoikkaleimmet	V;COND;PL;1;LGSPEC1
čuohppat	čuhppet	V;IND;PL;3;PRS
njoallut	njoallu	V;IND;SG;3;PRS
kollektiiva	kollektiivva	N;ACC;SG
njoarostit	njoarostehkoset	V;IMP;PL;3
rihccut	rihcoleimme	V;COND;DU;1;LGSPEC1
diehtit	diehtibehtet	V;IND;PL;2;PRS
lákcut	lávccoleimmet	V;COND;PL;1;LGSPEC1
rančát	rančášeidde	V;COND;DU;2
skeaikit	skeaikkále	V;COND;PL;3;LGSPEC1
lávlageattet	lávlagiinnádet	N;COM;SG
gullat	gulaide	V;IND;DU;2;PST
gaskat	gaskkan	V;IND;SG;1;PRS
skuhrrat	skuhrale	V;COND;PL;3;LGSPEC1
luoikat	luoikkažan	V;POT;SG;1
njeađgat	njeađgaba	V;IND;DU;3;PRS
guovvamánnu	guovvamánuiguin	N;COM;PL
gávrát	gávrájin	V;IND;SG;1;PST
geahčastit	geahčastivččii	V;COND;SG;3
háŋgut	háŋggožan	V;POT;SG;1
heaitit	heaitiba	V;IND;DU;3;PRS
áigečála	áigečállagii	N;IN+ALL;SG
roandit	ronddežat	V;POT;SG;2
automáhtalaš	automáhtalaččaide	ADJ;IN+ALL;PL
doarrut	dorošeiddet	V;COND;PL;2
deabbut	debboset	V;IMP;PL;3
bánžat	bánže	V;IND;DU;1;PRS
ipmirdit	ipmirdii	V;IND;SG;3;PST
buoidudit	buoidudivčče	V;COND;PL;3
goaskin	goaskimiid	N;GEN;PL
joatkit	joatki	V;IMP;DU;2
liekčát	liekčáleidde	V;COND;DU;2;LGSPEC1
kárta	kártii	N;IN+ALL;SG
čierrut	čiruidet	V;IND;PL;2;PST
gáhččat	gáhčču	V;IMP;DU;1
nearrat	nearašeidde	V;COND;DU;2
guhkkat	guhkašii	V;COND;SG;3
gávrut	gávru	V;IND;SG;3;PRS
ođđajahki	ođđajahkái	N;IN+ALL;SG
boalbut	bolb	V;COND;DU;1;LGSPEC1
vearru	vearuin	N;COM;SG
cukcat	cuvccaimet	V;IND;PL;1;PST
rusen	rusena	N;GEN;SG
reavgut	revggožehpet	V;POT;PL;2
čeallut	čelloska	V;IMP;DU;3
váibmu	váimmuid	N;GEN;PL
maŋŋebárga	maŋŋebárggat	N;NOM;PL
laigat	laiget	V;IND;SG;2;PST
lávlagan	lávlagan	N;NOM;SG
mearka	mearkka	N;GEN;SG
jakŋat	jaŋaleimmet	V;COND;PL;1;LGSPEC1
rahpat	rabalit	V;COND;SG;2;LGSPEC1
biebmat	bibmen	V;IND;SG;1;PST
baikin	baikimiidda	N;IN+ALL;PL
čuopmat	čuomale	V;COND;PL;3;LGSPEC1
caggat	cakkažat	V;POT;SG;2
doaibmat	doaimmaide	V;IND;DU;2;PST
lákcut	lávccut	V;IND;SG;2;PRS
laggat	lakkažan	V;POT;SG;1
cahkat	cagašin	V;COND;SG;1
náitit	náittežit	V;POT;PL;1
čeallulit	čeallulehpet	V;IND;PL;2;PRS
liippát	liippážehpet	V;POT;PL;2
sáhttit	sáhtte	V;IND;PL;3;PST
vuohppát	vuohppán	V;IND;SG;1;PRS
állát	ál'lájehkon	V;IMP;SG;1
golgadit	golgadin	V;IND;SG;1;PST
oassi	osiiguin	N;COM;PL
attribuhtta	attribuhtaid	N;ACC;PL
searvi	searvái	N;IN+ALL;SG
duođat	duođabuidda	ADJ;IN+ALL;PL
bearrat	bearaleidde	V;COND;DU;2;LGSPEC1
gávrut	gávrrošeimmet	V;COND;PL;1
nuortalašgiella	nuortalašgielain	N;COM;SG
vuosehit	vuosehan	V;IND;SG;1;PRS
ráhkistit	ráhkistivččiimet	V;COND;PL;1
láikkit	láikkibui	ADJ;IN+ALL;SG
biergu	biergun	N;FRML;SG
boršut	borššošit	V;COND;SG;2
ádjánit	ádjánivččiide	V;COND;DU;2
vuolla	vuolaid	N;ACC;PL
gávrut	gávrruimet	V;IND;PL;1;PST
maŋŋebárga	maŋŋebárgga	N;GEN;SG
ráddut	ráttuime	V;IND;DU;1;PST
leat	lea	V;IND;SG;3;PRS
niitu	niitu	N;NOM;SG
šuohkkit	šuhkežan	V;POT;SG;1
jápmit	jámálin	V;COND;SG;1;LGSPEC1
širrat	širrat	V;IND;PL;1;PRS
bohtal	bohttalis	N;PRP;SG
ihtit	ihte	V;IND;PL;3;PST
seailut	seilo	V;IND;PL;3;PST
dolastit	dolasteaba	V;IND;DU;3;PRS
vákšut	vávššuime	V;IND;DU;1;PST
ávus	ávvosiiguin	N;COM;PL
málet	máležan	V;POT;SG;1
sahčat	sahčoska	V;IMP;DU;3
saddit	sattiiga	V;IND;DU;3;PST
dihkkat	dihkkos	V;IMP;SG;3
njoazimus	njoazimusain	ADJ;COM;SG
albmeassi	albmeasis	N;PRP;SG
bárgut	bárggolit	V;COND;SG;2;LGSPEC1
jalgat	jalgadin	ADJ;FRML;SG
ádjit	ájášeidde	V;COND;DU;2
gaŋkát	gaŋkát	V;IND;PL;1;PRS
čoavdit	čoavddálin	V;COND;SG;1;LGSPEC1
loaidat	loaiddat	V;IND;SG;2;PRS
gáhččat	gáhčale	V;COND;PL;3;LGSPEC1
spildut	spilddožit	V;POT;PL;3
loavdit	lovdet	V;IND;PL;3;PRS
vuoksit	vukset	V;IND;PL;3;PRS
soallut	soallubehtet	V;IND;PL;2;PRS
gaŋkát	gaŋkále	V;COND;PL;3;LGSPEC1
davrát	davrát	V;IND;SG;2;PRS
borgat	borgá	V;IND;SG;3;PRS
skilkit	skilkkáleiddet	V;COND;PL;2;LGSPEC1
náššat	náššabeahtti	V;IND;DU;2;PRS
arestet	arestejin	V;IND;SG;1;PST
boagustit	boagustivčče	V;COND;PL;3
njávgit	njávggiime	V;IND;DU;1;PST
nihttit	nihtáleimmet	V;COND;PL;1;LGSPEC1
johttát	johttáleiddet	V;COND;PL;2;LGSPEC1
sáhttit	sáhtii	V;IND;SG;3;PST
bodnját	bodnjájehkos	V;IMP;SG;3
skarkit	skarkkálit	V;COND;SG;2;LGSPEC1
duohččat	duohčašeimme	V;COND;DU;1
gahkit	gahket	V;IND;PL;3;PRS
nohkkat	nohkaža	V;POT;SG;3
leahki	legiid	N;GEN;PL
čukčá	čuvččáin	N;PRP;PL
cirgut	cirggut	V;IND;SG;2;PRS
áitit	áittášeidde	V;COND;DU;2
bierfát	bierfáleimmet	V;COND;PL;1;LGSPEC1
sahčat	sažažeahppi	V;POT;DU;2
cuozza	cuzzii	N;IN+ALL;SG
čáihni	čáihnniin	N;PRP;PL
čáhppadeamos	čáhppadepmosiid	ADJ;GEN;PL
skuhrrat	skuhraleimme	V;COND;DU;1;LGSPEC1
vuogas	vuohkkasiid	ADJ;ACC;PL
ásahit	ásaheaba	V;IND;DU;3;PRS
duohččat	duohččat	V;IND;PL;1;PRS
rámbut	rámbu	V;IMP;DU;1
spalcat	spalccaleigga	V;COND;DU;3;LGSPEC1
navdit	navddášeiddet	V;COND;PL;2
máššat	mášaleimmet	V;COND;PL;1;LGSPEC1
alvvahuvvat	alvvahuvai	V;IND;SG;3;PST
árrit	áre	V;IMP;SG;2
goarjut	gorjjožit	V;POT;PL;3
njávgit	njávggášin	V;COND;SG;1
gohccát	gohccálit	V;COND;SG;2;LGSPEC1
jakŋat	jaŋažat	V;POT;SG;2
adnot	adnui	V;IND;SG;3;PST
hávda	hávda	N;NOM;SG
suorbma	suorpma	N;ACC;SG
gieldit	gilddiime	V;IND;DU;1;PST
bivvat	bivašeidde	V;COND;DU;2
guhkkat	guhkká	V;IND;SG;3;PRS
suostat	suosttašeimme	V;COND;DU;1
gilljut	giljoleigga	V;COND;DU;3;LGSPEC1
vihpat	vibale	V;COND;PL;3;LGSPEC1
duoggut	dukkoleigga	V;COND;DU;3;LGSPEC1
gaŋkát	gaŋkášeidde	V;COND;DU;2
čiekčat	čievččašii	V;COND;SG;3
šealgat	šealgadiiguin	ADJ;COM;PL
láibut	láibboleiddet	V;COND;PL;2;LGSPEC1
bivvat	bivve	V;IND;PL;3;PST
ásahit	ásahehket	V;IMP;PL;2
uštit	ušten	V;IND;SG;1;PST
huilát	huiláide	V;IND;DU;2;PST
dolkat	dolkkašin	V;COND;SG;1
beavdi	beavddi	N;ACC;SG
háŋgut	háŋgut	V;IND;PL;1;PRS
huilát	huilále	V;COND;PL;3;LGSPEC1
mulgut	mulggošeidde	V;COND;DU;2
addálas	addálasa	ADJ;GEN;SG
deabbut	deppožan	V;POT;SG;1
hárdit	hárddežan	V;POT;SG;1
vuoksit	vuoksu	V;IMP;DU;1
deapmat	deamalii	V;COND;SG;3;LGSPEC1
biila	biillaid	N;ACC;PL
diehtit	diehtti	V;IMP;DU;2
boaldit	bolde	V;IND;PL;3;PST
diehtit	diehtibeahtti	V;IND;DU;2;PRS
ruoidnát	ruoidná	V;IND;SG;3;PRS
liippát	liippát	V;IND;SG;2;PRS
cadjat	cadjoska	V;IMP;DU;3
bárra	bárat	N;NOM;PL
allatiiva	allatiivvas	N;PRP;SG
mánnu	mánnui	N;IN+ALL;SG
iskat	isket	V;IMP;PL;2
nuortalaš	nuortalaččain	N;PRP;PL
gievdni	gievnnit	N;NOM;PL
toarga	torgii	N;IN+ALL;SG
šleambut	šlembbošeimme	V;COND;DU;1
reahccut	rehcoleiddet	V;COND;PL;2;LGSPEC1
bassat	basažit	V;POT;PL;1
ráhkesvuohta	ráhkesvuođaiguin	N;COM;PL
cahppát	cahppášeigga	V;COND;DU;3
jurbmát	jurbmá	V;IMP;SG;2
fuorrá	fuorrái	N;IN+ALL;SG
cummát	cummále	V;COND;PL;3;LGSPEC1
ilbmat	ilmmažetne	V;POT;DU;1
huikit	huikkežit	V;POT;PL;1
geologiija	geologiija	N;NOM;SG
golgadit	golgadehkot	V;IMP;PL;1
háistit	háisttášeigga	V;COND;DU;3
stoahkat	stohket	V;IMP;PL;2
mođđat	mođaleigga	V;COND;DU;3;LGSPEC1
sarva	sarvvat	N;NOM;PL
jástit	jástiba	V;IND;DU;3;PRS
struhpat	strubaše	V;COND;PL;3
girtat	girttašin	V;COND;SG;1
aiget	aigežehpet	V;POT;PL;2
cohkkát	cohkkášeidde	V;COND;DU;2
nealgut	nelggoleigga	V;COND;DU;3;LGSPEC1
seaŋga	seaŋggat	N;NOM;PL
njaŋgát	njaŋgášeimme	V;COND;DU;1
dietnut	ditnon	V;IND;SG;1;PST
skeaikit	skeikkiide	V;IND;DU;2;PST
cissat	cis'set	V;IND;SG;2;PST
skihččát	skihččá	V;IMP;SG;2
hávda	hávddain	N;PRP;PL
gádjut	gájui	V;IND;SG;3;PST
holvut	holvvožit	V;POT;PL;1
julevsámegiella	julevsámegielat	N;NOM;PL
bivvát	biv'válit	V;COND;SG;2;LGSPEC1
boltut	bolttošin	V;COND;SG;1
čulkit	čulket	V;IND;SG;2;PST
lapmat	lapmabeahtti	V;IND;DU;2;PRS
cuvkit	cuvkke	V;IMP;SG;2
njiedjat	njieddji	V;IMP;DU;2
márfut	márffoleidde	V;COND;DU;2;LGSPEC1
boaggut	bokkoleiddet	V;COND;PL;2;LGSPEC1
bargat	barggašin	V;COND;SG;1
njávgit	njávggále	V;COND;PL;3;LGSPEC1
jahtat	jađaidet	V;IND;PL;2;PST
háistit	háiston	V;IMP;SG;1
duoldat	duoldda	V;IMP;SG;2
njoammut	njomoše	V;COND;PL;3
láibut	láibbo	V;IMP;SG;2
vealčut	velčon	V;IMP;SG;1
oahkut	ohkoska	V;IMP;DU;3
boras	borrasis	N;PRP;SG
guovssahas	guovssahasaide	N;IN+ALL;PL
luoitit	luoitibeahtti	V;IND;DU;2;PRS
guoktelogigoalmmát	guoktelogigoalmmádiid	ADJ;ACC;PL
mihtidit	mihtideaččan	V;POT;SG;1
rihpat	ribaiga	V;IND;DU;3;PST
girtat	girttašeimmet	V;COND;PL;1
addáleamos	addálepmosa	ADJ;GEN;SG
ráhkesvuohta	ráhkesvuođaid	N;ACC;PL
coggat	cokkaiga	V;IND;DU;3;PST
addálit	addáleappuide	ADJ;IN+ALL;PL
uhkidit	uhkidivččet	V;COND;SG;2
bárgut	bárggožat	V;POT;SG;2
bollát	bol'lát	V;IND;SG;2;PRS
autoritehta	autoritehtan	N;FRML;SG
gáhččat	gáhčči	V;IMP;DU;2
gávrát	gávráleidde	V;COND;DU;2;LGSPEC1
dolkat	dolket	V;IMP;PL;2
heaibat	heaibbaiga	V;IND;DU;3;PST
čorget	čorgešeidde	V;COND;DU;2
máttasámegiella	máttasámegielaiguin	N;COM;PL
šiitit	šiittiimet	V;IND;PL;1;PST
guorsat	gurson	V;IMP;SG;1
boaldit	bolddežehpet	V;POT;PL;2
arkiiva	arkiivva	N;ACC;SG
monni	moni	N;GEN;SG
roandit	rondet	V;IND;SG;2;PST
duđahit	duđaheiddet	V;IND;PL;2;PST
hearvát	hearvážit	V;POT;PL;3
eadni	eadni	N;NOM;SG
čádjidit	čádjidivččii	V;COND;SG;3
láđđi	láđđin	N;FRML;SG
ođđajagimánnu	ođđajagimánnun	N;FRML;SG
vadjat	vajaleimme	V;COND;DU;1;LGSPEC1
njoallut	njološit	V;COND;SG;2
čohkkát	čohkká	V;IND;SG;3;PRS
suossat	suosažehpet	V;POT;PL;2
argumeanta	argumentii	N;IN+ALL;SG
seastit	seasttálit	V;COND;SG;2;LGSPEC1
čuorvut	čurvvožetne	V;POT;DU;1
heaŋgát	heaŋgážetne	V;POT;DU;1
boagustit	boagustit	V;IND;SG;2;PST
geallat	gealažit	V;POT;PL;3
muollat	muolat	V;IND;SG;2;PRS
doaivvuhit	doaivvuha	V;IND;SG;3;PRS
nihttit	nihtáleigga	V;COND;DU;3;LGSPEC1
fierrut	firošeimme	V;COND;DU;1
čuollát	čuol'láleimmet	V;COND;PL;1;LGSPEC1
oidit	oiddáleidde	V;COND;DU;2;LGSPEC1
muohttát	muohttášeidde	V;COND;DU;2
áitit	áitet	V;IMP;PL;2
boaibmut	boibmot	V;IMP;PL;2
duđahit	duđaheimmet	V;IND;PL;1;PST
arkiiva	arkiivvain	N;COM;SG
lákcut	lákcu	V;IMP;DU;1
snuhrrat	snuhrrabehtet	V;IND;PL;2;PRS
bieggat	biekkažehpet	V;POT;PL;2
guoggát	guoggá	V;IMP;SG;2
guorbát	guorbášii	V;COND;SG;3
háŋgut	háŋggolii	V;COND;SG;3;LGSPEC1
giehtaruohtas	giehtaruohttasiin	N;COM;SG
duottar	duoddariin	N;PRP;PL
urdit	urdoset	V;IMP;PL;3
ádjánit	ádjáneaččan	V;POT;SG;1
háŋgut	háŋggožehpet	V;POT;PL;2
vašálaččat	vašálaččabuiguin	ADJ;COM;PL
deallut	deallu	V;IND;SG;3;PRS
buohcci	buohccit	N;NOM;PL
áddet	áddežit	V;POT;PL;1
čurtát	čurtá	V;IMP;SG;2
njanzát	njanzášeimme	V;COND;DU;1
čáskat	čáskkat	V;IND;SG;2;PRS
áktit	ákte	V;IND;DU;1;PRS
gažahit	gažahivččen	V;COND;SG;1
dievvat	divvet	V;IND;SG;2;PST
juhkaluvvat	juhkaluvaleiddet	V;COND;PL;2;LGSPEC1
giron	gironis	N;PRP;SG
geahččat	geahčašin	V;COND;SG;1
sehkket	sehkkežehpet	V;POT;PL;2
čavgadeamos	čavgadepmosiid	ADJ;GEN;PL
čearguladdat	čearguladdos	V;IMP;SG;3
addálasat	addálasabuin	ADJ;PRP;PL
bruvda	bruvddat	N;NOM;PL
čuoggut	čukkuime	V;IND;DU;1;PST
ruosta	ruosttaid	N;ACC;PL
aiddostahttit	aiddostahttiba	V;IND;DU;3;PRS
lihtter	lihtterat	N;NOM;PL
hilgut	hilggožeaba	V;POT;DU;3
gálgat	gálget	V;IND;PL;3;PRS
brillat	brillat	N;NOM;PL
čigŋát	čigŋábeahtti	V;IND;DU;2;PRS
autoriseret	autoriseren	V;IND;SG;1;PRS
lotnut	lonui	V;IND;SG;3;PST
lahpat	labažeahppi	V;POT;DU;2
jearrat	jearažit	V;POT;PL;3
snoallat	snoalažetne	V;POT;DU;1
dolastaddat	dolastattašeiddet	V;COND;PL;2
čieskat	čieskkalit	V;COND;SG;2;LGSPEC1
sadjit	saddji	V;IMP;DU;2
čierastit	čierasta	V;IND;SG;3;PRS
mahkkit	mahkášii	V;COND;SG;3
juhkaluvvat	juhkaluvvoska	V;IMP;DU;3
speadjal	speadjalin	N;FRML;SG
ruoidnat	ruoinnažat	V;POT;SG;2
sruva	sruvii	N;IN+ALL;SG
muitit	muiten	V;IND;SG;1;PST
gallen	gallemiin	N;PRP;PL
čurtát	čurtážehpet	V;POT;PL;2
uhkki	uhkiid	N;GEN;PL
báhcit	bázále	V;COND;PL;3;LGSPEC1
beađđat	beđđoset	V;IMP;PL;3
abskissa	abskissat	N;NOM;PL
njiellat	njillet	V;IND;SG;2;PST
leandit	leanddášii	V;COND;SG;3
máltit	málttášit	V;COND;SG;2
vuodjut	vujolii	V;COND;SG;3;LGSPEC1
viidni	viinnit	N;NOM;PL
šleambit	šleambibehtet	V;IND;PL;2;PRS
nuollat	nuolašit	V;COND;SG;2
ajihustit	ajihusttiide	V;IND;DU;2;PST
luohttit	luhtežit	V;POT;PL;3
heaibut	heibbošin	V;COND;SG;1
eadnáde	eatnáde	N;GEN;SG
ovccinuppelogát	ovccinuppelogádiiguin	ADJ;COM;PL
guolbmat	guolmmašeimmet	V;COND;PL;1
boles	boles	N;NOM;SG
goallut	golui	V;IND;SG;3;PST
čoarrát	čoar'rá	V;IMP;SG;2
gávdnat	gávnnaide	V;IND;DU;2;PST
bohccon	bohccostan	N;PRP;SG
vuorkut	vurkkuimet	V;IND;PL;1;PST
stuorimus	stuorimusain	ADJ;COM;SG
snuordát	snuordáleidde	V;COND;DU;2;LGSPEC1
sildnit	silnnálin	V;COND;SG;1;LGSPEC1
mánnodat	mánnodagat	N;NOM;PL
geatki	getkkiin	N;COM;SG
deakčut	devččošeidde	V;COND;DU;2
máilmmicup	máilmmicupaid	N;GEN;PL
ceaggát	ceaggálii	V;COND;SG;3;LGSPEC1
giektat	giektu	V;IMP;DU;1
rávkat	rávkkaidet	V;IND;PL;2;PST
amastit	amastit	V;IND;PL;3;PRS
aresteret	arestereleidde	V;COND;DU;2;LGSPEC1
áibbašit	áibbašeigga	V;IND;DU;3;PST
doaibat	doaibbaiga	V;IND;DU;3;PST
cabbi	cappit	N;NOM;PL
nuondat	nunde	V;IND;DU;1;PRS
vardit	vardot	V;IMP;PL;1
goaski	goaski	N;NOM;SG
teknologiija	teknologiija	N;GEN;SG
dovdat	dovdot	V;IMP;PL;1
njaldit	njalddeža	V;POT;SG;3
jávkat	jávkkažeahppi	V;POT;DU;2
niitit	niittáleidde	V;COND;DU;2;LGSPEC1
cabbi	cabbin	N;FRML;SG
jurdit	jurddášeiddet	V;COND;PL;2
bossut	bosošeimme	V;COND;DU;1
leavdnit	leavnnát	V;IND;SG;2;PRS
giehka	giegaid	N;ACC;PL
vuovdit	vuvddii	V;IND;SG;3;PST
njahppit	njahppe	V;IND;DU;1;PRS
njanzát	njanzájehkon	V;IMP;SG;1
čiehkat	čiegašeimmet	V;COND;PL;1
aldna	alnnat	N;NOM;PL
čavgadeamos	čavgadepmosat	ADJ;NOM;PL
bálggis	bálgáid	N;GEN;PL
addit	attálit	V;COND;SG;2;LGSPEC1
boahtit	boađáleiddet	V;COND;PL;2;LGSPEC1
njealljenuppelogát	njealljenuppelogádat	ADJ;NOM;PL
jaskat	jaskada	ADJ;ACC;SG
fitnat	finaleigga	V;COND;DU;3;LGSPEC1
juksat	juvssažit	V;POT;PL;1
bispa	bisppain	N;COM;SG
álgga	álgagat	N;NOM;PL
gastit	gasttále	V;COND;PL;3;LGSPEC1
čuoigát	čuoigájit	V;IND;SG;2;PST
vahcut	vazoleidde	V;COND;DU;2;LGSPEC1
geavrát	geavrášii	V;COND;SG;3
čeargat	čearggaleidde	V;COND;DU;2;LGSPEC1
hihttát	hihttáime	V;IND;DU;1;PST
šealgadit	šealgadeappuid	ADJ;ACC;PL
čuohkat	čuogašeimme	V;COND;DU;1
govdut	govddoleimmet	V;COND;PL;1;LGSPEC1
vuordnut	vurtnolii	V;COND;SG;3;LGSPEC1
čuožžut	čuččuidet	V;IND;PL;2;PST
álgit	álget	V;IMP;PL;2
guođđit	guđđot	V;IMP;PL;1
brigáda	brigáda	N;GEN;SG
jearrat	jear'ru	V;IMP;DU;1
girji	girjjiiguin	N;COM;PL
duhtadit	duhtadehkon	V;IMP;SG;1
borrat	borron	V;IMP;SG;1
vuođgŋit	vuđŋŋii	V;IND;SG;3;PST
lullisámegiella	lullisámegielaid	N;GEN;PL
fagŋát	fagŋájit	V;IND;PL;3;PRS
árbi	árbbiide	N;IN+ALL;PL
sihkkut	sihkošeimmet	V;COND;PL;1
čuoigat	čuoiggažetne	V;POT;DU;1
njallat	njalašeimmet	V;COND;PL;1
hállat	hálašin	V;COND;SG;1
bákŋat	báŋat	V;IND;SG;2;PRS
čeargat	čearggaleigga	V;COND;DU;3;LGSPEC1
áddet	áddejehkos	V;IMP;SG;3
viššat	višašin	V;COND;SG;1
heaŋgut	heŋggošii	V;COND;SG;3
rinčát	rinčájit	V;IND;SG;2;PST
njassat	njasa	V;IMP;SG;2
bávtat	bávtet	V;IND;PL;3;PRS
rinčát	rinčán	V;IND;SG;1;PRS
hállat	hálaža	V;POT;SG;3
buvru	buvrruid	N;GEN;PL
urbi	urbin	N;FRML;SG
njuoskkas	njuoskasa	ADJ;GEN;SG
áibbašit	áibbašivččiidet	V;COND;PL;2
čatnat	čanažat	V;POT;SG;2
skavdut	skavdu	V;IMP;DU;2
guoktelogiviđat	guoktelogiviđadiidda	ADJ;IN+ALL;PL
boahtit	boađálin	V;COND;SG;1;LGSPEC1
suovvabiipu	suovvabiippuid	N;GEN;PL
máksit	mávssášeimmet	V;COND;PL;1
guvrut	guvrruide	V;IND;DU;2;PST
lávgut	lávggoleigga	V;COND;DU;3;LGSPEC1
labmát	labmájedje	V;IND;PL;3;PST
guvrut	guvrubehtet	V;IND;PL;2;PRS
šnjivvat	šnjivažeahppi	V;POT;DU;2
šieđđat	šieđaleidde	V;COND;DU;2;LGSPEC1
lohtat	lođaleigga	V;COND;DU;3;LGSPEC1
ruoidnat	ruoidnabehtet	V;IND;PL;2;PRS
šnjarvát	šnjarvážetne	V;POT;DU;1
láibi	láibbiid	N;ACC;PL
alladávttálaš	alladávttálaččas	ADJ;PRP;SG
láigohit	láigohehket	V;IMP;PL;2
suoskat	suoskkaleidde	V;COND;DU;2;LGSPEC1
gohcut	gozoleimmet	V;COND;PL;1;LGSPEC1
almmáskit	almmáskeažžabeahtti	V;POT;DU;2
jearrat	jearaleigga	V;COND;DU;3;LGSPEC1
čuodjat	čuojale	V;COND;PL;3;LGSPEC1
searvat	searvvalii	V;COND;SG;3;LGSPEC1
vardit	varddeža	V;POT;SG;3
náđđát	náđ'đášeimme	V;COND;DU;1
bealuštit	bealušteadnu	V;IMP;DU;1
dadjat	dajašii	V;COND;SG;3
buotnjut	buotnjubeahtti	V;IND;DU;2;PRS
sárdnut	sárdnos	V;IMP;SG;3
viibat	viibbalin	V;COND;SG;1;LGSPEC1
lávgut	lávggožeaba	V;POT;DU;3
albmanit	albmane	V;IND;PL;3;PST
geargat	gearggažit	V;POT;PL;1
suoibut	suibbuide	V;IND;DU;2;PST
njuvdit	njuvddiimet	V;IND;PL;1;PST
leavvat	leavvá	V;IND;SG;3;PRS
váddut	váddo	V;IND;DU;1;PRS
veadjit	veadjibehtet	V;IND;PL;2;PRS
sehkket	sehkkiimet	V;IND;PL;1;PST
snurkit	snurkke	V;IMP;SG;2
doidit	doiddežit	V;POT;PL;1
čalmmeheamos	čalmmehepmosa	ADJ;GEN;SG
ruššat	rušaleigga	V;COND;DU;3;LGSPEC1
sáddet	sáddeleidde	V;COND;DU;2;LGSPEC1
garcut	garcos	V;IMP;SG;3
čigŋát	čigŋájetnot	V;IMP;PL;1
goaski	goskkiiguin	N;COM;PL
sekšuvdna	sekšuvdnan	N;FRML;SG
butnjat	butnjot	V;IMP;PL;1
aritmetihkka	aritmetihkain	N;PRP;PL
játnat	játnet	V;IND;PL;3;PRS
ohcat	ohcet	V;IMP;PL;2
dálvat	dálvvaime	V;IND;DU;1;PST
skávgat	skávgá	V;IND;SG;3;PRS
doadjit	doajášit	V;COND;SG;2
luddat	ludde	V;IND;DU;1;PRS
gazza	gacca	N;GEN;SG
banána	banánain	N;COM;SG
laskat	lasket	V;IND;SG;2;PST
duhtadit	duhtadeažžat	V;POT;PL;1
muitit	muite	V;IND;PL;3;PST
njoahcut	njozoleigga	V;COND;DU;3;LGSPEC1
čiktit	čivttáleigga	V;COND;DU;3;LGSPEC1
savvit	savežeaba	V;POT;DU;3
avvit	avvos	V;IMP;SG;3
máinnastit	máinnastehket	V;IMP;PL;2
ássat	ásaime	V;IND;DU;1;PST
gártat	gárti	V;IMP;DU;2
vuohttit	vuhtiiga	V;IND;DU;3;PST
iđit	iđidiidda	N;IN+ALL;PL
suhttat	suhtašii	V;COND;SG;3
gillát	gil'láža	V;POT;SG;3
áltár	áltáriid	N;ACC;PL
vuođgŋit	vuđgŋet	V;IMP;PL;2
rinčát	rinčážat	V;POT;SG;2
gohcut	gozuiga	V;IND;DU;3;PST
cuoppu	cubbos	N;PRP;SG
vealtit	vealttáleiddet	V;COND;PL;2;LGSPEC1
dorvvolaš	dorvvolažžii	ADJ;IN+ALL;SG
gohččut	gohččot	V;IND;PL;3;PRS
šloahtta	šloahtaid	N;GEN;PL
konvenšuvdna	konvenšuvnna	N;GEN;SG
šlahttát	šlahttášeimme	V;COND;DU;1
gosahit	gosahehket	V;IMP;PL;2
njuovvat	njuvvet	V;IND;SG;2;PST
čuorgadit	čuorgadeappuin	ADJ;COM;SG
albmudit	albmudeiddet	V;IND;PL;2;PST
njuolgut	njuolgubeahtti	V;IND;DU;2;PRS
vuovdit	vuovddášit	V;COND;SG;2
gáhtat	gáđašit	V;COND;SG;2
báhčit	bážáleimmet	V;COND;PL;1;LGSPEC1
gielddasámegiella	gielddasámegielat	N;NOM;PL
játnat	jánažan	V;POT;SG;1
gohppa	gohpain	N;COM;SG
golggotmánnu	golggotmánu	N;ACC;SG
šibit	šibihiid	N;GEN;PL
astat	asten	V;IND;SG;1;PST
njeazzát	njeazzáleimme	V;COND;DU;1;LGSPEC1
cábmit	cápmáleimmet	V;COND;PL;1;LGSPEC1
njuovvat	njuovalin	V;COND;SG;1;LGSPEC1
vuoiŋŋadit	vuoiŋŋadežžet	V;POT;PL;3
vearju	vearjjut	N;NOM;PL
čoaskát	čoaskábuin	ADJ;COM;SG
váidit	váiddášii	V;COND;SG;3
njurgut	njurgos	V;IMP;SG;3
baste	basttet	N;NOM;PL
ollit	olálii	V;COND;SG;3;LGSPEC1
ceaggát	ceaggába	V;IND;DU;3;PRS
skátnjat	skátnjoset	V;IMP;PL;3
gosahit	gosahivččiidet	V;COND;PL;2
čieskat	čiskoska	V;IMP;DU;3
buldu	buldu	N;NOM;SG
doarjut	dorjoska	V;IMP;DU;3
justit	justtežan	V;POT;SG;1
snoallat	snolle	V;IND;DU;1;PRS
oahppáseamos	oahppásepmosiidda	ADJ;IN+ALL;PL
skátnjat	skánjažit	V;POT;PL;3
varraserum	varraserumiid	N;GEN;PL
sárdnut	sárdnoska	V;IMP;DU;3
assosiašuvdna	assosiašuvdnii	N;IN+ALL;SG
juorbut	jurbbolit	V;COND;SG;2;LGSPEC1
geatki	getkkiid	N;GEN;PL
butnjat	bunjan	V;IND;SG;1;PRS
buollit	buliide	V;IND;DU;2;PST
máinnastit	máinnastivččiidet	V;COND;PL;2
fanas	fatnasis	N;PRP;SG
skirrát	skir'rášeimmet	V;COND;PL;1
máksit	mávssáleiddet	V;COND;PL;2;LGSPEC1
suhttat	suhtaža	V;POT;SG;3
veavvát	veav'vášin	V;COND;SG;1
dáhttut	dáhtolii	V;COND;SG;3;LGSPEC1
vástidit	vástideš	V;POT;SG;3
árgi	árgái	ADJ;IN+ALL;SG
čuožžut	čuččošeimmet	V;COND;PL;1
budjeahtta	budjeahttan	N;FRML;SG
jabbut	jappuide	V;IND;DU;2;PST
čuoggut	čukkošeigga	V;COND;DU;3
višuvdna	višuvnnas	N;PRP;SG
jorbasit	jorbaseappuid	ADJ;GEN;PL
dárustit	dárustivččet	V;COND;SG;2
vuoidat	vuoidi	V;IMP;DU;2
borramuš	borramušain	N;PRP;PL
áiru	áirruin	N;PRP;PL
snuordát	snuordát	V;IND;PL;1;PRS
njeazzát	njeazzán	V;IND;SG;1;PRS
gaivát	gaiváleimme	V;COND;DU;1;LGSPEC1
gossat	gosažetne	V;POT;DU;1
njávkat	njávku	V;IMP;DU;1
vuskkon	vuskkoniiguin	N;COM;PL
čábbe	čáppe	N;ACC;SG
almmáskit	almmáskeš	V;POT;SG;3
gálgat	gálge	V;IND;DU;1;PRS
borrat	boraleiddet	V;COND;PL;2;LGSPEC1
lotnut	lotnoska	V;IMP;DU;3
alihit	aliheappuin	ADJ;PRP;PL
čuođđit	čuođášeimmet	V;COND;PL;1
gossat	gosset	V;IND;PL;3;PRS
háhkat	hágaše	V;COND;PL;3
bára	báraid	N;GEN;PL
njunni	njuniide	N;IN+ALL;PL
posišuvdna	posišuvnnaid	N;GEN;PL
čiehkat	čiegale	V;COND;PL;3;LGSPEC1
speallat	spealašeidde	V;COND;DU;2
liiki	liikkiid	N;ACC;PL
čuoigat	čuigen	V;IND;SG;1;PST
čuohcat	čuozaleigga	V;COND;DU;3;LGSPEC1
buollinolmmái	buollinolbmáid	N;ACC;PL
almmolašvuohta	almmolašvuohtan	N;FRML;SG
bassit	bassibeahtti	V;IND;DU;2;PRS
geallir	geal'lára	N;ACC;SG
buođgát	buođgá	V;IND;SG;3;PRS
gurká	gurkká	N;GEN;SG
šnjivvat	šnjivašeimmet	V;COND;PL;1
gohcut	gohcu	V;IND;SG;3;PRS
čuođđit	čuđežat	V;POT;SG;2
dovdat	dovddalit	V;COND;SG;2;LGSPEC1
náđđut	náđđot	V;IND;PL;3;PRS
gohcut	gozuide	V;IND;DU;2;PST
automatiseret	automatisereža	V;POT;SG;3
akademihkar	akademihkkarii	N;IN+ALL;SG
vielgadit	vielgadeappuide	ADJ;IN+ALL;PL
aldna	alnnain	N;PRP;PL
vuordnut	vuortno	V;IMP;SG;2
čurtát	čurtážetne	V;POT;DU;1
áibat	áibban	V;IND;SG;1;PRS
automatiseret	automatiserelit	V;COND;SG;2;LGSPEC1
njahppit	njahpále	V;COND;PL;3;LGSPEC1
máistit	máisttášii	V;COND;SG;3
čalán	čalámiin	N;PRP;PL
duogŋat	duokŋaiga	V;IND;DU;3;PST
cáhkit	cágálit	V;COND;SG;2;LGSPEC1
álgit	álggále	V;COND;PL;3;LGSPEC1
siigat	siiggaide	V;IND;DU;2;PST
boahtit	bođežetne	V;POT;DU;1
akademiija	akademiija	N;NOM;SG
vuohpput	vuhppot	V;IND;PL;3;PRS
rustát	rustábehtet	V;IND;PL;2;PRS
advearba	advearbbaid	N;GEN;PL
ealihit	ealiheiddet	V;IND;PL;2;PST
sekšuvdna	sekšuvnnaid	N;GEN;PL
juksat	juvssažat	V;POT;SG;2
oattit	oattibus	ADJ;PRP;SG
rážžat	ráččašeimme	V;COND;DU;1
njuovvat	njuovaža	V;POT;SG;3
šnjuoggát	šnjuoggájehkoset	V;IMP;PL;3
čurtát	čurtáše	V;COND;PL;3
čoarrát	čoar'ráleiddet	V;COND;PL;2;LGSPEC1
deakčut	devččole	V;COND;PL;3;LGSPEC1
vuollat	vuolaidet	V;IND;PL;2;PST
vázzit	váccežehpet	V;POT;PL;2
juksat	juvssažeahppi	V;POT;DU;2
guoktelogigávccát	guoktelogigávccádii	ADJ;IN+ALL;SG
gurdit	gurddeža	V;POT;SG;3
čakčamánnu	čakčamánus	N;PRP;SG
sadjit	sajášeimme	V;COND;DU;1
šiega	šigii	ADJ;IN+ALL;SG
jierbmat	jierpmašeimmet	V;COND;PL;1
jorrat	jorros	V;IMP;SG;3
luohttit	luohttá	V;IND;SG;3;PRS
guoktelogiguđat	guoktelogiguđada	ADJ;ACC;SG
vuohttit	vuhteža	V;POT;SG;3
reavvat	reavat	V;IND;SG;2;PRS
čieskat	čiskot	V;IMP;PL;1
vašálit	vašáleappuid	ADJ;ACC;PL
buođgát	buođgážit	V;POT;PL;1
readnját	readnjáleigga	V;COND;DU;3;LGSPEC1
šohkut	šoguimet	V;IND;PL;1;PST
jáhkkit	jáhkkit	V;IND;PL;1;PRS
ohcat	ozaleiddet	V;COND;PL;2;LGSPEC1
čierastit	čierasteažžaba	V;POT;DU;3
vuordit	vuorddášeidde	V;COND;DU;2
garcut	garccoše	V;COND;PL;3
čiktit	čiktet	V;IND;SG;2;PST
loktit	lovttášeimme	V;COND;DU;1
luokčat	luokčabehtet	V;IND;PL;2;PRS
dáidit	dáiddálin	V;COND;SG;1;LGSPEC1
ruoŧŧa	ruoŧŧa	N;NOM;SG
niitit	niitibeahtti	V;IND;DU;2;PRS
boahtit	boađáleigga	V;COND;DU;3;LGSPEC1
deaššat	deašalin	V;COND;SG;1;LGSPEC1
vuohttit	vuhtežeaba	V;POT;DU;3
miessemánnu	miessemánus	N;PRP;SG
háhkat	hágažetne	V;POT;DU;1
hihttát	hihttájedje	V;IND;PL;3;PST
čáskat	čáskkaža	V;POT;SG;3
rávkat	rávkkažeahppi	V;POT;DU;2
moardit	mordos	V;IMP;SG;3
buollát	buol'lálin	V;COND;SG;1;LGSPEC1
čavggat	čavggabui	ADJ;IN+ALL;SG
báidnit	báinnášit	V;COND;SG;2
áhčči	áhčis	N;PRP;SG
vuoitit	vuitteža	V;POT;SG;3
lákca	lávccas	N;PRP;SG
báitit	báittežan	V;POT;SG;1
spálčát	spálčái	V;IND;SG;3;PST
geahččat	geahčaide	V;IND;DU;2;PST
dolastaddat	dolastattaleigga	V;COND;DU;3;LGSPEC1
njeazzát	njeazzáleimmet	V;COND;PL;1;LGSPEC1
luddat	luttai	V;IND;SG;3;PST
joahcat	johcoset	V;IMP;PL;3
máltit	málttežeahppi	V;POT;DU;2
máltit	málton	V;IMP;SG;1
dápmat	dáman	V;IND;SG;1;PRS
ceggoseamos	ceggosepmosiin	ADJ;PRP;PL
reahkut	regoža	V;POT;SG;3
muitit	muitte	V;IMP;SG;2
geatki	geatki	N;NOM;SG
speallat	spealaimet	V;IND;PL;1;PST
vuodjut	vuojun	V;IND;SG;1;PRS
boatkanit	boatkane	V;IND;PL;3;PST
gieđbmi	gieđmmi	N;ACC;SG
gággat	gákkašeidde	V;COND;DU;2
hárcut	hárccoleimmet	V;COND;PL;1;LGSPEC1
hahppit	hahpáleimmet	V;COND;PL;1;LGSPEC1
iras	irrasiin	ADJ;COM;SG
smiehttat	smiehtaleimme	V;COND;DU;1;LGSPEC1
vuordnut	vurtnoleiddet	V;COND;PL;2;LGSPEC1
gotka	gotkkaid	N;ACC;PL
alkohola	alkoholan	N;FRML;SG
gávdnat	gávnnaleigga	V;COND;DU;3;LGSPEC1
goardit	goardiba	V;IND;DU;3;PRS
násti	násti	N;NOM;SG
diktit	dikte	V;IND;PL;3;PST
váddut	váddos	V;IMP;SG;3
gossat	gosset	V;IND;SG;2;PST
rávkat	rávket	V;IND;PL;3;PRS
šohkut	šohkoset	V;IMP;PL;3
bardit	barddán	V;IND;SG;1;PRS
riessat	riesaleimmet	V;COND;PL;1;LGSPEC1
luohti	luđiid	N;ACC;PL
sistat	sistá	V;IND;SG;3;PRS
náđđát	náđ'đážehpet	V;POT;PL;2
dálvat	dálve	V;IND;DU;1;PRS
labmát	labmájehkoset	V;IMP;PL;3
plastihkka	plastihkka	N;NOM;SG
cuvket	cuvkešeiddet	V;COND;PL;2
dorvvastit	dorvvastehkot	V;IMP;PL;1
áibat	áibbašeidde	V;COND;DU;2
gáddit	gáttii	V;IND;SG;3;PST
máltit	máltet	V;IMP;PL;2
badji	baji	N;ACC;SG
váddut	váddubeahtti	V;IND;DU;2;PRS
njuolgut	njulggoše	V;COND;PL;3
heaibut	heibbožehpet	V;POT;PL;2
báidnit	báinnáleidde	V;COND;DU;2;LGSPEC1
miehtat	mihtot	V;IMP;PL;1
jalkát	jalkážeaba	V;POT;DU;3
čuovgadit	čuovgadeappuid	ADJ;ACC;PL
ajihustit	ajihustá	V;IND;SG;3;PRS
gohcut	gozuimet	V;IND;PL;1;PST
guolbmat	guolmmalii	V;COND;SG;3;LGSPEC1
časkit	časkkáleimmet	V;COND;PL;1;LGSPEC1
báhcit	bázii	V;IND;SG;3;PST
čeaksa	čeavssain	N;PRP;PL
jearrat	jearašit	V;COND;SG;2
káffe	káfe	N;ACC;SG
amastit	amastehpet	V;IND;PL;2;PRS
dassat	dasaleimme	V;COND;DU;1;LGSPEC1
snurkit	snurkkežetne	V;POT;DU;1
juohkit	juhken	V;IND;SG;1;PST
vuohpput	vuhpožetne	V;POT;DU;1
doapmat	doapmabehtet	V;IND;PL;2;PRS
gođđat	gođaleigga	V;COND;DU;3;LGSPEC1
boazu	bohccos	N;PRP;SG
málli	máliid	N;GEN;PL
mearra	mearaid	N;GEN;PL
oallut	oluiga	V;IND;DU;3;PST
čuolbma	čuolmma	N;GEN;SG
čábbut	čáppošin	V;COND;SG;1
automatiseret	automatisereleimmet	V;COND;PL;1;LGSPEC1
dievvaseamos	dievvasepmosii	ADJ;IN+ALL;SG
gaikut	gaikkuime	V;IND;DU;1;PST
gártat	gárttaleigga	V;COND;DU;3;LGSPEC1
nuondat	nuondaba	V;IND;DU;3;PRS
baján	bajána	N;GEN;SG
sihkkut	sihkoleidde	V;COND;DU;2;LGSPEC1
butnjat	bunjažit	V;POT;PL;3
sarcut	sarccožeahppi	V;POT;DU;2
justit	justtežit	V;POT;PL;3
sruva	sruvat	N;NOM;PL
arggit	arggibu	ADJ;GEN;SG
anihit	anihehkon	V;IMP;SG;1
stálli	stáliiguin	N;COM;PL
ađahuvvat	ađahuvašeigga	V;COND;DU;3
salgat	salggai	V;IND;SG;3;PST
njiellat	njielašit	V;COND;SG;2
duogŋat	duokŋažit	V;POT;PL;1
skuvladállu	skuvladálu	N;GEN;SG
dárustit	dárustit	V;IND;SG;2;PST
dieigut	diiggožetne	V;POT;DU;1
savvit	sav'vi	V;IMP;DU;2
šohkut	šohkon	V;IMP;SG;1
buokčat	buovččaše	V;COND;PL;3
čurtát	čurtášeiddet	V;COND;PL;2
ruoksadeamos	ruoksadepmosa	ADJ;ACC;SG
ceaggát	ceaggášeimmet	V;COND;PL;1
illu	illui	N;IN+ALL;SG
šnjivvat	šnjivvet	V;IMP;PL;2
gohcit	gozežan	V;POT;SG;1
čiktit	čivttežat	V;POT;SG;2
seaktit	sevttežit	V;POT;PL;3
básár	básáriin	N;COM;SG
botnjat	bonjat	V;IND;SG;2;PRS
skávgat	skávggat	V;IND;SG;2;PRS
dálvat	dálvvalii	V;COND;SG;3;LGSPEC1
bilbut	bilbbožat	V;POT;SG;2
haddi	hattiid	N;GEN;PL
anárašgiella	anárašgiela	N;ACC;SG
čuoigát	čuoigážetne	V;POT;DU;1
gáivo	gáivui	N;IN+ALL;SG
giektat	gievttai	V;IND;SG;3;PST
čitnut	činožetne	V;POT;DU;1
čieskat	čieskkašit	V;COND;SG;2
vealtit	velttiide	V;IND;DU;2;PST
garcut	garccoleiddet	V;COND;PL;2;LGSPEC1
ceaggát	ceaggáime	V;IND;DU;1;PST
diktit	divttežetne	V;POT;DU;1
boahtit	bohtet	V;IND;SG;2;PST
basahit	basahii	V;IND;SG;3;PST
guostát	guostáža	V;POT;SG;3
cuovkanit	cuovkanivččii	V;COND;SG;3
dieigut	diigot	V;IMP;PL;1
sirgŋat	sirkŋažehpet	V;POT;PL;2
aji	aji	N;NOM;SG
albmanit	albmaneažžabeahtti	V;POT;DU;2
vuoigŋa	vuoiŋŋaide	N;IN+ALL;PL
vuolli	vuliin	N;PRP;PL
budjeahtta	budjeahtaid	N;GEN;PL
uhcit	uhcibun	ADJ;FRML;SG
gohcut	gohccu	V;IMP;DU;2
guostát	guostájeahkki	V;IMP;DU;2
čuoigat	čuoigu	V;IMP;DU;1
guoktelogičihččet	guoktelogičihččedis	ADJ;PRP;SG
gažahit	gažaha	V;IND;SG;3;PRS
beastit	beastiba	V;IND;DU;3;PRS
duhtadit	duhtadivččiimet	V;COND;PL;1
automatiseret	automatisereleimme	V;COND;DU;1;LGSPEC1
njassat	njasažit	V;POT;PL;3
váddut	váttošeimme	V;COND;DU;1
váidit	váidoska	V;IMP;DU;3
dapmi	dapmin	N;FRML;SG
doaivut	doaivuba	V;IND;DU;3;PRS
goallut	goložehpet	V;POT;PL;2
anihit	aniheimme	V;IND;DU;1;PST
gohpat	gobale	V;COND;PL;3;LGSPEC1
konklušuvdna	konklušuvnnat	N;NOM;PL
olju	oljjuid	N;ACC;PL
almmaiduvvat	almmaiduvvaba	V;IND;DU;3;PRS
goargŋut	gorkŋuime	V;IND;DU;1;PST
vuordit	vurddežit	V;POT;PL;3
seavvit	seave	V;IMP;SG;2
njukčamánnu	njukčamánnu	N;NOM;SG
doaibat	doaibban	V;IND;SG;1;PRS
čitnut	činolit	V;COND;SG;2;LGSPEC1
divri	divrrit	N;NOM;PL
goardit	goarddále	V;COND;PL;3;LGSPEC1
gildát	gildážehpet	V;POT;PL;2
garvit	garvvát	V;IND;SG;2;PRS
vuordit	vuorddáleiddet	V;COND;PL;2;LGSPEC1
automatiseret	automatiserešeiddet	V;COND;PL;2
šnjarvát	šnjarvájit	V;IND;PL;3;PRS
adopteret	adoptereleimme	V;COND;DU;1;LGSPEC1
stađđat	stađalit	V;COND;SG;2;LGSPEC1
skátnjat	skánjale	V;COND;PL;3;LGSPEC1
gordni	gortniiguin	N;COM;PL
ruosta	ruostan	N;FRML;SG
gárrat	gáražan	V;POT;SG;1
čuoldit	čulddežat	V;POT;SG;2
áktit	ávttiiga	V;IND;DU;3;PST
čeargat	čerget	V;IND;PL;3;PRS
báitit	báitte	V;IMP;SG;2
searvat	searvaba	V;IND;DU;3;PRS
buhtis	buhttása	ADJ;GEN;SG
čorgadit	čorgadeappuin	ADJ;COM;SG
čuovggahit	čuovggaha	V;IND;SG;3;PRS
gahppat	gahpaimet	V;IND;PL;1;PST
rážžat	ráččaidet	V;IND;PL;2;PST
geahččat	geahčaleiddet	V;COND;PL;2;LGSPEC1
riitát	riitábehtet	V;IND;PL;2;PRS
borga	borggain	N;PRP;PL
jurdit	jurdde	V;IMP;SG;2
ivdnet	ivdnet	V;IND;PL;1;PRS
giron	gironiid	N;GEN;PL
duhtadit	duhtadeš	V;POT;SG;3
máinnastit	máinnas	V;IMP;SG;2
bávtat	bávttašii	V;COND;SG;3
mielki	mielkkis	N;PRP;SG
cealkit	cealkkášeimmet	V;COND;PL;1
juolgat	julge	V;IND;DU;1;PRS
njuordat	njurdot	V;IMP;PL;1
báidnit	báinnáleigga	V;COND;DU;3;LGSPEC1
oaidnit	oinnežeahppi	V;POT;DU;2
giektat	giktoska	V;IMP;DU;3
gájot	gájogii	N;IN+ALL;SG
ovccinuppelogát	ovccinuppelogát	ADJ;NOM;SG
vuoitit	vuoittáleimme	V;COND;DU;1;LGSPEC1
sárrat	sárai	V;IND;SG;3;PST
borgemánnu	borgemánuide	N;IN+ALL;PL
eadnáde	eatnist	N;PRP;SG
háhccát	háhccáleimmet	V;COND;PL;1;LGSPEC1
njahppit	njahpáleimme	V;COND;DU;1;LGSPEC1
doadjit	doajáleimmet	V;COND;PL;1;LGSPEC1
duogŋat	duokŋalii	V;COND;SG;3;LGSPEC1
duođamus	duođamus	ADJ;NOM;SG
addjohit	addjoheahkki	V;IMP;DU;2
friddja	friddjaid	ADJ;GEN;PL
gastit	gasttáleidde	V;COND;DU;2;LGSPEC1
muhttit	muhtežeahppi	V;POT;DU;2
aresteret	arestereleiddet	V;COND;PL;2;LGSPEC1
njuoskat	njuske	V;IND;PL;3;PST
boahtit	boahtit	V;IND;PL;1;PRS
bákŋat	bákŋoska	V;IMP;DU;3
vuorkut	vuorkuba	V;IND;DU;3;PRS
leandit	lendot	V;IMP;PL;1
čállit	čálášeidde	V;COND;DU;2
vuoidat	vuoiddaža	V;POT;SG;3
vuola	vuollagiin	N;COM;SG
eadnádet	etniideattetguin	N;COM;PL
čállit	čálálii	V;COND;SG;3;LGSPEC1
dassat	dassaba	V;IND;DU;3;PRS
beahkit	beagáleigga	V;COND;DU;3;LGSPEC1
iđitgákti	iđitgákti	N;NOM;SG
doaimmalaš	doaimmalaš	ADJ;NOM;SG
jalkát	jalkášeimmet	V;COND;PL;1
lahpat	lahpat	V;IND;PL;1;PRS
almmuhit	almmuhivčče	V;COND;PL;3
njávkat	njávkon	V;IMP;SG;1
čuođát	čuođádii	ADJ;IN+ALL;SG
fasána	fasánan	N;FRML;SG
garcut	garccoleigga	V;COND;DU;3;LGSPEC1
bomba	bombbain	N;PRP;PL
vuoiŋŋadit	vuoiŋŋadivččiidet	V;COND;PL;2
oakti	oakti	N;NOM;SG
spálčát	spálčálit	V;COND;SG;2;LGSPEC1
bohkat	bohkot	V;IMP;PL;1
oaggut	okkošeimme	V;COND;DU;1
márfi	márffit	N;NOM;PL
divvut	divošeidde	V;COND;DU;2
áhtat	áhtaba	V;IND;DU;3;PRS
loahppat	loahpažat	V;POT;SG;2
institušuvdna	institušuvnnain	N;PRP;PL
čalán	čalámii	N;IN+ALL;SG
gaivát	gaiváime	V;IND;DU;1;PST
láhppit	láhppet	V;IND;PL;3;PRS
readnját	readnjážit	V;POT;PL;3
beana	beatnagat	N;NOM;PL
čuolbma	čuolmmaiguin	N;COM;PL
giektat	gievtta	V;IMP;SG;2
leavvat	levvoska	V;IMP;DU;3
albbas	albbas	N;NOM;SG
ruoksát	ruoksájeadnu	V;IMP;DU;1
gokčat	govččaide	V;IND;DU;2;PST
divvut	divvos	V;IMP;SG;3
deallut	delui	V;IND;SG;3;PST
bilbut	bilbbuimet	V;IND;PL;1;PST
vuohttit	vuhtton	V;IMP;SG;1
duohta	duođa	ADJ;ACC;SG
dárustit	dárusteimmet	V;IND;PL;1;PST
čuohkat	čuogažat	V;POT;SG;2
gohcit	gozášeimme	V;COND;DU;1
juohkit	jugežeahppi	V;POT;DU;2
loavdda	loavdagiiguin	N;COM;PL
oallut	oallubeahtti	V;IND;DU;2;PRS
njuolgut	njulggolii	V;COND;SG;3;LGSPEC1
gaškát	gaškážit	V;POT;PL;1
vázzit	vázzá	V;IND;SG;3;PRS
gohpat	gohpaba	V;IND;DU;3;PRS
skavdut	skavdot	V;IMP;PL;2
sustit	susttálii	V;COND;SG;3;LGSPEC1
gávdnat	gávdne	V;IND;DU;1;PRS
juohkit	juohkit	V;IND;PL;1;PRS
láigohit	láigohivččii	V;COND;SG;3
áhkkilsámegiella	áhkkilsámegielaid	N;ACC;PL
gággat	gággat	V;IND;PL;1;PRS
dáidu	dáidduid	N;GEN;PL
siigat	siiggalit	V;COND;SG;2;LGSPEC1
vuoitit	vuittežeahppi	V;POT;DU;2
oallut	oalluba	V;IND;DU;3;PRS
ganjal	ganjal	N;NOM;SG
bardit	barddáleiddet	V;COND;PL;2;LGSPEC1
doadjit	dojiimet	V;IND;PL;1;PST
giektat	gievttan	V;IND;SG;1;PRS
bákti	bávttiin	N;COM;SG
čiehkat	čiegažan	V;POT;SG;1
vealgut	velggošit	V;COND;SG;2
vuollat	vuolažit	V;POT;PL;3
adnostit	adnostivččiidet	V;COND;PL;2
ruoŧŧa	ruoŧas	N;PRP;SG
perspektiiva	perspektiivvain	N;COM;SG
oastit	osttiidet	V;IND;PL;2;PST
buoidivuohta	buoidivuođa	N;GEN;SG
njanzát	njanzážit	V;POT;PL;1
áktit	áktet	V;IND;PL;3;PRS
dáhttut	dáhtoleidde	V;COND;DU;2;LGSPEC1
šnjuoggát	šnjuoggálii	V;COND;SG;3;LGSPEC1
gohpat	gohppi	V;IMP;DU;2
dadjat	dajažeahppi	V;POT;DU;2
gurdit	gurdot	V;IMP;PL;1
čeargut	čeargubeahtti	V;IND;DU;2;PRS
doaimmahit	doaimmaheahkki	V;IMP;DU;2
gáhkku	gáhkuiguin	N;COM;PL
jorrat	joralit	V;COND;SG;2;LGSPEC1
njoarrat	njoarrabeahtti	V;IND;DU;2;PRS
čiežanuppelogát	čiežanuppelogádiin	ADJ;PRP;PL
ohcat	ozale	V;COND;PL;3;LGSPEC1
gilvit	gilvváleimmet	V;COND;PL;1;LGSPEC1
ordi	orddi	N;GEN;SG
rušpi	rušppiid	N;ACC;PL
beaŋka	beaŋkan	N;FRML;SG
sárrat	sáražan	V;POT;SG;1
čiekŋaleamos	čiekŋalepmosiid	ADJ;ACC;PL
loddi	lottiid	N;ACC;PL
suovvabiipu	suovvabiippu	N;GEN;SG
šnjirgut	šnjirgu	V;IND;SG;3;PRS
beaivváš	beaivvážii	N;IN+ALL;SG
gilvit	gilvváleidde	V;COND;DU;2;LGSPEC1
suoggat	suokkai	V;IND;SG;3;PST
gildát	gildáleidde	V;COND;DU;2;LGSPEC1
vuođgŋit	vuođŋŋášeimme	V;COND;DU;1
máinnastit	máinnastivččii	V;COND;SG;3
leandit	leanddášin	V;COND;SG;1
varra	vara	N;GEN;SG
gohččut	gohčču	V;IMP;DU;1
riitát	riitážat	V;POT;SG;2
dárustit	dáruste	V;IND;PL;3;PST
fasána	fasánaiguin	N;COM;PL
bárrastávvalsátni	bárrastávvalsátnái	N;IN+ALL;SG
čatnat	čanaleigga	V;COND;DU;3;LGSPEC1
muohttit	muhtežan	V;POT;SG;1
ruššat	ruš'šu	V;IMP;DU;1
goallát	goal'lájehkoset	V;IMP;PL;3
nuollat	nuolaleiddet	V;COND;PL;2;LGSPEC1
hivssetbábir	hivssetbábiris	N;PRP;SG
johtit	jođále	V;COND;PL;3;LGSPEC1
sárgut	sárgot	V;IND;SG;2;PST
klubba	klubban	N;FRML;SG
gaivát	gaiváleimmet	V;COND;PL;1;LGSPEC1
eadnámet	eadnineamet	N;FRML;SG
buođđut	buđolii	V;COND;SG;3;LGSPEC1
doapmat	dopmon	V;IMP;SG;1
ađa	ađa	N;NOM;SG
siigat	siiggažeaba	V;POT;DU;3
alva	alvvain	N;COM;SG
riessat	riesaimet	V;IND;PL;1;PST
vahcut	vazoža	V;POT;SG;3
oažžut	oččuidet	V;IND;PL;2;PST
goallut	goallubeahtti	V;IND;DU;2;PRS
vuoidat	vuide	V;IND;DU;1;PRS
skavdut	skavddui	V;IND;SG;3;PST
adopteret	adopterelit	V;COND;SG;2;LGSPEC1
dolastaddat	dolastattat	V;IND;SG;2;PRS
čuoika	čuoikkain	N;PRP;PL
dárustit	dárustivččiide	V;COND;DU;2
oaidnit	oaidná	V;IND;SG;3;PRS
reavgit	reavgu	V;IMP;DU;1
sihkkut	sihkku	V;IMP;DU;1
jorrat	joraiga	V;IND;DU;3;PST
njeazzát	njeazzážan	V;POT;SG;1
čuorgadeamos	čuorgadepmosat	ADJ;NOM;PL
biologa	biologaiguin	N;COM;PL
báidnit	báinneža	V;POT;SG;3
seavvit	seavvá	V;IND;SG;3;PRS
apostal	apostaliid	N;GEN;PL
diktit	divttán	V;IND;SG;1;PRS
bustávva	bustávva	N;NOM;SG
gággat	gákkašeiddet	V;COND;PL;2
šlundut	šlundot	V;IND;SG;2;PST
gohppa	gohppa	N;NOM;SG
báhcit	bázálii	V;COND;SG;3;LGSPEC1
smiehttat	smiehtašii	V;COND;SG;3
coakcut	covccuidet	V;IND;PL;2;PST
dáidit	dáidibeahtti	V;IND;DU;2;PRS
ruohttat	ruohttu	V;IMP;DU;1
nuollat	nuollat	V;IND;PL;1;PRS
ráhkistuvvat	ráhkistuvažit	V;POT;PL;1
njoarrat	njorre	V;IND;PL;3;PST
ahkiduššat	ahkidušan	V;IND;SG;1;PRS
sárdnut	sárdnu	V;IMP;DU;2
riessat	riesašii	V;COND;SG;3
ajihuvvat	ajihuvvabehtet	V;IND;PL;2;PRS
bohčit	bohče	V;IND;PL;3;PST
sálti	sálttiid	N;ACC;PL
báhčit	bážiidet	V;IND;PL;2;PST
cáhpat	cábaidet	V;IND;PL;2;PST
ruodjat	ruodjabehtet	V;IND;PL;2;PRS
jierbmat	jierpmažan	V;POT;SG;1
vuodjat	vuojažehpet	V;POT;PL;2
vealgut	velgoska	V;IMP;DU;3
cuollat	cuollabehtet	V;IND;PL;2;PRS
cealkit	cealkkáleimme	V;COND;DU;1;LGSPEC1
buohccát	buohccájit	V;IND;SG;2;PST
savvit	savvá	V;IND;SG;3;PRS
šleambit	šlembbežeaba	V;POT;DU;3
muhttit	muhttoset	V;IMP;PL;3
joavdat	jovden	V;IND;SG;1;PST
njuovvat	njuovaide	V;IND;DU;2;PST
gávri	gávrriid	N;GEN;PL
reavri	reavrrit	N;NOM;PL
adopteret	adopterešeidde	V;COND;DU;2
máksit	máksos	V;IMP;SG;3
duohta	duođat	ADJ;NOM;PL
duostat	duosttaleimmet	V;COND;PL;1;LGSPEC1
riitát	riitájeahkki	V;IMP;DU;2
njurgut	njurggožit	V;POT;PL;1
dovdat	dovdabehtet	V;IND;PL;2;PRS
duogŋat	duokŋašeigga	V;COND;DU;3
čuohcat	čuozažat	V;POT;SG;2
muoŧŧá	muoŧáid	N;ACC;PL
gopmat	gopmon	V;IMP;SG;1
čáskat	čáske	V;IND;DU;1;PRS
čeavrris	čeavráid	N;ACC;PL
gažahit	gažaheažžabeahtti	V;POT;DU;2
báhcit	bázášeigga	V;COND;DU;3
cuovkanit	cuovkanivččiide	V;COND;DU;2
lihtter	lihtteriin	N;PRP;PL
geahčastallat	geahčastallen	V;IND;SG;1;PST
čakčamánnu	čakčamánuid	N;GEN;PL
máinnastit	máinnasteažžabeahtti	V;POT;DU;2
šnjarvát	šnjarvábeahtti	V;IND;DU;2;PRS
bárru	bárrui	N;IN+ALL;SG
vuodjat	vuojašeimme	V;COND;DU;1
cáhpat	cábaimet	V;IND;PL;1;PST
geahččat	geahčaše	V;COND;PL;3
čuođđit	čuđežeahppi	V;POT;DU;2
cuvket	cuvkejit	V;IND;PL;3;PRS
buollit	buležat	V;POT;SG;2
sirdát	sirdái	V;IND;SG;3;PST
njalgat	njalggaleigga	V;COND;DU;3;LGSPEC1
goahcat	goazaiga	V;IND;DU;3;PST
gámme	gám'mii	N;IN+ALL;SG
konvenšuvdna	konvenšuvnnain	N;PRP;PL
avvit	avven	V;IND;SG;1;PST
speadjal	speadjal	N;NOM;SG
moddját	moddjálit	V;COND;SG;2;LGSPEC1
geafi	gefiid	ADJ;GEN;PL
friddja	friddja	ADJ;NOM;SG
roahttu	roahtuide	N;IN+ALL;PL
čuovgadit	čuovgadeappuide	ADJ;IN+ALL;PL
bordit	borddálit	V;COND;SG;2;LGSPEC1
jabbut	jappolii	V;COND;SG;3;LGSPEC1
savvit	sav'vu	V;IMP;DU;1
albmanit	albmaneadnu	V;IMP;DU;1
almmuhit	almmuhivččiidet	V;COND;PL;2
čáhppadit	čáhppadeappuide	ADJ;IN+ALL;PL
sadjit	sajiiga	V;IND;DU;3;PST
automáhtta	automáhttii	N;IN+ALL;SG
buvtta	buvttan	N;FRML;SG
lohtat	lohte	V;IND;DU;1;PRS
njallat	njallot	V;IMP;PL;1
dáhttut	dáhttos	V;IMP;SG;3
gohcit	gozáleiddet	V;COND;PL;2;LGSPEC1
čeargut	čearggun	V;IND;SG;1;PRS
šibit	šibihat	N;NOM;PL
gildát	gildát	V;IND;PL;1;PRS
gáddit	gáddoset	V;IMP;PL;3
viššat	višaleiddet	V;COND;PL;2;LGSPEC1
ceggoseamos	ceggosepmosa	ADJ;GEN;SG
avvit	avvet	V;IND;PL;3;PRS
aresteret	aresterelit	V;COND;SG;2;LGSPEC1
doaimmalaš	doaimmalaččain	ADJ;COM;SG
sárrat	sárašeidde	V;COND;DU;2
áibat	áibbažehpet	V;POT;PL;2
cáhkit	cágežehpet	V;POT;PL;2
sadjit	saježat	V;POT;SG;2
doahput	dobuiga	V;IND;DU;3;PST
uhcit	uhcibu	ADJ;GEN;SG
ruskat	rusket	V;IND;SG;2;PST
viežžat	viečča	V;IMP;SG;2
časkit	časkkežat	V;POT;SG;2
goaikut	goikoska	V;IMP;DU;3
buvtta	buktagiid	N;ACC;PL
gilvit	gilvviide	V;IND;DU;2;PST
gággat	gágge	V;IND;PL;3;PST
artista	artisttaid	N;GEN;PL
vuohpput	vuhpožat	V;POT;SG;2
ruškadeamos	ruškadeamosin	ADJ;FRML;SG
goarrut	goarrubehtet	V;IND;PL;2;PRS
rievdat	rievddaidet	V;IND;PL;2;PST
giektat	gikton	V;IMP;SG;1
oaidnit	oinnežehpet	V;POT;PL;2
duostut	duston	V;IND;SG;1;PST
fuotni	fuotnái	ADJ;IN+ALL;SG
ráigi	ráiggi	N;ACC;SG
sadjit	sajálin	V;COND;SG;1;LGSPEC1
ivdnet	ivdnežat	V;POT;SG;2
áibbašit	áibbašan	V;IND;SG;1;PRS
hieibmat	hieimmažetne	V;POT;DU;1
oliiva	oliivvas	N;PRP;SG
artista	artisttain	N;COM;SG
jearahit	jearaheimmet	V;IND;PL;1;PST
hárcut	hárccuide	V;IND;DU;2;PST
bánedoavttir	bánedoaktára	N;ACC;SG
bilidit	bilidetne	V;IND;DU;1;PRS
borgárvuohta	borgárvuođaid	N;ACC;PL
reahkut	regožetne	V;POT;DU;1
rievdat	rievddaleimmet	V;COND;PL;1;LGSPEC1
láigohit	láigohivččet	V;COND;SG;2
sárgut	sárggožat	V;POT;SG;2
hárdu	hárdduiguin	N;COM;PL
rávkat	rávkaba	V;IND;DU;3;PRS
buolláhit	buol'láhetne	V;IND;DU;1;PRS
gurdit	gurddán	V;IND;SG;1;PRS
suddit	suttáleimme	V;COND;DU;1;LGSPEC1
logát	logádii	ADJ;IN+ALL;SG
dálvat	dálvá	V;IND;SG;3;PRS
fárru	fáru	N;GEN;SG
fuobmát	fuobmájetne	V;IND;DU;1;PRS
aski	aski	N;NOM;SG
gohpat	gobaimet	V;IND;PL;1;PST
bákŋat	báŋaiga	V;IND;DU;3;PST
vuovdit	vuvddežehpet	V;POT;PL;2
oalul	olloliiguin	N;COM;PL
guvrut	guvrroše	V;COND;PL;3
gahppat	gahppat	V;IND;PL;1;PRS
admirála	admirála	N;NOM;SG
njohcut	njozoleimmet	V;COND;PL;1;LGSPEC1
giron	gironii	N;IN+ALL;SG
čábbámus	čábbámusa	ADJ;GEN;SG
bavssa	baksama	N;ACC;SG
fasána	fasánain	N;PRP;PL
ássat	ássoska	V;IMP;DU;3
vielgadit	vielgadeabbon	ADJ;FRML;SG
alkohola	alkoholat	N;NOM;PL
časkit	časkkášin	V;COND;SG;1
čavgadeamos	čavgadepmosii	ADJ;IN+ALL;SG
reahkut	rehkot	V;IND;SG;2;PST
ravgat	ravggai	V;IND;SG;3;PST
oaddi	ottiin	ADJ;PRP;PL
savvit	saváleiddet	V;COND;PL;2;LGSPEC1
ustit	ustibin	N;FRML;SG
deháleamos	dehálepmosiin	ADJ;COM;SG
sárdnut	sárdnot	V;IMP;PL;2
baika	baikkain	N;COM;SG
gohcut	gozožat	V;POT;SG;2
buoidut	buiddošii	V;COND;SG;3
bláđet	bláđešeidde	V;COND;DU;2
ubmisámegiella	ubmisámegiellan	N;FRML;SG
čuodjat	čudjon	V;IMP;SG;1
lohkat	lohkabehtet	V;IND;PL;2;PRS
bealuštit	bealuštehkoset	V;IMP;PL;3
njalgat	njalggaimet	V;IND;PL;1;PST
buokčat	buovččašeiddet	V;COND;PL;2
vuoitit	vuoittášii	V;COND;SG;3
almmáskit	almmáskehkot	V;IMP;PL;1
čalmmeheamos	čalmmehepmosis	ADJ;PRP;SG
jorrat	jorre	V;IND;PL;3;PST
girji	girjái	N;IN+ALL;SG
čeŋkkeš	čeŋkkeža	N;GEN;SG
gealdit	gelden	V;IND;SG;1;PST
duogŋat	duokŋaime	V;IND;DU;1;PST
roggat	rokkat	V;IND;SG;2;PRS
suolu	sulluin	N;COM;SG
rustát	rustáiga	V;IND;DU;3;PST
njeazzát	njeazzáleiddet	V;COND;PL;2;LGSPEC1
eallaseamos	eallasepmosiidda	ADJ;IN+ALL;PL
beahttit	beahtášeidde	V;COND;DU;2
čuohkat	čuogale	V;COND;PL;3;LGSPEC1
lávlut	lávlložit	V;POT;PL;1
guvrut	guvrrolit	V;COND;SG;2;LGSPEC1
bassit	basáleimmet	V;COND;PL;1;LGSPEC1
assi	assi	N;NOM;SG
dutkat	dutkkaleimmet	V;COND;PL;1;LGSPEC1
njaldit	njalde	V;IND;DU;1;PRS
gaikut	gaikkošeigga	V;COND;DU;3
váddut	váttožit	V;POT;PL;1
huhpat	hubažat	V;POT;SG;2
dorvvolaččat	dorvvolaččabus	ADJ;PRP;SG
váldit	váldu	V;IMP;DU;1
árbi	árbbiin	N;COM;SG
čoarrát	čoar'rájin	V;IND;SG;1;PST
báron	bároniid	N;GEN;PL
šaddu	šattuide	N;IN+ALL;PL
gilvit	gilvve	V;IMP;SG;2
boija	boijaiguin	N;COM;PL
suoibut	suoibbut	V;IND;SG;2;PRS
njaldit	njalddášii	V;COND;SG;3
šnjivvat	šnjivai	V;IND;SG;3;PST
sihkkut	sihkožeaba	V;POT;DU;3
báitit	báitet	V;IND;SG;2;PST
albmanit	albmaneimme	V;IND;DU;1;PST
čearguladdat	čeargulattažetne	V;POT;DU;1
oahppat	oahpan	V;IND;SG;1;PRS
gossat	gosaleiddet	V;COND;PL;2;LGSPEC1
akšuvdna	akšuvdna	N;NOM;SG
boatkanit	boatkan	V;IMP;SG;2
šlundut	šlunddolit	V;COND;SG;2;LGSPEC1
ađahuvvat	ađahuvažehpet	V;POT;PL;2
gealdit	geldet	V;IMP;PL;2
ceaggát	ceaggášeiddet	V;COND;PL;2
sehkket	sehkkešeimmet	V;COND;PL;1
beahkit	beagán	V;IND;SG;1;PRS
