boža	božilesai	N;TERM;PL
kal’l’	kal’l’oidme	N;PROL;PL
sirdändleikatuz	sirdändleikatusele	N;AT+ALL;SG
lehmuz	lehmusihepäi	N;PRP;PL
elomišt	elomišton	N;ACC;SG
manitelda	manitelda	V;NFIN
babarmžom	babarmžomalesai	N;TERM;SG
lüuste	lüustet	N;PRT;SG
ristitrod	ristitrodunnoks	N;APPRX;SG
institut	institutan	N;GEN;SG
unekaz	unekaz	ADJ;ACC;SG
olod	oloidennopäi	N;ON+ABL;PL
ripitada	ripita	V;IMP;SG;2;POS
haug’	haugišpäi	N;IN+ABL;PL
kezasoba	kezasobidennoks	N;APPRX;PL
suloim	suloimelesai	N;TERM;SG
vändutai	vändutajalepäi	N;PRP;SG
azjtego	azjtegoodme	N;PROL;SG
reht	rehtoidme	N;PROL;PL
leved	levedoiden	ADJ;GEN;PL
bumagpühkmut	bumagpühkmudeks	N;TRANS;SG
mujumär	mujumärilpäi	N;AT+ABL;PL
nenanjur’	nenanjuren	N;FRML;SG
sol’mekaz	sol’mekahannopäi	ADJ;ON+ABL;SG
laudkund	laudkundale	N;AT+ALL;SG
potklaud	potklaudalepäi	N;PRP;SG
nimitadas	nimitatoi	V;IND;SG;2;POS;PRS
sai	sajoidme	N;PROL;PL
kaumžom	kaumžomanno	N;APPRX;SG
el’gendamatoi	el’gendamatoaks	ADJ;TRANS;SG
akcionerine	akcionerižehesai	ADJ;TERM;SG
kagrlüuste	kagrlüuskilpäi	N;AT+ABL;PL
märičematoi	märičematomaha	ADJ;IN+ALL;SG
valdankumaiduz	valdankumaidusihe	N;IN+ALL;PL
keskmäine	keskmäižid	ADJ;PRT;PL
kudmaine	kudmaižikš	ADJ;TRANS;PL
kezr	kezroid	N;PRT;PL
vändutai	vändutajaspäi	N;IN+ABL;SG
čapta	čapnuižin	V;IPFV;COND;SG;1;POS;PST
heregata	hereganzid	V;IPFV;IND;SG;2;POS;PST
babarmžom	babarmžomale	N;AT+ALL;SG
joksmuz	joksmuselepäi	N;PRP;SG
muštatez	muštatesele	N;AT+ALL;SG
kosketuz	kosketusel	N;AT+ESS;SG
ping	pingun	N;ACC;SG
edahuz’	edahudehe	N;IN+ALL;SG
babarmpirg	babarmpirgoiš	N;IN+ESS;PL
redutuk	redutukuhupäi	N;PRP;SG
verivihanik	verivihanikal	N;AT+ESS;SG
penzaz	penshazesai	N;TERM;SG
čagar’	čagarin	N;ACC;SG
ahavoičend	ahavoičendal	N;AT+ESS;SG
kaludišt	kaludištod	N;NOM;PL
moda	modile	N;AT+ALL;PL
kaičendbank	kaičendbankoil	N;AT+ESS;PL
surestada	surestaba	V;IND;PL;3;POS;PRS
pal’l’	pal’l’ahasai	N;TERM;SG
garantine	garantižišpäi	ADJ;IN+ABL;PL
satusekaz	satusekahidenke	ADJ;COM;PL
starinoičii	starinoičijil	N;AT+ESS;PL
saharrogo	saharrogoikš	N;TRANS;PL
ehtatuzsija	ehtatuzsijannoks	N;APPRX;SG
südäingardalei	südäingardalejadme	N;PROL;SG
garantiruida	garantiruidas	V;IND;PL;3;POS;PRS
pordhad	pordhižepäi	N;PRP;PL
lehtišt	lehtištonnoks	N;APPRX;SG
kojeg	kojegen	N;FRML;SG
väzutoitai	väzutoitajikš	ADJ;TRANS;PL
laskm	laskmin	N;FRML;PL
heregata	heregakha	V;IMP;SG;3;POS
täuz’holišt	täuz’holištoidme	N;PROL;PL
püdand	püdandahapäi	N;PRP;SG
sal’m	sal’milesai	N;TERM;PL
näpine	näpižen	N;FRML;SG
kučutada	kučuti	V;IPFV;IND;SG;3;POS;PST
uraduz	uradusenno	N;APPRX;SG
diskussii	diskussijaha	N;IN+ALL;SG
täuz’	täudenno	ADJ;APPRX;SG
pen’	penihe	ADJ;IN+ALL;PL
ragištada	ragištab	V;IND;SG;3;POS;PRS
dumaida	dumainuižin’	V;IPFV;COND;SG;1;POS;PST
käp	käpidme	N;PROL;PL
čaig	čaiguspäi	N;IN+ABL;SG
kanghasine	kanghasiželesai	ADJ;TERM;SG
openduzerišt	openduzerištoihepäi	N;PRP;PL
sapugpäline	sapugpäližišpäi	N;IN+ABL;PL
kalendar’	kalendaridme	N;PROL;PL
higota	higonuižiba	V;IPFV;COND;PL;3;POS;PST
toiženlaine	toiženlaiželpäi	ADJ;AT+ABL;SG
anastuzplan	anastuzplananno	N;APPRX;SG
radvelguded	radvelguzišpäi	N;IN+ABL;PL
idätada	idätada	V;NFIN
pakutada	pakutad	V;IND;SG;2;POS;PRS
tazoznam	tazoznamale	N;AT+ALL;SG
saharrogo	saharrogoidenno	N;APPRX;PL
erižpert’	erižpertinnoks	N;APPRX;SG
tüništuda	tüništuiba	V;IPFV;IND;PL;3;POS;PST
loita	loita	V;NFIN
razv	razvalepäi	N;PRP;SG
ecta	ecta	V;NFIN
vastuz	vastusespäi	N;IN+ABL;SG
lasketimmez’	lasketimmehin	N;FRML;PL
rubl’	rublidennopäi	N;ON+ABL;PL
nižupä	nižupä	N;ACC;SG
kudmaine	kudmaine	ADJ;NOM;SG
napern	napernoile	ADJ;AT+ALL;PL
döl	dölole	N;AT+ALL;SG
ikunlaud	ikunlaudale	N;AT+ALL;SG
änetamine	änetamiženke	N;COM;SG
lu	lun	N;FRML;SG
aigankohtaline	aigankohtaližidenke	ADJ;COM;PL
lämoitand	lämoitandalpäi	N;AT+ABL;SG
armahtamine	armahtamištme	N;PROL;SG
vendmaksud	vendmaksuidme	N;PROL;PL
meripihk	meripihkas	N;IN+ESS;SG
üksituda	üksituit	V;IPFV;IND;PL;2;POS;PST
pasport	pasportannoks	N;APPRX;SG
libedkeline	libedkeližel	ADJ;AT+ESS;SG
pudr	pudrod	N;ACC;PL
mecankaičii	mecankaičijannoks	N;APPRX;SG
merilaid	merilaidad	N;ACC;PL
ünaine	ünaižilepäi	ADJ;PRP;PL
apel’sinpu	apel’sinpuikš	N;TRANS;PL
bumagänik	bumagänikon	N;FRML;SG
pehk	pehkoihepäi	N;PRP;PL
azjtego	azjtegoonnoks	N;APPRX;SG
tarkišteluz	tarkištelusidennoks	N;APPRX;PL
šil’pta	šil’ptas	V;IND;PL;3;POS;PRS
vahveta	vahvenim	V;IPFV;IND;PL;1;POS;PST
ökötada	ökötagat	V;IMP;PL;2;POS
joudutadas	joudutaižitoi	V;COND;SG;2;POS;PRS
harotada	harotagha	V;IMP;PL;3;POS
pullištuda	pullištunuižid	V;IPFV;COND;SG;2;POS;PST
dumaida	dumaigaha	V;IMP;PL;3;POS
čupsuine	čupsuižilesai	N;TERM;PL
pühävoi	pühävoihesai	N;TERM;PL
likumatoi	likumatomidenno	ADJ;APPRX;PL
mecanholitai	mecanholitajale	N;AT+ALL;SG
lendand	lendandan	N;ACC;SG
värmeline	värmeližišpäi	ADJ;IN+ABL;PL
nižuine	nižušt	ADJ;PRT;SG
ištta	išttihe	V;IPFV;PST;PASS
veziludeg	veziludegespäi	N;IN+ABL;SG
saumanjagai	saumanjagajad	N;PRT;SG
allergine	allergižespäi	ADJ;IN+ABL;SG
päministr	päministraspäi	N;IN+ABL;SG
maidnik	maidnikoišpäi	N;IN+ABL;PL
tedotermišt	tedotermištoid	N;PRT;PL
panend	panendoidenno	N;APPRX;PL
ambuskeluzlendim	ambuskeluzlendimidenno	N;APPRX;PL
kel’kosketused	kel’kosketusin	N;FRML;PL
astuhtada	astuhti	V;IPFV;IND;SG;3;POS;PST
sol’mekaz	sol’mekahal	ADJ;AT+ESS;SG
mujuštada	mujuštit	V;IPFV;IND;PL;2;POS;PST
muštištada	muštištaižiba	V;COND;PL;3;POS;PRS
kül’bendhosim	kül’bendhosim	N;NOM;SG
jänduzkogo	jänduzkogoks	N;TRANS;SG
arvostelend	arvostelendannopäi	N;ON+ABL;SG
aigankohtaline	aigankohtaližes	ADJ;IN+ESS;SG
jagaduz	jagaduz	N;NOM;SG
pedajik	pedajikoilepäi	N;PRP;PL
abutuz	abutusilepäi	N;PRP;PL
ičetartui	ičetartujanke	ADJ;COM;SG
uraiduz	uraidusennopäi	N;ON+ABL;SG
barttuda	barttuižit	V;COND;PL;2;POS;PRS
absolutine	absolutižehe	ADJ;IN+ALL;SG
kapustlipikaine	kapustlipikaiželepäi	N;PRP;SG
värohjata	värohjanuižid	V;IPFV;COND;SG;2;POS;PST
abittuda	abittuim	V;IPFV;IND;PL;1;POS;PST
manaluine	manaluine	ADJ;ACC;SG
aldonharj	aldonharjaks	N;TRANS;SG
longibok	longibokidenno	N;APPRX;PL
aktivine	aktivižehe	ADJ;IN+ALL;SG
huzaita	huzaidaižim	V;COND;PL;1;POS;PRS
kalitk	kalitkalpäi	N;AT+ABL;SG
bolvezi	bolvedelpäi	N;AT+ABL;SG
arvnimi	arvnimidme	N;PROL;PL
vähämahtoine	vähämahtoižile	ADJ;AT+ALL;PL
edeta	edeniži	V;COND;SG;3;POS;PRS
pirdaine	pirdaižen	N;ACC;SG
popugai	popugajoihe	N;IN+ALL;PL
upotand	upotandalpäi	N;AT+ABL;SG
kodžu	kodžunke	N;COM;SG
lidnoituz	lidnoituselpäi	N;AT+ABL;SG
mäthišt	mäthištospäi	N;IN+ABL;SG
mudastoitta	mudastoittas	V;PRS;PASS
umbehtuda	umbehtuiži	V;COND;SG;3;POS;PRS
elonnavedii	elonnavedijoihe	ADJ;IN+ALL;PL
herebubarik	herebubarik	N;NOM;SG
regiraiž	regiraižuhupäi	N;PRP;SG
sihloine	sihloiželepäi	N;PRP;SG
ahavoičend	ahavoičendoin	N;FRML;PL
kukoi	kukoilpäi	N;AT+ABL;SG
kirjeine	kirjeižilepäi	N;PRP;PL
parata	paranuižin	V;IPFV;COND;SG;1;POS;PST
semen	semnidme	N;PROL;PL
absolutine	absolutižešpäi	ADJ;IN+ABL;PL
puhtastuzjauh	puhtastuzjauhonnopäi	N;ON+ABL;SG
nenakaz	nenakahan	ADJ;FRML;SG
nägumatoi	nägumatomin	ADJ;FRML;PL
vihmatoi	vihmatoman	ADJ;FRML;SG
astta	astnuižiba	V;IPFV;COND;PL;3;POS;PST
hüpindnor	hüpindnoran	N;FRML;SG
betonsegoituz	betonsegoitusen	N;ACC;SG
rod	rodadme	N;PROL;SG
muštmižed	muštmižed	N;ACC;PL
möhästuda	möhästuit	V;IPFV;IND;PL;2;POS;PST
vändutai	vändutajan	N;GEN;SG
himo	himospäi	N;IN+ABL;SG
idejatoi	idejatoman	ADJ;GEN;SG
kazvalikaz	kazvalikahal	ADJ;AT+ESS;SG
avtomatk	avtomatkalepäi	N;PRP;SG
oks	oksikš	N;TRANS;PL
aigankohtaline	aigankohtaližen	ADJ;ACC;SG
ladida	ladid	V;IND;SG;2;POS;PRS
joukmel’pido	joukmel’pidonno	N;APPRX;SG
kuvataideh	kuvataidehennoks	N;APPRX;SG
neglansil’mäine	neglansil’mäižidenke	N;COM;PL
šohu	šohuid	N;PRT;PL
melentartutoi	melentartutomihe	ADJ;IN+ALL;PL
vendmaksud	vendmaksuin	N;FRML;PL
pahn	pahnalpäi	N;AT+ABL;SG
porohein	porohein	N;ACC;SG
muštatiž	muštatišidme	N;PROL;PL
vajeh	vaihen	N;FRML;SG
radsija	radsijalesai	N;TERM;SG
rida	ridoihe	N;IN+ALL;PL
takkiž	takhennoks	N;APPRX;SG
kodipol’	kodipolihepäi	N;PRP;PL
sitbubarik	sitbubarikal	N;AT+ESS;SG
pahenzuda	pahenzudihe	V;IPFV;PST;PASS
laskta	laskin	V;IPFV;IND;SG;1;POS;PST
panda	pannuižid	V;IPFV;COND;SG;2;POS;PST
sitbubarik	sitbubarikas	N;IN+ESS;SG
ozateluz	ozatelusen	N;ACC;SG
uraduz	uradusihe	N;IN+ALL;PL
naceine	naceižihe	ADJ;IN+ALL;PL
ahtištuz	ahtištusidme	N;COM;PL
vezilaskm	vezilaskmoil	N;AT+ESS;PL
päivitada	päivitanuiži	V;IPFV;COND;SG;3;POS;PST
arvostelda	arvosteled	V;IND;SG;2;POS;PRS
punoda	punonuižin	V;IPFV;COND;SG;1;POS;PST
jumalatomuz’	jumalatomudel	N;AT+ESS;SG
arvostamatoi	arvostamatomassai	ADJ;TERM;SG
analiziruind	analiziruindan	N;FRML;SG
varz	varzoiden	N;GEN;PL
merilaid	merilaidoiden	N;GEN;PL
kulomušt	kulomuštoiden	N;GEN;PL
vezitähtaz	vezitähthidme	N;PROL;PL
kodielo	kodieloihepäi	N;PRP;PL
novakaz	novakahaze	ADJ;IN+ALL;SG
huikteldas	huiktelnuižihe	V;IPFV;COND;SG;3;POS;PST
moda	modal	N;AT+ESS;SG
sportmal’l’	sportmal’l’oile	N;AT+ALL;PL
abstrakcii	abstrakcijoiš	N;IN+ESS;PL
nühkutada	nühkutaižin	V;COND;SG;1;POS;PRS
munavauktuš	munavauktušiš	N;IN+ESS;PL
azegvaražom	azegvaražoman	N;FRML;SG
augonpanend	augonpanendannoks	N;APPRX;SG
arvtego	arvtegooilpäi	N;AT+ABL;PL
kandatez	kandateses	N;IN+ESS;SG
purutuz	purutusele	N;AT+ALL;SG
adverbial	adverbialan	N;FRML;SG
paginmastar’	paginmastarile	N;AT+ALL;SG
sanatoi	sanatomilesai	ADJ;TERM;PL
verisistem	verisistem	N;ACC;SG
pühäkodi	pühäkodinke	N;COM;SG
azjantedai	azjantedajidme	ADJ;PROL;PL
hozj	hozjidme	N;PROL;PL
astrologine	astrologišt	ADJ;PRT;SG
sol’mekaz	sol’mekahalpäi	ADJ;AT+ABL;SG
babarmpirg	babarmpirgal	N;AT+ESS;SG
ličkeh	ličkehile	N;AT+ALL;PL
kogo	kogoišpäi	N;IN+ABL;PL
furašk	furaškoile	N;AT+ALL;PL
saliž	sal’hes	N;IN+ESS;SG
kiruhrad	kiruhradoihepäi	N;PRP;PL
assistent	assistentad	N;PRT;SG
tagotoitta	tagotoitnuižim	V;IPFV;COND;PL;1;POS;PST
alkogol’travind	alkogol’travindan	N;FRML;SG
garun	garunoihepäi	N;PRP;PL
tämävozne	tämävoččil	ADJ;AT+ESS;PL
kaludišt	kaludištonnopäi	N;ON+ABL;SG
joksmuz	joksmustme	N;PROL;SG
lumineičukaine	lumineičukaižehepäi	N;PRP;SG
pedajik	pedajikoid	N;PRT;PL
kül’bendhosim	kül’bendhosimen	N;FRML;SG
avtonkohenduz	avtonkohenduseks	N;TRANS;SG
kärdäs	kärižihe	V;COND;PL;3;POS;PRS
turuvezi	turuvedehe	N;IN+ALL;SG
bumagänik	bumagänikoihesai	N;TERM;PL
torehtuda	torehtugam	V;IMP;PL;1;POS
käzi	käzilpäi	N;AT+ABL;PL
leibmuru	leibmurule	N;AT+ALL;SG
arvonalenduz	arvonalendusen	N;FRML;SG
pullištuda	pullištuin	V;IPFV;IND;SG;1;POS;PST
huzaita	huzaitas	V;PRS;PASS
tätüteatr	tätüteatroid	N;PRT;PL
alič	aličuidennoks	N;APPRX;PL
lugemine	lugemine	N;NOM;SG
garbol	garbloišpäi	N;IN+ABL;PL
kel’kosketused	kel’kosketusil	N;AT+ESS;PL
kezerta	kezernuižimai	V;IPFV;COND;PL;1;POS;PST
olii	olijoikš	N;TRANS;PL
louskutada	louskutaižid	V;COND;SG;2;POS;PRS
edahaksnägii	edahaksnägii	ADJ;NOM;SG
vähenduz	vähendusihe	N;IN+ALL;PL
ohjandai	ohjandajidenno	N;APPRX;PL
potklaud	potklaudaha	N;IN+ALL;SG
ičestuda	ičestuižiba	V;COND;PL;3;POS;PRS
erazvuičetada	erazvuičetadas	V;PRS;PASS
mujuštada	mujuštaižin	V;COND;SG;1;POS;PRS
pol’vaumičez	pol’vaumičez	N;ACC;SG
mürk	mürkan	ADJ;ACC;SG
pordhad	pordhilpäi	N;AT+ABL;PL
villaine	villaižil	ADJ;AT+ESS;PL
tomu	tomulepäi	N;PRP;SG
bobita	bobičižin	V;COND;SG;1;POS;PRS
kävuda	kävuimei	V;IPFV;IND;PL;1;POS;PST
vihasine	vihasižespäi	ADJ;IN+ABL;SG
tarboin	tarboimehepäi	N;PRP;SG
tähthaine	tähthaižed	N;NOM;PL
ecii	ecijoiš	N;IN+ESS;PL
pal’l’	pal’l’alesai	N;TERM;SG
tervhutez	tervhutesehe	N;IN+ALL;SG
tül’c	tül’calesai	ADJ;TERM;SG
bumagkäreg	bumagkäregin	N;FRML;PL
käpsta	käpsnuižid	V;IPFV;COND;SG;2;POS;PST
putuz	putusen	N;ACC;SG
levitadas	levitase	V;IND;SG;3;POS;PRS
möl’kištada	möl’kištad	V;IND;SG;2;POS;PRS
jumalanuskoi	jumalanuskojid	N;PRT;PL
brängaiduz	brängaidusen	N;GEN;SG
adverbial	adverbialas	N;IN+ESS;SG
rouhii	rouhijannoks	N;APPRX;SG
löumai	löumal	ADJ;AT+ESS;PL
pičuine	pičuižidenno	ADJ;APPRX;PL
jumalanuskoi	jumalanuskojannopäi	N;ON+ABL;SG
vajuda	vajuižiba	V;COND;PL;3;POS;PRS
orav	oravanke	N;COM;SG
praznikambuskeluz	praznikambuskelusidennopäi	N;ON+ABL;PL
vin	vinoihepäi	N;PRP;PL
sebanpä	sebanpäilesai	N;TERM;PL
manituzkuva	manituzkuvilesai	N;TERM;PL
vilik	vilikod	N;NOM;PL
kojaduz	kojadusišpäi	N;IN+ABL;PL
olii	olijannoks	N;APPRX;SG
hambazharj	hambazharjannopäi	N;ON+ABL;SG
siganik	siganikoidennopäi	N;ON+ABL;PL
statj	statjad	N;ACC;PL
alavzumine	alavzumižehesai	N;TERM;SG
jändeansambl’	jändeansambin	N;GEN;SG
hagurta	hagurdaižit	V;COND;PL;2;POS;PRS
rahvazkund	rahvazkundalesai	N;TERM;SG
manituzkuva	manituzkuviš	N;IN+ESS;PL
varaidmatomuz’	varaidmatomudelpäi	N;AT+ABL;SG
muštlaud	muštlaudaha	N;IN+ALL;SG
leibmuru	leibmurulpäi	N;AT+ABL;SG
sinikod	sinikoikš	N;TRANS;PL
nühaida	nühaidihe	V;IPFV;PST;PASS
vahv	vahvad	ADJ;NOM;PL
rippuda	rippuin	V;IPFV;IND;SG;1;POS;PST
tarkatoi	tarkatomidennopäi	ADJ;ON+ABL;PL
longahtada	longahtiba	V;IPFV;IND;PL;3;POS;PST
holenpidänd	holenpidändahapäi	N;PRP;SG
nühkutada	nühkutagam	V;IMP;PL;1;POS
kazvahtada	kazvahtam	V;IND;PL;1;POS;PRS
kakatuz	kakatuses	N;IN+ESS;SG
pordhad	pordhišpäi	N;IN+ABL;PL
pil’vesennavedii	pil’vesennavedijoihe	ADJ;IN+ALL;PL
lüpsai	lüpsajahapäi	N;PRP;SG
jur’plod	jur’plodudme	N;PROL;SG
tarkišteluz	tarkištelusiden	N;GEN;PL
humalzuda	humalzuiži	V;COND;SG;3;POS;PRS
möl’kištada	möl’kištaižim	V;COND;PL;1;POS;PRS
saumanjagai	saumanjagajan	N;ACC;SG
erazvuičetada	erazvuičetit	V;IPFV;IND;PL;2;POS;PST
rozmekaz	rozmekahad	ADJ;ACC;PL
azegetoi	azegetomale	ADJ;AT+ALL;SG
torv	torvel	N;AT+ESS;SG
brod	brodulesai	N;TERM;SG
augku	augkulpäi	N;AT+ABL;SG
pahakulu	pahakululepäi	ADJ;PRP;SG
imel’	imeläks	ADJ;TRANS;SG
kačk	kačkule	N;AT+ALL;SG
suičetada	suičetiba	V;IPFV;IND;PL;3;POS;PST
kukerdeluz	kukerdelusehe	N;IN+ALL;SG
valičendbumag	valičendbumagalepäi	N;PRP;SG
küläškol	küläškolanke	N;COM;SG
nižuine	nižuižed	ADJ;ACC;PL
savusumeg	savusumeg	N;NOM;SG
kanghasine	kanghasine	ADJ;ACC;SG
plokta	plokižin	V;COND;SG;1;POS;PRS
tegohengituz	tegohengitust	N;PRT;SG
čočoi	čočoinke	ADJ;COM;SG
kubukaz	kubukahikš	ADJ;TRANS;PL
armastuz	armastusil	N;AT+ESS;PL
merilaid	merilaidanke	N;COM;SG
robeh	robeh	N;ACC;SG
kel’dändsana	kel’dändsanoišpäi	N;IN+ABL;PL
pakičaine	pakičaižidenke	N;COM;PL
kodikanghasine	kodikanghasižennopäi	ADJ;ON+ABL;SG
voipu	voipuid	N;PRT;PL
vezipomp	vezipompannoks	N;APPRX;SG
avtoškol	avtoškolaha	N;IN+ALL;SG
hirenherneh	hirenhernhilesai	N;TERM;PL
atom	atoman	N;ACC;SG
lastvod	lastvidenno	N;APPRX;PL
pärm	pärmalepäi	N;PRP;SG
laudkund	laudkundan	N;ACC;SG
modkuva	modkuval	N;AT+ESS;SG
aldonvuitte	aldonvuiččen	ADJ;FRML;SG
pugetada	pugetanuiži	V;IPFV;COND;SG;3;POS;PST
edahaksnägui	edahaksnägujale	ADJ;AT+ALL;SG
vargastada	vargastanuižit	V;IPFV;COND;PL;2;POS;PST
šuhaiduz	šuhaiduselesai	N;TERM;SG
pakuižharagaine	pakuižharagaiženke	N;COM;SG
lähtan	lähtmin	N;FRML;PL
kurg	kurgessai	N;TERM;SG
benzinvaražom	benzinvaražomid	N;PRT;PL
bobuštamine	bobuštamižen	N;ACC;SG
ong	ongidennoks	N;APPRX;PL
sel’grod	sel’grodahasai	N;TERM;SG
virg	virgalpäi	N;AT+ABL;SG
uhu	uhuin	N;FRML;PL
čuhluine	čuhluižihe	N;IN+ALL;PL
alangsija	alangsijjoid	N;PRT;PL
aigankohtaline	aigankohtaližišpäi	ADJ;IN+ABL;PL
rod	rodule	N;AT+ALL;SG
purskta	purskaiži	V;COND;SG;3;POS;PRS
hobedtabaine	hobedtabaižidennopäi	ADJ;ON+ABL;PL
mäč	mäčuid	N;PRT;PL
tagotoitta	tagotoitaba	V;IND;PL;3;POS;PRS
mannasurin	mannasurimas	N;IN+ESS;SG
puhtastuzjauh	puhtastuzjauhozesai	N;TERM;SG
kurik	kurikoišpäi	N;IN+ABL;PL
essiv-instruktiv	essiv-instruktivalesai	N;TERM;SG
maröunanvarjoičii	maröunanvarjoičijalepäi	N;PRP;SG
tartlent	tartlentan	N;GEN;SG
burahtand	burahtandale	N;AT+ALL;SG
absolutine	absolutižen	ADJ;FRML;PL
lehtišt	lehtišton	N;GEN;SG
pol’vozne	pol’voččilepäi	ADJ;PRP;PL
kunigaz	kunigahil	N;AT+ESS;PL
pihl’lind	pihl’lind	N;ACC;SG
pörukukoi	pörukukoid	N;NOM;PL
bölskutand	bölskutandahasai	N;TERM;SG
velg	velgoidennoks	N;APPRX;PL
venälaine	venälaižišpäi	ADJ;IN+ABL;PL
avtotanaz	avtotanhale	N;AT+ALL;SG
azotamine	azotamižilepäi	N;PRP;PL
randird	randirdannoks	N;APPRX;SG
dub	dubidennopäi	N;ON+ABL;PL
lämoinvaraidai	lämoinvaraidajil	ADJ;AT+ESS;PL
polišk	poliškoikš	N;TRANS;PL
päivlaskmaig	päivlaskmaigoil	N;AT+ESS;PL
karglava	karglavoidennoks	N;APPRX;PL
šuhaitas	šuhaikahas	V;IMP;PL;3;POS
kolmatoi	kolmatomidennopäi	ADJ;ON+ABL;PL
üldüda	üldüi	V;IPFV;IND;SG;3;POS;PST
juraita	juraidab	V;IND;SG;3;POS;PRS
azjtego	azjtegoolepäi	N;PRP;SG
čibutätüine	čibutätüine	N;ACC;SG
villak	villakoidme	N;PROL;PL
muigota	muigonuižim	V;IPFV;COND;PL;1;POS;PST
čibirik	čibirik	N;NOM;SG
telefon	telefonoile	N;AT+ALL;PL
jokseta	joksekat	V;IMP;PL;2;POS
hapata	hapnim	V;IPFV;IND;PL;1;POS;PST
puhtastuz	puhtastusilepäi	N;PRP;PL
tedoline	tedoližilpäi	ADJ;AT+ABL;PL
pärm	pärmihe	N;IN+ALL;PL
sportmal’l’	sportmal’l’adme	N;PROL;SG
kalatada	kalatada	V;NFIN
sömänsulatuzainehed	sömänsulatuzainehennopäi	N;ON+ABL;SG
azotez	azotesen	N;ACC;SG
mär	märidenke	N;COM;PL
hirenherneh	hirenhernhišpäi	N;IN+ABL;PL
regiraiž	regiraižunno	N;APPRX;SG
bäläita	bäläikam	V;IMP;PL;1;POS
tegetez	tegetesehe	N;IN+ALL;SG
jagamatoi	jagamatomahasai	ADJ;TERM;SG
edeta	edetihe	V;IPFV;PST;PASS
täuz’	täuzihesai	ADJ;TERM;PL
än’	änihe	N;IN+ALL;PL
čupsuine	čupsuižen	N;FRML;SG
oleskelend	oleskelendoilpäi	N;AT+ABL;PL
hil’l’	hillil	ADJ;AT+ESS;PL
kalendar’	kalendarin	N;FRML;PL
vändutada	vändutin	V;IPFV;IND;SG;1;POS;PST
hobitada	hobitaba	V;IND;PL;3;POS;PRS
aparoičend	aparoičendoidennopäi	N;ON+ABL;PL
mezjaižpeza	mezjaižpezoihe	N;IN+ALL;PL
levednenaine	levednenaiželpäi	ADJ;AT+ABL;SG
mod	modhosai	N;TERM;SG
ristta	ristnuižiba	V;IPFV;COND;PL;3;POS;PST
kajag	kajagišpäi	N;IN+ABL;PL
abittuda	abittuižid	V;COND;SG;2;POS;PRS
mäzötada	mäzötit	V;IPFV;IND;PL;2;POS;PST
buhkutez	buhkuteses	N;IN+ESS;SG
jumalanuskoi	jumalanuskojas	N;IN+ESS;SG
än’	änen	N;ACC;SG
čiksutada	čiksutanuiži	V;IPFV;COND;SG;3;POS;PST
sügüz’pol’	sügüz’polehe	N;IN+ALL;SG
ohjandai	ohjandajilpäi	N;AT+ABL;PL
taidehkuva	taidehkuvad	N;ACC;PL
rahanik	rahanikoile	N;AT+ALL;PL
kapust	kapustoihepäi	N;PRP;PL
benzin	benzinahasai	N;TERM;SG
purehveneh	purehvenehezesai	N;TERM;SG
näl’ghine	näl’ghižidme	ADJ;PROL;PL
tuhahtada	tuhahtanuižin	V;IPFV;COND;SG;1;POS;PST
pimed	pimedalpäi	ADJ;AT+ABL;SG
pučoi	pučoid	N;PRT;PL
samalduz	samaldusilesai	N;TERM;PL
jagaduz	jagadusidenno	N;APPRX;PL
nenakaz	nenakahidme	ADJ;PROL;PL
jänmurendai	jänmurendajadme	N;PROL;SG
louskutada	louskutin	V;IPFV;IND;SG;1;POS;PST
tabanräk	tabanräkel	N;AT+ESS;SG
kezi	keden	N;GEN;SG
sauvotuz	sauvotuz	N;NOM;SG
avtoajeluz	avtoajeluselpäi	N;AT+ABL;SG
buhkahtada	buhkahtaižim	V;COND;PL;1;POS;PRS
telefon	telefonalpäi	N;AT+ABL;SG
jügeduz’	jügeduden	N;FRML;SG
kulm	kulmil	N;AT+ESS;PL
radatoitta	radatoitan	V;IND;SG;1;POS;PRS
murendai	murendajihepäi	N;PRP;PL
nägumatoi	nägumatomidennoks	ADJ;APPRX;PL
suomalaiž-ugrilaine	suomalaiž-ugrilaižilesai	ADJ;TERM;PL
vanhuz’	vanhudehesai	N;TERM;SG
kel’dändsana	kel’dändsanoidenno	N;APPRX;PL
rubikibu	rubikibuilepäi	N;PRP;PL
kagr	kagroilpäi	N;AT+ABL;PL
alištada	alištaižin	V;COND;SG;1;POS;PRS
edahaksnägii	edahaksnägijoiden	ADJ;GEN;PL
ohjanduzmaht	ohjanduzmaht	N;ACC;SG
tämävozne	tämävoččihesai	ADJ;TERM;PL
dumaida	dumaiba	V;IND;PL;3;POS;PRS
čuhluine	čuhluižennopäi	N;ON+ABL;SG
tarboin	tarboimen	N;FRML;SG
avonaine	avonaižin	ADJ;FRML;PL
vezimuju	vezimujuspäi	N;IN+ABL;SG
snap	snapule	N;AT+ALL;SG
ajelzoitta	ajelzoitab	V;IND;SG;3;POS;PRS
akustik	akustikan	N;GEN;SG
aigankohtaline	aigankohtaližespäi	ADJ;IN+ABL;SG
ridlematoi	ridlematomaks	ADJ;TRANS;SG
sibitez	sibitezsespäi	N;IN+ABL;SG
lähtendznam	lähtendznamad	N;PRT;SG
buhaidamine	buhaidamižele	N;AT+ALL;SG
faternik	faternikoidennoks	N;APPRX;PL
buhaidamine	buhaidamižehepäi	N;PRP;SG
higota	higonuiži	V;IPFV;COND;SG;3;POS;PST
päivlaskmaig	päivlaskmaigad	N;PRT;SG
tekst	teksthapäi	N;PRP;SG
aigastada	aigastaižiba	V;COND;PL;3;POS;PRS
meriveneh	merivenehidennoks	N;APPRX;PL
neglansil’mäine	neglansil’mäižihe	N;IN+ALL;PL
hubeta	hubenzin	V;IPFV;IND;SG;1;POS;PST
azialaine	azialaižilepäi	N;PRP;PL
matkvaumičused	matkvaumičusilepäi	N;PRP;PL
londuztedo	londuztedospäi	N;IN+ABL;SG
otuz	otusil	N;AT+ESS;PL
olut	oludenke	N;COM;SG
vastuzsija	vastuzsijan	N;GEN;SG
hubeta	hubenuižiba	V;IPFV;COND;PL;3;POS;PST
mecankaičii	mecankaičijal	N;AT+ESS;SG
telefon	telefonaks	N;TRANS;SG
razvaduda	razvadunuižim	V;IPFV;COND;PL;1;POS;PST
haikosteldas	haikostelesoiš	V;IND;PL;3;POS;PRS
otta	otta	V;NFIN
vauvhakaz	vauvhakahan	ADJ;GEN;SG
murginoita	murginoičiba	V;IPFV;IND;PL;3;POS;PST
hagomado	hagomadod	N;PRT;SG
homaita	homainuižin	V;IPFV;COND;SG;1;POS;PST
arbaine	arbaižidme	N;PROL;PL
kajahtada	kajahtadas	V;PRS;PASS
il’mkül’bend	il’mkül’bendoid	N;PRT;PL
vatišk	vatiškon	N;FRML;SG
trio	trioiš	N;IN+ESS;PL
uraiduz	uraidusihe	N;IN+ALL;PL
rida	ridan	N;FRML;SG
jurdutand	jurdutandalesai	N;TERM;SG
tarh	tarhoihesai	N;TERM;PL
räk	räkidennoks	N;APPRX;PL
pakssüine	pakssüižidenke	ADJ;COM;PL
tarbeh	tarbhidennoks	N;APPRX;PL
arb	arbanke	N;COM;SG
edahaksnägii	edahaksnägijoidenke	ADJ;COM;PL
keitimpol’	keitimpolelepäi	N;PRP;SG
bul’botuz	bul’botusehesai	N;TERM;SG
valičendbumag	valičendbumagad	N;ACC;PL
zakonankundlijaine	zakonankundlijaižiden	ADJ;GEN;PL
veziznam	veziznamas	N;IN+ESS;SG
kokrištuda	kokrištuin	V;IPFV;IND;SG;1;POS;PST
pordazkeskust	pordazkeskustoidme	N;PROL;PL
ong	ongidennopäi	N;ON+ABL;PL
samalduz	samaldusihepäi	N;PRP;PL
negloikaz	negloikahaze	ADJ;IN+ALL;SG
saliž	sal’hiže	N;IN+ALL;PL
rainiž	rainihižesai	ADJ;TERM;PL
natikaz	natikahas	ADJ;IN+ESS;SG
aktivine	aktivižes	ADJ;IN+ESS;SG
paremba	parembaid	ADJ;PRT;PL
umbehtuda	umbehtunuiži	V;IPFV;COND;SG;3;POS;PST
uraz	urasiden	N;GEN;PL
mäč	mäčunnopäi	N;ON+ABL;SG
tätüteatr	tätüteatroihe	N;IN+ALL;PL
germanialaine	germanialaižen	ADJ;GEN;SG
keitoz	keitosin	N;FRML;PL
kand	kand	N;NOM;SG
modkuva	modkuvahasai	N;TERM;SG
bumagtegeline	bumagtegeližen	ADJ;GEN;SG
pahn	pahnadme	N;PROL;SG
ambuskeluzlendim	ambuskeluzlendimes	N;IN+ESS;SG
avtoškol	avtoškol	N;NOM;SG
vesoidas	vesoinuižihe	V;IPFV;COND;PL;3;POS;PST
tabaduz	tabadusidenno	N;APPRX;PL
radnik	radnikoišpäi	N;IN+ABL;PL
veziznam	veziznamoikš	N;TRANS;PL
läžund	läžundoidennopäi	N;ON+ABL;PL
pjes	pjesan	N;ACC;SG
kaičuztaho	kaičuztahoihesai	N;TERM;PL
pälidn	pälidnan	N;GEN;SG
kucta	kucu	V;IMP;SG;2;POS
hebočaine	hebočaine	N;ACC;SG
šuhaita	šuhaidaižid	V;COND;SG;2;POS;PRS
kürz	kürzalesai	N;TERM;SG
agl’utinativine	agl’utinativižidennoks	ADJ;APPRX;PL
kormadai	kormadajiš	N;IN+ESS;PL
pullištuda	pullištui	V;IPFV;IND;SG;3;POS;PST
išttas	ištusoiš	V;IND;PL;3;POS;PRS
akpol’	akpol’tme	N;PROL;SG
likund	likundoihe	N;IN+ALL;PL
joukmel’pido	joukmel’pidoile	N;AT+ALL;PL
artut’pachaine	artut’pachaiženke	N;COM;SG
sapugpäline	sapugpäližel	N;AT+ESS;SG
pal’l’	pal’l’ad	N;PRT;SG
kazvokaz	kazvokahidenke	ADJ;COM;PL
azjanajai	azjanajajilepäi	N;PRP;PL
vastoidas	vastoinuižimoiš	V;IPFV;COND;PL;1;POS;PST
ozražnik	ozražnikoilepäi	N;PRP;PL
sädai	sädajas	N;IN+ESS;SG
sebruz’lidn	sebruz’lidn	N;ACC;SG
čailuzik	čailuzikoihesai	N;TERM;PL
jagaduz	jagadust	N;PRT;SG
pahantegii	pahantegijan	N;FRML;SG
korišk	koriškoihe	N;IN+ALL;PL
päiväine	päiväižilesai	N;TERM;PL
kehkerzoitta	kehkerzoitkam	V;IMP;PL;1;POS
azotez	azotesenke	N;COM;SG
sula	sulad	ADJ;PRT;SG
avtotanaz	avtotanhas	N;IN+ESS;SG
haikosteldas	haikosteližitoi	V;COND;SG;2;POS;PRS
vaugedpä	vaugedpän	ADJ;FRML;SG
tegii	tegijoiden	N;GEN;PL
törkita	törkinuižiba	V;IPFV;COND;PL;3;POS;PST
kodielo	kodielolesai	N;TERM;SG
regisä	regisän	N;ACC;SG
holituz	holituselesai	N;TERM;SG
čipitada	čipitagha	V;IMP;PL;3;POS
öpu	öpul	N;AT+ESS;SG
häčamuna	häčamunile	N;AT+ALL;PL
šaug	šaugun	N;FRML;SG
elonaigaine	elonaigaižid	ADJ;PRT;PL
alištuzsanund	alištuzsanundan	N;FRML;SG
kel’dänd	kel’dändalepäi	N;PRP;SG
putuz	putuselesai	N;TERM;SG
muzaver’	muzaverelesai	ADJ;TERM;SG
akcionerine	akcionerištme	ADJ;PROL;SG
puhtastuzjauh	puhtastuzjauhonnoks	N;APPRX;SG
kangazkoda	kangazkodiš	N;IN+ESS;PL
tal’vvara	tal’vvaras	N;IN+ESS;SG
lumut	lumut	N;ACC;SG
artut’pachaine	artut’pachaižile	N;AT+ALL;PL
kukoi	kukoin	N;ACC;SG
hajutoin	hajutoin	ADJ;ACC;SG
lahjpauk	lahjpaukoidennopäi	N;ON+ABL;PL
pahmaz	pahmahazepäi	N;PRP;SG
sijahavad	sijahavadonke	N;COM;SG
azjantedai	azjantedajalepäi	ADJ;PRP;SG
jokseta	joksenuižid	V;IPFV;COND;SG;2;POS;PST
sel’gitada	sel’gitanuižim	V;IPFV;COND;PL;1;POS;PST
kel’tedomez’	kel’tedomehen	N;GEN;SG
laskm	laskmilesai	N;TERM;PL
bumagnor	bumagnoridennopäi	N;ON+ABL;PL
betonlava	betonlavannopäi	N;ON+ABL;SG
oigedpoline	oigedpoližilepäi	ADJ;PRP;PL
foto	fotod	N;NOM;PL
saliž	sal’hennopäi	N;ON+ABL;SG
mugoita	mugoitas	V;IND;PL;3;POS;PRS
gor’aine	gor’aižilepäi	N;PRP;PL
čuklostuda	čuklostud	V;IND;SG;2;POS;PRS
söda	sönuižit	V;IPFV;COND;PL;2;POS;PST
živatrazv	živatrazvoidenke	N;COM;PL
mureptuz	mureptused	N;ACC;PL
saliž	sal’hezepäi	ADJ;PRP;SG
holituz	holitusele	N;AT+ALL;SG
alištand	alištandal	N;AT+ESS;SG
paraine	paraižile	ADJ;AT+ALL;PL
vezimuju	vezimujuihesai	N;TERM;PL
kucta	kucnuižiba	V;IPFV;COND;PL;3;POS;PST
imičaine	imičaiženno	N;APPRX;SG
läžund	läžundoin	N;FRML;PL
sel’genzoitta	sel’genzoitam	V;IND;PL;1;POS;PRS
päkonsul	päkonsuloidennoks	N;APPRX;PL
akademii	akademijoidme	N;PROL;PL
odvendamine	odvendamiženke	N;COM;SG
hirenherneh	hirenhernhespäi	N;IN+ABL;SG
harotada	harotaiži	V;COND;SG;3;POS;PRS
küläškol	küläškolahasai	N;TERM;SG
virst	virstalesai	N;TERM;SG
värištuz	värištusel	N;AT+ESS;SG
azialaine	azialaižennopäi	N;ON+ABL;SG
rügida	rügi	V;IPFV;IND;SG;3;POS;PST
böl’skutuz	böl’skutuseks	N;TRANS;SG
barabanda	barabani	V;IMP;SG;2;POS
rubl’	rubl’adme	N;PROL;SG
väta	vänuižit	V;IPFV;COND;PL;2;POS;PST
tätüteatr	tätüteatralepäi	N;PRP;SG
pol’vozne	pol’voččelpäi	ADJ;AT+ABL;SG
vahveta	vahvenuiži	V;IPFV;COND;SG;3;POS;PST
pol’vozne	pol’voččehesai	ADJ;TERM;SG
adverb	adverboil	N;AT+ESS;PL
katuz	katusiden	N;GEN;PL
garantiruida	garantiruinuižin	V;IPFV;COND;SG;1;POS;PST
joudobuz	joudobuselesai	N;TERM;SG
kaid	kaidoin	ADJ;FRML;PL
ezipauk	ezipaukoidenno	N;APPRX;PL
lapsestada	lapsestadihe	V;IPFV;PST;PASS
kožudas	kožutoiš	V;IND;PL;2;POS;PRS
danialaine	danialaižidennoks	N;APPRX;PL
radvelguded	radvelguzilesai	N;TERM;PL
tacind	tacindoile	N;AT+ALL;PL
eländsija	eländsijidenke	N;COM;PL
vägi	vägele	N;AT+ALL;SG
ahtištada	ahtištagha	V;IMP;PL;3;POS
redumajag	redumajagad	N;PRT;SG
lainhekaz	lainhekahikš	ADJ;TRANS;PL
kartohkpörukaine	kartohkpörukaižilesai	N;TERM;PL
hubeta	hubekaha	V;IMP;PL;3;POS
väčurta	väčurkaha	V;IMP;PL;3;POS
saubpoikuz	saubpoikusen	N;GEN;SG
mäzötada	mäzötaižiba	V;COND;PL;3;POS;PRS
poikuz	poikuses	N;IN+ESS;SG
jauhostada	jauhostaižin	V;COND;SG;1;POS;PRS
dumaida	dumaižin’	V;COND;SG;1;POS;PRS
himo	himonke	N;COM;SG
lipsutada	lipsutaižid	V;COND;SG;2;POS;PRS
kohuda	kohugat	V;IMP;PL;2;POS
kodipol’	kodipolin	N;FRML;PL
kurik	kurikole	N;AT+ALL;SG
pärm	pärmin	N;FRML;PL
vanh	vanhaspäi	ADJ;IN+ABL;SG
kormastada	kormastanuižim	V;IPFV;COND;PL;1;POS;PST
naceine	naceižihepäi	ADJ;PRP;PL
uskmatoi	uskmatomalepäi	ADJ;PRP;SG
pökoi	pökoihepäi	N;PRP;SG
kokotada	kokotaižiba	V;COND;PL;3;POS;PRS
jügeduz’	jügedudeks	N;TRANS;SG
kivirong	kivirongul	N;AT+ESS;SG
hered	heredadme	ADJ;PROL;SG
lopku	lopkud	N;ACC;PL
nenakaz	nenakahaks	ADJ;TRANS;SG
armahtamine	armahtamižennopäi	N;ON+ABL;SG
kandantaguine	kandantaguižilepäi	N;PRP;PL
vösija	vösijiden	N;GEN;PL
jogahine	jogahižišpäi	ADJ;IN+ABL;PL
kuz’	kuzelepäi	N;PRP;SG
bobita	bobičeb	V;IND;SG;3;POS;PRS
näpine	näpiženno	N;APPRX;SG
levitada	levitatei	V;IND;PL;2;POS;PRS
ozražnik	ozražnikoile	N;AT+ALL;PL
voibištelendkalu	voibištelendkaluiden	N;GEN;PL
uraduz	uradusehepäi	N;PRP;SG
varjoičim	varjoičimmen	N;GEN;SG
joudobuz	joudobusin	N;FRML;PL
suvi	suvennopäi	N;ON+ABL;SG
ridelta	ridelnuižid	V;IPFV;COND;SG;2;POS;PST
tütrindam	tütrindamad	N;NOM;PL
kahaita	kahaižin	V;IPFV;IND;SG;1;POS;PST
sada	sanuužimaa	V;IPFV;COND;PL;1;POS;PST
villaine	villaižehe	ADJ;IN+ALL;SG
hormheinžom	hormheinžomadme	N;PROL;SG
jügeduz’	jügedudehesai	N;TERM;SG
avar	avar	ADJ;ACC;SG
heinäkaz	heinäkahaze	ADJ;IN+ALL;SG
paginmastar’	paginmastaridennopäi	N;ON+ABL;PL
redutuk	redutukuin	N;FRML;PL
mecannena	mecannenoilepäi	N;PRP;PL
muštkirjaine	muštkirjaižilesai	N;TERM;PL
ühthižvarad	ühthižvaroihepäi	N;PRP;PL
vihmda	vihmgaha	V;IMP;SG;3;POS
leved	leved	ADJ;NOM;SG
varutuzznam	varutuzznamanno	N;APPRX;SG
tartlent	tartlentoidme	N;PROL;PL
upotand	upotandanke	N;COM;SG
jogavozne	jogavoččennopäi	ADJ;ON+ABL;SG
garun	garunalepäi	N;PRP;SG
ül’dütada	ül’dütit	V;IPFV;IND;PL;2;POS;PST
pimed	pimedoilpäi	N;AT+ABL;PL
nit’	niidennopäi	N;ON+ABL;PL
kaičuz	kaičusehepäi	N;PRP;SG
lipsutada	lipsutat	V;IND;PL;2;POS;PRS
videnz’päiv	videnz’päivilesai	N;TERM;PL
agronom	agronomoil	N;AT+ESS;PL
holenpidänd	holenpidändalpäi	N;AT+ABL;SG
katuz	katusidennoks	N;APPRX;PL
leved	levedoilepäi	ADJ;PRP;PL
levednenaine	levednenaižel	ADJ;AT+ESS;SG
lapsestada	lapsestanuiži	V;IPFV;COND;SG;3;POS;PST
keväz’	keväzihepei	N;PRP;PL
brängaiduz	brängaidustme	N;PROL;SG
silituz	silitusil	N;AT+ESS;PL
koverzoitta	koverzoitkaha	V;IMP;PL;3;POS
čailuzik	čailuzikoidenno	N;APPRX;PL
kollektiv	kollektivad	N;PRT;SG
kagr	kagroilesai	N;TERM;PL
toh’	tohile	N;AT+ALL;PL
radatoitta	radatoitnuižid	V;IPFV;COND;SG;2;POS;PST
turuvezi	turuveden	N;FRML;SG
čupsuine	čupsuiželpäi	N;AT+ABL;SG
virz	virzulpäi	N;AT+ABL;SG
kibuntegii	kibuntegijad	ADJ;ACC;PL
tukuine	tukuižilepäi	N;PRP;PL
palo	palho	N;IN+ALL;SG
gad	gadad	N;NOM;PL
seinkeskust	seinkeskustahasai	N;TERM;SG
peneta	penenzit	V;IPFV;IND;PL;2;POS;PST
ajelzoitta	ajelzoitkam	V;IMP;PL;1;POS
pal’patada	pal’pataižin	V;COND;SG;1;POS;PRS
süvüz’laiv	süvüz’laivoiš	N;IN+ESS;PL
kakastuda	kakastub	V;IND;SG;3;POS;PRS
čapatez	čapatestme	N;PROL;SG
peittas	peitkahas	V;IMP;PL;3;POS
tokata	tokanuižid	V;IPFV;COND;SG;2;POS;PST
elonaigaine	elonaigaižikš	ADJ;TRANS;PL
uhoku	uhokuks	N;TRANS;SG
kormmašin	kormmašinan	N;GEN;SG
avokado	avokadol	N;AT+ESS;SG
bahfal	bahfalad	N;PRT;SG
lapseline	lapseližehepäi	N;PRP;SG
surestada	surestan	V;IND;SG;1;POS;PRS
ezitada	ezitam	V;IND;PL;1;POS;PRS
garboljom	garboljomidenno	N;APPRX;PL
mod	modoilesai	N;TERM;PL
unohtuz	unohtusile	N;AT+ALL;PL
kakastuda	kakastudihe	V;IPFV;PST;PASS
lahjakaz	lahjakahilesai	ADJ;TERM;PL
maim	maimahapäi	N;PRP;SG
joudutada	joudutanuižin	V;IPFV;COND;SG;1;POS;PST
bučintegii	bučintegijad	N;ACC;PL
vastkarine	vastkarine	ADJ;ACC;SG
vasttullei	vasttullein	N;FRML;PL
tünüz’	tünüdes	N;IN+ESS;SG
openduzerišt	openduzerištoihe	N;IN+ALL;PL
kattas	kataižimoiš	V;COND;PL;1;POS;PRS
raudtestancii	raudtestancijaha	N;IN+ALL;SG
polišk	polišk	N;ACC;SG
kebnpäzuine	kebnpäzuižile	ADJ;AT+ALL;PL
mudaita	mudaidaižim	V;COND;PL;1;POS;PRS
tedotuzlaud	tedotuzlaudaks	N;TRANS;SG
antonim	antonimaks	N;TRANS;SG
toštmatoi	toštmatomile	ADJ;AT+ALL;PL
pöudtedo	pöudtedoile	N;AT+ALL;PL
päiväine	päiväižidenke	N;COM;PL
raudsomuz	raudsomusel	N;AT+ESS;SG
openduz	opendusihepäi	N;PRP;PL
haudad	haudoihesai	N;TERM;PL
vedändlaiv	vedändlaivoin	N;FRML;PL
londusetoi	londusetomidenno	ADJ;APPRX;PL
komitativ	komitativoikš	N;TRANS;PL
pälidn	pälidnoil	N;AT+ESS;PL
kirgundznam	kirgundznamaks	N;TRANS;SG
muilpala	muilpalan	N;GEN;SG
radnik	radnikaks	N;TRANS;SG
kandaine	kandaižidenke	N;COM;PL
mezisil’mäd	mezisil’mišpäi	N;IN+ABL;PL
imičaine	imičaižilesai	N;TERM;PL
šuhaiduz	šuhaidusilepäi	N;PRP;PL
telefon	telefonalesai	N;TERM;SG
päivänteraline	päivänteraližil	ADJ;AT+ESS;PL
longahtada	longahta	V;IMP;SG;2;POS
säta	sänuižim	V;IPFV;COND;PL;1;POS;PST
joudutand	joudutandahapäi	N;PRP;SG
kand	kandol	N;AT+ESS;SG
hagomado	hagomadoihepäi	N;PRP;PL
värenzoituz	värenzoitusenke	N;COM;SG
kalatada	kalataižiba	V;COND;PL;3;POS;PRS
uskmatoi	uskmatomilpäi	ADJ;AT+ABL;PL
metiškend	metiškendad	N;NOM;PL
pol’vozne	pol’voččenke	ADJ;COM;SG
redumajag	redumajagid	N;PRT;PL
paginmaht	paginmahtoil	N;AT+ESS;PL
aldonvuitte	aldonvuiččel	ADJ;AT+ESS;SG
harjoitada	harjoitagat	V;IMP;PL;2;POS
kezalind	kezalinduikš	N;TRANS;PL
štanad	štanoil	N;AT+ESS;PL
kazvalikaz	kazvalikahiden	ADJ;GEN;PL
šobaiduz	šobaidused	N;NOM;PL
lehtišt	lehtištoiden	N;GEN;PL
mel’dütoitta	mel’dütoittas	V;PRS;PASS
bumagtegeline	bumagtegeližin	ADJ;FRML;PL
rentgen	rentgenaha	N;IN+ALL;SG
mannapudr	mannapudrodme	N;PROL;SG
perspektivitoi	perspektivitomal	ADJ;AT+ESS;SG
čanžoi	čanžojaha	N;IN+ALL;SG
küpsuz’	küpsudeks	N;TRANS;SG
živatrazv	živatrazvan	N;FRML;SG
avaruz’tandreh	avaruz’tandrehilesai	N;TERM;PL
keitoz	keitosihepäi	N;PRP;PL
naceine	naceižilpäi	ADJ;AT+ABL;PL
napern	napernoidenno	ADJ;APPRX;PL
übik	übikon	N;FRML;SG
muzahahk	muzahahkanno	N;APPRX;SG
marjkeitoz	marjkeitosiš	N;IN+ESS;PL
katkaižim	katkaižim	N;NOM;SG
hätkestoitta	hätkestoitaižiba	V;COND;PL;3;POS;PRS
garbol	garbloho	N;IN+ALL;SG
täuz’	täudespäi	ADJ;IN+ABL;SG
labotada	labotagha	V;IMP;SG;3;POS
mägišt	mägištoks	N;TRANS;SG
lainduz	laindusilpäi	N;AT+ABL;PL
puzerduz	puzerdusennopäi	N;ON+ABL;SG
taidehkuva	taidehkuva	N;ACC;SG
abittuda	abittunuižid	V;IPFV;COND;SG;2;POS;PST
avar	avarodme	ADJ;PROL;SG
ahtištuz	ahtištusihepei	N;PRP;PL
kaiv	kaiv	N;ACC;SG
märatoi	märatmile	ADJ;AT+ALL;PL
vähämeline	vähämeližilepäi	N;PRP;PL
jänduzkogo	jänduzkogoho	N;IN+ALL;SG
süvüz’	süvüded	N;NOM;PL
mägenlibutesed	mägenlibutesidme	N;PROL;PL
absol’utine	absol’utižehepäi	ADJ;PRP;SG
säritera	säriterannopäi	N;ON+ABL;SG
bipšta	bipškam	V;IMP;PL;1;POS
počtkühkjaine	počtkühkjaižidennoks	N;APPRX;PL
betonlava	betonlavoiden	N;GEN;PL
magitoitta	magitoitim	V;IPFV;IND;PL;1;POS;PST
käzirengaz	käzirengahidennoks	N;APPRX;PL
lapt	laptoid	N;PRT;PL
danialaine	danialaižehe	ADJ;IN+ALL;SG
maho	mahohosai	ADJ;TERM;SG
radiopagištoituz	radiopagištoitusiš	N;IN+ESS;PL
vezipomp	vezipompilesai	N;TERM;PL
allergii	allergijoikš	N;TRANS;PL
ičeladuine	ičeladuižen	ADJ;GEN;SG
löumai	löuman	ADJ;ACC;SG
etnografine	etnografižihepäi	ADJ;PRP;PL
kül’bendkoda	kül’bendkodikš	N;TRANS;PL
tedotai	tedotajile	N;AT+ALL;PL
käskta	käskim	V;IPFV;IND;PL;1;POS;PST
vastustada	vastustan	V;IND;SG;1;POS;PRS
tukuine	tukuižidenno	N;APPRX;PL
pormoi	pormoinke	N;COM;SG
ambundharjoituz	ambundharjoitusenno	N;APPRX;SG
alavuz’	alavuded	N;ACC;PL
lapt	laptoidennoks	N;APPRX;PL
mugavoita	mugavoinuižiba	V;IPFV;COND;PL;3;POS;PST
sihloine	sihloižin	N;FRML;PL
aigastada	aigastaba	V;IND;PL;3;POS;PRS
bipšta	bipštihe	V;IPFV;PST;PASS
vedändlaiv	vedändlaiv	N;NOM;SG
poikestada	poikestanuižin	V;IPFV;COND;SG;1;POS;PST
räk	räkidennopäi	ADJ;ON+ABL;PL
naiželuz’	naiželudenno	N;APPRX;SG
lapseline	lapseližihesai	N;TERM;PL
sulatada	sulatan	V;IND;SG;1;POS;PRS
agitator	agitatoran	N;GEN;SG
rahkiž	rahkiž	N;NOM;SG
kazvalikaz	kazvalikahilepäi	ADJ;PRP;PL
siled	siled	ADJ;ACC;SG
rahvazkund	rahvazkundidenno	N;APPRX;PL
kel’tedomez’	kel’tedomehižepäi	N;PRP;PL
pičkaita	pičkainuižid	V;IPFV;COND;SG;2;POS;PST
semen	semnilesai	N;TERM;PL
rivipol’	rivipoleks	N;TRANS;SG
sudäimuna	sudäimunilesai	N;TERM;PL
vin	vinad	N;ACC;PL
merilaid	merilaidoilepäi	N;PRP;PL
nügahir’	nügahirilepäi	N;PRP;PL
avonaine	avonaižed	ADJ;ACC;PL
südäimetomuz’	südäimetomudel	N;AT+ESS;SG
napern	napernoilesai	ADJ;TERM;PL
alič	aličulesai	N;TERM;SG
ristitrod	ristitroduidenke	N;COM;PL
kül’bendhosim	kül’bendhosimilpäi	N;AT+ABL;PL
il’manmäričim	il’manmäričiint	N;PRT;SG
pudr	pudroil	N;AT+ESS;PL
kačustada	kačustada	V;NFIN
panda	pane	V;IMP;SG;2;POS
mectuda	mectuim	V;IPFV;IND;PL;1;POS;PST
kabj	kabjoikš	N;TRANS;PL
torv	torven	N;GEN;SG
jagamatoi	jagamatomilesai	ADJ;TERM;PL
bröngvac	bröngvacalpäi	N;AT+ABL;SG
tedotai	tedotajad	N;ACC;PL
znamoitas	znamoičetoi	V;IND;SG;2;POS;PRS
hengituzvoibištelend	hengituzvoibištelend	N;ACC;SG
long’	longihe	N;IN+ALL;PL
kebneta	kebnenižin	V;COND;SG;1;POS;PRS
rujoheinpenzaz	rujoheinpenshil	N;AT+ESS;PL
kantele	kantelilpäi	N;AT+ABL;PL
suimata	suimazim	V;IPFV;IND;PL;1;POS;PST
maug	maugud	N;NOM;PL
bardveič	bardveičilpäi	N;AT+ABL;PL
söndkurk	söndkurkuiden	N;GEN;PL
abidoičii	abidoičijoilepäi	N;PRP;PL
nodj	nodjoil	N;AT+ESS;PL
ladv	ladvoišpäi	N;IN+ABL;PL
metkuz’	metkuden	N;ACC;SG
avovezi	avovedele	N;AT+ALL;SG
bobušteluz	bobuštelusespäi	N;IN+ABL;SG
pagl	paglan	N;GEN;SG
tilg	tilguihepäi	N;PRP;PL
sekund	sekundoilesai	N;TERM;PL
znamoičend	znamoičendoile	N;AT+ALL;PL
püžund	püžundalepäi	N;PRP;SG
hohotuz	hohotusilepäi	N;PRP;PL
letema	letema	N;NOM;SG
bajutuz	bajutusennopäi	N;ON+ABL;SG
paks	paksuiden	ADJ;GEN;PL
kahteluz	kahtelusidenke	N;COM;PL
lühünik	lühünikoidenno	N;APPRX;PL
sel’gaivod	sel’gaivoiš	N;IN+ESS;PL
briket	briketoidennoks	N;APPRX;PL
vihelta	vihelta	V;NFIN
tat	tatoilpäi	N;AT+ABL;PL
ukrainalaine	ukrainalaižid	ADJ;PRT;PL
universam	universamannopäi	N;ON+ABL;SG
puru	puru	N;NOM;SG
runosarn	runosarnad	N;NOM;PL
počt	počtikš	N;TRANS;PL
hormhein	hormheinihepäi	N;PRP;PL
märitas	märinuižihe	V;IPFV;COND;SG;3;POS;PST
raidpenzaz	raidpenzhad	N;ACC;PL
taigin	taignan	N;FRML;SG
sel’getoi	sel’getomalepäi	ADJ;PRP;SG
avaitas	avaidaižitoiš	V;COND;PL;2;POS;PRS
hormhein	hormheinilesai	N;TERM;PL
biznesabunik	biznesabunikoihepäi	N;PRP;PL
udištamine	udištamižin	N;FRML;PL
voik	voikud	N;ACC;PL
mödmeline	mödmeližiš	ADJ;IN+ESS;PL
sauvond	sauvondoiš	N;IN+ESS;PL
pigatulend	pigatulendoiš	N;IN+ESS;PL
üks’mujuine	üks’mujuižel	ADJ;AT+ESS;SG
pästred	pästrišpäi	N;IN+ABL;PL
biznes	biznesaspäi	N;IN+ABL;SG
gripk	gripkannoks	N;APPRX;SG
tervasine	tervasižidenno	ADJ;APPRX;PL
met	metoidennopäi	N;ON+ABL;PL
prihakark	prihakarkunnoks	N;APPRX;SG
hijamsu	hijamsud	N;ACC;PL
rämäita	rämäidaižiba	V;COND;PL;3;POS;PRS
süvämeline	süvämeline	ADJ;NOM;SG
liigeh	liigeheze	N;IN+ALL;SG
bardveič	bardveičele	N;AT+ALL;SG
omblii	omblijoil	N;AT+ESS;PL
pažag	pažagile	N;AT+ALL;PL
kändlop	kändlop	N;NOM;SG
astiihozjaine	astiihozjaižid	N;PRT;PL
kivekaz	kivekahas	ADJ;IN+ESS;SG
ločk	ločkus	N;IN+ESS;SG
tal’vte	tal’vted	N;NOM;PL
töpaja	töpajannopäi	N;ON+ABL;SG
türmata	türmanuižiba	V;IPFV;COND;PL;3;POS;PST
kaukol	kaukloiden	N;GEN;PL
vikateh	vikatehižesai	N;TERM;PL
nüblästada	nüblästadas	V;PRS;PASS
ozutadas	ozutanuižimoiš	V;IPFV;COND;PL;1;POS;PST
päivitadas	päivitadas	V;NFIN
todesine	todesištme	ADJ;PROL;SG
vida	vidoidennopäi	N;ON+ABL;PL
pijo	pijoilpäi	N;AT+ABL;PL
kaideta	kaidenid	V;IPFV;IND;SG;2;POS;PST
kasteluzkanav	kasteluzkanavoidennopäi	N;ON+ABL;PL
hilestada	hilestaba	V;IND;PL;3;POS;PRS
znamoita	znamoinuižin	V;IPFV;COND;SG;1;POS;PST
lagedišt	lagedištoihesai	N;TERM;PL
kumaiduz	kumaidused	N;NOM;PL
pano	panod	N;PRT;SG
bolgarialaine	bolgarialaiželesai	ADJ;TERM;SG
emindam	emindamidennopäi	N;ON+ABL;PL
agjatoi	agjatomidennoks	ADJ;APPRX;PL
tahtnik	tahtnikannoks	N;APPRX;SG
vällišpä	vällišpälpäi	ADJ;AT+ABL;SG
länged	längidme	N;PROL;PL
voz’kund	voz’kund	N;NOM;SG
sirp	sirpid	N;PRT;SG
parang	parangonnopäi	N;ON+ABL;SG
täutmatoi	täutmatoman	ADJ;ACC;SG
voik	voikuidennopäi	N;ON+ABL;PL
höunhišt	höunhištoihepäi	N;PRP;PL
pezualuine	pezualuižidenno	N;APPRX;PL
tippaita	tippaikat	V;IMP;PL;2;POS
pitte	piččhepäi	ADJ;PRP;SG
ištund	ištundoidennoks	N;APPRX;PL
paju	pajuilepäi	N;PRP;PL
norekaz	norekahaspäi	ADJ;IN+ABL;SG
sok	sok	N;ACC;SG
tabazuda	tabazuižim	V;COND;PL;1;POS;PRS
tilkuine	tilkuižidme	N;PROL;PL
eläda	elägaha	V;IMP;PL;3;POS
kodvuzznam	kodvuzznamalpäi	N;AT+ABL;SG
karv	karvoidennopäi	N;ON+ABL;PL
libedkel’	libedkeliš	N;IN+ESS;PL
čapatezhein	čapatezheinin	N;FRML;PL
ümbrikacund	ümbrikacundahasai	N;TERM;SG
rindatada	rindataiži	V;COND;SG;3;POS;PRS
rostkekaz	rostkekahannopäi	ADJ;ON+ABL;SG
suruz’mär	suruz’märalesai	N;TERM;SG
gradus	gradusanke	N;COM;SG
ümbärta	ümbärkaha	V;IMP;PL;3;POS
koivuine	koivuine	N;ACC;SG
nominacii	nominacijan	N;GEN;SG
nominacii	nominacijahapäi	N;PRP;SG
läbireig	läbireigus	N;IN+ESS;SG
ühtejitte	ühtejiččen	ADJ;GEN;SG
matksused	matksusedoil	N;AT+ESS;PL
pal’c	pal’chasai	N;TERM;SG
hillenduz	hillendusilesai	N;TERM;PL
žüri	žürišpäi	N;IN+ABL;PL
lemkta	lemgoid	V;IPFV;IND;SG;2;POS;PST
löda	löin	V;IPFV;IND;SG;1;POS;PST
sapburak	sapburakon	N;GEN;SG
avstrialaine	avstrialaiženno	ADJ;APPRX;SG
hahkač	hahkačuin	ADJ;FRML;PL
kidastuz	kidastusehepäi	N;PRP;SG
kirjanik	kirjanikoidennoks	N;APPRX;PL
peitkožui	peitkožujišpäi	N;IN+ABL;PL
kahnak	kahnakolpäi	ADJ;AT+ABL;SG
ümbärta	ümbärzin’	V;IPFV;IND;SG;1;POS;PST
bok	bokilepäi	N;PRP;PL
ülipigaline	ülipigaliženke	ADJ;COM;SG
uskotoitai	uskotoitajihepäi	ADJ;PRP;PL
taht	tahthosai	N;TERM;SG
naglaine	naglaižed	N;ACC;PL
žir	žirudme	N;PROL;SG
mokičuz	mokičusiš	N;IN+ESS;PL
lugutego	lugutegoišpäi	N;IN+ABL;PL
koumečogaine	koumečogaižehe	ADJ;IN+ALL;SG
holetoi	holetomidennopäi	ADJ;ON+ABL;PL
čahlida	čahlim	V;IPFV;IND;PL;1;POS;PST
lepäine	lepäižed	ADJ;ACC;PL
mez’ruk	mez’rukidenno	N;APPRX;PL
projekt	projektalpäi	N;AT+ABL;SG
ezipakičez	ezipakičesehesai	N;TERM;SG
aižastada	aižastanuižit	V;IPFV;COND;PL;2;POS;PST
mülündmär	mülündmäridennoks	N;APPRX;PL
kulištada	kulištim	V;IPFV;IND;PL;1;POS;PST
linol’	linoilepäi	N;PRP;SG
hul’voiže	hul’voiškišpäi	N;IN+ABL;PL
käta	kätas	V;PRS;PASS
kühkjaine	kühkjaižid	N;PRT;PL
lekar’	lekarihi	N;IN+ALL;SG
lämptuda	lämptunuiži	V;IPFV;COND;SG;3;POS;PST
elätada	elätanuižim	V;IPFV;COND;PL;1;POS;PST
rivipalič	rivipaličil	N;AT+ESS;PL
leg	legoidenno	N;APPRX;PL
pästand	pästandoidennopäi	N;ON+ABL;PL
süvä	süvänno	ADJ;APPRX;SG
tahtaz	tahthalesai	N;TERM;SG
makaz	makahaspäi	ADJ;IN+ABL;SG
toimitada	toimita	V;IMP;SG;2;POS
raccastamine	raccastamižen	N;GEN;SG
sinonim	sinonimanno	N;APPRX;SG
lukkol	luklon	N;ACC;SG
umbezjur’	umbezjurelepäi	N;PRP;SG
toine	toižid’	ADJ;PRT;PL
ero	eronnoks	N;APPRX;SG
pakaine	pakaižed	N;ACC;PL
ambundtarkuz’	ambundtarkuded	N;ACC;PL
korekaz	korekahidenke	ADJ;COM;PL
jändevändimed	jändevändimidenke	N;COM;PL
al’bom	al’bomidennopäi	N;ON+ABL;PL
ogahikaz	ogahikahiš	ADJ;IN+ESS;PL
azjatoi	azjatomannoks	ADJ;APPRX;SG
vezi	vezikš	N;TRANS;PL
biznes	biznesad	N;NOM;PL
manzikžom	manzikžomahapäi	N;PRP;SG
käskmaline	käskmaližehepäi	ADJ;PRP;SG
mät	mätoilepäi	N;PRP;PL
pohtta	pohti	V;IPFV;IND;SG;3;POS;PST
tineh	tinehilepäi	ADJ;PRP;PL
varz’	vardhesai	N;TERM;SG
ustavakaz	ustavakahannoks	ADJ;APPRX;SG
noikta	noiknuižin	V;IPFV;COND;SG;1;POS;PST
pil’da	pil’gam	V;IMP;PL;1;POS
kehuda	kehub	V;IND;SG;3;POS;PRS
ridaine	ridaižed	N;NOM;PL
augonotand	augonotandoid	N;PRT;PL
meletoi	meletomile	ADJ;AT+ALL;PL
anastuzjouk	anastuzjoukuikš	N;TRANS;PL
hohotuz	hohotuselesai	N;TERM;SG
sapburak	sapburakol	N;AT+ESS;SG
lapsestuz	lapsestusel	N;AT+ESS;SG
huigenzoituz	huigenzoituz	N;ACC;SG
hilestada	hilestad	V;IND;SG;2;POS;PRS
jäduda	jädui	V;IPFV;IND;SG;3;POS;PST
pidenzoitta	pidenzoiti	V;IPFV;IND;SG;3;POS;PST
vitiling	vitilingoišpäi	N;IN+ABL;PL
tazoitada	tazoitagat	V;IMP;PL;2;POS
heinmadoine	heinmadoižen	N;ACC;SG
meri	merilpäi	N;AT+ABL;PL
irdpol’	irdpoleks	N;TRANS;SG
akvarium	akvariumalpäi	N;AT+ABL;SG
bolgarialaine	bolgarialaižeks	N;TRANS;SG
letema	letemal	N;AT+ESS;SG
raccastamine	raccastamižennoks	N;APPRX;SG
ujui	ujujilesai	N;TERM;PL
ridelmatoi	ridelmatomile	ADJ;AT+ALL;PL
lekar’	lekar’	N;NOM;SG
čustak	čustakonnopäi	N;ON+ABL;SG
azeg	azegelepäi	N;PRP;SG
znamoita	znamoičižit	V;COND;PL;2;POS;PRS
peigol	peiglod	N;NOM;PL
imedas	imihe	V;IPFV;IND;PL;3;POS;PST
taktokaz	taktokahad	ADJ;NOM;PL
värištuda	värištub	V;IND;SG;3;POS;PRS
kühkjaine	kühkjaiželpäi	N;AT+ABL;SG
norištuda	norištugha	V;IMP;PL;3;POS
irdlämänmäričim	irdlämänmäričimehesai	N;TERM;SG
turistkeskuz	turistkeskusenno	N;APPRX;SG
čilaita	čilainuiži	V;IPFV;COND;SG;3;POS;PST
hoik	hoikahapäi	ADJ;PRP;SG
vedekaz	vedekast	ADJ;PRT;SG
räbed	räbedoikš	ADJ;TRANS;PL
poleta	polendaba	V;IND;PL;3;POS;PRS
bab	babaks	N;TRANS;SG
meri	merenno	N;APPRX;SG
kellotuz	kellotusidme	N;PROL;PL
paralleline	paralleliženke	ADJ;COM;SG
pitte	piččidennoks	ADJ;APPRX;PL
pitte	piččehesai	ADJ;TERM;SG
puhtazroduine	puhtazroduižihepäi	ADJ;PRP;PL
sündutuzmär	sündutuzmärihe	N;IN+ALL;PL
točind	točindoidennoks	N;APPRX;PL
jumalansä	jumalansänke	N;COM;SG
poukahtuda	poukahtunuižid	V;IPFV;COND;SG;2;POS;PST
pagl	pagloilpäi	N;AT+ABL;PL
päharjoituz	päharjoitusele	N;AT+ALL;SG
hakkida	hakkigaha	V;IMP;SG;3;POS
silitada	silitaižin’	V;COND;SG;1;POS;PRS
tundištoituz	tundištoitusidenke	N;COM;PL
hurapoline	hurapoližehesai	ADJ;TERM;SG
mokičuz	mokičusilesai	N;TERM;PL
biznes	biznesan	N;FRML;SG
räčkta	räčkat	V;IND;PL;2;POS;PRS
astii	astijahasai	N;TERM;SG
tozioiged	tozioiktahasai	ADJ;TERM;SG
mät	mätolepäi	N;PRP;SG
kazak	kazakoidenke	N;COM;PL
voik	voikud	N;NOM;PL
spravitada	spravitanuižim	V;IPFV;COND;PL;1;POS;PST
čuruine	čuruižen	ADJ;FRML;SG
näritada	näritadihe	V;IPFV;PST;PASS
tond	tondha	N;IN+ALL;SG
tirine	tirižen	N;GEN;SG
mavezieläjad	mavezieläjile	N;AT+ALL;PL
ujumišt	ujumištole	N;AT+ALL;SG
pabetk	pabetkod	N;NOM;PL
vägevuz’	vägevuden	N;GEN;SG
vajehtuz	vajehtust	N;PRT;SG
azjatomuz’	azjatomudehepäi	N;PRP;SG
čibuverk	čibuverkonnopäi	N;ON+ABL;SG
söndkurk	söndkurkuidenke	N;COM;PL
lehtezmec	lehtezmecal	N;AT+ESS;SG
kart	kartoihepäi	N;PRP;PL
irdpol’	irdpolilpäi	N;AT+ABL;PL
voi	vonnopäi	N;ON+ABL;SG
tartuteldas	tartutelihe	V;IPFV;IND;PL;3;POS;PST
emindam	emindamilpäi	N;AT+ABL;PL
viluku	vilukuiden	N;GEN;PL
oigedkirjutamine	oigedkirjutamižen	N;GEN;SG
vil’l’purn	vil’l’purnun	N;GEN;SG
fun’ahtoitta	fun’ahtoitnuižit	V;IPFV;COND;PL;2;POS;PST
voz’päiv	voz’päiväspäi	N;IN+ABL;SG
kelikorend	kelikorendoid	N;PRT;PL
lapsensöm	lapsensömädme	N;PROL;SG
viri	viridenke	N;COM;PL
ambuz	ambusehepäi	N;PRP;SG
tauguh	taughun	N;ACC;SG
jouhik	jouhik	N;NOM;SG
antarktine	antarktiženno	ADJ;APPRX;SG
vähäluguine	vähäluguižidme	ADJ;PROL;PL
konsonant	konsonantoiden	N;GEN;PL
tomišt	tomištonnoks	N;APPRX;SG
mel’mahtoine	mel’mahtoižehepäi	ADJ;PRP;SG
noikta	noikun	V;IND;SG;1;POS;PRS
keitänd	keitändoihesai	N;TERM;PL
šujeg	šujegelpäi	N;AT+ABL;SG
motokezr	motokezroilpäi	N;AT+ABL;PL
noikta	noikkaha	V;IMP;SG;3;POS
londuzkund	londuzkundaha	N;IN+ALL;SG
piringpacaz	piringpacaz	N;NOM;SG
dölta	dölnuižin	V;IPFV;COND;SG;1;POS;PST
tat	tatanno	N;APPRX;SG
kibedakaz	kibedakahanke	ADJ;COM;SG
starinoita	starinoičid	V;IPFV;IND;SG;2;POS;PST
keitänd	keitändoilesai	N;TERM;PL
äi	äjad	ADJ;NOM;PL
kahnak	kahnakoikš	ADJ;TRANS;PL
muilhodr	muilhodr	N;NOM;SG
haugaita	haugaidan	V;IND;SG;1;POS;PRS
matksused	matksusedal	N;AT+ESS;SG
sebrastada	sebrastadas	V;PRS;PASS
kahnak	kahnakoidennopäi	ADJ;ON+ABL;PL
pämehišt	pämehištolpäi	N;AT+ABL;SG
paks	pakshusai	ADJ;TERM;SG
röunatuz	röunatusin	N;FRML;PL
mehanine	mehanižed	ADJ;NOM;PL
imperfekt	imperfektahasai	N;TERM;SG
naglaine	naglaiželo	N;AT+ALL;SG
nadei	nadejannoks	N;APPRX;SG
emä	emišpäi	N;IN+ABL;PL
ehtkoline	ehtkoližil	N;AT+ESS;PL
käraita	käraidad	V;IND;SG;2;POS;PRS
ližatukad	ližatukidenke	N;COM;PL
mechaine	mechaižel	N;AT+ESS;SG
pestrak	pestrakod	N;PRT;SG
paindišt	paindištoil	N;AT+ESS;PL
pohtta	pohtaižid	V;COND;SG;2;POS;PRS
kelastai	kelastajan	N;GEN;SG
hüpindlava	hüpindlavan	N;GEN;SG
taboitelda	taboiteližiba	V;COND;PL;3;POS;PRS
nel’l’čoganik	nel’l’čoganikoilesai	N;TERM;PL
kündlekaz	kündlekastme	ADJ;PROL;SG
vägevuz’	vägevuden	N;FRML;SG
jodas	joe	V;IMP;SG;2;POS
keskvozine	keskvozišt	ADJ;PRT;SG
vald	valdoidenke	N;COM;PL
kärmehtida	kärmehtinuiži	V;IPFV;COND;SG;3;POS;PST
käbu	käbuidenno	N;APPRX;PL
harj	harjoilpäi	N;AT+ABL;PL
pehmed	pehmedoid	ADJ;PRT;PL
heled	heledas	ADJ;IN+ESS;SG
pakičuz	pakičusespäi	N;IN+ABL;SG
harjoiteluz	harjoiteluseks	N;TRANS;SG
udištamine	udištamižikš	N;TRANS;PL
ezipakičez	ezipakičesehepäi	N;PRP;SG
bakterii	bakterijoikš	N;TRANS;PL
virgaine	virgaižed	N;ACC;PL
riičta	riičižid	V;COND;SG;2;POS;PRS
antibiotine	antibiotišt	ADJ;PRT;SG
sak	sakulesai	N;TERM;SG
tugipu	tugipuks	N;TRANS;SG
sabitas	sabinuižimoiš	V;IPFV;COND;PL;1;POS;PST
mujupordhišt	mujupordhištod	N;ACC;PL
teplik	teplikoidennoks	N;APPRX;PL
sirtta	sirtkaha	V;IMP;SG;3;POS
änenhillenduz	änenhillendusidennoks	N;APPRX;PL
püštta	püštnuiži	V;IPFV;COND;SG;3;POS;PST
avtozavod	avtozavodaks	N;TRANS;SG
haižu	haižud	N;PRT;SG
puru	purunno	N;APPRX;SG
čanžotada	čanžotagha	V;IMP;SG;3;POS
haug	haugole	N;AT+ALL;SG
painuz	painuselesai	N;TERM;SG
kündlekaz	kündlekahan	ADJ;FRML;SG
vask	vaskehesai	N;TERM;SG
ero	eroilesai	N;TERM;PL
jouhik	jouhikole	N;AT+ALL;SG
pjesanpala	pjesanpalahasai	N;TERM;SG
mülündmär	mülündmäridenke	N;COM;PL
ojandeh	ojandehespäi	N;IN+ABL;SG
suruz’mär	suruz’märanke	N;COM;SG
kazvmuzližag	kazvmuzližagen	N;ACC;SG
vandhine	vandhižilpäi	N;AT+ABL;PL
ukol	ukoloihe	N;IN+ALL;PL
leg	legoin	N;FRML;PL
tervata	tervanuižid	V;IPFV;COND;SG;2;POS;PST
arvjärgenduz	arvjärgendustme	N;PROL;SG
leht	lehtihe	N;IN+ALL;PL
kebneta	kebneniba	V;IPFV;IND;PL;3;POS;PST
pigatulend	pigatulendan	N;ACC;SG
ristipoig	ristipoig	N;NOM;SG
nol	nolid	N;PRT;PL
hengahtada	hengahtaižim	V;COND;PL;1;POS;PRS
purnač	purnačunke	ADJ;COM;SG
abupaginkirj	abupaginkirjoidme	N;PROL;PL
sebr	sebroidenke	N;COM;PL
sätkulund	sätkulundan	N;ACC;SG
veruda	veru	V;IMP;SG;2;POS
pul’čak	pul’čakolesai	N;TERM;SG
prizor	prizoral	N;AT+ESS;SG
mäkätada	mäkäti	V;IPFV;IND;SG;3;POS;PST
vezisauptuz	vezisauptused	N;NOM;PL
puhtazroduine	puhtazroduine	ADJ;ACC;SG
käbu	käbud	N;PRT;SG
azartine	azartižihe	ADJ;IN+ALL;PL
helištada	helištagat	V;IMP;PL;2;POS
sekund	sekundaks	N;TRANS;SG
rižada	rižab	V;IND;SG;3;POS;PRS
tippaita	tippaidat	V;IND;PL;2;POS;PRS
kaičuzrengaz	kaičuzrenghaspäi	N;IN+ABL;SG
muštinpäiv	muštinpäividenke	N;COM;PL
bučinsurtte	bučinsurččehesai	ADJ;TERM;SG
andeltas	andelnuižimoi	V;IPFV;COND;SG;1;POS;PST
ambundhihtai	ambundhihtajad	N;PRT;SG
mectuz	mectust	N;PRT;SG
pilitesed	pilitesil	N;AT+ESS;PL
haudutada	haudutiba	V;IPFV;IND;PL;3;POS;PST
čopjaine	čopjaižed	N;ACC;PL
riičta	riiči	V;IPFV;IND;SG;3;POS;PST
aleta	aleb	V;IND;SG;3;POS;PRS
kormadand	kormadandoidme	N;PROL;PL
tiks	tiksuhu	N;IN+ALL;SG
vezivedoverk	vezivedoverk	N;ACC;SG
pättin	pättinaha	N;IN+ALL;SG
keväz’vezi	keväz’vedelesai	N;TERM;SG
bäkičend	bäkičendaha	N;IN+ALL;SG
sukaz	sukahaze	ADJ;IN+ALL;SG
vunuk	vunukoikš	N;TRANS;PL
rohtmatoi	rohtmatomaspäi	ADJ;IN+ABL;SG
jumalansä	jumalansäilpäi	N;AT+ABL;PL
purnač	purnačulesai	ADJ;TERM;SG
soudai	soudajid	N;PRT;PL
mel’hine	mel’hižiden	ADJ;GEN;PL
änestuzlaudkund	änestuzlaudkundidenke	N;COM;PL
pardesine	pardesižeks	ADJ;TRANS;SG
gips	gipsaks	N;TRANS;SG
libedkel’	libedkelihe	N;IN+ALL;PL
sömäiduz	sömäidusid	N;PRT;PL
pördutada	pörduti	V;IPFV;IND;SG;3;POS;PST
ruskota	ruskokam	V;IMP;PL;1;POS
tilg	tilguiden	N;GEN;PL
jonoikaz	jonoikahižepäi	ADJ;PRP;PL
taboitelda	taboitelin	V;IPFV;IND;SG;1;POS;PST
gor’a	gor’annoks	N;APPRX;SG
zel’l’	zel’l’annopäi	N;ON+ABL;SG
puskič	puskičuidennoks	ADJ;APPRX;PL
läpsahtada	läpsahtad	V;IND;SG;2;POS;PRS
manpind	manpindahapäi	N;PRP;SG
pu	puhupäi	N;PRP;SG
čapai	čapajidme	N;PROL;PL
bar	baroidennoks	N;APPRX;PL
abzac	abzacoikš	N;TRANS;PL
inehmoi	inehmoidennoks	N;APPRX;PL
čustak	čustakoidennoks	N;APPRX;PL
örkta	örgam	V;IND;PL;1;POS;PRS
kodiživat	kodiživatoihepäi	N;PRP;PL
sana	sanaspäi	N;IN+ABL;SG
hengtedod	hengtedoiš	N;IN+ESS;PL
satatada	satatanuiži	V;IPFV;COND;SG;3;POS;PST
sadmanzikaine	sadmanzikaiželpäi	N;AT+ABL;SG
ajamatoi	ajamatontme	ADJ;PROL;SG
long’	longidme	N;PROL;PL
kaks’modoine	kaks’modoižilepäi	ADJ;PRP;PL
ämbätez	ämbätesehe	N;IN+ALL;SG
ustavakaz	ustavakahidenke	ADJ;COM;PL
todištamatoi	todištamatomil	ADJ;AT+ESS;PL
kaum	kaumoidme	N;PROL;PL
pörde	pörtkennoks	N;APPRX;SG
ristlu	ristlun	N;GEN;SG
apak	apakonnoks	N;APPRX;SG
kazak	kazakas	N;IN+ESS;SG
taigin	taignalepäi	N;PRP;SG
küzeluz	küzelusehepäi	N;PRP;SG
päivmär	päivmäriden	N;GEN;PL
rahansirdäline	rahansirdäližihesai	ADJ;TERM;PL
piha	pihaoidennopäi	N;ON+ABL;PL
mäčkaita	mäčkainuižin	V;IPFV;COND;SG;1;POS;PST
long’	longilpäi	N;AT+ABL;SG
vas	vasoihepäi	N;PRP;PL
ižasiga	ižasigal	N;AT+ESS;SG
piduz’	piduzilesai	N;TERM;PL
registr	registroidennoks	N;APPRX;PL
artut’segoituz	artut’segoitusihe	N;IN+ALL;PL
soja	soja	N;NOM;SG
školanedeline	školanedeližidenno	ADJ;APPRX;PL
voz’päiv	voz’päivädme	N;PROL;SG
bahval	bahvalihepäi	N;PRP;PL
pämehišt	pämehištolepäi	N;PRP;SG
rebizuda	rebizuit	V;IPFV;IND;PL;2;POS;PST
vahvištoittas	vahvištoitkahas	V;IMP;SG;3;POS
amerikalaine	amerikalaižennoks	ADJ;APPRX;SG
änestamine	änestamižennoks	N;APPRX;SG
abzac	abzacoidenno	N;APPRX;PL
ezisijaline	ezisijaližiden	ADJ;GEN;PL
leht	lehtidennopäi	N;ON+ABL;PL
arvuz’	arvuded	N;NOM;PL
raudaine	raudaižeks	ADJ;TRANS;SG
ustavakaz	ustavakahin	ADJ;FRML;PL
čahlind	čahlindaspäi	N;IN+ABL;SG
tazoitada	tazoitad	V;IND;SG;2;POS;PRS
bar	baroikš	N;TRANS;PL
hijamsu	hijamsunke	N;COM;SG
boljom	boljomaha	N;IN+ALL;SG
haikta	haignuižid	V;IPFV;COND;SG;2;POS;PST
brinkta	bringnuiži	V;IPFV;COND;SG;3;POS;PST
lihav	lihavahapäi	ADJ;PRP;SG
balet	baletoišpäi	N;IN+ABL;PL
jumalatoi	jumalatoman	N;FRML;SG
voik	voikuhusai	N;TERM;SG
valita	valitihe	V;IPFV;PST;PASS
änestuzlaudkund	änestuzlaudkundišpäi	N;IN+ABL;PL
mokičuz	mokičusen	N;ACC;SG
kärpišk	kärpiškoidenno	N;APPRX;PL
suladuz	suladustme	N;PROL;SG
vida	vidha	N;IN+ALL;SG
aprobacii	aprobacijoilpäi	N;AT+ABL;PL
tip	tipoidenno	N;APPRX;PL
karv	karvale	N;AT+ALL;SG
borkukaz	borkukahannoks	ADJ;APPRX;SG
brilliantčomitez	brilliantčomitesele	N;AT+ALL;SG
hüde	hüdegin	N;FRML;PL
kastar’	kastarin	N;FRML;SG
argestamine	argestamižennopäi	N;ON+ABL;SG
ülikova	ülikovaks	ADJ;TRANS;SG
bukoi	bukoin	N;FRML;PL
süvä	süvädme	ADJ;PROL;SG
melaz	melahile	N;AT+ALL;PL
käziraudad	käziraudoilesai	N;TERM;PL
laudasine	laudasižehe	ADJ;IN+ALL;SG
honuzkazvmuz	honuzkazvmusil	N;AT+ESS;PL
kastar’	kastaridme	N;PROL;PL
jumalatoi	jumalatoi	ADJ;NOM;SG
paimetas	paimenuižihe	V;IPFV;COND;PL;3;POS;PST
honuzholitai	honuzholitai	N;NOM;SG
purnač	purnačunnoks	ADJ;APPRX;SG
pämal’l’	pämal’l’aha	N;IN+ALL;SG
kargsebr	kargsebralesai	N;TERM;SG
koditego	koditego	N;ACC;SG
jatkustada	jatkustagat	V;IMP;PL;2;POS
babarmonmaguine	babarmonmaguižiden	ADJ;GEN;PL
kävundmär	kävundmäras	N;IN+ESS;SG
vil’skta	vil’skkam	V;IMP;PL;1;POS
järed	järedoilesai	ADJ;TERM;PL
vezi	vezidenno	N;APPRX;PL
näk	näkihesai	N;TERM;PL
madoikaz	madoikahas	ADJ;IN+ESS;SG
ukrainalaine	ukrainalaižiden	N;GEN;PL
stauc	staucanno	N;APPRX;SG
herema	heremalesai	N;TERM;SG
murčak	murčakoiden	N;GEN;PL
bajutez	bajutesen	N;ACC;SG
lehtesenozutim	lehtesenozutimilepäi	N;PRP;PL
kurikoita	kurikoičid	V;IPFV;IND;SG;2;POS;PST
augtal’v	augtal’vilesai	N;TERM;PL
keskuzliha	keskuzlihoidennopäi	N;ON+ABL;PL
koritada	koritaiži	V;COND;SG;3;POS;PRS
boljom	boljomile	N;AT+ALL;PL
sein	seinäspäi	N;IN+ABL;SG
lämänvedo	lämänvedohopäi	N;PRP;SG
pijo	pijohopäi	N;PRP;SG
advokatine	advokatine	ADJ;ACC;SG
mez’ruk	mez’rukidme	N;PROL;PL
aptek	aptekannopäi	N;ON+ABL;SG
edelaigaine	edelaigaižehesai	ADJ;TERM;SG
lukkol	luklos	N;IN+ESS;SG
köhkitada	köhkitanuižid	V;IPFV;COND;SG;2;POS;PST
küzelendleht	küzelendlehtespäi	N;IN+ABL;SG
avovezi	avovedenke	N;COM;SG
unificiruida	unificirui	V;IPFV;IND;SG;3;POS;PST
hernesine	hernesižidennopäi	ADJ;ON+ABL;PL
aprobacii	aprobacijoid	N;PRT;PL
kelastai	kelastajale	N;AT+ALL;SG
tazoitada	tazoitanuižiba	V;IPFV;COND;PL;3;POS;PST
tantoine	tantoiženke	ADJ;COM;SG
läbireig	läbireigulpäi	N;AT+ABL;SG
vajehtuz	vajehtusin	N;FRML;PL
kündekaz	kündekahilpäi	ADJ;AT+ABL;PL
tal’vpäiv	tal’vpäividenke	N;COM;PL
mäčkart	mäčkartale	N;AT+ALL;SG
babičend	babičendannopäi	N;ON+ABL;SG
vellesed	vellesidenke	N;COM;PL
sirp	sirpilepäi	N;PRP;PL
elonkirjutai	elonkirjutajan	N;FRML;SG
sarv	sarvelpäi	N;AT+ABL;SG
tozioiged	tozioiktad	ADJ;PRT;SG
jähine	jähine	N;NOM;SG
veda	veižiba	V;COND;PL;3;POS;PRS
brilliant	brilliantoidme	N;PROL;PL
azjtedod	azjtedoidennopäi	N;ON+ABL;PL
počtansai	počtansajaspäi	N;IN+ABL;SG
koumevozne	koumevoččenke	ADJ;COM;SG
rečostada	rečostaba	V;IND;PL;3;POS;PRS
voz’satuz	voz’satusiš	N;IN+ESS;PL
babarmonmujuine	babarmonmujuižespäi	ADJ;IN+ABL;SG
rahantuloine	rahantuloiželesai	ADJ;TERM;SG
nozolzoitta	nozolzoitaižiba	V;COND;PL;3;POS;PRS
bant	bantoilesai	N;TERM;PL
jatkustada	jatkustanuižit	V;IPFV;COND;PL;2;POS;PST
ajai	ajajalepäi	N;PRP;SG
bapshaine	bapshaižilepäi	N;PRP;PL
abidsana	abidsanannoks	N;APPRX;SG
muštelta	muštle	V;IMP;SG;2;POS
keskustamatoi	keskustamatomilepäi	ADJ;PRP;PL
alastoi	alastomas	ADJ;IN+ESS;SG
maskiruida	maskiruit	V;IPFV;IND;PL;2;POS;PST
torskahtada	torskahtada	V;NFIN
tahtoimatoi	tahtoimatomannoks	ADJ;APPRX;SG
advokat	advokatan	N;FRML;SG
tärged	tärkthasai	ADJ;TERM;SG
latvialaine	latvialaižeks	ADJ;TRANS;SG
počtanoigendai	počtanoigendajile	N;AT+ALL;PL
hämähouk	hämähoukuhupäi	N;PRP;SG
telenägudez	telenägudesehepäi	N;PRP;SG
arvuz’	arvuz’	N;ACC;SG
norekaz	norekahile	ADJ;AT+ALL;PL
valdatoi	valdatoman	ADJ;GEN;SG
ühthižrad	ühthižradoihesai	N;TERM;PL
gagura	gaguroilesai	N;TERM;PL
peitmecnik	peitmecnikoin	N;FRML;PL
kirjamišt	kirjamištohosai	N;TERM;SG
imetajad	imetajad	N;NOM;PL
apel’sin	apel’sinoilesai	N;TERM;PL
kart	kartalepäi	N;PRP;SG
adivhonuz	adivhonusihesai	N;TERM;PL
babarmonmaguine	babarmonmaguižehepäi	ADJ;PRP;SG
il’meh	il’mehilepäi	N;PRP;PL
hörm	hörmanke	ADJ;COM;SG
ihastuda	ihastudas	V;PRS;PASS
aburadnik	aburadnik	N;NOM;SG
čvik	čvikuidenke	N;COM;PL
ristit	ristituiš	N;IN+ESS;PL
judaita	judaidaižit	V;COND;PL;2;POS;PRS
sel’gaivod	sel’gaivoid	N;PRT;PL
čibuverk	čibuverkod	N;PRT;SG
pühä	pühälpäi	ADJ;AT+ABL;SG
lühünik	lühünikoilpäi	N;AT+ABL;PL
alendamine	alendamižilesai	N;TERM;PL
änenhillenduz	änenhillendusiš	N;IN+ESS;PL
advokatine	advokatižed	ADJ;ACC;PL
aldonkorktuz’	aldonkorktut	N;PRT;SG
haudutez	hauduteseks	N;TRANS;SG
sogeta	sogened	V;IND;SG;2;POS;PRS
rižada	rižaižid	V;COND;SG;2;POS;PRS
riktas	rikoitoi	V;IPFV;IND;SG;2;POS;PST
azjanik	azjanikale	N;AT+ALL;SG
mez’	mehil	N;AT+ESS;PL
noikta	noikuižid	V;COND;SG;2;POS;PRS
kertihein	kertiheinälpäi	N;AT+ABL;SG
avovezi	avovedelpäi	N;AT+ABL;SG
pätnič	pätničoil	N;AT+ESS;PL
örkta	örgit	V;IPFV;IND;PL;2;POS;PST
böl’skahtada	böl’skahtin	V;IPFV;IND;SG;1;POS;PST
käretada	käretim	V;IPFV;IND;PL;1;POS;PST
sauvond	sauvondahasai	N;TERM;SG
šokopäline	šokopäližeks	N;TRANS;SG
annuliruida	annuliruižit	V;COND;PL;2;POS;PRS
rigoaig	rigoaigas	N;IN+ESS;SG
lämännavedii	lämännavedijad	ADJ;PRT;SG
kerita	keričet	V;IND;PL;2;POS;PRS
vokaline	vokaliželepäi	N;PRP;SG
inehmoi	inehmoid	N;NOM;PL
piringpacaz	piringpachilepäi	N;PRP;PL
lauk	laukoihessai	N;TERM;PL
avoin’su	avoin’sulpäi	N;AT+ABL;SG
rassal’	rassalinnopäi	N;ON+ABL;SG
augotuz	augotustme	N;PROL;SG
akvarium	akvariumahapäi	N;PRP;SG
ühtejitte	ühtejiččespäi	ADJ;IN+ABL;SG
adjektivine	adjektivižen	ADJ;FRML;SG
opeta	opekaha	V;IMP;PL;3;POS
painastada	painastin	V;IPFV;IND;SG;1;POS;PST
länged	längidenno	N;APPRX;PL
kezurm	kezurmihesai	N;TERM;PL
sel’g	sel’gähä	N;IN+ALL;SG
palahtuda	palahtunuižiba	V;IPFV;COND;PL;3;POS;PST
kuvazuda	kuvazudas	V;PRS;PASS
teplik	teplikoilepäi	N;PRP;PL
rihenduz	rihendusidennoks	N;APPRX;PL
viluku	vilukuuišpäi	N;IN+ABL;PL
kaukol	kauklhosai	N;TERM;SG
piduz’	piduzidennoks	N;APPRX;PL
verg	vergoilepäi	N;PRP;PL
pol’final	pol’finalaks	N;TRANS;SG
muhahtada	muhahtada	V;NFIN
has’ak	has’akol	N;AT+ESS;SG
sömänäl’gvoz’	sömänäl’gvozilesai	N;TERM;PL
lohkaita	lohkaitihe	V;IPFV;PST;PASS
voi	volpäi	N;AT+ABL;SG
vastustuztego	vastustuztegoilesai	N;TERM;PL
läbireig	läbireiguidennoks	N;APPRX;PL
tarinoita	tarinoičeba	V;IND;PL;3;POS;PRS
irdlämänmäričim	irdlämänmäričimelpäi	N;AT+ABL;SG
ap’	apidme	N;PROL;PL
tedotoi	tedotomile	ADJ;AT+ALL;PL
telekamer	telekamerannopäi	N;ON+ABL;SG
arvjärgenduz	arvjärgendust	N;PRT;SG
astiihozjaine	astiihozjaižilepäi	N;PRP;PL
kül’menzoitta	kül’menzoitaižid	V;COND;SG;2;POS;PRS
učubras	učubrasalesai	N;TERM;SG
päipol’	päipoled	N;NOM;PL
ülikova	ülikovidennopäi	ADJ;ON+ABL;PL
napersnik	napersnik	N;NOM;SG
jänduzvezituru	jänduzvezituru	N;ACC;SG
pit’khambaz	pit’khambhikš	ADJ;TRANS;PL
tundištelda	tundištelda	V;NFIN
klass	klassad	N;NOM;PL
näukta	näuguba	V;IND;PL;3;POS;PRS
surendeluz	surendelusen	N;FRML;SG
emä	emiš	N;IN+ESS;PL
sideg	sidegilesai	N;TERM;PL
zavetoita	zavetoičiži	V;COND;SG;3;POS;PRS
nogijüvä	nogijüvikš	N;TRANS;PL
azotadas	azotaižitoiš	V;COND;PL;2;POS;PRS
voimuz	voimusiš	N;IN+ESS;PL
virigzoitta	virigzoitiba	V;IPFV;IND;PL;3;POS;PST
biznes	biznesoil	N;AT+ESS;PL
märtego	märtegoid	N;PRT;PL
tedotelda	tedotelda	V;NFIN
sirtta	sirdim	V;IPFV;IND;PL;1;POS;PST
koskennišk	koskenniškalpäi	N;AT+ABL;SG
avovezi	avovedehepäi	N;PRP;SG
kuzenkavaged	kuzenkavagil	N;AT+ESS;PL
arguz’	argudes	N;IN+ESS;SG
kargištada	kargištaižit	V;COND;PL;2;POS;PRS
toi	tojad	N;ACC;PL
sauvond	sauvondoil	N;AT+ESS;PL
ruskedjur’salat	ruskedjur’salatoin	N;FRML;PL
gripk	gripkal	N;AT+ESS;SG
tihed	tihedoiden	ADJ;GEN;PL
hul’voiže	hul’voišken	N;FRML;SG
südeita	südeita	V;NFIN
mel’	melidme	N;PROL;PL
ližavärištelda	ližavärištelnuižim	V;IPFV;COND;PL;1;POS;PST
hajuriža	hajurižannoks	N;APPRX;SG
nodj	nodjodme	N;PROL;SG
ristipoig	ristipoigahapäi	N;PRP;SG
gradus	gradusad	N;PRT;SG
rehetas	rehenuižimoi	V;IPFV;COND;SG;1;POS;PST
vil’skta	vil’skkat	V;IMP;PL;2;POS
kadomine	kadomižihepäi	N;PRP;PL
bakteriolog	bakteriologan	N;FRML;SG
fun’ahtoitta	fun’ahtoitaba	V;IND;PL;3;POS;PRS
sebr	sebral	N;AT+ESS;SG
tegopä	tegopän	N;GEN;SG
päipol’	päipoliš	N;IN+ESS;PL
oleskelda	oleskelin	V;IPFV;IND;SG;1;POS;PST
velokezr	velokezroiden	N;GEN;PL
abzac	abzac	N;NOM;SG
seinlamp	seinlampad	N;PRT;SG
süvämeline	süvämeline	ADJ;ACC;SG
pästand	pästandad	N;PRT;SG
sulasolad	sulasolilpäi	N;AT+ABL;PL
tedontahtoine	tedontahtoižid	ADJ;PRT;PL
muštpacaz	muštpachal	N;AT+ESS;SG
pardesine	pardesižile	ADJ;AT+ALL;PL
heimostadas	heimostaižitoiš	V;COND;PL;2;POS;PRS
bajutez	bajutesen	N;FRML;SG
pehmik	pehmikod	N;NOM;PL
kävelehtta	kävelehtin	V;IPFV;IND;SG;1;POS;PST
alastoi	alastomihesai	ADJ;TERM;PL
nervakaz	nervakahale	ADJ;AT+ALL;SG
paks	paksud	ADJ;PRT;SG
sabitas	sabičižimoiš	V;COND;PL;1;POS;PRS
bibu	bibuikš	N;TRANS;PL
püžund	püžundoilepäi	N;PRP;PL
maorj	maorj	N;NOM;SG
hüpindlava	hüpindlavahasai	N;TERM;SG
mät	mätoilpäi	N;AT+ABL;PL
jouhik	jouhikonnopäi	N;ON+ABL;SG
kebneta	kebnendab	V;IND;SG;3;POS;PRS
kodima	kodimailesai	N;TERM;PL
tela	teloidme	N;PROL;PL
räzin	räzinahapäi	N;PRP;SG
gagura	gaguranno	N;APPRX;SG
atomambuz	atomambusidenke	N;COM;PL
agjatoi	agjatomin	ADJ;FRML;PL
käziraudad	käziraudoikš	N;TRANS;PL
kidajokseluz	kidajokselusehesai	N;TERM;SG
čunz’	čunz’uilesai	N;TERM;PL
honuzkazvmuz	honuzkazvmusin	N;FRML;PL
eripoline	eripolinežen	ADJ;GEN;SG
bombituz	bombitusikš	N;TRANS;PL
jänišanpirgad	jänišanpirgoil	N;AT+ESS;PL
lidnanagj	lidnanagjjoidenno	N;APPRX;PL
rivipalič	rivipaličale	N;AT+ALL;SG
papta	paptihe	V;IPFV;PST;PASS
starinoita	starinoinuižid	V;IPFV;COND;SG;2;POS;PST
pälustada	pälustam	V;IND;PL;1;POS;PRS
räčkta	räčkam	V;IND;PL;1;POS;PRS
ümbärta	ümbärda	V;IMP;SG;2;POS
muhahtada	muhahtanuižid	V;IPFV;COND;SG;2;POS;PST
kävelehtta	kävelehtaižin	V;COND;SG;1;POS;PRS
kuva	kuval	N;AT+ESS;SG
bask	baskoilesai	ADJ;TERM;PL
heled	heledahapäi	ADJ;PRP;SG
talutimed	talutimišpäi	N;IN+ABL;PL
kibedakaz	kibedakahile	ADJ;AT+ALL;PL
openduzraha	openduzrahan	N;FRML;SG
täudutoitta	täudutoitnuiži	V;IPFV;COND;SG;3;POS;PST
räpus	räpusel	N;AT+ESS;SG
pärp	pärp	N;ACC;SG
paralleline	paralleline	ADJ;ACC;SG
buhaita	buhaidaba	V;IND;PL;3;POS;PRS
ambund	ambundannopäi	N;ON+ABL;SG
jänišankorvaine	jänišankorvaižid	N;PRT;PL
räpus	räpusilpäi	N;AT+ABL;PL
ustavakaz	ustavakahiš	ADJ;IN+ESS;PL
kadomine	kadomižilepäi	N;PRP;PL
andmine	andmižid	N;PRT;PL
čilaiduz	čilaiduz	N;NOM;SG
kareg	karegile	N;AT+ALL;PL
meletoi	meletomaks	ADJ;TRANS;SG
kudoda	kudonuižimei	V;IPFV;COND;PL;1;POS;PST
valita	valinuižin’	V;IPFV;COND;SG;1;POS;PST
kaukol	kauklod	N;ACC;PL
koivuine	koivuižehepäi	N;PRP;SG
antipod	antipodidennopäi	N;ON+ABL;PL
arz’	arden	N;FRML;SG
plotušk	plotuškanno	N;APPRX;SG
jalam	jalamidennoks	N;APPRX;PL
kazvattuda	kazvattuižid	V;COND;SG;2;POS;PRS
zatinkoikaz	zatinkoikahiden	ADJ;GEN;PL
mustnahk	mustnahkalesai	ADJ;TERM;SG
velokezr	velokezr	N;NOM;SG
sok	sokuiš	N;IN+ESS;PL
abupaginkirj	abupaginkirjahapäi	N;PRP;SG
holvaz	holvhalepäi	ADJ;PRP;SG
telenägudez	telenägudeselesai	N;TERM;SG
aptek	aptekoidenno	N;APPRX;PL
buhaita	buhaižit	V;IPFV;IND;PL;2;POS;PST
nogijüvä	nogijüvänno	N;APPRX;SG
alenzoitamine	alenzoitamiženke	N;COM;SG
änenhillenduz	änenhillendusihe	N;IN+ALL;PL
vällišpä	vällišpäihesai	ADJ;TERM;PL
kor’	korilesai	N;TERM;PL
ilostoitta	ilostoitnuiži	V;IPFV;COND;SG;3;POS;PST
toi	tojil	N;AT+ESS;PL
jalam	jalamidenke	N;COM;PL
vokaline	vokaližehesai	N;TERM;SG
tazoitada	tazoitin	V;IPFV;IND;SG;1;POS;PST
paik	paikas	N;IN+ESS;SG
heittas	heitätoi	V;IND;SG;2;POS;PRS
čibuverk	čibuverkoks	N;TRANS;SG
avtoajai	avtoajajad	N;PRT;SG
zor’atähtaz	zor’atähthil	N;AT+ESS;PL
päsü	päsüks	N;TRANS;SG
azjtedod	azjtedoidme	N;PROL;PL
vihelta	vihelnuižit	V;IPFV;COND;PL;2;POS;PST
vada	vadoidennoks	N;APPRX;PL
kuha	kuhilpäi	N;AT+ABL;PL
paralleline	paralleližel	ADJ;AT+ESS;SG
tagasana	tagasanoil	N;AT+ESS;PL
hernesine	hernesiženke	ADJ;COM;SG
puskič	puskičuiden	ADJ;GEN;PL
čahlida	čahlida	V;NFIN
bolakaz	bolakahidennopäi	N;ON+ABL;PL
igä	igidme	N;PROL;PL
kaum	kaumale	N;AT+ALL;SG
tip	tipoile	N;AT+ALL;PL
tihed	tihedoidme	ADJ;PROL;PL
koumečoganik	koumečoganikaspäi	N;IN+ABL;SG
abutomuz’	abutomuzil	N;AT+ESS;PL
mel’nicnik	mel’nicnikoišpäi	N;IN+ABL;PL
meheluz	mehelusile	N;AT+ALL;PL
ahavoine	ahavoižidennoks	N;APPRX;PL
kelikorend	kelikorendoile	N;AT+ALL;PL
rindatada	rindataba	V;IND;PL;3;POS;PRS
keväz’il’m	keväz’il’malpäi	N;AT+ABL;SG
kulo	kulon	N;FRML;SG
muštelta	muštelnuižin	V;IPFV;COND;SG;1;POS;PST
ladeh	ladeht	N;PRT;SG
vitiling	vitilingolesai	N;TERM;SG
pühä	pühižepäi	N;PRP;PL
aspekt	aspektoiš	N;IN+ESS;PL
ambundpöud	ambundpöudoil	N;AT+ESS;PL
lülükaz	lülükahan	ADJ;ACC;SG
jom	jomilesai	N;TERM;PL
sambutada	sambutin	V;IPFV;IND;SG;1;POS;PST
paglkengäd	paglkengihepäi	N;PRP;PL
erilaine	erilaižehepäi	ADJ;PRP;SG
kivi	kivenke	N;COM;SG
boba-astii	boba-astijoihe	N;IN+ALL;PL
mokičuseline	mokičuseližeks	ADJ;TRANS;SG
elämatoi	elämatomidenke	ADJ;COM;PL
sohein	soheinikš	N;TRANS;PL
ostmine	ostmižel	N;AT+ESS;SG
valičused	valičusin	N;FRML;PL
päzutai	päzutajidennopäi	N;ON+ABL;PL
ližata	ližakaha	V;IMP;PL;3;POS
spravitada	spravitaižim	V;COND;PL;1;POS;PRS
äižiruine	äižiruižehe	ADJ;IN+ALL;SG
imeda	imid	V;IPFV;IND;SG;2;POS;PST
virgaine	virgaižišpäi	N;IN+ABL;PL
letema	letemanno	N;APPRX;SG
imičhein	imičheinännopäi	N;ON+ABL;SG
ambuz	ambusenno	N;APPRX;SG
jänduzvezi	jänduzvezil	N;AT+ESS;PL
oigedkirjutamine	oigedkirjutamižilesai	N;TERM;PL
long’	longil	N;AT+ESS;SG
abufond	abufondal	N;AT+ESS;SG
tropine	tropižeks	ADJ;TRANS;SG
rahvazkeskeine	rahvazkeskeštme	ADJ;PROL;SG
koht	kohtuihesai	N;TERM;PL
kandan’	kandmalepäi	N;PRP;SG
haugaita	haugaižit	V;IPFV;IND;PL;2;POS;PST
eläda	elädaze	V;IND;PL;3;POS;PRS
sabustada	sabusti	V;IPFV;IND;SG;3;POS;PST
gips	gipsan	N;GEN;SG
ihastuda	ihastugha	V;IMP;SG;3;POS
noid	noidhasai	N;TERM;SG
röunatuz	röunatused	N;NOM;PL
optimistine	optimistištme	ADJ;PROL;SG
röstta	röstab	V;IND;SG;3;POS;PRS
spravitada	spravitim	V;IPFV;IND;PL;1;POS;PST
sädatada	sädatadihe	V;IPFV;PST;PASS
bahval	bahvalidenke	N;COM;PL
aspekt	aspektoilepäi	N;PRP;PL
puru	puruin	N;FRML;PL
vei	vejan	N;ACC;SG
alastoi	alastomidennoks	ADJ;APPRX;PL
havadsu	havadsuil	N;AT+ESS;PL
sabustada	sabustim	V;IPFV;IND;PL;1;POS;PST
pakičuz	pakičusišpäi	N;IN+ABL;PL
hengahtada	hengahtim	V;IPFV;IND;PL;1;POS;PST
kabesine	kabesižennoks	ADJ;APPRX;SG
päipol’	päipolihe	N;IN+ALL;PL
ümbrikacund	ümbrikacund	N;ACC;SG
imedas	imegahas	V;IMP;SG;3;POS
hörm	hörman	ADJ;FRML;SG
taidehstudii	taidehstudii	N;NOM;SG
pul’čak	pul’čakolepäi	N;PRP;SG
motokezr	motokezroidenke	N;COM;PL
pühä	pühidme	ADJ;PROL;PL
alastoi	alastoi	ADJ;NOM;SG
puhtazroduine	puhtazroduižikš	ADJ;TRANS;PL
unohtada	unohtadas	V;PRS;PASS
kividuz	kividusidenno	N;APPRX;PL
napersnik	napersnikan	N;GEN;SG
toine	toižehesei	ADJ;TERM;SG
hämähouk	hämähoukuks	N;TRANS;SG
lindä	linnuižit	V;IPFV;COND;PL;2;POS;PST
kanznik	kanznikan	N;FRML;SG
paksuz’	paksudehe	N;IN+ALL;SG
babičend	babičendal	N;AT+ESS;SG
voi	voi	N;ACC;SG
üks’mujuine	üks’mujuižihepäi	ADJ;PRP;PL
babarmmado	babarmmadoilpäi	N;AT+ABL;PL
sohein	soheinidennoks	N;APPRX;PL
virkeh	virkehennoks	N;APPRX;SG
holvaz	holvast	ADJ;PRT;SG
ezipaukata	ezipauktam	V;IND;PL;1;POS;PRS
tozioiged	tozioiktaks	ADJ;TRANS;SG
pehmeta	pehmenit	V;IPFV;IND;PL;2;POS;PST
hakkida	hakkiba	V;IND;PL;3;POS;PRS
karvakaz	karvakahišpäi	ADJ;IN+ABL;PL
ločk	ločkud	N;PRT;SG
avto	avtonnoks	N;APPRX;SG
vellesed	vellesidenno	N;APPRX;PL
räpus	räpuselpäi	N;AT+ABL;SG
kaks’kezraine	kaks’kezraižidme	ADJ;PROL;PL
čikoi	čikoil	N;AT+ESS;SG
lidnanagj	lidnanagjan	N;FRML;SG
lühüd	lühüdoil	ADJ;AT+ESS;PL
läžegata	läžegata	V;NFIN
bobušteluz	bobuštelusenno	N;APPRX;SG
purde	purtked	N;NOM;PL
keradused	keradusidennoks	N;APPRX;PL
nodj	nodjod	N;ACC;PL
voita	voikaha	V;IMP;SG;3;POS
raudtelämoi	raudtelämoile	N;AT+ALL;PL
lämptuda	lämptun	V;IND;SG;1;POS;PRS
kahteluz	kahteluz	N;NOM;SG
muhahtada	muhahti	V;IPFV;IND;SG;3;POS;PST
hurapoline	hurapolišt	ADJ;PRT;SG
bolpaik	bolpaikaks	N;TRANS;SG
taboitelda	taboiteleb	V;IND;SG;3;POS;PRS
mez’ruk	mez’rukad	N;ACC;PL
sirdim	sirdimelepäi	N;PRP;SG
sofa	sofihe	N;IN+ALL;PL
tal’vpäiv	tal’vpäivänno	N;APPRX;SG
ambundtarkuz’	ambundtarkudehe	N;IN+ALL;SG
pühä	pühikš	N;TRANS;PL
kaida	kaivoin	V;IPFV;IND;SG;1;POS;PST
pämal’l’	pämal’l’ale	N;AT+ALL;SG
ocsein	ocseinilesai	N;TERM;PL
jäl’gestuz	jäl’gestusidenno	N;APPRX;PL
katil	katl’an	N;FRML;SG
nišk	niškoid’me	N;COM;PL
pehmik	pehmikonke	N;COM;SG
tabazuda	tabazui	V;IPFV;IND;SG;3;POS;PST
besedoičii	besedoičijoiš	N;IN+ESS;PL
sihlaine	sihlaižilpäi	N;AT+ABL;PL
huiktatoi	huiktatomanke	ADJ;COM;SG
bajutuz	bajutusenno	N;APPRX;SG
arz’	arzikš	N;TRANS;PL
räzin	räzin	N;ACC;SG
varjete	varjete	N;ACC;SG
ujui	ujujas	N;IN+ESS;SG
bard	bardalepäi	N;PRP;SG
nol	noledme	N;PROL;SG
hamatomuz’	hamatomuzidenke	N;COM;PL
poromado	poromadoiden	N;GEN;PL
kärmehtida	kärmehtit	V;IPFV;IND;PL;2;POS;PST
avangard	avangardoiden	N;GEN;PL
putustada	putustad	V;IND;SG;2;POS;PRS
kundaline	kundaline	ADJ;ACC;SG
lajindsana	lajindsanas	N;IN+ESS;SG
mairheline	mairheližilepäi	N;PRP;PL
kaičuzrengaz	kaičuzrenghalepäi	N;PRP;SG
rigoaig	rigoaigalpäi	N;AT+ABL;SG
arvostand	arvostandannoks	N;APPRX;SG
