hwealf	hwealf	N;ACC;SG
understondan	understōdon	V;IND;PL;PST
spiwan	spiwen	V.PTCP;PST
teran	tǣre	V;IND;SG;2;PST
forgifendlic	forġifendlīċan	ADJ;DAT;MASC;SG;LGSPEC1
cweccan	cweċċan	V;NFIN
ploh	plōgum	N;DAT;PL
deop	dēopes	ADJ;GEN;MASC;SG;LGSPEC2
gemagian	ġemagian	V;NFIN
yfel	yfla	ADJ;NOM;MASC;SG;LGSPEC1
geanlæcan	ġeānlǣhte	V;SBJV;SG;PST
gieddian	ġieddast	V;IND;SG;2;PRS
bisgian	bisġodon	V;IND;PL;PST
dæfte	dæfte	ADJ;NOM;MASC;PL;LGSPEC2
becuman	becym	V;IMP;SG
wilnian	wilnodest	V;IND;SG;2;PST
æþele	æþelra	ADJ;GEN;NEUT;PL;LGSPEC2
isceald	īsceald	ADJ;ACC;FEM;PL;LGSPEC2
fricu	frica	N;NOM;PL
hleahtor	hleahtre	N;DAT;SG
liþe	līþe	ADJ;ACC;NEUT;PL;LGSPEC2
biter	bitran	ADJ;GEN;SG;LGSPEC1
acol	āclum	ADJ;DAT;MASC;PL;LGSPEC1
deorc	deorcum	ADJ;INS;NEUT;PL;LGSPEC2
bucc	buccas	N;NOM;PL
frec	frece	ADJ;ACC;FEM;SG;LGSPEC2
elþeodig	elþēodġum	ADJ;DAT;NEUT;PL;LGSPEC1
etan	ǣte	V;IND;SG;2;PST
galfull	gālfullan	ADJ;INS;NEUT;SG;LGSPEC1
arleas	ārlēasra	ADJ;GEN;NEUT;PL;LGSPEC1
æþele	æþele	ADJ;ACC;NEUT;SG;LGSPEC2
geotan	ġēote	V;IND;SG;1;PRS
halig	hālġes	ADJ;GEN;FEM;SG;LGSPEC2
wordfæst	wordfæstre	ADJ;GEN;FEM;SG;LGSPEC2
dyhtig	dyhtiġra	ADJ;GEN;NEUT;PL;LGSPEC2
ƿeard	ƿearde	N;NOM;PL
brad	brādan	ADJ;GEN;MASC;SG;LGSPEC1
felahror	felahrōr	ADJ;NOM;FEM;SG;LGSPEC2
forstoppian	tō forstoppianne	V;NFIN
tiger	tigres	N;GEN;SG
colian	cōlie	V;IND;SG;1;PRS
castenere	castenerum	N;DAT;PL
isceald	īscealde	ADJ;ACC;MASC;PL;LGSPEC2
fealu	fealwe	ADJ;ACC;MASC;PL;LGSPEC2
geþing	geþing	N;ACC;SG
bereofan	berofen	V.PTCP;PST
geomor	ġēomoran	ADJ;DAT;MASC;SG;LGSPEC1
biter	bitre	ADJ;NOM;NEUT;SG;LGSPEC1
deor	dēora	N;GEN;PL
wilisc	wilscum	ADJ;DAT;PL;LGSPEC2
wiþmetenlic	wiþmetenlīċ	ADJ;NOM;MASC;SG;LGSPEC2
guþrof	gūþrōfe	ADJ;ACC;MASC;PL;LGSPEC2
logian	lōgode	V;IND;SG;3;PST
spowan	spēwst	V;IND;SG;2;PRS
penning	penninga	N;GEN;PL
geomor	ġēomoran	ADJ;INS;MASC;SG;LGSPEC1
holian	hōlode	V;SBJV;SG;PST
tacor	tācor	N;ACC;SG
bisig	bisiġre	ADJ;ACC;FEM;PL;LGSPEC2
losian	losiaþ	V;IND;PL;PRS
irnan	irneþ	V;IND;SG;3;PRS
aberendlic	āberendlīċe	ADJ;ACC;FEM;PL;LGSPEC2
generian	ġenerie	V;SBJV;SG;PRS
gehyran	ġehȳran	V;NFIN
trig	triġ	N;ACC;SG
mecgan	mecgen	V;SBJV;PL;PRS
hiwfæst	hīwfæstan	ADJ;INS;NEUT;SG;LGSPEC1
deop	dēop	ADJ;ACC;NEUT;PL;LGSPEC2
giefan	ġēafe	V;IND;SG;2;PST
drefan	drēfde	V;IND;SG;1;PST
brun	brūne	ADJ;NOM;FEM;PL;LGSPEC2
agnian	āgnod	V.PTCP;PST
burgræden	burgrǣdenne	N;ACC;PL
Nazarenisc	Nazarenisce	ADJ;ACC;MASC;PL;LGSPEC2
ardæde	ārdǣdan	ADJ;DAT;FEM;SG;LGSPEC1
elþeodig	elþēodġan	ADJ;DAT;FEM;SG;LGSPEC1
hleahtor	hleahtras	N;NOM;PL
gal	gāle	ADJ;ACC;MASC;PL;LGSPEC2
fæle	fǣlan	ADJ;GEN;SG;LGSPEC1
offrian	offraþ	V;IND;SG;3;PRS
wealcian	wealcoden	V;SBJV;PL;PST
ielden	ieldenne	N;NOM;PL
brad	brāda	ADJ;ACC;FEM;PL;LGSPEC2
spyrd	spyrde	N;DAT;SG
hersum	hērsume	ADJ;NOM;FEM;SG;LGSPEC1
gelæran	ġelǣran	V;NFIN
cwedol	cwedola	ADJ;NOM;FEM;PL;LGSPEC2
mildheortlic	mildheortlīċum	ADJ;DAT;FEM;PL;LGSPEC1
hatheort	hātheortum	ADJ;INS;FEM;PL;LGSPEC1
gifre	ġīfrre	ADJ;GEN;NEUT;SG;LGSPEC2
clipigendlic	clipiġendlīċra	ADJ;GEN;NEUT;PL;LGSPEC2
fæstan	ġefæsted	V.PTCP;PST
minsian	minsiġaþ	V;IMP;PL
offrian	offrian	V;NFIN
ƿeard	ƿeardas	N;NOM;PL
bidan	bīdende	V.PTCP;PRS
metetid	metetid	N;ACC;SG
badian	bāda	V;IMP;SG
teag	tēage	N;ACC;PL
ielden	ieldenes	N;GEN;SG
bæcere	bæcere	N;ACC;SG
acan	ace	V;SBJV;SG;PRS
read	rēade	ADJ;ACC;NEUT;SG;LGSPEC2
basu	baswan	ADJ;ACC;NEUT;SG;LGSPEC1
fægen	fæġenan	ADJ;ACC;FEM;PL;LGSPEC1
sefte	sēftum	ADJ;DAT;PL;LGSPEC1
lettan	tō lettanne	V;NFIN
foldbuend	foldbūend	N;NOM;SG
haligdom	hāliġdōmum	N;DAT;PL
aberendlic	āberendlīċena	ADJ;GEN;NEUT;PL;LGSPEC1
wæscan	wæsce	V;SBJV;SG;PRS
riman	rīmde	V;IND;SG;1;PST
gifre	ġīfrre	ADJ;DAT;NEUT;SG;LGSPEC2
angenga	ānġengan	N;ACC;PL
maþa	maþan	N;ACC;SG
wordfæst	wordfæsta	ADJ;NOM;FEM;PL;LGSPEC2
isiht	īsihte	ADJ;NOM;NEUT;SG;LGSPEC1
beterian	beteriaþ	V;IMP;PL
smocian	smocie	V;IND;SG;1;PRS
accent	accentes	N;GEN;SG
deop	dēopra	ADJ;GEN;MASC;PL;LGSPEC1
secgan	seċġende	V.PTCP;PRS
liþe	līþum	ADJ;DAT;PL;LGSPEC2
steorfan	steorf	V;IMP;SG
sweorfan	swurfe	V;IND;SG;2;PST
from	froman	ADJ;ACC;MASC;SG;LGSPEC1
grædig	grǣdiġan	ADJ;GEN;SG;LGSPEC1
scieppan	scōp	V;IND;SG;3;PST
domeadig	dōmēadġes	ADJ;GEN;NEUT;SG;LGSPEC2
wiþmetan	wiþmitst	V;IND;SG;2;PRS
sceadwian	sceadwiaþ	V;IMP;PL
hrop	hrōpas	N;NOM;PL
wacol	wacolum	ADJ;DAT;NEUT;PL;LGSPEC1
sweotol	sweotole	ADJ;ACC;FEM;PL;LGSPEC2
leoran	lēorden	V;SBJV;PL;PST
gecigendlic	ġeċīġendlīċra	ADJ;GEN;FEM;PL;LGSPEC2
andelbære	andelbǣrum	ADJ;INS;NEUT;PL;LGSPEC2
basu	baswum	ADJ;DAT;PL;LGSPEC1
myndleas	myndlēasan	ADJ;GEN;MASC;SG;LGSPEC1
fægen	fæġne	ADJ;ACC;FEM;SG;LGSPEC2
wacol	wacol	ADJ;NOM;NEUT;SG;LGSPEC2
þorp	þorp	N;ACC;SG
adeliht	adelihte	ADJ;ACC;FEM;PL;LGSPEC2
domeadig	dōmēadġe	ADJ;ACC;FEM;SG;LGSPEC2
traht	trahtum	N;DAT;PL
dæfte	dæfte	ADJ;NOM;MASC;SG;LGSPEC2
dilgian	dīlġiġe	V;IND;SG;1;PRS
clipigendlic	clipiġendlīċan	ADJ;DAT;NEUT;SG;LGSPEC1
guþbeorn	gūþbeornum	N;DAT;PL
bedælan	bedǣlde	V;IND;SG;3;PST
grædig	grǣdiġan	ADJ;DAT;SG;LGSPEC1
gleaw	glēawan	ADJ;ACC;MASC;SG;LGSPEC1
aheawan	ahēawest	V;IND;SG;2;PRS
cweccan	cwehte	V;SBJV;SG;PST
blotan	blōt	V;IMP;SG
domeadig	dōmēadġum	ADJ;DAT;NEUT;SG;LGSPEC2
punian	pūnie	V;IND;SG;1;PRS
widsiþ	wīdsīþ	N;NOM;SG
geascian	ġeāscode	V;IND;SG;1;PST
hyngran	hyngreden	V;SBJV;PL;PST
isceald	īscealdan	ADJ;DAT;SG;LGSPEC1
þenest	þēneste	N;GEN;SG
sweostor	ġesweostra	N;NOM;PL
wiþmetan	wiþmete	V;IMP;SG
birnan	birne	V;SBJV;SG;PRS
eaþdæde	ēaþdǣde	ADJ;NOM;NEUT;PL;LGSPEC2
gewyrcan	ġewyrċ	V;IMP;SG
yfel	yfle	ADJ;ACC;NEUT;SG;LGSPEC2
har	hārne	ADJ;ACC;MASC;SG;LGSPEC2
folm	folma	N;GEN;PL
est	ēstum	N;DAT;PL
feorm	feorme	N;DAT;SG
dead	dēade	ADJ;NOM;MASC;PL;LGSPEC2
wærc	wærc	N;ACC;SG
beorg	beorgum	N;DAT;PL
ƿeard	ƿearde	N;DAT;SG
beirnan	beirn	V;IMP;SG
onsendan	onsendaþ	V;IND;PL;PRS
adlig	ādliġ	ADJ;NOM;MASC;SG;LGSPEC2
mætan	tō mǣtanne	V;NFIN
lamb	lamb	N;ACC;SG
gewindan	ġewindeþ	V;IND;SG;3;PRS
fæger	fæġres	ADJ;GEN;MASC;SG;LGSPEC2
mare	maran	N;NOM;PL
spiwan	spiwe	V;IND;SG;2;PST
hildedeor	hildedēore	ADJ;INS;NEUT;SG;LGSPEC2
ealgian	ealgode	V;IND;SG;1;PST
gecigendlic	ġeċīġendlīċum	ADJ;INS;MASC;PL;LGSPEC2
hal	hāle	ADJ;NOM;MASC;PL;LGSPEC2
gearu	ġearwa	ADJ;NOM;NEUT;PL;LGSPEC2
wæflian	wæfliġaþ	V;IND;PL;PRS
andelbære	andelbǣrum	ADJ;DAT;NEUT;PL;LGSPEC1
dead	dēadra	ADJ;GEN;PL;LGSPEC1
gelic	ġelīċan	ADJ;GEN;NEUT;SG;LGSPEC1
fleogan	flīehþ	V;IND;SG;3;PRS
wendan	ġewended	V.PTCP;PST
þryccan	ġeþryct	V.PTCP;PST
geseon	ġesāwe	V;SBJV;SG;PST
swindan	swindaþ	V;IND;PL;PRS
hæst	hǣste	N;GEN;SG
blostmian	blōstmodon	V;IND;PL;PST
sweart	sweartum	ADJ;DAT;PL;LGSPEC1
ferian	tō ferianne	V;NFIN
þafian	ġeþafod	V.PTCP;PST
sniwan	snīw	V;IMP;SG
gal	gālan	ADJ;ACC;MASC;SG;LGSPEC1
brant	brantum	ADJ;DAT;FEM;PL;LGSPEC1
nealæcan	nēalǣċeþ	V;IND;SG;3;PRS
waru	wara	N;NOM;PL
bindan	bindan	V;NFIN
andelbære	andelbǣrena	ADJ;GEN;NEUT;PL;LGSPEC1
cynde	cynda	ADJ;NOM;MASC;SG;LGSPEC1
sceadwian	sceadwien	V;SBJV;PL;PRS
feccan	feċċaþ	V;IND;PL;PRS
Nazarenisc	Nazarenisce	ADJ;NOM;FEM;SG;LGSPEC1
frec	frecan	ADJ;NOM;FEM;PL;LGSPEC1
dyhtig	dyhtiġena	ADJ;GEN;NEUT;PL;LGSPEC1
deaf	dēafra	ADJ;GEN;MASC;PL;LGSPEC2
hæling	hǣlinga	N;GEN;PL
ƿeard	ƿearda	N;NOM;PL
fæge	fǣgu	ADJ;NOM;FEM;PL;LGSPEC2
hatheort	hātheortena	ADJ;GEN;MASC;PL;LGSPEC1
crincan	crincest	V;IND;SG;2;PRS
hreac	hrēace	N;DAT;SG
wynfæst	wynfæstan	ADJ;GEN;NEUT;SG;LGSPEC1
weorpan	weorp	V;IMP;SG
þringan	þringe	V;SBJV;SG;PRS
yfel	yflena	ADJ;GEN;PL;LGSPEC1
hreþig	hrēþiġan	ADJ;GEN;MASC;SG;LGSPEC1
blac	blāc	ADJ;ACC;FEM;PL;LGSPEC2
geong	ġeongan	ADJ;DAT;NEUT;SG;LGSPEC1
durran	dyrsten	V;SBJV;PL;PST
med	mēda	N;NOM;PL
moru	mora	N;ACC;PL
gleaw	glēawan	ADJ;ACC;FEM;SG;LGSPEC1
cornbære	cornbǣran	ADJ;GEN;MASC;SG;LGSPEC1
felahror	felahrōrum	ADJ;DAT;NEUT;PL;LGSPEC2
finul	finulas	N;ACC;PL
afigen	āfiġenum	ADJ;INS;NEUT;PL;LGSPEC1
wlitan	wlite	V;IND;SG;2;PST
brucan	brūce	V;IND;SG;1;PRS
gegræppian	ġegræppie	V;SBJV;SG;PRS
ƿebbestre	ƿebbestre	N;NOM;SG
grighund	grīġhunda	N;GEN;PL
bisig	bisiġan	ADJ;DAT;FEM;SG;LGSPEC1
blac	blāce	ADJ;ACC;NEUT;PL;LGSPEC2
fæge	fǣgum	ADJ;DAT;FEM;SG;LGSPEC2
wordfæst	wordfæste	ADJ;INS;MASC;SG;LGSPEC2
clipigendlic	clipiġendlīċan	ADJ;GEN;MASC;SG;LGSPEC1
acwincan	tō ācwincanne	V;NFIN
coþu	coþe	N;GEN;SG
wilnian	wilnode	V;IND;SG;3;PST
weardian	weardiġaþ	V;IMP;PL
reordberend	reordberend	N;NOM;PL
folc	folc	N;ACC;SG
onþracian	onþraciende	V.PTCP;PRS
medemian	medemiġende	V.PTCP;PRS
line	līnan	N;GEN;SG
hindrian	hindriġende	V.PTCP;PRS
gehende	ġehende	ADJ;INS;MASC;SG;LGSPEC2
breme	brēme	ADJ;INS;MASC;SG;LGSPEC2
asecgan	āsæġd	V.PTCP;PST
line	līne	N;NOM;SG
magian	magiġaþ	V;IND;PL;PRS
herian	hered	V.PTCP;PST
swindan	swindan	V;NFIN
cyþlæcan	cȳþlǣhte	V;IND;SG;1;PST
cwedol	cwedolan	ADJ;DAT;MASC;SG;LGSPEC1
ceorfan	curfe	V;IND;SG;2;PST
pytt	pyttum	N;DAT;PL
fæger	fæġrum	ADJ;DAT;PL;LGSPEC1
rimcræft	rīmcræft	N;ACC;SG
geanlæcan	ġeānlǣhtest	V;IND;SG;2;PST
blacian	blāciġe	V;SBJV;SG;PRS
bæddel	bæddlum	N;DAT;PL
glidan	glād	V;IND;SG;3;PST
acol	ācla	ADJ;ACC;FEM;PL;LGSPEC2
lec	lēcas	N;ACC;PL
leodan	lēad	V;IND;SG;1;PST
gecyþan	ġecȳþest	V;IND;SG;2;PRS
writan	write	V;SBJV;SG;PST
wacol	wacolra	ADJ;GEN;FEM;PL;LGSPEC1
freond	frēond	N;NOM;SG
þegnian	þeġna	V;IMP;SG
findig	findiġan	ADJ;ACC;FEM;PL;LGSPEC1
strynd	strȳndum	N;DAT;PL
ƿadan	ƿaden	V.PTCP;PST
dysig	dysġan	ADJ;INS;NEUT;SG;LGSPEC1
hindrian	hindriġe	V;SBJV;SG;PRS
swefan	swef	V;IMP;SG
flan	flāna	N;NOM;PL
hland	hland	N;NOM;SG
andefn	andefna	N;NOM;PL
freodom	freodomas	N;ACC;PL
þing	þinga	N;GEN;PL
ƿadan	ƿade	V;SBJV;SG;PRS
gesceaft	ġesċeafta	N;GEN;PL
hlynsian	hlynsiġe	V;IND;SG;1;PRS
blacian	blācie	V;SBJV;SG;PRS
weorcsum	weorcsumra	ADJ;GEN;FEM;PL;LGSPEC2
frec	frecra	ADJ;GEN;NEUT;PL;LGSPEC2
lustbære	lustbǣrum	ADJ;DAT;MASC;SG;LGSPEC2
findig	findiġum	ADJ;INS;MASC;PL;LGSPEC1
rodor	rodoras	N;ACC;PL
amirran	āmirde	V;SBJV;SG;PST
fagettan	fāgetten	V;SBJV;PL;PRS
brun	brūn	ADJ;NOM;NEUT;PL;LGSPEC2
bolgenmod	bolgenmōde	ADJ;NOM;MASC;PL;LGSPEC2
rinnan	rinne	V;SBJV;SG;PRS
gearu	ġearone	ADJ;ACC;MASC;SG;LGSPEC2
geomor	ġēomorena	ADJ;GEN;MASC;PL;LGSPEC1
herian	herest	V;IND;SG;2;PRS
todælan	tōdǣlende	V.PTCP;PRS
neotan	nēat	V;IND;SG;1;PST
dilgian	dīlġa	V;IMP;SG
cwedol	cwedolum	ADJ;DAT;NEUT;PL;LGSPEC1
fiscian	tō fiscianne	V;NFIN
scip	scipu	N;ACC;PL
hreþig	hrēþġe	ADJ;INS;NEUT;SG;LGSPEC2
þegnian	þeġnoden	V;SBJV;PL;PST
swaþrian	swaþrest	V;IND;SG;2;PRS
agnian	āgnode	V;SBJV;SG;PST
sigebeam	siġebēamum	N;DAT;PL
fæger	fæġre	ADJ;ACC;MASC;PL;LGSPEC2
forstoppian	forstoppiġende	V.PTCP;PRS
besteman	bestēmde	V;IND;SG;3;PST
undergan	undergān	V;SBJV;PL;PRS
brant	brantra	ADJ;GEN;MASC;PL;LGSPEC2
geagniendlic	ġeāgniendlīċe	ADJ;NOM;FEM;SG;LGSPEC1
felahror	felahrōrne	ADJ;ACC;MASC;SG;LGSPEC2
elþeodig	elþēodiġe	ADJ;NOM;NEUT;SG;LGSPEC1
getæsu	getæsu	N;DAT;PL
sæcc	sæċċe	N;GEN;SG
lif	līf	N;ACC;SG
profian	prōfiaþ	V;IND;PL;PRS
langoþ	langoþa	N;GEN;PL
arleas	ārlēasan	ADJ;INS;FEM;SG;LGSPEC1
geomor	ġēomore	ADJ;INS;NEUT;SG;LGSPEC2
bacan	bōc	V;IND;SG;1;PST
gleaw	glēawan	ADJ;ACC;NEUT;PL;LGSPEC1
hreþig	hrēþiġu	ADJ;NOM;NEUT;PL;LGSPEC2
bellan	bellaþ	V;IMP;PL
tacor	tācor	N;NOM;SG
dunn	dunne	ADJ;NOM;NEUT;SG;LGSPEC1
eþelweard	ēþelweardas	N;ACC;PL
geagniendlic	ġeāgniendlīċena	ADJ;GEN;NEUT;PL;LGSPEC1
hreþig	hrēþiġa	ADJ;NOM;MASC;SG;LGSPEC1
guþrof	gūþrōf	ADJ;ACC;NEUT;PL;LGSPEC2
leode	lēoda	N;GEN;PL
hean	hēanes	ADJ;GEN;MASC;SG;LGSPEC2
þæsma	þǣsmena	N;GEN;PL
forlætan	forlǣtende	V.PTCP;PRS
grafan	grafaþ	V;IMP;PL
egsian	eġsiġende	V.PTCP;PRS
magian	magodon	V;IND;PL;PST
crudan	crūdaþ	V;IMP;PL
hreowan	hrēowan	V;NFIN
grædig	grǣdiġu	ADJ;ACC;FEM;PL;LGSPEC2
geatolic	ġeatolīċu	ADJ;NOM;FEM;SG;LGSPEC2
byrde	byrdum	ADJ;INS;FEM;PL;LGSPEC2
waru	ware	N;GEN;SG
adlig	ādliġra	ADJ;GEN;MASC;PL;LGSPEC2
brant	brante	ADJ;ACC;FEM;PL;LGSPEC2
adlig	ādliġum	ADJ;INS;FEM;PL;LGSPEC2
forebisen	forebīsena	N;GEN;PL
blæc	blacum	ADJ;DAT;MASC;PL;LGSPEC2
wigbære	wīġbǣran	ADJ;NOM;MASC;PL;LGSPEC1
wiglian	wiġlod	V.PTCP;PST
swicol	swicolre	ADJ;GEN;FEM;SG;LGSPEC2
westerne	westerne	ADJ;NOM;NEUT;SG;LGSPEC2
wacol	wacolan	ADJ;GEN;FEM;SG;LGSPEC1
byrde	byrdan	ADJ;DAT;FEM;SG;LGSPEC1
inferan	infēraþ	V;IND;PL;PRS
freondleas	frēondlēasan	ADJ;ACC;MASC;SG;LGSPEC1
isiht	īsihtum	ADJ;DAT;NEUT;PL;LGSPEC1
guþrof	gūþrōfre	ADJ;DAT;FEM;SG;LGSPEC2
geoluread	ġeolurēad	ADJ;NOM;FEM;SG;LGSPEC2
grædig	grǣdiġum	ADJ;DAT;PL;LGSPEC2
erian	erede	V;IND;SG;3;PST
unnan	ann	V;IND;SG;1;PRS
acol	ācle	ADJ;NOM;FEM;SG;LGSPEC1
slupan	slupon	V;IND;PL;PST
domeadig	dōmēadġe	ADJ;ACC;MASC;PL;LGSPEC2
broga	brōgan	N;NOM;PL
hildedeor	hildedēore	ADJ;NOM;MASC;PL;LGSPEC2
geotan	ġēotaþ	V;IND;PL;PRS
brun	brūne	ADJ;ACC;FEM;PL;LGSPEC2
ƿacnes	ƿācnes	N;NOM;SG
þenest	þēnestum	N;DAT;PL
laþ	lāþa	ADJ;NOM;FEM;PL;LGSPEC2
gegræppian	ġegræppode	V;SBJV;SG;PST
onþracian	onþraciġende	V.PTCP;PRS
undergan	undergā	V;IMP;SG
hydan	hȳd	V;IMP;SG
halig	hālġan	ADJ;NOM;PL;LGSPEC1
isiht	īsihte	ADJ;INS;NEUT;SG;LGSPEC2
acol	ācle	ADJ;ACC;FEM;SG;LGSPEC2
onsendan	onsendaþ	V;IMP;PL
flowan	flēwþ	V;IND;SG;3;PRS
deon	dēode	V;IND;SG;1;PST
from	froman	ADJ;GEN;FEM;SG;LGSPEC1
wynfull	wynfullum	ADJ;INS;NEUT;PL;LGSPEC1
soþ	sōþ	N;ACC;SG
aberendlic	āberendlīċum	ADJ;INS;MASC;PL;LGSPEC2
andswarian	andswarie	V;SBJV;SG;PRS
fiscian	fiscie	V;IND;SG;1;PRS
bisgian	bisġast	V;IND;SG;2;PRS
blæwen	blǣwen	ADJ;NOM;FEM;SG;LGSPEC2
geap	ġēapan	ADJ;DAT;MASC;SG;LGSPEC1
hiwfæst	hīwfæstum	ADJ;DAT;FEM;PL;LGSPEC1
sellic	sellīċan	ADJ;GEN;FEM;SG;LGSPEC1
bletsian	blētsode	V;IND;SG;1;PST
fugol	fugla	N;GEN;PL
scinan	scine	V;IND;SG;2;PST
glædman	glædmanre	ADJ;GEN;FEM;SG;LGSPEC2
onwacan	onwacest	V;IND;SG;2;PRS
laþ	lāþ	ADJ;NOM;NEUT;PL;LGSPEC2
gæsne	gǣsne	ADJ;ACC;FEM;PL;LGSPEC2
fægen	fæġenum	ADJ;INS;MASC;PL;LGSPEC2
aheawan	ahēowon	V;IND;PL;PST
æþele	æþelan	ADJ;GEN;MASC;SG;LGSPEC1
breowan	brēow	V;IMP;SG
bispell	bīspelles	N;GEN;SG
anliepig	ānlīepġum	ADJ;DAT;NEUT;PL;LGSPEC2
salor	salore	N;DAT;SG
feallan	fealle	V;IND;SG;1;PRS
scafan	scōfe	V;IND;SG;2;PST
brant	brantum	ADJ;INS;FEM;PL;LGSPEC2
springan	sprungen	V.PTCP;PST
onþracian	onþracie	V;IND;SG;1;PRS
earmcearig	earmċeariġa	ADJ;ACC;NEUT;PL;LGSPEC2
tacor	tācora	N;GEN;PL
weorcsum	weorcsuman	ADJ;NOM;MASC;PL;LGSPEC1
weardian	weardiġe	V;SBJV;SG;PRS
deaf	dēafum	ADJ;DAT;NEUT;PL;LGSPEC1
fersc	ferscra	ADJ;GEN;MASC;PL;LGSPEC2
hwierfan	hwierfed	V.PTCP;PST
scua	scūan	N;GEN;SG
afor	āfre	ADJ;INS;NEUT;SG;LGSPEC2
wæflian	wæfloden	V;SBJV;PL;PST
flan	flānas	N;ACC;PL
sundrian	sundrien	V;SBJV;PL;PRS
scamian	scamiaþ	V;IMP;PL
græg	grǣġa	ADJ;ACC;FEM;PL;LGSPEC2
gecigendlic	ġeċīġendlīċan	ADJ;NOM;FEM;PL;LGSPEC1
hwettan	hwetest	V;IND;SG;2;PRS
dysig	dysiġum	ADJ;INS;NEUT;PL;LGSPEC1
frignan	ġefruġnen	V.PTCP;PST
bringan	ġebrōht	V.PTCP;PST
deop	dēopan	ADJ;GEN;MASC;SG;LGSPEC1
domeadig	dōmēadiġu	ADJ;NOM;FEM;SG;LGSPEC2
sweart	swearta	ADJ;NOM;MASC;SG;LGSPEC1
acol	ācolre	ADJ;ACC;FEM;PL;LGSPEC2
hwisprian	tō hwisprianne	V;NFIN
meteþegn	meteþegnas	N;NOM;PL
anliepig	ānlīepiġum	ADJ;DAT;MASC;SG;LGSPEC2
oþstandan	oþstænt	V;IND;SG;3;PRS
rocettan	roċeted	V.PTCP;PST
hlynsian	hlynsiġaþ	V;IND;PL;PRS
hildedeor	hildedēorum	ADJ;DAT;NEUT;PL;LGSPEC2
blostma	blōstman	N;DAT;SG
leccan	lehten	V;SBJV;PL;PST
fæle	fǣles	ADJ;GEN;FEM;SG;LGSPEC2
deop	dēopes	ADJ;GEN;NEUT;SG;LGSPEC2
friclu	fricle	N;ACC;SG
hildedeor	hildedēoran	ADJ;GEN;NEUT;SG;LGSPEC1
guþrof	gūþrōfa	ADJ;ACC;FEM;PL;LGSPEC2
dwæs	Neuter	ADJ;NOM;NEUT;SG;LGSPEC2
cweman	cwēmaþ	V;IMP;PL
breotan	brīett	V;IND;SG;3;PRS
breme	brēman	ADJ;ACC;NEUT;SG;LGSPEC1
stan	stāne	N;DAT;SG
hoppian	hoppode	V;IND;SG;3;PST
forgiefan	forġeaf	V;IND;SG;3;PST
wiþsacendlic	wiþsacendlīċum	ADJ;DAT;NEUT;PL;LGSPEC2
modig	mōdiġa	ADJ;NOM;NEUT;PL;LGSPEC2
dreamleas	drēamlēasum	ADJ;INS;FEM;PL;LGSPEC1
cwedol	cwedol	ADJ;ACC;NEUT;PL;LGSPEC2
fysan	fȳse	V;SBJV;SG;PRS
asecgan	āsǣden	V;SBJV;PL;PST
hring	hringas	N;ACC;PL
hyscan	ġehysced	V.PTCP;PST
þicce	þiccra	ADJ;GEN;NEUT;PL;LGSPEC2
wealcian	wealciġende	V.PTCP;PRS
isiht	īsihtra	ADJ;GEN;MASC;PL;LGSPEC1
gedryht	ġedryhta	N;ACC;PL
meltan	miltst	V;IND;SG;2;PRS
minsian	minsode	V;SBJV;SG;PST
anliepig	ānlīepġan	ADJ;ACC;FEM;PL;LGSPEC1
meltan	melten	V;SBJV;PL;PRS
acol	ācla	ADJ;NOM;FEM;PL;LGSPEC2
riman	rīmaþ	V;IND;PL;PRS
hildedeor	hildedēor	ADJ;ACC;NEUT;PL;LGSPEC2
purpuren	purpuren	ADJ;NOM;NEUT;SG;LGSPEC2
pucel	pūclas	N;ACC;PL
slecg	sleċġa	N;GEN;PL
weorcsum	weorcsumum	ADJ;INS;MASC;PL;LGSPEC1
wæflian	wæflien	V;SBJV;PL;PRS
wilisc	wiliscan	ADJ;GEN;SG;LGSPEC1
ærendian	ǣrendiġe	V;SBJV;SG;PRS
fæhþu	fǣhþe	N;DAT;SG
todrifan	tōdrīfest	V;IND;SG;2;PRS
alimpan	tō ālimpanne	V;NFIN
foresteall	forestealle	N;DAT;SG
hearpe	hearpena	N;GEN;PL
domeadig	dōmēadiġan	ADJ;NOM;NEUT;PL;LGSPEC1
gehyran	ġehȳre	V;IND;SG;1;PRS
abredwian	ābredwode	V;IND;SG;1;PST
dysig	dysiġum	ADJ;INS;FEM;PL;LGSPEC1
cnossian	cnossoden	V;SBJV;PL;PST
wynn	wynne	N;NOM;PL
gearu	ġearwe	ADJ;INS;NEUT;SG;LGSPEC2
ælagol	ǣlagolan	ADJ;ACC;MASC;SG;LGSPEC1
fersc	fersca	ADJ;ACC;FEM;PL;LGSPEC2
nihtgenga	nihtgengan	N;NOM;PL
arleas	ārlēasra	ADJ;GEN;FEM;PL;LGSPEC1
basu	basora	ADJ;GEN;PL;LGSPEC1
wynfæst	wynfæstan	ADJ;GEN;MASC;SG;LGSPEC1
hatan	hēton	V;IND;PL;PST
swaþrian	swaþrien	V;SBJV;PL;PRS
fæstnian	fæstniġe	V;IND;SG;1;PRS
geascian	ġeāsca	V;IMP;SG
blæwen	blǣwenum	ADJ;DAT;NEUT;PL;LGSPEC1
warian	wariġe	V;SBJV;SG;PRS
þing	þing	N;ACC;PL
fetian	fetiaþ	V;IND;PL;PRS
alimpan	ālumpon	V;IND;PL;PST
hildedeor	hildedēorre	ADJ;DAT;FEM;SG;LGSPEC2
wiþmetenlic	wiþmetenlīċan	ADJ;NOM;MASC;PL;LGSPEC1
bescufan	bescūf	V;IMP;SG
gisl	gisla	N;GEN;PL
abredwian	ġeābredwod	V.PTCP;PST
aliefan	ālīefden	V;SBJV;PL;PST
nest	nesta	N;GEN;PL
hlifian	hlifode	V;IND;SG;3;PST
pusa	pusan	N;GEN;SG
profian	prōfode	V;IND;SG;1;PST
wiþmetenlic	wiþmetenlīċum	ADJ;DAT;FEM;PL;LGSPEC1
lædan	lǣdde	V;IND;SG;3;PST
sceawian	scēawiaþ	V;IND;PL;PRS
cracian	cracaþ	V;IND;SG;3;PRS
bletsian	tō blētsianne	V;NFIN
from	froman	ADJ;ACC;FEM;SG;LGSPEC1
brun	brūn	ADJ;NOM;FEM;SG;LGSPEC2
sealh	sealh	N;ACC;SG
wynfull	wynfullum	ADJ;INS;NEUT;PL;LGSPEC2
ceowan	ċēowaþ	V;IMP;PL
ardæde	ārdǣdum	ADJ;DAT;MASC;SG;LGSPEC2
slitan	sliton	V;IND;PL;PST
geondferan	tō ġeondfēranne	V;NFIN
gesceaft	ġesċeaftes	N;GEN;SG
wandian	wandiġe	V;SBJV;SG;PRS
dugan	dohtest	V;IND;SG;2;PST
eaþdæde	ēaþdǣde	ADJ;ACC;FEM;SG;LGSPEC2
wiþsacendlic	wiþsacendlīċan	ADJ;DAT;MASC;SG;LGSPEC1
galfull	gālfulra	ADJ;GEN;NEUT;PL;LGSPEC1
weorcsum	weorcsuman	ADJ;GEN;NEUT;SG;LGSPEC1
geatolic	ġeatolīċan	ADJ;NOM;FEM;PL;LGSPEC1
þeodisc	þēodisc	N;ACC;PL
findig	findiġre	ADJ;GEN;FEM;SG;LGSPEC2
bispell	bīspell	N;NOM;SG
lustbære	lustbǣrena	ADJ;GEN;FEM;PL;LGSPEC1
geomor	ġēomran	ADJ;INS;NEUT;SG;LGSPEC1
burgræden	burgrǣdenne	N;NOM;PL
frec	frecena	ADJ;GEN;MASC;PL;LGSPEC1
galfull	gālfullan	ADJ;DAT;FEM;SG;LGSPEC1
isceald	īscealde	ADJ;NOM;NEUT;PL;LGSPEC2
finul	finul	N;ACC;SG
wynfull	wynfullan	ADJ;GEN;NEUT;SG;LGSPEC1
hyrne	hyrnan	N;ACC;PL
brun	brūnum	ADJ;INS;NEUT;PL;LGSPEC2
dragan	dragen	V.PTCP;PST
wiþmetenlic	wiþmetenlīċan	ADJ;DAT;NEUT;SG;LGSPEC1
earg	eargra	ADJ;GEN;FEM;PL;LGSPEC1
modig	mōdġa	ADJ;NOM;NEUT;PL;LGSPEC2
guþbeorn	gūþbeorn	N;ACC;SG
forþgewitan	forþġewiten	V;SBJV;PL;PST
adlig	ādliġe	ADJ;ACC;NEUT;PL;LGSPEC2
geseon	ġesāwe	V;IND;SG;2;PST
wordfæst	wordfæstum	ADJ;DAT;FEM;PL;LGSPEC1
sniþan	snāþ	V;IND;SG;1;PST
ascian	āsciġe	V;IND;SG;1;PRS
feþer	feþre	N;GEN;SG
ƿicce	ƿiċċum	N;DAT;PL
hleahtor	hleahtra	N;GEN;PL
modig	mōdiġum	ADJ;DAT;PL;LGSPEC1
midwist	midwist	N;NOM;SG
sæp	sæpu	N;NOM;PL
dugan	dūge	V;IMP;SG
tendan	tende	V;IND;SG;1;PRS
secgan	sæġde	V;SBJV;SG;PST
strengþo	strengþo	N;GEN;SG
fæger	fæġran	ADJ;GEN;SG;LGSPEC1
gecyþan	ġecȳþen	V;SBJV;PL;PRS
geolu	ġeolwum	ADJ;DAT;MASC;SG;LGSPEC2
warian	warodest	V;IND;SG;2;PST
Englisc	Engliscan	ADJ;NOM;NEUT;PL;LGSPEC1
cleofan	clēof	V;IMP;SG
fulian	fūlode	V;IND;SG;1;PST
wlitan	wliten	V.PTCP;PST
domeadig	dōmēadġan	ADJ;INS;MASC;SG;LGSPEC1
bocian	bōcode	V;IND;SG;3;PST
gefeon	tō ġefēonne	V;NFIN
abelgan	ābulgon	V;IND;PL;PST
lof	lofe	N;DAT;SG
rimere	rīmera	N;GEN;PL
deorc	deorc	ADJ;NOM;FEM;SG;LGSPEC2
wæflian	wæflaþ	V;IND;SG;3;PRS
lettan	letten	V;SBJV;PL;PST
habban	habbaþ	V;IMP;PL
gæsne	gǣsne	ADJ;ACC;MASC;PL;LGSPEC2
wrigian	wrīġiġen	V;SBJV;PL;PRS
brad	brād	ADJ;NOM;NEUT;SG;LGSPEC2
dyhtig	dyhtiġa	ADJ;ACC;FEM;PL;LGSPEC2
morþor	morþor	N;ACC;SG
fealu	fealu	ADJ;NOM;MASC;SG;LGSPEC2
biter	bitrum	ADJ;DAT;FEM;SG;LGSPEC2
smocian	smociġen	V;SBJV;PL;PRS
acol	ācolan	ADJ;DAT;FEM;SG;LGSPEC1
yþan	ȳþeþ	V;IND;SG;3;PRS
æþelu	æþelu	N;GEN;SG
sniwan	snīwdest	V;IND;SG;2;PST
yfel	yfel	ADJ;ACC;FEM;SG;LGSPEC2
prætt	prattas	N;NOM;PL
hersum	hērsume	ADJ;NOM;MASC;PL;LGSPEC2
alimpan	ālamp	V;IND;SG;3;PST
tynan	tȳnan	V;NFIN
lacan	lācaþ	V;IMP;PL
bitan	bite	V;SBJV;SG;PST
hreþig	hrēþiġena	ADJ;GEN;FEM;PL;LGSPEC1
pullian	pullode	V;IND;SG;3;PST
bleat	blēat	ADJ;NOM;NEUT;SG;LGSPEC2
weorcsum	weorcsume	ADJ;ACC;MASC;PL;LGSPEC2
æþm	ǣþmes	N;GEN;SG
sceawian	scēawa	V;IMP;SG
þrowian	þrowiġaþ	V;IMP;PL
ærendian	ǣrendie	V;IND;SG;1;PRS
wendan	wendest	V;IND;SG;2;PRS
axian	ġeāxod	V.PTCP;PST
durran	durre	V;SBJV;SG;PRS
stincan	stince	V;SBJV;SG;PRS
siþian	sīþie	V;SBJV;SG;PRS
æþele	æþela	ADJ;NOM;FEM;PL;LGSPEC2
mus	mūsa	N;GEN;PL
fegan	fēġaþ	V;IMP;PL
bleo	blēo	N;ACC;PL
fetian	fetiġaþ	V;IND;PL;PRS
pægel	pæġle	N;DAT;SG
burg	byriġ	N;NOM;PL
gieddian	tō ġieddianne	V;NFIN
halpenige	halpeniġe	N;DAT;SG
weorcsum	weorcsumra	ADJ;GEN;MASC;PL;LGSPEC1
dyfan	ġedȳfed	V.PTCP;PST
freodom	freodome	N;DAT;SG
libban	libben	V;SBJV;PL;PRS
benc	benċa	N;GEN;PL
burh	byriġ	N;DAT;SG
acol	āclan	ADJ;ACC;NEUT;PL;LGSPEC1
delfan	tō delfanne	V;NFIN
freondleas	frēondlēasan	ADJ;NOM;MASC;PL;LGSPEC1
brun	brūn	ADJ;ACC;NEUT;SG;LGSPEC2
siþian	sīþiġe	V;IND;SG;1;PRS
earg	eargum	ADJ;INS;FEM;PL;LGSPEC1
dyppan	dypte	V;SBJV;SG;PST
broc	brōce	N;DAT;SG
wynfull	wynfulra	ADJ;GEN;MASC;PL;LGSPEC2
hatan	heht	V;IND;SG;1;PST
liþe	līþra	ADJ;GEN;PL;LGSPEC1
swegl	swegla	N;GEN;PL
myndleas	myndlēasan	ADJ;ACC;MASC;PL;LGSPEC1
earmcearig	earmċeariġan	ADJ;GEN;SG;LGSPEC1
ascian	āsciġen	V;SBJV;PL;PRS
magian	magiġen	V;SBJV;PL;PRS
pullian	pulliaþ	V;IMP;PL
swicol	swicol	ADJ;NOM;MASC;SG;LGSPEC2
gestigan	ġestīge	V;IND;SG;1;PRS
laþ	lāþum	ADJ;DAT;MASC;PL;LGSPEC2
fæstnian	fæstnie	V;SBJV;SG;PRS
neaht	neaht	N;NOM;SG
þwean	þwōgon	V;IND;PL;PST
elþeodig	elþēodiġan	ADJ;GEN;NEUT;SG;LGSPEC1
glidan	glide	V;SBJV;SG;PST
eaþdæde	ēaþdǣdan	ADJ;DAT;NEUT;SG;LGSPEC1
andefn	andefna	N;GEN;PL
ielden	ieldenne	N;GEN;SG
anliepig	ānlīepiġum	ADJ;INS;FEM;PL;LGSPEC1
egsian	eġsiende	V.PTCP;PRS
fæge	fǣge	ADJ;ACC;FEM;PL;LGSPEC2
forstoppian	forstoppie	V;IND;SG;1;PRS
dead	dēadan	ADJ;ACC;PL;LGSPEC1
earg	eargan	ADJ;ACC;FEM;SG;LGSPEC1
lædan	lǣdde	V;SBJV;SG;PST
cene	cēne	ADJ;NOM;FEM;PL;LGSPEC2
weorcsum	weorcsumes	ADJ;GEN;NEUT;SG;LGSPEC2
gefeon	ġefēo	V;IND;SG;1;PRS
from	fromum	ADJ;DAT;NEUT;PL;LGSPEC2
þwean	þwēan	V;NFIN
feorsian	feorsiġaþ	V;IMP;PL
cweccan	cweċ	V;IMP;SG
swiþ	swīþan	ADJ;GEN;SG;LGSPEC1
agiefan	āġiefende	V.PTCP;PRS
abelgan	ābulgen	V;SBJV;PL;PST
felahror	felahrōrra	ADJ;GEN;MASC;PL;LGSPEC1
liget	līġete	N;DAT;SG
lædan	lǣdest	V;IND;SG;2;PRS
bidan	bide	V;SBJV;SG;PST
sceat	scēate	N;DAT;SG
cnihtwesende	cnihtwesendena	ADJ;GEN;PL;LGSPEC1
tendan	tendaþ	V;IND;PL;PRS
undergan	undergangende	V.PTCP;PRS
steorfan	sturfe	V;IND;SG;2;PST
acol	ācolan	ADJ;DAT;MASC;SG;LGSPEC1
basu	baswe	ADJ;ACC;FEM;SG;LGSPEC1
deorc	deorcan	ADJ;GEN;NEUT;SG;LGSPEC1
gifre	ġīfre	ADJ;ACC;MASC;PL;LGSPEC2
acan	acen	V.PTCP;PST
bispell	bīspell	N;ACC;SG
ungefæd	unġefæd	N;ACC;SG
yfel	yfelre	ADJ;DAT;NEUT;SG;LGSPEC2
lucan	lūcende	V.PTCP;PRS
wiþmetenlic	wiþmetenlīċre	ADJ;INS;FEM;SG;LGSPEC2
hatheort	hātheorte	ADJ;INS;MASC;SG;LGSPEC2
gæsne	gǣsne	ADJ;NOM;NEUT;SG;LGSPEC2
hreac	hrēacas	N;NOM;PL
penning	penningas	N;ACC;PL
fersc	ferscan	ADJ;GEN;FEM;SG;LGSPEC1
willian	willast	V;IND;SG;2;PRS
hwisprian	hwisprode	V;SBJV;SG;PST
socn	sōcne	N;DAT;SG
ifiht	īfihtum	ADJ;INS;NEUT;PL;LGSPEC1
domeadig	dōmēadġan	ADJ;NOM;FEM;PL;LGSPEC1
elþeodig	elþēodiġan	ADJ;NOM;MASC;PL;LGSPEC1
ƿracu	ƿraca	N;GEN;PL
wacol	wacolan	ADJ;NOM;MASC;PL;LGSPEC1
seomian	seomod	V.PTCP;PST
elþeodig	elþēodġan	ADJ;GEN;FEM;SG;LGSPEC1
earg	eargum	ADJ;DAT;MASC;PL;LGSPEC1
tima	tīman	N;ACC;PL
Englisc	Engliscum	ADJ;DAT;MASC;PL;LGSPEC2
wiþmetenlic	wiþmetenlīċan	ADJ;DAT;MASC;SG;LGSPEC1
bisgian	bisġiaþ	V;IMP;PL
bilewit	bilewites	ADJ;GEN;MASC;SG;LGSPEC2
andelbære	andelbǣrra	ADJ;GEN;FEM;PL;LGSPEC1
begang	begang	N;NOM;SG
wriþan	wride	V;IND;SG;2;PST
agnettan	tō āgnettanne	V;NFIN
findig	findiġum	ADJ;DAT;NEUT;PL;LGSPEC1
ƿacnes	ƿācnessa	N;ACC;PL
scieppan	scieppest	V;IND;SG;2;PRS
flacor	flacorra	ADJ;GEN;FEM;PL;LGSPEC2
fæstan	fæstest	V;IND;SG;2;PST
rinnan	runne	V;IND;SG;2;PST
æþele	æþelra	ADJ;GEN;MASC;PL;LGSPEC2
missan	misseþ	V;IND;SG;3;PRS
guþrof	gūþrōfan	ADJ;ACC;MASC;PL;LGSPEC1
afor	āfran	ADJ;NOM;PL;LGSPEC1
siþian	sīþiġaþ	V;IND;PL;PRS
fiscian	fisciġaþ	V;IND;PL;PRS
wearn	wearna	N;ACC;PL
flan	flān	N;ACC;SG
geagniendlic	ġeāgniendlīċra	ADJ;GEN;MASC;PL;LGSPEC1
dwæs	dwǣsan	ADJ;GEN;FEM;SG;LGSPEC1
stæfgefeg	stæfġefēġe	N;DAT;SG
offrian	offrien	V;SBJV;PL;PRS
mildheortlic	mildheortlīċan	ADJ;ACC;MASC;PL;LGSPEC1
anliepig	ānlīepiġum	ADJ;INS;MASC;PL;LGSPEC1
hyd	hȳda	N;NOM;PL
hæling	hǣling	N;NOM;SG
earg	eargan	ADJ;INS;FEM;SG;LGSPEC1
dropian	dropie	V;SBJV;SG;PRS
wynn	wynn	N;NOM;SG
bisig	bisiġum	ADJ;DAT;MASC;PL;LGSPEC1
blostma	blōstman	N;GEN;SG
herebeorgian	herebeorgiġende	V.PTCP;PRS
isiht	īsihte	ADJ;NOM;MASC;PL;LGSPEC2
weg	weġa	N;GEN;PL
sniwan	snīwden	V;SBJV;PL;PST
lustbære	lustbǣre	ADJ;ACC;FEM;PL;LGSPEC2
cynde	cyndes	ADJ;GEN;FEM;SG;LGSPEC2
breowan	brēowaþ	V;IND;PL;PRS
brad	brādan	ADJ;ACC;FEM;PL;LGSPEC1
holdscipe	holdschipe	N;DAT;SG
yþan	ȳþde	V;IND;SG;3;PST
growan	grōwen	V;SBJV;PL;PRS
forstoppian	forstoppie	V;SBJV;SG;PRS
glædman	glædmanena	ADJ;GEN;FEM;PL;LGSPEC1
slecg	sleċġum	N;DAT;PL
fulian	fūliġaþ	V;IND;PL;PRS
wiþmetan	wiþmet	V;IMP;SG
brun	brūnum	ADJ;DAT;FEM;PL;LGSPEC2
fegan	fēġeþ	V;IND;SG;3;PRS
acol	ācolre	ADJ;DAT;FEM;SG;LGSPEC2
leogan	lēog	V;IMP;SG
weardian	weardiġe	V;IND;SG;1;PRS
frec	frecum	ADJ;DAT;MASC;SG;LGSPEC2
spinnan	spann	V;IND;SG;1;PST
biter	bitee	ADJ;ACC;NEUT;PL;LGSPEC2
glædman	glædmanan	ADJ;NOM;NEUT;PL;LGSPEC1
ænlæcan	ǣnlǣhten	V;SBJV;PL;PST
hatan	hātaþ	V;IND;PL;PRS
gelic	ġelīċra	ADJ;GEN;MASC;PL;LGSPEC2
anliepig	ānlīepġe	ADJ;INS;NEUT;SG;LGSPEC2
cræft	cræft	N;ACC;SG
purpuren	purpurene	ADJ;ACC;FEM;PL;LGSPEC2
gelafian	ġelafoden	V;SBJV;PL;PST
þearm	þearma	N;GEN;PL
willan	wolde	V;IND;SG;3;PST
crudan	crȳt	V;IND;SG;3;PRS
morað	mōrað	N;ACC;SG
tungolcræft	tungolcræfta	N;GEN;PL
dreccan	dreccaþ	V;IMP;PL
cyning	cyning	N;ACC;SG
bleat	blēata	ADJ;NOM;MASC;SG;LGSPEC1
ærendian	ǣrendoden	V;SBJV;PL;PST
herian	tō herianne	V;NFIN
cornbære	cornbǣrum	ADJ;INS;NEUT;PL;LGSPEC2
isiht	īsihtum	ADJ;INS;NEUT;PL;LGSPEC2
animan	ānāmen	V;SBJV;PL;PST
þegnian	þeġnian	V;NFIN
earfoþe	earfoþre	ADJ;GEN;NEUT;SG;LGSPEC2
geolu	ġeolwan	ADJ;ACC;PL;LGSPEC1
siþian	sīþa	V;IMP;SG
scafan	scæfeþ	V;IND;SG;3;PRS
flacor	flacore	ADJ;NOM;FEM;PL;LGSPEC2
wlitan	wlīte	V;SBJV;SG;PRS
þryccan	þryhtest	V;IND;SG;2;PST
wordfæst	wordfæste	ADJ;ACC;NEUT;SG;LGSPEC1
forgifendlic	forġifendlīċum	ADJ;DAT;MASC;PL;LGSPEC1
yfel	yflum	ADJ;DAT;PL;LGSPEC2
uprodor	ūprodores	N;GEN;SG
hreþig	hrēþiġe	ADJ;NOM;NEUT;SG;LGSPEC1
salor	salores	N;GEN;SG
wigbære	wīġbǣrum	ADJ;DAT;FEM;PL;LGSPEC2
isceald	īsceald	ADJ;NOM;SG;LGSPEC2
nafu	nafum	N;DAT;PL
dreamleas	drēamlēas	ADJ;ACC;NEUT;PL;LGSPEC2
duru	durum	N;DAT;PL
bescufan	bescufe	V;SBJV;SG;PST
ladian	ġelādod	V.PTCP;PST
sweostor	ġesweostra	N;ACC;PL
andelbære	andelbǣran	ADJ;GEN;NEUT;SG;LGSPEC1
dysig	dysġan	ADJ;GEN;MASC;SG;LGSPEC1
elþeodig	elþēodiġan	ADJ;ACC;FEM;SG;LGSPEC1
cunnan	cunne	V;SBJV;SG;PRS
maþelian	ġemaþelod	V.PTCP;PST
dæfte	dæftra	ADJ;GEN;PL;LGSPEC1
brad	brāde	ADJ;ACC;MASC;PL;LGSPEC2
bellan	beal	V;IND;SG;3;PST
andswarian	andswaroden	V;SBJV;PL;PST
hreodan	hrēodende	V.PTCP;PRS
hring	hringa	N;GEN;PL
breme	brēmena	ADJ;GEN;PL;LGSPEC1
dwelian	dwelie	V;IND;SG;1;PRS
dyhtig	dyhtiġan	ADJ;NOM;NEUT;PL;LGSPEC1
wealcian	ġewealcod	V.PTCP;PST
slean	slōge	V;IND;SG;2;PST
ærendian	ǣrendien	V;SBJV;PL;PRS
beogang	bēogangas	N;NOM;PL
licgan	tō licganne	V;NFIN
brant	brantum	ADJ;INS;NEUT;PL;LGSPEC2
þwean	tō þwēanne	V;NFIN
swiþ	swīþ	ADJ;ACC;FEM;SG;LGSPEC2
medemian	medemie	V;SBJV;SG;PRS
dysig	dysiġra	ADJ;GEN;MASC;PL;LGSPEC2
brun	brūne	ADJ;INS;NEUT;SG;LGSPEC2
Nazarenisc	Nazareniscne	ADJ;ACC;MASC;SG;LGSPEC2
guþrof	gūþrōfa	ADJ;NOM;MASC;SG;LGSPEC1
leorningcild	leorningcildra	N;ACC;PL
from	froman	ADJ;INS;NEUT;SG;LGSPEC1
cwedol	cwedol	ADJ;NOM;NEUT;PL;LGSPEC2
begong	begongas	N;NOM;PL
starian	stariġende	V.PTCP;PRS
blæc	blacum	ADJ;INS;NEUT;PL;LGSPEC1
hors	horse	N;DAT;SG
wiþmetenlic	wiþmetenlīċan	ADJ;ACC;MASC;SG;LGSPEC1
maþelian	maþeliende	V.PTCP;PRS
eaþdæde	ēaþdǣdan	ADJ;INS;NEUT;SG;LGSPEC1
myndleas	myndlēasum	ADJ;DAT;MASC;PL;LGSPEC2
adeliht	adeliht	ADJ;NOM;MASC;SG;LGSPEC2
growan	grōwaþ	V;IMP;PL
duru	dura	N;GEN;PL
forlætan	forlēton	V;IND;PL;PST
Englisc	Engliscan	ADJ;DAT;FEM;SG;LGSPEC1
deop	dēopum	ADJ;INS;MASC;PL;LGSPEC2
nædre	nædran	N;ACC;PL
from	fromre	ADJ;DAT;FEM;SG;LGSPEC2
fus	fūse	ADJ;ACC;FEM;PL;LGSPEC2
ceorran	ċearr	V;IND;SG;3;PST
feþer	feþra	N;ACC;PL
beran	bǣron	V;IND;PL;PST
nabban	nafaþ	V;IND;SG;3;PRS
laþ	lāþum	ADJ;DAT;FEM;PL;LGSPEC1
isiht	īsihtan	ADJ;INS;NEUT;SG;LGSPEC1
cweman	cwēme	V;SBJV;SG;PRS
al	āl	N;NOM;PL
elþeodig	elþēodġes	ADJ;GEN;MASC;SG;LGSPEC2
deorc	deorcan	ADJ;DAT;MASC;SG;LGSPEC1
leofwende	lēofwendes	ADJ;GEN;MASC;SG;LGSPEC2
sinnan	sinnen	V;SBJV;PL;PRS
freondleas	frēondlēasan	ADJ;GEN;MASC;SG;LGSPEC1
unlucan	unlūcaþ	V;IMP;PL
manfordædla	mānfordǣdla	N;NOM;SG
gifre	ġīfrena	ADJ;GEN;PL;LGSPEC1
græg	grǣġum	ADJ;DAT;MASC;PL;LGSPEC1
ferian	ferede	V;SBJV;SG;PST
ifiht	īfiht	ADJ;NOM;FEM;SG;LGSPEC2
elþeodig	elþēodġan	ADJ;INS;MASC;SG;LGSPEC1
dropian	dropien	V;SBJV;PL;PRS
migan	māh	V;IND;SG;1;PST
cene	cēnes	ADJ;GEN;FEM;SG;LGSPEC2
modig	mōdġu	ADJ;NOM;FEM;SG;LGSPEC2
bescufan	bescofen	V.PTCP;PST
frefran	frēfrede	V;IND;SG;1;PST
fægen	fæġnan	ADJ;NOM;MASC;PL;LGSPEC1
secgan	seċġaþ	V;IMP;PL
wohsum	wōhsume	ADJ;NOM;MASC;PL;LGSPEC2
inhold	inholdre	ADJ;DAT;NEUT;SG;LGSPEC2
þrawan	þrēawen	V;SBJV;PL;PST
ælagol	ǣlagolra	ADJ;GEN;FEM;PL;LGSPEC2
laþ	lāþe	ADJ;NOM;NEUT;SG;LGSPEC1
pucel	pūcles	N;GEN;SG
ceorran	ċeorraþ	V;IMP;PL
cyþlæcan	cȳþlǣċan	V;NFIN
bisgian	bisġiġaþ	V;IMP;PL
lygen	lyġenne	N;ACC;SG
forgifendlic	forġifendlīċum	ADJ;INS;MASC;PL;LGSPEC1
acwician	acwicie	V;SBJV;SG;PRS
brun	brūna	ADJ;NOM;MASC;SG;LGSPEC1
bolgenmod	bolgenmōd	ADJ;NOM;MASC;SG;LGSPEC2
modig	mōdiġan	ADJ;DAT;SG;LGSPEC1
axian	āxodon	V;IND;PL;PST
æfæst	ǣfæstum	ADJ;DAT;MASC;PL;LGSPEC1
æced	æċede	N;DAT;SG
adlig	ādliġan	ADJ;NOM;NEUT;PL;LGSPEC1
mamorian	mamorie	V;IND;SG;1;PRS
adeliht	adeliht	ADJ;ACC;NEUT;SG;LGSPEC2
langian	langie	V;IND;SG;1;PRS
gryre	gryres	N;GEN;SG
reordberend	reordberend	N;ACC;SG
flacor	flacore	ADJ;ACC;FEM;PL;LGSPEC2
domeadig	dōmēadiġum	ADJ;DAT;MASC;PL;LGSPEC1
Englisc	Engliscum	ADJ;INS;FEM;PL;LGSPEC2
wisdom	wīsdōm	N;NOM;SG
cene	cēnena	ADJ;GEN;PL;LGSPEC1
friclu	friclu	N;NOM;SG
flett	flett	N;NOM;SG
blæwen	blǣwenan	ADJ;INS;MASC;SG;LGSPEC1
lac	lāc	N;NOM;PL
blæc	blace	ADJ;ACC;FEM;PL;LGSPEC2
aliefan	ālīefaþ	V;IND;PL;PRS
wynn	wynnum	N;DAT;PL
bisgian	bisġiġende	V.PTCP;PRS
æmtian	ǣmtodon	V;IND;PL;PST
mildheortlic	mildheortlīċne	ADJ;ACC;MASC;SG;LGSPEC2
þafian	þafode	V;IND;SG;3;PST
dwæs	dwǣsra	ADJ;DAT;FEM;SG;LGSPEC2
þrowian	þrowiġende	V.PTCP;PRS
elþeodig	elþēodiġan	ADJ;INS;NEUT;SG;LGSPEC1
nagan	nāhtaþ	V;IMP;PL
har	hārra	ADJ;GEN;FEM;PL;LGSPEC2
dysig	dysġa	ADJ;ACC;FEM;PL;LGSPEC2
yfel	yfelan	ADJ;GEN;SG;LGSPEC1
grædig	grǣdiġu	ADJ;NOM;FEM;PL;LGSPEC2
secan	sēċaþ	V;IMP;PL
dwæs	dwǣsan	ADJ;ACC;FEM;SG;LGSPEC1
þenian	þēniġaþ	V;IND;PL;PRS
cnearr	cnearre	N;DAT;SG
losian	tō losianne	V;NFIN
geascian	ġeāscoden	V;SBJV;PL;PST
fægen	fæġnum	ADJ;DAT;MASC;SG;LGSPEC2
wigbære	wīġbǣrum	ADJ;INS;FEM;PL;LGSPEC1
ealgian	ealgien	V;SBJV;PL;PRS
racente	racentan	N;DAT;SG
risan	rīsende	V.PTCP;PRS
mus	mūsum	N;DAT;PL
fyndel	fyndele	N;ACC;PL
dunn	dunn	ADJ;NOM;MASC;SG;LGSPEC2
begong	begonga	N;GEN;PL
hwisprian	hwisprodon	V;IND;PL;PST
cnihtwesende	cnihtwesendum	ADJ;DAT;FEM;SG;LGSPEC2
ræcan	rǣċe	V;SBJV;SG;PRS
arleas	ārlēasa	ADJ;NOM;FEM;PL;LGSPEC2
mamorian	mamora	V;IMP;SG
æced	æċed	N;ACC;PL
modig	mōdġu	ADJ;NOM;FEM;PL;LGSPEC2
dyhtig	dyhtiġan	ADJ;INS;MASC;SG;LGSPEC1
hreowan	ġehrowen	V.PTCP;PST
wynfæst	wynfæstra	ADJ;GEN;FEM;PL;LGSPEC1
read	rēadan	ADJ;GEN;SG;LGSPEC1
wiþmetenlic	wiþmetenlīċra	ADJ;GEN;NEUT;PL;LGSPEC2
wynfæst	wynfæste	ADJ;ACC;FEM;SG;LGSPEC2
gifre	ġīfrum	ADJ;DAT;MASC;SG;LGSPEC2
þrysmian	þrysmiende	V.PTCP;PRS
mætan	mǣtte	V;SBJV;SG;PST
weorc	weorces	N;GEN;SG
heawan	hēawende	V.PTCP;PRS
yfel	yfelan	ADJ;ACC;MASC;SG;LGSPEC1
fæle	fǣlum	ADJ;DAT;MASC;SG;LGSPEC2
galfull	gālfullan	ADJ;GEN;MASC;SG;LGSPEC1
swindan	ġeswunden	V.PTCP;PST
unwæstmbære	unwæstmbǣre	ADJ;ACC;FEM;SG;LGSPEC2
inca	incum	N;DAT;PL
bleaþ	blēaþ	ADJ;NOM;NEUT;SG;LGSPEC2
ænlic	ǣnlīċra	ADJ;GEN;NEUT;PL;LGSPEC1
bilehwit	bilehwītum	ADJ;DAT;MASC;PL;LGSPEC1
wynsum	wynsumum	ADJ;DAT;NEUT;PL;LGSPEC2
leaslic	lēaslīċu	ADJ;NOM;NEUT;PL;LGSPEC2
deagol	dēagole	ADJ;ACC;FEM;SG;LGSPEC2
sceafa	sceafan	N;ACC;SG
gebyrde	ġebyrdne	ADJ;ACC;MASC;SG;LGSPEC2
bledsian	blēdsiġen	V;SBJV;PL;PRS
deogol	dēogole	ADJ;ACC;NEUT;SG;LGSPEC1
mod	mōd	N;NOM;SG
mindom	mindōmum	N;DAT;PL
forgietan	tō forġietanne	V;NFIN
limpan	lumpon	V;IND;PL;PST
dufan	dēaf	V;IND;SG;1;PST
blodreow	blōdrēowum	ADJ;DAT;FEM;PL;LGSPEC1
mihtig	mihtiġum	ADJ;DAT;MASC;PL;LGSPEC1
cuþlæcan	cūþlǣhtest	V;IND;SG;2;PST
hlud	hlūdum	ADJ;DAT;FEM;PL;LGSPEC1
andweardian	andweardiende	V.PTCP;PRS
gifol	ġifole	ADJ;ACC;MASC;PL;LGSPEC2
sarig	sārġum	ADJ;DAT;NEUT;SG;LGSPEC2
clæg	clǣġes	N;GEN;SG
bæcestre	bæcestran	N;DAT;SG
oferflitan	oferflāt	V;IND;SG;1;PST
hyreborg	hȳreborg	N;NOM;SG
sigan	sigon	V;IND;PL;PST
unwæstmbære	unwæstmbǣre	ADJ;INS;MASC;SG;LGSPEC2
standan	standaþ	V;IND;PL;PRS
orlæg	orlæg	N;NOM;SG
lang	lange	ADJ;NOM;NEUT;SG;LGSPEC1
wange	wangum	N;DAT;PL
ealdorleas	ealdorlēase	ADJ;NOM;NEUT;SG;LGSPEC1
tellan	teleþ	V;IND;SG;3;PRS
gifstol	ġifstōlum	N;DAT;PL
blinnan	blinnen	V;SBJV;PL;PRS
geæhtle	ġeæhtlan	N;ACC;SG
drincan	ġedruncen	V.PTCP;PST
feortan	feart	V;IND;SG;3;PST
clænsian	clǣnsast	V;IND;SG;2;PRS
tudor	tudru	N;NOM;PL
beorcan	beorce	V;IND;SG;1;PRS
gebyrde	ġebyrdum	ADJ;DAT;MASC;SG;LGSPEC2
geweorþan	ġeweorþe	V;IND;SG;1;PRS
creopan	cropen	V.PTCP;PST
blæhæwen	blǣhǣwenra	ADJ;GEN;NEUT;PL;LGSPEC2
deman	dēman	V;NFIN
grammatic	grammatiċe	ADJ;ACC;NEUT;SG;LGSPEC1
great	grēatum	ADJ;INS;NEUT;PL;LGSPEC1
gamol	gamolan	ADJ;GEN;MASC;SG;LGSPEC1
bregdan	briġdeþ	V;IND;SG;3;PRS
eþian	ēþode	V;IND;SG;1;PST
orþanc	orþances	N;GEN;SG
bæcestre	bæcestran	N;ACC;SG
ænlic	ǣnlīċan	ADJ;GEN;NEUT;SG;LGSPEC1
grammatic	grammatiċum	ADJ;DAT;MASC;SG;LGSPEC2
forcippian	forċippiġaþ	V;IMP;PL
soþlic	sōþlīċe	ADJ;ACC;FEM;SG;LGSPEC2
hnot	hnotan	ADJ;ACC;NEUT;SG;LGSPEC1
wyrcan	wyrċe	V;SBJV;SG;PRS
wancol	wanclan	ADJ;NOM;NEUT;PL;LGSPEC1
andweard	andwearde	ADJ;ACC;FEM;SG;LGSPEC2
healfdead	healfdēadan	ADJ;GEN;FEM;SG;LGSPEC1
leassagol	lēassagoles	ADJ;GEN;MASC;SG;LGSPEC2
acennedlic	ācennedlīċe	ADJ;NOM;FEM;PL;LGSPEC2
gesund	ġesundum	ADJ;DAT;FEM;PL;LGSPEC1
beogol	bēogole	ADJ;ACC;NEUT;SG;LGSPEC1
fadian	fadoden	V;SBJV;PL;PST
dreorig	drēoriġa	ADJ;NOM;FEM;PL;LGSPEC2
gecwician	gecwicie	V;SBJV;SG;PRS
feohtan	fohten	V.PTCP;PST
stæflic	stæflīċre	ADJ;INS;FEM;SG;LGSPEC2
searu	searwa	N;GEN;PL
duguþ	duguþum	N;DAT;PL
gerad	ġerādum	ADJ;INS;FEM;PL;LGSPEC2
sculan	scolde	V;IND;SG;3;PST
deogol	dēogolum	ADJ;DAT;FEM;PL;LGSPEC1
dælan	dǣlden	V;SBJV;PL;PST
ametendlic	āmetendlīċum	ADJ;DAT;MASC;SG;LGSPEC2
hælan	hǣldest	V;IND;SG;2;PST
suþerne	sūþerne	ADJ;ACC;FEM;SG;LGSPEC1
blondenfeax	blondenfeaxum	ADJ;DAT;FEM;PL;LGSPEC1
scieran	scēare	V;IND;SG;2;PST
flugol	flugole	ADJ;ACC;FEM;SG;LGSPEC2
bealohydig	bealohȳdiġan	ADJ;GEN;MASC;SG;LGSPEC1
fordon	fordō	V;IMP;SG
inlihtan	inlīhtest	V;IND;SG;2;PRS
gemyndig	ġemyndiġu	ADJ;NOM;NEUT;PL;LGSPEC2
twiccian	twiccoden	V;SBJV;PL;PST
eaden	ēadnena	ADJ;GEN;MASC;PL;LGSPEC1
eaden	ēadenum	ADJ;DAT;MASC;PL;LGSPEC2
sieltan	sielten	V;SBJV;PL;PRS
ametendlic	āmetendlīċra	ADJ;GEN;NEUT;PL;LGSPEC1
glæd	gladan	ADJ;ACC;NEUT;PL;LGSPEC1
wifer	wifer	N;NOM;SG
hnah	hnāgan	ADJ;ACC;MASC;SG;LGSPEC1
ametendlic	āmetendlīċum	ADJ;DAT;NEUT;PL;LGSPEC1
æwan	ǣwde	V;IND;SG;1;PST
wacian	wacie	V;IND;SG;1;PRS
wiþceosan	wiþcoren	V.PTCP;PST
neþan	ġenēþed	V.PTCP;PST
mægencræft	mæġencræftas	N;ACC;PL
tiwesdæg	tiwesdaga	N;GEN;PL
siwian	siwode	V;IND;SG;1;PST
gram	grame	ADJ;NOM;MASC;PL;LGSPEC2
hlafordlic	hlāfordlīċan	ADJ;INS;NEUT;SG;LGSPEC1
mereswin	mereswīn	N;NOM;PL
begietan	beġieten	V.PTCP;PST
strang	strangan	ADJ;NOM;PL;LGSPEC1
steppan	ġestapen	V.PTCP;PST
smugan	smēag	V;IND;SG;1;PST
wæcnan	ġewæcen	V.PTCP;PST
feasceaft	fēasceaftum	ADJ;INS;MASC;PL;LGSPEC2
eahtian	eahtode	V;IND;SG;1;PST
lesan	list	V;IND;SG;2;PRS
fætt	fǣtt	ADJ;ACC;NEUT;SG;LGSPEC2
æþelboren	æþelborene	ADJ;NOM;FEM;SG;LGSPEC1
easterne	ēasternra	ADJ;GEN;PL;LGSPEC1
gedefe	ġedēfu	ADJ;ACC;FEM;PL;LGSPEC2
fæst	fæstan	ADJ;ACC;FEM;PL;LGSPEC1
andgietol	andġietolum	ADJ;INS;NEUT;PL;LGSPEC2
rihtwis	rihtwīsum	ADJ;DAT;NEUT;PL;LGSPEC1
geþyldig	ġeþyldiġre	ADJ;GEN;NEUT;SG;LGSPEC2
ceorlboren	ċeorlborenra	ADJ;GEN;FEM;PL;LGSPEC2
bicnol	bīċnolra	ADJ;GEN;NEUT;PL;LGSPEC1
beardleas	beardlēase	ADJ;NOM;FEM;PL;LGSPEC2
andweard	andweard	ADJ;NOM;MASC;SG;LGSPEC2
wæstmbære	wæstmbǣrum	ADJ;INS;FEM;PL;LGSPEC2
clipol	clipolra	ADJ;GEN;MASC;PL;LGSPEC1
bealohydig	bealohȳdġum	ADJ;DAT;MASC;SG;LGSPEC2
grima	grīma	N;NOM;SG
eacan	ēoce	V;IND;SG;2;PST
leof	lēofum	ADJ;DAT;FEM;PL;LGSPEC2
bealohydig	bealohȳdġe	ADJ;ACC;NEUT;SG;LGSPEC1
cræftig	cræftiġum	ADJ;DAT;NEUT;PL;LGSPEC1
wrætlic	wrǣtlīċe	ADJ;ACC;MASC;PL;LGSPEC2
fundian	fundiġaþ	V;IND;PL;PRS
yce	ȳċan	N;ACC;PL
drincan	druncen	V;SBJV;PL;PST
æfen	ǣfen	N;GEN;SG
bealohydig	bealohȳdġum	ADJ;DAT;NEUT;SG;LGSPEC2
bebugan	bebȳgest	V;IND;SG;2;PRS
hlafordleas	hlāfordlēasena	ADJ;GEN;NEUT;PL;LGSPEC1
modiglic	mōdiġlīċena	ADJ;GEN;MASC;PL;LGSPEC1
beald	bealdum	ADJ;DAT;NEUT;SG;LGSPEC2
æfen	ǣfennes	N;DAT;SG
gat	gēt	N;NOM;PL
hlafordlic	hlāfordlīċra	ADJ;GEN;NEUT;PL;LGSPEC1
lignan	līġne	V;IND;SG;1;PRS
great	grēatum	ADJ;DAT;MASC;PL;LGSPEC2
styrian	styriġe	V;IND;SG;1;PRS
scufan	scofen	V.PTCP;PST
purs	pursa	N;GEN;PL
hremig	hrēmiġum	ADJ;DAT;FEM;SG;LGSPEC2
sorgian	sorgie	V;SBJV;SG;PRS
mund	mundum	N;DAT;PL
dafenian	dafeniġe	V;SBJV;SG;PRS
angsum	angsumre	ADJ;INS;FEM;SG;LGSPEC2
sarig	sārġu	ADJ;NOM;NEUT;PL;LGSPEC2
calu	calwe	ADJ;ACC;FEM;SG;LGSPEC1
gast	gāst	N;NOM;SG
midd	middan	ADJ;ACC;MASC;SG;LGSPEC1
drencan	drencte	V;IND;SG;3;PST
bugan	būg	V;IMP;SG
efenmetan	efenmet	V;IND;SG;3;PRS
alan	alaþ	V;IMP;PL
mannbære	mannbǣrre	ADJ;INS;FEM;SG;LGSPEC2
bearneacen	bearnēacenena	ADJ;GEN;MASC;PL;LGSPEC1
weddian	weddiaþ	V;IND;PL;PRS
blodreow	blōdrēowan	ADJ;GEN;MASC;SG;LGSPEC1
stæflic	stæflīċne	ADJ;ACC;MASC;SG;LGSPEC2
hefig	hefiġ	ADJ;NOM;MASC;SG;LGSPEC2
abeodan	ābēad	V;IND;SG;1;PST
cost	costum	ADJ;DAT;NEUT;PL;LGSPEC1
gemimor	ġemimorra	ADJ;GEN;NEUT;PL;LGSPEC1
gemimor	ġemimorum	ADJ;DAT;FEM;PL;LGSPEC2
astyrian	āstyrede	V;SBJV;SG;PST
ceorl	ċeorl	N;NOM;SG
sigan	sāh	V;IND;SG;1;PST
glæd	glada	ADJ;NOM;MASC;SG;LGSPEC1
tredan	tredaþ	V;IND;PL;PRS
gemyndig	ġemyndiġre	ADJ;ACC;FEM;PL;LGSPEC2
soþlic	sōþlīċan	ADJ;ACC;NEUT;PL;LGSPEC1
ætren	ǣtrenu	ADJ;NOM;FEM;SG;LGSPEC2
ieldu	ielde	N;NOM;PL
gram	graman	ADJ;GEN;NEUT;SG;LGSPEC1
læccan	ġelæht	V.PTCP;PST
gewiss	ġewiss	N;ACC;PL
lah	lāgum	ADJ;DAT;MASC;SG;LGSPEC2
heah	hēagu	ADJ;NOM;FEM;SG;LGSPEC2
lah	lāgan	ADJ;ACC;PL;LGSPEC1
gan	gǣst	V;IND;SG;2;PRS
hræn	hræne	N;NOM;PL
onirnan	onirne	V;IND;SG;1;PRS
mearc	mearce	N;NOM;PL
edcwic	edcwican	ADJ;ACC;FEM;SG;LGSPEC1
wrætlic	wrǣtlīċe	ADJ;NOM;NEUT;PL;LGSPEC2
gemyndig	ġemyndiġe	ADJ;ACC;NEUT;SG;LGSPEC1
ierfa	ierfan	N;ACC;SG
gewær	ġewære	ADJ;ACC;MASC;PL;LGSPEC2
þufbære	þūfbǣrre	ADJ;DAT;FEM;SG;LGSPEC2
cræftig	cræftiġum	ADJ;DAT;MASC;SG;LGSPEC2
dafen	dafenra	ADJ;GEN;FEM;PL;LGSPEC2
stæflic	stæflīċu	ADJ;ACC;NEUT;PL;LGSPEC2
calu	calwa	ADJ;ACC;NEUT;PL;LGSPEC2
cost	costra	ADJ;GEN;FEM;PL;LGSPEC2
solian	solodon	V;IND;PL;PST
minlic	minlīċena	ADJ;GEN;NEUT;PL;LGSPEC1
loccian	locciġaþ	V;IND;PL;PRS
sceotan	scēot	V;IMP;SG
ærendfæst	ǣrendfæstum	ADJ;INS;MASC;PL;LGSPEC2
gælan	gæled	V.PTCP;PST
fleon	flugon	V;IND;PL;PST
restan	restaþ	V;IMP;PL
behealdan	behēold	V;IND;SG;3;PST
cræftig	cræftġum	ADJ;INS;NEUT;PL;LGSPEC2
weorþian	weorþast	V;IND;SG;2;PRS
werig	wēriġum	ADJ;INS;FEM;PL;LGSPEC2
sprecol	sprecoles	ADJ;GEN;MASC;SG;LGSPEC2
smeortan	smeortende	V.PTCP;PRS
hremig	hrēmiġan	ADJ;DAT;SG;LGSPEC1
endian	endiġende	V.PTCP;PRS
cweþan	cweþe	V;SBJV;SG;PRS
cwellan	cwellaþ	V;IND;PL;PRS
eaden	ēadnes	ADJ;GEN;MASC;SG;LGSPEC2
fordeman	fordēmed	V.PTCP;PST
ferhþ	ferhþ	N;ACC;PL
tawian	tawode	V;SBJV;SG;PST
dreorig	drēorġa	ADJ;NOM;FEM;PL;LGSPEC2
andgietol	andġietolan	ADJ;GEN;NEUT;SG;LGSPEC1
frod	frōde	ADJ;NOM;FEM;SG;LGSPEC1
manian	maniġaþ	V;IND;PL;PRS
solian	solian	V;NFIN
lesan	lesaþ	V;IND;PL;PRS
baþian	baþodest	V;IND;SG;2;PST
æwita	ǣwitum	N;DAT;PL
bealohydig	bealohȳdiġan	ADJ;DAT;FEM;SG;LGSPEC1
fiffealde	fīffealdan	N;ACC;SG
eaden	ēadnena	ADJ;GEN;FEM;PL;LGSPEC1
ceald	ċealdum	ADJ;DAT;FEM;SG;LGSPEC2
hlud	hlūdum	ADJ;INS;NEUT;PL;LGSPEC2
drepan	dræp	V;IND;SG;1;PST
æcced	æċċedes	N;GEN;SG
onettan	ōnettan	V;NFIN
stigan	stīgeþ	V;IND;SG;3;PRS
lytel	lȳteles	ADJ;GEN;FEM;SG;LGSPEC2
cræftig	cræftiġan	ADJ;ACC;MASC;PL;LGSPEC1
dafenian	dafeniġaþ	V;IMP;PL
fleon	flēo	V;SBJV;SG;PRS
gemyndig	ġemyndġum	ADJ;DAT;NEUT;SG;LGSPEC2
blawan	blēowe	V;IND;SG;2;PST
nacian	naciende	V.PTCP;PRS
sƿefan	sƿefe	V;SBJV;SG;PRS
Crist	Crist	N;NOM;SG
andwist	andwistum	N;DAT;PL
gebyrde	ġebyrdre	ADJ;GEN;FEM;SG;LGSPEC2
gestrienendlic	ġestrīenendlīċum	ADJ;DAT;MASC;SG;LGSPEC2
cneordlæcan	cneordlǣhton	V;IND;PL;PST
oncweþan	oncwǣden	V;SBJV;PL;PST
don	dyden	V;SBJV;PL;PST
entisc	entiscan	ADJ;GEN;MASC;SG;LGSPEC1
asettan	āsette	V;IND;SG;3;PST
dagian	dagode	V;SBJV;SG;PST
æþelboren	æþelborene	ADJ;INS;MASC;SG;LGSPEC2
Seaxisc	Seaxiscne	ADJ;ACC;MASC;SG;LGSPEC2
minlic	minlīċum	ADJ;INS;MASC;PL;LGSPEC1
pæþ	pæþ	N;NOM;SG
medwis	medwīsre	ADJ;INS;FEM;SG;LGSPEC2
purs	pursas	N;NOM;PL
unwæstmbære	unwæstmbǣrena	ADJ;GEN;MASC;PL;LGSPEC1
bleoread	blēorēada	ADJ;NOM;MASC;SG;LGSPEC1
higian	hīgode	V;SBJV;SG;PST
clipian	clipast	V;IND;SG;2;PRS
healfdead	healfdēadan	ADJ;ACC;FEM;PL;LGSPEC1
werig	wēriġre	ADJ;GEN;FEM;SG;LGSPEC2
cystig	cystiġum	ADJ;INS;MASC;PL;LGSPEC2
cræftig	cræftiġum	ADJ;INS;NEUT;PL;LGSPEC2
stryndan	strȳndeþ	V;IND;SG;3;PRS
wadan	wōde	V;SBJV;SG;PST
lixan	līxaþ	V;IND;PL;PRS
hawian	hāwiaþ	V;IND;PL;PRS
rida	rida	N;NOM;SG
bugan	būgaþ	V;IND;PL;PRS
efenbyrde	evenbyrde	ADJ;NOM;NEUT;SG;LGSPEC1
sealtian	sealtoden	V;SBJV;PL;PST
cræftig	cræftġena	ADJ;GEN;MASC;PL;LGSPEC1
beorma	beormum	N;DAT;PL
weorþian	weorþiġen	V;SBJV;PL;PRS
niman	nimest	V;IND;SG;2;PRS
efenbyrde	evenbyrdum	ADJ;DAT;MASC;PL;LGSPEC1
ælan	ǣlde	V;SBJV;SG;PST
wunian	wuniġe	V;SBJV;SG;PRS
gemyndig	ġemyndiġne	ADJ;ACC;MASC;SG;LGSPEC2
cild	ċildru	N;ACC;PL
gestrienendlic	ġestrīenendlīċan	ADJ;ACC;FEM;PL;LGSPEC1
behreosan	behrīeseþ	V;IND;SG;3;PRS
cwic	cwicena	ADJ;GEN;PL;LGSPEC1
fundian	fundast	V;IND;SG;2;PRS
sceada	sceadan	N;ACC;SG
forþgeriman	forþġerīman	V;NFIN
fylan	fȳlende	V.PTCP;PRS
bilehwit	bilehwīt	ADJ;ACC;NEUT;SG;LGSPEC2
afulic	afulīċan	ADJ;NOM;MASC;PL;LGSPEC1
fætt	fǣttan	ADJ;DAT;FEM;SG;LGSPEC1
sorgian	sorgiġe	V;IND;SG;1;PRS
asettan	āsettaþ	V;IMP;PL
hæþen	hǣþne	ADJ;ACC;NEUT;SG;LGSPEC2
gælan	gæleden	V;SBJV;PL;PST
leof	lēof	ADJ;NOM;FEM;SG;LGSPEC2
wancol	wancolum	ADJ;DAT;NEUT;SG;LGSPEC2
bleoread	blēorēadum	ADJ;DAT;NEUT;SG;LGSPEC2
bensian	bēnsode	V;SBJV;SG;PST
potian	tō potianne	V;NFIN
turnian	turniġe	V;IND;SG;1;PRS
da	dāna	N;GEN;PL
Seaxisc	Seaxiscre	ADJ;GEN;FEM;SG;LGSPEC2
swimman	swimmeþ	V;IND;SG;3;PRS
dreogan	drogen	V.PTCP;PST
mynelic	mynelīċra	ADJ;GEN;NEUT;PL;LGSPEC2
clænsian	clǣnsode	V;IND;SG;3;PST
hris	hrīs	N;ACC;SG
arfæst	ārfæstan	ADJ;DAT;MASC;SG;LGSPEC1
cweþan	cwæþ	V;IND;SG;1;PST
endian	endode	V;SBJV;SG;PST
swæslæcan	swǣslǣċan	V;NFIN
hangian	hangiaþ	V;IND;PL;PRS
copp	coppas	N;NOM;PL
onbidan	onbīdeþ	V;IND;SG;3;PRS
wascan	wōsc	V;IND;SG;1;PST
glæd	gladan	ADJ;ACC;FEM;SG;LGSPEC1
beorht	beorhta	ADJ;ACC;NEUT;PL;LGSPEC2
beladian	belādodest	V;IND;SG;2;PST
sorh	sorga	N;GEN;PL
tonama	tōnaman	N;DAT;SG
ilfete	ilfetan	N;ACC;SG
grambære	grambǣrum	ADJ;DAT;NEUT;PL;LGSPEC2
gripan	gripe	V;IND;SG;2;PST
ieldu	ielde	N;GEN;SG
frinan	frān	V;IND;SG;1;PST
ætren	ǣtrenum	ADJ;INS;MASC;PL;LGSPEC2
acumendlic	ācumendlīċu	ADJ;NOM;FEM;SG;LGSPEC2
egle	eġlan	ADJ;ACC;MASC;SG;LGSPEC1
gelogian	ġelōgaþ	V;IND;SG;3;PRS
biddan	bǣde	V;SBJV;SG;PST
sculan	sculon	V;IND;PL;PRS
wracu	wrace	N;GEN;SG
drepan	dripst	V;IND;SG;2;PRS
blæhæwen	blǣhǣwnan	ADJ;NOM;FEM;PL;LGSPEC1
gram	gramum	ADJ;DAT;MASC;PL;LGSPEC2
gemyndig	ġemyndġum	ADJ;DAT;MASC;SG;LGSPEC2
fuht	fūhtes	ADJ;GEN;MASC;SG;LGSPEC2
fiell	fielles	N;GEN;SG
eacen	ēacnan	ADJ;INS;FEM;SG;LGSPEC1
leof	lēofra	ADJ;GEN;MASC;PL;LGSPEC2
þufbære	þūfbǣrre	ADJ;INS;FEM;SG;LGSPEC2
rarian	rārode	V;IND;SG;3;PST
nift	niftum	N;DAT;PL
gemimor	ġemimoran	ADJ;ACC;FEM;SG;LGSPEC1
wæstmbære	wæstmbǣrum	ADJ;DAT;MASC;PL;LGSPEC2
flugol	flugolan	ADJ;INS;FEM;SG;LGSPEC1
east	ēastan	ADJ;ACC;MASC;PL;LGSPEC1
clænsian	clǣnsiaþ	V;IND;PL;PRS
gesund	ġesundum	ADJ;INS;FEM;PL;LGSPEC2
læccan	tō læċċanne	V;NFIN
lafian	lafiġaþ	V;IND;PL;PRS
befindan	befindaþ	V;IMP;PL
spræc	sprǣċe	N;NOM;PL
ceorlboren	ċeorlborenan	ADJ;ACC;FEM;PL;LGSPEC1
wrætt	wrǣttes	N;GEN;SG
onfon	ġeonfongen	V.PTCP;PST
ungelic	unġelīċe	ADJ;ACC;FEM;SG;LGSPEC2
hremig	hrēmiġes	ADJ;GEN;FEM;SG;LGSPEC2
ricsian	rīcsiaþ	V;IND;PL;PRS
borian	boriġaþ	V;IMP;PL
sincan	sunce	V;IND;SG;2;PST
ungelic	unġelīċan	ADJ;DAT;NEUT;SG;LGSPEC1
batian	batodon	V;IND;PL;PST
cild	ċild	N;NOM;SG
geliefan	ġelīefde	V;IND;SG;3;PST
deore	dēorra	ADJ;GEN;PL;LGSPEC2
blodreow	blōdrēowum	ADJ;DAT;NEUT;SG;LGSPEC2
cennan	cenne	V;IND;SG;1;PRS
cealdian	cealdiġaþ	V;IMP;PL
began	beēode	V;SBJV;SG;PST
heore	hēore	ADJ;ACC;NEUT;SG;LGSPEC2
stingan	stingaþ	V;IND;PL;PRS
midd	middan	ADJ;ACC;PL;LGSPEC1
blæhæwen	blǣhǣwenre	ADJ;ACC;FEM;PL;LGSPEC2
gewiss	ġewissum	ADJ;DAT;MASC;PL;LGSPEC1
eadig	ēadiġum	ADJ;INS;MASC;PL;LGSPEC2
wifian	tō wīfianne	V;NFIN
weorþan	wierþest	V;IND;SG;2;PRS
swerian	swōron	V;IND;PL;PST
fandian	fandoden	V;SBJV;PL;PST
liþan	liden	V;SBJV;PL;PST
eahtian	eahtast	V;IND;SG;2;PRS
has	hāsre	ADJ;DAT;FEM;SG;LGSPEC2
medwis	medwīse	ADJ;INS;NEUT;SG;LGSPEC2
blatian	blāta	V;IMP;SG
Seaxisc	Seaxiscan	ADJ;ACC;MASC;PL;LGSPEC1
mece	mēċas	N;ACC;PL
clyccan	clyċċan	V;NFIN
fordon	tō fordōnne	V;NFIN
hefig	hefiġan	ADJ;NOM;NEUT;PL;LGSPEC1
deogol	dēogolu	ADJ;NOM;NEUT;PL;LGSPEC2
entisc	entiscum	ADJ;INS;FEM;PL;LGSPEC2
eadig	ēadiġra	ADJ;GEN;FEM;PL;LGSPEC1
gemimor	ġemimore	ADJ;ACC;FEM;SG;LGSPEC2
soþlic	sōþlīċa	ADJ;NOM;MASC;SG;LGSPEC1
edcwic	edcwicum	ADJ;DAT;FEM;PL;LGSPEC2
sægrund	sǣgrundas	N;ACC;PL
great	grēatum	ADJ;INS;NEUT;PL;LGSPEC2
grambære	grambǣran	ADJ;DAT;NEUT;SG;LGSPEC1
gemyndig	ġemyndiġan	ADJ;GEN;FEM;SG;LGSPEC1
æfnian	ǣfna	V;IMP;SG
þafung	þafung	N;NOM;SG
baþian	baþian	V;NFIN
deore	dēoran	ADJ;ACC;NEUT;SG;LGSPEC1
leof	lēofan	ADJ;DAT;NEUT;SG;LGSPEC1
bretwalda	bretwaldan	N;ACC;PL
frinan	frīne	V;SBJV;SG;PRS
stæflic	stæflīċan	ADJ;ACC;FEM;PL;LGSPEC1
tonama	tōnaman	N;ACC;PL
bilehwit	bilehwītum	ADJ;INS;NEUT;PL;LGSPEC2
gaderian	gaderiġe	V;SBJV;SG;PRS
þeahtian	þeahtiġe	V;IND;SG;1;PRS
dafen	dafene	ADJ;ACC;FEM;PL;LGSPEC2
cennan	cende	V;IND;SG;3;PST
eare	ēarum	N;DAT;PL
niwe	nīwra	ADJ;GEN;NEUT;PL;LGSPEC2
stalu	stala	N;GEN;PL
suþerne	sūþernu	ADJ;NOM;FEM;SG;LGSPEC2
georn	ġeorne	ADJ;NOM;FEM;SG;LGSPEC1
blæhæwen	blǣhǣwenan	ADJ;ACC;FEM;PL;LGSPEC1
lang	langes	ADJ;GEN;MASC;SG;LGSPEC2
æwita	ǣwitena	N;GEN;PL
bicnol	bīċnolum	ADJ;DAT;MASC;PL;LGSPEC2
fadian	fadiġende	V.PTCP;PRS
borian	bora	V;IMP;SG
cepan	cēpaþ	V;IND;PL;PRS
amarian	āmarast	V;IND;SG;2;PRS
blatian	blātiġe	V;IND;SG;1;PRS
murnan	ġemurned	V.PTCP;PST
settan	sette	V;SBJV;SG;PRS
bledsian	blēdsiġaþ	V;IMP;PL
swimman	swumme	V;SBJV;SG;PST
læcan	tō lǣċanne	V;NFIN
aswebban	āswebbe	V;SBJV;SG;PRS
hefig	hefiġa	ADJ;NOM;MASC;SG;LGSPEC1
spilian	spilie	V;IND;SG;1;PRS
blostm	blōstma	N;GEN;PL
cennan	cene	V;IMP;SG
bleoread	blēorēadena	ADJ;GEN;NEUT;PL;LGSPEC1
sƿiþ	sƿīþes	ADJ;GEN;FEM;SG;LGSPEC2
geunnan	ġeūþon	V;IND;PL;PST
niwe	nīwe	ADJ;ACC;NEUT;SG;LGSPEC2
stille	stillena	ADJ;GEN;FEM;PL;LGSPEC1
leassagol	lēassagolan	ADJ;NOM;FEM;PL;LGSPEC1
sendan	send	V;IMP;SG
mihtig	mihtġan	ADJ;GEN;MASC;SG;LGSPEC1
laþu	laþe	N;DAT;SG
fadian	fadode	V;IND;SG;1;PST
hebban	hefþ	V;IND;SG;3;PRS
higian	hīgiende	V.PTCP;PRS
æppelbære	æppelbǣran	ADJ;ACC;MASC;SG;LGSPEC1
aswebban	āswebban	V;NFIN
angsum	angsuman	ADJ;ACC;MASC;SG;LGSPEC1
seoþan	sude	V;SBJV;SG;PST
wenn	wenne	N;DAT;SG
nearo	nearo	ADJ;NOM;MASC;SG;LGSPEC2
guþmod	gūþmōdne	ADJ;ACC;MASC;SG;LGSPEC2
stille	stillan	ADJ;ACC;MASC;SG;LGSPEC1
stæflic	stæflīċu	ADJ;NOM;FEM;SG;LGSPEC2
gerad	ġerādes	N;GEN;SG
dufan	dufen	V;SBJV;PL;PST
cierran	ċierde	V;SBJV;SG;PST
ficol	ficole	ADJ;ACC;MASC;PL;LGSPEC2
cost	coste	ADJ;ACC;FEM;PL;LGSPEC2
niwe	nīwra	ADJ;GEN;MASC;PL;LGSPEC2
hwilwende	hwīlwendra	ADJ;GEN;PL;LGSPEC2
eaden	ēadnan	ADJ;GEN;FEM;SG;LGSPEC1
þyncan	þynċeþ	V;IND;SG;3;PRS
dufan	dūfe	V;SBJV;SG;PRS
forleosan	forlēosaþ	V;IND;PL;PRS
weorþan	wurde	V;SBJV;SG;PST
angsum	angsuman	ADJ;DAT;FEM;SG;LGSPEC1
hremig	hrēmiġne	ADJ;ACC;MASC;SG;LGSPEC2
gaderian	gaderie	V;SBJV;SG;PRS
atol	atola	ADJ;NOM;FEM;PL;LGSPEC2
gaderian	tō gaderianne	V;NFIN
weddian	weddiġaþ	V;IMP;PL
fadian	fadiġaþ	V;IMP;PL
cræftig	cræftġan	ADJ;INS;FEM;SG;LGSPEC1
adreogan	ādrīegeþ	V;IND;SG;3;PRS
beald	bealdan	ADJ;GEN;MASC;SG;LGSPEC1
ætren	ǣtrenena	ADJ;GEN;MASC;PL;LGSPEC1
earfoþdæde	earfoþdǣdum	ADJ;DAT;FEM;PL;LGSPEC1
mannbære	mannbǣran	ADJ;NOM;MASC;PL;LGSPEC1
guþsele	gūþsela	N;GEN;PL
strang	strangan	ADJ;GEN;SG;LGSPEC1
gemyndig	ġemyndġan	ADJ;ACC;FEM;SG;LGSPEC1
earsþerl	earsþerle	N;DAT;SG
andweardian	andwearda	V;IMP;SG
horn	hornas	N;ACC;PL
beald	beald	ADJ;NOM;NEUT;SG;LGSPEC2
earnian	earniende	V.PTCP;PRS
ceald	ċealdan	ADJ;ACC;NEUT;SG;LGSPEC1
modstaþolnes	mōdstaþolnesse	N;NOM;PL
gemyndig	ġemyndiġum	ADJ;DAT;MASC;SG;LGSPEC2
hatian	hataþ	V;IND;SG;3;PRS
behweorfan	behweorfan	V;NFIN
bensian	bēnsiġen	V;SBJV;PL;PRS
hildebord	hildebord	N;NOM;SG
stoppian	stoppoden	V;SBJV;PL;PST
cost	cost	N;ACC;SG
sendan	ġesended	V.PTCP;PST
blawan	blāwaþ	V;IMP;PL
forþteon	forþtugen	V;SBJV;PL;PST
þiccet	þiccet	N;ACC;SG
leod	lēoda	N;GEN;PL
mearcian	mearcie	V;SBJV;SG;PRS
miscian	misciende	V.PTCP;PRS
bold	bolda	N;GEN;PL
healfdead	healfdēada	ADJ;NOM;FEM;PL;LGSPEC2
rice	rīċe	N;NOM;SG
atol	atolra	ADJ;GEN;NEUT;PL;LGSPEC2
duguþ	duguþa	N;NOM;PL
gemætan	ġemǣtten	V;SBJV;PL;PST
Seaxisc	Seaxiscan	ADJ;ACC;MASC;SG;LGSPEC1
acweorna	ācweornan	N;GEN;SG
glæd	glade	ADJ;ACC;FEM;PL;LGSPEC2
hlafordleas	hlāfordlēasre	ADJ;GEN;FEM;SG;LGSPEC2
lesan	lǣren	V;SBJV;PL;PST
dol	dole	ADJ;INS;NEUT;SG;LGSPEC2
lufsum	lufsum	ADJ;ACC;NEUT;SG;LGSPEC2
blæhæwen	blǣhǣwene	ADJ;INS;MASC;SG;LGSPEC2
gemyndig	ġemyndiġena	ADJ;GEN;NEUT;PL;LGSPEC1
onwæcnan	onwæcnan	V;NFIN
ilfete	ilfete	N;NOM;SG
trymman	trymede	V;IND;SG;3;PST
guþmod	gūþmōdan	ADJ;ACC;NEUT;PL;LGSPEC1
gebedda	ġebeddan	N;DAT;SG
leaslic	lēaslīċum	ADJ;INS;MASC;PL;LGSPEC2
swerian	swerian	V;NFIN
niwe	nīwena	ADJ;GEN;FEM;PL;LGSPEC1
toslitan	tōslite	V;SBJV;SG;PST
hangian	hangie	V;IND;SG;1;PRS
æppelbære	æppelbǣra	ADJ;NOM;MASC;SG;LGSPEC1
gefan	ġefe	V;SBJV;SG;PRS
dagian	dagast	V;IND;SG;2;PRS
mealwe	mealwan	N;ACC;SG
onlihtan	onlīhtaþ	V;IMP;PL
gieldan	gulde	V;SBJV;SG;PST
bena	bēnum	N;DAT;PL
ætren	ǣtrenra	ADJ;GEN;MASC;PL;LGSPEC1
sendan	senden	V;SBJV;PL;PRS
lareow	lārēowes	N;GEN;SG
geþyldig	ġeþyldiġum	ADJ;DAT;FEM;SG;LGSPEC2
mæscre	mæscran	N;DAT;SG
andwis	andwīse	ADJ;INS;NEUT;SG;LGSPEC2
fealdan	fealdaþ	V;IND;PL;PRS
siwian	siwoden	V;SBJV;PL;PST
gebyrde	ġebyrdan	ADJ;INS;FEM;SG;LGSPEC1
loþa	loþena	N;GEN;PL
gieldan	ġeald	V;IND;SG;1;PST
begeotan	beġīetst	V;IND;SG;2;PRS
hawian	hāwian	V;NFIN
orþanc	orþancas	N;NOM;PL
gewær	ġewæran	ADJ;ACC;FEM;SG;LGSPEC1
agifan	āġifaþ	V;IND;PL;PRS
bær	baran	ADJ;GEN;NEUT;SG;LGSPEC1
onsittan	onsittaþ	V;IMP;PL
hopian	hopode	V;IND;SG;3;PST
bestyman	bestȳme	V;IND;SG;1;PRS
sprecol	sprecolum	ADJ;DAT;MASC;PL;LGSPEC1
leaslic	lēaslīċum	ADJ;DAT;NEUT;PL;LGSPEC1
gewiss	ġewisse	ADJ;NOM;FEM;SG;LGSPEC1
fætt	fǣttra	ADJ;GEN;NEUT;PL;LGSPEC2
edstaþelian	edstaþelod	V.PTCP;PST
swealwe	swealwena	N;GEN;PL
grund	grunda	N;GEN;PL
trahtian	trahtiġaþ	V;IND;PL;PRS
lytel	lȳtel	ADJ;NOM;NEUT;SG;LGSPEC2
faran	fare	V;IND;SG;1;PRS
hwilwende	hwīlwendes	ADJ;GEN;FEM;SG;LGSPEC2
cræftig	cræftġum	ADJ;DAT;NEUT;PL;LGSPEC2
sien	sīen	N;ACC;SG
onfindan	onfunden	V.PTCP;PST
bleaþ	blēaþra	ADJ;GEN;FEM;PL;LGSPEC1
grim	grimman	ADJ;DAT;MASC;SG;LGSPEC1
gerad	ġerāde	ADJ;NOM;FEM;SG;LGSPEC1
fleotan	flīetest	V;IND;SG;2;PRS
wice	wicena	N;GEN;PL
cealdian	cealdiġaþ	V;IND;PL;PRS
healfdead	healfdēadan	ADJ;GEN;MASC;SG;LGSPEC1
entisc	entisce	ADJ;NOM;NEUT;SG;LGSPEC1
strican	strīcaþ	V;IND;PL;PRS
dwinan	dwīnen	V;SBJV;PL;PRS
acumendlic	ācumendlīċum	ADJ;DAT;MASC;SG;LGSPEC2
befylan	befȳlde	V;SBJV;SG;PST
ficol	ficol	ADJ;ACC;NEUT;SG;LGSPEC2
georn	ġeornum	ADJ;INS;MASC;PL;LGSPEC1
angsum	angsume	ADJ;ACC;NEUT;SG;LGSPEC1
ceorian	ceoriġende	V.PTCP;PRS
steartlian	steartlod	V.PTCP;PST
landbuend	landbūendum	N;DAT;PL
þrote	þrotena	N;GEN;PL
togian	togiaþ	V;IND;PL;PRS
gemimor	ġemimor	ADJ;ACC;NEUT;PL;LGSPEC2
geweorþan	ġeweorþan	V;NFIN
acennedlic	ācennedlīċe	ADJ;NOM;FEM;SG;LGSPEC1
þolian	þolodon	V;IND;PL;PST
leof	lēofan	ADJ;GEN;FEM;SG;LGSPEC1
dreorig	drēorġan	ADJ;INS;MASC;SG;LGSPEC1
eadig	ēadġum	ADJ;INS;MASC;PL;LGSPEC1
halbære	hālbǣran	ADJ;NOM;FEM;PL;LGSPEC1
modiglic	mōdiġlīċ	ADJ;ACC;NEUT;SG;LGSPEC2
gewiss	ġewissan	ADJ;DAT;FEM;SG;LGSPEC1
bleoread	blēorēades	ADJ;GEN;MASC;SG;LGSPEC2
reafian	rēafiaþ	V;IMP;PL
bledsian	blēdsiaþ	V;IMP;PL
hol	hōlum	N;DAT;PL
æppelbære	æppelbǣrum	ADJ;DAT;NEUT;SG;LGSPEC2
wregendlic	wrēġendlīċan	ADJ;GEN;MASC;SG;LGSPEC1
bleaþ	blēaþra	ADJ;GEN;NEUT;PL;LGSPEC1
leof	lēofe	ADJ;NOM;FEM;PL;LGSPEC2
cost	costes	ADJ;GEN;NEUT;SG;LGSPEC2
frod	frōde	ADJ;NOM;MASC;PL;LGSPEC2
unwæstmbære	unwæstmbǣrre	ADJ;GEN;FEM;SG;LGSPEC2
sittan	seten	V.PTCP;PST
rarian	rārast	V;IND;SG;2;PRS
woda	wōdena	N;GEN;PL
werig	wērġan	ADJ;NOM;FEM;PL;LGSPEC1
goldfah	goldfāgan	ADJ;ACC;PL;LGSPEC1
geƿindan	ġeƿinde	V;SBJV;SG;PRS
gefrignan	ġefriġnaþ	V;IMP;PL
mihtlic	mihtlīċan	ADJ;GEN;FEM;SG;LGSPEC1
leaslic	lēaslīċan	ADJ;ACC;MASC;PL;LGSPEC1
bealohydig	bealohȳdiġum	ADJ;DAT;NEUT;PL;LGSPEC2
sculan	sculende	V.PTCP;PRS
fætt	fǣttra	ADJ;GEN;MASC;PL;LGSPEC2
wynsum	wynsuman	ADJ;ACC;FEM;PL;LGSPEC1
eadig	ēadiġena	ADJ;GEN;MASC;PL;LGSPEC1
intinga	intingan	N;DAT;SG
ceallian	cealliġe	V;IND;SG;1;PRS
cild	ċild	N;NOM;PL
bestyman	bestȳmaþ	V;IMP;PL
ielfetu	ielfeta	N;GEN;PL
earfoþdæde	earfoþdǣdan	ADJ;GEN;NEUT;SG;LGSPEC1
wiþceosan	wiþcure	V;SBJV;SG;PST
wixlan	wixlede	V;IND;SG;3;PST
lufsum	lufsumum	ADJ;DAT;MASC;SG;LGSPEC2
geanian	ġeāniġe	V;IND;SG;1;PRS
liþan	līþen	V;SBJV;PL;PRS
scyldwite	scyldwitu	N;ACC;PL
hildebord	hildebord	N;ACC;PL
beginnan	begunne	V;SBJV;SG;PST
bretwalda	bretwaldan	N;NOM;PL
sarig	sāriġena	ADJ;GEN;MASC;PL;LGSPEC1
capian	capodon	V;IND;PL;PST
mihtig	mihtġum	ADJ;INS;MASC;PL;LGSPEC1
blodreow	blōdrēowum	ADJ;DAT;NEUT;PL;LGSPEC2
gestrienendlic	ġestrīenendlīċe	ADJ;ACC;NEUT;PL;LGSPEC2
lang	langum	ADJ;DAT;FEM;SG;LGSPEC2
great	grēatra	ADJ;GEN;NEUT;PL;LGSPEC1
swefn	swefnes	N;GEN;SG
domleas	dōmlēasa	ADJ;ACC;FEM;PL;LGSPEC2
hawian	hāwod	V.PTCP;PST
hringan	hringe	V;IND;SG;1;PRS
bær	baran	ADJ;INS;FEM;SG;LGSPEC1
gripan	grīpende	V.PTCP;PRS
gegaderung	ġegaderunge	N;ACC;SG
gemimor	ġemimorre	ADJ;GEN;FEM;SG;LGSPEC2
bregdan	briġdest	V;IND;SG;2;PRS
werig	wērġan	ADJ;INS;FEM;SG;LGSPEC1
ungelic	unġelīċra	ADJ;GEN;NEUT;PL;LGSPEC1
feasceaft	fēasceafte	ADJ;INS;NEUT;SG;LGSPEC2
firas	fīra	N;GEN;PL
wiþsecgan	wiþsæġd	V.PTCP;PST
feasceaft	fēasceafte	ADJ;ACC;NEUT;SG;LGSPEC1
hopian	hopiġe	V;SBJV;SG;PRS
eacen	ēacenan	ADJ;GEN;MASC;SG;LGSPEC1
bugan	būge	V;IND;SG;1;PRS
ladteow	lādtēowas	N;ACC;PL
wifian	wīfodon	V;IND;PL;PST
grindan	grindende	V.PTCP;PRS
domleas	dōmlēas	ADJ;NOM;FEM;SG;LGSPEC2
receleas	rēċelēasa	ADJ;ACC;FEM;PL;LGSPEC2
gieldan	ġieldende	V.PTCP;PRS
bicnol	bīċnola	ADJ;ACC;FEM;PL;LGSPEC2
wiþsecgan	wiþsǣdon	V;IND;PL;PST
wyrd	wyrde	N;ACC;PL
pleoh	plēoum	N;DAT;PL
geþicfieldan	ġeþicfielden	V;SBJV;PL;PRS
asettan	tō āsettanne	V;NFIN
eaden	ēadnan	ADJ;INS;FEM;SG;LGSPEC1
feasceaft	fēasceaftra	ADJ;GEN;MASC;PL;LGSPEC2
andcwiss	andcwiss	N;NOM;SG
trymman	trymest	V;IND;SG;2;PRS
bihreosan	bihrēosaþ	V;IMP;PL
angsum	angsumum	ADJ;DAT;FEM;PL;LGSPEC2
eaden	ēadenu	ADJ;NOM;FEM;SG;LGSPEC2
hlæder	hlædrum	N;DAT;PL
fuht	fūhtra	ADJ;GEN;NEUT;PL;LGSPEC2
geliefan	ġelīefden	V;SBJV;PL;PST
wrætlic	wrǣtlīċum	ADJ;INS;FEM;PL;LGSPEC2
cealdian	cealdiaþ	V;IMP;PL
bledsian	blēdsiġe	V;IND;SG;1;PRS
frod	frōde	ADJ;NOM;NEUT;SG;LGSPEC1
dafen	dafene	ADJ;NOM;NEUT;SG;LGSPEC1
freme	freme	ADJ;NOM;NEUT;SG;LGSPEC1
eadig	ēadiġan	ADJ;DAT;NEUT;SG;LGSPEC1
æfnian	ǣfnode	V;SBJV;SG;PST
pæþ	paþa	N;GEN;PL
faþu	faþa	N;ACC;PL
ƿindan	ƿindeþ	V;IND;SG;3;PRS
dafen	dafenum	ADJ;INS;FEM;PL;LGSPEC1
gewær	ġewærra	ADJ;GEN;FEM;PL;LGSPEC1
færgripe	fǣrgripas	N;ACC;PL
cweme	cwēmre	ADJ;DAT;NEUT;SG;LGSPEC2
bucca	buccan	N;ACC;SG
ungelic	unġelīċan	ADJ;ACC;MASC;PL;LGSPEC1
wancol	wancole	ADJ;ACC;NEUT;SG;LGSPEC1
great	grēatum	ADJ;DAT;NEUT;PL;LGSPEC2
norþerne	norþerna	ADJ;NOM;NEUT;PL;LGSPEC2
yþlaf	ȳþlāfa	N;GEN;PL
gamol	gamolan	ADJ;ACC;FEM;PL;LGSPEC1
ænlic	ǣnlīċe	ADJ;ACC;NEUT;PL;LGSPEC2
þyncan	þūhton	V;IND;PL;PST
werig	wēriġena	ADJ;GEN;NEUT;PL;LGSPEC1
behreosan	behrure	V;IND;SG;2;PST
behweorfan	behweorfaþ	V;IND;PL;PRS
ceosan	ċīest	V;IND;SG;3;PRS
cost	costum	ADJ;DAT;MASC;SG;LGSPEC2
hlafordleas	hlāfordlēase	ADJ;ACC;MASC;PL;LGSPEC2
norþerne	norþernan	ADJ;DAT;SG;LGSPEC1
unligne	līġne	ADJ;NOM;FEM;PL;LGSPEC2
dryge	dryġan	ADJ;ACC;PL;LGSPEC1
fiell	fiell	N;ACC;PL
modiglic	mōdiġlīċum	ADJ;INS;NEUT;PL;LGSPEC1
dryge	dryġe	ADJ;ACC;FEM;SG;LGSPEC2
stæflic	stæflīċra	ADJ;GEN;NEUT;PL;LGSPEC1
manian	manian	V;NFIN
weard	ƿeardas	N;ACC;PL
gebyrde	ġebyrde	ADJ;ACC;MASC;PL;LGSPEC2
mamor	māmras	N;NOM;PL
gemætan	ġemǣtte	V;SBJV;SG;PST
bucca	buccan	N;ACC;PL
mæscre	mæscran	N;GEN;SG
hwit	hwītan	ADJ;ACC;PL;LGSPEC1
stigan	ġestigen	V.PTCP;PST
galan	galan	V;NFIN
hnossian	hnossodest	V;IND;SG;2;PST
wancol	wancolne	ADJ;ACC;MASC;SG;LGSPEC2
Seaxisc	Seaxiscu	ADJ;ACC;NEUT;PL;LGSPEC2
staþolian	staþolode	V;IND;SG;3;PST
acumendlic	ācumendlīċra	ADJ;GEN;NEUT;PL;LGSPEC2
ƿindan	ġeƿunden	V.PTCP;PST
bicnol	bīċnolan	ADJ;INS;MASC;SG;LGSPEC1
cost	costan	ADJ;GEN;FEM;SG;LGSPEC1
cnæwe	cnǣwan	ADJ;NOM;PL;LGSPEC1
gecwician	gecwicien	V;SBJV;PL;PRS
stice	stiċe	N;ACC;SG
neþan	nēþden	V;SBJV;PL;PST
stæflic	stæflīċa	ADJ;ACC;FEM;PL;LGSPEC2
sƿiþ	sƿīþra	ADJ;GEN;PL;LGSPEC2
bifian	bifie	V;IND;SG;1;PRS
wancol	wancla	ADJ;NOM;MASC;SG;LGSPEC1
beardleas	beardlēasena	ADJ;GEN;FEM;PL;LGSPEC1
wincel	winclum	N;DAT;PL
genugan	ġenuge	V;SBJV;SG;PRS
gemunan	ġemune	V;SBJV;SG;PRS
minlic	minlīċre	ADJ;DAT;FEM;SG;LGSPEC2
leassagol	lēassagol	ADJ;ACC;NEUT;SG;LGSPEC2
bifian	bifian	V;NFIN
lah	lāh	ADJ;NOM;NEUT;SG;LGSPEC2
eacen	ēacnan	ADJ;NOM;MASC;PL;LGSPEC1
bledsian	tō blēdsianne	V;NFIN
bicnol	bīċnolum	ADJ;DAT;FEM;PL;LGSPEC1
berstan	berstan	V;NFIN
fyrwit	fyrwita	N;GEN;PL
mearcian	tō mearcianne	V;NFIN
wæstmbære	wæstmbǣrum	ADJ;DAT;FEM;PL;LGSPEC1
scufan	scēaf	V;IND;SG;1;PST
sarig	sāriġra	ADJ;GEN;MASC;PL;LGSPEC2
deogol	dēogle	ADJ;ACC;FEM;SG;LGSPEC2
limpan	lamp	V;IND;SG;3;PST
acennedlic	ācennedlīċe	ADJ;ACC;NEUT;SG;LGSPEC1
hwearfian	hwearfiġende	V.PTCP;PRS
borian	borie	V;SBJV;SG;PRS
bleoread	blēorēadum	ADJ;DAT;FEM;PL;LGSPEC2
leon	lāh	V;IND;SG;1;PST
scinu	scine	N;NOM;PL
gebyrde	ġebyrdan	ADJ;ACC;MASC;SG;LGSPEC1
ætren	ǣtrene	ADJ;NOM;FEM;SG;LGSPEC1
werig	wēriġan	ADJ;NOM;MASC;PL;LGSPEC1
gebedda	ġebeddan	N;GEN;SG
lutan	lūte	V;IND;SG;1;PRS
fordon	fordyde	V;IND;SG;1;PST
frod	frōdum	ADJ;DAT;NEUT;PL;LGSPEC1
gewiss	ġewisra	ADJ;GEN;NEUT;PL;LGSPEC1
dreorig	drēoriġum	ADJ;DAT;MASC;PL;LGSPEC2
edcwic	edcwican	ADJ;ACC;NEUT;PL;LGSPEC1
sƿiþ	sƿīþe	ADJ;ACC;FEM;SG;LGSPEC1
calu	calwe	ADJ;ACC;MASC;PL;LGSPEC2
abeodan	ābēad	V;IND;SG;3;PST
deogol	dēogolum	ADJ;INS;NEUT;PL;LGSPEC1
began	begǣþ	V;IND;SG;3;PRS
cuþlæcan	cūþlǣċest	V;IND;SG;2;PRS
wrenc	wrenc	N;NOM;SG
dryht	dryht	N;ACC;SG
cleopian	cleopiġen	V;SBJV;PL;PRS
æsc	æsce	N;DAT;SG
dwinan	dwīn	V;IMP;SG
clipol	clipoles	ADJ;GEN;NEUT;SG;LGSPEC2
blandan	blandende	V.PTCP;PRS
strang	strangan	ADJ;ACC;NEUT;SG;LGSPEC1
geolo	ġeolwes	ADJ;GEN;FEM;SG;LGSPEC2
gælan	tō gælanne	V;NFIN
lah	lāge	ADJ;NOM;NEUT;PL;LGSPEC2
bogiht	bogihtum	ADJ;DAT;NEUT;PL;LGSPEC2
wæstmbære	wæstmbǣru	ADJ;NOM;NEUT;PL;LGSPEC2
geþyldig	ġeþyldiġum	ADJ;DAT;PL;LGSPEC2
arfæst	ārfæste	ADJ;INS;NEUT;SG;LGSPEC2
yst	ȳsta	N;GEN;PL
camb	cambum	N;DAT;PL
hatian	tō hatianne	V;NFIN
dol	dolu	ADJ;NOM;FEM;SG;LGSPEC2
gemyndig	ġemyndġa	ADJ;NOM;FEM;PL;LGSPEC2
gifol	ġifole	ADJ;INS;MASC;SG;LGSPEC2
beogol	bēogole	ADJ;NOM;FEM;SG;LGSPEC1
beorn	beornes	N;GEN;SG
befæstan	befæste	V;IND;SG;3;PST
cearig	ċeariġa	ADJ;NOM;MASC;SG;LGSPEC1
modþracu	mōdþracum	N;DAT;PL
gylden	gyldnan	ADJ;DAT;NEUT;SG;LGSPEC1
receleas	rēċelēasan	ADJ;DAT;MASC;SG;LGSPEC1
medwis	medwīs	ADJ;NOM;MASC;SG;LGSPEC2
soþlic	sōþlīċre	ADJ;INS;FEM;SG;LGSPEC2
wenn	wenn	N;NOM;SG
clipol	clipolum	ADJ;INS;NEUT;PL;LGSPEC2
gewunian	ġewunode	V;IND;SG;1;PST
tilian	tiliġaþ	V;IMP;PL
andweardian	andweardast	V;IND;SG;2;PRS
þeahtian	þeahtian	V;NFIN
reotan	rēat	V;IND;SG;1;PST
cwic	cwice	ADJ;ACC;FEM;SG;LGSPEC1
efenbyrde	evenbyrdum	ADJ;DAT;NEUT;SG;LGSPEC2
batian	bata	V;IMP;SG
þufbære	þūfbǣran	ADJ;ACC;FEM;PL;LGSPEC1
bearneacen	bearnēacenre	ADJ;GEN;FEM;SG;LGSPEC2
cleopian	cleopie	V;SBJV;SG;PRS
mihtig	mihtiġum	ADJ;DAT;NEUT;SG;LGSPEC2
ansien	ansīene	N;ACC;SG
onwæcnan	onwæcnaþ	V;IMP;PL
trymman	trymmaþ	V;IND;PL;PRS
gaderian	gaderie	V;IND;SG;1;PRS
forþgeriman	forþġerīmeþ	V;IND;SG;3;PRS
deogol	dēogolu	ADJ;NOM;FEM;SG;LGSPEC2
andweard	andweardra	ADJ;GEN;NEUT;PL;LGSPEC2
cweme	cwēmne	ADJ;ACC;MASC;SG;LGSPEC2
astyrian	āstyre	V;IMP;SG
medwis	medwīsan	ADJ;INS;NEUT;SG;LGSPEC1
sceotan	scēat	V;IND;SG;1;PST
oferteon	tō ofertēonne	V;NFIN
bær	barum	ADJ;DAT;MASC;SG;LGSPEC2
mearcian	mearcian	V;NFIN
bleoread	blēorēade	ADJ;NOM;FEM;PL;LGSPEC2
sealtian	sealtiġende	V.PTCP;PRS
earfoþdæde	earfoþdǣdum	ADJ;INS;NEUT;PL;LGSPEC2
edstaþeliend	edstaþeliend	N;ACC;SG
bogiht	bogiht	ADJ;ACC;NEUT;SG;LGSPEC2
æwan	ǣwan	V;NFIN
sweltan	swilteþ	V;IND;SG;3;PRS
limpan	lumpe	V;IND;SG;2;PST
flugol	flugolena	ADJ;GEN;NEUT;PL;LGSPEC1
mealwe	mealwan	N;GEN;SG
sendan	sendeþ	V;IND;SG;3;PRS
sarig	sārġum	ADJ;INS;NEUT;PL;LGSPEC1
guþ	gūþum	N;DAT;PL
fleogenda	flēogendena	N;GEN;PL
sarig	sārġan	ADJ;GEN;MASC;SG;LGSPEC1
sugan	suge	V;SBJV;SG;PST
wifmann	wīfmenn	N;NOM;PL
bedecian	bedecodon	V;IND;PL;PST
bleoread	blēorēade	ADJ;NOM;MASC;PL;LGSPEC2
ansien	ansīena	N;ACC;PL
hlafordlic	hlāfordlīċan	ADJ;NOM;MASC;PL;LGSPEC1
hefig	hefġes	ADJ;GEN;NEUT;SG;LGSPEC2
ealdorleas	ealdorlēasne	ADJ;ACC;MASC;SG;LGSPEC2
freme	freme	ADJ;INS;NEUT;SG;LGSPEC2
deagol	dēagole	ADJ;INS;MASC;SG;LGSPEC2
unwæstmbære	unwæstmbǣrum	ADJ;DAT;NEUT;PL;LGSPEC2
becweþan	becweþende	V.PTCP;PRS
oferflitan	oferflīt	V;IMP;SG
midþolian	midþolode	V;SBJV;SG;PST
dafen	dafenan	ADJ;GEN;MASC;SG;LGSPEC1
staniht	stānihte	ADJ;ACC;FEM;PL;LGSPEC2
hefig	hefġum	ADJ;DAT;FEM;PL;LGSPEC1
dryge	dryġra	ADJ;GEN;PL;LGSPEC2
sealtian	sealtie	V;IND;SG;1;PRS
andwis	andwīsan	ADJ;INS;NEUT;SG;LGSPEC1
has	hāsena	ADJ;GEN;MASC;PL;LGSPEC1
wynsum	wynsume	ADJ;INS;NEUT;SG;LGSPEC2
þancian	þancie	V;SBJV;SG;PRS
niman	ġenumen	V.PTCP;PST
wregendlic	wrēġendlīċ	ADJ;NOM;NEUT;SG;LGSPEC2
mægencræft	mæġencræftas	N;NOM;PL
wascan	wōscen	V;SBJV;PL;PST
sarig	sārġan	ADJ;INS;NEUT;SG;LGSPEC1
forcippian	forċippien	V;SBJV;PL;PRS
hefig	hefiġan	ADJ;ACC;FEM;SG;LGSPEC1
hlud	hlūdan	ADJ;GEN;FEM;SG;LGSPEC1
rowan	rēow	V;IND;SG;1;PST
dol	dol	ADJ;ACC;FEM;SG;LGSPEC2
halbære	hālbǣrre	ADJ;GEN;FEM;SG;LGSPEC2
gram	gramum	ADJ;INS;NEUT;PL;LGSPEC2
cidan	ċīd	V;IMP;SG
gerad	ġerādan	ADJ;INS;FEM;SG;LGSPEC1
domleas	dōmlēasena	ADJ;GEN;FEM;PL;LGSPEC1
frinan	frīnan	V;NFIN
spilian	spiliaþ	V;IND;PL;PRS
ealdorleas	ealdorlēase	ADJ;NOM;FEM;SG;LGSPEC1
wacan	wacaþ	V;IND;PL;PRS
hangian	tō hangianne	V;NFIN
gedælan	ġedǣle	V;IND;SG;1;PRS
fætt	fǣttan	ADJ;INS;FEM;SG;LGSPEC1
geposu	ġepose	N;ACC;SG
fon	fō	V;IND;SG;1;PRS
insiht	insihte	N;ACC;SG
þeahtian	þeahtiaþ	V;IMP;PL
gesund	ġesundra	ADJ;GEN;FEM;PL;LGSPEC2
unwæstmbære	unwæstmbǣre	ADJ;NOM;MASC;SG;LGSPEC2
heregrima	heregrīman	N;NOM;PL
ƿindan	ƿand	V;IND;SG;3;PST
modiglic	mōdiġlīċe	ADJ;NOM;FEM;SG;LGSPEC1
seoþan	sēoþo	V;IND;SG;1;PRS
wyrms	wyrms	N;ACC;PL
stille	stille	ADJ;ACC;FEM;PL;LGSPEC2
wancol	wancolan	ADJ;ACC;FEM;SG;LGSPEC1
ærendfæst	ǣrendfæst	ADJ;NOM;NEUT;SG;LGSPEC2
inlihtan	ġeinlīhted	V.PTCP;PST
Seaxisc	Seaxiscum	ADJ;INS;NEUT;PL;LGSPEC1
wrætlic	wrǣtlīċum	ADJ;DAT;FEM;PL;LGSPEC2
hangian	hangiaþ	V;IMP;PL
cost	costan	ADJ;NOM;MASC;PL;LGSPEC1
staniht	stānihtan	ADJ;NOM;MASC;PL;LGSPEC1
leþer	leþra	N;GEN;PL
hlafordlic	hlāfordlīċe	ADJ;INS;MASC;SG;LGSPEC2
geolo	ġeolwa	ADJ;NOM;MASC;SG;LGSPEC1
freogan	frēoġende	V.PTCP;PRS
capian	tō capianne	V;NFIN
tonama	tōnamena	N;GEN;PL
fon	fēng	V;IND;SG;3;PST
gifol	ġifolan	ADJ;ACC;FEM;SG;LGSPEC1
hlafordlic	hlāfordlīċre	ADJ;GEN;FEM;SG;LGSPEC2
cystig	cystiġan	ADJ;ACC;NEUT;PL;LGSPEC1
gecwide	ġecwides	N;GEN;SG
hlud	hlūdum	ADJ;DAT;NEUT;SG;LGSPEC2
fyrd	fyrde	N;ACC;SG
forgietan	forġietan	V;NFIN
cuþlæcan	cūþlǣhte	V;IND;SG;3;PST
nytlic	nytlīċum	ADJ;INS;NEUT;PL;LGSPEC1
sƿefan	sƿǣfen	V;SBJV;PL;PST
leaslic	lēaslīċan	ADJ;DAT;MASC;SG;LGSPEC1
wregendlic	wrēġendlīċa	ADJ;NOM;MASC;SG;LGSPEC1
onlihtan	onlīhtan	V;NFIN
halbære	hālbǣres	ADJ;GEN;MASC;SG;LGSPEC2
bilehwit	bilehwīt	ADJ;NOM;NEUT;PL;LGSPEC2
cwelan	cwæl	V;IND;SG;1;PST
domleas	dōmlēasan	ADJ;GEN;MASC;SG;LGSPEC1
rodfæstnian	rōdfæstnodon	V;IND;PL;PST
gefan	ġefen	V.PTCP;PST
ærendfæst	ǣrendfæstum	ADJ;DAT;NEUT;PL;LGSPEC2
hnah	hnāgum	ADJ;DAT;MASC;SG;LGSPEC2
staniht	stānihta	ADJ;ACC;FEM;PL;LGSPEC2
entisc	entiscre	ADJ;INS;FEM;SG;LGSPEC2
beobread	beobread	N;NOM;PL
beorht	beorhte	ADJ;NOM;MASC;PL;LGSPEC2
cu	cūum	N;DAT;PL
gemyndig	ġemyndġan	ADJ;GEN;MASC;SG;LGSPEC1
cweme	cwēme	ADJ;NOM;FEM;SG;LGSPEC1
efenbyrde	evenbyrdum	ADJ;DAT;FEM;PL;LGSPEC2
lah	lāge	ADJ;NOM;MASC;PL;LGSPEC2
eacen	ēacnan	ADJ;GEN;FEM;SG;LGSPEC1
swican	swāc	V;IND;SG;1;PST
wancol	wancolan	ADJ;GEN;FEM;SG;LGSPEC1
cearig	ċearġe	ADJ;INS;MASC;SG;LGSPEC2
dreorig	drēorġes	ADJ;GEN;MASC;SG;LGSPEC2
frod	frōdan	ADJ;DAT;FEM;SG;LGSPEC1
plegian	pleġiġe	V;SBJV;SG;PRS
werig	wēriġan	ADJ;INS;MASC;SG;LGSPEC1
scitan	scīt	V;IMP;SG
aswebban	āswebbaþ	V;IND;PL;PRS
behealdan	behēolden	V;SBJV;PL;PST
wisian	wīsiende	V.PTCP;PRS
stacga	stacgum	N;DAT;PL
spurnan	spurne	V;SBJV;SG;PST
