araber	arabere	N;NOM;INDF;PL
klimaforandring	klimaforandringens	N;NOM;DEF;SG
metafor	metaforen	N;NOM;DEF;SG
klaviatur	klaviatur	N;NOM;INDF;SG
kommentere	kommenteret	V.PTCP;PST;PASS
bi	bierne	N;NOM;DEF;PL
kirke	kirker	N;NOM;INDF;PL
klare	klaret	V.PTCP;PST;PASS
valravn	valravne	N;NOM;INDF;PL
tungemål	tungemål	N;NOM;INDF;PL
løvinde	løvinde	N;NOM;INDF;SG
elev	elevers	N;GEN;INDF;PL
pengepung	pengepunge	N;NOM;INDF;PL
trekant	trekantens	N;NOM;DEF;SG
hjort	hjort	N;NOM;INDF;SG
pinje	pinjer	N;NOM;INDF;PL
faktotum	faktotummerne	N;NOM;DEF;PL
kraft	kraften	N;NOM;DEF;SG
stjernekaster	stjernekasteres	N;GEN;INDF;PL
teater	teater	N;NOM;INDF;SG
unge	ungens	N;NOM;DEF;SG
løgn	løgnen	N;NOM;DEF;SG
mikrosekund	mikrosekunderne	N;NOM;DEF;PL
mandag	mandagene	N;NOM;DEF;PL
vandrefalk	vandrefalk	N;NOM;INDF;SG
voldtægt	voldtægt	N;NOM;INDF;SG
pattedyr	pattedyrenes	N;NOM;DEF;PL
harpe	harpes	N;GEN;INDF;SG
fond	fonds	N;GEN;INDF;SG
tøjle	tøjlernes	N;NOM;DEF;PL
ytringsfrihed	ytringsfrihedens	N;NOM;DEF;SG
karnap	karnappen	N;NOM;DEF;SG
orgel	orgler	N;NOM;INDF;PL
forklare	forklarende	V.PTCP;PRS;ACT
stab	stabene	N;NOM;DEF;PL
ændringsforslag	ændringsforslagets	N;NOM;DEF;SG
strømstyrke	strømstyrker	N;NOM;INDF;PL
rugbrød	rugbrødene	N;NOM;DEF;PL
pentagram	pentagram	N;NOM;INDF;SG
hvepsetalje	hvepsetaljers	N;GEN;INDF;PL
akkumulator	akkumulatorer	N;NOM;INDF;PL
refraktion	refraktionerne	N;NOM;DEF;PL
konsul	konsulens	N;NOM;DEF;SG
hovedsag	hovedsag	N;NOM;INDF;SG
tomrum	tomrum	N;NOM;INDF;PL
afføring	afførings	N;GEN;INDF;SG
rosé	rosés	N;GEN;INDF;SG
krystallisere	krystalliseredes	V;IND;PST;PASS
lillefinger	lillefingeren	N;NOM;DEF;SG
arie	ariernes	N;NOM;DEF;PL
overmængde	overmængderne	N;NOM;DEF;PL
græsenke	græsenkerne	N;NOM;DEF;PL
glas	glasset	N;NOM;DEF;SG
møde	møde	N;NOM;INDF;SG
musikvideo	musikvideoers	N;GEN;INDF;PL
stol	stolenes	N;NOM;DEF;PL
kloakdyr	kloakdyrs	N;GEN;INDF;SG
hovedpine	hovedpinens	N;NOM;DEF;SG
galge	galgers	N;GEN;INDF;PL
høste	høstede	V;IND;PST;ACT
barnesoldat	barnesoldats	N;GEN;INDF;SG
ambassade	ambassaderne	N;NOM;DEF;PL
vene	venen	N;NOM;DEF;SG
toilet	toilets	N;GEN;INDF;SG
grunde	grundende	V.PTCP;PRS;ACT
offer	ofrene	N;NOM;DEF;PL
affaldsbeholder	affaldsbeholders	N;GEN;INDF;SG
medicin	mediciners	N;GEN;INDF;PL
tyskertøs	tyskertøsens	N;NOM;DEF;SG
hyldebær	hyldebærs	N;GEN;INDF;SG
stol	stolen	N;NOM;DEF;SG
stødtand	stødtand	N;NOM;INDF;SG
småkage	småkagen	N;NOM;DEF;SG
jolle	jollers	N;GEN;INDF;PL
globe	globe	N;NOM;INDF;SG
måned	måneden	N;NOM;DEF;SG
verden	verdens	N;NOM;DEF;SG
bambus	bambussers	N;GEN;INDF;PL
spurt	spurternes	N;NOM;DEF;PL
ordspil	ordspils	N;GEN;INDF;SG
æbletærte	æbletærtens	N;NOM;DEF;SG
patent	patenter	N;NOM;INDF;PL
damp	dampe	N;NOM;INDF;PL
fyrværkeri	fyrværkeris	N;GEN;INDF;SG
talsperson	talspersonen	N;NOM;DEF;SG
spørgsmålstegn	spørgsmålstegns	N;GEN;INDF;SG
mafioso	mafioso	N;NOM;INDF;SG
barnevogn	barnevognene	N;NOM;DEF;PL
nødvendighed	nødvendighed	N;NOM;INDF;SG
odør	odøren	N;NOM;DEF;SG
grankogle	grankogles	N;GEN;INDF;SG
ordklasse	ordklasse	N;NOM;INDF;SG
konservatorium	konservatoriumerne	N;NOM;DEF;PL
nidstirre	nidstirres	V;IND;PRS;PASS
transformator	transformatorerne	N;NOM;DEF;PL
asparges	asparges	N;NOM;INDF;SG
englænderinde	englænderinden	N;NOM;DEF;SG
brunsviger	brunsvigerenes	N;NOM;DEF;PL
kurv	kurvenes	N;NOM;DEF;PL
anæstesi	anæstesiens	N;NOM;DEF;SG
øgle	øglers	N;GEN;INDF;PL
vejskilt	vejskilts	N;GEN;INDF;SG
ildkugle	ildkuglers	N;GEN;INDF;PL
indflyvning	indflyvningers	N;GEN;INDF;PL
nippel	niplensnippelens	N;NOM;DEF;SG
sektor	sektoren	N;NOM;DEF;SG
ærme	ærmet	N;NOM;DEF;SG
vrag	vragene	N;NOM;DEF;PL
definere	definerer	V;IND;PRS;ACT
rugbrød	rugbrød	N;NOM;INDF;PL
ribs	ribsenes	N;NOM;DEF;PL
muddergrøft	muddergrøfterne	N;NOM;DEF;PL
tepotte	tepotter	N;NOM;INDF;PL
præstation	præstationens	N;NOM;DEF;SG
guitarist	guitaristernes	N;NOM;DEF;PL
bøhmand	bøhmænd	N;NOM;INDF;PL
arie	ariens	N;NOM;DEF;SG
klapvogn	klapvognen	N;NOM;DEF;SG
tyveri	tyveris	N;GEN;INDF;SG
hjerne	hjernerne	N;NOM;DEF;PL
møl	møllene	N;NOM;DEF;PL
autoritet	autoriteter	N;NOM;INDF;PL
loppetjans	loppetjanser	N;NOM;INDF;PL
løvinde	løvindernes	N;NOM;DEF;PL
revers	reversens	N;NOM;DEF;SG
fløjt	fløjtene	N;NOM;DEF;PL
værdighed	værdigheder	N;NOM;INDF;PL
motorcyklist	motorcyklister	N;NOM;INDF;PL
nav	nav	N;NOM;INDF;PL
etage	etages	N;GEN;INDF;SG
talord	talord	N;NOM;INDF;PL
udelukkelse	udelukkelse	N;NOM;INDF;SG
statsoverhoved	statsoverhovederne	N;NOM;DEF;PL
akrobat	akrobaters	N;GEN;INDF;PL
kommode	kommoderne	N;NOM;DEF;PL
klient	klient	N;NOM;INDF;SG
hovedpine	hovedpine	N;NOM;INDF;SG
pigtråd	pigtråde	N;NOM;INDF;PL
hollænder	hollænder	N;NOM;INDF;SG
bil	bils	N;GEN;INDF;SG
freske	freskerne	N;NOM;DEF;PL
rådyr	rådyr	N;NOM;INDF;SG
jernbaneoverskæring	jernbaneoverskæringer	N;NOM;INDF;PL
stinkdyr	stinkdyr	N;NOM;INDF;SG
lighed	ligheden	N;NOM;DEF;SG
islænding	islændingen	N;NOM;DEF;SG
europæer	europæernes	N;NOM;DEF;PL
barnesoldat	barnesoldatens	N;NOM;DEF;SG
færdselstavle	færdselstavlerne	N;NOM;DEF;PL
cembalist	cembalists	N;GEN;INDF;SG
palisade	palisaden	N;NOM;DEF;SG
egn	egns	N;GEN;INDF;SG
intelligensprøve	intelligensprøvers	N;GEN;INDF;PL
euro	euroers	N;GEN;INDF;PL
gilding	gildingernes	N;NOM;DEF;PL
skifte	skiftet	N;NOM;DEF;SG
celle	cellernes	N;NOM;DEF;PL
bidrag	bidraget	N;NOM;DEF;SG
cigarettænder	cigarettænderne	N;NOM;DEF;PL
finanslov	finanslove	N;NOM;INDF;PL
krage	kragers	N;GEN;INDF;PL
høstak	høstakkene	N;NOM;DEF;PL
celle	cellers	N;GEN;INDF;PL
pave	paven	N;NOM;DEF;SG
data	data	N;NOM;INDF;SG
mellemkrigsår	mellemkrigsåret	N;NOM;DEF;SG
afføring	afføringer	N;NOM;INDF;PL
kalkulere	kalkulerede	V;IND;PST;ACT
galge	galgernes	N;NOM;DEF;PL
snabel	snabler	N;NOM;INDF;PL
meditation	meditationerne	N;NOM;DEF;PL
oldemor	oldemoren	N;NOM;DEF;SG
vægt	vægtenes	N;NOM;DEF;PL
værdighed	værdighed	N;NOM;INDF;SG
palæ	palæs	N;GEN;INDF;SG
skræl	skrællers	N;GEN;INDF;PL
bestie	besties	N;GEN;INDF;SG
næringsstof	næringsstoffer	N;NOM;INDF;PL
navnebroder	navnebrødrene	N;NOM;DEF;PL
ekstrahere	ekstraherede	V;IND;PST;ACT
englænderinde	englænderindernes	N;NOM;DEF;PL
brunsviger	brunsvigeres	N;GEN;INDF;PL
historie	historierne	N;NOM;DEF;PL
æblesaft	æblesafterne	N;NOM;DEF;PL
kronprinsesse	kronprinsessens	N;NOM;DEF;SG
lut	lutters	N;GEN;INDF;PL
tysker	tyskerens	N;NOM;DEF;SG
peberkværn	peberkværnes	N;GEN;INDF;PL
afsløre	afsløres	V;IND;PRS;PASS
tjørn	tjørns	N;GEN;INDF;SG
blokere	blokerer	V;IND;PRS;ACT
konkurrence	konkurrencers	N;GEN;INDF;PL
angstskrig	angstskrigenes	N;NOM;DEF;PL
ananas	ananas	N;NOM;INDF;PL
bogstav	bogstavs	N;GEN;INDF;SG
accent	accentens	N;NOM;DEF;SG
musikartikel	musikartiklers	N;GEN;INDF;PL
skåning	skåningens	N;NOM;DEF;SG
pengepung	pengepungen	N;NOM;DEF;SG
areal	arealet	N;NOM;DEF;SG
raritet	raritetens	N;NOM;DEF;SG
gerningssted	gerningsstederne	N;NOM;DEF;PL
onomatopoietikon	onomatopoietikonet	N;NOM;DEF;SG
nævn	nævn	N;NOM;INDF;PL
asteroide	asteroide	N;NOM;INDF;SG
pinlighed	pinligheder	N;NOM;INDF;PL
suppe	suppens	N;NOM;DEF;SG
helligdag	helligdag	N;NOM;INDF;SG
risvin	risvines	N;GEN;INDF;PL
orkan	orkanens	N;NOM;DEF;SG
trespring	trespringet	N;NOM;DEF;SG
euro	euroerne	N;NOM;DEF;PL
tand	tand	N;NOM;INDF;SG
bavian	bavianen	N;NOM;DEF;SG
kommentar	kommentarens	N;NOM;DEF;SG
ordinere	ordinerede	V;IND;PST;ACT
regnskov	regnskoven	N;NOM;DEF;SG
hypotese	hypotese	N;NOM;INDF;SG
fader	faderens	N;NOM;DEF;SG
børnesygdom	børnesygdoms	N;GEN;INDF;SG
omelet	omeletterne	N;NOM;DEF;PL
notits	notitserne	N;NOM;DEF;PL
pig	pig	N;NOM;INDF;SG
jungle	junglen	N;NOM;DEF;SG
javaneser	javaneser	N;NOM;INDF;SG
cembalist	cembalisters	N;GEN;INDF;PL
husmand	husmand	N;NOM;INDF;SG
musketer	musketers	N;GEN;INDF;SG
penalhus	penalhus'	N;GEN;INDF;SG
angreb	angrebenes	N;NOM;DEF;PL
etage	etagens	N;NOM;DEF;SG
dadel	dadlen	N;NOM;DEF;SG
kalkun	kalkuner	N;NOM;INDF;PL
koben	kobenene	N;NOM;DEF;PL
musketer	musketeren	N;NOM;DEF;SG
autoritet	autoriteters	N;GEN;INDF;PL
billet	billetters	N;GEN;INDF;PL
bikube	bikuberne	N;NOM;DEF;PL
farmand	farmændenes	N;NOM;DEF;PL
mule	mulers	N;GEN;INDF;PL
sværd	sværdets	N;NOM;DEF;SG
faldgrube	faldgrubers	N;GEN;INDF;PL
møbel	møblers	N;GEN;INDF;PL
adjektiv	adjektivernes	N;NOM;DEF;PL
kapring	kapringen	N;NOM;DEF;SG
facet	facetter	N;NOM;INDF;PL
næringsstof	næringsstof	N;NOM;INDF;SG
terræn	terrænets	N;NOM;DEF;SG
ribs	ribs	N;NOM;INDF;SG
e-mail	e-mailene	N;NOM;DEF;PL
skifte	skifte	N;NOM;INDF;SG
køleskab	køleskabene	N;NOM;DEF;PL
zebrafinke	zebrafinkernes	N;NOM;DEF;PL
verden	verden	N;NOM;DEF;SG
pendant	pendanters	N;GEN;INDF;PL
ekstrem	ekstremerne	N;NOM;DEF;PL
strygebræt	strygebrætterne	N;NOM;DEF;PL
istid	istiders	N;GEN;INDF;PL
kamæleon	kamæleoner	N;NOM;INDF;PL
sørøver	sørøvernes	N;NOM;DEF;PL
agronom	agronomernes	N;NOM;DEF;PL
skumbad	skumbadene	N;NOM;DEF;PL
butik	butiks	N;GEN;INDF;SG
pengeautomat	pengeautomater	N;NOM;INDF;PL
mundharmonika	mundharmonikas	N;GEN;INDF;SG
bidrag	bidragenes	N;NOM;DEF;PL
retfærdighed	retfærdigheders	N;GEN;INDF;PL
ungkarl	ungkarlen	N;NOM;DEF;SG
knap	knaps	N;GEN;INDF;SG
antibiotikum	antibiotikaene	N;NOM;DEF;PL
nævner	nævneren	N;NOM;DEF;SG
låneord	låneord	N;NOM;INDF;PL
ed	ederne	N;NOM;DEF;PL
pessimist	pessimisters	N;GEN;INDF;PL
musikproducer	musikproducers	N;GEN;INDF;SG
helikopter	helikopteren	N;NOM;DEF;SG
rugemor	rugemoren	N;NOM;DEF;SG
sorg	sorgerne	N;NOM;DEF;PL
burger-bar	burger-barernes	N;NOM;DEF;PL
ildflue	ildfluer	N;NOM;INDF;PL
samling	samlingers	N;GEN;INDF;PL
afrikaner	afrikaner	N;NOM;INDF;SG
pincet	pincettens	N;NOM;DEF;SG
greve	grever	N;NOM;INDF;PL
hovedstad	hovedstads	N;GEN;INDF;SG
diæt	diæts	N;GEN;INDF;SG
golfer	golferen	N;NOM;DEF;SG
postkort	postkortene	N;NOM;DEF;PL
manifest	manifest	N;NOM;INDF;SG
roomie	roomies'	N;GEN;INDF;PL
sædvane	sædvane	N;NOM;INDF;SG
rytter	rytter	N;NOM;INDF;SG
topolog	topolog	N;NOM;INDF;SG
tomme	tommer	N;NOM;INDF;PL
intelligenskvotient	intelligenskvotienter	N;NOM;INDF;PL
pattedyr	pattedyrs	N;GEN;INDF;PL
dag	dags	N;GEN;INDF;SG
menu	menuers	N;GEN;INDF;PL
kryddernellike	kryddernellikernes	N;NOM;DEF;PL
fritænker	fritænkers	N;GEN;INDF;SG
hovedserie	hovedseriers	N;GEN;INDF;PL
slof	sloffens	N;NOM;DEF;SG
bekostning	bekostningerne	N;NOM;DEF;PL
sydkyst	sydkysternes	N;NOM;DEF;PL
hjul	hjulene	N;NOM;DEF;PL
sten	sten	N;NOM;INDF;PL
høg	høge	N;NOM;INDF;PL
golfer	golfernes	N;NOM;DEF;PL
brod	brod	N;NOM;INDF;SG
oversvømmelse	oversvømmelsen	N;NOM;DEF;SG
kaj	kajernes	N;NOM;DEF;PL
befolkning	befolkningers	N;GEN;INDF;PL
sekretariat	sekretariaternes	N;NOM;DEF;PL
venskab	venskabs	N;GEN;INDF;SG
dekret	dekreter	N;NOM;INDF;PL
delstatsregering	delstatsregering	N;NOM;INDF;SG
bille	billerne	N;NOM;DEF;PL
dåne	dåne	V;NFIN;ACT
pornograf	pornografs	N;GEN;INDF;SG
guldur	guldures	N;GEN;INDF;PL
voldtægtsmand	voldtægtsmænds	N;GEN;INDF;PL
frisør	frisørens	N;NOM;DEF;SG
nordkyst	nordkysternes	N;NOM;DEF;PL
effekt	effekts	N;GEN;INDF;SG
muslim	muslim	N;NOM;INDF;SG
spilfigur	spilfigurens	N;NOM;DEF;SG
korrigere	korriger	V;IMP;ACT
lut	lutten	N;NOM;DEF;SG
dadel	dadels	N;GEN;INDF;SG
flueknepperi	flueknepperiers	N;GEN;INDF;PL
bageri	bagerierne	N;NOM;DEF;PL
hypnotisør	hypnotisørerne	N;NOM;DEF;PL
tyskertøs	tyskertøserne	N;NOM;DEF;PL
hundesnor	hundesnores	N;GEN;INDF;PL
knagebræt	knagebrætternes	N;NOM;DEF;PL
abdikation	abdikation	N;NOM;INDF;SG
årtusinde	årtusindet	N;NOM;DEF;SG
flue	flues	N;GEN;INDF;SG
trappe	trapper	N;NOM;INDF;PL
forglemmigej	forglemmigej	N;NOM;INDF;SG
drue	drues	N;GEN;INDF;SG
droge	droger	N;NOM;INDF;PL
lingvist	lingvisternes	N;NOM;DEF;PL
revers	reversen	N;NOM;DEF;SG
sejr	sejrenes	N;NOM;DEF;PL
punkt	punkt	N;NOM;INDF;SG
ingeniør	ingeniøren	N;NOM;DEF;SG
oversvømmelse	oversvømmelserne	N;NOM;DEF;PL
mole	molerne	N;NOM;DEF;PL
hyl	hylenes	N;NOM;DEF;PL
rotte	rottes	N;GEN;INDF;SG
kroge	kroget	V.PTCP;PST;PASS
anorak	anorakkenes	N;NOM;DEF;PL
vandmelon	vandmelonen	N;NOM;DEF;SG
mynte	mynters	N;GEN;INDF;PL
superorganisme	superorganismerne	N;NOM;DEF;PL
skåle	skåles	V;IND;PRS;PASS
babysæl	babysæler	N;NOM;INDF;PL
skattekiste	skattekisten	N;NOM;DEF;SG
pagaj	pagajen	N;NOM;DEF;SG
magre	magrer	V;IND;PRS;ACT
issyl	issyl	N;NOM;INDF;SG
konkurs	konkursernes	N;NOM;DEF;PL
begyndelse	begyndelserne	N;NOM;DEF;PL
strygebræt	strygebrættet	N;NOM;DEF;SG
diagonal	diagonaler	N;NOM;INDF;PL
forglemmigej	forglemmigejs	N;GEN;INDF;SG
gamache	gamachernes	N;NOM;DEF;PL
gedde	gedderne	N;NOM;DEF;PL
storetå	storetæer	N;NOM;INDF;PL
kønsord	kønsordets	N;NOM;DEF;SG
musikkonservatorie	musikkonservatoriernes	N;NOM;DEF;PL
broderskab	broderskabernes	N;NOM;DEF;PL
knogle	knoglens	N;NOM;DEF;SG
frue	frue	N;NOM;INDF;SG
forsømthed	forsømtheds	N;GEN;INDF;SG
danisere	daniserende	V.PTCP;PRS;ACT
dekagram	dekagrammet	N;NOM;DEF;SG
polygon	polygon	N;NOM;INDF;SG
kondom	kondomets	N;NOM;DEF;SG
kranse	kransende	V.PTCP;PRS;ACT
gondol	gondol	N;NOM;INDF;SG
overbid	overbiddene	N;NOM;DEF;PL
kloakdyr	kloakdyr	N;NOM;INDF;PL
boysenbær	boysenbær	N;NOM;INDF;SG
motiv	motiv	N;NOM;INDF;SG
tøjle	tøjlerne	N;NOM;DEF;PL
ståltråd	ståltrådene	N;NOM;DEF;PL
filter	filtrenes	N;NOM;DEF;PL
hypnose	hypnoser	N;NOM;INDF;PL
bistro	bistro	N;NOM;INDF;SG
odør	odørernes	N;NOM;DEF;PL
pomfrit	pomfritternes	N;NOM;DEF;PL
førnutid	førnutids	N;GEN;INDF;SG
jubilæum	jubilæers	N;GEN;INDF;PL
kylling	kyllingernes	N;NOM;DEF;PL
pæderast	pæderasten	N;NOM;DEF;SG
høg	høges	N;GEN;INDF;PL
dekoration	dekorationen	N;NOM;DEF;SG
lyske	lyskens	N;NOM;DEF;SG
droge	drogen	N;NOM;DEF;SG
rotte	rotterne	N;NOM;DEF;PL
øreflip	øreflippen	N;NOM;DEF;SG
forårsrulle	forårsruller	N;NOM;INDF;PL
forhøjelse	forhøjelsers	N;GEN;INDF;PL
nitrat	nitrater	N;NOM;INDF;PL
emballage	emballages	N;GEN;INDF;SG
æblesaft	æblesafters	N;GEN;INDF;PL
TV-program	TV-programs	N;GEN;INDF;SG
kusk	kusken	N;NOM;DEF;SG
pigtråd	pigtrådenes	N;NOM;DEF;PL
gravsten	gravsten	N;NOM;INDF;PL
bedemand	bedemændene	N;NOM;DEF;PL
forkølelse	forkølelse	N;NOM;INDF;SG
intelligensniveau	intelligensniveauerne	N;NOM;DEF;PL
metafor	metaforers	N;GEN;INDF;PL
violin	violiner	N;NOM;INDF;PL
anholdelse	anholdelses	N;GEN;INDF;SG
rokere	rokerer	V;IND;PRS;ACT
pizza	pizza	N;NOM;INDF;SG
kriterium	kriterium	N;NOM;INDF;SG
formue	formue	N;NOM;INDF;SG
hjul	hjulets	N;NOM;DEF;SG
plekter	plektrets	N;NOM;DEF;SG
pilot	piloters	N;GEN;INDF;PL
kobber	kobberne	N;NOM;DEF;PL
subjekt	subjekts	N;GEN;INDF;SG
tyskertøs	tyskertøsernes	N;NOM;DEF;PL
katakombe	katakombernes	N;NOM;DEF;PL
virolog	virologs	N;GEN;INDF;SG
eng	engen	N;NOM;DEF;SG
autopsi	autopsiernes	N;NOM;DEF;PL
lort	lortens	N;NOM;DEF;SG
skalerbarhed	skalerbarheders	N;GEN;INDF;PL
pynt	pynternes	N;NOM;DEF;PL
akrobat	akrobat	N;NOM;INDF;SG
affaldskurv	affaldskurvenes	N;NOM;DEF;PL
aubergine	aubergine	N;NOM;INDF;SG
campingvogn	campingvognens	N;NOM;DEF;SG
mafioso	mafiosos	N;GEN;INDF;SG
ambassade	ambassadernes	N;NOM;DEF;PL
reklame	reklamerne	N;NOM;DEF;PL
tøsedreng	tøsedrengenes	N;NOM;DEF;PL
bi	bis	N;GEN;INDF;SG
knæ	knæet	N;NOM;DEF;SG
advarsel	advarslerne	N;NOM;DEF;PL
collie	collierne	N;NOM;DEF;PL
galehus	galehus'	N;GEN;INDF;SG
gnu	gnuer	N;NOM;INDF;PL
sammenskrivning	sammenskrivning	N;NOM;INDF;SG
plekter	plektrenes	N;NOM;DEF;PL
orkestergrav	orkestergravs	N;GEN;INDF;SG
deisme	deismens	N;NOM;DEF;SG
drue	druen	N;NOM;DEF;SG
babylem	babylemmes	N;GEN;INDF;PL
kobber	kobbere	N;NOM;INDF;PL
finmark	finmark	N;NOM;INDF;SG
padde	padders	N;GEN;INDF;PL
massakre	massakrernes	N;NOM;DEF;PL
dørmåtte	dørmåttes	N;GEN;INDF;SG
nødudgang	nødudgange	N;NOM;INDF;PL
hik	hik	N;NOM;INDF;SG
knæ	knæene	N;NOM;DEF;PL
svastika	svastikaer	N;NOM;INDF;PL
kvæld	kvælds	N;GEN;INDF;SG
datere	datere	V;NFIN;ACT
biting	bitingens	N;NOM;DEF;SG
nudel	nudlers	N;GEN;INDF;PL
sten	stens	N;GEN;INDF;SG
golfer	golferes	N;GEN;INDF;PL
pelikan	pelikaner	N;NOM;INDF;PL
færdselstavle	færdselstavlens	N;NOM;DEF;SG
signere	signeres	V;IND;PRS;PASS
abbed	abbederne	N;NOM;DEF;PL
mandelolie	mandeloliernes	N;NOM;DEF;PL
recirkulation	recirkulationerne	N;NOM;DEF;PL
menage	menagers	N;GEN;INDF;PL
pulver	pulverets	N;NOM;DEF;SG
symbol	symbolets	N;NOM;DEF;SG
klan	klans	N;GEN;INDF;SG
ekstrem	ekstrem	N;NOM;INDF;SG
bug	bugen	N;NOM;DEF;SG
fund	funds	N;GEN;INDF;PL
mælkevej	mælkevejens	N;NOM;DEF;SG
ærme	ærmerne	N;NOM;DEF;PL
urinal	urinalers	N;GEN;INDF;PL
brydningsindeks	brydningsindeksers	N;GEN;INDF;PL
modersmål	modersmålene	N;NOM;DEF;PL
babydoll	babydolls'	N;GEN;INDF;PL
stab	stabes	N;GEN;INDF;PL
pennalhus	pennalhusene	N;NOM;DEF;PL
knap	knapper	N;NOM;INDF;PL
flødekaramel	flødekaramel	N;NOM;INDF;SG
urinrør	urinrør	N;NOM;INDF;SG
dyrskue	dyrskues	N;GEN;INDF;SG
tante	tanters	N;GEN;INDF;PL
orkestergrav	orkestergravenes	N;NOM;DEF;PL
kildekode	kildekoder	N;NOM;INDF;PL
grundlag	grundlags	N;GEN;INDF;PL
skåning	skåningernes	N;NOM;DEF;PL
defekt	defekts	N;GEN;INDF;SG
trappe	trappens	N;NOM;DEF;SG
kobber	kobberes	N;GEN;INDF;PL
bodybuilder	bodybuildernes	N;NOM;DEF;PL
pedel	pedeller	N;NOM;INDF;PL
klimaændring	klimaændringen	N;NOM;DEF;SG
orm	ormeorm	N;NOM;INDF;PL
subtraktion	subtraktion	N;NOM;INDF;SG
sneugle	sneuglen	N;NOM;DEF;SG
oversvømmelse	oversvømmelser	N;NOM;INDF;PL
gen	gens	N;GEN;INDF;SG
kalkulere	kalkuleres	V;IND;PRS;PASS
afstand	afstandens	N;NOM;DEF;SG
basketballspiller	basketballspilleren	N;NOM;DEF;SG
anledning	anledninger	N;NOM;INDF;PL
hundesnor	hundesnor	N;NOM;INDF;SG
datter	datters	N;GEN;INDF;SG
samarbejde	samarbejdes	N;GEN;INDF;SG
paragraf	paragraffer	N;NOM;INDF;PL
kaj	kajens	N;NOM;DEF;SG
neksøbo	neksøboernes	N;NOM;DEF;PL
kælenavn	kælenavns	N;GEN;INDF;SG
grænse	grænsernes	N;NOM;DEF;PL
hovedpine	hovedpinen	N;NOM;DEF;SG
samling	samling	N;NOM;INDF;SG
guldsmed	guldsmedenes	N;NOM;DEF;PL
psykose	psykosens	N;NOM;DEF;SG
guldur	guldur	N;NOM;INDF;SG
krise	krises	N;GEN;INDF;SG
sudaner	sudaners	N;GEN;INDF;SG
højttaler	højttaler	N;NOM;INDF;SG
bøsse	bøsse	N;NOM;INDF;SG
stådreng	stådrenge	N;NOM;INDF;PL
pinlighed	pinligheden	N;NOM;DEF;SG
japaner	japaneren	N;NOM;DEF;SG
skov	skovene	N;NOM;DEF;PL
vandmelon	vandmelon	N;NOM;INDF;SG
chok	chok	N;NOM;INDF;SG
anglofil	anglofil	N;NOM;INDF;SG
huskat	huskatte	N;NOM;INDF;PL
subjekt	subjekters	N;GEN;INDF;PL
psykologi	psykologier	N;NOM;INDF;PL
nippel	niplers	N;GEN;INDF;PL
beton	betonens	N;NOM;DEF;SG
kaj	kajerne	N;NOM;DEF;PL
certifikat	certifikaters	N;GEN;INDF;PL
strikkepind	strikkepindene	N;NOM;DEF;PL
ildflue	ildflues	N;GEN;INDF;SG
oversvømmelse	oversvømmelses	N;GEN;INDF;SG
hår	hår	N;NOM;INDF;SG
juvel	juvels	N;GEN;INDF;SG
browser	browsernes	N;NOM;DEF;PL
hellebard	hellebardernes	N;NOM;DEF;PL
kvæld	kvælden	N;NOM;DEF;SG
græskar	græskar	N;NOM;INDF;SG
kuldegysning	kuldegysningernes	N;NOM;DEF;PL
tykhornsfår	tykhornsfår	N;NOM;INDF;SG
bombardement	bombardementet	N;NOM;DEF;SG
pande	panderne	N;NOM;DEF;PL
delegat	delegat	N;NOM;INDF;SG
sonet	sonet	N;NOM;INDF;SG
fagot	fagotter	N;NOM;INDF;PL
valnød	valnøddens	N;NOM;DEF;SG
rollespil	rollespil	N;NOM;INDF;PL
onomatopoietikon	onomatopoietikon	N;NOM;INDF;SG
pattedyr	pattedyr	N;NOM;INDF;PL
østkyst	østkystens	N;NOM;DEF;SG
cigaretstump	cigaretstumpernes	N;NOM;DEF;PL
angstskrig	angstskrigs	N;GEN;INDF;SG
malke	malke	V;NFIN;ACT
snuble	snubledes	V;IND;PST;PASS
dryp	dryp	N;NOM;INDF;PL
fodjonglør	fodjonglørs	N;GEN;INDF;SG
forhøjelse	forhøjelse	N;NOM;INDF;SG
beton	betons	N;GEN;INDF;SG
brugerdiskussion	brugerdiskussions	N;GEN;INDF;SG
krøsus	krøsus	N;NOM;INDF;SG
apotek	apotekernes	N;NOM;DEF;PL
skohorn	skohorns	N;GEN;INDF;PL
abrikostræ	abrikostræ	N;NOM;INDF;SG
frøken	frøkeners	N;GEN;INDF;PL
trold	troldene	N;NOM;DEF;PL
tilstand	tilstandes	N;GEN;INDF;PL
hermafrodit	hermafroditters	N;GEN;INDF;PL
røgalarm	røgalarmens	N;NOM;DEF;SG
skulderblad	skulderbladenes	N;NOM;DEF;PL
helikopter	helikopterens	N;NOM;DEF;SG
sædvane	sædvanernes	N;NOM;DEF;PL
deisme	deisme	N;NOM;INDF;SG
elefant	elefanternes	N;NOM;DEF;PL
atmosfære	atmosfærernes	N;NOM;DEF;PL
isvaffel	isvaflers	N;GEN;INDF;PL
egennavn	egennavne	N;NOM;INDF;PL
måbe	måbe	V;NFIN;ACT
paragraf	paragraffen	N;NOM;DEF;SG
freske	freskernes	N;NOM;DEF;PL
nippel	niplernes	N;NOM;DEF;PL
tankbil	tankbiler	N;NOM;INDF;PL
madras	madrassers	N;GEN;INDF;PL
løb	løbets	N;NOM;DEF;SG
lår	lårs	N;GEN;INDF;PL
snabel	snabels	N;GEN;INDF;SG
knæ	knæets	N;NOM;DEF;SG
slikkepot	slikkepotter	N;NOM;INDF;PL
tagetes	tagetes	N;NOM;INDF;SG
densitet	densiteten	N;NOM;DEF;SG
kunstgalleri	kunstgalleriernes	N;NOM;DEF;PL
accelerere	accelereredes	V;IND;PST;PASS
knurhår	knurhår	N;NOM;INDF;SG
torv	torve	N;NOM;INDF;PL
vams	vamsene	N;NOM;DEF;PL
dukke	dukkers	N;GEN;INDF;PL
napoleonshat	napoleonshatten	N;NOM;DEF;SG
insektæder	insektæders	N;GEN;INDF;SG
kædesav	kædesav	N;NOM;INDF;SG
spermatozo	spermatozo	N;NOM;INDF;SG
konfiskere	konfiskeredes	V;IND;PST;PASS
altæder	altæders	N;GEN;INDF;SG
toilet	toiletterne	N;NOM;DEF;PL
pelargonie	pelargonierne	N;NOM;DEF;PL
toilet	toilet	N;NOM;INDF;SG
agurk	agurks	N;GEN;INDF;SG
krematorie	krematoriet	N;NOM;DEF;SG
snebold	snebolde	N;NOM;INDF;PL
inficere	inficere	V;NFIN;ACT
hvirveldyr	hvirveldyrs	N;GEN;INDF;SG
grønsag	grønsagers	N;GEN;INDF;PL
atmosfære	atmosfærens	N;NOM;DEF;SG
pate	pateers	N;GEN;INDF;PL
bro	broen	N;NOM;DEF;SG
flertal	flertallene	N;NOM;DEF;PL
oversættelseslån	oversættelseslånets	N;NOM;DEF;SG
årtusinde	årtusindets	N;NOM;DEF;SG
tomat	tomats	N;GEN;INDF;SG
hat	hattes	N;GEN;INDF;PL
klimaforandring	klimaforandringer	N;NOM;INDF;PL
facet	facetters	N;GEN;INDF;PL
kolesterol	kolesterolens	N;NOM;DEF;SG
anholdelse	anholdelse	N;NOM;INDF;SG
raritet	rariteters	N;GEN;INDF;PL
skærf	skærfet	N;NOM;DEF;SG
hypnotisør	hypnotisørs	N;GEN;INDF;SG
basketballspiller	basketballspillerene	N;NOM;DEF;PL
chimpanse	chimpanser	N;NOM;INDF;PL
aforisme	aforismens	N;NOM;DEF;SG
guldsmed	guldsmed	N;NOM;INDF;SG
ventil	ventils	N;GEN;INDF;SG
tryk	tryks	N;GEN;INDF;SG
hov	hoves	N;GEN;INDF;PL
biskop	biskoppers	N;GEN;INDF;PL
kødspiser	kødspisers	N;GEN;INDF;SG
hytte	hyttens	N;NOM;DEF;SG
troldmand	troldmændene	N;NOM;DEF;PL
medicin	mediciner	N;NOM;INDF;PL
vandrør	vandrørets	N;NOM;DEF;SG
tærte	tærten	N;NOM;DEF;SG
medley	medleyers	N;GEN;INDF;PL
bro	bros	N;GEN;INDF;SG
trespring	trespringenes	N;NOM;DEF;PL
sektor	sektorer	N;NOM;INDF;PL
ægte	ægtes	V;IND;PRS;PASS
cembalist	cembalisterne	N;NOM;DEF;PL
potentat	potentater	N;NOM;INDF;PL
fag	fags	N;GEN;INDF;PL
jolle	jollen	N;NOM;DEF;SG
algoritme	algoritmerne	N;NOM;DEF;PL
lokum	lokums	N;GEN;INDF;SG
smøre	smørernes	N;NOM;DEF;PL
gratulant	gratulants	N;GEN;INDF;SG
radiobil	radiobilers	N;GEN;INDF;PL
pingvin	pingvinen	N;NOM;DEF;SG
estragon	estragonens	N;NOM;DEF;SG
penis	penisserne	N;NOM;DEF;PL
fund	fundet	N;NOM;DEF;SG
krokodilletåre	krokodilletårer	N;NOM;INDF;PL
ingeniør	ingeniør	N;NOM;INDF;SG
klap-sammen-mad	klap-sammen-madders	N;GEN;INDF;PL
idiotsikre	idiotsikre	V;NFIN;ACT
droge	droge	N;NOM;INDF;SG
mær	mære	N;NOM;INDF;PL
kurs	kursen	N;NOM;DEF;SG
frimurer	frimureres	N;GEN;INDF;PL
kanapé	kanapéens	N;NOM;DEF;SG
smed	smeds	N;GEN;INDF;SG
gnist	gnist	N;NOM;INDF;SG
ør	ørerne	N;NOM;DEF;PL
gemytlighed	gemytligheder	N;NOM;INDF;PL
oversvømmelse	oversvømmelsers	N;GEN;INDF;PL
potentat	potentaterne	N;NOM;DEF;PL
apotek	apotek	N;NOM;INDF;SG
bygkorn	bygkornets	N;NOM;DEF;SG
rhesusabe	rhesusabens	N;NOM;DEF;SG
newzealænder	newzealænderes	N;GEN;INDF;PL
appelsinskræl	appelsinskrællernes	N;NOM;DEF;PL
juletræ	juletræets	N;NOM;DEF;SG
kronprins	kronprinser	N;NOM;INDF;PL
suspensorium	suspensoriers	N;GEN;INDF;PL
hestesko	hesteskoens	N;NOM;DEF;SG
pincet	pincetter	N;NOM;INDF;PL
makron	makrons	N;GEN;INDF;SG
topografi	topografiens	N;NOM;DEF;SG
spækhugger	spækhugger	N;NOM;INDF;SG
hingst	hingst	N;NOM;INDF;SG
nævn	nævnene	N;NOM;DEF;PL
bulgarer	bulgareres	N;GEN;INDF;PL
æggestok	æggestokkens	N;NOM;DEF;SG
ko	koen	N;NOM;DEF;SG
dram	dram	N;NOM;INDF;SG
kno	knoers	N;GEN;INDF;PL
elg	elges	N;GEN;INDF;PL
zarina	zarinas	N;GEN;INDF;SG
autodidakt	autodidakternes	N;NOM;DEF;PL
babysæl	babysælerne	N;NOM;DEF;PL
bodybuilder	bodybuilderen	N;NOM;DEF;SG
procentpoint	procentpointet	N;NOM;DEF;SG
geometri	geometrien	N;NOM;DEF;SG
bodybuilder	bodybuilders	N;GEN;INDF;SG
krage	krage	N;NOM;INDF;SG
ven	venners	N;GEN;INDF;PL
gene	genes	N;GEN;INDF;SG
menage	menages	N;GEN;INDF;SG
grøft	grøftens	N;NOM;DEF;SG
lillefinger	lillefingrene	N;NOM;DEF;PL
svanesang	svanesangene	N;NOM;DEF;PL
afdeling	afdelings	N;GEN;INDF;SG
afstemning	afstemningen	N;NOM;DEF;SG
tjørn	tjørn	N;NOM;INDF;SG
færdselstavle	færdselstavlen	N;NOM;DEF;SG
verden	verdens	N;GEN;INDF;SG
børnesoldat	børnesoldaten	N;NOM;DEF;SG
øjenbryn	øjenbrynet	N;NOM;DEF;SG
collie	collies	N;GEN;INDF;SG
aktieselskab	aktieselskabet	N;NOM;DEF;SG
cykeldæk	cykeldækkenes	N;NOM;DEF;PL
perle	perlernes	N;NOM;DEF;PL
følelse	følelse	N;NOM;INDF;SG
mikroskop	mikroskopet	N;NOM;DEF;SG
jubilæum	jubilæet	N;NOM;DEF;SG
rådyr	rådyrs	N;GEN;INDF;PL
autodidakt	autodidakts	N;GEN;INDF;SG
klare	klarede	V;IND;PST;ACT
stud	studes	N;GEN;INDF;PL
peanut	peanuts'	N;GEN;INDF;PL
kedel	kedlenkedelen	N;NOM;DEF;SG
fund	fund	N;NOM;INDF;PL
danse	danser	V;IND;PRS;ACT
harpe	harpe	N;NOM;INDF;SG
fiskestang	fiskestænger	N;NOM;INDF;PL
hytte	hytte	N;NOM;INDF;SG
projekt	projekternes	N;NOM;DEF;PL
videnskabsmand	videnskabsmands	N;GEN;INDF;SG
manko	mankoernes	N;NOM;DEF;PL
skærf	skærfs	N;GEN;INDF;PL
sjæl	sjælene	N;NOM;DEF;PL
kilometer	kilometeren	N;NOM;DEF;SG
yver	yvere	N;NOM;INDF;PL
genotype	genotype	N;NOM;INDF;SG
kløftehammer	kløftehammere	N;NOM;INDF;PL
hynde	hynden	N;NOM;DEF;SG
musikinstrument	musikinstrument	N;NOM;INDF;SG
længsel	længslernes	N;NOM;DEF;PL
egern	egernets	N;NOM;DEF;SG
smoking	smoking	N;NOM;INDF;SG
efternavn	efternavnenes	N;NOM;DEF;PL
røvhul	røvhullet	N;NOM;DEF;SG
bandeord	bandeordet	N;NOM;DEF;SG
nævner	nævnerenes	N;NOM;DEF;PL
farvestof	farvestof	N;NOM;INDF;SG
orm	ormesorms	N;GEN;INDF;PL
samfund	samfundene	N;NOM;DEF;PL
trespring	trespring	N;NOM;INDF;PL
brasilianer	brasilianeres	N;GEN;INDF;PL
trimester	trimestrenes	N;NOM;DEF;PL
voldtægt	voldtægten	N;NOM;DEF;SG
voldtægt	voldtægts	N;GEN;INDF;SG
lørdag	lørdagens	N;NOM;DEF;SG
musikkonservatorie	musikkonservatorier	N;NOM;INDF;PL
forklare	forklaret	V.PTCP;PST;PASS
pelargonie	pelargonien	N;NOM;DEF;SG
satse	satsende	V.PTCP;PRS;ACT
allike	allikes	N;GEN;INDF;SG
smølf	smølfen	N;NOM;DEF;SG
optimist	optimisterne	N;NOM;DEF;PL
sædvane	sædvanens	N;NOM;DEF;SG
mus	musenes	N;NOM;DEF;PL
præst	præstens	N;NOM;DEF;SG
næringsstof	næringsstofferne	N;NOM;DEF;PL
tomme	tommes	N;GEN;INDF;SG
grøft	grøfternes	N;NOM;DEF;PL
højdespring	højdespringene	N;NOM;DEF;PL
gilding	gildingerne	N;NOM;DEF;PL
kno	knoernes	N;NOM;DEF;PL
cykeldæk	cykeldæks	N;GEN;INDF;PL
bug	buges	N;GEN;INDF;PL
relativ	relativ	N;NOM;INDF;SG
hat	hatte	N;NOM;INDF;PL
mælkebøtte	mælkebøtternes	N;NOM;DEF;PL
pengeautomat	pengeautomaters	N;GEN;INDF;PL
afsnit	afsnittene	N;NOM;DEF;PL
fregne	fregner	N;NOM;INDF;PL
løsesum	løsesummers	N;GEN;INDF;PL
middag	middagen	N;NOM;DEF;SG
napoleonshat	napoleonshattes	N;GEN;INDF;PL
issyl	issylene	N;NOM;DEF;PL
apotek	apotekerne	N;NOM;DEF;PL
tømrer	tømrerne	N;NOM;DEF;PL
vindruekerneolie	vindruekerneoliernes	N;NOM;DEF;PL
muskel	musklers	N;GEN;INDF;PL
forsikring	forsikringers	N;GEN;INDF;PL
afsløre	afslørende	V.PTCP;PRS;ACT
dekagram	dekagrammene	N;NOM;DEF;PL
propeller	propellernes	N;NOM;DEF;PL
kvæld	kvæld	N;NOM;INDF;SG
hofteholder	hofteholders	N;GEN;INDF;SG
kasserolle	kasserollens	N;NOM;DEF;SG
kutyme	kutymernes	N;NOM;DEF;PL
aktivitet	aktiviteters	N;GEN;INDF;PL
spurt	spurterne	N;NOM;DEF;PL
inuit	inuits	N;GEN;INDF;SG
kødæder	kødæderes	N;GEN;INDF;PL
kødspiser	kødspiserens	N;NOM;DEF;SG
tværfløjte	tværfløjterne	N;NOM;DEF;PL
epitet	epitetet	N;NOM;DEF;SG
vittighed	vittigheden	N;NOM;DEF;SG
armlægning	armlægningernes	N;NOM;DEF;PL
ædelsten	ædelsten	N;NOM;INDF;SG
kande	kanders	N;GEN;INDF;PL
celle	celle	N;NOM;INDF;SG
sål	sålernes	N;NOM;DEF;PL
trommesæt	trommesættets	N;NOM;DEF;SG
søn	søns	N;GEN;INDF;SG
veto	vetoernes	N;NOM;DEF;PL
uddannelse	uddannelses	N;GEN;INDF;SG
sædvane	sædvaner	N;NOM;INDF;PL
nippel	niplennippelen	N;NOM;DEF;SG
verdensmester	verdensmester	N;NOM;INDF;SG
strategi	strategis	N;GEN;INDF;SG
akkumulator	akkumulator	N;NOM;INDF;SG
kyniker	kynikere	N;NOM;INDF;PL
orkan	orkan	N;NOM;INDF;SG
skumbad	skumbades	N;GEN;INDF;PL
telefonbog	telefonbogen	N;NOM;DEF;SG
talemåde	talemåde	N;NOM;INDF;SG
egern	egerns	N;GEN;INDF;SG
flygel	flyglerne	N;NOM;DEF;PL
bæ	bæens	N;NOM;DEF;SG
statsoverhoved	statsoverhovedernes	N;NOM;DEF;PL
farvestof	farvestoffer	N;NOM;INDF;PL
dødelighed	dødeligheder	N;NOM;INDF;PL
havfrue	havfruens	N;NOM;DEF;SG
uheld	uheld	N;NOM;INDF;PL
baby-sitter	baby-sitters	N;GEN;INDF;SG
flygel	flygel	N;NOM;INDF;SG
solnedgang	solnedgangene	N;NOM;DEF;PL
helgen	helgen	N;NOM;INDF;SG
fløjt	fløjt	N;NOM;INDF;SG
kalv	kalvene	N;NOM;DEF;PL
juicer	juicere	N;NOM;INDF;PL
harpe	harpens	N;NOM;DEF;SG
udråbstegn	udråbstegn	N;NOM;INDF;PL
akkumulator	akkumulatoren	N;NOM;DEF;SG
motiv	motiver	N;NOM;INDF;PL
tagetes	tagetesene	N;NOM;DEF;PL
godbid	godbiddernes	N;NOM;DEF;PL
radio	radioen	N;NOM;DEF;SG
palisade	palisaderne	N;NOM;DEF;PL
trafikprop	trafikprops	N;GEN;INDF;SG
syre	syrernes	N;NOM;DEF;PL
urinal	urinalernes	N;NOM;DEF;PL
frænke	frænker	N;NOM;INDF;PL
glimt	glimtets	N;NOM;DEF;SG
elev	elev	N;NOM;INDF;SG
niece	niecen	N;NOM;DEF;SG
trekant	trekanten	N;NOM;DEF;SG
afsløre	afsløre	V;NFIN;ACT
fag	fags	N;GEN;INDF;SG
suppe	suppe	N;NOM;INDF;SG
gælle	gælles	N;GEN;INDF;SG
certifikat	certifikaternes	N;NOM;DEF;PL
muskel	musklen	N;NOM;DEF;SG
spilfigur	spilfigurernes	N;NOM;DEF;PL
datamat	datamater	N;NOM;INDF;PL
krematorie	krematorierne	N;NOM;DEF;PL
skidt	skidtets	N;NOM;DEF;SG
kineser	kineseres	N;GEN;INDF;PL
malke	malkende	V.PTCP;PRS;ACT
rejecocktail	rejecocktail	N;NOM;INDF;SG
mule	mulens	N;NOM;DEF;SG
satire	satirernes	N;NOM;DEF;PL
vægtfylde	vægtfylden	N;NOM;DEF;SG
orgel	orgels	N;GEN;INDF;SG
finmark	finmarkens	N;NOM;DEF;SG
intervention	interventionernes	N;NOM;DEF;PL
zarina	zarina	N;NOM;INDF;SG
ordinere	ordineredes	V;IND;PST;PASS
eksamen	eksamenerne	N;NOM;DEF;PL
gerningssted	gerningsstedet	N;NOM;DEF;SG
hat	hattene	N;NOM;DEF;PL
ambassade	ambassaden	N;NOM;DEF;SG
kupon	kuponers	N;GEN;INDF;PL
grankogle	grankoglernes	N;NOM;DEF;PL
sikkerhed	sikkerheds	N;GEN;INDF;SG
mus	mus'	N;GEN;INDF;SG
tryk	trykkenes	N;NOM;DEF;PL
gudstjeneste	gudstjenesternes	N;NOM;DEF;PL
nitrat	nitraterne	N;NOM;DEF;PL
ekstrahere	ekstraheres	V;IND;PRS;PASS
hypnose	hypnosen	N;NOM;DEF;SG
emirat	emiraternes	N;NOM;DEF;PL
fodre	fodredes	V;IND;PST;PASS
forhøjelse	forhøjelsen	N;NOM;DEF;SG
hånd	hånds	N;GEN;INDF;SG
elg	elgene	N;NOM;DEF;PL
recirkulation	recirkulationernes	N;NOM;DEF;PL
søjle	søjlers	N;GEN;INDF;PL
mundharpe	mundharpens	N;NOM;DEF;SG
japaner	japanerne	N;NOM;DEF;PL
kompagnon	kompagnoner	N;NOM;INDF;PL
kuffert	kufferter	N;NOM;INDF;PL
hane	hane	N;NOM;INDF;SG
eritreer	eritreerens	N;NOM;DEF;SG
mester	mesters	N;GEN;INDF;SG
kaskelothval	kaskelothvals	N;GEN;INDF;SG
mole	moler	N;NOM;INDF;PL
grupperabat	grupperabatten	N;NOM;DEF;SG
nexøbo	nexøboen	N;NOM;DEF;SG
cigaretstump	cigaretstumpers	N;GEN;INDF;PL
elg	elgens	N;NOM;DEF;SG
dommer	dommer	N;NOM;INDF;SG
machomand	machomand	N;NOM;INDF;SG
englænder	englænders	N;GEN;INDF;SG
paulun	paulunerne	N;NOM;DEF;PL
abdicere	abdiceredes	V;IND;PST;PASS
appelsinskræl	appelsinskræl	N;NOM;INDF;SG
terrasse	terrassernes	N;NOM;DEF;PL
ozelot	ozelot	N;NOM;INDF;SG
svare	svarer	V;IND;PRS;ACT
arne	arner	N;NOM;INDF;PL
sekretariat	sekretariaterne	N;NOM;DEF;PL
skud	skuds	N;GEN;INDF;PL
fodre	fodres	V;IND;PRS;PASS
karotin	karotinets	N;NOM;DEF;SG
addere	adderende	V.PTCP;PRS;ACT
strømstyrke	strømstyrkes	N;GEN;INDF;SG
refraktion	refraktioner	N;NOM;INDF;PL
facade	facade	N;NOM;INDF;SG
lår	lårenes	N;NOM;DEF;PL
svulme	svulmes	V;IND;PRS;PASS
skyllemiddel	skyllemiddel	N;NOM;INDF;SG
flamme	flammens	N;NOM;DEF;SG
tøsedreng	tøsedrengen	N;NOM;DEF;SG
tjørn	tjørnenes	N;NOM;DEF;PL
jødinde	jødindens	N;NOM;DEF;SG
bøhmand	bøhmænds	N;GEN;INDF;PL
nul	nuls	N;GEN;INDF;SG
sudaner	sudanerne	N;NOM;DEF;PL
terrier	terrieren	N;NOM;DEF;SG
samfund	samfund	N;NOM;INDF;SG
bøjle	bøjler	N;NOM;INDF;PL
pagaj	pagajers	N;GEN;INDF;PL
rendezvous	rendezvouserne	N;NOM;DEF;PL
gilding	gildinger	N;NOM;INDF;PL
bøjle	bøjlerne	N;NOM;DEF;PL
apotek	apotekets	N;NOM;DEF;SG
defekt	defekter	N;NOM;INDF;PL
eritreer	eritreere	N;NOM;INDF;PL
kraft	kræfter	N;NOM;INDF;PL
frimærke	frimærker	N;NOM;INDF;PL
ændre	ændr	V;IMP;ACT
grundlag	grundlag	N;NOM;INDF;PL
overbid	overbiddenes	N;NOM;DEF;PL
ordklasse	ordklassens	N;NOM;DEF;SG
stødtand	stødtænder	N;NOM;INDF;PL
galop	galops	N;GEN;INDF;SG
alfabet	alfabeternes	N;NOM;DEF;PL
kardon	kardoner	N;NOM;INDF;PL
tragt	tragten	N;NOM;DEF;SG
bæ	bæer	N;NOM;INDF;PL
betablokker	betablokkerne	N;NOM;DEF;PL
skohorn	skohornene	N;NOM;DEF;PL
byttehandel	byttehandlernes	N;NOM;DEF;PL
jødinde	jødinderne	N;NOM;DEF;PL
kriterium	kriterierne	N;NOM;DEF;PL
laste	lastes	V;IND;PRS;PASS
korrigere	korrigerede	V;IND;PST;ACT
kæle	kælede	V;IND;PST;ACT
frænde	frændes	N;GEN;INDF;SG
guldblomme	guldblommerne	N;NOM;DEF;PL
bro	broers	N;GEN;INDF;PL
aforisme	aforismers	N;GEN;INDF;PL
ekstranet	ekstranettet	N;NOM;DEF;SG
oldemor	oldemor	N;NOM;INDF;SG
svare	svarede	V;IND;PST;ACT
rejecocktail	rejecocktail	N;NOM;INDF;PL
heltal	heltal	N;NOM;INDF;PL
plekter	plektre	N;NOM;INDF;PL
udråbsord	udråbsord	N;NOM;INDF;SG
mavesaft	mavesafterne	N;NOM;DEF;PL
trekant	trekant	N;NOM;INDF;SG
korps	korps'	N;GEN;INDF;PL
markere	markerende	V.PTCP;PRS;ACT
terzet	terzets	N;GEN;INDF;SG
garder	garderens	N;NOM;DEF;SG
rejsebureau	rejsebureauets	N;NOM;DEF;SG
atomkerne	atomkernes	N;GEN;INDF;SG
agnostiker	agnostikerens	N;NOM;DEF;SG
valg	valgs	N;GEN;INDF;SG
vaccine	vacciner	N;NOM;INDF;PL
køkkenvask	køkkenvask	N;NOM;INDF;SG
revisor	revisorerne	N;NOM;DEF;PL
debat	debatters	N;GEN;INDF;PL
metatese	metateses	N;GEN;INDF;SG
sanger	sangerne	N;NOM;DEF;PL
enkemand	enkemand	N;NOM;INDF;SG
søpapegøje	søpapegøjer	N;NOM;INDF;PL
panere	panerer	V;IND;PRS;ACT
sortering	sorteringen	N;NOM;DEF;SG
ydelse	ydelses	N;GEN;INDF;SG
plæneklipper	plæneklipper	N;NOM;INDF;SG
jag	jag	N;NOM;INDF;SG
substantiv	substantiver	N;NOM;INDF;PL
hammer	hammernehamrene	N;NOM;DEF;PL
kardinalitet	kardinaliteternes	N;NOM;DEF;PL
sovs	sovsens	N;NOM;DEF;SG
diplom	diplomets	N;NOM;DEF;SG
søster	søstrene	N;NOM;DEF;PL
quinde	quindernes	N;NOM;DEF;PL
beholder	beholderens	N;NOM;DEF;SG
tv-program	tv-programmet	N;NOM;DEF;SG
entré	entréer	N;NOM;INDF;PL
symfoni	symfoniens	N;NOM;DEF;SG
seng	senge	N;NOM;INDF;PL
quinde	quinden	N;NOM;DEF;SG
lykønske	lykønskes	V;IND;PRS;PASS
længdeforkortelse	længdeforkortelserne	N;NOM;DEF;PL
telefonboks	telefonboksens	N;NOM;DEF;SG
mønster	mønsters	N;GEN;INDF;SG
afasi	afasien	N;NOM;DEF;SG
mulighed	mulighedens	N;NOM;DEF;SG
kaptajn	kaptajnens	N;NOM;DEF;SG
meteorit	meteorits	N;GEN;INDF;SG
altmuligmand	altmuligmænd	N;NOM;INDF;PL
hjertestop	hjertestoppets	N;NOM;DEF;SG
dværg	dværgs	N;GEN;INDF;SG
kjole	kjoles	N;GEN;INDF;SG
ragout	ragoutens	N;NOM;DEF;SG
rokade	rokadens	N;NOM;DEF;SG
fodring	fodringer	N;NOM;INDF;PL
hudfarve	hudfarven	N;NOM;DEF;SG
æbleskive	æbleskivens	N;NOM;DEF;SG
erektion	erektionen	N;NOM;DEF;SG
stigma	stigmatas	N;GEN;INDF;PL
mynde	myndes	N;GEN;INDF;SG
cylinder	cylinderne	N;NOM;DEF;PL
hemmelighed	hemmeligheds	N;GEN;INDF;SG
adamsæble	adamsæble	N;NOM;INDF;SG
negativ	negativ	N;NOM;INDF;SG
afart	afart	N;NOM;INDF;SG
karikartutegning	karikartutegningen	N;NOM;DEF;SG
flag	flags	N;GEN;INDF;PL
chateau	chateauer	N;NOM;INDF;PL
vampyr	vampyrers	N;GEN;INDF;PL
åre	åres	N;GEN;INDF;SG
kaskade	kaskaders	N;GEN;INDF;PL
purere	purere	V;NFIN;ACT
pesticid	pesticids	N;GEN;INDF;SG
chokoladekage	chokoladekagers	N;GEN;INDF;PL
barnløshed	barnløsheds	N;GEN;INDF;SG
annullering	annullering	N;NOM;INDF;SG
flanere	flanerede	V;IND;PST;ACT
insekt	insekter	N;NOM;INDF;PL
skridtbind	skridtbindenes	N;NOM;DEF;PL
nytårsdag	nytårsdagenes	N;NOM;DEF;PL
akkord	akkorders	N;GEN;INDF;PL
fårehund	fårehunden	N;NOM;DEF;SG
størrelse	størrelsens	N;NOM;DEF;SG
gilde	gilderne	N;NOM;DEF;PL
strømpe	strømpernes	N;NOM;DEF;PL
sideordning	sideordning	N;NOM;INDF;SG
ambassadør	ambassadørers	N;GEN;INDF;PL
kongerige	kongeriges	N;GEN;INDF;SG
ubåd	ubådens	N;NOM;DEF;SG
miljø	miljøet	N;NOM;DEF;SG
høst	høsternes	N;NOM;DEF;PL
erobringskrig	erobringskriges	N;GEN;INDF;PL
seneskedehindebetændelse	seneskedehindebetændelses	N;GEN;INDF;SG
kræse	kræser	V;IND;PRS;ACT
gudbarn	gudbørnenes	N;NOM;DEF;PL
stank	stankenes	N;NOM;DEF;PL
bæger	bægerenebægrene	N;NOM;DEF;PL
stør	støres	N;GEN;INDF;PL
globus	globus	N;NOM;INDF;SG
krog	krogens	N;NOM;DEF;SG
laps	lapsenes	N;NOM;DEF;PL
foster	foster	N;NOM;INDF;SG
pensum	pensummets	N;NOM;DEF;SG
pseudonym	pseudonymernes	N;NOM;DEF;PL
arrigtrold	arrigtrold	N;NOM;INDF;SG
tale	tale	N;NOM;INDF;SG
korridor	korridor	N;NOM;INDF;SG
hammer	hammerens	N;NOM;DEF;SG
betegnelse	betegnelsernes	N;NOM;DEF;PL
vaccine	vaccinerne	N;NOM;DEF;PL
skiderik	skiderikkers	N;GEN;INDF;PL
diamant	diamanters	N;GEN;INDF;PL
pynte	pyntes	V;IND;PRS;PASS
kolli	kollis	N;GEN;INDF;PL
tiendedel	tiendedels	N;GEN;INDF;SG
tibetaner	tibetanerne	N;NOM;DEF;PL
chauffør	chauffører	N;NOM;INDF;PL
lian	lianers	N;GEN;INDF;PL
folkehøjskole	folkehøjskoler	N;NOM;INDF;PL
indhøste	indhøstet	V.PTCP;PST;PASS
carbonkredsløb	carbonkredsløbenes	N;NOM;DEF;PL
låg	lågs	N;GEN;INDF;PL
tuberkulose	tuberkulosernes	N;NOM;DEF;PL
sætning	sætninger	N;NOM;INDF;PL
salathoved	salathovedets	N;NOM;DEF;SG
sikring	sikringers	N;GEN;INDF;PL
udvikling	udvikling	N;NOM;INDF;SG
komikerduo	komikerduoens	N;NOM;DEF;SG
platfod	platfod	N;NOM;INDF;SG
kalksten	kalkstenene	N;NOM;DEF;PL
huske	huske	V;NFIN;ACT
husbond	husbondernes	N;NOM;DEF;PL
salut	salutter	N;NOM;INDF;PL
rosévin	rosévinene	N;NOM;DEF;PL
servitrice	servitricens	N;NOM;DEF;SG
harekilling	harekillingens	N;NOM;DEF;SG
parabolantenne	parabolantenner	N;NOM;INDF;PL
kultfilm	kultfilm	N;NOM;INDF;SG
klovn	klovnes	N;GEN;INDF;PL
redskab	redskabet	N;NOM;DEF;SG
lunte	luntes	N;GEN;INDF;SG
brillant	brillanterne	N;NOM;DEF;PL
eksempel	eksemplernes	N;NOM;DEF;PL
beholder	beholderne	N;NOM;DEF;PL
palimpsest	palimpsesternes	N;NOM;DEF;PL
kolli	kolli	N;NOM;INDF;PL
amager	amagerne	N;NOM;DEF;PL
dokument	dokumentet	N;NOM;DEF;SG
seraf	serafers	N;GEN;INDF;PL
ypsilon	ypsiloners	N;GEN;INDF;PL
parkeringsgarage	parkeringsgaragers	N;GEN;INDF;PL
pote	poters	N;GEN;INDF;PL
farao	faraos	N;GEN;INDF;SG
rig	riggens	N;NOM;DEF;SG
atgejr	atgejrerne	N;NOM;DEF;PL
hørfrø	hørfrøenes	N;NOM;DEF;PL
aristokrat	aristokrater	N;NOM;INDF;PL
bølgelængde	bølgelængde	N;NOM;INDF;SG
emne	emner	N;NOM;INDF;PL
vaccine	vaccinernes	N;NOM;DEF;PL
hest	hestes	N;GEN;INDF;PL
tyfon	tyfonens	N;NOM;DEF;SG
jordnøddeolie	jordnøddeoliernes	N;NOM;DEF;PL
rekviem	rekviemmerne	N;NOM;DEF;PL
vinter	vinter	N;NOM;INDF;SG
dyst	dyster	N;NOM;INDF;PL
klassifikation	klassifikationerne	N;NOM;DEF;PL
juble	jublende	V.PTCP;PRS;ACT
rende	renderne	N;NOM;DEF;PL
mynde	mynder	N;NOM;INDF;PL
bussemand	bussemænd	N;NOM;INDF;PL
sok	sokkers	N;GEN;INDF;PL
pornofilm	pornofilmens	N;NOM;DEF;SG
novelle	novellers	N;GEN;INDF;PL
årsdag	årsdagen	N;NOM;DEF;SG
motivere	motiverede	V;IND;PST;ACT
vaskemiddel	vaskemidler	N;NOM;INDF;PL
filosof	filosoffen	N;NOM;DEF;SG
tradition	traditionernes	N;NOM;DEF;PL
reagensglas	reagensglas'	N;GEN;INDF;SG
skildpadde	skildpadde	N;NOM;INDF;SG
hedning	hedningernes	N;NOM;DEF;PL
gnom	gnomen	N;NOM;DEF;SG
musket	musket	N;NOM;INDF;SG
soludbrud	soludbruddenes	N;NOM;DEF;PL
abbedisse	abbedisserne	N;NOM;DEF;PL
glente	glentens	N;NOM;DEF;SG
pokal	pokals	N;GEN;INDF;SG
fipskæg	fipskæg	N;NOM;INDF;SG
kirkeklokke	kirkeklokkers	N;GEN;INDF;PL
mængde	mængderne	N;NOM;DEF;PL
kugle	kuglernes	N;NOM;DEF;PL
kemiker	kemiker	N;NOM;INDF;SG
islom	islommers	N;GEN;INDF;PL
statue	statuernes	N;NOM;DEF;PL
køkkenvask	køkkenvaskes	N;GEN;INDF;PL
hedning	hedninger	N;NOM;INDF;PL
papaja	papajaerne	N;NOM;DEF;PL
flagermus	flagermus	N;NOM;INDF;SG
kontakt	kontakt	N;NOM;INDF;SG
carbonkredsløb	carbonkredsløbene	N;NOM;DEF;PL
stikprøve	stikprøves	N;GEN;INDF;SG
paraply	paraplyen	N;NOM;DEF;SG
donere	donere	V;NFIN;ACT
æra	æraer	N;NOM;INDF;PL
henvendelse	henvendelsernes	N;NOM;DEF;PL
benzinstation	benzinstationens	N;NOM;DEF;SG
computerspilfigur	computerspilfigurens	N;NOM;DEF;SG
aflyd	aflydenes	N;NOM;DEF;PL
kuld	kuldets	N;NOM;DEF;SG
bamseknus	bamseknusets	N;NOM;DEF;SG
bilist	bilisters	N;GEN;INDF;PL
udvikling	udviklingen	N;NOM;DEF;SG
diskotek	diskotekers	N;GEN;INDF;PL
alternativ	alternativ	N;NOM;INDF;SG
dehydrere	dehydreret	V.PTCP;PST;PASS
plage	plager	N;NOM;INDF;PL
bamseknus	bamseknusenes	N;NOM;DEF;PL
ærkeengel	ærkeenglens	N;NOM;DEF;SG
klovn	klovne	N;NOM;INDF;PL
spændingsforskel	spændingsforskellen	N;NOM;DEF;SG
testikel	testiklerne	N;NOM;DEF;PL
cellemembran	cellemembran	N;NOM;INDF;SG
ballet	balletternes	N;NOM;DEF;PL
vaccine	vaccine	N;NOM;INDF;SG
datid	datiden	N;NOM;DEF;SG
kind	kinder	N;NOM;INDF;PL
testamente	testamenter	N;NOM;INDF;PL
system	systemets	N;NOM;DEF;SG
vestkyst	vestkysters	N;GEN;INDF;PL
lønforhøjelse	lønforhøjelsens	N;NOM;DEF;SG
resistor	resistorers	N;GEN;INDF;PL
navnebror	navnebrødrene	N;NOM;DEF;PL
krølle	krølles	N;GEN;INDF;SG
dragt	dragterne	N;NOM;DEF;PL
kæft	kæfternes	N;NOM;DEF;PL
udsagnsord	udsagnsords	N;GEN;INDF;SG
olivenolie	olivenoliernes	N;NOM;DEF;PL
kokosnød	kokosnødder	N;NOM;INDF;PL
triumf	triumf	N;NOM;INDF;SG
hilsen	hilsenen	N;NOM;DEF;SG
positiv	positivers	N;GEN;INDF;PL
hjerte	hjerte	N;NOM;INDF;SG
kustode	kustoden	N;NOM;DEF;SG
balkon	balkons	N;GEN;INDF;SG
plaster	plastrenes	N;NOM;DEF;PL
justere	justerer	V;IND;PRS;ACT
argument	argumentets	N;NOM;DEF;SG
blodåre	blodåres	N;GEN;INDF;SG
visent	visenternes	N;NOM;DEF;PL
agnostiker	agnostikere	N;NOM;INDF;PL
differentialkvotient	differentialkvotient	N;NOM;INDF;SG
apparat	apparater	N;NOM;INDF;PL
surhedsregulator	surhedsregulatorens	N;NOM;DEF;SG
akt	akterne	N;NOM;DEF;PL
længdebølge	længdebølgers	N;GEN;INDF;PL
weekend	weekendernes	N;NOM;DEF;PL
ært	ærter	N;NOM;INDF;PL
globus	globussernes	N;NOM;DEF;PL
middel	midletmiddelet	N;NOM;DEF;SG
puslespil	puslespils	N;GEN;INDF;SG
vitamin	vitaminers	N;GEN;INDF;PL
solsikke	solsikkers	N;GEN;INDF;PL
genstandsled	genstandsled	N;NOM;INDF;PL
filosof	filosof	N;NOM;INDF;SG
sadel	sadlens	N;NOM;DEF;SG
globus	globus'	N;GEN;INDF;SG
kubikmeter	kubikmeter	N;NOM;INDF;SG
mund	mund	N;NOM;INDF;SG
stør	størene	N;NOM;DEF;PL
indbygger	indbyggere	N;NOM;INDF;PL
selskab	selskaberne	N;NOM;DEF;PL
hjord	hjordens	N;NOM;DEF;SG
vejr	vejrene	N;NOM;DEF;PL
dæmpe	dæmpes	V;IND;PRS;PASS
kål	kål	N;NOM;INDF;SG
sekant	sekants	N;GEN;INDF;SG
isbryder	isbryderene	N;NOM;DEF;PL
strømpe	strømpes	N;GEN;INDF;SG
kobberrør	kobberrør	N;NOM;INDF;PL
formiddag	formiddagene	N;NOM;DEF;PL
kastanje	kastanjens	N;NOM;DEF;SG
afprøvning	afprøvningens	N;NOM;DEF;SG
mutagen	mutagener	N;NOM;INDF;PL
fersken	ferskeners	N;GEN;INDF;PL
fodboldspiller	fodboldspillere	N;NOM;INDF;PL
afart	afarternes	N;NOM;DEF;PL
dans	dans	N;NOM;INDF;SG
ror	roret	N;NOM;DEF;SG
tunika	tunika	N;NOM;INDF;SG
pantebrev	pantebrev	N;NOM;INDF;SG
stofmængde	stofmængders	N;GEN;INDF;PL
islænder	islænderens	N;NOM;DEF;SG
skib	skibets	N;NOM;DEF;SG
kardiogram	kardiogram	N;NOM;INDF;SG
svigte	svigte	V;NFIN;ACT
hjemmeside	hjemmesider	N;NOM;INDF;PL
årti	årtiers	N;GEN;INDF;PL
henvendelse	henvendelse	N;NOM;INDF;SG
dynasti	dynastiernes	N;NOM;DEF;PL
stør	størens	N;NOM;DEF;SG
fætter	fætres	N;GEN;INDF;PL
julegave	julegaverne	N;NOM;DEF;PL
neutrum	neutrummets	N;NOM;DEF;SG
kvadrat	kvadraters	N;GEN;INDF;PL
biobrændsel	biobrændslet	N;NOM;DEF;SG
avokado	avokados	N;GEN;INDF;SG
ungarer	ungarernes	N;NOM;DEF;PL
proton	protonerne	N;NOM;DEF;PL
foreningsmængde	foreningsmængders	N;GEN;INDF;PL
tidsrejse	tidsrejses	N;GEN;INDF;SG
hjerte	hjerter	N;NOM;INDF;PL
arkiv	arkivet	N;NOM;DEF;SG
sandkasse	sandkasse	N;NOM;INDF;SG
æbleskive	æbleskivers	N;GEN;INDF;PL
aristokrat	aristokratens	N;NOM;DEF;SG
maddike	maddiker	N;NOM;INDF;PL
maksime	maksimer	N;NOM;INDF;PL
present	present	N;NOM;INDF;SG
klitoris	klitorisser	N;NOM;INDF;PL
frihed	frihed	N;NOM;INDF;SG
undskyldning	undskyldningerne	N;NOM;DEF;PL
salathoved	salathovedernes	N;NOM;DEF;PL
hø	hø	N;NOM;INDF;PL
spatel	spatels	N;GEN;INDF;SG
meteorit	meteorit	N;NOM;INDF;SG
pib	pibs	N;GEN;INDF;SG
kulturrevolution	kulturrevolutionens	N;NOM;DEF;SG
ugedag	ugedags	N;GEN;INDF;SG
øjelåg	øjelåget	N;NOM;DEF;SG
malle	malles	N;GEN;INDF;SG
vinkelhalveringslinje	vinkelhalveringslinjer	N;NOM;INDF;PL
stat	staterne	N;NOM;DEF;PL
brune	brunende	V.PTCP;PRS;ACT
canadier	canadiernes	N;NOM;DEF;PL
fagforening	fagforening	N;NOM;INDF;SG
storhed	storhed	N;NOM;INDF;SG
hustru	hustruernes	N;NOM;DEF;PL
gymnasium	gymnasiet	N;NOM;DEF;SG
substans	substansen	N;NOM;DEF;SG
udskud	udskud	N;NOM;INDF;SG
vabel	vablers	N;GEN;INDF;PL
sadel	sadlernes	N;NOM;DEF;PL
myre	myren	N;NOM;DEF;SG
symfoni	symfonier	N;NOM;INDF;PL
hvil	hvil	N;NOM;INDF;SG
tanke	tanke	N;NOM;INDF;SG
folkedragt	folkedragter	N;NOM;INDF;PL
citron	citroners	N;GEN;INDF;PL
udsagnsord	udsagnsordets	N;NOM;DEF;SG
tiendedel	tiendedele	N;NOM;INDF;PL
vagt	vagts	N;GEN;INDF;SG
herbivor	herbivorers	N;GEN;INDF;PL
smørelse	smørelses	N;GEN;INDF;SG
halvø	halvøen	N;NOM;DEF;SG
univers	univers	N;NOM;INDF;SG
hjertestop	hjertestoppenes	N;NOM;DEF;PL
bolværk	bolværks	N;GEN;INDF;SG
ærinde	ærindes	N;GEN;INDF;SG
aramæer	aramæeren	N;NOM;DEF;SG
ulykke	ulykkernes	N;NOM;DEF;PL
afholdsmand	afholdsmands	N;GEN;INDF;SG
parkeringsgarage	parkeringsgarager	N;NOM;INDF;PL
smørrebrød	smørrebrødet	N;NOM;DEF;SG
horehus	horehus'	N;GEN;INDF;SG
kjove	kjovens	N;NOM;DEF;SG
snefald	snefaldenes	N;NOM;DEF;PL
struds	strudsenes	N;NOM;DEF;PL
brandbil	brandbilens	N;NOM;DEF;SG
drøbel	drøblers	N;GEN;INDF;PL
syllogisme	syllogisme	N;NOM;INDF;SG
maddike	maddikens	N;NOM;DEF;SG
fluepapir	fluepapirerne	N;NOM;DEF;PL
guirlande	guirlandens	N;NOM;DEF;SG
huskarl	huskarlens	N;NOM;DEF;SG
alting	alting	N;NOM;INDF;PL
cellemembran	cellemembranen	N;NOM;DEF;SG
roman	romaner	N;NOM;INDF;PL
luftkastel	luftkastels	N;GEN;INDF;SG
agerhøne	agerhønens	N;NOM;DEF;SG
trafiklys	trafiklyset	N;NOM;DEF;SG
leverpostej	leverpostejers	N;GEN;INDF;PL
fertilitetsrate	fertilitetsrater	N;NOM;INDF;PL
miste	mister	V;IND;PRS;ACT
fordanskning	fordanskningens	N;NOM;DEF;SG
morder	morderes	N;GEN;INDF;PL
ankre	ankre	V;NFIN;ACT
røgelse	røgelses	N;GEN;INDF;SG
partikel	partiklens	N;NOM;DEF;SG
grindehval	grindehvalene	N;NOM;DEF;PL
fremlejer	fremlejernes	N;NOM;DEF;PL
feber	feberen	N;NOM;DEF;SG
strop	stropperne	N;NOM;DEF;PL
jorde	jordet	V.PTCP;PST;PASS
vandringsmand	vandringsmandens	N;NOM;DEF;SG
port	portene	N;NOM;DEF;PL
immigration	immigrationerne	N;NOM;DEF;PL
orne	ornernes	N;NOM;DEF;PL
hyppighed	hyppighedens	N;NOM;DEF;SG
dansker	danskeren	N;NOM;DEF;SG
giftstof	giftstoffer	N;NOM;INDF;PL
abbedisse	abbedisse	N;NOM;INDF;SG
eddike	eddikers	N;GEN;INDF;PL
brøk	brøkernes	N;NOM;DEF;PL
kerne	kernes	N;GEN;INDF;SG
særskrivning	særskrivning	N;NOM;INDF;SG
betydning	betydningen	N;NOM;DEF;SG
kovs	kovs'	N;GEN;INDF;SG
mangel	manglen	N;NOM;DEF;SG
vise	vise	N;NOM;INDF;SG
brusk	brusken	N;NOM;DEF;SG
kaffebønne	kaffebønner	N;NOM;INDF;PL
eksempel	eksemplets	N;NOM;DEF;SG
narhval	narhval	N;NOM;INDF;SG
vabel	vablenvabelen	N;NOM;DEF;SG
mannequin	mannequins	N;GEN;INDF;SG
fyrfadslys	fyrfadslysets	N;NOM;DEF;SG
bevægelse	bevægelses	N;GEN;INDF;SG
styr	styrs	N;GEN;INDF;PL
svip	svippene	N;NOM;DEF;PL
milt	milte	N;NOM;INDF;PL
debat	debatten	N;NOM;DEF;SG
hvil	hvilet	N;NOM;DEF;SG
guvernørpost	guvernørposters	N;GEN;INDF;PL
smørelse	smørelse	N;NOM;INDF;SG
orgie	orgier	N;NOM;INDF;PL
kardiogram	kardiograms	N;GEN;INDF;SG
sesamolie	sesamolie	N;NOM;INDF;SG
humanist	humanisten	N;NOM;DEF;SG
gulv	gulvets	N;NOM;DEF;SG
kopi	kopien	N;NOM;DEF;SG
brosten	brostens	N;GEN;INDF;SG
genstand	genstandene	N;NOM;DEF;PL
giftstof	giftstofs	N;GEN;INDF;SG
musket	musketten	N;NOM;DEF;SG
vandbakkelse	vandbakkelsens	N;NOM;DEF;SG
sovs	sovse	N;NOM;INDF;PL
låg	lågets	N;NOM;DEF;SG
porre	porre	N;NOM;INDF;SG
kvotientrække	kvotientrækken	N;NOM;DEF;SG
ambolt	amboltenes	N;NOM;DEF;PL
spor	spors	N;GEN;INDF;SG
aboriginer	aborigineres	N;GEN;INDF;PL
cigaretsælger	cigaretsælgeres	N;GEN;INDF;PL
adamsæble	adamsæblerne	N;NOM;DEF;PL
badmintonspiller	badmintonspiller	N;NOM;INDF;SG
vable	vable	N;NOM;INDF;SG
veninde	veninden	N;NOM;DEF;SG
mindretalsregering	mindretalsregeringens	N;NOM;DEF;SG
orientering	orienterings	N;GEN;INDF;SG
cigaretskod	cigaretskods	N;GEN;INDF;PL
park	parkernes	N;NOM;DEF;PL
mandebøde	mandebøder	N;NOM;INDF;PL
bønne	bønners	N;GEN;INDF;PL
slagsmål	slagsmålenes	N;NOM;DEF;PL
kaptajn	kaptajns	N;GEN;INDF;SG
fiskerbåd	fiskerbåde	N;NOM;INDF;PL
søpapegøje	søpapegøjes	N;GEN;INDF;SG
vejr	vejrets	N;NOM;DEF;SG
sorteringsmaskine	sorteringsmaskiner	N;NOM;INDF;PL
solvind	solvindes	N;GEN;INDF;PL
syrer	syreres	N;GEN;INDF;PL
burgerbar	burgerbaren	N;NOM;DEF;SG
fremlejer	fremlejerens	N;NOM;DEF;SG
frihed	friheds	N;GEN;INDF;SG
vampyr	vampyrs	N;GEN;INDF;SG
mayonnaise	mayonnaisen	N;NOM;DEF;SG
tur	turen	N;NOM;DEF;SG
interjektion	interjektion	N;NOM;INDF;SG
piberi	piberiers	N;GEN;INDF;PL
differentialkvotient	differentialkvotienters	N;GEN;INDF;PL
arving	arvingerne	N;NOM;DEF;PL
fællesbetegnelse	fællesbetegnelsen	N;NOM;DEF;SG
fyrfadslys	fyrfadslys	N;NOM;INDF;SG
start	starters	N;GEN;INDF;PL
krabbe	krabbens	N;NOM;DEF;SG
behov	behovs	N;GEN;INDF;PL
syllogisme	syllogismernes	N;NOM;DEF;PL
pors	porsene	N;NOM;DEF;PL
hyæne	hyænes	N;GEN;INDF;SG
tandpasta	tandpastaer	N;NOM;INDF;PL
bankkonto	bankkontoen	N;NOM;DEF;SG
rensdyr	rensdyr	N;NOM;INDF;SG
resume	resumeer	N;NOM;INDF;PL
svip	svippet	N;NOM;DEF;SG
krop	kroppene	N;NOM;DEF;PL
tv-serie	tv-serie	N;NOM;INDF;SG
heliotrop	heliotropers	N;GEN;INDF;PL
tegn	tegn	N;NOM;INDF;PL
krabbe	krabbe	N;NOM;INDF;SG
gudshus	gudshus	N;NOM;INDF;SG
sulfat	sulfaters	N;GEN;INDF;PL
hypnotisere	hypnotiserer	V;IND;PRS;ACT
bryllup	brylluppernes	N;NOM;DEF;PL
navne	navnen	N;NOM;DEF;SG
meteorit	meteoritters	N;GEN;INDF;PL
skandale	skandalerne	N;NOM;DEF;PL
gymnasium	gymnasiers	N;GEN;INDF;PL
kandidat	kandidat	N;NOM;INDF;SG
musikgenre	musikgenrerne	N;NOM;DEF;PL
selskab	selskabets	N;NOM;DEF;SG
tegnefilm	tegnefilmenes	N;NOM;DEF;PL
frømand	frømændene	N;NOM;DEF;PL
mål	målenes	N;NOM;DEF;PL
fiskerbåd	fiskerbådens	N;NOM;DEF;SG
gamer	gameres	N;GEN;INDF;PL
rov	rovs	N;GEN;INDF;PL
ordkløver	ordkløveren	N;NOM;DEF;SG
avis	avisens	N;NOM;DEF;SG
enke	enkernes	N;NOM;DEF;PL
guvernørpost	guvernørpost	N;NOM;INDF;SG
vitaminpille	vitaminpillernes	N;NOM;DEF;PL
stad	stædernes	N;NOM;DEF;PL
nøgleord	nøgleord	N;NOM;INDF;PL
fægtning	fægtnings	N;GEN;INDF;SG
lillehjerne	lillehjernes	N;GEN;INDF;SG
abkhaser	abkhasernes	N;NOM;DEF;PL
fætter	fætteren	N;NOM;DEF;SG
brise	brisers	N;GEN;INDF;PL
massøse	massøsernes	N;NOM;DEF;PL
udvikling	udviklings	N;GEN;INDF;SG
værdi	værdiernes	N;NOM;DEF;PL
skabelon	skabelonerne	N;NOM;DEF;PL
islænder	islænderen	N;NOM;DEF;SG
bersærk	bersærkers	N;GEN;INDF;PL
middel	middel	N;NOM;INDF;SG
vektorprodukt	vektorproduktet	N;NOM;DEF;SG
golfbold	golfboldenes	N;NOM;DEF;PL
surhedsregulator	surhedsregulatorerne	N;NOM;DEF;PL
strømpe	strømpers	N;GEN;INDF;PL
golden retriever	golden retrieverne	N;NOM;DEF;PL
hjelm	hjelms	N;GEN;INDF;SG
erklære	erklæredes	V;IND;PST;PASS
polyeder	polyederet	N;NOM;DEF;SG
mund	munds	N;GEN;INDF;SG
trumf	trumf	N;NOM;INDF;SG
delmængde	delmængderne	N;NOM;DEF;PL
kaskade	kaskades	N;GEN;INDF;SG
sav	saven	N;NOM;DEF;SG
harmonika	harmonikas	N;GEN;INDF;SG
lad	lad	N;NOM;INDF;SG
testamente	testamenterne	N;NOM;DEF;PL
oxidere	oxiderede	V;IND;PST;ACT
henvisning	henvisningers	N;GEN;INDF;PL
annullation	annullation	N;NOM;INDF;SG
beryl	beryls	N;GEN;INDF;SG
grundled	grundleddenes	N;NOM;DEF;PL
spatel	spatlerne	N;NOM;DEF;PL
anarki	anarki	N;NOM;INDF;SG
bøf	bøffens	N;NOM;DEF;SG
køb	køb	N;NOM;INDF;PL
velsigne	velsignede	V;IND;PST;ACT
emir	emir	N;NOM;INDF;SG
rambuk	rambukkene	N;NOM;DEF;PL
trin	trin	N;NOM;INDF;SG
schweizer	schweizerens	N;NOM;DEF;SG
mistelten	misteltens	N;GEN;INDF;SG
profeti	profetierne	N;NOM;DEF;PL
sydafrikaner	sydafrikanernes	N;NOM;DEF;PL
bøf	bøffers	N;GEN;INDF;PL
flanør	flanørernes	N;NOM;DEF;PL
æblekerne	æblekerner	N;NOM;INDF;PL
madding	maddinger	N;NOM;INDF;PL
skiderik	skiderikken	N;NOM;DEF;SG
metatese	metateserne	N;NOM;DEF;PL
fugleskræmsel	fugleskræmslers	N;GEN;INDF;PL
rekord	rekorden	N;NOM;DEF;SG
afvigelse	afvigelsen	N;NOM;DEF;SG
mesanmast	mesanmastens	N;NOM;DEF;SG
månefase	månefasernes	N;NOM;DEF;PL
lunde	lundens	N;NOM;DEF;SG
kultfilm	kultfilmens	N;NOM;DEF;SG
fluepapir	fluepapirers	N;GEN;INDF;PL
kommune	kommunes	N;GEN;INDF;SG
fyrfadslys	fyrfadslyset	N;NOM;DEF;SG
kvast	kvasternes	N;NOM;DEF;PL
tusind	tusinders	N;GEN;INDF;PL
terapeut	terapeuternes	N;NOM;DEF;PL
landkrabbe	landkrabbers	N;GEN;INDF;PL
strubehoved	strubehoveds	N;GEN;INDF;SG
resurse	resurse	N;NOM;INDF;SG
henvisning	henvisningernes	N;NOM;DEF;PL
far	fædrene	N;NOM;DEF;PL
vejr	vejr	N;NOM;INDF;SG
udvikler	udviklerenes	N;NOM;DEF;PL
metatese	metatesernes	N;NOM;DEF;PL
succes	succesen	N;NOM;DEF;SG
middel	midler	N;NOM;INDF;PL
laps	lapsene	N;NOM;DEF;PL
talje	taljen	N;NOM;DEF;SG
vod	voddet	N;NOM;DEF;SG
frokost	frokost	N;NOM;INDF;SG
hvil	hvilets	N;NOM;DEF;SG
trafiklys	trafiklysers	N;GEN;INDF;PL
modulation	modulationen	N;NOM;DEF;SG
liv	liv	N;NOM;INDF;PL
ugedag	ugedagen	N;NOM;DEF;SG
kamel	kamelen	N;NOM;DEF;SG
bøg	bøgernes	N;NOM;DEF;PL
åre	årers	N;GEN;INDF;PL
afprøvning	afprøvningen	N;NOM;DEF;SG
lystre	lystredes	V;IND;PST;PASS
mønster	mønster	N;NOM;INDF;SG
liv	livets	N;NOM;DEF;SG
bydel	bydelene	N;NOM;DEF;PL
brunette	brunetternes	N;NOM;DEF;PL
mandola	mandolaer	N;NOM;INDF;PL
hydrat	hydratet	N;NOM;DEF;SG
reparere	reparerer	V;IND;PRS;ACT
vandbakkelse	vandbakkelserne	N;NOM;DEF;PL
sulfat	sulfatets	N;NOM;DEF;SG
parfume	parfumer	N;NOM;INDF;PL
arkiv	arkivers	N;GEN;INDF;PL
navne	navnerne	N;NOM;DEF;PL
skulder	skuldres	N;GEN;INDF;PL
lian	lianens	N;NOM;DEF;SG
brise	brisen	N;NOM;DEF;SG
dialekt	dialekterne	N;NOM;DEF;PL
begravelse	begravelse	N;NOM;INDF;SG
malkepige	malkepiger	N;NOM;INDF;PL
perker	perkers	N;GEN;INDF;SG
tøj	tøjerne	N;NOM;DEF;PL
strygejern	strygejerns	N;GEN;INDF;SG
flange	flange	N;NOM;INDF;SG
metatese	metatesers	N;GEN;INDF;PL
gestus	gestus'	N;GEN;INDF;PL
værtinde	værtinden	N;NOM;DEF;SG
spilkarakter	spilkarakterers	N;GEN;INDF;PL
landskab	landskabers	N;GEN;INDF;PL
tobak	tobaks	N;GEN;INDF;SG
fordøje	fordøjet	V.PTCP;PST;PASS
svin	svinet	N;NOM;DEF;SG
hængelås	hængelås	N;NOM;INDF;SG
ordbog	ordbøgers	N;GEN;INDF;PL
ballet	ballettens	N;NOM;DEF;SG
passager	passagerens	N;NOM;DEF;SG
ran	ranets	N;NOM;DEF;SG
afsked	afskeder	N;NOM;INDF;PL
altan	altanens	N;NOM;DEF;SG
massefylde	massefylderne	N;NOM;DEF;PL
spektakel	spektakel	N;NOM;INDF;SG
jomfru	jomfruerne	N;NOM;DEF;PL
nervecelle	nervecellernes	N;NOM;DEF;PL
blok	blokkes	N;GEN;INDF;PL
spindelvæv	spindelvævenes	N;NOM;DEF;PL
haj	hajens	N;NOM;DEF;SG
stød	stødets	N;NOM;DEF;SG
karamel	karamellers	N;GEN;INDF;PL
hvalp	hvalpen	N;NOM;DEF;SG
bassin	bassin	N;NOM;INDF;SG
topograf	topografer	N;NOM;INDF;PL
kasse	kasses	N;GEN;INDF;SG
spøgelse	spøgelses	N;GEN;INDF;SG
galleri	galleriers	N;GEN;INDF;PL
spændingsforskel	spændingsforskellene	N;NOM;DEF;PL
tøj	tøjet	N;NOM;DEF;SG
remulade	remulade	N;NOM;INDF;SG
system	systemers	N;GEN;INDF;PL
skrin	skrin	N;NOM;INDF;SG
ankre	ankrer	V;IND;PRS;ACT
kaktus	kaktussen	N;NOM;DEF;SG
parkeringsgarage	parkeringsgarage	N;NOM;INDF;SG
suffiks	suffikset	N;NOM;DEF;SG
enhed	enheders	N;GEN;INDF;PL
dobbeltseng	dobbeltsenge	N;NOM;INDF;PL
bæskubber	bæskubberne	N;NOM;DEF;PL
puffer	pufferenes	N;NOM;DEF;PL
engel	englene	N;NOM;DEF;PL
atomkerne	atomkerne	N;NOM;INDF;SG
dannebrog	dannebrogenes	N;NOM;DEF;PL
elkedel	elkedel	N;NOM;INDF;SG
landsbytosse	landsbytosserne	N;NOM;DEF;PL
pronomen	pronomenets	N;NOM;DEF;SG
salatfad	salatfades	N;GEN;INDF;PL
horoskop	horoskoper	N;NOM;INDF;PL
servitrice	servitricerne	N;NOM;DEF;PL
vise	visers	N;GEN;INDF;PL
globus	globusser	N;NOM;INDF;PL
filosof	filosofferne	N;NOM;DEF;PL
nyre	nyrers	N;GEN;INDF;PL
smiley	smileyen	N;NOM;DEF;SG
øjelåg	øjelågets	N;NOM;DEF;SG
skridtbind	skridtbindene	N;NOM;DEF;PL
vase	vasen	N;NOM;DEF;SG
majonæse	majonæses	N;GEN;INDF;SG
omvej	omvejs	N;GEN;INDF;SG
krebs	krebsens	N;NOM;DEF;SG
lus	lusen	N;NOM;DEF;SG
biologi	biologien	N;NOM;DEF;SG
babyble	babyble	N;NOM;INDF;SG
sjal	sjaler	N;NOM;INDF;PL
kaffekande	kaffekanderne	N;NOM;DEF;PL
gulv	gulvenes	N;NOM;DEF;PL
kentaur	kentaurens	N;NOM;DEF;SG
politibetjent	politibetjentene	N;NOM;DEF;PL
erklære	erklærende	V.PTCP;PRS;ACT
aminosyre	aminosyrens	N;NOM;DEF;SG
burgerbar	burgerbars	N;GEN;INDF;SG
julekort	julekortenes	N;NOM;DEF;PL
lilje	liljens	N;NOM;DEF;SG
viske	visker	V;IND;PRS;ACT
affaldsstof	affaldsstoffernes	N;NOM;DEF;PL
måge	mågens	N;NOM;DEF;SG
abbedisse	abbedissen	N;NOM;DEF;SG
etymologi	etymologierne	N;NOM;DEF;PL
tidspunkt	tidspunkter	N;NOM;INDF;PL
udgift	udgifterne	N;NOM;DEF;PL
arbejdsdag	arbejdsdagenes	N;NOM;DEF;PL
ambassadør	ambassadørerne	N;NOM;DEF;PL
benzinstation	benzinstationen	N;NOM;DEF;SG
bål	bål	N;NOM;INDF;SG
tur	ture	N;NOM;INDF;PL
cellekerne	cellekerner	N;NOM;INDF;PL
kommissær	kommissærens	N;NOM;DEF;SG
diplomat	diplomaternes	N;NOM;DEF;PL
grønlænder	grønlændernes	N;NOM;DEF;PL
afvigelse	afvigelserne	N;NOM;DEF;PL
afløb	afløbet	N;NOM;DEF;SG
nyre	nyrernes	N;NOM;DEF;PL
bøjning	bøjningens	N;NOM;DEF;SG
verballed	verballeddenes	N;NOM;DEF;PL
sæbe	sæberne	N;NOM;DEF;PL
flage	flagens	N;NOM;DEF;SG
fordøje	fordøjedes	V;IND;PST;PASS
afasi	afasi	N;NOM;INDF;SG
metode	metoders	N;GEN;INDF;PL
bæskubber	bæskubberenes	N;NOM;DEF;PL
encyklopædi	encyklopædiens	N;NOM;DEF;SG
hexaeder	hexaeder	N;NOM;INDF;SG
periode	perioderne	N;NOM;DEF;PL
måde	måders	N;GEN;INDF;PL
medgift	medgifternes	N;NOM;DEF;PL
bilvask	bilvasken	N;NOM;DEF;SG
indadvendthed	indadvendtheders	N;GEN;INDF;PL
babyfløjl	babyfløjl	N;NOM;INDF;SG
manuskript	manuskriptets	N;NOM;DEF;SG
bølgefunktion	bølgefunktionens	N;NOM;DEF;SG
herbicid	herbiciderne	N;NOM;DEF;PL
donere	doneres	V;IND;PRS;PASS
manke	mankes	N;GEN;INDF;SG
kartoffel	kartoflens	N;NOM;DEF;SG
veteran	veteraners	N;GEN;INDF;PL
karaffel	karafler	N;NOM;INDF;PL
hexaeder	hexaedrene	N;NOM;DEF;PL
medium	mediernes	N;NOM;DEF;PL
partikel	partikler	N;NOM;INDF;PL
karpe	karper	N;NOM;INDF;PL
trone	tronen	N;NOM;DEF;SG
nyre	nyrer	N;NOM;INDF;PL
chokolade	chokolader	N;NOM;INDF;PL
art	artens	N;NOM;DEF;SG
konvoj	konvojen	N;NOM;DEF;SG
hyæne	hyæners	N;GEN;INDF;PL
dyne	dyne	N;NOM;INDF;SG
fællesbetegnelse	fællesbetegnelsens	N;NOM;DEF;SG
konflikt	konflikten	N;NOM;DEF;SG
hest	heste	N;NOM;INDF;PL
belaste	belastes	V;IND;PRS;PASS
cigar	cigarerne	N;NOM;DEF;PL
marmelade	marmeladerne	N;NOM;DEF;PL
taske	tasken	N;NOM;DEF;SG
gyngestol	gyngestolene	N;NOM;DEF;PL
smykke	smykker	N;NOM;INDF;PL
brystvorte	brystvorten	N;NOM;DEF;SG
ornitolog	ornitologs	N;GEN;INDF;SG
botanik	botanikkens	N;NOM;DEF;SG
kalejdoskop	kalejdoskops	N;GEN;INDF;SG
fluesmækker	fluesmækkeren	N;NOM;DEF;SG
soldug	solduggen	N;NOM;DEF;SG
kalejdoskop	kalejdoskop	N;NOM;INDF;SG
langfredag	langfredagens	N;NOM;DEF;SG
bighornfår	bighornfår	N;NOM;INDF;PL
betegnelse	betegnelsens	N;NOM;DEF;SG
længdebølge	længdebølgernes	N;NOM;DEF;PL
fjæs	fjæs'	N;GEN;INDF;SG
grotte	grottens	N;NOM;DEF;SG
faktum	faktummet	N;NOM;DEF;SG
karl	karlen	N;NOM;DEF;SG
elskerinde	elskerinde	N;NOM;INDF;SG
vølve	vølvers	N;GEN;INDF;PL
barnebarn	barne	N;NOM;DEF;SG
slutspurt	slutspurten	N;NOM;DEF;SG
bygning	bygnings	N;GEN;INDF;SG
kerne	kerne	N;NOM;INDF;SG
bøjning	bøjnings	N;GEN;INDF;SG
bønne	bønne	N;NOM;INDF;SG
cirkeludsnit	cirkeludsnittenes	N;NOM;DEF;PL
numismatiker	numismatikeres	N;GEN;INDF;PL
dæmpe	dæmper	V;IND;PRS;ACT
trin	trinet	N;NOM;DEF;SG
ror	rorenes	N;NOM;DEF;PL
dæmpe	dæmpet	V.PTCP;PST;PASS
prins	prinser	N;NOM;INDF;PL
butterfly	butterflyens	N;NOM;DEF;SG
giftstof	giftstoffernes	N;NOM;DEF;PL
kniv	knives	N;GEN;INDF;PL
hjernestamme	hjernestammernes	N;NOM;DEF;PL
bold	boldes	N;GEN;INDF;PL
tus	tussens	N;NOM;DEF;SG
violinist	violinister	N;NOM;INDF;PL
midnat	midnats	N;GEN;INDF;SG
mellemmand	mellemmændenes	N;NOM;DEF;PL
størrelse	størrelsernes	N;NOM;DEF;PL
handicaptoilet	handicaptoiletter	N;NOM;INDF;PL
artikel	artikler	N;NOM;INDF;PL
farmaceut	farmaceuts	N;GEN;INDF;SG
strømpe	strømpen	N;NOM;DEF;SG
surhedsregulator	surhedsregulatorers	N;GEN;INDF;PL
prins	prins'	N;GEN;INDF;SG
refræn	refræners	N;GEN;INDF;PL
halvmåne	halvmåne	N;NOM;INDF;SG
elske	elskedes	V;IND;PST;PASS
vogn	vogns	N;GEN;INDF;SG
dyse	dyses	N;GEN;INDF;SG
afholdsmand	afholdsmænds	N;GEN;INDF;PL
vandrehistorie	vandrehistorien	N;NOM;DEF;SG
telefon	telefoners	N;GEN;INDF;PL
viske	viskes	V;IND;PRS;PASS
tumult	tumulten	N;NOM;DEF;SG
karpe	karpers	N;GEN;INDF;PL
panda	pandas	N;GEN;INDF;SG
strop	strops	N;GEN;INDF;SG
hind	hind	N;NOM;INDF;SG
aflevering	afleveringerne	N;NOM;DEF;PL
TV-serie	TV-series	N;GEN;INDF;SG
synliggørelse	synliggørelses	N;GEN;INDF;SG
vejr	vejret	N;NOM;DEF;SG
stormfugl	stormfuglens	N;NOM;DEF;SG
spidsborger	spidsborgernes	N;NOM;DEF;PL
karisma	karismaernes	N;NOM;DEF;PL
chauffør	chaufførers	N;GEN;INDF;PL
ærinde	ærindets	N;NOM;DEF;SG
kovs	kovsens	N;NOM;DEF;SG
rekord	rekordens	N;NOM;DEF;SG
surhedsregulator	surhedsregulatorernes	N;NOM;DEF;PL
princip	principperne	N;NOM;DEF;PL
trubadour	trubadour	N;NOM;INDF;SG
bryllup	bryllups	N;GEN;INDF;SG
klaver	klaverer	N;NOM;INDF;PL
guirlande	guirlanderne	N;NOM;DEF;PL
brugerbidrag	brugerbidrag	N;NOM;INDF;PL
kølsvin	kølsvinet	N;NOM;DEF;SG
spørgsmål	spørgsmålet	N;NOM;DEF;SG
klitoris	klitorissernes	N;NOM;DEF;PL
garder	garderen	N;NOM;DEF;SG
kongerige	kongerigernes	N;NOM;DEF;PL
brise	brise	N;NOM;INDF;SG
julegave	julegavernes	N;NOM;DEF;PL
batteri	batteriers	N;GEN;INDF;PL
batteri	batterierne	N;NOM;DEF;PL
hornhinde	hornhindens	N;NOM;DEF;SG
morgenfrue	morgenfruernes	N;NOM;DEF;PL
karpe	karpes	N;GEN;INDF;SG
proscenium	proscenium	N;NOM;INDF;SG
vable	vablernes	N;NOM;DEF;PL
bagslag	bagslags	N;GEN;INDF;SG
bilvask	bilvaskene	N;NOM;DEF;PL
chokolade	chokoladen	N;NOM;DEF;SG
quarterback	quarterbacker	N;NOM;INDF;PL
skridtbind	skridtbinds	N;GEN;INDF;SG
quinde	quinde	N;NOM;INDF;SG
verballed	verballed	N;NOM;INDF;PL
testikel	testikels	N;GEN;INDF;SG
skrig	skrigs	N;GEN;INDF;PL
manke	manker	N;NOM;INDF;PL
vandringsmand	vandringsmænds	N;GEN;INDF;PL
interesse	interessers	N;GEN;INDF;PL
testamente	testamenternes	N;NOM;DEF;PL
kvadratmeter	kvadratmeterne	N;NOM;DEF;PL
filial	filialens	N;NOM;DEF;SG
elskerinde	elskerindernes	N;NOM;DEF;PL
kalksten	kalksten	N;NOM;INDF;PL
film	filmen	N;NOM;DEF;SG
succes	succeserne	N;NOM;DEF;PL
dominoeffekt	dominoeffekten	N;NOM;DEF;SG
resistivitet	resistivitetens	N;NOM;DEF;SG
udgang	udgang	N;NOM;INDF;SG
skræddermester	skræddermesteren	N;NOM;DEF;SG
kreds	kredsen	N;NOM;DEF;SG
barnløshed	barnløshedens	N;NOM;DEF;SG
kop	kopperne	N;NOM;DEF;PL
massør	massør	N;NOM;INDF;SG
gryn	grynene	N;NOM;DEF;PL
kæphest	kæphestens	N;NOM;DEF;SG
teknik	teknikkernes	N;NOM;DEF;PL
øjelåg	øjelågene	N;NOM;DEF;PL
mandola	mandolaens	N;NOM;DEF;SG
flagermus	flagermusens	N;NOM;DEF;SG
reparere	reparer	V;IMP;ACT
malle	malle	N;NOM;INDF;SG
krave	kraven	N;NOM;DEF;SG
avenue	avenues	N;GEN;INDF;SG
synliggørelse	synliggørelsernes	N;NOM;DEF;PL
finte	finterne	N;NOM;DEF;PL
tusinde	tusindets	N;NOM;DEF;SG
mord	mords	N;GEN;INDF;SG
autofokus	autofokusser	N;NOM;INDF;PL
midnat	midnætternes	N;NOM;DEF;PL
skulder	skuldre	N;NOM;INDF;PL
drej	drej	N;NOM;INDF;SG
motorcykel	motorcyklens	N;NOM;DEF;SG
verbum	verbers	N;GEN;INDF;PL
aflevering	afleverings	N;GEN;INDF;SG
loddekolbe	loddekolbers	N;GEN;INDF;PL
landkrabbe	landkrabbernes	N;NOM;DEF;PL
muldvarp	muldvarpene	N;NOM;DEF;PL
kultstatus	kultstatusers	N;GEN;INDF;PL
gyngehest	gyngehestene	N;NOM;DEF;PL
cigaretetui	cigaretetui	N;NOM;INDF;SG
ornitolog	ornitologernes	N;NOM;DEF;PL
akkord	akkorderne	N;NOM;DEF;PL
substans	substanserne	N;NOM;DEF;PL
skive	skivens	N;NOM;DEF;SG
spektakel	spektaklers	N;GEN;INDF;PL
rektor	rektorens	N;NOM;DEF;SG
realist	realist	N;NOM;INDF;SG
gyngehest	gyngehest	N;NOM;INDF;SG
dans	dansenes	N;NOM;DEF;PL
bilvask	bilvaske	N;NOM;INDF;PL
fajance	fajancen	N;NOM;DEF;SG
vindmølle	vindmølles	N;GEN;INDF;SG
atom	atoms	N;GEN;INDF;SG
politimester	politimesterens	N;NOM;DEF;SG
klovn	klovnenes	N;NOM;DEF;PL
enebarn	enebarnets	N;NOM;DEF;SG
tyver	tyveres	N;GEN;INDF;PL
henvendelse	henvendelser	N;NOM;INDF;PL
ornitologi	ornitologien	N;NOM;DEF;SG
sortering	sorterings	N;GEN;INDF;SG
sydafrikaner	sydafrikaners	N;GEN;INDF;SG
testning	testning	N;NOM;INDF;SG
fajance	fajancerne	N;NOM;DEF;PL
slagsmål	slagsmålet	N;NOM;DEF;SG
interesse	interesser	N;NOM;INDF;PL
søster	søsteren	N;NOM;DEF;SG
solsort	solsorts	N;GEN;INDF;SG
mobning	mobningens	N;NOM;DEF;SG
hældning	hældningen	N;NOM;DEF;SG
kasseapparat	kasseapparaternes	N;NOM;DEF;PL
manuskript	manuskript	N;NOM;INDF;SG
carbonkredsløb	carbonkredsløb	N;NOM;INDF;SG
fejl	fejlenes	N;NOM;DEF;PL
julegave	julegave	N;NOM;INDF;SG
central	centrals	N;GEN;INDF;SG
hornhinde	hornhinders	N;GEN;INDF;PL
lime	limen	N;NOM;DEF;SG
genstandsled	genstandsleds	N;GEN;INDF;PL
bogbus	bogbussers	N;GEN;INDF;PL
eddike	eddike	N;NOM;INDF;SG
flanør	flanørens	N;NOM;DEF;SG
hustru	hustruerne	N;NOM;DEF;PL
heltinde	heltindens	N;NOM;DEF;SG
hjernestamme	hjernestammers	N;GEN;INDF;PL
pornofilm	pornofilmen	N;NOM;DEF;SG
nål	nålen	N;NOM;DEF;SG
fremtid	fremtids	N;GEN;INDF;SG
kue	kue	V;NFIN;ACT
stål	stålene	N;NOM;DEF;PL
reagensglas	reagensglas	N;NOM;INDF;SG
boring	boringer	N;NOM;INDF;PL
hø	høets	N;NOM;DEF;SG
strubehoved	strubehovedets	N;NOM;DEF;SG
kandisere	kandiserede	V;IND;PST;ACT
mængdedifferens	mængdedifferensers	N;GEN;INDF;PL
kilogram	kilogrammenes	N;NOM;DEF;PL
duel	duellernes	N;NOM;DEF;PL
babysitter	babysitter	N;NOM;INDF;SG
multiplayerspil	multiplayerspillene	N;NOM;DEF;PL
læsehest	læsehestene	N;NOM;DEF;PL
lyn	lynet	N;NOM;DEF;SG
fordanskning	fordanskningerne	N;NOM;DEF;PL
vabel	vabels	N;GEN;INDF;SG
dogme	dogmers	N;GEN;INDF;PL
cellemembran	cellemembraner	N;NOM;INDF;PL
telefon	telefonen	N;NOM;DEF;SG
rektangel	rektangel	N;NOM;INDF;SG
mellemmand	mellemmændene	N;NOM;DEF;PL
sambo	samboens	N;NOM;DEF;SG
impuls	impuls	N;NOM;INDF;SG
fædreland	fædrelandene	N;NOM;DEF;PL
kandestøber	kandestøbers	N;GEN;INDF;SG
industrialisering	industrialiseringen	N;NOM;DEF;SG
gratismagasin	gratismagasin	N;NOM;INDF;SG
skridtbind	skridtbind	N;NOM;INDF;SG
mår	mårer	N;NOM;INDF;PL
hjerte	hjerters	N;GEN;INDF;PL
taxa	taxa	N;NOM;INDF;SG
malkepige	malkepiges	N;GEN;INDF;SG
dogme	dogmet	N;NOM;DEF;SG
kasseapparat	kasseapparat	N;NOM;INDF;SG
fremmedord	fremmedords	N;GEN;INDF;PL
hospital	hospitalet	N;NOM;DEF;SG
imitere	imiteres	V;IND;PRS;PASS
ugedag	ugedagene	N;NOM;DEF;PL
sus	sus'	N;GEN;INDF;PL
smiley	smileyernes	N;NOM;DEF;PL
kamel	kamel	N;NOM;INDF;SG
herbivor	herbivorernes	N;NOM;DEF;PL
vaccine	vacciners	N;GEN;INDF;PL
metropolit	metropolitter	N;NOM;INDF;PL
muldvarp	muldvarpen	N;NOM;DEF;SG
and	ænder	N;NOM;INDF;PL
paté	patéerne	N;NOM;DEF;PL
bydel	bydels	N;GEN;INDF;SG
nisse	nisse	N;NOM;INDF;SG
mp3-afspiller	mp3-afspillers	N;GEN;INDF;SG
huskarl	huskarls	N;GEN;INDF;SG
