क्षत्रिय	क्षत्रिये	ADJ;LOC;MASC;SG
अजाति	अजातौ	N;LOC;SG
अन्त	अन्तेषु	N;LOC;PL
शब्द	शब्दात्	N;ABL;SG
क्षत्रिय	क्षत्रियायाः	ADJ;GEN;FEM;SG
पलित	पलितानाम्	ADJ;GEN;PL
आप्त्य	आप्त्ये	ADJ;NOM;FEM;DU
दातृ	दातारौ	N;NOM;DU
स्वर्ग	स्वर्गायै	ADJ;DAT;FEM;SG
तित्तिर	तित्तिराः	N;VOC;PL
लक्ष्मी	लक्ष्मीः	N;NOM;SG
भुज	भुजम्	N;ACC;SG
मनुष्य	मनुष्यात्	ADJ;ABL;MASC;SG
मुरली	मुरलीभिः	N;INS;PL
पस्त्य	पस्त्याभ्याम्	N;INS;DU
अजाति	अजातिभ्याम्	N;DAT;DU
सांख्य	सांख्यानि	ADJ;ACC;NEUT;PL
अमल	अमलाः	ADJ;NOM;MASC;PL
अकर्मन्	अकर्म	N;ACC;SG
अन्ताराष्ट्रिय	अन्ताराष्ट्रियाभ्याम्	ADJ;DAT;NEUT;DU
भूर्ज	भूर्जम्	N;ACC;SG
अनुक्रमणिका	अनुक्रमणिकाभ्यः	N;ABL;PL
महाभारत	महाभारतम्	N;NOM;SG
मेघ	मेघेन	N;INS;SG
कल्ल	कल्लयोः	ADJ;GEN;NEUT;DU
प्रपाठक	प्रपाठकाः	N;NOM;PL
तित्तिर	तित्तिराभ्याम्	N;DAT;DU
बुध्न	बुध्नया	ADJ;INS;NEUT;SG
सुन्दर	सुन्दरात्	ADJ;ABL;SG
सांख्य	सांख्ये	ADJ;ACC;NEUT;DU
उद्गातृ	उद्गातॄणाम्	N;GEN;PL
नाटक	नाटकम्	ADJ;ACC;MASC;SG
भट्ट	भट्टानाम्	ADJ;GEN;MASC;PL
कच्छ	कच्छम्	N;ACC;SG
नलद	नलदे	ADJ;LOC;MASC;SG
तरु	तर्वा	ADJ;INS;SG
स्वश्व	स्वश्वाः	ADJ;VOC;FEM;PL
प्रथम	प्रथमा	ADJ;DAT;NEUT;SG
यातु	यातवे	N;DAT;SG
मरण	मरणयोः	N;GEN;DU
पृथु	पृथुभ्यः	N;DAT;PL
युग	युगाभ्याम्	N;DAT;DU
नाटक	नाटकैः	ADJ;INS;MASC;PL
विचार	विचारे	N;LOC;SG
चकोर	चकोर	N;VOC;SG
श्रवण	श्रवणे	N;LOC;SG
तित्तिर	तित्तिराणाम्	N;GEN;PL
यातु	यातुभिः	N;INS;PL
पार्वण	पार्वणाः	ADJ;NOM;MASC;PL
वसु	वसू	ADJ;VOC;DU
राज	राजानाम्	N;GEN;PL
पुष्प	पुष्पेण	N;INS;SG
जुष्ट	जुष्टे	ADJ;VOC;FEM;SG
अकर्मन्	अकर्मणी	N;VOC;DU
मुद्रा	मुद्रासु	N;LOC;PL
श्रम	श्रमयोः	N;GEN;DU
अङ्गार	अङ्गाराभ्याम्	N;DAT;DU
वृत्र	वृत्रयोः	N;GEN;DU
बोधिसत्त्व	बोधिसत्त्वेषु	N;LOC;PL
पृथु	प्र्थ्वीनाम्	ADJ;GEN;PL
अक्का	अक्के	N;VOC;SG
श्रमण	श्रमणीभ्याम्	ADJ;DAT;DU
पुष्कर	पुष्करानि	N;VOC;PL
आलय	आलयानि	N;VOC;PL
अश्रु	अश्रुभ्यः	N;DAT;PL
ह्रस्व	ह्रस्वान्	ADJ;ACC;MASC;PL
काव्य	काव्ये	ADJ;ACC;FEM;DU
आहार	आहारि	ADJ;VOC;FEM;SG
सहित	सहित	ADJ;VOC;NEUT;SG
वानर	वानरात्	ADJ;ABL;NEUT;SG
हरण	हरणेभ्यः	N;ABL;PL
अभाव	अभावाय	N;DAT;SG
इच्छा	इच्छायाः	N;GEN;SG
घटना	घटनाभ्यः	N;DAT;PL
वेणु	वेणू	N;VOC;DU
पृथु	पृथुनः	N;GEN;SG
अविक	अविकानाम्	N;GEN;PL
अंशुक	अंशुकम्	N;ACC;SG
यजमान	यजमानम्	ADJ;ACC;NEUT;SG
श्रद्धा	श्रद्धाभ्याम्	N;INS;DU
प्रहसन	प्रहसनानि	N;VOC;PL
सुन्दर	सुन्दर्यै	ADJ;DAT;SG
स्वर्ग	स्वर्गासु	ADJ;LOC;FEM;PL
क्रोश	क्रोशौ	N;VOC;DU
घोर	घोरः	ADJ;NOM;MASC;SG
पृथु	पृथ्वै	ADJ;DAT;SG
घोष	घोषयोः	N;GEN;DU
अकृत	अकृतम्	N;NOM;SG
सुन्दर	सुन्दरस्य	N;GEN;SG
श्वसुर	श्वसुराय	N;DAT;SG
तंतुवाय	तंतुवायाभ्याम्	N;INS;DU
भट्ट	भट्टस्य	ADJ;GEN;MASC;SG
जुगुप्सु	जुगुप्सुनि	ADJ;LOC;NEUT;SG
कल्ल	कल्लायाम्	ADJ;LOC;FEM;SG
शान्ति	शान्तिाय	N;DAT;SG
सर्प	सर्प्यौ	ADJ;ACC;FEM;DU
सुवर्ण	सुवर्णाम्	ADJ;ACC;FEM;SG
अविक	अविके	N;VOC;DU
कृष्ण	कृष्णाभ्याम्	ADJ;INS;MASC;DU
अक्का	अक्काभ्याम्	N;ABL;DU
मौन	मौनेन	N;INS;SG
अपस्मार	अपस्मारौ	N;NOM;DU
अंशुक	अंशुकयोः	N;GEN;DU
मोह	मोहाः	N;VOC;PL
वल	वलः	N;NOM;SG
लोह	लोहम्	ADJ;NOM;NEUT;SG
श्रद्धा	श्रद्धाभिः	N;INS;PL
हरण	हरणेभ्यः	N;DAT;PL
आहार	आहारयोः	ADJ;LOC;NEUT;DU
श्वशुर	श्वशुरेन	N;INS;SG
अक्षि	अक्ष्णोः	N;LOC;DU
तर्क	तर्केषु	N;LOC;PL
वेणु	वेणुः	N;NOM;SG
नक्ति	नक्तीः	N;ACC;PL
साम्य	साम्यानाम्	N;GEN;PL
स्वस्ति	स्वस्त्याः	N;GEN;SG
सत्य	सत्येभ्यः	N;DAT;PL
पलित	पलिक्न्यः	N;NOM;PL
दर्शपूर्णमास	दर्शपूर्णमासेभ्यः	N;DAT;PL
लोह	लोहेन	ADJ;INS;MASC;SG
बुध्न	बुध्ने	ADJ;VOC;NEUT;SG
स्वश्व	स्वश्वे	ADJ;ACC;NEUT;DU
आर्ष	आर्षः	ADJ;NOM;MASC;SG
पुष्प	पुष्पे	N;LOC;SG
अमल	अमलानि	ADJ;ACC;NEUT;PL
विराम	विरामाः	N;NOM;PL
अवतार	अवतारम्	N;ACC;SG
स्वरित	स्वरितम्	ADJ;ACC;NEUT;SG
भूतयज्ञ	भूतयज्ञेभ्यः	N;DAT;PL
कच्छ	कच्छाः	N;VOC;PL
तित्तिर	तित्तिराभ्याम्	N;ABL;DU
पट	पटे	N;LOC;SG
भट्ट	भट्टाः	ADJ;VOC;MASC;PL
अपरा	अपरे	N;VOC;DU
ह्रस्व	ह्रस्वाः	ADJ;NOM;FEM;PL
सपिण्ड	सपिण्डान्	N;ACC;PL
पाठ	पाठेभ्यः	N;DAT;PL
विभाग	विभागौ	N;VOC;DU
उल्ब	उल्बात्	N;ABL;SG
जुगुप्सु	जुगुप्सवे	ADJ;DAT;MASC;SG
लिङ्गशरीर	लिङ्गशरीरेभ्यः	N;DAT;PL
सुन्दर	सुन्दर्यौ	ADJ;ACC;DU
तृष्णा	तृष्णाभ्यः	N;ABL;PL
विबोध	विबोधे	N;LOC;SG
शान्ति	शान्तिात्	N;ABL;SG
विशाल	विशाल्यौ	ADJ;VOC;DU
यजमान	यजमानाभ्याम्	ADJ;INS;FEM;DU
सोम	सोमा	ADJ;DAT;NEUT;SG
जुगुप्सु	जुगुप्सू	ADJ;ACC;FEM;DU
रसा	रसयोः	N;GEN;DU
श्रम	श्रमाः	N;VOC;PL
अक्षि	अक्षीणि	N;VOC;PL
अविक	अविकौ	N;NOM;DU
विष्णु	विषणवे	N;DAT;SG
प्रहसन	प्रहसनम्	N;ACC;SG
श्रद्धा	श्रद्धाभ्यः	N;DAT;PL
तपस्	तपोभ्याम्	N;INS;DU
जन	जनीभ्याम्	ADJ;DAT;FEM;DU
पस्त्य	पस्त्यात्	N;ABL;SG
शारि	शारिभ्यः	N;ABL;PL
वातिगगम	वातिगगमेषु	N;LOC;PL
स्वर्ग	स्वर्गयोः	ADJ;LOC;NEUT;DU
आर्ष	आर्षाः	ADJ;VOC;MASC;PL
वैदर्भ	वैदर्भीम्	ADJ;ACC;FEM;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसानि	ADJ;ACC;NEUT;PL
काव्य	काव्ये	ADJ;NOM;FEM;DU
हरण	हरणानि	N;NOM;PL
सत्य	सत्येभ्यः	N;ABL;PL
सुन्दर	सुन्दरीभ्याम्	ADJ;ABL;DU
साहाय्य	साहाय्ये	N;NOM;DU
प्रहार	प्रहाराः	N;NOM;PL
श्वशुर	श्वशुरान्	N;ACC;PL
शारद	शारद्या	ADJ;INS;FEM;SG
क्रोश	क्रोशाय	N;DAT;SG
कार्य	कार्यम्	N;ACC;SG
प्रसाद	प्रसादः	N;NOM;SG
अनुक्रमणिका	अनुक्रमणिकायाः	N;ABL;SG
बहुव्रीहि	बहुव्रीह्या	ADJ;INS;FEM;SG
अजिर	अजिरेभ्यः	ADJ;ABL;MASC;PL
निपात	निपातेषु	N;LOC;PL
नलद	नलदाः	ADJ;NOM;MASC;PL
बुध्न	बुध्नौ	ADJ;ACC;MASC;DU
वानर	वानर्योः	ADJ;LOC;FEM;DU
प्रतीक	प्रतीकौ	ADJ;VOC;MASC;DU
पुष्कर	पुष्कराभ्याम्	N;INS;DU
गौड	गौड्या	ADJ;INS;FEM;SG
जन	जन्यः	ADJ;VOC;FEM;PL
स्वर्ग	स्वर्गैः	ADJ;INS;NEUT;PL
संसार	संसाराभ्याम्	N;DAT;DU
ऋण	ऋणेन	ADJ;INS;MASC;SG
क्षत्रिय	क्षत्रिया	ADJ;NOM;FEM;SG
जन	जनस्य	ADJ;GEN;MASC;SG
श्वशुर	श्वशुरेभ्यः	N;DAT;PL
सहित	सहिता	ADJ;NOM;FEM;SG
अकृता	अकृतायै	N;DAT;SG
सांख्य	सांख्य	ADJ;VOC;MASC;SG
स्वश्व	स्वश्वैः	ADJ;INS;MASC;PL
सुवर्ण	सुवर्णस्य	ADJ;GEN;MASC;SG
अरुण	अरुणौ	N;ACC;DU
साति	सत्याम्	N;LOC;SG
भूतयज्ञ	भूतयज्ञेषु	N;LOC;PL
स्वस्ति	स्वस्तिनोः	N;LOC;DU
जुगुप्सु	जुगुप्सुभ्यः	ADJ;ABL;FEM;PL
उद्गातृ	उद्गातारः	N;NOM;PL
वेला	वेले	N;NOM;DU
सुन्दर	सुन्दर	ADJ;VOC;SG
अक्का	अक्कया	N;INS;SG
आप्त्य	आप्त्यानाम्	ADJ;GEN;FEM;PL
सांख्य	सांख्याभ्याम्	ADJ;ABL;NEUT;DU
उद्गातृ	उद्गातारम्	N;ACC;SG
बुध्न	बुध्नेभ्यः	ADJ;DAT;MASC;PL
श्वसुर	श्वसुरौ	N;ACC;DU
वल	वलाभ्याम्	N;ABL;DU
काव्य	काव्यान्	ADJ;ACC;MASC;PL
केतक	केतकः	N;NOM;SG
कल्ल	कल्लाभ्याम्	ADJ;ABL;NEUT;DU
पृथु	पृथुने	N;DAT;SG
अनुक्रमणिका	अनुक्रमणिकाः	N;VOC;PL
अर्भ	अर्भानाम्	ADJ;GEN;MASC;PL
अक्का	अक्के	N;VOC;DU
अक्षता	अक्षताभ्याम्	N;INS;DU
पिण्ड	पिण्डात्	N;ABL;SG
सांख्य	सांख्ये	ADJ;NOM;NEUT;DU
पद	पदम्	N;NOM;SG
आर्ष	आर्षयोः	ADJ;LOC;NEUT;DU
प्रपाठक	प्रपाठकस्य	N;GEN;SG
अमल	अमला	ADJ;DAT;NEUT;SG
विचार	विचारेभ्यः	N;DAT;PL
क्षति	क्षते	N;VOC;SG
आदिकाव्य	आदिकाव्याभ्याम्	N;ABL;DU
लोह	लोह	ADJ;VOC;NEUT;SG
अश्रि	अश्र्याः	N;GEN;SG
आर्ष	आर्षैः	ADJ;INS;NEUT;PL
नलद	नलदाः	ADJ;NOM;NEUT;PL
द्युम्न	द्युम्नेषु	N;LOC;PL
अभ्र	अभ्राः	N;VOC;PL
अङ्गार	अङ्गारयोः	N;GEN;DU
पिण्ड	पिण्डाः	N;NOM;PL
उदन्या	उदन्यया	N;INS;SG
सांख्य	सांख्येन	ADJ;INS;MASC;SG
स्वस्ति	स्वस्तयः	N;NOM;PL
मयूरी	मयूरीभ्याम्	N;DAT;DU
संदेश	संदेशाभ्याम्	N;DAT;DU
घोर	घोराभ्याम्	ADJ;ABL;FEM;DU
महाभारत	महाभारतेभ्यः	N;ABL;PL
ऋण	ऋणाः	ADJ;VOC;MASC;PL
अजिर	अजिराभिः	ADJ;INS;FEM;PL
वैदर्भ	वैदर्भेभ्यः	ADJ;DAT;NEUT;PL
ऋण	ऋणाः	ADJ;NOM;FEM;PL
स्वस्ति	स्वस्त्यै	N;DAT;SG
तर्का	तर्के	N;ACC;DU
घोर	घोरात्	ADJ;ABL;MASC;SG
भट्ट	भट्टयोः	ADJ;LOC;MASC;DU
सहित	सहिताभ्याम्	ADJ;INS;NEUT;DU
उद्गातृ	उद्गातृभ्यः	N;ABL;PL
पार्वण	पार्वण्याः	ADJ;ABL;FEM;SG
दर्पण	दर्पणाभ्याम्	N;ABL;DU
क्रोश	क्रोशात्	N;ABL;SG
तर्कु	तर्कूणि	N;VOC;PL
यातु	यातु	N;NOM;SG
मृदु	मृदुना	ADJ;INS;SG
वसु	वस्व्यौ	ADJ;ACC;DU
शारद	शारदे	ADJ;VOC;NEUT;DU
वानर	वानरा	ADJ;DAT;NEUT;SG
वसु	वसुभ्याम्	N;INS;DU
कितव	कितवाः	N;VOC;PL
सर्प	सर्पयोः	ADJ;LOC;MASC;DU
स्वर्ग	स्वर्गाम्	ADJ;ACC;FEM;SG
सोम	सोमयोः	ADJ;LOC;NEUT;DU
प्रसाद	प्रसादात्	N;ABL;SG
शब्द	शब्देन	N;INS;SG
बुध्न	बुध्नाभ्यः	ADJ;ABL;NEUT;PL
अनेकान्तवाद	अनेकान्तवादौ	N;NOM;DU
बुध्न	बुध्नेभ्यः	ADJ;DAT;FEM;PL
अभाव	अभाव	N;VOC;SG
श्वशुर	श्वशुरयोः	N;GEN;DU
वृत्र	वृत्रेभ्यः	N;ABL;PL
दर्पण	दर्पणानाम्	N;GEN;PL
घोर	घोराः	ADJ;VOC;MASC;PL
मनुष्य	मनुष्ये	ADJ;NOM;FEM;DU
दर्पण	दर्पणेन	N;INS;SG
प्रासाद	प्रासादौ	N;VOC;DU
पार्वण	पार्वणेन	ADJ;INS;MASC;SG
रसा	रसाम्	N;ACC;SG
समुद्र	समुद्राः	N;VOC;PL
सुवर्ण	सुवर्णयोः	ADJ;LOC;NEUT;DU
क्षत्रिय	क्षत्रिय	ADJ;VOC;MASC;SG
अग्न्याधेय	अग्न्याधेयानाम्	N;GEN;PL
सत्य	सत्यात्	N;ABL;SG
तर्कु	तर्कूणि	N;ACC;PL
वसु	वसोः	ADJ;GEN;SG
वानर	वानराभ्याम्	ADJ;ABL;MASC;DU
मृदु	मृद्वीभिः	ADJ;INS;PL
सुन्दर	सुन्दरे	ADJ;LOC;SG
काव्य	काव्याभ्याम्	ADJ;ABL;FEM;DU
अश्रु	अश्रुभिः	N;INS;PL
उदन्या	उदन्याभिः	N;INS;PL
पार्वण	पार्वणेभ्यः	ADJ;ABL;NEUT;PL
पस्त्य	पस्त्ये	N;LOC;SG
अपरा	अपरयोः	N;GEN;DU
क्षत्रिय	क्षत्रियाभ्याम्	ADJ;ABL;NEUT;DU
बिडाली	बिडालि	N;VOC;SG
विशाल	विशालेषु	ADJ;LOC;PL
गौड	गौडा	ADJ;DAT;NEUT;SG
सृगाल	सृगालस्य	N;GEN;SG
लोह	लोहात्	ADJ;ABL;MASC;SG
अक्षि	अक्ष्णाः	N;ABL;SG
जुष्ट	जुष्टेषु	ADJ;LOC;NEUT;PL
पट	पटाभ्याम्	N;ABL;DU
गाथ	गाथयोः	N;GEN;DU
पथ	पथयोः	N;LOC;DU
अथर्वाङ्गिरस	अथर्वाङ्गिरसाः	ADJ;VOC;MASC;PL
यातु	यातुनोः	N;LOC;DU
यजमान	यजमानम्	ADJ;NOM;NEUT;SG
महिला	महिलासु	N;LOC;PL
कल्ल	कल्लेभ्यः	ADJ;ABL;MASC;PL
गौड	गौडेभ्यः	ADJ;ABL;MASC;PL
क्रोश	क्रोशाभ्याम्	N;ABL;DU
सहित	सहितानि	ADJ;ACC;NEUT;PL
आलय	आलयाः	N;VOC;PL
आर्ष	आर्षानि	ADJ;ACC;NEUT;PL
दर्पण	दर्पणौ	N;VOC;DU
ह्रस्व	ह्रस्वयोः	ADJ;LOC;NEUT;DU
लोक	लोकौ	N;VOC;DU
पट	पटः	N;NOM;SG
मृदु	मृदुभ्याम्	N;ABL;DU
मुरली	मुरल्यौ	N;VOC;DU
जुगुप्सु	जुगुप्सुम्	ADJ;ACC;FEM;SG
सोम	सोमे	ADJ;ACC;NEUT;DU
सर्प	सर्पाभ्याम्	ADJ;DAT;MASC;DU
उदन्	उदनी	N;ACC;DU
पान	पानानि	N;ACC;PL
लिङ्गशरीर	लिङ्गशरीरे	N;LOC;SG
वल	वलस्य	N;GEN;SG
दुग्ध	दुग्धाः	ADJ;ACC;FEM;PL
गभस्ति	गभस्ती	ADJ;ACC;MASC;DU
अश्व	अश्वे	N;LOC;SG
स्वरित	स्वरिते	ADJ;VOC;NEUT;DU
वल	वलाः	N;NOM;PL
गौड	गौडानि	ADJ;NOM;NEUT;PL
मौन	मौनात्	N;ABL;SG
हृद्	हृदः	N;GEN;SG
तर्क	तर्काभ्याम्	N;ABL;DU
स्वरित	स्वरिताम्	ADJ;ACC;FEM;SG
तित्तिर	तित्तिरौ	N;NOM;DU
मद	मदेन	N;INS;SG
नक्ति	नक्ती	N;NOM;DU
भुज	भुजौ	N;VOC;DU
अंश	अंशे	N;LOC;SG
सिंह	सिंहयोः	N;GEN;DU
जन	जनैः	ADJ;INS;MASC;PL
पार्वण	पार्वण्योः	ADJ;LOC;FEM;DU
दुग्ध	दुग्धयोः	ADJ;LOC;FEM;DU
अगस्ति	अगस्तिभ्यः	N;ABL;PL
अन्ताराष्ट्रिय	अन्ताराष्ट्रिया	ADJ;NOM;FEM;SG
अनुदात्त	अनुदात्तात्	ADJ;ABL;NEUT;SG
अजिर	अजिरेभ्यः	ADJ;DAT;NEUT;PL
गभस्ति	गभस्तिषु	ADJ;LOC;FEM;PL
श्रमण	श्रमणानाम्	N;GEN;PL
रति	रतयः	N;VOC;PL
शारि	शारिम्	N;ACC;SG
सोम	सोमे	ADJ;ACC;FEM;DU
द्वार	द्वारेण	N;INS;SG
स्वपू	स्वपूम्	N;ACC;SG
आहार	आहारेण	ADJ;INS;NEUT;SG
उद्गातृ	उद्गात्रे	N;DAT;SG
गृह	गृहाः	N;NOM;PL
पृथु	प्र्थ्व्याः	ADJ;ABL;SG
स्वर्ग	स्वर्गाभ्याम्	ADJ;ABL;MASC;DU
अजिर	अजिरेषु	ADJ;LOC;NEUT;PL
सहित	सहितैः	ADJ;INS;NEUT;PL
श्रमण	श्रमण्यौ	ADJ;VOC;DU
सुवर्ण	सुवर्णाः	ADJ;NOM;MASC;PL
प्रतीक	प्रतीके	ADJ;VOC;NEUT;DU
पथ	पथ	N;VOC;SG
तर्क	तर्के	N;LOC;SG
अचित्ति	अचित्त्याः	N;GEN;SG
अश्व	अश्वाः	N;NOM;PL
सोम	सोमाः	ADJ;NOM;MASC;PL
प्रतीक	प्रतीके	ADJ;LOC;NEUT;SG
ह्रस्व	ह्रस्वानाम्	ADJ;GEN;MASC;PL
गौड	गौडे	ADJ;VOC;NEUT;DU
साहित्य	साहित्यौ	N;VOC;DU
पुराण	पुराणाभ्याम्	N;INS;DU
अनस्	अनः	N;NOM;SG
युग	युगे	N;LOC;SG
शब्द	शब्द	N;VOC;SG
आहार	आहाराणि	ADJ;NOM;NEUT;PL
अन्ताराष्ट्रिय	अन्ताराष्ट्रियौ	ADJ;NOM;MASC;DU
परिजन	परिजनेषु	N;LOC;PL
अङ्गार	अङ्गारैः	N;INS;PL
विश्पति	विश्पतिभ्याम्	N;ABL;DU
अन्त	अन्तेभ्यः	N;DAT;PL
घटना	घटनाम्	N;ACC;SG
कल्ल	कल्लाभ्याम्	ADJ;DAT;NEUT;DU
अन्ताराष्ट्रिय	अन्ताराष्ट्रिये	ADJ;VOC;FEM;SG
द्युम्न	द्युम्नयोः	N;LOC;DU
पद	पदानि	N;VOC;PL
अर्भ	अर्भाः	ADJ;ACC;FEM;PL
भट्ट	भट्टेषु	ADJ;LOC;MASC;PL
तृष्णा	तृष्णाः	N;NOM;PL
पुराण	पुराणे	N;ACC;DU
जा	जया	N;INS;SG
सहित	सहिताभिः	ADJ;INS;FEM;PL
भट्ट	भट्टाभ्याम्	ADJ;DAT;MASC;DU
अरि	अरिना	N;INS;SG
गौड	गौडम्	ADJ;NOM;NEUT;SG
सहित	सहितम्	ADJ;ACC;NEUT;SG
शिल्पशाला	शिल्पशाले	N;ACC;DU
अर्थवाद	अर्थवादौ	N;NOM;DU
विशाल	विशालस्य	N;GEN;SG
सुवर्ण	सुवर्णाभ्यः	ADJ;DAT;FEM;PL
पिण्ड	पिण्डे	N;ACC;DU
अंश	अंशाभ्याम्	N;DAT;DU
प्रथम	प्रथमे	ADJ;VOC;NEUT;DU
सुवर्ण	सुवर्णयोः	ADJ;GEN;NEUT;DU
विश्पति	विश्पतयः	N;VOC;PL
अनेकान्तवाद	अनेकान्तवादेभ्यः	N;ABL;PL
बहुव्रीहि	बहुव्रीहिना	ADJ;INS;NEUT;SG
प्रसाद	प्रसादम्	N;ACC;SG
सोम	सोमेषु	ADJ;LOC;NEUT;PL
ऋण	ऋण	ADJ;VOC;NEUT;SG
बहुव्रीहि	बहुव्रीहेः	ADJ;ABL;FEM;SG
वैदर्भ	वैदर्भौ	ADJ;ACC;MASC;DU
दातृ	दातरि	N;LOC;SG
काम	कामात्	N;ABL;SG
पान	पानाभ्याम्	N;INS;DU
गभस्ति	गभस्ती	ADJ;NOM;FEM;DU
विशाल	विशालाभ्याम्	ADJ;ABL;DU
संदेश	संदेशयोः	N;LOC;DU
जुगुप्सु	जुगुप्सो	ADJ;VOC;MASC;SG
घोर	घोरस्य	ADJ;GEN;NEUT;SG
मौन	मौन	N;VOC;SG
पान	पाने	N;LOC;SG
आप्त्य	आप्त्येषु	ADJ;LOC;NEUT;PL
सुवर्ण	सुवर्णैः	ADJ;INS;NEUT;PL
सत्य	सत्याभ्याम्	N;ABL;DU
लोक	लोकात्	N;ABL;SG
पान	पान	N;VOC;SG
लोह	लोहस्य	ADJ;GEN;NEUT;SG
युग	युगाभ्याम्	N;ABL;DU
तरु	तरुभिः	ADJ;INS;PL
शान्ति	शान्तिेभ्यः	N;ABL;PL
मयूरी	मयूर्यौ	N;NOM;DU
राज	राजैः	N;INS;PL
बहुव्रीहि	बहुव्रीह्योः	ADJ;GEN;MASC;DU
मृदु	मृद्वोः	ADJ;GEN;DU
अपत्यता	अपत्यताम्	N;ACC;SG
जा	जे	N;VOC;SG
विराम	विरामाभ्याम्	N;INS;DU
नाटक	नाटकि	ADJ;VOC;FEM;SG
राज	राजौ	N;ACC;DU
बुध्न	बुध्नात्	ADJ;ABL;FEM;SG
द्वार	द्वारयोः	N;GEN;DU
प्रहार	प्रहारेषु	N;LOC;PL
अमल	अमलेन	ADJ;INS;NEUT;SG
नप्तृ	नप्तृभ्याम्	N;ABL;DU
वृक्ष	वृक्षाणाम्	N;GEN;PL
तडाग	तडागस्य	N;GEN;SG
अरि	अरिभ्याम्	N;INS;DU
अंशुक	अंशुकस्य	N;GEN;SG
श्रम	श्रमस्य	N;GEN;SG
सुवर्ण	सुवर्णे	ADJ;LOC;NEUT;SG
श्रद्धा	श्रद्धयोः	N;GEN;DU
वैदर्भ	वैदर्भाभ्याम्	ADJ;ABL;MASC;DU
वल	वले	N;LOC;SG
उद्गातृ	उद्गातारः	N;VOC;PL
अर्भ	अर्भानि	ADJ;NOM;NEUT;PL
प्रमन्थ	प्रमन्थाय	N;DAT;SG
प्रतीक	प्रतीकेभ्यः	ADJ;DAT;MASC;PL
जुगुप्सु	जुगुप्सुभिः	ADJ;INS;FEM;PL
बहुव्रीहि	बहुव्रीहीनाम्	ADJ;GEN;NEUT;PL
जुष्ट	जुष्टम्	ADJ;NOM;NEUT;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसायाः	ADJ;ABL;FEM;SG
सहित	सहिताभ्याम्	ADJ;ABL;MASC;DU
अनस्	अनसोः	N;LOC;DU
सुवर्ण	सुवर्णाभ्यः	ADJ;ABL;FEM;PL
अजाति	अजातेः	N;GEN;SG
शब्द	शब्दाभ्याम्	N;DAT;DU
पलित	पलिताः	ADJ;VOC;PL
सिंह	सिंहाः	N;VOC;PL
कृष्ण	कृष्णाम्	ADJ;ACC;FEM;SG
अङ्गार	अङ्गारेभ्यः	N;ABL;PL
जनन	जननाभ्याम्	N;DAT;DU
लोह	लोहान्	ADJ;ACC;MASC;PL
अश्रि	अश्रिभ्याम्	N;INS;DU
आहार	आहार्यौ	ADJ;ACC;FEM;DU
आदिकाव्य	आदिकाव्या	N;DAT;SG
बुध्न	बुध्नाभ्याम्	ADJ;ABL;MASC;DU
गाथ	गाथः	N;NOM;SG
घोर	घोरायाः	ADJ;ABL;FEM;SG
प्रवेशक	प्रवेशकाभ्याम्	N;ABL;DU
अमल	अमलायै	ADJ;DAT;FEM;SG
अविक	अविके	N;NOM;DU
अक्षता	अक्षते	N;VOC;SG
गभस्ति	गभस्त्योः	ADJ;LOC;MASC;DU
बहुव्रीहि	बहुव्रीहिभ्याम्	ADJ;ABL;NEUT;DU
तरु	तरधेन्वाः	ADJ;GEN;SG
वैडूर्य	वैडूर्यानि	N;NOM;PL
वाणिज	वाणिजौ	N;NOM;DU
द्वार	द्वाराणाम्	N;GEN;PL
शान्ति	शान्तिान्	N;ACC;PL
अविद्या	अविद्याभ्याम्	N;ABL;DU
बोधिसत्त्व	बोधिसत्त्वौ	N;NOM;DU
पितृयज्ञ	पितृयज्ञानाम्	N;GEN;PL
गौड	गौड्यै	ADJ;DAT;FEM;SG
गिरि	गिरिना	N;INS;SG
घोष	घोषैः	N;INS;PL
हरण	हरणेन	N;INS;SG
मृदु	मृदू	ADJ;NOM;DU
जनन	जननानि	N;VOC;PL
आप्त्य	आप्त्ययोः	ADJ;LOC;NEUT;DU
अर्भ	अर्भे	ADJ;VOC;FEM;DU
तूलि	तूल्याः	N;GEN;SG
आदिकाव्य	आदिकाव्यानि	N;VOC;PL
तपस्	तपसि	N;LOC;SG
कालचक्र	कालचक्राभ्याम्	N;ABL;DU
आदिकाव्य	आदिकाव्ये	N;NOM;DU
अर्भ	अर्भे	ADJ;ACC;FEM;DU
वानर	वानरेभ्यः	ADJ;ABL;NEUT;PL
सांख्य	सांख्येन	ADJ;INS;NEUT;SG
तर्कु	तर्कवः	N;VOC;PL
निपात	निपाते	N;LOC;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसाय	ADJ;DAT;MASC;SG
आर्ष	आर्षाभ्याम्	ADJ;DAT;MASC;DU
तर्कु	तर्कु	N;NOM;SG
प्रथम	प्रथमयोः	ADJ;LOC;FEM;DU
मनुष्य	मनुष्यात्	ADJ;ABL;NEUT;SG
अक्षता	अक्षताः	N;VOC;PL
नलद	नलदाभ्याम्	ADJ;ABL;NEUT;DU
विचार	विचारात्	N;ABL;SG
पाकयज्ञ	पाकयज्ञे	N;LOC;SG
पुराण	पुराणायाः	ADJ;GEN;SG
स्वरित	स्वरिते	ADJ;LOC;NEUT;SG
गभस्ति	गभस्ती	ADJ;VOC;FEM;DU
जाति	जाती	N;NOM;DU
विराम	विरामैः	N;INS;PL
साम्य	साम्य	N;VOC;SG
यजमान	यजमानात्	ADJ;ABL;MASC;SG
पार्वण	पार्वणानि	ADJ;ACC;NEUT;PL
रति	रत्याम्	N;LOC;SG
सुर	सुराय	N;DAT;SG
क्रोश	क्रोशः	N;NOM;SG
विशाल	विशाले	ADJ;ACC;DU
अश्व	अश्वैः	N;INS;PL
ग्रन्थ	ग्रन्थाभ्याम्	N;INS;DU
प्रथम	प्रथमाभ्याम्	ADJ;INS;MASC;DU
विराम	विरामेषु	N;LOC;PL
स्वरित	स्वरितायाः	ADJ;GEN;FEM;SG
अश्रु	अश्रु	N;NOM;SG
अक्का	अक्काभ्याम्	N;DAT;DU
लोह	लोहा	ADJ;NOM;FEM;SG
अथर्वाङ्गिरस	अथर्वाङ्गिरसे	ADJ;LOC;MASC;SG
रसभ	रसभाः	N;NOM;PL
बुध्न	बुध्नाभ्याम्	ADJ;INS;FEM;DU
अचित्ति	अचित्तये	N;DAT;SG
आदिकाव्य	आदिकाव्यस्य	N;GEN;SG
प्रपाठक	प्रपाठकयोः	N;LOC;DU
सत्य	सत्यम्	N;ACC;SG
सिंहल	सिंहलाभ्याम्	N;ABL;DU
मास	मासाभ्याम्	N;ABL;DU
मरण	मरणेन	N;INS;SG
जुगुप्सु	जुगुप्सुना	ADJ;INS;MASC;SG
स्वर्ग	स्वर्गेभ्यः	ADJ;ABL;MASC;PL
अक्का	अक्के	N;ACC;DU
विशाल	विशाले	ADJ;LOC;SG
मृदु	मृदौ	ADJ;LOC;SG
उल्ब	उल्बैः	N;INS;PL
सर्प	सर्प	ADJ;VOC;MASC;SG
वर्षा	वर्षाः	N;NOM;PL
नाटक	नाटकान्	ADJ;ACC;MASC;PL
भूर्ज	भूर्जस्य	N;GEN;SG
मृदु	मृद्व्यै	ADJ;DAT;SG
भट्ट	भट्टम्	ADJ;NOM;NEUT;SG
काव्य	काव्य	ADJ;VOC;NEUT;SG
दर्शपूर्णमास	दर्शपूर्णमासौ	N;ACC;DU
अरुण	अरुणः	N;NOM;SG
तरु	तरून्	N;ACC;PL
पलित	पलितस्य	ADJ;GEN;SG
नलद	नलदानि	ADJ;VOC;FEM;PL
द्रु	द्रोः	N;GEN;SG
दर्शपूर्णमास	दर्शपूर्णमासेन	N;INS;SG
प्रदेश	प्रदेशाभ्याम्	N;INS;DU
अविद्या	अविद्ययोः	N;LOC;DU
पाद	पादाभ्याम्	N;ABL;DU
अरि	अर्योः	N;LOC;DU
वाणिज	वाणिजेभ्यः	N;DAT;PL
पलित	पलितेषु	ADJ;LOC;PL
सहित	सहित	ADJ;VOC;MASC;SG
पाद	पादाभ्याम्	N;DAT;DU
आलय	आलयान्	N;ACC;PL
अंश	अंशौ	N;NOM;DU
नाटक	नाटकेभ्यः	ADJ;DAT;NEUT;PL
केतक	केतकौ	N;ACC;DU
उद्गातृ	उद्गातृभ्याम्	N;ABL;DU
वृक्ष	वृक्षेभ्यः	N;DAT;PL
सुवर्ण	सुवर्णाः	ADJ;VOC;FEM;PL
प्रहसन	प्रहसनाभ्याम्	N;ABL;DU
अविक	अविकैः	N;INS;PL
पुष्प	पुष्पे	N;NOM;DU
काम	कामम्	N;ACC;SG
दिन	दिनानि	N;VOC;PL
यातु	यातो	N;VOC;SG
सपिण्ड	सपिण्डस्य	N;GEN;SG
दुग्ध	दुग्धे	ADJ;ACC;NEUT;DU
दृढ	दृढेषु	N;LOC;PL
शारि	शारयः	N;NOM;PL
मुद्रा	मुद्राः	N;ACC;PL
अनुक्रमणिका	अनुक्रमणिकाः	N;ACC;PL
मृत्यु	मृत्यवे	N;DAT;SG
घोर	घोरे	ADJ;LOC;NEUT;SG
स्वसृ	स्वस्रा	N;INS;SG
तृष्णा	तृष्णे	N;NOM;DU
सांख्य	सांख्याभ्याम्	ADJ;ABL;MASC;DU
ऋण	ऋणेषु	ADJ;LOC;MASC;PL
कल्ल	कल्लाः	ADJ;VOC;MASC;PL
यवनिका	यवनिकाम्	N;ACC;SG
आलय	आलयम्	N;NOM;SG
कल्ल	कल्लौ	ADJ;ACC;MASC;DU
भूतयज्ञ	भूतयज्ञाः	N;NOM;PL
यजमान	यजमानाभ्याम्	ADJ;ABL;NEUT;DU
मृदु	मृद्वीभ्यः	ADJ;DAT;PL
साति	सतेः	N;GEN;SG
देवयज्ञ	देवयज्ञाभ्याम्	N;INS;DU
अपत्यता	अपत्यतायाम्	N;LOC;SG
गौड	गौडाभ्याम्	ADJ;DAT;NEUT;DU
पाद	पादेभ्यः	N;ABL;PL
दुर्ग	दुर्गाभ्याम्	N;ABL;DU
स्वपू	स्वप्वा	N;INS;SG
श्रमण	श्रमण	ADJ;VOC;SG
दुग्ध	दुग्धयोः	ADJ;GEN;NEUT;DU
जनन	जननस्य	N;GEN;SG
अकर्मन्	अकर्म्णोः	N;LOC;DU
द्रु	द्रून्	N;ACC;PL
प्रदेश	प्रदेशाभ्याम्	N;ABL;DU
सुन्दर	सुन्दरेभ्यः	N;DAT;PL
अङ्गार	अङ्गारम्	N;ACC;SG
अङ्गार	अङ्गारेभ्यः	N;DAT;PL
आप्त्य	आप्त्यस्य	ADJ;GEN;MASC;SG
वानर	वानरीभिः	ADJ;INS;FEM;PL
कल्ल	कल्लाभ्याम्	ADJ;ABL;MASC;DU
वल	वलौ	N;NOM;DU
आलय	आलये	N;NOM;DU
हृद्	हृद्भ्याम्	N;DAT;DU
कृष्ण	कृष्णम्	ADJ;ACC;MASC;SG
प्रमन्थ	प्रमन्थौ	N;ACC;DU
लक्ष्मी	लक्ष्मीम्	N;ACC;SG
स्वर्ग	स्वर्गाः	ADJ;VOC;MASC;PL
मार्जार	मार्जारात्	N;ABL;SG
पुष्प	पुष्प	N;VOC;SG
मनुष्य	मनुष्यायाम्	ADJ;LOC;FEM;SG
पुराण	पुराणीभ्याम्	ADJ;DAT;DU
श्रमण	श्रमणीनाम्	ADJ;GEN;PL
प्रासाद	प्रासादयोः	N;LOC;DU
सुवर्ण	सुवर्णायाः	ADJ;ABL;FEM;SG
विशाल	विशालात्	N;ABL;SG
आप्त्य	आप्त्यौ	ADJ;VOC;MASC;DU
रति	रती	N;ACC;DU
तपस्	तपसः	N;GEN;SG
यातु	यातु	N;VOC;SG
स्वपू	स्वप्वै	N;DAT;SG
साम्य	साम्येभ्यः	N;DAT;PL
क्षत्रिय	क्षत्रियेभ्यः	ADJ;DAT;NEUT;PL
संदेश	संदेशस्य	N;GEN;SG
अरुण	अरुणेभ्यः	N;DAT;PL
घटना	घटनाः	N;VOC;PL
जाति	जातीनाम्	N;GEN;PL
सहित	सहितस्य	ADJ;GEN;MASC;SG
अरि	अरिभ्यः	N;DAT;PL
पुष्प	पुष्पस्य	N;GEN;SG
श्वसुर	श्वसुरम्	N;ACC;SG
अवतार	अवतारेभ्यः	N;DAT;PL
सपिण्ड	सपिण्डाय	N;DAT;SG
अक्षि	अक्ष्यौ	N;NOM;DU
मत्त	मत्तौ	N;ACC;DU
नप्तृ	नप्तारौ	N;ACC;DU
शारि	शारौ	N;LOC;SG
प्राण	प्राणौ	N;VOC;DU
चुम्ब	चुम्बाभ्याम्	N;DAT;DU
उदन्	उद	N;VOC;SG
लिङ्गशरीर	लिङ्गशरीरैः	N;INS;PL
तन्तु	तन्त्वोः	N;GEN;DU
तर्क	तर्केण	N;INS;SG
अजाति	अजाती	N;ACC;DU
अरण्य	अरण्यम्	N;ACC;SG
क्षति	क्षत्योः	N;GEN;DU
मनुष्य	मनुष्यासु	ADJ;LOC;FEM;PL
उद्र	उद्रयोः	N;LOC;DU
ह्रस्व	ह्रस्वानि	ADJ;ACC;NEUT;PL
वसु	वसून्	ADJ;ACC;PL
आर्ष	आर्षाभ्याम्	ADJ;INS;MASC;DU
जाति	जाते	N;VOC;SG
अन्ताराष्ट्रिय	अन्ताराष्ट्रियाभ्यः	ADJ;DAT;FEM;PL
गौड	गौडे	ADJ;LOC;MASC;SG
अकृता	अकृताभ्याम्	N;DAT;DU
सहित	सहितयोः	ADJ;GEN;NEUT;DU
तर्क	तर्केभ्यः	N;ABL;PL
विश्पति	विश्पतयः	N;NOM;PL
प्रपाठक	प्रपाठक	N;VOC;SG
विबोध	विबोधयोः	N;LOC;DU
मृत्यु	मृत्यौ	N;LOC;SG
तडाग	तडागाभ्याम्	N;INS;DU
उद्गातृ	उद्गातॄन्	N;ACC;PL
विचार	विचारयोः	N;LOC;DU
सोम	सोमाः	ADJ;NOM;FEM;PL
उद्गातृ	उद्गातारौ	N;VOC;DU
तपस्	तपोभ्यः	N;DAT;PL
नाटक	नाटकैः	ADJ;INS;NEUT;PL
अजिर	अजिरे	ADJ;LOC;NEUT;SG
नलद	नलदाभ्याम्	ADJ;ABL;MASC;DU
अमल	अमलेषु	ADJ;LOC;NEUT;PL
तपस्	तपसोः	N;GEN;DU
महाभारत	महाभारतेषु	N;LOC;PL
भट्ट	भट्टाभ्याम्	ADJ;ABL;FEM;DU
यातु	यातू	N;NOM;DU
कण्ठ	कण्ठयोः	N;LOC;DU
आदिकाव्य	आदिकाव्याभ्याम्	N;DAT;DU
यजमान	यजमानयोः	ADJ;GEN;MASC;DU
ह्रस्व	ह्रस्वायाः	ADJ;ABL;FEM;SG
मरण	मरणे	N;LOC;SG
मुरली	मुरली	N;NOM;SG
वृत्र	वृत्रः	N;NOM;SG
पृथु	पृथुभिः	ADJ;INS;PL
युग	युगेषु	N;LOC;PL
अरुण	अरुणौ	N;NOM;DU
अन्ताराष्ट्रिय	अन्ताराष्ट्रियानि	ADJ;NOM;NEUT;PL
अन्ताराष्ट्रिय	अन्ताराष्ट्रियानाम्	ADJ;GEN;FEM;PL
संहिता	संहिता	N;NOM;SG
सोम	सोमेभ्यः	ADJ;ABL;NEUT;PL
मेघ	मेघात्	N;ABL;SG
क्षति	क्षतयः	N;VOC;PL
शारद	शारदस्य	ADJ;GEN;MASC;SG
अश्रि	अश्र्याम्	N;LOC;SG
कालचक्र	कालचक्राभ्याम्	N;DAT;DU
श्यामा	श्यामया	N;INS;SG
हरण	हरणाभ्याम्	N;DAT;DU
मरण	मरणानाम्	N;GEN;PL
पुराण	पुराणानि	N;VOC;PL
चकोर	चकोराय	N;DAT;SG
दर्पण	दर्पणान्	N;ACC;PL
अन्त	अन्तानाम्	N;GEN;PL
अकृत	अकृते	N;VOC;DU
विशाल	विशालेभ्यः	N;DAT;PL
साम्य	साम्याभ्याम्	N;DAT;DU
घोर	घोरेषु	ADJ;LOC;NEUT;PL
साति	सते	N;VOC;SG
विशाल	विशाल्योः	ADJ;LOC;DU
अविद्या	अविद्याः	N;NOM;PL
शब्द	शब्दान्	N;ACC;PL
जुष्ट	जुष्टाम्	ADJ;ACC;FEM;SG
अङ्गार	अङ्गाराय	N;DAT;SG
अजाति	अजातिभ्यः	N;ABL;PL
वैदर्भ	वैदर्भीभिः	ADJ;INS;FEM;PL
घोर	घोरैः	ADJ;INS;MASC;PL
दुग्ध	दुग्धयोः	ADJ;GEN;MASC;DU
प्रतीक	प्रतीक	ADJ;VOC;MASC;SG
बोधिसत्त्व	बोधिसत्त्वेभ्यः	N;DAT;PL
उदन्या	उदन्याम्	N;ACC;SG
अमल	अमलात्	ADJ;ABL;MASC;SG
कुञ्चिका	कुञ्चिकयोः	N;GEN;DU
विश्पति	विश्पत्योः	N;GEN;DU
वसु	वसौ	ADJ;LOC;SG
पिण्ड	पिण्डानि	N;NOM;PL
संगीतशाला	संगीतशाले	N;NOM;DU
मौन	मौनानि	N;NOM;PL
स्वश्व	स्वश्वयोः	ADJ;LOC;MASC;DU
प्रासाद	प्रासाद	N;VOC;SG
नाटक	नाटक्याम्	ADJ;LOC;FEM;SG
यजमान	यजमानाभ्याम्	ADJ;INS;NEUT;DU
प्राण	प्राणैः	N;INS;PL
शारि	शारिभ्याम्	N;ABL;DU
विशाल	विशालयोः	ADJ;LOC;DU
बुध्न	बुध्नानाम्	ADJ;GEN;MASC;PL
प्रासाद	प्रासादात्	N;ABL;SG
गृहपत्नी	गृहपत्नी	N;NOM;SG
ऋण	ऋणस्य	ADJ;GEN;MASC;SG
विभाग	विभागान्	N;ACC;PL
आर्ष	आर्षम्	ADJ;ACC;NEUT;SG
संहिता	संहितया	N;INS;SG
संदेश	संदेशेन	N;INS;SG
श्रमण	श्रमणैः	N;INS;PL
स्वश्व	स्वश्वानाम्	ADJ;GEN;FEM;PL
वल	वलेभ्यः	N;DAT;PL
अमल	अमल	ADJ;VOC;MASC;SG
घोर	घोर	ADJ;VOC;NEUT;SG
साति	सतिः	N;NOM;SG
सुवर्ण	सुवर्णाभ्याम्	ADJ;DAT;FEM;DU
योग	योगानाम्	N;GEN;PL
सृगाल	सृगालयोः	N;LOC;DU
अन्ताराष्ट्रिय	अन्ताराष्ट्रियानाम्	ADJ;GEN;MASC;PL
सुवर्ण	सुवर्णस्य	ADJ;GEN;NEUT;SG
सोम	सोमेभ्यः	ADJ;DAT;NEUT;PL
महाभारत	महाभारताभ्याम्	N;ABL;DU
नक्ति	नक्त्या	N;INS;SG
पलित	पलिक्न्या	N;INS;SG
पद	पदेन	N;INS;SG
बुध्न	बुध्ने	ADJ;LOC;FEM;SG
कल्ल	कल्लाभ्याम्	ADJ;INS;FEM;DU
क्षति	क्षती	N;VOC;DU
श्रमण	श्रमणाः	ADJ;NOM;PL
मृदु	मृदुनि	N;LOC;SG
सांख्य	सांख्यैः	ADJ;INS;MASC;PL
अकृत	अकृतयोः	N;LOC;DU
बुध्न	बुध्नानाम्	ADJ;GEN;NEUT;PL
स्वपू	स्वप्वः	N;VOC;PL
समुद्र	समुद्र	N;VOC;SG
कल्ल	कल्ले	ADJ;ACC;NEUT;DU
वसु	वस्वाम्	ADJ;LOC;SG
अकृत	अकृते	N;ACC;DU
गभस्ति	गभस्तिभ्याम्	ADJ;ABL;FEM;DU
लिङ्गशरीर	लिङ्गशरीरेन	N;INS;SG
सुवर्ण	सुवर्णेभ्यः	ADJ;DAT;MASC;PL
जन	जनः	ADJ;NOM;MASC;SG
आर्ष	आर्षा	ADJ;DAT;NEUT;SG
शारद	शारदी	ADJ;NOM;FEM;SG
आर्ष	आर्षेन	ADJ;INS;MASC;SG
श्रद्धा	श्रद्धाभ्याम्	N;DAT;DU
सुवर्ण	सुवर्णा	ADJ;DAT;NEUT;SG
घोर	घोराभ्याम्	ADJ;DAT;NEUT;DU
कण्ठ	कण्ठयोः	N;GEN;DU
अपस्मार	अपस्मारौ	N;ACC;DU
स्वस्ति	स्वस्तिभ्याम्	N;INS;DU
अविक	अविकेभ्यः	N;DAT;PL
गौड	गौडात्	ADJ;ABL;NEUT;SG
अपरा	अपराभ्याम्	N;ABL;DU
शारि	शारिभ्यः	N;DAT;PL
अक्षि	अक्ष्योः	N;GEN;DU
सर्प	सर्पीभिः	ADJ;INS;FEM;PL
प्रसाद	प्रसादाः	N;NOM;PL
पाठ	पाठेन	N;INS;SG
वातिगगम	वातिगगमयोः	N;LOC;DU
कण्ठ	कण्ठेन	N;INS;SG
नारी	नार्योः	N;GEN;DU
सिंहल	सिंहले	N;LOC;SG
गौड	गौडाः	ADJ;NOM;MASC;PL
अङ्गार	अङ्गारौ	N;VOC;DU
अपरा	अपरे	N;ACC;DU
यजमान	यजमानेन	ADJ;INS;NEUT;SG
शब्द	शब्दस्य	N;GEN;SG
वेणु	वेणुभ्याम्	N;ABL;DU
पाकयज्ञ	पाकयज्ञाभ्याम्	N;INS;DU
अर्थवाद	अर्थवादाभ्याम्	N;DAT;DU
तित्तिर	तित्तिराः	N;NOM;PL
आलय	आलयात्	N;ABL;SG
दिन	दिनानि	N;ACC;PL
ऋण	ऋणाः	ADJ;ACC;FEM;PL
अश्व	अश्वम्	N;ACC;SG
सुन्दर	सुन्दरः	N;NOM;SG
सांख्य	सांख्याभ्याम्	ADJ;INS;NEUT;DU
यवनिका	यवनिकया	N;INS;SG
मनुष्य	मनुष्याणि	ADJ;NOM;NEUT;PL
वृत्र	वृत्रेषु	N;LOC;PL
गिरि	गिर्योः	N;GEN;DU
लोक	लोकेन	N;INS;SG
पान	पानाभ्याम्	N;ABL;DU
मास	मासेन	N;INS;SG
अपत्यता	अपत्यताभ्याम्	N;INS;DU
आर्ष	आर्षीम्	ADJ;ACC;FEM;SG
मनुष्य	मनुष्येभ्यः	ADJ;ABL;NEUT;PL
तडाग	तडागाभ्याम्	N;ABL;DU
मेघ	मेघम्	N;ACC;SG
स्वपू	स्वपु	N;VOC;SG
अर्भ	अर्भायाः	ADJ;ABL;FEM;SG
श्रम	श्रमे	N;LOC;SG
देवी	देव्योः	N;LOC;DU
संगीतशाला	संगीतशालाभ्यः	N;DAT;PL
घोष	घोषाभ्याम्	N;ABL;DU
उल्ब	उल्ब	N;VOC;SG
विशाल	विशालाः	ADJ;VOC;PL
कृष्ण	कृष्णयोः	ADJ;LOC;FEM;DU
अजिर	अजिरयोः	ADJ;GEN;FEM;DU
स्वर्ग	स्वर्गाभ्यः	ADJ;DAT;FEM;PL
सहित	सहितेषु	ADJ;LOC;MASC;PL
स्वश्व	स्वश्वाः	ADJ;NOM;FEM;PL
कृष्ण	कृष्णाभ्याम्	ADJ;INS;NEUT;DU
विष्णु	विषणधेन्वाः	N;ABL;SG
जन	जनेषु	ADJ;LOC;MASC;PL
शारद	शारदे	ADJ;LOC;MASC;SG
प्राण	प्राणाः	N;VOC;PL
जुष्ट	जुष्टानाम्	ADJ;GEN;FEM;PL
वैदर्भ	वैदर्भे	ADJ;LOC;MASC;SG
सुन्दर	सुन्दराः	N;NOM;PL
मद	मदयोः	N;GEN;DU
निपात	निपातेभ्यः	N;ABL;PL
अनुदात्त	अनुदात्ताः	ADJ;ACC;FEM;PL
अनुदात्त	अनुदात्ता	ADJ;NOM;FEM;SG
महाकवि	महाकवेः	N;GEN;SG
गौड	गौड्याः	ADJ;GEN;FEM;SG
गभस्ति	गभस्तिभ्यः	ADJ;ABL;NEUT;PL
स्वश्व	स्वश्वाः	ADJ;ACC;FEM;PL
भट्ट	भट्टेन	ADJ;INS;MASC;SG
जाति	जाती	N;VOC;DU
नप्तृ	नप्तर्	N;VOC;SG
सुन्दर	सुन्दरेण	ADJ;INS;SG
यवनिका	यवनिकाभ्यः	N;ABL;PL
अकर्मन्	अकर्माणि	N;ACC;PL
क्षत्रिय	क्षत्रियाः	ADJ;VOC;MASC;PL
बहुव्रीहि	बहुव्रीहि	ADJ;ACC;NEUT;SG
कालचक्र	कालचक्रा	N;DAT;SG
क्षत्रिय	क्षत्रियम्	ADJ;ACC;NEUT;SG
संसार	संसाराः	N;NOM;PL
अमल	अमलाः	ADJ;NOM;FEM;PL
ह्रस्व	ह्रस्वाभ्याम्	ADJ;ABL;MASC;DU
भूतयज्ञ	भूतयज्ञयोः	N;GEN;DU
दुग्ध	दुग्धेषु	ADJ;LOC;NEUT;PL
परमाणु	परमाणुणा	N;INS;SG
तृष्णा	तृष्णाभ्याम्	N;INS;DU
पट	पटस्य	N;GEN;SG
मौन	मौनेभ्यः	N;ABL;PL
वानर	वानरम्	ADJ;ACC;MASC;SG
जुगुप्सु	जुगुप्सू	ADJ;NOM;FEM;DU
द्रु	द्रुभ्याम्	N;INS;DU
वृक्ष	वृक्षैः	N;INS;PL
प्रथम	प्रथमः	ADJ;NOM;MASC;SG
दृढ	दृढानि	N;ACC;PL
भट्ट	भट्टेभ्यः	ADJ;DAT;NEUT;PL
अजिर	अजिरैः	ADJ;INS;NEUT;PL
अजिर	अजिरेषु	ADJ;LOC;MASC;PL
सत्य	सत्ये	N;NOM;DU
पुराण	पुराणा	N;DAT;SG
द्युम्न	द्युम्नस्य	N;GEN;SG
इच्छा	इच्छासु	N;LOC;PL
पार्वण	पार्वणीभिः	ADJ;INS;FEM;PL
सोम	सोमेभ्यः	ADJ;DAT;MASC;PL
हृद्	हृत्	N;VOC;SG
अग्न्याधेय	अग्न्याधेयाभ्याम्	N;DAT;DU
अजाति	अजातीनाम्	N;GEN;PL
अगस्ति	अगस्तिभ्याम्	N;DAT;DU
सर्प	सर्पीषु	ADJ;LOC;FEM;PL
तर्क	तर्के	N;NOM;DU
स्वस्ति	स्वस्तीनि	N;ACC;PL
तरु	तरुभ्याम्	ADJ;ABL;DU
लोक	लोकयोः	N;LOC;DU
स्वरित	स्वरितेभ्यः	ADJ;ABL;NEUT;PL
अथर्वाङ्गिरस	अथर्वाङ्गिरसाभ्याम्	ADJ;ABL;NEUT;DU
गृह	गृहे	N;VOC;DU
सहित	सहितेभ्यः	ADJ;ABL;NEUT;PL
इच्छा	इच्छायाः	N;ABL;SG
उदन्	उद्नाम्	N;GEN;PL
सोम	सोमेभ्यः	ADJ;ABL;MASC;PL
सत्य	सत्यस्य	N;GEN;SG
साति	सत्याः	N;GEN;SG
पर्जन्य	पर्जन्ययोः	N;GEN;DU
कृष्ण	कृष्णौ	ADJ;NOM;MASC;DU
काव्य	काव्यानाम्	ADJ;GEN;MASC;PL
सर्प	सर्पयोः	ADJ;GEN;NEUT;DU
घटना	घटनायै	N;DAT;SG
रति	रतेः	N;ABL;SG
ह्रस्व	ह्रस्वौ	ADJ;VOC;MASC;DU
नाटक	नाटकेषु	ADJ;LOC;MASC;PL
दुग्ध	दुग्धा	ADJ;NOM;FEM;SG
नलद	नलदानि	ADJ;ACC;FEM;PL
वातिगगम	वातिगगमैः	N;INS;PL
बुध्न	बुध्नस्य	ADJ;GEN;MASC;SG
यातु	यातोः	N;ABL;SG
विशाल	विशालम्	ADJ;ACC;SG
शिल्पशाला	शिल्पशालाम्	N;ACC;SG
पार्वण	पार्वणेभ्यः	ADJ;DAT;NEUT;PL
कच्छ	कच्छैः	N;INS;PL
श्यामा	श्यामाः	N;NOM;PL
जन	जनेन	ADJ;INS;MASC;SG
ग्रन्थ	ग्रन्थान्	N;ACC;PL
प्रथम	प्रथमे	ADJ;LOC;NEUT;SG
अमल	अमलाः	ADJ;ACC;FEM;PL
समुद्र	समुद्रम्	N;ACC;SG
महाकवि	महाकविषु	N;LOC;PL
सुन्दर	सुन्दर्या	ADJ;INS;SG
पार्वण	पार्वणीभ्यः	ADJ;DAT;FEM;PL
वल्श	वल्शेषु	N;LOC;PL
अन्त	अन्तौ	N;ACC;DU
वसु	वसुभिः	ADJ;INS;PL
प्रहसन	प्रहसनेभ्यः	N;DAT;PL
सोम	सोमानि	ADJ;ACC;NEUT;PL
ग्रन्थ	ग्रन्थौ	N;ACC;DU
अक्षता	अक्षतासु	N;LOC;PL
ह्रस्व	ह्रस्वाम्	ADJ;ACC;FEM;SG
तर्का	तर्काभ्याम्	N;ABL;DU
उल्ब	उल्बानि	N;ACC;PL
तनू	तनूभ्यः	N;ABL;PL
सुन्दर	सुन्दरीः	ADJ;ACC;PL
तर्कु	तर्कुणः	N;ABL;SG
अन्ताराष्ट्रिय	अन्ताराष्ट्रिययोः	ADJ;LOC;NEUT;DU
श्वसुर	श्वसुरयोः	N;LOC;DU
पर्जन्य	पर्जन्यौ	N;ACC;DU
पुष्कर	पुष्कर	N;VOC;SG
स्वस्ति	स्वस्ति	N;ACC;SG
नक्ति	नक्तेः	N;GEN;SG
जुष्ट	जुष्टे	ADJ;NOM;NEUT;DU
अभ्र	अभ्रान्	N;ACC;PL
शिल्पशाला	शिल्पशालानाम्	N;GEN;PL
वर्षा	वर्षाभ्याम्	N;INS;DU
पार्वण	पार्वणे	ADJ;VOC;NEUT;DU
अमल	अमलाभ्याम्	ADJ;DAT;FEM;DU
पार्वण	पार्वणेन	ADJ;INS;NEUT;SG
अभ्र	अभ्रेण	N;INS;SG
प्रहार	प्रहाराभ्याम्	N;DAT;DU
जन	जन्याः	ADJ;GEN;FEM;SG
घोष	घोषौ	N;VOC;DU
सुन्दर	सुन्दरौ	ADJ;ACC;DU
तपस्	तपःसु	N;LOC;PL
बह्वृच	बह्वृच्याम्	N;LOC;SG
स्वतन्त्र	स्वतन्त्रानाम्	ADJ;GEN;FEM;PL
नेपथ्य	नेपथ्ये	N;VOC;DU
अनुस्वार	अनुस्वारौ	N;NOM;DU
सूक्त	सूक्ताभ्याम्	ADJ;ABL;MASC;DU
श्याम	श्यामेभ्यः	ADJ;ABL;NEUT;PL
गोपाल	गोपालयोः	N;GEN;DU
स्वेद	स्वेदेन	ADJ;INS;MASC;SG
राज्य	राज्य	ADJ;VOC;MASC;SG
नड	नडेभ्यः	N;DAT;PL
नारायण	नारायणाभ्याम्	ADJ;DAT;NEUT;DU
प्रार्थना	प्रार्थनाभ्याम्	N;INS;DU
कष्ट	कष्टौ	N;ACC;DU
अकृत्य	अकृत्यैः	N;INS;PL
मन्दर	मन्दरौ	ADJ;NOM;MASC;DU
समाधि	समाध्योः	N;LOC;DU
दर्शन	दर्शनात्	N;ABL;SG
समाधि	समाधिः	N;NOM;SG
बालक	बालकाः	N;NOM;PL
आम्र	आम्राः	N;VOC;PL
रूपक	रूपकेभ्यः	ADJ;DAT;MASC;PL
तद्धित	तद्धितस्य	N;GEN;SG
पूर	पूराभ्याम्	ADJ;ABL;MASC;DU
रुधिर	रुधिराणि	ADJ;VOC;NEUT;PL
अक्ष	अक्षम्	N;ACC;SG
चतुरङ्ग	चतुरङगाभ्याम्	ADJ;DAT;NEUT;DU
देवभाषा	देवभाषाभ्यः	N;ABL;PL
उक्त	उक्ताभ्याम्	ADJ;INS;FEM;DU
धर्म	धर्मात्	N;ABL;SG
बोधि	बोधिभ्याम्	ADJ;INS;MASC;DU
सङ्गीत	सङ्गीतेभ्यः	N;DAT;PL
त्रिज्या	त्रिज्यानाम्	N;GEN;PL
बुद्धि	बुद्ध्योः	N;LOC;DU
राज्ञी	राज्ञ्यौ	N;VOC;DU
वृत्त	वृत्ताभ्यः	ADJ;ABL;FEM;PL
आर्य	आर्यौ	ADJ;VOC;MASC;DU
अकूपार	अकूपाराः	ADJ;VOC;MASC;PL
विद्याचण	विद्याचणेषु	ADJ;LOC;MASC;PL
परा	पराभ्यः	N;DAT;PL
पराजय	पराजयाय	N;DAT;SG
दीर्घ	दीर्घेषु	ADJ;LOC;MASC;PL
गुरु	गुरुभ्याम्	N;DAT;DU
प्रान्त	प्रान्तौ	ADJ;VOC;MASC;DU
साहस	साहसेभ्यः	N;DAT;PL
बिन्दु	बिन्दूनि	N;VOC;PL
उक्त	उक्ताभ्याम्	ADJ;ABL;FEM;DU
नट	नटैः	N;INS;PL
कृपाण	कृपाणौ	N;ACC;DU
उद्यान	उद्यानौ	N;VOC;DU
संस्कृत	संस्कृतौ	ADJ;VOC;MASC;DU
पवमान	पवमानायाम्	ADJ;LOC;FEM;SG
दुर्जन	दुर्जने	ADJ;LOC;NEUT;SG
तप	तपस्य	ADJ;GEN;NEUT;SG
चक्रवात	चक्रवातेभ्यः	N;ABL;PL
अंशक	अंशिकाभ्यः	ADJ;DAT;FEM;PL
उपरम	उपरमाभ्याम्	N;INS;DU
फल	फलाभ्याम्	N;ABL;DU
प्रतिष्ठा	प्रतिष्ठाभ्यः	N;DAT;PL
नाचिकेत	नाचिकेतीषु	ADJ;LOC;FEM;PL
गुप्त	गुप्तस्य	ADJ;GEN;MASC;SG
जानु	जानुनः	N;ABL;SG
अग्निहोत्र	अग्निहोत्रेषु	ADJ;LOC;MASC;PL
दक्षिण	दक्षिणात्	ADJ;ABL;MASC;SG
शोभा	शोभे	N;NOM;DU
शत्रु	शत्रुणा	N;INS;SG
अपभ्रंश	अपभ्रंशेभ्यः	N;DAT;PL
चातुर्मास्य	चातुर्मास्यस्य	ADJ;GEN;MASC;SG
मन्त्र	मन्त्रेभ्यः	N;ABL;PL
विद्याचण	विद्याचणे	ADJ;LOC;MASC;SG
स्वयंवर	स्वयंवरे	ADJ;VOC;FEM;DU
कान्त	कान्ताय	N;DAT;SG
बुद्धि	बुद्धिः	N;NOM;SG
प्रयत्न	प्रयत्नाभ्याम्	N;INS;DU
रुधिर	रुधिरे	ADJ;ACC;NEUT;DU
नामन्	नामभ्यः	N;DAT;PL
साध्य	साध्ये	ADJ;VOC;NEUT;DU
प्रतिज्ञा	प्रतिज्ञासु	N;LOC;PL
भण्टाकी	भण्टाकीभ्याम्	N;DAT;DU
धर्म	धर्मेण	N;INS;SG
भार्या	भार्ययोः	N;LOC;DU
नेपथ्य	नेपथ्याभ्याम्	N;DAT;DU
राजकुमार	राजकुमारे	N;LOC;SG
अबला	अबलानाम्	N;GEN;PL
मधुर	मधुरयोः	ADJ;LOC;FEM;DU
संस्कार	संस्काराभ्याम्	N;INS;DU
पुण्डरीक	पुण्डरीके	N;VOC;DU
पूर	पूरात्	ADJ;ABL;MASC;SG
मुण्ड	मुण्डस्य	ADJ;GEN;MASC;SG
पाल	पालम्	N;NOM;SG
शिष्य	शिष्यात्	N;ABL;SG
बह्वृच	बह्वृचानि	ADJ;ACC;PL
सूक्त	सूक्ते	ADJ;VOC;FEM;DU
यज्ञ	यज्ञाभ्याम्	N;DAT;DU
पुलस्ति	पुलस्तयः	ADJ;VOC;FEM;PL
ब्रह्मोद्य	ब्रह्मोद्ये	ADJ;ACC;NEUT;DU
बल	बलैः	ADJ;INS;NEUT;PL
बह्वृच	बह्वृचाभ्यः	ADJ;ABL;PL
स्वेद	स्वेदस्य	ADJ;GEN;MASC;SG
स्वयंवर	स्वयंवरैः	ADJ;INS;NEUT;PL
बल	बलाः	ADJ;VOC;FEM;PL
पुलक	पुलकान्	N;ACC;PL
आशु	आश्वाम्	ADJ;LOC;FEM;SG
अंहु	अंह्वोः	ADJ;GEN;FEM;DU
नाथ	नाथानाम्	ADJ;GEN;FEM;PL
साधन	साधन्यः	ADJ;VOC;PL
भारतवर्ष	भारतवर्षे	N;LOC;SG
दोष	दोषाः	N;NOM;PL
पुर	पुराणाम्	ADJ;GEN;NEUT;PL
राशिचक्र	राशिचक्राणि	N;NOM;PL
वैश्वानर	वैश्वानराभ्याम्	ADJ;ABL;NEUT;DU
दुन्दुभि	दुन्दुभििः	N;NOM;SG
शाखा	शाखया	N;INS;SG
अध्वर्यु	अध्वर्यो	N;VOC;SG
यज्ञ	यज्ञेषु	N;LOC;PL
श्याम	श्यामे	ADJ;NOM;NEUT;DU
कन्या	कन्यायाः	N;GEN;SG
साधार	साधारैः	ADJ;INS;MASC;PL
भर्ग	भर्गाभ्याम्	N;DAT;DU
सूक्त	सूक्त	ADJ;VOC;NEUT;SG
द्वीप	द्वीपौ	N;VOC;DU
कुल	कुलौ	N;VOC;DU
साधारण	साधारणान्	ADJ;ACC;PL
अंहु	अंहुनोः	ADJ;LOC;NEUT;DU
उखा	उखाभ्यः	N;DAT;PL
ऊर्ध्व	ऊर्ध्वम्	ADJ;NOM;NEUT;SG
वृष	वृषाणि	N;VOC;PL
बह्वृच	बह्वृचे	ADJ;LOC;SG
स्वेद	स्वेदे	ADJ;LOC;MASC;SG
वाद	वादया	ADJ;INS;FEM;SG
राजि	राज्या	N;INS;SG
विष्कम्भ	विष्कम्भाः	N;NOM;PL
अद्रि	अद्र्योः	N;LOC;DU
युद्ध	युद्धाभ्याम्	ADJ;DAT;NEUT;DU
आद	आदौ	N;ACC;DU
उद्यान	उद्यानाभ्याम्	N;DAT;DU
दारु	दारुणा	N;INS;SG
प्राच्य	प्राच्याभ्याम्	ADJ;DAT;MASC;DU
मेध	मेधः	N;NOM;SG
हति	हतिभ्याम्	N;INS;DU
चन्द्र	चन्द्राणि	ADJ;ACC;NEUT;PL
अकूपार	अकूपारेभ्यः	ADJ;ABL;NEUT;PL
वर्ष	वर्षाभिः	ADJ;INS;FEM;PL
मध्यम	मध्यमेभ्यः	ADJ;ABL;NEUT;PL
शिष्य	शिष्यौ	N;NOM;DU
दुर्जन	दुर्जनाभ्याम्	ADJ;DAT;FEM;DU
अबुध्न	अबुध्नाभ्याम्	ADJ;ABL;FEM;DU
वृद्धि	वृद्धिभ्याम्	N;INS;DU
विधान	विधान	ADJ;VOC;NEUT;SG
प्रारम्भ	प्रारम्भस्य	N;GEN;SG
जनिमन्	जनिमभ्याम्	N;INS;DU
विदूषक	विदूषक	ADJ;VOC;MASC;SG
मृत	मृतायै	ADJ;DAT;FEM;SG
सिद्धार्थ	सिद्धार्थयोः	ADJ;LOC;NEUT;DU
परा	परे	N;VOC;DU
आवसथ्य	आवसथ्यौ	ADJ;NOM;MASC;DU
क्षिति	क्षिती	N;NOM;DU
सवन	सवनाभ्यः	ADJ;DAT;PL
ब्राह्मण	ब्राह्मणम्	ADJ;ACC;NEUT;SG
सिद्ध	सिद्धान्	ADJ;ACC;MASC;PL
आर्य	आर्याभ्याम्	ADJ;DAT;NEUT;DU
नाटिका	नाटिका	N;NOM;SG
संधि	संधिभ्याम्	ADJ;DAT;FEM;DU
श्वश्रू	श्वश्रूभ्याम्	N;ABL;DU
प्रान्त	प्रान्तानि	ADJ;VOC;FEM;PL
वारि	वारीणि	N;VOC;PL
वारि	वारिभिः	N;INS;PL
देवयान	देवयानाभ्याम्	ADJ;INS;FEM;DU
मिथुन	मिथुनानि	ADJ;NOM;NEUT;PL
मूढ	मूढे	N;LOC;SG
वैवाहिक	वैवाहिकान्	ADJ;ACC;MASC;PL
बोधि	बोध्यै	ADJ;DAT;FEM;SG
नीचामेढ्र	नीचामेढ्रैः	N;INS;PL
लघु	लघू	ADJ;VOC;DU
उक्त	उक्तात्	ADJ;ABL;MASC;SG
सुख	सुखाभ्याम्	ADJ;DAT;FEM;DU
वर्ण	वर्णाभ्याम्	N;ABL;DU
शलभ	शलभैः	N;INS;PL
वर्ष	वर्षाभ्याम्	ADJ;DAT;FEM;DU
देवर	देवराभ्याम्	N;DAT;DU
मानव	मानवेभ्यः	N;ABL;PL
विशेष	विशेषाभ्याम्	ADJ;INS;NEUT;DU
उच्च	उच्चे	ADJ;NOM;FEM;DU
बल	बलाः	ADJ;VOC;MASC;PL
मिथुन	मिथुनाभ्याम्	ADJ;ABL;NEUT;DU
कल्य	कल्याय	ADJ;DAT;MASC;SG
विद्याधरी	विद्याधरीभ्याम्	N;ABL;DU
सूक्त	सूक्तेभ्यः	ADJ;ABL;MASC;PL
नवोदय	नवोदये	ADJ;ACC;NEUT;DU
खिलकाण्ड	खिलकाण्डैः	N;INS;PL
मल	मलस्य	ADJ;GEN;NEUT;SG
पाप	पापीभ्यः	N;DAT;PL
जनि	जनी	N;ACC;DU
खिलकाण्ड	खिलकाण्डे	N;NOM;DU
व्याकरण	व्याकरणाभ्याम्	N;DAT;DU
फेन	फेनाय	N;DAT;SG
सहस्र	सहस्राणाम्	ADJ;GEN;MASC;PL
बोधि	बोधिभ्यः	ADJ;DAT;FEM;PL
नयन	नयनयोः	N;GEN;DU
प्रधान	प्रधानायाः	ADJ;GEN;FEM;SG
कर्म	कर्मैः	N;INS;PL
मठ	मठाः	N;NOM;PL
सुम्न	सुम्ने	ADJ;ACC;NEUT;DU
नर	नरम्	N;ACC;SG
साधार	साधाराभ्याम्	ADJ;INS;MASC;DU
नदी	नदीम्	N;ACC;SG
ज्ञानकाण्ड	ज्ञानकाण्डानि	N;VOC;PL
विहग	विहगौ	N;ACC;DU
राज्य	राज्येषु	ADJ;LOC;NEUT;PL
बह्वृच	बह्वृचेभ्यः	ADJ;ABL;PL
ध्यान	ध्यानाभ्याम्	N;ABL;DU
वैतान	वैतान्यौ	ADJ;NOM;FEM;DU
वैश्य	वैश्यौ	ADJ;VOC;MASC;DU
युद्ध	युद्धम्	ADJ;ACC;NEUT;SG
कुशीलव	कुशीलवात्	N;ABL;SG
जीवित	जीविते	ADJ;NOM;NEUT;DU
कुण्डलिनी	कुण्डलिनीभ्याम्	N;ABL;DU
मृग	मृगौ	N;ACC;DU
वैश्वानर	वैश्वानर	ADJ;VOC;MASC;SG
अवि	अविना	N;INS;SG
पण्डित	पण्डित	ADJ;VOC;NEUT;SG
कवि	कविम्	ADJ;ACC;MASC;SG
नक्षत्र	नक्षतर	N;VOC;SG
साधार	साधारायाम्	ADJ;LOC;FEM;SG
वेदी	वेदीभिः	N;INS;PL
नीतिशास्त्र	नीतिशास्त्रयोः	N;GEN;DU
सप्ताह	सप्ताहाभ्याम्	N;INS;DU
वैतथ्य	वैतथ्यानि	ADJ;VOC;NEUT;PL
सङ्गीत	सङ्गीते	N;LOC;SG
दुःस्वप्न	दुःस्वप्नयोः	N;GEN;DU
परा	पराभ्याम्	N;INS;DU
नेत्र	नेत्राभ्याम्	N;INS;DU
कपि	कपे	ADJ;VOC;MASC;SG
सूक्त	सूक्ते	ADJ;ACC;FEM;DU
अङ्गुलि	अङ्गुले	N;VOC;SG
वर्ण	वर्णाः	N;VOC;PL
दृष्टि	दृष्टिभ्याम्	N;ABL;DU
प्रतिज्ञा	प्रतिज्ञाभ्यः	N;ABL;PL
आधार	आधाराभ्याम्	N;ABL;DU
संधि	संधिभ्याम्	ADJ;DAT;NEUT;DU
तप	तपयोः	ADJ;LOC;MASC;DU
पठन	पठन	N;VOC;SG
क्षेत्र	क्षेत्रेषु	N;LOC;PL
ब्राह्म	ब्राह्मि	ADJ;VOC;FEM;SG
कर्कट	कर्कटेभ्यः	N;ABL;PL
धेनु	धेनू	N;VOC;DU
गञ्जा	गञ्जाः	N;NOM;PL
मण्डल	मण्डलायै	ADJ;DAT;FEM;SG
शिष्य	शिष्यः	N;NOM;SG
सङ्गीत	सङ्गीत	N;VOC;SG
पाल	पालाभ्याम्	N;DAT;DU
काम्बोज	काम्बोजौ	N;VOC;DU
कनीन	कनीनेभ्यः	ADJ;DAT;NEUT;PL
जय	जयेषु	N;LOC;PL
गर्भ	गर्भैः	N;INS;PL
सूकर	सूकरौ	N;VOC;DU
नान्दी	नान्दीः	N;ACC;PL
संतोष	संतोषानाम्	N;GEN;PL
अक्ष	अक्षान्	N;ACC;PL
नक्षत्र	नक्षतरम्	N;NOM;SG
भर्ग	भर्गेण	N;INS;SG
कुशीलव	कुशीलवौ	N;NOM;DU
चाप	चापैः	N;INS;PL
मनुष्ययज्ञ	मनुष्ययज्ञाभ्याम्	N;DAT;DU
स्तन	स्तनौ	N;ACC;DU
ऋद्धि	ऋद्ध्याम्	N;LOC;SG
सिद्ध	सिद्धात्	ADJ;ABL;NEUT;SG
नाथ	नाथस्य	ADJ;GEN;FEM;SG
द्वेष	द्वेषेभ्यः	N;DAT;PL
कृमि	कृम्याः	N;GEN;SG
खिल	खिलाः	ADJ;NOM;NEUT;PL
गो	गोः	N;GEN;SG
रुधिर	रुधिरात्	ADJ;ABL;MASC;SG
आशा	आशयोः	N;GEN;DU
डमरु	डमरुः	N;NOM;SG
काण्ड	काण्डैः	N;INS;PL
फल	फलम्	N;ACC;SG
प्रयत्न	प्रयत्नाः	N;VOC;PL
ऋष्व	ऋष्वेभ्यः	ADJ;DAT;NEUT;PL
महादव	महादवेन	N;INS;SG
पण्डित	पण्डितौ	ADJ;VOC;MASC;DU
नामन्	नामभ्याम्	N;DAT;DU
सुम्न	सुम्नौ	ADJ;ACC;MASC;DU
देवदासी	देवदासीषु	N;LOC;PL
कुमार	कुमाराभ्याम्	N;INS;DU
आकाश	आकाश	N;VOC;SG
पितृयाण	पितृयाणात्	ADJ;ABL;NEUT;SG
दीर्घ	दीर्घयोः	ADJ;GEN;MASC;DU
मन्दार	मन्दारैः	N;INS;PL
तद्धित	तद्धितेभ्यः	N;DAT;PL
भूमि	भूम्याः	N;ABL;SG
आर्य	आर्ये	ADJ;VOC;NEUT;DU
अष्टक	अष्टकौ	ADJ;VOC;MASC;DU
रुधिर	रुधिरैः	ADJ;INS;NEUT;PL
हिम	हिमयोः	ADJ;LOC;NEUT;DU
अकृत्य	अकृत्याभ्याम्	N;DAT;DU
माहात्म्य	माहात्म्यम्	N;ACC;SG
साध्य	साध्यौ	ADJ;NOM;MASC;DU
सुम्न	सुम्नाः	ADJ;NOM;MASC;PL
लोचन	लोचनेन	N;INS;SG
घूक	घूकस्य	N;GEN;SG
भारत	भारतीभिः	ADJ;INS;FEM;PL
साधन	साधनाभिः	ADJ;INS;PL
ऋषि	ऋषी	N;NOM;DU
विपक्ष	विपक्षस्य	ADJ;GEN;MASC;SG
मठ	मठेभ्यः	N;DAT;PL
उच्च	उच्चयोः	ADJ;GEN;NEUT;DU
जाङ्गल	जाङ्गले	ADJ;NOM;NEUT;DU
वीर	वीरे	N;ACC;DU
जुहू	जुह्वै	N;DAT;SG
सहस्र	सहस्रीणाम्	ADJ;GEN;NEUT;PL
प्रजापति	प्रजापतयः	N;VOC;PL
पार्वती	पार्वतीभ्याम्	N;DAT;DU
पण्डित	पण्डितौ	ADJ;NOM;MASC;DU
व्यञ्जन	व्यञ्जनम्	ADJ;NOM;NEUT;SG
सुराकार	सुराकार	N;VOC;SG
अग्निहोत्र	अग्निहोत्रः	ADJ;NOM;MASC;SG
प्रारम्भ	प्रारम्भानाम्	N;GEN;PL
प्रस्ताव	प्रस्तावौ	N;ACC;DU
सिद्धार्थ	सिद्धार्थाभ्यः	ADJ;DAT;FEM;PL
नवोदय	नवोदयाभ्याम्	ADJ;INS;NEUT;DU
वादक	वादकस्य	N;GEN;SG
विधान	विधानीभ्यः	ADJ;ABL;FEM;PL
अगद	अगदाय	N;DAT;SG
क्ष	क्षयोः	N;LOC;DU
अंह्रि	अंह्रिभिः	N;INS;PL
ऊर्ध्व	ऊर्ध्वायै	ADJ;DAT;FEM;SG
जय	जयात्	N;ABL;SG
मल	मलाभ्याम्	ADJ;ABL;MASC;DU
अर्जुन	अर्जुनेन	N;INS;SG
मन्यु	मन्यू	N;VOC;DU
राशिचक्र	राशिचक्राणि	N;ACC;PL
मार्ग	मार्गौ	N;VOC;DU
ईषा	ईषायाः	N;ABL;SG
चन्द्र	चन्द्राय	ADJ;DAT;MASC;SG
पानीय	पानीयैः	N;INS;PL
पितृयाण	पितृयाणौ	ADJ;VOC;MASC;DU
नवोदित	नवोदितेभ्यः	ADJ;DAT;NEUT;PL
सूक्त	सूक्तैः	ADJ;INS;MASC;PL
धातृ	धातुः	N;ABL;SG
पानीय	पानीयाभ्याम्	N;DAT;DU
ऋद्धि	ऋद्ध्याः	N;GEN;SG
आथर्वण	आथर्वणानाम्	ADJ;GEN;MASC;PL
जनिमन्	जनिम्नः	N;ABL;SG
भारत	भारतौ	ADJ;ACC;MASC;DU
द्वीप	द्वीप	N;VOC;SG
कृमि	कृमिभ्यः	N;DAT;PL
पारग	पारगाम्	ADJ;ACC;FEM;SG
कल्य	कल्यैः	ADJ;INS;MASC;PL
ओषधि	ओषधी	N;NOM;DU
वंश	वंशे	N;ACC;DU
अहर्गण	अहर्गणस्य	N;GEN;SG
तटाक	तटाकाः	N;NOM;PL
आवास	आवासान्	N;ACC;PL
ब्रह्मवेद	ब्रह्मवेदस्य	N;GEN;SG
व्यञ्जन	व्यञ्जनाम्	ADJ;ACC;FEM;SG
गुप्त	गुप्ते	ADJ;NOM;NEUT;DU
चन्द्र	चन्द्राभ्याम्	ADJ;INS;FEM;DU
भर्ग	भर्गेभ्यः	N;ABL;PL
जीवन्मुक्ति	जिवन्मुक्तिभ्यः	N;DAT;PL
वैश्वानर	वैश्वानरौ	ADJ;NOM;MASC;DU
विपक्ष	विपक्षयोः	ADJ;GEN;NEUT;DU
मध्यम	मध्यमाभ्यः	ADJ;ABL;FEM;PL
अग्निहोत्र	अग्निहोत्रेभ्यः	ADJ;DAT;MASC;PL
विधान	विधानानि	ADJ;VOC;NEUT;PL
अग्निष्टोम	अग्निष्टोमानाम्	N;GEN;PL
चन्द्र	चन्द्रेभ्यः	ADJ;DAT;MASC;PL
चातुर्मास्य	चातुर्मास्ये	ADJ;LOC;MASC;SG
वृक	वृकम्	N;ACC;SG
यान	यानानि	N;ACC;PL
अकन्या	अकन्याम्	N;ACC;SG
अकूपार	अकूपारे	ADJ;VOC;FEM;DU
पति	पतेः	N;ABL;SG
कृमि	कृमयः	N;VOC;PL
जाङ्गल	जाङ्गलाभ्याम्	ADJ;DAT;MASC;DU
संस्कृत	संस्कृतायाः	ADJ;ABL;FEM;SG
चुम्बन	चुम्बनेषु	N;LOC;PL
तुच्छ	तुच्छाभ्याम्	ADJ;DAT;MASC;DU
ब्राह्मण	ब्राह्मणाभ्याम्	ADJ;INS;MASC;DU
महादव	महादवौ	N;VOC;DU
कृपाण	कृपाणेभ्यः	N;DAT;PL
मेष	मेष	N;VOC;SG
कवि	कव्याम्	ADJ;LOC;FEM;SG
प्लुषि	प्लुषे	N;VOC;SG
वृत्त	वृत्तयोः	ADJ;GEN;MASC;DU
ज्या	ज्या	N;NOM;SG
अद्रि	अद्रीन्	N;ACC;PL
प्रतिबुद्ध	प्रतिबद्धाभ्याम्	ADJ;DAT;FEM;DU
अगुरु	अगुरूनाम्	N;GEN;PL
अंहु	अंहुः	ADJ;NOM;MASC;SG
उद्गूर्ण	उद्गूर्णैः	ADJ;INS;MASC;PL
हृदय	हृदयाभ्याम्	ADJ;ABL;FEM;DU
शलभ	शलभौ	N;ACC;DU
रयि	रयीनि	ADJ;VOC;NEUT;PL
ऋष्व	ऋष्वाभ्याम्	ADJ;DAT;MASC;DU
अक्ष	अक्षाः	N;NOM;PL
साधारण	साधारणस्य	ADJ;GEN;SG
प्रतिष्ठा	प्रतिष्ठे	N;NOM;DU
अग्निष्टोम	अग्निष्टोमेभ्यः	N;ABL;PL
चूर्ण	चूर्णयोः	ADJ;LOC;FEM;DU
गुप्त	गुप्ते	ADJ;LOC;MASC;SG
सामयाचारिक	सामयाचारिकयोः	ADJ;GEN;NEUT;DU
आथर्वण	आथर्वणीषु	ADJ;LOC;FEM;PL
आचार	आचारौ	N;NOM;DU
माधवीय	माधवीये	ADJ;LOC;NEUT;SG
वैवाहिक	वैवाहिकाय	ADJ;DAT;MASC;SG
आश्रम	आश्रमस्य	N;GEN;SG
नारायण	नारायणीभिः	ADJ;INS;FEM;PL
वाद	वादानि	ADJ;ACC;NEUT;PL
उपाख्यान	उपाख्याने	N;VOC;DU
अगाध	अगाधैः	N;INS;PL
नीड	नीडानि	N;NOM;PL
प्रताप	प्रतापयोः	N;LOC;DU
तोय	तोयात्	N;ABL;SG
अकृत्य	अकृत्येभ्यः	N;DAT;PL
बालातप	बालातपाय	N;DAT;SG
धातृ	धातर्	N;VOC;SG
वेदी	वेद्यः	N;VOC;PL
आखु	आक्हुभिः	N;INS;PL
युद्ध	युद्धौ	ADJ;NOM;MASC;DU
कुटुम्ब	कुटुम्बानि	N;ACC;PL
ईर्म	ईर्मानाम्	N;GEN;PL
मुण्ड	मुण्डा	ADJ;DAT;NEUT;SG
कृपाण	कृपाणेन	N;INS;SG
ब्रह्मोद्य	ब्रह्मोद्यानाम्	ADJ;GEN;FEM;PL
खण्ड	खण्डात्	N;ABL;SG
नड	नडेषु	N;LOC;PL
अकर्मक	अकर्मकायाः	ADJ;GEN;FEM;SG
हल	हलान्	N;ACC;PL
वृत्त	वृत्ता	ADJ;NOM;FEM;SG
चूर्ण	चूर्णात्	ADJ;ABL;NEUT;SG
शलभ	शलभाभ्याम्	N;INS;DU
अनुराग	अनुरागैः	N;INS;PL
व्यञ्जन	व्यञ्जनाभ्याम्	ADJ;INS;MASC;DU
मल	मलेषु	ADJ;LOC;MASC;PL
समवाय	समवायेन	N;INS;SG
वैश्य	वैश्ये	ADJ;VOC;FEM;DU
चूर्ण	चूर्णाभ्याम्	ADJ;DAT;FEM;DU
शिव	शिवाभ्याम्	ADJ;INS;FEM;DU
साधकत्व	साधकत्वा	N;DAT;SG
दिति	दितीः	N;ACC;PL
अङ्घ्रि	अङ्घ्रिम्	N;ACC;SG
नक्त	नक्तेन	N;INS;SG
ईशान	ईशानाभ्याम्	ADJ;DAT;MASC;DU
महादव	महादवाः	N;NOM;PL
गर्जन	गर्जनानाम्	N;GEN;PL
द्वादशाह	द्वादशाहाः	ADJ;VOC;MASC;PL
मानव	मानवौ	N;VOC;DU
शर्करा	शर्कराभ्याम्	N;DAT;DU
अकृत्य	अकृत्यानि	N;ACC;PL
संस्कृत	संस्कृताभ्याम्	ADJ;INS;FEM;DU
कारागार	कारागारम्	N;NOM;SG
मनु	मनोः	ADJ;ABL;FEM;SG
अन्ति	अन्तिभिः	N;INS;PL
जनिमन्	जनिम्नि	N;LOC;SG
ब्राह्म	ब्राह्मम्	ADJ;ACC;NEUT;SG
न्यग्रोध	न्यग्रोधौ	N;ACC;DU
कर्मकाण्ड	कर्मकाण्डाभ्याम्	N;INS;DU
पाप	पापानि	ADJ;NOM;PL
वैतान	वैतानाः	ADJ;VOC;MASC;PL
असि	असये	N;DAT;SG
सखि	सख्युः	N;GEN;SG
तित्तिरि	तित्तिरिम्	N;ACC;SG
जाङ्गल	जाङ्गलाभ्याम्	ADJ;DAT;NEUT;DU
बाल	बालौ	N;ACC;DU
किशोर	किशोराः	N;NOM;PL
तल्प	तल्पेभ्यः	N;DAT;PL
चातुर्मास्य	चातुर्मास्यम्	ADJ;NOM;NEUT;SG
नाचिकेत	नाचिकेतेभ्यः	ADJ;DAT;MASC;PL
तनूज	तनूजाभ्याम्	ADJ;ABL;FEM;DU
देश	देशयोः	N;LOC;DU
आथर्वण	आथर्वणम्	ADJ;NOM;NEUT;SG
असुर	असुरयोः	N;GEN;DU
साधन	साधना	N;DAT;SG
अदृष्ट	अदृष्टाभ्याम्	ADJ;DAT;NEUT;DU
हिम	हिमाभ्याम्	ADJ;INS;MASC;DU
गोपुर	गोपुरे	N;NOM;DU
शङ्ख	शङ्खैः	N;INS;PL
महादव	महादवौ	N;ACC;DU
शिव	शिवैः	ADJ;INS;MASC;PL
अदृष्ट	अदृष्टाः	ADJ;VOC;FEM;PL
पुरु	पुरौ	ADJ;LOC;MASC;SG
पुत्र	पुत्राभ्याम्	N;INS;DU
कर्ण	कर्णः	N;NOM;SG
साधु	साधुषु	ADJ;LOC;NEUT;PL
अकूपार	अकूपाराभ्याम्	ADJ;ABL;NEUT;DU
प्रधान	प्रधानम्	ADJ;ACC;NEUT;SG
बुद्धि	बुद्धिम्	N;ACC;SG
स्मृति	स्मृतिभ्याम्	N;ABL;DU
मुण्ड	मुण्डम्	ADJ;ACC;NEUT;SG
अद्रि	अद्रौ	N;LOC;SG
नाटिका	नाटिके	N;NOM;DU
घृणा	घृणायाम्	N;LOC;SG
विधान	विधानेन	ADJ;INS;MASC;SG
वृद्धि	वृद्ध्या	N;INS;SG
पण्डित	पण्डितानि	ADJ;ACC;NEUT;PL
वारि	वारिषु	N;LOC;PL
विशेष	विशेषाभ्याम्	ADJ;INS;MASC;DU
प्रधान	प्रधानस्य	ADJ;GEN;MASC;SG
वशगा	वशगाः	N;VOC;PL
चुम्बन	चुम्बनेभ्यः	N;DAT;PL
मन्दर	मन्दरयोः	ADJ;GEN;FEM;DU
वैतथ्य	वैतथ्याः	ADJ;VOC;MASC;PL
मल	मलौ	ADJ;ACC;MASC;DU
राम	रामान्	ADJ;ACC;MASC;PL
रूपक	रूपका	ADJ;DAT;NEUT;SG
मृत	मृतान्	ADJ;ACC;MASC;PL
स्वर	स्वरम्	N;ACC;SG
साहस	साहसात्	N;ABL;SG
पितृयाण	पितृयाणा	ADJ;NOM;FEM;SG
आधार	आधारयोः	N;LOC;DU
अनुवाक	अनुवाकात्	N;ABL;SG
देश	देशेन	N;INS;SG
उद्गूर्ण	उद्गूर्णानि	ADJ;ACC;NEUT;PL
अगुरु	अगुरवे	N;DAT;SG
सामयाचारिक	सामयाचारिकाः	ADJ;VOC;FEM;PL
ऋत	ऋतानि	N;VOC;PL
व्याकरण	व्याकरणस्य	N;GEN;SG
वैश्वानर	वैश्वानराय	ADJ;DAT;MASC;SG
मन्दर	मन्दरयोः	ADJ;GEN;NEUT;DU
पृष्ठ	पृष्ठेभ्यः	N;DAT;PL
चन्दन	चन्दनाः	N;VOC;PL
नामन्	नामभ्याम्	N;ABL;DU
औषध	औषधे	N;NOM;DU
प्राच्य	प्राच्यान्	ADJ;ACC;MASC;PL
खिलकाण्ड	खिलकाण्डेभ्यः	N;ABL;PL
पराजय	पराजये	N;LOC;SG
उक्त	उक्त	ADJ;VOC;MASC;SG
मनु	मनुनः	ADJ;ABL;NEUT;SG
विधान	विधानम्	ADJ;ACC;NEUT;SG
रोटी	रोटीभ्याम्	N;ABL;DU
उद्यान	उद्यानाय	N;DAT;SG
प्रताप	प्रतापौ	N;VOC;DU
भण्टाकी	भण्टाक्योः	N;LOC;DU
पुरंधि	पुरंधिना	ADJ;INS;FEM;SG
अघ्न्या	अघ्न्याभ्याम्	N;INS;DU
सूक्त	सूक्ताभ्याम्	ADJ;INS;NEUT;DU
द्रुम	द्रुमाणाम्	N;GEN;PL
जाङ्गल	जाङ्गलात्	ADJ;ABL;NEUT;SG
खण्ड	खण्डौ	N;NOM;DU
समाधि	समाध्योः	N;GEN;DU
पाप	पाप्योः	N;LOC;DU
अङ्गुलि	अङ्गुलिभ्यः	N;ABL;PL
भिक्षु	भिक्षौ	N;LOC;SG
अकर्मक	अकर्मकात्	ADJ;ABL;NEUT;SG
तर्पण	तर्पणम्	ADJ;ACC;NEUT;SG
साध्य	साध्याय	ADJ;DAT;MASC;SG
वर्ण	वर्णः	N;NOM;SG
युद्ध	युद्धयोः	ADJ;LOC;NEUT;DU
सवन	सवनाः	ADJ;VOC;PL
नामकरण	नामकरणेभ्यः	N;ABL;PL
हल	हलम्	N;ACC;SG
क्षौर	क्षौरस्य	N;GEN;SG
हिरण्य	हिरण्ये	N;VOC;DU
दुन्दुभि	दुन्दुभियः	N;VOC;PL
पर्वसंग्रह	पर्वसंग्रहः	N;NOM;SG
शृगाल	सृगालाः	N;VOC;PL
साधन	साधनायाः	ADJ;GEN;SG
जनिमन्	जनिम्ने	N;DAT;SG
साधु	साध्व्यौ	ADJ;NOM;FEM;DU
विद्यापति	विद्यापतीन्	N;ACC;PL
चीन	चीनौ	N;ACC;DU
द्राक्षा	द्राक्षाः	N;VOC;PL
विरा	विराभ्यः	N;ABL;PL
हंस	हंसौ	N;NOM;DU
बाधा	बाधयोः	N;GEN;DU
अबुध्न	अबुध्नाभ्याम्	ADJ;DAT;FEM;DU
निर्णय	निर्णययोः	N;LOC;DU
चूर्ण	चूर्णाय	ADJ;DAT;MASC;SG
बिल	बिले	N;ACC;DU
विशेष	विशेषम्	ADJ;ACC;NEUT;SG
नाथ	नाथयोः	ADJ;GEN;MASC;DU
वंश	वंशेषु	N;LOC;PL
वरुण	वरुणाय	N;DAT;SG
हेलि	हेलिभ्याम्	N;ABL;DU
कनीन	कनीनेषु	ADJ;LOC;NEUT;PL
पार्ष्णि	पार्ष्णये	N;DAT;SG
उक्ति	उक्त्या	N;INS;SG
कनीन	कनीनायाः	ADJ;GEN;FEM;SG
अमृता	अमृतानाम्	N;GEN;PL
वर्ष	वर्षम्	ADJ;ACC;MASC;SG
घृण	घृणेषु	N;LOC;PL
कर्पर	कर्पर	N;VOC;SG
कनीन	कनीने	ADJ;LOC;NEUT;SG
अकूपार	अकूपार	ADJ;VOC;NEUT;SG
मन्दर	मन्दरेभ्यः	ADJ;ABL;MASC;PL
जुहू	जुहूनाम्	N;GEN;PL
लम्बक	लम्बकेषु	N;LOC;PL
चन्द्र	चन्द्राभ्यः	ADJ;ABL;FEM;PL
रूपक	रूपकम्	ADJ;ACC;NEUT;SG
द्वीप	द्वीपैः	N;INS;PL
साधारण	साधारणात्	N;ABL;SG
खिलकाण्ड	खिलकाण्डाभ्याम्	N;DAT;DU
असत्य	असत्यस्य	N;GEN;SG
अदृष्ट	अदृष्टायाम्	ADJ;LOC;FEM;SG
नक्त	नक्त	N;VOC;SG
जामित्र	जामित्रात्	N;ABL;SG
व्रत	व्रतानि	N;NOM;PL
पुत्र	पुत्रात्	N;ABL;SG
नाश	नाशाय	N;DAT;SG
अरित्र	अरित्रेषु	ADJ;LOC;MASC;PL
आधार	आधारान्	N;ACC;PL
पितृयाण	पितृयाणाभ्याम्	ADJ;INS;FEM;DU
प्रतिज्ञा	प्रतिज्ञाभ्याम्	N;INS;DU
अध्वर्यु	अध्वर्य्वोः	N;LOC;DU
मुख	मुखेषु	N;LOC;PL
ब्राह्म	ब्राह्म	ADJ;VOC;NEUT;SG
अधिकार	अधिकारेषु	N;LOC;PL
देवयान	देवयानैः	ADJ;INS;MASC;PL
रात्रि	रात्रिभ्यः	N;DAT;PL
प्रार्थना	प्रार्थने	N;NOM;DU
माधवीय	माधवीयाः	ADJ;ACC;FEM;PL
उद्गीथ	उद्गीथाः	N;VOC;PL
साहस	साहसे	N;LOC;SG
साधन	साधनात्	ADJ;ABL;SG
पोत	पोतः	N;NOM;SG
शुनक	शुनकम्	N;ACC;SG
ग्रीवा	ग्रीवाभिः	N;INS;PL
अंशक	अंशके	ADJ;LOC;MASC;SG
रुधिर	रुधिरेषु	ADJ;LOC;MASC;PL
सखि	सखिभ्यः	N;ABL;PL
सह	सहाम्	ADJ;ACC;FEM;SG
पवमान	पवमानाः	ADJ;ACC;FEM;PL
वाहन	वाहनम्	N;NOM;SG
मलिक	मलिकस्य	N;GEN;SG
अकर्मक	अकर्मकाणाम्	ADJ;GEN;MASC;PL
मूढ	मूढ	N;VOC;SG
नीड	नीडानि	N;VOC;PL
नान्दी	नान्दीषु	N;LOC;PL
शील	शीलस्य	N;GEN;SG
अग	अगयोः	N;LOC;DU
विधवा	विधवायै	N;DAT;SG
पुरोहित	पुरोहितौ	ADJ;VOC;MASC;DU
माधवीय	माधवीयानि	ADJ;ACC;NEUT;PL
जम्भ	जम्भेन	N;INS;SG
नारायण	नारायणयोः	ADJ;LOC;MASC;DU
ब्रह्मचर्य	ब्रह्मचर्ययोः	N;GEN;DU
खण्ड	खण्डयोः	N;LOC;DU
प्रारम्भ	प्रारम्भान्	N;ACC;PL
सुम्न	सुम्नम्	ADJ;ACC;MASC;SG
मध्यम	मध्यमे	ADJ;VOC;FEM;DU
प्रसन्न	प्रसन्नाभ्याम्	N;DAT;DU
उच्च	उच्चाभिः	ADJ;INS;FEM;PL
परिमाण	परिमाणानि	N;ACC;PL
साहस	साहसम्	N;ACC;SG
गाथा	गाथाभ्यः	N;ABL;PL
अनुराग	अनुरागाभ्याम्	N;DAT;DU
उक्ति	उक्तयः	N;NOM;PL
लिंग	लिंगेभ्यः	N;DAT;PL
ईशान	ईशाने	ADJ;ACC;NEUT;DU
वृत्त	वृत्तायाम्	ADJ;LOC;FEM;SG
वैतान	वैतान्योः	ADJ;LOC;FEM;DU
केन्द्र	केन्द्र	N;VOC;SG
अमित्र	अमित्रः	ADJ;NOM;MASC;SG
मह	महानाम्	ADJ;GEN;FEM;PL
रुधिर	रुधिराम्	ADJ;ACC;FEM;SG
मण्डल	मण्डलायाम्	ADJ;LOC;FEM;SG
कष्ट	कष्ट	N;VOC;SG
सूक्त	सूक्तः	ADJ;NOM;MASC;SG
क्रिया	क्रियायै	N;DAT;SG
वाद	वादानाम्	ADJ;GEN;FEM;PL
युद्ध	युद्धे	ADJ;LOC;MASC;SG
तित्तिरि	तित्तिरिषु	N;LOC;PL
भारत	भारतेभ्यः	ADJ;ABL;NEUT;PL
हेतु	हेतोः	N;ABL;SG
ओषधि	ओषध्याः	N;ABL;SG
उदय	उदयाय	N;DAT;SG
उदात्त	उदात्तेन	ADJ;INS;NEUT;SG
चुम्बन	चुम्बने	N;LOC;SG
धूर्त	धूर्तैः	ADJ;INS;MASC;PL
अङ्घ्रि	अङ्घ्रेः	N;ABL;SG
उदात्त	उदात्ताभ्याम्	ADJ;ABL;FEM;DU
अकाल	अकालेभ्यः	N;DAT;PL
ईशान	ईशाने	ADJ;ACC;FEM;DU
धूम	धूमेभ्यः	N;DAT;PL
स्नेह	स्नेहौ	N;NOM;DU
पृथ्वी	पृथ्वीः	N;ACC;PL
इन्दु	इन्दौ	N;LOC;SG
विदूषक	विदूषकानि	ADJ;NOM;NEUT;PL
भारत	भारतेन	ADJ;INS;NEUT;SG
गुप्त	गुप्तम्	ADJ;ACC;NEUT;SG
धूम	धूमाभ्याम्	N;DAT;DU
बलि	बली	N;ACC;DU
अग्नि	अग्नी	N;VOC;DU
व्यञ्जन	व्यञ्जनाः	ADJ;ACC;FEM;PL
पण्यशाला	पण्यशालाभ्यः	N;ABL;PL
सत्त्व	सत्त्वानि	N;VOC;PL
गाथा	गाथाभ्यः	N;DAT;PL
पण्डित	पण्डिते	ADJ;ACC;NEUT;DU
लाक्षा	लाक्षाभ्यः	N;DAT;PL
साधन	साधनीभ्यः	ADJ;ABL;PL
मनु	मनवः	ADJ;NOM;FEM;PL
लघु	लघु	N;ACC;SG
ऋतु	ऋतुना	N;INS;SG
पुत्र	पुत्राः	N;NOM;PL
कनीन	कनीनानाम्	ADJ;GEN;FEM;PL
कुक्षि	कुक्षिना	N;INS;SG
विधान	विधानाभ्याम्	ADJ;INS;NEUT;DU
वली	वल्यः	N;VOC;PL
निष्क	निष्केषु	N;LOC;PL
आखु	आक्हुभ्याम्	N;DAT;DU
बालक	बालकेभ्यः	N;ABL;PL
पुलस्ति	पुलस्तीः	ADJ;ACC;FEM;PL
लोचन	लोचने	N;NOM;DU
इन्दु	इन्दुः	N;NOM;SG
आश्रम	आश्रमाणि	N;VOC;PL
सवन	सवनाभ्याम्	ADJ;ABL;DU
ब्राह्म	ब्राह्मी	ADJ;NOM;FEM;SG
ओषधि	ओषधिषु	N;LOC;PL
अग्निहोत्र	अग्निहोत्रेभ्यः	ADJ;ABL;MASC;PL
आशा	आशाभ्यः	N;ABL;PL
हृदय	हृदयाः	ADJ;VOC;MASC;PL
भग	भगे	N;LOC;SG
अमित्र	अमित्रात्	ADJ;ABL;MASC;SG
क्षौर	क्षौरेषु	N;LOC;PL
मन्दर	मन्दरयोः	ADJ;LOC;NEUT;DU
विजय	विजयेन	N;INS;SG
अगुरु	अगुरुनी	N;NOM;DU
ऊर्णा	ऊर्णाः	N;NOM;PL
धूर्त	धूर्तासु	ADJ;LOC;FEM;PL
महाकाव्य	महाकाव्येभ्यः	N;DAT;PL
गुप्त	गुप्तेषु	ADJ;LOC;NEUT;PL
दीर्घ	दीर्घासु	ADJ;LOC;FEM;PL
पितृयाण	पितृयाणाभ्याम्	ADJ;ABL;NEUT;DU
साध्य	साध्यान्	ADJ;ACC;MASC;PL
तद्	तस्मात्	N;ABL;SG
विपक्ष	विपक्षयोः	ADJ;LOC;MASC;DU
ईशान	ईशानम्	ADJ;ACC;MASC;SG
अंशक	अंशिकाः	ADJ;ACC;FEM;PL
अमित्र	अमित्राभ्याम्	ADJ;DAT;NEUT;DU
नारायण	नारायणानाम्	ADJ;GEN;NEUT;PL
अक्षय	अक्षयानाम्	ADJ;GEN;NEUT;PL
अष्टक	अष्टकौ	ADJ;NOM;MASC;DU
शिव	शिवयोः	ADJ;LOC;FEM;DU
लघु	लघू	ADJ;NOM;DU
अगुरु	अगुरुः	N;NOM;SG
विष्कम्भ	विष्कम्भानाम्	N;GEN;PL
स्नेह	स्नेहाभ्याम्	N;INS;DU
मेध	मेधम्	N;ACC;SG
रासभी	रासभ्या	N;INS;SG
प्राच्य	प्राच्यायै	ADJ;DAT;FEM;SG
विहग	विहगम्	N;ACC;SG
विधान	विधानयोः	ADJ;LOC;NEUT;DU
कष्ट	कष्टेन	N;INS;SG
वैश्वानर	वैश्वानर्याः	ADJ;ABL;FEM;SG
अष्टक	अष्टकयोः	ADJ;GEN;MASC;DU
सिद्ध	सिद्धाभ्याम्	ADJ;INS;NEUT;DU
साधारण	साधारणी	ADJ;NOM;SG
उत्सव	उत्सवः	N;NOM;SG
दुन्दुभि	दुन्दुभििषु	N;LOC;PL
दुर्बल	दुर्बलानाम्	N;GEN;PL
पाल	पालैः	N;INS;PL
तल्प	तल्पान्	N;ACC;PL
अंहु	अंहू	ADJ;ACC;FEM;DU
दुन्दुभि	दुन्दुभििभ्याम्	N;DAT;DU
स्नातक	स्नातके	N;LOC;SG
प्रतिबुद्ध	प्रतिबद्धासु	ADJ;LOC;FEM;PL
पृदाकु	पृदाकवः	N;NOM;PL
अजा	अजाभ्याम्	N;ABL;DU
अष्टक	अष्टकयोः	ADJ;LOC;MASC;DU
अकार्य	अकार्या	N;DAT;SG
मृत	मृतया	ADJ;INS;FEM;SG
हृदय	हृदययोः	ADJ;GEN;NEUT;DU
आस्य	आस्याभ्याम्	N;INS;DU
वृत्त	वृत्त	ADJ;VOC;MASC;SG
उपरम	उपरमाः	N;VOC;PL
वशगा	वशगा	N;NOM;SG
उद्गूर्ण	उद्गूर्णाभ्याम्	ADJ;ABL;MASC;DU
रुधिर	रुधिराणि	ADJ;NOM;NEUT;PL
पुरोहित	पुरोहितेभ्यः	ADJ;ABL;NEUT;PL
मध्यम	मध्यमस्य	ADJ;GEN;NEUT;SG
क्षत्र	क्षत्रेभ्यः	N;ABL;PL
सह	सहात्	ADJ;ABL;MASC;SG
कल	कलान्	ADJ;ACC;MASC;PL
नाचिकेत	नाचिकेतेभ्यः	ADJ;DAT;NEUT;PL
प्लुषि	प्लुषीन्	N;ACC;PL
सभास्थाणु	सभास्थाणवे	N;DAT;SG
नर	नराभ्याम्	N;DAT;DU
नामन्	नाम्नोः	N;GEN;DU
गुप्त	गुप्ताः	ADJ;VOC;FEM;PL
चातुर्मास्य	चातुर्मास्यैः	ADJ;INS;NEUT;PL
मण्डल	मण्डलेन	ADJ;INS;MASC;SG
कर्कट	कर्कटेन	N;INS;SG
नवोदित	नवोदितायाः	ADJ;ABL;FEM;SG
शिव	शिवेभ्यः	ADJ;DAT;MASC;PL
साधु	साधौ	ADJ;LOC;MASC;SG
हिम	हिमौ	ADJ;VOC;MASC;DU
पृथ्वी	पृथ्व्योः	N;LOC;DU
स्वेद	स्वेदायाः	ADJ;GEN;FEM;SG
तल्प	तल्पेषु	N;LOC;PL
अकूपार	अकूपाराः	ADJ;ACC;FEM;PL
मरु	मरुणा	N;INS;SG
केन्द्र	केन्द्रा	N;DAT;SG
महादव	महादवात्	N;ABL;SG
तप	तपे	ADJ;VOC;NEUT;DU
कर्मन्	कर्मभ्याम्	N;DAT;DU
ऋष्व	ऋष्वाभ्याम्	ADJ;ABL;FEM;DU
इतिहास	इतिहासाः	N;VOC;PL
वटवृक्ष	वटवृक्ष	N;VOC;SG
चतुरङ्ग	चतुरङगात्	ADJ;ABL;MASC;SG
पितृयाण	पितृयाणायाः	ADJ;GEN;FEM;SG
अगद	अगदेन	N;INS;SG
अकर्मक	अकर्मके	ADJ;ACC;NEUT;DU
कम्बल	कम्बलाः	N;VOC;PL
बोधि	बोधी	ADJ;NOM;MASC;DU
दुःस्वप्न	दुःस्वप्नाणाम्	N;GEN;PL
उद्यान	उद्यानम्	N;ACC;SG
वैयाकरण	वैयाकरणाः	ADJ;VOC;MASC;PL
वृश्चिक	वृश्चिकौ	N;NOM;DU
विधान	विधानेभ्यः	ADJ;DAT;MASC;PL
हल	हलैः	N;INS;PL
कुल	कुलेन	N;INS;SG
अकर्मक	अकर्मकौ	ADJ;ACC;MASC;DU
मूल्य	मूल्येभ्यः	ADJ;DAT;NEUT;PL
आकाश	आकाशाः	N;VOC;PL
अष्टक	अष्टकेभ्यः	ADJ;ABL;MASC;PL
रुधिर	रुधिराभ्यः	ADJ;DAT;FEM;PL
शिश्न	शिश्नयोः	N;LOC;DU
पुत्र	पुत्रयोः	N;LOC;DU
न्यग्रोध	न्यग्रोधाय	N;DAT;SG
दीर्घ	दीर्घौ	ADJ;VOC;MASC;DU
पुरोहित	पुरोहिते	ADJ;ACC;FEM;DU
प्रतिबुद्ध	प्रतिबद्धेषु	ADJ;LOC;MASC;PL
पाल	पालानाम्	N;GEN;PL
तर्पण	तर्पणे	ADJ;ACC;NEUT;DU
पुरंधि	पुरंध्योः	ADJ;GEN;NEUT;DU
पूर	पूराभिः	ADJ;INS;FEM;PL
स्नातक	स्नातकाभ्याम्	N;DAT;DU
मत्स्य	मत्स्येभ्यः	N;ABL;PL
रुद्राक्ष	रुद्राक्षौ	N;NOM;DU
अबला	अबलाम्	N;ACC;SG
मृत	मृताभ्याम्	ADJ;ABL;NEUT;DU
आधार	आधारेभ्यः	N;ABL;PL
मूढ	मूढेन	N;INS;SG
ब्रह्मवेद	ब्रह्मवेदौ	N;NOM;DU
वचन	वचनः	ADJ;NOM;MASC;SG
संस्कृत	संस्कृता	ADJ;DAT;NEUT;SG
शलभ	शलभयोः	N;GEN;DU
क्षेत्र	क्षेत्रेभ्यः	N;ABL;PL
भ्रमर	भ्रमरेभ्यः	N;DAT;PL
ब्राह्मण	ब्राह्मणे	ADJ;LOC;MASC;SG
पुत्र	पुत्र	N;VOC;SG
धर्म	धर्माः	N;NOM;PL
हंस	हंसः	N;NOM;SG
ईशान	ईशानाः	ADJ;NOM;MASC;PL
वैश्वानर	वैश्वानर्योः	ADJ;LOC;FEM;DU
साधु	साधू	ADJ;NOM;MASC;DU
प्रताप	प्रतापेण	N;INS;SG
ग्ना	ग्नाभ्यः	N;ABL;PL
परिमाण	परिमाणम्	N;NOM;SG
दारु	दारुभ्यः	N;DAT;PL
शून्य	शून्याभ्याम्	N;DAT;DU
रुधिर	रुधिरे	ADJ;VOC;FEM;SG
क्रिया	क्रिये	N;VOC;SG
संगीत	संगीता	ADJ;DAT;NEUT;SG
मन्दार	मन्दारौ	N;ACC;DU
ऊर्ध्व	ऊर्ध्वे	ADJ;NOM;FEM;DU
वशगा	वशगे	N;NOM;DU
पाप	पापौ	ADJ;VOC;DU
माहात्म्य	माहात्म्यानि	N;NOM;PL
प्रान्त	प्रान्ताः	ADJ;NOM;MASC;PL
वैवाहिक	वैवाहिकात्	ADJ;ABL;MASC;SG
तन्त्री	तन्त्र्यौ	N;ACC;DU
कुण्डलिनी	कुण्डलिन्याः	N;ABL;SG
हेतु	हेतोः	N;GEN;SG
नाटिका	नाटिकाः	N;NOM;PL
पुण्डरीक	पुण्डरीकेषु	N;LOC;PL
अंहु	अंह्वोः	ADJ;LOC;FEM;DU
द्राक्षा	द्राक्षया	N;INS;SG
केश	केशान्	N;ACC;PL
हिम	हिमासु	ADJ;LOC;FEM;PL
सूकर	सूकरेभ्यः	N;DAT;PL
चण्डाल	चण्डालेभ्यः	N;ABL;PL
नदी	नद्यः	N;NOM;PL
मिथुन	मिथुनाभ्याम्	ADJ;INS;FEM;DU
व्रत	व्रता	N;DAT;SG
ग्रीष्म	ग्रीष्माः	N;NOM;PL
श्याम	श्यामेन	ADJ;INS;MASC;SG
धातृ	धातॄन्	N;ACC;PL
चरण	चरणानाम्	N;GEN;PL
अर्थ	अर्थात्	N;ABL;SG
उक्थ	उक्थे	N;NOM;DU
सिंहपुर	सिंहपुरैः	N;INS;PL
राजि	राजी	N;VOC;DU
साधार	साधारायै	ADJ;DAT;FEM;SG
रासभी	रासभ्योः	N;LOC;DU
गुप्त	गुप्ताम्	ADJ;ACC;FEM;SG
साधार	साधारेण	ADJ;INS;MASC;SG
श्वन्	श्वभ्याम्	N;ABL;DU
हेलि	हेलेः	N;GEN;SG
साहस	साहसाभ्याम्	N;INS;DU
पुण्डरीक	पुण्डरीकान्	N;ACC;PL
विधान	विधानान्	ADJ;ACC;MASC;PL
अभय	अभयेभ्यः	N;DAT;PL
अरित्र	अरित्रौ	ADJ;VOC;MASC;DU
धूर्त	धूर्तयोः	ADJ;LOC;MASC;DU
साधु	साधुभ्यः	ADJ;ABL;MASC;PL
चिन्तन	चिन्तनाभ्याम्	N;DAT;DU
वीर	वीरेण	N;INS;SG
तोयकण	तोयकणस्य	N;GEN;SG
कान्त	कान्तौ	N;ACC;DU
सह	सहानि	ADJ;ACC;NEUT;PL
कर्पर	कर्परम्	N;ACC;SG
ब्रह्मवेद	ब्रह्मवेदाभ्याम्	N;INS;DU
प्रधान	प्रधानेभ्यः	ADJ;ABL;MASC;PL
अग	अगौ	N;NOM;DU
जीवित	जीवितेषु	ADJ;LOC;NEUT;PL
जय	जयस्य	N;GEN;SG
स्वयंवर	स्वयंवरात्	ADJ;ABL;NEUT;SG
स्वेद	स्वेदे	ADJ;LOC;NEUT;SG
वैश्वानर	वैश्वानरीभिः	ADJ;INS;FEM;PL
आधार	आधार	N;VOC;SG
चातुर्मास्य	चातुर्मास्याभ्याम्	ADJ;INS;NEUT;DU
तित्तिरि	तित्तिरौ	N;LOC;SG
छल्ली	छल्ल्योः	N;LOC;DU
अनुवाद	अनुवादे	N;ACC;DU
जङ्गल	जङ्गलायाम्	ADJ;LOC;FEM;SG
अभय	अभयेभ्यः	N;ABL;PL
पाप	पापानि	ADJ;VOC;PL
विजय	विजयाभ्याम्	N;DAT;DU
बोधि	बोधिभिः	ADJ;INS;MASC;PL
पर्कटी	पर्कट्यौ	N;ACC;DU
विद्याचण	विद्याचणम्	ADJ;ACC;MASC;SG
आर्य	आर्यायाः	ADJ;GEN;FEM;SG
दक्षिण	दक्षिणानाम्	ADJ;GEN;NEUT;PL
व्याहृति	व्याहृतिभ्याम्	N;ABL;DU
पितृयाण	पितृयाणयोः	ADJ;LOC;FEM;DU
आचार	आचाराभ्याम्	N;ABL;DU
क्ष	क्षौ	N;NOM;DU
मह	महाय	ADJ;DAT;MASC;SG
हिम	हिमयोः	ADJ;GEN;FEM;DU
ऋष्व	ऋष्वेभ्यः	ADJ;DAT;MASC;PL
मरु	मरोः	N;ABL;SG
सामयाचारिक	सामयाचारिकानाम्	ADJ;GEN;NEUT;PL
स्वेद	स्वेदः	ADJ;NOM;MASC;SG
अभिनय	अभिनयाभ्याम्	N;INS;DU
शिव	शिवेन	ADJ;INS;MASC;SG
शिष्य	शिष्ये	N;LOC;SG
स्वयंवर	स्वयंवरेन	ADJ;INS;NEUT;SG
धूर्त	धूर्तात्	ADJ;ABL;MASC;SG
सिद्धार्थ	सिद्धार्थे	ADJ;VOC;FEM;DU
ब्राह्म	ब्राह्मीभ्यः	ADJ;DAT;FEM;PL
वैबोधिक	वैबोधिकानाम्	N;GEN;PL
अनार्य	अनार्याभिः	ADJ;INS;FEM;PL
द्वादशाह	द्वादशाहासु	ADJ;LOC;FEM;PL
गविष्टि	गविष्ट्यै	N;DAT;SG
छाया	छायाभ्यः	N;DAT;PL
स्वयंवर	स्वयंवरायाः	ADJ;GEN;FEM;SG
अग्निहोत्र	अग्निहोत्राणाम्	ADJ;GEN;FEM;PL
सिद्धार्थ	सिद्धार्थानाम्	ADJ;GEN;NEUT;PL
भक्ति	भक्तयः	N;NOM;PL
माला	मालाः	N;ACC;PL
मूषक	मूषकौ	N;VOC;DU
पत्नी	पत्नी	N;NOM;SG
सवन	सवनासु	ADJ;LOC;PL
कृपाण	कृपाणौ	N;VOC;DU
संगीत	संगीतस्य	ADJ;GEN;MASC;SG
आकाश	आकाशः	N;NOM;SG
मलिक	मलिकयोः	N;GEN;DU
समस्या	समस्ये	N;VOC;DU
जाङ्गल	जाङ्गले	ADJ;LOC;MASC;SG
वज्र	वज्राय	ADJ;DAT;MASC;SG
सूक्त	सूक्ता	ADJ;DAT;NEUT;SG
प्रजापति	प्रजापतीनाम्	N;GEN;PL
अकर्मक	अकर्मकाभ्याम्	ADJ;INS;MASC;DU
आकाश	आकाशे	N;LOC;SG
वाद	वादाः	ADJ;VOC;FEM;PL
ओष्ठ	ओष्ठाभ्याम्	N;ABL;DU
सर्म	सर्माभ्याम्	N;INS;DU
राग	रागाभ्याम्	N;DAT;DU
पति	पती	N;ACC;DU
चातुर्मास्य	चातुर्मास्याः	ADJ;VOC;MASC;PL
संतोष	संतोषाभ्याम्	N;DAT;DU
पुरंधि	पुरंधिनोः	ADJ;GEN;FEM;DU
अक्षरा	अक्षरायाः	N;ABL;SG
ऋत	ऋतस्य	N;GEN;SG
देवयान	देवयानम्	ADJ;NOM;NEUT;SG
सवन	सवनैः	ADJ;INS;PL
श्वश्रू	श्वश्रूभ्यः	N;DAT;PL
अमृता	अमृताभ्याम्	N;INS;DU
पुरंधि	पुरंधिभ्याम्	ADJ;INS;NEUT;DU
साध्य	साध्याम्	ADJ;ACC;FEM;SG
व्याघ्र	व्याघ्रात्	N;ABL;SG
कर्पर	कर्परा	N;DAT;SG
श्रवस्	श्रवसी	N;NOM;DU
प्रयत्न	प्रयत्नस्य	N;GEN;SG
अक्ष	अक्षौ	N;VOC;DU
पाप	पापीभ्याम्	N;DAT;DU
सुख	सुखाम्	ADJ;ACC;FEM;SG
वैतथ्य	वैतथ्यात्	ADJ;ABL;NEUT;SG
तद्	ताभ्याम्	N;INS;DU
वृषभ	वृषभाभ्याम्	ADJ;ABL;FEM;DU
शिश्न	शिश्ना	N;DAT;SG
वृश्चिक	वृश्चिकाभ्याम्	N;ABL;DU
चक्रवाल	चक्रवाले	N;LOC;SG
मन्दर	मन्दरायै	ADJ;DAT;FEM;SG
कनीन	कनीनाभिः	ADJ;INS;FEM;PL
केश	केशः	N;NOM;SG
धूम	धूमयोः	N;GEN;DU
अवि	अविभ्यः	N;DAT;PL
अगुरु	अगुरुषु	N;LOC;PL
