Golfklub	Golfklubs	N;GEN;SG
Vorgabe	Vorgaben	N;NOM;PL
Wölfin	Wölfinnen	N;ACC;PL
Selbstbefriedigung	Selbstbefriedigung	N;DAT;SG
betreten	betritt	V;IND;SG;3;PRS
Thermoelement	Thermoelement	N;DAT;SG
Weltall	Weltall	N;NOM;SG
Hehler	Hehler	N;NOM;SG
Sachertorte	Sachertorte	N;ACC;SG
sausen	sausen	V;IND;PL;3;PRS
Palladiumkatalysator	Palladiumkatalysator	N;NOM;SG
Antifaschist	Antifaschisten	N;DAT;PL
akzeptieren	akzeptierte	V;SBJV;SG;1;PST
ergrauen	ergrauten	V;IND;PL;3;PST
Befürworter	Befürworter	N;NOM;SG
Wattebällchen	Wattebällchen	N;DAT;SG
atomisieren	atomisiere	V;SBJV;SG;1;PRS
Dessertlöffel	Dessertlöffel	N;NOM;SG
Froschmann	Froschmann	N;DAT;SG
Napfkuchen	Napfkuchens	N;GEN;SG
Gesäss	Gesässe	N;ACC;PL
Inhibitor	Inhibitoren	N;DAT;PL
beabsichtigen	beabsichtigten	V;SBJV;PL;3;PST
Kehrwert	Kehrwert	N;DAT;SG
Außenpolitik	Außenpolitik	N;DAT;SG
Freizeitzentrum	Freizeitzentrum	N;DAT;SG
gerben	gerbtest	V;SBJV;SG;2;PST
Sportklub	Sportklub	N;ACC;SG
durchsuchen	durchsuchen	V;IND;PL;3;PRS
Krawall	Krawalle	N;GEN;PL
Modultest	Modultests	N;NOM;PL
zupfen	zupfest	V;SBJV;SG;2;PRS
Anthocyan	Anthocyane	N;GEN;PL
Dithionit	Dithionit	N;DAT;SG
Aftershave	Aftershave	N;ACC;SG
Joint	Joints	N;GEN;PL
Sulfonamid	Sulfonamid	N;ACC;SG
Hydroxyaldehyd	Hydroxyaldehyd	N;ACC;SG
Dessertlöffel	Dessertlöffel	N;DAT;PL
rasen	rastet	V;SBJV;PL;2;PST
Hehler	Hehlers	N;GEN;SG
Fellache	Fellachen	N;NOM;PL
Absiedler	Absiedler	N;GEN;PL
Landstreicherei	Landstreichereien	N;GEN;PL
Versicherung	Versicherung	N;ACC;SG
grünen	grünest	V;SBJV;SG;2;PRS
Gelege	Geleges	N;GEN;SG
Erfahrung	Erfahrungen	N;GEN;PL
Befehl	Befehles	N;GEN;SG
grinsen	grinse	V;SBJV;SG;1;PRS
schweigen	schweige	V;IND;SG;1;PRS
Weltzeituhr	Weltzeituhren	N;NOM;PL
malen	malte	V;SBJV;SG;1;PST
Nutznießer	Nutznießer	N;GEN;PL
zerquetschen	zerquetschtet	V;IND;PL;2;PST
korrigieren	korrigierst	V;IND;SG;2;PRS
Menge	Menge	N;GEN;SG
zupfen	zupften	V;SBJV;PL;3;PST
Aquamarin	Aquamarine	N;NOM;PL
Sulfonamid	Sulfonamides	N;GEN;SG
patzen	patzt	V;IMP;PL;2
ergrauen	ergrauen	V;NFIN
Benutzer	Benutzers	N;GEN;SG
Bleigehalt	Bleigehalte	N;GEN;PL
argumentieren	argumentiere	V;SBJV;SG;3;PRS
spähen	spähe	V;SBJV;SG;3;PRS
Vorgabe	Vorgaben	N;DAT;PL
Flüssigkristall	Flüssigkristall	N;NOM;SG
Kilogramm	Kilogramme	N;GEN;PL
Kiba	Kiba	N;ACC;SG
durchsuchen	durchsuchten	V;IND;PL;1;PST
Dödel	Dödel	N;DAT;SG
Pater	Pater	N;DAT;SG
debattieren	debattiertest	V;SBJV;SG;2;PST
Libelle	Libellen	N;DAT;PL
assoziieren	assoziier	V;IMP;SG;2
Anzeiger	Anzeiger	N;ACC;SG
Fellache	Fellachen	N;GEN;PL
Wikiwörterbuch	Wikiwörterbücher	N;NOM;PL
internationalisieren	internationalisierte	V;IND;SG;1;PST
Frikadelle	Frikadellen	N;DAT;PL
menstruieren	menstruierten	V;IND;PL;3;PST
akzeptieren	akzeptiert	V;IND;SG;3;PRS
oktroyieren	oktroyiertet	V;SBJV;PL;2;PST
rüsten	rüste	V;IND;SG;1;PRS
Fürwort	Fürwort	N;ACC;SG
Bistro	Bistros	N;GEN;PL
Kürbis	Kürbissen	N;DAT;PL
zwangsernähren	zwangsernähren	V;IND;PL;3;PRS
Affinität	Affinität	N;GEN;SG
grinsen	grinsen	V;SBJV;PL;1;PRS
besiegen	besieget	V;SBJV;PL;2;PRS
Schmieröl	Schmieröl	N;ACC;SG
Loch	Löchern	N;DAT;PL
branden	brande	V;IMP;SG;2
Beschreibung	Beschreibung	N;GEN;SG
Ferchromid	Ferchromide	N;ACC;PL
Summe	Summen	N;DAT;PL
Befehlshaber	Befehlshaber	N;DAT;PL
geifern	geiferte	V;SBJV;SG;3;PST
Feuerwehrfrau	Feuerwehrfrauen	N;ACC;PL
Minus	Minusse	N;NOM;PL
entführen	entführtest	V;IND;SG;2;PST
Zellgift	Zellgifte	N;GEN;PL
verbarrikadieren	verbarrikadiere	V;IND;SG;1;PRS
drohen	drohte	V;SBJV;SG;3;PST
entziehen	entziehen	V;SBJV;PL;3;PRS
kampieren	kampier	V;IMP;SG;2
Befürworter	Befürworter	N;DAT;SG
Duell	Duelle	N;GEN;PL
Affix	Affixen	N;DAT;PL
internationalisieren	internationalisierte	V;SBJV;SG;1;PST
Darmentzündung	Darmentzündungen	N;DAT;PL
jappen	jappen	V;SBJV;PL;3;PRS
Balgfrucht	Balgfrucht	N;NOM;SG
buddeln	buddele	V;SBJV;SG;3;PRS
Golfklub	Golfklub	N;ACC;SG
Mischling	Mischlings	N;GEN;SG
Maulwurfsgrille	Maulwurfsgrillen	N;NOM;PL
gurgeln	gurgelt	V;IND;SG;3;PRS
Gleitzeit	Gleitzeit	N;GEN;SG
Gelege	Gelege	N;ACC;SG
Büffel	Büffel	N;NOM;PL
Flasche	Flasche	N;NOM;SG
Huflattich	Huflattich	N;NOM;SG
Kleintier	Kleintieres	N;GEN;SG
Grat	Grates	N;GEN;SG
summen	summte	V;SBJV;SG;1;PST
begrabschen	begrabschst	V;IND;SG;2;PRS
verwandeln	verwandelten	V;IND;PL;3;PST
Potenzial	Potenzial	N;ACC;SG
defragmentieren	defragmentierte	V;IND;SG;3;PST
zügeln	zügelten	V;IND;PL;1;PST
buddeln	buddeln	V;SBJV;PL;1;PRS
schwären	schwärst	V;IND;SG;2;PRS
Hellsehen	Hellsehen	N;NOM;SG
debattieren	debattiere	V;IND;SG;1;PRS
Pfuhlschnepfe	Pfuhlschnepfen	N;NOM;PL
detektieren	detektier	V;IMP;SG;2
defragmentieren	defragmentiert	V;IND;PL;2;PRS
Zufallsgröße	Zufallsgrößen	N;NOM;PL
drohen	drohte	V;IND;SG;3;PST
Inhibitor	Inhibitors	N;GEN;SG
Mauke	Mauke	N;NOM;SG
brausen	braust	V;IND;SG;3;PRS
türmen	türme	V;SBJV;SG;1;PRS
Sendegerät	Sendegeräte	N;ACC;PL
greinen	greinst	V;IND;SG;2;PRS
entlehnen	entlehnten	V;IND;PL;1;PST
Bodyguard	Bodyguard	N;DAT;SG
Mietvertrag	Mietvertrages	N;GEN;SG
verschaffen	verschafften	V;SBJV;PL;3;PST
Schnepfe	Schnepfen	N;GEN;PL
beaufsichtigen	beaufsichtigtest	V;SBJV;SG;2;PST
satteln	satteltest	V;IND;SG;2;PST
Meteorologin	Meteorologin	N;DAT;SG
Rattengift	Rattengiften	N;DAT;PL
türmen	türmen	V;SBJV;PL;3;PRS
Mandarinente	Mandarinenten	N;GEN;PL
Wasserlinie	Wasserlinien	N;ACC;PL
wecken	weckte	V;SBJV;SG;1;PST
verhüllen	verhülle	V;SBJV;SG;3;PRS
Safflorit	Safflorit	N;NOM;SG
Scheinsieg	Scheinsiegen	N;DAT;PL
Nadelholz	Nadelhölzern	N;DAT;PL
entlehnen	entlehnt	V;IND;PL;2;PRS
Briefbeschwerer	Briefbeschwerer	N;DAT;PL
Armutszeugnis	Armutszeugnis	N;NOM;SG
massieren	massieren	V;SBJV;PL;1;PRS
geifern	geiferte	V;IND;SG;3;PST
polarisieren	polarisieren	V;IND;PL;3;PRS
Gönnen	Gönnen	N;DAT;SG
widmen	widmete	V;IND;SG;1;PST
grünen	grünen	V;NFIN
rüsten	rüsten	V;SBJV;PL;1;PRS
ernennen	ernenne	V;SBJV;SG;3;PRS
Kiba	Kibas	N;GEN;SG
Gladiole	Gladiolen	N;GEN;PL
Dominicanerin	Dominicanerinnen	N;NOM;PL
beachten	beachten	V;IND;PL;3;PRS
Kefir	Kefire	N;NOM;PL
geifern	geifern	V;IND;PL;3;PRS
rüsten	rüstest	V;IND;SG;2;PRS
Balgfrucht	Balgfrüchte	N;NOM;PL
Landstreicherei	Landstreicherei	N;GEN;SG
Genickschuss	Genickschüsse	N;GEN;PL
Mondgestein	Mondgestein	N;ACC;SG
kümmern	kümmertest	V;SBJV;SG;2;PST
senken	senke	V;SBJV;SG;1;PRS
Höhlenforscher	Höhlenforschern	N;DAT;PL
melieren	melieren	V;IND;PL;1;PRS
gerben	gerbt	V;IMP;PL;2
Gehirnwäsche	Gehirnwäsche	N;ACC;SG
patentieren	patentierte	V;IND;SG;1;PST
kümmern	kümmere	V;SBJV;SG;3;PRS
verbarrikadieren	verbarrikadier	V;IMP;SG;2
Zugang	Zugängen	N;DAT;PL
Schläfer	Schläfern	N;DAT;PL
nächtigen	nächtigen	V;IND;PL;1;PRS
Fingerspitzengefühl	Fingerspitzengefühl	N;ACC;SG
Hundsrobbe	Hundsrobben	N;GEN;PL
Verschollenheit	Verschollenheit	N;GEN;SG
persiflieren	persiflierten	V;SBJV;PL;3;PST
spähen	spähet	V;SBJV;PL;2;PRS
erkundigen	erkundigst	V;IND;SG;2;PRS
Quartett	Quartette	N;NOM;PL
globalisieren	globalisierten	V;IND;PL;1;PST
gurgeln	gurgelte	V;SBJV;SG;1;PST
zwangsernähren	zwangsernähret	V;SBJV;PL;2;PRS
feiern	feiert	V;IMP;PL;2
geifern	geifre	V;IND;SG;1;PRS
Kefir	Kefir	N;NOM;SG
Gummibärchen	Gummibärchen	N;NOM;PL
Hellsehen	Hellsehen	N;DAT;SG
tappen	tappest	V;SBJV;SG;2;PRS
kacken	kackt	V;IMP;PL;2
kümmern	kümmert	V;IND;PL;2;PRS
evaluieren	evaluieren	V;SBJV;PL;1;PRS
billigen	billigen	V;NFIN
korrumpieren	korrumpierte	V;SBJV;SG;3;PST
Feuerwehrfrau	Feuerwehrfrauen	N;GEN;PL
popeln	popelet	V;SBJV;PL;2;PRS
Sulfonamid	Sulfonamide	N;NOM;PL
werfen	warfen	V;IND;PL;1;PST
unterrichten	unterrichtetest	V;IND;SG;2;PST
Stellenwert	Stellenwert	N;ACC;SG
Wohnzimmer	Wohnzimmern	N;DAT;PL
zügeln	zügelst	V;IND;SG;2;PRS
Master	Master	N;NOM;PL
ernennen	ernanntet	V;IND;PL;2;PST
Grausen	Grausen	N;NOM;SG
satteln	sattelten	V;SBJV;PL;1;PST
Böschung	Böschung	N;DAT;SG
drohen	drohtet	V;IND;PL;2;PST
verschwören	verschworen	V;IND;PL;1;PST
unterrichten	unterrichte	V;SBJV;SG;3;PRS
Schnorchel	Schnorchel	N;ACC;PL
Paradox	Paradoxe	N;ACC;PL
Polydeist	Polydeist	N;NOM;SG
erobern	erobere	V;SBJV;SG;1;PRS
entführen	entführen	V;NFIN
Anisette	Anisettes	N;DAT;PL
unternehmen	unternähmet	V;SBJV;PL;2;PST
Halbleiter	Halbleiter	N;GEN;PL
jappen	jappte	V;IND;SG;3;PST
argumentieren	argumentier	V;IMP;SG;2
Kernspaltung	Kernspaltungen	N;GEN;PL
Anwendungsgebiet	Anwendungsgebiete	N;GEN;PL
Briefbeschwerer	Briefbeschwerer	N;NOM;PL
beaufsichtigen	beaufsichtigen	V;IND;PL;3;PRS
Nilpferd	Nilpferden	N;DAT;PL
Geste	Geste	N;NOM;SG
Summe	Summe	N;DAT;SG
Hüpfburg	Hüpfburg	N;GEN;SG
Nutznießer	Nutznießer	N;ACC;SG
Leichnam	Leichnam	N;DAT;SG
akzeptieren	akzeptiert	V;IMP;PL;2
Ambiguität	Ambiguitäten	N;ACC;PL
Briefbeschwerer	Briefbeschwerer	N;GEN;PL
Antihistaminikum	Antihistaminikum	N;ACC;SG
beflügeln	beflügelte	V;SBJV;SG;1;PST
Korvette	Korvette	N;NOM;SG
Nachtquartier	Nachtquartiere	N;GEN;PL
verhüllen	verhüllet	V;SBJV;PL;2;PRS
Ambiguität	Ambiguität	N;DAT;SG
Sphäre	Sphäre	N;GEN;SG
Sicherheitsventil	Sicherheitsventile	N;NOM;PL
nächtigen	nächtigten	V;IND;PL;1;PST
Rasierstift	Rasierstift	N;NOM;SG
Intrusivgestein	Intrusivgesteine	N;GEN;PL
popeln	popeltest	V;SBJV;SG;2;PST
Maulwurfsgrille	Maulwurfsgrille	N;GEN;SG
Geselle	Gesellen	N;ACC;SG
Armutszeugnis	Armutszeugnissen	N;DAT;PL
entlehnen	entlehntet	V;IND;PL;2;PST
verabschieden	verabschiedet	V;IND;PL;2;PRS
akzeptieren	akzeptieren	V;IND;PL;3;PRS
verhüllen	verhüllest	V;SBJV;SG;2;PRS
enteisen	enteistest	V;IND;SG;2;PST
grinsen	grinset	V;SBJV;PL;2;PRS
unterrichten	unterrichten	V;NFIN
Franke	Franken	N;NOM;PL
Atomphysiker	Atomphysiker	N;DAT;SG
bieren	bierte	V;SBJV;SG;1;PST
versäumen	versäumest	V;SBJV;SG;2;PRS
erkundigen	erkundigen	V;SBJV;PL;1;PRS
bohren	bohrte	V;SBJV;SG;1;PST
verchromen	verchromest	V;SBJV;SG;2;PRS
spüren	spürt	V;IND;SG;3;PRS
Milchfieber	Milchfieber	N;ACC;SG
entschlüsseln	entschlüsselten	V;SBJV;PL;1;PST
Telephon	Telephone	N;NOM;PL
persiflieren	persifliertest	V;IND;SG;2;PST
verwandeln	verwandeln	V;IND;PL;3;PRS
schmauchen	schmauchte	V;SBJV;SG;3;PST
Zauberspruch	Zaubersprüche	N;GEN;PL
Schulbuch	Schulbücher	N;NOM;PL
kuscheln	kuschelten	V;IND;PL;1;PST
malen	malen	V;SBJV;PL;1;PRS
stippen	stippt	V;IND;PL;2;PRS
enteisen	enteisen	V;NFIN
Akanthit	Akanthits	N;GEN;SG
Feldspaten	Feldspaten	N;DAT;SG
Loch	Löcher	N;NOM;PL
verscheißern	verscheißern	V;SBJV;PL;3;PRS
Beschleunigungssensor	Beschleunigungssensor	N;DAT;SG
diffamieren	diffamieren	V;NFIN
fiepen	fiepst	V;IND;SG;2;PRS
Desoxidationsmittel	Desoxidationsmittel	N;NOM;PL
betreten	betreten	V;SBJV;PL;3;PRS
Quadratmeter	Quadratmeter	N;ACC;PL
Kleinhirn	Kleinhirn	N;NOM;SG
infizieren	infizieren	V;IND;PL;1;PRS
schmauchen	schmauchtest	V;SBJV;SG;2;PST
Zellgift	Zellgift	N;DAT;SG
Sphäre	Sphäre	N;ACC;SG
verscheißern	verscheißern	V;SBJV;PL;1;PRS
fiepen	fiepe	V;SBJV;SG;1;PRS
Lebensjahr	Lebensjahre	N;NOM;PL
sausen	sause	V;SBJV;SG;3;PRS
Trickbetrüger	Trickbetrüger	N;GEN;PL
verzieren	verziertest	V;SBJV;SG;2;PST
kodieren	kodierte	V;IND;SG;1;PST
karren	karrte	V;IND;SG;3;PST
Bromfluorid	Bromfluorids	N;GEN;SG
korrigieren	korrigierten	V;SBJV;PL;1;PST
Größe	Größen	N;DAT;PL
Mörser	Mörser	N;NOM;SG
Abstecher	Abstecher	N;NOM;SG
Energieniveau	Energieniveau	N;DAT;SG
marinieren	marinierten	V;SBJV;PL;3;PST
grunzen	grunzen	V;SBJV;PL;3;PRS
Mercaptan	Mercaptane	N;ACC;PL
Pol	Pol	N;NOM;SG
Flügelhorn	Flügelhörner	N;GEN;PL
schummeln	schummelten	V;IND;PL;1;PST
Schrifft	Schrifften	N;ACC;PL
deaktivieren	deaktiviert	V;IMP;PL;2
Schulbuch	Schulbuch	N;ACC;SG
verschaffen	verschaffen	V;IND;PL;1;PRS
jappen	jappte	V;SBJV;SG;1;PST
Lastschrift	Lastschrift	N;DAT;SG
widmen	widmete	V;SBJV;SG;1;PST
verscheißern	verscheißerten	V;SBJV;PL;1;PST
Herrscherpersönlichkeit	Herrscherpersönlichkeiten	N;GEN;PL
zerquetschen	zerquetsche	V;SBJV;SG;1;PRS
spüren	spürst	V;IND;SG;2;PRS
Loch	Loch	N;ACC;SG
Kloster	Klöster	N;GEN;PL
Regenpfeifer	Regenpfeifer	N;GEN;PL
marinieren	marinierten	V;IND;PL;3;PST
besiegen	besiegten	V;SBJV;PL;1;PST
verändern	veränderten	V;IND;PL;1;PST
senken	senkten	V;IND;PL;3;PST
Vorstandschef	Vorstandschefs	N;ACC;PL
zügeln	zügeln	V;IND;PL;3;PRS
entschlüsseln	entschlüsselt	V;IND;SG;3;PRS
My	My	N;NOM;SG
beäugen	beäuge	V;SBJV;SG;1;PRS
Blindstudie	Blindstudien	N;NOM;PL
Adenin	Adeninen	N;DAT;PL
Schachtelhalm	Schachtelhalm	N;DAT;SG
verscheißern	verscheißerst	V;IND;SG;2;PRS
opfern	opfre	V;IMP;SG;2
jappen	jappe	V;SBJV;SG;3;PRS
Flaschenhals	Flaschenhälse	N;ACC;PL
Abrieb	Abrieben	N;DAT;PL
beflügeln	beflügeln	V;NFIN
unterrichten	unterrichteten	V;IND;PL;1;PST
Betrachter	Betrachtern	N;DAT;PL
zügeln	zügle	V;IMP;SG;2
atomisieren	atomisierten	V;SBJV;PL;1;PST
versäumen	versäumt	V;IND;SG;3;PRS
Balgfrucht	Balgfrucht	N;GEN;SG
zerren	zerrten	V;SBJV;PL;1;PST
Physikerin	Physikerinnen	N;ACC;PL
enteisen	enteist	V;IMP;PL;2
bewerben	bewarb	V;IND;SG;3;PST
argumentieren	argumentieren	V;NFIN
Aquifer	Aquifere	N;ACC;PL
Welplein	Welplein	N;ACC;SG
argumentieren	argumentiertet	V;SBJV;PL;2;PST
Vögelchen	Vögelchen	N;ACC;PL
Hauptanteil	Hauptanteile	N;NOM;PL
verabschieden	verabschiede	V;IND;SG;1;PRS
frittieren	frittiert	V;IMP;PL;2
verweisen	verweiset	V;SBJV;PL;2;PRS
drohen	drohe	V;SBJV;SG;1;PRS
unterrichten	unterrichtete	V;SBJV;SG;1;PST
Treppennatter	Treppennatter	N;ACC;SG
Weltraumbahnhof	Weltraumbahnhöfe	N;GEN;PL
entführen	entführst	V;IND;SG;2;PRS
Gedanke	Gedankens	N;GEN;SG
schwären	schwär	V;IMP;SG;2
werfen	warfen	V;IND;PL;3;PST
prickeln	prickelten	V;IND;PL;3;PST
Gemisch	Gemische	N;NOM;PL
Gummibärchen	Gummibärchen	N;NOM;SG
Oberlippe	Oberlippen	N;ACC;PL
katapultieren	katapultiertest	V;SBJV;SG;2;PST
detektieren	detektierte	V;IND;SG;1;PST
zügeln	zügeltet	V;SBJV;PL;2;PST
evaluieren	evaluieren	V;NFIN
verbarrikadieren	verbarrikadierte	V;SBJV;SG;1;PST
versäumen	versäumst	V;IND;SG;2;PRS
Beutelratte	Beutelratten	N;NOM;PL
verchromen	verchromten	V;IND;PL;1;PST
Spielfeld	Spielfeldern	N;DAT;PL
tappen	tappt	V;IND;SG;3;PRS
schweigen	schweigt	V;IND;SG;3;PRS
rüsten	rüstet	V;IND;SG;3;PRS
Koordinatenachse	Koordinatenachse	N;GEN;SG
Gallenblase	Gallenblasen	N;DAT;PL
gurgeln	gurgeltet	V;SBJV;PL;2;PST
Kampfjet	Kampfjet	N;ACC;SG
zerquetschen	zerquetschen	V;IND;PL;3;PRS
atomisieren	atomisierte	V;IND;SG;1;PST
patentieren	patentieren	V;IND;PL;1;PRS
frittieren	frittierte	V;SBJV;SG;1;PST
hieven	hievtest	V;IND;SG;2;PST
Petersfisch	Petersfische	N;GEN;PL
schweigen	schweigt	V;IMP;PL;2
Klärung	Klärung	N;GEN;SG
erkundigen	erkundigen	V;IND;PL;1;PRS
hintertreiben	hintertreiben	V;SBJV;PL;1;PRS
Aprikosenkonfitüre	Aprikosenkonfitüre	N;NOM;SG
beäugen	beäugen	V;IND;PL;3;PRS
Murmeln	Murmeln	N;ACC;SG
Boson	Boson	N;NOM;SG
polarisieren	polarisierte	V;IND;SG;1;PST
Metropole	Metropolen	N;DAT;PL
Hörsaal	Hörsaales	N;GEN;SG
Proxyserver	Proxyserver	N;DAT;SG
Piedestal	Piedestalen	N;DAT;PL
satteln	satteln	V;SBJV;PL;3;PRS
geschehen	geschahen	V;IND;PL;3;PST
Zahnimplantat	Zahnimplantat	N;NOM;SG
polarisieren	polarisier	V;IMP;SG;2
Polin	Polin	N;NOM;SG
Sittich	Sittich	N;NOM;SG
Dienstagnachmittag	Dienstagnachmittage	N;GEN;PL
Pol	Pol	N;DAT;SG
Werbespot	Werbespots	N;NOM;PL
Befürworter	Befürworter	N;ACC;PL
Instrument	Instrument	N;ACC;SG
Einzelgänger	Einzelgänger	N;GEN;PL
Flasche	Flaschen	N;NOM;PL
menstruieren	menstruiertet	V;SBJV;PL;2;PST
Azubine	Azubinen	N;NOM;PL
marinieren	marinierte	V;IND;SG;1;PST
Leucit	Leucite	N;NOM;PL
Hühnerauge	Hühnerauge	N;NOM;SG
marinieren	mariniertest	V;IND;SG;2;PST
verchromen	verchromtest	V;SBJV;SG;2;PST
erobern	erobertest	V;SBJV;SG;2;PST
prickeln	prickelt	V;IND;PL;2;PRS
Facharzt	Facharzt	N;DAT;SG
kuscheln	kuscheltest	V;IND;SG;2;PST
globalisieren	globalisierte	V;SBJV;SG;1;PST
Sicherheitsvorkehrung	Sicherheitsvorkehrung	N;GEN;SG
Edukt	Eduktes	N;GEN;SG
Trickbetrüger	Trickbetrügern	N;DAT;PL
Diagnostik	Diagnostik	N;GEN;SG
Bodyguard	Bodyguards	N;GEN;PL
Konzentration	Konzentration	N;DAT;SG
Weltraumbahnhof	Weltraumbahnhöfe	N;ACC;PL
schummeln	schummeln	V;NFIN
Communiqué	Communiqué	N;DAT;SG
verchromen	verchromtet	V;SBJV;PL;2;PST
Aquarium	Aquarium	N;NOM;SG
Vizepremierminister	Vizepremierminister	N;ACC;SG
Preis	Preise	N;ACC;PL
gleichen	gleichen	V;IND;PL;1;PRS
Verwüstung	Verwüstungen	N;NOM;PL
Nadelwald	Nadelwälder	N;GEN;PL
evaluieren	evaluiertet	V;SBJV;PL;2;PST
Notaufnahme	Notaufnahmen	N;DAT;PL
Brechnuss	Brechnüsse	N;GEN;PL
beabsichtigen	beabsichtigt	V;IND;PL;2;PRS
Wohnzimmer	Wohnzimmer	N;ACC;SG
Studentenblume	Studentenblumen	N;GEN;PL
Strafantrag	Strafantrages	N;GEN;SG
Schnepfe	Schnepfen	N;DAT;PL
infizieren	infizierten	V;SBJV;PL;1;PST
Melone	Melonen	N;NOM;PL
marinieren	marinieren	V;SBJV;PL;1;PRS
Allee	Allee	N;GEN;SG
assoziieren	assoziieren	V;SBJV;PL;1;PRS
massieren	massiere	V;SBJV;SG;1;PRS
tappen	tappte	V;SBJV;SG;3;PST
Priester	Priester	N;NOM;PL
Datenbankmodell	Datenbankmodell	N;NOM;SG
entgehen	entgehen	V;IND;PL;3;PRS
grunzen	grunztet	V;SBJV;PL;2;PST
Innensenator	Innensenator	N;ACC;SG
löten	lötest	V;IND;SG;2;PRS
Grube	Grube	N;GEN;SG
Franke	Franke	N;NOM;SG
begrabschen	begrabschten	V;IND;PL;1;PST
rüsten	rüstet	V;SBJV;PL;2;PRS
prickeln	prickelest	V;SBJV;SG;2;PRS
türmen	türmen	V;IND;PL;1;PRS
Fürwort	Fürwortes	N;GEN;SG
Meteorologin	Meteorologinnen	N;DAT;PL
Muttersöhnchen	Muttersöhnchens	N;GEN;SG
Abrieb	Abrieb	N;ACC;SG
schmieden	schmiedeten	V;IND;PL;1;PST
verchromen	verchromen	V;IND;PL;3;PRS
Brechnuss	Brechnuss	N;ACC;SG
Wölfin	Wölfin	N;GEN;SG
Abstrebung	Abstrebungen	N;GEN;PL
prickeln	prickelt	V;IMP;PL;2
Spende	Spende	N;ACC;SG
verschmelzen	verschmolzt	V;IND;SG;2;PST
spazieren	spaziert	V;IMP;PL;2
Substrat	Substrate	N;NOM;PL
Vögelchen	Vögelchen	N;NOM;SG
erobern	erobere	V;SBJV;SG;3;PRS
Madenwurm	Madenwurm	N;DAT;SG
zwangsernähren	zwangsernähre	V;SBJV;SG;3;PRS
fluten	fluteten	V;SBJV;PL;3;PST
Feuerkäfer	Feuerkäfer	N;ACC;SG
Pauschenpferd	Pauschenpferdes	N;GEN;SG
Siegel	Siegel	N;ACC;PL
Delta	Delten	N;ACC;PL
persiflieren	persifliertest	V;SBJV;SG;2;PST
verbarrikadieren	verbarrikadierte	V;SBJV;SG;3;PST
satteln	satteln	V;NFIN
Investition	Investitionen	N;GEN;PL
sezieren	sezierest	V;SBJV;SG;2;PRS
buddeln	buddele	V;SBJV;SG;1;PRS
Hippie	Hippies	N;GEN;SG
orgeln	orgle	V;IND;SG;1;PRS
Anthocyan	Anthocyane	N;NOM;PL
patzen	patzen	V;IND;PL;1;PRS
Apiarium	Apiarien	N;GEN;PL
Abbauort	Abbauorten	N;DAT;PL
gleichen	glichst	V;IND;SG;2;PST
Koordinationszahl	Koordinationszahl	N;NOM;SG
Schwimmer	Schwimmer	N;NOM;SG
Flasche	Flasche	N;ACC;SG
Querflöte	Querflöten	N;NOM;PL
löten	löten	V;SBJV;PL;1;PRS
beäugen	beäuget	V;SBJV;PL;2;PRS
Verhütungsmittel	Verhütungsmittel	N;ACC;PL
Halbleiter	Halbleiters	N;GEN;SG
Polydeist	Polydeisten	N;DAT;PL
geschehen	geschähen	V;SBJV;PL;3;PST
entlehnen	entlehnet	V;SBJV;PL;2;PRS
korrumpieren	korrumpiertest	V;IND;SG;2;PST
Trickbetrüger	Trickbetrüger	N;DAT;SG
Polin	Polin	N;GEN;SG
verscheißern	verscheißeret	V;SBJV;PL;2;PRS
branden	brandete	V;IND;SG;3;PST
Obhut	Obhut	N;DAT;SG
Abfahrtsliste	Abfahrtsliste	N;DAT;SG
schmettern	schmettre	V;IND;SG;1;PRS
patzen	patze	V;SBJV;SG;3;PRS
Barbarei	Barbarei	N;GEN;SG
debattieren	debattierten	V;IND;PL;1;PST
Motiv	Motive	N;ACC;PL
patentieren	patentier	V;IMP;SG;2
bieren	bierten	V;IND;PL;3;PST
Grat	Grate	N;ACC;PL
wandeln	wandeln	V;IND;PL;1;PRS
Nummernschild	Nummernschilder	N;ACC;PL
ergrauen	ergrauet	V;SBJV;PL;2;PRS
multiplizieren	multiplizierte	V;IND;SG;1;PST
verschaffen	verschaffte	V;SBJV;SG;3;PST
Nebelgranate	Nebelgranaten	N;DAT;PL
kampieren	kampierest	V;SBJV;SG;2;PRS
akzeptieren	akzeptieren	V;IND;PL;1;PRS
Reißzwecke	Reißzwecke	N;DAT;SG
Baumwolle	Baumwolle	N;GEN;SG
Kodierungsrichtlinie	Kodierungsrichtlinie	N;GEN;SG
satteln	sattelst	V;IND;SG;2;PRS
Nachrichtensprecherin	Nachrichtensprecherinnen	N;ACC;PL
Begleitfahrzeug	Begleitfahrzeuge	N;NOM;PL
Ermittler	Ermittlers	N;GEN;SG
Bügelverschluß	Bügelverschlüssen	N;DAT;PL
hintertreiben	hintertreiben	V;NFIN
Bohrer	Bohrern	N;DAT;PL
Paradox	Paradoxe	N;NOM;PL
werfen	werfen	V;SBJV;PL;1;PRS
verschwören	verschwöret	V;SBJV;PL;2;PRS
Sache	Sache	N;ACC;SG
Rasierstift	Rasierstift	N;ACC;SG
Eselsohr	Eselsohres	N;GEN;SG
Intuition	Intuitionen	N;GEN;PL
Nachtquartier	Nachtquartiere	N;ACC;PL
Scheitern	Scheitern	N;DAT;SG
Stellenwert	Stellenwert	N;DAT;SG
löten	löteten	V;IND;PL;1;PST
spähen	späht	V;IMP;PL;2
Gebrauchsgegenstand	Gebrauchsgegenstand	N;NOM;SG
Brühe	Brühen	N;DAT;PL
schmettern	schmettern	V;SBJV;PL;1;PRS
Nagelknipser	Nagelknipser	N;ACC;PL
Spende	Spenden	N;DAT;PL
widmen	widmete	V;IND;SG;3;PST
Aquamarin	Aquamarinen	N;DAT;PL
unterrichten	unterrichtetet	V;IND;PL;2;PST
schmauchen	schmauche	V;SBJV;SG;1;PRS
entschlüsseln	entschlüsselt	V;IMP;PL;2
Froschmann	Froschmannes	N;GEN;SG
infizieren	infizierest	V;SBJV;SG;2;PRS
reimen	reimten	V;IND;PL;1;PST
schmauchen	schmauchte	V;IND;SG;1;PST
Verselbständigung	Verselbständigung	N;ACC;SG
stippen	stipp	V;IMP;SG;2
Versicherung	Versicherung	N;DAT;SG
Hofnarr	Hofnarren	N;ACC;PL
Plüsch	Plüsch	N;ACC;SG
Betttuch	Betttuch	N;ACC;SG
rasen	rasen	V;IND;PL;1;PRS
verbarrikadieren	verbarrikadierten	V;IND;PL;1;PST
bewerben	bewerbt	V;IND;PL;2;PRS
Befriedigung	Befriedigung	N;ACC;SG
bewerben	bewarb	V;IND;SG;1;PST
melieren	melierte	V;IND;SG;3;PST
Kleintier	Kleintier	N;NOM;SG
Weißblech	Weißblech	N;NOM;SG
Quartett	Quartettes	N;GEN;SG
Polin	Polin	N;DAT;SG
verschwören	verschwören	V;IND;PL;1;PRS
Flüssigkristall	Flüssigkristalles	N;GEN;SG
Koenzym	Koenzyme	N;ACC;PL
Niederschlag	Niederschlages	N;GEN;SG
zerren	zerre	V;SBJV;SG;1;PRS
betreten	betrat	V;IND;SG;3;PST
Kloster	Klöster	N;ACC;PL
Vorschlaghammer	Vorschlaghammer	N;NOM;SG
defragmentieren	defragmentierten	V;IND;PL;3;PST
braten	brate	V;IND;SG;1;PRS
verchromen	verchromten	V;SBJV;PL;3;PST
Wipfel	Wipfel	N;NOM;PL
berechnen	berechnen	V;NFIN
schimmeln	schimmelten	V;IND;PL;1;PST
Tartrat	Tartrate	N;NOM;PL
Grat	Grat	N;ACC;SG
Gleitzeit	Gleitzeiten	N;NOM;PL
verwandeln	verwandeln	V;SBJV;PL;1;PRS
Abrieb	Abriebe	N;NOM;PL
Darmstadtium	Darmstadtium	N;DAT;SG
Märtyrer	Märtyrer	N;NOM;PL
Bimetall	Bimetall	N;DAT;SG
appellieren	appellierten	V;IND;PL;1;PST
Kleintier	Kleintieren	N;DAT;PL
Vorschlaghammer	Vorschlaghammer	N;ACC;SG
Koordinatenachse	Koordinatenachse	N;ACC;SG
Blattlaus	Blattläuse	N;ACC;PL
versäumen	versäumen	V;IND;PL;3;PRS
Piedestal	Piedestale	N;GEN;PL
Herbsttrompete	Herbsttrompeten	N;DAT;PL
Pfuhlschnepfe	Pfuhlschnepfen	N;DAT;PL
löten	lötete	V;IND;SG;1;PST
knicken	knickest	V;SBJV;SG;2;PRS
Sicherheitsventil	Sicherheitsventil	N;NOM;SG
Grat	Grate	N;NOM;PL
schimmeln	schimmeltest	V;SBJV;SG;2;PST
Drehung	Drehungen	N;NOM;PL
Kameruner	Kameruners	N;GEN;SG
hieven	hieven	V;NFIN
Werbespot	Werbespot	N;NOM;SG
Pauschenpferd	Pauschenpferde	N;NOM;PL
Affinität	Affinitäten	N;ACC;PL
destillieren	destillier	V;IMP;SG;2
Wikiwörterbuch	Wikiwörterbücher	N;GEN;PL
karren	karrtet	V;IND;PL;2;PST
Zusammensetzung	Zusammensetzungen	N;GEN;PL
Katarrh	Katarrh	N;ACC;SG
Weltraumbahnhof	Weltraumbahnhof	N;DAT;SG
überstehen	überstehst	V;IND;SG;2;PRS
sezieren	sezierten	V;IND;PL;1;PST
spazieren	spazierten	V;SBJV;PL;3;PST
emulieren	emulierten	V;IND;PL;1;PST
beachten	beachtetet	V;SBJV;PL;2;PST
Gesamtkunstwerk	Gesamtkunstwerke	N;NOM;PL
grünen	grünt	V;IMP;PL;2
verschaffen	verschafft	V;IND;PL;2;PRS
Heliumisotop	Heliumisotop	N;DAT;SG
entführen	entführte	V;IND;SG;1;PST
defragmentieren	defragmentierten	V;SBJV;PL;1;PST
berechnen	berechnest	V;SBJV;SG;2;PRS
berechnen	berechnete	V;IND;SG;1;PST
Organophosphin	Organophosphine	N;NOM;PL
internationalisieren	internationalisiere	V;IND;SG;1;PRS
Zipfel	Zipfel	N;NOM;SG
marinieren	marinierte	V;IND;SG;3;PST
Bromfluorid	Bromfluorid	N;DAT;SG
Sicherheitsvorkehrung	Sicherheitsvorkehrung	N;ACC;SG
Kaplöwe	Kaplöwe	N;NOM;SG
kuscheln	kuschelt	V;IMP;PL;2
diffamieren	diffamieren	V;IND;PL;3;PRS
Stickoxid	Stickoxiden	N;DAT;PL
Habsucht	Habsucht	N;GEN;SG
kacken	kackte	V;SBJV;SG;1;PST
Ordensschwester	Ordensschwestern	N;ACC;PL
ergrauen	ergrautest	V;SBJV;SG;2;PST
Sachertorte	Sachertorten	N;ACC;PL
Dominicanerin	Dominicanerin	N;ACC;SG
Parzelle	Parzelle	N;DAT;SG
entführen	entführ	V;IMP;SG;2
speisen	speisten	V;SBJV;PL;1;PST
Buntstift	Buntstift	N;NOM;SG
Crescendo	Crescendos	N;DAT;PL
Einkristall	Einkristallen	N;DAT;PL
Erfahrung	Erfahrung	N;ACC;SG
Kleinhirn	Kleinhirnes	N;GEN;SG
unterrichten	unterrichtest	V;IND;SG;2;PRS
betreten	betratet	V;IND;PL;2;PST
opfern	opfern	V;IND;PL;3;PRS
Wohnung	Wohnungen	N;NOM;PL
flicken	flickten	V;IND;PL;3;PST
nächtigen	nächtigten	V;SBJV;PL;3;PST
Wohnzimmer	Wohnzimmer	N;ACC;PL
schmauchen	schmaucht	V;IND;PL;2;PRS
bohren	bohrtest	V;IND;SG;2;PST
Konzernumsatz	Konzernumsatz	N;DAT;SG
Förde	Förden	N;NOM;PL
Frikadelle	Frikadelle	N;GEN;SG
speisen	speisen	V;IND;PL;1;PRS
schimmeln	schimmeln	V;SBJV;PL;1;PRS
vergraulen	vergraul	V;IMP;SG;2
braten	briete	V;SBJV;SG;1;PST
Gelege	Gelege	N;NOM;PL
verweisen	verwiesen	V;SBJV;PL;3;PST
berechnen	berechnet	V;IND;PL;2;PRS
gerben	gerbtest	V;IND;SG;2;PST
gleichen	glicht	V;IND;PL;2;PST
senken	senkt	V;IND;PL;2;PRS
geifern	geifere	V;SBJV;SG;1;PRS
Anlass	Anlässe	N;NOM;PL
Knackarsch	Knackärsche	N;GEN;PL
Mandarinente	Mandarinente	N;NOM;SG
entgehen	entgehe	V;IND;SG;1;PRS
Empfangsdame	Empfangsdame	N;DAT;SG
Eigenbrötlerei	Eigenbrötlereien	N;DAT;PL
Schüler	Schüler	N;ACC;PL
appellieren	appellierte	V;SBJV;SG;1;PST
zerquetschen	zerquetschte	V;SBJV;SG;3;PST
Psychotiker	Psychotiker	N;GEN;PL
unterrichten	unterrichten	V;SBJV;PL;1;PRS
Gardinenpredigt	Gardinenpredigt	N;DAT;SG
grinsen	grinstest	V;SBJV;SG;2;PST
verschwören	verschwört	V;IMP;PL;2
Pfosten	Pfosten	N;ACC;SG
besiegen	besiegen	V;SBJV;PL;3;PRS
Gästezimmer	Gästezimmer	N;DAT;SG
Kollokation	Kollokation	N;DAT;SG
Betttuch	Betttuch	N;NOM;SG
erobern	eroberten	V;SBJV;PL;1;PST
Notaufnahme	Notaufnahmen	N;ACC;PL
greinen	greinten	V;SBJV;PL;1;PST
Plüsch	Plüschen	N;DAT;PL
schummeln	schummelet	V;SBJV;PL;2;PRS
Cabriolet	Cabriolets	N;GEN;PL
Vögelchen	Vögelchen	N;DAT;SG
Mörser	Mörser	N;ACC;SG
Milliardstel	Milliardstel	N;NOM;SG
fiepen	fiepest	V;SBJV;SG;2;PRS
zerren	zerrt	V;IND;SG;3;PRS
Magnesiumsalz	Magnesiumsalze	N;ACC;PL
Kleintier	Kleintiere	N;NOM;PL
menstruieren	menstruieren	V;SBJV;PL;1;PRS
beweisen	bewies	V;IND;SG;1;PST
entführen	entführe	V;SBJV;SG;3;PRS
verlängern	verlängerten	V;IND;PL;3;PST
Facharzt	Fachärzten	N;DAT;PL
defragmentieren	defragmentierest	V;SBJV;SG;2;PRS
satteln	sattele	V;SBJV;SG;1;PRS
Aquarium	Aquarium	N;DAT;SG
Kernspaltung	Kernspaltung	N;GEN;SG
Trampeltier	Trampeltiere	N;ACC;PL
verändern	veränderst	V;IND;SG;2;PRS
infizieren	infizierte	V;SBJV;SG;1;PST
verzieren	verzierest	V;SBJV;SG;2;PRS
Mietvertrag	Mietverträgen	N;DAT;PL
Bromat	Bromaten	N;DAT;PL
bieren	biert	V;IND;SG;3;PRS
durchsuchen	durchsuchten	V;SBJV;PL;1;PST
Erfrischung	Erfrischungen	N;DAT;PL
Kreissäge	Kreissäge	N;NOM;SG
patentieren	patentieret	V;SBJV;PL;2;PRS
Ferchromid	Ferchromid	N;NOM;SG
hintertreiben	hintertrieb	V;IND;SG;3;PST
verabschieden	verabschieden	V;IND;PL;1;PRS
verschmelzen	verschmolzen	V;IND;PL;1;PST
melieren	melierst	V;IND;SG;2;PRS
entschlüsseln	entschlüsselten	V;IND;PL;1;PST
Bügelverschluß	Bügelverschlüsse	N;ACC;PL
Metropole	Metropolen	N;NOM;PL
Ausfall	Ausfälle	N;ACC;PL
wecken	weckt	V;IND;SG;3;PRS
kuscheln	kuscheln	V;IND;PL;3;PRS
Napfkuchen	Napfkuchen	N;DAT;PL
Affix	Affixe	N;GEN;PL
flicken	flickten	V;SBJV;PL;3;PST
Thermoelement	Thermoelemente	N;NOM;PL
verändern	verändertest	V;SBJV;SG;2;PST
verschaffen	verschaffen	V;NFIN
Feuerwehrfrau	Feuerwehrfrau	N;NOM;SG
Duell	Duelle	N;ACC;PL
reimen	reimte	V;IND;SG;3;PST
Unwahrheit	Unwahrheiten	N;ACC;PL
Nager	Nagers	N;GEN;SG
diffamieren	diffamiert	V;IND;SG;3;PRS
flicken	flickten	V;IND;PL;1;PST
Allee	Alleen	N;DAT;PL
Kleinplanet	Kleinplaneten	N;GEN;PL
entgehen	entgingst	V;IND;SG;2;PST
Beschreibung	Beschreibungen	N;GEN;PL
Zugang	Zugang	N;DAT;SG
Einkristall	Einkristalle	N;GEN;PL
Kilogramm	Kilogramm	N;ACC;SG
Eisenstein	Eisensteine	N;NOM;PL
Blattlaus	Blattlaus	N;NOM;SG
Fürwort	Fürwörtern	N;DAT;PL
Rettungsring	Rettungsring	N;DAT;SG
Fluglinie	Fluglinie	N;GEN;SG
emulieren	emulieren	V;NFIN
Befehl	Befehle	N;ACC;PL
Alphabet	Alphabet	N;ACC;SG
Kürbis	Kürbis	N;NOM;SG
menstruieren	menstruierte	V;SBJV;SG;1;PST
Verstaatlichung	Verstaatlichung	N;GEN;SG
Schlagsahne	Schlagsahne	N;DAT;SG
Facharzt	Facharztes	N;GEN;SG
karren	karrten	V;SBJV;PL;3;PST
summen	summten	V;SBJV;PL;3;PST
gurgeln	gurgelt	V;IMP;PL;2
entschlüsseln	entschlüsseltest	V;IND;SG;2;PST
Alkoholiker	Alkoholiker	N;NOM;PL
Sendegerät	Sendegeräten	N;DAT;PL
Halbstufenpotential	Halbstufenpotential	N;ACC;SG
kümmern	kümmere	V;SBJV;SG;1;PRS
polarisieren	polarisierte	V;IND;SG;3;PST
Vorbemerkung	Vorbemerkungen	N;ACC;PL
fiepen	fiepen	V;SBJV;PL;1;PRS
Madenwurm	Madenwürmer	N;ACC;PL
Kehrwert	Kehrwert	N;NOM;SG
Anlass	Anlass	N;ACC;SG
evaluieren	evaluiert	V;IND;PL;2;PRS
Heliumisotop	Heliumisotops	N;GEN;SG
atomisieren	atomisierten	V;SBJV;PL;3;PST
Handelsmarine	Handelsmarine	N;NOM;SG
schummeln	schummeln	V;IND;PL;1;PRS
tappen	tappten	V;IND;PL;3;PST
vergraulen	vergraulten	V;IND;PL;1;PST
braten	brieten	V;IND;PL;3;PST
patentieren	patentieren	V;NFIN
verlängern	verlängert	V;IND;PL;2;PRS
Schulbuch	Schulbuches	N;GEN;SG
Lid	Lid	N;DAT;SG
atomisieren	atomisierte	V;SBJV;SG;3;PST
türmen	türme	V;IND;SG;1;PRS
schmauchen	schmauchte	V;IND;SG;3;PST
Abstecher	Abstecher	N;NOM;PL
betreten	beträtest	V;SBJV;SG;2;PST
marinieren	marinierten	V;IND;PL;1;PST
oktroyieren	oktroyierten	V;SBJV;PL;3;PST
Energieniveau	Energieniveaus	N;DAT;PL
drohen	droh	V;IMP;SG;2
Ausbeuterin	Ausbeuterinnen	N;NOM;PL
Leichnam	Leichname	N;ACC;PL
entführen	entführtest	V;SBJV;SG;2;PST
persiflieren	persifliert	V;IMP;PL;2
summen	summen	V;IND;PL;1;PRS
kampieren	kampiere	V;SBJV;SG;1;PRS
versäumen	versäumet	V;SBJV;PL;2;PRS
verweisen	verwies	V;IND;SG;1;PST
melieren	meliertest	V;SBJV;SG;2;PST
Hehler	Hehler	N;ACC;PL
Investition	Investition	N;ACC;SG
unterrichten	unterrichtest	V;SBJV;SG;2;PRS
braten	brietet	V;SBJV;PL;2;PST
schwären	schwäret	V;SBJV;PL;2;PRS
kodieren	kodiert	V;IMP;PL;2
Polin	Polin	N;ACC;SG
Muttersöhnchen	Muttersöhnchen	N;NOM;PL
infizieren	infizierten	V;IND;PL;1;PST
Beschleunigungssensor	Beschleunigungssensoren	N;DAT;PL
Telefonseelsorge	Telefonseelsorge	N;DAT;SG
zerren	zerrte	V;IND;SG;1;PST
Adenin	Adenin	N;DAT;SG
emulieren	emuliere	V;SBJV;SG;3;PRS
Türklingel	Türklingel	N;ACC;SG
beäugen	beäugte	V;IND;SG;3;PST
Sehne	Sehne	N;GEN;SG
Bündnis	Bündnis	N;NOM;SG
entführen	entführe	V;IND;SG;1;PRS
Ferchromid	Ferchromids	N;GEN;SG
Präparator	Präparator	N;NOM;SG
zerren	zerren	V;IND;PL;1;PRS
Atomphysiker	Atomphysiker	N;GEN;PL
Pfosten	Pfostens	N;GEN;SG
patzen	patzen	V;SBJV;PL;1;PRS
Nanodraht	Nanodrähten	N;DAT;PL
zügeln	zügelt	V;IMP;PL;2
Gallenblase	Gallenblasen	N;ACC;PL
Beifahrer	Beifahrers	N;GEN;SG
zwangsernähren	zwangsernähren	V;IND;PL;1;PRS
Nebelgranate	Nebelgranaten	N;ACC;PL
Knackarsch	Knackarsch	N;ACC;SG
detektieren	detektierte	V;SBJV;SG;3;PST
Gästezimmer	Gästezimmern	N;DAT;PL
Bodyguard	Bodyguards	N;GEN;SG
Telephon	Telephone	N;GEN;PL
nächtigen	nächtigte	V;SBJV;SG;3;PST
Intuition	Intuition	N;ACC;SG
verändern	verändertet	V;IND;PL;2;PST
Murmel	Murmeln	N;DAT;PL
buddeln	buddelst	V;IND;SG;2;PRS
Werbespot	Werbespots	N;ACC;PL
Krücke	Krücken	N;NOM;PL
Edukt	Edukten	N;DAT;PL
Partie	Partien	N;DAT;PL
begrabschen	begrabsche	V;SBJV;SG;1;PRS
Freizeit	Freizeiten	N;ACC;PL
Koordinatenachse	Koordinatenachsen	N;DAT;PL
Wipfel	Wipfel	N;GEN;PL
Lid	Lider	N;GEN;PL
Einklang	Einklänge	N;GEN;PL
rennen	renntet	V;SBJV;PL;2;PST
kampieren	kampiert	V;IND;SG;3;PRS
Größe	Größen	N;ACC;PL
nächtigen	nächtigen	V;SBJV;PL;3;PRS
argumentieren	argumentieret	V;SBJV;PL;2;PRS
Saibling	Saibling	N;ACC;SG
billigen	billigten	V;IND;PL;1;PST
Murmel	Murmel	N;DAT;SG
Taschenwörterbuch	Taschenwörterbuch	N;ACC;SG
Froschmann	Froschmänner	N;ACC;PL
Konzernumsatz	Konzernumsatzes	N;GEN;SG
Delta	Delten	N;DAT;PL
Pfosten	Pfosten	N;ACC;PL
Buntstift	Buntstiften	N;DAT;PL
Kilogramm	Kilogramme	N;NOM;PL
Heliumisotop	Heliumisotop	N;NOM;SG
Illustrator	Illustrator	N;ACC;SG
karren	karrten	V;IND;PL;1;PST
Schwellenwert	Schwellenwert	N;DAT;SG
Zwangsarbeiter	Zwangsarbeiter	N;GEN;PL
Boson	Bosonen	N;ACC;PL
schimmeln	schimmelten	V;IND;PL;3;PST
Lesekopf	Leseköpfe	N;ACC;PL
internationalisieren	internationalisiert	V;IND;SG;3;PRS
Rille	Rillen	N;GEN;PL
Befürworter	Befürworter	N;GEN;PL
Binnenländerin	Binnenländerinnen	N;NOM;PL
karren	karrt	V;IND;SG;3;PRS
Menage	Menage	N;GEN;SG
verchromen	verchromte	V;IND;SG;1;PST
Parzelle	Parzellen	N;ACC;PL
Petersfisch	Petersfische	N;NOM;PL
Hörsaal	Hörsäle	N;ACC;PL
Hehler	Hehler	N;ACC;SG
Honorar	Honorar	N;NOM;SG
branden	branden	V;NFIN
Quartett	Quartette	N;GEN;PL
Bon	Bon	N;NOM;SG
diffamieren	diffamiertest	V;IND;SG;2;PST
Komplex	Komplexe	N;GEN;PL
zerren	zerrte	V;SBJV;SG;3;PST
knicken	knickt	V;IND;SG;3;PRS
Klärung	Klärung	N;DAT;SG
bieren	biere	V;SBJV;SG;1;PRS
begrabschen	begrabschen	V;IND;PL;1;PRS
Garbe	Garbe	N;NOM;SG
gurgeln	gurgelte	V;IND;SG;3;PST
oktroyieren	oktroyierest	V;SBJV;SG;2;PRS
Gesamtkunstwerk	Gesamtkunstwerke	N;GEN;PL
Gladiole	Gladiole	N;GEN;SG
katapultieren	katapultieren	V;IND;PL;3;PRS
rasen	rast	V;IMP;PL;2
appellieren	appellier	V;IMP;SG;2
erkundigen	erkundige	V;IND;SG;1;PRS
Reinigung	Reinigung	N;DAT;SG
Kaliber	Kaliber	N;NOM;PL
destillieren	destilliere	V;SBJV;SG;3;PRS
Schulbuch	Schulbücher	N;GEN;PL
erobern	erobertet	V;IND;PL;2;PST
greinen	greine	V;SBJV;SG;1;PRS
Zain	Zaine	N;NOM;PL
Freizeitzentrum	Freizeitzentren	N;DAT;PL
Tinktur	Tinkturen	N;DAT;PL
Kerbel	Kerbel	N;NOM;SG
Büffel	Büffel	N;ACC;PL
buddeln	buddeln	V;IND;PL;1;PRS
akzeptieren	akzeptierst	V;IND;SG;2;PRS
Kürbis	Kürbisses	N;GEN;SG
feien	feie	V;IND;SG;1;PRS
Bändchen	Bändchen	N;ACC;SG
Weichholz	Weichhölzer	N;ACC;PL
löten	löte	V;SBJV;SG;1;PRS
geschehen	geschähe	V;SBJV;SG;1;PST
Kaplöwe	Kaplöwen	N;GEN;PL
Käsemacherin	Käsemacherin	N;NOM;SG
internationalisieren	internationalisieren	V;IND;PL;1;PRS
zupfen	zupfe	V;SBJV;SG;1;PRS
verlieben	verlieb	V;IMP;SG;2
trauen	trauten	V;SBJV;PL;1;PST
Eidechse	Eidechse	N;ACC;SG
süßen	süßen	V;SBJV;PL;1;PRS
goutieren	goutierest	V;SBJV;SG;2;PRS
beschlagnahmen	beschlagnahmte	V;SBJV;SG;1;PST
Holmium	Holmium	N;DAT;SG
stöhnen	stöhnen	V;IND;PL;1;PRS
Vernichtungslager	Vernichtungslager	N;ACC;SG
Halbwahrheit	Halbwahrheit	N;DAT;SG
Xenophilie	Xenophilie	N;GEN;SG
fragmentieren	fragmentieren	V;SBJV;PL;1;PRS
Sängerin	Sängerinnen	N;ACC;PL
vernetzen	vernetzt	V;IMP;PL;2
Eisenoxid	Eisenoxiden	N;DAT;PL
vermitteln	vermitteln	V;IND;PL;3;PRS
schachern	schacherte	V;SBJV;SG;3;PST
Falsett	Falsette	N;ACC;PL
Milchschlange	Milchschlangen	N;ACC;PL
glorifizieren	glorifiziert	V;IND;PL;2;PRS
zentrieren	zentrierte	V;IND;SG;3;PST
gebrauchen	gebrauchen	V;IND;PL;3;PRS
weißsagen	weißsagtest	V;SBJV;SG;2;PST
Stativ	Stative	N;GEN;PL
Bestatterin	Bestatterin	N;NOM;SG
zuckern	zuckerten	V;SBJV;PL;3;PST
bewässern	bewässertet	V;SBJV;PL;2;PST
veranlassen	veranlasset	V;SBJV;PL;2;PRS
ondulieren	onduliert	V;IMP;PL;2
Bezauberung	Bezauberung	N;NOM;SG
Kornett	Kornetten	N;DAT;PL
Sitzkrieg	Sitzkrieges	N;GEN;SG
horchen	horcht	V;IMP;PL;2
Vorstandssprecher	Vorstandssprechern	N;DAT;PL
Synthese	Synthesen	N;NOM;PL
befinden	befinden	V;IND;PL;3;PRS
tapezieren	tapezierte	V;SBJV;SG;3;PST
Zelt	Zeltes	N;GEN;SG
Prunksaal	Prunksäle	N;GEN;PL
Waschanlage	Waschanlage	N;DAT;SG
lokalisieren	lokalisiert	V;IND;SG;3;PRS
Deckenzapfen	Deckenzapfens	N;GEN;SG
horchen	horchest	V;SBJV;SG;2;PRS
zaubern	zaubere	V;SBJV;SG;3;PRS
Wasserwanze	Wasserwanze	N;NOM;SG
Atomwaffe	Atomwaffe	N;DAT;SG
vermeßen	vermeße	V;SBJV;SG;3;PRS
Höhlenbewohnerin	Höhlenbewohnerin	N;NOM;SG
Aussprachewörterbuch	Aussprachewörterbuches	N;GEN;SG
Bogenfenster	Bogenfenster	N;DAT;SG
gratulieren	gratulierte	V;IND;SG;3;PST
Wirkung	Wirkung	N;GEN;SG
mulchen	mulche	V;SBJV;SG;3;PRS
kabeln	kabeln	V;SBJV;PL;1;PRS
Schauer	Schauer	N;NOM;PL
grausen	grausten	V;IND;PL;1;PST
Krähenfraß	Krähenfraßen	N;DAT;PL
Mutlosigkeit	Mutlosigkeit	N;NOM;SG
dimerisieren	dimerisierten	V;IND;PL;1;PST
Stadtzentrum	Stadtzentren	N;NOM;PL
Lektüre	Lektüren	N;DAT;PL
erfreuen	erfreuen	V;IND;PL;3;PRS
statuieren	statuierte	V;SBJV;SG;1;PST
begrapschen	begrapsche	V;SBJV;SG;3;PRS
Serenade	Serenaden	N;ACC;PL
Grotte	Grotte	N;ACC;SG
Simse	Simse	N;NOM;SG
transportieren	transportieren	V;IND;PL;1;PRS
schröpfen	schröpftest	V;SBJV;SG;2;PST
Chinese	Chinesen	N;DAT;SG
Novize	Novize	N;NOM;SG
nummerieren	nummerieren	V;IND;PL;1;PRS
desinfizieren	desinfizierte	V;IND;SG;1;PST
besteuern	besteuerten	V;SBJV;PL;3;PST
Kaffeetasse	Kaffeetasse	N;ACC;SG
Spirale	Spirale	N;NOM;SG
erschiessen	erschiesst	V;IND;PL;2;PRS
Bambuswald	Bambuswäldern	N;DAT;PL
Zugabe	Zugabe	N;DAT;SG
Unter	Untern	N;DAT;PL
fauchen	fauche	V;SBJV;SG;3;PRS
saunieren	saunierten	V;IND;PL;1;PST
Verdacht	Verdachtes	N;GEN;SG
Humpen	Humpen	N;GEN;PL
tendieren	tendierte	V;IND;SG;3;PST
Sitzplatz	Sitzplätze	N;GEN;PL
Antagonist	Antagonisten	N;DAT;PL
absorbieren	absorbiere	V;SBJV;SG;1;PRS
Löllingit	Löllingit	N;DAT;SG
Fischbestand	Fischbeständen	N;DAT;PL
Taxifahrerin	Taxifahrerin	N;ACC;SG
Infekt	Infektes	N;GEN;SG
Mull	Mulle	N;GEN;PL
Promenade	Promenaden	N;DAT;PL
Geschmackssinn	Geschmackssinne	N;GEN;PL
Samstagvormittag	Samstagvormittagen	N;DAT;PL
Dekorierer	Dekorierer	N;ACC;PL
Erzherzogshütchen	Erzherzogshütchen	N;NOM;PL
lodern	loderet	V;SBJV;PL;2;PRS
funktionalisieren	funktionalisieret	V;SBJV;PL;2;PRS
Luftangriff	Luftangriff	N;NOM;SG
Jein	Jeins	N;NOM;PL
zentrieren	zentrierte	V;SBJV;SG;3;PST
Aak	Aak	N;ACC;SG
Therapie	Therapien	N;NOM;PL
Schönling	Schönling	N;NOM;SG
Kartenhaus	Kartenhaus	N;ACC;SG
Patronymikon	Patronymikon	N;ACC;SG
Jein	Jein	N;ACC;SG
Schweinerei	Schweinereien	N;GEN;PL
urinieren	urinieren	V;NFIN
Polypropylen	Polypropylene	N;ACC;PL
Selenat	Selenaten	N;DAT;PL
Sellait	Sellaite	N;GEN;PL
verlagern	verlagre	V;IMP;SG;2
Aufgebot	Aufgebote	N;NOM;PL
Auswahl	Auswahlen	N;ACC;PL
verbünden	verbündeten	V;IND;PL;3;PST
Baumarkt	Baumärkte	N;NOM;PL
meistern	meisterte	V;IND;SG;3;PST
Safe	Safes	N;NOM;PL
protokollieren	protokollieren	V;SBJV;PL;1;PRS
bezaubern	bezaubre	V;IMP;SG;2
Aufmerksamkeit	Aufmerksamkeit	N;ACC;SG
Cholin	Cholin	N;NOM;SG
Mönchsgeier	Mönchsgeier	N;ACC;SG
Einbahnstraße	Einbahnstraßen	N;GEN;PL
Sketsch	Sketsch	N;NOM;SG
flanieren	flanierte	V;IND;SG;3;PST
ordern	ordere	V;SBJV;SG;3;PRS
Grotte	Grotten	N;NOM;PL
Wange	Wangen	N;NOM;PL
herrschen	herrschtest	V;IND;SG;2;PST
Flößer	Flößer	N;ACC;SG
grollen	grolle	V;SBJV;SG;1;PRS
Sozialarbeiter	Sozialarbeiter	N;NOM;PL
hallen	hallen	V;SBJV;PL;1;PRS
Lappe	Lappen	N;GEN;PL
Protonenzahl	Protonenzahl	N;NOM;SG
paaren	paartest	V;IND;SG;2;PST
mobben	mobbte	V;SBJV;SG;3;PST
Fahne	Fahne	N;ACC;SG
bumsen	bumsten	V;IND;PL;1;PST
heften	hefteten	V;SBJV;PL;1;PST
mümmeln	mümmelt	V;IND;PL;2;PRS
Dichtstoff	Dichtstoffe	N;NOM;PL
Absorber	Absorber	N;GEN;PL
Grande	Granden	N;ACC;SG
ficken	ficktest	V;IND;SG;2;PST
Pfuhl	Pfuhl	N;ACC;SG
Ballen	Ballen	N;GEN;PL
Kehrseite	Kehrseite	N;ACC;SG
Schauspieler	Schauspieler	N;ACC;PL
Fachmarkt	Fachmarkt	N;ACC;SG
horchen	horchen	V;IND;PL;1;PRS
schleichen	schleicht	V;IMP;PL;2
entschärfen	entschärfen	V;IND;PL;1;PRS
Frikativ	Frikativs	N;GEN;SG
Berufungsgericht	Berufungsgerichte	N;NOM;PL
Protagonist	Protagonisten	N;GEN;PL
Sense	Sense	N;ACC;SG
charakterisieren	charakterisiere	V;IND;SG;1;PRS
prügeln	prügelte	V;IND;SG;3;PST
entfliehen	entflieh	V;IMP;SG;2
leuchten	leuchtete	V;SBJV;SG;1;PST
Backe	Backen	N;DAT;PL
prophezeien	prophezeit	V;IND;PL;2;PRS
verladen	verlüden	V;SBJV;PL;1;PST
denaturieren	denaturiert	V;IND;SG;3;PRS
Enterich	Enterich	N;DAT;SG
rosten	rosten	V;IND;PL;3;PRS
Anstecker	Ansteckern	N;DAT;PL
Jemenit	Jemeniten	N;ACC;PL
verschleißen	verschleißen	V;IND;PL;3;PRS
panieren	paniertest	V;IND;SG;2;PST
Ohnmacht	Ohnmacht	N;DAT;SG
Bleichstoff	Bleichstoffes	N;GEN;SG
versemmeln	versemmle	V;IMP;SG;2
Königstiger	Königstiger	N;DAT;SG
Ingredienz	Ingredienz	N;NOM;SG
Entdeckung	Entdeckungen	N;DAT;PL
Discount	Discounts	N;DAT;PL
verteilen	verteile	V;IND;SG;1;PRS
Ersuchen	Ersuchen	N;NOM;PL
Cornwallit	Cornwallite	N;NOM;PL
zittern	zitterten	V;SBJV;PL;3;PST
Protolyse	Protolysen	N;DAT;PL
Epoxid	Epoxide	N;NOM;PL
Dicke	Dicken	N;GEN;PL
Iberer	Iberer	N;NOM;SG
Kürbiskern	Kürbiskern	N;DAT;SG
kacheln	kacheln	V;IND;PL;3;PRS
Abartigkeit	Abartigkeiten	N;NOM;PL
modellieren	modellieren	V;NFIN
Alkylrest	Alkylreste	N;ACC;PL
formulieren	formulierest	V;SBJV;SG;2;PRS
Seltenerdmagnet	Seltenerdmagnete	N;GEN;PL
Ausrede	Ausreden	N;GEN;PL
entwischen	entwischte	V;IND;SG;1;PST
Dia	Dias	N;NOM;PL
Quittung	Quittungen	N;ACC;PL
Raucherin	Raucherinnen	N;ACC;PL
Wortanfang	Wortanfang	N;DAT;SG
Dichtung	Dichtung	N;DAT;SG
Langstreckenläufer	Langstreckenläufer	N;ACC;PL
verschlacken	verschlacken	V;IND;PL;1;PRS
bremsen	bremsen	V;NFIN
übermitteln	übermittele	V;SBJV;SG;1;PRS
Halogenid	Halogenid	N;ACC;SG
replizieren	repliziertet	V;SBJV;PL;2;PST
Aufzug	Aufzüge	N;ACC;PL
Ente	Ente	N;ACC;SG
Gefieder	Gefieder	N;ACC;PL
Kleptokratie	Kleptokratien	N;ACC;PL
erfüllen	erfülle	V;SBJV;SG;3;PRS
Kohlenstoffatom	Kohlenstoffatom	N;NOM;SG
replicieren	repliciere	V;IND;SG;1;PRS
lehren	lehrtest	V;SBJV;SG;2;PST
gähnen	gähnte	V;IND;SG;1;PST
überfordern	überfordern	V;IND;PL;1;PRS
Schrei	Schrei	N;NOM;SG
Programmiererin	Programmiererinnen	N;ACC;PL
Grundbestandteil	Grundbestandteil	N;DAT;SG
Gleis	Gleis	N;DAT;SG
Schleife	Schleifen	N;GEN;PL
rinnen	rinnt	V;IND;PL;2;PRS
Standardaussprache	Standardaussprache	N;GEN;SG
subtrahieren	subtrahiere	V;IND;SG;1;PRS
verdrießen	verdrieße	V;IND;SG;1;PRS
brennen	brennst	V;IND;SG;2;PRS
Metallselenid	Metallselenid	N;DAT;SG
chauffieren	chauffierten	V;SBJV;PL;3;PST
bröseln	bröselet	V;SBJV;PL;2;PRS
emigrieren	emigrierten	V;IND;PL;3;PST
tätigen	tätigen	V;IND;PL;3;PRS
verlangen	verlangtest	V;IND;SG;2;PST
wassern	wassre	V;IMP;SG;2
einschätzen	einschätzen	V;NFIN
krosen	krost	V;IMP;PL;2
wetzen	wetztest	V;SBJV;SG;2;PST
Demagoge	Demagogen	N;ACC;SG
Reh	Reh	N;ACC;SG
Bindemittel	Bindemittel	N;GEN;PL
Bromaromat	Bromaromaten	N;NOM;PL
unterlassen	unterlasst	V;IND;PL;2;PRS
sublimieren	sublimiere	V;SBJV;SG;1;PRS
booten	booten	V;SBJV;PL;1;PRS
bewaffnen	bewaffneten	V;SBJV;PL;1;PST
Feuerbohne	Feuerbohnen	N;ACC;PL
onanieren	onaniertest	V;SBJV;SG;2;PST
Elixier	Elixiers	N;GEN;SG
Lerche	Lerchen	N;ACC;PL
Bombenleger	Bombenleger	N;DAT;SG
Nachtmusik	Nachtmusiken	N;NOM;PL
Junior	Juniors	N;GEN;SG
Messias	Messias	N;DAT;SG
Thüringerin	Thüringerinnen	N;ACC;PL
Sympodium	Sympodien	N;DAT;PL
Sicherheit	Sicherheit	N;ACC;SG
Migräne	Migränen	N;ACC;PL
runzeln	runzele	V;SBJV;SG;1;PRS
Örtlichkeit	Örtlichkeiten	N;DAT;PL
Calciummangel	Calciummangel	N;DAT;SG
flirren	flirrtet	V;IND;PL;2;PST
Übersicht	Übersichten	N;GEN;PL
beschleunigen	beschleunige	V;SBJV;SG;3;PRS
meißeln	meißelte	V;SBJV;SG;1;PST
Emissär	Emissäre	N;GEN;PL
Steueroase	Steueroase	N;GEN;SG
tagträumen	tagträumte	V;SBJV;SG;3;PST
Weltmarktpreis	Weltmarktpreise	N;ACC;PL
Note	Note	N;GEN;SG
hasten	haste	V;SBJV;SG;3;PRS
mailen	mailen	V;IND;PL;3;PRS
foltern	foltert	V;IND;PL;2;PRS
erwärmen	erwärmen	V;IND;PL;3;PRS
fladern	fladern	V;NFIN
Rast	Rast	N;GEN;SG
Keltibererin	Keltibererin	N;DAT;SG
lizenzieren	lizenzierte	V;IND;SG;1;PST
Mora	Mora	N;ACC;SG
knechten	knechtet	V;IMP;PL;2
Arsch	Arsches	N;GEN;SG
winseln	winsle	V;IND;SG;1;PRS
verschlimmbessern	verschlimmbessern	V;SBJV;PL;1;PRS
erwachen	erwachtet	V;IND;PL;2;PST
Katalase	Katalase	N;NOM;SG
Ausstiegstür	Ausstiegstür	N;DAT;SG
belästigen	belästigte	V;IND;SG;3;PST
bestellen	bestellst	V;IND;SG;2;PRS
Apastron	Apastra	N;DAT;PL
Schreiner	Schreiner	N;ACC;PL
Baskin	Baskinnen	N;GEN;PL
beanspruchen	beanspruchte	V;SBJV;SG;3;PST
Wohnraum	Wohnraumes	N;GEN;SG
Aquakomplex	Aquakomplexes	N;GEN;SG
bepissen	bepisste	V;SBJV;SG;3;PST
Pauschale	Pauschalen	N;GEN;PL
spreizen	spreizten	V;IND;PL;3;PST
erschiessen	erschösse	V;SBJV;SG;3;PST
traumatisieren	traumatisiert	V;IMP;PL;2
Espe	Espen	N;NOM;PL
Geländer	Geländers	N;GEN;SG
hasten	hastetet	V;SBJV;PL;2;PST
Abbild	Abbild	N;NOM;SG
Ärztin	Ärztinnen	N;ACC;PL
Provisorium	Provisorien	N;NOM;PL
genieren	genieren	V;IND;PL;1;PRS
assistieren	assistiertest	V;IND;SG;2;PST
browsen	browste	V;IND;SG;1;PST
Scheinbuche	Scheinbuche	N;GEN;SG
Sträßchen	Sträßchen	N;ACC;SG
verhören	verhörten	V;SBJV;PL;3;PST
kalfatern	kalfatere	V;SBJV;SG;3;PRS
postulieren	postulierte	V;IND;SG;3;PST
Pentaborat	Pentaborate	N;NOM;PL
Geleitwort	Geleitwort	N;NOM;SG
Natter	Nattern	N;DAT;PL
Farblack	Farblacke	N;NOM;PL
Extrem	Extrems	N;GEN;SG
Fensterscheibe	Fensterscheibe	N;NOM;SG
prostituieren	prostituiere	V;IND;SG;1;PRS
erbarmen	erbarmtet	V;SBJV;PL;2;PST
Stannit	Stannit	N;DAT;SG
Fahnder	Fahnder	N;ACC;SG
rüffeln	rüffeln	V;IND;PL;3;PRS
kippen	kipp	V;IMP;SG;2
offenbaren	offenbare	V;SBJV;SG;1;PRS
ersetzen	ersetztest	V;IND;SG;2;PST
Schmelz	Schmelze	N;GEN;PL
Kiefernwald	Kiefernwälder	N;GEN;PL
homogenisieren	homogenisierte	V;SBJV;SG;3;PST
Aneurysma	Aneurysmas	N;GEN;SG
Mitstudent	Mitstudent	N;NOM;SG
rätseln	rätselten	V;IND;PL;3;PST
erkalten	erkalten	V;IND;PL;3;PRS
Farbfernseher	Farbfernseher	N;ACC;SG
Singhalese	Singhalesen	N;ACC;SG
verrechnen	verrechnetest	V;SBJV;SG;2;PST
sabbern	sabbern	V;SBJV;PL;1;PRS
Bitterkeit	Bitterkeiten	N;NOM;PL
spotten	spotten	V;SBJV;PL;3;PRS
Kassenbon	Kassenbon	N;ACC;SG
Schießgewehr	Schießgewehr	N;ACC;SG
bezwingen	bezwängen	V;SBJV;PL;1;PST
reüssieren	reüssieren	V;SBJV;PL;3;PRS
integrieren	integrierte	V;SBJV;SG;1;PST
Höcker	Höcker	N;NOM;SG
bedingen	bedingten	V;SBJV;PL;3;PST
stationieren	stationiert	V;IMP;PL;2
Rasur	Rasuren	N;DAT;PL
Depolarisation	Depolarisationen	N;ACC;PL
henken	henkte	V;IND;SG;3;PST
Abdankung	Abdankung	N;NOM;SG
Ablagerung	Ablagerungen	N;GEN;PL
tätigen	tätigt	V;IND;SG;3;PRS
Überklasse	Überklassen	N;GEN;PL
Oberkellner	Oberkellners	N;GEN;SG
brandschatzen	brandschatzte	V;IND;SG;1;PST
schalten	schalte	V;IMP;SG;2
Hommage	Hommage	N;ACC;SG
beziffern	bezifferte	V;SBJV;SG;3;PST
Isotopengemisch	Isotopengemisch	N;ACC;SG
Halogenkohlenwasserstoff	Halogenkohlenwasserstoffe	N;NOM;PL
Hurriterin	Hurriterin	N;GEN;SG
bedrucken	bedruck	V;IMP;SG;2
durchqueren	durchquerte	V;IND;SG;3;PST
grenzen	grenztet	V;IND;PL;2;PST
bequemben	bequembt	V;IND;SG;3;PRS
Gütdunken	Gütdunkens	N;GEN;SG
zappen	zappen	V;IND;PL;1;PRS
Insektizid	Insektiziden	N;DAT;PL
befassen	befasstest	V;SBJV;SG;2;PST
Clownfisch	Clownfisch	N;ACC;SG
Ehe	Ehe	N;GEN;SG
Mineralstoffwechsel	Mineralstoffwechsel	N;DAT;SG
Haushalt	Haushalten	N;DAT;PL
rummeln	rummeltet	V;IND;PL;2;PST
Grabhügel	Grabhügel	N;ACC;PL
diffundieren	diffundiertet	V;IND;PL;2;PST
Strafrechtler	Strafrechtler	N;NOM;SG
wässern	wässerten	V;IND;PL;1;PST
beneiden	beneidete	V;IND;SG;3;PST
Scheune	Scheunen	N;NOM;PL
Müllverbrennungsanlage	Müllverbrennungsanlagen	N;NOM;PL
spiegeln	spiegeln	V;SBJV;PL;1;PRS
Kreatur	Kreaturen	N;GEN;PL
Hottentottenente	Hottentottenenten	N;GEN;PL
Bornit	Bornite	N;NOM;PL
identifizieren	identifizierte	V;SBJV;SG;3;PST
Ulmer	Ulmer	N;NOM;SG
scheiden	scheidet	V;SBJV;PL;2;PRS
quarzen	quarzte	V;IND;SG;1;PST
offenbaren	offenbartet	V;IND;PL;2;PST
Sojamehl	Sojamehle	N;ACC;PL
vergiften	vergiftet	V;IND;PL;2;PRS
Schreibung	Schreibungen	N;DAT;PL
mißbrauchen	mißbrauchen	V;IND;PL;1;PRS
plagiieren	plagiierte	V;SBJV;SG;1;PST
studieren	studierte	V;SBJV;SG;1;PST
entkeimen	entkeimest	V;SBJV;SG;2;PRS
fahnden	fahndete	V;SBJV;SG;1;PST
glosen	glost	V;IND;PL;2;PRS
Krankenhäuschen	Krankenhäuschen	N;DAT;SG
Bedürftigkeit	Bedürftigkeit	N;ACC;SG
kentern	kentern	V;IND;PL;1;PRS
Jolle	Jolle	N;NOM;SG
Gaul	Gaul	N;DAT;SG
Libanesin	Libanesinnen	N;GEN;PL
salutieren	salutiertet	V;IND;PL;2;PST
kommunizieren	kommunizieren	V;NFIN
blenden	blende	V;SBJV;SG;3;PRS
europäisieren	europäisieren	V;SBJV;PL;1;PRS
fummeln	fummelte	V;SBJV;SG;3;PST
wuscheln	wuschelte	V;SBJV;SG;3;PST
Staatsanwaltschaft	Staatsanwaltschaft	N;ACC;SG
entlasten	entlastet	V;IMP;PL;2
diffundieren	diffundierte	V;IND;SG;1;PST
Nullpunkt	Nullpunkte	N;GEN;PL
Kofferraum	Kofferräume	N;GEN;PL
Raumtemperatur	Raumtemperatur	N;NOM;SG
verjähren	verjährtest	V;SBJV;SG;2;PST
vermeßen	vermeßet	V;SBJV;PL;2;PRS
Benutzername	Benutzernamen	N;NOM;PL
entfesseln	entfesseln	V;IND;PL;1;PRS
befreien	befreit	V;IMP;PL;2
blitzen	blitztet	V;SBJV;PL;2;PST
keimen	keimen	V;IND;PL;3;PRS
Broschüre	Broschüren	N;NOM;PL
Melodie	Melodien	N;GEN;PL
Fantasie	Fantasien	N;ACC;PL
extrahieren	extrahiert	V;IND;PL;2;PRS
nieten	nieten	V;NFIN
lieben	liebtet	V;SBJV;PL;2;PST
bewohnen	bewohne	V;SBJV;SG;1;PRS
Aspartat	Aspartats	N;GEN;SG
kitzeln	kitzele	V;SBJV;SG;1;PRS
Keltiberer	Keltiberer	N;GEN;PL
Schlachtfeld	Schlachtfeld	N;DAT;SG
Meeresboden	Meeresboden	N;ACC;SG
Exposee	Exposees	N;GEN;SG
halbieren	halbiere	V;SBJV;SG;3;PRS
Bonvivant	Bonvivants	N;GEN;SG
umhüllen	umhüllen	V;NFIN
dementieren	dementierten	V;IND;PL;3;PST
Natriumsalz	Natriumsalz	N;DAT;SG
Ablehnung	Ablehnung	N;DAT;SG
Verkehrsflugzeug	Verkehrsflugzeuge	N;ACC;PL
Henne	Hennen	N;NOM;PL
Latexrock	Latexröcken	N;DAT;PL
spitzen	spitzen	V;SBJV;PL;1;PRS
leuchten	leuchtetest	V;SBJV;SG;2;PST
Berichtigung	Berichtigung	N;NOM;SG
rauchen	raucht	V;IMP;PL;2
Panel	Panel	N;DAT;SG
schwindeln	schwindeltest	V;SBJV;SG;2;PST
Zinnsalz	Zinnsalz	N;ACC;SG
Einheit	Einheit	N;GEN;SG
Fräulein	Fräulein	N;DAT;SG
Werfall	Werfälle	N;ACC;PL
boykottieren	boykottierten	V;SBJV;PL;1;PST
Kleiderstoff	Kleiderstoff	N;ACC;SG
Steppenwaran	Steppenwaran	N;NOM;SG
Weltraumteleskop	Weltraumteleskops	N;GEN;SG
Rechenbrett	Rechenbrettern	N;DAT;PL
beantragen	beantrag	V;IMP;SG;2
Widerstand	Widerständen	N;DAT;PL
Kotflügel	Kotflügeln	N;DAT;PL
knurren	knurren	V;SBJV;PL;3;PRS
Steuerbord	Steuerbord	N;NOM;SG
Ruck	Rucken	N;DAT;PL
heiraten	heiraten	V;IND;PL;1;PRS
Knipser	Knipsern	N;DAT;PL
Dekorierer	Dekorierers	N;GEN;SG
Voraussetzung	Voraussetzung	N;NOM;SG
Zahnfleisch	Zahnfleisches	N;GEN;SG
Tischler	Tischlers	N;GEN;SG
Trakt	Trakte	N;NOM;PL
erfrischen	erfrischt	V;IND;SG;3;PRS
ankern	ankerten	V;IND;PL;3;PST
erregen	erregest	V;SBJV;SG;2;PRS
lochen	locht	V;IMP;PL;2
erzeugen	erzeugen	V;IND;PL;3;PRS
reformieren	reformieren	V;IND;PL;1;PRS
Buddhist	Buddhisten	N;NOM;PL
kränken	kränkte	V;SBJV;SG;1;PST
stürmen	stürmen	V;SBJV;PL;1;PRS
Petalit	Petalite	N;NOM;PL
Schürze	Schürze	N;ACC;SG
Passionsfrucht	Passionsfrüchten	N;DAT;PL
freuen	freutest	V;IND;SG;2;PST
erdrücken	erdrück	V;IMP;SG;2
Rezitativ	Rezitativs	N;GEN;SG
recyceln	recycelt	V;IND;PL;2;PRS
Unbescholtenheit	Unbescholtenheit	N;GEN;SG
Apparatur	Apparaturen	N;ACC;PL
Grünspecht	Grünspechte	N;GEN;PL
Restbetrag	Restbetrages	N;GEN;SG
Rückruf	Rückruf	N;DAT;SG
galvanisieren	galvanisieren	V;SBJV;PL;1;PRS
Zimmerschlüssel	Zimmerschlüssel	N;DAT;SG
Abszess	Abszesse	N;ACC;PL
hasten	hasteten	V;SBJV;PL;1;PST
ringen	ringen	V;IND;PL;1;PRS
überqueren	überquertet	V;IND;PL;2;PST
schnarchen	schnarchet	V;SBJV;PL;2;PRS
scheffeln	scheffelt	V;IND;PL;2;PRS
Alarmsignal	Alarmsignale	N;GEN;PL
diversifizieren	diversifizierte	V;IND;SG;3;PST
Karlchen	Karlchens	N;GEN;SG
Eisengranat	Eisengranat	N;ACC;SG
spritzen	spritzen	V;IND;PL;3;PRS
Schlaraffenland	Schlaraffenländer	N;NOM;PL
blanchieren	blanchiertest	V;SBJV;SG;2;PST
Regenzeit	Regenzeit	N;NOM;SG
Pseudoephedrin	Pseudoephedrin	N;ACC;SG
moderieren	moderierte	V;IND;SG;1;PST
befolgen	befolgen	V;SBJV;PL;1;PRS
Seitenfläche	Seitenfläche	N;DAT;SG
Rentenmarkt	Rentenmarkt	N;NOM;SG
Frack	Frack	N;DAT;SG
jagen	jagen	V;IND;PL;1;PRS
Hautausschlag	Hautausschläge	N;NOM;PL
Bauch	Bauch	N;ACC;SG
Entfroster	Entfroster	N;NOM;SG
Tierquälerei	Tierquälereien	N;ACC;PL
entsaften	entsaftetet	V;SBJV;PL;2;PST
Ionenbindung	Ionenbindung	N;GEN;SG
panieren	panierten	V;SBJV;PL;3;PST
verzetteln	verzettele	V;SBJV;SG;1;PRS
Schirmherr	Schirmherr	N;NOM;SG
Medienhistorikerin	Medienhistorikerinnen	N;NOM;PL
Schrank	Schrank	N;DAT;SG
Cashflow	Cashflows	N;GEN;PL
Umlauf	Umläufe	N;GEN;PL
Sportler	Sportler	N;GEN;PL
Piratin	Piratin	N;NOM;SG
bedanken	bedankten	V;IND;PL;1;PST
Schwefeloxid	Schwefeloxid	N;NOM;SG
XOR-Gatter	XOR-Gatter	N;ACC;PL
verteilen	verteiltest	V;IND;SG;2;PST
Gesetzeshüter	Gesetzeshüter	N;DAT;SG
schweißen	schweißte	V;IND;SG;1;PST
dominieren	dominierten	V;SBJV;PL;1;PST
verschleiern	verschleierte	V;SBJV;SG;3;PST
Heiland	Heilande	N;ACC;PL
Wirtschaftswissenschaftler	Wirtschaftswissenschaftler	N;ACC;PL
Monoglycerid	Monoglycerid	N;ACC;SG
entfrosten	entfrostetest	V;IND;SG;2;PST
Magnolie	Magnolie	N;DAT;SG
bugsieren	bugsierten	V;IND;PL;1;PST
kapitulieren	kapituliertest	V;IND;SG;2;PST
fangen	fangen	V;NFIN
Sägezahn	Sägezähne	N;NOM;PL
Fotokopierer	Fotokopierern	N;DAT;PL
klimatisieren	klimatisiertet	V;IND;PL;2;PST
Reifizierung	Reifizierung	N;DAT;SG
Schädlingsbekämpfungsmittel	Schädlingsbekämpfungsmittel	N;ACC;SG
vertun	vertaten	V;IND;PL;3;PST
Taucherin	Taucherin	N;DAT;SG
verfärben	verfärbe	V;SBJV;SG;1;PRS
Affenpinscher	Affenpinscher	N;GEN;PL
entspringen	entspränge	V;SBJV;SG;1;PST
verwechseln	verwechselt	V;IND;PL;2;PRS
rußen	rußen	V;IND;PL;3;PRS
Schneekanone	Schneekanone	N;ACC;SG
Peroxidradikal	Peroxidradikale	N;NOM;PL
Riesenalk	Riesenalke	N;ACC;PL
Amtsantritt	Amtsantritte	N;ACC;PL
räsonieren	räsoniert	V;IND;PL;2;PRS
paraphrasieren	paraphrasierte	V;SBJV;SG;1;PST
Leutnant	Leutnante	N;GEN;PL
verwahrlosen	verwahrlosest	V;SBJV;SG;2;PRS
balkanisieren	balkanisiert	V;IND;SG;3;PRS
Fuchshund	Fuchshunde	N;NOM;PL
käufen	käuftet	V;IND;PL;2;PST
entkommen	entkommt	V;IND;SG;3;PRS
Öffner	Öffner	N;ACC;SG
Graphem	Graphem	N;DAT;SG
boßen	boßte	V;SBJV;SG;3;PST
Laib	Laib	N;NOM;SG
erwärmen	erwärmte	V;SBJV;SG;1;PST
Küster	Küster	N;ACC;PL
Druide	Druide	N;NOM;SG
Gegenspieler	Gegenspieler	N;NOM;SG
Fettmolekül	Fettmoleküle	N;ACC;PL
wuchern	wucherte	V;IND;SG;3;PST
Sonnabendabend	Sonnabendabend	N;NOM;SG
Wart	Warte	N;ACC;PL
möblieren	möblierten	V;IND;PL;3;PST
turnen	turnst	V;IND;SG;2;PRS
Premiere	Premieren	N;DAT;PL
Möbelstück	Möbelstücken	N;DAT;PL
entjungfern	entjungerest	V;SBJV;SG;2;PRS
Hausfrau	Hausfrau	N;DAT;SG
Empfindlichkeit	Empfindlichkeit	N;NOM;SG
Steinbutt	Steinbutte	N;NOM;PL
Kelvin	Kelvin	N;NOM;PL
Wasserstoffoxid	Wasserstoffoxide	N;NOM;PL
verheiraten	verheiratetest	V;SBJV;SG;2;PST
Kompositum	Kompositum	N;DAT;SG
Mundart	Mundart	N;ACC;SG
flutschen	flutschtet	V;SBJV;PL;2;PST
Überlebenskunst	Überlebenskünsten	N;DAT;PL
Rasthof	Rasthöfen	N;DAT;PL
anmelden	anmelden	V;NFIN
Jagdhund	Jagdhunde	N;ACC;PL
Gießerei	Gießereien	N;NOM;PL
verkapseln	verkapseln	V;SBJV;PL;1;PRS
Au	Au	N;NOM;SG
Analemma	Analemma	N;DAT;SG
emittieren	emittier	V;IMP;SG;2
Treibhaus	Treibhaus	N;ACC;SG
möblieren	möblieren	V;IND;PL;1;PRS
erwachen	erwachtest	V;SBJV;SG;2;PST
expandieren	expandieret	V;SBJV;PL;2;PRS
belüften	belüfteten	V;IND;PL;3;PST
Sonnentau	Sonnentau	N;NOM;SG
Twist	Twist	N;DAT;SG
Phosphin	Phosphins	N;GEN;SG
limitieren	limitiere	V;SBJV;SG;3;PRS
belassen	beließe	V;SBJV;SG;1;PST
begrapschen	begrapscht	V;IND;PL;2;PRS
Kinase	Kinasen	N;NOM;PL
beziffern	bezifferte	V;IND;SG;3;PST
sintern	sintern	V;IND;PL;3;PRS
feilschen	feilschte	V;IND;SG;1;PST
Pomologin	Pomologin	N;DAT;SG
Akkord	Akkorde	N;GEN;PL
pachten	pachte	V;IMP;SG;2
Überlegenheit	Überlegenheiten	N;ACC;PL
Chemikerin	Chemikerin	N;NOM;SG
klonen	klonten	V;IND;PL;3;PST
berücksichtigen	berücksichtigest	V;SBJV;SG;2;PRS
ändern	änderte	V;SBJV;SG;3;PST
Elster	Elstern	N;DAT;PL
Vagabund	Vagabunden	N;NOM;PL
schalten	schaltetest	V;SBJV;SG;2;PST
Moloch	Moloche	N;ACC;PL
Sanitäter	Sanitätern	N;DAT;PL
befallen	befielet	V;SBJV;PL;2;PST
Lautschrift	Lautschriften	N;DAT;PL
verlagern	verlagerest	V;SBJV;SG;2;PRS
marodieren	marodiertet	V;IND;PL;2;PST
Unwiderlegbarkeit	Unwiderlegbarkeiten	N;NOM;PL
Dewargefäß	Dewargefäß	N;NOM;SG
Wicht	Wicht	N;ACC;SG
Amtsträger	Amtsträger	N;DAT;SG
leiten	leiten	V;SBJV;PL;3;PRS
Zimmernummer	Zimmernummern	N;DAT;PL
Falter	Falters	N;GEN;SG
Charakter	Charakter	N;ACC;SG
Poster	Poster	N;NOM;PL
schauspielern	schauspielerte	V;SBJV;SG;3;PST
Zankapfel	Zankapfel	N;NOM;SG
streichen	streichet	V;SBJV;PL;2;PRS
schalten	schaltetet	V;IND;PL;2;PST
Tibeterin	Tibeterinnen	N;ACC;PL
Hochkomma	Hochkommas	N;NOM;PL
Börsengang	Börsengängen	N;DAT;PL
Senkkasten	Senkkasten	N;DAT;SG
pikieren	pikiert	V;IND;PL;2;PRS
bluffen	blufftet	V;SBJV;PL;2;PST
quadrieren	quadriertest	V;SBJV;SG;2;PST
Handgemenge	Handgemenges	N;GEN;SG
Gasballon	Gasballons	N;GEN;PL
christianisieren	christianisieren	V;SBJV;PL;1;PRS
Steuerwagen	Steuerwagen	N;NOM;SG
Datei	Dateien	N;GEN;PL
personifizieren	personifizieret	V;SBJV;PL;2;PRS
appliciren	applicirten	V;IND;PL;3;PST
importieren	importierest	V;SBJV;SG;2;PRS
schrumpfen	schrumpftet	V;IND;PL;2;PST
Lanthanoid	Lanthanoids	N;GEN;SG
würdigen	würdigte	V;IND;SG;3;PST
zerstäuben	zerstäubst	V;IND;SG;2;PRS
Widerlegung	Widerlegung	N;DAT;SG
meißeln	meißelte	V;IND;SG;1;PST
skypen	skypt	V;IND;PL;2;PRS
Buntwaschmittel	Buntwaschmittels	N;GEN;SG
übergeben	übergebt	V;IMP;PL;2
leuchten	leuchten	V;NFIN
kreisen	kreiste	V;IND;SG;1;PST
Agglomeration	Agglomeration	N;GEN;SG
Gärtner	Gärtner	N;GEN;PL
Tastenbelegung	Tastenbelegungen	N;NOM;PL
Sense	Sense	N;GEN;SG
Bodybuilding	Bodybuilding	N;ACC;SG
verseuchen	verseuchen	V;SBJV;PL;3;PRS
Diglycerid	Diglyceride	N;NOM;PL
Unterwerfung	Unterwerfungen	N;DAT;PL
perfektionieren	perfektionieret	V;SBJV;PL;2;PRS
Chiasmus	Chiasmen	N;NOM;PL
konzentrieren	konzentrierte	V;SBJV;SG;3;PST
lindern	lindert	V;IMP;PL;2
Fundi	Fundis	N;GEN;PL
Holzscheit	Holzscheite	N;GEN;PL
schmieren	schmieren	V;IND;PL;3;PRS
räsonieren	räsonieret	V;SBJV;PL;2;PRS
Sympodium	Sympodien	N;NOM;PL
bluffen	blufften	V;IND;PL;1;PST
Phosphatgestein	Phosphatgestein	N;DAT;SG
schrumpfen	schrumpfte	V;SBJV;SG;1;PST
belaufen	belieft	V;IND;PL;2;PST
Arrangement	Arrangement	N;NOM;SG
erfinden	erfändet	V;SBJV;PL;2;PST
Kollektion	Kollektion	N;NOM;SG
Essigfliege	Essigfliegen	N;DAT;PL
System	System	N;ACC;SG
Mannsschild	Mannsschilden	N;DAT;PL
Spot	Spots	N;NOM;PL
Frettchen	Frettchen	N;DAT;SG
Elefantenrüsselmuschel	Elefantenrüsselmuschel	N;GEN;SG
Selbstverzwergung	Selbstverzwergungen	N;DAT;PL
besudeln	besudeltest	V;SBJV;SG;2;PST
bedanken	bedank	V;IMP;SG;2
Erdbeerbaum	Erdbeerbäumen	N;DAT;PL
Durchschlag	Durchschläge	N;ACC;PL
Königstochter	Königstöchter	N;GEN;PL
Maskulinum	Maskulina	N;GEN;PL
Schwazer	Schwazer	N;DAT;SG
Liebling	Lieblinge	N;ACC;PL
Schweinchen	Schweinchens	N;GEN;SG
Nationalspielerin	Nationalspielerinnen	N;ACC;PL
stationieren	stationieren	V;SBJV;PL;1;PRS
Xi	Xis	N;ACC;PL
verarbeiten	verarbeite	V;SBJV;SG;3;PRS
Bedürftigkeit	Bedürftigkeiten	N;DAT;PL
Gottesgnadentum	Gottesgnadentum	N;DAT;SG
strafen	strafest	V;SBJV;SG;2;PRS
filzen	filzen	V;IND;PL;3;PRS
Stricher	Strichers	N;GEN;SG
Silberchalkogenid	Silberchalkogenid	N;ACC;SG
Einbrecher	Einbrecher	N;GEN;PL
Staatssekretär	Staatssekretäres	N;GEN;SG
aufkonzentrieren	aufkonzentrierten	V;SBJV;PL;1;PST
Swastika	Swastiken	N;DAT;PL
schiffen	schiffen	V;SBJV;PL;3;PRS
Penisknochen	Penisknochen	N;NOM;SG
Bedienung	Bedienung	N;DAT;SG
Wasserstoffantrieb	Wasserstoffantriebe	N;NOM;PL
Wette	Wetten	N;GEN;PL
Feldbett	Feldbetten	N;DAT;PL
beeindrucken	beeindruckt	V;IMP;PL;2
Beratung	Beratungen	N;DAT;PL
wimmeln	wimmeltest	V;SBJV;SG;2;PST
Zeitpunkt	Zeitpunkt	N;ACC;SG
Bezirksausschuss	Bezirksausschuss	N;NOM;SG
Grenzfluss	Grenzflüsse	N;GEN;PL
Arzthelferin	Arzthelferin	N;NOM;SG
knuffen	knuffen	V;IND;PL;1;PRS
Wrack	Wrack	N;ACC;SG
blöken	blökt	V;IND;PL;2;PRS
krepieren	krepierte	V;IND;SG;3;PST
Riegel	Riegel	N;NOM;PL
Schilddrüsenhormon	Schilddrüsenhormon	N;DAT;SG
entkeimen	entkeimt	V;IND;PL;2;PRS
hetzen	hetztet	V;IND;PL;2;PST
Telekommunikation	Telekommunikationen	N;NOM;PL
tratschen	tratschet	V;SBJV;PL;2;PRS
radieren	radierte	V;IND;SG;3;PST
Gegensatz	Gegensatz	N;NOM;SG
signalisieren	signalisierest	V;SBJV;SG;2;PRS
chillen	chilltet	V;SBJV;PL;2;PST
Happen	Happen	N;NOM;PL
Wächter	Wächtern	N;DAT;PL
parkieren	parkier	V;IMP;SG;2
nationalisieren	nationalisiertet	V;IND;PL;2;PST
Bilanz	Bilanzen	N;ACC;PL
Hassliebe	Hassliebe	N;GEN;SG
verlangsamen	verlangsamen	V;SBJV;PL;1;PRS
Sonnabendabend	Sonnabendabend	N;DAT;SG
Schneidbrett	Schneidbrettern	N;DAT;PL
klemmen	klemmtet	V;SBJV;PL;2;PST
bekränzen	bekränzte	V;IND;SG;3;PST
Brötchen	Brötchen	N;NOM;PL
fanatisieren	fanatisieren	V;IND;PL;3;PRS
bestehlen	bestahl	V;IND;SG;1;PST
Süßholz	Süßhölzer	N;ACC;PL
ölen	ölten	V;IND;PL;3;PST
süssen	süsst	V;IND;SG;3;PRS
ersteigern	ersteigert	V;IMP;PL;2
mästen	mäste	V;IND;SG;1;PRS
Feldspat	Feldspat	N;ACC;SG
verlassen	verließen	V;SBJV;PL;1;PST
Höschenwindel	Höschenwindel	N;NOM;SG
Liter	Liter	N;DAT;SG
Nickelarsenkies	Nickelarsenkies	N;DAT;SG
Akt	Aktes	N;GEN;SG
Skizze	Skizze	N;DAT;SG
schauspielern	schauspieleren	V;SBJV;PL;1;PRS
Schwarm	Schwärme	N;GEN;PL
schweißen	schweißen	V;SBJV;PL;3;PRS
Hinterzimmer	Hinterzimmers	N;GEN;SG
fixieren	fixierten	V;IND;PL;3;PST
Rhodiummineral	Rhodiummineral	N;DAT;SG
Ferritin	Ferritine	N;NOM;PL
hökern	hökre	V;IMP;SG;2
korrelieren	korrelieret	V;SBJV;PL;2;PRS
Zar	Zar	N;NOM;SG
Graveur	Graveur	N;DAT;SG
Bundesinnenminister	Bundesinnenminister	N;NOM;SG
adeln	adelt	V;IND;PL;2;PRS
jonglieren	jonglieren	V;IND;PL;3;PRS
Weinbeere	Weinbeeren	N;ACC;PL
verstreuen	verstreuten	V;IND;PL;3;PST
Aerosol	Aerosols	N;GEN;SG
Schreiner	Schreinern	N;DAT;PL
begeistern	begeistert	V;IND;PL;2;PRS
eignen	eignete	V;IND;SG;3;PST
Verletzung	Verletzung	N;DAT;SG
Bandit	Banditen	N;DAT;SG
haken	hakte	V;SBJV;SG;3;PST
mopsen	mopstest	V;SBJV;SG;2;PST
buchstabieren	buchstabiertest	V;SBJV;SG;2;PST
erwärmen	erwärmtest	V;SBJV;SG;2;PST
Häkchen	Häkchen	N;DAT;PL
ölen	ölet	V;SBJV;PL;2;PRS
klingen	klang	V;IND;SG;3;PST
Weißpunkt-Buntbarsch	Weißpunkt-Buntbarsch	N;NOM;SG
offerieren	offeriere	V;SBJV;SG;3;PRS
Einweisung	Einweisung	N;NOM;SG
überleben	überlebten	V;IND;PL;1;PST
Rasierklinge	Rasierklinge	N;GEN;SG
unterschätzen	unterschätzten	V;SBJV;PL;1;PST
Zobel	Zobels	N;GEN;SG
amputieren	amputieren	V;SBJV;PL;3;PRS
Aerosol	Aerosolen	N;DAT;PL
errechnen	errechnetet	V;SBJV;PL;2;PST
Krach	Kräche	N;ACC;PL
dekompilieren	dekompilieren	V;SBJV;PL;3;PRS
Arithmetik	Arithmetik	N;NOM;SG
Glatze	Glatze	N;GEN;SG
Sterz	Sterze	N;GEN;PL
toasten	toastete	V;IND;SG;1;PST
Eisenkies	Eisenkies	N;DAT;SG
Arsentrichlorid	Arsentrichloride	N;GEN;PL
Türsteher	Türstehers	N;GEN;SG
Haarwaschmittel	Haarwaschmittel	N;DAT;SG
velarisieren	velarisieren	V;NFIN
spionieren	spioniert	V;IND;PL;2;PRS
befallen	befallt	V;IND;PL;2;PRS
Karton	Kartone	N;GEN;PL
monogrammieren	monogrammiere	V;IND;SG;1;PRS
Golfschläger	Golfschläger	N;GEN;PL
laichen	laichtet	V;SBJV;PL;2;PST
Server	Servers	N;GEN;SG
Spann	Spannes	N;GEN;SG
Schoner	Schonern	N;DAT;PL
erziehen	erzogen	V;IND;PL;3;PST
kooperieren	kooperierst	V;IND;SG;2;PRS
Hyperoxid	Hyperoxide	N;NOM;PL
verschärfen	verschärft	V;IMP;PL;2
entfesseln	entfesseln	V;SBJV;PL;3;PRS
Hooligan	Hooligans	N;GEN;PL
Bügeleisen	Bügeleisen	N;GEN;PL
Deklaration	Deklarationen	N;DAT;PL
Kupferkies	Kupferkiese	N;NOM;PL
Antiklopfmittel	Antiklopfmittel	N;NOM;PL
Decacarbonyl	Decacarbonyle	N;GEN;PL
Nachschub	Nachschübe	N;ACC;PL
Piano	Pianos	N;DAT;PL
Dreirad	Dreiräder	N;ACC;PL
Blumenmuster	Blumenmuster	N;GEN;PL
Mäusebussard	Mäusebussarde	N;NOM;PL
Liebhaberei	Liebhaberei	N;ACC;SG
Unterkategorie	Unterkategorie	N;NOM;SG
kastrieren	kastrieren	V;NFIN
Bauchgefühl	Bauchgefühl	N;ACC;SG
Beichtvater	Beichtväter	N;DAT;PL
Kirchenbank	Kirchenbank	N;GEN;SG
melden	meldeten	V;SBJV;PL;3;PST
Überangebot	Überangebote	N;GEN;PL
personifizieren	personifizieren	V;SBJV;PL;3;PRS
Bertrandit	Bertrandite	N;NOM;PL
Vorbote	Vorbote	N;NOM;SG
Bakkalaureus	Bakkalaureus	N;NOM;SG
Krebs	Krebs	N;DAT;SG
Sternbild	Sternbild	N;DAT;SG
Bibel	Bibeln	N;NOM;PL
verbrennen	verbrannten	V;IND;PL;3;PST
Campingplatz	Campingplatzes	N;GEN;SG
rollen	rolle	V;SBJV;SG;1;PRS
Guru	Gurus	N;NOM;PL
gebrauchen	gebrauchten	V;IND;PL;3;PST
eliminieren	eliminier	V;IMP;SG;2
würdigen	würdigt	V;IMP;PL;2
Figur	Figuren	N;DAT;PL
grapschen	grapschen	V;SBJV;PL;3;PRS
Langschwert	Langschwertern	N;DAT;PL
verwickeln	verwickeltet	V;IND;PL;2;PST
Ziellinie	Ziellinie	N;NOM;SG
Email	Email	N;DAT;SG
Hungersnot	Hungersnöten	N;DAT;PL
Proposition	Propositionen	N;ACC;PL
Quorum	Quorums	N;GEN;SG
interpolieren	interpoliert	V;IND;SG;3;PRS
systematisieren	systematisierten	V;SBJV;PL;1;PST
verschonen	verschonen	V;SBJV;PL;1;PRS
Pyrazin	Pyrazine	N;NOM;PL
zocken	zocke	V;SBJV;SG;3;PRS
repräsentieren	repräsentierst	V;IND;SG;2;PRS
maskieren	maskierten	V;IND;PL;3;PST
begründen	begründen	V;IND;PL;1;PRS
vertun	vertatet	V;IND;PL;2;PST
schachern	schachert	V;IMP;PL;2
Löllingit	Löllingite	N;NOM;PL
Hungersnot	Hungersnöte	N;ACC;PL
Waschbecken	Waschbecken	N;NOM;SG
Fritzchen	Fritzchen	N;ACC;SG
Expansion	Expansionen	N;GEN;PL
Gewinde	Gewinde	N;NOM;SG
verletzen	verletz	V;IMP;SG;2
prägen	prägten	V;IND;PL;3;PST
rosten	rostetest	V;SBJV;SG;2;PST
adeln	adelte	V;IND;SG;1;PST
Illyrer	Illyrer	N;NOM;PL
Schneidbrett	Schneidbrettes	N;GEN;SG
Gefahrensymbol	Gefahrensymbols	N;GEN;SG
Ameisenkönigin	Ameisenköniginnen	N;ACC;PL
äussern	äusseret	V;SBJV;PL;2;PRS
Prinzeß	Prinzeß	N;GEN;SG
schnüren	schnürten	V;SBJV;PL;3;PST
beantworten	beantwortetet	V;SBJV;PL;2;PST
Rhabdomyopathie	Rhabdomyopathie	N;GEN;SG
Daumennagel	Daumennägel	N;NOM;PL
Trinker	Trinkers	N;GEN;SG
begrenzen	begrenzten	V;SBJV;PL;3;PST
gewittern	gewittern	V;SBJV;PL;3;PRS
Zusage	Zusage	N;ACC;SG
schnaufen	schnaufen	V;SBJV;PL;3;PRS
Haarnetz	Haarnetze	N;ACC;PL
Ethnologe	Ethnologen	N;NOM;PL
Chimäre	Chimäre	N;GEN;SG
weiden	weidest	V;SBJV;SG;2;PRS
Hommage	Hommagen	N;NOM;PL
verspröden	verspröden	V;IND;PL;3;PRS
implizieren	impliziertet	V;IND;PL;2;PST
Habitat	Habitate	N;NOM;PL
Albino	Albino	N;ACC;SG
Einstieg	Einstiege	N;NOM;PL
liebäugeln	liebäugeltet	V;SBJV;PL;2;PST
schaden	schaden	V;NFIN
Dinukleotid	Dinukleotide	N;ACC;PL
Einschreiben	Einschreibens	N;GEN;SG
adsorbieren	adsorbieren	V;SBJV;PL;1;PRS
verloben	verloben	V;SBJV;PL;1;PRS
Schisser	Schisser	N;DAT;SG
Hafenanlage	Hafenanlagen	N;GEN;PL
Granate	Granaten	N;NOM;PL
ermächtigen	ermächtigten	V;SBJV;PL;3;PST
Laubholz	Laubholz	N;NOM;SG
negieren	negieren	V;NFIN
emaillieren	emailliertet	V;SBJV;PL;2;PST
Blattspinat	Blattspinat	N;NOM;SG
Gewächs	Gewächs	N;ACC;SG
Kilobyte	Kilobyte	N;NOM;SG
Chlorat	Chloraten	N;DAT;PL
verdrängen	verdrängten	V;SBJV;PL;1;PST
Marodeur	Marodeure	N;GEN;PL
empfinden	empfänden	V;SBJV;PL;3;PST
Amblygonit	Amblygonits	N;GEN;SG
Erbgut	Erbgut	N;NOM;SG
Feinstruktur	Feinstrukturen	N;DAT;PL
injizieren	injiziere	V;SBJV;SG;1;PRS
Lesbarkeit	Lesbarkeit	N;GEN;SG
ebben	ebbe	V;SBJV;SG;1;PRS
bimmeln	bimmeln	V;IND;PL;3;PRS
Pentafluorid	Pentafluoride	N;NOM;PL
schämen	schämt	V;IND;SG;3;PRS
decken	decktet	V;IND;PL;2;PST
Blamage	Blamage	N;DAT;SG
Paraffinöl	Paraffinöle	N;GEN;PL
Nähmaschine	Nähmaschinen	N;NOM;PL
erziehen	erziehen	V;NFIN
Archivar	Archivaren	N;DAT;PL
transferieren	transferiert	V;IND;PL;2;PRS
wiederholen	wiederhol	V;IMP;SG;2
Azobenzol	Azobenzol	N;ACC;SG
horten	horte	V;SBJV;SG;1;PRS
nebeln	nebelten	V;IND;PL;1;PST
zementieren	zementierte	V;SBJV;SG;1;PST
blanchieren	blanchieren	V;SBJV;PL;3;PRS
Fichtelit	Fichtelit	N;ACC;SG
Ösophagospasmus	Ösophagospasmus	N;NOM;SG
Basalt	Basalt	N;DAT;SG
lieben	liebt	V;IND;SG;3;PRS
Imitation	Imitation	N;GEN;SG
reißen	reißet	V;SBJV;PL;2;PRS
Unit-Test-Programmiergerüst	Unit-Test-Programmiergerüst	N;NOM;SG
Stutzuhr	Stutzuhr	N;ACC;SG
rauschen	rauschten	V;SBJV;PL;1;PST
Astronomin	Astronomin	N;GEN;SG
erstechen	ersteche	V;SBJV;SG;1;PRS
Apathie	Apathien	N;GEN;PL
Gefahrensymbol	Gefahrensymbole	N;GEN;PL
Bedingung	Bedingung	N;ACC;SG
parkieren	parkierte	V;SBJV;SG;3;PST
grämen	grämet	V;SBJV;PL;2;PRS
sengen	sengen	V;IND;PL;3;PRS
