lys	lyse	ADJ;DEF;SG+PL
anbefale	anbefalt	V.PTCP;PST
bidra	bidrar	V;PRS
misteltein	mistelteiner	N;NDEF;PL
jordmor	jordmora	N;DEF;SG
behov	behov	N;NDEF;PL
fjernsyn	fjernsynet	N;DEF;SG
forklaring	forklaringen	N;DEF;SG
kompetanse	kompetansen	N;DEF;SG
automatisk	automatisk	ADJ;NEUT;SG
tiendedel	tiendedelene	N;DEF;PL
kapittel	kapitler	N;NDEF;PL
adressat	adressatene	N;DEF;PL
spedbarn	spedbarnene	N;DEF;PL
fortau	fortauet	N;DEF;SG
sosial	sosial	ADJ;CMPR
lys	lysere	ADJ;CMPR
klo	klørne	N;DEF;PL
skilletegn	skilletegnet	N;DEF;SG
nettside	nettsida	N;DEF;SG
be	ba	V;PST
pensjonist	pensjonistene	N;DEF;PL
beist	beist	N;NDEF;PL
fargeløs	fargeløse	ADJ;DEF;SG+PL
portugisisk	portugisiske	ADJ;DEF;SG+PL
hytte	hytter	N;NDEF;PL
reisemål	reisemåla	N;DEF;PL
pålitelig	pålitelige	ADJ;DEF;SG+PL
beundre	beundra	V;PST
magedanserinne	magedanserinner	N;NDEF;PL
finale	finaler	N;NDEF;PL
bleik	bleikeste	ADJ;SPRL;DEF
stjernetegn	stjernetegna	N;DEF;PL
uegnet	uegnete	ADJ;DEF;SG+PL
fredag	fredagene	N;DEF;PL
sammenlignbar	sammenlignbart	ADJ;NEUT;SG
sikring	sikringer	N;NDEF;PL
lekeplass	lekeplassen	N;DEF;SG
stim	stimet	N;DEF;SG
støtdemper	støtdempere	N;NDEF;PL
fargerik	fargerikt	ADJ;NEUT;SG
opplevelse	opplevelsen	N;DEF;SG
klippe	klippene	N;DEF;PL
perfeksjonist	perfeksjonisten	N;DEF;SG
undergrave	undergrov	V;PST
lydbølge	lydbølgen	N;DEF;SG
forsvar	forsvara	N;DEF;PL
fest	fester	N;NDEF;PL
avfyre	avfyrende	V.PTCP;PRS
lovløs	lovløst	ADJ;NEUT;SG
halvsøster	halvsøstrene	N;DEF;PL
måse	måsene	N;DEF;PL
strømme	strømma	V;PST
kasino	kasinoet	N;DEF;SG
blyant	blyanten	N;DEF;SG
kapitel	kapitela	N;DEF;PL
sperrebånd	sperrebåndene	N;DEF;PL
morfologi	morfologiene	N;DEF;PL
dryppe	drypte	V;PST
millimeter	millimeter	N;NDEF;PL
språkforsker	språkforskeren	N;DEF;SG
røyker	røykerne	N;DEF;PL
akseptere	aksepter	V;IMP
grand danois	grand danoiser	N;NDEF;PL
solur	soluret	N;DEF;SG
brett	bretter	N;NDEF;PL
taushet	tausheten	N;DEF;SG
ultrafiolett	ultrafiolett	ADJ;NEUT;SG
lampeskjerm	lampeskjermene	N;DEF;PL
maler	maleren	N;DEF;SG
volum	volumene	N;DEF;PL
oljefelt	oljefeltet	N;DEF;SG
frase	frasen	N;DEF;SG
dagsavis	dagsavisa	N;DEF;SG
løype	løypa	N;DEF;SG
avansere	avanserer	V;PRS
beskrive	beskriv	V;IMP
nebb	nebbet	N;DEF;SG
sabbatsår	sabbatsåret	N;DEF;SG
seilskip	seilskipa	N;DEF;PL
gjennomsnitt	gjennomsnittene	N;DEF;PL
akkompagnere	akkompagnerer	V;PRS
kaste	kaster	N;NDEF;PL
paviljong	paviljonger	N;NDEF;PL
bevæpne	bevæpn	V;IMP
revolusjon	revolusjonen	N;DEF;SG
utenlandsk	utenlandsk	ADJ;NEUT;SG
hjerte	hjerta	N;DEF;PL
kraftig	kraftigste	ADJ;SPRL;DEF
kult	kulten	N;DEF;SG
strøm	strømmer	N;NDEF;PL
spire	spiren	N;DEF;SG
brøler	brølerne	N;DEF;PL
torn	torner	N;NDEF;PL
turniké	turnikéene	N;DEF;PL
arving	arvingene	N;DEF;PL
velge	valgte	V;PST
strand	stranden	N;DEF;SG
fiskevær	fiskeværene	N;DEF;PL
gal	galene	N;DEF;PL
clutch	clutchen	N;DEF;SG
bror	brødre	N;NDEF;PL
nær	nærmeste	ADJ;SPRL;DEF
ordtak	ordtaket	N;DEF;SG
slarv	slarver	N;NDEF;PL
kardinal	kardinalen	N;DEF;SG
lunge	lunga	N;DEF;SG
straks	strakser	N;NDEF;PL
vekslingskurs	vekslingskursen	N;DEF;SG
morgen	morgenene	N;DEF;PL
synder	synderen	N;DEF;SG
eksistens	eksistensene	N;DEF;PL
oppvaskmiddel	oppvaskmidler	N;NDEF;PL
bygg	bygga	N;DEF;PL
kontaktlinse	kontaktlinsene	N;DEF;PL
debutere	debuterte	V;PST
plog	plogen	N;DEF;SG
fotavtrykk	fotavtrykka	N;DEF;PL
sekret	sekret	N;NDEF;PL
lidelse	lidelsen	N;DEF;SG
rør	rørene	N;DEF;PL
øyeskygge	øyeskyggene	N;DEF;PL
tall	talla	N;DEF;PL
julestrømpe	julestrømpene	N;DEF;PL
e-post	e-poster	N;NDEF;PL
opprettholde	opprettholdende	V.PTCP;PRS
hav	havet	N;DEF;SG
tøymykner	tøymyknerne	N;DEF;PL
eske	esken	N;DEF;SG
sone	sona	N;DEF;SG
mamma	mammaen	N;DEF;SG
projisere	projiserende	V.PTCP;PRS
angrep	angrepet	N;DEF;SG
bleke	bleket	V;PST
edelstein	edelsteiner	N;NDEF;PL
løpe	løp	V;PST
hoppe	hoppende	V.PTCP;PRS
kongefamilie	kongefamilier	N;NDEF;PL
sjettedel	sjettedelene	N;DEF;PL
kapittel	kapitlet	N;DEF;SG
maleri	malerier	N;NDEF;PL
fly	flyr	V;PRS
erkebiskop	erkebiskoper	N;NDEF;PL
tsjekker	tsjekkerne	N;DEF;PL
tuvaler	tuvalere	N;NDEF;PL
politi	politiet	N;DEF;SG
bagasjerom	bagasjerommet	N;DEF;SG
platespiller	platespillere	N;NDEF;PL
hemmelighetsfull	hemmelighetsfullt	ADJ;NEUT;SG
borgerkrig	borgerkrigen	N;DEF;SG
teleskopisk	teleskopisk	ADJ;NEUT;SG
kvartett	kvartettene	N;DEF;PL
vrak	vraket	N;DEF;SG
regel	regelen	N;DEF;SG
spire	spirer	N;NDEF;PL
ur	uret	N;DEF;SG
avhengig	avhengige	ADJ;DEF;SG+PL
snakke	snakket	V;PST
spiss	spissere	ADJ;CMPR
skål	skålen	N;DEF;SG
formel	formelen	N;DEF;SG
variant	variantene	N;DEF;PL
utland	utland	N;NDEF;PL
forbudt	forbudte	ADJ;DEF;SG+PL
avrunde	avrund	V;IMP
kjennskap	kjennskapene	N;DEF;PL
lykkelig	lykkelig	ADJ;NEUT;SG
fjell	fjellene	N;DEF;PL
dobbeltfeil	dobbeltfeilen	N;DEF;SG
malm	malmene	N;DEF;PL
filosof	filosofene	N;DEF;PL
vekslingskurs	vekslingskursene	N;DEF;PL
kaotisk	kaotiske	ADJ;DEF;SG+PL
rull	ruller	N;NDEF;PL
øl	øl	N;NDEF;PL
gjenkjennelig	gjenkjennelig	ADJ;NEUT;SG
nese	nesene	N;DEF;PL
e-post	e-posten	N;DEF;SG
nevner	nevneren	N;DEF;SG
wienerbrød	wienerbrøda	N;DEF;PL
student	studenter	N;NDEF;PL
bur	buret	N;DEF;SG
passere	passerer	V;PRS
spontan	spontant	ADJ;NEUT;SG
autoritet	autoriteten	N;DEF;SG
avhengighet	avhengigheter	N;NDEF;PL
lyst	lysten	N;DEF;SG
skille	skilt	V.PTCP;PST
klinkekule	klinkekulene	N;DEF;PL
knapphull	knapphull	N;NDEF;PL
tekanne	tekanna	N;DEF;SG
sentrifugalkraft	sentrifugalkreftene	N;DEF;PL
svensk	svenske	ADJ;DEF;SG+PL
hjernestamme	hjernestammer	N;NDEF;PL
dag	dagene	N;DEF;PL
bokhylle	bokhyllene	N;DEF;PL
skulderveske	skulderveska	N;DEF;SG
hodetelefon	hodetelefoner	N;NDEF;PL
årtusen	årtusena	N;DEF;PL
perspektiv	perspektivene	N;DEF;PL
mongol	mongolen	N;DEF;SG
grønn	grønne	ADJ;DEF;SG+PL
arameisk	arameisk	ADJ;NEUT;SG
nabolag	nabolaget	N;DEF;SG
tommel	tommelen	N;DEF;SG
isbryter	isbryterne	N;DEF;PL
aristokrat	aristokrater	N;NDEF;PL
kompleks	komplekser	N;NDEF;PL
spekter	spektre	N;NDEF;PL
adamseple	adamsepla	N;DEF;PL
musikalsk	musikalske	ADJ;DEF;SG+PL
bosnier	bosnieren	N;DEF;SG
pakt	pakta	N;DEF;SG
fjerne	fjerna	V;PST
paprika	paprikaen	N;DEF;SG
inngang	innganger	N;NDEF;PL
pedal	pedalene	N;DEF;PL
kollega	kollegaer	N;NDEF;PL
krokus	krokuser	N;NDEF;PL
lav	lavest	ADJ;SPRL;NDEF
amfiteater	amfiteater	N;NDEF;PL
lyst	lysta	N;DEF;SG
vandre	vandrende	V.PTCP;PRS
håndskrift	håndskrifta	N;DEF;SG
dørlukker	dørlukkere	N;NDEF;PL
eske	eska	N;DEF;SG
bringebær	bringebæra	N;DEF;PL
terrorist	terroristene	N;DEF;PL
luxembourger	luxembourgere	N;NDEF;PL
fettsyre	fettsyren	N;DEF;SG
iskald	iskalde	ADJ;DEF;SG+PL
økonomisere	økonomisert	V.PTCP;PST
taxisjåfør	taxisjåførene	N;DEF;PL
sommersolverv	sommersolverva	N;DEF;PL
maksimalisere	maksimaliserer	V;PRS
katolikk	katolikker	N;NDEF;PL
gribb	gribben	N;DEF;SG
bryllup	bryllupene	N;DEF;PL
simulering	simuleringen	N;DEF;SG
østtimoreser	østtimoreserne	N;DEF;PL
autoritet	autoritetene	N;DEF;PL
blasfemisk	blasfemiske	ADJ;DEF;SG+PL
spiss	spissest	ADJ;SPRL;NDEF
konspirasjon	konspirasjoner	N;NDEF;PL
tredemølle	tredemøllene	N;DEF;PL
angriper	angriperne	N;DEF;PL
arbeiderklasse	arbeiderklassen	N;DEF;SG
dataprogram	dataprogramma	N;DEF;PL
dvergbjørk	dvergbjørken	N;DEF;SG
kommunisere	kommunisert	V.PTCP;PST
tannløs	tannløse	ADJ;DEF;SG+PL
tilfeldig	tilfeldige	ADJ;DEF;SG+PL
vannseng	vannsenger	N;NDEF;PL
arkaisere	arkaiser	V;IMP
innsjø	innsjøene	N;DEF;PL
pannekake	pannekaker	N;NDEF;PL
nerve	nerver	N;NDEF;PL
bevæpne	bevæpne	V;IMP
lim	lim	N;NDEF;PL
uendret	uendrete	ADJ;DEF;SG+PL
skade	skadet	V;PST
badeby	badebyene	N;DEF;PL
nerve	nervene	N;DEF;PL
fattig	fattigst	ADJ;SPRL;NDEF
marked	markedet	N;DEF;SG
skjerm	skjermen	N;DEF;SG
fregne	fregna	N;DEF;SG
nabolag	nabolagene	N;DEF;PL
sentrum	sentrene	N;DEF;PL
logo	logoen	N;DEF;SG
autorisere	autoriser	V;IMP
tvetydig	tvetydig	ADJ;NEUT
regne	regna	V.PTCP;PST
svømmebasseng	svømmebassengene	N;DEF;PL
nymfoman	nymfomanene	N;DEF;PL
forsake	forsakende	V.PTCP;PRS
øyeskygge	øyeskyggen	N;DEF;SG
variasjon	variasjoner	N;NDEF;PL
student	studenten	N;DEF;SG
fosfor	fosforen	N;DEF;SG
doble	dobla	V;PST
belte	beltet	N;DEF;SG
får	fåra	N;DEF;PL
mirakel	mirakelet	N;DEF;SG
oksidere	oksidert	V.PTCP;PST
adamseple	adamseplene	N;DEF;PL
pakt	pakten	N;DEF;SG
agurk	agurkene	N;DEF;PL
monolog	monologene	N;DEF;PL
flyfoto	flyfoto	N;NDEF;PL
regne	regnet	V;PST
dryppe	dryppet	V.PTCP;PST
gammel	eldste	ADJ;SPRL;DEF
lår	lårene	N;DEF;PL
gruvearbeider	gruvearbeideren	N;DEF;SG
basalt	basalter	N;NDEF;PL
lommelerke	lommelerkene	N;DEF;PL
fløte	fløter	V;PRS
undergrave	undergrav	V;IMP
tallerken	tallerkenen	N;DEF;SG
verdsette	verdsatte	V;PST
tysker	tyskeren	N;DEF;SG
støpsel	støpselet	N;DEF;SG
bibliofil	bibliofiler	N;NDEF;PL
montere	monterer	V;PRS
grindhval	grindhvalen	N;DEF;SG
kollega	kollegaen	N;DEF;SG
rundkjøring	rundkjøringer	N;NDEF;PL
dessert	desserten	N;DEF;SG
variere	varierer	V;PRS
skade	skaden	N;DEF;SG
utfordre	utfordrende	V.PTCP;PRS
gulrot	gulroten	N;DEF;SG
stedsnavn	stedsnavn	N;NDEF;PL
ugift	ugift	ADJ;NEUT;SG
hav	havene	N;DEF;PL
snøbrett	snøbretta	N;DEF;PL
laser	laserne	N;DEF;PL
særegen	særegent	ADJ;NEUT;SG
partall	partallet	N;DEF;SG
profet	profeter	N;NDEF;PL
åpenbar	åpenbart	ADJ;NEUT;SG
folketelling	folketellingen	N;DEF;SG
verden	verdenen	N;DEF;SG
dataprogram	dataprogrammer	N;NDEF;PL
sprøyte	sprøyten	N;DEF;SG
nødvendig	nødvendige	ADJ;DEF;SG+PL
hud	huda	N;DEF;SG
overhode	overhoda	N;DEF;PL
akrobat	akrobatene	N;DEF;PL
holdning	holdningene	N;DEF;PL
nål	nåler	N;NDEF;PL
innhold	innholdene	N;DEF;PL
desimal	desimalene	N;DEF;PL
vanntårn	vanntårnet	N;DEF;SG
nøtt	nøtten	N;DEF;SG
bestikk	bestikk	N;NDEF;PL
programmering	programmeringen	N;DEF;SG
pælerot	pælerøttene	N;DEF;PL
turkmener	turkmenere	N;NDEF;PL
oksidere	oksiderer	V;PRS
propan	propanet	N;DEF;SG
avrunde	avrunda	V;PST
feie	feia	V.PTCP;PST
bilist	bilister	N;NDEF;PL
snøbyge	snøbygene	N;DEF;PL
frukttre	frukttreet	N;DEF;SG
tolke	tolk	V;IMP
blyant	blyantene	N;DEF;PL
mirakel	mirakel	N;NDEF;PL
skisse	skissen	N;DEF;SG
turve	turvt	V.PTCP;PST
kilde	kilder	N;NDEF;PL
debatt	debattene	N;DEF;PL
skaper	skaperen	N;DEF;SG
bygdelag	bygdelaget	N;DEF;SG
variere	varier	V;IMP
ønske	ønsker	V;PRS
fotballag	fotballagene	N;DEF;PL
krakk	krakker	N;NDEF;PL
miljø	miljøet	N;DEF;SG
konisk	koniske	ADJ;DEF;SG+PL
ferskvannsfisk	ferskvannsfisken	N;DEF;SG
hendig	hendige	ADJ;DEF;SG+PL
sirup	siruper	N;NDEF;PL
forsterker	forsterkere	N;NDEF;PL
tåre	tårer	N;NDEF;PL
usikkerhet	usikkerheten	N;DEF;SG
trinidader	trinidaderne	N;DEF;PL
fransk	fransk	ADJ;NEUT;SG
sjokk	sjokka	N;DEF;PL
utvidelse	utvidelsene	N;DEF;PL
grådig	grådigste	ADJ;SPRL;DEF
våkne	våkn	V;IMP
tunnelbane	tunnelbanen	N;DEF;SG
forord	forord	N;NDEF;PL
forhud	forhudene	N;DEF;PL
univers	universene	N;DEF;PL
fyrstikk	fyrstikker	N;NDEF;PL
bore	boret	V;PST
grafisk	grafisk	ADJ;NEUT;SG
kontant	kontant	ADJ;NEUT;SG
meteorologisk	meteorologisk	ADJ;NEUT;SG
hoppe	hopper	N;NDEF;PL
spion	spioner	N;NDEF;PL
agenda	agendaer	N;NDEF;PL
sensurere	sensurerte	V;PST
ågerkar	ågerkaren	N;DEF;SG
vannkoker	vannkokere	N;NDEF;PL
hue	huer	N;NDEF;PL
konspirasjonsteori	konspirasjonsteorier	N;NDEF;PL
avrunde	avrundet	V;PST
dialog	dialoger	N;NDEF;PL
meteorolog	meteorologen	N;DEF;SG
ventil	ventilen	N;DEF;SG
forskjærkniv	forskjærknivene	N;DEF;PL
pælerot	pælerøtter	N;NDEF;PL
misfarget	misfargede	ADJ;DEF;SG+PL
overskudd	overskuddet	N;DEF;SG
produsere	produsert	V.PTCP;PST
hjelpemiddel	hjelpemidla	N;DEF;PL
ublodig	ublodige	ADJ;DEF;SG+PL
moské	moskéen	N;DEF;SG
jamaicaner	jamaicanerne	N;DEF;PL
hærverk	hærverk	N;NDEF;PL
piano	pianoet	N;DEF;SG
kateter	katetre	N;NDEF;PL
true	truet	V;PST
skyggelue	skyggeluene	N;DEF;PL
kveld	kveldene	N;DEF;PL
aksess	aksessen	N;DEF;SG
mase	maset	V;PST
lok	lok	N;NDEF;PL
diplomati	diplomati	N;NDEF;PL
årsak	årsakene	N;DEF;PL
brøler	brølere	N;NDEF;PL
lørdag	lørdager	N;NDEF;PL
slovakisk	slovakisken	N;DEF;SG
forlover	forloverne	N;DEF;PL
karriere	karrierene	N;DEF;PL
trykkfeil	trykkfeilene	N;DEF;PL
tommelfinger	tommelfingrene	N;DEF;PL
drabantby	drabantbyen	N;DEF;SG
måke	måkene	N;DEF;PL
containerskip	containerskipa	N;DEF;PL
fullastet	fullastet	ADJ;NEUT;SG
akademiker	akademikere	N;NDEF;PL
nummer	numre	N;NDEF;PL
sønn	sønner	N;NDEF;PL
klovn	klovnene	N;DEF;PL
univers	universa	N;DEF;PL
male	malende	V.PTCP;PRS
batteri	batteri	N;NDEF;PL
bore	borer	V;PRS
abdikasjon	abdikasjonen	N;DEF;SG
tegning	tegningene	N;DEF;PL
venn	vennen	N;DEF;SG
befrukte	befruktet	V;PST
etablering	etableringer	N;NDEF;PL
pælerot	pælerota	N;DEF;SG
halvsøster	halvsøstera	N;DEF;SG
feie	feier	V;PRS
japansk	japansken	N;DEF;SG
tobakk	tobakkene	N;DEF;PL
grandtante	grandtanta	N;DEF;SG
kjøretøy	kjøretøyene	N;DEF;PL
fingeravtrykk	fingeravtrykk	N;NDEF;PL
hjemland	hjemlandet	N;DEF;SG
aske	asken	N;DEF;SG
samtale	samtalene	N;DEF;PL
hjem	hjemmet	N;DEF;SG
bo	boene	N;DEF;PL
helikopter	helikoptre	N;NDEF;PL
perrong	perrongen	N;DEF;SG
frispark	frisparka	N;DEF;PL
tegning	tegninga	N;DEF;SG
språk	språka	N;DEF;PL
piktogram	piktogram	N;NDEF;PL
lide	lidt	V.PTCP;PST
dramatiker	dramatikerne	N;DEF;PL
regnbue	regnbuen	N;DEF;SG
flis	flisa	N;DEF;SG
mor	mora	N;DEF;SG
bhutaner	bhutanerne	N;DEF;PL
dømme	dømt	V.PTCP;PST
sammenligne	sammenligna	V;PST
lok	loka	N;DEF;PL
underart	underarten	N;DEF;SG
studium	studia	N;DEF;PL
rand	render	N;NDEF;PL
eksperiment	eksperimenta	N;DEF;PL
retning	retningene	N;DEF;PL
rennesnare	rennesnarene	N;DEF;PL
bestefar	bestefaren	N;DEF;SG
visittkort	visittkortet	N;DEF;SG
rattstamme	rattstammer	N;NDEF;PL
skatteparadis	skatteparadiset	N;DEF;SG
vannseng	vannsengene	N;DEF;PL
musikal	musikalene	N;DEF;PL
katt	katter	N;NDEF;PL
tidsskrift	tidsskrifter	N;NDEF;PL
gymnas	gymnas	N;NDEF;PL
entreprenør	entreprenørene	N;DEF;PL
bilde	bilder	N;NDEF;PL
journalist	journalistene	N;DEF;PL
dekke	dekk	V;IMP
skalldyr	skalldyrene	N;DEF;PL
gjel	gjel	N;NDEF;PL
vindtunnel	vindtunneler	N;NDEF;PL
lamme	lamma	V;PST
forstå	forstått	V.PTCP;PST
filippiner	filippineren	N;DEF;SG
plante	planter	N;NDEF;PL
ski	skia	N;DEF;PL
supermarked	supermarkeda	N;DEF;PL
stereoanlegg	stereoanleggene	N;DEF;PL
måle	mål	V;IMP
strekning	strekninger	N;NDEF;PL
apostel	apostlene	N;DEF;PL
vakuum	vakuumer	N;NDEF;PL
lunge	lungen	N;DEF;SG
italiener	italienerne	N;DEF;PL
vind	vindene	N;DEF;PL
malm	malmen	N;DEF;SG
kuleramme	kulerammen	N;DEF;SG
kappverder	kappverderne	N;DEF;PL
fryse	fryser	V;PRS
kreativ	kreative	ADJ;DEF;SG+PL
kvadratmeter	kvadratmeter	N;NDEF;PL
finnerlønn	finnerlønnene	N;DEF;PL
rogn	rognen	N;DEF;SG
kondensere	kondenser	V;IMP
løse	løste	V;PST
akseptere	aksepterende	V.PTCP;PRS
bukt	buktene	N;DEF;PL
fløte	fløta	V.PTCP;PST
sort	sorter	N;NDEF;PL
kanon	kanonene	N;DEF;PL
containerskip	containerskipene	N;DEF;PL
symbolisere	symboliserer	V;PRS
måned	måneder	N;NDEF;PL
intervju	intervjuene	N;DEF;PL
dag	dager	N;NDEF;PL
sommerfugl	sommerfuglene	N;DEF;PL
krasje	krasj	V;IMP
hette	hetta	N;DEF;SG
koreaner	koreanere	N;NDEF;PL
taxisjåfør	taxisjåføren	N;DEF;SG
perfeksjon	perfeksjonene	N;DEF;PL
språk	språket	N;DEF;SG
lys	lyseste	ADJ;SPRL;DEF
kaste	kastene	N;DEF;PL
hustru	hustruer	N;NDEF;PL
tunge	tungen	N;DEF;SG
sensurere	sensurerende	V.PTCP;PRS
vid	vidt	ADJ;NEUT;SG
tegn	tegnet	N;DEF;SG
kjøle	kjølt	V.PTCP;PST
krokus	krokusen	N;DEF;SG
ball	baller	N;NDEF;PL
stålull	stålulla	N;DEF;SG
newzealander	newzealandere	N;NDEF;PL
pandemisk	pandemiske	ADJ;DEF;SG+PL
dato	datoene	N;DEF;PL
biologisk	biologiske	ADJ;DEF;SG+PL
turve	turv	V;IMP
baderom	baderommet	N;DEF;SG
utbrudd	utbrudd	N;NDEF;PL
akilleshæl	akilleshælene	N;DEF;PL
forhistorie	forhistoria	N;DEF;SG
nasjon	nasjoner	N;NDEF;PL
misteltein	mistelteinen	N;DEF;SG
tro	trodd	V.PTCP;PST
uttrykk	uttrykket	N;DEF;SG
tynn	tynne	ADJ;DEF;SG+PL
nær	nærmest	ADJ;SPRL;NDEF
bringebær	bringebæret	N;DEF;SG
tekanne	tekannene	N;DEF;PL
fregne	fregner	N;NDEF;PL
tomatpuré	tomatpureen	N;DEF;SG
århundre	århundrene	N;DEF;PL
sykebil	sykebiler	N;NDEF;PL
kompleks	kompleksa	N;DEF;PL
støttann	støttanna	N;DEF;SG
spre	sprer	V;PRS
hotell	hoteller	N;NDEF;PL
være	været	V;PST
uavhengig	uavhengig	ADJ;NEUT;SG
swazilender	swazilenderen	N;DEF;SG
oljefelt	oljefelter	N;NDEF;PL
hårklipp	hårklippen	N;DEF;SG
trafikkork	trafikkorker	N;NDEF;PL
vade	vadet	V.PTCP;PST
forbrenning	forbrenningene	N;NDEF;PL
sentral	sentralene	N;DEF;PL
skjønne	skjønt	V.PTCP;PST
henge	hengt	V.PTCP;PST
eksperimentere	eksperimentert	V.PTCP;PST
etterforske	etterforsker	V;PRS
vase	vaser	N;NDEF;PL
trenge	treng	V;IMP
skyhøy	skyhøyt	ADJ;NEUT;SG
halvdel	halvdeler	N;NDEF;PL
kollektiv	kollektivt	ADJ;NEUT;SG
kamera	kameraer	N;NDEF;PL
korrumpere	korrumperer	V;PRS
statue	statuer	N;NDEF;PL
flom	flommene	N;DEF;PL
dataprogram	dataprogrammene	N;DEF;PL
rytter	rytterne	N;DEF;PL
halvøy	halvøyer	N;NDEF;PL
pupp	puppen	N;DEF;PL
datterselskap	datterselskapa	N;DEF;PL
rådhus	rådhuset	N;DEF;SG
spektrum	spektra	N;NDEF;PL
komfyr	komfyrene	N;DEF;PL
overstige	overstig	V;IMP
fiber	fiberen	N;DEF;SG
rennesnare	rennesnarer	N;NDEF;PL
fjerning	fjerningene	N;DEF;PL
takle	takla	V;PST
svelge	svelger	V;PRS
bakterie	bakterier	N;NDEF;PL
bord	bordene	N;DEF;PL
vinsj	vinsjene	N;DEF;PL
regnskog	regnskogene	N;DEF;PL
rise	riser	N;NDEF;PL
rødhet	rødheten	N;DEF;SG
fysisk	fysisk	ADJ;NEUT;SG
uautorisert	uautoriserte	ADJ;DEF;SG+PL
moské	moskeer	N;NDEF;PL
historie	historia	N;DEF;SG
brett	brettet	N;DEF;SG
petriskål	petriskåler	N;NDEF;PL
ekko	ekkoet	N;DEF;SG
målvakt	målvakta	N;DEF;SG
gifte	giftet	V;PST
snabel	snabelen	N;DEF;SG
aborigin	aboriginen	N;DEF;SG
båt	båter	N;NDEF;PL
hengsel	hengselen	N;DEF;SG
europeer	europeere	N;NDEF;PL
nebb	nebba	N;DEF;PL
utnytte	utnytt	V;IMP
dørlukker	dørlukkerne	N;DEF;PL
tørr	tørt	ADJ;NEUT;SG
rokke	rokken	N;DEF;SG
insekt	insekter	N;NDEF;PL
magedanserinne	magedanserinnene	N;DEF;PL
detonere	detoner	V;IMP
rennesnare	rennesnaren	N;DEF;SG
kostfiber	kostfibrer	N;NDEF;PL
usbeker	usbekere	N;NDEF;PL
trekkvogn	trekkvognen	N;DEF;SG
åk	åk	N;NDEF;PL
interjeksjon	interjeksjonen	N;DEF;SG
gifte	gifter	V;PRS
kyniker	kynikerne	N;DEF;PL
forfriske	forfriska	V;PST
kjernefamilie	kjernefamilien	N;DEF;SG
hud	hudene	N;DEF;PL
ekskone	ekskonene	N;DEF;PL
kull	kulla	N;DEF;PL
klassifisere	klassifisert	V.PTCP;PST
container	containerne	N;DEF;PL
ventil	ventilene	N;DEF;PL
angriper	angripere	N;NDEF;PL
kystlinje	kystlinja	N;DEF;SG
tortur	torturene	N;DEF;PL
sår	såra	N;DEF;PL
detektiv	detektiver	N;NDEF;PL
prise	priset	V;PST
stim	stim	N;NDEF;PL
forkortelse	forkortelsen	N;DEF;SG
rettmessig	rettmessige	ADJ;DEF;SG+PL
moldvarp	moldvarper	N;NDEF;PL
skrift	skrifta	N;DEF;SG
kjennskap	kjennskaper	N;NDEF;PL
koordinasjon	koordinasjoner	N;NDEF;PL
pensjonist	pensjonisten	N;DEF;SG
isbjørn	isbjørner	N;NDEF;PL
minimum	minimaene	N;DEF;PL
jamføre	jamfør	V;IMP
motiv	motivet	N;DEF;SG
pneumatiker	pneumatikeren	N;DEF;SG
argument	argumenter	N;NDEF;PL
blindhet	blindheta	N;DEF;SG
bombe	bombet	V;PST
segl	segla	N;DEF;PL
havn	havner	N;NDEF;PL
markedsandel	markedsandeler	N;NDEF;PL
ønske	ønsk	V;IMP
samtale	samtaler	N;NDEF;PL
søster	søsteren	N;DEF;SG
tyrkisk	tyrkiske	ADJ;DEF;SG+PL
byråkrati	byråkrati	N;NDEF;PL
globus	globuser	N;NDEF;PL
amfiteater	amfiteatra	N;DEF;PL
nobelpris	nobelpriser	N;NDEF;PL
plassering	plasseringer	N;NDEF;PL
ambassade	ambassader	N;NDEF;PL
panter	panteren	N;DEF;SG
afar	afarene	N;DEF;PL
dørslag	dørslaget	N;DEF;SG
nettkamera	nettkameraer	N;NDEF;PL
opprinnelig	opprinnelig	ADJ;NEUT;SG
visum	visa	N;NDEF;PL
svigermor	svigermødrer	N;NDEF;PL
liberier	liberierne	N;DEF;PL
jiddisk	jiddisken	N;DEF;SG
åring	åringene	N;DEF;PL
firedoble	firedobler	V;PRS
håndskrift	håndskriftet	N;DEF;SG
lufthavn	lufthavnene	N;DEF;PL
moped	mopedene	N;DEF;PL
utopi	utopiene	N;DEF;PL
umulig	umulige	ADJ;DEF;SG+PL
høgskole	høgskolen	N;DEF;SG
destilleri	destilleri	N;NDEF;PL
bokfink	bokfinker	N;NDEF;PL
forandring	forandringene	N;DEF;PL
døv	døvt	ADJ;NEUT;SG
hette	hetten	N;DEF;SG
fortau	fortauene	N;DEF;PL
anakronisme	anakronismen	N;DEF;SG
skudd	skuddene	N;DEF;PL
tilpasse	tilpassa	V;PST
våt	våte	ADJ;DEF;SG+PL
teknisk	tekniske	ADJ;DEF;SG+PL
stige	stiger	N;NDEF;PL
plassere	plasser	V;IMP
konditor	konditorene	N;DEF;PL
frigjøring	frigjøringer	N;NDEF;PL
holdning	holdningen	N;DEF;SG
musiker	musikeren	N;DEF;SG
piano	pianoa	N;DEF;PL
abstrakt	abstrakt	ADJ;NEUT;SG
perspektiv	perspektivet	N;DEF;SG
fantom	fantom	N;NDEF;PL
spise	spiste	V;PST
armé	arméer	N;NDEF;PL
gjemme	gjemte	V;PST
saftig	saftigst	ADJ;SPRL;NDEF
bleikemiddel	bleikemidla	N;DEF;PL
golfbane	golfbaner	N;NDEF;PL
atavisme	atavismer	N;NDEF;PL
ekstrem	ekstremt	ADJ;NEUT;SG
bidrag	bidraga	N;DEF;PL
sveising	sveisingene	N;DEF;PL
kjedereaksjon	kjedereaksjonen	N;DEF;SG
pattedyr	pattedyrene	N;DEF;PL
draft	draftet	N;DEF;SG
religion	religionene	N;DEF;PL
bayonneskinke	bayonneskinkene	N;DEF;PL
skarv	skarver	N;NDEF;PL
fargestoff	fargestoffer	N;NDEF;PL
forsake	forsaker	V;PRS
klimatisk	klimatisk	ADJ;NEUT;SG
henge	henger	V;PRS
nominell	nominelt	ADJ;NEUT;SG
vitamin	vitamin	N;NDEF;PL
alminnelig	alminnelig	ADJ;NEUT;SG
vekselstrøm	vekselstrømmen	N;DEF;SG
horisont	horisonten	N;DEF;SG
ræv	rævene	N;DEF;PL
diskotek	diskotekene	N;DEF;PL
spisse	spissende	V.PTCP;PRS
ivorianer	ivorianeren	N;DEF;SG
utgift	utgiften	N;DEF;SG
juletid	juletidene	N;DEF;PL
galopp	galoppene	N;DEF;PL
kommune	kommunen	N;DEF;SG
målestokk	målestokken	N;DEF;SG
pupp	puppene	N;DEF;PL
søt	søtest	ADJ;SPRL;NDEF
ballett	balletter	N;NDEF;PL
vaskeservant	vaskeservantene	N;DEF;PL
oversjøisk	oversjøisk	ADJ;NEUT;SG
trommehinne	trommehinnen	N;DEF;SG
salg	salgene	N;DEF;PL
repertoar	repertoar	N;NDEF;PL
wienerbrød	wienerbrød	N;NDEF;PL
vinter	vinteren	N;DEF;SG
langrenn	langrennet	N;DEF;SG
togstasjon	togstasjonen	N;DEF;SG
hytte	hytten	N;DEF;SG
sprøyte	sprøyter	V;PRS
halvsøster	halvsøstrer	N;NDEF;PL
aristokrat	aristokraten	N;DEF;SG
nyzealandsk	nyzealandske	ADJ;DEF;SG+PL
nypotet	nypoteten	N;DEF;SG
larve	larver	N;NDEF;PL
skille	skiller	V;PRS
sage	sag	V;IMP
astronaut	astronauter	N;NDEF;PL
fakkel	fakler	N;NDEF;PL
høne	høns	N;NDEF;PL
desimal	desimalen	N;DEF;SG
utemmet	utemmet	ADJ;NEUT;SG
bilnøkkel	bilnøkkelen	N;DEF;SG
dal	daler	N;NDEF;PL
pil	pilen	N;DEF;SG
reflektere	reflekterer	V;PRS
avdød	avdødt	ADJ;NEUT;SG
britisk	britisk	ADJ;NEUT;SG
piksel	piksler	N;NDEF;PL
krasje	krasja	V;PST
pinnsvin	pinnsvina	N;DEF;PL
turist	turister	N;NDEF;PL
avansere	avanserte	V;PST
midtlinje	midtlinjen	N;DEF;SG
inspirere	inspirert	V.PTCP;PST
håndtak	håndtakene	N;DEF;PL
krøll	krøllene	N;DEF;PL
kraftverk	kraftverk	N;NDEF;PL
skudd	skudda	N;DEF;PL
manuskript	manuskript	N;NDEF;PL
diktator	diktatorer	N;NDEF;PL
beundre	beundrende	V.PTCP;PRS
rundkjøring	rundkjøringene	N;DEF;PL
stim	stimen	N;DEF;SG
ekspedisjon	ekspedisjonene	N;DEF;PL
psykiater	psykiatere	N;NDEF;PL
forord	forordet	N;DEF;SG
territorium	territoriet	N;DEF;SG
forvirre	forvirra	V;PST
vanlig	vanlige	ADJ;DEF;SG+PL
autorisere	autoriserte	V;PST
servitør	servitører	N;NDEF;PL
båt	båtene	N;DEF;PL
orkester	orkester	N;NDEF;PL
besøke	besøk	V;IMP
jomfruhinne	jomfruhinna	N;DEF;SG
kristadelfianer	kristadelfianeren	N;DEF;SG
hendig	hendig	ADJ;NEUT;SG
eksistens	eksistenser	N;NDEF;PL
årvåkenhet	årvåkenheta	N;DEF;SG
kroat	kroaten	N;DEF;SG
vie	vidde	V;PST
bokstavelig	bokstavelige	ADJ;DEF;SG+PL
familie	familier	N;NDEF;PL
ulydighet	ulydighetene	N;DEF;PL
batteri	batteria	N;DEF;PL
vakuum	vakuumet	N;DEF;SG
flom	flommer	N;NDEF;PL
eikenøtt	eikenøtten	N;DEF;SG
vask	vaskene	N;DEF;PL
formalisere	formaliserte	V;PST
pulveraktig	pulveraktige	ADJ;DEF;SG+PL
vie	vigde	V;PST
likestrøm	likestrømmer	N;NDEF;PL
holder	holdere	N;NDEF;PL
konsultere	konsultert	V.PTCP;PST
gammastråling	gammastrålingen	N;DEF;SG
likestrøm	likestrømmen	N;DEF;SG
bestille	bestilt	V.PTCP;PST
utvikling	utviklingene	N;DEF;PL
råd	rådene	N;DEF;PL
galoppere	galoppert	V.PTCP;PST
maldiver	maldiverne	N;DEF;PL
avfyre	avfyrt	V.PTCP;PST
overskudd	overskudda	N;DEF;PL
stork	storken	N;DEF;SG
klisjé	klisjeer	N;NDEF;PL
løype	løypte	V;PST
friksjon	friksjonen	N;DEF;SG
linse	linsen	N;DEF;SG
galskap	galskapene	N;DEF;PL
selvmord	selvmorda	N;DEF;PL
ubrukt	ubrukte	ADJ;DEF;SG+PL
miste	mister	V;PRS
flyfoto	flyfotoene	N;DEF;PL
diplomat	diplomatene	N;DEF;PL
beist	beista	N;DEF;PL
markedsandel	markedsandelen	N;DEF;SG
takke	takket	V;PST
bombe	bomber	V;PRS
sjø	sjøene	N;DEF;PL
tegnebord	tegneborda	N;DEF;PL
entreprenør	entreprenører	N;NDEF;PL
monolog	monologen	N;DEF;SG
fenghette	fenghetten	N;DEF;SG
teater	teater	N;NDEF;PL
etablere	etablerende	V.PTCP;PRS
abkhaser	abkhaserne	N;DEF;PL
konspirasjonsteori	konspirasjonsteorien	N;DEF;SG
jord	jorda	N;DEF;SG
sabotasje	sabotasjene	N;DEF;PL
synonym	synonym	N;NDEF;PL
sluse	slusene	N;DEF;PL
krangel	krangler	N;NDEF;PL
sardin	sardiner	N;NDEF;PL
rogn	rognene	N;DEF;PL
snøbyge	snøbygen	N;DEF;SG
flyfoto	flyfotoer	N;NDEF;PL
øvelse	øvelsen	N;DEF;SG
dekke	dekket	V;PST
dekke	dekkene	N;DEF;PL
utvikling	utviklinger	N;NDEF;PL
avsnitt	avsnittene	N;DEF;PL
irlender	irlendere	N;NDEF;PL
vanlig	vanligst	ADJ;SPRL;NDEF
leke	leker	N;NDEF;PL
g-streng	g-strengene	N;DEF;PL
kråke	kråka	N;DEF;SG
or	oren	N;DEF;SG
høyesterett	høyesteretten	N;DEF;SG
stadion	stadiona	N;DEF;PL
krokus	krokus	N;NDEF;PL
univers	universer	N;NDEF;PL
perfeksjon	perfeksjoner	N;NDEF;PL
rekke	rekkene	N;DEF;PL
kanon	kanonen	N;DEF;SG
bryllup	bryllupa	N;DEF;PL
talgokse	talgoksen	N;DEF;SG
laboratorium	laboratorier	N;NDEF;PL
drap	drap	N;NDEF;PL
daglig	daglig	ADJ;NEUT;SG
romtemperatur	romtemperaturene	N;DEF;PL
frispark	frispark	N;NDEF;PL
ledd	ledda	N;DEF;PL
sentrum	sentret	N;DEF;SG
katedral	katedralen	N;DEF;SG
sikksakkbevegelse	sikksakkbevegelsen	N;DEF;SG
fregnet	fregnet	ADJ;NEUT;SG
nesebor	nesebora	N;DEF;PL
framgang	framgangen	N;DEF;SG
omkrets	omkretsene	N;DEF;PL
blodhund	blodhunder	N;NDEF;PL
sandstrand	sandstranda	N;DEF;SG
nakke	nakkene	N;DEF;PL
kirkegjenger	kirkegjengere	N;NDEF;PL
advokat	advokatene	N;DEF;PL
trene	trente	V;PST
lamme	lammer	V;PRS
bleike	bleika	V.PTCP;PST
myke	myket	V;PST
jackpot	jackpotene	N;DEF;PL
politi	politiene	N;DEF;PL
annen	andre	ADJ;DEF
voks	voks	N;NDEF;PL
overstige	oversteget	V.PTCP;PST
styre	styrer	V;PRS
hyperlenke	hyperlenkene	N;DEF;PL
diskvalifisere	diskvalifiserende	V.PTCP;PRS
halvøy	halvøya	N;DEF;SG
nedleggelse	nedleggelsen	N;DEF;SG
tempel	tempel	N;NDEF;PL
nødvendig	nødvendigst	ADJ;SPRL;NDEF
kapitél	kapitéla	N;DEF;PL
spektrum	spektra	N;DEF;PL
fiberoptisk	fiberoptisk	ADJ;NEUT;SG
uvær	uværene	N;DEF;PL
undersøke	undersøkt	V.PTCP;PST
abkhaser	abkhasere	N;NDEF;PL
strand	strender	N;NDEF;PL
forsinke	forsink	V;IMP
newzealender	newzealenderen	N;DEF;SG
sekk	sekker	N;NDEF;PL
green	greenen	N;DEF;SG
sort	sort	ADJ;NEUT;SG
ørret	ørretene	N;DEF;PL
togoleser	togoleserne	N;DEF;PL
skibakke	skibakker	N;NDEF;PL
karm	karmene	N;DEF;PL
heire	heirene	N;DEF;PL
trene	trenende	V.PTCP;PRS
furu	furua	N;DEF;SG
kirurg	kirurgene	N;DEF;PL
alternativ	alternativet	N;DEF;SG
bygge	bygg	V;IMP
danser	danserne	N;DEF;PL
skater	skatere	N;NDEF;PL
luftfoto	luftfotoet	N;DEF;SG
kypriot	kyprioten	N;DEF;SG
kryptere	krypterte	V;PST
vinter	vintere	N;NDEF;PL
minutt	minuttene	N;DEF;PL
busk	busker	N;NDEF;PL
rosmarin	rosmarinene	N;DEF;PL
komma	kommaene	N;DEF;PL
akkompagnere	akkompagnert	V.PTCP;PST
kabinett	kabinettene	N;DEF;PL
konsentrasjon	konsentrasjonene	N;DEF;PL
stendød	stendøde	ADJ;DEF;PL
grandtante	grandtantene	N;DEF;PL
mutter	mutre	N;NDEF;PL
kulturell	kulturelle	ADJ;DEF;SG+PL
kompetanse	kompetansene	N;DEF;PL
midtlinje	midtlinjene	N;DEF;PL
nigerianer	nigerianere	N;NDEF;PL
taushet	taushetene	N;DEF;PL
sjokolade	sjokolader	N;NDEF;PL
karpe	karper	N;NDEF;PL
nyttårsdag	nyttårsdagen	N;DEF;SG
renslighet	rensligheten	N;DEF;SG
bulevard	bulevarden	N;DEF;SG
gjemme	gjemt	V.PTCP;PST
halvdel	halvdelen	N;DEF;SG
vaskemiddel	vaskemidlene	N;DEF;PL
eksplosjon	eksplosjonen	N;DEF;SG
vertsmaskin	vertsmaskinen	N;DEF;SG
publikasjon	publikasjonene	N;DEF;PL
eier	eiere	N;NDEF;PL
engelskspråklig	engelskspråklig	ADJ;NEUT;SG
kappe	kappa	N;DEF;SG
leke	lekte	V;PST
gjennomføre	gjennomfører	V;PRS
angstskrik	angstskrik	N;NDEF;PL
jungel	jungler	N;NDEF;PL
finne sted	funnet sted	V.PTCP;PST
kateter	katetra	N;DEF;PL
damp	dampene	N;DEF;PL
høyskole	høyskoler	N;NDEF;PL
produsere	produserer	V;PRS
oppleve	opplev	V;IMP
kanadier	kanadierne	N;DEF;PL
klippe	klipper	N;NDEF;PL
kjede	kjeden	N;DEF;SG
ensemble	ensembla	N;DEF;PL
sjøkart	sjøkartet	N;DEF;SG
motsetning	motsetningen	N;DEF;SG
lei	leien	N;DEF;SG
panikk	panikken	N;DEF;SG
grå	gråeste	ADJ;SPRL;DEF
sigøyner	sigøyneren	N;DEF;SG
skru	skru	V;IMP
gnager	gnagerne	N;DEF;PL
campingvogn	campingvogner	N;NDEF;PL
flaggermus	flaggermusene	N;DEF;PL
semittisk	semittiske	ADJ;DEF;SG+PL
fantasere	fantaserte	V;PST
nøytral	nøytralt	ADJ;NEUT;SG
gnage	gnaget	V;PST
kjenne	kjenner	V;PRS
rettighet	rettighetene	N;DEF;PL
negl	negler	N;NDEF;PL
melkesjokolade	melkesjokolader	N;NDEF;PL
datavirus	datavirusa	N;DEF;PL
krangle	krangle	V;IMP
sted	steder	N;NDEF;PL
hemmelighet	hemmeligheten	N;DEF;SG
grov	groveste	ADJ;SPRL;DEF
jevn	jevnest	ADJ;SPRL;NDEF
snøfall	snøfallene	N;DEF;PL
hage	hager	N;NDEF;PL
setning	setningen	N;DEF;SG
kø	køen	N;DEF;SG
trofé	troféene	N;DEF;PL
rotte	rotta	N;DEF;SG
termostat	termostatene	N;DEF;PL
streng	strengest	ADJ;SPRL;NDEF
arbeide	arbeidet	V;PST
atlas	atlasene	N;DEF;PL
brystholder	brystholderen	N;DEF;SG
forbedre	forbedret	V;PST
betaling	betalinger	N;NDEF;PL
forvarsel	forvarslene	N;DEF;PL
mæle	mælet	N;DEF;SG
tørket	tørkede	ADJ;DEF;SG+PL
majones	majonesene	N;DEF;PL
eggehvite	eggehvitene	N;DEF;PL
drikke	drukket	V.PTCP;PST
feromon	feromonet	N;DEF;SG
identisk	identiske	ADJ;DEF;SG+PL
arm	arme	ADJ;DEF;SG+PL
nordmann	nordmannen	N;DEF;SG
ordbok	ordbøkene	N;DEF;PL
påskesøndag	påskesøndagen	N;DEF;SG
klassifikasjon	klassifikasjonen	N;DEF;SG
hake	haker	N;NDEF;PL
salmebok	salmebøkene	N;DEF;PL
ustabil	ustabilt	ADJ;NEUT;SG
stattholder	stattholderne	N;DEF;PL
bibliotekar	bibliotekarer	N;NDEF;PL
rabatt	rabattene	N;DEF;PL
bøye	bøyer	V;PRS
nedgradere	nedgraderte	V;PST
kanin	kaninen	N;DEF;SG
støtte	støtta	V;PST
bevisst	bevisst	ADJ;NEUT;SG
forvente	forventet	V;PST
håndhilse	håndhils	V;IMP
håndjern	håndjernet	N;DEF;SG
sykdom	sykdommer	N;NDEF;PL
så	så	V;IMP
utfordring	utfordringene	N;DEF;PL
barnelærdom	barnelærdomen	N;DEF;SG
skogbruk	skogbrukene	N;DEF;PL
ansvar	ansvaret	N;DEF;SG
objektiv	objektiv	N;NDEF;PL
fuktighetskrem	fuktighetskremer	N;NDEF;PL
tordensky	tordenskyen	N;DEF;SG
glamour	glamouren	N;DEF;SG
blad	blader	N;NDEF;PL
band	banda	N;DEF;PL
montenegrinsk	montenegrinsk	ADJ;NEUT;SG
soveværelse	soveværelset	N;DEF;SG
virksom	virksomme	ADJ;DEF;SG+PL
hele	helet	V.PTCP;PST
skjønnhetssalong	skjønnhetssalongen	N;DEF;SG
stilfull	stilfullt	ADJ;NEUT;SG
forbedre	forbedra	V;PST
høste	høst	V;IMP
stat	staten	N;DEF;SG
sykle	sykler	V;PRS
slektskap	slektskapet	N;DEF;SG
utsette	utsatt	V.PTCP;PST
suge	sugde	V;PST
fysiker	fysikeren	N;DEF;SG
girkasse	girkassa	N;DEF;SG
encyklopedi	encyklopedien	N;DEF;SG
nepalsk	nepalske	ADJ;DEF;SG+PL
stjernebilde	stjernebilder	N;NDEF;PL
filleting	filletingen	N;DEF;SG
røveri	røveriet	N;DEF;SG
overfiske	overfisket	N;DEF;SG
overraske	overraskende	V.PTCP;PRS
labyrint	labyrinten	N;DEF;SG
egenskap	egenskaper	N;NDEF;PL
tygge	tygger	V;PRS
føner	føner	N;NDEF;SG
fjellside	fjellsidene	N;DEF;PL
ekvator	ekvatoren	N;DEF;SG
het	hett	ADJ;NEUT;SG
eksempel	eksemplet	N;DEF;SG
fortelle	fortellende	V.PTCP;PRS
bulgarsk	bulgarsk	ADJ;NEUT;SG
sider	siderne	N;DEF;PL
romertall	romertall	N;NDEF;PL
foajé	foajeen	N;DEF;SG
kjemiker	kjemikere	N;NDEF;PL
mykne	mykna	V;PST
modell	modeller	N;NDEF;PL
bad	badene	N;DEF;PL
svarteliste	svartelista	N;DEF;SG
datter	døtrer	N;NDEF;PL
artikkel	artiklene	N;DEF;PL
studere	studert	V.PTCP;PST
objekt	objekt	N;NDEF;PL
posisjon	posisjonene	N;DEF;PL
dverg	dvergen	N;DEF;SG
slekt	slekter	N;NDEF;PL
suge	sug	V;IMP
lås	låsa	N;DEF;PL
nyttår	nyttårene	N;DEF;PL
betydning	betydningene	N;DEF;PL
tone	toner	N;NDEF;PL
maursluker	maurslukeren	N;DEF;SG
sang	sangene	N;DEF;PL
halvautomatisk	halvautomatiske	ADJ;DEF;SG+PL
frykte	fryktende	V.PTCP;PRS
premiere	premierene	N;DEF;PL
konkurrent	konkurrenten	N;DEF;SG
and	endene	N;DEF;PL
korstog	korstoga	N;DEF;PL
teaterstykke	teaterstykka	N;DEF;PL
begrep	begrepa	N;DEF;PL
tillate	tillot	V;PST
skøyteløper	skøyteløperen	N;DEF;SG
klaustrofobisk	klaustrofobisk	ADJ;NEUT;SG
femtedel	femtedeler	N;NDEF;PL
unik	unike	ADJ;DEF;SG+PL
vinglass	vinglassa	N;DEF;PL
heissjakt	heissjakter	N;NDEF;PL
sørafrikansk	sørafrikanske	ADJ;DEF;SG+PL
overføre	overfører	V;PRS
svakhet	svakheta	N;DEF;SG
røyl	røylene	N;DEF;PL
boks	boksene	N;DEF;PL
trille	trilla	N;DEF;SG
oppfinnelse	oppfinnelsene	N;DEF;PL
tavle	tavlen	N;DEF;SG
blokk	blokkene	N;DEF;PL
ting	tinga	N;DEF;PL
hoste	hostet	V;PST
uaktsom	uaktsomme	ADJ;DEF;SG+PL
persisk	persisken	N;DEF;SG
mellomstor	mellomstore	ADJ;DEF;SG+PL
tankskip	tankskip	N;NDEF;PL
vinner	vinneren	N;DEF;SG
sverd	sverda	N;DEF;PL
ørken	ørkener	N;NDEF;PL
magnolia	magnoliaene	N;DEF;PL
tonn	tonna	N;DEF;PL
plastfolie	plastfolier	N;NDEF;PL
hodepine	hodepiner	N;NDEF;PL
glemme	glemmer	V;PRS
kopper	koppene	N;DEF;PL
minimere	minimer	V;IMP
heise	heis	V;IMP
veto	vetoene	N;DEF;PL
kommunikasjon	kommunikasjonen	N;DEF;SG
filmstjerne	filmstjernen	N;DEF;SG
leve	levende	V.PTCP;PRS
program	programmer	N;NDEF;PL
leverandør	leverandøren	N;DEF;SG
valmue	valmuer	N;NDEF;PL
utforme	utformende	V.PTCP;PRS
samling	samlinga	N;DEF;SG
boikott	boikotten	N;DEF;SG
etterligne	etterlignet	V;PST
kollisjon	kollisjonene	N;DEF;PL
sjimpanse	sjimpanser	N;NDEF;PL
suge	suga	V.PTCP;PST
lånord	lånord	N;NDEF;PL
gnage	gnager	V;PRS
dagbok	dagbøkene	N;DEF;PL
katastrofe	katastrofer	N;NDEF;PL
benytte	benytta	V;PST
avholde	avhold	V;IMP
beskyttelse	beskyttelsen	N;DEF;SG
påskeegg	påskeegg	N;NDEF;PL
jakte	jakta	V;PST
danse	danser	V;PRS
menneske	menneska	N;DEF;PL
puré	pureen	N;DEF;SG
kompresjon	kompresjonene	N;DEF;PL
radar	radarene	N;DEF;PL
fornavn	fornavnet	N;DEF;SG
hardfør	hardføre	ADJ;DEF;SG+PL
uhelbredelig	uhelbredelig	ADJ;NEUT;SG
gaffeltruck	gaffeltrucken	N;DEF;SG
olden	oldenene	N;DEF;PL
skoggrense	skoggrensa	N;DEF;SG
trykk	trykket	N;DEF;SG
galakse	galakser	N;NDEF;PL
transportmiddel	transportmiddelet	N;DEF;SG
fast	faste	ADJ;DEF;SG+PL
kutte	kutta	V;PST
desertør	desertørene	N;DEF;PL
celle	celler	N;NDEF;PL
bordell	bordellen	N;DEF;SG
blek	blekere	ADJ;CMPR
tre	tredd	V.PTCP;PST
hele	helende	V.PTCP;PRS
bygd	bygda	N;DEF;SG
løs	løsest	ADJ;SPRL;NDEF
film	filmene	N;DEF;PL
dreiemoment	dreiemomenter	N;NDEF;PL
ghanesisk	ghanesiske	ADJ;DEF;SG+PL
kommunikasjon	kommunikasjoner	N;NDEF;PL
saltholdig	saltholdige	ADJ;DEF;SG+PL
roman	romanene	N;DEF;PL
balsampære	balsampæra	N;DEF;SG
avtale	avtalene	N;DEF;PL
årlig	årlig	ADJ;NEUT;SG
trampoline	trampoliner	N;NDEF;PL
hjemmelaget	hjemmelagede	ADJ;DEF;SG+PL
danse	dansende	V.PTCP;PRS
karboksylsyre	karboksylsyrer	N;NDEF;PL
ingenmannsland	ingenmannslandet	N;DEF;SG
kastanje	kastanjen	N;DEF;SG
fartøy	fartøyer	N;NDEF;PL
kolposkop	kolposkop	N;NDEF;PL
flatbrystet	flatbrystede	ADJ;DEF;SG+PL
tøff	tøffere	ADJ;CMPR
brunsj	brunsjer	N;NDEF;PL
sjukebil	sjukebiler	N;NDEF;PL
hyene	hyener	N;NDEF;PL
langsom	langsommere	ADJ;CMPR
olje	oljene	N;DEF;PL
langfredag	langfredagen	N;DEF;SG
rolle	rollene	N;DEF;PL
tredjedel	tredjedelene	N;DEF;PL
veps	vepser	N;NDEF;PL
fartøy	fartøyene	N;DEF;PL
luksus	luksusen	N;DEF;SG
budsjett	budsjettet	N;DEF;SG
amatør	amatører	N;NDEF;PL
prøve	prøva	N;DEF;SG
saudiaraber	saudiaraberen	N;DEF;SG
elektromotor	elektromotorer	N;NDEF;PL
bryllupskake	bryllupskaken	N;DEF;SG
rabatt	rabatten	N;DEF;SG
tilhenger	tilhengere	N;NDEF;PL
undervassbåt	undervassbåter	N;NDEF;PL
belizer	belizeren	N;DEF;SG
under	undre	N;NDEF;SG
interiør	interiøra	N;DEF;PL
bordell	bordella	N;DEF;PL
zambisk	zambisk	ADJ;NEUT;SG
bryst	brysta	N;DEF;PL
børste	børstene	N;DEF;PL
farmasøyt	farmasøyten	N;DEF;SG
kolposkop	kolposkopet	N;DEF;SG
skolekorps	skolekorpset	N;DEF;SG
inndele	inndel	V;IMP
glassmester	glassmesteren	N;DEF;SG
forlovede	forloveder	N;NDEF;PL
trio	trioen	N;DEF;SG
tennisbane	tennisbanene	N;DEF;PL
kjerub	kjeruber	N;NDEF;PL
selskap	selskapene	N;DEF;PL
gate	gatene	N;DEF;PL
nasjonalitet	nasjonalitetene	N;DEF;PL
kjemiker	kjemikerne	N;DEF;PL
krysse	krysser	V;PRS
spiller	spilleren	N;DEF;SG
appelsin	appelsinene	N;DEF;PL
zoomobjektiv	zoomobjektivene	N;DEF;PL
dividere	dividerer	V;PRS
elektron	elektronene	N;DEF;PL
røveri	røveria	N;DEF;PL
latterliggjøre	latterliggjorde	V;PST
øyeblikk	øyeblikket	N;DEF
tur	turer	N;NDEF;PL
skoleveske	skoleveska	N;DEF;SG
anerkjenne	anerkjente	V;PST
sjukehus	sjukehusene	N;DEF;PL
troll	troll	N;NDEF;PL
vinduspusser	vinduspusserne	N;DEF;PL
aktivitet	aktiviteten	N;DEF;SG
nonne	nonner	N;NDEF;PL
misfarge	misfarget	V;PST
sverd	sverd	N;NDEF;PL
klump	klumpene	N;DEF;PL
afrikansk	afrikansk	ADJ;FEM
kommandør	kommandører	N;NDEF;PL
sanktlucianer	sanktlucianere	N;NDEF;PL
kokk	kokker	N;NDEF;PL
tallrik	tallrike	ADJ;DEF;SG+PL
kiosk	kiosker	N;NDEF;PL
sportslig	sportslige	ADJ;DEF;SG+PL
brukernavn	brukernavnet	N;DEF;SG
menneskerettighetsforkjemper	menneskerettighetsforkjempere	N;NDEF;PL
rike	riker	N;NDEF;PL
bratt	bratt	ADJ;NEUT;SG
bensin	bensinen	N;DEF;SG
pilot	pilotene	N;DEF;PL
forum	forumet	N;DEF;SG
skadelig	skadelige	ADJ;DEF;SG+PL
gravemaskin	gravemaskiner	N;NDEF;PL
offiser	offiserer	N;NDEF;PL
dødsstraff	dødsstraffer	N;NDEF;PL
mote	moten	N;DEF;SG
tillate	tillater	V;PRS
kosedyr	kosedyret	N;DEF;SG
overenskomst	overenskomster	N;NDEF;PL
potte	potten	N;DEF;SG
sludd	sluddet	N;DEF;SG
neglelakk	neglelakken	N;DEF;SG
tendens	tendensen	N;DEF;SG
stivelse	stivelsen	N;DEF;SG
svarteliste	svartelist	V;IMP
levested	levestedene	N;DEF;PL
sjøkart	sjøkartene	N;DEF;PL
kondensasjon	kondensasjoner	N;NDEF;PL
geværild	geværilden	N;DEF;SG
langbue	langbuene	N;DEF;PL
hjelper	hjelperne	N;DEF;PL
fyrtårn	fyrtårn	N;NDEF;PL
følsom	følsomt	ADJ;NEUT;SG
syltetøy	syltetøyet	N;DEF;SG
levere	levert	V.PTCP;PST
gasell	gaseller	N;NDEF;PL
ytringsfrihet	ytringsfrihetene	N;DEF;PL
oppheve	opphevet	V.PTCP;PST
oppfinner	oppfinneren	N;DEF;SG
oppvask	oppvasken	N;DEF;SG
ekorn	ekorner	N;NDEF;PL
astronomi	astronomien	N;DEF;SG
smaragd	smaragder	N;NDEF;PL
leie	leid	V.PTCP;PST
billig	billigste	ADJ;DEF;PL
svindel	svindelen	N;DEF;SG
tøff	tøffeste	ADJ;SPRL;DEF
slagskip	slagskip	N;NDEF;PL
hele	helt	V.PTCP;PST
kjæreste	kjærester	N;NDEF;PL
lydpotte	lydpotta	N;DEF;SG
stilling	stillinger	N;NDEF;PL
foreldet	foreldede	ADJ;DEF;SG+PL
pioner	pioneren	N;DEF;SG
justere	justert	V.PTCP;PST
benytte	benyttende	V.PTCP;PRS
oppslagsverk	oppslagsverket	N;DEF;SG
aprikos	aprikoser	N;NDEF;PL
potteplante	potteplanta	N;DEF;SG
program	programmet	N;DEF;SG
utseende	utseendene	N;DEF;PL
fordele	fordelte	V;PST
blomsterbutikk	blomsterbutikker	N;NDEF;PL
demontere	demontert	V.PTCP;PST
søvn	søvnen	N;DEF;SG
korallrev	korallrevene	N;DEF;PL
skulderblad	skulderbladet	N;DEF;SG
avsporing	avsporinger	N;NDEF;PL
medlemskap	medlemskapet	N;DEF;SG
anstøtelighet	anstøteligheten	N;DEF;SG
snøplog	snøploger	N;NDEF;PL
termostat	termostaten	N;DEF;SG
sjekke	sjekka	V;PST
trommestikke	trommestikka	N;DEF;SG
belegge	belagt	V.PTCP;PST
provins	provinsene	N;DEF;PL
dagbok	dagboken	N;DEF;SG
skjermskudd	skjermskuddene	N;DEF;PL
senter	sentre	N;NDEF;PL
leppestift	leppestiften	N;DEF;SG
tekste	teksta	V;PST
felt	feltet	N;DEF;SG
eksitere	eksitert	V.PTCP;PST
frisyre	frisyrene	N;DEF;PL
fugleskremsel	fugleskremslet	N;DEF;SG
dybde	dybder	N;NDEF;PL
cubaner	cubanerne	N;DEF;PL
bind	bindet	N;DEF;SG
elfenbeinstårn	elfenbeinstårnene	N;DEF;PL
fryktelig	fryktelige	ADJ;DEF;SG+PL
historiker	historikerene	N;DEF;PL
leve	levd	V.PTCP;PST
bachelorgrad	bachelorgraden	N;DEF;SG
skulder	skuldra	N;DEF;SG
ampulle	ampullene	N;DEF;PL
bursdag	bursdager	N;NDEF;PL
fald	falden	N;DEF;SG
systematisk	systematisk	ADJ;NEUT;SG
sjukebil	sjukebilene	N;DEF;PL
boble	bobla	V;PST
oppfordre	oppfordr	V;IMP
rep	repa	N;DEF;PL
orkan	orkanene	N;DEF;PL
syrer	syrere	N;NDEF;PL
forvente	forventa	V;PST
parti	partia	N;DEF;PL
fald	falder	N;NDEF;PL
skvadron	skvadronen	N;DEF;SG
ledelse	ledelser	N;NDEF;PL
kineser	kineseren	N;DEF;SG
bue	buer	N;NDEF;PL
steinblokk	steinblokken	N;DEF;SG
bakeri	bakeriene	N;DEF;PL
forfatter	forfatteren	N;DEF;SG
psykologi	psykologier	N;NDEF;PL
valutakurs	valutakurser	N;NDEF;PL
forsvare	forsvarte	V;PST
veps	vepsene	N;DEF;PL
forsagelse	forsagelsen	N;DEF;SG
sverd	sverdene	N;DEF;PL
bajonett	bajonettene	N;DEF;PL
krystall	krystalla	N;DEF;PL
arkitekt	arkitekter	N;NDEF;PL
korketrekker	korketrekkere	N;NDEF;PL
forby	forbøy	V;PST
omslag	omslagene	N;DEF;PL
brann	brannen	N;DEF;SG
boble	boblende	V.PTCP;PRS
monarki	monarkiet	N;DEF;SG
alder	alderne	N;DEF;PL
støyttann	støyttannen	N;DEF;SG
kirke	kirker	N;NDEF;PL
konvolutt	konvoluttene	N;DEF;PL
evne	evnene	N;DEF;PL
jakte	jakt	V;IMP
tap	tap	N;NDEF;PL
pinsevenn	pinsevenner	N;NDEF;PL
vokse	vokser	V;PRS
slekt	slekta	N;DEF;SG
alarmere	alarmerende	V.PTCP;PRS
søle	sølen	N;DEF;SG
hummer	hummeren	N;DEF;SG
langfinger	langfingre	N;NDEF;PL
elfenbeinstårn	elfenbeinstårna	N;DEF;PL
orientere	orienter	V;IMP
pumpe	pumpen	N;DEF;SG
børste	børster	N;NDEF;PL
engelsk	engelsk	ADJ;NEUT;SG
estlender	estlenderen	N;DEF;SG
gaffeltruck	gaffeltruckene	N;DEF;PL
partner	partneren	N;DEF;SG
tegnspråk	tegnspråka	N;DEF;PL
svale	svaler	N;NDEF;PL
gælisk	gælisk	ADJ;NEUT;SG
oppfordre	oppfordrer	V;PRS
forårsake	forårsak	V;IMP
sammenheng	sammenhenger	N;NDEF;PL
skygge	skygget	V.PTCP;PST
koreansk	koreanske	ADJ;DEF;SG+PL
pisk	pisken	N;DEF;SG
aprikos	aprikosene	N;DEF;PL
vår	vårer	N;NDEF;PL
øke	øket	V;PST
føde	føder	V;PRS
virus	virusa	N;DEF;PL
viser	viseren	N;DEF;SG
privatlærer	privatlæreren	N;DEF;SG
dvergbjerk	dvergbjerker	N;NDEF;PL
tilstrekkelig	tilstrekkelige	ADJ;DEF;SG+PL
tørste	tørstet	V;PST
gjennombrudd	gjennombruddene	N;DEF;PL
tribune	tribuner	N;NDEF;PL
metode	metoden	N;DEF;SG
jordsmonn	jordsmonn	N;NDEF;PL
fluid	fluida	N;DEF;PL
watt	watten	N;DEF;SG
telefonsentral	telefonsentralen	N;DEF;SG
søle	søler	V;PRS
tittel	titler	N;NDEF;PL
påhengsmotor	påhengsmotoren	N;DEF;SG
alter	altera	N;DEF;PL
diagram	diagrammer	N;NDEF;PL
regndråpe	regndråpene	N;DEF;PL
elv	elven	N;DEF;SG
desertering	deserteringa	N;DEF;SG
barnevogn	barnevogna	N;DEF;SG
sikkerhetsnål	sikkerhetsnålene	N;DEF;PL
fødselsdag	fødselsdagene	N;DEF;PL
fylle	fylt	V.PTCP;PST
speil	speilet	N;DEF;SG
bil	bilene	N;DEF;PL
renneløkke	renneløkken	N;DEF;SG
fylke	fylkene	N;DEF;PL
økosystem	økosystemene	N;DEF;PL
stavelse	stavelsen	N;DEF;SG
overleve	overlev	V;IMP
politikvinne	politikvinnen	N;DEF;SG
feste	fest	V;IMP
trykkoker	trykkokere	N;NDEF;PL
kjøttdeig	kjøttdeiger	N;NDEF;PL
umoden	umodent	ADJ;NEUT;SG
hus	husene	N;DEF;PL
omaner	omanere	N;NDEF;PL
foss	fossene	N;DEF;PL
overvelde	overvelder	V;PRS
fusjon	fusjonene	N;DEF;PL
vinterlig	vinterlig	ADJ;NEUT;SG
danne	dann	V;IMP
penis	penisen	N;DEF;SG
flaskehals	flaskehalser	N;NDEF;PL
vurdere	vurderende	V.PTCP;PRS
skrekkelig	skrekkeligst	ADJ;SPRL;NDEF
få	fås	V;NFIN;PASS
senegaleser	senegaleseren	N;DEF;SG
organisere	organiserende	V.PTCP;PRS
åsyn	åsyn	N;NDEF;PL
kulehull	kulehull	N;NDEF;PL
brisling	brislinger	N;NDEF;PL
type	typer	N;NDEF;PL
målmann	målmennene	N;DEF;PL
edelsten	edelstenene	N;DEF;PL
mykne	mykner	V;PRS
etasje	etasjer	N;NDEF;PL
sanddyne	sanddynen	N;DEF;SG
åker	åkrene	N;DEF;PL
trio	trioene	N;DEF;PL
nauruer	naurueren	N;DEF;SG
ektepar	ekteparene	N;DEF;PL
transvestitt	transvestitten	N;DEF;SG
gjenkjenne	gjenkjent	V.PTCP;PST
slavisk	slavisk	ADJ;NEUT;SG
brisling	brislingene	N;DEF;PL
kommentere	kommenterte	V;PST
flaggstang	flaggstanga	N;DEF;SG
rytme	rytmer	N;NDEF;PL
saudiaraber	saudiaraberne	N;DEF;PL
trykke	trykt	V.PTCP;PST
kobber	kobberet	N;DEF;SG
anonymitet	anonymiteten	N;DEF;SG
gravemaskin	gravemaskinene	N;DEF;PL
løvinne	løvinnene	N;NDEF;PL
forhåpning	forhåpningen	N;DEF;SG
namibier	namibiere	N;NDEF;PL
sårbar	sårbar	ADJ;CMPR
påskeegg	påskeeggene	N;DEF;PL
tallrik	tallrikt	ADJ;NEUT;SG
gulv	gulvene	N;DEF;PL
medisin	medisinen	N;DEF;SG
tiår	tiårene	N;DEF;PL
morsenøkkel	morsenøklene	N;DEF;PL
pianist	pianister	N;NDEF;PL
jernbane	jernbanen	N;DEF;SG
alder	aldre	N;NDEF;PL
understreke	understreker	V;PRS
åpning	åpningen	N;DEF;SG
sortere	sortert	V.PTCP;PST
ruste	rusta	V;PST
forhandling	forhandlinger	N;NDEF;PL
bevæpnet	bevæpnet	ADJ;NEUT;SG
sportsbil	sportsbiler	N;NDEF;PL
disig	disig	ADJ;NEUT;SG
multiplum	multipla	N;NDEF;PL
potteplante	potteplanten	N;DEF;SG
hypnose	hypnosene	N;DEF;PL
saks	saksen	N;DEF;SG
silikon	silikona	N;DEF;PL
smake	smak	V;IMP
bokser	boksere	N;NDEF;PL
forsterke	forsterker	V;PRS
strømpe	strømpa	N;DEF;SG
svarteliste	svartelistene	N;DEF;PL
bad	bada	N;DEF;PL
munn	munnene	N;DEF;PL
soverom	soveromma	N;DEF;PL
aminosyre	aminosyrer	N;NDEF;PL
kontinent	kontinent	N;NDEF;PL
gnu	gnuer	N;NDEF;PL
skygge	skygd	V.PTCP;PST
stridsøks	stridsøksen	N;DEF;SG
marsjere	marsjerte	V;PST
postkort	postkortene	N;DEF;PL
armener	armeneren	N;DEF;SG
anbefaling	anbefalingene	N;DEF;PL
identifisere	identifiserte	V;PST
håndjern	håndjernene	N;DEF;PL
lekke	lekker	V;PRS
apparat	apparata	N;DEF;PL
jernbanelinje	jernbanelinjen	N;DEF;SG
tyrker	tyrkerne	N;DEF;PL
portugiser	portugiseren	N;DEF;SG
ravn	ravnen	N;DEF;SG
kamuflasje	kamuflasjen	N;DEF;SG
atlas	atlas	N;NDEF;PL
tilskuer	tilskuere	N;NDEF;PL
rop	ropa	N;DEF;PL
modellfly	modellfly	N;NDEF;PL
sjekke	sjekk	V;IMP
snøball	snøballen	N;DEF;SG
hylle	hyllet	V.PTCP;PST
juletre	juletreet	N;DEF;SG
presentere	presenterte	V;PST
ivoriansk	ivoriansk	ADJ;NEUT;SG
svarting	svartinger	N;NDEF;PL
evne	evna	N;DEF;SG
kokepunkt	kokepunktene	N;DEF;PL
dobbeltmoral	dobbeltmoralene	N;DEF;PL
overføre	overfør	V;IMP
bryllupskake	bryllupskakene	N;DEF;PL
kompressor	kompressoren	N;DEF;SG
overleve	overlevde	V;PST
galge	galger	N;NDEF;PL
dugnad	dugnader	N;NDEF;PL
kort	kortest	ADJ;NDEF;PL
frost	frosten	N;DEF;SG
multiplum	multiplumene	N;DEF;PL
husholdning	husholdningen	N;DEF;SG
hunkjønn	hunkjønna	N;DEF;PL
fordømmelse	fordømmelsen	N;DEF;SG
inntrykk	inntrykket	N;DEF;SG
vaskemaskin	vaskemaskiner	N;NDEF;PL
fregatt	fregattene	N;DEF;PL
forrentning	forrentninger	N;NDEF;PL
gjennomgå	gjennomgått	V.PTCP;PST
glemme	glemte	V;PST
tikke	tikker	V;PRS
snøfall	snøfalla	N;DEF;PL
forandre	forandre	V;IMP
kjederøyker	kjederøykerne	N;DEF;PL
bambusrør	bambusrøra	N;DEF;PL
profesjonell	profesjonelle	ADJ;DEF;SG+PL
tvinge	tvang	V;PST
fornavn	fornavn	N;NDEF;PL
fullstendig	fullstendig	ADJ;NEUT;SG
informasjonsteknologi	informasjonsteknologien	N;DEF;SG
tegne	tegna	V;PST
justere	justerte	V;PST
smile	smiler	V;PRS
reinsdyr	reinsdyrene	N;DEF;PL
comeback	comeback	N;NDEF;PL
sentrifugal	sentrifugale	ADJ;DEF;SG+PL
prosjekt	prosjektet	N;DEF;SG
matforgiftning	matforgiftningen	N;DEF;SG
villdyr	villdyra	N;DEF;PL
tank	tanker	N;NDEF;PL
sommertid	sommertiden	N;DEF;SG
høyde	høyder	N;NDEF;PL
sukkerbete	sukkerbeten	N;DEF;SG
kondensasjon	kondensasjonene	N;DEF;PL
øyevipp	øyevippen	N;DEF;SG
gravemaskin	gravemaskinen	N;DEF;SG
karakter	karakteren	N;DEF;SG
balltre	balltre	N;NDEF;PL
posthum	posthume	ADJ;DEF;SG+PL
rwander	rwanderne	N;DEF;PL
amerikansk-engelsk	amerikansk-engelsken	N;DEF;SG
strykejern	strykejernene	N;DEF;PL
foajé	foajéen	N;DEF;SG
grep	grepet	N;DEF;SG
entall	entallene	N;DEF;PL
uttalelse	uttalelser	N;NDEF;PL
verb	verber	N;NDEF;PL
nattpotte	nattpotten	N;DEF;SG
utbredt	utbredt	ADJ;NEUT;SG
storm	stormer	N;NDEF;PL
teaterstykke	teaterstykket	N;DEF;SG
by	byen	N;DEF;SG
ujevn	ujevne	ADJ;DEF;SG+PL
halvmåne	halvmånen	N;DEF;SG
fullstendig	fullstendige	ADJ;DEF;SG+PL
monarki	monarkia	N;DEF;PL
psykopat	psykopatene	N;DEF;PL
apal	apalene	N;DEF;PL
umyndig	umyndige	ADJ;DEF;SG+PL
politiker	politikeren	N;DEF;SG
brunsj	brunsjen	N;DEF;SG
fugl	fugler	N;NDEF;PL
symbol	symbolene	N;DEF;PL
soveværelse	soveværelser	N;NDEF;PL
passform	passformen	N;DEF;SG
rik	rikest	ADJ;SPRL;NDEF
redskap	redskapen	N;DEF;SG
grimase	grimasene	N;DEF;PL
aggressiv	aggressiv	ADJ;SPRL
glassmester	glassmesterne	N;DEF;PL
gods	godsene	N;DEF;PL
sanddyne	sanddynene	N;DEF;PL
skulder	skuldrer	N;NDEF;PL
paleontologi	paleontologien	N;DEF;SG
krysse	kryssa	V;PST
ettermiddag	ettermiddager	N;NDEF;PL
kolon	kolonene	N;DEF;PL
trussel	truslene	N;DEF;PL
synagoge	synagogen	N;DEF;SG
ulovlig	ulovlig	ADJ;NEUT;SG
ponni	ponnien	N;DEF;SG
bind	bindene	N;DEF;PL
nyre	nyra	N;DEF;SG
skjorte	skjorta	N;DEF;SG
jernmalm	jernmalmene	N;DEF;PL
pose	posen	N;DEF;SG
premie	premier	N;NDEF;PL
utdanne	utdanner	V;PRS
nymfe	nymfen	N;DEF;SG
tolkning	tolkninger	N;NDEF;PL
kalender	kalendere	N;NDEF;PL
splitt	splitten	N;DEF;SG
kvinne	kvinnen	N;DEF;SG
hals	halsene	N;DEF;PL
skulderblad	skulderblada	N;DEF;PL
punktum	punktuma	N;DEF;PL
parykk	parykken	N;DEF;SG
tosk	tosker	N;NDEF;PL
visdomstann	visdomstennene	N;DEF;PL
silhuett	silhuettene	N;DEF;PL
person	personene	N;DEF;PL
triumfere	triumferer	V;PRS
ekvatorialguineaner	ekvatorialguineanere	N;NDEF;PL
gammeldags	gammeldags	ADJ;NEUT;SG
prislapp	prislappene	N;DEF;PL
frysepunkt	frysepunktene	N;DEF;PL
skjermutklipp	skjermutklippene	N;DEF;PL
lagune	laguner	N;NDEF;PL
pose	poser	N;NDEF;PL
angstbiting	angstbitinger	N;NDEF;PL
sengetid	sengetidene	N;DEF;PL
økosystem	økosystemet	N;DEF;SG
trommis	trommisen	N;DEF;SG
mørketall	mørketalla	N;DEF;PL
triumfere	triumferte	V;PST
pappa	pappaer	N;NDEF;PL
haglgevær	haglgeværer	N;NDEF;PL
beskyttelse	beskyttelsene	N;DEF;PL
egg	eggene	N;DEF;PL
svartemarje	svartemarjen	N;DEF;SG
verdenskart	verdenskarter	N;NDEF;PL
sjonglere	sjongler	V;IMP
postkort	postkorta	N;DEF;PL
hensyn	hensyna	N;DEF;PL
trulig	trulige	ADJ;DEF;SG+PL
gitar	gitarene	N;DEF;PL
farmakologi	farmakologien	N;DEF;SG
klokke	klokka	N;DEF;SG
flaggermus	flaggermusen	N;DEF;SG
søtlig	søtlig	ADJ;NEUT;SG
spesiell	spesiell	ADJ;CMPR
tjern	tjern	N;NDEF;PL
grunnlegger	grunnleggere	N;NDEF;PL
branndør	branndørene	N;DEF;PL
befolkning	befolkninga	N;DEF;SG
reagensglass	reagensglasset	N;DEF;SG
gyldig	gyldig	ADJ;NEUT;SG
artikkel	artikler	N;NDEF;PL
stenge	steng	V;IMP
utgave	utgava	N;DEF;SG
semikolon	semikoloner	N;NDEF;PL
faktor	faktoren	N;DEF;SG
tomme	tommene	N;DEF;PL
stridsøks	stridsøksa	N;DEF;SG
beskatte	beskattet	V;PST
sektor	sektoren	N;DEF;SG
bordell	bordeller	N;NDEF;PL
kule	kulen	N;DEF;SG
kulehull	kulehullene	N;DEF;PL
fartøy	fartøyet	N;DEF;SG
nysgjerrig	nysgjerrig	ADJ;NEUT;SG
revolver	revolvere	N;NDEF;PL
kyrillisk	kyrillisk	ADJ;NEUT;SG
falle	faller	N;NDEF;PL
styrehus	styrehusa	N;DEF;PL
sandsekk	sandsekken	N;DEF;SG
handlevogn	handlevognen	N;DEF;SG
dusjhode	dusjhodet	N;DEF;SG
topografisk	topografiske	ADJ;DEF;SG+PL
komité	komitéer	N;NDEF;PL
latterliggjøre	latterliggjørende	V.PTCP;PRS
drivstoff	drivstoff	N;NDEF;PL
eksempel	eksempla	N;DEF;PL
sirkelsag	sirkelsagen	N;DEF;SG
hjemmelaget	hjemmelagete	ADJ;DEF;SG+PL
multiplum	multiplumer	N;NDEF;PL
lommepenger	lommepengene	N;DEF;PL
molekyl	molekylene	N;DEF;PL
lande	landende	V.PTCP;PRS
syvendedagsadventist	syvendedagsadventisten	N;DEF;SG
telle	tellet	V;PST
koke	kokt	V.PTCP;PST
gråte	gråt	V;IMP
tradisjon	tradisjonen	N;DEF;SG
romer	romerne	N;DEF;PL
skrive	skriv	V;IMP
dagbok	dagbøker	N;NDEF;PL
mauritanier	mauritaniere	N;NDEF;PL
afrikansk	afrikansk	ADJ;MASC
åverk	åverkene	N;DEF;PL
hebraisk	hebraiske	ADJ;DEF;SG+PL
potteplante	potteplanter	N;NDEF;PL
farmasøyt	farmasøytene	N;DEF;PL
skyggefull	skyggefullt	ADJ;NEUT;SG
libyer	libyere	N;NDEF;PL
stille	stillet	V;PST
personskade	personskadene	N;DEF;PL
reagensglass	reagensglassene	N;DEF;PL
jevndøgn	jevndøgna	N;DEF;PL
ukrainer	ukrainerne	N;DEF;PL
gipsbandasje	gipsbandasjer	N;NDEF;PL
tømmerstokk	tømmerstokken	N;DEF;SG
mine	minene	N;DEF;PL
flyge	fløy	V;PST
tøff	tøffest	ADJ;SPRL;NDEF
langer	langere	N;NDEF;PL
tjern	tjerna	N;DEF;PL
alpakka	alpakkaer	N;NDEF;PL
adskille	adskillende	V.PTCP;PRS
klesskap	klesskapene	N;DEF;PL
topografisk	topografisk	ADJ;NEUT;SG
bølge	bølgen	N;DEF;SG
hoppbakke	hoppbakkene	N;DEF;PL
burkiner	burkinerne	N;DEF;PL
makrell	makrellene	N;DEF;PL
konvolutt	konvolutten	N;DEF;SG
sjekk	sjekken	N;DEF;SG
motvekt	motvektene	N;DEF;PL
forklare	forklar	V;IMP
øyelokk	øyelokkene	N;DEF;PL
skape	skapende	V.PTCP;PRS
dobbelthake	dobbelthaken	N;DEF;SG
rumener	rumenere	N;NDEF;PL
kvalitet	kvaliteter	N;NDEF;PL
gissel	gisselet	N;DEF;SG
skihopping	skihoppingen	N;DEF;SG
utålmodighet	utålmodigheten	N;DEF;SG
anarki	anarkier	N;NDEF;PL
oppfinne	oppfant	V;PST
kildekode	kildekodene	N;DEF;PL
rotte	rotten	N;DEF;SG
påskelilje	påskeliljene	N;DEF;PL
hjelm	hjelmen	N;DEF;SG
jordbær	jordbær	N;NDEF;PL
skinke	skinken	N;DEF;SG
sol	sola	N;DEF;SG
tute	tutende	V.PTCP;PRS
hyperbol	hyperbolene	N;DEF;PL
persisk	persisk	ADJ;NEUT;SG
kunde	kundene	N;DEF;PL
allehånde	allehåndene	N;DEF;PL
redskap	redskap	N;NDEF;PL
finne opp	fant opp	V;PST
kjønn	kjønna	N;DEF;PL
temme	temma	V;PST
siriss	sirissen	N;DEF;SG
rulleskøyte	rulleskøyter	N;NDEF;PL
banke	bank	V;IMP
operette	operettene	N;DEF;PL
hyperbel	hyperbelen	N;DEF;SG
tømmerstokk	tømmerstokkene	N;DEF;PL
føde	fødte	V;PST
sirkulasjon	sirkulasjoner	N;NDEF;PL
side	sidene	N;DEF;PL
disk	disker	N;NDEF;PL
feil	feil	N;NDEF;PL
tekste	tekst	V;IMP
mester	mestere	N;NDEF;PL
senat	senatene	N;DEF;PL
navngi	navngi	V;IMP
obo	oboer	N;NDEF;PL
selvmordsoffer	selvmordsofferet	N;DEF;SG
radioaktiv	radioaktive	ADJ;DEF;SG+PL
enhet	enhetene	N;DEF;PL
verdensmester	verdensmestere	N;NDEF;PL
sykepleier	sykepleierne	N;DEF;PL
rulle	rullet	V;PST
tånegl	tåneglen	N;DEF;SG
engel	englene	N;DEF;PL
kjempe	kjemper	N;NDEF;PL
minoritet	minoritetene	N;DEF;PL
sukkerrør	sukkerrøret	N;DEF;SG
sag	saga	N;DEF;SG
angripe	angrip	V;IMP
kafé	kafeen	N;DEF;SG
kone	konen	N;DEF;SG
spiralfjær	spiralfjærer	N;NDEF;PL
løft	løft	N;NDEF;PL
kupong	kuponger	N;NDEF;PL
utdrag	utdrag	N;NDEF;PL
representere	representerer	V;PRS
feromon	feromon	N;NDEF;PL
glassmester	glassmestere	N;NDEF;PL
løs	løse	ADJ;DEF;SG+PL
motorkjøretøy	motorkjøretøya	N;DEF;PL
ballkjole	ballkjolen	N;DEF;SG
ordfører	ordførere	N;NDEF;PL
avtrekker	avtrekkeren	N;DEF;SG
søppel	søplet	N;DEF;SG
sen	senest	ADJ;SPRL;NDEF
finne	finner	N;NDEF;PL
offer	ofrene	N;DEF;PL
kø	køene	N;DEF;PL
skrive	skriver	V;PRS
treenighet	treenigheta	N;DEF;SG
motsetning	motsetninga	N;DEF;SG
makedonier	makedoniere	N;NDEF;PL
pike	pikene	N;DEF;PL
ting	tinget	N;DEF;SG
svigerbror	svigerbroren	N;DEF;SG
gipsbandasje	gipsbandasjene	N;DEF;PL
tsjader	tsjaderne	N;DEF;PL
støtfanger	støtfangere	N;NDEF;PL
slips	slipsa	N;DEF;PL
mæle	mælene	N;DEF;PL
utvalg	utvalga	N;DEF;PL
blodoverføring	blodoverføringen	N;DEF;SG
matforgiftning	matforgiftninger	N;NDEF;PL
danne	danna	V;PST
håp	håp	N;NDEF;PL
statistikk	statistikker	N;NDEF;PL
resiprok	resiproke	ADJ;DEF;SG+PL
konkurrent	konkurrentene	N;DEF;PL
rå	rær	N;NDEF;PL
krem	kremer	N;NDEF;PL
øyevipp	øyevipper	N;NDEF;PL
hakekors	hakekors	N;NDEF;PL
påhengsmotor	påhengsmotorene	N;DEF;PL
nonne	nonnen	N;DEF;SG
forelder	forelderen	N;DEF;SG
omdirigere	omdirigerer	V;PRS
sjekk	sjekker	N;NDEF;PL
myndighet	myndigheta	N;DEF;SG
træ	trædd	V.PTCP;PST
relativitet	relativiteten	N;DEF;SG
salmebok	salmeboka	N;DEF;SG
seile	seiler	V;PRS
gjestfri	gjestfritt	ADJ;NEUT;SG
akne	akner	N;NDEF;PL
mexicaner	mexicanerne	N;DEF;PL
analyse	analyser	N;NDEF;PL
spille	spilt	V.PTCP;PST
vendepunkt	vendepunktet	N;DEF;SG
lån	lån	N;NDEF;PL
bro	broene	N;DEF;PL
senator	senatorene	N;DEF;PL
skjermskudd	skjermskudda	N;DEF;PL
helle	hellende	V.PTCP;PRS
skinne	skint	V.PTCP;PST
fabrikant	fabrikanter	N;NDEF;PL
akkar	akkaren	N;DEF;SG
fotograf	fotografen	N;DEF;SG
esel	eslene	N;DEF;PL
invadere	invaderende	V.PTCP;PRS
hånd	hender	N;NDEF;PL
palestinsk	palestinske	ADJ;DEF;SG+PL
kjøpe	kjøp	V;IMP
algebra	algebraene	N;DEF;PL
appelsintre	appelsintrea	N;DEF;PL
ravn	ravnene	N;DEF;PL
jakte	jaktet	V;PST
yrke	yrker	N;NDEF;PL
blåse	blås	V;IMP
perfeksjonere	perfeksjonerer	V;PRS
videokamera	videokameraer	N;NDEF;PL
gardin	gardin	N;NDEF;PL
stoppeklokke	stoppeklokka	N;DEF;SG
struktur	strukturen	N;DEF;SG
gummistøvel	gummistøvler	N;NDEF;PL
armbåndsur	armbåndsur	N;NDEF;PL
løselig	løselige	ADJ;DEF;SG+PL
vaskemaskin	vaskemaskinene	N;DEF;PL
lærebok	lærebøkene	N;DEF;PL
praktisk	praktiske	ADJ;DEF;SG+PL
formål	formål	N;NDEF;PL
å	åa	N;DEF;SG
kontekst	kontekster	N;NDEF;PL
haglgevær	haglgeværene	N;DEF;PL
republikansk	republikansk	ADJ;NEUT;SG
lagre	lagret	V;PST
foto	fotoet	N;DEF;SG
vits	vitser	N;NDEF;PL
selektiv	selektive	ADJ;DEF;SG+PL
varsel	varselet	N;DEF;SG
gnu	gnuene	N;DEF;PL
assistent	assistenten	N;DEF;SG
tilfelle	tilfellet	N;DEF;SG
villdyr	villdyrene	N;DEF;PL
løfte	løfter	N;NDEF;PL
høl	hølene	N;DEF;PL
løfte	løfta	N;DEF;PL
kvintett	kvintetten	N;DEF;SG
ferje	ferja	N;DEF;SG
halskjede	halskjeda	N;DEF;PL
spindelvev	spindelvev	N;NDEF;PL
evangelium	evangeliet	N;DEF;SG
teolog	teologen	N;DEF;SG
sopp	soppene	N;DEF;PL
samling	samlingene	N;DEF;PL
sanktvincenter	sanktvincentere	N;NDEF;PL
perfeksjonere	perfeksjonerende	V.PTCP;PRS
muslim	muslimen	N;DEF;SG
revolusjonær	revolusjonærene	N;DEF;PL
pronomen	pronomen	N;NDEF;PL
trommestikke	trommestikken	N;DEF;SG
kanin	kaninene	N;DEF;PL
