чуж	чужлы	N;DAT;SG
овмӧс	овмӧсъяс	N;NOM;PL
ссуз	ссузъясын	N;IN+ESS;PL;LGSPEC1
кватитны	кватитчисны	V;PL;3;PST;PASS;LGSPEC1
ошкӧм	ошкӧмӧн	N;INS;SG
петны	петкӧд	V;IMP;SG;2;CAUS
арка	арка	N;NOM;SG;LGSPEC1
шыд	шыдӧ	N;NOM;SG;PSS1S
ондатра	ондатраӧс	N;HUM;ACC;SG;LGSPEC1
федерация	федерацияӧн	N;INS;SG;LGSPEC1
компот	компот	N;NOM;SG;LGSPEC1
тшак	тшактӧ	N;ACC;SG;PSS2S
янсавны	янсӧд	V;SG;NEG;CAUS
посольство	посольствосянь	N;SG;LGSPEC_EGREXT
чӧжны	чожа	V;SG;1;PRS
гызьыны	гызьӧны	V;PL;3;PRS
мыждыны	мыждынысӧ	V;ACC;NFIN;PSS3S
надея	надеятӧг	N;SG;LGSPEC_CAREXT
вӧшны	вошлӧ	V;SG;3;PRS;LGSPEC_DELIM
труппа	труппалысь	N;ABL;SG;LGSPEC1
отряд	отрядсакӧд	N;COM;SG;LGSPEC_ATTR;LGSPEC1
кывкутысь	кывкутысьнас	ADJ;INS;SG;PSS3S
удмурт	удмуртъясӧс	N;HUM;ACC;PL;PSS1S
тӧвны	тӧлӧдӧ	V;SG;3;PRS;CAUS
веськавны	веськӧдлӧ	V;SG;3;PRS;CAUS;LGSPEC_DELIM
климат	климат	N;NOM;SG;LGSPEC1
сос	соскӧс	N;ACC;SG
копыр	копыр	N;NOM;SG
шпалеритны	шпалеритім	V;PL;1;PST;LGSPEC1
чер	черъяс	N;NOM;PL
портрет	портретъяс	N;NOM;PL;LGSPEC1
комендант	комендант	N;HUM;NOM;SG;LGSPEC1
нювны	нювны	V;NFIN
юсь	юсьлӧн	N;HUM;GEN;SG
туны	тусьла	V;SG;1;PRS;PASS;LGSPEC_DELIM
конкуренция	конкуренциясӧ	N;ACC;SG;PSS3S;LGSPEC1
бӧртас	бӧртасъяссӧ	N;ACC;PL;PSS3S
кылавны	кылавліс	V;SG;3;PST;LGSPEC_DELIM
пук	пуктӧ	N;ACC;SG;PSS2S;LGSPEC1
кывбур	кывбуръясным	N;NOM;PL;PSS1P
пасйыны	пасъянныд	V;PL;2;FUT
письтны	письт	V;IMP;SG;2
книга	книгаясад	N;IN+ALL;PL;PSS2S;LGSPEC1
тшак	тшакыд	N;NOM;SG;PSS2S
ангел	ангел	N;NOM;SG;LGSPEC1
мыччавны	мыччӧдласны	V;PL;3;FUT;CAUS;LGSPEC_DELIM
тшупӧда	тшупӧдаяс	ADJ;NOM;PL
кыс	кыс	N;NOM;SG
чолӧмавны	чолӧмась	V;SG;NEG;PASS
сгущёнка	сгущёнка	N;NOM;SG;LGSPEC1
сикт	сиктӧс	N;ACC;SG;PSS1S
ӧтлаӧдӧм	ӧтлаӧдӧмысь	N;IN+ABL;SG
приём	приёмъясӧн	N;INS;PL;LGSPEC1
удзавны	удзав	V;SG;NEG
нажӧвитны	нажӧвитӧй	V;IMP;PL;2;LGSPEC1
старейшина	старейшинаяслы	N;HUM;DAT;PL;LGSPEC1
заводитны	заводит	V;SG;NEG;LGSPEC1
рейс	рейсъясыс	N;NOM;PL;PSS3S;LGSPEC1
рифма	рифматӧм	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
кутны	кутла	V;SG;1;FUT;LGSPEC_DELIM
шойччыны	шойччим	V;PL;1;PST
сикт	сиктсаяс	N;NOM;PL;LGSPEC_ATTR
ӧтлаӧдӧм	ӧтлаӧдӧмыс	N;NOM;SG;PSS3S
телеканал	телеканал	N;NOM;SG;LGSPEC1
бизнес	бизнесад	N;IN+ESS;SG;PSS2S;LGSPEC1
олысь	олысьясыд	N;HUM;NOM;PL;PSS2S
пинявны	пинявны	V;NFIN
шенны	шеныштны	V;PL;2;NEG;LGSPEC_ATTEN
бомба	бомбаяс	N;NOM;PL;LGSPEC1
теш	тешъяснас	N;INS;PL;PSS3S;LGSPEC1
мам	мамыс	N;HUM;NOM;SG;PSS3S
вом	вомнад	N;INS;SG;PSS2S
няклявны	някляліс	V;SG;3;PST
сгущёнка	сгущёнканас	N;INS;SG;PSS3S;LGSPEC1
анализируйтӧм	анализируйтӧмӧ	N;IN+ALL;SG;LGSPEC1
кылавны	кылӧдліс	V;SG;3;PST;CAUS;LGSPEC_DELIM
билет	билетсьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
включитны	включитіс	V;SG;3;PST;LGSPEC1
пенсия	пенсияыдлӧн	N;GEN;SG;PSS2S;LGSPEC1
эштыны	эштӧдӧй	V;IMP;PL;2;CAUS
кокньӧдны	кокньӧдыштны	V;PL;2;NEG;LGSPEC_ATTEN
инны	ин	V;SG;NEG
ход	ходӧн	N;INS;SG;LGSPEC1
пӧлявны	пӧляв	V;IMP;SG;2
лекарство	лекарствоыс	N;NOM;SG;PSS3S;LGSPEC1
муртавны	муртавны	V;PL;2;NEG
вайӧдӧм	вайӧдӧмыс	N;NOM;SG;PSS3S
краситны	краситам	V;PL;1;PRS;LGSPEC1
кӧк	коктӧ	N;HUM;ACC;SG;PSS2S
кыйысь	кыйысьӧс	N;HUM;ACC;SG;PSS1S
кытш	кытшсӧ	N;ACC;SG;PSS3S
зон	зонмысь	N;HUM;IN+ABL;SG
тусь	тусьяслысь	N;ABL;PL
финиш	финишӧдзыс	N;TERM;SG;PSS3S;LGSPEC1
тӧвны	тӧлӧдӧй	V;PL;1;NEG;CAUS
препарат	препаратъясӧс	N;ACC;PL;LGSPEC1
кампужитчыны	кампужитчыны	V;NFIN;LGSPEC1
кӧк	кокад	N;HUM;IN+ESS;SG;PSS2S
лямпа	лямпаястӧг	N;PL;LGSPEC_CAR
нар	нарын	N;IN+ESS;SG;LGSPEC1
оборудование	оборудованиеысь	N;IN+ABL;SG;LGSPEC1
пинявны	пинясисны	V;PL;3;PST;PASS
интерес	интересысь	N;IN+ABL;SG;LGSPEC1
висьлыны	висьлы	V;SG;NEG
ыркнитны	ыркнитіс	V;SG;3;PST;IMPRS
кульны	кулясны	V;PL;3;FUT
юмореска	юморескаӧс	N;ACC;SG;LGSPEC1
мам	мамӧс	N;HUM;ACC;SG;PSS1S
сотовӧй	сотовӧйӧ	ADJ;NOM;SG;PSS1S;LGSPEC1
вом	воманыс	N;IN+ESS;SG;PSS3P
взнос	взноссӧ	N;ACC;SG;PSS3S;LGSPEC1
петны	петам	V;PL;1;PRS
петны	петлӧй	V;IMP;PL;2;LGSPEC_DELIM
командир	командирлысь	N;HUM;ABL;SG;LGSPEC1
петны	петкӧдалісны	V;ITER;PL;3;PST;CAUS
керка-карта	керка-картаыд	N;NOM;SG;PSS2S
косявны	косялас	V;SG;3;FUT
тіравны	тірала	V;SG;1;PRS
лӧсьны	лӧсьӧдыштӧ	V;SG;3;PRS;CAUS;LGSPEC_ATTEN
петны	петкӧдчылі	V;SG;1;PST;CAUS;PASS;LGSPEC_DELIM
эштыны	эштыны	V;NFIN
ӧддзыны	ӧддзывлін	V;SG;2;PST;LGSPEC_DELIM
няргыны	нярга	V;SG;1;PRS
петны	петкӧдчыла	V;SG;1;PRS;CAUS;PASS;LGSPEC_DELIM
сюйсьыны	сюйсясны	V;PL;3;FUT
дивуйтчыны	дивуйтча	V;SG;1;FUT;LGSPEC1
сваритны	сваритчыны	V;PL;2;NEG;PASS;LGSPEC1
акция	акцияын	N;IN+ESS;SG;LGSPEC1
овмӧс	овмӧсъясысь	N;IN+ABL;PL
гынкӧмасьны	гынкӧмаси	V;SG;1;PST
портрет	портретъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
асныра	асныраыд	ADJ;NOM;SG;PSS2S
лэптыны	лэптыны	V;NFIN;TR
вины	виан	V;SG;2;FUT
казьтыштӧм	казьтыштӧм	N;NOM;SG
пыксьыны	пыксям	V;PL;1;PRS
номер	номерӧ	N;IN+ALL;SG;LGSPEC1
кывкутысь	кывкутысьыс	ADJ;NOM;SG;PSS3S
командир	командирлӧн	N;HUM;GEN;SG;LGSPEC1
объяснитны	объяснитчы	V;SG;NEG;PASS;LGSPEC1
вӧшны	вошлӧны	V;PL;3;PRS;LGSPEC_DELIM
кывбур	кывбуръяслы	N;DAT;PL
косявны	косяв	V;IMP;SG;2
веськавны	веськалам	V;PL;1;FUT
командир	командиръяс	N;HUM;NOM;PL;LGSPEC1
турник	турникъяс	N;NOM;PL;LGSPEC1
палявны	пальӧдчӧмыд	V;SG;2;PST;CAUS;PASS
госпиталь	госпитальясӧ	N;IN+ALL;PL;LGSPEC1
ӧтка	ӧткаыс	ADJ;NOM;SG;PSS3S
мыждыны	мыждысь	V;SG;NEG;PASS
нар	народ	N;PROL;SG;LGSPEC1
челядьдыр	челядьдырас	N;IN+ESS;SG;PSS3S;LGSPEC1
коньӧр	коньӧръясыд	N;HUM;NOM;PL;PSS2S
ордйысьысь	ордйысьысьяслӧн	ADJ;GEN;PL
кужысь	кужысь	ADJ;NOM;SG
пӧчӧ	пӧчӧлӧн	N;HUM;GEN;SG
пӧрт	пӧртйӧдз	N;TERM;SG
рӧмдыны	рӧмдан	V;SG;2;PRS
фонд	фондъясӧс	N;ACC;PL;LGSPEC1
юсь	юсьӧс	N;HUM;ACC;SG;PSS1S
ӧвны	олӧмаджык	V;COMPV;SG;3;PST
университет	университетад	N;IN+ESS;SG;PSS2S;LGSPEC1
архитектура	архитектуралысь	N;ABL;SG;LGSPEC1
пастук	пастукӧс	N;HUM;ACC;SG
письтны	письтлі	V;SG;3;PST;LGSPEC_DELIM
видеоролик	видеороликъяслӧн	N;GEN;PL;LGSPEC1
оборудование	оборудованиеӧ	N;NOM;SG;PSS1S;LGSPEC1
вӧйны	войлӧны	V;PL;3;PRS;LGSPEC_DELIM
суседко	суседкоӧс	N;ACC;SG;PSS1S;LGSPEC1
пуд	пудлы	N;DAT;SG;LGSPEC1
ёкмыльтны	ёкмыльтчӧй	V;PL;2;NEG;PASS
спикер	спикерӧс	N;HUM;ACC;SG;PSS1S;LGSPEC1
зырны	зыра	V;SG;1;PRS
уджалӧм	уджалӧм	N;NOM;SG
пӧчӧ	пӧчӧӧс	N;HUM;ACC;SG
йӧлӧга	йӧлӧгакӧд	N;COM;SG
кролик	кролик	N;HUM;NOM;SG;LGSPEC1
ӧбедайтны	ӧбедайті	V;SG;1;PST;LGSPEC1
йывмыны	йывмыны	V;PL;2;NEG
гор	горъяс	N;NOM;PL
косявны	косясь	V;SG;NEG;PASS
шемӧсмунны	шемӧсмунлі	V;SG;1;PST;LGSPEC_DELIM
зільны	зільыштны	V;PL;2;NEG;LGSPEC_ATTEN
ыджыдавны	ыджыдалас	V;SG;3;FUT
гусялӧм	гусялӧмъяс	N;NOM;PL
шобны	шобӧмаӧсь	V;PL;3;PST
фронт	фронтлы	N;DAT;SG;LGSPEC1
петны	петкӧдчӧй	V;IMP;PL;2;CAUS;PASS
уджалӧм	уджалӧмӧс	N;ACC;SG;PSS1S
кутны	куті	V;SG;1;PST
шойччыны	шойччанныд	V;PL;2;FUT
веськыд	веськыдӧн	ADJ;INS;SG
веськавны	веськӧдчин	V;SG;2;PST;CAUS;PASS
пинявны	пинясьла	V;SG;1;PRS;PASS;LGSPEC_DELIM
йывмыны	йывмы	V;IMP;SG;2
туны	тусьла	V;SG;1;FUT;PASS;LGSPEC_DELIM
велӧдӧм	велӧдӧмыд	N;NOM;SG;PSS2S
уль	ульджык	ADJ;NOM+COMPV;SG
зон	зонсӧ	N;HUM;ACC;SG;PSS3S
качество	качестволы	N;DAT;SG;LGSPEC1
офис	офисыс	N;NOM;SG;PSS3S;LGSPEC1
туны	тулӧ	V;SG;3;PRS;LGSPEC_DELIM
веськавны	веськалі	V;SG;1;PST
юр	юръясӧдыс	N;PROL;PL;PSS3S
ход	ход	N;NOM;SG;LGSPEC1
арӧс	арӧсъясӧдз	N;TERM;PL
ӧтлаӧдӧм	ӧтлаӧдӧм	N;NOM;SG
сикт	сиктсаяскӧд	N;COM;PL;LGSPEC_ATTR
петны	петкӧд	V;SG;NEG;CAUS
теш	тешъяс	N;NOM;PL;LGSPEC1
зільны	зільны	V;NFIN
сакны	сакны	V;NFIN
восстание	восстание	N;NOM;SG;LGSPEC1
грымӧбтыны	грымӧбтыны	V;NFIN
командир	командирным	N;HUM;NOM;SG;PSS1P;LGSPEC1
вуг	вуг	N;NOM;SG
юсь	юсьӧ	N;HUM;IN+ALL;SG
вайӧдӧм	вайӧдӧмкӧд	N;COM;SG
весьт	весьтса	N;NOM;SG;LGSPEC_ATTR
кывбур	кывбуръясысь	N;IN+ABL;PL
видзӧм	видзӧмӧ	N;NOM;SG;PSS1S
ыстӧм	ыстӧм	N;NOM;SG
гымӧбтыны	гымӧбта	V;SG;1;FUT
шӧркодь	шӧркодьӧс	ADJ;ACC;SG
песны	песі	V;SG;1;PST
лӧсьны	лӧсьӧдлам	V;PL;1;FUT;CAUS;LGSPEC_DELIM
пешны	пеша	V;SG;1;PRS
веськыд	веськыдыс	ADJ;NOM;SG;PSS3S
горув	горув	N;NOM;SG;LGSPEC1
бӧртас	бӧртассӧ	N;ACC;SG;PSS3S
доктор	докторъяс	N;HUM;NOM;PL;LGSPEC1
гармонист	гармонистъяс	N;HUM;NOM;PL;LGSPEC1
бӧртас	бӧртасӧдз	N;TERM;SG
карандаш	карандашӧс	N;ACC;SG;LGSPEC1
вӧчасьысь	вӧчасьысьяслы	N;HUM;DAT;PL
кырны	кырӧд	V;IMP;SG;2;CAUS
шковгыны	шковгӧ	V;SG;3;PRS;INTR
берег	берегъяснас	N;INS;PL;PSS3S;LGSPEC1
кутны	кутӧд	V;IMP;SG;2;CAUS
ордйысьысь	ордйысьысьяс	ADJ;NOM;PL
веськавны	веськавлӧ	V;SG;3;PRS;LGSPEC_DELIM
сёян-юан	сёян-юанлы	N;DAT;SG
кытш	кытш	N;NOM;SG
правилӧ	правилӧястӧг	N;PL;LGSPEC_CAREXT
шойччыны	шойччӧдас	V;SG;3;FUT;CAUS
сакар	сакар	N;NOM;SG;LGSPEC1
отпуск	отпускыд	N;NOM;SG;PSS2S;LGSPEC1
чолӧмавны	чолӧмасьӧ	V;SG;3;PRS;PASS
удзавны	удзӧд	V;IMP;SG;2;CAUS
ойбыртны	ойбыртлі	V;SG;3;PST;LGSPEC_DELIM
юксьыны	юксьылі	V;SG;1;PST;LGSPEC_DELIM
юксьыны	юксясны	V;PL;3;FUT
либерал	либералъясысь	N;HUM;IN+ABL;PL;LGSPEC1
источник	источник	N;NOM;SG;LGSPEC1
нажӧвитны	нажӧвит	V;IMP;SG;2;LGSPEC1
веськавны	веськӧдчылӧны	V;PL;3;PRS;CAUS;PASS;LGSPEC_DELIM
стрӧчка	строчкасӧ	N;ACC;SG;PSS3S;LGSPEC1
интеллигенция	интеллигенциялӧн	N;GEN;SG;LGSPEC1
структура	структураяс	N;NOM;PL;LGSPEC1
вӧйны	вӧйӧма	V;SG;3;PST
гымӧбтыны	гымӧбта	V;SG;1;PRS
зэк	зэк	N;HUM;NOM;SG;LGSPEC1
жӧник	жӧникным	N;HUM;NOM;SG;PSS1P;LGSPEC1
нырис	ныриссӧ	N;ACC;SG;PSS3S
веськавны	веськавлінныд	V;PL;2;PST;LGSPEC_DELIM
веськавны	веськӧдышті	V;SG;3;PST;CAUS;LGSPEC_ATTEN
куд	кудйӧ	N;IN+ALL;SG
ыдждавны	ыдждӧдла	V;SG;1;PRS;CAUS;LGSPEC_DELIM
пӧрӧдчысь	пӧрӧдчысь	N;HUM;NOM;SG
кежласьны	кежласянныд	V;PL;2;PRS
бланк	бланксӧ	N;ACC;SG;PSS3S;LGSPEC1
видео	видеоас	N;IN+ESS;SG;PSS3S;LGSPEC1
ӧвны	олыштам	V;PL;1;PRS;LGSPEC_ATTEN
палявны	палялін	V;SG;2;PST
значок	значоксӧ	N;ACC;SG;PSS3S;LGSPEC1
зал	залӧн	N;INS;SG;LGSPEC1
вӧшны	вошсьыны	V;NFIN;PASS
удача	удача	N;NOM;SG;LGSPEC1
лямпа	лямпатӧг	N;SG;LGSPEC_CAR
мам	мамъяслы	N;HUM;DAT;PL
веськавны	веськӧдчыны	V;NFIN;CAUS;PASS
кластер	кластерӧ	N;IN+ALL;SG;LGSPEC1
федерация	федерацияын	N;IN+ESS;SG;LGSPEC1
пастукавны	пастукалан	V;SG;2;FUT;LGSPEC1
пинявны	пинялім	V;PL;1;PST
университет	университетӧс	N;ACC;SG;LGSPEC1
книга	книгаӧс	N;ACC;SG;LGSPEC1
магистраль	магистральсӧ	N;ACC;SG;PSS3S;LGSPEC1
заявка	заявка	N;NOM;SG;LGSPEC1
кывбур	кывбуръяс	N;NOM;PL
шӧравны	шӧрасисны	V;PL;3;PST;PASS
пӧлать	пӧлатьысь	N;IN+ABL;SG;LGSPEC1
армия	армияын	N;IN+ESS;SG;LGSPEC1
победа	победаыслысь	N;ABL;SG;PSS3S;LGSPEC1
петны	петкӧдлінныд	V;PL;2;PST;CAUS;LGSPEC_DELIM
чаг	чагъяс	N;NOM;PL
тусь	тусьяс	N;NOM;PL
эрдавны	эрдӧдӧны	V;PL;3;PRS;CAUS
парашют	парашютыд	N;NOM;SG;PSS2S;LGSPEC1
креслӧ	креслӧ	N;NOM;SG;LGSPEC1
визувтны	визувтӧ	V;SG;3;PRS
брезент	брезент	N;NOM;SG;LGSPEC1
правилӧ	правилӧясыс	N;NOM;PL;PSS3S;LGSPEC1
вритны	врит	V;SG;NEG;LGSPEC1
партизан	партизанъяслӧн	N;HUM;GEN;PL;LGSPEC1
лягуша	лягушаястӧ	N;HUM;ACC;PL;PSS2S;LGSPEC1
кывбур	кывбуръяснад	N;INS;PL;PSS2S
вӧшны	вошан	V;SG;2;PRS
пуксьӧм	пуксьӧмыс	N;NOM;SG;PSS3S
жугыльтны	жугыльт	V;IMP;SG;2
композиция	композицияыс	N;NOM;SG;PSS3S;LGSPEC1
вожавны	вожавлывліс	V;SG;3;PST;LGSPEC_DELIM
кульны	куля	V;SG;1;FUT
сюйсьыны	сюйсьӧ	V;SG;3;PRS
кылавны	кылалан	V;SG;2;PRS
пенал	пеналӧ	N;IN+ALL;SG;LGSPEC1
пеславны	песласьӧ	V;SG;3;PRS;PASS
пират	пиратъясӧ	N;HUM;IN+ALL;PL;LGSPEC1
тшӧка	тшӧкаясыс	N;NOM;PL;PSS3S
регулируйтны	регулируйтӧ	V;SG;3;PRS;LGSPEC1
ошйысьны	ошйысьышт	V;SG;NEG;LGSPEC_ATTEN
плита	плитасӧ	N;ACC;SG;PSS3S;LGSPEC1
военкомат	военкоматад	N;IN+ESS;SG;PSS2S;LGSPEC1
велӧдчысь	велӧдчысьяс	N;HUM;NOM;PL
оператор	операторса	N;HUM;NOM;SG;LGSPEC_ATTR;LGSPEC1
жугавны	жугӧдліс	V;SG;3;PST;CAUS;LGSPEC_DELIM
веськавны	веськӧдчӧ	V;SG;3;PRS;CAUS;PASS
шыд	шыдӧс	N;ACC;SG
госпиталь	госпитальсянь	N;SG;LGSPEC_EGREXT
джудждыны	джудждӧдан	V;SG;2;PRS;CAUS
пенсия	пенсияным	N;NOM;SG;PSS1P;LGSPEC1
рака	рака	N;HUM;NOM;SG
веськавны	веськав	V;SG;NEG
кролик	кроликъясӧс	N;HUM;ACC;PL;PSS1S;LGSPEC1
сины	сиинныд	V;PL;2;PST
отравитны	отравитчыны	V;PL;2;NEG;PASS;LGSPEC1
юр	юрысь	N;IN+ABL;SG
гажтӧмавны	гажтӧмаліс	V;SG;3;PST
берег	береглӧн	N;GEN;SG;LGSPEC1
кагук	кагукныс	N;HUM;NOM;SG;PSS3P
аспирант	аспирантъяс	N;HUM;NOM;PL;LGSPEC1
жугавны	жугалӧны	V;PL;3;PRS
вӧйны	войӧй	V;IMP;PL;2
ыпъявны	ыпъялӧ	V;SG;3;PRS
дача	дачаысь	N;IN+ABL;SG;LGSPEC1
мыччавны	мыччасьӧ	V;SG;3;PRS;PASS
вины	висьӧны	V;PL;3;PRS;PASS
ойӧс	ойӧстӧмӧн	N;INS;SG;LGSPEC_ATTR
кутны	кутасны	V;PL;3;FUT
туялысь	туялысьӧс	N;HUM;ACC;SG;PSS1S
военкомат	военкоматлӧн	N;GEN;SG;LGSPEC1
жугавны	жугӧдны	V;NFIN;CAUS
скважина	скважинасянь	N;SG;LGSPEC_EGREXT
ошйысьны	ошйысям	V;PL;1;FUT
падей	падейясӧн	N;INS;PL
рейс	рейсъясысь	N;IN+ABL;PL;LGSPEC1
сёян-юан	сёян-юан	N;NOM;SG
юксьыны	юксян	V;SG;2;FUT
лӧсьны	лӧсьӧдыштны	V;PL;2;NEG;CAUS;LGSPEC_ATTEN
кырны	кыр	V;SG;NEG
руч	ручьяс	N;HUM;NOM;PL
овмӧс	овмӧсысь	N;IN+ABL;SG
пастук	пастукыслы	N;HUM;DAT;SG;PSS3S
дивитны	дивитнысӧ	V;ACC;NFIN;PSS3S
гу	гуясӧ	N;NOM;PL;PSS1S
нажӧвитны	нажӧвитӧ	V;SG;3;PRS;LGSPEC1
ӧтка	ӧтканас	ADJ;INS;SG;PSS3S
олысь	олысьсӧ	N;HUM;ACC;SG;PSS3S
ошйысьны	ошйысьнысӧ	V;ACC;NFIN;PSS3S
рӧшкыд	рӧшкыд	ADJ;NOM;SG
акция	акцияӧн	N;INS;SG;LGSPEC1
бизнес	бизнесас	N;IN+ESS;SG;PSS3S;LGSPEC1
мыждыны	мыждӧ	V;SG;3;PRS
гӧг	гӧг	N;NOM;SG
олысь	олысьтӧгыд	N;HUM;SG;PSS2S;LGSPEC_CAR
чер	черӧс	N;ACC;SG;PSS1S
вермысь	вермысьыс	N;HUM;NOM;SG;PSS3S
сикт	сиктсаясӧс	N;ACC;PL;LGSPEC_ATTR
торкны	торксинныд	V;PL;2;PST;PASS
кыйысь	кыйысьясӧн	N;HUM;INS;PL
кутны	кутлӧ	V;SG;3;PRS;LGSPEC_DELIM
сандали	сандалиӧн	N;INS;SG;LGSPEC1
монтёр	монтёр	N;HUM;NOM;SG;LGSPEC1
доймӧм	доймӧмӧс	N;ACC;SG
завӧдитны	заводитчас	V;SG;3;FUT;PASS;LGSPEC1
шойччыны	шойччыштан	V;SG;2;FUT;LGSPEC_ATTEN
фонд	фондъясын	N;IN+ESS;PL;LGSPEC1
старейшина	старейшинаяслысь	N;HUM;ABL;PL;LGSPEC1
рӧмпӧштан	рӧмпӧштанлы	N;DAT;SG
холодильник	холодильникас	N;IN+ESS;SG;PSS3S;LGSPEC1
тырны	тырим	V;PL;1;PST
шыд	шыдтӧ	N;ACC;SG;PSS2S
бунтуйтны	бунтуйтӧны	V;PL;3;PRS;LGSPEC1
дивитны	дивитӧй	V;PL;1;NEG
ӧтар	ӧтарӧ	N;NOM;SG;PSS1S
вурун	вурунсӧ	N;ACC;SG;PSS3S
лӧсьны	лӧсьӧданныд	V;PL;2;FUT;CAUS
пасйыны	пасйылӧны	V;PL;3;PRS;LGSPEC_DELIM
ӧзтавны	ӧзтав	V;IMP;SG;2
велӧдчысь	велӧдчысьыс	N;HUM;NOM;SG;PSS3S
гургыны	гургыны	V;PL;2;NEG
сім	сімӧн	N;INS;SG
ног	ногджык	N;NOM+COMPV;SG
кутны	кутӧда	V;SG;1;PRS;CAUS
сувенир	сувениръяс	N;NOM;PL;LGSPEC1
мамӧ	мамӧлы	N;HUM;DAT;SG
ойбыртны	ойбыртан	V;SG;2;PRS
велӧдчысь	велӧдчысьясыд	N;HUM;NOM;PL;PSS2S
буксан	буксанъяс	N;NOM;PL
кавшасьны	кавшасян	V;SG;2;PRS
велӧдӧм	велӧдӧмӧ	N;NOM;SG;PSS1S
гымӧбтыны	гымӧбтыны	V;NFIN
весьт	весьтаныд	N;IN+ESS;SG;PSS2P
суседко	суседколы	N;DAT;SG;LGSPEC1
кывбур	кывбуръясад	N;IN+ALL;PL;PSS2S
тэрмасьысь	тэрмасьысь	ADJ;NOM;SG
отряд	отряднас	N;INS;SG;PSS3S;LGSPEC1
няйтӧсьтны	няйтӧсьтам	V;PL;1;FUT
тапсьӧдны	тапсьӧда	V;SG;1;FUT
велосипед	велосипедъяс	N;NOM;PL;LGSPEC1
веськавны	веськӧдчим	V;PL;1;PST;CAUS;PASS
тема	темаясӧн	N;INS;PL;LGSPEC1
юр	юрӧн	N;INS;SG
шойччыны	шойччӧдны	V;PL;2;NEG;CAUS
катовмунны	катовмунӧ	V;SG;3;PRS
кыскӧд	кыскӧдъяс	N;HUM;NOM;PL
отряд	отрядлӧн	N;GEN;SG;LGSPEC1
тури	турияслы	N;HUM;DAT;PL
веськавны	веськалӧй	V;IMP;PL;2
вӧшны	вошан	V;SG;2;FUT
гыа	гыалысь	ADJ;ABL;SG
велосипед	велосипедыс	N;NOM;SG;PSS3S;LGSPEC1
гыжъя	гыжъяла	N;HUM;SG;LGSPEC_CNS
зӧркавны	зӧркӧдчыны	V;NFIN;CAUS;PASS
ӧддзыны	ӧддзылім	V;PL;1;PST;LGSPEC_DELIM
экскурсия	экскурсиясянь	N;SG;LGSPEC_EGREXT
кольцо	кольцояс	N;NOM;PL;LGSPEC1
вины	висьлӧй	V;PL;2;NEG;PASS;LGSPEC_DELIM
ӧбӧдитны	ӧбӧдит	V;SG;NEG;LGSPEC1
шӧр	шоръяслӧн	N;GEN;PL
ветлысь-мунысь	ветлысь-мунысьӧн	N;HUM;INS;SG
петны	петнысӧ	V;ACC;NFIN;PSS3S
йӧжгылясьны	йӧжгылясьӧй	V;IMP;PL;2
кролик	кроликъяслы	N;HUM;DAT;PL;LGSPEC1
тусь	тусьлӧн	N;GEN;SG
лукйыны	лукйӧны	V;PL;3;PRS
гу	гуясас	N;IN+ESS;PL;PSS3S
участвуйтны	участвуйті	V;SG;1;PST;LGSPEC1
йитӧд	йитӧдъяслӧн	N;GEN;PL
панно	панно	N;NOM;SG;LGSPEC1
веськавны	веськӧдыштны	V;NFIN;CAUS;LGSPEC_ATTEN
сулея	сулеяысь	N;IN+ABL;SG;LGSPEC1
правилӧ	правилӧнас	N;INS;SG;PSS3S;LGSPEC1
отряд	отрядъяслысь	N;ABL;PL;LGSPEC1
палявны	палявлан	V;SG;2;PRS;LGSPEC_DELIM
средство	средствояскӧд	N;COM;PL;LGSPEC1
велосипед	велосипедӧс	N;ACC;SG;LGSPEC1
весьӧпӧртны	весьӧпӧртінныд	V;PL;2;PST
веськавны	веськалан	V;SG;2;FUT
интерес	интересыс	N;NOM;SG;PSS3S;LGSPEC1
юксьыны	юксьышт	V;SG;NEG;LGSPEC_ATTEN
экзамен	экзаменлысь	N;ABL;SG;LGSPEC1
пеж	пежлысь	N;HUM;ABL;SG
больгыны	больгыштны	V;PL;2;NEG;LGSPEC_ATTEN
волонтёр	волонтёрлысь	N;HUM;ABL;SG;LGSPEC1
композиция	композициялӧн	N;GEN;SG;LGSPEC1
куд	кудлы	N;DAT;SG
кылавны	кылалім	V;PL;1;PST
модератор	модератор	N;HUM;NOM;SG;LGSPEC1
косявны	косясьны	V;PL;2;NEG;PASS
сюйсьыны	сюйсян	V;SG;2;PRS
байдкор	байдкор	N;HUM;NOM;SG
инкубатор	инкубатор	N;NOM;SG;LGSPEC1
нырис	нырис	N;NOM;SG
торкӧм	торкӧмысь	N;IN+ABL;SG
арӧс	арӧсыс	N;NOM;SG;PSS3S
заводитны	заводитан	V;SG;2;PRS;LGSPEC1
абитуриент	абитуриентъясыдлы	N;HUM;DAT;PL;PSS2S;LGSPEC1
сценарий	сценарийсӧ	N;ACC;SG;PSS3S;LGSPEC1
жугыльтны	жугыльтчисны	V;PL;3;PST;PASS
шлангыны	шлангысь	V;SG;NEG;PASS
экзамен	экзаменъяслысь	N;ABL;PL;LGSPEC1
перилӧ	перилӧ	N;NOM;SG;LGSPEC1
чурйӧдлыны	чурйӧдлін	V;SG;2;PST
зон	зонмыслӧн	N;HUM;GEN;SG;PSS3S
шпуткыны	шпуткыны	V;NFIN
мыччавны	мыччӧдлыны	V;PL;2;NEG;CAUS;LGSPEC_DELIM
ӧш	ошкас	N;HUM;IN+ESS;SG;PSS3S
мэрия	мэрияад	N;IN+ALL;SG;PSS2S;LGSPEC1
чушкысь	чушкысьӧ	N;HUM;IN+ALL;SG
ыджыдавны	ыджыдавнысӧ	V;ACC;NFIN;PSS3S
секция	секциясӧ	N;ACC;SG;PSS3S;LGSPEC1
ошкӧм	ошкӧмысь	N;IN+ABL;SG
дивитны	дивитыштны	V;NFIN;LGSPEC_ATTEN
эштыны	эштӧдчанныд	V;PL;2;PRS;CAUS;PASS
ӧтувтны	ӧтувтчӧны	V;PL;3;PRS;PASS
някыртны	някыртлі	V;SG;1;PST;LGSPEC_DELIM
заводитны	заводитас	V;SG;3;FUT;LGSPEC1
берег	берегсянь	N;SG;LGSPEC_EGREXT
вордны	ворд	V;IMP;SG;2
эштыны	эштӧді	V;SG;1;PST;CAUS
детдом	детдомысь	N;IN+ABL;SG;LGSPEC1
прӧдукта	прӧдуктаяс	N;NOM;PL;LGSPEC1
рифма	рифмаясысь	N;IN+ABL;PL;LGSPEC1
гызьыны	гызьылӧ	V;SG;3;PRS;LGSPEC_DELIM
печатайтӧм	печатайтӧмӧн	N;INS;SG;LGSPEC1
юр	юрсянь	N;SG;LGSPEC_EGR
петны	петсис	V;SG;3;PST;PASS
график	графикын	N;IN+ESS;SG;LGSPEC1
петны	петі	V;SG;1;PST
ӧбедайтны	ӧбедайтны	V;NFIN;LGSPEC1
веськавны	веськӧдчи	V;SG;1;PST;CAUS;PASS
скӧт	скӧтӧс	N;HUM;ACC;SG
жугыльтны	жугыльтчин	V;SG;2;PST;PASS
подъезд	подъезданым	N;IN+ALL;SG;PSS1P;LGSPEC1
балалайка	балалайкалысь	N;ABL;SG;LGSPEC1
петны	петкӧдчан	V;SG;2;PRS;CAUS;PASS
пеж	пежкӧд	N;HUM;COM;SG
понимайтны	понимайтан	V;SG;2;PRS;LGSPEC1
ӧтка	ӧткаясӧс	ADJ;ACC;PL
торкны	торксьы	V;SG;NEG;PASS
кутю	кутюяс	N;HUM;NOM;PL
реорганизация	реорганизацияыс	N;NOM;SG;PSS3S;LGSPEC1
сины	сиим	V;PL;1;PST
кывбур	кывбурлӧн	N;GEN;SG
эштыны	эштаджык	V;COMPV;SG;1;PRS
кутны	кутам	V;PL;1;PRS
лӧсьны	лӧсьӧдам	V;PL;1;FUT;CAUS
кутны	кутанныд	V;PL;2;FUT
лэптыны	лэптысь	V;SG;NEG;TR;PASS
мыждыны	мыждӧны	V;PL;3;PRS
ӧтка	ӧткаяс	ADJ;NOM;PL
шойччыны	шойччӧмыд	V;SG;2;PST
кабала	кабалатӧ	N;ACC;SG;PSS2S;LGSPEC1
шойччыны	шойччылӧ	V;SG;3;PRS;LGSPEC_DELIM
реорганизация	реорганизацияӧн	N;INS;SG;LGSPEC1
виччысьтӧм	виччысьтӧмысла	N;SG;PSS3S;LGSPEC_CNS
еджыд	еджыдъяс	N;NOM;PL
кыйны	кыйся	V;SG;1;PRS;PASS
субъект	субъектъясӧс	N;ACC;PL;PSS1S;LGSPEC1
важ	важыслӧн	ADJ;GEN;SG;PSS3S
патриотизм	патриотизмсӧ	N;ACC;SG;PSS3S;LGSPEC1
велӧдчысь	велӧдчысьясыс	N;HUM;NOM;PL;PSS3S
зон	зонмыслысь	N;HUM;ABL;SG;PSS3S
бомба	бомбанад	N;INS;SG;PSS2S;LGSPEC1
нюжгысьны	нюжгысьны	V;PL;2;NEG
сайт	сайтӧн	N;INS;SG;LGSPEC1
велӧдӧм	велӧдӧмсянь	N;SG;LGSPEC_EGR
кокньӧдны	кокньӧдчыны	V;PL;2;NEG;PASS
лотны	лота	V;SG;1;FUT
амнистия	амнистиясӧ	N;ACC;SG;PSS3S;LGSPEC1
шӧр	шорӧн	N;INS;SG
преподаватель	преподавательӧс	N;HUM;ACC;SG;PSS1S;LGSPEC1
пӧртӧм	пӧртӧмсянь	N;SG;LGSPEC_EGR
нажӧвитны	нажӧвитӧй	V;PL;1;NEG;LGSPEC1
джӧмдыны	джӧмдыны	V;NFIN
победа	победаӧдз	N;TERM;SG;LGSPEC1
повестка	повестка	N;NOM;SG;LGSPEC1
вӧчӧдӧм	вӧчӧдӧмкӧд	N;COM;SG
ног	ногысь	N;IN+ABL;SG
рӧмдыны	рӧмдыштӧ	V;SG;3;PRS;LGSPEC_ATTEN
прӧмыс	прӧмыссӧ	N;ACC;SG;PSS3S;LGSPEC1
медаль	медальсӧ	N;ACC;SG;PSS3S;LGSPEC1
инновация	инновацияяслӧн	N;GEN;PL;LGSPEC1
кутны	кутыштам	V;PL;1;FUT;LGSPEC_ATTEN
тшак	тшактӧгыд	N;SG;PSS2S;LGSPEC_CAR
сериал	сериалъясысь	N;IN+ABL;PL;LGSPEC1
рейс	рейсӧ	N;IN+ALL;SG;LGSPEC1
шыӧдчысь	шыӧдчысьыс	ADJ;NOM;SG;PSS3S
резидент	резидентъясӧс	N;HUM;ACC;PL;LGSPEC1
довъявны	довъялін	V;SG;2;PST
кынмӧм	кынмӧмысла	N;SG;PSS3S;LGSPEC_CNS
идравны	идралі	V;SG;1;PST
пеславны	песлалӧны	V;PL;3;PRS
книга	книгаӧс	N;ACC;SG;PSS1S;LGSPEC1
иналӧм	иналӧмнас	N;INS;SG;PSS3S
дӧлавны	дӧлавны	V;PL;2;NEG
розьӧдны	розьӧдлӧма	V;SG;3;PST;LGSPEC_DELIM
ойбыртны	ойбыртлам	V;PL;1;FUT;LGSPEC_DELIM
ямщик	ямщикъяс	N;HUM;NOM;PL;LGSPEC1
кампания	кампанияяссӧ	N;ACC;PL;PSS3S;LGSPEC1
шобны	шобӧй	V;IMP;PL;2
видеоролик	видеороликысь	N;IN+ABL;SG;LGSPEC1
ыліса	ылісаас	ADJ;IN+ALL;SG;PSS3S
таитны	таит	V;IMP;SG;2;LGSPEC1
юр	юрам	N;IN+ALL;SG;PSS1S
инны	инӧ	V;SG;3;PRS
затон	затонӧ	N;IN+ALL;SG;LGSPEC1
сісьтыны	сісьты	V;SG;NEG
вӧйтавны	войтӧдӧны	V;PL;3;PRS;CAUS
лӧсьӧдлӧм	лӧсьӧдлӧм	N;NOM;SG
кыскысь	кыскысьыс	ADJ;NOM;SG;PSS3S
ног	ноглысь	N;ABL;SG
веськавны	веськӧдӧ	V;SG;3;PRS;CAUS
весьт	весьтъясын	N;IN+ESS;PL
кислород	кислород	N;NOM;SG;LGSPEC1
петны	петкӧдлан	V;SG;2;PRS;CAUS;LGSPEC_DELIM
МВД	мвд-лӧн	N;GEN;SG;LGSPEC1
тырны	тырны	V;PL;2;NEG
сельсӧвет	сельсӧвет	N;NOM;SG;LGSPEC1
номер	номерлы	N;DAT;SG;LGSPEC1
быравлыны	быравлы	V;SG;NEG
пӧчӧ	пӧчӧ	N;HUM;NOM;SG
ёрны	ёр	V;IMP;SG;2
билет	билетысь	N;IN+ABL;SG;LGSPEC1
вины	виам	V;PL;1;PRS
овмӧс	овмӧсын	N;IN+ESS;SG
варгыны	варги	V;SG;1;PST
кыйысь	кыйысьяс	N;HUM;NOM;PL
туялысь	туялысьясыд	N;HUM;NOM;PL;PSS2S
ыджыдавны	ыджыдавны	V;NFIN
метро	метроӧн	N;INS;SG;LGSPEC1
морт	мортысь	N;HUM;IN+ABL;SG
йирсьыны	йирсьыны	V;NFIN
бастион	бастионсянь	N;SG;LGSPEC_EGREXT
рытйыны	рытъя	V;SG;1;FUT
кутны	кутла	V;SG;1;PRS;LGSPEC_DELIM
управа	управа	N;NOM;SG;LGSPEC1
зал	залъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
комбинат	комбинатын	N;IN+ESS;SG;LGSPEC1
пӧрт	пӧрттӧмысь	N;IN+ABL;SG;LGSPEC_ATTR
дача	дачаясӧ	N;NOM;PL;PSS1S;LGSPEC1
гын	гын	N;NOM;SG
аэродром	аэродромысь	N;IN+ABL;SG;LGSPEC1
йитӧд	йитодкӧд	N;COM;SG
базар	базар	N;NOM;SG;LGSPEC1
рудзӧг	рудзӧгыд	N;NOM;SG;PSS2S
нация	нациялӧн	N;GEN;SG;LGSPEC1
уджсикас	уджсикасъяссянь	N;PL;LGSPEC_EGR
теш	тешысь	N;IN+ABL;SG;LGSPEC1
овмӧдчӧм	овмӧдчӧмсянь	N;SG;LGSPEC_EGR
кӧк	кокным	N;HUM;NOM;SG;PSS1P
поликлиника	поликлиникаӧ	N;NOM;SG;PSS1S;LGSPEC1
радлыны	радлас	V;SG;3;FUT;LGSPEC1
юр	юртӧг	N;SG;LGSPEC_CAR
депозит	депозитъясӧ	N;IN+ALL;PL;LGSPEC1
нартитысь	нартитысь	ADJ;NOM;SG
весьт	весьтысь	N;IN+ABL;SG
книга	книгаясыс	N;NOM;PL;PSS3S;LGSPEC1
веськавны	веськӧдлӧны	V;PL;3;PRS;CAUS;LGSPEC_DELIM
национализм	национализмысь	N;IN+ABL;SG;LGSPEC1
йирсьыны	йирсьӧд	V;SG;NEG;CAUS
тырны	тырсяв	V;ITER;SG;NEG;PASS
парашют	парашютсьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
рамка	рамкаӧ	N;NOM;SG;PSS1S;LGSPEC1
краситны	краситчӧй	V;IMP;PL;2;PASS;LGSPEC1
фонограф	фонографӧн	N;INS;SG;LGSPEC1
скважина	скважинаяс	N;NOM;PL;LGSPEC1
стен	стенлысь	N;ABL;SG;LGSPEC1
инкубатор	инкубаторӧ	N;IN+ALL;SG;LGSPEC1
сьӧлавны	сьӧлалӧ	V;SG;3;PRS
дама	дама	N;HUM;NOM;SG;LGSPEC1
аэродром	аэродромъяс	N;NOM;PL;LGSPEC1
улӧс	улӧс	N;NOM;SG
лэптыны	лэптін	V;SG;2;PST;TR
экзамен	экзаменысь	N;IN+ABL;SG;LGSPEC1
кылавны	кылӧдчыны	V;NFIN;CAUS;PASS
гымньӧв	гымньӧвъяссӧ	N;ACC;PL;PSS3S
гуны	гусялӧй	V;ITER;IMP;PL;2;PASS
латыш	латыш	N;HUM;NOM;SG;LGSPEC1
палявны	пальӧд	V;IMP;SG;2;CAUS
янсавны	янсӧдчыны	V;NFIN;CAUS;PASS
ветлысь-мунысь	ветлысь-мунысьӧс	N;HUM;ACC;SG
кампания	кампанияын	N;IN+ESS;SG;LGSPEC1
шутёвтны	шутёвта	V;SG;1;PRS
приём	приёмсӧ	N;ACC;SG;PSS3S;LGSPEC1
фронт	фронтсалы	N;DAT;SG;LGSPEC_ATTR;LGSPEC1
правилӧ	правилӧяслы	N;DAT;PL;LGSPEC1
сандали	сандалиӧс	N;ACC;SG;LGSPEC1
тырны	тырлӧ	V;SG;3;PRS;LGSPEC_DELIM
песны	пессисны	V;PL;3;PST;PASS
зал	залъясӧ	N;NOM;PL;PSS1S;LGSPEC1
тырны	тырсяласны	V;ITER;PL;3;FUT;PASS
лекарство	лекарство	N;NOM;SG;LGSPEC1
шӧр	шӧртӧ	N;ACC;SG;PSS2S
фонд	фондъясысь	N;IN+ABL;PL;LGSPEC1
субъект	субъектын	N;IN+ESS;SG;LGSPEC1
бунтуйтны	бунтуйтчыны	V;NFIN;PASS;LGSPEC1
поликлиника	поликлиника	N;NOM;SG;LGSPEC1
чай	чайтӧмысь	N;IN+ABL;SG;LGSPEC_ATTR;LGSPEC1
вермысь	вермысьлӧн	N;HUM;GEN;SG
рытйыны	рытъя	V;SG;1;PRS
средство	средствоясӧс	N;ACC;PL;LGSPEC1
революционер	революционеръяс	N;HUM;NOM;PL;LGSPEC1
строка	строкаяс	N;NOM;PL;LGSPEC1
бутылка	бутылкаын	N;IN+ESS;SG;LGSPEC1
ветлысь-мунысь	ветлысь-мунысьяслы	N;HUM;DAT;PL
торкны	торксин	V;SG;2;PST;PASS
ӧбедайтны	ӧбедайтны	V;PL;2;NEG;LGSPEC1
муртавны	мурталӧма	V;SG;3;PST
сикт	сиктӧйлы	N;DAT;SG;PSS1S
книга	книгаӧ	N;IN+ALL;SG;LGSPEC1
ветлысь-мунысь	ветлысь-мунысьсӧ	N;HUM;ACC;SG;PSS3S
овмӧс	овмӧсъясыс	N;NOM;PL;PSS3S
овмӧс	овмӧссянь	N;SG;LGSPEC_EGR
мырсьыны	мырсьыштны	V;PL;2;NEG;LGSPEC_ATTEN
пӧртӧм	пӧртӧмӧн	N;INS;SG
гӧль	гӧльыс	ADJ;NOM;SG;PSS3S;LGSPEC1
янсавны	янсалан	V;SG;2;PRS
виччысьтӧм	виччысьтӧмӧс	N;ACC;SG;PSS1S
кутны	кутанныд	V;PL;2;PRS
гижанног	гижанноглысь	N;ABL;SG
тэрмӧдны	тэрмӧдлісны	V;PL;3;PST;LGSPEC_DELIM
чукӧстны	чукӧстчим	V;PL;1;PST;PASS
армия	армияад	N;IN+ALL;SG;PSS2S;LGSPEC1
шутёвтны	шутёвтін	V;SG;2;PST
торкӧм	торкӧмкӧд	N;COM;SG
тырны	тырсяліс	V;ITER;SG;3;PST;PASS
шыӧдчысь	шыӧдчысьяслӧн	ADJ;GEN;PL
тшак	тшакӧ	N;IN+ALL;SG
елецкӧй	елецкӧйысь	ADJ;IN+ABL;SG;LGSPEC1
предатель	предательястӧ	N;HUM;ACC;PL;PSS2S;LGSPEC1
пӧнар	пӧнаръясӧн	N;INS;PL;LGSPEC1
доймӧм	доймӧм	N;NOM;SG
весьт	весьтӧ	N;NOM;SG;PSS1S
тэрмӧдны	тэрмӧдліс	V;SG;3;PST;LGSPEC_DELIM
выть	вытьӧн	N;INS;SG
гырк	гыркӧн	N;INS;SG
номер	номерным	N;NOM;SG;PSS1P;LGSPEC1
собор	соборыс	N;NOM;SG;PSS3S;LGSPEC1
кывбур	кывбуръяссьыд	N;IN+ABL;PL;PSS2S
тшӧгны	тшӧгӧй	V;PL;1;NEG
кырны	кырыштіс	V;SG;3;PST;LGSPEC_ATTEN
экскаватор	экскаваторса	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
мӧвпсям	мӧвпсямӧ	N;IN+ALL;SG
ёрны	ёр	V;SG;NEG
гӧль	гӧльӧн	ADJ;INS;SG;LGSPEC1
юксьыны	юксьыштан	V;SG;2;FUT;LGSPEC_ATTEN
сім	сімлы	N;DAT;SG
успенньӧ	успенньӧ	N;NOM;SG;LGSPEC1
вом	вомнымӧс	N;ACC;SG;PSS1P
велӧдысь	велӧдысьяслы	N;HUM;DAT;PL
кывбур	кывбуркӧд	N;COM;SG
мам	мамъясӧс	N;HUM;ACC;PL;PSS1S
письтны	письта	V;SG;1;FUT
тырны	тырӧны	V;PL;3;PRS
интерес	интересъяс	N;NOM;PL;LGSPEC1
парашют	парашюттӧг	N;SG;LGSPEC_CAREXT
жулик	жулик	N;HUM;NOM;SG;LGSPEC1
заводитны	заводитчӧны	V;PL;3;PRS;PASS;LGSPEC1
участвуйтны	участвуйтанныд	V;PL;2;FUT;LGSPEC1
мам	мамыдлы	N;HUM;DAT;SG;PSS2S
МВД	мвд-кӧд	N;COM;SG;LGSPEC1
сайт	сайтад	N;IN+ESS;SG;PSS2S;LGSPEC1
шӧриавны	шӧриав	V;IMP;SG;2
бизнес	бизнес	N;NOM;SG;LGSPEC1
сакар	сакартӧм	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
скорӧй	скорӧйӧн	ADJ;INS;SG;LGSPEC1
кватитны	кватитім	V;PL;1;PST;LGSPEC1
дивитны	дивит	V;SG;NEG
общество	обществоас	N;HUM;IN+ALL;SG;PSS3S;LGSPEC1
тема	темаыслысь	N;ABL;SG;PSS3S;LGSPEC1
эштыны	эшты	V;IMP;SG;2
кагук	кагукыдкӧд	N;HUM;COM;SG;PSS2S
гу	гусӧ	N;ACC;SG;PSS3S
парикмахерскӧй	парикмахерскӧйсьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
варенньӧ	варенньӧыд	N;NOM;SG;PSS2S;LGSPEC1
кылавны	кылӧдчылісны	V;PL;3;PST;CAUS;PASS;LGSPEC_DELIM
дзользьыны	дзользьысь	V;SG;NEG;PASS
кагук	кагукыс	N;HUM;NOM;SG;PSS3S
весьт	весьтаныс	N;IN+ESS;SG;PSS3P
ньӧбны	ньӧби	V;SG;1;PST
пӧрт	пӧртйӧ	N;IN+ALL;SG
кыс	кыстӧ	N;ACC;SG;PSS2S
тема	тема	N;NOM;SG;LGSPEC1
сёр	серъяслӧн	N;GEN;PL
кӧк	кокыслӧн	N;HUM;GEN;SG;PSS3S
дзерӧдӧм	дзерӧдӧмӧн	ADJ;INS;SG
гу	гуясысь	N;IN+ABL;PL
оз	озлӧн	N;GEN;SG
веськавны	веськӧдчынысӧ	V;ACC;NFIN;PSS3S;CAUS;PASS
кыйны	кыйӧдны	V;NFIN;CAUS
сім	сімнысӧ	N;ACC;SG;PSS3P
мам-бать	мам-батькӧд	N;HUM;COM;SG;LGSPEC1
розьӧдны	розьӧдны	V;PL;2;NEG
плита	плитаӧн	N;INS;SG;LGSPEC1
финиш	финиш	N;NOM;SG;LGSPEC1
портрет	портретӧн	N;INS;SG;LGSPEC1
шоч	шочлӧн	ADJ;GEN;SG
гумла	гумлаясныс	N;NOM;PL;PSS3P;LGSPEC1
планшет	планшет	N;NOM;SG;LGSPEC1
ӧтувтчӧм	ӧтувтчӧмъяс	N;NOM;PL
успокоитны	успокоитчыны	V;PL;2;NEG;PASS;LGSPEC1
довъявны	довъявны	V;PL;2;NEG
ӧтка	ӧтка	ADJ;NOM;SG
больгыны	больгӧмыд	V;SG;2;PST
пачка	пачкаясӧ	N;IN+ALL;PL;LGSPEC1
шӧравны	шӧравны	V;NFIN
нӧйтӧм	нӧйтӧмсьыс	N;IN+ABL;SG;PSS3S
лелькуйтны	лелькуйтӧны	V;PL;3;PRS;LGSPEC1
райисполком	райисполкомлысь	N;ABL;SG;LGSPEC1
кежласьны	кежласис	V;SG;3;PST
чепӧсйӧм	чепӧсйӧмсӧ	N;ACC;SG;PSS3S
чермунны	чермунлӧ	V;SG;3;PRS;LGSPEC_DELIM
номер	номеръясӧ	N;NOM;PL;PSS1S;LGSPEC1
фотокарточка	фотокарточкаыс	N;NOM;SG;PSS3S;LGSPEC1
гӧльмыны	гӧльмӧд	V;IMP;SG;2;CAUS;LGSPEC1
завӧдитны	заводитам	V;PL;1;FUT;LGSPEC1
краж	краж	N;NOM;SG;LGSPEC1
идравны	идравлім	V;PL;1;PST;LGSPEC_DELIM
нальны	налим	V;PL;1;PST
пук	пуктӧмын	N;IN+ESS;SG;LGSPEC_ATTR;LGSPEC1
пӧсь	пӧсьтӧ	ADJ;ACC;SG;PSS2S
кытш	кытшъяссянь	N;PL;LGSPEC_EGR
ньӧбны	ньӧблӧмыд	V;SG;2;PST;LGSPEC_DELIM
купе	купеяс	N;NOM;PL;LGSPEC1
бизнес	бизнесӧ	N;NOM;SG;PSS1S;LGSPEC1
кутны	кута	V;SG;1;FUT
приёмнӧй	приёмнӧй	ADJ;NOM;SG;LGSPEC1
тшак	тшаклӧн	N;GEN;SG
лэптыны	лэпты	V;SG;NEG;TR
труппа	труппаас	N;IN+ESS;SG;PSS3S;LGSPEC1
балет	балетӧ	N;IN+ALL;SG;LGSPEC1
лелькуйтны	лелькуйтан	V;SG;2;PRS;LGSPEC1
петны	петкӧда	V;SG;1;FUT;CAUS
веськыдвыв	веськыдвыв	N;NOM;SG
йитӧд	йитӧдъяс	N;NOM;PL
янсавны	янсӧдіс	V;SG;3;PST;CAUS
кӧтшас	кӧтшасын	N;IN+ESS;SG
университет	университетсаӧс	N;ACC;SG;LGSPEC_ATTR;LGSPEC1
пасйыны	пасйышта	V;SG;1;FUT;LGSPEC_ATTEN
бабӧ	бабӧ	N;HUM;NOM;SG;LGSPEC1
произведение	произведениеяс	N;NOM;PL;LGSPEC1
мыськыны	мыськышті	V;SG;1;PST;LGSPEC_ATTEN
веськыд	веськыдӧ	ADJ;IN+ALL;SG
мам	мамлы	N;HUM;DAT;SG
реанимация	реанимация	N;NOM;SG;LGSPEC1
вожавны	вожалӧма	V;SG;3;PST
мэрия	мэрияын	N;IN+ESS;SG;LGSPEC1
нестандартнӧй	нестандартнӧйӧс	ADJ;ACC;SG;PSS1S;LGSPEC1
нуръявны	нуръясь	V;IMP;SG;2;PASS
комбинат	комбинат	N;NOM;SG;LGSPEC1
тытвидзны	тытвидзны	V;PL;2;NEG
ыдждавны	ыдждӧдас	V;SG;3;FUT;CAUS
обсерватория	обсерватория	N;NOM;SG;LGSPEC1
весьт	весьтам	N;IN+ESS;SG;PSS1S
палявны	паляласны	V;PL;3;FUT
субъект	субъекткӧд	N;COM;SG;LGSPEC1
кабала	кабалалысь	N;ABL;SG;LGSPEC1
сюйсьыны	сюйсьыны	V;PL;2;NEG
петны	петкӧдчанныд	V;PL;2;FUT;CAUS;PASS
челядьдыр	челядьдырсӧ	N;ACC;SG;PSS3S;LGSPEC1
овмӧс	овмӧснад	N;INS;SG;PSS2S
лола	лола	N;HUM;NOM;SG
бал	балас	N;IN+ESS;SG;PSS3S;LGSPEC1
чер	черыд	N;NOM;SG;PSS2S
секция	секцияысь	N;IN+ABL;SG;LGSPEC1
гӧльмыны	гӧльмыны	V;PL;2;NEG;LGSPEC1
юр	юръясӧ	N;NOM;PL;PSS1S
бомба	бомба	N;NOM;SG;LGSPEC1
чукӧстны	чукӧстны	V;NFIN
военкомат	военкомат	N;NOM;SG;LGSPEC1
ковтӧм	ковтӧмысла	ADJ;SG;PSS3S;LGSPEC_CNS
нар	нарад	N;IN+ALL;SG;PSS2S;LGSPEC1
конкурент	конкурентъяслӧн	N;HUM;GEN;PL;LGSPEC1
чукӧстны	чукӧстлы	V;SG;NEG;LGSPEC_DELIM
сериал	сериалтӧ	N;ACC;SG;PSS2S;LGSPEC1
кӧк	кокъясныс	N;HUM;NOM;PL;PSS3P
больгыны	больгысь	V;IMP;SG;2;PASS
пенсия	пенсияыс	N;NOM;SG;PSS3S;LGSPEC1
еджыд	еджыдджык	ADJ;NOM+COMPV;SG
кавшасьны	кавшасян	V;SG;2;FUT
ног	ногӧнджык	N;INS+COMPV;SG
правилӧ	правилӧяслӧн	N;GEN;PL;LGSPEC1
пеж	пеж	N;HUM;NOM;SG
ӧддзыны	ӧддзӧдам	V;PL;1;FUT;CAUS
джӧмдыны	джӧмдӧ	V;SG;3;PRS
пӧрӧдчысь	пӧрӧдчысьӧс	N;HUM;ACC;SG
тӧрытъя	тӧрытъяысь	ADJ;IN+ABL;SG
эштыны	эштӧдчис	V;SG;3;PST;CAUS;PASS
нюмъявны	нюмъялӧй	V;IMP;PL;2
зон	зонмыдлы	N;HUM;DAT;SG;PSS2S
лэптыны	лэптыв	V;SG;NEG;TR;LGSPEC_DELIM
чардби	чардби	N;NOM;SG
лямпа	лямпаяс	N;NOM;PL
шковгыны	шковгас	V;SG;3;FUT;INTR
лыбзьыны	лыбзьы	V;SG;NEG
тшак	тшаклысь	N;ABL;SG
телепон	телепонсянь	N;SG;LGSPEC_EGREXT
йирсьыны	йирсьӧ	V;SG;3;PRS
плита	плитаясын	N;IN+ESS;PL;LGSPEC1
кульны	кульсьӧ	V;SG;3;PRS;PASS
йывмыны	йывмысь	V;SG;NEG;PASS
кытш	кытшлы	N;DAT;SG
детдом	детдомас	N;IN+ALL;SG;PSS3S;LGSPEC1
номер	номер	N;NOM;SG;LGSPEC1
сикт	сиктъяслы	N;DAT;PL
жулик	жуликӧс	N;HUM;ACC;SG;LGSPEC1
шойччыны	шойччышт	V;SG;NEG;LGSPEC_ATTEN
уджалӧм	уджалӧмсьыд	N;IN+ABL;SG;PSS2S
мургыны	мургис	V;SG;3;PST
механизм	механизмъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
берег	берегысь	N;IN+ABL;SG;LGSPEC1
кыйны	кыйӧдӧмаӧсь	V;PL;3;PST;CAUS
нювны	нювлін	V;SG;2;PST;LGSPEC_DELIM
мирнӧй	мирнӧйӧн	ADJ;INS;SG;LGSPEC1
панӧм	панӧм	N;NOM;SG
палявны	паляв	V;IMP;SG;2
кывзысь	кывзысьтӧмӧс	N;HUM;ACC;SG;LGSPEC_ATTR;PSS1S
вылысса	вылысса	N;NOM;SG
кокньӧдны	кокньӧдӧ	V;SG;3;PRS
петны	петкӧдны	V;NFIN;CAUS
чолӧмавны	чолӧмаси	V;SG;1;PST;PASS
ыдждавны	ыдждӧдӧ	V;SG;3;PRS;CAUS
тусь	тусьястӧ	N;ACC;PL;PSS2S
волонтёр	волонтёръясӧн	N;HUM;INS;PL;LGSPEC1
пыксьыны	пыксьӧ	V;SG;3;PRS
атака	атакаӧн	N;INS;SG;LGSPEC1
тшетшкыны	тшетшкыны	V;NFIN
деятель	деятель	N;HUM;NOM;SG;LGSPEC1
чош	чош	ADJ;NOM;SG
сикт	сиктын	N;IN+ESS;SG
морт	мортъяслӧн	N;HUM;GEN;PL
петны	петам	V;PL;1;FUT
сибӧдчывны	сибӧдчысь	V;SG;NEG;PASS;LGSPEC_DELIM
жӧник	жӧникӧн	N;HUM;INS;SG;LGSPEC1
сайт	сайтъясын	N;IN+ESS;PL;LGSPEC1
профиль	профильса	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
пӧсь	пӧсьӧн	ADJ;INS;SG
оборудование	оборудованиелысь	N;ABL;SG;LGSPEC1
туялысь	туялысьлӧн	N;HUM;GEN;SG
мам-бать	мам-батьыскӧд	N;HUM;COM;SG;PSS3S;LGSPEC1
ломтас	ломтасӧн	N;INS;SG
национализм	национализм	N;NOM;SG;LGSPEC1
эрдавны	эрдӧдны	V;NFIN;CAUS
армия	армиялӧн	N;GEN;SG;LGSPEC1
перйыны	перъян	V;SG;2;PRS
еджыд	еджыдӧс	ADJ;ACC;SG;PSS1S
пинявны	пинявліс	V;SG;3;PST;LGSPEC_DELIM
завӧдитны	заводита	V;SG;1;PRS;LGSPEC1
шутёвтны	шутёвтлім	V;PL;1;PST;LGSPEC_DELIM
рӧдтыны	рӧдты	V;SG;NEG
петны	петлы	V;SG;NEG;LGSPEC_DELIM
туялысь	туялысьтӧг	N;HUM;SG;LGSPEC_CAR
бутылка	бутылкаӧн	N;INS;SG;LGSPEC1
пуръявны	пуръялас	V;SG;3;FUT
сгущёнка	сгущёнкаысь	N;IN+ABL;SG;LGSPEC1
письтны	письтас	V;SG;3;FUT
кабала	кабалаяс	N;NOM;PL;LGSPEC1
пеславны	песласян	V;SG;2;PRS;PASS
шедӧдӧм	шедӧдӧмӧ	N;IN+ALL;SG
буткыны	буткы	V;IMP;SG;2
лэптыны	лэптыштісны	V;PL;3;PST;TR;LGSPEC_ATTEN
дӧзьӧритӧм	дӧзьӧритӧмлы	N;DAT;SG;LGSPEC1
чипанпи	чипанпиян	N;HUM;NOM;PL
мам	мамъясӧс	N;HUM;ACC;PL
жираф	жираф	N;HUM;NOM;SG;LGSPEC1
твиттер	твиттерлысь	N;ABL;SG;LGSPEC1
ыпнитны	ыпнитас	V;SG;3;FUT
бригадиравны	бригадиравны	V;NFIN;LGSPEC1
петкӧдӧм	петкӧдӧмӧн	N;INS;SG
мамӧ	мамӧлысь	N;HUM;ABL;SG
сины	сиан	V;SG;2;FUT
дрӧгнитны	дрӧгнит	V;SG;NEG;LGSPEC1
ошйысьны	ошйысян	V;SG;2;PRS
доктор	докторӧс	N;HUM;ACC;SG;PSS1S;LGSPEC1
ворссьӧм	ворссьӧмнысӧ	N;ACC;SG;PSS3P
рака	ракаясӧ	N;HUM;NOM;PL;PSS1S
телепон	телепонысь	N;IN+ABL;SG;LGSPEC1
зумыдмыны	зумыдмӧдӧны	V;PL;3;PRS;CAUS
песны	песлала	V;ITER;SG;1;PRS;LGSPEC_DELIM
федерация	федерациялы	N;DAT;SG;LGSPEC1
са	саяс	N;NOM;PL
уджсикас	уджсикасъяслысь	N;ABL;PL
йитӧд	йитӧдъяслысь	N;ABL;PL
ойбыртны	ойбыртӧ	V;SG;3;PRS
йирсьыны	йирсьӧд	V;IMP;SG;2;CAUS
вен	веныс	N;NOM;SG;PSS3S
инновация	инновацияясӧн	N;INS;PL;LGSPEC1
ырӧш	ырӧшсӧ	N;ACC;SG;PSS3S
завӧдитны	заводитӧй	V;PL;1;NEG;LGSPEC1
отравитны	отравитӧмаӧсь	V;PL;3;PST;LGSPEC1
паськӧдӧм	паськӧдӧмсӧ	N;ACC;SG;PSS3S
довъявны	довъялӧ	V;SG;3;PRS
мыськыны	мыським	V;PL;1;PST
руч	ручысь	N;HUM;IN+ABL;SG
кластер	кластеръяслысь	N;ABL;PL;LGSPEC1
чаг	чагсӧ	N;ACC;SG;PSS3S
справка	справкаысь	N;IN+ABL;SG;LGSPEC1
чард	чардысь	N;IN+ABL;SG
пӧрт	портъясӧ	N;NOM;PL;PSS1S
куньтыртны	куньтыртлас	V;SG;3;FUT;LGSPEC_DELIM
руч	ручсаяслӧн	N;HUM;GEN;PL;LGSPEC_ATTR
пыксьыны	пыксьыв	V;IMP;SG;2;LGSPEC_DELIM
концепция	концепцияас	N;IN+ALL;SG;PSS3S;LGSPEC1
заводитны	заводитанныд	V;PL;2;FUT;LGSPEC1
ног	ногсаджык	N;NOM+COMPV;SG;LGSPEC_ATTR
кырны	кырӧдісны	V;PL;3;PST;CAUS
пыксьыны	пыксьыны	V;PL;2;NEG
кутны	кутім	V;PL;1;PST
зелля	зелля	N;NOM;SG;LGSPEC1
кыйны	кыйсьыны	V;PL;2;NEG;PASS
нажӧвитны	нажӧвитны	V;NFIN;LGSPEC1
вины	висян	V;SG;2;PRS;PASS
гуны	гукӧд	V;SG;NEG;CAUS
укӧрайтны	укӧрайтны	V;PL;2;NEG;LGSPEC1
дружба	дружбаысь	N;IN+ABL;SG;LGSPEC1
лунпас	лунпасъяс	N;NOM;PL
пӧртӧм	пӧртӧмсӧ	N;ACC;SG;PSS3S
отравитны	отравитчыны	V;NFIN;PASS;LGSPEC1
спорт	спортас	N;IN+ALL;SG;PSS3S;LGSPEC1
чашка	чашкаяссӧ	N;ACC;PL;PSS3S;LGSPEC1
кекӧначавны	кекӧначасьны	V;NFIN;PASS
пасьтавны	пасьтавлы	V;SG;NEG;LGSPEC_DELIM
кӧявны	коялӧ	V;SG;3;PRS
видеокамера	видеокамералӧн	N;GEN;SG;LGSPEC1
вӧдитчӧм	вӧдитчӧмлысь	N;ABL;SG
кӧтны	кӧтӧдыштӧй	V;IMP;PL;2;CAUS;LGSPEC_ATTEN
хозяйство	хозяйство	N;NOM;SG;LGSPEC1
чуйдавны	чуйдӧд	V;IMP;SG;2;CAUS
лӧньны	лӧньӧдча	V;SG;1;FUT;CAUS;PASS
ракапи	ракапиянлӧн	N;HUM;GEN;PL
мича	мичаӧс	ADJ;ACC;SG;PSS1S
карта	карталы	N;DAT;SG
ӧтвет	ӧтветнад	N;INS;SG;PSS2S;LGSPEC1
вӧравны	вӧравлім	V;PL;1;PST;LGSPEC_DELIM
улича	уличаяслӧн	N;GEN;PL;LGSPEC1
ёрт	ёртъясыслы	N;HUM;DAT;PL;PSS3S
гажмыны	гажмӧны	V;PL;3;PRS
индыны	индывлыны	V;PL;2;NEG;LGSPEC_DELIM
вем	вемтӧм	N;NOM;SG;LGSPEC_ATTR
ошкыны	ошкӧй	V;PL;1;NEG
рӧдитель	рӧдитель	N;HUM;NOM;SG;LGSPEC1
вузавны	вузалӧй	V;IMP;PL;2
пышйыны	пышъян	V;SG;2;PRS
лӧсьӧдӧм	лӧсьӧдӧмӧн	N;INS;SG
том	томъяслӧн	ADJ;GEN;PL
куритны	куритчӧй	V;PL;1;NEG;PASS;LGSPEC1
кывзыны	кывзӧны	V;PL;3;PRS
вӧрзьыны	вӧрзьӧдӧ	V;SG;3;PRS;CAUS
председатель	председательӧ	N;HUM;IN+ALL;SG;LGSPEC1
козъян	козъянсьыс	N;HUM;IN+ABL;SG;PSS3S
котыр	котыртӧмысь	N;IN+ABL;SG;LGSPEC_ATTR
электрик	электрикӧн	N;HUM;INS;SG;LGSPEC1
бурдӧдысь	бурдӧдысьӧс	N;HUM;ACC;SG;PSS1S
жаравеч	жаравеч	N;NOM;SG;LGSPEC1
батальон	батальоныс	N;NOM;SG;PSS3S;LGSPEC1
тыш	тышъясӧн	N;INS;PL
мероприятие	мероприятиеяс	N;NOM;PL;LGSPEC1
педучилище	педучилищеад	N;IN+ALL;SG;PSS2S;LGSPEC1
бок	бокъястӧ	N;ACC;PL;PSS2S;LGSPEC1
рай	райын	N;IN+ESS;SG;LGSPEC1
триллион	триллион	N;NOM;SG;LGSPEC1
пузьыны	пузьӧдӧ	V;SG;3;PRS;CAUS
уджмог	уджмогъяс	N;NOM;PL
вера	вера	N;NOM;SG;LGSPEC1
кӧкны	кокӧд	V;SG;NEG;CAUS
пӧль	пӧль	N;HUM;NOM;SG
вентиляция	вентиляцияӧн	N;INS;SG;LGSPEC1
кывтны	кывтлывлім	V;PL;1;PST;LGSPEC_DELIM
роч	рочьяскӧд	N;HUM;COM;PL
механизируйтны	механизируйтӧма	V;SG;3;PST;LGSPEC1
право	правояссӧ	N;ACC;PL;PSS3S;LGSPEC1
чишкавны	чишкавны	V;NFIN
кывзыны	кывзыси	V;SG;1;PST;PASS
клёнӧдны	клёнӧдчам	V;PL;1;PRS;PASS
вочаавны	вочаасьлам	V;PL;1;PRS;PASS;LGSPEC_DELIM
эравны	эравны	V;NFIN
ӧтторъя	ӧтторъя	ADJ;NOM;SG
вугыр	вугырӧ	N;NOM;SG;PSS1S
ныв-пи	ныв-пиыд	N;HUM;NOM;SG;PSS2S
ноксьыны	ноксьысь	V;SG;NEG;PASS
плака	плакаяс	N;NOM;PL;LGSPEC1
воавны	воӧдчынысӧ	V;ACC;NFIN;PSS3S;CAUS;PASS
блогер	блогерлы	N;HUM;DAT;SG;LGSPEC1
скӧр	скӧрсӧ	ADJ;ACC;SG;PSS3S
команда	командаяс	N;NOM;PL;LGSPEC1
точка	точка	N;NOM;SG;LGSPEC1
пыран	пыранын	ADJ;IN+ESS;SG
дрӧгмунны	дрӧгмунны	V;NFIN;LGSPEC1
клетка	клеткасьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
ёма	ёмалысь	N;HUM;ABL;SG
сорлавны	сорласисны	V;PL;3;PST;PASS
веритны	веритіс	V;SG;3;PST;LGSPEC1
сімны	сімкӧд	V;IMP;SG;2;CAUS
кад	кадсянь	N;SG;LGSPEC_EGR
гындыны	гындісны	V;PL;3;PST
вооружитӧм	вооружитӧм	N;NOM;SG;LGSPEC1
сьыланкыв	сьыланкывъяснас	N;INS;PL;PSS3S
мусукасьны	мусукасьны	V;PL;2;NEG
автомат	автоматас	N;IN+ESS;SG;PSS3S;LGSPEC1
рубрика	рубрикаын	N;IN+ESS;SG;LGSPEC1
сюсь	сюсьӧсь	ADJ;PL
ёнмыны	ёнмӧдыштны	V;PL;2;NEG;CAUS;LGSPEC_ATTEN
радиокомпания	радиокомпанияяскӧд	N;COM;PL;LGSPEC1
чувствуйтны	чувствуйтан	V;SG;2;PRS;LGSPEC1
администрация	администрацияӧн	N;INS;SG;LGSPEC1
рыт	рытыслы	N;DAT;SG;PSS3S
кондуктор	кондукторъяслы	N;HUM;DAT;PL;LGSPEC1
президиум	президиумӧн	N;INS;SG;LGSPEC1
быдтыны	быдтам	V;PL;1;FUT
овмыны	овмӧдӧй	V;PL;1;NEG;CAUS
скандал	скандал	N;NOM;SG;LGSPEC1
броткыны	броткыштісны	V;PL;3;PST;LGSPEC_ATTEN
тӧдмавны	тӧдмала	V;SG;1;FUT
вайны	вайла	V;SG;1;FUT;LGSPEC_DELIM
таладор	таладорын	N;IN+ESS;SG
дитя	дитясӧ	N;HUM;ACC;SG;PSS3S;LGSPEC1
мынтавны	мынтӧдчин	V;SG;2;PST;CAUS;PASS
шыбитны	шыбитлісны	V;PL;3;PST;LGSPEC_DELIM
интервент	интервентъяслӧн	N;HUM;GEN;PL;LGSPEC1
критика	критикаысь	N;IN+ABL;SG;LGSPEC1
куритчан	куритчантӧ	N;ACC;SG;PSS2S;LGSPEC1
виктория	викторияӧс	N;ACC;SG;LGSPEC1
коса	косаад	N;IN+ESS;SG;PSS2S;LGSPEC1
кост	костъясас	N;IN+ESS;PL;PSS3S
полиция	полицияӧс	N;ACC;SG;PSS1S;LGSPEC1
гажӧдны	гажӧд	V;SG;NEG
туйдны	туйдан	V;SG;2;PRS
контора	контораын	N;IN+ESS;SG;LGSPEC1
методика	методика	N;NOM;SG;LGSPEC1
панапида	панапидаыс	N;NOM;SG;PSS3S;LGSPEC1
педиатр	педиатрным	N;HUM;NOM;SG;PSS1P;LGSPEC1
состояние	состояниесӧ	N;ACC;SG;PSS3S;LGSPEC1
комиссар	комиссарлӧн	N;HUM;GEN;SG;LGSPEC1
льӧм	льӧмйыслӧн	N;GEN;SG;PSS3S
вой	войяс	N;NOM;PL
суны	сулалӧ	V;ITER;SG;3;PRS;LGSPEC_DELIM
велӧдан	велӧданныд	ADJ;NOM;SG;PSS2P
шедны	шедасджык	V;COMPV;SG;3;FUT
образ	образъяслысь	N;ABL;PL;LGSPEC1
вайны	вайӧдӧ	V;SG;3;PRS;CAUS
республика	республикаӧн	N;INS;SG;LGSPEC1
ӧдзӧс	ӧдзӧсӧн	N;INS;SG
ньӧв	ньӧвйыс	N;NOM;SG;PSS3S
эскыны	эскӧда	V;SG;1;PRS;CAUS
ӧлавны	ӧлӧд	V;IMP;SG;2;CAUS
пункт	пунктӧ	N;NOM;SG;PSS1S;LGSPEC1
поезд	поездын	N;IN+ESS;SG;LGSPEC1
сценка	сценкасӧ	N;ACC;SG;PSS3S;LGSPEC1
надейтчыны	надейтча	V;SG;1;FUT;LGSPEC1
смерть	смертьӧс	N;ACC;SG;PSS1S;LGSPEC1
привал	привал	N;NOM;SG;LGSPEC1
пос	поскыд	N;NOM;SG;PSS2S
кырта	кырта	N;NOM;SG
дэльӧдны	дэльӧдчы	V;SG;NEG;PASS
нотаавны	нотаавны	V;PL;2;NEG;LGSPEC1
йӧр	йӧраныс	N;IN+ALL;SG;PSS3P
АВГ	авг	N;NOM;SG;LGSPEC1
артыштны	артыштам	V;PL;1;FUT
видзавны	видзӧдлам	V;PL;1;FUT;CAUS;LGSPEC_DELIM
чой	чойӧд	N;HUM;PROL;SG
кӧкны	кӧкӧдан	V;SG;2;PRS;CAUS
рытыввыв	рытыввывсаясын	N;IN+ESS;PL;LGSPEC_ATTR
домкрат	домкратыс	N;NOM;SG;PSS3S;LGSPEC1
кузя	кузяӧс	N;ACC;SG
помнитны	помнитӧй	V;IMP;PL;2;LGSPEC1
кывсьыны	кывсьӧ	V;SG;3;PRS
буситны	буситӧ	V;SG;3;PRS
тӧлавны	тӧлӧдны	V;NFIN;CAUS
серпасавны	серпасалі	V;SG;1;PST
воштыны	воштысян	V;SG;2;FUT;PASS
висьтавны	висьтасян	V;SG;2;FUT;PASS
медбур	медбуръяснас	ADJ;INS;PL;PSS3S
няйт	няйтӧн	N;INS;SG
югӧр	югӧръясӧс	N;ACC;PL;PSS1S
архангел	архангелыс	N;NOM;SG;PSS3S;LGSPEC1
серӧктыны	серӧкта	V;SG;1;FUT
вуз	вузӧс	N;ACC;SG;PSS1S;LGSPEC1
кыскӧм	кыскӧмкӧд	N;COM;SG
чуктыны	чуктан	V;SG;2;FUT
рӧдвуж	рӧдвуж	N;HUM;NOM;SG;LGSPEC1
шогны	шогсьӧны	V;PL;3;PRS;PASS
вурны	вуран	V;SG;2;FUT
сьӧр	сьӧрсьыныд	N;IN+ABL;SG;PSS2P
мынтыны	мынтӧдны	V;PL;2;NEG;CAUS
вадор	вадорыд	N;NOM;SG;PSS2S
зарни	зарниӧн	N;INS;SG
доцент	доцентӧс	N;HUM;ACC;SG;LGSPEC1
бюджетник	бюджетникъяс	N;HUM;NOM;PL;LGSPEC1
вӧтны	вӧтлӧ	V;SG;3;PRS;LGSPEC_DELIM
парсавны	парсалім	V;PL;1;PST
турӧбавны	турӧбаліс	V;SG;3;PST
сямтӧм	сямтӧмъясыд	ADJ;NOM;PL;PSS2S
обучение	обучение	N;NOM;SG;LGSPEC1
видзӧдысь	видзӧдысьясыд	N;HUM;NOM;PL;PSS2S
вӧчны	вӧчан	V;SG;2;FUT
образ	образъясыс	N;NOM;PL;PSS3S;LGSPEC1
чужӧм	чужӧмсьыс	N;IN+ABL;SG;PSS3S
югӧр	югӧръяслӧн	N;GEN;PL
восны	восӧдны	V;NFIN;CAUS
рӧштво	рӧштвоӧ	N;IN+ALL;SG;LGSPEC1
ном	номсӧ	N;HUM;ACC;SG;PSS3S
легенда	легендалӧн	N;GEN;SG;LGSPEC1
направленньӧ	направленньӧӧй	N;NOM;SG;PSS1S;LGSPEC1
ю	юла	N;SG;LGSPEC_CNS
грезд	грезданым	N;IN+ESS;SG;PSS1P
бӧрйыны	бӧръям	V;PL;1;FUT
телега	телеганас	N;INS;SG;PSS3S;LGSPEC1
звӧнитны	звӧнитӧй	V;IMP;PL;2;LGSPEC1
пластайтны	пластайтчыны	V;PL;2;NEG;PASS;LGSPEC1
серпасавны	серпасалан	V;SG;2;PRS
делӧ	делӧыскӧд	N;COM;SG;PSS3S;LGSPEC1
зэвтны	зэвтчылісны	V;PL;3;PST;PASS;LGSPEC_DELIM
мездыны	мездысян	V;SG;2;FUT;PASS
лӧгавны	лӧгасьлы	V;SG;NEG;PASS;LGSPEC_DELIM
могмыны	могмӧдам	V;PL;1;PRS;CAUS
шахмат	шахматысь	N;IN+ABL;SG;LGSPEC1
быдмыны	быдмӧны	V;PL;3;PRS
аэропорт	аэропортӧдзыд	N;TERM;SG;PSS2S;LGSPEC1
мыжавны	мыжавлісны	V;PL;3;PST;LGSPEC_DELIM
чурка	чурканас	N;INS;SG;PSS3S;LGSPEC1
торъявны	торъяв	V;IMP;SG;2
сяльгыны	сяльгис	V;SG;3;PST
скӧрмыны	скӧрмӧд	V;IMP;SG;2;CAUS
воны	воыштас	V;SG;3;FUT;LGSPEC_ATTEN
осётр	осётр	N;HUM;NOM;SG;LGSPEC1
сӧвесть	сӧвестьысь	N;IN+ABL;SG;LGSPEC1
басни	басни	N;NOM;SG;LGSPEC1
кӧрны	корсим	V;PL;1;PST;PASS
юрсигусь	юрсигусьлӧн	N;HUM;GEN;SG
сӧстӧм	сӧстӧмнас	ADJ;INS;SG;PSS3S
клиника	клиникаас	N;IN+ESS;SG;PSS3S;LGSPEC1
техникум	техникумъяслы	N;DAT;PL;LGSPEC1
броткыны	броткӧны	V;PL;3;PRS
келавны	келав	V;IMP;SG;2
ваймыны	ваймы	V;IMP;SG;2
удждывны	удждысьӧй	V;PL;1;NEG;PASS;LGSPEC_DELIM
сырчик	сырчикъяс	N;HUM;NOM;PL
склад	склад	N;NOM;SG;LGSPEC1
гартчан	гартчан	ADJ;NOM;SG
шыбитны	шыбитасны	V;PL;3;FUT
тун	тунлӧн	N;HUM;GEN;SG
волӧм	волӧмӧ	N;IN+ALL;SG
счётчик	счётчиклӧн	N;HUM;GEN;SG;LGSPEC1
медічӧт	медічӧтыслы	ADJ;DAT;SG;PSS3S
торйӧдчӧм	торйӧдчӧмӧн	N;INS;SG
бюджет	бюджеттӧг	N;SG;LGSPEC_CAREXT
риск	рискӧн	N;INS;SG;LGSPEC1
военно-патриотическӧй	военно-патриотическӧй	ADJ;NOM;SG;LGSPEC1
мынны	мынла	V;SG;1;FUT;LGSPEC_DELIM
лэч	лэчтӧг	N;SG;LGSPEC_CAR
ылӧдчытӧм	ылӧдчытӧмӧн	ADJ;INS;SG
рӧдина	рӧдинаӧн	N;INS;SG;LGSPEC1
вертолёт	вертолёттӧ	N;ACC;SG;PSS2S;LGSPEC1
томатнӧй	томатнӧй	ADJ;NOM;SG;LGSPEC1
грезд	грездсаясӧс	N;ACC;PL;LGSPEC_ATTR
тӧдмавны	тӧдмаланныд	V;PL;2;PRS
выставка	выставкаясӧ	N;IN+ALL;PL;LGSPEC1
омра	омраын	N;IN+ESS;SG
дой	дойясыс	N;NOM;PL;PSS3S
гулю	гулюлӧн	N;HUM;GEN;SG
жӧникпу	жӧникпуӧс	N;HUM;ACC;SG;LGSPEC1
рӧч	рочьясыс	N;NOM;PL;PSS3S
авария	аварияясыс	N;NOM;PL;PSS3S;LGSPEC1
сысъявны	сысъялӧны	V;PL;3;PRS
ылькйыны	ылькйы	V;SG;NEG;INTR
вож	вожсаяс	N;NOM;PL;LGSPEC_ATTR
состав	составлысь	N;ABL;SG;LGSPEC1
тӧдны	тӧдыштам	V;PL;1;FUT;LGSPEC_ATTEN
ӧдзӧс	ӧдзӧсыд	N;NOM;SG;PSS2S
мӧвп	мӧвпъяснас	N;INS;PL;PSS3S
ян	янлы	N;DAT;SG
акань	аканьсӧ	N;ACC;SG;PSS3S
ӧтнога	ӧтнога	ADJ;NOM;SG
машина	машинасьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
бурмыны	бурмӧны	V;PL;3;PRS
король	корольӧн	N;HUM;INS;SG;LGSPEC1
амбар	амбаръясныс	N;NOM;PL;PSS3P;LGSPEC1
топӧдӧм	топӧдӧм	N;NOM;SG
водзмӧстчысь	водзмӧстчысьясыс	N;HUM;NOM;PL;PSS3S
висьт	висьтысь	N;IN+ABL;SG
чурвидзны	чурвидзан	V;SG;2;FUT
зумыдмӧдӧм	зумыдмӧдӧм	N;NOM;SG
вуджӧдчысь	вуджӧдчысьяслысь	N;HUM;ABL;PL
чача	чачалы	N;DAT;SG
реорганизуйтӧм	реорганизуйтӧм	N;NOM;SG;LGSPEC1
радиопередача	радиопередача	N;NOM;SG;LGSPEC1
регион	регионъяс	N;NOM;PL;LGSPEC1
сӧтана	сӧтанаыс	N;NOM;SG;PSS3S;LGSPEC1
колльыны	коллим	V;PL;1;PST
сёрни	сёрниӧ	N;NOM;SG;PSS1S
рузум	рузумӧ	N;NOM;SG;PSS1S
йӧзӧдӧм	йӧзӧдӧмыс	N;NOM;SG;PSS3S
гыжъявны	гыжъявны	V;PL;2;NEG
жёлтӧй	жёлтӧй	ADJ;NOM;SG;LGSPEC1
слӧймыны	слӧймим	V;PL;1;PST
пасьта	пасьтаӧн	N;INS;SG
бурдны	бурдӧдны	V;PL;2;NEG;CAUS
ай	айыд	N;HUM;NOM;SG;PSS2S
вочавидзны	вочавидзӧны	V;PL;3;PRS
машина	машинаас	N;IN+ALL;SG;PSS3S;LGSPEC1
дзолюк	дзолюкъяссӧ	N;HUM;ACC;PL;PSS3S
бӧж	бӧжас	N;IN+ALL;SG;PSS3S
вынсьӧдны	вынсьӧдас	V;SG;3;FUT
слӧй	слӧйсӧ	N;ACC;SG;PSS3S;LGSPEC1
мын	мынла	N;SG;LGSPEC_CNS
монь	монь	N;HUM;NOM;SG
куръя	куръясӧ	N;ACC;SG;PSS3S
вӧдитны	вӧдитчасны	V;PL;3;FUT;PASS
индыны	индӧ	V;SG;3;PRS
велавны	велӧднысӧ	V;ACC;NFIN;PSS3S;CAUS
тырсявны	тырсьӧдны	V;NFIN;CAUS
вотчина	вотчина	N;NOM;SG;LGSPEC1
аппарат	аппаратӧ	N;IN+ALL;SG;LGSPEC1
кад	кадад	N;IN+ESS;SG;PSS2S
ызӧн	ызӧн	N;NOM;SG
чышкыны	чышкыштӧй	V;IMP;PL;2;LGSPEC_ATTEN
лавка	лавкаяслӧн	N;GEN;PL;LGSPEC1
кушин	кушинъясын	N;HUM;IN+ESS;PL
чуймавны	чуймӧдасны	V;PL;3;FUT;CAUS
креставны	крестась	V;SG;NEG;PASS;LGSPEC1
вӧляникысь	вӧляникысь	ADJ;NOM;SG;LGSPEC1
делӧ	делӧяслӧн	N;GEN;PL;LGSPEC1
учение	учениеясӧ	N;IN+ALL;PL;LGSPEC1
фото	фотояссӧ	N;ACC;PL;PSS3S;LGSPEC1
кельдавны	кельдӧдыштіс	V;SG;3;PST;CAUS;LGSPEC_ATTEN
иславны	ислалыштны	V;NFIN;LGSPEC_ATTEN
бонзьыны	бонзьӧмаӧсь	V;PL;3;PST
сёрнитны	сёрнитчавны	V;ITER;PL;2;NEG;PASS
нёрпавны	нёрпавлі	V;SG;1;PST;LGSPEC_DELIM
би	биас	N;IN+ESS;SG;PSS3S
трактир	трактиръясын	N;IN+ESS;PL;LGSPEC1
ошкыны	ошка	V;SG;1;FUT
епископ	епископыд	N;HUM;NOM;SG;PSS2S;LGSPEC1
месторождение	месторождениеяс	N;NOM;PL;LGSPEC1
йӧзӧдны	йӧзӧдла	V;SG;1;PRS;LGSPEC_DELIM
пуктӧм	пуктӧмтӧ	N;ACC;SG;PSS2S
гӧрддзавны	гӧрддзаліс	V;SG;3;PST
заптыны	заптан	V;SG;2;PRS
эксперимент	экспериментъясӧ	N;IN+ALL;PL;LGSPEC1
навӧлӧк	навӧлӧк	N;NOM;SG;LGSPEC1
нёльзьыны	нельзя	V;SG;1;PRS
вермыны	вермӧдча	V;SG;1;FUT;CAUS;PASS
мӧс	мӧскыскӧд	N;HUM;COM;SG;PSS3S
тьӧт	тьӧтӧ	N;HUM;IN+ALL;SG;LGSPEC1
сьылідзир	сьылідзирсӧ	N;ACC;SG;PSS3S
инмавны	инмӧдчылӧ	V;SG;3;PRS;CAUS;PASS;LGSPEC_DELIM
рӧч	рочьяссӧ	N;ACC;PL;PSS3S
кад	кадӧдз	N;TERM;SG
дзескыд	дзескыдӧсь	ADJ;PL
сьывны	сьылас	V;SG;3;FUT
быдмӧг	быдмӧглӧн	N;GEN;SG
ловзьыны	ловзям	V;PL;1;FUT
велавны	велӧдчӧны	V;PL;3;PRS;CAUS;PASS
зажиточнӧй	зажиточнӧйяс	ADJ;NOM;PL;LGSPEC1
колян	колян	ADJ;NOM;SG
югъявны	югъялан	V;SG;2;PRS
юрбитӧм	юрбитӧм	N;NOM;SG
труба	трубаясӧд	N;PROL;PL;LGSPEC1
вермӧм	вермӧмъяссӧ	N;ACC;PL;PSS3S
шуд	шудным	N;NOM;SG;PSS1P
уколавны	уколасян	V;SG;2;FUT;PASS;LGSPEC1
юрнуӧдны	юрнуӧдан	V;SG;2;FUT
власьт	власьтлы	N;DAT;SG;LGSPEC1
ёнтыны	ёнтысь	V;IMP;SG;2;PASS
чина	чинаясыдлы	ADJ;DAT;PL;PSS2S;LGSPEC1
ситуация	ситуацияӧ	N;IN+ALL;SG;LGSPEC1
конкурсант	конкурсантъясӧс	N;HUM;ACC;PL;LGSPEC1
вез	везйӧ	N;NOM;SG;PSS1S
стаж	стаж	N;NOM;SG;LGSPEC1
сьӧр	сьӧрсьыс	N;IN+ABL;SG;PSS3S
гӧстинеч	гӧстинечьяс	N;NOM;PL;LGSPEC1
сертификат	сертификатъяслысь	N;ABL;PL;LGSPEC1
пожъявны	пожъясь	V;SG;NEG;PASS
ёрд	ёрдъясӧ	N;NOM;PL;PSS1S
киномеханик	киномеханикъяс	N;HUM;NOM;PL;LGSPEC1
фигурист	фигурист	N;HUM;NOM;SG;LGSPEC1
пошиктыны	пошиктӧ	V;SG;3;PRS
история	историяӧс	N;ACC;SG;LGSPEC1
гижӧд	гижӧдъяссӧ	N;ACC;PL;PSS3S
тӧждысьысь	тӧждысьысьӧн	ADJ;INS;SG
ытшкытӧм	ытшкытӧм	ADJ;NOM;SG
йитны	йитлан	V;SG;2;FUT;LGSPEC_DELIM
витны	виті	V;SG;1;PST
вермыны	вермӧдча	V;SG;1;PRS;CAUS;PASS
донавны	донӧдны	V;NFIN;CAUS
рай	райӧ	N;NOM;SG;PSS1S;LGSPEC1
ӧткодявны	ӧткодяв	V;IMP;SG;2
грек	грекӧс	N;ACC;SG;LGSPEC1
ёль	ёльӧ	N;IN+ALL;SG
во	вояснас	N;INS;PL;PSS3S
верстьӧ	верстьӧлы	ADJ;DAT;SG
ун	унмӧс	N;ACC;SG
кань	каньным	N;HUM;NOM;SG;PSS1P
тур	турас	N;IN+ALL;SG;PSS3S;LGSPEC1
рыт	рытлы	N;DAT;SG
садитӧм	садитӧмын	N;IN+ESS;SG;LGSPEC1
кыскыны	кыскан	V;SG;2;PRS
этнограф	этнографӧн	N;HUM;INS;SG;LGSPEC1
садьмыны	садьмам	V;PL;1;FUT;INTR
пласт	пластъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
чужӧм	чужӧм	N;NOM;SG
вичмыны	вичмӧдлін	V;SG;2;PST;CAUS;LGSPEC_DELIM
кужны	кужас	V;SG;3;FUT
воссьӧм	воссьӧмыс	N;NOM;SG;PSS3S
уськӧдны	уськӧдчам	V;PL;1;FUT;PASS
кӧсйӧм	кӧсйӧмъясныд	N;NOM;PL;PSS2P
ичӧт	ичӧтджыкнас	ADJ;INS+COMPV;SG;PSS3S
шмонитана	шмонитанаӧс	ADJ;ACC;SG
вочаавны	вочаалан	V;SG;2;FUT
вӧв	волас	N;HUM;IN+ALL;SG;PSS3S
дука	дукаӧн	ADJ;INS;SG;LGSPEC1
полномочие	полномочиесӧ	N;ACC;SG;PSS3S;LGSPEC1
гез	гез	N;NOM;SG
ёрт	ёртъясныд	N;HUM;NOM;PL;PSS2P
нир	ниртӧ	N;ACC;SG;PSS2S
кынь	кынь	N;HUM;NOM;SG
князь	князьлы	N;DAT;SG
помны	помлан	V;SG;2;PRS;LGSPEC_DELIM
нуавны	нуӧдӧй	V;IMP;PL;2;CAUS
пасьта	пасьтала	N;SG;LGSPEC_CNS
роз	розйыс	N;NOM;SG;PSS3S
мынтыны	мынтӧдчан	V;SG;2;FUT;CAUS;PASS
клиника	клиникаясын	N;IN+ESS;PL;LGSPEC1
воспитатель	воспитательяслы	N;HUM;DAT;PL;LGSPEC1
садитны	садитан	V;SG;2;FUT;LGSPEC1
каратист	каратистъяскӧд	N;HUM;COM;PL;LGSPEC1
лысьтны	лысьті	V;SG;1;PST
кухня	кухняас	N;IN+ALL;SG;PSS3S;LGSPEC1
сёй	сёйла	N;SG;LGSPEC_CNS
племянник	племянникъясыс	N;HUM;NOM;PL;PSS3S;LGSPEC1
пӧгибнитны	пӧгибнитас	V;SG;3;FUT;LGSPEC1
нуны	нуӧдлы	V;IMP;SG;2;CAUS;LGSPEC_DELIM
сибдыны	сибдывны	V;PL;2;NEG;LGSPEC_DELIM
истина	истина	N;NOM;SG;LGSPEC1
гусясьысь	гусясьысьтӧ	N;HUM;ACC;SG;PSS2S
резны	резыштіс	V;SG;3;PST;LGSPEC_ATTEN
бригада	бригадаяслы	N;DAT;PL;LGSPEC1
кынйир	кынйирас	N;IN+ALL;SG;PSS3S
веравны	веравны	V;NFIN
панас	панасын	N;IN+ESS;SG
джагавны	джагӧдӧ	V;SG;3;PRS;CAUS
теплица	теплицаыд	N;NOM;SG;PSS2S;LGSPEC1
кай	кайяс	N;HUM;NOM;PL
автобус	автобусъяслы	N;DAT;PL;LGSPEC1
ӧшны	ӧшӧдлывлыны	V;NFIN;CAUS;LGSPEC_DELIM
везйӧдны	везйӧдлан	V;SG;2;PRS;LGSPEC_DELIM
поэт	поэтсянь	N;HUM;SG;LGSPEC_EGREXT
сяльӧдчыны	сяльӧдчы	V;SG;NEG
кодзувкот	кодзувкотын	N;HUM;IN+ESS;SG
рельс	рельсъяс	N;NOM;PL;LGSPEC1
шутёв	шутёв	N;NOM;SG
индӧм	индӧм	N;NOM;SG
программа	программаӧн	N;INS;SG;LGSPEC1
чинны	чині	V;SG;1;PST
сынавны	сынӧд	V;SG;NEG;CAUS
син	синъясас	N;IN+ALL;PL;PSS3S
пӧтӧлӧк	пӧтӧлӧкӧ	N;IN+ALL;SG;LGSPEC1
сёй	сёйыс	N;NOM;SG;PSS3S
вина	винаӧн	N;INS;SG;LGSPEC1
стрӧитчысь	стрӧитчысьяс	N;HUM;NOM;PL;LGSPEC1
лэбавны	лэбала	V;SG;1;PRS
сувтавны	сувтӧда	V;SG;1;PRS;CAUS
юӧр	юӧрсьыс	N;IN+ABL;SG;PSS3S
вежнясьны	вежнясьны	V;NFIN
сёрнитны	сёрнитлыны	V;PL;2;NEG;LGSPEC_DELIM
сынны	сынӧдас	V;SG;3;FUT;CAUS
менталитет	менталитетсӧ	N;ACC;SG;PSS3S;LGSPEC1
велавны	велӧдышталі	V;ITER;SG;1;PST;CAUS;LGSPEC_ATTEN
племянник	племянникӧс	N;HUM;ACC;SG;LGSPEC1
гимназия	гимназияӧдз	N;TERM;SG;LGSPEC1
банк	банкыслы	N;DAT;SG;PSS3S;LGSPEC1
вештыны	вештысьны	V;NFIN;PASS
вотӧс	вотӧссӧ	N;ACC;SG;PSS3S
звукооператор	звукооператоръяслы	N;HUM;DAT;PL;LGSPEC1
ненога	ненога	ADJ;NOM;SG
дзӧргыны	дзоргысь	V;SG;NEG;PASS
дон	донӧ	N;IN+ALL;SG
ӧбижайтны	ӧбижайтӧны	V;PL;3;PRS;LGSPEC1
тӧждысьысь	тӧждысьысьяслы	ADJ;DAT;PL
комиссия	комиссияӧ	N;NOM;SG;PSS1S;LGSPEC1
путешественник	путешественникъясӧс	N;HUM;ACC;PL;LGSPEC1
броткысь	броткысьӧн	N;HUM;INS;SG
вома	воманыс	ADJ;NOM;SG;PSS3P
шедавны	шедӧдам	V;PL;1;PRS;CAUS
приступ	приступыс	N;NOM;SG;PSS3S;LGSPEC1
сӧвны	соссьыны	V;NFIN;PASS
моторист	мотористӧ	N;HUM;IN+ALL;SG;LGSPEC1
виччыны	виччысянныд	V;PL;2;PRS;PASS
печкыны	печкан	V;SG;2;PRS
вир	вирӧдз	N;TERM;SG
котравны	котравлӧй	V;PL;2;NEG;LGSPEC_DELIM
сьылысь	сьылысьыд	N;HUM;NOM;SG;PSS2S
институт	институтъяслӧн	N;GEN;PL;LGSPEC1
вайны	вайӧдӧны	V;PL;3;PRS;CAUS
туй	туйыслӧн	N;GEN;SG;PSS3S
зачёт	зачётын	N;IN+ESS;SG;LGSPEC1
хакер	хакерӧн	N;HUM;INS;SG;LGSPEC1
мича	мичаӧ	ADJ;IN+ALL;SG
эскана	эсканаӧсь	ADJ;PL
дойдны	дойдлыны	V;NFIN;LGSPEC_DELIM
сорсьыны	сорсьыны	V;NFIN
кувлыны	кувлыны	V;PL;2;NEG;LGSPEC_DELIM
вуджан	вуджанныд	N;NOM;SG;PSS2P
во	воясӧдз	N;TERM;PL
чукӧр	чукӧрті	N;PROL;SG
паськавны	паськӧдчы	V;IMP;SG;2;CAUS;PASS
хор	хорӧс	N;ACC;SG;LGSPEC1
кӧзяйка	кӧзяйкаыс	N;HUM;NOM;SG;PSS3S;LGSPEC1
посводз	посводзӧ	N;NOM;SG;PSS1S
чышъянавны	чышъянасьны	V;PL;2;NEG;PASS
мудзны	мудзӧй	V;PL;1;NEG
орфография	орфографияӧ	N;NOM;SG;PSS1S;LGSPEC1
орны	орӧдча	V;SG;1;PRS;CAUS;PASS
водка	водкаӧн	N;INS;SG;LGSPEC1
кулӧм	кулӧмӧ	N;IN+ALL;SG
виччыны	виччышта	V;SG;1;PRS;LGSPEC_ATTEN
кӧрны	коран	V;SG;2;PRS
видзӧдавны	видзӧдала	V;SG;1;PRS
вуджӧртны	вуджӧртлы	V;IMP;SG;2;LGSPEC_DELIM
майбыр	майбыръясӧй	ADJ;NOM;PL;PSS1S
кадпас	кадпасыслы	N;DAT;SG;PSS3S
уголок	уголок	N;NOM;SG;LGSPEC1
падъян	падъянсьыс	N;IN+ABL;SG;PSS3S
вежавны	вежӧдас	V;SG;3;FUT;CAUS
небӧг	небӧгъястӧ	N;ACC;PL;PSS2S
кынь	кыньӧс	N;HUM;ACC;SG
корӧма	корӧмалы	ADJ;DAT;SG
бант	бант	N;NOM;SG;LGSPEC1
йи	йиас	N;IN+ESS;SG;PSS3S
шифруйтны	шифруйтны	V;NFIN;LGSPEC1
дедъюр	дедъюрсӧ	N;ACC;SG;PSS3S
юны	юсьӧ	V;SG;3;PRS;PASS
бырны	бырлі	V;SG;1;PST;LGSPEC_DELIM
министерство	министерствоыс	N;NOM;SG;PSS3S;LGSPEC1
восьлавны	восьлалан	V;SG;2;FUT
ичӧтик	ичӧтикӧс	ADJ;ACC;SG
мича	мичалы	ADJ;DAT;SG
сюрны	сюрам	V;PL;1;FUT
небзьыны	небзьӧдӧмаӧсь	V;PL;3;PST;CAUS
лёк	лёкъясыс	ADJ;NOM;PL;PSS3S
партук	партуксӧ	N;ACC;SG;PSS3S;LGSPEC1
шуны	шуӧны	V;PL;3;PRS
подоходнӧй	подоходнӧй	ADJ;NOM;SG;LGSPEC1
тэчны	тэчим	V;PL;1;PST
министр	министртӧ	N;HUM;ACC;SG;PSS2S;LGSPEC1
йӧрыш	йӧрышысь	N;IN+ABL;SG
дугӧдны	дугӧдчыны	V;NFIN;PASS
узь	узьлы	N;DAT;SG
творчество	творчествотӧ	N;ACC;SG;PSS2S;LGSPEC1
стажёр	стажер	N;HUM;NOM;SG;LGSPEC1
керка	керкатіыс	N;PROL;SG;PSS3S
снегоход	снегоход	N;NOM;SG;LGSPEC1
судзны	судзан	V;SG;2;PRS
вабергач	вабергачсьыс	N;IN+ABL;SG;PSS3S
бурмӧдӧм	бурмӧдӧмыс	N;NOM;SG;PSS3S
лунйыны	лунъя	V;SG;1;FUT
табйыны	табйӧй	V;PL;1;NEG
канализация	канализация	N;NOM;SG;LGSPEC1
канал	каналъясын	N;IN+ESS;PL;LGSPEC1
вышивайтны	вышивайтӧ	V;SG;3;PRS;LGSPEC1
чукӧртны	чукӧртчам	V;PL;1;PRS;PASS
луд	лудъяс	N;NOM;PL
СМИ	сми-кӧд	N;COM;SG;LGSPEC1
муса	мусаясӧс	ADJ;ACC;PL;PSS1S
прокуратура	прокуратураӧ	N;NOM;SG;PSS1S;LGSPEC1
урӧк	урокыд	N;NOM;SG;PSS2S
зонтик	зонтикӧс	N;ACC;SG;PSS1S;LGSPEC1
потшӧс	потшӧсъясӧ	N;IN+ALL;PL
меліавны	меліалышт	V;IMP;SG;2;LGSPEC_ATTEN
туй	туйястӧ	N;ACC;PL;PSS2S
шоныд	шоныдтӧг	N;SG;LGSPEC_CAR
детсад	детсадйӧн	N;INS;SG;LGSPEC1
вежны	вежлавны	V;ITER;NFIN;LGSPEC_DELIM
ӧдӧб	ӧдӧб	N;NOM;SG
ки-кок	ки-кокнысӧ	N;ACC;SG;PSS3P
няйт	няйтӧдз	N;TERM;SG
боевик	боевикъясыдлы	N;HUM;DAT;PL;PSS2S;LGSPEC1
участок	участокъяслысь	N;ABL;PL;LGSPEC1
снимок	снимокӧс	N;ACC;SG;LGSPEC1
мужик	мужикъясысь	N;HUM;IN+ABL;PL;LGSPEC1
ужнайтны	ужнайт	V;SG;NEG;LGSPEC1
сёрнитны	сёрнитлам	V;PL;1;FUT;LGSPEC_DELIM
охотовед	охотоведӧн	N;HUM;INS;SG;LGSPEC1
герой	геройлы	N;HUM;DAT;SG;LGSPEC1
кӧртымавны	кӧртымалӧны	V;PL;3;PRS
сись	сиськӧн	N;INS;SG
шемӧсмыны	шемӧсмылан	V;SG;2;FUT;LGSPEC_DELIM
кӧдж	кӧджын	N;IN+ESS;SG
баян	баянсӧ	N;ACC;SG;PSS3S;LGSPEC1
сёрмыны	сёрми	V;SG;1;PST
ворсӧм	ворсӧмад	N;IN+ESS;SG;PSS2S
воавны	воӧдчӧны	V;PL;3;PRS;CAUS;PASS
реабилитация	реабилитациялысь	N;ABL;SG;LGSPEC1
вурд	вурдӧс	N;HUM;ACC;SG;PSS1S
гижны	гижам	V;PL;1;FUT
ылавны	ылавлісны	V;PL;3;PST;LGSPEC_DELIM
вугравны	вугрӧдлыны	V;PL;2;NEG;CAUS;LGSPEC_DELIM
урӧстны	урӧстӧ	V;SG;3;PRS
пилипызь	пилипызь	N;NOM;SG;LGSPEC1
аттьӧавны	аттьӧаланныд	V;PL;2;FUT
зона	зонасьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
дорйыны	дорйӧй	V;PL;1;NEG
кабинет	кабинетас	N;IN+ALL;SG;PSS3S;LGSPEC1
мач	мачьяссӧ	N;ACC;PL;PSS3S;LGSPEC1
желайтны	желайтан	V;SG;2;FUT;LGSPEC1
вуджӧдӧм	вуджӧдӧмӧ	N;IN+ALL;SG
бурси	бурсиас	N;IN+ALL;SG;PSS3S
воссьыны	воссяс	V;SG;3;FUT
раскладка	раскладкаӧ	N;NOM;SG;PSS1S;LGSPEC1
дурмыны	дурмӧдчынысӧ	V;ACC;NFIN;PSS3S;CAUS;PASS;LGSPEC1
лысьтысь	лысьтысьлӧн	N;HUM;GEN;SG
ньӧбӧм	ньӧбӧмысь	N;IN+ABL;SG
сӧтны	сотчыв	V;IMP;SG;2;PASS;LGSPEC_DELIM
мавтны	мавтін	V;SG;2;PST
суседка	суседка	N;HUM;NOM;SG;LGSPEC1
митрополит	митрополитӧн	N;HUM;INS;SG;LGSPEC1
шлапсьӧдны	шлапсьӧдны	V;NFIN
кежны	кежӧдны	V;PL;2;NEG;CAUS
перӧ	перӧяс	N;NOM;PL;LGSPEC1
чеччыны	чеччышта	V;SG;1;PRS;LGSPEC_ATTEN
гӧснеч	гӧснечтӧ	N;ACC;SG;PSS2S;LGSPEC1
шуӧм	шуӧмсӧ	N;ACC;SG;PSS3S
вомӧнавны	вомӧнавлӧ	V;SG;3;PRS;LGSPEC_DELIM
новлыны	новлӧдлан	V;SG;2;FUT;CAUS;LGSPEC_DELIM
ылавны	ылӧдлӧй	V;IMP;PL;2;CAUS;LGSPEC_DELIM
нимкодясьны	нимкодясьлім	V;PL;1;PST;LGSPEC_DELIM
юрган	юрганӧ	ADJ;IN+ALL;SG
содтӧд	содтӧдыс	N;NOM;SG;PSS3S
вуштыны	вуштам	V;PL;1;FUT
ёль	ёльлы	N;DAT;SG
учреждение	учреждениеяскӧд	N;COM;PL;LGSPEC1
кыв	кывъясӧс	N;ACC;PL;PSS1S
вуджравны	вуджрасьӧй	V;PL;1;NEG;PASS
барак	баракыс	N;NOM;SG;PSS3S;LGSPEC1
пар	парнас	N;INS;SG;PSS3S
матрас	матрасъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
иеромонах	иеромонах	N;HUM;NOM;SG;LGSPEC1
вок	вокным	N;HUM;NOM;SG;PSS1P
случай	случайясын	N;IN+ESS;PL;LGSPEC1
сапкыны	сапкыны	V;NFIN
юны	юсьы	V;IMP;SG;2;PASS
кывбуралысь	кывбуралысьӧн	N;HUM;INS;SG
газет-журнал	газет-журналъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
ловъя	ловъяӧс	ADJ;ACC;SG
зыньгыны	зыньгыны	V;NFIN
яй	яйтӧг	N;SG;LGSPEC_CAR
няйтчыны	няйтчӧдан	V;SG;2;PRS;CAUS
ов	овас	N;IN+ALL;SG;PSS3S
би	бисӧ	N;ACC;SG;PSS3S
котыртӧм	котыртӧмъясыс	N;NOM;PL;PSS3S
вуджравны	вуджрасьны	V;NFIN;PASS
чуд	чудлӧн	N;HUM;GEN;SG;LGSPEC1
курс	курсӧ	N;IN+ALL;SG;LGSPEC1
такавны	такӧда	V;SG;1;PRS;CAUS
характер	характерсӧ	N;ACC;SG;PSS3S;LGSPEC1
егыр	егырӧ	N;IN+ALL;SG
гӧсть	гӧстьяс	N;HUM;NOM;PL;LGSPEC1
внук	внукъяс	N;HUM;NOM;PL;LGSPEC1
секта	сектасаяс	N;NOM;PL;LGSPEC_ATTR;LGSPEC1
мерайтны	мерайтчан	V;SG;2;FUT;PASS;LGSPEC1
тічкыны	тічкан	V;SG;2;PRS
гуавны	гуалӧй	V;IMP;PL;2
вермыны	вермылі	V;SG;1;PST;LGSPEC_DELIM
корреспондент	корреспондент	N;HUM;NOM;SG;LGSPEC1
чеччавны	чеччаласны	V;PL;3;FUT
восны	воссьы	V;SG;NEG;PASS
югыд	югыдӧдз	N;TERM;SG
сюйӧм	сюйӧмыд	N;NOM;SG;PSS2S
форма	форматом	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
ай	айлӧн	N;HUM;GEN;SG
сиргаг	сиргаг	N;HUM;NOM;SG
домавны	домавны	V;NFIN
концерт	концертлы	N;DAT;SG;LGSPEC1
штука	штукаӧдз	N;TERM;SG;LGSPEC1
видзӧдавны	видзӧдась	V;SG;NEG;PASS
тшӧтшъя	тшӧтшъяяс	N;HUM;NOM;PL
усьӧм	усьӧмысь	N;IN+ABL;SG
висьт	висьтӧ	N;NOM;SG;PSS1S
театр	театрысь	N;HUM;IN+ABL;SG;LGSPEC1
вӧвны	воланныд	V;PL;2;FUT
процент	процентыс	N;NOM;SG;PSS3S;LGSPEC1
вольсавны	вольсав	V;SG;NEG
сир	сиртӧ	N;ACC;SG;PSS2S
стопка	стопкаыс	N;NOM;SG;PSS3S;LGSPEC1
ӧшйыны	ӧшйӧдыштӧма	V;SG;3;PST;CAUS;LGSPEC_ATTEN
гинекология	гинекология	N;NOM;SG;LGSPEC1
удждон	удждоныс	N;NOM;SG;PSS3S
шой	шойӧс	N;ACC;SG;PSS1S
вож	вожсӧ	N;ACC;SG;PSS3S
тэчысь	тэчысьясӧс	N;HUM;ACC;PL;PSS1S
дзиръя	дзиръяысь	N;IN+ABL;SG
частушка	частушкатӧ	N;ACC;SG;PSS2S;LGSPEC1
гӧтырпу	гӧтырпуыскӧд	N;HUM;COM;SG;PSS3S
тшапитны	тшапитчан	V;SG;2;PRS;PASS
чӧр	чӧръясын	N;IN+ESS;PL
пӧдруга	пӧдругаясӧс	N;HUM;ACC;PL
врач	врач	N;HUM;NOM;SG;LGSPEC1
вашмунны	вашмунліс	V;SG;3;PST;LGSPEC_DELIM
медицина	медицинаса	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
кисьтны	кисьтлы	V;SG;NEG;LGSPEC_DELIM
сургыны	сургысь	V;IMP;SG;2;PASS
пычкыны	пычкы	V;IMP;SG;2
видзны	видзӧдлан	V;SG;2;PRS;CAUS;LGSPEC_DELIM
сунгысьны	сунгысис	V;SG;3;PST
терпитны	терпитам	V;PL;1;FUT;LGSPEC1
юктавны	юктасян	V;SG;2;FUT;PASS
прӧститны	прӧстит	V;SG;NEG;LGSPEC1
ноп	нопсьыс	N;IN+ABL;SG;PSS3S
наянмыны	наянмӧны	V;PL;3;PRS
пӧсявны	пӧсьӧдліс	V;SG;3;PST;CAUS;LGSPEC_DELIM
помӧд	помӧдъяссӧ	N;ACC;PL;PSS3S
сирена	сиренаысь	N;IN+ABL;SG;LGSPEC1
чукӧртны	чукӧртласны	V;PL;3;FUT;LGSPEC_DELIM
мог	могъяснас	N;INS;PL;PSS3S
йыв	йыласджык	N;IN+ESS+COMPV;SG;PSS3S
лоны	лолав	V;ITER;SG;NEG;LGSPEC_DELIM
кӧртымалӧм	кӧртымалӧмӧн	N;INS;SG
тулысъя	тулысъясӧ	ADJ;ACC;SG;PSS3S
журналистскӧй	журналистскӧй	ADJ;NOM;SG;LGSPEC1
ляскыны	ляскысян	V;SG;2;PRS;PASS
роз	розъяс	N;NOM;PL
океан	океанын	N;IN+ESS;SG;LGSPEC1
частник	частникъяслы	N;HUM;DAT;PL;LGSPEC1
гижавны	гижӧдны	V;PL;2;NEG;CAUS
мусаник	мусаник	ADJ;NOM;SG
шкатулка	шкатулкасӧ	N;ACC;SG;PSS3S;LGSPEC1
пищаль	пищальыс	N;NOM;SG;PSS3S;LGSPEC1
пасека	пасека	N;NOM;SG;LGSPEC1
четверг	четверг	N;NOM;SG;LGSPEC1
сьӧлӧм	сьӧлӧмсяньджык	N;COMPV;SG;LGSPEC_EGR
автомашина	автомашинаясыс	N;NOM;PL;PSS3S;LGSPEC1
пескыльтчыны	пескыльтчис	V;SG;3;PST
сёрни	сёрниыд	N;NOM;SG;PSS2S
политик	политикъяс	N;HUM;NOM;PL;LGSPEC1
пасьвартны	пасьвартісны	V;PL;3;PST
ньӧв	ньӧвтӧ	N;ACC;SG;PSS2S
сорсьыны	сорсясны	V;PL;3;FUT
еврей	еврей	N;HUM;NOM;SG;LGSPEC1
субӧта	субӧтаӧ	N;NOM;SG;PSS1S;LGSPEC1
юкны	юксям	V;PL;1;FUT;PASS
театр	театрас	N;HUM;IN+ALL;SG;PSS3S;LGSPEC1
оранжерея	оранжерея	N;NOM;SG;LGSPEC1
аддзыны	аддзыны	V;NFIN
отдел	отделнытӧ	N;ACC;SG;PSS2P;LGSPEC1
вердысь	вердысьӧн	N;HUM;INS;SG
замечание	замечаниеяс	N;NOM;PL;LGSPEC1
поручение	поручениесӧ	N;ACC;SG;PSS3S;LGSPEC1
шедны	шедӧдны	V;NFIN;CAUS
война	войнаас	N;IN+ESS;SG;PSS3S;LGSPEC1
моски	москиыд	N;NOM;SG;PSS2S;LGSPEC1
тӧрг	тӧргъястӧг	N;PL;LGSPEC_CAREXT
корсьны	корсяс	V;SG;3;FUT
блокируйтны	блокируйтан	V;SG;2;FUT;LGSPEC1
керны	керсьы	V;SG;NEG;PASS
макет	макет	N;NOM;SG;LGSPEC1
герой	герой	N;HUM;NOM;SG;LGSPEC1
капитальнӧй	капитальнӧй	ADJ;NOM;SG;LGSPEC1
гижавны	гижасим	V;PL;1;PST;PASS
кынмыны	кынмим	V;PL;1;PST
артмӧм	артмӧмкӧд	N;COM;SG
вӧв	вӧвлысь	N;HUM;ABL;SG
пӧжар	пӧжаръясысь	N;IN+ABL;PL;LGSPEC1
вежӧрсявны	вежӧрсялыштіс	V;SG;3;PST;LGSPEC_ATTEN
дубавны	дубалісны	V;PL;3;PST
рукодельница	рукодельницаӧ	N;IN+ALL;SG;LGSPEC1
песӧм	песӧм	N;NOM;SG
ньылавны	ньылалӧй	V;IMP;PL;2
мочалка	мочалкаӧй	N;NOM;SG;PSS1S;LGSPEC1
быдмӧг	быдмӧгъяссӧ	N;ACC;PL;PSS3S
школа	школаясӧс	N;ACC;PL;LGSPEC1
гортса	гортса	ADJ;NOM;SG
архитектор	архитекторӧ	N;HUM;IN+ALL;SG;LGSPEC1
ордым	ордымъяс	N;NOM;PL
шутитны	шутитам	V;PL;1;FUT;LGSPEC1
пыртны	пыртӧй	V;PL;1;NEG
вужля	вужлясӧ	N;ACC;SG;PSS3S
веж	вежам	N;IN+ESS;SG;PSS1S
нига	нигаас	N;IN+ESS;SG;PSS3S;LGSPEC1
нимкодясьны	нимкодясьыштам	V;PL;1;FUT;LGSPEC_ATTEN
дӧрапас	дӧрапаснад	N;INS;SG;PSS2S
лап	лапъясӧн	N;INS;PL;LGSPEC1
кырӧм	кырӧм	N;NOM;SG
дзоля	дзоляясыд	ADJ;NOM;PL;PSS2S
мыжавны	мыжав	V;SG;NEG
гольӧдчыны	гольӧдчис	V;SG;3;PST
керны	керсьӧ	V;SG;3;PRS;PASS
хип-хоп	хип-хоп	N;NOM;SG;LGSPEC1
творческӧй	творческӧйӧн	ADJ;INS;SG;LGSPEC1
вӧчӧм	вӧчӧмыд	N;NOM;SG;PSS2S
библия	библиясӧ	N;ACC;SG;PSS3S;LGSPEC1
лэччавны	лэччӧдны	V;NFIN;CAUS
эксперт	экспертъяскӧд	N;HUM;COM;PL;LGSPEC1
мында	мындаӧс	ADJ;ACC;SG;PSS1S
ужнайтны	ужнайта	V;SG;1;FUT;LGSPEC1
ньывны	ньылыштасны	V;PL;3;FUT;LGSPEC_ATTEN
тур	тур	N;NOM;SG;LGSPEC1
пырӧм	пырӧмӧс	N;ACC;SG
армяна	армяна	N;HUM;NOM;SG;LGSPEC1
отсӧг	отсӧгсьыд	N;IN+ABL;SG;PSS2S
рӧд	рӧдным	N;NOM;SG;PSS1P;LGSPEC1
сенатор	сенаторъяслӧн	N;HUM;GEN;PL;LGSPEC1
кыны	кылам	V;PL;1;PRS;LGSPEC_DELIM
туша	туша	N;NOM;SG;LGSPEC1
пиньтуй	пиньтуйясыс	N;NOM;PL;PSS3S
нуавны	нуаліс	V;SG;3;PST
электрогазосварщик	электрогазосварщикӧс	N;HUM;ACC;SG;LGSPEC1
ыб	ыблысь	N;ABL;SG
ворсӧм	ворсӧмъясыс	N;NOM;PL;PSS3S
партия	партияӧн	N;INS;SG;LGSPEC1
роза	розалысь	N;ABL;SG;LGSPEC1
видзан	видзан	N;NOM;SG
ордйыны	ордйыся	V;SG;1;FUT;PASS
аккумулятор	аккумуляторсӧ	N;ACC;SG;PSS3S;LGSPEC1
пон	понкӧд	N;HUM;COM;SG
килльыны	киллис	V;SG;3;PST
критерий	критерийӧн	N;INS;SG;LGSPEC1
частник	частникъяс	N;HUM;NOM;PL;LGSPEC1
сетка	сеткаӧн	N;INS;SG;LGSPEC1
нюжавны	нюжӧдчас	V;SG;3;FUT;CAUS;PASS
судьба	судьбаын	N;IN+ESS;SG;LGSPEC1
балетмейстер	балетмейстерӧс	N;HUM;ACC;SG;LGSPEC1
рыт	рытысь	N;IN+ABL;SG
регион	регионъясӧ	N;NOM;PL;PSS1S;LGSPEC1
вын	вынас	N;IN+ALL;SG;PSS3S
вож	вожъясас	N;IN+ESS;PL;PSS3S
лапйӧдлыны	лапйӧдлӧ	V;SG;3;PRS
сатшкыны	сатшкам	V;PL;1;FUT
шӧйтны	шӧйтам	V;PL;1;FUT
фирма	фирмаяскӧд	N;COM;PL;LGSPEC1
сьыланкыв	сьыланкывным	N;NOM;SG;PSS1P
роман	романъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
гарйыны	гаръя	V;SG;1;PRS
полк	полклы	N;DAT;SG;LGSPEC1
фриц	фрицъясӧс	N;HUM;ACC;PL;LGSPEC1
тӧв	тӧвсянь	N;SG;LGSPEC_EGR
невельскӧй	невельскӧй	ADJ;NOM;SG;LGSPEC1
локны	локтӧ	V;SG;3;PRS
депутат	депутатлӧн	N;HUM;GEN;SG;LGSPEC1
клуб	клубъясыслӧн	N;GEN;PL;PSS3S;LGSPEC1
персонаж	персонажӧ	N;HUM;IN+ALL;SG;LGSPEC1
канал	каналъяс	N;NOM;PL;LGSPEC1
ломтывны	ломтысисны	V;PL;3;PST;PASS
ылавны	ылав	V;IMP;SG;2
усьӧма	усьӧмаяс	ADJ;NOM;PL
пурт	пуртнас	N;INS;SG;PSS3S
бес	бесъяслы	N;DAT;PL;LGSPEC1
чой	чойсӧ	N;HUM;ACC;SG;PSS3S
символ	символӧдз	N;TERM;SG;LGSPEC1
калькавны	калькӧдлан	V;SG;2;FUT;CAUS;LGSPEC_DELIM
тшапитны	тшапитча	V;SG;1;PRS;PASS
делопроизводитель	делопроизводительӧн	N;INS;SG;LGSPEC1
собрание	собраниеса	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
торк	торкас	N;IN+ALL;SG;PSS3S
вевттьыны	вевттян	V;SG;2;FUT
театр	театрын	N;HUM;IN+ESS;SG;LGSPEC1
сбербанк	сбербанклысь	N;ABL;SG;LGSPEC1
часовня	часовняын	N;IN+ESS;SG;LGSPEC1
директор	директоръясӧс	N;HUM;ACC;PL;LGSPEC1
котыр	котырсянь	N;SG;LGSPEC_EGR
первенство	первенствоыс	N;NOM;SG;PSS3S;LGSPEC1
кулик	кулик	N;HUM;NOM;SG;LGSPEC1
пӧлӧс	пӧлӧсджык	ADJ;NOM+COMPV;SG
верӧс	верӧстӧг	N;HUM;SG;LGSPEC_CAR
старшина	старшинаӧдз	N;HUM;TERM;SG;LGSPEC1
гижӧд	гижӧдъяс	N;NOM;PL
мотоцикл	мотоциклсьыс	N;IN+ABL;SG;PSS3S;LGSPEC1
доналӧм	доналӧмсӧ	N;ACC;SG;PSS3S
тупӧсь	тупӧсьысь	N;IN+ABL;SG
торкысь	торкысьӧс	N;HUM;ACC;SG
овсьыны	овсьӧ	V;SG;3;PRS
сусед	суседъясас	N;HUM;IN+ESS;PL;PSS3S;LGSPEC1
чинны	чинны	V;NFIN
косявлыны	косявлӧны	V;PL;3;PRS
ен	енъясӧс	N;ACC;PL;PSS1S
виж	вижӧд	ADJ;PROL;SG
федеративнӧй	федеративнӧй	ADJ;NOM;SG;LGSPEC1
повзьыны	повзясны	V;PL;3;FUT
троицкӧй	троицкӧй	ADJ;NOM;SG;LGSPEC1
дзескыд	дзескыдджык	ADJ;NOM+COMPV;SG
вунны	вунӧдан	V;SG;2;PRS;CAUS
синмавны	синмасьны	V;NFIN;PASS
нывбаба	нывбаба	N;HUM;NOM;SG
пӧльыштӧм	пӧльыштӧмысь	ADJ;IN+ABL;SG
гӧтравны	гӧтраси	V;SG;1;PST;PASS
празднуйтны	празднуйтам	V;PL;1;PRS;LGSPEC1
тыдалана	тыдаланаӧн	ADJ;INS;SG
доз	дозйӧ	N;IN+ALL;SG
тувкыны	тувкӧді	V;SG;3;PST;CAUS
нимкодьмыны	нимкодьмӧдіс	V;SG;3;PST;CAUS
пединститут	пединститут	N;NOM;SG;LGSPEC1
поколение	поколениеӧс	N;ACC;SG;LGSPEC1
имитны	имит	V;SG;NEG
рекорд	рекорд	N;NOM;SG;LGSPEC1
бласлӧвитны	бласлӧвитӧ	V;SG;3;PRS;LGSPEC1
медалысь	медалысьӧс	N;HUM;ACC;SG
нӧдкыв	нӧдкывъяс	N;NOM;PL
ай	ай	N;HUM;NOM;SG
нуавны	нуӧдлі	V;SG;1;PST;CAUS;LGSPEC_DELIM
пӧрны	пӧрӧдан	V;SG;2;PRS;CAUS
кынйир	кынйирас	N;IN+ESS;SG;PSS3S
майшӧдлыны	майшӧдлан	V;SG;2;PRS
колана	колананас	ADJ;INS;SG;PSS3S
шахта	шахтаясын	N;IN+ESS;PL;LGSPEC1
торкавны	торкалӧ	V;SG;3;PRS
велавны	велала	V;SG;1;FUT
подъёмнӧй	подъёмнӧйяс	ADJ;NOM;PL;LGSPEC1
пытшкӧс	пытшкӧсад	N;IN+ALL;SG;PSS2S
гран-при	гран-при	N;NOM;SG;LGSPEC1
личкыны	личкысь	V;SG;NEG;PASS
начальник	начальникӧ	N;HUM;IN+ALL;SG;LGSPEC1
ассоциация	ассоциацияӧ	N;IN+ALL;SG;LGSPEC1
ловру	ловруӧн	N;INS;SG
гранит	гранитысь	N;IN+ABL;SG;LGSPEC1
шузьыны	шузьы	V;SG;NEG
янӧдана	янӧданаыс	ADJ;NOM;SG;PSS3S
югӧр	югӧртӧг	N;SG;LGSPEC_CAR
шуавны	шуалам	V;PL;1;FUT
водзсасьны	водзсасьӧны	V;PL;3;PRS
вурны	вурсян	V;SG;2;FUT;PASS
нимпас	нимпасын	N;IN+ESS;SG
сорны	сор	V;IMP;SG;2
автомобильнӧй	автомобильнӧй	ADJ;NOM;SG;LGSPEC1
электрикавны	электрикалӧ	V;SG;3;PRS;LGSPEC1
мятеж	мятеж	N;NOM;SG;LGSPEC1
пыж	пыжас	N;IN+ALL;SG;PSS3S
кит	китӧ	N;HUM;IN+ALL;SG
ансамбль	ансамбльнас	N;INS;SG;PSS3S;LGSPEC1
виччыны	виччысь	V;IMP;SG;2;PASS
кыпӧдчӧм	кыпӧдчӧм	N;NOM;SG
каттьыны	каттьысисны	V;PL;3;PST;PASS
мездыны	мезда	V;SG;1;PRS
пышъявны	пышъялін	V;SG;2;PST
тутсыны	тутсан	V;SG;2;PRS
лоны	лолалі	V;ITER;SG;1;PST;LGSPEC_DELIM
келавны	келав	V;SG;NEG
финн-йӧгра	финн-йӧграыс	ADJ;NOM;SG;PSS3S
бабук	бабукӧн	N;HUM;INS;SG;LGSPEC1
нацист	нацистӧн	N;HUM;INS;SG;LGSPEC1
реагент	реагент	N;NOM;SG;LGSPEC1
пищаль	пищальӧн	N;INS;SG;LGSPEC1
салдат	салдатъясыс	N;HUM;NOM;PL;PSS3S;LGSPEC1
общественник	общественникӧс	N;HUM;ACC;SG;LGSPEC1
индеец	индеецъяс	N;HUM;NOM;PL;LGSPEC1
пуны	пусьы	V;SG;NEG;PASS
кыны	кыласны	V;PL;3;FUT;LGSPEC_DELIM
юркар	юркарсаяс	N;NOM;PL;LGSPEC_ATTR
гусявны	гусявлас	V;SG;3;FUT;LGSPEC_DELIM
йӧй	йӧйӧсь	ADJ;PL
сьӧлӧм	сьӧлӧмад	N;IN+ALL;SG;PSS2S
тӧждысьысь	тӧждысьысьясӧс	ADJ;ACC;PL
шмоньлив	шмоньлив	ADJ;NOM;SG
кывтыд	кывтыд	N;NOM;SG
блог	блогӧс	N;ACC;SG;LGSPEC1
вӧйпны	вӧйпӧдіс	V;SG;3;PST;CAUS
вир-яй	вир-яйнымӧс	N;ACC;SG;PSS1P
организация	организациясӧ	N;ACC;SG;PSS3S;LGSPEC1
пырны	пырыштны	V;PL;2;NEG;LGSPEC_ATTEN
повесьт	повесьтас	N;IN+ESS;SG;PSS3S;LGSPEC1
ен	енсянь	N;SG;LGSPEC_EGR
частушка	частушка	N;NOM;SG;LGSPEC1
войпель	войпельӧс	N;ACC;SG
корпоратив	корпоратив	N;NOM;SG;LGSPEC1
багатыр	багатыркӧд	N;HUM;COM;SG;LGSPEC1
падмыны	падмӧдан	V;SG;2;PRS;CAUS
кӧмкот	кӧмкотаныс	N;IN+ALL;SG;PSS3P
иславны	исласян	V;SG;2;FUT;PASS
ызӧбтыны	ызӧбтісны	V;PL;3;PST
вугыр	вугырӧс	N;ACC;SG
сопка	сопкаясын	N;IN+ESS;PL;LGSPEC1
сертификат	сертификатъяс	N;NOM;PL;LGSPEC1
вежласяна	вежласянаӧн	ADJ;INS;SG
специалист	специалистъяссӧ	N;HUM;ACC;PL;PSS3S;LGSPEC1
воськовтны	воськовтлыны	V;PL;2;NEG;LGSPEC_DELIM
вичмыны	вичмӧда	V;SG;1;PRS;CAUS
кӧин	кӧинкӧд	N;HUM;COM;SG
кежны	кежлас	V;SG;3;FUT;LGSPEC_DELIM
отечество	отечество	N;NOM;SG;LGSPEC1
рӧм	рӧмлӧн	N;GEN;SG
донка	донкасӧ	N;ACC;SG;PSS3S;LGSPEC1
мыськалӧм	мыськалӧмыс	N;NOM;SG;PSS3S
медик	медиклы	N;HUM;DAT;SG;LGSPEC1
тыл	тылад	N;IN+ESS;SG;PSS2S;LGSPEC1
войвыв	войвывсаяслысь	N;ABL;PL;LGSPEC_ATTR
адрес	адресъяссӧ	N;ACC;PL;PSS3S;LGSPEC1
бӧрыньтны	бӧрыньтчан	V;SG;2;FUT;PASS
зывӧктыны	зывӧктыны	V;PL;2;NEG
лыа	лыаысь	N;IN+ABL;SG
шуны	шулам	V;PL;1;FUT;LGSPEC_DELIM
кыпавны	кыпӧдлам	V;PL;1;PRS;CAUS;LGSPEC_DELIM
госэкзамен	госэкзаменъяс	N;NOM;PL;LGSPEC1
язычник	язычникыс	N;HUM;NOM;SG;PSS3S;LGSPEC1
сёян	сёянъястӧ	N;ACC;PL;PSS2S
гӧрӧд	городсянь	N;SG;LGSPEC_EGR
лифт	лифтъяслӧн	N;GEN;PL;LGSPEC1
турнир	турнир	N;NOM;SG;LGSPEC1
телеграмма	телеграммаӧс	N;ACC;SG;LGSPEC1
контролёр	контролёрӧс	N;HUM;ACC;SG;PSS1S;LGSPEC1
торйӧдӧм	торйӧдӧм	N;NOM;SG
сер	серъяслӧн	N;GEN;PL
тыдавны	тыдалӧны	V;PL;3;PRS
господь	господьыд	N;NOM;SG;PSS2S;LGSPEC1
тыдовтны	тыдовтчылӧны	V;PL;3;PRS;PASS;LGSPEC_DELIM
лун	лунӧ	N;IN+ALL;SG
технология	технологияӧ	N;IN+ALL;SG;LGSPEC1
система	системаса	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
зарадитны	зарадиті	V;SG;3;PST;LGSPEC1
электромонтёр	электромонтёрӧс	N;HUM;ACC;SG;LGSPEC1
котыртчӧм	котыртчӧм	N;NOM;SG
диктуйтны	диктуйті	V;SG;1;PST;LGSPEC1
бӧръя	бӧръяяссӧ	ADJ;ACC;PL;PSS3S
режиссёравны	режиссёравны	V;PL;2;NEG;LGSPEC1
тывъявны	тывъясьлӧны	V;PL;3;PRS;PASS;LGSPEC_DELIM
вура-варакывны	вура-варакылӧ	V;SG;3;PRS
лыдпас	лыдпасӧн	N;INS;SG
быдтас	быдтасыслӧн	N;HUM;GEN;SG;PSS3S
сӧс	сӧстӧмнас	ADJ;INS;SG;LGSPEC_ATTR;PSS3S
типография	типографияӧ	N;IN+ALL;SG;LGSPEC1
внук	внукъястӧ	N;HUM;ACC;PL;PSS2S;LGSPEC1
