эрямс	эряфстост	V.PTCP;IN+ABL;SG;PSS3P;PST;INTR
стирьшаба	стирьшабатнень	N;HUM;GEN;DEF;PL
грамота	грамотас	N;IN+ALL;SG;LGSPEC1
штраф	штрафнень	N;GEN;DEF;PL;LGSPEC1
чиновник	чиновникне	N;HUM;NOM;PL;PSS1S;LGSPEC1
пеедемс	пеедель	V;SG;3;RMT;INTR
правила	правилац	N;NOM;SG;PSS3S;LGSPEC1
кулемс	кулихтень	V;AC2S;SG;1;TR
танка	танкась	N;NOM;DEF;SG;LGSPEC1
поляк	полякне	N;HUM;NOM;PL;PSS1S;LGSPEC1
соревнования	соревнованиянь	N;GEN;SG;LGSPEC1
язык	язык	N;NOM;SG;LGSPEC1
антология	антологиясь	N;NOM;DEF;SG;LGSPEC1
издания	изданияда	N;ABL;SG;LGSPEC1
алуце	алуце	ADJ
программа	программаста	N;IN+ABL;SG;LGSPEC1
отвечамс	отвечаль	V;SG;3;RMT;TR;LGSPEC1
ферма	ферматне	N;NOM;PL;PSS2S;LGSPEC1
строямс	строяк	V;IMP;SG;2;TR;LGSPEC1
эрямс	эряфтсы	V;AC3S;SG;3;CAUS
ули	улись	N;NOM;DEF;SG
снимандамс	снимандафтольхть	V;PL;3;RMT;CAUS;LGSPEC1
вал	валдот	N;ABL;SG;PSS2S
мошенник	мошенниксь	N;HUM;NOM;DEF;SG;LGSPEC1
учемс	учемс	V;NFIN;TR
варма	варматнень	N;GEN;DEF;PL
виензамс	виенза	V;NEG;INTR
тиемс	тиевсть	V;AC3;PL;2;TR;PASS
положения	положениянзон	N;GEN;PL;PSS3S;LGSPEC1
смола	смолань	N;GEN;SG;LGSPEC1
фотография	фотографияса	N;IN+ESS;SG;LGSPEC1
аськолкс	аськолксонзон	N;GEN;PL;PSS3S
охота	охотась	N;NOM;DEF;SG;LGSPEC1
эштерь	эштерь	ADJ
водопровод	водопроводса	N;IN+ESS;SG;LGSPEC1
заказамс	заказакшнесть	V;AC3;PL;2;TR;LGSPEC1
сквозняк	сквознякнень	N;GEN;PL;PSS1S;LGSPEC1
тунда	тундать	N;GEN;DEF;SG
кстиндамс	кстиндакшнят	V;SG;2;TR
колендема	колендемань	N;GEN;SG
род	родсь	N;NOM;DEF;SG;LGSPEC1
кулемс	кулендеви	V;SG;3;TR;PASS
рота	ротать	N;GEN;DEF;SG;LGSPEC1
вай	вайть	N;NOM;PL
профилактика	профилактикац	N;NOM;SG;PSS3S;LGSPEC1
парикмахер	парикмахерхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
сюролда	сюролдань	N;GEN;SG
памятник	памятникне	N;NOM;PL;PSS1S;LGSPEC1
сельме	сельмосонк	N;IN+ESS;SG;PSS1P
арьсемс	арьсефокс	V.PTCP;TRANS;SG;PST;TR
выставка	выставкаста	N;IN+ABL;SG;LGSPEC1
вольер	вольерхнень	N;GEN;DEF;PL;LGSPEC1
крандаз	крандазс	N;IN+ALL;SG
кстиндамс	кстиндань	V;SG;1;PST;TR
прдамс	прдасть	V;AC3;PL;2;TR
книга	книганза	N;NOM;PL;PSS3S;LGSPEC1
илядомс	иляда	V;NEG;INTR
тише	тишетнень	N;GEN;PL;PSS2S
лувома	лувоматнень	N;GEN;DEF;PL
этаж	этажти	N;DAT;DEF;SG;LGSPEC1
мистика	мистикац	N;NOM;SG;PSS3S;LGSPEC1
мярьгомс	мярьги	V;SG;3;TR
сотомс	сотфтомс	V;NFIN;CAUS
пуре	пуреть	N;GEN;DEF;SG
правила	правилатненди	N;DAT;DEF;PL;LGSPEC1
птицефабрика	птицефабрикась	N;NOM;DEF;SG;LGSPEC1
скрипка	скрипка	N;NOM;SG;LGSPEC1
братства	братствась	N;NOM;DEF;SG;LGSPEC1
работа	работасот	N;IN+ESS;SG;PSS2S;LGSPEC1
анокши	анокшить	N;GEN;DEF;SG
канды	кандыеньке	N;GEN;SG;LGSPEC_AMP
судендамс	судендафт	V;NEG;CAUS;LGSPEC1
васта	вастце	N;NOM;SG;PSS2S
ару	аруван	ADJ;PROL;SG;PSS1S
келу	келус	N;IN+ALL;SG
экскурсия	экскурсияньке	N;NOM;SG;PSS1P;LGSPEC1
автомашина	автомашинаньке	N;NOM;SG;PSS1P;LGSPEC1
судендамс	судендафтольхть	V.PTCP;NOM;PL;3;PST;TR;LGSPEC1
лотка	лотка	N;NOM;SG
понамс	понаса	V;AC3S;SG;1;TR
вест	весса	N;IN+ESS;SG;LGSPEC1
секция	секциянь	N;GEN;SG;LGSPEC1
эвондамс	эвондакшнихть	V;PL;3;INTR
залп	залп	N;NOM;SG;LGSPEC1
варжамс	варжась	V;SG;3;PST;TR
ферма	фермат	N;NOM;PL;LGSPEC1
вальмя	вальмада	N;ABL;SG
вий	вийса	N;IN+ESS;SG
грамма	граммань	N;GEN;SG;LGSPEC1
вер	вер	N;NOM;SG
морамс	моразевсть	V;AC3;PL;2;TR
тонафты	тонафтыснонды	N;HUM;DAT;SG;PSS3P
потма	потмостонза	N;IN+ABL;SG;PSS3S
православнай	православнайти	ADJ;DAT;DEF;SG;LGSPEC1
вешфкс	вешфксу	N;AT+ALL;SG
чемпион	чемпиононь	N;HUM;GEN;SG;LGSPEC1
керомс	керфти	V.PTCP;DAT;DEF;SG;PST;TR
книга	книгадост	N;ABL;SG;PSS3P;LGSPEC1
урма	урматне	N;NOM;PL;PSS2S
шаба	шабазе	N;HUM;NOM;SG;PSS1S
критик	критикокс	N;HUM;TRANS;SG;LGSPEC1
коллегия	коллегияв	N;AT+ALL;SG;LGSPEC1
пяльдемс	пяльдихть	V;PL;3;TR
раса	расать	N;GEN;DEF;SG;LGSPEC1
шаромс	шарондыхть	V;PL;3;INTR
модамарь	модамарьда	N;ABL;SG
эй	эйть	N;GEN;DEF;SG
помощник	помощниконь	N;HUM;GEN;SG;LGSPEC1
сборнай	сборнайснон	N;GEN;SG;PSS3P;LGSPEC1
кемокстамс	кемокстафат	V.PTCP;SG;2;PST;TR
конференция	конференцияньконь	N;GEN;SG;PSS1P;LGSPEC1
кярьмодемс	кярьмодель	V;SG;3;RMT;INTR
премьер-лига	премьер-лигати	N;DAT;DEF;SG;LGSPEC1
заместитель	заместитель	N;HUM;NOM;SG;LGSPEC1
декан	декаттне	N;HUM;NOM;DEF;PL;LGSPEC1
зона	зонакс	N;TRANS;SG;LGSPEC1
курендамс	курендай	V;SG;3;TR;LGSPEC1
интернет	интернетфтома	N;PRIV;SG;LGSPEC1
слой	слойти	N;DAT;DEF;SG;LGSPEC1
график	график	N;NOM;SG;LGSPEC1
шапамомс	шапамсь	V;SG;3;PST;INTR
пар	парат	N;SG;2
кундамс	кундаль	V;SG;3;RMT;TR
новоселья	новосельять	N;GEN;DEF;SG;LGSPEC1
медицина	медицинаснон	N;GEN;SG;PSS3P;LGSPEC1
фракция	фракциянц	N;GEN;SG;PSS3S;LGSPEC1
раса	расада	N;ABL;SG;LGSPEC1
экономика	экономикатне	N;NOM;PL;PSS2S;LGSPEC1
катастрофа	катастрофати	N;DAT;DEF;SG;LGSPEC1
тяльме	тяльмоти	N;DAT;DEF;SG
тиф	тифонц	N;GEN;SG;PSS3S;LGSPEC1
повомс	повонды	V;SG;3;INTR
труппа	труппати	N;DAT;DEF;SG;LGSPEC1
тол	толста	N;IN+ABL;SG
прибавамс	прибавасть	V;AC3;IMP;PL;2;TR;LGSPEC1
этнодискотека	этнодискотекатнень	N;GEN;PL;PSS2S;LGSPEC1
симомс	симоль	V;SG;3;RMT;TR
кев	кевоц	N;NOM;SG;PSS3S
пульзямс	пульзяфтолеме	V.PTCP;NOM;PL;1;PST;INTR
страница	страницашка	N;COMPV;SG;LGSPEC1
коммунальщик	коммунальщикненди	N;HUM;DAT;DEF;PL;LGSPEC1
паця	пацятнень	N;GEN;PL;PSS2S
психолог	психологонь	N;HUM;GEN;SG;LGSPEC1
пиле	пилесон	N;IN+ESS;SG;PSS1S
кафе	кафетненди	N;DAT;PL;PSS2S;LGSPEC1
содай	содайхнень	N;HUM;GEN;PL;PSS1S
тапарямс	тапарясть	V;PL;3;PST;TR
рецензия	рецензиятне	N;NOM;PL;PSS2S;LGSPEC1
суффикс	суффикссь	N;NOM;DEF;SG;LGSPEC1
кярьмодемс	кярьмотькшнетяда	V;PL;2;INTR
пиле	пиленте	N;NOM;SG;PSS2P
конференция	конференцияда	N;ABL;SG;LGSPEC1
кабель	кабеленди	N;DAT;SG;LGSPEC1
сярятьф	сярятьфне	N;NOM;PL;PSS1S
заведующай	заведующай	N;HUM;LGSPEC1
васьфнемс	васьфнян	V;SG;1;TR
поезд	поездоцка	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
панемс	паньфтольхть	V;PL;3;RMT;CAUS
гайморит	гаймориту	N;AT+ALL;SG;LGSPEC1
баяр	баяр	N;HUM;NOM;SG;LGSPEC1
шнамс	шнафтыхть	V;PL;3;CAUS
антихрист	антихристта	N;ABL;SG;LGSPEC1
дыня	дынятка	N;NOM;PL;LGSPEC_AMP;LGSPEC1
повестка	повесткась	N;NOM;DEF;SG;LGSPEC1
приём	приёпнень	N;GEN;PL;PSS1S;LGSPEC1
обследования	обследованияда	N;ABL;SG;LGSPEC1
птицефабрика	птицефабрикатне	N;NOM;PL;PSS2S;LGSPEC1
мода	модань	N;GEN;SG
эрямс	эрявкшнесть	V;AC3;IMP;PL;2;INTR;PASS
аськолкс	аськолкст	N;NOM;PL
вайгяльбе	вайгяльбетне	N;NOM;DEF;PL
ламолгодомс	ламолгодсь	V;SG;3;PST;INTR
управляющай	управляющайть	N;HUM;NOM;PL;LGSPEC1
руця	руцясь	N;NOM;DEF;SG
фонд	фонтт	N;NOM;PL;LGSPEC1
ладямс	ладяви	V;SG;3;TR;PASS;LGSPEC1
трагедия	трагедиясь	N;NOM;DEF;SG;LGSPEC1
марсекшнемс	марсекшнесть	V;PL;3;PST;INTR
шарфтомс	шарфтольхть	V;PL;3;RMT;TR
классик	классиксь	N;HUM;NOM;DEF;SG;LGSPEC1
нупонь	нупотнень	N;GEN;DEF;PL
продукта	продуктатнень	N;GEN;PL;PSS2S;LGSPEC1
нюрьхтямс	нюрьхтятама	V;PL;1;TR
ужяльдемс	ужяльдень	V;SG;1;PST;TR
мэр	мэрти	N;HUM;DAT;DEF;SG;LGSPEC1
националист	националисттнень	N;HUM;GEN;DEF;PL;LGSPEC1
режим	режимса	N;IN+ESS;SG;LGSPEC1
повомс	повондсть	V;AC3;IMP;PL;2;INTR
модель	модель	N;LGSPEC1
машинка	машинкатнень	N;GEN;PL;PSS2S;LGSPEC1
кирдемс	кирдеви	V;SG;3;TR;PASS
лица	лицатненди	N;DAT;DEF;PL;LGSPEC1
идея	идеят	N;NOM;PL;LGSPEC1
перямс	перя	V;NEG;TR
кайгомс	кайгост	V;OPT;PL;3;INTR
шоряфкс	шоряфкста	N;ABL;SG
лозунг	лозунг	N;NOM;SG;LGSPEC1
образования	образованиять	N;GEN;DEF;SG;LGSPEC1
боец	боецонза	N;HUM;NOM;PL;PSS3S;LGSPEC1
парши	паршиснон	N;GEN;SG;PSS3P
профессор	профессорхнень	N;HUM;GEN;DEF;PL;LGSPEC1
помещик	помещиконь	N;HUM;GEN;SG;LGSPEC1
васта	вастоц	N;NOM;SG;PSS3S
государства	государстваньке	N;NOM;SG;PSS1P;LGSPEC1
корпорация	корпорациять	N;GEN;DEF;SG;LGSPEC1
оборона	оборонать	N;GEN;DEF;SG;LGSPEC1
печкомс	печкфт	V;NEG;CAUS
воспитатель	воспитательсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
лездомс	лездсть	V;PL;3;PST;INTR
шине	шинеть	N;NOM;PL
общества	обществатнень	N;GEN;PL;PSS2S;LGSPEC1
путомс	путфтомс	V;NFIN;CAUS
казендемс	казенди	V;SG;3;TR
атмосфера	атмосферать	N;GEN;DEF;SG;LGSPEC1
ляень	ляеньке	ADJ;LGSPEC_AMP
исследования	исследованияснон	N;GEN;SG;PSS3P;LGSPEC1
тарваз	тарвазонц	N;GEN;SG;PSS3S
миф	мифан	N;SG;1;LGSPEC1
стамс	сташендыхть	V;PL;3;TR
кяскав	кяскавть	N;GEN;DEF;SG
пона	понать	N;GEN;DEF;SG
полоса	полосатнень	N;GEN;DEF;PL;LGSPEC1
якшам	якшапненди	N;DAT;PL;PSS1S
кяше	кяшенди	N;DAT;SG
эрямс	эряк	V;IMP;SG;2;INTR
саламс	салаван	V;SG;1;TR;PASS
аля	алят	N;HUM;NOM;PL
печкомс	печк	V;NEG;TR
союз	союзсна	N;NOM;SG;PSS3P;LGSPEC1
ладямс	ладядязь	V;AC2S;PL;3;TR;LGSPEC1
явомс	явить	V;AC3;SG;2;TR
чётнай	чётнайхть	ADJ;NOM;PL;LGSPEC1
функция	функция	N;NOM;SG;LGSPEC1
сувамс	сувафнень	V.PTCP;GEN;PL;PSS1S;PST;INTR
князь	княсьне	N;HUM;NOM;PL;PSS1S;LGSPEC1
дисциплина	дисциплинаса	N;IN+ESS;SG;LGSPEC1
дивизия	дивизияв	N;AT+ALL;SG;LGSPEC1
карьхцямс	карьхцявихть	V;PL;3;TR;PASS
концепция	концепциятне	N;NOM;PL;PSS2S;LGSPEC1
мярьгомс	мярьгонди	V;SG;3;TR
собрания	собранияти	N;DAT;DEF;SG;LGSPEC1
конкурс	конкурснень	N;GEN;DEF;PL;LGSPEC1
рецензия	рецензия	N;NOM;SG;LGSPEC1
директор	директороньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
кавалер	кавалерсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
грамота	грамотазе	N;NOM;SG;PSS1S;LGSPEC1
грешнай	грешнай	ADJ;LGSPEC1
вирь	вирь	N
венгерка	венгерка	N;HUM;NOM;SG;LGSPEC1
максомс	максоволень	V;SG;1;RMT;TR;PASS
уемс	уйфне	V.PTCP;NOM;PL;PSS1S;PST;INTR
СПК	спк-кс	N;TRANS;SG;LGSPEC1
пианист	пианистоньке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
ила	илатне	N;NOM;DEF;PL
таколдомс	таколдоме	V;PL;1;PST;INTR
потребитель	потребительхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
термин	термиттнень	N;GEN;DEF;PL;LGSPEC1
шоряфкс	шоряфксть	N;GEN;DEF;SG
гвоздика	гвоздика	N;NOM;SG;LGSPEC1
синагога	синагогасост	N;IN+ESS;SG;PSS3P;LGSPEC1
сёрмадомс	сермадовольхть	V;PL;3;RMT;TR;PASS
христианства	христианствань	N;GEN;SG;LGSPEC1
анокламс	аноклакшнесть	V;AC3;IMP;PL;2;TR
шобда	шобдати	ADJ;DAT;DEF;SG
казьфт	казьфтольхть	N;PL;3;PST
картина	картина	N;NOM;SG;LGSPEC1
монтажник	монтажникне	N;HUM;NOM;PL;PSS1S;LGSPEC1
арьсемс	арьсезеват	V;SG;2;TR
венемомс	венемкшнемс	V;NFIN;INTR
слушания	слушаният	N;NOM;PL;LGSPEC1
колония	колониятнень	N;GEN;PL;PSS2S;LGSPEC1
учредитель	учредительхне	N;HUM;NOM;DEF;PL;LGSPEC1
нармонь	нармонель	N;HUM;SG;3;PST
керомс	керфсь	V.PTCP;NOM;DEF;SG;PST;TR
нянечка	нянечкась	N;HUM;NOM;DEF;SG;LGSPEC1
цярахман	цярахманть	N;GEN;DEF;SG
профсоюз	профсоюзонь	N;GEN;SG;LGSPEC1
издания	изданияньконь	N;GEN;SG;PSS1P;LGSPEC1
уемс	уель	V;SG;3;RMT;INTR
ункс	унксонтень	N;GEN;SG;PSS2P
юкстамс	юкстасак	V;AC3S;SG;2;TR
алтарь	алтарть	N;NOM;PL;LGSPEC1
боеприпас	боеприпаснень	N;GEN;DEF;PL;LGSPEC1
перямс	перяви	V;SG;3;TR;PASS
посёлка	поселканьке	N;NOM;SG;PSS1P;LGSPEC1
эпоха	эпохась	N;NOM;DEF;SG;LGSPEC1
проектировщик	проектировщиконь	N;HUM;GEN;SG;LGSPEC1
трактор	тракторда	N;HUM;ABL;SG;LGSPEC1
управляющай	управляющайхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
акшептомс	акшептомс	V;NFIN;TR
волна	волнань	N;GEN;SG;LGSPEC1
армия	армияса	N;IN+ESS;SG;LGSPEC1
ве	венза	N;NOM;PL;PSS3S
крга	крганте	N;NOM;SG;PSS2P
парши	паршинкса	N;CAUSV;SG
совет	советонза	N;NOM;PL;PSS3S;LGSPEC1
куя	куять	ADJ;GEN;DEF;SG
кядьлапш	кядьлапшсонза	N;IN+ESS;SG;PSS3S
пролив	пролив	N;NOM;SG;LGSPEC1
васта	вастова	N;PROL;SG
система	системава	N;PROL;SG;LGSPEC1
аздомс	азфне	V.PTCP;NOM;DEF;PL;PST;INTR
шумбра	шумбрати	ADJ;DAT;DEF;SG
трудендамс	трудендан	V;SG;1;INTR;LGSPEC1
пшкядемс	пшкядеме	V;PL;1;PST;TR
строямс	строять	V;SG;2;PST;TR;LGSPEC1
зверь	зверь	N;HUM;NOM;SG;LGSPEC1
работник	работникта	N;HUM;ABL;SG;LGSPEC1
щамс	щафтоде	V;PL;2;PST;CAUS
пеже	пеженте	N;NOM;SG;PSS2P
пуня	пунятнень	N;GEN;PL;PSS2S
мордва	мордва	N;HUM;NOM;SG;LGSPEC1
полга	полконьконь	N;GEN;SG;PSS1P
кадомс	кадондсть	V;AC3;IMP;PL;2;TR
содамс	содайтьке	V;AC3;SG;LGSPEC_AMP;2;TR
вера	верат	N;NOM;PL;LGSPEC1
илядомс	иляткшнесть	V;AC3;IMP;PL;2;INTR
содамс	содафта	V.PTCP;ABL;SG;PST;TR
мазомомс	мазоми	V;SG;3;INTR
котф	котфне	N;NOM;PL;PSS1S
путомс	путовсть	V;AC3;IMP;PL;2;TR;PASS
идея	идеякс	N;TRANS;SG;LGSPEC1
станция	станцияв	N;AT+ALL;SG;LGSPEC1
вииямс	виияфтовсь	V;SG;3;PST;CAUS;PASS
дисциплина	дисциплинанза	N;NOM;PL;PSS3S;LGSPEC1
пине	пинень	N;HUM;GEN;SG
удмурт	удмурттне	N;HUM;NOM;PL;PSS2S
пизем	пиземонзон	N;GEN;PL;PSS3S
садик	садику	N;AT+ALL;SG;LGSPEC1
сота	сотатнень	N;GEN;PL;PSS2S;LGSPEC1
кадомс	кадонь	V;SG;1;PST;TR
кайгомс	кайгозевсь	V;SG;3;PST;INTR
партия	партиятненьге	N;GEN;PL;LGSPEC_AMP;PSS2S;LGSPEC1
панемс	панесть	V;AC3;IMP;PL;2;TR
валгомс	валгоме	V;PL;1;PST;INTR
установка	установкатнень	N;GEN;PL;PSS2S;LGSPEC1
вирь	вирьснон	N;GEN;SG;PSS3P
идея	идеятне	N;NOM;DEF;PL;LGSPEC1
мокшава	мокшавась	N;HUM;NOM;DEF;SG
секта	сектать	N;GEN;DEF;SG;LGSPEC1
кельгомс	кельгован	V;SG;1;TR;PASS
бренд	брендонц	N;GEN;SG;PSS3S;LGSPEC1
волонтёр	волонтерда	N;HUM;ABL;SG;LGSPEC1
племянник	племянниконзон	N;HUM;GEN;PL;PSS3S;LGSPEC1
тяште	тяште	N;NOM;SG
щамс	щамасть	V;AC1;PL;2;TR
практика	практикат	N;NOM;PL;LGSPEC1
лядомс	лядсть	V;PL;3;PST;INTR
события	событияти	N;DAT;DEF;SG;LGSPEC1
лидер	лидерхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
бактерия	бактерияда	N;ABL;SG;LGSPEC1
немец	немецнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
мярьгомс	мярьговоль	V;SG;3;RMT;TR;PASS
срадомс	срафтови	V;SG;3;CAUS;PASS
сод	сотсь	N;NOM;DEF;SG
мече	мечеть	N;HUM;GEN;DEF;SG
крематорий	крематорийти	N;DAT;DEF;SG;LGSPEC1
идея	идеятнень	N;GEN;PL;PSS2S;LGSPEC1
коллега	коллегакс	N;HUM;TRANS;SG;LGSPEC1
разрешения	разрешениянь	N;GEN;SG;LGSPEC1
кирдемс	кирдеда	V;IMP;PL;2;TR
ваны	ваныхнень	N;GEN;PL;PSS1S
курсовой	курсовой	N;NOM;SG;LGSPEC1
благодать	благодатенц	N;GEN;SG;PSS3S;LGSPEC1
спортсменка	спортсменкатненди	N;HUM;DAT;DEF;PL;LGSPEC1
лиемс	лифтезе	V;AC3S;SG;3;CAUS
прябала	прябаланц	N;GEN;SG;PSS3S
копорь	копорьге	N;NOM;SG;LGSPEC_AMP
пульзямс	пульзяфста	V.PTCP;IN+ABL;SG;PST;INTR
единоличник	единоличникне	N;HUM;NOM;DEF;PL;LGSPEC1
эвондамс	эвондафтсть	V;AC3;IMP;PL;2;CAUS
поступамс	поступамань	V;AC1;SG;3;INTR;LGSPEC1
сельмоведь	сельмоветтнень	N;GEN;PL;PSS2S
пайгарма	пайгармань	N;GEN;SG
аськолкс	аськолксоньке	N;GEN;SG;LGSPEC_AMP
качества	качестванзон	N;GEN;PL;PSS3S;LGSPEC1
тарваз	тарвазкс	N;TRANS;SG
газ	газфтома	N;PRIV;SG;LGSPEC1
дефицит	дефицит	N;NOM;SG;LGSPEC1
наряжамс	наряжань	V;SG;1;PST;TR;LGSPEC1
благоустройства	благоустройствац	N;NOM;SG;PSS3S;LGSPEC1
ведява	ведявась	N;NOM;DEF;SG
май	маень	N;GEN;SG;LGSPEC1
средства	средстванди	N;DAT;SG;LGSPEC1
райисполком	райисполкомонь	N;GEN;SG;LGSPEC1
программист	программисттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
щамс	щафтольхть	V;PL;3;RMT;CAUS
интеллигенция	интеллигенция	N;NOM;SG;LGSPEC1
кучка	кучкать	N;GEN;DEF;SG
уре	урентень	N;HUM;GEN;SG;PSS2P
пропаганда	пропагандаснонды	N;DAT;SG;PSS3P;LGSPEC1
морамс	морафтольхть	V.PTCP;NOM;PL;3;PST;TR
мокшава	мокшаватнень	N;HUM;GEN;PL;PSS2S
часть	частеньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
корабль	корабльхне	N;NOM;DEF;PL;LGSPEC1
академик	академикть	N;HUM;GEN;DEF;SG;LGSPEC1
лопадемс	лопадемс	V;NFIN;TR;LGSPEC1
армия	армиятнень	N;GEN;PL;PSS2S;LGSPEC1
скорость	скоростть	N;GEN;DEF;SG;LGSPEC1
симомс	симондевихть	V;PL;3;TR;PASS
седямс	седяфста	V.PTCP;IN+ABL;SG;PST;TR
цильф	цильфсь	N;NOM;DEF;SG
васьфнемс	васьфнесайне	V;AC3P;SG;1;TR
юкстамс	юкстасть	V;PL;3;PST;TR
стака	стаканц	ADJ;GEN;SG;PSS3S
свидетельства	свидетельстватне	N;NOM;DEF;PL;LGSPEC1
большевик	большевикнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
пиже	пиже	N;NOM;SG
поликлиника	поликлиникась	N;NOM;DEF;SG;LGSPEC1
партнёр	партнерсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
агрегат	агрегаттнень	N;GEN;PL;PSS2S;LGSPEC1
телевидения	телевиденияста	N;IN+ABL;SG;LGSPEC1
ве	вец	N;NOM;SG;PSS3S
потя	потя	N;NOM;SG
моряк	морякть	N;HUM;GEN;DEF;SG;LGSPEC1
жилет	жилетка	N;PROL;SG;LGSPEC1
эрямс	эряфсонк	V.PTCP;IN+ESS;SG;PSS1P;PST;INTR
проба	пробань	N;GEN;SG;LGSPEC1
эйндамс	эйндамс	V;NFIN;INTR
учредитель	учредителенза	N;HUM;NOM;PL;PSS3S;LGSPEC1
монография	монография	N;NOM;SG;LGSPEC1
завхоз	завхозонц	N;HUM;GEN;SG;PSS3S;LGSPEC1
сан	саттама	N;PL;1
путомс	путоме	V;PL;1;PST;TR
баба	бабаньконь	N;GEN;SG;PSS1P;LGSPEC1
интернат	интернатть	N;GEN;DEF;SG;LGSPEC1
ярхцамс	ярхцайхть	V;PL;3;TR
залп	залпне	N;NOM;PL;PSS1S;LGSPEC1
люпштама	люпштама	N;NOM;SG
пуштомс	пуштфсь	V.PTCP;NOM;DEF;SG;PST;TR
фотография	фотографиянтень	N;GEN;SG;PSS2P;LGSPEC1
лаподемс	лаподсть	V;PL;3;PST;TR
типография	типографияньке	N;NOM;SG;PSS1P;LGSPEC1
пеель	пеелькс	N;TRANS;SG
цебярь	цебяренди	ADJ;DAT;SG
стамс	стафтсть	V;AC3;PL;2;CAUS
крепость	крепостсь	N;NOM;DEF;SG;LGSPEC1
эряй	эряйснонды	N;HUM;DAT;SG;PSS3P
партия	партиятненьге	N;GEN;DEF;PL;LGSPEC_AMP;LGSPEC1
председатель	председателень	N;HUM;GEN;SG;LGSPEC1
недляши	недляшить	N;GEN;DEF;SG;LGSPEC1
кундамс	кундафт	V;NEG;CAUS
кадомс	кадондов	V;NEG;TR;PASS
секция	секциязост	N;IN+ALL;SG;PSS3P;LGSPEC1
шарфтомс	шарфтан	V;SG;1;TR
стирьшаба	стирьшабати	N;HUM;DAT;DEF;SG
мордовка	мордовкада	N;HUM;ABL;SG;LGSPEC1
скрипка	скрипкась	N;NOM;DEF;SG;LGSPEC1
предложения	предложениять	N;GEN;DEF;SG;LGSPEC1
салмокс	салмокст	N;NOM;PL
ктмордамс	ктмордасамазь	V;AC1;PL;3;TR
звена	звенать	N;GEN;DEF;SG;LGSPEC1
кинотеатра	кинотеатраса	N;IN+ESS;SG;LGSPEC1
кев	кеву	N;AT+ALL;SG
пере	перезонк	N;IN+ALL;SG;PSS1P
пьеса	пьесанзонды	N;DAT;PL;PSS3S;LGSPEC1
мотив	мотифт	N;NOM;PL;LGSPEC1
фойе	фойесонза	N;IN+ESS;SG;PSS3S;LGSPEC1
морси	морсихненди	N;DAT;PL;PSS1S
тии	тииснон	N;HUM;GEN;SG;PSS3P
ёнь	ёнезе	N;NOM;SG;PSS1S
резидент	резидентонзонды	N;HUM;DAT;PL;PSS3S;LGSPEC1
страна	странасост	N;IN+ESS;SG;PSS3P;LGSPEC1
живой	живоян	ADJ;SG;1;LGSPEC1
таштомомс	таштомсть	V;PL;3;PST;INTR
веле	веленьке	N;GEN;SG;LGSPEC_AMP
мак	мака	N;PROL;SG;LGSPEC1
вал	валхненьге	N;GEN;DEF;PL;LGSPEC_AMP
шавомс	шавондомс	V;NFIN;TR
сташендомс	сташендсть	V;PL;3;PST;TR
пиламс	пиламс	V;NFIN;TR;LGSPEC1
сельме	сельмосонга	N;IN+ESS;SG;LGSPEC_AMP;PSS1S
шутендамс	шутендамс	V;NFIN;INTR;LGSPEC1
трактор	трактороньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
пря	пряснонды	N;DAT;SG;PSS3P
кяшемс	кяшенди	V;SG;3;TR
орден	орденца	N;IN+ESS;SG;LGSPEC1
ункс	унксонь	N;GEN;SG
студентка	студенткатнень	N;HUM;GEN;DEF;PL;LGSPEC1
сяськома	сяськоматне	N;NOM;DEF;PL
отряд	отряттне	N;NOM;DEF;PL;LGSPEC1
кемокстамс	кемокстафста	V.PTCP;IN+ABL;SG;PST;TR
венгра	венгратненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
кабель	кабельхнень	N;GEN;DEF;PL;LGSPEC1
пиле	пилезонт	N;IN+ALL;SG;PSS2P
матрамс	матрамс	V;NFIN;TR
фотография	фотографиясь	N;NOM;DEF;SG;LGSPEC1
мучендамс	мучендамс	V;NFIN;TR;LGSPEC1
рекордсменка	рекордсменкать	N;HUM;GEN;DEF;SG;LGSPEC1
приз	призда	N;ABL;SG;LGSPEC1
ширь	ширенкса	N;CAUSV;SG
пря	прява	N;PROL;SG
пяле	пялестонза	N;IN+ABL;SG;PSS3S
синдемс	синдьса	V;AC3S;SG;1;TR
тур	турда	N;HUM;ABL;SG
явомс	явихть	V;PL;3;TR
тонадомс	тонадовсть	V;AC3;PL;2;INTR;PASS
васта	васттнень	N;GEN;PL;PSS2S
трактор	тракторонза	N;HUM;NOM;PL;PSS3S;LGSPEC1
кабинет	кабинетозонт	N;IN+ALL;SG;PSS2P;LGSPEC1
гражданин	гражданинць	N;HUM;NOM;DEF;SG;LGSPEC1
дача	дачас	N;IN+ALL;SG;LGSPEC1
тердемс	тертьфтолеме	V.PTCP;NOM;PL;1;PST;TR
гуляндамс	гуляндакшнеме	V;PL;1;PST;INTR;LGSPEC1
учредитель	учредительти	N;HUM;DAT;DEF;SG;LGSPEC1
психолог	психологсь	N;HUM;NOM;DEF;SG;LGSPEC1
васедемс	васедемань	V;AC1;SG;3;INTR
снимандамс	снимандафт	V;NEG;CAUS;LGSPEC1
кедь	кеденди	N;DAT;SG
самоуправления	самоуправленияснон	N;GEN;SG;PSS3P;LGSPEC1
атказамс	атказась	V;SG;3;PST;INTR;LGSPEC1
сайт	сайттнень	N;GEN;DEF;PL;LGSPEC1
каштаз	каштазцень	N;GEN;SG;PSS2S
врач	врачне	N;HUM;NOM;DEF;PL;LGSPEC1
мелодия	мелодиянь	N;GEN;SG;LGSPEC1
явомс	явфтама	V.PTCP;PL;1;PST;TR
кафедра	кафедра	N;NOM;SG;LGSPEC1
футболист	футболисттненди	N;HUM;DAT;DEF;PL;LGSPEC1
тиемс	тиевода	V;IMP;PL;2;TR;PASS
кргамс	кргава	V;NEG;TR;PASS
юмафкс	юмафксонзон	N;GEN;PL;PSS3S
медпункт	медпункттнень	N;GEN;DEF;PL;LGSPEC1
ки	кизон	N;HUM;IN+ALL;SG;PSS1S
призыв	призыв	N;NOM;SG;LGSPEC1
погода	погодада	N;ABL;SG;LGSPEC1
мелодия	мелодияснон	N;GEN;SG;PSS3P;LGSPEC1
абондомс	абонда	V;NEG;INTR
пря	пряцка	N;NOM;SG;LGSPEC_AMP;PSS3S
обеспечения	обеспечениясост	N;IN+ESS;SG;PSS3P;LGSPEC1
стих	стихта	N;ABL;SG;LGSPEC1
ляды	лядысь	ADJ;NOM;DEF;SG
кепотькс	кепотькста	N;ABL;SG
черновик	черновикста	N;IN+ABL;SG;LGSPEC1
стирьшаба	стирьшабат	N;HUM;NOM;PL
ушедомс	ушедови	V;SG;3;TR;PASS
лозунг	лозункнень	N;GEN;PL;PSS1S;LGSPEC1
сяськома	сяськоманьке	N;GEN;SG;LGSPEC_AMP
бюджет	бюджеттненди	N;DAT;DEF;PL;LGSPEC1
планирования	планированиянь	N;GEN;SG;LGSPEC1
программа	программатне	N;NOM;DEF;PL;LGSPEC1
молемс	мольфтевсь	V;SG;3;PST;CAUS;PASS
шуму	шумуван	ADJ;PROL;SG;PSS1S
самолёт	самолетоц	N;NOM;SG;PSS3S;LGSPEC1
инвалид	инвалидонь	N;HUM;GEN;SG;LGSPEC1
вал	валоньконь	N;GEN;SG;PSS1P
веща	вещать	N;GEN;DEF;SG;LGSPEC1
яндава	яндавать	N;GEN;DEF;SG;LGSPEC1
ломань	ломанезти	N;DAT;SG;PSS1S
вешфкс	вешфксонза	N;NOM;PL;PSS3S
инголдамс	инголдасть	V;PL;3;PST;TR
газета	газетаса	N;IN+ESS;SG;LGSPEC1
секретариат	секретариату	N;AT+ALL;SG;LGSPEC1
вай	вайти	N;DAT;DEF;SG
богатырь	богатырева	N;HUM;PROL;SG;LGSPEC1
приветствия	приветствияснон	N;GEN;SG;PSS3P;LGSPEC1
гала-концерт	гала-концертс	N;IN+ALL;SG;LGSPEC1
ополчения	ополчениясь	N;NOM;DEF;SG;LGSPEC1
сатирик	сатирикнень	N;HUM;GEN;DEF;PL;LGSPEC1
наставник	наставникоц	N;HUM;NOM;SG;PSS3S;LGSPEC1
оборудовандамс	оборудовандамс	V;NFIN;TR;LGSPEC1
кедь	кеттнень	N;GEN;DEF;PL
архитектура	архитектуранц	N;GEN;SG;PSS3S;LGSPEC1
партнёр	партнеронц	N;HUM;GEN;SG;PSS3S;LGSPEC1
киремс	кирьфтама	V.PTCP;PL;1;PST;INTR
фото	фототь	N;GEN;DEF;SG;LGSPEC1
традиция	традицияснон	N;GEN;SG;PSS3P;LGSPEC1
келемомс	келемихть	V;PL;3;INTR
пеже	пежентень	N;GEN;SG;PSS2P
совет	советсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
шаба	шабатне	N;HUM;NOM;DEF;PL
стенд	стенттнень	N;GEN;PL;PSS2S;LGSPEC1
прябала	прябалафтома	N;PRIV;SG
потямс	потяса	V;AC3S;SG;1;TR
весялгодомс	весялгоды	V;SG;3;INTR;LGSPEC1
пуромкс	пуромксоньке	N;GEN;SG;LGSPEC_AMP
здравоохранения	здравоохранениянц	N;GEN;SG;PSS3S;LGSPEC1
интереснай	интереснайдонга	ADJ;ABL;SG;LGSPEC_AMP;PSS1S;LGSPEC1
снимандамс	снимандась	V;SG;3;PST;TR;LGSPEC1
мода	модатненди	N;DAT;PL;PSS2S
коськомс	коськсть	V;AC3;PL;2;INTR
заботендамс	заботендатада	V;PL;2;INTR;LGSPEC1
байдек	байдекне	N;NOM;PL;PSS1S
воспитания	воспитаниясна	N;NOM;SG;PSS3P;LGSPEC1
медсестра	медсестраста	N;HUM;IN+ABL;SG;LGSPEC1
фотография	фотография	N;NOM;SG;LGSPEC1
машина	машинатненди	N;DAT;PL;PSS2S;LGSPEC1
кайгомс	кайгозевсть	V;PL;3;PST;INTR
пинге	пингонди	N;DAT;SG
сумань	суманенц	N;GEN;SG;PSS3S
книга	книгазти	N;DAT;SG;PSS1S;LGSPEC1
дипломатия	дипломатиянь	N;GEN;SG;LGSPEC1
панар	панархнень	N;GEN;DEF;PL
знамя	знамятнень	N;GEN;PL;PSS2S;LGSPEC1
мярьгомс	мярьгондян	V;SG;1;TR
пикник	пикникса	N;IN+ESS;SG;LGSPEC1
цифра	цифратне	N;NOM;DEF;PL;LGSPEC1
пристав	пристафненди	N;HUM;DAT;DEF;PL;LGSPEC1
объект	объектт	N;NOM;PL;LGSPEC1
литературовед	литературоветт	N;HUM;NOM;PL;LGSPEC1
лувома	лувомазень	N;GEN;SG;PSS1S
дума	думань	N;GEN;SG;LGSPEC1
мярьгомс	мярьгсть	V;PL;3;PST;TR
получамс	получави	V;SG;3;INTR;PASS;LGSPEC1
кячказ	кячказсь	N;NOM;DEF;SG
вадемс	ваде	V;NEG;TR
ярхцамс	ярхцаме	V;PL;1;PST;TR
счётт	счетстонза	N;IN+ABL;SG;PSS3S;LGSPEC1
пря	прянтенди	N;DAT;SG;PSS2P
симомс	симовсь	V;SG;3;PST;TR;PASS
шачемс	шачфтса	V;AC3S;SG;1;CAUS
молемс	мольфтевсть	V;AC3;PL;2;CAUS;PASS
перяфкс	перяфксса	N;IN+ESS;SG
нацпроект	нацпроектса	N;IN+ESS;SG;LGSPEC1
медсестра	медсестрати	N;HUM;DAT;DEF;SG;LGSPEC1
манеж	манеж	N;NOM;SG;LGSPEC1
состав	составснон	N;GEN;SG;PSS3P;LGSPEC1
повомс	повфти	V.PTCP;DAT;DEF;SG;PST;INTR
стройотряд	стройотряттне	N;NOM;PL;PSS2S;LGSPEC1
выступандамс	выступандакшни	V;SG;3;INTR;LGSPEC1
пря	пряснон	N;GEN;SG;PSS3P
форточка	форточказонк	N;IN+ALL;SG;PSS1P;LGSPEC1
копорь	копорезень	N;GEN;SG;PSS1S
интернат	интернату	N;AT+ALL;SG;LGSPEC1
шарьхкодемс	шарьхкотькшнесть	V;AC3;IMP;PL;2;TR
секретарь	секретарь	N;HUM;LGSPEC1
туркс	туркст	N;NOM;PL
курсант	курсантонь	N;HUM;GEN;SG;LGSPEC1
маятамс	маятан	V;SG;1;INTR;LGSPEC1
содамс	содадязь	V;AC2P;TR
вяти	вятиснон	N;HUM;GEN;SG;PSS3P
тутмадемс	тутмадить	V;AC3;SG;2;TR
винтовка	винтовканьке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
система	системась	N;NOM;DEF;SG;LGSPEC1
подполковник	подполковникокс	N;HUM;TRANS;SG;LGSPEC1
заметка	заметкасонза	N;IN+ESS;SG;PSS3S;LGSPEC1
нажядемс	нажятькшнихть	V;PL;3;INTR
якшам	якшам	N;NOM;SG
казань	казанти	ADJ;DAT;DEF;SG;LGSPEC1
абитуриент	абитуриенттненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
кузенця	кузенцяста	N;IN+ABL;SG;LGSPEC1
стихотворения	стихотворениятнень	N;GEN;DEF;PL;LGSPEC1
отвечамс	отвечай	V;SG;3;TR;LGSPEC1
кизефтемс	кизефтемс	V;NFIN;TR
лямбе	лямбода	N;ABL;SG
конфликт	конфликтса	N;IN+ESS;SG;LGSPEC1
шарфтомс	шарфтоль	V;SG;3;RMT;TR
ки	кицень	N;GEN;SG;PSS2S
пряруця	пряруцятнень	N;GEN;DEF;PL
ювадемс	юватькшнесь	V;SG;3;PST;TR
селькор	селькорхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
атя	атякс	N;HUM;TRANS;SG
вельмомс	вельмофнень	V.PTCP;GEN;DEF;PL;PST;INTR
васькамс	васькафтозень	V;AC3P;SG;3;CAUS
круг	крукт	N;NOM;PL;LGSPEC1
строямс	строясть	V;AC3;IMP;PL;2;TR;LGSPEC1
экономист	экономистсь	N;HUM;NOM;DEF;SG;LGSPEC1
факт	фактти	N;DAT;DEF;SG;LGSPEC1
свидетельства	свидетельства	N;NOM;SG;LGSPEC1
путомс	путовсть	V;PL;3;PST;TR;PASS
телефон	телефонцта	N;IN+ABL;SG;LGSPEC1
тур	турхнень	N;HUM;GEN;PL;PSS1S
няфтемс	няфтьфт	V.PTCP;NOM;PL;PST;TR
гразямс	гразясть	V;AC3;PL;2;TR;LGSPEC1
куку	куку	N;HUM;NOM;SG
энциклопедия	энциклопедиятненди	N;DAT;DEF;PL;LGSPEC1
балкон	балкону	N;AT+ALL;SG;LGSPEC1
веща	вещанзон	N;GEN;PL;PSS3S;LGSPEC1
комамс	команда	V;NEG;INTR
тонадомс	тонафттада	V;PL;2;CAUS
лапамс	лапайхть	V;PL;3;INTR
кирьфтамс	кирьфтавихть	V;PL;3;TR;PASS
дотация	дотация	N;NOM;SG;LGSPEC1
кеподемс	кепотьфне	V.PTCP;NOM;PL;PSS1S;PST;TR
заметка	заметказе	N;NOM;SG;PSS1S;LGSPEC1
клуб	клубсонк	N;IN+ESS;SG;PSS1P;LGSPEC1
путёвка	путевкас	N;IN+ALL;SG;LGSPEC1
нешке	нешкт	N;NOM;PL
сфера	сфератнень	N;GEN;PL;PSS2S;LGSPEC1
порядка	порядкаса	N;IN+ESS;SG;LGSPEC1
благосостояния	благосостояниянц	N;GEN;SG;PSS3S;LGSPEC1
учемс	учтядязь	V;AC2;PL;3;TR
орден	ордеттнень	N;GEN;PL;PSS2S;LGSPEC1
дотация	дотациятнень	N;GEN;DEF;PL;LGSPEC1
тише	тишева	N;PROL;SG
искусствовед	искусствоведсь	N;HUM;NOM;DEF;SG;LGSPEC1
преступления	преступлениясь	N;NOM;DEF;SG;LGSPEC1
медсестра	медсестрат	N;HUM;NOM;PL;LGSPEC1
сатира	сатирац	N;NOM;SG;PSS3S;LGSPEC1
шаба	шабаньконь	N;HUM;GEN;SG;PSS1P
секта	сектакс	N;TRANS;SG;LGSPEC1
номинация	номинацияс	N;IN+ALL;SG;LGSPEC1
обряд	обрядсна	N;NOM;SG;PSS3P;LGSPEC1
веле	веленте	N;NOM;SG;PSS2P
эрямс	эряфста	V.PTCP;IN+ABL;SG;PST;INTR
юкстамс	юкстафтольхть	V.PTCP;NOM;PL;3;PST;TR
поэма	поэманзон	N;GEN;PL;PSS3S;LGSPEC1
строямс	строятада	V;PL;2;TR;LGSPEC1
актив	актифне	N;NOM;DEF;PL;LGSPEC1
бюджет	бюджету	N;AT+ALL;SG;LGSPEC1
партнёр	партнероньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
самс	салеме	V;PL;1;RMT;INTR
счётт	счетста	N;IN+ABL;SG;LGSPEC1
удома	удомацка	N;NOM;SG;LGSPEC_AMP;PSS3S
водопровод	водопровод	N;NOM;SG;LGSPEC1
презентация	презентацият	N;NOM;PL;LGSPEC1
сельмодемс	сельмодихть	V;PL;3;INTR
карьхцямс	карьхцяфт	V;NEG;CAUS
куломс	кулофсь	V.PTCP;NOM;DEF;SG;PST;INTR
сестра	сестра	N;HUM;NOM;SG;LGSPEC1
мошенник	мошенникокс	N;HUM;TRANS;SG;LGSPEC1
раздел	разделхнень	N;GEN;DEF;PL;LGSPEC1
воспитания	воспитаниясост	N;IN+ESS;SG;PSS3P;LGSPEC1
эвондамс	эвондафт	V.PTCP;NOM;PL;PST;INTR
коллега	коллегатненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
сеель	сеельхне	N;HUM;NOM;DEF;PL
экскурсия	экскурсиятнень	N;GEN;PL;PSS2S;LGSPEC1
азомс	азсь	V;SG;3;PST;TR
риск	риска	N;PROL;SG;LGSPEC1
арьсемс	арьсефти	V.PTCP;DAT;DEF;SG;PST;TR
пленнай	пленнайть	N;HUM;GEN;DEF;SG;LGSPEC1
срадомс	срады	V;SG;3;INTR
щамс	щафтф	V.PTCP;PST;CAUS
сяли	сялиень	N;GEN;SG
белок	белоксь	N;NOM;DEF;SG;LGSPEC1
танка	танканьконь	N;GEN;SG;PSS1P;LGSPEC1
нумс	нумань	V;AC1;SG;3;TR
ёнь	енезост	N;IN+ALL;SG;PSS3P
дивизия	дивизиясь	N;NOM;DEF;SG;LGSPEC1
конференция	конференцияти	N;DAT;DEF;SG;LGSPEC1
мече	мечень	N;HUM;GEN;SG
учемс	учендомс	V;NFIN;TR
фотография	фотографиянь	N;GEN;SG;LGSPEC1
актив	активсь	N;NOM;DEF;SG;LGSPEC1
налхкомс	налхколь	V;SG;3;RMT;TR
панжемс	панжевсть	V;AC3;IMP;PL;2;TR;PASS
сяськомс	сяськф	V.PTCP;PST;TR
выступандамс	выступандань	V;SG;1;PST;INTR;LGSPEC1
получамс	получайне	V;AC3;SG;1;INTR;LGSPEC1
участница	участницанцты	N;HUM;DAT;SG;PSS3S;LGSPEC1
пяше	пяше	N;NOM;SG
категория	категориятнень	N;GEN;PL;PSS2S;LGSPEC1
нупонь	нупонь	N
чемпион	чемпиононьке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
сеель	сееленьке	N;HUM;GEN;SG;LGSPEC_AMP
слава	славац	N;NOM;SG;PSS3S;LGSPEC1
спартакиада	спартакиадатнень	N;GEN;DEF;PL;LGSPEC1
коммуникация	коммуникациянзон	N;GEN;PL;PSS3S;LGSPEC1
цебярь	цебярьхне	ADJ;NOM;PL;PSS1S
ки	киснон	N;HUM;GEN;SG;PSS3P
мучендамс	мучендан	V;SG;1;TR;LGSPEC1
коськомс	коськоль	V;SG;3;RMT;INTR
шумордамс	шумордаса	V;AC3S;SG;1;TR
мече	мечеть	N;HUM;NOM;PL
цебярь	цебярьдонза	ADJ;ABL;SG;PSS3S
дискотека	дискотекатне	N;NOM;DEF;PL;LGSPEC1
издания	изданияса	N;IN+ESS;SG;LGSPEC1
мир	мирхнень	N;GEN;PL;PSS1S;LGSPEC1
содержания	содержанияц	N;NOM;SG;PSS3S;LGSPEC1
пизелкс	пизелкснень	N;GEN;DEF;PL
танкист	танкистокс	N;HUM;TRANS;SG;LGSPEC1
молемс	молихтьке	V;PL;LGSPEC_AMP;3;INTR
копордамс	копордат	V;SG;2;TR
права	правати	N;DAT;DEF;SG;LGSPEC1
шачемс	шачфне	V.PTCP;NOM;PL;PSS1S;PST;INTR
кореец	кореецт	N;HUM;NOM;PL;LGSPEC1
тува	тувотненди	N;HUM;DAT;DEF;PL
атяката	атякатонь	N;HUM;GEN;SG
национальнай	национальнайть	ADJ;NOM;PL;LGSPEC1
абитуриент	абитуриенттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
приоритет	приоритетонзон	N;GEN;PL;PSS3S;LGSPEC1
тиемс	тиендель	V;SG;3;RMT;TR
кужа	кужа	N;NOM;SG
правления	правленияв	N;AT+ALL;SG;LGSPEC1
проспект	проспекту	N;AT+ALL;SG;LGSPEC1
эрзява	эрзяватнень	N;HUM;GEN;DEF;PL
отделения	отделенияцка	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
таргоземс	таргозьфне	V.PTCP;NOM;DEF;PL;PST;INTR
погода	погодаста	N;IN+ABL;SG;LGSPEC1
пуре	пуреда	N;ABL;SG
агрегат	агрегаттненди	N;DAT;DEF;PL;LGSPEC1
сельгомс	сельгонь	V;SG;1;PST;TR
уксус	уксус	N;NOM;SG;LGSPEC1
спортсменка	спортсменкать	N;HUM;GEN;DEF;SG;LGSPEC1
узел	узелхнень	N;GEN;PL;PSS1S;LGSPEC1
удомс	удонь	V;SG;1;PST;TR
группа	группатненди	N;DAT;PL;PSS2S;LGSPEC1
произведения	произведениядот	N;ABL;SG;PSS2S;LGSPEC1
националист	националисттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
пустыня	пустынява	N;PROL;SG;LGSPEC1
сярятькстомс	сярятькстат	V;SG;2;INTR
рана	ранатнень	N;GEN;PL;PSS2S;LGSPEC1
этнос	этносне	N;NOM;PL;PSS1S;LGSPEC1
корма	корматнень	N;GEN;PL;PSS2S
озамс	озай	V;SG;3;INTR
пехотинец	пехотинецсь	N;HUM;NOM;DEF;SG;LGSPEC1
шаромс	шарфтоза	V;OPT;SG;3;CAUS
ёжуши	ёжушинц	N;GEN;SG;PSS3S
дисциплина	дисциплинанц	N;GEN;SG;PSS3S;LGSPEC1
мультфильма	мультфильмат	N;NOM;PL;LGSPEC1
кошардомс	кошардсайть	V;AC3P;SG;2;TR
каркс	карксне	N;NOM;PL;PSS1S
статус	статуссь	N;NOM;DEF;SG;LGSPEC1
воспитания	воспитаниязон	N;IN+ALL;SG;PSS1S;LGSPEC1
качества	качестватне	N;NOM;DEF;PL;LGSPEC1
газета	газетаньконь	N;GEN;SG;PSS1P;LGSPEC1
труд	трудфтома	N;PRIV;SG;LGSPEC1
морай	мораень	ADJ;GEN;SG
иеромонах	иеромонах	N;HUM;NOM;SG;LGSPEC1
спортсменка	спортсменканьконди	N;HUM;DAT;SG;PSS1P;LGSPEC1
творчества	творчествасонза	N;IN+ESS;SG;PSS3S;LGSPEC1
цемент	цементть	N;GEN;DEF;SG;LGSPEC1
аэропорт	аэропортоньке	N;NOM;SG;PSS1P;LGSPEC1
явомс	явондови	V;SG;3;TR;PASS
кабинет	кабинету	N;AT+ALL;SG;LGSPEC1
коськомс	коськи	V;SG;3;INTR
аноклай	аноклай	N;HUM
произведения	произведениянкса	N;CAUSV;SG;LGSPEC1
заявления	заявленият	N;NOM;PL;LGSPEC1
полга	полкненди	N;DAT;PL;PSS1S
комсомол	комсомолсь	N;NOM;DEF;SG;LGSPEC1
синдемс	синдсь	V;SG;3;PST;TR
кочкай	кочкайсна	N;HUM;NOM;SG;PSS3P
рдаз	рдазти	N;DAT;DEF;SG
конфессия	конфессият	N;NOM;PL;LGSPEC1
танка	танкать	N;GEN;DEF;SG;LGSPEC1
сёрмадомс	серматкшнефт	V.PTCP;NOM;PL;PST;TR
касыкс	касыксонте	N;NOM;SG;PSS2P
сргоземс	сргозьфтян	V;SG;1;CAUS
ки	киста	N;HUM;IN+ABL;SG
типография	типографиясна	N;NOM;SG;PSS3P;LGSPEC1
казендемс	казендян	V;SG;1;TR
вииямс	виияфттама	V.PTCP;NOM;PL;1;PST;INTR
рейд	рейдсь	N;NOM;DEF;SG;LGSPEC1
происшествия	происшествиятнень	N;GEN;PL;PSS2S;LGSPEC1
уемс	уихть	V;PL;3;INTR
бактерия	бактериятне	N;NOM;DEF;PL;LGSPEC1
парши	паршихненди	N;DAT;DEF;PL
лампа	лампаса	N;IN+ESS;SG;LGSPEC1
самс	сашендода	V;IMP;PL;2;INTR
якстерьгодомс	якстерьгодсть	V;PL;3;PST;INTR
филолог	филолокне	N;HUM;NOM;DEF;PL;LGSPEC1
счёт	счетста	N;IN+ABL;SG;LGSPEC1
пеже	пежец	N;NOM;SG;PSS3S
мокшэрзя	мокшэрзятнень	N;HUM;GEN;PL;PSS2S
экономист	экономистокс	N;HUM;TRANS;SG;LGSPEC1
псалом	псалопт	N;NOM;PL;LGSPEC1
луви	лувихненди	N;HUM;DAT;PL;PSS1S
профсоюз	профсоюсненди	N;DAT;DEF;PL;LGSPEC1
алкоголь	алкоголь	N;LGSPEC1
аппарат	аппаратоньке	N;NOM;SG;PSS1P;LGSPEC1
праздник	праздниконзонды	N;DAT;PL;PSS3S;LGSPEC1
кооператив	кооператифне	N;NOM;PL;PSS1S;LGSPEC1
композиция	композициятнень	N;GEN;PL;PSS2S;LGSPEC1
исполнитель	исполнитель	N;HUM;NOM;SG;LGSPEC1
самолёт	самолеттост	N;ABL;SG;PSS3P;LGSPEC1
тюштемс	тюшти	V;SG;3;TR
поздравляндамс	поздравляндасайне	V;AC3P;SG;1;TR;LGSPEC1
ходок	ходокне	N;HUM;NOM;PL;PSS1S;LGSPEC1
дистанция	дистанциятненди	N;DAT;DEF;PL;LGSPEC1
учемс	учендсть	V;PL;3;PST;TR
церемония	церемонияц	N;NOM;SG;PSS3S;LGSPEC1
тише	тишетне	N;NOM;PL;PSS2S
машты	маштыста	ADJ;IN+ABL;SG
лефкс	лефксонзон	N;HUM;GEN;PL;PSS3S
творчества	творчествазень	N;GEN;SG;PSS1S;LGSPEC1
шарфтомс	шарфтофтада	V.PTCP;PL;2;PST;TR
щамс	щафтсть	V;PL;3;PST;CAUS
ворьгодемс	ворьготькшнень	V;SG;1;PST;TR
библиотека	библиотекатне	N;NOM;PL;PSS2S;LGSPEC1
писатель	писателенц	N;HUM;GEN;SG;PSS3S;LGSPEC1
арьсемс	арьсефта	V.PTCP;ABL;SG;PST;TR
басня	баснят	N;NOM;PL;LGSPEC1
наступления	наступления	N;NOM;SG;LGSPEC1
заседания	заседаниява	N;PROL;SG;LGSPEC1
юмамс	юмафтфт	V.PTCP;NOM;PL;PST;CAUS
традиция	традицияс	N;IN+ALL;SG;LGSPEC1
куломс	кулофстонга	V.PTCP;IN+ABL;SG;LGSPEC_AMP;PST;INTR
сосед	сосед	N;HUM;NOM;SG;LGSPEC1
орудия	орудиятнень	N;GEN;PL;PSS2S;LGSPEC1
он	отт	N;NOM;PL
информация	информация	N;NOM;SG;LGSPEC1
оборона	оборонаньке	N;NOM;SG;PSS1P;LGSPEC1
он	онцот	N;IN+ESS;SG;PSS2S
сценка	сценканц	N;GEN;SG;PSS3S;LGSPEC1
сайт	сайтт	N;NOM;PL;LGSPEC1
тревога	тревогас	N;IN+ALL;SG;LGSPEC1
тяряфтомс	тяряфтса	V;AC3S;SG;1;TR
ктмордамс	ктмордамс	V;NFIN;TR
таколдомс	таколфтомс	V;NFIN;CAUS
пяльдемс	пяльде	V;NEG;TR
кордон	кордонца	N;IN+ESS;SG;LGSPEC1
писатель	писательхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
заявления	заявленияса	N;IN+ESS;SG;LGSPEC1
резерва	резерватнень	N;GEN;PL;PSS2S;LGSPEC1
фотография	фотографият	N;NOM;PL;LGSPEC1
почта	почтас	N;IN+ALL;SG;LGSPEC1
рейтинг	рейтингснон	N;GEN;SG;PSS3P;LGSPEC1
вадяв	вадявста	ADJ;IN+ABL;SG
пакш	пакшт	N;NOM;PL
ресурс	ресурсне	N;NOM;DEF;PL;LGSPEC1
валгомс	валгсть	V;AC3;PL;2;INTR
пограничник	пограничникне	N;HUM;NOM;PL;PSS1S;LGSPEC1
пели	пелихненьге	ADJ;GEN;PL;LGSPEC_AMP;PSS1S
праздник	праздникне	N;NOM;DEF;PL;LGSPEC1
шаба	шабаньконьге	N;HUM;GEN;SG;LGSPEC_AMP;PSS1P
ноляви	нолявихнень	ADJ;GEN;DEF;PL
яндава	яндаватне	N;NOM;DEF;PL;LGSPEC1
стихотворения	стихотворениянза	N;NOM;PL;PSS3S;LGSPEC1
скульптор	скульптороньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
пяль	пялеснонга	N;GEN;SG;LGSPEC_AMP;PSS3P
этнос	этности	N;DAT;DEF;SG;LGSPEC1
кондястемс	кондястихть	V;PL;3;INTR
ширь	ширьхне	N;NOM;PL;PSS1S
пряруця	пряруця	N;NOM;SG
шуму	шумуфнень	ADJ;GEN;PL;PSS1S
актив	активс	N;IN+ALL;SG;LGSPEC1
конь	конелень	N;SG;1;PST;LGSPEC1
одкстомомс	одкстомф	V.PTCP;PST;INTR
религия	религият	N;NOM;PL;LGSPEC1
фатямс	фатя	V;NEG;TR;LGSPEC1
аруямс	аруяк	V;IMP;SG;2;INTR
строямс	строясть	V;PL;3;PST;TR;LGSPEC1
шаба	шабантень	N;HUM;GEN;SG;PSS2P
документ	документонзон	N;GEN;PL;PSS3S;LGSPEC1
танка	танканцты	N;DAT;SG;PSS3S;LGSPEC1
пуромкс	пуромкссонза	N;IN+ESS;SG;PSS3S
туткоткс	туткотксокс	N;HUM;TRANS;SG
петеви	петеви	ADJ
бюджет	бюджетоньке	N;NOM;SG;PSS1P;LGSPEC1
учредитель	учредителец	N;HUM;NOM;SG;PSS3S;LGSPEC1
маятамс	маятафтозь	V;AC3;PL;3;CAUS;LGSPEC1
зиян	зиянкс	N;TRANS;SG;LGSPEC1
чакамс	чакасть	V;AC3;PL;2;INTR
каркс	карксненди	N;DAT;PL;PSS1S
конференция	конференцияс	N;IN+ALL;SG;LGSPEC1
шавомс	шавондозь	V;AC3;PL;3;TR
васьфнемс	васьфнельхть	V;PL;3;RMT;TR
дворец	дворецнень	N;GEN;PL;PSS1S;LGSPEC1
комбайна	комбайнаньке	N;NOM;SG;PSS1P;LGSPEC1
арьсемс	арьсефтеви	V;SG;3;CAUS;PASS
страхования	страхованиять	N;GEN;DEF;SG;LGSPEC1
активнайши	активнайшиснон	N;GEN;SG;PSS3P;LGSPEC1
мода	модасна	N;NOM;SG;PSS3P
пякстамс	пякставсть	V;PL;3;PST;TR;PASS
тор	тороц	N;NOM;SG;PSS3S
сувамс	сувафтольхть	V;PL;3;RMT;CAUS
тёждялгодомс	теждялгодат	V;SG;2;INTR
костюм	костюмс	N;IN+ALL;SG;LGSPEC1
творчества	творчествастон	N;IN+ABL;SG;PSS1S;LGSPEC1
самс	сафтыть	V;AC3;SG;2;CAUS
эвондамс	эвондазь	V;AC3;PL;3;INTR
слой	слойсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
тиемс	тифтян	V;SG;1;CAUS
пуромомс	пуромкшне	V;NEG;INTR
тапарямс	тапарякшнесайне	V;AC3P;SG;1;TR
тонадомс	тонадовсть	V;AC3;IMP;PL;2;INTR;PASS
бславамс	бславафолень	V.PTCP;SG;1;PST;TR;LGSPEC1
гонорар	гонорарсь	N;NOM;DEF;SG;LGSPEC1
пеедемс	пеетькшнесть	V;AC3;IMP;PL;2;INTR
васьфнемс	васьфнек	V;AC3;IMP;SG;2;TR
вазь	вазьть	N;GEN;DEF;SG
юрнамс	юрнась	V;SG;3;PST;INTR
продавец	продавец	N;HUM;NOM;SG;LGSPEC1
пяль	пяльхнень	N;GEN;PL;PSS1S
биография	биографиянц	N;GEN;SG;PSS3S;LGSPEC1
бюро	бюро	N;NOM;SG;LGSPEC1
перьф	перьфсост	N;IN+ESS;SG;PSS3P
ноябрь	ноябрь	N;NOM;SG;LGSPEC1
сяряди	сярядихненди	ADJ;DAT;DEF;PL
шопача	шопача	N;HUM;NOM;SG
балл	баллхненди	N;DAT;DEF;PL;LGSPEC1
аздомс	азфонц	V.PTCP;GEN;SG;PSS3S;PST;INTR
судендамс	судендать	V;SG;2;PST;TR;LGSPEC1
группа	группат	N;NOM;PL;LGSPEC1
пейзиволь	пейзивольхнень	N;GEN;PL;PSS1S
решения	решениянц	N;GEN;SG;PSS3S;LGSPEC1
батюшка	батюшкатне	N;HUM;NOM;DEF;PL;LGSPEC1
купол	куполти	N;DAT;DEF;SG;LGSPEC1
передача	передачанза	N;NOM;PL;PSS3S;LGSPEC1
сургуд	сургутонь	N;GEN;SG
штатол	штатолсь	N;NOM;DEF;SG
синдемс	синдевсть	V;PL;3;PST;TR;PASS
педагогика	педагогикась	N;NOM;DEF;SG;LGSPEC1
ансамбль	ансамбльти	N;DAT;DEF;SG;LGSPEC1
аборт	абортсь	N;NOM;DEF;SG;LGSPEC1
танка	танкантень	N;GEN;SG;PSS2P;LGSPEC1
кизефтемс	кизефтень	V;SG;1;PST;TR
кулу	кулуфнень	N;GEN;PL;PSS1S
тяште	тяштелень	N;SG;1;PST
пичефкс	пичефксонтень	N;GEN;SG;PSS2P
печкомс	печкондсть	V;AC3;IMP;PL;2;TR
группа	группать	N;GEN;DEF;SG;LGSPEC1
группа	группава	N;PROL;SG;LGSPEC1
маятамс	маятафтсть	V;AC3;IMP;PL;2;CAUS;LGSPEC1
молемс	молелеме	V;PL;1;RMT;INTR
директор	директорхнень	N;HUM;GEN;DEF;PL;LGSPEC1
колемс	колендезь	V;AC3;PL;3;INTR
килькш	килькшне	N;NOM;DEF;PL
сяськомс	сяськфт	V.PTCP;NOM;PL;PST;TR
маршрут	маршрутонь	N;GEN;SG;LGSPEC1
зенитчик	зенитчикне	N;HUM;NOM;PL;PSS1S;LGSPEC1
поза	поза	N;NOM;SG
касомс	касфтоволь	V;SG;3;RMT;CAUS;PASS
заразиндамс	заразиндафоль	V.PTCP;SG;3;PST;TR;LGSPEC1
использовандамс	использовандаволь	V;SG;3;RMT;TR;PASS;LGSPEC1
видеоролик	видеороликнень	N;GEN;PL;PSS1S;LGSPEC1
сура	суронзон	N;GEN;PL;PSS3S
видьме	видьмонкса	N;CAUSV;SG
дивандамс	дивандафтсть	V;AC3;PL;2;CAUS;LGSPEC1
лятфтамс	лятфтасайне	V;AC3P;SG;1;TR
царевна	царевнанцты	N;HUM;DAT;SG;PSS3S;LGSPEC1
бюджетнай	бюджетнай	ADJ;LGSPEC1
край	крайхненди	N;DAT;PL;PSS1S;LGSPEC1
штамс	штаф	V.PTCP;PST;TR
молитва	молитванди	N;DAT;SG;LGSPEC1
занямс	заняфат	V.PTCP;SG;2;PST;TR;LGSPEC1
залив	заливть	N;GEN;DEF;SG;LGSPEC1
автоинспектор	автоинспекторхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
деловой	деловой	ADJ;LGSPEC1
эндокринолог	эндокринологти	N;HUM;DAT;DEF;SG;LGSPEC1
кагод	кагодс	N;IN+ALL;SG
жест	жесттнень	N;GEN;DEF;PL;LGSPEC1
поладомс	поладовихть	V;PL;3;TR;PASS
осложнения	осложнениякс	N;TRANS;SG;LGSPEC1
героизма	героизмаснон	N;GEN;SG;PSS3P;LGSPEC1
идь	идненьге	N;HUM;GEN;PL;LGSPEC_AMP;PSS1S
сеелень	сееленьке	ADJ;LGSPEC_AMP
нарвавомс	нарвави	V;SG;3;INTR
лажадомс	лажадоманьке	V;AC1;SG;LGSPEC_AMP;3;INTR
аймак	аймаксонза	N;IN+ESS;SG;PSS3S
розарямс	розаряви	V;SG;3;TR;PASS;LGSPEC1
комплекс	комплекссна	N;NOM;SG;PSS3P;LGSPEC1
замечания	замечаниятне	N;NOM;DEF;PL;LGSPEC1
очерк	очеркоц	N;NOM;SG;PSS3S;LGSPEC1
лопаямс	лопаякшнесть	V;AC3;PL;2;INTR
штамс	штамс	V;NFIN;TR
дальнобойщик	дальнобойщикокс	N;HUM;TRANS;SG;LGSPEC1
правитель	правительхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
инспекция	инспекцияса	N;IN+ESS;SG;LGSPEC1
казарма	казарматнень	N;GEN;PL;PSS2S;LGSPEC1
район	районцьке	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
кузнець	кузнецсна	N;HUM;NOM;SG;PSS3P;LGSPEC1
вернайши	вернайшисна	N;NOM;SG;PSS3P;LGSPEC1
семинар	семинарснон	N;GEN;SG;PSS3P;LGSPEC1
вешемс	вешеме	V;PL;1;PST;TR
толдокш	толдокшнень	N;GEN;PL;PSS1S
юниорка	юниоркатнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
пешкодомс	пешкоткшнемс	V;NFIN;INTR
присяга	присягаснон	N;GEN;SG;PSS3P;LGSPEC1
пакся	паксясь	N;NOM;DEF;SG
оператор	операторти	N;HUM;DAT;DEF;SG;LGSPEC1
столица	столицаснон	N;GEN;SG;PSS3P;LGSPEC1
профессиональнай	профессиональнайста	ADJ;IN+ABL;SG;LGSPEC1
сооружения	сооружениясь	N;NOM;DEF;SG;LGSPEC1
вена	вена	N;NOM;SG;LGSPEC1
распорядка	распорядкать	N;GEN;DEF;SG;LGSPEC1
пянакуд	пянакуттне	N;NOM;PL;PSS2S
пялькс	пяльксоньке	N;NOM;SG;PSS1P
цикла	цикла	N;NOM;SG;LGSPEC1
осложнения	осложнениянза	N;NOM;PL;PSS3S;LGSPEC1
цесарка	цесаркатненди	N;HUM;DAT;DEF;PL;LGSPEC1
нардамс	нардат	V;SG;2;TR
преподаватель	преподавательти	N;HUM;DAT;DEF;SG;LGSPEC1
пелемаши	пелемашить	N;GEN;DEF;SG
видекс	видекс	ADJ
озксвяти	озксвятиень	N;HUM;GEN;SG
ризф-пичефкс	ризф-пичефкс	N;NOM;SG
куцемс	куцсть	V;AC3;IMP;PL;2;INTR
сода	соткстка	N;TRANS;SG;LGSPEC_AMP;PSS2S;LGSPEC1
крейсер	крейсерть	N;GEN;DEF;SG;LGSPEC1
порькс	порькс	N;NOM;SG
шире	ширезень	N;GEN;SG;PSS1S
трва	трватне	N;NOM;DEF;PL
улем	улемдонза	N;ABL;SG;PSS3S
куль	кулезень	N;GEN;SG;PSS1S;LGSPEC1
ярмак	ярмакне	N;NOM;DEF;PL
алимент	алименттнень	N;GEN;PL;PSS2S;LGSPEC1
кодамс	кодайхть	V;PL;3;TR
правительства	правительствань	N;GEN;SG;LGSPEC1
лазомс	лазфнень	V.PTCP;GEN;DEF;PL;PST;TR
изгордомс	изгордозь	V;AC3;PL;3;INTR
новость	новостнень	N;GEN;DEF;PL;LGSPEC1
аралай	аралай	N;HUM
швабра	швабрат	N;NOM;PL;LGSPEC1
договорённость	договоренностть	N;NOM;PL;LGSPEC1
осложнения	осложнениятненди	N;DAT;DEF;PL;LGSPEC1
заведения	заведениясонк	N;IN+ESS;SG;PSS1P;LGSPEC1
командировочнай	командировочнай	ADJ;LGSPEC1
кочевник	кочевникнень	N;HUM;GEN;DEF;PL;LGSPEC1
бюст	бюстонь	N;GEN;SG;LGSPEC1
граф	граф	N;HUM;NOM;SG;LGSPEC1
семья	семьят	N;NOM;PL;LGSPEC1
квартира	квартирадонза	N;ABL;SG;PSS3S;LGSPEC1
мзолдомс	мзолдсть	V;AC3;IMP;PL;2;INTR
кучемс	кучфолень	V.PTCP;SG;1;PST;TR
батарея	батареянь	N;GEN;SG;LGSPEC1
кампания	кампаниятьке	N;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
работамс	работазевсь	V;SG;3;PST;TR;LGSPEC1
эшкс	эшксста	N;IN+ABL;SG
патриарх	патриархокс	N;HUM;TRANS;SG;LGSPEC1
налог	налокнень	N;GEN;PL;PSS1S;LGSPEC1
хлебозавод	хлебозаводса	N;IN+ESS;SG;LGSPEC1
валомс	валовсть	V;PL;3;PST;TR;PASS
мадомс	мадонь	V;SG;1;PST;INTR
гарантия	гарантиякс	N;TRANS;SG;LGSPEC1
аспирантура	аспирантураса	N;IN+ESS;SG;LGSPEC1
класс	классне	N;NOM;PL;PSS1S;LGSPEC1
кочкярьгя	кочкярьгязе	N;NOM;SG;PSS1S
администратор	администраторсь	N;HUM;NOM;DEF;SG;LGSPEC1
топодемс	топотькшне	V;NEG;INTR
принцип	принцип	N;NOM;SG;LGSPEC1
частт	часттненди	N;DAT;DEF;PL;LGSPEC1
почфонь	почфонь	ADJ
сберкасса	сберкассав	N;AT+ALL;SG;LGSPEC1
стена	стенатнень	N;GEN;DEF;PL;LGSPEC1
присяга	присягань	N;GEN;SG;LGSPEC1
кенеремс	кенерьф	V.PTCP;PST;INTR
лопаямс	лопаясть	V;AC3;PL;2;INTR
кржалгодомс	кржалготкшнихть	V;PL;3;INTR
седень	седень	ADJ
сынок	сынокт	N;NOM;PL
рацион	рационцнон	N;GEN;SG;PSS3P;LGSPEC1
бокс	бокстьке	N;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
метро	метроса	N;IN+ESS;SG;LGSPEC1
кенярдемс	кеняртькшнек	V;IMP;SG;2;INTR
реконструкция	реконструкцияц	N;NOM;SG;PSS3S;LGSPEC1
марамс	марамс	V;NFIN;TR
сувенир	сувенирда	N;ABL;SG;LGSPEC1
партийнай	партийнаель	ADJ;SG;3;PST;LGSPEC1
стена	стенась	N;NOM;DEF;SG;LGSPEC1
вирус	вируст	N;NOM;PL;LGSPEC1
топодемс	топодсть	V;PL;3;PST;INTR
капюшон	капюшон	N;NOM;SG;LGSPEC1
рой	ройть	N;NOM;PL;LGSPEC1
демобилизация	демобилизацияда	N;ABL;SG;LGSPEC1
кредит	кредитсь	N;NOM;DEF;SG;LGSPEC1
одолгодомс	одолгофтфт	V.PTCP;NOM;PL;PST;CAUS
существительнай	существительнайть	N;GEN;DEF;SG;LGSPEC1
конемс	конек	V;IMP;SG;2;TR
меленця	меленцяса	N;IN+ESS;SG;LGSPEC1
ваномс	ванондовсть	V;AC3;IMP;PL;2;TR;PASS
сюра	сюронза	N;NOM;PL;PSS3S
трамвай	трамвай	N;HUM;NOM;SG;LGSPEC1
доза	дозаса	N;IN+ESS;SG;LGSPEC1
аш	ашесь	V;SG;3;PST
классика	классиказонза	N;IN+ALL;SG;PSS3S;LGSPEC1
традиционнай	традиционнай	ADJ;LGSPEC1
планёрка	планеркаса	N;IN+ESS;SG;LGSPEC1
шары	шарыхнень	N;GEN;DEF;PL
графика	графикс	N;IN+ALL;SG;LGSPEC1
шуди	шуди	ADJ
альбом	альбомтьке	N;GEN;DEF;SG;LGSPEC_AMP;LGSPEC1
час	часта	N;ABL;SG;LGSPEC1
касомс	касфтови	V;SG;3;CAUS;PASS
седи	седисотка	N;IN+ESS;SG;LGSPEC_AMP;PSS2S
коллектор	коллекторхненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
сержант	сержанттне	N;HUM;NOM;DEF;PL;LGSPEC1
схватка	схватка	N;NOM;SG;LGSPEC1
начфтомс	начфтость	V;AC3;IMP;PL;2;TR
сюра	сюра	N;NOM;SG
попугай	попугайхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
стандарт	стандарттненди	N;DAT;PL;PSS2S;LGSPEC1
процесс	процессненди	N;DAT;PL;PSS1S;LGSPEC1
мора	морафтомонза	N;PRIV;SG;PSS3S
работамс	работада	V;IMP;PL;2;TR;LGSPEC1
водендамс	водендада	V;IMP;PL;2;TR;LGSPEC1
кельме	кельмоль	N;SG;3;PST
глухой	глухой	ADJ;LGSPEC1
миниатюра	миниатюрат	N;NOM;PL;LGSPEC1
васькафни	васькафнисна	N;HUM;NOM;SG;PSS3P
эрекламс	эреклафты	V;SG;3;CAUS
жвачка	жвачка	N;NOM;SG;LGSPEC1
деятельность	деятельностьсна	N;NOM;SG;PSS3P;LGSPEC1
нурда	нурттнень	N;GEN;PL;PSS2S
тест	тест	N;NOM;SG;LGSPEC1
пси	псият	ADJ;SG;2
регистрация	регистрацияснон	N;GEN;SG;PSS3P;LGSPEC1
удобрения	удобренияса	N;IN+ESS;SG;LGSPEC1
километра	километрань	N;GEN;SG;LGSPEC1
священник	священникненди	N;HUM;DAT;DEF;PL;LGSPEC1
шашлык	шашлыконкса	N;CAUSV;SG;LGSPEC1
статья	статьясь	N;NOM;DEF;SG;LGSPEC1
водоём	водоёмт	N;NOM;PL;LGSPEC1
элякодомс	элякоткшнезь	V;AC3;PL;3;INTR
парламент	парламенттненди	N;DAT;PL;PSS2S;LGSPEC1
сявомс	сявоть	V;SG;2;PST;TR
заводь	заводть	N;GEN;DEF;SG;LGSPEC1
рьвяямс	рьвяясь	V;SG;3;PST;INTR
снав	снавсь	N;NOM;DEF;SG
вяшкяня	вяшкянять	N;GEN;DEF;SG
религиознай	религиознайхнень	ADJ;GEN;PL;PSS1S;LGSPEC1
судьба	судьбань	N;GEN;SG;LGSPEC1
маладомс	малаткшнесь	V;SG;3;PST;INTR
лядемс	ляденди	V;SG;3;TR
шамафкс	шамафксонц	N;GEN;SG;PSS3S
хоккеист	хоккеистоньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
руководитель	руководительське	N;HUM;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
тев	тевозонза	N;IN+ALL;SG;PSS3S
кевонь	кевонне	ADJ;NOM;PL;PSS1S
съезд	съездста	N;IN+ABL;SG;LGSPEC1
порошок	порошоконь	N;GEN;SG;LGSPEC1
лампада	лампадаста	N;IN+ABL;SG;LGSPEC1
шовафкс	шовафксста	N;IN+ABL;SG
мала	малатне	ADJ;NOM;DEF;PL
валвеляфкс	валвеляфкснень	N;GEN;DEF;PL
солдат	солдатокс	N;HUM;TRANS;SG;LGSPEC1
шума	шумоньконь	N;GEN;SG;PSS1P
пенгя	пенгятне	N;NOM;PL;PSS2S
чуваш	чувашка	N;HUM;NOM;SG;LGSPEC_AMP
проектант	проектанттнень	N;HUM;GEN;DEF;PL;LGSPEC1
трва	трвастон	N;IN+ABL;SG;PSS1S
столица	столицац	N;NOM;SG;PSS3S;LGSPEC1
гадямс	гадяват	V;SG;2;TR;PASS
позвоночник	позвоночникста	N;IN+ABL;SG;LGSPEC1
педагог	педагокненди	N;HUM;DAT;PL;PSS1S;LGSPEC1
жуватань	жуватаньке	ADJ;LGSPEC_AMP
тев	тевонтенди	N;DAT;SG;PSS2P
ялга	ялгань	N;HUM;GEN;SG
товар	товархненди	N;DAT;DEF;PL;LGSPEC1
юр	юрстонза	N;IN+ABL;SG;PSS3S
щакамс	щакай	V;SG;3;INTR
согласия	согласиянь	N;GEN;SG;LGSPEC1
координатор	координаторхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
армян	армятт	N;HUM;NOM;PL;LGSPEC1
шум	шумть	N;GEN;DEF;SG;LGSPEC1
светила	светилатне	N;NOM;PL;PSS2S;LGSPEC1
шапарякс	шапарякст	N;NOM;PL
сотрудник	сотрудникненди	N;HUM;DAT;DEF;PL;LGSPEC1
компонент	компонентт	N;NOM;PL;LGSPEC1
сазан	сазан	N;HUM;NOM;SG;LGSPEC1
клиника	клиникать	N;GEN;DEF;SG;LGSPEC1
район	райоттненди	N;DAT;DEF;PL;LGSPEC1
шавшинь	шавшинь	ADJ
козякодомс	козякофтовольхть	V;PL;3;RMT;CAUS;PASS
моль	молель	N;HUM;SG;3;PST;LGSPEC1
календула	календулань	N;GEN;SG;LGSPEC1
сиве	сивось	N;NOM;DEF;SG
поколения	поколенияти	N;DAT;DEF;SG;LGSPEC1
ведомства	ведомстватне	N;NOM;PL;PSS2S;LGSPEC1
петемс	петемс	V;NFIN;TR
метра	метрат	N;NOM;PL;LGSPEC1
сюре	сюренди	N;DAT;SG
юбилей	юбилейнц	N;GEN;SG;PSS3S;LGSPEC1
идемс	идеманьке	V;AC1;SG;LGSPEC_AMP;3;TR
кагор	кагор	N;NOM;SG;LGSPEC1
автоколонна	автоколоннать	N;GEN;DEF;SG;LGSPEC1
стямс	стязь	V;AC3;PL;3;INTR
кельме	кельмонзон	N;GEN;PL;PSS3S
валкс	валксонь	N;GEN;SG
столовай	столоваи	N;AT+ALL;SG;LGSPEC1
покадемс	покадельхть	V;PL;3;RMT;INTR
штабель	штабельхнень	N;GEN;PL;PSS1S;LGSPEC1
токамс	токафт	V.PTCP;NOM;PL;PST;TR
ген	геттнень	N;GEN;PL;PSS2S;LGSPEC1
кодамс	кодафт	V.PTCP;NOM;PL;PST;TR
сиве	сивеса	N;IN+ESS;SG
ваномс	ваномазь	V;AC1;PL;3;TR
наругамс	наругасть	V;AC3;IMP;PL;2;TR;LGSPEC1
лауреат	лауреатсь	N;HUM;NOM;DEF;SG;LGSPEC1
стенной	стенной	ADJ;LGSPEC1
конкурент	конкурентт	N;HUM;NOM;PL;LGSPEC1
писания	писания	N;NOM;SG;LGSPEC1
часовой	часовойть	N;HUM;GEN;DEF;SG;LGSPEC1
выступления	выступлениятнень	N;GEN;DEF;PL;LGSPEC1
сатана	сатанати	N;DAT;DEF;SG;LGSPEC1
сувомс	суви	V;SG;3;INTR
святитель	святительсь	N;HUM;NOM;DEF;SG;LGSPEC1
тапоркс	тапорксне	N;NOM;PL;PSS1S
участковай	участковайсь	ADJ;NOM;DEF;SG;LGSPEC1
ризф	ризф	N;NOM;SG
визькс	визькс	N;NOM;SG
келазь	келазь	N;HUM;NOM;SG
нечистай	нечистай	N;NOM;SG;LGSPEC1
соя	соя	N;NOM;SG;LGSPEC1
кинят	кинясь	N;NOM;DEF;SG
кргапарь	кргапарьце	N;NOM;SG;PSS2S
рэпер	рэперсь	N;HUM;NOM;DEF;SG;LGSPEC1
кржалгодомс	кржалгодсь	V;SG;3;PST;INTR
идь	идьфтомон	N;HUM;PRIV;SG;PSS1S
рассада	рассаданьконь	N;GEN;SG;PSS1P;LGSPEC1
стирь	стирь	N;HUM;NOM;SG
овчарка	овчарканьке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
лувомс	лувсамак	V;AC1;SG;2;TR
сатомс	сатса	V;AC3S;SG;1;TR
лагер	лагерть	N;GEN;DEF;SG;LGSPEC1
консул	консулсь	N;HUM;NOM;DEF;SG;LGSPEC1
ваномс	ваноде	V;PL;2;PST;TR
отькорь	отькорькс	ADJ;TRANS;SG
павильон	павильоттнень	N;GEN;DEF;PL;LGSPEC1
сталма	сталмотнень	N;GEN;PL;PSS2S
мазут	мазутса	N;IN+ESS;SG;LGSPEC1
технолог	технолокт	N;HUM;NOM;PL;LGSPEC1
формат	форматнень	N;GEN;PL;PSS1S;LGSPEC1
сявань	сяваньке	ADJ;LGSPEC_AMP
лувкс	лувксоньке	N;NOM;SG;PSS1P
финанс	финанснень	N;GEN;DEF;PL;LGSPEC1
сюжет	сюжетснон	N;GEN;SG;PSS3P;LGSPEC1
премия	премияса	N;IN+ESS;SG;LGSPEC1
краеведения	краеведениясь	N;NOM;DEF;SG;LGSPEC1
солистка	солистканзон	N;HUM;GEN;PL;PSS3S;LGSPEC1
сван	сваттнень	N;HUM;GEN;DEF;PL;LGSPEC1
рьвяямс	рьвяяфтомань	V;AC1;SG;3;CAUS
кочкяря	кочкяряти	N;DAT;DEF;SG
кочкамат	кочкамазень	N;GEN;SG;PSS1S
рьвяямс	рьвяяй	V;SG;3;INTR
солдат	солдатнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
поладомс	полафтодязь	V;AC2P;CAUS
печатламс	печатлафтыне	V;AC3;SG;1;CAUS;LGSPEC1
пеелем	пеелемса	N;IN+ESS;SG
ваномс	ваноль	V;SG;3;RMT;TR
ардомс	ардсаськ	V;AC3;PL;1;INTR
консультация	консультациятненди	N;DAT;DEF;PL;LGSPEC1
рекламнай	рекламнайхть	ADJ;NOM;PL;LGSPEC1
миле	милетне	N;NOM;PL;PSS2S
материал	материалхненди	N;DAT;DEF;PL;LGSPEC1
фамилия	фамилиянц	N;GEN;SG;PSS3S;LGSPEC1
профильнай	профильнай	ADJ;LGSPEC1
лисемс	лисенде	V;NEG;INTR
нашамс	наша	V;NEG;TR
тапоркс	тапорксти	N;DAT;DEF;SG
роштува	роштувати	N;DAT;DEF;SG;LGSPEC1
матф	матфста	N;IN+ABL;SG
спецназ	спецназса	N;IN+ESS;SG;LGSPEC1
аспирин	аспиринть	N;GEN;DEF;SG;LGSPEC1
миллиметра	миллиметрада	N;ABL;SG;LGSPEC1
антибиотик	антибиотикт	N;NOM;PL;LGSPEC1
кятав	кятафт	ADJ;NOM;PL
тренер	тренеронте	N;HUM;NOM;SG;PSS2P;LGSPEC1
пол	полонц	N;GEN;SG;PSS3S;LGSPEC1
пупай	пупайхть	N;NOM;PL
отравиндамс	отравинда	V;NEG;TR;LGSPEC1
кей	кей	N;NOM;SG
марлянь	марлянь	ADJ;LGSPEC1
водка	водкаса	N;IN+ESS;SG;LGSPEC1
марямс	маряфне	V.PTCP;NOM;DEF;PL;PST;TR
лагерь	лагерьхненди	N;DAT;DEF;PL;LGSPEC1
мазоптомс	мазопты	V;SG;3;TR
шуфта	шуфтть	N;GEN;DEF;SG
артистка	артистканте	N;HUM;NOM;SG;PSS2P;LGSPEC1
награда	наградатнень	N;GEN;PL;PSS2S;LGSPEC1
петемс	петеме	V;PL;1;PST;TR
артист	артист	N;HUM;NOM;SG;LGSPEC1
зарисовка	зарисовканзон	N;GEN;PL;PSS3S;LGSPEC1
сазан	сазанць	N;HUM;NOM;DEF;SG;LGSPEC1
идь	идец	N;HUM;NOM;SG;PSS3S
вакансия	вакансияда	N;ABL;SG;LGSPEC1
доярка	дояркатнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
ёрдамс	ердамань	V;AC1;SG;3;TR
зарплата	зарплатати	N;DAT;DEF;SG;LGSPEC1
район	районцнон	N;GEN;SG;PSS3P;LGSPEC1
келазь	келазсь	N;HUM;NOM;DEF;SG
корпус	корпусу	N;AT+ALL;SG;LGSPEC1
предатель	предательхть	N;HUM;NOM;PL;LGSPEC1
условия	условияньконди	N;DAT;SG;PSS1P;LGSPEC1
сакал	сакалхнень	N;GEN;DEF;PL
площадка	площадкас	N;IN+ALL;SG;LGSPEC1
лазомс	лазондсь	V;SG;3;PST;TR
шуфтомомс	шуфтомоть	V;SG;2;PST;INTR
касомс	касондсть	V;AC3;IMP;PL;2;INTR
накопления	накоплениятне	N;NOM;PL;PSS2S;LGSPEC1
удобрения	удобрениянди	N;DAT;SG;LGSPEC1
капа	капати	N;DAT;DEF;SG
судья	судьязе	N;HUM;NOM;SG;PSS1S;LGSPEC1
печатламс	печатлак	V;AC3;IMP;SG;2;TR;LGSPEC1
сувенир	сувенирхтка	N;NOM;PL;LGSPEC_AMP;LGSPEC1
экран	экранца	N;IN+ESS;SG;LGSPEC1
номер	номеркс	N;TRANS;SG;LGSPEC1
ванни	ваннихть	N;HUM;GEN;DEF;SG
свадьба	свадьбаньке	N;NOM;SG;PSS1P;LGSPEC1
панга	панкс	N;IN+ALL;SG
вазыямс	вазыясь	V;SG;3;PST;INTR
случай	случай	N;LGSPEC1
хор	хорхненди	N;DAT;DEF;PL;LGSPEC1
образ	образсь	N;NOM;DEF;SG;LGSPEC1
разбой	разбой	N;LGSPEC1
лингвистика	лингвистикать	N;GEN;DEF;SG;LGSPEC1
тялькфтамс	тялькфтави	V;SG;3;TR;PASS
шум	шумокс	N;TRANS;SG;LGSPEC1
жувата	жуватати	N;HUM;DAT;DEF;SG
нярьхкамаз	нярьхкамазсь	N;NOM;DEF;SG
ашка	ашкнень	N;GEN;PL;PSS1S
панда	панда	N;NOM;SG
аш	ашеть	V;SG;2;PST
келе	келес	N;IN+ALL;SG
дошкольник	дошкольникт	N;HUM;NOM;PL;LGSPEC1
дрога	дрогаса	N;IN+ESS;SG;LGSPEC1
артист	артисткат	N;HUM;PROL;SG;PSS2S;LGSPEC1
родительнай	родительнай	ADJ;LGSPEC1
честнай	честнай	ADJ;LGSPEC1
поколения	поколенияньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
заезд	заезтта	N;ABL;SG;LGSPEC1
наказ	наказснонды	N;DAT;SG;PSS3P;LGSPEC1
шабра	шабрацень	N;HUM;GEN;SG;PSS2S
жувата	жуватанц	N;HUM;GEN;SG;PSS3S
заработка	заработкать	N;GEN;DEF;SG;LGSPEC1
солдат	солдатоньке	N;HUM;NOM;SG;PSS1P;LGSPEC1
горнямс	горнязь	V;AC3;PL;3;INTR
стрижка	стрижкатнень	N;GEN;DEF;PL;LGSPEC1
лоскод	лоскод	N;NOM;SG;LGSPEC1
пиксомс	пиксов	V;NEG;TR;PASS
ультразвуковой	ультразвуковой	ADJ;LGSPEC1
лем	лемозост	N;IN+ALL;SG;PSS3P
слайд	слайттнень	N;GEN;PL;PSS2S;LGSPEC1
куй	куй	N;HUM
дивандамс	дивандась	V;SG;3;PST;INTR;LGSPEC1
юрхта	юрхтава	N;PROL;SG
призёр	призероль	N;HUM;SG;3;PST;LGSPEC1
маштомаши	маштомошиц	N;NOM;SG;PSS3S
знакомондамс	знакомондасть	V;AC3;IMP;PL;2;TR;LGSPEC1
час	части	N;DAT;DEF;SG;LGSPEC1
пожар	пожархненди	N;DAT;DEF;PL;LGSPEC1
слесарь	слесарьхне	N;HUM;NOM;DEF;PL;LGSPEC1
надиямс	надияме	V;PL;1;PST;INTR;LGSPEC1
сатомс	сатовсь	V;SG;3;PST;TR;PASS
бок	боксь	N;NOM;DEF;SG;LGSPEC1
маласькодомс	маласькофтовихть	V;PL;3;CAUS;PASS
эши	эшихтьке	N;GEN;DEF;SG;LGSPEC_AMP
визди	виздихть	ADJ;GEN;DEF;SG
рашка	рашка	N;NOM;SG
касомс	касфты	V;SG;3;CAUS
лётчик	лётчиколь	N;HUM;SG;3;PST;LGSPEC1
куд	кудсонга	N;IN+ESS;SG;LGSPEC_AMP;PSS1S
кочегар	кочегаркс	N;HUM;TRANS;SG;LGSPEC1
заботафтома	заботафтома	ADJ;LGSPEC1
аттракцион	аттракциоттнень	N;GEN;DEF;PL;LGSPEC1
азор	азорсна	N;HUM;NOM;SG;PSS3P
ута	утце	N;NOM;SG;PSS2S
спорямс	споряк	V;AC3;IMP;SG;2;INTR;LGSPEC1
ковёр	коверхнень	N;GEN;DEF;PL;LGSPEC1
стержневой	стержневойста	ADJ;IN+ABL;SG;LGSPEC1
ящик	ящикт	N;NOM;PL;LGSPEC1
клеямс	клеявихть	V;PL;3;TR;PASS;LGSPEC1
авторитет	авторитетокс	N;TRANS;SG;LGSPEC1
лекторий	лекторийсь	N;NOM;DEF;SG;LGSPEC1
очерк	очеркта	N;ABL;SG;LGSPEC1
герой	героенди	N;HUM;DAT;SG;LGSPEC1
роман	роматтне	N;NOM;PL;PSS2S;LGSPEC1
цильге	цильгсь	N;NOM;DEF;SG
диссертационнай	диссертационнай	ADJ;LGSPEC1
кумбарав	кумбаравсь	N;NOM;DEF;SG
сёпомс	сепонда	V;NEG;TR
сазор	сазоронзонды	N;HUM;DAT;PL;PSS3S
направления	направленияда	N;ABL;SG;LGSPEC1
сускомс	сускфнень	V.PTCP;GEN;PL;PSS1S;PST;TR
конемс	конине	V;AC3;SG;1;TR
вастомс	вастське	V;SG;LGSPEC_AMP;3;PST;INTR
правительства	правительстваньке	N;NOM;SG;PSS1P;LGSPEC1
срхкамс	срхкат	V;SG;2;INTR
горнямс	горняй	V;SG;3;INTR
такор	такор	ADJ
инвестор	инвесторхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
сокай-види	сокай-видиень	N;HUM;GEN;SG
мисс	мисс	N;HUM;NOM;SG;LGSPEC1
драма	драмастонза	N;IN+ABL;SG;PSS3S;LGSPEC1
либордомс	либордсть	V;AC3;IMP;PL;2;INTR
потамс	потасть	V;AC3;PL;2;INTR
внешкольнай	внешкольнай	ADJ;LGSPEC1
соратник	соратниконзонды	N;HUM;DAT;PL;PSS3S;LGSPEC1
куямс	куяфтан	V;SG;1;CAUS
лапа	лапасонза	N;IN+ESS;SG;PSS3S;LGSPEC1
тев	тевсот	N;IN+ESS;SG;PSS2S
колхозник	колхозникненди	N;HUM;DAT;DEF;PL;LGSPEC1
шуфта	шуфттнень	N;GEN;PL;PSS2S
организация	организацияти	N;DAT;DEF;SG;LGSPEC1
якшама	якшама	ADJ
оцязор	оцязорхненди	N;HUM;DAT;DEF;PL
задача	задачанза	N;NOM;PL;PSS3S;LGSPEC1
кочкомс	кочкость	V;AC3;PL;2;TR
сад	садфтома	N;PRIV;SG;LGSPEC1
стипендия	стипендиятнень	N;GEN;DEF;PL;LGSPEC1
вес	весса	N;IN+ESS;SG;LGSPEC1
автовокзал	автовокзалса	N;IN+ESS;SG;LGSPEC1
сарафан	сарафан	N;NOM;SG;LGSPEC1
герой	герой	N;HUM;LGSPEC1
вельхтямс	вельхтяфтость	V;AC3;PL;2;CAUS
архивист	архивисттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
сорт	сортт	N;NOM;PL;LGSPEC1
тренер	тренеронтень	N;HUM;GEN;SG;PSS2P;LGSPEC1
велень	веленне	ADJ;NOM;PL;PSS1S
филиал	филиалсь	N;NOM;DEF;SG;LGSPEC1
сюконямс	сюконямс	V;NFIN;INTR
мастерица	мастерицатнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
кяль	кялькс	N;TRANS;SG
железа	железань	N;GEN;SG;LGSPEC1
причёска	прическась	N;NOM;DEF;SG;LGSPEC1
инженер	инженерхт	N;HUM;NOM;PL;LGSPEC1
обязанность	обязанносттне	N;NOM;DEF;PL;LGSPEC1
бункер	бункер	N;NOM;SG;LGSPEC1
баня	банятне	N;NOM;DEF;PL;LGSPEC1
обуза	обузакс	N;TRANS;SG;LGSPEC1
ши	шине	N;NOM;DEF;PL
куз	кузенька	N;GEN;SG;LGSPEC_AMP
ваномс	ванфтса	V;AC3S;SG;1;CAUS
шуфта	шуфттне	N;NOM;DEF;PL
сатовикс	сатовикст	ADJ;NOM;PL
сявомс	сявфольхть	V.PTCP;PL;3;PST;TR
воин	воинонзон	N;HUM;GEN;PL;PSS3S;LGSPEC1
корхтавкшу	корхтафкшу	ADJ
кочкомс	кочкат	V;SG;2;TR
залив	залив	N;NOM;SG;LGSPEC1
газовик	газовикти	N;HUM;DAT;DEF;SG;LGSPEC1
маска	маска	N;NOM;SG;LGSPEC1
честнай	честнайста	ADJ;IN+ABL;SG;LGSPEC1
матомс	матфан	V.PTCP;SG;1;PST;TR
пожар	пожару	N;AT+ALL;SG;LGSPEC1
вице-президент	вице-президентть	N;HUM;GEN;DEF;SG;LGSPEC1
кукамс	кукай	V;SG;3;INTR
панчф	панчфть	N;GEN;DEF;SG
курант	куранттнень	N;GEN;PL;PSS2S;LGSPEC1
договорённость	договоренность	N;NOM;SG;LGSPEC1
авозь	авозце	N;HUM;NOM;SG;PSS2S
отрасля	отраслясонза	N;IN+ESS;SG;PSS3S;LGSPEC1
сускомс	сускф	V.PTCP;PST;TR
актриса	актрисаньконь	N;HUM;GEN;SG;PSS1P;LGSPEC1
сяземс	сязев	V;NEG;TR;PASS
груша	грушаса	N;IN+ESS;SG;LGSPEC1
субэтнос	субэтноссь	N;NOM;DEF;SG;LGSPEC1
клад	кладсь	N;NOM;DEF;SG;LGSPEC1
национальность	национальносттненди	N;DAT;PL;PSS2S;LGSPEC1
керы	керыне	ADJ;NOM;PL;PSS1S
прощения	прощениянь	N;GEN;SG;LGSPEC1
доклад	докладть	N;GEN;DEF;SG;LGSPEC1
забота	заботати	N;DAT;DEF;SG;LGSPEC1
куфкстомс	куфкстсь	V;SG;3;PST;INTR
особеннай	особеннай	ADJ;LGSPEC1
цех	цехти	N;DAT;DEF;SG;LGSPEC1
аист	аистсь	N;HUM;NOM;DEF;SG;LGSPEC1
коллекция	коллекцияс	N;IN+ALL;SG;LGSPEC1
матомс	матыхть	V;PL;3;TR
политолог	политологсь	N;HUM;NOM;DEF;SG;LGSPEC1
пулю	пулю	ADJ
очерк	очерконьке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
артист	артисттненди	N;HUM;DAT;DEF;PL;LGSPEC1
ашувонь	ашувонь	ADJ
бобовай	бобовайхнень	ADJ;GEN;PL;PSS1S;LGSPEC1
премия	премиянцты	N;DAT;SG;PSS3S;LGSPEC1
цятордомс	цятордсть	V;PL;3;PST;INTR
дата	датанц	N;GEN;SG;PSS3S;LGSPEC1
жир	жирда	N;ABL;SG;LGSPEC1
вешемс	вешень	V;SG;1;PST;TR
афсатыкс	афсатыксонзон	N;GEN;PL;PSS3S
грань	грань	N;LGSPEC1
эпидемия	эпидемиясь	N;NOM;DEF;SG;LGSPEC1
удаламс	удалафтольхть	V;PL;3;RMT;CAUS;LGSPEC1
фамилия	фамилия	N;NOM;SG;LGSPEC1
руз	рузан	N;HUM;SG;1;LGSPEC1
эводемс	эводе	V;NEG;INTR
храм	храпнень	N;GEN;PL;PSS1S;LGSPEC1
синоним	синонипне	N;NOM;DEF;PL;LGSPEC1
пулф	пулфнень	N;GEN;DEF;PL
решандамс	решандаськ	V;AC3;PL;1;TR;LGSPEC1
рабства	рабствас	N;IN+ALL;SG;LGSPEC1
стена	стенац	N;NOM;SG;PSS3S;LGSPEC1
плодороднай	плодороднай	ADJ;LGSPEC1
реанимация	реанимациянь	N;GEN;SG;LGSPEC1
представитель	представитель	N;HUM;LGSPEC1
талакодомс	талакодсь	V;SG;3;PST;INTR
техника	техникаснонга	N;GEN;SG;LGSPEC_AMP;PSS3P;LGSPEC1
клиника	клиникаса	N;IN+ESS;SG;LGSPEC1
сотрудник	сотрудниконза	N;HUM;NOM;PL;PSS3S;LGSPEC1
кучемс	кучфнень	V.PTCP;GEN;DEF;PL;PST;TR
ашуши	ашушись	N;NOM;DEF;SG
итальянец	итальянец	N;HUM;NOM;SG;LGSPEC1
донор	донорхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
аудитория	аудиторияв	N;AT+ALL;SG;LGSPEC1
тев	тевсонт	N;IN+ESS;SG;PSS2P
сускомс	сускодязь	V;AC2P;TR
комболф	комболфть	N;GEN;DEF;SG
седь	седьге	N;NOM;SG;LGSPEC_AMP
шаркстомс	шаркстыхть	V;PL;3;INTR
шамдомс	шамдозе	V;AC3S;SG;3;TR
эрекламс	эреклакшнетяма	V;PL;1;INTR
заповедник	заповедникнень	N;GEN;DEF;PL;LGSPEC1
маштомаши	маштомошинень	N;GEN;DEF;PL
лишнай	лишнайть	ADJ;NOM;PL;LGSPEC1
бохарям	бохарямста	N;IN+ABL;SG
снимка	снимка	N;NOM;SG;LGSPEC1
паваз	паваст	N;NOM;PL
сор	сорхнень	N;GEN;DEF;PL;LGSPEC1
куля	кулядонза	N;ABL;SG;PSS3S
ваномс	ванфнень	V.PTCP;GEN;PL;PSS1S;PST;TR
панчф	панчфу	N;AT+ALL;SG
сявомс	сяводязь	V;AC2P;TR
кулома	куломада	N;ABL;SG
противник	противникснон	N;HUM;GEN;SG;PSS3P;LGSPEC1
военачальник	военачальникти	N;HUM;DAT;DEF;SG;LGSPEC1
планёрка	планеркат	N;NOM;PL;LGSPEC1
арнемат	арнемаснон	N;GEN;SG;PSS3P
шабра	шабрать	N;HUM;GEN;DEF;SG
компонент	компонентонц	N;GEN;SG;PSS3S;LGSPEC1
марямс	маряфтозе	V;AC3S;SG;3;CAUS
китель	кительса	N;IN+ESS;SG;LGSPEC1
варжакстомс	варжакстсть	V;PL;3;PST;INTR
симулянт	симулянтка	N;HUM;NOM;SG;LGSPEC_AMP;LGSPEC1
служба	службатнень	N;GEN;DEF;PL;LGSPEC1
рис	рисста	N;IN+ABL;SG;LGSPEC1
сок	сокат	N;PROL;SG;PSS2S;LGSPEC1
мумс	мувсь	V;SG;3;PST;TR;PASS
стирь	стирян	N;HUM;SG;1
пинкс	пинкс	N;NOM;SG
вайгяльпе	вайгяльпе	N;NOM;SG
кор	кор	N;NOM;SG
ваномс	ванфтондярясасть	V;AC3;COND;PL;2;CAUS
тост	тосттнень	N;GEN;PL;PSS2S;LGSPEC1
пяшксе	пяшксень	ADJ;GEN;SG
мала	маласта	ADJ;IN+ABL;SG
мрдамс	мрдак	V;IMP;SG;2;INTR
товар	товархт	N;NOM;PL;LGSPEC1
вельхтямс	вельхтясть	V;PL;3;PST;TR
москвичка	москвичка	N;HUM;NOM;SG;LGSPEC1
аллея	аллеять	N;GEN;DEF;SG;LGSPEC1
метра	метрать	N;GEN;DEF;SG;LGSPEC1
шов	шофт	N;NOM;PL
лисемс	лисьфоль	V.PTCP;SG;3;PST;INTR
иняру	инярусь	ADJ;NOM;DEF;SG
сейхтемс	сейхтемс	V;NFIN;TR
приёмнай	приемнайхнень	N;GEN;PL;PSS1S;LGSPEC1
актёр	актерхт	N;HUM;NOM;PL;LGSPEC1
трубка	трубкати	N;DAT;DEF;SG;LGSPEC1
пекиямс	пекияфтада	V.PTCP;PL;2;PST;INTR
пиче	пиченза	N;NOM;PL;PSS3S
труба	трубать	N;GEN;DEF;SG;LGSPEC1
шов	шовда	N;ABL;SG
жувата	жуватане	N;HUM;NOM;PL;PSS1S
пара	паратнень	N;GEN;PL;PSS2S;LGSPEC1
миле	милеть	N;GEN;DEF;SG
стирь	стирти	N;HUM;DAT;DEF;SG
вагон	ваготт	N;NOM;PL;LGSPEC1
леф	лефкст	N;HUM;TRANS;SG;PSS2S;LGSPEC1
практикум	практикум	N;NOM;SG;LGSPEC1
бельгиец	бельгиецнень	N;HUM;GEN;DEF;PL;LGSPEC1
ал	алхт	N;NOM;PL
люкшя	люкшя	N;NOM;SG
связист	связисттненди	N;HUM;DAT;DEF;PL;LGSPEC1
пляма	плямакс	N;TRANS;SG
пачкодемс	пачкодель	V;SG;3;RMT;INTR
пароход	парохотти	N;DAT;DEF;SG;LGSPEC1
кочам	кочамть	N;GEN;DEF;SG
звонямс	звонятада	V;PL;2;INTR;LGSPEC1
нардамс	нардасть	V;AC3;PL;2;TR
вычислительнай	вычислительнай	ADJ;LGSPEC1
упаковка	упаковкать	N;GEN;DEF;SG;LGSPEC1
подростка	подросткатненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
источник	источникста	N;IN+ABL;SG;LGSPEC1
одкстоптомс	одкстоптозе	V;AC3S;SG;3;TR
идемс	идесть	V;AC3;PL;2;TR
свобода	свободанзон	N;GEN;PL;PSS3S;LGSPEC1
вастонь	вастоньке	ADJ;LGSPEC_AMP
визькс	визьксонте	N;NOM;SG;PSS2P
баритон	баритон	N;NOM;SG;LGSPEC1
спасибамс	спасибан	V;SG;1;TR;LGSPEC1
стирь	стиреньке	N;HUM;GEN;SG;LGSPEC_AMP
пластинка	пластинка	N;NOM;SG;LGSPEC1
драма	драмать	N;GEN;DEF;SG;LGSPEC1
дизель	дизель	N;NOM;SG;LGSPEC1
нардамс	нардада	V;IMP;PL;2;TR
шабра	шабрати	N;HUM;DAT;DEF;SG
тидя	тидянц	N;HUM;GEN;SG;PSS3S
азондомс	азондонь	V;SG;1;PST;TR
уликс	уликсть	N;GEN;DEF;SG
валомс	валса	V;AC3S;SG;1;TR
локсти	локстихне	N;HUM;NOM;DEF;PL
градус	градусс	N;IN+ALL;SG;LGSPEC1
представитель	представительсь	N;HUM;NOM;DEF;SG;LGSPEC1
запас	запасне	N;NOM;DEF;PL;LGSPEC1
ацамс	ацавсть	V;AC3;PL;2;TR;PASS
чардаш	чардашть	N;GEN;DEF;SG;LGSPEC1
паламс	паламайть	V;AC1;SG;2;TR
патриот	патриоттненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
отечества	отечествати	N;DAT;DEF;SG;LGSPEC1
одеколон	одеколонца	N;IN+ESS;SG;LGSPEC1
логопед	логопеттне	N;HUM;NOM;PL;PSS2S;LGSPEC1
электроплитка	электроплиткатне	N;NOM;DEF;PL;LGSPEC1
запас	запасне	N;NOM;PL;PSS1S;LGSPEC1
военнослужащай	военнослужащай	N;HUM;LGSPEC1
ацам	ацамсь	N;NOM;DEF;SG
поколения	поколениянза	N;NOM;PL;PSS3S;LGSPEC1
эмоция	эмоцият	N;NOM;PL;LGSPEC1
шаржа	шаржень	N;GEN;SG
купальня	купальнять	N;GEN;DEF;SG;LGSPEC1
номер	номеронцка	N;GEN;SG;LGSPEC_AMP;PSS3S;LGSPEC1
добувамс	добувафт	V.PTCP;NOM;PL;PST;TR;LGSPEC1
лётчик	лётчикта	N;HUM;ABL;SG;LGSPEC1
марлю	марлюста	N;IN+ABL;SG
основной	основной	ADJ;LGSPEC1
фермер	фермерти	N;HUM;DAT;DEF;SG;LGSPEC1
кормушка	кормушкасна	N;NOM;SG;PSS3P;LGSPEC1
процент	проценттнень	N;GEN;DEF;PL;LGSPEC1
мастерства	мастерствац	N;NOM;SG;PSS3S;LGSPEC1
этюд	этюдсна	N;NOM;SG;PSS3P;LGSPEC1
июль	июленди	N;DAT;SG;LGSPEC1
победа	победанди	N;DAT;SG;LGSPEC1
ласькомс	ласьколь	V;SG;3;RMT;INTR
пандомс	пандсь	V;SG;3;PST;TR
сокамс	сокаме	V;PL;1;PST;TR
баллада	баллада	N;NOM;SG;LGSPEC1
случай	случайхнень	N;GEN;PL;PSS1S;LGSPEC1
пилафкс	пилафкснень	N;GEN;DEF;PL;LGSPEC1
жалоба	жалобатнень	N;GEN;PL;PSS2S;LGSPEC1
стадион	стадиоттненди	N;DAT;DEF;PL;LGSPEC1
белковай	белковай	ADJ;LGSPEC1
аккуратнай	аккуратнайста	ADJ;IN+ABL;SG;LGSPEC1
лувкс	лувксс	N;IN+ALL;SG
диктант	диктантть	N;GEN;DEF;SG;LGSPEC1
кулхцондомс	кулхцондода	V;IMP;PL;2;TR
жаднайгодомс	жаднайгодсь	V;SG;3;PST;INTR;LGSPEC1
жидкость	жидкостьса	N;IN+ESS;SG;LGSPEC1
кучемс	кучемайть	V;AC1;SG;2;TR
продюсер	продюсер	N;HUM;NOM;SG;LGSPEC1
штамс	штафт	V;NEG;CAUS
пурхц	пурхцнень	N;HUM;GEN;PL;PSS1S
шудемс	шудефтеви	V;SG;3;CAUS;PASS
болгарин	болгаринць	N;HUM;NOM;DEF;SG;LGSPEC1
эколог	эколог	N;HUM;NOM;SG;LGSPEC1
сивомс	сиводе	V;PL;2;PST;TR
заправка	заправкат	N;NOM;PL;LGSPEC1
маласта	маластонцты	ADJ;DAT;SG;PSS3S
сускомс	сускомс	V;NFIN;TR
прамс	праль	V;SG;3;RMT;INTR
экзамен	экзаметтнень	N;GEN;PL;PSS2S;LGSPEC1
кенеремс	кенерьфсь	V.PTCP;NOM;DEF;SG;PST;INTR
сад	сатат	N;SG;2;LGSPEC1
аш	ашезь	V;AC3;PL;3
сявомс	сявольхть	V;PL;3;RMT;TR
лама	ламодонга	ADJ;ABL;SG;LGSPEC_AMP
реклама	реклама	N;NOM;SG;LGSPEC1
примамс	примальхть	V;PL;3;RMT;TR;LGSPEC1
венч	венчезост	N;IN+ALL;SG;PSS3P
пеки	пекихненди	ADJ;DAT;DEF;PL
россиянин	россиянинць	N;HUM;NOM;DEF;SG;LGSPEC1
бронзовай	бронзовайсь	ADJ;NOM;DEF;SG;LGSPEC1
замечания	замечаниятне	N;NOM;PL;PSS2S;LGSPEC1
пединститут	пединститутоньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
свадьба	свадьбанц	N;GEN;SG;PSS3S;LGSPEC1
пялеве	пялевес	N;IN+ALL;SG
массив	массивть	N;GEN;DEF;SG;LGSPEC1
масса	массатнень	N;GEN;DEF;PL;LGSPEC1
шкай	шкайцень	N;GEN;SG;PSS2S
класс	классна	N;NOM;SG;PSS3P;LGSPEC1
волынка	волынкада	N;ABL;SG;LGSPEC1
ассамблея	ассамблеясна	N;NOM;SG;PSS3P;LGSPEC1
центра	центрасонк	N;IN+ESS;SG;PSS1P;LGSPEC1
лисемс	лисендян	V;SG;1;INTR
шовордамс	шовордави	V;SG;3;TR;PASS
шарф	шарф	N;NOM;SG;LGSPEC1
подстилка	подстилкати	N;DAT;DEF;SG;LGSPEC1
имущественнай	имущественнай	ADJ;LGSPEC1
васенцекс	васенцекс	ADJ
эняльдемс	эняльтькшнемс	V;NFIN;TR
парямс	паряй	V;SG;3;TR
аердомс	аерды	V;SG;3;INTR
шачемаши	шачемашиц	N;NOM;SG;PSS3S
тяштемс	тяштьфста	V.PTCP;IN+ABL;SG;PST;TR
пехота	пехотань	N;GEN;SG;LGSPEC1
золотань	золотанне	ADJ;NOM;DEF;PL;LGSPEC1
срхкамс	срхкафне	V.PTCP;NOM;PL;PSS1S;PST;INTR
вайме	ваймоль	N;SG;3;PST
грамотность	грамотностень	N;GEN;SG;LGSPEC1
звания	звания	N;NOM;SG;LGSPEC1
кшти	кштильхть	N;PL;3;PST
мокорь	мокорьста	N;IN+ABL;SG
бункер	бункерс	N;IN+ALL;SG;LGSPEC1
шире	ширень	N;GEN;SG
торт	торт	N;NOM;SG;LGSPEC1
ответ	ответфтома	N;PRIV;SG;LGSPEC1
азондомс	азондовихть	V;PL;3;TR;PASS
муниципальнай	муниципальнай	ADJ;LGSPEC1
сиземс	сизесь	V;SG;3;PST;INTR
каблук	каблукт	N;NOM;PL;LGSPEC1
простой	простоель	ADJ;SG;3;PST;LGSPEC1
лпнамс	лпнайхть	V;PL;3;INTR
укроп	укропть	N;GEN;DEF;SG;LGSPEC1
мумс	муде	V;PL;2;PST;TR
мишенди	мишендихнень	N;HUM;GEN;PL;PSS1S
потмар	потмар	N;NOM;SG
астма	астмакс	N;TRANS;SG;LGSPEC1
лядемс	лятьфоль	V.PTCP;SG;3;PST;INTR
полковой	полковой	ADJ;LGSPEC1
сялгомс	сялгольхть	V;PL;3;RMT;TR
драматургия	драматургиясь	N;NOM;DEF;SG;LGSPEC1
февраль	февраль	N;NOM;SG;LGSPEC1
полномочия	полномочиянза	N;NOM;PL;PSS3S;LGSPEC1
сотрудник	сотрудник	N;HUM;NOM;SG;LGSPEC1
приключения	приключениянза	N;NOM;PL;PSS3S;LGSPEC1
станица	станица	N;NOM;SG;LGSPEC1
ванондомс	ванондоль	V;SG;3;RMT;TR
жилищно-коммунальнай	жилищно-коммунальнай	ADJ;LGSPEC1
хозяйства	хозяйстваське	N;NOM;DEF;SG;LGSPEC_AMP;LGSPEC1
пуд	путоль	N;SG;3;PST;LGSPEC1
факультет	факультетсонк	N;IN+ESS;SG;PSS1P;LGSPEC1
кружок	кружок	N;NOM;SG;LGSPEC1
пичемарь	пичемарьхне	N;NOM;PL;PSS1S
урядамс	урядави	V;SG;3;TR;PASS;LGSPEC1
орта	ортась	N;NOM;DEF;SG;LGSPEC1
пильге	пильгстот	N;IN+ABL;SG;PSS2S
цёрабай	цёрабай	N;HUM;NOM;SG
юрист	юристтнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
кабинка	кабинкать	N;GEN;DEF;SG;LGSPEC1
щеня	щенясь	N;HUM;NOM;DEF;SG
потяфа	потяфань	N;GEN;SG
бизнес	бизнесонцты	N;DAT;SG;PSS3S;LGSPEC1
спектакль	спектакль	N;NOM;SG;LGSPEC1
кши	кши	N;NOM;SG
артист	артистоньке	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
минимум	минимумсна	N;NOM;SG;PSS3P;LGSPEC1
кемамс	кематада	V;PL;2;INTR
ёфкс	ёфксонц	N;GEN;SG;PSS3S
нардамс	нардамс	V;NFIN;TR
сталма	сталмотнень	N;GEN;DEF;PL
отрасля	отрасляса	N;IN+ESS;SG;LGSPEC1
кфчядемс	кфчядсть	V;AC3;PL;2;INTR
юроньбула	юроньбулось	N;NOM;DEF;SG
уроз	урост	N;HUM;NOM;PL
вешемс	вешендевсть	V;AC3;IMP;PL;2;TR;PASS
седьвальмя	седьвальмат	N;NOM;PL
пефтома	пефтома	ADJ
вайме	ваймоньке	N;NOM;SG;PSS1P
мечта	мечта	N;NOM;SG;LGSPEC1
святитель	святительти	N;HUM;DAT;DEF;SG;LGSPEC1
керф	керфтада	N;PL;2
люпштамс	люпштафоль	V.PTCP;SG;3;PST;TR
калмамс	калмамс	V;NFIN;TR
регион	региону	N;AT+ALL;SG;LGSPEC1
снаряд	снаряттнень	N;GEN;DEF;PL;LGSPEC1
кал	калда	N;HUM;ABL;SG
эняльдемс	эняльдезевонь	V;SG;1;PST;TR
няемс	няендемс	V;NFIN;TR
купец	купецнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
абзац	абзацонц	N;GEN;SG;PSS3S;LGSPEC1
солдат	солдаттнень	N;HUM;GEN;PL;PSS2S;LGSPEC1
кемамс	кемасть	V;PL;3;PST;INTR
магия	магияц	N;NOM;SG;PSS3S;LGSPEC1
парамс	парасть	V;AC3;PL;2;INTR
кредит	кредитс	N;IN+ALL;SG;LGSPEC1
тетрадь	тетраднень	N;GEN;PL;PSS1S;LGSPEC1
фестиваль	фестивальсонза	N;IN+ESS;SG;PSS3S;LGSPEC1
обзор	обзорхт	N;NOM;PL;LGSPEC1
ваномс	ванфсонза	V.PTCP;IN+ESS;SG;PSS3S;PST;TR
азкс	азксоц	N;NOM;SG;PSS3S
каникулат	каникулатне	N;NOM;DEF;PL;LGSPEC1
сырзавод	сырзаводса	N;IN+ESS;SG;LGSPEC1
грамотнай	грамотнайста	ADJ;IN+ABL;SG;LGSPEC1
центра	центранзон	N;GEN;PL;PSS3S;LGSPEC1
преподаватель	преподавательдонк	N;HUM;ABL;SG;PSS1P;LGSPEC1
ногай	ногайхнень	N;HUM;GEN;PL;PSS1S
сувенир	сувенироньке	N;NOM;SG;PSS1P;LGSPEC1
лядемс	лятьфтольхть	V;PL;3;RMT;CAUS
шоссе	шоссева	N;PROL;SG;LGSPEC1
работамс	работакшнесть	V;PL;3;PST;TR;LGSPEC1
поладомс	полаткшнесыне	V;AC3P;SG;3;TR
пача	пачафтома	N;PRIV;SG
структура	структуранзонды	N;DAT;PL;PSS3S;LGSPEC1
смузь	смузти	N;DAT;DEF;SG
варя	варясь	N;NOM;DEF;SG
ёлкань	елкань	ADJ;LGSPEC1
школа	школаста	N;IN+ABL;SG;LGSPEC1
шар	шарда	N;ABL;SG;LGSPEC1
демократия	демократиянь	N;GEN;SG;LGSPEC1
агрономия	агрономиянь	N;GEN;SG;LGSPEC1
агрохолдинг	агрохолдинкнень	N;GEN;PL;PSS1S;LGSPEC1
царь	царень	N;HUM;GEN;SG;LGSPEC1
евро	евро	N;NOM;SG;LGSPEC1
лопа	лопатненди	N;DAT;PL;PSS2S
рекордсмен	рекордсметт	N;HUM;NOM;PL;LGSPEC1
праймериз	праймеризти	N;DAT;DEF;SG;LGSPEC1
рис	риска	N;PROL;SG;LGSPEC1
музыка	музыка	N;NOM;SG;LGSPEC1
налог	налогонди	N;DAT;SG;LGSPEC1
шкай	шкайсна	N;NOM;SG;PSS3P
печения	печенияса	N;IN+ESS;SG;LGSPEC1
тядя	тядятнень	N;HUM;GEN;DEF;PL
видеоролик	видеороликонь	N;GEN;SG;LGSPEC1
забота	заботафтома	N;PRIV;SG;LGSPEC1
ётай	етайть	ADJ;GEN;DEF;SG
тираж	тиражснон	N;GEN;SG;PSS3P;LGSPEC1
областной	областной	ADJ;LGSPEC1
династия	династиять	N;GEN;DEF;SG;LGSPEC1
киви	кивинь	N;GEN;SG
мекольце	мекольцетнень	ADJ;GEN;DEF;PL
сока	сокаян	N;SG;1;LGSPEC1
коромысла	коромысла	N;NOM;SG;LGSPEC1
фестиваль	фестивальхненди	N;DAT;PL;PSS1S;LGSPEC1
уйгур	уйгурхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
шиньгучка	шиньгучкась	N;NOM;DEF;SG
рахамс	рахазевонь	V;SG;1;PST;INTR
корянь	корянь	N;NOM;SG;LGSPEC1
философия	философия	N;NOM;SG;LGSPEC1
гороскоп	гороскоп	N;NOM;SG;LGSPEC1
ульця	ульцяват	N;PROL;SG;PSS2S;LGSPEC1
драгоценность	драгоценностенди	N;DAT;SG;LGSPEC1
геология	геологиянь	N;GEN;SG;LGSPEC1
рьвяяй	рьвяяй	N;HUM;NOM;SG
абон	абон	ADJ
региональнай	региональнай	ADJ;LGSPEC1
педагог	педагогснонды	N;HUM;DAT;SG;PSS3P;LGSPEC1
награда	награда	N;NOM;SG;LGSPEC1
разработка	разработканзон	N;GEN;PL;PSS3S;LGSPEC1
морфема	морфемань	N;GEN;SG;LGSPEC1
вандолгодомс	вандолгодсь	V;SG;3;PST;INTR
оформления	оформлениянь	N;GEN;SG;LGSPEC1
желудка	желудкань	N;GEN;SG;LGSPEC1
шума	шумода	N;ABL;SG
клин	клин	N;NOM;SG;LGSPEC1
юр	юрозост	N;IN+ALL;SG;PSS3P
батрачка	батрачкати	N;HUM;DAT;DEF;SG;LGSPEC1
централизация	централизациясна	N;NOM;SG;PSS3P;LGSPEC1
разряд	разрядонь	N;GEN;SG;LGSPEC1
школа-интернат	школа-интернатти	N;DAT;DEF;SG;LGSPEC1
плод	плоттне	N;NOM;PL;PSS2S;LGSPEC1
растениеводства	растениеводстваса	N;IN+ESS;SG;LGSPEC1
руз	рустка	ADJ;NOM;PL;LGSPEC_AMP
толмар	толмаронь	N;GEN;SG
аш	ашеськ	V;AC3;PL;1
колонна	колоннастост	N;IN+ABL;SG;PSS3P;LGSPEC1
АФУН	афун-ть	N;GEN;DEF;SG;LGSPEC1
палата	палатав	N;AT+ALL;SG;LGSPEC1
кочкамат	кочкамаса	N;IN+ESS;SG
якорь	якорь	N;NOM;SG;LGSPEC1
грамматика	грамматикань	N;GEN;SG;LGSPEC1
воляши	воляшинцты	N;DAT;SG;PSS3S;LGSPEC1
кельме	кельмонзон	ADJ;GEN;PL;PSS3S
нильготькс	нильготькс	ADJ
сочнай	сочнай	ADJ;LGSPEC1
экономия	экономиянь	N;GEN;SG;LGSPEC1
грушакс	грушаксть	N;GEN;DEF;SG;LGSPEC1
марина	марина	N;NOM;SG
бизнес	бизнести	N;DAT;DEF;SG;LGSPEC1
амбиция	амбиция	N;NOM;SG;LGSPEC1
тястонне	тястоннет	ADJ;NOM;PL
валюта	валютац	N;NOM;SG;PSS3S;LGSPEC1
чёмболямс	чемболяй	V;SG;3;INTR
сокоргодомс	сокоргодсть	V;AC3;PL;2;INTR
романтик	романтикнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
улемс	улендеда	V;IMP;PL;2;INTR
пакся	паксяньке	N;NOM;SG;PSS1P
кува	куване	N;NOM;PL;PSS1S
родительскяй	родительскяй	ADJ;LGSPEC1
сиземс	сизефтови	V;SG;3;CAUS;PASS
торф	торфонкса	N;CAUSV;SG;LGSPEC1
лгун	лгун	N;HUM;NOM;SG;LGSPEC1
архив	архивста	N;IN+ABL;SG;LGSPEC1
наводчик	наводчиксь	N;HUM;NOM;DEF;SG;LGSPEC1
ускомс	ускомань	V;AC1;SG;3;TR
тормоз	тормосне	N;NOM;PL;PSS1S;LGSPEC1
ми	милеть	N;SG;2;PST
техникум	техникупненди	N;DAT;PL;PSS1S;LGSPEC1
кенярдемс	кеняртькшнемс	V;NFIN;INTR
диктор	дикторть	N;HUM;GEN;DEF;SG;LGSPEC1
нолдамс	нолдадязь	V;AC2S;PL;3;TR
линейка	линейка	N;NOM;SG;LGSPEC1
семья	семьяцень	N;GEN;SG;PSS2S;LGSPEC1
свадьбань	свадьбань	ADJ;LGSPEC1
съезд	съездсь	N;NOM;DEF;SG;LGSPEC1
штамс	шташендса	V;AC3S;SG;1;TR
пух	пухсь	N;NOM;DEF;SG;LGSPEC1
буква	буквать	N;GEN;DEF;SG;LGSPEC1
сяшка	сяшкада	ADJ;ABL;SG
полк	полкне	N;NOM;PL;PSS1S;LGSPEC1
вельхкс	вельхксс	N;IN+ALL;SG
нолдамс	нолдафт	V.PTCP;NOM;PL;PST;TR
вийкс	вийкс	N;HUM;NOM;SG
роман	роматт	N;NOM;PL;LGSPEC1
сюре	сюреста	N;IN+ABL;SG
автор	авторсь	N;HUM;NOM;DEF;SG;LGSPEC1
меленця	меленцяньке	N;GEN;SG;LGSPEC_AMP;LGSPEC1
линолеум	линолеум	N;NOM;SG;LGSPEC1
сок	сокса	N;IN+ESS;SG;LGSPEC1
защитник	защитникть	N;HUM;GEN;DEF;SG;LGSPEC1
охотник	охотникне	N;HUM;NOM;DEF;PL;LGSPEC1
организация	организациязонк	N;IN+ALL;SG;PSS1P;LGSPEC1
знахарь	знахарьхне	N;HUM;NOM;PL;PSS1S;LGSPEC1
мзолдомс	мзолдсть	V;AC3;PL;2;INTR
юбилей	юбилейсна	N;NOM;SG;PSS3P;LGSPEC1
помидора	помидоратне	N;NOM;DEF;PL;LGSPEC1
техника	техникафтома	N;PRIV;SG;LGSPEC1
ЖКХ	жкх-ти	N;DAT;DEF;SG;LGSPEC1
замполит	замполитсь	N;HUM;NOM;DEF;SG;LGSPEC1
ментюк	ментюконь	N;HUM;GEN;SG
товар	товаронкса	N;CAUSV;SG;LGSPEC1
реструктуризация	реструктуризацияснон	N;GEN;SG;PSS3P;LGSPEC1
спортсмен	спортсменцнон	N;HUM;GEN;SG;PSS3P;LGSPEC1
эрьгаскодомс	эрьгаскоткшнемс	V;NFIN;INTR
лингвистическяй	лингвистическяй	ADJ;LGSPEC1
лимонад	лимонадонц	N;GEN;SG;PSS3S;LGSPEC1
работамс	работан	V;SG;1;TR;LGSPEC1
осколка	осколкатне	N;NOM;PL;PSS2S;LGSPEC1
инвентарь	инвентарьть	N;NOM;PL;LGSPEC1
конемс	конезень	V;AC3P;SG;3;TR
кочкамат	кочкамац	N;NOM;SG;PSS3S
вии	виихнень	ADJ;GEN;DEF;PL
пиксомс	пиксфоль	V.PTCP;SG;3;PST;TR
эпос	эпосоц	N;NOM;SG;PSS3S;LGSPEC1
адвокат	адвокаттненди	N;HUM;DAT;PL;PSS2S;LGSPEC1
коняфкс	коняфкст	N;NOM;PL
кеву	кеву	ADJ
мишенди	мишенди	N;HUM;NOM;SG
изюм	изюмда	N;ABL;SG;LGSPEC1
руководитель	руководительхнень	N;HUM;GEN;PL;PSS1S;LGSPEC1
горна	горнась	N;NOM;DEF;SG;LGSPEC1
седь	седенди	N;DAT;SG
