чевер	чевер	ADJ;NOM;SG
фар	фар	N;NOM;SG;LGSPEC1
каяш	каяшат	V;NFIN;LGSPEC_AMP;ACT
сантиметр	сантиметрлан	N;DAT;SG;LGSPEC1
кышкаш	кышкем	V;SG;1;ACT
тергаш	тергалтат	V;SG;2;PASS
вучалташ	вучалта	V;SG;3;ACT
кылдаш	кылдалташ	V;NFIN;PASS
тиште	тиште-влаклан	N;DAT;PL
туна	тунамат	N;HUM;NOM;SG;LGSPEC_AMP;PSS1S
шӱяш	шӱяшан	N;NOM;SG;LGSPEC_ATTR
тарлаш	тарлен	V;SG;3;RMT;ACT
чер	черланем	N;DAT;SG;PSS1S
льготник	льготник-влаклан	N;HUM;DAT;PL;LGSPEC1
йоча	йочалак	N;HUM;SIM;SG;LGSPEC_EMPH
унагудо	унагудыштат	N;NOM;SG;LGSPEC_AMP;PSS3P
конференц-зал	конференц-залыште	N;IN+ESS;SG;LGSPEC1
лу	лумлак	N;SIM;SG;LGSPEC_EMPH;PSS1S
мал	малем	N;NOM;SG;PSS1S
тариф	тарифын	N;GEN;SG;LGSPEC1
совет	советшылан	N;DAT;SG;PSS3S;LGSPEC1
шижаш	шижынна	V;PL;1;RMT;ACT
анонс	анонсым	N;ACC;SG;LGSPEC1
йолташ	йолташ-влакыш	N;HUM;IN+ALL;PL
шӱм-кыл	шӱм-кылет	N;NOM;SG;PSS2S
пураш	пуредат	V;PL;LGSPEC_AMP;2;ACT
аппетит	аппетитлан	N;DAT;SG;LGSPEC1
кӱшташ	куштышда	V;PL;2;PST;ACT
мокшо	мокшышто	N;HUM;IN+ESS;SG
кылдаш	кылдалтынам	V;SG;1;RMT;PASS
уш	ушла	N;SIM;SG
сай	саламлат	ADJ;SIM;SG;LGSPEC_AMP;PSS1S
савыктыш	савыктышлан	N;DAT;SG
каныш	канышын	N;GEN;SG
старт	стартыште	N;IN+ESS;SG;LGSPEC1
эмблеме	эмблемыжлан	N;DAT;SG;PSS3S;LGSPEC1
явлений	явленийже	N;NOM;SG;PSS3S;LGSPEC1
механизм	механизмжым	N;ACC;SG;PSS3S;LGSPEC1
изданий	изданийлаш	N;IN+ALL;PL;LGSPEC1
арулык	арулык	N;NOM;SG
показатель	показательлан	N;DAT;SG;LGSPEC1
шӱм-кыл	шӱм-кылна	N;NOM;SG;PSS1P
шочаш	шоч	V;IMP;SG;2;ACT
шотлаш	шотлыктет	V;SG;2;CAUS;ACT
вата	ватывᵊлаклан	N;DAT;PL;LGSPEC1
каче	качынат	N;HUM;NOM;SG;LGSPEC_AMP;PSS1P
когарташ	когарташак	V;NFIN;LGSPEC_EMPH;ACT
шопкер	шопкержын	N;GEN;SG;PSS3S
шуаш	шуда	V;PL;2;PST;ACT
ту	тудак	N;NOM;SG;LGSPEC_EMPH;PSS2P
ӱштӧ	уштымак	N;ACC;SG;LGSPEC_EMPH
раздел	раздел	N;NOM;SG;LGSPEC1
тор	торешышт	N;ALL;SG;PSS3P
куштызо	куштызым	N;HUM;ACC;SG
памятник	памятникшылан	N;DAT;SG;PSS3S;LGSPEC1
керташ	кертынак	V;SG;LGSPEC_EMPH;3;RMT;ACT
отметке	отметкылам	N;ACC;PL;LGSPEC1
келгемаш	келгемынам	V;SG;1;RMT;ACT
йыдал	йыдалымак	N;ACC;SG;LGSPEC_EMPH
лу	лужо-влак	N;NOM;PL;PSS3S
кече	кечылажым	N;ACC;SIM;SG;PSS3S
кумыл	кумылан-влакым	N;ACC;PL;LGSPEC_ATTR
проект	проектнам	N;ACC;SG;PSS1P;LGSPEC1
пераш	пералтше	V;IMP;SG;3;PASS
чын	чынын	N;GEN;SG
уровень	уровеньласе	N;NOM;PL;LGSPEC_ATTR;LGSPEC1
радиоузел	радиоузелыш	N;IN+ALL;SG;LGSPEC1
ошкылаш	ошкылынат	V;SG;LGSPEC_AMP;3;RMT;ACT
лудаш	лудат	V;IMP;SG;LGSPEC_AMP;2;ACT
муро	мурыштымат	N;ACC;SG;LGSPEC_AMP;PSS3P
учитель	учителем	N;HUM;NOM;SG;PSS1S;LGSPEC1
таҥасаш	таҥасашат	V;NFIN;LGSPEC_AMP;ACT
юмылташ	юмылтен	V;SG;3;RMT;ACT
аҥыртараш	аҥыртараш	V;NFIN;ACT
тайне	тайнылан	N;DAT;SG;LGSPEC1
коллекций	коллекций	N;NOM;SG;LGSPEC1
титак	титаканжым	N;ACC;SG;LGSPEC_ATTR;PSS3S
хоккеист	хоккеистлан	N;HUM;DAT;SG;LGSPEC1
кочай	кочайым	N;HUM;ACC;SG
медаль	медальже-влакым	N;ACC;PL;PSS3S;LGSPEC1
община	общиныштак	N;NOM;SG;LGSPEC_EMPH;PSS3P;LGSPEC1
чӧкай	чокайын	ADJ;GEN;SG
инфраструктура	инфраструктура	N;NOM;SG;LGSPEC1
кынелаш	кынелыда	V;PL;2;ACT
йол	йолын	N;GEN;SG
пӱгаш	пугалт	V;NEG;PASS
тар	тар	N;NOM;SG
чактараш	чактараш	V;NFIN;ACT
экран	экранышкына	N;IN+ALL;SG;PSS1P;LGSPEC1
йылме	йылмыштыже	N;IN+ESS;SG;PSS3S
лудо	лудыланат	N;HUM;SIM;SG;LGSPEC_AMP;PSS1P
колхоз	колхозлан	N;DAT;SG;LGSPEC1
пеҥгыдылык	пеҥгыдылыкшат	N;NOM;SG;LGSPEC_AMP;PSS3S
ӧк	окымемым	N;ACC;SG;PSS1S
вуй	вуйымак	N;ACC;SG;LGSPEC_EMPH
привилегий	привилегийым	N;ACC;SG;LGSPEC1
сакаш	сакат	V;LGSPEC_AMP;NEG;ACT
чер	черет	N;NOM;SG;PSS2S
йӱд	йӱдем	N;NOM;SG;PSS1S
порылык	порылыкышт	N;NOM;SG;PSS3P
куан	куаныштат	N;NOM;SG;LGSPEC_AMP;PSS3P
нераш	нерат	V;LGSPEC_AMP;NEG;ACT
чумыраш	чумырат	V;LGSPEC_AMP;NEG;ACT
нелаш	нелам	V;SG;1;ACT
документ	документ-влаклан	N;DAT;PL;LGSPEC1
вер	верладам	N;ACC;PL;PSS2P
лӱмнер	лӱмнердам	N;ACC;SG;PSS2P
портрет	портрет-влакын	N;GEN;PL;LGSPEC1
пулаштараш	пулаштарышт	V;IMP;PL;3;ACT
ритмика	ритмикылан	N;DAT;SG;LGSPEC1
йодаш	йодынна	V;PL;1;RMT;ACT
йылме	йылмыштынат	N;GEN;SG;LGSPEC_AMP;PSS3P
сӧрасаш	сӧрасенам	V;SG;1;RMT;ACT
туфльо	туфльыж	N;NOM;SG;PSS3S;LGSPEC1
иземдаш	иземденыт	V;PL;3;RMT;ACT
иге	иге-влакын	N;HUM;GEN;PL
йӱла	йӱлалын	N;GEN;SG;LGSPEC_ATTR
рейд	рейдыште	N;IN+ESS;SG;LGSPEC1
продуктивность	продуктивностян	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
изданий	изданийыштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
колхоз	колхозышт-влакым	N;ACC;PL;PSS3P;LGSPEC1
кӱ	кумытынак	N;GEN;LGSPEC_EMPH;LGSPEC2
пластинке	пластинкыште	N;IN+ESS;SG;LGSPEC1
тренироватлаш	тренироватлаш	V;NFIN;ACT;LGSPEC1
артыраш	артыра	V;SG;3;ACT
шочаш	шочыктыш	V;SG;3;PST;CAUS;ACT
радамлаш	радамлат	V;PL;3;ACT;LGSPEC1
ролик	роликан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
поҥгаҥаш	поҥгаҥеш	V;SG;3;ACT
икгайлык	икгайлыкышт	N;NOM;SG;PSS3P
ора	оралат	N;NOM;PL;LGSPEC_AMP
орландараш	орландарат	V;SG;LGSPEC_AMP;3;ACT
кушкыжаш	кушкыжынам	V;SG;1;RMT;ACT
сеҥаш	сеҥышат	V;SG;LGSPEC_AMP;3;PST;ACT
уш	ушнан	N;GEN;SG;PSS1P
фуфайка	фуфайкыдан	N;GEN;SG;PSS2P;LGSPEC1
журнал	журналлан	N;DAT;SG;LGSPEC1
кокша	кокшам	N;ACC;SG
саламлалташ	саламлалтыныт	V;PL;3;RMT;ACT
палемдаш	палемдышт	V;IMP;PL;3;ACT
лицо	лицо-влаклан	N;DAT;PL;LGSPEC1
тӱяш	тӱеныт	V;PL;3;RMT;ACT
арка	аркасе	N;NOM;SG;LGSPEC_ATTR
памятник	памятникышт-влак	N;NOM;PL;PSS3P;LGSPEC1
кож	кожын	N;GEN;SG
сӱан	сӱаныштем	N;IN+ESS;SG;PSS1S
учений	учений	N;NOM;SG;LGSPEC1
среда	средаште	N;IN+ESS;SG;LGSPEC1
нелаш	нелыт	V;SG;2;PST;ACT
тайна	тайнем	N;NOM;SG;PSS1S;LGSPEC1
сулык	сулыкем	N;NOM;SG;PSS1S
мияш	миенытат	V;PL;LGSPEC_AMP;3;RMT;ACT
умбал	умбал	ADJ;NOM;SG
аклаш	аклалтынат	V;PL;LGSPEC_AMP;1;PASS
орва	орвалан	N;DAT;SG
кнага	кнагалан	N;DAT;SG;LGSPEC1
шондык	шондыкге	N;COM;SG
ӧртньӧр	ӧртньӧр	N;NOM;SG
шурно	шурно	N;NOM;SG
карт	карт-влакым	N;ACC;PL;LGSPEC1
лугаш	лугенат	V;SG;2;RMT;ACT
станций	станцийым	N;ACC;SG;LGSPEC1
черландараш	черландараш	V;NFIN;ACT
кумыл	кумылланат	N;SIM;SG;LGSPEC_AMP;PSS1P
пыльгыжаш	пыльгыжын	V;SG;3;RMT;ACT
лӱшкаш	лӱшкенат	V;SG;2;RMT;ACT
канцелярий	канцелярийыштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
этнографий	этнографийлан	N;DAT;SG;LGSPEC1
метр	метрлан	N;DAT;SG;LGSPEC1
икгайлык	икгайлыкше	N;NOM;SG;PSS3S
прозо	прозыжо	N;NOM;SG;PSS3S;LGSPEC1
карт	картыште	N;HUM;IN+ESS;SG
онаш	оныктеныт	V;PL;3;RMT;CAUS;ACT
настроений	настроениетын	N;GEN;SG;PSS2S;LGSPEC1
направлений	направлениян	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
пушеҥге	пушеҥгынат	N;GEN;SG;LGSPEC_AMP
билет	билет	N;NOM;SG;LGSPEC1
мураш	муреныт	V;PL;3;RMT;ACT
ӱдыр	ӱдырышт-влакым	N;HUM;ACC;PL;PSS3P
фотографий	фотографийышт	N;NOM;SG;PSS3P;LGSPEC1
чумаш	чумаш	V;NFIN;ACT
рӱзалташ	рӱзалтат	V;IMP;SG;LGSPEC_AMP;2;ACT
срок	срокан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
тӧршташ	тӧрштыш	V;SG;3;PST;ACT
император	императорлан	N;HUM;DAT;SG;LGSPEC1
воштылташ	воштылтет	V;SG;2;ACT
толаштараш	толаштарат	V;SG;LGSPEC_AMP;3;ACT
сылнылык	сылнылыкше	N;NOM;SG;PSS3S
темаш	темалтыт	V;SG;2;PST;PASS
лаборантка	лаборанткам	N;HUM;ACC;SG;LGSPEC1
шешке	шешкымат	N;HUM;ACC;SG;LGSPEC_AMP
статистике	статистикын	N;GEN;SG;LGSPEC1
кусаркалаш	кусаркален	V;SG;3;RMT;ACT
фотографий	фотографийыште	N;IN+ESS;SG;LGSPEC1
алаш	алак	V;SG;LGSPEC_EMPH;3;ACT
ор	ордам	N;ACC;SG;PSS2P
шок	шокшат	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
ача-ава	ача-авашт-влаклан	N;HUM;DAT;PL;PSS3P
герб	гербшым	N;ACC;SG;PSS3S;LGSPEC1
саман	саманынат	N;GEN;SG;LGSPEC_AMP
ыреслаш	ыреслаш	V;NFIN;ACT
писатель	писательже	N;HUM;NOM;SG;PSS3S;LGSPEC1
подвиг	подвигше	N;NOM;SG;PSS3S;LGSPEC1
кабин	кабиныштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
экзамен	экзаменын	N;GEN;SG;LGSPEC1
пелешташ	пелештышна	V;PL;1;PST;ACT
поланвондо	поланвондышто	N;IN+ESS;SG
тугаш	тугак	V;SG;LGSPEC_EMPH;3;ACT
чия	чияшат	N;IN+ALL;SG;LGSPEC_AMP
салтак	салтак-влакын	N;HUM;GEN;PL;LGSPEC1
ветеран	ветеранышт	N;HUM;NOM;SG;PSS3P;LGSPEC1
пураш	пурат	V;IMP;SG;LGSPEC_AMP;2;ACT
еҥ	еҥжым	N;HUM;ACC;SG;PSS3S
пыташ	пытен	V;SG;3;RMT;ACT
муро	мурем	N;NOM;SG;PSS1S
вияш	виет	V;SG;2;ACT
титак	титак	N;NOM;SG
полк	полкшын	N;GEN;SG;PSS3S;LGSPEC1
ӱшандараш	ӱшандарат	V;PL;3;ACT
ий	ий	N;NOM;SG
кӱ	кумытымат	N;ACC;LGSPEC_AMP;LGSPEC2
лунчырташ	лунчыртат	V;LGSPEC_AMP;NEG;ACT
палемдаш	палемдалтым	V;SG;1;PST;PASS
мастарлык	мастарлыкшын	N;GEN;SG;PSS3S;LGSPEC1
воспитатель	воспитательже	N;HUM;NOM;SG;PSS3S;LGSPEC1
решений	решенийым	N;ACC;SG;LGSPEC1
коллекций	коллекцийлаштат	N;SIM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
нералташ	нералтен	V;SG;3;RMT;ACT
тугаш	тугалт	V;IMP;SG;2;PASS
оҥ	оҥешем	N;ALL;SG;PSS1S
намияш	намиена	V;PL;1;ACT
выле	вылетым	N;ACC;SG;PSS2S
лупшаш	лупшалтынат	V;SG;2;RMT;PASS
нитрат	нитратын	N;GEN;SG;LGSPEC1
салат	салат-влак	N;NOM;PL
медсестра	медсестра-влаклан	N;HUM;DAT;PL;LGSPEC1
орландараш	орландаре	V;IMP;SG;2;ACT
вокзал	вокзалласе	N;PL;LGSPEC_ATTR;LGSPEC1
приоритетный	приоритетныйлан	ADJ;DAT;SG;LGSPEC1
доллар	долларым	N;ACC;SG;LGSPEC1
салтак	салтакак	N;HUM;NOM;SG;LGSPEC_EMPH;LGSPEC1
салам	саламлымышт	N;ACC;SG;LGSPEC_ATTR;PSS3P
чапландараш	чапландаре	V;IMP;SG;2;ACT
шуйналташ	шуйналт	V;IMP;SG;2;ACT
подпись	подписьла	N;SIM;SG;LGSPEC1
давлений	давлениетым	N;ACC;PSS2S;LGSPEC1
квитанций	квитанцийдам	N;ACC;SG;PSS2P;LGSPEC1
газет	газетыштыда	N;IN+ESS;SG;PSS2P;LGSPEC1
юватылаш	юватыл	V;IMP;SG;2;ACT
титак	титакетланат	N;DAT;SG;LGSPEC_AMP;PSS2S
сакаш	сакышт	V;IMP;PL;3;ACT
полдыш	полдышто	N;IN+ESS;SG
коча	кочажлан	N;HUM;DAT;SG;PSS3S
йӱла	йӱлажымат	N;ACC;SG;LGSPEC_AMP;PSS3S
постановка	постановкышт	N;NOM;SG;PSS3P;LGSPEC1
открытке	открытке-влакым	N;ACC;PL;LGSPEC1
двигатель	двигателет	N;NOM;SG;PSS2S;LGSPEC1
медперсонал	медперсоналланат	N;DAT;SG;LGSPEC_AMP;LGSPEC1
системе	системыжлан	N;DAT;SG;PSS3S;LGSPEC1
вазе	вазыште	N;IN+ESS;SG
врач	врачланат	N;HUM;DAT;SG;LGSPEC_AMP;LGSPEC1
ойыраш	ойыреныт	V;PL;3;RMT;ACT
модаш	модыктеныт	V;PL;3;RMT;CAUS;ACT
ӱп	ӱпешышт	N;ALL;SG;PSS3P
лектедаш	лектедат	V;PL;3;ACT
музей	музей-влакым	N;ACC;PL;LGSPEC1
сӧрастараш	сӧрастарышт	V;PL;3;PST;ACT
навык	навыкем	N;NOM;SG;PSS1S;LGSPEC1
васлий	васлийлан	N;DAT;SG
ор	орлаеш	N;ALL;PL
вынер	вынер	N;NOM;SG
тулык	тулыкым	N;HUM;ACC;SG
сото	сотылан	N;DAT;SG
банк	банклан	N;DAT;SG;LGSPEC1
мут	мутемланат	N;DAT;SG;LGSPEC_AMP;PSS1S
возкалаш	возкалыза	V;IMP;PL;2;ACT
рецепт	рецептше	N;NOM;SG;PSS3S;LGSPEC1
шокш	шокшетлан	N;DAT;SG;PSS2S
кече	кечыжак	N;NOM;SG;LGSPEC_EMPH;PSS3S
онаш	онышт	V;PL;3;PST;ACT
сарзе	сарзан	N;HUM;NOM;SG;LGSPEC_ATTR
кӱ	кӱшт	N;NOM;SG;PSS3P
перекрёсток	перекрестокышто	N;IN+ESS;SG;LGSPEC1
тюрка	тюркым	N;HUM;ACC;SG;LGSPEC1
кучаш	кучыктет	V;SG;2;CAUS;ACT
мураш	муралтат	V;LGSPEC_AMP;NEG;PASS
сово	совет-влакым	N;ACC;PL;PSS2S
тамгалаш	тамгалалтса	V;IMP;PL;2;PASS
коҥга	коҥгашкыже	N;IN+ALL;SG;PSS3S
пӧртыш	пӧртыштет	N;IN+ESS;SG;PSS2S
палемдаш	палемдаш	V;NFIN;ACT
пураш	пурдак	V;IMP;PL;LGSPEC_EMPH;2;ACT
шараш	шарат	V;SG;LGSPEC_AMP;3;ACT
курык	курыкнат	N;NOM;SG;LGSPEC_AMP;PSS1P
приговор	приговорым	N;ACC;SG;LGSPEC1
пудий	пудий-влак	N;HUM;NOM;PL
йодышташ	йодыштыт	V;PL;3;ACT
пеледыш	пеледышлашке	N;IN+ALL;PL
кундем	кундемлашт	N;SIM;SG;PSS3P
пистолет	пистолетлан	N;DAT;SG;LGSPEC1
кага	кагак	N;NOM;SG;LGSPEC_EMPH
эртараш	эртарынет	V;OPT;SG;2;ACT
труппа	труппышто	N;IN+ESS;SG;LGSPEC1
волташ	волтеда	V;PL;2;ACT
шурка	шуркалат	N;SIM;SG;LGSPEC_AMP
оварташ	оварта	V;SG;3;ACT
вияҥдаш	вияҥдышым	V;SG;1;PST;ACT
чӧкай	чокайнан	ADJ;GEN;SG;PSS1P
отрасль	отрасльыштын	N;GEN;SG;PSS3P;LGSPEC1
изай	изайлан	N;HUM;DAT;SG
юмо	юмышт	N;NOM;SG;PSS3P
пӱраш	пуретат	V;SG;LGSPEC_AMP;2;ACT
ува	уват	ADJ;NOM;SG;LGSPEC_AMP
пациент	пациентшым	N;HUM;ACC;SG;PSS3S;LGSPEC1
защитник	защитник	N;HUM;NOM;SG;LGSPEC1
лекций	лекцийда-влак	N;NOM;PL;PSS2P;LGSPEC1
урок	урокла	N;SIM;SG;LGSPEC1
лудаш	луднеда	V;OPT;PL;2;ACT
норматив	нормативыш	N;IN+ALL;SG;LGSPEC1
вӱта	вӱташтым	N;ACC;SG;PSS3P
сокта	соктамат	N;NOM;SG;LGSPEC_AMP;PSS1S
кумыл	кумылемын	N;GEN;SG;PSS1S
ӱдыръеҥ	ӱдыръеҥ-влак	N;HUM;NOM;PL
пӱраш	пурашат	N;HUM;NOM;SG;LGSPEC_AMP
курчак	курчакшым	N;ACC;SG;PSS3S
кышкаш	кышкалт	V;IMP;SG;2;PASS
идеологий	идеологийже	N;NOM;SG;PSS3S;LGSPEC1
пыташ	пытенат	V;SG;2;RMT;ACT
театр	театрыштынат	N;GEN;SG;LGSPEC_AMP;PSS3P;LGSPEC1
авагудо	авагудыжым	N;ACC;SG;PSS3S
интернет	интернетынышт	N;GEN;SG;PSS3P;LGSPEC1
ял	ялешемак	N;ALL;SG;LGSPEC_EMPH;PSS1S
группа	группа-влакым	N;ACC;PL;LGSPEC1
чек	чекшым	N;ACC;SG;PSS3S;LGSPEC1
пурышташ	пурышт	V;NEG;ACT
ушештараш	ушештаралтын	V;SG;3;RMT;PASS
озавате	озавате-влакын	N;HUM;GEN;PL
вашкаш	вашкенам	V;SG;1;RMT;ACT
ӧндалаш	ондалалтна	V;PL;1;PST;PASS
нӱшкӧ	нушкына	ADJ;NOM;SG;PSS1P
мультфильм	мультфильм	N;NOM;SG;LGSPEC1
ӱмбал	умбалын	N;GEN;SG
йол	йолыштым	N;ACC;SG;PSS3P
давлений	давленийлан	N;DAT;SG;LGSPEC1
ончаш	ончыктат	V;SG;LGSPEC_AMP;3;CAUS;ACT
тор	торлашат	ADJ;ALL;SIM;SG;LGSPEC_AMP
нӱж	нуждам	N;ACC;SG;PSS2P
ил	илшыланак	N;DAT;SG;LGSPEC_EMPH;PSS3S;LGSPEC1
порылык	порылыкыштыжо	N;IN+ESS;SG;PSS3S
туара	туарамат	N;NOM;SG;LGSPEC_AMP;PSS1S
пылвомыш	пылвомышыш	N;IN+ALL;SG
родо	родыжын	N;HUM;GEN;SG;PSS3S;LGSPEC1
икшыве	икшывыжым	N;HUM;ACC;SG;PSS3S
чумалаш	чумалнеже	V;OPT;SG;3;ACT
кугезе	кугезыштлан	N;HUM;DAT;SG;PSS3P
пулаштараш	пулаштаренам	V;SG;1;RMT;ACT
лекций	лекцийыштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
пайремле	пайремлын	ADJ;GEN;SG
вашешташ	вашештышна	V;PL;1;PST;ACT
ой	ойлымым	N;ACC;SG;LGSPEC_ATTR
операций	операцийланат	N;SIM;SG;LGSPEC_AMP;PSS1P;LGSPEC1
родо	родет	N;HUM;NOM;SG;PSS2S;LGSPEC1
мушкаш	мушкыч	V;PL;3;PST;ACT
вер	верышкыжак	N;IN+ALL;SG;LGSPEC_EMPH;PSS3S
латыш	латышла	N;HUM;SIM;SG;LGSPEC1
кожа	кожыштак	N;NOM;SG;LGSPEC_EMPH;PSS3P;LGSPEC1
вашлияш	вашлийынамат	V;SG;LGSPEC_AMP;1;RMT;ACT
сказуемый	сказуемыят	N;NOM;SG;LGSPEC_AMP;LGSPEC1
ломбо	ломбын	N;GEN;SG
монтироватлаш	монтироватлат	V;PL;3;ACT;LGSPEC1
тушман	тушманлылан	N;HUM;DAT;SG;LGSPEC_ATTR
орава	оравам	N;ACC;SG
экран	экраным	N;ACC;SG;LGSPEC1
пӧрт	портемын	N;GEN;SG;PSS1S
клиент	клиентшын	N;HUM;GEN;SG;PSS3S;LGSPEC1
колбаса	колбасат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
игылташ	игылтнем	V;OPT;SG;1;ACT
пасаш	пасыш	V;SG;3;PST;ACT
молемаш	молемаш	V;NFIN;ACT
кӱ	кумдак	N;ACC;SG;LGSPEC_EMPH;PSS2P
шочаш	шочыктышт	V;PL;3;PST;CAUS;ACT
шинчал	шинчаланже	N;NOM;SG;LGSPEC_ATTR;PSS3S
пиал	пиалжылан	N;DAT;SG;PSS3S
мокташ	моктат	V;LGSPEC_AMP;NEG;ACT
министерстве	министерствышкыжат	N;IN+ALL;SG;LGSPEC_AMP;PSS3S;LGSPEC1
нагрузко	нагрузкылан	N;DAT;SG;LGSPEC1
шарик	шарикна	N;NOM;SG;PSS1P;LGSPEC1
портрет	портретыштышт	N;IN+ESS;SG;PSS3P;LGSPEC1
шиша	шишадам	N;ACC;SG;PSS2P
шогаш	шогышт	V;PL;3;PST;ACT
эрге	эргыжын	N;HUM;GEN;SG;PSS3S
пӱкш	пукшымым	N;ACC;SG
чымыш	чымышым	N;ACC;SG
модаш	моднеже	V;OPT;SG;3;ACT
лышташ	лышташыш	N;IN+ALL;SG
мине	миныштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
кнага	кнаганам	N;ACC;SG;PSS1P;LGSPEC1
община	общинынанат	N;GEN;SG;LGSPEC_AMP;PSS1P;LGSPEC1
ишке	ишкыште	N;IN+ESS;SG
пеледыш	пеледыш-влакланат	N;DAT;PL;LGSPEC_AMP
кучаш	кучышна	V;PL;1;PST;ACT
кӱлаш	кулынам	V;SG;1;RMT;ACT
наследий	наследийышкыже	N;IN+ALL;SG;PSS3S;LGSPEC1
кӱдаш	кудалтыт	V;PL;3;PASS
шогаш	шогат	V;SG;LGSPEC_AMP;3;ACT
полко	полкышт	N;NOM;SG;PSS3P;LGSPEC1
причёско	прическыжо	N;NOM;SG;PSS3S;LGSPEC1
магыраш	магыр	V;NEG;ACT
совет	советшын	N;GEN;SG;PSS3S;LGSPEC1
чап	чапшылан	N;DAT;SG;PSS3S
йыдал	йыдалжым	N;ACC;SG;PSS3S
тыршаш	тыршышна	V;PL;1;PST;ACT
мондаш	мондеда	V;PL;2;ACT
карт	картак	N;NOM;SG;LGSPEC_EMPH;LGSPEC1
орава	ораваштым	N;ACC;SG;PSS3P
шурка	шурканат	N;GEN;SG;LGSPEC_AMP
пуш	пушемын	N;GEN;SG;PSS1S
ойласаш	ойласат	V;PL;3;ACT
парня	парнят	N;NOM;SG;LGSPEC_AMP
кына	кынат	ADJ;NOM;SG;LGSPEC_AMP
мужыр	мужырет	N;NOM;SG;PSS2S
кинде	киндышт	N;NOM;SG;PSS3P
пеҥгыдемдаш	пеҥгыдемденна	V;PL;1;RMT;ACT
пайрем	пайремдан	N;GEN;SG;PSS2P
кӱ	куанышна	N;IN+ALL;SG;LGSPEC_ATTR;PSS1P
лӱшташ	лӱштена	V;PL;1;ACT
совхоз	совхозысо	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
сайт	сайтышкышт	N;IN+ALL;SG;PSS3P;LGSPEC1
иго	игылыш	N;IN+ALL;SG;LGSPEC_ATTR;LGSPEC1
колташ	колтынена	V;OPT;PL;1;ACT
коча	кочамат	N;HUM;NOM;SG;LGSPEC_AMP;PSS1S
тариф	тарифышт	N;NOM;SG;PSS3P;LGSPEC1
сарзе	сарзын	N;HUM;GEN;SG
экзамен	экзаменымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
союз	союзышто	N;IN+ESS;SG;LGSPEC1
руаш	руэнам	V;SG;1;RMT;ACT;LGSPEC1
хор	хорышт	N;NOM;SG;PSS3P;LGSPEC1
шагат	шагатыштат	N;NOM;SG;LGSPEC_AMP;PSS3P
шагалемаш	шагалемыт	V;PL;3;ACT
ак	аклыш	N;IN+ALL;SG;LGSPEC_ATTR
подпрограмма	подпрограммыжым	N;ACC;SG;PSS3S;LGSPEC1
салам	саламлышда	N;IN+ALL;SG;LGSPEC_ATTR;PSS2P
мучашлаш	мучашлыш	V;SG;3;PST;ACT
нелыт	нелытлан	N;DAT;SG
документ	документлаштым	N;ACC;SIM;SG;PSS3P;LGSPEC1
каласкалаш	каласкалат	V;PL;3;ACT
апшат	апшат-влакым	N;HUM;ACC;PL
ӱдыр	ӱдыржынат	N;HUM;GEN;SG;LGSPEC_AMP;PSS3S
пӱкш	пукшышна	N;IN+ALL;SG;PSS1P
батальон	батальон-влак	N;NOM;PL;LGSPEC1
чӧгыт	чӧгытак	N;NOM;SG;LGSPEC_EMPH
дуэт	дуэтыштын	N;GEN;SG;PSS3P;LGSPEC1
куандараш	куандараш	V;NFIN;ACT
йӱла	йӱлашкына	N;IN+ALL;SG;PSS1P
гуляяш	гуляят	V;SG;LGSPEC_AMP;3;ACT;LGSPEC1
лидер	лидерлан	N;HUM;DAT;SG;LGSPEC1
коляска	коляскыште	N;IN+ESS;SG;LGSPEC1
рой	рожышко	N;IN+ALL;SG;PSS3S
йолташ	йолташак	N;HUM;NOM;SG;LGSPEC_EMPH
занятий	занятий	N;NOM;SG;LGSPEC1
батальон	батальоныштыжо	N;IN+ESS;SG;PSS3S;LGSPEC1
служба	служба-влакым	N;ACC;PL;LGSPEC1
экипаж	экипажыш	N;IN+ALL;SG;LGSPEC1
посёлко	посёлкылаштат	N;SIM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
шочмо	шочмемла	N;SIM;SG;PSS1S
аптыранаш	аптыранем	V;SG;1;ACT
штрафной	штрафной	ADJ;NOM;SG;LGSPEC1
пий	пижеш	N;HUM;ALL;SG;PSS3S
промышленник	промышленник-влак	N;HUM;NOM;PL;LGSPEC1
илем	илемат	N;NOM;SG;LGSPEC_AMP
парча	парчат	N;NOM;SG;LGSPEC_AMP
правило	правилышт	N;NOM;SG;PSS3P;LGSPEC1
ӱп	упанна	N;NOM;SG;LGSPEC_ATTR;PSS1P
ола	олалам	N;SIM;SG;PSS1S
кленча	кленчада	N;NOM;SG;PSS2P;LGSPEC1
кумдаҥдаш	кумдаҥдена	V;PL;1;ACT
историй	историйын	N;GEN;SG;LGSPEC1
пар	паранем	N;NOM;SG;LGSPEC_ATTR;PSS1S
чумыраш	чумырынеже	V;OPT;SG;3;ACT
кӱрык	курыкет	N;NOM;SG;PSS2S
мусульман	мусульман-шамычат	N;HUM;NOM;PL;LGSPEC_AMP;LGSPEC1
перевод	переводлак	N;NOM;PL;LGSPEC_EMPH;LGSPEC1
тояш	тойыза	V;IMP;PL;2;ACT
технике	техникем	N;NOM;SG;PSS1S;LGSPEC1
воштылалаш	воштылалыч	V;PL;3;PST;ACT
йӱла	йӱла-влакат	N;NOM;PL;LGSPEC_AMP
манаш	манашат	V;NFIN;LGSPEC_AMP;ACT
районо	районышкына	N;IN+ALL;SG;PSS1P;LGSPEC1
чытыш	чытышет	N;NOM;SG;PSS2S
вашлияш	вашлиям	V;SG;1;ACT
кече	кечыштыда	N;IN+ESS;SG;PSS2P
пӱраш	пуренытат	V;PL;LGSPEC_AMP;3;RMT;ACT
участвоватлаш	участвоватлена	V;PL;1;ACT;LGSPEC1
йодаш	йодымат	V;SG;LGSPEC_AMP;1;PST;ACT
ситаш	ситат	V;PL;3;ACT
пайда	пайдажлан	N;DAT;SG;PSS3S
каватӱр	каватӱрын	N;GEN;SG
училище	училищыштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
верешташ	верештна	V;PL;1;PST;ACT
олмыкташ	олмыктышт	V;PL;3;PST;ACT
тор	торлана	N;SIM;SG;PSS1P
легенде	легендым	N;ACC;SG;LGSPEC1
ола	олаштына	ADJ;IN+ESS;SG;PSS1P
ылыжаш	ылыжат	V;LGSPEC_AMP;NEG;ACT
ласка	ласка	N;HUM;NOM;SG;LGSPEC1
келанаш	келанаш	V;NFIN;ACT
темдышташ	темдыштыт	V;PL;3;ACT
принц	принцше	N;HUM;NOM;SG;PSS3S;LGSPEC1
ода	ода	N;NOM;SG;LGSPEC1
открытке	открыткыжым	N;ACC;SG;PSS3S;LGSPEC1
арня	арняшт	N;NOM;SG;PSS3P
чек	чекышт	N;NOM;SG;PSS3P;LGSPEC1
шерге	шергеже	N;NOM;SG;PSS3S
пудырго	пудыргыжо	N;NOM;SG;PSS3S
сай	саемын	ADJ;GEN;PSS1S
полат	полатыште	N;IN+ESS;SG;LGSPEC1
мутер	мутерласе	N;NOM;PL;LGSPEC_ATTR
эртараш	эртаренда	V;PL;2;RMT;ACT
мланде	мландыштымак	N;ACC;SG;LGSPEC_EMPH;PSS3P
тургыж	тургыжланат	N;SIM;SG;LGSPEC_AMP;PSS1P
моделироватлаш	моделироватлат	V;SG;LGSPEC_AMP;3;ACT;LGSPEC1
чер	черынат	N;GEN;SG;LGSPEC_AMP
ыштылаш	ыштылына	V;PL;1;ACT
кандидатур	кандидатурыштым	N;ACC;SG;PSS3P;LGSPEC1
оборона	оборонылан	N;DAT;SG;LGSPEC1
шараш	шарем	V;SG;1;ACT
орлык	орлыкетым	N;ACC;SG;PSS2S
неле	нелыракла	ADJ;COMPV;SIM;SG
комбиге	комбиге	N;HUM;NOM;SG
черке	черкылаште	N;IN+ESS;PL;LGSPEC1
практика	практикыжымат	N;ACC;SG;LGSPEC_AMP;PSS3S;LGSPEC1
чап	чаплаш	N;IN+ALL;PL
тарла	тарлашыштат	N;HUM;ALL;SG;LGSPEC_AMP;PSS3P
поход	походым	N;ACC;SG;LGSPEC1
ошемаш	ошемын	V;SG;3;RMT;ACT
колой	колоэтым	N;HUM;ACC;SG;PSS2S
вӱчӧ	вучымым	N;ACC;SG
символика	символикан	N;GEN;SG;LGSPEC1
ӱдыр	ӱдырдак	N;HUM;NOM;SG;LGSPEC_EMPH;PSS2P
показатель	показательым	N;ACC;SG;LGSPEC1
шагалемаш	шагалемже	V;IMP;SG;3;ACT
саваш	савыктыш	V;SG;3;PST;CAUS;ACT
весела	веселан	ADJ;GEN;SG;LGSPEC1
уш	ушыштыда	N;IN+ESS;SG;PSS2P
укш	укшла	N;SIM;SG
психолог	психологшо	N;HUM;NOM;SG;PSS3S;LGSPEC1
закон	законыштышт	N;IN+ESS;SG;PSS3P;LGSPEC1
сооружений	сооруженийже	N;NOM;SG;PSS3S;LGSPEC1
сераш	серенат	V;SG;2;RMT;ACT
объект	объектыштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
каныш	каныш	N;NOM;SG
видео	видеожо	N;NOM;SG;PSS3S;LGSPEC1
ойласаш	ойласышат	V;SG;LGSPEC_AMP;3;PST;ACT
кошталаш	кошталынам	V;SG;1;RMT;ACT
перкалаш	перкалат	V;SG;LGSPEC_AMP;3;ACT
копий	копийжым	N;ACC;SG;PSS3S;LGSPEC1
кут	кутаныште	N;IN+ESS;SG;LGSPEC_ATTR
еҥ	еҥнат	N;HUM;NOM;SG;LGSPEC_AMP;PSS1P
эрвел	эрвелешак	N;ALL;SG;LGSPEC_EMPH
класс	классышкына	N;IN+ALL;SG;PSS1P;LGSPEC1
шупшыкташ	шупшыктыкта	V;SG;3;CAUS;ACT
диаспора	диаспора	N;NOM;SG;LGSPEC1
прокурор	прокуроржо	N;HUM;NOM;SG;PSS3S;LGSPEC1
радиоузел	радиоузелым	N;ACC;SG;LGSPEC1
кыраш	кырыктеда	V;PL;2;CAUS;ACT
нушкаш	нушкам	V;SG;1;ACT
муаш	муын	V;SG;3;RMT;ACT
занятий	занятий-влакат	N;NOM;PL;LGSPEC_AMP;LGSPEC1
палас	паласшым	N;ACC;SG;PSS3S
самолёт	самолётат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
там	тамлат	N;SIM;SG;LGSPEC_AMP
сорла	сорлажым	N;ACC;SG;PSS3S
кӱшташ	кушталтынна	V;PL;1;RMT;PASS
сугыньлаш	сугыньлен	V;SG;3;RMT;ACT
ойыртемалташ	ойыртемалт	V;NEG;ACT
дуэт	дуэтат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
вучаш	вученат	V;SG;2;RMT;ACT
ялсовет	ялсоветла	N;NOM;PL;LGSPEC1
керышташ	керыштын	V;SG;3;RMT;ACT
кӱр	куржат	N;NOM;SG;LGSPEC_AMP;PSS3S
изданий	изданий	N;NOM;SG;LGSPEC1
олмыкташ	олмыкталтын	V;SG;3;RMT;PASS
нӱж	нужышто	N;IN+ESS;SG
нӧреп	нӧрепын	N;GEN;SG
шӱяш	шуйыкташ	V;NFIN;CAUS;ACT
муча	мучаштет	N;IN+ESS;SG;PSS2S
юрист	юрист-влак	N;HUM;NOM;PL;LGSPEC1
чурий	чурийыштет	N;IN+ESS;SG;PSS2S
муро	мурыжат	N;NOM;SG;LGSPEC_AMP;PSS3S
американец	американецын	N;HUM;GEN;SG;LGSPEC1
саремаш	саремын	V;SG;3;RMT;ACT
археолог	археолог-шамычат	N;HUM;NOM;PL;LGSPEC_AMP;LGSPEC1
чон	чоныштак	N;NOM;SG;LGSPEC_EMPH;PSS3P
талант	талантан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
прицеп	прицепыште	N;IN+ESS;SG;LGSPEC1
рашемдаш	рашемдет	V;SG;2;ACT
команде	команде-влакымат	N;ACC;PL;LGSPEC_AMP;LGSPEC1
шинчыр	шинчыржым	N;ACC;SG;PSS3S
мастарлык	мастарлыкымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
кӱсен	кӱсенет	N;NOM;SG;PSS2S
йол	йолемым	N;ACC;SG;PSS1S
мӱй	мӱйымат	N;ACC;SG;LGSPEC_AMP
эрнаш	эрнынем	V;OPT;SG;1;ACT
аҥыртараш	аҥыртара	V;SG;3;ACT
союз	союзыш	N;IN+ALL;SG;LGSPEC1
кокла	коклам	N;ACC;SG
ешараш	ешаренат	V;SG;LGSPEC_AMP;3;RMT;ACT
йӱк	йӱкан-влак	N;NOM;PL;LGSPEC_ATTR
ушаш	ушеныт	V;PL;3;RMT;ACT
арвер	арверыштыже	N;IN+ESS;SG;PSS3S
села	селат	N;NOM;SG;PSS2S;LGSPEC1
чоҥаш	чоҥыза	V;IMP;PL;2;ACT
специализаций	специализацийже	N;NOM;SG;PSS3S;LGSPEC1
сакаш	сакенат	V;SG;2;RMT;ACT
шӱмаҥдаш	шӱмаҥдат	V;LGSPEC_AMP;NEG;ACT
ответственность	ответственностьым	N;ACC;SG;LGSPEC1
йодышташ	йодыштынат	V;SG;2;RMT;ACT
йӧрлаш	йӧрлаш	V;NFIN;ACT
телевизор	телевизорыштым	N;ACC;SG;PSS3P;LGSPEC1
ӱдаш	ӱдалтын	V;SG;3;RMT;PASS
йӧрташ	йорт	V;NEG;ACT
пура	пурашышт	N;IN+ALL;SG;PSS3P
арка	аркалаште	N;IN+ESS;PL
волость	волость	N;NOM;SG;LGSPEC1
кугыеҥ	кугыеҥымат	N;HUM;ACC;SG;LGSPEC_AMP
ветлабораторий	ветлабораторийыш	N;IN+ALL;SG;LGSPEC1
ӱштӧ	ӱштыжын	N;GEN;SG;PSS3S
мутер	мутерлам	N;SIM;SG;PSS1S
чудь	чудьын	N;HUM;GEN;SG;LGSPEC1
аваш	авалтын	V;SG;3;RMT;PASS
вӱд	вӱдлам	N;ACC;PL
сакаш	сакен	V;SG;3;RMT;ACT
уржа-сорла	уржа-сорла	N;NOM;SG
йылме	йылмылан	N;DAT;SG
йолташ	йолташ-влакше	N;HUM;NOM;PL;PSS3S
лавка	лавкыште	N;IN+ESS;SG;LGSPEC1
шога	шога	N;NOM;SG
умло	умлем	ADJ;NOM;SG;PSS1S
лекций	лекцийыштым	N;ACC;SG;PSS3P;LGSPEC1
кар	каршат	N;NOM;SG;LGSPEC_AMP;PSS3S
аҥгаш	аҥга	V;SG;3;ACT
лава	лаваш	N;IN+ALL;SG;LGSPEC1
серыш	серышышт-влакым	N;ACC;PL;PSS3P
университет	университетла	N;SIM;SG;LGSPEC1
сочетаний	сочетанийжым	N;ACC;SG;PSS3S;LGSPEC1
воштылалаш	воштылалынат	V;SG;2;RMT;ACT
кылдаш	кылдат	V;PL;3;ACT
пор	порлат	N;SIM;SG;PSS2S
рама	рамым	N;ACC;SG;LGSPEC1
мучашлаш	мучашленна	V;PL;1;RMT;ACT
медперсонал	медперсоналын	N;GEN;SG;LGSPEC1
савар	саваран	N;NOM;SG;LGSPEC_ATTR
лектедаш	лектедат	V;LGSPEC_AMP;NEG;ACT
кужу	кужут	ADJ;NOM;SG;PSS2S
ачалаш	ачале	V;IMP;SG;2;ACT
тӧпкаш	топка	V;SG;3;ACT
кӱ	кунамат	N;ACC;SG;LGSPEC_AMP;PSS1P
пунаш	пуныза	V;IMP;PL;2;ACT
инвестор	инвестор-влаклан	N;HUM;DAT;PL;LGSPEC1
салам	саламдалан	N;DAT;SG;PSS2P
операций	операцийланат	N;DAT;SG;LGSPEC_AMP;LGSPEC1
опера	оперышкыже	N;IN+ALL;SG;PSS3S;LGSPEC1
мондаш	мондалтат	V;IMP;SG;LGSPEC_AMP;2;PASS
ферме	фермылашке	N;IN+ALL;PL;LGSPEC1
шӱре	шӱретым	N;ACC;SG;PSS2S
разведке	разведкыш	N;IN+ALL;SG;LGSPEC1
кучылташ	кучылтна	V;PL;1;PST;ACT
чума	чумалеш	N;ALL;SG;LGSPEC_ATTR;LGSPEC1
киноискусство	киноискусство	N;NOM;SG;LGSPEC1
чучаш	чучынам	V;SG;1;RMT;ACT
талант	талантым	N;ACC;SG;LGSPEC1
ӧндалаш	ондалалтынат	V;SG;LGSPEC_AMP;3;RMT;PASS
мэр	мэр-влак	N;HUM;NOM;PL;LGSPEC1
верешташ	верештат	V;SG;LGSPEC_AMP;3;ACT
шу	шулат	N;NOM;PL;LGSPEC_AMP
титак	титакланат	N;SIM;SG;LGSPEC_AMP;PSS1P
урнаш	урналтын	V;SG;3;RMT;PASS
куандараш	куандаренак	V;SG;LGSPEC_EMPH;3;RMT;ACT
занятий	занятийлаште	N;IN+ESS;PL;LGSPEC1
курык	курыкышкыжо	N;IN+ALL;SG;PSS3S
ойпого	ойпогеш	N;ALL;SG
гуляяш	гуляят	V;PL;3;ACT;LGSPEC1
мужедаш	мужедыкташ	V;NFIN;CAUS;ACT
ий	ийлажым	N;ACC;SIM;SG;PSS3S
эрнаш	эрнен	V;SG;3;RMT;ACT
пионер	пионер	N;HUM;NOM;SG;LGSPEC1
ветеран	ветеран-влакланат	N;HUM;SIM;PL;LGSPEC_AMP;PSS1P;LGSPEC1
юрист	юристда	N;HUM;NOM;SG;PSS2P;LGSPEC1
кампет	кампет	N;NOM;SG;LGSPEC1
ожо	ожо-влакым	N;HUM;ACC;PL
поран	поранжынат	N;GEN;SG;LGSPEC_AMP;PSS3S
кушкыжмо	кушкыжмыжым	N;ACC;SG;PSS3S
вате	ватемат	N;HUM;NOM;SG;LGSPEC_AMP;PSS1S
кас	касем	N;NOM;SG;PSS1S
военнослужащий	военнослужащий-влакым	N;HUM;ACC;PL;LGSPEC1
шел	шелна	N;NOM;SG;PSS1P
шараш	шарыш	V;SG;3;PST;ACT
лӱддымылык	лӱддымылыкат	N;NOM;SG;LGSPEC_AMP
кумылаҥдаш	кумылаҥденыт	V;PL;3;RMT;ACT
йӧр	йӧршӧ-влакын	N;GEN;PL;PSS3S
шынаш	шыныза	V;IMP;PL;2;ACT
шагат	шагатла	N;SIM;SG
ойпого	ойпогышкыжо	N;IN+ALL;SG;PSS3S
кошкаш	кошкетат	V;SG;LGSPEC_AMP;2;ACT
пурташ	пурташат	V;NFIN;LGSPEC_AMP;ACT
нӱж	нужнаште	N;IN+ESS;SG;PSS1P
йӱле	йӱле	N;NOM;SG
ӱмылка	умылкалат	N;NOM;PL;LGSPEC_AMP
йоча	йочатын	N;HUM;GEN;SG;PSS2S
чия	чияжым	N;ACC;SG;PSS3S
парняш	парняштына	N;HUM;IN+ESS;SG;PSS1P
клуб	клубысо	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
кожла	кожлажын	N;GEN;SG;PSS3S
олимпиаде	олимпиадышкет	N;IN+ALL;SG;PSS2S;LGSPEC1
кычкыраш	кычкыреныт	V;PL;3;RMT;ACT
ту	тум	N;NOM;SG;PSS1S
кылмаш	кылмыктат	V;LGSPEC_AMP;NEG;CAUS;ACT
ландыш	ландышым	N;ACC;SG;LGSPEC1
авыз	авыз	N;NOM;SG
тӱвыра	тӱвыраштлан	N;DAT;SG;PSS3P
шергылтараш	шергылтарышым	V;SG;1;PST;ACT
кержалташ	кержалтат	V;IMP;SG;LGSPEC_AMP;2;ACT
каткалаш	каткаленыт	V;PL;3;RMT;ACT
родо-шочшо	родо-шочшышт-влакым	N;HUM;ACC;PL;PSS3P;LGSPEC1
ассоциаций	ассоциацийышт	N;NOM;SG;PSS3P;LGSPEC1
шӱша	шушаш	N;ALL;SG
ойласаш	ойласем	V;SG;1;ACT
вашешташ	вашештат	V;SG;LGSPEC_AMP;3;ACT
негызлаш	негызленак	V;SG;LGSPEC_EMPH;3;RMT;ACT
интернет	интернетеш	N;ALL;SG;LGSPEC1
ерунда	ерунда	N;NOM;SG;LGSPEC1
стипендиат	стипендиатше-влаклан	N;HUM;DAT;PL;PSS3S;LGSPEC1
саваш	савак	V;SG;LGSPEC_EMPH;3;ACT
йылме	йылметлан	N;DAT;SG;PSS2S
шӱлалташ	шӱлалтеныт	V;PL;3;RMT;ACT
аршаш	аршашда	N;NOM;SG;PSS2P
мӧдывуй	мӧдывуй	N;NOM;SG
тумо	тумынак	N;GEN;SG;LGSPEC_EMPH
пӱйыраш	пуйыралтын	V;SG;3;RMT;PASS
сурт-пече	сурт-печыштыда	N;IN+ESS;SG;PSS2P
пенсий	пенсийыштын	N;GEN;SG;PSS3P;LGSPEC1
шогаш	шогыштат	V;IMP;PL;LGSPEC_AMP;3;ACT
чер	чердам	N;ACC;SG;PSS2P
райцентр	райцентрым	N;ACC;SG;LGSPEC1
пураш	пураш	V;NFIN;ACT
капот	капотым	N;ACC;SG;LGSPEC1
йодышташ	йодыштынат	V;SG;LGSPEC_AMP;3;RMT;ACT
бригадир	бригадирже	N;HUM;NOM;SG;PSS3S;LGSPEC1
стандарт	стандарт	N;NOM;SG;LGSPEC1
туш	тушлак	N;NOM;PL;LGSPEC_EMPH
кайыклудо	кайыклудо	N;HUM;NOM;SG
пӧрдаш	пӧрдыктат	V;SG;LGSPEC_AMP;3;CAUS;ACT
шой	шоэш	N;ALL;SG
наследий	наследийлан	N;DAT;SG;LGSPEC1
сургалташ	сургалтат	V;IMP;SG;LGSPEC_AMP;2;ACT
фото	фотода	N;NOM;SG;PSS2P;LGSPEC1
экран	экранеш	N;ALL;SG;LGSPEC1
метр	метрым	N;ACC;SG;LGSPEC1
ойласаш	ойласыкта	V;SG;3;CAUS;ACT
судно	суднылаште	N;IN+ESS;PL;LGSPEC1
тарлаш	тарленак	V;SG;LGSPEC_EMPH;3;RMT;ACT
тӧршташ	тӧрштышым	V;SG;1;PST;ACT
тарлаш	тарлат	V;SG;LGSPEC_AMP;3;ACT
мондаш	мондашат	V;NFIN;LGSPEC_AMP;ACT
вашкаш	вашкыктен	V;SG;3;RMT;CAUS;ACT
газет	газетыштак	N;NOM;SG;LGSPEC_EMPH;PSS3P;LGSPEC1
экскурсий	экскурсийлашке	N;IN+ALL;PL;LGSPEC1
кожгаташ	кожгатем	V;SG;1;ACT
фуфайка	фуфайкем	N;NOM;SG;PSS1S;LGSPEC1
телестудий	телестудийыште	N;IN+ESS;SG;LGSPEC1
вӱчӧ	вучыдымын	N;GEN;SG;LGSPEC_ATTR
ту	тум	N;ACC;SG
патент	патентым	N;ACC;SG;LGSPEC1
подготовка	подготовкышто	N;IN+ESS;SG;LGSPEC1
выпускник	выпускникда-влак	N;HUM;NOM;PL;PSS2P;LGSPEC1
администраций	администрацийышт	N;NOM;SG;PSS3P;LGSPEC1
номер	номеремым	N;ACC;SG;PSS1S;LGSPEC1
курчак	курчак	N;NOM;SG
керташ	кертыда	V;PL;2;ACT
парым	парымже	N;NOM;SG;PSS3S
тын	тынысын	N;GEN;SG;LGSPEC_ATTR
кече	кечаныште	N;IN+ESS;SG;LGSPEC_ATTR
шорташ	шортат	V;SG;2;ACT
постановко	постановкысо	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
технике	техникымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
шотлаш	шотлем	V;SG;1;ACT
пайлаш	пайленат	V;SG;2;RMT;ACT
профессионал	профессионалын	N;HUM;GEN;SG;LGSPEC1
первенство	первенствыштыжат	N;IN+ESS;SG;LGSPEC_AMP;PSS3S;LGSPEC1
чытыраш	чытыр	V;NEG;ACT
вашмут	вашмутлам	N;SIM;SG;PSS1S
шондык	шондыкшо	N;NOM;SG;PSS3S
титак	титакан-влаклан	N;DAT;PL;LGSPEC_ATTR
офис	офисым	N;ACC;SG;LGSPEC1
журнал	журналыштым	N;ACC;SG;PSS3P;LGSPEC1
администраций	администраций-влакым	N;ACC;PL;LGSPEC1
кило	килом	N;NOM;SG;PSS1S;LGSPEC1
пӱнышкаш	пунышкен	V;SG;3;RMT;ACT
команда	командым	N;ACC;SG;LGSPEC1
закон	законат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
студий	студийлан	N;DAT;SG;LGSPEC1
петрушка	петрушка	N;NOM;SG;LGSPEC1
фантазий	фантазий	N;NOM;SG;LGSPEC1
отвор	отворнан	N;GEN;SG;PSS1P;LGSPEC1
ошма	ошма	N;NOM;SG
ял	яллам	N;SIM;SG;PSS1S
лупшаш	лупшалтам	V;SG;1;PASS
фотокорреспондент	фотокорреспондентшылан	N;HUM;DAT;SG;PSS3S;LGSPEC1
чудо	чудым	N;ACC;SG;LGSPEC1
сату	сатужын	N;GEN;SG;PSS3S
кӱлаш	кулак	V;LGSPEC_EMPH;NEG;ACT
ача	ачажын	N;HUM;GEN;SG;PSS3S
списке	спискышкышт	N;IN+ALL;SG;PSS3P;LGSPEC1
митинг	митингыште	N;IN+ESS;SG;LGSPEC1
йос	йосланет	N;HUM;DAT;SG;PSS2S
солист	солистышт-влак	N;HUM;NOM;PL;PSS3P;LGSPEC1
сурт-оралте	сурт-оралтыжымат	N;ACC;SG;LGSPEC_AMP;PSS3S
чемпион	чемпионжым	N;HUM;ACC;SG;PSS3S;LGSPEC1
титак	титакшылан	N;DAT;SG;PSS3S
ойласаш	ойласеныт	V;PL;3;RMT;ACT
кумдык	кумдыкышт	N;NOM;SG;PSS3P
ора	орамат	N;NOM;SG;LGSPEC_AMP;PSS1S
объект	объектлаште	N;IN+ESS;PL;LGSPEC1
депрессий	депрессийлан	N;DAT;SG;LGSPEC1
наркотик	наркотикланат	N;DAT;SG;LGSPEC_AMP;LGSPEC1
прицеп	прицеп-влакын	N;GEN;PL;LGSPEC1
ыраш	ырем	V;SG;1;ACT
чоҥаш	чоҥышт	V;PL;3;PST;ACT
лу	луат	N;NOM;SG;LGSPEC_AMP
ярсаш	ярсенат	V;SG;LGSPEC_AMP;3;RMT;ACT
илышташ	илыштыт	V;PL;3;ACT
кумдык	кумдыкышкышт	N;IN+ALL;SG;PSS3P
модельер	модельер-влакын	N;HUM;GEN;PL;LGSPEC1
тыршаш	тыршетат	V;SG;LGSPEC_AMP;2;ACT
шӱвӧ	шувыш	N;IN+ALL;SG
сылне	сылныжат	ADJ;NOM;SG;LGSPEC_AMP;PSS3S
кундем	кундемнанат	N;GEN;SG;LGSPEC_AMP;PSS1P
пиж	пижнам	N;ACC;SG;PSS1P
патент	патентшым	N;ACC;SG;PSS3S;LGSPEC1
газет	газетымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
лӱм	лумлак	N;NOM;PL;LGSPEC_EMPH
лудо	лудыда	ADJ;NOM;SG;PSS2P
июль	июльыш	N;IN+ALL;SG;LGSPEC1
постановка	постановка-влак	N;NOM;PL;LGSPEC1
шай	шайла	N;SIM;SG
чумаш	чуменат	V;PL;LGSPEC_AMP;1;ACT
шӱша	шушашем	N;ALL;SG;PSS1S
чеверласаш	чеверласем	V;SG;1;ACT
шемер	шемер-влаклан	N;HUM;DAT;PL
шӧраш	шӧрышт	V;PL;3;PST;ACT
окса	оксанамат	N;ACC;SG;LGSPEC_AMP;PSS1P
тар	тарла	N;SIM;SG;LGSPEC1
вашлияш	вашлийнеже	V;OPT;SG;3;ACT
кутко	куткыеш	N;HUM;ALL;SG
чыкедылаш	чыкедылаш	V;NFIN;ACT
кышкылташ	кышкылтынат	V;PL;LGSPEC_AMP;1;ACT
кабин	кабинетышке	N;IN+ALL;SG;PSS2S;LGSPEC1
тезис	тезис	N;NOM;SG;LGSPEC1
защитник	защитниклан	N;HUM;DAT;SG;LGSPEC1
шӱре	шуренна	N;HUM;GEN;SG;PSS1P
талешке	талешкышке	N;HUM;IN+ALL;SG
ӧрыктараш	ӧрыктарет	V;SG;2;ACT
губернатор	губернаторын	N;HUM;GEN;SG;LGSPEC1
пеледыш	пеледышна	N;NOM;SG;PSS1P
улдаш	улден	V;SG;3;RMT;ACT
тулланаш	тулланат	V;LGSPEC_AMP;NEG;ACT
сетке	сетке	N;NOM;SG;LGSPEC1
тын	тындам	N;ACC;SG;PSS2P
кӧҥга	коҥгана	ADJ;NOM;SG;PSS1P
участвоватлаш	участвоватленат	V;SG;2;RMT;ACT;LGSPEC1
община	общинылажын	N;GEN;PL;PSS3S;LGSPEC1
председатель	председательже	N;HUM;NOM;SG;PSS3S;LGSPEC1
тӧчаш	тӧченак	V;SG;LGSPEC_EMPH;3;RMT;ACT
услуга	услугыштым	N;ACC;SG;PSS3P;LGSPEC1
соваш	совашат	V;NFIN;LGSPEC_AMP;ACT
илем	илемыштлан	N;DAT;SG;PSS3P
коршташ	корштат	V;LGSPEC_AMP;NEG;ACT
ужаташ	ужатенат	V;SG;2;RMT;ACT
икшыве	икшыванлан	N;HUM;DAT;SG;LGSPEC_ATTR
пашаеҥ	пашаеҥна-влаклан	N;HUM;DAT;PL;PSS1P
джинс	джинсылан	N;DAT;SG;LGSPEC1
лӱҥгаш	лӱҥгыкта	V;SG;3;CAUS;ACT
повестке	повесткын	N;GEN;SG;LGSPEC1
мурж	муржым	N;ACC;SG
чапландараш	чапландареда	V;PL;2;ACT
намияш	намият	V;SG;LGSPEC_AMP;3;ACT
пыташ	пыта	V;SG;3;ACT
кочкыш	кочкышеш	N;ALL;SG
комиссий	комиссийын	N;GEN;SG;LGSPEC1
пиал	пиалышкына	N;IN+ALL;SG;PSS1P
марганцовко	марганцовкымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
тошташ	тоштында	V;PL;2;RMT;ACT
сессий	сессийжылан	N;DAT;SG;PSS3S;LGSPEC1
там	тамлат	N;NOM;PL;LGSPEC_AMP
чес	чесыштым	N;ACC;SG;PSS3P
век	век-влакыште	N;IN+ESS;PL;LGSPEC1
кочкыш	кочкышнам	N;ACC;SG;PSS1P
сӧраш	сӧренна	V;PL;1;RMT;ACT
квартал	кварталжылан	N;DAT;SG;PSS3S;LGSPEC1
школа	школымак	N;ACC;SG;LGSPEC_EMPH;LGSPEC1
кучаш	кученат	V;SG;2;RMT;ACT
коллектив	коллектив-влакымат	N;ACC;PL;LGSPEC_AMP;LGSPEC1
пале	палымемат	N;ACC;SG;LGSPEC_AMP;PSS1S
зданий	зданиеш	N;ALL;SG;LGSPEC1
ола	олаштына	N;IN+ESS;SG;PSS1P
намыс	намысетат	N;NOM;SG;LGSPEC_AMP;PSS2S
ака	акат-влак	N;HUM;NOM;PL;PSS2S
сура	сурам	N;NOM;SG;PSS1S
сознаний	сознанийым	N;ACC;SG;LGSPEC1
шуаш	шунат	V;PL;LGSPEC_AMP;1;PST;ACT
ужаргаш	ужаргат	V;LGSPEC_AMP;NEG;ACT
тарлаш	тарлена	V;PL;1;ACT
театр	театрыштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
кӱсен	кӱсенже	N;NOM;SG;PSS3S
кучем	кучем	N;NOM;SG
пӱчкедаш	пӱчкедыза	V;IMP;PL;2;ACT
кыл	кылыш	N;IN+ALL;SG
йолташ	йолташышкыже	N;HUM;IN+ALL;SG;PSS3S
руководитель	руководитель	N;HUM;NOM;SG;LGSPEC1
пуэдаш	пуэдыза	V;IMP;PL;2;ACT
тире	тирем	N;NOM;SG;PSS1S;LGSPEC1
салтак	салтак	N;HUM;NOM;SG;LGSPEC1
йомша	йомшаш	N;ALL;SG
болельщик	болельщик-влакат	N;HUM;NOM;PL;LGSPEC_AMP;LGSPEC1
тӱвыра	тӱвыражлан	N;DAT;SG;PSS3S
ямде	ямдылашат	ADJ;ALL;SIM;SG;LGSPEC_AMP
участвоватлаш	участвоватлышна	V;PL;1;PST;ACT;LGSPEC1
лӱяш	лӱйышт	V;PL;3;PST;ACT
автономий	автономийышкышт	N;IN+ALL;SG;PSS3P;LGSPEC1
книга	книгаге	N;COM;SG;LGSPEC1
еҥ	еҥыште	N;HUM;IN+ESS;SG
ковышта	ковыштанлан	N;DAT+GEN;SG
шочыкташ	шочыктыза	V;IMP;PL;2;ACT
шӱшкылташ	шӱшкылтын	V;SG;3;RMT;ACT
ворандараш	ворандарен	V;SG;3;RMT;ACT
строй	стройышто	N;IN+ESS;SG;LGSPEC1
любовник	любовник	N;HUM;NOM;SG;LGSPEC1
перчатке	перчаткын	N;GEN;SG;LGSPEC1
пидаш	пидыктышт	V;IMP;PL;3;CAUS;ACT
кудывече	кудывечыжым	N;ACC;SG;PSS3S
ончаш	ончыктенда	V;PL;2;RMT;CAUS;ACT
иск	искше	N;NOM;SG;PSS3S;LGSPEC1
чарташ	чартынем	V;OPT;SG;1;ACT
кӱдаш	кудалташак	V;NFIN;LGSPEC_EMPH;PASS
парня	парнятым	N;ACC;SG;PSS2S
шаблон	шаблон-влак	N;NOM;PL;LGSPEC1
ӱштӧ	уштышна	N;IN+ALL;SG;PSS1P
иго	игыжын	N;GEN;SG;PSS3S;LGSPEC1
премьера	премьерымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
чӱдылык	чӱдылыкшым	N;ACC;SG;PSS3S
пуда	пудан	N;GEN;SG
сулык	сулыкшым	N;ACC;SG;PSS3S
кучаш	кучалташ	V;NFIN;PASS
ушкал	ушкалналан	N;HUM;DAT;SG;PSS1P
солист	солистше-шамычлан	N;HUM;DAT;PL;PSS3S;LGSPEC1
одо	одым	N;HUM;ACC;SG
лӱддымылык	лӱддымылыкшылан	N;DAT;SG;PSS3S
лист	листат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
шинча	шинчам	N;ACC;SG
кычкыраш	кычкыренна	V;PL;1;RMT;ACT
аҥыртараш	аҥыртарашат	V;NFIN;LGSPEC_AMP;ACT
шуташ	шутышым	V;SG;1;PST;ACT
сорт	сортлан	N;DAT;SG;LGSPEC1
келшаш	келшенам	V;SG;1;RMT;ACT
чытыраш	чытыралтеш	V;SG;3;PASS
чон	чоныметым	N;ACC;SG;PSS2S
умыр	умырда	ADJ;NOM;SG;PSS2P
кид-йол	кид-йолем	N;NOM;SG;PSS1S
у	утын	ADJ;GEN;SG;PSS2S
кечалташ	кечалтынат	V;SG;2;RMT;ACT
одо	одыжат	N;HUM;NOM;SG;LGSPEC_AMP;PSS3S
колхоз	колхозышкыжо	N;IN+ALL;SG;PSS3S;LGSPEC1
жюри	жюриштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
пӱяш	пуемат	V;SG;LGSPEC_AMP;1;ACT
носки	носки	N;NOM;SG;LGSPEC1
балет	балетна	N;NOM;SG;PSS1P;LGSPEC1
педтехникум	педтехникумлашке	N;IN+ALL;PL;LGSPEC1
бригадир	бригадирлан	N;HUM;DAT;SG;LGSPEC1
разряд	разряд-влакым	N;ACC;PL;LGSPEC1
пыташ	пытыже	V;IMP;SG;3;ACT
май	майже	N;NOM;SG;PSS3S;LGSPEC1
лапта	лапта	N;NOM;SG;LGSPEC1
картычке	картычкына-влак	N;NOM;PL;PSS1P;LGSPEC1
сор	сорем	ADJ;NOM;SG;PSS1S
ӱрӧ	уремлаш	N;ALL;SIM;SG;PSS1S
правило	правилым	N;ACC;SG;LGSPEC1
тылзе	тылзынат	N;GEN;SG;LGSPEC_AMP
темаш	темалтше	V;IMP;SG;3;PASS
сылнештараш	сылнештарышт	V;IMP;PL;3;ACT
показатель	показательжым	N;ACC;SG;PSS3S;LGSPEC1
кылмаш	кылменат	V;PL;LGSPEC_AMP;1;ACT
пеҥаш	пеҥалтын	V;SG;3;RMT;PASS
шояклаш	шояклалт	V;IMP;SG;2;PASS
муро	мурыштем	N;IN+ESS;SG;PSS1S
поремаш	порем	V;IMP;SG;2;ACT
арня	арнят	N;NOM;SG;PSS2S
кокша	кокшаге	N;COM;SG
осал	осалан	N;NOM;SG;LGSPEC_ATTR
темлаш	темленам	V;SG;1;RMT;ACT
кичке	кичкыжат	N;NOM;SG;LGSPEC_AMP;PSS3S
сем	семла	N;SIM;SG
мокша	мокша-влак	N;HUM;NOM;PL
полка	полклем	N;NOM;SG;LGSPEC_ATTR;PSS1S;LGSPEC1
толь	толешак	N;ALL;SG;LGSPEC_EMPH;LGSPEC1
шер	шерлем	N;NOM;SG;LGSPEC_ATTR;PSS1S
турист	туристын	N;HUM;GEN;SG;LGSPEC1
качалке	качалке	N;NOM;SG;LGSPEC1
лавыргаш	лавыргашат	V;NFIN;LGSPEC_AMP;ACT
тулсавыш	тулсавыш	N;NOM;SG
статья	статьяштем	N;IN+ESS;SG;PSS1S;LGSPEC1
тий	тий	N;HUM;NOM;SG
уезд	уездлан	N;DAT;SG;LGSPEC1
лаче	лачышкыже	N;HUM;IN+ALL;SG;PSS3S
шукташ	шуктынеда	V;OPT;PL;2;ACT
пойма	поймыда	N;NOM;SG;PSS2P;LGSPEC1
име	имылашке	N;IN+ALL;PL
стрелке	стрелкым	N;ACC;SG;LGSPEC1
интеллигент	интеллигент-влак	N;HUM;NOM;PL;LGSPEC1
купорос	купорос	N;NOM;SG;LGSPEC1
бензин	бензин	N;NOM;SG;LGSPEC1
контракт	контракт-влак	N;NOM;PL;LGSPEC1
паша	пашадымын	N;HUM;GEN;SG;LGSPEC_ATTR
одеколон	одеколоным	N;ACC;SG;LGSPEC1
ракетный	ракетный	ADJ;NOM;SG;LGSPEC1
тӱс	тусымемым	N;ACC;SG;PSS1S
одноклассница	одноклассница	N;HUM;NOM;SG;LGSPEC1
ургаш	ургат	V;PL;3;ACT
пушташ	пуштыктат	V;SG;LGSPEC_AMP;3;CAUS;ACT
поҥго	поҥгет	N;NOM;SG;PSS2S
куп	куплет	N;NOM;SG;LGSPEC_ATTR;PSS2S
пик	пикетыште	N;IN+ESS;SG;PSS2S;LGSPEC1
шӱкташ	шуктынет	V;OPT;SG;2;ACT
лӱмлӧ	лӱмлымым	ADJ;ACC;SG
чыкалташ	чыкалтат	V;LGSPEC_AMP;NEG;ACT
заграничный	заграничный	ADJ;NOM;SG;LGSPEC1
окна	окналасе	N;PL;LGSPEC_ATTR;LGSPEC1
час	час	N;NOM;SG;LGSPEC1
паром	паром	N;NOM;SG;LGSPEC1
йокрокланаш	йокроклане	V;IMP;SG;2;ACT
участке	участкылам	N;SIM;SG;PSS1S;LGSPEC1
следователь	следователь	N;HUM;NOM;SG;LGSPEC1
омсадӱр	омсадӱр	N;NOM;SG
чоко	чокым	N;ACC;SG
стена	стенашкына	N;IN+ALL;SG;PSS1P;LGSPEC1
материал	материаллан	N;DAT;SG;LGSPEC1
ремонт	ремонт-влакым	N;ACC;PL;LGSPEC1
утараш	утараш	V;NFIN;ACT
каҥашаш	каҥашыштат	V;IMP;PL;LGSPEC_AMP;3;ACT
комбайн	комбайныште	N;IN+ESS;SG;LGSPEC1
ной	нойымым	N;ACC;SG
сӱрет	сӱретаныште	N;IN+ESS;SG;LGSPEC_ATTR
тӱшкагудо	тӱшкагудын	N;GEN;SG
безопасность	безопасностьлан	N;DAT;SG;LGSPEC1
йорлешташ	йорлешт	V;IMP;SG;2;ACT
кылымде	кылымдым	N;ACC;SG
шинчылташ	шинчылтше	V;IMP;SG;3;ACT
сигнал	сигналже-влакым	N;ACC;PL;PSS3S;LGSPEC1
алташ	алтыш	V;SG;3;PST;ACT
вызов	вызовыш	N;IN+ALL;SG;LGSPEC1
столовый	столовый	N;NOM;SG;LGSPEC1
участница	участницылан	N;HUM;DAT;SG;LGSPEC1
оҥылаш	оҥылашемат	N;NOM;SG;LGSPEC_AMP;PSS1S
лодка	лодка	N;NOM;SG;LGSPEC1
ашнаш	ашныктат	V;LGSPEC_AMP;NEG;CAUS;ACT
ром	романлан	N;DAT;SG;LGSPEC_ATTR;LGSPEC1
физкультур	физкультурыш	N;IN+ALL;SG;LGSPEC1
балл	баллышт	N;NOM;SG;PSS3P;LGSPEC1
пич	пич	N;NOM;SG
вездеход	вездеходшым	N;ACC;SG;PSS3S;LGSPEC1
уэмдаш	уэмдет	V;SG;2;ACT
пӱртӱс	пӱртӱсыштак	N;NOM;SG;LGSPEC_EMPH;PSS3P
идалык	идалыкыштыже	N;IN+ESS;SG;PSS3S
ящик	ящикым	N;ACC;SG;LGSPEC1
койыш	койышат	N;NOM;SG;LGSPEC_AMP
куньырий	куньырий	ADJ;NOM;SG
поян	поян-влаклан	ADJ;DAT;PL
экскурсант	экскурсант-влаклан	N;HUM;DAT;PL;LGSPEC1
империализм	империализм	N;NOM;SG;LGSPEC1
йоҥгалтараш	йоҥгалтарат	V;PL;3;ACT
кӓл	кӓлжым	N;ACC;SG;PSS3S
корно	корныжын	N;GEN;SG;PSS3S
гана	ганам	N;ACC;SG
медиа	медиаште	N;IN+ESS;SG;LGSPEC1
специальность	специальностьыш	N;IN+ALL;SG;LGSPEC1
водыж	водыжым	N;ACC;SG
чиновник	чиновникынат	N;HUM;GEN;SG;LGSPEC_AMP;LGSPEC1
лагерь	лагерешак	N;ALL;SG;LGSPEC_EMPH;LGSPEC1
общественный	общественныйым	ADJ;ACC;SG;LGSPEC1
кычкыралаш	кычкырал	V;NEG;ACT
немыч	немыч-влакат	N;HUM;NOM;PL;LGSPEC_AMP;LGSPEC1
пошырнаш	пошырненат	V;PL;LGSPEC_AMP;1;ACT
каҥашаш	каҥашеныт	V;PL;3;RMT;ACT
толашаш	толашыш	V;SG;3;PST;ACT
шымлызе	шымлызыштым	N;HUM;ACC;SG;PSS3P
пашма	пашмажым	N;ACC;SG;PSS3S
приклад	прикладыш	N;IN+ALL;SG;LGSPEC1
свойство	свойствыжо	N;NOM;SG;PSS3S;LGSPEC1
логар	логаржылан	N;DAT;SG;PSS3S
пеледаш	пеледышт	V;IMP;PL;3;ACT
фермер	фермер-влаклан	N;HUM;DAT;PL;LGSPEC1
тошкалтыш	тошкалтышымат	N;ACC;SG;LGSPEC_AMP
межень	межень	N;NOM;SG;LGSPEC1
глагол	глаголын	N;GEN;SG;LGSPEC1
схеме	схемыжым	N;ACC;SG;PSS3S;LGSPEC1
фермер	фермерат	N;HUM;NOM;SG;LGSPEC_AMP;LGSPEC1
турлаш	турлалтын	V;SG;3;RMT;PASS
албаста	албаста	N;NOM;SG
лӱмдылаш	лӱмдылаш	V;NFIN;ACT
кӱчаш	кучыктышт	V;PL;3;PST;CAUS;ACT
ужаш	ужеш	V;SG;3;ACT
дискографий	дискографий	N;NOM;SG;LGSPEC1
кува	кувам	ADJ;NOM;SG;PSS1S
пездараш	пездара	V;SG;3;ACT
вирус	вирусшо	N;NOM;SG;PSS3S;LGSPEC1
кува	куваштым	N;HUM;ACC;SG;PSS3P
пинеге	пинегем	N;HUM;NOM;SG;PSS1S
правительство	правительствышкыже	N;IN+ALL;SG;PSS3S;LGSPEC1
эпизод	эпизодлаште	N;IN+ESS;PL;LGSPEC1
уто	утыжак	ADJ;NOM;SG;LGSPEC_EMPH;PSS3S
ойгырыкташ	ойгырыкташ	V;NFIN;ACT
языкланаш	языклан	V;NEG;ACT
граф	графын	N;HUM;GEN;SG;LGSPEC1
пӧлеклаш	пӧлекледа	V;PL;2;ACT
техника	техникыланат	N;DAT;SG;LGSPEC_AMP;LGSPEC1
кухня	кухнят	N;NOM;SG;LGSPEC_AMP;LGSPEC1
видеооператор	видеооператорлан	N;HUM;DAT;SG;LGSPEC1
шемалгаш	шемалге	V;IMP;SG;2;ACT
сад-пакча	сад-пакчашт	N;NOM;SG;PSS3P;LGSPEC1
чиялташ	чиялтен	V;SG;3;RMT;ACT
шӱведаш	шӱведат	V;LGSPEC_AMP;NEG;ACT
каштан	каштанан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
вурго	вургыжеш	N;ALL;SG;PSS3S
весы	весыжланат	N;DAT;SG;LGSPEC_AMP;PSS3S;LGSPEC1
чӱчӱ	чӱчӱмат	N;HUM;ACC;SG;LGSPEC_AMP
кореец	кореецлан	N;HUM;DAT;SG;LGSPEC1
ваза	ваза	N;NOM;SG;LGSPEC1
лончылаш	лончылат	V;SG;LGSPEC_AMP;3;ACT
начальник	начальникшылан	N;HUM;DAT;SG;PSS3S;LGSPEC1
тӱҥ	тӱҥыштыжӧ	N;IN+ESS;SG;PSS3S
вӱршудо	вӱршудо	N;NOM;SG
паран	паранем	N;HUM;NOM;SG;PSS1S
нумалышташ	нумалышт	V;IMP;SG;2;ACT
чиялташ	чиялталтынам	V;SG;1;RMT;PASS
сӱанвате	сӱанвате-влак	N;HUM;NOM;PL
кӱзаш	кӱзенат	V;SG;2;RMT;ACT
юлаш	юлат	V;LGSPEC_AMP;NEG;ACT
шуч	шучыш	ADJ;IN+ALL;SG
тӱжаҥаш	тӱжаҥда	V;IMP;PL;2;ACT
тодышташ	тодыштыт	V;SG;2;PST;ACT
мыскара	мыскаражым	N;ACC;SG;PSS3S
юл	юлла	N;NOM;PL
эҥерташ	эҥертышым	V;SG;1;PST;ACT
содержательный	содержательный	ADJ;NOM;SG;LGSPEC1
шолышташ	шолыштынат	V;SG;2;RMT;ACT
стрелке	стрелке	N;NOM;SG;LGSPEC1
нерге	нергенна	N;HUM;GEN;SG;PSS1P
вел	велыште	N;IN+ESS;SG
ияш	ияш	ADJ;NOM;SG
рубрика	рубрика-влак	N;NOM;PL;LGSPEC1
флора	флоран	N;GEN;SG;LGSPEC1
ион	ионын	N;GEN;SG;LGSPEC1
чызе	чызым	N;ACC;SG
шолташ	шолтетат	V;SG;LGSPEC_AMP;2;ACT
очки	очким	N;NOM;SG;PSS1S;LGSPEC1
чай	чайымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
фигур	фигуран	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
пойдараш	пойдарышт	V;PL;3;PST;ACT
тореш	торешле	N;NOM;SG;LGSPEC_ATTR
радам	радаметым	N;ACC;SG;PSS2S;LGSPEC1
кечаш	кечеда	V;PL;2;ACT
палдырнаш	палдырнышт	V;IMP;PL;3;ACT
пашаче	пашачыла	ADJ;SIM;SG
отделений	отделенийыштыжат	N;IN+ESS;SG;LGSPEC_AMP;PSS3S;LGSPEC1
тӱткӧ	тӱткышем	ADJ;IN+ALL;SG;PSS1S
мочевина	мочевина	N;NOM;SG;LGSPEC1
ер	ернан	N;GEN;SG;PSS1P
пушташ	пуштат	V;LGSPEC_AMP;NEG;ACT
тава	тава	ADJ;NOM;SG
дизайн	дизайнышт	N;NOM;SG;PSS3P;LGSPEC1
сӱрет	сӱретлымым	N;ACC;SG;LGSPEC_ATTR
агропром	агропромлан	N;DAT;SG;LGSPEC1
шушаш	шушашыш	ADJ;IN+ALL;SG
налаш	налешат	V;SG;LGSPEC_AMP;3;ACT
милиций	милицийым	N;ACC;SG;LGSPEC1
кудри	кудрин	N;GEN;SG;LGSPEC1
ведомственный	ведомственный	ADJ;NOM;SG;LGSPEC1
фугас	фугасым	N;ACC;SG;LGSPEC1
авыраш	авыреныт	V;PL;3;RMT;ACT
рат	ратыметым	N;ACC;SG;PSS2S;LGSPEC1
вожылаш	вожылыт	V;SG;2;PST;ACT
временный	временный	ADJ;NOM;SG;LGSPEC1
мушка	мушкынат	N;NOM;SG;LGSPEC_AMP;PSS1P;LGSPEC1
конвой	конвой	N;HUM;NOM;SG;LGSPEC1
катар	катар	N;NOM;SG
мисс	миссышт	N;HUM;NOM;SG;PSS3P;LGSPEC1
умдыла	умдылам	N;HUM;ACC;SG
орлудо	орлудо-влак	N;HUM;NOM;PL
чолгаш	чолга	V;SG;3;ACT
станок	станокшым	N;ACC;SG;PSS3S;LGSPEC1
периферий	периферий	N;NOM;SG;LGSPEC1
возалташ	возалтынам	V;SG;1;RMT;ACT
лайгата	лайгатат	ADJ;NOM;SG;PSS2S
солдатский	солдатский	ADJ;NOM;SG;LGSPEC1
шоя	шояш	N;ALL;SG
кевыт	кевыт	N;NOM;SG
ю	ютын	N;GEN;SG;PSS2S
скотник	скотникше	N;HUM;NOM;SG;PSS3S;LGSPEC1
физик	физикыш	N;HUM;IN+ALL;SG;LGSPEC1
тывырдык	тывырдыкымат	N;ACC;SG;LGSPEC_AMP
специй	специйым	N;ACC;SG;LGSPEC1
пурла	пурлашак	ADJ;IN+ALL;SG;LGSPEC_EMPH
йырвел	йырвелыште	N;IN+ESS;SG
кусартыш	кусартышыже	N;NOM;SG;PSS3S
кӱчаш	кучалтат	V;LGSPEC_AMP;NEG;PASS
тунемаш	тунемна	V;PL;1;PST;ACT
элитный	элитный	ADJ;NOM;SG;LGSPEC1
цоколь	цоколь	N;NOM;SG;LGSPEC1
аквариум	аквариумым	N;ACC;SG;LGSPEC1
шулыкташ	шулыкташ	V;NFIN;ACT
немыч	немычат	N;HUM;NOM;SG;LGSPEC_AMP;LGSPEC1
весы	весыштым	N;ACC;SG;PSS3P;LGSPEC1
эрт	эртымым	N;ACC;SG
таҥ	таҥышт	N;HUM;NOM;SG;PSS3P
минусовка	минусовка	N;NOM;SG;LGSPEC1
кутыраш	кутыра	V;SG;3;ACT
помидор	помидорат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
вончыктараш	вончыктарат	V;PL;3;ACT
лакаш	лакаш	V;NFIN;ACT
межа	межаште	N;IN+ESS;SG;LGSPEC1
тропик	тропикыш	N;IN+ALL;SG;LGSPEC1
йоҥгаш	йоҥгалташ	V;NFIN;PASS
тургым	тургымыш	N;IN+ALL;SG
рӱпшаш	рӱпшаш	V;NFIN;ACT
чий	чиемын	ADJ;GEN;PSS1S
лакемаш	лакемеш	V;SG;3;ACT
писемаш	писем	V;NEG;ACT
экономике	экономикыште	N;IN+ESS;SG;LGSPEC1
лаке	лакыжым	N;ACC;SG;PSS3S
бригада	бригада-влакат	N;NOM;PL;LGSPEC_AMP;LGSPEC1
киса	киса	N;HUM;NOM;SG
эрташ	эртак	V;SG;LGSPEC_EMPH;3;ACT
продукт	продуктшым	N;ACC;SG;PSS3S;LGSPEC1
танык	танык-влак	N;HUM;NOM;PL
синдром	синдромжо	N;NOM;SG;PSS3S;LGSPEC1
нур	нуржымат	N;ACC;SG;LGSPEC_AMP;PSS3S
вурсо	вурсынет	N;GEN;SG;PSS2S
каласалташ	каласалт	V;NEG;ACT
местный	местный	ADJ;NOM;SG;LGSPEC1
пуаш	пуышна	V;PL;1;PST;ACT
романист	романист	N;HUM;NOM;SG;LGSPEC1
делегаций	делегацийыштым	N;ACC;SG;PSS3P;LGSPEC1
эмгаташ	эмгатышт	V;IMP;PL;3;ACT
сироп	сиропым	N;ACC;SG;LGSPEC1
моктанаш	моктанышым	V;SG;1;PST;ACT
ӧраш	орыкташ	V;NFIN;CAUS;ACT
шолташ	шолтат	V;SG;LGSPEC_AMP;3;ACT
ойырлаш	ойырлыжо	V;IMP;SG;3;ACT
собор	соборлаште	N;IN+ESS;PL;LGSPEC1
империалистический	империалистический	ADJ;NOM;SG;LGSPEC1
дитя	дитя	N;HUM;NOM;SG;LGSPEC1
ом	омын	V;GEN;SG;1;NEG
таушташ	тауштышна	V;PL;1;PST;ACT
шомак	шомак-влакат	N;NOM;PL;LGSPEC_AMP
кап	капда	N;NOM;SG;PSS2P
аналог	аналогым	N;ACC;SG;LGSPEC1
лӱштышаш	лӱштышаш	ADJ;NOM;SG
ава-ача	ава-ача	N;HUM;NOM;SG
блюдо	блюдылан	N;DAT;SG;LGSPEC1
тӱлык	тулыкна	N;NOM;SG;PSS1P
шарж	шарж-влакым	N;ACC;PL;LGSPEC1
ӱнар	ӱнарыштым	N;ACC;SG;PSS3P
медкомиссий	медкомиссий	N;NOM;SG;LGSPEC1
тайнаш	тайна	V;SG;3;ACT
лӱмӧ	лӱман-влаклан	N;DAT;PL;LGSPEC_ATTR
вер-шӧр	вер-шӧрышкем	N;IN+ALL;SG;PSS1S
вера	вераланат	N;SIM;SG;LGSPEC_AMP;PSS1P;LGSPEC1
аклалташ	аклалтынат	V;SG;LGSPEC_AMP;3;RMT;ACT;LGSPEC1
арт-кафе	арт-кафе	N;NOM;SG;LGSPEC1
экскурсовод	экскурсовод	N;HUM;NOM;SG;LGSPEC1
ёлка	елкада	N;NOM;SG;PSS2P;LGSPEC1
шыпланаш	шыпланена	V;PL;1;ACT
шыже	шыжыла	N;NOM;PL
нужнаҥаш	нужнаҥ	V;NEG;ACT;LGSPEC1
сука	суксыш	N;HUM;IN+ALL;SG;LGSPEC_ATTR;LGSPEC1
орда	ордалын	N;GEN;SG;LGSPEC_ATTR;LGSPEC1
чаплаш	чаплышым	V;SG;1;PST;ACT
эмганаш	эмганышт	V;PL;3;PST;ACT
командир	командирышт	N;HUM;NOM;SG;PSS3P;LGSPEC1
талылык	талылыкым	N;ACC;SG
лудмо	лудмыжын	N;GEN;SG;PSS3S
ферма	фермым	N;ACC;SG;LGSPEC1
шупшаш	шупшына	V;PL;1;ACT
шӱмлаш	шӱмлӧ	V;IMP;SG;2;ACT
кычкырлаш	кычкырлет	V;SG;2;ACT
чокмар	чокмар	N;NOM;SG;LGSPEC1
вургем	вургемланат	N;SIM;SG;LGSPEC_AMP;PSS1P
кенгуру	кенгуру	N;HUM;NOM;SG;LGSPEC1
юстиций	юстиций	N;NOM;SG;LGSPEC1
химий	химияным	N;ACC;SG;LGSPEC_ATTR;LGSPEC1
мобильник	мобильникыш	N;IN+ALL;SG;LGSPEC1
лампе	лампыже	N;NOM;SG;PSS3S;LGSPEC1
урвалте	урвалтым	N;ACC;SG
иза-шольо	иза-шольышт	N;HUM;NOM;SG;PSS3P
спираль	спираль	N;NOM;SG;LGSPEC1
иза	изак	N;HUM;NOM;SG;LGSPEC_EMPH
сургалтараш	сургалтара	V;SG;3;ACT
шогылташ	шогылтыда	V;PL;2;ACT
пуштедаш	пуштедыктат	V;LGSPEC_AMP;NEG;CAUS;ACT
ияш	ияш	V;NFIN;ACT
организаций	организацийымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
вес	весла	N;NOM;PL;LGSPEC1
причастий	причастийын	N;GEN;SG;LGSPEC1
луштараш	луштарышт	V;PL;3;PST;ACT
кӱчаш	кучалтынна	V;PL;1;RMT;PASS
партий	партийна	N;NOM;SG;PSS1P;LGSPEC1
кара	карам	N;HUM;ACC;SG
коя	коят	N;NOM;SG;PSS2S
кычалаш	кычалынат	V;SG;LGSPEC_AMP;3;RMT;ACT
курика	курикаштым	N;ACC;SG;PSS3P
тур	туржын	N;GEN;SG;PSS3S
тархан	тархан-влак	N;NOM;PL;LGSPEC1
ырший	ырший-влакым	N;ACC;PL
чӱчкалташ	чӱчкалташ	V;NFIN;ACT
чывытан	чывытаныштым	N;HUM;ACC;SG;PSS3P
водопад	водопадше	N;NOM;SG;PSS3S;LGSPEC1
лектыш	лектышыже	N;NOM;SG;PSS3S
ончалтыш	ончалтыш	N;NOM;SG
кыртмаш	кыртмем	V;SG;1;ACT
толашаш	толашышт	V;IMP;PL;3;ACT
кид	кидшымак	N;ACC;SG;LGSPEC_EMPH;PSS3S
кычалаш	кычалынат	V;SG;2;RMT;ACT
уезд	уездла	N;SIM;SG;LGSPEC1
пӱтыркалаш	пӱтыркалем	V;SG;1;ACT
ранг	ранг	N;NOM;SG;LGSPEC1
мочыла	мочылам	N;ACC;SG;LGSPEC1
радио	радио	N;NOM;SG;LGSPEC1
платье	платье	N;NOM;SG;LGSPEC1
тувыр	тувыр	N;NOM;SG
тувыр	тувырыштет	N;IN+ESS;SG;PSS2S
ал	алак	N;NOM;SG;LGSPEC_EMPH
онкодиспансер	онкодиспансерыште	N;IN+ESS;SG;LGSPEC1
турий	турий-влак	N;HUM;NOM;PL
родыланаш	родылан	V;NEG;ACT;LGSPEC1
планета	планетын	N;GEN;SG;LGSPEC1
кояҥаш	кояҥ	V;NEG;ACT
свет	светше	N;NOM;SG;PSS3S;LGSPEC1
шелаш	шел	V;IMP;SG;2;ACT
савыкташ	савыкталташ	V;NFIN;PASS
привычка	привычкыдам	N;ACC;SG;PSS2P;LGSPEC1
лиялташ	лиялтын	V;SG;3;RMT;ACT
мода	модет	N;NOM;SG;PSS2S;LGSPEC1
текстиль	текстиль	N;NOM;SG;LGSPEC1
карме	кармыжым	N;HUM;ACC;SG;PSS3S
пошкудо	пошкудына-влакым	N;HUM;ACC;PL;PSS1P
иностранец	иностранецлан	N;HUM;DAT;SG;LGSPEC1
наглядный	наглядный	ADJ;NOM;SG;LGSPEC1
шолткыкташ	шолткыктен	V;SG;3;RMT;ACT
компонент	компонентым	N;ACC;SG;LGSPEC1
станок	станок	N;NOM;SG;LGSPEC1
ораш	оралтешат	V;SG;LGSPEC_AMP;3;PASS
лингвистика	лингвистика	N;NOM;SG;LGSPEC1
лужавуй	лужавуйлан	N;HUM;DAT;SG
эмгаташ	эмгатен	V;SG;3;RMT;ACT
юг	югысо	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
руш	рушетым	ADJ;ACC;SG;PSS2S
йолчием	йолчиемыштат	N;NOM;SG;LGSPEC_AMP;PSS3P
скандал	скандал	N;NOM;SG;LGSPEC1
удыр	удырымак	N;HUM;ACC;SG;LGSPEC_EMPH
шувыртылаш	шувыртыл	V;NEG;ACT
нерге	нергеште	N;HUM;IN+ESS;SG
приставке	приставкын	N;GEN;SG;LGSPEC1
облучений	облученийым	N;ACC;SG;LGSPEC1
попой	попойжо	ADJ;NOM;SG;PSS3S
известий	известийже	N;NOM;SG;PSS3S;LGSPEC1
руалташ	руалтеныт	V;PL;3;RMT;ACT
торф	торфлак	N;NOM;PL;LGSPEC_EMPH;LGSPEC1
смете	сметышке	N;IN+ALL;SG;LGSPEC1
аҥысыр	аҥысырат	ADJ;NOM;SG;LGSPEC_AMP
элита	элитыжын	N;GEN;SG;PSS3S;LGSPEC1
волгалтараш	волгалтареныт	V;PL;3;RMT;ACT
тормоз	тормоз	N;NOM;SG;LGSPEC1
спица	спицан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
тур	тур	N;NOM;SG;LGSPEC1
блиндаж	блиндажлам	N;SIM;SG;PSS1S;LGSPEC1
механизатор	механизатор	N;HUM;NOM;SG;LGSPEC1
килограмм	килограммлан	N;DAT;SG;LGSPEC1
прейскурант	прейскурант	N;NOM;SG;LGSPEC1
редакций	редакцийжат	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
умдызо	умдызо	N;HUM;NOM;SG
татар	татаржат	N;HUM;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
нӧрташ	нӧртыш	V;SG;3;PST;ACT
новелла	новеллыже-влак	N;NOM;PL;PSS3S;LGSPEC1
лиде	лиде	N;NOM;SG
цех	цехыштак	N;NOM;SG;LGSPEC_EMPH;PSS3P;LGSPEC1
авыраш	авыралтын	V;SG;3;RMT;PASS
пакыс	пакысым	ADJ;ACC;SG
поктылаш	поктылын	V;SG;3;RMT;ACT
пуредылаш	пуредылаш	V;NFIN;ACT
уксус	уксусым	N;ACC;SG;LGSPEC1
курмызак	курмызакым	N;HUM;ACC;SG
тазыла	тазылашт	ADJ;NOM;SG;PSS3P
шырпештараш	шырпештаре	V;IMP;SG;2;ACT
яр	ярла	N;SIM;SG
поиск	поиск	N;NOM;SG;LGSPEC1
музыкальный	музыкальныйым	ADJ;ACC;SG;LGSPEC1
пӱгырнаш	пӱгырна	V;SG;3;ACT
шӱй	шушеш	N;ALL;SG;PSS3S
пагыт	пагытыштак	N;NOM;SG;LGSPEC_EMPH;PSS3P
упражнений	упражнений-влакымат	N;ACC;PL;LGSPEC_AMP;LGSPEC1
металлургий	металлургийым	N;ACC;SG;LGSPEC1
панель	панельыште	N;IN+ESS;SG;LGSPEC1
матрас	матрас	N;NOM;SG;LGSPEC1
адрес	адресышкет	N;IN+ALL;SG;PSS2S;LGSPEC1
пукшаш	пукшенат	V;SG;2;RMT;ACT
кайыраш	кайырат	V;LGSPEC_AMP;NEG;ACT
чарак	чаракше	N;NOM;SG;PSS3S
шеҥаш	шеҥат	V;IMP;SG;LGSPEC_AMP;2;ACT
абитуриент	абитуриент	N;HUM;NOM;SG;LGSPEC1
соловецкий	соловецкийым	ADJ;ACC;SG;LGSPEC1
шындылаш	шындылда	V;PL;2;PST;ACT
стихи	стихин	N;GEN;SG;LGSPEC1
лига	лигышкышт	N;IN+ALL;SG;PSS3P;LGSPEC1
чошаш	чошена	V;PL;1;ACT
шоваш	шоваш	N;NOM;SG
шаланаш	шаланышт	V;PL;3;PST;ACT
кумыр	кумырым	N;ACC;SG
судья	судьям	N;HUM;ACC;SG;LGSPEC1
эффективность	эффективностьышт	N;NOM;SG;PSS3P;LGSPEC1
авалташ	авалтат	V;SG;LGSPEC_AMP;3;ACT
умылаш	умылашат	V;NFIN;LGSPEC_AMP;ACT
организаций	организацийыштын	N;GEN;SG;PSS3P;LGSPEC1
чечен	чеченет	N;HUM;NOM;SG;PSS2S;LGSPEC1
лектыш	лектышем	N;NOM;SG;PSS1S
чайгорка	чайгорка	N;NOM;SG;LGSPEC1
шофёр	шофер-влакат	N;HUM;NOM;PL;LGSPEC_AMP;LGSPEC1
писемаш	писемда	V;IMP;PL;2;ACT
нелемдаш	нелемден	V;SG;3;RMT;ACT
разработка	разработкыж	N;NOM;SG;PSS3S;LGSPEC1
варнаш	варнышт	V;IMP;PL;3;ACT
филармоний	филармонийлан	N;DAT;SG;LGSPEC1
глава	главаштак	N;NOM;SG;LGSPEC_EMPH;PSS3P;LGSPEC1
район	районнан	N;GEN;SG;PSS1P;LGSPEC1
зимагор	зимагор	N;HUM;NOM;SG;LGSPEC1
нергелаш	нергелен	V;SG;3;RMT;ACT
пижаш	пижыктышт	V;IMP;PL;3;CAUS;ACT
легенда	легендыжлан	N;DAT;SG;PSS3S;LGSPEC1
мӱшкыраҥаш	мӱшкыраҥ	V;IMP;SG;2;ACT
стадион	стадионысо	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
вургыжаш	вургыжам	V;SG;1;ACT
катканланаш	катканлан	V;NEG;ACT
тат	татланат	N;DAT;SG;LGSPEC_AMP
репост	репостет	N;NOM;SG;PSS2S;LGSPEC1
эскераш	эскереда	V;PL;2;ACT
таҥ	таҥна-влак	N;HUM;NOM;PL;PSS1P
саскаҥаш	саскаҥда	V;IMP;PL;2;ACT
юлаш	юлен	V;SG;3;RMT;ACT
шурнывече	шурнывече	N;NOM;SG
радам	радамыштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
омо	омыжат	N;NOM;SG;LGSPEC_AMP;PSS3S
тӱкӧ	тукышыш	ADJ;IN+ALL;SG
виктараш	виктарат	V;LGSPEC_AMP;NEG;ACT
пызле	пызле-влак	N;NOM;PL
фуфайке	фуфайке	N;NOM;SG;LGSPEC1
майлаш	майл	V;NEG;ACT;LGSPEC1
лейтенант	лейтенант	N;HUM;NOM;SG;LGSPEC1
породо	породын	N;GEN;SG;LGSPEC1
мода	модеш	N;ALL;SG;LGSPEC1
фамилий	фамилийым	N;ACC;SG;LGSPEC1
шӱраш	шуралтат	V;IMP;SG;LGSPEC_AMP;2;PASS
фуражка	фуражкан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
сем	семжымат	N;ACC;SG;LGSPEC_AMP;PSS3S
томографий	томографийлан	N;DAT;SG;LGSPEC1
шольо	шольыжланат	N;HUM;DAT;SG;LGSPEC_AMP;PSS3S
ум	умет	N;NOM;SG;PSS2S;LGSPEC1
ракет	ракетыштым	N;ACC;SG;PSS3P;LGSPEC1
чарлак	чарлакыште	N;IN+ESS;SG
йомаш	йомам	V;SG;1;ACT
карме	карман-влакыш	N;HUM;IN+ALL;PL;LGSPEC_ATTR
тур	турымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
электромеханик	электромеханиклан	N;HUM;DAT;SG;LGSPEC1
маршрутка	маршруткышто	N;IN+ESS;SG;LGSPEC1
моктанаш	моктаненыт	V;PL;3;RMT;ACT
артель	артельлаште	N;IN+ESS;PL;LGSPEC1
шӱмлаш	шӱмлаш	V;NFIN;ACT
ям	яметын	N;GEN;SG;PSS2S
теннисный	теннисный	ADJ;NOM;SG;LGSPEC1
миниатюра	миниатюра-влакым	N;ACC;PL;LGSPEC1
мотор	моторем	N;NOM;SG;PSS1S;LGSPEC1
партсъезд	партсъездыш	N;IN+ALL;SG;LGSPEC1
формо	формылажым	N;ACC;SIM;SG;PSS3S;LGSPEC1
богатырь	богатырьла	N;HUM;SIM;SG;LGSPEC1
лияш	лийдат	V;IMP;PL;LGSPEC_AMP;2;ACT
савыкташ	савыктышда	V;PL;2;PST;ACT
пелаш	пелашланат	N;SIM;SG;LGSPEC_AMP;PSS1P
тачысе	тачысыла	ADJ;SIM;SG
йомдараш	йомдарыктен	V;SG;3;RMT;CAUS;ACT
чыра	чырамат	N;NOM;SG;LGSPEC_AMP;PSS1S
сорта	сортана	N;NOM;SG;PSS1P
машина	машинажат	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
эша	эша	N;HUM;NOM;SG
пышташ	пыштенытат	V;PL;LGSPEC_AMP;3;RMT;ACT
кубик	кубикла	N;NOM;PL;LGSPEC1
лупс	лупс	N;NOM;SG
тулаш	тулаш	V;NFIN;ACT
чарайол	чарайолынак	ADJ;GEN;SG;LGSPEC_EMPH
фельетон	фельетон	N;NOM;SG;LGSPEC1
черланаш	черлане	V;IMP;SG;2;ACT
шуэ	шуэнам	N;ACC;SG;PSS1P
ушанаш	ушанат	V;LGSPEC_AMP;NEG;ACT
сӧралешташ	сӧралештеш	V;SG;3;ACT
кӧкӧмаш	кокомшо	V;IMP;SG;3;ACT
павильон	павильонлам	N;SIM;SG;PSS1S;LGSPEC1
шыташ	шытат	V;PL;3;ACT
интеллектуальный	интеллектуальный	ADJ;NOM;SG;LGSPEC1
коробка	коробкаште	N;IN+ESS;SG;LGSPEC1
куп	куп	N;NOM;SG
илалше	илалшыже	ADJ;NOM;SG;PSS3S
касте	касте	N;NOM;SG;LGSPEC1
атыландараш	атыландарен	V;SG;3;RMT;ACT
урядник	урядникым	N;HUM;ACC;SG;LGSPEC1
лодымандаш	лодыманде	V;IMP;SG;2;ACT
проза	прозыжо	N;NOM;SG;PSS3S;LGSPEC1
ӱшкыж	ӱшкыж-влакын	N;HUM;GEN;PL
национально-культурный	национально-культурный	ADJ;NOM;SG;LGSPEC1
взнос	взнослан	N;DAT;SG;LGSPEC1
артем	артем	N;NOM;SG
ваче	вачын	N;GEN;SG
пакча	пакчамат	N;NOM;SG;LGSPEC_AMP;PSS1S
чыра	чырат	N;NOM;SG;LGSPEC_AMP
таваш	тавалтат	V;IMP;SG;LGSPEC_AMP;2;PASS
ава	авадам	N;HUM;ACC;SG;PSS2P
явыгаш	явыгышт	V;PL;3;PST;ACT
кандидат	кандидатын	N;HUM;GEN;SG;LGSPEC1
ашнаш	ашнат	V;SG;LGSPEC_AMP;3;ACT
тройчын	тройчын	N;NOM;SG;LGSPEC1
кумаш	кумем	V;SG;1;ACT
шакшылык	шакшылыкышт	N;NOM;SG;PSS3P
амбулаторий	амбулаторий-влакым	N;ACC;PL;LGSPEC1
оролаш	орол	V;NEG;ACT
йылгыжаш	йылгыжаш	V;NFIN;ACT
проблеме	проблеман	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
кугылудо	кугылудым	N;HUM;ACC;SG
ялче	ялче-влакат	N;HUM;NOM;PL;LGSPEC_AMP
фотограф	фотографым	N;HUM;ACC;SG;LGSPEC1
са	саште	N;IN+ESS;SG
чашка	чашкалан	N;DAT;SG;LGSPEC1
изи	изижланат	ADJ;DAT;SG;LGSPEC_AMP;PSS3S
фармакологий	фармакологий	N;NOM;SG;LGSPEC1
руда	рудаш	N;ALL;SG;LGSPEC1
мургайык	мургайык	N;HUM;NOM;SG
очко	очколан	N;DAT;SG;LGSPEC1
локтызо	локтызын	N;HUM;GEN;SG
пачер	пачерна	N;NOM;SG;PSS1P;LGSPEC1
шырчык	шырчыкат	N;NOM;SG;LGSPEC_AMP
тӱжаҥаш	тӱжаҥыт	V;PL;3;ACT
монча	мончаштак	N;NOM;SG;LGSPEC_EMPH;PSS3P
ӱпш	упшыштыжо	N;IN+ESS;SG;PSS3S
гарем	гаремлаште	N;IN+ESS;PL;LGSPEC1
калык	калыкда	N;HUM;NOM;SG;PSS2P
костюм	костюмлан	N;DAT;SG;LGSPEC1
цыган	цыган	N;HUM;NOM;SG;LGSPEC1
арака	аракам	N;NOM;SG;PSS1S
свод	свод	N;NOM;SG;LGSPEC1
кува	кува-влакын	ADJ;GEN;PL
тело	телыланат	N;SIM;SG;LGSPEC_AMP;PSS1P;LGSPEC1
шойышташ	шойыштат	V;IMP;SG;LGSPEC_AMP;2;ACT
шалаташ	шалаташак	V;NFIN;LGSPEC_EMPH;ACT
пычал	пычалат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
булат	булатат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
агаш	аген	V;SG;3;RMT;ACT
мунчалташ	мунчалтынешт	V;OPT;PL;3;ACT
йымыктараш	йымыктара	V;SG;3;ACT
кушкаш	кушкынат	V;SG;2;RMT;ACT
устав	уставыштышт	N;IN+ESS;SG;PSS3P;LGSPEC1
стол	столышто	N;IN+ESS;SG;LGSPEC1
лум	луманым	N;ACC;SG;LGSPEC_ATTR
ава	авамла	N;HUM;ACC;SIM;SG
кутыраш	кутырышт	V;PL;3;PST;ACT
нояш	ноен	V;SG;3;RMT;ACT
школ	школыштышт	N;IN+ESS;SG;PSS3P;LGSPEC1
тӱжвал	тӱжвалнат	N;NOM;SG;LGSPEC_AMP;PSS1P
программа	программа	N;NOM;SG;LGSPEC1
тоштыеҥ	тоштыеҥын	N;HUM;GEN;SG
сийлаш	сийлышт	V;PL;3;PST;ACT
лайга	лайгатат	ADJ;NOM;SG;LGSPEC_AMP;PSS2S
электротул	электротулым	N;ACC;SG
час	часак	N;NOM;SG;LGSPEC_EMPH;LGSPEC1
чарша	чарша	N;NOM;SG
инфляций	инфляцийын	N;GEN;SG;LGSPEC1
сӱлык	сулыкетым	N;HUM;ACC;SG;PSS2S
ыр	ырынет	N;GEN;SG;PSS2S
воспитанник	воспитанник	N;HUM;NOM;SG;LGSPEC1
командировка	командировкыштат	N;NOM;SG;LGSPEC_AMP;PSS3P;LGSPEC1
нуж	нужын	N;HUM;GEN;SG
ия	ияшат	N;IN+ALL;SG;LGSPEC_AMP
пырткаш	пырткаш	V;NFIN;ACT
отраве	отравым	N;ACC;SG;LGSPEC1
очередь	очередьыш	N;IN+ALL;SG;LGSPEC1
сагындараш	сагындарен	V;SG;3;RMT;ACT
вирус	вирусшылан	N;DAT;SG;PSS3S;LGSPEC1
тӱргыжаш	тургыжым	V;SG;1;PST;ACT
шижылалташ	шижылалташ	V;NFIN;ACT
содержаний	содержанийым	N;ACC;SG;LGSPEC1
передача	передачемын	N;GEN;SG;PSS1S;LGSPEC1
серый	серышымат	ADJ;ACC;SG;LGSPEC_AMP;PSS3S;LGSPEC1
электровий	электровий	N;NOM;SG
автотранспорт	автотранспорт	N;NOM;SG;LGSPEC1
сугынь	сугыньла	N;SIM;SG
государство	государствыжын	N;GEN;SG;PSS3S;LGSPEC1
кран	краныште	N;IN+ESS;SG;LGSPEC1
религий	религийыштым	N;ACC;SG;PSS3P;LGSPEC1
волгалтараш	волгалтараш	V;NFIN;ACT
сигара	сигаретым	N;ACC;SG;PSS2S;LGSPEC1
институт	институтат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
шумыктараш	шумыктараш	V;NFIN;ACT
дирижёр	дирижерат	N;HUM;NOM;SG;LGSPEC_AMP;LGSPEC1
бронепоезд	бронепоезд	N;NOM;SG;LGSPEC1
профориентаций	профориентацийлан	N;DAT;SG;LGSPEC1
ваче	вачыжым	N;ACC;SG;PSS3S
фотостудий	фотостудий	N;NOM;SG;LGSPEC1
йӧндымылык	йӧндымылык	N;NOM;SG
колыштараш	колыштарыкташ	V;NFIN;CAUS;ACT
урылташ	урылтыныт	V;PL;3;RMT;ACT
колышташ	колыштынат	V;SG;LGSPEC_AMP;3;RMT;ACT
копнаш	копнат	V;SG;LGSPEC_AMP;3;ACT
чеке	чекыштым	N;ACC;SG;PSS3P
сӱрт	суртемым	N;ACC;SG;PSS1S
капланаш	каплан	V;NEG;ACT
шушко	шушкылаш	N;ALL;SIM;SG
пызаш	пызак	V;LGSPEC_EMPH;NEG;ACT
ургызо	ургызышт	N;HUM;NOM;SG;PSS3P
преступник	преступник-влак	N;HUM;NOM;PL;LGSPEC1
пӧчкаш	почкышда	V;PL;2;PST;ACT
ӱшшудо	ушшудын	N;GEN;SG
кап	капыштат	N;NOM;SG;LGSPEC_AMP;PSS3P
изача	изачаж	N;HUM;NOM;SG;PSS3S
мурызо	мурызан	N;HUM;NOM;SG;LGSPEC_ATTR
музыка	музыка	N;NOM;SG;LGSPEC1
старший	старшина	ADJ;NOM;SG;PSS1P;LGSPEC1
государство	государствын	N;GEN;SG;LGSPEC1
вараланаш	варалан	V;IMP;SG;2;ACT
вычыраҥге	вычыраҥге	N;NOM;SG
нер	нерыштым	N;ACC;SG;PSS3P
тул	тулжо-влак	N;NOM;PL;PSS3S
товатлаш	товатле	V;IMP;SG;2;ACT
танцплощадке	танцплощадкыш	N;IN+ALL;SG;LGSPEC1
шарныкташ	шарныктет	V;SG;2;ACT
правительство	правительствынат	N;GEN;SG;LGSPEC_AMP;LGSPEC1
ледокол	ледокол	N;NOM;SG;LGSPEC1
кычалтылаш	кычалтылыт	V;SG;2;PST;ACT
площадь	площадьышкыла	N;HUM;IN+ALL;SIM;SG;LGSPEC1
турок	турок	N;HUM;NOM;SG;LGSPEC1
ревизор	ревизорышто	N;HUM;IN+ESS;SG;LGSPEC1
вашталтыш	вашталтыш-влакат	N;NOM;PL;LGSPEC_AMP
кидшер	кидшерлан	N;DAT;SG
палаш	палат	V;LGSPEC_AMP;NEG;ACT
брак	бракышт	N;NOM;SG;PSS3P;LGSPEC1
профсоюз	профсоюзыштлан	N;DAT;SG;PSS3P;LGSPEC1
тошто	тоштынат	ADJ;NOM;SG;LGSPEC_AMP;PSS1P
тӱс	тӱсшылан	N;DAT;SG;PSS3S
тренажёр	тренажерлаште	N;IN+ESS;PL;LGSPEC1
паша	пашамак	N;HUM;ACC;SG;LGSPEC_EMPH
кӱдыртылаш	кудыртылеш	V;SG;3;ACT
пурла	пурлам	ADJ;NOM;SG;PSS1S
шалатылаш	шалатылше	V;IMP;SG;3;ACT
ер	ерыште	N;IN+ESS;SG
профком	профкомын	N;GEN;SG;LGSPEC1
шпрот	шпрот	N;NOM;SG;LGSPEC1
эшаш	эшат	V;LGSPEC_AMP;NEG;ACT
участник	участникнам	N;HUM;ACC;SG;PSS1P;LGSPEC1
архангел	архангелжым	N;ACC;SG;PSS3S;LGSPEC1
мурызо	мурызына	N;HUM;NOM;SG;PSS1P
пломба	пломбым	N;ACC;SG;LGSPEC1
кыне	кынела	N;NOM;PL
полыш	полышда	N;NOM;SG;PSS2P
мокаҥаш	мокаҥеш	V;SG;3;ACT
кумышка	кумышка	N;NOM;SG
дед	дедшын	N;HUM;GEN;SG;PSS3S;LGSPEC1
эмоций	эмоцийже	N;NOM;SG;PSS3S;LGSPEC1
сурт	суртышкышт	N;HUM;IN+ALL;SG;PSS3P
руда	рудам	N;ACC;SG;LGSPEC1
активность	активностьшым	N;ACC;SG;PSS3S;LGSPEC1
станок	станоклан	N;DAT;SG;LGSPEC1
орлаҥге	орлаҥгыжым	N;ACC;SG;PSS3S
тыглай	тыглаяк	ADJ;NOM;SG;LGSPEC_EMPH
оптыш	оптышым	N;ACC;SG
тувыр	тувырымат	N;ACC;SG;LGSPEC_AMP
умша	умшатым	N;ACC;SG;PSS2S
кучыкташ	кучыктат	V;PL;3;ACT
кондуктор	кондукторлан	N;HUM;DAT;SG;LGSPEC1
удыраш	удырыштат	V;IMP;PL;LGSPEC_AMP;3;ACT
кӱзаш	кӱзышна	V;PL;1;PST;ACT
он	ондалаш	N;HUM;ALL;SIM;SG;PSS2P
антологий	антологийже	N;NOM;SG;PSS3S;LGSPEC1
ямдылаш	ямдыленда	V;PL;2;RMT;ACT
йӧн	йӧнланат	N;SIM;SG;LGSPEC_AMP;PSS1P
пан	панда	N;HUM;NOM;SG;PSS2P;LGSPEC1
церемоний	церемонийже	N;NOM;SG;PSS3S;LGSPEC1
волгыдо-ужар	волгыдо-ужарге	ADJ;COM;SG
ошемдаш	ошемдынешт	V;OPT;PL;3;ACT
ораш	оралтеш	V;SG;3;PASS
битва	битвыште	N;IN+ESS;SG;LGSPEC1
аппаратура	аппаратуран	N;GEN;SG;LGSPEC1
пресс-конференций	пресс-конференцийыште	N;IN+ESS;SG;LGSPEC1
чытырыкташ	чытырыкташ	V;NFIN;ACT
обязанность	обязанностьшылан	N;DAT;SG;PSS3S;LGSPEC1
каждый	каждый	ADJ;NOM;SG;LGSPEC1
налшаш	налшашым	N;ACC;SG
обложко	обложкыжо-влак	N;NOM;PL;PSS3S;LGSPEC1
мучышташ	мучыштыш	V;SG;3;PST;ACT
фамилий	фамилийжым	N;ACC;SG;PSS3S;LGSPEC1
каҥаш	каҥашыштын	N;GEN;SG;PSS3P
шалаш	шалаш	N;NOM;SG;LGSPEC1
кӱзаш	кузеат	V;IMP;SG;LGSPEC_AMP;2;ACT
почиҥга	почиҥга	N;NOM;SG
пара	парымже	N;ACC;SG;PSS3S;LGSPEC1
полигон	полигонлаш	N;ALL;SIM;SG;LGSPEC1
тесьма	тесьма	N;NOM;SG;LGSPEC1
питомник	питомникыш	N;IN+ALL;SG;LGSPEC1
чий	чийышем	N;IN+ALL;SG;PSS1S
тормак	тормак	N;NOM;SG
черепице	черепице	N;NOM;SG;LGSPEC1
лента	лента	N;NOM;SG;LGSPEC1
кафе	кафет	N;NOM;SG;PSS2S;LGSPEC1
пара	парымжат	N;ACC;SG;LGSPEC_AMP;PSS3S;LGSPEC1
плакат	плакатлаш	N;ALL;SIM;SG;LGSPEC1
кыдалаш	кыдалашыш	ADJ;IN+ALL;SG
ургыш	ургыш	N;NOM;SG
албаста	албастам	N;NOM;SG;PSS1S
ленинец	ленинец	N;HUM;NOM;SG;LGSPEC1
кума	кумам	N;HUM;ACC;SG;LGSPEC1
угинде	угинде	N;NOM;SG
лушкыдемаш	лушкыдемда	V;IMP;PL;2;ACT
промысел	промыселыште	N;IN+ESS;SG;LGSPEC1
самосвал	самосвал	N;NOM;SG;LGSPEC1
лавыргаш	лавыргенам	V;SG;1;RMT;ACT
юбилей	юбилейыштым	N;ACC;SG;PSS3P;LGSPEC1
карме	кармыже	N;HUM;NOM;SG;PSS3S
вераҥдаш	вераҥдалтыт	V;PL;3;PASS
иктӧрлык	иктӧрлыкым	N;ACC;SG
кран	краным	N;ACC;SG;LGSPEC1
костюм	костюмна	N;NOM;SG;PSS1P;LGSPEC1
пассивный	пассивный	ADJ;NOM;SG;LGSPEC1
вӱраҥ	вӱраҥлымым	N;ACC;SG;LGSPEC_ATTR
ложаш	ложашлан	N;DAT;SG
мыскара	мыскарамат	N;NOM;SG;LGSPEC_AMP;PSS1S
тунемалташ	тунемалтын	V;SG;3;RMT;ACT
шокшо	шокшына	N;NOM;SG;PSS1P
уштыш	уштыш-влак	N;NOM;PL
лӱкӧ	лукыштыда	N;IN+ESS;SG;PSS2P
уполномоченный	уполномоченныйже	N;HUM;NOM;SG;PSS3S;LGSPEC1
увлечений	увлеченийжылан	N;DAT;SG;PSS3S;LGSPEC1
пуреҥгаяш	пуреҥгайышым	V;SG;1;PST;ACT
геологический	геологический	ADJ;NOM;SG;LGSPEC1
орай	орай	ADJ;NOM;SG
канаш	канат	V;SG;LGSPEC_AMP;3;ACT
пурла	пурлаштыда	ADJ;IN+ESS;SG;PSS2P
аккомпанемент	аккомпанементлан	N;DAT;SG;LGSPEC1
исследователь	исследователь	N;HUM;NOM;SG;LGSPEC1
орай	ораланат	ADJ;DAT;SG;LGSPEC_AMP
пиво	пивылан	N;DAT;SG;LGSPEC1
ряд	ряд	N;NOM;SG;LGSPEC1
он	онлан	N;HUM;DAT;SG
йӱкташ	йӱкталтеш	V;SG;3;PASS
кылткаш	кылтка	V;SG;3;ACT
тувыр-шовыр	тувыр-шовыржат	N;NOM;SG;LGSPEC_AMP;PSS3S
шелаш	шелалтше	V;IMP;SG;3;PASS
кушташ	куштынена	V;OPT;PL;1;ACT
полшаш	полшыктат	V;SG;LGSPEC_AMP;3;CAUS;ACT
моктанаш	моктанышт	V;IMP;PL;3;ACT
йоҥго	йоҥго	ADJ;NOM;SG
ойгырышо	ойгырышын	ADJ;GEN;SG
туле	тулет	N;NOM;SG;PSS2S
аклалташ	аклалтын	V;SG;3;RMT;ACT;LGSPEC1
лӱдыкташ	лӱдыктат	V;PL;3;ACT
корно	корныла	N;SIM;SG
культ	культым	N;ACC;SG;LGSPEC1
уташ	утыжо	V;IMP;SG;3;ACT
кресло	креслыштыже	N;IN+ESS;SG;PSS3S;LGSPEC1
стыд	стыд	N;NOM;SG;LGSPEC1
йӱд-кече	йӱд-кечыже	N;NOM;SG;PSS3S
пандус	пандус	N;NOM;SG;LGSPEC1
микрорайон	микрорайон	N;NOM;SG;LGSPEC1
фирма	фирмыштым	N;ACC;SG;PSS3P;LGSPEC1
куэр	куэрынак	N;GEN;SG;LGSPEC_EMPH
турняйол	турняйол	N;NOM;SG
тыртыкташ	тыртыктен	V;SG;3;RMT;ACT
поэт	поэт-влакланат	N;HUM;DAT;PL;LGSPEC_AMP;LGSPEC1
толаш	толатат	V;SG;LGSPEC_AMP;2;ACT
лончо	лончылашлан	N;DAT;PL;PSS3S
звонитлаш	звонитлаш	V;NFIN;ACT;LGSPEC1
будильник	будильникым	N;ACC;SG;LGSPEC1
концертмейстер	концертмейстер	N;HUM;NOM;SG;LGSPEC1
акцент	акцентан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
сварщик	сварщик-влак	N;HUM;NOM;PL;LGSPEC1
сак	сакем	N;NOM;SG;PSS1S;LGSPEC1
онколог	онколог	N;HUM;NOM;SG;LGSPEC1
грандиозный	грандиозный	ADJ;NOM;SG;LGSPEC1
лупс	лупсат	N;NOM;SG;LGSPEC_AMP
изача	изачан	N;HUM;GEN;SG
пресвятой	пресвятой	ADJ;NOM;SG;LGSPEC1
картинке	картинке-влак	N;NOM;PL;LGSPEC1
пулыш	пулышлам	N;SIM;SG;PSS1S
налаш	налыт	V;SG;2;PST;ACT
корак	коракшат	ADJ;NOM;SG;LGSPEC_AMP;PSS3S
сак	сакыш	ADJ;IN+ALL;SG
суд	суд-влакым	N;ACC;PL;LGSPEC1
ракаш	ракат	V;PL;3;ACT
тава	тавадан	ADJ;GEN;SG;PSS2P
наука	наука	N;NOM;SG;LGSPEC1
семӱзгар	семӱзгарже-влакым	N;ACC;PL;PSS3S
кӱрен	кӱреным	ADJ;ACC;SG
когаргаш	когаргынеже	V;OPT;SG;3;ACT
духовенство	духовенство	N;NOM;SG;LGSPEC1
заслуга	заслуган	N;GEN;SG;LGSPEC1
отметка	отметкылам	N;ACC;PL;LGSPEC1
пуаш	пуэдат	V;PL;LGSPEC_AMP;2;ACT
йомдараш	йомдарем	V;SG;1;ACT
политинформатор	политинформатор	N;HUM;NOM;SG;LGSPEC1
кыне	кынелам	N;ACC;PL
куб	кубышко	N;IN+ALL;SG;LGSPEC1
кафе	кафежым	N;ACC;SG;PSS3S;LGSPEC1
физкультура	физкультурыштыжо	N;IN+ESS;SG;PSS3S;LGSPEC1
йогын	йогынын	N;GEN;SG
сака	сакале	N;HUM;NOM;SG;LGSPEC_ATTR
вклад	вклад	N;NOM;SG;LGSPEC1
парикмахер	парикмахерым	N;HUM;ACC;SG;LGSPEC1
вакаш	ваке	V;IMP;SG;2;ACT
ойго	ойго	N;NOM;SG
кадр	кадр-влак	N;NOM;PL;LGSPEC1
шара	шарат	N;NOM;SG;PSS2S
позитивный	позитивный	ADJ;NOM;SG;LGSPEC1
подборко	подборкыжым	N;ACC;SG;PSS3S;LGSPEC1
йомаш	йомат	V;LGSPEC_AMP;NEG;ACT
йымыжа	йымыжаже	ADJ;NOM;SG;PSS3S
штурм	штурмжо	N;NOM;SG;PSS3S;LGSPEC1
ушаҥдаш	ушаҥда	V;SG;3;ACT
шарнаш	шарнаш	V;NFIN;ACT
каҥашаш	каҥашет	V;SG;2;ACT
ушалташ	ушалтыт	V;PL;3;ACT
куржталаш	куржталамат	V;SG;LGSPEC_AMP;1;ACT
пойдараш	пойдаралт	V;NEG;PASS
заезд	заезд-влак	N;NOM;PL;LGSPEC1
чӱчалтыш	чӱчалтыш	N;NOM;SG
шуйдаралташ	шуйдаралтеш	V;SG;3;ACT
ответ	ответымат	N;ACC;SG;LGSPEC_AMP;LGSPEC1
робот	робот	N;NOM;SG;LGSPEC1
телефон	телефоныштыжо	N;IN+ESS;SG;PSS3S;LGSPEC1
заниматлаш	заниматлалтеш	V;SG;3;PASS;LGSPEC1
кычалтылаш	кычалтылат	V;SG;2;ACT
параллельный	параллельный	ADJ;NOM;SG;LGSPEC1
методист	методист	N;HUM;NOM;SG;LGSPEC1
сувенир	сувенир-влакын	N;GEN;PL;LGSPEC1
чоткар	чоткарым	ADJ;ACC;SG
шӱдыр	шудыремын	N;GEN;SG;PSS1S
выселке	выселке	N;NOM;SG;LGSPEC1
мотор	моторжат	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
окшак	окшакле	N;HUM;NOM;SG;LGSPEC_ATTR
ужаш	ужыкташ	V;NFIN;CAUS;ACT
ӧндалтыш	ӧндалтышышкет	N;IN+ALL;SG;PSS2S
квалификаций	квалификацием	N;NOM;SG;PSS1S;LGSPEC1
акваланг	аквалангым	N;ACC;SG;LGSPEC1
шур	шургет	N;COM;SG;PSS2S
партбилет	партбилет	N;NOM;SG;LGSPEC1
кӱсото	кӱсото-влакым	N;ACC;PL
пачашлаш	пачашлат	V;LGSPEC_AMP;NEG;ACT
йомак	йомакшым	N;ACC;SG;PSS3S
министерство	министерствыштына	N;IN+ESS;SG;PSS1P;LGSPEC1
тополь	топольын	N;GEN;SG;LGSPEC1
грек	грек-влак	N;HUM;NOM;PL;LGSPEC1
международник	международник	N;HUM;NOM;SG;LGSPEC1
озым	озымем	N;NOM;SG;PSS1S;LGSPEC1
диджей	диджейнам	N;HUM;ACC;SG;PSS1P;LGSPEC1
юм	юмынак	N;HUM;GEN;SG;LGSPEC_EMPH
вера	верандан	N;GEN;SG;PSS2P;LGSPEC1
элемент	элементшым	N;ACC;SG;PSS3S;LGSPEC1
сборник	сборникшым	N;ACC;SG;PSS3S;LGSPEC1
кресача	кресача	N;HUM;NOM;SG;LGSPEC1
щука	щука	N;HUM;NOM;SG;LGSPEC1
сескемалташ	сескемалт	V;NEG;ACT
лагерь	лагерьлаш	N;ALL;SIM;SG;LGSPEC1
электролиний	электролинийлам	N;ACC;PL;LGSPEC1
лекле	лекле	N;HUM;NOM;SG
тер	терысыжым	N;ACC;SG;LGSPEC_ATTR;PSS3S
йӱкшемдаш	йӱкшемдаш	V;NFIN;ACT
ава	авашкыда	N;HUM;IN+ALL;SG;PSS2P
комментарий	комментарием	N;NOM;SG;PSS1S;LGSPEC1
кондаш	кондынем	V;OPT;SG;1;ACT
друзья	друзьям	N;HUM;ACC;SG;LGSPEC1
ярым	ярым	N;NOM;SG;LGSPEC1
обелиск	обелиск	N;NOM;SG;LGSPEC1
ойлаш	ойлышт	V;IMP;PL;3;ACT
кылдем	кылдем	N;NOM;SG
фотограф	фотографла	N;HUM;SIM;SG;LGSPEC1
демобилизоватлаш	демобилизоватлалтынам	V;SG;1;RMT;PASS;LGSPEC1
печатлаш	печатлалтеш	V;SG;3;PASS;LGSPEC1
машина	машинажымат	N;ACC;SG;LGSPEC_AMP;PSS3S;LGSPEC1
иза	изанам	N;HUM;ACC;SG;PSS1P
шарныктыш	шарныктышышт	N;NOM;SG;PSS3P
поп	поплан	N;HUM;DAT;SG;LGSPEC1
тывырдык	тывырдыкыште	N;IN+ESS;SG
вӱр	вурешна	N;ALL;SG;PSS1P
кап	капыштышт	N;IN+ESS;SG;PSS3P
музейный	музейный	ADJ;NOM;SG;LGSPEC1
пычкемышалташ	пычкемышалтын	V;SG;3;RMT;ACT
глава	главаште	N;IN+ESS;SG;LGSPEC1
савыраш	савыренак	V;SG;LGSPEC_EMPH;3;RMT;ACT
коричневый	коричневый	ADJ;NOM;SG;LGSPEC1
куку	кукуна	N;HUM;NOM;SG;PSS1P
кува	куваштым	ADJ;ACC;SG;PSS3P
юм	юмымат	N;HUM;ACC;SG;LGSPEC_AMP
электронике	электроникан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
нӱжалташ	нӱжалтешат	V;SG;LGSPEC_AMP;3;ACT
факультет	факультет	N;NOM;SG;LGSPEC1
нылыташ	нылыташ	N;NOM;SG
патырлык	патырлыкым	N;ACC;SG
черемис	черемис-влакет	N;HUM;NOM;PL;PSS2S;LGSPEC1
илалше	илалшыжат	ADJ;NOM;SG;LGSPEC_AMP;PSS3S
янлык	янлыкетым	N;HUM;ACC;SG;PSS2S
йомдараш	йомдара	V;SG;3;ACT
шӱгарла	шӱгарла-влак	N;NOM;PL
шовыч	шовычеш	N;ALL;SG
водыж	водыж-влак	N;NOM;PL
тӱсаш	тӱсыштак	V;PL;LGSPEC_EMPH;3;PST;ACT
титаклаш	титаклалтыт	V;SG;2;PST;PASS
торгавуй	торгавуй	N;NOM;SG
рӱдӧ	рӱдӧ-влакым	N;ACC;PL
чурияш	чурием	V;SG;1;ACT
камера	камерылаште	N;IN+ESS;PL;LGSPEC1
товарвондо	товарвондыжат	N;NOM;SG;LGSPEC_AMP;PSS3S
олтыш	олтышым	N;ACC;SG
тушкалташ	тушкалтеныт	V;PL;3;RMT;ACT
воспитанник	воспитанникшым	N;HUM;ACC;SG;PSS3S;LGSPEC1
шӱведаш	шуведышым	V;SG;1;PST;ACT
олык	олык-влакын	N;GEN;PL
паз	пазлым	N;ACC;SG;LGSPEC_ATTR;LGSPEC1
йомдараш	йомдарыктат	V;PL;3;CAUS;ACT
заложник	заложниклан	N;HUM;DAT;SG;LGSPEC1
португалец	португалец-влак	N;HUM;NOM;PL;LGSPEC1
носилка	носилка	N;NOM;SG;LGSPEC1
версий	версийжат	N;NOM;SG;LGSPEC_AMP;PSS3S;LGSPEC1
шойыл	шойылым	ADJ;ACC;SG
рат	ратан	N;NOM;SG;LGSPEC_ATTR;LGSPEC1
флакон	флаконым	N;ACC;SG;LGSPEC1
чадыра	чадыра	N;NOM;SG
фотопаша	фотопашам	N;NOM;SG;PSS1S
боксёр	боксёрым	N;HUM;ACC;SG;LGSPEC1
зачёт	зачетыштлан	N;DAT;SG;PSS3P;LGSPEC1
кошелёк	кошелек	N;NOM;SG;LGSPEC1
шекландараш	шекландарат	V;PL;3;ACT
опкын	опкын-влакым	N;HUM;ACC;PL
шымлызе	шымлызе-влаклан	N;HUM;DAT;PL
ӱскырт	ӱскыртланаш	ADJ;ALL;SIM;SG;PSS1P
купаш	купе	V;IMP;SG;2;ACT
версий	версийже	N;NOM;SG;PSS3S;LGSPEC1
фасад	фасадшым	N;ACC;SG;PSS3S;LGSPEC1
лектыш	лектышыштат	N;NOM;SG;LGSPEC_AMP;PSS3P
формулировка	формулировкат	N;NOM;SG;LGSPEC_AMP;LGSPEC1
пружина	пружиным	N;ACC;SG;LGSPEC1
ссуз	ссуз	N;NOM;SG;LGSPEC1
ӱпшалташ	ӱпшалтын	V;SG;3;RMT;ACT
тӱжаҥаш	тӱжаҥаш	V;NFIN;ACT
ашнаш	ашненат	V;SG;LGSPEC_AMP;3;RMT;ACT
парламентарий	парламентарий-влак	N;HUM;NOM;PL;LGSPEC1
калнык	калныкшым	N;ACC;SG;PSS3S
мӱкшотар	мӱкшотарышкыже	N;IN+ALL;SG;PSS3S
коммерсант	коммерсант-влакын	N;HUM;GEN;PL;LGSPEC1
кычкаш	кычкышымат	V;SG;LGSPEC_AMP;1;PST;ACT
тале	талынам	N;ACC;SG;PSS1P
кап	каплаш	N;ALL;SIM;SG
олмештыш	олмештышыже	N;NOM;SG;PSS3S
классик	классикын	N;HUM;GEN;SG;LGSPEC1
рушарня	рушарнян	N;GEN;SG
ӱчаш	учашем	N;NOM;SG;PSS1S
важыкнер	важыкнерым	N;HUM;ACC;SG
пӧлемлаш	пӧлемлаш	V;NFIN;ACT
процедурный	процедурныйна	ADJ;NOM;SG;PSS1P;LGSPEC1
сурт	суртыштыжат	N;HUM;IN+ESS;SG;LGSPEC_AMP;PSS3S
письма	письма-шамыч	N;NOM;PL;LGSPEC1
пурыс	пурысат	N;NOM;SG;LGSPEC_AMP
рубрик	рубрикыштына	N;IN+ESS;SG;PSS1P;LGSPEC1
гӱжлаш	гӱжлаш	V;NFIN;ACT
йӧрнаш	йӧрналтын	V;SG;3;RMT;PASS
кушташ	кушталтын	V;SG;3;RMT;PASS
сын	сынжымат	N;ACC;SG;LGSPEC_AMP;PSS3S
пондаш	пондашыже	N;NOM;SG;PSS3S
киносценарий	киносценарийымат	ADJ;ACC;SG;LGSPEC_AMP;LGSPEC1
кува	куважым	N;HUM;ACC;SG;PSS3S
пече	печыжат	N;NOM;SG;LGSPEC_AMP;PSS3S
призывник	призывникна-влакын	N;HUM;GEN;PL;PSS1P;LGSPEC1
юлаш	юленыт	V;PL;3;RMT;ACT
шӱкшӧ	шӱкшемын	ADJ;GEN;SG;PSS1S
гуталин	гуталиным	N;ACC;SG;LGSPEC1
каван	каванлыш	N;IN+ALL;SG;LGSPEC_ATTR
дизайнер	дизайнер-влакым	N;HUM;ACC;PL;LGSPEC1
тестирований	тестирований-влак	N;NOM;PL;LGSPEC1
пуаш	пуыжо	V;IMP;SG;3;ACT
сфере	сфере-влакымат	N;ACC;PL;LGSPEC_AMP;LGSPEC1
руш	рушна	ADJ;NOM;SG;PSS1P
регистрироватлаш	регистрироватлалтса	V;IMP;PL;2;PASS;LGSPEC1
