huolenpidäi	huolenpidäi	N;NOM;SG
kudomine	kudomistu	N;PRT;SG
marinuija	marinuija	V;NFIN
arvovešši	arvoveššilöi	N;PRT;PL
tavoittelii	tavoittelijii	N;PRT;PL
viändö	viännön	ADJ;GEN;SG
sargu	sargua	N;PRT;SG
sillankorvu	sillankorvan	N;GEN;SG
jevrei	jevrei	N;NOM;SG
kadai	kadajan	N;GEN;SG
kezämökki	kezämökkii	N;PRT;SG
taidomiehet	taidomiehet	N;NOM;SG
tulenduveräi	tulenduveriälöi	N;PRT;PL
rajoittamatoi	rajoittamattomua	ADJ;PRT;SG
luondokuva	luondokuvua	N;PRT;SG
kuurnistuo	kuurnistuo	V;NFIN
kazvosrazvu	kazvosrazvan	N;GEN;SG
meččy	meččiä	N;PRT;SG
virgudovariššu	virgudovariššu	N;NOM;SG
avokuado	avokuadoloi	N;PRT;PL
rahvahanvastaine	rahvahanvastazen	ADJ;GEN;SG
muagari	muagarin	N;GEN;SG
kniigu	kniigan	N;GEN;SG
läbiajo	läbiajon	N;GEN;SG
liedžuttua	liedžuttua	V;NFIN
hurai	hurai	ADJ;NOM;SG
futl’uaru	futl’uaru	N;NOM;SG
liipoi	liippoloi	N;PRT;PL
ruado	ruado	N;NOM;SG
sevoittua	sevoitetah	V;IND;PL;3;POS;PRS
radeiččii	radeiččijii	ADJ;PRT;PL
leikkuamine	leikkuamistu	N;PRT;SG
vastuamatoi	vastuamattoman	ADJ;GEN;SG
ebävys	ebävyksen	N;GEN;SG
koiražu	koiražan	ADJ;GEN;SG
laho	laholoi	ADJ;PRT;PL
suo	suo	N;NOM;SG
sellittämätöi	sellittämättömiä	ADJ;PRT;SG
tarkoituksenmugaine	tarkoituksenmugazen	ADJ;GEN;SG
härčistelläkseh	härčistelemmös	V;IND;SG;1;POS;PRS
kulku	kulku	N;NOM;SG
kuvataido	kuvataiduo	N;PRT;SG
vazita	vazičen	V;IND;SG;1;POS;PRS
hinnakas	hinnakas	ADJ;NOM;SG
kyläläine	kyläläzen	ADJ;GEN;SG
ozutusikkun	ozutusikkunua	N;PRT;SG
keksii	keksijii	ADJ;PRT;PL
videokirjutus	videokirjutustu	N;PRT;SG
ur’ku	ur’kan	N;GEN;SG
rannikoleläi	rannikoleläjän	N;GEN;SG
tyttispektakli	tyttispektaklin	N;GEN;SG
aigalaine	aigalazen	N;GEN;SG
nominatiivu	nominatiivu	N;NOM;SG
ižätöi	ižättömiä	ADJ;PRT;SG
santimetri	santimetrii	N;PRT;SG
juoksukrossu	juoksukrossii	N;PRT;PL
räškyttiä	räškytän	V;IND;SG;1;POS;PRS
biznesanpidäi	biznesanpidäi	N;NOM;SG
viivudiagrammu	viivudiagrammua	N;PRT;SG
jälgivaivu	jälgivaivoi	N;PRT;PL
n’upsistua	n’upsistetah	V;IND;PL;3;POS;PRS
ägei	ägiedy	N;PRT;SG
pihku	pihkan	N;GEN;SG
nälgyvuozi	nälgyvuvven	N;GEN;SG
askel	askel	N;NOM;SG
čiksuttua	čiksuttau	V;IND;SG;3;POS;PRS
kuvailii	kuvailijoi	ADJ;PRT;PL
hurvehtuo	hurvehtutah	V;IND;PL;3;POS;PRS
loppu	lopun	N;GEN;SG
yhtymine	yhtymine	N;NOM;SG
hukanniini	hukanniinii	N;PRT;SG
segaruavonruadai	segaruavonruadajan	N;GEN;SG
lämmänsuvaiččii	lämmänsuvaiččijii	ADJ;PRT;PL
filatelii	filateliedu	N;PRT;SG
rist’oi	rist’oidu	N;PRT;SG
tuline	tuline	ADJ;NOM;SG
hyövylline	hyövyllizen	ADJ;GEN;SG
elostella	elostella	V;NFIN
yö	yöh	N;IN+ALL;SG
pastuttua	pastuttua	V;NFIN
silmäillä	silmäilöy	V;IND;SG;3;POS;PRS
ruho	ruhuo	N;PRT;SG
astalatoi	astalattomii	ADJ;PRT;PL
umbisolmi	umbisolmen	N;GEN;SG
vallita	valliččou	V;IND;SG;3;POS;PRS
merkikieli	merkikielen	N;GEN;SG
miäččyhokkejistu	miäččyhokkejistoi	N;PRT;PL
arvovešši	arvovešši	N;NOM;SG
savehine	savehine	ADJ;NOM;SG
britfu	britfu	N;NOM;SG
silminnägii	silminnägijiä	N;PRT;SG
livottua	livottua	V;NFIN
ojaine	ojaine	N;NOM;SG
rovvata	rovvata	V;NFIN
luonnonvoimat	luonnonvoimien	N;GEN;SG
enzikluassalaine	enzikluassalastu	N;PRT;SG
tudista	tudista	V;NFIN
valmistuo	valmistutah	V;IND;PL;3;POS;PRS
kuuzenkäby	kuuzenkävyn	N;GEN;SG
lapsetoi	lapsettoman	ADJ;GEN;SG
vägivaldu	vägivaldu	N;NOM;SG
nominu	nominua	N;PRT;SG
poromuaperä	poromuaperä	N;NOM;SG
ekolougine	ekolougistu	ADJ;PRT;SG
ohjailii	ohjailijoi	N;PRT;PL
ajatus	ajatustu	N;PRT;SG
čakkavo	čakkavuo	N;PRT;SG
tundui	tundujoi	ADJ;PRT;PL
hengitysgimnastiekku	hengitysgimnastiekku	N;NOM;SG
kieletöi	kieletöi	ADJ;NOM;SG
höyrykeitin	höyrykeitin	N;NOM;SG
kintuija	kintuiččou	V;IND;SG;3;POS;PRS
pyörähtelläkseh	pyörähtelehes	V;IND;SG;3;POS;PRS
kandusuoni	kandusuonii	N;PRT;PL
libevyö	libevyö	V;NFIN
vyö	vyölöi	N;PRT;PL
vuoziaigu	vuoziaigugua	N;PRT;SG
pöyhöttiä	pöyhöttiä	V;NFIN
senuator	senuatoran	N;GEN;SG
paikkailla	paikkailen	V;IND;SG;1;POS;PRS
hierellä	hierellä	V;NFIN
rambu	ramboi	ADJ;PRT;PL
merikala	merikalan	N;GEN;SG
heinänkorzi	heinänkortu	N;PRT;SG
kidukazvoine	kidukazvozen	ADJ;GEN;SG
karjalaine	karjalaine	N;NOM;SG
jiäkauzi	jiäkauziuzii	N;PRT;PL
vuassu	vuasan	N;GEN;SG
šurahtuakseh	šurahtahes	V;IND;SG;3;POS;PRS
ruostienkarvaine	ruostienkarvazii	ADJ;PRT;PL
aivokuori	aivokuordu	N;PRT;SG
höblistelläkseh	höblistelläkseh	V;NFIN
tundui	tundujan	ADJ;GEN;SG
houkku	houkkua	N;PRT;SG
rahvahanvallittu	rahvahanvallittu	N;NOM;SG
pystynäine	pystynäzii	ADJ;PRT;PL
deklinacii	deklinacieloi	N;PRT;PL
vikeldiäkseh	vikeldämmös	V;IND;SG;1;POS;PRS
ikkun	ikkunan	N;GEN;SG
meččylagevus	meččylagevus	N;NOM;SG
herneh	hernehii	N;PRT;PL
čomendellakseh	čomendelehes	V;IND;SG;3;POS;PRS
vaski	vaski	N;NOM;SG
liemen	liemendy	N;PRT;SG
vaivaine	vaivastu	ADJ;PRT;SG
puoliško	puoliškon	N;GEN;SG
stola	stolua	N;PRT;SG
tilavusaigu	tilavusaigoi	N;PRT;PL
sumeh	sumehii	N;PRT;PL
n’uhiško	n’uhiškoloi	N;PRT;PL
tiijonsiirdo	tiijonsiirron	N;GEN;SG
selgyrangu	selgyrangu	N;NOM;SG
vigahine	vigahine	N;NOM;SG
nagriskapustu	nagriskapustu	N;NOM;SG
valdukundu	valdukundii	N;PRT;PL
kukkuripiä	kukkuripiälöi	ADJ;PRT;PL
myöndy	myöndii	N;PRT;PL
šupettua	šupetan	V;IND;SG;1;POS;PRS
kilo	kilon	N;GEN;SG
brihastua	brihastan	V;IND;SG;1;POS;PRS
laukkaine	laukkastu	N;PRT;SG
äry	äryy	N;PRT;SG
pyhä	pyhä	ADJ;NOM;SG
superlatiivu	superlatiivua	N;PRT;SG
armahtus	armahtustu	N;PRT;SG
dekoratiivine	dekoratiivizii	ADJ;PRT;PL
kylmättiä	kylmättiä	V;NFIN
kuivata	kuivatah	V;IND;PL;3;POS;PRS
školindu	školindu	N;NOM;SG
skuupita	skuupičen	V;IND;SG;1;POS;PRS
koperatiivu	koperatiivua	N;PRT;SG
jyrähtys	jyrähtyksii	N;PRT;PL
rikosoigevus	rikosoigevuksen	N;GEN;SG
vastekylmätetty	vastekylmätettyy	ADJ;PRT;SG
räččin	räččin	N;NOM;SG
laihahko	laihahkuo	ADJ;PRT;SG
alakazvos	alakazvostu	N;PRT;SG
syväintaudiliäkäri	syväintaudiliäkärii	N;PRT;SG
kuvondutevolližus	kuvondutevolližuon	N;GEN;SG
šahero	šaheroloi	N;PRT;PL
jagai	jagajua	N;PRT;SG
pel’menit	pel’menilöi	N;PRT;SG
riihi	riihi	N;NOM;SG
tyhjäntoimittai	tyhjäntoimittajoi	N;PRT;PL
vastu	vastoi	N;PRT;PL
zakonankuundelii	zakonankuundelijua	ADJ;PRT;SG
vaččuvyö	vaččuvyödy	N;PRT;SG
kiro	kiroloi	N;PRT;PL
erivärine	erivärizii	ADJ;PRT;PL
amierikkalaine	amierikkalastu	N;PRT;SG
nevvotes	nevvotestu	N;PRT;SG
mustelendupäivy	mustelendupäivän	N;GEN;SG
n’uavu	n’uavoi	N;PRT;PL
ruiskukansinine	ruiskukansinizii	ADJ;PRT;PL
tarviččematoi	tarviččemattomua	ADJ;PRT;SG
valehnägy	valehnägylöi	N;PRT;PL
pezemätöi	pezemättömiä	ADJ;PRT;SG
alguaineh	alguaineh	N;NOM;SG
puhtastusvoije	puhtastusvoidien	N;GEN;SG
ponnistuakseh	ponnistuakseh	V;NFIN
konstitucii	konstitucien	N;GEN;SG
varasolii	varasolijan	N;GEN;SG
uskaldai	uskaldajan	ADJ;GEN;SG
kuameru	kuameru	N;NOM;SG
peittiä	peittiä	V;NFIN
pamista	pamizen	N;GEN;SG
čiihota	čiihuon	V;IND;SG;1;POS;PRS
tuhlata	tuhluau	V;IND;SG;3;POS;PRS
kuččumatoi	kuččumattomii	ADJ;PRT;PL
čakkaillakseh	čakkaillakseh	V;NFIN
toimisto	toimistuo	N;PRT;SG
lohkata	lohkuan	V;IND;SG;1;POS;PRS
suolavuo	suolavutah	V;IND;PL;3;POS;PRS
astii	astii	N;NOM;SG
veikoi	veikkoloi	N;PRT;PL
dokko	dokko	ADJ;NOM;SG
uvvistai	uvvistajii	N;PRT;PL
kyllys	kyllys	N;NOM;SG
prokuratuuru	prokuratuuru	N;NOM;SG
lapsettomus	lapsettomuttu	N;PRT;SG
virraseruondu	virraseruondua	N;PRT;SG
piälikkö	piälikön	N;GEN;SG
vienostuo	vienostutah	V;IND;PL;3;POS;PRS
omanenäine	omanenäzen	ADJ;GEN;SG
syvätä	syvätäh	V;IND;PL;3;POS;PRS
diagnozu	diagnozoi	N;PRT;PL
höblistelläkseh	höblisteleh	V;IND;SG;3;POS;PRS
sebäilläkseh	sebäilläkseh	V;NFIN
veroitus	veroitustu	N;PRT;SG
internuattu	internuattoi	N;PRT;PL
rippui	rippui	ADJ;NOM;SG
räšky	räškyn	N;GEN;SG
tavar	tavaran	N;GEN;SG
hörkistelläkseh	hörkistelläkseh	V;NFIN
kikota	kikkuon	V;IND;SG;1;POS;PRS
kontekstu	kontekstua	N;PRT;SG
tykki	tykki	N;NOM;SG
kover	koveroi	ADJ;PRT;PL
kirahtuakseh	kirahtammos	V;IND;SG;1;POS;PRS
akardion	akardionua	N;PRT;SG
syömäri	syömärin	ADJ;GEN;SG
kezämökiseläi	kezämökiseläjii	N;PRT;PL
šuorei	šuorieloi	ADJ;PRT;PL
kuohui	kuohujii	ADJ;PRT;PL
trigonometrii	trigonometrii	N;NOM;SG
vägehtungevumine	vägehtungevumizii	N;PRT;PL
virčiškö	virčiškön	N;GEN;SG
parasluaduine	parasluaduzen	ADJ;GEN;SG
käyttöala	käyttöala	N;NOM;SG
volli	vollin	N;GEN;SG
ammattineroine	ammattinerozii	ADJ;PRT;PL
keričys	keričyksii	N;PRT;PL
šolkahtuakseh	šolkahtetahes	V;IND;PL;3;POS;PRS
lapsensuandukodi	lapsensuandukodiloi	N;PRT;PL
ajo	ajoloi	N;PRT;PL
ragoine	ragozii	N;PRT;PL
ylendiä	ylendetäh	V;IND;PL;3;POS;PRS
maidokiiseli	maidokiiselin	N;GEN;SG
taivoindellakseh	taivoindellakseh	V;NFIN
kieldävys	kieldävyksii	N;PRT;PL
pyvvändy	pyvvändy	N;NOM;SG
hiirenrida	hiirenrijan	N;GEN;SG
lugumiäry	lugumiärii	N;PRT;PL
märehtie	märehtiy	V;IND;SG;3;POS;PRS
bokkalaine	bokkalazen	ADJ;GEN;SG
suurivezine	suurivezine	ADJ;NOM;SG
tatujirouhku	tatujirouhkan	N;GEN;SG
hyvä	hyvän	N;GEN;SG
bat’mu	bat’moi	N;PRT;PL
asfal’tiiruija	asfal’tiiruiččou	V;IND;SG;3;POS;PRS
typehtyö	typehtyy	V;IND;SG;3;POS;PRS
rivi	rivi	N;NOM;SG
kallistuo	kallistuu	V;IND;SG;3;POS;PRS
vihandu	vihandoi	ADJ;PRT;PL
rubevuo	rubevuo	V;NFIN
dezinfeksiilaitos	dezinfeksiilaitoksen	N;GEN;SG
serveru	serveroi	N;PRT;PL
tiijoneččimine	tiijoneččimine	N;NOM;SG
tribunualu	tribunualua	N;PRT;SG
traktoristu	traktoristua	N;PRT;SG
matkuaju	matkuajoi	N;PRT;PL
guazuaineh	guazuainehen	N;GEN;SG
haukkuo	haukkuu	V;IND;SG;3;POS;PRS
iškie	išken	V;IND;SG;1;POS;PRS
huoldoruavonruadai	huoldoruavonruadajan	N;GEN;SG
sekretari	sekretariloi	N;PRT;PL
ribuhine	ribuhine	ADJ;NOM;SG
kundohpanemine	kundohpanemine	N;NOM;SG
valgiettavu	valgiettavii	ADJ;PRT;PL
astundu	astundan	N;GEN;SG
buolakas	buolakastu	ADJ;PRT;SG
oiginaine	oiginazii	ADJ;PRT;PL
ennustus	ennustus	N;NOM;SG
izru	izrua	N;PRT;SG
čirviškö	čirviškön	ADJ;GEN;SG
hörkistelläkseh	hörkistelemmös	V;IND;SG;1;POS;PRS
čibrakko	čibrakkuo	ADJ;PRT;SG
uduine	uduzii	ADJ;PRT;PL
pokoroijakseh	pokoroijakseh	V;NFIN
diädö	diädölöi	N;PRT;PL
juurikko	juurikkuo	N;PRT;SG
interiessu	interiessua	N;PRT;SG
saduloija	saduloiččou	V;IND;SG;3;POS;PRS
valdivomiehistö	valdivomiehistyö	N;PRT;SG
kalmumätäs	kalmumätästy	N;PRT;SG
tappai	tappajoi	N;PRT;PL
pädevy	pädevy	ADJ;NOM;SG
vilpitöi	vilpittömiä	ADJ;PRT;SG
substantiivu	substantiivu	N;NOM;SG
tarboin	tarboindu	N;PRT;SG
proššaijakseh	proššaijakseh	V;NFIN
birku	birku	N;NOM;SG
veneh	venehii	N;PRT;PL
puistuakseh	puistetahes	V;IND;PL;3;POS;PRS
varavospidäi	varavospidäjän	N;GEN;SG
täyttiä	täytetäh	V;IND;PL;3;POS;PRS
piilu	piilun	N;GEN;SG
loppiekseh	lopemmos	V;IND;SG;1;POS;PRS
puupiä	puupiädy	N;PRT;SG
aziibumuagu	aziibumuagan	N;GEN;SG
kogomus	kogomuksen	N;GEN;SG
nilgavuo	nilgavuo	V;NFIN
vuonaine	vuonastu	N;PRT;SG
kualikku	kualikan	N;GEN;SG
ruadosobimus	ruadosobimus	N;NOM;SG
pahanruadai	pahanruadajoi	N;PRT;PL
ilostus	ilostuksen	N;GEN;SG
parroittuo	parroittuu	V;IND;SG;3;POS;PRS
šulkukuidu	šulkukuidu	N;NOM;SG
erosolendu	erosolendua	N;PRT;SG
karatee	karatee	N;NOM;SG
tanaittua	tanaittau	V;IND;SG;3;POS;PRS
vällinäine	vällinästy	ADJ;PRT;SG
kagrusuurim	kagrusuurimoi	N;PRT;PL
ambuo	ambuo	V;NFIN
sukkelo	sukkelo	ADJ;NOM;SG
kiher	kiher	ADJ;NOM;SG
čugunpada	čugunpadapadua	N;PRT;SG
keitetty	keitetyn	ADJ;GEN;SG
kolkuttua	kolkutan	V;IND;SG;1;POS;PRS
stiilussu	stiilussoi	N;PRT;PL
denganvajavus	denganvajavus	N;NOM;SG
liäkärikundu	liäkärikundua	N;PRT;SG
luondo	luondoloi	N;PRT;PL
tiijonjuotto	tiijonjuotto	N;NOM;SG
kulukuudam	kulukuudamua	N;PRT;SG
mela	mela	N;NOM;SG
puaduo	puaduu	V;IND;SG;3;POS;PRS
imettäi	imettäjän	N;GEN;SG
mečästäi	mečästäi	N;NOM;SG
tiedosistiemu	tiedosistiemoi	N;PRT;PL
manasteri	manasterin	N;GEN;SG
diabiettu	diabietan	N;GEN;SG
kodikonehet	kodikonehet	N;NOM;SG
vil’l’anleikkuaju	vil’l’anleikkuajan	N;GEN;SG
abeija	olin  abeinnuh	V;PRF;IND;SG;1;POS;PST
säjeh	säjehty	N;PRT;SG
suokurmoi	suokurmoin	N;GEN;SG
läbipiäzemätöi	läbipiäzemättömiä	ADJ;PRT;SG
käyttöratas	käyttöratastu	N;PRT;SG
ičenviendytavat	ičenviendytaboi	N;PRT;SG
pohjus	pohjuksii	N;PRT;PL
bokkalaine	bokkalazii	ADJ;PRT;PL
eriluondoine	eriluondostu	ADJ;PRT;SG
kivostua	kivostetah	V;IND;PL;3;POS;PRS
puu	puu	N;NOM;SG
puistella	puistella	V;NFIN
mujuttua	mujuttua	V;NFIN
salvata	salbuan	V;IND;SG;1;POS;PRS
pöyhöttiä	pöyhöttäy	V;IND;SG;3;POS;PRS
toizenžiälöičys	toizenžiälöičys	N;NOM;SG
kuunnelmu	kuunnelmu	N;NOM;SG
hoksata	hoksuan	V;IND;SG;1;POS;PRS
seiččievuodehine	seiččievuodehizii	ADJ;PRT;PL
latelampu	latelampu	N;NOM;SG
muzei	muzieloi	N;PRT;PL
kičku	kičku	ADJ;NOM;SG
humal	humalan	N;GEN;SG
ilmuvirdu	ilmuvirdu	N;NOM;SG
praktiekku	praktiekkoi	N;PRT;PL
videomagnitofon	videomagnitofon	N;NOM;SG
ristikanzantiedo	ristikanzantiijon	N;GEN;SG
hienotavar	hienotavaran	N;GEN;SG
virgusovat	virgusobii	N;PRT;SG
hambahanpaikkavus	hambahanpaikkavus	N;NOM;SG
naimizihmenendy	naimizihmenendy	N;NOM;SG
bat’mu	bat’mu	N;NOM;SG
töykäta	töykätäh	V;IND;PL;3;POS;PRS
perehetöi	perehetöi	ADJ;NOM;SG
smuttie	smuttie	V;NFIN
porraspuu	porraspuuloi	N;PRT;PL
luondal	luondaloi	N;PRT;PL
välisuudokomissii	välisuudokomissiedu	N;PRT;SG
vedäi	vedäjii	N;PRT;PL
kuutti	kuuttii	N;PRT;SG
auttai	auttajua	N;PRT;SG
liikkuo	liikkuu	V;IND;SG;3;POS;PRS
viändö	viändyö	ADJ;PRT;SG
hambahikas	hambahikastu	ADJ;PRT;SG
hora	horan	N;GEN;SG
mölistä	mölistäh	V;IND;PL;3;POS;PRS
kenguru	kenguruloi	N;PRT;PL
bahvualiekseh	bahvualimmos	V;IND;SG;1;POS;PRS
pagintaba	pagintabua	N;PRT;SG
kapitalizmu	kapitalizmua	N;PRT;SG
puhtastusainehet	puhtastusainehii	N;PRT;PL
kanuavu	kanuavu	N;NOM;SG
viččuaidu	viččuaidua	N;PRT;SG
šn’avvahtuakseh	šn’avvahtammos	V;IND;SG;1;POS;PRS
umbiaidu	umbiaidua	N;PRT;SG
mäzry	mäzriä	N;PRT;SG
kohmevuo	kohmevun	V;IND;SG;1;POS;PRS
muailmalline	muailmallizen	ADJ;GEN;SG
tyhjänhövvändy	tyhjänhövvändän	N;GEN;SG
kytkyt	kytkyzii	N;PRT;PL
vyödälys	vyödälyksii	N;PRT;PL
tirpua	tirpetäh	V;IND;PL;3;POS;PRS
pitkittiä	pitkittiä	V;NFIN
niininuoru	niininuoran	N;GEN;SG
höydiä	höydiä	V;NFIN
illalline	illalline	ADJ;NOM;SG
sormipagin	sormipaginua	N;PRT;SG
kastelukanuavu	kastelukanuavoi	N;PRT;PL
heilutella	heiluttelen	V;IND;SG;1;POS;PRS
höllätä	höllätäh	V;IND;PL;3;POS;PRS
nagrishuuhtu	nagrishuuhtu	N;NOM;SG
täyzivaldažus	täyzivaldažuttu	N;PRT;SG
kaikenpuoline	kaikenpuoline	ADJ;NOM;SG
täyzinäine	täyzinäine	ADJ;NOM;SG
liäkäri	liäkärilöi	N;PRT;PL
kirgualdua	kirgualdau	V;IND;SG;3;POS;PRS
nimi	nimiie	N;PRT;SG
opastusharjaittelu	opastusharjaitteluloi	N;PRT;PL
nähtä	nähtä	V;NFIN
Čeehii	Čeehiedu	N;PRT;SG
čökehviivu	čökehviivua	N;PRT;SG
rouzankarvaine	rouzankarvaine	ADJ;NOM;SG
pellastai	pellastai	N;NOM;SG
čuašku	čuaškan	N;GEN;SG
hävitys	hävitys	N;NOM;SG
avtovokzualu	avtovokzualu	N;NOM;SG
eländypaikku	eländypaikkua	N;PRT;SG
raukku	raukkoi	N;PRT;PL
benzinbuakku	benzinbuakan	N;GEN;SG
puretellakseh	puretellahes	V;IND;PL;3;POS;PRS
tuomaine	tuomazii	N;PRT;PL
huaristuo	huaristuo	V;NFIN
pastuttua	pastuttau	V;IND;SG;3;POS;PRS
sokeldua	sokeldetah	V;IND;PL;3;POS;PRS
akkuvägi	akkuväin	N;GEN;SG
persounalline	persounallistu	ADJ;PRT;SG
konstrukcii	konstrukcien	N;GEN;SG
kirpiččyzavodu	kirpiččyzavodu	N;NOM;SG
kattilaine	kattilazii	N;PRT;PL
pyhkimyt	pyhkimytty	N;PRT;SG
venehennenä	venehennenän	N;GEN;SG
vastavuo	vastavutah	V;IND;PL;3;POS;PRS
ögy	ögyy	N;PRT;SG
halgo	hallon	N;GEN;SG
rahvahanroinduperä	rahvahanroinduperä	N;NOM;SG
argikieline	argikielizen	ADJ;GEN;SG
tutkimusinstituuttu	tutkimusinstituuttoi	N;PRT;PL
perustai	perustajan	N;GEN;SG
rohtupäivykukkaine	rohtupäivykukkaine	N;NOM;SG
čibru	čibruloi	N;PRT;PL
pajonalgai	pajonalgajii	N;PRT;PL
luu	luuloile	N;AT+ALL;PL
rajanvardoiččii	rajanvardoiččijan	N;GEN;SG
kohmakko	kohmakon	ADJ;GEN;SG
vähäine	vähäine	N;NOM;SG
vikeldiäkseh	vikeldäh	V;IND;SG;3;POS;PRS
tärineh	tärineh	N;NOM;SG
nagronalaine	nagronalazen	ADJ;GEN;SG
sroju	srojuu	N;PRT;SG
pakolline	pakollizii	ADJ;PRT;PL
diabiettu	diabiettu	N;NOM;SG
uskaldai	uskaldajoi	ADJ;PRT;PL
pinduala	pindualoi	N;PRT;PL
kiirehelruattavu	kiirehelruattavan	ADJ;GEN;SG
ymbärysviivu	ymbärysviivoi	N;PRT;PL
vallata	vallata	V;NFIN
počinbuolu	počinbuolua	N;PRT;SG
egläine	egläzii	ADJ;PRT;PL
tirpačču	tirpačun	ADJ;GEN;SG
pettymys	pettymyksen	N;GEN;SG
lendo	lendo	N;NOM;SG
karahtuakseh	karahtuakseh	V;NFIN
tiedosistiemu	tiedosistieman	N;GEN;SG
ryöčkiä	ryöčketäh	V;IND;PL;3;POS;PRS
hengi	hengi	N;NOM;SG
taivutella	taivutellah	V;IND;PL;3;POS;PRS
meččy	mečättäh	N;PRIV;SG
pidäi	pidäjän	N;GEN;SG
keskelekaduomine	keskelekaduomizen	N;GEN;SG
pienetä	pienetäh	V;IND;PL;3;POS;PRS
majendua	majendetah	V;IND;PL;3;POS;PRS
mouduombeluslaitos	mouduombeluslaitoksen	N;GEN;SG
hyväkundoine	hyväkundozii	ADJ;PRT;PL
šiižmu	šiižmu	N;NOM;SG
parembi	parembii	ADJ;PRT;PL
mennyt	mennytty	ADJ;PRT;SG
riädy	riädy	N;NOM;SG
kielitiijolline	kielitiijollizen	ADJ;GEN;SG
kaikenpuoline	kaikenpuolistu	ADJ;PRT;SG
ketterys	ketterys	N;NOM;SG
čäijeh	čäijeh	N;NOM;SG
pudro	pudro	N;NOM;SG
ulgopoliitiekalline	ulgopoliitiekallistu	ADJ;PRT;SG
kažinkuldu	kažinkuldii	N;PRT;PL
liäkärikundu	liäkärikundii	N;PRT;PL
nägö	nägölöi	N;PRT;PL
ulista	ulista	V;NFIN
lomeikko	lomeikon	N;GEN;SG
inženierutoimisto	inženierutoimiston	N;GEN;SG
läbikävelypiha	läbikävelypihoi	N;PRT;PL
kirzi	kirzi	N;NOM;SG
hroumukengät	hroumukengien	N;GEN;PL
piha	pihan	N;GEN;SG
käinando	käinando	N;NOM;SG
sormus	sormus	N;NOM;SG
valella	valellah	V;IND;PL;3;POS;PRS
magistru	magistru	N;NOM;SG
pihkulehti	pihkulehten	N;GEN;SG
vigelö	vigelön	ADJ;GEN;SG
tiedäi	tiedäjiä	N;PRT;SG
vaibuo	vaibuu	V;IND;SG;3;POS;PRS
ystävysmieline	ystävysmielizen	ADJ;GEN;SG
verenimii	verenimii	N;NOM;SG
linnunkapustu	linnunkapustoi	N;PRT;PL
zvonie	zvonin	V;IND;SG;1;POS;PRS
gruššiekku	gruššiekku	N;NOM;SG
leikkuaju	leikkuaju	N;NOM;SG
sienikaššali	sienikaššali	N;NOM;SG
opastunnuh	opastunnuttu	ADJ;PRT;SG
este	estielöi	N;PRT;PL
yhtehsobimatoi	yhtehsobimattomua	ADJ;PRT;SG
venčaijakseh	venčaijakseh	V;NFIN
ylendys	ylendyksii	N;PRT;PL
sud’d’u	sud’d’ua	N;PRT;SG
pihahodu	pihahodu	N;NOM;SG
nimittiäkseh	nimitetähes	V;IND;PL;3;POS;PRS
elostella	elostelou	V;IND;SG;3;POS;PRS
kego	kego	N;NOM;SG
sieniaigu	sieniaigua	N;PRT;SG
vikeldyö	vikeldytäh	V;IND;PL;3;POS;PRS
paikku	paikkoi	N;PRT;PL
kodžat	kodžien	N;GEN;SG
kiinitysnuoru	kiinitysnuoru	N;NOM;SG
tazata	tazata	V;NFIN
korgeipalkaine	korgeipalkazii	ADJ;PRT;PL
pakehtuo	pakehtutah	V;IND;PL;3;POS;PRS
läbinägymätöi	läbinägymättömän	ADJ;GEN;SG
murčivuo	murčivun	V;IND;SG;1;POS;PRS
kaikkehpättävy	kaikkehpättävän	ADJ;GEN;SG
vihjavus	vihjavus	N;NOM;SG
tolkukas	tolkukastu	ADJ;PRT;SG
abai	abajil	N;AT+ESS;PL
tiedosanakniigu	tiedosanakniigua	N;PRT;SG
viärysilmy	viärysilmän	ADJ;GEN;SG
jauhokivi	jauhokivilöi	N;PRT;PL
hangikeli	hangikelilöi	N;PRT;PL
kyrzy	kyrzän	N;GEN;SG
hindulippuine	hindulippuzii	N;PRT;PL
silminnägii	silminnägii	N;NOM;SG
nävetä	nävetäh	V;IND;PL;3;POS;PRS
tezaurus	tezaurustu	N;PRT;SG
rahvahansuvaiččii	rahvahansuvaiččijoi	ADJ;PRT;PL
lyhythändäine	lyhythändäine	ADJ;NOM;SG
perehtyö	perehtyy	V;IND;SG;3;POS;PRS
rohkendua	rohkendan	V;IND;SG;1;POS;PRS
tuulentuisku	tuulentuiskun	N;GEN;SG
kerralline	kerrallizii	ADJ;PRT;PL
kujo	kujo	N;NOM;SG
opastundutovestus	opastundutovestuksii	N;PRT;PL
tiähtientiijustelii	tiähtientiijustelijua	N;PRT;SG
kallehus	kallehuttu	N;PRT;SG
tervu	tervan	N;GEN;SG
tyhjäntoimittai	tyhjäntoimittajan	N;GEN;SG
mygyry	mygyry	ADJ;NOM;SG
bul’ku	bul’kii	N;PRT;PL
sportumuasteri	sportumuasterin	N;GEN;SG
hoikkukuorine	hoikkukuorizii	ADJ;PRT;PL
möčkäta	möčkätäh	V;IND;PL;3;POS;PRS
koisluajittu	koisluajittuu	ADJ;PRT;SG
orožu	orožua	N;PRT;SG
tatuarielaine	tatuarielazii	N;PRT;PL
maidolaukku	maidolaukkoi	N;PRT;PL
sobevuo	sobevuu	V;IND;SG;3;POS;PRS
meččy	mečäs	N;IN+ESS;SG
puolivillaine	puolivillazen	ADJ;GEN;SG
lapsus	lapsuon	N;GEN;SG
vardoijakseh	vardoičemmos	V;IND;SG;1;POS;PRS
ymbäriolijat	ymbäriolijoin	N;GEN;PL
keppikävely	keppikävely	N;NOM;SG
ihastus	ihastustu	N;PRT;SG
luondo	luonnon	N;GEN;SG
revittia	revittia	V;NFIN
del’fin	del’finoi	N;PRT;PL
valgamo	valgamoloi	N;PRT;PL
doupingutestu	doupingutestu	N;NOM;SG
ilonpiendy	ilonpiendii	N;PRT;PL
lyydiläine	lyydiläzen	ADJ;GEN;SG
kirrahtella	kirrahtellah	V;IND;PL;3;POS;PRS
merenpindu	merenpindu	N;NOM;SG
yhtehmenendyigä	yhtehmenendyigä	N;NOM;SG
sovittua	sovittua	V;NFIN
literatuuruarvostelu	literatuuruarvosteluloi	N;PRT;PL
n’apakko	n’apakko	ADJ;NOM;SG
pakehtuo	pakehtuu	V;IND;SG;3;POS;PRS
nakata	nakata	V;NFIN
lämmähkö	lämmähkön	ADJ;GEN;SG
liippi	liippilöi	N;PRT;PL
selgäin	selgäimen	N;GEN;SG
talvilindu	talvilindu	N;NOM;SG
muahine	muahizii	ADJ;PRT;PL
aiguväli	aiguvälilöi	N;PRT;PL
pidävyö	pidävyö	V;NFIN
sammutin	sammutindu	N;PRT;SG
munitusjäiččy	munitusjäičän	N;GEN;SG
vaihtumine	vaihtumizen	N;GEN;SG
tumakko	tumakko	ADJ;NOM;SG
vezikolonku	vezikolonkoi	N;PRT;PL
langenii	langenijii	ADJ;PRT;PL
niemi	niemen	N;GEN;SG
ahavoija	ahavoijah	V;IND;PL;3;POS;PRS
huurmevuo	huurmevuu	V;IND;SG;3;POS;PRS
tovelline	tovelline	ADJ;NOM;SG
valdivonpalkindo	valdivonpalkinduo	N;PRT;SG
meččyjänöi	meččyjänöidy	N;PRT;SG
julgevus	julgevuttu	N;PRT;SG
läyhistely	läyhistelyy	N;PRT;SG
čagari	čagari	N;NOM;SG
puindukoneh	puindukonehii	N;PRT;PL
viinanjuoju	viinanjuojua	N;PRT;SG
soimi	soimen	N;GEN;SG
huabu	huavan	N;GEN;SG
hözistä	hözizöy	V;IND;SG;3;POS;PRS
tyhjänpagizii	tyhjänpagizijan	N;GEN;SG
gemoglobin	gemoglobinua	N;PRT;SG
ravahtus	ravahtuksii	N;PRT;PL
sogei	sogei	N;NOM;SG
poigaine	poigastu	N;PRT;SG
lampočku	lampočkua	N;PRT;SG
luonnontiedäi	luonnontiedäjiä	N;PRT;SG
halgosarai	halgosarai	N;NOM;SG
tervakas	tervakkahii	ADJ;PRT;PL
kodvastuo	kodvastuu	V;IND;SG;3;POS;PRS
kiiristiäkseh	kiiristetähes	V;IND;PL;3;POS;PRS
ennustai	ennustajan	N;GEN;SG
mennä	mennä	V;NFIN
leibylaukku	leibylaukkua	N;PRT;SG
koiransieni	koiransienii	N;PRT;PL
leskevyö	leskevyö	V;NFIN
organizmu	organizman	N;GEN;SG
dokumentualline	dokumentuallizen	ADJ;GEN;SG
särizii	särizijii	ADJ;PRT;PL
tappai	tappajoi	ADJ;PRT;PL
telefon	telefonoi	N;PRT;PL
kurrensiibiaidu	kurrensiibiaijan	N;GEN;SG
kirikönkalenduaru	kirikönkalenduarua	N;PRT;SG
tetratti	tetrattii	N;PRT;SG
opastusmetoudiekku	opastusmetoudiekku	N;NOM;SG
lugujoukko	lugujoukkoloi	N;PRT;PL
asfal’tiiruija	asfal’tiiruičen	V;IND;SG;1;POS;PRS
terä	terän	N;GEN;SG
näbläkkö	näbläkön	ADJ;GEN;SG
uuličču	uuličču	N;NOM;SG
juodu	juodua	N;PRT;SG
kuidu	kuiduloi	N;PRT;PL
rutostuo	rutostuo	V;NFIN
čukeldusveneh	čukeldusveneh	N;NOM;SG
kirkottua	kirkotan	V;IND;SG;1;POS;PRS
vastahmielespiendy	vastahmielespiendy	N;NOM;SG
ristižä	ristižä	N;NOM;SG
kuokkie	kuokin	V;IND;SG;1;POS;PRS
hengi	hengen	N;GEN;SG
töngie	töngitäh	V;IND;PL;3;POS;PRS
särgi	särgii	N;PRT;SG
vieras	vierahan	N;GEN;SG
kerduamatoi	kerduamattomua	ADJ;PRT;SG
kostuo	kostuo	V;NFIN
viärinkäyttö	viärinkäyttö	N;NOM;SG
muann’aba	muann’avan	N;GEN;SG
astal	astalii	N;PRT;PL
lapsi	lapsi	ADJ;NOM;SG
alango	alangoloi	N;PRT;PL
heilutella	heilutellah	V;IND;PL;3;POS;PRS
abeija	abeičemmo	V;IND;PL;1;POS;PRS
tarkuluondoine	tarkuluondozii	ADJ;PRT;PL
pakičuspalaine	pakičuspalaine	N;NOM;SG
pönnistiä	pönnistetäh	V;IND;PL;3;POS;PRS
leveihardiene	leveihardiestu	N;PRT;SG
ägei	ägien	ADJ;GEN;SG
meloudii	meloudien	N;GEN;SG
čäri	čäri	N;NOM;SG
imettäi	imettäi	N;NOM;SG
vihmaksine	vihmaksistu	ADJ;PRT;SG
riissukuaššu	riissukuašan	N;GEN;SG
jumaittua	jumaitetah	V;IND;PL;3;POS;PRS
hobjulohi	hobjulohiloi	N;PRT;PL
läbivedo	läbivevon	N;GEN;SG
oigevustila	oigevustilua	N;PRT;SG
suundu	suundoi	N;PRT;PL
griekkalaine	griekkalastu	ADJ;PRT;SG
smuttie	smutitah	V;IND;PL;3;POS;PRS
rudžahtuakseh	rudžahtuakseh	V;NFIN
lapsettomus	lapsettomuon	N;GEN;SG
nahkupohjaine	nahkupohjazen	ADJ;GEN;SG
rauduvanuin	rauduvanuin	N;NOM;SG
unohtuo	unohtuo	V;NFIN
ozattomus	ozattomus	N;NOM;SG
plakuttua	plakuttua	N;NOM;SG
mielespiettävy	mielespiettävy	N;NOM;SG
urhakko	urhakon	ADJ;GEN;SG
kriäškiä	kriäškän	V;IND;SG;1;POS;PRS
venehennenä	venehennenä	N;NOM;SG
kuvanvestotaido	kuvanvestotaiduo	N;PRT;SG
kartu	kartua	N;PRT;SG
nellikkö	nellikkö	N;NOM;SG
jallasolendu	jallasolendua	N;PRT;SG
ajos	ajoksen	N;GEN;SG
kyrčistiäkseh	kyrčistämmös	V;IND;SG;1;POS;PRS
smuttie	smuttiu	V;IND;SG;3;POS;PRS
sangviiniekku	sangviiniekan	N;GEN;SG
segaruavonruadai	segaruavonruadajii	N;PRT;PL
ilmaine	ilmazen	ADJ;GEN;SG
vardoičuslaiteh	vardoičuslaittehii	N;PRT;PL
tuotando	tuotandon	N;GEN;SG
kielitiedo	kielitieduo	N;PRT;SG
hyväksytty	hyväksytyn	ADJ;GEN;SG
eromerki	eromerkilöi	N;PRT;PL
plöčkähtiäkseh	plöčkähtetähes	V;IND;PL;3;POS;PRS
kalkettua	kalkettau	V;IND;SG;3;POS;PRS
kualua	kualua	V;NFIN
bahvualiekseh	bahvualihes	V;IND;SG;3;POS;PRS
kezäaigu	kezäaigoi	N;PRT;PL
vakustua	vakustan	V;IND;SG;1;POS;PRS
dollar	dollaran	N;GEN;SG
rehoittua	rehoitan	V;IND;SG;1;POS;PRS
vahingo	vahingoloi	N;PRT;PL
kimpu	kimpuloi	N;PRT;PL
vaivatakseh	vaivuahes	V;IND;SG;3;POS;PRS
pločkata	pločkuan	V;IND;SG;1;POS;PRS
fotobumuagu	fotobumuagua	N;PRT;SG
kielastai	kielastajua	N;PRT;SG
tuulenpuoli	tuulenpuoldu	N;PRT;SG
opastusvuozi	opastusvuottu	N;PRT;SG
ogrodu	ogrodu	N;NOM;SG
pilvi	pilvi	N;NOM;SG
jiäškuappu	jiäškuapan	N;GEN;SG
abai	abajanke	N;COM;SG
huondeskaste	huondeskastettu	N;PRT;SG
miero	mieruo	N;PRT;SG
sammal	sammalen	N;GEN;SG
kynäbrys	kynäbrysty	N;PRT;SG
pihaaidaine	pihaaidaine	N;NOM;SG
muanomistai	muanomistajoi	N;PRT;PL
valmistua	valmistau	V;IND;SG;3;POS;PRS
lähendiä	lähendän	V;IND;SG;1;POS;PRS
hoikeh	hoikeh	N;NOM;SG
kastuo	kastun	V;IND;SG;1;POS;PRS
tehnolougu	tehnolougan	N;GEN;SG
takelduo	takeldun	V;IND;SG;1;POS;PRS
elektrohärkin	elektrohärkimii	N;PRT;PL
hörhöttiä	hörhöttiä	V;NFIN
nenäine	nenästy	N;PRT;SG
kabrastai	kabrastai	N;NOM;SG
kuudoine	kuudostu	N;PRT;SG
vähävaraine	vähävarastu	ADJ;PRT;SG
parter	parter	N;NOM;SG
pihaaitu	pihaaittoi	N;PRT;PL
kserokoupii	kserokoupieloi	N;PRT;PL
mua	muan	N;GEN;SG
lyhythiemai	lyhythiemualoi	ADJ;PRT;PL
muutto	muuttuo	N;PRT;SG
sročittua	sročittua	V;NFIN
nenäluu	nenäluudu	N;PRT;SG
yö	yökse	N;TRANS;SG
kähärpiä	kähärpiä	ADJ;NOM;SG
lappalaine	lappalastu	N;PRT;SG
arheolougielline	arheolougiellistu	ADJ;PRT;SG
puoleta	puoletah	V;IND;PL;3;POS;PRS
kiher	kiherän	N;GEN;SG
ehoittua	ehoittua	V;NFIN
haldivoiččii	haldivoiččijii	N;PRT;PL
tozinimi	tozinimie	N;PRT;SG
ylendys	ylendys	N;NOM;SG
valpastuo	valpastun	V;IND;SG;1;POS;PRS
liikundanopastai	liikundanopastai	N;NOM;SG
rauhannevvottelut	rauhannevvotteluloin	N;GEN;PL
miilostin	miilostinan	N;GEN;SG
imetys	imetyksii	N;PRT;PL
kilbailla	kilbailen	V;IND;SG;1;POS;PRS
tozine	tozizii	ADJ;PRT;PL
lukšukorvu	lukšukorvua	ADJ;PRT;SG
puolistus	puolistus	N;NOM;SG
tiijoitussekretari	tiijoitussekretarii	N;PRT;SG
valku	valkan	N;GEN;SG
sammal	sammalii	N;PRT;PL
voimakas	voimakastu	ADJ;PRT;SG
päivy	päiviä	N;PRT;SG
monikieline	monikieline	ADJ;NOM;SG
sumeh	sumeh	N;NOM;SG
ruavas	ruavastu	ADJ;PRT;SG
ispuanielaine	ispuanielaine	ADJ;NOM;SG
kieli	kielii	N;PRT;PL
aigalaine	aigalaine	N;NOM;SG
kieldotavar	kieldotavarua	N;PRT;SG
sanondutaba	sanondutavan	N;GEN;SG
kosmossusoba	kosmossusobua	N;PRT;SG
neroniekkusoittai	neroniekkusoittajii	N;PRT;PL
hyväluondone	hyväluondostu	ADJ;PRT;SG
ilotoi	ilottoman	ADJ;GEN;SG
yrrästiäkseh	yrrästähes	V;IND;SG;3;POS;PRS
peittohommat	peittohommatii	N;PRT;PL
čakata	čakataatah	V;IND;PL;3;POS;PRS
lugumiäry	lugumiäry	N;NOM;SG
koste	koste	N;NOM;SG
käbristyö	käbristyn	V;IND;SG;1;POS;PRS
nuorekas	nuorekastu	ADJ;PRT;SG
loitosnägii	loitosnägijiä	ADJ;PRT;SG
mečästysaigu	mečästysaigu	N;NOM;SG
rožapuoliško	rožapuoliškuo	N;PRT;SG
havista	havistah	V;IND;PL;3;POS;PRS
jauhoaittu	jauhoaittua	N;PRT;SG
kynnys	kynnysty	N;PRT;SG
halgopino	halgopinon	N;GEN;SG
koupiilaiteh	koupiilaiteh	N;NOM;SG
välleta	vällenöy	V;IND;SG;3;POS;PRS
savehine	savehizen	ADJ;GEN;SG
paloittelu	paloitteluu	N;PRT;SG
illen	illen	ADJ;NOM;SG
vyöčin	vyöččimii	N;PRT;PL
idiä	ijän	V;IND;SG;1;POS;PRS
lämbö	lämbö	N;NOM;SG
karandiššu	karandiššua	N;PRT;SG
boba	bobua	N;PRT;SG
kiuzavus	kiuzavus	N;NOM;SG
globualline	globualline	ADJ;NOM;SG
huogavo	huogavon	N;GEN;SG
pilkettiä	pilkettäy	V;IND;SG;3;POS;PRS
vähävoimaine	vähävoimazii	ADJ;PRT;PL
verlibru	verlibran	N;GEN;SG
akkuvägi	akkuvägii	N;PRT;PL
povvatoi	povvattoman	ADJ;GEN;SG
suoduo	suoduu	V;IND;SG;3;POS;PRS
ajelu	ajeluu	N;PRT;SG
tazamiäräine	tazamiäräine	ADJ;NOM;SG
taidoaineh	taidoainehii	N;PRT;PL
kunnostua	kunnostau	V;IND;SG;3;POS;PRS
tuondutavar	tuondutavaran	N;GEN;SG
säveldämine	säveldämine	N;NOM;SG
rudžahtuakseh	rudžahtammos	V;IND;SG;1;POS;PRS
keskenaigaine	keskenaigazen	ADJ;GEN;SG
liygi	livvin	N;GEN;SG
loppuvokali	loppuvokaliloi	N;PRT;PL
tiijonandai	tiijonandajan	N;GEN;SG
zvonie	zvonitah	V;IND;PL;3;POS;PRS
kazvitiijolline	kazvitiijolline	ADJ;NOM;SG
čečotku	čečotku	N;NOM;SG
kiroillakseh	kiroileh	V;IND;SG;3;POS;PRS
violončeli	violončeli	N;NOM;SG
ulgomuodo	ulgomuodoloi	N;PRT;PL
koskematoi	koskematoi	ADJ;NOM;SG
rahvahanroinduperä	rahvahanroinduperiä	N;PRT;SG
vastahmielespiendy	vastahmielespiendii	N;PRT;PL
livvinkieli	livvinkielii	N;PRT;PL
mul’u	mul’un	ADJ;GEN;SG
pakasčirkoi	pakasčirkoin	N;GEN;SG
magavoaigu	magavoaigoi	N;PRT;PL
huondesvuoro	huondesvuoron	N;GEN;SG
melliččykivi	melliččykiven	N;GEN;SG
nägymine	nägymine	N;NOM;SG
sormikirjaimikko	sormikirjaimikkoloi	N;PRT;PL
memorialu	memorialu	N;NOM;SG
soloveilinduine	soloveilinduzii	N;PRT;PL
pal’l’as	pal’l’as	ADJ;NOM;SG
vastahottai	vastahottajan	ADJ;GEN;SG
rehevy	reheviä	ADJ;PRT;SG
mielekäs	mielekästy	ADJ;PRT;SG
lumovuttai	lumovuttajoi	ADJ;PRT;PL
pločku	pločkuloi	N;PRT;PL
hädäilläkseh	hädäilemmös	V;IND;SG;1;POS;PRS
suunnata	suunduau	V;IND;SG;3;POS;PRS
juotto	juoton	N;GEN;SG
deklinacii	deklinacien	N;GEN;SG
suolatoi	suolatoi	ADJ;NOM;SG
avto	avtuo	N;PRT;SG
vällähkö	vällähkö	ADJ;NOM;SG
juuretoi	juurettomii	ADJ;PRT;PL
kuvondutevolližus	kuvondutevolližuzii	N;PRT;PL
ruvvatoi	ruvvattomua	ADJ;PRT;SG
niškutugi	niškutugi	N;NOM;SG
parahodu	parahodoi	N;PRT;PL
kl’ona	kl’onoi	N;PRT;PL
tarkukohtu	tarkukohtu	N;NOM;SG
plastiekkuhuavoine	plastiekkuhuavostu	N;PRT;SG
romantikku	romantikkua	N;PRT;SG
tuhukuu	tuhukuuloi	N;PRT;PL
ruissieni	ruissiendy	N;PRT;SG
muahine	muahizen	ADJ;GEN;SG
šl’oimua	šl’oimau	V;IND;SG;3;POS;PRS
jagai	jagajoi	N;PRT;PL
silmälpido	silmälpidoloi	N;PRT;PL
langeilii	langeilijoi	N;PRT;PL
viirukku	viirukkoi	N;PRT;PL
pelvas	pelvas	N;NOM;SG
ylendys	ylendysty	N;PRT;SG
rahvasjoukko	rahvasjoukon	N;GEN;SG
puhtastus	puhtastuksen	N;GEN;SG
juohattua	juohattua	V;NFIN
n’uhiško	n’uhiškuo	ADJ;PRT;SG
kestiä	kestetäh	V;IND;PL;3;POS;PRS
kitailaine	kitailazii	N;PRT;PL
kyhnistiä	kyhnistän	V;IND;SG;1;POS;PRS
lambahanjuusto	lambahanjuusto	N;NOM;SG
pihl’aimarju	pihl’aimarjoi	N;PRT;PL
pölynimii	pölynimii	N;NOM;SG
miekkailii	miekkailii	N;NOM;SG
surematoi	suremattomua	ADJ;PRT;SG
peittoliitto	peittoliittoloi	N;PRT;PL
kylgiluu	kylgiluudu	N;PRT;SG
resuija	resuiččou	V;IND;SG;3;POS;PRS
diagnozu	diagnozan	N;GEN;SG
uskolline	uskollizen	ADJ;GEN;SG
satattua	satattau	V;IND;SG;3;POS;PRS
erimieližys	erimieližytty	N;PRT;SG
madoine	madoine	N;NOM;SG
äblistelläkseh	äblisteleh	V;IND;SG;3;POS;PRS
monimerkičykselline	monimerkičykselline	ADJ;NOM;SG
kamin	kaminoi	N;PRT;PL
palkanližä	palkanližiä	N;PRT;SG
zirkalo	zirkalon	N;GEN;SG
urai	urai	ADJ;NOM;SG
tuukkua	tuukkau	V;IND;SG;3;POS;PRS
miespolvi	miespolven	N;GEN;SG
rindulastu	rindulastu	N;NOM;SG
kiistu	kiistoi	N;PRT;PL
oijendua	oijendan	V;IND;SG;1;POS;PRS
juuretoi	juurettomua	ADJ;PRT;SG
huigietoi	huigiettomii	ADJ;PRT;PL
keriäjy	keriäjy	N;NOM;SG
vakkaine	vakkazen	N;GEN;SG
vaikkaniolii	vaikkaniolijua	ADJ;PRT;SG
razmoi	razmoidu	N;PRT;SG
ylendysmerki	ylendysmerki	N;NOM;SG
ägevys	ägevytty	N;PRT;SG
suittuo	suitun	V;IND;SG;1;POS;PRS
peruszakon	peruszakon	N;NOM;SG
ystävyslinnu	ystävyslinnua	N;PRT;SG
eläjientihevys	eläjientihevytty	N;PRT;SG
äbäzöijä	äbäzöijäh	V;IND;PL;3;POS;PRS
ärineh	ärinehen	N;GEN;SG
kuritus	kuritustu	N;PRT;SG
pakkaine	pakkaine	ADJ;NOM;SG
pitkynäppi	pitkynäppii	N;PRT;SG
hormu	hormu	N;NOM;SG
räyrettiä	räyrettiä	V;NFIN
ilotoi	ilottomii	ADJ;PRT;PL
vihaine	vihazii	ADJ;PRT;PL
vastukavaine	vastukavazii	ADJ;PRT;PL
hrizantiemu	hrizantiemua	N;PRT;SG
kovasydämelližys	kovasydämelližyzii	N;PRT;PL
kiistumielenvaihto	kiistumielenvaihtuo	N;PRT;SG
tappotanner	tappotanderii	N;PRT;PL
kirikönkiro	kirikönkiron	N;GEN;SG
ilmoittuo	ilmoitun	V;IND;SG;1;POS;PRS
tiijustella	tiijustellah	V;IND;PL;3;POS;PRS
viäristelläkseh	viäristelehes	V;IND;SG;3;POS;PRS
rannikko	rannikko	N;NOM;SG
ristintytär	ristintyttärii	N;PRT;PL
pellastua	pellastetah	V;IND;PL;3;POS;PRS
voitahtas	voitahtas	N;NOM;SG
gryhnistiä	gryhnistiä	V;NFIN
meččykurmoi	meččykurmoi	N;NOM;SG
bul’kahtellakseh	bul’kahtellakseh	V;NFIN
komendua	komendetah	V;IND;PL;3;POS;PRS
vastustua	vastustan	V;IND;SG;1;POS;PRS
tuulenhengi	tuulenhengie	N;PRT;SG
lepikkö	lepikkyö	N;PRT;SG
čöke	čökkien	V;IND;SG;1;POS;PRS
vizahtuakseh	vizahtahes	V;IND;SG;3;POS;PRS
peränpido	peränpivon	N;GEN;SG
jiäkur’oi	jiäkur’oloi	N;PRT;PL
vahneksie	vahneksiu	V;IND;SG;3;POS;PRS
mandariinu	mandariinu	N;NOM;SG
pippuri	pippuri	N;NOM;SG
tiijonsiirdoverko	tiijonsiirdoverkon	N;GEN;SG
emigracii	emigraciedu	N;PRT;SG
bleznuiččii	bleznuiččijan	ADJ;GEN;SG
ruoste	ruoste	N;NOM;SG
käzipagin	käzipaginua	N;PRT;SG
juurdua	juurran	V;IND;SG;1;POS;PRS
pezendy	pezendän	N;GEN;SG
lehtikirjutusruado	lehtikirjutusruavon	N;GEN;SG
voipuu	voipuuloi	N;PRT;PL
kiitoskirjaine	kiitoskirjazii	N;PRT;PL
koittelu	koittelu	N;NOM;SG
nälgähine	nälgähizii	ADJ;PRT;PL
huondesvalgei	huondesvalgei	N;NOM;SG
pystäi	pystäjiä	ADJ;PRT;SG
iänestäi	iänestäjiä	N;PRT;SG
lämmitä	lämbien	V;IND;SG;1;POS;PRS
vezibutkimies	vezibutkimiehii	N;PRT;PL
čondžoinnylgii	čondžoinnylgijöi	N;PRT;PL
šarkuttua	šarkuttau	V;IND;SG;3;POS;PRS
oras	oras	N;NOM;SG
hypätä	hyppiäy	V;IND;SG;3;POS;PRS
domru	domrii	N;PRT;PL
suoturveh	suoturveh	N;NOM;SG
tuijuttua	tuijuttau	V;IND;SG;3;POS;PRS
taivahanrandu	taivahanrannan	N;GEN;SG
inkeriläine	inkeriläzen	ADJ;GEN;SG
häkinjyvä	häkinjyvän	N;GEN;SG
koirantaudi	koirantaudi	N;NOM;SG
vengrieläine	vengrieläine	N;NOM;SG
valvondu	valvondua	N;PRT;SG
botuanikku	botuanikkoi	N;PRT;PL
zuaharipesku	zuaharipeskun	N;GEN;SG
dielontiedäi	dielontiedäjän	ADJ;GEN;SG
leibypala	leibypaloi	N;PRT;PL
mielihyvä	mielihyvä	N;NOM;SG
šuolisto	šuolistuo	N;PRT;SG
detsadu	detsaduu	N;PRT;SG
matkustai	matkustai	N;NOM;SG
randu	randoi	N;PRT;PL
keräkapustu	keräkapustan	N;GEN;SG
aluspohju	aluspohjan	N;GEN;SG
alatuuli	alatuuli	N;NOM;SG
kuundelii	kuundelijoi	N;PRT;PL
kurniekku	kurniekkua	N;PRT;SG
otto	ottoloi	N;PRT;PL
žualuijakseh	žualuičemmos	V;IND;SG;1;POS;PRS
valdahtulendu	valdahtulendua	N;PRT;SG
ennustusmerki	ennustusmerkin	N;GEN;SG
biljardupussi	biljardupusin	N;GEN;SG
ijättiä	ijättäy	V;IND;SG;3;POS;PRS
linnanhaldivosto	linnanhaldivoston	N;GEN;SG
paginanvedäi	paginanvedäjiä	N;PRT;SG
ombelus	ombeluksen	N;GEN;SG
tarkastamatoi	tarkastamattomua	ADJ;PRT;SG
veretöi	verettömän	ADJ;GEN;SG
nogevuo	nogevuu	V;IND;SG;3;POS;PRS
sanakirjutus	sanakirjutus	N;NOM;SG
liekastellakseh	liekasteleh	V;IND;SG;3;POS;PRS
varuamatoi	varuamatoi	ADJ;NOM;SG
pračku	pračkuloi	N;PRT;PL
merinuottu	merinuottua	N;PRT;SG
proufil’u	proufil’an	N;GEN;SG
köblöttiä	köblöttiä	V;NFIN
guazupastopäčči	guazupastopäččii	N;PRT;SG
hiekku	hiekkoi	N;PRT;PL
lapsiigä	lapsiigäigii	N;PRT;PL
mualuamistaido	mualuamistaido	N;NOM;SG
pagin	paginoi	N;PRT;PL
hil’l’aine	hil’l’aine	ADJ;NOM;SG
briljantu	briljantan	N;GEN;SG
yhtymys	yhtymys	N;NOM;SG
ičenkaččoi	ičenkaččojan	ADJ;GEN;SG
st’oklubumuagu	st’oklubumuagoi	N;PRT;PL
aigulugu	aiguluguu	N;PRT;SG
lipas	lippahan	N;GEN;SG
peitelläkseh	peittelehes	V;IND;SG;3;POS;PRS
ižändättömys	ižändättömyön	N;GEN;SG
jämpistyö	jämpistyö	V;NFIN
töhläkkö	töhläkkyö	ADJ;PRT;SG
hobjaine	hobjazen	ADJ;GEN;SG
tiijoituspalvelu	tiijoituspalvelun	N;GEN;SG
vähälellendettävy	vähälellendettävii	ADJ;PRT;PL
ezihammas	ezihammastu	N;PRT;SG
jägäl	jägäliä	N;PRT;SG
puija	puijah	V;IND;PL;3;POS;PRS
lagevo	lagevoloi	N;PRT;PL
vastahotto	vastahotto	N;NOM;SG
ubouuzi	ubouuzi	ADJ;NOM;SG
mustopačas	mustopačas	N;NOM;SG
tarkendus	tarkendus	N;NOM;SG
čuppu	čuppu	N;NOM;SG
hernehyt	hernehyön	N;GEN;SG
ruagu	ruagua	N;PRT;SG
vanandeh	vanandehii	N;PRT;PL
einehlaukku	einehlaukan	N;GEN;SG
farfouru	farfouran	N;GEN;SG
syvysyö	syvysyölöi	N;PRT;PL
ihalmo	ihalmuo	N;PRT;SG
bumerangu	bumerangua	N;PRT;SG
rima	rimua	N;PRT;SG
kurikoija	kurikoiččou	V;IND;SG;3;POS;PRS
kurčistuo	kurčistutah	V;IND;PL;3;POS;PRS
svättie	svättie	V;NFIN
kandelehelsoittai	kandelehelsoittajan	N;GEN;SG
nimikartočku	nimikartočkoi	N;PRT;PL
väline	väline	N;NOM;SG
pianino	pianino	N;NOM;SG
vierettiä	vierettiä	V;NFIN
jyristä	jyrizöy	V;IND;SG;3;POS;PRS
keskimäine	keskimäine	ADJ;NOM;SG
ližämakso	ližämakso	N;NOM;SG
vahnuontugi	vahnuontuven	N;GEN;SG
čähkiä	čähketäh	V;IND;PL;3;POS;PRS
tuttavuo	tuttavuu	V;IND;SG;3;POS;PRS
suojusjoukko	suojusjoukko	N;NOM;SG
ridžaittua	ridžaitetah	V;IND;PL;3;POS;PRS
perävymine	perävymizen	N;GEN;SG
kuuzikuuhine	kuuzikuuhizii	ADJ;PRT;PL
rammičču	rammiččuloi	ADJ;PRT;PL
tyhjänkeittäi	tyhjänkeittäjii	N;PRT;PL
numeruija	numeruija	V;NFIN
höštöböröi	höštöböröi	N;NOM;SG
ližämerki	ližämerki	N;NOM;SG
sybly	sybly	N;NOM;SG
nägii	nägijii	ADJ;PRT;PL
tavi	taviloi	N;PRT;PL
vägehtulii	vägehtulijan	ADJ;GEN;SG
vuotandu	vuotandu	N;NOM;SG
eroittamatoi	eroittamattomii	ADJ;PRT;PL
čiimottua	čiimottau	V;IND;SG;3;POS;PRS
plettie	pletin	V;IND;SG;1;POS;PRS
hairovus	hairovuksii	N;PRT;PL
laivankulletustiedo	laivankulletustiedo	N;NOM;SG
valdukunnanraja	valdukunnanrajan	N;GEN;SG
paginkanzu	paginkanzua	N;PRT;SG
bul’kettua	bul’kettau	V;IND;SG;3;POS;PRS
yläraja	yläraja	N;NOM;SG
adressi	adresin	N;GEN;SG
kugalaine	kugalastu	ADJ;PRT;SG
toimikundu	toimikunnan	N;GEN;SG
truba	truba	N;NOM;SG
kodivägi	kodivägi	N;NOM;SG
kivipohju	kivipohjii	N;PRT;PL
nilapuu	nilapuuloi	N;PRT;PL
pahantahtoi	pahantahtojoi	ADJ;PRT;PL
perävymine	perävymizii	N;PRT;PL
ven’alaine	ven’alazii	N;PRT;PL
jiäkondii	jiäkondii	N;NOM;SG
siirdyö	siirdyy	V;IND;SG;3;POS;PRS
kezälline	kezällizii	ADJ;PRT;PL
kala	kalan	N;GEN;SG
pabu	pabuloi	N;PRT;PL
aigulippu	aigulipun	N;GEN;SG
nytkyttiä	nytkytan	V;IND;SG;1;POS;PRS
moninoumeralline	moninoumeralline	ADJ;NOM;SG
kudamittuine	kudamittuzen	ADJ;GEN;SG
kyzymysadverbi	kyzymysadverbiloi	N;PRT;PL
viitata	viittuan	V;IND;SG;1;POS;PRS
tukehtus	tukehtuksii	N;PRT;PL
kummastella	kummastelou	V;IND;SG;3;POS;PRS
kačella	kaččelou	V;IND;SG;3;POS;PRS
segaine	segazen	ADJ;GEN;SG
keskikohtu	keskikohtan	N;GEN;SG
socialiruavonruadai	socialiruavonruadajii	N;PRT;PL
viimu	viiman	N;GEN;SG
vahata	vahata	V;NFIN
paginkieline	paginkieline	ADJ;NOM;SG
käpettiä	käpettiä	V;NFIN
iänestyskabin	iänestyskabinua	N;PRT;SG
tranzitiivuverbi	tranzitiivuverbin	N;GEN;SG
fizioterapevtu	fizioterapevtua	N;PRT;SG
päivännouzutuuli	päivännouzutuulen	N;GEN;SG
hallonhalguaju	hallonhalguajua	N;PRT;SG
vuolehtes	vuolehtestu	N;PRT;SG
sterilizuija	sterilizuiččou	V;IND;SG;3;POS;PRS
unohtuakseh	unohtetahes	V;IND;PL;3;POS;PRS
alus	aluksii	ADJ;PRT;PL
koiraittua	koiraitetah	V;IND;PL;3;POS;PRS
tyhjy	tyhjän	ADJ;GEN;SG
oččukiiru	oččukiiruloi	N;PRT;PL
häglätä	hägliän	V;IND;SG;1;POS;PRS
keitändyperti	keitändypertin	N;GEN;SG
tutkindolippu	tutkindolippuu	N;PRT;SG
čiristä	čirizen	V;IND;SG;1;POS;PRS
ulgopuoli	ulgopuolii	N;PRT;PL
arvostelii	arvostelijan	N;GEN;SG
kronkottua	kronkotan	V;IND;SG;1;POS;PRS
procentu	procentua	N;PRT;SG
hierates	hierates	N;NOM;SG
tammi	tammiloi	N;PRT;PL
myöndylaivasto	myöndylaivaston	N;GEN;SG
stoikku	stoikan	N;GEN;SG
tulensuamine	tulensuamine	N;NOM;SG
kiiristiä	kiiristän	V;IND;SG;1;POS;PRS
seizattuakseh	seizattuakseh	V;NFIN
tennispualikku	tennispualikkua	N;PRT;SG
pappi	papin	N;GEN;SG
piäuuličču	piäuuličču	N;NOM;SG
operiettu	operiettua	N;PRT;SG
raskuttua	raskutan	V;IND;SG;1;POS;PRS
čihmerdiä	čihmerdän	V;IND;SG;1;POS;PRS
mašin	mašinan	N;GEN;SG
kapsuttua	kapsuttua	V;NFIN
pergavo	pergavoloi	N;PRT;PL
kulmuviivatin	kulmuviivattimii	N;PRT;PL
kiännellä	kiändelöy	V;IND;SG;3;POS;PRS
pitkyjalgaine	pitkyjalgazii	N;PRT;PL
pitkysiimu	pitkysiiman	N;GEN;SG
segoilehtua	segoilehtetah	V;IND;PL;3;POS;PRS
litvalaine	litvalaine	ADJ;NOM;SG
lämmänpidäi	lämmänpidäjän	N;GEN;SG
lešku	leškan	N;GEN;SG
kostuttua	kostutan	V;IND;SG;1;POS;PRS
vägevy	vägeviä	ADJ;PRT;SG
tel’l’u	tel’l’ua	N;PRT;SG
ombelusnieglu	ombelusnieglua	N;PRT;SG
nyhtätä	nyhtiän	V;IND;SG;1;POS;PRS
valgehus	valgehuttu	N;PRT;SG
lodaittua	lodaitetah	V;IND;PL;3;POS;PRS
veziratas	veziratas	N;NOM;SG
sellofuanu	sellofuanu	N;NOM;SG
eleegii	eleegielöi	N;PRT;PL
keldusieni	keldusiendy	N;PRT;SG
nuorita	nuoričen	V;IND;SG;1;POS;PRS
yllinkylläine	yllinkylläine	ADJ;NOM;SG
tavaransiirdo	tavaransiirdoloi	N;PRT;PL
silmydiagnostiekku	silmydiagnostiekkua	N;PRT;SG
auttua	auttau	V;IND;SG;3;POS;PRS
niškuluu	niškuluudu	N;PRT;SG
pagizendu	pagizendoi	N;PRT;PL
virguniekku	virguniekan	N;GEN;SG
rinneh	rinneh	N;NOM;SG
luazerkirjutinlaiteh	luazerkirjutinlaittehii	N;PRT;PL
hairehtuo	hairehtuo	V;NFIN
potkiekseh	potkihes	V;IND;SG;3;POS;PRS
vahnoinkodi	vahnoinkoin	N;GEN;SG
ezimerkilline	ezimerkillizii	ADJ;PRT;PL
pidvittiä	pidvittiä	V;NFIN
kavondu	kavondua	N;PRT;SG
madožikko	madožikon	N;GEN;SG
nora	norii	N;PRT;PL
vavoi	vavoin	N;GEN;SG
kabli	kabli	N;NOM;SG
profilaktourii	profilaktourien	N;GEN;SG
kilketys	kilketysty	N;PRT;SG
jallas	jallaksii	N;PRT;PL
kaikennägöine	kaikennägözen	ADJ;GEN;SG
kryyčkäine	kryyčkäzii	N;PRT;PL
vate	vate	N;NOM;SG
hengähtelläkseh	hengähtelehes	V;IND;SG;3;POS;PRS
elektrolampu	elektrolampun	N;GEN;SG
marši	maršin	N;GEN;SG
ogahakas	ogahakkahan	ADJ;GEN;SG
vähäkalourine	vähäkalouristu	ADJ;PRT;SG
vedo	vedoloi	N;PRT;PL
linnanhaldivosto	linnanhaldivosto	N;NOM;SG
simfounii	simfounieloi	N;PRT;PL
muikistuo	muikistutah	V;IND;PL;3;POS;PRS
sv’oklu	sv’oklan	N;GEN;SG
kuohkuttua	kuohkuttua	V;NFIN
ehättiä	ehättiä	V;NFIN
korendo	korenduo	N;PRT;SG
vihmupilvi	vihmupilvie	N;PRT;SG
joudo	jouduo	N;PRT;SG
mielenpidäi	mielenpidäi	N;NOM;SG
pal’l’ata	pal’l’ata	V;NFIN
psihiatru	psihiatroi	N;PRT;PL
hyövynandai	hyövynandajii	ADJ;PRT;PL
yhtehkuulundu	yhtehkuulundoi	N;PRT;PL
tarkus	tarkuttu	N;PRT;SG
hirvei	hirvien	ADJ;GEN;SG
neste	neste	N;NOM;SG
bronzumedali	bronzumedaliloi	N;PRT;PL
kaikilekuului	kaikilekuulujua	ADJ;PRT;SG
pästär	pästär	N;NOM;SG
pohjupeitto	pohjupeiton	N;GEN;SG
kuuzikuuhine	kuuzikuuhine	ADJ;NOM;SG
äijähkö	äijähkyö	ADJ;PRT;SG
survuo	survuo	V;NFIN
luonneh	luonneh	N;NOM;SG
viruttuakseh	virutammos	V;IND;SG;1;POS;PRS
salbamo	salbamo	N;NOM;SG
žiälöijä	žiälöijä	V;NFIN
hizistä	hizistäh	V;IND;PL;3;POS;PRS
sulandeh	sulandehen	N;GEN;SG
kägöinmarju	kägöinmarju	N;NOM;SG
kanabro	kanabro	N;NOM;SG
pedäjikkö	pedäjikkö	N;NOM;SG
vezipilvi	vezipilvi	N;NOM;SG
nikkua	nikkau	V;IND;SG;3;POS;PRS
hebotahnut	hebotahnuttu	N;PRT;SG
parandua	parandua	V;NFIN
alkogoulitoi	alkogoulittomua	ADJ;PRT;SG
ohjuamine	ohjuamistu	N;PRT;SG
izrail’alaine	izrail’alazii	N;PRT;PL
kelloine	kellozii	N;PRT;PL
pruazniekku	pruazniekkua	N;PRT;SG
lumovus	lumovuksen	N;GEN;SG
ygistä	ygistäh	V;IND;PL;3;POS;PRS
myöstiä	myöstäy	V;IND;SG;3;POS;PRS
kaksiteräine	kaksiteräine	ADJ;NOM;SG
nieglu	nieglu	N;NOM;SG
hormuheiny	hormuheiniä	N;PRT;SG
pölypilvi	pölypilven	N;GEN;SG
opastussistiemu	opastussistiemoi	N;PRT;PL
čokähtiäkseh	čokähtämmös	V;IND;SG;1;POS;PRS
monikko	monikko	N;NOM;SG
uskoi	uskojoi	N;PRT;PL
tehniekky	tehniekköi	N;PRT;PL
komsahtuakseh	komsahtammos	V;IND;SG;1;POS;PRS
vinguttua	vingutan	V;IND;SG;1;POS;PRS
kaksinkerdaine	kaksinkerdazii	ADJ;PRT;PL
kuvittua	kuvitetah	V;IND;PL;3;POS;PRS
kuolendu	kuolendu	N;NOM;SG
kalastai	kalastajoi	N;PRT;PL
kannelline	kannellizen	ADJ;GEN;SG
ruskevus	ruskevuttu:	N;PRT;SG
sizärentytär	sizärentyttären	N;GEN;SG
vuozipuoliško	vuozipuoliškoloi	N;PRT;PL
koupii	koupien	N;GEN;SG
kačondukandu	kačondukandu	N;NOM;SG
ulgočura	ulgočurii	N;PRT;PL
ellendämine	ellendämisty	N;PRT;SG
ubornoi	ubornoloi	N;PRT;PL
hyödyö	hyödyö	V;NFIN
diettu	dietan	N;GEN;SG
kerrata	kerduau	V;IND;SG;3;POS;PRS
hondo	honduo	ADJ;PRT;SG
lainota	lainuon	V;IND;SG;1;POS;PRS
vierde	vierdien	N;GEN;SG
tinata	tinauan	V;IND;SG;1;POS;PRS
borču	borču	N;NOM;SG
žuaru	žuaruu	N;PRT;SG
ozutella	ozuttelou	V;IND;SG;3;POS;PRS
ahven	ahven	N;NOM;SG
jougu	jouguan	N;GEN;SG
kököttiä	kököttiä	V;NFIN
ruozmeikko	ruozmeikkoloi	N;PRT;PL
ruadivonkuundelii	ruadivonkuundelijan	N;GEN;SG
peldohiiri	peldohiirilöi	N;PRT;PL
mödžöi	mödžöin	N;GEN;SG
pul’su	pul’sii	N;PRT;PL
verbl’uudu	verbl’uudu	N;NOM;SG
perustatoi	perustatoi	ADJ;NOM;SG
myrkykäs	myrkykästy	ADJ;PRT;SG
rikittiä	rikitän	V;IND;SG;1;POS;PRS
liikutella	liikuttelou	V;IND;SG;3;POS;PRS
fruktusadu	fruktusadu	N;NOM;SG
zuaharipesku	zuaharipesku	N;NOM;SG
ylängö	ylängö	N;NOM;SG
syödävy	syödävän	N;GEN;SG
tervehyöt	tervehyöt	N;NOM;SG
kačelmu	kačelman	N;GEN;SG
ehtypuoli	ehtypuolii	N;PRT;PL
intonacii	intonacien	N;GEN;SG
orju	orjua	N;PRT;SG
muuzikualline	muuzikuallistu	ADJ;PRT;SG
ylävirdu	ylävirdua	N;PRT;SG
merilohi	merilohtu	N;PRT;SG
ylbevyö	ylbevyy	V;IND;SG;3;POS;PRS
vagoižikko	vagoižikkuo	N;PRT;SG
činkata	činkuan	V;IND;SG;1;POS;PRS
kestäi	kestäjöi	ADJ;PRT;PL
turvehtie	turvehtie	V;NFIN
unehine	unehine	ADJ;NOM;SG
tavata	tabuan	V;IND;SG;1;POS;PRS
piinata	piinatah	N;PRT;PL
tehniekku	tehniekkoi	N;PRT;PL
gruadusniekku	gruadusniekkoi	N;PRT;PL
pahoittua	pahoitetah	V;IND;PL;3;POS;PRS
hiildyö	hiildyy	V;IND;SG;3;POS;PRS
kivipohju	kivipohjan	N;GEN;SG
viheldiä	viheldäy	V;IND;SG;3;POS;PRS
suksikotat	suksikottien	N;GEN;PL
terendiä	terendiä	V;NFIN
härkinheiny	härkinheinän	N;GEN;SG
elektročökin	elektročökkimen	N;GEN;SG
interrogatiivupronominu	interrogatiivupronominua	N;PRT;SG
galaktiekku	galaktiekan	N;GEN;SG
kartohku	kartohkoi	N;PRT;PL
muninduaigu	muninduaijan	N;GEN;SG
lapsienpäivykodi	lapsienpäivykodiloi	N;PRT;PL
keritä	keriey	V;IND;SG;3;POS;PRS
kuolluh	kuolluzii	ADJ;PRT;PL
herkevyö	herkevyö	V;NFIN
tulukset	tulukset	N;NOM;SG
tiediä	tiediä	V;NFIN
čerstavuttua	čerstavutetah	V;IND;PL;3;POS;PRS
vilistä	vilizen	V;IND;SG;1;POS;PRS
hormeikko	hormeikkoloi	N;PRT;PL
kaste	kastieloi	N;PRT;PL
alguainehine	alguainehizen	ADJ;GEN;SG
kostevus	kostevustu	N;PRT;SG
vierde	vierde	N;NOM;SG
kaktussu	kaktusan	N;GEN;SG
rikki	rikkilöi	N;PRT;PL
päivystäi	päivystäjän	N;GEN;SG
pehmevys	pehmevys	N;NOM;SG
ulgoazieloinministru	ulgoazieloinministran	N;GEN;SG
liečetiijolline	liečetiijollistu	ADJ;PRT;SG
kagluremeni	kagluremenii	N;PRT;SG
tolkutoi	tolkuttomua	ADJ;PRT;SG
ribistä	ribizen	V;IND;SG;1;POS;PRS
hyväily	hyväilyn	N;GEN;SG
tiijustelii	tiijustelijan	N;GEN;SG
jupku	jupkan	N;GEN;SG
nuorus	nuorus	N;NOM;SG
valerjuanutipat	valerjuanutipat	N;NOM;SG
mainehikas	mainehikkahan	ADJ;GEN;SG
pul’su	pul’su	N;NOM;SG
ulahtuakseh	ulahtetahes	V;IND;PL;3;POS;PRS
pöyhötä	pöyhönöy	V;IND;SG;3;POS;PRS
mustottua	mustotan	V;IND;SG;1;POS;PRS
ižänmua	ižänmua	N;NOM;SG
obrazu	obrazu	N;NOM;SG
opastusnelländes	opastusnelländeksen	N;GEN;SG
azettua	azettua	V;NFIN
tevokas	tevokkahan	ADJ;GEN;SG
mainita	mainiččou	V;IND;SG;3;POS;PRS
vaivuttua	vaivutetah	V;IND;PL;3;POS;PRS
bohattu	bohattu	ADJ;NOM;SG
por’atku	por’atku	N;NOM;SG
huonus	huonuksii	N;PRT;PL
rängeh	rängehen	N;GEN;SG
pirdu	pirdua	N;PRT;SG
sylgie	sylgie	V;NFIN
valličustulos	valličustulostu	N;PRT;SG
kivos	kivos	N;NOM;SG
tazapuoline	tazapuolistu	ADJ;PRT;SG
palvelu	palvelun	N;GEN;SG
ruadoaigu	ruadoaigua	N;PRT;SG
pualikku	pualikan	N;GEN;SG
lämmityslaiteh	lämmityslaiteh	N;NOM;SG
veziheiny	veziheinän	N;GEN;SG
tihi	tihi	N;NOM;SG
armo	armon	N;GEN;SG
kiistämätöi	kiistämättömän	ADJ;GEN;SG
tarkastai	tarkastajoi	N;PRT;PL
kazvatussistiemu	kazvatussistiemu	N;NOM;SG
käzipuoliško	käzipuoliškoloi	N;PRT;PL
johtai	johtai	N;NOM;SG
kamahtuakseh	kamahtuakseh	V;NFIN
toizenmoine	toizenmoizii	ADJ;PRT;PL
poijanpoigu	poijanpoigu	N;NOM;SG
torpu	torpua	N;PRT;SG
rahmannoi	rahmannoi	ADJ;NOM;SG
lämminverine	lämminverizen	ADJ;GEN;SG
lyhytmieline	lyhytmielizii	ADJ;PRT;PL
seiväs	seivästy	N;PRT;SG
siäsputniekku	siäsputniekan	N;GEN;SG
alembaine	alembazii	ADJ;PRT;PL
ristitty	ristittyy	ADJ;PRT;SG
markintalovus	markintalovus	N;NOM;SG
vähälkuulužu	vähälkuulužu	ADJ;NOM;SG
jogaaigaine	jogaaigazen	ADJ;GEN;SG
jogapäiväine	jogapäiväzen	ADJ;GEN;SG
reidu	reidoi	N;PRT;PL
helletä	hellenöy	V;IND;SG;3;POS;PRS
kananpoigu	kananpoigu	N;NOM;SG
ilduyö	ilduyö	N;NOM;SG
galstukku	galstukkoi	N;PRT;PL
sävelikkö	sävelikkyö	N;PRT;SG
lepites	lepiteksen	N;GEN;SG
huuvehtuo	huuvehtuo	V;NFIN
čole	čole	N;NOM;SG
atomjiänmurendailaivu	atomjiänmurendailaivu	N;NOM;SG
kulkutaudiheiny	kulkutaudiheinii	N;PRT;PL
modernu	modernu	N;NOM;SG
kezoisoba	kezoisobii	N;PRT;PL
oigevustiijolline	oigevustiijolline	ADJ;NOM;SG
tuomehine	tuomehine	ADJ;NOM;SG
piäpalvelii	piäpalvelijoi	N;PRT;PL
savutus	savutuksen	N;GEN;SG
piälyssoba	piälyssobua	N;PRT;SG
etnogruafii	etnogruafieloi	N;PRT;PL
kadal	kadal	N;NOM;SG
alendushinnat	alendushindoi	N;PRT;PL
nänni	nännin	N;GEN;SG
puolipimei	puolipimien	ADJ;GEN;SG
ruskottua	ruskotan	V;IND;SG;1;POS;PRS
heläittiä	heläitän	V;IND;SG;1;POS;PRS
hyövyneččimättömys	hyövyneččimättömyön	N;GEN;SG
arvotoi	arvottoman	ADJ;GEN;SG
höyryttiä	höyryttiä	V;NFIN
pattevus	pattevus	N;NOM;SG
repressiiruija	repressiiruijah	V;IND;PL;3;POS;PRS
kampottu	kampottoi	N;PRT;PL
puristua	puristau	V;IND;SG;3;POS;PRS
homsuttua	homsutetah	V;IND;PL;3;POS;PRS
aksiomu	aksioman	N;GEN;SG
sanelmus	sanelmustu	N;PRT;SG
kala	kala	N;NOM;SG
kunnivoitettu	kunnivoitettuloi	ADJ;PRT;PL
turvata	turvuau	V;IND;SG;3;POS;PRS
manuahu	manuahoi	N;PRT;PL
kilaittua	kilaittua	V;NFIN
humaljuomine	humaljuomine	N;NOM;SG
mečänkuadai	mečänkuadajan	N;GEN;SG
pahoitellakseh	pahoitellahes	V;IND;PL;3;POS;PRS
arhitektuuru	arhitektuuru	N;NOM;SG
mauroi	mauroidu	N;PRT;SG
ližätä	ližätä	V;NFIN
laihin	laihin	N;NOM;SG
poltua	poltan	V;IND;SG;1;POS;PRS
ilminäine	ilminäzii	ADJ;PRT;PL
pikšu	pikšoi	N;PRT;PL
kižajoukko	kižajoukko	N;NOM;SG
venehmotor	venehmotoran	N;GEN;SG
randučibi	randučibilöi	N;PRT;PL
ottaakseh	en olle ottanuhes	V;PRF;POT;SG;1;NEG;PRS
hyybii	hyybijii	N;PRT;PL
persounatoi	persounatoi	ADJ;NOM;SG
kazvatussistiemu	kazvatussistiemoi	N;PRT;PL
kurmuta	kurmuou	V;IND;SG;3;POS;PRS
formusoba	formusobii	N;PRT;PL
lettu	letun	N;GEN;SG
keldaine	keldastu	ADJ;PRT;SG
movvakas	movvakkahan	ADJ;GEN;SG
sivuloinraippavus	sivuloinraippavus	N;NOM;SG
kovaiänine	kovaiänisty	ADJ;PRT;SG
piättäi	piättäjän	N;GEN;SG
poliruittu	poliruitun	ADJ;GEN;SG
rapsata	rapsata	V;NFIN
likvidiiruičendu	likvidiiruičendu	N;NOM;SG
rizinänkeskine	rizinänkeskine	ADJ;NOM;SG
ulahtuakseh	ulahtammos	V;IND;SG;1;POS;PRS
syöndyhimo	syöndyhimuo	N;PRT;SG
rekluamu	rekluamoi	N;PRT;PL
astuo	etto ollus astunuh	V;PRF;COND;PL;2;NEG;PST
merki	merkin	N;GEN;SG
ottaakseh	en olluh ottanuhes	V;PRF;IND;SG;1;NEG;PST
bes’odu	bes’odu	N;NOM;SG
enimistö	enimistölöi	N;PRT;PL
lappu	lapua	N;PRT;SG
linnanjohtai	linnanjohtai	N;NOM;SG
kodvu	kodvu	N;NOM;SG
tarkunägöine	tarkunägözen	ADJ;GEN;SG
priičču	priičču	N;NOM;SG
hienondua	hienondua	V;NFIN
alguristikanzu	alguristikanzua	N;PRT;SG
kirjavus	kirjavuzii	N;PRT;PL
bliämitä	bliämiččöy	V;IND;SG;3;POS;PRS
sugupuoli	sugupuoldu	N;PRT;SG
sijalline	sijalline	ADJ;NOM;SG
benzin	benzinöi	N;PRT;PL
tugipuu	tugipuu	N;NOM;SG
ottaakseh	ottanuzittos	V;IPFV;COND;SG;2;POS;PST
vegetariansu	vegetariansoi	N;PRT;PL
vahnu	vahnan	ADJ;GEN;SG
hardiekas	hardiekas	ADJ;NOM;SG
muamankieline	muamankielizii	ADJ;PRT;PL
poččiloinkaččoi	poččiloinkaččojoi	N;PRT;PL
voračču	voraččuloi	ADJ;PRT;PL
nuoreta	nuorenen	V;IND;SG;1;POS;PRS
kiittämättömys	kiittämättömyön	N;GEN;SG
tottumatoi	tottumatoi	ADJ;NOM;SG
nagrismua	nagrismualoi	N;PRT;PL
mikroskouppu	mikroskouppu	N;NOM;SG
vongeh	vongehtu	N;PRT;SG
pyhitys	pyhitys	N;NOM;SG
vil’l’akas	vil’l’akkahii	ADJ;PRT;PL
ambulatourii	ambulatourien	N;GEN;SG
uudine	uudistu	N;PRT;SG
valliččii	valliččijoi	N;PRT;PL
pahanluadii	pahanluadii	N;NOM;SG
kiirehine	kiirehisty	ADJ;PRT;SG
vilustuo	vilustutah	V;IND;PL;3;POS;PRS
ovvostua	ovvostetah	V;IND;PL;3;POS;PRS
pajatandu	pajatandan	N;GEN;SG
velgavuo	velgavutah	V;IND;PL;3;POS;PRS
köyhentaudi	köyhentavvin	N;GEN;SG
peruskursu	peruskursan	N;GEN;SG
šoijata	šoiguan	V;IND;SG;1;POS;PRS
pastopäčči	pastopäččii	N;PRT;SG
läbimenokohtu	läbimenokohtua	N;PRT;SG
huonohkuulii	huonohkuulijua	ADJ;PRT;SG
leppyö	leppyy	V;IND;SG;3;POS;PRS
kazvo	kazvoloi	N;PRT;PL
jyrketä	jyrketä	V;NFIN
myödäine	myödäzii	ADJ;PRT;PL
reikku	reikan	N;GEN;SG
bankrottu	bankrottua	N;PRT;SG
päivänkohtaine	päivänkohtaine	N;NOM;SG
hengenhädä	hengenhädä	N;NOM;SG
paheksindu	paheksindua	N;PRT;SG
huolehtimine	huolehtimizen	N;GEN;SG
vonguo	vonguu	V;IND;SG;3;POS;PRS
vagavus	vagavuon	N;GEN;SG
seiny	seinii	N;PRT;PL
likvidiiruija	likvidiiruiččou	V;IND;SG;3;POS;PRS
pystyaidu	pystyaijan	N;GEN;SG
čuajuluzikkaine	čuajuluzikkaine	N;NOM;SG
valloituspoliitiekku	valloituspoliitiekan	N;GEN;SG
ozutteluvešši	ozutteluveššilöi	N;PRT;PL
piädyö	piädyy	V;IND;SG;3;POS;PRS
jyvetä	jyvetäh	V;IND;PL;3;POS;PRS
vikkelys	vikkelyön	N;GEN;SG
potkičču	potkičču	ADJ;NOM;SG
tähky	tähky	N;NOM;SG
buuristua	buuristetah	V;IND;PL;3;POS;PRS
lapsienlapset	lapsienlapsien	N;GEN;PL
lodineh	lodineh	N;NOM;SG
päivymatku	päivymatku	N;NOM;SG
kuvata	kuvuan	V;IND;SG;1;POS;PRS
alguaigaine	alguaigazii	ADJ;PRT;PL
jyvetä	jygenen	V;IND;SG;1;POS;PRS
alguvuozi	alguvuozii	N;PRT;PL
vähälopastunnuh	vähälopastunnuttu	ADJ;PRT;SG
notko	notkuo	N;PRT;SG
aigu	aijan	N;GEN;SG
kanzoinväline	kanzoinvälizen	ADJ;GEN;SG
haravanpii	haravanpiidy	N;PRT;SG
yhtenluaduine	yhtenluaduine	N;NOM;SG
lamaaidu	lamaaidoi	N;PRT;PL
toziolo	toziolo	N;NOM;SG
alevuttua	alevuttua	V;NFIN
krinčaine	krinčastu	N;PRT;SG
tervuamatoi	tervuamattoman	ADJ;GEN;SG
lämmin	lämmin	N;NOM;SG
kačondukandu	kačondukannan	N;GEN;SG
algueläi	algueläi	N;NOM;SG
kurikku	kurikan	N;GEN;SG
erilline	erillizen	ADJ;GEN;SG
viinat	viinoi	N;PRT;PL
kabju	kabjua	N;PRT;SG
riidavuttua	riidavuttau	V;IND;SG;3;POS;PRS
taksoparku	taksoparkua	N;PRT;SG
segatavarlaukku	segatavarlaukan	N;GEN;SG
rozvojoukko	rozvojoukkoloi	N;PRT;PL
rauguo	rauguu	V;IND;SG;3;POS;PRS
valličuskundu	valličuskundii	N;PRT;PL
čuloi	čuloi	N;NOM;SG
iirissu	iirisan	N;GEN;SG
čelata	čelata	V;NFIN
sel’soviettu	sel’soviettoi	N;PRT;PL
huonoluaduine	huonoluaduine	ADJ;NOM;SG
taidovestos	taidovestoksen	N;GEN;SG
vuozikerähmö	vuozikerähmön	N;GEN;SG
maineh	mainehtu	N;PRT;SG
hyydiä	hyydäy	V;IND;SG;3;POS;PRS
kiirehelline	kiirehellisty	ADJ;PRT;SG
talvi	talvii	N;PRT;PL
rähy	rähylöi	N;PRT;PL
rungo	rungon	N;GEN;SG
sabilas	sabilahii	N;PRT;PL
mereži	merežii	N;PRT;SG
tolkutoi	tolkuttoman	ADJ;GEN;SG
tyyni	tyyndy	N;PRT;SG
kuduo	kudou	V;IND;SG;3;POS;PRS
luahkan’n’u	luahkan’n’oi	N;PRT;PL
ruvvakas	ruvvakkahan	ADJ;GEN;SG
raippavus	raippavuksii	N;PRT;PL
virši	virši	N;NOM;SG
yksiozaine	yksiozazen	ADJ;GEN;SG
lipsuttua	lipsuttua	V;NFIN
urvakas	urvakkahan	ADJ;GEN;SG
hallindohuonus	hallindohuonus	N;NOM;SG
tazakylgine	tazakylgizii	ADJ;PRT;PL
lämmin	lämmii	N;PRT;PL
muaruavontiedäi	muaruavontiedäjöi	N;PRT;PL
haikostellakseh	haikostelemmos	V;IND;SG;1;POS;PRS
droždei	droždien	N;GEN;SG
denganandai	denganandajii	N;PRT;PL
sajendettu	sajendettuloi	ADJ;PRT;PL
kulonurmi	kulonurmen	N;GEN;SG
hömsähtiäkseh	hömsähtämmös	V;IND;SG;1;POS;PRS
polguin	polguimii	N;PRT;PL
nuorus	nuoruon	N;GEN;SG
torfu	torfii	N;PRT;PL
šakšu	šakšun	N;GEN;SG
syöttäi	syöttäjiä	N;PRT;SG
čäigyö	čäigyö	V;NFIN
möngeh	möngehty	N;PRT;SG
lädžötä	lädžötä	V;NFIN
etnogruafielline	etnogruafiellizen	ADJ;GEN;SG
kabaittua	kabaittau	V;IND;SG;3;POS;PRS
tervehtyttäi	tervehtyttäjiä	ADJ;PRT;SG
viglua	viglau	V;IND;SG;3;POS;PRS
loppie	loppou	V;IND;SG;3;POS;PRS
poltateksenjälgi	poltateksenjälgi	N;NOM;SG
kehityskauzi	kehityskauzi	N;NOM;SG
ylähys	ylähys	N;NOM;SG
hengenrauhu	hengenrauhu	N;NOM;SG
kiändiä	kiännän	V;IND;SG;1;POS;PRS
pohjattomus	pohjattomus	N;NOM;SG
škuappu	škuappu	N;NOM;SG
upottua	upottua	V;NFIN
pal’čostua	pal’čostetah	V;IND;PL;3;POS;PRS
suolatus	suolatus	N;NOM;SG
möhkäleh	möhkälehen	N;GEN;SG
virguniekku	virguniekkua	N;PRT;SG
jatkamine	jatkamizen	N;GEN;SG
valelendurengi	valelendurengi	N;NOM;SG
granuattupuu	granuattupuun	N;GEN;SG
pasku	paskua	N;PRT;SG
suksi	suksi	N;NOM;SG
jovenajai	jovenajajoi	N;PRT;PL
lieččie	lieččiy	V;IND;SG;3;POS;PRS
suojuspuoline	suojuspuolizen	ADJ;GEN;SG
basketbolistu	basketbolistan	N;GEN;SG
vuoldamatoi	vuoldamattomii	ADJ;PRT;PL
ounastuo	ounastuo	V;NFIN
kezoinkylbii	kezoinkylbijii	N;PRT;PL
n’aukata	n’aukkuan	V;IND;SG;1;POS;PRS
kuožali	kuožaliloi	N;PRT;PL
rungakas	rungakas	ADJ;NOM;SG
bombittua	bombittau	V;IND;SG;3;POS;PRS
palopaikku	palopaikkoi	N;PRT;PL
häkki	häkki	N;NOM;SG
ahnastua	ahnastau	V;IND;SG;3;POS;PRS
upotus	upotustu	N;PRT;SG
padapaikku	padapaikkoi	N;PRT;PL
kaldailla	kaldailla	V;NFIN
voitolline	voitollistu	ADJ;PRT;SG
narkoutiekku	narkoutiekan	N;GEN;SG
muapala	muapala	N;NOM;SG
ounas	ounahii	ADJ;PRT;PL
čodrie	čodrie	V;NFIN
puretes	pureteksii	N;PRT;PL
lajeta	lajetah	V;IND;PL;3;POS;PRS
uskoittua	uskoittua	V;NFIN
galstukku	galstukan	N;GEN;SG
kiškoi	kiškojoi	N;PRT;PL
koillispuoli	koillispuoli	N;NOM;SG
vivuta	vivuta	V;NFIN
laskevuo	laskevutah	V;IND;PL;3;POS;PRS
ydžistä	ydžistäh	V;IND;PL;3;POS;PRS
kiittämätöi	kiittämättömän	ADJ;GEN;SG
krossujallačit	krossujallaččiloin	N;GEN;PL
rataskuožali	rataskuožalin	N;GEN;SG
libiehkö	libiehkölöi	ADJ;PRT;PL
lähimäine	lähimästy	ADJ;PRT;SG
krägähyö	krägähyn	V;IND;SG;1;POS;PRS
apuatilline	apuatillistu	ADJ;PRT;SG
tartellakseh	tartelemmos	V;IND;SG;1;POS;PRS
imettiä	imetetäh	V;IND;PL;3;POS;PRS
sijalline	sijallizen	ADJ;GEN;SG
oigevuseččo	oigevuseččuo	N;PRT;SG
kiitellä	kiitellä	V;NFIN
vekseli	vekselin	N;GEN;SG
stomatolougii	stomatolougiedu	N;PRT;SG
kiämi	kiämin	N;GEN;SG
kouhkoitaudi	kouhkoitavvin	N;GEN;SG
nedälikirju	nedälikirjan	N;GEN;SG
nimipäivät	nimipäivii	N;PRT;SG
varaččuluondoine	varaččuluondoine	ADJ;NOM;SG
terrortego	terrortego	N;NOM;SG
račoi	račoi	N;NOM;SG
ablatiivu	ablatiivu	N;NOM;SG
plastiekku	plastiekkoi	N;PRT;PL
koiras	koiraksen	N;GEN;SG
samannägöine	samannägözen	ADJ;GEN;SG
hairahtuo	hairahtuu	V;IND;SG;3;POS;PRS
maksokyvytöi	maksokyvyttömiä	ADJ;PRT;SG
higi	higi	ADJ;NOM;SG
ižäččykoiru	ižäččykoirua	N;PRT;SG
myvvitellä	myvvittelöy	V;IND;SG;3;POS;PRS
vastahottoantennu	vastahottoantennoi	N;PRT;PL
räpistyö	räpistyö	V;NFIN
viheldellä	viheldelöy	V;IND;SG;3;POS;PRS
kyndžätes	kyndžätesty	N;PRT;SG
raudaine	raudaine	ADJ;NOM;SG
riehkiekseh	riehkiekseh	V;NFIN
avvopäčči	avvopäčin	N;GEN;SG
hullavo	hullavo	N;NOM;SG
glaukomu	glaukoman	N;GEN;SG
unohtus	unohtuksen	N;GEN;SG
kahačču	kahaččuu	N;PRT;SG
halvastua	halvastan	V;IND;SG;1;POS;PRS
fonotiekku	fonotiekan	N;GEN;SG
halliččii	halliččijoi	N;PRT;PL
turvata	turvatah	V;IND;PL;3;POS;PRS
pagohtyöndö	pagohtyöndö	N;NOM;SG
suksivoije	suksivoidieloi	N;PRT;PL
ločotus	ločotuksen	N;GEN;SG
eistellä	eistelläh	V;IND;PL;3;POS;PRS
bariššu	bariššua	N;PRT;SG
nilapuu	nilapuun	N;GEN;SG
puuttuo	puututah	V;IND;PL;3;POS;PRS
omanmuansuvaičus	omanmuansuvaičus	N;NOM;SG
oigevuksenrikondu	oigevuksenrikondoi	N;PRT;PL
granuattupuu	granuattupuu	N;NOM;SG
rapistua	rapistan	V;IND;SG;1;POS;PRS
siirdolaine	siirdolastu	N;PRT;SG
žiitoija	žiitoičen	V;IND;SG;1;POS;PRS
varattavu	varattavu	ADJ;NOM;SG
navediekseh	navedimmos	V;IND;SG;1;POS;PRS
suoluvakku	suoluvakan	N;GEN;SG
sälgy	sälgy	N;NOM;SG
kielentutkii	kielentutkijii	N;PRT;PL
loppukuu	loppukuun	N;GEN;SG
kuvahaine	kuvahastu	N;PRT;SG
taguo	tavotah	V;IND;PL;3;POS;PRS
muansäräitys	muansäräityksen	N;GEN;SG
ižänmua	ižänmuadu	N;PRT;SG
mököttiä	mököttiä	V;NFIN
heinysuatto	heinysuaton	N;GEN;SG
emäpočči	emäpoččii	N;PRT;SG
mečäntiedo	mečäntiedo	N;NOM;SG
emäččyhebo	emäččyheboloi	N;PRT;PL
korendo	korendo	N;NOM;SG
kiketys	kiketyksen	N;GEN;SG
erehtymätöi	erehtymättömiä	ADJ;PRT;SG
äijänkerdaine	äijänkerdastu	ADJ;PRT;SG
l’uboi	l’uboi	N;NOM;SG
hiirenheiny	hiirenheiniä	N;PRT;SG
vintovku	vintovkoi	N;PRT;PL
kalmupačas	kalmupaččahan	N;GEN;SG
ammuine	ammuzii	ADJ;PRT;PL
etnossu	etnossoi	N;PRT;PL
kolmekolkaine	kolmekolkazii	ADJ;PRT;PL
tehniekky	tehniekkiä	N;PRT;SG
palua	palua	V;NFIN
kaivonsalvos	kaivonsalvostu	N;PRT;SG
valehelline	valehellizen	ADJ;GEN;SG
matkudovariššu	matkudovariššoi	N;PRT;PL
čiihistyö	čiihistyn	V;IND;SG;1;POS;PRS
ansambl’u	ansambl’an	N;GEN;SG
keskenkypsy	keskenkypsiä	ADJ;PRT;SG
diiviekseh	diivimmös	V;IND;SG;1;POS;PRS
miäččy	miäčyn	N;GEN;SG
kirikönkello	kirikönkellon	N;GEN;SG
tomineh	tominehii	N;PRT;PL
taijokas	taijokas	ADJ;NOM;SG
hinnoittua	hinnoitan	V;IND;SG;1;POS;PRS
nälgy	nälgiä	N;PRT;SG
meloudine	meloudizen	ADJ;GEN;SG
planiiruija	planiiruija	V;NFIN
individualine	individualistu	ADJ;PRT;SG
kara	karoi	N;PRT;PL
tumeh	tumehen	N;GEN;SG
opastusmeno	opastusmeno	N;NOM;SG
tuhkimus	tuhkimuksii	N;PRT;PL
žerebei	žerebielöi	N;PRT;PL
kirjuttamine	kirjuttamistu	N;PRT;SG
tiijolline	tiijollizii	ADJ;PRT;PL
tuatto	tuatto	N;NOM;SG
ahvenikas	ahvenikas	ADJ;NOM;SG
šohelo	šohelon	N;GEN;SG
pal’l’aine	pal’l’azii	N;PRT;PL
ojandeh	ojandehen	N;GEN;SG
čällävyö	čällävytäh	V;IND;PL;3;POS;PRS
rauduseppy	rauduseppiä	N;PRT;SG
kodialoveh	kodialovehtu	N;PRT;SG
komandu	komandan	N;GEN;SG
astuo	et olis astunuh	V;PRF;COND;SG;2;NEG;PRS
vedohebo	vedohebuo	N;PRT;SG
pečenny	pečenniä	N;PRT;SG
bel’gieläine	bel’gieläzii	N;PRT;PL
kuari	kuardu	N;PRT;SG
käitöi	käittömii	ADJ;PRT;PL
lipettiä	lipettäy	V;IND;SG;3;POS;PRS
rizinky	rizinköi	N;PRT;PL
ylivauhti	ylivauhtii	N;PRT;SG
käzimiäččyhkižuaju	käzimiäččyhkižuajoi	N;PRT;PL
piirdourokku	piirdourokan	N;GEN;SG
vedonevvot	vedonevvot	N;NOM;PL
jalgumiäččy	jalgumiäččyy	N;PRT;SG
kodiigävys	kodiigävys	N;NOM;SG
huavikko	huavikkoloi	N;PRT;PL
jumalanuskomatoi	jumalanuskomatoi	N;NOM;SG
rajon	rajonua	N;PRT;SG
omanarvontundo	omanarvontunduo	N;PRT;SG
keksitty	keksityn	ADJ;GEN;SG
lökšähtiäkseh	lökšähtämmös	V;IND;SG;1;POS;PRS
rahtimakso	rahtimaksuo	N;PRT;SG
kyskevyö	kyskevyö	V;NFIN
saluattu	saluatan	N;GEN;SG
kur’oigr’uuhu	kur’oigr’uuhu	N;NOM;SG
nenänsydii	nenänsydijän	N;GEN;SG
loppukezä	loppukeziä	N;PRT;SG
oravu	oravoi	N;PRT;PL
suojelurokotus	suojelurokotuksii	N;PRT;PL
vihmusiä	vihmusiä	N;NOM;SG
muzavattavu	muzavattavan	ADJ;GEN;SG
omaničenkaičusvainu	omaničenkaičusvainu	N;NOM;SG
fruktusadu	fruktusavun	N;GEN;SG
kebjendys	kebjendyksii	N;PRT;PL
kudrit	kudriloi	N;PRT;PL
näiverdiä	näiverdäy	V;IND;SG;3;POS;PRS
čuudie	čuudin	V;IND;SG;1;POS;PRS
hollu	hollu	N;NOM;SG
marinuittu	marinuittu	ADJ;NOM;SG
tuskaine	tuskazen	ADJ;GEN;SG
vedrei	vedrei	ADJ;NOM;SG
huahittua	huahittua	V;NFIN
härmy	härmy	N;NOM;SG
lujus	lujuttu	N;PRT;SG
mötkähtiäkseh	mötkähtähes	V;IND;SG;3;POS;PRS
mielenkiindoine	mielenkiindozen	ADJ;GEN;SG
kadajikko	kadajikon	N;GEN;SG
nellivuodehine	nellivuodehine	ADJ;NOM;SG
kiildiä	kiildiä	V;NFIN
liturgii	liturgiedu	N;PRT;SG
estietöi	estietöi	ADJ;NOM;SG
hoido	hoidoloi	N;PRT;PL
ihandelii	ihandelii	N;NOM;SG
muanpido	muanpiduo	N;PRT;SG
ut’ugu	ut’ugu	N;NOM;SG
hernehine	hernehine	ADJ;NOM;SG
orožansuu	orožansuudu	N;PRT;SG
pezomuilu	pezomuilii	N;PRT;PL
passiivumuodo	passiivumuodooduo	N;PRT;SG
tego	tego	N;NOM;SG
lykystiä	lykystiä	V;NFIN
savihaudu	savihaudoi	N;PRT;PL
kirjutushaireh	kirjutushairehii	N;PRT;PL
käzikirjutus	käzikirjutuksen	N;GEN;SG
vemmel	vembelen	N;GEN;SG
uudinaine	uudinazii	ADJ;PRT;PL
puustu	puustii	N;PRT;PL
helmet	helmien	N;GEN;PL
eländyaloveh	eländyalovehtu	N;PRT;SG
luvva	luou	V;IND;SG;3;POS;PRS
siäsputniekku	siäsputniekkua	N;PRT;SG
tolkuija	tolkuija	V;NFIN
konsonantuyhtymy	konsonantuyhtymän	N;GEN;SG
vara	varoi	N;PRT;PL
lukku	lukkuloi	N;PRT;PL
meččyruadokeskus	meččyruadokeskuksii	N;PRT;PL
čurnie	čurnie	V;NFIN
pahamieline	pahamielizii	ADJ;PRT;PL
burčusavakeh	burčusavakeh	N;NOM;SG
väkkeri	väkkerii	N;PRT;SG
rämizii	rämizijiä	ADJ;PRT;SG
madjuaru	madjuaran	N;GEN;SG
jovenala	jovenala	N;NOM;SG
rungakas	rungakastu	ADJ;PRT;SG
humu	humu	N;NOM;SG
kičkoitellakseh	kičkoittelemmos	V;IND;SG;1;POS;PRS
tervehtyttiä	tervehtytän	V;IND;SG;1;POS;PRS
buhanku	buhankan	N;GEN;SG
kampottu	kampottu	N;NOM;SG
brihastanduaigu	brihastanduaigua	N;PRT;SG
syöndy	syöndän	N;GEN;SG
sylgie	syllen	V;IND;SG;1;POS;PRS
luistelu	luisteluloi	N;PRT;PL
randunuottu	randunuottu	N;NOM;SG
savuta	savuon	V;IND;SG;1;POS;PRS
taba	taba	N;NOM;SG
avata	avuan	V;IND;SG;1;POS;PRS
tervas	tervaksii	N;PRT;PL
riissu	riissu	N;NOM;SG
ruadopäivy	ruadopäivii	N;PRT;PL
virgahtulendu	virgahtulendan	N;GEN;SG
uulahtus	uulahtuksii	N;PRT;PL
ebätoivo	ebätoivon	N;GEN;SG
ahmie	ahmie	V;NFIN
ögistä	ögizen	V;IND;SG;1;POS;PRS
pličkahtuakseh	pličkahtammos	V;IND;SG;1;POS;PRS
peldopyy	peldopyy	N;NOM;SG
lähevys	lähevys	N;NOM;SG
kiändiä	kiännetäh	V;IND;PL;3;POS;PRS
juoksendella	juoksendelou	V;IND;SG;3;POS;PRS
čestie	čestie	V;NFIN
lutikku	lutikku	N;NOM;SG
vähälkehitynnyh	vähälkehitynnytty	ADJ;PRT;SG
perfektu	perfektu	N;NOM;SG
ast’e	ast’e	N;NOM;SG
kebjevys	kebjevyzii	N;PRT;PL
kaikenvalduaju	kaikenvalduaju	ADJ;NOM;SG
punaldua	punaldua	V;NFIN
poltelijaine	poltelijaine	N;NOM;SG
čurčettua	čurčetetah	V;IND;PL;3;POS;PRS
elimistö	elimistölöi	N;PRT;PL
kleimu	kleimoi	N;PRT;PL
matti	matti	N;NOM;SG
kuorittamatoi	kuorittamatoi	ADJ;NOM;SG
vähälnägyi	vähälnägyjän	ADJ;GEN;SG
läimistelläkseh	läimistelehes	V;IND;SG;3;POS;PRS
niittämätöi	niittämättömän	ADJ;GEN;SG
attestacii	attestaciedu	N;PRT;SG
lugukeppizet	lugukeppizii	N;PRT;PL
inversii	inversien	N;GEN;SG
ruavottomusabu	ruavottomusabuabuu	N;PRT;SG
loppumyöndy	loppumyöndy	N;NOM;SG
hyvyöntahtoi	hyvyöntahtoi	ADJ;NOM;SG
iškiekseh	iškehes	V;IND;SG;3;POS;PRS
keroi	keroi	N;NOM;SG
lämmitä	lämmitäh	V;IND;PL;3;POS;PRS
yövardoiččii	yövardoiččijan	N;GEN;SG
armastua	armastan	V;IND;SG;1;POS;PRS
allekirjutus	allekirjutuksii	N;PRT;PL
siemen	siemenii	N;PRT;PL
linduparvi	linduparvi	N;NOM;SG
värilline	värillizen	ADJ;GEN;SG
laudu	laudua	N;PRT;SG
hämmästys	hämmästyksen	N;GEN;SG
policiilaitos	policiilaitos	N;NOM;SG
kuvastus	kuvastuksen	N;GEN;SG
haihattua	haihatetah	V;IND;PL;3;POS;PRS
jäte	jättien	N;GEN;SG
hobjankarvaine	hobjankarvazen	ADJ;GEN;SG
pienendys	pienendyksen	N;GEN;SG
suomelaine	suomelazii	N;PRT;PL
miriekseh	miriekseh	V;NFIN
šarahtuakseh	šarahtuakseh	V;NFIN
fiizielline	fiiziellizen	ADJ;GEN;SG
lagei	lagien	ADJ;GEN;SG
varalähtendyveräi	varalähtendyveriälöi	N;PRT;PL
iänikolonku	iänikolonkoi	N;PRT;PL
närhi	närhii	N;PRT;SG
hyväsydämelližys	hyväsydämelližyzii	N;PRT;PL
burbettua	burbettau	V;IND;SG;3;POS;PRS
siäkeskus	siäkeskus	N;NOM;SG
internacionalizmu	internacionalizmoi	N;PRT;PL
vihmupilvi	vihmupilvilöi	N;PRT;PL
rentgenlaiteh	rentgenlaitehtu	N;PRT;SG
suomelaine	suomelastu	ADJ;PRT;SG
viärendetty	viärendetyn	ADJ;GEN;SG
oravanhändy	oravanhännän	N;GEN;SG
hyvyönluajindu	hyvyönluajindua	N;PRT;SG
vil’l’ukazvokset	vil’l’ukazvoksii	N;PRT;PL
