sikkerhedsvagt	sikkerhedsvagters	N;GEN;INDF;PL
babyboom	babyboomenes	N;NOM;DEF;PL
kontinent	kontinentets	N;NOM;DEF;SG
dørmand	dørmænds	N;GEN;INDF;PL
rugbrød	rugbrøds	N;GEN;INDF;SG
fægter	fægternes	N;NOM;DEF;PL
berømmelse	berømmelser	N;NOM;INDF;PL
pund	pundenes	N;NOM;DEF;PL
kollega	kollegaernes	N;NOM;DEF;PL
schweizer	schweizerens	N;NOM;DEF;SG
honning	honningers	N;GEN;INDF;PL
nationalsang	nationalsangen	N;NOM;DEF;SG
syl	sylen	N;NOM;DEF;SG
sværddrager	sværddragers	N;GEN;INDF;SG
intelligentsia	intelligentsiaens	N;NOM;DEF;SG
tilnavn	tilnavn	N;NOM;INDF;SG
gase	gasens	N;NOM;DEF;SG
estimere	estimeredes	V;IND;PST;PASS
pande	pander	N;NOM;INDF;PL
hjærte	hjærtet	N;NOM;DEF;SG
opmærksomhed	opmærksomheds	N;GEN;INDF;SG
ulykke	ulykkes	N;GEN;INDF;SG
rype	rypes	N;GEN;INDF;SG
løve	løven	N;NOM;DEF;SG
høg	høgenes	N;NOM;DEF;PL
affaldsstof	affaldsstof	N;NOM;INDF;SG
græskar	græskar	N;NOM;INDF;SG
etape	etaper	N;NOM;INDF;PL
ispind	ispinde	N;NOM;INDF;PL
eskadrille	eskadrillerne	N;NOM;DEF;PL
guirlande	guirlandernes	N;NOM;DEF;PL
blodkredsløb	blodkredsløbene	N;NOM;DEF;PL
tånegl	tånegles	N;GEN;INDF;PL
breche	brechernes	N;NOM;DEF;PL
bussemand	bussemændene	N;NOM;DEF;PL
ildkugle	ildkugler	N;NOM;INDF;PL
nørd	nørd	N;NOM;INDF;SG
cellevæg	cellevæggen	N;NOM;DEF;SG
chok	chok	N;NOM;INDF;PL
gennemsnit	gennemsnittenes	N;NOM;DEF;PL
guitar	guitar	N;NOM;INDF;SG
liv	liv	N;NOM;INDF;PL
glimt	glimts	N;GEN;INDF;PL
opmærksomhed	opmærksomhed	N;NOM;INDF;SG
kraveben	kravebenets	N;NOM;DEF;SG
chauffør	chaufføren	N;NOM;DEF;SG
krystallisere	krystalliserende	V.PTCP;PRS;ACT
kerte	kerten	N;NOM;DEF;SG
fajance	fajancers	N;GEN;INDF;PL
brunette	brunetter	N;NOM;INDF;PL
honning	honnings	N;GEN;INDF;SG
mål	målets	N;NOM;DEF;SG
dørmand	dørmands	N;GEN;INDF;SG
montere	monteredes	V;IND;PST;PASS
karisma	karismaens	N;NOM;DEF;SG
lærerinde	lærerindernes	N;NOM;DEF;PL
lænestol	lænestols	N;GEN;INDF;SG
ildkugle	ildkugle	N;NOM;INDF;SG
brydningsindeks	brydningsindekser	N;NOM;INDF;PL
vinliste	vinlistes	N;GEN;INDF;SG
centralnervesystem	centralnervesystemernes	N;NOM;DEF;PL
abrikostræ	abrikostræernes	N;NOM;DEF;PL
strø	strøer	N;NOM;INDF;PL
grapefrugt	grapefrugtens	N;NOM;DEF;SG
spætte	spætternes	N;NOM;DEF;PL
midnat	midnats	N;GEN;INDF;SG
lort	lorten	N;NOM;DEF;SG
burgerbar	burgerbar	N;NOM;INDF;SG
ceremoni	ceremoni	N;NOM;INDF;SG
flanke	flanker	N;NOM;INDF;PL
hospital	hospitalers	N;GEN;INDF;PL
mester	mesters	N;GEN;INDF;SG
klassiker	klassikernes	N;NOM;DEF;PL
ælling	ællingen	N;NOM;DEF;SG
dørmåtte	dørmåtterne	N;NOM;DEF;PL
bølgelængde	bølgelængder	N;NOM;INDF;PL
pige	pigernes	N;NOM;DEF;PL
konkurrence	konkurrencen	N;NOM;DEF;SG
flanere	flaneredes	V;IND;PST;PASS
mælkebøtte	mælkebøtters	N;GEN;INDF;PL
nisse	nissers	N;GEN;INDF;PL
od	oddes	N;GEN;INDF;PL
eksistens	eksistenserne	N;NOM;DEF;PL
kanapé	kanapéen	N;NOM;DEF;SG
afstemning	afstemningerne	N;NOM;DEF;PL
skræl	skrællens	N;NOM;DEF;SG
monark	monarkens	N;NOM;DEF;SG
gyngestol	gyngestole	N;NOM;INDF;PL
freske	fresken	N;NOM;DEF;SG
dompap	dompappers	N;GEN;INDF;PL
brystvorte	brystvorter	N;NOM;INDF;PL
morgenmand	morgenmand	N;NOM;INDF;SG
højtaler	højtalerens	N;NOM;DEF;SG
sovs	sovsene	N;NOM;DEF;PL
allokering	allokeringers	N;GEN;INDF;PL
styr	styr	N;NOM;INDF;PL
tøjte	tøjtens	N;NOM;DEF;SG
fæ	fæenes	N;NOM;DEF;PL
rig	riggen	N;NOM;DEF;SG
ansøger	ansøgeren	N;NOM;DEF;SG
dokument	dokumentet	N;NOM;DEF;SG
etymologi	etymologierne	N;NOM;DEF;PL
tydeliggørelse	tydeliggørelsers	N;GEN;INDF;PL
præst	præsters	N;GEN;INDF;PL
besked	beskedernes	N;NOM;DEF;PL
pegefinger	pegefingers	N;GEN;INDF;SG
kvart	kvarter	N;NOM;INDF;PL
politiker	politikers	N;GEN;INDF;SG
wc	wc's	N;GEN;INDF;SG
pandekage	pandekagerne	N;NOM;DEF;PL
brik	brikkers	N;GEN;INDF;PL
knob	knobs	N;GEN;INDF;SG
føderation	føderationen	N;NOM;DEF;SG
karisma	karismaernes	N;NOM;DEF;PL
sinecure	sinecurerne	N;NOM;DEF;PL
udsagnsled	udsagnsled	N;NOM;INDF;PL
ultralyd	ultralyds	N;GEN;INDF;SG
flue	fluens	N;NOM;DEF;SG
fjæs	fjæs	N;NOM;INDF;SG
kører	kørerens	N;NOM;DEF;SG
grundlov	grundlove	N;NOM;INDF;PL
skræddermester	skræddermestrene	N;NOM;DEF;PL
kanapé	kanapéerne	N;NOM;DEF;PL
mø	møens	N;NOM;DEF;SG
len	len	N;NOM;INDF;SG
standard	standarder	N;NOM;INDF;PL
stormfugl	stormfuglen	N;NOM;DEF;SG
skueproces	skueproces	N;NOM;INDF;SG
bøf	bøfferne	N;NOM;DEF;PL
violin	violinernes	N;NOM;DEF;PL
buket	bukets	N;GEN;INDF;SG
eksemplar	eksemplarets	N;NOM;DEF;SG
sudaner	sudanere	N;NOM;INDF;PL
harekilling	harekillingernes	N;NOM;DEF;PL
hestesko	hestesko	N;NOM;INDF;PL
år	år	N;NOM;INDF;SG
jordnød	jordnødderne	N;NOM;DEF;PL
pentagram	pentagrammerne	N;NOM;DEF;PL
drøne	drøne	V;NFIN;ACT
helligdag	helligdagene	N;NOM;DEF;PL
hudfarve	hudfarven	N;NOM;DEF;SG
vindmølle	vindmøllens	N;NOM;DEF;SG
retfærdighed	retfærdighed	N;NOM;INDF;SG
hjul	hjuls	N;GEN;INDF;SG
kompagnon	kompagnonerne	N;NOM;DEF;PL
frue	frues	N;GEN;INDF;SG
skjald	skjalds	N;GEN;INDF;SG
knob	knobenes	N;NOM;DEF;PL
tydeliggørelse	tydeliggørelserne	N;NOM;DEF;PL
begyndelse	begyndelsen	N;NOM;DEF;SG
akkumulator	akkumulator	N;NOM;INDF;SG
tyveri	tyverier	N;NOM;INDF;PL
afsnit	afsnittenes	N;NOM;DEF;PL
brækjern	brækjernenes	N;NOM;DEF;PL
gene	geners	N;GEN;INDF;PL
svastika	svastika	N;NOM;INDF;SG
hjernestamme	hjernestamme	N;NOM;INDF;SG
rejecocktail	rejecocktailens	N;NOM;DEF;SG
toilet	toiletter	N;NOM;INDF;PL
grapefrugt	grapefrugterne	N;NOM;DEF;PL
veranda	verandaerne	N;NOM;DEF;PL
fodring	fodringers	N;GEN;INDF;PL
grin	grin	N;NOM;INDF;PL
guldsmed	guldsmedenes	N;NOM;DEF;PL
tolk	tolken	N;NOM;DEF;SG
ispind	ispindene	N;NOM;DEF;PL
birkes	birkes'	N;GEN;INDF;SG
bov	bovens	N;NOM;DEF;SG
allike	allikens	N;NOM;DEF;SG
knar	knars	N;GEN;INDF;SG
skurk	skurks	N;GEN;INDF;SG
glansbillede	glansbilledets	N;NOM;DEF;SG
barbering	barberinger	N;NOM;INDF;PL
flaskehals	flaskehalsens	N;NOM;DEF;SG
ornitolog	ornitologens	N;NOM;DEF;SG
hjerne	hjernen	N;NOM;DEF;SG
hals	halsens	N;NOM;DEF;SG
erobringskrig	erobringskrigen	N;NOM;DEF;SG
paryk	parykkerne	N;NOM;DEF;PL
pokeransigt	pokeransigts	N;GEN;INDF;SG
filosof	filosoffernes	N;NOM;DEF;PL
datid	datid	N;NOM;INDF;SG
måne	månen	N;NOM;DEF;SG
fængsle	fængsles	V;IND;PRS;PASS
strube	struberne	N;NOM;DEF;PL
tidsforlængelse	tidsforlængelser	N;NOM;INDF;PL
debut	debut	N;NOM;INDF;SG
alkymist	alkymisterne	N;NOM;DEF;PL
koncentrat	koncentratet	N;NOM;DEF;SG
sammenskrivning	sammenskrivning	N;NOM;INDF;SG
dørmåtte	dørmåtten	N;NOM;DEF;SG
tryne	trynens	N;NOM;DEF;SG
smørrebrød	smørrebrød	N;NOM;INDF;PL
egetræ	egetræernes	N;NOM;DEF;PL
tradition	traditions	N;GEN;INDF;SG
bolværk	bolværkerne	N;NOM;DEF;PL
soldat	soldat	N;NOM;INDF;SG
horkarl	horkarlene	N;NOM;DEF;PL
abrikostræ	abrikostræerne	N;NOM;DEF;PL
flyttemand	flyttemandens	N;NOM;DEF;SG
slutspurt	slutspurterne	N;NOM;DEF;PL
kompagnon	kompagnons	N;GEN;INDF;SG
gasmaske	gasmasken	N;NOM;DEF;SG
delegat	delegaters	N;GEN;INDF;PL
cigarettænder	cigarettænderne	N;NOM;DEF;PL
mær	mærenes	N;NOM;DEF;PL
sangfugl	sangfugles	N;GEN;INDF;PL
babyface	babyfaces	N;GEN;INDF;SG
drøbel	drøbel	N;NOM;INDF;SG
e-mail-adresse	e-mail-adressen	N;NOM;DEF;SG
babyalarm	babyalarmerne	N;NOM;DEF;PL
mineralogi	mineralogiers	N;GEN;INDF;PL
polyeder	polyedrene	N;NOM;DEF;PL
ildsjæl	ildsjæls	N;GEN;INDF;SG
hyppighed	hyppigheders	N;GEN;INDF;PL
kvæld	kvælds	N;GEN;INDF;SG
violin	violiner	N;NOM;INDF;PL
burgerbar	burgerbarens	N;NOM;DEF;SG
orgie	orgiers	N;GEN;INDF;PL
højtaler	højtalernes	N;NOM;DEF;PL
lejrskole	lejrskolen	N;NOM;DEF;SG
dompap	dompapper	N;NOM;INDF;PL
gnom	gnomen	N;NOM;DEF;SG
geled	geledder	N;NOM;INDF;PL
trin	trin	N;NOM;INDF;PL
sætning	sætningen	N;NOM;DEF;SG
ornitolog	ornitologernes	N;NOM;DEF;PL
majonæse	majonæsernes	N;NOM;DEF;PL
farmand	farmændenes	N;NOM;DEF;PL
folkedragt	folkedragten	N;NOM;DEF;SG
muslim	muslimerne	N;NOM;DEF;PL
pige	piges	N;GEN;INDF;SG
tromme	trommerne	N;NOM;DEF;PL
næb	næb	N;NOM;INDF;PL
ørering	øreringenes	N;NOM;DEF;PL
sydkyst	sydkyster	N;NOM;INDF;PL
grundlag	grundlag	N;NOM;INDF;SG
spark	sparks	N;GEN;INDF;PL
terapeut	terapeuten	N;NOM;DEF;SG
botanik	botanikker	N;NOM;INDF;PL
republik	republikkerne	N;NOM;DEF;PL
urinal	urinalerne	N;NOM;DEF;PL
vektorprodukt	vektorprodukterne	N;NOM;DEF;PL
askebæger	askebægers	N;GEN;INDF;SG
snestorm	snestormens	N;NOM;DEF;SG
synapse	synapsens	N;NOM;DEF;SG
låge	lågen	N;NOM;DEF;SG
pude	pudens	N;NOM;DEF;SG
citron	citronernes	N;NOM;DEF;PL
boring	boringers	N;GEN;INDF;PL
pizza	pizzaernes	N;NOM;DEF;PL
diftong	diftongen	N;NOM;DEF;SG
helikopter	helikoptere	N;NOM;INDF;PL
kaktus	kaktusser	N;NOM;INDF;PL
besked	beskederne	N;NOM;DEF;PL
tånegl	tåneglene	N;NOM;DEF;PL
monopol	monopoler	N;NOM;INDF;PL
trafikprop	trafikpropperne	N;NOM;DEF;PL
babyboom	babyboomet	N;NOM;DEF;SG
trin	trinenes	N;NOM;DEF;PL
immigration	immigrationer	N;NOM;INDF;PL
blindtarm	blindtarmene	N;NOM;DEF;PL
barnevogn	barnevogn	N;NOM;INDF;SG
advarsel	advarslers	N;GEN;INDF;PL
kamel	kamelernes	N;NOM;DEF;PL
kirkeklokke	kirkeklokkernes	N;NOM;DEF;PL
kvalitet	kvaliteter	N;NOM;INDF;PL
førnutid	førnutiders	N;GEN;INDF;PL
behov	behov	N;NOM;INDF;SG
tagetage	tage	N;NOM;DEF;SG
mekaniker	mekanikerne	N;NOM;DEF;PL
skuespillerinde	skuespillerinden	N;NOM;DEF;SG
marsvin	marsvinet	N;NOM;DEF;SG
argumentere	argumenter	V;IMP;ACT
controller	controllerens	N;NOM;DEF;SG
syge	sygerne	N;NOM;DEF;PL
tykhornsfår	tykhornsfårene	N;NOM;DEF;PL
næringsstof	næringsstoffers	N;GEN;INDF;PL
svend	svendes	N;GEN;INDF;PL
rokere	rokerer	V;IND;PRS;ACT
rappenskralde	rappenskralder	N;NOM;INDF;PL
strube	struber	N;NOM;INDF;PL
anæstesi	anæstesis	N;GEN;INDF;SG
nisse	nissen	N;NOM;DEF;SG
apotek	apotek	N;NOM;INDF;SG
kommode	kommodes	N;GEN;INDF;SG
sonet	sonet	N;NOM;INDF;SG
ressource	ressourcers	N;GEN;INDF;PL
retfærdighed	retfærdighedens	N;NOM;DEF;SG
hængelås	hængelåsen	N;NOM;DEF;SG
amager	amageren	N;NOM;DEF;SG
roma	romas	N;GEN;INDF;SG
tekniker	teknikere	N;NOM;INDF;PL
cigaretstump	cigaretstumperne	N;NOM;DEF;PL
periode	periode	N;NOM;INDF;SG
frikadelle	frikadeller	N;NOM;INDF;PL
parodi	parodi	N;NOM;INDF;SG
majonæse	majonæses	N;GEN;INDF;SG
konsulat	konsulats	N;GEN;INDF;SG
skueproces	skueprocesserne	N;NOM;DEF;PL
tydeliggørelse	tydeliggørelses	N;GEN;INDF;SG
jag	jagenes	N;NOM;DEF;PL
behov	behov	N;NOM;INDF;PL
hjørne	hjørners	N;GEN;INDF;PL
vinkelhalveringslinje	vinkelhalveringslinjerne	N;NOM;DEF;PL
hypnose	hypnosers	N;GEN;INDF;PL
tavle	tavle	N;NOM;INDF;SG
pedel	pedellens	N;NOM;DEF;SG
hydrolog	hydrologernes	N;NOM;DEF;PL
satse	sats	V;IMP;ACT
krokodille	krokodillers	N;GEN;INDF;PL
jorde	jordedes	V;IND;PST;PASS
vabel	vabler	N;NOM;INDF;PL
kontaktinformation	kontaktinformationen	N;NOM;DEF;SG
tepotte	tepottes	N;GEN;INDF;SG
vektorprodukt	vektorprodukts	N;GEN;INDF;SG
kultur	kulturs	N;GEN;INDF;SG
hår	hårs	N;GEN;INDF;SG
håndgemæng	håndgemængenes	N;NOM;DEF;PL
lilje	liljernes	N;NOM;DEF;PL
veninde	venindernes	N;NOM;DEF;PL
TV-program	TV-programmer	N;NOM;INDF;PL
vindbøjtel	vindbøjtlen	N;NOM;DEF;SG
pengeautomat	pengeautomaterne	N;NOM;DEF;PL
fægter	fægterens	N;NOM;DEF;SG
sok	sokker	N;NOM;INDF;PL
kobber	kobberne	N;NOM;DEF;PL
kugleramme	kuglerammers	N;GEN;INDF;PL
kilder	kilderne	N;NOM;DEF;PL
vaskeklud	vaskekludes	N;GEN;INDF;PL
jurist	juristers	N;GEN;INDF;PL
henvisning	henvisningers	N;GEN;INDF;PL
kondom	kondom	N;NOM;INDF;SG
regnskov	regnskovens	N;NOM;DEF;SG
istid	istiden	N;NOM;DEF;SG
spiserør	spiserørs	N;GEN;INDF;PL
løsen	løsen	N;NOM;INDF;SG
æbletærte	æbletærterne	N;NOM;DEF;PL
idiosynkrasi	idiosynkrasierne	N;NOM;DEF;PL
strø	strøen	N;NOM;DEF;SG
fiske	fiskedes	V;IND;PST;PASS
hensynsled	hensynsled	N;NOM;INDF;PL
hilsen	hilseners	N;GEN;INDF;PL
gymnasium	gymnasiets	N;NOM;DEF;SG
marmelade	marmeladernes	N;NOM;DEF;PL
medalje	medaljes	N;GEN;INDF;SG
ridt	ridt	N;NOM;INDF;PL
rødvin	rødvinens	N;NOM;DEF;SG
brillant	brillanternes	N;NOM;DEF;PL
amatør	amatørs	N;GEN;INDF;SG
leksikon	leksikonernes	N;NOM;DEF;PL
autopsi	autopsiernes	N;NOM;DEF;PL
amagerkaner	amagerkaneres	N;GEN;INDF;PL
hammer	hammers	N;GEN;INDF;SG
datid	datider	N;NOM;INDF;PL
bamse	bamsens	N;NOM;DEF;SG
gennembrud	gennembruds	N;GEN;INDF;PL
juvel	juvelens	N;NOM;DEF;SG
browser	browsere	N;NOM;INDF;PL
element	elementer	N;NOM;INDF;PL
blåhval	blåhvaler	N;NOM;INDF;PL
muslim	muslimernes	N;NOM;DEF;PL
nexøbo	nexøboernes	N;NOM;DEF;PL
tennisspiller	tennisspilleren	N;NOM;DEF;SG
lønforhøjelse	lønforhøjelser	N;NOM;INDF;PL
sinecure	sinecurers	N;GEN;INDF;PL
boysenbær	boysenbærret	N;NOM;DEF;SG
avantgarde	avantgarden	N;NOM;DEF;SG
tekniker	teknikerens	N;NOM;DEF;SG
bille	bille	N;NOM;INDF;SG
folkedragt	folkedragters	N;GEN;INDF;PL
certifikat	certifikaterne	N;NOM;DEF;PL
milt	milten	N;NOM;DEF;SG
krage	krager	N;NOM;INDF;PL
starter	starter	N;NOM;INDF;SG
bavian	bavians	N;GEN;INDF;SG
sætning	sætningerne	N;NOM;DEF;PL
medicin	medicinen	N;NOM;DEF;SG
lampeskærm	lampeskærmene	N;NOM;DEF;PL
kolonialforretning	kolonialforretningen	N;NOM;DEF;SG
pizza	pizza	N;NOM;INDF;SG
grundlovsdag	grundlovsdag	N;NOM;INDF;SG
møller	møllere	N;NOM;INDF;PL
tv-program	tv-programmerne	N;NOM;DEF;PL
kar	kars	N;GEN;INDF;PL
pandekage	pandekager	N;NOM;INDF;PL
kardiogram	kardiogrammernes	N;NOM;DEF;PL
englærke	englærkernes	N;NOM;DEF;PL
sejl	sejls	N;GEN;INDF;PL
arkitekt	arkitektens	N;NOM;DEF;SG
bambus	bambussers	N;GEN;INDF;PL
piberenser	piberenserens	N;NOM;DEF;SG
refræn	refræn	N;NOM;INDF;SG
terapeut	terapeuterne	N;NOM;DEF;PL
kejserinde	kejserinden	N;NOM;DEF;SG
cirkel	cirklens	N;NOM;DEF;SG
befolkning	befolkningen	N;NOM;DEF;SG
tøjte	tøjtes	N;GEN;INDF;SG
orgie	orgiet	N;NOM;DEF;SG
himmel	himlenes	N;NOM;DEF;PL
magasin	magasinernes	N;NOM;DEF;PL
klaviatur	klaviatur	N;NOM;INDF;SG
ædelgas	ædelgassen	N;NOM;DEF;SG
oplysning	oplysninger	N;NOM;INDF;PL
pedel	pedellen	N;NOM;DEF;SG
agnostiker	agnostiker	N;NOM;INDF;SG
syge	sygen	N;NOM;DEF;SG
medley	medleyet	N;NOM;DEF;SG
metier	metierens	N;NOM;DEF;SG
muskel	musklers	N;GEN;INDF;PL
fordampningsvarme	fordampningsvarmer	N;NOM;INDF;PL
kusk	kuskes	N;GEN;INDF;PL
lund	lundene	N;NOM;DEF;PL
oxidere	oxideret	V.PTCP;PST;PASS
brunsviger	brunsvigerenes	N;NOM;DEF;PL
hovedpulsåre	hovedpulsåre	N;NOM;INDF;SG
neutron	neutron	N;NOM;INDF;SG
konservatorie	konservatoriernes	N;NOM;DEF;PL
evighed	evigheds	N;GEN;INDF;SG
kedel	kedler	N;NOM;INDF;PL
cyste	cyste	N;NOM;INDF;SG
påfugl	påfuglen	N;NOM;DEF;SG
basar	basarernes	N;NOM;DEF;PL
peanut	peanuttenes	N;NOM;DEF;PL
kanapé	kanapé	N;NOM;INDF;SG
idiosynkrasi	idiosynkrasier	N;NOM;INDF;PL
gardin	gardiners	N;GEN;INDF;PL
tyveri	tyveriets	N;NOM;DEF;SG
hingst	hingsten	N;NOM;DEF;SG
detalje	detaljens	N;NOM;DEF;SG
magasin	magasin	N;NOM;INDF;SG
skumbad	skumbad	N;NOM;INDF;SG
håb	håbets	N;NOM;DEF;SG
kvalitet	kvalitet	N;NOM;INDF;SG
imitere	imiteret	V.PTCP;PST;PASS
ukrainer	ukrainernes	N;NOM;DEF;PL
morgenmand	morgenmanden	N;NOM;DEF;SG
buffer	bufferes	N;GEN;INDF;PL
tv-program	tv-programmer	N;NOM;INDF;PL
helgen	helgeners	N;GEN;INDF;PL
frisør	frisøren	N;NOM;DEF;SG
autoritet	autoriteters	N;GEN;INDF;PL
javaneser	javanesere	N;NOM;INDF;PL
sæbeopera	sæbeoperaens	N;NOM;DEF;SG
trafikprop	trafikprop	N;NOM;INDF;SG
egetræ	egetræs	N;GEN;INDF;SG
zucchini	zucchinis	N;GEN;INDF;SG
beryl	beryller	N;NOM;INDF;PL
formelenhed	formelenheder	N;NOM;INDF;PL
køkkenvask	køkkenvaskes	N;GEN;INDF;PL
fjord	fjorden	N;NOM;DEF;SG
makrel	makrellerne	N;NOM;DEF;PL
person	personers	N;GEN;INDF;PL
varulv	varulvene	N;NOM;DEF;PL
diamant	diamanternes	N;NOM;DEF;PL
stær	stære	N;NOM;INDF;PL
substantiv	substantivets	N;NOM;DEF;SG
romani	romaniens	N;NOM;DEF;SG
malkepige	malkepigerne	N;NOM;DEF;PL
slagsmål	slagsmålenes	N;NOM;DEF;PL
himmel	himles	N;GEN;INDF;PL
signere	signeret	V.PTCP;PST;PASS
frokost	frokosts	N;GEN;INDF;SG
trug	trugs	N;GEN;INDF;PL
gnom	gnomens	N;NOM;DEF;SG
ansøgning	ansøgningen	N;NOM;DEF;SG
brændsel	brændsler	N;NOM;INDF;PL
tepotte	tepotte	N;NOM;INDF;SG
elevator	elevatorer	N;NOM;INDF;PL
nattergal	nattergalenes	N;NOM;DEF;PL
opmærksomhed	opmærksomhedens	N;NOM;DEF;SG
klassifikation	klassifikationer	N;NOM;INDF;PL
medicin	medicinens	N;NOM;DEF;SG
ringfinger	ringfingre	N;NOM;INDF;PL
pentagon	pentagoners	N;GEN;INDF;PL
viskestykke	viskestykkernes	N;NOM;DEF;PL
hovedserie	hovedseries	N;GEN;INDF;SG
pokeransigt	pokeransigtets	N;NOM;DEF;SG
bold	bold	N;NOM;INDF;SG
mallemuk	mallemukkernes	N;NOM;DEF;PL
stormfugl	stormfugls	N;GEN;INDF;SG
avance	avancerne	N;NOM;DEF;PL
diskutere	diskuterende	V.PTCP;PRS;ACT
guvernør	guvernørers	N;GEN;INDF;PL
hammer	hammernehamrene	N;NOM;DEF;PL
vams	vamses	N;GEN;INDF;PL
hærværksmand	hærværksmands	N;GEN;INDF;SG
resistor	resistorernes	N;NOM;DEF;PL
deviere	deviere	V;NFIN;ACT
motivere	motiveredes	V;IND;PST;PASS
knæ	knæs	N;GEN;INDF;PL
menu	menuernes	N;NOM;DEF;PL
ugle	uglers	N;GEN;INDF;PL
manke	manke	N;NOM;INDF;SG
smørrebrød	smørrebrødene	N;NOM;DEF;PL
karl	karl	N;NOM;INDF;SG
søgeresultat	søgeresultatet	N;NOM;DEF;SG
præfiks	præfiksernes	N;NOM;DEF;PL
pistol	pistolernes	N;NOM;DEF;PL
dørmåtte	dørmåttes	N;GEN;INDF;SG
spiserør	spiserøret	N;NOM;DEF;SG
palmesøndag	palmesøndagenes	N;NOM;DEF;PL
penalhus	penalhusenes	N;NOM;DEF;PL
kasket	kasket	N;NOM;INDF;SG
fægtning	fægtning	N;NOM;INDF;SG
hensynsled	hensynsleds	N;GEN;INDF;SG
ræv	rævene	N;NOM;DEF;PL
visum	visummets	N;NOM;DEF;SG
ræv	rævens	N;NOM;DEF;SG
palæstinenser	palæstinensers	N;GEN;INDF;SG
machomand	machomændene	N;NOM;DEF;PL
leverpostej	leverpostejers	N;GEN;INDF;PL
ravn	ravnene	N;NOM;DEF;PL
far	far	N;NOM;INDF;SG
bugspytkirtel	bugspytkirtlers	N;GEN;INDF;PL
fodbold	fodboldene	N;NOM;DEF;PL
bronze	bronzers	N;GEN;INDF;PL
løvinde	løvinder	N;NOM;INDF;PL
honning	honningens	N;NOM;DEF;SG
rygrad	rygradens	N;NOM;DEF;SG
vegetar	vegetarers	N;GEN;INDF;PL
fedtsyl	fedtsylen	N;NOM;DEF;SG
campingvogn	campingvogn	N;NOM;INDF;SG
mineralogi	mineralogi	N;NOM;INDF;SG
kupon	kuponerne	N;NOM;DEF;PL
symbol	symbolers	N;GEN;INDF;PL
vortemælk	vortemælk	N;NOM;INDF;PL
kultur	kulturernes	N;NOM;DEF;PL
standard	standarders	N;GEN;INDF;PL
testamente	testamenters	N;GEN;INDF;PL
dige	digernes	N;NOM;DEF;PL
fodspor	fodspor	N;NOM;INDF;PL
paryk	paryk	N;NOM;INDF;SG
øreflip	øreflippers	N;GEN;INDF;PL
ordre	ordrerne	N;NOM;DEF;PL
albumin	albuminet	N;NOM;DEF;SG
ildkugle	ildkuglens	N;NOM;DEF;SG
krave	kraver	N;NOM;INDF;PL
rødvin	rødvins	N;GEN;INDF;SG
koncert	koncerten	N;NOM;DEF;SG
stræde	stræde	N;NOM;INDF;SG
slagskib	slagskibs	N;GEN;INDF;SG
vektorprodukt	vektorproduktet	N;NOM;DEF;SG
formue	formue	N;NOM;INDF;SG
skonnert	skonnertens	N;NOM;DEF;SG
trafikprop	trafikprops	N;GEN;INDF;SG
palads	paladsets	N;NOM;DEF;SG
brise	brises	N;GEN;INDF;SG
afbildning	afbildningen	N;NOM;DEF;SG
tebrev	tebrevs	N;GEN;INDF;SG
hvalros	hvalrossen	N;NOM;DEF;SG
intelligentsia	intelligentsiaerne	N;NOM;DEF;PL
miste	mistende	V.PTCP;PRS;ACT
stormfugl	stormfugle	N;NOM;INDF;PL
anagram	anagrammer	N;NOM;INDF;PL
facade	facade	N;NOM;INDF;SG
hjord	hjorders	N;GEN;INDF;PL
riffel	riflensriffelens	N;NOM;DEF;SG
periode	perioders	N;GEN;INDF;PL
babysæl	babysælen	N;NOM;DEF;SG
brændsel	brændslers	N;GEN;INDF;PL
monsun	monsunens	N;NOM;DEF;SG
synonym	synonymernes	N;NOM;DEF;PL
addere	adderet	V.PTCP;PST;PASS
entrecote	entrecote	N;NOM;INDF;SG
hexaeder	hexaedre	N;NOM;INDF;PL
revy	revyers	N;GEN;INDF;PL
ægtemand	ægtemandens	N;NOM;DEF;SG
karakteristik	karakteristik	N;NOM;INDF;SG
akt	akterne	N;NOM;DEF;PL
konservatorie	konservatorierne	N;NOM;DEF;PL
tændstikæske	tændstikæskers	N;GEN;INDF;PL
blodplade	blodpladens	N;NOM;DEF;SG
gene	gener	N;NOM;INDF;PL
kendeord	kendeordet	N;NOM;DEF;SG
globe	globe	N;NOM;INDF;SG
giro	giro	N;NOM;INDF;SG
færing	færinger	N;NOM;INDF;PL
uddannelse	uddannelser	N;NOM;INDF;PL
ælling	ællingers	N;GEN;INDF;PL
kvæld	kvælders	N;GEN;INDF;PL
kryds	krydsets	N;NOM;DEF;SG
pæderast	pæderasternes	N;NOM;DEF;PL
bøf	bøffernes	N;NOM;DEF;PL
veninde	venindens	N;NOM;DEF;SG
juletræ	juletræ	N;NOM;INDF;SG
chilener	chileneren	N;NOM;DEF;SG
kejsersnit	kejsersnit	N;NOM;INDF;SG
film	films	N;GEN;INDF;PL
årsdag	årsdage	N;NOM;INDF;PL
rabarber	rabarberens	N;NOM;DEF;SG
løkke	løkkes	N;GEN;INDF;SG
panere	paneret	V.PTCP;PST;PASS
kaffekande	kaffekandens	N;NOM;DEF;SG
karantæne	karantæne	N;NOM;INDF;SG
malle	mallens	N;NOM;DEF;SG
torsk	torskens	N;NOM;DEF;SG
udmatning	udmatningen	N;NOM;DEF;SG
kappe	kappen	N;NOM;DEF;SG
referendum	referendums	N;GEN;INDF;SG
republik	republiks	N;GEN;INDF;SG
strygebræt	strygebrættets	N;NOM;DEF;SG
sætning	sætningens	N;NOM;DEF;SG
snuble	snublende	V.PTCP;PRS;ACT
ambra	ambraernes	N;NOM;DEF;PL
mynde	mynderne	N;NOM;DEF;PL
nål	nålen	N;NOM;DEF;SG
autodidakt	autodidakternes	N;NOM;DEF;PL
skrig	skrigene	N;NOM;DEF;PL
apotek	apoteks	N;GEN;INDF;SG
æra	æras	N;GEN;INDF;SG
rytter	rytteren	N;NOM;DEF;SG
fædreland	fædreland	N;NOM;INDF;SG
diskotek	diskotekers	N;GEN;INDF;PL
musikartikel	musikartiklers	N;GEN;INDF;PL
tenor	tenorens	N;NOM;DEF;SG
pude	pude	N;NOM;INDF;SG
ambolt	ambolten	N;NOM;DEF;SG
kører	kørers	N;GEN;INDF;SG
vom	vommens	N;NOM;DEF;SG
himmel	himlene	N;NOM;DEF;PL
skiderik	skideriks	N;GEN;INDF;SG
målmand	målmændene	N;NOM;DEF;PL
ordre	ordrens	N;NOM;DEF;SG
newzealænder	newzealænderes	N;GEN;INDF;PL
istap	istapperne	N;NOM;DEF;PL
klient	klienters	N;GEN;INDF;PL
drager	dragerens	N;NOM;DEF;SG
inuit	inuit	N;NOM;INDF;SG
bov	bove	N;NOM;INDF;PL
troldmand	troldmand	N;NOM;INDF;SG
hæl	hæl	N;NOM;INDF;SG
lærerinde	lærerindens	N;NOM;DEF;SG
overraskelse	overraskelserne	N;NOM;DEF;PL
kunstgalleri	kunstgalleri	N;NOM;INDF;SG
materiale	materialet	N;NOM;DEF;SG
aramæer	aramæeres	N;GEN;INDF;PL
princip	princippets	N;NOM;DEF;SG
mistelten	misteltenens	N;NOM;DEF;SG
søjle	søjlers	N;GEN;INDF;PL
millimeter	millimeternes	N;NOM;DEF;PL
skæg	skæggenes	N;NOM;DEF;PL
chimpanse	chimpansers	N;GEN;INDF;PL
enhed	enheder	N;NOM;INDF;PL
røn	rønnerøn	N;NOM;INDF;PL
fløjt	fløjtet	N;NOM;DEF;SG
time	timer	N;NOM;INDF;PL
fjord	fjordens	N;NOM;DEF;SG
napoleonshat	napoleonshat	N;NOM;INDF;SG
hjernestamme	hjernestammers	N;GEN;INDF;PL
golfer	golfers	N;GEN;INDF;SG
formue	formues	N;GEN;INDF;SG
filetere	fileterende	V.PTCP;PRS;ACT
skuffe	skuffer	N;NOM;INDF;PL
ildsjæl	ildsjæles	N;GEN;INDF;PL
autodidakt	autodidakters	N;GEN;INDF;PL
faster	fastres	N;GEN;INDF;PL
chikane	chikane	N;NOM;INDF;SG
marsvin	marsvinene	N;NOM;DEF;PL
biskop	biskoppen	N;NOM;DEF;SG
fjols	fjolser	N;NOM;INDF;PL
vandrehistorie	vandrehistorier	N;NOM;INDF;PL
udstyre	udstyres	V;IND;PRS;PASS
bøhmand	bøhmands	N;GEN;INDF;SG
revolution	revolutioner	N;NOM;INDF;PL
sydvest	sydvestene	N;NOM;DEF;PL
helgen	helgenerne	N;NOM;DEF;PL
udgang	udgangene	N;NOM;DEF;PL
barnevogn	barnevogns	N;GEN;INDF;SG
åre	årernes	N;NOM;DEF;PL
knagebræt	knagebrætterne	N;NOM;DEF;PL
kvantificere	kvantificerer	V;IND;PRS;ACT
kanariefugl	kanariefugle	N;NOM;INDF;PL
husbåd	husbådenes	N;NOM;DEF;PL
næsehorn	næsehornene	N;NOM;DEF;PL
ask	asken	N;NOM;DEF;SG
substituere	substitueret	V.PTCP;PST;PASS
terapeut	terapeuters	N;GEN;INDF;PL
palmesøndag	palmesøndags	N;GEN;INDF;SG
kolesterol	kolesterolerne	N;NOM;DEF;PL
fejl	fejlens	N;NOM;DEF;SG
las	lasen	N;NOM;DEF;SG
freske	fresker	N;NOM;INDF;PL
kommentar	kommentarer	N;NOM;INDF;PL
centralnervesystem	centralnervesystemets	N;NOM;DEF;SG
stavkirke	stavkirkes	N;GEN;INDF;SG
panda	pandaer	N;NOM;INDF;PL
hængelås	hængelåses	N;GEN;INDF;PL
mafioso	mafiosoen	N;NOM;DEF;SG
konflikt	konflikternes	N;NOM;DEF;PL
dåne	dånet	V.PTCP;PST;PASS
tur	turenes	N;NOM;DEF;PL
løsen	løsenets	N;NOM;DEF;SG
kroge	kroget	V.PTCP;PST;PASS
oliven	olivenenes	N;NOM;DEF;PL
guvernør	guvernørernes	N;NOM;DEF;PL
melodigrandprix	melodigrandprixernes	N;NOM;DEF;PL
motorvej	motorvejes	N;GEN;INDF;PL
politibetjent	politibetjent	N;NOM;INDF;SG
kineser	kinesere	N;NOM;INDF;PL
interjektion	interjektionens	N;NOM;DEF;SG
isbryder	isbryder	N;NOM;INDF;SG
tørretumbler	tørretumblerne	N;NOM;DEF;PL
jorde	jord	V;IMP;ACT
kæp	kæps	N;GEN;INDF;SG
produkt	produktets	N;NOM;DEF;SG
kultfilm	kultfilm	N;NOM;INDF;SG
stør	størene	N;NOM;DEF;PL
palmeolie	palmeoliers	N;GEN;INDF;PL
golden retriever	golden retriever	N;NOM;INDF;SG
ildkugle	ildkuglers	N;GEN;INDF;PL
stavkirke	stavkirkens	N;NOM;DEF;SG
primtal	primtals	N;GEN;INDF;PL
knar	knarers	N;GEN;INDF;PL
vams	vams	N;NOM;INDF;SG
diskussion	diskussionens	N;NOM;DEF;SG
glansbillede	glansbillede	N;NOM;INDF;SG
ansøger	ansøgere	N;NOM;INDF;PL
golden retriever	golden retrievere	N;NOM;INDF;PL
fersken	ferskenernes	N;NOM;DEF;PL
debut	debuts	N;GEN;INDF;SG
akkordeon	akkordeons	N;GEN;INDF;SG
tilnavn	tilnavnet	N;NOM;DEF;SG
epitet	epitetet	N;NOM;DEF;SG
stræde	stræder	N;NOM;INDF;PL
klimaforandring	klimaforandringens	N;NOM;DEF;SG
revolution	revolutionerne	N;NOM;DEF;PL
harpe	harpens	N;NOM;DEF;SG
lejrskole	lejrskole	N;NOM;INDF;SG
tobak	tobakken	N;NOM;DEF;SG
hvalros	hvalrossernes	N;NOM;DEF;PL
emir	emirernes	N;NOM;DEF;PL
oversvømmelse	oversvømmelses	N;GEN;INDF;SG
cigarettænder	cigarettænder	N;NOM;INDF;SG
vektorprodukt	vektorprodukter	N;NOM;INDF;PL
straffespark	straffesparkene	N;NOM;DEF;PL
atlet	atleter	N;NOM;INDF;PL
udvikling	udvikling	N;NOM;INDF;SG
dessert	desserterne	N;NOM;DEF;PL
deviere	devieret	V.PTCP;PST;PASS
bryllup	brylluppets	N;NOM;DEF;SG
horkarl	horkarls	N;GEN;INDF;SG
krematorie	krematorie	N;NOM;INDF;SG
magre	magr	V;IMP;ACT
lænestol	lænestolen	N;NOM;DEF;SG
atgejr	atgejrens	N;NOM;DEF;SG
diskutere	diskuter	V;IMP;ACT
mappe	mappes	N;GEN;INDF;SG
satse	satser	V;IND;PRS;ACT
låg	lågets	N;NOM;DEF;SG
tandpasta	tandpastas	N;GEN;INDF;SG
bandeord	bandeordenes	N;NOM;DEF;PL
skive	skivernes	N;NOM;DEF;PL
krabbe	krabberne	N;NOM;DEF;PL
babymajs	babymajs	N;NOM;INDF;PL
brik	brik	N;NOM;INDF;SG
tenor	tenoren	N;NOM;DEF;SG
udskud	udskud	N;NOM;INDF;PL
mesanmast	mesanmasten	N;NOM;DEF;SG
medalje	medaljers	N;GEN;INDF;PL
brugerdiskussionsside	brugerdiskussionssiden	N;NOM;DEF;SG
veganer	veganerne	N;NOM;DEF;PL
scorereplik	scorereplik	N;NOM;INDF;SG
anagram	anagrammernes	N;NOM;DEF;PL
kejsersnit	kejsersnits	N;GEN;INDF;PL
nattergal	nattergal	N;NOM;INDF;SG
semester	semestre	N;NOM;INDF;PL
emballage	emballagers	N;GEN;INDF;PL
palads	palads	N;NOM;INDF;SG
nanometer	nanometers	N;GEN;INDF;PL
grundlov	grundloven	N;NOM;DEF;SG
densitet	densitetens	N;NOM;DEF;SG
pandekage	pandekagernes	N;NOM;DEF;PL
ridder	ridderes	N;GEN;INDF;PL
kunstgalleri	kunstgalleriets	N;NOM;DEF;SG
prisvinder	prisvinderes	N;GEN;INDF;PL
hydrolog	hydrologens	N;NOM;DEF;SG
verdensmester	verdensmesteren	N;NOM;DEF;SG
algoritme	algoritmens	N;NOM;DEF;SG
chikane	chikanes	N;GEN;INDF;SG
tånegl	tåneglens	N;NOM;DEF;SG
synonym	synonymets	N;NOM;DEF;SG
cyste	cyster	N;NOM;INDF;PL
pindsvin	pindsvinets	N;NOM;DEF;SG
udstråle	udstrålede	V;IND;PST;ACT
ungarer	ungarere	N;NOM;INDF;PL
nationalsang	nationalsange	N;NOM;INDF;PL
kerte	kerternes	N;NOM;DEF;PL
længdespring	længdespringenes	N;NOM;DEF;PL
flanere	flaner	V;IMP;ACT
høst	høst	N;NOM;INDF;SG
grin	grinene	N;NOM;DEF;PL
babyloner	babylonernes	N;NOM;DEF;PL
makrel	makrel	N;NOM;INDF;SG
malle	mallen	N;NOM;DEF;SG
indbrud	indbruds	N;GEN;INDF;PL
vejrhane	vejrhaners	N;GEN;INDF;PL
cello	celloers	N;GEN;INDF;PL
tanke	tanken	N;NOM;DEF;SG
hvidløg	hvidløgs	N;GEN;INDF;PL
malke	malkede	V;IND;PST;ACT
angreb	angrebets	N;NOM;DEF;SG
navlestreng	navlestreng	N;NOM;INDF;SG
kædesav	kædesavens	N;NOM;DEF;SG
mutagen	mutagenets	N;NOM;DEF;SG
veganer	veganeres	N;GEN;INDF;PL
silikat	silikat	N;NOM;INDF;SG
jurist	jurist	N;NOM;INDF;SG
vinliste	vinlister	N;NOM;INDF;PL
klan	klanerne	N;NOM;DEF;PL
alkymist	alkymists	N;GEN;INDF;SG
pyjamas	pyjamassens	N;NOM;DEF;SG
flødekaramel	flødekaramellen	N;NOM;DEF;SG
lingvist	lingvisternes	N;NOM;DEF;PL
dekade	dekaden	N;NOM;DEF;SG
håndbold	håndbold	N;NOM;INDF;SG
genotype	genotypens	N;NOM;DEF;SG
pseudonym	pseudonyms	N;GEN;INDF;SG
asyl	asylers	N;GEN;INDF;PL
tolk	tolkes	N;GEN;INDF;PL
majsolie	majsoliernes	N;NOM;DEF;PL
teknik	teknikkers	N;GEN;INDF;PL
ræv	ræv	N;NOM;INDF;SG
bussemand	bussemændenes	N;NOM;DEF;PL
filial	filial	N;NOM;INDF;SG
betydning	betydningernes	N;NOM;DEF;PL
sal	salene	N;NOM;DEF;PL
søjle	søjles	N;GEN;INDF;SG
panda	pandaen	N;NOM;DEF;SG
tone	tone	N;NOM;INDF;SG
mælkebøtte	mælkebøtter	N;NOM;INDF;PL
kontaktinformation	kontaktinformations	N;GEN;INDF;SG
nominativ	nominativerne	N;NOM;DEF;PL
konstruktion	konstruktionerne	N;NOM;DEF;PL
neuron	neuron	N;NOM;INDF;SG
karikartutegning	karikartutegning	N;NOM;INDF;SG
vinkelhalveringslinje	vinkelhalveringslinjens	N;NOM;DEF;SG
etiopier	etiopieren	N;NOM;DEF;SG
abkhaser	abkhaseren	N;NOM;DEF;SG
datolinje	datolinjernes	N;NOM;DEF;PL
astronaut	astronauters	N;GEN;INDF;PL
lyske	lyske	N;NOM;INDF;SG
debat	debatter	N;NOM;INDF;PL
glimt	glimt	N;NOM;INDF;SG
neutrum	neutrummerne	N;NOM;DEF;PL
ølmave	ølmaven	N;NOM;DEF;SG
differenskvotient	differenskvotienten	N;NOM;DEF;SG
hjerte	hjerters	N;GEN;INDF;PL
stræde	stræderne	N;NOM;DEF;PL
ordbog	ordbøger	N;NOM;INDF;PL
døgn	døgnet	N;NOM;DEF;SG
tryk	tryk	N;NOM;INDF;PL
karantæne	karantæner	N;NOM;INDF;PL
metropol	metropolens	N;NOM;DEF;SG
akillessene	akillessenes	N;GEN;INDF;SG
tatovere	tatoverende	V.PTCP;PRS;ACT
pokal	pokalers	N;GEN;INDF;PL
sydkyst	sydkyst	N;NOM;INDF;SG
stængel	stænglers	N;GEN;INDF;PL
impuls	impulserne	N;NOM;DEF;PL
annektering	annektering	N;NOM;INDF;SG
diskussionsside	diskussionssides	N;GEN;INDF;SG
konkurrence	konkurrencer	N;NOM;INDF;PL
burgerbar	burgerbaren	N;NOM;DEF;SG
skandale	skandaler	N;NOM;INDF;PL
annullation	annullations	N;GEN;INDF;SG
eksistens	eksistensens	N;NOM;DEF;SG
basun	basunernes	N;NOM;DEF;PL
indhøste	indhøstede	V;IND;PST;ACT
vortemælk	vortemælkens	N;NOM;DEF;SG
husbåd	husbåden	N;NOM;DEF;SG
argentiner	argentineren	N;NOM;DEF;SG
antal	antallet	N;NOM;DEF;SG
frakke	frakkens	N;NOM;DEF;SG
småkage	småkager	N;NOM;INDF;PL
ektoplasma	ektoplasma	N;NOM;INDF;SG
stål	ståls	N;GEN;INDF;SG
tatovere	tatoveres	V;IND;PRS;PASS
årtusind	årtusindet	N;NOM;DEF;SG
besked	beskeder	N;NOM;INDF;PL
opdagelse	opdagelses	N;GEN;INDF;SG
medicin	medicinerne	N;NOM;DEF;PL
krop	kroppens	N;NOM;DEF;SG
tandlæge	tandlægens	N;NOM;DEF;SG
ambra	ambras	N;GEN;INDF;SG
øjenlåg	øjenlågenes	N;NOM;DEF;PL
svip	svip	N;NOM;INDF;SG
kirkeklokke	kirkeklokkers	N;GEN;INDF;PL
tandpasta	tandpastaers	N;GEN;INDF;PL
glarmester	glarmestrene	N;NOM;DEF;PL
hofteholder	hofteholdernes	N;NOM;DEF;PL
bund	bundenes	N;NOM;DEF;PL
pengeautomat	pengeautomater	N;NOM;INDF;PL
ballade	balladens	N;NOM;DEF;SG
æbletærte	æbletærtens	N;NOM;DEF;SG
remoulade	remouladen	N;NOM;DEF;SG
palads	paladser	N;NOM;INDF;PL
musikvideoinstruktør	musikvideoinstruktøren	N;NOM;DEF;SG
emne	emnet	N;NOM;DEF;SG
kæp	kæppe	N;NOM;INDF;PL
struds	strudse	N;NOM;INDF;PL
brystvorte	brystvorternes	N;NOM;DEF;PL
start	starten	N;NOM;DEF;SG
sudaner	sudaneres	N;GEN;INDF;PL
absurditet	absurditeter	N;NOM;INDF;PL
basketballspiller	basketballspilleres	N;GEN;INDF;PL
tur	turene	N;NOM;DEF;PL
raritet	rariteters	N;GEN;INDF;PL
kunst	kunst	N;NOM;INDF;SG
begyndelse	begyndelser	N;NOM;INDF;PL
ædelsten	ædelstenen	N;NOM;DEF;SG
ventil	ventilernes	N;NOM;DEF;PL
neg	neg	N;NOM;INDF;PL
anglofil	anglofil	N;NOM;INDF;SG
pore	pores	N;GEN;INDF;SG
tatovør	tatovørerne	N;NOM;DEF;PL
tøjte	tøjten	N;NOM;DEF;SG
hjerne	hjernerne	N;NOM;DEF;PL
fjord	fjordenes	N;NOM;DEF;PL
gåsepotentil	gåsepotentillerne	N;NOM;DEF;PL
albumin	albuminers	N;GEN;INDF;PL
kugleramme	kuglerammens	N;NOM;DEF;SG
mellemkrigsår	mellemkrigsårs	N;GEN;INDF;PL
stormfugl	stormfuglene	N;NOM;DEF;PL
navlestreng	navlestrengenes	N;NOM;DEF;PL
gudstjeneste	gudstjenestens	N;NOM;DEF;SG
boysenbær	boysenbær	N;NOM;INDF;SG
række	rækkernes	N;NOM;DEF;PL
resistivitet	resistivitets	N;GEN;INDF;SG
loddekolbe	loddekolben	N;NOM;DEF;SG
kvart	kvartens	N;NOM;DEF;SG
kineser	kineseres	N;GEN;INDF;PL
nitrat	nitraten	N;NOM;DEF;SG
elektron	elektron	N;NOM;INDF;SG
cigaretrør	cigaretrørenes	N;NOM;DEF;PL
beton	betoner	N;NOM;INDF;PL
trubadour	trubadour	N;NOM;INDF;SG
abyssinier	abyssinier	N;NOM;INDF;SG
knagerække	knagerækkes	N;GEN;INDF;SG
kriterium	kriteriets	N;NOM;DEF;SG
smil	smils	N;GEN;INDF;PL
englænder	englænderne	N;NOM;DEF;PL
sammenskrivning	sammenskrivningers	N;GEN;INDF;PL
neksøbo	neksøboerne	N;NOM;DEF;PL
ran	ran	N;NOM;INDF;SG
rosmarin	rosmarinernes	N;NOM;DEF;PL
konflikt	konflikt	N;NOM;INDF;SG
magre	magrende	V.PTCP;PRS;ACT
ædelsten	ædelstens	N;GEN;INDF;PL
klan	klanernes	N;NOM;DEF;PL
præstation	præstationerne	N;NOM;DEF;PL
afsnit	afsnits	N;GEN;INDF;PL
fajance	fajancen	N;NOM;DEF;SG
sangsvane	sangsvanernes	N;NOM;DEF;PL
penis	penis	N;NOM;INDF;SG
carbonkredsløb	carbonkredsløbenes	N;NOM;DEF;PL
avance	avancen	N;NOM;DEF;SG
gravsten	gravstenene	N;NOM;DEF;PL
golfer	golferes	N;GEN;INDF;PL
imitere	imiterende	V.PTCP;PRS;ACT
nonne	nonnes	N;GEN;INDF;SG
substituere	substituer	V;IMP;ACT
middag	middagens	N;NOM;DEF;SG
samfund	samfund	N;NOM;INDF;SG
cirkeludsnit	cirkeludsnit	N;NOM;INDF;PL
krokodille	krokodille	N;NOM;INDF;SG
skive	skiven	N;NOM;DEF;SG
papir	papirernes	N;NOM;DEF;PL
løve	løvens	N;NOM;DEF;SG
person	personen	N;NOM;DEF;SG
raritet	rariteten	N;NOM;DEF;SG
tragt	tragts	N;GEN;INDF;SG
åg	ågs	N;GEN;INDF;PL
skarpskytte	skarpskytter	N;NOM;INDF;PL
fordampningsvarme	fordampningsvarmerne	N;NOM;DEF;PL
hjemmeside	hjemmesiders	N;GEN;INDF;PL
penneven	pennevennernes	N;NOM;DEF;PL
trommesæt	trommesættet	N;NOM;DEF;SG
produkt	produkter	N;NOM;INDF;PL
fodring	fodringen	N;NOM;DEF;SG
diamant	diamanter	N;NOM;INDF;PL
godbid	godbidders	N;GEN;INDF;PL
nødvendighed	nødvendigheden	N;NOM;DEF;SG
allokering	allokeringer	N;NOM;INDF;PL
genotype	genotypen	N;NOM;DEF;SG
kladde	kladderne	N;NOM;DEF;PL
primtal	primtallenes	N;NOM;DEF;PL
primtal	primtal	N;NOM;INDF;PL
vrag	vrags	N;GEN;INDF;PL
søgeresultat	søgeresultats	N;GEN;INDF;SG
sesamolie	sesamoliernes	N;NOM;DEF;PL
værdimængde	værdimængden	N;NOM;DEF;SG
klassifikation	klassifikationernes	N;NOM;DEF;PL
triumf	triumfernes	N;NOM;DEF;PL
høg	høge	N;NOM;INDF;PL
tolvfingertarm	tolvfingertarmens	N;NOM;DEF;SG
mulighed	muligheds	N;GEN;INDF;SG
malstrøm	malstrømmen	N;NOM;DEF;SG
smaragd	smaragdens	N;NOM;DEF;SG
videospilfigur	videospilfiguren	N;NOM;DEF;SG
flag	flag	N;NOM;INDF;SG
altmuligmand	altmuligmanden	N;NOM;DEF;SG
gyngehest	gyngehest	N;NOM;INDF;SG
gren	grenene	N;NOM;DEF;PL
flertal	flertallet	N;NOM;DEF;SG
dyste	dyste	V;NFIN;ACT
mus	mus'	N;GEN;INDF;SG
eksamen	eksamenen	N;NOM;DEF;SG
dannebrog	dannebrogets	N;NOM;DEF;SG
æbleskive	æbleskivernes	N;NOM;DEF;PL
sojaolie	sojaoliernes	N;NOM;DEF;PL
marinere	marinerede	V;IND;PST;ACT
afsked	afskeden	N;NOM;DEF;SG
altæder	altæders	N;GEN;INDF;SG
ordsprog	ordsprog	N;NOM;INDF;PL
fødsel	fødsler	N;NOM;INDF;PL
underlag	underlag	N;NOM;INDF;PL
patient	patienter	N;NOM;INDF;PL
eftermiddag	eftermiddagene	N;NOM;DEF;PL
gyroskop	gyroskops	N;GEN;INDF;SG
strategi	strategier	N;NOM;INDF;PL
fregne	fregnes	N;GEN;INDF;SG
yndlingsfarve	yndlingsfarve	N;NOM;INDF;SG
rom	roms	N;GEN;INDF;SG
tyv	tyve	N;NOM;INDF;PL
brandbil	brandbiler	N;NOM;INDF;PL
afrikaner	afrikaners	N;GEN;INDF;SG
korps	korps	N;NOM;INDF;PL
kaskade	kaskaders	N;GEN;INDF;PL
pelargonie	pelargoniers	N;GEN;INDF;PL
hvirveldyr	hvirveldyr	N;NOM;INDF;PL
celle	cellernes	N;NOM;DEF;PL
organdonor	organdonorerne	N;NOM;DEF;PL
spisebord	spisebords	N;GEN;INDF;SG
fiskestang	fiskestænger	N;NOM;INDF;PL
balkon	balkonerne	N;NOM;DEF;PL
vandmelon	vandmelonens	N;NOM;DEF;SG
rekviem	rekviem	N;NOM;INDF;SG
inficere	inficeres	V;IND;PRS;PASS
bogstav	bogstavets	N;NOM;DEF;SG
balkon	balkons	N;GEN;INDF;SG
kælling	kællingernes	N;NOM;DEF;PL
århusianer	århusianernes	N;NOM;DEF;PL
nødudgang	nødudgangen	N;NOM;DEF;SG
kanin	kanin	N;NOM;INDF;SG
arkiv	arkivers	N;GEN;INDF;PL
halvbror	halvbroren	N;NOM;DEF;SG
lydpotte	lydpottens	N;NOM;DEF;SG
hud	huden	N;NOM;DEF;SG
møl	møls	N;GEN;INDF;SG
sektor	sektorer	N;NOM;INDF;PL
kup	kuppets	N;NOM;DEF;SG
punktum	punktummerne	N;NOM;DEF;PL
chokolade	chokoladerne	N;NOM;DEF;PL
lut	lutterne	N;NOM;DEF;PL
terzet	terzet	N;NOM;INDF;SG
spilkarakter	spilkarakterer	N;NOM;INDF;PL
afsked	afsked	N;NOM;INDF;SG
politimester	politimestre	N;NOM;INDF;PL
ironi	ironierne	N;NOM;DEF;PL
egn	egn	N;NOM;INDF;SG
nyre	nyrens	N;NOM;DEF;SG
spindelvæv	spindelvævs	N;GEN;INDF;SG
vækkeur	vækkeures	N;GEN;INDF;PL
autorisation	autorisationerne	N;NOM;DEF;PL
dyd	dyder	N;NOM;INDF;PL
organisere	organiserer	V;IND;PRS;ACT
grotesk	groteskerne	N;NOM;DEF;PL
database	databasen	N;NOM;DEF;SG
vandmelon	vandmeloners	N;GEN;INDF;PL
knalde	knaldede	V;IND;PST;ACT
kurs	kurs'	N;GEN;INDF;SG
tegneserie	tegneseriens	N;NOM;DEF;SG
strop	stroppen	N;NOM;DEF;SG
thiuf	thiufæn	N;NOM;DEF;SG
luftkastel	luftkastel	N;NOM;INDF;SG
supermagt	supermagternes	N;NOM;DEF;PL
brugerdiskussion	brugerdiskussionerne	N;NOM;DEF;PL
argument	argumenterne	N;NOM;DEF;PL
fingernegl	fingerneglens	N;NOM;DEF;SG
das	dasser	N;NOM;INDF;PL
zar	zarers	N;GEN;INDF;PL
ophavsgruppe	ophavsgruppe	N;NOM;INDF;SG
ankre	ankrer	V;IND;PRS;ACT
papegøje	papegøjens	N;NOM;DEF;SG
lastbil	lastbiler	N;NOM;INDF;PL
kronprinsesse	kronprinsessen	N;NOM;DEF;SG
lokomotiv	lokomotivers	N;GEN;INDF;PL
araber	arabere	N;NOM;INDF;PL
autorisation	autorisation	N;NOM;INDF;SG
brønd	brønde	N;NOM;INDF;PL
lillebror	lillebror	N;NOM;INDF;SG
mile	milerne	N;NOM;DEF;PL
altan	altaner	N;NOM;INDF;PL
skomager	skomageren	N;NOM;DEF;SG
skumring	skumrings	N;GEN;INDF;SG
kronprinsesse	kronprinsessens	N;NOM;DEF;SG
solsikke	solsikkers	N;GEN;INDF;PL
agerhøne	agerhøns'	N;GEN;INDF;PL
flynder	flynderes	N;GEN;INDF;PL
kasseapparat	kasseapparaters	N;GEN;INDF;PL
lut	luts	N;GEN;INDF;SG
mandarin	mandarinen	N;NOM;DEF;SG
horoskop	horoskoperne	N;NOM;DEF;PL
succes	succes'	N;GEN;INDF;SG
cigar	cigarernes	N;NOM;DEF;PL
helhest	helhestene	N;NOM;DEF;PL
halvmåne	halvmåne	N;NOM;INDF;SG
sarkasme	sarkasmernes	N;NOM;DEF;PL
stork	storkens	N;NOM;DEF;SG
sonate	sonaterne	N;NOM;DEF;PL
armbåndsur	armbåndsurenes	N;NOM;DEF;PL
snog	snoges	N;GEN;INDF;PL
bon	bonerne	N;NOM;DEF;PL
dråbe	dråbes	N;GEN;INDF;SG
sikkerhed	sikkerhedens	N;NOM;DEF;SG
issyl	issyls	N;GEN;INDF;SG
onomatopoietikon	onomatopoietikaene	N;NOM;DEF;PL
tømrer	tømrer	N;NOM;INDF;SG
fiskestang	fiskestangens	N;NOM;DEF;SG
musikpædagog	musikpædagog	N;NOM;INDF;SG
vandregræshoppe	vandregræshoppen	N;NOM;DEF;SG
gnist	gnisten	N;NOM;DEF;SG
lunte	lunte	N;NOM;INDF;SG
vejr	vejrets	N;NOM;DEF;SG
forsørger	forsørgere	N;NOM;INDF;PL
statsoverhoved	statsoverhoveds	N;GEN;INDF;SG
gæstebog	gæstebøgers	N;GEN;INDF;PL
farvestof	farvestofferne	N;NOM;DEF;PL
distance	distancers	N;GEN;INDF;PL
fasan	fasanerne	N;NOM;DEF;PL
syre	syrerne	N;NOM;DEF;PL
knap	knapper	N;NOM;INDF;PL
mellemnavn	mellemnavnenes	N;NOM;DEF;PL
gevinst	gevinsters	N;GEN;INDF;PL
videnskab	videnskaber	N;NOM;INDF;PL
federation	federationen	N;NOM;DEF;SG
eventyrer	eventyrerens	N;NOM;DEF;SG
fagforening	fagforeningers	N;GEN;INDF;PL
halvbror	halvbrorens	N;NOM;DEF;SG
starut	staruts	N;GEN;INDF;SG
avocado	avocadoerne	N;NOM;DEF;PL
ishockeyspiller	ishockeyspillerens	N;NOM;DEF;SG
høtyv	høtyve	N;NOM;INDF;PL
væge	vægers	N;GEN;INDF;PL
stofmisbrug	stofmisbrugs	N;GEN;INDF;PL
krokodilletåre	krokodilletåre	N;NOM;INDF;SG
børnehave	børnehavens	N;NOM;DEF;SG
ordsprog	ordsprogene	N;NOM;DEF;PL
spyd	spyd	N;NOM;INDF;PL
elfenbenstårn	elfenbenstårnets	N;NOM;DEF;SG
ork	ork	N;NOM;INDF;SG
bogstav	bogstaver	N;NOM;INDF;PL
møbel	møblers	N;GEN;INDF;PL
præsident	præsidenterne	N;NOM;DEF;PL
afdeling	afdelingen	N;NOM;DEF;SG
furie	furier	N;NOM;INDF;PL
madding	maddingen	N;NOM;DEF;SG
dehydrere	dehydrer	V;IMP;ACT
skoletaske	skoletasken	N;NOM;DEF;SG
motiv	motivernes	N;NOM;DEF;PL
bersærk	bersærker	N;NOM;INDF;PL
cigar	cigar	N;NOM;INDF;SG
bogorm	bogorme	N;NOM;INDF;PL
ståsted	ståstedets	N;NOM;DEF;SG
græsenke	græsenkes	N;GEN;INDF;SG
suffiks	suffiksernes	N;NOM;DEF;PL
mage	magers	N;GEN;INDF;PL
kommentere	kommenteredes	V;IND;PST;PASS
børs	børs'	N;GEN;INDF;SG
metafor	metaforers	N;GEN;INDF;PL
mare	marens	N;NOM;DEF;SG
nøgleroman	nøgleromanens	N;NOM;DEF;SG
galskab	galskaberne	N;NOM;DEF;PL
despot	despoternes	N;NOM;DEF;PL
bidrag	bidrag	N;NOM;INDF;PL
blender	blender	N;NOM;INDF;SG
skud	skuds	N;GEN;INDF;PL
dadel	dadlen	N;NOM;DEF;SG
motivation	motivationen	N;NOM;DEF;SG
kentaur	kentaurers	N;GEN;INDF;PL
ordkløver	ordkløver	N;NOM;INDF;SG
pilgrim	pilgrim	N;NOM;INDF;SG
betablokker	betablokkers	N;GEN;INDF;SG
basketballkurv	basketballkurvs	N;GEN;INDF;SG
barrikade	barrikaders	N;GEN;INDF;PL
knalde	knaldet	V.PTCP;PST;PASS
udsagnsord	udsagnsordenes	N;NOM;DEF;PL
blender	blenderne	N;NOM;DEF;PL
rabat	rabatter	N;NOM;INDF;PL
multiplayerspil	multiplayerspil	N;NOM;INDF;PL
landsbytosse	landsbytosse	N;NOM;INDF;SG
eng	engene	N;NOM;DEF;PL
kraft	kraftens	N;NOM;DEF;SG
lån	lån	N;NOM;INDF;PL
liechtensteiner	liechtensteinerens	N;NOM;DEF;SG
forsørger	forsørgerens	N;NOM;DEF;SG
smoking	smokings	N;GEN;INDF;SG
sværm	sværmes	N;GEN;INDF;PL
strejf	strejfene	N;NOM;DEF;PL
forårsrulle	forårsrullers	N;GEN;INDF;PL
mår	mårer	N;NOM;INDF;PL
danskvand	danskvandernes	N;NOM;DEF;PL
køb	køb	N;NOM;INDF;SG
bil	bilens	N;NOM;DEF;SG
horn	horn	N;NOM;INDF;SG
haj	hajers	N;GEN;INDF;PL
pilgrim	pilgrimmenes	N;NOM;DEF;PL
sludder	sluddere	N;NOM;INDF;PL
svækling	svæklingens	N;NOM;DEF;SG
kule	kule	N;NOM;INDF;SG
politimand	politimand	N;NOM;INDF;SG
yndling	yndlings	N;GEN;INDF;SG
paradoks	paradoksets	N;NOM;DEF;SG
snor	snorene	N;NOM;DEF;PL
sålbænk	sålbænkes	N;GEN;INDF;PL
vagt	vagterne	N;NOM;DEF;PL
præposition	præpositionerne	N;NOM;DEF;PL
lørdag	lørdagen	N;NOM;DEF;SG
estimat	estimater	N;NOM;INDF;PL
nippel	niplers	N;GEN;INDF;PL
jordsvin	jordsvin	N;NOM;INDF;PL
padde	paddernes	N;NOM;DEF;PL
sonate	sonater	N;NOM;INDF;PL
dukke	dukkerne	N;NOM;DEF;PL
frygte	frygt	V;IMP;ACT
skulptur	skulpturens	N;NOM;DEF;SG
japaner	japanere	N;NOM;INDF;PL
karakter	karakterer	N;NOM;INDF;PL
pantebrev	pantebreves	N;GEN;INDF;PL
solsikkeolie	solsikkeolier	N;NOM;INDF;PL
polygon	polygonernes	N;NOM;DEF;PL
mandarin	mandarinens	N;NOM;DEF;SG
plov	plove	N;NOM;INDF;PL
halvvokal	halvvokalens	N;NOM;DEF;SG
lomme	lommes	N;GEN;INDF;SG
konserveringsmiddel	konserveringsmidlets	N;NOM;DEF;SG
flankere	flankerende	V.PTCP;PRS;ACT
venskabsby	venskabsbyen	N;NOM;DEF;SG
forkortelse	forkortelses	N;GEN;INDF;SG
billet	billetter	N;NOM;INDF;PL
brakteat	brakteat	N;NOM;INDF;SG
tændstikmand	tændstikmænd	N;NOM;INDF;PL
esplanade	esplanades	N;GEN;INDF;SG
husmand	husmanden	N;NOM;DEF;SG
mare	marers	N;GEN;INDF;PL
pessimist	pessimisters	N;GEN;INDF;PL
optimist	optimistens	N;NOM;DEF;SG
refraktion	refraktions	N;GEN;INDF;SG
bombe	bomber	N;NOM;INDF;PL
stud	stud	N;NOM;INDF;SG
jolle	jollen	N;NOM;DEF;SG
computerspilfigur	computerspilfigurernes	N;NOM;DEF;PL
hav	hav	N;NOM;INDF;SG
hedning	hedningens	N;NOM;DEF;SG
kongruens	kongruens'	N;GEN;INDF;SG
kommissær	kommissærens	N;NOM;DEF;SG
fremtid	fremtiders	N;GEN;INDF;PL
horehus	horehus'	N;GEN;INDF;SG
skrivemaskine	skrivemaskine	N;NOM;INDF;SG
niece	niecen	N;NOM;DEF;SG
vølve	vølves	N;GEN;INDF;SG
kulstofkredsløb	kulstofkredsløbet	N;NOM;DEF;SG
stork	storkene	N;NOM;DEF;PL
fipskæg	fipskæggets	N;NOM;DEF;SG
gæstebog	gæstebog	N;NOM;INDF;SG
fiskestang	fiskestangs	N;GEN;INDF;SG
blender	blendere	N;NOM;INDF;PL
tredjepart	tredjeparts	N;GEN;INDF;SG
hukommelse	hukommelse	N;NOM;INDF;SG
nevø	nevøers	N;GEN;INDF;PL
integrere	integrerende	V.PTCP;PRS;ACT
måge	måges	N;GEN;INDF;SG
snebold	sneboldene	N;NOM;DEF;PL
operere	opereredes	V;IND;PST;PASS
lomme	lommen	N;NOM;DEF;SG
assimilere	assimileredes	V;IND;PST;PASS
dynasti	dynastierne	N;NOM;DEF;PL
seraf	seraferne	N;NOM;DEF;PL
parallellogram	parallellograms	N;GEN;INDF;SG
amøbe	amøbers	N;GEN;INDF;PL
pyrrhussejr	pyrrhussejre	N;NOM;INDF;PL
dampskib	dampskibe	N;NOM;INDF;PL
pinlighed	pinlighedens	N;NOM;DEF;SG
musikinstrument	musikinstrumenter	N;NOM;INDF;PL
paté	patéens	N;NOM;DEF;SG
notits	notitsen	N;NOM;DEF;SG
hviderusser	hviderusserens	N;NOM;DEF;SG
bevis	bevisets	N;NOM;DEF;SG
central	centralernes	N;NOM;DEF;PL
abort	aborterne	N;NOM;DEF;PL
kongruens	kongruenserne	N;NOM;DEF;PL
kradse	kradsende	V.PTCP;PRS;ACT
cigaretsælger	cigaretsælgernes	N;NOM;DEF;PL
karamel	karamellens	N;NOM;DEF;SG
skudår	skudårs	N;GEN;INDF;PL
tirsdag	tirsdage	N;NOM;INDF;PL
gummi	gummiernes	N;NOM;DEF;PL
gaffel	gaflernes	N;NOM;DEF;PL
svale	svales	N;GEN;INDF;SG
hypnotisør	hypnotisørernes	N;NOM;DEF;PL
syre	syrens	N;NOM;DEF;SG
kokkepige	kokkepigernes	N;NOM;DEF;PL
panter	panternes	N;NOM;DEF;PL
forglemmigej	forglemmigejers	N;GEN;INDF;PL
isbjørn	isbjørnes	N;GEN;INDF;PL
fødsel	fødslen	N;NOM;DEF;SG
grønlænder	grønlænderen	N;NOM;DEF;SG
lykønske	lykønsk	V;IMP;ACT
visdomstand	visdomstandens	N;NOM;DEF;SG
bagslag	bagslag	N;NOM;INDF;SG
krølle	krøllernes	N;NOM;DEF;PL
cigaret	cigarettens	N;NOM;DEF;SG
sommerfugl	sommerfugls	N;GEN;INDF;SG
midtnormal	midtnormalers	N;GEN;INDF;PL
slurk	slurken	N;NOM;DEF;SG
ægte	ægtede	V;IND;PST;ACT
superorganisme	superorganismernes	N;NOM;DEF;PL
valnød	valnødder	N;NOM;INDF;PL
propeller	propelleren	N;NOM;DEF;SG
ordenstal	ordenstals	N;GEN;INDF;SG
retssal	retssalene	N;NOM;DEF;PL
bordeaux	bordeauxens	N;NOM;DEF;SG
stådreng	stådrengene	N;NOM;DEF;PL
snor	snore	N;NOM;INDF;PL
hjelm	hjelmenes	N;NOM;DEF;PL
guldfisk	guldfiskenes	N;NOM;DEF;PL
svans	svanse	N;NOM;INDF;PL
forholdsord	forholdsords	N;GEN;INDF;SG
køretøj	køretøjet	N;NOM;DEF;SG
bæk	bækkenes	N;NOM;DEF;PL
platfod	platfods	N;GEN;INDF;SG
negl	neglenes	N;NOM;DEF;PL
knap	knaps	N;GEN;INDF;SG
biologi	biologi	N;NOM;INDF;SG
afsked	afskeder	N;NOM;INDF;PL
horn	horns	N;GEN;INDF;PL
kastanje	kastanjernes	N;NOM;DEF;PL
talord	talordet	N;NOM;DEF;SG
sav	saven	N;NOM;DEF;SG
patent	patenterne	N;NOM;DEF;PL
standart	standart	N;NOM;INDF;SG
pind	pind	N;NOM;INDF;SG
kranse	kransende	V.PTCP;PRS;ACT
gemytlighed	gemytlighed	N;NOM;INDF;SG
rundkørsel	rundkørslen	N;NOM;DEF;SG
federation	federationer	N;NOM;INDF;PL
kup	kuppenes	N;NOM;DEF;PL
substans	substans	N;NOM;INDF;SG
moratorium	moratoriernes	N;NOM;DEF;PL
bønne	bønnes	N;GEN;INDF;SG
motivation	motivationernes	N;NOM;DEF;PL
ejendom	ejendommene	N;NOM;DEF;PL
cigaretmærke	cigaretmærkes	N;GEN;INDF;SG
dodekaeder	dodekaeder	N;NOM;INDF;SG
aftale	aftales	N;GEN;INDF;SG
albatros	albatrossen	N;NOM;DEF;SG
manifest	manifesters	N;GEN;INDF;PL
dæk	dækkets	N;NOM;DEF;SG
forklare	forklar	V;IMP;ACT
wc-rulle	wc-ruller	N;NOM;INDF;PL
jungle	junglernes	N;NOM;DEF;PL
bæst	bæst	N;NOM;INDF;SG
foster	fosters	N;GEN;INDF;SG
kriger	krigeren	N;NOM;DEF;SG
syllogisme	syllogismer	N;NOM;INDF;PL
pennalhus	pennalhusene	N;NOM;DEF;PL
brandsår	brandsår	N;NOM;INDF;PL
tæller	tælleres	N;GEN;INDF;PL
heliotrop	heliotroper	N;NOM;INDF;PL
ulk	ulkenes	N;NOM;DEF;PL
krøsus	krøsussers	N;GEN;INDF;PL
mavesaft	mavesaften	N;NOM;DEF;SG
vorte	vorten	N;NOM;DEF;SG
værktøj	værktøjers	N;GEN;INDF;PL
afstand	afstandene	N;NOM;DEF;PL
potentat	potentatens	N;NOM;DEF;SG
skrin	skrinenes	N;NOM;DEF;PL
mandola	mandolaerne	N;NOM;DEF;PL
palaver	palaver	N;NOM;INDF;SG
mandarin	mandariner	N;NOM;INDF;PL
recitation	recitationers	N;GEN;INDF;PL
kronprins	kronprinsen	N;NOM;DEF;SG
elg	elge	N;NOM;INDF;PL
synder	synderes	N;GEN;INDF;PL
affaldscontainer	affaldscontainers	N;GEN;INDF;SG
jødinde	jødinders	N;GEN;INDF;PL
ambassade	ambassade	N;NOM;INDF;SG
vejr	vejr	N;NOM;INDF;PL
lillebror	lillebrorens	N;NOM;DEF;SG
løg	løg	N;NOM;INDF;PL
definitionsmængde	definitionsmængden	N;NOM;DEF;SG
afholdsmand	afholdsmænds	N;GEN;INDF;PL
granat	granat	N;NOM;INDF;SG
medgift	medgiften	N;NOM;DEF;SG
efterår	efterårets	N;NOM;DEF;SG
rabat	rabats	N;GEN;INDF;SG
kriger	krigerne	N;NOM;DEF;PL
mellemistid	mellemistiders	N;GEN;INDF;PL
oversættelse	oversættelsers	N;GEN;INDF;PL
orientering	orienteringer	N;NOM;INDF;PL
faktum	faktas	N;GEN;INDF;PL
spermatozo	spermatozoernes	N;NOM;DEF;PL
skøjte	skøjte	N;NOM;INDF;SG
vandregræshoppe	vandregræshoppernes	N;NOM;DEF;PL
realist	realist	N;NOM;INDF;SG
advent	adventers	N;GEN;INDF;PL
kalkun	kalkunen	N;NOM;DEF;SG
strikkepind	strikkepinden	N;NOM;DEF;SG
svigte	svigte	V;NFIN;ACT
clips	clips	N;NOM;INDF;SG
and	ænderne	N;NOM;DEF;PL
bankkonto	bankkontoens	N;NOM;DEF;SG
lån	lånene	N;NOM;DEF;PL
tjeneste	tjeneste	N;NOM;INDF;SG
padde	paddes	N;GEN;INDF;SG
kommentere	kommenterer	V;IND;PRS;ACT
rektor	rektorens	N;NOM;DEF;SG
tepose	teposerne	N;NOM;DEF;PL
platfod	platføddernes	N;NOM;DEF;PL
kup	kups	N;GEN;INDF;SG
gelé	gelés	N;GEN;INDF;SG
akkusativ	akkusativernes	N;NOM;DEF;PL
græker	grækere	N;NOM;INDF;PL
metafor	metaforernes	N;NOM;DEF;PL
konsekvens	konsekvenser	N;NOM;INDF;PL
egn	egnen	N;NOM;DEF;SG
marinere	marinerende	V.PTCP;PRS;ACT
pronomen	pronomens	N;GEN;INDF;SG
forbier	forbieres	N;GEN;INDF;PL
differensrække	differensrækker	N;NOM;INDF;PL
relativ	relativ	N;NOM;INDF;SG
tortur	torturers	N;GEN;INDF;PL
halvvokal	halvvokalers	N;GEN;INDF;PL
genfærd	genfærd	N;NOM;INDF;SG
ejer	ejers	N;GEN;INDF;SG
perle	perlernes	N;NOM;DEF;PL
kommunist	kommunists	N;GEN;INDF;SG
kiste	kisterne	N;NOM;DEF;PL
mus	musen	N;NOM;DEF;SG
meteorit	meteorits	N;GEN;INDF;SG
anledning	anlednings	N;GEN;INDF;SG
halskæde	halskædes	N;GEN;INDF;SG
gaffel	gaflensgaffelens	N;NOM;DEF;SG
carnivor	carnivorer	N;NOM;INDF;PL
ludder	ludderen	N;NOM;DEF;SG
kontor	kontorets	N;NOM;DEF;SG
moderkage	moderkagen	N;NOM;DEF;SG
intelligenskvotient	intelligenskvotienters	N;GEN;INDF;PL
apokope	apokopers	N;GEN;INDF;PL
profeti	profetiers	N;GEN;INDF;PL
niveau	niveauer	N;NOM;INDF;PL
krølle	krølle	N;NOM;INDF;SG
slot	slots	N;GEN;INDF;SG
barnesoldat	barnesoldaten	N;NOM;DEF;SG
fornemmelse	fornemmelse	N;NOM;INDF;SG
dyd	dyds	N;GEN;INDF;SG
oldemor	oldemor	N;NOM;INDF;SG
vals	vals'	N;GEN;INDF;SG
reportage	reportagen	N;NOM;DEF;SG
recirkulation	recirkulations	N;GEN;INDF;SG
rødlos	rødlosserne	N;NOM;DEF;PL
udsigt	udsigten	N;NOM;DEF;SG
brandbil	brandbil	N;NOM;INDF;SG
orkestergrav	orkestergrave	N;NOM;INDF;PL
sanger	sangerne	N;NOM;DEF;PL
fritænker	fritænkers	N;GEN;INDF;SG
pinlighed	pinligheder	N;NOM;INDF;PL
esplanade	esplanader	N;NOM;INDF;PL
musikkonservatorie	musikkonservatories	N;GEN;INDF;SG
rapportering	rapporteringernes	N;NOM;DEF;PL
intervention	interventions	N;GEN;INDF;SG
ærme	ærmets	N;NOM;DEF;SG
vasal	vasallens	N;NOM;DEF;SG
hest	hesten	N;NOM;DEF;SG
unge	unger	N;NOM;INDF;PL
plæneklipper	plæneklipperenes	N;NOM;DEF;PL
voldtægt	voldtægters	N;GEN;INDF;PL
trækfugl	trækfuglenes	N;NOM;DEF;PL
foderbræt	foderbrætterne	N;NOM;DEF;PL
radiobil	radiobilernes	N;NOM;DEF;PL
sygdom	sygdomme	N;NOM;INDF;PL
diabetiker	diabetikeres	N;GEN;INDF;PL
hat	hats	N;GEN;INDF;SG
dyste	dystede	V;IND;PST;ACT
cylinder	cylinderne	N;NOM;DEF;PL
duel	duellerne	N;NOM;DEF;PL
krokodilletåre	krokodilletårernes	N;NOM;DEF;PL
ambassade	ambassaderne	N;NOM;DEF;PL
køleskab	køleskabet	N;NOM;DEF;SG
statsoverhoved	statsoverhovedets	N;NOM;DEF;SG
arne	arne	N;NOM;INDF;SG
avocado	avocadoernes	N;NOM;DEF;PL
pen	pennene	N;NOM;DEF;PL
hasselnød	hasselnødden	N;NOM;DEF;SG
kænguru	kænguruerne	N;NOM;DEF;PL
accelerere	accelereres	V;IND;PRS;PASS
navnebror	navnebroren	N;NOM;DEF;SG
rude	rudens	N;NOM;DEF;SG
hollænder	hollænder	N;NOM;INDF;SG
trækfugl	trækfuglens	N;NOM;DEF;SG
hobby	hobbyer	N;NOM;INDF;PL
søster	søstres	N;GEN;INDF;PL
ribs	ribs'	N;GEN;INDF;SG
faktotum	faktotummers	N;GEN;INDF;PL
proprium	propriet	N;NOM;DEF;SG
nøgleben	nøglebenets	N;NOM;DEF;SG
ælte	ælt	V;IMP;ACT
urinrør	urinrørs	N;GEN;INDF;PL
estimat	estimats	N;GEN;INDF;SG
tysker	tyskers	N;GEN;INDF;SG
samarbejde	samarbejdets	N;NOM;DEF;SG
antistof	antistof	N;NOM;INDF;SG
kæphest	kæphestes	N;GEN;INDF;PL
ombudsmand	ombudsmand	N;NOM;INDF;SG
vals	valsen	N;NOM;DEF;SG
dun	duns	N;GEN;INDF;SG
tid	tiden	N;NOM;DEF;SG
kolibri	kolibrien	N;NOM;DEF;SG
telefonboks	telefonbokse	N;NOM;INDF;PL
spilkarakter	spilkarakteren	N;NOM;DEF;SG
entalpi	entalpiers	N;GEN;INDF;PL
genvej	genvejs	N;GEN;INDF;SG
kanonkugle	kanonkugler	N;NOM;INDF;PL
udråbsord	udråbsordene	N;NOM;DEF;PL
kønsord	kønsordet	N;NOM;DEF;SG
dyste	dystende	V.PTCP;PRS;ACT
operahus	operahuse	N;NOM;INDF;PL
kammer	kammer	N;NOM;INDF;SG
kronprinsesse	kronprinsessernes	N;NOM;DEF;PL
kardon	kardons	N;GEN;INDF;SG
ordsprog	ordsprog	N;NOM;INDF;SG
knap	knappen	N;NOM;DEF;SG
ork	orker	N;NOM;INDF;PL
fluesmækker	fluesmækkerens	N;NOM;DEF;SG
apanage	apanages	N;GEN;INDF;SG
pokerfjæs	pokerfjæs'	N;GEN;INDF;SG
filet	filet	N;NOM;INDF;SG
accelerere	accelererende	V.PTCP;PRS;ACT
tyver	tyverens	N;NOM;DEF;SG
forbrydelse	forbrydelse	N;NOM;INDF;SG
begivenhed	begivenheds	N;GEN;INDF;SG
porøsitet	porøsiteternes	N;NOM;DEF;PL
albatros	albatros'	N;GEN;INDF;SG
dynasti	dynastis	N;GEN;INDF;SG
gemytlighed	gemytlighedernes	N;NOM;DEF;PL
bæk	bækkes	N;GEN;INDF;PL
brandert	branderters	N;GEN;INDF;PL
markere	markerer	V;IND;PRS;ACT
bilvask	bilvask	N;NOM;INDF;SG
frænke	frænken	N;NOM;DEF;SG
baby-sitter	baby-sitterene	N;NOM;DEF;PL
blodåre	blodårer	N;NOM;INDF;PL
vinkelhalveringslinie	vinkelhalveringsliniers	N;GEN;INDF;PL
kildekode	kildekode	N;NOM;INDF;SG
computerspilfigur	computerspilfigurers	N;GEN;INDF;PL
autorisation	autorisationens	N;NOM;DEF;SG
horoskop	horoskopernes	N;NOM;DEF;PL
mp3-afspiller	mp3-afspillere	N;NOM;INDF;PL
proton	protoners	N;GEN;INDF;PL
musikpædagog	musikpædagogen	N;NOM;DEF;SG
skrivemaskine	skrivemaskiner	N;NOM;INDF;PL
omelet	omelettens	N;NOM;DEF;SG
urin	uriner	N;NOM;INDF;PL
dyne	dynes	N;GEN;INDF;SG
nøddeskal	nøddeskals	N;GEN;INDF;SG
henvendelse	henvendelser	N;NOM;INDF;PL
teater	teatrenes	N;NOM;DEF;PL
bevis	beviset	N;NOM;DEF;SG
kno	knoens	N;NOM;DEF;SG
collie	colliens	N;NOM;DEF;SG
arrigtrold	arrigtrolde	N;NOM;INDF;PL
pupil	pupillerne	N;NOM;DEF;PL
grønsag	grønsagens	N;NOM;DEF;SG
forsøg	forsøgets	N;NOM;DEF;SG
spisebord	spisebordes	N;GEN;INDF;PL
nidstirre	nidstirrende	V.PTCP;PRS;ACT
fjernsyn	fjernsynene	N;NOM;DEF;PL
fælled	fælleden	N;NOM;DEF;SG
hø	høs	N;GEN;INDF;PL
tåge	tåges	N;GEN;INDF;SG
peberkværn	peberkværne	N;NOM;INDF;PL
bombe	bombernes	N;NOM;DEF;PL
afholdsmand	afholdsmændenes	N;NOM;DEF;PL
recept	recepten	N;NOM;DEF;SG
løb	løb	N;NOM;INDF;PL
pengepung	pengepungen	N;NOM;DEF;SG
metallurg	metallurgerne	N;NOM;DEF;PL
flagermus	flagermusens	N;NOM;DEF;SG
svækling	svækling	N;NOM;INDF;SG
udrensning	udrensnings	N;GEN;INDF;SG
dryp	dryp	N;NOM;INDF;SG
gudshus	gudshuses	N;GEN;INDF;PL
ærinde	ærinderne	N;NOM;DEF;PL
kokkepige	kokkepiges	N;GEN;INDF;SG
akronym	akronymerne	N;NOM;DEF;PL
diagram	diagrammerne	N;NOM;DEF;PL
studium	studiets	N;NOM;DEF;SG
idyl	idyller	N;NOM;INDF;PL
bibliofil	bibliofiler	N;NOM;INDF;PL
dodekaeder	dodekaedrenes	N;NOM;DEF;PL
pind	pindenes	N;NOM;DEF;PL
akronym	akronymer	N;NOM;INDF;PL
adgangskode	adgangskodens	N;NOM;DEF;SG
rygsøjle	rygsøjlens	N;NOM;DEF;SG
strømpe	strømpernes	N;NOM;DEF;PL
myndighedsrepræsentant	myndighedsrepræsentant	N;NOM;INDF;SG
parkere	parkeredes	V;IND;PST;PASS
elfenbenstårn	elfenbenstårnenes	N;NOM;DEF;PL
fodre	fodrende	V.PTCP;PRS;ACT
is	isenes	N;NOM;DEF;PL
fodre	fodr	V;IMP;ACT
komikerduo	komikerduoerne	N;NOM;DEF;PL
mentor	mentorer	N;NOM;INDF;PL
professionshøjskole	professionshøjskole	N;NOM;INDF;SG
forkortning	forkortningens	N;NOM;DEF;SG
landsbytosse	landsbytosser	N;NOM;INDF;PL
fætter	fætrene	N;NOM;DEF;PL
ventilere	ventiler	V;IMP;ACT
assimilere	assimileret	V.PTCP;PST;PASS
putte	putten	N;NOM;DEF;SG
børnehave	børnehavernes	N;NOM;DEF;PL
topograf	topografer	N;NOM;INDF;PL
advent	adventernes	N;NOM;DEF;PL
sejle	sejle	V;NFIN;ACT
stegepande	stegepandens	N;NOM;DEF;SG
trillebør	trillebørs	N;GEN;INDF;SG
hassel	haslers	N;GEN;INDF;PL
stedord	stedordenes	N;NOM;DEF;PL
rensdyr	rensdyrets	N;NOM;DEF;SG
folkehøjskole	folkehøjskolers	N;GEN;INDF;PL
dråbe	dråberne	N;NOM;DEF;PL
jordnøddeolie	jordnøddeolierne	N;NOM;DEF;PL
medaljon	medaljonerne	N;NOM;DEF;PL
komtesse	komtessens	N;NOM;DEF;SG
punkt	punkts	N;GEN;INDF;SG
fyrfadslys	fyrfadslys	N;NOM;INDF;SG
general	generalers	N;GEN;INDF;PL
distance	distancernes	N;NOM;DEF;PL
ørken	ørkenernesørknernes	N;NOM;DEF;PL
pig	piggen	N;NOM;DEF;SG
ragout	ragouter	N;NOM;INDF;PL
manuskript	manuskripters	N;GEN;INDF;PL
definere	definerede	V;IND;PST;ACT
karamel	karamels	N;GEN;INDF;SG
kasse	kassernes	N;NOM;DEF;PL
diagonal	diagonalens	N;NOM;DEF;SG
gondol	gondolens	N;NOM;DEF;SG
hæle	hæles	V;IND;PRS;PASS
pølse	pølsers	N;GEN;INDF;PL
nomade	nomaderne	N;NOM;DEF;PL
engel	englene	N;NOM;DEF;PL
ændringsforslag	ændringsforslaget	N;NOM;DEF;SG
sandsæk	sandsækkens	N;NOM;DEF;SG
bistro	bistro	N;NOM;INDF;SG
vinter	vinter	N;NOM;INDF;SG
solsystem	solsystemerne	N;NOM;DEF;PL
udsagnsord	udsagnsords	N;GEN;INDF;PL
dekagram	dekagram	N;NOM;INDF;PL
entalpi	entalpiernes	N;NOM;DEF;PL
kalkun	kalkunens	N;NOM;DEF;SG
solsikkeolie	solsikkeoliernes	N;NOM;DEF;PL
voldtægt	voldtægternes	N;NOM;DEF;PL
propel	propellen	N;NOM;DEF;SG
møl	møllet	N;NOM;DEF;SG
opgave	opgavens	N;NOM;DEF;SG
musical	musicalers	N;GEN;INDF;PL
fugleskræmsel	fugleskræmsler	N;NOM;INDF;PL
ketsjer	ketsjers	N;GEN;INDF;SG
hellebard	hellebarders	N;GEN;INDF;PL
stødtand	stødtands	N;GEN;INDF;SG
brandbil	brandbils	N;GEN;INDF;SG
gudbarn	gudbørnenes	N;NOM;DEF;PL
brosten	brosten	N;NOM;INDF;SG
bengel	bengels	N;GEN;INDF;SG
anonymisere	anonymisere	V;NFIN;ACT
væg	vægs	N;GEN;INDF;SG
hormon	hormonerne	N;NOM;DEF;PL
stol	stol	N;NOM;INDF;SG
kvotient	kvotienternes	N;NOM;DEF;PL
kasseapparat	kasseapparatet	N;NOM;DEF;SG
komposition	kompositions	N;GEN;INDF;SG
strygejern	strygejernene	N;NOM;DEF;PL
urinrør	urinrørs	N;GEN;INDF;SG
hellebard	hellebarden	N;NOM;DEF;SG
ribs	ribsene	N;NOM;DEF;PL
motorcykel	motorcyklers	N;GEN;INDF;PL
viser	viser	N;NOM;INDF;SG
mobiltelefon	mobiltelefonens	N;NOM;DEF;SG
bogorm	bogormen	N;NOM;DEF;SG
tidspunkt	tidspunkter	N;NOM;INDF;PL
kernekraft	kernekrafters	N;GEN;INDF;PL
bi	bier	N;NOM;INDF;PL
horoskop	horoskopets	N;NOM;DEF;SG
påske	påskers	N;GEN;INDF;PL
grube	grubernes	N;NOM;DEF;PL
alter	altres	N;GEN;INDF;PL
novelle	noveller	N;NOM;INDF;PL
bibel	biblensbibelens	N;NOM;DEF;SG
plov	plovs	N;GEN;INDF;SG
encyklopædi	encyklopædiens	N;NOM;DEF;SG
aften	aftenensaftnens	N;NOM;DEF;SG
enebarn	enebørnene	N;NOM;DEF;PL
partner	partner	N;NOM;INDF;SG
pornograf	pornografers	N;GEN;INDF;PL
firkant	firkanternes	N;NOM;DEF;PL
appelsin	appelsiner	N;NOM;INDF;PL
cigaretskod	cigaretskoddets	N;NOM;DEF;SG
dekoration	dekorationerne	N;NOM;DEF;PL
gamer	gamernes	N;NOM;DEF;PL
sorteringsmaskine	sorteringsmaskinernes	N;NOM;DEF;PL
stab	stabe	N;NOM;INDF;PL
urinrør	urinrørets	N;NOM;DEF;SG
eddike	eddike	N;NOM;INDF;SG
superorganisme	superorganismen	N;NOM;DEF;SG
stad	stadens	N;NOM;DEF;SG
musket	musketten	N;NOM;DEF;SG
broccoli	broccolien	N;NOM;DEF;SG
fodboldspiller	fodboldspillerens	N;NOM;DEF;SG
snor	snorens	N;NOM;DEF;SG
arne	arnens	N;NOM;DEF;SG
kakerlak	kakerlakker	N;NOM;INDF;PL
massakre	massakres	N;GEN;INDF;SG
halvbror	halvbrødrene	N;NOM;DEF;PL
mellemniveau	mellemniveauers	N;GEN;INDF;PL
skåle	skåledes	V;IND;PST;PASS
krokodilletåre	krokodilletårer	N;NOM;INDF;PL
bankkonto	bankkontoers	N;GEN;INDF;PL
bidrag	bidrags	N;GEN;INDF;PL
gedde	gedders	N;GEN;INDF;PL
rude	rudernes	N;NOM;DEF;PL
rovfugl	rovfugl	N;NOM;INDF;SG
torturere	torturerede	V;IND;PST;ACT
operahus	operahusenes	N;NOM;DEF;PL
elg	elges	N;GEN;INDF;PL
guldfisk	guldfisks	N;GEN;INDF;SG
database	databases	N;GEN;INDF;SG
terapi	terapis	N;GEN;INDF;SG
svensker	svensker	N;NOM;INDF;SG
opfostre	opfostret	V.PTCP;PST;PASS
rundsav	rundsavens	N;NOM;DEF;SG
metafor	metaforens	N;NOM;DEF;SG
differensrække	differensrækkes	N;GEN;INDF;SG
pessimist	pessimisternes	N;NOM;DEF;PL
æggestok	æggestokkenes	N;NOM;DEF;PL
rædsel	rædslers	N;GEN;INDF;PL
vandrør	vandrørs	N;GEN;INDF;SG
perle	perles	N;GEN;INDF;SG
kænguru	kænguruers	N;GEN;INDF;PL
rekviem	rekviemmets	N;NOM;DEF;SG
bøn	bønnen	N;NOM;DEF;SG
adjektiv	adjektivers	N;GEN;INDF;PL
gevinst	gevinsts	N;GEN;INDF;SG
loppe	loppe	N;NOM;INDF;SG
begivenhed	begivenhed	N;NOM;INDF;SG
fugleskræmsel	fugleskræmslet	N;NOM;DEF;SG
skåning	skåninger	N;NOM;INDF;PL
guddom	guddommens	N;NOM;DEF;SG
stegepande	stegepande	N;NOM;INDF;SG
tronarving	tronarvinger	N;NOM;INDF;PL
øgenavn	øgenavnets	N;NOM;DEF;SG
helhest	helhest	N;NOM;INDF;SG
kolli	kollienes	N;NOM;DEF;PL
forsikring	forsikrings	N;GEN;INDF;SG
central	centralers	N;GEN;INDF;PL
foderbræt	foderbrætters	N;GEN;INDF;PL
skede	skeders	N;GEN;INDF;PL
natugle	natuglen	N;NOM;DEF;SG
enzym	enzym	N;NOM;INDF;SG
gratismagasin	gratismagasiners	N;GEN;INDF;PL
partikel	partikels	N;GEN;INDF;SG
agern	agern	N;NOM;INDF;PL
frimurer	frimurers	N;GEN;INDF;SG
missekat	missekattenes	N;NOM;DEF;PL
gerningsmand	gerningsmænd	N;NOM;INDF;PL
emblem	emblemernes	N;NOM;DEF;PL
graver	graveren	N;NOM;DEF;SG
komodovaran	komodovaraner	N;NOM;INDF;PL
data	dataene	N;NOM;DEF;PL
bordel	bordellers	N;GEN;INDF;PL
ørken	ørkenensørknens	N;NOM;DEF;SG
effekt	effekts	N;GEN;INDF;SG
ophavsgruppe	ophavsgruppens	N;NOM;DEF;SG
brudepige	brudepigers	N;GEN;INDF;PL
solnedgang	solnedgangenes	N;NOM;DEF;PL
akronym	akronym	N;NOM;INDF;SG
assimilere	assimilerede	V;IND;PST;ACT
musketer	musketerens	N;NOM;DEF;SG
ør	øren	N;NOM;DEF;SG
foto	fotoets	N;NOM;DEF;SG
udseende	udseendernes	N;NOM;DEF;PL
foster	fostret	N;NOM;DEF;SG
bighornfår	bighornfårs	N;GEN;INDF;SG
pokerfjæs	pokerfjæset	N;NOM;DEF;SG
dukke	dukkernes	N;NOM;DEF;PL
stofmisbrug	stofmisbrug	N;NOM;INDF;PL
anonymisere	anonymiser	V;IMP;ACT
mængde	mængders	N;GEN;INDF;PL
operere	opererende	V.PTCP;PRS;ACT
munk	munkene	N;NOM;DEF;PL
liechtensteiner	liechtensteineren	N;NOM;DEF;SG
stødtand	stødtanden	N;NOM;DEF;SG
hormon	hormon	N;NOM;INDF;SG
bistro	bistroens	N;NOM;DEF;SG
køretøj	køretøjerne	N;NOM;DEF;PL
ydelse	ydelse	N;NOM;INDF;SG
bibel	biblenbibelen	N;NOM;DEF;SG
virkning	virkning	N;NOM;INDF;SG
udråbstegn	udråbstegnet	N;NOM;DEF;SG
deisme	deismerne	N;NOM;DEF;PL
foderbræt	foderbræts	N;GEN;INDF;SG
solsort	solsorterne	N;NOM;DEF;PL
halvmåne	halvmånens	N;NOM;DEF;SG
mund	mundenes	N;NOM;DEF;PL
erfare	erfaredes	V;IND;PST;PASS
malm	malmes	N;GEN;INDF;PL
sav	savens	N;NOM;DEF;SG
knor	knor	N;NOM;INDF;SG
humanist	humanist	N;NOM;INDF;SG
yver	yverets	N;NOM;DEF;SG
hoppe	hopper	N;NOM;INDF;PL
flygel	flygels	N;GEN;INDF;SG
troubadur	troubadurerne	N;NOM;DEF;PL
gærdesmutte	gærdesmutternes	N;NOM;DEF;PL
medium	mediets	N;NOM;DEF;SG
vogn	vognenes	N;NOM;DEF;PL
tidspunkt	tidspunktets	N;NOM;DEF;SG
ærkeengel	ærkeengles	N;GEN;INDF;PL
hjertestop	hjertestop	N;NOM;INDF;PL
hindbærsnitte	hindbærsnitterne	N;NOM;DEF;PL
lunte	luntes	N;GEN;INDF;SG
kanelsnegl	kanelsnegle	N;NOM;INDF;PL
øjenbryn	øjenbrynet	N;NOM;DEF;SG
palaver	palaveres	N;GEN;INDF;PL
overskæg	overskæg	N;NOM;INDF;PL
tegnefilm	tegnefilms	N;GEN;INDF;SG
håndklæde	håndklædet	N;NOM;DEF;SG
bilist	bilists	N;GEN;INDF;SG
cigaret	cigaretter	N;NOM;INDF;PL
trekant	trekanter	N;NOM;INDF;PL
tibetaner	tibetaneres	N;GEN;INDF;PL
album	albummets	N;NOM;DEF;SG
spænding	spændingen	N;NOM;DEF;SG
fællesmængde	fællesmængderne	N;NOM;DEF;PL
intelligensniveau	intelligensniveauerne	N;NOM;DEF;PL
trafiklys	trafiklysers	N;GEN;INDF;PL
kirtel	kirtlers	N;GEN;INDF;PL
salme	salmerne	N;NOM;DEF;PL
suppe	suppernes	N;NOM;DEF;PL
snebold	snebolden	N;NOM;DEF;SG
skåning	skåningerne	N;NOM;DEF;PL
frygte	frygtet	V.PTCP;PST;PASS
frænke	frænkerne	N;NOM;DEF;PL
efterår	efteråret	N;NOM;DEF;SG
svensker	svenskeren	N;NOM;DEF;SG
orientering	orienteringerne	N;NOM;DEF;PL
øgle	øglens	N;NOM;DEF;SG
klare	klaret	V.PTCP;PST;PASS
nul	nullerne	N;NOM;DEF;PL
erektion	erektionernes	N;NOM;DEF;PL
radiobil	radiobilen	N;NOM;DEF;SG
altan	altanerne	N;NOM;DEF;PL
flåde	flåde	N;NOM;INDF;SG
pig	piggenes	N;NOM;DEF;PL
enkemand	enkemænds	N;GEN;INDF;PL
kernekraft	kernekraften	N;NOM;DEF;SG
diagram	diagrammernes	N;NOM;DEF;PL
ironi	ironi	N;NOM;INDF;SG
hundestejle	hundestejle	N;NOM;INDF;SG
bombe	bomben	N;NOM;DEF;SG
brandbil	brandbilers	N;GEN;INDF;PL
oldemor	oldemødres	N;GEN;INDF;PL
mule	mule	N;NOM;INDF;SG
æggestok	æggestokkes	N;GEN;INDF;PL
sektor	sektorerne	N;NOM;DEF;PL
laste	lastede	V;IND;PST;ACT
nav	navs	N;GEN;INDF;SG
voldtægtsmand	voldtægtsmandens	N;NOM;DEF;SG
søndag	søndags	N;GEN;INDF;SG
mafia	mafiaerne	N;NOM;DEF;PL
citat	citat	N;NOM;INDF;SG
polemik	polemiks	N;GEN;INDF;SG
graver	gravere	N;NOM;INDF;PL
hypotese	hypotesens	N;NOM;DEF;SG
landmand	landmandens	N;NOM;DEF;SG
mikrobølge	mikrobølges	N;GEN;INDF;SG
nul	nullet	N;NOM;DEF;SG
nakke	nakkers	N;GEN;INDF;PL
herbivor	herbivorers	N;GEN;INDF;PL
høretelefon	høretelefoner	N;NOM;INDF;PL
avocado	avocadoer	N;NOM;INDF;PL
hyæne	hyænes	N;GEN;INDF;SG
forsørger	forsørgers	N;GEN;INDF;SG
frier	frierens	N;NOM;DEF;SG
dehydrere	dehydrere	V;NFIN;ACT
fingerspids	fingerspidser	N;NOM;INDF;PL
kanelsnegl	kanelsnegls	N;GEN;INDF;SG
apropos	apropos	N;NOM;INDF;SG
sekant	sekanter	N;NOM;INDF;PL
gondol	gondolerne	N;NOM;DEF;PL
vinkelhalveringslinie	vinkelhalveringslinier	N;NOM;INDF;PL
hvepsetalje	hvepsetaljernes	N;NOM;DEF;PL
eddike	eddikerne	N;NOM;DEF;PL
korrigere	korriger	V;IMP;ACT
medaljon	medaljoner	N;NOM;INDF;PL
middelhav	middelhavs	N;GEN;INDF;SG
valg	valget	N;NOM;DEF;SG
stedord	stedord	N;NOM;INDF;SG
skotte	skotte	N;NOM;INDF;SG
selvportræt	selvportrætternes	N;NOM;DEF;PL
musketer	musketers	N;GEN;INDF;SG
lunde	lunderne	N;NOM;DEF;PL
vandrør	vandrørs	N;GEN;INDF;PL
intimidere	intimidere	V;NFIN;ACT
afpresning	afpresningerne	N;NOM;DEF;PL
ludder	ludder	N;NOM;INDF;SG
sovepose	sovepose	N;NOM;INDF;SG
fingerspids	fingerspidsen	N;NOM;DEF;SG
stigma	stigmataenes	N;NOM;DEF;PL
spurv	spurve	N;NOM;INDF;PL
tyv	tyves	N;GEN;INDF;PL
guddom	guddommene	N;NOM;DEF;PL
vask	vaskenes	N;NOM;DEF;PL
præposition	præpositioner	N;NOM;INDF;PL
østkyst	østkysten	N;NOM;DEF;SG
navne	navners	N;GEN;INDF;PL
ubåd	ubådene	N;NOM;DEF;PL
D-mark	D-markens	N;NOM;DEF;SG
danse	dansedes	V;IND;PST;PASS
succes	succeserne	N;NOM;DEF;PL
parkere	parkeres	V;IND;PRS;PASS
bibliofil	bibliofilernes	N;NOM;DEF;PL
halvtredser	halvtredsernes	N;NOM;DEF;PL
antonym	antonyms	N;GEN;INDF;SG
bregne	bregnernes	N;NOM;DEF;PL
Wikipediabrugerside	Wikipediabrugersiden	N;NOM;DEF;SG
kind	kinderne	N;NOM;DEF;PL
terræn	terræner	N;NOM;INDF;PL
refraktion	refraktioner	N;NOM;INDF;PL
bogstav	bogstavs	N;GEN;INDF;SG
hæle	hæler	V;IND;PRS;ACT
luftkastel	luftkastellers	N;GEN;INDF;PL
konserveringsmiddel	konserveringsmiddel	N;NOM;INDF;SG
soldug	solduggens	N;NOM;DEF;SG
kolos	kolosserne	N;NOM;DEF;PL
kejserpingvin	kejserpingvins	N;GEN;INDF;SG
recept	recepternes	N;NOM;DEF;PL
wc-rulle	wc-rullernes	N;NOM;DEF;PL
kutyme	kutymen	N;NOM;DEF;SG
konspirationsteori	konspirationsteoris	N;GEN;INDF;SG
kakofoni	kakofoniens	N;NOM;DEF;SG
kål	kålenes	N;NOM;DEF;PL
grube	grubens	N;NOM;DEF;SG
kreds	kreds'	N;GEN;INDF;SG
pyton	pytonernes	N;NOM;DEF;PL
nederdel	nederdeles	N;GEN;INDF;PL
tagetes	tagetesens	N;NOM;DEF;SG
musket	musketters	N;GEN;INDF;PL
fasan	fasanen	N;NOM;DEF;SG
antonym	antonymers	N;GEN;INDF;PL
bordeaux	bordeaux	N;NOM;INDF;SG
spytkirtel	spytkirtel	N;NOM;INDF;SG
galleri	gallerierne	N;NOM;DEF;PL
ged	gederne	N;NOM;DEF;PL
bon	boner	N;NOM;INDF;PL
hane	hanen	N;NOM;DEF;SG
database	databasers	N;GEN;INDF;PL
arrigtrold	arrigtrolds	N;GEN;INDF;SG
handler	handlernes	N;NOM;DEF;PL
underlag	underlag	N;NOM;INDF;SG
foderbræt	foderbrætter	N;NOM;INDF;PL
massefylde	massefylde	N;NOM;INDF;SG
heltinde	heltinden	N;NOM;DEF;SG
kamæleon	kamæleoner	N;NOM;INDF;PL
massefylde	massefyldens	N;NOM;DEF;SG
puslespil	puslespillenes	N;NOM;DEF;PL
is	is'	N;GEN;INDF;PL
arbejdsgiver	arbejdsgiver	N;NOM;INDF;SG
pronomen	pronomenernes	N;NOM;DEF;PL
brudepige	brudepigerne	N;NOM;DEF;PL
tjeneste	tjenesters	N;GEN;INDF;PL
sild	sildenes	N;NOM;DEF;PL
palisade	palisadens	N;NOM;DEF;SG
tyd	tydene	N;NOM;DEF;PL
konservator	konservatorerne	N;NOM;DEF;PL
barnesoldat	barnesoldaternes	N;NOM;DEF;PL
hobby	hobbyens	N;NOM;DEF;SG
issyl	issyles	N;GEN;INDF;PL
reservere	reserveres	V;IND;PRS;PASS
troubadur	troubadurernes	N;NOM;DEF;PL
kværke	kværket	V.PTCP;PST;PASS
vittighed	vittigheders	N;GEN;INDF;PL
bighornfår	bighornfårets	N;NOM;DEF;SG
broderskab	broderskabernes	N;NOM;DEF;PL
trold	troldens	N;NOM;DEF;SG
butterfly	butterflyens	N;NOM;DEF;SG
genstand	genstands	N;GEN;INDF;SG
fugleskræmsel	fugleskræmslets	N;NOM;DEF;SG
autofokus	autofokusser	N;NOM;INDF;PL
hvirveldyr	hvirveldyrenes	N;NOM;DEF;PL
