vulgair	vulgaire	ADJ;INDF;PL
printen	printte	V;SBJV;SG;PST
versoepelen	versoepelden	V;SBJV;PL;PST
braden	braden	V;NFIN
nemen	namen	V;IND;PL;PST
trillen	trilt	V;IMP;PL
bijdehand	bijdehanter	ADJ;CMPR;INDF;PL
ontluiken	ontluik	V;IMP;SG
gisten	gistten	V;SBJV;PL;PST
sektarisch	sektarischte	ADJ;SPRL;INDF;PL
versperren	verspert	V;IMP;PL
boeten	boet	V;IMP;PL
verteren	verteerden	V;IND;PL;PST
faxen	faxt	V;IMP;PL
vermelden	vermeldt	V;IND;SG;2;PRS
scherpen	scherpten	V;IND;PL;PST
adstrueren	adstrueerde	V;SBJV;SG;PST
veulendragend	veulendragendere	ADJ;CMPR;INDF;PL
overzichtelijk	overzichtelijkste	ADJ;SPRL;DEF
hemelsblauw	hemelsblauwere	ADJ;SPRL;INDF;NEUT;SG
bezwendelen	bezwendelen	V;SBJV;PL;PRS
dommelen	dommelden	V;SBJV;PL;PST
onbruikbaar	onbruikbaarste	ADJ;SPRL;DEF
vlezig	vlezig	ADJ;INDF;NEUT;SG
spoedig	spoedigste	ADJ;SPRL;INDF;PL
nomineren	nominere	V;SBJV;SG;PRS
lijden	lijdt	V;IND;SG;3;PRS
zingen	zonge	V;SBJV;SG;PST
schroeien	schroeiden	V;IND;PL;PST
Nederlands	Nederlandser	ADJ;CMPR;INDF;PL
Mongools	Mongoolser	ADJ;CMPR;INDF;PL
bemoedigen	bemoedigen	V;IND;PL;PRS
angstig	angstige	ADJ;CMPR;INDF;NEUT;SG
portretteren	portretteert	V;IND;SG;3;PRS
maskeren	maskert	V;IMP;PL
aangeschoten	aangeschoten	ADJ;CMPR;INDF;NEUT;SG
begrenzen	begrensde	V;SBJV;SG;PST
geregeld	geregeld	ADJ;INDF;NEUT;SG
projecteren	projecteerde	V;SBJV;SG;PST
eentonig	eentonige	ADJ;INDF;PL
vergrendelen	vergrendelde	V;IND;SG;1;PST
aannemelijk	aannemelijke	ADJ;DEF
duimen	geduimd	V.PTCP;PST
gammel	gammele	ADJ;DEF
decoderen	decodeerden	V;IND;PL;PST
langwerpig	langwerpigere	ADJ;CMPR;DEF
helpen	help	V;IMP;SG
verschuilen	verscholen	V;SBJV;PL;PST
schoeien	schoeie	V;SBJV;SG;PRS
incongruent	incongruente	ADJ;CMPR;INDF;NEUT;SG
drammerig	drammerigste	ADJ;SPRL;INDF;PL
toosten	toostte	V;IND;SG;2;PST
jeuken	jeukten	V;SBJV;PL;PST
anarchistisch	anarchistischere	ADJ;SPRL;INDF;NEUT;SG
glad	gladder	ADJ;CMPR;INDF;PL
kwaadwillend	kwaadwillendste	ADJ;SPRL;INDF;PL
schuwen	schuw	V;IMP;SG
poetsen	poetsen	V;IND;PL;PRS
schromen	schroom	V;IMP;SG
meewarig	meewarig	ADJ;INDF;NEUT;SG
verordonneren	verordonneert	V;IMP;PL
integer	integere	ADJ;DEF
bespringen	besprong	V;IND;SG;2;PST
sloffen	slofte	V;IND;SG;3;PST
gebaren	gebaren	V;NFIN
intrigeren	intrigeer	V;IMP;SG
verrassen	verraste	V;IND;SG;1;PST
zwiepen	gezwiept	V.PTCP;PST
neigen	neigde	V;IND;SG;2;PST
verhapstukken	verhapstukten	V;IND;PL;PST
corresponderen	corresponderen	V;SBJV;PL;PRS
bedanken	bedankte	V;SBJV;SG;PST
verwoorden	verwoordt	V;IND;SG;2;PRS
hardnekkig	hardnekkigere	ADJ;CMPR;DEF
zeker	zekere	ADJ;INDF;PL
veroveren	veroverden	V;IND;PL;PST
Katangees	Katangees	ADJ;INDF;NEUT;SG
infernaal	infernaalere	ADJ;SPRL;INDF;NEUT;SG
beslaan	besloegen	V;IND;PL;PST
eigentijds	eigentijdse	ADJ;DEF
inspireren	inspireerde	V;SBJV;SG;PST
levenloos	levenlozer	ADJ;CMPR;INDF;PL
ontspringen	ontspringe	V;SBJV;SG;PRS
absoluut	absolutere	ADJ;SPRL;INDF;NEUT;SG
gebrekkig	gebrekkigere	ADJ;CMPR;DEF
registreren	geregistreerd	V.PTCP;PST
verwekken	verwekte	V;IND;SG;1;PST
wonen	woonden	V;SBJV;PL;PST
vellen	vellen	V;SBJV;PL;PRS
vuisten	vuiste	V;SBJV;SG;PRS
kaatsen	kaatste	V;IND;SG;2;PST
ontregelen	ontregelt	V;IMP;PL
stadig	stadig	ADJ;INDF;NEUT;SG
optimaliseren	optimaliseerde	V;SBJV;SG;PST
ontbloten	ontblote	V;SBJV;SG;PRS
ontroostbaar	ontroostbaarste	ADJ;SPRL;DEF
passeren	passeren	V;IND;PL;PRS
kortelings	kortelings	ADJ;INDF;NEUT;SG
hecht	hechtere	ADJ;SPRL;INDF;NEUT;SG
wenen	weende	V;IND;SG;3;PST
schattig	schattiger	ADJ;CMPR;INDF;PL
verzwinden	verzwindt	V;IND;SG;2;PRS
ontbieden	ontbood	V;IND;SG;1;PST
sabbelen	sabbelt	V;IND;SG;2;PRS
failliet	faillietste	ADJ;SPRL;DEF
beschaven	beschaaft	V;IMP;PL
kortademig	kortademige	ADJ;DEF
respectabel	respectabelere	ADJ;CMPR;DEF
ritmisch	ritmischer	ADJ;CMPR;INDF;PL
legitimeren	legitimeert	V;IND;SG;3;PRS
lijden	lijd	V;IMP;SG
nauwkeurig	nauwkeurige	ADJ;DEF
betamen	betaam	V;IND;SG;1;PRS
bevorderlijk	bevorderlijkste	ADJ;SPRL;INDF;PL
lusteloos	lustelooste	ADJ;SPRL;DEF
spreken	sprak	V;IND;SG;3;PST
finishen	finishte	V;IND;SG;1;PST
verschrijven	verschrijf	V;IND;SG;1;PRS
bezweet	bezweetere	ADJ;SPRL;INDF;NEUT;SG
schakelen	schakel	V;IND;SG;1;PRS
voeden	voed	V;IMP;SG
futloos	futlozere	ADJ;CMPR;DEF
omwikkelen	omwikkelde	V;IND;SG;2;PST
verhuizen	verhuist	V;IND;SG;2;PRS
vermoeien	vermoeien	V;IND;PL;PRS
huiken	huikt	V;IND;SG;3;PRS
vervuilen	vervuilden	V;IND;PL;PST
belemmeren	belemmert	V;IND;SG;2;PRS
reconstrueren	reconstrueren	V;NFIN
gekeerd	gekeerdste	ADJ;SPRL;INDF;PL
Noords	Noordste	ADJ;SPRL;INDF;NEUT;SG
kakken	kakte	V;IND;SG;2;PST
declareren	declareerden	V;SBJV;PL;PST
verenigen	verenigde	V;IND;SG;1;PST
destilleren	destilleer	V;IMP;SG
excessief	excessieve	ADJ;CMPR;INDF;NEUT;SG
doodeenvoudig	doodeenvoudigste	ADJ;SPRL;INDF;PL
computeren	computere	V;SBJV;SG;PRS
algebraïsch	algebraïschere	ADJ;CMPR;DEF
zinloos	zinlozer	ADJ;CMPR;INDF;PL
memorabel	memorabelste	ADJ;SPRL;INDF;PL
brak	brakker	ADJ;CMPR;INDF;PL
borgen	borgde	V;IND;SG;3;PST
beklagenswaardig	beklagenswaardigere	ADJ;CMPR;DEF
amechtig	amechtigste	ADJ;SPRL;DEF
Assamees	Assameeste	ADJ;SPRL;INDF;PL
koralen	koralen	ADJ;INDF;PL
landen	landden	V;IND;PL;PST
prominent	prominentste	ADJ;SPRL;DEF
mompelen	mompelt	V;IMP;PL
keurig	keurige	ADJ;DEF
formeren	formeerden	V;IND;PL;PST
verafschuwen	verafschuwden	V;IND;PL;PST
verenigbaar	verenigbare	ADJ;DEF
verenigbaar	verenigbaarder	ADJ;CMPR;INDF;PL
lukraak	lukraker	ADJ;CMPR;INDF;PL
finishen	finisht	V;IND;SG;2;PRS
blozen	gebloosd	V.PTCP;PST
noordelijk	noordelijke	ADJ;INDF;PL
gewagen	gewagen	V;SBJV;PL;PRS
onthalen	onthalen	V;SBJV;PL;PRS
onbezonnen	onbezonnen	ADJ;INDF;PL
bekronen	bekroonde	V;IND;SG;2;PST
generiek	generiekste	ADJ;SPRL;DEF
ontrafelen	ontrafel	V;IND;SG;1;PRS
hameren	hamert	V;IND;SG;3;PRS
adoreren	adoreren	V;SBJV;PL;PRS
onbeschaafd	onbeschaafdste	ADJ;SPRL;DEF
mislukken	mislukten	V;SBJV;PL;PST
beschaamd	beschaamde	ADJ;DEF
beklemmen	beklem	V;IND;SG;1;PRS
ootmoedig	ootmoedige	ADJ;CMPR;INDF;NEUT;SG
monteren	gemonteerd	V.PTCP;PST
zorgen	zorg	V;IND;SG;1;PRS
overwinnen	overwint	V;IND;SG;3;PRS
brullen	brult	V;IMP;PL
schuifelen	geschuifeld	V.PTCP;PST
federaliseren	gefederaliseerd	V.PTCP;PST
hooghartig	hooghartigste	ADJ;SPRL;INDF;PL
godvruchtig	godvruchtigere	ADJ;CMPR;DEF
eindig	eindigste	ADJ;SPRL;INDF;PL
divers	diversere	ADJ;SPRL;INDF;NEUT;SG
formeren	formeerde	V;IND;SG;2;PST
viskeus	viskeuzere	ADJ;SPRL;INDF;NEUT;SG
zat	zatte	ADJ;INDF;PL
wroeten	wroet	V;IND;SG;2;PRS
heetgebakerd	heetgebakerder	ADJ;CMPR;INDF;PL
taxeren	taxere	V;SBJV;SG;PRS
vermorsen	vermorsen	V;SBJV;PL;PRS
geestelijk	geestelijke	ADJ;INDF;PL
zwetsen	zwetst	V;IMP;PL
morren	morren	V;SBJV;PL;PRS
lijnen	lijnt	V;IMP;PL
vlijmscherp	vlijmscherpere	ADJ;SPRL;INDF;NEUT;SG
verharen	verhaart	V;IMP;PL
besluipen	besluipen	V;NFIN
raadselachtig	raadselachtige	ADJ;DEF
ontdooien	ontdooid	V.PTCP;PST
stevig	stevige	ADJ;CMPR;INDF;NEUT;SG
programmeren	programmeerden	V;SBJV;PL;PST
bedompt	bedomptere	ADJ;SPRL;INDF;NEUT;SG
fabriceren	fabriceerden	V;IND;PL;PST
slingeren	slingeren	V;NFIN
afschrikwekkend	afschrikwekkendste	ADJ;SPRL;DEF
kleinzerig	kleinzerigste	ADJ;SPRL;INDF;PL
sommeren	sommeren	V;NFIN
verplanten	verplanten	V;NFIN
donkerblauw	donkerblauwer	ADJ;CMPR;INDF;PL
resulteren	resulteerde	V;SBJV;SG;PST
verfilmen	verfilm	V;IND;SG;1;PRS
gisten	gisten	V;SBJV;PL;PRS
wandelen	wandelt	V;IND;SG;2;PRS
wemelen	wemelt	V;IMP;PL
geregeld	geregeldere	ADJ;SPRL;INDF;NEUT;SG
jarig	jarige	ADJ;CMPR;INDF;NEUT;SG
ontsnappen	ontsnapt	V;IND;SG;2;PRS
brengen	bracht	V;IND;SG;2;PST
ontkoppelen	ontkoppelen	V;IND;PL;PRS
naïef	naïevere	ADJ;CMPR;DEF
projecteren	projecteren	V;IND;PL;PRS
kinderlijk	kinderlijkste	ADJ;SPRL;INDF;PL
bereikbaar	bereikbare	ADJ;CMPR;INDF;NEUT;SG
Noors	Noorse	ADJ;INDF;PL
sjokken	sjokken	V;NFIN
verwijden	verwijde	V;SBJV;SG;PRS
voetballen	voetballen	V;NFIN
repareren	reparere	V;SBJV;SG;PRS
ontkurken	ontkurk	V;IND;SG;1;PRS
prestigieus	prestigieus	ADJ;INDF;NEUT;SG
verprutsen	verprutste	V;IND;SG;3;PST
langgerekt	langgerektere	ADJ;CMPR;DEF
verdiepen	verdiepten	V;IND;PL;PST
hopen	hopen	V;NFIN
onttrekken	onttrok	V;IND;SG;2;PST
vermeend	vermeend	ADJ;INDF;NEUT;SG
behoeden	behoedt	V;IND;SG;3;PRS
vieren	vieren	V;IND;PL;PRS
sociaal	socialere	ADJ;SPRL;INDF;NEUT;SG
springen	sprongen	V;IND;PL;PST
kissebissen	kissebissen	V;NFIN
zeiknat	zeiknattere	ADJ;SPRL;INDF;NEUT;SG
klikken	klikken	V;IND;PL;PRS
beschutten	beschutte	V;SBJV;SG;PST
kotsen	kotsten	V;SBJV;PL;PST
baggeren	baggeren	V;IND;PL;PRS
betamen	betamen	V;NFIN
vlammen	vlammen	V;IND;PL;PRS
nestelen	genesteld	V.PTCP;PST
pendelen	pendelde	V;SBJV;SG;PST
hydrodynamisch	hydrodynamische	ADJ;INDF;PL
menschelijk	menschelijke	ADJ;DEF
nuttigen	nuttigt	V;IMP;PL
jatten	jatten	V;SBJV;PL;PST
onomstreden	onomstreden	ADJ;DEF
tolereren	tolereerden	V;SBJV;PL;PST
abdiceren	abdiceren	V;SBJV;PL;PRS
fataal	fatalere	ADJ;CMPR;DEF
overkoepelen	overkoepelen	V;NFIN
diepzinnig	diepzinnige	ADJ;DEF
Lets	Letser	ADJ;CMPR;INDF;PL
morren	morde	V;SBJV;SG;PST
knetteren	knetterde	V;IND;SG;1;PST
bereikbaar	bereikbaar	ADJ;INDF;NEUT;SG
vermoeden	vermoedt	V;IND;SG;3;PRS
Katangees	Katangese	ADJ;INDF;PL
orgelen	orgelt	V;IND;SG;3;PRS
dimmen	dim	V;IMP;SG
modificeren	modificeer	V;IND;SG;1;PRS
creatief	creatievere	ADJ;CMPR;DEF
bekwaam	bekwamere	ADJ;SPRL;INDF;NEUT;SG
kankeren	kankert	V;IND;SG;3;PRS
zindelijk	zindelijkere	ADJ;SPRL;INDF;NEUT;SG
zoeten	zoet	V;IMP;SG
Leids	Leidsere	ADJ;SPRL;INDF;NEUT;SG
loodrecht	loodrechte	ADJ;CMPR;INDF;NEUT;SG
specialiseren	specialiseren	V;NFIN
baggeren	baggerde	V;IND;SG;3;PST
verwarmen	verwarmt	V;IND;SG;2;PRS
surfen	surf	V;IND;SG;1;PRS
tippelen	tippelt	V;IMP;PL
ondiep	ondiepere	ADJ;SPRL;INDF;NEUT;SG
kubistisch	kubistische	ADJ;DEF
humeurig	humeurigste	ADJ;SPRL;INDF;PL
grissen	griste	V;IND;SG;1;PST
slingeren	slingert	V;IMP;PL
gehecht	gehechte	ADJ;CMPR;INDF;NEUT;SG
vermaken	vermaakten	V;IND;PL;PST
roken	rookte	V;IND;SG;3;PST
pekelen	gepekeld	V.PTCP;PST
relativeren	relativeerde	V;IND;SG;1;PST
sudderen	sudder	V;IND;SG;1;PRS
slopen	slopen	V;SBJV;PL;PRS
Spartaans	Spartaanste	ADJ;SPRL;DEF
verbinden	verbind	V;IND;SG;1;PRS
onwettig	onwettiger	ADJ;CMPR;INDF;PL
perfectioneren	perfectioneerde	V;IND;SG;3;PST
interviewen	interviewde	V;SBJV;SG;PST
ontspringen	ontspringen	V;NFIN
hechten	hechtten	V;IND;PL;PST
rapporteren	rapporteerde	V;IND;SG;2;PST
registreren	registreren	V;IND;PL;PRS
surfen	surft	V;IND;SG;2;PRS
demagogisch	demagogischere	ADJ;SPRL;INDF;NEUT;SG
angstig	angstigste	ADJ;SPRL;INDF;PL
ongeremd	ongeremdste	ADJ;SPRL;INDF;PL
rectificeren	rectificeren	V;IND;PL;PRS
herleven	herleven	V;IND;PL;PRS
ontoereikend	ontoereikende	ADJ;INDF;PL
duizelingwekkend	duizelingwekkende	ADJ;CMPR;INDF;NEUT;SG
dronken	dronkenste	ADJ;SPRL;INDF;PL
benodigen	benodigde	V;IND;SG;1;PST
verwijden	verwijdden	V;IND;PL;PST
splitsen	splitst	V;IND;SG;3;PRS
inspireren	inspirere	V;SBJV;SG;PRS
hemels	hemelse	ADJ;INDF;PL
ontvolken	ontvolkten	V;IND;PL;PST
stampvoeten	stampvoeten	V;NFIN
emulgeren	emulgeren	V;IND;PL;PRS
zappen	zapt	V;IND;SG;2;PRS
sterken	gesterkt	V.PTCP;PST
verhandelen	verhandeld	V.PTCP;PST
consolideren	consolideren	V;SBJV;PL;PRS
druppelen	gedruppeld	V.PTCP;PST
braaien	braaide	V;IND;SG;2;PST
nalatig	nalatigere	ADJ;SPRL;INDF;NEUT;SG
lusteloos	lusteloos	ADJ;INDF;NEUT;SG
categoriseren	categoriseren	V;SBJV;PL;PRS
vloeibaar	vloeibaardere	ADJ;CMPR;DEF
onzinnig	onzinnige	ADJ;INDF;PL
geleidelijk	geleidelijke	ADJ;DEF
stoken	stook	V;IMP;SG
verrijzen	verrijzen	V;NFIN
noordelijk	noordelijkere	ADJ;CMPR;DEF
debatteren	debatteert	V;IMP;PL
synthetiseren	synthetiseerde	V;IND;SG;2;PST
glooien	glooien	V;NFIN
schallen	schalde	V;IND;SG;1;PST
kalven	kalft	V;IND;SG;3;PRS
viseren	viseerden	V;SBJV;PL;PST
Dalmatisch	Dalmatischte	ADJ;SPRL;INDF;PL
betamen	betaamt	V;IMP;PL
amuseren	amuseer	V;IMP;SG
faxen	fax	V;IMP;SG
betwistbaar	betwistbaarste	ADJ;SPRL;INDF;PL
verdommen	verdomt	V;IMP;PL
vereenvoudigen	vereenvoudigde	V;SBJV;SG;PST
verstikken	verstikke	V;SBJV;SG;PRS
blunderen	blunderen	V;SBJV;PL;PRS
machteloos	machtelooste	ADJ;SPRL;INDF;PL
ongeremd	ongeremd	ADJ;INDF;NEUT;SG
merken	merken	V;IND;PL;PRS
claimen	claimen	V;NFIN
knetteren	knettert	V;IND;SG;3;PRS
sparen	spaarde	V;IND;SG;3;PST
bezuinigen	bezuinigen	V;IND;PL;PRS
nat	nattere	ADJ;CMPR;DEF
strategisch	strategischte	ADJ;SPRL;DEF
berokkenen	berokken	V;IND;SG;1;PRS
krioelen	krioelde	V;IND;SG;1;PST
vrijgevig	vrijgeviger	ADJ;CMPR;INDF;PL
stimuleren	stimuleren	V;NFIN
deporteren	deporteerde	V;SBJV;SG;PST
repareren	repareerde	V;SBJV;SG;PST
lasteren	lasterde	V;IND;SG;1;PST
graaien	graaide	V;IND;SG;2;PST
portretteren	portretteren	V;IND;PL;PRS
verenigen	verenigde	V;SBJV;SG;PST
galmen	gegalmd	V.PTCP;PST
kundig	kundige	ADJ;CMPR;INDF;NEUT;SG
vermurwen	vermurwde	V;IND;SG;2;PST
Tsjechisch	Tsjechischte	ADJ;SPRL;INDF;PL
knutselen	knutselt	V;IMP;PL
gewagen	gewaagd	V.PTCP;PST
proactief	proactiefste	ADJ;SPRL;INDF;PL
gewennen	gewenne	V;SBJV;SG;PRS
voedselrijk	voedselrijke	ADJ;CMPR;INDF;NEUT;SG
roddelen	roddele	V;SBJV;SG;PRS
accelereren	accelereert	V;IND;SG;3;PRS
beleggen	beleg	V;IMP;SG
lelijk	lelijke	ADJ;DEF
vermolmen	vermolmen	V;NFIN
veroordelen	veroordeelden	V;IND;PL;PST
organisch	organische	ADJ;DEF
obsceen	obscenere	ADJ;SPRL;INDF;NEUT;SG
delven	delven	V;NFIN
verzengen	verzengen	V;IND;PL;PRS
huiveren	huivere	V;SBJV;SG;PRS
plaatsvervangend	plaatsvervangende	ADJ;DEF
natuurlijk	natuurlijke	ADJ;INDF;PL
jatten	jatten	V;IND;PL;PRS
verlangen	verlange	V;SBJV;SG;PRS
bibberen	bibbert	V;IND;SG;2;PRS
decoratief	decoratieve	ADJ;INDF;PL
ontfutselen	ontfutsel	V;IND;SG;1;PRS
begrenzen	begrenst	V;IMP;PL
versmallen	versmal	V;IMP;SG
roodgloeiend	roodgloeiende	ADJ;CMPR;INDF;NEUT;SG
porren	porre	V;SBJV;SG;PRS
verhogen	verhoogden	V;SBJV;PL;PST
lyrisch	lyrischer	ADJ;CMPR;INDF;PL
serveren	serveert	V;IND;SG;3;PRS
exposeren	exposeren	V;NFIN
omsingelen	omsingelde	V;SBJV;SG;PST
verzoenen	verzoende	V;SBJV;SG;PST
duiden	duidden	V;SBJV;PL;PST
literair	literairste	ADJ;SPRL;DEF
bewerkelijk	bewerkelijke	ADJ;CMPR;INDF;NEUT;SG
mallen	mal	V;IND;SG;1;PRS
vermaken	vermaakt	V;IMP;PL
ruziën	ruziën	V;SBJV;PL;PRS
veropenbaren	veropenbare	V;SBJV;SG;PRS
vroom	vromere	ADJ;SPRL;INDF;NEUT;SG
belachelijk	belachelijke	ADJ;DEF
copieus	copieus	ADJ;INDF;NEUT;SG
langgerekt	langgerekte	ADJ;INDF;PL
satanisch	satanischer	ADJ;CMPR;INDF;PL
notuleren	notuleren	V;IND;PL;PRS
deplorabel	deplorabele	ADJ;CMPR;INDF;NEUT;SG
springen	spring	V;IND;SG;1;PRS
persoonlijk	persoonlijkere	ADJ;SPRL;INDF;NEUT;SG
worstelen	worstelde	V;SBJV;SG;PST
demotiveren	demotiveerde	V;IND;SG;1;PST
equiperen	equipeerde	V;IND;SG;3;PST
piepen	piepen	V;NFIN
levenloos	levenloze	ADJ;INDF;PL
schaatsen	schaatste	V;IND;SG;3;PST
bloedheet	bloedhete	ADJ;DEF
sjoemelen	sjoemelt	V;IND;SG;2;PRS
halen	haal	V;IMP;SG
stapelen	stapelde	V;IND;SG;3;PST
euvel	euvel	ADJ;INDF;NEUT;SG
verwilderen	verwilder	V;IND;SG;1;PRS
sprokkelen	sprokkel	V;IND;SG;1;PRS
luchtig	luchtigere	ADJ;SPRL;INDF;NEUT;SG
duivelachtig	duivelachtig	ADJ;INDF;NEUT;SG
passief	passieve	ADJ;DEF
streven	streef	V;IND;SG;1;PRS
voedselarm	voedselarm	ADJ;INDF;NEUT;SG
Myceens	Myceense	ADJ;DEF
schromen	schromen	V;IND;PL;PRS
Zuid-Afrikaans	Zuid-Afrikaanse	ADJ;INDF;PL
grillig	grillige	ADJ;INDF;PL
associëren	associeert	V;IND;SG;2;PRS
gewichtloos	gewichtlooste	ADJ;SPRL;INDF;PL
verhouden	verhouden	V;NFIN
aansprakelijk	aansprakelijk	ADJ;INDF;NEUT;SG
minimalistisch	minimalistische	ADJ;CMPR;INDF;NEUT;SG
bibberen	bibber	V;IND;SG;1;PRS
vergelden	vergelde	V;SBJV;SG;PRS
beletten	beletten	V;IND;PL;PST
benadrukken	benadrukte	V;SBJV;SG;PST
dierbaar	dierbaardere	ADJ;SPRL;INDF;NEUT;SG
walgelijk	walgelijkere	ADJ;CMPR;DEF
rechtmatig	rechtmatigere	ADJ;SPRL;INDF;NEUT;SG
rijgen	rijg	V;IND;SG;1;PRS
hyperventileren	hyperventileerde	V;IND;SG;3;PST
aanschouwelijk	aanschouwelijke	ADJ;DEF
prikkelbaar	prikkelbaardere	ADJ;SPRL;INDF;NEUT;SG
stroomlijnen	stroomlijnden	V;IND;PL;PST
kronkelen	kronkelde	V;IND;SG;1;PST
drenken	drenkte	V;IND;SG;1;PST
beheersen	beheerste	V;SBJV;SG;PST
spoedig	spoedige	ADJ;INDF;PL
verstoppen	verstopt	V;IND;SG;2;PRS
bestempelen	bestempelt	V;IND;SG;2;PRS
houterig	houterigste	ADJ;SPRL;DEF
schuin	schuinste	ADJ;SPRL;INDF;PL
Laotiaans	Laotiaanse	ADJ;CMPR;INDF;NEUT;SG
wiebelen	wiebelen	V;SBJV;PL;PRS
verlagen	verlaag	V;IND;SG;1;PRS
belastbaar	belastbaar	ADJ;INDF;NEUT;SG
aarzelen	aarzelen	V;NFIN
belemmeren	belemmert	V;IMP;PL
betreuren	betreuren	V;IND;PL;PRS
onheilspellend	onheilspellendste	ADJ;SPRL;INDF;PL
denken	denken	V;IND;PL;PRS
huisvesten	huisvesten	V;SBJV;PL;PRS
dateren	dateren	V;SBJV;PL;PRS
dwaas	dwazere	ADJ;SPRL;INDF;NEUT;SG
degelijk	degelijke	ADJ;CMPR;INDF;NEUT;SG
memoriseren	memoriseer	V;IMP;SG
Sloveens	Sloveense	ADJ;CMPR;INDF;NEUT;SG
echoën	geëchood	V.PTCP;PST
ploegen	ploege	V;SBJV;SG;PRS
huisvesten	huisvesten	V;NFIN
prepareren	prepareer	V;IND;SG;1;PRS
minachten	minachtten	V;SBJV;PL;PST
huwen	huwde	V;IND;SG;3;PST
gewenst	gewenstste	ADJ;SPRL;DEF
bewerkstelligen	bewerkstelligen	V;IND;PL;PRS
kotsen	kotst	V;IND;SG;3;PRS
vulgair	vulgaire	ADJ;DEF
volslank	volslanker	ADJ;CMPR;INDF;PL
aanschouwelijk	aanschouwelijkere	ADJ;SPRL;INDF;NEUT;SG
schakelen	schakelen	V;IND;PL;PRS
analyseren	analyseren	V;NFIN
vertroosten	vertroostte	V;SBJV;SG;PST
krank	krankere	ADJ;SPRL;INDF;NEUT;SG
slinken	slonk	V;IND;SG;3;PST
hecht	hechtste	ADJ;SPRL;INDF;PL
vlijtig	vlijtigere	ADJ;CMPR;DEF
puberen	gepuberd	V.PTCP;PST
jammer	jammerste	ADJ;SPRL;INDF;PL
gezellig	gezelliger	ADJ;CMPR;INDF;PL
toe-eigenen	toe-eigenden	V;IND;PL;PST
boud	boude	ADJ;CMPR;INDF;NEUT;SG
tof	tofste	ADJ;SPRL;DEF
tieren	tiert	V;IMP;PL
slapen	slaapt	V;IMP;PL
verslechteren	verslechtere	V;SBJV;SG;PRS
Latijns	Latijns	ADJ;INDF;NEUT;SG
ondersteunen	ondersteunde	V;IND;SG;2;PST
overstelpen	overstelpte	V;SBJV;SG;PST
versleten	versletenste	ADJ;SPRL;DEF
creatief	creatief	ADJ;INDF;NEUT;SG
Oekraïens	Oekraïense	ADJ;CMPR;INDF;NEUT;SG
dominant	dominante	ADJ;CMPR;INDF;NEUT;SG
kortademig	kortademiger	ADJ;CMPR;INDF;PL
claimen	claimde	V;IND;SG;3;PST
verwarmen	verwarmde	V;IND;SG;3;PST
jodelen	jodelde	V;IND;SG;2;PST
afwezig	afwezigste	ADJ;SPRL;DEF
verhaspelen	verhaspel	V;IMP;SG
donkerblauw	donkerblauwe	ADJ;CMPR;INDF;NEUT;SG
zot	zot	ADJ;INDF;NEUT;SG
hoopvol	hoopvolste	ADJ;SPRL;DEF
repen	reept	V;IND;SG;3;PRS
boeten	boete	V;SBJV;SG;PRS
verglijden	verglijdt	V;IND;SG;3;PRS
legitimeren	legitimeer	V;IMP;SG
spreken	spreken	V;SBJV;PL;PRS
detecteren	detecteert	V;IND;SG;3;PRS
bits	bitser	ADJ;CMPR;INDF;PL
aanpasbaar	aanpasbare	ADJ;INDF;PL
figuurlijk	figuurlijke	ADJ;CMPR;INDF;NEUT;SG
vergrendelen	vergrendelden	V;SBJV;PL;PST
klieren	klieren	V;IND;PL;PRS
meubileren	meubileren	V;IND;PL;PRS
vernietigen	vernietigt	V;IMP;PL
dooien	gedooid	V.PTCP;PST
exciteren	exciteerden	V;IND;PL;PST
behartigen	behartigt	V;IND;SG;3;PRS
evenwichtig	evenwichtigste	ADJ;SPRL;INDF;PL
wiebelen	wiebelt	V;IND;SG;3;PRS
versieren	versierde	V;SBJV;SG;PST
congruent	congruente	ADJ;INDF;PL
schransen	geschranst	V.PTCP;PST
homofoob	homofoobste	ADJ;SPRL;DEF
wantrouwig	wantrouwigste	ADJ;SPRL;DEF
verwaarloosbaar	verwaarloosbaarder	ADJ;CMPR;INDF;PL
verdrijven	verdrijft	V;IND;SG;3;PRS
beschutten	beschutten	V;SBJV;PL;PST
hecht	hechte	ADJ;CMPR;INDF;NEUT;SG
frunniken	frunnikten	V;SBJV;PL;PST
schoon	schoner	ADJ;CMPR;INDF;PL
accelereren	accelereerde	V;SBJV;SG;PST
rectaal	rectale	ADJ;INDF;PL
hartig	hartigere	ADJ;CMPR;DEF
teder	teder	ADJ;INDF;NEUT;SG
verplanten	verplant	V;IND;SG;3;PRS
bruisen	bruist	V;IND;SG;3;PRS
dun	dunne	ADJ;DEF
houtig	houtigste	ADJ;SPRL;INDF;PL
programmeren	programmeerde	V;IND;SG;2;PST
bekruipen	bekroop	V;IND;SG;3;PST
brisant	brisantste	ADJ;SPRL;INDF;PL
sjoemelen	sjoemelde	V;IND;SG;3;PST
rechtdoorzee	rechtdoorzeeëre	ADJ;SPRL;INDF;NEUT;SG
bevooroordeeld	bevooroordeelde	ADJ;INDF;PL
vormeloos	vormelooste	ADJ;SPRL;DEF
wenen	geweend	V.PTCP;PST
gevoelen	gevoelt	V;IMP;PL
centrumrechts	centrumrechtse	ADJ;DEF
wervelen	wervel	V;IND;SG;1;PRS
verstandig	verstandig	ADJ;INDF;NEUT;SG
verharen	verhaarden	V;SBJV;PL;PST
signaleren	signaleerden	V;IND;PL;PST
plukken	plukte	V;SBJV;SG;PST
herleiden	herleide	V;SBJV;SG;PRS
verhit	verhittere	ADJ;SPRL;INDF;NEUT;SG
verdraaid	verdraaide	ADJ;INDF;PL
homogeen	homogenere	ADJ;SPRL;INDF;NEUT;SG
laconiek	laconiekste	ADJ;SPRL;DEF
overmeesteren	overmeester	V;IMP;SG
zwellen	zwol	V;IND;SG;1;PST
aaibaar	aaibare	ADJ;DEF
lofwaardig	lofwaardigere	ADJ;SPRL;INDF;NEUT;SG
organoleptisch	organoleptische	ADJ;CMPR;INDF;NEUT;SG
bladeren	bladerde	V;SBJV;SG;PST
decoderen	decodeert	V;IND;SG;2;PRS
herkrijgen	herkrijgen	V;SBJV;PL;PRS
pyknisch	pyknische	ADJ;DEF
zuigen	zogen	V;IND;PL;PST
helderziend	helderderziendere	ADJ;SPRL;INDF;NEUT;SG
maximaliseren	maximaliseert	V;IMP;PL
Servisch	Servischer	ADJ;CMPR;INDF;PL
doorgedraaid	doorgedraaide	ADJ;DEF
rillen	rilt	V;IND;SG;2;PRS
casten	castten	V;SBJV;PL;PST
ongewenst	ongewenste	ADJ;CMPR;INDF;NEUT;SG
draaien	draai	V;IND;SG;1;PRS
gewennen	gewent	V;IND;SG;2;PRS
reizen	reist	V;IND;SG;3;PRS
globaliseren	globaliseert	V;IND;SG;3;PRS
oordelen	oordeel	V;IND;SG;1;PRS
dienstig	dienstigste	ADJ;SPRL;INDF;PL
ongeremd	ongeremdere	ADJ;SPRL;INDF;NEUT;SG
schillen	schille	V;SBJV;SG;PRS
toe-eigenen	toe-eigent	V;IMP;PL
eroderen	erodeerde	V;SBJV;SG;PST
zat	zatter	ADJ;CMPR;INDF;PL
fotograferen	fotografeert	V;IND;SG;3;PRS
landen	landen	V;SBJV;PL;PRS
allemachtig	allemachtiger	ADJ;CMPR;INDF;PL
ontcijferen	ontcijferden	V;IND;PL;PST
betuigen	betuigt	V;IMP;PL
mankeren	mankeerde	V;IND;SG;1;PST
zomen	zoom	V;IND;SG;1;PRS
beschieten	beschiete	V;SBJV;SG;PRS
onwettelijk	onwettelijkere	ADJ;SPRL;INDF;NEUT;SG
geneeslijk	geneeslijkste	ADJ;SPRL;INDF;PL
verafgoden	verafgoden	V;SBJV;PL;PRS
beplaten	beplaatten	V;IND;PL;PST
ruziën	ruziede	V;IND;SG;2;PST
gigantisch	gigantischer	ADJ;CMPR;INDF;PL
bliksemen	bliksemen	V;SBJV;PL;PRS
onvoorspelbaar	onvoorspelbare	ADJ;DEF
verpesten	verpestte	V;IND;SG;1;PST
sjoemelen	sjoemelen	V;IND;PL;PRS
joggen	joggen	V;NFIN
dilettantisch	dilettantisch	ADJ;INDF;NEUT;SG
kakken	gekakt	V.PTCP;PST
humoristisch	humoristische	ADJ;DEF
aannemelijk	aannemelijkste	ADJ;SPRL;DEF
Servisch	Servische	ADJ;DEF
vormeloos	vormelozer	ADJ;CMPR;INDF;PL
ondergeschikt	ondergeschiktere	ADJ;SPRL;INDF;NEUT;SG
gappen	gapte	V;SBJV;SG;PST
futloos	futloze	ADJ;INDF;PL
anarchistisch	anarchistische	ADJ;INDF;PL
zeilen	zeilden	V;SBJV;PL;PST
zingen	zongen	V;IND;PL;PST
bevatten	bevat	V.PTCP;PST
retarderen	retardeert	V;IMP;PL
formeel	formele	ADJ;DEF
huiken	huikte	V;IND;SG;1;PST
braaien	braaien	V;NFIN
vlammen	vlam	V;IMP;SG
lukraak	lukraakste	ADJ;SPRL;INDF;PL
toekomend	toekomend	ADJ;INDF;NEUT;SG
rotsig	rotsige	ADJ;INDF;PL
pendelen	pendelt	V;IMP;PL
verzengen	verzeng	V;IND;SG;1;PRS
vibreren	vibreren	V;IND;PL;PRS
noemen	noemden	V;SBJV;PL;PST
halfnaakt	halfnaaktere	ADJ;SPRL;INDF;NEUT;SG
hergebruiken	hergebruikte	V;IND;SG;3;PST
louteren	louter	V;IMP;SG
aanmerkelijk	aanmerkelijkste	ADJ;SPRL;DEF
zwellen	zwelle	V;SBJV;SG;PRS
arctisch	arctische	ADJ;DEF
vernuftig	vernuftigste	ADJ;SPRL;INDF;PL
razendsnel	razendsnelste	ADJ;SPRL;DEF
verwijven	verwijf	V;IMP;SG
wedijveren	wedijverde	V;IND;SG;2;PST
levendig	levendig	ADJ;INDF;NEUT;SG
onbelastbaar	onbelastbaar	ADJ;INDF;NEUT;SG
inclusief	inclusiefste	ADJ;SPRL;INDF;PL
Bosnisch	Bosnischte	ADJ;SPRL;DEF
stelselmatig	stelselmatigere	ADJ;SPRL;INDF;NEUT;SG
inclusief	inclusiever	ADJ;CMPR;INDF;PL
auditeren	auditeerde	V;IND;SG;2;PST
klateren	klatere	V;SBJV;SG;PRS
luchten	luchtte	V;SBJV;SG;PST
schuw	schuw	ADJ;INDF;NEUT;SG
slopen	sloopt	V;IND;SG;2;PRS
melodisch	melodische	ADJ;CMPR;INDF;NEUT;SG
zeilen	zeilde	V;IND;SG;3;PST
stuiteren	stuitert	V;IMP;PL
verdrievoudigen	verdrievoudig	V;IMP;SG
worteltrekken	worteltrekken	V;NFIN
presenteren	presenteert	V;IND;SG;2;PRS
levensmoe	levensmoeste	ADJ;SPRL;INDF;PL
geliefd	geliefdere	ADJ;SPRL;INDF;NEUT;SG
tieren	tier	V;IND;SG;1;PRS
begiftigen	begiftig	V;IMP;SG
desoriënteren	desoriënteerde	V;SBJV;SG;PST
bezig	bezigere	ADJ;SPRL;INDF;NEUT;SG
blozen	bloosden	V;IND;PL;PST
loeien	loeien	V;SBJV;PL;PRS
belazeren	belazerd	V.PTCP;PST
bestuderen	bestudeert	V;IND;SG;3;PRS
voelen	gevoeld	V.PTCP;PST
politiek correct	politiek correcte	ADJ;DEF
verheffen	verheffe	V;SBJV;SG;PRS
verademen	verademt	V;IND;SG;3;PRS
roemruchtig	roemruchtigste	ADJ;SPRL;DEF
onaangenaam	onaangenaamste	ADJ;SPRL;DEF
preken	preekte	V;IND;SG;2;PST
ongewenst	ongewenst	ADJ;INDF;NEUT;SG
ondersteunen	ondersteunen	V;NFIN
Limburgs	Limburgs	ADJ;INDF;NEUT;SG
verrassen	verrasten	V;SBJV;PL;PST
Germaans	Germaanse	ADJ;CMPR;INDF;NEUT;SG
bezuinigen	bezuinigen	V;SBJV;PL;PRS
pejoratief	pejoratievere	ADJ;SPRL;INDF;NEUT;SG
conflictueus	conflictueuzere	ADJ;SPRL;INDF;NEUT;SG
telefoneren	telefoneerde	V;IND;SG;2;PST
ontmaskeren	ontmaskerden	V;IND;PL;PST
opaak	opaker	ADJ;CMPR;INDF;PL
kisten	kistte	V;IND;SG;3;PST
fataal	fataalste	ADJ;SPRL;DEF
puntig	puntig	ADJ;INDF;NEUT;SG
bovengistend	bovengistende	ADJ;INDF;PL
roesten	roest	V;IMP;SG
zwaar	zwaardere	ADJ;CMPR;DEF
tussentijds	tussentijds	ADJ;INDF;NEUT;SG
verkiesbaar	verkiesbaarste	ADJ;SPRL;DEF
dimmen	dimme	V;SBJV;SG;PRS
relativeren	relativeerden	V;IND;PL;PST
memorabel	memorabele	ADJ;DEF
zout	zoutste	ADJ;SPRL;INDF;PL
patrouilleren	patrouilleert	V;IND;SG;3;PRS
herenigen	herenigen	V;SBJV;PL;PRS
minimalistisch	minimalistisch	ADJ;INDF;NEUT;SG
aanvaarden	aanvaarden	V;NFIN
abonneren	abonneer	V;IND;SG;1;PRS
hengelen	hengelen	V;SBJV;PL;PRS
beven	beeft	V;IMP;PL
vermolmen	vermolm	V;IMP;SG
eerbiedig	eerbiedigste	ADJ;SPRL;DEF
indringend	indringend	ADJ;INDF;NEUT;SG
knutselen	knutselde	V;IND;SG;1;PST
vies	vieze	ADJ;DEF
verdrievoudigen	verdrievoudigen	V;NFIN
schroeien	schroeide	V;SBJV;SG;PST
steigeren	steigerde	V;IND;SG;1;PST
overzichtelijk	overzichtelijke	ADJ;DEF
zot	zotste	ADJ;SPRL;DEF
ontdooien	ontdooide	V;IND;SG;2;PST
massief	massievere	ADJ;SPRL;INDF;NEUT;SG
hemelblauw	hemelblauwe	ADJ;INDF;PL
dobbelen	dobbelen	V;NFIN
demonstreren	demonstreerde	V;IND;SG;3;PST
onopvallend	onopvallend	ADJ;INDF;NEUT;SG
kritiek	kritiek	ADJ;INDF;NEUT;SG
gespierd	gespierde	ADJ;INDF;PL
bespotten	bespotte	V;IND;SG;3;PST
intrigeren	intrigeerden	V;IND;PL;PST
lenen	geleend	V.PTCP;PST
walgelijk	walgelijke	ADJ;DEF
geschift	geschifter	ADJ;CMPR;INDF;PL
ontfermen	ontferme	V;SBJV;SG;PRS
begiftigen	begiftigen	V;NFIN
derogeren	derogeert	V;IMP;PL
stompen	stompt	V;IND;SG;2;PRS
sprokkelen	sprokkelden	V;IND;PL;PST
verwijderen	verwijderd	V.PTCP;PST
detecteren	detecteerde	V;IND;SG;3;PST
beklagen	beklaagde	V;SBJV;SG;PST
consistent	consistentere	ADJ;SPRL;INDF;NEUT;SG
vrezen	vrees	V;IND;SG;1;PRS
verschaffen	verschaffen	V;NFIN
retoucheren	retoucheerden	V;IND;PL;PST
excuseren	excuseerde	V;IND;SG;3;PST
razendsnel	razendsnelle	ADJ;INDF;PL
bekrachtigen	bekrachtigden	V;IND;PL;PST
motiveren	motiveren	V;SBJV;PL;PRS
benieuwen	benieuwden	V;SBJV;PL;PST
verschillen	verschille	V;SBJV;SG;PRS
ijken	ijkten	V;SBJV;PL;PST
isoleren	isoleer	V;IND;SG;1;PRS
isoleren	isoleerden	V;SBJV;PL;PST
duwen	duwen	V;NFIN
opperen	opperden	V;SBJV;PL;PST
klaar	klare	ADJ;INDF;PL
verkiesbaar	verkiesbare	ADJ;DEF
bewonderen	bewondert	V;IND;SG;3;PRS
detacheren	detacheren	V;IND;PL;PRS
degelijk	degelijker	ADJ;CMPR;INDF;PL
fluisteren	fluister	V;IMP;SG
kwaken	kwaakt	V;IMP;PL
onzinnig	onzinnige	ADJ;CMPR;INDF;NEUT;SG
Anatolisch	Anatolische	ADJ;CMPR;INDF;NEUT;SG
galvaniseren	gegalvaniseerd	V.PTCP;PST
reflecteren	reflecteerde	V;IND;SG;1;PST
schoppen	schopten	V;IND;PL;PST
hoofdrekenen	hoofdrekenen	V;SBJV;PL;PRS
verslinden	verslindt	V;IMP;PL
omvatten	omvat	V;IMP;SG
polynomiaal	polynomiaalste	ADJ;SPRL;DEF
casten	gecast	V.PTCP;PST
lelijk	lelijkste	ADJ;SPRL;INDF;PL
vertroosten	vertroostten	V;IND;PL;PST
druipen	droop	V;IND;SG;1;PST
massief	massief	ADJ;INDF;NEUT;SG
onbeperkt	onbeperktste	ADJ;SPRL;DEF
overdenken	overdenkt	V;IMP;PL
beschoren	beschoren	ADJ;INDF;NEUT;SG
verwisselen	verwisselde	V;IND;SG;1;PST
sloffen	sloffen	V;IND;PL;PRS
ontharen	onthaart	V;IND;SG;3;PRS
exerceren	exerceren	V;NFIN
pro-actief	pro-actiefste	ADJ;SPRL;INDF;PL
volledig	volledigste	ADJ;SPRL;INDF;PL
vernoemen	vernoemden	V;SBJV;PL;PST
spontaan	spontane	ADJ;DEF
melancholiek	melancholieke	ADJ;DEF
schateren	schaterde	V;IND;SG;1;PST
talrijk	talrijke	ADJ;DEF
verharden	verhardde	V;SBJV;SG;PST
overstijgen	overstijgen	V;SBJV;PL;PRS
verzwijgen	verzwijgt	V;IND;SG;3;PRS
ontketenen	ontketenen	V;IND;PL;PRS
blozen	bloost	V;IMP;PL
gevoelen	gevoelde	V;IND;SG;2;PST
rustiek	rustieke	ADJ;INDF;PL
beklagen	beklagen	V;NFIN
stollen	stolle	V;SBJV;SG;PRS
intelligent	intelligenter	ADJ;CMPR;INDF;PL
dwarsliggend	dwarsliggendste	ADJ;SPRL;DEF
klieren	klierde	V;IND;SG;3;PST
rellen	rellen	V;SBJV;PL;PRS
bestuderen	bestudeer	V;IND;SG;1;PRS
watertanden	watertandden	V;IND;PL;PST
ontduiken	ontduik	V;IND;SG;1;PRS
onschuldig	onschuldigere	ADJ;CMPR;DEF
Ingrisch	Ingrische	ADJ;INDF;PL
langgerokt	langgeroktste	ADJ;SPRL;DEF
vertoeven	vertoeve	V;SBJV;SG;PRS
kokhalzen	kokhals	V;IND;SG;1;PRS
onwel	onwelle	ADJ;DEF
internetten	internette	V;SBJV;SG;PRS
verfijnen	verfijnde	V;IND;SG;3;PST
schor	schordere	ADJ;CMPR;DEF
orgelen	orgelde	V;IND;SG;3;PST
lengen	lengde	V;IND;SG;2;PST
verslijten	versleet	V;IND;SG;2;PST
subjectief	subjectieve	ADJ;INDF;PL
maf	maffe	ADJ;INDF;PL
kissebissen	kissebisten	V;IND;PL;PST
boeten	boette	V;IND;SG;2;PST
mislukken	mislukte	V;IND;SG;2;PST
flessen	flesten	V;IND;PL;PST
nutteloos	nuttelozere	ADJ;SPRL;INDF;NEUT;SG
beheersbaar	beheersbaardere	ADJ;SPRL;INDF;NEUT;SG
vogelachtig	vogelachtigste	ADJ;SPRL;INDF;PL
ijveren	ijverde	V;SBJV;SG;PST
doorgronden	doorgrond	V.PTCP;PST
beschaven	beschaaft	V;IND;SG;3;PRS
beschouwen	beschouwden	V;IND;PL;PST
ondervinden	ondervinden	V;NFIN
creëren	creëer	V;IMP;SG
Portugees	Portugese	ADJ;CMPR;INDF;NEUT;SG
verschrijven	verschreven	V;IND;PL;PST
constateren	constateerde	V;SBJV;SG;PST
constateren	constateren	V;IND;PL;PRS
verhogen	verhoogt	V;IMP;PL
bukken	bukken	V;IND;PL;PRS
signaleren	signaleert	V;IMP;PL
geurig	geurige	ADJ;DEF
wendbaar	wendbaardere	ADJ;SPRL;INDF;NEUT;SG
frunniken	frunnike	V;SBJV;SG;PRS
verafgoden	verafgoodt	V;IMP;PL
compact	compactste	ADJ;SPRL;INDF;PL
duister	duistere	ADJ;INDF;PL
overkoepelen	overkoepelt	V;IMP;PL
vernietigen	vernietigde	V;IND;SG;1;PST
fragiel	fragielste	ADJ;SPRL;INDF;PL
klieren	kliert	V;IND;SG;2;PRS
proportioneel	proportioneel	ADJ;INDF;NEUT;SG
offensief	offensieve	ADJ;DEF
tronen	tronen	V;NFIN
pieren	pier	V;IND;SG;1;PRS
onoplettend	onoplettende	ADJ;CMPR;INDF;NEUT;SG
betreffen	betref	V;IMP;SG
graaien	graait	V;IND;SG;2;PRS
verfomfaaien	verfomfaait	V;IMP;PL
vluchten	vluchtten	V;IND;PL;PST
chatten	chat	V;IND;SG;2;PRS
diepzinnig	diepzinnige	ADJ;CMPR;INDF;NEUT;SG
kubistisch	kubistisch	ADJ;INDF;NEUT;SG
herwinnen	herwinnen	V;IND;PL;PRS
verademen	verademt	V;IND;SG;2;PRS
lenen	leent	V;IND;SG;3;PRS
overrulen	overruled	V.PTCP;PST
leerlooien	leerlooie	V;SBJV;SG;PRS
botsen	bots	V;IND;SG;1;PRS
maskeren	gemaskerd	V.PTCP;PST
attributief	attributievere	ADJ;CMPR;DEF
nestelen	nestelen	V;IND;PL;PRS
briesen	bries	V;IMP;SG
verdommen	verdomd	V.PTCP;PST
krom	kromme	ADJ;CMPR;INDF;NEUT;SG
bedwingen	bedwongen	V.PTCP;PST
omsingelen	omsingelen	V;NFIN
oprecht	oprecht	ADJ;INDF;NEUT;SG
hopen	hope	V;SBJV;SG;PRS
schroeien	schroei	V;IMP;SG
organoleptisch	organoleptisch	ADJ;INDF;NEUT;SG
streven	streefden	V;SBJV;PL;PST
ruim	ruimer	ADJ;CMPR;INDF;PL
betreuren	betreurt	V;IMP;PL
bezoedelen	bezoedelen	V;SBJV;PL;PRS
strijken	streek	V;IND;SG;3;PST
ontbloten	ontblootten	V;SBJV;PL;PST
besterven	bestorven	V.PTCP;PST
elektronisch	elektronischte	ADJ;SPRL;INDF;PL
zwetsen	zwetse	V;SBJV;SG;PRS
klaverjassen	klaverjas	V;IMP;SG
laconiek	laconieker	ADJ;CMPR;INDF;PL
strikken	strikken	V;NFIN
bezeren	bezeerde	V;IND;SG;3;PST
retarderen	retarderen	V;SBJV;PL;PRS
informeren	informeerde	V;IND;SG;2;PST
Anatolisch	Anatolischere	ADJ;SPRL;INDF;NEUT;SG
Limburgs	Limburgsere	ADJ;SPRL;INDF;NEUT;SG
ketters	kettersere	ADJ;CMPR;DEF
Braziliaans	Braziliaanser	ADJ;CMPR;INDF;PL
Mongools	Mongoolse	ADJ;INDF;PL
documenteren	documenteert	V;IND;SG;2;PRS
vertakken	vertakt	V;IND;SG;2;PRS
verpesten	verpestte	V;IND;SG;3;PST
achterhalen	achterhaalt	V;IND;SG;3;PRS
vertegenwoordigen	vertegenwoordigde	V;IND;SG;3;PST
bestempelen	bestempelt	V;IND;SG;3;PRS
willen	willen	V;SBJV;PL;PRS
verhitten	verhit	V;IND;SG;3;PRS
testen	teste	V;SBJV;SG;PRS
paren	pare	V;SBJV;SG;PRS
stevig	stevigste	ADJ;SPRL;INDF;PL
ellendig	ellendig	ADJ;INDF;NEUT;SG
nutteloos	nuttelozer	ADJ;CMPR;INDF;PL
schuifelen	schuifelde	V;SBJV;SG;PST
corresponderen	correspondeerden	V;SBJV;PL;PST
emanciperen	emancipeerde	V;IND;SG;3;PST
voedselrijk	voedselrijker	ADJ;CMPR;INDF;PL
begrijpen	begrijpen	V;SBJV;PL;PRS
roesten	roestte	V;SBJV;SG;PST
vermelden	vermeldt	V;IND;SG;3;PRS
beschijnen	bescheen	V;IND;SG;2;PST
sjokken	sjokt	V;IMP;PL
verslaan	verslaan	V;IND;PL;PRS
casten	cast	V;IMP;SG
beven	beven	V;NFIN
organoleptisch	organoleptischere	ADJ;SPRL;INDF;NEUT;SG
gluren	glure	V;SBJV;SG;PRS
bruisen	bruisten	V;SBJV;PL;PST
bezig	bezigste	ADJ;SPRL;DEF
verrotten	verrotte	V;SBJV;SG;PST
ezelachtig	ezelachtige	ADJ;DEF
Aroemeens	Aroemeense	ADJ;CMPR;INDF;NEUT;SG
onderzoeken	onderzochten	V;SBJV;PL;PST
verstoppen	verstoppen	V;NFIN
rot	rotte	ADJ;DEF
bemoeien	bemoeien	V;SBJV;PL;PRS
gesticuleren	gesticuleerde	V;IND;SG;2;PST
liften	lift	V;IND;SG;1;PRS
haperen	hapert	V;IND;SG;2;PRS
vernietigen	vernietig	V;IMP;SG
bemiddelen	bemiddeld	V.PTCP;PST
joelen	joelen	V;NFIN
flippen	flipte	V;IND;SG;1;PST
adelen	adelde	V;SBJV;SG;PST
ontbreken	ontbreke	V;SBJV;SG;PRS
bespeuren	bespeurt	V;IMP;PL
frunniken	frunniken	V;IND;PL;PRS
katachtig	katachtig	ADJ;INDF;NEUT;SG
vermoeden	vermoeden	V;SBJV;PL;PRS
verblinden	verblindde	V;SBJV;SG;PST
berouwen	berouwe	V;SBJV;SG;PRS
duivelachtig	duivelachtige	ADJ;CMPR;INDF;NEUT;SG
wild	wilde	ADJ;DEF
friemelen	friemelde	V;IND;SG;3;PST
verzadigen	verzadigt	V;IMP;PL
dwalen	dwaalde	V;IND;SG;3;PST
aamborstig	aamborstige	ADJ;CMPR;INDF;NEUT;SG
vloeibaar	vloeibaarste	ADJ;SPRL;DEF
lek	lekkere	ADJ;SPRL;INDF;NEUT;SG
stunten	stunt	V;IND;SG;2;PRS
overdenken	overdenken	V;SBJV;PL;PRS
gebaren	gebaart	V;IND;SG;3;PRS
tegendraads	tegendraadsere	ADJ;SPRL;INDF;NEUT;SG
vernietigen	vernietige	V;SBJV;SG;PRS
porren	por	V;IND;SG;1;PRS
vertikken	vertikken	V;IND;PL;PRS
onzeker	onzekerdere	ADJ;CMPR;DEF
beschouwen	beschouwd	V.PTCP;PST
fragmenteren	fragmenteert	V;IND;SG;3;PRS
inunderen	inundeert	V;IMP;PL
versoepelen	versoepelt	V;IND;SG;3;PRS
penetreren	penetreert	V;IMP;PL
verzekeren	verzekerde	V;SBJV;SG;PST
verdringen	verdrong	V;IND;SG;2;PST
kermen	kermde	V;IND;SG;3;PST
ontnemen	ontneem	V;IND;SG;1;PRS
fotograferen	fotograferen	V;SBJV;PL;PRS
restaureren	restaureerde	V;IND;SG;3;PST
betreuren	betreurt	V;IND;SG;3;PRS
categoriseren	categoriseerden	V;IND;PL;PST
droef	droeve	ADJ;CMPR;INDF;NEUT;SG
volgen	volgen	V;SBJV;PL;PRS
wurgen	gewurgd	V.PTCP;PST
krassen	krast	V;IND;SG;3;PRS
schelden	scheldt	V;IMP;PL
stokoud	stokoud	ADJ;INDF;NEUT;SG
overmatig	overmatig	ADJ;INDF;NEUT;SG
verzuilen	verzuilt	V;IMP;PL
dromen	droomde	V;IND;SG;3;PST
treuren	treurt	V;IND;SG;3;PRS
verpieteren	verpieteren	V;IND;PL;PRS
maoïstisch	maoïstische	ADJ;INDF;PL
bevaarbaar	bevaarbare	ADJ;INDF;PL
babbelen	babbelden	V;IND;PL;PST
naadloos	naadloze	ADJ;INDF;PL
fundamenteel	fundamentele	ADJ;DEF
officieus	officieuzer	ADJ;CMPR;INDF;PL
bevaarbaar	bevaarbaardere	ADJ;CMPR;DEF
zwaaien	zwaaien	V;SBJV;PL;PRS
vitaal	vitaler	ADJ;CMPR;INDF;PL
twinkelen	twinkelde	V;IND;SG;3;PST
schandelijk	schandelijke	ADJ;CMPR;INDF;NEUT;SG
puffen	puften	V;SBJV;PL;PST
slijten	slijten	V;IND;PL;PRS
alledaags	alledaagsere	ADJ;SPRL;INDF;NEUT;SG
krukken	krukke	V;SBJV;SG;PRS
Beiers	Beiers	ADJ;INDF;NEUT;SG
rantsoeneren	rantsoeneer	V;IND;SG;1;PRS
prettig	prettigere	ADJ;CMPR;DEF
bezwaren	bezwaart	V;IND;SG;3;PRS
bruinachtig	bruinachtige	ADJ;DEF
verliezen	verlieze	V;SBJV;SG;PRS
verdampen	verdampte	V;IND;SG;1;PST
voorbarig	voorbariger	ADJ;CMPR;INDF;PL
Frankisch	Frankische	ADJ;DEF
reden	reedt	V;IND;SG;2;PRS
globaal	globale	ADJ;DEF
herdenken	herdenken	V;IND;PL;PRS
verloochenen	verloochend	V.PTCP;PST
condoleren	condolere	V;SBJV;SG;PRS
bezoeken	bezoek	V;IMP;SG
representatief	representatievere	ADJ;CMPR;DEF
verdubbelen	verdubbele	V;SBJV;SG;PRS
staren	staarden	V;IND;PL;PST
zuchten	zucht	V;IND;SG;2;PRS
hoogpolig	hoogpolige	ADJ;DEF
verkneukelen	verkneukelden	V;IND;PL;PST
vloeien	vloeie	V;SBJV;SG;PRS
bestemmen	bestem	V;IMP;SG
grijnzen	grijnst	V;IMP;PL
zogen	zogen	V;IND;PL;PRS
smullen	gesmuld	V.PTCP;PST
wollig	wolligere	ADJ;SPRL;INDF;NEUT;SG
beschimpen	beschimpte	V;IND;SG;3;PST
verklappen	verklapte	V;SBJV;SG;PST
verchromen	verchromen	V;SBJV;PL;PRS
twinkelen	twinkel	V;IMP;SG
redeneren	redeneerde	V;IND;SG;3;PST
goeden	goedden	V;IND;PL;PST
versleutelen	versleutelt	V;IMP;PL
ongenaakbaar	ongenaakbaarste	ADJ;SPRL;INDF;PL
achtervolgen	achtervolgen	V;NFIN
Silezisch	Silezischte	ADJ;SPRL;INDF;PL
vreesaanjagend	vreesaanjagende	ADJ;INDF;PL
onsamenhangend	onsamenhangender	ADJ;CMPR;INDF;PL
blokkeren	blokkeer	V;IMP;SG
fixeren	fixeerden	V;IND;PL;PST
eerloos	eerlozere	ADJ;CMPR;INDF;PL
schelden	scheld	V;IND;SG;1;PRS
miezeren	miezert	V;IND;SG;2;PRS
kruisigen	kruisigde	V;IND;SG;3;PST
schimmig	schimmigste	ADJ;SPRL;INDF;PL
stagneren	stagneren	V;NFIN
bezielen	bezielde	V;SBJV;SG;PST
warm	warme	ADJ;CMPR;INDF;NEUT;SG
fluiten	gefloten	V.PTCP;PST
oorspronkelijk	oorspronkelijk	ADJ;INDF;NEUT;SG
mokken	mokte	V;SBJV;SG;PST
bedenken	bedachten	V;SBJV;PL;PST
alleen	alleenste	ADJ;SPRL;INDF;PL
cederen	cedeert	V;IND;SG;2;PRS
koortsachtig	koortsachtigste	ADJ;SPRL;INDF;PL
kapseizen	kapseizen	V;SBJV;PL;PRS
vrolijk	vrolijkste	ADJ;SPRL;INDF;PL
ontgoochelen	ontgoochelde	V;IND;SG;2;PST
hergroeperen	hergroeperen	V;IND;PL;PRS
babbelen	babbelen	V;IND;PL;PRS
verkloten	verkloten	V;IND;PL;PRS
herkansen	herkanst	V;IND;SG;2;PRS
verhuren	verhuurden	V;SBJV;PL;PST
Kroatisch	Kroatische	ADJ;INDF;PL
geilig	geiligere	ADJ;CMPR;INDF;PL
verwerpelijk	verwerpelijkste	ADJ;SPRL;DEF
verkommeren	verkommerd	V.PTCP;PST
ontmaagden	ontmaagd	V;IMP;SG
brokkelen	brokkelen	V;IND;PL;PRS
bewieroken	bewierookt	V;IND;SG;3;PRS
postuum	postume	ADJ;DEF
trachten	trachtten	V;IND;PL;PST
doseren	doseren	V;IND;PL;PRS
noodzakelijk	noodzakelijke	ADJ;CMPR;INDF;NEUT;SG
bezorgen	bezorg	V;IND;SG;1;PRS
herinneren	herinneren	V;NFIN
heiig	heiige	ADJ;INDF;PL
rappen	rapte	V;IND;SG;2;PST
propageren	propageerde	V;IND;SG;3;PST
jaloers	jaloerste	ADJ;SPRL;DEF
gewaagd	gewaagd	ADJ;INDF;NEUT;SG
emfatisch	emfatischere	ADJ;SPRL;INDF;NEUT;SG
zonderling	zonderling	ADJ;INDF;NEUT;SG
weerspiegelen	weerspiegel	V;IND;SG;1;PRS
bezielen	bezielt	V;IMP;PL
armoedig	armoedige	ADJ;CMPR;INDF;NEUT;SG
deugdelijk	deugdelijkste	ADJ;SPRL;INDF;PL
heldhaftig	heldhaftig	ADJ;INDF;NEUT;SG
gijzelen	gegijzeld	V.PTCP;PST
onovergankelijk	onovergankelijke	ADJ;DEF
belligerent	belligerent	ADJ;INDF;NEUT;SG
spammen	spam	V;IND;SG;1;PRS
rokeren	rokeert	V;IND;SG;3;PRS
laarzen	laarzen	V;SBJV;PL;PRS
rijen	rijt	V;IND;SG;2;PRS
Georgisch	Georgische	ADJ;CMPR;INDF;NEUT;SG
wellen	geweld	V.PTCP;PST
verminderen	vermindert	V;IND;SG;3;PRS
veroorloven	veroorloofde	V;IND;SG;3;PST
seinen	seinde	V;SBJV;SG;PST
schelen	scheelden	V;SBJV;PL;PST
betichten	beticht	V;IMP;SG
berekenen	berekene	V;SBJV;SG;PRS
wankel	wankelere	ADJ;SPRL;INDF;NEUT;SG
verkeren	verkeerde	V;IND;SG;1;PST
averechts	averechtsere	ADJ;SPRL;INDF;NEUT;SG
sterk	sterke	ADJ;INDF;PL
herstarten	herstartte	V;IND;SG;3;PST
stompzinnig	stompzinnigere	ADJ;CMPR;DEF
getuigen	getuigt	V;IND;SG;2;PRS
verkommeren	verkommer	V;IND;SG;1;PRS
gassen	gassen	V;IND;PL;PRS
oefenen	oefenen	V;SBJV;PL;PRS
bejubelen	bejubelt	V;IND;SG;3;PRS
honds	hondste	ADJ;SPRL;INDF;PL
bestralen	bestraalde	V;IND;SG;2;PST
puffen	puffen	V;SBJV;PL;PRS
belligerent	belligerente	ADJ;INDF;PL
heus	heusere	ADJ;SPRL;INDF;NEUT;SG
spijbelen	spijbelt	V;IND;SG;2;PRS
mijden	mijden	V;IND;PL;PRS
knevelen	knevel	V;IMP;SG
gespannen	gespannener	ADJ;CMPR;INDF;PL
wazig	wazigere	ADJ;CMPR;DEF
karnen	karnden	V;SBJV;PL;PST
pikzwart	pikzwarter	ADJ;CMPR;INDF;PL
scanderen	scanderen	V;NFIN
vervolgen	vervolgden	V;IND;PL;PST
rasecht	rasechte	ADJ;CMPR;INDF;NEUT;SG
blokkeren	blokkeert	V;IND;SG;3;PRS
spreiden	spreidt	V;IMP;PL
indexeren	indexeert	V;IND;SG;3;PRS
potten	potte	V;IND;SG;1;PST
zoor	zore	ADJ;CMPR;INDF;NEUT;SG
bejaard	bejaard	ADJ;INDF;NEUT;SG
pogen	poogden	V;IND;PL;PST
omklemmen	omklemt	V;IMP;PL
volbrengen	volbrenge	V;SBJV;SG;PRS
kinderachtig	kinderachtiger	ADJ;CMPR;INDF;PL
figuratief	figuratief	ADJ;INDF;NEUT;SG
wrikken	wrik	V;IMP;SG
kabbelen	kabbelen	V;SBJV;PL;PRS
neurotisch	neurotischere	ADJ;CMPR;DEF
herdenken	herherdachte	V;SBJV;SG;PST
sneeuwen	sneeuwt	V;IMP;PL
turven	turf	V;IMP;SG
bewonen	bewone	V;SBJV;SG;PRS
confronteren	confronteerden	V;IND;PL;PST
verbuigen	verbuigt	V;IND;SG;3;PRS
doden	dood	V;IND;SG;1;PRS
defect	defectste	ADJ;SPRL;INDF;PL
muiten	muit	V;IMP;PL
verkleuren	verkleurden	V;IND;PL;PST
krachtig	krachtige	ADJ;CMPR;INDF;NEUT;SG
dwarrelen	dwarrel	V;IND;SG;1;PRS
betekenisvol	betekenisvolste	ADJ;SPRL;INDF;PL
verfomfaaid	verfomfaaidste	ADJ;SPRL;INDF;PL
gunnen	gun	V;IMP;SG
bestrijden	bestrijd	V;IND;SG;1;PRS
verbasteren	verbasteren	V;NFIN
geroutineerd	geroutineerder	ADJ;CMPR;INDF;PL
flitsen	flitst	V;IND;SG;3;PRS
tafelen	tafelt	V;IMP;PL
dragelijk	dragelijk	ADJ;INDF;NEUT;SG
snoeien	snoeit	V;IND;SG;2;PRS
verdubbelen	verdubbelde	V;IND;SG;2;PST
verduidelijken	verduidelijkten	V;SBJV;PL;PST
appreciëren	apprecieerden	V;IND;PL;PST
legaal	legalere	ADJ;SPRL;INDF;NEUT;SG
raadplegen	raadpleeg	V;IMP;SG
prediken	predikt	V;IND;SG;3;PRS
nationalistisch	nationalistische	ADJ;INDF;PL
metselen	metselen	V;NFIN
verdwalen	verdwaalde	V;SBJV;SG;PST
verzamelen	verzamele	V;SBJV;SG;PRS
verwarren	verwarde	V;IND;SG;2;PST
bijgelovig	bijgelovigste	ADJ;SPRL;DEF
feesten	feestte	V;IND;SG;1;PST
verraderlijk	verraderlijke	ADJ;CMPR;INDF;NEUT;SG
hellen	hellen	V;SBJV;PL;PRS
sluik	sluikere	ADJ;CMPR;DEF
nopen	noopten	V;IND;PL;PST
putten	put	V;IND;SG;1;PRS
verlichten	verlichten	V;NFIN
rieken	rieken	V;NFIN
geleiden	geleide	V;SBJV;SG;PRS
trotseren	trotsere	V;SBJV;SG;PRS
ontheemd	ontheemde	ADJ;INDF;PL
verwonderen	verwonder	V;IND;SG;1;PRS
dineren	dineren	V;IND;PL;PRS
evalueren	evalueren	V;IND;PL;PRS
miskennen	misken	V;IMP;SG
glijden	gleden	V;SBJV;PL;PST
natuurkundig	natuurkundigere	ADJ;CMPR;DEF
alledaags	alledaagste	ADJ;SPRL;INDF;PL
vergemakkelijken	vergemakkelijkt	V.PTCP;PST
genetisch	genetische	ADJ;INDF;PL
Georgisch	Georgischere	ADJ;CMPR;DEF
doseren	doseerden	V;SBJV;PL;PST
behoeftig	behoeftige	ADJ;DEF
somberen	sombert	V;IND;SG;2;PRS
ongewijzigd	ongewijzigd	ADJ;INDF;NEUT;SG
nieuwgekozen	nieuwgekozen	ADJ;INDF;NEUT;SG
beknibbelen	beknibbel	V;IMP;SG
rammelen	gerammeld	V.PTCP;PST
welven	welfde	V;IND;SG;1;PST
ongedwongen	ongedwongenste	ADJ;SPRL;INDF;PL
triomferen	triomfeerden	V;IND;PL;PST
slagen	slagen	V;SBJV;PL;PRS
blinken	blinkt	V;IMP;PL
knallen	knallen	V;SBJV;PL;PRS
compileren	compileerde	V;SBJV;SG;PST
bebossen	bebost	V;IND;SG;3;PRS
ploeteren	ploeterde	V;IND;SG;3;PST
duizelen	duizelde	V;IND;SG;3;PST
gekarteld	gekartelde	ADJ;DEF
openbaren	openbaarden	V;IND;PL;PST
smaden	gesmaad	V.PTCP;PST
bestrijden	bestreed	V;IND;SG;3;PST
verven	verfden	V;IND;PL;PST
vertrouwen	vertrouwen	V;NFIN
eigenen	eigenen	V;SBJV;PL;PRS
gepeperd	gepeperder	ADJ;CMPR;INDF;PL
protegeren	geprotegeerd	V.PTCP;PST
ongetrouwd	ongetrouwde	ADJ;DEF
bejubelen	bejubelen	V;SBJV;PL;PRS
aerodynamisch	aerodynamischere	ADJ;SPRL;INDF;NEUT;SG
ontzeggen	ontzeg	V;IND;SG;1;PRS
meedogenloos	meedogenlooser	ADJ;CMPR;INDF;PL
kopiëren	kopieerde	V;SBJV;SG;PST
goedkoop	goedkope	ADJ;CMPR;INDF;NEUT;SG
reserveren	reserveren	V;NFIN
duizelen	duizelen	V;SBJV;PL;PRS
onontbeerlijk	onontbeerlijke	ADJ;INDF;PL
psychedelisch	psychedelischere	ADJ;SPRL;INDF;NEUT;SG
vitaal	vitalere	ADJ;CMPR;DEF
upgraden	geüpgraded	V.PTCP;PST
onbetaalbaar	onbetaalbare	ADJ;INDF;PL
vervolgen	vervolgen	V;SBJV;PL;PRS
industrialiseren	industrialiseert	V;IMP;PL
prolongeren	geprolongeerd	V.PTCP;PST
heel	hele	ADJ;DEF
gebeft	gebefter	ADJ;CMPR;INDF;PL
regelmatig	regelmatigste	ADJ;SPRL;DEF
oefenen	oefende	V;IND;SG;1;PST
deinen	deinde	V;IND;SG;2;PST
hunkeren	hunkerde	V;IND;SG;2;PST
bijwoordelijk	bijwoordelijke	ADJ;INDF;PL
zenuwachtig	zenuwachtige	ADJ;INDF;PL
mailen	mailde	V;IND;SG;3;PST
Austronesisch	Austronesische	ADJ;INDF;PL
dromen	droom	V;IND;SG;1;PRS
verorberen	verorber	V;IMP;SG
minuscuul	minuscuulste	ADJ;SPRL;DEF
plezant	plezantere	ADJ;SPRL;INDF;NEUT;SG
aantrekkelijk	aantrekkelijkere	ADJ;SPRL;INDF;NEUT;SG
stedelijk	stedelijke	ADJ;DEF
opmerkelijk	opmerkelijk	ADJ;INDF;NEUT;SG
adellijk	adellijk	ADJ;INDF;NEUT;SG
simpel	simpelere	ADJ;SPRL;INDF;NEUT;SG
pril	prille	ADJ;INDF;PL
procederen	procedeerde	V;IND;SG;2;PST
lichtvoetig	lichtvoetige	ADJ;INDF;PL
plaatsen	plaatst	V;IMP;PL
wankel	wankelste	ADJ;SPRL;INDF;PL
plaatsen	plaatste	V;SBJV;SG;PST
bedroeven	bedroefde	V;IND;SG;3;PST
proppen	prop	V;IMP;SG
onbehoorlijk	onbehoorlijk	ADJ;INDF;NEUT;SG
vernaaien	vernaaien	V;SBJV;PL;PRS
spioneren	spionere	V;SBJV;SG;PRS
boeken	boekt	V;IND;SG;2;PRS
geuren	geuren	V;IND;PL;PRS
donkerrood	donkerrood	ADJ;INDF;NEUT;SG
versturen	verstuurde	V;IND;SG;1;PST
pandoeren	pandoert	V;IND;SG;2;PRS
harken	harkte	V;IND;SG;3;PST
verzetten	verzet	V;IND;SG;2;PRS
deleten	delete	V;IMP;SG
rantsoeneren	rantsoeneert	V;IND;SG;3;PRS
uniform	uniformste	ADJ;SPRL;INDF;PL
rieken	rook	V;IND;SG;2;PST
ploeteren	ploeteren	V;NFIN
malverseren	gemalverseerd	V.PTCP;PST
gooien	gooi	V;IMP;SG
velen	veelt	V;IND;SG;3;PRS
romantiseren	romantiseert	V;IND;SG;2;PRS
triomferen	triomfeerde	V;IND;SG;2;PST
oogsten	oogst	V;IMP;PL
plaatsen	plaatse	V;SBJV;SG;PRS
klutsen	klutste	V;IND;SG;1;PST
eigenaardig	eigenaardig	ADJ;INDF;NEUT;SG
schatrijk	schatrijke	ADJ;CMPR;INDF;NEUT;SG
verminderen	verminderde	V;IND;SG;2;PST
gedenken	gedachten	V;IND;PL;PST
deugdelijk	deugdelijker	ADJ;CMPR;INDF;PL
stofferen	stoffeer	V;IND;SG;1;PRS
geijkt	geijktste	ADJ;SPRL;DEF
verbaasd	verbaasdere	ADJ;CMPR;DEF
bevinden	bevonden	V;IND;PL;PST
beroeren	beroerde	V;IND;SG;1;PST
promoveren	promoveren	V;NFIN
bebouwen	bebouwt	V;IND;SG;2;PRS
spuwen	gespuwd	V.PTCP;PST
vrijgesteld	vrijgesteld	ADJ;INDF;NEUT;SG
dramatisch	dramatische	ADJ;DEF
vissen	vist	V;IND;SG;2;PRS
dineren	dineerde	V;IND;SG;2;PST
zwaaien	zwaait	V;IND;SG;2;PRS
vreugdeloos	vreugdeloze	ADJ;CMPR;INDF;NEUT;SG
bundelen	bundel	V;IMP;SG
goedkoop	goedkopere	ADJ;SPRL;INDF;NEUT;SG
verfraaien	verfraaien	V;NFIN
bedwelmen	bedwelmde	V;SBJV;SG;PST
democratisch	democratischere	ADJ;SPRL;INDF;NEUT;SG
upgraden	upgradet	V;IND;SG;3;PRS
situeren	situeer	V;IMP;SG
prachtig	prachtig	ADJ;INDF;NEUT;SG
vermoedelijk	vermoedelijk	ADJ;INDF;NEUT;SG
deugdelijk	deugdelijkste	ADJ;SPRL;DEF
ongedwongen	ongedwongen	ADJ;INDF;PL
herkennen	herken	V;IND;SG;1;PRS
staatkundig	staatkundigere	ADJ;CMPR;DEF
spuiten	spote	V;SBJV;SG;PST
weifelen	weifelden	V;SBJV;PL;PST
warm	warm	ADJ;INDF;NEUT;SG
detecteerbaar	detecteerbaarder	ADJ;CMPR;INDF;PL
harden	hardden	V;IND;PL;PST
verplegen	verplegen	V;SBJV;PL;PRS
vroegtijdig	vroegtijdigere	ADJ;CMPR;DEF
kwijten	kweten	V;IND;PL;PST
boetseren	boetseert	V;IND;SG;2;PRS
antiferromagnetisch	antiferromagnetische	ADJ;INDF;PL
vereeuwigen	vereeuwigen	V;IND;PL;PRS
zelfingenomen	zelfingenomenste	ADJ;SPRL;DEF
vergezellen	vergezeld	V.PTCP;PST
snoeren	snoer	V;IND;SG;1;PRS
transfigureren	transfigureren	V;SBJV;PL;PRS
doceren	doceer	V;IND;SG;1;PRS
genereus	genereuze	ADJ;DEF
overwegen	overwoog	V;IND;SG;2;PST
verroesten	verroest	V.PTCP;PST
stoffelijk	stoffelijkere	ADJ;CMPR;DEF
Iberisch	Iberische	ADJ;INDF;PL
ziften	ziftten	V;SBJV;PL;PST
spruiten	spruite	V;SBJV;SG;PRS
systematiseren	systematiseer	V;IMP;SG
verzetten	verzette	V;SBJV;SG;PRS
behaagziek	behaagzieke	ADJ;DEF
topografisch	topografische	ADJ;INDF;PL
titreren	titreerde	V;IND;SG;1;PST
Waals	Waalsere	ADJ;SPRL;INDF;NEUT;SG
ontkennen	ontkende	V;IND;SG;3;PST
sneeuwen	sneeuwde	V;IND;SG;2;PST
omcirkelen	omcirkelen	V;NFIN
rappen	rapten	V;IND;PL;PST
kruidig	kruidigste	ADJ;SPRL;DEF
weerkaatsen	weerkaatsen	V;NFIN
bewapenen	bewapenen	V;NFIN
rijten	rijt	V;IND;SG;1;PRS
bezitten	bezit	V;IMP;PL
funderen	fundeer	V;IMP;SG
sjagerijnig	sjagerijnig	ADJ;INDF;NEUT;SG
separatistisch	separatistische	ADJ;INDF;PL
lichtgeel	lichtgelere	ADJ;SPRL;INDF;NEUT;SG
handhaven	handhave	V;SBJV;SG;PRS
oneven	oneven	ADJ;DEF
verwennen	verwennen	V;SBJV;PL;PRS
schijten	scheten	V;IND;PL;PST
overweldigen	overweldigden	V;SBJV;PL;PST
oneven	oneven	ADJ;INDF;PL
vergen	vergden	V;SBJV;PL;PST
pijnloos	pijnlooste	ADJ;SPRL;DEF
legendarisch	legendarischere	ADJ;CMPR;DEF
mijden	mede	V;SBJV;SG;PST
geestig	geestigste	ADJ;SPRL;INDF;PL
jaarlijks	jaarlijkse	ADJ;INDF;PL
rapen	geraapt	V.PTCP;PST
ijskoud	ijskoud	ADJ;INDF;NEUT;SG
chanteren	chanteerden	V;SBJV;PL;PST
onderdrukken	onderdrukke	V;SBJV;SG;PRS
bestormen	bestorm	V;IND;SG;1;PRS
misbruiken	misbruikt	V;IND;SG;3;PRS
gerechtigd	gerechtigde	ADJ;DEF
kleurrijk	kleurrijker	ADJ;CMPR;INDF;PL
gemaakt	gemaaktere	ADJ;CMPR;DEF
verzuren	verzuurde	V;IND;SG;2;PST
Frankisch	Frankische	ADJ;INDF;PL
gevoelig	gevoeligste	ADJ;SPRL;DEF
overmatig	overmatige	ADJ;CMPR;INDF;NEUT;SG
stinken	stonk	V;IND;SG;3;PST
endemisch	endemische	ADJ;CMPR;INDF;NEUT;SG
teekenen	teekent	V;IND;SG;3;PRS
loom	lomere	ADJ;CMPR;DEF
verloederen	verloederde	V;SBJV;SG;PST
plenair	plenair	ADJ;INDF;NEUT;SG
onmiskenbaar	onmiskenbaarste	ADJ;SPRL;INDF;PL
verroesten	verroestte	V;IND;SG;1;PST
kijken	kijken	V;NFIN
turven	turfde	V;IND;SG;1;PST
gestoord	gestoordste	ADJ;SPRL;DEF
oorvegen	oorveeg	V;IND;SG;1;PRS
beraadslagen	beraadslaagden	V;SBJV;PL;PST
rapen	raapt	V;IND;SG;3;PRS
verzamelen	verzamelden	V;IND;PL;PST
oxideren	oxideer	V;IND;SG;1;PRS
buitenaards	buitenaardste	ADJ;SPRL;INDF;PL
Australisch	Australische	ADJ;CMPR;INDF;NEUT;SG
efficiënt	efficiëntste	ADJ;SPRL;DEF
buitelen	buitel	V;IND;SG;1;PRS
tuiten	tuit	V;IMP;PL
stagneren	stagneerde	V;SBJV;SG;PST
dubieus	dubieuste	ADJ;SPRL;INDF;PL
rieken	rook	V;IND;SG;3;PST
aanneembaar	aanneembaarste	ADJ;SPRL;DEF
betwijfelen	betwijfelen	V;NFIN
besnijden	besneed	V;IND;SG;2;PST
Caraïbisch	Caraïbische	ADJ;CMPR;INDF;NEUT;SG
kunstmatig	kunstmatige	ADJ;DEF
reusachtig	reusachtigere	ADJ;CMPR;DEF
plebeïsch	plebeïscher	ADJ;CMPR;INDF;NEUT;SG
verrukkelijk	verrukkelijkere	ADJ;CMPR;DEF
zwaaien	zwaaien	V;IND;PL;PRS
noest	noester	ADJ;CMPR;INDF;PL
lanceren	lanceert	V;IMP;PL
ongenadig	ongenadige	ADJ;CMPR;INDF;NEUT;SG
verlieven	verlieven	V;SBJV;PL;PRS
stofferen	stoffeer	V;IMP;SG
krijgen	kregen	V;IND;PL;PST
hartvormig	hartvormigere	ADJ;SPRL;INDF;NEUT;SG
parmantig	parmantigste	ADJ;SPRL;DEF
piramidaal	piramidalere	ADJ;CMPR;DEF
sluikstorten	sluikstortten	V;SBJV;PL;PST
kneuzen	kneus	V;IMP;SG
aanbidden	aanbid	V;IMP;SG
rekels	rekelse	ADJ;INDF;PL
vergroten	vergrootten	V;SBJV;PL;PST
vergroeien	vergroeiden	V;IND;PL;PST
afgrijselijk	afgrijselijke	ADJ;CMPR;INDF;NEUT;SG
onmogelijk	onmogelijke	ADJ;CMPR;INDF;NEUT;SG
kaarsrecht	kaarsrecht	ADJ;INDF;NEUT;SG
discrimineren	discrimineerde	V;SBJV;SG;PST
babbelen	gebabbeld	V.PTCP;PST
drogen	drogen	V;SBJV;PL;PRS
gespannen	gespannenste	ADJ;SPRL;INDF;PL
ageren	ageert	V;IND;SG;2;PRS
biografisch	biografische	ADJ;INDF;PL
pedofiel	pedofiele	ADJ;DEF
satiriek	satirieke	ADJ;DEF
eenparig	eenparige	ADJ;CMPR;INDF;NEUT;SG
doorwaadbaar	doorwaadbaar	ADJ;INDF;NEUT;SG
benemen	benemen	V;NFIN
wurgen	wurgden	V;IND;PL;PST
komisch	komische	ADJ;INDF;PL
verschrikkelijk	verschrikkelijkste	ADJ;SPRL;DEF
breekbaar	breekbare	ADJ;INDF;PL
eindigen	eindigt	V;IMP;PL
sproeien	sproeide	V;IND;SG;2;PST
rolschaatsen	rolschaatsten	V;IND;PL;PST
pauselijk	pauselijker	ADJ;CMPR;INDF;PL
stoutmoedig	stoutmoedigere	ADJ;SPRL;INDF;NEUT;SG
bewieroken	bewieroken	V;NFIN
dwars	dwarsere	ADJ;SPRL;INDF;NEUT;SG
begeren	begere	V;SBJV;SG;PRS
vermeten	vermetener	ADJ;CMPR;INDF;PL
Middeliers	Middeliers	ADJ;INDF;NEUT;SG
geuren	gegeurd	V.PTCP;PST
wurmen	wurmt	V;IND;SG;3;PRS
fungeren	fungeerde	V;IND;SG;2;PST
tijdig	tijdig	ADJ;INDF;NEUT;SG
dement	demente	ADJ;CMPR;INDF;NEUT;SG
bedruipen	bedruipe	V;SBJV;SG;PRS
intimideren	intimideerden	V;SBJV;PL;PST
vertrouwen	vertrouwde	V;IND;SG;3;PST
omgekeerd	omgekeerde	ADJ;INDF;PL
stofzuigen	stofzuigen	V;SBJV;PL;PRS
vroegtijdig	vroegtijdigste	ADJ;SPRL;INDF;PL
moeiteloos	moeiteloze	ADJ;CMPR;INDF;NEUT;SG
giechelen	gegiecheld	V.PTCP;PST
laagdrempelig	laagdrempeliger	ADJ;CMPR;INDF;PL
reviseren	reviseert	V;IND;SG;3;PRS
volbrengen	volbreng	V;IND;SG;1;PRS
plechtig	plechtige	ADJ;CMPR;INDF;NEUT;SG
Palestijns	Palestijnste	ADJ;SPRL;DEF
ingezet	ingezette	ADJ;DEF
perfect	perfecte	ADJ;INDF;PL
noordwestelijk	noordwestelijke	ADJ;INDF;PL
geestdodend	geestdodend	ADJ;INDF;NEUT;SG
polygaam	polygaam	ADJ;INDF;NEUT;SG
snappen	snappe	V;SBJV;SG;PRS
beluisteren	beluisteren	V;IND;PL;PRS
gescheiden	gescheiden	ADJ;DEF
detineren	detineerde	V;SBJV;SG;PST
capricieus	capricieuzere	ADJ;SPRL;INDF;NEUT;SG
ziekelijk	ziekelijkste	ADJ;SPRL;DEF
omzichtig	omzichtiger	ADJ;CMPR;INDF;PL
duivels	duivelste	ADJ;SPRL;DEF
vooraanstaand	vooraanstaandste	ADJ;SPRL;INDF;PL
devoot	devoter	ADJ;CMPR;INDF;PL
plebeïsch	plebeïschte	ADJ;SPRL;DEF
verzwaren	verzwaren	V;SBJV;PL;PRS
verroesten	verroeste	V;SBJV;SG;PRS
gratuit	gratuite	ADJ;DEF
autonoom	autonoom	ADJ;INDF;NEUT;SG
verhuren	verhuurt	V;IMP;PL
verveeld	verveelde	ADJ;INDF;PL
kwispelen	kwispelde	V;IND;SG;1;PST
schamel	schameler	ADJ;CMPR;INDF;PL
verleiden	verleiden	V;IND;PL;PRS
husselen	hussele	V;SBJV;SG;PRS
plassen	plast	V;IND;SG;3;PRS
nijgen	neeg	V;IND;SG;1;PST
participeren	participeer	V;IND;SG;1;PRS
identificeren	identificeren	V;NFIN
ontsieren	ontsierde	V;IND;SG;2;PST
bezwijken	bezwijkt	V;IND;SG;2;PRS
glunderen	glunder	V;IND;SG;1;PRS
rammelen	rammelen	V;NFIN
transseksueel	transseksueler	ADJ;CMPR;INDF;PL
onkreukbaar	onkreukbaarste	ADJ;SPRL;DEF
onderscheppen	onderschepten	V;SBJV;PL;PST
sleutelen	gesleuteld	V.PTCP;PST
problematisch	problematischere	ADJ;CMPR;DEF
denkbeeldig	denkbeeldige	ADJ;CMPR;INDF;NEUT;SG
escorteren	escorteerde	V;IND;SG;2;PST
ontploffen	ontploften	V;SBJV;PL;PST
gruwelijk	gruwelijker	ADJ;CMPR;INDF;PL
verzaken	verzaakte	V;IND;SG;2;PST
bevoordelen	bevoordeelt	V;IND;SG;3;PRS
deerniswekkend	deerniswekkendste	ADJ;SPRL;DEF
belichamen	belichaamde	V;IND;SG;1;PST
executief	executievere	ADJ;CMPR;DEF
specificeren	specificeren	V;NFIN
maken	gemaakt	V.PTCP;PST
strelen	streelden	V;SBJV;PL;PST
eindigen	eindigde	V;IND;SG;2;PST
dapper	dapperder	ADJ;CMPR;INDF;PL
betwisten	betwist	V.PTCP;PST
raak	rake	ADJ;INDF;PL
Tibetaans	Tibetaansere	ADJ;CMPR;DEF
kritisch	kritischte	ADJ;SPRL;INDF;PL
onuitstaanbaar	onuitstaanbaarste	ADJ;SPRL;DEF
structureel	structurele	ADJ;DEF
verwonderen	verwonderde	V;IND;SG;1;PST
fixen	fixt	V;IND;SG;2;PRS
onverdienstelijk	onverdienstelijkere	ADJ;SPRL;INDF;NEUT;SG
verzoeken	verzoekt	V;IMP;PL
Georgisch	Georgischte	ADJ;SPRL;INDF;PL
impopulair	impopulairste	ADJ;SPRL;INDF;NEUT;SG
zouten	zoutte	V;IND;SG;2;PST
klagen	klaagden	V;IND;PL;PST
malverseren	malverseren	V;NFIN
wrochten	wrochten	V;NFIN
lichtvoetig	lichtvoetige	ADJ;DEF
ruiken	ruik	V;IND;SG;1;PRS
rekwireren	rekwireerde	V;IND;SG;3;PST
controleren	controleerde	V;SBJV;SG;PST
gerechtelijk	gerechtelijkere	ADJ;SPRL;INDF;NEUT;SG
internationaal	internationalere	ADJ;SPRL;INDF;NEUT;SG
beknibbelen	beknibbel	V;IND;SG;1;PRS
bloen	bloenere	ADJ;CMPR;DEF
sterk	sterkere	ADJ;CMPR;DEF
kolken	kolkt	V;IND;SG;3;PRS
huren	huurde	V;SBJV;SG;PST
skeeleren	skeelere	V;SBJV;SG;PRS
brandbaar	brandbare	ADJ;CMPR;INDF;NEUT;SG
popelen	popelt	V;IND;SG;3;PRS
zien	zag	V;IND;SG;3;PST
ambitieus	ambitieuste	ADJ;SPRL;DEF
lispelen	lispelde	V;IND;SG;1;PST
beklimmen	beklimme	V;SBJV;SG;PRS
vloeien	vloeit	V;IMP;PL
laagdrempelig	laagdrempelige	ADJ;CMPR;INDF;NEUT;SG
bezwaren	bezwaren	V;NFIN
houdbaar	houdbaardere	ADJ;CMPR;DEF
averechts	averechts	ADJ;INDF;NEUT;SG
mopperen	mopperen	V;IND;PL;PRS
afgrijselijk	afgrijselijkste	ADJ;SPRL;DEF
jachtig	jachtigste	ADJ;SPRL;INDF;PL
pokeren	pokeren	V;SBJV;PL;PRS
kampen	kampe	V;SBJV;SG;PRS
prat	pratte	ADJ;INDF;PL
verbouwen	verbouwd	V.PTCP;PST
dagelijks	dagelijkse	ADJ;INDF;PL
glimlachen	glimlachte	V;SBJV;SG;PST
Austronesisch	Austronesisch	ADJ;INDF;NEUT;SG
lastig	lastig	ADJ;INDF;NEUT;SG
bangelijk	bangelijkste	ADJ;SPRL;DEF
aalvlug	aalvlugste	ADJ;SPRL;INDF;PL
winkelen	winkelde	V;IND;SG;2;PST
vissen	viste	V;IND;SG;1;PST
lichtgrijs	lichtgrijzere	ADJ;CMPR;DEF
demonstratief	demonstratieve	ADJ;CMPR;INDF;NEUT;SG
lispelen	lispelt	V;IND;SG;2;PRS
proper	propere	ADJ;CMPR;INDF;NEUT;SG
nederig	nederigere	ADJ;CMPR;DEF
zagen	zaagt	V;IMP;PL
wrevelig	wrevelige	ADJ;INDF;PL
besteden	besteedden	V;IND;PL;PST
verloochenen	verloochen	V;IND;SG;1;PRS
believen	believen	V;NFIN
Nigeriaans	Nigeriaanse	ADJ;CMPR;INDF;NEUT;SG
onderliggend	onderliggende	ADJ;DEF
onpasselijk	onpasselijke	ADJ;INDF;PL
slachten	slachte	V;SBJV;SG;PRS
verkoelen	verkoeld	V.PTCP;PST
controleren	controleert	V;IMP;PL
zuchten	zuchte	V;SBJV;SG;PRS
bezitten	bezitte	V;SBJV;SG;PRS
fraai	fraaie	ADJ;DEF
beredeneren	beredeneerden	V;IND;PL;PST
vertonen	vertoont	V;IMP;PL
dartelen	gedarteld	V.PTCP;PST
rehabiliteren	rehabiliteert	V;IND;SG;2;PRS
harmoniseren	harmonisere	V;SBJV;SG;PRS
verkneukelen	verkneukel	V;IND;SG;1;PRS
verdampen	verdampen	V;IND;PL;PRS
versmelten	versmelten	V;SBJV;PL;PRS
slepen	sleepte	V;SBJV;SG;PST
verjaren	verjaarde	V;SBJV;SG;PST
beweegbaar	beweegbaardere	ADJ;SPRL;INDF;NEUT;SG
onderwerpen	onderwerpe	V;SBJV;SG;PRS
deinen	deint	V;IMP;PL
Kazachs	Kazachsere	ADJ;CMPR;DEF
beminnen	beminne	V;SBJV;SG;PRS
overig	overige	ADJ;DEF
kidnappen	kidnapte	V;IND;SG;1;PST
Oudnederlands	Oudnederlandse	ADJ;INDF;PL
wisselen	wisselt	V;IMP;PL
rommelen	rommelden	V;IND;PL;PST
beheerbaar	beheerbaarste	ADJ;SPRL;DEF
masturberen	masturberen	V;NFIN
gebieden	gebied	V;IND;SG;1;PRS
beslissen	beslist	V.PTCP;PST
contacteren	contacteerde	V;IND;SG;3;PST
maken	maakten	V;SBJV;PL;PST
eigenaardig	eigenaardige	ADJ;CMPR;INDF;NEUT;SG
verdenken	verdachten	V;IND;PL;PST
hersenspoelen	hersenspoelt	V;IMP;PL
lappen	lap	V;IMP;SG
triomferen	triomfeert	V;IND;SG;2;PRS
enten	entte	V;IND;SG;3;PST
gooien	gooi	V;IND;SG;1;PRS
verlokken	verlokte	V;SBJV;SG;PST
onderbouwen	onderbouwt	V;IND;SG;2;PRS
Noord-Hollands	Noord-Hollandste	ADJ;SPRL;INDF;PL
controleren	controleer	V;IND;SG;1;PRS
lambriseren	lambriseren	V;SBJV;PL;PRS
aflijvig	aflijvig	ADJ;INDF;NEUT;SG
castreren	castreerde	V;IND;SG;2;PST
bewijzen	bewijst	V;IND;SG;2;PRS
waarschijnlijk	waarschijnlijkste	ADJ;SPRL;DEF
onderbreken	onderbrak	V;IND;SG;1;PST
bestijgen	besteeg	V;IND;SG;3;PST
kelderen	kelderde	V;IND;SG;3;PST
verhelpen	verhielp	V;IND;SG;1;PST
gruwzaam	gruwzame	ADJ;INDF;PL
prematuur	prematuurste	ADJ;SPRL;DEF
welven	gewelfd	V.PTCP;PST
geschieden	geschiedde	V;IND;SG;3;PST
slagen	slaagde	V;IND;SG;2;PST
lichtvoetig	lichtvoetige	ADJ;CMPR;INDF;NEUT;SG
fuseren	fuseer	V;IND;SG;1;PRS
discussiëren	discussieert	V;IND;SG;3;PRS
bazig	bazige	ADJ;CMPR;INDF;NEUT;SG
onberispelijk	onberispelijkere	ADJ;SPRL;INDF;NEUT;SG
machtig	machtigste	ADJ;SPRL;INDF;PL
ontkleden	ontkleeden	V;NFIN
Israëlisch	Israëlischere	ADJ;CMPR;DEF
zeer	zere	ADJ;CMPR;INDF;NEUT;SG
verlengen	verlengt	V;IMP;PL
verbijsteren	verbijsterde	V;IND;SG;1;PST
verwerpelijk	verwerpelijker	ADJ;CMPR;INDF;PL
verwarren	verwarre	V;SBJV;SG;PRS
achturig	achturig	ADJ;INDF;NEUT;SG
dubbelklikken	dubbelklikte	V;IND;SG;2;PST
Romaans	Romaanser	ADJ;CMPR;INDF;PL
lispelen	lispele	V;SBJV;SG;PRS
verwringen	verwrong	V;IND;SG;2;PST
weigeren	weiger	V;IMP;SG
ontruimen	ontruim	V;IND;SG;1;PRS
waarschijnlijk	waarschijnlijkere	ADJ;SPRL;INDF;NEUT;SG
verhuren	verhuur	V;IMP;SG
betwijfelen	betwijfelde	V;IND;SG;3;PST
gassen	gaste	V;IND;SG;2;PST
graveren	graveren	V;IND;PL;PRS
hallucineren	hallucineren	V;SBJV;PL;PRS
ontmaagden	ontmaagden	V;NFIN
krijgen	krijgen	V;NFIN
mishandelen	mishandel	V;IMP;SG
slagvaardig	slagvaardiger	ADJ;CMPR;INDF;PL
schijten	schijt	V;IND;SG;2;PRS
onverhoopt	onverhoopte	ADJ;DEF
vuurrood	vuurroder	ADJ;CMPR;INDF;PL
lezen	lazen	V;IND;PL;PST
turven	turven	V;SBJV;PL;PRS
behoren	behoorde	V;IND;SG;3;PST
schijten	scheet	V;IND;SG;1;PST
bepleiten	bepleiten	V;IND;PL;PRS
bestormen	bestormen	V;NFIN
meinedig	meinedige	ADJ;DEF
voleindigen	voleindigden	V;IND;PL;PST
bewijzen	bewijs	V;IMP;SG
tochtig	tochtigere	ADJ;CMPR;DEF
kreeftachtig	kreeftachtigste	ADJ;SPRL;DEF
oehoeën	oehoet	V;IND;SG;2;PRS
dansbaar	dansbare	ADJ;INDF;PL
triomferen	triomfeerde	V;IND;SG;1;PST
beschuldigen	beschuldigden	V;SBJV;PL;PST
sjorren	sjorde	V;IND;SG;2;PST
joviaal	joviale	ADJ;CMPR;INDF;NEUT;SG
oogsten	oogst	V;IND;SG;2;PRS
begunstigen	begunstig	V;IND;SG;1;PRS
gezond	gezonde	ADJ;CMPR;INDF;NEUT;SG
titreren	titreert	V;IND;SG;3;PRS
herbouwen	herbouwen	V;NFIN
muiten	muitte	V;SBJV;SG;PST
verwerpelijk	verwerpelijke	ADJ;DEF
batsen	batst	V;IND;SG;2;PRS
objectief	objectieve	ADJ;CMPR;INDF;NEUT;SG
heus	heuser	ADJ;CMPR;INDF;PL
schuinen	schuinden	V;IND;PL;PST
onbehoorlijk	onbehoorlijkste	ADJ;SPRL;DEF
spraakzaam	spraakzaam	ADJ;INDF;NEUT;SG
verbreden	verbreedden	V;IND;PL;PST
belonen	belonen	V;SBJV;PL;PRS
lusten	lustte	V;IND;SG;3;PST
gedenken	gedenk	V;IMP;SG
schuilen	schuilen	V;SBJV;PL;PRS
bemerken	bemerken	V;SBJV;PL;PRS
gelukkig	gelukkigste	ADJ;SPRL;DEF
devoot	devootste	ADJ;SPRL;DEF
googelen	googelen	V;NFIN
ballen	balde	V;IND;SG;1;PST
Oezbeeks	Oezbeeksere	ADJ;SPRL;INDF;NEUT;SG
kletsnat	kletsnattere	ADJ;CMPR;DEF
kwalijk	kwalijkere	ADJ;SPRL;INDF;NEUT;SG
drinken	dronke	V;SBJV;SG;PST
profiteren	profitere	V;SBJV;SG;PRS
bewonen	bewoon	V;IMP;SG
mondig	mondig	ADJ;INDF;NEUT;SG
gewelddadig	gewelddadig	ADJ;INDF;NEUT;SG
Iraans	Iraanser	ADJ;CMPR;INDF;PL
bebroeden	bebroede	V;SBJV;SG;PRS
kwijlen	kwijlde	V;IND;SG;2;PST
bruinachtig	bruinachtigste	ADJ;SPRL;INDF;PL
weven	weeft	V;IND;SG;3;PRS
bebouwen	bebouwen	V;IND;PL;PRS
verplaatsen	verplaatste	V;IND;SG;3;PST
redeneren	redeneert	V;IND;SG;3;PRS
aftelbaar	aftelbaar	ADJ;INDF;NEUT;SG
minzaam	minzamere	ADJ;SPRL;INDF;NEUT;SG
extra	extra	ADJ;DEF
behalen	behalen	V;NFIN
discrimineren	discrimineerde	V;IND;SG;3;PST
batsen	batst	V;IMP;PL
fouilleren	fouilleerde	V;IND;SG;1;PST
sneeuwen	sneeuwen	V;NFIN
behinderd	behinderdere	ADJ;CMPR;INDF;PL
indexeren	indexeer	V;IND;SG;1;PRS
spreiden	spreidde	V;IND;SG;1;PST
mopperen	moppert	V;IMP;PL
aristocratisch	aristocratische	ADJ;INDF;PL
gijzelen	gijzele	V;SBJV;SG;PRS
autochtoon	autochtoner	ADJ;CMPR;INDF;PL
mengelen	mengel	V;IMP;SG
compliceren	compliceerden	V;IND;PL;PST
sissen	siste	V;IND;SG;3;PST
dorsten	dorsten	V;SBJV;PL;PRS
verpanden	verpanden	V;NFIN
Perzisch	Perzischer	ADJ;CMPR;INDF;PL
onbetaalbaar	onbetaalbare	ADJ;DEF
baanbrekend	baanbrekende	ADJ;DEF
verzamelen	verzamelde	V;IND;SG;2;PST
verpieteren	verpieterd	V.PTCP;PST
maanogig	maanogige	ADJ;DEF
onterecht	onterechtere	ADJ;SPRL;INDF;NEUT;SG
compliceren	compliceer	V;IMP;SG
miezerig	miezerige	ADJ;DEF
harken	harkten	V;SBJV;PL;PST
veil	veile	ADJ;CMPR;INDF;NEUT;SG
kwiek	kwieke	ADJ;INDF;PL
vingeren	vingerde	V;SBJV;SG;PST
gematigd	gematigde	ADJ;DEF
gekscheren	gekscheert	V;IND;SG;2;PRS
bevaarbaar	bevaarbaardere	ADJ;SPRL;INDF;NEUT;SG
vereren	vereer	V;IND;SG;1;PRS
Israëlisch	Israëlischere	ADJ;SPRL;INDF;NEUT;SG
genereus	genereuze	ADJ;CMPR;INDF;NEUT;SG
Amerikaans	Amerikaans	ADJ;INDF;NEUT;SG
wenken	wenkte	V;IND;SG;1;PST
veroorzaken	veroorzaken	V;SBJV;PL;PRS
schrappen	schrappen	V;SBJV;PL;PRS
Italiaans	Italiaanste	ADJ;SPRL;DEF
ontruimen	ontruim	V;IMP;SG
ruien	ruien	V;SBJV;PL;PRS
genieten	genoten	V.PTCP;PST
lanceren	lanceerde	V;SBJV;SG;PST
onverzettelijk	onverzettelijk	ADJ;INDF;NEUT;SG
wrevelig	wreveligere	ADJ;SPRL;INDF;NEUT;SG
putten	put	V;IND;SG;3;PRS
getuigen	getuigde	V;IND;SG;1;PST
bekennen	bekende	V;IND;SG;3;PST
storen	stoorde	V;IND;SG;3;PST
herinneren	herinneren	V;SBJV;PL;PRS
identificeren	identificeer	V;IND;SG;1;PRS
aantrekkelijk	aantrekkelijke	ADJ;CMPR;INDF;NEUT;SG
slagen	slaagt	V;IND;SG;3;PRS
bevaarbaar	bevaarbaarder	ADJ;CMPR;INDF;PL
Amsterdams	Amsterdams	ADJ;INDF;NEUT;SG
nominatief	nominatieve	ADJ;DEF
treuren	treurden	V;IND;PL;PST
gestreept	gestreepte	ADJ;INDF;PL
zonnig	zonnigere	ADJ;SPRL;INDF;NEUT;SG
beklimmen	beklimt	V;IND;SG;2;PRS
financieel	financiële	ADJ;DEF
denkbaar	denkbaarste	ADJ;SPRL;DEF
centraliseren	centralisere	V;SBJV;SG;PRS
stijlvol	stijlvolle	ADJ;INDF;PL
verleiden	verleidt	V;IND;SG;3;PRS
miezeren	gemiezerd	V.PTCP;PST
blijkbaar	blijkbare	ADJ;CMPR;INDF;NEUT;SG
achtvoudig	achtvoudige	ADJ;DEF
kastijden	kastijd	V;IMP;SG
verlokken	verlokken	V;IND;PL;PRS
glaceren	glaceren	V;IND;PL;PRS
weergalmen	weergalmde	V;SBJV;SG;PST
traceren	traceerde	V;IND;SG;3;PST
meticuleus	meticuleuzere	ADJ;CMPR;DEF
bezichtigen	bezichtigen	V;NFIN
bogen	boogt	V;IMP;PL
telbaar	telbare	ADJ;INDF;PL
kerkelijk	kerkelijker	ADJ;CMPR;INDF;PL
interesseren	interesseerde	V;IND;SG;2;PST
indiscreet	indiscreetste	ADJ;SPRL;DEF
huiveringwekkend	huiveringwekkende	ADJ;CMPR;INDF;NEUT;SG
wraakzuchtig	wraakzuchtigste	ADJ;SPRL;INDF;PL
fel	felle	ADJ;INDF;PL
gevangen	gevangen	ADJ;INDF;NEUT;SG
onbeschrijfelijk	onbeschrijfelijkste	ADJ;SPRL;DEF
bedwelmen	bedwelme	V;SBJV;SG;PRS
tafelen	tafel	V;IMP;SG
ruwen	geruwd	V.PTCP;PST
harden	hardt	V;IND;SG;3;PRS
klassiek	klassieke	ADJ;INDF;PL
mokken	mok	V;IND;SG;1;PRS
wentelen	wentelde	V;IND;SG;1;PST
bedenken	bedenken	V;NFIN
attesteren	geattesteerd	V.PTCP;PST
vernielen	vernielde	V;IND;SG;2;PST
veronderstellen	veronderstelt	V;IMP;PL
grijnzen	grijnsde	V;IND;SG;2;PST
escorteren	escorteren	V;SBJV;PL;PRS
klutsen	kluts	V;IND;SG;1;PRS
ruw	ruwer	ADJ;CMPR;INDF;PL
dwingerig	dwingerig	ADJ;INDF;NEUT;SG
markeren	markeerde	V;SBJV;SG;PST
meedogenloos	meedogenloose	ADJ;DEF
dineren	dineerde	V;SBJV;SG;PST
interageren	geïnterageerd	V.PTCP;PST
behagen	behaagde	V;IND;SG;1;PST
geselen	geselt	V;IND;SG;3;PRS
abnormaal	abnormale	ADJ;INDF;PL
betaalbaar	betaalbaarste	ADJ;SPRL;DEF
dineren	dineerde	V;IND;SG;3;PST
happen	hapt	V;IND;SG;3;PRS
nijgen	negen	V;SBJV;PL;PST
bemannen	bemannen	V;NFIN
buizen	buist	V;IND;SG;2;PRS
ongevoelig	ongevoeligste	ADJ;SPRL;DEF
bescheiden	bescheidenste	ADJ;SPRL;DEF
spoken	gespookt	V.PTCP;PST
bedeesd	bedeesd	ADJ;INDF;NEUT;SG
gespen	gespt	V;IND;SG;3;PRS
regeren	regeert	V;IND;SG;2;PRS
formaliseren	formaliseer	V;IND;SG;1;PRS
Keltisch	Keltischere	ADJ;SPRL;INDF;NEUT;SG
erkennen	erkenne	V;SBJV;SG;PRS
Waals	Waalste	ADJ;SPRL;INDF;PL
bersten	gebersten	V.PTCP;PST
cederen	gecedeerd	V.PTCP;PST
verkleuren	verkleurt	V;IND;SG;2;PRS
gerechtigd	gerechtigde	ADJ;INDF;PL
eenparig	eenparigste	ADJ;SPRL;DEF
scharren	geschard	V.PTCP;PST
stokoud	stokoude	ADJ;INDF;PL
beramen	beraamt	V;IMP;PL
machtig	machtige	ADJ;DEF
Trojaans	Trojaanse	ADJ;DEF
sluikstorten	sluikstortte	V;IND;SG;1;PST
sissen	siste	V;IND;SG;1;PST
ontmoeten	ontmoet	V;IMP;PL
converseren	converseren	V;NFIN
centraliseren	centraliseerde	V;IND;SG;2;PST
volharden	volharden	V;NFIN
opereren	opereerden	V;IND;PL;PST
citeren	citeer	V;IMP;SG
catastrofaal	catastrofaler	ADJ;CMPR;INDF;PL
sappig	sappigere	ADJ;SPRL;INDF;NEUT;SG
poten	poot	V;IND;SG;2;PRS
fantaseren	fantaseerde	V;SBJV;SG;PST
flitsen	flitsten	V;IND;PL;PST
onherbergzaam	onherbergzaamste	ADJ;SPRL;INDF;PL
reviseren	reviseerde	V;IND;SG;1;PST
etaleren	etaleert	V;IMP;PL
onverslaanbaar	onverslaanbaarste	ADJ;SPRL;INDF;PL
talentvol	talentvole	ADJ;INDF;PL
ongeoorloofd	ongeoorloofdere	ADJ;SPRL;INDF;NEUT;SG
storen	store	V;SBJV;SG;PRS
trimmen	trimmen	V;SBJV;PL;PRS
vergroeien	vergroeit	V;IND;SG;2;PRS
verorberen	verorbere	V;SBJV;SG;PRS
happen	hap	V;IMP;SG
sluikstorten	sluikstortte	V;IND;SG;2;PST
emotioneren	emotioneerde	V;IND;SG;2;PST
hondachtig	hondachtigere	ADJ;CMPR;INDF;PL
bolrond	bolronde	ADJ;INDF;PL
moeten	moet	V;IMP;PL
kortdurend	kortdurende	ADJ;INDF;PL
falen	falen	V;NFIN
behelzen	behelst	V;IND;SG;2;PRS
verorberen	verorberen	V;SBJV;PL;PRS
benedictijner	benedictijner	ADJ;INDF;NEUT;SG
juridisch	juridisch	ADJ;INDF;NEUT;SG
perfect	perfect	ADJ;INDF;NEUT;SG
deprimeren	deprimeerden	V;IND;PL;PST
blank	blanke	ADJ;DEF
islamitisch	islamitischere	ADJ;SPRL;INDF;NEUT;SG
generaliseren	generalisere	V;SBJV;SG;PRS
realistisch	realistischer	ADJ;CMPR;INDF;PL
wurmen	wurmen	V;IND;PL;PRS
bogen	boog	V;IMP;SG
striemen	striemt	V;IND;SG;3;PRS
behandelen	behandelen	V;IND;PL;PRS
kritiseren	kritiseer	V;IND;SG;1;PRS
kunstig	kunstige	ADJ;INDF;PL
treuren	treur	V;IND;SG;1;PRS
schunnig	schunnigere	ADJ;SPRL;INDF;NEUT;SG
luw	luwste	ADJ;SPRL;DEF
slaperig	slaperigste	ADJ;SPRL;DEF
herkansen	herkansten	V;IND;PL;PST
lichtbruin	lichtbruinere	ADJ;SPRL;INDF;NEUT;SG
zwoegen	zwoegt	V;IMP;PL
verkloten	verklote	V;SBJV;SG;PRS
volharden	volhardt	V;IND;SG;2;PRS
zullen	zoude	V;SBJV;SG;PST
zogenaamd	zogenaamd	ADJ;INDF;NEUT;SG
beklemtonen	beklemtonen	V;IND;PL;PRS
aalglad	aalgladdere	ADJ;SPRL;INDF;NEUT;SG
rapen	raapte	V;SBJV;SG;PST
cynisch	cynischte	ADJ;SPRL;DEF
stoffelijk	stoffelijkste	ADJ;SPRL;INDF;PL
huilebalken	huilebalken	V;IND;PL;PRS
ontwarren	ontwarren	V;IND;PL;PRS
kaarten	kaartte	V;IND;SG;1;PST
gedegen	gedegen	ADJ;DEF
glijden	glijdt	V;IND;SG;2;PRS
onweren	onweerde	V;IND;SG;3;PST
gemeenzaam	gemeenzaam	ADJ;INDF;NEUT;SG
miskennen	miskend	V.PTCP;PST
beplakken	beplakten	V;SBJV;PL;PST
neuspeuteren	neuspeutert	V;IMP;PL
polijsten	polijst	V;IND;SG;2;PRS
artificieel	artificiëlere	ADJ;CMPR;DEF
invalide	invalide	ADJ;CMPR;INDF;NEUT;SG
industrialiseren	industrialiseerde	V;SBJV;SG;PST
prophylactisch	prophylactischer	ADJ;CMPR;INDF;NEUT;SG
onnozel	onnozelere	ADJ;SPRL;INDF;NEUT;SG
versturen	versture	V;SBJV;SG;PRS
oostelijk	oostelijkere	ADJ;CMPR;DEF
bedroeven	bedroefde	V;SBJV;SG;PST
overslaan	oversloeg	V;IND;SG;3;PST
smijten	smeet	V;IND;SG;2;PST
