бейә	бейә	N;NOM;SG
миләш	миләштән	N;ABL;SG
кесе йома	кесе йоманы	N;ACC;DEF;SG
аждаһа	аждаһалар	N;NOM;PL
пәйғәмбәр	пәйғәмбәрҙәрҙә	N;LOC;PL
ҡәбер	ҡәберҙе	N;ACC;DEF;SG
баш мәҡәлә	баш мәҡәләләр	N;NOM;PL
кәйеф	кәйефтән	N;ABL;SG
яры	ярынан	N;ABL;SG
ҡоро ер	ҡоро ергә	N;DAT;SG
ауырыу	ауырыуҙарҙың	ADJ;GEN;DEF;PL
ожмах	ожмахтарҙың	N;GEN;DEF;PL
ҡоротҡос	ҡоротҡосҡа	N;DAT;SG
күргәҙмә	күргәҙмәлә	N;LOC;SG
селән	селәндән	N;ABL;SG
ташбаҡа	ташбаҡала	N;LOC;SG
опто	оптола	N;LOC;SG
йөкмәтке	йөкмәткегә	N;DAT;SG
фатир	фатирҙан	N;ABL;SG
балаҫ	балаҫтарҙың	N;GEN;DEF;PL
ултырғыс	ултырғыс	N;NOM;SG
тәгәрмәс	тәгәрмәс	N;NOM;SG
күт	күт	N;DAT;SG
эремсек	эремсектә	N;LOC;SG
милли көрәш	милли көрәштән	N;ABL;SG
һурпа	һурпа	N;DAT;SG
шишәмбе	шишәмбеләрҙе	N;ACC;DEF;PL
Саян	Саяндарҙың	N;GEN;DEF;PL
әлморон	әлморондоң	N;GEN;DEF;SG
ғаилә	ғаиләнән	N;ABL;SG
мыйыҡ	мыйыҡтарҙы	N;ACC;DEF;PL
энә	энәләрҙә	N;LOC;PL
һүҙлек	һүҙлектәр	N;NOM;PL
фәрештә	фәрештәне	N;ACC;DEF;SG
баш	баштарға	N;DAT;PL
башҡорт	башҡорттоң	N;GEN;DEF;SG
сәскә	сәскәләр	N;NOM;PL
яҙма	яҙмаларға	N;DAT;PL
морон	морондоң	N;GEN;DEF;SG
бырау	бырауҙарға	N;DAT;PL
яуап	яуапты	N;ACC;DEF;SG
тау	тауҙан	N;ABL;SG
тирмә	тирмәлә	N;LOC;SG
килеш	килештән	N;ABL;SG
мәҙрәсә	мәҙрәсә	N;ACC;DEF;PL
хәйерсе	хәйерсе	N;NOM;SG
фәлсәфә	фәлсәфәләрҙән	N;ABL;PL
диуар	диуарҙарға	N;DAT;PL
ең	еңгә	N;DAT;SG
буҫаға	буҫағаларҙа	N;LOC;PL
байрам	байрамдарҙан	N;ABL;PL
ярҙам	ярҙамда	N;LOC;SG
күгәүен	күгәүендәргә	N;DAT;PL
замана	заманала	N;LOC;SG
миләш	миләштең	N;GEN;DEF;SG
Ҡыҫала	Ҡыҫаланың	N;GEN;DEF;SG
салбар	салбарҙарҙы	N;ACC;DEF;PL
ниәт	ниәтте	N;ACC;DEF;SG
йондоҙ	йондоҙҙарҙың	N;GEN;DEF;PL
күләгә	күләгәләр	N;NOM;PL
ҡатын	ҡатындарҙың	N;GEN;DEF;PL
табут	табут	N;GEN;DEF;SG
рәссам	рәссамға	N;DAT;SG
тәм	тәмдәрҙе	N;ACC;DEF;PL
башватҡыс	башватҡыстарҙың	N;GEN;DEF;PL
тирәк	тирәккә	N;DAT;SG
сәбәп	сәбәптәргә	N;DAT;PL
көл	көлдө	N;ACC;DEF;SG
урта	урталарҙа	ADJ;LOC;PL
ҡылыс	ҡылыстарҙы	N;ACC;DEF;PL
күрше	күршенең	N;GEN;DEF;SG
керпек	керпектә	N;LOC;SG
мәсьәлә	мәсьәләләрҙә	N;LOC;PL
болан	боландың	N;GEN;DEF;SG
елен	елендәрҙән	N;ABL;PL
шаҡмаҡ	шаҡмаҡтың	N;GEN;DEF;SG
балтырған	балтырған	N;NOM;SG
һандыҡ	һандыҡтарға	N;DAT;PL
дәрәжә	дәрәжәнән	N;ABL;SG
мылтыҡ	мылтыҡтарҙан	N;ABL;PL
көйәнтә	көйәнтәләргә	N;DAT;PL
аш	аштарҙың	N;GEN;DEF;PL
күбек	күбектең	N;GEN;DEF;SG
ҡарға	ҡарғаның	N;GEN;DEF;SG
кесе йома	кесе йоманан	N;ABL;SG
ҡарт	ҡарттарҙың	N;GEN;DEF;PL
ағай	ағайҙа	N;LOC;SG
төйөн	төйөндәргә	N;DAT;PL
ҡалып	ҡалыпта	N;LOC;SG
ҡамыр	ҡамырҙан	N;ABL;SG
ата-әсә	ата-әсәлә	N;LOC;SG
көҙгө	көҙгөнөң	N;GEN;DEF;SG
бәрәңге	бәрәңгенең	N;GEN;DEF;SG
торош	тороштарҙы	N;ACC;DEF;PL
ҡош-ҡорт	ҡош-ҡорт	N;NOM;SG
аҙаҡ	аҙаҡтарға	N;DAT;PL
редакция	редакцияларҙың	N;GEN;DEF;PL
сәңгелдәк	сәңгелдәктәр	N;NOM;PL
ғүмер	ғүмерҙәргә	N;DAT;PL
минут	минут	N;NOM;PL
уғры	уғрыларҙан	N;ABL;PL
бәрҙе	бәрҙегә	N;DAT;SG
дым	дымдан	N;ABL;SG
баҡса	баҡсаны	N;ACC;DEF;SG
әжәл	әжәлдәр	N;NOM;PL
ҡымыҙ	ҡымыҙға	N;DAT;SG
шәриғәт	шәриғәтте	N;ACC;DEF;SG
ялан	яландан	ADJ;ABL;SG
өйрәк	өйрәктәрҙә	N;LOC;PL
бөрсә	бөрсәләрҙе	N;ACC;DEF;PL
байрам	байрамды	N;ACC;DEF;SG
тамаша	тамашанан	N;ABL;SG
инсан	инсандәрҙең	N;GEN;DEF;PL
сыр	сыр	N;NOM;SG
алҡыш	алҡыштың	N;GEN;DEF;SG
бау	бау	N;NOM;SG
эсәк	эсәкте	N;ACC;DEF;SG
йәтим	йәтим	N;DAT;SG
ҡаш	ҡаштарҙа	N;LOC;PL
яуап	яуапта	N;LOC;SG
дауыл	дауылды	N;ACC;DEF;SG
кирбес	кирбестән	N;ABL;SG
ҡауҙы	ҡауҙыларға	N;DAT;PL
һәйкәл	һәйкәл	N;NOM;SG
эйәк	эйәктәрҙе	N;ACC;DEF;PL
үҙәк	үҙәктәр	N;NOM;PL
ерек	еректә	N;LOC;SG
урта быуат	урта быуат	ADJ;NOM;SG
ҡорбан	ҡорбандарҙы	N;ACC;DEF;PL
сәйәхәт	сәйәхәттәрҙән	N;ABL;PL
хәреф	хәрефкә	N;DAT;SG
дәүләт	дәүләттәрҙең	ADJ;GEN;DEF;PL
ҡәбер	ҡәберҙә	N;LOC;SG
һунар	һунарҙарҙа	N;LOC;PL
айыу	айыу	N;NOM;SG
тамаша	тамашаға	N;DAT;SG
балаҡ	балаҡтарҙың	N;GEN;DEF;PL
һабын	һабындан	N;ABL;SG
бил	бил	N;GEN;DEF;SG
самолёт	самолёттарҙың	N;GEN;DEF;PL
әҙәм	әҙәмдән	N;ABL;SG
инсан	инсандәр	N;NOM;PL
ҡаш	ҡашта	N;LOC;SG
рәҡәғәт	рәҡәғәттәр	N;NOM;PL
сирек	сиректәрҙән	N;ABL;PL
мейес	мейестәр	N;NOM;PL
бурыс	бурысҡа	N;DAT;SG
бей	бейҙе	N;ACC;DEF;SG
боҙбармаҡ	боҙбармаҡта	N;LOC;SG
сәбәп	сәбәптән	N;ABL;SG
йәйғор	йәйғорҙан	N;ABL;SG
ынйы	ынйылар	N;NOM;PL
һупайҙы	һупайҙыларҙың	N;GEN;DEF;PL
аҙналыҡ	аҙналыҡтар	N;NOM;PL
аҡбур	аҡбур	N;LOC;SG
тамашасы	тамашасыларҙа	N;LOC;PL
башватҡыс	башватҡыстар	N;NOM;PL
сер	серҙәр	N;NOM;PL
кәштә	кәштәлә	N;LOC;SG
үҙәк	үҙәктең	N;GEN;DEF;SG
хеҙмәт	хеҙмәттең	N;GEN;DEF;SG
алтын	алтындан	N;ABL;SG
даирә	даирәләрҙә	N;LOC;PL
ашъяулыҡ	ашъяулыҡ	N;NOM;SG
ат	ат	N;NOM;SG
эсәк	эсәктәрҙә	N;LOC;PL
намаҙ	намаҙҙан	N;ABL;SG
алма	алманан	N;ABL;SG
туғай	туғайҙарға	N;DAT;PL
аҙыҡ	аҙыҡтан	N;ABL;SG
ҡаш	ҡаштарҙан	N;ABL;PL
ҡалҡан	ҡалҡандарҙы	N;ACC;DEF;PL
тирмә	тирмә	N;NOM;SG
һал	һалдарға	N;DAT;PL
һөҙөмтә	һөҙөмтә	N;GEN;DEF;SG
таш	таш	N;NOM;SG
тәгәрмәс	тәгәрмәстәргә	N;DAT;PL
эшҡыуар	эшҡыуарҙың	N;GEN;DEF;SG
маймыл	маймыл	N;NOM;SG
ирен	ирендәрҙә	N;LOC;PL
былау	былауҙа	N;LOC;SG
аҙыҡ	аҙыҡты	N;ACC;DEF;SG
шишә	шишәлә	N;LOC;SG
йәһәннәм	йәһәннәмдә	N;LOC;SG
эне	энене	N;ACC;DEF;SG
нур	нур	N;NOM;PL
иғтибар	иғтибарҙы	N;ACC;DEF;SG
бәке	бәкене	N;ACC;DEF;SG
милләт	милләттең	N;GEN;DEF;SG
нөктә	нөктәлә	N;LOC;SG
ҡурғаш	ҡурғаштың	N;GEN;DEF;SG
быҙау	быҙауҙа	N;LOC;SG
сейә	сейәне	N;ACC;DEF;SG
тәбиғәт	тәбиғәтте	N;ACC;DEF;SG
һупылдаҡ	һупылдаҡтарҙан	N;ABL;PL
энә	энәгә	N;DAT;SG
яры	ярыла	N;LOC;SG
тәгәрмәс	тәгәрмәсте	N;ACC;DEF;SG
тыҡрыҡ	тыҡрыҡтың	N;GEN;DEF;SG
турғай	турғайға	N;DAT;SG
буйҙаҡ	буйҙаҡ	N;NOM;SG
сепрәк	сепрәктәрҙең	N;GEN;DEF;PL
эскәмйә	эскәмйәнән	N;ABL;SG
бауыр	бауырҙа	N;LOC;SG
йәшелсә	йәшелсәне	N;ACC;DEF;SG
һум	һум	N;DAT;PL
кеше	кешеләрҙән	N;ABL;PL
тоҙ	тоҙҙан	N;ABL;SG
күләм	күләмгә	N;DAT;SG
өмөт	өмөттө	N;ACC;DEF;SG
юйғыс	юйғыстан	N;ABL;SG
болан	боланда	N;LOC;SG
һабаҡ	һабаҡ	N;NOM;SG
боҙ	боҙ	N;NOM;SG
бәшмәк	бәшмәктәр	N;NOM;PL
дарыухана	дарыуханаларға	N;DAT;PL
тәһәрәт	тәһәрәттән	N;ABL;SG
ҡая	ҡаяға	N;DAT;SG
ялыу	ялыуҙар	N;NOM;PL
дәүләт	дәүләт	N;NOM;SG
башҡала	башҡала	N;NOM;SG
һарымһаҡ	һарымһаҡҡа	N;DAT;SG
бырау	бырауҙы	N;ACC;DEF;SG
Балыҡ	Балыҡты	N;ACC;DEF;SG
диуар	диуарҙарҙан	N;ABL;PL
байтал	байталдарҙан	N;ABL;PL
айҙар	айҙарҙарҙы	N;ACC;DEF;PL
салғы	салғыларҙың	N;GEN;DEF;PL
бәндә	бәндәдәрҙә	N;LOC;PL
тамашасы	тамашасыны	N;ACC;DEF;SG
ойошма	ойошманың	N;GEN;DEF;SG
ең	ең	N;NOM;SG
тау	тауҙарға	N;DAT;PL
ҡорбан	ҡорбандарға	N;DAT;PL
итәк	итәктәр	N;NOM;PL
арпа	арпанан	N;ABL;SG
тишек	тишектәрҙә	ADJ;LOC;PL
киле	килегә	N;DAT;SG
елен	елендең	N;GEN;DEF;SG
ҡаҙ	ҡаҙҙа	N;LOC;SG
мәҙрәсә	мәҙрәсә	N;GEN;DEF;PL
таж	таждан	N;ABL;SG
сәүкә	сәүкәнән	N;ABL;SG
дәрес	дәрестә	N;LOC;SG
шырау	шырауҙарҙың	N;GEN;DEF;PL
һөлдә	һөлдәләрҙән	N;ABL;PL
юйғыс	юйғыстарҙа	N;LOC;PL
һаҡал	һаҡалдарҙы	N;ACC;DEF;PL
төҫ	төҫтәрҙә	N;LOC;PL
күбек	күбектәргә	N;DAT;PL
һупылдаҡ	һупылдаҡтарҙы	N;ACC;DEF;PL
шишәмбе	шишәмбене	N;ACC;DEF;SG
әсәй	әсәйҙәр	N;NOM;PL
һауа	һауала	N;LOC;SG
кесе йома	кесе йомаларҙан	N;ABL;PL
һуҡыр сысҡан	һуҡыр сысҡанды	N;ACC;DEF;SG
ҡыпсыуыр	ҡыпсыуырҙы	N;ACC;DEF;SG
сепрәк	сепрәк	N;NOM;SG
яуап	яуаптарҙың	N;GEN;DEF;PL
рашҡы	рашҡынан	N;ABL;SG
тәрилкә	тәрилкәгә	N;DAT;SG
уҡ	уҡ	N;ABL;SG
буш ваҡыт	буш ваҡытты	N;ACC;DEF;SG
ҡәбер	ҡәберҙәр	N;NOM;PL
сиркәү	сиркәүҙә	ADJ;LOC;SG
баш бармаҡ	баш бармаҡтарҙың	N;GEN;DEF;PL
еңгә	еңгә	N;DAT;PL
ҡайнатма	ҡайнатманан	N;ABL;SG
ярҙамсы	ярҙамсыларҙа	N;LOC;PL
билдә	билдәләрҙән	N;ABL;PL
ҡая	ҡая	N;NOM;SG
мәктәп	мәктәпте	N;ACC;DEF;SG
урта	урталарҙа	N;LOC;PL
банан	бананда	N;LOC;SG
ташҡын	ташҡындарҙың	N;GEN;DEF;PL
һемәк	һемәктәрҙә	N;LOC;PL
болан	боландарҙан	N;ABL;PL
ботаҡ	ботаҡта	N;LOC;SG
болот	болоттарҙа	N;LOC;PL
әбей	әбейҙәрҙе	N;ACC;DEF;PL
яҡты	яҡтыны	N;ACC;DEF;SG
һинд	һиндтар	N;NOM;PL
бырау	бырауҙан	N;ABL;SG
өмөт	өмөткә	N;DAT;SG
серәкәй	серәкәйҙе	N;ACC;DEF;SG
дарыу	дарыу	N;NOM;SG
хәҡиҡәт	хәҡиҡәтте	N;ACC;DEF;SG
йомран	йомранға	N;DAT;SG
үтек	үтек	N;NOM;SG
кәңәш	кәңәштәрҙән	N;ABL;PL
һурпа	һурпа	N;NOM;SG
арҡа	арҡаларҙан	N;ABL;PL
әсәй	әсәйҙәрҙе	N;ACC;DEF;PL
каруан	каруандың	N;GEN;DEF;SG
ҡыяр	ҡыяр	N;NOM;SG
ауыл	ауылдарҙа	N;LOC;PL
буҫтау	буҫтау	N;NOM;SG
үҫемлек	үҫемлеккә	N;DAT;SG
талпан	талпандар	N;NOM;PL
урта	уртанан	N;ABL;SG
йүнәлеш	йүнәлеште	N;ACC;DEF;SG
ағай-эне	ағай-энеләр	N;NOM;PL
күләгә	күләгәләрҙе	N;ACC;DEF;PL
мәсет	мәсеттәрҙән	N;ABL;PL
тәҙрә	тәҙрәләр	N;NOM;PL
Ҡыҫала	Ҡыҫалаларҙан	N;ABL;PL
рәссам	рәссам	N;NOM;SG
туй	туй	N;NOM;SG
мәғәнә	мәғәнәләрҙе	N;ACC;DEF;PL
киләсәк	киләсәктең	N;GEN;DEF;SG
таҡмаҡ	таҡмаҡтарҙы	N;ACC;DEF;PL
эйәк	эйәктә	N;LOC;SG
күркә	күркәнең	N;GEN;DEF;SG
бауырһаҡ	бауырһаҡтан	N;ABL;SG
рашҡы	рашҡы	N;DAT;SG
салбар	салбарҙарға	N;DAT;PL
тиреҫ	тиреҫтә	N;LOC;SG
умарта	умарталарға	N;DAT;PL
йәшелсә	йәшелсәгә	N;DAT;SG
һүҙ	һүҙ	N;GEN;DEF;PL
тотҡа	тотҡа	N;GEN;DEF;SG
уҡытыусы	уҡытыусы	N;NOM;SG
ҡунаҡхана	ҡунаҡхананан	N;ABL;SG
шаҡмаҡ	шаҡмаҡтар	N;NOM;PL
кесе аҙна	кесе аҙнанан	N;ABL;SG
ужым	ужымды	N;ACC;DEF;SG
туй	туй	N;DAT;PL
батырлыҡ	батырлыҡты	N;ACC;DEF;SG
тел	телде	N;ACC;DEF;SG
йәһәннәм	йәһәннәмдәр	N;NOM;PL
туҙан	туҙандың	N;GEN;DEF;SG
сиркәү	сиркәүҙе	N;ACC;DEF;SG
ташҡын	ташҡындарҙы	N;ACC;DEF;PL
бала	бала	N;NOM;SG
ойошма	ойошманан	N;ABL;SG
тин	тин	N;ABL;PL
абруй	абруй	N;ABL;SG
тартма	тартмала	N;LOC;SG
яҡ	яҡтарҙың	N;GEN;DEF;PL
күстәнәс	күстәнәстә	N;LOC;SG
өлкә	өлкәләрҙең	N;GEN;DEF;PL
себен	себендәргә	N;DAT;PL
Ҡыҙ	Ҡыҙға	N;DAT;SG
йәннәт	йәннәттәрҙән	N;ABL;PL
секунд	секунд	N;ACC;DEF;PL
орлоҡ	орлоҡтарҙан	N;ABL;PL
зыярат	зыярат	N;NOM;SG
яңылыҡ	яңылыҡта	N;LOC;SG
бураҙна	бураҙналарҙы	N;ACC;DEF;PL
ярҙам	ярҙамдың	N;GEN;DEF;SG
кесе аҙна	кесе аҙнаны	N;ACC;DEF;SG
сәбәп	сәбәптең	N;GEN;DEF;SG
Ҡыҙ	Ҡыҙҙарҙың	N;GEN;DEF;PL
йәшелсә	йәшелсәнән	N;ABL;SG
миҙгел	миҙгелдәргә	N;DAT;PL
ҡулаҡса	ҡулаҡсаларға	N;DAT;PL
маймыл	маймылда	N;LOC;SG
хыял	хыялдарҙа	N;LOC;PL
аҙыҡ-түлек	аҙыҡ-түлектәрҙән	N;ABL;PL
хикәйә	хикәйәгә	N;DAT;SG
күн	күн	N;GEN;DEF;SG
күгәүен	күгәүенгә	N;DAT;SG
ниәт	ниәткә	N;DAT;SG
аҙналыҡ	аҙналыҡтарға	N;DAT;PL
башватҡыс	башватҡыстың	N;GEN;DEF;SG
себен	себен	N;NOM;SG
алҡыш	алҡыштар	N;NOM;PL
күргәҙмә	күргәҙмәнән	N;ABL;SG
бата	батала	N;LOC;SG
өтөр	өтөрҙәрҙә	N;LOC;PL
һинд	һиндты	N;ACC;DEF;SG
ирек	ирек	N;NOM;SG
ҡул	ҡул	N;ACC;DEF;SG
көрәш	көрәшкә	N;DAT;SG
урман	урман	N;NOM;SG
тәнәфес	тәнәфестәрҙә	N;LOC;PL
сыйырсыҡ	сыйырсыҡты	N;ACC;DEF;SG
көйә	көйәнән	N;ABL;SG
ғөрөф-ғәҙәт	ғөрөф-ғәҙәттә	N;LOC;SG
ҡаҙаныш	ҡаҙаныштың	N;GEN;DEF;SG
хәҡиҡәт	хәҡиҡәттәрҙән	N;ABL;PL
ҡарлуғас	ҡарлуғастың	N;GEN;DEF;SG
ихтилал	ихтилалда	N;LOC;SG
тау	тауҙы	N;ACC;DEF;SG
аҙыҡ-түлек	аҙыҡ-түлектең	N;GEN;DEF;SG
йоҙроҡ	йоҙроҡтарҙың	N;GEN;DEF;PL
ярғанат	ярғанат	N;NOM;SG
бәхәс	бәхәстәргә	N;DAT;PL
кәшәнә	кәшәнәләрҙең	N;GEN;DEF;PL
шәриғәт	шәриғәт	N;NOM;SG
баҡсасы	баҡсасыларҙы	N;ACC;DEF;PL
шағирә	шағирәләрҙә	N;LOC;PL
яҡ	яҡтарҙы	N;ACC;DEF;PL
он	онға	N;DAT;SG
дауыл	дауылдан	N;ABL;SG
йәтим	йәтим	N;ABL;SG
өйрәк	өйрәктең	N;GEN;DEF;SG
йырсы	йырсыларҙың	N;GEN;DEF;PL
ожмах	ожмахты	N;ACC;DEF;SG
таң	таңдан	N;ABL;SG
йоҙроҡ	йоҙроҡҡа	N;DAT;SG
йәтим	йәтим	N;NOM;PL
бәйләүес	бәйләүестәрҙә	N;LOC;PL
һаҙ	һаҙҙар	N;NOM;PL
сыр	сырҙарға	N;DAT;PL
салғы	салғыны	N;ACC;DEF;SG
нәтижә	нәтижәләрҙең	N;GEN;DEF;PL
тырма	тырмаларҙан	N;ABL;PL
шиғриәт	шиғриәттең	N;GEN;DEF;SG
тәһәрәт	тәһәрәттәрҙән	N;ABL;PL
йәннәт	йәннәттәргә	N;DAT;PL
һейҙек	һейҙек	N;NOM;SG
иғтибар	иғтибарҙар	N;NOM;PL
выждан	выжданда	N;LOC;SG
көл	көлдәр	N;NOM;PL
алтын	алтын	N;NOM;SG
тыныслыҡ	тыныслыҡтарҙың	N;GEN;DEF;PL
хыял	хыялда	N;LOC;SG
этморон	этморондоң	N;GEN;DEF;SG
бесәй	бесәйҙәрҙә	N;LOC;PL
уғры	уғрыларҙа	N;LOC;PL
шаһит	шаһит	N;LOC;SG
хайуан	хайуандарҙың	N;GEN;DEF;PL
тарма	тарманан	N;ABL;SG
оя	ояларҙа	N;LOC;PL
тирмә	тирмәләргә	N;DAT;PL
ашхана	ашханаларҙа	N;LOC;PL
шырау	шырауҙы	N;ACC;DEF;SG
йәй	йәйҙәрҙе	N;ACC;DEF;PL
балыҡсы	балыҡсы	N;NOM;SG
сеймал	сеймалға	N;DAT;SG
ауырыу	ауырыуҙан	N;ABL;SG
игәү	игәүҙән	N;ABL;SG
ярҙамсы	ярҙамсыны	N;ACC;DEF;SG
мөгөҙ	мөгөҙҙө	N;ACC;DEF;SG
эш	эш	N;NOM;PL
ярымутрау	ярымутрауҙың	N;GEN;DEF;SG
еңгә	еңгә	N;GEN;DEF;SG
баш мәҡәлә	баш мәҡәлә	N;NOM;SG
һунар	һунарға	N;DAT;SG
шарт	шарт	N;NOM;SG
айғыр	айғырҙарҙы	N;ACC;DEF;PL
ҡағыҙ	ҡағыҙҙан	N;ABL;SG
биҙәк	биҙәккә	N;DAT;SG
морон	моронға	N;DAT;SG
ауыл	ауылдарҙы	ADJ;ACC;DEF;PL
тауар	тауарҙарҙан	N;ABL;PL
күбек	күбектән	N;ABL;SG
иҡтисад	иҡтисадтан	N;ABL;SG
Балыҡ	Балыҡтарҙа	N;LOC;PL
Ҡуҙы	Ҡуҙылар	N;NOM;PL
сысҡан	сысҡандың	N;GEN;DEF;SG
таҫма	таҫма	N;ABL;SG
бала	балаларҙы	N;ACC;DEF;PL
һыу	һыуҙарға	N;DAT;PL
ир-ат	ир-аттарҙы	N;ACC;DEF;PL
умарта	умартаның	N;GEN;DEF;SG
ҡарғыш	ҡарғыштың	N;GEN;DEF;SG
йыуа	йыуа	N;ACC;DEF;SG
быуын	быуындың	N;GEN;DEF;SG
йөкмәтке	йөкмәткеләрҙе	N;ACC;DEF;PL
умарта	умарталар	N;NOM;PL
әшнә	әшнәне	N;ACC;DEF;SG
тәрилкә	тәрилкәлә	N;LOC;SG
ботаҡ	ботаҡтарҙы	N;ACC;DEF;PL
көйәнтә	көйәнтәнең	N;GEN;DEF;SG
кейем	кейемдә	N;LOC;SG
бей	бейҙә	N;LOC;SG
үлән	үләндәрҙән	N;ABL;PL
бәрәкәт	бәрәкәт	N;NOM;SG
бөрсә	бөрсәләрҙең	N;GEN;DEF;PL
абруй	абруй	N;DAT;SG
аҙыҡ	аҙыҡҡа	N;DAT;SG
хужа	хужаларҙың	N;GEN;DEF;PL
кеҫә	кеҫәләрҙән	N;ABL;PL
Алла	Алла	N;DAT;SG
синыф	синыфты	N;ACC;DEF;SG
сыбыҡ	сыбыҡта	N;LOC;SG
үҙәк	үҙәкте	N;ACC;DEF;SG
әбей	әбейҙән	N;ABL;SG
хәбәрсе	хәбәрселәрҙең	N;GEN;DEF;PL
ураҡ	ураҡтар	N;NOM;PL
симешкә	симешкәлә	N;LOC;SG
нисбәт	нисбәттәрҙән	N;ABL;PL
хужа	хужаларҙы	N;ACC;DEF;PL
яҫмыҡ	яҫмыҡтың	N;GEN;DEF;SG
ниәт	ниәттәрҙән	N;ABL;PL
инша	иншаларҙан	N;ABL;PL
тәсбих	тәсбих	N;GEN;DEF;PL
быуын	быуынға	N;DAT;SG
ҡарлуғас	ҡарлуғастан	N;ABL;SG
тыҡрыҡ	тыҡрыҡтарҙа	N;LOC;PL
көрәш	көрәштәрҙе	N;ACC;DEF;PL
балыҡсы	балыҡсыларҙың	N;GEN;DEF;PL
тишек	тишектең	N;GEN;DEF;SG
минут	минут	N;GEN;DEF;PL
миләүшә	миләүшәләргә	N;DAT;PL
төбәк	төбәктәргә	N;DAT;PL
баш	баштарҙы	N;ACC;DEF;PL
күбек	күбектәрҙә	N;LOC;PL
һабын	һабын	N;NOM;SG
фәрештә	фәрештә	N;NOM;SG
буйҙаҡ	буйҙаҡты	ADJ;ACC;DEF;SG
ауыл	ауылдарҙан	N;ABL;PL
арба	арбаларҙа	N;LOC;PL
осраҡ	осраҡтар	N;NOM;PL
быяла	быялаларҙы	N;ACC;DEF;PL
урман	урманды	N;ACC;DEF;SG
синыф	синыфтарҙы	N;ACC;DEF;PL
ҡом	ҡомда	N;LOC;SG
ялан	яландарға	ADJ;DAT;PL
бүләк	бүләккә	N;DAT;SG
ҡоҙоҡ	ҡоҙоҡта	N;LOC;SG
әҙәм	әҙәмдәрҙе	N;ACC;DEF;PL
алҡыш	алҡыштарҙы	N;ACC;DEF;PL
мейе	мейегә	N;DAT;SG
эйәк	эйәктәргә	N;DAT;PL
бәйләүес	бәйләүескә	N;DAT;SG
иғтибар	иғтибар	N;NOM;SG
сәнғәт	сәнғәттәрҙән	N;ABL;PL
ай	айҙарға	N;DAT;PL
кесе йома	кесе йоманың	N;GEN;DEF;SG
имсәк	имсәктәрҙән	N;ABL;PL
маңҡа	маңҡа	N;NOM;SG
ыласын	ыласындың	N;GEN;DEF;SG
төймә	төймәләрҙең	N;GEN;DEF;PL
ҡойо	ҡойонан	N;ABL;SG
хоҡуҡ	хоҡуҡ	N;ABL;SG
сысҡан	сысҡандарҙан	N;ABL;PL
балта	балтаны	N;ACC;DEF;SG
һуҡыр сысҡан	һуҡыр сысҡанда	N;LOC;SG
алма	алманың	N;GEN;DEF;SG
форсат	форсаттарҙың	N;GEN;DEF;PL
бутҡа	бутҡаның	N;GEN;DEF;SG
төбәк	төбәктәрҙә	N;LOC;PL
ҡоролоҡ	ҡоролоҡтар	N;NOM;PL
сәскә	сәскәләрҙән	N;ABL;PL
тотҡа	тотҡа	N;LOC;SG
ҡалҡан	ҡалҡандың	N;GEN;DEF;SG
күҙлек	күҙлектәрҙән	N;ABL;PL
тәһәрәт	тәһәрәттә	N;LOC;SG
ямғыр	ямғырҙы	N;ACC;DEF;SG
талпан	талпандарҙың	N;GEN;DEF;PL
аҙыҡ	аҙыҡтың	N;GEN;DEF;SG
мөгөҙ	мөгөҙҙәрҙә	N;LOC;PL
яра	яраны	N;ACC;DEF;SG
тәҡдир	тәҡдир	N;ABL;PL
йүгән	йүгәндәрҙе	N;ACC;DEF;PL
һағыҙ	һағыҙҙы	N;ACC;DEF;SG
һылыу	һылыуҙарҙы	N;ACC;DEF;PL
тумыртҡа	тумыртҡа	N;NOM;SG
мәжүси	мәжүсиҙәрҙе	N;ACC;DEF;PL
йомран	йомрандарҙы	N;ACC;DEF;PL
орҙоҡ	орҙоҡларҙың	N;GEN;DEF;PL
хәйер	хәйерҙәрҙән	N;ABL;PL
ялыу	ялыуҙан	N;ABL;SG
күләм	күләмдәрҙә	N;LOC;PL
тишек	тишектәр	ADJ;NOM;PL
балаҫ	балаҫтарға	N;DAT;PL
йәннәт	йәннәттең	N;GEN;DEF;SG
дәрес	дәрестәрҙә	N;LOC;PL
аҡман-тоҡман	аҡман-тоҡманда	N;LOC;SG
йырсы	йырсынан	N;ABL;SG
фәлсәфә	фәлсәфәләр	N;NOM;PL
нөктә	нөктәләрҙе	N;ACC;DEF;PL
сәүкә	сәүкәләрҙән	N;ABL;PL
билдә	билдәләрҙә	N;LOC;PL
ыласын	ыласындар	N;NOM;PL
тин	тин	N;GEN;DEF;SG
каса	касала	N;LOC;SG
кәмә	кәмәләрҙән	N;ABL;PL
арҡан	арҡандарҙа	N;LOC;PL
яры	ярыға	N;DAT;SG
кисә	кисә	N;GEN;DEF;PL
үҫенте	үҫентелә	N;LOC;SG
уйын	уйындарҙан	N;ABL;PL
редакция	редакция	N;NOM;SG
эйәк	эйәкте	N;ACC;DEF;SG
ҡыпһыуыр	ҡыпһыуырҙарҙы	N;ACC;DEF;PL
норма	нормалар	N;NOM;PL
муйыл	муйылды	N;ACC;DEF;SG
тир	тир	N;ACC;DEF;SG
балаҫ	балаҫтан	N;ABL;SG
шағирә	шағирә	N;NOM;SG
гәүһәр	гәүһәрҙе	N;ACC;DEF;SG
намаҙлыҡ	намаҙлыҡтан	N;ABL;SG
бәрҙе	бәрҙеләрҙең	N;GEN;DEF;PL
аҡсарлаҡ	аҡсарлаҡ	N;NOM;SG
үҫемлек	үҫемлекте	N;ACC;DEF;SG
гөбөргәйел	гөбөргәйелдә	N;LOC;SG
ырғаҡ	ырғаҡтар	N;NOM;PL
төтөн	төтөнгә	N;DAT;SG
таҡырбаш	таҡырбаштарға	N;DAT;PL
таҡта	таҡта	N;NOM;SG
кисеү	кисеүҙәр	N;NOM;PL
яры	ярының	N;GEN;DEF;SG
болот	болоттар	N;NOM;PL
мәсет	мәсеттән	N;ABL;SG
шешә	шешәләргә	N;DAT;PL
елкән	елкәндәрҙең	N;GEN;DEF;PL
сыбыҡ	сыбыҡтарға	N;DAT;PL
йүгән	йүгән	N;NOM;SG
үҫенте	үҫентеләргә	N;DAT;PL
хәйер	хәйерҙән	N;ABL;SG
үҙәк	үҙәктәрҙең	ADJ;GEN;DEF;PL
фекер	фекерҙәргә	N;DAT;PL
Азия	Азияның	N;GEN;DEF;SG
зыярат	зыяраттарҙы	N;ACC;DEF;PL
тир	тир	N;NOM;SG
рәхмәт	рәхмәттәрҙә	N;LOC;PL
йомран	йомрандарға	N;DAT;PL
дәфтәр	дәфтәрҙәрҙә	N;LOC;PL
һөйәк	һөйәкте	N;ACC;DEF;SG
нәфрәт	нәфрәттән	N;ABL;SG
айҙар	айҙарға	N;DAT;SG
маңлай	маңлайҙың	N;GEN;DEF;SG
һемәк	һемәктәрҙе	N;ACC;DEF;PL
ҡорбан	ҡорбандарҙың	N;GEN;DEF;PL
дәүләт	дәүләтте	N;ACC;DEF;SG
бырау	бырау	N;NOM;SG
тимер	тимер	N;NOM;SG
йоҙроҡ	йоҙроҡтарҙы	N;ACC;DEF;PL
үҫенте	үҫентеләрҙә	N;LOC;PL
терһәк	терһәк	N;NOM;SG
бутҡа	бутҡаға	N;DAT;SG
кәмә	кәмәнең	N;GEN;DEF;SG
ҡарағай	ҡарағайҙа	N;LOC;SG
таныш	танышты	ADJ;ACC;DEF;SG
йыр	йырҙа	N;LOC;SG
ташлама	ташламанан	N;ABL;SG
эш	эш	N;NOM;SG
хыял	хыял	N;NOM;SG
йәшәйеш	йәшәйештә	N;LOC;SG
ҡауҙы	ҡауҙыларҙың	N;GEN;DEF;PL
тарма	тарма	N;DAT;SG
еҫ	еҫ	N;NOM;SG
рәссам	рәссамда	N;LOC;SG
тирмән	тирмәндең	N;GEN;DEF;SG
ысынбарлыҡ	ысынбарлыҡтарға	N;DAT;PL
болан	боландар	N;NOM;PL
тубыҡ	тубыҡтарҙың	N;GEN;DEF;PL
һырға	һырғаларҙа	N;LOC;PL
күгәүен	күгәүенде	N;ACC;DEF;SG
серәкәй	серәкәйҙәрҙә	N;LOC;PL
хужа	хужаларҙан	N;ABL;PL
миләш	миләште	N;ACC;DEF;SG
нисбәт	нисбәттә	N;LOC;SG
синыф	синыфтарҙан	N;ABL;PL
инәй	инәйгә	N;DAT;SG
һум	һум	N;ABL;PL
буҫтау	буҫтауға	N;DAT;SG
баш бармаҡ	баш бармаҡҡа	N;DAT;SG
таң	таңдарҙы	N;ACC;DEF;PL
саң	саңдың	N;GEN;DEF;SG
туҡыма	туҡымаларға	N;DAT;PL
тартма	тартмаларҙа	N;LOC;PL
төркөм	төркөмдәрҙән	N;ABL;PL
бала саҡ	бала саҡ	N;NOM;SG
орлоҡ	орлоҡтар	N;NOM;PL
ултырғыс	ултырғыстың	N;GEN;DEF;SG
йүгән	йүгәндә	N;LOC;SG
эйәк	эйәктең	N;GEN;DEF;SG
һаҡал	һаҡал	N;NOM;SG
гөл	гөлнө	N;ACC;DEF;SG
һөңгө	һөңгөгә	N;DAT;SG
ырғаҡ	ырғаҡтарҙан	N;ABL;PL
байрам	байрамдан	N;ABL;SG
һөргөн	һөргөндән	N;ABL;SG
дарыу	дарыуҙы	ADJ;ACC;DEF;SG
йәрәхәт	йәрәхәттәрҙең	N;GEN;DEF;PL
тиҙлек	тиҙлектән	N;ABL;SG
тәсбих	тәсбих	N;LOC;SG
дәфтәр	дәфтәрҙән	N;ABL;SG
сабата	сабата	N;DAT;SG
йөрәк	йөрәктә	N;LOC;SG
күпер	күперҙең	N;GEN;DEF;SG
таҫма	таҫма	N;GEN;DEF;PL
рәссам	рәссамдың	N;GEN;DEF;SG
ирен	ирен	N;NOM;SG
ниәт	ниәттәр	N;NOM;PL
ихтилал	ихтилал	N;NOM;SG
кәшәнә	кәшәнәнең	N;GEN;DEF;SG
үҙәк	үҙәктән	ADJ;ABL;SG
быҙау	быҙауҙарға	N;DAT;PL
еҫ	еҫтәрҙә	N;LOC;PL
дарыу	дарыуҙан	N;ABL;SG
итәк	итәкте	N;ACC;DEF;SG
яға	яғаға	N;DAT;SG
буҫтау	буҫтауҙар	N;NOM;PL
тәҡдим	тәҡдим	N;DAT;SG
редакция	редакцияларҙан	N;ABL;PL
ҡашығаяҡ	ҡашығаяҡ	N;NOM;SG
бурыс	бурыстарҙан	N;ABL;PL
китапхана	китапхананың	N;GEN;DEF;SG
ауырыу	ауырыу	ADJ;NOM;SG
редакция	редакцияла	N;LOC;SG
ашҡаҙан	ашҡаҙандың	N;GEN;DEF;SG
таж	тажда	N;LOC;SG
мырҙа	мырҙаларҙа	N;LOC;PL
һабаҡ	һабаҡтарҙың	N;GEN;DEF;PL
мәҡәлә	мәҡәлә	N;NOM;SG
фәлсәфә	фәлсәфә	N;NOM;SG
яға	яғала	N;LOC;SG
һуған	һуғандан	N;ABL;SG
диуар	диуарҙар	N;NOM;PL
сәс	сәстәрҙән	N;ABL;PL
тотҡа	тотҡа	N;ACC;DEF;PL
ғүмер	ғүмерҙәрҙе	N;ACC;DEF;PL
сыйырсыҡ	сыйырсыҡтарҙан	N;ABL;PL
салғы	салғынан	N;ABL;SG
даирә	даирәне	N;ACC;DEF;SG
ағыу	ағыуҙар	N;NOM;PL
бүләк	бүләктәрҙең	N;GEN;DEF;PL
кисә	кисә	N;NOM;SG
мендәр	мендәрҙәргә	N;DAT;PL
иғтибар	иғтибарҙарҙы	N;ACC;DEF;PL
фатиха	фатиха	N;NOM;SG
ҡалып	ҡалыптарҙың	N;GEN;DEF;PL
һаҡал	һаҡалдан	N;ABL;SG
ҡорт	ҡорттарға	N;DAT;PL
боҙлауыҡ	боҙлауыҡтың	N;GEN;DEF;SG
ҡаш	ҡаштар	N;NOM;PL
йәтим	йәтим	N;DAT;PL
терһәк	терһәктән	N;ABL;SG
ҡутаҡ	ҡутаҡтан	N;ABL;SG
салауат	салауаттарҙың	N;GEN;DEF;PL
аждаһа	аждаһаның	N;GEN;DEF;SG
мыйыҡ	мыйыҡты	N;ACC;DEF;SG
бур	бур	N;DAT;PL
ҡоҙоҡ	ҡоҙоҡтан	N;ABL;SG
үрҙәк	үрҙәктә	N;LOC;SG
риүәйәт	риүәйәттәрҙә	N;LOC;PL
ултырғыс	ултырғысҡа	N;DAT;SG
орсоҡ	орсоҡта	N;LOC;SG
һинд	һиндта	ADJ;LOC;SG
самауыр	самауырҙарға	N;DAT;PL
баҡа	баҡаларҙың	N;GEN;DEF;PL
ең	еңдәрҙең	N;GEN;DEF;PL
йыуаса	йыуасала	N;LOC;SG
мөрйә	мөрйәләрҙә	N;LOC;PL
һауыт-һаба	һауыт-һабалар	N;NOM;PL
ташлама	ташламаларҙа	N;LOC;PL
ғүмер	ғүмерҙәрҙән	N;ABL;PL
малай	малай	N;NOM;SG
балаҡ	балаҡта	N;LOC;SG
кәңәш	кәңәштәр	N;NOM;PL
тәбиғәт	тәбиғәттең	N;GEN;DEF;SG
һал	һал	N;NOM;SG
сәнәғәт	сәнәғәттәрҙең	N;GEN;DEF;PL
ҡанун	ҡанун	N;ACC;DEF;SG
бармаҡ	бармаҡта	N;LOC;SG
һөйкәлеш	һөйкәлештәрҙә	N;LOC;PL
татыулыҡ	татыулыҡтарҙың	N;GEN;DEF;PL
тин	тин	N;LOC;PL
ҡатырға	ҡатырғаның	N;GEN;DEF;SG
хаким	хакимдарҙан	N;ABL;PL
һауынсы	һауынсыла	N;LOC;SG
быуат	быуаттарҙан	N;ABL;PL
сәйнүк	сәйнүк	N;NOM;SG
алтын	алтынды	ADJ;ACC;DEF;SG
йомортҡа	йомортҡала	N;LOC;SG
тармаҡ	тармаҡтарҙың	N;GEN;DEF;PL
керпек	керпектең	N;GEN;DEF;SG
бесән	бесәндә	N;LOC;SG
бура	бураларҙа	N;LOC;PL
көнкүреш	көнкүреште	ADJ;ACC;DEF;SG
яҙма	яҙмаларҙың	N;GEN;DEF;PL
йыртҡыс	йыртҡысҡа	N;DAT;SG
кәбеҫтә	кәбеҫтәнән	N;ABL;SG
күл	күл	N;NOM;PL
өҫтәл	өҫтәлдәрҙең	N;GEN;DEF;PL
аҙан	аҙан	N;NOM;SG
гәүһәр	гәүһәрҙең	N;GEN;DEF;SG
шешә	шешәләрҙән	N;ABL;PL
тел	телдәрҙә	N;LOC;PL
таяҡ	таяҡҡа	N;DAT;SG
мәней	мәнейҙә	N;LOC;SG
яуап	яуаптарға	N;DAT;PL
ысынбарлыҡ	ысынбарлыҡтарҙан	N;ABL;PL
фән	фәнгә	N;DAT;SG
һандыҡ	һандыҡтың	N;GEN;DEF;SG
ҡая	ҡаяның	N;GEN;DEF;SG
офоҡ	офоҡҡа	N;DAT;SG
китап	китапты	N;ACC;DEF;SG
замана	замананан	N;ABL;SG
Уҡсы	Уҡсылар	N;NOM;PL
башҡорт	башҡортто	N;ACC;DEF;SG
һырға	һырғала	N;LOC;SG
ишек	ишекте	N;ACC;DEF;SG
буйҙаҡ	буйҙаҡта	ADJ;LOC;SG
һауыт	һауыттарҙан	N;ABL;PL
ғашиҡ	ғашиҡтарҙы	N;ACC;DEF;PL
һылыу	һылыуҙарҙың	N;GEN;DEF;PL
күләгә	күләгәнең	N;GEN;DEF;SG
бәрҙе	бәрҙене	N;ACC;DEF;SG
башаҡ	башаҡ	N;NOM;SG
намыҫ	намыҫта	N;LOC;SG
һупылдаҡ	һупылдаҡтан	N;ABL;SG
яға	яға	N;NOM;SG
һейҙек	һейҙектең	N;GEN;DEF;SG
ҡорбан	ҡорбанға	N;DAT;SG
ижек	ижектәр	N;NOM;PL
намыҫ	намыҫты	N;ACC;DEF;SG
самауыр	самауырҙарҙан	N;ABL;PL
ташҡын	ташҡында	N;LOC;SG
хәҡиҡәт	хәҡиҡәттә	N;LOC;SG
һуған	һуғанда	N;LOC;SG
тәнҡит	тәнҡит	N;LOC;SG
ҡоролтай	ҡоролтайға	N;DAT;SG
бейәләй	бейәләйҙе	N;ACC;DEF;SG
ҡомартҡы	ҡомартҡының	N;GEN;DEF;SG
күренеш	күренеш	N;NOM;SG
нур	нур	N;ACC;DEF;PL
арыш	арышҡа	N;DAT;SG
быуат	быуатта	N;LOC;SG
һауынсы	һауынсыларҙың	N;GEN;DEF;PL
шайыҡ	шайыҡта	N;LOC;SG
буҫтау	буҫтауҙа	N;LOC;SG
бәйләүес	бәйләүестәрҙе	N;ACC;DEF;PL
йәйғор	йәйғорға	N;DAT;SG
мырҙа	мырҙанан	N;ABL;SG
болан	боландарҙы	N;ACC;DEF;PL
аҡбур	аҡбур	N;GEN;DEF;SG
ғашиҡ	ғашиҡ	N;NOM;SG
яуап	яуапҡа	N;DAT;SG
тел	телдәргә	N;DAT;PL
тамға	тамғаларға	N;DAT;PL
ҡарғыш	ҡарғыштан	N;ABL;SG
уңыш	уңыштан	N;ABL;SG
сүмес	сүместән	N;ABL;SG
ғәйбәт	ғәйбәткә	N;DAT;SG
киле	килеләрҙән	N;ABL;PL
уңыш	уңыш	N;NOM;SG
тәржемә	тәржемәләр	N;NOM;PL
йыртҡыс	йыртҡыстарҙа	N;LOC;PL
самолёт	самолётта	N;LOC;SG
төп	төптәргә	ADJ;DAT;PL
тәртип	тәртип	N;NOM;PL
йәрәхәт	йәрәхәттәргә	N;DAT;PL
йылға	йылғаның	N;GEN;DEF;SG
үксә	үксәләрҙе	N;ACC;DEF;PL
дәүләт	дәүләт	ADJ;NOM;SG
һуҡыр сысҡан	һуҡыр сысҡандарҙың	N;GEN;DEF;PL
бейеүсе	бейеүселәрҙән	N;ABL;PL
итәк	итәк	N;NOM;SG
үрҙәк	үрҙәктәрҙә	N;LOC;PL
һеләгәй	һеләгәй	N;NOM;SG
ҡатнашыусы	ҡатнашыусыларҙан	N;ABL;PL
синыф	синыфтан	N;ABL;SG
тишек	тишектәрҙән	N;ABL;PL
игеҙәк	игеҙәктәрҙе	N;ACC;DEF;PL
иғтибар	иғтибарҙарҙан	N;ABL;PL
әкиәт	әкиәтте	N;ACC;DEF;SG
эремсек	эремсеккә	N;DAT;SG
намаҙлыҡ	намаҙлыҡтар	N;NOM;PL
үҙгәреш	үҙгәрештең	N;GEN;DEF;SG
мәжүсилек	мәжүсилекте	N;ACC;DEF;SG
ҡапҡас	ҡапҡаста	N;LOC;SG
ҡол	ҡолдарға	N;DAT;PL
ниәт	ниәттән	N;ABL;SG
тарих	тарихта	N;LOC;SG
тамуҡ	тамуҡ	N;NOM;SG
сәскә	сәскәлә	N;LOC;SG
таҫма	таҫма	N;ABL;PL
ҡапҡас	ҡапҡасҡа	N;DAT;SG
селлә	селләләр	N;NOM;PL
таш	таштарҙан	N;ABL;PL
ғасыр	ғасырҙарҙа	N;LOC;PL
ҡурсаҡ	ҡурсаҡты	N;ACC;DEF;SG
опто	оптоларҙы	N;ACC;DEF;PL
ботаҡ	ботаҡты	N;ACC;DEF;SG
салғы	салғы	N;NOM;SG
күркә	күркәнән	N;ABL;SG
ботаҡ	ботаҡтарҙан	N;ABL;PL
мәктәп	мәктәп	N;NOM;SG
дуңғыҙ	дуңғыҙҙар	N;NOM;PL
дәүер	дәүерҙәрҙән	N;ABL;PL
яҙма	яҙманан	ADJ;ABL;SG
бүрәнә	бүрәнәләр	N;NOM;PL
телмәр	телмәрҙе	N;ACC;DEF;SG
өйрәк	өйрәктәр	N;NOM;PL
көҙгө	көҙгөгә	N;DAT;SG
сауап	сауаптарҙың	N;GEN;DEF;PL
торна	торнанан	N;ABL;SG
ит	ит	N;ABL;SG
алма	алмалар	N;NOM;PL
кәшәнә	кәшәнәнән	N;ABL;SG
доға	доғаны	N;ACC;DEF;SG
абруй	абруй	N;NOM;SG
сусҡа	сусҡаларҙы	N;ACC;DEF;PL
тубыҡ	тубыҡтарҙы	N;ACC;DEF;PL
йәннәт	йәннәткә	N;DAT;SG
уҡытыусы	уҡытыусыға	N;DAT;SG
талап	талаптарға	N;DAT;PL
редакция	редакциянан	N;ABL;SG
ауырыу	ауырыуҙарҙа	ADJ;LOC;PL
ата-әсә	ата-әсәләргә	N;DAT;PL
сәнәғәт	сәнәғәт	N;NOM;SG
һал	һалдарҙың	N;GEN;DEF;PL
йәкшәмбе	йәкшәмбегә	N;DAT;SG
йоҙроҡ	йоҙроҡтарҙан	N;ABL;PL
уҡ	уҡ	N;ABL;PL
әүҙемлек	әүҙемлектәр	N;NOM;PL
шифа	шифаларға	N;DAT;PL
кейеҙ	кейеҙҙең	N;GEN;DEF;SG
һуған	һуған	N;NOM;SG
гөл	гөлләрҙең	N;GEN;DEF;PL
көрт	көрттәр	N;NOM;PL
дала	даланы	N;ACC;DEF;SG
ғаилә	ғаиләләрҙән	N;ABL;PL
турғай	турғайҙарҙың	N;GEN;DEF;PL
эскәмйә	эскәмйә	N;NOM;SG
таҡтаташ	таҡтаташта	N;LOC;SG
фәрештә	фәрештәгә	N;DAT;SG
мөгөҙ	мөгөҙгә	N;DAT;SG
ҡулаҡса	ҡулаҡсаны	N;ACC;DEF;SG
ең	еңдең	N;GEN;DEF;SG
ҡыш	ҡыштарға	N;DAT;PL
ярҙамсы	ярҙамсының	N;GEN;DEF;SG
хеҙмәт	хеҙмәттәргә	N;DAT;PL
тымау	тымау	N;NOM;SG
йән	йәндең	N;GEN;DEF;SG
милли көрәш	милли көрәштә	N;LOC;SG
хәйер	хәйерҙә	N;LOC;SG
буҫаға	буҫағалар	N;NOM;PL
башҡорт	башҡорттарға	ADJ;DAT;PL
терһәк	терһәктәрҙең	N;GEN;DEF;PL
тоҡ	тоҡтарҙы	N;ACC;DEF;PL
сиркәү	сиркәүҙәр	N;NOM;PL
туй	туй	N;ACC;DEF;SG
сүмес	сүместә	N;LOC;SG
ҡойо	ҡойола	N;LOC;SG
бәшмәк	бәшмәктәрҙә	N;LOC;PL
атай	атайға	N;DAT;SG
ҡармаҡ	ҡармаҡ	N;NOM;SG
туй	туй	N;DAT;SG
ғасыр	ғасырҙан	N;ABL;SG
һабаҡ	һабаҡтан	N;ABL;SG
ҡомартҡы	ҡомартҡы	N;NOM;SG
келәм	келәмдәр	N;NOM;PL
дарыухана	дарыуханаларҙан	N;ABL;PL
баҡсасы	баҡсасыны	N;ACC;DEF;SG
тау	тауҙың	N;GEN;DEF;SG
бүлмә	бүлмәнең	N;GEN;DEF;SG
йәшелсә	йәшелсәлә	N;LOC;SG
һағыҙ	һағыҙҙың	N;GEN;DEF;SG
үлән	үләндең	N;GEN;DEF;SG
замана	заманалар	N;NOM;PL
уйын	уйындарҙа	N;LOC;PL
ҡырмыҫҡа	ҡырмыҫҡаларҙың	N;GEN;DEF;PL
аш	ашҡа	N;DAT;SG
ваҡ-төйәк	ваҡ-төйәктән	ADJ;ABL;SG
күт	күт	N;ABL;SG
оро	ороноң	N;GEN;DEF;SG
малай	малайҙың	N;GEN;DEF;SG
баҡа	баҡаға	N;DAT;SG
бей	бейҙәрҙең	N;GEN;DEF;PL
тин	тин	N;LOC;SG
эҙ	эҙ	N;GEN;DEF;PL
киләсәк	киләсәкте	N;ACC;DEF;SG
дала	даланан	N;ABL;SG
тубыҡ	тубыҡты	N;ACC;DEF;SG
өҙәңге	өҙәңгеләрҙән	N;ABL;PL
замана	заманаларға	N;DAT;PL
иптәш	иптәштәрҙең	N;GEN;DEF;PL
сиркәү	сиркәүҙәргә	ADJ;DAT;PL
таҡмаҡ	таҡмаҡҡа	N;DAT;SG
күгәүен	күгәүендә	N;LOC;SG
мәжүси	мәжүсиҙәрҙең	N;GEN;DEF;PL
әлифба	әлифбанан	N;ABL;SG
ҡаҙ	ҡаҙҙар	N;NOM;PL
бейә	бейәләрҙән	N;ABL;PL
йыназа	йыназала	N;LOC;SG
үҙгәреш	үҙгәрештән	N;ABL;SG
урман	урмандарҙың	N;GEN;DEF;PL
юйғыс	юйғысҡа	N;DAT;SG
бәйләүес	бәйләүестәргә	N;DAT;PL
туп	туп	N;ACC;DEF;PL
риүәйәт	риүәйәттәр	N;NOM;PL
күт	күт	N;NOM;SG
баҙар	баҙар	N;NOM;SG
һыйыр	һыйырҙар	N;NOM;PL
бейә	бейәне	N;ACC;DEF;SG
ярҙамсы	ярҙамсынан	N;ABL;SG
сәбәп	сәбәптә	N;LOC;SG
инсан	инсандән	N;ABL;SG
хеҙмәт	хеҙмәттә	N;LOC;SG
йылъяҙма	йылъяҙманан	N;ABL;SG
гөл	гөлләрҙә	N;LOC;PL
хәйерсе	хәйерсенән	N;ABL;SG
аҡыл	аҡылдарҙа	N;LOC;PL
ҡабырға	ҡабырға	N;DAT;PL
төп	төптәрҙән	N;ABL;PL
дуҫлыҡ	дуҫлыҡтарға	N;DAT;PL
даирә	даирәләрҙе	N;ACC;DEF;PL
шәмбе	шәмбеләрҙән	N;ABL;PL
йәһәннәм	йәһәннәм	N;NOM;SG
тояҡ	тояҡтың	N;GEN;DEF;SG
бесәй	бесәйҙәргә	N;DAT;PL
тормош	тормоштоң	N;GEN;DEF;SG
Арыҫлан	Арыҫлан	N;NOM;SG
килмешәк	килмешәк	N;NOM;SG
дуҫ	дуҫ	N;NOM;PL
эшсе	эшселәрҙә	N;LOC;PL
яҙыусы	яҙыусыға	N;DAT;SG
ҡайыш	ҡайыштарҙа	N;LOC;PL
ҡағиҙә	ҡағиҙәнән	N;ABL;SG
ватан	ватанды	N;ACC;DEF;SG
сәғәт	сәғәткә	N;DAT;SG
нәшриәт	нәшриәттәрҙең	N;GEN;DEF;PL
Ылаҡ	Ылаҡтарҙа	N;LOC;PL
имән	имәндәрҙе	N;ACC;DEF;PL
ирлән	ирләндән	N;ABL;SG
ҡайыш	ҡайыштың	N;GEN;DEF;SG
ғибәҙәт	ғибәҙәттәр	N;NOM;PL
билдәләмә	билдәләмәлә	N;LOC;SG
егәр	егәрҙәрҙең	N;GEN;DEF;PL
ришүәтсе	ришүәтселәрҙән	N;ABL;PL
үҫмер	үҫмерҙең	N;GEN;DEF;SG
саҡрым	саҡрым	N;NOM;SG
бысҡы	бысҡы	N;ACC;DEF;PL
нәшриәт	нәшриәтте	N;ACC;DEF;SG
яуым-төшөм	яуым-төшөмдән	N;ABL;SG
саҡрым	саҡрымдар	N;NOM;PL
сәхнә	сәхнә	N;NOM;SG
ҡотоҡ	ҡотоҡтан	N;ABL;SG
мөьмин	мөьмин	N;LOC;PL
ҡоҙғон	ҡоҙғондарҙан	N;ABL;PL
Һыуғояр	Һыуғоярҙарҙың	N;GEN;DEF;PL
һыҙыҡ	һыҙыҡтарға	N;DAT;PL
йома	йоманың	N;GEN;DEF;SG
мосолман	мосолманда	N;LOC;SG
йома	йомаларҙа	N;LOC;PL
төшөнсә	төшөнсәләрҙе	N;ACC;DEF;PL
ҡайыш	ҡайышта	N;LOC;SG
мөьмин	мөьмин	N;ACC;DEF;SG
ел	елдең	N;GEN;DEF;SG
бөҙрә	бөҙрәлә	N;LOC;SG
бабай	бабайға	N;DAT;SG
мышы	мышыларҙың	N;GEN;DEF;PL
ваҡиға	ваҡиғанан	N;ABL;SG
ҡыҙыҡ	ҡыҙыҡта	ADJ;LOC;SG
кесаҙна	кесаҙналарҙан	N;ABL;PL
көндәлек	көндәлекте	N;ACC;DEF;SG
дауам	дауамдар	N;NOM;PL
ҡайын	ҡайындарҙа	N;LOC;PL
тәүтормош	тәүтормоштан	N;ABL;SG
көс	көстәрҙең	N;GEN;DEF;PL
гәзит	гәзит	N;ABL;SG
ҡыҙ	ҡыҙҙан	N;ABL;SG
енәйәт	енәйәттәрҙә	N;LOC;PL
өлгө	өлгөләрҙән	N;ABL;PL
тәмәке	тәмәкенән	N;ABL;SG
хаҡ	хаҡтарға	N;DAT;PL
үҫмер	үҫмер	N;NOM;SG
юлдаш	юлдаштар	N;NOM;PL
көндәлек	көндәлектәрҙән	N;ABL;PL
сифат	сифат	N;NOM;SG
батмус	батмус	N;ABL;PL
мөьмин	мөьмин	N;ABL;PL
ҡулъяулыҡ	ҡулъяулыҡтарҙы	N;ACC;DEF;PL
ҡараңғы	ҡараңғының	ADJ;GEN;DEF;SG
бөҙрә	бөҙрәләрҙә	N;LOC;PL
алмас	алмастың	N;GEN;DEF;SG
йүтәл	йүтәлдәр	N;NOM;PL
тамсы	тамсы	N;NOM;SG
һандуғас	һандуғасҡа	N;DAT;SG
ҡағиҙә	ҡағиҙәләр	N;NOM;PL
тыуған көн	тыуған көнгә	N;DAT;SG
батша	батшаларҙа	N;LOC;PL
ваҡиға	ваҡиғаның	N;GEN;DEF;SG
әҫәр	әҫәрҙәрҙә	N;LOC;PL
бүҙәнә	бүҙәнәләрҙән	N;ABL;PL
йәһүд	йәһүд	ADJ;ABL;PL
хәл	хәлдәрҙә	N;LOC;PL
йәрминкә	йәрминкә	N;DAT;PL
һуғыш	һуғыштарҙың	N;GEN;DEF;PL
нәшриәт	нәшриәттәрҙә	N;LOC;PL
тиҫтә	тиҫтә	N;NOM;SG
бысаҡ	бысаҡтарҙан	N;ABL;PL
ауһаҡ	ауһаҡ	N;NOM;SG
ҡарағат	ҡарағат	N;NOM;SG
үҫмер	үҫмерҙе	N;ACC;DEF;SG
йәрминкә	йәрминкә	N;ACC;DEF;SG
Ылаҡ	Ылаҡҡа	N;DAT;SG
дөйә	дөйәне	N;ACC;DEF;SG
килмешәк	килмешәктәрҙең	N;GEN;DEF;PL
бөрө	бөрөгә	N;DAT;SG
мөхәррир	мөхәррир	N;DAT;PL
рөхсәт	рөхсәттәрҙе	N;ACC;DEF;PL
алҡа	алҡаларҙан	N;ABL;PL
тимерсыбыҡ	тимерсыбыҡтарҙың	N;GEN;DEF;PL
үрнәк	үрнәктәр	N;NOM;PL
сәтләүек	сәтләүектәрҙе	N;ACC;DEF;PL
һорау	һорауҙы	N;ACC;DEF;SG
шыршы	шыршыны	N;ACC;DEF;SG
баҫҡыс	баҫҡыстарға	N;DAT;PL
тиҫбе	тиҫбелә	N;LOC;SG
ришүәт	ришүәттең	N;GEN;DEF;SG
ҡарама	ҡараманың	N;GEN;DEF;SG
ирлән	ирләндәр	N;NOM;PL
ҡасҡын	ҡасҡындарҙа	N;LOC;PL
үткән заман	үткән замандан	N;ABL;SG
хата	хата	N;LOC;SG
ялҡаулыҡ	ялҡаулыҡтан	N;ABL;SG
шәжәрә	шәжәрәләрҙе	N;ACC;DEF;PL
сәхнә	сәхнәләр	N;NOM;PL
килмешәк	килмешәккә	N;DAT;SG
мөхәббәт	мөхәббәт	N;NOM;SG
ымлыҡ	ымлыҡҡа	N;DAT;SG
тамсы	тамсыларҙың	N;GEN;DEF;PL
гәзит	гәзит	N;DAT;SG
үркәс	үркәсләргә	N;DAT;PL
бүре	бүре	N;NOM;SG
тамыр	тамырҙа	N;LOC;SG
әҫәр	әҫәрҙең	N;GEN;DEF;SG
ҡарама	ҡарамала	N;LOC;SG
сәхнә	сәхнәләргә	N;DAT;PL
ҡараңғы	ҡараңғы	N;NOM;SG
остаз	остаздан	N;ABL;SG
буранка	буранкаларҙан	N;ABL;PL
ишәк	ишәктә	N;LOC;SG
кәүҙә	кәүҙәнән	N;ABL;SG
яҙ	яҙҙарға	N;DAT;PL
ҡулъяҙма	ҡулъяҙмаға	N;DAT;SG
һыҙат	һыҙатты	N;ACC;DEF;SG
аҡса	аҡсаны	N;ACC;DEF;SG
шоңҡар	шоңҡарҙан	N;ABL;SG
егет	егетте	N;ACC;DEF;SG
тупраҡ	тупраҡтарҙа	N;LOC;PL
тире	тиренең	N;GEN;DEF;SG
түтәл	түтәлдәргә	N;DAT;PL
яҙыусы	яҙыусыларға	N;DAT;PL
балан	баланда	N;LOC;SG
сәтләүек	сәтләүектәр	N;NOM;PL
төшөнсә	төшөнсәнән	N;ABL;SG
хәбәр	хәбәрҙәрҙең	N;GEN;DEF;PL
баҫым	баҫым	N;NOM;SG
елем	елемдән	N;ABL;SG
ут	ут	N;LOC;SG
ялҡаулыҡ	ялҡаулыҡҡа	N;DAT;SG
исемлек	исемлеккә	N;DAT;SG
мосолман	мосолмандарҙың	ADJ;GEN;DEF;PL
саған	саған	N;NOM;SG
һыҙыҡ	һыҙыҡтарҙан	N;ABL;PL
Ылаҡ	Ылаҡтың	N;GEN;DEF;SG
ҡыҙыҡ	ҡыҙыҡ	ADJ;NOM;SG
мышы	мышыла	N;LOC;SG
мышар	мышарҙарҙан	N;ABL;PL
дөйә	дөйәгә	N;DAT;SG
көндәлек	көндәлектәрҙең	N;GEN;DEF;PL
ришүәтсе	ришүәтселәргә	N;DAT;PL
тиҫтә	тиҫтәгә	N;DAT;SG
тауис	тауистан	N;ABL;SG
төн	төндәргә	N;DAT;PL
тутыйғош	тутыйғошларҙың	N;GEN;DEF;PL
килмешәк	килмешәктәрҙә	N;LOC;PL
имән	имәндәр	N;NOM;PL
хөкүмәт	хөкүмәттәр	N;NOM;PL
торлаҡ	торлаҡты	N;ACC;DEF;SG
баҫҡыс	баҫҡыстан	N;ABL;SG
бөҙрә	бөҙрәләрҙе	ADJ;ACC;DEF;PL
тубырсыҡ	тубырсыҡтың	N;GEN;DEF;SG
көндәлек	көндәлектән	ADJ;ABL;SG
кесаҙна	кесаҙнанан	N;ABL;SG
көсөк	көсөктәрҙән	N;ABL;PL
Һыуғояр	Һыуғояр	N;NOM;SG
енәйәт	енәйәттәргә	N;DAT;PL
япраҡ	япраҡта	N;LOC;SG
ғәҙәт	ғәҙәттәрҙән	N;ABL;PL
ауһаҡ	ауһаҡты	N;ACC;DEF;SG
тәғлимәт	тәғлимәттәрҙең	N;GEN;DEF;PL
утҡойроҡ	утҡойроҡтарҙа	N;LOC;PL
егет	егеттәрҙең	N;GEN;DEF;PL
яҙыусы	яҙыусыларҙан	N;ABL;PL
үткән заман	үткән заманда	N;LOC;SG
толом	толомдарҙы	N;ACC;DEF;PL
мышар	мышарҙы	N;ACC;DEF;SG
йәһүд	йәһүд	N;DAT;SG
бәхет	бәхет	N;NOM;SG
асҡыс	асҡыстан	N;ABL;SG
мосолман	мосолман	N;NOM;SG
йәшен	йәшендәрҙе	N;ACC;DEF;PL
бойҙай	бойҙайға	N;DAT;SG
ғибәҙәт	ғибәҙәттәрҙә	N;LOC;PL
батша	батшаларҙан	N;ABL;PL
үт	үт	N;DAT;SG
донъя	донъя	N;NOM;SG
фил	фил	N;LOC;SG
билдәләмә	билдәләмәләргә	N;DAT;PL
гәзит	гәзит	N;ABL;PL
мосолман	мосолман	ADJ;NOM;SG
милләтсе	милләтсегә	N;DAT;SG
тал	талдарҙа	N;LOC;PL
тауис	тауиста	N;LOC;SG
һунарсы	һунарсыларҙы	N;ACC;DEF;PL
мосолман	мосолманда	ADJ;LOC;SG
сумаҙан	сумаҙандың	N;GEN;DEF;SG
урам	урамдың	N;GEN;DEF;SG
тиҫтә	тиҫтәне	N;ACC;DEF;SG
эшсе	эшсенән	N;ABL;SG
емеш	емеште	N;ACC;DEF;SG
ҡулъяҙма	ҡулъяҙмаларға	ADJ;DAT;PL
тал	тал	N;NOM;SG
тутыйғош	тутыйғошларҙа	N;LOC;PL
яуаплылыҡ	яуаплылыҡтарҙың	N;GEN;DEF;PL
кимереүсе	кимереүселәрҙең	N;GEN;DEF;PL
йәшен	йәшендән	N;ABL;SG
урын	урындарҙа	N;LOC;PL
хоҙай	хоҙайҙан	N;ABL;SG
һорау	һорауҙарҙа	ADJ;LOC;PL
фил	фил	N;ACC;DEF;PL
тирмәнсе	тирмәнселәрҙән	N;ABL;PL
алҡа	алҡаларҙы	N;ACC;DEF;PL
таҫтамал	таҫтамалдан	N;ABL;SG
алҡа	алҡанан	N;ABL;SG
мосолман	мосолмандың	N;GEN;DEF;SG
ватан	ватандың	N;GEN;DEF;SG
тут	тут	N;NOM;SG
помидор	помидорға	N;DAT;SG
төрткө	төрткөләргә	N;DAT;PL
көрсөк	көрсөктөң	N;GEN;DEF;SG
ауһаҡ	ауһаҡтарҙа	N;LOC;PL
диңгеҙ	диңгеҙ	N;NOM;SG
һунарсы	һунарсы	N;NOM;SG
фил	фил	N;NOM;SG
бабай	бабайҙа	N;LOC;SG
ир	ир	N;GEN;DEF;PL
машина	машиналарҙың	N;GEN;DEF;PL
әфәнде	әфәнде	N;NOM;SG
күгәрсен	күгәрсендәрҙән	N;ABL;PL
ураҡ һәм сүкеш	ураҡ һәм сүкештең	N;GEN;DEF;SG
баҫма	баҫманың	ADJ;GEN;DEF;SG
Науруз	Науруз	N;ACC;DEF;SG
һыҙат	һыҙаттарҙан	N;ABL;PL
сәйхана	сәйхананан	N;ABL;SG
көсөк	көсөктәр	N;NOM;PL
һалдат	һалдатты	N;ACC;DEF;SG
ауыҙ	ауыҙҙар	N;NOM;PL
бүҙәнә	бүҙәнәнең	N;GEN;DEF;SG
ҡала	ҡалаларҙың	N;GEN;DEF;PL
һөлөк	һөлөктәргә	N;DAT;PL
иблис	иблис	N;ACC;DEF;SG
йылан	йыланға	N;DAT;SG
атама	атамаларҙан	N;ABL;PL
сәтләүек	сәтләүектең	N;GEN;DEF;SG
утҡойроҡ	утҡойроҡтарҙың	N;GEN;DEF;PL
толом	толомдан	N;ABL;SG
етем	етемде	N;ACC;DEF;SG
һарай	һарайла	N;LOC;SG
утҡойроҡ	утҡойроҡтарҙан	N;ABL;PL
алҡа	алҡаларға	N;DAT;PL
ришүәтсе	ришүәтсенән	N;ABL;SG
өлгө	өлгө	N;NOM;SG
хужалыҡ	хужалыҡтарға	N;DAT;PL
тәңре	тәңре	N;NOM;SG
Һыуғояр	Һыуғоярҙан	N;ABL;SG
пәрҙә	пәрҙәләр	N;NOM;PL
мәрйен	мәрйендәр	N;NOM;PL
ғәмәл	ғәмәлдән	N;ABL;SG
халыҡ	халыҡты	N;ACC;DEF;SG
Үлсәү	Үлсәүгә	N;DAT;SG
ҡунаҡ	ҡунаҡ	N;NOM;SG
юлдаш	юлдаш	N;NOM;SG
тимерсыбыҡ	тимерсыбыҡтарҙан	N;ABL;PL
бабай	бабайҙарҙан	N;ABL;PL
беләҙек	беләҙек	N;NOM;SG
мөхәррир	мөхәррир	N;GEN;DEF;PL
емеш	емештәрҙең	N;GEN;DEF;PL
әтәс	әтәстең	N;GEN;DEF;SG
Һыуғояр	Һыуғоярҙарҙан	N;ABL;PL
мөхәррир	мөхәррир	N;NOM;SG
эшсе	эшселәр	N;NOM;PL
барабан	барабандың	N;GEN;DEF;SG
кимереүсе	кимереүсе	N;NOM;SG
һарай	һарайнан	N;ABL;SG
бәпембә	бәпембәнең	N;GEN;DEF;SG
Ылаҡ	Ылаҡтарға	N;DAT;PL
тупраҡ	тупраҡтың	N;GEN;DEF;SG
томан	томанда	N;LOC;SG
тиҫбе	тиҫбене	N;ACC;DEF;SG
киләсәк заман	киләсәк заманға	N;DAT;SG
ҡоҙғон	ҡоҙғондар	N;NOM;PL
ир	ир	N;DAT;PL
үт	үт	N;NOM;SG
баҫҡыс	баҫҡысҡа	N;DAT;SG
алмас	алмастарға	N;DAT;PL
мосолман	мосолмандарҙан	N;ABL;PL
рөхсәт	рөхсәттән	N;ABL;SG
тейен	тейен	N;NOM;SG
мышы	мышының	N;GEN;DEF;SG
алҡа	алҡаға	N;DAT;SG
бөйөр	бөйөрҙөң	N;GEN;DEF;SG
ҡалай	ҡалайҙың	N;GEN;DEF;SG
ҡайын	ҡайындан	N;ABL;SG
исемлек	исемлектәрҙән	N;ABL;PL
сәхнә	сәхнәләрҙә	N;LOC;PL
тыуған көн	тыуған көндән	N;ABL;SG
ҡағиҙә	ҡағиҙәнең	N;GEN;DEF;SG
хоҙай	хоҙайҙың	N;GEN;DEF;SG
ялҡаулыҡ	ялҡаулыҡтың	N;GEN;DEF;SG
мосолман	мосолмандан	ADJ;ABL;SG
арыҫлан	арыҫланды	N;ACC;DEF;SG
асҡыс	асҡыс	N;NOM;SG
хаҡ	хаҡта	N;LOC;SG
борғаҡ	борғаҡты	N;ACC;DEF;SG
ҡыҙыҡ	ҡыҙыҡтан	N;ABL;SG
егәр	егәрҙән	N;ABL;SG
тал	талдан	N;ABL;SG
арыҫлан	арыҫландан	N;ABL;SG
олон	олонға	N;DAT;SG
миҫал	миҫал	N;NOM;SG
һандуғас	һандуғастарҙа	N;LOC;PL
ғалим	ғалимдар	N;NOM;PL
даға	дағаларға	N;DAT;PL
йылан	йыландан	N;ABL;SG
йәштәр	йәштәрҙә	N;LOC;SG
ҡулъяҙма	ҡулъяҙмаларҙа	ADJ;LOC;PL
кимәл	кимәлгә	N;DAT;SG
бәхет	бәхеттәрҙе	N;ACC;DEF;PL
шоңҡар	шоңҡарҙарҙан	N;ABL;PL
беләҙек	беләҙектән	N;ABL;SG
милләтсе	милләтсенән	N;ABL;SG
шаршау	шаршауҙарҙа	N;LOC;PL
тәғлимәт	тәғлимәттәрҙе	N;ACC;DEF;PL
киндер	киндерҙе	N;ACC;DEF;SG
шишмә	шишмәне	N;ACC;DEF;SG
көнбағыш	көнбағышҡа	N;DAT;SG
тәүтормош	тәүтормоштар	N;NOM;PL
мосолман	мосолмандарға	N;DAT;PL
белешмә	белешмә	N;NOM;SG
кесаҙна	кесаҙналарҙы	N;ACC;DEF;PL
саған	сағандарға	N;DAT;PL
хужабикә	хужабикәләрҙән	N;ABL;PL
төрткө	төрткөләрҙе	N;ACC;DEF;PL
һайыҫҡан	һайыҫҡандар	N;NOM;PL
дөйә	дөйәләрҙә	N;LOC;PL
хата	хата	N;DAT;SG
суйын	суйындың	N;GEN;DEF;SG
барабан	барабандарға	N;DAT;PL
асҡыс	асҡысты	N;ACC;DEF;SG
һалдат	һалдаттан	N;ABL;SG
бишек	бишектең	N;GEN;DEF;SG
ришүәтсе	ришүәтселәрҙә	N;LOC;PL
ишәк	ишәк	N;NOM;SG
урам	урамдарҙа	N;LOC;PL
ҡояш	ҡояшта	N;LOC;SG
тәүтормош	тәүтормоштарҙың	ADJ;GEN;DEF;PL
яҙмыш	яҙмышты	N;ACC;DEF;SG
ҡарама	ҡарамаларҙан	N;ABL;PL
тол	тол	N;NOM;SG
сәхнә	сәхнәгә	N;DAT;SG
аяҡ	аяҡҡа	N;DAT;SG
мышы	мышынан	N;ABL;SG
урам	урамды	N;ACC;DEF;SG
күңел	күңелдең	N;GEN;DEF;SG
шыршы	шыршының	N;GEN;DEF;SG
барабан	барабандар	N;NOM;PL
милләтсе	милләтселәрҙә	N;LOC;PL
батша	батшаның	N;GEN;DEF;SG
шоңҡар	шоңҡарға	N;DAT;SG
ғәмәл	ғәмәлдең	N;GEN;DEF;SG
тирмәнсе	тирмәнсенән	N;ABL;SG
ҡарабойҙай	ҡарабойҙайҙа	N;LOC;SG
тире	тире	N;NOM;SG
буран	бурандарҙан	N;ABL;PL
тиҫтә	тиҫтәләргә	N;DAT;PL
дуҫ	дуҫ	N;NOM;SG
көндәлек	көндәлектәргә	N;DAT;PL
атама	атамаларға	N;DAT;PL
егәр	егәрҙәр	N;NOM;PL
саған	сағандарҙың	N;GEN;DEF;PL
бәпембә	бәпембәләрҙән	N;ABL;PL
нәркәс	нәркәстәрҙе	N;ACC;DEF;PL
матбуғат	матбуғатҡа	N;DAT;SG
баҫма	баҫмаға	N;DAT;SG
Һыуғояр	Һыуғоярҙарҙа	N;LOC;PL
ирлән	ирләнде	N;ACC;DEF;SG
һайыҫҡан	һайыҫҡандарға	N;DAT;PL
ҡанат	ҡанаттар	N;NOM;PL
милләтсе	милләтсенең	N;GEN;DEF;SG
тәүтормош	тәүтормоштар	ADJ;NOM;PL
йәрминкә	йәрминкә	N;ABL;SG
арыҫлан	арыҫландарға	N;DAT;PL
хужалыҡ	хужалыҡ	N;NOM;SG
һөлөк	һөлөктәрҙән	N;ABL;PL
ҡыуаҡ	ҡыуаҡтар	N;NOM;PL
емеш	емештәргә	N;DAT;PL
сәйхана	сәйхананы	N;ACC;DEF;SG
хөкүмәт	хөкүмәттәрҙә	N;LOC;PL
әңгәмә	әңгәмә	N;DAT;SG
тәңре	тәңрегә	N;DAT;SG
әтәс	әтәскә	N;DAT;SG
машина	машиналар	N;NOM;PL
шаршамбы	шаршамбыға	N;DAT;SG
ымлыҡ	ымлыҡтарға	N;DAT;PL
ирлән	ирләндә	N;LOC;SG
ел	елдәрҙә	N;LOC;PL
нәшриәт	нәшриәттә	N;LOC;SG
ришүәт	ришүәттәрҙән	N;ABL;PL
хужалыҡ	хужалыҡтар	N;NOM;PL
иҫ	иҫ	N;LOC;PL
баҫҡыс	баҫҡыстарҙа	N;LOC;PL
тыуған көн	тыуған көндәр	N;NOM;PL
бүре	бүреләрҙе	N;ACC;DEF;PL
Һыуғояр	Һыуғоярҙарға	N;DAT;PL
буранка	буранкаларға	N;DAT;PL
борғаҡ	борғаҡ	N;NOM;SG
өсмөйөш	өсмөйөштө	N;ACC;DEF;SG
шама	шама	N;ABL;SG
баҫма	баҫма	ADJ;NOM;SG
муйын	муйындарҙы	N;ACC;DEF;PL
яҙмыш	яҙмыштың	N;GEN;DEF;SG
ҡараңғы	ҡараңғының	N;GEN;DEF;SG
бысаҡ	бысаҡтарҙың	N;GEN;DEF;PL
ғәмәл	ғәмәлдәрҙән	N;ABL;PL
шоңҡар	шоңҡарҙарҙың	N;GEN;DEF;PL
борғаҡ	борғаҡтан	N;ABL;SG
теләк	теләктең	N;GEN;DEF;SG
матбуғат	матбуғатты	N;ACC;DEF;SG
аяҡ	аяҡ	N;NOM;SG
йоҙаҡ	йоҙаҡтан	N;ABL;SG
мосолман	мосолмандар	ADJ;NOM;PL
журнал	журналдар	N;NOM;PL
тиҫтә	тиҫтәләрҙән	N;ABL;PL
сәхнә	сәхнәнең	N;GEN;DEF;SG
ҡотоҡ	ҡотоҡта	N;LOC;SG
һөйләм	һөйләмдәрҙә	N;LOC;PL
эстәлек	эстәлекте	N;ACC;DEF;SG
ҡыуаҡ	ҡыуаҡта	N;LOC;SG
күңел	күңел	N;NOM;SG
бысҡы	бысҡы	N;GEN;DEF;SG
ҡунаҡ	ҡунаҡтарҙан	N;ABL;PL
эшсе	эшсе	N;NOM;SG
матбуғат	матбуғатта	N;LOC;SG
машина	машинаны	N;ACC;DEF;SG
тәүтормош	тәүтормоштоң	N;GEN;DEF;SG
ғибәҙәт	ғибәҙәт	N;NOM;SG
ҡумта	ҡумтаны	N;ACC;DEF;SG
хужалыҡ	хужалыҡтарҙан	N;ABL;PL
ҡоҙғон	ҡоҙғондарҙы	N;ACC;DEF;PL
үткән заман	үткән заманға	N;DAT;SG
ҡунаҡ	ҡунаҡта	N;LOC;SG
толом	толомға	N;DAT;SG
араҡы	араҡыла	N;LOC;SG
буран	бурандарҙың	N;GEN;DEF;PL
ҡулъяҙма	ҡулъяҙманың	N;GEN;DEF;SG
имән	имәндән	N;ABL;SG
адрес	адрестан	N;ABL;SG
юлдаш	юлдашҡа	N;DAT;SG
журнал	журналдан	N;ABL;SG
ус	ус	N;NOM;SG
көс	көстәрҙән	N;ABL;PL
килмешәк	килмешәкте	N;ACC;DEF;SG
йылан	йыландар	N;NOM;PL
йоҙаҡ	йоҙаҡтың	N;GEN;DEF;SG
көндәлек	көндәлек	ADJ;NOM;SG
тауис	тауистарҙы	N;ACC;DEF;PL
йәшен	йәшен	N;NOM;SG
күгәрсен	күгәрсендәргә	N;DAT;PL
арыҫлан	арыҫландар	N;NOM;PL
суйын	суйын	N;NOM;SG
бысаҡ	бысаҡта	N;LOC;SG
түтәл	түтәлдәрҙе	N;ACC;DEF;PL
емеш	емештәрҙән	N;ABL;PL
уҡыусы	уҡыусыны	N;ACC;DEF;SG
рәт	рәттәрҙең	N;GEN;DEF;PL
алмас	алмасты	N;ACC;DEF;SG
хәл	хәл	N;NOM;SG
танау	танаутар	N;NOM;PL
ҡағиҙә	ҡағиҙә	N;NOM;SG
үҫмер	үҫмерҙәр	N;NOM;PL
ҡайын	ҡайындарҙы	N;ACC;DEF;PL
аҙым	аҙымды	N;ACC;DEF;SG
имән	имән	N;NOM;SG
батыр	батырға	N;DAT;SG
ваҡыт	ваҡыттарҙан	N;ABL;PL
яҙмыш	яҙмыш	N;NOM;SG
бәпембә	бәпембәләр	N;NOM;PL
хөкүмәт	хөкүмәттәрҙең	N;GEN;DEF;PL
шоңҡар	шоңҡарҙарға	N;DAT;PL
белешмә	белешмәләрҙе	N;ACC;DEF;PL
шайтан	шайтанда	N;LOC;SG
шәрәлек	шәрәлекте	N;ACC;DEF;SG
гонаһ	гонаһтан	N;ABL;SG
емеш	емеш	N;NOM;SG
ҡырау	ҡырауҙарҙан	N;ABL;PL
үҫмер	үҫмерҙәрҙән	N;ABL;PL
үркәс	үркәсләрҙән	N;ABL;PL
төн	төндө	N;ACC;DEF;SG
тәмәке	тәмәке	N;DAT;SG
ҡараңғы	ҡараңғынан	N;ABL;SG
егәр	егәрҙең	N;GEN;DEF;SG
олон	олондарҙа	N;LOC;PL
һыҙыҡ	һыҙыҡ	N;NOM;SG
бөрө	бөрөнөң	N;GEN;DEF;SG
ришүәт	ришүәттә	N;LOC;SG
үркәс	үркәсгә	N;DAT;SG
терпе	терпеләрҙән	N;ABL;PL
эстәлек	эстәлектән	N;ABL;SG
ҡулъяҙма	ҡулъяҙма	ADJ;NOM;SG
мышы	мышы	N;NOM;SG
ирлән	ирләндең	N;GEN;DEF;SG
тут	тут	N;DAT;SG
толом	толомда	N;LOC;SG
килмешәк	килмешәктән	N;ABL;SG
танау	танаутарға	N;DAT;PL
егет	егеткә	N;DAT;SG
теш	тешкә	N;DAT;SG
батмус	батмус	N;NOM;PL
мөхәррир	мөхәррир	N;ACC;DEF;PL
ҡалай	ҡалай	N;NOM;SG
эшсе	эшсегә	N;DAT;SG
батыр	батырҙы	N;ACC;DEF;SG
тейен	тейендәрҙең	N;GEN;DEF;PL
мышар	мышарҙарҙы	N;ACC;DEF;PL
ваҡиға	ваҡиға	N;NOM;SG
даға	дағаларҙы	N;ACC;DEF;PL
яуаплылыҡ	яуаплылыҡтарҙа	N;LOC;PL
тирмәнсе	тирмәнсене	N;ACC;DEF;SG
тиҫтә	тиҫтәләрҙең	N;GEN;DEF;PL
ишәк	ишәктәрҙән	N;ABL;PL
үткән заман	үткән заманды	N;ACC;DEF;SG
ҡасҡын	ҡасҡындарҙы	N;ACC;DEF;PL
төн	төндәрҙең	N;GEN;DEF;PL
һунарсы	һунарсының	N;GEN;DEF;SG
төшөнсә	төшөнсәләрҙә	N;LOC;PL
томан	томандар	N;NOM;PL
йүтәл	йүтәлдәргә	N;DAT;PL
мышар	мышарҙарға	N;DAT;PL
ҡотоҡ	ҡотоҡтарҙың	N;GEN;DEF;PL
өлгө	өлгөнө	N;ACC;DEF;SG
тол	толдар	N;NOM;PL
бәхет	бәхеттә	N;LOC;SG
шаршамбы	шаршамбыларҙан	N;ABL;PL
баҫма	баҫмалар	ADJ;NOM;PL
балан	баландың	N;GEN;DEF;SG
сәхнә	сәхнәләрҙең	N;GEN;DEF;PL
ир	ир	N;LOC;PL
бөрө	бөрөләрҙә	N;LOC;PL
енәйәт	енәйәттәрҙән	N;ABL;PL
ҡала	ҡалаларҙы	N;ACC;DEF;PL
баҫма	баҫмаларҙың	ADJ;GEN;DEF;PL
мөхәррир	мөхәррир	N;ABL;PL
ғалим	ғалимға	N;DAT;SG
хөкүмәт	хөкүмәткә	N;DAT;SG
етем	етемдә	N;LOC;SG
ваҡыт	ваҡыт	N;NOM;SG
майҙансыҡ	майҙансыҡтың	N;GEN;DEF;SG
томан	томанға	N;DAT;SG
һандуғас	һандуғастан	N;ABL;SG
кәүҙә	кәүҙәләр	N;NOM;PL
исемлек	исемлектәргә	N;DAT;PL
тал	талдарҙы	N;ACC;DEF;PL
Үлсәү	Үлсәүҙең	N;GEN;DEF;SG
баҫма	баҫма	N;NOM;SG
майҙансыҡ	майҙансыҡтарҙың	N;GEN;DEF;PL
милләтсе	милләтсе	N;NOM;SG
тейен	тейенде	N;ACC;DEF;SG
ҡунаҡ	ҡунаҡты	N;ACC;DEF;SG
йүтәл	йүтәлгә	N;DAT;SG
батмус	батмус	N;GEN;DEF;SG
муйын	муйында	N;LOC;SG
яуаплылыҡ	яуаплылыҡтың	N;GEN;DEF;SG
шайтан	шайтандан	N;ABL;SG
енәйәт	енәйәтте	N;ACC;DEF;SG
ҡанат	ҡанаттан	N;ABL;SG
һайыҫҡан	һайыҫҡан	N;NOM;SG
эшсе	эшсенең	N;GEN;DEF;SG
торлаҡ	торлаҡтарҙан	N;ABL;PL
ус	ус	N;ACC;DEF;PL
таҫтамал	таҫтамалдың	N;GEN;DEF;SG
күмер	күмерҙә	N;LOC;SG
атама	атаманан	N;ABL;SG
тубырсыҡ	тубырсыҡтарҙан	N;ABL;PL
бойҙай	бойҙайҙан	N;ABL;SG
шоңҡар	шоңҡарҙы	N;ACC;DEF;SG
ир	ир	N;NOM;PL
дуҫ	дуҫ	N;ABL;SG
саған	сағанды	N;ACC;DEF;SG
атама	атаманы	N;ACC;DEF;SG
көрсөк	көрсөктәрҙән	N;ABL;PL
ҡайын	ҡайынды	N;ACC;DEF;SG
ымлыҡ	ымлыҡтың	N;GEN;DEF;SG
тимерсыбыҡ	тимерсыбыҡтарҙы	N;ACC;DEF;PL
ҡулъяулыҡ	ҡулъяулыҡҡа	N;DAT;SG
ҡолон	ҡолондарҙа	N;LOC;PL
урам	урамдарҙан	N;ABL;PL
гәзит	гәзит	N;GEN;DEF;SG
тәғлимәт	тәғлимәттәр	N;NOM;PL
йома	йома	N;NOM;SG
ауһаҡ	ауһаҡҡа	N;DAT;SG
рәт	рәттән	N;ABL;SG
маңдай	маңдайҙарҙан	N;ABL;PL
аҡса	аҡсаларҙан	N;ABL;PL
пәрҙә	пәрҙә	N;NOM;SG
тауис	тауистар	N;NOM;PL
ғәҙәт	ғәҙәттә	N;LOC;SG
буран	бурандарға	N;DAT;PL
эстәлек	эстәлектә	N;LOC;SG
гонаһ	гонаһтарҙа	N;LOC;PL
шаршамбы	шаршамбыларҙа	N;LOC;PL
арыҫлан	арыҫландарҙың	N;GEN;DEF;PL
хөкүмәт	хөкүмәттәрҙән	N;ABL;PL
яҙ	яҙҙа	N;LOC;SG
яҙ	яҙҙан	N;ABL;SG
енәйәт	енәйәттән	N;ABL;SG
көндәлек	көндәлек	N;NOM;SG
ҡамыш	ҡамыштың	N;GEN;DEF;SG
сәғәт	сәғәттең	N;GEN;DEF;SG
әтәс	әтәстәрҙең	N;GEN;DEF;PL
батмус	батмус	N;NOM;SG
уҫаҡ	уҫаҡтарҙың	N;GEN;DEF;PL
тәүтормош	тәүтормошто	ADJ;ACC;DEF;SG
әтәс	әтәсте	N;ACC;DEF;SG
хөкүмәт	хөкүмәттәрҙе	N;ACC;DEF;PL
саңғы	саңғының	N;GEN;DEF;SG
түтәл	түтәлдә	N;LOC;SG
һыҙыҡ	һыҙыҡта	N;LOC;SG
ус	ус	N;GEN;DEF;SG
алҡа	алҡаларҙа	N;LOC;PL
бөҙрә	бөҙрәләрҙә	ADJ;LOC;PL
үпкә	үпкә	N;LOC;SG
уҫаҡ	уҫаҡтар	N;NOM;PL
эстәлек	эстәлектәргә	N;DAT;PL
әңгәмә	әңгәмә	N;ABL;PL
Үлсәү	Үлсәүҙә	N;LOC;SG
ҡала	ҡалалар	N;NOM;PL
күбәләк	күбәләктәр	N;NOM;PL
хаҡ	хаҡтан	ADJ;ABL;SG
ирлән	ирлән	N;NOM;SG
енәйәт	енәйәттең	N;GEN;DEF;SG
ҡыуаҡ	ҡыуаҡтарҙы	N;ACC;DEF;PL
мөьмин	мөьмин	N;ABL;SG
мышар	мышарҙар	N;NOM;PL
ҡырау	ҡырауҙың	N;GEN;DEF;SG
ришүәт	ришүәттәрҙе	N;ACC;DEF;PL
емтек	емтектең	N;GEN;DEF;SG
алҡа	алҡаларҙың	N;GEN;DEF;PL
арыҫлан	арыҫландарҙа	N;LOC;PL
ислам	исламда	N;LOC;SG
яҙмыш	яҙмышҡа	N;DAT;SG
сумаҙан	сумаҙандарҙа	N;LOC;PL
баҫма	баҫмалар	N;NOM;PL
төн	төндә	N;LOC;SG
ҡумта	ҡумталарҙың	N;GEN;DEF;PL
донъя	донъяға	N;DAT;SG
хөкүмәт	хөкүмәт	N;NOM;SG
яҙ	яҙҙар	N;NOM;PL
олон	олондо	N;ACC;DEF;SG
әхирәт	әхирәттәрҙән	N;ABL;PL
тараф	тарафтың	N;GEN;DEF;SG
ир	ир	N;ABL;SG
упҡын	упҡындарҙың	N;GEN;DEF;PL
батмус	батмус	N;DAT;SG
ваҡыт	ваҡыттарға	N;DAT;PL
үрнәк	үрнәктәрҙе	N;ACC;DEF;PL
ҡыҙ	ҡыҙҙың	N;GEN;DEF;SG
бойондороҡһоҙлоҡ	бойондороҡһоҙлоҡта	N;LOC;SG
тырнаҡ	тырнаҡтарҙан	N;ABL;PL
һуғыш	һуғышта	N;LOC;SG
хәбәр	хәбәргә	N;DAT;SG
тал	талдарҙан	N;ABL;PL
ҡыҙыҡ	ҡыҙыҡтан	ADJ;ABL;SG
батша	батшанан	N;ABL;SG
тамсы	тамсыларҙан	N;ABL;PL
бөҙрә	бөҙрә	ADJ;NOM;SG
хаҡ	хаҡ	ADJ;NOM;SG
утҡойроҡ	утҡойроҡҡа	N;DAT;SG
бүҙәнә	бүҙәнә	N;NOM;SG
бысҡы	бысҡы	N;ABL;PL
ҡулъяулыҡ	ҡулъяулыҡтарҙа	N;LOC;PL
көҙ	көҙ	N;NOM;SG
теләк	теләк	N;NOM;SG
тиҫтә	тиҫтәлә	N;LOC;SG
шәреҡ	шәреҡте	N;ACC;DEF;SG
иҫ	иҫ	N;NOM;SG
үркәс	үркәс	N;NOM;SG
милләтсе	милләтселәрҙән	N;ABL;PL
буранка	буранканан	N;ABL;SG
тубырсыҡ	тубырсыҡтарҙың	N;GEN;DEF;PL
тауис	тауистарҙан	N;ABL;PL
урынбаҫар	урынбаҫарҙан	N;ABL;SG
ҡолон	ҡолондарға	N;DAT;PL
нәркәс	нәркәстәр	N;NOM;PL
ғәҙәт	ғәҙәттәргә	N;DAT;PL
әтәс	әтәс	N;NOM;SG
йәшен	йәшендә	N;LOC;SG
бөрө	бөрө	N;NOM;SG
хоҙай	хоҙайҙарҙы	N;ACC;DEF;PL
етем	етем	N;NOM;SG
белешмә	белешмәләрҙән	N;ABL;PL
көрсөк	көрсөктәр	N;NOM;PL
белешмә	белешмәнең	N;GEN;DEF;SG
бөрө	бөрөлә	N;LOC;SG
осҡон	осҡондоң	N;GEN;DEF;SG
шишмә	шишмәнең	N;GEN;DEF;SG
көрсөк	көрсөктәргә	N;DAT;PL
тирмәнсе	тирмәнсегә	N;DAT;SG
алҡа	алҡа	N;NOM;SG
йәштәр	йәштәрҙең	N;GEN;DEF;SG
ҡанат	ҡанат	N;NOM;SG
ҡоҙғон	ҡоҙғондо	N;ACC;DEF;SG
килмешәк	килмешәктәрҙе	N;ACC;DEF;PL
өлгө	өлгөләргә	N;DAT;PL
һорау	һорауҙан	ADJ;ABL;SG
тире	тирегә	N;DAT;SG
даға	дағаларҙа	N;LOC;PL
ир	ир	N;LOC;SG
сифат	сифаттарға	N;DAT;PL
бүҙәнә	бүҙәнәнән	N;ABL;SG
түтәл	түтәлдән	N;ABL;SG
киләсәк заман	киләсәк заманды	N;ACC;DEF;SG
йүтәл	йүтәлдә	N;LOC;SG
сифат	сифатҡа	N;DAT;SG
аҡса	аҡсала	N;LOC;SG
халыҡ	халыҡтарҙа	N;LOC;PL
алмас	алмастарҙы	N;ACC;DEF;PL
ватан	ватанға	N;DAT;SG
белешмә	белешмәне	N;ACC;DEF;SG
өсмөйөш	өсмөйөшкә	N;DAT;SG
ҡағиҙә	ҡағиҙәләрҙән	N;ABL;PL
һалам	һалам	N;NOM;SG
үҫеш	үҫештең	N;GEN;DEF;SG
кимереүсе	кимереүселә	N;LOC;SG
рәт	рәттәргә	N;DAT;PL
яҙ	яҙҙарҙан	N;ABL;PL
дауам	дауамда	N;LOC;SG
бөҙрә	бөҙрәләргә	ADJ;DAT;PL
кимәл	кимәлдең	N;GEN;DEF;SG
үрнәк	үрнәктәрҙә	N;LOC;PL
ҡараңғы	ҡараңғынан	ADJ;ABL;SG
тәңре	тәңренән	N;ABL;SG
һөлөк	һөлөктә	N;LOC;SG
әтәс	әтәстәрҙә	N;LOC;PL
шәреҡ	шәреҡ	ADJ;NOM;SG
үткән заман	үткән заман	N;NOM;SG
белем	белемдә	N;LOC;SG
иҫ	иҫ	N;ABL;SG
маңдай	маңдайҙарға	N;DAT;PL
бүҙәнә	бүҙәнәләрҙең	N;GEN;DEF;PL
йома	йомаға	N;DAT;SG
һарай	һарайларҙың	N;GEN;DEF;PL
сәйхана	сәйханаларҙы	N;ACC;DEF;PL
кәкүк	кәкүк	N;GEN;DEF;SG
диңгеҙ	диңгеҙҙәргә	N;DAT;PL
алмас	алмастар	N;NOM;PL
ҡоҙғон	ҡоҙғондоң	N;GEN;DEF;SG
уҡыусы	уҡыусыла	N;LOC;SG
батша	батшаларға	N;DAT;PL
ҡыуаҡ	ҡыуаҡтарға	N;DAT;PL
атама	атамаларҙың	N;GEN;DEF;PL
ҡотоҡ	ҡотоҡто	N;ACC;DEF;SG
айғолаҡ	айғолаҡтарға	N;DAT;PL
адрес	адрестар	N;NOM;PL
уҡыусы	уҡыусыға	N;DAT;SG
ауһаҡ	ауһаҡта	N;LOC;SG
хата	хата	N;GEN;DEF;PL
буранка	буранкаларҙа	N;LOC;PL
маңдай	маңдайға	N;DAT;SG
көс	көстө	N;ACC;DEF;SG
йәрминкә	йәрминкә	N;NOM;SG
кәкүк	кәкүк	N;LOC;PL
хөкүмәт	хөкүмәттәргә	N;DAT;PL
аяҡ	аяҡтарҙы	N;ACC;DEF;PL
рөхсәт	рөхсәттәр	N;NOM;PL
шама	шама	N;ACC;DEF;SG
бәүел	бәүелдең	N;GEN;DEF;SG
вазифа	вазифаны	N;ACC;DEF;SG
адрес	адрестарҙы	N;ACC;DEF;PL
йүтәл	йүтәлдәрҙән	N;ABL;PL
үҫмер	үҫмерҙәргә	N;DAT;PL
ҡарабойҙай	ҡарабойҙайҙың	N;GEN;DEF;SG
егәр	егәрҙәрҙе	N;ACC;DEF;PL
әңгәмә	әңгәмә	N;ACC;DEF;SG
әңгәмә	әңгәмә	N;ABL;SG
ҡайыш	ҡайышҡа	N;DAT;SG
упҡын	упҡынды	N;ACC;DEF;SG
хәл	хәлдең	N;GEN;DEF;SG
баҫма	баҫмаларға	ADJ;DAT;PL
әтәс	әтәстәр	N;NOM;PL
рәт	рәт	N;NOM;SG
асҡыс	асҡыстың	N;GEN;DEF;SG
өсмөйөш	өсмөйөштән	N;ABL;SG
сифат	сифаттан	N;ABL;SG
пәрҙә	пәрҙәлә	N;LOC;SG
ус	ус	N;ABL;PL
баҫма	баҫманан	ADJ;ABL;SG
төшөнсә	төшөнсәләргә	N;DAT;PL
ҡыуаҡ	ҡыуаҡтарҙың	N;GEN;DEF;PL
ирлән	ирләндәрҙең	N;GEN;DEF;PL
мөьмин	мөьмин	N;DAT;SG
тиҫтә	тиҫтәнең	N;GEN;DEF;SG
терпе	терпенән	N;ABL;SG
барабан	барабанға	N;DAT;SG
танау	танаутың	N;GEN;DEF;SG
ҡояш	ҡояшты	N;ACC;DEF;SG
остаз	остаз	N;NOM;SG
хужалыҡ	хужалыҡтың	N;GEN;DEF;SG
олон	олондарҙан	N;ABL;PL
йәһүд	йәһүд	N;GEN;DEF;SG
япраҡ	япраҡтарҙан	N;ABL;PL
майҙансыҡ	майҙансыҡтарҙан	N;ABL;PL
шәреҡ	шәреҡтең	ADJ;GEN;DEF;SG
йомағара	йомағараның	N;GEN;DEF;SG
үпкә	үпкә	N;ABL;SG
ваҡыт	ваҡыттарҙа	N;LOC;PL
ваҡиға	ваҡиғаға	N;DAT;SG
хоҙай	хоҙайҙы	N;ACC;DEF;SG
алҡа	алҡаны	N;ACC;DEF;SG
арыҫлан	арыҫланда	N;LOC;SG
йәһүд	йәһүд	ADJ;ABL;SG
хәл	хәлдәр	N;NOM;PL
бүре	бүреләр	N;NOM;PL
батыр	батырҙан	N;ABL;SG
енәйәт	енәйәттәрҙең	N;GEN;DEF;PL
йылан	йыландарға	N;DAT;PL
мәрйен	мәрйендең	N;GEN;DEF;SG
бәхет	бәхеттән	N;ABL;SG
мосолман	мосолмандарға	ADJ;DAT;PL
бойондороҡһоҙлоҡ	бойондороҡһоҙлоҡ	N;NOM;SG
һөйләм	һөйләмдәрҙең	N;GEN;DEF;PL
кимәл	кимәлдә	N;LOC;SG
хаҡ	хаҡтарға	ADJ;DAT;PL
уҡыусы	уҡыусыларға	N;DAT;PL
урынбаҫар	урынбаҫарға	N;DAT;SG
көҙ	көҙҙән	N;ABL;SG
баҫҡыс	баҫҡыстың	N;GEN;DEF;SG
рөхсәт	рөхсәт	N;NOM;SG
ҡайын	ҡайында	N;LOC;SG
төрткө	төрткө	N;NOM;SG
мәрйен	мәрйендән	N;ABL;SG
урынбаҫар	урынбаҫарҙың	N;GEN;DEF;SG
ваҡиға	ваҡиғаларҙан	N;ABL;PL
йүтәл	йүтәлдәрҙә	N;LOC;PL
ҡусты	ҡустыларҙан	N;ABL;PL
борос	боростоң	N;GEN;DEF;SG
мышы	мышыға	N;DAT;SG
әфәнде	әфәнделәрҙән	N;ABL;PL
муйын	муйынға	N;DAT;SG
торлаҡ	торлаҡтарҙы	N;ACC;DEF;PL
бабай	бабайҙарҙа	N;LOC;PL
ишәк	ишәкте	N;ACC;DEF;SG
ишәк	ишәктән	N;ABL;SG
ҡотоҡ	ҡотоҡтарҙа	N;LOC;PL
имән	имәндең	N;GEN;DEF;SG
йылан	йылан	N;NOM;SG
асҡыс	асҡысҡа	N;DAT;SG
тол	толдоң	N;GEN;DEF;SG
мышы	мышыларҙы	N;ACC;DEF;PL
ғибәҙәт	ғибәҙәтте	N;ACC;DEF;SG
муйын	муйын	N;NOM;SG
ҡалай	ҡалайҙа	N;LOC;SG
саңғы	саңғы	N;NOM;SG
тубырсыҡ	тубырсыҡтар	N;NOM;PL
бәпембә	бәпембәгә	N;DAT;SG
ғибәҙәт	ғибәҙәттә	N;LOC;SG
ҡулъяҙма	ҡулъяҙмаларҙың	ADJ;GEN;DEF;PL
милләтсе	милләтселәр	N;NOM;PL
емеш	емештә	N;LOC;SG
хаж	хажда	N;LOC;SG
борғаҡ	борғаҡтарҙан	N;ABL;PL
һыҙыҡ	һыҙыҡҡа	N;DAT;SG
үҫмер	үҫмерҙәрҙә	N;LOC;PL
йома	йоманан	N;ABL;SG
ауыҙ	ауыҙҙарға	N;DAT;PL
ғибәҙәт	ғибәҙәткә	N;DAT;SG
Ылаҡ	Ылаҡта	N;LOC;SG
теләк	теләктә	N;LOC;SG
дуҫ	дуҫ	N;DAT;SG
йылан	йыландың	N;GEN;DEF;SG
ус	ус	N;NOM;PL
еләк	еләкте	N;ACC;DEF;SG
исемлек	исемлектәрҙә	N;LOC;PL
фил	фил	N;NOM;PL
адрес	адрес	N;NOM;SG
дуҫ	дуҫ	N;GEN;DEF;SG
әҫәр	әҫәрҙәрҙе	N;ACC;DEF;PL
һунарсы	һунарсыла	N;LOC;SG
бүҙәнә	бүҙәнәләрҙе	N;ACC;DEF;PL
йәһүд	йәһүд	N;NOM;PL
тол	толдарҙан	N;ABL;PL
бәпембә	бәпембәләрҙең	N;GEN;DEF;PL
мөьмин	мөьмин	N;NOM;PL
Үлсәү	Үлсәүҙе	N;ACC;DEF;SG
емеш	емештәрҙә	N;LOC;PL
яҙыусы	яҙыусыла	N;LOC;SG
ҡанат	ҡанаттарҙы	N;ACC;DEF;PL
көсөк	көсөк	N;NOM;SG
кесаҙна	кесаҙнаға	N;DAT;SG
ислам	исламдың	N;GEN;DEF;SG
бүре	бүрегә	N;DAT;SG
иҫ	иҫ	N;LOC;SG
һөлөк	һөлөктәрҙе	N;ACC;DEF;PL
ғәмәл	ғәмәлдә	N;LOC;SG
алмас	алмастан	N;ABL;SG
тирмәнсе	тирмәнселә	N;LOC;SG
ҡайыш	ҡайышты	N;ACC;DEF;SG
ауыҙ	ауыҙҙарҙан	N;ABL;PL
шаршау	шаршауҙарҙы	N;ACC;DEF;PL
көс	көстәр	N;NOM;PL
тамсы	тамсыға	N;DAT;SG
бүре	бүрелә	N;LOC;SG
тырнаҡ	тырнаҡтарҙың	N;GEN;DEF;PL
саған	сағандарҙа	N;LOC;PL
көнбағыш	көнбағышты	N;ACC;DEF;SG
тәғлимәт	тәғлимәттәргә	N;DAT;PL
төшөнсә	төшөнсәнең	N;GEN;DEF;SG
емтек	емтекте	N;ACC;DEF;SG
умырзая	умырзая	N;ACC;DEF;PL
тауис	тауисҡа	N;DAT;SG
айғолаҡ	айғолаҡтан	N;ABL;SG
ауһаҡ	ауһаҡтарҙы	N;ACC;DEF;PL
яҙ	яҙҙы	N;ACC;DEF;SG
һорау	һорауҙарҙың	ADJ;GEN;DEF;PL
ҡулъяулыҡ	ҡулъяулыҡ	N;NOM;SG
белешмә	белешмәлә	N;LOC;SG
томан	томандарҙа	N;LOC;PL
балан	баландарҙан	N;ABL;PL
муйын	муйындарҙың	N;GEN;DEF;PL
хоҙай	хоҙайға	N;DAT;SG
ғибәҙәт	ғибәҙәттән	N;ABL;SG
Игеҙәктәр	Игеҙәктәргә	N;DAT;SG
ришүәт	ришүәттән	N;ABL;SG
ҡырау	ҡырауҙарға	N;DAT;PL
шәреҡ	шәреҡ	N;NOM;SG
бүре	бүренең	N;GEN;DEF;SG
пәрҙә	пәрҙәләрҙән	N;ABL;PL
барабан	барабанды	N;ACC;DEF;SG
ҡала	ҡалаларға	N;DAT;PL
журнал	журналдың	N;GEN;DEF;SG
ваҡыт	ваҡыттың	N;GEN;DEF;SG
урын	урындарҙың	N;GEN;DEF;PL
бүре	бүренән	N;ABL;SG
беләҙек	беләҙектәрҙә	N;LOC;PL
тал	талдың	N;GEN;DEF;SG
үҫмер	үҫмерҙәрҙе	N;ACC;DEF;PL
ҡарабойҙай	ҡарабойҙайға	N;DAT;SG
ваҡыт	ваҡыттарҙы	N;ACC;DEF;PL
ауһаҡ	ауһаҡтарҙың	N;GEN;DEF;PL
терпе	терпегә	N;DAT;SG
бүҙәнә	бүҙәнәлә	N;LOC;SG
ҡулъяҙма	ҡулъяҙманы	ADJ;ACC;DEF;SG
енәйәт	енәйәткә	N;DAT;SG
Үлсәү	Үлсәүҙән	N;ABL;SG
сүл	сүл	N;DAT;SG
ауыҙ	ауыҙ	N;NOM;SG
сүл	сүл	N;GEN;DEF;PL
уҡыусы	уҡыусыларҙың	N;GEN;DEF;PL
емтек	емтектән	N;ABL;SG
гонаһ	гонаһта	N;LOC;SG
уҫаҡ	уҫаҡтарҙы	N;ACC;DEF;PL
әфәнде	әфәнделәрҙе	N;ACC;DEF;PL
умырзая	умырзая	N;ABL;SG
белешмә	белешмәләргә	N;DAT;PL
үрнәк	үрнәк	N;NOM;SG
үпкә	үпкә	N;ACC;DEF;PL
ҡасҡын	ҡасҡындарҙың	N;GEN;DEF;PL
күбәләк	күбәләккә	N;DAT;SG
ваҡыт	ваҡытта	N;LOC;SG
һунарсы	һунарсыларға	N;DAT;PL
урынбаҫар	урынбаҫарҙарҙы	N;ACC;DEF;PL
тал	талдарҙың	N;GEN;DEF;PL
йәһүд	йәһүд	ADJ;NOM;SG
ҡағиҙә	ҡағиҙәгә	N;DAT;SG
белем	белемде	N;ACC;DEF;SG
ҡарсыҡ	ҡарсыҡтарҙың	N;GEN;DEF;PL
адрес	адрестарҙың	N;GEN;DEF;PL
урынбаҫар	урынбаҫарҙарҙан	N;ABL;PL
әфәнде	әфәнденең	N;GEN;DEF;SG
мөьмин	мөьмин	N;LOC;SG
баҫым	баҫымдан	N;ABL;SG
хат	хаттарҙа	N;LOC;PL
Игеҙәктәр	Игеҙәктәрҙең	N;GEN;DEF;SG
төшөнсә	төшөнсәләр	N;NOM;PL
урынбаҫар	урынбаҫарҙарҙа	N;LOC;PL
иблис	иблис	N;GEN;DEF;SG
ҡалай	ҡалайҙы	N;ACC;DEF;SG
ус	ус	N;DAT;SG
баҫма	баҫмаға	ADJ;DAT;SG
үт	үт	N;LOC;SG
тамсы	тамсынан	N;ABL;SG
бысаҡ	бысаҡтарҙа	N;LOC;PL
йомаҡ	йомаҡтан	N;ABL;SG
бысҡы	бысҡы	N;NOM;SG
тәмәке	тәмәкенең	N;GEN;DEF;SG
хаҡ	хаҡтан	N;ABL;SG
Игеҙәктәр	Игеҙәктәр	N;NOM;SG
дөйә	дөйәнең	N;GEN;DEF;SG
һунарсы	һунарсылар	N;NOM;PL
дөйә	дөйәнән	N;ABL;SG
исемлек	исемлектәрҙең	N;GEN;DEF;PL
төн	төндән	N;ABL;SG
бысҡы	бысҡы	N;DAT;PL
тәүтормош	тәүтормош	ADJ;NOM;SG
балан	баландан	N;ABL;SG
нәркәс	нәркәстәрҙә	N;LOC;PL
көнбағыш	көнбағыштың	N;GEN;DEF;SG
юлдаш	юлдаштан	N;ABL;SG
сумаҙан	сумаҙан	N;NOM;SG
