naturgass	naturgassen	N;DEF;SG
etablering	etableringane	N;DEF;PL
pisk	piskane	N;DEF;PL
torsdag	torsdagar	N;NDEF;PL
utfordre	utfordre	V;IMP
gangsti	gangstiane	N;DEF;PL
haitiar	haitiarane	N;DEF;PL
australiar	australiaren	N;DEF;SG
art	artene	N;DEF;PL
fysikar	fysikarane	N;DEF;PL
hank	hankane	N;DEF;PL
gul	gulaste	ADJ;SPRL;DEF
atrofi	atrofien	N;DEF;SG
separat	separat	ADJ;NEUT;SG
grekar	grekarar	N;NDEF;PL
gruve	gruver	N;NDEF;PL
protein	proteina	N;DEF;PL
militær	militær	ADJ;MASC+FEM
sokk	sokkar	N;NDEF;PL
ynska	ynsk	V;IMP
teater	teater	N;NDEF;PL
berømt	berømt	ADJ;NEUT;SG
brur	brurer	N;NDEF;PL
kvadratrot	kvadratrota	N;DEF;SG
ordre	ordrane	N;DEF;PL
diamant	diamanten	N;DEF;SG
regelmessig	regelmessig	ADJ;NEUT;SG
fotografi	fotografi	N;NDEF;PL
torn	tornar	N;NDEF;PL
nobelpris	nobelprisar	N;NDEF;PL
borgarkrig	borgarkrigane	N;DEF;PL
sølv	sølv	N;NDEF;PL
gjetar	gjetarane	N;DEF;PL
or	orane	N;DEF;PL
mørk	mørkt	ADJ;NEUT
planteetar	planteetarane	N;DEF;PL
ettermiddag	ettermiddagen	N;DEF;SG
kategori	kategorien	N;DEF;SG
dronning	dronninga	N;DEF;SG
akillessene	akillessener	N;NDEF;PL
utløp	utløp	N;NDEF;PL
terrorangrep	terrorangrepet	N;DEF;SG
krystallklar	krystallklart	ADJ;NEUT;SG
snøplog	snøplogar	N;NDEF;PL
kikert	kikertar	N;NDEF;PL
tykkja	tykk	V;IMP
advokat	advokatane	N;DEF;PL
hank	hanken	N;DEF;SG
veskenappar	veskenapparane	N;DEF;PL
bok	boka	N;DEF;SG
fengsel	fengsla	N;DEF;PL
apostrof	apostrofane	N;DEF;PL
milliliter	milliliterane	N;DEF;PL
dominikanar	dominikanaren	N;DEF;SG
stoff	stoffet	N;DEF;SG
total	totale	N;DEF;SG+PL
hale	halar	N;NDEF;PL
sørkorean	sørkoreanane	N;DEF;PL
nigerar	nigeraren	N;DEF;SG
oseanograf	oseanografar	N;NDEF;PL
ending	endingar	N;NDEF;PL
fredeleg	fredelegaste	ADJ;SPRL;DEF
vokabular	vokabularet	N;DEF;SG
enorm	enorme	N;DEF;SG+PL
marknad	marknadene	N;DEF;PL
fascinere	fascinerte	V;PST
politikvinne	politikvinnene	N;DEF;PL
kystlinje	kystlinjer	N;NDEF;PL
bilist	bilistar	N;NDEF;PL
stavemåte	stavemåtar	N;NDEF;PL
bergmann	bergmennene	N;DEF;PL
åtaka	åtak	V;IMP
talent	talentet	N;DEF;SG
einig	einigaste	ADJ;SPRL;DEF
erobre	erobrar	V;PRS
avla	avlast	V;NFIN;PASS
slenga	slengde	V;PST
treverk	treverka	N;DEF;PL
kopp	koppar	N;NDEF;PL
tårn	tårn	N;NDEF;PL
fabrikant	fabrikanten	N;DEF;SG
kvinnfolk	kvinnfolk	N;NDEF;PL
glidelås	glidelåsar	N;NDEF;PL
omgivnad	omgivnader	N;NDEF;PL
femdel	femdelar	N;NDEF;PL
resultat	resultata	N;DEF;PL
drepa	drep	V;IMP
kapitalist	kapitalistar	N;NDEF;PL
dårleg	dårlegaste	ADJ;SPRL;DEF
hendig	hendige	N;DEF;SG+PL
forbindelse	forbindelsar	N;NDEF;PL
uregistrert	uregistrert	ADJ;NEUT;SG
blære	blærer	N;NDEF;PL
sist	siste	N;DEF;SG+PL
måke	måka	N;DEF;SG
pol	polen	N;DEF;SG
anbefaling	anbefalingar	N;NDEF;PL
kronhjort	kronhjortar	N;NDEF;PL
kaste	kastar	N;NDEF;PL
forvirring	forvirringane	N;DEF;PL
aksel	akslane	N;DEF;PL
bukett	bukettar	N;NDEF;PL
system	systemet	N;DEF;SG
oppvaskmaskin	oppvaskmaskina	N;DEF;SG
lerke	lerkene	N;DEF;PL
tru	trudde	V;PST
feiebrett	feiebrettet	N;DEF;SG
krokodille	krokodiller	N;NDEF;PL
milliardær	milliardærar	N;NDEF;PL
gruve	gruvene	N;DEF;PL
kongefamilie	kongefamiliane	N;DEF;PL
bein	bein	N;NDEF;PL
diaré	diaréane	N;DEF;PL
idé	idéen	N;DEF;SG
troll	trollet	N;DEF;SG
kor	kora	N;DEF;PL
vaksine	vaksinen	N;DEF;SG
søt	søte	N;DEF;SG+PL
selskap	selskapet	N;DEF;SG
åtaka	åtek	V;PRS
invasjon	invasjonar	N;NDEF;PL
offisiell	offisielle	N;DEF;SG+PL
arkitekt	arkitektane	N;DEF;PL
rekord	rekorden	N;DEF;SG
kamel	kamelar	N;NDEF;PL
ynska	ynsker	V;PRS
høyre	høyrde	V;PST
hyperbol	hyperbolane	N;DEF;PL
kartograf	kartografen	N;DEF;SG
hemn	hemnen	N;DEF;SG
volum	volumet	N;DEF;SG
magnolia	magnoliaer	N;NDEF;PL
zambiar	zambiarar	N;NDEF;PL
solur	solura	N;DEF;PL
kubanar	kubanarar	N;NDEF;PL
fåe	færre	ADJ;CMPR
padde	padda	N;DEF;SG
overmoden	overmodent	ADJ;NEUT;SG
resymé	resymea	N;DEF;PL
bestemor	bestemødrer	N;NDEF;PL
tvilling	tvillingen	N;DEF;SG
byrja	byrja	V;IMP
hyene	hyenar	N;NDEF;PL
luxembourgar	luxembourgarane	N;DEF;PL
engelskmann	engelskmannen	N;DEF;SG
tank	tankane	N;DEF;PL
flyt	flyten	N;DEF;SG
minusgrad	minusgradar	N;NDEF;PL
minoritet	minoritetar	N;NDEF;PL
drepa	drepast	V;NFIN;PASS
tyde	tyder	V;PRS
føre	før	V;IMP
tittel	titlane	N;DEF;PL
magnetfelt	magnetfelta	N;DEF;PL
gjest	gjester	N;NDEF;PL
positiv	positivt	ADJ;NEUT;SG
barnesoldat	barnesoldaten	N;DEF;SG
estlendar	estlendarane	N;DEF;PL
dør	dører	N;NDEF;PL
vêrmelding	vêrmeldingar	N;NDEF;PL
navlestreng	navlestrengene	N;DEF;PL
minusgrad	minusgrada	N;DEF;SG
undulat	undulatane	N;DEF;PL
konsonant	konsonantane	N;DEF;PL
fjernkontroll	fjernkontrollen	N;DEF;SG
bjart	bjartaste	ADJ;SPRL;DEF
rullestol	rullestolen	N;DEF;SG
komme	kjem	V;PRS
hellenar	hellenarane	N;DEF;PL
barrikade	barrikaden	N;DEF;SG
pinleg	pinlegast	ADJ;SPRL;NDEF
kjøpe	kjøper	V;PRS
romersk	romerskaste	ADJ;SPRL;DEF
hekka	hekka	V;PST
nøytron	nøytronen	N;DEF;SG
finne	finnen	N;DEF;SG
oppteken	opptekne	N;DEF;SG+PL
verkeleg	verkelege	N;DEF;SG+PL
stearinlys	stearinlysa	N;DEF;PL
programmering	programmeringar	N;NDEF;PL
skremma	skremde	V;PST
meksikan	meksikanane	N;DEF;PL
fotball	fotballen	N;DEF;SG
veng	vengene	N;DEF;PL
ministerium	ministeriet	N;DEF;SG
forskjellig	forskjellig	ADJ;NEUT;SG
død	dødaste	ADJ;SPRL;DEF
bylgje	bylgjene	N;DEF;PL
fotografi	fotografia	N;DEF;PL
lår	låra	N;DEF;PL
halda	heldt	V;PST
brasme	brasmene	N;DEF;PL
skandinav	skandinavane	N;DEF;PL
sitje	sit	V;IMP
forslag	forslaget	N;DEF;SG
konkurrent	konkurrentar	N;NDEF;PL
serviett	servietten	N;DEF;SG
satire	satirane	N;DEF;PL
vert	vertar	N;NDEF;PL
verkeleg	verkeleg	ADJ;NDEF;SG
harddisk	harddiskar	N;NDEF;PL
idé	idear	N;NDEF;PL
sanddyne	sanddyner	N;NDEF;PL
hår	hår	N;NDEF;PL
guineanar	guineanarar	N;NDEF;PL
mauritiar	mauritiaren	N;DEF;SG
yrke	yrke	N;NDEF;PL
indar	indarar	N;NDEF;PL
ringe	ring	V;IMP
tunna	tunnast	V;NFIN;PASS
arbeidsgjevar	arbeidsgjevarane	N;DEF;PL
plan	planen	N;DEF;SG
feire	feirast	V;NFIN;PASS
armenar	armenaren	N;DEF;SG
boks	boksane	N;DEF;PL
reparasjon	reparasjonar	N;NDEF;PL
stridsøks	stridsøksene	N;DEF;PL
entomolog	entomologen	N;DEF;SG
forkasta	forkastast	V;NFIN;PASS
bulgarsk	bulgarsken	N;DEF;SG
landemerke	landemerke	N;NDEF;PL
tiger	tigerane	N;DEF;PL
åtvara	åtvara	V;PST
folketeljing	folketeljingar	N;NDEF;PL
miniskjørt	miniskjørtet	N;DEF;SG
sokk	sokkane	N;DEF;PL
reparasjon	reparasjonen	N;DEF;SG
eliminere	eliminerte	V;PST
no	noet	N;DEF;SG
bratsj	bratsjane	N;DEF;PL
eftan	eftanar	N;NDEF;PL
ideologi	ideologiane	N;DEF;PL
ornitologisk	ornitologisk	ADJ;NEUT;SG
midje	midja	N;DEF;SG
kjæledyr	kjæledyret	N;DEF;SG
resepsjonist	resepsjonistane	N;DEF;PL
ligga	ligg	V;PRS
medlemskap	medlemskapane	N;DEF;PL
primitiv	primitivt	ADJ;NEUT;SG
sump	sumpen	N;DEF;SG
tonn	tonnet	N;DEF;SG
singaporar	singaporarar	N;NDEF;PL
maksimal	maksimale	N;DEF;SG+PL
attraksjon	attraksjonar	N;NDEF;PL
fontene	fontenene	N;DEF;PL
palass	palassa	N;DEF;PL
venleg	venleg	ADJ;NDEF;SG
katastrofal	katastrofalt	ADJ;NEUT
dominikanar	dominikanarane	N;DEF;PL
akillessene	akillessenene	N;DEF;PL
halda	haldast	V;NFIN;PASS
ekvatorialguinean	ekvatorialguineanar	N;NDEF;PL
lufttett	lufttette	N;DEF;SG+PL
libyar	libyarar	N;NDEF;PL
erfaren	erfarent	ADJ;NEUT;SG
armeniar	armeniarar	N;NDEF;PL
kresen	krese	ADJ;NEUT;SG
mark	markar	N;NDEF;PL
lege	legar	N;NDEF;PL
legering	legeringane	N;DEF;PL
melon	melonar	N;NDEF;PL
munk	munken	N;DEF;SG
thailandsk	thailandske	N;DEF;SG+PL
komfyr	komfyrane	N;DEF;PL
minoritet	minoritetane	N;DEF;PL
halda	hald	V;IMP
maskin	maskina	N;DEF;SG
fotografi	fotografiet	N;DEF;SG
vêr	vêr	N;NDEF;PL
tommelfinger	tommelfingrane	N;DEF;PL
rytme	rytmen	N;DEF;SG
erobre	erobre	V;IMP
kremasjon	kremasjonen	N;DEF;SG
solist	solistar	N;NDEF;PL
syntese	syntesane	N;DEF;PL
kusine	kusiner	N;NDEF;PL
soloppgang	soloppgangen	N;DEF;SG
entreprenør	entreprenørane	N;DEF;PL
synd	synda	N;DEF;SG
hertug	hertugar	N;NDEF;PL
eksplodere	eksploderer	V;PRS
naken	nakne	N;DEF;SG+PL
selje	selde	V;PST
parkeringsplass	parkeringsplassar	N;NDEF;PL
livmor	livmorene	N;DEF;PL
komet	kometane	N;DEF;PL
bolivianar	bolivianaren	N;DEF;SG
nasjonalitet	nasjonalitetane	N;DEF;PL
tittel	titlar	N;NDEF;PL
skisse	skisser	N;NDEF;PL
eksistera	eksisterer	V;PRS
flyterminal	flyterminalen	N;DEF;SG
slutte	sluttast	V;NFIN;PASS
orrhøne	orrhøner	N;NDEF;PL
hestesko	hesteskoen	N;DEF;SG
blære	blærene	N;DEF;PL
drypp	dryppa	N;DEF;PL
offentleg	offentlege	N;DEF;SG+PL
destilleri	destilleria	N;DEF;PL
rein	reinar	N;NDEF;PL
stavemåte	stavemåten	N;DEF;SG
kalv	kalven	N;DEF;SG
anakronisme	anakronismen	N;DEF;SG
maskin	maskinane	N;DEF;PL
vind	vindar	N;NDEF;PL
skjematisk	skjematisk	ADJ;NEUT;SG
revolusjonær	revolusjonært	ADJ;NDEF;NEUT;SG
hemn	hemnane	N;DEF;PL
allé	alléar	N;NDEF;PL
kunst	kunster	N;NDEF;PL
hengebru	hengebruer	N;NDEF;PL
norrøn	norrønt	ADJ;NEUT;SG
omen	omena	N;DEF;PL
ponni	ponniar	N;NDEF;PL
sau	sauene	N;DEF;PL
hakekross	hakekrossane	N;DEF;PL
ekorn	ekorn	N;NDEF;PL
elektrikar	elektrikarar	N;NDEF;PL
skytar	skytarane	N;DEF;PL
rund	rundaste	ADJ;SPRL;DEF
smaragd	smaragdane	N;DEF;PL
musikal	musikalar	N;NDEF;PL
ministerium	ministeria	N;DEF;PL
dal	dalen	N;DEF;SG
vinter	vintrane	N;DEF;PL
konse	konsar	V;PRS
slengje	sleng	V;IMP
gjest	gjestene	N;DEF;PL
sentralafrikan	sentralafrikanen	N;DEF;SG
nykel	nykelen	N;DEF;SG
verkeleg	verkelegare	ADJ;CMPR
fort	fort	N;NDEF;PL
sanning	sanningar	N;NDEF;PL
undersøkje	undersøk	V;IMP
gris	grisar	N;NDEF;PL
hovudstad	hovudstadar	N;NDEF;PL
alkoholikar	alkoholikaren	N;DEF;SG
adamseple	adamseple	N;NDEF;PL
opphav	opphav	N;NDEF;PL
skade	skadane	N;DEF;PL
fobi	fobien	N;DEF;SG
hovud	hovuda	N;DEF;PL
pinleg	pinlegaste	ADJ;SPRL;DEF
aminosyre	aminosyra	N;DEF;SG
gambiar	gambiaren	N;DEF;SG
person	personar	N;NDEF;PL
oppvaskmiddel	oppvaskmiddelet	N;DEF;SG
nygift	nygift	ADJ;NEUT;SG
snøplog	snøplogen	N;DEF;SG
julegåve	julegåva	N;DEF;SG
maskara	maskaraen	N;DEF;SG
tunnelbane	tunnelbanar	N;NDEF;PL
tanzanianar	tanzanianarane	N;DEF;PL
pengeskap	pengeskapet	N;DEF;SG
konsert	konsertar	N;NDEF;PL
ven	venen	N;DEF;SG
regnskog	regnskogane	N;DEF;PL
taiwanar	taiwanarar	N;NDEF;PL
katastrofe	katastrofen	N;DEF;SG
advokat	advokaten	N;DEF;SG
koma	kom	V;IMP
ha	havast	V;NFIN;PASS
ballkjole	ballkjolen	N;DEF;SG
scene	scenar	N;NDEF;PL
gløyma	gløymast	V;NFIN;PASS
interiør	interiøra	N;DEF;PL
brukar	brukarar	N;NDEF;PL
kor	koret	N;DEF;SG
planet	planetane	N;DEF;PL
sterk	sterke	N;DEF;SG+PL
sikte	sikta	N;DEF;PL
hovudstad	hovudstadene	N;DEF;PL
monument	monumentet	N;DEF;SG
tillegg	tillegga	N;DEF;PL
klesskap	klesskapet	N;DEF;SG
setebelte	setebelta	N;DEF;PL
sirkulasjon	sirkulasjonane	N;DEF;PL
fin	finare	ADJ;CMPR
terreng	terrenga	N;DEF;PL
halvøy	halvøyene	N;DEF;PL
snøras	snøras	N;NDEF;PL
glidelås	glidelåsane	N;DEF;PL
garanti	garantiar	N;NDEF;PL
maskin	maskiner	N;NDEF;PL
kjøttmeis	kjøttmeisene	N;DEF;PL
tusenbein	tusenbein	N;NDEF;PL
bidrag	bidraget	N;DEF;SG
litteratur	litteraturane	N;DEF;PL
autentisk	autentisk	ADJ;NEUT;SG
bergensar	bergensarane	N;DEF;PL
regnbogeaure	regnbogeaurar	N;NDEF;PL
raudrev	raudrevane	N;DEF;PL
bokhandel	bokhandelen	N;DEF;SG
finale	finalar	N;NDEF;PL
styrkje	styrk	V;IMP
kunstverk	kunstverk	N;NDEF;PL
fijian	fijianane	N;DEF;PL
byggja	bygde	V;PST
jamaikanar	jamaikanarane	N;DEF;PL
verja	verja	V;PST
hendig	hendigaste	ADJ;SPRL;DEF
mal	malane	N;DEF;PL
ongel	ongelar	N;NDEF;PL
skytar	skytarar	N;NDEF;PL
aktiv	aktivt	ADJ;NEUT;SG
kjøkkenbenk	kjøkkenbenkane	N;DEF;PL
piggvar	piggvaren	N;DEF;SG
region	regionane	N;DEF;PL
havfrue	havfruer	N;NDEF;PL
portugis	portugisar	N;NDEF;PL
ung	yngre	ADJ;CMPR
avla	avla	V;PST
madagassar	madagassarar	N;NDEF;PL
plan	planaste	ADJ;SPRL;DEF
feromon	feromona	N;DEF;PL
diagnose	diagnosar	N;NDEF;PL
kompressor	kompressorar	N;NDEF;PL
vanleg	vanlegare	ADJ;CMPR
svarttrast	svarttrasta	N;DEF;SG
skoleveske	skoleveska	N;DEF;SG
tastatur	tastaturet	N;DEF;SG
diagram	diagram	N;NDEF;PL
turbulens	turbulensane	N;DEF;PL
tavle	tavler	N;NDEF;PL
handflate	handflater	N;NDEF;PL
gummistøvel	gummistøvelen	N;DEF;SG
roleg	rolegaste	ADJ;SPRL;DEF
AUF-ar	AUF-arane	N;DEF;PL
rwandar	rwandarane	N;DEF;PL
parykk	parykkane	N;DEF;PL
naboland	naboland	N;NDEF;PL
girkasse	girkassa	N;DEF;SG
radar	radarar	N;NDEF;PL
panne	pannene	N;DEF;PL
passform	passforma	N;DEF;SG
smal	smale	N;DEF;SG+PL
rusten	ruste	ADJ;NEUT;SG
trinidadar	trinidadarane	N;DEF;PL
mytologi	mytologiane	N;DEF;PL
telefon	telefonar	N;NDEF;PL
amatør	amatøren	N;DEF;SG
dekka	dekkast	V;NFIN;PASS
samd	samde	N;DEF;SG+PL
skole	skolane	N;DEF;PL
arkiv	arkiv	N;NDEF;PL
søppelbøtte	søppelbøtter	N;NDEF;PL
autoritet	autoriteten	N;DEF;SG
hanske	hansken	N;DEF;SG
brannmur	brannmurane	N;DEF;PL
logo	logoen	N;DEF;SG
bombefly	bombefly	N;NDEF;PL
klimaendring	klimaendringane	N;DEF;PL
kvalfangar	kvalfangarane	N;DEF;PL
armé	armear	N;NDEF;PL
marokkanar	marokkanaren	N;DEF;SG
fortene	forten	V;IMP
gjera	gjerast	V;NFIN;PASS
galoppbane	galoppbanen	N;DEF;SG
open	opne	N;DEF;SG+PL
hendig	hendigare	ADJ;CMPR
gjetar	gjetaren	N;DEF;SG
rabatt	rabattar	N;NDEF;PL
container	containerar	N;NDEF;PL
høgskole	høgskolen	N;DEF;SG
banan	bananar	N;NDEF;PL
spøkje	spøkjast	V;NFIN;PASS
tap	tapet	N;DEF;SG
girspak	girspakane	N;DEF;PL
solsikke	solsikker	N;NDEF;PL
periode	periodane	N;DEF;PL
øydelegga	øydela	V;PST
repertoar	repertoara	N;DEF;PL
ghanesar	ghanesarar	N;NDEF;PL
navlestreng	navlestrengar	N;NDEF;PL
finale	finalane	N;DEF;PL
datamaskin	datamaskinar	N;NDEF;PL
bordduk	bordduken	N;DEF;SG
reagens	reagensar	N;NDEF;PL
nederlendar	nederlendarar	N;NDEF;PL
engsteleg	engstelege	N;DEF;SG+PL
jakt	jakter	N;NDEF;PL
angolanar	angolanarar	N;NDEF;PL
invasjon	invasjonane	N;DEF;PL
tå	tær	N;NDEF;PL
osean	osean	N;NDEF;PL
greia	greiast	V;NFIN;PASS
mandel	mandlane	N;DEF;PL
honduran	honduranen	N;DEF;SG
simulering	simuleringa	N;DEF;SG
pil	pilene	N;DEF;PL
verdsrekord	verdsrekordar	N;NDEF;PL
irsk	irske	N;DEF;SG+PL
sfære	sfæren	N;DEF;SG
montenegrinsk	montenegrinsk	ADJ;NEUT;SG
fijian	fijianen	N;DEF;SG
geologisk	geologiske	N;DEF;SG+PL
restaurant	restaurantane	N;DEF;PL
juletre	juletra	N;DEF;PL
gøyme	gøymer	V;PRS
rogn	rognen	N;DEF;SG
betennelse	betennelsane	N;DEF;PL
løytnant	løytnantane	N;DEF;PL
morsmål	morsmåla	N;DEF;PL
jolaftan	jolaftanen	N;DEF;SG
srilankar	srilankarane	N;DEF;PL
romstasjon	romstasjonar	N;NDEF;PL
klinkekule	klinkekuler	N;NDEF;PL
skinke	skinkene	N;DEF;PL
detta	dett	V;IMP
redaktør	redaktørar	N;NDEF;PL
plattform	plattformer	N;NDEF;PL
ring	ringen	N;DEF;SG
økonom	økonomen	N;DEF;SG
transport	transporten	N;DEF;SG
varemerke	varemerke	N;NDEF;PL
løysa	løys	V;IMP
søka	søkte	V;PST
bukt	buktene	N;DEF;PL
delirium	delirium	N;NDEF;PL
ynska	ynskast	V;NFIN;PASS
naturlov	naturlovane	N;DEF;PL
skarv	skarven	N;DEF;SG
varsam	varsamt	ADJ;NEUT
apekatt	apekattar	N;NDEF;PL
frukt	fruktene	N;DEF;PL
hyperlenkje	hyperlenkjene	N;DEF;PL
pære	pærer	N;NDEF;PL
nonne	nonner	N;NDEF;PL
tyde	tyd	V;IMP
gulrot	gulrota	N;DEF;SG
angre	angra	V;PST
breiflabb	breiflabbar	N;NDEF;PL
setebelte	setebelte	N;NDEF;PL
samarbeide	samarbeidast	V;NFIN;PASS
falk	falken	N;DEF;SG
kaste	kaste	V;IMP
køyre	køyrde	V;PST
republikk	republikken	N;DEF;SG
møte	møta	N;DEF;PL
detalj	detaljar	N;NDEF;PL
sakne	saknast	V;NFIN;PASS
utgang	utgangar	N;NDEF;PL
honduranar	honduranarar	N;NDEF;PL
influensa	influensaene	N;DEF;PL
åsyn	åsyn	N;NDEF;PL
hugsa	hugsar	V;PRS
boks	boksar	N;NDEF;PL
hebraisk	hebraiske	N;DEF;SG+PL
fattigdom	fattigdomen	N;DEF;SG
antiguanar	antiguanaren	N;DEF;SG
minutt	minutt	N;NDEF;PL
torpedo	torpedoane	N;DEF;PL
bety	betyr	V;PRS
kosa	kosa	V;PST
skorpion	skorpionen	N;DEF;SG
elskarinne	elskarinna	N;DEF;SG
bakterie	bakteriar	N;NDEF;PL
gir	gira	N;DEF;PL
vøla	vøl	V;IMP
festival	festivalane	N;DEF;PL
rev	reven	N;DEF;SG
omgivnad	omgivnaden	N;DEF;SG
langskip	langskipa	N;DEF;PL
kapittel	kapitla	N;DEF;PL
paraguayanar	paraguayanaren	N;DEF;SG
arm	arme	N;DEF;SG+PL
sabotør	sabotøren	N;DEF;SG
solsikke	solsikka	N;DEF;SG
ordtak	ordtaket	N;DEF;SG
hyperkopling	hyperkoplinga	N;DEF;SG
julaftan	julaftanen	N;DEF;SG
universitet	universiteta	N;DEF;PL
avsnitt	avsnitt	N;NDEF;PL
balalaika	balalaikaer	N;NDEF;PL
utland	utland	N;NDEF;PL
rand	render	N;NDEF;PL
skandinavisk	skandinaviske	N;DEF;SG+PL
pedal	pedalar	N;NDEF;PL
besøkje	besøkjer	V;PRS
landsby	landsbyen	N;DEF;SG
undersøka	undersøkast	V;NFIN;PASS
hyse	hysene	N;DEF;PL
rekord	rekordane	N;DEF;PL
kjøp	kjøpa	N;DEF;PL
albanar	albanarane	N;DEF;PL
bjørk	bjørkene	N;DEF;PL
fin	fint	ADJ;NEUT
uoffisiell	uoffisielt	ADJ;NEUT;SG
andorranar	andorranarar	N;NDEF;PL
mark	marka	N;DEF;SG
sandal	sandalane	N;DEF;PL
grunnflate	grunnflatene	N;DEF;PL
kryssarrakett	kryssarraketten	N;DEF;SG
bom	bommane	N;DEF;PL
tygga	tygg	V;IMP
naturkatastrofe	naturkatastrofane	N;DEF;PL
plass	plassar	N;NDEF;PL
hellenar	hellenaren	N;DEF;SG
kjensle	kjensler	N;NDEF;PL
inskripsjon	inskripsjonane	N;DEF;PL
tap	tap	N;NDEF;PL
ferdast	ferdast	V;IMP
notisbok	notisboka	N;DEF;SG
svigerbror	svigerbroren	N;DEF;SG
høg	høgt	ADJ;NEUT
journalist	journalistane	N;DEF;PL
tillegg	tillegg	N;NDEF;PL
administrasjon	administrasjonen	N;DEF;SG
tekopp	tekoppen	N;DEF;SG
eid	eiden	N;DEF;SG
undersøka	undersøker	V;PRS
magnolia	magnoliaar	N;NDEF;PL
rektor	rektorar	N;NDEF;PL
spark	sparket	N;DEF;SG
langfinger	langfingrane	N;DEF;PL
nyttelast	nyttelastene	N;DEF;PL
srilankar	srilankaren	N;DEF;SG
motvekt	motvektene	N;DEF;PL
månefisk	månefiskane	N;DEF;PL
siriss	sirissane	N;DEF;PL
synga	syng	V;IMP
brannbil	brannbilen	N;DEF;SG
ubåt	ubåtane	N;DEF;PL
åndeleg	åndeleg	ADJ;NDEF;SG
tørketrommel	tørketrommelen	N;DEF;SG
horngjel	horngjelar	N;NDEF;PL
forgløymmegei	forgløymmegeiar	N;NDEF;PL
korridor	korridorar	N;NDEF;PL
monarkisk	monarkiske	N;DEF;SG+PL
mange	fleire	ADJ;CMPR
dialekt	dialektene	N;DEF;PL
magedans	magedansar	N;NDEF;PL
kaste	kastane	N;DEF;PL
kabin	kabinar	N;NDEF;PL
romstasjon	romstasjonen	N;DEF;SG
følge	følgast	V;NFIN;PASS
sjølvmordsbombar	sjølvmordsbombarane	N;DEF;PL
fallskjerm	fallskjermane	N;DEF;PL
diktatur	diktaturet	N;DEF;SG
sekret	sekreta	N;DEF;PL
terreng	terrenget	N;DEF;SG
bru	bruer	N;NDEF;PL
radikal	radikalt	ADJ;NEUT
sloven	slovenen	N;DEF;SG
tefat	tefat	N;NDEF;PL
kai	kaien	N;DEF;SG
investering	investeringa	N;DEF;SG
krem	kremane	N;DEF;PL
mutter	mutterane	N;DEF;PL
radar	radarane	N;DEF;PL
svindel	svindlane	N;DEF;PL
bakteriolog	bakteriologen	N;DEF;SG
engelskmann	engelskmennene	N;DEF;PL
karakter	karakterar	N;NDEF;PL
kalv	kalvane	N;DEF;PL
terapi	terapiar	N;NDEF;PL
andrespråk	andrespråka	N;DEF;PL
land	landet	N;DEF;SG
saudiar	saudiaren	N;DEF;SG
tå	tærne	N;DEF;PL
polsk	polske	N;DEF;SG+PL
angripe	angrip	V;PRS
sko	skoen	N;DEF;SG
eliminera	eliminer	V;IMP
innbyggjar	innbyggjarane	N;DEF;PL
bergta	bergtakast	V;NFIN;PASS
skal	skala	N;DEF;PL
sjeldan	sjeldnare	ADJ;CMPR
konkurrere	konkurrerast	V;NFIN;PASS
brur	brurene	N;DEF;PL
plagg	plagg	N;NDEF;PL
øydelegge	øydelegg	V;PRS
søring	søringen	N;DEF;SG
konsulent	konsulentane	N;DEF;PL
dumheit	dumheita	N;DEF;SG
hand	hender	N;NDEF;PL
verte	vert	V;PRS
eksplodere	eksploderte	V;PST
hage	hagar	N;NDEF;PL
bosniar	bosniarane	N;DEF;PL
søvn	søvne	N;DAT
maksimum	maksimuma	N;DEF;PL
komme	kom	V;PST
kjedereaksjon	kjedereaksjonen	N;DEF;SG
serbisk	serbisk	ADJ;NEUT;SG
år	årar	N;NDEF;PL
avhengig	avhengige	N;DEF;SG+PL
glasmanet	glasmaneter	N;NDEF;PL
skodespelar	skodespelaren	N;DEF;SG
besøkje	besøkjast	V;NFIN;PASS
kvadratkilometer	kvadratkilometerane	N;DEF;PL
svigerbror	svigerbrør	N;NDEF;PL
hjarte	hjarte	N;NDEF;PL
spøka	spøker	V;PRS
tena	tener	V;PRS
basilikum	basilikumar	N;NDEF;PL
gjensidig	gjensidige	N;DEF;SG+PL
sitja	sat	V;PST
åndeleg	åndelegast	ADJ;SPRL;NDEF
ampulle	ampullen	N;DEF;SG
måse	måsen	N;DEF;SG
terroråtak	terroråtaka	N;DEF;PL
forventning	forventningar	N;NDEF;PL
fiolin	fiolinar	N;NDEF;PL
skoleveske	skoleveskene	N;DEF;PL
eufemisme	eufemismane	N;DEF;PL
sverm	svermar	N;NDEF;PL
tunnelbane	tunnelbana	N;DEF;SG
frø	frø	N;NDEF;PL
stor	største	ADJ;SPRL;DEF
hava	har	V;PRS
kinn	kinnet	N;DEF;SG
land	land	N;NDEF;PL
islandsk	islandsk	ADJ;NEUT;SG
sjukebil	sjukebilane	N;DEF;PL
musikal	musikalane	N;DEF;PL
pigment	pigmenta	N;DEF;PL
eik	eikene	N;DEF;PL
energi	energiar	N;NDEF;PL
tyda	tydde	V;PST
bikini	bikiniar	N;NDEF;PL
avis	avisa	N;DEF;SG
trufast	trufast	ADJ;NDEF;SG
arktisk	arktiske	N;DEF;SG+PL
hage	hagen	N;DEF;SG
trekant	trekantane	N;DEF;PL
høg	høgre	ADJ;CMPR
lengdegrad	lengdegrada	N;DEF;SG
sikker	sikre	N;DEF;SG+PL
hevelse	hevelsen	N;DEF;SG
ven	venene	N;DEF;PL
teknikk	teknikken	N;DEF;SG
skarv	skarvar	N;NDEF;PL
hengsel	hengselet	N;DEF;SG
eksemplarisk	eksemplarisk	ADJ;SPRL
maldiv	maldiven	N;DEF;SG
olje	oljane	N;DEF;PL
datasimulering	datasimuleringane	N;DEF;PL
kjemisk	kjemisk	ADJ;NEUT;SG
belizar	belizarar	N;NDEF;PL
spesiell	spesielt	ADJ;NEUT;SG
frukost	frukosten	N;DEF;SG
ventil	ventilar	N;NDEF;PL
særleg	særlegast	ADJ;SPRL;NDEF
undergang	undergangen	N;DEF;SG
reagens	reagenset	N;DEF;SG
fotograf	fotografar	N;NDEF;PL
glorie	gloriar	N;NDEF;PL
konvolutt	konvoluttane	N;DEF;PL
kilometer	kilometeren	N;DEF;SG
skrift	skrifter	N;NDEF;PL
naudsynt	naudsynte	N;DEF;SG+PL
kjølig	kjøligast	ADJ;SPRL;NDEF
stoppekran	stoppekrana	N;DEF;SG
vilja	viljast	V;NFIN;PASS
verna	verna	V;PST
midtlinje	midtlinja	N;DEF;SG
gælisk	gæliske	N;DEF;SG+PL
styrke	styrk	V;IMP
egyptisk	egyptiske	N;DEF;SG+PL
nysgjerrig	nysgjerrige	N;DEF;SG+PL
troll	troll	N;NDEF;PL
tråd	trådar	N;NDEF;PL
laurdag	laurdagar	N;NDEF;PL
madrass	madrassar	N;NDEF;PL
veskenappar	veskenapparen	N;DEF;SG
væpne	væpnast	V;NFIN;PASS
artikkel	artiklane	N;DEF;PL
mannleg	mannlege	N;DEF;SG+PL
organisasjon	organisasjonar	N;NDEF;PL
usbekar	usbekarane	N;DEF;PL
sanning	sanningane	N;DEF;PL
kontakt	kontaktar	N;NDEF;PL
væske	væskene	N;DEF;PL
prinsipp	prinsippet	N;DEF;SG
bit	bitet	N;DEF;SG
vibrasjon	vibrasjonar	N;NDEF;PL
kjøpesenter	kjøpesenter	N;NDEF;PL
sprøyte	sprøyta	N;DEF;SG
vaksen	vaksnast	ADJ;SPRL;NDEF
fasinera	fasinerast	V;NFIN;PASS
presang	presangen	N;DEF;SG
naud	nauda	N;DEF;SG
regjering	regjeringane	N;DEF;PL
gløyme	gløymast	V;NFIN;PASS
gigantisk	gigantisk	ADJ;NEUT;SG
ligga	låg	V;PST
herskar	herskaren	N;DEF;SG
ven	venane	N;DEF;PL
kjempe	kjemper	N;NDEF;PL
hjarte	hjartet	N;DEF;SG
hake	hakene	N;DEF;PL
angripe	angreip	V;PST
fase	fasane	N;DEF;PL
ufatteleg	ufatteleg	ADJ;NDEF;SG
bjørk	bjørka	N;DEF;SG
tyggja	tyggjast	V;NFIN;PASS
plog	plogane	N;DEF;PL
topp	toppane	N;DEF;PL
fylke	fylka	N;DEF;PL
note	notane	N;DEF;PL
ordinær	ordinært	ADJ;NEUT;SG
utstilling	utstillinga	N;DEF;SG
garderobe	garderobane	N;DEF;PL
fasan	fasanane	N;DEF;PL
eddik	eddiken	N;DEF;SG
motorvogn	motorvognene	N;DEF;PL
duld	duldaste	ADJ;SPRL;DEF
djevel	djevelen	N;DEF;SG
batteridriven	batteridrivne	N;DEF;SG+PL
snømann	snømannen	N;DEF;SG
god	beste	ADJ;SPRL;DEF
fylgje	fylgjast	V;NFIN;PASS
kryssarrakett	kryssarrakettar	N;NDEF;PL
vøle	vøler	V;PRS
salvadoranar	salvadoranarane	N;DEF;PL
slovakisk	slovakisken	N;DEF;SG
jaktar	jaktarane	N;DEF;PL
art	artane	N;DEF;PL
minusgrad	minusgrader	N;NDEF;PL
underleg	underleg	ADJ;NDEF;SG
heila	heila	V;IMP
regnfull	regnfullt	ADJ;NEUT;SG
avle	avle	V;IMP
frosk	frosken	N;DEF;SG
burundiar	burundiarane	N;DEF;PL
kombinasjon	kombinasjonar	N;NDEF;PL
byste	bystar	N;NDEF;PL
tenka	tenkte	V;PST
mage	magane	N;DEF;PL
prostituert	prostituert	ADJ;NEUT;SG
atrofi	atrofiar	N;NDEF;PL
reisemål	reisemål	N;NDEF;PL
serleg	serlegare	ADJ;CMPR
stasjon	stasjonar	N;NDEF;PL
varm	varmaste	ADJ;SPRL;DEF
fôrhaustar	fôrhaustarar	N;NDEF;PL
panamanar	panamanarar	N;NDEF;PL
kompleks	komplekst	ADJ;NEUT;SG
unge	ungane	N;DEF;PL
reagens	reagensane	N;DEF;PL
magnetisk	magnetiske	N;DEF;SG+PL
planet	planetar	N;NDEF;PL
oljefelt	oljefelt	N;NDEF;PL
granitt	granitten	N;DEF;SG
katolsk	katolsk	ADJ;NEUT;SG
kostarikan	kostarikanane	N;DEF;PL
hai	haiar	N;NDEF;PL
stor	store	N;DEF;SG+PL
framand	framande	N;DEF;SG+PL
avla	avlar	V;PRS
hete	heten	N;DEF;SG
køyra	køyrast	V;NFIN;PASS
melodi	melodiane	N;DEF;PL
ranar	ranarar	N;NDEF;PL
medisinsk	medisinske	N;DEF;SG+PL
gris	grisen	N;DEF;SG
majestetisk	majestetiske	N;DEF;SG+PL
mikroorganisme	mikroorganismane	N;DEF;PL
trong	trong	ADJ;MASC+FEM
eliminera	eliminerte	V;PST
væske	væska	N;DEF;SG
fyrverkeri	fyrverkeri	N;NDEF;PL
delstat	delstatar	N;NDEF;PL
snakke	snakkast	V;NFIN;PASS
forbløffa	forbløffa	V;PST
møteplass	møteplassen	N;DEF;SG
balltre	balltre	N;NDEF;PL
pla	pla	V;IMP
teskei	teskeier	N;NDEF;PL
tanke	tanka	V;PST
svikar	svikaren	N;DEF;SG
mellomstor	mellomstore	N;DEF;SG+PL
stadion	stadiona	N;DEF;PL
pigment	pigmentet	N;DEF;SG
tygge	togg	V;PST
dårleg	dårlege	N;DEF;SG+PL
kjøp	kjøp	N;NDEF;PL
konse	konse	V;IMP
engel	englar	N;NDEF;PL
subsidie	subsidiane	N;DEF;PL
indisk	indiske	N;DEF;SG+PL
hann	hannar	N;NDEF;PL
god	godt	ADJ;NEUT
kosa	kosast	V;NFIN;PASS
konsentrasjon	konsentrasjonar	N;NDEF;PL
jarnbanestasjon	jarnbanestasjonar	N;NDEF;PL
is	isen	N;DEF;SG
millionær	millionærane	N;DEF;PL
grossist	grossistane	N;DEF;PL
tung	tyngre	ADJ;CMPR
hand	handa	N;DEF;SG
marknad	marknaden	N;DEF;SG
republikk	republikkar	N;NDEF;PL
sykkel	syklane	N;DEF;PL
domene	domenet	N;DEF;SG
tørke	tørkar	N;NDEF;PL
no	noa	N;DEF;PL
revolusjonær	revolusjonæren	N;DEF;SG
lyddempar	lyddemparar	N;NDEF;PL
undergang	undergangar	N;NDEF;PL
vegetabilsk	vegetabilsk	ADJ;NEUT;SG
akselerasjon	akselerasjonar	N;NDEF;PL
bilførar	bilførarar	N;NDEF;PL
smeltepunkt	smeltepunkt	N;NDEF;PL
gardsarbeidar	gardsarbeidarar	N;NDEF;PL
hormon	hormon	N;NDEF;PL
mosambikar	mosambikarane	N;DEF;PL
karakter	karakteren	N;DEF;SG
luksusbil	luksusbilane	N;DEF;PL
burmesar	burmesaren	N;DEF;SG
kabin	kabinen	N;DEF;SG
tåke	tåker	N;NDEF;PL
distrikt	distriktet	N;DEF;SG
sekundær	sekundært	ADJ;NEUT;SG
baryton	barytonar	N;NDEF;PL
rådhus	rådhus	N;NDEF;PL
legering	legeringar	N;NDEF;PL
fiskevær	fiskeværet	N;DEF;SG
omn	omnane	N;DEF;PL
T-bane	T-banane	N;DEF;PL
polsk	polsk	ADJ;NEUT;SG
kommersiell	kommersielt	ADJ;NEUT;SG
trompet	trompetar	N;NDEF;PL
pakke	pakker	N;NDEF;PL
ramme	ramma	N;DEF;SG
smal	smalast	ADJ;SPRL;NDEF
spiss	spissane	N;DEF;PL
filippinar	filippinarar	N;NDEF;PL
tempo	tempoa	N;DEF;PL
sider	sideren	N;DEF;SG
hyperbol	hyperbolen	N;DEF;SG
trena	trenar	V;PRS
kokepunkt	kokepunkt	N;NDEF;PL
optisk	optiske	N;DEF;SG+PL
erfaren	erfarne	N;DEF;SG+PL
salig	saligast	ADJ;SPRL;NDEF
mikroorganisme	mikroorganismar	N;NDEF;PL
bachelorgrad	bachelorgrader	N;NDEF;PL
mongol	mongolar	N;NDEF;PL
quisling	quislingen	N;DEF;SG
gjætar	gjætarar	N;NDEF;PL
løynd	løynde	N;DEF;SG+PL
skyting	skytingar	N;NDEF;PL
utvikling	utviklinga	N;DEF;SG
opphav	opphavet	N;DEF;SG
lygn	lygner	N;NDEF;PL
lampe	lampane	N;DEF;PL
tolk	tolken	N;DEF;SG
lønn	lønnen	N;DEF;SG
definera	definer	V;IMP
forbløffa	forbløffast	V;NFIN;PASS
nauruar	nauruaren	N;DEF;SG
stor	stort	ADJ;NEUT
synga	song	V;PST
verja	verja	V;IMP
svak	svakare	ADJ;CMPR
ung	yngst	ADJ;SPRL;NDEF
egyptar	egyptarar	N;NDEF;PL
sportsbil	sportsbilane	N;DEF;PL
tusj	tusjane	N;DEF;PL
nase	nase	V;IMP
ghanesisk	ghanesiske	N;DEF;SG+PL
trong	trongt	ADJ;NEUT
panaman	panamanen	N;DEF;SG
ørliten	ørsmåe	ADJ;PL
flyplass	flyplassar	N;NDEF;PL
bevisst	bevisst	ADJ;NEUT;SG
tankskip	tankskipet	N;DEF;SG
parkeringsplass	parkeringsplassane	N;DEF;PL
fluid	fluid	N;NDEF;PL
nase	nasar	V;PRS
satellitt	satellittane	N;DEF;PL
bokstavleg	bokstavlegare	ADJ;CMPR
myrk	myrkt	ADJ;NEUT
mutter	mutterar	N;NDEF;PL
sandal	sandalen	N;DEF;SG
duge	dugast	V;NFIN;PASS
år	åra	N;DEF;SG
lagring	lagringane	N;DEF;PL
brukar	brukaren	N;DEF;SG
trollkvinne	trollkvinna	N;DEF;SG
frykt	frykter	N;NDEF;PL
leirdue	leirdua	N;DEF;SG
drikk	drikken	N;DEF;SG
klegg	kleggene	N;DEF;PL
antenne	antenner	N;NDEF;PL
kapasitet	kapasitetane	N;DEF;PL
underart	underartar	N;NDEF;PL
langfredag	langfredagen	N;DEF;SG
gabonar	gabonarar	N;NDEF;PL
spørsmål	spørsmålet	N;DEF;SG
dialekt	dialekter	N;NDEF;PL
fingeravtrykk	fingeravtrykk	N;NDEF;PL
privat	privat	ADJ;NEUT;SG
tips	tips	N;NDEF;PL
older	oldrer	N;NDEF;PL
revolver	revolveren	N;DEF;SG
oksid	oksidet	N;DEF;SG
dronning	dronningane	N;DEF;PL
togolesar	togolesarane	N;DEF;PL
taxisjåfør	taxisjåførar	N;NDEF;PL
song	songar	N;NDEF;PL
hugenott	hugenotten	N;DEF;SG
selja	sel	V;IMP
sesjon	sesjonar	N;NDEF;PL
mørke	mørke	N;NDEF;PL
sveitte	sveittast	V;NFIN;PASS
behalde	beheldt	V;PST
krengja	kreng	V;IMP
skyttargrav	skyttargravene	N;DEF;PL
alpakka	alpakkaen	N;DEF;SG
filosofisk	filosofisk	ADJ;NEUT;SG
boggi	boggien	N;DEF;SG
alder	aldrar	N;NDEF;PL
profesjonell	profesjonelle	N;DEF;SG+PL
fastland	fastland	N;NDEF;PL
symaskin	symaskiner	N;NDEF;PL
rosin	rosina	N;DEF;SG
regntid	regntider	N;NDEF;PL
bakke	bakken	N;DEF;SG
elskar	elskarar	N;NDEF;PL
ungdom	ungdommane	N;DEF;PL
våpen	våpenet	N;DEF;SG
jobb	jobbane	N;DEF;PL
drøyme	drøym	V;IMP
syngja	song	V;PST
spenning	spenningane	N;DEF;PL
taxisjåfør	taxisjåføren	N;DEF;SG
tomme	tommen	N;DEF;SG
and	ender	N;NDEF;PL
malm	malmar	N;NDEF;PL
medlemskort	medlemskortet	N;DEF;SG
brikke	brikker	N;NDEF;PL
åremål	åremålet	N;DEF;SG
panter	panterane	N;DEF;PL
duo	duoen	N;DEF;SG
katekisme	katekismene	N;DEF;PL
seksdel	seksdelane	N;DEF;PL
medlem	medlemene	N;DEF;PL
bokfink	bokfinkane	N;DEF;PL
stele	stel	V;PRS
tidel	tidelane	N;DEF;PL
mygg	myggen	N;DEF;SG
sjukepleiar	sjukepleiarane	N;DEF;PL
halvår	halvår	N;NDEF;PL
pentan	pentanet	N;DEF;SG
imponere	imponerast	V;NFIN;PASS
dikt	diktet	N;DEF;SG
kort	kortast	ADJ;SPRL;NDEF
blome	blomen	N;DEF;SG
libysk	libysk	ADJ;NEUT;SG
arkitektur	arkitekturar	N;NDEF;PL
trålar	trålarane	N;DEF;PL
forvirra	forvirra	V;IMP
ecuadorianar	ecuadorianarar	N;NDEF;PL
sår	såra	N;DEF;PL
samlar	samlarar	N;NDEF;PL
bokfink	bokfinkar	N;NDEF;PL
arkitektonisk	arkitektonisk	ADJ;NEUT;SG
hinne	hinner	N;NDEF;PL
keisemd	keisemda	N;DEF;SG
sjøfugl	sjøfuglar	N;NDEF;PL
løp	løp	N;NDEF;PL
kose	kosar	V;PRS
abdikasjon	abdikasjonen	N;DEF;SG
dølja	døl	V;PRS
klehengjar	klehengjaren	N;DEF;SG
postnummer	postnummeret	N;DEF;SG
gevær	gevær	N;NDEF;PL
grense	grenser	N;NDEF;PL
forbrenningsmotor	forbrenningsmotorane	N;DEF;PL
hugenott	hugenottar	N;NDEF;PL
garasje	garasjane	N;DEF;PL
selja	seljast	V;NFIN;PASS
nazistisk	nazistiske	N;DEF;SG+PL
pose	posane	N;DEF;PL
lag	laga	N;DEF;PL
lakris	lakrisar	N;NDEF;PL
silisium	silisiumet	N;DEF;SG
overhovud	overhovudet	N;DEF;SG
kjøleskap	kjøleskapet	N;DEF;SG
røykja	røykjast	V;NFIN;PASS
fjerna	fjerna	V;PST
ringje	ringjast	V;NFIN;PASS
aristokrat	aristokratar	N;NDEF;PL
topplokk	topplokka	N;DEF;PL
heile	heilar	V;PRS
privatfly	privatflya	N;DEF;PL
teljing	teljingane	N;DEF;PL
kalender	kalendrane	N;DEF;PL
eismal	eismal	ADJ;MASC+FEM
heita	heit	V;IMP
kjøpar	kjøparen	N;DEF;SG
tobakk	tobakkar	N;NDEF;PL
ljos	ljost	ADJ;NEUT
nettside	nettsida	N;DEF;SG
tørr	tørre	N;DEF;SG+PL
skilte	skiltar	V;PRS
afrikansk	afrikansk	ADJ;FEM
vendbar	vendbare	N;DEF;SG+PL
gladiator	gladiatoren	N;DEF;SG
slette	slettene	N;DEF;PL
forsvar	forsvara	N;DEF;PL
åtvaring	åtvaringane	N;DEF;PL
patrulje	patruljane	N;DEF;PL
atomvåpen	atomvåpenet	N;DEF;SG
hastigheit	hastigheitene	N;DEF;PL
flaggermus	flaggermus	N;NDEF;PL
rattstamme	rattstammer	N;NDEF;PL
øydeleggja	øydela	V;PST
mekanisk	mekanisk	ADJ;NEUT;SG
premie	premiane	N;DEF;PL
gudshus	gudshusa	N;DEF;PL
flyfrakt	flyfrakta	N;DEF;SG
kviterussar	kviterussaren	N;DEF;SG
grunnlag	grunnlag	N;NDEF;PL
g-streng	g-strengane	N;DEF;PL
liten	minst	ADJ;SPRL;NDEF
blanding	blandingane	N;DEF;PL
tannlækjar	tannlækjarane	N;DEF;PL
eufemistisk	eufemistisk	ADJ;NEUT;SG
nisje	nisjar	N;NDEF;PL
makedoniar	makedoniarane	N;DEF;PL
automat	automaten	N;DEF;SG
europear	europearar	N;NDEF;PL
elektrisk	elektriske	N;DEF;SG+PL
sludd	sluddet	N;DEF;SG
rik	rikt	ADJ;NEUT;SG
streng	strengare	ADJ;CMPR
høre	hørast	V;NFIN;PASS
innføring	innføringar	N;NDEF;PL
vanskeleg	vanskeleg	ADJ;NDEF;SG
komponent	komponentane	N;DEF;PL
linse	linsa	N;DEF;SG
anneks	anneks	N;NDEF;PL
lærepenge	lærepengen	N;DEF;SG
pingvin	pingvinar	N;NDEF;PL
animasjon	animasjonen	N;DEF;SG
likvid	likvide	N;DEF;SG+PL
bakeri	bakeriet	N;DEF;SG
vekkja	vekkjer	V;PRS
entusiast	entusiastane	N;DEF;PL
oppvask	oppvaska	N;DEF;PL
kjenne	kjennast	V;NFIN;PASS
spent	spente	N;DEF;SG+PL
blekksprut	blekksprutar	N;NDEF;PL
forlag	forlaga	N;DEF;PL
synonymordbok	synonymordbøkene	N;DEF;PL
visittkort	visittkorta	N;DEF;PL
konteinar	konteinarane	N;DEF;PL
søke	søkte	V;PST
symaskin	symaskinene	N;DEF;PL
lang	lengste	ADJ;SPRL;DEF
pass	passet	N;DEF;SG
hard	hardare	ADJ;CMPR
gullalder	gullalderane	N;DEF;PL
trykk	trykk	N;NDEF;PL
elementær	elementært	ADJ;NEUT;SG
retorisk	retorisk	ADJ;NEUT;SG
kvalross	kvalrossar	N;NDEF;PL
auke	aukast	V;NFIN;PASS
stabilitet	stabiliteten	N;DEF;SG
gravemaskin	gravemaskinane	N;DEF;PL
funksjon	funksjonar	N;NDEF;PL
befolkning	befolkningar	N;NDEF;PL
optimisme	optimismen	N;DEF;SG
inflasjon	inflasjonane	N;DEF;PL
rett	rettar	N;NDEF;PL
torsk	torskane	N;DEF;PL
gravemaskin	gravemaskinene	N;DEF;PL
tettbygd	tettbygd	ADJ;NEUT;SG
disippel	disiplane	N;DEF;PL
uvêr	uvêra	N;DEF;PL
minimum	minimuma	N;DEF;PL
ende	endane	N;DEF;PL
oppblåsbar	oppblåsbart	ADJ;NEUT;SG
stolt	stoltaste	ADJ;SPRL;DEF
sofa	sofaer	N;NDEF;PL
hockeykølle	hockeykølla	N;DEF;SG
hekk	hekkar	N;NDEF;PL
ende	enden	N;DEF;SG
kork	korken	N;DEF;SG
masse	massar	N;NDEF;PL
symbolsk	symbolske	N;DEF;SG+PL
sonde	sondane	N;DEF;PL
strekning	strekningar	N;NDEF;PL
stare	starane	N;DEF;PL
aftan	aftanen	N;DEF;SG
ljos	ljosa	N;DEF;PL
påhengsmotor	påhengsmotorane	N;DEF;PL
optimist	optimistane	N;DEF;PL
nicaraguanar	nicaraguanaren	N;DEF;SG
purre	purra	V;PST
suppe	supper	N;NDEF;PL
mikroskopisk	mikroskopiske	N;DEF;SG+PL
eksakt	eksakt	ADJ;NEUT;SG
spesialitet	spesialiteten	N;DEF;SG
hettitt	hettittane	N;DEF;PL
leiar	leiaren	N;DEF;SG
ekspedisjon	ekspedisjonane	N;DEF;PL
orden	ordenen	N;DEF;SG
braut	brauter	N;NDEF;PL
eksempel	eksempel	N;NDEF;PL
hylle	hylla	N;DEF;SG
stereoanlegg	stereoanlegga	N;DEF;PL
fotosyntese	fotosyntesen	N;DEF;SG
ljota	lyt	V;PRS
fjerne	fjerna	V;PST
jiddisch	jiddische	N;DEF;SG+PL
frimurar	frimurarar	N;NDEF;PL
grave	grev	V;PRS
forvirre	forvirre	V;IMP
trene	trenar	V;PRS
klasserom	klasseromma	N;DEF;PL
svane	svanene	N;DEF;PL
duo	duoar	N;NDEF;PL
hopp	hoppa	N;DEF;PL
ferda	ferdast	V;NFIN;PASS
tørst	tørstast	ADJ;SPRL;NDEF
synål	synålene	N;DEF;PL
hals	halsar	N;NDEF;PL
liste	lista	N;DEF;SG
firling	firlingane	N;DEF;PL
dress	dressar	N;NDEF;PL
skyttargrav	skyttargrava	N;DEF;SG
bere	bera	N;DEF;SG
russisk	russisken	N;DEF;SG
heile	heilar	N;NDEF;PL
kloster	kloster	N;NDEF;PL
påskeegg	påskeegga	N;DEF;PL
legg	leggen	N;DEF;SG
glamorøs	glamorøst	ADJ;NEUT;SG
slette	sletta	N;DEF;SG
gribb	gribbar	N;NDEF;PL
separatist	separatisten	N;DEF;SG
tobakk	tobakkane	N;DEF;PL
lilje	lilja	N;DEF;SG
søke	søk	V;IMP
fall	falla	N;DEF;PL
fluidmekanikk	fluidmekanikken	N;DEF;SG
rik	rike	N;DEF;SG+PL
skyttargrav	skyttargraver	N;NDEF;PL
regntid	regntidene	N;DEF;PL
jord	jorda	N;DEF;SG
ære	æra	N;DEF;SG
religion	religionane	N;DEF;PL
skjøna	skjøna	V;IMP
fjern	fjernast	ADJ;SPRL;NDEF
kampanje	kampanjen	N;DEF;SG
skjera	skar	V;PST
rekna	reknast	V;NFIN;PASS
plante	plantar	N;NDEF;PL
følga	følg	V;IMP
undersøke	undersøker	V;PRS
kjøtmeis	kjøtmeiser	N;NDEF;PL
umogleg	umogleg	ADJ;NDEF;SG
bulgarar	bulgararane	N;DEF;PL
rå	rær	N;NDEF;PL
kynikar	kynikarane	N;DEF;PL
sol	solene	N;DEF;PL
køyeseng	køyesenger	N;NDEF;PL
tiår	tiår	N;NDEF;PL
kirgisar	kirgisarar	N;NDEF;PL
teaterstykke	teaterstykke	N;NDEF;PL
publikasjon	publikasjonen	N;DEF;SG
krydder	kryddera	N;DEF;PL
vekke	vekkast	V;NFIN;PASS
tøff	tøffast	ADJ;SPRL;NDEF
onkel	onklar	N;NDEF;PL
katolisisme	katolisismen	N;DEF;SG
tuvalar	tuvalarane	N;DEF;PL
privilegium	privilegia	N;DEF;PL
sitteplass	sitteplassane	N;DEF;PL
ferda	ferda	V;PST
labyrint	labyrinten	N;DEF;SG
katedral	katedralar	N;NDEF;PL
visittkort	visittkort	N;NDEF;PL
farleg	farlegaste	ADJ;SPRL;DEF
andorran	andorranane	N;DEF;PL
tusjpenn	tusjpennar	N;NDEF;PL
stråle	strålen	N;DEF;SG
importør	importørar	N;NDEF;PL
sekk	sekkar	N;NDEF;PL
delikatesse	delikatessa	N;DEF;SG
parlament	parlamentet	N;DEF;SG
afrikansk	afrikanske	N;DEF;SG+PL
økotype	økotypar	N;NDEF;PL
fetter	fetteren	N;DEF;SG
innehalda	innehald	V;IMP
ljuge	ljug	V;IMP
malm	malmen	N;DEF;SG
liste	listene	N;DEF;PL
helt	heltar	N;NDEF;PL
behalda	beheldt	V;PST
plast	plastane	N;DEF;PL
dobbeltseng	dobbeltsenger	N;NDEF;PL
pensjonist	pensjonistane	N;DEF;PL
gladiator	gladiatorane	N;DEF;PL
rekna	rekna	V;IMP
kort	korta	N;DEF;PL
mammut	mammutar	N;NDEF;PL
tongan	tonganar	N;NDEF;PL
vekkje	vekkjast	V;NFIN;PASS
sedimentær	sedimentært	ADJ;NEUT;SG
mørketid	mørketider	N;NDEF;PL
buss	bussen	N;DEF;SG
landkrabbe	landkrabbane	N;DEF;PL
drammensar	drammensaren	N;DEF;SG
dialog	dialogar	N;NDEF;PL
verje	verjene	N;DEF;PL
ønske	ønsker	V;PRS
ljos	ljose	N;DEF;SG+PL
sørafrikan	sørafrikanen	N;DEF;SG
kontekst	konteksten	N;DEF;SG
gjeva	gjev	V;PRS
livslang	livslange	N;DEF;SG+PL
bardage	bardagen	N;DEF;SG
muskel	musklar	N;NDEF;PL
parasitt	parasittane	N;DEF;PL
symbolsk	symbolsk	ADJ;NEUT;SG
formell	formelt	ADJ;NEUT;SG
amfibium	amfibium	N;NDEF;PL
mordvåpen	mordvåpenet	N;DEF;SG
maliar	maliaren	N;DEF;SG
smil	smilar	N;NDEF;PL
sjarmere	sjarmerast	V;NFIN;PASS
puré	pureen	N;DEF;SG
luftforsvar	luftforsvaret	N;DEF;SG
prosedyre	prosedyrar	N;NDEF;PL
svovel	svovelet	N;DEF;SG
pine	pinast	V;NFIN;PASS
fusjon	fusjonane	N;DEF;PL
ål	ålane	N;DEF;PL
kontekst	konteksta	N;DEF;SG
kurdar	kurdaren	N;DEF;SG
intern	interne	N;DEF;SG+PL
innføring	innføringa	N;DEF;SG
vintertid	vintertidene	N;DEF;PL
appell	appellen	N;DEF;SG
overflate	overflater	N;NDEF;PL
lyspære	lyspærene	N;DEF;PL
hårklipp	hårklippar	N;NDEF;PL
inngang	inngangen	N;DEF;SG
framdrift	framdrifta	N;DEF;SG
reptil	reptilet	N;DEF;SG
behalda	behaldast	V;NFIN;PASS
marg	margane	N;DEF;PL
piksel	pikselen	N;DEF;SG
barnebarn	barneborn	N;NDEF;PL
songar	songarane	N;DEF;PL
teologisk	teologiske	N;DEF;SG+PL
jernmalm	jernmalmar	N;NDEF;PL
kontroll	kontrollane	N;DEF;PL
sjø	sjøane	N;DEF;PL
cupfinale	cupfinalen	N;DEF;SG
lys	lys	N;NDEF;PL
hjelpa	hjelper	V;PRS
vollgrav	vollgravene	N;DEF;PL
gøyma	gøym	V;IMP
kokong	kokongar	N;NDEF;PL
utvikla	utviklar	V;PRS
drepe	drep	V;PRS
grunnlag	grunnlaget	N;DEF;SG
bibliotek	biblioteka	N;DEF;PL
individ	individa	N;DEF;PL
børste	børstane	N;DEF;PL
animasjon	animasjonar	N;NDEF;PL
ljos	ljosare	ADJ;CMPR
toalettpapir	toalettpapiret	N;DEF;SG
adventskalender	adventskalendrane	N;DEF;PL
frykteleg	fryktelegaste	ADJ;SPRL;DEF
irakar	irakarane	N;DEF;PL
gnostisisme	gnostisismen	N;DEF;SG
sofa	sofaene	N;DEF;PL
anneks	anneksa	N;DEF;PL
bord	borden	N;DEF;SG
stengel	stenglar	N;NDEF;PL
frimurar	frimuraren	N;DEF;SG
intervju	intervju	N;NDEF;PL
kjøleskap	kjøleskapa	N;DEF;PL
hard	hardast	ADJ;SPRL;NDEF
kabriolet	kabrioletar	N;NDEF;PL
barriere	barrieren	N;DEF;SG
grave	gravast	V;NFIN;PASS
mine	minar	N;NDEF;PL
fargestoff	fargestoffet	N;DEF;SG
mangemillionær	mangemillionærar	N;NDEF;PL
aluminium	aluminiumen	N;DEF;SG
mauritaniar	mauritaniarar	N;NDEF;PL
fullblodshest	fullblodshesten	N;DEF;SG
fengd	fengdene	N;DEF;PL
byrje	byrjar	V;PRS
lukkeleg	lukkelege	N;DEF;SG+PL
tuvalar	tuvalaren	N;DEF;SG
uttrykk	uttrykket	N;DEF;SG
etande	etandet	N;DEF;SG
vårteikn	vårteikna	N;DEF;PL
merke	merka	N;DEF;PL
byrje	bør	V;PRS
besøke	besøkast	V;NFIN;PASS
druide	druiden	N;DEF;SG
asbest	asbesten	N;DEF;SG
snikmordar	snikmordarar	N;NDEF;PL
mannskap	mannskap	N;NDEF;PL
verta	vert	V;IMP
ungdom	ungdomen	N;DEF;SG
gyngestol	gyngestolane	N;DEF;PL
bardage	bardagar	N;NDEF;PL
bumerang	bumerangar	N;NDEF;PL
velje	vel	V;IMP
lesothoar	lesothoarar	N;NDEF;PL
sitte	sit	V;PRS
aspekt	aspektane	N;DEF;PL
skribent	skribentar	N;NDEF;PL
brudgom	brudgommar	N;NDEF;PL
mangel	manglane	N;DEF;PL
last	lastar	N;NDEF;PL
gjeva	gjevast	V;NFIN;PASS
kokebok	kokeboka	N;DEF;SG
colombianar	colombianarar	N;NDEF;PL
stjerne	stjerna	N;DEF;SG
kledehengjar	kledehengjaren	N;DEF;SG
mjølk	mjølka	N;DEF;SG
svanger	svangre	N;DEF;SG+PL
kvile	kvil	V;IMP
brunbjørn	brunbjørnar	N;NDEF;PL
bumerang	bumerangane	N;DEF;PL
lagune	lagunene	N;DEF;PL
medlem	medlemmene	N;DEF;PL
suppe	suppa	N;DEF;SG
invadere	invader	V;IMP
filosof	filosofane	N;DEF;PL
tøff	tøffaste	ADJ;SPRL;DEF
spedbarn	spedbarn	N;NDEF;PL
vott	vottane	N;DEF;PL
program	programma	N;DEF;PL
klippe	klippene	N;DEF;PL
nerve	nervar	N;NDEF;PL
opne	opne	V;IMP
lukkeleg	lukkelegare	ADJ;CMPR
armbrøst	armbrøsten	N;DEF;SG
plast	plastar	N;NDEF;PL
songar	songarar	N;NDEF;PL
korporal	korporalar	N;NDEF;PL
delta	deltek	V;PRS
aud	aude	N;DEF;SG+PL
omgjevnad	omgjevnadar	N;NDEF;PL
massakre	massakren	N;DEF;SG
barnebarn	barneborna	N;DEF;PL
potet	potetene	N;DEF;PL
styrka	styrker	V;PRS
heita	het	V;PST
stele	stel	V;IMP
dialog	dialogane	N;DEF;PL
vandre	vandre	V;IMP
nymfe	nymfa	N;DEF;SG
farleg	farlegare	ADJ;CMPR
domstol	domstolen	N;DEF;SG
tann	tanna	N;DEF;SG
veranda	verandaen	N;DEF;SG
storm	stormen	N;DEF;SG
jernbane	jernbanane	N;DEF;PL
rekna	reknar	V;PRS
hærførar	hærførarar	N;NDEF;PL
angra	angra	V;IMP
klasse	klassa	N;DEF;SG
økosystem	økosystema	N;DEF;PL
ljos	ljosast	ADJ;SPRL;NDEF
ende	endast	V;NFIN;PASS
svanger	svangert	ADJ;NEUT;SG
missil	missil	N;NDEF;PL
ubalanse	ubalansane	N;DEF;PL
namibiar	namibiarane	N;DEF;PL
lampeskjerm	lampeskjermane	N;DEF;PL
song	songen	N;DEF;SG
granmeis	granmeisene	N;DEF;PL
sveitsisk	sveitsisk	ADJ;NEUT;SG
prinsipiell	prinsipielt	ADJ;NEUT;SG
ungarsk	ungarsken	N;DEF;SG
lagnad	lagnadane	N;DEF;PL
sveitte	sveittar	V;PRS
handtering	handteringane	N;DEF;PL
mørke	mørket	N;DEF;SG
venta	venta	V;IMP
arkeolog	arkeologane	N;DEF;PL
offiser	offiserane	N;DEF;PL
djiboutiar	djiboutiarane	N;DEF;PL
farleg	farleg	ADJ;NDEF;SG
ryggsekk	ryggsekker	N;NDEF;PL
landskap	landskapa	N;DEF;PL
søsken	søsken	N;NDEF;PL
heimebrent	heimebrenten	N;DEF;SG
mistanke	mistanken	N;DEF;SG
butan	butanen	N;DEF;SG
humoristisk	humoristisk	ADJ;NEUT;SG
sveitsar	sveitsaren	N;DEF;SG
firling	firlingen	N;DEF;SG
ambassade	ambassadane	N;DEF;PL
arabisk	arabisk	ADJ;NEUT;SG
klehengar	klehengarane	N;DEF;PL
kynikar	kynikaren	N;DEF;SG
skjøne	skjøna	V;PST
konsentrere	konsentrerte	V;PST
verne	verna	V;PST
kull	kullet	N;DEF;SG
abdikasjon	abdikasjonane	N;DEF;PL
demens	demensen	N;DEF;SG
forhandling	forhandlingane	N;DEF;PL
indonesisk	indonesiske	N;DEF;SG+PL
forhandling	forhandlinga	N;DEF;SG
eske	esker	N;NDEF;PL
umogeleg	umogelegaste	ADJ;SPRL;DEF
nymfoman	nymfomant	ADJ;NEUT;SG
revebjølle	revebjøller	N;NDEF;PL
ressurs	ressursen	N;DEF;SG
atomvåpen	atomvåpen	N;NDEF;PL
forum	forumet	N;DEF;SG
kyss	kyss	N;NDEF;PL
malt	maltet	N;DEF;SG
gjeva	gjev	V;IMP
tørr	tørrast	ADJ;SPRL;NDEF
grave	grov	V;PST
symaskin	symaskinar	N;NDEF;PL
maori	maorien	N;DEF;SG
kjønnshår	kjønnshåra	N;DEF;PL
fetter	fetrane	N;DEF;PL
skjøne	skjøn	V;IMP
postnummer	postnummer	N;NDEF;PL
ringa	ring	V;IMP
medlemskort	medlemskort	N;NDEF;PL
kjeks	kjeksa	N;DEF;PL
himmel	himmelar	N;NDEF;PL
overtyda	overtyder	V;PRS
emalje	emaljar	N;NDEF;PL
slå	slåast	V;NFIN;PASS
sårbar	sårbart	ADJ;NEUT;SG
kose	kose	V;IMP
spøkja	spøkjer	V;PRS
molekylær	molekylært	ADJ;NEUT;SG
populær	populære	N;DEF;SG+PL
matematisk	matematiske	N;DEF;SG+PL
kasakhstanar	kasakhstanarar	N;NDEF;PL
tam	tamme	N;DEF;SG+PL
identitet	identitetane	N;DEF;PL
påskedag	påskedagar	N;NDEF;PL
subtropisk	subtropisk	ADJ;NEUT;SG
bekk	bekkane	N;DEF;PL
ringje	ring	V;IMP
symja	sym	V;PRS
umogeleg	umogelegast	ADJ;SPRL;NDEF
sjø	sjøar	N;NDEF;PL
sumar	sumaren	N;DEF;SG
nikkel	nikkelen	N;DEF;SG
sketsj	sketsjen	N;DEF;SG
invadere	invaderast	V;NFIN;PASS
anarki	anarkia	N;DEF;PL
skinn	skinna	N;DEF;PL
strategi	strategiane	N;DEF;PL
køntri	køntrien	N;DEF;SG
typisk	typisk	ADJ;NEUT;SG
aggresjon	aggresjonar	N;NDEF;PL
aspekt	aspekten	N;DEF;SG
tortur	torturen	N;DEF;SG
elfenbeinstårn	elfenbeinstårn	N;NDEF;PL
fossefall	fossefalla	N;DEF;PL
ønske	ønsket	N;DEF;SG
flaskehals	flaskehalsane	N;DEF;PL
middel	middelet	N;DEF;SG
byggjar	byggjarane	N;DEF;PL
lærepenge	lærepengane	N;DEF;PL
purre	purrast	V;NFIN;PASS
tendens	tendensane	N;DEF;PL
klubb	klubben	N;DEF;SG
jekk	jekkar	N;NDEF;PL
skjegg	skjegget	N;DEF;SG
likvid	likvid	ADJ;NEUT;SG
maliar	maliarar	N;NDEF;PL
blasfemisk	blasfemiske	N;DEF;SG+PL
ikon	ikonen	N;DEF;SG
seksualitet	seksualiteten	N;DEF;SG
bolivian	bolivianar	N;NDEF;PL
infeksiøs	infeksiøse	N;DEF;SG+PL
syn	synene	N;DEF;PL
asjett	asjetten	N;DEF;SG
tenkje	tenkjast	V;NFIN;PASS
hestekraft	hestekrafter	N;NDEF;PL
utval	utvalet	N;DEF;SG
medlem	medlemen	N;DEF;SG
vaskemaskin	vaskemaskinar	N;NDEF;PL
sement	sementar	N;NDEF;PL
tennisbane	tennisbanar	N;NDEF;PL
mudderflate	mudderflatene	N;DEF;PL
fotavtrykk	fotavtrykka	N;DEF;PL
grense	grensa	N;DEF;SG
tørste	tørsten	N;DEF;SG
konsentrere	konsentrerer	V;PRS
fiber	fibrane	N;DEF;PL
orden	ordenar	N;NDEF;PL
vindtunnel	vindtunnelen	N;DEF;SG
pass	passa	N;DEF;PL
snikmordar	snikmordaren	N;DEF;SG
kaldbrann	kaldbrannen	N;DEF;SG
fugleinfluensa	fugleinfluensaen	N;DEF;SG
radiobil	radiobilar	N;NDEF;PL
grei	greie	N;DEF;SG+PL
fjern	fjernare	ADJ;CMPR
dans	dansane	N;DEF;PL
symptom	symptomet	N;DEF;SG
spontanabort	spontanaborten	N;DEF;SG
gipsbandasje	gipsbandasjane	N;DEF;PL
linse	linser	N;NDEF;PL
notat	notata	N;DEF;PL
bibliofil	bibliofilen	N;DEF;SG
flamsk	flamsk	ADJ;NEUT;SG
kivi	kiviar	N;NDEF;PL
parakitt	parakitten	N;DEF;SG
appell	appellane	N;DEF;PL
setning	setningar	N;NDEF;PL
roman	romanane	N;DEF;PL
skugga	skuggast	V;NFIN;PASS
sovepose	soveposen	N;DEF;PL
skugga	skugga	V;PST
typisk	typiske	N;DEF;SG+PL
proporsjonal	proporsjonale	N;DEF;SG+PL
følgja	følgjast	V;NFIN;PASS
avgjera	avgjerast	V;NFIN;PASS
ekvator	ekvatoren	N;DEF;SG
folkestyrt	folkestyrte	N;DEF;SG+PL
katedral	katedralane	N;DEF;PL
edderkopp	edderkoppane	N;DEF;PL
spesialitet	spesialitetar	N;NDEF;PL
gjere	gjorde	V;PST
ryggsekk	ryggsekkar	N;NDEF;PL
sykkelsete	sykkelsete	N;NDEF;PL
løk	løkar	N;NDEF;PL
pinse	pinser	N;NDEF;PL
slektskap	slektskapane	N;DEF;PL
grei	greiast	ADJ;SPRL;NDEF
tredjedel	tredjedelar	N;NDEF;PL
gravemaskin	gravemaskinar	N;NDEF;PL
eplepai	eplepaiane	N;DEF;PL
sveitsar	sveitsarar	N;NDEF;PL
konsis	konsist	ADJ;NEUT;SG
austleg	austlegare	ADJ;CMPR
snøbrille	snøbrillene	N;DEF;PL
protestantisk	protestantisk	ADJ;NEUT;SG
gevær	geværa	N;DEF;PL
duft	dufter	N;NDEF;PL
seia	sei	V;IMP
sement	sementen	N;DEF;SG
steinsprang	steinsprang	N;NDEF;PL
bjode	baud	V;PST
forbetre	forbetre	V;IMP
park	parken	N;DEF;SG
dobbeltseng	dobbeltsengene	N;DEF;PL
eksempel	eksempla	N;DEF;PL
streng	strengt	ADJ;NEUT;SG
klon	klonar	N;NDEF;PL
søsken	søskena	N;DEF;PL
bere	berast	V;NFIN;PASS
spele	spele	V;IMP
turist	turistane	N;DEF;PL
pennesplitt	pennesplittane	N;DEF;PL
horoskop	horoskop	N;NDEF;PL
barnebarn	barnebarna	N;DEF;PL
svenske	svensken	N;DEF;SG
kiwi	kiwiane	N;DEF;PL
bølgjelengd	bølgjelengda	N;DEF;SG
anarkist	anarkisten	N;DEF;SG
sjåar	sjåarar	N;NDEF;PL
garasje	garasjar	N;NDEF;PL
gyngestol	gyngestolar	N;NDEF;PL
lang	langt	ADJ;NEUT
liggje	ligg	V;IMP
klesplagg	klesplagg	N;NDEF;PL
rygg	ryggar	N;NDEF;PL
orsaking	orsakingane	N;DEF;PL
stat	statane	N;DEF;PL
sjukdom	sjukdomar	N;NDEF;PL
hard	hardt	ADJ;NEUT
helle	heller	N;NDEF;PL
påverka	påverka	V;IMP
tredemølle	tredemøllene	N;DEF;PL
pall	pallar	N;NDEF;PL
bakeri	bakeria	N;DEF;PL
profil	profilar	N;NDEF;PL
venteliste	ventelistene	N;DEF;PL
helikopter	helikopteret	N;DEF;SG
vulkan	vulkanar	N;NDEF;PL
hydrogen	hydrogenet	N;DEF;SG
målestokk	målestokkar	N;NDEF;PL
vanuatuar	vanuatuarar	N;NDEF;PL
skilt	skilt	N;NDEF;PL
flykaprar	flykaprarar	N;NDEF;PL
sjukdom	sjukdomen	N;DEF;SG
ringa	ringast	V;NFIN;PASS
modifikasjon	modifikasjonen	N;DEF;SG
slå	slår	V;PRS;ACT
terrasse	terrassen	N;DEF;SG
kvartal	kvartal	N;NDEF;PL
nicaraguanar	nicaraguanarane	N;DEF;PL
andreplass	andreplassar	N;NDEF;PL
styresmakt	styresmaktene	N;DEF;PL
tynn	tynne	N;DEF;SG+PL
løk	løkane	N;DEF;PL
lærebok	lærebøker	N;NDEF;PL
sitteplass	sitteplassar	N;NDEF;PL
vernehjelm	vernehjelmar	N;NDEF;PL
sentral	sentralar	N;NDEF;PL
vennleg	vennlege	N;DEF;SG+PL
dataspel	dataspela	N;DEF;PL
guatemalanar	guatemalanarar	N;NDEF;PL
spartansk	spartanske	N;DEF;SG+PL
disk	disken	N;DEF;SG
kinesar	kinesaren	N;DEF;SG
ask	askar	N;NDEF;PL
bølgjelengd	bølgjelengder	N;NDEF;PL
sylv	sylvet	N;DEF;SG
himmelseng	himmelsenger	N;NDEF;PL
forklaring	forklaringar	N;NDEF;PL
stad	stada	N;DEF;PL
flyselskap	flyselskapa	N;DEF;PL
utforming	utformingane	N;DEF;PL
knyttneve	knyttnevar	N;NDEF;PL
halskjede	halskjedene	N;DEF;PL
gå	gådde	V;PST
selja	selde	V;PST
potensiell	potensielt	ADJ;NEUT;SG
måtta	måtte	V;PST
prestisje	prestisjen	N;DEF;SG
fullmåne	fullmånen	N;DEF;SG
fastland	fastlandet	N;DEF;SG
kjevle	kjevlar	V;PRS
blome	bloma	V;PST
krets	kretsane	N;DEF;PL
kort	kortaste	ADJ;SPRL;DEF
bokstaveleg	bokstavelegaste	ADJ;SPRL;DEF
bestefar	bestefaren	N;DEF;SG
umoden	umode	ADJ;NEUT;SG
erosjon	erosjonar	N;NDEF;PL
rabarbra	rabarbraene	N;DEF;PL
altar	altar	N;NDEF;PL
maske	maska	N;DEF;SG
kurdar	kurdarane	N;DEF;PL
innehalda	inneheld	V;PRS
g-streng	g-strengen	N;DEF;SG
maskinvare	maskinvara	N;DEF;SG
skilnad	skilnader	N;NDEF;PL
radiobil	radiobilane	N;DEF;PL
spekter	spekter	N;NDEF;PL
tape	tapa	V;PST
vekse	veks	V;IMP
desimal	desimalen	N;DEF;SG
zoologi	zoologien	N;DEF;SG
baksete	baksete	N;NDEF;PL
mexicanar	mexicanaren	N;DEF;SG
edel	edlast	ADJ;SPRL;NDEF
dobbelthake	dobbelthakene	N;DEF;PL
verje	verja	N;DEF;SG
meteorologi	meteorologien	N;DEF;SG
last	lasta	N;DEF;SG
innkast	innkasta	N;DEF;PL
tredjedel	tredjedelane	N;DEF;PL
gjere	gjer	V;IMP
mottakar	mottakarane	N;DEF;PL
moped	mopedar	N;NDEF;PL
armbrøst	armbrøstane	N;DEF;PL
brennbar	brennbart	ADJ;NEUT;SG
tynn	tynnare	ADJ;CMPR
bokstaveleg	bokstavelegare	ADJ;CMPR
overhovud	overhovuda	N;DEF;PL
mord	mord	N;NDEF;PL
rik	rikaste	ADJ;SPRL;DEF
besøk	besøka	N;DEF;PL
masse	massen	N;DEF;SG
molekyl	molekyla	N;DEF;PL
dansar	dansarane	N;DEF;PL
funksjon	funksjonen	N;DEF;SG
gallar	gallarane	N;DEF;PL
følga	følgde	V;PST
aprikos	aprikosane	N;DEF;PL
snøscooter	snøscooteren	N;DEF;SG
meksikanar	meksikanarar	N;NDEF;PL
trålar	trålaren	N;DEF;SG
stilig	stiligaste	ADJ;SPRL;DEF
sår	sår	N;NDEF;PL
rattstamme	rattstammen	N;DEF;SG
tortur	torturar	N;NDEF;PL
geit	geiter	N;NDEF;PL
kult	kultar	N;NDEF;PL
senegalesar	senegalesarar	N;NDEF;PL
hals	halsane	N;DEF;PL
søke	søkast	V;NFIN;PASS
steinsprang	steinspranga	N;DEF;PL
rekne	reknar	V;PRS
spade	spaden	N;DEF;SG
notat	notatet	N;DEF;SG
tynn	tynnast	ADJ;SPRL;NDEF
kort	kort	ADJ;NEUT;SG
kabinett	kabinett	N;NDEF;PL
arkaisk	arkaiske	N;DEF;SG+PL
heissjakt	heissjakter	N;NDEF;PL
kvitlauk	kvitlaukane	N;DEF;PL
sår	såre	N;DEF;SG+PL
libysk	libyske	N;DEF;SG+PL
keisemd	keisemdene	N;DEF;PL
gravemaskin	gravemaskiner	N;NDEF;PL
hastigheit	hastigheiter	N;NDEF;PL
medlemskort	medlemskorta	N;DEF;PL
rådgjevar	rådgjevarane	N;DEF;PL
umyndig	umyndig	ADJ;NEUT;SG
sukker	sukkeret	N;DEF;SG
katedral	katedralen	N;DEF;SG
malaysiar	malaysiarar	N;NDEF;PL
klokkar	klokkaren	N;DEF;SG
fugleinfluensa	fugleinfluensaane	N;DEF;PL
uruguayan	uruguayanen	N;DEF;SG
taka	tek	V;PRS
nordamerikanar	nordamerikanarane	N;DEF;PL
martyr	martyrar	N;NDEF;PL
nordamerikanar	nordamerikanaren	N;DEF;SG
krona	kronar	V;PRS
kjeks	kjeks	N;NDEF;PL
vesteuropeisk	vesteuropeisk	ADJ;NDEF;NEUT;SG
motor	motorane	N;DEF;PL
haust	haustar	N;NDEF;PL
ambassade	ambassaden	N;DEF;SG
næringsstoff	næringsstoffa	N;DEF;PL
vekke	vekker	V;PRS
bygge	bygger	V;PRS
farge	fargane	N;DEF;PL
radioaktiv	radioaktive	N;DEF;SG+PL
tøff	tøffare	ADJ;CMPR
engelsk	engelskare	ADJ;CMPR
astrologisk	astrologiske	N;DEF;SG+PL
soge	soga	N;DEF;SG
rekne	reknast	V;NFIN;PASS
kledehengjar	kledehengjarane	N;DEF;PL
klisjé	klisjear	N;NDEF;PL
meteoritt	meteorittar	N;NDEF;PL
heile	heilast	V;NFIN;PASS
alkyn	alkyna	N;DEF;PL
fråsegn	fråsegnene	N;DEF;PL
metafor	metaforar	N;NDEF;PL
flykte	flykte	V;IMP
kjevle	kjevlast	V;NFIN;PASS
søppel	søppelet	N;DEF;SG
trilling	trillingane	N;DEF;PL
bakke	bakkar	N;NDEF;PL
stasjonsvogn	stasjonsvogna	N;DEF;SG
storby	storbyar	N;NDEF;PL
sivil	sivilt	ADJ;NEUT
ærleg	ærlegare	ADJ;CMPR
gruvearbeidar	gruvearbeidaren	N;DEF;SG
sukker	sukkera	N;DEF;PL
muskel	musklane	N;DEF;PL
vase	vasane	N;DEF;PL
heissjakt	heissjaktene	N;DEF;PL
rull	rullen	N;DEF;SG
lang	lange	N;DEF;SG+PL
diplomat	diplomatar	N;NDEF;PL
kivi	kivien	N;DEF;SG
visepresident	visepresidentane	N;DEF;PL
papegøye	papegøyane	N;DEF;PL
styrka	styrk	V;IMP
sjuk	sjuke	N;DEF;SG+PL
shorts	shortsane	N;DEF;PL
vaffel	vaflane	N;DEF;PL
rabarbra	rabarbraar	N;NDEF;PL
rasere	raserte	V;PST
segl	seglet	N;DEF;SG
fregatt	fregattane	N;DEF;PL
bestilling	bestillinga	N;DEF;SG
vogn	vogner	N;NDEF;PL
trafikk	trafikken	N;DEF;SG
lilje	liljer	N;NDEF;PL
retorikk	retorikken	N;DEF;SG
eske	eskene	N;DEF;PL
farleg	farlege	N;DEF;SG+PL
mørke	mørkte	V;PST
rulett	rulettar	N;NDEF;PL
snøfnugg	snøfnugga	N;DEF;PL
eismal	eismalt	ADJ;NEUT
optimist	optimisten	N;DEF;SG
tynn	tynnaste	ADJ;SPRL;DEF
pine	pin	V;IMP
sniglehus	sniglehus	N;NDEF;PL
jiddisch	jiddischen	N;DEF;SG
purre	purrar	N;NDEF;PL
tabell	tabellar	N;NDEF;PL
par	paret	N;DEF;SG
kasino	kasinoet	N;DEF;SG
kivi	kiviane	N;DEF;PL
destruksjon	destruksjonar	N;NDEF;PL
opprørar	opprørarar	N;NDEF;PL
overtyde	overtydast	V;NFIN;PASS
elektrisk	elektrisk	ADJ;NEUT;SG
torsk	torsken	N;DEF;SG
skjørt	skjørtet	N;DEF;SG
øydar	øydarane	N;DEF;PL
utvikla	utvikla	V;IMP
utanriksminister	utanriksministerane	N;DEF;PL
vekkja	vekk	V;IMP
samleie	samleie	N;NDEF;PL
zoomobjektiv	zoomobjektiv	N;NDEF;PL
hydrokarbon	hydrokarbon	N;NDEF;PL
globus	globusane	N;DEF;PL
primær	primære	N;DEF;SG+PL
døy	døyast	V;NFIN;PASS
nyhende	nyhende	N;NDEF;PL
nasjonaldag	nasjonaldagen	N;DEF;SG
påhengsmotor	påhengsmotorar	N;NDEF;PL
tjukk	tjukkaste	ADJ;SPRL;DEF
nydeleg	nydelege	N;DEF;SG+PL
åtvare	åtvarast	V;NFIN;PASS
bysantinar	bysantinaren	N;DEF;SG
eksplodera	eksploderast	V;NFIN;PASS
skyld	skylda	N;DEF;SG
heite	het	V;PST
etanol	etanolen	N;DEF;SG
kongle	konglene	N;DEF;PL
gruvearbeidar	gruvearbeidarar	N;NDEF;PL
safari	safariane	N;DEF;PL
landkrabbe	landkrabber	N;NDEF;PL
landssvikar	landssvikaren	N;DEF;SG
nitrogen	nitrogenet	N;DEF;SG
boggi	boggiar	N;NDEF;PL
populær	populært	ADJ;NEUT
aktsam	aktsam	ADJ;MASC+FEM
snøbrett	snøbrettet	N;DEF;SG
samanlikne	samanliknast	V;NFIN;PASS
epletre	epletra	N;DEF;PL
vadefugl	vadefuglane	N;DEF;PL
tyggje	tyggjast	V;NFIN;PASS
mangan	manganet	N;DEF;SG
åtvare	åtvare	V;IMP
hestehale	hestehalen	N;DEF;SG
overbefolkning	overbefolkninga	N;DEF;SG
nordleg	nordlege	N;DEF;SG+PL
vanskeleg	vanskelege	N;DEF;SG+PL
anarkist	anarkistane	N;DEF;PL
aluminiumsfolie	aluminiumsfoliane	N;DEF;PL
einast	einast	V;IMP
samarbeid	samarbeid	N;NDEF;PL
blåmeis	blåmeiser	N;NDEF;PL
googla	googlar	V;PRS
kort	kortare	ADJ;CMPR
rakett	rakettar	N;NDEF;PL
vesteuropeisk	vesteuropeiske	N;DEF;SG+PL
psykiatrisk	psykiatrisk	ADJ;NEUT;SG
teaterstykke	teaterstykka	N;DEF;PL
dørslag	dørslag	N;NDEF;PL
spele	spelar	V;PRS
sketsj	sketsjane	N;DEF;PL
alkyn	alkyn	N;NDEF;PL
anarkist	anarkistar	N;NDEF;PL
meteoritt	meteoritten	N;DEF;SG
forsvar	forsvar	N;NDEF;PL
sørleg	sørleg	ADJ;NDEF;SG
dekkje	dekkjer	V;PRS
flaggermus	flaggermyser	N;NDEF;PL
uniform	uniformer	N;NDEF;PL
trollmann	trollmannen	N;DEF;SG
altar	altara	N;DEF;PL
liten	liten	ADJ;MASC
kjendis	kjendisen	N;DEF;SG
vits	vitsane	N;DEF;PL
strekk	strekkar	N;NDEF;PL
turist	turistar	N;NDEF;PL
krone	krona	V;PST
landskap	landskapet	N;DEF;SG
svigerinne	svigerinnene	N;DEF;PL
fjerdedel	fjerdedelane	N;DEF;PL
køyretøy	køyretøy	N;NDEF;PL
modifikasjon	modifikasjonane	N;DEF;PL
dørklokke	dørklokker	N;NDEF;PL
konteinar	konteinarar	N;NDEF;PL
diplomati	diplomatiet	N;DEF;SG
notatbok	notatbøker	N;NDEF;PL
vitne	vitne	N;NDEF;PL
krone	krone	V;IMP
næringsrik	næringsrikt	ADJ;NEUT;SG
øydeleggja	øydelegg	V;IMP
klehengjar	klehengjarar	N;NDEF;PL
slektskap	slektskapet	N;DEF;SG
roman	romanar	N;NDEF;PL
makaber	makabert	ADJ;NEUT;SG
lakris	lakris	N;NDEF;PL
refreng	refreng	N;NDEF;PL
bergart	bergarta	N;DEF;SG
bere	berer	N;NDEF;PL
emalje	emaljen	N;DEF;SG
lommetjuv	lommetjuven	N;DEF;SG
natrium	natriumet	N;DEF;SG
aprikos	aprikosen	N;DEF;SG
fingertupp	fingertuppen	N;DEF;SG
øvst	øvste	ADJ;DEF
plastfolie	plastfolien	N;DEF;SG
konspirasjonsteori	konspirasjonsteoriar	N;NDEF;PL
