discutir	discuteixis	V;SBJV;SG;2;PRS
remeiar	remeiàrem	V;PFV;IND;PL;1;PST
completar	completàrem	V;PFV;IND;PL;1;PST
deure	deurien	V;COND;PL;3
llegir	llegí	V;PFV;IND;SG;3;PST
eructar	eructà	V;PFV;IND;SG;3;PST
reclamar	reclamareu	V;IND;PL;2;FUT
disculpar	disculparíeu	V;COND;PL;2
zigzaguejar	zigzaguegin	V;SBJV;PL;3;PRS
explotar	explotar	V;NFIN
simpatitzar	simpatitzares	V;PFV;IND;SG;2;PST
disculpar	disculpí	V;PFV;IND;SG;1;PST
agrupar	agrupàrem	V;PFV;IND;PL;1;PST
fotre	fotés	V;SBJV;SG;3;PST
sancionar	sancionés	V;SBJV;SG;1;PST
bullir	bulliran	V;IND;PL;3;FUT
ulular	ululaves	V;IPFV;IND;SG;2;PST
agusar	agusaràs	V;IND;SG;2;FUT
ulular	ululàreu	V;PFV;IND;PL;2;PST
escurar	escurareu	V;IND;PL;2;FUT
enutjar	enutgi	V;SBJV;SG;3;PRS
desbordar	desbordeu	V;SBJV;PL;2;PRS
empaquetar	empaquetessin	V;SBJV;PL;3;PST
esmorzar	esmorzaríem	V;COND;PL;1
consistir	consisteixin	V;IMP;PL;3;POS
definir	defineixi	V;SBJV;SG;3;PRS
motivar	motivés	V;SBJV;SG;1;PST
roncar	ronquem	V;IND;PL;1;PRS
insultar	insultar	V;NFIN
repartir	repartís	V;SBJV;SG;1;PST
excretar	excretaríem	V;COND;PL;1
deure	degueres	V;PFV;IND;SG;2;PST
internacionalitzar	internacionalitzava	V;IPFV;IND;SG;3;PST
catalitzar	catalitzàrem	V;PFV;IND;PL;1;PST
rodar	rodaran	V;IND;PL;3;FUT
llogar	llogarem	V;IND;PL;1;FUT
corroir	corroeixo	V;IND;SG;1;PRS
respirar	respireu	V;IMP;PL;2;POS
manipular	manipulí	V;PFV;IND;SG;1;PST
intensificar	intensificaries	V;COND;SG;2
denunciar	denunciaria	V;COND;SG;1
lamentar	lamentaria	V;COND;SG;1
descendir	descendiran	V;IND;PL;3;FUT
vigilar	vigilo	V;IND;SG;1;PRS
arrapar	arraparé	V;IND;SG;1;FUT
eixugar	eixugaria	V;COND;SG;3
subhastar	subhasten	V;IND;PL;3;PRS
mortificar	mortificarem	V;IND;PL;1;FUT
ballar	ballaren	V;PFV;IND;PL;3;PST
abdicar	abdiquí	V;PFV;IND;SG;1;PST
alfabetitzar	alfabetitzi	V;IMP;SG;3;POS
observar	observessis	V;SBJV;SG;2;PST
enutjar	enutjarien	V;COND;PL;3
desitjar	desitja	V;IMP;SG;2;POS
ubicar	ubicareu	V;IND;PL;2;FUT
tirotejar	tirotejàrem	V;PFV;IND;PL;1;PST
gesticular	gesticularem	V;IND;PL;1;FUT
desbordar	desbordem	V;IMP;PL;1;POS
mocar-se	moquem	V;IND;PL;1;PRS
desar	desà	V;PFV;IND;SG;3;PST
frenar	frenàvem	V;IPFV;IND;PL;1;PST
saludar	saludés	V;SBJV;SG;3;PST
contravenir	contravinguérem	V;PFV;IND;PL;1;PST
arrencar	arrenqui	V;IMP;SG;3;POS
sopar	sopava	V;IPFV;IND;SG;3;PST
entregar	entregava	V;IPFV;IND;SG;3;PST
sexar	sexin	V;SBJV;PL;3;PRS
demolir	demoliu	V;SBJV;PL;2;PRS
coexistir	coexistíem	V;IPFV;IND;PL;1;PST
intervenir	intervinguis	V;SBJV;SG;2;PRS
habilitar	habilitava	V;IPFV;IND;SG;3;PST
destorbar	destorbaràs	V;IND;SG;2;FUT
seleccionar	seleccionaves	V;IPFV;IND;SG;2;PST
respondre	respongueren	V;PFV;IND;PL;3;PST
néixer	naixé	V;PFV;IND;SG;3;PST
esternudar	esternudaves	V;IPFV;IND;SG;2;PST
forjar	forgessis	V;SBJV;SG;2;PST
influir	influeixo	V;IND;SG;1;PRS
plantar	planti	V;SBJV;SG;3;PRS
aportar	aportin	V;SBJV;PL;3;PRS
enfonsar	enfonsi	V;SBJV;SG;3;PRS
profetitzar	profetitzarien	V;COND;PL;3
seleccionar	seleccionessin	V;SBJV;PL;3;PST
finir	finissis	V;SBJV;SG;2;PST
clamar	clamarem	V;IND;PL;1;FUT
enxampar	enxampàreu	V;PFV;IND;PL;2;PST
exhumar	exhumaríem	V;COND;PL;1
pujar	pugessis	V;SBJV;SG;2;PST
dogmatitzar	dogmatitza	V;IND;SG;3;PRS
mitigar	mitiga	V;IND;SG;3;PRS
internacionalitzar	internacionalitzin	V;IMP;PL;3;POS
tossir	tossiren	V;PFV;IND;PL;3;PST
orinar	orinéssim	V;SBJV;PL;1;PST
quedar-se	quedava	V;IPFV;IND;SG;3;PST
diversificar	diversificarien	V;COND;PL;3
sentir	sentís	V;SBJV;SG;1;PST
protagonitzar	protagonitzem	V;SBJV;PL;1;PRS
afaitar	afaitessin	V;SBJV;PL;3;PST
mocar	mocava	V;IPFV;IND;SG;1;PST
dimeritzar	dimeritzareu	V;IND;PL;2;FUT
aparèixer	apareixem	V;IND;PL;1;PRS
desobeir	desobeíreu	V;PFV;IND;PL;2;PST
afeblir	afeblíssim	V;SBJV;PL;1;PST
afaitar	afaitar	V;NFIN
estigmatitzar	estigmatitzessin	V;SBJV;PL;3;PST
distingir	distingir	V;NFIN
col·leccionar	col·leccionaven	V;IPFV;IND;PL;3;PST
podar	podem	V;IMP;PL;1;POS
trenar	treni	V;IMP;SG;3;POS
raonar	raonem	V;IMP;PL;1;POS
costar	costessis	V;SBJV;SG;2;PST
governar	governin	V;SBJV;PL;3;PRS
capitular	capitulareu	V;IND;PL;2;FUT
oposar	oposi	V;SBJV;SG;3;PRS
desenterrar	desenterréssim	V;SBJV;PL;1;PST
immobilitzar	immobilitzarem	V;IND;PL;1;FUT
labialitzar	labialitzem	V;IMP;PL;1;POS
americanitzar	americanitzin	V;SBJV;PL;3;PRS
esforçar-se	esforcéssim	V;SBJV;PL;1;PST
mirar-se	mirarien	V;COND;PL;3
desplaçar	desplacem	V;IND;PL;1;PRS
quedar	quedeu	V;SBJV;PL;2;PRS
triomfar	triomfaves	V;IPFV;IND;SG;2;PST
vorejar	voregi	V;IMP;SG;3;POS
rodar	roden	V;IND;PL;3;PRS
conrear	conrea	V;IMP;SG;2;POS
protegir	protegireu	V;IND;PL;2;FUT
emetre	emetreu	V;IND;PL;2;FUT
cosir	cosíssiu	V;SBJV;PL;2;PST
nomenar	nomenarem	V;IND;PL;1;FUT
acaronar	acaroni	V;SBJV;SG;1;PRS
adornar	adornes	V;IND;SG;2;PRS
recórrer	recorreguéssim	V;SBJV;PL;1;PST
eructar	eructi	V;IMP;SG;3;POS
trenar	trenem	V;IMP;PL;1;POS
socarrar	socarrem	V;SBJV;PL;1;PRS
prosperar	prospera	V;IND;SG;3;PRS
independitzar	independitzàreu	V;PFV;IND;PL;2;PST
liderar	liderés	V;SBJV;SG;3;PST
designar	designaran	V;IND;PL;3;FUT
discutir	discutí	V;PFV;IND;SG;3;PST
dotorejar	dotorejava	V;IPFV;IND;SG;1;PST
suar	sueu	V;SBJV;PL;2;PRS
emplenar	emplenava	V;IPFV;IND;SG;3;PST
teixir	teixissin	V;SBJV;PL;3;PST
somiar	somiàreu	V;PFV;IND;PL;2;PST
embriagar	embriagarem	V;IND;PL;1;FUT
preocupar-se	preocupà	V;PFV;IND;SG;3;PST
escanejar	escanegí	V;PFV;IND;SG;1;PST
forjar	forgi	V;SBJV;SG;1;PRS
oferir	oferien	V;IPFV;IND;PL;3;PST
enfondre	enfondrem	V;IND;PL;1;FUT
acariciar	acariciar	V;NFIN
suportar	suportaves	V;IPFV;IND;SG;2;PST
viure	visquéssim	V;SBJV;PL;1;PST
despatxar	despatxes	V;IND;SG;2;PRS
observar	observar	V;NFIN
establir	estableixi	V;IMP;SG;3;POS
finir	finirem	V;IND;PL;1;FUT
arraulir	arrauleixin	V;SBJV;PL;3;PRS
defenestrar	defenestra	V;IMP;SG;2;POS
jubilar	jubilí	V;PFV;IND;SG;1;PST
destil·lar	destil·lin	V;IMP;PL;3;POS
atenuar	atenuaria	V;COND;SG;3
condicionar	condicionen	V;IND;PL;3;PRS
afeblir	afeblíssiu	V;SBJV;PL;2;PST
dessalar	dessalà	V;PFV;IND;SG;3;PST
exorcitzar	exorcitzaràs	V;IND;SG;2;FUT
confirmar	confirmaríeu	V;COND;PL;2
orinar	orina	V;IMP;SG;2;POS
respirar	respiri	V;IMP;SG;3;POS
protagonitzar	protagonitzi	V;SBJV;SG;3;PRS
dominar	dominarien	V;COND;PL;3
cloure	cloïa	V;IPFV;IND;SG;1;PST
exhibir	exhibeixi	V;IMP;SG;3;POS
circumcidar	circumcidéssim	V;SBJV;PL;1;PST
mirar	mirar	V;NFIN
mostrar	mostràreu	V;PFV;IND;PL;2;PST
canviar	canviares	V;PFV;IND;SG;2;PST
deixar	deixi	V;IMP;SG;3;POS
capitular	capitularàs	V;IND;SG;2;FUT
cloure	clouria	V;COND;SG;3
pujar	pujaran	V;IND;PL;3;FUT
desar	deseu	V;IMP;PL;2;POS
suplicar	supliquessis	V;SBJV;SG;2;PST
atenuar	atenuessin	V;SBJV;PL;3;PST
dansar	dansares	V;PFV;IND;SG;2;PST
congelar	congelareu	V;IND;PL;2;FUT
ronronejar	ronronegem	V;SBJV;PL;1;PRS
imantar	imantareu	V;IND;PL;2;FUT
localitzar	localitzaré	V;IND;SG;1;FUT
alleugerir	alleugerirem	V;IND;PL;1;FUT
doldre	doldrien	V;COND;PL;3
témer	temo	V;IND;SG;1;PRS
fotosintetitzar	fotosintetitzares	V;PFV;IND;SG;2;PST
recórrer	recorregué	V;PFV;IND;SG;3;PST
designar	designis	V;SBJV;SG;2;PRS
agonitzar	agonitzeu	V;IMP;PL;2;POS
témer	temem	V;SBJV;PL;1;PRS
evitar	evitéssim	V;SBJV;PL;1;PST
traumatitzar	traumatitzar	V;NFIN
beneir	beneïu	V;SBJV;PL;2;PRS
occir	occís	V;SBJV;SG;3;PST
somriure	somric	V;IND;SG;1;PRS
esqueixar	esqueixéssim	V;SBJV;PL;1;PST
cruixir	cruixirem	V;IND;PL;1;FUT
escaramussar	escaramussis	V;SBJV;SG;2;PRS
escaramussar	escaramussem	V;IND;PL;1;PRS
nacionalitzar	nacionalitzem	V;IMP;PL;1;POS
emigrar	emigrareu	V;IND;PL;2;FUT
exhumar	exhumo	V;IND;SG;1;PRS
disseminar	dissemineu	V;IND;PL;2;PRS
untar	untaries	V;COND;SG;2
prometre	prometeren	V;PFV;IND;PL;3;PST
distreure	distrauríeu	V;COND;PL;2
resultar	resultés	V;SBJV;SG;3;PST
ventilar	ventilaves	V;IPFV;IND;SG;2;PST
familiaritzar	familiaritzà	V;PFV;IND;SG;3;PST
espanyolitzar	espanyolitzaria	V;COND;SG;3
idealitzar	idealitzen	V;IND;PL;3;PRS
enlluernar	enlluernaré	V;IND;SG;1;FUT
cuejar	cuegés	V;SBJV;SG;1;PST
centrar	centrava	V;IPFV;IND;SG;3;PST
fugir	fugi	V;SBJV;SG;3;PRS
néixer	naixia	V;IPFV;IND;SG;1;PST
vèncer	vencis	V;SBJV;SG;2;PRS
escornar	escornés	V;SBJV;SG;3;PST
conèixer	coneixeria	V;COND;SG;3
propagar	propaguis	V;SBJV;SG;2;PRS
reformar	reformaves	V;IPFV;IND;SG;2;PST
habilitar	habilitaven	V;IPFV;IND;PL;3;PST
estudiar	estudiïs	V;SBJV;SG;2;PRS
distreure	distragueu	V;SBJV;PL;2;PRS
mudar	mudaré	V;IND;SG;1;FUT
falsificar	falsifiquem	V;SBJV;PL;1;PRS
imposar	imposem	V;SBJV;PL;1;PRS
desafiar	desafiava	V;IPFV;IND;SG;3;PST
demolir	demolissin	V;SBJV;PL;3;PST
arraulir-se	arraulís	V;SBJV;SG;1;PST
emprar	emprí	V;PFV;IND;SG;1;PST
esmentar	esmentarem	V;IND;PL;1;FUT
usar	usava	V;IPFV;IND;SG;1;PST
tapar	taparà	V;IND;SG;3;FUT
atenuar	atenuarien	V;COND;PL;3
concebre	concebien	V;IPFV;IND;PL;3;PST
alliberar	alliberés	V;SBJV;SG;3;PST
nàixer	naixeu	V;IMP;PL;2;POS
fumar	fumares	V;PFV;IND;SG;2;PST
gesticular	gesticulaves	V;IPFV;IND;SG;2;PST
saludar	saludi	V;SBJV;SG;3;PRS
absoldre	absoldrien	V;COND;PL;3
tesar	tesaria	V;COND;SG;3
jeure	jeguis	V;SBJV;SG;2;PRS
remar	remin	V;IMP;PL;3;POS
executar	executem	V;SBJV;PL;1;PRS
robar	robaríem	V;COND;PL;1
acudir	acudeixi	V;SBJV;SG;1;PRS
rebentar	rebentareu	V;IND;PL;2;FUT
simpatitzar	simpatitzaria	V;COND;SG;1
acariciar	acariciàrem	V;PFV;IND;PL;1;PST
enregistrar	enregistraren	V;PFV;IND;PL;3;PST
verbalitzar	verbalitzéssiu	V;SBJV;PL;2;PST
destil·lar	destil·làveu	V;IPFV;IND;PL;2;PST
combatre	combatrà	V;IND;SG;3;FUT
contraatacar	contraataquin	V;IMP;PL;3;POS
teixir	teixírem	V;PFV;IND;PL;1;PST
extingir	extingiríem	V;COND;PL;1
rebotre	reboti	V;SBJV;SG;3;PRS
agitar	agités	V;SBJV;SG;1;PST
gambar	gambeu	V;IND;PL;2;PRS
estabilitzar	estabilitzi	V;IMP;SG;3;POS
engolir	engoleixin	V;SBJV;PL;3;PRS
rebotre	rebotés	V;SBJV;SG;3;PST
destacar	destacares	V;PFV;IND;SG;2;PST
destrossar	destrosséssim	V;SBJV;PL;1;PST
confondre	confongués	V;SBJV;SG;1;PST
perillar	perilléssiu	V;SBJV;PL;2;PST
traure	traurien	V;COND;PL;3
adquirir	adquiriràs	V;IND;SG;2;FUT
ventilar	ventili	V;SBJV;SG;3;PRS
fornir	forneixi	V;SBJV;SG;1;PRS
apologitzar	apologitzaríeu	V;COND;PL;2
jeure	jaguí	V;PFV;IND;SG;1;PST
apoderar	apoderin	V;IMP;PL;3;POS
traure	trauran	V;IND;PL;3;FUT
conquerir	conquereixi	V;SBJV;SG;3;PRS
dimeritzar	dimeritzaran	V;IND;PL;3;FUT
colar	colares	V;PFV;IND;SG;2;PST
mastegar	mastego	V;IND;SG;1;PRS
llepar	llepàveu	V;IPFV;IND;PL;2;PST
sobrevolar	sobrevoleu	V;IND;PL;2;PRS
alleugerir	alleugeria	V;IPFV;IND;SG;3;PST
generar	generin	V;IMP;PL;3;POS
desaparèixer	desapareguessin	V;SBJV;PL;3;PST
transformar	transformeu	V;IND;PL;2;PRS
estar	estiguem	V;IMP;PL;1;POS
prosperar	prosperaré	V;IND;SG;1;FUT
subratllar	subratllin	V;IMP;PL;3;POS
improvisar	improvisarem	V;IND;PL;1;FUT
unir	unim	V;IND;PL;1;PRS
agonitzar	agonitzaran	V;IND;PL;3;FUT
revenir	revindríem	V;COND;PL;1
estigmatitzar	estigmatitzem	V;IMP;PL;1;POS
capitular	capitulessis	V;SBJV;SG;2;PST
col·leccionar	col·leccionaria	V;COND;SG;1
enyorar	enyoràrem	V;PFV;IND;PL;1;PST
aprovar	aprovem	V;IMP;PL;1;POS
contravenir	contravinguéssim	V;SBJV;PL;1;PST
fertilitzar	fertilitza	V;IND;SG;3;PRS
gratular	gratulin	V;SBJV;PL;3;PRS
deixar	deixis	V;SBJV;SG;2;PRS
queixar-se	queixares	V;PFV;IND;SG;2;PST
ferrar	ferraràs	V;IND;SG;2;FUT
treure	tregui	V;SBJV;SG;1;PRS
dominar	dominarà	V;IND;SG;3;FUT
compensar	compensa	V;IMP;SG;2;POS
contenir	contens	V;IND;SG;2;PRS
garantir	garanties	V;IPFV;IND;SG;2;PST
escalfar	escalfaríem	V;COND;PL;1
fugir	fugires	V;PFV;IND;SG;2;PST
oposar	oposaràs	V;IND;SG;2;FUT
concórrer	concorreries	V;COND;SG;2
destil·lar	destil·laren	V;PFV;IND;PL;3;PST
arraulir	arrauliràs	V;IND;SG;2;FUT
allunyar	allunyava	V;IPFV;IND;SG;1;PST
dogmatitzar	dogmatitzaríeu	V;COND;PL;2
arrodonir	arrodonissis	V;SBJV;SG;2;PST
explicar	expliquí	V;PFV;IND;SG;1;PST
expel·lir	expel·lires	V;PFV;IND;SG;2;PST
cascar	casqueu	V;IND;PL;2;PRS
capolar	capolaríem	V;COND;PL;1
rompre	rompin	V;IMP;PL;3;POS
influir	influiria	V;COND;SG;3
perillar	perillaràs	V;IND;SG;2;FUT
promoure	promogui	V;SBJV;SG;1;PRS
colar	colàvem	V;IPFV;IND;PL;1;PST
esperar-se	esperem	V;SBJV;PL;1;PRS
anomenar	anomenaríem	V;COND;PL;1
eixir	eixireu	V;IND;PL;2;FUT
derrotar	derrotéssiu	V;SBJV;PL;2;PST
desodoritzar	desodoritzéssiu	V;SBJV;PL;2;PST
unir	uniríeu	V;COND;PL;2
sobremenjar	sobremengéssim	V;SBJV;PL;1;PST
distreure	distraurà	V;IND;SG;3;FUT
aliar	aliïn	V;SBJV;PL;3;PRS
controlar	controleu	V;IND;PL;2;PRS
necessitar	necessitaríeu	V;COND;PL;2
oprimir	oprimeixin	V;SBJV;PL;3;PRS
orar	orares	V;PFV;IND;SG;2;PST
procrastinar	procrastinés	V;SBJV;SG;1;PST
aprestar	aprestin	V;SBJV;PL;3;PRS
naufragar	naufragava	V;IPFV;IND;SG;3;PST
alleugerar	alleugeraren	V;PFV;IND;PL;3;PST
persuadir	persuadíem	V;IPFV;IND;PL;1;PST
dir	diríem	V;COND;PL;1
enyorar	enyoraren	V;PFV;IND;PL;3;PST
traspassar	traspassa	V;IND;SG;3;PRS
aprestar	aprestin	V;IMP;PL;3;POS
anglicitzar	anglicitzin	V;SBJV;PL;3;PRS
reiniciar	reiniciava	V;IPFV;IND;SG;3;PST
aprestar	aprestaré	V;IND;SG;1;FUT
estabilitzar	estabilitzés	V;SBJV;SG;1;PST
barrejar	barreja	V;IND;SG;3;PRS
ampliar	ampliava	V;IPFV;IND;SG;1;PST
evitar	evitares	V;PFV;IND;SG;2;PST
odiar	odia	V;IMP;SG;2;POS
enllestir	enllestirien	V;COND;PL;3
dissoldre	dissolguí	V;PFV;IND;SG;1;PST
segellar	segelleu	V;SBJV;PL;2;PRS
obtenir	obtinguí	V;PFV;IND;SG;1;PST
assistir	assistiríeu	V;COND;PL;2
col·leccionar	col·leccioneu	V;IND;PL;2;PRS
derivar	derivaré	V;IND;SG;1;FUT
subornar	subornàreu	V;PFV;IND;PL;2;PST
subornar	subornares	V;PFV;IND;SG;2;PST
respondre	respongui	V;SBJV;SG;1;PRS
sintonitzar	sintonitzi	V;SBJV;SG;3;PRS
destil·lar	destil·lares	V;PFV;IND;SG;2;PST
consagrar	consagreu	V;IND;PL;2;PRS
delir	deliu	V;IND;PL;2;PRS
desitjar	desitgi	V;IMP;SG;3;POS
llençar	llencéssim	V;SBJV;PL;1;PST
desprendre	desprendries	V;COND;SG;2
dotorejar	dotorejareu	V;IND;PL;2;FUT
voltar	voltaria	V;COND;SG;1
abeurar	abeuraré	V;IND;SG;1;FUT
tiranitzar	tiranitzen	V;IND;PL;3;PRS
pagar	pagares	V;PFV;IND;SG;2;PST
desvetllar	desvetlleu	V;IND;PL;2;PRS
cuirassar	cuirassaren	V;PFV;IND;PL;3;PST
declarar	declararíem	V;COND;PL;1
arraulir	arraulim	V;SBJV;PL;1;PRS
ruixar	ruixarà	V;IND;SG;3;FUT
costar	costaren	V;PFV;IND;PL;3;PST
caracteritzar	caracteritzessin	V;SBJV;PL;3;PST
idealitzar	idealitzar	V;NFIN
aglutinar	aglutinaríem	V;COND;PL;1
perillar	perillaré	V;IND;SG;1;FUT
lladrar	lladraríeu	V;COND;PL;2
habilitar	habilitem	V;IMP;PL;1;POS
llençar	llencin	V;SBJV;PL;3;PRS
agusar	agusàreu	V;PFV;IND;PL;2;PST
engolir	engolies	V;IPFV;IND;SG;2;PST
acabar	acabares	V;PFV;IND;SG;2;PST
guaitar	guaitaríem	V;COND;PL;1
efectuar	efectuaria	V;COND;SG;3
nuar	nueu	V;SBJV;PL;2;PRS
participar	participares	V;PFV;IND;SG;2;PST
retenir	retenia	V;IPFV;IND;SG;3;PST
proclamar	proclamà	V;PFV;IND;SG;3;PST
dissoldre	dissolien	V;IPFV;IND;PL;3;PST
bastir	bastireu	V;IND;PL;2;FUT
repartir	repartiria	V;COND;SG;1
disputar	disputí	V;PFV;IND;SG;1;PST
col·leccionar	col·leccioneu	V;IMP;PL;2;POS
rimar	rimares	V;PFV;IND;SG;2;PST
capficar-se	capficàreu	V;PFV;IND;PL;2;PST
globalitzar	globalitzessin	V;SBJV;PL;3;PST
queixar-se	queixen	V;IND;PL;3;PRS
citar	citeu	V;IND;PL;2;PRS
aglomerar	aglomerem	V;IMP;PL;1;POS
retallar	retallaràs	V;IND;SG;2;FUT
créixer	creixia	V;IPFV;IND;SG;1;PST
ferir	ferirem	V;IND;PL;1;FUT
compensar	compensaven	V;IPFV;IND;PL;3;PST
marxar	marxava	V;IPFV;IND;SG;1;PST
agregar	agregaven	V;IPFV;IND;PL;3;PST
ornamentar	ornamentem	V;IMP;PL;1;POS
suposar	suposava	V;IPFV;IND;SG;1;PST
fabricar	fabricava	V;IPFV;IND;SG;3;PST
ajornar	ajornin	V;IMP;PL;3;POS
vèncer	vencen	V;IND;PL;3;PRS
rebotre	rebotés	V;SBJV;SG;1;PST
acostumar-se	acostumi	V;SBJV;SG;1;PRS
llepar	llepa	V;IMP;SG;2;POS
témer	temi	V;IMP;SG;3;POS
departir	departiu	V;IMP;PL;2;POS
pujar	pujaven	V;IPFV;IND;PL;3;PST
imantar	imantaries	V;COND;SG;2
suplicar	suplico	V;IND;SG;1;PRS
fragmentar	fragmentessin	V;SBJV;PL;3;PST
confondre	confongués	V;SBJV;SG;3;PST
transfondre	transfongui	V;SBJV;SG;3;PRS
jeure	jaurem	V;IND;PL;1;FUT
renovar	renovaràs	V;IND;SG;2;FUT
estrenar	estrenarem	V;IND;PL;1;FUT
estudiar	estudiï	V;SBJV;SG;1;PRS
recolzar	recolzem	V;IMP;PL;1;POS
tossir	tossim	V;IMP;PL;1;POS
nodrir	nodreix	V;IMP;SG;2;POS
rovellar	rovellà	V;PFV;IND;SG;3;PST
assolir	assoleixi	V;IMP;SG;3;POS
preservar	preservessis	V;SBJV;SG;2;PST
distingir	distingissin	V;SBJV;PL;3;PST
fornir	forniu	V;SBJV;PL;2;PRS
barallar	barallaríem	V;COND;PL;1
esmentar	esmento	V;IND;SG;1;PRS
adquirir	adquiriríem	V;COND;PL;1
brillar	brillaràs	V;IND;SG;2;FUT
danyar	danyaràs	V;IND;SG;2;FUT
completar	completeu	V;IND;PL;2;PRS
capolar	capoléssiu	V;SBJV;PL;2;PST
barbar	barbeu	V;IMP;PL;2;POS
mancar	mancàrem	V;PFV;IND;PL;1;PST
rabejar	rabegem	V;SBJV;PL;1;PRS
fugir	fugir	V;NFIN
canviar	canviàrem	V;PFV;IND;PL;1;PST
persuadir	persuadia	V;IPFV;IND;SG;1;PST
ordenar	ordenà	V;PFV;IND;SG;3;PST
finir	finien	V;IPFV;IND;PL;3;PST
agusar	agusareu	V;IND;PL;2;FUT
xafarotejar	xafarotejarem	V;IND;PL;1;FUT
identificar	identificà	V;PFV;IND;SG;3;PST
afeblir	afeblíreu	V;PFV;IND;PL;2;PST
naufragar	naufraguin	V;IMP;PL;3;POS
moldre	molia	V;IPFV;IND;SG;1;PST
concebre	concebés	V;SBJV;SG;1;PST
envellir	envellireu	V;IND;PL;2;FUT
subornar	subornaríem	V;COND;PL;1
anomenar	anomenaria	V;COND;SG;1
establir	establiu	V;SBJV;PL;2;PRS
plantar	planto	V;IND;SG;1;PRS
merceritzar	merceritzares	V;PFV;IND;SG;2;PST
edificar	edificaven	V;IPFV;IND;PL;3;PST
ocupar	ocupessin	V;SBJV;PL;3;PST
ulular	ulularíeu	V;COND;PL;2
constrènyer	constrenyérem	V;PFV;IND;PL;1;PST
orientalitzar	orientalitza	V;IND;SG;3;PRS
demolir	demolirà	V;IND;SG;3;FUT
garantir	garantí	V;PFV;IND;SG;1;PST
posseir	posseïm	V;IND;PL;1;PRS
fixar-se	fixava	V;IPFV;IND;SG;3;PST
catalitzar	catalitzis	V;SBJV;SG;2;PRS
cascar	casqués	V;SBJV;SG;3;PST
trillar	trillàvem	V;IPFV;IND;PL;1;PST
desencadenar	desencadenem	V;IMP;PL;1;POS
mitigar	mitigaven	V;IPFV;IND;PL;3;PST
enregistrar	enregistrava	V;IPFV;IND;SG;1;PST
restaurar	restaures	V;IND;SG;2;PRS
orinar	orinar	V;NFIN
impedir	impedís	V;SBJV;SG;3;PST
reconciliar	reconciliàreu	V;PFV;IND;PL;2;PST
suggerir	suggeriries	V;COND;SG;2
contenir	continguessis	V;SBJV;SG;2;PST
ficar	fiquem	V;IND;PL;1;PRS
concloure	concloïen	V;IPFV;IND;PL;3;PST
adquirir	adquireixo	V;IND;SG;1;PRS
sol·licitar	sol·licitar	V;NFIN
imposar	imposa	V;IMP;SG;2;POS
ajornar	ajornaràs	V;IND;SG;2;FUT
rovellar	rovellaries	V;COND;SG;2
destorbar	destorbis	V;SBJV;SG;2;PRS
treballar	treballaré	V;IND;SG;1;FUT
sintonitzar	sintonitzares	V;PFV;IND;SG;2;PST
sobreestimar	sobreestimi	V;SBJV;SG;1;PRS
merceritzar	merceritzaré	V;IND;SG;1;FUT
esmentar	esmenta	V;IMP;SG;2;POS
masticar	masticaries	V;COND;SG;2
rabejar	rabegés	V;SBJV;SG;1;PST
comportar	comportin	V;SBJV;PL;3;PRS
denunciar	denunciïn	V;SBJV;PL;3;PRS
desprendre	desprendria	V;COND;SG;1
potabilitzar	potabilitzaria	V;COND;SG;3
remeiar	remeià	V;PFV;IND;SG;3;PST
quantificar	quantificàvem	V;IPFV;IND;PL;1;PST
esforçar-se	esforcem	V;IMP;PL;1;POS
arraulir	arrauleixen	V;IND;PL;3;PRS
coagular	coagularies	V;COND;SG;2
exorcitzar	exorcitzaven	V;IPFV;IND;PL;3;PST
podar	podéssiu	V;SBJV;PL;2;PST
assimilar	assimili	V;SBJV;SG;3;PRS
indignar	indignem	V;IND;PL;1;PRS
falsificar	falsificàrem	V;PFV;IND;PL;1;PST
violar	violarem	V;IND;PL;1;FUT
bullir	bullies	V;IPFV;IND;SG;2;PST
variar	variaren	V;PFV;IND;PL;3;PST
impossibilitar	impossibilitàrem	V;PFV;IND;PL;1;PST
mocar-se	mocava	V;IPFV;IND;SG;1;PST
caçar	caçaria	V;COND;SG;3
infectar	infectis	V;SBJV;SG;2;PRS
mecanitzar	mecanitzaríeu	V;COND;PL;2
rearrencar	rearrenquem	V;IND;PL;1;PRS
atrapar	atrapà	V;PFV;IND;SG;3;PST
alliberar	allibera	V;IMP;SG;2;POS
corroborar	corroboràreu	V;PFV;IND;PL;2;PST
capolar	capolí	V;PFV;IND;SG;1;PST
guarnir	guarnirien	V;COND;PL;3
classificar	classificaríem	V;COND;PL;1
explicar	explicàvem	V;IPFV;IND;PL;1;PST
rimar	rimessis	V;SBJV;SG;2;PST
exhibir	exhibien	V;IPFV;IND;PL;3;PST
multiplicar	multipliqueu	V;IND;PL;2;PRS
acampar	acamparien	V;COND;PL;3
exorcitzar	exorcitzarem	V;IND;PL;1;FUT
titubejar	titubegis	V;SBJV;SG;2;PRS
curar	curarem	V;IND;PL;1;FUT
anunciar	anuncio	V;IND;SG;1;PRS
determinar	determini	V;SBJV;SG;3;PRS
jeure	jauràs	V;IND;SG;2;FUT
abraçar	abraçarà	V;IND;SG;3;FUT
conquistar	conquista	V;IND;SG;3;PRS
barallar	barallava	V;IPFV;IND;SG;1;PST
enlluernar	enlluernaràs	V;IND;SG;2;FUT
somriure	somriguin	V;SBJV;PL;3;PRS
ubicar	ubicaríeu	V;COND;PL;2
internacionalitzar	internacionalitzeu	V;IND;PL;2;PRS
aportar	aporteu	V;IMP;PL;2;POS
especificar	especificaries	V;COND;SG;2
esternudar	esternudaria	V;COND;SG;3
desbordar	desbordà	V;PFV;IND;SG;3;PST
corroir	corroïu	V;IND;PL;2;PRS
besar	besarien	V;COND;PL;3
paralitzar	paralitzen	V;IND;PL;3;PRS
saquejar	saquejarà	V;IND;SG;3;FUT
bordar	bordi	V;SBJV;SG;3;PRS
refugiar	refugia	V;IMP;SG;2;POS
emetre	emeties	V;IPFV;IND;SG;2;PST
feminitzar	feminitzàreu	V;PFV;IND;PL;2;PST
immigrar	immigràreu	V;PFV;IND;PL;2;PST
parir	paríreu	V;PFV;IND;PL;2;PST
somiar	somií	V;PFV;IND;SG;1;PST
aguar	agües	V;IND;SG;2;PRS
protagonitzar	protagonitzin	V;IMP;PL;3;POS
remeiar	remeieu	V;IND;PL;2;PRS
divorciar	divorcií	V;PFV;IND;SG;1;PST
modernitzar	modernitzaren	V;PFV;IND;PL;3;PST
encantar	encantaré	V;IND;SG;1;FUT
revenjar-se	revenjar	V;NFIN
galvanitzar	galvanitzen	V;IND;PL;3;PRS
enutjar	enutjàvem	V;IPFV;IND;PL;1;PST
aglomerar	aglomereu	V;IMP;PL;2;POS
suïcidar-se	suïcidéssiu	V;SBJV;PL;2;PST
bastir	bastiu	V;IMP;PL;2;POS
desprendre	desprengués	V;SBJV;SG;1;PST
trencar	trenquen	V;IND;PL;3;PRS
consistir	consistir	V;NFIN
suprimir	suprimirem	V;IND;PL;1;FUT
insultar	insultàrem	V;PFV;IND;PL;1;PST
abrigar	abrigava	V;IPFV;IND;SG;3;PST
llogar	llogueu	V;SBJV;PL;2;PRS
educar	eduquéssiu	V;SBJV;PL;2;PST
ésser	era	V;IPFV;IND;SG;3;PST
felicitar	felicitarem	V;IND;PL;1;FUT
descriure	descriuràs	V;IND;SG;2;FUT
preveure	preveié	V;PFV;IND;SG;3;PST
ronronejar	ronronegés	V;SBJV;SG;3;PST
trencar	trenquessin	V;SBJV;PL;3;PST
evocar	evoquem	V;IND;PL;1;PRS
sobremenjar	sobremenja	V;IMP;SG;2;POS
disseminar	disseminéssim	V;SBJV;PL;1;PST
comprendre	comprèn	V;IND;SG;3;PRS
revenir	reveníeu	V;IPFV;IND;PL;2;PST
prohibir	prohibiria	V;COND;SG;3
beneir	beneíeu	V;IPFV;IND;PL;2;PST
fusionar	fusionàrem	V;PFV;IND;PL;1;PST
apoderar	apodereu	V;IND;PL;2;PRS
protestar	protestàvem	V;IPFV;IND;PL;1;PST
jubilar	jubilaràs	V;IND;SG;2;FUT
rebentar	rebentéssim	V;SBJV;PL;1;PST
acariciar	acaricia	V;IND;SG;3;PRS
capolar	capolàreu	V;PFV;IND;PL;2;PST
planxar	planxaràs	V;IND;SG;2;FUT
capficar-se	capficàveu	V;IPFV;IND;PL;2;PST
enfondre	enfoneu	V;IND;PL;2;PRS
sofrir	sofreixo	V;IND;SG;1;PRS
coincidir	coincidíssim	V;SBJV;PL;1;PST
cansar-se	cansàveu	V;IPFV;IND;PL;2;PST
redactar	redacti	V;SBJV;SG;3;PRS
subhastar	subhastaria	V;COND;SG;1
il·luminar	il·luminàrem	V;PFV;IND;PL;1;PST
nomenar	nomenen	V;IND;PL;3;PRS
argüir	argüiríeu	V;COND;PL;2
retenir	retenir	V;NFIN
llatinitzar	llatinitzéssim	V;SBJV;PL;1;PST
esternudar	esternudi	V;SBJV;SG;1;PRS
judaïtzar	judaïtzàvem	V;IPFV;IND;PL;1;PST
enregistrar	enregistràreu	V;PFV;IND;PL;2;PST
calcificar	calcifiqui	V;SBJV;SG;1;PRS
sofrir	sofrís	V;SBJV;SG;3;PST
arraulir-se	arraulirem	V;IND;PL;1;FUT
divinitzar	divinitzem	V;IMP;PL;1;POS
créixer	creixem	V;IMP;PL;1;POS
discutir	discutia	V;IPFV;IND;SG;3;PST
abrandar	abranda	V;IMP;SG;2;POS
localitzar	localitzem	V;SBJV;PL;1;PRS
fixar	fixa	V;IMP;SG;2;POS
dansar	dansarem	V;IND;PL;1;FUT
falsificar	falsifiquessin	V;SBJV;PL;3;PST
rebotre	reboteres	V;PFV;IND;SG;2;PST
ronronejar	ronronejava	V;IPFV;IND;SG;3;PST
emetre	emeteres	V;PFV;IND;SG;2;PST
extingir	extingiria	V;COND;SG;3
dominar	dominaren	V;PFV;IND;PL;3;PST
ferrar	ferrem	V;SBJV;PL;1;PRS
jurar	jureu	V;IND;PL;2;PRS
vedar	vedem	V;IMP;PL;1;POS
frenar	frenàveu	V;IPFV;IND;PL;2;PST
pal·liar	pal·liés	V;SBJV;SG;3;PST
incrementar	incrementeu	V;IND;PL;2;PRS
cascar	cascaria	V;COND;SG;3
mecanitzar	mecanitzessis	V;SBJV;SG;2;PST
aguar	agüem	V;IMP;PL;1;POS
judaïtzar	judaïtzaria	V;COND;SG;3
fornejar	fornegi	V;SBJV;SG;1;PRS
atrofiar	atrofia	V;IND;SG;3;PRS
suplantar	suplanta	V;IMP;SG;2;POS
estabilitzar	estabilitzàveu	V;IPFV;IND;PL;2;PST
marcar	marquéssiu	V;SBJV;PL;2;PST
desmoralitzar	desmoralitzàrem	V;PFV;IND;PL;1;PST
planxar	planxem	V;IND;PL;1;PRS
oprimir	oprimia	V;IPFV;IND;SG;3;PST
embriagar	embriagà	V;PFV;IND;SG;3;PST
quedar	quedessis	V;SBJV;SG;2;PST
combatre	combatin	V;IMP;PL;3;POS
divertir-se	diverteixin	V;SBJV;PL;3;PRS
concentrar	concentraren	V;PFV;IND;PL;3;PST
ulular	ululi	V;SBJV;SG;1;PRS
materialitzar	materialitzàreu	V;PFV;IND;PL;2;PST
sentir	sentí	V;PFV;IND;SG;1;PST
merceritzar	merceritzaries	V;COND;SG;2
islamitzar	islamitzéssim	V;SBJV;PL;1;PST
restringir	restringires	V;PFV;IND;SG;2;PST
caldre	calen	V;IND;PL;3;PRS
desbordar	desbordàveu	V;IPFV;IND;PL;2;PST
trobar	trobà	V;PFV;IND;SG;3;PST
fortificar	fortifiquéssiu	V;SBJV;PL;2;PST
servir	servíssim	V;SBJV;PL;1;PST
consistir	consistíreu	V;PFV;IND;PL;2;PST
recuperar	recupera	V;IND;SG;3;PRS
fixar	fixar	V;NFIN
potabilitzar	potabilitzava	V;IPFV;IND;SG;1;PST
edificar	edificaves	V;IPFV;IND;SG;2;PST
rearrencar	rearrencaríeu	V;COND;PL;2
segellar	segellàrem	V;PFV;IND;PL;1;PST
vociferar	vocifero	V;IND;SG;1;PRS
fragmentar	fragmenta	V;IMP;SG;2;POS
folrar	folraria	V;COND;SG;1
conquistar	conquistaran	V;IND;PL;3;FUT
destituir	destitueixi	V;SBJV;SG;1;PRS
llogar	llogues	V;IND;SG;2;PRS
jurar	juri	V;SBJV;SG;3;PRS
reiniciar	reiniciaria	V;COND;SG;3
ofegar	ofegaria	V;COND;SG;1
refrescar	refrescàvem	V;IPFV;IND;PL;1;PST
occir	occiria	V;COND;SG;3
ruixar	ruixaríem	V;COND;PL;1
esmentar	esmenten	V;IND;PL;3;PRS
aportar	aportava	V;IPFV;IND;SG;3;PST
catalitzar	catalitzeu	V;IND;PL;2;PRS
facilitar	facilitaren	V;PFV;IND;PL;3;PST
internacionalitzar	internacionalitzares	V;PFV;IND;SG;2;PST
voler	vulguem	V;IMP;PL;1;POS
monopolitzar	monopolitzàreu	V;PFV;IND;PL;2;PST
explotar	explotarien	V;COND;PL;3
arrossegar	arrossegà	V;PFV;IND;SG;3;PST
identificar	identificàveu	V;IPFV;IND;PL;2;PST
promoure	promou	V;IMP;SG;2;POS
raure	ragué	V;PFV;IND;SG;3;PST
polaritzar	polaritzes	V;IND;SG;2;PRS
remeiar	remeï	V;SBJV;SG;3;PRS
categoritzar	categoritzarem	V;IND;PL;1;FUT
enfondre	enfonies	V;IPFV;IND;SG;2;PST
subhastar	subhastava	V;IPFV;IND;SG;1;PST
esmorzar	esmorza	V;IMP;SG;2;POS
pal·liar	pal·liïn	V;SBJV;PL;3;PRS
transcriure	transcriuríeu	V;COND;PL;2
arrendar	arrendàvem	V;IPFV;IND;PL;1;PST
reescalfar	reescalfarà	V;IND;SG;3;FUT
explotar	explotarà	V;IND;SG;3;FUT
exhumar	exhumen	V;IND;PL;3;PRS
indignar	indignéssiu	V;SBJV;PL;2;PST
refrigerar	refrigerar	V;NFIN
educar	eduquessin	V;SBJV;PL;3;PST
coagular	coaguli	V;IMP;SG;3;POS
motivar	motivi	V;SBJV;SG;1;PRS
civilitzar	civilitzàrem	V;PFV;IND;PL;1;PST
exclamar	exclamin	V;SBJV;PL;3;PRS
comparar	comparessin	V;SBJV;PL;3;PST
orientalitzar	orientalitzen	V;IND;PL;3;PRS
ulular	ulularan	V;IND;PL;3;FUT
restaurar	restauraves	V;IPFV;IND;SG;2;PST
causar	causem	V;IMP;PL;1;POS
sobrevolar	sobrevolaran	V;IND;PL;3;FUT
roncar	roncarà	V;IND;SG;3;FUT
reformar	reformarien	V;COND;PL;3
llatinitzar	llatinitzàreu	V;PFV;IND;PL;2;PST
terminar	terminàrem	V;PFV;IND;PL;1;PST
disculpar-se	disculpa	V;IMP;SG;2;POS
terminar	terminen	V;IND;PL;3;PRS
rebentar	rebenten	V;IND;PL;3;PRS
menar	menaré	V;IND;SG;1;FUT
subministrar	subministraria	V;COND;SG;1
orar	ori	V;SBJV;SG;1;PRS
terminar	terminaríem	V;COND;PL;1
dependre	depenc	V;IND;SG;1;PRS
centrar	centri	V;SBJV;SG;3;PRS
fornir	fornissin	V;SBJV;PL;3;PST
quedar	quedéssiu	V;SBJV;PL;2;PST
dar	deu	V;SBJV;PL;2;PRS
independitzar	independitzarà	V;IND;SG;3;FUT
oir	oïren	V;PFV;IND;PL;3;PST
estabilitzar	estabilitzaria	V;COND;SG;3
tantalitzar	tantalitza	V;IND;SG;3;PRS
gesticular	gesticulà	V;PFV;IND;SG;3;PST
alleugerar	alleugerarem	V;IND;PL;1;FUT
esgarrar	esgarri	V;IMP;SG;3;POS
dramatitzar	dramatitzeu	V;IMP;PL;2;POS
centrar	centreu	V;IMP;PL;2;POS
guarnir	guarnim	V;IND;PL;1;PRS
adornar	adornàvem	V;IPFV;IND;PL;1;PST
redactar	redactem	V;SBJV;PL;1;PRS
usar	usés	V;SBJV;SG;3;PST
abrigar	abrigués	V;SBJV;SG;1;PST
trucar	trucàrem	V;PFV;IND;PL;1;PST
americanitzar	americanitzàrem	V;PFV;IND;PL;1;PST
apologitzar	apologitza	V;IND;SG;3;PRS
desmilitaritzar	desmilitaritzí	V;PFV;IND;SG;1;PST
generar	generi	V;SBJV;SG;3;PRS
frenar	frenaria	V;COND;SG;3
desvetllar	desvetlli	V;SBJV;SG;3;PRS
persistir	persisteix	V;IMP;SG;2;POS
sabotejar	sabotejàreu	V;PFV;IND;PL;2;PST
agrupar	agrupa	V;IND;SG;3;PRS
rodar	rodis	V;SBJV;SG;2;PRS
confondre	confon	V;IMP;SG;2;POS
intitular	intitulares	V;PFV;IND;SG;2;PST
excretar	excretaríeu	V;COND;PL;2
rearrencar	rearrencares	V;PFV;IND;SG;2;PST
orar	oraven	V;IPFV;IND;PL;3;PST
desplaçar	desplaçà	V;PFV;IND;SG;3;PST
cancel·lar	cancel·lares	V;PFV;IND;SG;2;PST
cicatritzar	cicatritzava	V;IPFV;IND;SG;3;PST
bordar	bordem	V;IMP;PL;1;POS
resoldre	resolguéssim	V;SBJV;PL;1;PST
podar	podàreu	V;PFV;IND;PL;2;PST
desobeir	desobeiran	V;IND;PL;3;FUT
témer	tem	V;IMP;SG;2;POS
defendre	defens	V;IND;SG;2;PRS
denunciar	denunciés	V;SBJV;SG;1;PST
labialitzar	labialitzessin	V;SBJV;PL;3;PST
distreure	distrauran	V;IND;PL;3;FUT
fixar	fixis	V;SBJV;SG;2;PRS
fraternitzar	fraternitzes	V;IND;SG;2;PRS
cansar-se	canseu	V;IMP;PL;2;POS
néixer	naixeré	V;IND;SG;1;FUT
teixir	teixiries	V;COND;SG;2
saquejar	saquejaríeu	V;COND;PL;2
defendre	defèn	V;IMP;SG;2;POS
circumcidar	circumcidà	V;PFV;IND;SG;3;PST
esmicolar	esmicolés	V;SBJV;SG;3;PST
caracteritzar	caracteritzessis	V;SBJV;SG;2;PST
desodoritzar	desodoritzava	V;IPFV;IND;SG;1;PST
revenjar-se	revenjares	V;PFV;IND;SG;2;PST
aïnar	aïneu	V;SBJV;PL;2;PRS
traure	tragui	V;SBJV;SG;1;PRS
esglaiar	esglaiéssiu	V;SBJV;PL;2;PST
apoderar	apoderessis	V;SBJV;SG;2;PST
raonar	raonis	V;SBJV;SG;2;PRS
escornar	escorna	V;IND;SG;3;PRS
desar	desi	V;IMP;SG;3;POS
atrapar	atrapeu	V;IND;PL;2;PRS
acampar	acamparà	V;IND;SG;3;FUT
desitjar	desitgés	V;SBJV;SG;3;PST
córrer	corrin	V;IMP;PL;3;POS
constrènyer	constrenyi	V;SBJV;SG;1;PRS
insultar	insultaries	V;COND;SG;2
decidir	decidissin	V;SBJV;PL;3;PST
besar	besa	V;IND;SG;3;PRS
reconstruir	reconstruíeu	V;IPFV;IND;PL;2;PST
batallar	batallí	V;PFV;IND;SG;1;PST
subjugar	subjugàveu	V;IPFV;IND;PL;2;PST
cabre	caberen	V;PFV;IND;PL;3;PST
desfer	desfacin	V;SBJV;PL;3;PRS
llepar	llepeu	V;SBJV;PL;2;PRS
ofegar	ofegaria	V;COND;SG;3
potabilitzar	potabilitza	V;IMP;SG;2;POS
reforçar	reforço	V;IND;SG;1;PRS
caracteritzar	caracteritza	V;IMP;SG;2;POS
fraternitzar	fraternitza	V;IND;SG;3;PRS
alterar	alterares	V;PFV;IND;SG;2;PST
bufar	buféssiu	V;SBJV;PL;2;PST
rebel·lar	rebel·lar	V;NFIN
mitigar	mitigaren	V;PFV;IND;PL;3;PST
enxampar	enxampéssiu	V;SBJV;PL;2;PST
domtar	domtava	V;IPFV;IND;SG;3;PST
col·leccionar	col·leccionés	V;SBJV;SG;3;PST
esperar-se	esperava	V;IPFV;IND;SG;3;PST
dissociar	dissocio	V;IND;SG;1;PRS
apologitzar	apologitzar	V;NFIN
somriure	somriguis	V;SBJV;SG;2;PRS
democratitzar	democratitzaré	V;IND;SG;1;FUT
cancel·lar	cancel·laven	V;IPFV;IND;PL;3;PST
agonitzar	agonitzes	V;IND;SG;2;PRS
marxar	marxí	V;PFV;IND;SG;1;PST
sol·licitar	sol·licitem	V;SBJV;PL;1;PRS
redactar	redactà	V;PFV;IND;SG;3;PST
concórrer	concorrerà	V;IND;SG;3;FUT
traure	trauré	V;IND;SG;1;FUT
caracteritzar	caracteritzava	V;IPFV;IND;SG;3;PST
deturar	deturin	V;IMP;PL;3;POS
créixer	creixeu	V;IMP;PL;2;POS
aportar	aporti	V;IMP;SG;3;POS
encantar	encantessis	V;SBJV;SG;2;PST
costar	costaràs	V;IND;SG;2;FUT
emancipar	emancipés	V;SBJV;SG;1;PST
massejar	massejàveu	V;IPFV;IND;PL;2;PST
tardar	tardaràs	V;IND;SG;2;FUT
suposar	suposés	V;SBJV;SG;3;PST
economitzar	economitzaria	V;COND;SG;3
urgir	urgires	V;PFV;IND;SG;2;PST
abeurar	abeuri	V;SBJV;SG;1;PRS
capitular	capituléssim	V;SBJV;PL;1;PST
visitar	visitin	V;IMP;PL;3;POS
hipnotitzar	hipnotitzarien	V;COND;PL;3
desaparèixer	desaparèixer	V;NFIN
rebaixar	rebaixaran	V;IND;PL;3;FUT
pintar	pinta	V;IND;SG;3;PRS
definir	definim	V;SBJV;PL;1;PRS
estigmatitzar	estigmatitzeu	V;IND;PL;2;PRS
declarar	declaressis	V;SBJV;SG;2;PST
menar	meni	V;SBJV;SG;1;PRS
rebre	rebí	V;PFV;IND;SG;1;PST
lexicalitzar	lexicalitzis	V;SBJV;SG;2;PRS
empaquetar	empaquetaríem	V;COND;PL;1
gelar	gelarem	V;IND;PL;1;FUT
menysvalorar	menysvalorés	V;SBJV;SG;3;PST
familiaritzar	familiaritzí	V;PFV;IND;SG;1;PST
nàixer	nàixer	V;NFIN
delir	delíreu	V;PFV;IND;PL;2;PST
demanar	demano	V;IND;SG;1;PRS
invitar	invitares	V;PFV;IND;SG;2;PST
sobrevolar	sobrevolaria	V;COND;SG;3
seduir	sedueix	V;IMP;SG;2;POS
envellir	envellissin	V;SBJV;PL;3;PST
dir-se	es diuen	V;IND;PL;3;PRS
ruixar	ruixaves	V;IPFV;IND;SG;2;PST
pronunciar-se	pronunciessin	V;SBJV;PL;3;PST
riure	riguem	V;SBJV;PL;1;PRS
urgir	urgiríeu	V;COND;PL;2
occir	occíssiu	V;SBJV;PL;2;PST
contravenir	contravén	V;IMP;SG;2;POS
protagonitzar	protagonitzessis	V;SBJV;SG;2;PST
envejar	envegem	V;IMP;PL;1;POS
hipnotitzar	hipnotitzà	V;PFV;IND;SG;3;PST
imantar	imantem	V;IND;PL;1;PRS
orientalitzar	orientalitzaria	V;COND;SG;1
mocar-se	moquéssiu	V;SBJV;PL;2;PST
remar	remaré	V;IND;SG;1;FUT
dimeritzar	dimeritzàreu	V;PFV;IND;PL;2;PST
abrandar	abrandi	V;IMP;SG;3;POS
tardar	tarda	V;IND;SG;3;PRS
enlluernar	enlluernarem	V;IND;PL;1;FUT
assabentar	assabentin	V;IMP;PL;3;POS
mitigar	mitigaves	V;IPFV;IND;SG;2;PST
cometre	cometeu	V;SBJV;PL;2;PRS
preocupar-se	preocuparà	V;IND;SG;3;FUT
imposar	imposaven	V;IPFV;IND;PL;3;PST
sobreviure	sobreviuràs	V;IND;SG;2;FUT
subjugar	subjugava	V;IPFV;IND;SG;1;PST
aconseguir	aconseguiria	V;COND;SG;1
abrandar	abrandés	V;SBJV;SG;3;PST
orinar	orinares	V;PFV;IND;SG;2;PST
repartir	repartirem	V;IND;PL;1;FUT
dibuixar	dibuixa	V;IMP;SG;2;POS
trucar	truco	V;IND;SG;1;PRS
tirar	tiraré	V;IND;SG;1;FUT
reclamar	reclamava	V;IPFV;IND;SG;1;PST
esterilitzar	esterilitzin	V;IMP;PL;3;POS
suplir	supleixi	V;SBJV;SG;3;PRS
exhumar	exhumi	V;SBJV;SG;3;PRS
desistir	desisteixo	V;IND;SG;1;PRS
esperar-se	espera	V;IMP;SG;2;POS
llegar	llegués	V;SBJV;SG;3;PST
originar	originaríem	V;COND;PL;1
atrapar	atrapéssim	V;SBJV;PL;1;PST
finir	finiràs	V;IND;SG;2;FUT
fregir	fregeixi	V;SBJV;SG;1;PRS
saquejar	saquejaríem	V;COND;PL;1
cometre	cometéssiu	V;SBJV;PL;2;PST
dinamitzar	dinamitzava	V;IPFV;IND;SG;1;PST
atribuir	atribuïm	V;IMP;PL;1;POS
legislar	legislàreu	V;PFV;IND;PL;2;PST
batejar	batejaríeu	V;COND;PL;2
usar	usava	V;IPFV;IND;SG;3;PST
omplir	ompliríem	V;COND;PL;1
soldar	soldareu	V;IND;PL;2;FUT
podar	podaríem	V;COND;PL;1
ventilar	ventilarem	V;IND;PL;1;FUT
rebentar	rebentàvem	V;IPFV;IND;PL;1;PST
anunciar	anunciares	V;PFV;IND;SG;2;PST
cosir	cosiria	V;COND;SG;1
encarregar	encarregaren	V;PFV;IND;PL;3;PST
absoldre	absolguin	V;SBJV;PL;3;PRS
polaritzar	polaritzo	V;IND;SG;1;PRS
fugir	fugissis	V;SBJV;SG;2;PST
liderar	lidereu	V;IMP;PL;2;POS
finalitzar	finalitzis	V;SBJV;SG;2;PRS
simpatitzar	simpatitzàveu	V;IPFV;IND;PL;2;PST
ventilar	ventiléssiu	V;SBJV;PL;2;PST
bullir	bullen	V;IND;PL;3;PRS
catapultar	catapultares	V;PFV;IND;SG;2;PST
adobar	adobem	V;IND;PL;1;PRS
influir	influiran	V;IND;PL;3;FUT
alçar	alçàreu	V;PFV;IND;PL;2;PST
curar	curin	V;SBJV;PL;3;PRS
calmar	calma	V;IND;SG;3;PRS
terminar	terminaren	V;PFV;IND;PL;3;PST
designar	designàreu	V;PFV;IND;PL;2;PST
aprovar	aprova	V;IMP;SG;2;POS
ficar	fiquis	V;SBJV;SG;2;PRS
internacionalitzar	internacionalitzeu	V;SBJV;PL;2;PRS
labiovelaritzar	labiovelaritzes	V;IND;SG;2;PRS
noure	noguéssiu	V;SBJV;PL;2;PST
entregar	entregaries	V;COND;SG;2
esperar-se	esperaries	V;COND;SG;2
aplicar	aplicaries	V;COND;SG;2
acaronar	acaronéssim	V;SBJV;PL;1;PST
enyorar	enyori	V;SBJV;SG;3;PRS
esmicolar	esmicolàvem	V;IPFV;IND;PL;1;PST
exorcitzar	exorcitza	V;IMP;SG;2;POS
arrendar	arrendaria	V;COND;SG;1
descompondre	descompondríeu	V;COND;PL;2
ulular	ululessis	V;SBJV;SG;2;PST
labialitzar	labialitzaries	V;COND;SG;2
il·lustrar	il·lustrarem	V;IND;PL;1;FUT
estar	estaria	V;COND;SG;1
sexar	sexem	V;SBJV;PL;1;PRS
rebre	rebia	V;IPFV;IND;SG;3;PST
retallar	retallin	V;IMP;PL;3;POS
suprimir	suprimiren	V;PFV;IND;PL;3;PST
reflexionar	reflexionaries	V;COND;SG;2
nuar	nuàrem	V;PFV;IND;PL;1;PST
pasteuritzar	pasteuritzis	V;SBJV;SG;2;PRS
afavorir	afavorirà	V;IND;SG;3;FUT
teixir	teixíssiu	V;SBJV;PL;2;PST
escalfar	escalfaríeu	V;COND;PL;2
esperar-se	esperaren	V;PFV;IND;PL;3;PST
distreure	distreies	V;IPFV;IND;SG;2;PST
jugar	jugares	V;PFV;IND;SG;2;PST
dilatar	dilataràs	V;IND;SG;2;FUT
ionitzar	ionitzaré	V;IND;SG;1;FUT
relaxar	relaxéssiu	V;SBJV;PL;2;PST
aterrar	aterra	V;IMP;SG;2;POS
aproximar	aproxima	V;IND;SG;3;PRS
guarir	guareixin	V;IMP;PL;3;POS
amar	amaries	V;COND;SG;2
inclinar	inclinava	V;IPFV;IND;SG;3;PST
ensordir	ensordiràs	V;IND;SG;2;FUT
decapitar	decapita	V;IMP;SG;2;POS
pelar	pela	V;IMP;SG;2;POS
batre	bateu	V;IND;PL;2;PRS
guanyar	guanyin	V;SBJV;PL;3;PRS
associar	associï	V;SBJV;SG;3;PRS
alegrar	alegri	V;IMP;SG;3;POS
practicar	practicaríeu	V;COND;PL;2
escapar	escapo	V;IND;SG;1;PRS
sostenir	sostinguem	V;IMP;PL;1;POS
proporcionar	proporcionar	V;NFIN
comparèixer	compareixeran	V;IND;PL;3;FUT
aconsellar	aconsellés	V;SBJV;SG;1;PST
recordar	recorden	V;IND;PL;3;PRS
informar	informi	V;SBJV;SG;3;PRS
pregar	pregaré	V;IND;SG;1;FUT
imitar	imitareu	V;IND;PL;2;FUT
remenar	remenarà	V;IND;SG;3;FUT
recomençar	recomencéssim	V;SBJV;PL;1;PST
editar	editaria	V;COND;SG;3
condemnar	condemnaria	V;COND;SG;3
captivar	captivàveu	V;IPFV;IND;PL;2;PST
dialogar	dialogarem	V;IND;PL;1;FUT
sincronitzar	sincronitzés	V;SBJV;SG;1;PST
privatitzar	privatitzaríem	V;COND;PL;1
esnifar	esnifi	V;IMP;SG;3;POS
comandar	comandes	V;IND;SG;2;PRS
destripar	destriparia	V;COND;SG;1
apostar	apostava	V;IPFV;IND;SG;3;PST
daurar	daureu	V;SBJV;PL;2;PRS
inaugurar	inaugureu	V;IMP;PL;2;POS
raspallar	raspallares	V;PFV;IND;SG;2;PST
moralitzar	moralitzem	V;IND;PL;1;PRS
escapar	escapava	V;IPFV;IND;SG;1;PST
plorar	plorem	V;IND;PL;1;PRS
vincular	vinculareu	V;IND;PL;2;FUT
remoldre	remoldríeu	V;COND;PL;2
pensar	pensaríeu	V;COND;PL;2
nedar	nedàreu	V;PFV;IND;PL;2;PST
crucificar	crucifiqueu	V;SBJV;PL;2;PRS
ploure	plouran	V;IND;PL;3;FUT
aidar	aidaràs	V;IND;SG;2;FUT
vendre	vendreu	V;IND;PL;2;FUT
absorbir	absorbien	V;IPFV;IND;PL;3;PST
conceptualitzar	conceptualitzaria	V;COND;SG;3
motoritzar	motoritzaríeu	V;COND;PL;2
doblar	doblàrem	V;PFV;IND;PL;1;PST
realitzar	realitzareu	V;IND;PL;2;FUT
polir	polir	V;NFIN
ridiculitzar	ridiculitzaria	V;COND;SG;1
revistar	revistava	V;IPFV;IND;SG;1;PST
embolicar	embolica	V;IND;SG;3;PRS
intuir	intuïm	V;SBJV;PL;1;PRS
armar	armi	V;SBJV;SG;1;PRS
embenar	embeneu	V;SBJV;PL;2;PRS
relatar	relata	V;IMP;SG;2;POS
justificar	justifiquen	V;IND;PL;3;PRS
estripar	estripava	V;IPFV;IND;SG;3;PST
segregar	segregarà	V;IND;SG;3;FUT
distanciar	distanciï	V;IMP;SG;3;POS
refredar	refredéssim	V;SBJV;PL;1;PST
perpetrar	perpetris	V;SBJV;SG;2;PRS
sagnar	sagnem	V;IMP;PL;1;POS
perdonar	perdonaria	V;COND;SG;3
esgarriar	esgarriava	V;IPFV;IND;SG;1;PST
obliquar	obliquàreu	V;PFV;IND;PL;2;PST
retirar	retireu	V;IMP;PL;2;POS
graduar	graduí	V;PFV;IND;SG;1;PST
esquitxar	esquitxaria	V;COND;SG;1
confeccionar	confeccionem	V;IND;PL;1;PRS
caure	caigui	V;SBJV;SG;1;PRS
distendre	distenien	V;IPFV;IND;PL;3;PST
faltar	falteu	V;SBJV;PL;2;PRS
flairar	flairàreu	V;PFV;IND;PL;2;PST
escollir	escollirà	V;IND;SG;3;FUT
callar	callem	V;IMP;PL;1;POS
alletar	alletaries	V;COND;SG;2
esbotifarrar	esbotifarrin	V;SBJV;PL;3;PRS
armar	armàvem	V;IPFV;IND;PL;1;PST
inflar	inflaràs	V;IND;SG;2;FUT
mercantilitzar	mercantilitzessis	V;SBJV;SG;2;PST
inclinar	inclina	V;IMP;SG;2;POS
fundar	fundéssiu	V;SBJV;PL;2;PST
descoratjar	descoratjaràs	V;IND;SG;2;FUT
estacar	estaquéssim	V;SBJV;PL;1;PST
continuar	continueu	V;SBJV;PL;2;PRS
acollir	acolliré	V;IND;SG;1;FUT
avantatjar	avantatgem	V;SBJV;PL;1;PRS
assecar	assequessis	V;SBJV;SG;2;PST
posposar	posposar	V;NFIN
descobrir	descobreixin	V;SBJV;PL;3;PRS
belar	belem	V;SBJV;PL;1;PRS
reflectir	reflectiu	V;IND;PL;2;PRS
cansar	canséssiu	V;SBJV;PL;2;PST
faltar	falteu	V;IMP;PL;2;POS
assaborir	assaborírem	V;PFV;IND;PL;1;PST
retornar	retornéssiu	V;SBJV;PL;2;PST
constituir	constituireu	V;IND;PL;2;FUT
excel·lir	excel·lissis	V;SBJV;SG;2;PST
temptar	temptaren	V;PFV;IND;PL;3;PST
viatjar	viatjaries	V;COND;SG;2
distendre	distenc	V;IND;SG;1;PRS
provocar	provoqués	V;SBJV;SG;1;PST
relaxar	relaxarà	V;IND;SG;3;FUT
nadar	nadareu	V;IND;PL;2;FUT
separar	separen	V;IND;PL;3;PRS
obeir	obeiries	V;COND;SG;2
excitar	excitàrem	V;PFV;IND;PL;1;PST
respectar	respecti	V;SBJV;SG;3;PRS
experimentar	experimentaràs	V;IND;SG;2;FUT
sorprendre	sorprenia	V;IPFV;IND;SG;3;PST
datar	datarien	V;COND;PL;3
torturar	torturàvem	V;IPFV;IND;PL;1;PST
estirar	estirí	V;PFV;IND;SG;1;PST
agradar	agradaves	V;IPFV;IND;SG;2;PST
expulsar	expulsares	V;PFV;IND;SG;2;PST
precisar	preciseu	V;SBJV;PL;2;PRS
cedir	cedires	V;PFV;IND;SG;2;PST
honrar	honrà	V;PFV;IND;SG;3;PST
ploure	plogueres	V;PFV;IND;SG;2;PST
regressar	regressem	V;IND;PL;1;PRS
mobilitzar	mobilitzàveu	V;IPFV;IND;PL;2;PST
enterrar	enterràrem	V;PFV;IND;PL;1;PST
propiciar	propicies	V;IND;SG;2;PRS
atemptar	atemptava	V;IPFV;IND;SG;3;PST
carregar	carreguen	V;IND;PL;3;PRS
esbotifarrar	esbotifarréssiu	V;SBJV;PL;2;PST
organitzar	organitzarien	V;COND;PL;3
editar	editava	V;IPFV;IND;SG;1;PST
partir	partiria	V;COND;SG;1
disposar	disposéssiu	V;SBJV;PL;2;PST
narrar	narressin	V;SBJV;PL;3;PST
imprimir	imprimia	V;IPFV;IND;SG;1;PST
creuar	creués	V;SBJV;SG;3;PST
perseverar	perseveri	V;SBJV;SG;3;PRS
etiquetar	etiquetàreu	V;PFV;IND;PL;2;PST
tornar-se	torneu	V;IMP;PL;2;POS
atomitzar	atomitzàvem	V;IPFV;IND;PL;1;PST
esdevenir	esdevindràs	V;IND;SG;2;FUT
exterminar	exterminaré	V;IND;SG;1;FUT
emmagatzemar	emmagatzemés	V;SBJV;SG;3;PST
pecar	pecaven	V;IPFV;IND;PL;3;PST
cooperar	cooperen	V;IND;PL;3;PRS
adormir	adormissis	V;SBJV;SG;2;PST
callar	calles	V;IND;SG;2;PRS
atorgar	atorguem	V;IND;PL;1;PRS
narrar	narréssim	V;SBJV;PL;1;PST
demostrar	demostro	V;IND;SG;1;PRS
reeixir	reïx	V;IMP;SG;2;POS
elevar	eleves	V;IND;SG;2;PRS
comandar	comandin	V;SBJV;PL;3;PRS
disposar	disposaríem	V;COND;PL;1
investigar	investigaren	V;PFV;IND;PL;3;PST
inventar	inventin	V;SBJV;PL;3;PRS
incorporar	incorporaríeu	V;COND;PL;2
botre	boten	V;IND;PL;3;PRS
humanitzar	humanitzava	V;IPFV;IND;SG;3;PST
rejovenir	rejoveneix	V;IMP;SG;2;POS
tronar	tronaré	V;IND;SG;1;FUT
pertànyer	pertanyíeu	V;IPFV;IND;PL;2;PST
deshumanitzar	deshumanitzares	V;PFV;IND;SG;2;PST
assumir	assumirem	V;IND;PL;1;FUT
vaporitzar	vaporitzaren	V;PFV;IND;PL;3;PST
etiquetar	etiquetàvem	V;IPFV;IND;PL;1;PST
rescatar	rescateu	V;SBJV;PL;2;PRS
batre	batem	V;IND;PL;1;PRS
obrir	obríreu	V;PFV;IND;PL;2;PST
remuntar	remuntaríeu	V;COND;PL;2
monetitzar	monetitzarien	V;COND;PL;3
refondre	refondrem	V;IND;PL;1;FUT
fotografiar	fotografiaves	V;IPFV;IND;SG;2;PST
interrompre	interromperes	V;PFV;IND;SG;2;PST
carbonitzar	carbonitzeu	V;SBJV;PL;2;PRS
editar	editàreu	V;PFV;IND;PL;2;PST
acostar	acostéssim	V;SBJV;PL;1;PST
sostenir	sostindrà	V;IND;SG;3;FUT
encendre	enceneu	V;IND;PL;2;PRS
suspendre	suspendrà	V;IND;SG;3;FUT
boxar	boxaven	V;IPFV;IND;PL;3;PST
pronunciar	pronunciés	V;SBJV;SG;1;PST
segregar	segreguem	V;IND;PL;1;PRS
orbitar	orbitares	V;PFV;IND;SG;2;PST
encadenar	encadenares	V;PFV;IND;SG;2;PST
estalviar	estalviï	V;SBJV;SG;3;PRS
xopar	xopa	V;IMP;SG;2;POS
debutar	debuti	V;SBJV;SG;1;PRS
nominar	nomini	V;SBJV;SG;3;PRS
cargolar	cargolaries	V;COND;SG;2
comentar	comentem	V;IND;PL;1;PRS
enfadar	enfadareu	V;IND;PL;2;FUT
magnetitzar	magnetitzà	V;PFV;IND;SG;3;PST
temptar	tempteu	V;SBJV;PL;2;PRS
assenyalar	assenyaleu	V;SBJV;PL;2;PRS
manllevar	manllevaré	V;IND;SG;1;FUT
culminar	culminin	V;SBJV;PL;3;PRS
assenyalar	assenyaléssim	V;SBJV;PL;1;PST
contradir	contradiguis	V;SBJV;SG;2;PRS
marejar	marejareu	V;IND;PL;2;FUT
embriagar-se	embriagueu	V;IMP;PL;2;POS
allargar	allarguéssiu	V;SBJV;PL;2;PST
encallar-se	encallem	V;IND;PL;1;PRS
forçar	forçarem	V;IND;PL;1;FUT
orbitar	orbiten	V;IND;PL;3;PRS
imprimir	imprimírem	V;PFV;IND;PL;1;PST
xopar	xopes	V;IND;SG;2;PRS
dormir	dormíssiu	V;SBJV;PL;2;PST
lloar	lloàveu	V;IPFV;IND;PL;2;PST
gustar	gusti	V;SBJV;SG;1;PRS
constituir	constituïm	V;SBJV;PL;1;PRS
detectar	detectarem	V;IND;PL;1;FUT
equivocar-se	equivoqui	V;IMP;SG;3;POS
purificar	purificaries	V;COND;SG;2
digerir	digeríeu	V;IPFV;IND;PL;2;PST
casar	casem	V;IMP;PL;1;POS
adreçar	adreça	V;IND;SG;3;PRS
assumir	assumís	V;SBJV;SG;3;PST
absorbir	absorbirà	V;IND;SG;3;FUT
proposar	proposaran	V;IND;PL;3;FUT
ensopir	ensopiu	V;IND;PL;2;PRS
signar	signo	V;IND;SG;1;PRS
cagar	cagares	V;PFV;IND;SG;2;PST
memoritzar	memoritzàreu	V;PFV;IND;PL;2;PST
onejar	onegessis	V;SBJV;SG;2;PST
pactar	pactà	V;PFV;IND;SG;3;PST
expandir	expandírem	V;PFV;IND;PL;1;PST
sospitar	sospitàvem	V;IPFV;IND;PL;1;PST
haver	hagués	V;SBJV;SG;1;PST
graduar	graduï	V;IMP;SG;3;POS
aprofitar	aprofitaren	V;PFV;IND;PL;3;PST
afirmar	afirmés	V;SBJV;SG;3;PST
espolsar	espolsés	V;SBJV;SG;1;PST
falsejar	falsegi	V;SBJV;SG;1;PRS
digitalitzar	digitalitzem	V;IND;PL;1;PRS
simbolitzar	simbolitzàvem	V;IPFV;IND;PL;1;PST
arriscar	arriscares	V;PFV;IND;SG;2;PST
reflectir	reflecteixi	V;SBJV;SG;1;PRS
neutralitzar	neutralitzaríeu	V;COND;PL;2
portar	portàrem	V;PFV;IND;PL;1;PST
romandre	romanguessis	V;SBJV;SG;2;PST
plorar	ploraríem	V;COND;PL;1
terroritzar	terroritzeu	V;IMP;PL;2;POS
impulsar	impulsarà	V;IND;SG;3;FUT
casar	casares	V;PFV;IND;SG;2;PST
emascular	emasculà	V;PFV;IND;SG;3;PST
empapussar	empapussaries	V;COND;SG;2
adormir	adormiràs	V;IND;SG;2;FUT
pondre	pondríeu	V;COND;PL;2
compartir	compartia	V;IPFV;IND;SG;3;PST
limitar	limiti	V;SBJV;SG;3;PRS
atraure	atraureu	V;IND;PL;2;FUT
desenvolupar	desenvolupen	V;IND;PL;3;PRS
gravar	gravéssim	V;SBJV;PL;1;PST
unflar	unfleu	V;IND;PL;2;PRS
velaritzar	velaritzaré	V;IND;SG;1;FUT
grapejar	grapejàrem	V;PFV;IND;PL;1;PST
vulcanitzar	vulcanitzares	V;PFV;IND;SG;2;PST
atendre	atenen	V;IND;PL;3;PRS
malvendre	malvengui	V;SBJV;SG;3;PRS
admirar	admirem	V;IND;PL;1;PRS
boicotejar	boicotejo	V;IND;SG;1;PRS
salar	salessis	V;SBJV;SG;2;PST
segrestar	segrestaré	V;IND;SG;1;FUT
renillar	renillaran	V;IND;PL;3;FUT
banyar	banyaríeu	V;COND;PL;2
sondejar	sondeja	V;IMP;SG;2;POS
polir	políssim	V;SBJV;PL;1;PST
avantatjar	avantatjaren	V;PFV;IND;PL;3;PST
difamar	difamaríeu	V;COND;PL;2
regular	circulà	V;PFV;IND;SG;3;PST
anhelar	anhelessin	V;SBJV;PL;3;PST
correspondre	correspondràs	V;IND;SG;2;FUT
obliquar	obliquï	V;IMP;SG;3;POS
llevar	llevaré	V;IND;SG;1;FUT
etiquetar	etiquetaré	V;IND;SG;1;FUT
solidificar	solidificàvem	V;IPFV;IND;PL;1;PST
exhalar	exhalà	V;PFV;IND;SG;3;PST
armar	armarem	V;IND;PL;1;FUT
collir	colliràs	V;IND;SG;2;FUT
descentralitzar	descentralitzaríem	V;COND;PL;1
encunyar	encunyarà	V;IND;SG;3;FUT
partir	partim	V;SBJV;PL;1;PRS
debilitar	debilitarien	V;COND;PL;3
magnetitzar	magnetitzéssim	V;SBJV;PL;1;PST
estiuejar	estiuegeu	V;IMP;PL;2;POS
asseure	asseuran	V;IND;PL;3;FUT
preguntar-se	preguntés	V;SBJV;SG;3;PST
confiar	confiaries	V;COND;SG;2
prendre	prenen	V;IND;PL;3;PRS
equivocar	equivoquin	V;IMP;PL;3;POS
involucrar	involucràrem	V;PFV;IND;PL;1;PST
armar	armeu	V;IND;PL;2;PRS
tremolar	tremolí	V;PFV;IND;SG;1;PST
refondre	refongui	V;SBJV;SG;1;PRS
reflectir	reflectírem	V;PFV;IND;PL;1;PST
abolir	aboleixi	V;SBJV;SG;1;PRS
digerir	digereixi	V;SBJV;SG;3;PRS
perfumar	perfuma	V;IMP;SG;2;POS
maleir	maleiria	V;COND;SG;3
condemnar	condemnarem	V;IND;PL;1;FUT
sorprendre	sorprendrien	V;COND;PL;3
salvar	salvi	V;SBJV;SG;1;PRS
captivar	captivin	V;SBJV;PL;3;PRS
aproximar	aproximàvem	V;IPFV;IND;PL;1;PST
diagnosticar	diagnosticareu	V;IND;PL;2;FUT
remenar	remenareu	V;IND;PL;2;FUT
inflar	infleu	V;SBJV;PL;2;PRS
pescar	pescarà	V;IND;SG;3;FUT
despertar-se	despertaré	V;IND;SG;1;FUT
lloar	lloaria	V;COND;SG;3
distendre	distenguessin	V;SBJV;PL;3;PST
abolir	aboleixen	V;IND;PL;3;PRS
penjar	pengi	V;SBJV;SG;1;PRS
permetre	permetíem	V;IPFV;IND;PL;1;PST
davallar	davallà	V;PFV;IND;SG;3;PST
correspondre	correspondreu	V;IND;PL;2;FUT
ennuvolar-se	ennuvoléssim	V;SBJV;PL;1;PST
tricotar	tricotéssiu	V;SBJV;PL;2;PST
incloure	incloguin	V;SBJV;PL;3;PRS
centralitzar	centralitzaríem	V;COND;PL;1
vehicular	vehiculeu	V;SBJV;PL;2;PRS
atacar	ataca	V;IMP;SG;2;POS
preocupar	preocuparem	V;IND;PL;1;FUT
compilar	compileu	V;IND;PL;2;PRS
memoritzar	memoritzi	V;SBJV;SG;3;PRS
denominar	denominarà	V;IND;SG;3;FUT
beneficiar	beneficiessis	V;SBJV;SG;2;PST
empresonar	empresonaves	V;IPFV;IND;SG;2;PST
profunditzar	profunditzessis	V;SBJV;SG;2;PST
encallar-se	encallaven	V;IPFV;IND;PL;3;PST
segregar	segregaràs	V;IND;SG;2;FUT
associar	associem	V;IND;PL;1;PRS
infeccionar	infeccionin	V;SBJV;PL;3;PRS
prioritzar	prioritzí	V;PFV;IND;SG;1;PST
salar	salis	V;SBJV;SG;2;PRS
gustar	gustaves	V;IPFV;IND;SG;2;PST
guiar	guiaria	V;COND;SG;3
digitalitzar	digitalitzaríem	V;COND;PL;1
apreciar	aprecien	V;IND;PL;3;PRS
diagnosticar	diagnosticaria	V;COND;SG;3
empresonar	empresoni	V;IMP;SG;3;POS
intersectar	intersectava	V;IPFV;IND;SG;1;PST
sostenir	sostindria	V;COND;SG;1
renillar	renilléssim	V;SBJV;PL;1;PST
imitar	imitessis	V;SBJV;SG;2;PST
enfocar	enfocà	V;PFV;IND;SG;3;PST
polir	poleixen	V;IND;PL;3;PRS
bombardejar	bombardegis	V;SBJV;SG;2;PRS
segrestar	segrestaren	V;PFV;IND;PL;3;PST
comentar	comenti	V;SBJV;SG;3;PRS
creure	creuen	V;IND;PL;3;PRS
envoltar	envoltaràs	V;IND;SG;2;FUT
gravar	gravàrem	V;PFV;IND;PL;1;PST
distribuir	distribuiríem	V;COND;PL;1
harmonitzar	harmonitzéssim	V;SBJV;PL;1;PST
regar	reguessin	V;SBJV;PL;3;PST
halar	halar	V;NFIN
estalviar	estalviïn	V;SBJV;PL;3;PRS
tornar-se	tornin	V;SBJV;PL;3;PRS
recollir	recollírem	V;PFV;IND;PL;1;PST
aidar	aidem	V;IMP;PL;1;POS
cuidar	cuidis	V;SBJV;SG;2;PRS
escandalitzar	escandalitzaríem	V;COND;PL;1
universalitzar	universalitza	V;IND;SG;3;PRS
beure	beguéreu	V;PFV;IND;PL;2;PST
exterminar	extermino	V;IND;SG;1;PRS
insurreccionar	insurreccionareu	V;IND;PL;2;FUT
uniformar	uniformàvem	V;IPFV;IND;PL;1;PST
suspendre	suspeníeu	V;IPFV;IND;PL;2;PST
digitalitzar	digitalitzaré	V;IND;SG;1;FUT
vaporitzar	vaporitzeu	V;SBJV;PL;2;PRS
adorar	adoréssim	V;SBJV;PL;1;PST
unir-se	unien	V;IPFV;IND;PL;3;PST
infeccionar	infeccionaries	V;COND;SG;2
falsejar	falsegi	V;SBJV;SG;3;PRS
detectar	detectis	V;SBJV;SG;2;PRS
esclafar	esclafaria	V;COND;SG;3
raucar	rauca	V;IMP;SG;2;POS
practicar	practica	V;IMP;SG;2;POS
apunyalar	apunyaléssim	V;SBJV;PL;1;PST
aturar	aturà	V;PFV;IND;SG;3;PST
sodomitzar	sodomitzés	V;SBJV;SG;1;PST
exercir	exercirà	V;IND;SG;3;FUT
teoritzar	teoritzaràs	V;IND;SG;2;FUT
adormir	adormí	V;PFV;IND;SG;3;PST
abatre	abatessis	V;SBJV;SG;2;PST
flairar	flairin	V;IMP;PL;3;POS
pronunciar	pronunciarem	V;IND;PL;1;FUT
sincronitzar	sincronitzéssiu	V;SBJV;PL;2;PST
difondre	difoníem	V;IPFV;IND;PL;1;PST
sondejar	sondejarem	V;IND;PL;1;FUT
esquitxar	esquitxi	V;SBJV;SG;1;PRS
perdonar	perdonaràs	V;IND;SG;2;FUT
associar	associàrem	V;PFV;IND;PL;1;PST
eludir	eludim	V;IND;PL;1;PRS
escopir	escopírem	V;PFV;IND;PL;1;PST
eludir	eludeixen	V;IND;PL;3;PRS
hibernar	hibernar	V;NFIN
empapussar-se	empapussis	V;SBJV;SG;2;PRS
laïcitzar	laïcitzaren	V;PFV;IND;PL;3;PST
pretendre	pretenien	V;IPFV;IND;PL;3;PST
infiltrar	infiltràreu	V;PFV;IND;PL;2;PST
perpetrar	perpetrava	V;IPFV;IND;SG;3;PST
exigir	exigir	V;NFIN
elegir	elegíreu	V;PFV;IND;PL;2;PST
polir	poleixi	V;IMP;SG;3;POS
organitzar	organitzaria	V;COND;SG;1
asseure's	s'asseu	V;IND;SG;3;PRS
transgredir	transgredeixis	V;SBJV;SG;2;PRS
profunditzar	profunditzaré	V;IND;SG;1;FUT
castrar	castrar	V;NFIN
asseure's	t'asseguis	V;SBJV;SG;2;PRS
exercir	exerciu	V;IMP;PL;2;POS
graduar	graduïs	V;SBJV;SG;2;PRS
pregar	pregaren	V;PFV;IND;PL;3;PST
patir	patíssim	V;SBJV;PL;1;PST
perfumar	perfumar	V;NFIN
sonar	sones	V;IND;SG;2;PRS
enfocar	enfocàreu	V;PFV;IND;PL;2;PST
pronunciar	pronunciéssiu	V;SBJV;PL;2;PST
cobrir	cobriré	V;IND;SG;1;FUT
remuntar	remuntés	V;SBJV;SG;1;PST
saber	sabéssiu	V;SBJV;PL;2;PST
reprendre	reprens	V;IND;SG;2;PRS
refinar	refinaven	V;IPFV;IND;PL;3;PST
preguntar	preguntin	V;IMP;PL;3;POS
emprendre	empreneu	V;IND;PL;2;PRS
esdevenir	esdevinguérem	V;PFV;IND;PL;1;PST
romandre	romania	V;IPFV;IND;SG;1;PST
mesclar	mesclaríeu	V;COND;PL;2
esgarrapar	esgarrapeu	V;IND;PL;2;PRS
partir	parteixi	V;SBJV;SG;3;PRS
desodorar	desodori	V;IMP;SG;3;POS
balcanitzar	balcanitzareu	V;IND;PL;2;FUT
pronunciar	pronunciaves	V;IPFV;IND;SG;2;PST
recomençar	recomenci	V;IMP;SG;3;POS
difondre	difongui	V;SBJV;SG;1;PRS
apostar	apostaven	V;IPFV;IND;PL;3;PST
diagnosticar	diagnostica	V;IMP;SG;2;POS
negar	negui	V;IMP;SG;3;POS
telefonar	telefonés	V;SBJV;SG;1;PST
elegir	elegeixes	V;IND;SG;2;PRS
reiterar	reiteràvem	V;IPFV;IND;PL;1;PST
entretenir	entreté	V;IMP;SG;2;POS
penetrar	penetres	V;IND;SG;2;PRS
exigir	exigim	V;SBJV;PL;1;PRS
flairar	flairí	V;PFV;IND;SG;1;PST
boxar	boxaria	V;COND;SG;3
correspondre	correspondrà	V;IND;SG;3;FUT
caure	caigueren	V;PFV;IND;PL;3;PST
animar	animareu	V;IND;PL;2;FUT
memoritzar	memoritzéssiu	V;SBJV;PL;2;PST
datar	datava	V;IPFV;IND;SG;3;PST
tractar	tractava	V;IPFV;IND;SG;3;PST
rescatar	rescato	V;IND;SG;1;PRS
avantatjar	avantatgem	V;IMP;PL;1;POS
requerir	requeriràs	V;IND;SG;2;FUT
reviscolar	reviscola	V;IND;SG;3;PRS
partir	partírem	V;PFV;IND;PL;1;PST
sostenir	sostindries	V;COND;SG;2
estimar	estimaven	V;IPFV;IND;PL;3;PST
cantar	cantarem	V;IND;PL;1;FUT
alletar	alletava	V;IPFV;IND;SG;1;PST
refinar	refinàrem	V;PFV;IND;PL;1;PST
jaquir	jaquírem	V;PFV;IND;PL;1;PST
ser	fou	V;PFV;IND;SG;3;PST
cessar	cessi	V;SBJV;SG;1;PRS
denominar	denominàreu	V;PFV;IND;PL;2;PST
rescatar	rescatàrem	V;PFV;IND;PL;1;PST
destripar	destripava	V;IPFV;IND;SG;1;PST
integrar	integrin	V;IMP;PL;3;POS
devorar	devorar	V;NFIN
maquillar	maquilleu	V;IMP;PL;2;POS
foradar	foradem	V;IMP;PL;1;POS
conspirar	conspirés	V;SBJV;SG;1;PST
justificar	justifiquem	V;IND;PL;1;PRS
passar-se	passava	V;IPFV;IND;SG;3;PST
cobrir	cobreix	V;IMP;SG;2;POS
popularitzar	popularitzava	V;IPFV;IND;SG;3;PST
olorar	oloréssiu	V;SBJV;PL;2;PST
emmascarar	emmascaressin	V;SBJV;PL;3;PST
profunditzar	profunditzes	V;IND;SG;2;PRS
subjectivar	subjectiveu	V;IND;PL;2;PRS
nevar	nevàrem	V;PFV;IND;PL;1;PST
anhelar	anheli	V;SBJV;SG;3;PRS
saber	sabem	V;IND;PL;1;PRS
mesurar	mesuraria	V;COND;SG;1
harmonitzar	harmonitza	V;IND;SG;3;PRS
mesurar	mesuraré	V;IND;SG;1;FUT
afirmar	afirmen	V;IND;PL;3;PRS
atemptar	atempten	V;IND;PL;3;PRS
escandalitzar	escandalitzares	V;PFV;IND;SG;2;PST
excedir	excedires	V;PFV;IND;SG;2;PST
atrevir-se	atreviríem	V;COND;PL;1
recomençar	recomencí	V;PFV;IND;SG;1;PST
carregar	carregaríem	V;COND;PL;1
contaminar	contaminessin	V;SBJV;PL;3;PST
agrair	agraís	V;SBJV;SG;1;PST
xiular	xiulà	V;PFV;IND;SG;3;PST
neutralitzar	neutralitzaràs	V;IND;SG;2;FUT
comunicar	comuniqui	V;SBJV;SG;1;PRS
menjar	menjareu	V;IND;PL;2;FUT
prioritzar	prioritzaven	V;IPFV;IND;PL;3;PST
hibernar	hibernaríem	V;COND;PL;1
manllevar	manllevàveu	V;IPFV;IND;PL;2;PST
manar	manés	V;SBJV;SG;3;PST
empènyer	empenyem	V;SBJV;PL;1;PRS
destinar	destinarien	V;COND;PL;3
entrevistar	entrevistarem	V;IND;PL;1;FUT
dimitir	dimitissis	V;SBJV;SG;2;PST
apunyalar	apunyalés	V;SBJV;SG;1;PST
grapejar	grapegen	V;IND;PL;3;PRS
renillar	renillàrem	V;PFV;IND;PL;1;PST
justificar	justificaran	V;IND;PL;3;FUT
tacar	taques	V;IND;SG;2;PRS
deshumanitzar	deshumanitzà	V;PFV;IND;SG;3;PST
dirimir	dirimís	V;SBJV;SG;3;PST
cagar	caga	V;IMP;SG;2;POS
precisar	precisi	V;SBJV;SG;1;PRS
adorar	adoraria	V;COND;SG;3
llançar	llancem	V;IND;PL;1;PRS
incorporar	incorporí	V;PFV;IND;SG;1;PST
aixecar	aixecàveu	V;IPFV;IND;PL;2;PST
ofendre	ofenen	V;IND;PL;3;PRS
polir	poliré	V;IND;SG;1;FUT
propiciar	propiciàvem	V;IPFV;IND;PL;1;PST
propiciar	propiciïs	V;SBJV;SG;2;PRS
eliminar	eliminaven	V;IPFV;IND;PL;3;PST
esgarrapar	esgarrapem	V;SBJV;PL;1;PRS
inscriure	inscrivia	V;IPFV;IND;SG;3;PST
penetrar	penetraríeu	V;COND;PL;2
calcular	calcularan	V;IND;PL;3;FUT
assemblar	assemblaré	V;IND;SG;1;FUT
encórrer	encorrem	V;IMP;PL;1;POS
plegar	plegarem	V;IND;PL;1;FUT
pensar	pensis	V;SBJV;SG;2;PRS
raucar	raucaríem	V;COND;PL;1
reemplaçar	reemplaçà	V;PFV;IND;SG;3;PST
oscil·lar	oscil·larem	V;IND;PL;1;FUT
col·laborar	col·laborí	V;PFV;IND;SG;1;PST
avantatjar	avantatjava	V;IPFV;IND;SG;1;PST
compartir	compartim	V;IMP;PL;1;POS
plegar	plegaren	V;PFV;IND;PL;3;PST
anticipar	anticipéssim	V;SBJV;PL;1;PST
veure's	es veuran	V;IND;PL;3;FUT
entretenir	entretenim	V;IND;PL;1;PRS
onejar	onegeu	V;SBJV;PL;2;PRS
doblar	doblin	V;IMP;PL;3;POS
romandre	romanguem	V;SBJV;PL;1;PRS
escollir	escollissis	V;SBJV;SG;2;PST
compartir	compartiré	V;IND;SG;1;FUT
miolar	miolar	V;NFIN
estimular	estimularies	V;COND;SG;2
acordar	acordaven	V;IPFV;IND;PL;3;PST
enviar	enviessin	V;SBJV;PL;3;PST
respectar	respectàveu	V;IPFV;IND;PL;2;PST
distribuir	distribuïu	V;IND;PL;2;PRS
sacsejar	sacsegí	V;PFV;IND;SG;1;PST
travessar	travessareu	V;IND;PL;2;FUT
denominar	denominessin	V;SBJV;PL;3;PST
degradar	degrades	V;IND;SG;2;PRS
semblar	semblessis	V;SBJV;SG;2;PST
allotjar	allotgéssim	V;SBJV;PL;1;PST
exigir	exigissin	V;SBJV;PL;3;PST
corprendre	corpreneu	V;IMP;PL;2;POS
memoritzar	memoritzaran	V;IND;PL;3;FUT
dialogar	dialogaves	V;IPFV;IND;SG;2;PST
circumnavegar	circumnaveguéssim	V;SBJV;PL;1;PST
impetrar	impetréssiu	V;SBJV;PL;2;PST
onejar	oneja	V;IND;SG;3;PRS
davallar	davalleu	V;SBJV;PL;2;PRS
empresonar	empresonin	V;IMP;PL;3;POS
equivocar	equivocarà	V;IND;SG;3;FUT
retornar	retornéssim	V;SBJV;PL;1;PST
pretendre	pretendrien	V;COND;PL;3
graduar	graduaran	V;IND;PL;3;FUT
inventar	inventessin	V;SBJV;PL;3;PST
racionalitzar	racionalitzaríem	V;COND;PL;1
enterrar	enterris	V;SBJV;SG;2;PRS
exercir	exercíeu	V;IPFV;IND;PL;2;PST
buidar	buidaria	V;COND;SG;3
escopir	escopí	V;PFV;IND;SG;1;PST
disposar	disposà	V;PFV;IND;SG;3;PST
vehicular	vehiculem	V;IND;PL;1;PRS
vendre	vendre	V;NFIN
nedar	nedi	V;IMP;SG;3;POS
conversar	conversàvem	V;IPFV;IND;PL;1;PST
verificar	verificar	V;NFIN
contribuir	contribuíreu	V;PFV;IND;PL;2;PST
plorar	ploràrem	V;PFV;IND;PL;1;PST
marejar	marejaria	V;COND;SG;3
xafardejar	xafardegi	V;IMP;SG;3;POS
ensordir	ensordia	V;IPFV;IND;SG;3;PST
imprimir	imprimeixi	V;IMP;SG;3;POS
reinicialitzar	reinicialitzareu	V;IND;PL;2;FUT
experimentar	experimentaves	V;IPFV;IND;SG;2;PST
acreditar	acredità	V;PFV;IND;SG;3;PST
vincular	vincularem	V;IND;PL;1;FUT
forçar	forcessis	V;SBJV;SG;2;PST
trivialitzar	trivialitzin	V;SBJV;PL;3;PRS
posposar	posposarien	V;COND;PL;3
enterrar	enterri	V;IMP;SG;3;POS
convocar	convocaràs	V;IND;SG;2;FUT
xatejar	xategí	V;PFV;IND;SG;1;PST
atrevir-se	atreveixes	V;IND;SG;2;PRS
assetjar	assetjàvem	V;IPFV;IND;PL;1;PST
espaventar	espaventin	V;IMP;PL;3;POS
relaxar	relaxes	V;IND;SG;2;PRS
remoldre	remols	V;IND;SG;2;PRS
representar	representares	V;PFV;IND;SG;2;PST
sorgir	sorgim	V;IMP;PL;1;POS
evolucionar	evolucionaríem	V;COND;PL;1
ridiculitzar	ridiculitzàrem	V;PFV;IND;PL;1;PST
salar	saléssim	V;SBJV;PL;1;PST
vincular	vincularia	V;COND;SG;1
domar	domaren	V;PFV;IND;PL;3;PST
passar	passa	V;IMP;SG;2;POS
complir	compliries	V;COND;SG;2
embrutar	embrutem	V;IND;PL;1;PRS
firmar	firmeu	V;SBJV;PL;2;PRS
negar	negaré	V;IND;SG;1;FUT
digerir	digerim	V;SBJV;PL;1;PRS
universalitzar	universalitzàrem	V;PFV;IND;PL;1;PST
oblidar	oblidi	V;SBJV;SG;3;PRS
importar	importi	V;IMP;SG;3;POS
emmagatzemar	emmagatzemaríem	V;COND;PL;1
expandir	expandeixes	V;IND;SG;2;PRS
erigir	erigíem	V;IPFV;IND;PL;1;PST
encendre	encenguessis	V;SBJV;SG;2;PST
refinar	refinessin	V;SBJV;PL;3;PST
verificar	verifico	V;IND;SG;1;PRS
compilar	compilarien	V;COND;PL;3
honrar	honraves	V;IPFV;IND;SG;2;PST
idolatrar	idolatreu	V;SBJV;PL;2;PRS
acorralar	acorralaries	V;COND;SG;2
terroritzar	terroritzaria	V;COND;SG;3
estirar	estiraríeu	V;COND;PL;2
polir	poliria	V;COND;SG;3
captivar	captivarien	V;COND;PL;3
compartir	compartiràs	V;IND;SG;2;FUT
balcanitzar	balcanitzéssiu	V;SBJV;PL;2;PST
intimidar	intimidis	V;SBJV;SG;2;PRS
vendre	vens	V;IND;SG;2;PRS
patir	patíeu	V;IPFV;IND;PL;2;PST
gravar	gravàreu	V;PFV;IND;PL;2;PST
devorar	devorem	V;SBJV;PL;1;PRS
conceptualitzar	conceptualitzeu	V;IMP;PL;2;POS
vexar	vexaves	V;IPFV;IND;SG;2;PST
beure	begueren	V;PFV;IND;PL;3;PST
preocupar	preocupa	V;IMP;SG;2;POS
notar	notaríeu	V;COND;PL;2
carregar	carregaven	V;IPFV;IND;PL;3;PST
crear	crearia	V;COND;SG;3
prevenir	prevenir	V;NFIN
relacionar	relacionar	V;NFIN
embrutar	embrutaríem	V;COND;PL;1
enterrar	enterrés	V;SBJV;SG;3;PST
vaporitzar	vaporitzaràs	V;IND;SG;2;FUT
regular	circulin	V;IMP;PL;3;POS
desenvolupar	desenvolupeu	V;IMP;PL;2;POS
limitar	limitaven	V;IPFV;IND;PL;3;PST
encallar	encallareu	V;IND;PL;2;FUT
abolir	abolís	V;SBJV;SG;3;PST
oscil·lar	oscil·laves	V;IPFV;IND;SG;2;PST
interrompre	interrompéssim	V;SBJV;PL;1;PST
conservar	conservaràs	V;IND;SG;2;FUT
abreujar	abreugeu	V;IMP;PL;2;POS
gratar	gratessis	V;SBJV;SG;2;PST
tacar	tacàveu	V;IPFV;IND;PL;2;PST
ploure	ploveu	V;IND;PL;2;PRS
debutar	debutaríeu	V;COND;PL;2
semblar	semblaran	V;IND;PL;3;FUT
maleir	maleí	V;PFV;IND;SG;3;PST
escandalitzar	escandalitzem	V;IMP;PL;1;POS
celebrar	celebren	V;IND;PL;3;PRS
pactar	pactaries	V;COND;SG;2
exercir	exercí	V;PFV;IND;SG;3;PST
xocar	xoqui	V;IMP;SG;3;POS
entretenir	entretindran	V;IND;PL;3;FUT
impetrar	impetréssim	V;SBJV;PL;1;PST
reelegir	reelegim	V;SBJV;PL;1;PRS
sodomitzar	sodomitzava	V;IPFV;IND;SG;3;PST
telefonar	telefonessis	V;SBJV;SG;2;PST
relatar	relataves	V;IPFV;IND;SG;2;PST
nominar	nominessis	V;SBJV;SG;2;PST
regnar	regnaria	V;COND;SG;3
estiuejar	estiuejaríeu	V;COND;PL;2
disparar	dispares	V;IND;SG;2;PRS
redimir	redimim	V;IND;PL;1;PRS
dispersar	disperseu	V;IMP;PL;2;POS
assassinar	assassinar	V;NFIN
enterrar	enterrà	V;PFV;IND;SG;3;PST
celebrar	celebrem	V;IMP;PL;1;POS
xarrupar	xarrupés	V;SBJV;SG;3;PST
admetre	admets	V;IND;SG;2;PRS
malvendre	malvendria	V;COND;SG;1
introduir	introduiríeu	V;COND;PL;2
miolar	miolaríem	V;COND;PL;1
assenyalar	assenyalessin	V;SBJV;PL;3;PST
insistir	insisteixis	V;SBJV;SG;2;PRS
retornar	retornem	V;IMP;PL;1;POS
complir	compleixen	V;IND;PL;3;PRS
espiar	espien	V;IND;PL;3;PRS
constituir	constitueix	V;IMP;SG;2;POS
anticipar	anticipis	V;SBJV;SG;2;PRS
autoritzar	autoritzo	V;IND;SG;1;PRS
inhumar	inhumí	V;PFV;IND;SG;1;PST
vincular	vincula	V;IMP;SG;2;POS
manar	manin	V;IMP;PL;3;POS
gratar	grati	V;SBJV;SG;3;PRS
precisar	precisaran	V;IND;PL;3;FUT
guardonar	guardono	V;IND;SG;1;PRS
menysprear	menyspreï	V;SBJV;SG;3;PRS
alletar	alletaven	V;IPFV;IND;PL;3;PST
distendre	distenguin	V;IMP;PL;3;POS
apreciar	apreciaràs	V;IND;SG;2;FUT
esgatinyar-se	esgatinyessin	V;SBJV;PL;3;PST
refondre	refonem	V;IND;PL;1;PRS
cantar	cantaríeu	V;COND;PL;2
casar-se	casarien	V;COND;PL;3
pensar	pensen	V;IND;PL;3;PRS
inclinar	inclinaves	V;IPFV;IND;SG;2;PST
exterminar	exterminaries	V;COND;SG;2
trinxar	trinxí	V;PFV;IND;SG;1;PST
posposar	posposen	V;IND;PL;3;PRS
aproximar	aproximessis	V;SBJV;SG;2;PST
pudir	pudíssiu	V;SBJV;PL;2;PST
laïcitzar	laïcitzaves	V;IPFV;IND;SG;2;PST
adreçar	adreçar	V;NFIN
privar	privi	V;IMP;SG;3;POS
excedir	excediu	V;IND;PL;2;PRS
elegir	elegiré	V;IND;SG;1;FUT
vacil·lar	vacil·lar	V;NFIN
signar	signaria	V;COND;SG;1
tocar	tocàreu	V;PFV;IND;PL;2;PST
rendir	rendim	V;IMP;PL;1;POS
hospitalitzar	hospitalitzeu	V;IMP;PL;2;POS
desembarcar	desembarcà	V;PFV;IND;SG;3;PST
cuinar	cuinaria	V;COND;SG;1
extreure	extreguis	V;SBJV;SG;2;PRS
extreure	extragués	V;SBJV;SG;1;PST
acollir	acull	V;IND;SG;3;PRS
domar	domen	V;IND;PL;3;PRS
perdonar	perdoneu	V;SBJV;PL;2;PRS
cargolar	cargolaran	V;IND;PL;3;FUT
organitzar	organitzaren	V;PFV;IND;PL;3;PST
exhalar	exhalessis	V;SBJV;SG;2;PST
ennuvolar-se	ennuvolaríem	V;COND;PL;1
simular	simulis	V;SBJV;SG;2;PRS
adaptar	adapta	V;IND;SG;3;PRS
transportar	transportarien	V;COND;PL;3
funcionar	funcionaven	V;IPFV;IND;PL;3;PST
alternar	alterna	V;IND;SG;3;PRS
mutar	muti	V;IMP;SG;3;POS
punxar	punxis	V;SBJV;SG;2;PRS
divulgar	divulguessin	V;SBJV;PL;3;PST
carregar	carregaré	V;IND;SG;1;FUT
allargar	allargui	V;SBJV;SG;3;PRS
exiliar	exiliava	V;IPFV;IND;SG;1;PST
conjuntar	conjuntaren	V;PFV;IND;PL;3;PST
foradar	foradaria	V;COND;SG;1
encapçalar	encapçali	V;IMP;SG;3;POS
torturar	torturar	V;NFIN
prestar	prestareu	V;IND;PL;2;FUT
aromar	aromaren	V;PFV;IND;PL;3;PST
telefonar	telefonàvem	V;IPFV;IND;PL;1;PST
transferir	transferí	V;PFV;IND;SG;3;PST
obeir	obeïm	V;IND;PL;1;PRS
assemblar	assemblo	V;IND;SG;1;PRS
assemblar	assemblés	V;SBJV;SG;3;PST
poder	puguis	V;SBJV;SG;2;PRS
rejovenir	rejoveniria	V;COND;SG;1
estiuejar	estiuejaven	V;IPFV;IND;PL;3;PST
submergir	submergí	V;PFV;IND;SG;1;PST
rotar	roteu	V;IMP;PL;2;POS
negar	negarem	V;IND;PL;1;FUT
guiar	guiarà	V;IND;SG;3;FUT
vetllar	vetllo	V;IND;SG;1;PRS
terroritzar	terroritzi	V;SBJV;SG;1;PRS
cuidar	cuidessin	V;SBJV;PL;3;PST
boicotejar	boicoteges	V;IND;SG;2;PRS
vexar	vexéssiu	V;SBJV;PL;2;PST
travessar	travessi	V;SBJV;SG;1;PRS
reemplaçar	reemplacis	V;SBJV;SG;2;PRS
tancar	tancaràs	V;IND;SG;2;FUT
investigar	investigava	V;IPFV;IND;SG;1;PST
cobrar	cobréssim	V;SBJV;PL;1;PST
inclinar	inclinarà	V;IND;SG;3;FUT
col·laborar	col·laboris	V;SBJV;SG;2;PRS
dissuadir	dissuadim	V;IMP;PL;1;POS
jaquir	jaquissis	V;SBJV;SG;2;PST
tallar	tallés	V;SBJV;SG;1;PST
desautoritzar	desautoritzessis	V;SBJV;SG;2;PST
udolar	udolaràs	V;IND;SG;2;FUT
equivocar-se	equivoqui	V;SBJV;SG;3;PRS
davallar	davallem	V;IND;PL;1;PRS
ancorar	ancorà	V;PFV;IND;SG;3;PST
especialitzar	especialitzaré	V;IND;SG;1;FUT
signar	signessis	V;SBJV;SG;2;PST
infeccionar	infeccionin	V;IMP;PL;3;POS
acorralar	acorralo	V;IND;SG;1;PRS
privar	privarem	V;IND;PL;1;FUT
dificultar	dificultaren	V;PFV;IND;PL;3;PST
humanitzar	humanitzi	V;SBJV;SG;3;PRS
autoritzar	autoritzéssiu	V;SBJV;PL;2;PST
pensar	penso	V;IND;SG;1;PRS
perfumar	perfumés	V;SBJV;SG;3;PST
acostar	acostaven	V;IPFV;IND;PL;3;PST
constituir	constituíeu	V;IPFV;IND;PL;2;PST
conservar	conservis	V;SBJV;SG;2;PRS
inventar	inventis	V;SBJV;SG;2;PRS
despertar-se	despertaria	V;COND;SG;1
empapussar	empapussem	V;IND;PL;1;PRS
pair	pairé	V;IND;SG;1;FUT
codificar	codifiqueu	V;IMP;PL;2;POS
pactar	pactàreu	V;PFV;IND;PL;2;PST
avorrir	avorrirà	V;IND;SG;3;FUT
enviar	enviaran	V;IND;PL;3;FUT
mullar	mullo	V;IND;SG;1;PRS
significar	signifiquí	V;PFV;IND;SG;1;PST
dirimir	dirimirien	V;COND;PL;3
adoptar	adoptaria	V;COND;SG;3
romandre	romangui	V;SBJV;SG;3;PRS
constituir	constituir	V;NFIN
distanciar	distanciaran	V;IND;PL;3;FUT
debutar	debutava	V;IPFV;IND;SG;1;PST
ofendre	ofeneu	V;IMP;PL;2;POS
ridiculitzar	ridiculitzaries	V;COND;SG;2
cristal·litzar	cristal·litzin	V;SBJV;PL;3;PRS
renunciar	renuncií	V;PFV;IND;SG;1;PST
excedir	excedeixin	V;SBJV;PL;3;PRS
perfeccionar	perfeccionaves	V;IPFV;IND;SG;2;PST
hesitar	hesiteu	V;IMP;PL;2;POS
halar	halarà	V;IND;SG;3;FUT
ennuvolar-se	ennuvolaries	V;COND;SG;2
colonitzar	colonitzéssiu	V;SBJV;PL;2;PST
alternar	alternares	V;PFV;IND;SG;2;PST
escalar	escaleu	V;IMP;PL;2;POS
assolar	assoléssim	V;SBJV;PL;1;PST
ancorar	ancores	V;IND;SG;2;PRS
refutar	refutés	V;SBJV;SG;3;PST
apostar	apostarien	V;COND;PL;3
revoltar	revoltés	V;SBJV;SG;1;PST
debilitar	debilito	V;IND;SG;1;PRS
conjuntar	conjuntarem	V;IND;PL;1;FUT
emmagatzemar	emmagatzemeu	V;IMP;PL;2;POS
alternar	alternaria	V;COND;SG;1
criticar	critiqués	V;SBJV;SG;3;PST
telefonar	telefoní	V;PFV;IND;SG;1;PST
forçar	forci	V;IMP;SG;3;POS
arrestar	arrestéssiu	V;SBJV;PL;2;PST
criticar	criticar	V;NFIN
salvar	salvava	V;IPFV;IND;SG;1;PST
aguaitar	aguaitin	V;SBJV;PL;3;PRS
enterrar	enterrés	V;SBJV;SG;1;PST
rentar	rentar	V;NFIN
qüestionar	qüestioni	V;IMP;SG;3;POS
ajudar	ajuden	V;IND;PL;3;PRS
idolatrar	idolatraria	V;COND;SG;3
motoritzar	motoritzàveu	V;IPFV;IND;PL;2;PST
fracassar	fracassessis	V;SBJV;SG;2;PST
provocar	provoquin	V;SBJV;PL;3;PRS
desautoritzar	desautoritzàreu	V;PFV;IND;PL;2;PST
perdonar	perdonaríem	V;COND;PL;1
encunyar	encunyéssim	V;SBJV;PL;1;PST
xipollejar	xipollegí	V;PFV;IND;SG;1;PST
reorganitzar	reorganitzem	V;IMP;PL;1;POS
vincular	vinculàreu	V;PFV;IND;PL;2;PST
assemblar	assemblaríeu	V;COND;PL;2
distanciar	distanciem	V;SBJV;PL;1;PRS
dividir	dividirien	V;COND;PL;3
diagnosticar	diagnostiqui	V;SBJV;SG;1;PRS
tallar	tallem	V;IMP;PL;1;POS
planejar	planeja	V;IND;SG;3;PRS
cristal·litzar	cristal·litzaré	V;IND;SG;1;FUT
fendre	fendrem	V;IND;PL;1;FUT
obligar	obligareu	V;IND;PL;2;FUT
intimidar	intimidí	V;PFV;IND;SG;1;PST
xatejar	xatejàreu	V;PFV;IND;PL;2;PST
reemplaçar	reemplacin	V;SBJV;PL;3;PRS
jaquir	jaquires	V;PFV;IND;SG;2;PST
lluitar	lluitàvem	V;IPFV;IND;PL;1;PST
significar	significaríeu	V;COND;PL;2
subestimar	subestimàreu	V;PFV;IND;PL;2;PST
excedir	excedeixin	V;IMP;PL;3;POS
follar	follaria	V;COND;SG;1
naturalitzar	naturalitzeu	V;SBJV;PL;2;PRS
discriminar	discriminàrem	V;PFV;IND;PL;1;PST
estressar	estressaria	V;COND;SG;1
casar	casa	V;IND;SG;3;PRS
agafar	agafem	V;IND;PL;1;PRS
refondre	refons	V;IND;SG;2;PRS
apreciar	apreciava	V;IPFV;IND;SG;1;PST
donar	dono	V;IND;SG;1;PRS
manar	manéssim	V;SBJV;PL;1;PST
halar	hali	V;SBJV;SG;1;PRS
experimentar	experimenti	V;IMP;SG;3;POS
estossegar	estosseguí	V;PFV;IND;SG;1;PST
empapussar	empapusseu	V;SBJV;PL;2;PRS
significar	signifiquin	V;IMP;PL;3;POS
esnifar	esnifàrem	V;PFV;IND;PL;1;PST
refusar	refusàreu	V;PFV;IND;PL;2;PST
seure	seiem	V;IND;PL;1;PRS
negar	neguin	V;SBJV;PL;3;PRS
creuar	creui	V;SBJV;SG;3;PRS
desconèixer	desconeguessin	V;SBJV;PL;3;PST
sagnar	sagnaríeu	V;COND;PL;2
harmonitzar	harmonitzés	V;SBJV;SG;3;PST
escandalitzar	escandalitzaries	V;COND;SG;2
magnetitzar	magnetitzessis	V;SBJV;SG;2;PST
xatejar	xatejarà	V;IND;SG;3;FUT
precisar	precisi	V;SBJV;SG;3;PRS
girar	giri	V;SBJV;SG;1;PRS
doblar	doblaré	V;IND;SG;1;FUT
harmonitzar	harmonitzéssiu	V;SBJV;PL;2;PST
remoldre	remoldrien	V;COND;PL;3
organitzar	organitzí	V;PFV;IND;SG;1;PST
profunditzar	profunditzaren	V;PFV;IND;PL;3;PST
xiuxiuejar	xiuxiuejaran	V;IND;PL;3;FUT
publicar	publiqueu	V;IND;PL;2;PRS
assumir	assumirà	V;IND;SG;3;FUT
simplificar	simplificarien	V;COND;PL;3
fotografiar	fotografiàreu	V;PFV;IND;PL;2;PST
infondre	infonia	V;IPFV;IND;SG;1;PST
profunditzar	profunditzaves	V;IPFV;IND;SG;2;PST
trinxar	trinxaven	V;IPFV;IND;PL;3;PST
encoratjar	encoratgen	V;IND;PL;3;PRS
publicar	publica	V;IND;SG;3;PRS
pentinar	pentini	V;IMP;SG;3;POS
tronar	tronaríem	V;COND;PL;1
resistir	resisteixi	V;IMP;SG;3;POS
augmentar	augmentares	V;PFV;IND;SG;2;PST
votar	voteu	V;IMP;PL;2;POS
atacar	ataqueu	V;SBJV;PL;2;PRS
durar	duraran	V;IND;PL;3;FUT
perfeccionar	perfeccionà	V;PFV;IND;SG;3;PST
infiltrar	infiltrareu	V;IND;PL;2;FUT
donar	donaran	V;IND;PL;3;FUT
temptar	temptem	V;IMP;PL;1;POS
empapussar	empapussaríeu	V;COND;PL;2
callar	calli	V;IMP;SG;3;POS
posposar	posposaran	V;IND;PL;3;FUT
escriure	escrigué	V;PFV;IND;SG;3;PST
aproximar	aproximarem	V;IND;PL;1;FUT
funcionar	funcioneu	V;IMP;PL;2;POS
aidar	aidar	V;NFIN
disparar	disparés	V;SBJV;SG;1;PST
atendre	atengui	V;SBJV;SG;1;PRS
titubar	titubis	V;SBJV;SG;2;PRS
assecar	assecàreu	V;PFV;IND;PL;2;PST
regnar	regnava	V;IPFV;IND;SG;3;PST
preocupar	preocupeu	V;IMP;PL;2;POS
adormir	adormiran	V;IND;PL;3;FUT
llançar	llança	V;IMP;SG;2;POS
excel·lir	excel·lireu	V;IND;PL;2;FUT
vetar	vetis	V;SBJV;SG;2;PRS
menysprear	menyspreava	V;IPFV;IND;SG;1;PST
pretendre	pretendrem	V;IND;PL;1;FUT
assolar	assolaràs	V;IND;SG;2;FUT
heretar	hereti	V;SBJV;SG;1;PRS
conjuntar	conjuntàreu	V;PFV;IND;PL;2;PST
endur-se	s'enduu	V;IND;SG;3;PRS
cremar	cremàrem	V;PFV;IND;PL;1;PST
seure	seureu	V;IND;PL;2;FUT
cessar	cessi	V;IMP;SG;3;POS
daurar	dauraries	V;COND;SG;2
prestar	prestaran	V;IND;PL;3;FUT
enllaçar	enllacéssim	V;SBJV;PL;1;PST
impulsar	impulsaries	V;COND;SG;2
adoptar	adoptaren	V;PFV;IND;PL;3;PST
alternar	alternaré	V;IND;SG;1;FUT
irritar	irrités	V;SBJV;SG;3;PST
coronar	coronaria	V;COND;SG;3
finançar	financem	V;IMP;PL;1;POS
buidar	buidin	V;SBJV;PL;3;PRS
sumar	sumarem	V;IND;PL;1;FUT
espiar	espiem	V;IMP;PL;1;POS
pactar	pactava	V;IPFV;IND;SG;1;PST
encoratjar	encoratjarem	V;IND;PL;1;FUT
tòrcer	torci	V;SBJV;SG;1;PRS
empitjorar	empitjoraria	V;COND;SG;3
manifestar	manifestin	V;SBJV;PL;3;PRS
difamar	difamin	V;IMP;PL;3;POS
destinar	destinaràs	V;IND;SG;2;FUT
proporcionar	proporcioneu	V;SBJV;PL;2;PRS
envoltar	envoltava	V;IPFV;IND;SG;3;PST
escollir	escolliren	V;PFV;IND;PL;3;PST
foradar	foradéssim	V;SBJV;PL;1;PST
afectar	afectaria	V;COND;SG;3
preguntar	preguntàrem	V;PFV;IND;PL;1;PST
arribar	arribem	V;IMP;PL;1;POS
embriagar-se	embriago	V;IND;SG;1;PRS
confeccionar	confeccioneu	V;IMP;PL;2;POS
crucificar	crucificava	V;IPFV;IND;SG;3;PST
